### ISSUE TITLE
solve_linear_system is now deprecated

### ISSUE THREAD

**Issue by aktech** [sympy/sympy#10001]
`solve_linear_system` is now deprecated. Use `linsolve` instead.

This is the Deprecation Removal issue for the same. See #10000

**Comment by oscarbenjamin** [comment]
The `solve_linear_system` function is still in use in `solve` and by users and does not have any deprecation warning so it can not be removed. Looks like #10000 did not get finished.

**Comment by oscarbenjamin** [comment]
gh-18814
