### ISSUE TITLE
set attribute 'is_integer' for Indexed / IndexedBase object

### ISSUE THREAD

**Issue by spjammy** [sympy/sympy#10012]
> > > temp = IndexedBase('t')
> > > setattr(temp,'is_integer', true)

this throws me an error

AttributeError: can't set attribute

Any help, is appreciated

**Comment by oscarbenjamin** [comment]
SymPy objects are usually immutable so you can't set attributes on them. To set assumptions on a symbol you should do it while creating the symbol:
```
In [12]: x = Symbol('x', integer=True)                                                                                                         

In [13]: sin(x*pi)                                                                                                                             
Out[13]: 0
```
There's nothing to fix here so closing...
