### ISSUE TITLE
Wrong output of `srepr' for unicode symbol (Python2 only)

### ISSUE THREAD

**Issue by haimoz** [sympy/sympy#10021]
If a symbol is constructed using a unicode string, then `srepr' for this symbol fails to wrap the symbol name with single quotes and the leading 'u', as would for symbols constructed using an ASCII string.  Try the following:

```
>>> srepr(Symbol('x'))
Symbol('x')
>>> srepr(Symbol(u'x'))
Symbol(x)
>>> Symbol('x') == Symbol(u'x')
True
>>> eval(srepr(Symbol('x')))  # should return Symbol('x')
x
>>> eval(srepr(Symbol(u'x')))  # shoudl return Symbol(u'x')
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/sympy/core/symbol.py", line 77, in __new__
    return Symbol.__xnew_cached_(cls, name, **assumptions)
  File "/usr/local/lib/python2.7/dist-packages/sympy/core/cache.py", line 93, in wrapper
    r = func(*args, **kw_args)
  File "/usr/local/lib/python2.7/dist-packages/sympy/core/symbol.py", line 81, in __new_stage2__
    raise TypeError("name should be a string, not %s" % repr(type(name)))
TypeError: name should be a string, not <class 'sympy.core.symbol.Symbol'>
```

It appears that for a unicode string at [sympy/printing/printer.py#L254](https://github.com/sympy/sympy/blob/113cce5a3f53b86657da99b5af737f1dfb04ba63/sympy/printing/printer.py#L254), the possible printers are `unicode`, `basestring`, and `object`.  Somehow, for a unicode string, all these printers are not supported, and as a result, an empty printer is used in [line 260](https://github.com/sympy/sympy/blob/113cce5a3f53b86657da99b5af737f1dfb04ba63/sympy/printing/printer.py#L260), which runs to [sympy/printing/repr.py#L45](https://github.com/sympy/sympy/blob/113cce5a3f53b86657da99b5af737f1dfb04ba63/sympy/printing/repr.py#L45), and results in the plain string without wrapping with single quotes.  The issue might be fixed with using `repr` instead of `str` in [sympy/printing/repr.py#L45](https://github.com/sympy/sympy/blob/113cce5a3f53b86657da99b5af737f1dfb04ba63/sympy/printing/repr.py#L45).  However, I do not have sufficient understanding of the sympy internals to know all possible consequences of doing this.  Could anyone kindly look into this and suggest whether this is the right fix?  Thanks a lot!

**Comment by haimoz** [comment]
Just found out that this issue only happens in python2.  In python3:

```
>>> from sympy import *
>>> srepr(Symbol('x'))
"Symbol('x')"
>>> srepr(Symbol(u'x'))
"Symbol('x')"
```

**Comment by oscarbenjamin** [comment]
This is fixed in Python 2 as well:
```
In [10]: srepr(Symbol(u'x'))                                                                                                                   
Out[10]: "Symbol('x')"
```
(the u prefix is still not there though)

**Comment by jksuom** [comment]
It looks like this was fixed by the recent commit https://github.com/sympy/sympy/commit/f7db65d156836e9fbabcc9c7b8aa004907a6d9b6#diff-cf1b02148933ebf37fafd7f65eb14da4 and can probably be closed.
