### ISSUE TITLE
str() printer for sets should give re-creatable representations

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#10035]
```
In [20]: str(S.Naturals)
Out[20]: 'Naturals()'

In [21]: str(S.Reals)
Out[21]: '(-oo, oo)'

In [22]: str(S.Complexes)
Out[22]: 'Complexes(Lambda((_x, _y), _x + _y*I), (-oo, oo) x (-oo, oo))'
```

For the first one, `Naturals` is not in the namespace from `from sympy import *`. For the second one, it would just create a tuple. For the third one, the product set is printed with an `x`, which is not valid Python syntax.  There may be other examples as well. In general, `str()` should give you something that you can copy and paste, and the more fancy printing should be left to `pprint()`.

**Comment by mickyaero** [comment]
I would like to work on this bug. Any hints would be appreciated

**Comment by asmeurer** [comment]
The Reals one is probably the easiest to fix. One should change the printing of Reals and Interval in StrPrinter in sympy/printing/str.py and move the existing printer to the pretty printer in sympy/printing/pretty/pretty.py.

**Comment by mickyaero** [comment]
I ran the following:-
>>> str(S.Reals)
(-oo, oo)

Correct me if i am wrong, the output doesn't seem to be string. So do i need to change something in here

**Comment by asmeurer** [comment]
`str` always returns a string. Where did you run this?

**Comment by mickyaero** [comment]
Ok ..Ok , i got confused as in the comment done on 25th october, the result displayed was quoted, but now i ran this in i sympy it didnt show any quotes. Now i checked the type it was string.
Could you please guide me where to find the S.Reals , i couldnt find it in sympy/printing/str.py?

**Comment by asmeurer** [comment]
Reals itself is defined in sympy/sets, but you should add the printer to sympy/printing/str.py, like

```
    def _print_Reals(self, p):
        ...
```

You can emulate how the other methods are defined in that file.

**Comment by asmeurer** [comment]
And `_print_Interval` is already defined there. So it should be changed to print a Python representation, and the current printer moved to `pretty.py`.

**Comment by mickyaero** [comment]
What is expected to print if i run " str(S.Reals)"?

**Comment by asmeurer** [comment]
I would expect `"S.Reals"`.

**Comment by mickyaero** [comment]
I wrote 4 functions in str.py :-_

    def _print_Reals(self, p):
        return "S.Reals"

    def _print_Naturals(self, p):
        return "S.Naturals"

    def _print_Complexes(self, p):
        return "S.Complexes"

    def _print_EmptySet(self, p):
        return "S.EmptySet"

But i am getting the error on running the test on str.py :-
assert str(Complement(S.Reals, S.Naturals)) == '(-oo, oo) \ Naturals()'
AssertionError


I am not able to resolve the error

**Comment by asmeurer** [comment]
You will need to update the tests.

**Comment by mickyaero** [comment]
I updated the test_str.py. But the Travis Cl gave a lot failures, most of them were because i created new functions which return something else,
like the  "def _print_EmptySet(self, p):"
returns "S.EmptySet".
This function was used in many other files and they were expecting something else but got this.
So, what should i do?

**Comment by asmeurer** [comment]
You will need to update the all the tests that have changed.

**Comment by mickyaero** [comment]
I got this error

"" sympy/printing/pretty/tests/test_pretty.py:test_pretty_ConditionSet ______

  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/sympy-1.0.1.dev0-py2.7.egg/sympy/printing/pretty/tests/test_pretty.py", line 3279, in test_pretty_ConditionSet

    assert pretty(ConditionSet(x, Eq(sin(x), 0), S.Reals)) == ascii_str

AssertionError""

where
ascii_str = "S.Reals"

**What should be there instead of ascii_str?**

**Comment by asmeurer** [comment]
It should be the actual output of `pretty(ConditionSet(x, Eq(sin(x), 0), S.Reals), use_unicode=False)`.

**Comment by manpreetsjsu** [comment]
if this issue is still unresolved and open, I would like to contribute....please give starting hint or idea..

**Comment by gxyd** [comment]
Closing this issue, fixed by https://github.com/sympy/sympy/pull/12112.
