### ISSUE TITLE
Indexed Object Latex printing, wrong if base label  has a subscript

### ISSUE THREAD

**Issue by spjammy** [sympy/sympy#10048]
If the base label has subscripts, then the Indexed object latex format throw double subscript error.

 This change removes the error

def _print_Indexed(self, expr):
-        tex = self._print(expr.base)+'_{%s}' % ','.join(
-        tex = '{%s}'%self._print(expr.base)+'_{%s}' % ','.join(
           map(self._print, expr.indices))
       return tex

**Comment by oscarbenjamin** [comment]
Did this turn into a PR?

**Comment by smichr** [comment]
It must have -- this is the definition now mod string wrangling:
```python
    def _print_Indexed(self, expr):
        tex_base = self._print(expr.base)
        tex = '{'+tex_base+'}'+'_{%s}' % ','.join(
            map(self._print, expr.indices))
        return tex
```
