### ISSUE TITLE
solve(sin(x) < 2) is wrong

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#10047]
```
In [24]: solve(sin(x) < 2)
Out[24]: False

In [27]: solveset.solveset(sin(x) < 2, domain=S.Reals)
Out[27]: ∅
```

The answer should be all real x. Note, this is from the Wester paper (N13).

**Comment by gxyd** [comment]
The problem occurs on [this line](https://github.com/sympy/sympy/blob/master/sympy/solvers/inequalities.py#L438-L441) . The same thing that `sin(oo).n()`. returns `nan`.
Can you please tell what is "Wester paper"? (may be a link to that)

**Comment by asmeurer** [comment]
See sympy/core/tests/test_wester.py.

**Comment by asmeurer** [comment]
How does it end up substituting oo? There is no oo in the original problem.

**Comment by gxyd** [comment]
> How does it end up substituting oo? There is no oo in the original problem.

It substitutes the `start(=S.NegativeInfinity)`[on this line](https://github.com/sympy/sympy/blob/master/sympy/solvers/inequalities.py#L443) into `e`(the original expression) , the substitution takes [on this line](https://github.com/sympy/sympy/blob/master/sympy/solvers/inequalities.py#L428) then `sin(oo) - 2` is checked for `(sin(oo) - 2).n)()` which is `nan` hence is `.is_comparable`[on this line](https://github.com/sympy/sympy/blob/master/sympy/solvers/inequalities.py#L439) is `false` and `False` is returned as the output.

**Comment by asmeurer** [comment]
I don't really understand how the algorithm works, but substituting oo seems wrong.
