### ISSUE TITLE
sympy.vector del prints as .del but is accessed as .delop

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#10045]
```
In [44]: N.delop
Out[44]: N.del
```

It should print the same as it is accessed.

**Comment by asmeurer** [comment]
Since delop has already been in a release I would recommend changing the printing.

**Comment by SpeedyiiiTH** [comment]
In this issue we only have to put a function.
def del(self):
     return self._del

Is this all we need to add in this issue??
@asmeurer

**Comment by asmeurer** [comment]
No, the function name should stay the same. The printing should change.

**Comment by SpeedyiiiTH** [comment]
ok. Let me try once.

**Comment by SpeedyiiiTH** [comment]
I want to ask what does it really mean by your statement that.
**It should print the same as it is accessed. **

As when we are accessing the delop function, we are ourself returning self._del.

I'm really not clear on this, please guide me through this.

**Comment by asmeurer** [comment]
I mean it prints as `N.del` but if you type that, it gives an AttributeError. It should print as `N.delop`.

**Comment by SpeedyiiiTH** [comment]
I got this from your words that:
if I type:
` N.del` it should give me `N.delop`

and on giving `N.delop` its giving `N.del` which is good.

am I getting you correct?

**Comment by asmeurer** [comment]
There should be no `N.del`. It should print as `N.delop`, because that's what it actually is.

**Comment by SpeedyiiiTH** [comment]
It means in both cases either I type `N.del` or `N.delop` it should always give `N.delop`.

Or you want to say that there should be nothing of  kind `N.del` meaning .del should not be defined.

**Comment by asmeurer** [comment]
There should be no `N.del`.

**Comment by SpeedyiiiTH** [comment]
So this is the thing you wanted to be done here.

```
>>> from sympy.vector import *
>>> N = CoordSysCartesian('N')
>>> N.delop
N.delop
>>> N.del
  File "<stdin>", line 1
    N.del
        ^
SyntaxError: invalid syntax
```
Is this all we need to do?

**Comment by asmeurer** [comment]
All you need to do is this

```
>>> N.delop
N.delop
```

**Comment by SpeedyiiiTH** [comment]
So, I think I have Implemented that.

now should I drop a pull request?
or do you need to check the code changed first.

If I'm to send a pull request, Please guide me to do so as I hadn't created any pull request till now.
Thanks.

**Comment by tyagi-prashant** [comment]
SpeedyiiiTH: you can send pull request by cloning a latest git  repository , prepare a branch with your code upload it somewhere. after that send a link to your upload to sympy mailing list so that sympy members can review your work.

**Comment by leosartaj** [comment]
@tyagi-prashant @SpeedyiiiTH We prefer Github for sending pull requests. Read [this](https://github.com/sympy/sympy/wiki/Development-workflow) to get started.

**Comment by asmeurer** [comment]
I can't check the code until you send a pull request, so that's what you should do.

**Comment by SpeedyiiiTH** [comment]
I had made a pull request,
have a review of that and let me know if something more needed to be implemented.

**Comment by tyagi-prashant** [comment]
@asmeurer i made a pull request for this issue.
please review it, so that i could get to know if something went wrong

**Comment by asmeurer** [comment]
@tyagi221295 there is already a pull request by @VinaySingh035 at https://github.com/sympy/sympy/pull/10059 (in the future, to both of you, please actually paste the pull request link instead of just writing "I made a pull request").

**Comment by asmeurer** [comment]
Oh and I completely missed that `del` is a keyword. So `N.del` is actually impossible.

**Comment by asmeurer** [comment]
I merged https://github.com/sympy/sympy/pull/10059.
