### ISSUE TITLE
init_printing() doesn't seem to do anything on cloud.sagemath.com

### ISSUE THREAD

**Issue by moorepants** [sympy/sympy#10040]
See this notebook:

https://cloud.sagemath.com/projects/ebb30a0f-930e-45a6-b727-53df0c36a484/files/sympy%20printing%20test.html

It would typically enable LaTeX enabled pretty printing for SymPy objects.

@williamstein

**Comment by williamstein** [comment]
works fine now.

https://cloud.sagemath.com/projects/4a5f0542-5873-4eed-a85c-a18c706e8bcd/files/support/sympy%20printing%20test.html
