### ISSUE TITLE
linsolve does not find solutions that solve_linear_system does

### ISSUE THREAD

**Issue by MooVI** [sympy/sympy#10056]
For some overdetermined systems, `linsolve` does not find solutions which `solve_linear_system` does. For example:

```python
In [12]: from sympy.solvers.solveset import linsolve
from sympy import *

A, B, J1, J2 = symbols('A B J1 J2')

augmatrix = Matrix([
    [ 2*I*J1,  2*I*J2,-2/J1],
    [-2*I*J2, -2*I*J1, 2/J2],
    [ 0,  2, 2*I/(J1*J2)],
    [2, 0,  0],
])

linsolve(augmatrix, A, B)
solve_linear_system(augmatrix, A, B)

Out[16]: EmptySet()

Out[17]: {A: 0, B: I/(J1*J2)}
```
On the other hand:

```python
In [23]: augmatrix = Matrix([
    [2*I*J2,-2/J1],
    [-2*I*J1, 2/J2],
    [ 2, 2*I/(J1*J2)],
])

linsolve(augmatrix, A)
solve_linear_system(augmatrix, A)

Out[24]: {(I/(J1*J2),)}

Out[25]: {A: I/(J1*J2)}
```

works fine.

I understand that this issue is problematic because `solve_linear_system` is being deprecated in favour of  `linsolve`: #10000.

**Comment by asmeurer** [comment]
@aktech @hargup

**Comment by MooVI** [comment]
On further investigation, this issue is not restricted to just overdetermined systems. Here is an example of an undetermined system for which `solve_linear_system` (and Mathematica) find solutions but `linsolve` does not:
```python
In [18]: V, f, J = symbols('V f J')
freevars_gen = numbered_symbols('x')
free_vars = [next(freevars_gen) for i in range(17)]
m = Matrix([
[     0,      0,      0,  2*I*J,     0, -2*I*J,  2*I*J,  2*I*J,  2*I*f,          0,           0,           0,   0,   0,      0,      0,          0,                   2*I*V**2*f**3/J**4],
[-2*I*J,      0,      0,      0, 2*I*J,      0, -2*I*J, -2*I*J,      0,          0,           0,           0,   0,   0,      0,      0,          0,               4*I*V**2*f**3/(3*J**4)],
[ 2*I*J,  2*I*J,      0,      0,     0, -2*I*J,  2*I*J,      0, -2*I*f,          0,           0,           0,   0,   0,  2*I*f,      0,          0,               8*I*V**2*f**3/(3*J**4)],
[-2*I*J, -2*I*J, -2*I*J,      0, 2*I*J,      0,      0,      0,      0, 2*I*V**2/f, -4*I*V**2/f, -2*I*V**2/f, 2*V, 2*V,      0, -2*I*f, 2*I*V**2/f, 2*I*V**2*f*(-2*V**2 + f**2)/(3*J**4)],
[     0,      0, -2*I*J, -2*I*J, 2*I*J,      0,      0, -2*I*J,      0,          0,           0,           0,   0,   0,      0,  2*I*f,          0,                  -4*I*V**2*f**3/J**4],
[     0, -2*I*J,      0, -2*I*J, 2*I*J,      0, -2*I*J,      0,      0,          0,           0,           0,   0,   0,      0,      0,          0,              -8*I*V**2*f**3/(3*J**4)],
[     0,  2*I*J,  2*I*J,  2*I*J,     0, -2*I*J,      0,      0,      0, 2*I*V**2/f, -4*I*V**2/f, -2*I*V**2/f, 2*V, 2*V, -2*I*f,      0, 2*I*V**2/f,   4*I*V**2*f*(-V**2 + f**2)/(3*J**4)],
[ 2*I*J,      0,  2*I*J,      0,     0, -2*I*J,      0,  2*I*J,      0,          0,           0,           0,   0,   0,      0,      0,          0,                                    0]])

solve_linear_system(m,*free_vars)
linsolve(m, *free_vars)

Out[22]: 
{x0: x4 - x6 - x7 - 2*V**2*f**3/(3*J**5),
 x5: x4 + f*x14/(2*J) - 5*V**2*f**3/(6*J**5),
 x8: x14 - x15 - 2*V**2*f**2/J**4,
 x3: x4 - x6 - x7 - f*x14/(2*J) + f*x15/J + 13*V**2*f**3/(6*J**5),
 x1: x7 + f*x14/(2*J) - f*x15/J - 5*V**2*f**3/(6*J**5),
 x2: x6 + f*x14/(2*J) - V**2*f**3/(6*J**5),
 x9: 2*x10 + x11 - x16 + I*f*x12/V + I*f*x13/V + f**2*x14/V**2 - 2*V**2*f**2/(3*J**4) - 4*f**4/(3*J**4)}

Out[23]: EmptySet()
```

On the other hand, I have found a matrix equation which `linsolve` solves but for which `solve_linear_system` hangs indefinitely (an issue I am not reporting since it's being deprecated), so just using `solve_linear_system` is not a good workaround even before it is deprecated.

**Comment by MooVI** [comment]
The problem is with this [line] (https://github.com/sympy/sympy/blob/f865a088d2b717f3840a4814cb4660f31af8f84a/sympy/matrices/matrices.py#L4320)

```python
A, pivots = aug.rref()
```

If you change that to:

```python
A, pivots = aug.rref(simplify=True)  
```

Then: 

```python
augmatrix = Matrix([
    [ 2*I*J1,  2*I*J2,-2/J1],
    [-2*I*J2, -2*I*J1, 2/J2],
    [ 0,  2, 2*I/(J1*J2)],
    [2, 0,  0],
])

linsolve(augmatrix, A, B)
solve_linear_system(augmatrix, A, B)

{(I*J2*(2/J2 - 2*J2/J1**2)/(2*(-J1**2 + J2**2)) + I/J1**2, -I*J1*(2/J2 - 2*J2/J1**2)/(2*(-J1**2 + J2**2)))}

{B: I/(J1*J2), A: 0}
```

which are the same solutions, although `solve_linear_system` give them in simpler form (but one could always call `simplify` on the results of `linsolve`).

Perhaps the arguments of rref (`iszerofunc` and `simplify`) should be made available from `linsolve`? I really think the default should at least be `simplify=True`, as one would expect symbolic solving to work by default.

**Comment by aktech** [comment]
> Perhaps the arguments of rref (iszerofunc and simplify) should be made available from linsolve? 

I think that would probably complicate the input API.

>  I really think the default should at least be simplify=True, as one would expect symbolic solving to work by default.

That seems like a better idea.

**Comment by MooVI** [comment]
OK. I merely wondered whether giving the choice would be good because of the answer asmeurer gave in [this stackoverflow question] (http://stackoverflow.com/questions/19072700/why-does-sympy-give-me-the-wrong-answer-when-i-row-reduce-a-symbolic-matrix):

> The option is off by default because in general such simplification can be expensive, through this can be controlled by passing in a less general simplify function than simplify (for rational functions, use cancel).

What do you think about linsolve calling simplify on its results as well? It does give much more complex solutions than `solve_linear_system` does.

**Comment by aktech** [comment]
@MooVI  The problem with such flags is that, if the user is not aware of them he would be getting `EmptySet()` & we would not like to have the result of `linsolve` dependent on flags.

> What do you think about linsolve calling simplify on its results as well? It does give much more complex solutions than solve_linear_system does.

Yeah, that's better Indeed.
