### ISSUE TITLE
Code coverage report on README.rst?

### ISSUE THREAD

**Issue by Newman101** [sympy/sympy#10061]
Hi all.

Is it possible to get code coverage report to README file? 

Coveralls (https://coveralls.io/) does provide free coverage report for open source projects.

Thanks.

**Comment by moorepants** [comment]
I think people have worked on this some. There was a sympy coveralls account at some point. Feel free to set it up. You may want to search the mailing list and github to find other references. I don't think there will be any objection to adding it and it would be nice to know the number. But I don't think we should make it a strict goal to get 100% coverage.

**Comment by asmeurer** [comment]
I tried it at https://github.com/sympy/sympy/pull/1960 but it was a mess because of mpmath. It should be easier now that we don't use it, though. 

If you want to do this and need me to perform any actions on coveralls (since you don't have push access) just let me know.

**Comment by oscarbenjamin** [comment]
We now have coverage from codecov.io
