### ISSUE TITLE
key error for solveset_real

### ISSUE THREAD

**Issue by smichr** [sympy/sympy#10069]
The following generates a key error

```python
>>> sympy.solvers.solveset.solveset_real(x + 1 > 0,  x)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "sympy\solvers\solveset.py", line 508, in solveset_real
    for g in equation.args):
  File "sympy\solvers\solveset.py", line 508, in <genexpr>
    for g in equation.args):
  File "sympy\solvers\solveset.py", line 658, in _has_rational_power
    if pattern_match is None or pattern_match[a] is S.Zero:
KeyError: a_
```

**Comment by hargup** [comment]
`solveset_real` is meant to be only used through the high level wrapper `solveset` with the `domain=S.Reals` argument. In case an inequality is passed to it, it calls the appropriate inequality solver. We should make this clear in the doc-string and maybe we should make `solveset_real` a private function.

**Comment by smichr** [comment]
For efficiency sake, I beleive that's a good idea (to make all but `solveset` private): `solveset` gets args into shape and dispatches to the appropriate helper.
