### ISSUE TITLE
X.pdf(x) for Symbol x returns 0

### ISSUE THREAD

**Issue by gxyd** [sympy/sympy#10075]
```
>>> x = Symbol('x')
>>> from sympy.stats.frv_types import DieDistribution
>>> X = DieDistribution(6)
>>> X.pdf(x)
0
```
Either this should raise a `ValueError` or unevaluated. Returning unevaluated seems more favourable.

**Comment by jksuom** [comment]
``X`` is a uniform discrete distribution with value 1/6 at each point of its space {1, 2, ..., 6}. This could be returned. (And maybe ``ValueError`` for invalid argument values.)
