### ISSUE TITLE
Website says "SymPy is written entirely in Python and does not require any external libraries.", but then "SymPy now depends on mpmath as an external library."

### ISSUE THREAD

**Issue by TomasRiker** [sympy/sympy#10081]
SymPy's main website says:

> SymPy is written entirely in Python and does not require any external libraries.

But then, when trying to import SymPy, I get the error:

> SymPy now depends on mpmath as an external library.

Isn't that a contradiction?

**Comment by debugger22** [comment]
Yes, it is. Website should be updated. Thanks for pointing it out!

**Comment by TomasRiker** [comment]
Well, at least mpmath doesn't have additional dependencies, and it is also fully written in Python, so no need to install any binary libraries. :)

**Comment by moorepants** [comment]
Yes, we are still purely python dependent, but the next release (1.0) will introduce dependencies. The current release, 0.7.6, does not require deps as mpmath is included. So the website needs to be updated for the next release. You must be installing the dev version.

**Comment by asmeurer** [comment]
https://github.com/sympy/sympy.github.com/pull/86

**Comment by asmeurer** [comment]
Also https://github.com/sympy/sympy/pull/10527
