### ISSUE TITLE
unxfail tests in test_eval_power.py

### ISSUE THREAD

**Issue by gxyd** [sympy/sympy#10096]
[These lines in test_eval_power.py](https://github.com/sympy/sympy/blob/master/sympy/core/tests/test_eval_power.py#L338-L344) now pass in master. So `@XFAIL` can be removed.

**Comment by gxyd** [comment]
@debugger22 please have a look(for validity of issue)

**Comment by leosartaj** [comment]
Looks valid to me.

**Comment by kshitij10496** [comment]
@gxyd I would like to work on this

**Comment by gxyd** [comment]
Sure you can go head.

**Comment by kshitij10496** [comment]
I will be sending a PR soon
