### ISSUE TITLE
simplify((1/(2*E))**oo) returns `nan`

### ISSUE THREAD

**Issue by gxyd** [sympy/sympy#10095]
```
>>> (1/(2*E))**oo
(1/(2*E))**oo
>>> simplify((1/(2*E))**oo)
nan
>>> powsimp((1/(2*E))**oo)
(1/(2*E))**oo
```

**Comment by leosartaj** [comment]
This works,

```
>>> limit((1/(2*E))**x, x, oo)
0
```

**Comment by gxyd** [comment]
@asmeurer was the automatic simplification of `1/(2*E)**oo`  is not done. Is that so because that makes the `core` slow? Or is that a bug?

**Comment by mohamedotnet** [comment]
>>> from sympy import *
>>> (1/(2*E))**oo
(exp(-1)/2)**oo
>>> simplify((exp(-1)/2)**oo)
nan

So, I don't think that it is a bug.. Perhaps you should calculate the limit instead.
