### ISSUE TITLE
fresnel limit to infinite gives wrong answer

### ISSUE THREAD

**Issue by cbm755** [sympy/sympy#10102]
```
>>> fresnels(oo)    # good

1/2

>>> fresnels(x).limit(x,oo)    # bad!

0
```

**Comment by cbm755** [comment]
Hmmm: `fresnels(x).limit(x,-oo)` correctly gives `-1/2`

**Comment by normalhuman** [comment]
What's more, multiplying the function by any constant makes the limit a correct one:
```
>>> limit(3*fresnels(x), x, oo)
3/2
```

Whereas adding a constant results in that constant disappearing:
```
>>> limit(3 + fresnels(x), x, oo)
0
```
