### ISSUE TITLE
Fresnel integrals contain gamma fcns and do not simplify enough

### ISSUE THREAD

**Issue by cbm755** [sympy/sympy#10101]
```
>>> y = sin(pi/2*t**2).integrate()
>>> pprint(y)

3⋅fresnels(t)⋅Γ(3/4)
────────────────────
      4⋅Γ(7/4)      

>>> pprint(simplify(y))

3⋅fresnels(t)⋅Γ(3/4)
────────────────────
      4⋅Γ(7/4)      
```

But the various constants are (correctly) just 1:

```
>>> pprint(N(y))

1.0⋅fresnels(t)
```

I haven't looked carefully, but one possibility is

```
>>> gamma(S(3)/4) / gamma(S(7)/4)

gamma(3/4)/gamma(7/4)

>>> simplify(gamma(S(3)/4) / gamma(S(7)/4))

gamma(3/4)/gamma(7/4)

>>> N(gamma(S(3)/4) / gamma(S(7)/4))

1.33333333333333
```

which is possibly related to #8156.

**Comment by jksuom** [comment]
It seems that the simplification of gamma functions should be developed further. It is currently done in ``combsimp`` that was originally developed for combinatorial functions. In #9785 I suggested that the gamma function part be moved to an new module ``gammasimp`` that would make it easier to concentrate on properties specific to the gamma function.

**Comment by Flexico** [comment]
I'm getting a similar problem, though integrate(sin(x**2),x) is giving a different answer (though still with gamma functions):
[code]>>> integrate(sin(x**2),x)
                      ⎛  ___  ⎞       
    ___   ___         ⎜╲╱ 2 ⋅x⎟       
3⋅╲╱ 2 ⋅╲╱ π ⋅fresnels⎜───────⎟⋅Γ(3/4)
                      ⎜   ___ ⎟       
                      ⎝ ╲╱ π  ⎠       
──────────────────────────────────────
               8⋅Γ(7/4)               [/code]
I'm using Linux Mint 18, with Python 2.7.12 and Sympy 0.7.6.1-1.
