### ISSUE TITLE
expression with multiple abs has partial solution returned

### ISSUE THREAD

**Issue by smichr** [sympy/sympy#10122]
Here is the right answer (confirmed graphically)

``` python
>>> solve(abs(x)+abs(x-1)-1>0,x)
Or(And(-oo < x, x < 0), And(1 < x, x < oo))
```

Here are ways to get the wrong answer:

``` python
>>> solve(Piecewise((x,x>=0),(-x,True))+Piecewise((x-1,x>=1),(1-x,True))-1>0,x)
And(1 < x, x < oo)

>>> solveset(Piecewise((x,x>=0),(-x,True))+Piecewise((x-1,x>=1),(1-x,True))-1>0,
x,domain=S.Reals)
(1, oo)

>>> solveset(abs(x)+abs(1-x)-1>0,x,domain=S.Reals)
(1, oo)
>>>
```

**Comment by meghana1995** [comment]
Even these seem to be giving wrong answers:

>>> solve(abs(x)+abs(x-1) -1, x)
[1]
>>> solve(Piecewise((x,x>=0),(-x,True))+Piecewise((x-1,x>=1),(1-x,True))-1, x)
[1]

The answer for both cases should be [0, 1]

**Comment by meghana1995** [comment]
The piecewise_fold() in solvers returns the following function
 list: [Piecewise((Piecewise((2*x - 2, x >= 1), (0, True)), x >= 0), (Piecewise((-2, x >= 1), (-2*x, True)), True))]

When Piecewise((2*x - 2, x >= 1), (0, True)) is solved, it doesn't consider 0 as a solution even though it satisfies (0, True). I think that seems to be the issue.

**Comment by meghana1995** [comment]
Is someone else working on this or should I go ahead and try to fix it ?

**Comment by Shekharrajak** [comment]
```
>>> solve(abs(x)+abs(x-1)-1>0,x)
```
raises 
`NotImplementedError: can't solve inequalities with absolute values of a complex variable`
means `SymPy`  did not find any solutions.
We can't check `solveset` using Sympy live ,right ?
