### ISSUE TITLE
inverse_laplace_transform value error

### ISSUE THREAD

**Issue by proy87** [sympy/sympy#10123]
`inverse_laplace_transform(20/(s**3 - 2*pi*s**2), s, t)` raises `ValueError: too many values to unpack`

**Comment by jksuom** [comment]
SymPy's integrator finds a hypergeometric function representing the transform, and then tries to express that in terms of more tractable functions, Lerch's transcendents in this case.

The new expression is derived from the partial fractions of the coefficients of the hypergeometric function. ``try_lerch`` applies [``apart``](https://github.com/sympy/sympy/blob/master/sympy/simplify/hyperexpand.py#L1766) for this purpose. By default, it is intended for denominators with rational roots only:
```
    The undetermined coefficients method (selected by ``full=False``) uses
    polynomial factorization (and therefore accepts the same options as
    factor) for the denominator. Per default it works over the rational
    numbers, therefore decomposition of denominators with non-rational roots
    (e.g. irrational, complex roots) is not supported by default (see options
    of factor).

    Bronstein's algorithm can be selected by using ``full=True`` and allows a
    decomposition of denominators with non-rational roots. A human-readable
    result can be obtained via ``doit()`` (see examples below).
```
In the case at hand there is a ``pi`` in the denominator. If it is replaced with 1, there
will be no problem. For the general case it should be sufficient to add ``full=True``
to the ``apart`` call.

**Comment by oscarbenjamin** [comment]
Seems to work okay on master now:
```
In [5]: inverse_laplace_transform(20/(s**3 - 2*pi*s**2), s, t)                                                                                 
Out[5]: 
   ⎛         2⋅π⋅t    ⎞              
-5⋅⎝2⋅π⋅t - ℯ      + 1⎠⋅Heaviside(t) 
─────────────────────────────────────
                   2                 
                  π   
```
Does that look like the correct answer?

**Comment by jksuom** [comment]
At least the leading term`exp(2*pi*t)` looks qualitatively correct. It corresponds to the pole at `2*pi`.

**Comment by oscarbenjamin** [comment]
Seems to round trip okay with Laplace and inverse Laplace transforms:
```
In [2]: s, t = symbols('s t')                                                                            

In [3]: inverse_laplace_transform(20/(s**3 - 2*pi*s**2), s, t)                                           
Out[3]: 
   ⎛         2⋅π⋅t    ⎞              
-5⋅⎝2⋅π⋅t - ℯ      + 1⎠⋅Heaviside(t) 
─────────────────────────────────────
                   2                 
                  π                  

In [4]: laplace_transform(_, t, s)                                                                       
Out[4]: 
⎛     20            2⋅π    ⎞
⎜────────────, 2⋅π, ─── ≠ 1⎟
⎜ 2                  s     ⎟
⎝s ⋅(s - 2⋅π)              ⎠

```
