### ISSUE TITLE
Derivative of _diff_wrt object with itself doesn't evaluate

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#10150]
```
In [10]: class Test(Expr):
   ....:    _diff_wrt = True
   ....:

In [11]: t = Test()

In [12]: diff(t, t)
Out[12]:
   d
───────(Test())
dTest()

In [13]: diff(2*t, t)
Out[13]: 2

```

Marking as easy to fix because it probably is.

**Comment by asmeurer** [comment]
It's because it has no `_eval_derivative` method (the one on `Symbol` comes from `AtomicExpr`). You can work around this by defining it in a similar way. It seems like it should work automatically, though. At the very least, it should be documented that you have to do this.

**Comment by Curious72** [comment]
@asmeurer  do we have to make change to the sympy/core/expr.py : diff(self,*symbols,**assumptions)?
putting a special case inside diff method might work !! but after making changes i am getting errors on python shell , in importing sympy -> " sympy now depends on mpmath as an external library ...."

**Comment by vishnu93** [comment]
Hi, I made a fix for this which is adding the _eval_derivative in Expr class. Derivatives wrt itself is showing result one. I have the following doubts :
1 The test file test_diff.py breaks as we are checking the Expr class doesnt have a _eval_derivative method. Since are requirement is that this method should be present, should that test be modified?
2 Should _eval_derivative be removed from the subclasses of Expr (AtomicExpr) ?

**Comment by asmeurer** [comment]
@Curious72 you will need to install mpmath. We used to include it with SymPy but you now need to install it yourself. 

@vishnu93 Can you be more specific about which test you are referring to?

**Comment by vishnu93** [comment]
@asmeurer I'm referring to this test case under test_diff.py : 


def test_diff_no_eval_derivative():
    class My(Expr):
        def __new__(cls, x):
            return Expr.__new__(cls, x)

    x, y = symbols('x y')
    # My doesn't have its own _eval_derivative method
    assert My(x).diff(x).func is Derivative #This is the problem as diff wrt itself should be 0
    # it doesn't have y so it shouldn't need a method for this case
    assert My(x).diff(y) == 0

**Comment by asmeurer** [comment]
@vishnu93 wrap your code with ``` so that it renders properly (see https://guides.github.com/features/mastering-markdown/)

**Comment by asmeurer** [comment]
In any case, I'm still not following what you did. Can you show me the change you made, either by opening a pull request, or pasting the git diff here?

**Comment by kshitij10496** [comment]
@vishnu93 Are you still working on this ?

**Comment by kshitij10496** [comment]
I am working on this
