### ISSUE TITLE
solve(x*Max(x, 15) - 10, x) doesn't work

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#10158]
`solve(x*Max(x, 15) - 10, x)` gives NotImplementedError. `solveset` can't solve it either. 

I think to solve equations like this, one should replace the Max with each argument and solve independently, then backtrack and remove any solutions where the Max argument is not actually the maximum. For instance, in this case, one would solve `x**2 - 10` and `x*15 - 10`. The first one gives `[sqrt(10), -sqrt(10)]`, but both of those solutions are invalid because they aren't the maximum in `Max(x, 15)`. The second gives `2/3`, which is the correct solution.

**Comment by smichr** [comment]
Perhaps rewriting as a Piecewise and resubmitting to `solve` rather than handling the solution in-place would be a way to go? The `piecewise_fold`would then take care of multiple Max/Min in the expression

`x*Max(x, 15) - Max(x, 10)` -> `Piecewise ((x**2, x>15), (15, True)) - Piecewise ((x, x>10), (10, True))` for which sympy says the solution is 15.

**Comment by asmeurer** [comment]
Yep, this seems to work

```
In [4]: solve(x*Piecewise((x, x >=15), (15, x < 15)) - 10, x)
Out[4]: [2/3]
```

So I guess the algorithm I hinted at is already implemented for Piecewise. You don't need to fold to solve multiple Piecewise, by the way, just check every combination of Piecewise args. 

It looks like Max.rewrite(Piecewise) isn't implemented. 

By the way, this is from http://stackoverflow.com/q/33803806/161801.

**Comment by smichr** [comment]
> You don't need to fold to solve multiple Piecewise, by the way, just check every combination of Piecewise args

That is now what `piecewise_fold` does.

**Comment by JosephMehdiyev** [comment]
This PR https://github.com/sympy/sympy/pull/29586 fixes the issue, suprisingly. 
Now,
```Python
solve(x*Max(x, 15) - 10, x) ## gives 2/3 instead of not implemented error
```
