### ISSUE TITLE
System of Equations

### ISSUE THREAD

**Issue by Nedaaaa** [sympy/sympy#10160]
I am trying to solve a system of linear equations which in matrix notation it is like below:
K -  w * M = 0
where K and M are known square matrices and I am trying to find the values for w.
Can I solve this matrix equation with SymPy??

**Comment by jksuom** [comment]
If you multiply the matrix equation by ``M**-1`` you get ``K*(M**-1) - w = 0``, i.e., ``w = K*(M**-1)``.

**Comment by Nedaaaa** [comment]
@jksuom 
Sorry, I made a mistake! actually I want to solve this equation:
det( K - w * M ) = 0

**Comment by asmeurer** [comment]
Is w a scalar or a square matrix?

**Comment by jksuom** [comment]
If ``w`` is to be a scalar, its possible values are the eigenvalues of ``K*(M**-1)``. Those are the roots of the characteristic polynomial and obtained from ``(K*M**-1).eigenvals()``.

**Comment by asmeurer** [comment]
You can also use `solve((A - w*M).det(), w)` directly.

**Comment by Nedaaaa** [comment]
@asmeurer 
w is an unknown variable which will be the roots of det( K - w * M ) = 0 equation.
actually w is a scalar but it would have n different value based on the size of the K and M matrices.

**Comment by Nedaaaa** [comment]
@jksuom 
What do you mean by K*(M**-1)?

**Comment by jksuom** [comment]
``K*(M**-1)`` is the matrix product of ``K`` and the inverse of ``M``.

**Comment by Nedaaaa** [comment]
@jksuom 
You are right! I hadn't noticed it!
Thank you so much.

**Comment by jksuom** [comment]
@Nedaaaa Maybe this could be closed?

**Comment by Nedaaaa** [comment]
@jksuom yes, I got my answer.
Thank you
