### ISSUE TITLE
improper numpy test?

### ISSUE THREAD

**Issue by benaxelrod** [sympy/sympy#10172]
It seems to me that line 166 of `sympy/external/tests/test_numpy.py` should be changed from this:

```
assert m + M == Matrix([[3, 5, 7], [2*x, y + 5, x + 6], [2*y + x, y - 50, z*x + z**2]])
```

to this:

```
assert (m + M == matrix([[3, 5, 7], [2*x, y + 5, x + 6], [2*y + x, y - 50, z*x + z**2]])).all()
```

**Comment by oscarbenjamin** [comment]
SymPy's matrix class doesn't work like Numpy's. Comparing matrices with == gives True or False (rather than an array of True/False). So this change isn't needed.
