### ISSUE TITLE
about using subs, replace

### ISSUE THREAD

**Issue by skstar** [sympy/sympy#10175]
I'm newbie of python and sympy.

I have a problem to use subs and replace

I tried to below code.

(x + 1/x).subs(1/x, x)
(x + 1/x).replace(1/x,x)

I expected 'x + 1/x'
but result was 2x

Am I wrong? or did I misunderstand about using subs?
Please help me.
Thanks.

**Comment by leosartaj** [comment]
``subs`` will find occurrences of ``1/x`` and replace them with ``x``.

This should work in your case

```
>>> (x + 1/x).subs(x, 1/x)
x + 1/x
```

Also checkout the docs for [subs](http://docs.sympy.org/latest/modules/core.html?highlight=subs#sympy.core.basic.Basic.subs) and [replace](http://docs.sympy.org/latest/modules/core.html?highlight=subs#sympy.core.basic.Basic.replace).

**Comment by leosartaj** [comment]
Feel free to reopen.
