### ISSUE TITLE
Make `rs_log` work with `rs_series`

### ISSUE THREAD

**Issue by shivamvats** [sympy/sympy#10189]
`rs_series` is the newer and faster series expansion method which calls elementary `rs` functions as required by parsing the input expression. However, it currently works with expressions involving sin, cos , exp and tan only. To make it recognize `rs_log` certain changes need to be made in `rs_log`.
Read the comments [here](https://github.com/sympy/sympy/blob/master/sympy/polys/ring_series.py#L1)

**Comment by VinaySingh035** [comment]
I would like to work on this issue.
@shivamvats  can you please help me understand what exactly do you want to be done in this issue.

until now what I got is that we have to use the ``rs_series`` somewhere inside ``rs_log`` so as to solve the rest of the part from the ``rs_series`` function. am I right or i missed something?

**Comment by shivamvats** [comment]
@VinaySingh035 I will be glad to help you.

I think I should rephrase the issue. You don't need to modify the algorithm of `rs_log`. `rs_series` is a wrapper function that parses an input expression and calls the elementary `rs_` functions whenever required. Currently, it can recognize only four functions(as mentioned in the file). You need to make it recognize `rs_log` also. For this, certain changes need to be made in `rs_log` which is explained in the comments in the file.

**Comment by tokencolour** [comment]
@VinaySingh035 Are you coming up with a PR on this?

**Comment by Shaswat27** [comment]
@shivamvats Can I work on this?

**Comment by VinaySingh035** [comment]
Initially I was working on this, but left in between.
So, If you like you can work on this. @Shaswat27.

**Comment by Shaswat27** [comment]
@VinaySingh035 Alright. 
@shivamvats Working on this one.

**Comment by Nitin216** [comment]
@shivamvats Can i also work on this one too?

**Comment by shivamvats** [comment]
@Nitin216 Sure! Talk to @Shaswat27 and together perhaps you can come up with a better solution.

**Comment by shivamvats** [comment]
PR #12274 solves this.
