### ISSUE TITLE
solve() can't solve a simple exponential expression

### ISSUE THREAD

**Issue by moorepants** [sympy/sympy#10181]
The following causes SymPy to start computing and doesn't finish within a couple of minutes. Seems like `solve()` should be able to do this.

```
moorepants@garuda:eme150a-website(master)$ ipython 
Python 3.5.0 |Continuum Analytics, Inc.| (default, Oct 19 2015, 21:57:25) 
Type "copyright", "credits" or "license" for more information.

IPython 4.0.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: from sympy import *

In [2]: var('x, y')
Out[2]: (x, y)

In [3]: eq = Eq(y, x**1.9783)

In [4]: eq
Out[4]: y == x**1.9783

In [5]: solve(eq, x)
```

**Comment by smichr** [comment]
Can you use nsolve instead? I think the floating exponent is going to be converted to a rational and you will get many (i.e. 10000)  roots. You can see what I mean by solving something like `y=x**1.2` which will give 5 roots.

**Comment by moorepants** [comment]
Yes I can use nsolve in this case. I guess I was assuming solve to do the numeric solve under the hood. I'll close this.
