### ISSUE TITLE
Clarification about srepr in the docs

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#10185]
Quoting from Gitter chat

> srepr gives the “repr” form, which is what reprwould normally give
but for SymPy we don’t actually use it for `__repr__` because it’s way too verbose
and on top of that when you print a list or a tuple it calls repr on the elements instead of str, so a list of sympy expressions would always have the repr output
that page should probably mention all of this. it could be a lot clearer
oh I guess that’s the tutorial. For the tutorial I would just replace the “repr” heading with “srepr”. But in the docs for srepr it should have the discussion about the repr builtin

We should rename the `repr` section in the tutorial to `srepr`, and add some in-depth discussion (basically what I wrote above) to the `srepr` docstring, which appears [here](http://docs.sympy.org/dev/modules/printing.html?highlight=srepr#sympy.printing.repr.srepr).

**Comment by VinaySingh035** [comment]
what exactly do you expect to be done in this issue??
as things aren't much clear from above statement.

**Comment by asmeurer** [comment]
Two things

1. Replace `repr` with `srepr` in the tutorial (`doc/src/tutorial` in the sympy source)
2. Add some discussion about `repr` and `__repr__` based on my quoted text above to the `srepr` docstring (which I linked to above).

**Comment by VinaySingh035** [comment]
do we have to replace it for all the file's `repr`  present  here in the tutorial directory of the source?

**Comment by asmeurer** [comment]
I think it's only mentioned once in the tutorial (in the printing section).

**Comment by VinaySingh035** [comment]
would be good for a newbie to start with.
so, leaving it.

**Comment by sampadsaha5** [comment]
I m going to fix it.
What else from the above quoting we need to add in the documentation ?
@asmeurer

**Comment by asmeurer** [comment]
https://github.com/sympy/sympy/pull/10225 fixed the tutorial but not the `srepr` docstring.

**Comment by ritz301** [comment]
@asmeurer I am going to fix this. What exactly do I need to add in the documentation?

**Comment by sampadsaha5** [comment]
@ritz301 
Actually I am still working on this issue.

**Comment by ritz301** [comment]
@sampadsaha5 Ok then, go ahead.

**Comment by sampadsaha5** [comment]
Thanks @ritz301

**Comment by sampadsaha5** [comment]
@asmeurer We are supposed to change the srepr docstring at [here](https://github.com/sympy/sympy/blob/master/doc/src/modules/printing.rst).
