### ISSUE TITLE
pprint  Matrix with characters E 

### ISSUE THREAD

**Issue by pedritomelenas** [sympy/sympy#10184]
If you try to latex print a matrix with characters and this character is E or I, the they are translated in LaTeX to lower case (with N will raise an error). The same issue in print.

```
In [15]: pprint(Matrix([["EE","E","N"]]))
[EE  ℯ  <function N at 0x104145b90>]
```
Notice the the `e` is translated to the exponential.

Thanks

**Comment by asmeurer** [comment]
This is a perfect example of why you should not use strings as input. SymPy (sometimes) converts strings to SymPy expressions automatically using `sympify`, but `sympify` will translate names of SymPy functions to those functions, and only unknown names are translated to Symbol objects. In this case, `E` is `exp(1)` and `N` is a function that numerically evaluates expressions. See https://github.com/sympy/sympy/wiki/Idioms-and-Antipatterns#strings-as-input for more information. 

To get what you want, use `Symbol("E")`, `Symbol("N")`, and so on explicitly.

**Comment by pedritomelenas** [comment]
Yes, I already used the symbols trick in my code. But for me this is a bug.

Enviado con Aquamail para Android
http://www.aqua-mail.com


El 1 de diciembre de 2015 4:36:55 p. m. Aaron Meurer 
<notifications@github.com> escribio:
