### ISSUE TITLE
solveset error when input is bool

### ISSUE THREAD

**Issue by smichr** [sympy/sympy#10197]
```python
>>> solveset(True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "sympy\solvers\solveset.py", line 899, in solveset
    free_symbols = f.free_symbols
AttributeError: 'bool' object has no attribute 'free_symbols'
```

**Comment by Curious72** [comment]
what should be the correct output?

**Comment by leosartaj** [comment]
As ``solveset`` returns solutions in the form of set. I think this should work fine.

```
>>> solveset(True)
S.UniversalSet
>>> solveset(False)
S.EmptySet
```

ping @aktech @hargup

**Comment by leosartaj** [comment]
Though I am not very sure about this.

**Comment by smichr** [comment]
I've got a fix in progress. Something that isn't clear to me is the ambiguity in what solveset is answering. If the expr is not a Relational then it should answer when expr=0, hence solveset(0) should be the domain. If expr is a Relational (or something that can be obtained from a Relational, i.e., True, False) then True should be the domain and False the EmptySet.  So 0 and 1 which are aliases to False and True in python represent ambiguous input:

```
>>> all(i in (True, False) for i in (0,1))
True
```

So if `1` is interpreted as an expr the answer should be EmptySet; but if it is interpreted as True (as the result of a Relational) then it should be `domain`. The same for 0: if an expression, then `domain` else `EmptySet` if it's interpreted as a bool. Perhaps a ValueError should be raised in these cases:

if sympified input is S.Zero or input is S.One 

```raise ValueError(filldedent('''Ambiguous input: in python 0 and 1 can represent 
booleans False and True or simple expressions. The return value of solveset is 
`domain` for expressions that are 0 but `EmptySet` for false relationals; 
similarily, `EmptySet` is returned for expressions that are 1 but `domain` for true 
relationals''')
```
