### ISSUE TITLE
Solution of "first order linear non-homogeneous ODE-System" is wrong

### ISSUE THREAD

**Issue by elDan101** [sympy/sympy#10201]
## Sympy:

```
eq = [Eq(Derivative(v1(t),t), -v1(t)+v2(t)+1), 
      Eq(Derivative(v2(t),t), -v1(t)-v2(t)),
      Eq(Derivative(v3(t),t), -v3(t))
     ]

sol = dsolve(eq)
```

##### Solution:
```
v1(t) == C2*exp(-t)*sin(t) - C3*exp(-t)*cos(t), 
v2(t) == C2*exp(-t)*cos(t) + C3*exp(-t)*sin(t), 
v3(t) == C1*exp(-t)
```

## Maple:
```
ode_sys := {diff(vx(t),t) = -vx(t)+vy(t)+1, 
           diff(vy(t),t) = -vx(t)-vy(t), 
           diff(vz(t),t) = -vz(t)}; 
dsolve(ode_sys);
```

##### Solution:
```
vx(t) = 1/2 + exp(-t) (sin(t) _C2 + cos(t) _C1), 
vy(t) = - 1/2 - exp(-t) (sin(t) _C1 - cos(t) _C2),
vz(t) = _C3 exp(-t)
```

With the initial condition v = (0,0,0) I get 3 zero functions in sympy. The first two in Maple are non-zero due to the extra terms 1/2.    

I solved the system also by hand and agree with Maple. It seems that sympy solves the homogenous ode (ignoring the inhomogeneous part). I assume sympy can also solve inhomogenous systems or would throw an error when I try to do so in case it is not supported. 

Note: I am new to Sympy so there is a bigger chance that I used it wrong.

**Comment by nagarakshay** [comment]
I would like to work on this.

**Comment by nagarakshay** [comment]
@asmeurer @cbm755  Please tell me if anything else needs to be done!!
PR #10830

**Comment by smichr** [comment]
OK, the leak of wrong rersults has been plugged. Now it would be nice to have the correct result returned so this issue has not been closed.
