### ISSUE TITLE
Cuda support

### ISSUE THREAD

**Issue by latot** [sympy/sympy#10216]
Hi all, do you intend to support in the future cuda?
it feels can be very good here :D 
or think this like a feature request.

Cya.

**Comment by moorepants** [comment]
Cuda for what? You'll need to be more specific about your request. Maybe you want to be able to generate CUDA code from SymPy objects?

**Comment by latot** [comment]
Hi, mm i prefer talk as a user i have some tchnical knowledge but don't is enough, so i'll replace the explanation with my little experience.
I use sympy thx to the pkg symbolic of octave to realize the symbolics calcs.
in this case i found a way to optimize the product of matrix in octave using cuda.
So i think if its posible optimize in that way the sympy functions too, it can be very helpful, then i'm here. 

Cya :D

**Comment by moorepants** [comment]
@cbm755 You may be interested in this. Sounds like @latot uses your Octave package.

**Comment by cbm755** [comment]
@latot, if I understand correctly, you're wondering if the same technique (as in your stackoverflow link) can be used in SymPy.  Perhaps it could.  However, matrices in SymPy can contain:
(a) symbols;
(b) high precision floating point numbers;
(c) double precision floats.
Only (c) could be reasonably accelerated with CUDA.  And IMHO if you want fast linear algebra on doubles, SymPy is not the right tool: use (core) Octave or NumPy instead.

**Comment by latot** [comment]
mm, i post the link because it has the method i found for octave, respect sympy i don't know if is the right method to use it.

**Comment by bjodah** [comment]
@latot you might be interested in [pyviennacl](http://viennacl.sourceforge.net/pyviennacl.html) as well.
I'm closing this for now. Feel free to ping me if you think of anything else and want it to be reopened.

**Comment by latot** [comment]
Okis, thx.
