### ISSUE TITLE
solveset is not solving equations like sqrt(x) - const

### ISSUE THREAD

**Issue by smichr** [sympy/sympy#10214]
There is an XFAIL test that indicates that solveset is doing something wrong: the following fails in master

```
solveset(x**(S(3)/2) + 4, x, S.Reals) == S.EmptySet
```

**Comment by Shekharrajak** [comment]
```
1. >>> solveset(x**(S(3)/2) + 4, x, S.Reals)
⎧  3 ___⎫
⎨2⋅╲╱ 2 ⎬
⎩       ⎭
2. >>> solveset(x**(S(3)) + 4, x, S.Reals)
⎧  2/3⎫
⎨-2   ⎬
⎩     ⎭
>>> solveset(x**(S(1)/2) + 4, x, S.Reals)
{16}
>>> solveset(x**(2) + 4, x, S.Reals)
∅
>>> solveset(x**(2) + 4, x, S.Reals)==S.EmptySet
True

```
In 1st it seems `solveset` first squaring then cube root.
2nd answer is wrong.if it would `-4^(1/3)` we may say it is returning whole `(-4)^(1/3)` but it is not.
It seems problem is in cube root only.
```
>>> solveset(x**(S(5)/2) + 4, x, S.Reals)
∅
>>> solveset(x**(S(6)/2) + 4, x, S.Reals)
⎧  2/3⎫
⎨-2   ⎬
⎩     ⎭
>>> solveset(x**(S(7)/2) + 4, x, S.Reals)

```
Isn't it ?

**Comment by Shekharrajak** [comment]
```
>>> solveset(x**(S(3)/2) + 4, x, S.Reals)
⎧  3 ___⎫
⎨2⋅╲╱ 2 ⎬
⎩           ⎭
>>> import sympy
>>> sympy.__version__
0.7.7.dev
```
Actual answer should be `S.EmptySet`.
Because when we check `2*2^(1/3)` in expression `x**(3/2)+4` we won't get zero.So `no solution for all x belongs to Real`.
