### ISSUE TITLE
improper inequality reduction

### ISSUE THREAD

**Issue by smichr** [sympy/sympy#10237]
```python
>>> reduce_inequalities([x < oo, x >= 0, -oo < x])
And(-oo < x, x < oo)  <--- wrong
>>> And(*[x < oo, x >= 0, -oo < x]).as_set().as_relational(x)
And(0 <= x, x < oo)  <--- right
```

**Comment by khannavansh** [comment]
Can you elaborate on the issue a little more

**Comment by smichr** [comment]
I indicated in the OP that the wrong answer is obtained when the inequalities are run through `reduce_inequalities` and showed what the right answer should be. I see that @skirpichev was able to find a solution.
