### ISSUE TITLE
serializing with srepr: `eval(srepr(...))` can fail on long expressions with more than 255 children

### ISSUE THREAD

**Issue by cbm755** [sympy/sympy#10259]
An identity: `eval(srepr(q)) == q`

But suppose `q` has a sum of more than 255 items, then we get `Add(...)` with more than 255 arguments.  And `eval` then dies with a SyntaxError.

Example:

```
In [129]: q = Add(*[Symbol('x%.3d' % i) for i in range(0, 256)])

In [130]: eval(srepr(q))
  File "<string>", line 1
SyntaxError: more than 255 arguments
```

What can be done?
- I prefer srepr for serializing but could revert to using "pickles"...
- `Add` (and friends) could accept a list input which could be used by the appropriate printer when there is a large number of arguments.  Is this too invasive?

Other ideas?

**Comment by cbm755** [comment]
One approach, recursively divide `Add`/`Mult` into chunks with 255 or fewer:
````
In [483]: Add(1,2,3,4)
Out[483]: 10

In [484]: Add(Add(1,2),Add(3,4))
Out[484]: 10
````
Is that more or less elegant than hacking `Add`/`Mult` to take a list:
````
Add([1, 2, 3, 4])
````

**Comment by latot** [comment]
This should be fixed in python 3.7 finally:

https://docs.python.org/3.7/whatsnew/3.7.html

**Comment by cbm755** [comment]
Confirmed so closing.  Eventually everyone will be on Python 3.7 so probably not worth other fixes in the meantime.

**Comment by asmeurer** [comment]
It could be printed as `Add(*[1, 2, 3, ...])` when there are more than 255 args.

**Comment by cbm755** [comment]
I cannot comprehend why that works!   I hope that is a pun on some kind of comprehension.

But it does work.

**Comment by cbm755** [comment]
@asmeurer would you like such a patch for Add and Mul?

**Comment by asmeurer** [comment]
You can read the linked issues from the 3.7 release notes. I guess there are (were) some limits in the opcodes used for function calls. `*` unpacking doesn't have the problem because the args are all used to build the list and then a single argument is passed to the function:

```py
>>> dis.dis('f(*[x, y])')
  1           0 LOAD_NAME                0 (f)
              3 LOAD_NAME                1 (x)
              6 LOAD_NAME                2 (y)
              9 BUILD_LIST               2
             12 CALL_FUNCTION_VAR        0 (0 positional, 0 keyword pair)
             15 RETURN_VALUE
>>> dis.dis('f(x, y)')
  1           0 LOAD_NAME                0 (f)
              3 LOAD_NAME                1 (x)
              6 LOAD_NAME                2 (y)
              9 CALL_FUNCTION            2 (2 positional, 0 keyword pair)
             12 RETURN_VALUE
```

A patch for this is probably a good idea. It's easy enough to support pre-3.7, and it will be some time before we only support 3.7+ (we don't even plan to drop 2.7 until 2020, see https://github.com/sympy/sympy/wiki/Python-version-support-policy).

**Comment by cbm755** [comment]
@asmeurer I patched for Add/Mul.

I'm sure there are many others in principle (MatMul, MatAdd, etc).   And its easy to make silly examples: "Bro, yer softwarez is teh sux, cannot take 256th derivative":
```
>>> f = sin(x)
>>> s = 'f.diff(%s)' % ','.join(['x']*256)
  'f.diff(x,x,x,x,x,...)'
>>> eval(s)
  File "<string>", line 1
SyntaxError: more than 255 arguments
```

So I think in practice only Add really matters, rest can wait for Python 3.7.
