### ISSUE TITLE
solving inequality involving exp fails for large values

### ISSUE THREAD

**Issue by smichr** [sympy/sympy#10268]
```python
>>> solve(log(x)<100)
And(-oo < x, x < exp(100))
>>> solve(log(x)<1000)
False
```

**Comment by darkcoderrises** [comment]
It breaks on `solve(log(x)<250)`

**Comment by meghana1995** [comment]
I would like to add one more thing to that. 
The return value of ' v = e.subs(gen, x)' in  
https://github.com/sympy/sympy/blob/master/sympy/solvers/inequalities.py#L428.
is different in both the cases.

In the case of solve( log (x) < 100), some of the assumptions of v such as 'is_negative', 'is_nonnegative' have true/false values. However, in the case of solve(log(x) < 1000), these assumptions are of type None. 

The function https://github.com/sympy/sympy/blob/master/sympy/solvers/inequalities.py#L430
will eventually call
https://github.com/sympy/sympy/blob/master/sympy/core/expr.py#L290.
The line here which seems to be different for both the cases is this if condition:
https://github.com/sympy/sympy/blob/master/sympy/core/expr.py#L304
The assumptions of 'dif' here depend on the assumptions of v, and in the case of solve(log(x) < 1000), these are of type None, so it enters the 'else' block even though it should satisfy the 'if' condition.

**Comment by smichr** [comment]
@meghana1995, thanks for your input. This is now resolved.
