### ISSUE TITLE
Printing matrices in the qtconsole fails when LaTeX is not installed

### ISSUE THREAD

**Issue by Emile59** [sympy/sympy#10264]
I have one computer with Anaconda 2.4.1, on which I can print symbolic matrices in latex on the Ipython console embedded in Spyder2 without raising any error. On this computer was installed another version of python 2.7.10 for other softwares.
Recently I got a new computer on which I installed the same anaconda distribution, and I can't print matrices anymore because of this error :  

    Python 2.7.11 |Anaconda 2.4.1 (64-bit)| (default, Dec  7 2015, 14:10:42) [MSC v.1500 64 bit (AMD64)]
    Type "copyright", "credits" or "license" for more information.
    
    IPython 4.0.1 -- An enhanced Interactive Python.
    ?         -> Introduction and overview of IPython's features.
    %quickref -> Quick reference.
    help      -> Python's own help system.
    object?   -> Details about 'object', use 'object??' for extra details.
    %guiref   -> A brief reference about the graphical user interface.
    
    from sympy import Matrix
    
    from sympy import init_printing
    
    init_printing()
    
    Matrix([0,0])
    Out[4]: 
    Traceback (most recent call last):
    
      File "C:\Users\Anaconda2\lib\site-packages\IPython\core\formatters.py", line 337, in __call__
        return printer(obj)
    
      File "C:\Users\Anaconda2\lib\site-packages\sympy\interactive\printing.py", line 127, in _print_latex_png
        return _matplotlib_wrapper(s)
    
      File "C:\Users\Anaconda2\lib\site-packages\sympy\interactive\printing.py", line 90, in _matplotlib_wrapper
        return latex_to_png(o)
    
      File "C:\Users\Anaconda2\lib\site-packages\IPython\lib\latextools.py", line 87, in latex_to_png
        bin_data = f(s, wrap)
    
      File "C:\Users\Anaconda2\lib\site-packages\IPython\lib\latextools.py", line 106, in latex_to_png_mpl
        mt.to_png(f, s, fontsize=12)
    
      File "C:\Users\Anaconda2\lib\site-packages\matplotlib\mathtext.py", line 3207, in to_png
        rgba, depth = self.to_rgba(texstr, color=color, dpi=dpi, fontsize=fontsize)
    
      File "C:\Users\Anaconda2\lib\site-packages\matplotlib\mathtext.py", line 3172, in to_rgba
        x, depth = self.to_mask(texstr, dpi=dpi, fontsize=fontsize)
    
      File "C:\Users\Anaconda2\lib\site-packages\matplotlib\mathtext.py", line 3145, in to_mask
        ftimage, depth = self.parse(texstr, dpi=dpi, prop=prop)
    
      File "C:\Users\Anaconda2\lib\site-packages\matplotlib\mathtext.py", line 3118, in parse
        box = self._parser.parse(s, font_output, fontsize, dpi)
    
      File "C:\Users\Anaconda2\lib\site-packages\matplotlib\mathtext.py", line 2374, in parse
        six.text_type(err)]))
    
    ValueError: 
    \left[\begin{smallmatrix}0\\0\end{smallmatrix}\right]
          ^
    Expected "\right" (at char 6), (line:1, col:7)
    
    Failed to render latex: 
    \left[\begin{matrix}0\\0\end{matrix}\right]
          ^
    Expected "\right" (at char 6), (line:1, col:7) 

On this topic (https://github.com/sympy/sympy/pull/9959) it is said that there is a work around to avoid matplotlib's mathtext issues, but as the printing works perfectly with others printers on my old computer I would like to know if you have any idea of what is missing in the new computer, meanings in the anaconda 2.4.0 package itself.

**Comment by moorepants** [comment]
Do you know if Spyder is using the IPython qtconsole?

**Comment by moorepants** [comment]
I just reproduced this with SymPy 0.7.6.1, Spyder 2.3.8, Python 3.5.1, IPython 4.0.1. Spyder uses an IPython qtconsole by default. If LaTeX is not installed and you try to print a Matrix, then it will default to the matplotlib backend, which can't print matrices, thus the error you see.

The only current solution for correct printing is to install LaTeX with dvipng and the qtconsole printing will work.

This is an outstanding issue that we haven't come up with a good solution for yet because IPython doesn't let you detect what the frontend of the kernel is.

**Comment by moorepants** [comment]
The commit message in this pull request explains the issue: https://github.com/sympy/sympy/pull/9976

**Comment by moorepants** [comment]
Also see this: https://github.com/sympy/sympy/pull/10005

**Comment by moorepants** [comment]
The other workaround is to use `init_printing(use_latex='matplotlib')`, but you will only get unicode printing of the matrices.

**Comment by Emile59** [comment]
First, thank you very much for your fast answers ! I'm sorry for not beeing
so reactive, I had to leave my computer for a while.

So if I understood you well, I need to install dvipng
<https://www.ctan.org/tex-archive/dviware/dvipng> (which is effectively
installed on the computer without the error as I have miktex) to get back
the alternative to mathtext printer ? In any case, I'm trying this and let
you know asap.

2015-12-15 17:28 GMT+01:00 Jason K. Moore <notifications@github.com>:

**Comment by moorepants** [comment]
Yes, the best solution is to install a LaTeX distribution that includes dvipng. The second solution is to use `init_printing(use_lates='matplotlib')` so that the pretty printing fall-back will work without errors.

**Comment by Emile59** [comment]
Well it works perfectly ! I did it on two different computers, and the problem is solved. Thank you very much Mr.Moore. 
If I may, I will redirect this user (http://stackoverflow.com/questions/33792174/spyder-failed-to-render-latex-when-rendering-a-sympy-matrix) to this page because I am apparently not the only guy who couldn't find easily this solution.

**Comment by asmeurer** [comment]
This is a bug in the upstream qtconsole that has been fixed https://github.com/jupyter/qtconsole/issues/63. The workarounds that @moorepants describes above should work in the meantime.
