### ISSUE TITLE
Add something like "Projects using SymPy" to the top-level of the docs

### ISSUE THREAD

**Issue by moorepants** [sympy/sympy#10273]
See issue #10046 for background.

**Comment by Shekharrajak** [comment]
For this we need list of researches/papers, Sympy or works where Sympy is mainly used. Am I right ? @moorepants

**Comment by moorepants** [comment]
This is meant to be a list of software packages that utilize sympy like galgebra, PyDy, Sage, etc.

There is a list of research papers on the wiki but that is not what we are talking about here. See the cited issue for the conversation.

**Comment by moorepants** [comment]
You could search Github for "import sympy", "from sympy import *", etc. and see if you find any major projects that utilize SymPy for additional ones.

**Comment by Curious72** [comment]
@moorepants  there are many such software packages, and can u tell me exactly what part of the documentation is to be updated?

**Comment by moorepants** [comment]
You could start by adding more information here: http://docs.sympy.org/latest/outreach.html#projects-using-sympy

**Comment by Curious72** [comment]
@moorepants how to add information to documentation? is the documentation also saved in the build?

**Comment by bjodah** [comment]
@Curious72 the sources for the documentation are located in the same repo:
https://github.com/sympy/sympy/blob/a57f3c43b9c86979ff7fe04d520bc404b94d859a/doc/src/outreach.rst

**Comment by Sumith1896** [comment]
Oh I have actually met couple of interesting people who use SymPy in some conferences. I'll try to get in touch with them and update the list.

**Comment by moorepants** [comment]
Depsy lists 50+ citations to SymPy in academic journals:

http://depsy.org/package/python/sympy

We should link to Depsy and also go through these papers and list the ones that use SymPy on our website/wiki.
