### ISSUE TITLE
simplify simple FiniteSet intersections

### ISSUE THREAD

**Issue by smichr** [sympy/sympy#10285]
If there is only a single element in a FiniteSet, it's intersection with an Interval could be simplified in some cases, for example:

```python
>>> FiniteSet(-x+1).intersect(Interval(1,3))
Intersection([1, 3], {-x + 1})
```
could be 

```
Intersection([-2, 0], {x})
```

**Comment by darkcoderrises** [comment]
Can I work on this?

**Comment by smichr** [comment]
> Can I work on this?

Sure. I would suggest the following for tests to aim for:

```
assert FiniteSet(2*x + 1).intersect(Interval(3, 5)) == FiniteSet(x).intersect(Interval(1, 2))
assert FiniteSet(x*y + 1).intersect(Interval(3, 5)) == FiniteSet(x*y).intersect(Interval(2, 4))
assert FiniteSet(2*x + 2*y).intersect(Interval(2, 4)) == FiniteSet(x + y).intersect(Interval(1, 2))
```

That last one is more borderline. Let's see if anyone has an opinion regarding that (which would require factor_terms to be run on the expression).

**Comment by darkcoderrises** [comment]
Should I also aim for cases like `FiniteSet(x**2 + 2*x + 1).intersect(Interval(3, 5))` 
If yes, then I was thinking that maybe we could solve the given equation for less than first element and greater than the second, then take a Union. But this will only be there for a single variable as multiple are not implemented yet. 
Otherwise, I wanted to know that should I first remove the constant term, by subtracting it from both the sides and then divide with the HCF of all coefficients of remaining term.

**Comment by achaitanyasai** [comment]
@smichr  I have worked on this issue and I have tested and added these tests : 
<pre>
<code>
assert FiniteSet(2*x + 1).intersect(Interval(3, 5)) == FiniteSet(x).intersect(Interval(1, 2))
assert FiniteSet(x*y + 1).intersect(Interval(3, 5)) == FiniteSet(x*y).intersect(Interval(2, 4))
assert FiniteSet(2*x + 2*y).intersect(Interval(2, 4)) == FiniteSet(x + y).intersect(Interval(1, 2))
assert FiniteSet(2*x + 1).intersect(Interval(2, 4)) == FiniteSet(x).intersect(Interval(Mul(1) / 2, Mul(3) / 2))
assert FiniteSet((2*x + 1) / 3).intersect(Interval(2, 4)) == FiniteSet(x).intersect(Interval(Mul(5) /2, Mul(11) /2))
assert FiniteSet(x).intersect(Interval(2, 3)) == FiniteSet(x).intersect(Interval(2, 3))
assert FiniteSet(2*x/3 + 3*y/2).intersect(Interval(2, 4)) == FiniteSet(4*x + 9*y).intersect(Interval(12, 24))
</code></pre>

Every thing seems to be fine, so shall I continue to PR  ?

**Comment by achaitanyasai** [comment]
@smichr  It seems like we should not simplify always, for example in this case : 
<pre><code>>>> absxm3 = Piecewise(
...         (x - 3, S(0) <= x - 3),
...         (3 - x, S(0) > x - 3)
...     )
>>> 
>>> solveset_real(absxm3 - y, x)
Intersection((-oo, 3), {y}) U Intersection([3, oo), {y})
</code></pre>
Where as the actual result is : 
<pre><code>Intersection([3, oo), {y + 3}) U Intersection((-oo, 3), {-y + 3})</code></pre>

So can you help me with these cases.
