### ISSUE TITLE
Bug in ImageSet

### ISSUE THREAD

**Issue by kshitij10496** [sympy/sympy#10287]
I think we should not use `args[0]` [here](https://github.com/sympy/sympy/blob/master/sympy/sets/fancysets.py#L240).
Reason : 
It works fine when `linsolve` returns a non-empty set.
But when it returns an empty set, an error is raised.
As calling `args[0]` on an empty set raises an `IndexError`.

This is most likely the reason why this [test](https://github.com/sympy/sympy/blob/master/sympy/sets/tests/test_fancysets.py#L81-L94) is failing for `(1, 0)` and passing for `(0, 0)`

Also, why are we type-casting the `set` to a `list` ?

Ping @mrocklin 
Maybe you can help me out here.

**Comment by kshitij10496** [comment]
Ping @aktech

**Comment by aktech** [comment]
>As calling args[0] on an empty set raises an IndexError.

A try catch should be used there.

> Also, why are we type-casting the set to a list ?

It doesn't looks like we should, we are typecasting the first argument of `FiniteSet` returned by `linsolve` which is a `tuple`, & it's unneccesary to typecast a tuple to a list in this case.

**Comment by kshitij10496** [comment]
> A try catch should be used there.

Wouldn't an `if` condition checking the size of returned tuple be better suited here ?

> it's unneccesary to typecast a tuple to a list in this case.

Should we remove it and work on the returned tuple itself ?

**Comment by aktech** [comment]
> Wouldn't an if condition checking the size of returned tuple be better suited here ?

We wouldn't have a tuple when `EmptySet()` is returned.

> Should we remove it and work on the returned tuple itself ?

Yes.

**Comment by kshitij10496** [comment]
> We wouldn't have a tuple when EmptySet() is returned.

Yeah. Actually, I meant an `if` condition to check the size of the returned set from `linsolve`.
If its an `EmptySet`, we  can directly return `False`.

**Comment by smichr** [comment]
Did #10645 address this issue?
