### ISSUE TITLE
Fourier transform not returning DiracDelta

### ISSUE THREAD

**Issue by tedtss** [sympy/sympy#10299]
Fourier transform is returning 0 intead of a DiracDelta. As a simple example, fourier_transform(1, x, y) returns zero, not DiracDelta(0).

**Comment by jksuom** [comment]
This is a well known issue. SymPy's integrator (used for transforms) can not currently handle generalized functions such as Dirac delta.

**Comment by asmeurer** [comment]
Duplicate of
