### ISSUE TITLE
poly cannot generically be rebuilt from its args

### ISSUE THREAD

**Issue by MooVI** [sympy/sympy#10292]
``` python
In [18]: expr = poly(1,x)
In [19]: expr.func(*expr.args)
GeneratorsNeeded: specify generators to give 1 a meaning
```

Isn't it supposed to be a general property that we can rebuild expressions like this?

**Comment by asmeurer** [comment]
Poly is not actually a Basic subclass. It only implements .args for some basic compatibility.

**Comment by MooVI** [comment]
@asmeurer Oh, I see. Just for my understanding in the future, what set of classes are expr.func(*expr.args) == expr supposed to be true for? One can't check whether something is a Basic subclass, because Poly is technically derived from Basic:

```python
In [13]: issubclass(Poly, Basic)
Out[13]: True

**Comment by oscarbenjamin** [comment]
Is there anything to fix here?

**Comment by MooVI** [comment]
Apparently this has been fixed -- sorry I missed this! Will close.

**Comment by jksuom** [comment]
There is an open PR concerned with the creation of Poly objects from their arguments: https://github.com/sympy/sympy/pull/15799. That should probably be completed.
