### ISSUE TITLE
expression reports as being comparable but is not

### ISSUE THREAD

**Issue by smichr** [sympy/sympy#10303]
The logic for `is_comparable` should be checked so that the following is False for `is_comparable`:

```python
a = (2**pi*(1 + 2**pi))
>>> d = (a - expand(a))
>>> d.is_comparable
True 
>>> d.equals(0)
True 
>>> (d < 0) == False  # since d == 0, d < 0 should be false but it's not
False
>>> d.n(2)._prec  # when this is 1 there is no precision, hence not comparable
1

```

**Comment by smichr** [comment]
simplifying this type of expression does not help reduce it to zero because of #7981.

**Comment by smichr** [comment]
Sorry for the noise. My master branch must not have been up to date:

```python
>>> a = (2**pi*(1 + 2**pi))
>>> d=a-a.expand()
>>> d.is_comparable
False
```

**Comment by meghana1995** [comment]
I must have had an older version of the master too as I had gotten the wrong output .
