### ISSUE TITLE
Equality involving expression with known real part and 0 should evaluate

### ISSUE THREAD

**Issue by smichr** [sympy/sympy#10304]
```python
>>> d=S('-(3*2**pi)**(1/pi) + 2*3**(1/pi)')
>>> d.is_comparable
False
>>> e = 1 + d*I
>>> e.is_real  # can't tell unless we know d is nonzero...
>>> simplify(Eq(e,0))
Eq(1 + I*(-(3*2**pi)**(1/pi) + 2*3**(1/pi)), 0)
```

That final expression should be False since we know that the real part is non-zero (so it doesn't matter if we can't decide about the imaginary part).

**Comment by asmeurer** [comment]
You also need to know d.is_real (if d == I then e is 0).

**Comment by smichr** [comment]
> You also need to know d.is_real

good catch -- I'll check for that condition, too.
