### ISSUE TITLE
diff(integrate(e)) takes long time, can be made more efficient

### ISSUE THREAD

**Issue by Shaswat27** [sympy/sympy#10310]
diff(integrate(e)) first computes the anti-derivative and differentiates the result to get the answer. However, a more more efficient method would be to directly return 'e'. 
For cases where the integration variable and diff_wrt to variables are different, Leibniz rule must be applied which is already implemented in integration function.

e.g: e = ( x*_2 + 2_x + 1 + (3_x+1)_sqrt(x+log(x)) )/( x_sqrt(x+log(x))_(x+sqrt(x+log(x))) )
       integrate(e) takes ~3.75s
       Differentiating the above result takes ~0.018s
       diff(integrate(e)) takes ~3.89s

**Comment by kshitij10496** [comment]
Seems like a nice idea

**Comment by Shaswat27** [comment]
@asmeurer

**Comment by asmeurer** [comment]
Thus should already work if you pass diff an unevaluated Integral object. Otherwise, it can't be made to work, because Python is an eagerly evaluated language.

**Comment by oscarbenjamin** [comment]
So `diff(Integral(e))` does what you want.
