### ISSUE TITLE
Extend vigenère in crypto to accept repetitions in keys

### ISSUE THREAD

**Issue by ec-m** [sympy/sympy#10317]
In line 369 of function `encipher_vigenere`, which is part of `crypto.py` the method `uniq` from utilities.iterables is used to return an iterator of the key-phrase without possible spaces in the key. However, `uniq` will return an iterator with only unique characters of the key. Therefore, if one uses a key such as "cool", `uniq` returns "col" and the function will hence encrypt in a wrong way.

Example: `encipher_vigenere("wow", "cool")` returns "YCH". However, the right result would actually be "YCK".

Also, instead of using `capitalize` on each character of the key or the plaintext (see lines 370 or 373) we could also simplify the problem by using `key.upper` or `pt.upper`.

I would volunteer to fix this and if I am assuming right and `uniq` is used wrong also in other crypto functions such as `encipher_bifid5` or `bifid5_square` I could also fix these functions.

**Comment by moorepants** [comment]
I'd recommend writing test cases for the functions you know are outputting the incorrect results. You can use git blame to see who works on the crypto package and ask them about the correctness.

**Comment by ec-m** [comment]
Alright, I'll do that. Thanks!

**Comment by ec-m** [comment]
The use of `uniq` in all the `bifid`-encryption functions actually seems fine - here it is mentioned in the doc string that the key does not allow repetition of characters. 

For the `vigenere` functions I wrote the following examples to illustrate wrong results: (Sorry, I can only add this as a *.txt file since *.py is not allowed)
[test_crypto.txt](https://github.com/sympy/sympy/files/72266/test_crypto.txt)

@wdjoyner (wrote the function `encipher_vigenere` but seems to be inactive at the moment) @jrioux @ankit-maverick @asmeurer You have also contributed to `crypto.py` - Can you see if my assumptions about `vigenere` are correct? Thanks :)

**Comment by wdjoyner** [comment]
Sorry, I'm not sure I understand.
Are you saying that the key must have distinct letters?

**Comment by ec-m** [comment]
@wdjoyner No, I am not. I am just saying that the use of `uniq` in `encipher_vigenere` and `decipher_vigenere` can result in wrong results. Please see my examples here: https://github.com/sympy/sympy/files/72266/test_crypto.txt and my explanation from the opening message of this issue.

**Comment by wdjoyner** [comment]
On Fri, Dec 25, 2015 at 5:06 PM, Eva Charlotte Mayer <
notifications@github.com> wrote:

> @wdjoyner <https://github.com/wdjoyner> No, I am not. I am just saying
> that the use of uniq in encipher_vigenere and decipher_vigenere can
> result in wrong results. Please see my examples here:
> https://github.com/sympy/sympy/files/72266/test_crypto.txt and my
> explanation from the opening message of this issue.
>

Sorry, I'm still confused. Do you have any examples where encipher_vigenere
and decipher_vigenere result in wrong results where the key has no repeated
letters?

**Comment by ec-m** [comment]
@wdjoyner No, the functions work fine if the key has no repeated letters. But it should also work if it does have repetitions, since no such restrictions are mentioned anywhere.

**Comment by wdjoyner** [comment]
On Fri, Dec 25, 2015 at 5:24 PM, Eva Charlotte Mayer <
notifications@github.com> wrote:

> @wdjoyner <https://github.com/wdjoyner> No, the functions work fine if
> the key has no repeated letters. But it should also work if it does have
> repetitions, since no such restrictions are mentioned anywhere.
>
Sorry for the confusion. I think the code is correct as is. The docstrict
is perhaps not clear enough.

As described in the reference, where the cipher is defined more carefully,
"Although there are 26 key rows shown, you will only use as many keys
(different alphabets) as there are unique letters in the key string". The
repeated letters of the key are always ignored. Perhaps it would be better
to add a line to the documentation which makes that clear?

 In [1]: key = "encrypt"

In [2]: pt = "meet me on monday"

In [4]: from sympy.crypto.crypto import encipher_vigenere

In [5]: encipher_vigenere(pt, key)
Out[5]: 'QRGKKTHRZQEBPR'

In [6]: key = "encryptt"

In [7]: encipher_vigenere(pt, key)
Out[7]: 'QRGKKTHRZQEBPR'

**Comment by ec-m** [comment]
Alright, we could clarify this in the docstring. However, the Vigerère Cipher as I know it (see [this link](http://www.cryptool-online.org/index.php?option=com_content&view=article&id=51&Itemid=98&lang=en)) does not have restrictions on repeated characters in the keyphrase.

**Comment by smichr** [comment]
I read the link and indeed, it does not imply that there be no repeats. I know little about the merits in allowing them, however. One could use a keyword to control whether repeats are allowed or not.

**Comment by wdjoyner** [comment]
I'm not sure what you mean by link. Do you mean the Wikipedia reference?

**Comment by ec-m** [comment]
I think we have two options: Either we clarify that character repetitions are not allowed (the way it is done in the bifid-functions for example, see line 563 for example) or we avoid the use of `uniq` and instead use `string.replace(" ", "" )` just to remove the white spaces which are not needed. This is actually all that needs to be changed, then the function works for both keys with and without repetitions - we don't even need a keyword as @smichr suggested.

**Comment by wdjoyner** [comment]
On Sat, Dec 26, 2015 at 4:23 PM, Eva Charlotte Mayer <
notifications@github.com> wrote:

> I think we have two options: Either we clarify that character repetitions
> are not allowed (the way it is done in the bifid-functions for example, see
> line 563 for example) or we avoid the use of uniq and instead use string.replace("
> ", "" ) just to remove the white spaces which are not needed. This is
> actually all that needs to be changed, then the function works for both
> keys with and without repetitions - we don't even need a keyword as
> @smichr <https://github.com/smichr> suggested.
>

I have no preference but the first way is the way I intended the function
to work.

**Comment by smichr** [comment]
> I'm not sure what you mean by link. Do you mean the Wikipedia reference?

No, the CrypTool link [cited](http://www.cryptool-online.org/index.php?option=com_content&view=article&id=51&Itemid=98&lang=en). It says that the key can be arbitrary length (hence must allow for repeats). When the key is the same length as the text, it is a Vernam cipher; when a key (as long as the text) is randomly generated, it is a One Time Pad cipher.

There is no need for separate functions, I think. The `encipher_vigenere` principle is to use a changing shift of the `symbols` as indicated by the `key'.

**Comment by wdjoyner** [comment]
On Mon, Dec 28, 2015 at 12:08 AM, Christopher Smith <
notifications@github.com> wrote:

> I'm not sure what you mean by link. Do you mean the Wikipedia reference?
>
> No, the CrypTool link cited
> <http://www.cryptool-online.org/index.php?option=com_content&view=article&id=51&Itemid=98&lang=en>.
> It says that the key can be arbitrary length (hence must
>

The link cited where? I searched the entire cypto.py module and didn't find
it there.
The only link cited in that module's Vigenere cipher functions is the
wikipedia reference to the Vigenere cipher. Please reread the quote I gave
from that reference in a previous post in this thread. I can give other
references to descriptions of the Vigenere cipher that stipulate it ignores
repeats, but what is the point? I used a reference that did make that
assumption (which I claim is a standard assumption) and that is how I wrote
the code. If you want to change it, free free. I request you please don't
make it the default.

allow for repeats). When the key is the same length as the text, it is a

**Comment by ec-m** [comment]
Alright, I'll add an option for keys with repetitions then but don't make it default.

**Comment by smichr** [comment]
> The link cited where?

In the discussion [above](https://github.com/sympy/sympy/issues/10317#issuecomment-167266433)

**Comment by smichr** [comment]
> As described in the reference, where the cipher is defined more carefully,
> "Although there are 26 key rows shown, you will only use as many keys
> (different alphabets) as there are unique letters in the key string". The
> repeated letters of the key are always ignored.

OK, I read the wiki article carefully. What they mean, however, in the above quote is that you will ignore (of course) any shifted alphabet corresponding to an unused letter. It doesn't imply that there are no repeated letters in the key. If there are repeats you will (of course) reuse the corresponding shifted alphabet. Also, the wiki article cites as examples of keys that were used historically as "Manchester Bluff" which has a repeated `e` and "Complete Victory" which repeats 'eoct'.

Although it would break backwards compatibility to change this, it seems like it should have allowed repeats from the start. Would you object strongly to making the default allow repeats? It's not hard for someone to simply use `uniq(phrase)` to get the old behavior instead of setting a flag with `unique=True` if the change is made.

**Comment by wdjoyner** [comment]
On Mon, Dec 28, 2015 at 10:31 AM, Christopher Smith <
notifications@github.com> wrote:

> As described in the reference, where the cipher is defined more carefully,
> "Although there are 26 key rows shown, you will only use as many keys
> (different alphabets) as there are unique letters in the key string". The
> repeated letters of the key are always ignored.
>
> OK, I read the wiki article carefully. What they mean, however, in the
> above quote is that you will ignore (of course) any shifted alphabet
> corresponding to an unused letter. It doesn't imply that there are no
> repeated letters in the key. If there are repeats you will (of course)
> reuse the corresponding shifted alphabet. Also, the wiki article cites as
> examples of keys that were used historically as "Manchester Bluff" which
> has a repeated e and "Complete Victory" which repeats 'eoct'.
>

I interpret "The repeated letters of the key are always ignored." to mean,
for example, that the key "AAC" is replaced by "AC".



> Although it would break backwards compatibility to change this, it seems
> like it should have allowed repeats from the start. Would you object
> strongly to making the default allow repeats? It's not hard for someone to
> simply use uniq(phrase) to get the old behavior instead of setting a flag
> with unique=True if the change is made.
>

I think the currently implemented code allows repeats. It just ignores them
in the enciphering process.

**Comment by smichr** [comment]
> I interpret "The repeated letters of the key are always ignored." to mean,
> for example, that the key "AAC" is replaced by "AC".

<smile> That is self evident since these are your own words, not those of the wikipedia article. 

What the article is saying is that each letter of the `key string` corresponds to one of 26 `keys`; repeated letters in the `key string` each use the same `key`. In fact, in the Kasiski analysis section it says "This means that the key length could be 30 ... characters long."  This would be impossible if only the unique letters in the `key string` were used.

There is a good reason to allow repeated letters in the `key string`: if you don't, you end up with a smaller `key phrase` but the more unbreakable `key string` is the one that approaches a random sequence of the numbers letters. `abracadabra` is 11 chars long but using the current implementation would condense down to `abrcd`; at the extreme, a random `key string` as long as the text to be encypted would necessarily reduce to only 26 characters and the latter will be much easier to break.

If you are not agreeable to changing the default behavior, a keyword to allow for not removing repeats is fine with me. Since we are so close to the initial release of this module I would prefer to redefine this aspect rather than make the non-traditional (based on the wiki reference) behavior be the default.

The following function might also be good to add:

```python
>>> def keystring(phrase, repeats=True):
...   rv = ''.join(''.join(phrase.split()).upper())
...   if repeats:
...     return rv
...   return ''.join(uniq(rv))
...
>>> keystring('a stitch in time saves nine')
'ASTITCHINTIMESAVESNINE'
>>> keystring('a stitch in time saves nine', 0)
'ASTICHNMEV'
>>>
```

**Comment by wdjoyner** [comment]
On Mon, Dec 28, 2015 at 8:56 PM, Christopher Smith <notifications@github.com
> wrote:

> I interpret "The repeated letters of the key are always ignored." to mean,
> for example, that the key "AAC" is replaced by "AC".
>
> That is self evident since these are your own words, not those of the
> wikipedia article.
>

Sorry, I copied the wrong phrase. I meant to copy "Although there are 26
key rows shown, you will only use as many keys (different alphabets) as
there are unique letters in the key string"


> What the article is saying is that each letter of the key string
> corresponds to one of 26 keys; repeated letters in the key string each
> use the same key. In fact, in the Kasiski analysis section it says "This
> means that the key length could be 30 ... characters long." This would be
> impossible if only the unique letters in the key string were used.
>

You could be right that my interpretation of the wikipedia article
description is wrong. I actually got my description from Alasdair
McAndrew's  "Introduction to Cryptography with Open-Source Software"
https://books.google.com/books?isbn=1439825718
Of course, I may have misinterpreted his as well!

There is a good reason to allow repeated letters in the key string: if you
> don't, you end up with a smaller key phrase but the more unbreakable key
> string is the one that approaches a random sequence of the numbers
> letters. abracadabra is 11 chars long but using the current
> implementation would condense down to abrcd; at the extreme, a random key
> string as long as the text to be encypted would necessarily reduce to
> only 26 characters and the latter will be much easier to break.
>

The computations needed to decipher, using the standard method of frequency
analysis, a ciphertext  based on the key abracadabra would be the same
level of difficulty as that using abrcd. In other words, I believe you are
wrong if you are suggesting that allowing repetitions will increase
security when the key length is much smaller than the message. Maybe it
would if you want to intend the vigenere cipher as a one-time pad, but that
is really a different cipher.


> If you are not agreeable to changing the default behavior, a keyword to
> allow for not removing repeats is fine with me. Since we are so close to
> the initial release of this module I would prefer to redefine this aspect
> rather than make the non-traditional (based on the wiki reference) behavior
> be the default.
>
> The following function might also be good to add:
>
> >>> def keystring(phrase, repeats=True):
> ...   rv = ''.join(''.join(phrase.split()).upper())
> ...   if repeats:
> ...     return rv
> ...   return ''.join(uniq(rv))
> ...>>> keystring('a stitch in time saves nine')'ASTITCHINTIMESAVESNINE'>>> keystring('a stitch in time saves nine', 0)'ASTICHNMEV'>>>
>
>
Agreed.

**Comment by asmeurer** [comment]
@wdjoyner I looked up Vigenère in that Google books link (page 61) and I see no reference to repeated letters. Their only example key is "CODE", which has no repeated letters. The Python code for `vige(s,key)` appears to not remove repeats (I don't know what `str21st(key)` does, but if it removes duplicates there is a bug because `kn = len(key)` before `str21st` is called).  It does mention that repeated characters in the *message* won't be cyphered to the same character (as opposed to the Caesar cipher). Furthermore, in section 3.6 (page 65) it mentions that the one-time pad is a variation on the Vigenère cipher, which of course is only true if duplicate characters are not removed (although it also states that one-time pads are the only unbreakable cryptosystems, of which I am sceptical). 

@smichr this code was already included in a release https://github.com/sympy/sympy/blob/sympy-0.7.6.1/sympy/crypto/crypto.py#L368. That doesn't mean we shouldn't change it, though.

**Comment by ec-m** [comment]
@smichr 
> def keystring(phrase, repeats=True):
...   rv = ''.join(''.join(phrase.split()).upper())
...   if repeats:
...     return rv
...   return ''.join(uniq(rv))

Should we check if the input has only alphanumeric value? This is what is done in `encipher_vigenere` right now, which is why I am asking. We could simply add:

`rv = ''.join(''.join([x for x in phrase.split() if x.isalnum()]).upper())`

**Comment by smichr** [comment]
> Sorry, I copied the wrong phrase. I meant to copy "Although there are 26
> key rows shown, you will only use as many keys (different alphabets) as
> there are unique letters in the key string"

BTW, I thought I left a smile in my comment; I didn't intend what I said to sound snarky. Regarding the newly quoted phrase -- I can totally see why there would be confusion. I only interpret it differently since I have the filter of this issue coloring my view. Perhaps I'll edit the wiki page to make this clearer.

**Comment by smichr** [comment]
> ...input has only alphanumeric....We could simply add...

That seems like a good idea to prevent garbage in the key.

**Comment by smichr** [comment]
I've been working over the routines in crypto, especially vigenere and bifid. If you would like to take a look, they are in my crypto branch. My main concern is that the routines are too specific to allow experimentation, especially in an educational setting. Also, the bifid7 routine seems to be an albatross since once can't unambiguosly decode what it encodes. Likewise, the morse routine returns a string when it encounters a bad morse code rather than raising an error.

**Comment by wdjoyner** [comment]
On Thu, Jan 7, 2016 at 5:23 AM, Christopher Smith <notifications@github.com>
wrote:

> I've been working over the routines in crypto, especially vigenere and
> bifid. If you would like to take a look, they are in my crypto branch. My
> main concern is that the routines are too specific to allow
> experimentation, especially in an educational setting. Also, the bifid7
> routine seems to be an albatross since once can't unambiguosly decode what
> it encodes. Likewise, the morse routine returns a string when it encounters
> a bad morse code rather than raising an error.
>

Many thanks for improving these. I don't see it in
https://github.com/smichr/sympy/tree/master/sympy

**Comment by ec-m** [comment]
@smichr I like your changes. Especially the additional `AZ`, `paddedkey` and `check_and_join functions` are very helpful.

@wdjoyner 
>Many thanks for improving these. I don't see it in
https://github.com/smichr/sympy/tree/master/sympy

You can find the changes in the crypto branch:
https://github.com/smichr/sympy/tree/crypto/sympy

**Comment by smichr** [comment]
More changes but have to quit for now. I still think more consistent handling of initial args should be done. My inclination is to have an init function which, if symbols are not provided, does the uppercase default otherwise allow one to "shoot themselves in the foot." Something like this:

```python
def _init(pt, key, symbols, default=None):
    if not symbols:
        A = default or AZ()
        key = check_and_join(AZ(key), A, filter=True)
        pt = check_and_join(AZ(pt), A, filter=True)
    else:
        A = check_and_join(symbols)
        key = check_and_join(key)
        pt = check_and_join(pt)
    return pt, key, A
```

**Comment by smichr** [comment]
OK, I think that's about it. Substitution can now handle multi-character replacements via the `replace` function that was added to `misc`. The trouble with `translate` between Py2 and Py3 was handled with a `translate` function also added to `misc'.  I'll put this up as a PR where comments can be added.
