### ISSUE TITLE
Making add iterable

### ISSUE THREAD

**Issue by pirocks** [sympy/sympy#10325]
I would like to see something like this:
>for item in x+y+3*cos(x):
>    print(item)

Which would output:

>x
>y
>3*cos(x)
 I'm unsure if anything like this already exists, but I couldn't find anything in the documentation/google

**Comment by leosartaj** [comment]
@pirocks You can do something like this

```
In [1]: (x + y + 3*cos(x)).args
Out[1]: (x, y, 3⋅cos(x))
In [2]: for item in (x + y + 3*cos(x)).args:
   ...:     print item
   ...:     
x
y
3*cos(x)
```

**Comment by pirocks** [comment]
Thanks.
