### ISSUE TITLE
Interval(-oo, oo) contains oo

### ISSUE THREAD

**Issue by kshitij10496** [sympy/sympy#10326]
Related : #9706 

```python
In [ ]: foo = Interval(-oo, oo)

In [ ]: foo.contains(-oo)
Out[ ]: True

In [ ]: foo.contains(oo)
Out[ ]: True

```

Ping @asmeurer

**Comment by asmeurer** [comment]
To quote my comment from the other issue, I guess the issue is

        if self.start is S.NegativeInfinity and self.end is S.Infinity:
            if not other.is_real is None:
                return other.is_real

in `Interval._contains`. But the problem is that oo.is_real is True, which is a known issue with the old assumptions (I guess #8203 is the issue for it).

**Comment by kshitij10496** [comment]
@asmeurer I think fixing this issue in `_contains` would overlook the actual bug (`oo.is_real` returns `True`).
If the new Assumptions fixes this (as it should), wouldn't it be better if we wait until then ?

**Comment by kshitij10496** [comment]
@asmeurer What are your inputs on this ?
