### ISSUE TITLE
Is nextprime supposed to return <int> instead of <Integer>?

### ISSUE THREAD

**Issue by cbm755** [sympy/sympy#10361]
The output of nextprime/prevprime is not sympified.  Is that intentional or should I patch?

````
In [1]: from sympy import *

In [2]: q = nextprime(5)

In [3]: q?
Type:        int
String form: 7
Docstring:
int(x=0) -> int or long
----- 8< ------
````
One might expect it to return an proper sympy `Integer`

**Comment by smichr** [comment]
For speed purposes, I believe this is intentional. `prime(n)` also returns an `int`.

**Comment by cbm755** [comment]
I can see why the algorithm itself might be faster by using `int` internally.  But after it finishes?  I suppose so, if its used in a tight loop elsewhere in sympy...

Thanks!
