### ISSUE TITLE
Problem with expression args

### ISSUE THREAD

**Issue by achaitanyasai** [sympy/sympy#10365]
<pre><code>
>>> expr1 = x
>>> expr1.args
()
>>> expr2 = -x
>>> expr2.args
(-1, x)
>>> expr3 = x + y
>>> expr3.args
(x, y)
>>> expr4 = -x - y
>>> expr4.args
(-x, -y)
>>> expr5 = x - y
>>> expr5.args
(x, -y)
</code></pre>

Isn't expr1.args = (x) and expr2.args = (-x) ?

**Comment by gxyd** [comment]
`.args` goes through the expression-tree of the corresponding expression.(that stop's at the `Symbol` object)
For
```
>>> expr1, expr2 = x, -x
>>> type(expr1)
sympy.core.symbol.Symbol
>>> type(expr2)
sympy.core.mul.Mul
```
Hence here for `expr2` the `.args` returns the it's expression tree which is an instance of `Mul`, hence returning the corresponding objects multiplied i.e `(-1, x)`.
> Isn't expr1.args = (x) and expr2.args = (-x) ?

So no.

**Comment by achaitanyasai** [comment]
Thanks!
