### ISSUE TITLE
dsolve() converts floats to integers/rationals

### ISSUE THREAD

**Issue by ronanpaixao** [sympy/sympy#10379]
Unlike `solve()`, `dsolve()` doesn't allow a `rational=False` flag and **by default converts floats to rationals**. This causes bugs when solving ODEs with floats. This works:

    dsolve(x1(t).diff(t)-(1-41.05*y*x1(t)))

```x1(t) == (0.0243605359317905*exp(y*(C1 - 41.05*t)) + 0.0243605359317905)/y```

but this doesn't (just 41.05 changed to 51.05):

    dsolve(x1(t).diff(t)-(1-51.05*y*x1(t)))

```
Traceback (most recent call last):
...
OverflowError: Python int too large to convert to C long
```

Using Python 2.7.11, SymPy 0.7.6.1

**Comment by shubhamtibra** [comment]
I would like to work on it. I can't find the code where it is converting those floats into rationals/integers.
