### ISSUE TITLE
(1 / (4 + 3*I)).is_imaginary -> None

### ISSUE THREAD

**Issue by oscarbenjamin** [sympy/sympy#10387]
Currently we have:

```
>>> from sympy import I
>>> print((1 / (4 + 3*I)).is_imaginary)
None
```

I've attached PR #10386  that fixes this using the fact that z is imaginary iff 1/z is imaginary.

**Comment by thisch** [comment]
I think you don't need to open a separate issue if you've already submitted a PR.

**Comment by oscarbenjamin** [comment]
Oh okay. I'll close this then.
