### ISSUE TITLE
det of empty matrix is 1

### ISSUE THREAD

**Issue by akritas** [sympy/sympy#10383]
If M = Matrix(0, 0, []), then M.det() returns 1. Is this on purpose?

In other CAS's it returns an error message that the matrix is not square or something to that effect.

**Comment by jksuom** [comment]
I believe it is set on purpose. It simplifies coding as it is not necessary make preparations for exceptions.

The value 1 is analogous to the value of an empty product. In fact, the determinant of a diagonal matrix is the product of its diagonal entries. For a 0x0 matrix this product takes conventionally the value 1.

**Comment by asmeurer** [comment]
Or applying the [Leibniz formula](https://en.wikipedia.org/wiki/Leibniz_formula_for_determinants), which (at least according to Wikipedia) is the definition of the determinant, you get Sum(Product(a_i,sigma(i), (i, 1, n), (sigma in S_n)). The Product is the empty product (i.e., 1), and the Sum is over S_0, which contains one element (the identity; S_n is a group so it always has at least one element). 

Note that `Matrix(1, 0, []).det()` does give a NonSquareMatrixError. But a 0x0 matrix *is* square.
