### ISSUE TITLE
Remove all 1.0 deprecated code

### ISSUE THREAD

**Issue by moorepants** [sympy/sympy#10392]
There are likely a number of deprecations that can be removed with the 1.0 release. Someone needs to scour the source and see what needs removing. Deprecation warnings may need to be updated too.

**Comment by kshitij10496** [comment]
I just did a quick `grep` search of the `@deprecated` decorator and I found the following deprecations:

- sympy/utilities/iterables.py:1756: [Link](https://github.com/sympy/sympy/blob/master/sympy/utilities/iterables.py#L1756)
- sympy/galgebra/printing.py:237: [Link](https://github.com/sympy/sympy/blob/master/sympy/galgebra/printing.py#L237)
- sympy/galgebra/printing.py:242: [Link](https://github.com/sympy/sympy/blob/master/sympy/galgebra/printing.py#L242)
- sympy/tensor/tensor.py:222: [Link](https://github.com/sympy/sympy/blob/master/sympy/tensor/tensor.py#L222)
- sympy/tensor/tensor.py:747: [Link](https://github.com/sympy/sympy/blob/master/sympy/tensor/tensor.py#L747)
- sympy/tensor/tensor.py:753: [Link](https://github.com/sympy/sympy/blob/master/sympy/tensor/tensor.py#L753)
- sympy/tensor/tensor.py:760: [Link](https://github.com/sympy/sympy/blob/master/sympy/tensor/tensor.py#L760)
- sympy/tensor/tensor.py:768: [Link](https://github.com/sympy/sympy/blob/master/sympy/tensor/tensor.py#L768)
- sympy/core/basic.py:678: [Link](https://github.com/sympy/sympy/blob/master/sympy/core/basic.py#L678)
- sympy/core/basic.py:1614: [Link](https://github.com/sympy/sympy/blob/master/sympy/core/basic.py#L1614)
- sympy/core/basic.py:1619: [Link](https://github.com/sympy/sympy/blob/master/sympy/core/basic.py#L1619)
- sympy/core/basic.py:1623: [Link](https://github.com/sympy/sympy/blob/master/sympy/core/basic.py#L1623)
- sympy/logic/boolalg.py:1291: [Link](https://github.com/sympy/sympy/blob/master/sympy/logic/boolalg.py#L1291)
- sympy/logic/boolalg.py:1861: [Link](https://github.com/sympy/sympy/blob/master/sympy/logic/boolalg.py#L1861)
- sympy/assumptions/ask.py:360: [Link](https://github.com/sympy/sympy/blob/master/sympy/assumptions/ask.py#L360)
- sympy/assumptions/ask.py:380: [Link](https://github.com/sympy/sympy/blob/master/sympy/assumptions/ask.py#L380)
- sympy/assumptions/ask.py:388: [Link](https://github.com/sympy/sympy/blob/master/sympy/assumptions/ask.py#L388)
- sympy/sets/fancysets.py:303: [Link](https://github.com/sympy/sympy/blob/master/sympy/sets/fancysets.py#L303)
- sympy/sets/sets.py:291: [Link](https://github.com/sympy/sympy/blob/master/sympy/sets/sets.py#L291)
- sympy/sets/sets.py:521: [Link](https://github.com/sympy/sympy/blob/master/sympy/sets/sets.py#L521)
- sympy/sets/sets.py:658: [Link](https://github.com/sympy/sympy/blob/master/sympy/sets/sets.py#L658)
- sympy/sets/sets.py:728: [Link](https://github.com/sympy/sympy/blob/master/sympy/sets/sets.py#L728)
- sympy/sets/sets.py:1350: [Link](https://github.com/sympy/sympy/blob/master/sympy/sets/sets.py#L1350)
- sympy/sets/sets.py:1946: [Link](https://github.com/sympy/sympy/blob/master/sympy/sets/sets.py#L1946)
- sympy/geometry/line.py:1192: [Link](https://github.com/sympy/sympy/blob/master/sympy/geometry/line.py#L1192)

@moorepants Are there any more deprecations that need to be removed ?

**Comment by moorepants** [comment]
We need to make sure we don't remove any that haven't been in deprecated mode for at least one version. So any that have been introduced since 0.7.6 need to stay. But any that have been in deprecated more from 0.7.6 or before, we can remove.

**Comment by kshitij10496** [comment]
Cool.
I will make the necessary fixes

**Comment by asmeurer** [comment]
Be sure to check the "Deprecation Removal" tag on GitHub. Each issue should correspond to a deprecation.

**Comment by kshitij10496** [comment]
@asmeurer Sure.
I will check all the deprecations for their corresponding issues.

**Comment by asmeurer** [comment]
https://github.com/sympy/sympy/pull/10405 was merged. I think this can be closed.

**Comment by kshitij10496** [comment]
@asmeurer Yeah.
I am editing the changelog.
