### ISSUE TITLE
`str(Union)` printer needs parenthesizing love

### ISSUE THREAD

**Issue by cbm755** [sympy/sympy#10415]
I notice Union pretty printing has been improving.  The `str` printer could also use parentheses in (some of?) those cases.  See #7486, #9877, #9878, maybe others.

**Comment by kshitij10496** [comment]
@cbm755 I am looking into this.

**Comment by kotharitrisha** [comment]
@kshitij10496 Has this been addressed? If not, I'd like to take a shot at this!

**Comment by kshitij10496** [comment]
@kotharitrisha Please give it a go.
I haven't made progress on this issue.

**Comment by pt247** [comment]
@cbm755 can you please give me an example where this can be improved?

**Comment by cbm755** [comment]
Hmmm, its definitely not clear what I meant.  I guess things like:
````
>>> pprint((Interval(-oo, 0, True, True) + Interval(S(113)/123, oo, True, True)) * (FiniteSet(1) + Interval(2, 3, True, True)))

⎛          ⎛113   ⎞⎞                 
⎜(-∞, 0) ∪ ⎜───, ∞⎟⎟ × ({1} ∪ (2, 3))
⎝          ⎝123   ⎠⎠                 

>>>: str((Interval(-oo, 0, True, True) + Interval(S(113)/123, oo, True, True)) * (FiniteSet(1) + Interval(2, 3, True, True)))

'(-oo, 0) U (113/123, oo) x {1} U (2, 3)'
````
Note the `str` output is ambiguous whereas the `pprint` output has parentheses.

**Comment by cbm755** [comment]
This looks like its fixed as `str` now prints with `Union(..., ...)`
