### ISSUE TITLE
`pprint(Union, use_unicode=False)` raises error (but `str(Union)` works)

### ISSUE THREAD

**Issue by cbm755** [sympy/sympy#10414]
See `printing/pretty/pretty.py`.

1.  Possible fix:
`union_delimiter = ' %s ' % pretty_atom('Union', 'U')`

2.  Similarly, I wonder if lower-case `n` might be an appropriate ascii character for `Intersection`?  If not, at least throw `NotImplemented` like in `SymmetricDifference`.

**Comment by tokencolour** [comment]
I'll add the tests shortly. 
>I wonder if lower-case n might be an appropriate ascii character for Intersection?

A lower-case `n` looks better than `^`. So I've added the former. Thanks @cbm755 . Please take a look at this.
