### ISSUE TITLE
Can't simplify/rewrite inverse hyperbolic functions

### ISSUE THREAD

**Issue by zamb3zi** [sympy/sympy#10429]
Hi,

I'm trying to simplify `asinh(sqrt(2)/4)` to `log(2)/2` without success. Similarly `asinh(x).rewrite(log)` just returns `asinh(x)` whereas it should give `log(x+sqrt(x**2+1))`.

My wider issue is trying to simplify the following:

```
y = 2*(n-1)*asinh(sqrt(2)/4)
Q = 2**(-n)*(5*sinh(y) + 3*cosh(y))/6
```

which is equal to `(1-4**(-n))/3`. I can make progress with `Q.rewrite(exp)` but the inverse `asinh` won't rewrite so I can't proceed without manually rewriting.

Obviously it would be great if `simplify(Q)` would handle everything automatically.

Thanks.

**Comment by asmeurer** [comment]
Adding the rewrites should be easy.

**Comment by sandeepveethu** [comment]
I would like to fix this.

**Comment by ashutoshsaboo** [comment]
@asmeurer I guess, Is this issue closed? Because, I saw the merged PR above - #10439 .

**Comment by sandeepveethu** [comment]
@ashutoshsaboo  yeah this issue was resolved, but the PR isn't closed, I don't know why. Maybe, this can be closed now.

**Comment by zamb3zi** [comment]
Thanks a lot for this.

**Comment by jksuom** [comment]
It seems that this can be closed.
