### ISSUE TITLE
recognize special literal complex arguments for `log`

### ISSUE THREAD

**Issue by smichr** [sympy/sympy#10428]
Like trig function which give certain simple values for given angles, `log` could use a similar mechanism to automatically simplify certain arguments to their simple form, e.g.

``` python
>> log(S(1/2)+I*sqrt(3)/2)
I*pi/3
```

`pure_complex` could be used to test the argument of log.

**Comment by darkcoderrises** [comment]
Could I work on this?

**Comment by darkcoderrises** [comment]
I have a doubt, I can write -1 as `e**(I*π)`, so should it return I*π for log(-1).

**Comment by jksuom** [comment]
``log`` is a multivalued function and there are two common ways to define its principal branch. In Sympy it is defined by ``-pi < im(log(z)) <= pi`` and the other one is ``0 <= im(log(z)) < 2*pi``. In both cases, ``log(-1)`` will have the value ``pi*I``.

**Comment by darkcoderrises** [comment]
Is something like this, okay?
```
           rad = Abs(arg)
            try:
                if int(rad) == rad:
                    rad = int(rad)
            except:
                pass

            return cls(rad) + S.ImaginaryUnit * Arg(arg)
```

This return `I*atan(1.0*sqrt(3))`

**Comment by gschintgen** [comment]
related: #4612

**Comment by smichr** [comment]
Duplicate of #4612
