### ISSUE TITLE
Dict does not accept collections.defaultdict

### ISSUE THREAD

**Issue by Upabjojr** [sympy/sympy#10433]
Currently, one needs to call

```
Dict(dict(d))
```

if `d` is a _defaultdict_.

**Comment by Upabjojr** [comment]
Should be easy to fix, how can I put a label?

**Comment by tokencolour** [comment]
I would like to try to fix this.

**Comment by architv** [comment]
@Upabjojr Can you please elaborate a bit more about issue?

**Comment by asmeurer** [comment]
The problem is that it's doing direct class comparisons instead of using isinstance.

**Comment by architv** [comment]
@asmeurer So should it support `defaultdict` ?

**Comment by asmeurer** [comment]
yes

**Comment by architv** [comment]
If this is isn't solved yet, I would like to work on this.
