### ISSUE TITLE
Improper integral does not evaluate

### ISSUE THREAD

**Issue by bolverk** [sympy/sympy#10445]
The integral of 1/(exp(x)+1) from 0 to infinity should give log(2), but sympy 0.7.6.1 produces a NaN

```python
from sympy import oo, exp, Symbol, integrate
x = Symbol('x')
integrate(1/(1+exp(x)),(x,0,oo))
```

**Comment by jksuom** [comment]
It appears that the integrator does not recognize improper integrals as limits. It finds the correct indefinite integral ``x - log(exp(x) + 1)``, but, instead of taking the limit ``x -> oo`` it tries to assign the value ``oo`` to ``x`` on [this line](https://github.com/sympy/sympy/blob/master/sympy/integrals/integrals.py#L523) and arrives at ``nan``.

**Comment by sandeepveethu** [comment]
so , @jksuom do we have to leave this issue or try to fix this?

**Comment by gxyd** [comment]
The issue can be tried to solve if possibly you can. He wrote the explanation for what is going wrong according to him.(Most probably that seems right explanation to me as well).

**Comment by jksuom** [comment]
This is an issue that should be fixed. Improper integrals with infinite limits are easy to recognize, and perhaps they could be fixed first. But there are also improper integrals with finite limits where the integrand is singular at an end point. It may be harder to take care of those.

**Comment by shubhamtibra** [comment]
I would like to fix this. @jksuom can you explain how [this line](https://github.com/sympy/sympy/blob/master/sympy/integrals/integrals.py#L523) is working?

**Comment by jksuom** [comment]
It works by computing separately the contribution to the integral of each component of an antiderivative (i.e., arguments of ``Add``) and adding the results. That is fine for (proper) integrals but in this case the increments of the components ``x`` and ``log(x) + 1`` over the infinite interval are infinite, and it is impossible to find the difference afterwards even if it is finite. Therefore, it is necessary to compute the integral first over a finite integral and only then pass to the limit.

**Comment by shubhamtibra** [comment]
The function `_eval_interval`  already  takes care in case `self.subs` return NaN . [link](https://github.com/sympy/sympy/blob/master/sympy/core/expr.py#L750)

**Comment by jksuom** [comment]
I think that in this case ``self.subs`` would return ``oo`` (or ``-oo``) for each component and ``limit`` would produce the same result. The limit should be computed for the total expression, not for each component separately.

**Comment by shubhamtibra** [comment]
Ah, you are right.

**Comment by asmeurer** [comment]
I don't understand why that Add.make_args bit is there. We should definitely remove it.

**Comment by shubhamtibra** [comment]
This issue can be closed now.
