### ISSUE TITLE
ChiSquared CDF does not run

### ISSUE THREAD

**Issue by AddemF** [sympy/sympy#10459]
When I run the code 

> import sympy as sp
> import sympy.stats as stat
> 
> x, y = sp.symbols('x y')
> 
> X = stat.Poisson('X', sp.Rational(1,3)
> print( stat.cdf(X)(x) )
> 
> Y = stat.ChiSquared('Y', 15)
> print( stat.cdf(Y)(y) )

It will print the CDF of the Poisson distribution but it seems to run infinitely and lock up my interpreter when it gets to the Chi Squared distribution.  It does the same for a similar code that ends in 

> print( stat.cdf(Y)(1) )

or other things that work when I try them on other distributions.

**Comment by jksuom** [comment]
It appears that the ``cdf`` integral is computed by ``heurisch``.  It does look for the result by trying to find a suitable linear combination of monomials in the components of the integrand. (In this case those are ``z``, ``sqrt(z)`` and ``exp(-z/2)`` where ``z`` is the integration variable.) The maximum degree of the monomials is computed from the degrees of the components in the integrand, and will in the case of ``ChiSquared`` be nearly twice the value of the parameter.

This means that the time taken by the computation is strongly dependent on the parameter. SymPy computes e.g. ``cdf(ChiSquared('Y', 5))`` in a reasonable time, but the parameter value of 15 leads to so many terms (over 4000) that the computation may, in fact, seem to 'run infinitely' in some installations.

**Comment by AddemF** [comment]
@jksuom I figured the issue would be something like this.  Is there any sort of fix or work-around for this, or will that take some development time?

**Comment by jksuom** [comment]
I don't think there would be any work-around in SymPy. It might be possible to develop a special integrator for some of these ``ChiSquared`` distribution functions, but that would be a major task.

**Comment by ethankward** [comment]
These CDF calculations are now possible and do not hang. Issue resolved?
