### ISSUE TITLE
Dropping Python 2.6 and 3.2 support

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#10463]
Once SymPy 1.0 is out, we should drop Python 2.6 and 3.2 support. Python 2.6 reached its end-of-life in 2013 and 3.2 will reach it on February 20 of this year (which will likely be before 1.0 goes out at the rate we are going). See https://docs.python.org/devguide/#status-of-python-branches. I don't think we should support Python versions that have reached end-of-life. 

Additionally, with https://github.com/sympy/sympy/pull/10084, we now support 7 Python versions (including PyPy), resulting in a total of 44 builds on Travis. This is too much. Travis only runs 10 builds at a time for all of SymPy, meaning every push to every pull request has 44 builds and only 10 of those, globally, can run at once. If we drop these two Python versions we can remove 9 of those builds. 

Finally, this will open up a lot of syntactic features in the language that we've heretofore been unable to use. See https://docs.python.org/dev/whatsnew/2.7.html for a full list, but the main ones are set and dictionary comprehensions, set literals, and unicode literals (no more `u()`). 

Please **DO NOT DO ANYTHING** on this issue until after SymPy 1.0 is released.

**Comment by moorepants** [comment]
+1. I've seen chatter on the other SciPy stack projects about the same thing. Many have already dropped support.

**Comment by stonebig** [comment]
Why don't you stop targeting Python 3.3 / 3.4 at the same time ?
- Previous version users can live with the awesome 1.0.
- forbiding sympy to use the "@" may be a torture for future contributors.

**Comment by asmeurer** [comment]
`@` isn't a huge carrot for SymPy, since it has separate types for matrices (meaning `*` is always matrix multiplication on matrices). Personally the biggest carrot in 3.5 is the new star unpacking stuff, but we can live without it, just as we've lived without dictionary comprehensions and set literals. 

We aren't going to drop Python 2 support until the community does (at least until 2020 when CPython stops supporting it). 

I think we should make it an official policy to support whatever Python versions are still supported by core Python for security releases.

**Comment by asmeurer** [comment]
Now that 1.0 is out, this can be fixed.

Another thing that will need to be fixed here is that the VM used by the release scripts uses Python 3.2, so we will need to use an updated VM.

**Comment by AnishShah** [comment]
@asmeurer I will work on this..
apart from removing travis build for Python 2.6 and 3.2, can you tell me what needs to be done?

**Comment by AnishShah** [comment]
Should I replace `set() , dict()` to `{}`?

**Comment by asmeurer** [comment]
You should remove things from the compatibility file that are no longer necessary. 

You can also replace set with set literals and use set dictionary comprehensions if you want, but it isn't required. The old way still works. 

We also need to figure out the release process, as I noted in my previous comment.

**Comment by asmeurer** [comment]
And I guess grep the repo for "2.6" and "3.2" to see if there are any other compatibility things that can be removed.
