### ISSUE TITLE
integrate(sinc(x)**2, (x, -oo, oo)) can't do it

### ISSUE THREAD

**Issue by certik** [sympy/sympy#10464]
But the algorithm itself can do it:
```
In [7]: integrate(sinc(x)**2, (x, -oo, oo))
Out[7]: 
∞             
⌠             
⎮      2      
⎮  sinc (x) dx
⌡             
-∞            

In [8]: integrate((sin(x)/x), (x, -oo, oo))
Out[8]: π

In [9]: integrate((sin(x)/x)**2, (x, -oo, oo))
Out[9]: π
```
I.e. [7] is equivalent to [9].

**Comment by leosartaj** [comment]
I am not very well acquainted with the integration routines. One way of doing this is to internally call ``sinc(x).rewrite(sin)``. Not really sure if it's the best way.

**Comment by shubhamtibra** [comment]
I would like to work on this.

**Comment by asmeurer** [comment]
Probably sinc needs to be added to the meijerg tables (meijerg is what is computing the sin(x)/x integral).

**Comment by shubhamtibra** [comment]
@asmeurer where is the code of meijerg tables located?

**Comment by jksuom** [comment]
sympy/integrals/meijerint.py

**Comment by shubhamtibra** [comment]
Where to get the Meijerg-G representation of sinc?
I guess it is `**G ( [ ], [ ], [ -1/2 ], [ -1 ],  t**2/4, sqrt( pi ))**`

**Comment by jksuom** [comment]
I think you have to derive it from the representation of sin the way your guess indicates. But I suspect that the constants should be re-checked.

**Comment by jksuom** [comment]
This is what I get
```
In [6]: hyperexpand(meijerg([], [], [-S(1)/2], [-1], t**2/4))
Out[6]: 
4⋅sin(t)
────────
     2  
 √π⋅t   
```
It is close, but not quite right.

**Comment by certik** [comment]
I would start with hypergeometric functions first, and then convert those to meijerg in a second step.
You start with `sin(x) = x * 0F1(3/2; -x^2/4)` and get:
```
sinc(x) = sin(x)/x = x * 0F1(3/2; -x^2/4) / x = 0F1(3/2; -x^2/4)
```
Then you square it:
```
sinc^2(x) = 0F1^2(3/2; -x^2/4) = 2F3(3/2,1; 3/2,3/2,2; -x^2)
```
So now we just need to convert `2F3(3/2,1; 3/2,3/2,2; -x^2)` to a meijerg function.

**Comment by asmeurer** [comment]
I'm not sure if you have to add the square to the tables as well.

**Comment by certik** [comment]
I started discussing this here: https://groups.google.com/d/topic/sympy/S0MSlsAhL74/discussion, I think we can definitely improve the Meijer G-function rewriting in general.
