### ISSUE TITLE
summation(1/x**y, (x, 1, oo)) doesn't do it

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#10471]
The answer should be `zeta(y)` (https://en.wikipedia.org/wiki/Riemann_zeta_function).

```
In [10]: summation(1/x**y, (x, 1, oo))
Out[10]:
  ∞
 ___
 ╲
  ╲    -y
  ╱   x
 ╱
 ‾‾‾
x = 1
```

**Comment by darkcoderrises** [comment]
I would like to give it a try, could someone mentor me?

**Comment by AnishShah** [comment]
I read the source code and it appears that `hypersimp` returns None as zeta is not hypergeometric.

**Comment by AnishShah** [comment]
I think, I can solve this, but I'm not sure if my way is a good way of solving this issue, I will send a PR in sometime.
