### ISSUE TITLE
zeta(2 + I).is_finite returns None

### ISSUE THREAD

**Issue by gxyd** [sympy/sympy#10475]
Atleast `zeta(x)` for `Re(x) > 1` and `Im(x)` being finite it should return `True`.

**Comment by jksuom** [comment]
Actually the (analytically continued) Riemann zeta function is finite in the whole plane except at 1 where it has a simple pole.

**Comment by gxyd** [comment]
Ok, i didn't knew the term `Analytic Continuation` (now i read it). It is sure to me that `zeta` function for `Re(x) > 1` is defined by summation of `1/n**s` from `n = 1 to oo` but for the remaining domain i.e `C \ {z | Re(z) > 1}` how is the function defined? (mathematically by which expression).
Since i know that `∑ 1/n**s` for `s = 1/2` is divergent hence equals `infinity`(mathematical) but you already said `zeta(1/2)` should be finite. So how is it defined for the remaining domain?

**Comment by jksuom** [comment]
There are integral expressions for zeta that make sense for all complex values, but those may not be useful for computations.
An elementary way of extending the domain to ``Re(s) > 0`` is the following (dating back to Euler, I think). If you multiply the zeta  series by ``1 - 2**(1 - s)``, you get a similar alternating series, and this series is convergent if ``Re(s) > 0``. The remaining arguments can be taken care of, at least in theory, by Riemann's functional equation than expresses ``zeta(s)`` in terms of ``zeta(1 - s)``.

**Comment by ashutoshsaboo** [comment]
Is this issue solved? I would like to work on this issue. Can I work on this or is it already solved?

**Comment by gxyd** [comment]
No, this has not been solved. You can work on this

**Comment by architv** [comment]
I would like to work on this one.

**Comment by architv** [comment]
@gxyd What all values should I test for?
