### ISSUE TITLE
Gotchas docs for 1/2 and SymPy Live

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#10484]
If you run the code blocks at http://docs.sympy.org/latest/tutorial/gotchas.html#two-final-notes-and in SymPy Live the 1/2 examples are wrapped by Integer by SymPy Live, so they don't show what they are supposed to show. We should add a small note about this to the page.

**Comment by ngaurav** [comment]
similar exception applies to type(1 + 1) example as well

**Comment by debodirno** [comment]
How do I edit the documentation ? I wish to contribute to sympy.

**Comment by leosartaj** [comment]
@debodirno Read [this](https://github.com/sympy/sympy/wiki/Introduction-to-contributing#documentation)

**Comment by aktech** [comment]
Closed via #10493
