### ISSUE TITLE
Mathematical Symbol does not seem to serialize correctly LaTeX printer

### ISSUE THREAD

**Issue by Gjacquenot** [sympy/sympy#10489]
I would like to declare a Sympy symbol, that looks like `C_{x_{0}}` when displayed as a LaTeX string.

I have tested the following

    from sympy import Symbol, latex
    Cx0=Symbol('{C_{x_{0}}')
    latex(Cx0)

However, the result is not as expected, the second underscore is not present. I obtain

    '{C_{{x {0}}}'

Does anyone has a clue on how to display any mathematical LaTeX expression?

I have tested the option `mode="equation"`, with no success

I have posted this question on [stackoverflow](http://stackoverflow.com/questions/35072145/sympy-how-to-declare-mathematical-symbol-with-any-latex-string)

**Comment by annakovale** [comment]
I believe the issue is because  def _deal_with_super_sub(self, string) in Latex.py is not recursive. 

Consider the following: 
>>> L = Symbol('{L^{x_{0}}}')
>>> latex(L)
{L^{{x}_{{0}}}}

>>> j = Symbol('{C_{x_{y}}}')
>>> latex(j)
{C_{{x {y}}}}

**Comment by asmeurer** [comment]
It seems to me that if a symbol name has `{` in it that the latex printer should just print it as is.

**Comment by Gjacquenot** [comment]
Well, I have tried to find the problem. As @annakovale mentioned, the string is not correctly dealt in method `_deal_with_super_sub` of `latex.py`. Maybe we could replace the method `_deal_with_super_sub` with the following: I have updated the `" ".join` instructions with `"^".join` and `"_".join`. It works for me, but : 

- what are the consequences for other people
- the subscripts and upperscripts should be considered recursively in function `split_super_sub`
- maybe exception rules should be created so as not to consider everything between braces



        class LatexPrinter(Printer):
    
            ...
            def _deal_with_super_sub(self, string):
        
                name, supers, subs = split_super_sub(string)
        
                name = translate(name)
                supers = [translate(sup) for sup in supers]
                subs = [translate(sub) for sub in subs]
        
                # glue all items together:
                if len(supers) > 0:
                    name += "^{%s}" % "^".join(supers)
                if len(subs) > 0:
                    name += "_{%s}" % "_".join(subs)

**Comment by asmeurer** [comment]
You can try making the change and then running `./bin/test latex`. That will at least tell you if it breaks any of the existing tests.

**Comment by asmeurer** [comment]
And I'm still slightly in preference to my suggestion to not do any translation if the symbol name has `{` (probably also `\`). That would likely actually break things for some people, but it's a cleaner design, because you don't have to try to understand all the translations that SymPy does and how to potentially work around them just to get symbols to print the way you want. You can just write the exact LaTeX that you want if you know what that is.

**Comment by Gjacquenot** [comment]
I have added a single commit to fix the latex printing issue #10489. The solution is really simple and does not break existing tests. An additional test has been added. @asmeurer maybe you can have a look?

**Comment by asmeurer** [comment]
Can you create a pull request? It looks good.

**Comment by Gjacquenot** [comment]
@asmeurer : I did only one commit and have done some rebase operations to fetch sympy master head. The pull request was created 3 days ago here: #10548

**Comment by asmeurer** [comment]
In the future, create a new branch before making a pull request. You should never commit directly to master.
