### ISSUE TITLE
Apply inverse() on custom functions

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#10487]
See https://stackoverflow.com/questions/35060127/sympy-simplifying-of-inverse-function. If you define `inverse` on a custom function, it works with `solve`, but you can't actually reduce it, like `f(g(x))` -> `x` (if `f(x).inverse() == g`).  Probably `simplify` should do it.

**Comment by asmeurer** [comment]
This is probably easy to fix.

**Comment by AnishShah** [comment]
I will work on this..

**Comment by AnishShah** [comment]
@asmeurer I have opened a PR.. please check
