### ISSUE TITLE
MatrixSymbol Needs Differentiation Ability

### ISSUE THREAD

**Issue by dusenberrymw** [sympy/sympy#10509]
Currently, it does not appear to be possible to take a partial derivative of an expression of `MatrixSymbols`, failing with the error `'MatrixSymbol' object has no attribute '_diff_wrt'`.

The following example highlights this:

```
A = MatrixSymbol('A', 3, 2)
B = MatrixSymbol('B', 2, 3)
expr = A*B
diff(expr, A)
```
```
...
AttributeError: 'MatrixSymbol' object has no attribute '_diff_wrt'
```

This would be great for the project to have, especially for those working with vectorized functions.

**Comment by moorepants** [comment]
What is your expected answer for the above example?

Are you requesting this: https://en.wikipedia.org/wiki/Matrix_calculus#Scalar-by-matrix?

**Comment by asmeurer** [comment]
Related (or possibly a duplicate) https://github.com/sympy/sympy/issues/5858

**Comment by asmeurer** [comment]
Actually I'm going to say that this is a duplicate.

**Comment by dusenberrymw** [comment]
@moorepants Apologies for the delay.  As a followup, I would expect `B` for the given expression `dA*B/dB`.

@asmeurer Thanks.  From the opening post (~2011) on that PR, it looks like differentiation on MatrixSymbols was once possible (albeit, possibly incorrect).  Was this removed at some point?

**Comment by asmeurer** [comment]
It did work but it was completely wrong, so we removed it (non-behavior is better than wrong answers).

**Comment by dusenberrymw** [comment]
@asmeurer Agreed.  Incorrect behavior is worse than lack of functionality.

**Comment by moorepants** [comment]
Just saw this paper:

http://www.matrixcalculus.org/matrixcalculus.pdf

and website:

http://www.matrixcalculus.org/matrixCalculus

SymPy should be able to do these things and the code gen the results.

**Comment by asmeurer** [comment]
Yes, I think it could be useful for taking an expression that manipulates an ndarray (for instance, using something like uarray, or even just parsing some code) and translating it into a high level tensor or matrix expression.

**Comment by Upabjojr** [comment]
https://github.com/sympy/sympy/pull/15615
