### ISSUE TITLE
Try codecov (code coverage)

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#10519]
See https://github.com/cloudpipe/cloudpickle/pull/48#issuecomment-169821928 for an example of why this is cool. We could also try coveralls (see my ancient attempt to get it working at https://github.com/sympy/sympy/pull/1960).

**Comment by isuruf** [comment]
Codecov is much better. In SymEngine, we tried both and codecov is better because of the ability to see the coverage of the lines changed in the PR, seeing the lines of new files in the PR and the browser extensions.

**Comment by asmeurer** [comment]
Yep, from what I've seen, codecov is better. It should be trivial to get set up. Let's definitely disable the commenting on PRs if we do, though (that's really annoying).

**Comment by sylee957** [comment]
I have rebased the old branches to my fork, and could generate some coverage reports, despite some timeout issues

https://codecov.io/gh/sylee957/sympy/branch/codecov

But I don't know whether this project is valid at this point.

**Comment by moorepants** [comment]
We would like to have some kind of coverage reporting that works consistently on CI. There are different options. If you have something working, I recommend submitting a PR for discussion.

**Comment by asmeurer** [comment]
Let me know if you need me to enable a GitHub integration.
