### ISSUE TITLE
simplify solveset/solve result for functions containing Abs

### ISSUE THREAD

**Issue by smichr** [sympy/sympy#10532]
It seems like the following

```
>>> solveset(abs(x+1)-y,x,S.Reals)
Intersection([-1, oo), {y - 1}) U Intersection((-oo, -1], {-y - 1})
```

is not quite right. With #10158 work, I think this will become

```
Intersection([0, oo), {y}) U Intersection([0, oo), {y}) ->
Intersection([0, oo), {y})
```

and that is definitely wrong since that doesn't give the right value of `x` for the original expression.

What is the better way to state this in terms of sets?  Stated directly we would say that the solution is values of `x` equal to `y - 1` if `x + 1>0` is positive else `-1 - y` if `x + 1 is negative`.

And `solve` gives a strange result, too:

```
>>> solve(abs(x+1)-y,x)
[-y - 1, Piecewise((y - 1, y >= 0), (nan, True))]
```

**Comment by smichr** [comment]
I think the expression that should be returned is

```
ConditionSet(x, y >= 0, {-y - 1, y - 1})
```

But that will return an error if we substitution `I` for `y`, so perhaps

```
>>> ConditionSet(x, Intersection(Interval(0,oo), FiniteSet(y)),
... FiniteSet(-y - 1, y - 1))
ConditionSet(x, Intersection([0, oo), {y}), {-y - 1, y - 1})
>>> _.subs(y, -1)
ConditionSet(x, EmptySet(), {-2, 0})
```

But that doesn't evaluate when replacing `y` with a bad value because the condition doesn't become a bool. Contains is probably the better form to use:

```
>>> sol = ConditionSet(x, Contains(y, Interval(0, oo), evaluate=False),
... FiniteSet(-y - 1, y - 1)); sol
ConditionSet(x, Contains(y, [0, oo)), {-y - 1, y - 1})
>>> sol.subs(y,-1)
EmptySet()
>>> sol.subs(y, 1)
{-2, 0}
```

An unevaluated `Contains` must be used or else it becomes an `And` with Relationals that will fail a substitution with an imaginary value of `y`:

```
>>> Contains(y, Interval(0, oo))
And(y < oo, y >= 0)
>>> _.subs(y, I)
>>> _.subs(y,I)
Traceback (most recent call last):
...
TypeError: Invalid comparison of complex I
```

**Comment by yash14123** [comment]
Please assign me this task.

**Comment by Shekharrajak** [comment]
```
>>> solveset(abs(x+1)-y,x,S.Reals)
([-1, ∞) ∩ {y - 1}) ∪ ((-∞, -1] ∩ {-y - 1})
```
according to [this doc](https://github.com/sympy/sympy/blob/master/doc/src/modules/solvers/solveset.rst#how-does-solveset-ensure-that-it-is-not-returning-any-wrong-solution)
above answer is expected , right ?

```
>>> x = symbols('x', positive=true)
>>> solveset(abs(x+1)-y,x,S.Reals)
ℝ ∩ {y - 1}             #correct
```
```
>>> y = symbols('y', positive =true)
>>> solveset(abs(x+1)-y,x,S.Reals)
{-y - 1, y - 1}        #correct
```
```
>>> y = symbols('y', negative =true)
>>> solveset(abs(x+1)-y,x,S.Reals)
∅                       #correct
```
```
>>> x = symbols('x', negative =true)
>>> solveset(abs(x+1)-y,x,S.Reals)
([-1, ∞) ∩ {y - 1}) ∪ ((-∞, -1] ∩ {-y - 1})
                # seems wrong ; should be R ∩ {-y-1}
```

**Comment by asmeurer** [comment]
+1. I came to the same conclusion myself, that it should use a ConditionSet. There was a typo in the solveset docs which really confused me about this, but even fixed, the solution form is very confusing. And that would only get worse for more complicated solutions of this form (say, of equations with multiple abs or multiple symbolic parameters).

**Comment by aktech** [comment]
+1

**Comment by smichr** [comment]
See also my comment -- for some reason these links never quite get me to the comment, don't know why, but you should see it on the page -- [here](https://github.com/sympy/sympy/issues/9586#issuecomment-184321410)

**Comment by asmeurer** [comment]
> But that will return an error if we substitution I for y

I think that is fine. Functions that determine the truth value of inequalities in condition sets should set an inequality to be false when it is complex. That is, something like I ∈ {x | x > 1} will be false because I > 1 gives false (put another way, `a > b` should implicitly mean `a ∈ ℝ ∧ b ∈ ℝ ∧ a > b`).

**Comment by asmeurer** [comment]
(the link doesn't bring you to the comment because the page isn't long enough to bring the comment all the way to the top)

**Comment by kshitij10496** [comment]
@smichr I would like to implement your idea for solving atleast expressions containing `abs`.
