### ISSUE TITLE
aboutus page in the documentation

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#10533]
I think we should consider getting rid of the "aboutus" page in the documentation (http://docs.sympy.org/latest/aboutus.html#sympy-development-team) (or rather, specifically, the list of people on that page). Reasons:

- The page is duplicated against the [AUTHORS file](https://github.com/sympy/sympy/blob/master/AUTHORS).
- The AUTHORS file is updated automatically with the `bin/authors_update.py` script, but aboutus is not. Currently the aboutus page is very out of date (there are currently 38 people missing, if I did my math right). 
- The aboutus page is not so easy to update automatically, because it has a description of what each person did. This has to be added manually.
- However (and this is the key issue), these descriptions tend to be wrong. What happens is that the first time someone contributes something, their description is updated for the patch that they submitted. But then if that person makes a lot more contributions, maybe even becomes a core contributor, their description on the aboutus page is generally not updated. 

Some examples of this, just scrolling through

- "Sean Vig: Quantum improvement" (Sean did a GSoC that wrote a significant part of the quantum module)
- "Tom Bachmann: fixes to Real" (That must have been Tom's first patch. His main contribution at this point is the entire meijerg integration and summation algorithm, as well as tons of special functions improvements)
- "David Li: Documentation fixes" (also the manualintegrate module)
- "Kalevi Suominen: fix to assumptions" (he has tons of various improvements everywhere by now)

The list goes on. Those are just what I know, off the top of my head. But I'm not expert on every contributor and what they've contributed. To really fix this we would have to do research for each person in the git history. And even if we did, it would soon get out of date again.

So I think we should remove the list of people with descriptions. We can write something about ways to find who the contributors and and what they contributed using git/GitHub. We should then link to the AUTHORS file. Alternately, if it's possible we should source in the AUTHORS file directly, so that the list of names is still there in the docs. 

Thoughts?

**Comment by smichr** [comment]
+1 for the reasons cited. The commit log already contains a history of what a person has done.

**Comment by asmeurer** [comment]
See https://github.com/sympy/sympy/pull/10535.
