### ISSUE TITLE
simplification of ConditionSet with FiniteSet

### ISSUE THREAD

**Issue by smichr** [sympy/sympy#10565]
Should the following just simplify (automatically) to {0}?

```
>>> ConditionSet(x, And(x < 1, x > -3), FiniteSet(0, 1, 2))
ConditionSet(x, And(x < 1, x > -3), {0, 1, 2})
```

If the set (last arg) is a FiniteSet, and all elements cause the condition to be evaluated (True or False) then perhaps the filtered FIniteSet should be returned.

**Comment by jksuom** [comment]
+1

**Comment by AnishShah** [comment]
working on this..
