### ISSUE TITLE
flag bad input to ConditionSet?

### ISSUE THREAD

**Issue by smichr** [sympy/sympy#10566]
The 2nd arg to ConditionSet is supposed to be an expression that returns True or False when a value from the last arg (a set) is substituted into it, e.g. `ConditionSet(x, x > 1, S.Integers)`. But there is no checking of that 2nd arg which is a feature that allows one to use an expression,

```
>>> 4 in ConditionSet(x, x%3, S.Integers)
True
>>> 3 in ConditionSet(x, x%3, S.Integers)
False
```

Although that makes sense, other input does not (as far as I can tell):

```
>>> ConditionSet(x, Interval(1, 2), S.Reals)
ConditionSet(x, [1, 2], (-oo, oo))
```

Should we be raising an error for bad input to the 2nd arg or just leave it as garbage in garbage out?

**Comment by oscarbenjamin** [comment]
These examples all raise TypeError now.
