### ISSUE TITLE
autowrap.autowrap: TypeError: can only concatenate tuple (not "list") to tuple

### ISSUE THREAD

**Issue by ronanpaixao** [sympy/sympy#10571]
autowrap.autowrap says this about the `args` parameter:

> args : iterable, optional
> An iterable of symbols. Specifies the argument sequence for the function.

However, it only allows lists. For example, a tuple raises TypeError:
```python
from sympy.utilities import autowrap
from sympy.abc import x, t
func = autowrap.autowrap(expr, args=(x, t))
```
```python
Traceback (most recent call last):

  (...)

  File "D:\Anaconda\lib\site-packages\sympy\utilities\autowrap.py", line 528, in autowrap
    routine = make_routine('autofunc', expr, args + new_args)

TypeError: can only concatenate tuple (not "list") to tuple
```

**Comment by jerli** [comment]
I addressed this by adding one line to check if args is a tuple, then if it is, converting args to a list so that the rest of the function should work as expected. 
I'm about to submit a pull request, but this is my first time contributing to SymPy, so let me know if there's any issues.

**Comment by Nitin216** [comment]
If this is open i would like to work on this one.

**Comment by asmeurer** [comment]
This was fixed by https://github.com/sympy/sympy/pull/10587
