### ISSUE TITLE
Should `has` try `in` for collections like Sets?

### ISSUE THREAD

**Issue by cbm755** [sympy/sympy#10573]
For `FiniteSet`, `in` and `has` do the same thing.

But for other `Sets` they do not.  So we have things like:

```
>>> A = Interval(2, 4, true, false)   # note half-open
>>> A
(2, 4]

>>> 2 in A      # correct
False

>>> A.has(2)    # ??
True

>>> 3 in A      # correct
True

>>> A.has(3)    # ??
False
```

Having read the code, I know why this happens (`has` checks the atoms/args).  But potentially confusing...
1.  Is this by design?  (I haven't looked at what is using `has`).
2.  Should we change `has` to try `in` when the object is a collection?
3.  If not, should we document this somehow?  Currently `has` doc says:
   
   > Test whether any subexpression matches any of the patterns.
   
   Its not clear what a "subexpression" is in the context of an infinite set.

**Comment by asmeurer** [comment]
I believe `has` is supposed to be strictly an expression tree algorithm, with no knowledge of mathematics.

**Comment by cbm755** [comment]
Ok thanks.  Perhaps I should patch the `has` docs to note something like that.

(Also, just FTR: I was wrong about them being the same for `FiniteSet`: lots of things can go wrong if you `has` to try to test for set membership: *just don't do that*.)

**Comment by asmeurer** [comment]
Yes, the docstring could be improved. Implicitly, any method defined on `Basic` itself should be a structural algorithm (no mathematics), but this is not always made explicit.

**Comment by oscarbenjamin** [comment]
I'm not sure there's anything left to fix here...
