### ISSUE TITLE
N-dim array documentation not showing

### ISSUE THREAD

**Issue by Upabjojr** [sympy/sympy#10599]
N-dim array documentation not showing on the website:

http://docs.sympy.org/dev/modules/tensor/array.html

@asmeurer better solve this before 1.0 is out, I've been writing quite a lot so that end-users have an easy introduction.

When I call `make html` on my computer, that page gets displayed.

I cannot reproduce this problem on my computer.

**Comment by SalilVishnuKapur** [comment]
Hie ,
I would like to work on this . Kindly assign it to me .

**Comment by moorepants** [comment]
The dev docs have to be manually updated. I think Aaron and Ondrej may only have permissions to do this.

**Comment by Upabjojr** [comment]
`Last updated on Feb 11, 2016. Created using Sphinx 1.3b2. `

They were created on 11 February, documentation was already there.

**Comment by Upabjojr** [comment]
Maybe all `\` in the LaTeX documentation should be escaped `\\` ?

**Comment by jksuom** [comment]
Maybe not necessarily if raw strings are used.

**Comment by asmeurer** [comment]
I built the docs locally on the release branch and it shows up there. Maybe somehow @aktech missed it when he did https://github.com/sympy/sympy_doc/pull/16

**Comment by asmeurer** [comment]
It works in the "latest" docs. http://docs.sympy.org/latest/modules/tensor/array.html. I don't know what happened with the dev docs. Probably if you rebuild them they will work.

**Comment by Upabjojr** [comment]
OK, issue is closed.
