### ISSUE TITLE
imageset could simplify expression

### ISSUE THREAD

**Issue by smichr** [sympy/sympy#10598]
Consider

```
y, a = symbols('y,a')  
solveset(sin(y + a) - sin(y), a, domain=S.Reals)
--> produces
Union(imageset(Lambda(n, 2*n*pi), S.Integers),  
imageset(Lambda(n,  -I*(I*(2*n*pi +arg(-exp(-2*I*y))) + 2*im(y))), S.Integers))
```

Somewhere, it would be nice to get that `-I` and `I` distributed into the expression. It's probably overkill to use `simplify`, but perhaps there is a better way to do an `expand_mul` or something so expressions like this are somewhat simplified.

**Comment by oscargus** [comment]
In the current version it produces `ImageSet(Lambda(_n, 2*_n*pi), Integers)` so something has happened. Not sure if it is enough to close it.

(There are other cases with different types of Unions of ImageSets that can be simplified further, which is why I stumbled upon this.)

**Comment by oscarbenjamin** [comment]
The listed example is fixed very nicely:
```
In [10]: y, a = symbols('y,a')   
    ...: solveset(sin(y + a) - sin(y), a, domain=S.Reals)                                                                                      
Out[10]: {2⋅n⋅π | n ∊ ℤ}
```

We should think of others or close this.
