### ISSUE TITLE
Range reverses backwards ranges

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#10606]
```
In [13]: list(range(-1, -10, -1))
Out[13]: [-1, -2, -3, -4, -5, -6, -7, -8, -9]

In [14]: list(Range(-1, -10, -1))
Out[14]: [-9, -8, -7, -6, -5, -4, -3, -2, -1]
```

Range needs to keep the right order so that it is useful for code generation (https://github.com/sympy/sympy/pull/10486).

**Comment by asmeurer** [comment]
Question about infinite ranges. Right now, `iter(Range(-oo, 1))` just iterates backwards. Should it continue to do this, or should it raise an exception?

**Comment by SalilVishnuKapur** [comment]
I am receiving error <generator object __iter__ at 0x7f8c9b478b48>  while running iter(Range(-oo, 1)). I want to work on this issue .Kindly guide how to proceed further.

**Comment by asmeurer** [comment]
What error do you get? It is working for me.

**Comment by asmeurer** [comment]
```
In [5]: i = iter(Range(-oo, 1))

In [6]: next(i)
Out[6]: 0

In [7]: next(i)
Out[7]: -1

In [8]: next(i)
Out[8]: -2

In [9]: next(i)
Out[9]: -3
```

**Comment by AnishShah** [comment]
Works fine for me on the latest master.
If we correct the order of `Range`, I think, it should raise an Exception as `-inf` is not a finite term.

**Comment by SalilVishnuKapur** [comment]
No it works fine here as well, i restarted the kernel and it worked. I was wondering if you could tell me where in sympy directory do i need to look to fix the list(Range(-1, -10, -1)) that would be great.

**Comment by AnishShah** [comment]
@SalilVishnuKapur sympy/sets/fancysets.py

**Comment by SalilVishnuKapur** [comment]
Thanks @AnishShah . But regarding raising an exception , in my opinion it shouldn't because maybe in some indefinite problem we need the values in negative till some condition holds. What do you think ?

**Comment by asmeurer** [comment]
I don't think we should disallow infinite ranges. They already work and are useful. 

@SalilVishnuKapur you should know that I am already working on this.

**Comment by AnishShah** [comment]
Okay @asmeurer . I was thinking that the behaviour of Range should be the same for everything.
`start, start + step, start + 2*step, ... , `. But, in Range(-oo, 1) , it iterates backwards.
But, as you said that infinite ranges are useful, then I think we should keep this as it is.

**Comment by asmeurer** [comment]
They are useful, but I am wondering if `iter(Range(-oo, 1))` shouldn't raise an exception, since it the only way to iterate through it is to change the order (same with `iter(Range(oo, 1, -1))`).  `iter(Range(1, oo))` would still work. 

The confusion here is that Range is a Set, which is generally unordered, but to be useful, it really needs to maintain order always. `list(Range(3)) == [1, 0, 2]` would also be not useful.  So even though for other infinite sets (like `S.Integers`), iterating through them works, for Range, I think it would be better to raise an exception for `iter(Range(-oo, 1))`, because it could catch errors.

@aktech @hargup you both work quite a bit on the sets module. What do you think?

**Comment by asmeurer** [comment]
Finding some interesting bugs here by the way

```
In [18]: Range(2, 30, 5)
Out[18]: {2, 7, …, 22}

In [19]: list(range(2, 30, 5))
Out[19]: [2, 7, 12, 17, 22, 27]

In [20]: Range(2, 30, 5).sup
Out[20]: 25
```

**Comment by gxyd** [comment]
I get this: (which looks fine)
```
>>> Range(2, 30, 5).sup
27
```

**Comment by asmeurer** [comment]
You're right. I think these are some bugs that I introduced myself in the process of fixing this.

**Comment by hargup** [comment]
I don't have a strong opinion on this one. I don't remember a case where we had to use `iter(Range(-oo, 1))` so it might not hurt raising an error for it. But I don't feel there is strong case to disallow them either, because mathematically infinite ranges are iterable and it is very easy to check if a range is finite or not, as you said this will also be inconsistent with the behavior of `S.Integer`.

**Comment by smichr** [comment]
> but to be useful, it really needs to maintain order always. list(Range(3)) == [1, 0, 2] would also be not useful

I saw this always-increasing ordering when I worked on the recent PR to recognize range/xrange. I thought it makes sense and would still lobby for keeping it that way. It is a set (as you say). If you want the elements of a set to be ordered, you have to pick the appropriate ordering that you want. Or, 
1. don't use Range when you should (perhaps) be using `range`
1. use list(sorted(Range(3))) if you want the values sorted

In what case(s) is `Range` more useful that `range`? 
Are there other sets that we expect to maintain order?

**Comment by asmeurer** [comment]
It's useful because it's a SymPy object, so we can put it in SymPy expressions. You might argue that one could just use a Tuple, but

- `Range` allows very large ranges, without storing them in memory.
- `Range` allows infinite ranges.
- `Range` presently doesn't allow symbolic bounds, but I'll probably end up adding them at some point.
- `Range(start, stop, step)` is more useful for code generation than the tuple of values because, at least for C and C-like languages, that will generate, when used as part of a for loop, something like `for (i = start; i < stop; i+=step)`.

As a set it's useful because we can do things like intersection calculations. 

The code generation is the primary reason I'm working on this (see the `For` object at https://github.com/sympy/sympy/pull/10486).
