### ISSUE TITLE
linear_eq_to_matrix fails on unsimplified version of equation

### ISSUE THREAD

**Issue by RmStorm** [sympy/sympy#10608]
For some reason the function linear_eq_to_matrix from solveset fails when used in a certain manner without any error! It simply returns 0's.

I have an equation which is part of a set of equations. Feeding it into linear_eq_to_matrix gives a row of zeros. When using simplify(eq), linear_eq_to_matrix does correctly recognize the terms and returns the correct answer.

Attached are 2 files, one file with only the bug and one with the assignment in which I discovered the bug. It is added for context. Also in the bigger file another version of the bug manifests itself. eq3 is only partly parsed by linear_eq_to_matrix and expand(eq3) is parsed correctly.

I tested the bug on two machines: both have anaconda installed and the developer version of sympy.

[ass1.py.txt](https://github.com/sympy/sympy/files/133230/ass1.py.txt)
[linear_eq_to_matrix_BUG.py.txt](https://github.com/sympy/sympy/files/133202/linear_eq_to_matrix_BUG.py.txt)

**Comment by Shekharrajak** [comment]
Can you paste only those lines code, on which you are getting problem?

**Comment by RmStorm** [comment]
This is directly from the linear_eq_to_matrix_BUG.txt the bug happens in the last line of code.
----------------------
from sympy import *

t,l = symbols('t l');
x2, phi1, phi2 = symbols('x2 phi1 phi2');
eq9 = l*cos(phi1(t)) - (x2(t) - l/2 * cos(phi2(t)));
U = (phi1(t).diff(t,2),x2(t).diff(t,2),phi2(t).diff(t,2));

A1, b1 = linear_eq_to_matrix([eq9.diff(t,2)], U);
A2, b2 = linear_eq_to_matrix([simplify(eq9.diff(t,2))], U);
--------------------------------------
The problem is that A1 is only zeros while A2 has the correct values. Running simplify on eq9.diff(t,2) before feeding it into linear_eq_to_matrix  gives different results which it definitely should not do.

In the other file this problem shows up in its context and also a different version of the bug where expanding an equation before linear_eq_to_matrix gives a different result.

**Comment by oscarbenjamin** [comment]
Updated the example
```
from sympy import *

t,l = symbols('t l')
x2, phi1, phi2 = symbols('x2 phi1 phi2', cls=Function)
eq9 = l*cos(phi1(t)) - (x2(t) - l/2 * cos(phi2(t)))
U = (phi1(t).diff(t,2),x2(t).diff(t,2),phi2(t).diff(t,2))

A1, b1 = linear_eq_to_matrix([eq9.diff(t,2)], U)
A2, b2 = linear_eq_to_matrix([simplify(eq9.diff(t,2))], U)
```

Both examples now fail with
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
~/current/sympy/sympy/t.py in <module>
      6 U = (phi1(t).diff(t,2),x2(t).diff(t,2),phi2(t).diff(t,2))
      7 
----> 8 A1, b1 = linear_eq_to_matrix([eq9.diff(t,2)], U)
      9 A2, b2 = linear_eq_to_matrix([simplify(eq9.diff(t,2))], U)

~/current/sympy/sympy/sympy/solvers/solveset.py in linear_eq_to_matrix(equations, *symbols)
   1960             raise ValueError(filldedent('''
   1961             Expecting a Symbol but got %s
-> 1962             ''' % i))
   1963 
   1964     if has_dups(symbols):

ValueError: 
Expecting a Symbol but got Derivative(phi1(t), (t, 2))
```

The docs for linear_eq_to_matrix are pretty clear that any simplification needed to put the equations into straight-forward linear form needs to happen before calling the function.

**Comment by RmStorm** [comment]
I think this can be closed if an error is thrown instead of a wrong answer being returned.
