### ISSUE TITLE
Problem while importing solveset  on sympy liveshell

### ISSUE THREAD

**Issue by SalilVishnuKapur** [sympy/sympy#10601]
>>> from sympy import solveset, S
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: cannot import name solveset

Even while trying to import solveset on ipython I am still facing the same error.

**Comment by leosartaj** [comment]
You need to do something like this

```
>>> from sympy.solvers.solveset import solveset
```

With the next release probably you will be able to do this ``from sympy import solveset``.

**Comment by smichr** [comment]
closing as there is nothing wrong -- that's just how the namespace is (as was noted)
