### ISSUE TITLE
documentation typo

### ISSUE THREAD

**Issue by goretkin** [sympy/sympy#10614]
Sorry that I don't know the proper way to update the docs.

https://github.com/sympy/sympy_doc/blob/e166657d641ea7138a9fb1ac057209213f129b0d/latest/modules/simplify/simplify.html#L600

```
If we know nothing about sign of some exponent and `exact`;
flag is unset, then structure this exponen's structure will
be analyzed and pretty fraction will be returned:
```

**Comment by bjodah** [comment]
Thanks, it looks as if it is already fixed in `master`:

```
$ grep --include "*.py" "If we know nothing" -R sympy/
sympy/simplify/radsimp.py:       If we know nothing about sign of some exponent and 'exact'
```
https://github.com/sympy/sympy/blob/master/sympy/simplify/radsimp.py#L936

Or maybe I'm missing something?

**Comment by goretkin** [comment]
Great! Thank you. I would judge that the following sounds a bit better, but not enough to open an issue 

"If we know nothing about *the* sign of some exponent, and *the* `exact` flag is set, then ... *a* pretty fraction will be returned."

**Comment by bjodah** [comment]
@goretkin I agree, feel free to open a pull request (you can edit using the "pen" button in my link)
