### ISSUE TITLE
sympify(set) should give FiniteSet

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#10654]
```
In [14]: sympify({n})
Out[14]: set([n])
```

It should give FiniteSet(n), so that people can use that convenient syntax in set functions (like Union and so on). 

This is easy to fix. Just add it to the converter dictionary in sympify.py

**Comment by asmeurer** [comment]
(and ditto for frozenset)

**Comment by AnishShah** [comment]
I will work on this

**Comment by ashutoshsaboo** [comment]
@asmeurer I guess this issue can be closed since #10657 is merged? :smile:

**Comment by AnishShah** [comment]
@ashutoshsaboo it is already closed.
