### ISSUE TITLE
evalf(subs={}) in Piecewise

### ISSUE THREAD

**Issue by mzaffalon** [sympy/sympy#10662]
In the following snippet of code

```
w = symbols("w")
phidir = Piecewise((0, s <= w), 
                   (1, s > w))
phidir.evalf(subs={w:0})
```

I would expect to define the Heaviside step function, but the limit `w` is not evaluated. On the other hand, `phidir.subs(w,1).evalf()` does work.

**Comment by sampadsaha5** [comment]
I feel like if you use `subs={w:0}` then you are creating a dictionary which says `subs[w]=0`.
To use the substitution functionality one have to use `subs(a,b)` which would replace all `a` by `b`. 
That is why when you use  `subs(w,1)` , the limit works and the former one fails.

**Comment by mzaffalon** [comment]
Unless I misread
http://docs.sympy.org/dev/tutorial/basic_operations.html#evalf, it seems
that what I do should be working.

**Comment by sampadsaha5** [comment]
Yah , you are right. Actually I missed that thing.

**Comment by asmeurer** [comment]
I think this is the same issue as https://github.com/sympy/sympy/issues/6974. Currently evalf(subs) doesn't work if you don't substitute every symbol in the expression.
