### ISSUE TITLE
integrate does not give the right answer

### ISSUE THREAD

**Issue by EnriquePH** [sympy/sympy#10665]
Version: 0.7.6.1 is giving me this problem:

http://stackoverflow.com/questions/35564899/sympy-integrate-does-not-give-the-right-answer

Best Regards, Enrique.

**Comment by jksuom** [comment]
This is fixed in SymPy 0.7.7-dev:
```
In [11]: integrate(sigma, (x, -oo, 0))
Out[11]: log(2)
```

**Comment by Upabjojr** [comment]
Please try the issue on the development branch before reporting a bug.
