### ISSUE TITLE
autowrap should accept any type of iterable for the args keyword

### ISSUE THREAD

**Issue by moorepants** [sympy/sympy#10669]
```
moorepants@garuda:sympy(matrix-operator)$ ipython
Python 3.5.1 |Continuum Analytics, Inc.| (default, Dec  7 2015, 11:16:01) 
Type "copyright", "credits" or "license" for more information.

IPython 4.1.1 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: from sympy import *

In [2]: from sympy.utilities.autowrap import autowrap

In [3]: from sympy.abc import a, b, c

In [4]: m = Matrix([a, b + c])

In [5]: m
Out[5]: 
Matrix([
[    a],
[b + c]])

In [6]: f = autowrap(m, args=(a, b, c))
---------------------------------------------------------------------------
CodeGenArgumentListError                  Traceback (most recent call last)
/home/moorepants/src/sympy/sympy/utilities/autowrap.py in autowrap(expr, language, backend, tempdir, args, flags, verbose, helpers)
    517     try:
--> 518         routine = make_routine('autofunc', expr, args)
    519     except CodeGenArgumentListError as e:

/home/moorepants/src/sympy/sympy/utilities/codegen.py in make_routine(name, expr, argument_sequence, global_vars, language)
   1607 
-> 1608     return code_gen.routine(name, expr, argument_sequence, global_vars)

/home/moorepants/src/sympy/sympy/utilities/codegen.py in routine(self, name, expr, argument_sequence, global_vars)
    604                 msg = msg.format(", ".join([str(m.name) for m in missing]))
--> 605                 raise CodeGenArgumentListError(msg, missing)
    606 

CodeGenArgumentListError: ("Argument list didn't specify: out_2163190553469947090 ", [OutputArgument(out_2163190553469947090, Matrix([
[    a],
[b + c]]), out_2163190553469947090)])

During handling of the above exception, another exception occurred:

TypeError                                 Traceback (most recent call last)
<ipython-input-6-fcea31f79d7e> in <module>()
----> 1 f = autowrap(m, args=(a, b, c))

/home/moorepants/src/sympy/sympy/utilities/autowrap.py in autowrap(expr, language, backend, tempdir, args, flags, verbose, helpers)
    526                 raise
    527             new_args.append(missing.name)
--> 528         routine = make_routine('autofunc', expr, args + new_args)
    529 
    530     return code_wrapper.wrap_code(routine, helpers=helps)

TypeError: can only concatenate tuple (not "list") to tuple
```

**Comment by inception007** [comment]
I will work on this.

**Comment by inception007** [comment]
I am getting different error.
`CodeWrapError                             Traceback (most recent call last)
<ipython-input-5-fcea31f79d7e> in <module>()
----> 1 f = autowrap(m, args=(a, b, c))

/home/parv/sympy/sympy/sympy/core/cache.pyc in wrapper(*args, **kwargs)
     91             def wrapper(*args, **kwargs):
     92                 try:
---> 93                     retval = cfunc(*args, **kwargs)
     94                 except TypeError:
     95                     retval = func(*args, **kwargs)

/home/parv/sympy/sympy/sympy/core/compatibility.pyc in wrapper(*args, **kwds)
    882                 except TypeError:
    883                     stats[MISSES] += 1
--> 884                     return user_function(*args, **kwds)
    885                 with lock:
    886                     link = cache_get(key)

/home/parv/sympy/sympy/sympy/utilities/autowrap.pyc in autowrap(expr, language, backend, tempdir, args, flags, verbose, helpers)
    529         routine = make_routine('autofunc', expr, args + new_args)
    530 
--> 531     return code_wrapper.wrap_code(routine, helpers=helps)
    532 
    533 

/home/parv/sympy/sympy/sympy/utilities/autowrap.pyc in wrap_code(self, routine, helpers)
    142             self._generate_code(routine, helpers)
    143             self._prepare_files(routine)
--> 144             self._process_files(routine)
    145             mod = __import__(self.module_name)
    146         finally:

/home/parv/sympy/sympy/sympy/utilities/autowrap.pyc in _process_files(self, routine)
    165             raise CodeWrapError(
    166                 "Error while executing command: %s. Command output is:\n%s" % (
--> 167                     " ".join(command), e.output.decode()))
    168         if not self.quiet:
    169             print(retoutput)

CodeWrapError: Error while executing command: /usr/bin/python -c import numpy.f2py as f2py2e;f2py2e.main() -c -m wrapper_module_0 wrapped_code_0.f90. Command output is:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named numpy.f2py
`

**Comment by moorepants** [comment]
Seems like you may not have numpy installed.

**Comment by vovapolu** [comment]
@moorepants I don't get this error. 
```
Python 3.5.1 |Anaconda 2.5.0 (64-bit)| (default, Dec  7 2015, 11:16:01)
Type "copyright", "credits" or "license" for more information.

IPython 4.0.3 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: from sympy import *

In [2]: from sympy.utilities.autowrap import autowrap

In [3]: from sympy.abc import a, b, c

In [4]: m = Matrix([a, b + c])

In [5]: f = autowrap(m, args=(a, b, c))

In [6]: f(2, 3, 4)
Out[6]: 
array([[ 2.],
       [ 7.]])
```

**Comment by moorepants** [comment]
It is also working for me on master and I'm unable to reproduce the the error:

```
Python 2.7.11 |Continuum Analytics, Inc.| (default, Dec  6 2015, 18:08:32) 
Type "copyright", "credits" or "license" for more information.

IPython 4.0.1 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: from sympy import *

In [2]: from sympy.utilities.autowrap import autowrap

In [3]: from sympy.abc import a, b, c

In [4]: m = Matrix([a, b + c])

In [5]: f = autowrap(m, args=(a, b, c))

In [6]: f(1, 2, 3)
Out[6]: 
array([[ 1.],
       [ 5.]])

In [7]: import sympy

In [8]: sympy.__version__
Out[8]: '1.0.1.dev'
```

I must have been using 0.7.6.1, as it fails there. I'm not able to easily find the PR that fixed it.
