### ISSUE TITLE
Sets printing issues

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#10672]
Some issues with str and srepr printing in sets. 

Some notes:
- The `str` printer should always generate valid Python, which recreates the expression (but may require some variables to be defined).
- The `srepr` printer should generate an expression that recreates the expression exactly, using only the names from `from sympy import *` (or other relevant imports for other submodules, but that isn't relevant for the sets). 
- Fancy printing should be relegated to the pretty printers (`pprint` and `latex`). 

Here are the issues I found:
1. `str(Interval)`
   
   ```
   In [9]: str(Interval(0, 1, False))
   Out[9]: '[0, 1]'
   
   In [10]: str(Interval(0, 1, True))
   Out[10]: '(0, 1]'
   ```
   
   The former creates a list, not an interval. The latter isn't even valid Python.
2. `srepr(S.Integers)` (and probably others)
   
   ```
   In [11]: srepr(S.Integers)
   Out[11]: 'Integers()'
   ```
   
   `Integers` isn't a name that is imported from `sympy`. It should print as `S.Integers`. The `str` printers should probably do the same. 
3. `str(Union)`
   
   ```
   In [18]: str(Union(S.Integers, FiniteSet(pi))) 
   Out[18]: 'Integers() U {pi}'
   ```
   
   It's not valid Python. It should print as `Union(S.Integers, FiniteSet(pi))`. Printing as `Union(S.Integers, {pi})` is fine when https://github.com/sympy/sympy/issues/10654 gets merged. 

There are likely others. I didn't check too much. An audit of the printing in the sets module would be worthwhile.

**Comment by inception007** [comment]
I would like to work on this.

**Comment by SalilVishnuKapur** [comment]
I am already working on this

**Comment by SalilVishnuKapur** [comment]
@asmeurer  Regarding the issue 1 . I find it outputs something else to on the sympy live shell . Kindly have a look . 
>>> str(Interval(0, 1, False))
[0,1]

**Comment by AnishShah** [comment]
The output is the same on sympy live

**Comment by SalilVishnuKapur** [comment]
@AnishShah  but here have a look at this screenshot of what i tried on sympy live.
![image](https://cloud.githubusercontent.com/assets/10466576/13282607/cb860554-db0f-11e5-8011-2ed2702fee66.png)

**Comment by AnishShah** [comment]
I'm sorry if I'm missing something, but the output in your screenshot is same as the output mentioned by @asmeurer. I don't see any difference.

**Comment by SalilVishnuKapur** [comment]
'[0, 1]' and [0, 1] . I think it is already a string after getting evaluated by str.

**Comment by asmeurer** [comment]
@SalilVishnuKapur that's because the SymPy Live shell renders the output as LaTeX. 

You should work locally against the git master. SymPy Live has some differences against the normal SymPy which might confuse, but more importantly, it runs SymPy 0.7.6, whereas you want to work against the git master.

**Comment by yash14123** [comment]
I would like to take this up. :)

**Comment by srajangarg** [comment]
@asmeurer I was reviewing the whole str.py file. Always `str` printing `FiniteSet` in the `{ , , , }` fashion maybe problematic sometimes. Like
```python
>>> S = {1, 2, 3} 
>>> I = Interval(0, 1)
>>> l = I * S
>>> str(l)
Interval(0, 1, False, False) * {1, 2, 3}  # the default printing is using 'x' right now, which is wrong
>>> newS = {1, 2, 3}
{1, 2, 3}
>>> newl = Interval(0, 5, False, False) * {1, 2, 3}
throws TypeError
```

**Comment by wrat** [comment]
I also want to work on this but i am new here so  how should start?

**Comment by asmeurer** [comment]
It looks like this has already been started at https://github.com/sympy/sympy/pull/10708, so you should at least wait until that is merged and see if anything is left to do then.

**Comment by asmeurer** [comment]
Also see https://github.com/sympy/sympy/wiki/Development-workflow for general instructions on how to contribute.

**Comment by wrat** [comment]
Ohkk thanks Aaron Meurer!!!  I will wait for that or I will work on other Issue. Thanks for suggestion.

**Comment by asmeurer** [comment]
Related https://github.com/sympy/sympy/issues/10035

**Comment by SagarB-97** [comment]
@asmeurer 
Please review PR #12112

**Comment by Upabjojr** [comment]
https://github.com/sympy/sympy/issues/12213

**Comment by asmeurer** [comment]
@Upabjojr wrong number? I don't see how that's related.

**Comment by Upabjojr** [comment]
> wrong number? I don't see how that's related.

Sorry, I wanted to link the issue of the `And` and `Or` str() printer.

**Comment by SagarB-97** [comment]
Please review #12112

**Comment by SagarB-97** [comment]
@Upabjojr I don't think this issue should be closed. #12112 takes care of only `str` printer. `srepr` printer is still the same.

**Comment by Upabjojr** [comment]
@SagarB-97 github apparently closed the issue automatically, I didn't actually notice that.

**Comment by AnimeshSinha1309** [comment]
Is this the expected behaviour of `str()` and `srepr()`:

```python
>>> from sympy import S
>>> from sympy import srepr
>>> print(S.Integers)
S.Integers
>>> S.Naturals0
S.Naturals0
>>> srepr(S.Naturals)
'S.Naturals'
>>> str(S.Reals)
'S.Reals'
```

I implemented this but then did not pass the tests as the examples and tests are written for the previous output. Please tell me if this is what was desired so I can fix the tests and examples for the new output.

**Comment by asmeurer** [comment]
It looks like points 1 and 3 are now fixed. It is no longer necessary to print the fancy sets with `S.` because they are included in `from sympy import *` now. 

However, this is still wrong:

```py
>>> srepr(Integers)
Integers()
```

because `Integers()` raises a TypeError. It should just return `"Integers"`, the same as `str`.

**Comment by AnimeshSinha1309** [comment]
Thanks, will fix srepr.
