### ISSUE TITLE
solveset(sin(y), y, Interval(0, pi)) is wrong

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#10671]
```
In [5]: solveset(sin(y), y, Interval(0, pi))
Out[5]: {2⋅n⋅π | n ∊ ℤ} ∪ {2⋅n⋅π + π | n ∊ ℤ}
```

It isn't intersecting the domain `Interval(0, pi)`. 

@smichr

**Comment by nishnik** [comment]
I did a little research on it:
`solveset` calls `_solveset` which calls `_solve_real_trig(f, symbol)` for `f`=`sin(y)` and `symbol`=`y`.
Where it is solved by transforming the problem to complex plane and whose solution is then transformed back to real plane and returned. But then in `_solveset`, I couldn't find something for Domain Intersection.
If you guide me a little, I will be able to solve it.

**Comment by asmeurer** [comment]
I think it used to work, so I would investigate what broke it (you can use `git bisect`).

**Comment by nishnik** [comment]
I found that it broke in #10448 . Before it in `solveset` we were doing:
```
if isinstance(f, (Expr, Number)):
    if domain is S.Reals:
        return solveset_real(f, symbol)
    elif domain is S.Complexes:
        return solveset_complex(f, symbol)
    elif domain.is_subset(S.Reals):
        return Intersection(solveset_real(f, symbol), domain)
    else:
        return Intersection(solveset_complex(f, symbol), domain)
```
But after that PR we are simply calling `_solveset`, and in it we are not doing the above mentioned intersection
But now, as `solveset_real` and `solveset_complex` have changed and they call `solveset` with their respective domain. So I tried to fix it like [this](https://github.com/nishnik/sympy/commit/cd633e19a75dada0a323245e22f0e5a087496b49) using one extra variable.
Furthemore, I noticed some bug in `test_solveset`, like:
```
assert solveset(sin(y + a) - sin(y), a, domain=S.Reals) == \
        Union(imageset(Lambda(n, 2*n*pi), S.Integers),
        imageset(Lambda(n,
        -I*(I*(2*n*pi +arg(-exp(-2*I*y))) + 2*im(y))), S.Integers))
```
But I think this `imageset(Lambda(n, -I*(I*(2*n*pi +arg(-exp(-2*I*y))) + 2*im(y))), S.Integers))` is in complex plane right ?
If you find my fix right, Should I send a PR ?

**Comment by nishnik** [comment]
I don't think using an extra variable will be a good practice here. Using domain intersection *every-time* will work too, but that mean extra computation, even when it is not needed. Can you suggest an alternative @asmeurer ? Or using extra variable is fine.
Well in long term we can make all those solvers like `solve_real_trig`, to do domain intersection on their own, implementing a better encapsulation.

**Comment by Shekharrajak** [comment]
https://github.com/sympy/sympy/pull/10482 and https://github.com/sympy/sympy/pull/10552
Return
```
>>> solveset(sin(y), y, Interval(0, pi))
[0, π] ∩ {n⋅π | n ∊ ℤ}
```
I think I should rewrite these PR in a better way.

**Comment by nishnik** [comment]
@Shekharrajak  Already  worked out the situation

**Comment by kshitij10496** [comment]
@nishnik I appreciate your idea here.
But I think the core issue is with the Intersection and Union of ImageSet objects.
The code for these cases needs to be improved.
I am working on it.

**Comment by nishnik** [comment]
Fixed through #10709

**Comment by smichr** [comment]
@kshitij10496 , have you made any progress on [this]()? I noticed today, too:

```
>>> eq
-1/x**2 <= 0
>>> sol = solveset(_, x, Interval(1, oo))
>>> sol
(-oo, oo)
```

I am expecting `[1, oo)`.  (Noticed in #12458.)

**Comment by smichr** [comment]
I've got a fix for this and a test showing that this issue has been fixed.

**Comment by kshitij10496** [comment]
@smichr No, I haven't worked in that direction since I assumed that #10709 fixed this.
However, I will review #12471 as it looks to solve the issue I was addressing.
