### ISSUE TITLE
Add a header to old docs stating that they are out of date

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#10696]
We have a lot of older docs on the docs website, like http://docs.sympy.org/0.7.1/modules/simplify/simplify.html. Unfortunately, Google likes to return these in search results instead of the newest version (http://docs.sympy.org/latest/modules/simplify/simplify.html). 

We should add a header to all the old docs that warns users that they are outdated, and links to the same page with "latest" in the URL. 

The change here would go to https://github.com/sympy/sympy_doc, but I'm opening this here so that people will see it.

**Comment by asmeurer** [comment]
Apparently we can also influence Google with a sitemap.xml. If you know how to do this, that would be awesome too.

**Comment by asmeurer** [comment]
Another idea https://en.wikipedia.org/wiki/Noindex

**Comment by mvnnn** [comment]
I would like to work on this.

**Comment by mvnnn** [comment]
@asmeurer i added latest link on all ```index.html``` file.please check that if that's looks good then i will add latest link in all other html files.[PR#18](https://github.com/sympy/sympy_doc/pull/18)

**Comment by mvnnn** [comment]
![screenshot from 2016-02-27 15 06 43](https://cloud.githubusercontent.com/assets/12225578/13372301/3cea4588-dd64-11e5-97a6-e1c4f7bf35ff.png)

**Comment by mvnnn** [comment]
@asmeurer that's looks good.

**Comment by asmeurer** [comment]
Red text on green background is hard to read. I was thinking of a larger (maybe about 80 pixels or so) dismissable dialog at the top (similar to those cookie warnings that some websites have). 

We should also definitely look into some of those metadata options to get Google to not rank those pages in the first place.

**Comment by mvnnn** [comment]
@asmeurer that's looks good.
![screenshot from 2016-03-01 23 41 58](https://cloud.githubusercontent.com/assets/12225578/13437296/849c0ce8-e009-11e5-94e0-b4116eadda1c.png)

**Comment by debugger22** [comment]
@mvnnn How about this? https://docs.djangoproject.com/en/1.7/ref/models/querysets/

**Comment by debugger22** [comment]
Also the sentence is not correct.

**Comment by mvnnn** [comment]
@debugger22 please tell me which sentence we need to write.

**Comment by mvnnn** [comment]
```
We should also definitely look into some of those metadata options to get Google to not rank those pages in the first place.
```
i am working on this. we need to improve also lot of things see :[PageSpeed Insights](https://developers.google.com/speed/pagespeed/insights/?url=sympy.org&tab=desktop)

**Comment by debugger22** [comment]
You forgot a `to` after `go`.

IMO, it would be better to write this:

```
This page is outdated, click here for the latest docs
```

**Comment by mvnnn** [comment]
@debugger22 that's looks good. 
![screenshot from 2016-03-02 00 42 48](https://cloud.githubusercontent.com/assets/12225578/13438637/db728bae-e00f-11e5-9938-3e1ace4ef5fc.png)

**Comment by mvnnn** [comment]
@debugger22 that's looks good. 
![screenshot from 2016-03-03 16 15 44](https://cloud.githubusercontent.com/assets/12225578/13491942/567b9ba0-e15b-11e5-9390-6c55e2efe89f.png)

**Comment by shashankgandham** [comment]
Why not use redirect ? I mean redirect all the outdated pages to the new documentation ! Is there any problem with that ?

**Comment by mvnnn** [comment]
@shashankgandham yes, if any user want to work on older version in that case what we do? so that's not good idea.

**Comment by mvnnn** [comment]
@asmeurer that's looks good. i know Google webmaster tools very well so i would like to work on this.

**Comment by mvnnn** [comment]
@asmeurer that's looks good. i know Google webmaster tools very well so i would like to work on this.
![screenshot from 2016-03-03 16 15 44](https://cloud.githubusercontent.com/assets/12225578/13491942/567b9ba0-e15b-11e5-9390-6c55e2efe89f.png)

**Comment by mvnnn** [comment]
@asmeurer i know Google webmaster tools very well so i would like to work on this.my email address ```mavanibhautik@gmail.com```.

**Comment by asmeurer** [comment]
@mvnnn I'm about to do a SymPy release (hopefully either later today or this weekend). Part of the release process involves updating the docs, so in order to make sure that goes smoothly I want to hold off on pushing updates to the docs website until after that is done. The SymPy release script updates the docs automatically by running some scripts. Just letting you know that you can continue to work on this, but I don't want to merge any of your changes until after then.

**Comment by mvnnn** [comment]
@asmeurer sorry for disturb you.i would like to work on web related issue.i threw out all ```Label```-->
```Documentation``` issue.please suggest me more web related issue.if you have time for that else i would to like improve website code. what should i do ?

**Comment by asmeurer** [comment]
It's not a disturbance, just letting you know. The website stuff is at https://github.com/sympy/sympy.github.com and https://github.com/sympy/sympy-web-static.

**Comment by certik** [comment]
I am fine with giving @mvnnn the needed access to fix this, let me know what needs to be done. @mvnnn, thanks for working on this!

**Comment by mvnnn** [comment]
@certik i agree with @asmeurer.

**Comment by mvnnn** [comment]
```
but I don't want to merge any of your changes until after then.
```
@asmeurer  i added latest link on all index.html file PR#18. if that's looks good then i would like to move to another issue.

**Comment by ishanaj** [comment]
@asmeurer @debugger22 @certik if the issue still persists ...i would like to work on it.

**Comment by kmeagle1515** [comment]
Hello @asmeurer should i work on it?

**Comment by asmeurer** [comment]
We don't have old versions of the docs any more.
