### ISSUE TITLE
Eq works incorrectly

### ISSUE THREAD

**Issue by rpisarev** [sympy/sympy#10699]
In [36]: Eq(x - 1, x - 1)
Out[36]: True

OK, because expresion x - 1 exists for all x.

`In [37]: Eq(1/x, 1/x)
Out[37]: True

In [50]: Piecewise((-1/x , Eq(1/x, 1/x)), (-7, Eq(x, 0)))
Out[50]: -1/x

In [51]: Piecewise((-1/x , Eq(1/x, 1/x)), (-7, Eq(x, 0))).subs(x, 0)
Out[51]: zoo
`

Oops.  Equality Eq(1/x, 1/x) does not hold for all x, but it holds for all x != 0

**Comment by danielbarter** [comment]
I don't think anything is broken here. 

Remember, 1/x is just a symbolic object, not a function, so Eq(1/x,1/x) is just true. In Piecewise, the conditions are evaluated left to right.

If you evaluate Piecewise((-7,Eq(x,0)),(-1/x,Eq(1/x,1/x))).subs(x,0), then you get -7.

**Comment by bjodah** [comment]
I agree completely with @danielbarter here. There is no bug here. @rpisarev do you follow the reasoning here? if not: feel free to ask here and we'll try to elaborate.

**Comment by rpisarev** [comment]
It's bug

**Comment by bjodah** [comment]
@rpisarev exactly what do you think qualifies as a bug?

One way to achieve what (I tink) you are trying to achieve is:
```
>>> Piecewise((-1/x , And(Ne(x, 0), Eq(1/x, 1/x))), (-7, Eq(x, 0))).subs(x, 0)
-7
```

Another way is reordering you arguments to Piecewise:
```
>>> Piecewise((-7, Eq(x, 0)), (-1/x , Eq(1/x, 1/x))).subs(x, 0)
-7
```

Or do you feel `Eq(1/x, 1/x)` should evaluate as `False`?
```
>>> Eq(1/x, 1/x)
True
>>> Eq(1/x, 1/x, evaluate=False)
1   1
─ = ─
x   x
```
Perhaps this is a bit of gray zone though:
```
>>> Eq(1/x, 1/x, evaluate=False).subs(x, 0)
True
```
but then again, wouldn't equality be defined even for infinity?

**Comment by rpisarev** [comment]
The expression 1/x is symbol, yes. Also Eq(1/x, 1/x) is symbol too. But when it's used in piecewise, expression Eq(1/x, 1/x) is not abstract symbol anymore. It has domain already. E.g. the symbol Eq(1/x, 1/x) works for all x. But when it is defined as part of function, it does not work for all x: only for x from domain of function - x != 0. So, we have conditions Eq(1/x, 1/x) and Eq(x, 0). They cover whole space (reals or complex), but in this function system mistakenly believes, that Eq(1/x, 1/x) works for all x in space and throws branch Eq(x, 0). Yes, of course, I can use another order or form. I know it. But I want to see that correctly and thorough way from system, which knows about domain.

**Comment by bjodah** [comment]
I see your point. However, this would require some substantial changes to Piecewise (making it considerably more complex), and in my opinion, the current behaviour is not surprising. But I've reopened the issue to see what other people think.

**Comment by smichr** [comment]
All here is as intended. `Eq(foo, foo)` is shorthand for `True` unless `foo==S.NaN`. The Piecewise should be written as `Piecewise((-7, Eq(x, 0)), (-1/x , True))`.
