### ISSUE TITLE
Is the empty matrix nilpotent? IndexError: Index out of range: a[0]

### ISSUE THREAD

**Issue by argriffing** [sympy/sympy#10701]

**Comment by aravindkanna** [comment]
I would like to work on this issue. Can you please guide me on this issue because I am new to this. 
It will suffice if you add some clear description of the issue and where to start.

**Comment by argriffing** [comment]
> Can you please guide me on this issue because I am new to this. 
It will suffice if you add some clear description of the issue and where to start.

1. Begin running the Python read-eval-print-loop (REPL). This may be available by typing `python` on your command line, followed by an 'enter' or 'return' keystroke.
2. Within the Python REPL, type `from sympy import Matrix`. This command may require that the Python package called "sympy" is installed on your system. If you don't have sympy installed, you can find instructions for installing it [here](http://www.sympy.org/).
3. Use sympy to check whether an empty matrix is nilpotent. This can be achieved by typing the command `Matrix([[]]).is_nilpotent()` in the REPL followed by an <enter> keystroke. Be careful to include all of the square brackets and parentheses in that command, it matters whether they are square or rounded and it matters which way they are facing!
4. Observe the output of that command. On my system it gives a traceback (one of Python's ways of indicating some kind of error) which includes the output "`IndexError: Index out of range: a[0]`". I hope this clarifies the issue and gives you a place to start!

**Comment by argriffing** [comment]
@aravindkanna Sorry my last response was too snarky. I see that you are a new github user and that you are probably trying to build up your github portfolio. If you want increase your github metrics and start earning those green squares on your user page with contributions to high-impact projects such as this one, you might start by looking at issues that are labeled as 'easy to fix' https://github.com/sympy/sympy/issues?q=is%3Aopen+is%3Aissue+label%3A%22Easy+to+Fix%22

**Comment by aravindkanna** [comment]
Thank you for the quick reply.

So what I'm thinking to do is, 
Raise an exception saying 

> **Nilpotency of an empty matrix is not defined**

Can I continue?

**Comment by argriffing** [comment]
To be clear, this is primarily a math question not a software engineering issue. There are math conventions like 'an empty sum is 0 and an empty product is 1' and 'the determinant of an empty matrix is 1`.
```python
>>> Matrix([[]]).det()
1
```
Maybe nilpotency can be determined by following those conventions. For example, non-empty matrices with nonzero determinant cannot be nilpotent. If this property extends to empty matrices, and if the determinant of the entry matrix is 1, then would imply that `is_nilpotent()` of the empty matrix should return `False`. But I'm not 100% sure that this is the mathematically correct convention. After the convention is decided, this will certainly become an `Easy to Fix` issue from a software engineering perspective!

**Comment by aravindkanna** [comment]
Sir, 
I have done some work regarding this. What I have found is:

1) As you said, the empty matrix is also a zero matrix which is defined by norms. So following that if A is our empty matrix, A raised to power 1 is a zero matrix. So A is a nil potent with degree 1.

2) Now what I have found is, a small experiment in sympy itself.

**In [74]: a = symbols('a')
In [75]: b = Matrix([[]])
In [76]: c = eye(0)
In [77]: d = a*c - b
In [78]: d.det()
Out[78]: 1
**

so that means the characteristic polynomial is a constant polynomial and is 1.
Now there won't be any roots for constant polynomials other than zero. So the characteristic polynomial of an empty matrix has no roots and so there are no eigen values(or at least real eigen values)  for an empty matrix. But we know that a Nilpotent matrix has a single eigen value as ZERO. 

but if we see it the other way, if A is our empty matrix, **Av = av** for any  vector v and scalar a. Here as A is an Identity matrix of size 0x0, **Av** is nothing but **v** which results is value of **a** being 1. So the eigen value of empty matrix is 1. But nilpotent matrix has a single eigen value as ZERO.

Now, as you said and sympy is returning, if an empty matrix is a zero matrix, then how can the determinant of it is 1?. We have taken it as a convention(as far as I know). So based on that I think we can't say it to be nilpotent.

So following all these, I suppose that the empty matrix is not a nil potent and also the eigen value of an empty matrix is 1(which is also giving the same index out of range error).

So if this seems convincing in a way, then I'll continue fixing this. If anything seems wrong, please try to rectify me.

**Comment by aravindkanna** [comment]
Sir, can you please guide me how to proceed with my existing knowledge and understanding of the problem.

**Comment by argriffing** [comment]
@aravindkanna Thanks for looking at this issue, especially for showing that `eigenvals()` of an empty matrix gives the same error as I was seeing for `is_nilpotent`. I've opened https://github.com/sympy/sympy/issues/10719 for the `eigenvals` issue.

**Comment by aravindkanna** [comment]
Sir, this error is not only for eigenvals(), but also for eigenvects(). So the same issue can point to this too. And what should I do now?

**Comment by argriffing** [comment]
> what should I do now?

I see that the `eigenvals()` of non-empty matrices returns a multi-set in the form of a Python dict, so I was going to suggest improving the implementation of `eigenvals()` of an empty matrix so that it returns an empty dict instead of erroring. But I see that numpy, for example, deliberately raises an error when asked for eigenvalues of an empty matrix, so maybe this decision is not as obvious as I'd thought...

**Comment by aravindkanna** [comment]
> **so I was going to suggest improving the implementation of eigenvals() of an empty matrix so that it returns an empty dict instead of erroring**

So are you encouraging me to implement the `eigenvals(self, **flags)` function to return an empty dict if the input is an empty matrix?

**Comment by argriffing** [comment]
I was going to suggest that, until I saw what numpy does. Now I'm not so sure. Maybe the actual sympy devs could decide.

**Comment by aravindkanna** [comment]
Sir, after your conversation about Numpy I have done some study on that. What I found is:

1) Sympy is allowing or trying to allow to find eigen values for all dimenional matrices.

`
In [10]: a = Matrix([1])

In [11]: a
Out[11]: [1]

In [12]: Matrix.eigenvals(a)
Out[12]: {1: 1}

`

2) Numpy is not allowing to find the eigen values for all dimensional Matrices. They have restricted its usage such that the matrix should be at least 2 dimensional. So Numpy is raising an error to say that the matrix is not 2 dimensional. 

3) I don't know whether I can say this or not but just as a discussion I would like to point it out. I use matlab for some course work. So I have a little experience in it. What I have seen there is that, it is not returning any error. 

`>> a = [];
>> e = eigs(a);
>> e

e =

   Empty matrix: 0-by-1

`

it just says that the result is an empty matrix of order 0-by-1. What I observed from this is I have taken the transpose of the matrix **e**. Then I have taken the product of both in the order so as to get a 1-by-1 matrix. What I got as a result is zero. I think probably they are returning the eigen value of an empty matrix to be zero. So we can do consider this thing also. 

> I was going to suggest that, until I saw what numpy does.

Numpy is not doing anything with empty matrices. So I think we have to continue with our procedures. Sorry if I have done any wrong comparisions.

**Comment by aravindkanna** [comment]
Sir, is there any update?

**Comment by aravindkanna** [comment]
Sir, I would like to implement an `is_empty` property. Actually I have implemented it in my local machine and it worked as below. 

`>>> from sympy import Matrix, zeros`
`>>> a = Matrix([])`
`>>> b = Matrix([1])`
`>>> c = Matrix([0])`
`>>> d = zeros(3, 4)`
`>>> a.is_empty`
`True`
`>>> b.is_empty`
`False`
`>>> c.is_empty`
`False`
`>>> d.is_empty`
`False`

I have created a new branch with name `test` and started working in that. I have also staged my results. Please have a look at it. I have created it just for the use in other functions like `is_nilpotent()`, as if the input matrix is empty then we can do something other than usual. Please provide your inputs.

**Comment by argriffing** [comment]
Yes I think `is_empty` (True iff at least one of the dimensions is zero) is a great idea and I'm surprised it's not already available. But I'm not actually a sympy dev, so someone else will have to decide whether it will be added.

**Comment by moorepants** [comment]
@aravindkanna Please submit a pull request with your `is_empty` method. It can then be decided there if it is useful and should be included.

**Comment by aravindkanna** [comment]
I am thinking to provide it with a NameError till anyone with exact idea comes or I get some other clarificaton.

Thank you,
Aravind

**Comment by aravindkanna** [comment]
@moorepants , I am getting an error while trying to push the changes.

`fatal: remote error: 
  You can't push to git://github.com/sympy/sympy.git
  Use https://github.com/sympy/sympy.git
`
can you please help me?

**Comment by moorepants** [comment]
You need to fork sympy in the github interface, clone that, and only push to your fork.

Please read: https://github.com/sympy/sympy/wiki/Development-workflow

**Comment by leosartaj** [comment]
@aravindkanna You can't push directly to the sympy's repo. Also, it is not recommended to directly push to the repo, even you have the rights. You should try pushing to your sympy fork.

Something like this, ``git push https://github.com/aravindkanna/sympy.git [Branch-name]`` should work.

I would recommend going through https://github.com/sympy/sympy/wiki/Development-workflow first.

**Comment by aravindkanna** [comment]
Thank you @moorepants and @argriffing 
I have submitted my pull request
