### ISSUE TITLE
Any dict-like object in expr.subs

### ISSUE THREAD

**Issue by parnmatt** [sympy/sympy#10710]
https://github.com/sympy/sympy/blob/master/sympy/core/basic.py#L836
Explicitly checks for instances of `Dict` or `dict`.
Realistically this should be anything `dict`-like, for example a `collections.ChainMap` object.

As `Dict` is your own wrapper, it is up to you how to handle it's inheritance, however I suggest rather than, or in addition to `dict`, you have `collections.abc.Mapping`. All standard library `dict`-like objects are instances of `collections.abc.Mapping`, thus this should cover all cases within the stdlib.

Currently I have to wrap my `ChainMap`s with a `dict()` call, which wastes computational time and memory; when duct-typing should be satisfied with `OrderedDict` or `ChainMap` as a drop-in replacements for `dict`.

**Comment by debugger22** [comment]
+1
This would be a good addition.

**Comment by asmeurer** [comment]
Should be easy to fix. Just change the isinstance check.

**Comment by parnmatt** [comment]
Indeed, I wished to get a consensus before creating a pull request, which should be linked above as #10753 

(stupidly I create a pull request on myself, please ignore)

**Comment by parnmatt** [comment]
Although there is a `unordered = True` under the `isinstance`, even for `OrderedDicts`, I believe the intended functionality ought to be the same, following the code further down.
