### ISSUE TITLE
Incorrect rref

### ISSUE THREAD

**Issue by proy87** [sympy/sympy#10718]
`Matrix([[3+3*sqrt(3)*I, -9],[4,-3+3*sqrt(3)*I]]).rref()` returns identity matrix, but in fact rref is not identity matrix.

**Comment by MooVI** [comment]
@proy87 You need to set the simplify flag to `True`; i.e. ``Matrix([[3+3*sqrt(3)*I, -9],[4,-3+3*sqrt(3)*I]]).rref(simplify=True)`` gives the correct answer (at least it agrees with Mathematica's). I have tried to get this default changed to something more sane, but sadly to no avail so far, see the discussion in #10280.

**Comment by proy87** [comment]
OK. Thanks.

**Comment by siefkenj** [comment]
This issue should be resolved by PR #11554.  I think it can be closed now.

**Comment by moorepants** [comment]
"Should be" or "is"? Can you add a unit test for this specific issue?

**Comment by siefkenj** [comment]
Sorry.  It is resolved and a unit test has already been added.

**Comment by versatran01** [comment]
The following matrix `C`
```
1     1     1    -1    -1    -1     0     0     0
0     0     0     1     1     1    -1    -1    -1
1    -1     0     1    -1     0     1    -1     0
0     1    -1     0     1    -1     0     1    -1
0     1     1    -1     0     0    -1     0     0
```

When I do `np.linalg.matrix_rank(C)` gives back 4.
But the reduced row-echelon form from sympy via `sympy.Matrix(C).rref()` has 5 pivots.
```
1 0 0 0 -1 0 0 -1 0
0 1 0 0  1 0 -1 0 -1
0 0 1 0 0 0 0 0 0 
0 0 0 1 1 0 0 0 -1
0 0 0 0 1 -1 -1 0
```
Did I do something wrong?

**Comment by siefkenj** [comment]
@versatran01 It is related to floating point issues.  If you use integers, you get

```
Matrix(C).rref() ==
(Matrix([
 [1, 0, 0, 0, -1, -1,  1,  0,  0],
 [0, 1, 0, 0,  1,  0, -1,  0, -1],
 [0, 0, 1, 0,  0,  1, -1, -1,  0],
 [0, 0, 0, 1,  1,  1, -1, -1, -1],
 [0, 0, 0, 0,  0,  0,  0,  0,  0]]), [0, 1, 2, 3])
```

However, if you use `float`s you need to pass an `iszerofunc`.  For example,

```Matrix(C).rref(iszerofunc=lambda x:abs(x)<10**-10)```

will give you a more appropriate answer.

**Comment by MooVI** [comment]
I thought this was fixed by #11554 ? Isn't that supposed to choose a sensible iszerofunc automatically (at least for standard types like floats? Or is this not possible for some reason? It still seems worrying to me that SymPy just silently returns the wrong result.

Having to set a lambda seems even more opaque to me than the old simplify=True flag.

**Comment by siefkenj** [comment]
Unfortunately this matrix doesn't seem to be reduced properly even with partial pivoting.  Partial pivoting increases numerical stability, but it doesn't give numerical perfection.  I agree, it is poor behaviour to silently give the wrong answer for matrices of floats.  I think a correct solution would be to create a `FloatMatrix` subclass that would set its `iszerofunc` automatically to something appropriate, and that a call to `Matrix` would automatically subclass to `FloatMatrix` if it were called on arrays of floats.

I've set it up to make this subclassing easier with PR #11592 but unfortunately it hasn't been reviewed or merged yet...

**Comment by MooVI** [comment]
I see, Your suggestion sounds very sensible. Hopefully your PR #11592 will be merged soon (I will try and at least review it soon but am not a member...).

Perhaps until then there should be some sort of warning. I notice in #11554 you assume a non-zero element to use as a pivot if none can be found, which also seems ripe for silent errors (which as you say in the comment is in line with the previous behaviour but to me seems bizarre, see discussion in #10120 ).

**Comment by moorepants** [comment]
The original now returns the following in master:

```
In [19]: simplify(Matrix([[3+3*sqrt(3)*I, -9],[4,-3+3*sqrt(3)*I]]).rref()[0])
Out[19]: 
Matrix([
[1, -3/4 + 3*sqrt(3)*I/4],
[0,                    0]])
```

but Wolfram seems to give a different answer:

https://www.wolframalpha.com/input/?i=rref(%5B%5B3%2B3*sqrt(3)*I,+-9%5D,%5B4,-3%2B3*sqrt(3)*I%5D%5D)

```
[[1, 3/4*I*(sqrt(3) + I)], [0, 0]]
```

**Comment by siefkenj** [comment]
Those are mathematically equivalent answers.

**Comment by moorepants** [comment]
Thanks, my algebra mus be rusty.
