### ISSUE TITLE
an error in the tutorial

### ISSUE THREAD

**Issue by tawaye** [sympy/sympy#10711]
I was going through the tutorial here
http://docs.sympy.org/latest/tutorial/gotchas.html
the sample code 

> > > Eq(x + 1, 4)
> > > x + 1 == 4
> > > is not correct. It should give
> > > x + 1 = 4
> > > this is trivial but hope someone could fix it.

**Comment by AkshaySiramdas** [comment]
Done!

**Comment by aravindkanna** [comment]
Hi, I too found this error in the tutorial. So anyone corrected it? can I continue?

**Comment by sidhantnagpal** [comment]
`Eq(x + 1, 4)` gives the correct representation in the latest docs.
