### ISSUE TITLE
sympy.Rational and sympy.core.numbers are not Number

### ISSUE THREAD

**Issue by emilienkofman** [sympy/sympy#10715]
I don't know if it's the intended behavior  but the instances of `sympy.Rational`, `sympy.core.numbers.Integer`, `sympy.core.numbers.Float` ... and so on are not Numbers in the sense of the numeric abstract base class [number](https://docs.python.org/2/library/numbers.html). For instance the Fraction type from the fractions module (which is more or less the same than the Rational type from sympy (?)) is a Number.
```python
>>> from numbers import Number
>>> from sympy import Rational, pi, sympify
>>> from fractions import Fraction as F
>>> isinstance(Rational(1,2), Number)
False
>>> isinstance(F(1,2), Number)
True
>>> isinstance(pi, Number)
False
>>> isinstance(sympify(1), Number)
False
>>> isinstance(sympify(1.0), Number)
False
```

edit:
sympy version '0.7.6.1' and Python 2.7.9.

**Comment by aravindkanna** [comment]
for the same command line inputs I am getting different outputs from those you got.

**In [29]: isinstance(Rational(1, 2), Number)
Out[29]: True

In [30]: isinstance(F(1, 2), Number)
Out[30]: False

In [31]: isinstance(pi, Number)
Out[31]: False

In [32]: isinstance(sympify(1), Number)
Out[32]: True

In [33]: isinstance(sympify(1.0), Number)
Out[33]: True
**

Is the thing got updated or what?

**Comment by emilienkofman** [comment]
I updated to:
```python
>>> sympy.__version__
'1.0.1.dev'
```
And obtained exactly the same results. @aravindkanna which version do you use? It is very weird since fractions has nothing to do with sympy, and should really be a `Number`...

**Comment by aravindkanna** [comment]
>>> from numbers import Number
>>> from sympy import *
>>> from fractions import *
>>> isinstance(Rational(1,2), Number)
True
>>> isinstance(Fraction(1,2), Number)
False
>>> isinstance(pi, Number)
False
>>> isinstance(simplify(1), Number)
True
>>> isinstance(simplify(1.0), Number)
True
>>> sympy.__version__
'1.0.1.dev'

I also have the same version. Previously I haven't run the commands on python script. But now I have run them using python script and the results are same.

**Comment by leosartaj** [comment]
@aravindkanna It seems to me you are mixing namespaces here (it's bad to do from ``from sympy import *``).

@emilienkofman SymPy has it's own ``Number`` class and we do not use ``numbers.Number`` class for defining things like ``Rational``, etc.

I don't see an issue here. Closing. Feel free to reopen, if something else comes up.

**Comment by emilienkofman** [comment]
Ok it just does not fit [the standard way to check that some argument is a numeric value](https://docs.python.org/2/library/numbers.html):

> The root of the numeric hierarchy. If you just want to check if an argument x is a number, without caring what kind, use isinstance(x, Number) but I don't know if this would be a valuable addition.

**Comment by leosartaj** [comment]
I guess, ``is_number`` can be used in this case.

eg.

```
>>> Rational(1, 2).is_number
True
>>> pi.is_number
True
>>> S.One.is_number
True
```

**Comment by thomasaarholt** [comment]
I am encountering this error as well, and find it a bit annoying. As @emilienkofman posts above, sympy.core.numbers are not recognised as numbers in the standard way of checking for numbers.
