### ISSUE TITLE
sympify(dict) should give Dict

### ISSUE THREAD

**Issue by AnishShah** [sympy/sympy#10726]
As discussed in #10657, sympify(dict) should return Dict (sympy/core/containers.py)

This is an easy issue, but some tests might fail.

@asmeurer Can you please confirm if this issue is valid?

**Comment by bjodah** [comment]
You probably mean `sympify(dict())` should return a `Dict`?
By analogy this raises the question if instances `list` should map to a sympy class, (`Array` eventually?).
