### ISSUE TITLE
Link to mpmath installation instructions is dead

### ISSUE THREAD

**Issue by certik** [sympy/sympy#10731]
When I try to run `sympy` and `mpmath` is not installed, I get:
```
.../sympy-1.0$ bin/isympy 
Traceback (most recent call last):
  File "bin/isympy", line 357, in <module>
    main()
  File "bin/isympy", line 353, in main
    from sympy.interactive import init_session
  File "/home/certik/Downloads/sympy-1.0/sympy/__init__.py", line 20, in <module>
    raise ImportError("SymPy now depends on mpmath as an external library. "
ImportError: SymPy now depends on mpmath as an external library. See http://docs.sympy.org/latest/install.html#mpmath for more information.
```
But the link http://docs.sympy.org/latest/install.html#mpmath seems to be a dead link. There is no `#mpmath` section on that page.

**Comment by asmeurer** [comment]
Yes, this is a known issue. The link won't be live until after we do the release and the docs are uploaded. You can see that the URL will be correct if you replace "latest" with "dev" in the URL.

**Comment by certik** [comment]
Indeed, http://docs.sympy.org/dev/install.html#mpmath is correct.
