### ISSUE TITLE
sympy.physics.units not up-to-date with CODATA

### ISSUE THREAD

**Issue by bjodah** [sympy/sympy#10742]
See this link for 2014 recommended values:
http://arxiv.org/pdf/1507.07956.pdf

**Comment by badcoderparashar** [comment]
is this issue free coz i want to work on it

**Comment by bjodah** [comment]
You are welcome to work on it. As you see there is an open PR regarding this issue.
You can start with reviewing that PR and add comments on e.g. something that can be improved or if something is missing. If you want to make substantial additions to said PR, it might be a good idea to see if it can be merged first and then you can start your own work on a subsequent PR. If the work on the referenced PR has stalled, then another option is to open a "competing" PR (which should then be considerably more extensive, of course).
