### ISSUE TITLE
Sympy-1.0.rc1 gives error on installation

### ISSUE THREAD

**Issue by PlatinumFrog** [sympy/sympy#10745]
When I install the version of sympy in the title on my mac, it gives the error:

  File "harddrive/user/desktop/sympy-1.0.rc1/setup.py", line 313, in <module>
    exec(open('sympy/release.py').read())
IOError: [Errno 2] No such file or directory: 'sympy/release.py'

There is in fact a release.py in the directory the error is talking about. I checked line 313 in setup.py and there doesn't seem to be an error there, but then again I don't know anywhere near as much about python as you by the looks of your code.

**Comment by moorepants** [comment]
Are you in the `sympy-1.0.rc1` directory when you run `setup.py`? If not, then it will not find the file.

**Comment by asmeurer** [comment]
setup.py should not require the current working directory to be the sympy/ directory. I'll push a fix for this to the release branch. Thanks for testing.

**Comment by asmeurer** [comment]
I pushed a fix to the release branch.

**Comment by asmeurer** [comment]
https://github.com/sympy/sympy/commit/d33c528568c16f11f07de41a1ddd3c2ddf4b61ac
