### ISSUE TITLE
Geometric algebra module missing from SymPy 1.0.rc1

### ISSUE THREAD

**Issue by JonnyMaddox** [sympy/sympy#10744]
The galgebra module is missing in the newest version, why, why?

**Comment by moorepants** [comment]
We are happy to answer your questions about the geometric algebra module but do not use language like this. It violates our code of conduct:

https://github.com/sympy/sympy/blob/master/CODE_OF_CONDUCT.md

**Comment by asmeurer** [comment]
See https://github.com/sympy/sympy/wiki/Release-Notes-for-1.0. Geometric algebra is now maintained separately at https://github.com/brombo/galgebra.

**Comment by asmeurer** [comment]
Perhaps we should add `sympy/galgebra.py` which raises an error message pointing to https://github.com/brombo/galgebra.

**Comment by asmeurer** [comment]
@brombo I recommend registering and uploading a release of `galgebra` to PyPI, so that we can point people to there. If you do this within the next 24 hours I will add this error message to point people there.

**Comment by brombo** [comment]
Why PyPi and not github.com/brombo/galgebra where it already is?

**Comment by asmeurer** [comment]
Having it on pypi will allow people to pip install it. When you register it you should include a link to the github page as the homepage.

**Comment by asmeurer** [comment]
https://github.com/sympy/sympy/pull/10756

**Comment by moorepants** [comment]
PyPi is the most popular and common way to distribute Python packages. It will allow people to simply type:

```
pip install galgebra
```

To install galagebra and all the dependencies. If it you only distribute through Github then users have to download the compressed source tree, uncompresses it, navigate into the directory, and run `python setup.py install`.

**Comment by moorepants** [comment]
But I guess people can do this too:

```
pip install git+https://github.com/brombo/galgebra.git
```

for a one liner.

**Comment by asmeurer** [comment]
Having it on PyPI lets you do versioned releases, and it makes the project more "official".

**Comment by brombo** [comment]
On 03/07/2016 04:49 PM, Jason K. Moore wrote:
>
> But I guess people can do this too:
>
> |pip install git+https://github.com/brombo/galgebra.git |
>
> for a one liner.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/sympy/sympy/issues/10744#issuecomment-193469181>.
>
My current setup.py is -

#!/usr/bin/env python
from setuptools import setup, find_packages
from distutils.core import Extension


setup(name='galgebra',
       version='0.4.0',
       description='Symbolic Geometric Algebra/Calculus modules for sympy',
       author='Alan Bromborsky',
       author_email='abrombo@verizon.net',
       license='BSD',
       packages=find_packages(),
       package_dir={'galgebra':'galgebra'},
       install_requires = [
                 'sympy',
                 'numpy'],
       #long_description=read('README'),
       classifiers=[
             'Development Status :: 4 - Beta',
             'Environment :: Console',
             'Intended Audience :: Science/Research',
             'License :: OSI Approved :: BSD License',
             'Natural Language :: English',
             'Operating System :: OS Independent',
             'Programming Language :: Python :: 2.7',
             'Topic :: Scientific/Engineering :: Mathematics',
             'Topic :: Scientific/Engineering :: Physics'])

which does not do anything that I can tell.  I am not clear on 
setup.py.  My instructions for setting up galgebra once it is downloaded 
from github is to run the program setgapth.py in the 
galgebra-master/galgebra directory which just sets the python path so 
that the galgebra modules can be used.  I don't know what setup() in 
setuptools does.  Any help would be appreciated.  I would like to put 
the github files downloaded in a directory that is easily accessed since 
they contain the LaTeX docs.  I know how to do this working directly 
with github but do not understand setup.py and pip.

**Comment by moorepants** [comment]
Alan, the `setup.py` file essentially copies your library to a location on the operating system that is available to all users along side the system python, i.e. it "installs" the software. If a user has your source directory they can simple execute:

```
python setup.py install
```

and it will put all the files in the correct place. Then you can be in any directory on your computer and successfully import galgebra. Secondly when download/installation tools are used (e.g. `pip) they look for the `setup.py` file to install the software. This makes the software more end-user friendly.

Here are a couple of resources about packaging python code to make it more easily installable for users (and developers):

- https://python-packaging-user-guide.readthedocs.org/en/latest/
- https://python-packaging.readthedocs.org/en/latest/
- http://docs.python-guide.org/en/latest/shipping/packaging/

**Comment by asmeurer** [comment]
The import warning was implemented.
