### ISSUE TITLE
ImageSet._contains error

### ISSUE THREAD

**Issue by smichr** [sympy/sympy#10746]
The following (AFAICT) should be True

```python
>>> x = Interval(1,2)*Interval(2,3)*Interval(0,3)
>>> Tuple(3,1,0) in imageset(Lambda((a,y,z),(y,a,z)),x)
False
>>> Tuple(S(1)/3,1,0) in imageset(Lambda((a,y,z),(1/y,a,z)),x)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "sympy\sets\sets.py", line 508, in __contains__
    symb = sympify(self.contains(other))
  File "sympy\sets\sets.py", line 283, in contains
    ret = sympify(self._contains(other))
  File "sympy\sets\fancysets.py", line 240, in _contains
    zip(other, L.expr)], L.variables).args[0])
IndexError: tuple index out of range
```

Corrected in #10645

**Comment by smichr** [comment]
This just needs a test at about line 86 in `test_fancysets.py`.

**Comment by nagarakshay** [comment]
I would like to work on this.

**Comment by nagarakshay** [comment]
Is this issue fixed? Because in my sympy `
 from sympy import* 
`>>> y,z,a=symbols('y z a')
>>> x=Interval(1,2)*Interval(2,3)*Interval(0,3)
>>> Tuple(3,1,0) in imageset(Lambda((a,y,z),(y,a,z)),x)
True
>>> Tuple(S(1)/3,1,0) in imageset(Lambda((a,y,z),(1/y,a,z)),x)
True
`

**Comment by kshitij10496** [comment]
@nagarakshay
Yes. 
The core issue has been fixed by #10645
But we still need tests to be added.
You can give this a try

**Comment by nagarakshay** [comment]
@smichr Thanks for the feedback. Does it look ok now?

**Comment by smichr** [comment]
Yes, that looks right. Could you include spaces after the commas, please? And there is no need to recreate a new PR. Just open the old one, and push your branch there and it will be updated.

**Comment by nagarakshay** [comment]
@smichr I was not able to reopen the PR. So I created a new PR . I amended the commas as you advised. Thanks.

**Comment by smichr** [comment]
The test was merged but didn't have an autoclose tag. Closing manually.

**Comment by nagarakshay** [comment]
@smichr Thank you,sir. I wont forget it next time.
