### ISSUE TITLE
add Rationals to fancysets

### ISSUE THREAD

**Issue by smichr** [sympy/sympy#10757]
Changes made by #10645 make possible a Rationals class:

```
>>> Rationals = imageset((x, y), x/y, S.Integers*S.Integers)
>>> S.Half in Rationals
True
>>> 1/pi in Rationals
False
```

Perhaps the product set should be `S.Integers*S.Naturals` since the sign is always associated with the numerator of a Rational, and there is no option to create an unevaluated Rational.

**Comment by kshitij10496** [comment]
@smichr I would like to give this a try

**Comment by smichr** [comment]
sounds good

**Comment by kshitij10496** [comment]
Thank you @smichr

**Comment by smichr** [comment]
A more well-behaved and tractable form is: `Rationals = S.Integers*S.Naturals` and a `contains` method would convert input into the tuple form before asking if it is in the `ProductSet`, e.g. `Rationals.contains(arg)` would return `arg.as_numer_denom() in self`

**Comment by smichr** [comment]
It just occurred to me that perhaps a good optional keyword to add to imagesets is `contains` which defines a function that would be used to define any custom behavior for how to decide if something is in the mapping or not, e.g. 
```python
def contains(x):
    n, d = x.as_numer_denom()
    return fuzzy_and([n.is_integer, d.is_integer, d.is_nonzero])
rationals = imageset((x, y), x/y, S.Integer, S.Naturals, contains=contains)
```

**Comment by oscarbenjamin** [comment]
It's not really in the spirit of Basic that an object can depend on an arbitrary Python function like that.

It should be possible to define Rationals using
```
In [20]: rat_tuple = ConditionSet((x,y), [S.Integers.contains(x) & S.Naturals.contains(y)], S.Integers**2)                        

In [21]: rat_tuple                                                                                                                
Out[21]: 
⎧                   2                        ⎫
⎨(x, y) | (x, y) ∊ ℤ  ∧ ({(x ∈ ℤ) ∧ (y ∈ ℕ)})⎬
⎩                                            ⎭
```
Trying to put that into an ImageSet doesn't quite work though (note x in rather than (x,y) in):
```
In [22]: Rationals = ImageSet(Lambda((x, y), x/y), rat_tuple)                                                                     

In [23]: Rationals                                                                                                                
Out[23]: 
⎧x       ⎧                   2                        ⎫⎫
⎨─ | x ∊ ⎨(x, y) | (x, y) ∊ ℤ  ∧ ({(x ∈ ℤ) ∧ (y ∈ ℕ)})⎬⎬
⎩y       ⎩                                            ⎭⎭
```
Maybe like with Python's list comprehensions what is needed is something that combines both filtering and mapping...

**Comment by oscarbenjamin** [comment]
Adding a Rational set could close #5952

**Comment by smichr** [comment]
We can already define it as `Rationals = imageset((x, y), x/y, S.Integers*S.Naturals)` with the `contains` hack that is already in place to make compare (numer, denom) when imageset is vector->scalar. This work was started in #10777.

**Comment by jksuom** [comment]
Another possibility is `ConditionSet(x, x.is_Rational)`

**Comment by oscarbenjamin** [comment]
The condition for a ConditionSet needs to be a relation involving x so that doesn't work:
```julia
In [33]: x = Symbol('x')                                                                                                                          

In [34]: x.is_Rational                                                                                                                            
Out[34]: False

In [35]: ConditionSet(x, x.is_Rational)                                                                                                           
Out[35]: ∅
```

**Comment by smichr** [comment]
> not really in the spirit of Basic that an object can depend on an arbitrary Python function like that.

Agree. So when such a need is present it means that an object should be created. I guess this could happen at the SymPy or user level.

**Comment by smichr** [comment]
> The condition for a ConditionSet needs to be a relation involving x so that doesn't work:

@jksuom , I was thinking the same thing. But we also want behavior similar to 
```python
>>> Dummy(integer=True) in S.Integers
True
>> Dummy(rational=True) in S.Rationals
True
```

**Comment by smichr** [comment]
We are trying to solve this at too high a level -- look at what the other classes are doing:
```python
class Integers(with_metaclass(Singleton, Set)):

    is_iterable = True

    def _contains(self, other):
        if not isinstance(other, Expr):
            return S.false
        elif other.is_integer:  --> change to 
            return S.true
        elif other.is_integer is False:
            return S.false

    def __iter__(self):
        yield S.Zero
        i = S.One
        while True:
            yield i
            yield -i
            i = i + 1

    @property
    def _inf(self):
        return -S.Infinity

    @property
    def _sup(self):
        return S.Infinity

    @property
    def _boundary(self):
        return self
```
Rationals would not be iterable and would use `is_rational` instead of `is_integer`.

**Comment by smichr** [comment]
Or it could iterate over `+/-a/b` for increasing `b` with `a` relatively prime to `b`? To limit the denominator one would generate until the `b` exceeded the limit. Rationals in Interval(a, b) with denominator less than c would be smthg like `a + (b-a)*{Rationals with denominator less than c*(b-a)}`. Or instead of iterating, one could retrieve a subset by intersecting with the desired grid, e.g. `Rationals.intersection(imageset((x,y) x/y, S.Integers, Range(1,11)).Interval(3, 7))` to give fractions between 3 and 7 (inclusive) with denominator no greater than 10.  {But there are methods for generating increasing fractions for a product of two finite sets as [here](https://github.com/sympy/sympy/pull/10777#issuecomment-195604469).}
