### ISSUE TITLE
(1/(x**-2 + x**-3)).series(x, 0) gives wrong result

### ISSUE THREAD

**Issue by vovapolu** [sympy/sympy#10761]
`(1/(x**-2 + x**-3)).series(x, 0)` returns `x**3 - x**4 + O(x**6)` which is incorrect. Wolfram Alpha gives `x**3 - x**4 + x**5 - x**6 + x**7 + O(x**8)`.

**Comment by jksuom** [comment]
This is probably related to #10503.

**Comment by vovapolu** [comment]
@jksuom I found wrong behavior in method `_eval_nseries` in '`Pow` class while debugging this issue #9549
