### ISSUE TITLE
autowrap on windows -- distutils doesn't work with C compiler

### ISSUE THREAD

**Issue by chubukov** [sympy/sympy#10784]
I am running into problems trying to use autowrap on Windows with Anaconda python 2.7.

```
import sympy
from sympy.utilities.autowrap import autowrap
x,y=sympy.symbols('x,y')
autowrap(x+y,args=[x,y],backend='cython')
```

...
```
CodeWrapError: Error while executing command: C:\Users\victor.chubukov\AppData\Local\Continuum\Miniconda3\envs\py27\python.exe setup.py build_ext --inplace. Command output is:
running build_ext
cythoning wrapper_module_0.pyx to wrapper_module_0.c
building 'wrapper_module_0' extension
error: Unable to find vcvarsall.bat
```

I do have the MS Visual Studio 2008 compiler installed and I have no problem building python packages from source. However, I believe the root of the problem is that this compiler is only found by setuptools and not by distutils.

If I go into setup.py and replace
```
from distutils.core import setup
from distutils.extension import Extension
```
with
```
from setuptools import setup
from setuptools import Extension
```

then I'm able to run `python setup.py build_ext --inplace` and it creates the `wrapper_module1.pyd` file.

However, this doesn't get me very far in terms of actually being able to use autowrap in my code. Is there an easy workaround that I'm missing? Or am I doing something wrong further upstream?

**Comment by chubukov** [comment]
Modifying `setup_template` in utilities/autowrap.py to use setuptools led to working behavior. I don't know what other implementations may depend on distutils, so I leave it to the more experienced folks to decide whether this change should be implemented.

**Comment by moorepants** [comment]
We should probably implement this:

```python
try:
    from setuptools import setup
    from setuptools import Extension
except ImportError:
    from distutils.core import setup
    from distutils.extension import Extension
```

as per https://github.com/cython/cython/wiki/CythonExtensionsOnWindows

**Comment by moorepants** [comment]
Posted a fix here #10789, can you see if that works for you?

**Comment by chubukov** [comment]
Yes, as expected that also works fine.

**Comment by chubukov** [comment]
By the way, there is a similar issue with `ufuncify`, which uses `numpy.distutils`. I'm not sure what the recommended workaround is for that.

**Comment by moorepants** [comment]
Can you please make a new issue for ufuncify and specify exactly what goes wrong (tracebacks and such)? Thanks. We don't test these on Windows often, so there are bound to be bugs.
