### ISSUE TITLE
Bad pretty printing of power of Limit

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#10803]
```
In [240]: 1/limit(airyai(x)*2*root(x, 4)*exp(2*x**(S(3)/2)/3), x, oo)**2
Out[240]:
                             -2
                3/2
             2⋅x
             ──────
      4 ___    3
lim 2⋅╲╱ x ⋅ℯ      ⋅airyai(x)
x─→∞
```

The `-2` power is just floating there. There needs to be parentheses. Marking as easy to fix because it's probably just an issue of marking the precedence of Limit correctly.

**Comment by badcoderparashar** [comment]
has this been fixed because i ll like to try it

**Comment by AnishShah** [comment]
No, it's not fixed.

**Comment by badcoderparashar** [comment]
can you guide me where to checks there

so i can make change

**Comment by badcoderparashar** [comment]
i know what to change can you provide me with the directory you worked with

**Comment by asmeurer** [comment]
The pretty printer is in sympy/printing/pretty/

**Comment by badcoderparashar** [comment]
on it

**Comment by Imran31** [comment]
I would like to work on this, and I want to clarify if you want the parentheses around the entire limit expression.

**Comment by asmeurer** [comment]
Yes, there should be parentheses around the whole thing, since it is the whole limit being taken to the -2 power. It should look like this

```
                               -2
⎛                3/2          ⎞
⎜             2⋅x             ⎟
⎜             ──────          ⎟
⎜      4 ___    3             ⎟
⎜lim 2⋅╲╱ x ⋅ℯ      ⋅airyai(x)⎟
⎝x─→∞                         ⎠
```

(I did that by hand so hopefully it's correct)

**Comment by rd13123013** [comment]
Ping @asmeurer

**Comment by asmeurer** [comment]
https://github.com/sympy/sympy/pull/10940 fixed this.
