### ISSUE TITLE
LaTeX printer: Integral not surrounded in brackets

### ISSUE THREAD

**Issue by Upabjojr** [sympy/sympy#10806]
```
In [3]: print latex(Integral(z,z)**2)
\int z\, dz^{2}
```
Should be:
```latex
\left( \int z\, dz\right)^{2}
```

**Comment by gxyd** [comment]
Thanks for opening this!. I realised this in https://github.com/fredrik-johansson/314/pull/6 .

**Comment by sampadsaha5** [comment]
@gxyd @Upabjojr 

I am getting this : 

```
In [1]: Integral(z,z)**2
Out[1]: 
        2
⎛⌠     ⎞ 
⎜⎮ z dz⎟ 
⎝⌡     ⎠ 
   
      
In [2]: print latex(Integral(z,z)**2)
\left(\int z\, dz\right)^{2}
```

I am not getting an issue.

**Comment by gxyd** [comment]
I get this issue on Python2.7 and Python3.5 (both) with development version of SymPy on jupyter notebook and terminal as well. Can you specify your system details?

**Comment by Upabjojr** [comment]
Precedence operation here:
https://github.com/sympy/sympy/blob/5b3889aa679bdc808e27bb283cd516a048ccec13/sympy/printing/latex.py#L148

For `Pow` it is set to 60, for `Integral` it's 1000.

The problem is that `Integral` counts as some kind of single variable element, therefore it gets a precedence value of 1000.

For reference
```python
(Pdb) PRECEDENCE
{'Xor': 10, 'Add': 40, 'Relational': 35, 'Mul': 50, 'Or': 20,
'Lambda': 1, 'And': 30, 'Pow': 60, 'Func': 70, 'Atom': 1000, 'Not': 100}
```

Another related issue
```
In [7]: Integral(z+x, z)
Out[7]: 
⌠           
⎮ (x + z) dz
⌡           

In [8]: print latex(_)
\int x + z\, dz
```

LaTeX expression lacks brackets inside Integral, it should be:
```latex
\int (x + z)\, dz
```

**Comment by Upabjojr** [comment]
Maybe `Integral` should have the same `PRECEDENCE` as `Mul`?

**Comment by Upabjojr** [comment]
Update: this bug has been introduced in SymPy 1.0.
