### ISSUE TITLE
Unicode test error with Python 2.7.10

### ISSUE THREAD

**Issue by verdurin** [sympy/sympy#10818]
When testing a build of sympy using EasyBuild, I see the following error during the tests:

```
____________ sympy/diffgeom/tests/test_hyperbolic_space.py:test_H2 _____________
  File "sympy/core/compatibility.py", line 137, in exec_
    exec("exec _code_ in _globs_, _locs_")
  File "<string>", line 1, in <module>
  File "/home/adam/.local/easybuild/build/sympy/1.0/foss-2015b-Python-2.7.10/sympy-sympy-1.0/sympy/external/tests/test_autowrap.py", line 17, in <module>
    autowrap(symbols('x'), 'f95', 'f2py')
  File "sympy/core/cache.py", line 93, in wrapper
    retval = cfunc(*args, **kwargs)
  File "sympy/core/compatibility.py", line 899, in wrapper
    result = user_function(*args, **kwds)
  File "sympy/utilities/autowrap.py", line 531, in autowrap
    return code_wrapper.wrap_code(routine, helpers=helps)
  File "sympy/utilities/autowrap.py", line 144, in wrap_code
    self._process_files(routine)
  File "sympy/utilities/autowrap.py", line 167, in _process_files
    " ".join(command), e.output.decode()))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 4082: ordinal not in range(128)
```

Someone mentioned that this might be due to locale settings, so I changed them to `en_US.utf8`, but that didn't make any difference.

**Comment by boegel** [comment]
@verdurin same problem as in #4549?

**Comment by micklat** [comment]
I just ran into the same problem. It's probably not the same problem as #4549. I worked around it by removing the ".decode()" from the line: 

```
            raise CodeWrapError(
                "Error while executing command: %s. Command output is:\n%s" % (
                    " ".join(command), e.output.decode()))
```
So the unicode problem goes away when you have this instead:
```
            raise CodeWrapError(
                "Error while executing command: %s. Command output is:\n%s" % (
                    " ".join(command), e.output))
```
Which, of course, only allows you to see the error message from the failed command, so takes you to the next problem you have to solve.

Shall I make a pull request for that?

**Comment by oscarbenjamin** [comment]
Is this still a problem?

**Comment by boegel** [comment]
We worked around for `sympy` 1.0 with a patch, see https://github.com/easybuilders/easybuild-easyconfigs/pull/3058/files#diff-93716e356b5691213ae8594a2b7e0742.

That looks quite similar to what's there now in `master`, i.e. `.decode('utf-8')`, so I guess this is good to close.

@verdurin is the right person to call this though, maybe with a test report to the `sympy` 1.3 easyconfig contributed in https://github.com/easybuilders/easybuild-easyconfigs/pull/7405 ?
