### ISSUE TITLE
Latex generation error for .series expansion for \rightarrow term 

### ISSUE THREAD

**Issue by mnmt** [sympy/sympy#10836]
Best shown with [notebook view of this gist](http://nbviewer.jupyter.org/gist/mnmt/3804cdaaeb70300a719e), but basically when the latex is produced for a series expansion for variable x around point x0 at the end of the expansion there is a "as x --> x0" at the end for the neglected expansion terms, which displays correctly when x0 is a number, e.g:
`x \rightarrow5`
 but when x0 is a symbol it doesn't
`x \rightarrowx_{0}`

It seems that *a space needs to be added between \rightarrow and the following term* for it to be read/rendered correctly.

Using sympy version: 0.7.6.1 as part of conda version : 3.19.0

**Comment by mnmt** [comment]
Added pull request #10837, I think this will fix it? Appreciate a look over to check though since I don't know how to easily test it myself.

**Comment by leosartaj** [comment]
This appears to be a bug. Also, @mnmt SymPy 1.0 is out. There are many bug fixes and new features. I suggest you should upgrade. :smile:
