### ISSUE TITLE
KanesMethod.kanes_equations() should accept an empty variable for the loads.

### ISSUE THREAD

**Issue by moorepants** [sympy/sympy#10841]
```python
kane = KanesMethod(....)
kane.kanes_equations((,), (b1, b2, b3))
```
should work. Not all systems have external loads (forces and torques) applied to them. This currently errors and requires you to add at least one dummy load.

**Comment by rehassachdeva** [comment]
Hi, I'm a beginner. I would like to work on this. Could you please guide me how to go about this?
I took a look at the `kanes_equations` method and `_form_fr`.

**Comment by moorepants** [comment]
There are tests that exercise the KanesMethod class. You should start by modifying the tests by passing in an empty iterable for the loads. fr should then be a zero column matrix and frstar should successfully compute the correct equations.

**Comment by rehassachdeva** [comment]
Thanks for the directions @moorepants . But i haven't used KanesMethod or Matrix before. 
Could you please guide me as to which tests I should try modifying.
Say in `test_one_dof`  in `test_kane.py` would this be a good approach?
```
fr, frstar = KM.kanes_equations((,), BL)
...
assert fr.expand() == Matrix([0, 0, 0, 0, 0])
```

**Comment by aravindkanna** [comment]
@moorepants , 
Sir, I have made some changes to `kanes_equations()` class. I got the following as result. Please review it once.

```
In [13]: fr, frstar = kane.kanes_equations((), BL)

In [14]: fr
Out[14]: [0]

In [15]: frstar
Out[15]: 
⎡   d       ⎤
⎢-5⋅──(u(t))⎥
⎣   dt      ⎦

In [16]: fr, frstar = kane.kanes_equations(FL, BL)

In [17]: fr
Out[17]: [7]

In [18]: frstar
Out[18]: 
⎡   d       ⎤
⎢-5⋅──(u(t))⎥
⎣   dt      ⎦

```

Just check whether it is correct or not. Just as you said fr is a zero column matrix and frstart is computing as it should be.

**Comment by moorepants** [comment]
@rehassachdeva You can modify https://github.com/sympy/sympy/blob/master/sympy/physics/mechanics/tests/test_kane.py#L11 and set FL to an empty tuple. That should be sufficient.

**Comment by moorepants** [comment]
@aravindkanna Please submit a pull request if you think you have a fix.
