### ISSUE TITLE
integrate(sqrt(x - y) * log(z / x), x) has no result

### ISSUE THREAD

**Issue by lindsayad** [sympy/sympy#10847]
but with Mathematica I can get a solution:

2/9 (6 y^(3/2) ArcTan(Sqrt(x - y)/Sqrt(y)) + Sqrt(x - y) (2 (x - 4 y) + 3 (x - y) Log(z/x)))

Where in sympy would we have to do work to implement a solution?

**Comment by asmeurer** [comment]
The simplest way to fix it is to add some rules to manualintegrate.
