### ISSUE TITLE
multidimensional interval fails bool test

### ISSUE THREAD

**Issue by smichr** [sympy/sympy#10859]
``` python
>>> Interval(2,3)*Interval(1,2)
[2, 3] x [1, 2]
>>> c=_
>>> if c:print 1
...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "sympy\sets\sets.py", line 666, in __len__
    return Mul(*[len(s) for s in self.args])
TypeError: object of type 'Interval' has no len()
```

Although `__nonzero__` could be defined, it looks like bool calls to `len`; is there any way to fix this?

**Comment by rd13123013** [comment]
can we define `len` for `Interval` ?

**Comment by frankwang95** [comment]
I'd like to solve this.

**Comment by asmeurer** [comment]
We should define `__nonzero__`. I think it defaults to calling len if it isn't defined.

**Comment by frankwang95** [comment]
Is it a problem then that `len` can be called on `ProductSet` type objects?

**Comment by leosartaj** [comment]
> I'd like to solve this. Would it suffice to simply define len to be inf or 0 for Intervals?

Consider,

```
>>> FiniteSet(2, 3) * FiniteSet(4, 5)
{2, 3} × {4, 5}
```

The length in this case should be 4. If you want to implement ``__len__`` you will need to cover these cases as well. Defining, ``__nonzero__`` should be much easier.

**Comment by frankwang95** [comment]
I submitted the pull request, having defined `__nonzero__`.

In response to leosartaj, Implementing `__len__` for intervals would be the only problem. It is already defined for ProductSet to be the product of each of the elements in `self.arg`.  The only question is to how to naturally define `__len__` on intervals.

**Comment by asmeurer** [comment]
You can't define `__len__` on intervals. The mathematical answer would be some kind of infinity, but `__len__` can only return an int (https://docs.python.org/3.5/reference/datamodel.html#object.__len__). Hence, the current behavior or raising a TypeError is the correct one.

**Comment by oscarbenjamin** [comment]
The behaviour seems to have changed since the last comment here. I think the new current behaviour is reasonable:
```
In [13]: Interval(2,3)*Interval(1,2)                                                                                                           
Out[13]: [2, 3] × [1, 2]

In [14]: bool(Interval(2,3)*Interval(1,2))                                                                                                     
Out[14]: True

In [15]: bool(Interval(2, 1))                                                                                                                  
Out[15]: False

In [16]: bool(Interval(2, 2))                                                                                                                  
Out[16]: True

In [17]: bool(Interval(2, 1.999999))                                                                                                           
Out[17]: False

In [18]: bool(Interval(2, 3))                                                                                                                  
Out[18]: True
```
As afar as I can tell bool(interval) is true if the interval is non-empty.
