### ISSUE TITLE
solve_univariate_inequality bug

### ISSUE THREAD

**Issue by proy87** [sympy/sympy#10854]
`solve_univariate_inequality(1/(x-2)**2 >= 0, x)` should return all real line except `x=2`, but instead it returns all real line.

**Comment by Shekharrajak** [comment]
You can use `solveset`
```
>>> solveset(1/(x-2)**2 >= 0, x,S.Reals)
(-∞, 2) ∪ (2, ∞)

```

**Comment by proy87** [comment]
Thank you.
