### ISSUE TITLE
Where is formula parser documentation?

### ISSUE THREAD

**Issue by ceremcem** [sympy/sympy#10866]
Hello, 

I want to use my LibreOfficeMath equations in Sympy, so I first need to build a tokenizer for LibreOfficeMathFormulaLanguage and then pass this tokenized formula to Sympy somehow. 

Where can I find the Scmpy's formula tokenizer so I can test my tokenized formulas directly in Scmpy?

**Comment by bjodah** [comment]
Hello,

We try to track issues regarding SymPy in the issue tracker.
You may want to try to ask your question at stackoverflow and tag it with the [sympy tag](http://stackoverflow.com/questions/tagged/sympy) (perhaps along with an minimal example showing what you are aiming to achieve).

You will find the documentation for the parsers here: http://docs.sympy.org/dev/modules/parsing.html

If you are writing your own parser (I am not completely sure what you want to do), you may also want to read the actual source code of the parsing module: https://github.com/sympy/sympy/tree/master/sympy/parsing

If you think that your parser will be of interest to more people, we will happily review your parser for inclusion into SymPy as a pull request. There is also a mailing list here: https://groups.google.com/forum/#!forum/sympy

Hope it helps.

**Comment by ceremcem** [comment]
Hi, 

As described [here](http://stackoverflow.com/questions/36096388/is-there-any-way-to-use-latex-formulas-in-a-programming-language-to-make-a-real) there is DRY problem which I'm also hitting. Since I find LaTex a little bit cryptic, I want to implement the exactly [the same functionality](https://github.com/augustt198/latex2sympy) with [LibreOffice's Math Formula syntax](https://wiki.documentfoundation.org/images/3/37/MG40-MathGuide.pdf) and solve this equation with SymPy. 

But the thing that I'm avoiding is that the sytax used for math formulas are varying between programming languages and if I write that compiler only for SymPy, then I have to write for all of languages that I plan to port. Therefore, I think there must be a meta format (a non human readable format, ie. in JSON) that represents a formula. 

The reason I asked this question in here is that if there is such a format used in SymPy already, I can pick that format up for an easy start, so that I only have to write a library to convert LibreOffice's format to that abstract format (which SymPy can read natively) for a quick startup and then a small converter to make `SOME_JAVASCRIPT_LIBRARY` understand that format. 

Thank you for the tips, I'll take a look at all of these.
