### ISSUE TITLE
solveset errors if numerator doesn't have symbol

### ISSUE THREAD

**Issue by smichr** [sympy/sympy#10876]
```
>>> solveset(1/sqrt(x),x)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "sympy\solvers\solveset.py", line 792, in solveset
    return _solveset(f, symbol, domain, _check=True)
  File "sympy\solvers\solveset.py", line 613, in _solveset
    solver)
  File "sympy\solvers\solveset.py", line 492, in _solve_radical
    eq, cov = unrad(f)
TypeError: 'NoneType' object is not iterable
```

...but not always:

```
>>> solveset(1/x**2,x)
EmptySet()
```

**Comment by Nitin216** [comment]
Hey smichr, when the numerator is number unrad simply return and thus NoneType. Could you suggest me how to find the solution to this problem ??

**Comment by smichr** [comment]
I think I have modifications towards this end in my range2 branch. Basically, don't call `_solveset` if the numerator doesn't have the symbol of interest. The same thing needs to be applied to where Mul's are being handled in `_solveset` since `(x-1)/sqrt(x)` will otherwise fail *there* even though it passes out of `solveset`. If you want to cherry pick the commit from my branch and open a PR that would be fine with me.

**Comment by rd13123013** [comment]
@smichr  couldn't find anything in range2 branch

**Comment by smichr** [comment]
> couldn't find anything in range2 branch

I'll check later this evening. I just made two changes as suggested above. But I'll see if I can find those and open a PR or make a branch/diff availiable.

**Comment by oscargus** [comment]
Works on current master. I'll add a test that closes this.
