### ISSUE TITLE
Allow GoldenRatio to be written in sqrt form

### ISSUE THREAD

**Issue by leosartaj** [sympy/sympy#10894]
Desired functionality,

```
>>> S.GoldenRatio.rewrite(sqrt)
1/2 + sqrt(5)/2
```

**Comment by harmor11** [comment]
Hello,
I am a beginner at fixing issues, but I would like to contribute.
What exactly is S? (in S.GoldenRatio)

**Comment by harmor11** [comment]
Actually, 1/2 + sqrt(5)/2 can be achieved by
`>>> GoldenRatio.expand(func=true)`

**Comment by leosartaj** [comment]
> What exactly is S? (in S.GoldenRatio)

``S`` is short for ``SingletonRegistry``. It is just a registry for all the singletons. Surprisingly I don't see any [docs](http://docs.sympy.org/latest/modules/core.html#s) for it.

> Actually, 1/2 + sqrt(5)/2 can be achieved by
``>>> GoldenRatio.expand(func=true)``

Yes, correct. It would be nice if this can also be achieved using ``rewrite``.

**Comment by Nitin216** [comment]
This issue is resolved from #10900 PR
