### ISSUE TITLE
rewrite im() in terms of re() and vice versa

### ISSUE THREAD

**Issue by thisch** [sympy/sympy#10897]
There is a bug in the rewrite logic in ``complexes.py`` (see https://github.com/sympy/sympy/pull/8359#issuecomment-200560081 and https://github.com/sympy/sympy/pull/8359#issuecomment-200713532). 

The expected output should be:
```py
re(x).rewrite(im) == x - I*im(x)
im(x).rewrite(re) == -I*(x - re(x))
```

**Comment by Nitin216** [comment]
This issue is resolved by PR #10899
