### ISSUE TITLE
statement is not being accepted in Python3.4.4rc1 Shell

### ISSUE THREAD

**Issue by SHIVAPRASAD96** [sympy/sympy#10909]
The following statement is not being accepted in 3.4.4rc1 Shell
 x,y,z=symbols('x y z')
Error shown is: 
Traceback (most recent call last):
  File "<pyshell#6>", line 1, in <module>
    x,y,z=symbols('x y z')
NameError: name 'symbols' is not defined

**Comment by leosartaj** [comment]
Did you import sympy?

**Comment by SHIVAPRASAD96** [comment]
Yes i imported sympy

**Comment by SHIVAPRASAD96** [comment]
it got fixed thanks, we need to give import and that statement on after other.
