### ISSUE TITLE
fourier_series cannot be imported

### ISSUE THREAD

**Issue by akritas** [sympy/sympy#10912]
from sympy import fourier_series, pi, cos

results in

ImportError: cannot import name fourier_series

**Comment by leosartaj** [comment]
Which version you are using?

**Comment by akritas** [comment]
The very latest I think. From github.
Quoting Sartaj Singh <notifications@github.com>:

**Comment by leosartaj** [comment]
```
In [1]: import sympy as sy

In [2]: from sympy import fourier_series, pi, cos

In [3]: sy.__version__
Out[3]: '1.0.1.dev'
```

This should work for SymPy-1.0

**Comment by akritas** [comment]
[2] gives me the same Import error.

[3] gives me

0.7.3

Quoting Sartaj Singh <notifications@github.com>:

**Comment by akritas** [comment]
On my other computer (ubuntu) I have 0.7.4.1 and also does not work.

Quoting Sartaj Singh <notifications@github.com>:

**Comment by leosartaj** [comment]
You should update your SymPy version to the latest 1.0. Instructions can be found [here](http://docs.sympy.org/latest/install.html).

**Comment by akritas** [comment]
Thank you. Will do.

Quoting Sartaj Singh <notifications@github.com>:
