### ISSUE TITLE
Regression: `Eq(x, oo)` should not evaluate

### ISSUE THREAD

**Issue by cbm755** [sympy/sympy#10927]
After #10644, `Eq(x, oo)` is now False, but should be unevaluated (as it was before #10644).  I thought I'd added tests for this but perhaps I ended up dropping the patch---if so, sorry!

(`Eq(f, oo)` where `f = symbols('f', finite=True)` could be False: I think it was unevaluated before #10644.)

**Comment by isuruf** [comment]
Reported by @CodeMaxx,
`Eq(-oo, oo)` is now True. 

cc @smichr

**Comment by cbm755** [comment]
This is pretty serious: we should not release with this problem, added the 1.1 milestone.

**Comment by cbm755** [comment]
Eh really?  With git master on either python2 or python3 I get:
````
In [4]: Eq(-oo, oo)
Out[4]: True

In [5]: Eq(x, oo)
Out[5]: False
````

Where-as with SymPy 1.0 I have:
````
In [4]: Eq(-oo, oo)
Out[4]: False

In [5]: Eq(x, oo)
Out[5]: Eq(x, oo)
````

For me, this has been broken since #10644.

**Comment by sum2it** [comment]
How do I reproduce the first pair of results? I've only been able to reproduce the second pair(presumably correct).

**Comment by cbm755** [comment]
Do you have a git clone?  You cannot reproduce from sympy 1.0.
