### ISSUE TITLE
Infinite recursion in Delta function integration

### ISSUE THREAD

**Issue by zanzibar7** [sympy/sympy#10922]
If we try

```
integrate(DiracDelta(x-1).diff(x)*x**2,(x,0,2))
```

we get an infinite recursion.  The problem is different but related to issues #4523 and #6968 .
Looking through the code, it seems `change_mul()` is called recursively without appropriate
checks on its arguments.  I have an simple fix to propose.

**Comment by ethankward** [comment]
This is resolved with #10923.
