### ISSUE TITLE
Simple linear equation raises NotAlgebraic in solve

### ISSUE THREAD

**Issue by proy87** [sympy/sympy#10930]
`solve([Eq(9*x, pi**2)],[x])` raises NotAlgebraic Exception.

However, solution is simple: x = pi**2/9

**Comment by AkshaySiramdas** [comment]
solve(Eq(9*x, pi**)) gives the desired result

**Comment by Nitin216** [comment]
@proy87 You are using '[' wrong. Due to these it is giving NotAlgrebraic.
My output is coming right
```
In [3]: solve(Eq(9*x,pi**2),x)
Out[3]:
   2
 pi
[---]
  9
```

**Comment by proy87** [comment]
@Nitin216 , following doesn't work:
`from sympy.abc import A,B,C`
`from sympy import pi, Eq, solve`
`solve([Eq(A + B, 0), Eq(C, 0), Eq(9*A, pi**2)])`

**Comment by Nitin216** [comment]
@proy87 if u interchange the import in you second code then it will also give error. I don't know why this is happening

**Comment by Shekharrajak** [comment]
You can use `linsolve` : 
```
>>> linsolve([Eq(A + B, 0), Eq(C, 0), Eq(9*A, pi**2)],[A,B,C])
⎧⎛ 2    2    ⎞⎫
⎪⎜π   -π     ⎟⎪
⎨⎜──, ────, 0⎟⎬
⎪⎝9    9     ⎠⎪
⎩             ⎭

```

**Comment by smichr** [comment]
In the case that is failing, you are solving a system of equations with the *number symbol* pi whose value is 3.14... when evaluated; when it doesn't fail, you are using the symbol named pi. By using the square brackets the way you did, you forced `solve` to solve the single equation using the matrix method. If you had left the brackets off, you would have obtained a solution. 

There still remains the problem of why the system failed with `pi` -- it shouldn't fail like that.

Based on the following,

```
>>> Eq(9*x,pi**2).as_poly(x)
Poly(9*x - pi**2, x, domain='EX')
>>> Eq(9*x,pi**2).as_poly(x,extension=True)
Traceback (most recent call last):
...
sympy.polys.polyerrors.NotAlgebraic: pi doesn't seem to be an algebraic element
```

it appears that the use of extension=True is the culprit. My guess is that linsolve doesn't use that (so if that option is really needed, there are equations that `solve` can handle that perhaps `linsolve` cannot).

So the temporary workaround is to replace number symbols with symbols before solving the equation.

**Comment by oscarbenjamin** [comment]
All examples seem to work now:
```julia
In [1]: solve([Eq(9*x, pi**2)],[x])                                                                                                            
Out[1]: 
⎧    2⎫
⎪   π ⎪
⎨x: ──⎬
⎪   9 ⎪
⎩     ⎭

In [2]: from sympy.abc import A,B,C 
   ...: from sympy import pi, Eq, solve 
   ...: solve([Eq(A + B, 0), Eq(C, 0), Eq(9*A, pi**2)])                                                                                        
Out[2]: 
⎧    2       2       ⎫
⎪   π      -π        ⎪
⎨A: ──, B: ────, C: 0⎬
⎪   9       9        ⎪
⎩                    ⎭

In [3]: linsolve([Eq(A + B, 0), Eq(C, 0), Eq(9*A, pi**2)],[A,B,C])                                                                             
Out[3]: 
⎧⎛ 2    2    ⎞⎫
⎪⎜π   -π     ⎟⎪
⎨⎜──, ────, 0⎟⎬
⎪⎝9    9     ⎠⎪
⎩             ⎭
```
