### ISSUE TITLE
Existing code of  sympy/sympy/functions/combinatorial/factorials.py

### ISSUE THREAD

**Issue by SHIVAPRASAD96** [sympy/sympy#10932]
sympy/sympy/functions/combinatorial/factorials.py
 _small_swing = [
        1, 1, 1, 3, 3, 15, 5, 35, 35, 315, 63, 693, 231, 3003, 429, 6435, 6435, 109395,
        12155, 230945, 46189, 969969, 88179, 2028117, 676039, 16900975, 1300075,
        35102025, 5014575, 145422675, 9694845, 300540195, 300540195
    ]
can someone same why is _small_swing list confined to 300540195???

**Comment by oscarbenjamin** [comment]
I don't know. Is that just asked out of interest or does it seem it seem incorrect to you?
