### ISSUE TITLE
test_dice_bayes in test_finite_rv.py it too slow

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#10936]
It sometimes takes more than 10 minutes to run, which causes Travis to fail. 

We should figure out why it is slow and see if it can be sped up. It doesn't seem like it should be slow, but maybe the computation is harder than I'm imagining it is. 

If we can't figure it out, we should mark it as slow. But we should try to figure it out first before just marking it as slow.

**Comment by jksuom** [comment]
The conditional probability distribution is constructed in ``frv.conditional_space`` by collecting those elements of the total space that satisfy the given condition. The condition is coded as  ``domain = self.where(condition)`` which is of type ``ConditionalFiniteDomain``. Testing its elements is very slow. If it is replaced by a set, for example, the time spent will be reasonable.
```
--- a/sympy/stats/frv.py
+++ b/sympy/stats/frv.py
@@ -278,9 +278,10 @@ def probability(self, condition):
 
     def conditional_space(self, condition):
         domain = self.where(condition)
+        dom_set = set(sympify(list(domain)))
         prob = self.probability(condition)
         density = dict((key, val / prob)
-                for key, val in self._density.items() if key in domain)
+                for key, val in self._density.items() if key in dom_set)
         return FinitePSpace(domain, density)
 ```

**Comment by asmeurer** [comment]
Why is the element testing slow? Does it redo some difficult calculation each time? Is it resulting in something like `6**3**2` calculations because of the outer loop? 

Your patch looks fine for this issue, but what if `domain` is much larger? Is it possible for testing containment to be faster than computing the entire set?

**Comment by asmeurer** [comment]
I guess `self` is always a finite probability space, so maybe not.

**Comment by jksuom** [comment]
The test ``key in domain`` consists of two parts in ``ConditionalFiniteDomain.__contains__``:
1. ``key in domain.fulldomain`` (Is ``key`` in the total space?)
2. ``domain._test(key)`` (Does it satisfy the condition?)

It is the first part that is really time consuming for a ``ProductDomain``:
```
    def __contains__(self, other):
        # Split event into each subdomain
        for domain in self.domains:
            # Collect the parts of this event which associate to this domain
            elem = frozenset([item for item in other
                              if sympify(domain.symbols.contains(item[0]))
                              is S.true])
            # Test this sub-event
            if elem not in domain:
                return False
        # All subevents passed
        return True
```
In this case it is automatically satisfied by all keys in ``self._density`` as ``domain`` is derived from ``self``. Hence this test is superfluous, and it is enough to take the latter test alone.
```
--- a/sympy/stats/frv.py
+++ b/sympy/stats/frv.py
@@ -280,7 +280,7 @@ def conditional_space(self, condition):
         domain = self.where(condition)
         prob = self.probability(condition)
         density = dict((key, val / prob)
-                for key, val in self._density.items() if key in domain)
+                for key, val in self._density.items() if domain._test(key))
         return FinitePSpace(domain, density)
```

**Comment by asmeurer** [comment]
+1. The test only takes a few seconds with that fix.
