### ISSUE TITLE
RandomSymbol with unknown probability space

### ISSUE THREAD

**Issue by Upabjojr** [sympy/sympy#10969]
_RandomSymbol_ as defined in _sympy.stats.rv_ associates a symbol name with a probability space.

One may be willing to operate on random symbols with unknown probability spaces, so maybe we could make the probability space parameter optional?

So transform:

``` python
    def __new__(cls, pspace, symbol):
```

to 

``` python
    def __new__(cls, symbol, pspace=None):
```

and check all occurrences.

**Comment by Smit-create** [comment]
@czgdp1807 @oscarbenjamin  The issue has been fixed on the current master. I think it can be closed.

**Comment by Smit-create** [comment]
The required changes are present in the master. Can this be closed @Upabjojr @czgdp1807 ?
https://github.com/sympy/sympy/blob/969cf54cf19e830306a84c00864b03f7b66bf8e0/sympy/stats/rv.py#L225-L252
https://github.com/sympy/sympy/blob/969cf54cf19e830306a84c00864b03f7b66bf8e0/sympy/stats/rv.py#L293-L301
https://github.com/sympy/sympy/blob/969cf54cf19e830306a84c00864b03f7b66bf8e0/sympy/stats/rv.py#L313-L320
