### ISSUE TITLE
maximum recursion depth exceeded on subfactorial(1000)

### ISSUE THREAD

**Issue by rd13123013** [sympy/sympy#10962]

**Comment by rd13123013** [comment]
I think this can be resolved by two ways.
1. subfactorial uses Memoization, we can calculate subfactorial(1000) if we start from subfactorial(100) and then keep increasing the argument by some constant till we reach 1000 . for example if we calculate subfactorial(200) then subfactorial(300) going till subfactorial(1000) by increasing by 100 at each step we can avoid error.
function can be modified to choose some constant ( like 100 in above example ) to iterate till target value in case argument is a large number.

2. use

**Comment by postvakje** [comment]
A third possibility is to move the `factorial(n)` in method 2 inside the sum and get:
`subfactorial(n) = Sum((-1)**(n-x)*ff(n,x), (x,0,n))`
or as you suggested not use `Sum` and compute `ff(n,x)` iteratively inside the function definition itself.

**Comment by asmeurer** [comment]
The docstring says it is defined by

```
          ,
         |  1                             for n = 0
    !n = {  0                             for n = 1
         |  (n - 1)*(!(n - 1) + !(n - 2)) for n > 1
```

This seems to be equivalent. 

```
def _eval(self, n):
    if n == 0:
        return 1
    if n == 1:
        return 0
    a, b = 1, 0
    for i in range(n-1):
        a, b = b, (i+1)*(a + b)
    return b
```

(this is very similar to the fibonacci sequence, so maybe there are even more efficient ways to compute it)

By the way, it's worth noting that the current implementation doesn't even use memoization, it uses caching (meaning if the cache is turned off, the runtime is exponential).

**Comment by rd13123013** [comment]
recurrence  reduces to 
`` !n = n*( !(n-1) ) + (-1)**n``
which is close to factorial function. Since matrix exponentiation can not be used here, hence linear time complexity is best we can get.

**Comment by sachin-4099** [comment]
As @asmeurer said:
By the way, it's worth noting that the current implementation doesn't even use memoization, it uses caching (meaning if the cache is turned off, the runtime is exponential).

Due to this fact, if we directly call **subfactorial(1500)** -->**Maximum Recursion Depth is reached**.
So I think the inbuilt implementation should be such that this should not happen. 

What are your thoughts @oscarbenjamin @asmeurer ?

**Comment by sachin-4099** [comment]
I am planning to implement more or less a similar implementation to that of @asmeurer.
It is a sort of a memoized solution as well, just using two variables (similar to fibonacci).
It is even not taking much time to calculate **subfactorial(10000).** 
So the problem of Maximum Recursion depth is getting resolved this way.
