### ISSUE TITLE
Indexed random variables

### ISSUE THREAD

**Issue by Upabjojr** [sympy/sympy#10968]
There is currently no way to represent indexed random variables.

One idea: add a parameter to _IndexedBase_ to represent the base class.

`IndexedBase("A")` would be equal to `IndexedBase("A", base_class=Symbol)`

while

`IndexedBase("A", base_class=RandomSymbol)` could represent an indexed base for random variables.

It would operate in a manner similar to C++ templates, with some magic such as _getattr_ to allow access to methods proper of random symbol.

Otherwise, create a new class, say `IndexedRandomSymbolBase` inheriting both `RandomSymbol` and `IndexedBase`.

**Comment by jksuom** [comment]
A parameter in ``IndexedBase`` could be a workable idea, but it would probably mean that the ``tensor`` module would have to import and deal with classes of the ``stats`` module. So maybe the creation of a new class ``IndexedRandomBase`` in ``stats`` would be preferable. It would have to override ``__getitem__`` and probably also ``__ new__``.

**Comment by Smit-create** [comment]
We have RandomIndexedSymbol currently in the master.
https://github.com/sympy/sympy/blob/969cf54cf19e830306a84c00864b03f7b66bf8e0/sympy/stats/rv.py#L293-L311

Can this be closed @Upabjojr @czgdp1807? Or does it require any more changes?
