### ISSUE TITLE
[tensor module] incorrect evaluation of TensMul.data 

### ISSUE THREAD

**Issue by vasdommes** [sympy/sympy#10972]
The code below gives a simple example when `TensMul.data` is evaluated incorrectly.
We compose TensMul expression from tensor `F` and vector `u`:
`mul_1 = F(mu, alpha) * u(-alpha) * F(nu, beta) * u(-beta)`,
and `mul_1.data` returns `[[0, 0], [0, 1]]`, as it should.

But if we change order of arguments and write
`mul_2 = F(mu, alpha) * F(nu, beta) * u(-alpha) * u(-beta)`, expecting the same result,
then `mul_2.data` returns `[[0, 0], [0, 0]]`!

Code:
```python
from sympy.tensor.tensor import *

Lorentz = TensorIndexType('Lorentz', metric=False, dummy_fmt='i', dim=2)
Lorentz.data = [-1, 1]

mu, nu, alpha, beta = tensor_indices('\\mu, \\nu, \\alpha, \\beta', Lorentz)

Vec = TensorType([Lorentz], tensorsymmetry([1]))
A2 = TensorType([Lorentz] * 2, tensorsymmetry([2]))

u = Vec('u')
u.data = [1, 0]

F = A2('F')
F.data = [[0, 1],
          [-1, 0]]

mul_1 = F(mu, alpha) * u(-alpha) * F(nu, beta) * u(-beta)
print(mul_1.data)
# mul_1.data - correct:
# [[0 0]
#  [0 1]]

# Same as mul_1, but in another order
mul_2 = F(mu, alpha) * F(nu, beta) * u(-alpha) * u(-beta)
print(mul_2.data)
# mul_2.data - ERROR:
# [[0 0]
#  [0 0]]
```

In the first case `_TensorDataLazyEvaluator.data_product_tensors.data_mul` method works only with 1- and 2-dimensional `data` arrays, whereas in the second case this method at some step builds 4-dimensional `data` array (arising from `F(mu, alpha) * F(nu, beta)`) and then contracts it with 1-dimensional arrays (`u.data`).
Probably this causes the problem?

P.S. sympy version 1.0

**Comment by vasdommes** [comment]
Also if we take sum of `mul_1` and `mul_1`, its `data` evaluates to `[[0, 0], [0, 0]]`:
```python
print((mul_1 + mul_1).data)
# [[0 0]
#  [0 0]]
```

This is because `TensMul.canon_bp()` is called inside `TensAdd` constructor (and canonical form of `mul_1` coincides with `mul_2`):
```python
print(mul_1.canon_bp())
# F(\mu, i_0)*F(\nu, i_1)*u(-i_0)*u(-i_1)
print(mul_1.canon_bp().data)
# [[0 0]
#  [0 0]]
```

**Comment by vasdommes** [comment]
@Upabjojr could your please take a look at this issue? Would it be hard to fix it?

**Comment by Upabjojr** [comment]
Using the newly introduced _sympy.tensor.array_ I get another result:

```python
In [4]: from sympy.tensor.tensor import *

In [22]: ua = Array([1,0])

In [23]: Fa = Array([[0, 1], [-1, 0]])

In [24]: tensorproduct(Fa, ua, Fa, ua)
Out[24]: [[[[[[0, 0], [0, 0]], [[0, 0], [0, 0]]], [[[0, 0], [0, 0]], [[0, 0], [0, 0]]]], [[[[0, 0], [1, 0]], [[-1, 0], [0, 0]]], [[[0, 0], [0, 0]], [[0, 0], [0, 0]]]]], [[[[[0, 0], [-1, 0]], [[1, 0], [0, 0]]], [[[0, 0], [0, 0]], [[0, 0], [0, 0]]]], [[[[0, 0], [0, 0]], [[0, 0], [0, 0]]], [[[0, 0], [0, 0]], [[0, 0], [0, 0]]]]]]

In [25]: tensorcontraction(_, (1, 2), (4, 5))
Out[25]: [[0, 0], [0, 2]]

In [26]: tensorproduct(Fa, Fa, ua, ua)
Out[26]: [[[[[[0, 0], [0, 0]], [[0, 0], [0, 0]]], [[[0, 0], [0, 0]], [[0, 0], [0, 0]]]], [[[[0, 0], [0, 0]], [[1, 0], [0, 0]]], [[[-1, 0], [0, 0]], [[0, 0], [0, 0]]]]], [[[[[0, 0], [0, 0]], [[-1, 0], [0, 0]]], [[[1, 0], [0, 0]], [[0, 0], [0, 0]]]], [[[[0, 0], [0, 0]], [[0, 0], [0, 0]]], [[[0, 0], [0, 0]], [[0, 0], [0, 0]]]]]]

In [27]: tensorcontraction(_, (1, 4), (3, 5))
Out[27]: [[0, 0], [0, 2]]
```

@vasdommes do you want to try to fix it? If you know how to debug Python code and understand how `_TensorDataLazyEvaluator` works, it won't be too hard.

**Comment by Upabjojr** [comment]
Sorry, didn't notice the metric. Anyway, I would also try to use the new array module, removing the external dependency (_numpy_).

**Comment by vasdommes** [comment]
@Upabjojr
> Using the newly introduced _sympy.tensor.array_ I get another result:

Either your result `[[0, 0], [0, 2]]` is obviously incorrect, or I am missing something important.

### Check №1:
```python
FuFu = tensorproduct(Fa, ua, Fa, ua)
FuFu_4 = tensorcontraction(FuFu, (1, 2))
tensorcontraction(FuFu_4, (2,3))
# [[0, 0], [0, 1]]
```

### Check №2:
We can rewrite our tensor expression as

![codecogseqn 1](https://cloud.githubusercontent.com/assets/8809142/14388173/9b3aef36-fdb5-11e5-900c-37e0dc86e2d5.gif)
where

![codecogseqn 2](https://cloud.githubusercontent.com/assets/8809142/14388175/a07b049a-fdb5-11e5-85e6-3cd4b9249627.gif)

Let's check it:
```python
Ea = tensorcontraction(tensorproduct(Fa, ua), (1, 2))
# [0, -1]

tensorproduct(Ea, Ea)
# [[0, 0], [0, 1]]
```
(this can also be checked manually)

**Comment by Upabjojr** [comment]
> Either your result [[0, 0], [0, 2]] is obviously incorrect, or I am missing something important.

There's a bug in _sympy.tensor.array_, I have just realized it.

**Comment by Upabjojr** [comment]
Here is the fix:

https://github.com/sympy/sympy/pull/10981

**Comment by vasdommes** [comment]
@Upabjojr it was a really quick fix=)

> @vasdommes do you want to try to fix it? If you know how to debug Python code and understand how `_TensorDataLazyEvaluator` works, it won't be too hard.

Although I have never looked at `_TensorDataLazyEvaluator` code before, I hope that I found the root of the problem. I'll try to fix it.

>  Anyway, I would also try to use the new array module, removing the external dependency (_numpy_).

Do you mean that in the future `Tensor.data` should be stored in `Array` instead of `numpy.ndarray`?

**Comment by Upabjojr** [comment]
> Although I have never looked at _TensorDataLazyEvaluator code before, I hope that I found the root of the problem. I'll try to fix it.

Perfect.

> Do you mean that in the future Tensor.data should be stored in Array instead of numpy.ndarray?

Yes, it would remove all the problems associated with a dependency on an external library. Furthermore, _numpy_ isn't really intended to represent symbolic arrays.

**Comment by vasdommes** [comment]
> Yes, it would remove all the problems associated with a dependency on an external library. Furthermore, numpy isn't really intended to represent symbolic arrays.

Yes, it is a good idea. By the way, is there an issue for this improvement? I didn't found one.

**Comment by Upabjojr** [comment]
> Yes, it is a good idea. By the way, is there an issue for this improvement? I didn't found one.

There isn't. There are still unsupported features in SymPy arrays, like _numpy.swapaxes_ that is currently used to check the array compatibility with the tensor symmetry.

Another idea is to create arrays with symmetry info so that symmetric components are stored only once (e.g. a symmetric matrix of size _N_ needs only _N (N + 1)/2_ components to be stored, the others being symmetric).

**Comment by vasdommes** [comment]
@Upabjojr an issue with TODO-list would be helpful if someone else (e.g. me=)) would like to contribute.

**Comment by Upabjojr** [comment]
The arrays are a recent introduction, I felt more like testing them a bit before replacing them with the existing ones.

@vasdommes do you feel like contributing to the tensor module?

**Comment by Upabjojr** [comment]
Also, bug reporting is really appreciated.

**Comment by vasdommes** [comment]
@Upabjojr I don't have enough free time to contribute actively and regularly, but I feel like making some contributions from time to time.

By the way, I found another bug with `data` evaluation: #11020
