### ISSUE TITLE
solvers.py contains BOM character

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#10974]
See https://stackoverflow.com/questions/7297888/ufeff-character-showing-up-in-files-how-to-remove-them for more information. The first character of solvers.py is U+FEFF. As far as I can tell it's impossible to tell this from GitHub, but if you `git blame sympy/solvers/solvers.py`, or use a hex editor (or even `less`), you can see it. The BOM was added by 56713720. 

We should find whatever other files have these and remove them. If a file has non-ASCII characters, it should start with `# -*- coding: utf-8 -*-`.

**Comment by Nitin216** [comment]
@asmeurer I think it is only in ```solvers.py```. So should i add it manually.
