### ISSUE TITLE
Remove u() function from compatibility

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#10985]
The pull request https://github.com/sympy/sympy/pull/10778 missed some uses of the `u()` function in the printing module. The function should be removed from the compatibility file completely, and all instance of `u("string")` should be replaced with `u"string"`.

**Comment by Nitin216** [comment]
@asmeurer I am able to remove all the instance of ```u("string")``` with ```u"string"```. But after this when i test ```test_pretty.py``` i am getting AssertionError on PieceWise, Meijerg.

**Comment by Nitin216** [comment]
@asmeurer Could you tell me what to do. After removing the ```u()``` function`in ```compatability.py```. What to do of the imports including ```u```?

**Comment by robfauli** [comment]
I've started working on this, it's been a month so presumably that is fine.

**Comment by kritkaran94** [comment]
@asmeurer I have removed the u() function from the file named compatibility.py and the corresponding imports too. However, this is the error I got after doing so :
 


![screen shot 2016-06-10 at 12 47 08 pm](https://cloud.githubusercontent.com/assets/10063868/15956975/9aa0a464-2f09-11e6-817d-6ec9b36d9d9f.png)

**Comment by asmeurer** [comment]
You'll need to replace it with `u'string'` in the places where it is used.

**Comment by kritkaran94** [comment]
After removing the function, I ensured that u() is not imported. Also,
later all instances of u(" ") which were present in
printing/pretty/pretty.py too are removed still there are similar issues.
What error could it be ?




*Krit Karan Singh Bhardwaj*
*IIIT Sri City *
*+91 7032306986 *
*kritkaran.b13@iiits.in <kritkaran.b13@iiits.in>*
http://iamkrit.in/

**Comment by kritkaran94** [comment]
@asmeurer Please review this PR.

**Comment by kritkaran94** [comment]
@asmeurer I worked upon your comment and submitted this PR. Please review it.

**Comment by debugger22** [comment]
@asmeurer Can we user `unicode_literals` across the whole codebase and not use `u'string'` anywhere? It shouldn't create any issue except at few places in crypto where byte strings are required.

**Comment by bjodah** [comment]
@debugger22 that would create massive head aches for people using Python 2.7, see Aaron's comment [here](https://github.com/sympy/sympy/pull/9692#issuecomment-126162173).

**Comment by debugger22** [comment]
That's some great stuff. Thanks!

**Comment by kritkaran94** [comment]
@asmeurer Could you please have a look at the code and hint at want more changes may be required in this PR

**Comment by asmeurer** [comment]
@kritkaran94 can you link to the pull request?

**Comment by kritkaran94** [comment]
@asmeurer It's #11256 (There are issue's with the name of the commit's) I would correct that after your feedback on the changes.

**Comment by kritkaran94** [comment]
@asmeurer I am stuck at this error. Could you please guide me.
[https://travis-ci.org/kritkaran94/sympy/jobs/140248731](url). 
I tested this locally [https://github.com/kritkaran94/sympy/pull/3/files](url)

**Comment by kritkaran94** [comment]
@asmeurer any suggestions where I am making a mistake. [[Travis Error](https://travis-ci.org/kritkaran94/sympy/jobs/140248731). 
I tested this locally [here](https://github.com/kritkaran94/sympy/pull/3/files])]

**Comment by asmeurer** [comment]
You need to create your pull request against sympy/sympy. The one you have now is made against your own fork, meaning that if you merge it, it will only update your fork, not sympy/sympy.

**Comment by jksuom** [comment]
Closed because of #11338
