### ISSUE TITLE
vertical bar at output end

### ISSUE THREAD

**Issue by florianGithub** [sympy/sympy#10986]
![sympy vertical bar at output end](https://cloud.githubusercontent.com/assets/14261779/14397290/db6f3586-fddc-11e5-8fd4-6223ed3356c3.PNG)

How can I remove the ugly vertical bar at the output end?

**Comment by moorepants** [comment]
I think this is a mathjax issue because I think I've only seen it in one browser. Can you report your browser name and try i tin other browsers?

**Comment by Nitin216** [comment]
Hey, i am also getting this when i use ```init_printing()```.I am currently using Chrome.In Microsoft Edge,and Mozilla Firefox this vertical bar is not showing. This error is only in Chrome.

**Comment by moorepants** [comment]
I would see if MathJax from other websites renders this way. If so you should report this issue to MathJax. Or if it is a Jupyter/Chrome issue, maybe you need to open the issue there.

**Comment by florianGithub** [comment]
Thanks for the answers! Nitin216 is right Firefox and IE work, Chrome only shows the bar.
I found this: https://github.com/mathjax/MathJax/issues/1300
I right clicked on the output -> Math Settings -> MathML and now the math display is really bad:
![bad math rendering](https://cloud.githubusercontent.com/assets/14261779/14511003/e2a058fc-01d4-11e6-8553-d40002917314.PNG)
Unfortunately, if I right click now, I dont get the Math Settings option anymore.
Does anyone know how to fix this?

**Comment by moorepants** [comment]
@florianGithub You need to submit the issue to MathJax or Jupyter Notebook. SymPy just uses those libraries and we don't necessarily know how to fix it.

**Comment by oscarbenjamin** [comment]
This doesn't seem to be an issue any more as far as I can tell.
