### ISSUE TITLE
Use pretty_symbology in sympy/printing/pretty/pretty.py

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#10983]
There are several places in pretty.py where a unicode string is used directly like `"\N{RIGHTWARDS ARROW WITH STROKE}"`. These should be refactored to use the `pretty_symbology` submodule.

**Comment by nathanmusoke** [comment]
I'm interested in doing this.

What is the correct way to do it?

It looks like sympy/printing/pretty/pretty_symbology.py will need some new definitions added too.

**Comment by asmeurer** [comment]
Yes, a lot of things will need to be added to pretty_symbology. Just add them in a reasonably high-level way, matching the format of what's there.

**Comment by SaiHarsh** [comment]
Is it still open? I would like to work on this.

**Comment by asmeurer** [comment]
`git grep --color '\\N'` shows lots of instances in pretty.py.

**Comment by Riyuzakii** [comment]
@asmeurer i have done changes to the files on my pc regarding this issue but when i try to push using:
git push -f origin
it says:
```
remote: Permission to sympy/sympy.git denied to Riyuzakii.
fatal: unable to access 'https://github.com/sympy/sympy/': The requested URL returned error: 403
```
can you please help me out?

**Comment by asmeurer** [comment]
@Riyuzakii you need to push to your fork. See our developer workflow for more information https://github.com/sympy/sympy/wiki/Development-workflow.

**Comment by ShikharJ** [comment]
@asmeurer @Riyuzakii I already have an open PR regarding this issue. Please refer #12291.
