### ISSUE TITLE
as_finite_diff does not support partial derivatives

### ISSUE THREAD

**Issue by bjodah** [sympy/sympy#11007]
partial derivatives is not well supported by `as_finite_diff`:
```
>>> f = Function('f')(x, y)
>>> d2fdxdy = f.diff(x).diff(y)
>>> as_finite_diff(d2fdxdy, wrt=x)
-f(x - 1/2, y) + f(x + 1/2, y)
```
which is incorrect, the correct output would be:
```
  ∂                   ∂                
- ──(f(x - 1/2, y)) + ──(f(x + 1/2, y))
  ∂y                  ∂y
```

related:
https://groups.google.com/forum/#!searchin/sympy/Mathias$20Louboutin/sympy/MIlkgmts8xw/jQ_-EUrUAAAJ
https://groups.google.com/forum/#!searchin/sympy/Mathias$20Louboutin/sympy/mzr_ET2Pu2E/0gK6jxcUDQAJ

a nice addition would be to allow the syntax `wrt=(x, y)`

**Comment by souravsingh** [comment]
I would like to work on this. How do I start?

**Comment by bjodah** [comment]
@souravsingh you can start by writing a (failing) test of what should be supported and add it to [test_finite_diff.py](https://github.com/sympy/sympy/blob/master/sympy/calculus/tests/test_finite_diff.py), then modify [finite_diff.py](https://github.com/sympy/sympy/blob/master/sympy/calculus/finite_diff.py) to allow those tests to pass (using `$ ./bin/test sympy/calculus/tests/test_finite_diff.py`). Then open a PR to have your changes it reviewed.

**Comment by mloubout** [comment]
Another non-supported mode (and easier to fix I think) is to able to give the product of two function as an input : 

>>> f = Function('f')(x)
>>> g = Function('g')(x)
>>> dfgdx = (f*g).diff(x)
>>> as_finite_diff(dfgdx)

which would give 

-f(x - 1/2)*g(x - 1/2) + f(x + 1/2)*g(x - 1/2,)

**Comment by parsoyaarihant** [comment]
@souravsingh , is the issue fixed?

**Comment by mloubout** [comment]
@souravsingh any updates?

**Comment by parsoyaarihant** [comment]
I have submitted PR #11177 for this issue.

**Comment by smichr** [comment]
> Another non-supported mode

Let's get that opened as a new issue if it is not addressed by #11177

**Comment by parsoyaarihant** [comment]
We could pass an optional argument to the function for non support mode. Will that be fine?

**Comment by mloubout** [comment]
I think it needs a flag 'expand' or 'noexpand' saying if you want to develop the product or treat it as a single variable, from all mathematical expression for derivatives should follow (product, quotient, f(g(x)),...)
