### ISSUE TITLE
Pretty printing expression, get too many minus signs (`- - - ...` instead of `- ...`)

### ISSUE THREAD

**Issue by vperic** [sympy/sympy#11009]
I am generating some expressions programatically and often, I get an expression of the form `- - - <whatever>`, where I'd obviously prefer a simpler `- whatever`. Looking at the srepr, I see there are more `Mul(Integer(-1), <whatever>)` objects than I'd expects. Calling simplify on this expression doesn't help --- is there another simplification function I should be calling?

```
                          3                           2                       
- - -0.00116343365098086⋅x  - - -0.00605972798002368⋅x  + 0.0673537506748162⋅x + 5.24680299415976
```
Calling just `print(e)`, I get the expected results:

```
-0.00116343365098086*x**3 - 0.00605972798002368*x**2 + 0.0673537506748162*x + 5.24680299415976
```

Here's the `srepr` of the expression:
```
"Add(Mul(Integer(-1), Float('0.001163433650980864', prec=15), Pow(Symbol('x'), Integer(3))), Mul(Integer(-1), Float('0.0060597279800236794', prec=15), Pow(Symbol('x'), Integer(2))), Mul(Float('0.067353750674816151', prec=15), Symbol('x')), Float('5.2468029941597596', prec=15))"
```

There seem to be way too many `Mul(Integer(-1), ...` objects.

**Comment by asmeurer** [comment]
I get this in SymPy 0.7.6 but not in SymPy 1.0 (or master). I think the bug has been fixed.

**Comment by vperic** [comment]
Ah, you're right. Thanks, and sorry for the bother.
