### ISSUE TITLE
problems with numerical evaluation

### ISSUE THREAD

**Issue by mhlr** [sympy/sympy#11004]
I working with a simple statistical mechanics example,
using the Stirling approximation of the factorial in combinatorial functions:

```
from __future__ import division
from sympy.abc import *
from sympy import *
from sympy.physics.units import avogadro_number as N


# Stirling's approximation for factorial
def f(n):
    return sqrt(2*pi*n)*(n/E)**n

# number of k-equipartitions of n particles
def m(n, k):
    return  f(n)/ (f(n/k)**k)

# probability of a k-partition being an equipartition
def p(n,k):
    return m(n, k)/(k**n)

q = (p(n, 2)/p(n, 3)).simplify()

z = log(p(n, k)/p(n, k+1)).expand(force=True)
```

Working tests:

```
>>> print q.n(4)
0.9648*n**0.5
>>> print q.n(4,subs={n: N})
7.487e+11
>>> print z   
k*n*log(n)/(k + 1) - k*n*log(k + 1)/(k + 1) - k*n/(k + 1) + k*log(k)/2 - k*log(k + 1)/2 - n*log(n) + n*log(k + 1) + n + n*log(n)/(k + 1) - n*log(k + 1)/(k + 1) - n/(k + 1) + log(n)/2 - log(k + 1)/2 + log(2)/2 + log(pi)/2
>>> print z.simplify()
k*log(k)/2 - k*log(k + 1)/2 + log(n)/2 - log(k + 1)/2 + log(2)/2 + log(pi)/2
>>> print z.simplify().n(4)
0.5*k*log(k) - 0.5*k*log(k + 1) + 0.5*log(n) - 0.5*log(k + 1) + 0.9189
>>> print z.n(4).simplify()
0.5*k*log(k) - 0.5*k*log(k + 1) + 0.5*log(n) - 0.5*log(k + 1) + 0.9189
>>> print z.subs(n,N).simplify()
k*log(k)/2 - k*log(k + 1)/2 - log(k + 1)/2 + log(2)/2 + log(pi)/2 + log(602214179000000000000000)/2
>>> print z.subs(n,N).simplify().n(4)
0.5*k*log(k) - 0.5*k*log(k + 1) - 0.5*log(k + 1) + 28.3
```

The problem cases:
- Substitution not working `n` is not replaced by `N` - note that `print q.n(4,subs={n: N})` above works

```
>>> print z.n(4, subs={n: N})
k*n*log(n)/(k + 1.0) - k*n*log(k + 1)/(k + 1.0) - k*n/(k + 1.0) + 0.5*k*log(k) - 0.5*k*log(k + 1) - n*log(n) + n*log(k + 1) + n + n*log(n)/(k + 1.0) - n*log(k + 1)/(k + 1.0) - n/(k + 1.0) + 0.5*log(n) - 0.5*log(k + 1) + 0.9189

>>> print z.simplify().n(4, subs={n: N}) 
0.5*k*log(k) - 0.5*k*log(k + 1) + 0.5*log(n) - 0.5*log(k + 1) + 0.9189
```
- This looses the `log(n)` term completely and performs some other invalid transformations

```
>>> print z.subs(n,N).n(4).simplify()
0.5*k*(k*log(k) - k*log(k + 1) + log(k))/(k + 1)
```

**Comment by smichr** [comment]
Nothing stands out to me as being wrong:

```
>>> z.subs(n,2).n(4).simplify()
0.5*k*log(k) - 0.5*k*log(k + 1) - 0.5*log(k + 1) + 1.266
>>> z.simplify().subs(n,2).n(4)
0.5*k*log(k) - 0.5*k*log(k + 1) - 0.5*log(k + 1) + 1.266
>>> z.simplify().n(4, subs={n:2})
0.5*k*log(k) - 0.5*k*log(k + 1) + 0.5*log(n) - 0.5*log(k + 1) + 0.9189
```

The only thing different in case 3 is that the n has not been replaced (because doing so doesn't change the expression to a number that can be evaluated) so it isn't combined in with the numerical term -- thus 0.9189 instead of 1.266.

Is there something that I am missing?

**Comment by mhlr** [comment]
In my last example
```
>>> print z.subs(n,N).n(4).simplify()
0.5*k*(k*log(k) - k*log(k + 1) + log(k))/(k + 1)
```
There is no numerical term that comes from  `n`. It does not depend on `n` at all. Where did the `n` go?
Also when you divide through by `(k + 1)` coefficient of `log(k + 1)` is `0.5*k*k/(k + 1)` which
not equivalent to that in the other evaluations.

In the `z.simplify().n(4, subs={n:2})` case I do not understand the explanation:

> the n has not been replaced (because doing so doesn't change the expression to a number that can be evaluated)

What is the difference between `X.n(4, subs={n:2})` and `X.subs(n,2).n(4)`?
I thought they should be equvalent.

**Comment by oscarbenjamin** [comment]
I think the problem is just that evalf doesn't work very well with expressions involving symbols unless all of them are fully substituted for actual numbers.

**Comment by smichr** [comment]
> What is the difference between `X.n(4, subs={n:2})` and `X.subs(n,2).n(4)`?



> There is no numerical term that comes from `N`. It does not depend on `N` at all. Where did the `N` go?

It is now there in master:
```
>>> simplify(z.subs(n,N).n(4))
0.5*k*log(k) - 0.5*k*log(k + 1) + 0.5*log(avogadro_number) - 0.5*log(k + 1) + 0.9189
```
This issue could probably be closed with a test (or confirmation that a test addressing the root issue has already been added by the commit that fixed this).

**Comment by hyadav2k** [comment]
I can't find avogadro_number defined in the physics module.

Tried adding test cases to `test_simplify.py`
```python
N=Symbol('N')
def f(n):
    return sqrt(2*pi*n)*(n/E)**n
def m(n, k):
    return  f(n)/ (f(n/k)**k)
def p(n,k):
    return m(n, k)/(k**n)
q = (p(n, 2)/p(n, 3)).simplify()
z = log(p(n, k)/p(n, k+1)).expand(force=True)
assert simplify(z.subs(n,N).n(4)) == 0.5*k*log(k) - 0.5*k*log(k + 1) + 0.5*log(N) - 0.5*log(k + 1) + 0.9189
```
Still, it gives assertion error, but checking for simplify(z.subs(n,N).n(4)), it returns the same expression as above.
It returns `0.5*k*log(k) - 0.5*k*log(k + 1) + 0.5*log(N) - 0.5*log(k + 1) + 0.9189`
What could be the possible reason @smichr @oscarbenjamin @mhlr?

**Comment by oscarbenjamin** [comment]
You need to create floats with the correct precision:
```python
In [23]: r = simplify(z.subs(n,N).n(4))

In [24]: half = Float('0.5', 4)

In [25]: r == half*k*log(k) - half*k*log(k + 1) + half*log(N) - half*log(k + 1) + Float(0.9189224, 4)
Out[25]: True
```

**Comment by hyadav2k** [comment]
Thank you for your assistance.
Kindly review the PR.

**Comment by yasphy** [comment]
> I can't find avogadro_number defined in the physics module.
> 
> Tried adding test cases to `test_simplify.py`
> 
> ```python
> N=Symbol('N')
> def f(n):
>     return sqrt(2*pi*n)*(n/E)**n
> def m(n, k):
>     return  f(n)/ (f(n/k)**k)
> def p(n,k):
>     return m(n, k)/(k**n)
> q = (p(n, 2)/p(n, 3)).simplify()
> z = log(p(n, k)/p(n, k+1)).expand(force=True)
> assert simplify(z.subs(n,N).n(4)) == 0.5*k*log(k) - 0.5*k*log(k + 1) + 0.5*log(N) - 0.5*log(k + 1) + 0.9189
> ```
> 
> Still, it gives assertion error, but checking for simplify(z.subs(n,N).n(4)), it returns the same expression as above. It returns `0.5*k*log(k) - 0.5*k*log(k + 1) + 0.5*log(N) - 0.5*log(k + 1) + 0.9189` What could be the possible reason @smichr @oscarbenjamin @mhlr?

You can find avogadro number using following code
import sympy.physics.units as u
l=u.avogadro_constant
l1=u.convert_to(l,u.mol)
print(l1)

**Comment by yasphy** [comment]
![image](https://user-images.githubusercontent.com/78342519/137574735-2573aa42-5790-4661-a8d8-bc86ad1c15cb.png)
