### ISSUE TITLE
diop: power_representation

### ISSUE THREAD

**Issue by smichr** [sympy/sympy#11000]
```
>>> list(power_representation(1, 1, 1)) 
[()] 
```
This should be [(1,)]

addressed by #10997

**Comment by Nitin216** [comment]
@smichr It is calling ```perfect_power(n)```. But what to return in ```perfect_power``` as it returns (b,e) where 
```n = b**e``` as n is 1. We have multiple options of b if we put e=0 and only 1 if we use both b=1 and a=1.

**Comment by smichr** [comment]
This is a special case for the diop routine; no change would (need to) be made to `perfect_power`. The docstring says that the default is to return non-zero containing solutions. (So getting a null answer for (6, 2, 4) is right since without 0 there are no 4 squares that sum to 6.)

**Comment by Nitin216** [comment]
thank you @smichr so is this now closed.
