### ISSUE TITLE
diop: sum of squares needs to try more options to satisfy conditions

### ISSUE THREAD

**Issue by smichr** [sympy/sympy#11016]
```python
>>> eq=Add(*[i**2 for i in symbols('x:6',nonnegative=1)])
>>> eq.subs(zip(eq.free_symbols,(10, 3, 0, 1, 1, 1)))
112
>>>
>>> diophantine(eq - 112)
set([])
```

Currently, only a single solution is returned to diophantine, (-10, -3, 0, 1, 1, 1, 1), but that one doesn't satisfy the condition that the values be nonnegative, so the empty set is returned rather than the solution without negatives.

**Comment by Shekharrajak** [comment]
From the current branch, I got : 

```
In [1]: from sympy.solvers.diophantine import *

In [2]: eq=Add(*[i**2 for i in symbols('x:6',nonnegative=1)])

In [3]: eq.subs(zip(eq.free_symbols,(10, 3, 0, 1, 1, 1)))
Out[3]: 112

In [4]: diophantine(eq - 112)
Out[4]: set([(8, 4, 4, 4, 0, 0)])

In [5]: diop_solve(eq - 112)
Out[5]: set([(8, 4, 4, 4, 0, 0)])
```

**Comment by smichr** [comment]
OK, for demonstration purposes, declare all symbols as negative. I think you will get an empty set.

**Comment by Shekharrajak** [comment]
If `eq=Add(*[i**2 for i in symbols('x:6',negative=true)])` then it returns empty set.
So if there is no assumptions then it should return both negative and positive solutions.

**Comment by smichr** [comment]
Currently only 1 solution is returned, but in #10997 I am returning all solutions (except for permutations of order and sign)

```
set([
        (1, 1, 1, 3, 6, -8), (2, 3, 3, 4, 5, -7), 
        (2, 2, 4, 4, 6, -6), (1, 3, 4, 5, 5, -6), 
        (1, 2, 3, 3, 5, -8), (1, 1, 2, 3, 4, -9), 
        (1, 1, 3, 4, 6, -7)])
```

By "except for sign" I don't mean that the solution will contain no negatives. If a symbol is required to be negative then it is made so as seen in the set given.

**Comment by smichr** [comment]
The non-trivial solutions containing 0 are also returned now.
