### ISSUE TITLE
solveset(oo*x - 1) -> {0}; should be {}

### ISSUE THREAD

**Issue by smichr** [sympy/sympy#11015]
Substitution of 0 into the expression `oo*x - 1` gives `nan - 1` -> `nan`, so 0 should not be reported as a solution from `solveset` (and `nan` should not be reported as the solution from solve).

``` python
>>> solve(1-oo*x)
[nan]
>>> solveset(1-oo*x)
{0}
```

**Comment by Shekharrajak** [comment]
I think these should be EmptySet 
```
In [ ]: solveset(oo*x,x)
Out[ ]: {0}

In [ ]: solve(oo*x,x)
Out[ ]: [0]
```
Right ?

**Comment by AkshaySiramdas** [comment]
`solve(oo*x,x)` already is giving emptyset.

**Comment by smichr** [comment]
I agree.

**Comment by AkshaySiramdas** [comment]
I think `nan` could be returned as a solution coz there is no solution to the given equation. Another thing to try is to return a no-solution error.

**Comment by latot** [comment]
Hi, only as a note, if we include the limit concept the solution should be EmptySet excluding x==0, if x==0 should be nan.

**Comment by latot** [comment]
little question here in sympy are you taking oo including it self or not?

if its included the solution of ```solveset(oo*x, x)``` should be nan.
else, ```solveset(oo*x, x)``` should be 0.

**Comment by ArifAhmed1995** [comment]
@AkshaySiramdas `nan` isn't a number.It cannot be treated as a solution which substituted back into the equation yields zero.

**Comment by latot** [comment]
mm, i think nan is the solution not for a numerical expression, is because that solution can't be calculated, at least while we don't have the expression of oo, or maybe other expression with this meaning?.
