### ISSUE TITLE
diop: power_representation(4**5, 3, 1) -> (4,)

### ISSUE THREAD

**Issue by smichr** [sympy/sympy#11021]
```python
>>> from sympy.solvers.diophantine import power_representation as f
>>> list(f(4**5,3,1))
[(4,)]
```

The above answer is not right since `4**3 != 4**5`.

Addressed by #10997

**Comment by lePerdu** [comment]
Since `perfect[0] ** perfect[1] == n`:
```python
perfect = perfect_power(n)
if perfect and perfect[1] % p == 0:
    yield (perfect[0] ** (perfect[1] // p),)
else:
    yield tuple()
```

**Comment by smichr** [comment]
I'm not sure if you are agreeing and pointing out where the problem is or disagreeing. The `power_representation` is supposed to give you the base that must be raised to the prescribed power. In the example I gave, that power was 3 and `4**5` cannot be represented as `k**3` where `k` is an integer, so no solution should be given. As mentioned, however, this has been addressed in the cited PR.

**Comment by yougaindra** [comment]
I tried it and I got [(2,)], here's the [link](http://live.sympy.org/?evaluate=from%20sympy.solvers.diophantine%20import%20power_representation%20as%20f%0A%23--%0Alist(f(4**5%2C3%2C1))%0A%23--%0A)
BTW, what does this function supposed to do, I tried to lookup in documentation but couldn't find it?

**Comment by lePerdu** [comment]
I was agreeing about the problem and proposing a solution.
```python
if perfect_power(n):
     yield (perfect_power(n)[0],)
```
is problematic because `perfect_power()` returns `(4, 5)` (`(2, 10)` for me). The base-exponent pair `(a, b)` from `perfect_power()` can be used if `b` is divisible by `p`: `a**(b / p)` is a solution to the equation because `(a**(b / p))**p == a**b == n`.

**Comment by lePerdu** [comment]
I see now that the idea above was covered (with a better implementation) by the commit [diop: general_sum_of_even_powers; sum_of_squares; sum_of_powers](https://github.com/sympy/sympy/pull/10997/commits/8605f310734fd1db18e4f4ab2d7c0b3d387bf7d6) just after my comment, so I guess I was a bit late.
