### ISSUE TITLE
Better docs for custom printing

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#11025]
We need better Sphinx docs for how to customize printing for custom classes, and also how to subclass the printers to customize printing for existing classes.

**Comment by rahulroxx** [comment]
I would like to work on this !

**Comment by rahulroxx** [comment]
I would like to work on this !

**Comment by asmeurer** [comment]
Custom classes means user subclasses of `Expr` or `Function`. A good place to start would be to read through the code and try to understand how it works. You can also search the code for `_sympystr` to see some examples of this in action.

**Comment by rohitrango** [comment]
Hello, I'm a newcomer here and I would like to work on this. 
Can you please provide me with a starting point ?
Thanks :smile:

**Comment by asmeurer** [comment]
Start with understanding how the printing system works (probably by reading the code). There are also some examples of subclassing printers in some StackOverflow answers if you search.

**Comment by rohitrango** [comment]
Well, there are many printer functions and I do not have time to understand and write docs for all of them. Could you possibly redirect me to some other issue?

**Comment by asmeurer** [comment]
Look for other issues with the "easy to fix" tag.

**Comment by rasto2211** [comment]
Isn't this issue already solved? Isn't this part of the documentation the answer:
http://docs.sympy.org/dev/modules/printing.html#sympy.printing.printer.Printer ??

**Comment by asmeurer** [comment]
I'd like it if it were a little less hidden (like at the top of that page). Also there isn't an example for adding the printmethod to a custom class.

**Comment by rasto2211** [comment]
Ok, I'll work on this issue.
