### ISSUE TITLE
Matrix does not support division by 1x1 matrix

### ISSUE THREAD

**Issue by jschall** [sympy/sympy#11032]
1x1 matrix should be interpreted as a scalar in this situation. Matlab does this.

**Comment by AStorus** [comment]
Similarly should multiplication of an NxN by a 1x1 be treated as NxN * a scalar?

**Comment by moorepants** [comment]
Some previous related discussion: https://github.com/sympy/sympy/issues/9190

**Comment by AStorus** [comment]
@moorepants thanks for that

@jschall something as simple as this?

```python
    def __div__(self, other):
        #if dividing by 1x1 matrix, treat as division by scalar
        if other.shape == (1,1):
            return self*(S.One / other[0])
        return self*(S.One / other)
```

**Comment by jschall** [comment]
Closing in favor of #9190.
