### ISSUE TITLE
[tensor module] Free index order problem in tensor expressions

### ISSUE THREAD

**Issue by vasdommes** [sympy/sympy#11039]
I am opening this issue for discussion of the problem mentioned by @Upabjojr in comments for issue #11020:

> This problem is related to a bigger one: how do you define the free index order of a _TensAdd_ object? Unlike for _TensMul_, it's undefined. A quick idea would be to force to use the lexicographical order of free indices.
> 
> In the future, we expect this problem to be extended to TensMul, as one may wish to represent unexpanded expressions, like, for example: `A(i) * ( B(j,k) + C(k, j) )`. This is a _TensMul_ containing a _TensAdd_. Currently such expressions get expanded to a TensAdd.

In current implementation the free indices in _Tensor_, _TensMul_ and _TensAdd_  are stored (in `free_args` property) in lexicographical order (see also PR #11037 for `TensAdd.data` bugfix).
This can lead to rather surprising bevaviour:

``` python
from sympy.tensor.tensor import *
Lorentz = TensorIndexType('Lorentz', metric=False, dummy_fmt='i', dim=2)
alpha, beta, gamma, delta = tensor_indices('\\alpha, \\beta, \\gamma, \\delta', Lorentz)
A2 = TensorType([Lorentz]*2, tensorsymmetry([2]))

# asymmetric tensors
F = A2('F')
G = A2('G')

F2 = F(gamma, delta)
F2(alpha, beta)
# F(\beta, \alpha)
F2(gamma, delta)
# F(\delta, \gamma)
F2(gamma, delta) + F(gamma, delta)
#0
```

Same problem for _TensMul_:

``` python
FG = F(alpha, beta) * G(gamma, delta)
FG(alpha, beta, gamma, delta)
# F(\alpha, \beta)*G(\delta, \gamma)
FG(alpha, beta, gamma, delta) + F(alpha, beta)*G(gamma,delta)
#0
```

...and for _TensAdd_:

``` python
add_1 = F(gamma, delta) + G(gamma, delta)
add_1(gamma, delta)
# F(\delta, \gamma) + G(\delta, \gamma)
```

Seems pretty confusing, huh?

**Comment by vasdommes** [comment]
My opinion:

For _Tensor_ and _TensMul_ it is a bug of `__call__()` method.

For _TensAdd_ it is either
(a) bug, if the free index order is the same for all arguments,
or
(b) undefined behaviour, if the free index order in arguments is different and one cannot obtain the correct order unambiguously.

I think, in the case (b) we should raise an exception: as said in The Zen of Python,
> In the face of ambiguity, refuse the temptation to guess.

**Comment by Upabjojr** [comment]
If you don't like index reordering, do not declare the tensor symmetry.

_TensAdd_ and other places perform a call to `canon_bp( )`, which performs the Butler-Portugal canonicalization. This means, given the symmetry structure of the tensor expression, it reorders the indices in the most lexicographic order allowed by the tensor symmetry, eventually adding a minus sign to the expression in case of antisymmetry.

I believe that some degree of canonicalization is a desirable feature, for example the current system can perform some automatic simplifications, such as:

```python
>>> A(i, j)*B(-i, -j)
0
```
if _A_ is symmetric and _B_ is anti-symmetric.

Concerning potential bugs in `__call__`, it might be. I would first try to finish a huge rewrite (that I have in progress) of the tensor module before dealing with complicated bugs.

**Comment by vasdommes** [comment]
> If you don't like index reordering, do not declare the tensor symmetry.

Well, this is not an answer=) Tensor symmetry is very useful, but the implicit (and unavoidable) lexicographical reordering is not the thing that users always want. As demonstrated above, it naturally leads to problems with `__call__`.

Sometimes user just wants to declare tensor expression `F(mu, nu, lambda)` (you can find such index order in many papers or textbooks), and he doesn't want to get, e.g., `-F(lambda, mu, nu)` instead of it.
Furthermore (see initial post), lexicographical order for `(gamma, delta)` is `(delta, gamma)`. And if I write `F(gamma, delta)` (e.g asymmetric), of course I don't expect it to be implicitly converted to `-F(delta, gamma)`!

If the user wants to get lexicographical (or any other) order, let him call the corresponding method explicitly.
Something like:
```python
>>> F(mu, nu, alpha).reorder_indices() # lexicographical by default
- F(alpha, mu, nu)
>>> F(mu, nu, alpha).reorder_indices(mu, alpha, nu)
- F(mu, alpha, nu)
>>> F(mu, nu, alpha).reorder_indices(mu, beta, nu)
ValueError: free index mismatch
```

>I believe that some degree of canonicalization is a desirable feature, for example the current system can perform some automatic simplifications

I agree with that. Obviously, we have to use canonicalization, e.g. for collecting terms in _TensAdd_ or for other simplifications. But it is a matter of internal implementation.
As for interface (`__call__`, printing etc.), free indices must be exposed to user in the order that he defined. I cannot see another way to avoid subtle bugs such as described in this issue.

> I would first try to finish a huge rewrite (that I have in progress) of the tensor module before dealing with complicated bugs.

Do you mean PR #9521? How long would it take to finish it?

Probably fixing this issue wouldn't require huge changes, so I hope I could fix it by myself (after you finish your huge rewrite, if you say so). But these changes will be breaking, so I would like to discuss them thoroughly before opening a PR.

**Comment by Upabjojr** [comment]
I think that eventually fixed evaluation of tensor expressions should be done away with.

The method `.canon_bp( )` should not be automatically called. Another possibility is the parameter `evaluate=False`, as used in other SymPy objects.

I would also like to make `TensAdd` and `TensMul` inherit `Add` and `Mul`, respectively. A `TensPow` expression could also be added in the future.

> Do you mean PR #9521? How long would it take to finish it?

It still needs a rewrite of the matrix indices, I want to make them easier to implement and to use, I don't like the current implementation. The rest of that PR should already be working. I will try to finish it, but it's still going to take some time.

**Comment by Upabjojr** [comment]
```
>>> F(mu, nu, alpha).reorder_indices() 
```

We have `.canon_bp()`, the canonical order is called Butler-Portugal canonical order. Lexicographical order is wrong, because generally you may get a different expression (if symmetry structure does not allow such permutation).

**Comment by Kishore96in** [comment]
Can this issue be closed, now that `TensAdd.__call__` and `TensMul.__call__` are deprecated?
