### ISSUE TITLE
MatrixBase does not inherit from Basic

### ISSUE THREAD

**Issue by jschall** [sympy/sympy#11042]
This seems like it probably causes https://github.com/sympy/sympy/issues/11041 and https://github.com/sympy/sympy/issues/11034

**Comment by isuruf** [comment]
I think that's by design. Basic is immutable but not all types of MatrixBase are immutable. Only immutable matrix types like ImmutableDenseMatrix inherit from Basic.

**Comment by asmeurer** [comment]
Yes, this is intentional. Use ImmutableMatrix is you need a matrix that subclasses from Basic.
