### ISSUE TITLE
implement faster partition counting function

### ISSUE THREAD

**Issue by smichr** [sympy/sympy#11058]
The `nT` function could benefit from the work of [Ken Locey](https://github.com/klocey/partitions/blob/master/README.md) who published under the MIT license a couple of nice functions: 
- [x] `NrParts` (Find the number of partition for a given total q and number of parts n) and 
- [x] `P` (A function to return the number of partitions of q with k or less parts). This is perhaps not necessary since the partitions of `n` identical items with `parts <= k` is just the partitions of `n + k` with parts `k`.

See Also #6662

**Comment by jtnydv25** [comment]
Hi! I improved the `npartitions` function some days back.
I think I can work on it.
Does a naive implementation exist in sympy presently?

**Comment by smichr** [comment]
Sorry to not have left a reference:

```
Help on function nT in module sympy.functions.combinatorial.numbers:

nT(n, k=None)
    Return the number of ``k``-sized partitions of ``n`` items.

    Possible values for ``n``::
        integer - ``n`` identical items
        sequence - converted to a multiset internally
        multiset - {element: multiplicity}

    Note: the convention for ``nT`` is different than that of ``nC`` and
    ``nP`` in that
    here an integer indicates ``n`` *identical* items instead of a set of
    length ``n``; this is in keeping with the ``partitions`` function which
    treats its integer-``n`` input like a list of ``n`` 1s. One can use
    ``range(n)`` for ``n`` to indicate ``n`` distinct items.

    If ``k`` is None then the total number of ways to partition the elements
    represented in ``n`` will be returned.
```

**Comment by Nitin216** [comment]
is this closed ?
