### ISSUE TITLE
subs does not like equations? 

### ISSUE THREAD

**Issue by delooper** [sympy/sympy#11056]
Greetings, 

If I have an expression like exp1 = L^3 * W and perform a substitution, 

exp1.subs(L, 24)

sympy 1.0 works fine.  But if I put exp1 into an equation:

eq = sp.Eq(D, exp1)

substitute fails:

eq.subs(L, 24)

returns the error message:

TypeError: _subs() missing 1 required positional argument: 'new'

This would appear to be a bug.

**Comment by asmeurer** [comment]
I can't reproduce this. Can you give a full code snippet that gives the error?

**Comment by delooper** [comment]
``import sympy as sp
 L, I = sp.symbols("L I")
 blah = sp.Eq(D, L)
 blah.subs(L, I)

That does it.  The error message is quite large:

``TypeError                                 Traceback (most recent call last)
/usr/local/lib/python3.5/dist-packages/sympy/core/cache.py in wrapper(*args, **kwargs)
     92                 try:
---> 93                     retval = cfunc(*args, **kwargs)
     94                 except TypeError:

TypeError: _subs() missing 1 required positional argument: 'new'

During handling of the above exception, another exception occurred:

TypeError                                 Traceback (most recent call last)
/usr/local/lib/python3.5/dist-packages/sympy/core/cache.py in wrapper(*args, **kwargs)
     92                 try:
---> 93                     retval = cfunc(*args, **kwargs)
     94                 except TypeError:

/usr/local/lib/python3.5/dist-packages/sympy/core/basic.py in _subs(self, old, new, **hints)
   1015         if rv is None:
-> 1016             rv = fallback(self, old, new)
   1017         return rv

/usr/local/lib/python3.5/dist-packages/sympy/core/basic.py in fallback(self, old, new)
    987                     continue
--> 988                 arg = arg._subs(old, new, **hints)
    989                 if not _aresame(arg, args[i]):

/usr/local/lib/python3.5/dist-packages/sympy/core/cache.py in wrapper(*args, **kwargs)
     94                 except TypeError:
---> 95                     retval = func(*args, **kwargs)
     96                 return retval

TypeError: _subs() missing 1 required positional argument: 'new'

During handling of the above exception, another exception occurred:

TypeError                                 Traceback (most recent call last)
/usr/local/lib/python3.5/dist-packages/sympy/core/cache.py in wrapper(*args, **kwargs)
     92                 try:
---> 93                     retval = cfunc(*args, **kwargs)
     94                 except TypeError:

TypeError: _subs() missing 1 required positional argument: 'new'

During handling of the above exception, another exception occurred:

TypeError                                 Traceback (most recent call last)
<ipython-input-56-e8c4e79ad93f> in <module>()
      2 L, I = sp.symbols("L I")
      3 blah = sp.Eq(D, L)
----> 4 blah.subs(L, I)

/usr/local/lib/python3.5/dist-packages/sympy/core/basic.py in subs(self, *args, **kwargs)
    900             rv = self
    901             for old, new in sequence:
--> 902                 rv = rv._subs(old, new, **kwargs)
    903                 if not isinstance(rv, Basic):
    904                     break

/usr/local/lib/python3.5/dist-packages/sympy/core/cache.py in wrapper(*args, **kwargs)
     93                     retval = cfunc(*args, **kwargs)
     94                 except TypeError:
---> 95                     retval = func(*args, **kwargs)
     96                 return retval
     97 

/usr/local/lib/python3.5/dist-packages/sympy/core/basic.py in _subs(self, old, new, **hints)
   1014         rv = self._eval_subs(old, new)
   1015         if rv is None:
-> 1016             rv = fallback(self, old, new)
   1017         return rv
   1018 

/usr/local/lib/python3.5/dist-packages/sympy/core/basic.py in fallback(self, old, new)
    986                 if not hasattr(arg, '_eval_subs'):
    987                     continue
--> 988                 arg = arg._subs(old, new, **hints)
    989                 if not _aresame(arg, args[i]):
    990                     hit = True

/usr/local/lib/python3.5/dist-packages/sympy/core/cache.py in wrapper(*args, **kwargs)
     93                     retval = cfunc(*args, **kwargs)
     94                 except TypeError:
---> 95                     retval = func(*args, **kwargs)
     96                 return retval
     97 

TypeError: _subs() missing 1 required positional argument: 'new'

**Comment by smichr** [comment]
What is D for your example? When I do the following, I don't have a problem:

```python
>>> import sympy as sp
>>> D, L, I = sp.symbols("D L I")
>>> blah = sp.Eq(D, L)
>>> blah.subs(L, I)
Eq(D, I) <-- a new Eq is produced with L replaced with I
>>> blah
Eq(D, L)  <-- blah is unchanged
```

**Comment by delooper** [comment]
Apologies, I am using D = sp.Function("D").  Somehow I forgot to paste that. 

If I use D = sp.Symbol("D") there is no problem. 

So it appears to be a problem with having an equation between a function and some symbolic expression of symbols.

**Comment by asmeurer** [comment]
You can't have unapplied functions in expressions (see https://github.com/sympy/sympy/issues/4787). If you want to use a function that isn't called with any arguments, you have to use `Lambda`.

**Comment by delooper** [comment]
Thanks.
