### ISSUE TITLE
abs() returns complex numbers

### ISSUE THREAD

**Issue by LeopoldKellers** [sympy/sympy#11061]
```
Python 3.5.1+ (default, Apr 17 2016, 16:14:06) 
[GCC 5.3.1 20160409] on linux

>>> import sympy as sp
>>> sp.init_printing()
>>> f = sp.sqrt(sp.I + 1) * sp.exp(1 + sp.I)
>>> f
  _______  1 + ⅈ
╲╱ 1 + ⅈ ⋅ℯ     
>>> abs(f)
       ___________________________________________________________________
      ╱                         __________                       ________ 
     ╱    4 ___     _______    ╱   √2   1    4 ___   _______    ╱ √2   1  
ℯ⋅  ╱   - ╲╱ 2 ⋅ⅈ⋅╲╱ 1 + ⅈ ⋅  ╱  - ── + ─  + ╲╱ 2 ⋅╲╱ 1 + ⅈ ⋅  ╱  ── + ─  
  ╲╱                        ╲╱     4    2                    ╲╱   4    2  
>>> if abs(f).evalf() >= 0:
...     pass # Should obviously always be the case
... 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/tmp/sympy/sympy/core/expr.py", line 244, in __ge__
    raise TypeError("Invalid comparison of complex %s" % me)
TypeError: Invalid comparison of complex 3.2326000909861 - 5.53934772120312e-27*I
```

Ouch! abs() returning complex numbers must be a bug, right?

I ran setup.py test on my machine and nothing failed unexepectedly - isn't there anything in there to catch such a fundamental flaw?
I am willing to add a test case for the future at least! Would core/tests/test_complex.py be the right place for that?

What I am less sure about: is it really neccessary for a simple thing like abs to result in this complicated expression above? When I lambdify a somewhat more complicated expression than this (fed into abs()), is it going to be optimized or will it actually compute all those square roots?

**Comment by isuruf** [comment]
This is due to a rounding-off error when `evalf` is called.

```IPython
In [13]: abs(f).evalf(100)
Out[13]: 3.232600090986102706209508321654787390944599823965062664272302559067532731567792074378632601295513725 - 2.376175950248462332503639927857795980968359690916513174214231974745053167752733840977505964269903204e-112*I

In [14]: abs(f).evalf(chop=True)
Out[14]: 3.23260009098610
```
See the option `chop` for `evalf`

**Comment by isuruf** [comment]
You can create a Abs object if you don't want it to evaluate.
```IPython
In [19]: Abs(f, evaluate=False)
Out[19]: Abs(sqrt(1 + I)*exp(1 + I))
```

**Comment by LeopoldKellers** [comment]
Hello,

Thanks a lot!

So this is actually expected behaviour?
I looked at the documentation again and it does indeed not tell anything about the type that abs/Abs evaluate to. So seems like I made an incorrect assumption. I apologize. Maybe this could be mentioned in the docs then, to prevent others from falling for the same thing? For me it is pretty counterintuitive at least. I guess I was mislead by 
```
>>> Abs.is_real
True
```

So as matters stand now, the above example is no longer a good, minimal representative of my problem: I need to evaluate Abs(f) where f is some complex, complicated expression depending on real variables and feed the result into numeric integrators that only accept real input. Let's say
```
>>> x = symbols('x', real=True)
>>> f = Abs(sqrt(I + x) * exp(-x**2+I))
>>> l = lambdify(x, f, modules="numpy")
>>> l(1)
(0.437484848904-1.71722915513e-17j)
```
.
Unfortunately, lambdify does not accept chop as suggested above. Is there any better way get a real value from a complex expression entirely from sympy itself rather than
```
>>> ll = lambda x: numpy.real(l(x))
>>> ll(1)
0.43748484890430417
```
or explicit casting?
The docstring of re() suggests using as_real_imag(), but that does not solve my problem:
```
lll = lambdify(x, f.as_real_imag(), modules="numpy")
>>> lll(1)
((0.437484848904-1.71722915513e-17j), 0)
```
Btw.: before upgrading from version 0.7.6 I did not run into this problem.

**Comment by smichr** [comment]
Can you use `re`?

```python
>>> re(abs(f).n())
3.23260009098610
```

**Comment by LeopoldKellers** [comment]
Indeed, this does the job:
```
>>> x = symbols('x', real=True)
>>> f = sqrt(I + x) * exp(-x**2+I)
>>> freal = re(Abs(f).n())  # won't work without the Abs.n() inside re()!
>>> l = lambdify(x, freal, modules="numpy")
>>> l(1)
0.437484848904
```
And so far also seems to work for my more complicated functions!

I did not attempt this myself because for `re` the docstring suggests I shouldn't use it at all:
```
Help on class re in module sympy.functions.elementary.complexes:

class re(sympy.core.function.Function)
 |  Returns real part of expression. This function performs only
 |  elementary analysis and so it will fail to decompose properly
 |  more complicated expressions. If completely simplified result
 |  is needed then use Basic.as_real_imag() or perform complex
 |  expansion on instance of this function.

...
```
but going ahead directly and using `as_real_imag` instead of `re` did not help either (c.f. the last example in my previous post)

Well then, thanks a lot! The crucial part that I was not aware of is the requirement to call `Abs(...).evalf()`/`Abs(...).n()` BEFORE applying `re()` or `as_real_imag()` to it, otherwise the expression won't be changed at all!

**Comment by isuruf** [comment]
Let `p=abs(f)`
Issue here is that, the symbolic algorithms can deduce that the expression `p` is real.
Therefore `re` would return return `p` and `as_real_imag()` returns `(p, 0)`.

Lambdify is a numeric algorithm and it can't deduce that the expression is real. Therefore you need to apply `re` or `as_real_imag` after a numeric algorithm like `lambdify` or `.evalf()` both of which are numeric algorithms.

**Comment by LeopoldKellers** [comment]
Alright, now I do understand how it works, thanks again for clarifying this!

Just one last thing I'd be interested to know before I dig through my code and fix things: this somehow used to work for me without that extra `re`/`evalf` handiwork before upgrading to 1.0:
```
>>> import sympy as sp
>>> x = sp.symbols('x', real=True)
>>> f = sp.Abs(sp.sqrt(sp.I + x) * sp.exp(-x**2+sp.I))
>>> l = sp.lambdify(x, f, modules="numpy")
>>> l(1)
0.43748484890430422
>>> sp.__version__
'0.7.6'
```
(the same code as in my second post), so I am wondering why my code broke. I could not find anything matching my problem in the breaking changes section of the release notes before opening the issue. The new features section however advertises:
> New assumption system is now able to read the assumptions set over Symbol object. For e.g.:
> 
> In [7]: x = Symbol('x', positive=True)
> 
> In [8]: ask(Q.positive(x))
> Out[8]: True

Could that be related?

**Comment by asmeurer** [comment]
Small complex "tails" are unavoidable in general because how floating point numbers work, but this strikes me as something that shouldn't happen. Why does abs return a complex number? Shouldn't abs, when presented with a complex number, always return `sqrt(re(x)**2 + im(x)**2)` (or a floating point stable equivalent)?

As to `lambdify`, at that point, you're using numpy's algorithms. I wonder how it is translated, though, because I get

```
In [15]: import numpy as np

In [16]: np.abs(np.sqrt(1j+1)*np.exp(-1**2+1j))
Out[16]: 0.437484848904
```

**Comment by isuruf** [comment]
Change from 0.7.6 is that `abs(sqrt(I+x))` is automatically expanded into an ugly form.

You seem to be talking about two problems. One with `abs(sqrt(I+x))` and another with `abs(sqrt(I+1))`
With the latter, I get the same complex valued answer as it is automatically evaluated. With the former there is a difference, because sympy-1.0 expands it to an ugly form.

@asmeurer, reason for the expanded form having `I` in it is that `Abs` doesn't do that, it uses, `x*conjugate(x)`, but conjugate of `sqrt(1+I)` is given as `2**(1/4)*sqrt(sqrt(2)/4 + 1/2) - 2**(1/4)*I*sqrt(-sqrt(2)/4 + 1/2)` and when multiplied is not cancelled out, giving this answer `sqrt(-2**(1/4)*I*sqrt(1 + I)*sqrt(-sqrt(2)/4 + 1/2) + 2**(1/4)*sqrt(1 + I)*sqrt(sqrt(2)/4 + 1/2))`, for `abs(sqrt(1+I))`.

As to lambdify issue, you are using numpy assuming sympy doesn't simplify, but it does (it's not making it simple though).

@LeopoldKellers, best option would be to do `Abs(sqrt(I+x), evaluate=False)` instead of `abs(sqrt(I+x))` to prevent sympy's automatic evaluation.

**Comment by asmeurer** [comment]
I bisected the autoexpand change to

commit 5c3824f7f81aaa11a6abf1fac98092616091e8d4
Author: Chris Smith <smichr@gmail.com>
Date:   Mon Dec 28 20:52:21 2015 -0600

    modify Relational._eval_simplify add Add._eval_is_ funcs

**Comment by LeopoldKellers** [comment]
Passing the `evaluate=False` option to `Abs` does unfortunately not handle expressions well, where derivatives of `Abs` are involved, e.g.
```
simplify(Abs(sqrt(I + x) * exp(-x**2+I), evaluate=False).diff(x,x)) 
```
is "an order of magnitude" more complicated (also wrt. the execution time of `simplify`) than the expression returned by
```
simplify(Abs(sqrt(I + x) * exp(-x**2+I)).diff(x,x))
```
Unfortunately, (and this is the reason why I am using SymPy instead of numpy directly) I also need to evaluate a few expressions of the form `f + f.diff(x) + ... + f.diff(x, x, ...)` where `f = Abs(some expression)`. This works by far better when the expansion does actually take place. That was the main reason why I upgraded to the new version. So I do appreciate the expansion of Abs now taking place in general (however, I can treat these cases manually with the `re(Abs(...).n())` method while using `evaluate=False` on the rest I think).
I should probably have written all this in the first post already, instead of using the `Abs(sqrt(1 + I)*exp(1 + I))` example. I am still comparatively new to sympy and had never seen `abs/Abs` return nonreal numbers. Just like asmeurer, I felt that this was something not to be expected or at least to be mentioned in the docstring like it is the case with `re` for nontrivial expressions. I should indeed have checked the behaviour of what I originaly considered a meaningful, minimal example in 0.7.6 as well. So yes, you are of course right about the two different kinds of problems discussed here, isuruf. That's my bad. 
Finally, I am dreaming of an ideal world where `Abs` does get expanded, like it is the case now, but SymPy still keeping track of the resulting expression in a way such that numeric evaluation algorithms will directly truncate the result to its real part (and similarly derivatives of `Abs(...)` with respect to a real variable). Due to my lack of knowledge about the internal workings, I have no idea whether that is achievable or even desired, though. Anyway, I will apply the suggestions you guys have made above to my code and be happy with it.

**Comment by isuruf** [comment]
You can also do something like
```
def abs2(x):
    return sqrt(expand(x*conjugate(x)))
```
or
```
def abs3(x):       
    t = conjugate(x)
    return sqrt(expand(t*conjugate(t)))
```
Note that these functions use `expand` and it can quickly become a bottleneck.
