### ISSUE TITLE
Heaviside undefined at zero

### ISSUE THREAD

**Issue by woodscn** [sympy/sympy#11060]
The behavior of the Heaviside step function was recently changed such that H(0) is no longer defined, where previously it evaluated to 1/2. (See #9907 #9909) The reasoning given for this change was that there was no particular reason to choose a value of 1/2 over other choices. 

Mathematically, this makes good sense. Pragmatically, it breaks code and makes it difficult to use Heaviside functions as building blocks for more complicated expressions. For instance, one might wish to define a rectangle function as a product of Heaviside functions, or use them to generate code for discontinuous expressions. In both of these cases, an undefined boundary is impossible to deal with.

I'd like to see some option to customize the behavior made available to the user. Leave the default value as-is, but give Heaviside an additional optional argument for the value at 0, e.g:

h1 = Heaviside(x, x0=S(1)/2)
h2 = Heaviside(x, x0=0)

**Comment by moorepants** [comment]
@zanzibar7 @jksuom

**Comment by zanzibar7** [comment]
We have an open issue related to this in the specific context of laplace transforms (issue #10840 addressed by pull request #10955).

I like the idea you are proposing, as an alternative.  I'm taking a quick look at a prototype implementation, and have snagged. `Heaviside` subclasses `Function` for it's machinery, so there is no constructor that can simply absorb the new key word argument. I'm looking into this further.

**Comment by zanzibar7** [comment]
I don't know how to implement this.  I don't have a good understanding yet of sympy's conventions with
objects and classes representing functions.  The classes `Piecewise` and `hyper` for hypergeometric functions provide examples of how to override `Function.__new__`, but unless the new default value for `Heaviside(0)` is made a class property, then it I don't see how it can get propagated into the standard `eval()` routine where I expect it to get used.  If we did make it a property of the class, then we would get messy global-state bugs down the road.

**Comment by jksuom** [comment]
Perhaps the value could be made a class attribute ``H0``, initially ``None``. It could be set by something like ``Heaviside.setH0(value)``. (Or maybe by ``setattr(Heaviside, 'H0', value)``).

**Comment by woodscn** [comment]
This would (I think) have the effect that changing its value in a script would propagate to every other instance of H in that script. For my specific purpose, that's better, but I wonder if it would violate the principle of least surprise.

**Comment by zanzibar7** [comment]
Looks like sympy's design doesn't allow keyword args to granularly refine the Function class.  But
we can pass in a second argument similar to a branch-cut specification and get similar results.  Here's how it might work.

```
>>> Heaviside(9)
1
>>> Heaviside(-9)
0
>>> Heaviside(0)
Heaviside(0)
>>> Heaviside(0, y)
y
```

**Comment by woodscn** [comment]
I don't think that would solve the problem. The real objective here is to allow something like the following:

`>>> expr = Heaviside(x, x0=y)` 
`>>> expr.subs({x: 0}) == y`
`True`

Something like `expr.set_zero(y)` would also work. The point is to change the default behavior of H, either for a specific instance or globally, and these changes need to propagate through sympy operations. Is there no way to parameterize functions in Sympy?

**Comment by zanzibar7** [comment]
The proposed fix above deals with your case naturally, with the exception that it just doesn't have the 
informative `x0 = ` keyword to remind us of the role of the second argument.

Changing the behavior globally is easy, though, as you point out, can cause suprise or confusion.  This approach only effects individual instances, and still gives you allot of flexibility.  Do you have other test cases where this pull request won't work?

**Comment by woodscn** [comment]
I'm sorry about that; I misunderstood you. I thought that you had to specify the zero-behavior at evaluation time. I checked out your PR, and I think it fixes my problem nicely.

**Comment by woodscn** [comment]
This can be closed as soon as #11065 is merged.

**Comment by cbm755** [comment]
Fixed by #11244, which is basically #11065 with another change.

**Comment by BrodaUa** [comment]
Hello.
[This merge](https://github.com/sympy/sympy/pull/11244) fixed some uncertainty with Heaviside(0) which brings headache to writing code. But, can you please provide a way of evaluating the value of expression comprised with Heaviside(0)? For instance, if I got this: 1.0*Heaviside(0) + 1.0 or even more complex expr as result of derivation. Dealing with term Heaviside(0) alone quite easy via eval(), but about my case?
Thanks.

**Comment by zanzibar7** [comment]
Something other than a standard substitutions and rewrite solutions?

```
>>> (2*Heaviside(0)+1).subs(Heaviside(0), 1)
>>> (1+Heaviside(x)).subs(Heaviside(x), Heaviside(x,1))
>>> (2*Heaviside(0)+1).rewrite(sign)
```

**Comment by BrodaUa** [comment]
@zanzibar7 Thank you. Eventually, the next  code worked for me too:
`(1+Heaviside(0)).subs({H0:1})`
