### ISSUE TITLE
solveset(x+sqrt(x**2-5)>0,x,S.Reals) gives wrong resullt

### ISSUE THREAD

**Issue by wxgeo** [sympy/sympy#11064]
In [4]: solveset(x+sqrt(x**2-5)>0,x,S.Reals)
Out[4]: ∅

Result should be [sqrt(5), ∞)

**Comment by smichr** [comment]
solveset needs the ability to find the domain of a function.

**Comment by wxgeo** [comment]
Indeed. This should be first step when solving an equation or inequation. (And this is particularly important for inequations).

**Comment by parsoyaarihant** [comment]
Solveset solves inequalities by finding the roots of the equation and checking where the inequality holds between the roots of the equation. 

In this problem, the roots of the equation cannot be found. Hence, `solveset(x+sqrt(x**2-5)>0,x,S.Reals)` gives `∅` as the solution.
