### ISSUE TITLE
Improvements to DiracDelta and Heaviside

### ISSUE THREAD

**Issue by moorepants** [sympy/sympy#11075]
@sampadsaha5 We can use this issue to track the desired work on these functions.

First thought: You should ensure that these properties work with our functions: https://en.wikipedia.org/wiki/Dirac_delta_function#Properties. Many of these could be turned into unit tests.

- [x] Improve documentation of fdiff and explain the relationship to _eval_derivative. Aaron's comment " fdiff is a convenience. it lets you write the derivative without concern for the chain rule. the superclass Function._eval_derivative handles the rest"
- [x] Implement rewriting DiracDelta and Heaviside as Piecewise.
- [x] Improve docstrings of the `DircaDelta` and `Heaviside` classes and methods.
- [x] Give contextual examples for `DiracDelta(x, k)`
- [x] Print the DiracDelta function as the lower case delta symbol in pretty print and latex.

**Comment by sampadsaha5** [comment]
@moorepants This is a great idea.  
I went through the link that you have posted :   
- **Scaling and symmetry**  would work perfectly if #10863 gets implemented properly.
- **Translation** is working fine.
```
In [5]: integrate(sin(x)*DiracDelta(x-t), (x, -oo, oo))
Out[5]: sin(t)
```
- If I can remove the merge conflict of #10863 I hope that **Composition with a function** would also work fine. 

I will let you know when I am done with #10863. After this I will focus on documentation part.

**Comment by moorepants** [comment]
Please ensure that there are unit tests for these properties.

**Comment by sampadsaha5** [comment]
OK @moorepants. I will make sure that there are tests written for each and every functionality that will be newly implemented.

**Comment by moorepants** [comment]
I also am suggesting that you should add tests that for existing untested functionality. For example, the two lines you show above, could be a test if it isn't already one.

**Comment by sampadsaha5** [comment]
Ok Sure. I will then check for existing untested functionalities also and I will add tests to them.

**Comment by sampadsaha5** [comment]
@moorepants Can you please explain me a bit about the last one in the checklist?

**Comment by moorepants** [comment]
I was wondering if it would be nice to enable pretty printers and latex printers that printed the DiracDelta class as:

```python
>>> DiracDelta(x)
δ(x)
```

**Comment by sampadsaha5** [comment]
Okay, I will try to figure out how to implement that.
Can you please tell me how to use this method:
```py
    def _latex_no_arg(printer):
        return r'\delta'
```

**Comment by sampadsaha5** [comment]
@moorepants @asmeurer @leosartaj 
Under `eval` class method under `DiracDelta` class why does the following case  is not implemented:
```py
if arg is S.Zero:
    return S.Infinity
```
This case is also an obvious value for Diracdelta.

**Comment by moorepants** [comment]
@sampadsaha5 Are all of these items taken care of? Can this be closed?

**Comment by sampadsaha5** [comment]
Yah sure.
