### ISSUE TITLE
Pretty printer inconsistent

### ISSUE THREAD

**Issue by trxrunner** [sympy/sympy#11070]
```
   pprint(sympify('5/7'))
   5/7
   pprint(sympify('5/7',evaluate=False))
   5
   –
   7
```
Are these supposed to be different?

**Comment by parsoyaarihant** [comment]
I referred this in the documentaiton and I feel that the output is as expected : [documentation for sympify](http://docs.sympy.org/dev/modules/core.html)

**Comment by kpsychas** [comment]
The problem is the first is identified as rational and the second as a division of two expressions. To avoid inconsistency we could always pretty print rationals the second way. Now this happens only if nominator and denominator have at least 2 digits.

**Comment by oscarbenjamin** [comment]
I think there is nothing to fix here
