### ISSUE TITLE
wrong result in limit calculation

### ISSUE THREAD

**Issue by burg1ar** [sympy/sympy#11073]
and this is my code:
```
from sympy import *
x=Symbol('x')
y=limit((x**3-sin(1/2*x**3))/(x**2*log(sqrt(1+x))),x,0)
print(y)
```
the I get the result:2,and actually the right answer is 1

**Comment by parsoyaarihant** [comment]
Hi @sheldonAi , I ran this code in my computer and I am getting output 1.00. Can you tell me the version of python and sympy you are using?

**Comment by sheldonAi** [comment]
Thank you @parsoyaarihant for your reply,I am using the latest Anaconda distribution.
python --version:Python 2.7.11 :: Anaconda 4.0.0 (64-bit)
sympy:version 1.0
and I may figure it out,I tried to add a line of code:
`from __future__ import division`
then I got the answer:1.00000000000000,it is the right result.
the problem may be the "/"(divide operator),the result of / is always an interger in python 2.7.
But I don't know how it works in fact,I didn't get this problem when I run:`limit(sin(x)/x,x,0)`,I would get the right answer anyhow.
by the way,my os is ubuntu 16.04

**Comment by parsoyaarihant** [comment]
@sheldonAi , I am not sure how evaluaiton of limit works too but in case of `limit(sin(x)/x,x,0)` after the expansion of `sin(x)` series is done the `x` cancels and we get a integer answer 1 directly by substitution. Hence you must be right regarding the  divide operator in python 2.7. I am using python 3.4 hence didnt face that problem when I ran the code.

**Comment by isuruf** [comment]
Problem is here, `sin(1/2*x**3)`. `1/2` would evaluated to `0` by python and therefore give a wrong answer.
Use `sin(S(1)/2*x**3)` or simply `sin(x**3/2)`.

See here for a detailed explanation, http://docs.sympy.org/latest/tutorial/gotchas.html#two-final-notes-and

**Comment by sheldonAi** [comment]
@isuruf yes,that is the problem,and the doc is exactly what I want,thank you for your help.

**Comment by oscarbenjamin** [comment]
This works fine on master (with Python 3):
```
In [23]: from sympy import * 
    ...: x=Symbol('x') 
    ...: y=limit((x**3-sin(1/2*x**3))/(x**2*log(sqrt(1+x))),x,0) 
    ...: print(y)                                                                                                                                             
1.00000000000000
```
Even better if I use rationals:
```
In [24]: from sympy import * 
    ...: x=Symbol('x') 
    ...: y=limit((x**3-sin(S(1)/2*x**3))/(x**2*log(sqrt(1+x))),x,0) 
    ...: print(y)                                                                                                                                             
1
```
I don't think there is anything to fix here. If you want this to work on Python 2 then my second example above should work fine.

**Comment by sachin-4099** [comment]
Closing in favour of: https://github.com/sympy/sympy/issues/11073#issuecomment-473605002
