### ISSUE TITLE
where possible, use python fractions for Rational

### ISSUE THREAD

**Issue by smichr** [sympy/sympy#11081]
Since we have dropped support for 2.5 we can use the [fractions module](https://docs.python.org/2/library/fractions.html?highlight=rational) for Rational internals. The `gcd` method could also replace `igcd`:

```python
>>> timeit('gcd(12,3)','from fractions import gcd')
0.5296611342553904
>>> timeit('gcd(12,3)','from sympy import igcd as gcd')
6.766568780548827
```

**Comment by isuruf** [comment]
`igcd` has a caching mechanism which is good, but it may take some fixed time for table lookup. It's essentially the same algorithm.

fractions module suffers from the same issue fixed in `https://github.com/sympy/sympy/pull/11019`

**Comment by isuruf** [comment]
caching of igcd was not working properly. Fixed this in #11089

**Comment by asmeurer** [comment]
Maybe we should merge with the polys, which uses gmpy types when they are available (which are even faster).

**Comment by isuruf** [comment]
I've tried using gmpy mpzs here https://github.com/isuruf/sympy/tree/gmpy. Didn't have time to check whether there are speed improvements though.

Using gmpy mpqs will take some more work though, because Rational class keeps the two separate ints.
