### ISSUE TITLE
Float(mpf) loses precision

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#11092]
```
In [33]: import mpmath

In [34]: mpmath.mp.dps = 50

In [35]: a = mpmath.mpf('1.0')/mpmath.mpf('3.0')

In [36]: a
Out[36]: mpf('0.33333333333333333333333333333333333333333333333333311')

In [37]: sympify(a)
Out[37]: 0.33333333333333333333333333333333333333333333333333

In [38]: Float(a)
Out[38]: 0.333333333333333

In [39]: Float(a)._mpf_
Out[39]: (0, 6004799503160661, -54, 53)

In [40]: a._mpf_
Out[40]: (0, 498859225542281529413524422900491270709224974669141, -170, 169)

```

`Float(a)` should give the same thing as `sympify(a)`.

**Comment by asmeurer** [comment]
Same with mpc (see https://stackoverflow.com/questions/37054917/solving-a-symbolic-sympy-with-mpmath-mpc-types).

**Comment by asmeurer** [comment]
Also `mpc` (see https://stackoverflow.com/questions/37054917/solving-a-symbolic-sympy-with-mpmath-mpc-types).

**Comment by smichr** [comment]
> Float(a) should give the same thing as sympify(a)

Is there a precision declaration in sympify's documentation? If not, I don't see why the two should return the same thing. Float *does* declare that it uses 15 digits (as I recall).

**Comment by asmeurer** [comment]
IMHO unless the precision argument is passed to Float it should infer the precision from the argument (ditto if you pass it a string).

**Comment by MayankJhamtani** [comment]
Should I try to implement a code to implement this, that is float inferring the precision from the argument. Or a precision of 15 for all arguments is alright?

**Comment by ArifAhmed1995** [comment]
@MayankJhamtani It would be better to extract the `dps` from the mpmath float , rather than assume it to be 15 which the current code in `core.numbers` does.

**Comment by czgdp1807** [comment]
The current master doesn't have this issue,
```python
Python 3.6.8 (default, Oct  7 2019, 12:59:55) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import mpmath
>>> mpmath.mp.dps = 50
>>> a = mpmath.mpf('1.0')/mpmath.mpf('3.0')
>>> a
mpf('0.33333333333333333333333333333333333333333333333333311')
>>> from sympy import *
>>> sympify(a)
0.33333333333333333333333333333333333333333333333333
>>> Float(a)
0.33333333333333333333333333333333333333333333333333
>>> Float(a)._mpf_
(0, 498859225542281529413524422900491270709224974669141, -170, 169)
>>> a._mpf_
(0, 498859225542281529413524422900491270709224974669141, -170, 169)
>>> Float(a)._mpf_ == a._mpf_
True
>>> sympify(a) == Float(a)
True
```
Therefore closing this issue. Please let me know by commenting below if this needs to re-opened.
