### ISSUE TITLE
 solve([x**2 + y**2 - 16, 4*x - y**2 + 6], x, y) gives an empty list

### ISSUE THREAD

**Issue by isuruf** [sympy/sympy#11106]
This doesn't seem to affect everybody. It's working fine on sympy live and @asmeurer checked that it gives correct output on SymPy 1.0 and git master.

Gives an empty list for 1.0 and master. Bisected the change to 068607e7555d1741b6a46a2a152dfd3a6bd87c04

@smichr

**Comment by smichr** [comment]
I don't understand under which conditions it gives the wrong result:  "correct output on SymPy 1.0 and git master" vs "[g]ives an empty list for 1.0 and master".

**Comment by isuruf** [comment]
This was probably due to a broken python install and it is now fixed.
