### ISSUE TITLE
solve() gives no result when check = True

### ISSUE THREAD

**Issue by parsoyaarihant** [sympy/sympy#11118]
I am trying to solve the equaiton `solve(sqrt(x) + 1/root(x, 3) - 1, check=True)` and no output is being returned by the program. 

`solve(sqrt(x) + 1/root(x, 3) - 1, check=False)` gives immediate result for the equaiton. Any way to make the program return RuntimeError for the equation `solve(sqrt(x) + 1/root(x, 3) - 1, check=True)` ?

**Comment by smichr** [comment]
Although it's slow, I get results with live.sympy.org; did something break with a new release or is it possible you are not waiting long enough (or is None returned)?

**Comment by parsoyaarihant** [comment]
Yeah I am not waiting for long enough when it is running in my local machine. But if the answer is correct then the test [test_slow_general_univariate()](https://github.com/parsoyaarihant/sympy/blob/solveset-bug-%2311064/sympy/solvers/tests/test_inequalities.py#L302) should work when `check = True`.
