### ISSUE TITLE
x > 0 doesn't evaluate for x = Symbol('x', positive=False)

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#11122]
```
In [16]: x = Symbol('x', positive=False)

In [17]: x > 0
Out[17]: x > 0
```

The reason is that `Expr.__gt__` doesn't evaluate based on assumptions unless both sides are known to be real, because otherwise it doesn't want to subtract them (in case the nonreals all cancel). This is fine, but I think the case where one side is 0 should be sufficient for it to evaluate. Or, more generally, it should  be fine if just one side is real (subtracting a real can't make a nonreal cancel). 

CC @smichr

**Comment by parsoyaarihant** [comment]
I am working on this issue. Any tips are welcome :) .

**Comment by prateekg** [comment]
I think this should be closed.
Ref #11276 
@asmeurer
