### ISSUE TITLE
use underlying sieve to compute composite(n)

### ISSUE THREAD

**Issue by smichr** [sympy/sympy#11125]
Although the current implementation is mathematically sound, performance may favor the following:

```python
def composite(nth):
    from sympy.ntheory.generate import sieve as s
    n = as_int(nth)
    if n < 1:
        raise ValueError("nth must be a positive integer; composite(1) == 4")
    composite_arr = [4, 6, 8, 9, 10, 12, 14, 15, 16, 18]
    if n <= 10:
        return composite_arr[n - 1]
    i = s.search(20)[0] # index of prime < nth composite
    j = s.search(int(n*(log(n) + log(log(n)))))[1]  # index of prime > nth composite
    while j - i > 1:
      k = (j + i)//2
      if compositepi(s[k]) < n:
          i = k
      else:
          j = k
    return s[i] + n - compositepi(s[i])
```

**Comment by postvakje** [comment]
The current implementation of `composite(n)` mirrors the implementation of `prime(n)` in #10888, which also does not use sieve to improve performance for large n.

**Comment by smichr** [comment]
Perhaps the thing to do is use the sieve if the sieve is large enough, otherwise use the implementation given.

**Comment by postvakje** [comment]
I think that is a good idea.  I added the use of sieve when it is large enough (back) in `prime()`, `composite()`, `nextprime()`, etc. in PR #11163.

**Comment by smichr** [comment]
PR was committed.
