### ISSUE TITLE
MatrixSymbol doesn't work in solve()

### ISSUE THREAD

**Issue by nsabovic** [sympy/sympy#11124]
In sympy 1.0, trying to solve a simple equation with `MatrixSymbol` gives an error:

```
In [1]: from sympy import *
In [2]: solve(Eq(MatrixSymbol('a', 2, 1), MatrixSymbol('b', 2, 1)))

AttributeError: 'MatrixSymbol' object has no attribute 'as_coefficient'
```

The same thing works with manually entered symbols:

```
In [3]: solve(Eq(Matrix(symbols('a1` a2')), Matrix(symbols('b1 b2'))))

Out[3]: {a2: b2, a1`: b1}
```

Am I missing something? I thought `MatrixSymbol`s were usable in this fashion. If not, `AttributeError` isn't the way to go.

**Comment by asmeurer** [comment]
Duplicate of https://github.com/sympy/sympy/issues/7379
