### ISSUE TITLE
stats module shouldn't require assumptions to be set on parameters

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#11121]
Right now, if you try to create a Normal random variable with sympy.stats:

```
In [21]: mu, sigma = symbols('mu sigma')

In [22]: Normal("X", mu, sigma)
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-22-44ed9802fc72> in <module>()
----> 1 Normal("X", mu, sigma)

/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/stats/crv_types.py in Normal(name, mean, std)
   1775     """
   1776
-> 1777     return rv(name, NormalDistribution, (mean, std))
   1778
   1779 #-------------------------------------------------------------------------------

/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/stats/crv_types.py in rv(symbol, cls, args)
    133     args = list(map(sympify, args))
    134     dist = cls(*args)
--> 135     dist.check(*args)
    136     return SingleContinuousPSpace(symbol, dist).value
    137

/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/stats/crv_types.py in check(mean, std)
   1702     @staticmethod
   1703     def check(mean, std):
-> 1704         _value_check(std > 0, "Standard deviation must be positive")
   1705
   1706     def pdf(self, x):

/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/stats/rv.py in _value_check(condition, message)
   1102     """
   1103     if condition != True:
-> 1104         raise ValueError(message)

ValueError: Standard deviation must be positive
```

This is because I didn't create `sigma = symbols('sigma', positive=True)`. 

This is an antipattern. Assumptions checks shouldn't fail on None, only on False. 

This should be easy to fix. Just modify how the `_value_check` function works.

**Comment by Upabjojr** [comment]
Remember that `sympy.stats` was intended for evaluation of integrals. If we don't set the proper assumptions, we could get wrong results when evaluating the expressions.

**Comment by Upabjojr** [comment]
Also, we should allow for compound random variables, that is putting a `RandomSymbol` as a parameter for the construction of another `RandomSymbol`.

**Comment by asmeurer** [comment]
To be clear, false assumptions should still error. The issue is disallowing None assumptions. Doing this is always an antipattern, because it places an unnecessary burden on users to set assumptions on their symbols, and furthermore, it limits the system to expressions which SymPy's assumptions system can compute (something like `Normal('X', mu, expr)` would be disallowed if `expr` were too complicated to for SymPy to compute `is_positive` on, even if it were actually true). 

Allowing random parameters should be a separate issue. I imagine that would be more work to fix.

**Comment by asmeurer** [comment]
Having too few assumptions should never result in wrong results. If that happens, it's a bug. However, it is possible that not setting sigma to be positive might result in a more complicated result from an integral than what is desired.
