### ISSUE TITLE
[stats] Calculating probabilities for a normal variable often raises an error when using Floats

### ISSUE THREAD

**Issue by wxgeo** [sympy/sympy#11142]
IPython console for SymPy 1.0.1.dev (Python 2.7.6-64-bit)
In [1]: from sympy.stats import Normal, P
In [2]: mu=7.74
In [3]: sigma=1.95
In [4]: X = Normal('X', mu, sigma)
In [5]: k=6.23
In [6]: P(X>k)

---

PolynomialDivisionFailed

In [19]: Y = Normal('X', 12.5, 1.1)
In [20]: P(Y>1.1)
Out[20]: 0.707106781186548⋅√2
In [21]: Y = Normal('X', 12.5, 6.1)
In [22]: P(Y>1.1)

---

PolynomialDivisionFailed

**Comment by wxgeo** [comment]
Note that converting k to a rational avoids this error:

    from sympy.stats import Normal, P
    mu=7.74
    sigma=1.95
    X = Normal('X', mu, sigma)
    k=6.23
    P(X>Rational(k))

Previous code returns `0.55199635474805⋅√2` which sounds a bit weird imo but is correct.

**Comment by czgdp1807** [comment]
**Code**
```
from sympy.stats import Normal, P
mu=7.74
sigma=1.95
X = Normal('X', mu, sigma)
k=6.23
print(P(X>k))
```
**Output**
```
0.55199635474805*sqrt(2)
```
@sidhantnagpal I think this can be closed.

**Comment by sidhantnagpal** [comment]
That's right, both the code blocks in _OP_ are now able to produce the same output.
