### ISSUE TITLE
Incorrect integration of (sqrt(1 + x) + sqrt(1 + x))**2/x with manualintegrate

### ISSUE THREAD

**Issue by lindsayad** [sympy/sympy#11152]
`In [36]: manualintegrate((sqrt(1 + x) + sqrt(1 + x))**2/x, x)`
`Out[36]: 4*x + 4*log(4*x)`

`In [37]: integrate((sqrt(1 + x) + sqrt(1 + x))**2/x, x)`
`Out[37]: 4*x + 4*log(x)`

**Comment by jksuom** [comment]
Both antiderivatives are valid though the latter one is simpler in form. Their difference is the constant `4*log(4)`.

**Comment by lindsayad** [comment]
Ah, you are of course correct. Silly me
