### ISSUE TITLE
Add angadhn to the SymPy organization

### ISSUE THREAD

**Issue by moorepants** [sympy/sympy#11162]
I would like to add @angadhn to the mechanics team.

@asmeurer @certik

**Comment by asmeurer** [comment]
Are you able to do it as a team maintainer?

**Comment by moorepants** [comment]
No, I think it only allows me to add people to the team if they are members of the sympy organization. I'm not allowed to add members to the org.

**Comment by asmeurer** [comment]
I see. It doesn't matter that the mechanics team doesn't have any repositories associated with it.

By the way, I also made the team visible. Previously it was secret (meaning other people wouldn't be able to @mention it).
