### ISSUE TITLE
Incorrect solution to diffeq y' = x^(-2)*(sin(2x) - 2xy)

### ISSUE THREAD

**Issue by johncurcio** [sympy/sympy#11173]
I started to use sympy not long ago and while trying to convince one of my professors to try it out he pointed out that the `dsolve` method does not correctly return an answer when the ODE is `y' = x^(-2)*(sin(2x) - 2xy)`. 

I tried to solve the equation using:

```
x, y = symbols('x y')
eq = Eq(Derivative(y(x), x), x**(-2)*(sin(2*x) - 2*x*y))
dsolve(eq)
dsolve(eq, hint="all")
dsolve(eq, hint="best")
```

All of these methods return the following solution (or something in the lines of that):

```
y(x) = C1 - 2*y*log(x) - 2*log(x) + log(x**2) + 2*Ci(2*x) - sin(2*x)/x
```

However, using solvers such as wolfram and axiom, the answer apparently was supposed to be:

```
y(x) = c1/x**2 - cos(2*x)/(2*x**2)
```

Is that a known issue?

**Comment by lePerdu** [comment]
In the equation, you need to declare `y` as a function of `x`. This:
```python
x = Symbol('x')
y = Function('y')(x)
eq = Eq(Derivative(y, x), x**(-2)*(sin(2*x) - 2*x*y))
dsolve(eq)
```
and this:
```python
x, y = symbols('x y')
eq = Eq(Derivative(y(x), x), x**(-2)*(sin(2*x) - 2*x*y(x)))
dsolve(eq)
```
both yield the correct answer:
```python
Eq(y(x), (C1 - cos(2*x)/2)/x**2)
```

**Comment by oscarbenjamin** [comment]
In current SymPy master you would get an error with that code which would force you to correct it to this:
```python
from sympy import *
x = Symbol('x')
y = Function('y')
eq = Eq(Derivative(y(x), x), x**(-2)*(sin(2*x) - 2*x*y(x)))
```

Then the answer you get is
```
In [9]: dsolve(eq)                                                                                                                                            
Out[9]: 
            cos(2⋅x)
       C₁ - ────────
               2    
y(x) = ─────────────
              2     
             x   
```

I think this is correct so this can be closed.
