### ISSUE TITLE
bug with trigsimp(method='combined') and trigsimp(method='groebner')

### ISSUE THREAD

**Issue by chaowenGUO** [sympy/sympy#11181]
code:

import sympy
x,y=sympy.symbols('x,y',real=True)
sympy.trigsimp(y\* sympy.sin(x/2)**2,method='combined')

NameError                                 Traceback (most recent call last)
<ipython-input-28-c21cbd1cfed9> in <module>()
      1 import sympy
      2 x,y=sympy.symbols('x,y',real=True)
----> 3 sympy.trigsimp(y\* sympy.sin(x/2)**2,method='combined')

/usr/lib/python3/dist-packages/sympy/simplify/trigsimp.py in trigsimp(expr, **opts)
    511                    }[method]
    512 
--> 513     return trigsimpfunc(expr)
    514 
    515 

/usr/lib/python3/dist-packages/sympy/simplify/trigsimp.py in <lambda>(x)
    507         'groebner': (lambda x: groebnersimp(x, *\* opts)),
    508         'combined': (lambda x: futrig(groebnersimp(x,
--> 509                                polynomial=True, hints=[2, tan]))),
    510         'old': lambda x: trigsimp_old(x, **opts),
    511                    }[method]

/usr/lib/python3/dist-packages/sympy/simplify/trigsimp.py in groebnersimp(ex, *\* opts)
    500         if not isinstance(new, Expr):
    501             return new
--> 502         return trigsimp_groebner(new, *\* opts)
    503 
    504     trigsimpfunc = {

/usr/lib/python3/dist-packages/sympy/simplify/trigsimp.py in trigsimp_groebner(expr, hints, quick, order, polynomial)
    377 
    378     if freegens and pdenom.has_only_gens(\* set(gens).intersection(pdenom.gens)):
--> 379         num = Poly(num, gens=gens+freegens).eject(*gens)
    380         res = []
    381         for monom, coeff in num.terms():

NameError: name 'Poly' is not defined

Also, there is similar error when I use method='groebner'

**Comment by jksuom** [comment]
It is odd that the name 'Poly' should not be defined since it is imported at the top of the file. Maybe there is some problem in the installation.

This is what I get:
```
>>> import sympy
>>> x,y=sympy.symbols('x,y',real=True)
>>> sympy.trigsimp(y* sympy.sin(x/2)**2,method='combined')
y*(-cos(x) + 1)/2
```

**Comment by gcwenken** [comment]
Well, at top of file trigsimp.py, I just see:
from __future__ import print_function, division

from collections import defaultdict

from sympy.core.cache import cacheit
from sympy.core import (sympify, Basic, S, Expr, expand_mul, factor_terms,
    Mul, Dummy, igcd, FunctionClass, Add, symbols, Wild, expand)
from sympy.core.compatibility import reduce, iterable
from sympy.core.numbers import I, Integer
from sympy.core.function import count_ops, _mexpand
from sympy.functions.elementary.trigonometric import TrigonometricFunction
from sympy.functions.elementary.hyperbolic import HyperbolicFunction
from sympy.functions import sin, cos, exp, cosh, tanh, sinh, tan, cot, coth

from sympy.strategies.core import identity
from sympy.strategies.tree import greedy


from sympy.polys.polyerrors import PolificationFailed
from sympy.polys.polytools import groebner
from sympy.polys.domains import ZZ
from sympy.polys import factor, cancel, parallel_poly_from_expr

from sympy.utilities.misc import debug

I do not see any import of Poly. I also get the same information from:
http://docs.sympy.org/latest/_modules/sympy/simplify/trigsimp.html#trigsimp

I do not think it is the problem in the installation.
 
Well, I use sympy 1.0

**Comment by jksuom** [comment]
```
commit 50d47cfe61f9982e8f1cf2e99bc3cdfa4dc2079c
Author: arihant parsoya <parsoyaarihant@gmail.com>
Date:   Sat Apr 30 12:55:44 2016 +0530

    imported Poly function in trigsimp.py file

diff --git a/sympy/simplify/trigsimp.py b/sympy/simplify/trigsimp.py
index 5dbbdb4..7a21e56 100644
--- a/sympy/simplify/trigsimp.py
+++ b/sympy/simplify/trigsimp.py
@@ -15,7 +15,7 @@
 from sympy.strategies.core import identity
 from sympy.strategies.tree import greedy
 
-
+from sympy.polys import Poly
 from sympy.polys.polyerrors import PolificationFailed
 from sympy.polys.polytools import groebner
 from sympy.polys.domains import ZZ

```
Yes, you are right. It seems that it was imported only after v1.0 was released.

**Comment by oscarbenjamin** [comment]
I now get:
```
In [6]: import sympy 
   ...: x,y=sympy.symbols('x,y',real=True) 
   ...: sympy.trigsimp(y* sympy.sin(x/2)**2,method='combined')                                                                                                
Out[6]: 
y⋅(1 - cos(x))
──────────────
      2  
```
Looks like this was fixed a long time ago so closing.
