### ISSUE TITLE
There is no class for Parabola in geometry module

### ISSUE THREAD

**Issue by dimitra-kon** [sympy/sympy#11191]
We have noticed that there is no class in the geometry module that implements Parabola, so we are working on adding a new one.

**Comment by ChristinaZografou** [comment]
We sent a pull request including our basic implementation of class Parabola.

**Comment by leosartaj** [comment]
#11192

On 4 June 2016 at 13:27, Christina Zografou <notifications@github.com>
wrote:

> We sent a pull request including our basic implementation of class
> Parabola.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/sympy/sympy/issues/11191#issuecomment-223742827>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AF7g-CDuQb1QSBHqMja3eBi6lhFV2W49ks5qIS_7gaJpZM4IuEz7>
> .
>



-- 
Regards
*Sartaj Singh*

*Mathematics and Computing*,
Indian Institute of Technology,
Varanasi - 221 005 INDIA

E-mail: singhsartaj94@gmail.com, *sartaj.singh.apm13@itbhu.ac.in
<sartaj.singh.apm13@itbhu.ac.in>*
