### ISSUE TITLE
Physics vector printing screws up matrix brackets.

### ISSUE THREAD

**Issue by moorepants** [sympy/sympy#11197]
On master:

```
Python 3.5.1 |Continuum Analytics, Inc.| (default, Dec  7 2015, 11:16:01) 
Type "copyright", "credits" or "license" for more information.

IPython 4.2.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: from sympy.physics.mechanics.models import n_link_pendulum_on_cart

In [2]: kane = n_link_pendulum_on_cart(1)

In [3]: from sympy import Eq

In [4]: from sympy.physics.mechanics import mechanics_printing

In [5]: me
mechanics_printing  memoryview          

In [5]: mechanics_printing()

In [6]: kane = n_link_pendulum_on_cart(1)

In [7]: Eq(kane.mass_matrix_full * kane.q.col_join(kane.u).diff(), kane.forcing_full)
Out[7]: 
⎡               q₀̇                ⎤ = ⎡          u₀           ⎤
⎢                                  ⎥   ⎢                       ⎥
⎢               q₁̇                ⎥   ⎢          u₁           ⎥
⎢                                  ⎥   ⎢                       ⎥
⎢-l₀⋅m₁⋅cos(q₁)⋅u₁̇ + (m₀ + m₁)⋅u₀̇⎥   ⎢          2            ⎥
⎢                                  ⎥   ⎢- l₀⋅m₁⋅u₁ ⋅sin(q₁) + F⎥
⎢    2                             ⎥   ⎢                       ⎥
⎣  l₀ ⋅m₁⋅u₁̇ - l₀⋅m₁⋅cos(q₁)⋅u₀̇  ⎦   ⎣    g⋅l₀⋅m₁⋅sin(q₁)    ⎦
```

**Comment by parsoyaarihant** [comment]
I want to work on this issue. How do I proceed?

**Comment by moorepants** [comment]
The entries of the matrix are printed with the sympy.physics.vector pretty printers (basically changes Derivative(q(t), t) to q'. These dots don't seem to work with the matrix pretty printers. You'd need to investigate the interaction between these two printers.

**Comment by rammanoj** [comment]
Can I work on this issue?

**Comment by articuno12** [comment]
@moorepants I wish to work on this issue.I tried to follow your previous comment.I am not able to understand what role matrix pretty printers play.Can you please elaborate a bit more?

**Comment by articuno12** [comment]
@moorepants I have understood what is causing the error and have narrowed it down to few lines. The error is caused after converting dq/dt to other notation(q ^()) , when we consider width or len of this element ,it comes out be 3 instead of 1 ,mostly because unicode character also gets counted.So now when we align the elements in a row in matrix extra space get added for blank vertical spaces to adjust its width also to 3. Please guide me how to move forward now.

**Comment by articuno12** [comment]
@moorepants  Please guide me how to move forward.

**Comment by oscargus** [comment]
Same issue as #9313
