### ISSUE TITLE
Code quality tests are not failing on Travis

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#11204]
See https://travis-ci.org/sympy/sympy/jobs/135668052#L3715, where it says that on commit 36b0e24, the code quality tests pass (note that this is the test against the branch master, not a PR, so it's testing exactly that commit). But for me:

```
sympy(36b0e24...)%$./bin/test quality
==================================================================== test process starts =====================================================================
executable:         /Users/aaronmeurer/anaconda3/bin/python  (3.5.1-final-0) [CPython]
architecture:       64-bit
cache:              yes
ground types:       python
random seed:        8986512
hash randomization: on (PYTHONHASHSEED=931924248)

sympy/utilities/tests/test_code_quality.py[6] F.....                                                                                                    [FAIL]

______________________________________________________________________________________________________________________________________________________________
___________________________________________________ sympy/utilities/tests/test_code_quality.py:test_files ____________________________________________________
  File "/users/aaronmeurer/documents/python/sympy/sympy/sympy/utilities/tests/test_code_quality.py", line 228, in test_files
    check_directory_tree(SYMPY_PATH, test, exclude)
  File "/users/aaronmeurer/documents/python/sympy/sympy/sympy/utilities/tests/test_code_quality.py", line 107, in check_directory_tree
    check_files(glob(join(root, pattern)), file_check, exclusions)
  File "/users/aaronmeurer/documents/python/sympy/sympy/sympy/utilities/tests/test_code_quality.py", line 123, in check_files
    file_check(fname)
  File "/users/aaronmeurer/documents/python/sympy/sympy/sympy/utilities/tests/test_code_quality.py", line 143, in test
    test_this_file(fname, test_file)
  File "/users/aaronmeurer/documents/python/sympy/sympy/sympy/utilities/tests/test_code_quality.py", line 169, in test_this_file
    assert False, message_space % (fname, idx + 1)
AssertionError: File contains trailing whitespace: /users/aaronmeurer/documents/python/sympy/sympy/sympy/holonomic/holonomic.py, line 1042.

==================================================== tests finished: 5 passed, 1 failed, in 2.00 seconds =====================================================
DO *NOT* COMMIT!
```

And indeed, at https://github.com/sympy/sympy/blob/36b0e2433fd9d814acd2ed74d5c2e68a69e37f12/sympy/holonomic/holonomic.py#L1042 you can see that that line ends in trailing whitespace. 

I'm opening a PR to fix the immediate issue, but we should investigate why the tests didn't fail (they didn't fail on the [PR](https://github.com/sympy/sympy/pull/11195) either, or else it couldn't have been merged thanks to GitHub's branch protection).

**Comment by asmeurer** [comment]
Here is the PR that clears the whitespace https://github.com/sympy/sympy/pull/11205

**Comment by asmeurer** [comment]
Travis claims to have checked out the [correct commit](https://travis-ci.org/sympy/sympy/jobs/135668052#L117). So I think there are two possibilities:

- Travis is lying, and is really testing a different commit, or
- something is clearing the trailing whitespace

A third possibility is that somehow the code quality tests are broken, but it seems odd that they would work on my machine but not on Travis, so I think that's unlikely.

**Comment by certik** [comment]
We need to figure out how it is possible that trailing white space got in.

**Comment by asmeurer** [comment]
I think setuptools is clearing whitespace when SymPy is installed. I just tested installing SymPy from master in an empty conda environment, and `sympy.test('quality')` passes.

**Comment by asmeurer** [comment]
Oh, it's not that at all. The holonomic module is not being installed. Meaning none of the holonomic tests are being run at all. @shubhamtibra can you fix this?

**Comment by shubhamtibra** [comment]
Sure. What am I supposed to do for installing the module?

**Comment by asmeurer** [comment]
Run [this](https://github.com/sympy/sympy/blob/master/setup.py#L66) and [this](https://github.com/sympy/sympy/blob/master/setup.py#L256). You may also need to fix some test failures in holonomic, since they have never been tested by Travis.

**Comment by shubhamtibra** [comment]
I ran these commands. I guess they should change some files, but there isn't any (nothing from `git diff` or `git status`).?

**Comment by shubhamtibra** [comment]
Oh, I get it. I need to make the changes manually.

**Comment by asmeurer** [comment]
I have a general fix at https://github.com/sympy/sympy/pull/11269, which now tests that the modules and tests are up-to-date in setup.py. But I didn't check if there were any holonomic test failures, so if there are any, you should fix those. Also, at least https://github.com/sympy/sympy/pull/11267 will need to be merged first.

**Comment by shubhamtibra** [comment]
Thanks for the fix @asmeurer . I will take care if test(s) fail.
