### ISSUE TITLE
floor(ceiling(x)) doesn't simplify

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#11207]
`floor(ceiling(x))` doesn't simplify. It should simplify to just `ceiling(x)`. 

This works if `x` is set to be real, because then `ceiling(x)` sets itself as an integer, and `floor(x)` returns `x` if `x` is an integer. But for complex `x`, the floor and ceiling are still defined, but are not integers if `x` is not real. However, the definition appears to be simply that the usual floor and ceiling are applied to the real and complex parts separately, so `floor(ceiling(x)) == ceiling(x)` is always true. Ditto for `ceiling(ceiling(x))`, `ceiling(floor(x))`, and so on.

**Comment by cyru** [comment]
This seems to be fixed in the latest version of sympy. The expression "floor(ceiling(x)) == ceiling(x)" evaluates to true.
