### ISSUE TITLE
Unable to solve heaviside equations

### ISSUE THREAD

**Issue by parsoyaarihant** [sympy/sympy#11216]
I ran the following program:

``` python
In [1]: from sympy import *

In [2]: from sympy.abc import x

In [3]: solveset(Heaviside(x)-1, x, S.Reals)
Out[3]: ConditionSet(x, Eq(Heaviside(x) - 1, 0), (-oo, oo))
```

**Comment by zanzibar7** [comment]
This should be easy to implement.  Is there documentation on the standard method for
extending `solveset`?  (like there is for `integrate`)

**Comment by parsoyaarihant** [comment]
I dont think so, but you can check [this](https://github.com/sympy/sympy/wiki/GSoC-2015-Application-AMiT-Kumar--Solvers-:-Extending-Solveset).

**Comment by oscarbenjamin** [comment]
Works fine now on master:
```
In [8]: solveset(Heaviside(x)-1, x, Reals)                                                                                                                    
Out[8]: (0, ∞)
```

**Comment by oscarbenjamin** [comment]
Closing as fixed
