### ISSUE TITLE
solveset(sin(pi*x), x, domain=S.Reals) doesn't give the solution

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#11218]
See https://stackoverflow.com/questions/37603511/sympy-solve-for-all-solutions-on-domain.

```
In [2]: solveset(sin(x), x, domain=S.Reals)
Out[2]: {2⋅n⋅π | n ∊ ℤ} ∪ {2⋅n⋅π + π | n ∊ ℤ}

In [3]: solveset(sin(pi*x), x, domain=S.Reals)
Out[3]:
⎧               ⎛ 2⋅ⅈ⋅π⋅x    ⎞  -ⅈ⋅π⋅x     ⎫
⎪            -ⅈ⋅⎝ℯ        - 1⎠⋅ℯ           ⎪
⎨x | x ∊ ℝ ∧ ────────────────────────── = 0⎬
⎪                        2                 ⎪
⎩                                          ⎭
```

**Comment by kshitij10496** [comment]
For solving trigonometric functions, we rewrite them in terms of exponential function.
As can be seen in this example, we cannot solve all the corresponding exponential equations.

However, some can be solved via `solve_decomposition`. #11141 
I have been working on solving this particular example for some time.

**Comment by oscarbenjamin** [comment]
This works fine-ish now in master:
```
In [5]: solveset(sin(x), x, domain=Reals)                                                                                                                     
Out[5]: {2⋅n⋅π | n ∊ ℤ} ∪ {2⋅n⋅π + π | n ∊ ℤ}
```
That should simplify a bit but it is an explicit form of the solution.

**Comment by asmeurer** [comment]
The problem is with the `sin(pi*x)` version. I still get the nonuseful result for it in master.

**Comment by gschintgen** [comment]
With the draft PR #19507:
```
In [4]: solveset(sin(pi*x), x, domain=S.Reals)
Out[4]:
                ⎧2⋅n⋅π + π        ⎫
{2⋅n | n ∊ ℤ} ∪ ⎨───────── | n ∊ ℤ⎬
                ⎩    π            ⎭

In [5]: simplify(_)
Out[5]: {2⋅n | n ∊ ℤ} ∪ {2⋅n + 1 | n ∊ ℤ}
```
