### ISSUE TITLE
subs() bug

### ISSUE THREAD

**Issue by parsoyaarihant** [sympy/sympy#11223]
subs() method is giving wrong result.
#### The following gives correct result:
```python
>>> from sympy import *
>>> from sympy.abc import x,y,z
>>> from sympy import I
>>> g = -I*exp(2*I*x) + I
>>> g.subs(exp(I*x), y)
-I*y**2 + I
```
#### The following gives wrong result:
```python
>>> g = -I*exp(2*pi*I*x) + I
>>> g.subs(exp(I*x), y)
-I*exp(2*I*pi*x) + I
```
answer should be `-I*y**(2*pi) + I`

**Comment by smichr** [comment]
Comments have been left on #11225 indicating that this is the correct behavior since the substitution as you have proposed would not always be valid (if I am understanding all correctly).
