### ISSUE TITLE
solveset unable to solve equation x**2.5 = 1

### ISSUE THREAD

**Issue by parsoyaarihant** [sympy/sympy#11228]
```python
>>> from sympy import *
>>> from sympy.abc import x
>>> g = x**(2.5) - 1
>>> solveset(g, x, domain=S.Complexes)
ConditionSet(x, Eq(x**2.5 - 1, 0), Complexes((-oo, oo) x (-oo, oo), False))
```

**Comment by GNAMGNAM** [comment]
>>> x=Symbol('x')
>>> solveset(x**(2)-1,x)
{-1, 1}

OK

>>> solveset(x**(4/2)-1,x)
ConditionSet(x, Eq(x**2.0 - 1, 0), Complexes((-oo, oo) x (-oo, oo), False))

UNABLE TO SOLVE

**Comment by parsoyaarihant** [comment]
I am working on this issue. I will submit a PR soon.

**Comment by rouckas** [comment]
Perhaps you want to do:
```
>>> solveset(x**Rational(5,2)-1,x)
{1, -sqrt(5)/4 - 1/4 - I*sqrt(-sqrt(5)/8 + 5/8), -sqrt(5)/4 - 1/4 + I*sqrt(-sqrt(5)/8 + 5/8)}
```
It is better to avoid floats in symbolic computations

**Comment by rouckas** [comment]
@GNAMGNAM see [Python numbers vs. SymPy Numbers](http://docs.sympy.org/latest/gotchas.html#python-numbers-vs-sympy-numbers)
This works:
```
>>> solveset(x**Rational(4,2)-1,x)
{-1, 1}
>>> solveset(x**(S(4)/2)-1,x)
{-1, 1}
```

**Comment by parsoyaarihant** [comment]
@rouckas , thanks.
