### ISSUE TITLE
Products of sums with fractions, integers and similar are automatically expanded

### ISSUE THREAD

**Issue by Wrzlprmft** [sympy/sympy#11226]
Consider the following code:

```Python
from sympy.abc import *

some_sum = p+q+r+s+t+u+v+w+x+y+z

print( some_sum * sympy.Rational(42,23) )
print( some_sum * sympy.Float(0.123) )
print( some_sum * sympy.Integer(42) )
print( some_sum * c )
```

On my Sympy, the first three expressions are expanded, while the last is not. This should not happen as expanding is no straightforward simplification and not easily reversible (`factor` can take considerably long if the sum is sufficiently long). Moreover, it is inconsistent with the last expression not being expanded.

This happens in version 1.0 as well as 0.7.4.1-1.

**Comment by smichr** [comment]
Yes, this is issue #4596, a deeply rooted feature that nobody has yet extracted.
