### ISSUE TITLE
Limit erroneously reported as infinity

### ISSUE THREAD

**Issue by krey** [sympy/sympy#11270]
```
> limit(log(   1/2  *exp(u*x)+   1/2  *exp(-u*x))/(x**2), x, 0)
oo
```

```
> limit(log(S("1/2")*exp(u*x)+S("1/2")*exp(-u*x))/(x**2), x, 0)
u**2/2
```

The latter of the two is the correct answer. I understand that the discrepancy is due to the fact that python converts 1/2 into a floating point number before sympy is able to treat it as a fraction.

But I think it is buggy behaviour to return infinity instead throwing an "UnknownLimitError" or something.

I'm using the latest version (1.0 apparently?) from pip under Python 3.5.1 on ArchLinux.

**Comment by jksuom** [comment]
> python converts 1/2 into a floating point number

Also this is possible:
```
>>> 1/2
0
```
Python converts the argument of `log` to 0.

**Comment by krey** [comment]
Not in Python 3 ;-)

**Comment by oscarbenjamin** [comment]
This seems to be fixed. I now get:
```julia
In [3]: limit(log(   1/2  *exp(u*x)+   1/2  *exp(-u*x))/(x**2), x, 0)                                                                                         
Out[3]: 
     2
0.5⋅u 

In [4]: limit(log(   S(1)/2  *exp(u*x)+   S(1)/2  *exp(-u*x))/(x**2), x, 0)                                                                                   
Out[4]: 
 2
u 
──
2 
```
