### ISSUE TITLE
MathML printer produces incorrect results with matrices

### ISSUE THREAD

**Issue by gungan37** [sympy/sympy#11273]
When using the MathML printer, matrices are not printed correctly. For example,

`M = Matrix([[1,2],[3,4],[5,6]])`
`print_mathml(M)`

produces the following output

`<immutablematrix>`
`<cn>1</cn>`
`<cn>2</cn>`
`<cn>3</cn>`
`<cn>4</cn>`
`<cn>5</cn>`
`<cn>6</cn>`
`</immutablematrix>`

rather than using `matrix` and `matrixrow` MathML elements like the code is intended to.

**Comment by oscargus** [comment]
This seems to have been fixed over time so I am closing this for now. Current output:
`<matrix><matrixrow><cn>1</cn><cn>2</cn></matrixrow><matrixrow><cn>3</cn><cn>4</cn></matrixrow><matrixrow><cn>5</cn><cn>6</cn></matrixrow></matrix>`
