### ISSUE TITLE
ccode(sinc(x)) doesn't work

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#11281]
```
In [30]: ccode(sinc(x))
Out[30]: '// Not supported in C:\n// sinc\nsinc(x)'
```

I don't think `math.h` has `sinc`, but it could print

```
In [38]: ccode(Piecewise((sin(theta)/theta, Ne(theta, 0)), (1, True)))
Out[38]: '((Ne(theta, 0)) ? (\n   sin(theta)/theta\n)\n: (\n   1\n))'
```

**Comment by kritkaran94** [comment]
@asmeurer I would like to fix this issue. Should I work upon  the codegen.py file ? If there's something else tell me how to start ?

**Comment by asmeurer** [comment]
The relevant file is sympy/printing/ccode.py

**Comment by rahuldan** [comment]
@asmeurer I am new here. I would like to work on this issue. Please tell me how to start?

**Comment by cbm755** [comment]
Since there are two people asking, maybe one person can try #11286 which is very similar, maybe even easier.

**Comment by kritkaran94** [comment]
@asmeurer @debugger22 the output for the same should be sinc(x/pi) right?
