### ISSUE TITLE
Converting holonomic function to a symbolic expression

### ISSUE THREAD

**Issue by certik** [sympy/sympy#11288]
```
In [41]: %time a = integrate(sin(x)**2/x, (x, 1, x))
CPU times: user 9.31 s, sys: 0 ns, total: 9.31 s
Wall time: 9.31 s

In [42]: a
Out[42]: 
log(x)   Ci(2⋅x)   Ci(2)
────── - ─────── + ─────
  2         2        2  

In [43]: %time b = sympy.holonomic.from_sympy(sin(x)**2/x).integrate((x, 1, x))
CPU times: user 104 ms, sys: 0 ns, total: 104 ms
Wall time: 102 ms

In [44]: b
Out[44]: HolonomicFunction((4)Dx + (4*x)Dx**2 + (3)Dx**3 + (x)Dx**4, x), f(1) = 0, f'(1) = sin(1)**2, f''(1) = -sin(1)**2 + 2*sin(1)*cos(1), f'''(1) = -4*sin(1)*cos(1) + 2*cos(1)**2
```
Here `a` and `b` are the same functions, but `b` was calculated immediately, while `a` is very slow, since the `integrate()` function can sometimes be slow, its algorithm is pretty complicated.

However, to be truly fair, we need to be able to convert back to a symbolic expression, if it is possible.

**Comment by shubhamtibra** [comment]
If the function is also Hypergeometric, then we have an implementation at #11246 .  However we do need a general method for any Holonomic Function.

**Comment by certik** [comment]
That PR indeed works in many cases, though it fails in this case (#11291). Is it because `a` above is not a linear combination of hypergeometric functions?

**Comment by shubhamtibra** [comment]
This didn't work also because of the fact that the initial conditions were stored at `1`. While computing a  Recurrence relation in the coefficients of Power series, the series is taken around origin only. This recurrence is further used to convert to `hyper` and eventually to symbolic expressions using `hyperexpand`.
One fix is that if conditions are not given at origin, then the method automatically uses numerical computation to get them at origin and proceed.
Another is if we can get the recurrence relation for Power series about any point. Can anyone confirm if this is possible?

**Comment by certik** [comment]
Now I am getting:
```
In [46]: b = from_sympy(sin(x)**2/x, x0=1).integrate((x, 1, x))

In [47]: b
Out[47]: HolonomicFunction((4)Dx + (4*x)Dx**2 + (3)Dx**3 + (x)Dx**4, x), f(1) = 0, f'(1) = sin(1)**2, f''(1) = -sin(1)**2 + 2*sin(1)*cos(1), f'''(1) = -4*sin(1)*cos(1) + 2*cos(1)**2

In [48]: b.to_sympy()
Out[48]: 
3⋅(-2⋅x + Si(2⋅x))⋅(-1 - cos(2) + 2⋅sin(2))   (2⋅x⋅sin(1) + (-sin(1) + 2⋅cos(1
─────────────────────────────────────────── + ────────────────────────────────
                     8                                                        

))⋅(log(x) - Ci(2⋅x) + γ + log(2)))⋅sin(1)
──────────────────────────────────────────
    2                                     
```
Which is the right answer, as you can check using:
```
In [49]: a = integrate(sin(x)**2/x, (x, 1, x))

In [51]: from_sympy(a, x0=1)
Out[51]: HolonomicFunction((4)Dx + (4*x)Dx**2 + (3)Dx**3 + (x)Dx**4, x), f(1) = 0, f'(1) = -cos(2)/2 + 1/2, f''(1) = -1/2 + cos(2)/2 + sin(2), f'''(1) = -2*sin(2) + cos(2) + 1
```
The ODE is the same, and the initial conditions are also the same, as can be checked numerically.

**Comment by certik** [comment]
So I think we can close this one @shubhamtibra, feel free to close it.
