### ISSUE TITLE
Improving integrate() for holonomic functions

### ISSUE THREAD

**Issue by certik** [sympy/sympy#11284]
Currently it does:
```
In [17]: sympy.holonomic.from_sympy(sin(x)**2/x).integrate((x, 0, 1))
Out[17]: HolonomicFunction((4)Dx + (4*x)Dx**2 + (3)Dx**3 + (x)Dx**4, x)
```
But should probably raise an exception, since it can't do it --- the returned answer is just a general holonomic function, which is wrong. Let's try just the indefinite integral:
```
In [13]: integrate(sin(x)**2/x, x)
Out[13]: 
log(x)   Ci(2⋅x)
────── - ───────
  2         2   
```
using holonomic functions:
```
In [20]: sympy.holonomic.from_sympy(sin(x)**2/x).integrate(x)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-20-7ec59a73e656> in <module>()
----> 1 sympy.holonomic.from_sympy(sin(x)**2/x).integrate(x)

/home/certik/repos/sympy/sympy/holonomic/holonomic.py in integrate(self, *args)
    525 
    526         # definite integral if limits are (x0, x)
--> 527         if len(args) == 1 and len(args[0]) == 3 and args[0][1] == self.x0 and args[0][2] == self.x:
    528             y0 = [S(0)]
    529             y0 += self.y0

TypeError: object of type 'Symbol' has no len()
```
Exception, should be fixed. Let's try another way:
```
In [24]: sympy.holonomic.from_sympy(sin(x)**2/x).integrate((x, 0, x))
Out[24]: HolonomicFunction((4)Dx + (4*x)Dx**2 + (3)Dx**3 + (x)Dx**4, x)
```
Let's confirm that this is the right answer:
```
In [26]: sympy.holonomic.from_sympy(_13)
Out[26]: HolonomicFunction((4)Dx + (4*x)Dx**2 + (3)Dx**3 + (x)Dx**4, x), f(1) = -Ci(2)/2, f'(1) = -cos(2)/2 + 1/2, f''(1) = -1/2 + cos(2)/2 + sin(2), f'''(1) = -2*sin(2) + cos(2) + 1
```
The holonomic function is indeed the same, but the initial condition was lost in 24. Any idea how to fix this?

cc @shubhamtibra.

**Comment by shubhamtibra** [comment]
When we converted `sin(x)**2/x`, initial conditions are stored at `1` instead of `0` as the function is not defined at `0`. Currently the `.integrate` method can only compute initial conditions if limits are `x0` to `x`, `x0` being `1` here.
To compute initial conditions for arbitrary limits, we will first have to write the method for numerical computation at any given point (currently we have to provide a path).

**Comment by shubhamtibra** [comment]
This can probably be the next thing to implement i.e. `making integrate work with arbitrary limits`. I will be on it.

**Comment by certik** [comment]
I see, I have to do:
```
In [4]: sympy.holonomic.from_sympy(sin(x)**2/x).integrate((x, 1, x))
Out[4]: HolonomicFunction((4)Dx + (4*x)Dx**2 + (3)Dx**3 + (x)Dx**4, x), f(1) = 0, f'(1) = sin(1)**2, f''(1) = -sin(1)**2 + 2*sin(1)*cos(1), f'''(1) = -4*sin(1)*cos(1) + 2*cos(1)**2
```
The initial conditions are a bit different, but hopefully they are numerically the same, except f(1) which is just a constant shift.

**Comment by shubhamtibra** [comment]
I didn't understand. Different from what?

**Comment by certik** [comment]
I clarified the comment. The initial conditions have symbolic form, that is obviously different, e.g. `-2⋅sin(2) + cos(2) + 1` is different to `-4⋅sin(1)⋅cos(1) + 2⋅cos^2 (1)`, but numerically it is the same value.

**Comment by shubhamtibra** [comment]
Yes. In case limits  are `x0` to `x`, just a shift of initial conditions happens. In a general method, we need numerical values at both upper and lower limit.

**Comment by certik** [comment]
I think fixing #11287 should help a lot.

**Comment by shubhamtibra** [comment]
I have made some changes in `.integrate()` at #11297 , so that it works with arbitrary limits using numerical computation. Since `0` is a singular point here, a numerical computation from `0` to `1` isn't possible however we can integrate from `1` to `0` and see if the magnitude is same with opposite sign. An example from the PR
```
>>> p = from_sympy(sin(x)**2/x, x0=2).integrate((x, 1, 0))
>>> q = (sin(x)**2/x).integrate((x, 0, 1)).evalf()
>>> p+q
-1.35060015205024e-6
```

**Comment by shubhamtibra** [comment]
Ping @certik @jksuom .

**Comment by certik** [comment]
0 is not a singular point. The function has all derivagives there.

**Comment by shubhamtibra** [comment]
I meant for the differential equation. A numerical integration isn't possible on `0`.

**Comment by jksuom** [comment]
The differential equation of `sin(x)**2/x` is `(4) + (4*x)Dx + (3)Dx**2 + (x)Dx**3`, and the coefficient `x` of its highest derivative vanishes at 0. Hence it is a (regular) singularity of the equation.

**Comment by certik** [comment]
```
In [1]: from sympy.holonomic import from_sympy

In [2]: time (sin(x)**2/x).integrate((x, 0, x))
CPU times: user 8.96 s, sys: 72 ms, total: 9.03 s
Wall time: 8.98 s
Out[2]: 
log(x)   Ci(2⋅x)   γ   log(2)
────── - ─────── + ─ + ──────
  2         2      2     2   

In [3]: time from_sympy(sin(x)**2/x).integrate((x, 0, x)).to_sympy()
CPU times: user 1.01 s, sys: 16 ms, total: 1.02 s
Wall time: 975 ms
Out[3]: 
log(x)   Ci(2⋅x)   γ   log(2)
────── - ─────── + ─ + ──────
  2         2      2     2   
```
So that's a 9.2x speedup over SymPy right here.
