### ISSUE TITLE
octave(sinc(x)) doesn't work

### ISSUE THREAD

**Issue by cbm755** [sympy/sympy#11286]
```
In [9]: octave_code(sinc(x))
Out[9]: '% Not supported in Octave:\n% sinc\nsinc(x)'
```

Octave does the "normalized sinc function" so the desired output is:

```
'sinc(x/pi)'
```

How to start:
1. clone sympy
2.  look at #11219, changes should be very similar to the `_print_uppergamma` stuff.

**Comment by cbm755** [comment]
Note, these should work too:
````
octave_code(sinc((x+3)))
'sinc((x + 3)/pi)'

octave_code(sinc(pi*(x+3)))
'sinc(x + 3)'
````

**Comment by rahuldan** [comment]
I want to work on this issue.

**Comment by cbm755** [comment]
great, send us a PR for comments whenever you can.

**Comment by rahuldan** [comment]
#11300

**Comment by rahuldan** [comment]
#11300 Please review this PR

**Comment by Lakshya1605** [comment]
Is this still open if so i want to work on this.

**Comment by cbm755** [comment]
Its fixed in master, not sure why this issue didn't autoclose with #11381.  Anyway, closing now.

Hope you found something else to work on.
