### ISSUE TITLE
Add a docstring how to plot a holonomic function

### ISSUE THREAD

**Issue by certik** [sympy/sympy#11285]
Something like this:
```
import sympy.holonomic
import numpy as np
r = np.linspace(1, 5, 100)
y = sympy.holonomic.from_sympy(sin(x)**2/x).evalf(r)
plot(r, y)
```

This should be part of some larger docstring, or part of a tutorial for the holonomic module. Here is a jupyter notebook showing that it works:

http://nbviewer.jupyter.org/gist/certik/849a62d23f615d89dd37585b76159e78

cc @shubhamtibra .

**Comment by shubhamtibra** [comment]
Thanks for the link. How about adding in the docstring of the `HolonomicFunction` class?

**Comment by certik** [comment]
That would work.
