### ISSUE TITLE
Any thoughts on starting to use mypy for type checking?

### ISSUE THREAD

**Issue by amitsaha** [sympy/sympy#11311]
For the uninitiated, [mypy ](http://mypy-lang.org/index.html) is "optional type checking" for Python.

**Comment by asmeurer** [comment]
Where would it be used? Most SymPy functions take any Expr or Basic type as input.

**Comment by eric-wieser** [comment]
xref gh-17945

**Comment by oscarbenjamin** [comment]
I'll close this because it is discussed in #17945 instead.
