### ISSUE TITLE
convert to MeijerG

### ISSUE THREAD

**Issue by certik** [sympy/sympy#11329]
Add a method that returns a MeijerG (unexpanded) of a given holonomic function, if it exists.

**Comment by jksuom** [comment]
This looks hard. It is easy to recognize those differential equations that have Meijer G-functions as solutions. Also the `a`- and `b`- parameters can be easily found from the equation. But this does not suffice, in general. To define a G-function these two families of parameters have to be divided into two parts each. Thus there are many G-functions satisfying the same differential equation. A general (holonomic) solution of the equation is a linear combination of these functions. The really hard question is how to find the coefficients of such a combination.

**Comment by certik** [comment]
Isn't the same problem with the hypergeometric differential equation?

**Comment by jksuom** [comment]
G-functions and generalized hypergeometric functions (series that begin with a term `x**s` for some complex `s`) are solutions of essentially the same differential equations. So it seems that the problem is more or less the same.

**Comment by certik** [comment]
And yet, we can convert to a hypergeometric function. I think we use the series expansion, but if it is possible to overcome this problem for a hypergeometric function, it might be possible to do the same for the G function somehow.

**Comment by jksuom** [comment]
Those conversions succeed under special conditions. And only a specific branch of a holonomic function is converted in the current implementation.

**Comment by jksuom** [comment]
But I think that if a conversion is desired, the chances are better with hypergeometric series when a holonomic function is defined with  initial conditions.

**Comment by certik** [comment]
I thought that's how we convert back to sympy, that we identify the hypergeometric function. The motivation to obtain a G function is to use the G function definite integrator, i.e. to use holonomic functions as a robust method to obtain a G function.

**Comment by certik** [comment]
I think this is fixed:
```
In [34]: expr_to_holonomic(sin(x))
Out[34]: HolonomicFunction((1) + (1)Dx**2, x), f(0) = 0, f'(0) = 1

In [35]: expr_to_holonomic(sin(x)).to_meijerg()
Out[35]: 
             ⎛        │  2⎞
     ╭─╮1, 0 ⎜        │ x ⎟
√π⋅x⋅│╶┐     ⎜        │ ──⎟
     ╰─╯0, 2 ⎝0  -1/2 │ 4 ⎠
───────────────────────────
             2             
```
