### ISSUE TITLE
convert to a hypergeometric function

### ISSUE THREAD

**Issue by certik** [sympy/sympy#11328]
Add a method that returns an unexpanded hypergeometric representation (if it exists) of a given HolonomicFunction. We already use this in `to_sympy()` but we expand the hypergeometric function.

**Comment by shubhamtibra** [comment]
We have that, use `to_hyper()`.

**Comment by certik** [comment]
I think this is fixed:
```
In [36]: expr_to_holonomic(sin(x)).to_hyper()
Out[36]: 
       ⎛    │   2 ⎞
   ┌─  ⎜    │ -x  ⎟
x⋅ ├─  ⎜    │ ────⎟
  0╵ 1 ⎝3/2 │  4  ⎠
```
