### ISSUE TITLE
from_sympy(sqrt(x)) fails

### ISSUE THREAD

**Issue by certik** [sympy/sympy#11327]
```
In [2]: from_sympy(sqrt(x))
---------------------------------------------------------------------------
NotImplementedError                       Traceback (most recent call last)
<ipython-input-2-246a3e4f65e0> in <module>()
----> 1 from_sympy(sqrt(x))

/home/certik/repos/sympy/sympy/holonomic/holonomic.pyc in from_sympy(func, x, initcond, x0)
   1719 
   1720     if not sol:
-> 1721         raise NotImplementedError
   1722     if not initcond:
   1723         return sol

NotImplementedError: 
```
Either it should raise `NotHolonomicError` or it should work.

**Comment by certik** [comment]
Here is the ODE that it satisfies, thanks to @asmeurer:
```
In [3]: f = sqrt(x)

In [4]: 2*x*f.diff(x) - f
Out[4]: 0
```

**Comment by certik** [comment]
Once this is done, also make sure things like `sqrt(1+x**2)` and other algebraic functions work.

**Comment by shubhamtibra** [comment]
There doesn't seem to be a direct algorithm for computing the differential equation of an algebraic function. We had a discussion on this [here](https://gitter.im/shubhamtibra/Holonomic_Discussion?at=5761215cf191398330a0a721), we should figure out some way to implement this.

**Comment by certik** [comment]
@shubhamtibra we can tackle a general algebraic function later. For now let's just tackle powers like `x^(1/2)`, `x^(1/3)` and so on. Here is how to derive the ODE:
```
f(x) = x^(1/n)
f'(x) = 1/n*x^{1/n-1} = x^{1/n}/(n*x) = f/(n*x)
-f + n*x*f' = 0
```
E.g. if `f(x) = sqrt(x)`, then `n = 2` and the ODE is `-f + 2*x*f' = 0`.

**Comment by certik** [comment]
Similarly, for `x^(m/n)` I get:
```
f(x) = x^(m/n)
f'(x) = m/n * f / x
-f(x) + n*x/m * f'(x) = 0
```
Then for things like sqrt(x^2+1), cannot you use the composition function that is already implemented?

**Comment by shubhamtibra** [comment]
Cool, I think this will be the way to go. Thanks @certik .

**Comment by certik** [comment]
It's actually thanks to @asmeurer, he showed me this trick yesterday.

**Comment by certik** [comment]
In the latest master, this now works:
```
In [3]: expr_to_holonomic(sqrt(x))
Out[3]: HolonomicFunction((-1/2) + (x)Dx, x), [(1/2, [1])]

In [4]: expr_to_holonomic(x**(S(1)/2))
Out[4]: HolonomicFunction((-1/2) + (x)Dx, x), [(1/2, [1])]

In [5]: expr_to_holonomic(x**(S(3)/2))
Out[5]: HolonomicFunction((-3/2) + (x)Dx, x), [(3/2, [1])]

In [6]: expr_to_holonomic(x**(S(3)/7))
Out[6]: HolonomicFunction((-3/7) + (x)Dx, x), [(3/7, [1])]

```
