### ISSUE TITLE
``MatrixBase.inv`` should have a docstring.

### ISSUE THREAD

**Issue by leosartaj** [sympy/sympy#11344]
Likewise, all the other public methods should have a docstring.

**Comment by kritkaran94** [comment]
@leosartaj I will take this issue and try to make the change/changes.

**Comment by leosartaj** [comment]
Sure.

On 5 July 2016 at 03:27, Krit Karan <notifications@github.com> wrote:

> @leosartaj <https://github.com/leosartaj> I will take this issue and try
> to make the change/changes.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/sympy/sympy/issues/11344#issuecomment-230358027>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AF7g-K52wXZ11TPAG7zNdjmqJqkdll8zks5qSYG4gaJpZM4JEoKt>
> .
>



-- 
Regards
*Sartaj Singh*

*Mathematics and Computing*,
Indian Institute of Technology,
Varanasi - 221 005 INDIA

E-mail: singhsartaj94@gmail.com, *sartaj.singh.apm13@itbhu.ac.in
<sartaj.singh.apm13@itbhu.ac.in>*

**Comment by leosartaj** [comment]
Fixed by #11346
