### ISSUE TITLE
TypeError exception in totient and reduced_totient LaTeX printers

### ISSUE THREAD

**Issue by gorisaka** [sympy/sympy#11351]
In spyder, or other latex enabled environment, run:
```python
>>> from sympy import *
>>> init_printing()
>>> x = symbols('x')
>>> totient(x) ** 2
```
...
```python
TypeError: _print_totient() takes 2 positional arguments but 3 were given
```

The same occurs for `reduced_totient`.

Edit:info

**Comment by kritkaran94** [comment]
@gorisaka It works fine for me. 
![screen shot 2016-07-07 at 3 37 48 pm](https://cloud.githubusercontent.com/assets/10063868/16649899/cf7d42c8-4458-11e6-8534-566d20da8e88.png)

**Comment by gorisaka** [comment]
Pretty printing is working. The problem ocurrs when using LaTeX printer.
