### ISSUE TITLE
Does SymPy implement Marichev-Adamchik/Mellin method for integration?

### ISSUE THREAD

**Issue by Piruzzolo** [sympy/sympy#11368]
Does SymPy implement Marichev-Adamchik Mellin transform method for indefinite integrals? Plans to implement it?
I can't find it in the code.

P.S. I know that's not the right place to write this, but here on Github we don't have a Faq at all. So excuse me since now. (we should create a separate repo for the Faq, as [IPFS](https://github.com/ipfs/faq/) does, for example)

**Comment by jksuom** [comment]
Can you give a reference to Mellin transform method for *indefinite* integrals. I only know of the method for definite integrals that is implemented in the `meijerint` module.

**Comment by Piruzzolo** [comment]
Sorry, meant "definite integrals". Made a mistake.

So it actually implements the method for definite integrals? 

Note: There's this test for differential equations: 
http://12000.org/my_notes/kamek/kamke_differential_equations.htm
There may be something similar for integral testing, but of course we'd need to convert it to sympy form

**Comment by jksuom** [comment]
There is a description of Mellin related integrals implemented in SymPy in the [documentation](http://docs.sympy.org/latest/modules/integrals/g-functions.html#the-g-function-integration-theorems). In particular, the 'Mellin method for definite integrals' is based on integral 2. The method is automatically applied by the `integrate` function, if it is applicable.

**Comment by Piruzzolo** [comment]
Ok, thank you very much. Will go through the docs for further details

**Comment by asmeurer** [comment]
Regarding the FAQ, there is one in the [wiki](https://github.com/sympy/sympy/wiki/Faq), although it hasn't been updated in a while. We should also update the documentation, if something is missing.

**Comment by oscarbenjamin** [comment]
I think this can be closed now.

**Comment by jksuom** [comment]
I think so too.
