### ISSUE TITLE
S.Reals should be accessible as just "Reals"

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#11378]
I think it's confusing that things like S.Reals are only accessible from the S object. We should just import `Reals` into the namespace. Personally I would also avoid using `S` outside of library code (i.e., don't use it in the docs), as I think the fact that things are singletonized is an implementation detail that most users shouldn't care about. 

I think there can be some issues if we use the same name for the class and the instance, but we already do it for [a few items](https://github.com/sympy/sympy/blob/39c6a9e42356d1afd6d8eb8a056e77ebfff6e5d4/sympy/core/__init__.py#L32-L34).

I believe this is just a matter of adding the set objects to that `__init__.py` file.

**Comment by asmeurer** [comment]
CC @sympy/sympy-solvers

**Comment by parsoyaarihant** [comment]
working on it.

**Comment by kshitij10496** [comment]
I think this is a good idea.

Should we extend this to `Complexes` as well ?

**Comment by aktech** [comment]
> Should we extend this to Complexes as well ?
 Yes, Indeed.

**Comment by kshitij10496** [comment]
> I think there can be some issues if we use the same name for the class and the instance, but we already do it for a few items.

Moreover, would it be advisable to continue following this convention in the future ?

**Comment by shrutishrm512** [comment]
@asmeurer  I have sent the pull request for this making changes in sets/__init__.py file please review it

**Comment by asmeurer** [comment]
Please cross reference the pull request here (and cross reference this issue on the pull request).

**Comment by shrutishrm512** [comment]
#11686

**Comment by smichr** [comment]
> Please cross reference the pull request here (and cross reference this issue on the pull request).

If you just write in your OP (opening paragraph) of the PR "closes #11378" it will automatically create a notation here in the issue and close the issue when the PR is closed. See, for example, how #11558 references the issue and then click on the blue text/link in its OP to go to the issue and look near the bottom to see how a cross reference to the PR was made. And if you click on the Issue's cross reference it will take you back to the PR.

**Comment by asmeurer** [comment]
@smichr you may be interested in this https://github.com/sympy/sympy/pull/11687

**Comment by E-DEA** [comment]
@asmeurer Is this issue open ? I would like to take it up if it is.
