### ISSUE TITLE
Matplotlib plotting isympy with OS X makes the GUI inaccessable

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#11399]
Whatever isympy is doing to enable matplotlib, it isn't the right thing. When I create a plot, I can't access the GUI. 

If I instead start IPython and run `%matplotlib`, and then import SymPy and plot things, it does the right thing. I can access the GUI.

**Comment by kritkaran94** [comment]
@asmeurer I am an OS X user. Could you please guide me how can I reproduce that same issue with a basic example.

**Comment by asmeurer** [comment]
Start `isympy` and try plotting something, and see if you can interact with the plot that pops up (try clicking the buttons).

**Comment by kritkaran94** [comment]
I started ``isympy`` and carried out the following steps. 

````
In [1]: from sympy import symbols

In [2]: from sympy.plotting import plot

In [3]: p1 = plot(x*x)

````
I was able to interact with the plot (by clicking the buttons). A few screenshots can also be seen.

**Original Plot**

![screen shot 2016-07-17 at 10 06 05 am](https://cloud.githubusercontent.com/assets/10063868/16898777/36915c74-4c06-11e6-8b72-17e25fd41792.png)

**After clicking the buttons**

![screen shot 2016-07-17 at 10 06 29 am](https://cloud.githubusercontent.com/assets/10063868/16898778/38a7633c-4c06-11e6-80ad-fa3ebbfb398d.png)

**Comment by kritkaran94** [comment]
@asmeurer This worked for me. Any other stuff to work in order to rectify this?

**Comment by asmeurer** [comment]
How did you install matplotlib? This could be related to the fact that I use conda.

**Comment by kritkaran94** [comment]
@asmeurer ``pip install matplotlib ```. Using the pip command I installed it earlier.

**Comment by mjeromin** [comment]
@asmeurer Is this still a problem? What version of conda are you running? I could not reproduce the issue and I was able to interact with the plot, but I'm also testing on Linux (sorry, no OS X). 
```
$ virtualenv sympy-ve
$ . sympy-ve/bin/activate
$ pip install --upgrade pip
$ pip install sympy matplotlib
$ isympy
...
>>> from sympy import symbols
>>> from sympy.plotting import plot
>>> p1 = plot(x*x)
```

**Comment by asmeurer** [comment]
@mjeromin this issue is very specific to OS X, and the way matplotlib interacts with its GUI system.

**Comment by asmeurer** [comment]
At any rate, this is working for me now, both with `conda-forge` packages and `defaults` packages. I suspect the problem was with the upstream conda packages.
