### ISSUE TITLE
diophantine: misclassification

### ISSUE THREAD

**Issue by smichr** [sympy/sympy#11418]
```python
>>> eq = x**2+y**2+z**4-(1+4+2**4)
>>> classify_diop(eq)
([x, y, z], {1: -21, y**2: 1, x**2: 1, z**4: 1}, 'general_sum_of_even_powers')
>>> diophantine(eq)
set([])
```

A check should be made that all powers are the same (not only that they are even).

**Comment by karthikkalidas** [comment]
I would like to work on this issue. Please guide me

**Comment by gorisaka** [comment]
It appears it is not checking even if they are even, but only if their sum is even.
```python
>>> eq = x**3 + y**3 + z**4 - (1 + 8 + 81)
>>> classify_diop(eq)
([x, y, z], {1: -90, y**3: 1, z**4: 1, x**3: 1}, 'general_sum_of_even_powers')
>>> diophantine(eq)
set()
```

Also, if the powers are supposed to be the same, I think the name `'general_sum_of_even_powers'` is very misleading.

**Comment by gorisaka** [comment]
The relevant file is sympy/solvers/diophantine.py. One could start by checking the function `classify_diop`.

@karthikkalidas Are you working on this issue or still want to?

Otherwise I would like to work on it.

**Comment by karthikkalidas** [comment]
No you go ahead!
