### ISSUE TITLE
Is it possible to use Sympy to generate Tensorflow graphs?

### ISSUE THREAD

**Issue by ataber** [sympy/sympy#11420]
I'm interested in using Sympy to add a symbolic layer to my Tensorflow graph generation code. I noticed that Tensorflow is mentioned in the wiki, but I'm not sure how to get the two to play well together. For instance, I tried 
```
import tensorflow as tf
from sympy.abc import x
f = x+2
f.as_poly()(tf.constant(1))
```
And I understandably get a domain error. Would getting this expression to work simply require implementing a new domain, or is it more involved?

**Comment by moorepants** [comment]
tensorflow and sympy do not work together. The wiki page you found is simply a list of software that implements some form of code generation. SymPy does interact with Theano, which is a similar software as tensorflow.

**Comment by ataber** [comment]
Makes sense. Would an implementation of a bridge like `theano_function` for Tensorflow be straightforward and welcome as a contribution?

**Comment by moorepants** [comment]
I'm not sure how straightforward it would be because I don't know anything much about tensorflow. But yes, a connector would be welcome. It may be as simple as defining the correct sympy-tensorflow mappings as we did for theano.

**Comment by ataber** [comment]
Gotcha! I'll take a stab at implementing it then. Thanks!

**Comment by yaroslavvb** [comment]
Theano/TensorFlow have similar structure, so TensorFlow graph converter could be done analogously to Theano graph converter. I wrote Theano graph->TensorFlow graph converter for an older version of TensorFlow and it was about 300 lines of Python -- https://gist.github.com/yaroslavvb/8d2853645b381342344d39a39e006905

It's probably easiest to work with GraphDef directly. If you have 1-1 correspondence between every sympy operation and some TensorFlow op, then the creating graph is just a straightforward translation. If some sympy op can't be implemented as a native TensorFlow op, then you'll need custom logic for those ops to create new subgraphs.

**Comment by yaroslavvb** [comment]
Actually, if it's just a matter of covering 45 ops that is done for Theano already then direct graph translation may be overkill and this can be done through TensorFlow Python API

**Comment by ataber** [comment]
The PR was merged in, so now it's possible to generate TF graphs from Sympy expressions in the following way:
```
import tensorflow as tf
from sympy.abc import x
from sympy import *
f = x+2
lambdify(x, f, "tensorflow")(tf.constant(1)) # returns a Tensor representing 1+2
```
I'll make a PR to add some documentation soon.

**Comment by danbri** [comment]
@ataber - is there more documentation coming?

**Comment by ataber** [comment]
Apologies, this got lost in my queue :) I'll do it tomorrow, shouldn't be much to document. I did write up a blog post containing some code snippets showing how I use this feature [here](https://medium.com/@awildtaber/computer-algebra-and-graphics-4fcb97836ee8#.be67cf79p), but that's not exactly documentation.

**Comment by arita37** [comment]
Hello,
Can't we just map with a dictionnary-style or graph style ?
    SymPy Tree  ---->    TensorFlow Tree (Code Generation)

TF_operation  <--->  Sympy Matrix Operation.
 tf.mult               <--->  
 tf.add                .....

**Comment by bionicles** [comment]
is it possible to make tensors with symbolic values? as opposed to symbolic expressions with tensor values, can we make a tensor of symbols?
