### ISSUE TITLE
The Poly class needs a useful doc string

### ISSUE THREAD

**Issue by moorepants** [sympy/sympy#11427]
At the terminal I get:

```
In [1]: Poly?
Init signature: Poly(rep, *gens, **args)
Docstring:      Generic class for representing polynomial expressions. 
File:           ~/miniconda3/lib/python3.5/site-packages/sympy/polys/polytools.py
Type:           ManagedProperties
```

which is pretty useless for determining how to initialize and use the class.

**Comment by souravsingh** [comment]
@moorepants I really want to work on this issue. How do I start?

**Comment by jksuom** [comment]
The docstring should refer to `Expr.as_poly` that is a user interface to `Poly`. Its docstring could be expanded as well. The meaning of various keywords should be explained.

**Comment by moorepants** [comment]
It wasn't really even clear to me how to create polynomials. The polynomial page on the sympy docs is also quite confusing. It has and "introduction to polynomials" but it is hardly an introduction, it doesn't even show how to create polynomials. Is the `.as_poly` method the preferred way to create polynomials?

**Comment by jksuom** [comment]
I think that `as_poly` was created for that purpose. I have recently expanded the introduction to `polys` in #11425, but that has not been merged yet.

**Comment by jksuom** [comment]
This [comment](https://github.com/sympy/sympy/pull/11370#issuecomment-233554159) contains some information on the meaning of some keywords.

**Comment by parsoyaarihant** [comment]
@souravsingh is the issue fixed?

**Comment by souravsingh** [comment]
@parsoyaarihant I am waiting for the PR #11425 to be merged before working on it

**Comment by shrutishrm512** [comment]
@moorepants I want to work on this issue. As of now, I think I can describe about what actually means like args and gens and in some methods , I can give examples like in revert method.
Since I am new,but I really want to work on this issue, so, can you please assign it to me?

**Comment by moorepants** [comment]
We don't really make use of Github's assign feature. If you want to work on it, simply state that in this thread and submit a pull request when you have something ready to for review (can be in draft state if you want early feedback).

**Comment by shrutishrm512** [comment]
OK! I want to work on this issue.

**Comment by shrutishrm512** [comment]
@moorepants I have again sent the pull request and it has cleared all the checks, then it can be merged into the main code?

**Comment by jtoka** [comment]
@moorepants seems that this ticket has been dead for a bit. I picked it up and considered your comments. Please take a look when you have a chance.
