### ISSUE TITLE
str printing of logic expressions should use operators

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#11435]
Currently:

```
In [5]: print(And(Not(x), Or(y, z)))
And(Not(x), Or(y, z))
```

But it would be better for the str printer (and non-Unicode pretty printer) to use `~`, `&`, and `|`, like `~x & (y | z)`. 

This should be easy to fix, although you need to make sure the parenthesization is correct.

**Comment by parsoyaarihant** [comment]
I am working on it. Any tips are welcome :)

**Comment by jhsong111** [comment]
I found that ccode function can perform similar function. 
```
sympy.printing.ccode(Or(A, B))
A || B 
```
So, this issue can be resolved quickly. Thanks

**Comment by asmeurer** [comment]
ccode uses C operators, but the str printer should use Python operators (single `|` instead of `||`). Also, ccode will print all subexpressions as C code, which may not be desired.

**Comment by lopezdp** [comment]
Where can i find the file for this line of code?

**Comment by aheyman11** [comment]
Hi, I'm a new contributor interested in working on this issue. I think that I should be able to fix it, and I've read through the previous pull request and understand why that approach did not work.

**Comment by parsoyaarihant** [comment]
hi @aheyman11 , you can go ahead if you have fix for the bug.

**Comment by aheyman11** [comment]
Thanks @parsoyaarihant, working on it now.

**Comment by ShivramIITG** [comment]
@asmeurer  @parsoyaarihant 
Is this still open ? Can i work on this ? Kindly help me getting started,i am new here

**Comment by ritvikraj14** [comment]
I want to work on this.  Kindly let me know if this is still open?

**Comment by SagarB-97** [comment]
@asmeurer 
Please review PR #12108.
./bin/test and Travis CI tests are failing because the assert statements require the old printing formats.
What should I do?

**Comment by asmeurer** [comment]
You should change the tests that tested against the old format to test against the new format. Also be sure to run `./bin/doctest` as generally when the printer changes you need to change several of those.

**Comment by SagarB-97** [comment]
@asmeurer 
Thanks! I'll do that!

**Comment by SagarB-97** [comment]
@asmeurer 
Does Travis CI use the updated test files for approving build?

**Comment by asmeurer** [comment]
Yes. Travis tests against the files in your branch.
