### ISSUE TITLE
Simplify acos(x)+asin(x) to pi/2

### ISSUE THREAD

**Issue by michaeldongyuxi** [sympy/sympy#11446]
Is there any way to Simplify acos(x)+asin(x) to pi/2 ? I tried simplify, trigsimp, expand_trig, none of them seem to work.

**Comment by jksuom** [comment]
You can rewrite the functions in terms of each other.
```
>>> (acos(x) + asin(x)).rewrite(acos)
pi/2
>>> (acos(x) + asin(x)).rewrite(asin)
pi/2
```

**Comment by michaeldongyuxi** [comment]
Awesome!
