### ISSUE TITLE
parse_expr(u'Abs(x+x)' , evaluate=False) reduces to 2*Abs(x).  For me this is very bad

### ISSUE THREAD

**Issue by MrDarkHorse** [sympy/sympy#11441]
I'm dealing with significant digits, so I NEVER want the expression to reduce itself.  Using parse_expr is generally what I need, but when I throw Abs into the mix, it goes haywire.

This is also the case when I attempt to substitute my own abs function using the global_dict.

**Comment by kritkaran94** [comment]
@asmeurer How to work on this issue?

@MrDarkHorse Could you please give an example.

**Comment by MrDarkHorse** [comment]
My example is in the title.

y = parse_expr(u'Abs(x+x)' , evaluate=False)

This expression "Abs(x+x)" is parsed as "2*Abs(x)"
Specifically, if you call print_tree(y), it shows:
```
Mul: 2*Abs(x)
+-Integer: 2
+-Abs: Abs(x)
```

Whereas, I would expect it to parse as "Abs(x+x)", with an abstract Syntax tree that looks like this:
```
Abs: Abs(x + x)
+-Add: x + x
| +-Symbol: x
| +-Symbol: x
```


While the 2 expressions are mathematically equivalent, they produce different results when significant digits are introduced.  I can get into a discussion about how significant digits work, but that is beside the point.  In every other case, except for when the Abs function is introduced into an expression, the parse_expr leaves the expression syntax tree alone.  But for some reason, when the Abs function is used, parse_expr behaves more like the sympify function, and reduces the original expression.

**Comment by kritkaran94** [comment]
Thanks a lot for the detailed explanation. I am working on this issue.

**Comment by MrDarkHorse** [comment]
Any update on this?

**Comment by kritkaran94** [comment]
I apologize I haven't made any progress on this yet.

I will keep you updated.
