### ISSUE TITLE
mpmath import issue

### ISSUE THREAD

**Issue by chan-y-park** [sympy/sympy#11453]
I just installed conda 4.1.6 on Ubuntu 16.04, where sympy 1.0 is contained. Then I tried
```
>>> import sympy.mpmath as mpmath
```
But I got
```
>>> ImportError: No module named mpmath
```
Whereas when I run
```
>>> from sympy import mpmath
```
It works without a problem.

When I use sympy 0.7.6 both works fine. Is this a bug, or am I doing something wrong?

**Comment by gorisaka** [comment]
Versions of sympy prior to 1.0 included mpmath, now it is an external dependency.
(http://docs.sympy.org/latest/install.html#mpmath)
(PR #8856)

So ```import sympy.mpmath``` is expected to fail from 1.0.
I think ```from sympy import mpmath``` should also fail, so it appears to be a minor bug.

`mpmath` is imported in sympy/\__init\__.py only to test if the module is available and should not be exposed.

**Comment by moorepants** [comment]
Seems like this should have had a deprecation warning if it was an existing public api. Mabye 0.7.7 did have one, but jumping from 0.7.6 6 to 1.0 skips that warning.

**Comment by chan-y-park** [comment]
Thanks for your help! I dropped using sympy.mpmath and started using mpmath directly and everything works. It would indeed be great if such a deprecation warning is printed. I will close this issue, then.
