### ISSUE TITLE
AttributeError: 'bool' object has no attribute 'subs' 

### ISSUE THREAD

**Issue by lucidbee** [sympy/sympy#11477]
I am writing an evaluator for a language. The expressions and values are run through sympy for evaluation. In my language I can have something like 
  'if x == true' 
Instead of using the test "x == true" I use just "x" and I can evaluate with values True or False:
>>> from sympy import *
>>> x = Symbol('x')
>>> x.subs({x:True})
True

This is what I want.
However this does not work for 'if x == false'
When I use 'not x' I get an AttributeError:
>>> x = Symbol('x')
>>> expr = not x
>>> expr.subs({x:True})
AttributeError: 'bool' object has no attribute 'subs'

How can I implement this case? Or is it a bug?

**Comment by gorisaka** [comment]
The result of `not x` is a python bool and not a sympy expression. For what you want, I think you should use the logical function Not from sympy.

```python
>>> from sympy import *
>>> x = symbols('x')
>>> expr = Not(x)
>>> expr.subs({x: True})
False
>>> expr.subs({x: False})
True
```

For more information on the sympy logics module:
http://docs.sympy.org/latest/modules/logic.html

**Comment by lucidbee** [comment]
Thanks for the awesomely fast and helpful answer!! Fixed my problem.
