### ISSUE TITLE
coeff() needs expand()

### ISSUE THREAD

**Issue by nschloe** [sympy/sympy#11475]
When trying to find a coefficient of a variable in an expression, that expression always has to be expanded. Consider, e.g.,
``` python
import sympy
x = sympy.Symbol('x')
a = sympy.Symbol('a')

f = a*(x + 7)
print(f.coeff(x, n=0))
```
You'd expect `7*a`, but the result is `0`. This
```python
print(f.expand().coeff(x, n=0))
```
works better.

**Comment by oscarbenjamin** [comment]
I think coeff is a low-level operation. If you want to use that then you need to put the expression in the right form using other low-level operations.

I'm not sure what's a better way to do this than expanding though...

**Comment by smichr** [comment]
duplicate of #7195, basically
