### ISSUE TITLE
Pell equations

### ISSUE THREAD

**Issue by ranea** [sympy/sympy#11486]
I'm trying to solve pell equations with sympy.

However, I get some bad results.

For example, let d=2, n=-9.

```
>>> diop_DN(2, -9)
[(3, 3)] 

>>> diop_bf_DN(2, -9)
[(3, 3)] 
```

But (3,3) isn't a solution!

```
3^2 + 9 * 3^2 != 2
```

Is there something about the Diophantine module that I am missing?

Thanks.

**Comment by jksuom** [comment]
The equation is `x^2  - d*y^2 = n`, or, explicitly, `x^2 - 2*y^2 = -9`.

**Comment by mzaffalon** [comment]
Should this issue not be closed?

**Comment by thilinarmtb** [comment]
Since the issue is resolved, I suggest closing this too.

**Comment by thilinarmtb** [comment]
Thanks !!
