### ISSUE TITLE
Not converting floats to rationals in sympy.geometry objects

### ISSUE THREAD

**Issue by BebeSparkelSparkel** [sympy/sympy#11484]
For performance reasons I need to be able to turn off the conversion from floats to rational numbers for sympy.geometry objects.
The Point class has the ability to set evaluate=False. It would be good if all geometry could set evaluate to False, but at least the class sympy.geometry.ellipse.Circle .

**Comment by siefkenj** [comment]
@BebeSparkelSparkel pull requestion #11241 should be a step in this direction.  It prevents existing points from being turned into points again and thus being resimplified.

**Comment by smichr** [comment]
duplicates #4748
