### ISSUE TITLE
ReferenceFrame.orient() needs an option to pass in the rotation matrices manually.

### ISSUE THREAD

**Issue by moorepants** [sympy/sympy#11498]
For example:

```python
>>> A = ReferenceFrame('A')
>>> B = ReferenceFrame('B')
>>> A.orient(B, 'DCM', eye(3))
>>> A.dcm(B)
Matrix([[1, 0, 0],
[0, 1, 0],
[0, 0, 1]])
```

Currently there is no clean way to set rotation matrices manually.

**Comment by souravsingh** [comment]
@moorepants I would like to work on this. How do I start?

**Comment by Chandak01** [comment]
I'm new to opensource and want to contribute to this,could you help me how to approach this problem and where to start

**Comment by moorepants** [comment]
I would suggest writing some unit tests in the sympy/physics/vector/tests/test_frame.py showing the desired functionality.

**Comment by Chandak01** [comment]
I would appreciate if it could be debugging task,as I've no idea about setting the test cases currently

**Comment by souravsingh** [comment]
Thanks for the advice @moorepants

**Comment by nikoskaragiannakis** [comment]
I think I can help with this.
