### ISSUE TITLE
ENH: stats: add multinomial distribution

### ISSUE THREAD

**Issue by dr-leo** [sympy/sympy#11499]
Hi,

I am new to sympy. Having played around a bit with some of its great concepts, I wonder why stats Features Binomial but not Multinomial Distribution. Adding this would be a low hanging fruit as multinomial_coefficient is already contained in ntheory.

I did a quick and dirty hack. As it would take some time though to prepare a PR, I wonder if there is Appetite at all in this Feature.

Leo

**Comment by sidhantnagpal** [comment]
Closing, as per https://github.com/sympy/sympy/pull/11516#issuecomment-493065194.
