### ISSUE TITLE
Move check_assumptions into the main namespace

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#11505]
sympy.solvers.check_assumptions checks if the given assumptions match a value. We should move that into the main namespace. It may also be useful to have a variant that checks a value against a variable/expression (the equivalent of `check_assumptions(val, **expr.assumptions0)`). Or maybe we just need to document that.

**Comment by asmeurer** [comment]
Another idea: once ask works with Eq better, you could just do `ask(Eq(Symbol('x', negative=True), 3))`. So one way to fix this would be to just improve ask Eq support, and document that you can check assumptions by `ask`ing an `Eq`.

**Comment by prateekg** [comment]
Hi, can you please brief me about the issue ?

**Comment by parsoyaarihant** [comment]
@asmeurer , I submitted PR #11509 for this issue. However, I am unclear about
> variant that checks a value against a variable/expression

Could you elaborate on that through an example?

**Comment by asmeurer** [comment]
I mean something like `check_assumptions(-1, Symbol('x', negative=True))`.

**Comment by prateekg** [comment]
Hi, when you say that " Move check_assumptions in main namespace", what actually you mean to say? Please help me this.

**Comment by asmeurer** [comment]
I mean to add it to `__init__.py`, or add an equivalent function to `__init__.py`. Or another option would be to add it as a method of Expr.

**Comment by zwaltman** [comment]
@asmeurer, do you mean check_assumptions should just be moved from solvers/solvers.py to solvers/__init__.py? Looking at the __init__.py for other packages, none of them seem to contain functions... Do we want to make this an exception, or is there something I'm missing?

**Comment by asmeurer** [comment]
@zwaltman I mean to add an import for it to `__init__.py`, so that `from sympy.solvers import check_assumptions` (and hence `from sympy import check_assumptions`) works.

**Comment by zwaltman** [comment]
@asmeurer Gotcha, thanks! Created a pull request with the addition.

**Comment by asmeurer** [comment]
https://github.com/sympy/sympy/pull/11509
