### ISSUE TITLE
import errors Version 1.0

### ISSUE THREAD

**Issue by pbender3469** [sympy/sympy#11515]
I am getting the following error when I try to import the mechanics module from sympy version 1.0
```
import sympy.physics.mechanics as me

ImportError                               Traceback (most recent call last)
<ipython-input-9-1fcf14bc4e58> in <module>()
      1 import sympy as sym
----> 2 import sympy.physics.mechanics as me

c:\python27\lib\site-packages\sympy\physics\mechanics\__init__.py in <module>()
     12 #    "from sympy.physics.mechanics import *" is done.
     13 
---> 14 from . import kane
     15 from .kane import *
     16 __all__.extend(kane.__all__)

c:\python27\lib\site-packages\sympy\physics\mechanics\kane.py in <module>()
      4 
      5 from sympy import zeros, Matrix, diff, solve_linear_system_LU, eye
----> 6 from sympy.core.compatibility import range
      7 from sympy.utilities import default_sort_key
      8 from sympy.physics.vector import (ReferenceFrame, dynamicsymbols,

ImportError: cannot import name range
```
Thanks for any help.

Phil Bender

**Comment by bjodah** [comment]
Strange, I don't see this
```
$ git checkout sympy-1.0
$ python -c "import sympy.physics.mechanics as me"
$ git checkout master
$ python -c "import sympy.physics.mechanics as me"
```
no error messages

**Comment by pbender3469** [comment]
Thanks for getting back to me.

The error went away after I installed the Anaconda distribution.






Sent with MailTrack
<https://mailtrack.io/install?source=signature&lang=en&referral=pbender3469@gmail.com&idSignature=22>

**Comment by bjodah** [comment]
I can't reproduce this in my anaconda installation either.
Is `c:\python27` the location of your anaconda installation?
I have had problems with anaconda environments picking up user site packages, setting the environment variable `PYTHONNOUSERSITE=1` helped me (on linux though).

**Comment by asmeurer** [comment]
Perhaps you had a stale pyc file somewhere. 

I'm closing this, but please reopen if you see it again.
