### ISSUE TITLE
_sqrt_mod_prime_power factors argument unnecessarily

### ISSUE THREAD

**Issue by schoen** [sympy/sympy#11512]
I just used `ntheory.residue_ntheory._sqrt_mod_prime_power` successfully (thanks!), but I was using a very large value for `a` and I had to comment out the line that attempts to factor `a` in order to get the process to complete in a reasonable time:

https://github.com/sympy/sympy/blob/master/sympy/ntheory/residue_ntheory.py#L415

I think this `f = factorint(a)` may have been copy and pasted from another implementation in this file, or perhaps left over from an earlier algorithm. As far as I can see, the factorization `f` is simply not used at all for any purpose in this function, so computing it simply makes `_sqrt_mod_prime_power` slower to no benefit!

**Comment by jksuom** [comment]
It seems that `f = factorint(a)` was left over from an earlier implementation by mistake. It was originally introduced in https://github.com/sympy/sympy/commit/e0e0a182d7edff485f7fce6645a50f1735832988#diff-d43e7fc1bd11e75f0bc7baf255de6605R298 as an easy (but wasteful) way to find the exponent of the prime `p` in `a`. It was later found out that the idea was wrong and the code using the exponent was removed (https://github.com/sympy/sympy/commit/4a1914af0379a59010ed5119390d3f07cf643f90#diff-d43e7fc1bd11e75f0bc7baf255de6605L299). However, the useless `factorint` call was forgotten.

Please, send in a PR for the removal of this line.

**Comment by yash-reddy** [comment]
I'd like to work on it. Any advice would be welcome

**Comment by yash-reddy** [comment]
removed the line and created a PR (#11513)

**Comment by jksuom** [comment]
Thank you, @schoen, for pointing out this.
