### ISSUE TITLE
Exponent doesn't fully simplify

### ISSUE THREAD

**Issue by michaeldong21** [sympy/sympy#11518]
Say I have code like this:

```
import sympy
from sympy import *
x=Symbol('x')
expr1 = S(1)/2*x**2.5
expr2 = S(1)*x**(S(5)/2)/2
res = expr1-expr2
res= simplify(res.evalf(5))
print res
```

The output is
`-0.5*x**2.5 + 0.5*x**2.5`
How do I simplify it to 0?

**Comment by michaeldong21** [comment]
However N() works
im```
port sympy
from sympy import *
x=Symbol('x')
expr1 = S(1)/2*x**2.5
expr2 = S(1)*x**(S(5)/2)/2
res = expr1-expr2
res= simplify(N(res), 5)
print res
```
output:
`0`

**Comment by asmeurer** [comment]
A strange bug. The floating point numbers appear to be identical:

```
In [30]: expr2.evalf(5).args[1].args[1]._mpf_
Out[30]: (0, 5, -1, 3)

In [31]: expr1.evalf(5).args[1].args[1]._mpf_
Out[31]: (0, 5, -1, 3)

In [32]: expr1.evalf(5).args[0]._mpf_
Out[32]: (0, 1, -1, 1)

In [33]: expr2.evalf(5).args[0]._mpf_
Out[33]: (0, 1, -1, 1)
```

It also works if you use the default precision:

```
In [27]: expr1.evalf() - expr2.evalf()
Out[27]: 0

In [28]: (expr1 - expr2).evalf()
Out[28]: 0
```

**Comment by ylemkimon** [comment]
@asmeurer It seems that 2.5 from expr1 is Float('2.5', precision=53) which has default precision(53) and 2.5 from evalf-ed expr2 is Float('2.5', precision=20), so although their _mpf_ is identical, their hash of x**2.5 is different.
As a result, Add fails to see them as same term in https://github.com/sympy/sympy/blob/master/sympy/core/add.py#L188.

I think this issue can be solved by one of following ways:
1. Implement custom hash function for Float using _mpf_
2. Implement custom term compare for Float in Add
