### ISSUE TITLE
[tensor] TensAdd ignores all but one scalar argument

### ISSUE THREAD

**Issue by peterstangl** [sympy/sympy#11525]
If a `TensAdd` instance is formed by the sum of fully contracted tensors (i.e. `TensMul` instances with an empty list as the `free_args` attribute) and scalars (usual sympy symbols), `TensAdd` ignores all but the last scalar in the sum.

Consider the following example:
```python
>>> import sympy.tensor.tests.test_tensor as test_tensor
>>> (A, B, AB, BA, C, Lorentz, E, px, py, pz, LorentzD, mu0, mu1, mu2, ndm, n0, n1,
...     n2, NA, NB, NC, minkowski, ba_matrix, ndm_matrix, i0, i1, i2, i3, i4
... ) = test_tensor._get_valued_base_test_variables()
>>> expr1 = A(i0)*A(-i0) - (E**2 - px**2 - py**2 - pz**2)
>>> expr2 = E**2 - px**2 - py**2 - pz**2 - A(i0)*A(-i0)
>>> expr3 = A(i0)*A(-i0) - E**2 + px**2 + py**2 + pz**2
```
The scalar addends in `expr1` and `expr2` are treated as a single argument of `TensAdd` and no problem appears:
```python
>>> expr1.args
(-E**2 + px**2 + py**2 + pz**2, A(Lorentz_0)*A(-Lorentz_0))
>>> expr2.args
(E**2 - px**2 - py**2 - pz**2, -A(Lorentz_0)*A(-Lorentz_0))
```
This is different in `expr3`, where only the last scalar addend is considered:
```python
>>> expr3.args
(pz**2, A(Lorentz_0)*A(-Lorentz_0))
```
The same problem also appears with multiple tensor arguments:
```python
>>> expr4 = C(mu0)*C(-mu0) + 2*E**2 - 2*px**2 - 2*py**2 - 2*pz**2 - A(i0)*A(-i0)
>>> expr4.args
(-2*pz**2, -A(Lorentz_0)*A(-Lorentz_0), C(LorentzD_0)*C(-LorentzD_0))
```

**Comment by Upabjojr** [comment]
Oh, this is a serious bug. I have never noticed it.

**Comment by Upabjojr** [comment]
@peterstangl do you feel like trying to fix this bug? It should be in `TensAdd.__new__`.
