### ISSUE TITLE
ASCII printing for Singularity Function.

### ISSUE THREAD

**Issue by sampadsaha5** [sympy/sympy#11524]
Implementation of ASCII printing for Singularity Functions is needed.

**Comment by kritkaran94** [comment]
@sampadsaha5 I would like to work on this. Can you please tell me how to start ?

**Comment by sampadsaha5** [comment]
@kritkaran94 You can look into pretty printing module and figure out how to print Singularity Functions in the case of `use_unicode=False`.

**Comment by Nitin216** [comment]
@sampadsaha5 Could u give an example. I am not able to understand. Thank You.

**Comment by parsoyaarihant** [comment]
@kritkaran94 , is the issue fixed?

**Comment by kritkaran94** [comment]
@parsoyaarihant Working on it buddy :)

**Comment by parsoyaarihant** [comment]
@kritkaran94 , any update?

**Comment by kritkaran94** [comment]
@parsoyaarihant You can work on this issue Bro. Little busy with other stuff. Sorry, for making you wait.

**Comment by parsoyaarihant** [comment]
Thanks :)
