### ISSUE TITLE
ITE(x, True, False) should auto simplify to x

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#11530]
```
In [13]: ITE(x, True, False)
Out[13]: ITE(x, True, False)
```

It works if you call `to_nnf()`, but it should auto-simplify.  The same with `ITE(x, False, True)` (should simplify to `Not(x)`).

**Comment by parsoyaarihant** [comment]
I am working on it.

**Comment by Chandak01** [comment]
I'm new to opensource and want to contribute in this,could you help me how to approach this problem and where to start

**Comment by kshitij10496** [comment]
@Chandak01 
I think this issue already fixed.
Feel free to work on other "Easy to Fix" issues

**Comment by asmeurer** [comment]
This was fixed by https://github.com/sympy/sympy/pull/11535
