### ISSUE TITLE
Bug in solve maybe

### ISSUE THREAD

**Issue by miketheanimal** [sympy/sympy#11538]
With python 3.4.2, Sympy 1.0:

```
mike@quaking:~/solver/client/app$ pip3 list | grep -i sympy
sympy (1.0)
mike@quaking:~/solver/client/app$ python3
Python 3.4.2 (default, Oct  8 2014, 10:45:20) 
[GCC 4.9.1] on linux
```

If I run the following script

```
import sympy
import math
x, y = sympy.symbols('x y')
e1 = x - y**3 + 4
e2 =  x + y + 4 + 4 * sympy.E
e3 =  x + y + 4 + 4 * math.e
print ("with sympy.E:", sympy.solve([e1, e2], x, y))
print ("with math.e :", sympy.solve([e1, e3], x, y))
```

then I get:

```
mike@quaking:~/solver/client/app$ python3 /tmp/s.py 
with sympy.E: []
with math.e : [(-12.8079458780453, -2.06518143579091), (-15.9057180317317 - 2.04908046988193*I, 1.03259071789545 + 2.04908046988193*I), (-15.9057180317317 + 2.04908046988193*I, 1.03259071789545 - 2.04908046988193*I)]
```

Granted sympy.E and math.e are not the same thing, its odd that in the former case sympy says there are no solutions, and in the second that there are three (which looks plausible since there is a cube term.

Regards
Mike

**Comment by Finite-Programming** [comment]
I tried e2 =  x + y + 4 + 4 * sympy.pi with same result. Workaround was adding evalf() to the end.

e2 =  x + y + 4 + 4 * sympy.E.evalf()

**Comment by cttefer** [comment]
After more investigation: Python doesn't evaluate sympy.E or other NumberSymbol objects like it evaluates math.e. Currently neither Poly nor DMP evaluate their coefficients when NumberSymbol is involved. So, for the developers, should we evaluate NumberSymbol within DMP/Poly or should we provide a native function to the NumberSymbol class that allows Python to evaluate the value like a constant?

**Comment by miketheanimal** [comment]
Back with my original, if i do:

x, y, k = symbols('x y k')
e1 = x - y**3 + 4
e2 =  x + y + 4 + 4 * k
solve([e1, e2], x, y)

then I get (after several seconds, and omitting most of the 1200 or so characters) :

    [((-4*(k + 1)*(18*k + sqrt(324*k**2 + 3)) .......]

so the result is a function of the variable k. So, if instead of k i put E, I'd at least expect to get the same result but with k replaced by E.

So answering ctefer, I'd like 4*E to display as 4*E, since that is the exact answer (ie., sympy.E *is* e), whereas with 4*math.e i'm happy with 10.87312731383618 because I know that math.e is only an approximation.

**Comment by ctefer** [comment]
I think this is correct as well. Pardon my ignorance as I'm new to this system, but in keeping with the sympy philosophy that symbols are treated as symbols and never reduced to their approximate values, shouldn't NumberSymbol be also treated as a symbol? 

I believe this issue may actually be caused by:

> >>x = symbols('x')
> >>x.free_symbols
> {x}
>
> >>from sympy import E
> >>E.free_symbols
>{}

**Comment by ctefer** [comment]
I think I figured it out. I noticed a bad tab spacing around sympy/poly/polyroots.py line 1012

**Comment by jksuom** [comment]
It seems that `E` should be treated as a symbol in `polys`. It is not implemented that way currently, but can be effected by specifying the coefficient domain as a hint.  As `solve` doesn't currently pass the hints to `solve_poly_system`, the latter function has to be called directly: 

`solve_poly_system([e1, e2], x, y, domain=ZZ{E])`

These deficiencies should probably be fixed.

**Comment by ctefer** [comment]
In the constructor we could set it up so NumberSymbols are considered instead of just "is_number"

```
       for gen in gens:
            if gen.is_number:
                if gen.is_NumberSymbol:
                    continue
                return None # generators are number-like so lets better use EX
            
        #if any(gen.is_number for gen in gens):
        #    return None # generators are number-like so lets better use EX
```

**Comment by jksuom** [comment]
This is plausible, but there may be a problem. Not all number symbols are algebraically independent and therefore acceptable as generators in a coefficient ring.  `GoldenRatio` is also a number symbol, and it is algebraic.

**Comment by ctefer** [comment]
`GoldenRatio` seems to be the only current NumberSymbol that has this problem. Also, I ran something similar to the initial issue that I think is interesting. This makes me think that even though `Golden Ratio` is called algebraic, I'm wondering if it's implemented correctly.

I would ignore the timeout and assume that it's coming back with numbers. I ran this from the browser shell.
```
Python console for SymPy 1.0 (Python 2.7.5)

These commands were executed:
>>> from __future__ import division
>>> from sympy import *
>>> x, y, z, t = symbols('x y z t')
>>> k, m, n = symbols('k m n', integer=True)
>>> f, g, h = symbols('f g h', cls=Function)

>>> e1 = x**2 + y + 1
>>> e2 = x + y**2 + k
>>> e3 = x + y**2 + E
>>> e4 = x + y**2 + GoldenRatio
>>> solve([e1,e2], x, y)
Error: Operation timed out.
>>> solve([e1,e3], x, y)
[]

>>> solve([e1,e4], x, y)
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/base/data/home/apps/s~sympy-live-hrd/46.393464279709602171/sympy/sympy/solvers/solvers.py", line 1055, in solve
    solution = _solve_system(f, symbols, **flags)
  File "/base/data/home/apps/s~sympy-live-hrd/46.393464279709602171/sympy/sympy/solvers/solvers.py", line 1662, in _solve_system
    poly = g.as_poly(*symbols, extension=True)
  File "/base/data/home/apps/s~sympy-live-hrd/46.393464279709602171/sympy/sympy/core/basic.py", line 697, in as_poly
    poly = Poly(self, *gens, **args)
  File "/base/data/home/apps/s~sympy-live-hrd/46.393464279709602171/sympy/sympy/polys/polytools.py", line 89, in __new__
    return cls._from_expr(rep, opt)
  File "/base/data/home/apps/s~sympy-live-hrd/46.393464279709602171/sympy/sympy/polys/polytools.py", line 200, in _from_expr
    return cls._from_dict(rep, opt)
  File "/base/data/home/apps/s~sympy-live-hrd/46.393464279709602171/sympy/sympy/polys/polytools.py", line 144, in _from_dict
    domain, rep = construct_domain(rep, opt=opt)
  File "/base/data/home/apps/s~sympy-live-hrd/46.393464279709602171/sympy/sympy/polys/constructor.py", line 238, in construct_domain
    result = _construct_simple(coeffs, opt)
  File "/base/data/home/apps/s~sympy-live-hrd/46.393464279709602171/sympy/sympy/polys/constructor.py", line 45, in _construct_simple
    domain, result = _construct_algebraic(coeffs, opt)
  File "/base/data/home/apps/s~sympy-live-hrd/46.393464279709602171/sympy/sympy/polys/constructor.py", line 93, in _construct_algebraic
    g, span, H = primitive_element(exts, ex=True, polys=True)
  File "/base/data/home/apps/s~sympy-live-hrd/46.393464279709602171/sympy/sympy/polys/numberfields.py", line 857, in primitive_element
    f = minpoly(ext, y)
  File "/base/data/home/apps/s~sympy-live-hrd/46.393464279709602171/sympy/sympy/polys/numberfields.py", line 657, in minimal_polynomial
    result = _minpoly_compose(ex, x, dom)
  File "/base/data/home/apps/s~sympy-live-hrd/46.393464279709602171/sympy/sympy/polys/numberfields.py", line 578, in _minpoly_compose
    raise NotAlgebraic("%s doesn't seem to be an algebraic element" % ex)
NotAlgebraic: GoldenRatio doesn't seem to be an algebraic element
```

**Comment by jksuom** [comment]
That must be a bug.
