### ISSUE TITLE
Solution of 0**x + a should be EmptySet

### ISSUE THREAD

**Issue by kshitij10496** [sympy/sympy#11536]
There is some discrepancy in the behaviour of `0**x` and the solving technique for the following equations in solveset:

``` python
In []: solveset(0**x - 1, x, S.Reals)
Out[]: {0} # correct result

In []: solveset(0**x - 100, x, S.Reals)
Out[]: {0} # should be EmptySet 

In []: solveset(0**x + 100, x, S.Reals)
Out[]: {0} # should be EmptySet

In [17]: solve(0**x - 100, x) # raises NotImplementedError
```

**Comment by nikoskaragiannakis** [comment]
SymPy 1.0 returns
```python
ConditionSet(x, Eq(0**x - 100, 0), Complexes((-oo, oo) x (-oo, oo), False))
```
Which version of SymPy are you using?

**Comment by Yathartha22** [comment]
I agree with you @kshitij10496. Should it be fixed? If so I would like to work on it.

**Comment by kshitij10496** [comment]
> Should it be fixed? If so I would like to work on it.

Yes, it needs to be fixed. 

The function `0**x` is a transcendental function.
For now, I would suggest we prevent `solveset` from returning an incorrect solution by returning a `ConditionSet` object instead. 
However, this case needs to be addressed in the future while implementing `transolve`.

**Comment by kshitij10496** [comment]
@nikoskaragiannakis I think you might have confused between `solve` and `solveset` here.
In spite of that, I agree with you that `solveset` works fine in the `S.Complexes` domain.
However, the issue here is that an incorrect solution is returned in case of real domain.

```python
In []: solve(0**x - 100, x) # raises NotImplementedError

In []: solveset(0**x - 100, x)
Out[]: ConditionSet(x, Eq(0**x - 100, 0), Complexes((-oo, oo) x (-oo, oo), False)) # correct answer in Complex domain

In []: solveset(0**x - 100, x, S.Reals)
Out[]: {0} # wrong result in the Real domain
```

**Comment by Yathartha22** [comment]
@kshitij10496 I could fix this to return `ConditionSet` for time being.
Right now I am trying to study `solve's` transcendental eq solver. Also looking forward to contribute in `transolve` in future.

**Comment by Yathartha22** [comment]
@kshitij10496 could you help me, how do I check that this eq has to return a `ConditionSet`. 
At first I thought to just check that if it a transcendental type equation, if so then it would return `ConditionSet`.
But there are some eqs like : `3**x - 100` that would return `{log(100)/log(3)}` which is correct.
So how would I differentiate between the latter and the former equations to return a `ConditionSet`.

**Comment by Yathartha22** [comment]
@kshitij10496 I was thinking to use `checksol` to check whether the the result satisfies the given eq `f`, but many tests were failing, I implemented it in line 692 of `solveset` module.
```
chk = checksol(f, symbol, rhs_s.args[0])
            if not chk:
                result = ConditionSet(symbol, f, domain)
```
I guess its not the right place to use `checksol` or is there any other way to implement

**Comment by kshitij10496** [comment]
Checking for the solution inside `_solveset` won't exactly address this behavior.
I would suggest you fix this by adding checks inside `invert_real` function.

**Comment by Shekharrajak** [comment]
These are indeterminate forms : 

```
In [1]: 0**0
Out[1]: 1 # must be nan

In [2]: oo/oo
Out[2]: nan

In [3]: 0/0
---------------------------------------------------------------------------
ZeroDivisionError                         Traceback (most recent call last)
<ipython-input-3-6549dea6d1ae> in <module>()
----> 1 0/0

ZeroDivisionError: division by zero # must be nan

In [4]: 0*oo
Out[4]: nan

In [5]: oo-oo
Out[5]: nan

In [6]: 1**oo
Out[6]: nan

In [7]: oo**0
Out[7]: 1 # must be nan

```

So [0**x  - 1 = 0 for x ](http://www.wolframalpha.com/input/?i=0**x++-+1+%3D+0+for+x) should return no solution. Right ?

**Comment by Yathartha22** [comment]
We can have a look [here](https://math.stackexchange.com/questions/11150/zero-to-the-zero-power-is-00-1)

**Comment by Yathartha22** [comment]
Then I guess, we should return no solutions for `0**x + a` type equations, because 

`x = log(a)/log(0)`
and `log(0)` is undefined.

**Comment by kshitij10496** [comment]
@jksuom @asmeurer 
As @Shekharrajak mentioned above,`0**0` returns `1`.
Is this by design or a bug?

**Comment by Yathartha22** [comment]
I have found an interesting [answer](https://stackoverflow.com/questions/14414430/why-0-0-equals-1-in-python) as well as the [wiki link](https://en.wikipedia.org/wiki/Exponentiation#Zero_to_the_power_of_zero) that might be able to answer our question.
Since python too evaluates `0**0` to `1`, might be possible that `sympy` is made to do the same.
I guess it may help.

**Comment by jksuom** [comment]
It seems to be by design in the current implementation. But I think that nan would be more consistent with the way powers with special base or exponent are defined in the docstring of `Pow`.

The idea is that `0**0` should be the limit of `x**y` when `x` and `y` tend to 0. The function `x**x` has limit 1 at `x = 0`. However, `x**y` has no limit at `(x, y) = (0, 0)` as a function of two variables. In fact, it is possible to find functions `f(t)` and `g(t)` both tending to 0 as `t -> 0` such that `f(t)**g(t)` has limit different from 1 or no limit at all. (There are examples in the wiki article referred to above.)
