### ISSUE TITLE
Solve only work after evalf()

### ISSUE THREAD

**Issue by Huyston** [sympy/sympy#11565]
In some cases solve doesn't not solve the equation correctly, returning [].
If the same equation is evaluated (using evalf()), then solve gives the right solution.

An example of this issue is posted in https://gist.github.com/Huyston/4035351b8738464019895db23f0688ae

**Comment by jksuom** [comment]
This is a quintic equation for which there is no algebraic solution with radicals. Only numeric solution with numeric coefficients is possible, in general.

**Comment by nikoskaragiannakis** [comment]
I think sympy has solvers for quintic equations, provided these equations are solvable. Maybe applying something [some criteria](https://en.wikipedia.org/wiki/Quintic_function) in solve could be helpful.

**Comment by Huyston** [comment]
I see, you are right.
I was wondering if it should raise an error or something to inform the user about this. Maybe a "No algebraic solution error" try using .evalf().
I'll close it since it's not sympy's fault :)
Thanks.
