### ISSUE TITLE
Log simplification and comparison doesn't  match on positive symbols

### ISSUE THREAD

**Issue by Zaharid** [sympy/sympy#11563]
I would expect the following equality test to be True (and more generally to always be the case that `simplify(X) == X`)

``` python
from sympy import *
m,n = symbols('m n', positive=True)
A = log(m) + log(n)
B = simplify(A)
print(B)
print(A == B)
```

```
log(m*n)
False
```

**Comment by JainulV** [comment]
The == operator tests for exact structural equality between two expressions.  You can use the Equality class to evaluate them mathematically.
`from sympy import *
m,n = symbols('m n', positive=True)
A = log(m) + log(n)
B = simplify(A)
print(B)
simplify(Eq(A, B))`

This evaluates to 
`log(m*n)
True`

**Comment by Zaharid** [comment]
Ok, it's clear now. Thanks.

**Comment by oscarbenjamin** [comment]
There are a couple of options for this:
```julia
In [57]: A.equals(B)
Out[57]: True

In [58]: simplify(Eq(A, B))
Out[58]: True
```
Looks like this is solved so I'll close this issue.
