### ISSUE TITLE
GLSL CodeGen?

### ISSUE THREAD

**Issue by ataber** [sympy/sympy#11578]
I'm writing a Sympy-to-GLSL Code Generator right now, and I'm wondering whether it should be its own project or whether it belongs in Sympy. On the one hand, I prefer having it be its own project so it can remain an optional module. On the other hand, some of Sympy's Codegen architecture would have to be copied in the new module (for instance, [this function](https://github.com/sympy/sympy/blob/master/sympy/utilities/codegen.py#L1609) would have to be rewritten to load a GLSLCodegen instance instead of [looking up from a dictionary](https://github.com/sympy/sympy/blob/master/sympy/utilities/codegen.py#L1730)). 

This is perhaps related to the broader question of Sympy's philosophy around modular components. Thoughts?

**Comment by moorepants** [comment]
You are welcome to maintain your own separate package but for the code generators we generally like to have the support built in to SymPy. There are advantages and disadvantages of having a separate package. If you include with SymPy you benefit from our tests run on every SymPy pull and others are more likely to both use and work on the code. We've accepted several new languages for the code gen module lately, so my guess is your's would be happily accepted. But there may be some reasons that it is better for your to maintain your own code too.

**Comment by ataber** [comment]
Thanks for the answer! I'll finish developing it and will open a PR if it makes sense.

**Comment by micahscopes** [comment]
@ataber I've submitted a pull request for a glsl code printer: https://github.com/sympy/sympy/pull/12713

Maybe you have some feedback?
