### ISSUE TITLE
conjugate of real expression should not change expression

### ISSUE THREAD

**Issue by mzaffalon** [sympy/sympy#11581]
The square root of a real quantity does not seem to be detected as real. The last two expressions are not evaluated as 0.
```
x, y = symbols("x, y", real=True)
r = sqrt(x**2+y**2)
simplify(conjugate(r)-r)
simplify(conjugate(re(r))-r)
```

**Comment by smichr** [comment]
Do we just need to add a check for non-negative base with a non-negative power in the following?


```python
In file: sympy\core\power.py
    def _eval_conjugate(self):
        from sympy.functions.elementary.complexes import conjugate as c
        i, p = self.exp.is_integer, self.base.is_positive
        if i:
            return c(self.base)**self.exp
        if p:
            return self.base**c(self.exp)
        if i is False and p is False:
            expanded = expand_complex(self)
            if expanded != self:
                return c(expanded)
        if i.is_nonnegative and p.is_nonnegative:
            return self
```

**Comment by mzaffalon** [comment]
I do not understand the proposed code change, but is checking base and power necessary? If my understanding of the field `is_real` is correct in the following example
```
r = sqrt(x**2 + y**2)
r.is_real # --> True
nr = sqrt(x**2 - y**2)
nr.is_real # --> None
nr.is_complex # --> True
```
isn't sufficient to simply check the truth value of `is_real`?

**Comment by smichr** [comment]
I suspect the routine I pasted above is trying to avoid recursion errors by checking the base and power.

I'm not sure I understand the intention of your examples. The `nr.is_real` is None because it will be real if x**2 >= y**2 and imaginary otherwise. And if the result has both real and imaginary components then it will be neither real nor imaginary, just complex.

**Comment by mzaffalon** [comment]
Sorry for not being clear.

With my second example I wanted to say that SymPy already detects the correct type for `r` without the proposed patch. Then if SymPy evaluates `r.is_real` as true, both `conjugate(r)` and `conjugate(re(r))` should simply be equal to `r`.

Does it make sense?

**Comment by smichr** [comment]
> Does it make sense?

Yes. What I am trying to say is that I think the change needs to be made in the function I pasted and just putting `if self.is_real: return self` may lead to recursion problems for some expressions. You can try it and see.  (When you say `conjugate(r)` the function I pasted is going to be triggered.)

**Comment by smichr** [comment]
Is this in line with what you are saying?

```python
def _eval_conjugate(self):
    from sympy.functions.elementary.complexes import conjugate as c
    i = self.exp.is_integer
    if i:
        return c(self.base)**self.exp
    p = self.base.is_positive
    if p:
        return self.base**c(self.exp)
    if i is False and p is False:
        expanded = expand_complex(self)
        if expanded != self:
            return c(expanded)
    if self.is_real:
        return self
```

The `conjugate` tests pass and 

```python
>>> var('x y',real=1)
(x, y)
>>> conjugate(sqrt(x**2+y**2))
sqrt(x**2 + y**2)
>>> x = var('x')
>>> conjugate(re(x))
re(x)
```

**Comment by mzaffalon** [comment]
I was trying to digest your first proposal and I missed your last comment. Yes, that was it. Does it lead to recursion problems as you mentioned above?

In your first proposal, why is the line you added
```
if i.is_nonnegative and p.is_nonnegative:
    return self
```
ever evaluated, after you checked the truth value of `i` and `p`?

(By the way, thank you for the excellent work you are putting in SymPy.)

**Comment by smichr** [comment]
> I was trying to digest your first proposal and I missed your last comment. Yes, that was it. Does it lead to recursion problems as you mentioned above?

No recursion problems. Having worked a fair amount on the assumptions system (which is full of such tets) I think I was confusing the `_eval_conjugate` routine with that.

> In your first proposal, why is the line you added

Instead of `i` and `p` I should have written `self.base...self.power...`. But I think the simple change to just start by checking if the power is real or not is the better way to go. If you want to make such a PR I would be happy to review. it.

> (By the way, thank you for the excellent work you are putting in SymPy.)

Thanks for saying so. I have appreciated the number of knowledgeable and helpful people that are associated with SymPy. It's been both instructive and enjoyable to have taken part.

**Comment by mzaffalon** [comment]
Sorry for the delay, I seem to have an aversion to git that makes me procrastinate anything that has to do with it.

Your proposed patch fails for

1. `sympy\concrete\tests\test_sums_products.py:test_euler_maclaurin` -> `AttributeError: 'NoneType' object has no attribute 'is_nonnegative'`
2. ` sympy\concrete\tests\test_sums_products.py:test_is_convergent` -> `AttributeError: 'bool' object has no attribute 'is_nonnegative'`
3. `sympy\core\tests\test_arit.py:test_pow` -> `AttributeError: 'NoneType' object has no attribute 'is_nonnegative'`

I stopped here because the tests were taking too long.

**Comment by mzaffalon** [comment]
@smichr I am sorry for commenting on this again: your initial reaction to check the reality of the expression was negative and instead proposed a different fix. Why do you pull the PR now? The fact that some tests fail could be because other functions are buggy and your intuition is correct.
