### ISSUE TITLE
Question, how can i know what assumptions are available in my SymPy ver?

### ISSUE THREAD

**Issue by latot** [sympy/sympy#11587]
Hi all, well i'm asking here because i can't get an answer, basically with the actual version of SymPy we can check this on the wiki:
http://docs.sympy.org/dev/modules/core.html

But this don't is documented for every version, and some time we works with differents versions of Sympy, so how can i get a list of the available assumptions for any version?
i can't try setting one by one because we can set anything:
```
>>> x=Symbol("x", HHHHHHHHHHHHHHH=True)
>>> x.assumptions0
{'commutative': True, 'HHHHHHHHHHHHHHH': True}
```

Thx. Cya.

**Comment by smichr** [comment]
Does this [comment](https://github.com/sympy/sympy/issues/11539#issuecomment-242088404) help?

**Comment by latot** [comment]
:D 
Thx.
Posting here for the record.
```
>>> from sympy.core.assumptions import _assume_defined as r
>>> r
{algebraic,antihermitian,commutative,complex,composite,even,finite,hermitian,imaginary,infinite,
integer,irrational,negative,noninteger,nonnegative,nonpositive,nonzero,odd,polar,positive,prime,
rational,real,transcendental,zero} 
```

**Comment by smichr** [comment]
P.S. The [group discussion list](https://groups.google.com/forum/#!forum/sympy) is a good place to raise questions. This is a place to identify issues that need to be fixed. 

You beat me to the closing of this! :-) Thanks for doing so.

**Comment by latot** [comment]
Thx, i'll take into consider.
(i really don't knew that exist!)
