### ISSUE TITLE
special value of polylog(s, z) at z = -1

### ISSUE THREAD

**Issue by p-zander** [sympy/sympy#11593]
Easy to fix:

The special value of the polylogarithm `polylog(s, z)` at `z = -1` is

`polylog(s, -1) = -dirichlet_eta(s)` [[wikipedia.org](https://en.wikipedia.org/wiki/Polylogarithm#Relationship_to_other_functions)]

but the sign seems to be missing, example:

`polylog(2,-1)` and `dirichlet_eta(2)` both return `pi**2/12`

**Comment by normalhuman** [comment]
I don't know when this was corrected but it works in both 1.1.1 and current master: `polylog(s, -1)` returns `-dirichlet_eta(s)`

**Comment by asmeurer** [comment]
This was fixed by https://github.com/sympy/sympy/pull/10799
