### ISSUE TITLE
Cannot use `Add` on `MatrixSymbol`

### ISSUE THREAD

**Issue by siefkenj** [sympy/sympy#11599]
It would be nice to be able to call `Add` on `MatrixSymbol` objects.  Currently

```
>>> A,B = MatrixSymbol('A',2,2), MatrixSymbol('B',2,2)
>>> Add(A,B)
/usr/lib64/python3.4/site-packages/sympy/core/expr.py in as_terms(self)
    916 
    917         for term in Add.make_args(self):
--> 918             coeff, _term = term.as_coeff_Mul()
    919 
    920             coeff = complex(coeff)

AttributeError: 'MatrixSymbol' object has no attribute 'as_coeff_Mul'
```

I suspect `MatrixSymbol` should inherit from `Expr` instead of `Basic`, but switching this breaks a lot.

**Comment by JainulV** [comment]
Matrixsymbol just Creates a SymPy Symbol to represent a Matrix. This matrix has a shape and can be included in Matrix Expressions.
If you want to use operations you need to create a Matrix class  object not matrixsymbol. Matrix symbol is just like a placeholder for the matrix.

**Comment by siefkenj** [comment]
@JainulV symbolic operations are supported in other ways.

```
>>> A,B = MatrixSymbol('A',2,2), MatrixSymbol('B',2,2)
>>> A + B
A + B
```

**Comment by moorepants** [comment]
The issue here is that matrices do not subclass from basic sympy types in a way that allows them to work with the standard SymPy operators. All of the operators are redefined for matrices:

```
In [8]: from sympy import *

In [9]: from sympy.matrices import MatAdd

In [10]: A, B = MatrixSymbol('A', 2, 2), MatrixSymbol('B', 2, 2)

In [11]: MatAdd(A, B)
Out[11]: A + B
```

I know that for the Matrix objects they require mutability for specific operations to be efficient, so we can't subclass from Basic. I'm not sure about MatrixSymbol though. Maybe it could be seperated from the MatrixBase types.

**Comment by siefkenj** [comment]
@moorepants `Matrix` does not inherit from `Basic`, but `MatrixSymbol` does inherit from `Basic` (even though it should really inherit from `Expr`).  `MatrixSymbol` doesn't inherit from `MatrixBase`, though `ImmutableDenseMatrix` inherits from both `MatrixSymbol` and `MatrixBase`.

**Comment by moorepants** [comment]
Hmm. I don't know why it doesn't work then.

**Comment by asmeurer** [comment]
This works for me in master.

**Comment by oscarbenjamin** [comment]
Still works now on master:
```julia
In [47]: A,B = MatrixSymbol('A',2,2), MatrixSymbol('B',2,2)

In [48]: Add(A,B)
Out[48]: A + B
```
I'll close this.

**Comment by asmeurer** [comment]
Related to https://github.com/sympy/sympy/pull/15948.
