### ISSUE TITLE
Replace \dots with \ldots or \cdots

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#11602]
In a few places in the source we have LaTeX math that uses `\dots`. According to https://tex.stackexchange.com/questions/77737/dots-versus-ldots-is-there-a-difference, `\dots` is `\ldots` in raw LaTeX, but with amsmath, it trues to guess if it should use `\ldots` or `\cdots`. 

Fortunately, none of the printers are using `\dots`, but I still think we should be explicit everywhere. Another issue with this is that KaTeX doesn't support `\dots` (https://github.com/Khan/KaTeX/issues/528).

**Comment by raghvendrar** [comment]
I want to work on this.
