### ISSUE TITLE
Add Lanczos sigma approximation functionality

### ISSUE THREAD

**Issue by mjenczmyk** [sympy/sympy#11626]
I would like to add new function performing [Lanczos sigma approximation](http://mathworld.wolfram.com/LanczosSigmaFactor.html) task (I haven't seen one in sympy). 

My first idea is is to create`LanczosApproximation` (or `Lanczos Series`) class in `sympy.series.fourier` module inheriting `FourierSeries` class and than write function `lanczos_approximation` in `sympy.core.expr.Expr` using new class.

Are you OK with that? Do you have any remarks/corrections to my idea?

**Comment by leosartaj** [comment]
> I would like to add new function performing Lanczos sigma approximation task (I haven't seen one in sympy).

+1

> My first idea is is to createLanczosApproximation (or Lanczos Series) class in sympy.series.fourier module inheriting FourierSeries class

``FourierSeries`` class is still new, we might have to see if there needs to be any changes.

> and than write function lanczos_approximation in sympy.core.expr.Expr using new class.

Why not just write it in the fourier file for now. We can then find a better place to put it.

**Comment by mjenczmyk** [comment]
All right than, I'll put it in `sympy.series.fourier` module (the same in which the `FourierSeries` class is. There may be more to discuss, but it's better to discuss when there is a code, so I will make a pull request fist.

I'll be in touch - I'm a little busy recently, but I hope to find some time in a weekend.

Thanks for the response, and have a great time :)
