### ISSUE TITLE
N-dim arrays: add printers

### ISSUE THREAD

**Issue by Upabjojr** [sympy/sympy#11636]
Add printers for the objects in `sympy.tensor.array`.

``` python
In [1]: from sympy.tensor.array import *

In [2]: A = derive_by_array(f(x,y,z), (x, y, z))
```

`A` is an N-dim array, it has no printers:

``` python
In [3]: A
Out[3]: [Derivative(f(x, y, z), x), Derivative(f(x, y, z), y), Derivative(f(x, y, z), z)]

In [4]: type(A)
Out[4]: sympy.tensor.array.dense_ndim_array.ImmutableDenseNDimArray
```

If _A_ is converted to a list, the printers will work correctly:

``` python
In [6]: A.tolist()
Out[6]: 
⎡∂               ∂               ∂             ⎤
⎢──(f(x, y, z)), ──(f(x, y, z)), ──(f(x, y, z))⎥
⎣∂x              ∂y              ∂z            ⎦

In [7]: type(A.tolist())
Out[7]: list

```

Notes:
- rank 1 and rank 2 N-dim arrays can be thought of as vectors and matrices.
- rank 3 and above arrays need a special way of representation.
- default `__str__` and/or `__repr__` needs to encompass the class constructor, i.e. printing `Array([1, 2, 3])` instead of `[1, 2, 3]`.

**Comment by Lakshya1605** [comment]
Hello i am a newbie and I want to work on this issue.Could some one suggest me how do I start?

**Comment by Upabjojr** [comment]
> Hello i am a newbie and I want to work on this issue.Could some one suggest me how do I start? 

There are various printers in SymPy, they can be found in `sympy.printing`.

Of special interest are classes like:

- `StrPrinter` in `sympy.printing.str`
- `ReprPrinter` in `sympy.printing.repr`
- `PrettyPrinter` in `sympy/printing/pretty/pretty.py`
- `LatexPrinter` in `sympy/printing/latex.py`

This issue requires to add the method `_print_NDimArray(self, expr)` (or its subclasses like `_print_ImmutableDenseNDimArray`) to return the proper expression 

- _str_ shall return the current content,
- _pretty_ should nicely format is,
- _latex_ shall return a LaTeX representation of the array.

**Comment by Upabjojr** [comment]
You could have a look at methods like `_print_list` and `_print_Matrix`, they already implement the printers for those special cases.

**Comment by abhimnc** [comment]
@Lakshya1605     another newbie here ! Have you made progress on this issue ? If not then I want  to solve this issue .

**Comment by Upabjojr** [comment]
LaTeX printers are easier. Just re-adapt the code from matrix/list printers.

**Comment by liamlundy** [comment]
This isn't quite that simple. The array you gave in the example would be easy to print as it has 1 dimension, but other possible arrays could have many more dimensions. This means there would have to be a concise way of print an array of more than 2 dimensions. Although 3 is possible to visualize, there isn't an immediate way to print and anything with more than three dimensions would require techniques that do no show the true shape of the array without "cheating".

That being said, I think this is possible as long as the visual representation of array with more than 3 dimensions is covered.

**Comment by Upabjojr** [comment]
> but other possible arrays could have many more dimensions.
> [...]
> there isn't an immediate way to print anything with more than three dimensions as that would require techniques that do not show the true shape of the array without "cheating".

Just print it as nested lists. Or, print it as a nested list except for the last two dimensions, which can be printed as a matrix.

**Comment by Upabjojr** [comment]
https://github.com/sympy/sympy/pull/11792

**Comment by Upabjojr** [comment]
https://github.com/sympy/sympy/pull/11793

**Comment by Upabjojr** [comment]
Test.

**Comment by Upabjojr** [comment]
This issue has been solved.
