### ISSUE TITLE
Missing text in the Installation doc

### ISSUE THREAD

**Issue by Dawny33** [sympy/sympy#11639]
In the following installation doc: http://docs.sympy.org/latest/install.html#installation, the method for installing the git version from sympy is mentioned as: `setupegg.py develop`

But, the correct way to execute the `setupegg.py` file is: `python setupegg.py develop`

[Pl verify. If legit, I can fix it and send a PR]

**Comment by sidhantnagpal** [comment]
It seems to have been corrected now. The docs now say: `python setupegg.py develop`.
