### ISSUE TITLE
How does the Reduce Row Echelon Form work with Sympy?

### ISSUE THREAD

**Issue by Anabstudent** [sympy/sympy#11638]
So I am trying to make a program that can do a RREF algorithm to a matrix. Here is the code I have thus far:

```
import math
import numpy as SHIT
import sympy as GARBAGE
from sympy import *
from sympy import Matrix
```

```
alpha = eval(input("How many rows? "))
beta = eval(input("How many columns? "))
```

```
def make_matrix(alpha,beta):
    matrix_thing = SHIT.random.randint(0,50,(alpha,beta))
    return(matrix_thing)
print(make_matrix(alpha,beta))
```

```
matrix_thing = make_matrix(alpha,beta)
RREF_Matrix = matrix_thing.rref()
```

The final line I am returned "AttributeError: 'numpy.ndarray' object has no attribute 'rref'" which does not make sense to me and was hoping I could get clarified for me today.

**Comment by siddharthist** [comment]
Try constructing a matrix with the constructors in Sympy: http://docs.sympy.org/latest/tutorial/matrices.html

**Comment by siefkenj** [comment]
I think this bug should be closed.

**Comment by undefx** [comment]
Replace your very last line:

````python
RREF_Matrix = matrix_thing.rref()
````
with this:

````python
RREF_Matrix = SHIT.array(Matrix(matrix_thing).rref()[0]).astype(SHIT.float)
````
---

+1 for close

**Comment by sidhantnagpal** [comment]
Closing issue as resolved.
