### ISSUE TITLE
.real and .imag properties

### ISSUE THREAD

**Issue by arsenovic** [sympy/sympy#11645]
i am designing an algorithm, and i would like it to work with numerics (numpy) and symbolics(sympy). i realize this is not a typical usage..
in either case, i do a lot of work with complex numbers and frequently run into a problem with non-existence of the attributes `real` and `imag` on sympy objects.  i have hacked around this by adding these attributes in the past, but i cannot add them to everything ( `sympy.core.numbers.One` for example). 

do you have a suggestion for a solution? 
could  the `real`, `imag`  attributes be added  sympy objects?

**Comment by sidhantnagpal** [comment]
You can use `.as_real_imag()` or the functions `re` and `im`.
```py
In [19]: z = 5 + 6*I                                                         

In [20]: z.as_real_imag()                                                    
Out[20]: (5, 6)

In [21]: re(z), im(z)                                                     
Out[21]: (5, 6)
```
