### ISSUE TITLE
Geometric sum doesn't evaluate with float base

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#11642]
Originally reported at https://stackoverflow.com/questions/39547952/why-does-sympy-not-work-properly-with-real-numbers

```
In [211]: Sum(Rational(1, 2)**(n), (n, 1, oo)).doit()
Out[211]: 1

In [212]: Sum((0.5)**(n), (n, 1, oo)).doit()
Out[212]:
  ∞
 ___
 ╲
  ╲      n
  ╱   0.5
 ╱
 ‾‾‾
n = 1
```

**Comment by smichr** [comment]
Well...0.5 is not exact so are you expecting some sort of Float with appropriate precision from `doit`?

**Comment by asmeurer** [comment]
Yeah an answer of 1.0 would be appropriate.

**Comment by smichr** [comment]
I suspect you just want the equivalent of `Float(answer_of_sum_with_Float_converted_to_Rationals)` but is it trivial to calculate what the precision is of `Sum((1/2+eps)**n, (n,1,oo))`? If someone explicitly wants to treat the precision as infinite they should `nsimplify(the_sum, rational=True).doit().n()` -- explicit is better than implicit.

**Comment by asmeurer** [comment]
I don't see why it shouldn't just work. The closed form of a sum of `a**n` is very simple, and only requires that `abs(a) < 1` if the sum is infinite. It should just plug a into the answer, regardless of whether it a float or a rational. I can see maybe`Sum(1.0**n, (n, 1, oo))` being problematic, but 0.5 is very neatly in bounds.
