### ISSUE TITLE
SymPy cannot compute Sum(p**k/factorial(k) * 1/(h+k), (k, 1, oo))

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#11643]
```
h, k, lam, p = symbols('h k lambda p')
exprInner = Sum(p**k/factorial(k) * 1/(h+k), (k, 1, oo))
exprInner.doit()
```

According to [WolframAlpha](https://www.wolframalpha.com/input/?i=sum%28p%5Ek%2Fk!+*+1%2F%28h%2Bk%29,+%28k,+1,+infinity%29%29), the answer is `((-p)**(-h) (exp(p) (-p)**h-(-p)**h+Γ(h+1, 0, -p)))/h` where `Γ` I think is an incomplete gamma function (WolframAlpha isn't working so well right now, so I can't check what it is exactly). 

See https://stackoverflow.com/questions/39547495/how-to-solve-this-sum-with-sympy-wolfram-alpha-could-do-it

**Comment by oscarbenjamin** [comment]
I get this now:
```julia
In [16]: h, k, lam, p = symbols('h k lambda p')
    ...: exprInner = Sum(p**k/factorial(k) * 1/(h+k), (k, 1, oo))
    ...: exprInner.doit()
    ...: 
Out[16]: 
  ⎛ -h - 1          -ⅈ⋅π⋅h  ⎛      ⅈ⋅π⎞   -h - 1⎞
p⋅⎜p      ⋅(h + 1)⋅ℯ      ⋅γ⎝h, p⋅ℯ   ⎠ + ──────⎟
  ⎝                                        h⋅p  ⎠
─────────────────────────────────────────────────
                      h + 1  
```
That looks similar-ish to Wolfram's answer which I think (not sure) is
```
In [28]: ((-p)**(-h)* (exp(p)* (-p)**h-(-p)**h+lowergamma(h+1, -p)))/h
Out[28]: 
    -h ⎛    h  p       h               ⎞
(-p)  ⋅⎝(-p) ⋅ℯ  - (-p)  + γ(h + 1, -p)⎠
────────────────────────────────────────
                   h 
```

Not sure if that's correct...

**Comment by asmeurer** [comment]
`lowergamma(s + 1, x) = s*lowergamma(s, x) + x**s*exp(-x)` (see https://en.wikipedia.org/wiki/Incomplete_gamma_function#Properties).

So I think they are equal, at least under some assumptions on h and p

```py
>>> a = ((-p)**(-h)* (exp(p)* (-p)**h-(-p)**h+lowergamma(h+1, -p)))/h
>>> simplify(exprInner.doit() - a).replace(exp_polar(I*pi), -1).replace(lowergamma(h + 1, -p), h*lowergamma(h, -p) - (-p)**h*exp(-(-p))).replace(exp(-I*pi*h), (-1)**h).expand().powsimp(force=True)
0
```

**Comment by oscarbenjamin** [comment]
Okay!

Is further investigation warranted or should we close this?

**Comment by asmeurer** [comment]
The SymPy answer could probably be simpler, but that's a general problem with Sum and Integral returning results with exp_polar and the like. And of course it would be nice if simplify() were better at equating the two expressions, in particular it would be nice if it knew about the lowergamma identity, but that's a separate issue.
