### ISSUE TITLE
Wrong answer: Diff. of trig. functions two times

### ISSUE THREAD

**Issue by VirtualAcoustics** [sympy/sympy#11646]
> > > f1 = cos(x)
> > > This works fine:
> > > diff(f1,x,2)
> > > −cos(x)

But function of cos

> > > f2 = sin(x)+ cos(x)
> > > diff(f2,x,2) 
> > > −sin(x)+cos(x)
> > > is wrong! Answer should be −sin(x)  −cos(x)
> > > I ran this on http://live.sympy.org/

**Comment by parsoyaarihant** [comment]
This program runs fine locally:

```python
>>> from sympy import *
>>> from sympy.abc import *
>>> f2 = sin(x)+ cos(x)
>>> diff(f2,x,2)
-(sin(x) + cos(x))
```

**Comment by VirtualAcoustics** [comment]
Interesting...
setting output to ASCII instead of Latex yields correct answer on  http://live.sympy.org/
Locally, in Jupyter notebook, if I skip init_printing() the answer is correct. It seems like there is something with the paranthesis.

**Comment by oscarbenjamin** [comment]
I've just tested this on SymPy live and it seems fine in either output mode.

Is this still an issue?

**Comment by VirtualAcoustics** [comment]
Not an issue anymore. I get correct printing.
