### ISSUE TITLE
limit(Rational(-1,2)**k, k, oo) fails

### ISSUE THREAD

**Issue by SteliosStefanatos** [sympy/sympy#11672]
Python 3.5.2, Sympy 1.0.

The following code

```
k = symbols('k', integer = True, positive= True)
limit(Rational(-1,2)**k, k, sp.oo)
```

returns `NotImplementedError`, instead of `0`.

**Comment by Lakshya1605** [comment]
I am a newbie a would like to work on this issue ..Get someone guide me

**Comment by sachin-4099** [comment]
For such cases, `limit_seq` should be used:
On current master:
```
In [1]: limit_seq(Rational(-1,2)**k, k)
Out[1]: 0
```
This only needs a test in order to be closed.

**Comment by goddus** [comment]
I'd like to help with this issue.

**Comment by sachin-4099** [comment]
You should simply add the required testcase to `series/test_limitseq.py`.
