### ISSUE TITLE
Matrix power to known integer too slow

### ISSUE THREAD

**Issue by Upabjojr** [sympy/sympy#11677]
Is the matrix power to an integer calculated by repeatedly multiplying the matrix by itself?

For large integers, it may be convenient to calculate the matrix power by an integer symbol (currently implemented with an algorithm depending on Jordan canonical forms) and then replace it by the integer values.

The threshold (if it exists) should be determined by benchmarks.

**Comment by mon95** [comment]
Hello! I am new to open source and I would like to work on this issue and start contributing.

I understand that the Matrix power to an integer (in matrices/matrices.py) is computed using exponentiation by squaring. 

Could you please elaborate on what exactly is expected?

**Comment by Upabjojr** [comment]
https://github.com/sympy/sympy/blob/2de847577b98934a8f8e96e02ce8fd11741687a6/sympy/matrices/matrices.py#L195

This is the code for matrix power in case of integer exponent, the while loop performs the matrix power in `O(log(N))` operations (presumably).

Next term to the `if` loop is the code with Jordan block:
https://github.com/sympy/sympy/blob/2de847577b98934a8f8e96e02ce8fd11741687a6/sympy/matrices/matrices.py#L210

Question: if the exponent is numeric but very high (say, `m**100000000000`), could the second algorithm be faster?

**Comment by mon95** [comment]
Thank you! 

This link suggests that powers of Jordan normal form matrices are easier to compute. 

The matrix powers for integers over 1e6 seem to be really slow. I checked this using different values on the interpreter. Could you tell me how to determine the threshold using benchmarks?

**Comment by Upabjojr** [comment]
http://stackoverflow.com/questions/2866380/how-can-i-time-a-code-segment-for-testing-performance-with-pythons-timeit

I suggest to try various matrix sizes and exponents.

> This link suggests that powers of Jordan normal form matrices are easier to compute. 

Well, it depends on what you mean by _easier_, the algorithm is actually more complicated.

**Comment by mon95** [comment]
I wrote a small script to see how the time taken varies as we change the exponent. And, I used this with varying matrix sizes and found this: 

(Matrix Size  ->  Exponent up to which using the matrix power definition for integers is faster)

2x2 -> 131072 
3x3 -> 16000 (approx)
4x4 -> 8192
5x5 -> 8192
10x10 -> 8192
20x20 -> 8192
50x50 -> 8192 

Code snippet used:

`def findpow(matrix, exponent):
    return (matrix ** exponent).n()

A = SparseMatrix(eye(100)).add(SparseMatrix(ones(100)))  # Change value for different matrix sizes

i = 128
while i < 10000:
    t0 = time.time()
    Z = findpow(A, i)           # Uses the code for matrix power in case of integer exponent
    # findpow(A, float(i))      # Uses the code with Jordan block 
    t1 = time.time()
    print('Exponent: {0} -> Time: {1} \n').format(i, t1 - t0)
    i = i*2
`

Can we conclude that exponent = 8192 is a reasonable threshold for NxN matrices with N > 3?  

Can I modify the code accordingly?

**Comment by Upabjojr** [comment]
Maybe better try both sparse and dense matrices.

Did you try only one matrix? Did you try matrices with symbols?

If you edit, remember that the Jordan block algorithm requires the eigenvalues, which can be found only if the solvers are able to (sometimes it may occur that there is some unsolvable polynomial). So, better have a fallback on the old algorithm in case of failure.

**Comment by Upabjojr** [comment]
Better remove `.n()` in `findpow`, it might compromise the timing.

**Comment by Upabjojr** [comment]
May I suggest this kind of for-loop:

```python
for mattype, mat, n in itertools.product([SparseMatrix, DenseMatrix], [mat1, mat2, ...], [16, 32, 64, ...]):
    ...
```
This would test all combinations of cases.

In particular, I wanna see if matrices containing symbolic expressions get sped up.

**Comment by mon95** [comment]
I used something like this earlier today to try out various matrices (Removed the .n() in findpow() and used Matrix instead of SparseMatrix) : 
`
def findpow(matrix, exponent):
    return (matrix ** exponent)

n = <some value>
A = Matrix(eye(n)).add(Matrix(ones(n))*random.randint(0,100)).add(Matrix(ones(n)) * random.randint(700,1000))
...
`
> Did you try matrices with symbols?
I used: A = Matrix([[a, 1, 0, 0], [0, a, 1, 0], [0, 0, a, 0], [0, 1, 0, a]]). pow() for these matrices seem to be working fine even for large integer powers. 

> I wanna see if matrices containing symbolic expressions get sped up

Could you give me an example of one or two such matrices containing symbolic expressions? 
(I tried using:  X = MatrixSymbol('X', 3, 3). But I'm unable to use the jordan cell definition with this form)

**Comment by prateekg** [comment]
Can't matrix power be calculated using the numpy.linalg.matrix_power(M, n) ?
{where M = square matrix, n = Integer}

**Comment by prateekg** [comment]
The 'if' statement for the integral power seems OK. We are looking to optimize the 'elif' statement ? @Upabjojr

**Comment by Upabjojr** [comment]
```python
In [1]: m = Matrix([[a, b], [c, d]])

In [2]: m**k
===> works fast

In [3]: m**100000
===> takes a lot of time

In [4]: (m**k).subs(k, 100000)
===> works fast
```

So I guess `m**100000` should be calculated symbolically, then have the exponent replaced by 100000.

> The 'if' statement for the integral power seems OK.

It's OK, but it is too slow sometimes.

**Comment by prateekg** [comment]
Okay, so for simple int value passed, the pow() works slowly for big values while if the same value is passed symbolically as an expression it is calculated through Jordan_cells, which is quite efficient and faster.

So, if we find a way to replace the simple int value passed to be converted into some expression, it will solve our issue.

I guess my above assumption for solving the issue is correct @Upabjojr  ?

**Comment by Upabjojr** [comment]
> So, if we find a way to replace the simple int value passed to be converted into some expression, it will solve our issue.

Be careful, the Jordan cells algorithm might fail (e.g. if the solvers are unable to calculate the eigenvalues). We need to make sure there's always a fallback on the slow code.

**Comment by Abdullahjavednesar** [comment]
@Upabjojr it seems that the first algorithm works fine within a particular threshold value and beyond that the Jordan algorithm works better. So can I code it such that within the threshold first algorithm is executed else Jordan method(I'll see to it that it falls back to the first algorithm in case failure ).

**Comment by prateekg** [comment]
@Abdullahjavednesar  @Upabjojr  Instead we will calculate the threshold value first (which will take signigicant for computation), we can directly compute using Jordan Method and can fall back to first algorithm in case it fails to compute the eigen values.

**Comment by Upabjojr** [comment]
> we can directly compute using Jordan Method

I wouldn't use the algorithm with the Jordan form of small powers like `A**2` or `A**3`. Besides, the Jordan form tends to give a rather messy result.

The point is simple: expressions like `A**100000` tend to hang up forever.

**Comment by Upabjojr** [comment]
https://github.com/sympy/sympy/pull/11874
