### ISSUE TITLE
simplify: wrong simplification with trigonometric functions with complex arguments

### ISSUE THREAD

**Issue by walterhuber** [sympy/sympy#11685]
sympy version is 1.0

```
>>> from sympy import *
>>> a = 2*sqrt(2)*I*cos(pi/6 - `I*asinh(5*sqrt(2)/2)/3)/3`
>>> a
2*sqrt(2)*I*cos(pi/6 - I*asinh(5*sqrt(2)/2)/3)/3
>>> a.evalf()
-0.333333333333333 + 1.0*I
>>> b = a.simplify()
>>> b
2*sqrt(2)*I*cosh(pi/6 + asinh(5*sqrt(2)/2)/3)/3
>>> b.evalf()
1.6818694524863*I
```

> > > So **a** should equal **b** numerically, which is not at all the case. The reason seems to be  that 
> > > `cos(pi/6 -I*asinh() )` is converted into `cosh(pi/6 + asinh())` instead of 
> > > `cosh(I*pi/6 + asinh())`

Remarkably: if we remove the factors in the expression above, simplify leaves the expression unchanged 

```
>>> c= cos(pi/6 - I*asinh(5*sqrt(2)/2)/3)
>>> c.simplify()
cos(pi/6 - I*asinh(5*sqrt(2)/2)/3)
```

**Comment by baoqchau** [comment]
Can I work on this issue?

**Comment by asmeurer** [comment]
Go for it.

**Comment by ylemkimon** [comment]
This seems to be problem in hyper_as_trig(osborne) in fu.

**Comment by ylemkimon** [comment]
The implemented osborne's rule isn't valid for simplification like TR10i.
