### ISSUE TITLE
implemented_function (UndefinedFunction) fails to deserialize with cloudpickle

### ISSUE THREAD

**Issue by richardotis** [sympy/sympy#11692]
An instance of `UndefinedFunction` is returned by the `implemented_function` routine. This issue causes a problem with using `implemented_function` with multiprocessing.

Example
=======
```python
from sympy.core.function import UndefinedFunction
f = UndefinedFunction('test')
import cloudpickle
tss = cloudpickle.dumps(f)
cloudpickle.loads(tss)
```
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-6-bcafff842eeb> in <module>()
      3 import cloudpickle
      4 tss = cloudpickle.dumps(f)
----> 5 cloudpickle.loads(tss)

TypeError: __new__() takes 2 positional arguments but 4 were given
```

Workaround
=========
cloudpickle can handle nested classes, so you can get around the metaclass trickery by defining the function as a class directly:
```python
from sympy import Function, Lambda, symbols
x, y = symbols('x y')
class f(Function):
    _imp_ = Lambda((x,y), x**2+y**2)
tss = cloudpickle.dumps(f)
cloudpickle.loads(tss) # no errors
```

**Comment by richardotis** [comment]
I did my best to work out the cause of this bug, but there's a lot of low-level stuff involving metaclasses that I had trouble following. I'm hoping someone with more familiarity with the core can take a look. cc @asmeurer @moorepants

**Comment by moorepants** [comment]
I think you'll find many related issues, for example:https://github.com/sympy/sympy/issues/4297. That includes a number of references to other related issues too.

**Comment by asmeurer** [comment]
Also https://github.com/sympy/sympy/issues/4787

**Comment by richardotis** [comment]
Right, the inability to pickle many types of SymPy objects is nothing new. I'm specifically talking about cloudpickle support, which otherwise works flawlessly. The reason we should care about cloudpickle support is because dask uses it for serialization across workers by default. Sending `UndefinedFunction` across the wire ends up being necessary for making dask multiprocessing/distributed play nicely with autowrap-based codegen.

**Comment by asmeurer** [comment]
Oddly, it seems that regular `pickle` can handle functions (when was that fixed?). 

Do you know what `__new__` the traceback is referring to?

**Comment by asmeurer** [comment]
My best guess is that it's referring to this line https://github.com/sympy/sympy/blob/20872c3b27726825869876b2dbe38e2fcd3bef2a/sympy/core/function.py#L780

**Comment by asmeurer** [comment]
Another data point: it works in an interactive session

```
In [8]: cloudpickle.loads(cloudpickle.dumps(f(x))) is f(x)
Out[8]: True
```

**Comment by asmeurer** [comment]
Python 2 gives a different traceback. Maybe more helpful to debug this:

```pytb
Traceback (most recent call last):
  File "test.py", line 9, in <module>
    d = cloudpickle.dumps(f(x))
  File "/Users/aaronmeurer/anaconda3/envs/python2/lib/python2.7/site-packages/cloudpickle/cloudpickle.py", line 629, in dumps
    cp.dump(obj)
  File "/Users/aaronmeurer/anaconda3/envs/python2/lib/python2.7/site-packages/cloudpickle/cloudpickle.py", line 107, in dump
    return Pickler.dump(self, obj)
  File "/Users/aaronmeurer/anaconda3/envs/python2/lib/python2.7/pickle.py", line 224, in dump
    self.save(obj)
  File "/Users/aaronmeurer/anaconda3/envs/python2/lib/python2.7/pickle.py", line 331, in save
    self.save_reduce(obj=obj, *rv)
  File "/Users/aaronmeurer/anaconda3/envs/python2/lib/python2.7/site-packages/cloudpickle/cloudpickle.py", line 528, in save_reduce
    save(func)
  File "/Users/aaronmeurer/anaconda3/envs/python2/lib/python2.7/pickle.py", line 300, in save
    self.save_global(obj)
  File "/Users/aaronmeurer/anaconda3/envs/python2/lib/python2.7/site-packages/cloudpickle/cloudpickle.py", line 368, in save_global
    self.save_reduce(typ, (obj.__name__, obj.__bases__, d), obj=obj)
  File "/Users/aaronmeurer/anaconda3/envs/python2/lib/python2.7/site-packages/cloudpickle/cloudpickle.py", line 533, in save_reduce
    self.memoize(obj)
  File "/Users/aaronmeurer/anaconda3/envs/python2/lib/python2.7/pickle.py", line 244, in memoize
    assert id(obj) not in self.memo
AssertionError
```

**Comment by asmeurer** [comment]
I reported https://github.com/cloudpipe/cloudpickle/issues/65 upstream. Hopefully we just need to implement some `__reduce__` method on UndefinedFunction to make this work (or hopefully it is a bug in cloudpickle that can be fixed upstream).

**Comment by richardotis** [comment]
UndefinedFunction is a metaclass which returns an instance of a class type. Shouldn't calling `UndefinedFunction('f')` be roughly the same as
```python
from sympy.core.function import AppliedUndef
class f(AppliedUndef):
    __module__ = None
```
(the above works fine with cloudpickle)

**Comment by richardotis** [comment]
Oh, no, I'm getting the metaclass mixed up with the class. The type of `UndefinedFunction('f')` will still be `UndefinedFunction`.

**Comment by asmeurer** [comment]
Yes, a more correct example is 

```
from sympy.core.function import AppliedUndef, UndefinedFunction

class f(AppliedUndef, metaclass=UndefinedFunction):
    __module__ = None
```

which fails with the same exception.

**Comment by richardotis** [comment]
That example fails with the same exception for me, but at *class definition*. That makes this more likely to be a bug in SymPy I think.

**Comment by richardotis** [comment]
Changing
```python
class UndefinedFunction(FunctionClass):
    """
    The (meta)class of undefined functions.
    """
    def __new__(mcl, name, **kwargs):
```
to
```python
class UndefinedFunction(FunctionClass):
    """
    The (meta)class of undefined functions.
    """
    def __new__(mcl, name, *args, **kwargs):
```

appears to fix the issue. I'm not sure what the consequences of this are, however.

**Comment by asmeurer** [comment]
If you add `print(args)` to the top of `__new__`, this is what is printed:

```
()
((AppliedUndef,), {'__qualname__': 'f', '__module__': None})
```

So, does every metaclass need to accept the full function signature of `type`?

**Comment by richardotis** [comment]
It looks like it. That would explain why unpickling and invoking the metaclass indirectly via the `class` statement raise the same exception.

**Comment by asmeurer** [comment]
OK, the first one comes from import time, from https://github.com/sympy/sympy/blob/20872c3b27726825869876b2dbe38e2fcd3bef2a/sympy/functions/combinatorial/numbers.py#L39. When `UndefinedFunction` is created from `Function.__new__` ([here](https://github.com/sympy/sympy/blob/20872c3b27726825869876b2dbe38e2fcd3bef2a/sympy/core/function.py#L408), only the arguments of `Function` are passed in (I don't know why it takes `*args`, i.e., just `name`). But when you create a class, the metaclass is passed the bases and dictionary, just as with type. I guess unpickling does the same. 

So I think your fix is fine. I'm a little unclear if we should check the `*args` and pass them through to the `BasicMeta.__new__` call (side question, should that be `super().__new__`?). 

We also should add a check in `Function.__new__` to make sure that `len(args) == 1` when `cls == Function`, so that people don't create `Function('f', args)` and have the extra args eaten up.

**Comment by asmeurer** [comment]
Or maybe it should be

```py
class UndefinedFunction(FunctionClass):
    def __new__(mcl, name, bases=(AppliedUndef,), dict=None, **kwargs):
        dict = dict or {}
        dict.update(kwargs)
        ret = BasicMeta.__new__(mcl, name, bases, dict)
        ...
```

That way we aren't eating arbitrary `*args`, and it is more self documenting.

**Comment by asmeurer** [comment]
Oh and it should probably be `mod_dict` instead of `dict` so that we don't override the builtin.

**Comment by asmeurer** [comment]
OK, see https://github.com/sympy/sympy/pull/11693. We should definitely test this somehow (probably by testing cloudpickle directly). 

Also, note that it still doesn't work in Python 2 (same error as before). I'm guessing this is due to some limitations in the older pickle protocols, or possibly a bug in cloudpickle.

**Comment by richardotis** [comment]
Does it work in Python 2 if you change `bases` and `mod_dict` to be positional arguments?

**Comment by asmeurer** [comment]
Nope, doesn't look like it. And doing so breaks [this test](https://github.com/sympy/sympy/pull/7688/files#diff-5f25427da46082ec269576baef49a5c4R674) anyway, becuase you have to manually pass `bases=(AppliedUndef,)` and `mod_dict={}` when creating `UndefinedFunction` (that might even be considered an API change, I'm unsure how people are using UndefinedFunction in the wild).
