### ISSUE TITLE
Make the releases in the release table links

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#11702]
At https://github.com/sympy/sympy/releases, the items in the table should be links.

The table is generated automatically by `release/fabfile.py`.

**Comment by Lakshya1605** [comment]
I would like to work on this .Please can you elaborate on  what is expected .Thank You.

**Comment by asmeurer** [comment]
The fabfile generates the release table. The items in the left column should be links to the downloads.

**Comment by Lakshya1605** [comment]
@asmeurer  I have modified the code ,but i am not able to understand how to check it .Please Can you help me out.

**Comment by asmeurer** [comment]
I'm not sure how to completely verify it without doing a release. I guess you can run the table command and check the resulting markdown. It may require running the other commands first (doing a fake release, see the release/README).

**Comment by Lakshya1605** [comment]
@asmeurer  I am trying to follow to the release/README but i am getting this error "Fatal error: fabvenv is required. See https://pypi.python.org/pypi/fabric-virtualenv/"  when i run fab vagrant prepare,
I am not able to understand what to do .Can you please help me.

**Comment by asmeurer** [comment]
You'll need to install a few things to run the releases script, including fabric, fabric-virtualenv, and vagrant (and btw fabric requires Python 2). If you are unable to test the change you can just make a PR and I will test if it works.

**Comment by Lakshya1605** [comment]
@asmeurer Please Verify .

**Comment by rammanoj** [comment]
can I want to work on this issue?

**Comment by LejlaMetohajrova** [comment]
Looks like this was fixed by #12359. Is there anything else to do? Shouldn't this and #12359 be closed?
