### ISSUE TITLE
diff should return Derivative instances when they can

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#11737]
It's confusing to allow `diff(f(g(x)), g(x))` but not actually return that:

```
In [33]: print(diff(f(g(x)), g(x)))
Subs(Derivative(f(_xi_2), _xi_2), (_xi_2,), (g(x),))

In [34]: print(diff(f(g(x)), g(x)).doit())
Derivative(f(g(x)), g(x))
```

If the derivative can be expressed without `Subs`, it should.

**Comment by isuruf** [comment]
Isn't that all of them? What are some expressions that cannot be expressed without `Subs`?

**Comment by asmeurer** [comment]
Derivatives can only be taken with respect to a symbol or a function. Taking derivatives of more complex expressions is not allowed (see http://docs.sympy.org/latest/modules/core.html#sympy.core.function.Derivative). So a simple example would be 

```
In [40]: diff(f(x**2), x)
Out[40]:
    ⎛ d        ⎞│
2⋅x⋅⎜───(f(ξ₁))⎟│    2
    ⎝dξ₁       ⎠│ξ₁=x
```

**Comment by asmeurer** [comment]
Related bug, which will probably need to be fixed at the same time https://github.com/sympy/sympy/issues/7027

**Comment by normalhuman** [comment]
Closely related to #13848 where I proposed a solution (replacing Subs by `subs` on [this line](https://github.com/sympy/sympy/blob/master/sympy/core/function.py#L1274)) but it is blocked by #13803.
