### ISSUE TITLE
Interval inside intervals

### ISSUE THREAD

**Issue by rohitrango** [sympy/sympy#11736]
I'm getting undesirable results in the following cases (only the 4th case is true) - 
```
In [1]: Interval(1,3) in Interval(1,4)
Out[1]: False

In [2]: Interval(0,5) in Interval(1,4)
Out[2]: False

In [3]: Interval(2,2) in Interval(1.4,4.2)
Out[3]: False

In [4]: 2.3 in Interval(1.4,4.2)
Out[4]: True

In [5]: set([1,2,3]) in Interval(1.4,4.2)
Out[5]: False

In [6]: set([1,2,3,5]) in Interval(1.4,4.2)
Out[6]: False
```

But we can definitely say that one interval lies inside the other.  Basically we are not checking whether an interval lies inside another interval or not.

**Comment by YodelingPenguin** [comment]
Is that because 'in' is a shortcut of method contains? And 'contains' returns True if ‘other’ is contained in ‘self’ as an element.

Hence, when you do in for interval or set, it will always return a False?

**Comment by rohitrango** [comment]
Yes. I was just about to start work on it, but I don't know whether this is desirable or not. I would like a word or two from the admins on the same.

**Comment by rohitrango** [comment]
Closing this after @jksuom recommended me to use the `is_subset` function and the understand the correct interpretation of `contains` (to be used for elements and not for subsets). Refer this #11732

**Comment by YodelingPenguin** [comment]
Actually, I'm wondering if it is good option to make 'in' a more general method. So it will return True if ‘other’ is contained in ‘self’ as an element or as a set?  
What do you think?

**Comment by rohitrango** [comment]
I thought it at first, but realized it is not a good idea. We already have other methods for that, and making a more general function may sometimes be undesirable. 
That's the reason I closed the issue.

**Comment by YodelingPenguin** [comment]
Yeah, I agree with you. Thanks!
