### ISSUE TITLE
Union(FiniteSet(oo), S.Complexes) gives S.Complexes (should remain unevaluated)

### ISSUE THREAD

**Issue by latot** [sympy/sympy#11730]
Hi, well searching i found this:

``` python
>>> oo in S.UniversalSet
True
>>> oo in S.Complexes
False
>>> Union(FiniteSet(oo), S.Complexes)
S.Complexes
```

i don't know with this where `oo` belongs, is part of Complexes or not?

Thx. Cya.

**Comment by asmeurer** [comment]
UniversalSet doesn't come into play here. It's just a formal set that always returns True for any containment check. `Union(FiniteSet(oo), S.Complexes)` giving `S.Complexes` is a bug.

**Comment by asmeurer** [comment]
(Optimistically setting this as easy to fix. I suspect it isn't difficult, but there is a chance I am wrong)

**Comment by MrOverlord** [comment]
After working for a bit on this, there's also a related bug with Intersection
```python
>>> Intersection(S.Reals, ComplexRegion(Interval(0,1)**2))
ℝ
```
One would expect this to be [0,1].

I have tried fixing this [here](https://github.com/MrOverlord/sympy/commit/efa9a618bb277612c1520eaea01264a866d654b0#diff-c1c17bdd28aafd400bf9415c7d048382), but this causes a failure in test_ComplexRegion_union : 
```python
c1 = ComplexRegion(Interval(0, 1)*Interval(0, 2*S.Pi), polar=True)
#...
assert c1.union(Interval(2, 4)) == Union(c1, Interval(2, 4), evaluate=False)
```
and test_union_RealSubSet :
```python
assert (S.Complexes).union(Interval(1, 2)) == S.Complexes
```
Could you give me a hint, what is wrong with my fix?

**Comment by asmeurer** [comment]
If the new test output is still mathematically correct, then just change the test. union returning Union is the default behavior. If it can return something more specific instead, that is preferred.
