### ISSUE TITLE
Fails operators between Interval and some S.Sets

### ISSUE THREAD

**Issue by latot** [sympy/sympy#11732]
Hi, here the problem:
```python
>>> Interval(1, 2) in S.EmptySet
False
>>> Interval(1, 2) in S.Integers
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python2.7/site-packages/sympy/sets/sets.py", line 513, in __contains__
    raise TypeError('contains did not evaluate to a bool: %r' % symb)
TypeError: contains did not evaluate to a bool: Contains([1, 2], Integers())
>>> Interval(1, 2) in S.Naturals
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python2.7/site-packages/sympy/sets/sets.py", line 513, in __contains__
    raise TypeError('contains did not evaluate to a bool: %r' % symb)
TypeError: contains did not evaluate to a bool: Contains([1, 2], Naturals())
>>> Interval(1, 2) in S.Naturals0
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python2.7/site-packages/sympy/sets/sets.py", line 513, in __contains__
    raise TypeError('contains did not evaluate to a bool: %r' % symb)
TypeError: contains did not evaluate to a bool: Contains([1, 2], Naturals0())
>>> Interval(1, 2) in S.Reals
False
>>> Interval(1, 2) in S.Complexes
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python2.7/site-packages/sympy/sets/sets.py", line 511, in __contains__
    symb = sympify(self.contains(other))
  File "/usr/lib64/python2.7/site-packages/sympy/sets/sets.py", line 286, in contains
    ret = sympify(self._contains(other))
  File "/usr/lib64/python2.7/site-packages/sympy/sets/fancysets.py", line 1359, in _contains
    re, im = other if isTuple else other.as_real_imag()
AttributeError: 'Interval' object has no attribute 'as_real_imag'
>>> Interval(1, 2) in S.UniversalSet
True
```

For now i found this in Contains function, this can exist in others, so for now this is all.

Thx. Cya.

**Comment by rohitrango** [comment]
As of now, modifying the `_contains` function of the `fancysets` seems to resolve the issue to some extent. But since they all seem to inherit from the `Sets` and `Singleton` class. Since I'm a newcomer, can someone guide me a bit? 

Here's the temporary fix as of now.
![sympy_fix](https://cloud.githubusercontent.com/assets/15312514/19420493/11f3b078-940a-11e6-9447-8da3e1d85383.png)

**Comment by jksuom** [comment]
`Interval(1, 1)` and `set([1, 2, 3, 4])` are not integers although `FiniteSet(1)` and `FiniteSet(1, 2, 3, 4)` are subsets of `S.Integers`. Therefore also 10 and 11 should be `False`.

**Comment by rohitrango** [comment]
Sympify function converts them to the FiniteSet class.

**Comment by jksuom** [comment]
The word 'contains' may be confusing. In SymPy, 'S contains x' means that x is an element of S. The word is often also used to indicate the subset relation, like 'S contains A' meaning that A is a subset of S, but that is not how it is used in SymPy.

So, if x is an element of S (or `x in S`), then the set {x} is a subset of S  but not an element of S.

(The sympify function has no role in this.)

**Comment by rohitrango** [comment]
Alright. Perhaps we can have some other function that tells whether it is a subset or not.

**Comment by jksuom** [comment]
There is the method `is_subset` in the 'Set` class.

**Comment by rohitrango** [comment]
Thanks! As of now, I'm running the tests and will soon send a PR. Thanks for the help. I'm a newcomer, and I'm really glad by the support I'm being given. Thanks again :smile:

**Comment by jksuom** [comment]
#11738
