### ISSUE TITLE
TypeError: __new__() missing 1 required positional argument: 'cond' with solve

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#11745]
Reported at https://stackoverflow.com/questions/40082924/error-when-using-sympys-solver-on-polynomials-with-complex-coefficients-4th-de

```
import sympy as sym
from sympy import I
sym.init_printing()

k = sym.Symbol('k')
t, sigma ,k0, L , V = sym.symbols('t, sigma, k0, L,V')

x4 = ( -t**2 + 2*I * t / sigma**2 + 1/sigma**4)
x3 = ( -2*I * t * k0 / sigma**2 - 2*k0 / sigma**4)
x2 = ( L**2 + k0 **2 / sigma **4 + t**2 * V - 2 * I * t * V / sigma**2 -V/sigma**4)
x1 = (2*I * V * k0 / sigma**2 + 2*k0 * V / sigma **4)
x0 = (2*I*k0*t*V / sigma**2 - k0 **2 *V / sigma**4)

expr = x4 * k**4 + x3 * k**3 + x2 * k**2 + x1 * k + x0
expr2 = expr.subs({k0 :2 , sigma : .2 , L : 1, V:1})

sym.solvers.solve(expr2,k)
```

gives

```
Traceback (most recent call last):

  File "<ipython-input-4-e1ce7d8c9531>", line 1, in <module>
    sols = sym.solvers.solve(expr2,k)

  File "/usr/local/lib/python2.7/dist-packages/sympy/solvers    /solvers.py", line 1125, in solve
    solution = nfloat(solution, exponent=False)

  File "/usr/local/lib/python2.7/dist-packages/sympy/core/function.py",     line 2465, in nfloat
    return type(expr)([nfloat(a, n, exponent) for a in expr])

  File "/usr/local/lib/python2.7/dist-packages/sympy/core/function.py",     line 2499, in nfloat
    lambda x: isinstance(x, Function)))

  File "/usr/local/lib/python2.7/dist-packages/sympy/core/basic.py",     line 1087, in xreplace
    value, _ = self._xreplace(rule)

  File "/usr/local/lib/python2.7/dist-packages/sympy/core/basic.py",     line 1095, in _xreplace
    return rule[self], True

  File "/usr/local/lib/python2.7/dist-packages/sympy/core/rules.py",     line 59, in __getitem__
    return self._transform(key)

  File "/usr/local/lib/python2.7/dist-packages/sympy/core/function.py",     line 2498, in <lambda>
    lambda x: x.func(*nfloat(x.args, n, exponent)),

  File "/usr/local/lib/python2.7/dist-packages/sympy/core/function.py",     line 2465, in nfloat
    return type(expr)([nfloat(a, n, exponent) for a in expr])

  File "/usr/local/lib/python2.7/dist-packages/sympy/core/function.py",     line 2465, in nfloat
    return type(expr)([nfloat(a, n, exponent) for a in expr])

TypeError: __new__() takes exactly 3 arguments (2 given)
```

In Python 3 the error is

```
TypeError: __new__() missing 1 required positional argument: 'cond'
```

which suggests that the object is a Piecewise. The code in question should be using `expr.func` instead of `type(expr)`, but even then, it isn't passing in the `args` correctly.

**Comment by Lakshya1605** [comment]
I would like to work on this, could someone please tell me what is expected to be done.Thank you

**Comment by asmeurer** [comment]
You'll need to debug the problem to see what is going wrong.

**Comment by Lakshya1605** [comment]
@asmeurer  as it has been mentioned in stackoverflow that "sym.solvers.solve(expr2, k, rational =False)" gives the result .Do we want  "sym.solvers.solve(expr2,k)" to also give the  same result

**Comment by asmeurer** [comment]
Yes.

**Comment by Lakshya1605** [comment]
@asmeurer  how to check whether a given expression is entering into a particular loop of sympy,solvers module .
If i change the code in the loop (in solvers module) to something like "print "inside the loop"" i get an error .Can you please help me out.

**Comment by asmeurer** [comment]
What error do you get?

**Comment by Lakshya1605** [comment]
File "/home/lakshya/sympy/sympy/solvers/solvers.py", line 1030
    print " in the loop"
                       ^
SyntaxError: invalid syntax

**Comment by asmeurer** [comment]
You need to put parentheses, like `print("in the loop")`.

**Comment by Lakshya1605** [comment]
It working Thank you .

**Comment by Lakshya1605** [comment]
@asmeurer  In the docstring it has been mentioned that "rational = True " by default.

>     if floats and solution and flags.get('rational',None) is None:
        solution = nfloat(solution, exponent=False)

However the above line of code uses "None" as the default value . Is this a specified behaviour of the code or is it a unknowingly done.
Fixing the above issue gives the correct result.

**Comment by asmeurer** [comment]
Is that just because you're changing the default value of the `rational` flag? It seems from the traceback that the issue is in the core.

**Comment by Lakshya1605** [comment]
I figured out that "solve(expr2, k, rational=False)" as well as "solve(expr2, k, rational=True)" were giving the result .But "solve(expr2, k,)" wasn't able to and it was mentioned in docstring that rational uses True as default so i just searched were was "rational"  initialized as "None" or "False" if no agument is passed and fixing that gave that correct result.
