### ISSUE TITLE
nsolve wrong result

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#11768]
``` py
>>> print(E.subs(sols[0]).diff(t))
-0.0243197537608033*(-0.636658291554981*t + 0.561884537092944)/(-0.0243197537608033*t + 1)**2 + (-2*(t + 1)/(2*t - 2)**2 + 1/(2*t - 2))*exp((t + 1)/(2*t - 2)) + 0.636658291554981/(-0.0243197537608033*t + 1)
>>> nsolve(diff(E.subs(sols[0]), t), .9)
mpf('0.99996577349047597')
>>> E.subs(sols[0]).diff(t).subs(t, 0.99996577349047597) 
0.654436749282803
```

Here's a plot of the function in question. As you can see, the root should be around 0.7.

![8pzjlzvm767vqaaaaasuvork5cyii](https://cloud.githubusercontent.com/assets/71486/19700941/503fa83c-9ac7-11e6-8f51-76ce5bfd4441.png)

**Comment by asmeurer** [comment]
Using a different solver gives the right answer:

```py
>>> nsolve(diff(E.subs(sols[0]), t), (.5, 0.9), solver='bisect')
mpf('0.70295119676297064')
```

**Comment by smichr** [comment]
`nsolve` only uses the numerator of the expression...and the numerator is close to zero at the reported root so it fools the solver.

**Comment by asmeurer** [comment]
So we should probably make it not just use the numerator. Numerically, the denominator can be significant if it is near 0 where the numerator is.

**Comment by smichr** [comment]
It's probably better to make nsolve just use whatever function it is given and leave the choice of what function to use (numerator or rational expression) up to the user. The problem with leaving a denominator is that the singularities often cause problems for root solvers. But sometimes, as here, you get problems if you ignore the denominator.

**Comment by smichr** [comment]
tests are running on my nsolve branch...

**Comment by smichr** [comment]
If you look at the numerator of the expression you used you can see that it has a very different derivative structure than the full expression:

![image](https://cloud.githubusercontent.com/assets/90703/19808996/dbed6870-9cec-11e6-9338-077331bb0c57.png)
