### ISSUE TITLE
Integral (fourier) transforms not evaluating distributions correctly

### ISSUE THREAD

**Issue by rancomp** [sympy/sympy#11772]
Trying to calculate the (continuous) fourier transform of a distribution (e.g. 1, sine, cosine...) returns 0 as indeed this functions are not integrable. 

As one would benefit greatly if the fourier_transform would deal with distributions aswell (easy example; figuring out main frequncies of a given expression) I think we would all benefit if this would be 'fixed'.

code example
````
In [1]: from sympy.integrals.transforms import fourier_transform'

In [2]: from sympy import sin

In [3]: from sympy.abc import x, k

In [4]: fourier_transform(sin(x), x, k)

Out[4]: 0
```

BTW, Is it just me not being able to tab auto-complete `sympy.integrals.tr` to `sympy.integrals.transforms`?
Also, if i don't import the transforms directly (and just import sympy instead) I cannot call them.

**Comment by nantonel** [comment]
has this been fixed? it doesn't look like from the version I'm using (v1.2) or is there any other issue?

**Comment by jksuom** [comment]
Fourier transforms of distributions have not yet been implemented.
