### ISSUE TITLE
exp(eye(2)) maybe wrong?

### ISSUE THREAD

**Issue by augustt198** [sympy/sympy#11807]
```
>>> exp(eye(2))
Matrix([
[E, 0],
[0, E]])
```
Is `exp` not applied element-wise for matrices? Numpy, matlab, and mathematica give the result I expected: `[[E, 1], [1, E]]`.

**Comment by jksuom** [comment]
> Is exp not applied element-wise for matrices?

There is another method for that purpose.
```
>>> eye(2).applyfunc(exp)
Matrix([
[E, 1],
[1, E]])
```

**Comment by asmeurer** [comment]
This is a semantic difference between SymPy and NumPy, MATLAB, and (imho, unfortunately) Mathematica. SymPy only uses mathematically meaningful operations on matrices. That means that operators like `*`, `**`, `exp`, and others perform their matrix versions. For NumPy, all operators apply element wise over arrays. I assume MATLAB is similar. Mathematica requires special operators to apply matrix operators (if I remember correctly). 

I'm closing this as a won't fix.
