### ISSUE TITLE
Incorrectly evaluating integral

### ISSUE THREAD

**Issue by lengelhardt** [sympy/sympy#11806]
The following integral is incorrectly evaluated to be zero:

from sympy import *
var('x', real=True)
var('y, L', positive=True)
integrand = 1 / sqrt(x**2 + y**2)**3
integrate(integrand, [x, -L/2, L/2])

The result that SHOULD be returned is:
2/(y**2*sqrt(1 + 4*y**2/L**2))

It seems that x**2 is being treated as a negative number instead of a positive number for x<0.

**Comment by latot** [comment]
Hi, its little hard read this, i can see ```x2``` and ```y2```, and i don't know if is ```x*2``` or ```x**2```, please edit the issue and use this format with this symbol "`" to can see this better plis:
> \`\`\`
code...
\`\`\`

Here you can get more info: https://guides.github.com/features/mastering-markdown/

Thx. Cya.

**Comment by lengelhardt** [comment]
Sorry.  Here is the correctly formatted code:
```
from sympy import *
var('x', real=True)
var('y, L', positive=True)
integrand = 1 / sqrt(x**2 + y**2)**3
integrate(integrand, [x, -L2, L/2])
```
and the expected result:
```
2/(y**2*sqrt(1 + 4*y**2/L**2))
```

**Comment by latot** [comment]
Hi, ```L2``` is ```L*2```?

**Comment by lengelhardt** [comment]
Whoops!  That should have been L/2.  I will add another comment.

Dr. Larry Engelhardt
Professor of Physics
Francis Marion University
(843) 661-1452,  LSF 103E
http://swampfox.fmarion.edu/engelhardt

**Comment by latot** [comment]
Thx, Confirmed:
```
....
>>> integrate(integrand, [x, -L/2, L/2])
0
```
