### ISSUE TITLE
SymPy's cache doesn't free objects at the end

### ISSUE THREAD

**Issue by isuruf** [sympy/sympy#11819]
This can be observed when running symengine under debug mode.

When a sympy function that is decorated with `cacheit` is called with a symengine object, symengine object is converted to a sympy object and the function works correctly.
These symengine objects are not freed at the end though. (Seen from symengine's debug mode object pool, which gives a warning that these objects are not freed).

When SYMPY_USE_CACHE=no is set, no such leaks occur.

**Comment by isuruf** [comment]
An exit handler fixes this.

**Comment by asmeurer** [comment]
The garbage collector should handle this automatically. Maybe it's a bug in fastcache?

**Comment by isuruf** [comment]
Tried with fastcache removed as well. Same result.

**Comment by isuruf** [comment]
Consider the following two examples

Program 1
```Python
from sympy import cacheit

class Bar:
    def __init__(self):
        print("init")

    def __del__(self):
        print("del")

@cacheit
def foo(a):
    return a

b = Bar()
foo(b)
```
Output :
```
init
```

Program 2:
```Python
class Bar:
    def __init__(self):
        print("init")

    def __del__(self):
        print("del")

b = Bar()
```

Output :
```
init
del
```

**Comment by asmeurer** [comment]
Interesting. I would be curious to find out just why this is happening. 

Does symengine have deconstructors that need to flush things to disk or anything like that? Or is the concern about memory leaks from embedding Python?

**Comment by isuruf** [comment]
SymEngine Python objects keep pointers to C++ objects created in the heap. They need to be freed before the program ends, otherwise memory leaks will occur.

**Comment by isuruf** [comment]
This is a gc issue. I'm not familiar with how Python's gc works to give you a reason for it
Following patch fixes it. 

```diff
diff --git a/sympy/core/cache.py b/sympy/core/cache.py
index b6c64c1..680a443 100644
--- a/sympy/core/cache.py
+++ b/sympy/core/cache.py
@@ -105,8 +105,8 @@ def wrapper(*args, **kwargs):
             # assign to wrapper.__wrapped__.
             update_wrapper(wrapper, func)
             wrapper.__wrapped__ = cfunc.__wrapped__
-
-            CACHE.append(wrapper)
+            import weakref
+            CACHE.append(weakref.ref(wrapper))
             return wrapper
 
         return func_wrapper
@@ -136,7 +136,8 @@ def __cacheit(maxsize):
         def func_wrapper(func):
 
             cfunc = fastcache.clru_cache(maxsize, typed=True, unhashable='ignore')(func)
-            CACHE.append(cfunc)
+            import weakref
+            CACHE.append(weakref.ref(cfunc))
             return cfunc
 
         return func_wrapper
```

**Comment by asmeurer** [comment]
I am +1 to that patch. The cache ought to be using weakrefs anyway.

**Comment by isuruf** [comment]
What happens when `cfunc` is garbage collected and a user calls `clear_cache`?

**Comment by isuruf** [comment]
I'll use a [WeakSet](https://docs.python.org/2/library/weakref.html#weakref.WeakSet)

**Comment by pbrady** [comment]
From the [python docs](https://docs.python.org/3/reference/datamodel.html#object.__del__) 

>  It is not guaranteed that __del__() methods are called for objects that still exist when the interpreter exits.

It seems like a design error in SymEngine to rely on "not guaranteed" behavior

**Comment by asmeurer** [comment]
That's odd that Python does that. Does that mean that libraries that have "real" `__del__` methods (like writing to a database or whatever) always have to register atexit callbacks?

**Comment by isuruf** [comment]
@pbrady, whole Cython community relies on it for clearing objects created in the C/C++ side.
I think the not guaranteed behaviour is because of situations like this, where the garbage collector fails to delete them because of issues like globals, cyclic references, etc.

**Comment by isuruf** [comment]
Weakref objects cannot be made for the lru_cache objects. So, the only option is to use a atexit handler to run `clear_cache` at the end.

**Comment by asmeurer** [comment]
Assumedly that should be implemented on the symengine side. Should this be closed?

**Comment by isuruf** [comment]
Here's the code that needs to be run. Should this happen on SymPy or SymEngine? If SymEngine, this issue should be closed?
```
from sympy.core.cache import clear_cache
import atexit
atexit.register(clear_cache)
```

**Comment by asmeurer** [comment]
Shouldn't symengine have its own handler that calls del for all the symengine objects? It seems this issue could crop up in instances outside the SymPy cache.

**Comment by isuruf** [comment]
Right. I've never needed handlers for symengine objects except when sympy's cache is used.
I've now added atexit handlers to clear sympy cache in tests.

**Comment by asmeurer** [comment]
I'm curious how it's an issue at all. If the process is ending, how can there be a memory leak?
