### ISSUE TITLE
Problem with symbolic summation of expandable geometric series

### ISSUE THREAD

**Issue by tschijnmo** [sympy/sympy#11823]
In the symbolic summation function, there is very good support for geometric sequence [here](https://github.com/sympy/sympy/blob/6242d1239828d3e2256108243ae091d72782f415/sympy/concrete/summations.py#L961-L975).  However, in the higher-level function `eval_sum`, the summand is expanded before being given to this piece of code, [here](https://github.com/sympy/sympy/blob/6242d1239828d3e2256108243ae091d72782f415/sympy/concrete/summations.py#L882).  A result of this `expand` is that when the summand is a power that can be expanded, its syntactical form of a geometric series might be destroyed.

For instance, when we do

```Py
import sympy as sp

N = sp.Symbol('N', integer=True)
k = sp.Symbol('k', integer=True)
q = sp.Symbol('q', integer=True)
n = sp.Symbol('n', integer=True)

expr = sp.Sum(
    sp.simplify(sp.exp(-2*sp.pi*sp.I*k*n/N) * sp.exp(2*sp.pi*sp.I*q*n/N)),
    (n, 0, N - 1)
)
print(sp.simplify(expr.doit()))
```

we get result as `Sum(exp(2*I*pi*n*(-k + q)/N), (n, 0, N - 1))` rather than the expected `Piecewise((N, Eq(exp(2*I*pi*(-k + q)/N), 1)), (0, True))`.  It seems to be caused by the call to `expand`, which makes the summand a product of two exponentials.

I tried to change it to

```Py
value = eval_sum_symbolic(f.expand(power_exp=False), (i, a, b))
```

and things seem to work for this special case.  And it does not break the commented purpose for the call to `expand` of changing to partial sums .  But I cannot be sure if this change is okay for the entire Sympy project.  Any comment on this is appreciated.  If this change is fine, a PR can be submitted real quick.  Thank you!

**Comment by oscarbenjamin** [comment]
This seems to work fine now. I get this:
```
⎧        2⋅ⅈ⋅π⋅(-k + q)    
⎪        ──────────────    
⎪              N           
⎨N  for ℯ               = 1
⎪                          
⎪0         otherwise       
⎩       
```

**Comment by smichr** [comment]
A check for a test and the need for #11836 could be done.

**Comment by czgdp1807** [comment]
I think this issue and the PR can be closed. Thanks for the contribution @tschijnmo . Please let us know if you want to re-open anyone of these.
