### ISSUE TITLE
cannot simplify log(x)+log(1/x)

### ISSUE THREAD

**Issue by zhou13** [sympy/sympy#11835]
````
>>> simplify(log(x) + log(1/x))
log(1/x) + log(x)
````

I believe it should be zero.

**Comment by asmeurer** [comment]
Logs only combine under the proper assumptions by default. You can use logcombine(force=True) to force them to combine.

**Comment by asmeurer** [comment]
Or set `x = symbols("x", positive=True)`.

**Comment by zhou13** [comment]
Thanks for the input.
