### ISSUE TITLE
broken xreplace

### ISSUE THREAD

**Issue by FabioLuporini** [sympy/sympy#11837]
xreplace ends up expanding the common factor 2.5 in the following example (and similarly in all analogous cases):

```
In [19]: Mul(2.5, a + b)
Out[19]: 2.5*a + 2.5*b

In [19]: Mul(2.5, a + b, evaluate=False)
Out[19]: 2.5*(a + b)

In [20]: Mul(2.5, a + b, evaluate=False).xreplace({a: c})
Out[20]: 2.5*b + 2.5*c
```

**Comment by moorepants** [comment]
I think this is expected behavior. If `xreplace()` has an `evaluate=False` flag, then it would fit with how SymPy deals with these simple evaluations.

**Comment by latot** [comment]
mm, i don't like this behavior....
basically, if is the expected behavior it leave ```evaluate``` option useless in this cases...., and there is very probable more functions with this behavior, if you want keep this maybe send a warning when a ```evaluate``` option is used?
other option, enable the ```evaluate``` option in xreplace. (so in this case is like don't inherit the properties).

**Comment by FabioLuporini** [comment]
@moorepants I don't understand why this should be the expected behaviour. ``xreplace`` should substitute nodes, but clearly not changing the tree structure. With larger expressions, I get totally different objects.

 There's no such a flag for ``xreplace``, unfortunately (AFAICT).

**Comment by czgdp1807** [comment]
For anyone passing by using the following trick,

```python
with evaluate(False):
    Mul(2.5, a + b).xreplace({a: c})
```

**Comment by czgdp1807** [comment]
Thanks for raising the issue. Closing this because of the reasons mentioned [here](https://github.com/sympy/sympy/pull/17855#issuecomment-551195719). It will be too costly to change the API of `xreplace`.
