### ISSUE TITLE
Moving TensorProduct out of the physics module?

### ISSUE THREAD

**Issue by johanbluecreek** [sympy/sympy#11832]
As per conversations with @asmeurer in PR #11774, I'm starting this issue to have a conversation on moving the `TensorProduct` out of the physics module.

`TensorProduct` has some functionality beyond the (seemingly) originally intended use for `Operator` and/or non-commutative symbols as arguments to also include `MatrixSymbol` (#11774), `ImmutableMatrices` (#10735) and already has support for explicit matrix expressions. This means that the position of `TensorProduct` in `sympy/physics/quantum/` might be a bit misplaced since it has other than quantum physics applications.

Over gitter, @asmeurer also mentioned that "we would need to split out the physics specific stuff into physics specific subclasses", for this move.

See also Issue #10771 regarding the renaming of `TensorProduct`.

**Comment by oscarbenjamin** [comment]
There now seem to be two tensorproduct functions: one in tensor and one in quantum. Not sure how these relate to each other.

Does that mean this issue is solved?
