### ISSUE TITLE
error in limit involving exp, sinh and an assumption (maybe related to caching)

### ISSUE THREAD

**Issue by Ruediger-Braun** [sympy/sympy#11833]
Hi all!

The following code

```
(compana16) braun:~/git/compana16$ ipython
Python 3.5.2 |Continuum Analytics, Inc.| (default, Jul  2 2016, 17:49:02)
Type "copyright", "credits" or "license" for more information.

IPython 5.1.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: import sympy

In [2]: sympy.__version__
Out[2]: '1.0'

In [3]: x = sympy.Symbol('x')

In [4]: a = sympy.Symbol('a', positive=True)

In [5]: f = sympy.exp(x*(-a-1)) * sympy.sinh(x)

In [6]: f.limit(x, sympy.oo)
Out[6]: oo

```
produces false output.  Correct is 0.  
Since sometimes the correct result is returned, I think the problem is related to caching.  If caching is turned off, then the product in [5] cannot even be constructed.

```
(compana16) braun:~/git/compana16$ export SYMPY_USE_CACHE='no'
(compana16) braun:~/git/compana16$ ipython
Python 3.5.2 |Continuum Analytics, Inc.| (default, Jul  2 2016, 17:49:02)
Type "copyright", "credits" or "license" for more information.

IPython 5.1.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: import sympy

In [2]: sympy.__version__
Out[2]: '1.0'

In [3]: x = sympy.Symbol('x')

In [4]: a = sympy.Symbol('a', positive=True)

In [5]: f = sympy.exp(x*(-a-1))

In [6]: g = sympy.sinh(x)

In [7]: h = f*g
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
/home/braun/miniconda3/envs/compana16/lib/python3.5/site-packages/sympy/core/assumptions.py in getit(self)
    240         try:
--> 241             return self._assumptions[fact]
    242         except KeyError:

KeyError: 'zero'

During handling of the above exception, another exception occurred:

KeyError                                  Traceback (most recent call last)
/home/braun/miniconda3/envs/compana16/lib/python3.5/site-packages/sympy/core/assumptions.py in getit(self)
    240         try:
--> 241             return self._assumptions[fact]
    242         except KeyError:

KeyError: 'zero'


```

This goes on until a RecursionError kicks in,

**Comment by karan1276** [comment]
I think u wanted to write: `f = sympy.exp(x*(-a-1) * sympy.sinh(x))`
instead you wrote:  `f = sympy.exp(x*(-a-1)) * sympy.sinh(x)`
reason: brackets at the wrong place.

@asmeurer i think this can be closed.

**Comment by Ruediger-Braun** [comment]
@karan1276 unfortunately, the brackets are where I want them.  The problem is that the error is intermittent, so you may have seen the correct answer if you only tried once.

**Comment by karan1276** [comment]
@Ruediger-Braun Sorry i got you wrong.

I am new to sympy, i din't get what you mean by `f = sympy.exp(x*(-a-1)) * sympy.sinh(x)`. First you created an expression `x*(-a-1)` then multiplied it with another expression `sinh(x)`. Is that not equal to `x*(-a-1)*sinh(x)` anyways?

**Comment by Ruediger-Braun** [comment]
sympy.exp is the exponential function.  Since sinh(x) = (exp(x)-exp(-x))/2, the formula for f simplifies to (sympy.exp(-a*x) - sympy.exp((-a-2)*x))/2, so the limit for x -> oo is clearly 0 under the assumption a > 0.

**Comment by maurogaravello** [comment]
Indeed the following code gives the correct answer

```
import sympy

x = sympy.Symbol('x')
a = sympy.Symbol('a', positive=True)
f = sympy.exp(x*(-a-1)) * sympy.sinh(x)


print sympy.sinh(x).limit(x, sympy.oo)
print f.limit(x, sympy.oo)
```
while the following (without **print sympy.sinh(x).limit(x, sympy.oo)**) does not


```
import sympy

x = sympy.Symbol('x')
a = sympy.Symbol('a', positive=True)
f = sympy.exp(x*(-a-1)) * sympy.sinh(x)

print f.limit(x, sympy.oo)
```

**Comment by Ruediger-Braun** [comment]
Thanks for your suggestion.  I tried it three times
* once under python2.7: it worked
* twice under python3.5 (with the necessary change of the print-statement): once it worked, once it failed

I think the problems happens in the cache, but I have no idea what triggers it

**Comment by Ruediger-Braun** [comment]
Works correctly under Version 1.3
