### ISSUE TITLE
Function('gamma') pretty prints as Γ

### ISSUE THREAD

**Issue by moorepants** [sympy/sympy#11841]
```
In [13]: from sympy import *

In [14]: t = symbols('t')

In [15]: init_printing()

In [16]: gamma = symbols('gamma', cls=Function)(t)

In [17]: gamma
Out[17]: Γ(t)
```

This should not create the [Gamma Function](https://en.wikipedia.org/wiki/Gamma_function).

**Comment by Abdullahjavednesar** [comment]
I would like to work on this, @moorepants could you explain how to start.

**Comment by asmeurer** [comment]
The issue is the printing I guess. 

This is also somewhat related to https://github.com/sympy/sympy/issues/6938.

**Comment by asmeurer** [comment]
I updated the issue title. The function itself is distinct from `gamma`. The problem is that the printer is hardcoded to print gamma as Γ instead of γ. It should distinguish UndefinedFunctions and only apply the simple Symbol printing rules to them.

**Comment by Abdullahjavednesar** [comment]
Fine, then I'm working on it.

**Comment by Abdullahjavednesar** [comment]
@asmeurer here, if we are defining gamma as a symbol it should print γ rather than Γ. This is the bug I guess if I've got it right.

**Comment by Abdullahjavednesar** [comment]
I've been working on this issue but unable to locate where to make changes in the sympy code. @asmeurer 
please help.

**Comment by asmeurer** [comment]
The change should be made in sympy/printing/pretty/pretty.py.
