### ISSUE TITLE
Dummy fails when is re-evaluated in S and srepr

### ISSUE THREAD

**Issue by latot** [sympy/sympy#11847]
Hi all!

Well, i found this little problem, Dummy is a nice function but in the way is implemented exist this:
```
>>> alpha = Dummy("alpha")
>>> i = Integral(1/sqrt(1 - sin(alpha)**2), (alpha, 0, pi/2))
>>> N(i)
0.e+2
>>> i = S(srepr(i))
>>> N(i)
Integral(1/sqrt(-sin(_alpha)**2 + 1), (_alpha, 0, pi/2))
```
Basically, if you works with Dummy, and you get the expression with srepr or similar, when you eval it every Dummy will be interpreted as a new Dummy, so it fails, in the example you can see we can't eval the second expression because the 2 Dummy expression are interpreted as differents, other ex:
```
>>> m=Dummy("m")
>>> a=Matrix([m, m])
>>> a[0]==a[1]
True
>>> b=S(srepr(a))
>>> b[0]==b[1]
False
```

So thinking a solution can be use a hash or similar function, like:
```
>>> m=Dummy("m")
>>> srepr(m)
"Dummy('m', hash=987654321)"
>>> m=Dummy("m")
>>> srepr(m)
"Dummy('m', hash=754619474)"
```
Always will exist the hash collision, but at least to cover all possible can be sympy check the existents Dummy expressions and check the hash never by equal to other, the probability of the hash collision, to be equal, in the same context, with the same name, and in the same expression, i think is very low.

Maybe instead use a hash can be a random expression, with chars like ```8waerfn23jb89a```, that can help to avoid hash collision.

Thx. Cya.

**Comment by cbm755** [comment]
I can confirm this.  Quoting `printing/repr.py`

> srepr returns a string so that the relation eval(srepr(expr))=expr holds in an appropriate environment.

Here's my minimal example:
````
>>> d = Dummy('d')
>>> A = Add(d, d, evaluate=False)

>>> srepr(A)                    # can see what the problem will be
"Add(Dummy('d'), Dummy('d'))"

>>> B = S(srepr(A))
>>> B
_d + _d

>>> A.doit()
2*_d

>>> B.doit()     # cannot, has two different Dummys
_d + _d
````

Note that Dummy does seem to maintain its identity across pickling:
````
>>> import cPickle
>>> d1 = Dummy()
>>> s1 = cPickle.dumps(d1)
>>> d2 = cPickle.loads(s1)
>>> d1 == d2
True
>>> d1 is d2
False
````

**Comment by asmeurer** [comment]
You have to set it to have the same dummy_index attribute. Right now there isn't a way to do that, but a (private) keyword argument could be added.  Not sure I agree that srepr should maintain this, though.

**Comment by latot** [comment]
mm, not support this i think is a vary bad idea, because this means all expressions with Dummy, used internally or externally will break all data export.......... (like the examples posted here)
And not all expressions can not have a Dummy, is used a lot in subs, and similars, and other common expression are integrals without elementary functions... (ex, all elliptic functions), we will be unable to represent it in the right way............
In my perspective i can see 2 ways, one, error when we send a dummy to srepr, second fix dummy in srepr, i actually have a fix for this, but i don't know if you will like it....

**Comment by asmeurer** [comment]
Well the fix is easy. Allow `Dummy('x', _dummy_index=10)` to override the `dummy_index` that is set from the class variable, and make srepr print that. 

But the whole point of dummy is that they shouldn't be equal to other instances of the same name. So the question is, should objects created with srepr be considered new or not? 

Also, if you do recreate an object in a new session, bets are off, because the same dummy_index could represent a completely different Dummy created somewhere else. This would only apply if you serialize and deserialize an expression in the same session. But I think srepr's primary use-case is for separate sessions (or any serialization really. Why would you serialize something if you're in the same session? Just reuse it).

**Comment by cbm755** [comment]
@asmeurer I think the point is that a single object could contain the same Dummy more than once (think of a variable of integration or my silly `evaluate=False` example).

Pre-serialization this is fine.

But upon `S(srepr(x))`, they become two distinct objects.  Bad news for the integral, whose meaning has just completely changed.

**Comment by cbm755** [comment]
(There is a related concern about two distinct objects depending on the same Dummy, and serialized separately.  I agree that's a much greyer area).

**Comment by asmeurer** [comment]
Ah, I see. So in that case, I do think this is a good idea, but caveated that dummy objects are only guaranteed to be the same in a single srepr'd expression, not across expressions.

**Comment by latot** [comment]
Hi, can you give me an example of across expressions plis?

**Comment by cbm755** [comment]
@latot, see my example above but consider:
````
A2 = 3*A
````
Now `A2` and `A` are two expressions which contain the same Dummy (the Dummy is shared "across expressions".

Now do `B = S(srepr(A))` and `B2 = S(srepr(A2))`: we want each of those to "DTRT".  But perhaps we do not guarantee that both `B` and `B2` contain the same Dummy (the Dummy might not be shared across B and B2).

**Comment by latot** [comment]
mm, i think both dummy should be equals, only for one reason, if don't are equals will break the user env...... (ex, if is trying to export it)

**Comment by cbm755** [comment]
Maybe, I'm not sure.  But let's fight one bug at a time: the most serious is the use of Dummy multiple times within one expression.  Let's fix that.  Then see where we stand.  

Baby steps right?  No need to fix everything, all-at-once, all-in-one PR.  That's almost the same as never fixing anything.

**Comment by latot** [comment]
mm, my fix cover that, but is for other reason, basically if we use the easy way, like explained above, we will have this:
```
>>> a = Dummy()
>>> a = srepr(a) %%save the value
%% New env
>>> b = Dummy()
>>> c = S(a)
>>> b == c
True
```
Basically a hash collision, so to avoid it i try safer way....
(in this case is a little pr :-)

**Comment by asmeurer** [comment]
My suggested fix would fix that too. The downside would be potentially two dummys that should be unequal being equal.

**Comment by cbm755** [comment]
I hit this again today with an integral transform.  Specifically the `inverse_laplace_transform` introduces a `Dummy('c')` (which lives in both the upper and lower limits of integration).  But try `eval(srepr(...))` and now there are two Dummy `c`'s.

````
>>> f = Function('f')
>>> x, s = symbols('x, s')
>>> ilt = inverse_laplace_transform(f(s), s, x).rewrite('Integral')
>>> ilt

c + ∞⋅ⅈ             
   ⌠                
   ⎮          s⋅x   
   ⎮    f(s)⋅ℯ    ds
   ⌡                
c - ∞⋅ⅈ             

>>> ilt.free_symbols                  # yes, this is correct

set([c, x])

>>> ilt2 = eval(srepr(ilt))
>>> ilt2                              # visually looks good, but ....

c + ∞⋅ⅈ             
   ⌠                
   ⎮          s⋅x   
   ⎮    f(s)⋅ℯ    ds
   ⌡                
c - ∞⋅ⅈ             

>>> ilt2.free_symbols                 # ... oh snap, two c's!

set([c, c, x])
````
