### ISSUE TITLE
integrating the sinc function

### ISSUE THREAD

**Issue by lxkain** [sympy/sympy#11854]
Hello,

When I do 

```
t = symbols('t', real=True)
sinc(t).integrate()

```

I get, after a relatively long time, `Si(t)`, whereas I was expecting the answer to be 1. Moreover, when I define the normalized sinc function via

```
def nsinc(t):
    "normalized sinc function"
    return sinc(pi * t)
```

and I then issue:

`nsinc(t).integrate()`

the process never returns (or perhaps it takes very very long). The expected answer in this case was also 1.

(this may be related to
https://github.com/sympy/sympy/issues/10541)

**Comment by asmeurer** [comment]
Si(t) is the right answer. Why do you expect 1?

**Comment by lxkain** [comment]
My apologies. Indeed,
`sinc(pi * t).integrate((t,-oo,oo))`
_does_ evaluate to 1.

And even

`nsinc(t).integrate((t,-oo,oo))` works correctly too. For some reason I forgot to make the integral definite.

Thank you for an awesome project!
