### ISSUE TITLE
DiracDelta function is zero for nonzero arguments

### ISSUE THREAD

**Issue by lxkain** [sympy/sympy#11855]
For
```
t = symbols('t', real=True, nonzero=True)
DiracDelta(t)
```
I would have expected the output to be 0, but instead I am getting
`δ(t)`

**Comment by smarterthanu1234** [comment]
Hi,
nonzero assumption is not checked in DiracDelta while returning 0.
Working on it.
Regards,
Aditya

**Comment by gxyd** [comment]
Closing this issue. Fixed by #11867.
