### ISSUE TITLE
Range._intersect fails when (in a line) the solution is returned in other order

### ISSUE THREAD

**Issue by latot** [sympy/sympy#11863]
Hi all!, well trying to fix some issue i found this, basically, the problem start in this line:

fancysets.py:684
```
a, b = diop_linear(eq(r1, Dummy()) - eq(r2, Dummy()))
```
The return is correct, but the problem is the algorithm applied next with a and b, it only check a, so the problem start when the first the Dummy is sorted after the second Dummy (are sorted by name), so when this happen the return is reversed, not a very big change, b is a, and a is b, is logic because is the same but in other order, well the problem is when is treaty in this case, and basically all intersections when this happen return ```EmptySet()```.

To fix this please avoid assign names to Dummy, i think the idea is fix the algorithm to can work with both solutions, a and b to avoid problems in the future.

Thx. Cya.

**Comment by smichr** [comment]
Without a failing example, this is difficult to assess and hard to imagine how it would fail since Dummy assigns name sequenctially so the one with r1 would come before that with r2. Nonetheless, I have added names in #16896
