### ISSUE TITLE
can't plot piecewise function

### ISSUE THREAD

**Issue by lxkain** [sympy/sympy#11865]
When I do

```
ω = sym.symbols('omega')
k = sym.symbols('k', real=True, k=integer)
f = sym.integrate(sym.exp(sym.I*ω*k), (ω,-π,π))
```

I cannot do

`sym.plot(f)`

However, just plotting the second piece works, via

`sym.plot(1 / (2 * π) * f.args[1][0])`

**Comment by lxkain** [comment]
Also, evaluation, e.g f(0) doesn't work - do I need to specify the independent variable specifically somewhere?

**Comment by danielmclaury** [comment]
Looks like the plotting issue is a manifestation of #11248 

Re: the second post, this is behaving as intended.  Compare

```
g = exp(x)
g(0)

```

If you want to plug things in you can do

`f.subs(k, 2)`

or, if it weren't for the unresolved issue above, 

`lambdify([k], f)(2)`
