### ISSUE TITLE
simplifying exponential -> trig identities

### ISSUE THREAD

**Issue by lxkain** [sympy/sympy#11864]
```
f = 1 / 2 * (-I*exp(I*k) + I*exp(-I*k))
trigsimp(f)
```

Ideally, this would yield `sin(k)`. Is there a way to do this?

As a corollary, it would be awesome if 

```
f = 1 / 2 / k* (-I*exp(I*k) + I*exp(-I*k))
trigsimp(f)
```

could yield `sinc(k)`. Thank you for your consideration!

**Comment by jksuom** [comment]
rewrite can be used:
```
>>> f = S(1) / 2 * (-I*exp(I*k) + I*exp(-I*k))
>>> f.rewrite(sin).simplify()
sin(k)
```

**Comment by lxkain** [comment]
Thank you for that suggestion!

**Comment by lxkain** [comment]
Too bad this doesn't work as expected:

```
ω = sym.symbols('ω', real=True)
k = sym.symbols('k', real=True)
f = 1 / 2 / π * sym.exp(sym.I * ω * k)
F = sym.integrate(f, (ω, -π, π))
F.rewrite(sym.sinc).simplify()
```

It does not produce the desired sinc function in the equation.

**Comment by jksuom** [comment]
It seems that rewrite for sinc has not been implemented.
