### ISSUE TITLE
'solveset' function  bug—solveset('log(x + 1) < 0', domain=S.Reals)

### ISSUE THREAD

**Issue by GeekTemo** [sympy/sympy#11878]
when i call solveset to solve inequation: 'log(x + 1) < 0'. It return EmptySet. It is the error result.

In [2]: solveset('log(x + 1) < 0', domain=S.Reals)
Out[2]: EmptySet()

The correct result must be (-1, 0)

**Comment by danielmclaury** [comment]
Weirder: 

`sympy.solveset('log(x) < 0', domain = sympy.S.Reals)`

returns `(-oo,1)`.

**Comment by smarterthanu1234** [comment]
returning correct output in my environment?  (for both cases)

**Comment by rohitrango** [comment]
```
In [33]: solveset('log(x) < 0', domain = S.Reals)
Out[33]: (0, 1)

In [34]: solveset('log(x+1) < 0', domain = S.Reals)
Out[34]: (-1, 0)

In [35]: solveset(log(x+1) < 0, domain = S.Reals)
Out[35]: (-1, 0)
```

@danielmclaury @GeekTemo I think it is working fine for both cases. I'm using sympy1.0.1.dev0

**Comment by MayankJhamtani** [comment]
Worked for me too.
Using sympy1.0.1.dev0 and Python 2.7 .

**Comment by oscarbenjamin** [comment]
This works fine:
```julia
In [31]:  solveset('log(x + 1) < 0', domain=S.Reals)                                                                                                          
Out[31]: (-1, 0)

In [32]:  solveset('log(x) < 0', domain=S.Reals)                                                                                                              
Out[32]: (0, 1)
```
I'll close this.
