### ISSUE TITLE
sympy not importing in jython (when defining AtomicExpr) and modifications were needed to get mpmath and sympy to install on jython

### ISSUE THREAD

**Issue by pentolope** [sympy/sympy#11875]
I have modified sympy and it's dependency mpmath to get it to install on jython. For mpmath I had to remove a test due to the method length limit that the vm has (java.lang.RuntimeException: java.lang.RuntimeException: Method code too large!). mpmath imports fine on it's own (it's missing test_fp.py though) inside jython. sympy I had to do a little more. I removed two tests (test_spin.py and bench_solvers.py) because of the length of the methods (I don't "need" tests to see if it will install and import) and modified two other files. I split up polyquinticconst.py into multiple functions so the vm would be okay with the length of the method, and I added "sympy" before the "." in the imports in the  __init__.py file. However, jython still crashes on the AtomicExpr class definition when it is importing, and I can't find an actual reason why or a way around it, but cpython works fine with that so I would consider that a bug with jython. Sympy and mpmath, please fix those tests (make the methods smaller). And sympy, please make those modifications that I made (but check if they work first, I obviously haven't tested that yet because I don't have sympy functioning on jython yet). I hope sympy and mpmath think it is a good idea to make this work on jython and not just cpython (I think it would be a good idea, at least for me). I made a fork of sympy that has the modifications that I made done at https://github.com/pentolope/sympy. (Edit it has been deleted now)

Error information:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\jython2.7.0\Lib\site-packages\sympy-1.0.1.dev0-py2.7.egg\sympy\__init__.py", line 57, in <module>
    from sympy.core import *
  File "C:\jython2.7.0\Lib\site-packages\sympy-1.0.1.dev0-py2.7.egg\sympy\core\__init__.py", line 8, in <module>
    from .expr import Expr, AtomicExpr, UnevaluatedExpr
  File "C:\jython2.7.0\Lib\site-packages\sympy-1.0.1.dev0-py2.7.egg\sympy\core\expr.py", line 3203, in <module>
    class AtomicExpr(Atom, Expr):
TypeError: Error when calling the metaclass bases
    multiple bases have instance lay-out conflict

I am posting this on sympy's, mpmath's, and jython's issue page.

**Comment by abhi18av** [comment]
@pentolope I came here and following the jython issues in the sympy repo. I was interested in your modifications but the repo seems to have been deleted...

What's the current status of this effort?

**Comment by pentolope** [comment]
I was told from the jython team that sympy is functional now (discussion is here: https://github.com/jythontools/jython/issues/52), I apologize for not updating this.
