### ISSUE TITLE
please include latex 2 sympy

### ISSUE THREAD

**Issue by kalbhairab** [sympy/sympy#11880]

**Comment by bjodah** [comment]
@kalbhairab care to elaborate what you mean with include?
Are you referring to this?:
https://github.com/augustt198/latex2sympy

**Comment by oscarbenjamin** [comment]
This issue doesn't have enough information to be useful.

**Comment by asmeurer** [comment]
latex2sympy is included in SymPy now, as `sympy.parsing.latex.parse_latex()`.
