### ISSUE TITLE
Prevent latex/dvipng console window popup on Windows

### ISSUE THREAD

**Issue by nanoant** [sympy/sympy#11882]
I have to recently use QtConsole and SymPy in Windows environment. While everything works fine, there is annoying 2 window popups appearing for fraction of second every time LaTeX -> PNG printing is performed. It is a fault of Windows which basically has this weird distinction between console and windows app.

Anyway, long story short, the workaround is very simple, you need to pass `creationflags=CREATE_NO_WINDOW` to `submodule.check_open`, here I just made a simple wrapped in `compatibility.py` so there is no popup anymore 

~~~python
        from subprocess import check_output as subprocess_check_output
        def check_output(*args, **kwargs):
            return subprocess_check_output(*args, **kwargs, creationflags=0x08000000) # CREATE_NO_WINDOW
~~~

I humbly ask to apply such a fix to mainstream for a pleasure & comfort of Windows users.
Cheers,
Adam

**Comment by smichr** [comment]
Thanks for the report @nanoant , how does it look now? If not fixed, please reopen the issue (or create a new one).

**Comment by nanoant** [comment]
@smichr I am not particularly fond of the solution proposed by @ccordoba12 in #12391. Not that I mind that it was inspired by StackOverflow post which was in turn cited the solution originally posted here in this issue report - which makes kind of weird loop :)

The problem is that merged #12391 was reworked for some reason, and now it applies only to the `latex` call, whereas all other calls using `check_output`, such as `dvips/png/svg` conversions, remain unaffected by 56bf637, still generating popups.

The original solution posted here was more general, applying for all calls (including potential future calls).

Moreover, I find checking for `os.name == "nt"` and otherwise setting `creationflags=0` unnecessary, since it is clearly stated in `subprocess.check_output` that `creationflags` applies only on Windows.

Cheers,
Adam

**Comment by ccordoba12** [comment]
> whereas all other calls using check_output

There's only one call to `check_output` in `master` that could benefit from my fix:

https://github.com/sympy/sympy/search?utf8=✓&q=check_output&type=

> I find checking for os.name == "nt" and otherwise setting creationflags=0 unnecessary

Probably, but it makes clear *in the code* why it's needed only on Windows. Else, it seems a bit of magic.

**Comment by nanoant** [comment]
> There's only one call to check_output in master that could benefit from my fix:
> https://github.com/sympy/sympy/search?utf8=✓&q=check_output&type=

@ccordoba12 Are you aware that this GitHub search page is only **"Showing the top two matches"** (as stated under the results) for each matching file? `sympy\printing\preview.py` contains another 2 calls to `check_output` (3 altogether, not just one).

> Probably, but it makes clear in the code why it's needed only on Windows. Else, it seems a bit of magic.

You could always add some comment explaining more this parameter, then at least the intentions would be clear to the reader. But still since it is Windows-only argument, checking the platform and setting it to 0 (a default value for Windows-only argument on non-Windows platform?) is just a waste of CPU cycles and may look like a mistake.

**Comment by ccordoba12** [comment]
> Are you aware that this GitHub search page is only "Showing the top two matches"

Sorry, I wasn't aware of that. Please see #12642.

> You could always add some comment explaining more this parameter

I left things as they are because I don't have more time for this. sorry.
