### ISSUE TITLE
simplifying complex math

### ISSUE THREAD

**Issue by lxkain** [sympy/sympy#11890]
```
F = sym.exp(-sym.I * ω * n0)
sym.arg(F)
```

This results in:
arg(e^−i n0 ω)

but I would really like to see:
-n0 ω

Is this a bug or user error?

**Comment by isuruf** [comment]
What is `ω` and `n0`? Can you post a python script?

**Comment by lxkain** [comment]
(first had to edit the original post)

In its simplest form:

```
import sympy as sym
w = sym.symbols('w', real=True)
F = sym.exp(sym.I * w)
print(sym.arg(F))

```
 gives

`arg(exp(I*w))`

but just

`w`

should do it :)

**Comment by ylemkimon** [comment]
Argument function(arg) is multi-valued function and SymPy's arg returns principal value which is not necessarily w. ([Wikipedia](https://en.wikipedia.org/wiki/Argument_(complex_analysis)))

**Comment by lxkain** [comment]
Can you show me the case when it is not w?

**Comment by ylemkimon** [comment]
Any w outside (-pi, pi]. For example,
```python
>>> arg(exp((3*pi)*I))
pi
>>> arg(exp((-pi)*I))
pi
```

**Comment by lxkain** [comment]
I see what you mean now, thank you.

From my naive (as in: I don't know anything about the internals of an algebra system) perspective, it seems as if some sort of rewrite rules should know about the special relationship between arg and the imaginary part of exponentiation. I must conclude that there must be good reasons for not doing this.

**Comment by oscarbenjamin** [comment]
So can this be closed?

**Comment by lxkain** [comment]
@ylemkimon seems very knowledgeable about this, so I will defer to their judgement. I'll close the issue.
