### ISSUE TITLE
Simplifying expression with 1x1 matrix transpose

### ISSUE THREAD

**Issue by andreo** [sympy/sympy#11899]
```
> m = MatrixSymbol('m', 1, 1)
> simplify(m.T - m) # i would like to see 0 here
> m.equals(m.T) # prove by numerical computation
True
```

**Comment by divs4debu** [comment]
I am new to open source project and i am trying to understand sympy's code base but after searching and digging for hours i cant find where actually matrix subtraction is taking place. I looked in core, matrices etc but cant find it.
A little help would be great.I would like to work on this issue.
