### ISSUE TITLE
Functions with integer arguments remain un-evaluated

### ISSUE THREAD

**Issue by FR4NKESTI3N** [sympy/sympy#11894]
Functions that are given an integer argument do not evaluate:
```
>>> tan(10)
tan(10)
```
Float argument:
```
>>> tan(10.0)
0.648360827459087

```
I am not sure if this is intentional or not and have not been anything on this. But this results in problems in comparisons:
```
>>> tan(10)==tan(10.0)
False
>>> tan(10)>tan(10.0)
True
>>> tan(10)<=tan(10.0)
False
```

**Comment by asmeurer** [comment]
This is intentional. The comparisons are an unfortunate consequence of the inexactness of floating point numbers.

**Comment by FR4NKESTI3N** [comment]
Although using evalf() seems to work 
```
>>>tan(10).evalf()==tan(10.0).evalf()
True
```

I tried adding this code to convert integer argument to float in eval method of tan class and it seems to show proper results. 
```
if isinstance(arg,Integer):
    return cls(float(arg))
```
If ones with integer arguments are supposed to stay unevaluated, maybe `__eq__`,` __le__` etc. can be used to return evaluated form when comparisons are being made.
If its okay, I would like to write the code for it according to your directions
