### ISSUE TITLE
Support printing presentation MathML

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#11893]
The mathml printer outputs content MathML, but it would be nice to have an option to output to presentation MathML, since not every MathML renderer supports content MathML.

**Comment by mamakancha** [comment]
Hi @asmeurer  I would like to work on this issue. Can you give me any starting point?

**Comment by asmeurer** [comment]
I would start by understanding the two different types of mathml (see https://en.wikipedia.org/wiki/MathML). The current printer code is at https://github.com/sympy/sympy/blob/master/sympy/printing/mathml.py

**Comment by mamakancha** [comment]
@asmeurer Thanks for the resources. I can give this one a try. Will start working on it and try to come up with something as soon as possible.

**Comment by mamakancha** [comment]
@asmeurer After making some changes, I want to test my `mathml.py` file with some inputs. How should I do that?

**Comment by mamakancha** [comment]
Also I am a bit lost in the code. I have gone through [https://en.wikipedia.org/wiki/MathML](https://en.wikipedia.org/wiki/MathML) but the code is confusing me. It would be great if you could suggest me something

**Comment by mamakancha** [comment]
First I thought of replacing all the ci with mi and all the cn with mn.
For this piece of code :

```
def _print_Mul(self, expr):

        if _coeff_isneg(expr):
            x = self.dom.createElement('apply')
            x.appendChild(self.dom.createElement('minus'))
            x.appendChild(self._print_Mul(-expr))
            return x
```
from line 85 onwards in [https://github.com/sympy/sympy/blob/master/sympy/printing/mathml.py](https://github.com/sympy/sympy/blob/master/sympy/printing/mathml.py)

What changes should I do?

**Comment by Subhash-Saurabh** [comment]
Is anyone currently working on this ? If not I would like to take up this issue.
