### ISSUE TITLE
Add warning in docs Live shell about SymPy version

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#11892]
Sometimes people are confused when they go to the dev documentation (or docs for an older version), and the live shell doesn't give the same answer as the page example. We should add some warning to the shell that it runs SymPy 1.0 and that examples on other docs pages might differ.

I'm not sure where this change should go. It may need to go [here](https://github.com/sympy/sympy-live).

**Comment by Shade5** [comment]
@asmeurer Can I work on this? I'm new

**Comment by moorepants** [comment]
Yes you can work on this issue.

**Comment by Shade5** [comment]
@moorepants Which shell is he talking about? How do I run it?

**Comment by jksuom** [comment]
I believe it is this one: http://live.sympy.org/

**Comment by jtoka** [comment]
@jksuom @moorepants @asmeurer I added a warning line to sympy-live here: https://github.com/sympy/sympy-live/pull/103 . Are you able to review? Also, can you tell me the suggested way to reference another repo's issue in a PR?
