### ISSUE TITLE
both solveset(sqrt(x+2)>x, x, S.Reals) and solve([sqrt(x+2)>x], x) give wrong answers

### ISSUE THREAD

**Issue by beling** [sympy/sympy#11909]
`solveset(sqrt(x+2)>x, x, S.Reals)`
gives `(-oo, -1) U (-1, 2)`

`solve([sqrt(x+2)>x], x)`
gives `Or(And(-1 < x, x < 2), And(-oo < x, x < -1))`

Correct answers is [-2, 2).

**Comment by Newman101** [comment]
Hi. 

I tested the first one: 

```solveset(sqrt(x+2)>x, x, S.Reals)```

It gives:

```In [8]: solveset(sqrt(x+2)>x, x, S.Reals)
Out[8]: [-2, 2)```

As supposed to be. 

How ever, what comes to latter one, the results are: 

```In [11]: solve([sqrt(x+2)>x], x)
Out[11]: And(-2 <= x, x < 2)```.

**Comment by beling** [comment]
I've checked at http://live.sympy.org/ (please try even now) and on my debian machine (SymPy 1.0). (also on quite fresh anaconda -- windows -- but I don't know exact SymPy version.) Everywhere the results were incorrect.
I belive that development version is free from the bug, but I can't check this.

**Comment by Newman101** [comment]
I have the latest master branch, so that might actually explain why the bug is gone.

**Comment by beling** [comment]
So, this issue can be closed, but it also shows quite good reason to release the next SymPy version possibly soon.
