### ISSUE TITLE
typo in docs of printing

### ISSUE THREAD

**Issue by gxyd** [sympy/sympy#11911]
Change "therefor" -> "therefore"  in [sympy/sympy/printing/printer.py
 line 19](https://github.com/sympy/sympy/blob/master/sympy/printing/printer.py#L19)

**Comment by baoqchau** [comment]
working on this. give me 15 mins. This will be my first pull request.

**Comment by mohit3011** [comment]
I have changed printer.py file , can anyone help me to merge it

**Comment by gxyd** [comment]
Fixed by #11912
