### ISSUE TITLE
Implementing a custom datatype

### ISSUE THREAD

**Issue by Pastafarianist** [sympy/sympy#11918]
This is a question, not an issue report. If these are not welcome in the bugtracker, please flag it as invalid.

(Crossposted from [StackOverflow](http://stackoverflow.com/questions/40947209/implementing-a-custom-datatype-in-sympy).)

I want to perform calculations with a binary operation (`Tensor`) that takes two non-commutative arguments, converts them into something like a pair, and then does funny things when I multiply these pairs.

```python
# a, b, c, d are non-commutative
Tensor(a, b) * Tensor(c, d) == Tensor(a*c, d*b)  # yes, in this order
```

Furthermore, I want all integer constants to be taken modulo 2.

```python
-Tensor(a, b) == Tensor(a, b)
2*Tensor(a, b) == 0
Tensor(2*a, b) == 0
```

---

My shot at doing this:

```python
import sympy as sp
from sympy.core.expr import Expr

class Tensor(Expr):
    __slots__ = ['is_commutative']

    def __new__(cls, l, r):
        l = sp.sympify(l)
        r = sp.sympify(r)
        obj = Expr.__new__(cls, l, r)
        obj.is_commutative = False
        return obj

    def __neg__(self):
        return self

    def __mul__(self, other):
        if isinstance(other, Tensor):
            return Tensor(self.args[0] * other.args[0], other.args[1] * self.args[1])
        elif other.is_number:
            if other % 2 == 0:
                return 0
            else:
                return self
        else:
            return sp.Mul(self, other)


x, y = sp.symbols('x, y', commutative=False)

Ym = Tensor(y, 1) - Tensor(1, y)
Yp = Tensor(y, 1) + Tensor(1, y)
Xm = Tensor(x, 1) - Tensor(1, x)

d1 = Ym * Yp + Xm * 0
print(d1)
print(sp.expand(d1))

d2 = Xm * Ym
print(d2)
print(sp.expand(d2))
```

Output:

    (Tensor(1, y) + Tensor(y, 1))**2
    Tensor(1, y**2) + 2*Tensor(y, y) + Tensor(y**2, 1)
    (Tensor(1, x) + Tensor(x, 1))*(Tensor(1, y) + Tensor(y, 1))
    Tensor(1, x)*Tensor(1, y) + Tensor(1, x)*Tensor(y, 1) + Tensor(x, 1)*Tensor(1, y) + Tensor(x, 1)*Tensor(y, 1)

* Test №1 is correct.
* Test №2 has a term `2*Tensor(y, y)` which should be zero (since I'm doing all calculations modulo 2, and, 2 % 2 == 0). How do I enforce that?
* Test №3 is correct.
* Test №4 does not multiply different `Tensor`s at all. `Tensor(1, x)*Tensor(1, y)` should be `Tensor(1, y*x)`, for example. How do I enforce that?

---

Context (if you're interested in why I'm doing this):

This is for calculating a bimodule resolution of an algebra over a `char=2` field. A bimodule resolution of an algebra `R` over a field `K` is a minimal projective resolution of the same algebra `R` over its enveloping algebra `R⊗R^op`. Here `op` means "multiplication works in the opposite direction". The enveloping algebra has both left and right action on the algebra:

    (a⊗b)*r == a*r*b
    r*(a⊗b) == b*r*a

There is a theorem that simplifies calculations in the case where a minimal projective resolution of the algebra over the field is known. Still, they are quite tedious and I want to stop doing them manually.

**Comment by jksuom** [comment]
I cannot reproduce these results because there is a Tensor class also in SymPy. Its printing method becomes involved:
```
>>> a, b = symbols('a b', commutative=False)
>>> Tensor(a, 1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "sympy/core/basic.py", line 398, in __repr__
    return sstr(self, order=None)
  File "sympy/printing/str.py", line 764, in sstr
    s = p.doprint(expr)
  File "sympy/printing/printer.py", line 233, in doprint
    return self._str(self._print(expr))
  File "sympy/printing/printer.py", line 257, in _print
    return getattr(self, printmethod)(expr, *args, **kwargs)
  File "sympy/printing/str.py", line 365, in _print_Tensor
    return expr._print()
AttributeError: 'Tensor' object has no attribute '_print'
>
```

I suppose some other name should be used.

**Comment by Pastafarianist** [comment]
@jksuom the script should work out-of-the-box if you run it separately. In case this is not an option, here is a [revised version](https://gist.github.com/Pastafarianist/f1bdf74161e9ada9a6e38895b2001f24) (I only did `s/Tensor/TP/g` there).

**Comment by jksuom** [comment]
It seems that `expand()` will always apply SymPy `Mul` instead of `TP.__mul__`. Therefore a custom version is needed, There should probably be a new class for "tensor expressions" like `Ym`, etc.

**Comment by Pastafarianist** [comment]
I have managed to accomplish this with:

* Implementing `__rmul__` in addition to `__mul__`
* Expanding the whole expression with `expand_mul` and `expand_multinomial`
* Manually going through the expression (which is of the form `Add(coefficient * (TP or Sum of TP)))) and applying all the remaining transformations.
