### ISSUE TITLE
SymPy claims that a triangle has a negative area

### ISSUE THREAD

**Issue by beling** [sympy/sympy#11920]
`Triangle(Point(0, 0), Point(2, 2), Point(4, 0)).area`
gives `-4`, but should `4`.

I have SymPy ver. 1.0.

**Comment by zorroblue** [comment]
I think it is related to the signed area. SymPy treats polygons as closed paths and also the given order of vertices are in clockwise order. So, I guess the sign of the area must be negative.
http://mathworld.wolfram.com/PolygonArea.html

**Comment by beling** [comment]
Thank you! I checked, and this is even mentioned in the area documentation. Everything is ok.
