### ISSUE TITLE
Q.prime returns False when it should return None

### ISSUE THREAD

**Issue by symbolique** [sympy/sympy#11925]
The documentation for `ask` gives the following example:
```py
>>> ask(Q.prime(x*y), Q.integer(x) &  Q.integer(y))
False
```
which is wrong if one integer is a unit.

**Comment by rohitrango** [comment]
Quite valid. @symbolique are you working on it? I want to fix it.

**Comment by symbolique** [comment]
Go ahead!

**Comment by Abdullahjavednesar** [comment]
@rohitrango are you still working on it? I wanna try this.

**Comment by rohitrango** [comment]
@Abdullahjavednesar Sure! I had just started anyway. :smile:
