### ISSUE TITLE
Add link to PDF docs to docs site

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#11927]
We build PDF docs with the release at https://github.com/sympy/sympy/releases, but people might not know about it. We should add a link to the release docs at http://docs.sympy.org/latest/index.html to the PDF docs. Probably the simplest solution would be to just add a sentence to the top that says "a PDF version of these docs can be found at https://github.com/sympy/sympy/releases".

**Comment by karthikchintapalli** [comment]
Hello, I am new to open source. I would like to work on this.

**Comment by mamakancha** [comment]
Has this issue been assigned?

**Comment by gxyd** [comment]
@mamakancha There is currently one PR #11929 for this issue, which has been approved.

**Comment by mamakancha** [comment]
@gxyd  Thanks for informing! In general, what should I do to get some issue assigned to me?

**Comment by gxyd** [comment]
You can first check if some pull request has already been submitted for the issue (you can ask others if you are not sure if there is already one), as is the current case. Otherwise just comment on the issue itself that "you are working on this issue".
