### ISSUE TITLE
Sphinx build failure in Travis

### ISSUE THREAD

**Issue by jksuom** [sympy/sympy#11930]
All sphinx builds have failed in Travis after docutils was updated to version 0.13.1. It looks like there is a bug in the new _html_base.py, most likely in image handling. This is a part of how the old doctools did translate lin_pend_nonmin_example.rst:
```
<div align="center" class="align-center"><img src="../../../../_images/pendulum_
nonmin.svg" /></div>
<p>The system will be modeled using both Kane&#8217;s and Lagrange&#8217;s metho
ds, and the
```
while this comes from 0.13.1:
```
<div align="center" class="align-center"> <img src="../../../../_images/pendulu
m_nonmin.svg" /> <p> The system will be modeled using both Kane&#8217;s and Lagr
ange&#8217;s methods, and the
```
Until that is fixed, we should probably arrange to load version 0.12 before sphinx is loaded.

**Comment by asmeurer** [comment]
https://github.com/sympy/sympy/pull/11935
