### ISSUE TITLE
Unicode issue with sympy.stats.FiniteRV

### ISSUE THREAD

**Issue by Erotemic** [sympy/sympy#11934]
This is an issue with a quick fix. 

In python 2.7 I kept getting an error 
`TypeError: s should have been string or Symbol`

when executing the following code 

```
import sympy
sympy.stats.FiniteRV('X', {0: .5, 1: .5})
```
it failed on my machine, but I checked and it worked on the live sympy terminal. 

Turns out the issue is that in `sympy/stats/rv.py` there is a check for `isinstance(s, str)`. 
On my machine I use unicode_literals and my 'X' is evaulated as a unicode character. 
By changing my code to use `sympy.stats.FiniteRV(str('X'), {0: .5, 1: .5})`, everything works. 

It would be nice to fix this in sympy by using `six` and changing all instances of  
`isinstance(s, str)` to `isinstance(s, six.text_type)`. It you don't want to add six as a dependency then 
six.text_type can easilly be defined somewhere as 
`text_type = (str, unicode) if sys.version_info.major == 2 else str`

**Comment by asmeurer** [comment]
We don't use `six` but we do have a compatibility file (sympy.core.compatibility) with `string_types` that should be used.

**Comment by mamakancha** [comment]
@asmeurer  Hi. I would like to get this issue assigned. Since I am a new-comer, I am having a bit-difficulty as to how I should go about solving this problem. Can you suggest something?

**Comment by patniharshit** [comment]
@mamakancha let me know if you aren't doing it. I want to do it too.

**Comment by rmagesh148** [comment]
@Erotemic @asmeurer I have fixed it as per your suggestion and the tests have passed. Thank you.

**Comment by mamakancha** [comment]
hi @asmeurer @Erotemic @rmagesh148 . I intend no offence here but I think it was pretty clear from the above thread that I was working on this issue. I have also made a pull request for the same about 11 hours ago. Kindly confirm it @rmagesh148 . Although I am getting some problems. They would be fixed very soon :)

**Comment by rmagesh148** [comment]
@mamakancha I am also a newbie to open-sourcing. I didn't know that I should wait for someone who was actually assigned this problem. I just tried doing it as it is "Easy to Fix" and please tell me if there is any way of reverting this back :) . I don't have a problem but if you know, please guide me on that. Thank you.

**Comment by mamakancha** [comment]
@rmagesh148  No problem there. I just wanted to make things clear so as to avoid any confusion. Although I am new user too but based on the very little experience I have, you should check this [link](https://github.com/sympy/sympy/wiki/Development-workflow).
Also You only pushed your changes to your forked repository only. You did not make a pull request to merge into the original sympy repository. (Just pointing it out in case that was not intentional.)
As far as reverting your push is concerned, I found this [link](http://stackoverflow.com/questions/6655052/is-there-a-way-to-rollback-my-last-push-to-git) very useful. You can check this one out.

**Comment by rmagesh148** [comment]
I believe I did [merge](https://github.com/sympy/sympy/pull/11945) my forked repo to the master:sympy, please let me know if that is wrong way of doing. Thank you.

**Comment by mamakancha** [comment]
@rmagesh148 Sorry. Did not check. Yes you have merged your repo with the original one [here](https://github.com/sympy/sympy/pull/11945). However since I am working on it I would suggest you to close your pull request.
I hope you understand that it was allotted to me first :)

**Comment by rmagesh148** [comment]
@mamakancha I did [close ](https://github.com/sympy/sympy/pull/11945) it. :) Thank you.

**Comment by mamakancha** [comment]
Submited a pull request for this issue with test. Please refer #11943
