### ISSUE TITLE
proposal: ccode of Max as concatenation of 2-parameter std::max

### ISSUE THREAD

**Issue by jhncls** [sympy/sympy#11953]
In  reference to the discussion with @bjodah in https://github.com/sympy/sympy/pull/11933:
ccode of `Max(...)` now simply returns `Max(...)` which is not a standard C function.
`std::max` only accepts 2 arguments, while sympy's Max accepts an arbitrary number of arguments.
Concatenation of n-1 two-argument calls of std:max could be a solution:
  `ccode(Max(x1,x2,x3,x4,x5))`
would then return
  `std::max(std::max(std::max(std::max(x1,x2),x3),x4),x5)`
Modern C++ compilers should generate quite optimal code in this case. Anyway, in practise, `Max` is very often used with just two arguments, in which case everything falls back to what's intuitively expected.
Typically, `Max` is used as a safe-keeping for other functions to receive their arguments in a valid range.
  `log(Max(x,0.000001))`
If there is only 1 argument, we just get the identity:
  `ccode(Max(x1))`
would just return
  `x1`
Not sure what 
  `ccode(Max(x1,x2,x3,x4,x5), user_functions={"Max":"my_max"})`
should do. Users targetting restraint hardware probably would also prefer two-argument versions.

Of course, the same proposal also addresses `Min`.

**Comment by bjodah** [comment]
I just remembered that in C99 we have `double fmax(double, double)` in `math.h`.
Hopefully modern compilers optimize nested calls to this as well.
