### ISSUE TITLE
diophantine doesn't find solutions for 2*x**2+y**2-16

### ISSUE THREAD

**Issue by sdemarre** [sympy/sympy#11956]
Diophantine returns the empty set but `{x=0,y=4}` and `{x=0,y=-4}` are solutions.
I suspect there is some issue with the solving of the elliptic case, as for example `10*x**2 + 12*x*y + 12*y**2 - 34` also doesn't return all solutions: it returns `{x=-1,y=2}` and `{x=1,y=1}` but fails to find `{x=-1,y=-1}` and `{x=1,y=-2}`

**Comment by pranjaltale16** [comment]
Hello,
I have started working on this problem.

**Comment by ayushjain19** [comment]
It returns all four possible solutions for 10*x**2 + 12*x*y + 12*y**2 - 34 when the parameter "permute" is passed as True in the Diophantine function. But yes, it returns an empty set for  2*x**2+y**2-16. Meanwhile I will try working on it. Suggestions are welcome.
