### ISSUE TITLE
printing.ccode regression for Max()

### ISSUE THREAD

**Issue by tommyolofsson** [sympy/sympy#11969]
The following works in version 1.0 but has since broken.
```
x = sp.symbols("x")
exp = sp.Max(0, x)
constants, not_c, c_expr = sp.printing.ccode(exp, human=False)
assert not not_c, not_c
```

**Comment by ArifAhmed1995** [comment]
@tommyolofsson The code does not yield an error for `Python-2.7` and Sympy version : '1.0.1-dev'. Can you tell me which Python version you are using ?

**Comment by asmeurer** [comment]
I bisected it to b3700eeeba1b6618b54442cf0bede1f7622bbe88. CC @bjodah

**Comment by tommyolofsson** [comment]
@ArifAhmed1995 I'm using Python 2.7.6. I think this is actually a fix that I incorrectly reported as a bug. The previous behavior of the code generator was to emit `Max(a, b)`with no indication of it not being a standard C function.

Would one not not expect something along the lines of `((a > b) ? a : b` instead?
