### ISSUE TITLE
Pretty printing with letter subscripts only works with some letters

### ISSUE THREAD

**Issue by nicolaje** [sympy/sympy#11972]
To reproduce the issue:
```python
from sympy import init_session
init_session()

for c in map(chr, range(97, 123)):
    s=Symbol("x_"+str(c))
    pprint(s)
    print(latex(s))
```

output:

```bash
IPython console for SymPy 1.0 (Python 3.5.2-64-bit) (ground types: python)

These commands were executed:
>>> from __future__ import division
>>> from sympy import *
>>> x, y, z, t = symbols('x y z t')
>>> k, m, n = symbols('k m n', integer=True)
>>> f, g, h = symbols('f g h', cls=Function)
>>> init_printing()

Documentation can be found at http://docs.sympy.org/1.0/
xₐ
x_{a}
x_b
x_{b}
x_c
x_{c}
x_d
x_{d}
xₑ
x_{e}
x_f
x_{f}
x_g
x_{g}
xₕ
x_{h}
xᵢ
x_{i}
x_j
x_{j}
xₖ
x_{k}
xₗ
x_{l}
xₘ
x_{m}
xₙ
x_{n}
xₒ
x_{o}
xₚ
x_{p}
x_q
x_{q}
xᵣ
x_{r}
xₛ
x_{s}
xₜ
x_{t}
xᵤ
x_{u}
xᵥ
x_{v}
x_w
x_{w}
xₓ
x_{x}
x_y
x_{y}
x_z
x_{z}
```

I would have expected the subscripts to be correct for all letters. Note this works correctly with numbered subscripts.

**Comment by nicolaje** [comment]
Ok, unicode only has subscripts for a subset of character:
https://en.wikipedia.org/wiki/Unicode_subscripts_and_superscripts

Is there a way to have symbols with letters subscript nicely rendered though?

**Comment by ngoonee** [comment]
Just came across this. It's my regrettable conclusion both from this and other similar print-related issues that latex output (probably in a jupyter notebook) is the way to go for proper display in a wide variety of circumstances. No real fault of sympy or pprint etc., either.

**Comment by oscargus** [comment]
As you noticed it is not really feasible to fix this without Unicode symbols for it. I close this, but be sure that once there are symbols it will happen,
