### ISSUE TITLE
Sympy integrates e^x strangely 

### ISSUE THREAD

**Issue by Terrydaktal** [sympy/sympy#11975]
On integrating e^x one gets a piecewise with the case, if log e=0 then int(e^x) = x,  which is impossible of course. Fix?

**Comment by jksuom** [comment]
The base of natural logarithms if written `E` in SymPy. For a general `e`, if `log(e) == 0`, then `e` and `e^x` are equal to 1.

**Comment by jksuom** [comment]
@Terrydaktal Can this issue be closed?

**Comment by oscarbenjamin** [comment]
This is what I get
```julia
In [11]: e = Symbol('e')                                                                                                                                      

In [12]: integrate(e**x, x)                                                                                                                                   
Out[12]: 
⎧   x                  
⎪  e                   
⎪──────  for log(e) ≠ 0
⎨log(e)                
⎪                      
⎪  x       otherwise   
⎩  
```
Given that e here is a symbol and doesn't represent E this is correct (at least for positive x).
