### ISSUE TITLE
powsimp() fails with noncommutative variables

### ISSUE THREAD

**Issue by Pastafarianist** [sympy/sympy#11981]
```python
import sympy as sp

x, y = sp.symbols('x, y', commutative=False)

v = (x*y)**2 * (y*x)**2
print(v)
print(sp.powsimp(v))
```

Output:

```
(x*y)**2*(y*x)**2
(x*y**2*x)**2
```

Needless to say, `xyxy yxyx != xyyx xyyx`.

The bug is apparently around [here](https://github.com/sympy/sympy/blob/master/sympy/simplify/powsimp.py#L384).

Possible fix: replace line 390 from

```python
if (e1 == e2 and e2.is_commutative):
```

to

```python
if (e1 == e2 and e2.is_commutative) and (not isinstance(b1, Mul) or not isinstance(b2, Mul)):
```

Is this the preferred way for testing whether an expression is a `Mul`?

**Comment by mamakancha** [comment]
I would like to get this one assigned too.

**Comment by jksuom** [comment]
```
                if nc_part:
                    b1, e1 = nc_part[-1].as_base_exp()
                    b2, e2 = term.as_base_exp()
                    if (e1 == e2 and e2.is_commutative):
                        nc_part[-1] = Pow(b1*b2, e1)
                        continue
  ```
This is not how non-commutative powers can be combined. That is possible when the bases are equal (but that is taken care of by the case `combine='exp'` above). Therefore this should be removed.

**Comment by mohit3011** [comment]
I would like to work on this issue if this issue is still open

**Comment by Pastafarianist** [comment]
@jksuom Noncommutative variables can still be combined with this code, at least in the case when one of the terms is just a single variable. Example:

```
(xy)^2 * x^2 → (xyx)^2
y^2 * (ab)^2 → (yab)^2
```

This is why I initially suggested checking for `not isinstance(..., Mul)`. Off the top of my head, I can't come up with any counterexamples to this when at least one of the terms is not a `Mul`.

Can I get this one assigned?

**Comment by jksuom** [comment]
You are welcome to send a PR if you have discovered a valid algorithm. But it seems to me that checking for `Mul` does not suffice: `(xy)^2 * x^2  = xyxyxx` is different from `(xyx)^2 = xyxxyx` in general.

**Comment by Pastafarianist** [comment]
@jksuom you're right. And apparently a few people have taken care of sending a PR for this already (https://github.com/sympy/sympy/pull/12008, https://github.com/sympy/sympy/pull/12009).
