### ISSUE TITLE
Typo Error in mathml.py

### ISSUE THREAD

**Issue by mamakancha** [sympy/sympy#11986]
In the file [https://github.com/sympy/sympy/blob/master/sympy/printing/mathml.py](https://github.com/sympy/sympy/blob/master/sympy/printing/mathml.py), there is a typo:
 in line `106`,  `# thing a coeff of 1 can remain` , `thing` should be replaced by `think`

**Comment by mamakancha** [comment]
PR has been requested for this issue. Please refer #11987

**Comment by SaiHarsh** [comment]
Is it still open? if yes can I work on this?

**Comment by mamakancha** [comment]
This issue has been resolved. Pull request has also been requested. Please refer #11987
