### ISSUE TITLE
lambdify() docs need a "Warning: Uses eval()"

### ISSUE THREAD

**Issue by user5061** [sympy/sympy#11990]
[sympify()](http://docs.sympy.org/latest/tutorial/basic_operations.html#converting-strings-to-sympy-expressions) has a warning: 

> Warning 
> sympify uses eval. Don’t use it on unsanitized input. 

`lambdify()` needs it as well since: 
```

import sympy 
some_str =  'exec("import os;print(os.getcwd())")'
sympy.lambdify(x, some_str, (sympy, numpy)) 

```

PS: How can I PR the doc instead of asking you to do so? I m relatively new to git and PRs.

**Comment by ArifAhmed1995** [comment]
Go through the Development Workflow page, everything related to contributing and testing is written there :
https://github.com/sympy/sympy/wiki/Development-workflow

**Comment by jtoka** [comment]
I will handle this issue

**Comment by moorepants** [comment]
One simple way to make a doc change like this is to find the file in the github interface, clock the little pencil to edit the file, and then when saving at the bottom, make a pull request from the change.

**Comment by jtoka** [comment]
@moorepants did what you suggested. Are you able to review the simple change?
