### ISSUE TITLE
Better way to compose rational functions 

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#12003]
I have a degree 17/degree 17 rational function in one variable with floating point coefficients with 1000 digits of precision. I would like to compose this with the Möbius transformation `(t - c)/(t + c)`. Here `c = 51/5` but in general it will be a similar fraction. I want the final rational function in expanded form (expanded polynomial/expanded polynomial)

The problem is that if you try just about any naive and even not so naive way of doing this, you lose a ton of precision as soon as you expand the polynomials. I finally figured out the following method for doing it without losing precision. 

Write `(t - c)/(t + c)` as `1 - 2*c/(t + c)`. Then the composition corresponds to a shift by 1, a composition with `-2*c*t`, an inversion (replacing `t` with `1/t`), and a shift by c. For the inversion we can make use of the fact that `P(1/t) == t**d*P'(t)`, where `d = deg(P)` and `P'` is `P` with the terms reversed. The `t**d` will cancel in the numerator and denominator because the numerator and denominator have the same degree. In other words, we just need to reverse the terms. 

The result is something like this

```py
mpmath.mp.dps = 1000 # This is needed to make Poly use full precision. I'll open a separate issue. 

frac = map(Poly, fraction(D))
for i in range(len(frac)):
    # Shift by 1
    frac[i] = frac[i].shift(1)
    # Compose with -2*c*t
    frac[i] = frac[i].compose(Poly(2*c*t))
    # Invert
    # XXX: Is there a better way than rep.rep
    frac[i] = Poly(reversed(frac[i].rep.rep), t)
    # Shift by c
    frac[i] = frac[i].shift(c)

n, d = frac
```

The resulting rational function, from what I can tell, does not lose precision. I believe the key here is that `shift` uses the Taylor shift algorithm. 

It would be nice to have some more direct support for this somehow.

**Comment by asmeurer** [comment]
CC @scopatz, c.f. recent commits to transmutagen.

**Comment by jksuom** [comment]
It seems that dup_transform should do this (with `p = 5*t - 51` and `q = 5*t + 51` to preserve precision). But maybe that is less efficient than dup_shift.

**Comment by asmeurer** [comment]
I don't know why, but when I was testing, `expr.subs(t, (5*t - 51)/(5*t + 51))` lost precision but ``expr.subs(t, (t - 51/5)/(t + 51/5))` kept it (this was before attempting any expansion). 

I didn't know about `dup_transform`. It doesn't seem to be exposed as `Poly.transform` (maybe because there's no `dmp_transform`?). It looks like exactly what I want (assuming it doesn't lose precision). 

I also noticed that there is `dup_scale` which isn't exposed either. I doubt it would end up being any different than using `compose`, but it would at least be cleaner.

**Comment by asmeurer** [comment]
I can upload the full expression I was testing with, if you are interested.

**Comment by asmeurer** [comment]
I just tested it and `dup_transform` does indeed seem to maintain precision.  I've exposed it as `Poly.transform` at https://github.com/sympy/sympy/pull/12021. This effectively fixes this issue for me (unless we want to try to "fix" the more naive methods as well).

**Comment by scopatz** [comment]
Just so I understand @asmeurer, where we using `dmp_transform` before then?

**Comment by jksuom** [comment]
It seems that 'transform' in `dup_transform` is comes from 'Moebius transform'. It is internally used for that purpose in `rootisolation`. Moebius transformations are the automorphims ot the projective line, and its generalizations to several variables are the automorphisms of the projective n-space (defined by n+1 linear forms in n+1, or n, variables). They have not been implemented in SymPy so far. That would probably be easier to do with sparse polynomials instead of DMP's.

**Comment by asmeurer** [comment]
Möbius transforms is exactly my use-case. I need to transform a function from [-1, 1] to [0, oo). 

What I would really want (and have wanted for some time) is a `Frac` object that represents rational functions (like `Poly` is to polynomials). Then `Frac.compose` would use this method internally. Working with two polys is not too difficult, but it gets annoying applying the same thing to the numerator and denominator everywhere, and it's easy to make mistakes.
