### ISSUE TITLE
Implementing Gamma Function(with integration) calculation for negative rational numbers (not negative integers as they are poles) giving Recursion Error 

### ISSUE THREAD

**Issue by Shikhar1998** [sympy/sympy#12025]
Gamma Function is undefined at negative integers but for saw a = -1/2(not an negative integer) in the  code( integrate(xaexp(-x), (x, 0, oo), conds='none')) ( i.e gamma(a + 1)  ) it should return
gamma(1/2) = sqrt(pi) a well defined value but however sympy gives a recursion error.

Am I missing out somewhere or sympy does not support it ?

**Comment by oscarbenjamin** [comment]
This seems fixed now in master:
```julia
In [90]: gamma(-S(1)/2)                                                                                                                                       
Out[90]: -2⋅√π
```
