### ISSUE TITLE
evalf doesn't round Floats correctly

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#12038]
```
In [19]: a = sympy.Float('-0.0000057867107664997448463499028244089449711571964804965971815969033830405123907539224808148514326235873144513304794471647300065550649')

In [20]: a.evalf(20)
Out[20]: -5.7867107664997448464e-6
```

The last digit is rounded as `4`, but in the original number we have `...34990`, so it should round to `3`.

@scopatz

**Comment by tyagi-iiitv** [comment]
a = sympy.Float('-0.0000057867107664997448463499028244089449711571964804965971815969033830405123907539224808148514326235873144513304794471647300065550649', 20) also gives -5.-5.7867107664997448464e-6

**Comment by isuruf** [comment]
First of all you should create `a` like,
```
a = sympy.Float('-0.0000057867107664997448463499028244089449711571964804965971815969033830405123907539224808148514326235873144513304794471647300065550649', 200)
```
otherwise it would use the default precision which is 32 bits.

Second, this is a problem with how sympy and mpmath hides info from the user. From the mpmath documentation,

>Mpmath uses binary arithmetic internally, while most interaction with the user is done via the decimal number system.

For evalf(20), mpmath has the following two representations to choose from,

```
In [121]: p=223862529800432098059 * S(2**S(-85))

In [122]: p.evalf(100)
Out[122]: 0.000005786710766499744846351626055918009430053400299343024926201906055212020874023437500000000000000000000

In [123]: q=223862529800432098058 * S(2**S(-85))

In [124]: q.evalf(100)
Out[124]: 0.000005786710766499744846325776661775727315213668777715838587027974426746368408203125000000000000000000000
```

`a` is rounded to `p` instead of `q`. Note that `a` has `...34990` while `p` has `...35162`.
When `p` is printed, it is rounded to the nearest decimal and becomes `...4`

**Comment by jksuom** [comment]
I think that is a good explanation. In more detail, when `a` is truncated, there are two possibilities `p` and `q`. When `_normalize` in mpmath is called with `rnd='n'`, it will choose `p` which is much closer to `a` than `q`. When `p` is printed in decimal form, the last digit is 4, but that does not mean loss of accuracy since the internal (binary) representation of `p` is the best approximation to `a`.

**Comment by asmeurer** [comment]
I see. So the Float rounding is actually what I want if I plan to use the number for floating point calculations. 

I can use the Python `decimal` module to round the decimal digits (`round(d, n - 1 - d.adjusted())` will round the `Decimal` `d` to `n` nonzero digits). I've felt before that it could be useful to have a SymPy wrapper around `decimal`, but that is a separate issue.

**Comment by scopatz** [comment]
It seems like for code gen we will also need to have a way to dump the hex rep too so we can get the exact binary version.

**Comment by asmeurer** [comment]
`a._mpf_` is an exact representation but it's not hex. It doesn't look like mpmath supports going to/from a hex representation, but that would be the place to implement it.

**Comment by scopatz** [comment]
Great!

**Comment by asmeurer** [comment]
I opened an upstream issue https://github.com/fredrik-johansson/mpmath/issues/345

**Comment by isuruf** [comment]
For codegen, are you using higher precision floating point types? If not, just `float(a)` would do.

**Comment by asmeurer** [comment]
We are comparing our results against published results that use 20 digits (and are apparently rounded using decimal arithmetic).

**Comment by bjodah** [comment]
I just came across this when writing test cases for rounding to `float32` and `float64` precision, here is
a failing case with just 12 figures:
```
In [1]: Float('0.1234567894').n(9)
Out[1]: 0.123456789

In [2]: Float('0.12345678949').n(9)
Out[2]: 0.123456789

In [3]: Float('0.123456789499').n(9)
Out[3]: 0.123456790

```

**Comment by isuruf** [comment]
That's expected. `Float('0.1234567894').n(9)` is not `0.123456789`. It is `8483885973*2**-36`. So when you subtract there is a small difference, but it is less than `10**-9`.

**Comment by bjodah** [comment]
@isuruf I see, so round should work then?

**Comment by isuruf** [comment]
Round should work. The difference you get is because of the behaviour of `sympify`.
Note that to sympy, `0.123456789` and `Float("0.123456789", 9)` are completely different things. Former has 53 bits of precision (15 decimal digits) while the latter has 9 decimal digits of precision.

```python
In [42]: Float('0.12345678949999999999999999999999').round(9) - 0.123456789
Out[42]: 6.01342586836751e-12

In [43]: Float('0.12345678949999999999999999999999').round(9) - Float("0.123456789", 9)
Out[43]: 0
```

**Comment by bjodah** [comment]
ok, but here is a counter example (at least I think so):
```
>>> Float('0.12345678949', 30).round(9) - Float('0.123456789', 30)
6.01342320442199707030786359940e-12
```
the only way I could get zero here is with the crazy `str`-hack:
```
>>> Float(str(Float('0.12345678949', 30).round(9)), 30) - Float('0.123456789', 30)
0

**Comment by bjodah** [comment]
So if Float.round lowers the precision, is there any way to make it higher again without going via `str`?

**Comment by isuruf** [comment]
Take a look at the source of `Float.round`. It creates a Rational (`rv`) of the type `a/10**n`. Instead of lowering the precision at the end, you can preserve the precision with a new method.

**Comment by asmeurer** [comment]
I didn't know about the round method. It seems it tries to do decimal rounding. This should perhaos be changed, or at least documented.

**Comment by smichr** [comment]
I added a [question](https://groups.google.com/forum/#!topic/sympy/3rUawNXT0Lc) of whether the 4 guard digits used during evaluation should actually be 5.

**Comment by smichr** [comment]
> the only way I could get zero here

As pointed out in #11704, when you round you "start over" with a new number at the requested rounded digit.

Here is your rational:
```python
>>> r = Rational('.12345678949'); r
12345678949/100000000000
```
Here is the best rational approximation of that rational *which cannot be represented exactly in binary* as a Float with 30 digits of decimal precision:
```python
>>> Rational(r, 30))
10016004691151914443264459427527/81129638414606681695789005144064
```
Here is `r` when rounded to 9 decimal places
```python
>>> Rational(Float('0.12345678949', 30).round(9)) <-- r rounded to 9
2120971485/17179869184
```
You wanted to subtract `0.123456789` (call it `R`) from `r` and get 0 but the best approximation to `R` is not the previous value shown:
```python
>>> R = Rational(Float('.123456789', 30)); R
10016004651398391620107185396591/81129638414606681695789005144064
```
...unless you also round *it* to 9 places:
```python
>>> Rational(_.round(9)) <-- R rounded to 9
2120971485/17179869184
```
