### ISSUE TITLE
Error in solveset for polynomial equation

### ISSUE THREAD

**Issue by zleba** [sympy/sympy#12032]
The "solve" gives fastly the result of:
`solve(x**4 +x -1, x)`
whereas "solveset" for the same equation fails:
`solveset(x**4 +x -1, x)`
It seems to be traped in infinite loop.

**Comment by zleba** [comment]
@mohit-raj I run it for 12 minutes without any result.
My laptop isn't so slow, it's Intel i3.
I have version 1.0-2 from the Ubuntu repository, maybe you have something else, more developed.
The solve(x4 +x -1, x) gives result in a second.

**Comment by jondo** [comment]
@zleba BTW, please edit your comments to use backticks (`) around code, otherwise the contained "**" is parsed as markup for bold text.

**Comment by oscargus** [comment]
In current master on my I7 laptop it takes about 25 ms. I'll add a test and close this.
