### ISSUE TITLE
Add contour plot function

### ISSUE THREAD

**Issue by chrstphrchvz** [sympy/sympy#12034]
(Mentioned on [gitter](https://gitter.im/sympy/sympy?at=58740606cbcb2817704aa5dd), no responses yet.)

I saw 2d plots mentioned on [this wiki page](https://github.com/sympy/sympy/wiki/Plotting-capabilities#types-of-plots), but I understand that might be outdated/inaccurate.

Looking through what `plot3d()` does, I used `Plot(ContourSeries(…)).show()` as a workaround.
It seems like much of the infrastructure is in place to support a contour plotting function, would there be any difficulty doing so?

**Comment by asmeurer** [comment]
My guess is it wouldn't be too difficult to add it.

**Comment by zaz** [comment]
Sorry if this is user error, but why can I not find `contour_plot` alongside `plot`, `plot3d` and other such functions?

    >>> sp.__version__
    '1.10.1'
    >>> sp.plotting.contour_plot
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
    AttributeError: module 'sympy.plotting' has no attribute 'contour_plot'

**Comment by chrstphrchvz** [comment]
@zaz the function is named `plot_contour`, see https://github.com/sympy/sympy/pull/14896#issuecomment-405382223

**Comment by oscarbenjamin** [comment]
Maybe the `plot_contour` function should be exposed at top-level like `from sympy import plot_contour`.

**Comment by zaz** [comment]
Sorry for mixing that up, but that is not there either:

    >>> sp.__version__
    '1.10.1'
    >>> sp.plotting.plot_contour
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
    AttributeError: module 'sympy.plotting' has no attribute 'plot_contour'

And the only mention of "contour" in `help(sp.plotting)` is under `plot_implicit`:

> ...
> a generating a **contour** using a mesh grid of fixed number of points. By
> ...

Even though I can see `def plot_contour` and docstring in `~/.local/lib/python3.9/site-packages/sympy/plotting/plot.py`

**Comment by oscarbenjamin** [comment]
It can be imported like this:
```python
In [6]: from sympy.plotting.plot import plot_contour

In [7]: plot_contour(sin(x)*sin(y), (x, -5, 5), (y, -5, 5))
Out[7]: <sympy.plotting.plot.Plot at 0x7fbc9c11d550>
```
It should probably be easier to import though (i.e. from sympy directly).

**Comment by zaz** [comment]
Why not add it under `sympy.plotting.`? That seems like the natural place for it.

I'm totally ignorant of the internals here, I'm just commenting based on where I would expect it as an inexperienced Sympy user.

PR #23591

**Comment by fergusbabb** [comment]
Thanks for this, but how can I plot a colourmap with sympy? I need the plots to be solid heat maps rather than wire grid contour plots
