### ISSUE TITLE
Install mpmath using pip in .travis.yml

### ISSUE THREAD

**Issue by isuruf** [sympy/sympy#12053]
It seems the tests weren't installing mpmath at all and we were relying on a mpmath installed in the environment. A change in the python 3.5 env makes the jobs fail now.

https://travis-ci.org/sympy/sympy/jobs/192727874

**Comment by Dakurels** [comment]
I would like to fix it :)

**Comment by yashsharan** [comment]
@isuruf I think i have made the necessary changes to fix this bug but dont know how to test it. Do i have to run ./setup.py test command to make sure my changes have been made are corrrect?

**Comment by madan96** [comment]
@yashsharan If you have made changes to `.travis.yml`, you can activate Travis CI for your fork and see if the issue is resolved or not.
