### ISSUE TITLE
Test with gmpy2 on travis

### ISSUE THREAD

**Issue by isuruf** [sympy/sympy#12054]
gmpy is not maintained anymore and gmpy2 is the successor of gmpy.

**Comment by yashsharan** [comment]
I wont to work on this..can you guide me how? I'm new here

**Comment by isuruf** [comment]
See https://github.com/sympy/sympy/blob/master/.travis.yml

**Comment by baoqchau** [comment]
#12057

**Comment by baoqchau** [comment]
#12057 @isuruf Can you help me check this please? Thanks a lot.
