### ISSUE TITLE
Better input validation for nsolve

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#12052]
From https://stackoverflow.com/questions/41687908/python-nsolve-solve-triple-of-equations:

```

In [22]: eq1 = x - y + 3

In [23]: eq2 = x + y

In [24]: eq3 = z - y

In [25]:

In [25]: print(nsolve( (eq1, eq2, eq3), (x,y,z), (-50,50)))
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/Users/aaronmeurer/anaconda3/lib/python3.5/site-packages/mpmath/calculus/optimization.py in findroot(ctx, f, x0, solver, tol, verbose, verify, **kwargs)
    927         try:
--> 928             fx = f(*x0)
    929             multidimensional = isinstance(fx, (list, tuple, ctx.matrix))

TypeError: <lambda>() missing 1 required positional argument: '_Dummy_24'

During handling of the above exception, another exception occurred:

TypeError                                 Traceback (most recent call last)
<ipython-input-25-56280812593e> in <module>()
----> 1 print(nsolve( (eq1, eq2, eq3), (x,y,z), (-50,50)))

/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/utilities/decorator.py in func_wrapper(*args, **kwargs)
     89         dps = mpmath.mp.dps
     90         try:
---> 91             return func(*args, **kwargs)
     92         finally:
     93             mpmath.mp.dps = dps

/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/solvers/solvers.py in nsolve(*args, **kwargs)
   2784     J = lambdify(fargs, J, modules)
   2785     # solve the system numerically
-> 2786     x = findroot(f, x0, J=J, **kwargs)
   2787     return Matrix(x)
   2788

/Users/aaronmeurer/anaconda3/lib/python3.5/site-packages/mpmath/calculus/optimization.py in findroot(ctx, f, x0, solver, tol, verbose, verify, **kwargs)
    929             multidimensional = isinstance(fx, (list, tuple, ctx.matrix))
    930         except TypeError:
--> 931             fx = f(x0[0])
    932             multidimensional = False
    933         if 'multidimensional' in kwargs:

TypeError: <lambda>() missing 2 required positional arguments: '_Dummy_23' and '_Dummy_24'
```

The problem is that the initial guess vector only has length 2. 

I also noticed if you forget to pass the initial guess:

```
In [26]: nsolve((x + y, x - y), (0, 1))
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-26-8797cce2cd81> in <module>()
----> 1 nsolve((x + y, x - y), (0, 1))

/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/utilities/decorator.py in func_wrapper(*args, **kwargs)
     89         dps = mpmath.mp.dps
     90         try:
---> 91             return func(*args, **kwargs)
     92         finally:
     93             mpmath.mp.dps = dps

/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/solvers/solvers.py in nsolve(*args, **kwargs)
   2768         return Float(findroot(f, x0, **kwargs))
   2769
-> 2770     if len(fargs) > f.cols:
   2771         raise NotImplementedError(filldedent('''
   2772             need at least as many equations as variables'''))

TypeError: object of type 'NoneType' has no len()
```

Based on the code it looks like it is trying to set the symbols from `expr.free_symbols.copy()`, but it should require them to be passed for a system.

**Comment by kritkaran94** [comment]
@asmeurer I would like to work on this. Can you tell me how to start on this ?

**Comment by yashsharan** [comment]
Hello i'm new here and want to solve this bug.Can you tell me from where i should start?

**Comment by mohit-raj** [comment]
@asmeurer  I would like to know Why can't i add these lines, for auto assigning of variables in case we forgot:
if fargs is None:
        fargs = f.free_symbols.copy().

**Comment by asmeurer** [comment]
@mohit-raj free_symbols is a set. It has no order. The order of `fargs` could be arbitrary. The user needs to specify the symbols so that it is clear which corresponds to which points.

**Comment by mohit-raj** [comment]
@asmeurer It means while extracting symbols from f we need to maintain the order.

**Comment by asmeurer** [comment]
The order has to be specified in the arguments to nsolve. Three arguments should be required when the input is a system.

**Comment by tanayag** [comment]
@mohit-raj yes we need to extract symbols in ordered way otherwise, we'll exchange the answers

Example:
`print(nsolve((a,b,c),(x,y,z),(50,50,50)))
[-1.5]
[ 1.5]
[ 1.5]

and

print(nsolve((a,b,c),(y,x,z),(50,50,50)))
[ 1.5]
[-1.5]
[ 1.5]`

so we can't just use frags = f.free_symbols
as here:

![screenshot from 2017-01-25 04-38-44](https://cloud.githubusercontent.com/assets/16465642/22271009/7631078c-e2b8-11e6-9588-9279de2cc7e5.png)


am I right @asmeurer 

so what exactly you want us to do? @asmeurer

**Comment by asmeurer** [comment]
The examples I listed above should give better error messages.

**Comment by tanayag** [comment]
working on it

**Comment by tanayag** [comment]
elif len(args) == 2:
        f = args[0]
        fargs = None
        x0 = args[1]
        for func0 in f:
               if len(func0.free_symbols)>1:
                       raise ValueError('expected a one dimensional function')

**Comment by mohit-raj** [comment]
@asmeurer I would like to have your valuable suggestion on this :
` if fargs is None:
            fargs = [ ]
            seen = [ ]
            out = [ ]    
            for i in f:
                temp = i.as_ordered_terms()
                for j in temp:
                    if(isinstance(j,Symbol)):
                        out.append(j)
        for m in out:
            if m not in seen:
                fargs.append(m)
                seen.append(m)`
It is taking symbols in an ordered way. Besides this i suppose preorder_traversal will also work.
Kindly do give suggestions.

**Comment by mohit-raj** [comment]
@asmeurer 
I would like to have any valuable suggestions on this code below.
It is maintaining order of variables. I think preorder_traversal would also work.
Kindly do give suggestions on this.

if fargs is None:
            fargs = [ ]
            seen = [ ]
            out = [ ]   
            for i in f:
                temp = i.as_ordered_terms()
                for j in temp:
                    if(isinstance(j,Symbol)):
                        out.append(j)
        for m in out:
            if m not in seen:
                fargs.append(m)
                seen.append(m)

**Comment by asmeurer** [comment]
@tanayag please wrap your code on GitHub with ``` so that it formats correctly.

**Comment by tanayag** [comment]
sorry @asmeurer 

```
elif len(args) == 2:   #line 2745 in solvers.py
        f = args[0]
        fargs = None
        x0 = args[1]
        for check_f in f:
                if len(check_f.free_symbols)>1:
                        raise ValueError('expected a one dimensional function')
```
since the user is not giving any variable(fargs=None), that means f should have only one dimensional equations,
so I am checking all the equations in f and anyone contains more then one variable
I will raise a ValueError

so will it work?

**Comment by tanayag** [comment]
@asmeurer I tried it 
but can't understand why the tests are failing #12093

**Comment by tanayag** [comment]
I have also looked upon 1st problem

and a little help here!

```
if len(args) == 3:
    f = args[0]
    fargs = args[1]
    x0 = args[2]

    if len(x0) != len(fargs):
            raise TypeError('nsolve expected exactly %i guess vectors, got %i'
                                       % (len(fargs), len(x0)))

```
u see
I can't find the length of x0(guess vector) if it is a single integer, since int type has no len()
or if fargs is just symbol(outside tuple/list whatever) since, Symbols type has no len() again

what should I do to, do this error right?

**Comment by asmeurer** [comment]
You can use the `iterable` function (see lower in the code) to check if `f` is an iterable.

**Comment by tanayag** [comment]
yep, now I guess it will work, running tests...

**Comment by tanayag** [comment]
@asmeurer please review #12106

**Comment by tanayag** [comment]
@asmeurer I guess we can merge and close the issue now!

**Comment by asmeurer** [comment]
Fixed by https://github.com/sympy/sympy/pull/12106
