### ISSUE TITLE
round for Float loses precision

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#12056]
The `__round__` method on `Float` uses `float`, which causes it to lose precision.

**Comment by asmeurer** [comment]
It seems only Python 3 supports returning a non-float from `round`. So this will need to be accounted for in the tests.

**Comment by jayankmayukh** [comment]
I'd like to fix this. I'm new to SymPy how should i begin?

**Comment by asmeurer** [comment]
Look in `sympy/core/numbers.py`.

**Comment by jayankmayukh** [comment]
Using decimal instead of float should work, right?

**Comment by nilabja10201992** [comment]
I've pulled a request after applying necessary changes 
https://github.com/sympy/sympy/pull/12063

**Comment by jayankmayukh** [comment]
Is there any method to check precision of a Float? I could not find one

**Comment by asmeurer** [comment]
The binary precision is in the _prec attribute. I believe there should be a function or method to convert that to decimal precision.

**Comment by jayankmayukh** [comment]
I've created a new pull request, I hope it fixes the issue.

**Comment by mohit9727** [comment]
@asmeurer  
i have an alternate solution i would like to contribute to this issue as well.
@jayankmayukh can you tell me your progress so that i can come along or suggest you my approach?

**Comment by mohit9727** [comment]
@asmeurer  @jayankmayukh  
We can have the hex storage of that float number 
` x.hex()
'0x1.921f9f01b866ep+1'
`

**Comment by jayankmayukh** [comment]
@mohit9727 I guess we should leave anything related to float, cuz that would mean we're dealing with binary to decimal conversion, which is not accurate.

**Comment by mohit9727** [comment]
My approach is: system actually reads the Hex value to be generated for any
float number and storing that number directly will be lossless.

**Comment by jayankmayukh** [comment]
See the problem is same even if one stores the values in hex, because certain decimal numbers such as 0.1 have no exact representation in bin, Oct, hex or any related number system. we use classes like decimal, Float, etc. to escape that kind of problem.
have a look on this
https://docs.python.org/2/library/decimal.html

**Comment by mohit9727** [comment]
in that case, can we use the rational number concept, just convert them to p/q form as integers and store them? we have a function for it too.
`x = 3.14159
 x.as_integer_ratio()
(3537115888337719, 1125899906842624)`

**Comment by jayankmayukh** [comment]
But how will you round a rational number? you'll convert it to Float or a similar class anyway.

**Comment by asmeurer** [comment]
Using the binary representation *is* correct but the issue here is that we shouldn't be using `float`. We need to use `Float`, which is a wrapper around `mpmath.mpf`, since that is arbitrary precision. Consider for instance `round(pi.evalf(100), 50)`. This should give pi to 51 digits.

**Comment by asmeurer** [comment]
Basically, `evalf` does the right algorithm, except you need to account for the difference between the number of digits (what `evalf` returns) and the number of places after the decimal (what `round` wants).

**Comment by jayankmayukh** [comment]
I've switched from Decimal to mpmath.mpf, see if that serves the purpose.

**Comment by barun511** [comment]
I've sent in a patch that solves this issue, but I'm not completely happy with my approach to it. Could you review it and let me know, so I can fix/fine tune? 
#12076

**Comment by chiranthsiddappa** [comment]
Needs base 2 rounding, based on what python's round does. evalf does that already, should be in mpmath already. Ex, round even.

**Comment by ishanSrt** [comment]
When is even the `__round__` method called? I am referring to the method in https://github.com/sympy/sympy/blob/e01729f7e7f9d43df711084dde431aad4461b792/sympy/core/numbers.py#L583

**Comment by asmeurer** [comment]
@ishanSrt it is called when using the `round` built in function. But be sure to use Python 3. In Python 2 `__round__` is not used.

**Comment by abhimanyuchaudhary** [comment]
Is this issue still open, I'd like to take it up

**Comment by Shreya610** [comment]
I have made new round function
import math
def new_round(f,n):
 z=int(f*math.pow(10,n+1))
 x1=int(((z%10)*2)/10)
 x2=float((int(z/10)+x1)/math.pow(10,n))
 return x2

**Comment by oscarbenjamin** [comment]
The change should be made to the Float.__round__ method.so that the ordinary round function works.

**Comment by smichr** [comment]
What about something that accomplishes this:
```python
def r(f, n):
  i = ceiling(f*10**n)
  return Float(Rational(i, 10**n), len(str(i)) or n) # use better way to get len(str(i))
```

**Comment by asmeurer** [comment]
Probably it can be done more efficiently than that. I was going to suggest to look at how mpmath does it but it looks like [mpmath uses `float(self)` as well](https://github.com/fredrik-johansson/mpmath/blob/e0ec6e894465c276448d42669f0b838071662199/mpmath/ctx_mp_python.py#L232)!

**Comment by oscarbenjamin** [comment]
How about:
```
In [20]: r = lambda f, n: f.evalf(ceiling(log(f, 10))+n)                                                                                       

In [21]: r(pi, 3)                                                                                                                              
Out[21]: 3.142
```

**Comment by smichr** [comment]
Or:

```python
>>> q= lambda f, n: f.evalf(integer_log(ceiling(f*10**n),10)[0] + 1)
>>> q(pi,3)
3.142
>>> q(100,2)
100.00
>>> r(100,2)
100.0

>>> timeit('q(Float(str(random.random())),4)','''
... import random
... from sympy import integer_log, ceiling,Float
... q = lambda f, n: f.evalf(integer_log(ceiling(f*10**n),10)[0] + 1)''',number=1000)
2.67067694664
>>> timeit('q(Float(str(random.random())),4)','''
... import random
... from sympy import log, ceiling,Float
... q = lambda f, n: f.evalf(ceiling(log(f, 10))+n)''',number=1000)
15.5046191216
```

What about the initial precision? If the required rounding is greater than the given precision then the digits past the given precision should be zero, shouldn't they?

```python
>>> from mpmath.libmp.libmpf import dps_to_prec, prec_to_dps
>>> prec_to_dps(Float(pi.n(),3)._prec)
3
```

**Comment by smichr** [comment]
We want `round(Float(1.54_321), 2)) == round(Float(1.54_123), 2))`, I think. When it's not a Python result I am not sure these two will be the same. (But maybe this is already handled.)

**Comment by asmeurer** [comment]
Also be aware of the caveat at https://docs.python.org/3/library/functions.html#round. `round` should work directly on the base 2 representation. `round(x, n)` is just `x.evalf(N)` where `N` is `n` plus the number of digits to the left of the decimal.

**Comment by smichr** [comment]
I think all the work is done:
```
def round(f, n):
    if PY3 and isinstance(f, Number):
        return f.round(n)
    return float(f, n)
```
from the `round` docstring,
```
Do not confuse the Python builtin function, round, with the
SymPy method of the same name. The former always returns a float
(or raises an error if applied to a complex value) while the
latter returns either a Number or a complex number:
```

**Comment by smichr** [comment]
#### Comments

1. I removed the Easy label: this is a subtle problem with lots of issues to [consider](https://stackoverflow.com/questions/9751476/float-and-round-in-python-2-and-3). It could be easy in the end to implement but it seems to me there are many corner cases to be concerned with along the way.

1. by "lose precision" is meant that applying `float` to a number will keep only 15 digits of precision -- not accuracy -- so 
```
>>> round(Float('1234567890123456789.12'), 1)*10 != 12345678901234567891
True
>>> round(Float('1234567890123456789.12'), 1)*10
1.2345678901234567e+19
>>> int(_)
12345678901234567168

The round method keeps track of full precision

>>> Float('1234567890123456789.12').round(1)*10
12345678901234567891.
```

1. if I understand correctly, in Py 2 `round` must always return a float; I'm not sure we want the Py 3 version to do anything different (other than that it will round to the even). But that is something that SymPy doesn't have to worry about. All we have to do is have a `__float__` method that will give round 15 digits of precision of a number and it will handle the rest.

Is there actually anything to do with this issue? The only thing apparent to me is to update the `round` method so it rounds towards the even last digit when half way between alternatives. And since this is a custom `round` method anyway, aren't we free to make it follow py 3.6 semantics regardless of the version? (Right now, it rounds up.)

**Comment by cbm755** [comment]
If what mpmath does it not ideal, shouldn't we fix it there?

Am I right from reading the docs that @asmeurer linked that on Python 3 we are allowed to return a Float (not a `float`) from `__round__` if the result is non-integer?  If so, that is good news!  Or did they mean that only "for the built-in types"?

**Comment by asmeurer** [comment]
`round` can return any object:

```py
>>> class Test:
...     def __round__(self):
...         return self
>>> round(Test())
<__main__.Test object at 0x11d3927b8>
```

**Comment by asmeurer** [comment]
I agree it isn't easy (the number of failed attempts shows that). I also agree we should just implement Python 3 semantics. We are dropping Python 2 support after the next version anyway.

**Comment by smichr** [comment]
Then what is posted [here](https://github.com/sympy/sympy/issues/12056#issuecomment-477819741) is probably the way forward. But do we want to make our round following the new convention of rounding to even?

**Comment by asmeurer** [comment]
I think it's fine to change to match the convention. In general I think `round(x)` should be the same as `round(Float(x))` if `x` is a `float`. We can add a keyword argument to `Float.round` to select other rounding strategies. It doesn't look like `round` is used very much in library code so it hopefully shouldn't break anything (I do see one use in `evalf.py` that should be checked). 

Round to even generally has [nicer mathematical properties](https://mathematica.stackexchange.com/questions/2116/why-round-to-even-integers) than round away from zero.
