### ISSUE TITLE
pickling tests fail

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#12067]
I think it doesn't fail when the full test suite is run (Travis hasn't been failing at any rate):

```
./bin/test pickling
==================================================================== test process starts =====================================================================
executable:         /Users/aaronmeurer/anaconda/envs/python2/bin/python  (2.7.11-final-0) [CPython]
architecture:       64-bit
cache:              yes
ground types:       python
random seed:        1029014
hash randomization: on (PYTHONHASHSEED=1794464771)

sympy/utilities/tests/test_pickling.py[33] ...........EE....................                                                                            [FAIL]

______________________________________________________________________________________________________________________________________________________________
___________________________________________________ sympy/utilities/tests/test_pickling.py:test_Singletons ___________________________________________________
  File "/users/aaronmeurer/documents/python/sympy/sympy/sympy/utilities/tests/test_pickling.py", line 180, in test_Singletons
    S.EmptySet, S.IdentityFunction):
  File "sympy/core/singleton.py", line 45, in __getattr__
    name, self))
AttributeError: Attribute 'EmptySet' was not installed on SymPy registry S
______________________________________________________________________________________________________________________________________________________________
___________________________________________________ sympy/utilities/tests/test_pickling.py:test_functions ____________________________________________________
  File "/users/aaronmeurer/documents/python/sympy/sympy/sympy/utilities/tests/test_pickling.py", line 207, in test_functions
    others = (chebyshevt_root, chebyshevu_root, Eijk(x, y, z),
  File "sympy/functions/special/tensor_functions.py", line 27, in Eijk
    return LeviCivita(*args, **kwargs)
  File "sympy/core/cache.py", line 93, in wrapper
    retval = cfunc(*args, **kwargs)
  File "sympy/core/compatibility.py", line 807, in wrapper
    result = user_function(*args, **kwds)
  File "sympy/core/function.py", line 411, in __new__
    if n not in cls.nargs:
  File "sympy/core/function.py", line 219, in nargs
    return FiniteSet(*self._nargs) if self._nargs else S.Naturals0
  File "sympy/core/singleton.py", line 45, in __getattr__
    name, self))
AttributeError: Attribute 'Naturals0' was not installed on SymPy registry S

================================================== tests finished: 31 passed, 2 exceptions, in 1.70 seconds ==================================================
DO *NOT* COMMIT!
```

My guess is that somehow the singleton registry is in a different state when just the pickling tests are run vs. when the full tests are run.

**Comment by madan96** [comment]
I would like to work on this issue.

By different state are you referring to different paths from which they run?

**Comment by asmeurer** [comment]
Yes.

**Comment by SACHIN-13** [comment]
I would like to work on it. Please guide me as to where shall I start from??
I'm comparatively new to sympy and going through the singleton class to understand this issue.

**Comment by jksuom** [comment]
It seems that if `SingletonRegistry()` is pickled it will lose the classes waiting to be installed.
```
>>> from sympy.core.singleton import SingletonRegistry, S
>>> S._classes_to_install
{'Integers': <class 'sympy.sets.fancysets.Integers'>,
'EmptySequence': <class 'sympy.series.sequences.EmptySequence'>,
'Naturals0': <class 'sympy.sets.fancysets.Naturals0'>,
'UniversalSet': <class 'sympy.sets.sets.UniversalSet'>,
'BooleanTrue': <class 'sympy.logic.boolalg.BooleanTrue'>,
'Naturals': <class 'sympy.sets.fancysets.Naturals'>,
'EmptySet': <class 'sympy.sets.sets.EmptySet'>,
'BooleanFalse': <class 'sympy.logic.boolalg.BooleanFalse'>}
>>> import pickle
>>> p = pickle.dumps(SingletonRegistry())
>>> S._classes_to_install
{}
```

**Comment by SACHIN-13** [comment]
Which section of code shall I go through to fix this? I went through `test_pickling` but couldn't understand what shall be done! Any suggestions??

**Comment by SACHIN-13** [comment]
> It seems that if SingletonRegistry() is pickled it will lose the classes waiting to be installed.

SingletonRegistry is already instantiated in `sympy.core.singleton` as S.
`>>> from sympy.core.singleton import SingletonRegistry, S
>>> import pickle
>>> S._classes_to_install
{'EmptySequence': <class 'sympy.series.sequences.EmptySequence'>, 'BooleanFalse': <class 'sympy.logic.boolalg.BooleanFalse'>, 'BooleanTrue': <class 'sympy.logic.boolalg.BooleanTrue'>, 'EmptySet': <class 'sympy.sets.sets.EmptySet'>, 'Integers': <class 'sympy.sets.fancysets.Integers'>, 'UniversalSet': <class 'sympy.sets.sets.UniversalSet'>, 'Naturals0': <class 'sympy.sets.fancysets.Naturals0'>, 'Naturals': <class 'sympy.sets.fancysets.Naturals'>}
>>> p = pickle.dumps(S)
>>> S._classes_to_install
{'EmptySequence': <class 'sympy.series.sequences.EmptySequence'>, 'BooleanFalse': <class 'sympy.logic.boolalg.BooleanFalse'>, 'BooleanTrue': <class 'sympy.logic.boolalg.BooleanTrue'>, 'EmptySet': <class 'sympy.sets.sets.EmptySet'>, 'Integers': <class 'sympy.sets.fancysets.Integers'>, 'UniversalSet': <class 'sympy.sets.sets.UniversalSet'>, 'Naturals0': <class 'sympy.sets.fancysets.Naturals0'>, 'Naturals': <class 'sympy.sets.fancysets.Naturals'>}
`
