### ISSUE TITLE
test_args fails on master

### ISSUE THREAD

**Issue by barun511** [sympy/sympy#12077]
On a clean master, the test_args suite fails. I've attached the log, since it's too big to put entirely into this message. 

This is probably a local issue, I just figured I should raise it anyway, just in case!
[err.txt](https://github.com/sympy/sympy/files/721861/err.txt)

**Comment by jksuom** [comment]
```
    <<<<<<< HEAD
               ^
IndentationError: expected an indented block
```
It seems that merging of master did not succeed. (Not 'a clean master'.)

**Comment by barun511** [comment]
Aha, thanks!
