### ISSUE TITLE
vlatex is broken

### ISSUE THREAD

**Issue by eugene-katsevman** [sympy/sympy#12078]
Say we have J_1O * alpha.diff()

![image](https://cloud.githubusercontent.com/assets/5425080/22182685/98999b34-e0bc-11e6-84a5-08dd77ba66c0.png)

and we want to substitute alpha with (beta - eta)

    print ((J_1O * alpha.diff()).subs(alpha, beta -eta))
    J_1O*Derivative(beta(t) - eta(t), t)

So, the internal representation is correct.

Then we do `latex` on it:

    print (latex((J_1O * alpha.diff()).subs(alpha, beta -eta)))
    J_{1O} \frac{d}{d t}\left(\beta{\left (t \right )} - \eta{\left (t \right )}\right)

![image](https://cloud.githubusercontent.com/assets/5425080/22182699/f1acc1c4-e0bc-11e6-82af-f8b3e3e941aa.png)

But I want the dot notation, so I use `vlatex` from physics.vector

    print (vlatex((J_1O * alpha.diff()).subs(alpha, beta -eta)))
    J_{1O} \dot{\beta} - \dot{\eta}

![image](https://cloud.githubusercontent.com/assets/5425080/22182713/4d417e76-e0bd-11e6-803d-c227c1c96630.png)

which is clearly wrong, since brackets are missing.

**Comment by maurogaravello** [comment]
I tried to correct this bug. I add '_needs_mul_brackets' in sympy/physics/vector/printing.py.
Pull request #12125

**Comment by maurogaravello** [comment]
I think I corrected the problem. See the pull request #12299

**Comment by gxyd** [comment]
Fixed by #12299 . Closing.
