### ISSUE TITLE
test_latex fails with IndexError: List Index out of range

### ISSUE THREAD

**Issue by barun511** [sympy/sympy#12074]
When running the test suite, test_latex fails with the following error message.

`File "/home/barun511/Desktop/sympy/sympy/printing/tests/test_latex.py", line 161, in test_latex_permutation`

`    assert latex(Permutation()) == r"\left( \right)"`
 ` File "sympy/printing/latex.py", line 2153, in latex`
 `   return LatexPrinter(settings).doprint(expr)`
`  File "sympy/printing/latex.py", line 175, in doprint`
 `   tex = Printer.doprint(self, expr)`
`  File "sympy/printing/printer.py", line 233, in doprint`
    `return self._str(self._print(expr))`
`  File "sympy/printing/printer.py", line 257, in _print`
`    return getattr(self, printmethod)(expr, *args, **kwargs)`
`  File "sympy/printing/latex.py", line 316, in _print_Cycle`
`    if expr.array_form[-1] == siz - 1:`
`IndexError: list index out of range`

http://pastebin.com/KKCVxhWJ

The last commit on this master branch was commit 12e9c3fa46dc862455a428cae5bf36338478cb40

**Comment by jksuom** [comment]
The test for empty permutation in latex.py assumes that `Permutation.print_cyclic == True`.
```
    def _print_Cycle(self, expr):
        from sympy.combinatorics.permutations import Permutation
        if str(expr) == '()':
            return r"\left( \right)"
```
I could probably be replaced by the more robust condition `expr.size == 0`.

**Comment by hrushikesht** [comment]
I would like to fix this issue. From which file should I start?

**Comment by barun511** [comment]
test_latex seems to work fine after the suggested change. Note that the original issue could only be reproduced if you ran the full test suite...running test_latex by itself did not raise the exception.

Could somebody review the PR and let me know whether it's okay?
