### ISSUE TITLE
symbol name containing underscore leads to incorrect latex

### ISSUE THREAD

**Issue by gerritholl** [sympy/sympy#12090]
If a symbol name contains an underscore, the latex code generated fails to compile with `! Double subscript`:

```
In [365]: a_b = sympy.symbols('a_b')

In [366]: from sympy.abc import c

In [367]: sympy.printing.print_latex(sympy.IndexedBase(a_b)[c])
a_{b}_{c}
```

There should perhaps be a warning or error on sympys side to handle this, or it should generate `{a_{b}}_c` instead.

**Comment by oscargus** [comment]
Now this seems to generate `{a_{b}}_{c}` so I close this.
