### ISSUE TITLE
List of prime factors including multiplicity is missing

### ISSUE THREAD

**Issue by orlp** [sympy/sympy#12101]
The vast majority of the time when using prime factorization in algorithms I'm interested in a list of prime factors. E.g. for 24 it's `[2, 2, 2, 3]`. However sympy (to my knowledge) only provides `sympy.factorint` which returns a dictionary. I always end up writing a helper function:

    factorlist = lambda fac: sum(([p] * fac[p] for p in sorted(fac)), [])

It would be really nice if factorizations in this format were directly provided by sympy, either by an option to `factorint` (e.g. `sympy.factorint(24, aslist=True)`) or under a new function name entirely.

**Comment by smichr** [comment]
A possibility is:

```
>>> from sympy.utilities.iterables import multiset_combinations
>>> d={'a':3,'b':2,'c':2}
>>> list(multiset_combinations(d, sum(d.values())))[0]
['a', 'a', 'a', 'b', 'b', 'c', 'c']
>>> d = factoring(24)
>>> list(multiset_combinations(d, sum(d.values())))[0]
[2, 2, 2, 3]
```

But maybe an argument `multiple=True` for `factorint` would be preferable.

**Comment by orlp** [comment]
@smichr `multiple=True` is definitely better than my suggestion. I really do think that providing this functionality straight up without a helper function is an improvement for sympy.
