### ISSUE TITLE
linsolve not working

### ISSUE THREAD

**Issue by db87** [sympy/sympy#12117]
I have a set of 8 linear equations, representing two linear coupled optical cavities. I am getting weird results using `linsolve` to solve them.

Here is my code: I have the full set of equations that I solve first and then sub in some variable values, this gives a different result to when I sub in the variable values first and then solve
```
from sympy import *
from sympy.solvers.solveset import linsolve
from IPython.display import display

init_printing()

print(sympy.__version__)

a0, a1, a2, a3, a4, a5, a6, a7, a8 = var("a_{0:9}")
A, B, C, D = var("A B C D")

eqs = [
    a1 - (A*a4 + B*a6),
    a2 - (C*a1 + C*a0),
    a3 - (A*a2 + B*a8),
    a4 - (a3),
    a5 - (A*a8 + B*a2),
    a6 - (a5),
    a7 - (A*a6 + B*a4),
    a8 - (D*a7)
]

eqs2 = []
values = {A:0, B:1}

# Sub in values before solving
for i in range(len(eqs)):
    eqs2.append(eqs[i].subs(values))
    
S1 = linsolve(eqs, [a1, a2, a3, a4, a5, a6, a7, a8])
S2 = linsolve(eqs2, [a1, a2, a3, a4, a5, a6, a7, a8])

display.display(S1.subs(values))
display.display(S2)
```
This outputs:
![image](https://cloud.githubusercontent.com/assets/1877777/22515328/06c559b0-e89a-11e6-83db-1e11a2f3c95a.png)

There shouldn't be any `D` values in the S1 solution as the coupling should have been removed.

What is also an issue is if I set the second equation: `a2 - C*(a1+a0)`, I get the output:
![image](https://cloud.githubusercontent.com/assets/1877777/22515413/4a752104-e89a-11e6-8d08-29a7df2d8750.png)

This is using the git commit 0626a3043deb1, OSX, python 3.5

**Comment by db87** [comment]
Ignore the part regarding the `D` variable, this was just me missing a simplify....

The issue with the simplification of equation 2 still seems to be there though.

**Comment by anca-mc** [comment]
linsolve() uses the linear_eq_to_matrix() to put the system of equations into matrix form.
The coeff() method of the Expr class (expr module) is used by the linear_eq_to_matrix() method to 
put into rows the coefficients of the equations. The docstring of the coeff() method reads:

"no factoring is done, so 1 + z*(1 + y) is not obtained
        from the following:

        >>> (x + z*(x + x*y)).coeff(x)
        1

"

So expanding the equations before linsolve() is necessary.

**Comment by db87** [comment]
Thanks, that seems to fix it!
