### ISSUE TITLE
Why 1/S.Zero and limit(1/x,x,0) have different output ?

### ISSUE THREAD

**Issue by Shikhar1998** [sympy/sympy#12111]
```
>>> 1/S.Zero
oo~

>>>x = Symbol("x" ,Real = False)
>>> limit(1/x,x,0)
oo
```
Why are the 2 outputs different , 1/S.Zero = ComplexInfinity and limit(1/x,x,0) = oo
As in the complex plane the limit can be obtained from any direction.

**Comment by jksuom** [comment]
Actually, there are three possible outputs. `limit` assumes that its variable `x` is real. Then `1/x` is real, and so is its limit, which is from the right by default. Limit from the left is different:
```
>>> limit(1/x, x, 0, dir='-')
-oo
```
`1/0` is defined as the limit of `1/z` for a complex `z` tending to 0, hence it is the complex infinity.

**Comment by Shikhar1998** [comment]
@jksuom , I understand your point , but if I define x (i.e variable where x->0) to be defined in the complex plane the the answer should be complex infinity and independent of the direction as we can approach a point in the Argand plane from any direction but why I get an answer +oo.

```
>>> limit(1/(x.expand(complex = True)),x,0)
∞
```

**Comment by jksuom** [comment]
`limit` has keyword argument `dir` that has two values, `+` and `-`. If no `dir` is given, `+` will be the default value. That is why limit is from the right.

**Comment by Shikhar1998** [comment]
@jksuom , ya that justifies the reason, thanks for clarifying 👍
