### ISSUE TITLE
solve() leads to ZeroDivisionError: polynomial division

### ISSUE THREAD

**Issue by vog** [sympy/sympy#12114]
In sympy 1.0 with Python 3.5 I tried to solve the following system of polynomial equations:

```python
from sympy import symbols, solve

a, b, c, d, e, f, g = symbols('a b c d e f g')
terms = [
    1 + a*b + d*e,
    1 + a*c + d*f,
    1 + b*c + e*f,
    g - a**2 - d**2,
    g - b**2 - e**2,
    g - c**2 - f**2,
]
s = solve(terms, [a, b, c, d, e, f, g])
print('Solutions: {!r}'.format(s))
```

However, after ~15 seconds of computation, `solve()` fails with the following exception:

```
Traceback (most recent call last):
  File "<...>", line 14, in <module>
    s = solve(terms, [a, b, c, d, e, f, g])
  File "/usr/lib/python3/dist-packages/sympy/solvers/solvers.py", line 1055, in solve
    solution = _solve_system(f, symbols, **flags)
  File "/usr/lib/python3/dist-packages/sympy/solvers/solvers.py", line 1708, in _solve_system
    res = solve_poly_system(polys, *syms)
  File "/usr/lib/python3/dist-packages/sympy/solvers/polysys.py", line 49, in solve_poly_system
    return solve_generic(polys, opt)
  File "/usr/lib/python3/dist-packages/sympy/solvers/polysys.py", line 228, in solve_generic
    result = _solve_reduced_system(polys, opt.gens, entry=True)
  File "/usr/lib/python3/dist-packages/sympy/solvers/polysys.py", line 222, in _solve_reduced_system
    for solution in _solve_reduced_system(new_system, new_gens):
  File "/usr/lib/python3/dist-packages/sympy/solvers/polysys.py", line 184, in _solve_reduced_system
    basis = groebner(system, gens, polys=True)
  File "/usr/lib/python3/dist-packages/sympy/polys/polytools.py", line 6483, in groebner
    return GroebnerBasis(F, *gens, **args)
  File "/usr/lib/python3/dist-packages/sympy/polys/polytools.py", line 6523, in __new__
    G = _groebner(polys, ring, method=opt.method)
  File "/usr/lib/python3/dist-packages/sympy/polys/groebnertools.py", line 45, in groebner
    G = _groebner(seq, ring)
  File "/usr/lib/python3/dist-packages/sympy/polys/groebnertools.py", line 201, in _buchberger
    r = p.rem(f[:i])
  File "/usr/lib/python3/dist-packages/sympy/polys/rings.py", line 1446, in rem
    raise ZeroDivisionError("polynomial division")
ZeroDivisionError: polynomial division
```

**Comment by jksuom** [comment]
It seems that `p.rem(f[:1])`, that computes the remainder of the polynomial `p` modulo the ideal generated by `f[:i]`, does not allow any zeros in the generator list. It would probably suffice that not all generators vanish. But, in the construction of a Gröbner basis it is not necessary to include any zero polynomials. Hence they can be removed from the argument `F` of `GroebnerBasis.__new__`.
This is probably best done after the expressions in `F` have been transformed into polynomials in `polys`.

**Comment by tanayag** [comment]
@jksuom 
what is polynomials in `poly` ?
and how can I transform expressions in `F` into them??

**Comment by jksuom** [comment]
Elements of `F` are expressions:
```
(Pdb) p F
[x**3 - x, y**3 - y]
```
and the transformation takes place in `GroebneBasis.__new__`:
```
(Pdb) 
> /home/jks/sympy/sympy/polys/polytools.py(6573)__new__()
-> polys, opt = parallel_poly_from_expr(F, *gens, **args)
```
Elements of `polys` are objects of class `Poly`:
```
(Pdb) p polys
[Poly(x**3 - x, x, y, domain='ZZ'), Poly(y**3 - y, x, y, domain='ZZ')]
```

**Comment by rammanoj** [comment]
can I solve this issue?

**Comment by Omarkhursheed** [comment]
Hello,
If this issue hasn't been fixed yet, I would like to work on it.

**Comment by Gouenji** [comment]
please tell me if this issue has been fixed?
if not i would like to work on it

**Comment by jksuom** [comment]
It still leads to the same error:
```
>>> from sympy import *
>>> a, b, c, d, e, f, g = symbols('a b c d e f g')
>>> terms = [
...     1 + a*b + d*e,
...     1 + a*c + d*f,
...     1 + b*c + e*f,
...     g - a**2 - d**2,
...     g - b**2 - e**2,
...     g - c**2 - f**2,
... ]
>>> s = solve(terms, [a, b, c, d, e, f, g])
Traceback (most recent call last):
,
,
,
  File "sympy/polys/rings.py", line 1467, in rem
    raise ZeroDivisionError("polynomial division")
ZeroDivisionError: polynomial division
```

**Comment by prateekiiest** [comment]
Hi, I would also like to work on this issue.  
Can you tell me why this zero division error is arising?

**Comment by vog** [comment]
This surprises me, too. The commit by @skirpichev adds a test case which is almost identical to the input program I gave. So I wonder why that test case would work, but my original program wouldn't.

**Comment by valglad** [comment]
@jksuom I'm not getting the error after making the change in polytools.py as in skirpichev's commit.

**Comment by jksuom** [comment]
This [comment](https://github.com/sympy/sympy/issues/12114#issuecomment-276589219) explains why that is to be expected. The reason is that zero polynomials are removed before they reach the critical `p.rem(f[:i])` call. Any way of removing the zeros will suffice.

**Comment by valglad** [comment]
Yes, I understand why it should work, and it does. But you commented after the commit that "it still leads to the same error", which it doesn't for me.

**Comment by jksuom** [comment]
That was another comment showing that it was not fixed, a reply to this [comment](https://github.com/sympy/sympy/issues/12114#issuecomment-277580851).

**Comment by valglad** [comment]
But the commit by skirpichev fixes it, so the answer to that comment should be that the issue is essentially fixed, it's just a matter of adding what skirpichev did. Sorry if I'm missing something. Is this because skirpichev didn't pull a request? Should someone else do it instead?

**Comment by jksuom** [comment]
> commit by skirpichev fixes it

Ah, I see. It may seem confusing, but that was a commit  to skirpichev/diofant, not to sympy/sympy. A separate PR to sympy is expected. It need not be a copy of skirpichev's commit. There are other possibilities.

**Comment by valglad** [comment]
Oh, okay. Skirpichev's thing is the most obvious one, so I'll do that in a bit (I haven't created pull requests before though I've read the instructions so hopefully it'll work fine).
