### ISSUE TITLE
[regression from 0.7] coeff(x, n=0) doesn't work correctly in some cases

### ISSUE THREAD

**Issue by nschloe** [sympy/sympy#12132]
From the expression `a` I'd like to get all terms in which `x` does not occur (i.e., `a`). This
```python
import sympy

a = sympy.Symbol('a')
x = sympy.Symbol('x')

expr = a
print(expr.coeff(x, n=0))
```
works fine.

However, if you replace `a` by `-a`, `coeff` will return `0`
```python
expr = -a
print(expr.coeff(x, n=0))
```
Expected: `-a`.

This is a regression from 0.7.6.1 where everything worked fine.

**Comment by prateekiiest** [comment]
Yeah, its printing 0. Can you specify the code part??

**Comment by nschloe** [comment]
The offending funtion is [here](https://github.com/sympy/sympy/blob/master/sympy/core/expr.py#L1107). Haven't looked into what's going wrong exactly though.

**Comment by prateekiiest** [comment]
Thanks, I'm looking into it

**Comment by nschloe** [comment]
[This line](https://github.com/sympy/sympy/blob/master/sympy/core/expr.py#L1245) is responsible. Looking at `as_independent`.

**Comment by prateekiiest** [comment]
Yeah, it has not taken into account the possibility of the coeff. to be negative.

**Comment by nschloe** [comment]
What probably makes a difference: `a` is a `<class 'sympy.core.symbol.Symbol'>`, `-a` is a `<class 'sympy.core.mul.Mul'>`.

**Comment by smichr** [comment]
Is your SymPy up to date? With the current head I get:

```
>>> from sympy import *
>>> y.coeff(x)
0
>>> y.coeff(x,0)
y
>>> (-y).coeff(x)
0
>>> (-y).coeff(x,0)
-y
```

Other than the docstring being wrong (indicating that `None` might be returned) I don't see a problem.

**Comment by nschloe** [comment]
@smichr Good call. Just tested master and found that the issue is fixed. Apparently this is only present in the 1.0 release. How unfortunate!
