### ISSUE TITLE
integrate(1/x**2,(x,-oo,oo)) give 0

### ISSUE THREAD

**Issue by kulalexey** [sympy/sympy#12133]
Correct answer is oo

**Comment by adeak** [comment]
It seems that `integrate(1/x**2,(x,-oo,0))` is `-oo` (using 1.0). Doesn't look good. (And even then the 0 result would only be a correct result in the principal value sense, but that's another matter).

Adding any finite upper limit for the above integral obviously works fine. I suspect the limit of the antiderivative might be to blame: `limit(-1/x,x,0)` without a direction gives `-oo`. If this is the reason, perhaps definite integrals should implicitly use `dir='-'` for their upper limits?

**Comment by jksuom** [comment]
This direction issue was fixed in https://github.com/sympy/sympy/pull/11889.

**Comment by jksuom** [comment]
Closed by #12142
