### ISSUE TITLE
Simplify does not always work with inverse trigonometric functions 

### ISSUE THREAD

**Issue by killerrex** [sympy/sympy#12140]
The simplification of an inverse trigonometric function depends of what surrounds it:

```python
>>> from sympy import *

>>> x = Symbol('x')

# This prints x as expected
>>> simplify(asin(sin(x)))
x

# Notice the only difference is the initial sign
>>> simplify(-asin(sin(x)))
-asin(sin(x))
```
The same happens with the other trigonometric functions (cos, tan, csc...)

The opposite order works fine:
```python
>>> sp.simplify(sin(asin(x)))
x
>>> sp.simplify(-sin(asin(x)))
-x
# But is because the sin-asin is cancelled before simplify
>>> sin(asin(x))
x
# And asin-sin not:
>>> asin(sin(x))
asin(sin(x))
```

Tested with Sympy 1.0 and python 3.5 in windows and opensuse tumbleweed.

**Comment by mohit3011** [comment]
I want to work on this issue , can you specify code part or any starting point ?

**Comment by killerrex** [comment]
I have reduced my case to this small test code:
```python
from sympy import *

x = Symbol('x')

f = asin(sin(x))
g = -f

a = simplify(f)
b = simplify(g)
```

For what I check with the debugger when the main function is the *f* the code enters in the following lines of simplify (lines 523-530 of simplify.py):
```python
    if not isinstance(expr, (Add, Mul, Pow, ExpBase)):
        if isinstance(expr, Function) and hasattr(expr, "inverse"):
            if len(expr.args) == 1 and len(expr.args[0].args) == 1 and \
               isinstance(expr.args[0], expr.inverse(argindex=1)):
                return simplify(expr.args[0].args[0], ratio=ratio,
                                measure=measure, fu=fu)
        return expr.func(*[simplify(x, ratio=ratio, measure=measure, fu=fu)
                         for x in expr.args])
```
As the root expression is asin and not not Add, Mul, Pow, ExpBase. As is a Function and the argument is the inverse function it cancels both.

But when the main function is the *g* the root expression is Mul, so it skips this block and none of the consequent simplifications is equivalent to this lines.

I have done a small modification to simplify.py that gives the right results and pass the basic test cases, but I have not tested it extensively.
```patch
diff --git a/sympy/simplify/simplify.py b/sympy/simplify/simplify.py
index fc803f899..204b2a229 100644
--- a/sympy/simplify/simplify.py
+++ b/sympy/simplify/simplify.py
@@ -381,6 +381,26 @@ def signsimp(expr, evaluate=None):
     return e
 
 
+def composed_inverse(expr):
+    """Cancel composition of functions with its own inverse:
+        f(finv(x)) ==> x
+    So The next substitutions are applied:
+    >>> composed_inverse(asin(sinx)))
+    x
+    >>> composed_inverse(exp(log(x)))
+    x
+
+    If no cancellation is possible returns the same expression.
+    """
+
+    if isinstance(expr, Function) and hasattr(expr, "inverse"):
+        # TODO: Can be just change this check to something simpler
+        if len(expr.args) == 1 and len(expr.args[0].args) == 1 and \
+           isinstance(expr.args[0], expr.inverse(argindex=1)):
+            return expr.args[0].args[0]
+    return expr
+
+
 def simplify(expr, ratio=1.7, measure=count_ops, fu=False):
     """
     Simplifies the given expression.
@@ -520,14 +540,16 @@ def simplify(expr, ratio=1.7, measure=count_ops, fu=False):
     if not isinstance(expr, Basic) or not expr.args:  # XXX: temporary hack
         return expr
 
-    if not isinstance(expr, (Add, Mul, Pow, ExpBase)):
-        if isinstance(expr, Function) and hasattr(expr, "inverse"):
-            if len(expr.args) == 1 and len(expr.args[0].args) == 1 and \
-               isinstance(expr.args[0], expr.inverse(argindex=1)):
-                return simplify(expr.args[0].args[0], ratio=ratio,
-                                measure=measure, fu=fu)
-        return expr.func(*[simplify(x, ratio=ratio, measure=measure, fu=fu)
+    if isinstance(expr, (Add, Mul, Pow, ExpBase)):
+        # Try to cancel all the sub-terms
+        expr = expr.func(*[composed_inverse(x) for x in expr.args])
+    else:
+        expr = composed_inverse(expr)
+        # If no simplification was possible, try nestesd simplification
+        if expr is original_expr:
+            return expr.func(*[simplify(x, ratio=ratio, measure=measure, fu=fu)
                          for x in expr.args])
+        # Otherwise continue with the normal simplification
 
     # TODO: Apply different strategies, considering expression pattern:
     # is it a purely rational function? Is there any trigonometric function?...
```

**Comment by mohit3011** [comment]
So should I add these lines into my code and test it ?

**Comment by jksuom** [comment]
It should be kept in mind that `sin` is a many-to-one function with a multivalued inverse. `asin` denotes the principal branch of the inverse with branch cuts along the real axis from 1 to oo and from -1 to -oo. The values of `asin` lie in the zone `-pi/2 < re(x) < pi2`, and therefore `x == asin(sin(x))` is valid in this zone only. If, for example, `pi/2 < re(x) < 3*pi/2`, then `asin(sin(x))` is equal to `pi - x`.

**Comment by killerrex** [comment]
I also notice the problem of the principal value but my concern was more in the line of the different behaviour of simplify depending of the contest where the asin-sin composite is found.
To address that discrepancy we need to remove the inverse method from the trigonometric functions or tune it so it returns a full set of solutions. Although I think this will introduce many unexpected and undesired results... I suspect in many places is common to assume that the inverse trigonometric functions are consider in their principal value.

**Comment by mohit3011** [comment]
I agree with both of you, so should I start with simplify.py

**Comment by jksuom** [comment]
I think that `asin(sin(x))` should be left as it is in `simplify`. It seems that the current conditions for cancelling two (partially) inverse functions are wrong.

**Comment by killerrex** [comment]
I think here there are 2 issues:
- simplify cancels f(finv(x)) => x only if f is the root expression,  so it does not solve nested expressions like 1+f(finv(x)) to 1+ x. This is contraintuitive and my patch solves it... Although I am convinced there is a cleanest way to do it.
- The inverse trigonometric functions (and also the hyperbolic ones) report incorrectly that they have inverse, ignoring that they are multivalued functions.  In this sense other pairs like log-exp works correctly

My patch or something similar will fix the first issue, but fixing the second one I think it can have bigger consequences

**Comment by mohit3011** [comment]
@killerrex  
Could you explain what's exactly happening in these lines of codes 
`if not isinstance(expr, (Add, Mul, Pow, ExpBase)):
        if isinstance(expr, Function) and hasattr(expr, "inverse"):
            if len(expr.args) == 1 and len(expr.args[0].args) == 1 and \
               isinstance(expr.args[0], expr.inverse(argindex=1)):
                return simplify(expr.args[0].args[0], ratio=ratio,
                                measure=measure, fu=fu)
        return expr.func(*[simplify(x, ratio=ratio, measure=measure, fu=fu)
                         for x in expr.args])`

**Comment by mohit3011** [comment]
![screen shot 2017-02-11 at 1 40 55 am](https://cloud.githubusercontent.com/assets/19210197/22842439/3f90c546-effb-11e6-8256-3794b59dcff6.png)
@killerrex  Could explain exactly what is happening . Thanks

**Comment by killerrex** [comment]
That part of the code was already in the simpñify code. My analysis of what is doing is:
- if expr is one of Add, Mul, Pow, ExpBase (and subclasses) just continue with the simplify function.
- for the rest of the expressions:
  + If is a function that declares to have inverse, and has just one argument, that is the inverse function with also just one argument (this part is really obscure) return the simplification of the inner value. Translated to something easier, if expr = f(f_inverse(other)) then return simplify(other)
  + For the other expressions return the same function with the arguments simplified so f(a, b) returns f(simplify(a), simplify(b))

The initial condition I think is to skip cases with no inverse and that shall be simplified with the other part of the code:
- Add, Mul:  functions of 2 aeguments, so not possible to cancel with the inverse
- Pow: the inverse is not obvious
- ExpBase: exp(log(x)) is simplified before entering in simplify,  and the subclasses of ExpBase may not have obvious inverse

The condition for the inverse I think is too complex, as a function with inverse must have only one variable,  any other argument must be a parameter like f(x; n, m) and g(x; n, m) if f(g(x; n, m); n, m) == x
The solution taken by the code is to limit the simplification to univariate functions, otherwise it needs some method to check if the other parameters have the right values.

**Comment by mohit3011** [comment]
@killerrex   I saw the code in simplify.py and from what I can see is that we can at least add some conditions for correctly simplifying problems with one argument for now. 
`if isinstance(expr, Function) and hasattr(expr, "inverse"):`
we can add a condition like this for simplifying the other way round for trigonometric functions.

**Comment by mohit3011** [comment]
I have one doubt in mind , sine and asine are each others inverse then how does sin(asin(x)) gives x and asin(sin(x)) doesnot simplify because both should enter the second if condition in code i.e the condition `if isinstance(expr, Function) and hasattr(expr, "inverse"):`

**Comment by jksuom** [comment]
`sin(asin(x))` is evaluated by `sin.eval`. `simplify` has no part in it.

**Comment by HoaiNam8282** [comment]
Hello,

I encountered the same issue with `simplify`. The aim of this comment can be seen as a more complex test case when the issue will be solved. Note that the code presented below worked perfectly with the previous release of `Sympy` (`Sympy 0.7.6.1`).

The image below depicts the original code. It aims to successively compute the first and second derivatives of `self.pexpr[idep]` (in this case idep=2 and nbrdof=1). The first derivative is stored in the variable `temp `and then simplified. Then, the variable `temp `is derived again and stored in `temp2`. `Temp2 `is finally simplified and placed in `self.pddexpr[idep]`. (Function `mysimplify `= `simplify`).

The simplified expression of `self.pddexpr[idep]` changes either according to `Simpy ver 0.7.6.1` or `Simpy ver 1.0`.

![code_simplify](https://cloud.githubusercontent.com/assets/17083539/22920489/906b3d9c-f295-11e6-9bf2-22e3a0effacd.PNG)

The next figure shows the equations to derive (p0 and p1) and the results generated by Simpy 0.7.6.1 (which were correct):

![eq_latex_sympy_0 7 6 1](https://cloud.githubusercontent.com/assets/17083539/22920949/e0796bf4-f297-11e6-9fdc-54dbb24f68f4.PNG)

The next figure shows the equations generated by Simpy 1.0 (pdotdot_1 incorrect):

![eq_latex_sympy_1 0](https://cloud.githubusercontent.com/assets/17083539/22920954/e91a327a-f297-11e6-871a-d530ab855910.PNG)

As seen, the simplified expression of the second derivative "pdotdot_1" is different from the one obtained with `Simpy 0.7.6.1` which was correct.

Here below, some intermediate 'print' functions were called into the original code: 

![code_simplify_print](https://cloud.githubusercontent.com/assets/17083539/22920938/cdcbc254-f297-11e6-9b76-e3c5bf8d8458.PNG)

[Code.txt](https://github.com/sympy/sympy/files/773481/Code.txt)

`Simpy 0.7.6.1`:

![sympy-0 7 6 1-py3 5](https://cloud.githubusercontent.com/assets/17083539/22920996/28d522bc-f298-11e6-975b-4057cc8e8bc6.PNG)

`Sympy 1.0`:

![sympy_1 0-py3 6](https://cloud.githubusercontent.com/assets/17083539/22921005/2f5f4482-f298-11e6-9df7-cd9d788cae95.JPG)

How do you plan to fix this issue ? 

Thanks for your replies !

(Tested with Sympy 0.7.6.1 and Sympy 1.0 and python 3.6 in windows).
