### ISSUE TITLE
matematica code printer does not handle floats and derivatives correctly

### ISSUE THREAD

**Issue by kemlath** [sympy/sympy#12163]
In its current state the mathematica code printer does not handle Derivative(func(vars), deriver) 
e.g. Derivative(f(t), t) yields Derivative(f(t), t) instead of D[f[t],t]

Also floats with exponents are not handled correctly e.g. 1.0e-4 is not converted to 1.0*^-4

This has an easy fix by adding the following lines to MCodePrinter:

def _print_Derivative(self, expr):
        return "D[%s]" % (self.stringify(expr.args, ", "))

def _print_Float(self, expr):
        res =str(expr)
        return res.replace('e','*^')

**Comment by mohit3011** [comment]
I would like to work on this issue

**Comment by mohit3011** [comment]
@kemlath could you tell me how to proceed .

**Comment by mohit3011** [comment]
So, should I add the lines in printing/mathematica.py ?

**Comment by kemlath** [comment]
I've tested the above code by adding these methods to a class derived from MCodePrinter and I was able to export an ODE system straight to NDSolve in Mathematica.

So I guess simply adding them to MCodePrinter in in printing/mathematica.py would fix the issue

**Comment by mohit3011** [comment]
Ok , so I'll add the method in McodePrinter class.

**Comment by mohit3011** [comment]
@kemlath  it is giving some error , please have a look
![screen shot 2017-02-13 at 10 51 05 pm](https://cloud.githubusercontent.com/assets/19210197/22894439/fc1e8ab4-f23e-11e6-8d1e-3e27174a6e01.png)

**Comment by mohit3011** [comment]
Maybe we should only go with printing issue of derivative. 
I have submitted the PR #12171

**Comment by kemlath** [comment]
My bad I should have called the super class version of _print_Float instead of str().
Please change the _print_Float method as below and the assertions are gone

```
def _print_Float(self, expr):        
        res = super()._print_Float(expr)
        return res.replace('e','*^')
```

or with fewer variables

```
def _print_Float(self, expr): 
        return super()._print_Float(expr).replace('e','*^')

```
I don't have access to the sympy unit tests I'm merely a user. Here's my test case that I built based on test_mathematica.py:

[test_MathematicaPrinterExt.py.zip](https://github.com/sympy/sympy/files/772195/test_MathematicaPrinterExt.py.zip)
