### ISSUE TITLE
Empty intersection should be UniversalSet

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#12178]
```
In [46]: Intersection()
Out[46]: ∅
```

It should be `S.UniversalSet`. See https://en.wikipedia.org/wiki/Intersection_(set_theory)#Nullary_intersection

**Comment by mohit3011** [comment]
I would like to take this issue.

**Comment by asmeurer** [comment]
I don't see how the empty set is valid.

**Comment by MrOverlord** [comment]
In ZFC intersection of a family of sets is always subset of union of said family (this convention is mentioned in linked wikipedia article).

**Comment by asmeurer** [comment]
I see. The universal set is more useful for algebraic operations, and SymPy does have a (formal) universal set object, so the ZFC concerns do not apply.
