### ISSUE TITLE
nsolve doesn't work with uppergamma/lowergamma

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#12173]
Reported on the mailing list. It's because lambdify doesn't know how to convert uppergamma and lowergamma to mpmath's gammainc (see how `evalf` is defined). 

Should be easy to fix. Just need to add some printers to `MpmathPrinter` in `sympy.printing.lambdarepr`.

**Comment by patniharshit** [comment]
Hi, I would like to take this up.

**Comment by codesep** [comment]
@asmeurer I would like to work on this issue.

**Comment by patniharshit** [comment]
@codesep I am already working on this, will let you know if I can't do it.

**Comment by patniharshit** [comment]
@asmeurer I followed your cues and found MpmathPrinter class. Now I can't figure out how to write printer for the issue ?

**Comment by Shariq03** [comment]
Hi, I've started knowing about open source organizations recently and I'm taking baby steps. I'm not clear with the problem statement. My understanding is that as there are only gamma & gammainc  and no upper gamma & lower gamma, we have to write code to equip users with upper and lower gamma. If this is actual statement then we can always find
1.  upper_gamma(a,z) = gammainc(a,z) * gamma(a)
2.  lower_gamma(a,z) =  (1-gammainc(a,z)) * gamma(a)
@asmeurer , Please correct me if I'm wrong.

**Comment by asmeurer** [comment]
There are no upper/lowergamma in mpmath. They do exist in SymPy. The issue here is to add translators to lambdify so that it knows how to convert them to mpmath.

**Comment by patniharshit** [comment]
If I am understanding you correctly then should I add MPMATH_TRANSLATIONS["uppergamma"] = "gammainc" in sympy/utilities/lambdify.py ?

**Comment by asmeurer** [comment]
That will work for uppergamma. For lowergamma you need a printer.

**Comment by pspbot7** [comment]
` def _print_Uppergamma(self,e):
        return "gammainc('%s','%s', ∞)" %e.args[0] %e.args[1]

    def _print_Lowergamma(self,e):
        return "gammainc('%s', 0, '%s')" %e.args[0] %e.args[1]`
@asmeurer I went through the syntax on the mpmath documentation, and will this solution work?

**Comment by asmeurer** [comment]
∞ is not valid syntax (should be `inf`). Also your string formatting syntax is invalid. But you have the right idea.

**Comment by pspbot7** [comment]
@asmeurer can you help me with the string formatting syntax

**Comment by patniharshit** [comment]
@pspbot7  you can write it like this:
`def _print_Uppergamma(self,e):
           return "gammainc({0}, {1}, inf)".format(e.args[0], e.args[1])`

**Comment by pspbot7** [comment]
@patniharshit  thanks for the help

**Comment by pspbot7** [comment]
` def _print_Uppergamma(self,e):
        return "gammainc({0}, {1}, inf)".format(e.args[0], e.args[1])

    def _print_Lowergamma(self,e):
        return "gammainc({0}, 0,{1})" %e.args[0] %e.args[1]`
@asmeurer will this work, and if so do I need to add anything else?

**Comment by patniharshit** [comment]
Lowergamma is still wrong. It can be written either as 
`"gammainc({0}, 0,{1})".format(e.args[0], e.args[1])`
or 
`"gammainc(%s, 0, %s)" % (e.args[0], e.args[1])`

**Comment by pspbot7** [comment]
` def _print_Uppergamma(self,e):
return "gammainc({0}, {1}, inf)".format(e.args[0], e.args[1])

def _print_Lowergamma(self,e):
    return "gammainc({0}, 0,{1})".format(e.args[0], e.args[1])`

@asmeurer will this work, and if so do I need to add anything else?

**Comment by pspbot7** [comment]
@patniharshit overlooked while pasting the code, my bad
