### ISSUE TITLE
default behavior for product rule in differentiate_finite is incorrect

### ISSUE THREAD

**Issue by halpernf** [sympy/sympy#12186]
Hi everybody,

First time user of SymPy. So far I am quite enjoying this and I was able to generate Arakawa brackets of arbitrary order with just a few lines of SymPy. I wanted to report on an issue I came across.

The following expression from the SymPy documentation shows use of the product rule for continuous function applied on a discrete function. This behavior is incorrect, e.g.

``>>> x = symbols('x')``
``>>> f, g = symbols('f g', cls=Function)``
``>>> differentiate_finite(f(x)*g(x))``
``(-f(x - 1/2) + f(x + 1/2))⋅g(x) + (-g(x - 1/2) + g(x + 1/2))⋅f(x)``

A large part of the applied mathematics literature is devoted to designing numerical schemes that preserve a "discrete product rule." Examples are summation-by-parts and mimetic finite differences. A better default behavior in SymPy would be to force ``evaluate=False``, which gives

``>>> differentiate_finite(f(x)*g(x), evaluate=False)``
``-f(x - 1/2)⋅g(x - 1/2) + f(x + 1/2)⋅g(x + 1/2)``

The latter expression is the correct answer.

**Comment by bjodah** [comment]
I am +1 for just changing the default to `evaluate=False`, @halpernf would you mind opening a PR changing this and perhaps changing the docstring to include the point you've made in this issue?

**Comment by mohit3011** [comment]
@bjodah I would like to work on this issue, kindly refer to any starting point on this . Thanks

**Comment by bjodah** [comment]
@mohit3011 are you familiar with MFD? I would do this myself if I had experience with MFD, but since I don't, I think it's better that someone who has updates the documentation.

**Comment by mohit3011** [comment]
@bjodah  What's the full form of MFD?

**Comment by LaviDM** [comment]
@bjodah sorry about my ignorance, by PR you mean pull request?

@bjodah @mohit3011 no need to implement MFD here. Changing the default to `evaluate=False` should be enough for the time being... I'll have some time later on this week. It should be easy enough to do even if I don't know the code that well.
