### ISSUE TITLE
Sympy Control Toolbox?

### ISSUE THREAD

**Issue by jgoppert** [sympy/sympy#12181]
Is there any interest in adding a control engineering toolbox I'm getting pretty good results with just writing some routines on top of the existing rational and polynomial stack.

Here is a demo of the state space and transfer function classes and conversion between the two for MIMO systems using a Gilbert realization. Also, I've implemented Jordan canonical form conversion. So far I just have this in a jupyter notebook but would happy to bring it in as a sympy module. 

This is more powerful than the routines in matlab and python-control since we can actually transform from state-space to transfer function matrix and back in a symbolic form.

![image](https://cloud.githubusercontent.com/assets/473772/23009609/f4b306ae-f3e4-11e6-9a5a-bddb1e4d2726.png)

**Comment by astrojuanlu** [comment]
See gh-18436, gh-19390, and gh-19896 (from the 1.7 release notes)

**Comment by moorepants** [comment]
We now have a control package, so closing.
