### ISSUE TITLE
Sympy doesn't compute powers in pretty print

### ISSUE THREAD

**Issue by Vedarth** [sympy/sympy#12185]
`def main():`
    `a = Symbol('a')`
    `b = Symbol('b')`
    `c = Symbol('c')`
    `e = ((a/a + 2*a/b )**(1/c))**c`
    `print('')`
    `pprint(e)`
    `print('')`
   `if __name__ == "__main__":`
    `main()`
Here output should be 1+2*a/b
But output is coming
![capture](https://cloud.githubusercontent.com/assets/22793275/23028856/96f42534-f48e-11e6-900a-7128c5443c50.PNG)
Here a/a is getting evaluated but powers are not getting evaluated properly.
I am new to sympy so it is possible I am doing something wrong but if not then I would like to solve this issue please tell me how to do so.

**Comment by maccaughanc** [comment]
This is proper behavior on sympy's part as it follows the identities held by powers. In this case, sympy follows the identity that `(x**a)**b` doesn't necessarily equal `x**(a*b)`, with the example given in the documentation being that `(-1)**(1/2)**2 != (-1)**(2*(1/2))`. You can see a fuller discussion of this behavior [here](http://docs.sympy.org/latest/tutorial/simplification.html#powers).

If you would still like to force the simplification, without adding assumptions about the symbols, you can use the function `powsimp` with the argument `force=True` as I have shown below:


```
def main():
  a, b, c = symbols('a b c')   # Using symbols function is preferable
  e = ((a/a + 2*a/b )**(1/c))**c
  print('')
  pprint(e)
  print('')

  f = powsimp(e, force=True)
  pprint(e)
```

As a last note, you can produce code blocks using a triple grave accent (i.e. ```) instead of the inline code with a single one (i.e. `). You can find a Github guide for Markdown [here](https://guides.github.com/features/mastering-markdown/).

**Comment by Vedarth** [comment]
@maccaughanc Thanks for your answer. I am terribly sorry for late reply. I wasn't familiar with sympy and github's markdown when i faced this issue but, even though now I am familiar with the codebase, your explanation was really helpful and accurate. I should have read it and replied to it sooner.
Thanks a lot for your help.
