### ISSUE TITLE
GitHub sympy/sympy contributors page is incorrect

### ISSUE THREAD

**Issue by certik** [sympy/sympy#12198]
This page: https://github.com/sympy/sympy/graphs/contributors lists the following people as the top contributors, sorted by the number of commits:

smichr
asmeurer
mattpap
mrocklin
certik
jrioux
raoulb
rlamy

However, the `git shortlog -ns` shows these people:

  4056  Chris Smith
  2884  Aaron Meurer
  1457  Ondřej Čertík
  1450  Mateusz Paprocki
  1055  Sergey B Kirpichev
  1046  Matthew Rocklin
   677  Julien Rioux
   543  Raoul Bourquin
   466  Ronan Lamy

One difference is that GitHub doesn't count merge commits I think, so the order is a bit different. However, most importantly GitHub is completely missing "Sergey B Kirpichev" (@skirpichev), which is unacceptable.

I contacted GitHub Support about this problem on 2/14 and then again on 2/16 (the dates might be approximate, as I don't have any confirmation), but unfortunately GitHub hasn't responded yet to either inquiry as of 2/18.

So I am creating a public issue so that we can keep track of the progress to fix this.

**Comment by certik** [comment]
I just sent them another email (2/22/2017) using the form https://github.com/contact with the following content:

```
Dear GitHub,

The contributors page at https://github.com/sympy/sympy/graphs/contributors is missing an author @skirpichev, that is very unfortunate, he should be attributed for his work on SymPy. Can you please fix it?
I have already contacted you twice and never received a reply. I am keeping track of this issue here:

https://github.com/sympy/sympy/issues/12198

If you could please acknowledge receiving this bug report, I would really appreciate it.

Thanks,
Ondrej
```
After clicking "Send request", a page appears with a text:
```
Thanks for getting in touch with us!
We’ll get back to you shortly. 
```

**Comment by certik** [comment]
As a further data point, I have unblocked the user skirpichev, to see if perhaps that is causing the problem, but he didn't appear here:

https://github.com/sympy/sympy/graphs/contributors

So this really looks like a bug at GitHub.

**Comment by skirpichev** [comment]
Maybe, there must be some time lag after blocking/unblocking, before these settings will affect statistics.

**Comment by certik** [comment]
GitHub finally got back to me, they said my emails were not reaching them due to some internal bug. They confirmed that blocking a user removes them from the Contributors list (and apparently there is some lag before this happens and before the user appears in the list after he is unblocked). I have asked them to please not do that. Blocking a user should not remove any of their credits. They said they will discuss that internally.

**Comment by isuruf** [comment]
This is fixed now.
