### ISSUE TITLE
Stray character

### ISSUE THREAD

**Issue by tlowerison** [sympy/sympy#12204]
In sympy/sympy/calculus/euler.py, in the first comment of function euler_equations there is a stray 'r' preceding the comment. Have not tested whether it creates any bugs.

**Comment by jksuom** [comment]
It is not a stray character but a [string prefix](https://docs.python.org/3/reference/lexical_analysis.html#string-and-bytes-literals) indicating that the docstring should be interpreted as a raw string. There are latex commands whose names consist of a \ symbol followed by some ordinary characters. In regular Python strings, \ is interpreted as an escape character but in raw strings it is not treated specially. It will be left as it is for the latex compiler.
