### ISSUE TITLE
Solveset doesn't solve for a number

### ISSUE THREAD

**Issue by Yathartha22** [sympy/sympy#12217]
`solveset` is not able to solve expressions, if the symbol is specified as a number rather it returns an `EmptySet()`. Like the `solve` is able to do the same, I thought to add on this functionality to the `solveset`.
Is this advisable, if so I would do this.

```
>>> solveset(sqrt(2) - 1, 1)
EmptySet()
```
While `solve` gets an answer.
```
>>> solve(sqrt(2) - 1, 1)
 [sqrt(2)]
```

**Comment by Shekharrajak** [comment]
In this case equation is `sqrt(2) - 1 == 0`, which is not possible so solveset returns `EmptySet`. But I think it must first check(whether it is a symbol or not) 2nd arg and returns `ValueError` (since 2ns arg should be a symbol).

See the [docs](https://github.com/sympy/sympy/blob/master/sympy/solvers/solveset.py#L743) . 

I don't think `solve` should return this.

**Comment by Yathartha22** [comment]
Yes, it would return a `ValueError`, but what prompted me to raise this issue is the point in the `[solvers docs](https://github.com/sympy/sympy/blob/master/sympy/solvers/solvers.py#L559)`
I thought that if `solveset` could do the same, it would be good. I might be wrong, what do you suggest @Shekharrajak

**Comment by asmeurer** [comment]
I agree it should give ValueError because of the meaningless symbol argument. I don't like how `solve` lets you solve for 1. The answer is meaningless (it implies that `1 = sqrt(2)`). If you really wanted to do that `(sqrt(2) - 1).subs(1, x)` works.

**Comment by Yathartha22** [comment]
```
if you attempt to solve for a number remember that the number
you have obtained does not necessarily mean that the value is
equivalent to the expression obtained
```

@asmeurer this is what the line says in [solvers docs](https://github.com/sympy/sympy/blob/master/sympy/solvers/solvers.py#L559)
and the next line folllows the above example.
Should I suppose it to be a bug in `solve`.

**Comment by Shekharrajak** [comment]
@Yathartha22 , `solve` can solve eq. for sub expression  (In this case expression is `1`)
```
>>> solve(x + 2 + sqrt(3), x + 2)
[-sqrt(3)]
```
 `solveset` 2nd arg should be symbol not any expression. So `solveset` should not return that ans, it is not made for solving expression. (There must be ValueError in this case)

**Comment by Yathartha22** [comment]
thanks @Shekharrajak I could sum up, that `solveset` should not be made to solve for sub expression in future it should only solve for symbols. Am I right?

**Comment by Shekharrajak** [comment]
Yes.

**Comment by Yathartha22** [comment]
I guess I should close this issue.

**Comment by Yathartha22** [comment]
I will fix this.

**Comment by Yathartha22** [comment]
@Shekharrajak I have created a PR please review.
