### ISSUE TITLE
Python code printer

### ISSUE THREAD

**Issue by Upabjojr** [sympy/sympy#12213]
The current Python printer prints expressions in a SymPy-style.

It could be useful to have a printer that prints non-SymPy Python code, for example:

- `Mod(x, 2)` as `x % 2`
- `And(x, y)` as `x and y` instead of SymPy's operator overloaded `x & y`.

Currently:

- `str( )` is supposed to return a valid Python code that is (with some exceptions/caveats) able to reconstruct the SymPy object.
- `lambdify( )` returns a lambda objects for optimized operations.

**Comment by mohit3011** [comment]
I would like to work on this issue, could you please refer the starting point

**Comment by Upabjojr** [comment]
Better discuss this issue a bit before starting, especially to get an idea of what other community members think about it.

This could potentially clash with the `lambdify` functionality.

**Comment by mohit3011** [comment]
Yes, you are right.

**Comment by asmeurer** [comment]
Do you mean the printer in `sympy.printing.python`? I don't think that is used by anything, except for the `python` function. It isn't used by lambdify. 

I agree it would be better to expand the functionality of this. It would be useful to directly codegen to Python. For instance, one could then subclass this to create a CythonPrinter. 

It does tie in pretty closely with the LambdaPrinter. They should definitely share some code. I'm not entirely sure what that should look like. LambdaPrinter is constrained in that it needs to print expressions, whereas the `python` printer can print entire blocks of code (although most everything in Python can be represented as a single expression).

Maybe @bjodah has some ideas?

**Comment by asmeurer** [comment]
And I should add that the `str` printer could be a superclass here, but it shouldn't be considered to be a code generation printer. Aside from what you said that it focuses on SymPy output, it also has a high focus on readability and human consumption, whereas a code generator printer doesn't have that restriction.

**Comment by moorepants** [comment]
I agree this is needed. I've needed it many times and just hacked around the str printer. I think it should likely be a separate than lambdify because lambdify does all these import tricks. It should just be another code printer that ties into the rest of the codegen framework.

**Comment by asmeurer** [comment]
Also, for what it's worth, the lambdify restriction that it prints an expression is not strictly needed. Right now, lambdify works like

```
return eval('lambda %s: %s' % (args, lambdarepr(expr)))
```

(roughly). But it could also work like 

```
ns = {}
exec("""
def f(%s):
    return %s
""", {})
return ns['f']
```

which would open up the possibility to do things like variable assignment inside of the lambdified expression. And then, in the long run, `lambdify` would just be a wrapper around the `python` printer. The LambdaRepr (expression only) printer could be kept for backwards compatibility (and it could be useful for general code printing).

**Comment by mohit3011** [comment]
@Upabjojr ,  I read about Lambdify as well as about codegen. I don't know about the difficulty of this issue if it is easy to fix then I would like to work. Could you please refer to the starting point for solving this issue.

**Comment by Upabjojr** [comment]
@mohit3011 , I would roughly try to see how `lambdify` works and figure out a way of printing the generated code instead of evaluating it. Not sure about the difficulty.

**Comment by mohit3011** [comment]
@asmeurer , could you refer to any starting point on this issue and it's difficulty level. Thanks.

**Comment by mohit3011** [comment]
@Upabjojr , did you look into this issue further ?

**Comment by Upabjojr** [comment]
> did you look into this issue further ?

No.

The way to go is to debug the `lambdify` function and see if you can reorganize the code to retrieve the expression string. If you feel like doing it, have a try!

**Comment by mohit3011** [comment]
@Upabjojr  , please have a look at #12250

**Comment by mohit3011** [comment]
@Upabjojr , I looked into lambdify function in lambdify.py and also lambdarepr.py ,  but I couldn't get anything . Could you please help me

**Comment by moorepants** [comment]
@mohit3011 I suggest reading the documentation on how printing works: http://docs.sympy.org/latest/modules/printing.html at a start.

**Comment by Upabjojr** [comment]
@mohit3011 just debug the code, put some breakpoints and explore the local variables. 

Once you understand how the code works, it will be easier to purpose an edit.

**Comment by bjodah** [comment]
Since there is a rudimentary Python code printer now (since gh-12808) should we close this issue? We can open up new issues for the new printer (wishlists and/or bug-reports)
