### ISSUE TITLE
Try out CircleCI for tests

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#12219]
https://circleci.com/

It's a little harder to set up than Travis, but it should run a lot faster. Basically, you have to create a bunch of Dockerfiles that set up and run the tests. I've not configured it before, so I don't know exactly how to do it. We'll have to figure that out.

**Comment by asmeurer** [comment]
If someone wants to try this and they don't have permissions to enable CircleCI for sympy/sympy, just let me know and I can do it. You can also try testing it out on your fork first.

**Comment by tanayag** [comment]
is it to be configured using circle.yml file?? @asmeurer

**Comment by asmeurer** [comment]
Yep
