### ISSUE TITLE
Both integrate(2*x/(x**2+y**2),y) and diff(2*atan(y/x),y) return wrong result. Result should be each other.

### ISSUE THREAD

**Issue by AmericanEnglish** [sympy/sympy#12229]
Forgive me here if this seems incorrect but I was recently doing some work for my complex analysis class and was testing out Smypys integration function. I suspected the integral should be some sort of arctrig function, I haven't done mutli-variable stuff in a while, but Sympy dumped this interesting imaginary function instead.

```
In [38]: integrate(2*x/(x**2+y**2),y)
Out[38]: -I*log(-I*x + y) + I*log(I*x + y)

In [39]: diff(2*atan(y/x),y)
Out[39]: 2/(x*(1 + y**2/x**2))
```

I went to Wolfram Alpha to double check the solution and it was wrong. So out of curiosity I decided to see if Sympy would be able to take the correct partial derivative with respect to y but this answer was also wrong by a factor of 1/x. A link to the [Wolfram calculation](https://www.wolframalpha.com/input/?i=d%2Fdy(2*tan%5E-1(y%2Fx))) for some proof. 

EDIT:

I was read that someone else mentioned a similar result with regards to an integration problem and the possible error was that sympy just isn't automatically converting the complex representation  to regular arctangent notation. However, in this case, Wolfram Alpha says that [this complex result is still incorrect if simplified to arctangent notation.](https://www.wolframalpha.com/input/?i=simplify+-I*log(-I*x+%2B+y)+%2B+I*log(I*x+%2B+y))  The link states that the simplified form of
```
-I*log(-I*x + y) + I*log(I*x + y) == -2atan(x/y)
```
```
-2atan(x/y) != 2atan(y/x)
```

**Comment by jksuom** [comment]
The values of `2*atan(y/x)` and `-2*atan(x/y)` are different but the derivative of their difference is zero.
```
In [11]: diff(2*atan(y/x) + 2*atan(x/y), y).simplify()
Out[11]: 0
```
Hence their values differ by a constant, and they are both antiderivatives of the same function.

**Comment by SoumyadeepThakur** [comment]
The output is correct
`atan(x)=pi/2-atan(1/x)`
hence the answer for `integrate()` is correct

`pprint(pprint(diff(2*atan(y/x),y).simplify())`'
this statement results in output:
`2*x/(x**2+y**2)`

Can this issue be closed?
