### ISSUE TITLE
Deprecated CCodePrinter

### ISSUE THREAD

**Issue by bjodah** [sympy/sympy#12220]
Since #11637 the C-code printers make a distinction with respect to standard.
As of writing C89 and C99 are the considered standards. Prior the the PR the
class `CCodePrinter` was using a mix of C89 and C99 features.

By introducing two classes: C89CodePrinter and C99CodePrinter, the user is
encouraged to think about the choice of standard.

During its deprecation CCodePrinter will continue to support the same features
as before (which is mostly C89 with some C99 features).

**Comment by hackrush01** [comment]
So as far as my understanding goes, the Class `CCodePrinter` has to be split up into two classes `C89CodePrinter` and `C99CodePrinter`, with `CCodePrinter` intact, giving a message that it is depreciated and tell them to use `C89` or `C99` instead.

**Comment by bjodah** [comment]
Precisely, I have done so locally, I will commit & push very soon. But I needed to create this issue to get an issue-number to add to the deprecation message.

**Comment by hackrush01** [comment]
Oh! So you have already taken care of the issue. I was hoping to get on with it for the upcoming GSoC.

**Comment by bjodah** [comment]
Yes, this issue is just a placeholder to reference the deprecation.
I just pushed my changes to #11637  (sorry I referenced the wrong PR at firrst).
The codegen part still needs fixing but I won't work more on it for the next 24h so I pushed my changes.
Feel free to work on my branch (you can open a PR against https://github.com/bjodah/sympy/tree/expm1-log1p) if you want.

**Comment by hackrush01** [comment]
Can you tell more about this codegen part, and which issue is this exactly(issue number).

**Comment by bjodah** [comment]
If you do something along these lines (untested):
```
$ git remote add bjodah git://github.com/bjodah/sympy.git
$ git fetch bjodah
$ git checkout expm1-log1p
$ ./bin/doctest doc/src/modules/codegen.rst 
```
there will be failing tests, i.e. somethings still not quite right with the code.
Since it's in the middle of sweeping changes this might not be the ideal
work to start with if you're new to the process but feel free to give it a try.

**Comment by hackrush01** [comment]
I am new to this, should I start somewhere else? Will it be possible for you to point me to it?

**Comment by bjodah** [comment]
I'm afraid I cannot advise you regarding what you should start with.

**Comment by hackrush01** [comment]
Oh it's completely fine, thanks for your time.
