### ISSUE TITLE
Write documentation and examples to UnevaluatedExpr

### ISSUE THREAD

**Issue by Upabjojr** [sympy/sympy#12230]
The class `sympy.core.expr.UnevaluatedExpr` can potentially be very useful.

- Write some documentation as to its usages in the tutorials and/or introduction to SymPy.
- Especially important, mark the difference between `UnevaluatedExpr` and `evaluate=False`.
- Show that SymPy printers seamlessly support `UnevaluatedExpr` (and report a bug if any issues arise).

Related on StackOverflow: http://stackoverflow.com/questions/42486283/preventing-a-multiplication-expression-evaluating-in-sympy/42503593#42503593

**Comment by mohit3011** [comment]
@Upabjojr , I would like to work on this issue

**Comment by mohit3011** [comment]
@Upabjojr , should I write in doc/src/tutorial/intro.rst or anywhere else ?

**Comment by Yathartha22** [comment]
@mohit3011 are you still working on it.
I would like to take this.

**Comment by mohit3011** [comment]
Yes

**Comment by Yathartha22** [comment]
Okay

**Comment by Upabjojr** [comment]
Candidates for the documentation:

* Add usage examples in: http://docs.sympy.org/latest/tutorial/manipulation.html
* Add class link after `Expr`: http://docs.sympy.org/dev/modules/core.html#id16
* Add some examples with `Float`: http://docs.sympy.org/dev/modules/core.html#float 

It's about editing the RST files (I think) or maybe some docstring.

**Comment by mohit3011** [comment]
@Upabjojr ,I have already written a full tutorial kind of thing , so I was thinking to put in as a whole rather than in parts ,  but I am confused in which rst file to put inside the folder (doc/src/tutorial/)

**Comment by Upabjojr** [comment]
> I have already written a full tutorial kind of thing , so I was thinking to put in as a whole rather than in parts

Oh nice. How much did you write? Make sure to make it clear why it is different from `evaluate=False`.

I think the file is this: http://docs.sympy.org/dev/modules/core.html#id16
(github isn't properly showing its contents)

**Comment by mohit3011** [comment]
@Upabjojr , the link you have given points to doc/src/modules/core.rst , so I will add the tutorial here

**Comment by Upabjojr** [comment]
No, wait, wrong link.

**Comment by Upabjojr** [comment]
https://github.com/sympy/sympy/blob/master/doc/src/tutorial/index.rst

**Comment by mohit3011** [comment]
@Upabjojr  index.rst represents index , maybe we have to add it in some other file

**Comment by Upabjojr** [comment]
@mohit3011 just open the PR, it's better to see the code for me to comment.

**Comment by mohit3011** [comment]
Okay so for I am adding the code in intro.rst for the time being
