### ISSUE TITLE
system of linear equations with singular matrix

### ISSUE THREAD

**Issue by Nedaaaa** [sympy/sympy#12242]
I am computing the solution of a linear system of equation Ax=B, where number of equations are equal to number of unknown and A and B are sparse matrices but A is a singular matrix. I've tried several commands from Scipy and Numpy library to solve this system but non of them gave the correct results.
Does anyone would have any idea of how I can solve this equation in Python.

Thanks

**Comment by twhunt** [comment]
If the system does have a solution (which implies infinitely many solutions in your case), gauss_jordan_solve() will return a parameterized solution:
`>>> A=sympy.Matrix([[1, 0, 0],[0, 0, 0], [0, 0, 0]])`
`>>> b=sympy.Matrix([3, 0, 0])`
`>>> x=A.gauss_jordan_solve(b)`

x[0] is the parameterized solution, with parameters _tau0 and -tau1 in this case.
x[1] is a vector containing the parameters.

If your system has no solutions, then gauss_jordan_solve() will raise an exception.

**Comment by grassknoted** [comment]
>>> import sympy as sm
>>> A = sm.Matrix([[1,0,0],[0,0,0],[0,0,0]])
>>> B = sm.Matrix([1,0,0])
>>> x  = A.gauss_jordan_solve(B)
>>> x
(Matrix([
[    1],
[_tau0],
[_tau1]]), Matrix([
[_tau0],
[_tau1]]))

**Comment by oscarbenjamin** [comment]
It looks like this is solved so I'll close this issue now.

**Comment by twhunt** [comment]
Fine by me!
