### ISSUE TITLE
solve(M*x + N*y, x) fails for non-commutative symbols

### ISSUE THREAD

**Issue by wakita** [sympy/sympy#12258]
Coming across with the following discussion, I found an issue that I think is a bug.
http://stackoverflow.com/questions/22820000/how-to-solve-matrix-equation-with-sympy

One of the answer suggests the following solution:
```
from sympy import *

M, N, x, y = symbols('M N x y', commutative=False)
solve(M * x + N * y, x)
```

whose (incorrect) result is `[-N*y*M**(-1)]`.  It should give `[-M**(-1) * N * y]`, instead.

**Comment by aaditya733** [comment]
Hey I would like to solve this issue. Can anyone guide me on how to proceed ?

**Comment by czgdp1807** [comment]
Thanks @wakita for raising reporting the bug. It looks like `solve` now returns correct result. Please refer the code below,

```python
Python 3.6.8 (default, Oct  7 2019, 12:59:55) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from sympy import *
>>> M, N, x, y = symbols('M N x y', commutative=False)
>>> solve(M * x + N * y, x)
[-M**(-1)*N*y]
```
Closing this for now. Please let me know if it is needed to be opened again.

**Comment by ggleizer** [comment]
Solving for non-commutative symbols is still weird in some cases.

```
import sympy as sp

>>> a, b, p, q = sp.symbols('a b p q', commutative=False)
>>> sp.solve(b * p * a - p - q, p)  # Answer below seems to assume bpa = bap
[-(1 - b*a)**(-1)*q]
>>> sp.solve(a*b+b*a,a)  # a=0 should solve it
[]
```

**Comment by asmeurer** [comment]
a=0 is not valid because 0 is not noncommutative. I agree the other example looks wrong.

**Comment by asmeurer** [comment]
Can you open a new issue for it?
