### ISSUE TITLE
Simplifications in Dirac Delta function

### ISSUE THREAD

**Issue by mohit3011** [sympy/sympy#12257]
It seems that the Dirac Delta function might be more useful if certain simplifications can be done.
For Example:

- For using the symmetry property of the dirac delta function i.e DiracDelta(x)==DiracDelta(-x) . The existing provision for this is `DiracDelta(-x).expand(diracdelta=True, wrt=x)` . As of now we have this
```
>>> DiracDelta(-x)
DiracDelta(-x)

```
What I hope after this issue would be 
```
>>> DiracDelta(-x)
DiracDelta(x)

```
- Also we can include the property like DiracDelta(m*x) = DiracDelta(x)/m , where m is an integer . This feature is also presently implemented like `DiracDelta(2*x).expand(diracdelta=True, wrt=x)`

We can have the existing way when more than one variables are involved . For constants, we can include it in basic cases.

I have read the code regarding this and it would be really nice , if someone could guide me in this.

**Comment by mohit3011** [comment]
@jksuom  , @Upabjojr  ,  can I go with this issue ?

**Comment by jksuom** [comment]
It seems that something like this has been implemented in deltaintegrate. Maybe that could be expanded.

**Comment by mohit3011** [comment]
@jksuom , yes you are right, I think we can do something similar here too.

**Comment by mohit3011** [comment]
@jksuom  , should I proceed with this issue ?

**Comment by jksuom** [comment]
The functionality exists already though it may look a bit clumsy:
```
>>> DiracDelta(-x).expand(diracdelta=True, wrt=x)
DiracDelta(x)
```
I'm not sure if the conversion `DiracDelta(-x) -> DiracDelta(x)` should be made automatic. Maybe someone with more practical experience on these matters could have an opinion.

**Comment by mohit3011** [comment]
@jksuom Yes, that is the whole point of this issue . The existing functionality is clumsy and could be shortened when we arguments of DIrac Delta as like "2*x" , "-x" etc . Here simply we write like (using the property of DIracDelta)

```
>>> DIracDelta(2*x)
DiracDelta(x)/2
```

**Comment by asmeurer** [comment]
The trig functions automatically canonicalize negative signs, so there is precedent. We should definitely have a way to do it the only question is if it should be automatic or not. I'm not sure if many practical applications create delta functions that aren't of the form `DiracDelta(x - a)`.

**Comment by jksuom** [comment]
It seems that the principal means of producing Dirac deltas in SymPy is `_eval_expand_diracdelta` which only creates expressions of the form `DiracDelta(x - a)`.

**Comment by mohit3011** [comment]
@jksuom , sorry for replying late. I wanted to know whether I should give this issue a try ?
