### ISSUE TITLE
cannot extract_multiplicatively(-2) from (-2*x - 2*y)

### ISSUE THREAD

**Issue by cbm755** [sympy/sympy#12254]
I think this might be a bug.
````
>>> (2+4*I).extract_multiplicatively(2)    # yes
1 + 2*I
>>> (-2-4*I).extract_multiplicatively(-1)   # yes
2 + 4*I
>>> (-2-4*I).extract_multiplicatively(-2)   # bug?
````
similarly:
````
>>> (2*x + 4*y + 8).extract_multiplicatively(2)   # yes
x + 2*y + 4
>>> (-2*x - 4*y - 8).extract_multiplicatively(2)    # yes
-x - 2*y - 4
>>> (-2*x - 4*y - 8).extract_multiplicatively(-1)    # yes
2*x + 4*y + 8
>>> (-2*x - 4*y - 8).extract_multiplicatively(-2)    # bug?
````

Assuming it is indeed a bug, here is why it happens:

Look in `core/expr.py` where:
````
>>> (-2*x - 4*y - 8).primitive()
(2, -x - 2*y - 4)
````
which is then made into a *non-evaluated* `Mul`, from which `-2` cannot be multiplicatively extracted; for example:
````
>>> Mul(2, -x).extract_multiplicatively(-2)
x
>>> Mul(2, -x, evaluate=False).extract_multiplicatively(-2)
````
@smichr do you think this is bug? (see your commit 8968b85310506c0a2b34f3d7aeb8e0d88f87885b: not clear whether we still need this special case anyway)

**Comment by SACHIN-13** [comment]
I would like to work on this issue. Please help me to start with it!

**Comment by SACHIN-13** [comment]
I do not understand why do we need 
`elif self.is_positive and quotient.is_negative:
                    return None`
in line 1975-76 of `sympy/core/expr.py` ?? Can you please explain?

**Comment by cbm755** [comment]
I'm not an expert so this is not much of an answer...  See `could_extract_minus_sign()` for an example of something that uses this.  You could also try dropping that `elif` and running the tests: I think you'll see endless recursion b/c this is used internally in various algorithms.

> then what about the args of `-2-4*I` here??

That thing is an `Add`.  It should try to extract `-1` from each of the things in the `Add`.  In this case that is `-2` and `Mul(-4, I)`, each of which can have `-1` extracted from it.  (I think same should be true for `-2`, hence I filed this bug).

**Comment by SACHIN-13** [comment]
> I think same should be true for -2
 This is what I thought it should work for, if it works fine for -1. But then what about the properties of arguments of self (the signs will then then be reversed )?? 
If we intend to preserve the properties, I think it shouldn't work for -1 as well!

**Comment by cbm755** [comment]
Maybe those docs are vague, ignore. Could_extract_minus_sign definitely replies on the -1 to keep working.

**Comment by cbm755** [comment]
Sorry "relies" not replies

**Comment by KTaruneshwarSai** [comment]
well i have worked on it and noticed that extract_multiplicatively works fine if you give second argument as positive..and if you give negative value there are many cases where it fails...
For example 
`>>> f=x**3*y**2
 >>> f.extract_multiplicatively(x*y)
 >>> x**2*y
 >>> f.extract_multiplicatively(-x*y)
 >>>
`

**Comment by cbm755** [comment]
That looks like the correct behaviour: there is no minus sign in `x**3*y**2` so cannot extract.

My understanding of `.extract_multiplicatively(-1)` is something like "would a human factor a minus sign out of this expression?"

**Comment by cbm755** [comment]
Put another way (and as I think I've said above at least once), if you could extract a "-1" from `x*y` then `.could_extract_minus_sign` would fail the `{e, -e}` thing explained in its docs.

**Comment by smichr** [comment]
> do you think this is bug

Yes. Consider:

```
>>> (-2-4*x).extract_multiplicatively(1+2*x)
>>> (-2-4*x).extract_multiplicatively(-1-2*x)
2
```

It allows a negative expression to be extracted. It seems that it should allow a bare negative to be extracted. I think I would change the routine by just recasting the input. Something like

```
given expr, test
if test.is_Number and test < 0:
  return (-expr).extract_multiplicatively(-test)
```

**Comment by ranjithkumar007** [comment]
@smichr, I think the recasting you suggested might fail in the following test case.
```
>>> (2*x).extract_multiplicatively(-1)
-2*x
```
But this should have been ```None```.

**Comment by smichr** [comment]
> I think the recasting you suggested would fail

Yes. What about doing something like

```
from sympy.core.function import _coeff_isneg as f
if test < 0 and all(f(t) for t in Add.make_args(expr)):
    return (-expr).extract_multiplicatively(-test)
```

**Comment by ranjithkumar007** [comment]
> from sympy.core.function import _coeff_isneg as f
> if test < 0 and all(f(t) for t in Add.make_args(expr)):
>     return (-expr).extract_multiplicatively(-test)

Looks great to me. I reproduced this locally and all tests(including the bugs reported in this issue) have also passed for ```extract_multiplicatively()```, If you agree i would like to send a PR with the fix that you suggested.

**Comment by smichr** [comment]
> If you agree

Sounds good. I'll watch for it.

**Comment by smichr** [comment]
You might want to test if `test` (or whatever the arg is) has a negative coefficient as well (rather than simply being negative) so the following works:

```
>>> (-2*x*y-4*x**2*y).extract_multiplicatively(-2*y)
>>> (+2*x*y+4*x**2*y).extract_multiplicatively(+2*y)
2*x**2 + x
```
