### ISSUE TITLE
IndexedBase commutes: A*B - B*A ==> 0

### ISSUE THREAD

**Issue by wakita** [sympy/sympy#12256]
The following code says A * B == B * A for IndexBases A and B:

```
n = Symbol('n', integer=True)
A = IndexedBase('A', shape=(n, n))
B = IndexedBase('B', shape=(n, n))
A * B - B * A
```

**Comment by mamakancha** [comment]
In general we know that two matrices commute if they are simultaneously` diagonalizable`. So would it be correct to say that the matrices formed by `IndexedBase` are `diagonalizable` or is it a bug in the code?

Note for reference: a square matrix A is called `diagonalizable` if there exists an invertible matrix P such that `(P^−1)AP` is a diagonal matrix.

**Comment by wakita** [comment]
Yes, I think so.  But is the use case of `IndexedBase` limited for simultaneously diagonalizable matrices?

**Comment by mamakancha** [comment]
If the commutative law is being followed for every square matrix of same order then I suppose `IndexedBase` indeed is limited for simultaneously diagonalizable matrices.

**Comment by wakita** [comment]
I could not find any description about `IndexedBase`s being *simultaneously* diagonalizable in SymPy documentation.  I wonder what kind of application meets this severely restricted condition.

I personally am trying to generate a working Python function applying `lambdify` to a formula that involves matrices whose sizes are parameterized by variables.  For this purpose, I do need an indexable general matrices and it seemed to me that `IndexedBase` is the only choice.

If there is a workaround, I love to hear.

**Comment by wakita** [comment]
I think an assumption setting is wrong with fresh `IndexedBase`s as you can see from the following example:

```
>>> from sympy import *
>>> n = Symbol('n', integer=True, positive=True)
>>> M = IndexedBase('M', (n, n))
>>> ask(Q.commutative(M))
True
>>> M = IndexedBase('M', (n, n+1))
>>> ask(Q.commutative(M))
True
```

It's weird that a non-square matrix is set commutative.

**Comment by isuruf** [comment]
You need `MatrixSymbol`, not `IndexedBase`.
`IndexedBase` is not a matrix but kind of an array that gives you indexed elements. `__mul__` doesn't make sense for it.
I'm closing this issue, but feel free to open this, if you think it should still be fixed.

**Comment by wakita** [comment]
All right.  Thank you for pointing me to `MatrixSymbol`.
