### ISSUE TITLE
Sympy can't solve simple differential equation

### ISSUE THREAD

**Issue by proy87** [sympy/sympy#12271]
It can't solve y''=1+(y')^2
I noticed that it can't determine type of the equation.

**Comment by SatyaPrakashDwibedi** [comment]
@proy87 I would like to work on this issue so where do you think change is to be done

**Comment by proy87** [comment]
In solvers/deutils.py there is line `hints = classifier(eq, func, dict=True, ics=ics, xi=xi, eta=eta, n=terms, x0=x0, prep=prep)`
Where classifier is `classify_ode` function in the same file.

In short, it can't decide what type of equation it is (classify it).
It raises exception `raise NotImplementedError(dummy + "solve" + ": Cannot solve " + str(eq))` (this line is in the same file).

**Comment by SatyaPrakashDwibedi** [comment]
@proy87 I think the error is in part `_nth_linear_match(reduced_eq, func, order)` because it's returning None in this case.

**Comment by proy87** [comment]
I didn't check it, but looks like you're correct.

**Comment by SatyaPrakashDwibedi** [comment]
@proy87 `classifier_ode` is not checking for degree 
I think nonlinear equation solving is not yet implemented

**Comment by samfdwang** [comment]
@proy87 how about use Fourier Transformation to make those type of nonlinear equation to linear one

**Comment by samfdwang** [comment]
There's no general theory to guarantee the uniqueness of such kind of non-linear DE.

**Comment by samfdwang** [comment]
This is Riccati type equations after making a transform $f=y'$, then $f'=1+f^2$,

**Comment by oscarbenjamin** [comment]
This equation can be solved by dsolve now using the order_reducible solver (on master):
```julia
In [101]: y = Function('y')                                                                                                                                   

In [102]: x = Symbol('x')                                                                                                                                     

In [103]: eq = Eq(y(x).diff(x, 2), 1 + y(x).diff(x)**2)                                                                                                       

In [104]: eq                                                                                                                                                  
Out[104]: 
  2                   2    
 d          ⎛d       ⎞     
───(y(x)) = ⎜──(y(x))⎟  + 1
  2         ⎝dx      ⎠     
dx                         

In [105]: classify_ode(eq)                                                                                                                                    
Out[105]: ('order_reducible',)

In [106]: dsolve(eq)                                                                                                                                          
Out[106]: 
               ⎛   2            ⎞
            log⎝tan (C₂ - x) + 1⎠
y(x) = C₁ + ─────────────────────
                      2          

In [107]: checkodesol(eq, dsolve(eq))                                                                                                                         
Out[107]: (True, 0)
```
