### ISSUE TITLE
SymPy stats expansion

### ISSUE THREAD

**Issue by Upabjojr** [sympy/sympy#12283]
Add

- `is_random` to every SymPy object (returns true if expression contains random symbols).
- test `is_random` on undefined functions and indexed bases.
- stats functions such as `P`, `E`, `var`, and `cov` should return their respective objects in case the `RandomSymbol` has no specified probability distribution.

**Comment by czgdp1807** [comment]
May be, `is_random` property can be added to `Basic` class(or whatever is the top most parent class) which can compute it's value by using the `OR` over all the `is_random` values of the objects args. Default value of `Symbol.is_random` should be `False` and `RandomSymbol.is_random` should be `True` and since every expression contains symbols, so for an expression `is_random` can be computed in O(number of args) complexity.

**Comment by Upabjojr** [comment]
@czgdp1807 since Python 3.5 methods can be added externally to the class through singledispatch.

We have dropped support for Python 2.7 and 3.4 this year, so we should start using this way in order not to overload too much `sympy/core`.

**Comment by czgdp1807** [comment]
I see, that's also possible. However, any thoughts on the approach? 
ping @Smit-create

**Comment by Smit-create** [comment]
One way is to add a method in class Expr
```python
def is_random(self):
    if random_symbols(self): # defined in sympy.stats.rv
        return True
    return False
```

**Comment by oscarbenjamin** [comment]
Both Basic and Expr have far too many methods, attributes and properties. Why can't this just be a normal function?

**Comment by Smit-create** [comment]
>  Why can't this just be a normal function?

We presently have a function `random_symbols` to get the random symbols from an expression.

**Comment by oscarbenjamin** [comment]
So why is a method needed?

**Comment by Upabjojr** [comment]
https://github.com/sympy/sympy/pull/19299/files#diff-91b28bab28724762f84e77df3facdb54R15

**Comment by Smit-create** [comment]
I will update it in my PR #19290

**Comment by Upabjojr** [comment]
I would recommend to add `is_random` in a separate PR, it's easier to review.

**Comment by Smit-create** [comment]
> I would recommend to add `is_random` in a separate PR, it's easier to review.

Okay, I will open it soon.
