### ISSUE TITLE
Runtime error encountered in testing of sympy/utilities/tests/test_lambdify.py

### ISSUE THREAD

**Issue by rathirocks-4** [sympy/sympy#12290]
RuntimeWarning: divide by zero encountered in true_divide

File "sympy/utilities/lambdify.py", line 440, in wrapper
    return funcarg(*[namespace['asarray'](i) for i in argsx], **kwargsx)

I am a beginner. Can someone guide me how to correct this?

**Comment by SatyaPrakashDwibedi** [comment]
@rathirocks-4 can you post your original code with errors

**Comment by rathirocks-4** [comment]
I didn't change anything from the forked version. I encountered this error while running customary tests on the whole project. The test and test file are as in my previous comment. "sympy/utilities/lambdify.py"
Test: test_lambdify.py

**Comment by E-DEA** [comment]
@rathirocks-4 Is numpy installed on your system ? I have been working on a problem with the same test and have put up a PR. Hopefully this error doesn't come up if PR is merged.

**Comment by rathirocks-4** [comment]
Yes, numpy is installed. Could you refer which PR you are talking about?

**Comment by E-DEA** [comment]
@rathirocks-4 , sorry for such a late reply didn't see the notification.
PR #12380 has solved the issue I guess.

**Comment by oscarbenjamin** [comment]
This is a warning sometimes emitted from numpy. I don't see any information to fix anything in SymPy here so I'll close this soon without more details
