### ISSUE TITLE
subs() not working properly

### ISSUE THREAD

**Issue by mamakancha** [sympy/sympy#12302]
I tried executing the following code :

```
In [1]: import sympy

In [2]: from sympy.abc import x,y

In [3]: expr1=x + x**y/x

In [4]: expr2=x*y + (x + y)/(x*y)

In [5]: expr2.subs(x,2)
Out[5]: 2*y + (y + 2)/(2*y)

In [6]: expr1.subs(x,2)
Out[6]: 2**y/2 + 2

In [7]: x=2

In [8]: expr1
Out[8]: x + x**y/x

In [9]: expr1.subs(x,2)
Out[9]: x + x**y/x
```

Before `In [7]`, the `subs()` is working quite fine but after `x=2` in `In [7]`, the `subs` function does not work as seen in `In [9]` . 
What could be the possible reason here?

**Comment by jksuom** [comment]
After [7], In [9] becomes `expr1.subs(2, 2)` (which does nothing to expr1).

**Comment by mamakancha** [comment]
If I use
`expr1.subs(x,8)` What should be the correct Output?

**Comment by jksuom** [comment]
Assuming that x denotes 2 and that there is no 2 in expr1, there should be no change in expr1.

**Comment by mamakancha** [comment]
Oh! Thanks a lot. 
I tried this with the following code :
```
expr1= x*2 + x**y/x
x=2
expr1.subs(x,8)
```
Output was :  `8*x + x**y/x`

So the code assigned value of `x` to `2` and when `expr1.sub(x,8)` was used, since `2` is `x` and `x` has to be substituted with `8` so we get our final output. Is that the correct explanation?

**Comment by jksuom** [comment]
I think so. It may be confusing that the (Python) symbol x has different meanings in different places. After import at [2] it denotes the SymPy symbol also denoted by x. So Python x denotes Symbol x in expr1. After [7] x changes its meaning and denotes the SymPy integer 2.So now Python x denotes Integer 2. There is no change in expr1, however. It still contains Symbol x.

**Comment by smichr** [comment]
Closing as a non-issue for SymPy.
