### ISSUE TITLE
Sympy returns an unevaluated limit

### ISSUE THREAD

**Issue by Shikhar1998** [sympy/sympy#12312]
Trying 
```
>>> e = 2**(-x)*(sin(x) + 1)**x
>>> limit(e, x, oo)
Limit(2**(-x)*(sin(x) + 1)**x, x, oo, dir='-')
```
returns an unevaluated limit.

**Comment by SatyaPrakashDwibedi** [comment]
@Shikhar1998 I think it should return 0.
right??

**Comment by Shikhar1998** [comment]
<0,oo> according to me.

**Comment by bhavishyagopesh** [comment]
@Shikhar1998 @SatyaPrakashDwibedi ,I might be wrong,But I think limit(L) at x=oo is not defined, as for large x=2*n*pi+pi/2, L=1 and for others L=0.

**Comment by SatyaPrakashDwibedi** [comment]
@bhavishyagopesh the first part 2**(-x) is zero
and zero multiplied by anything gives zero

**Comment by bhavishyagopesh** [comment]
@SatyaPrakashDwibedi  You cannot apply limits on parts separately,when individual limits do not exist.Try putting x=2npi+pi/2, Then expression tends to 1.

**Comment by ArifAhmed1995** [comment]
The value of `sin(x)` is not mathematically defined when `x --> oo`. Hence, the correct answer is an unevaluated limit.
@SatyaPrakashDwibedi `2**(-x)` is **not zero**. It tends to zero. Therefore one cannot say this limit yields zero.

**Comment by jksuom** [comment]
The limit does not exist, but it seems to me that all accumulation values are in the interval [0, 1]. So a better result could be `AccumBounds(0, 1)`.

**Comment by Shikhar1998** [comment]
Well, just to clarify, the above PR is not a fix, but will surely will give a good insight what the issue is .  
See the comment.
> One test case in AccumBounds is faulty or I can say the output by limit is incorrect (see here)
I had opened a issue #12312 ,that was the function obtained by applying ratsimp on the above stated test. But, interestingly it didn't gave any answer. Further going through the discussion on the issue I realised the output generated is incorrect of the original function and should be <0,1> .

**Comment by 0sidharth** [comment]
I think this might be related to #19453, as the answer is correct (according to what is currently expected from the code to output) if we simplify the expression first - 
```py
In [1]: e = 2**(-x)*(sin(x) + 1)**x

In [2]: limit(e, x, oo), limit(e.simplify(), x, oo)
Out[2]: 
⎛    ⎛ -x             x⎞        ⎞
⎜lim ⎝2  ⋅(sin(x) + 1) ⎠, <0, ∞>⎟
⎝x─→∞                           ⎠

```
