### ISSUE TITLE
Problem updating AUTHORS

### ISSUE THREAD

**Issue by mamakancha** [sympy/sympy#12318]
Since the file for AUTHORS was not updated since Sep 2016, I thought it would be a good idea to update it  since many new contributors have submitted their patches to Sympy.
However, on running `./bin/authors_update.py` in a `virtualenv` I get the following error:

```
Traceback (most recent call last):
  File "./bin/authors_update.py", line 15, in <module>
    from fabric.api import local, env
  File "/home/mamakancha/sympy/my_project1/lib/python3.4/site-packages/fabric/api.py", line 10, in <module>
    from fabric.context_managers import (cd, hide, settings, show, path, prefix,
  File "/home/mamakancha/sympy/my_project1/lib/python3.4/site-packages/fabric/context_managers.py", line 535
    def accept(channel, (src_addr, src_port), (dest_addr, dest_port)):
                        ^
SyntaxError: invalid syntax

```
I don't understand why I am getting this error.

**Comment by moorepants** [comment]
Fabric only works with Python 2, maybe you are using Python 3?

**Comment by mamakancha** [comment]
Yes. Found the same Issue at [https://github.com/fabric/fabric/issues/1209](https://github.com/fabric/fabric/issues/1209). 
Did the procedure with Python 2.7 and it worked. 
Submitted a PR for the same.

**Comment by mamakancha** [comment]
Closing the issue as the reason was pointed out by @moorepants and I have corrected it.
