### ISSUE TITLE
Extend det_LU_decomposition  to handle singular matrices

### ISSUE THREAD

**Issue by twhunt** [sympy/sympy#12321]
When passed a singular matrix, `det_LU_decomposition()` raises a ValueError with the message "No nonzero pivot found; inversion failed". However, this indicates that the determinant is 0. `det_LU_decomposition()` can be easily tweaked to return the correct value in this case.

**Comment by ajaysjacob** [comment]
Hi.I would like to try this out.Will it work if i just apply a try statement over the block of code in which L,U and P are defined of self matrix and set prod as 0 in the except?

**Comment by twhunt** [comment]
@ajaysjacob
I submitted a pull request for this issue, but please feel free to improve it!
