### ISSUE TITLE
The list of examples is not exhaustive.

### ISSUE THREAD

**Issue by mamakancha** [sympy/sympy#12341]
In the file `examples/all.py` , The `TERMINAL_EXAMPLES` (line `50`) as well as `WINDOWED_EXAMPLES` (line `77`) don't contain the following examples:
`examples/intermediate/sample.py`
`examples/begineer/plot_examples.py`

Is there a reason behind that or this should be fixed? If someone could let me know what do we mean by Terminal and Windowed examples, I could fix this issue by adding them to the desired category.

**Comment by mamakancha** [comment]
@jksuom  Any suggestions?

**Comment by jksuom** [comment]
Those examples depend on numpy that has not necessarily been installed in all systems. That may have been the reason why they were not included in all.py.

**Comment by mamakancha** [comment]
Thanks for pointing it out!
`examples/intermediate/sample.py` does use numpy
However, I don't see any use of numpy in `examples/begineer/plot_examples.py`. Am I missing some usage of numpy in `plot_examples.py`?

**Comment by jksuom** [comment]
plot_examples imports plot that imports numpy.

**Comment by oscarbenjamin** [comment]
The related PR #12344 was closed. Can this issue be closed as well?
