### ISSUE TITLE
Start using spherical_jn from SciPy

### ISSUE THREAD

**Issue by bjodah** [sympy/sympy#12369]
SciPy 0.18 deprecates `sph_jn`, we should use a try/except block to try to import spherical_jn

```
$ ./bin/test sympy/external/tests/test_scipy.py -k jn_zeros
...
  File "/home/bjorn/vc/sympy/sympy/external/tests/test_scipy.py", line 26, in test_jn_zeros
    assert eq(jn_zeros(0, 4, method="scipy"),
  File "sympy/functions/special/bessel.py", line 972, in jn_zeros
    root = solver(f, root)
  File "sympy/functions/special/bessel.py", line 964, in solver
    root = newton(f, x)
  File "/home/bjorn/.local/lib/python2.7/site-packages/scipy/optimize/zeros.py", line 167, in newton
    q0 = func(*((p0,) + args))
  File "sympy/functions/special/bessel.py", line 958, in <lambda>
    f = lambda x: sph_jn(n, x)[0][-1]
  File "/home/bjorn/.local/lib/python2.7/site-packages/numpy/lib/utils.py", line 100, in newfunc
    warnings.warn(depdoc, DeprecationWarning, stacklevel=2)
DeprecationWarning: `sph_jn` is deprecated!
scipy.special.sph_jn is deprecated in scipy 0.18.0. Use scipy.special.spherical_jn instead. Note that the new function has a different signature.
```

here is the use of sph_jn:
```
$ grep --include "*.py" sph_jn -R .
./sympy/functions/special/bessel.py:      `SciPy's sph_jn <http://docs.scipy.org/doc/scipy/reference/generated/scipy.special.jn_zeros.html>`_
./sympy/functions/special/bessel.py:        from scipy.special import sph_jn
./sympy/functions/special/bessel.py:        f = lambda x: sph_jn(n, x)[0][-1]
```

**Comment by E-DEA** [comment]
@bjodah I would like to take up this issue. Also, any kind of specifications about the problem would be helpful.

**Comment by mamakancha** [comment]
@E-DEA Hey! I had actually started working with this issue . Would it be fine if I continue working on this issue instead?

**Comment by bjodah** [comment]
@E-DEA go ahead. Not sure what you mean about specific failures, this issue is only about that single deprecation warning.

**Comment by bjodah** [comment]
@mamakancha if you've already started just continue and maybe @E-DEA can review your PR (or vice versa).

**Comment by E-DEA** [comment]
@mamakancha Ok. Please continue with your work. @bjodah I'll review it thanks.

**Comment by mamakancha** [comment]
I have submitted a PR. I will definitely need some help. Please review @E-DEA

**Comment by bjodah** [comment]
We still need to tests this on Travis using a recent version of SciPy (preferably from conda)

**Comment by progmatic-99** [comment]
can you elaborate on how to test this?
Also, would this issue be good for a begineer?
Thanks
