### ISSUE TITLE
MatrixElement in an Add cannot compare with `equals`

### ISSUE THREAD

**Issue by siefkenj** [sympy/sympy#12362]
For some reason, calling `.free_symbols` on a `MatrixElement` returns the matrix instead of the `MatrixElement`.  A consequence is that the following errors.

```
from sympy import *
A = MatrixSymbol('A', 4, 4)
A = A.as_explicit()
(A[1,1]-A[1,0]).is_constant()
```

with

```
/usr/lib64/python3.4/site-packages/sympy/core/function.py in __new__(cls, expr, *variables, **assumptions)
   1053             v, count = variables[i: i + 2]
   1054             iwas = i
-> 1055             if v._diff_wrt:
   1056                 # We need to test the more specific case of count being an
   1057                 # Integer first.

AttributeError: 'MatrixSymbol' object has no attribute '_diff_wrt'
```

this is because `(A[1,1]-A[1,0]).free_symbols` returns `{A}` instead of `{A[1,1], A[1,0]}`.  However, overriding `.free_symbols` in `MatrixElement` to _do the right thing_ causes a host of errors in the matrix tests.

**Comment by oscarbenjamin** [comment]
The issue seems to be fixed now:
```julia
In [20]: from sympy import * 
    ...: A = MatrixSymbol('A', 4, 4) 
    ...: A = A.as_explicit() 
    ...: (A[1,1]-A[1,0]).is_constant()                                                                                                                        
Out[20]: True
```

Although the free symbols result is the same
```julia
In [21]: (A[1,1]-A[1,0]).free_symbols                                                                                                                         
Out[21]: {A}
```
but actually that seems correct to me.

**Comment by siefkenj** [comment]
@oscarbenjamin Why does it seem right for the free symbols of `A[1,1]` to be `A`?

**Comment by oscarbenjamin** [comment]
Because `A` is the symbol and `A[1, 1]` is an expression derived from it (the same as `2*x` is an expression derived from the symbol `x`).

Maybe I'm misunderstanding this...

**Comment by siefkenj** [comment]
Are there other cases where calling `.free_symbols` on an indexed item produces the parent item? I guess I don't really know how `.free_symbols` is used in code.

**Comment by oscarbenjamin** [comment]
I don't know of other examples for indexing but if we look at the srepr
```julia
In [22]: A = MatrixSymbol('A', 3, 3)                                                                                                                          

In [23]: srepr(A[0,0])                                                                                                                                        
Out[23]: "MatrixElement(MatrixSymbol('A', Integer(3), Integer(3)), Integer(0), Integer(0))"

In [24]: srepr(A * 2)                                                                                                                                         
Out[24]: "Mul(Integer(2), MatrixSymbol('A', Integer(3), Integer(3)))"
```
then we see that as far as SymPy is concerned the action of taking `[0,0]` from `A` is an operation on the symbol `A` much like multiplying by 2 is. That's why I can substitute for `A` as in
```julia
In [25]: B = Matrix([[3]])                                                                                                                                    

In [26]: A[0,0].subs(A, B)                                                                                                                                    
Out[26]: 3
```

**Comment by siefkenj** [comment]
Okay. I'm convinced. Thank you for pointing this out.

**Comment by asmeurer** [comment]
See https://github.com/sympy/sympy/issues/14899 and the linked mailing list discussion.
