### ISSUE TITLE
Misspelling of "Bareiss" in Matrix module

### ISSUE THREAD

**Issue by siefkenj** [sympy/sympy#12361]
There are several references to the "Bareis" method for determinants, though his name appears to be spelled "Bareiss".  I assume this should be fixed and the one `s` version should be deprecated.

https://en.wikipedia.org/wiki/Bareiss_algorithm
https://www.genealogy.math.ndsu.nodak.edu/id.php?id=12730

**Comment by amrandahvur** [comment]
Can I be assigned this :)

**Comment by Hell0Kitty** [comment]
Hello,
I am willing to help fix this issue and I have started.

**Comment by siefkenj** [comment]
There is already a complete pull request PR #12363 to address this.
