### ISSUE TITLE
Addition of the Laplacian Operator

### ISSUE THREAD

**Issue by mohit3011** [sympy/sympy#12381]
While going through the Vector Module I noticed that Laplacian operations haven't been implemented in Sympy yet. I think this functionality can be added as in physics Laplacian operator plays a major role (like in Schrodinger Wave Equations).

Laplacian operations on Scalar functions is of importance and I would like to implement it.
What I hope after this implementation would be
```
>>>from sympy.vector import CoordSysCartesian, laplace
>>>R = CoordSysCartesian('R')
>>>v = R.x**2*R.y**2*R.z**2
>>>laplace(v, R)
2*R.x**2*R.y**2 + 2*R.x**2*R.z**2 + 2*R.y**2*R.z**2
```

**Comment by mohit3011** [comment]
@jksuom , @asmeurer  , please review it. Thanks

**Comment by siefkenj** [comment]
Has this been implemented?  Is it time to close this bug?

**Comment by ashu-22** [comment]
So Why we I get the issue from Triage account.I see that this issue is already revoked there.
