### ISSUE TITLE
Codegen:Boolean Implementation

### ISSUE THREAD

**Issue by SatyaPrakashDwibedi** [sympy/sympy#12423]
```
>>> from sympy import *
>>> from sympy.abc import x,y,z
>>> from sympy.utilities.codegen import codegen
>>> [(c,d),(e,f)]=codegen(("f",x&y),"C",header=False,empty=False)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python27\lib\site-packages\sympy\utilities\codegen.py", line 1744, in
 codegen
    global_vars))
  File "C:\Python27\lib\site-packages\sympy\utilities\codegen.py", line 585, in
routine
    return_val.append(Result(expr))
  File "C:\Python27\lib\site-packages\sympy\utilities\codegen.py", line 475, in
__init__
    raise TypeError("The first argument must be a sympy expression.")
TypeError: The first argument must be a sympy expression.
```
I think this is a bug in sympy it should return
```
#include "f.h"
#include <math.h>
double f(double x, double y) {
   double f_result;
   f_result = x && y;
   return f_result;
}
```

**Comment by SatyaPrakashDwibedi** [comment]
I have fixed the bug inside the `codegen.py` file but having doubts regarding where to add the test case in which function

**Comment by moorepants** [comment]
I think it should be a test case in the C printers.

**Comment by SatyaPrakashDwibedi** [comment]
@moorepants Do you mean `test_ccode.py`; it's already there.
I mean on 
```
>>>ccode(x&y)
'x && y'
```
but above `codegen` func didn't give the correct function.
 I think test case should be added somewhere in` tests` of `codegen.`

**Comment by bjodah** [comment]
Logcial operators operating on `double`s? I know it's defined but in my book that is a recipe for some serious confusion.

Isn't the user expected to pass something like:
```
>>> import sympy as sp
>>> x = sp.Symbol('x', real=True)
>>> y = sp.Symbol('y', real=True)
>>> sp.ccode(sp.Ne(x, 0) & sp.Ne(y, 0))
'x != 0 && y != 0'
```

**Comment by SatyaPrakashDwibedi** [comment]
@bjodah it works right for `ccode` but not for `codegen` the error is in `utilities.codegen` i.e if you run above command it does not work.

**Comment by asmeurer** [comment]
If the fix was in the codegen code I would add the test to the test_codegen.py file.

**Comment by SatyaPrakashDwibedi** [comment]
@asmeurer I am confused about adding in which function or should I define a new function for it?

**Comment by SatyaPrakashDwibedi** [comment]
@asmeurer See the changes I have done #12433  and it's giving output as required.
