### ISSUE TITLE
Is `sympy/doc/src/modules/rewriting.rst` complete?

### ISSUE THREAD

**Issue by bhavishyagopesh** [sympy/sympy#12425]
It abruptly ends with More Information :

**Comment by asmeurer** [comment]
If you look at the rst, it is trying to pull in the docstring for cse, but it isn't working. What's even more concerning is that this didn't even raise a warning in sphinx, or else the docs build would have failed.

**Comment by mohit3011** [comment]
@asmeurer , I would like to work on this issue. Could you please tell me which file raises warning for rewriting.rst . Thanks

**Comment by Vedarth** [comment]
@asmeurer Here is my solution :-- #12428 

Btw where is docstring for cse. Like what we need to do is simply write cse or something different after ```..autofunction::```?
I simply wrote cse. Please do review my changes.
I am really sorry  for mixing multiple solutions into single commit but my previous pull request hasn't been reviewed yet so I put solutions of two issues in a single pull request. I am terribly sorry for the inconvenience. Please tell me what am I expected to do in these situations.

**Comment by parsoyaarihant** [comment]
Is this issue fixed?

**Comment by asmeurer** [comment]
No, it doesn't look like it was ever fixed. http://docs.sympy.org/dev/modules/rewriting.html

**Comment by parsoyaarihant** [comment]
[http://docs.sympy.org/latest/gotchas.html#help](http://docs.sympy.org/latest/gotchas.html#help) also ends up with `The output will look something like this:`.
