### ISSUE TITLE
solveset(log(x)/x <= 0, x, S.Reals) ->(0, oo) instead of (0, 1]

### ISSUE THREAD

**Issue by smichr** [sympy/sympy#12429]
```
>>> var('x')
x
>>> solveset(log(x)/x<=0,x,S.Reals)
(0, oo)
```

The solution should be `(0, 1]`.

There is, perhaps, some issue with the `is_finite_with_finite_vars` routine which behaves as follows:

```
>>> from sympy.solvers.solveset import _is_finite_with_finite_vars as f
>>> f(1/Dummy())
True
>>> f(1/Dummy(real=True))
>>> f(1/Dummy(complex=True))
True
```

This is related to the reason behind why the test is failing that PR #12422 is addressing.

**Comment by mohit3011** [comment]
@smichr , I would like to work on this issue . Should I start with `is_finite_with_finite_vars` function ?

**Comment by smichr** [comment]
I'm not sure. Why is the complex case coming back as True? Why is the real case None? After knowing that I would proceed to either fix the assumptions or the `_is_finite...`. Once that is working, it seems like `solveset` should not be passing denominators to the `_is_finite` -- they should have been removed after checking for the singularities of the user's function. I can't access the line number right now, but just before calling `_is_finite` I think there is a `together` call. I suspect that shouldn't be there; that should be handled earlier.

**Comment by maurogaravello** [comment]
I noticed different behaviors of `solvify`   depending on different domains.

`from __future__ import division, print_function

from sympy import *
from sympy.solvers.solveset import solvify


x = Symbol('x')
expr = log(x)/x

dom = Interval(0, oo, True)
print(dom)
print(solvify(expr,x,dom))


dom = Interval(0, oo)
print(dom)
print(solvify(expr,x,dom))
`
In case the domain contains `0` the answer is correct, while if the domain does not contain `0` then the answer is not correct.

**Comment by maurogaravello** [comment]
I think that the problem is in the line 104 of `solveset.py`:

>     return x, s.intersection(domain) if isinstance(s, FiniteSet) else s

In the case, the function to be inverted is `log(x)/x`. In this case the inversion fails and so the return `s` is `0`, but it belongs to the co-domain and not to the domain. So `s.intersection(domain)` has not sense in this example.

**Comment by plonter99** [comment]
I came to the same conclusion as @maurogaravello .
According to the invert function documentation, it returns a tuple (g(x), set_h). After calling invert_real (on the entire real domain), seems to me that set_h would need to be intersected with the image of the function g on the original domain. Thus, intersecting with the domain only makes sense when g(x)=x. In this example g(x)=log(x)/x, so the image to intersect with would be (-oo,1/e], which includes set_h ( {0} ). The original domain ( (0,oo) ) does not include set_h. 
Is my understanding correct?

**Comment by vishu006** [comment]
On using solveset function to calculate this
>>> solveset((log(x-6)/x)<=0,x,S.Reals)
{7}
I think output should be (6,7], as the lhs is less than or equal to 0 for (6,7]. 

For examples such as 
>>> solveset(log(x+5)/x<=0,x,S.Reals)
[−4,0) 
Output is correct.

As I am new here, please correct me if I am wrong.

**Comment by maurogaravello** [comment]
I think it is another bug.

**Comment by vishu006** [comment]
I want to work on this. Can you please guide me on how to start to work on this issue?

**Comment by maurogaravello** [comment]
I am quite new to sympy.
In general I prepare a script with the code not working and i use pudb

Il 31/mar/2017 16:50, "Rajanikant Tenguria" <notifications@github.com> ha
scritto:

**Comment by vishu006** [comment]
Thank you @maurogaravello for your suggestion. I did not know about pudb and this would surely be helpful.

**Comment by smichr** [comment]
> I think that the problem is in the line 104 of solveset.py:

@maurogaravello , could you open a new issue (if there is not one for this issue already)

**Comment by maurogaravello** [comment]
@smichr vishu006 already opened #12466
