### ISSUE TITLE
DiagonalMatrix assumes shape is square

### ISSUE THREAD

**Issue by smichr** [sympy/sympy#12427]
`DiagonalMatrix` assumes its shape is (row x row):

```
>>> a=DiagonalMatrix(MatrixSymbol('x', 2, 3))
>>> b=DiagonalMatrix(MatrixSymbol('x', 3, 2))
>>> a.shape, b.shape
((2, 2), (3, 3))
```

So it is not surprising that the multiplication may fail;

```
>>> a*b
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "sympy\matrices\expressions\matexpr.py", line 21, in __sympifyit_wrapper
    b = sympify(b, strict=True)
  File "sympy\core\decorators.py", line 119, in binary_op_wrapper
    return func(self, other)
  File "sympy\matrices\expressions\matexpr.py", line 106, in __mul__
    def __mul__(self, other):
  File "sympy\matrices\expressions\matmul.py", line 38, in __new__
    validate(*matrices)
  File "sympy\matrices\expressions\matmul.py", line 136, in validate
    raise ShapeError("Matrices %s and %s are not aligned"%(A, B))
sympy.matrices.matrices.ShapeError: Matrices DiagonalMatrix(x) and DiagonalMatri
x(x) are not aligned
```

But non-square matrices should be allowed:

```
>>> Matrix(2,3,(1,0,0,0,2,0)) * Matrix(3,2,(4,0,0,5,0,0))
Matrix([
[4,  0],
[0, 10]])
```

The effective matrix size should be the minimum of the given dimensions. When any dimension is symbolic, there should be a way to indicate which one is the smaller. Or if one is symbolic and the other definite then (maybe) the definite one could be taken to be the limiting one. If both are symbolic there should either be an error or else a way to select the smaller of the two dimensions.

A **related issue** is that `DiagonalOf` assumes its shape is (row, 1):

```
>>> DiagonalOf(MatrixSymbol('x', 3, 2)).shape
(3, 1)  <------- that should be (2, 1)
```

**Comment by Vedarth** [comment]
@smichr  I am interested. Where should I start looking?

**Comment by Vedarth** [comment]
@smichr You have given me really great guidance. Thanks a lot for helping me out. I really need your honest opinion on this one. I am submitting a GSoC proposal to clean up and reorganize Matrices module and rewrite and improve upon code that are mathematically flawed. My aim is to make Matrices module more usable. Which also involves trying to return n in #12300 .Can I submit a proposal like that? Will it be enough for a GSoC project? I believe issues like this one are pretty complex and need more attention to get implemented properly. I believe Matrices module deserves personal attention.  A GSoC project will be the perfect thing. Can you help me out on this one?

**Comment by smichr** [comment]
@vedarth , there is a very significant overhaul of matrices being attended to by @siefkenj (e.g. #12402, #12390). Also, I am submitting a PR addressing this (and other) issues with `DiagonalMatrix` and `DiagonalOf`. And having just done the work, I can safely say it wasn't GSoC in scale. ;-) Perhaps something else will catch your attention, however. To get youor feet wetter, however, I would value any feedback you have on #12459.
