### ISSUE TITLE
DiagonalMatrix[i, j] -> 0

### ISSUE THREAD

**Issue by smichr** [sympy/sympy#12426]
Similar to #12300, DiagonalMatrix references to position (i,j) give 0:

```
>>> d = DiagonalMatrix(MatrixSymbol('x', 3, 3))
>>> d[i,j]
0
```

**Comment by smichr** [comment]
ping @bhavishyagopesh at #12316

**Comment by bhavishyagopesh** [comment]
@smichr I found something really strange(only if I'm not mistaken)
`from sympy import *
from sympy import Q as Query`

**Comment by Vedarth** [comment]
@smichr Here is my solution :- #12428 
Kindly review it.

```
>>> from sympy import *
>>> x=symbols('x')
>>> i,j=symbols('i j')
>>> d = DiagonalMatrix(MatrixSymbol('x', 3, 3))
>>> d[i,j]
KroneckerDelta(i, j)*x[i, 0]
>>> d[i,i]
x[i, 0]
>>> i=1
>>> j=2
>>> d[i,j]
0
```
I used your solution and @bhavishyagopesh solution to make a very efficient code.
Is is it giving the expected answer?@smichr Here is my solution
```
>>> from sympy import *
>>> x=symbols('x')
>>> i,j=symbols('i j')
>>> d = DiagonalMatrix(MatrixSymbol('x', 3, 3))
>>> d[i,j]
KroneckerDelta(i, j)*x[i, 0]
>>> d[i,i]
x[i, 0]
>>> i=1
>>> j=2
>>> d[i,j]
0
```
I used your solution for #12300 
Is it giving the expected answer?

**Comment by Vedarth** [comment]
@bhavishyagopesh  

> x=Matrix([[1,0,0],[0,2,0],[0,0,3]])
d = DiagonalMatrix(x)
d[1,1]

> It returns zero but should return 2, I think its becoz "/matrices/expressions/diagonal.py" line : 11,(I used trace), it returns self.arg[i, 0] when i==jwhy?

What you have done here is that, you have made a matrix of a matrix see if you take output of d only you get
```
>>> d
DiagonalMatrix(Matrix([
[1, 0, 0],
[0, 2, 0],
[0, 0, 3]]))
```
So basically what sympy is thinking is that you have put a matrix inside a diagonal matrix. That is a matrix which is made of a matrix. It is quite complicated for me to describe exactly what you have done. d[0,0] is coming as 1 which is the correct answer but idon't know how can we logically access other elements maybe we should try to do that. But I can say this for certain that you were not trying to create a matrix of a matrix.

**Comment by Vedarth** [comment]
@smichr I am terribly sorry that I am submitting solutions of two different issues in a single pull request. I just don't how else could I have done it.
