### ISSUE TITLE
Trailing Semicolons

### ISSUE THREAD

**Issue by rajatthakur** [sympy/sympy#12438]
Some of the files contain trailing semicolons which are redundant and should be removed.

**Comment by SatyaPrakashDwibedi** [comment]
@rajatthakur I don't think semicolons are significant in python

**Comment by rajatthakur** [comment]
@SatyaPrakashDwibedi You are absolutely right and that is same as what I am saying. Semicolons have no significance in python (at least in this case) and thus should be removed.
