### ISSUE TITLE
solve hangs on 4*4 linear system with non-trivial coefficients

### ISSUE THREAD

**Issue by vasdommes** [sympy/sympy#12448]
sympy 1.0.1dev
Python 3.5.2

Consider solving 3\*3 or 4\*4 linear system with unknown coefficients: a_ik * x_k + b_i == 0.
`solve` works fast when coefficients are simple symbols like `a_12` (see function `solve_fast` below), but slows down dramatically if coefficients are undefined functions like `a(1,2)` (see function `solve_slow` below).

Example:
```python
def solve_fast(n, **kwargs):
    from sympy import solve, symbols
    from sympy.core.cache import clear_cache

    clear_cache()

    eqns = []
    xs = symbols('x_0:{}'.format(n))

    for i in range(n):
        eq = 0
        for k in range(n):
            aik = symbols('a_{}{}'.format(i, k))
            eq += aik * xs[k]

        bi = symbols('b_{}'.format(i))
        eq += bi
        eqns.append(eq)

    return solve(eqns, *xs, **kwargs)


def solve_slow(n, **kwargs):
    from sympy import solve
    from sympy.abc import a, b, x

    from sympy.core.cache import clear_cache

    clear_cache()

    eqns = []
    xs = [x(k) for k in range(n)]

    for i in range(n):
        eq = 0
        for k in range(n):
            eq += a(i, k) * x(k)
        eq += b(i)
        eqns.append(eq)

    return solve(eqns, *xs, **kwargs)
```

Simple benchmarks on my laptop:
```
>>> %timeit solve_fast(3, simplify=False, check=False)
1 loop, best of 3: 241 ms per loop

>>> %timeit solve_fast(4, simplify=False, check=False)
1 loop, best of 3: 687 ms per loop

>>> %timeit solve_slow(3, simplify=False, check=False)
1 loop, best of 3: 19.3 s per loop
```

`solve_slow(4, simplify=False, check=False)` hangs for hours, I couldn't wait for the result.
Wolfram Mathematica solves such system in less than a second.

**Comment by smichr** [comment]
Hmmm. That's unexpected. I would have expected that the functions to be solved for would have been replaced with symbols and the system would solve as for the fast case.

**Comment by vasdommes** [comment]
Note also that for the 3*3 system the solution given by `solve_slow` has more complicated form in comparison to `solve_fast`:

input:
```python
from sympy import symbols
from sympy.abc import a,b,x

subs_rules = dict()
for i in range(3):
    for k in range(3):
        aik = symbols('a_{}{}'.format(i,k))
        subs_rules[a(i,k)] = aik
        
    bi = symbols('b_{}'.format(i))
    subs_rules[b(i)] = bi
    
    xi = symbols('x_{}'.format(i))
    subs_rules[x(i)] = xi
        
res_slow = {k.subs(subs_rules) : v.subs(subs_rules) for k, v in solve_slow(3, simplify=False, check=False).items()}
res_fast = solve_fast(3, simplify=False, check=False)
for x in symbols('x_0:3'):
    slow = res_slow[x]
    fast = res_fast[x]
    assert (slow-fast).simplify() == 0
    print('{}: slow.count_ops(): {}, fast.count_ops(): {}'.format(x, slow.count_ops(), fast.count_ops()))
```
output:
```
x_0: slow.count_ops(): 140, fast.count_ops(): 69
x_1: slow.count_ops(): 121, fast.count_ops(): 69
x_2: slow.count_ops(): 88, fast.count_ops(): 69
```

This is indeed surprising: sympy doesn't know anything special about `a(i, k)` and `b(i)` (as well as `a_ik` and `b_i`). Then why does it use different solving strategies in `solve_fast` and `solve_slow`?

**Comment by smichr** [comment]
Two different paths were being taken because of how symbolic matrices (vs numerical) were being detected. When that is fixed, the times taken are similar. See #12467

**Comment by smichr** [comment]
Thanks for this useful report!
