### ISSUE TITLE
CCodePrinter._print_Indexed assumes row-major ordering

### ISSUE THREAD

**Issue by bjodah** [sympy/sympy#12464]
When working with BLAS and LAPACK it's quite common to work with column-major ordering.
To avoid unneccessary transposes `_print_Indexed` should also support column-major ordering.
It is probably easiest to add either an `ordering` or `strides` property to `Indexed`.

**Comment by ArifAhmed1995** [comment]
Can you show me a simple example of an `Indexed` object which would use this method when translated to C code? I have gone through [this page](http://docs.sympy.org/dev/modules/tensor/indexed.html) but any `Indexed` object I'm trying out seems to lack some or the other attribute required in `_print_Indexed`.

**Comment by bjodah** [comment]
Sure,
```
>>> A = IndexedBase('A')
>>> A = IndexedBase('A', shape=(5,3))
>>> i, j = Idx('i'), Idx('j')
>>> ccode(A[i,j])
'A[3*i + j]'
```

**Comment by SatyaPrakashDwibedi** [comment]
@bjodah I think `CCodePrinter` assumes row major ordering because accessing matrices through rows is faster than accessing them through columns.

**Comment by bjodah** [comment]
@SatyaPrakashDwibedi no, which is faster depends on ordering. Generally speaking, iterating over the dimension with the lowest stride gives fastest access due to cache locality.
