### ISSUE TITLE
`Permutation` and `Cycle` as a callables have confusing behavior

### ISSUE THREAD

**Issue by siefkenj** [sympy/sympy#12487]
There was some cleverness in the design of `Permutation` as a callable to mimic cycle notation.  However, I think this is really confusing.

Cycle notation:  when a permutation is written as a product of cycles, for example "(a,b)(c,d)" and you wish to apply it to a list `l`, that generally means

```
l[c], l[d] = l[d], l[c]
l[a], l[b] = l[b], l[a]
```

That is, first do the swap `(a,b)` then do the swap `(c,d)`.  The `Permutation` object cleverly uses callable to mimic this notation.  That is, you can construct an object `Permutation(a,b)(c,d)` since `Permutation(a,b)` is callable.  However, this seems contradictory to how functions are normally treated in a programming language.

When I encounter a function like `( Perm(swap a,b) )(swap c,d)` I expect that first `a,b` are swapped and then `c,d` are swapped which is equivalent in the current codebase to `Permutation(c,d)(a,b)`.  I think at minimum there needs to be a `kwarg` to allow the reversed order that I expect, but I also think that using callable this way is too clever a use of a programming grammar to look like a common mathematical notation.

**Comment by smichr** [comment]
wikipedia gives the following statement about cycle notation:

> Cycle notation
> This alternative notation describes the effect of repeatedly applying the permutation, thought of as a function from a set onto itself. It expresses the permutation as a product of cycles corresponding to the orbits of the permutation; since distinct orbits are disjoint, this is referred to as "decomposition into disjoint cycles".

So if the cycles are disjoint (as it sounds like they are intended to be) then there is no problem, is there?

And if the user chooses not to make them disjoint...they get what they get and they are told what they get: the docstring says evaluation goes from right to left. Perhaps the docstring could be modified to indicate that *if orbits are not disjoint then the result is equivalent to processing orbits from right to left.*  

As I recall, one cannot capture all arguments at once, only one orbit at a time so I'm not sure a kwarg would work.

**Comment by siefkenj** [comment]
@smichr Yes, for disjoint cycles the order doesn't matter.  I think I understand what you're saying--to have evaluation go left to right instead of right to left via a kwarg, either the order would need to be stored in `.args` or there would need to e a `RightPermuation` and a `LeftPermutation` subclass...

**Comment by smichr** [comment]
Here is the current status

```
>>> Cycle(1,2)(2,3).list()  # current, R to L
[0, 3, 1, 2]
>>> Cycle((2,3), (1,2)).list()  # NEW, L to R in a PR that I will open
[0, 3, 1, 2]
>>> Permutation(1,2)(2,3).list()  # current, R to L
[0, 3, 1, 2]
>>> Permutation(((1,2), (2,3))).list()  # current, R to L  <-- fix
[0, 3, 1, 2]
```
I added a cycle (non-call) option to Cycle so tuples/cycles are processed from left to right. But the already existing input to Permutation operates right to left. To fix that we could raise an error/warning for non-disjoint cycles and fix it to process L to R, then remove the non-disjoint error after the next release.

Do you have other ideas? I don't really like the idea of LPerm and Rperm. (But I don't deal with this area of mathematics, however, so don't even know if that is a useful idea or just a band-aid over this wart.)
