### ISSUE TITLE
strange `solveset` output

### ISSUE THREAD

**Issue by SteliosStefanatos** [sympy/sympy#12494]
`solveset` fails for the following trivial (?) equation (Sympy ver. 1.0)

```
import sympy as sp
x, y = sp.symbols('x, y')
expr = 5 * x / ((x+10) * (10*x/(x+10) +y )) - sp.S(1)/2
sol = sp.solveset(expr, y)
print(sol)
```

> `{0} \ {-10*x/(x + 10)}`

A similar output is given if a solution with respect to `x` is requested. Passing `expr.simplify()` instead of `expr` does not help either.

Using `solve` gives the expected `0` answer, when solving w.r.t. `y`, but requires to pass `expr.simplify()` in order to solve w.r.t. `x`

(This was reported in http://stackoverflow.com/questions/43197272/sympy-solveset-multi-variable-non-linear-solutions.)

**Comment by smichr** [comment]
It's a constraint on y. If y had the value of `10*x/(x+10)` the denominator would be zero. If `x=0` then `10*x/(x+10) = 0` so the solution for the original expression is `{}`, otherwise the solution is 0. It's a set's way of returning a Piecewise solution (I think).

**Comment by SteliosStefanatos** [comment]
@smichr Thank you for the response. You are right, of course;  `solveset` does find the correct solution and moreover gives the set for which the equation is undefined.
