### ISSUE TITLE
pprint(Sum(f(n), (n, -oo, oo))) gives False instead of n = -∞

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#12501]
```
>>> pprint(Sum(f(n), (n, -oo, oo)))
  ∞
 ___
 ╲
  ╲   f(n)
  ╱
 ╱
 ‾‾‾
False
```

The False should be printed as `n = -∞`.

**Comment by Abdullahjavednesar** [comment]
SymPy live gives it correct
```
>>> pprint(Sum(f(n), (n, -oo, oo)))
   oo       
  __        
  \ `       
   )    f(n)
  /_,       
n = -oo  
```

**Comment by mohit3011** [comment]
@Abdullahjavednesar , sympy live often give a different result than what is produced on the terminal.

**Comment by Vedarth** [comment]
@asmeurer I don't understand how this loop is working. 
```
for lim in expr.limits:
            if len(lim) == 3:
                prettyUpper = self._print(lim[2])
                prettyLower = self._print(Equality(lim[0], lim[1]))
            elif len(lim) == 2:
                prettyUpper = self._print("")
                prettyLower = self._print(Equality(lim[0], lim[1]))
            elif len(lim) == 1:
                prettyUpper = self._print("")
                prettyLower = self._print(lim[0])

            max_upper = max(max_upper, prettyUpper.height())

            # Create sum sign based on the height of the argument
            d, h, slines, adjustment = asum(
                H, prettyLower.width(), prettyUpper.width(), ascii_mode)
            prettySign = stringPict('')
            prettySign = prettyForm(*prettySign.stack(*slines))

            if first:
                sign_height = prettySign.height()

            prettySign = prettyForm(*prettySign.above(prettyUpper))
            prettySign = prettyForm(*prettySign.below(prettyLower))

            if first:
                # change F baseline so it centers on the sign
                prettyF.baseline -= d - (prettyF.height()//2 -
                                         prettyF.baseline) - adjustment
                first = False

            # put padding to the right
            pad = stringPict('')
            pad = prettyForm(*pad.stack(*[' ']*h))
            prettySign = prettyForm(*prettySign.right(pad))
            # put the present prettyF to the right
            prettyF = prettyForm(*prettySign.right(prettyF))
```
What I am not getting is how n = lim[1] is getting printed. If self._print become false then how is anything getting printed?

**Comment by adilbeknurmakov** [comment]
Possible error may line in loop body. Specifically in the sequence of code. Printing statement is ran before than check of true false condition. That's why checking fails Try to change order and use something like this. 
  # Create sum sign based on the height of the argument
            d, h, slines, adjustment = asum(
                H, prettyLower.width(), prettyUpper.width(), ascii_mode)
            prettySign = stringPict('')
            prettySign = prettyForm(*prettySign.stack(*slines))

            if first:
                sign_height = prettySign.height()

            prettySign = prettyForm(*prettySign.above(prettyUpper))
            prettySign = prettyForm(*prettySign.below(prettyLower))

            if first:
                # change F baseline so it centers on the sign
                prettyF.baseline -= d - (prettyF.height()//2 -
                                         prettyF.baseline) - adjustment
                first = False

            # put padding to the right
            pad = stringPict('')
            pad = prettyForm(*pad.stack(*[' ']*h))
            prettySign = prettyForm(*prettySign.right(pad))
            # put the present prettyF to the right
            prettyF = prettyForm(*prettySign.right(prettyF))
for lim in expr.limits:
           
            elif len(lim) == 1:
                prettyUpper = self._print("")
                prettyLower = self._print(lim[0])
 if len(lim) == 3:
                prettyUpper = self._print(lim[2])
                prettyLower = self._print(Equality(lim[0], lim[1]))
            elif len(lim) == 2:
                prettyUpper = self._print("")
                prettyLower = self._print(Equality(lim[0], lim[1]))

**Comment by parsoyaarihant** [comment]
Related to #10927 .

**Comment by asmeurer** [comment]
Curious that this bug doesn't seem to affect this

```
>>> Eq(x, x)
True
>>> pprint(Sum(x, (x, 1, x)))
  x
 ___
 ╲
  ╲   x
  ╱
 ╱
 ‾‾‾
x = 1
```
