### ISSUE TITLE
Simplify() returns wrong simplified expressions using Sympy 1.0 (trigonometric functions)

### ISSUE THREAD

**Issue by HoaiNam8282** [sympy/sympy#12506]
The goal is to simplify the 2nd derivative of the following expression:
`expr = 1.0 * cos(x) + 2.0 * cos( asin( 0.5 * sin(x))) ` 

However, since Sympy was upgraded to version 1.0, the simplify() function does no longer return the correct simplification of its second derivative. The expression was correctly simplified in Sympy version 0.7.6.1.

Hence, the expression to evaluate was split in order to determine when the simplify() function started to return uncorrect results. Resulting expressions from Sympy 0.7.6.1 and Sympy 1.0 are compared  for all the tested cases. 

The generic code used to perform these comparisons can be found [HERE](https://github.com/sympy/sympy/files/905611/Test_Simplify.txt).

1) Evaluation of expr =` cos( asin( 0.5 * sin(x) )) `
While evaluating only the second term, both versions of Sympy gave the same results after the simplification of the second derivative. The initial expression is simplified before the first differentiation. Then, the resulting expression is also simplified after each differentiation .

[Sympy 0.7.6.1]
![test1_sympy0761](https://cloud.githubusercontent.com/assets/17083539/24800806/f433681a-1ba1-11e7-8965-ef716d679ed2.PNG)

[Sympy 1.0]
 ![test1_sympy1](https://cloud.githubusercontent.com/assets/17083539/24800821/0ac2b9aa-1ba2-11e7-88b5-f2fcb2dd27a1.PNG)

2) Evaluation of expr =`2.0*cos( asin(0.5* sin(x) ))`
The previous expression is multiplied by 2.0.  Both versions of Sympy gave the same results.

[Sympy 0.7.6.1]
![aveclex2devantsympy0761](https://cloud.githubusercontent.com/assets/17083539/24801263/bf682d58-1ba3-11e7-8c7d-8187335ab0ad.PNG)

[Sympy 1.0]
![avecle2devantsympy1](https://cloud.githubusercontent.com/assets/17083539/24801269/c41751f8-1ba3-11e7-8b17-941426fbc2b8.PNG)

3) Evaluation of expr =`cos(x) + cos( asin( sin(x) )) `
A cos(x) is added to the previous expression while the multiplying factor was removed. Again, both versions of Sympy gave the same results.

[Sympy 0.7.6.1]
![test2_sympy0761](https://cloud.githubusercontent.com/assets/17083539/24801374/42651a18-1ba4-11e7-89ac-9922785ae5f9.PNG)

[Sympy 1.0]
![test2_sympy1](https://cloud.githubusercontent.com/assets/17083539/24801379/4fa65d22-1ba4-11e7-8dde-72302b6cefe5.PNG)

4) Evaluation of expr =`cos(x) + cos( asin( 0.5 sin(x))) `
Building on the previous expression, a multiplying factor (0.5) is added before sin(x). In that case, Sympy 1.0 gives a different result in comparison with Sympy 0.7.6.1.

[Sympy 0.7.6.1]
![test3_sympy0761](https://cloud.githubusercontent.com/assets/17083539/24801497/c86415a6-1ba4-11e7-8222-0ab9afe1a5cf.PNG)

[Sympy 1.0]
![test3_sympy1](https://cloud.githubusercontent.com/assets/17083539/24801502/ce64dd78-1ba4-11e7-88b9-ad3b78d77ee4.PNG)

5) Evaluation of expr =` __  cos(x) + 2.0 * cos( asin( 0.5 sin(x))) `
A factor (2.0) now multiplies the second term of the expression. Sympy 1.0 gives a different result as well.

[Sympy 0.7.6.1]
![sansle1devantsympy0761](https://cloud.githubusercontent.com/assets/17083539/24801609/3c4f0bd8-1ba5-11e7-9f17-1464d75fa095.PNG)

[Sympy 1.0]
![sansle1devantsympy1](https://cloud.githubusercontent.com/assets/17083539/24801617/4626220e-1ba5-11e7-94ec-908fafe2fb2d.PNG)

6) Original expression: expr =` 1.0 * cos(x) + 2 * cos( asin( 0.5 sin(x)))  `
Of course, the simplification of the second derivative of the original expression is different from Sympy version 0.7.6.1 and version 1.0. Surprisingly, multiplying by "1.0" the first cos(x) returns a different simplification if compared to the one found in section 5).

[Sympy 0.7.6.1] :  correct simplification
![comparison_simplify_correct](https://cloud.githubusercontent.com/assets/17083539/24801863/1dcb1fe8-1ba6-11e7-83e5-eca3b6bea248.PNG)

[Sympy 1.0] :  UNcorrect simplification
![comparison_simplify_notcorrect](https://cloud.githubusercontent.com/assets/17083539/24801878/29e34daa-1ba6-11e7-9d80-6c93474fbe88.PNG)

Did anybody encounter the same issue and know how to solve it ?

**Comment by bjodah** [comment]
Try using `Rational(1, 2)`, `Rational(1, 4)`, ... instead of 0.5, 0.25, ...
