### ISSUE TITLE
Sympy cannot parse sys.version correctly in Anaconda3 distibution 

### ISSUE THREAD

**Issue by vbchrist** [sympy/sympy#12536]
This is my first bug report, please let me know if it needs anything.

When using the Python C API and the Anaconda3 Sympy distribution there is a bug where Sympy cannot be loaded using PyImport_ImportModule("sympy").

This is due to the addition of "|Continuum Analytics, Inc.|" in the sys.version string which the REGEX parser is not expecting. This was verified by setting sys.version to "3.5.2 (default, Jul  5 2016, 11:45:57) [MSC v.1900 32 bit (Intel)]" and having the import be successful.

The documentation for sys.version recommends that it is not used to retrieve version information.

The proposed fix is to retrieve the required version information from sys.version_info and not sys.version.

sys.version
A string containing the version number of the Python interpreter plus additional information on the build number and compiler used. This string is displayed when the interactive interpreter is started. Do not extract version information out of it, rather, use version_info and the functions provided by the platform module.

Here is the error traceback starting with a output of the sys.version:

VERSION:        3.5.2 |Continuum Analytics, Inc.| (default, Jul  5 2016, 11:45:57) [MSC v.1900 32 bit (Intel)]
Traceback (most recent call last):
  File "C:\Program Files (x86)\Anaconda3\Lib\site-packages\sympy\__init__.py", line 57, in <module>
    from .core import *
  File "C:\Program Files (x86)\Anaconda3\Lib\site-packages\sympy\core\__init__.py", line 4, in <module>
    from .sympify import sympify, SympifyError
  File "C:\Program Files (x86)\Anaconda3\Lib\site-packages\sympy\core\sympify.py", line 9, in <module>
    from .evaluate import global_evaluate
  File "C:\Program Files (x86)\Anaconda3\Lib\site-packages\sympy\core\evaluate.py", line 1, in <module>
    from .cache import clear_cache
  File "C:\Program Files (x86)\Anaconda3\Lib\site-packages\sympy\core\cache.py", line 60, in <module>
    if platform.python_implementation() == 'PyPy':
  File "C:\Users\COMPANY_NAME\AppData\Local\Programs\Python\Python35-32\Lib\platform.py", line 1292, in python_implementation
    return _sys_version()[0]
  File "C:\Users\COMPANY_NAME\AppData\Local\Programs\Python\Python35-32\Lib\platform.py", line 1252, in _sys_version
    repr(sys_version))
ValueError: failed to parse CPython sys.version: '3.5.2 |Continuum Analytics, Inc.| (default, Jul  5 2016, 11:45:57) [MSC v.1900 32 bit (Intel)]'

**Comment by asmeurer** [comment]
I don't think this is an issue with SymPy. It looks like the error is in the Python platform module, not SymPy itself. Please reopen if you believe otherwise. 

Based on your traceback, your platform module is coming from `C:\Users\COMPANY_NAME\AppData\Local\Programs\Python\Python35-32\Lib\platform.py` instead of `C:\Program Files (x86)\Anaconda3\Lib\platform.py`. The Anaconda Python has platform.py patched so that it can parse the sys.version string correctly. This is probably due to the `PYTHONHOME` environment variable being set. You can run `conda info -a` to see the environment variables that can affect this.
