### ISSUE TITLE
Cannot substitute IndexedBase for a list

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#12533]
```py
>>> d = IndexedBase('d')
>>> d[0].subs(d, range(5))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "./sympy/core/basic.py", line 915, in subs
    rv = rv._subs(old, new, **kwargs)
  File "./sympy/core/basic.py", line 1029, in _subs
    rv = fallback(self, old, new)
  File "./sympy/core/basic.py", line 1006, in fallback
    rv = self.func(*args)
  File "./sympy/tensor/indexed.py", line 157, in __new__
    return base[args]
  File "./sympy/sets/fancysets.py", line 923, in __getitem__
    rv = (self.stop if i < 0 else self.start) + i*self.step
TypeError: unorderable types: list() < int()
```

Ideally this would work.

**Comment by asmeurer** [comment]
If you pass a `list` instead of a `range` object it remains unchanged

```
>>> d[0].subs(d, list(range(5)))
d[0]
```

**Comment by artemrizhov** [comment]
Hi! Is there a workaround for substituting the IndexedBase for a list in summation?

**Comment by asmeurer** [comment]
Looks like you can do it with `replace`, but it doesn't know how to evaluate:

```
>>> d[0].replace(d, lambda : (1, 2))
(1, 2)[0]
>>> d[0].replace(d, lambda : (1, 2)).doit()
(1, 2)[0]
```

However, it looks like you can use replace directly to get it to work

```py
>>> l = range(5)
>>> d[0].replace(Indexed, lambda i, j: Indexed(i, j) if i != d else l[j])
0
```

**Comment by artemrizhov** [comment]
This did not work for me. Is my code correct?

```python
i = Idx('i')
d = IndexedBase('d')
expr = Sum(d[i], (i, 1, 5))
l = range(1, 6)
expr.replace(Indexed, lambda b, i: Indexed(b, i) if b != d else l[i])
```
This produces TypeError: list indices must be integers, not Idx

**Comment by asmeurer** [comment]
You need to evaluate the Sum first, `expr.doit()` (or use `summation` instead of `Sum`). Otherwise it tries to do `range(1, 6)[i]` where `i = Idx('i')` and range does not know how to evaluate on Idx.

**Comment by artemrizhov** [comment]
Oh, I just found you reply on SO. Thank you!

**Comment by asmeurer** [comment]
Yes, I wanted to keep it in both places, so that people could find the answer regardless of which site they ended up in. Plus, the discussion here could get technical, as the goal is to actually fix the issue.

**Comment by asmeurer** [comment]
This issue is related: https://github.com/sympy/sympy/issues/7985. I guess it was fixed for dictionaries, but not lists.

**Comment by artemrizhov** [comment]
On StackOverflow you provided [an example](http://stackoverflow.com/a/43356538/969451) where you use a range of six elements:

```python
>>> i = Idx('i')
>>> s = Sum(d[i], (i, 1, n))
>>> l = range(6)
>>> s.subs(n, 5).doit().replace(Indexed, lambda i, j: Indexed(i, j) if i != d else l[j])
15
```
This works, but `l` actually contains 6 elements instead of 5:
```python
>>> len(l)
6
>>> l
[0, 1, 2, 3, 4, 5]
```
If I replace it with a range of 5 elements `range(1,6)` then it fails with "IndexError: list index out of range". Why it requires elements #0 for some reason, it does not uses it for the result:
```python
>>> l[0] = 100
>>> s.subs(n, 5).doit().replace(Indexed, lambda i, j: Indexed(i, j) if i != d else l[j])
15
```
Is there a way to not add one extra element to the list and avoid the error?

**Comment by asmeurer** [comment]
Yes, as I noted on on the post, you really need to be indexing your sum from 0 to n - 1, since that is how Python does list indexing. If you do that, then your original `range(1, 6)` will give the answer you expect.

**Comment by artemrizhov** [comment]
Oh, I confused myself by trying to use identical indeces and values. I thought I've created a list starting from `l[1]=1` )))) Thank you for your patience!

**Comment by Upabjojr** [comment]
What about abolishing `IndexedBase` and just use `Symbol`? This would solve the problem of `Symbol("d")` and `IndexedBase(Symbol("d"))` being two different objects.

**Comment by asmeurer** [comment]
I'm not sure if that's a good idea. Anyway, I doubt it would affect this issue, which has to do with Indexed.

**Comment by Upabjojr** [comment]
> I'm not sure if that's a good idea. 

Why not? We can just move its `__getitem__` to `Expr` and/or `MatrixBase`. We could also abolish `MatrixElement` and just use `Indexed`.

**Comment by asmeurer** [comment]
We should open a new issue for it, but to me, it makes Symbol represent too many things.
