### ISSUE TITLE
diophantine. base_solution_linear returns solution 

### ISSUE THREAD

**Issue by YuriyTigiev** [sympy/sympy#12546]
Hello, 
The base_solution_linear returns a solution for case when equation doesn't have a solution 
Sample code
```
from sympy.solvers.diophantine import base_solution_linear  
from sympy.abc import t
a = 2
b = 4
c = -3 
f = base_solution_linear(a,b,c)
x = f[0]
y = f[1]
print(x,y)
```
Returns 
`2 2`

**Comment by Yerniyaz** [comment]
base_solution_linear(a,b,c) returns solution for the equation a=b*x+c*y. So, x=2 and y=2 is solution of the equation 2=4*x+(-3)*y. I think it returns rigth answer.

**Comment by YuriyTigiev** [comment]
Thank you. All works. It was my mistake with order of the coefficients.
