### ISSUE TITLE
Current state of multivariable stats distributions

### ISSUE THREAD

**Issue by hnykda** [sympy/sympy#12543]
Hi,

I am struggling to build a multivariate normal distribution. I found some hacky solutions on the web, but isn't there something right built in Sympy? There is some mention in [wiki](https://github.com/sympy/sympy/wiki/Random-Variables#multivariate-normal-random-variable), but I haven't found any code.

thanks

**Comment by oscarbenjamin** [comment]
You can pass lists or matrices for mu and sigma to Normal:
```julia
In [43]: from sympy.stats import Normal, density                                                                                                              

In [44]: X = Normal("X", [0, 0], [[1, 0], [0, 1]])                                                                                                            

In [45]: density(X)(z, y)                                                                                                                                     
Out[45]: 
    2    2
   y    z 
 - ── - ──
   2    2 
ℯ         
──────────
   2⋅π   
```
I'll close this issue for now.
