### ISSUE TITLE
problems in sum function 

### ISSUE THREAD

**Issue by RomanDerzh** [sympy/sympy#12547]
I have function to calculate he sum of integers. But my exception is not active and is not thrown when it is necessary. The code is not complete 
from sympy.solvers.diophantine import base_solution_sum_integers 
from sympy.abc import t
>>> try:
...     n = ["a", "b"]
...     int(n[2])
... except ValueError, IndexError:  # To catch both exceptions, right?
...     pass
...
Traceback (most recent call last):
  File "<stdin>", line 3, in <module>
IndexError: list index out of range

**Comment by adilbeknurmakov** [comment]
Problem here: you are specifying incorrectly parameters for exception block. In the above code, the IndexError exception is not being caught by the except statement; rather, the exception instead ends up being bound to a parameter named IndexError. To correct code you need an except statement is to specify the first parameter as a tuple containing all exceptions to be caught.

**Comment by adilbeknurmakov** [comment]
Try this one 
>>> try:
...     l = ["a", "b"]
...     int(l[2])
... except (ValueError, IndexError) as e:  
...     pass
...
>>>

**Comment by RomanDerzh** [comment]
oh, thanks a lot. Problem really was at exception parameters, Now everything works

**Comment by oscarbenjamin** [comment]
This isn't really a bug report for SymPy so I'm closing this.
