### ISSUE TITLE
unify return type for polygons

### ISSUE THREAD

**Issue by smichr** [sympy/sympy#12549]
```
>>> p
Polygon(Point2D(0, 0), Point2D(4, 0), Point2D(3, 2), Point2D(1, 1))
>>> type(p.sides),type(p.vertices)
(<type 'list'>, <type 'tuple'>)
```

It would be nice to have the same type in both cases. Having them be lists would make it easy to process the elements in a `while container:`-loop.

**Comment by Yerniyaz** [comment]
let me get this isue

**Comment by Yerniyaz** [comment]
I fixed it. Pull request #12551

**Comment by parsoyaarihant** [comment]
I think this issue should be closed.

**Comment by smichr** [comment]
Thanks; closed.
