### ISSUE TITLE
Polynomial function 

### ISSUE THREAD

**Issue by jady707** [sympy/sympy#12552]
Hello, from Australia. I want to try myself in writing polynomial function. But don't have deep knowledge in python syntax. For example, function negate(p) that negates the polynomial represented by the list of its coeffeicients p and returns a new polynomial (represented as a list). In other words, write a function that makes the list of numbers negative. How this will look like?

**Comment by Yerniyaz** [comment]
something like this:

def negate(p):    
    for i in range(len(p)):
        p[i]=(-1)*p[i]
    return p

**Comment by adilbeknurmakov** [comment]
Alternatively you can  use  numpy.poly1d and numpy.polymul, where the coefficients are a0*x2 + a1*x + a2.

For example, to represent 3*x**2 + 2*x + 1
def negl_polynomial(p,x):
    return sum((a*x**i for i,a in enumerate(p)))

def multiply_by_one_term(p, a, k):
    return [0]*k + [a*i for i in p]

**Comment by jady707** [comment]
Thank, you guys. Both ways work))) But second I guess is more flexible

**Comment by siefkenj** [comment]
Is this bug ready to close?

**Comment by oscarbenjamin** [comment]
This isn't really a bug report so I'll close it.
