### ISSUE TITLE
Integration fails unless I do it a step at a time

### ISSUE THREAD

**Issue by stevemolloy** [sympy/sympy#12554]
I am working with Python3 in a Jupyter notebook.

My setup code:
```
import sympy as sp
from sympy.abc import v, t, lamda, gamma, z, N, R, m, phi, r, c
sp.init_printing()

Dlamda = sp.Indexed('D', lamda)
zlamda = sp.Indexed('z', 'c')
r0 = sp.Indexed('r', 0)
phi0 = sp.Indexed('b', 'a')

g = (2*sp.pi*R) / (lamda*gamma)
N = sp.Piecewise((2, sp.Eq(m, 0)), (1, True))

funcToBeSummed = (1/(sp.pi*N*R)) * (sp.besseli(m, g*r0/R) / sp.besseli(m, g)) * sp.cos(m*(phi-phi0))

sigma = -Dlamda * sp.cos(((2*sp.pi)/lamda) * (v*t + c - z)) * sp.Sum(funcToBeSummed, (m, 0, sp.oo))
```

Then I try to integrate over `phi`.  This step fails with `TypeError: Invalid NaN comparison
`.
```
sp.integrate(sigma, phi)
```

To make it work, I go back to the same Jupyter cell, and edit it as follows:
```
sp.integrate(-Dlamda * sp.cos(((2*sp.pi)/lamda) * (v*t + c - z)), phi)
```
This works.

Then this **which also fails**,
```
sp.integrate(sp.Sum(funcToBeSummed, (m, 0, sp.oo)), phi)
```

Then,
```
sp.integrate(-Dlamda * sp.Sum(funcToBeSummed, (m, 0, sp.oo)), phi)
```
This works.

Then I try the original integration again.
```
sp.integrate(sigma, phi)
```
**And it works!!**

It must be caching some intermediate result somewhere, but this definitely doesn't seem like expected behaviour.  Am I doing something wrong, or have I uncovered something unexpected?

**Comment by stevemolloy** [comment]
Actually, that whole dance isn't necessary.  Just continually execute `sp.integrate(sigma, phi)` until it works.  Three or four times does the trick.

**Comment by oscarbenjamin** [comment]
I'm unable to reproduce this on current master. Is this still an issue for you?
