### ISSUE TITLE
solveset(log(x) < 1, x, domain=S.Reals) wrong answer

### ISSUE THREAD

**Issue by Xiaofei-Luo** [sympy/sympy#12559]
`solveset(log(x) < 1, x, domain=S.Reals)` gives `(-oo, E)` instead of `(0, E)`. It seems that sympy fails to consider function definition field when solving equations containing logarithmic functions.

**Comment by maurogaravello** [comment]
In the last version of sympy, `solveset(log(x) < 1, x, domain=S.Reals)` returns `Interval.open(0, E)`.
Probably some PR corrected the behavior.
