### ISSUE TITLE
solveset(x==0,x,S.Reals) returns EmptySet()

### ISSUE THREAD

**Issue by apalmer1377** [sympy/sympy#12563]
Running `solveset(x==0,x,S.Reals)` returns EmptySet().  However, `solveset(x>=0,x,S.Reals)` returns the proper value of `Interval(0,oo)`.

**Comment by smichr** [comment]
`x==0` automatically converts to False and solveset(False, x, S.Reals) is the empty set. If you send `Eq(x, 0)` -- the unevaluated equality -- you will get {0}.
