### ISSUE TITLE
problem with polygamma or im

### ISSUE THREAD

**Issue by mvanda** [sympy/sympy#12569]
N(polygamma(0,I))
yields a correct result 
0.094650320622477 + 2.07667404746858*I
but
im(polygamma(0,I))
yields zero.

**Comment by jksuom** [comment]
`polygamma` is real for real arguments. Hence the imaginary part is zero.
```
>>> N(polygamma(0, 1))
-0.577215664901533
>>> im(polygamma(0, 1))
0
```

**Comment by mvanda** [comment]
Please note that the second argument is I (imaginary unit) not 1 (one).

**Comment by jksuom** [comment]
I see, now that you point that out. (My eyesight is not what it used to be..)

**Comment by jksuom** [comment]
It seems that the error results from this:
```
>>> polygamma(0, I).is_real
True
```
There a bug in `polygamma._eval_is_real`. It does not check the proper argument.
