### ISSUE TITLE
problem with parse_expr and Abs

### ISSUE THREAD

**Issue by tgrassi** [sympy/sympy#12572]
Hi all,

I found a problem when using `parse_expr` and `Abs`.
In particular, when I do this
```
from sympy import Abs,Symbol,solve
from sympy.parsing.sympy_parser import parse_expr

x = Symbol("x",real=True)
expr = Abs(x)-1
print solve(expr,x)
```
I correctly get
```
>>> [-1,1]
```
However, when I try to do the same, but using `parse_expr` 
```
expr = parse_expr("Abs(x)-1")
print solve(expr,x)
```
I get an empty list
```
>>> []
```
This happens in ver 0.7.6.1 and 1.0.1.dev0

Thanks in advance for your help.

**Comment by debugger22** [comment]
There's a difference between both cases. In first case, the `x` is real where as in second it's unknown.

**Comment by debugger22** [comment]
Feel free to close this issue.

**Comment by tgrassi** [comment]
Hi,
thanks for the prompt answer!
The second example is a continuation of the first, so `x` is already defined real by `x = Symbol("x",real=True)`.
In fact, if I comment the line `x = Symbol("x",real=True)` I get an error when using `parse_expr`, i.e. `NameError: name 'x' is not defined`, so `x` seems to be defined there.
If the "real" is lost, how can I define `x` as real in an expression parsed by `parse_expr`?

**Comment by debugger22** [comment]
`x` doesn't need to be pre-defined in order to be used within `parse_expr`.

```python
sudhanshu:MacBook-Pro:~/workspace/sympy:master
$ python
Python 3.5.1 (default, Apr 18 2016, 11:46:32)
[GCC 4.2.1 Compatible Apple LLVM 7.3.0 (clang-703.0.29)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from sympy.parsing.sympy_parser import parse_expr
>>> parse_expr("Abs(x)-1")
Abs(x) - 1
>>> list(_.free_symbols)[0].is_real is None
True
```

**Comment by tgrassi** [comment]
OK, thanks for the explanation.
I moved  to `solveset` using `domain=S.Reals` with the parsed expression and it works.

Thanks for maintaining this code!
