### ISSUE TITLE
Simplify constant coefficients

### ISSUE THREAD

**Issue by djsegal** [sympy/sympy#12574]
I have something like:

```
57459.1742773058*T_k/(-175329.0*sigma_v_hat + 196349.540849362)
```

And the coeffs (i.e. `57459.1742773058`) only grow with further solves.

Is there a way to make these scale/simplify towards `O(1)` values?

**Comment by smichr** [comment]
Perhaps replace them with `round(foo)` or `foo.n(nsig)`? Why do you want to replace them? Can you show more of the problem you are working on and how these are growing?

**Comment by oscarbenjamin** [comment]
@djsegal can you give more explanation?

Without that this issue is not useful so I will close it soon.
