### ISSUE TITLE
Taylor expansion wrong (likely because of wrong substitution at point of evaluation?)

### ISSUE THREAD

**Issue by xaverm** [sympy/sympy#12578]
`import sympy as sp`
Then let 
`xp = ((sp.Integer(1)-((u+sp.Integer(1)/u)/sp.Integer(2))**(-sp.Integer(4)))**sp.Rational(1,8))`
i.e. `xp = (1 - 1/(u/2 - 1/(2*u))**4)**(1/8)` ;)
then do
`s=sp.series(xp,u,0,17)`
we get 
`1 - 2*u**4 - 8*u**6 - 34*u**8 - 24*u**10 + 118*u**12 - 672*u**14 - 686*u**16 + O(u**17)`
**This is wrong**, starting with the coefficient of order 10. 
The proper series reads
`1 - 2*u**4 - 8*u**6 - 34*u**8 - 152*u**10 - 714*u**12 - 3472*u**14 - 17318*u**16 + ...`

To get some feeling, as to where the error stems from we can do the 10th order derivative 
`d10=sp.diff(xp,u,10)`
[Actually it takes very long on a core i7 machine to do this - even if compared to ancient CAS like Maxima(, let alone Mathematica or Maple) - **why?**]
Anyway `d10` is some trivial, but very lengthy expression. First we can do some numerical test, e.g.
```
In []: d10.subs(u,.1)
Out[]: -4202924629.88583
```
One can check that is correct. Now we do the limit onto the expansion point (which again takes a lot of time)
```
In []: sp.limit(d10, u, 0, dir="+")
Out[]: -oo
```
**This is wrong**, actually we should get `-551577600`. Next we do some simplification on `d10`
```
d10t=sp.together(d10)
(nm,dn)=sp.fraction(d10t)
nmx=sp.expand(nm)
d10ts=nmx/dn
```
 `d10ts` looks much nicer as compared to `d10` ... but its the same. So let's do the limit onto the expansion point once again
```
In []: sp.limit(d10ts, u, 0, dir="+")
Out[]: -551577600
```
OMG ... two different ways of writing the same algebraic expression (10th order derivative) yields two different limits at the expansion point. I.e. the reason for the wrong 10th order coefficient in the expansion is likely due to yet another wrong limiting value, evaluated internally at the expansion point(?).

N.b.: `-551577600/sp.factorial(10) =  -152` as it should be for the proper expansion.

xaverm

**Comment by jksuom** [comment]
Probably related to https://github.com/sympy/sympy/issues/10503, https://github.com/sympy/sympy/issues/9549 and some other similar issues.
