### ISSUE TITLE
Wrong measurement for one qubit state.

### ISSUE THREAD

**Issue by ghost** [sympy/sympy#12585]
Hi, sympy developers.

    measure_all(qapply(Qubit('0')))

returns [(|01>, 1)] but should be [(|0>, 1)]

best, Vladimir.

**Comment by jksuom** [comment]
It seems that if the number of qubits is one, the argument `nqubits` on [this line](https://github.com/sympy/sympy/blob/master/sympy/physics/quantum/qubit.py#L544) will be interpreted as an extra qubit. There should be only `IntQubit(i)` with no `nqubits` argument in case `nqubits == 1`.
