### ISSUE TITLE
Wrong test in Basic,is_comparable for imaginary part

### ISSUE THREAD

**Issue by skirpichev** [sympy/sympy#12589]
Example

```python
In [1]: sin(1)**2 + cos(1)**2 - 1
Out[1]: 
        2         2   
-1 + cos (1) + sin (1)

In [2]: _1*I
Out[2]: 
  ⎛        2         2   ⎞
ⅈ⋅⎝-1 + cos (1) + sin (1)⎠

In [3]: _2.is_comparable
Out[3]: False

In [4]: simplify(_2).is_comparable
Out[4]: True
```

**Comment by mvanda** [comment]
According to documentation, "false" result does not mean that a quantity cannot be converted to comparable, e.g. by simplification.

**Comment by skirpichev** [comment]
Oh, it's now a feature.  Sorry.

Unfortunately, your codebase still use is_comparable to check if number is not comparable with 0.  Notable example is ``solve_univariate_inequality``.
