### ISSUE TITLE
SymPy can't compare real numbers?

### ISSUE THREAD

**Issue by mehrdadn** [sympy/sympy#12583]
The code

	from sympy import sqrt
	v = sqrt(2)
	u = sqrt(v) + 2/sqrt(10 - 8/sqrt(2 - v) + 4*v*(1/sqrt(2 - v) - 1))
	if u >= 0: print("yes")

should not result in

	Traceback (most recent call last):
	  File "<pyshell#4>", line 1, in <module>
	    if u >= 0: print("yes")
	  File "sympy\sympy\core\relational.py", line 195, in __nonzero__
	    raise TypeError("cannot determine truth value of Relational")
	TypeError: cannot determine truth value of Relational

**Comment by jksuom** [comment]
Comparisons of real algebraic numbers have not yet been implemented in SymPy. It is currently necessary to pass over to floating point versions: `if N(u) >= 0: print('yes')`.

**Comment by mvanda** [comment]
My output from your code is
yes
using
python version: 2.7.8
sympy version: 0.7.5

**Comment by mehrdadn** [comment]
I'm on SymPy 1.0.1.dev.

**Comment by smichr** [comment]
> It is currently necessary to pass over to floating point versions: if N(u) >= 0: print('yes').

It is numerically inadvisable to do so in general since the evaluation may result in a number without precision about which no conclusion should be drawn. Here is another option that perhaps works because it forces an (careful) numerical evaluation in the assumption system:

```
>>> (u+Dummy(positive=True)).is_positive
True
```

**Comment by asmeurer** [comment]
These numbers without precision should be raising errors themselves when in comparisons, and preferably the precision should be increased automatically.

**Comment by mvanda** [comment]
Hi all,

I do not understand the discussion on precision here. These numbers v and u are exact and the question is if u>=0 can be decided or not by some simplification and logical steps. Manually (and exactly) it can be shown than u>0 is true. So ver. 0.7.5 works and 1.0 does not?

**Comment by jksuom** [comment]
It is true that `u >= 0` can be decided by logical steps since `u` is a real algebraic number, but that has not been implemented in SymPy. Before that is done, passing over to floating point numbers is the best workaround, and then one has to take care of sufficient precision. (In this particular case that is not a problem since `u` is not close to `0`.) That functionality did not exist in v. 0.7.5 either, so if it did work, there must be some other explanation.

**Comment by mehrdadn** [comment]
Note that it _does_ seem to have been implemented to some extent (try simplifying the expression, it'll figure it out), so the user doesn't expect it to be considered unimplemented, which makes it all the more unexpected and confusing. If it wasn't implemented at all, it would be spotted in the beginning and not pop up as a bug after release.

**Comment by smichr** [comment]
This appears to be working in master.

**Comment by mehrdadn** [comment]
I guess I'll close this as it seems to have been resolved?
