### ISSUE TITLE
Sympy can't simplify this modular expression

### ISSUE THREAD

**Issue by ychen306** [sympy/sympy#12592]
Sympy can simplify `(i*n + j%n) % n` into `j%n`. 
But `((j % n)*n + j%n) % n` can't be simplified.

**Comment by oscarbenjamin** [comment]
On current master I get:
```julia
In [10]: simplify((i*n + j%n) % n)                                                                                                                            
Out[10]: j mod n
```
so I think this is fixed...

**Comment by smichr** [comment]
Addressed, I believe, by [this PR](https://github.com/sympy/sympy/pull/15599).
