### ISSUE TITLE
make ray intersection more robust

### ISSUE THREAD

**Issue by smichr** [sympy/sympy#12598]
The intersection of two rays is being rejected:

```
def bisectors(p, prec=None):
    """Return angle bisectors of a polygon. If prec is given
    then approximate the point defining the ray to that precision.

    The distance between the points defining the bisector ray is 1.

    Examples
    ========

    >>> from sympy import Polygon, Point
    >>> p = Polygon(Point(0, 0), Point(2, 0), Point(1, 1), Point(0, 3)
    >>> for k, v in bisectors(p,2).items():
    ...     print (k, v)
    ...
    (Point2D(2, 0), Ray2D(Point2D(2, 0), Point2D(1.1, 0.38)))
    (Point2D(0, 3), Ray2D(Point2D(0, 3), Point2D(0.23, 2.0)))
    (Point2D(0, 0), Ray2D(Point2D(0, 0), Point2D(0.71, 0.71)))
    (Point2D(1, 1), Ray2D(Point2D(1, 1), Point2D(0.19, 0.42)))
    """
    b = {}
    pts = list(p.args)
    pts.append(pts[0])  # close it
    for v, a in p.angles.items():
        i = pts.index(v)
        ray = Ray(pts[i], pts[i + 1]).rotate(a/2, v)
        # normalize so distance from p1 to p2 is 1
        dir = ray.direction
        ray = Ray(ray.p1, ray.p1 + dir/dir.distance((0,0)))
        if prec is not None:
            ray = Ray(ray.p1, ray.p2.n(prec))
        b[v] = ray
    return b

p=Polygon((0,0),(3,0),(4,10),(0,1))
b = bisectors(p, 2)
for s in p.sides:
 r1, r2 = [b[i] for i in s.args]
 s.args, r1.intersection(r2), Line(r1).intersection(Line(r2))
```
Output is:
```
((Point2D(0, 0), Point2D(3, 0)), [Point2D(1.6, 1.6)], [Point2D(1.6, 1.6)])
((Point2D(3, 0), Point2D(4, 10)), [], [Point2D(1.7, 1.4)])
((Point2D(0, 1), Point2D(4, 10)), [], [Point2D(1.5, 0.68)])
((Point2D(0, 0), Point2D(0, 1)), [], [Point2D(0.82, 0.82)])
```

(The last 3 should have given ray intersection identical to the Line-wrapped ray intersections.)

**Comment by parsoyaarihant** [comment]
I am able to get the intersection locally:
``` python
>>> from sympy.geometry import Line, Ray
>>> from sympy import Point
>>> r1 = Ray(Point(4, 10), Point(3.7, 9))
>>> r2 = Ray(Point(0, 1), Point(0.98, 0.79))
>>> r1.intersection(r2)
[Point2D(182/149, 110/149)]
```

**Comment by smichr** [comment]
I noticed that after posting...the issue is a floating point one where the intersection is not detected to be exactly on both of the original rays. (The floating pt values come from a more complicated expression which I did not show.) The solution, I think, is to find a way to confirm that the rays are going to intersect and then to accept the solution of the lines without testing to see if the result is on the orginal rays.

**Comment by parsoyaarihant** [comment]
Can you post the expression which returns floating point?

**Comment by smichr** [comment]
It even fails without evaluation:

```
>>> p=Polygon((0,0),(3,0),(4,10),(0,1))
>>> a=p.angles
>>> r1=Ray((0,0),angle=a[Point(0,0)]/2)
>>> r2=Ray((0,1),angle=a[Point(0,1)]/2)
>>> r1.intersection(r2)
[]
```

**Comment by parsoyaarihant** [comment]
In the above code:
```python
r1 = Ray(Point(0, 0), Point(1, 1))
r2 = Ray(Point(0, 1), Point(1, 1 + tan(acos(-9*sqrt(97)/97)/2)))
```

or `r2 = Ray(Point(0, 1), Point(1, 5.712214450449026))`

The answer is correct since the two lines does not intersect.

**Comment by smichr** [comment]
OK, here's the original and I can't confirm it here because `live` is timing out:

```
>>> p=Polygon((0,0),(3,0),(4,10),(0,1))
>>> a=p.angles
>>> v=Point(4,10)
>>> a = a[v]
>>> r2 = Ray(v, Point(0,1)).rotate(a/2, v)
>>> assert r1.intersection(r2) # ok
>>> r1.intersection(Ray(v,r2.p2.n(2))  # but does THIS give []?
```

**Comment by smichr** [comment]
If this does prove to be a legitimate problem then perhaps the workaround is to check that both variables in arbitrary_point for both rays is positive, e.g. if `r1.arbitrary_point(t) = Point(t,t)` and `r2.arbitrary_point(u) = Point(1-u,u)` then the intersection is when `t=1-u` and `t=u` which gives `(t,u)=(1/2,1/2)`: both are positive so the intersection is valid regardless of whether it can be proved to be on the rays or not. So the idea is that it might be easier to prove that the variables for the arbitrary points are positive than it is to prove that they lie on the original rays.

**Comment by parsoyaarihant** [comment]
What is `r1` in `>>> assert r1.intersection(r2) # ok`? Is it the same as the one in previous code?
``` python
>>> r1
Ray(Point2D(0, 0), Point2D(1, 1))
```

**Comment by smichr** [comment]
yes. I have edited it show that.

**Comment by parsoyaarihant** [comment]
It does not return `[]`:

```python
>>> from sympy import *
>>> p=Polygon((0,0),(3,0),(4,10),(0,1))
>>> a=p.angles
>>> v=Point(4,10)
>>> a = a[v]
>>> r2 = Ray(v, Point(0,1)).rotate(a/2, v)
>>> r1 = Ray(Point2D(0, 0), Point2D(1, 1))
>>> r1.intersection(Ray(v,r2.p2.n(2)))
[Point2D(7200/3917, 7200/3917)]
```

**Comment by smichr** [comment]
You've been a trooper. I posted the full example in the OP. Let's see how your results with that input fare.

**Comment by smichr** [comment]
This shows a way to address the issues of #4748
