### ISSUE TITLE
Sympy integration

### ISSUE THREAD

**Issue by coderofgames** [sympy/sympy#12609]
Hi, I don't understand the algorithm used for integration, (Meijer G-funcs??)
I have problems with some integrals, the example as shown below isn't what is expected,
I have a suggestion for an intelligent algorithm (view in ipython):

example<br>
$$ \int \frac{x}{(x^2 + y^2 + z^2)^{3/2}} dx $$
<br>numerator: $u = x$
<br>denominator: $ v = (x^2 + y^2 + z^2)^{3/2} $
<br>if denominator is a function of a function, $ v = G(x) $
<br>find $\frac{dG}{dx}$ ans $2x$ so $dx = \frac{dG}{2x}$
<br>then the answer is 
$ \int \frac{dG}{G^{3/2}} = 1/G^{1/2} $
<br>check
<br>Differentiate $\frac{df}{dx} = \frac{d \frac{1}{G^{1/2}}}{dx} $
$\frac{df}{dG}\frac{dG}{dx} =  -(\frac{1}{2})G^{-3/2}2x $

**Comment by coderofgames** [comment]
The Meijer G-function idea is very advanced, so I can't contribute without a tutorial. I would suggest a modification that uses simpler styles with lookup tables - taking partial fractions etc - a search tree - then if this fails the algorithm could resort to Meijer G-functions (does it do that already?).

**Comment by parsoyaarihant** [comment]
Hi, I think you should discuss this on Gitter chat instead:

[https://gitter.im/sympy/sympy](https://gitter.im/sympy/sympy)

**Comment by coderofgames** [comment]
I thanks, are you supposed to create a room or post in the room that appears when you log in ?

**Comment by parsoyaarihant** [comment]
Post in the room that appears.

**Comment by coderofgames** [comment]
Issue resolved, did not import division or use S() notation for the exponent ...
Thanks for all the help on the channel. Ciao
