### ISSUE TITLE
kinematic_equations should return a zero vector if the speeds are all zero

### ISSUE THREAD

**Issue by moorepants** [sympy/sympy#12600]
This is currently the behavior:

```
moorepants@garuda:sympy(master)$ ipython --pdb
Python 3.5.3 |Continuum Analytics, Inc.| (default, Mar  6 2017, 11:58:13) 
Type 'copyright', 'credits' or 'license' for more information
IPython 6.0.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import sympy as sm

In [2]: import sympy.physics.mechanics as me

In [3]: me.kinematic_equations((0, 0, 0), (sm.pi, sm.pi / 2, 0), 'body', '132')
Out[3]: [nan, 0, nan]
```

This expected output should be:

```
[0, 0, 0]
```

**Comment by thechargedneutron** [comment]
Hello Sir, I am very much interested in contributing, but am new to open source. Where can I find this particular function kinematic_equation(), I opened sympy/physics/mechanics but could not find the function in the files. Can you please help me with this? I read that the code is present in sympy/core but could not find this

**Comment by jksuom** [comment]
It is defined in sympy/physics/vector/functions.py.

**Comment by yajnab** [comment]
q1d - (w1 * c3 + w3 * s3)/ c2 
This is what is returned
c2 is a function dealing with cos(q2)
q2 being Pi/2 makes c2 to become 0
x/ 0 is infinite which is getting to NaN

**Comment by moorepants** [comment]
My line of thought was that if the speeds are all zero it supersedes any result due to the definition of coordinates that may result in a singularity. From a physical, instead of mathematical, perspective I think that makes sense.

**Comment by yajnab** [comment]
@moorepants : Yes! But getting that mathematically will force us to equate infinity with 0. Binding a special case will look like a history text book rather than a mathematical equation.
Lets see If I can do anything

**Comment by moorepants** [comment]
The function "kinematic_equations" is not some mathematical construct in SymPy. It's purpose is to provide the correct angular velocity given a variety of rotation types. If you tell the function that angular velocity is zero, then it should return the same, regardless of any mathematical rules.

Here is a little more context:

```
moorepants@garuda:mae297(master)$ ipython
Python 3.5.3 |Continuum Analytics, Inc.| (default, Mar  6 2017, 11:58:13) 
Type 'copyright', 'credits' or 'license' for more information
IPython 6.0.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import sympy as sm

In [2]: import sympy.physics.mechanics as me

In [3]: N = me.ReferenceFrame('N')

In [4]: A = N.orientnew('A', 'body', (sm.pi, sm.pi / 2, 0), '132')

In [5]: A.dcm(N)
Out[5]: 
Matrix([
[ 0, -1,  0],
[-1,  0,  0],
[ 0,  0, -1]])

In [6]: A.ang_vel_in(N)
Out[6]: ---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/home/moorepants/miniconda3/lib/python3.5/site-packages/IPython/core/formatters.py in __call__(self, obj)
    664                 type_pprinters=self.type_printers,
    665                 deferred_pprinters=self.deferred_printers)
--> 666             printer.pretty(obj)
    667             printer.flush()
    668             return stream.getvalue()

/home/moorepants/miniconda3/lib/python3.5/site-packages/IPython/lib/pretty.py in pretty(self, obj)
    379                             if callable(meth):
    380                                 return meth(obj, self, cycle)
--> 381             return _default_pprint(obj, self, cycle)
    382         finally:
    383             self.end_group()

/home/moorepants/miniconda3/lib/python3.5/site-packages/IPython/lib/pretty.py in _default_pprint(obj, p, cycle)
    499     if _safe_getattr(klass, '__repr__', None) not in _baseclass_reprs:
    500         # A user-provided repr. Find newlines and replace them with p.break_()
--> 501         _repr_pprint(obj, p, cycle)
    502         return
    503     p.begin_group(1, '<')

/home/moorepants/miniconda3/lib/python3.5/site-packages/IPython/lib/pretty.py in _repr_pprint(obj, p, cycle)
    697     """A pprint that just redirects to the normal repr function."""
    698     # Find newlines and replace them with p.break_()
--> 699     output = repr(obj)
    700     for idx,output_line in enumerate(output.splitlines()):
    701         if idx:

/home/moorepants/miniconda3/lib/python3.5/site-packages/sympy/physics/vector/vector.py in __str__(self, printer)
    351             for j in 0, 1, 2:
    352                 # if the coef of the basis vector is 1, we skip the 1
--> 353                 if ar[i][0][j] == 1:
    354                     ol.append(' + ' + ar[i][1].str_vecs[j])
    355                 # if the coef of the basis vector is -1, we skip the 1

TypeError: 'NaN' object does not support indexing
```

The automatic calculation of angular velocity relies on `kinematic_equations`. This should simply return a zero vector for any non-time varying orientation. The error could be fixed in the `.orient` method or maybe it is appropriate for `kinematic_equations` to be aware of this.

**Comment by abhigyank** [comment]
Is this issue open?

**Comment by JameerBabu** [comment]
Is this a closed issue or an open issue ? Please confirm . I am really confused as it is shown as open in list and closed when we look at it with different issue numbers.

**Comment by moorepants** [comment]
It is an open issue. @smichr worked on it here: https://github.com/sympy/sympy/pull/12698 but I didn't think his solution was correct. These equations have to be solved explicitly for the derivative terms and rewriting the equations to avoid zeros on the denominator only postpones this issue.

**Comment by JameerBabu** [comment]
I tried on this issue to fix. Someone please review it .

**Comment by rahilhastu** [comment]
I cannot get what has to be done here? can u please make it clear @moorepants .Does this issue needs a PR or there already exists one?

**Comment by smichr** [comment]
> I didn't think his solution was correct

I'm not sure you looked at the final modifications which didn't change the kinematic equations. I committed the quick exit for all speeds equal 0 but the issue of what to do in the certain cases still exists. Tests for those cases were added in the unmerged issue.

**Comment by moorepants** [comment]
I will look at it again.

**Comment by moorepants** [comment]
Just looking at this, makes me think that maybe `kinematic_equations` should be left as is and the zero velocity should be correctly handled in `ang_vel_in()`, i.e. `kinematic_equations` should not be called if the rotation angles are not functions of time.
