### ISSUE TITLE
Cannot solve: integrate(3*exp(3*x - 2*y)*sin(2*x - 3*y),y)

### ISSUE THREAD

**Issue by jankoslavic** [sympy/sympy#12614]
The solution should be:
`3/13 exp**(3 x - 2 y) * (3*cos(2*x - 3*y) - 2*sin(2*x - 3*y))`

why do I get: CoercionFailed?

**Comment by jamesharrop** [comment]
Hello, I was trying to reproduce this error. I wonder if this has been fixed already?

The Conda version of Sympy gives CoercionFailed error message. However the latest GitHub version gives as output
`
-6*exp(3*x)*exp(-2*y)*sin(2*x` - 3*y)/13 + 9*exp(3*x)*exp(-2*y)*cos(2*x - 3*y)/13
`
which appears to reduce to the same solution you give.

**Comment by jankoslavic** [comment]
@jamesharrop thank you for the check. I tried the latest conda version and the github 1.0.1.dev0 version and with both I get now:
TypeError: _eval_power() missing 1 required positional argument: 'other'

Here is my code:
```
x, y = symbols('x, y')
integrate(3/13*exp**(3*x - 2*y) * (3*cos(2*x - 3*y) - 2*sin(2*x - 3*y)), y)
```

**Comment by maurogaravello** [comment]
As **jamesharrop** observed, the latest GitHub version gives the correct output.
@jankoslavic The code in your last comment does not reflect the original issue. However your code gives such an error, since `exp**(3*x - 2*y)` is not correct. Use `exp(3*x - 2*y)`.

**Comment by jankoslavic** [comment]
Thank you! I was fast with the snippet which is the result:)

I am confirming, the latest version of sympy works fine!
