### ISSUE TITLE
Something strange with plot of factor(x**4/2 + 5*x**3/12 - x**2/3)

### ISSUE THREAD

**Issue by simone-pizzolato** [sympy/sympy#12627]
Hi folks,
the plot is strange, it is always near zero in rage [-1.4,0.9].
Take a look at attached files
![wolframalpha](https://cloud.githubusercontent.com/assets/22774070/25858843/117ccc82-34dd-11e7-9d04-53d522047d7e.PNG)
![gammasympy](https://cloud.githubusercontent.com/assets/22774070/25858842/117a1910-34dd-11e7-8d7a-a9342a9dc880.PNG)

Simone

**Comment by asmeurer** [comment]
It seems to be a bad choice for the Y limits. Compare the range of Y values for Wolfram vs. SymPy Live. 

The plotting at SymPy Live is not part of SymPy itself, so it should be reported at https://github.com/sympy/sympy-live.

**Comment by asmeurer** [comment]
Sorry, this is SymPy Gamma, not SymPy Live. https://github.com/sympy/sympy_gamma

**Comment by simone-pizzolato** [comment]
Ok! Thanks.
I have opened a thread on SymPy Live.

**Comment by smichr** [comment]
opened elsewhere so closed here.
