### ISSUE TITLE
infinite recursion in periodicity

### ISSUE THREAD

**Issue by smichr** [sympy/sympy#12620]
I get an infinite recursion when trying to solve

```
periodicity(abs(x**2 - 3*x), x)
```

**Comment by kshitij10496** [comment]
This bug arises due to the fact that:
 
    In []: f = abs(x**2 - 3*x)
    In []: f_s = simplify(f)
    In []: g = compogen(decompogen(f_s), x) 
    In []: g == f
    Out[]: False

I propose that we add a conditional for checking equality with both the original function and the simplified expression to reflect this behaviour of `compogen`, `decompogen` and `simplify`.
