### ISSUE TITLE
implement Piecewise rewriting for Min and Max

### ISSUE THREAD

**Issue by smichr** [sympy/sympy#12639]
This was mention in #10158. I am just puttng this here as a separate issue.

```
>> Max(a, b).rewrite(Piecewise)
Piecewise((a, a>b), (b, True))
```

**Comment by Yathartha22** [comment]
@smichr I would like to take this issue.
I guess [this](http://docs.sympy.org/latest/_modules/sympy/core/basic.html#Basic.rewrite) will the starting point.
Could you provide me with some headstarts?

**Comment by smichr** [comment]
Have a look at ITE's rewrite method to convert ITE to Piecewise -- just search boolalg.py for Piecewise and you will find it.
