### ISSUE TITLE
collapse Min(a, b, Max(a, y)) to Min(a, b)

### ISSUE THREAD

**Issue by smichr** [sympy/sympy#12638]
I'm not sure where the best place to put this since MinMax are handled in the same place. It could go in the `__new__` definition for MinMaxBase in sympy/functions/elementary/miscellaneous.py around line 328. Or it could be defined as an `_eval_simplify` routine. The basic idea is (as for And/Or) that given f and g (which is the opposite of f) if g contains any args that f contains then g is redundant: `f(x, y, g(x, z)) -> f(x, y)`.

Simplifications
-----
- absorption: Min(x, y, Max(x, z), Max(w, z)) -> Min(x, y, Max(w, z)); any opposite function arg (Max in this case) with any arg in common with the args of the parent function (Min in this case):
- special case absorption: `Min(1, Max(4, x), y) -> Min(1, y)`: if any arg in Max is known to be greater than or equal to an arg in Min, then the Max arg is redundant.
- distribution: `Min(x, Max(y, z), Max(y, w), Max(u, v)) -> Min(x, Max(y, Min(w, z)), Max(u, v))`, perhaps only useful if all the internal Max args have a common factor and there are no other non-Max args, e.g. `Min(Max(y, z), Max(y, x)) -> Min(Max(y, Min(x, z))) -> Max(y, Min(x, z))`

[notes from discussion with @jksuom in #12587]

**Comment by asmeurer** [comment]
It should just be `foo`. If `foo >= y` then `Min(foo, Max(foo, y)) == Min(foo, foo) == foo`, and if `foo <= y` then `Min(foo, Max(foo, y) == Min(foo, y) == foo`. 

This is the [absorption law](https://en.wikipedia.org/wiki/Lattice_(order)#General_lattice), and should probably be implemented on `LatticeOp`.

**Comment by asmeurer** [comment]
Apparently LatticeOp isn't a very good superclass for a lattice, as it has no references to meet and join. Ideally, that would abstracted and the subclasses would identify themselves as the corresponding meet (And, Min) and join (Or, Max).

**Comment by smichr** [comment]
> It should just be foo

Or, rather, `Min(foo)` where `foo` might be a sequence of elements, e.g `Min(1, 2, Max(1, 2, 3)) -> Min(1, 2)`. OP and title modified accordingly.

**Comment by smichr** [comment]
@asmeurer , I wonder if this should be added as a quick simplifying test in `simplify_logic` or if it should be done at instantiation of And/Or. I know we tend to not favor automatic simplification but is there a reason that `f(x, y, g(x, z))` should not automatically give `f(x, y)` where `{f:g}` is `{And: Or, Max: Min, Min: Max, Or: And}`?

**Comment by asmeurer** [comment]
My main concern would be with And/Or, if someone wants to represent absorption without the simplification happening. Min/Max you probably just want to simplify as much as possible. 

But I suspect for the most part, you would want this to happen, so perhaps an automatic simplification is in order. It's similar in nature to the other automatic simplifications that already happen.

**Comment by asmeurer** [comment]
You need to fix LatticeOp first. Probably it's as simple as adding

```
class LatticeOp:
    ...
    @property
    def meet(self):
        raise NotImplementedError
    @property
    def join(self):
        raise NotImplementedError
```

and then subclasses would define

```
class And:
    ...
    @property
    def meet(self):
        return self.__class__
    @property
    def join(self):
        return Or

class Or:
    ...
    @property
    def meet(self):
        return And
    @property
    def join(self):
        return self.__class__
```

**Comment by smichr** [comment]
Whoever understands how meet and join should work to affect the simplification should tackle this. I don't understand it yet. I've also added, to the OP, a couple of other simplifications that can somehow be added.

**Comment by asmeurer** [comment]
Would still like to see some refactoring in the base classes. Maybe we should open a new issue.
