### ISSUE TITLE
Sympy plot using log

### ISSUE THREAD

**Issue by alabrazi** [sympy/sympy#12635]
The code below work with cos(t) but not with ln(t) or log(t) -> TypeError: can't convert expression to float
```
from sympy import *
########################################################################
P,t,phi,r,lambda_e, lambda_tot\
= symbols('P,t,phi,r,lambda_e, lambda_tot')
plot((2.5-(t/8760), (t, 0, 8760)), (-1348.8*ln(t)+12692, (t, 0, 8760)))
```

**Comment by jksuom** [comment]
It looks like `t = 0`, where the logarithm is not well defined, is included in the computation. This is what I get:
```
>>> float(ln(0))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "sympy/core/expr.py", line 238, in __float__
    raise TypeError("can't convert complex to float")
TypeError: can't convert complex to float
```

**Comment by alabrazi** [comment]
Seems so. 
Extending the range to start from -1 instead of 0 is one option to make sympy plot the graph.
`plot((2.5-(t/8760), (t, 0, 8760)), ((-1348.8*ln(t)+12692)/1000, (t, -1, 8760)))`

**Comment by oscarbenjamin** [comment]
So can this issue be closed?

**Comment by alabrazi** [comment]
Yes

**Comment by oscarbenjamin** [comment]
Thanks for getting back. Closing.
