### ISSUE TITLE
display of integrals

### ISSUE THREAD

**Issue by Greg1950** [sympy/sympy#12633]
I'm brand new to this, so if I'm posting in the wrong location, please let me know. 

My system:  I'm using the latest version of 64-bit Anaconda3 under Windows 10, and I'm in a Jupyter notebook after which SymPy 1.0's  `init_session()` has been run.  Among other actions, `init_session()` imports `sympy` and invokes the `init_printing()` command.  Consequently output cells look (for the most part) like traditionally typeset mathematics.

 I entered a command `Integral(exp(x)*sin(x)+ exp(x)*cos(x), x)`.  This should just display the integral to be done, not actually do it. What displays in the output cell is the integrand $e^x sin(x) + e^x cos(x)$, *without parentheses enclosing the terms*, sandwiched between the integral sign $\int$ on the left and the $dx$ on the right.  This goes against standard practice when displaying integrals.  Conceptually the "infinitesimal" $dx$ multiplies both terms of the integrand., and not just the right term. 

The analog is writing $a + bc$ when what one intends is $(a + b)c$.  The former multiplies $b$ and $c$, then adds the result to $a$, while the latter adds $a$ and $b$, then multiplies their sum by $c$.

By the way, I've enclosed some things above between dollar signs.  The idea was to use MathJax to display those things as typeset mathematics, but I see in the Preview tab that doesn't work.  Is there a way of showing typeset mathematics in this forum?

**Comment by asmeurer** [comment]
The omitting of parentheses here is not uncommon. The integral sign and the `dx` are often considered as the left and right operands of the integral operand. 

However, I do think we should put parentheses here, as it makes it easier to read. It is also what the pretty printer does, and generally `latex()` should match `pprint()`:

```
>>> pprint(Integral(exp(x)*sin(x)+ exp(x)*cos(x), x))
⌠
⎮ ⎛ x           x       ⎞
⎮ ⎝ℯ ⋅sin(x) + ℯ ⋅cos(x)⎠ dx
⌡
```

**Comment by hobenkr88** [comment]
This appears to have been fixed in the clone I made two days ago. Tested with:

>>> from sympy import *
>>> x = symbols('x')
>>> init_printing()
>>> Integral(sin(x)+1,x)

**Comment by asmeurer** [comment]
Indeed, it seems to be fixed in master.
