### ISSUE TITLE
latex(re(x)) should use parentheses

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#12649]
latex(re(x)) returns \Re{x}, but it would be better to use \Re{\left(x\right)}. 

I also don't really like \Re (would prefer \mathrm{Re}), but that's a separate issue.

**Comment by hanq08** [comment]
Can I just change precedence to 'Atom'?
`tex = r"\Re{%s}" % self.parenthesize(expr.args[0], PRECEDENCE['Atom'])`
