### ISSUE TITLE
Can't solve Integral((sin(2*x)*cos(x))/(1+cos(x)), (x, 0, pi/2))

### ISSUE THREAD

**Issue by neihousaigaai** [sympy/sympy#12641]
`Integral((sin(2*x)*cos(x))/(1+cos(x)), (x, 0, pi/2))` should return `2*log(2)-1`, but it returns itself.

**Comment by hanq08** [comment]
Looks like sympy can't solve this. See issue #11876. A new integration rule should be added in manualintegrate so it can recognise and convert sin(2x) tp 2cos(x)sin(x), etc. Any ideas?

**Comment by ishanaj** [comment]
Is there anything else to be done(or added) apart from what is done in PR #12651? 
I would like work on it.
@gxyd @neihousaigaai

**Comment by gxyd** [comment]
Fixed by https://github.com/sympy/sympy/pull/12651 . Closing this.
