### ISSUE TITLE
(x<oo).subs({-oo:1,oo:3,x:2}) ->False

### ISSUE THREAD

**Issue by smichr** [sympy/sympy#12657]
This is really strange. Please confirm:

```
>>> x<oo
x < oo
>>> (x<oo).subs({-oo:1,  oo:3,  x:2})  # should be 2 < 3 -> True
False
```

**Comment by smichr** [comment]
I suspect there is confusion about whether to treat `-oo` like an atom or a Mul. Using `xreplace` gives the right result and is a workaround.

**Comment by maurogaravello** [comment]
In `basic.py`, line 915, sympy does, more or less, the following steps in the substitution of `-oo` with `1`:
from `x<oo` we have `x<-(-oo)` and so `x<-1`.

**Comment by smichr** [comment]
The fix is to define `_eval_subs` for +/-oo. I'll make a PR this week unless someone else does so first.
