### ISSUE TITLE
integrate(1/(sqrt(x**2 + c**2)), x)

### ISSUE THREAD

**Issue by benzene33333** [sympy/sympy#12667]
This does not return the correct function.  It returns asinh(x/c).  It should return ln(x + sqrt(x**2 + c**2)).  They are the same if c = 1 but are different otherwise.  I included a simulation in Origin to show this and I verified that the ln function is correct numerically and with my TI-89 which in my experience never misses.
![c1](https://cloud.githubusercontent.com/assets/28904042/26369312/4f8b9efa-3fc2-11e7-8b12-216788ad2ad3.jpg)
![c2](https://cloud.githubusercontent.com/assets/28904042/26369315/5176247e-3fc2-11e7-9ff9-67d772fe6213.jpg)

**Comment by benzene33333** [comment]
Formatting ruined the content in the ln function above in the text...should be ln(x + sqrt(x**2 + c**2))

**Comment by benzene33333** [comment]
Wow...same problem...it is x squared and c squared inside of the square root...whew

**Comment by jksuom** [comment]
The logarithmic form of `asinh(x)` is `ln(x + sqrt(x**2 + 1))`. It follows that

    asinh(x/c) = ln(x/c + sqrt(x**2/c**2 + 1)) = ln(x + sqrt(x**2 + c**2)) - ln(c).

Hence the difference of the two functions is constant and both of them are valid indefinite integrals of `1/sqrt(x**2 + c**2)`.

**Comment by benzene33333** [comment]
You are correct...my mistake.  I made a numerical error and got confused...didn't stop long enough to think.  Sorry.
