### ISSUE TITLE
_eval_det_lu() always calls LUdecomposition_Simple() with its default keyword arguments

### ISSUE THREAD

**Issue by twhunt** [sympy/sympy#12661]
_eval_det_lu() has no mechanism to pass LUdecomposition_Simple() keyword arguments.
_eval_det_lu() catches a ValueError that LUdecomposition() will not throw as of commit 782ff711d58c78b0017ffa30077cba70f38a136b.

**Comment by jksuom** [comment]
Closed by #12662
