### ISSUE TITLE
sympy.Matrix appends extra dimension

### ISSUE THREAD

**Issue by nschloe** [sympy/sympy#12666]
(The following might or might not be intended by design.)

I'm having an issue when using a `sympy.Matrix` in a `dot` product: The lambdification will yield a dot-product with an extra dimension.

The MWE
```python
import numpy
import sympy


class dot(sympy.Function):
    pass


a = sympy.Matrix([1, 2, 3])
x = sympy.Symbol('x')

expr = dot(x, a)
f = sympy.lambdify(x, expr)

x = numpy.random.rand(7, 77, 3)
print(f(x).shape)
```
prints
```
(7, 77, 1)
```
instead of `(7, 77)`. When replacing the `sympy.Matrix` by a `numpy.array`, it all works as expected ([other problems](https://github.com/sympy/sympy/issues/12665) set aside).

**Comment by asmeurer** [comment]
The shape of your `x` is `(7, 77, 3)` (see https://docs.scipy.org/doc/numpy/reference/generated/numpy.random.rand.html#numpy.random.rand). Maybe you wanted [randint](https://docs.scipy.org/doc/numpy/reference/generated/numpy.random.randint.html#numpy.random.randint).

**Comment by nschloe** [comment]
Thanks Aaron for your reply.

Actually I _do_ want `x` to have exactly that shape. The dot product then will be the dot product of all `[77, 7]` vectors of the length 3 as in
```python
import numpy

x = numpy.random.rand(77, 7, 3)
a = numpy.random.rand(3)

print(numpy.dot(x, a).shape)
```
If `a` is of shape `[3, 1]`, then the result has shape `[77, 7, 1]`, which I must avoid.

**Comment by asmeurer** [comment]
I see. This is expected behavior. Matrices always have 2d shape. `Matrix([1, 2, 3])` is just syntactic shorthand for `Matrix([[1], [2], [3]])`. We used to use `np.matrix`, but this was deemed a bad idea. 

Maybe there is a more elegant way of solving the problem, but one way would be to define a custom printer on your `dot` class that fixes the shape. Or you could pass a custom function to `lambdify` that fixes it. 

By the way, I noticed the lambdify printers do not let you modify their printing properly https://github.com/sympy/sympy/issues/12668.

**Comment by nschloe** [comment]
> be to define a custom printer on your dot class that fixes the shape. 

A printer as in `print()`? Perhaps you can elaborate on that (if it makes sense at all in light of #12668).

> Or you could pass a custom function to lambdify that fixes it.

A custom function? What do you mean by that?

**Comment by asmeurer** [comment]
Sorry, I mean defining `_sympystr(self, printer)` on your `dot` class. Or for the custom function, passing `['numpy', {'dot': lambda x, y: ...}]` as the third argument to lambdify (where `...` performs `np.dot` after fixing the shape, I don't recall exactly how to do that in NumPy).

**Comment by nschloe** [comment]
>  Or for the custom function, passing ['numpy', {'dot': lambda x, y: ...}] as the third argument to lambdify

I see. Even better would be to intercept the `Matrix` itself, but I'm not sure what keyword is necessary there. Neither of
```
modules = [{'ImmutableMatrix': mymat}, 'numpy']
```
and
```
modules = [{'MutableDenseMatrix': mymat}, 'numpy']
```
did the trick.

**Comment by asmeurer** [comment]
The first one should work. There is even an example in the `lambdify` docstring that sets ImmutableMatrix to np.matrix.

**Comment by nschloe** [comment]
Well, it doesn't:
```python
import numpy
import sympy


class dot(sympy.Function):
    pass


a = sympy.Matrix([1, 2, 3])
x = sympy.Symbol('x')


def mymat(x):
    print('here i am')
    exit(1)
    return a


expr = dot(x, a)
f = sympy.lambdify(
        x, expr,
        modules=[{'ImmutableMatrix': mymat}, 'numpy']
        )

x = numpy.random.rand(7, 77, 3)
print(f(x).shape)
```

**Comment by asmeurer** [comment]
Hmm, it works in 1.0 but not in master.

**Comment by nschloe** [comment]
Probably worth filing a separate bug then. If you don't object, I'll go ahead and do so.

**Comment by asmeurer** [comment]
Bisected to 6d55b862ea1546269c52a93cf2984096501662a8. Seems it was changed to `ImmutableDenseMatrix`. @siefkenj can you add this and any other backwards incompatible changes to https://github.com/sympy/sympy/wiki/Release-Notes-for-1.1#backwards-compatibility-breaks-and-deprecations?

**Comment by nschloe** [comment]
Alright, great. Now
```python
import numpy
import sympy


class dot(sympy.Function):
    pass


a = sympy.Matrix([1, 2, 3])
x = sympy.Symbol('x')


def vector2vector(x):
    out = numpy.array(x)
    if len(out.shape) == 2 and out.shape[1] == 1:
        out = out[:, 0]
    return out


expr = dot(x, a)
f = sympy.lambdify(
        x, expr,
        modules=[{'ImmutableDenseMatrix': vector2vector}, 'numpy']
        )

x = numpy.random.rand(7, 77, 3)
print(f(x).shape)
```
does what I had expected in the beginning: `Matrix([1,2,3])` is translated to `numpy.array([1,2,3])`. Unfortunately, one cannot distinguish between `Matrix([1,2,3])` and `Matrix([[1],[2],[3]])`, but there's nothing I can do about that.

@asmeurer Would you think that it'd be worthwhile discussing the fact that a `sympy.Matrix` always has two dimensions, never 1 or more than 2 (like a `numpy.array`)?

**Comment by bjodah** [comment]
@nschloe a Matrix is 2D by definition, constructs with higher dimensions are e.g. Tensors or N-dimensional arrays. We have an N-dimensional array in SymPy, it could be worth trying out.

**Comment by asmeurer** [comment]
Also worth noting that np.dot has somewhat odd behavior with 1D arrays. It automatically treats the array as a column or row vector, depending on the other argument.
