### ISSUE TITLE
sympy requires ttfonts.map from the zhmetrics latex package

### ISSUE THREAD

**Issue by chickadee7** [sympy/sympy#12669]
```python
In [1]: import sympy
In [2]: sympy.init_printing()
```

It seems like sympy is not able to find the latex files it needs because when I enter these commands in python I get the following message:

![image](https://cloud.githubusercontent.com/assets/28904679/26371902/c68f916a-3fc1-11e7-8651-7fca5bb1261f.png)

I tried installing the zhmetrics latex package and copied the tile ttfonts.map to the directory 
MiKTeX 2.9/tex/latex/fonts/map/ttf2pk but that did not change anything.  How can I fix this?

**Comment by jksuom** [comment]
This looks like a MiKTeX installation problem. Probably TeX forums could help. For example this one: https://tex.stackexchange.com/questions/152721/problems-with-fonts

**Comment by chickadee7** [comment]
You're right it is a MiKTeX problem.  After doing some more digging, I think sympy is running latex code that requires fonts stored in the zhmetrics LaTeX package, which is not automatically installed in the MiKTeX distribution.  I found this youtube video very helpful for installing LaTeX packages, which is sort of complicated: https://www.youtube.com/watch?v=ZTJkI-czgyA

**Comment by oscargus** [comment]
Interesting. zhmetrics contains fonts for Chinese characters and I am pretty sure that sympy does not use any of those. It is possible though that some parameters are based on locales from the system. Could that be a reason?

I close this for now since it is solved.
