### ISSUE TITLE
vectors break pretty printing

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#12675]
```py
In [1]: from sympy.vector import *

In [2]: e = CoordSysCartesian('e')

In [3]: (x/y)**t*e.j
Out[3]:
⎛   t⎞ e_j
⎜⎛x⎞ e_j ⎟
⎜⎜─⎟ ⎟
⎝⎝y⎠ ⎠
```

Also, when it does print correctly, the baseline is wrong (it should be centered).

**Comment by rpz-harode** [comment]
Hi @asmeurer . I would like to work on this issue . Could you help me with the same ?
