### ISSUE TITLE
Definite integral not working

### ISSUE THREAD

**Issue by maurogaravello** [sympy/sympy#12677]
I noticed that the following code
```
x = Symbol('x', real = True)
expr = sin(x)/(cos(x)**3)
f = integrate(expr, (x, 0, pi/6))
```
does not work. However, if one tries to calculate only the primitive of `expr = sin(x)/(cos(x)**3)`, i.e. `integrate(expr, x)`, then sympy returns the correct answer.

**Comment by gxyd** [comment]
It does work for me:
```
gxyd@stallman:~/foss/sympy$ ipython3
Python 3.6.0 |Anaconda 4.3.1 (64-bit)| (default, Dec 23 2016, 12:22:00) 
Type "copyright", "credits" or "license" for more information.

IPython 5.1.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: from sympy import *

In [2]: x = Symbol('x', real = True)

In [3]: expr = sin(x)/(cos(x)**3)

In [4]: f = integrate(expr, (x, 0, pi/6))

In [5]: f
Out[5]: 1/6
```

**Comment by maurogaravello** [comment]
What version of sympy do you use? 
I tried with the last github version and with both python2 and python3. Unsuccessfully.

**Comment by gxyd** [comment]
```
In [6]: import sympy

In [7]: sympy.__version__
Out[7]: '1.0.1.dev'
```

**Comment by gxyd** [comment]
Does it return anything or just hangs in there for you?

**Comment by gxyd** [comment]
Sorry, in the latest master it does hang. My branch wasn't up to date.

**Comment by maurogaravello** [comment]
Sympy goes in an infinite loop. After some debugging, I notice that the loop is due to some lines in the `_eval_interval(self, x, a, b)` of `expr.py`. More precisely, at a certain point there is the code `list(solveset(self.cancel().as_numer_denom()[1], x))` and this is an infinite set. Then the next lines, starting with  `for s in singularities:`, are responsible for the infinite loop.
A possibility is to change in the following way:
```
        if a.is_comparable and b.is_comparable:
            if a < b:
                domain = Interval(a, b)
            else:
                domain = Interval(b, a)
            singularities = solveset(self.cancel().as_numer_denom()[1], x)
            singularities = list(Intersection(domain, singularities))
            for s in singularities:
                if a < s < b:
                    value += -limit(self, x, s, "+") + limit(self, x, s, "-")
                elif b < s < a:
                    value += limit(self, x, s, "+") - limit(self, x, s, "-")
```
In this way, probably it works.
