### ISSUE TITLE
beta latex input not working properly

### ISSUE THREAD

**Issue by alexeistepa** [sympy/sympy#12672]
Just a basic bug, 
When I try to define a symbol beta sympy prints a square followed by 'eta'.
>>> b = symbols('\beta')
... b
eta
The above was copy pasted from the online shell, I get the same issue when defining beta in my notebooks.

**Comment by asmeurer** [comment]
In Python, backslash escapes the next character. `\b` creates an ASCII backspace character (see https://docs.python.org/3.6/reference/lexical_analysis.html#string-and-bytes-literals).

To create a string with a backslash, either prefix the string with an `r`, to indicate that it is a "raw" string, like `symbol(r'\beta')`, or escape the backslash, like `symbols('\\beta')` (the first method of using a raw string is usually preferred).
