### ISSUE TITLE
Piecewise integration test is wrong

### ISSUE THREAD

**Issue by smichr** [sympy/sympy#12674]
The following test in 'test_piecewise' is wrong:

```
p1 = Piecewise((0, x < a), (0.5, x > b), (1, True))
...
assert integrate(p1, (x, -oo, y)) == 0.5*y + 0.5*Min(b, y) - Min(a, b, y)
```

as is asserted with these values:

```
>>> ans
y/2 + Min(b, y)/2 - Min(a, b, y)
>>> p1
Piecewise((0, x < a), (1/2, b < x), (1, True))
>>> i = Integral(p1, (x, -oo, y))
>>> ok = Tuple(ans, i)
>>> ok.subs({a:3, b:0, y:1})
(0, 0.5)  # <-- these should be the same
```

**Comment by jksuom** [comment]
Also the indefinite integral is wrong. It is discontinuous, in general:
```
>>> integrate(p1, x)
Piecewise((0, x < a), (0.5*x, x > b), (x, True))
```

**Comment by smichr** [comment]
The following is from my `lts` branch which is in a rough state. I'm not sure what should be done: return the potentially many-conditional general solution or just return and unevaluated integral if there are "too many" conditions. (The same dilemma applies to the definite integral.)

```
>>> from sympy.functions.elementary.piecewise import _simplify
>>> var('a b x', finite=True)
(a, b, x)
>>> q=Piecewise((0, x < a), (1, x > b), (2, True)).integrate(x)
>>> pp(q)
Piecewise(
    (0, (a <= b) & (x <= a)),
    (-2*a + 2*x, (a <= x) & (x <= b)),
    (-2*a + b + x, (a <= b) & (b <= x)),
    (0, ((b <= a) | (b <= x)) & 
        ((b <= a) | (x <= a)) & 
        ((b <= x) | (x <= b)) & 
        ((x <= a) | (x <= b))),
    (-a + x, (a <= x) & (b <= a)))
>>> _simplify(q.subs(dict(zip((a,b),(1,3)))))
Piecewise((0, x <= 1), (2*x - 2, (x >= 1) & (x <= 3)), (x + 1, x >= 3))
>>> _simplify(q.subs(dict(zip((a,b),(3,1)))))
Piecewise((0, x <= 3), (x - 3, x >= 3))
```

**Comment by jksuom** [comment]
One possibility is to transform the function internally into the equivalent form

    Piecewise((0, x <= a), (1, x > c), (2, True)),

where `c = max(a, b)`. Then the integration could yield

    Piecewise((0, x <= a), (-2*a + 2*x, x <= c), (-2*a + c + x, c < x)).subs(c, max(a, b))

Another possibility is to deal separately with the two cases

    a < b:    Piecewise((0, x <= a), (2, x <= b), (1, b < x))
    a >= b:   Piecewise((0, x <= a), (1, a < x))

 and then return a nested result:

    Piecewise(
        (Piecewise((0, x <= a), (-2*a + 2*x, x <= b), (-2*a + b + x, b < x)), a < b),
        (Piecewise((0, x <= a), (-a + x, a < x)), a >= b))

**Comment by smichr** [comment]
This comes back as the following, now:

```
>>> Piecewise((0, x < a), (1, x > b), (2, True)).integrate(x)
Piecewise(
    (0, x <= Min(a, b)),
    (-2*a + 2*x, (x <= b) & (a < x)),
    (-2*a + b + x, Max(a, b) < x),
    (0, (x <= a) & (b < x)))
```

**Comment by jksuom** [comment]
(-2*a + b + x, Max(a, b) < x),  # this ExprCondPair
    (-2*a + Max(a, b) + x, Max(a, b) < x),  # should be this

**Comment by smichr** [comment]
OK, I updated the indefinite integration to work with the Min/Max sorted intervals and this now comes back as

```
Piecewise(
    (0, x <= a),
    (-2*a + 2*Min(x, Max(a, b)), x <= Max(a, b)),
    (-2*a + x + Max(a, b), True))
```

I'm not sure how to get your result but the two evaluate to the same thing. Here is the approach I am taking to compute the continuous expression:

```
        sum = None
        for a, b, i in done:
            anti = integrate(abe[i][-1], x, **kwargs)
            bx = Min(b, x)
            if sum is None:
                sum = anti._eval_interval(x, a, bx)
            else:
                sum = sum.subs(x, a)
                sum += anti._eval_interval(x, a, bx)
```

**Comment by smichr** [comment]
Oh, I see. In each interval I just want the upper limit to be `x` and let the condition on that piece limit what x can be, so the result should be:

```
Piecewise(
    (0, x <= a),
    (-2*a + 2*x, x <= Max(a, b)),
    (-2*a + x + Max(a, b), True))

**Comment by jksuom** [comment]
The first interval may be unbounded (`a == -oo`) and the definite integral may be infinite, Perhaps the first sum piece could be just the antiderivative `anti`.

**Comment by smichr** [comment]
> Perhaps the first sum piece could be just the antiderivative anti.

Yes, that is what some of the tests reminded me about: if you don't do this then you end up with an infinity tagging along if the first interval has a non-0 integrand.

```
        sum = None
        for a, b, i in done:
            anti = integrate(abe[i][-1], x, **kwargs)
            if sum is None:
                sum = anti
            else:
                sum = sum.subs(x, a)
                sum += anti._eval_interval(x, a, x)
```

You might have noticed that I opened a new PR. I am trying to factor out some of the pieces to make the review easier. If all the tests pass, I don't have anything more that needs to be done. (I am expecting some tests to fail, however.)
