### ISSUE TITLE
[matrices] remove dead files `densearith.py` `densetools.py` and `densesolve.py`

### ISSUE THREAD

**Issue by siefkenj** [sympy/sympy#12695]
It appears that `densearith.py` `densetools.py` and `densesolve.py` are left over from a half-finished project.  They are used nowhere in the code base, and glancing at the code, are least the row-reduction algorithm appears to be incorrect.

Those modules have to be imported manually.  I propose adding a deprecation warning whenever someone imports them and slate them for removal in sympy 1.2.

**Comment by jksuom** [comment]
The commit message of densearith says
> Support for gmpy types is being added to the Matrix module in this PR like the Polys module.

This looks like something that is currently planned for all polys domains, not for gmpy types alone. If that is implemented, then this should apparently be deprecated. Maybe a warning would be appropriate now.

**Comment by firedranzer** [comment]
@siefkenj Is this issue still open? I would like to work on this issue.

**Comment by siefkenj** [comment]
@firedranzer It is!  You just need to add a deprecation warning to those files and fix the tests to handle the deprecation warning.  You can look at how the deprecated tests in `test_matrices.py` are handled.
