### ISSUE TITLE
Order of input can break Min/Max calls

### ISSUE THREAD

**Issue by djsegal** [sympy/sympy#12704]
arose from: https://github.com/JuliaPy/SymPy.jl/issues/163

+ `min([0,x])` causes an error
+ `min([x,0])` does not

**Comment by jksuom** [comment]
`min` is a Python built-in that does not know how to handle SymPy objects. Its counterpart in SymPy is `Min`. Thus `Min(0, x)` or `Min(x, 0` should be used in SymPy.

**Comment by smichr** [comment]
Thanks for the reply. Closing issue. BTW, if you have a question about SymPy behavior, feel free to use the mailing list, too, @djsegal .
