### ISSUE TITLE
Integral.as_sum() should output a Sum() object

### ISSUE THREAD

**Issue by moorepants** [sympy/sympy#12707]
Currently, Integral.as_sum() outputs an evaluated summation instead of an unevaluated expression:

```
In [1]: import sympy as sm

In [2]: t, t0, tf = sm.symbols('t, t0, tf')

In [3]: x = sm.Function('x')(t)

In [4]: y = sm.Function('y')(t)

In [5]: J = sm.Integral((x - y)**2, (t, t0, tf))

In [6]: J.as_sum(20, 'trapezoid')
Out[6]: (-t0/20 + tf/20)*((x(t0/20 + 19*tf/20) - y(t0/20 + 19*tf/20))**2 + (x(t0/10 + 9*tf/10) - y(t0/10 + 9*tf/10))**2 + (x(3*t0/20 + 17*tf/20) - y(3*t0/20 + 17*tf/20))**2 + (x(t0/5 + 4*tf/5) - y(t0/5 + 4*tf/5))**2 + (x(t0/4 + 3*tf/4) - y(t0/4 + 3*tf/4))**2 + (x(3*t0/10 + 7*tf/10) - y(3*t0/10 + 7*tf/10))**2 + (x(7*t0/20 + 13*tf/20) - y(7*t0/20 + 13*tf/20))**2 + (x(2*t0/5 + 3*tf/5) - y(2*t0/5 + 3*tf/5))**2 + (x(9*t0/20 + 11*tf/20) - y(9*t0/20 + 11*tf/20))**2 + (x(t0/2 + tf/2) - y(t0/2 + tf/2))**2 + (x(11*t0/20 + 9*tf/20) - y(11*t0/20 + 9*tf/20))**2 + (x(3*t0/5 + 2*tf/5) - y(3*t0/5 + 2*tf/5))**2 + (x(13*t0/20 + 7*tf/20) - y(13*t0/20 + 7*tf/20))**2 + (x(7*t0/10 + 3*tf/10) - y(7*t0/10 + 3*tf/10))**2 + (x(3*t0/4 + tf/4) - y(3*t0/4 + tf/4))**2 + (x(4*t0/5 + tf/5) - y(4*t0/5 + tf/5))**2 + (x(17*t0/20 + 3*tf/20) - y(17*t0/20 + 3*tf/20))**2 + (x(9*t0/10 + tf/10) - y(9*t0/10 + tf/10))**2 + (x(19*t0/20 + tf/20) - y(19*t0/20 + tf/20))**2 + x(t0)**2/2 - x(t0)*y(t0) + x(tf)**2/2 - x(tf)*y(tf) + y(t0)**2/2 + y(tf)**2/2)
```

For large n this takes a long time to compute. It seems like this should output an unevaluated sum and if the user wants to expand the sum they'd call `.doit()` on the result. It may not be worth deprecating this behavior, but maybe we need to have a `as_unevaluated_sum()` method.

**Comment by firedranzer** [comment]
Hi @moorepants ! I want to work on this issue .

**Comment by moorepants** [comment]
Go for it!

**Comment by firedranzer** [comment]
@moorepants Any kind of help will be appreciated.I'm new to this organization.

**Comment by moorepants** [comment]
Start here: https://github.com/sympy/sympy/wiki/introduction-to-contributing

Read the materials, setup your dev environment, and do the tutorial.

**Comment by firedranzer** [comment]
@moorepants I've read the materials.
Coming back to the issue tell me about the changes need to be done and point me to the files to be worked with.

**Comment by moorepants** [comment]
Here is the associated code: https://github.com/sympy/sympy/blob/master/sympy/integrals/integrals.py#L993

I suggest seeing if the reviewers would accept a deprecation so that we can change the behavior of `as_sum` but if not you'll need to create a new method. It would also be worth determining if the `Sum` object has duplicate code for the expansions in it's `doit()` method.
