### ISSUE TITLE
cannot import acsch

### ISSUE THREAD

**Issue by kyle-vigil** [sympy/sympy#12701]
All hyperbolic and inverse hyperbolic functions, except acsch, can be accessed from sympy.

Trying `from sympy import acsch`, acsch is the only inverse hyperbolic function to fail.
Trying `from sympy.functions.elementary.hyperbolic import acsch` acsch is again the only inverse hyperbolic function to fail.

Trying 'Run code block in SymPy Live' [here](http://docs.sympy.org/dev/modules/functions/elementary.html#acsch) produces the same errors.

Compared to the other function definitions [here](http://docs.sympy.org/dev/_modules/sympy/functions/elementary/hyperbolic.html#acsch) it seems to be lacking an expansion_term or taylor_term method decorated with staticmethod and cacheit.

**Comment by jksuom** [comment]
It has been importable in master since March 2016.
taylor_term is lacking because acsch is not analytic at the origin.

**Comment by kyle-vigil** [comment]
I'm running version 1.0, as is the sympy live shell I linked.  Why does the pre-written code fail in the sympy live shell hosted on sympy.org?
