### ISSUE TITLE
Model docstring examples for sympy

### ISSUE THREAD

**Issue by siefkenj** [sympy/sympy#12710]
Sympy could use some docs on what is expected for docstrings: how to list args, kwargs, include math, etc.

Nympy has a page that would make a good starting point: http://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_numpy.html

**Comment by rpz-harode** [comment]
Hi! I would like to work on this.Please guide me through it.

**Comment by siefkenj** [comment]
Great!  The first thing to do is get sphinx working for documentation building on your machine.  Then, survey the existing docs and extract the best practices.  For example, the docstring for `epath` in http://docs.sympy.org/latest/modules/simplify/simplify.html looks pretty good to me.  There are also several good-looking docstrings in `matrices.py`, but there are also some not-so-good looking ones.  I would use the `numpy` example as a starting point, and modify it to match `sympy`'s style.  For example, `sympy` tends to use `=====` to underline things instead of `----`, and we don't use pep484.  

I'm not sure if the wiki, or the `sympy` codebase is the best place to develop a guide. Any comments @moorepants @asmeurer ?

**Comment by rpz-harode** [comment]
Thanks @siefkenj for this opportunity.Looking forward to contributing to this organisation.Just one thing , I am complete newcomer to this organisation so please bear with me , so that we can make the learning process faster.Also can I contact you one-to-one if I have some query.That would be great.

**Comment by siefkenj** [comment]
That's great.  New contributors are always welcome!  Questions related to this project should be asked here, if they'd be relevant to others trying to understand why a decision was made a certain way.  General questions, you can ask on Gitter.  https://gitter.im/sympy/sympy  I am in and out with my work schedule, so I'm not always timely, so it's best to ask questions on Gitter.  (Plus, I only know some specific parts of `sympy`.  Others have more general knowledge.)

**Comment by asmeurer** [comment]
There's [this](https://github.com/sympy/sympy/wiki/Writing-documentation#docstrings). We could make that page easier to find, or move it to the docs (so far, most documentation for development on SymPy itself is on the wiki).

**Comment by ishanaj** [comment]
@asmeurer Should we move this wiki page to `doc`, if so I would like to work on it. Please suggest.

**Comment by ayushmankoul** [comment]
Hello @asmeurer @siefkenj Can I work on this task if it is yet to be completed ?
Regards
Ayushman Koul

**Comment by moorepants** [comment]
I think we should simply adopt the [numpydoc/napolean](http://www.sphinx-doc.org/en/master/usage/extensions/napoleon.html) format and work to change all docstrings to that format.

**Comment by smichr** [comment]
#15272 has comments about what was done to fix up Matrix docstrings and might be a good reference to consult when writing the wiki page.

**Comment by RashiG27** [comment]
Hey! I would like to work on it. Please guide me through it.

**Comment by moorepants** [comment]
We now have a docstring style guide, so I'm closing this.
