### ISSUE TITLE
Add warning about modulus variant to elliptic integral documentation

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#12715]
This just tripped me up. The elliptic integrals in Sympy are defined with the `m` parameter instead of the `k` parameter (`m = k**2`).

See https://en.wikipedia.org/wiki/Elliptic_integral#Notational_variants. We should add some notes to the docstrings to warn about this.

**Comment by LejlaMetohajrova** [comment]
Hi, I would like to work on this. I am new to sympy, but this looks pretty easy so I hope I won't mess it up :)

**Comment by LejlaMetohajrova** [comment]
I am not able to build the documentation. It shows this error:
`Makefile:121: warning: overriding recipe for target '_build/cheatsheet/cheatsheet.pdf'`
`Makefile:116: warning: ignoring old recipe for target '_build/cheatsheet/cheatsheet.pdf'`
`rm -rf _build/logo`
`mkdir -p _build/logo`
`python ./generate_logos.py -d`
`INFO:root: File saved: ./_build/logo/sympy-notail.svg`
`INFO:root: File saved: ./_build/logo/sympy-notailtext.svg`
`INFO:root: File saved: ./_build/logo/sympy-notext.svg`
`ERROR:root:rsvg-convert: command not found`
`Makefile:146: recipe for target 'logo' failed`
`make: *** [logo] Error 127`

Can you please help me with this @asmeurer ?
