### ISSUE TITLE
BooleanAtom.is_Atom -> False (could/should be True)

### ISSUE THREAD

**Issue by smichr** [sympy/sympy#12717]
Is there any reason that the following gives False instead of True

```
>>> S.true.is_Atom
False
```

**Comment by samyak-jain** [comment]
Can I work on this?

**Comment by smichr** [comment]
> Can I work on this?

Sure!  I would recommend a single line fix in BooleanAtom, right after `is_Boolean = True` :-) And then add a test function to `sympy/logic/tests/test_boolalg.py` that demonstrate that this now works.

**Comment by smichr** [comment]
Looks good...now if you make a pull request we can get this committed.

**Comment by samyak-jain** [comment]
I made the pull request. However, according to travis, some tests failed.

**Comment by smichr** [comment]
I see it. It was just a test that took too long and timed out. I restarted it and will commit after it passes.
