### ISSUE TITLE
Simplification with assumptions: refine and abs

### ISSUE THREAD

**Issue by maurogaravello** [sympy/sympy#12724]
The following code
```
from __future__ import division, print_function
from sympy import *

x, y = symbols('x, y', real = True)

expr1 = abs(x)
expr2 = abs(x*y)
hyp = Q.positive(x)

ref1 = refine(expr1, hyp)
ref2 = refine(expr2, hyp)
```
returns `ref1 = x` and `ref2=Abs(x*y)`. Clearly `Abs(x*y)` is correct, but I think that a better result should be  `x*Abs(y)`.

**Comment by samyak-jain** [comment]
Actually it seems none of the refine methods work well on multiple variables

'refine((-1)**(x*y), Q.even(x))'

gives (-1)**(x*y) even though it should give 1

I think I will try working on this.

**Comment by maurogaravello** [comment]
@samyak-jain Your example is not completely correct. Indeed if `x = 2` and `y = 1/2`, then `x*y = 1` and so `(-1)**(x*y) = -1`.

**Comment by samyak-jain** [comment]
Good point. Didn't think of that. That means the problem is only with refine_abs()?

**Comment by maurogaravello** [comment]
I do not know whether the problem is only with `refine_abs()`. 
However, I think that fixing this issue is important for simplification purposes.
@samyak-jain Are you working on this?

**Comment by samyak-jain** [comment]
@maurogaravello yes i am giving it a shot

**Comment by Krista** [comment]
@samyak-jain are you still working on this ?

**Comment by samyak-jain** [comment]
@Krista I have stopped working on this for now
