### ISSUE TITLE
Deprecate has_Field/Ring for domains and replace with is_Field/Ring

### ISSUE THREAD

**Issue by valglad** [sympy/sympy#12723]
The pr modifies `sympy/utilities/tests/test_pickling.py`. This is temporary and should be removed when `has_Field` and `has_Ring` are fully replaced.

The modification is adding `check_attr=False` to all the calls of `check()` in `test_pickling_polys_domains()`.

**Comment by firedranzer** [comment]
Hi @valglad ! I would like to work on this issue . Guide me for this .

**Comment by valglad** [comment]
It's too early. The deprecation has to stick around for a while to give the users time to get used to the new names. I've created the issue to make sure the changes are removed when enough time has passed.
