### ISSUE TITLE
Bug of vector norm function

### ISSUE THREAD

**Issue by kkosmidis** [sympy/sympy#12742]
x=symbols("x",real=True)
v=Matrix([1,1,sqrt(x)])
v.norm()

The above returns sqrt(-x+2) instead of the correct sqrt(x+2)

**Comment by szymag** [comment]
I have run your program with the newest version of SymPy and I get correct result:
```python
from sympy import symbols, sqrt
from sympy.matrices import Matrix
x=symbols("x",real=True)
v=Matrix([1,1,sqrt(x)])
print(v.norm())
```
```python
sqrt(Abs(sqrt(x))**2 + 2)
```

**Comment by kkosmidis** [comment]
In sympy version 1.0 it produces the wrong result
 sympy.__version__
Out[8]: '1.0'

In [2]: from sympy import symbols, sqrt
   ...: from sympy.matrices import Matrix
   ...: x=symbols("x",real=True)
   ...: v=Matrix([1,1,sqrt(x)])
   ...:print(v.norm())

sqrt(-x + 2)

**Comment by nebnola** [comment]
abs(sqrt(x)) returns sqrt(-x), which is not true. If abs() is passed a SymPy expression, it will be handled by the Abs() class, defined in sympy/functions/elementary/complexes.py
This is the part that deals with powers (where arg is the expression of which you try to calculate the absolute value):
```
if arg.is_Pow:
            base, exponent = arg.as_base_exp()
            if base.is_real:
                if exponent.is_integer:
                    if exponent.is_even:
                        return arg
                    if base is S.NegativeOne:
                        return S.One
                    if base.func is cls and exponent is S.NegativeOne:
                        return arg
                    return Abs(base)**exponent
                if base.is_nonnegative:
                    return base**re(exponent)
                if base.is_negative:
                    return (-base)**re(exponent)*exp(-S.Pi*im(exponent))
                return
```

I just don’t know where to go from there.

**Comment by nebnola** [comment]
Turns out the problem was already fixed. You won’t see this issue anymore when the updates are rolled out. I recommend this issue to be closed.
