### ISSUE TITLE
INVALID OPERATION (INVERSE TRIGONOMETRY)

### ISSUE THREAD

**Issue by ayush1999** [sympy/sympy#12756]
> from sympy import *
> x=symbols("x")
> expr=sin(asin(x))
> print(expr.subs(x,2))
> 
> 
**Gives the output** 
> 2
**Though asin(2) is not possible, due to which the whole expression becomes invalid.
_(sin(asin(x)) when x is not in the range of [-1,1] is invalid)_**

**Comment by jksuom** [comment]
In SymPy, trigonometric functions and their inverses are defined for complex arguments. Also `asin(2)` is defined, it has multiple values that are complex and `sin` has value 2 at each of them.
