### ISSUE TITLE
Add Wigner D matrices

### ISSUE THREAD

**Issue by oscarlazoarjona** [sympy/sympy#12766]
We should have [Wigner D matrices](https://en.wikipedia.org/wiki/Wigner_D-matrix) in sympy. They fit nicely in the physics.wigner module. I have functions `wigner_d_small` and `wigner_d` as defined in [1] that I would like to add.

[1] [A. R. Edmonds. Angular momentum in quantum mechanics](http://press.princeton.edu/titles/478.html). Investigations
     in physics, 4.; Investigations in physics, no. 4. Princeton, N.J.,
     Princeton University Press, 1957.

**Comment by OppenheimerAndTheMartians** [comment]
I'd like to help you with this, if possible. Been a while since I've cracked open Sakurai, though...

**Comment by oscarlazoarjona** [comment]
Sure, well I have added a pull request. Maybe you could check the code and approve it if you think it is ok. The Travis CI build failed, but I think this is because of some bug on their side, as far as I can see. Thank you for your interest!
