### ISSUE TITLE
Update documentation for vector module

### ISSUE THREAD

**Issue by szymag** [sympy/sympy#12760]
Corresponding to changes in #12720 and #12749, the documentation should be updated:
http://docs.sympy.org/dev/modules/vector/basics.html 
http://docs.sympy.org/dev/modules/vector/fields.html#scalar-and-vector-field-functionality

**Comment by harsh4123** [comment]
@szymag i would like to work on it

**Comment by szymag** [comment]
Great. In first step, we need to remove information that this module deals only with Cartesian coordinate, see 
http://docs.sympy.org/dev/modules/vector/basics.html
and 
#12720

**Comment by szymag** [comment]
@harsh4123, would you like to still work on it issue?
I'm asking because I'd be nice to update information about `Del` class before release new version of SymPy. 
The information should be updated mainly here: http://docs.sympy.org/dev/modules/vector/fields.html#the-del-operator
The changes should corresponds to this PR: #12749

**Comment by harsh4123** [comment]
give me 2 days, I will update it and then u could close the issue and update it.

**Comment by szymag** [comment]
OK

**Comment by moorepants** [comment]
Note that if you have made changes that are already in the 1.1 release and you did not update the documentation to reflect these changes, it could possible have this mismatch for a long time. The 1.1 release will happen in the next day likely. If this needs to get in you should tell @asmeurer.
