### ISSUE TITLE
Slow limit() calculation?!

### ISSUE THREAD

**Issue by WarShoe** [sympy/sympy#12769]
I am not 100% sure it is a (performance) bug, but I observe something strange when I use limit().

I have a function f(x,y) and I want to calculate f(x,x). This can be achieved by:
`f.subs(y,x)`
or with
`limit(f,y,x)`

I have a good function, where f(x,x) is defined. So the simplest substitution `f.subs(y,x)` just works.  But when I try to use limit(), sympy goes to deep thinking and never returns. And that puzzles me - why is it so complicated?! 

    from sympy import *
    r, z, x = symbols('r, z, x',real=True)
    a, b, s0, K, F0, s, T = symbols('a, b, s0, K, F0, s, T',positive=True,real=True)
    fx = (F0**b*K**b*r*s0 - sqrt((F0**2*K**(2*b)*a**2*(b - 1) + F0**(2*b)*K**2*a**2*(b - 1) + F0**(2*b)*K**(2*b)*s0**2*(b - 1)*(b**2 - 2*b + 1) - 2*F0**(2*b)*K**(b + 1)*a*r*s0*(b**2 - 2*b +  1) + 2*F0**(b + 1)*K**(2*b)*a*r*s0*(b**2 - 2*b + 1) - 2*F0**(b + 1)*K**(b + 1)*a**2*(b - 1))/((b - 1)*(b**2 - 2*b + 1))))*(b*r -  b - r + 1)
    fx.subs(K,F0)
    print('Starting to calculate the limit...')
    limit(fx,K,F0)
    print('Done!')

**Comment by oscarbenjamin** [comment]
I just tested this on current master and didn't wait for it to complete.

**Comment by jksuom** [comment]
This is an example where simple core methods would suffice to find the limit. `Limit.doit` currently only tries those methods (`inve.as_leading_term(u)`, [here](https://github.com/sympy/sympy/blob/master/sympy/series/limits.py#L251)) in case of limit at [infinity](https://github.com/sympy/sympy/blob/master/sympy/series/limits.py#L236) before passing over to `gruntz`. That should, in principle, be able to find the limit, but the computations seem to be too long.
