### ISSUE TITLE
Different results for integrate in sympy and wolfram alfa

### ISSUE THREAD

**Issue by christophesaintjean** [sympy/sympy#12777]
Hi, 
   i am trying to compute :
  $$\int log(\frac{x}{1-x} dx, for x in ]0,1[$$

   With Sympy, it gives :  $$G(x) = x*log(x/(1-x)) + log(x - 1)$$
   With Wolfram alpha, it gives $$G(x) = x*log(x/(1-x)) + log(1 - x) + cst$$

   Maybe these two results are correct but only the second one can be used in $]0,1[$

   Any ideas ?
C.

**Comment by jksuom** [comment]
The results differ only formally since `log(1 - x) = log((x - 1)*(-1)) = log(x - 1) + cst` where `cst = log(-1)`. Hence the integral over the interval (0, 1) can be computed also with SymPy:
```
>>> integrate(log(x/(1 - x)), (x, 0, 1))
0
```

**Comment by christophesaintjean** [comment]
My bad, thank you ;)
