### ISSUE TITLE
"sympy.plot_implicit(Or(Eq1,Eq2),(l,0,10),(g,0,30))" diverge and the plot is wrong.

### ISSUE THREAD

**Issue by chaihahaha** [sympy/sympy#12776]
from sympy import log, Eq, symbols,Or 
    from sympy import plot_implicit
    l, g = symbols('l g')
    r = 1.1
    b = 2
    b0 = 1
    plot_implicit(Or(
    ”“”Eq1“”“    Eq(log(10 * r - r * l * b / (r + 1) - log(g) * b * r / (b0 * (r + 1))) 
             + l * b / (r + 1) -r * b * log(g) / (b0 * (r + 1)) - log(10 * r)),
    ”“”Eq2“”“    Eq(log(9 * r - r * l * b / (r + 1) - log(g) * b * r / (b0 * (r + 1))) 
             + l * b / (r + 1) -r * b * log(g) / (b0 * (r + 1)) - log(9 * r))
                            ), (l, 0, 10), (g, 0, 30))

![wrong](https://user-images.githubusercontent.com/24356676/27277616-cfaa3fa2-54ac-11e7-92b6-3c692eaa788f.png)
However, when I plot the Eq1 and Eq2 alone without Or() function it looks like this
![10 svg](https://user-images.githubusercontent.com/24356676/27277992-28628fd6-54ae-11e7-897e-12843a5baaac.png)
![9 svg](https://user-images.githubusercontent.com/24356676/27278006-2eb7ec8c-54ae-11e7-831f-abba544a6e19.png)

**Comment by wuyudi** [comment]
this problem seems fixed.
![image](https://user-images.githubusercontent.com/30024051/79121172-36658780-7d84-11ea-85ad-d51d3abd7c04.png)

**Comment by chaihahaha** [comment]
Thanks for your help!
