### ISSUE TITLE
Trouble finding roots

### ISSUE THREAD

**Issue by ayush1999** [sympy/sympy#12775]
`from sympy import *`
`expr=sqrt(2*I)`
`print(expr)`

This prints 
`(-1)**(1/4)*sqrt(2)`
which is actual same as expr.

**But, 1+I is the root of 2*I.
Shouldn't 1+I be the correct answer?**

**Comment by jksuom** [comment]
There some ongoing work on this: https://github.com/sympy/sympy/pull/12472.

**Comment by ayush1999** [comment]
@jksuom Also, Can we calculate line integrals or surface integrals using sympy?

**Comment by jksuom** [comment]
There is 'line_integrate` that computes the integral of a function along a curve. A ready-made function for surface integration does not seem to exist. One has to explicitly transform the surface integral to plane using a parametric representation.

**Comment by ayush1999** [comment]
@jksuom  Don't you think there should be a module for line, surface and volume integrals? I mean they are widely used throughout maths. It could maybe come under the vectors section.

**Comment by jksuom** [comment]
It has been one of the GSoC ideas: https://github.com/sympy/sympy/wiki/GSoC-2017-Ideas#implementation-of-vector-integration.

**Comment by smichr** [comment]
> There some ongoing work on this: #12472.

Handling of these sorts of roots is added to the last commit.

**Comment by oscarbenjamin** [comment]
I now get:
```julia
In [2]: from sympy import * 
   ...: expr=sqrt(2*I) 
   ...: print(expr)                                                                                                                                           
1 + I
```

Closing as fixed.
