### ISSUE TITLE
Documentation 'display' of '.is_number' function

### ISSUE THREAD

**Issue by gxyd** [sympy/sympy#12788]
In the documentation http://docs.sympy.org/dev/modules/core.html#sympy.core.expr.Expr.is_number , it should display `.is_number` normally, currently it is showing it with a subscript of 'n'. Also is the case with `if not self.free_symbols`, that should also be changed to display normally.

**Comment by vvanarasi** [comment]
Hi Gaurav,

Can i help to fix this documentation issue.

Thanks

**Comment by gxyd** [comment]
Sure go ahead with fixing it. You just need to replace the backticks ( \` \` ) at two places with single quotes. Visit file sympy/core/expr.py to modify the documentation of the function `.is_number`. And you can see the output by building the docs https://github.com/sympy/sympy/wiki/Writing-documentation#building-docs.
