### ISSUE TITLE
Idx should not require integer assumptions

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#12780]
```py
>>> n = symbols('n')
>>> Idx('i', (0, n))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "./sympy/tensor/indexed.py", line 585, in __new__
    raise TypeError("Idx object requires integer bounds.")
TypeError: Idx object requires integer bounds.
```

Requiring assumptions is an antipattern. It should only fail if `is_integer` if False.

**Comment by GuyInALabCoat** [comment]
Hi @asmeurer,

Going through the `Idx` docstring, it states that 

> Note: the ``Idx`` constructor is rather pedantic in that it only accepts
    integer arguments.  The only exception is that you can use ``-oo`` and
    ``oo`` to specify an unbounded range.  For all other cases, both label and
    bounds must be declared as integers, e.g. if ``n`` is given as an argument
    then ``n.is_integer`` must return ``True``.

Therefore it appears that you must declare your symbols as integers, in your case:

```python
n = symbol('n', integer=True)
```

in which case `Idx('i', (0, n))` will return i.

Is this the solution that you were looking for? If not could you guide me through a possible solution, as I'm fairly new to sympy.

**Comment by asmeurer** [comment]
Yes, this is the current behavior. But it should work with just `symbols('n')`. It should only check if `is_integer` if `False`, and not fail if it is `None`.
