### ISSUE TITLE
Computation Speed Regressions since 1.0

### ISSUE THREAD

**Issue by moorepants** [sympy/sympy#12793]
@bjodah and I maintain speed benchmarks for SymPy which can be viewed here:

http://www.moorepants.info/misc/sympy-asv/

There are a number of regressions since SymPy 1.0 that should likely be investigated before the next release.

Notable ones:

- CSE http://www.moorepants.info/misc/sympy-asv/#cse.TimeCSE.time_cse
- dsolve http://www.moorepants.info/misc/sympy-asv/#dsolve.TimeDsolve01.time_dsolve
- lambdify http://www.moorepants.info/misc/sympy-asv/#lambdify.TimeLambdifyEvaluate.time_lambdify_evaluate
- Memory usage http://www.moorepants.info/misc/sympy-asv/#large_exprs.TimeLargeExpressionOperations.peakmem_jacobian_wrt_functions
- determinants http://www.moorepants.info/misc/sympy-asv/#solve.TimeMatrixOperations.time_det
- rank http://www.moorepants.info/misc/sympy-asv/#solve.TimeMatrixOperations.time_rank
- rref http://www.moorepants.info/misc/sympy-asv/#solve.TimeMatrixOperations.time_rref
- solve http://www.moorepants.info/misc/sympy-asv/#solve.TimeMatrixSolve.time_solve
- lusolve http://www.moorepants.info/misc/sympy-asv/#solve.TimeMatrixSolve2.time_lusolve

**Comment by asmeurer** [comment]
CC @siefkenj. Most of these are related to the matrices.

**Comment by asmeurer** [comment]
`dsolve` regression says it is from [this commit](https://github.com/sympy/sympy/commit/b5257d1a), but that commit is completely unrelated to the odes module.

**Comment by asmeurer** [comment]
I'm also skeptical that https://github.com/sympy/sympy/commit/dca59315 is the real source of the lambdify slowdown.

**Comment by moorepants** [comment]
Note that not all commits have been run for all of the benchmarks, you may need to look at a range. But in the past I've occasionally found regressions where the commit didn't make sense. I'm not sure what to make of that.

**Comment by moorepants** [comment]
Yeah, the dsolve one makes no sense. I'll rerun that benchmark monday when I'm back in the office with the machine I run these on.

**Comment by siefkenj** [comment]
`Lambdify` should have about a 20% slowdown as of the most recent immutable matrix commits.  I'm not sure how to improve performance beyond this.  My guess is that it's something that changed in `Lambdify` and not the matrix module that causes the last 20% of the slowdown.  The separate issue for this is #12731.

I'm also confused why several of the matrix slowdowns seem to happen at PR #11337.

The determinant one I will have to investigate further.

**Comment by isuruf** [comment]
lambdify slowdown is because of https://github.com/sympy/sympy/pull/11468. (credits to @bjodah for figuring this out)

**Comment by asmeurer** [comment]
That PR changes the semantics of lambdify. Does the benchmark include 'numpy' in the modules?

**Comment by moorepants** [comment]
It doesn't: https://github.com/sympy/sympy_benchmarks/blob/master/benchmarks/lambdify.py

We would need to parameterize that benchmark with different module names I guess, to get a true reflection of speed changes.

**Comment by asmeurer** [comment]
If you want to reevaluate that PR, now's the time to do it. I still think it's a good idea, although I do have real use-cases for lambdifying to non-numpy.

**Comment by asmeurer** [comment]
I haven't heard from @siefkenj for a while. How do you suggest we go forward with the Matrix regressions? Are they significant enough that we should look into reverts for the release?

**Comment by moorepants** [comment]
My guess is that reverts would be rough, due to the amount of work that was put into refactoring. I don't suggest that but it would be nice if they were investigated. I know that some are due to improvements to accuracy in the solutions for the algorithms and we have to live with the slowdowns, but I'm not sure that all of them are.

**Comment by siefkenj** [comment]
I may have some time on Sunday to investigate some of them, but I am quite busy for the next month.

**Comment by asmeurer** [comment]
How bad are the slowdowns? Are they livable?

**Comment by isuruf** [comment]
> We would need to parameterize that benchmark with different module names I guess, to get a true reflection of speed changes.

Isn't the speed of the default method kind of important too?

**Comment by siefkenj** [comment]
I have looked through all the benchmarks listed here that seem to be to be related to matrices.  These are `time_det`, `time_rank`, `time_rref`, `time_solve`, and `time_lusolve`.  (Please point out if I should look at a benchmark I didn't mention).

`time_rank`, `time_rref`, `time_solve`, and `time_lusolve` are all slowed down by the new pivot searching algorithm.  I am sure that there is room for improvement in this algorithm, but it will never achieve the speed of the old (incorrect) algorithm.  A quick test is running 

```
Matrix([[8*tan(13*pi/45)/(tan(13*pi/45) + sqrt(3)),(-8*sqrt(3)*tan(13*pi/45)**2 + 24*tan(13*pi/45))/ (-3 + tan(13*pi/45)**2)],[1,-sqrt(3)]]).rank()
```

which returns the incorrect answer of `2` on sympy 1.0 and the correct answer on master.  If you look at the parameterized benchmarks for `rref` and `rank`, the second parameter is the number of symbols in the matrix.  When that is zero (and hence no assumptions need to be made), there is almost no slowdown in the algorithms.

`time_det` can be improved for dense matrices.  I implimented the algorithm for the Bareiss determinant (the default) recursively, which I think is easier to understand, but if need be, the old code for that algorithm can be copy-and-pasted into `_eval_det_bareiss` and the original speed should be restored.  Without reviewing it in detail though, it looks like I used the new pivot-search algorithm in the current implementation of `_eval_det_bareiss`, which makes me think there are cases where the old algorithm could return the wrong answer.

**Comment by moorepants** [comment]
Thanks @siefkenj. Sounds like we need to live with these speed regressions. Maybe it is worth opening an issue requesting speed improvements to those algorithms so that someone may try to improve them in the future.

So we can close this, since the only one that needs to be fixed is the cse one.

**Comment by asmeurer** [comment]
> Isn't the speed of the default method kind of important too?

The old default was `['math', 'mpmath', 'sympy']`. Actually, this is still used if `numpy` cannot be imported. If you want to test the old behavior, test against that. Personally I don't really like that, because it mixes things up in ways that rarely make sense, i.e., you get `math` (finite precision, C implementation, `float` return type) for common math functions, `mpmath` (arbitrary precision, Python implementation, `mpf` return type) for less common math functions, and `sympy` (arbitrary precision or symbolic answer, python implementation, `Float` return type) for other functions still. So depending on the input expression, the output is quite different.
