### ISSUE TITLE
Series expansion of polynomial/rational expression throws NotImplementedError with "trigonometric constants"

### ISSUE THREAD

**Issue by PrometheusPi** [sympy/sympy#12791]
While trying to perform a series expansion on an expression containing trigonometric functions, independent of the variable used for the series expansion, I ran into a `NotImplementedError` error. 
(As shown below, this could be avoided by substituting the trigonometric functions. - Thus sympy is (in general) capable of performing the series expansion but unable to perform it with these functions included.)
```python
from sympy import *

x,y = symbols('x y', reals=True)
beta = symbols('beta', reals=True, positive=True)
theta, phi = symbols('theta varphi', reals=True)

expr = (-beta**2*phi*sin(theta) + beta**2*cos(theta) + beta*phi*sin(theta) - beta*cos(theta) - beta + 1)/(beta*cos(theta) - 1)**2

expr.series(beta, 0.5, 2)
# --> causes NotImplementedError
```

The same error occurs for simplified (by hand) form of the expression: 
```python
# this is equivalent to expr
expr2 = (beta**2*(cos(theta)-phi*sin(theta)) - beta* (cos(theta)-phi*sin(theta)) + 1)/(beta*cos(theta) - 1)**2

expr2.series(beta, 0.5, 2)
# -> fails too
```

However, from that form, the following substitution is obvious. 
*Substitute:*
 - `x` = `cos(theta)-phi*sin(theta)`
 - `y` = `cos(theta)`

Performing this substitution then avoids the error during the series expansion. 
```python
expr3 = expr2.subs(cos(theta) - phi*sin(theta), x).subs(cos(theta), y)
expr3_series = expr3.series(beta, 0.5, 2)
# --> does not fail
result = expr3_series.subs(x, cos(theta) - phi*sin(theta)).subs(y, cos(theta))
```

**Questions:**
What causes this error?  
What would be a (simple) workaround for expressions where such "playing around with substitutions" is not as easy? 
Is this something that should be fixed in upcoming versions?

(I will try to come up with a shorter expression to trigger the error.)

I am using:
 - python 3.4.3 (build with gcc 4.9.2)
 - sympy 1.0

**Comment by skirpichev** [comment]
BTW, I think this is fixed in the [diofant](https://github.com/diofant/diofant/).  Following result was verified with Mathematica. 

```
In [16]: x, y = symbols('x y', real=True)
In [17]: beta = symbols('beta', real=True, positive=True)
In [18]: theta, phi = symbols('theta varphi', real=True)
In [19]: expr = (-beta**2*phi*sin(theta) + beta**2*cos(theta) + beta*phi*sin(theta) - beta*cos(theta) - beta + 1)/(beta*cos(theta) - 1)**2
In [20]: expr.series(beta, 0.5, 2)
Out[20]: 
                                                                          ⎛                                                                             2   
             0.5                         0.25⋅cos(θ)                      ⎜              0.5⋅varphi⋅sin(θ)⋅cos(θ)                                0.5⋅cos (θ)
───────────────────────────── - ───────────────────────────── + (β - 0.5)⋅⎜- ─────────────────────────────────────────────── + ─────────────────────────────
        2                               2                                 ⎜           3              2                                  3              2    
0.25⋅cos (θ) - 1.0⋅cos(θ) + 1   0.25⋅cos (θ) - 1.0⋅cos(θ) + 1             ⎝  0.125⋅cos (θ) - 0.75⋅cos (θ) + 1.5⋅cos(θ) - 1.0   0.125⋅cos (θ) - 0.75⋅cos (θ) 

                                                                                                    ⎞                                                       
                                        1.0⋅cos(θ)                                   1              ⎟         0.25⋅varphi⋅sin(θ)         ⎛         2        
────────────────── - ─────────────────────────────────────────────── - ─────────────────────────────⎟ + ───────────────────────────── + O⎝(β - 0.5) ; β → 0.
                              3              2                                 2                    ⎟           2                                           
+ 1.5⋅cos(θ) - 1.0   0.125⋅cos (θ) - 0.75⋅cos (θ) + 1.5⋅cos(θ) - 1.0   0.25⋅cos (θ) - 1.0⋅cos(θ) + 1⎠   0.25⋅cos (θ) - 1.0⋅cos(θ) + 1                       

  
 ⎞
5⎠
```

But I'm not sure about your "simplified (by hand)" expressions, @PrometheusPi, ``expr2`` produce a different (not equivalent) output.

**Comment by sachin-4099** [comment]
On the current master:
This no longer raises `NotImplementedError`. And most probably the result produced is also correct.

**Comment by PrometheusPi** [comment]
@sachin-4099 Thanks for the update

**Comment by sachin-4099** [comment]
This issue only needs a test in order to be closed.

**Comment by abhaydhiman** [comment]
@sachin-4099 can you tell me where this Testcase should be added?

**Comment by sachin-4099** [comment]
> @sachin-4099 can you tell me where this Testcase should be added?

Add the testcase to `series/test_series.py'.

**Comment by abhaydhiman** [comment]
Thanks, I am on it.
