### ISSUE TITLE
Missing parentheses in LaTeX output

### ISSUE THREAD

**Issue by jamesluke** [sympy/sympy#12799]
The LaTeX output of `diff(sin(x)+cos(x), x, x))` is missing parentheses, producing incorrect output. The output looks like `-sin(x) + cos(x)`, instead of the correct `-(sin(x) + cos(x))`. The internal representation is correct.

The output of repr(...) is `'-(sin(x) + cos(x))'`
The output of srepr(...) is `"Mul(Integer(-1), Add(sin(Symbol('x')), cos(Symbol('x'))))"`
The (incorrect) output of latex(...) is `'- \\sin{\\left (x \\right )} + \\cos{\\left (x \\right )}'`

![screenshot](https://user-images.githubusercontent.com/5475226/27505716-52ecaa1a-585b-11e7-9b19-342e3ea12c53.png)

**Comment by asmeurer** [comment]
I believe this is fixed in master

```
>>> latex(diff(sin(x)+cos(x), x, x))
'- (\\sin{\\left (x \\right )} + \\cos{\\left (x \\right )})'
```
