### ISSUE TITLE
Deprecated PythonPrinter

### ISSUE THREAD

**Issue by bjodah** [sympy/sympy#12807]
The current `PythonPrinter` assumes that SymPy functions and classes are available in the global namespace. I will rename this class to `SymPyPrinter` and in another module create a `PyPrinter` which outputs python code (no dependency on SymPy), we can then subclass `PyPrinter` to have a `NumPyPrinter`. I intend to develop these printers together with `.codegen.ast` module.

Related issue: gh-12213

**Comment by moorepants** [comment]
My guess is that noone uses the `PythonPrinter`. Instead of `PyPrinter` I'd keep the `PythonPrinter` name for the new "correct" Python printer.
