### ISSUE TITLE
Replace 3.5 builds in Travis with 3.6

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#12814]
The builds that are just Python 2.7 and 3.5 should be changed to 2.7 and 3.6. We will need to find a 3.6 build of tensorflow to install. Otherwise this is easy to fix.

**Comment by firedranzer** [comment]
Hi @asmeurer .I want to work on this issue please help me with the changes.

**Comment by asmeurer** [comment]
Modify the .travis.yml and see if the builds fail. It may be useful to enable Travis on your fork so that you don't have to wait for the SymPy Travis pull request queue.
