### ISSUE TITLE
lgtm issue identified in translate

### ISSUE THREAD

**Issue by smichr** [sympy/sympy#12828]
I checked out an lgtm issue with translate. It appears to be valid. It also appears to me that this is tested in the docstring. I don't know how it is passing the docstring. Can anyone else confirm this:

```
in utilities.misc.translate,

s = s.translate(maketrans('', '', c))  should be s = s.translate(maketrans('', ''), c)
```

This should fail under Py3 if it traverses that line (shouldn't it?):

```
assert translate('abc','ab','bc','c') == 'bc'

**Comment by smichr** [comment]
maketrans can take 3 args in Py3. This is a false positive report from lgtm, @rneatherway

**Comment by rneatherway** [comment]
Hi @smichr, you're quite right about maketrans. The check for Python version ([here](https://lgtm.com/projects/g/sympy/sympy/snapshot/71767d18fb67e6317c77a0161dc63c8a33e8a308/files/sympy/utilities/misc.py#L351)) is quite non-standard, so the analysis isn't able to determine what the `if py3` guard really means. I'll put up a PR that changes the check to a more standard technique, and the alert should then be resolved.
