### ISSUE TITLE
Float(prec=...) is deprecated

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#12820]
Previously, the argument to the `Float` constructor to set the decimal precision was called `prec`. However, everywhere else in SymPy, `prec` means binary precision, whereas `dps` means decimal precision.

To change this behavior, the Float constructor is now `Float(num, dps=None, prec=None, precision=None)`. The decimal precision can still be passed as the second argument, like `Float(1.0, 100)`. What is deprecated is explicitly calling the argument `prec`. To set the decimal precision, use `dps`. To set the binary precision, use `precision`. 

In a future version of SymPy, `prec` will be removed. Or, I don't know if this was decided, we may instead remove `precision` and make `prec` act as the binary precision, which would match the rest of SymPy. 

The PR that implemented this was https://github.com/sympy/sympy/pull/12227.

**Comment by cbm755** [comment]
> The precision can still be passed as the second argument, like Float(1.0, 100)

@asmeuer, to avoid ambiguity, I think that should say: "As before, the decimal precision can still be passed as the second argument, ..."?
