### ISSUE TITLE
lgtm: meijerint arg count mismatch

### ISSUE THREAD

**Issue by smichr** [sympy/sympy#12831]
In [function E(z)](https://github.com/sympy/sympy/blob/master/sympy/integrals/meijerint.py#L1348) should this
```
        return And(*[statement(a - 1, 0, z) for a in g.an]) 
```
be this
```
        return And(*[statement(a - 1, 0, 0, z) for a in g.an]) 
```

If anyone has access to reference "[L] Luke, Y. L. (1969), The Special Functions and Their Approximations, Volume 1", a search of section 5.10 may be profitable as I think that is where you will find reference to the E(z) function.

**Comment by firedranzer** [comment]
Hi @smichr . I want to work on this issue . I am a newcomer to this organisation. Help me with this issue.

**Comment by smichr** [comment]
A good place to start is [here](https://github.com/sympy/sympy/wiki/Development-workflow). When you are ready, this is an easy edit in the code base. As I recall, it is in hyperexpand. Search for it, modify it, save it, and commit it to a new branch of master that you already created, then open the PR. *BUT* the thing that makes this tricky is that unless you have a test for that line of code and you know the answer, you won't know if it's right. You or someone will have to decide on a good test for that particular line of code. (The tests go in the appropriate file in the "test" folder in the folder that contains "hyperexpand.py".

**Comment by firedranzer** [comment]
It is hard to figure out a test case for this issue . @smichr help me in deciding test for this change.

**Comment by smichr** [comment]
The code near this change is:

```python
# There are two cases. If p >= q, we can directly use a slater expansion 
1338     # like [L], 5.2 (11). Note in particular that the asymptotics of such an 
1339     # expansion even hold when some of the parameters differ by integers, i.e. 
1340     # the formula itself would not be valid! (b/c G functions are cts. in their 
1341     # parameters) 
1342     # When p < q, we need to use the theorems of [L], 5.10. 
1343 
 
1344     if p >= q: 
1345         _debug('  Using asymptotic Slater expansion.') 
1346         return And(*[statement(a - 1, 0, 0, z) for a in g.an]) 
1347 
 
1348     def E(z): 
1349         return And(*[statement(a - 1, 0, 0, z) for a in g.an]) 
1350 
 

1360     # [L], section 5.10 
1361     conds = [] 
1362     # Theorem 1 
1363     conds += [And(1 <= n, p < q, 1 <= m, rho*pi - delta >= pi/2, delta > 0, 
1364                   E(z*exp(I*pi*(nu + 1))))] 
```

So the asymptotic expansion result is valid when p >= q while the only line that uses E() comes at line 1363. The conditions there require that n >= 1, p< q, m >=1, rho*pi-delta >= pi/2 and delta > 0. Then `E(zz)` is called where `zz=z*exp(I*pi*(nu+1))` and E(zz) will tell when zz converges. The result does not depend on b or c:

```
>>> x = z
>>> statement(a, b, c, zz)
Re(a) <= -1
```
