### ISSUE TITLE
sympify the symbol 'S'

### ISSUE THREAD

**Issue by bad-ants-fleet** [sympy/sympy#12835]
Hi, 
I use sympify a lot to rewrite autogenerated formulas in a nicer way:
```python
>> sympy.sympify('-k1 * e110 * Im1a + -k6 * Im1a * Gm4 + k7 * e119 * Fm1')
Fm1 * e119 * k7 - Gm4 * Im1a * k6 - Im1a * e110 * k1
```
but I realized that I cannot use the variable name "S", as it is interpreted as the SingletonRegistry
```python
>> sympy.sympify('S + A')
raises:
TypeError: unsupported operand type(s) for +: 'SingletonRegistry' and 'Symbol'
```
I haven't found this problem described anywhere, looks like a bug to me.

cheers,
Stefan

**Comment by cbm755** [comment]
I think this is documented in the help: see `sympify?`:
````
The sympification happens with access to everything that is loaded
by ``from sympy import *``; anything used in a string that is not
defined by that import will be converted to a symbol. 
````
Later there is an example involving `O` and maybe a workaround.

So it seems this is in the intended behaviour, but reopen if I've missed something.

**Comment by bad-ants-fleet** [comment]
awww.. you are absolutely right:

> from sympy.abc import _clash1
> sympify('S + A', _clash1)
A + S

thank you, didn't see that!
