### ISSUE TITLE
support for real set

### ISSUE THREAD

**Issue by max-yue** [sympy/sympy#12867]
if I have a latex expression \[x \in R\], that means x belongs to a real set, but I could not find class RealSet? could you please add support for real set.

**Comment by gxyd** [comment]
We do have support for a set of real numbers. You can use `S.Reals`, i.e. `x in S.Reals`, which will return a bool value or an error accordingly.

**Comment by asmeurer** [comment]
Use `Contains(x, Reals)` to represent `x \in R` symbolically.
