### ISSUE TITLE
tensorflow lambdify tests fail with latest version of tensorflow

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#12863]
```
_______ sympy/utilities/tests/test_lambdify.py:test_tensorflow_piecewise _______
  File "/home/sympy/sympy/utilities/tests/test_lambdify.py", line 525, in test_tensorflow_piecewise
    assert func(a).eval(session=s, feed_dict={a: -1}) == -1
  File "<string>", line 1, in <lambda>
NameError: name 'select' is not defined
```

They work with tensorflow 0.9.0, which is what is used on Travis. Seems to fail with tensorflow 1.0 and greater.

**Comment by asmeurer** [comment]
In the older version the tests give this warning: 

```WARNING:tensorflow:From /home/sympy/sympy/utilities/tests/test_lambdify.py:505 in test_tensorflow_variables.: initialize_all_variables (from tensorflow.python.ops.variables) is deprecated and will be removed after 2017-03-02.
Instructions for updating:
Use `tf.global_variables_initializer` instead.
```

Perhaps related?

**Comment by ixjlyons** [comment]
It seems there were enough breaking changes introduced with TensorFlow 1.0 to warrant [migration docs](https://www.tensorflow.org/install/migration). In this case, `select` just needs to be changed to `where`. *Both* actually seem to work with 0.12.1, which is the oldest version on PyPI.

**Comment by asmeurer** [comment]
Should we try to support old and new or just new? I don't know which versions are used in the wild.
