### ISSUE TITLE
No support for approx

### ISSUE THREAD

**Issue by max-yue** [sympy/sympy#12875]
I have latex \[e \approx 2.718\], which means e approx 2.718, please add support for that? Thank you.

**Comment by bjodah** [comment]
Just subclass `Eq`:
```
>>> class Approx(Eq):
...     def _latex(self, printer):
...         return r'%s \approx %s' % (printer._print(self.lhs), printer._print(self.rhs))
...
>>> e = Symbol('e')
>>> expr = Approx(e, 2.718)
>>> print(latex(expr))
e \approx 2.718
```

**Comment by ungung** [comment]
from sympy import Approx, and it could not work, could you please tell me how to import this ?

**Comment by asmeurer** [comment]
You could also use `Contains` and an `Interval` or an `And` with inequalities to represent the approximation precisely.
