### ISSUE TITLE
Eq with Poly object immediately evaulates to False

### ISSUE THREAD

**Issue by user234683** [sympy/sympy#12873]
```
>>> Eq(Poly((x-1)*(x-2),x),0)
False
```
```
>>> Eq((x-1)*(x-2),0)
Eq((x - 2)*(x - 1), 0)
```
This happens because in the `Equality` class, this code calls `is_zero` on the `Poly`:
```python
if all(isinstance(i, Expr) for i in (lhs, rhs)):
    # see if the difference evaluates
    dif = lhs - rhs
    z = dif.is_zero
    if z is not None:
        if z is False and dif.is_commutative:  # issue 10728
            return S.false
        if z:
            return S.true
```
And `is_zero` in `Poly` returns `True` if the poly is a zero-polynomial, and `False` if it's not, rather than returning whether it is *equal* to 0, which it still might be depending on the variables even if it's not a zero polynomial. I think this is an accidental name-collision.

Note: This bug doesn't reveal itself in the 1.0 release because `Equality` checks `if lhs.is_complex and rhs.is_complex`, which always gives `None`, before calling `is_zero`

**Comment by user234683** [comment]
I'd say `Poly.is_zero` should be renamed to `Poly.is_zero_poly`

**Comment by jksuom** [comment]
Please note that `(x - 1)*(x - 2)` and `p = Poly((x - 1)*(x - 2), x)` are different kinds of objects. The former is an expression that can be considered as a polynomial function of the symbol `x`. The latter is an element of a polynomial ring, and the natural meaning of equation `Eq(p, 0)` is that `p` is the zero element of the ring. The corresponding equation where `p` is regarded as a function can be written `Eq(p.as_expr(), 0)`.

**Comment by user234683** [comment]
Ah ok. Perhaps the documentation should clarify this, because I was thinking of Poly objects as a more efficient representation of polynomial expressions with specialized methods and as interchangeable with expressions, rather than a different kind of mathematical object.

But I'm still a bit confused. 
```
>>> Eq(Poly(x**2+1,x), x**2+1)
True
```
Shouldn't this evaluate to False, since " x**2+1 " isn't part of a polynomial ring? Or what if it is, and x is actually Poly( x - 1, x) for instance?
```
Eq( Poly(x**2 + 1, x),  Poly(x**2 - 2*x + 2, x) )
```
Would this be false?

**Comment by jksuom** [comment]
I agree that documentation is incomplete. One often has to read the code to see what to expect.
In the case of `Eq(Poly(x**2 + 1,x), ...)`, SymPy will try to make a `Poly` out of the right hand side before carrying out the comparison. (I suppose the idea is to make the method more 'user friendly'.)  

It should probably be pointed out in the documents that this way of treating `Eq` can make it asymmetric. The result may be different if the two arguments are interchanged.

 If `x` denotes a polynomial, then `Poly(x**2 - 2*x + 2, x)` is a polynomial whose generator is also a polynomial. There is no support in SymPy for that type of polynomials. Instead, `Poly(x**2 - 2*x + 2, Symbol("x"))` (or `Poly(x**2 - 2*x +2)`) should be used.

**Comment by user234683** [comment]
I think I've figured it out. So Poly objects are functions with named arguments ('generators'), rather than arguments referenced by order.
Typically, if you have f(x) = 3x and g(y) = 5y, then (g + f)(x) = 8x, since the x and y in those definitions simply act as binding variables and have no meaning outside the definition (the "for all" is implicit). But with Poly objects f and g, it's rather like (using Python dictionary syntax):
f("x": a) = 3a for all a
g("y": b) = 5b for all b
(f + g) would then be a function with two named parameters, "x" and "y", so
(f + g)("x":a, "y":b) = 3a + 5b for all a, b

Typical ordered functions could be written this way as well, but with a number as the named argument indicating the ordering, rather than a string.
f(x, y, z) = 3x + 2y + 8z for all x,y,z
could be written
f(0:x, 1:y, 2:z) = 3x + 2y + 8z for all x,y,z

Is my understanding correct here? If so, you can close this issue, unless you want to use it as a documentation issue.

**Comment by jksuom** [comment]
It think your understanding is essentially correct. Technically, Poly objects are collections of coefficients coupled with a list of labels called generators. So, strictly speaking, they are not functions, but it is possible to associate them with functions in the way you described.

I think this can be closed.
