### ISSUE TITLE
Latex output fails for superscript variables raised to a power

### ISSUE THREAD

**Issue by coderofgames** [sympy/sympy#12886]
using superscripts for coordinates like $$x^i$$ causes the latex to fail to print math (in jupyter notebooks) when the coordinate is raised to a power - it prints x^{1}^{2} for the case $$x^1$$ squared, I think it should use round brackets $$(x^{1})^2$$ instead.

**Comment by firedranzer** [comment]
Hey @moorepants I want to take this issue . Any help regarding the same would be great.

**Comment by moorepants** [comment]
You should investigate the latex printer and see how it prints exponents. I suggest writing a test case first from @coderofgames's description.

**Comment by vedantc98** [comment]
I would like to take up this issue but the description seems unclear, maybe a code sample would help?

**Comment by vedantc98** [comment]
I've identified the issue, can I take it up?

**Comment by coderofgames** [comment]
test case, environment is jupyter notebook with latex printing enabled, sympy imported too:

L__1, M__1 = symbols('L__1, M__1')
a = L__1* L__1
b =M__1*M__1
a+b

**Comment by coderofgames** [comment]
If the above example works, try more complicated examples, and also try using 
L__1**2 with more complicated expressions, it always crashes on my home PC, and prints badly on notebook viewer and github (with the superscript and power being unclear)

**Comment by moorepants** [comment]
@firedranzer and @vedantc98 anyone can take up this issue.
