### ISSUE TITLE
integrate(f(x, y).diff(x), y) is wrong

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#12899]
```py
>>> integrate(f(x, y).diff(x), y)
y*Derivative(f(x, y), x)
```

It is acting as if `f(x, y).diff(x)` does not depend on `y`.

**Comment by smichr** [comment]
For anyone else pondering why this isn't true, consider `f(x, y) = x*y` where `f(x, y).diff(x) = y` whereas when `f(x,y) = x + y`, `f(x, y).diff(x)` is independent of y (and is 1).

**Comment by ayush1999** [comment]
@asmeurer @smichr I'd like to work on this issue. Can you tell me where to start?

**Comment by 2torus** [comment]
@asmeurer @smichr @ayush1999 There is more:
`>>> integrate(f(x,y).diff(x).diff(y),x)
`
`
x*Derivative(f(x, y), x, y)
`
Worse still, in [test_manual, line 184](https://github.com/sympy/sympy/blob/master/sympy/integrals/tests/test_manual.py#L184)
`
assert manualintegrate(Derivative(x**2 + 2*x + 3, y), x) ==  x * Derivative(x**2 + 2*x + 3, y)
`
I'll post a pull request once the tests pass.

**Comment by gxyd** [comment]
Fixed by #12971 . Closing this issue.
