### ISSUE TITLE
Unit information not readily accessible in Quantity()

### ISSUE THREAD

**Issue by schymans** [sympy/sympy#12892]
There is no obvious way to get to the actual units of a quantity:
```
>>> M = Quantity("solar_mass", mass, 1.9891e30*kilogram)
>>> print(M.atoms())
set([solar_mass, M, mass, solar_mass, 1.98910000000000e+33])
```
It looks like the value in `atoms()` refers to grams, but why and how can I get to this information? Do I need to use `print M.convert_to(kilogram)`? But if I want to convert all quantities in an expression to their base units, I need to be able to enquire what their base units are, but I have not found a dictionary of base units for each dimension. Should this be a separate Issue?

**Comment by jirikuncar** [comment]
@schymans IMHO the units are relevant only in a chosen unit system (e.g. `SI`).

```python
>>> M = Quantity("solar_mass", mass, 1.9891e30*kilogram)
>>> SI.print_unit_base(M)
1.9891e+30*kilogram
```

**Comment by schymans** [comment]
Yes, the value given in the definition of `M` is stored as a scale factor and we can convert to any matching units, e.g.:
```
from sympy.physics.units import convert_to
convert_to(M, kilogram)

1.9891e+30*kilogram
```
I'll close the issue.
