### ISSUE TITLE
Argument is not an mpz

### ISSUE THREAD

**Issue by FabricioS** [sympy/sympy#12895]
On some platforms (debian sid, with sympy 1.0, gmpy2 2.0.8), I got troubles with operations on some sympy objects (numbers, matrices, etc...). Here is the minimal example that I could produce :

```
$ python3
Python 3.5.3+ (default, Jun  7 2017, 23:23:48) 
[GCC 6.3.0 20170516] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sympy as sy
>>> a = sy.Matrix(([0, 1], [1., 0]))
>>> a[1,0]._mpf_
(0, mpz(1), 0, 1)
>>> a+a
Matrix([
[  0, 2],
[2.0, 0]])
>>> import copy
>>> b = copy.deepcopy(a)
>>> b[1,0]._mpf_
(0, 1, 0, 1)
>>> b+b
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/sympy/core/decorators.py", line 118, in binary_op_wrapper
    return func(self, other)
  File "/usr/lib/python3/dist-packages/sympy/matrices/dense.py", line 539, in __add__
    return super(DenseMatrix, self).__add__(_force_mutable(other))
  File "/usr/lib/python3/dist-packages/sympy/matrices/matrices.py", line 579, in __add__
    ret[i] = [j + k for j, k in zip(alst[i], blst[i])]
  File "/usr/lib/python3/dist-packages/sympy/matrices/matrices.py", line 579, in <listcomp>
    ret[i] = [j + k for j, k in zip(alst[i], blst[i])]
  File "/usr/lib/python3/dist-packages/sympy/core/decorators.py", line 77, in __sympifyit_wrapper
    return func(a, b)
  File "/usr/lib/python3/dist-packages/sympy/core/numbers.py", line 930, in __add__
    return Float._new(mlib.mpf_add(self._mpf_, rhs, prec, rnd), prec)
  File "/usr/lib/python3/dist-packages/mpmath/libmp/libmpf.py", line 753, in mpf_add
    return normalize(ssign, man, texp, bc, prec or bc, rnd)
TypeError: argument is not an mpz

```

The (deep)copy loses the correct type of the mantrissa for the floating value of the matrix. The error does not occur for Zeros, Ones, Rationale and Integer instances.

This is the cause of the troubles mentioned in 
https://groups.google.com/forum/#!topic/sympy/d0zjnsUe0ks
https://github.com/afalaize/pyphs/issues/26

Where should it be fixed ?
-> in gmpy introducing some tolerance in the normalize function ?
-> in sympy, fixing the way the objects are copied ?
-> in the copy module ?

**Comment by casevh** [comment]
I have committed a fix to both gmpy2 master (which will become version 2.1.0) and the gmpy2-2.0.9 maintenance branch. This should work around the issues where code in sympy does not use the MPZ type declared in mpmath when creating mpf instances.

**Comment by asmeurer** [comment]
When will 2.0.9 be released? Is it still making a patch worth working around this for the SymPy 1.1.1 bug fix release?

**Comment by casevh** [comment]
I hope to release gmpy2 2.0.9 within a few weeks. I plan to release 2.1.0a1 first but I would only use that for testing. The mpmath code is stable but there have been many changes for real and complex numbers

Since many users have difficulties compiling a new version of gmpy2, I think including a patch in SymPy 1.1.1 bug fix release would be helpful for them.

**Comment by asmeurer** [comment]
What is the correct way to patch this? Can we just wrap some more places in MPZ, or should we try to fix deepcopy?

**Comment by richardotis** [comment]
@asmeurer Can we use the open PR https://github.com/sympy/sympy/pull/10674 to fix this issue, and use the minimal example above as the test?

**Comment by casevh** [comment]
The bug is triggered by manually created an `mpf` instance without using
MPZ() around `man`. I took a quick look in the code recently and didn't
find any other instances but there may be others.

Apologies but I have very little time available... :(
