### ISSUE TITLE
(1/x).evalf(subs={x: 0}) gives 0

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#12904]
```
>>> (1/x).evalf(subs={x: 0})
0
```

**Comment by orbisvicis** [comment]
Valid for sympy-1.0 and sympy-1.1-58-gd250ff0

**Comment by smichr** [comment]
duplicates #8242

**Comment by asmeurer** [comment]
Ah, I didn't find it because I was looking for issues with the wrong result label.

**Comment by asmeurer** [comment]
Duplicate of #8242

**Comment by asmeurer** [comment]
(FYI https://github.com/blog/2398-manage-issues-and-pull-requests-with-keyword-updates)
