### ISSUE TITLE
sympy/core/tests/test_sympify.py failure on 32-bit systems

### ISSUE THREAD

**Issue by jamesjer** [sympy/sympy#12902]
I maintain the sympy package for Fedora.  I just tried to build the 1.1 release.  The build succeeds on 64-bit builders, but on 32-bit builders (such as ARM), test_numpy in sympy/core/tests/test_sympify.py fails:

________________________________________________________________________________
_________________ sympy/core/tests/test_sympify.py:test_numpy __________________
  File "/builddir/build/BUILD/sympy-1.1/sympy-sympy-1.1/sympy/core/tests/test_sympify.py", line 592, in test_numpy
    Float(1.123456789123, precision=80))
AssertionError
===== tests finished: 1117 passed, 1 failed, 24 skipped, in 241.14 seconds =====
DO *NOT* COMMIT!
/usr/lib64/python2.7/site-packages/numpy/core/machar.py:127: RuntimeWarning: overflow encountered in add
  a = a + a
/usr/lib64/python2.7/site-packages/numpy/core/machar.py:129: RuntimeWarning: invalid value encountered in subtract
  temp1 = temp - a
/usr/lib64/python2.7/site-packages/numpy/core/machar.py:138: RuntimeWarning: invalid value encountered in subtract
  itemp = int_conv(temp-a)
/usr/lib64/python2.7/site-packages/numpy/core/machar.py:162: RuntimeWarning: overflow encountered in add
  a = a + a
/usr/lib64/python2.7/site-packages/numpy/core/machar.py:164: RuntimeWarning: invalid value encountered in subtract
  temp1 = temp - a
/usr/lib64/python2.7/site-packages/numpy/core/machar.py:171: RuntimeWarning: invalid value encountered in subtract
  if any(temp-a != zero):

This run does not show it, but on some 32-bit architectures, we have also seen a failure of test_numpy due to line 564, where python complains that the constant is too large to fit into a python integer:

assert equal(sympify(np.int_(1234567891234567891)), S(1234567891234567891))

**Comment by asmeurer** [comment]
I can reproduce the latter with my Mac system Python 2.7 (`PYTHONPATH=../mpmath/ arch -i386 /Library/Frameworks/Python.framework/Versions/2.7/bin/python2.7 bin/test sympify`):

```
  File "/users/aaronmeurer/documents/python/sympy/sympy/sympy/core/tests/test_sympify.py", line 564, in test_numpy
    sympify(np.int_(1234567891234567891)), S(1234567891234567891))
OverflowError: Python int too large to convert to C long
```

But when I comment out that assert (and another like it), I don't get the other failure. 

The test in question catches AttributeError to try to guard against this, but apparently a different error is given instead? 

What do you get when you run `sympify(np.float128(1.123456789123) ==  Float(1.123456789123, precision=80)`  in your 32-bit Python (with SymPy 1.1)?

**Comment by asmeurer** [comment]
Fixed the one issue at https://github.com/sympy/sympy/pull/12909.

**Comment by bjodah** [comment]
Why do the paths start with `/usr/lib64` on 32-bit systems? Sounds like the machines may have improper configurations.

I can reproduce the integer overflow error on i386 and armv7:
```
       assert equal(
            sympify(np.int_(1234567891234567891)), S(1234567891234567891))
E       OverflowError: Python int too large to convert to C long
```

but not the floating point error.

**Comment by asmeurer** [comment]
I was thinking, maybe the version of NumPy affects it?

**Comment by bjodah** [comment]
Could be, I could test against a specific version

**Comment by asmeurer** [comment]
1.1.1 was released and I haven't heard anything further about this. If there are still issues, please open a new issue.
