### ISSUE TITLE
`autowrap` compilation fails when setting `tempdir`

### ISSUE THREAD

**Issue by uweschmitt** [sympy/sympy#12939]
This is my setting:

```
$ python -V
Python 2.7.10

$ pip freeze
Cython==0.25.2
mpmath==0.19
numpy==1.13.1
sympy==1.1
```
The following code fails on my machine:
```
# encoding: utf-8
from __future__ import print_function, division, absolute_import

from sympy import Symbol
from sympy.utilities.autowrap import autowrap

x = Symbol("x")
y = Symbol("y")

exp1 = x + y
exp2 = x * y

tmpdir = "./tmp"

fun1 = autowrap(exp1, args=(x, y), tempdir=tmpdir)
fun2 = autowrap(exp2, args=(x, y), tempdir=tmpdir)

print(fun1(1, 2), fun2(1, 2))
```

with the following traceback:
```
Traceback (most recent call last):
  File "test.py", line 15, in <module>
    fun1 = autowrap(exp1, args=(x, y), tempdir=tmpdir) # , backend="cython")
  File "/Users/uweschmitt/tmp/venv_sympy_bug/lib/python2.7/site-packages/sympy/core/cache.py", line 93, in wrapper
    retval = cfunc(*args, **kwargs)
  File "/Users/uweschmitt/tmp/venv_sympy_bug/lib/python2.7/site-packages/sympy/core/compatibility.py", line 809, in wrapper
    result = user_function(*args, **kwds)
  File "/Users/uweschmitt/tmp/venv_sympy_bug/lib/python2.7/site-packages/sympy/utilities/autowrap.py", line 632, in autowrap
    return code_wrapper.wrap_code(routine, helpers=helps)
  File "/Users/uweschmitt/tmp/venv_sympy_bug/lib/python2.7/site-packages/sympy/utilities/autowrap.py", line 148, in wrap_code
    mod = __import__(self.module_name)
ImportError: No module named wrapper_module_0
```

The folder  `./tmp` exists, is empty and writable before I run the code. 

After the error happens `./tmp` contains the compiled files. I also can `cd tmp` and run `python -c "import wrapper_module_0"` without errors.

I get no errors and correct results if I modify `tempdir = "./tmp"`  to `tempdir = "."` or `tempdir = None`.

**Comment by moorepants** [comment]
I am not able to reproduce this. What operating system are you using?

**Comment by bjodah** [comment]
I can reproduce this on Ubuntu 16.04

**Comment by uweschmitt** [comment]
I use Mac OS X 11.6

**Comment by ixjlyons** [comment]
This is strange. I am able to reproduce this by running a script, but I used a relative path for `tempdir` in the codegen tutorial materials and it worked fine. I can actually run the script (which fails), then afterward open an interpreter and manually add the relative directory to the path and import using the name of the generated module and it works fine. @bjodah's fix works for me.

**Comment by uweschmitt** [comment]
Surprisingly it works if I run the script using `python -m pdb test_script.py`.
