### ISSUE TITLE
rref() issue 

### ISSUE THREAD

**Issue by ritchieng** [sympy/sympy#12933]
Given this matrix

A = [
    [-3, 6, -1, 1, -7],
    [1, -2, 2, 3, -1],
    [2, -4, 5, 8, -4]
]

If you run rref() it would return 
```
Matrix([
[1.0, -2.0,   0, -1.0,   0, 0],
[  0,    0, 1.0,  2.0,   0, 0],
[  0,    0,   0,    0, 1.0, 0]])
```
This is wrong. There's suppose to be only 2 pivots if you manually handle this compared to 3 pivots here.

**Comment by jksuom** [comment]
I seem to get only 2 pivots:
```
In [5]: print(A.rref())
(Matrix([
[1, -2, 0, -1,  3],
[0,  0, 1,  2, -2],
[0,  0, 0,  0,  0]]), (0, 2))
```
There are no floating point numbers either. I suspect that the wrong result is caused by rounding errors in floating point computations. It floats are used, then the zero detection function `iszerofunc` should consider very small numbers equal to zero and not make them pivots.

**Comment by ritchieng** [comment]
Thanks for the prompt reply. Yes it works if we feed in a nested list. 

However I fed it through a numpy array. 

```
A = [
[-3, 6, -1, 1, -7],
[1, -2, 2, 3, -1],
[2, -4, 5, 8, -4]
]
```

`A = np.array(A)`

Even with 

`A = np.array(A).astype(int)`

It doesn't seem to work. Any idea?

**Comment by bjodah** [comment]
@ritchieng are you using the latest version of SymPy? Could you provide complete to code to reproduce the error? (I can't reproduce it)

**Comment by ritchieng** [comment]
@bjodah My sincere apologies. You're right about the version. I was using 1.0 and upgraded to 1.1 and it was fixed. Thanks for the heads up.
