### ISSUE TITLE
geometry intersection is too restrictive

### ISSUE THREAD

**Issue by smichr** [sympy/sympy#12949]
It seems that the intersection function of geometry is looking for a common intersection of all entities. Perhaps it should be reporting the union of intersections?

```
>>> v1 = Line((1,0),(1,1))
>>> v2 = Line((2,0),(2,1))
>>> h = Line((0,0), slope=0)
>>> len(intersection(v1,h))
1
>>> len(intersection(v1,v2,h))
0  #<-- expecting 2
```

**Comment by ayush1999** [comment]
@smichr The output would be 0, since all the three lines **v1,v2,v3** do not meet at a single point. The total number of intersections among them is 2, but **intersection returns the point/points through which all entities pass.**

**Comment by ayush1999** [comment]
@smichr  @asmeurer  We can, however have a new function which returns all the points of intersection. I would love to work  on that. It would be more universal and less restrictive than the intersection function. Any ideas?

**Comment by smichr** [comment]
I think a fix to the current `intersection` routine would be in order. The docstring does not say that a common intersection is given so we are free to change it. Althernatively, a keyword "union" which, when true, could trigger all the pairwise intersections being given.

**Comment by ayush1999** [comment]
I have opened a PR. The change is working for all test cases I tried (2-Dimensional).
A new "union " argument was added. 
**When union is false, the function works like it used to before.**
**When union is true, it tells the total points at which interception, between any two entities took place.(Unlike the previous case, which told the point through which all entities passed.)**
