### ISSUE TITLE
Remove x**1.0 == x hack from core

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#12942]
Apparently the fix for #6100 involves a [hack](https://github.com/sympy/sympy/blob/3a771edb034c81957c0975ca06f0e0d51ab3741b/sympy/core/basic.py#L315) in `Basic.__eq__`.

This is bad not only because special casing subclasses in superclass is bad practice, but `Basic.__eq__` is a core part of the core and should be as fast and general as possible. 

This is related to the things discussed at https://github.com/sympy/sympy/issues/11707, although to me, it's fine if `x**1.0 == x` gives False, so long as `x**1.0` is a Pow, because `==` is structural equality.

**Comment by smichr** [comment]
+1

**Comment by asmeurer** [comment]
Might be easy to fix, depending on what test failures it causes.

**Comment by Trave11er** [comment]
Hello, I'd like to work on this issue.

**Comment by ylemkimon** [comment]
Closed via #13518.
