### ISSUE TITLE
Negative Power on a Holonomic Function not implemented

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#12955]
```
n = symbols('n', positive=True)
expr_to_holonomic(1/x**n, x)
```

Gives

```
sympy.holonomic.holonomicerrors.NotHolonomicError: Negative Power on a Holonomic Function
```

Even though it's simple:

```
>>> expr_to_holonomic(1/x)
HolonomicFunction((1) + (x)*Dx, x, 0, {-1: [1]})
>>> expr_to_holonomic(1/x**2)
HolonomicFunction((2) + (x)*Dx, x, 0, {-2: [1]})
>>> expr_to_holonomic(1/x**3)
HolonomicFunction((3) + (x)*Dx, x, 0, {-3: [1]})
```

Also, if `n` is not set as positive, you get a bug:

```
>>> expr_to_holonomic(1/x**n, x)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "./sympy/holonomic/holonomic.py", line 2424, in expr_to_holonomic
    sol = sol**args[1]
  File "./sympy/holonomic/holonomic.py", line 1131, in __pow__
    if n < 0:
  File "./sympy/core/relational.py", line 197, in __nonzero__
    __bool__ = __nonzero__
TypeError: cannot determine truth value of Relational
>>>
```

CC @certik @shubhamtibra

**Comment by jksuom** [comment]
Negative powers of holonomic functions are not holonomic, in general. (Holonomic functions form a ring but not a field.)

**Comment by asmeurer** [comment]
Is there a good subset of functions with multiplicative inverses that can be computed? Are rational functions always holonomic?

**Comment by jksuom** [comment]
Rational, and even algebraic, functions are holonomic. There is support for rational functions of one variable, but `is_rational_function` does not recognize `1/x**n`. ('This function returns False for expressions that are "rational functions" with symbolic exponents.')

**Comment by asmeurer** [comment]
I'm wondering how general we can be here. Can we compute the symbolic power of an algebraic function?

**Comment by zaxtax** [comment]
Is there is something that would allow the following to work?

````
a, b, x = symbols("a b x", positive=True)
b**(-a)*x**(a - 1)*exp(-x/b)/gamma(a)
````

**Comment by jksuom** [comment]
`is_algebraic` does not recognize symbolic exponents, either. I think that the natural way to handle `1/x**n` is to consider it as a holonomic functions of two variables, one continuous, one discrete. But those are not yet implemented.

**Comment by asmeurer** [comment]
I'm here with @zaxtax at SciPy. He is trying to implement Table 1 on page 7 of https://www.cs.indiana.edu/pub/techreports/TR719.pdf. 

It looks like these are all linear differential equations, and the symbolic powers all work out because the powers cancel in the logarithmic derivative D(log(f)). 

So should be able to implement any symbolic power of a rational function, `r**n`, since `p0/p1` = `-Dr/r` = `-nDr/r`, which gives polynomials for p0 and p1 when r is a rational function. 

So just symbolic powers of rational functions I think would go a long way to help out @zaxtax's use-case.

**Comment by asmeurer** [comment]
Or should it be degree <= 1?

**Comment by asmeurer** [comment]
So if `p1*Df + p0*f = 0`, then `p0/p1 = -Df/f = -D(log(f))`. So `-D(log(f^n)) = -nD(log(f))`, hence, if `f` is holonomic of degree <= 1, with `p1*Df + p0*f = 0`, then `p1*D(f^n) + n*p0*(f^n) = 0`. For the initial conditions, in the linear case, you just take it to the `n`-th power.

Summary: `HolonomicFunction(p0 + p1*Dx, x, [x0])**n` should be `HolonomicFunction(n*p0 + p1*Dx, x, [x0**n])`.

I think it doesn't generalize for degree > 1 (you get a nonlinear DE with things like `fDf` and `f^2`).

Does it seem correct to you?

**Comment by asmeurer** [comment]
By the way, there are two issues here

- Arbitrary powers of linear holonomic DEs
- Unguarded `n < 0` check (should check if `n.is_Integer` first and give a different error).

**Comment by zaxtax** [comment]
How would I multiply the n symbol by the DMP that HolonomicFunction uses internally to store its polynomials?

**Comment by jksuom** [comment]
That should be possible if `n` is included among the generators of the domain `dom` of the DMP's.

**Comment by asmeurer** [comment]
Also another thing: it should guard against symbolic powers that contain x (`other.contains(self.x)`).

**Comment by asmeurer** [comment]
@jksuom that will only work if the symbolic power is a polynomial. But it should work for any symbolic power that is independent of x. 

Why does the holonomic module use DMP objects instead of Poly objects? It would be much simpler to do this with Poly.

**Comment by jksuom** [comment]
Poly representations are DMP.
```
>>> Poly(x**2 - 1).rep
DMP([mpz(1), mpz(0), mpz(-1)], ZZ, None)
```

**Comment by asmeurer** [comment]
To multiply with an arbitrary constant you have to use the Poly logic. So you have to round trip to and from Poly. It would be simpler if DifferentialOperator just used Poly.

**Comment by asmeurer** [comment]
The powers of linear holonomics was implemented, but there is still the issue of the module using the lower level DMP objects instead of just using Poly, which would simplify the code quite a bit.

**Comment by asmeurer** [comment]
I opened a new issue for that. https://github.com/sympy/sympy/issues/13500
