### ISSUE TITLE
Search in the doc fails

### ISSUE THREAD

**Issue by jilljenn** [sympy/sympy#12958]
http://docs.sympy.org/latest/search.html?q=diff&check_keywords=yes&area=default

It just loops.

**Comment by asmeurer** [comment]
Let's check if the latest version of Sphinx fixes this https://github.com/sympy/sympy/issues/12841

**Comment by asmeurer** [comment]
Error shown in the console: `searchindex.js:1 Uncaught SyntaxError: Invalid or unexpected token`

**Comment by asmeurer** [comment]
Should try to fix this for the bugfix release.

**Comment by asmeurer** [comment]
Looks like the latest version of Sphinx fixes it https://github.com/sympy/sympy/pull/12965
