### ISSUE TITLE
Arbitrary point of a polygon misses some points.

### ISSUE THREAD

**Issue by regisin** [sympy/sympy#12966]
I believe I found a bug.

I am trying to print a dot along the perimeter of a polygon. I just installed anaconda and updated it, so SymPy is 1.1.

This is my script:

```
import numpy as np
import sympy as sp
import matplotlib.pyplot as plt

import matplotlib.patches as mpatches

MPoly = mpatches.Polygon(np.array([(0, 0), (0, 10), (5, 10), (5, 5), (10, 5), (10, 0)]), color='k')
fig = plt.figure()
ax = fig.add_axes([0.0, 0.0, 1.0, 1.0], frameon=True)
ax.set_xlim(-5, 15)
ax.set_ylim(-5, 15)
ax.add_patch(MPoly)

Poly = sp.Polygon((0, 0), (0, 10), (5, 10), (5, 5), (10, 5), (10, 0))

BBOX = Poly.bounds

ax.add_patch(mpatches.Rectangle((BBOX[0], BBOX[1]), BBOX[2], BBOX[3], fill=False, color='b'))

DELTA = 5.0 / Poly.perimeter # perimeter = 40

t = sp.Symbol('t', real=True)
pt = Poly.arbitrary_point()

for i in range(int(Poly.perimeter/5.0)): # print a dot every DELTA distance along the perimeter
    POINT = pt.subs(t, DELTA*i)
    print(i, DELTA*i, POINT)
    c = mpatches.Circle((POINT.x, POINT.y), 0.5, color='g', fill=True)
    ax.add_patch(c)

plt.draw()
plt.show()
```

So basically, every 5 points along the perimeter, there should be a green dot. For some reason I don't understand, the arbitrary point function skips 2 corners on the given polygon, and this is the output image:

![issue](https://user-images.githubusercontent.com/794426/28189684-d6bfe8cc-67db-11e7-898f-1ce31ecbc4fa.png)

The printed output (point 3 is the wrong one, should've been `3 Point2D(5, 10)`, similar for point 5):

```
$ ~/anaconda3/bin/python ~/workspace/python/deployment/issue.py
0 0 Point2D(0, 0)
1 0.125000000000000 Point2D(0, 5)
2 0.250000000000000 Point2D(0, 10)
3 0.375000000000000 Point2D(5, 5)
4 0.500000000000000 Point2D(5, 5)
5 0.625000000000000 Point2D(10, 0)
6 0.750000000000000 Point2D(0, 0)
7 0.875000000000000 Point2D(5, 0)
$
```

I thought the problem was that the polygon was convex, but if I use `(0, 0), (0, 10), (10, 10), (10, 0)` as the polygon, the same thing happens.

I am not sure how to solve this.

**Comment by regisin** [comment]
So, I think I solved it. How do I push something here? I never used github outside my own repos.

Anyway, the solution is simple, all done in the polygon.py:

1 - Create a new property, as the original create segments, so they are undirected, we need rays instead, so it doesn't mess up with the order of the points.

```
    @property
    def sides_rays(self):
        """The line rays that form the sides of the polygon.

        Returns
        =======

        sides_rays : list of sides as rays
            Each side is a Ray (directed).

        See Also
        ========

        sympy.geometry.point.Point, sympy.geometry.line.Ray

        Examples
        ========

        >>> from sympy import Point, Polygon
        >>> p1, p2, p3, p4 = map(Point, [(0, 0), (1, 0), (5, 1), (0, 1)])
        >>> poly = Polygon(p1, p2, p3, p4)
        >>> poly.sides_rays
        [Ray2D(Point2D(0, 0), Point2D(1, 0)), Ray2D(Point2D(1, 0), Point2D(5, 1)), Ray2D(Point2D(5, 1), Point2D(0, 1)), Ray2D(Point2D(0, 1), Point2D(0, 0))]


        """
        res = []
        args = self.vertices
        for i in range(-len(args), 0):
            res.append(Ray(args[i], args[i + 1]))
        return res
```

2 - Modify `def arbitrary_point(self, parameter='t')`:

```
        for r in self.sides_rays:
            length = r.points[0].distance(r.points[1])
            side_perim_fraction = length/perimeter
            perim_fraction_end = perim_fraction_start + side_perim_fraction
            pt = r.arbitrary_point(parameter).subs(
                t, (t - perim_fraction_start)/side_perim_fraction)
            sides.append(
                (pt, (And(perim_fraction_start <= t, t < perim_fraction_end))))
            perim_fraction_start = perim_fraction_end
        return Piecewise(*sides)
```

3 - All done, result:

![solved](https://user-images.githubusercontent.com/794426/28234358-b0cf0fa2-68b3-11e7-8fbd-a4aac4648186.png)

Again, I don't know how to send it to the repo using git.

**Comment by jksuom** [comment]
@regisin You can get started with this: https://github.com/sympy/sympy/wiki/Introduction-to-contributing

**Comment by regisin** [comment]
Thanks @jksuom 
I don't know if it worked or not, but I can see the request here: https://github.com/sympy/sympy/pull/12985
