### ISSUE TITLE
_print_Piecewise of NumExprPrinter

### ISSUE THREAD

**Issue by louisabraham** [sympy/sympy#12983]
You can't use Piecewise with numexpr:

```
f = sp.lambdify((x,y,z), sp.Piecewise((y, x >= 0), (z, x < 0)), numexpr)
f(1,2,3)
```
gives
```
TypeError: You can't use Python's standard boolean operators in NumExpr expressions. You should use their bitwise counterparts instead: '&' instead of 'and', '|' instead of 'or', and '~' instead of 'not'.
```

The problem is that
```
from sympy.utilities.lambdify import lambdastr
from sympy.printing.lambdarepr import NumExprPrinter
lambdastr((x,y,z), sp.Piecewise((y, x >= 0), (z, x < 0)), printer=NumExprPrinter)
```
gives you
`"lambda x,y,z: (evaluate('((y) if (x >= 0) else (((z) if (x < 0) else None)))', truediv=True))"`
and numexpr can't process that.

One should modify the function _print_Piecewise of [NumExprPrinter ](http://docs.sympy.org/dev/_modules/sympy/printing/lambdarepr.html) to use the `where` function of NumExpr.

I can do that but is complicated because Piecewise can allow undefined cases (returns ValueError) where as `where` does not. What should value should the lambda function of numexpr return?

**Comment by moorepants** [comment]
I think we require piecewise to be fully defined in the other code printers. We just through an error if they have a undefined case.

**Comment by louisabraham** [comment]
It seems you put nan as default for numpy:

```
>>> lambdastr((x,y,z), sp.Piecewise((y, x > 0), (z, x < 0)), printer=NumPyPrinter)
'lambda x,y,z: (select([greater(x, 0),less(x, 0)], [y,z], default=nan))'
```

I'll try to reproduce that then.
