### ISSUE TITLE
Location of RUBI code

### ISSUE THREAD

**Issue by Upabjojr** [sympy/sympy#12992]
The [current PR](https://github.com/sympy/sympy/pull/12978) for the RUBI integration code is adding a module located in `sympy.rubi`. 

Should this code be there? Or is it better to relocate it somewhere else, like in `sympy.integrals.rubi`?

**Comment by moorepants** [comment]
Seems like it belongs in integrals to me.

**Comment by asmeurer** [comment]
Agree an integrals submodule makes more sense.

**Comment by asmeurer** [comment]
Should this be closed?

**Comment by Upabjojr** [comment]
> Should this be closed?

Yes.
