### ISSUE TITLE
not about to find manualintegrate in sympy library

### ISSUE THREAD

**Issue by abhinov2** [sympy/sympy#13026]
Not about to find manualintegrate in sympy library.

**Comment by parsoyaarihant** [comment]
Hi @abhinov2 , can you elaborate on your issue?

**Comment by parsoyaarihant** [comment]
Here is the code for `manualintegrate` : https://github.com/sympy/sympy/blob/master/sympy/integrals/manualintegrate.py

**Comment by abhinov2** [comment]
Yes,i got that....
Just curious to know how to integrate this sympy module in website .
Or give any reference to any useful documentation.

Thanks 
For your help.

**Comment by parsoyaarihant** [comment]
Cool, @abhinov2 , can you close this issue?
