### ISSUE TITLE
regression: jordan form does not orthogonalize eigenvectors

### ISSUE THREAD

**Issue by cbm755** [sympy/sympy#13038]
@asmeurer @siefkenj here's a (minor?) regression from 1.0.  `A.jordan_form()` used to give orthogonal basis for eigenspace but now it does not.

````
# matrix from the jordan_form docstring:

In [31]: m = Matrix([[ 6,  5, -2, -3], [-3, -1,  3,  3], [ 2,  1, -2, -3], [-1,  1,  5,  5]])

In [32]: (V, J) = m.jordan_form()

In [33]: J
Out[33]: 
Matrix([
[2, 1, 0, 0],
[0, 2, 0, 0],
[0, 0, 2, 1],
[0, 0, 0, 2]])

In [34]: V
Out[34]: 
Matrix([
[ 4, 1,  5, 0],
[-3, 0, -3, 1],
[ 2, 0,  1, 0],
[-1, 0,  1, 0]])

In [35]: v1 = V[:,0]

In [36]: v2 = V[:,1]

In [37]: v1.dot(v2)
Out[37]: 4                  # not zero

````

The resulting vectors seem correct,  I'm still checking if this is alright by defn of Jordan form..., but wanted to let you know about this ASAP in case it needs to hold up 1.1.1.

Apologies for not seeing this sooner!

**Comment by cbm755** [comment]
BTW, I bisected this to 97aeed33d99fabd4975c8e4fa6b322b4f87072b5 or
88bca19948a9f937be21de14e72069017ab5cec2

**Comment by cbm755** [comment]
No mention of orthog basis for eigenspace on wikipedia.  Maple does not seem to orthogonalize.  So I'm thinking this isn't wrong, just a change.

Would be good to have @siefkenj's opinion

**Comment by siefkenj** [comment]
Jordan form does not require the eigenspaces have orthogonal bases. I believe the newly implemented algorithm is more efficient, in part because it doesn't orthogonalize.

**Comment by cbm755** [comment]
ok thank you.

@asmeurer sounds like @siefkenj agrees this should not block 1.1.1, nor does it need "fixing".  Closing.
