### ISSUE TITLE
ENH: Schoenflies + matrix representation in symmetry groups 

### ISSUE THREAD

**Issue by mcocdawc** [sympy/sympy#13058]
Disclaimer in the beginnig:
I am a chemist and we use only a small set of permutation groups for describing the symmetry of molecules, so probably I am lacking the rigorous knowledge about group theory.

Is it planned to support the Schoenflies notation for permutation groups?
By supporting I mean generation of the group instances via Schoenflies symbols like ``'C2v'``
and a ``__repr__``  that outputs Schoenflies symbols.
Besides it would be extremely useful to obtain the group elements as rotation, mirror... matrices when a basis representation in cartesian space is specified.

**Comment by jksuom** [comment]
> Is it planned to support the Schoenflies notation for permutation groups?

There are no plans as far as I know. A few groups are defined in the named_groups module. It should be straightforward to add new groups.

**Comment by mcocdawc** [comment]
Thank you for your answer.
And what about the matrix representations?

**Comment by jksuom** [comment]
> what about the matrix representations?

There is currently practically nothing on group representations. I'm afraid this will be harder to implement. (There are apparently no contributors specializing on groups.)

**Comment by mcocdawc** [comment]
Ok thank you very much for this information
