### ISSUE TITLE
Relationals from classes compares different to those implicitly constructed

### ISSUE THREAD

**Issue by bjodah** [sympy/sympy#13101]
Here's an example:
```
In [1]: Lt(x, 2) == x < 2
Out[1]: False

In [2]: Lt(x, 2).args == (x < 2).args
Out[2]: True

In [3]: Lt(x, 2).func == (x < 2).func
Out[3]: True

In [4]: Lt(x, 2)._hashable_content() == (x < 2)._hashable_content()
Out[4]: True

In [5]: Lt(x, 2)._mhash == (x < 2)._mhash
Out[5]: False

In [6]: Lt(x, 2)._mhash == Lt(x, 2)._mhash
Out[6]: True

In [7]: (x < 2)._mhash == (x < 2)._mhash
Out[7]: True
```
looking into the source I see `evaluate=False` passed in `__lt__`, and indeed that gives equality:
```
In [10]: Lt(x, 2, evaluate=False) == (x < 2)
Out[10]: True
```
But shouldn't they evaluate as equal even when constructed without `evaluate=False` since the arguments are the same?

**Comment by skirpichev** [comment]
@bjodah, I believe there is no issue, except usual Python [op precedence](https://docs.python.org/3/reference/expressions.html).

C.f.
```
In [5]: Lt(x, 2) == (x < 2)
Out[5]: True
```

**Comment by bjodah** [comment]
Ah, how silly of me. Thank you @skirpichev
