### ISSUE TITLE
Don't use "is" to compare classes

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#13111]
There's a lot of code, especially in the core, that tests things like `expr.func is Add`. This should instead use `isinstance(expr, Add)`. 

This is a subissue of https://github.com/sympy/sympy/issues/6751.

**Comment by Yathartha22** [comment]
@asmeurer so what needs to be done here is to replace the occurrences of all `is` to `isinstance` wherever present.

**Comment by BertiesBeans** [comment]
I'm new to contributing to open source, and I'l like to make this my first contribution. Do you mean something like changing
if nonn is not S.One:
     nonneg.append(nonn)

to 

if not isinstance(nonn, S.One):'
     nonneg.append(nonn)      

?

**Comment by vddesai1998** [comment]
Is this issue already assigned to someone?
If it isn't assigned to anyone I would like to fix this issue.

**Comment by abhigyank** [comment]
I'd like to fix this.

**Comment by iwhiz** [comment]
Even though there is lot of competition, why was this issue not assigned to anyone yet?? Any particular reason??

**Comment by asmeurer** [comment]
We don't assign issues to people. If you want to fix it, just state here that you are working on it and then open a pull request.

**Comment by ayush-vibrant** [comment]
I would like to work on this.

**Comment by Itay4** [comment]
I'm working on it.

**Comment by ylemkimon** [comment]
Should `assert x.func is type` in tests be changed?

**Comment by asmeurer** [comment]
The ones in tears should be left alone. In those cases, we do want to check for the exact type.

**Comment by smichr** [comment]
I believe these have all been removed but I am leaving this open, suggesting that the code quality add a test that nothing in the code adds new occurrences of ".func is " anywhere except in the test suite.

**Comment by bmgxyz** [comment]
I think I've got a quality test going for ".func is". (Turns out that testing tests is hard.) Running full test suite now.

**Comment by bmgxyz** [comment]
All tests pass locally, but I've noticed at least one other PR recently that failed on CI in spite of that, so we'll see.

**Comment by gxyd** [comment]
@smichr do you think we still need to keep this issue open?

**Comment by ylemkimon** [comment]
There seems to be cases of using equality(`==`) operator, e.g., `expr.func == exp`, using `in` operator, e.g., `expr.func in (And, Or)`, and comparing each other, e.g., `a.func != b.func`.

**Comment by Itay4** [comment]
@ylemkimon Could you please point to the files where these cases occur?
