### ISSUE TITLE
Integration error

### ISSUE THREAD

**Issue by ethankward** [sympy/sympy#13112]
The integral of `sin(t)^2 / (5 - 4*cos(t))` from `0` to `2 pi` can be verified numerically and with other symbolic integration programs as `pi / 4`. However, sympy gives `5 pi / 8`:

    >>> import sympy
    >>> sympy.__version__
    '1.1.1'
    >>> t = sympy.Symbol('t')
    >>> sympy.integrate(sympy.sin(t)**2 / (5 - 4*sympy.cos(t)), [t, 0, 2*sympy.pi])
    5*pi/8

The integral from `0` to `pi` is computed correctly (`pi / 8`):

    >>> sympy.N(sympy.integrate(sympy.sin(t)**2 / (5 - 4*sympy.cos(t)), [t, 0, sympy.pi]))
    0.392699081698724 + 0.e-21*I

**Comment by Dirivian** [comment]
I was wondering if #13086 is also related.

**Comment by jksuom** [comment]
That fails because there is no integrator for it yet. SymPy cannot currently compute the antiderivative.

**Comment by Roland-Sands** [comment]
Could the residue theorem be used for integrals of this kind
