### ISSUE TITLE
signature of degree function changed

### ISSUE THREAD

**Issue by smichr** [sympy/sympy#13137]
I inadvertently lost track, in #12999, of the change in `degree` function's signature which was `(f, *gens, **args)` and is now `(f, gen=0)`. I don't believe any danger in allowing a wrong result to pass silently has been introduced. Any mis-use will simply result in a TypeError:

1) degree(f, x, y, z) will now generate an arg count mismatch TypeError
2) degree(f, x, gen=y) will generate a duplicate value TypeError

An error will not be raised when users write degree(f, x) or degree(f). There were no use cases in the codebase that required modification for the new signature.

Should a correction be made to add a deprecation? If so, I think we can keep the old signature but warn as follows:

```
gen = args.get('gen', None)
if gens:
    if gen is not None:
        deprecation: gens are not needed
    elif len(args) > 1:
        deprecation: only the first generator needs to be given
        gen = gens[0]
gen = gen or 0
```

I believe that logic is in line with what was suggested by @jksuom 

> Perhaps the following strategy could be applied. If  gen  is given, ignore  gens . If there is no  gen , take the first item of  gens  as  gen  and ignore the rest. If neither  gen  nor  gens  is given, set  gen=0  (the default).

**Comment by jksuom** [comment]
I do not think deprecation would be necessary. The new signature is better than the original since it now raises an error if more than one generator is given. (That might happen if a user erroneously assumes that `degree` will work like `total_degree`.)
