### ISSUE TITLE
Some uses of could_extract_minus_sign can lead to infinite recursion

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#13134]
The issue coming from https://github.com/sympy/sympy/issues/13102 was fixed, but there is another issue has come up in my pull request https://github.com/sympy/sympy/pull/13059. Several places in sympy/functions/special/polynomials.py use could_extract_minus_sign() in a way that can lead to infinite recursion. For example, in [`chebyshevu`](https://github.com/sympy/sympy/blob/dceb708ca035c568c816d9457af1b7ca9e57c0a5/sympy/functions/special/polynomials.py#L605-L609):

```py
            if n.could_extract_minus_sign():
                if n == S.NegativeOne:
                    return S.Zero
                else:
                    return -chebyshevu(-n - 2, x)
```

The problem is that both `n.could_extract_minus_sign()` and `(-n - 2).could_extract_minus_sign()` could be True, leading to infinite recursion. This happens in my branch for `chebyshevu(n - 1, x)`, but probably an example could be found for master too. 

We need a more robust way to canonicalize this. Ideally we'd want to remove the minus sign from the highest order term. Is there a fast way to do that?

**Comment by asmeurer** [comment]
Actually I just thought of a much simpler way. Look at the numeric term (the `coeff` from `as_coeff_Add`), and canonicalize based on whichever is closer to 0. If the numeric term is -1 (so that the term in -n - 2 is also -1), then use `(n + 1).could_extract_minus_sign()`. 

@smichr what do you think?

**Comment by smichr** [comment]
> so that the term in -n - 2 is also -1

I am not following how this might be so -- can you tell me what the `n` is?

Also, what was `n` that cause the recursion error?

**Comment by asmeurer** [comment]
> I am not following how this might be so -- can you tell me what the n is?

```
>>> -(n - 1) - 2
-n - 1
```

Sorry for the confusion for `n` the arg name of `chebyshevu` and `Symbol('n')`. I should probably use a different symbol name for the example. 

> Also, what was n that cause the recursion error?

`chebyshevu(n - 1, x)`, but only in my branch, which has changed up the args ordering for Add and Mul. However, it seems you could probably find an example for master too, since `n.could_extract_minus_sign() == True` is no guarantee that `(-n - 2).could_extract_minus_sign() == False`.

**Comment by asmeurer** [comment]
Here's an example that works in master: `chebyshevu(n - x - 2, x)`

**Comment by asmeurer** [comment]
So I'm suggesting 

```py
coeff, rest = n.as_coeff_Add()
if coeff > -1:
    n = -n - 2
elif coeff == -1:
    n = -n - 2 if rest.could_extract_minus_sign() else n
```

And similar logic for the other places in the file that have this problem. That will produce an arg with constant term closest to 0, using could_extract_minus_sign for the split case.

**Comment by asmeurer** [comment]
Other instances of this I found in the file:

[`legendre`](https://github.com/sympy/sympy/blob/dceb708ca035c568c816d9457af1b7ca9e57c0a5/sympy/functions/special/polynomials.py#L790): `n` -> `-n - 1`

[`laguerre`](https://github.com/sympy/sympy/blob/dceb708ca035c568c816d9457af1b7ca9e57c0a5/sympy/functions/special/polynomials.py#L1088): `n` -> `n - 1`

For legendre the split case is `coeff == -S.Half`. For laguerre there is no split case, so we can just pick the original if the `coeff` is negative and `n - 1` otherwise.

**Comment by smichr** [comment]
> no guarantee

What you are proposing in terms of keeping track of the split point makes sense. And I agree that could_extract makes no guarantee about a new expression derived from n.
