### ISSUE TITLE
collect giving wrong results for derivatives

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#13143]
```py
>>> collect(x*diff(f(x), x, x) - 6*x + f(x).diff(x)*diff(f(x), x, x) + f(x).diff(x), f(x).diff(x, x))
x*Derivative(f(x), x, x) - 6*x + (Derivative(f(x), x, x) + 1)*Derivative(f(x), x)
```

I asked it to collect the second derivative, but it collected the first. I believe this is because it is trying to be smart with derivatives, but it relies on the args order

```py
>>> (diff(f(x), x, x)*diff(f(x), x)).args
(Derivative(f(x), x), Derivative(f(x), x, x))
```

This is a modified example from https://github.com/sympy/sympy/pull/13059#issuecomment-323195614 (in that PR, the args order of `f(x)*diff(f(x), x)` is reversed from master. 

I'm unclear what exactly collect is trying to do with derivatives, but it should respect the symbols given to it and their order (the original example had `collect(x*Derivative(f(x), x) - 6*x + f(x)*Derivative(f(x), x) + f(x), [f(x).diff(x), f(x)])`). Beyond that, I'd say should prefer to collect higher order derivatives.

**Comment by asmeurer** [comment]
Here is a simpler example (which should be more robust to arg order changes):

```py
>>> collect(x + y + x*y, [x, y])
x*(y + 1) + y
>>> collect(x + y + x*y, [y, x])
x + y*(x + 1)
>>> collect(f(x) + diff(f(x), x) + f(x)*diff(f(x), x), [diff(f(x)), f(x)])
(f(x) + 1)*Derivative(f(x), x) + f(x)
>>> collect(f(x) + diff(f(x), x) + f(x)*diff(f(x), x), [f(x), diff(f(x))])
(f(x) + 1)*Derivative(f(x), x) + f(x)
```

The last result should be `f(x)*(Derivative(f(x), x) + 1) + Derivative(f(x), x)`.

So `collect` respects the `syms` order when they are symbols, but when they are a function and its derivative, it disregards the order (and that order is actually arbitrary, based on the args order of the Mul).

**Comment by smichr** [comment]
Might the problem be that collection on `f(x)` targets derivatives? When you give `f(x)` as the first element in syms, it collects derivatives as can be seen by omitting the derivative and using *only* `f(x)`:

```python
>>> collect(f(x) + diff(f(x), x) + f(x)*diff(f(x), x), f(x))
(f(x) + 1)*Derivative(f(x), x) + f(x)
```
My hunch is that it should *first* try to match functions. And if that doesn't work, *then* try matching derivatives containing those functions.

**Comment by asmeurer** [comment]
I believe the automatic collection of derivatives was a feature that was added at some point to make collecting differential equations easier. 

The problem is how collect resolves ambiguities (`x*y` when both `x` and `y` are variables to be collected). When the ambiguity is in variables, it seems to do the right thing, but when they are a function and derivative, the automatic logic somehow confuses it, causing it to ignore the ordering given by the user.
