### ISSUE TITLE
integrate() outputs ∞ * sign(1 / s²)

### ISSUE THREAD

**Issue by Pastafarianist** [sympy/sympy#13140]
Execute in a Jupyter notebook cell:

```python
import sympy as sp
from sympy.abc import sigma
sp.init_printing()

y, r, b = sp.symbols('y r b')
R = sp.Piecewise((y, (0 <= y) & (y < b)), (0, True))
sp.integrate(-(y - r)**2 / (2 * sigma**2) + R, (y, -sp.oo, sp.oo))
```

Output:

![image](https://user-images.githubusercontent.com/1315874/29416492-f07c1b24-836e-11e7-87c5-89c09761cd94.png)

Clearly, `∞ * sign(1 / s²)` is not correct.

**Comment by asmeurer** [comment]
I believe it's correct. What is the output you'd expect? 

Outside the interval [0, b] the integrand is `-(y - r)**2 / (2 * sigma**2)`, which is either - or + infinity depending on the sign of `sigma**2` (SymPy isn't simplifying `sign(sigma**2)` to 1 because sigma could be complex, e.g., if sigma is sqrt(-1) then the sign of `sigma**2` is -1).

**Comment by Pastafarianist** [comment]
Apologies. I had forgotten to wrap the entire integrand in `sp.exp` but was thinking that I had not. The correct integral (`sp.integrate(sp.exp(-(y - r)**2 / (2 * sigma**2) + R), (y, -sp.oo, sp.oo))`) cannot be evaluated by sympy at all, but that's a topic for a different bug report.

**Comment by asmeurer** [comment]
I get an answer for that. It's quite complicated but it can be simplified quite a bit if you add assumptions like `real` or `positive` to your constants.

**Comment by Pastafarianist** [comment]
@asmeurer can you share the code for that?

**Comment by asmeurer** [comment]
Oh never mind I was using `R = symbols("R")` not the Piecewise.

**Comment by asmeurer** [comment]
I also tried it on https://github.com/sympy/sympy/pull/12587 but it doesn't work there either.
