### ISSUE TITLE
Tests on Travis always have NumPy installed

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#13148]
I think somehow the Travis virtualenvs always have NumPy installed. See https://github.com/sympy/sympy/pull/13145. As a result, there are several test failures in master when NumPy is not installed that we haven't caught. 

We should add a `pip remove numpy` line to the Travis builds that shouldn't have it. And also check if other libraries are installed that shouldn't be.

**Comment by ylemkimon** [comment]
```
_______________________________________________________________________________________________________________________
___________________________________ sympy\utilities\tests\test_lambdify.py:test_sin ___________________________________
  File "c:\users\wisec\documents\github\sympy\sympy\utilities\tests\test_lambdify.py", line 305, in test_sin
    assert isinstance(f(2), float)
AssertionError
```
Above test fails on Windows where mpmath seems to be first default module when NumPy is not installed.
