### ISSUE TITLE
AccumBounds needs recreatable str/srepr

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#13158]
```
>>> str(AccumBounds(-1, 1))
'<-1, 1>'
>>> srepr(AccumBounds(-1, 1))
'<-1, 1>'
```

The str and srepr should be recreatable. The pretty printer should be the only thing that prints the pretty form.

**Comment by asmeurer** [comment]
This is probably just a matter of moving the current printer from the str printer to the pretty printer.

**Comment by firedranzer** [comment]
Hi @asmeurer . I would like to work on this issue.
