### ISSUE TITLE
Mul(AccumBounds(-1, 1), 0) gives AccumBounds(-1, 1)

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#13159]
```py
>>> Mul(AccumBounds(-1, 1), 0)
<-1, 1>
```

Even though

```py
>>> Mul(0, AccumBounds(-1, 1))
0
>>> 0*AccumBounds(-1, 1)
0
>>> AccumBounds(-1, 1)*0
0
```

This is resulting in a regression in https://github.com/sympy/sympy/pull/13059 for `limit(atan(x)*sin(1/x), x, 0)` because the limit heuristics are going through the args in a different order. Probably an example could be found for master where an AccumBounds is returned from limit instead of 0.

**Comment by asmeurer** [comment]
Seems to be an issue with the op priority stuff.

**Comment by asmeurer** [comment]
Actually, the op priority *does* work. The problem is that there is code in Mul.flatten that tries to handle AccumBounds, and it is doing it wrong. Mul.flatten shouldn't be aware of these special classes (that's the whole point of op priority). 

If you remove it, it fixes this issue, but you also end up with some AccumBounds in the tests that don't auto-simplify, like 

```
>>> (x**2 + 2*x + 1).subs(x, AccumBounds(-1, 1))
2*<-1, 1> + <1, 2>
```

Maybe it needs to be using the new postprocessor stuff.

**Comment by asmeurer** [comment]
OK, it only fixes it in that case because Mul(0, anything that isn't infinity or nan) gives 0. In general, Mul.flatten doesn't look at op_priority. So I think it does need to implement a post-processor.

**Comment by asmeurer** [comment]
https://github.com/sympy/sympy/pull/13161

**Comment by asmeurer** [comment]
I think the issue still exists for more complicated cases:

```py
>>> import itertools
>>> for perm in itertools.permutations([0, AccumBounds(-1, 1), x]):
...     print(perm, Mul(*perm))
(0, AccumBounds(-1, 1), x) 0
(0, x, AccumBounds(-1, 1)) 0
(AccumBounds(-1, 1), 0, x) AccumBounds(-1, 1)*x
(AccumBounds(-1, 1), x, 0) AccumBounds(-1, 1)*x
(x, 0, AccumBounds(-1, 1)) 0
(x, AccumBounds(-1, 1), 0) AccumBounds(-1, 1)*x
```

**Comment by maurogaravello** [comment]
I think that the issue can be resolved changing the line 265 of `mul.py` in the following way:
`                elif coeff.is_Number:  # it could be zoo
` (original line)
`                elif coeff.is_Number or isinstance(coeff, AccumBounds):  # it could be zoo
` (modified)


In this way the code 
```
                    coeff *= o
                    if coeff is S.NaN:
                        # we know for sure the result will be nan
                        return [S.NaN], [], None

```
is executed also in the case `coeff` is `AccumBounds(-1, 1)` (or similar) and, in case `o` is `0`, then `coeff` becomes `0`.

**Comment by jksuom** [comment]
That looks promising to me. Can you send a PR?

**Comment by maurogaravello** [comment]
Sent it.
