### ISSUE TITLE
clarify Derivative docstring

### ISSUE THREAD

**Issue by smichr** [sympy/sympy#13156]
The discussion in Derivative's docstring is confusing. I think cut-and-paste wasn't edited properly and the example needs to be re-edited for clarity. This is only a piece of the documentation; the glaring problem is highlighted, but other edits may be necessary:

```
>>> from sympy.abc import c, s
>>> def F(u):
...     return 2*u
...
>>> def G(u):
...     return 2*sqrt(1 - u**2)
...
>>> F(cos(x))
2*cos(x)
>>> G(sin(x))
2*sqrt(-sin(x)**2 + 1)
>>> F(c).diff(c)  <--------same as the one that follows
2
>>> F(c).diff(c)  <--------ditto
2
>>> G(s).diff(c)
0
>>> G(sin(x)).diff(cos(x))
0
```

**Comment by anca-mc** [comment]
I can edit the docstring. To begin with, I guess the second F(c).diff(c) line should be in fact F(cos(x)).diff(cos(x)).
