### ISSUE TITLE
Mod(x**2, x) is not (always) 0

### ISSUE THREAD

**Issue by smichr** [sympy/sympy#13169]
When the base is not an integer, `x**2 % x` is not 0. The base is not tested to be an integer in Mod's eval logic:

```
if (p == q or p == -q or
        p.is_Pow and p.exp.is_Integer and p.base == q or
        p.is_integer and q == 1):
    return S.Zero
```

so

```
>>> Mod(x**2, x)
0
```
but
```
>>> x = S(1.5)
>>> Mod(x**2, x)
0.75
```

**Comment by smichr** [comment]
Even if `p.base` is an integer, the exponent must also be positive.

```
if (p == q or p == -q or p.is_integer and q == 1 or
        p.base == q and q.is_integer and p.is_Pow and p.exp.is_Integer
        and p.exp.is_positive):
    return S.Zero
```

**Comment by rheaparekh** [comment]
I would like to work on this.

**Comment by anca-mc** [comment]
One would need just a slight change in the order of the properties, 


            p.is_Pow and p.base == q and q.is_integer and p.exp.is_Integer
            and p.exp.is_positive):
            return S.Zero

instead of

        p.base == q and q.is_integer and p.is_Pow and p.exp.is_Integer
        and p.exp.is_positive):
        return S.Zero


otherwise one gets an Attribute error:'Symbol' object has no attribute 'base' from
>>> Mod(x**2, x).
