### ISSUE TITLE
f(x,g(x)).diff(x,x) produces inconsistent result

### ISSUE THREAD

**Issue by jklw** [sympy/sympy#13166]
Hello!

Example session:

```
IPython console for SymPy 1.1.1 (Python 3.4.2-64-bit) (ground types: gmpy)
[...]
In [1]: f(x,g(x)).diff(x,x)
Out[1]: 
⎛            2                     2               ⎞                     ⎛   2            ⎞│            2                 2                              
⎜d          d                     d                ⎟ d          d        ⎜  ∂             ⎟│           d                 d        ⎛ ∂           ⎞│       
⎜──(g(x))⋅──────(f(x, g(x))) + ────────(f(x, g(x)))⎟⋅──(g(x)) + ──(g(x))⋅⎜──────(f(x, ξ₃))⎟│        + ───(f(x, g(x))) + ───(g(x))⋅⎜───(f(x, ξ₂))⎟│       
⎜dx            2               dx dg(x)            ⎟ dx         dx       ⎝∂ξ₃ ∂x          ⎠│ξ₃=g(x)     2                 2       ⎝∂ξ₂          ⎠│ξ₂=g(x)
⎝         dg(x)                                    ⎠                                                  dx                dx                               
                               
                               ^^^^^^ Term 1 ^^^^^^                      ^^^^^ Term 2 ^^^^^           ^^^^ Term 3 ^^^

```

Apparently Sympy intends Term 3 to mean "the second derivative of `f` after its first parameter, holding the second parameter fixed" (cf. [Wolram Alpha](https://www.wolframalpha.com/input/?i=d%5E2%2Fdx%5E2+f(x,g(x))); Term 3 corresponds to the `f^(2,0)(x,g(x))` term there). On the other hand, `f(x,g(x)).diff(x,x, evaluate=False)` produces an identically-looking term (even with `str` or `repr`), but with different meaning (namely, the second derivative of the composite function `x -> f(x,g(x))`). This seems inconsistent.

There's a similar problem with Term 1.

Also, Sympy seems to randomly decide between using either the "evaluated-at" notation (with the ξs) or the other notation (Term 1, 3). This seems to prevent it from grouping terms 1 and 2 together, which are actually the same (thus the `2 * ...` term in Wolfram). IMHO, it would be better to always use the evaluated-at notation if there's any ambiguity.

**Comment by jklw** [comment]
PS: This isn't just a cosmetic problem. We can derive a falsehood simply by evaluating selectively:

```py
foo = f(x,g(x)).diff(x,x,evaluate=False)
Eq(0, foo.doit() - foo)
```

```
    ⎛            2                     2               ⎞                     ⎛   2            ⎞│            2                              
    ⎜d          d                     d                ⎟ d          d        ⎜  ∂             ⎟│           d        ⎛ ∂           ⎞│       
0 = ⎜──(g(x))⋅──────(f(x, g(x))) + ────────(f(x, g(x)))⎟⋅──(g(x)) + ──(g(x))⋅⎜──────(f(x, ξ₃))⎟│        + ───(g(x))⋅⎜───(f(x, ξ₂))⎟│       
    ⎜dx            2               dx dg(x)            ⎟ dx         dx       ⎝∂ξ₃ ∂x          ⎠│ξ₃=g(x)     2       ⎝∂ξ₂          ⎠│ξ₂=g(x)
    ⎝         dg(x)                                    ⎠                                                  dx                               
```

This clearly isn't true in general, e.g. take g(x) = x and f = anything with positive second partial derivatives.

The problem is that `foo.doit()` contains `foo` as a subterm, but with different intended meaning (as described above).

**Comment by jklw** [comment]
Narrowed it down to this:

```
In [83]: xi = symbols('xi')

In [84]: a = Subs(Derivative(f(xi,g(x)), xi, xi), xi, x)

In [85]: a
Out[85]: 
⎛  2            ⎞│   
⎜ ∂             ⎟│   
⎜───(f(ξ, g(x)))⎟│   
⎜  2            ⎟│   
⎝∂ξ             ⎠│ξ=x

In [86]: a.doit()
Out[86]: 
  2            
 d             
───(f(x, g(x)))
  2            
dx             
```

This illegally makes the differential operator capture the `x` in `g(x)`. So it seems that the problem is that `Derivative._eval_subs` doesn't check for variable capture: https://github.com/sympy/sympy/blob/628286fb5cc2248002bb0b141a911757a2e81fa7/sympy/core/function.py#L1392-L1412

**Comment by smichr** [comment]
In master this now gives
```python
>>> foo=f(x,g(x)).diff(x,x,evaluate=False)
>>> (foo.doit()-foo).subs({f:Lambda((x,y),x**2+y),g(x):exp(x)}).doit().expand()
0
>>> a = Subs(Derivative(f(xi,g(x)), xi, xi), xi, x)
>>> a.doit()
Subs(Derivative(f(xi, g(x)), (xi, 2)), (xi,), (x,))
```
