### ISSUE TITLE
sympy.heaviside does not properly get lambdified using numpy backend

### ISSUE THREAD

**Issue by laolux** [sympy/sympy#13176]
I just noticed that `sympy.heaviside` does not properly get lamdified to numpy's `numpy.heaviside`.
Numpy's heaviside function was added recently in version 1.13.0, so I guess it has been overlooked so far. The change should be rather easy for someone who knows the internals of sympy (not me).
Below I attached a minimal working example:

```python
import sympy as sym
import numpy as np
x = sym.symbols('x', real=True)
lambdified_heaviside = sym.lambdify(x, sym.Heaviside(x), 'numpy')
np.heaviside([-1,0,1],1/2)
lambdified_heaviside([-1,0,1])
```

I think the output of `numpy_heaviside([-1,0,1])` should be the same as `np.heaviside([-1,0,1],1/2)`.
Documentation for `numpy.heaviside` is [here](https://docs.scipy.org/doc/numpy/reference/generated/numpy.heaviside.html).

**Comment by rvignolo** [comment]
Seems that this issue has not been solved yet

**Comment by Ickaser** [comment]
I made the decision in #20411 to use np.heaviside([-1, 0, 1],0), which made the most sense to me at the time. I solved the problem by adding _print_Heaviside to the numpy printer.

**Comment by czgdp1807** [comment]
On current `master`,
```python
Python 3.6.9 (default, Jul 17 2020, 12:50:27) 
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> Heaviside
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'Heaviside' is not defined
>>> 
```
