### ISSUE TITLE
add `total_degree` thin-wrapper like function to polytools

### ISSUE THREAD

**Issue by smichr** [sympy/sympy#13179]
Just as there is a `degree` function and a `Poly.degree` method, a `total_degree` function could be added to polys.polytools.

Perhaps something like the following:

```
def total_degree(f):
    f = sympify(f)
    if f.is_Poly:
        rv = f.total_degree()
    elif f.is_Number:
        rv = 0
    else:
        rv = Poly(f).total_degree()
    # the Poly method returns int; SymPy functions return SymPy objects
    return Integer(rv)
```

**Comment by asmeurer** [comment]
It should also allow to specify the generators. It should match the other polys functions in its form.

**Comment by smichr** [comment]
> specify the generators

ahh...so `total_degree(x*y + z**3, x, y)` gives 2 instead of 3?

**Comment by asmeurer** [comment]
Yes

```
>>> Poly(x*y + z**3, x, y).total_degree()
2
```

Anything not in the generators should be thought of as a symbolic constant.

**Comment by Yathartha22** [comment]
@smichr I would like to work on this.
