### ISSUE TITLE
Scalar + sympy Matrix error.

### ISSUE THREAD

**Issue by jhacsonmeza** [sympy/sympy#13171]
When for example I try to do the following operation:
`sympy.Matrix([[1,2],[3,4]]) + 4`
I get the following error:
`TypeError: cannot add <class 'sympy.matrices.dense.MutableDenseMatrix'> and <class 'int'>`
I get the same with the `Array` module. 
I would appreciate your help.

**Comment by asmeurer** [comment]
This is the intended behavior. If you want to add an multiple of the identity use `Matrix([[1, 2], [3, 4]]) + 4*eye(2)`. If you want to add a multiple of a ones matrix use `Matrix([[1, 2], [3, 4]]) + 4*ones(2)`.
