### ISSUE TITLE
Ability to solve modular equations with integer solutions

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#13178]
See for instance https://www.johndcook.com/blog/2017/08/22/predicting-a-lcg-output/. It would be cool if you could just write

```py
n = symbols('n', integer=True)
a = 742938285
z = 1898888478
m = 2**31 - 1
x = 20170816
solveset(x – Mod(a**n*z, m), n, S.Integers)
```

and it produced the answer {100}.

**Comment by smichr** [comment]
breadcrumb:

```
z = 1898888478
m = 2**31 - 1
x = 20170816
arg = x*invert(z, m)
n = discrete_log(m, arg, a)
```

**Comment by asmeurer** [comment]
The equation is the same as solving `x = a**n*z` for n except each operation must be done as its analogue mod m.

**Comment by smichr** [comment]
I get an unexpected error when trying the above:

```
>>> a = 742938285
>>> z = 1898888478
>>> m = 2**31 - 1
>>> x = 20170816
>>> arg = x*invert(z, m)
>>> n = discrete_log(m, arg, a)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "sympy\ntheory\residue_ntheory.py", line 1298, in discrete_log
    return _discrete_log_pohlig_hellman(n, a, b, order)
  File "sympy\ntheory\residue_ntheory.py", line 1245, in _discrete_log_pohlig_he
llman
    aj = pow(a * mod_inverse(gj, n), order // pi**(j + 1), n)
TypeError: __sympifyit_wrapper() takes exactly 2 arguments (3 given)
>>>
```

**Comment by anca-mc** [comment]
One should then define an _invert (modulo m) function by the model of _invert_real and _invert_complex?

**Comment by ishanaj** [comment]
@asmeurer @smichr I would like to take this up. From should this be started? Is defining an `invert()` for modular eq(inside `solveset`) a good point to start with?
