### ISSUE TITLE
init_session() throws exception when called from iPython startup: "maximum recursion depth exceeded"

### ISSUE THREAD

**Issue by PorcelainMouse** [sympy/sympy#13197]
Sorry, I couldn't find any references to this issue.  When I call init_session() from iPython startup file (~/.ipython/profile_default/startup/NN-sympy.ipy), I get a huge traceback that ends with:

maximum recursion depth exceeded

But, it seems to work fine when I call it, manually, once the interactive session has started.  Does anyone recognize this symptom?

**Comment by ylemkimon** [comment]
Please upload or post full traceback. Although it's huge, last functions calls are probably repeating.

**Comment by PorcelainMouse** [comment]
Thanks for you help!  Yes, I think it is repeating.  A full console log is 1.3 MB and I doubt you want me to attach all that.  I'm just going to attach what I think is the last repeated output.
[ipython.onetraceback.txt](https://github.com/sympy/sympy/files/1253834/ipython.onetraceback.txt)

**Comment by PorcelainMouse** [comment]
BTW, ipython3 just crashes when I call init_session() from startup.

**Comment by asmeurer** [comment]
Is this with the latest version of SymPy? This looks like https://github.com/sympy/sympy/issues/12907, which was fixed in 1.1.1.

**Comment by PorcelainMouse** [comment]
Well, my package says 1.1.1.  I don't know which commit, though.

python3-sympy-1.1.1-1.fc26.noarch

**Comment by PorcelainMouse** [comment]
Maybe it's my iPython?  python3-ipython-5.3.0-4.fc26.noarch.  Looks like that is and old version.  Let me know if that is possibly the problem.

**Comment by asmeurer** [comment]
Maybe it's a different error. It would have been helpful to see the top of the traceback. What is the code that you have in your startup file?

**Comment by asmeurer** [comment]
What is `/home/<username>/.ipython/profile_default/startup/99-last.py`. It seems to be retrying the init after it fails with ImportError (I'm unclear why you are getting the import error).

**Comment by PorcelainMouse** [comment]
99-last.py contains:
`
sympy.init_session()
`
See attachments.  I have both iPython3, which crashed, and the first repeat of errors from ipython.
[ipython3.STDOUT.txt](https://github.com/sympy/sympy/files/1258562/ipython3.STDOUT.txt)
[ipython.STDOUT.head.txt](https://github.com/sympy/sympy/files/1258571/ipython.STDOUT.head.txt)

**Comment by oscarbenjamin** [comment]
Is this still an issue?

**Comment by PorcelainMouse** [comment]
No, it appears to not be happening anymore.  Thanks for asking; I forgot to check on it.

**Comment by oscarbenjamin** [comment]
Great. Thanks for responding!

I'll close this now but obviously let us know if you find more problems...
