### ISSUE TITLE
periodicity(Abs(sin(x)),x) return 2*pi

### ISSUE THREAD

**Issue by souravghosh97** [sympy/sympy#13207]
periodicity(Abs(sin(x)),x) returns 2*pi instead of pi
```
>>> from sympy import *
>>> x=Symbol('x')
>>> periodicity(Abs(sin(x)),x,check=True)
2*pi
>>> periodicity(Abs(sin(x)),x)
2*pi
```

**Comment by Itay4** [comment]
Can I have this issue ?

**Comment by asmeurer** [comment]
Note by the docstring we are not guaranteed to get the fundamental period. But of course it would be good to improve the answer if possible.
