### ISSUE TITLE
ITE.to_nnf appears to use Boolean of else arg

### ISSUE THREAD

**Issue by smichr** [sympy/sympy#13223]
I expect both to give the same result in the following:

```
>>> e = ITE(x<1,(1,2),S.NaN)
>>> e.to_nnf().subs(x,2)
True
>>> e.subs(x,2)
NaN
```

The NaN evaluates in a different way than the (1,2) does in an Or: Or(x<1,foo) is True if foo is a Number.

**Comment by asmeurer** [comment]
ITE expects all three args to be booleans, especially to_nnf, which rewrites it as a boolean expression.

**Comment by smichr** [comment]
It need not in general: using the same `e` we can get the tuple result from either form:

```
>>> e.subs(x,0), Eq(e.subs(x,0), e.to_nnf().subs(x,0))
((1, 2), True)
```

But yes: in the Boolean form there is no way (that I can think of) to have an Or return its first arg as a Number instead of as True or False. Whereas `2 or 3` is `2`, `Or(2, 3)` is `True`. Do you recall why don't we return the first true arg?

**Comment by asmeurer** [comment]
I'm not a fan of treating numbers as booleans. It's convenient for a programming language, but the SymPy logic module deals with boolean algebras, and the manipulations therein. OR in a boolean algebra is commutative.

To this problem, even if it did work on non-booleans and short circuit, `Or` sorts its arguments, so the short circuiting would be arbitrary. In fact, for me, `e.to_nnf()` gives `x ≥ 1 ∨ (1, 2)`, so a short circuit on `x=2` would be `True` anyway.

**Comment by smichr** [comment]
> even if it did work on non-booleans and short circuit, Or sorts its arguments

Ahh yes. So there is no problem here other than that it would be better to simply convert args to Booleans since that is how they are going to be treated. So instead of `x ≥ 1 ∨ (1, 2)` we would just get `x ≥ 1` since `(1, 2)` is a True expression. Maybe this would work

```
def as_Boolean(e):  
    if isinstance(e, Boolean):
        return e
    if not isinstance(e, Expr):
        return S.true if bool(e) else S.false
    return S.false if z.is_zero else (S.true if z.is_zero is False else e)
```

Could that be  an __init__ or __new__ for Boolean?

I would really like to keep the ability of *something* to hold any type argument. ITE seems to be a good candidate as a general switchable expression. One thing that could be done to improve it would be to make it pprint like Piecewise. Then we could let Piecewise only hold Expr in the expr part of its args.

```
>>> ITE(x<2,[1,2],(1,2)).subs(x,0)
[1, 2]
```

One thing that could be done to allow ITE to be used more like Piecewise would be instantiate as

```
def __init__(*args, **kwargs):
    '''
    >>> __init__((x<1,1),(x<2,2,3))
    ITE(x < 1, 1, ITE(x < 2, 2, 3))
    >>> __init__((x<1,1),(x<2,2))
    ITE(x < 1, 1, ITE(x < 2, 2, nan))
    >>> __init__((x<2,2,3))
    ITE(x < 2, 2, 3)
    >>> __init__(x<2,2,3)
    ITE(x < 2, 2, 3)
    >>> __init__((x<2,2))
    ITE(x < 2, 2, nan)
    '''
    if len(args) == 3 and isinstance(args[0], Boolean):
        assert not kwargs
        return ITE(*args)
    assert all(type(i) is tuple and isinstance(i[0], Boolean) for i in args)
    args = list(args)
    if len(args[-1]) ==3:
        last = args[-1][-1]
        args[-1] = args[-1][:2]
    else:
        last = S.NaN
    assert all(len(i) == 2 for i in args)
    for c, v in reversed(args):
        last = ITE(c, v, last)
    return last
```

We could also make ITE print like Piecewise with the exception that the last arg would be 3 elements long so `ITE(x < 1, 1, ITE(x < 2, 2, 3))` would be `ITE((x < 1, 1), (x < 2, 2, 3))`.

**Comment by smichr** [comment]
> ITE print like Piecewise

To avoid confusion, perhaps the input and output should be the same as Piecewise: give tuples in `(b, cond)` order. So `ITE(cond, a, b)` could be entered as `ITE((a, cond), (b, True))`.
