### ISSUE TITLE
Intersection of two circles can lead to a crash

### ISSUE THREAD

**Issue by nylocx** [sympy/sympy#13230]
In Sympy 1.1.1 this code:

```
c1 = Circle(Point2D(180 + 24*sqrt(210), 168), 231)
c2 = Circle(Point2D(889, 89 + 2*sqrt(9879)), 174)
intersection(c1, c2)
```

crashes with the following Stacktrace:
```
Traceback (most recent call last):
  ...
  File "/usr/lib/python3.6/site-packages/sympy/geometry/util.py", line 700, in intersection
    res = entities[0].intersection(entities[1])
  File "/usr/lib/python3.6/site-packages/sympy/geometry/ellipse.py", line 1444, in intersection
    return Ellipse.intersection(self, o)
  File "/usr/lib/python3.6/site-packages/sympy/geometry/ellipse.py", line 656, in intersection
    return list(ordered([Point(i) for i in solve([ellipse_equation, o.equation(x, y)], [x, y])]))
  File "/usr/lib/python3.6/site-packages/sympy/solvers/solvers.py", line 1067, in solve
    solution = _solve_system(f, symbols, **flags)
  File "/usr/lib/python3.6/site-packages/sympy/solvers/solvers.py", line 1744, in _solve_system
    result = solve_poly_system(polys, *symbols)
  File "/usr/lib/python3.6/site-packages/sympy/solvers/polysys.py", line 33, in solve_poly_system
    polys, opt = parallel_poly_from_expr(seq, *gens, **args)
  File "/usr/lib/python3.6/site-packages/sympy/polys/polytools.py", line 4266, in parallel_poly_from_expr
    return _parallel_poly_from_expr(exprs, opt)
  File "/usr/lib/python3.6/site-packages/sympy/polys/polytools.py", line 4280, in _parallel_poly_from_expr
    f, g = f.unify(g)
  File "/usr/lib/python3.6/site-packages/sympy/polys/polytools.py", line 384, in unify
    _, per, F, G = f._unify(g)
  File "/usr/lib/python3.6/site-packages/sympy/polys/polytools.py", line 399, in _unify
    dom, lev = f.rep.dom.unify(g.rep.dom, gens), len(gens) - 1
  File "/usr/lib/python3.6/site-packages/sympy/polys/domains/domain.py", line 262, in unify
    return K0.unify_with_symbols(K1, symbols)
  File "/usr/lib/python3.6/site-packages/sympy/polys/domains/domain.py", line 242, in unify_with_symbols
    return K0.unify(K1)
  File "/usr/lib/python3.6/site-packages/sympy/polys/domains/domain.py", line 318, in unify
    return K0.__class__(K0.dom.unify(K1.dom), *_unify_gens(K0.orig_ext, K1.orig_ext))
  File "/usr/lib/python3.6/site-packages/sympy/polys/domains/algebraicfield.py", line 33, in __init__
    self.ext = to_number_field(ext)
  File "/usr/lib/python3.6/site-packages/sympy/polys/numberfields.py", line 1046, in to_number_field
    root = sum([ coeff*ext for coeff, ext in zip(coeffs, extension) ])
TypeError: unsupported operand type(s) for +: 'int' and 'tuple'
```

Gaurav Dhingra @gxyd at gitter noted
> It used to work in SymPy 1.0 . Doing a git bisect shows that it was broken in commit sympy/sympy@0d4eaa2

and Kalevi Suominen @jksuom noted that this might be related to the AlgebraicField

> That commit made intersection of two circles use the more general code for ellipses. There should be nothing wrong with that in principle. Instead, it seems that there is a bug in AlgebraicField

**Comment by jksuom** [comment]
File "/usr/lib/python3.6/site-packages/sympy/polys/domains/algebraicfield.py", line 33, in __init__
    self.ext = to_number_field(ext)

The `ext` argument of `AlgebraicField` can take several forms. It can be an expression for a single algebraic number or a list of such expressions. Then `to_number_field` returns an algebraic number in terms of which all items of `ext` can be expressed (the primitive element of the field they generate), and it is saved as `ext` of the field. The original items are saved in `orig_ext` for later use.

In addition, there is one special case: `ext` may also be a tuple that consists of a polynomial and one of its roots. This tuple leads to the type error seen above. In this case, only the root component of the tuple should be saved as `orig_ext`.

**Comment by vishal-vardhan** [comment]
Is the problem here is that the function intersection should still give a valid output even when the points are given in expression form?

**Comment by jksuom** [comment]
I think that the problem is a bug in `AlgebraicField.__init__` as described in the comment above. If `ext` is a tuple that consists of a polynomial and one of its roots, only the root should be saved as `orig_ext`.

**Comment by jksuom** [comment]
Something like this will be needed for the fix:

    if len(ext) == 2 and isinstance(ext[0], Poly):
        self.orig_ext = ext[1:]
    else:
        self.orig_ext = ext

**Comment by vishal-vardhan** [comment]
I tried that but when i try to import Poly from algebraicfield.py it pops up "cannot import" Poly.
@jksuom can u help me out.

**Comment by vishal-vardhan** [comment]
@jksuom i tried that but its giving the same error again

**Comment by jksuom** [comment]
That is true. It seems that `ext` is not a tuple of length 2 but a tuple of length 1 whose sole item is a tuple of length 1. So the test has to modified to look at `ext[0]` instead of `ext`:

    if isinstance(ext[0], tuple):
        self.orig_ext = ext[0][1:]
    else:
        self.orig_ext = ext

This should fix the error in AlgebraicField. However, it seems that there is another conversion issue that may be harder to solve:
```
CoercionFailed: can't convert ANP([mpq(1,1)], [mpq(1,1), mpq(0,1), mpq(-210,1)], QQ) of type <class 'sympy.polys.polyclasses.ANP'> from QQ<sqrt(210)> to QQ<sqrt(210) + sqrt(9879)>
```

**Comment by vishal-vardhan** [comment]
@jksuom can u guide me to solve it

**Comment by jksuom** [comment]
The `orig_ext` issue is easy to fix, and that should be done in any case. The coercion issue is harder. It need not be solved in the same PR. You should first find out how algebraic numbers are represented as ANP's, and then how elements of `QQ<sqrt(210)>` can be represented as elements of `QQ<sqrt(210) + sqrt(9879)>` starting from the representation of `sqrt(210)`.

**Comment by vishal-vardhan** [comment]
sure thanks

**Comment by vishal-vardhan** [comment]
should i create a pull request for the orig_text case?

**Comment by jksuom** [comment]
I think you could do that even though the issue will not be solved. A suitable test should be devised to see that `orig_ext` will not contain Polys.

**Comment by vishal-vardhan** [comment]
To test it i think we should check the input args(some how) to the AlgebraicField class i.e "ext" here before it is passed to the class .

**Comment by jksuom** [comment]
The test should create an instance of AlgebraicField where `ext` contains a Poly. It will suffice to take one of the circles and convert its equation into a Poly with domain an AlgebraicField. Something like this, for example,

    p = c1.equation(x, y).as_poly(x, y, extension=True)

The field is then `p.domain`, and there should be no Poly in `p.domain.orig_ext`.
