### ISSUE TITLE
Printing should use short representation of quantities.

### ISSUE THREAD

**Issue by schymans** [sympy/sympy#13269]
There is a test that explicitly expects that printing does not use `abbrev` but `name`:
https://github.com/sympy/sympy/blob/8e962a301d7cc2d6fc3fa83deedd82697a809fd6/sympy/physics/units/tests/test_quantities.py#L87
Is there a reason behind this? I find it quite user-unfriendly to look at `1.34*meter/second` instead of `1.34*m/s`.
It would be very easy to change here: https://github.com/sympy/sympy/blob/8e962a301d7cc2d6fc3fa83deedd82697a809fd6/sympy/printing/str.py#L713
But then, the above test would fail. Is anyone emotionally attached to the current verbose display of units and quantities?

**Comment by asmeurer** [comment]
We could add a flag for it. Also I think the pretty printer should be using the shorter form always.

**Comment by schymans** [comment]
Thanks! I created a PR: https://github.com/sympy/sympy/pull/13310
I don't even see a point of adding a flag for it, as one should not provide `abbrev` to a `Quantity` if one does not want it to be used.
