### ISSUE TITLE
function_range keeps iterating over infinite critical points of ImageSet solution

### ISSUE THREAD

**Issue by aktech** [sympy/sympy#13273]
`function_range(sin(x)*exp(x) - 1, x, S.Reals)` hangs forever as it keeps iterating over critical points in the following:

```python
Union(ImageSet(Lambda(_n, 2*_n*pi + 3*pi/4), S.Integers), ImageSet(Lambda(_n, 2*_n*pi + 7*pi/4), S.Integers))
```

https://github.com/sympy/sympy/blob/1e2760d8da15fe238abdb9741dadb3b63a3114ec/sympy/calculus/util.py#L141-L145

**Comment by smichr** [comment]
I now get `NotImplementedError: Unable to find critical points for exp(x)*sin(x) - 1`

**Comment by gschintgen** [comment]
I can confirm the `NotImplementedError`, but while investigating `solve_decomposition` I stumbled over worse examples:
```
>>> function_range(tan(x)*sin(2*x), x, S.Reals)
{0}
>>> function_range(tan(x)*sin(2*x + 1), x, S.Reals)
^C^CTraceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/sympy/sympy/calculus/util.py", line 211, in function_range
    solution = solveset(f.diff(symbol), symbol, interval)
  File "/root/sympy/sympy/solvers/solveset.py", line 1700, in solveset
    return solveset(f.xreplace({symbol: r}), r, domain
  File "/root/sympy/sympy/solvers/solveset.py", line 1718, in solveset
    return _solveset(f, symbol, domain, _check=True)
  File "/root/sympy/sympy/solvers/solveset.py", line 907, in _solveset
    result = _solve_trig(f, symbol, domain)
  File "/root/sympy/sympy/solvers/solveset.py", line 539, in _solve_trig
    is yet to be implemented'''))
NotImplementedError:
Solution to this kind of trigonometric equations is yet to be
implemented
```
The first result is plain wrong, the second example hangs indefinitely (or at least it takes longer than I care for).

**Comment by gschintgen** [comment]
Hmm, the first one is a bug in solveset when domain is an interval: #17324

**Comment by gschintgen** [comment]
Disregard my previous comment. The problem is not with solveset but `f` has a removable singularity at `pi/2`. So the problem is with `continuous_domain` that doesn't notice the discontinuity. The correct range for `tan(x)*sin(2*x)` is `[0, 2)`.
(I'll file a separate issue if I have more to add, this is getting off-topic.)

**Comment by gschintgen** [comment]
Here's a reproducer for the original issue (infinite iteration) in current master:
`function_range(sin(x) + x, x, S.Reals)`

Maybe a check for infinite ImageSets should be added after the following check:
https://github.com/sympy/sympy/blob/c91f596b651f137df6fc252b50418df0ccc55745/sympy/calculus/util.py#L213-L214
