### ISSUE TITLE
creating Float explicitly from numpy types can fail

### ISSUE THREAD

**Issue by cbm755** [sympy/sympy#13275]
#11666 improved various `S(<numpy thing>)` but `Float(<numpy thing>)` still gives errors like `TypeError: cannot create mpf from...`

Examples:
````
Float(np.int64(5))
Float(np.float128(5))
Float(np.float32(5))
````

`Float(np.float64(5))` is ok on my computer, possibly because `np.float64` is the same as native python double-precision `float`.

Probably be nice to fix this without duplicating lots of code from the #11666 fix but I haven't looked at it at all so I could be wrong.

**Comment by Trave11er** [comment]
Hello! I would like to work on this issue.

**Comment by cbm755** [comment]
Sure, go for it and send us a PR, see https://github.com/sympy/sympy/wiki/Development-workflow

**Comment by bmgxyz** [comment]
I did a thing. (!) Hope this is useful. First time contributor; please be gentle.

**Comment by bmgxyz** [comment]
Oh, I just noticed this: https://github.com/Trave11er/sympy/commit/246e262bce2dd0706dcdeb21a348727f6c8974bd

Since this thread seemed dead, I thought it would be alright to go ahead and fix this. I'm rather confused now.

**Comment by Trave11er** [comment]
Hi Bradley, that is an unfortunate coincidence - was running tests as your message arrived and it is also the first time for me :) Perhaps, the most diplomatic solution would be to take best bits from both our codes somehow...

**Comment by cbm755** [comment]
Thank you both for your efforts on this so far, these things happen!

May I suggest we work together to try to the find the best fix?  I don't think either PR is ready to merge yet.

**Comment by cbm755** [comment]
Ok I've roughly reviewed both PRs.  If the approach of @bmgxyz works (note: **if**), then I think that might be what we want.  May I suggest a path forward?

1.  You both review each others' work.
2.  Eventually, we rebase and ideally take @Trave11er's testset and @bmgxyz's changes to `Float.__new__`.
3.  don't rebase anything yet.

**Comment by Trave11er** [comment]
Happy to do as you propose, @cbm755.

**Comment by bmgxyz** [comment]
Sounds good to me. Review incoming as soon as I've got some time.

**Comment by cbm755** [comment]
Thanks to both our new contributors for starting, and sticking with, this nice example of collaboration.

**Comment by Trave11er** [comment]
Was a pleasure! Thank you for the gentle introduction into the development of SymPy.

**Comment by bmgxyz** [comment]
My thoughts exactly. Many thanks. :+1:
