### ISSUE TITLE
Fix all pyflakes errors in the rubi module

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#13283]
The rubi module has a lot of code. If you run pyflakes on it, it reports a *lot* of errors, including undefined names. 

pyflakes should be giving no errors anywhere in the rubi module. That way we can be sure there aren't basic logical errors.

**Comment by alirizwi** [comment]
I want to work on this issue.There are around 9717 errors on running pyflakes on rubi module,mostly module imported but unused, undefined names, etc..

**Comment by alirizwi** [comment]
@asmeurer In sympy/integrals/rubi/utility_function.py, few functions like CoprimeQ, LE and PureFunctionOfCothQ are called but not defined. I can add PureFunctionOfCothQ function from http://www.apmaths.uwo.ca/~arich/IntegrationRules/PortableDocumentFiles/Integration%20utility%20functions.pdf , but what about the other functions?

**Comment by parsoyaarihant** [comment]
@alirizwi , you can add those functions in `utility_function.py` file: https://github.com/sympy/sympy/blob/master/sympy/integrals/rubi/utility_function.py
