### ISSUE TITLE
Request: serve SymPy documentation via https

### ISSUE THREAD

**Issue by canavandl** [sympy/sympy#13313]
Currently the entire SymPy site is served via http. It would be nice for the security of users to serve the site via https.

**Comment by asmeurer** [comment]
Main issue at https://github.com/sympy/sympy.github.com/issues/105. The problem is getting https support for SymPy Live and SymPy Gamma, which are both on the app engine. Once we have that, switching to https for the docs and main site will be easy.

**Comment by sidhantnagpal** [comment]
This has been resolved. SymPy [docs](https://docs.sympy.org/latest/index.html) (and related sites) now support https.
