### ISSUE TITLE
New problem with substitution and paranthesis handling

### ISSUE THREAD

**Issue by ttxtea** [sympy/sympy#13333]
Something has changed in the way substitutions work in sympy version 1.1.1. on python3.4.2

```
In [3]: sympy.S('R*F').subs({'R':'8314.4*mjoule/(mole*kelvin)','F':'96484.6*(coulomb/mole)'})
Out[3]: 8314.4*mjoule/(mole*kelvin)*96484.6*(coulomb/mole)

In [4]: sympy.S('R/F').subs({'R':'8314.4*mjoule/(mole*kelvin)','F':'96484.6*(coulomb/mole)'})
Out[4]: 8314.4*mjoule/(mole*kelvin)/96484.6*(coulomb/mole)

```

with sympy 1.0 on python2.7.9 this yielded

```
In [3]: sympy.S('R*F').subs({'R':'8314.4*mjoule/(mole*kelvin)','F':'96484.6*(coulomb/mole)'})
Out[3]: 802211558.24*coulomb*mjoule/(kelvin*mole**2)

In [4]: sympy.S('R/F').subs({'R':'8314.4*mjoule/(mole*kelvin)','F':'96484.6*(coulomb/mole)'})
Out[4]: 0.0861733375067109*mjoule/(coulomb*kelvin)
```

The update seems to have wronged something.

**Comment by jksuom** [comment]
It looks like SymPy is doing exactly what is prescibed:
```
>>> srepr(S('R*F'))
"Mul(Symbol('F'), Symbol('R'))"
>>> srepr(S('R*F').subs({'R':'8314.4*mjoule/(mole*kelvin)','F':'96484.6*(coulomb/mole)'}))
"Mul(Symbol('8314.4*mjoule/(mole*kelvin)'), Symbol('96484.6*(coulomb/mole)'))"
```
Before substitution, `S('R*F')` is a `Mul` expression with two symbols as arguments. The names of the symbols are Python strings and the substitution will replace them with new (long) strings. This should probably not be regarded as an error.

The values in the dictionary, `'8314.4*mjoule/(mole*kelvin)'` and `'96484.6*(coulomb/mole)'`, are Python strings. To obtain SymPy objects, the quotes should be omitted.

**Comment by ttxtea** [comment]
But the division is wrong, isn't it??

**Comment by ttxtea** [comment]
Sorry for the messy example with the "Nernst equation". Maybe this is clearer

```
In [9]: sympy.S('1/a').subs({'a':'2*d/c'})
Out[9]: 1/2*d/c
```
but
```
In [10]: sympy.srepr(sympy.S('1/a').subs({'a':'2*d/c'}))
Out[10]: "Pow(Symbol('2*d/c'), Integer(-1))"
```

**Comment by ttxtea** [comment]
Note that it is probably the repr() function that causes the problem. In `isympy`, where the output is based on `srepr` it is fine. So maybe the bug is somewhere in the `__repr__` function?

A workaround is to use additional parenthesis. like

`sympy.S('1/a').subs({'a':'(2*d/c)'})`

But the backwards compatibility to sympy 1.0 is not given and projects like `brian2` have problems with old model definitions.
