### ISSUE TITLE
Minor error in Matrices tutorial

### ISSUE THREAD

**Issue by wdscxsj** [sympy/sympy#13373]
In the [RREF section](http://docs.sympy.org/latest/tutorial/matrices.html#rref) of the Matrices tutorial, the note says "The second is of type `list`." The actual type should be `tuple`.

**Comment by bjodah** [comment]
@wdscxsj thanks, we welcome any corrections. You can fix this even using github's built in editor, here's the source file: https://github.com/sympy/sympy/blob/master/doc/src/tutorial/matrices.rst

(you can click the pen in the top right).

**Comment by wdscxsj** [comment]
Thanks for the tip! Fix proposed.

**Comment by gxyd** [comment]
You will also need to send in a pull request against SymPy master. Probably you have just created a commit on your branch. So now you need to send a PR. :)

**Comment by wdscxsj** [comment]
Thank you. I guess it's OK this time.
