### ISSUE TITLE
Add release dates to the release notes

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#13385]
The release notes on the wiki (https://github.com/sympy/sympy/wiki/Release-Notes) do not have the release dates for the release. The release date can be found from the tag metadata at https://github.com/sympy/sympy/releases (use the final release), or from the news section at http://www.sympy.org/en/index.html.  The date should be added to the top of the page (like 
"SymPy 1.0 was released on ...").

We should also probably automate that somehow, but that's also related to the release notes revamping/automating that I'd like to do.

**Comment by kenogo** [comment]
Can I just go ahead and add these in the wiki?

**Comment by asmeurer** [comment]
Yep, just do it. Let us know when it's done so we can close this issue.

**Comment by kenogo** [comment]
Ok I'm done, you can close this.

**Comment by asmeurer** [comment]
Thanks.
