### ISSUE TITLE
Incorrect Result for limit(n*(((n+1)**2+1)/((n)**2+1)-1), n ,oo)

### ISSUE THREAD

**Issue by Shikhar1998** [sympy/sympy#13382]
```
>>> import sympy
>>> from sympy.abc import n
>>> limit(n*(((n + 1)**2 + 1)/(n**2 + 1) - 1), n, oo)
0
```
The answer should be `2`.

**Comment by czgdp1807** [comment]
Closing in reference to, https://github.com/sympy/sympy/issues/18265

**Comment by czgdp1807** [comment]
Reopening in reference to https://github.com/sympy/sympy/issues/18265#issuecomment-572227687
