### ISSUE TITLE
physics.vector.Vector should have atoms and free_symbols

### ISSUE THREAD

**Issue by moorepants** [sympy/sympy#13398]
It would be nice to be able to call `free_symbols` on a physics vector and it works as it does with any expression. It would also be nice if `find_dynamicsymbols` worked with vectors. A current hack is to convert to a matrix then use these functions.

**Comment by dineshsuthar786** [comment]
Hello, I would like to work on this Issue.

**Comment by gxyd** [comment]
Yes, you can send in a PR.

**Comment by dineshsuthar786** [comment]
Can Someone explain, what needs to be done as part of this?

**Comment by moorepants** [comment]
To start, this should work:

```python
import sympy as sm
import sympy.physics.mechanics as me
a, b, c = sm.symbols('a, b, c')
A = me.ReferenceFrame('A')
v = a * A.x + b * A.y + c * A.z
me.find_dynamicsymbols(v)
```

**Comment by prajwalgatti** [comment]
@moorepants Can you explain what free_symbols and find_dynamicsymbols functions are meant to do?

**Comment by moorepants** [comment]
Note that this works:

```
me.find_dynamicsymbols(v.to_matrix(A))
```

and this works:

```
v.to_matrix(A).free_symbols
```

I think that these functions will need to have a reference frame as an argument, just like express because they may be functions of different scalars depending on what reference frame they are viewed from.

**Comment by prajwalgatti** [comment]
> @moorepants Excuse me if this is a silly question, but shouldn't a, b and c be declared as dynamic symbols if find_dynamicsymbols is supposed to return them when v is passed as an argument?

**Comment by moorepants** [comment]
Yes, that is a mistake I made above. Change to:

```python
import sympy as sm
import sympy.physics.mechanics as me
a, b, c = me.dynamicsymbols('a, b, c')
A = me.ReferenceFrame('A')
v = a * A.x + b * A.y + c * A.z
me.find_dynamicsymbols(v)
```

**Comment by prajwalgatti** [comment]
Can you please elaborate a bit more on why the reference frame needs to be taken as an argument?
I'm new to this and I am interested in finding a solution for this

**Comment by moorepants** [comment]
The vectors are functions of scalar variables when viewed from a particular reference frame. If viewed from different reference frames the may be functions of different scalar variables or none at all.

**Comment by tosalonijain** [comment]
@moorepants I am new to open source but am interested to take up this issue.
Cant this be fixed by adding a default argument to free_symbols and find_dynamicsymbols asking for  Reference frame and then internally convert these vectors to matrix using v.to_matrix(A) ??
Or we can allow physics.vector.Vector to have atoms, so with only the argument of a vector to find_dynamicsymbols we can have the desired result. 
Which way is preferred ?
Please guide me to fix this issue.

**Comment by moorepants** [comment]
That all sounds find. Please submit a pull request and we can review what you do there.

**Comment by tosalonijain** [comment]
@moorepants I tried some modifications and the consequences are depicted by the following code:
>>> import sympy as sm
>>> import sympy.physics.mechanics as me
>>> a, b, c = me.dynamicsymbols('a, b, c')
>>> A = me.ReferenceFrame('A')
>>> v = a * A.x + b * A.y + c * A.z
>>> v.free_symbols(A)
{t}
>>> me.find_dynamicsymbols(v,reference_frame=A)
{b(t), a(t), c(t)}

You may find the same code over pastebin through- https://pastebin.com/T3NYqkWt
Please guide me over this issue and suggest possible changes.

**Comment by tosalonijain** [comment]
Hey I have sent a pull request, please review.
Thanks.
