### ISSUE TITLE
fix TEST_SAGE=yes Travis script

### ISSUE THREAD

**Issue by rwst** [sympy/sympy#13395]
As discovered in #13392 the Travis testing of the SymPy --> Sage interface is non-functional. The test that should have failed was in #12826, the job log is https://travis-ci.org/sympy/sympy/jobs/257302234.

I'm not suggesting the fix is important, as we will have that testing in official Sage soon, but it may bite folks installing newer SymPy versions with Sage.

**Comment by ylemkimon** [comment]
Adding `sage -t sympy/external/tests/test_sage.py` to Travis `TEST_SAGE` build seems to raise following error:
```
init.sage does not exist ... creating
Traceback (most recent call last):
  File "/usr/lib/sagemath/local/bin/sage-runtests", line 88, in <module>
    DC = DocTestController(options, args)
  File "/usr/lib/sagemath/local/lib/python2.7/site-packages/sage/doctest/control.py", line 318, in __init__
    for pkg in list_packages('optional', local=True).values():
  File "/usr/lib/sagemath/local/lib/python2.7/site-packages/sage/misc/package.py", line 230, in list_packages
    for p in os.listdir(SAGE_PKGS):
OSError: [Errno 2] No such file or directory: '/usr/lib/sagemath/build/pkgs'
```

**Comment by rwst** [comment]
That looks like a serious Sage installation problem. Is Sage reinstalled from scratch every time? That would strain Travis quite a bit. If so then, honestly, testing the SymPy/Sage interface for every SymPy PR seems big time overkill to me.

**Comment by ylemkimon** [comment]
Yes, it reinstalls `sagemath-upstream-binary` from scratch, from `ppa:aims/sagemath` using `apt` like [Job #24412.30](https://travis-ci.org/sympy/sympy/jobs/286021892):
https://github.com/sympy/sympy/blob/41e59dd7e92350a90c792944953a7203325a6c4a/.travis.yml#L265-L269

**Comment by rwst** [comment]
Ah you install binary. That is much lighter. It seems the Sage doctester needs a source installation, so the command `sage -t` fails with a binary distribution. I have no idea if it helps to provide the Sage git source without actually building Sage.

Really, it's much easier to do this all when installing SymPy in Sage.

**Comment by rwst** [comment]
From discussion in #13430 it appears we can install SymPy master in a Sage binary distribution and run its tests by giving in Sage:
```
sage: import sys
sage: sys.path.append(path-to-sympy-egg)
sage: import sympy
sage: sympy.test('sympy/external/tests/test_sage.py')
```
so it looks Travis testing is possible. Note: I only tested this on a source installation.

**Comment by rwst** [comment]
You could put the 4 lines (without the `sage:` prefix) in a Python script and run `./sage -python t.py`, parsing the output.

**Comment by rwst** [comment]
No, I checked too late, this does NOT work unless one gives the test option `subprocess=False`. Comment is edited.

**Comment by asmeurer** [comment]
@isuruf can we install Sage on Travis with conda-forge? And if so, does `sage -t` work (according to @rwst above, it needs to be a source installation)?

**Comment by isuruf** [comment]
I do install sage with conda-forge here, https://github.com/symengine/symengine.py/blob/a12f736514baaa0ba457bd0250b511075bf1fc0e/bin/install_travis.sh#L20

I don't know whether `sage -t` works.

**Comment by asmeurer** [comment]
I guess we should give it a try.
