### ISSUE TITLE
Incorrect Result for limit(n*(-1 + (n + log(n + 1) + 1)/(n + log(n))), n ,oo)

### ISSUE THREAD

**Issue by Shikhar1998** [sympy/sympy#13403]
Calculation of the following limit gives an incorrect result:
```>>> import sympy
>>> from sympy.abc import n
>>> limit(n*(-1 + (n + log(n + 1) + 1)/(n + log(n))), n ,oo)
oo
```

The answer should have been  `1`.

**Comment by gxyd** [comment]
You can use 'triple backticks' https://help.github.com/articles/basic-writing-and-formatting-syntax/#quoting-code to better format the code.

**Comment by Shikhar1998** [comment]
Thanks, for the advice, I will surely do that in future.

**Comment by czgdp1807** [comment]
Closing in reference to, #18265

**Comment by czgdp1807** [comment]
Reopening in reference to https://github.com/sympy/sympy/issues/18265#issuecomment-572227687
