### ISSUE TITLE
Incorrect Result for limit((-n**3*log(n)**3 + (n - 1)*(n + 1)**2*log(n + 1)**3)/(n**2*log(n)**3), n ,oo) 

### ISSUE THREAD

**Issue by Shikhar1998** [sympy/sympy#13416]
```
>>> from sympy.abc import n
>>> limit((-n**3*log(n)**3 + (n - 1)*(n + 1)**2*log(n + 1)**3)/(n**2*log(n)**3), n ,oo) 
-1
```
The correct answer should have been 1.

**Comment by Upabjojr** [comment]
Apparently it's been fixed on _diofant_. I keep suggesting to merge the improvements on the limits algorithm from _diofant_.

**Comment by czgdp1807** [comment]
Closing in reference to, #18265

**Comment by czgdp1807** [comment]
Reopening in reference to https://github.com/sympy/sympy/issues/18265#issuecomment-572227687
