### ISSUE TITLE
Improve docstring of matrices/matrices.py

### ISSUE THREAD

**Issue by gxyd** [sympy/sympy#13449]
The docstring of functions in matrices/matrices.py looks ugly. Since it should use double backticks for functions mention instead of single backtick.

Look at PR #12726 .

**Comment by vishalg2235** [comment]
Hey. I'm new to sympy and open-source.
So should I change all the single backticks from all comments to double backticks ?

**Comment by yashkgp** [comment]
Hey! @gxyd  , Can I work on this issue?

**Comment by gxyd** [comment]
We don't need to change all single backticks to double backticks. Rather the ones which represent code, like `self` in most of the cases should be double ticked, also there are functions names that are there those should also be double back-ticked.

@yashkgp let's please wait for @vishalg2235 and see if he sends in a PR. If he says he isn't working on it, you can then send in a PR.

**Comment by jksuom** [comment]
Also, only docstrings need be considered. Comments elsewhere do not appear in documents.

**Comment by vishalg2235** [comment]
`"""Return the submatrix obtained by removing the `i`th row
        and `j`th column from ``self``.

        See Also
        ========

        minor
        cofactor
        """`
@gxyd  Here should I also doubletick i and j ?

**Comment by ayush1999** [comment]
Ping. Is this still open?

**Comment by gxyd** [comment]
This issue is open but we already have two PR's submitted for this issue.

**Comment by tosalonijain** [comment]
@gxyd can I work now on this issue as there's quite passive participation here?
Thanks

**Comment by abhigyank** [comment]
@gxyd  There seems to be no active PR on this, can I work on this issue?

**Comment by divyanshu132** [comment]
@gxyd can I take this??

**Comment by czgdp1807** [comment]
@divyanshu132 Is this fixed by your PR https://github.com/sympy/sympy/pull/15950 ?

**Comment by divyanshu132** [comment]
@czgdp1807 thanks for pointing out, I think this can be closed.
