### ISSUE TITLE
_eval_diff vs. _eval_derivative

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#13457]
Why do we have both _eval_diff and _eval_derivative? It seems the difference is that _eval_derivative is called inside Derivative, whereas _eval_diff is called inside diff(). It was added in https://github.com/sympy/sympy/commit/d86f737d11b75165d1a050f4636be90b6e9222cd but the commit message doesn't mention it. 

Is there anything that _eval_diff does that _eval_derivative cannot do? If not, I think we should remove it. Otherwise, it needs to be documented. 

CC @Upabjojr

**Comment by Upabjojr** [comment]
I guess the easiest explanation is that `diff` used to require the deriving variable to be a `Symbol`. In order to allow other objects to be derived wrt, `_eval_diff` has been created as a shortcut.

**Comment by asmeurer** [comment]
Is it no longer necessary? I guess if we remove it we should deprecate it, as it's apparently been there for some time (although undocumented).

**Comment by Upabjojr** [comment]
We now have `is_symbol` vs `is_Symbol`, and the lowercase is enough to be derivable wrt.

Just consider that my message above is just a guess.

**Comment by Upabjojr** [comment]
I have used `_eval_diff` in the past. If we are going to remove it, no deprecation is necessary as it is private API.

**Comment by asmeurer** [comment]
Your explanation makes sense. The code before [`_eval_derivative`](https://github.com/sympy/sympy/blob/d85689709985f508f99fcd31ea61b2415196a221/sympy/core/function.py#L1186) is called all deals with normalizing the variables. Particularly:

- Automatic variable for expressions with one free symbol,  like `diff(sin(x))` 

- Sorting of variables and canonicalization (like (x, x) -> (x, 2))

- Checking for symbols not in free_symbols

The free_symbols checking is already disabled if the variables are not instances of Symbol. I suppose there could be instances where you'd want to disable sorting, but if that comes up, we should just add a way to disable it in Derivative.
