### ISSUE TITLE
Why not incorporate Maxima?

### ISSUE THREAD

**Issue by JohnStone2017** [sympy/sympy#13466]
I mean this with all due respect. This page describes some features of Maxima lacking in SymPy:

https://github.com/sympy/sympy/wiki/SymPy-vs.-Maxima

For Maxima-features not implemented in SymPy, why not have SymPy call Maxima for the answer? If necessary, a LISP could be implemented within SymPy to support Maxima; LISP would not be hard to implement in Python.

**Comment by ylemkimon** [comment]
You can use [Sage](http://www.sagemath.org/) for integrating various mathematical packages. It includes SymPy, Maxima, as well as many other useful and powerful packages.

**Comment by JohnStone2017** [comment]
That is a good point, thanks.

**Comment by asmeurer** [comment]
SymPy aims to be a full featured CAS. While we are open to external dependencies, we prefer ones that are native to Python, and we would require a BSD compatible license (Maxima is GPL). As @ylemkimon pointed out, Sage is the more appropriate project for glueing distinct computer computer algebra systems into a coherent system. If you look closely at what Sage does, this is not a simple problem by any means.
