### ISSUE TITLE
dsolve gives correct solution

### ISSUE THREAD

**Issue by ferhatpy** [sympy/sympy#13477]
y''+y'=sinx

eq=Eq(y.diff(x,2)+y.diff(x),sin(x))
dsolve(eq,y,hint="nth_linear_constant_coeff_undetermined_coefficients")
gives a wrong answer. It gives 
C1 + C2*exp(-x) - sin(x)/2 - cos(x)/2
but it must be
(-(x/2) + C[1]) Cos[x] + C[2] Sin[x]
why?

**Comment by ylemkimon** [comment]
It seems correct. See [WolframAlpha](http://www.wolframalpha.com/input/?i=y%27%27%2By%27%3Dsin(x)).

**Comment by ferhatpy** [comment]
I'm really sorry that I have written the wrong equation and compared its solution with an another differential equation's solution.
The challenging one is the following,
y''+y=sinx

eq=Eq(y.diff(x,2)+y,sin(x))
dsolve(eq,y)
and SymPy gives the correct answer. 
Eq(y(x), C2*sin(x) + (C1 - x/2)*cos(x))

Also the solution for the previous equation is true.
Many thanks to the developers.

All codes:
x = symbols("x")
y = Function('y')(x) 
eq=Eq(y.diff(x,2)+y, sin(x))
sol=dsolve(eq,y)
sol
