### ISSUE TITLE
Add tests for normalized hydrogen wave functions psi_{nlm}

### ISSUE THREAD

**Issue by gxyd** [sympy/sympy#13481]
To complete PR #12164 add tests for it.

**Comment by Trave11er** [comment]
I would like to work on this issue.

**Comment by Trave11er** [comment]
Added tests for `Psi_{nlm}` as implemented in #12164 and removed a duplicate line from test_spherical_harmonics.py. Also, for me the `integrate(...)` example in the docstring failed to calculate.
