### ISSUE TITLE
High level lambdify documentation

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#13482]
We need some high level documentation on how lambdify works. A simple explanation of what it does (print and eval an expression as a Python lambda in a separate namespace) can go a long way to using it properly and understanding what is going on when it does something unexpected. 

I would either put it in the lambdify docstring, or, if it ends up being too long, a Sphinx document that is referenced in the lambdify docstring.

**Comment by czgdp1807** [comment]
I am a beginner, can I work on this?

**Comment by asmeurer** [comment]
I have the pull request https://github.com/sympy/sympy/pull/13485 but there are some sphinx errors and I haven't had the time to figure them out. If you can figure out what is going on it would help a lot.
