### ISSUE TITLE
lambdify doctests are not run

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#13483]
The `doctest_depends_on` decorator for `lambdify` is written incorrectly, and the doctests are not run. It uses `modules=('numpy')` instead of `modules=('numpy',)`. So you get, with `./bin/doctest -v lambdify`

```
sympy/utilities/lambdify.py[4]
sympy.utilities.lambdify.implemented_function ok
sympy.utilities.lambdify._imp_namespace ok
sympy.utilities.lambdify.lambdastr ok
Could not import None s
```

We should also check if other doctests have the same problem.

**Comment by asmeurer** [comment]
There is a partial fix at https://github.com/sympy/sympy/pull/13485, but I need some help figuring out some of the doctest failures in lambdify. Also, someone still needs to audit the codebase to make sure there aren't other doctests not being run, and we should also probably improve the `doctest_depends_on` to avoid issues like this in the future.

**Comment by tosalonijain** [comment]
Hey @asmeurer can I work on this issue?

**Comment by asmeurer** [comment]
Yes, you can base you work off my branch. I'm not currently working on it.

**Comment by asmeurer** [comment]
Or really just off https://github.com/sympy/sympy/pull/13485/commits/1f8bd0b658bbca90bfe87b0a61192346ac99467a. The other changes there aren't related to this issue.

**Comment by caley** [comment]
The problem with printing of numpy arrays mentioned in https://github.com/sympy/sympy/commit/1f8bd0b658bbca90bfe87b0a61192346ac99467a is related to changes to the DoctestRunner for #5140: https://github.com/sympy/sympy/blob/e154e8df5aa1718ab043c2a1a4a0c690651a1bfa/sympy/utilities/runtests.py#L1717-L1728

The sympy code avoids resetting sys.displayhook, and on my system at least, this results in the doctest output not matching interactive output (I've tried python 3.5 and 2.7 on a mac).

An example in the code base: https://github.com/sympy/sympy/blob/e154e8df5aa1718ab043c2a1a4a0c690651a1bfa/sympy/matrices/dense.py#L981-L983
This currently passes the sympy doctest.  But interactively
```
>>> from sympy import symarray
>>> symarray('', 3)
array([_0, _1, _2], dtype=object)
```

The difference seems to be that displayhook (under the sympy doctest) is using `str` instead of `repr`:
```
>>> print(str(symarray('', 3)))
[_0 _1 _2]
>>> print(repr(symarray('', 3)))
array([_0, _1, _2], dtype=object)
```

**Comment by asmeurer** [comment]
My [repr-doctests](https://github.com/asmeurer/sympy/tree/repr-doctests) branch has the basic change needed to make the doctests use repr. An easy to fix patch for someone would be to take my branch, run the doctests, and fix them all so they use the repr output (some outputs that use strings may need to change to use `print()` if the repr form is hard to read).

**Comment by caley** [comment]
With the repr patch I got this:
```
File ".../sympy/sympy/crypto/crypto.py", line 1588, in sympy.crypto.crypto.lfsr_sequence
Failed example:
    lfsr_sequence(key, fill, 10)
Expected:
    [1 mod 2, 1 mod 2, 0 mod 2, 1 mod 2, 0 mod 2,
    1 mod 2, 1 mod 2, 0 mod 2, 0 mod 2, 1 mod 2]
Got:
    [SymmetricModularIntegerMod2(1), SymmetricModularIntegerMod2(1), SymmetricModularIntegerMod2(0), SymmetricModularIntegerMod2(1), SymmetricModularIntegerMod2(0), SymmetricModularIntegerMod2(1), SymmetricModularIntegerMod2(1), SymmetricModularIntegerMod2(0), SymmetricModularIntegerMod2(0), SymmetricModularIntegerMod2(1)]
```
This matches what you get in an interactive session if you haven't called `init_printing()`, but really is not nice.  Perhaps it's best to leave the doctests as they currently are?  Maybe note somewhere in the documentation that the examples assume `init_printing()` has been called?

**Comment by asmeurer** [comment]
Certain doctests that don't look good with repr can be modified to use print() or pprint()

**Comment by asmeurer** [comment]
Also does that class use the sympy printing machinery? Any class that does should have the same repr and str. This would only affect non-sympy types.

**Comment by asmeurer** [comment]
CC @oscarbenjamin
