### ISSUE TITLE
Add tests for added attribute 'usebackend' for Plot

### ISSUE THREAD

**Issue by gxyd** [sympy/sympy#13516]
The task is to complete the closed PR #11983. In which I think (all) necessary changes were made for introducing attribute `backend` but no test cases were added.

Also address a few minor comments mentioned on PR #11983.

We would need to 'use the commits' of PR #11983  and on top of those add test cases for it.

**Comment by Dragneel7** [comment]
@gxyd Hello, I am new to open source and am interested in contributing to this issue.May I work on this issue?

**Comment by amitmanchanda1995** [comment]
Hi @gxyd. 
Could you please review my pull request? 
Thanks

**Comment by NoumbissiValere** [comment]
@asmeurer is this issue still open i will like to work on it
