### ISSUE TITLE
Address changes 'parameter' finding function

### ISSUE THREAD

**Issue by gxyd** [sympy/sympy#13515]
Address the requested changes in PR #11069. The name of the function could be `parameter_value`, but when does submit PR for this issue, we can decide as to what will be a good choice of name.

**Comment by yashkgp** [comment]
Hey @gxyd Can i work on this Issue?

**Comment by gxyd** [comment]
Yes, you can work on it. No PR has been submitted.

**Comment by yashkgp** [comment]
Hey @gxyd Do you want a seperate function for testing of `parameter_value` function or I'll just add it in `test_contains`?

**Comment by gxyd** [comment]
A separate test function `test_parameter_value` would be better I think.

**Comment by yashkgp** [comment]
Hey @gxyd ,I have send a pull request.Can you please review it?
P.S : Its my first PR .

**Comment by yashkgp** [comment]
Hey @gxyd I have a send a PR again with the requested changes .
PR #13539

**Comment by tosalonijain** [comment]
Hey @gxyd can I work on this issue if no one is working presently on it?

**Comment by gxyd** [comment]
There is already a PR in progress https://github.com/sympy/sympy/pull/13539 to fix this issue.

**Comment by abhigyank** [comment]
@gxyd No update has been on the PR since more than 10 days. Can I start working on this?

**Comment by gxyd** [comment]
@abhigyank yes we have to work to do on this issue but somewhat different from what has been described in this issue. See this comment by @smichr https://github.com/sympy/sympy/pull/13539#issuecomment-351415822 . So I think he has already opened an issue for that, see https://github.com/sympy/sympy/issues/13789 , let me know if you have any trouble with understanding the status of the issue.

**Comment by gxyd** [comment]
Also PR https://github.com/sympy/sympy/pull/13790 is an attempt at closing the issue https://github.com/sympy/sympy/issues/13789 . So I guess @saurabhkgp21 is working on it.
