### ISSUE TITLE
Improve fluid mechanics PR

### ISSUE THREAD

**Issue by gxyd** [sympy/sympy#13514]
See PR #12611 . We need to address the comments mentioned on that PR.
Also at the very least need tests cases to check for the functionality. More functionality could be added to but that can be a separate issue.

**Comment by ashishkg0022** [comment]
@gxyd can you please review my pr ? #13554

**Comment by gxyd** [comment]
Quoting @Upabjojr here
> I just don't see why this code could be helpful to anyone.

Also it seems better to close this issue.
