### ISSUE TITLE
Complete PR #10686 by adding 'coulombs_constant'

### ISSUE THREAD

**Issue by gxyd** [sympy/sympy#13528]
See PR #10686 . Address the requested changes on that PR.

**Comment by shivam207** [comment]
coulombs_constant is already added in units/definitions.py .
`# vacuum impedance:
Z0 = vacuum_impedance = Quantity("vacuum_impedance", impedance, u0 * c)
# Coulomb's constant:
coulomb_constant = electric_force_constant = Quantity("coulomb_constant", force*length**2/charge**2, 1/(4*pi*vacuum_permittivity), abbrev="k_e")`

**Comment by Sayan98** [comment]
@gxyd this seems to have been solved, check [here](https://github.com/sympy/sympy/blob/67e3c956083d0128a621f65ee86a7dacd4f9f19f/sympy/physics/units/definitions.py#L152).

**Comment by Shikhar1998** [comment]
@gxyd, both `molar_gas_constant` and `coulombs_constant` do exist in `sympy/physics/units/definitions.py`.  So, I think this issue can be closed.

**Comment by RISHAV98** [comment]
I would like to work on this issue...If it is still open

**Comment by gxyd** [comment]
I'm closing this, it was fixed by https://github.com/sympy/sympy/pull/13548. That PR should had reference this issue.
