### ISSUE TITLE
Mod(Mod(x + 1, 2) + 1, 2) should simplify to Mod(x, 2)

### ISSUE THREAD

**Issue by smichr** [sympy/sympy#13543]
From [stackoverflow](https://stackoverflow.com/questions/46914006/modulo-computations-in-sympy-fail)

Also, something like `Mod(foo*Mod(x + 1, 2) + non_mod_terms + 1, 2)` could be simplified. Recursively.

**Comment by ashishkg0022** [comment]
@smichr can you please review the pull request
