### ISSUE TITLE
Problem with discrete sampling

### ISSUE THREAD

**Issue by sswatson** [sympy/sympy#13576]
The code 
```python
from sympy import S
from sympy.stats import Geometric, sample
X = Geometric("X",S(1)/2)
sample(X)
```
throws an error (`global name 'floor' is not defined`). I found the same issue with `Poisson` as well.

**Comment by ylemkimon** [comment]
https://github.com/sympy/sympy/pull/13583#issuecomment-343524339 by @akash9712 
> Importing floor does not solve the issue. floor recieves a boolean value from _inverse_cdf_expression, which raises a TypeError.
