### ISSUE TITLE
Allow passing a printer to codegen()

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#13586]
The most common reason to pass a custom code_gen object to codegen() is to specify the printer. We should just add a printer flag to codegen(). See for instance http://www.sympy.org/scipy-2017-codegen-tutorial/notebooks/08-cythonizing.html#5.-Using-a-Custom-Printer-and-an-External-Library-with-autowrap.

**Comment by yash-iiith** [comment]
I would like to work on this.
