### ISSUE TITLE
limit(tan(tan(x)), x, -oo) causes recursion error

### ISSUE THREAD

**Issue by ethankward** [sympy/sympy#13585]
>>> from sympy import *
    >>> from sympy.abc import x
    >>> limit(tan(tan(x)), x, oo)
    tan(tan(zoo))
    >>> limit(tan(tan(x)), x, -oo)
    Traceback (most recent call last):
      File "<pyshell#3>", line 1, in <module>
                        limit(tan(tan(x)), x, -oo)
      File "C:\Users\E\AppData\Local\Programs\Python\Python36\lib\site-packages\sympy\series\limits.py", line 49, in limit
                        return Limit(e, z, z0, dir).doit(deep=False)
      File "C:\Users\E\AppData\Local\Programs\Python\Python36\lib\site-packages\sympy\series\limits.py", line 180, in doit
                        r = gruntz(e, z, z0, dir)
      File "C:\Users\E\AppData\Local\Programs\Python\Python36\lib\site-packages\sympy\series\gruntz.py", line 650, in gruntz
                        r = limitinf(e.subs(z, -z), z)
      File "C:\Users\E\AppData\Local\Programs\Python\Python36\lib\site-packages\sympy\core\cache.py", line 93, in wrapper
                        retval = cfunc(*args, **kwargs)
      File "C:\Users\E\AppData\Local\Programs\Python\Python36\lib\site-packages\sympy\series\gruntz.py", line 428, in limitinf
                        c0, e0 = mrv_leadterm(e, x)
      File "C:\Users\E\AppData\Local\Programs\Python\Python36\lib\site-packages\sympy\core\cache.py", line 93, in wrapper
                        retval = cfunc(*args, **kwargs)
      File "C:\Users\E\AppData\Local\Programs\Python\Python36\lib\site-packages\sympy\series\gruntz.py", line 513, in mrv_leadterm
                        series = calculate_series(f, w, logx=logw)
      File "C:\Users\E\AppData\Local\Programs\Python\Python36\lib\site-packages\sympy\series\gruntz.py", line 472, in calculate_series
                        if t.simplify():
      File "C:\Users\E\AppData\Local\Programs\Python\Python36\lib\site-packages\sympy\core\expr.py", line 3096, in simplify
                        return simplify(self, ratio, measure)
      File "C:\Users\E\AppData\Local\Programs\Python\Python36\lib\site-packages\sympy\simplify\simplify.py", line 515, in simplify
                        original_expr = expr = signsimp(expr)
      File "C:\Users\E\AppData\Local\Programs\Python\Python36\lib\site-packages\sympy\simplify\simplify.py", line 375, in signsimp
                        e = sub_post(sub_pre(expr))
      File "C:\Users\E\AppData\Local\Programs\Python\Python36\lib\site-packages\sympy\simplify\cse_opts.py", line 25, in sub_pre
                        for a in sorted(e.atoms(Add), key=default_sort_key):
      File "C:\Users\E\AppData\Local\Programs\Python\Python36\lib\site-packages\sympy\core\compatibility.py", line 461, in default_sort_key
                        return item.sort_key(order=order)
      File "C:\Users\E\AppData\Local\Programs\Python\Python36\lib\site-packages\sympy\core\cache.py", line 93, in wrapper
                        retval = cfunc(*args, **kwargs)
      File "C:\Users\E\AppData\Local\Programs\Python\Python36\lib\site-packages\sympy\core\expr.py", line 78, in sort_key
                        args = expr.as_ordered_terms(order=order)
      File "C:\Users\E\AppData\Local\Programs\Python\Python36\lib\site-packages\sympy\core\expr.py", line 944, in as_ordered_terms
                        terms, gens = self.as_terms()
      File "C:\Users\E\AppData\Local\Programs\Python\Python36\lib\site-packages\sympy\core\expr.py", line 983, in as_terms
                        coeff *= complex(factor)
      File "C:\Users\E\AppData\Local\Programs\Python\Python36\lib\site-packages\sympy\core\expr.py", line 243, in __complex__
                        re, im = result.as_real_imag()
      File "C:\Users\E\AppData\Local\Programs\Python\Python36\lib\site-packages\sympy\core\power.py", line 962, in as_real_imag
                        return expr.as_real_imag()
      File "C:\Users\E\AppData\Local\Programs\Python\Python36\lib\site-packages\sympy\core\power.py", line 962, in as_real_imag
                        return expr.as_real_imag()
      File "C:\Users\E\AppData\Local\Programs\Python\Python36\lib\site-packages\sympy\core\power.py", line 962, in as_real_imag
                        return expr.as_real_imag()
      [Previous line repeated 946 more times]
      File "C:\Users\E\AppData\Local\Programs\Python\Python36\lib\site-packages\sympy\core\power.py", line 954, in as_real_imag
                        re, im = self.base.as_real_imag(deep=deep)
      File "C:\Users\E\AppData\Local\Programs\Python\Python36\lib\site-packages\sympy\functions\elementary\trigonometric.py", line 1061, in as_real_imag
                        re, im = self._as_real_imag(deep=deep, **hints)
      File "C:\Users\E\AppData\Local\Programs\Python\Python36\lib\site-packages\sympy\functions\elementary\trigonometric.py", line 61, in _as_real_imag
                        re, im = self.args[0].expand(deep, **hints).as_real_imag()
      File "C:\Users\E\AppData\Local\Programs\Python\Python36\lib\site-packages\sympy\core\expr.py", line 1717, in as_real_imag
                        if hints.get('ignore') == self:
      File "C:\Users\E\AppData\Local\Programs\Python\Python36\lib\site-packages\sympy\core\basic.py", line 321, in __eq__
                        other = _sympify(other)
      File "C:\Users\E\AppData\Local\Programs\Python\Python36\lib\site-packages\sympy\core\sympify.py", line 387, in _sympify
                        return sympify(a, strict=True)
      File "C:\Users\E\AppData\Local\Programs\Python\Python36\lib\site-packages\sympy\core\sympify.py", line 256, in sympify
                        raise SympifyError(a)
    RecursionError: maximum recursion depth exceeded

**Comment by Sayan98** [comment]
Could reproduce. Here's additional debug info:

```
In [3]: limit(tan(tan(x)), x, -oo)
DEBUG: parsing of expression [(0, 1, None, None)] with symbol _w
DEBUG: returned None
DEBUG: parsing of expression [(_w, 1, None, None)] with symbol _w
DEBUG: returned ([], [(_w, 1, None, None)], 1, False)
DEBUG: parsing of expression [(_w, 1, None, None)] with symbol _w
DEBUG: returned ([], [(_w, 1, None, None)], 1, False)
DEBUG: parsing of expression [(0, 1, None, None)] with symbol _w
DEBUG: returned None
DEBUG: parsing of expression [(_w, 1, None, None)] with symbol _w
DEBUG: returned ([], [(_w, 1, None, None)], 1, False)
DEBUG: parsing of expression [(0, 1, None, None)] with symbol _w
DEBUG: returned None
DEBUG: parsing of expression [(_w, 1, None, None)] with symbol _w
DEBUG: returned ([], [(_w, 1, None, None)], 1, False)
DEBUG: parsing of expression [(_w, 1, None, None)] with symbol _w
DEBUG: returned ([], [(_w, 1, None, None)], 1, False)
DEBUG: parsing of expression [(0, 1, None, None)] with symbol _w
DEBUG: returned None
DEBUG: parsing of expression [(_w, 1, None, None)] with symbol _w
DEBUG: returned ([], [(_w, 1, None, None)], 1, False)
DEBUG: parsing of expression [(_w, 1, None, None)] with symbol _w
DEBUG: returned ([], [(_w, 1, None, None)], 1, False)
DEBUG: parsing of expression [(0, 1, None, None)] with symbol _w
DEBUG: returned None
DEBUG: parsing of expression [(_w, 1, None, None)] with symbol _w
DEBUG: returned ([], [(_w, 1, None, None)], 1, False)
DEBUG: parsing of expression [(0, 1, None, None)] with symbol _w
DEBUG: returned None
DEBUG: parsing of expression [(_w, 1, None, None)] with symbol _w
DEBUG: returned ([], [(_w, 1, None, None)], 1, False)
DEBUG: parsing of expression [(_w, 1, None, None)] with symbol _w
DEBUG: returned ([], [(_w, 1, None, None)], 1, False)
DEBUG: parsing of expression [(0, 1, None, None)] with symbol _w
DEBUG: returned None
DEBUG: parsing of expression [(_w, 1, None, None)] with symbol _w
DEBUG: returned ([], [(_w, 1, None, None)], 1, False)
DEBUG: parsing of expression [(0, 1, None, None)] with symbol _w
DEBUG: returned None
DEBUG: parsing of expression [(_w, 1, None, None)] with symbol _w
DEBUG: returned ([], [(_w, 1, None, None)], 1, False)
DEBUG: parsing of expression [(_w, 1, None, None)] with symbol _w
DEBUG: returned ([], [(_w, 1, None, None)], 1, False)
DEBUG: parsing of expression [(0, 1, None, None)] with symbol _w
DEBUG: returned None
DEBUG: parsing of expression [(_w, 1, None, None)] with symbol _w
DEBUG: returned ([], [(_w, 1, None, None)], 1, False)
Rule: TR2
In:   tan(zoo)
Out:  sin(zoo)/cos(zoo)

Rule: TR2i
In:   sin(zoo)/cos(zoo)
Out:  tan(zoo)

Rule: TR2
In:   tan(zoo)
Out:  sin(zoo)/cos(zoo)

Rule: TR2i
In:   sin(zoo)/cos(zoo)
Out:  tan(zoo)

Rule: TR2
In:   tan(zoo)
Out:  sin(zoo)/cos(zoo)

Rule: TR2i
In:   sin(zoo)/cos(zoo)
Out:  tan(zoo)

Rule: TR2
In:   tan(tan(zoo))
Out:  sin(sin(zoo)/cos(zoo))/cos(sin(zoo)/cos(zoo))

Rule: TR2i
In:   sin(sin(zoo)/cos(zoo))/cos(sin(zoo)/cos(zoo))
Out:  tan(tan(zoo))

Rule: TR2
In:   tan(tan(zoo))
Out:  sin(sin(zoo)/cos(zoo))/cos(sin(zoo)/cos(zoo))

Rule: TR2i
In:   sin(sin(zoo)/cos(zoo))/cos(sin(zoo)/cos(zoo))
Out:  tan(tan(zoo))

Rule: TR2
In:   tan(tan(zoo))
Out:  sin(sin(zoo)/cos(zoo))/cos(sin(zoo)/cos(zoo))

Rule: TR2i
In:   sin(sin(zoo)/cos(zoo))/cos(sin(zoo)/cos(zoo))
Out:  tan(tan(zoo))

Rule: TR2
In:   tan(tan(zoo))
Out:  sin(sin(zoo)/cos(zoo))/cos(sin(zoo)/cos(zoo))

Rule: TR2i
In:   sin(sin(zoo)/cos(zoo))/cos(sin(zoo)/cos(zoo))
Out:  tan(tan(zoo))

Rule: TR2
In:   tan(tan(zoo))
Out:  sin(sin(zoo)/cos(zoo))/cos(sin(zoo)/cos(zoo))

Rule: TR2i
In:   sin(sin(zoo)/cos(zoo))/cos(sin(zoo)/cos(zoo))
Out:  tan(tan(zoo))

Rule: TR2
In:   tan(tan(zoo))
Out:  sin(sin(zoo)/cos(zoo))/cos(sin(zoo)/cos(zoo))

Rule: TR2i
In:   sin(sin(zoo)/cos(zoo))/cos(sin(zoo)/cos(zoo))
Out:  tan(tan(zoo))

DEBUG: parsing of expression [(0, 1, None, None)] with symbol _w
DEBUG: returned None
DEBUG: parsing of expression [(_w, 1, None, None)] with symbol _w
DEBUG: returned ([], [(_w, 1, None, None)], 1, False)
DEBUG: parsing of expression [(_w, 1, None, None)] with symbol _w
DEBUG: returned ([], [(_w, 1, None, None)], 1, False)
DEBUG: parsing of expression [(0, 1, None, None)] with symbol _w
DEBUG: returned None
DEBUG: parsing of expression [(_w, 1, None, None)] with symbol _w
DEBUG: returned ([], [(_w, 1, None, None)], 1, False)
DEBUG: parsing of expression [(0, 1, None, None)] with symbol _w
DEBUG: returned None
DEBUG: parsing of expression [(_w, 1, None, None)] with symbol _w
DEBUG: returned ([], [(_w, 1, None, None)], 1, False)
DEBUG: parsing of expression [(_w, 1, None, None)] with symbol _w
DEBUG: returned ([], [(_w, 1, None, None)], 1, False)
DEBUG: parsing of expression [(0, 1, None, None)] with symbol _w
DEBUG: returned None
DEBUG: parsing of expression [(_w, 1, None, None)] with symbol _w
DEBUG: returned ([], [(_w, 1, None, None)], 1, False)
DEBUG: parsing of expression [(_w, 1, None, None)] with symbol _w
DEBUG: returned ([], [(_w, 1, None, None)], 1, False)
---------------------------------------------------------------------------
RecursionError                            Traceback (most recent call last)
<ipython-input-3-dd3631173bd8> in <module>()
----> 1 limit(tan(tan(x)), x, -oo)

~/miniconda3/lib/python3.6/site-packages/sympy/series/limits.py in limit(e, z, z0, dir)
     47     """
     48
---> 49     return Limit(e, z, z0, dir).doit(deep=False)
     50
     51

~/miniconda3/lib/python3.6/site-packages/sympy/series/limits.py in doit(self, **hints)
    178
    179         try:
--> 180             r = gruntz(e, z, z0, dir)
    181             if r is S.NaN:
    182                 raise PoleError()

~/miniconda3/lib/python3.6/site-packages/sympy/series/gruntz.py in gruntz(e, z, z0, dir)
    648         r = limitinf(e, z)
    649     elif z0 == -oo:
--> 650         r = limitinf(e.subs(z, -z), z)
    651     else:
    652         if str(dir) == "-":

~/miniconda3/lib/python3.6/site-packages/sympy/utilities/misc.py in decorated(*args, **kwargs)
    177
    178     def decorated(*args, **kwargs):
--> 179         return maketree(func, *args, **kwargs)
    180
    181     return decorated

~/miniconda3/lib/python3.6/site-packages/sympy/utilities/misc.py in maketree(f, *args, **kw)
    163         #    map(lambda x: '-', range(1, 2 + _debug_iter))), get_function_name(f), args))
    164
--> 165         r = f(*args, **kw)
    166
    167         _debug_iter -= 1

~/miniconda3/lib/python3.6/site-packages/sympy/core/cache.py in wrapper(*args, **kwargs)
     91             def wrapper(*args, **kwargs):
     92                 try:
---> 93                     retval = cfunc(*args, **kwargs)
     94                 except TypeError:
     95                     retval = func(*args, **kwargs)

~/miniconda3/lib/python3.6/site-packages/sympy/series/gruntz.py in limitinf(e, x)
    426         e = e.subs(x, p)
    427         x = p
--> 428     c0, e0 = mrv_leadterm(e, x)
    429     sig = sign(e0, x)
    430     if sig == 1:

~/miniconda3/lib/python3.6/site-packages/sympy/utilities/misc.py in decorated(*args, **kwargs)
    177
    178     def decorated(*args, **kwargs):
--> 179         return maketree(func, *args, **kwargs)
    180
    181     return decorated

~/miniconda3/lib/python3.6/site-packages/sympy/utilities/misc.py in maketree(f, *args, **kw)
    163         #    map(lambda x: '-', range(1, 2 + _debug_iter))), get_function_name(f), args))
    164
--> 165         r = f(*args, **kw)
    166
    167         _debug_iter -= 1

~/miniconda3/lib/python3.6/site-packages/sympy/core/cache.py in wrapper(*args, **kwargs)
     91             def wrapper(*args, **kwargs):
     92                 try:
---> 93                     retval = cfunc(*args, **kwargs)
     94                 except TypeError:
     95                     retval = func(*args, **kwargs)

~/miniconda3/lib/python3.6/site-packages/sympy/series/gruntz.py in mrv_leadterm(e, x)
    511     w = Dummy("w", real=True, positive=True, finite=True)
    512     f, logw = rewrite(exps, Omega, x, w)
--> 513     series = calculate_series(f, w, logx=logw)
    514     return series.leadterm(w)
    515

~/miniconda3/lib/python3.6/site-packages/sympy/utilities/misc.py in decorated(*args, **kwargs)
    177
    178     def decorated(*args, **kwargs):
--> 179         return maketree(func, *args, **kwargs)
    180
    181     return decorated

~/miniconda3/lib/python3.6/site-packages/sympy/utilities/misc.py in maketree(f, *args, **kw)
    163         #    map(lambda x: '-', range(1, 2 + _debug_iter))), get_function_name(f), args))
    164
--> 165         r = f(*args, **kw)
    166
    167         _debug_iter -= 1

~/miniconda3/lib/python3.6/site-packages/sympy/series/gruntz.py in calculate_series(e, x, logx)
    470             t = powdenest(t)
    471
--> 472         if t.simplify():
    473             break
    474

~/miniconda3/lib/python3.6/site-packages/sympy/core/expr.py in simplify(self, ratio, measure)
   3094         from sympy.core.function import count_ops
   3095         measure = measure or count_ops
-> 3096         return simplify(self, ratio, measure)
   3097
   3098     def nsimplify(self, constants=[], tolerance=None, full=False):

~/miniconda3/lib/python3.6/site-packages/sympy/simplify/simplify.py in simplify(expr, ratio, measure, fu)
    513         pass
    514
--> 515     original_expr = expr = signsimp(expr)
    516
    517     from sympy.simplify.hyperexpand import hyperexpand

~/miniconda3/lib/python3.6/site-packages/sympy/simplify/simplify.py in signsimp(expr, evaluate)
    373     if not isinstance(expr, Expr) or expr.is_Atom:
    374         return expr
--> 375     e = sub_post(sub_pre(expr))
    376     if not isinstance(e, Expr) or e.is_Atom:
    377         return e

~/miniconda3/lib/python3.6/site-packages/sympy/simplify/cse_opts.py in sub_pre(e)
     23     if isinstance(e, Basic):
     24         negs = {}
---> 25         for a in sorted(e.atoms(Add), key=default_sort_key):
     26             if a in reps or a.could_extract_minus_sign():
     27                 negs[a] = Mul._from_args([S.One, S.NegativeOne, -a])

~/miniconda3/lib/python3.6/site-packages/sympy/core/compatibility.py in default_sort_key(item, order)
    459
    460     if isinstance(item, Basic):
--> 461         return item.sort_key(order=order)
    462
    463     if iterable(item, exclude=string_types):

~/miniconda3/lib/python3.6/site-packages/sympy/core/cache.py in wrapper(*args, **kwargs)
     91             def wrapper(*args, **kwargs):
     92                 try:
---> 93                     retval = cfunc(*args, **kwargs)
     94                 except TypeError:
     95                     retval = func(*args, **kwargs)

~/miniconda3/lib/python3.6/site-packages/sympy/core/expr.py in sort_key(self, order)
     76         else:
     77             if expr.is_Add:
---> 78                 args = expr.as_ordered_terms(order=order)
     79             elif expr.is_Mul:
     80                 args = expr.as_ordered_factors(order=order)

~/miniconda3/lib/python3.6/site-packages/sympy/core/expr.py in as_ordered_terms(self, order, data)
    942         """
    943         key, reverse = self._parse_order(order)
--> 944         terms, gens = self.as_terms()
    945
    946         if not any(term.is_Order for term, _ in terms):

~/miniconda3/lib/python3.6/site-packages/sympy/core/expr.py in as_terms(self)
    981                     if factor.is_number:
    982                         try:
--> 983                             coeff *= complex(factor)
    984                         except TypeError:
    985                             pass

~/miniconda3/lib/python3.6/site-packages/sympy/core/expr.py in __complex__(self)
    241     def __complex__(self):
    242         result = self.evalf()
--> 243         re, im = result.as_real_imag()
    244         return complex(float(re), float(im))
    245

~/miniconda3/lib/python3.6/site-packages/sympy/core/power.py in as_real_imag(self, deep, **hints)
    960                     # We can be more efficient in this case
    961                     expr = expand_multinomial(self.base**exp)
--> 962                     return expr.as_real_imag()
    963
    964                 expr = poly(

... last 1 frames repeated, from the frame below ...

~/miniconda3/lib/python3.6/site-packages/sympy/core/power.py in as_real_imag(self, deep, **hints)
    960                     # We can be more efficient in this case
    961                     expr = expand_multinomial(self.base**exp)
--> 962                     return expr.as_real_imag()
    963
    964                 expr = poly(

RecursionError: maximum recursion depth exceeded
```

**Comment by jksuom** [comment]
`limitinf` is not designed to work with periodic functions, though it does not always raise an exception. There should probably be a periodicity test after the removal of Order terms along the following lines:

    try:
        if periodicity(e, x):
            raise ValueError("Periodic function has no limit at infinity")
    except NotImplementedError:
        pass

**Comment by normalhuman** [comment]
I don't think that `limit(tan(x), oo)` should raise a ValueError. It is a well-formed mathematical question: "what is the limit of tan(x) as x->oo"? The answer is: "it does not exist", which can be expressed by returning NaN or None, or something else. It's not like the user is asking SymPy to make exp(x) a polynomial in x, or differentiat 2*x with respect to 2.

**Comment by jksuom** [comment]
I was hoping that [this line](https://github.com/sympy/sympy/blob/master/sympy/series/limits.py#L212) would catch the error. Of course, `NaN` would probably do as well.

**Comment by normalhuman** [comment]
Was there any discussion on what `limit` should return to the user when it was determined that the limit does not exist? Currently it's like <-1, 1> when oscillation is detected; (say, `limit(sin(x), x, oo)`) but it may happen that the limit was found to not exist although oscillation bounds have not been determined.

**Comment by czgdp1807** [comment]
Latest update,

```python
Python 3.6.8 (default, Aug 20 2019, 17:12:48) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from sympy import *
>>> from sympy.abc import x
>>> limit(tan(tan(x)), x, oo)
Limit(tan(tan(x)), x, oo, dir='-')
>>> limit(tan(tan(x)), x, oo).doit()
Limit(tan(tan(x)), x, oo, dir='-')
>>> limit(tan(tan(x)), x, -oo)
Limit(tan(tan(x)), x, -oo)
>>> limit(tan(tan(x)), x, -oo).doit()
Limit(tan(tan(x)), x, -oo)
```
Probably this issue can be closed. What do you say @ethankward ?

**Comment by czgdp1807** [comment]
I think the original issue of recursion has been fixed. 
Wolfram Alpha says that results in the form of standard mathematical functions doesn't exist so, the results in https://github.com/sympy/sympy/issues/13585#issuecomment-531537340 appear to be consistent.
I am closing this issue for now. Please re-open this, if you feel or just comment below. Thanks for the contributions.

**Comment by czgdp1807** [comment]
In reference to https://github.com/sympy/sympy/issues/13585#issuecomment-360167150 Wolfram Alpha also gives similar results, https://www.wolframalpha.com/input/?i=limit%28sin%28x%29%2C+x%2C+oo%29
