### ISSUE TITLE
Vector module design

### ISSUE THREAD

**Issue by BMaxV** [sympy/sympy#13591]
Hello everyone,

recently I tried to do something with sympy again, using vectors.

Can you explain to me why the vector module was designed the way it was designed, because it's very confusing to me. Namely these two points:

 * Why we need a base coordinate system. Obviously one is implied any other time anyone describes a vector, why does the definition of a vector has to start with the base?

 * Why use the base vectors of the reference frame, when you have perfectly fine variables in sympy itself?

There is some other weird stuff like the fact that Vector, according to the docstring is intended to never be instantiated and why you felt you needed a separate Point class.

I'm game to write my own submodule and do a pull request for it, but I'd rather like to know before what your intentions were with what you have now.

**Comment by ylemkimon** [comment]
A vector is an element of vector space, and a vector space is defined by a basis (vectors).

**Comment by BMaxV** [comment]
That is correct, it's not an explanation though. Just because x and y are letters of the alphabet, you don't have to initialize sympy symbols with

```
A=sympy.Alphabet()
x,y=A[23],A[24]
```

instead I can just use

`x,y=sympy.symbols("x y")`

So why do I have to do
```
v=Vectorspace()
vector=v.basis[0] * valueforx + v.basis[1] * valuefory + v.basis[2] * valueforz
```

instead of 

```
x,y,z=sympy.symbols("x y z")
vector=[x,y,z]
```

**Comment by ylemkimon** [comment]
I think it’s because we can use existing operations, functions, simplifications, and etc. As vectors are linear combination of basis vectors, we can just use them. If we do [a, b, c]+[d, e, f], we have to implement how to handle vector addition. Also, with [x, y, z], we cannot know what are basis vectors.

**Comment by BMaxV** [comment]
You think? You can "just" use them? Which operations can you use by doing this? What's the gain?

You would not have to implement vector addition, since sympy already has an add function for expressions and symbols, it's not going to mix x and y.

It doesn't matter what the basis vectors are. (1,0,0) stands for a vector in any vectorspace with three dimensions, no matter what the basis is.

If you absolutely insist on there being a basis, you can add one later.

Also, I'd really rather hear an explanation from one of the authors of the code of the vector module.

**Comment by moorepants** [comment]
The vector module implements a "basis independent" vector, as opposed to a basis dependent one which you have shown: `vector = [x, y, z]`. This allows you to combine vectors without having to worry which basis the vector may be defined with respect to. The matrix module may provide sufficient functionality for your desired basis independent formulation.

We would likely more than welcome a pull request with a vector module that has a different design as companion to the existing one.

Also, I would encourage you to read our code of conduct:

https://github.com/sympy/sympy/blob/master/CODE_OF_CONDUCT.md

Your messages here can easily be interpreted with a confrontational tone.

**Comment by BMaxV** [comment]
Right, I'm sorry, I admit my previous reply wasn't as nice as it could have been. I'll try to be nice in the future.

I guess just writing the new submodule first might be a better approach.

**Comment by BMaxV** [comment]
Wrote my own algebra system and vector stuff. Thanks for the inspiration!
