### ISSUE TITLE
slow inverse_laplace_transform for easy poles in LH plane

### ISSUE THREAD

**Issue by cbm755** [sympy/sympy#13606]
Consider:
````
>>> f = 1/((p+1)*(p+8))
         1       
  ───────────────
  (p + 1)⋅(p + 8)
>>> inverse_laplace_transform(f, p, t)   % takes maybe 2 seconds
⎛ 7⋅t    ⎞  -8⋅t             
⎝ℯ    - 1⎠⋅ℯ    ⋅Heaviside(t)
─────────────────────────────
              7              
````
But change it to `f = 1/((p+1)*(p+10))` and it takes maybe 10 seconds.

Then change it to have `...(p+15)` and it takes at least 5 minutes (killed it then).

- - - - -

These functions have simple poles in the left have plane.  They should be easy to invert.

**Comment by cbm755** [comment]
I labeled this "easy to fix" but...  Well, its probably easy to get involved and potentially a nice project for someone who has learned their laplace transforms, but other than that I have no idea..., it might be a deep dive into the transform code.

**Comment by himanshukgp** [comment]
I'll be working on this.

**Comment by asmeurer** [comment]
This probably isn't easy to fix. The integral transforms are currently computed with the meijerg algorithm. If you don't know what's going on there, it could take some time to learn it. 

What we should do is add some table lookups a la manualintegrate for the common integral transforms so that cases like this can be computed quickly.

**Comment by jksuom** [comment]
It seems that most of the time is spent in `hyperexpand`. The inverse transform of `1/((p+1)*(p+10))` is quickly found to involve `meijerg(((-9, 0), ()), ((), (-10, -1)), z)`. (Note the poles in `bq` and counterterms in `ap`.) Then the expression is simplified using `hyperexpand`:
```
In [15]: f = meijerg(((-9, 0), ()), ((), (-10, -1)), z)

In [16]: %time hyperexpand(f)
CPU times: user 28.46 s, sys: 0.08 s, total: 28.54 s
Wall time: 28.54 s
```
It looks like the expansion process is computing with large (thousands of ops) polynomial expressions. It should be investigated if those could be replaced by Polys.

**Comment by vishalg2235** [comment]
hey! I would like to work on this issue. @cbm755 can I work on this issue ?

**Comment by cbm755** [comment]
Anyone can work on any issue, no permission required :-)

**Comment by vishalg2235** [comment]
Thank you! 
can you help me how to fix it ? which part of file meijerint.py I should look for ?

**Comment by cbm755** [comment]
Sorry, I cannot.  Note also @asmeurer's note earlier comment https://github.com/sympy/sympy/issues/13606#issuecomment-344382913

**Comment by vishalg2235** [comment]
@asmeurer how to add a lookup table ?

**Comment by asmeurer** [comment]
I would look at adding transform integrals to manualintegrate. However, I'm not sure if manualintegrate supports integration limits yet (maybe it does, I'm not sure). If it doesn't, that will need to be added first.

**Comment by vishalg2235** [comment]
@asmeurer is there any work here in which I could help ?

**Comment by asmeurer** [comment]
I'm not aware of existing work but you might search the open issues and pull requests to see what is there.

**Comment by hanspi42** [comment]
Pull request $21566 will solve this.
