### ISSUE TITLE
Rational(numpy.int64(1), 2)) fails on Python 3:  TypeError: invalid input: 1

### ISSUE THREAD

**Issue by nschloe** [sympy/sympy#13618]
MWE:
```python
import numpy
import sympy

sympy.Rational(numpy.int64(1), 2)
```
This fails with
```
[...]
/usr/lib/python3/dist-packages/sympy/core/numbers.py in __new__(cls, p, q, gcd)
   1483 
   1484             if not isinstance(p, SYMPY_INTS + (Rational,)):
-> 1485                 raise TypeError('invalid input: %s' % p)
   1486             q = q or S.One
   1487             gcd = 1

TypeError: invalid input: 1
```
on Python 3, SymPy 1.1.1.

Also failing:

 * `numpy.int32`

Working:
 * Anything on Python 2.
 * `numpy.int`

**Comment by abhigyank** [comment]
There seems to be no update on this issue since 1 month, so I am taking this up. No update on PR #13670 from 1 month as well.

**Comment by nschloe** [comment]
Not sure if this is the same issue:
```python
from mpmath import mp
import numpy

mp.sqrt(numpy.int64(1))
```
fails with
```
TypeError: cannot create mpf from 1
```
under Python 3. Should I file a new bug for this?

**Comment by normalhuman** [comment]
I think you should file an issue at https://github.com/fredrik-johansson/mpmath/issues since it does not involve SymPy.  mpmath is not a part of SymPy, it's just a dependency.

**Comment by oscarbenjamin** [comment]
This seems to be fixed now. I'll close - feel free to open if it doesn't seem fixed to you:
```julia
In [1]: import numpy 
   ...: import sympy 
   ...:  
   ...: sympy.Rational(numpy.int64(1), 2)                                                                                         
Out[1]: 1/2
```
