### ISSUE TITLE
Catalan assumptions

### ISSUE THREAD

**Issue by pelegm** [sympy/sympy#13627]
* For every nonnegative `x`, `catalan(x)` should be known to be positive.
* For every nonnegative integer `n`, `catalan(n)` should be known to be an integer.
* For every integer `n` larger than 3, `catalan(n)` should be known to composite.

I'll try working on some/all of these, you are welcome to add a couple of other assumptions here.

**Comment by ylemkimon** [comment]
Closed via #13628.
