### ISSUE TITLE
products with arrays with only one element convert to float

### ISSUE THREAD

**Issue by nschloe** [sympy/sympy#13637]
When multiplying a numpy array with more than one entries, `sympy` entities (such as `sympy.Rational`) correctly translate into the array:
```python
import numpy
import sympy

print(sympy.Rational(1, 2) * numpy.array([1, 1]))
```
```
[1/2 1/2]
```
If, however, the array only has length 1, the values are converted into `float`s:
```python
print(sympy.Rational(1, 2) * numpy.array([1]))
```
```
0.500000000000000
```
I would have expected an `array([1/2], dtype=object)` here.

Any idea what's going on?

**Comment by nschloe** [comment]
Workaround: `numpy.multiply`
```python
numpy.multiply(sympy.Rational(1, 2), numpy.array([1]))
```
```
[1/2]
```

**Comment by jksuom** [comment]
> what's going on?

The method of multiplication is determined by the order of the factors.
```
>>> sympy.Rational(1, 2) * numpy.array([1])  # SymPy multiplication
0.500000000000000
>>> numpy.array([1]) * sympy.Rational(1, 2)  # NumPy multiplication
array([1/2], dtype=object)
```

**Comment by nschloe** [comment]
Tough. Why isn't this the same way with
```
sympy.Rational(1, 2) * numpy.array([1, 1])
```
tough?

**Comment by yeshsurya** [comment]
Thanks @jksuom . I'm new to sympy. What should be the output of sympy.Rational(1,2) * numpy.array([1,1.0]) . is it [1/2 0.5] or [0.5 0.5].

**Comment by jksuom** [comment]
I'm not sure there is a definite answer. When objects of different libraries are combined, it is not clear which kind of object should result. Should it be a plain Python object or should it belong to one of the libraries, and if so, then which one. I think that, in general, the programmer should make the decision clear by explicitly converting the objects to compatible form before they are combined.

**Comment by asmeurer** [comment]
The reason this happens is that SymPy tries to convert the operand to a `float`, and NumPy arrays convert to floats when they have only one element. 

If you are trying to do NumPy array calculations with SymPy objects you should put them in a NumPy array first so that they use the correct operations.
