### ISSUE TITLE
Piecewise substitution issue

### ISSUE THREAD

**Issue by sswatson** [sympy/sympy#13633]
The code block 

```python
from sympy import sqrt, integrate, symbols
x = symbols("x")
integrate(x**2*sqrt(1-x**2),(x,-1,1))
```

throws an error `'Or' object has no attribute 'lts'`, even though the corresponding indefinite integration problem works.

**Comment by smichr** [comment]
Please try this in the most recent master.

**Comment by sswatson** [comment]
Works!

**Comment by smichr** [comment]
Nice!
