### ISSUE TITLE
perimeter of ellipse

### ISSUE THREAD

**Issue by smichr** [sympy/sympy#13644]
Look into algorithm given [here](https://groups.google.com/forum/#!topic/sympy/uhKKkBDMvVo)

```
# Computes Perimeter of Ellipse very fast correct to hundreds of places
# Written by Panna Lal Patodia (pannalal60@gmail.com, pannalal@usa.net)
# On November 3, 2017

from sympy import *

def peri(a, b, pr):
	import sympy
	tol = N(10**(-pr), pr)
	s = 0.0
	m = 1.0
	x = max(a,b)
	y = min(a,b)
	while (abs(x - y) > tol):
		t = (x + y) / 2
		y = N(sympy.sqrt(x * y), pr)
		x = t
		m *= 2
		s += N(m * (x - y) * (x - y), pr)
		#print(x-y, tol)
	p = N(sympy.pi * ((a + b) * (a + b) - s) / (x + y), pr)
	return p

print(peri(3, 1, 800))
```

**Comment by amitmanchanda1995** [comment]
Hi @smichr 
Do we need to implement it? If yes, can I contribute to this issue?
Thanks

**Comment by vishalg2235** [comment]
@smichr I have checked it with few values. I also checked for circle it gives right answer (pi). I think it should return answer in terms of 'pi'.

**Comment by smichr** [comment]
see [this and its references](http://www.ebyte.it/library/docs/math05a/EllipsePerimeterApprox05.html)

**Comment by vishalg2235** [comment]
@smichr I have read the reference but I didn't understand which approximation is used in this code. As here 's' is sum of 2^i*(x-y)^2 ; where x and y are AM and GM of previous x and y till x=y(abs(x-y)==tol) ?

**Comment by pannalal** [comment]
@smichr. I have written the code given at the top. Please note that algorithm is highly accurate and you can compute perimeter of ellipse to any number of decimals. The result will always be correct. However, your reference is pointing towards approximate values wherein the perimeter of ellipse is computed to 10 to 15 decimal places.

**Comment by namannimmo10** [comment]
According to me, a rather simple implementation  for the perimeter of ellipse would be:
```
>>> def peri(a, b):
...     return 2 * 3.14 * sqrt((a*a + b*b) / (2 * 1.0))
... 
>>> peri(3, 1)
14.042506898698681
```
@smichr Do you think its accurate?

**Comment by pannalal** [comment]
The above value is totally wrong.
The correct value of peri(3,1) = 13.364893220555258230129502325060196239

and Correct to 1000 decimal places = 13.36489322055525823012950232506019623940098267238917710329296039649258541904656960802591064811639821290607166134999609707234137108408063978974437709944818337753005351198974613394459388724274018343062779080020971080989499876000066675059035597414025930844251138344621656788990230991898575234813365779242775464810157049359219405013302149498414020173545802125794752194596115082221526780870912129533491495997315949096567501153587599941687464986032846510587753650524646875441299007579406915910286946141951705493009908045468956186313407300805036376511241116607015893377741713516792941702737043690937253728317665911710021475533561033075152845413919337045631890810044307505615839413131836316241985209877212891032434870426136915360796018339148014466989005657685110457645878914432261050313831369254784713002770427388405513278671216082804899933687810714711333673720110908255758942010499122648658760566049912376960951662914837984827093674995799081121146232455803154822957922881305317471585088312319171562407533771505

and the result is instant (less than 15 ms).

**Comment by oscarbenjamin** [comment]
Okay so this is:
```python
In [12]: e = Ellipse((0,0),3,4)

In [13]: e.circumference
Out[13]: 16⋅E(7/16)

In [14]: e.circumference.n()
Out[14]: 22.1034921607095
```
