### ISSUE TITLE
lambdify sinc gives wrong answer

### ISSUE THREAD

**Issue by ijackson** [sympy/sympy#13642]
Unfortunately, there is not only sinc(x) = sin(x)/x, the mathematical sinc function.  Some DSP people decided it would be more convenient if the integral was 1, and reused the name "sinc", so they have sinc(x) = sin(pi.x)/(pi.x).

sympy uses the mathematical sinc.  But when you lambdify, it ends up using numpy's sinc.  numpy's sinc is the DSP sinc.

Steps to reproduce, and actual output:

```python
  Python 3.5.3 (default, Jan 19 2017, 14:11:04) 
  [GCC 6.3.0 20170118] on linux
  Type "help", "copyright", "credits" or "license" for more information.
  >>> from sympy import *
  >>> from sympy.utilities.lambdify import *
  >>> import numpy as np
  >>> x = Symbol('x')
  >>> float(sinc(1))
  0.8414709848078965
  >>> lambdify(x, sinc(x))(1)
  3.8981718325193755e-17
  >>> np.sinc(1)
  3.8981718325193755e-17
  >>>
```
(this is all on Debian stretch amd64, with Debian's sympy 1.0 (package 1.0-3), Debian's numpy 1.12 (package 1:1.12.1-3).

Expected output:

  float(sinc(1)) => 0.8414709848078965 # as actual output
  lambdify(x, sinc(x))(1) => 0.8414709848078965 # CHANGE from actual output, equal to float(sinc(1))
  np.sinc(1) => 3.8981718325193755e-17 # as actual output, numpy still using DSP sinc

**Comment by PaiAkshay998** [comment]
If you have numpy installed, sympy will fall back to numpy's version of sinc which is the normalized version. However, if you want to use the unnormalized version of sinc, you can always pass "mpmath" to the modules parameter which uses the unnormalized version.

```py
print(lambdify(x, sinc(x), modules='mpmath')(1))
```
So, this should give you 0.8414709848078965 as expected.

Please do let me know if I've missed out something or misunderstood something. I'm new to sympy 😄
