### ISSUE TITLE
Tests for ring series failing

### ISSUE THREAD

**Issue by Krashcan** [sympy/sympy#13659]
Running the `sympy/polys/tests/test_ring_series.py` results in failure for many test functions. Here is the output from when i ran `pytest --pyargs sympy/polys/tests/test_ring_series.py`

                                                           DO *NOT* COMMIT!                                                                   
	====================================================================== FAILURES ======================================================================
	______________________________________________________________________ test_log ______________________________________________________________________

	    def test_log():
		R, x = ring('x', QQ)
		p = 1 + x
		p1 = rs_log(p, x, 4)/x**2
	>       assert p1 == 1/3*x - 1/2 + x**(-1)
	E       assert 1/3*x - 1/2 + x**(-1) == x**(-1)
	E         Omitting 1 identical items, use -vv to show
	E         Left contains more items:
	E         {(0,): -1/2, (1,): 1/3}
	E         Use -v to get the full diff

	sympy/polys/tests/test_ring_series.py:156: AssertionError
	______________________________________________________________________ test_tan ______________________________________________________________________

	    def test_tan():
		R, x, y = ring('x, y', QQ)
	>       assert rs_tan(x, x, 9)/x**5 == \
		    17/315*x**2 + 2/15 + 1/3*x**(-2) + x**(-4)
	E       assert 17/315*x**2 +...(-2) + x**(-4) == x**(-4)
	E         Omitting 1 identical items, use -vv to show
	E         Left contains more items:
	E         {(-2, 0): 1/3, (0, 0): 2/15, (2, 0): 17/315}
	E         Use -v to get the full diff

	sympy/polys/tests/test_ring_series.py:285: AssertionError
	______________________________________________________________________ test_sin ______________________________________________________________________

	    def test_sin():
		R, x, y = ring('x, y', QQ)
	>       assert rs_sin(x, x, 9)/x**5 == \
		    -1/5040*x**2 + 1/120 - 1/6*x**(-2) + x**(-4)
	E       assert -1/5040*x**2 ...(-2) + x**(-4) == -x**2 + x**(-4)
	E         Omitting 1 identical items, use -vv to show
	E         Differing items:
	E         {(2, 0): -1/5040} != {(2, 0): -1}
	E         Left contains more items:
	E         {(-2, 0): -1/6, (0, 0): 1/120}
	E         Use -v to get the full diff

	sympy/polys/tests/test_ring_series.py:324: AssertionError
	______________________________________________________________________ test_cos ______________________________________________________________________

	    def test_cos():
		R, x, y = ring('x, y', QQ)
	>       assert rs_cos(x, x, 9)/x**5 == \
		    1/40320*x**3 - 1/720*x + 1/24*x**(-1) - 1/2*x**(-3) + x**(-5)
	E       assert 1/40320*x**3 ...(-3) + x**(-5) == x**(-5)
	E         Omitting 1 identical items, use -vv to show
	E         Left contains more items:
	E         {(-3, 0): -1/2, (-1, 0): 1/24, (1, 0): -1/720, (3, 0): 1/40320}
	E         Use -v to get the full diff

	sympy/polys/tests/test_ring_series.py:350: AssertionError
	_____________________________________________________________________ test_atanh _____________________________________________________________________

	    def test_atanh():
		R, x, y = ring('x, y', QQ)
	>       assert rs_atanh(x, x, 9)/x**5 == 1/7*x**2 + 1/5 + 1/3*x**(-2) + x**(-4)
	E       assert 1/7*x**2 + 1/...(-2) + x**(-4) == x**(-4)
	E         Omitting 1 identical items, use -vv to show
	E         Left contains more items:
	E         {(-2, 0): 1/3, (0, 0): 1/5, (2, 0): 1/7}
	E         Use -v to get the full diff

	sympy/polys/tests/test_ring_series.py:385: AssertionError
	_____________________________________________________________________ test_sinh ______________________________________________________________________

	    def test_sinh():
		R, x, y = ring('x, y', QQ)
	>       assert rs_sinh(x, x, 9)/x**5 == 1/5040*x**2 + 1/120 + 1/6*x**(-2) + x**(-4)
	E       assert 1/5040*x**2 +...(-2) + x**(-4) == x**(-4)
	E         Omitting 1 identical items, use -vv to show
	E         Left contains more items:
	E         {(-2, 0): 1/6, (0, 0): 1/120, (2, 0): 1/5040}
	E         Use -v to get the full diff

	sympy/polys/tests/test_ring_series.py:408: AssertionError
	_____________________________________________________________________ test_cosh ______________________________________________________________________

	    def test_cosh():
		R, x, y = ring('x, y', QQ)
	>       assert rs_cosh(x, x, 9)/x**5 == 1/40320*x**3 + 1/720*x + 1/24*x**(-1) + \
		    1/2*x**(-3) + x**(-5)
	E       assert 1/40320*x**3 ...(-3) + x**(-5) == x**(-5)
	E         Omitting 1 identical items, use -vv to show
	E         Left contains more items:
	E         {(-3, 0): 1/2, (-1, 0): 1/24, (1, 0): 1/720, (3, 0): 1/40320}
	E         Use -v to get the full diff

	sympy/polys/tests/test_ring_series.py:416: AssertionError
	_____________________________________________________________________ test_tanh ______________________________________________________________________

	    def test_tanh():
		R, x, y = ring('x, y', QQ)
	>       assert rs_tanh(x, x, 9)/x**5 == -17/315*x**2 + 2/15 - 1/3*x**(-2) + x**(-4)
	E       assert -17/315*x**2 ...(-2) + x**(-4) == -x**2 + x**(-4)
	E         Omitting 1 identical items, use -vv to show
	E         Differing items:
	E         {(2, 0): -17/315} != {(2, 0): -1}
	E         Left contains more items:
	E         {(-2, 0): -1/3, (0, 0): 2/15}
	E         Use -v to get the full diff

	sympy/polys/tests/test_ring_series.py:425: AssertionError
	======================================================== 8 failed, 24 passed in 13.47 seconds =============================================

**Comment by RohitJain3241** [comment]
I am working on it. I am new to python and need help.
These functions are working fine. But the expressions such as "1/3*x - 1/2 + x**(-1)" which is an instance of PolyElement are not able to handle fractions and converts them into integers. 
But unable to understand the constructor of PolyElement.

**Comment by jksuom** [comment]
The error appears when Python 2 converts 1/3 and 1/2 to 0 (see http://docs.sympy.org/latest/tutorial/gotchas.html#two-final-notes-and). It can usually be fixed by adding `from __future__ import division`. Alternatively, it is possible to import `S` and write `S(1)/3` instead of 1/3.

**Comment by RohitJain3241** [comment]
Thanks. It's working fine now. #13662

**Comment by jksuom** [comment]
Closed by #13662 .
