### ISSUE TITLE
Substitution lacks parenthesis

### ISSUE THREAD

**Issue by schedacomp** [sympy/sympy#13654]
The following inconsistency in substitutions has emerged in `sympy 1.1.1` and is different to the behaviour found in `sympy 1.0`: 

```
fct = sympy.S("1/f")
A = {"f": "(1 / 2)"}
B = {"f": "1 / 2"}
print fct.subs(A)
print fct.subs(B)
print sympy.simplify(fct.subs(A) - fct.subs(B)) == 0
```

which gives

```
1/(1 / 2)  [= 2 as expected]
1/1 / 2    [= 1/2 which is wrong]
False      [confirming that both expressions are not equal, as they should be]
```

I think this could be solved by adding - by default - a parenthesis around expressions before substituting.

This issue has already been reported in [https://github.com/sympy/sympy/issues/13333](https://github.com/sympy/sympy/issues/13333), which filed a slightly more difficult example.

**Comment by ttxtea** [comment]
Note that it is probably the repr() function that causes the problem. In isympy, where the output is based on srepr it is fine. So maybe the bug is somewhere in the __repr__ function?

This is an issue for all backages using sympy in a more general setting like the `brian2` simulator.
