### ISSUE TITLE
Full support of laplacian in vector package

### ISSUE THREAD

**Issue by szymag** [sympy/sympy#13664]
In #12261 `laplacian` function was added.  I think that it could be good idea to add to `vector` package full support of `laplacian` operator like it is done for `del` operator.
For example support for `laplacian` may looks:
```python 
C = CoordSys3D('C')
i, j, k = C.base_vectors()
x, y, z = C.base_scalars()
delop = Del()
lap = Laplacian()
v = x*y**2
v1 = delop(v)).doit()    # C.y**2*C.i + 2*C.x*C.y*C.j
delop & v1    # 2*C.x

lap * v2 # 2*C.x, not sure if this operator is the best here
```

Another advantage of adding `laplacian` is better looking of unevaluated latex form. Instead of printing `del` twice we have one `delta` symbol.

@Upabjojr, @gxyd, what do you think?

I'd like to work on this issue.

**Comment by Upabjojr** [comment]
`lap = Laplacian()`

I don't really like the idea of overloading the `*` operator in general (it makes everything so confused when parsing _Mul_ expressions). I think it's best to use the name _Laplacian_ for unevaluated expressions, and use the function call `( )` for the operator application.

**Comment by szymag** [comment]
>  use the function call ( ) for the operator application.

I might agree with you, but shouldn't it introduce discrepancy between `laplacian` and `del` operators?

I mean, for `del` we have operator itself (`Del()`) and *acting* operator (`gradient(...)`, `curl(...)`, etc.), but for `laplacian` only *acting* operator. What do you think?

**Comment by Upabjojr** [comment]
We already have a `Del()` operator, the Laplacian could be represented by adding `_eval_power` or something similar to `Del`.
