### ISSUE TITLE
Document the fact that acot uses the odd/discontinuous definition

### ISSUE THREAD

**Issue by symbolique** [sympy/sympy#13679]
There may be some confusion over the definition of `acot`:
- it isn't specified in the documentation
- numeric evaluation and at least some simplifications use the odd/discontinuous definition
- the current `is_positive` implementation and test use the continuous/positive definition

In pull request #13678 I changed the latter to standardize on odd/discontinuous, but it could be worth considering whether to standardize on continuous/positive.

**Comment by jksuom** [comment]
It seems that the evaluation of `acot` is based on the odd/discontinuous definition. It should probably be investigated how mpmath behaves before making final decisions.

**Comment by symbolique** [comment]
mpmath uses the odd/discontinuous definition and so do Mathematica and Octave, so it seems a pretty safe bet.
