### ISSUE TITLE
Daggers print incorrectly in LaTeX

### ISSUE THREAD

**Issue by jarthurgross** [sympy/sympy#13671]
When using `sympy.latex`, an expression with a dagger will be rendered as `\dag` instead of `\dagger`. As `\dag` is a text-mode command and `\dagger` is the math-mode command, it should always render `\dagger`.

Example:
 ```python
import sympy
import sympy.physics.quantum as qu
a = qu.Operator('a')
sympy.latex(qu.Dagger(a))
```
outputs `'a^{\\dag}'` when it should output `'a^{\\dagger}'`.

This problem keeps `sympy.latex` from being easily used within a jupyter notebook to render sympy objects within hand-written LaTeX equations.

**Comment by ArighnaIITG** [comment]
has this issue been solved?

**Comment by jarthurgross** [comment]
Pull request #13672 solves the issue.
