### ISSUE TITLE
Example not working

### ISSUE THREAD

**Issue by harsh-98** [sympy/sympy#13675]
In [basic_operations](http://docs.sympy.org/latest/tutorial/basic_operations.html) last example on `how the lambdify works with numerical libraries that it does not know`, is through error.   
```
  >>> def mysin(x):
    ...     return x
    >>> f = lambdify(x, expr, {"sin":mysin})
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/base/data/home/apps/s~sympy-live-hrd/49.400254913747479351/sympy/sympy/utilities/lambdify.py", line 387, in lambdify
        func = eval(lstr, namespace)
      File "<string>", line 1
        lambda _Dummy_290: (<module 'sympy.core.expr' from '/base/data/home/apps/s~sympy-live-hrd/49.400254913747479351/sympy/sympy/core/expr.pyc'>)
                            ^
    SyntaxError: invalid syntax
    >>> f(0.1)
    f(0.1)
```

If is it really an error i would like to work on it :smile: !!

**Comment by ArighnaIITG** [comment]
It's working perfectly...

**Comment by gxyd** [comment]
What you are using `expr` (that occurs from `from sympy import *`) is
```python
>>> expr
<module 'sympy.core.expr' from '/home/gxyd/dev/sympy/sympy/core/expr.py'>
```
What you should be doing is setting `expr = sin(x)` as done in first code block in this section http://docs.sympy.org/latest/tutorial/basic_operations.html#lambdify.

**Comment by gxyd** [comment]
Also in general you should use better issue title.
