### ISSUE TITLE
Arithmetic Operations performed on inverse of Quaternion(0,0,0,0) doesn't throw an error.

### ISSUE THREAD

**Issue by ArighnaIITG** [sympy/sympy#13690]
Check the below code copied from the terminal.

```
>>> from sympy import *
>>> from sympy.algebras.quaternion import Quaternion
>>> 
>>> q1 = Quaternion(1,2,3,4)
>>> q1
1 + 2*i + 3*j + 4*k
>>> 
>>> q2 = Quaternion(0,0,0,0)
>>> q2
0 + 0*i + 0*j + 0*k
>>> 
>>> 
>>> q2.inverse()
nan + nan*i + nan*j + nan*k
>>> 
>>> 
>>> q1 + q2.inverse()
nan + nan*i + nan*j + nan*k
>>> 
>>> q1*q2.inverse()
nan + nan*i + nan*j + nan*k
>>> 
>>> q1/q2.inverse()
1 + 2*i + 3*j + 4*k*nan + nan*i + nan*j + nan*k**(-1)
```

We can see that when we perform operations like addition, multiplication and division on the inverse of Quaternion(0,0,0,0), which is NaN(not a number) , it again gives NaN, whereas it should throw an error.

**Comment by gxyd** [comment]
Thanks for reporting the issue. Feel free to submit a PR.

Also please don't use the issue description to ping, if you want to then use a separate comment.

**Comment by RohitJain3241** [comment]
I have created a PR #13693 . Hope it solves this issue. @gxyd

**Comment by Shikhar1998** [comment]
Similar would be the case, for another indeterminate form `Quaternion(0,0,0,0)`.

**Comment by RohitJain3241** [comment]
@Shikhar1998 Thanks for pointing that out. Would include that too.
