### ISSUE TITLE
Difficulties calculating integration

### ISSUE THREAD

**Issue by jerermyyoung** [sympy/sympy#13723]
Recently I use SymPy to calculate this integration integrate(sin(x)*cos(x)/(sin(x)**4+cos(x)**4),x),resulting my computer to halt...
I wonder if the integrating algorithm can be improved

**Comment by vishalg2235** [comment]
yup! my computer didn't even did it in 1 hour. 
It didn't even computed : 
```
>>> integrate(sin(2*x)/cos(x),x)
Integral(sin(2*x)/cos(x), x)
>>> integrate(sin(2*x)/cos(x),x).doit()
Integral(sin(2*x)/cos(x), x)
```

**Comment by smichr** [comment]
Try simplifying first?
```
>>> eq
sin(x)*cos(x)/(sin(x)**4 + cos(x)**4)
>>> simplify(eq)
sin(2*x)/(cos(2*x)**2 + 1)
>>> integrate(_,x)
I*log(cos(2*x) - I)/4 - I*log(cos(2*x) + I)/4
```

**Comment by vishalg2235** [comment]
@smichr It should come:
`atan(cos(2*x))/2` ?

**Comment by asmeurer** [comment]
Trig integrals like this should be easily computable once the Risch tangent work is completed. 

Getting heurisch to return an arctangent instead of complex logarithms is something that could be fixed independently (and perhaps not too difficultly).

**Comment by vishalg2235** [comment]
@asmeurer I would like to work on this issue. Can you give me some idea how to proceed ?

**Comment by vishalg2235** [comment]
ping @asmeurer @smichr

**Comment by asmeurer** [comment]
@vishalg2235 this isn't necessarily an easy to fix issue. The heurisch fix could be straightforward if you can handle the math. The idea is to detect expressions of the form `I*(log(-I*x + 1) - log(I*x + 1))/2` in heurisch and automatically convert them to `atan`. This should be doable in-algorithm (checking the `log_part`), but it could also be done with some pattern matching at the end (in-algorithm would be preferred).

**Comment by vishalg2235** [comment]
@asmeurer I couldn't detect from where the expression `I*(log(-I*x + 1) - log(I*x + 1))/2` is coming. I didn't even understood how to convert `log` part to `atan` ?
I'm really interested in solving this problem and in general knowing how integration is done using various algorithms.

**Comment by gxyd** [comment]
Since `I*(log(-I*x + 1) - log(I*x + 1))/2` is a logarithmic form of `atan`, you can use `atan(x).rewrite(log)` to get that.

For inverse part isn't currently done, I think.

**Comment by gxyd** [comment]
If you are interested in knowing how integration actually works, then see the documentation and source of `sympy.integrals`, start with the internals http://docs.sympy.org/latest/modules/integrals/integrals.html#internals

**Comment by vishalg2235** [comment]
Thanx @gxyd . But I couldn't figure out where in heurisch.py this expression is coming. And what does `in-algorithm` means ?

**Comment by gxyd** [comment]
You can use pdb (python debugger) to figure out the workflow of code. Where is this 'in-algorithm' word that you are referring to?

**Comment by vishalg2235** [comment]
In last comment of Aaron in this issue. He referred two ways to convert `I*(log(-I*x + 1) - log(I*x + 1))/2` to `atan`. First 'in-algorithm' (checking the log_part) and second pattern matching. I got pattern matching but what is first thing he is saying ?

**Comment by jksuom** [comment]
The `log`-terms are created by `_integrate` and inserted in a list called `log_part`. It is easier to recognize conjugate pairs of logarithms in that connection. That is what 'in-algorithm' means. It is also possible to find such conjugate pairs later at the end by pattern matching but then more work is needed since there are also other terms in general.

**Comment by vishalg2235** [comment]
ok! Thanks @jksuom . After finding `log` conjugate then `candidate` must be written in terms of `atan`. 
I will try add exception of 'log' conjugate.

**Comment by vishalg2235** [comment]
@jksuom I had detected when `I*(log(-I*x + 1) - log(I*x + 1))/2` is forming. But getting trouble in detecting it in code : 
At line 654 in heurisch.py 
here V = [_x0,_x1,_x2] ; where _x0 = 'x', _x1 = 'cos(x)', _x2 = 'sin(x)'.
```
y = candidate.subs(solution).subs(list(zip(poly_coeffs, [S.Zero]*len(poly_coeffs))))
pdb.set_trace()
for var in V:
    if y.has(I*log(var+I)/2) and y.has(I*log(var-I)/2):
        y -= I*(log(-I*var + 1) - log(I*var + 1))/2 + atan(var) #this line is wrong because y could have -ve of that expression
```
How should I write `if` statement and match those terms. Please correct me.

**Comment by jksuom** [comment]
It is better to search for those terms earlier, soon after they have been created by `root_factors` and inserted into `irreducibles` in [this loop](https://github.com/sympy/sympy/blob/master/sympy/integrals/heurisch.py#L587). Pairs of conjugate factors like `a + I*b` and `a - I*b` should be extracted from `irreducibles` and inserted into another set (e.g. `candidates`) before the [next loop](https://github.com/sympy/sympy/blob/master/sympy/integrals/heurisch.py#L601) is run. That can probably be done by pattern matching:

    a, b = symbols('a b', cls=Wild, exclude=[I])
    for poly in list(irreducibles):
        m = poly.match(a + I*b)
        if m[b] == 0:  # no I
            continue 
        candidates.add((m[a], m[b]))  # It is enough to save the coefficients
        irreducibles.remove(poly)

Then `candidates` should be scanned and, for each conjugate couple `(a, b)`, `(a, -b)`, two new terms should be added to replace the removed ones: `a**2 + b**2` into `irreducibles` and `atan(a/b)` into `atans`. (If there remains an 'odd' pair `(a, b)`, then `a + I*b` should be re-added to `irreducibles`.) The `irreducibles` are then inserted into `log_part` in the same way as before. The elements of `atans` are provided with coefficients (`C = _symbols('C', len(atan_part)`) and insert in a new list `atan_part`, which is then appended to the candidate solution `candidate` in the same way as `log_part`.

**Comment by asmeurer** [comment]
I thought I had remembered many similar issues but this is the only one I found: https://github.com/sympy/sympy/issues/11254 (namely, the `integrate( (sech(x)**1).rewrite(sech, exp), x )`, but that seems to be coming from risch, not heurisch). 

Anyway, it's easy enough to construct examples by differentiating and integrating `atan(something)`.

**Comment by vishalg2235** [comment]
@asmeurer the integral of `integrate( (sech(x)**1).rewrite(sech, exp), x )` is coming as : `RootSum(_z**2 + 1, Lambda(_i, _i*log(-_i + exp(-t))))` . I think it should be converted into simpler terms.

**Comment by jksuom** [comment]
I am not sure if everything touched here is covered yet but I am going to leave this closed for now. Please reopen, if you think it necessary.
