### ISSUE TITLE
line3D.equation(k=...) is deprecated

### ISSUE THREAD

**Issue by vishalg2235** [sympy/sympy#13742]
Argument `k` is deprecated from `line3D.equation()` .

Previously, the function `line3D.equation` returns `(X,Y,Z,k)` which is changed to `(Y-X,Z-X)` (here `X`, `Y` and `Z` are expressions of `x`, `y` and `z` respectively). As in 2D an equation is returned relating `x` and `y` just like that in 3D two equations will be returned relating `x`, `y` and `z`.

So in new `line3D.equation` argument `k` is not needed anymore. Now `k` is temporarily formed inside `equation()` and then gets substituted using `subs()` in terms of `x` and then `(Y-X,Z-X)` is returned.

Previously : 
```
>>> from sympy import Point3D,Line3D
>>> p1,p2 = Point3D(1,2,3),Point3D(5,6,7)
>>> l = Line3D(p1,p2)
>>> l.equation()
(x/4 - 1/4, y/4 - 1/2, z/4 - 3/4, k)
```
Now : 
```
>>> from sympy import Point3D,Line3D,solve
>>> p1,p2 = Point3D(1,2,3),Point3D(5,6,7)
>>> l = Line3D(p1,p2)
>>> l.equation()
(-x + y - 1, -x + z - 2)
```
This was implemented in PR #13726 .

**Comment by vishalg2235** [comment]
@smichr this should have a 'Deprecation removal' label.

**Comment by mohitacecode** [comment]
I am working on it.
