### ISSUE TITLE
Wrong result for integrate(1/(cos(t) + 2), (t,0,2*pi))

### ISSUE THREAD

**Issue by symbolique** [sympy/sympy#13749]
`integrate(1/(cos(t) + 2), (t,0,2*pi))` returns 0 instead of `2*pi/sqrt(3)`.
```py
>>> S('Integral(1/(cos(t) + 2), (t,0,2*pi))').doit()
0
>>> S('Integral(1/(cos(t) + 2), (t,0,2*pi))').n()
3.62759872846844
>>> S('2*pi/sqrt(3)').n()
3.62759872846844
```

**Comment by jksuom** [comment]
SymPy cannot currently compute *definite* integrals of most periodic functions. The antiderivatives of periodic integrands are typically multi-valued, 
```
In [1]: integrate(1/(cos(t) + 2), t)
Out[1]: 
          ⎛   ⎛t⎞       ⎞           ⎛   ⎛t⎞       ⎞
  √3⋅ⅈ⋅log⎜tan⎜─⎟ - √3⋅ⅈ⎟   √3⋅ⅈ⋅log⎜tan⎜─⎟ + √3⋅ⅈ⎟
          ⎝   ⎝2⎠       ⎠           ⎝   ⎝2⎠       ⎠
- ─────────────────────── + ───────────────────────
             3                         3           
# This can be expressed in terms of atan with no complex numbers.
```
and there is no method implemented for choosing suitable values at the endpoints of the integration interval. #11165, #13112

This problem is discussed in http://www.reduce-algebra.com/reduce38-docs/trigint.pdf.

**Comment by vishalg2235** [comment]
Issues (this, #11165 and #13112) all three uses 'Weierstrass substitution'. So whenever any such substitution is found then appropriate "floor" term should get added to it's integral(as per REDUCE-trigint function) to make antiderivative continuous. @jksuom I think I can start by implementing this?

**Comment by jksuom** [comment]
Ok. But a proper location for it in the code should be found. It should preferably work with all integrators implemented in SymPy.

**Comment by vishalg2235** [comment]
yup I'm working on it.

**Comment by vishalg2235** [comment]
At [line](https://github.com/sympy/sympy/blob/master/sympy/integrals/heurisch.py#L348) in heurisch.py  any sin,cos or cot in `f` is substitutes to tan and hyperbolic functions to tanh (or we can say the "Weierstrass substitution" occurs), but it happens only when function `heurisch(f, x, ....)` is called with argument `rewrite = True`, which only happens [here](https://github.com/sympy/sympy/blob/master/sympy/integrals/heurisch.py#L460). 

So for implementation I was planning that after Weierstrass substitution a 'Dictionary' will be maintained with keys : K, b and P (these are values needed for 'floor' term as given in table at page 4 of [ref](http://www.reduce-algebra.com/reduce38-docs/trigint.pdf)) , then after integration 'floor' term will be added to `antideriv` after this [statement](https://github.com/sympy/sympy/blob/master/sympy/integrals/heurisch.py#L667). 

I think 'K' can be computed from limit functions available, b and P can be taken from table itself and stored in a dictionary just like `rewritables` is stored [here](https://github.com/sympy/sympy/blob/master/sympy/integrals/heurisch.py#L343).

**Comment by jksuom** [comment]
I would place the fix in `Integral.doit()` since the issue is not connected with heurisch (or any other integrator in SymPy). It would come after (possibly multi-valued) `antideriv` has been computed but before the limits of a definite integral are substituted.

**Comment by vishalg2235** [comment]
What is multi-valued antiderivative ? can you brief me with it ?

**Comment by vishalg2235** [comment]
If we take example of `f = integrate(1/(cos(x)+2),x)`
Then, after `Integral.doit()` as result comes : `2*sqrt(3)*atan(sqrt(3)*tan(x/2)/3)/3` .
Then `free_symbol` in f was `cos(x)` and it is converted to `free_symbol` of `tan(x/2)` in result. 
So now we must add the `floor` term to make antiderivative continuous ?

**Comment by vishalg2235** [comment]
What are multivalued functions ? 
asin, acos, atan are these multivalued ?

**Comment by jksuom** [comment]
> add the floor term to make antiderivative continuous ?

Yes, that would fix the issue.

> asin, acos, atan are these multivalued ?

Yes, they are. In general, inverse functions of all periodic functions are multi-valued (i.e., the inverse value is not unique).

**Comment by vishalg2235** [comment]
Ok. I will add the floor term.

**Comment by vishalg2235** [comment]
@jksuom I'am able to check whether function has sin, cos. But how will I check their arguments (I have to check that whether it's converted to tan(x/2), tan(x/2+pi/4) or tan(x)) ?

**Comment by jksuom** [comment]
I don't think it should be necessary to know which kind of transformations (if any) were used to find the antiderivative. What is important is finding the discontinuities which are typically those places where tan becomes infinite.

**Comment by vishalg2235** [comment]
here : http://www.reduce-algebra.com/reduce38-docs/trigint.pdf in page 4 table has given some b and Period of transformations. 
Are we going to use that table or b and P will be computed in algorithm ?

**Comment by jksuom** [comment]
I think the table is for the implementation of an integrator. We should assume that an integrator has already found an antiderivative (possibly using one of those methods), and the task is to add a suitable (floor) term making the sum continuous.

**Comment by vishalg2235** [comment]
Ok in general for 'floor' I have to find that inner function (eg: tan(x/2),tan(x/2+pi/4) etc) to determine at which point discontinuity is present and what is period of function.

I think the table is for which particular substitution (sin(x) or cos(x) to tan(x/2);sin(x) or cos(x) to cot(x/2) etc) to use which values of b and P for making floor term.

**Comment by vishalg2235** [comment]
```
--- a/sympy/integrals/integrals.py
+++ b/sympy/integrals/integrals.py
@@ -8,7 +8,7 @@
 from sympy.core.expr import Expr
 from sympy.core.function import diff
 from sympy.core.mul import Mul
-from sympy.core.numbers import oo
+from sympy.core.numbers import oo, pi
 from sympy.core.relational import Eq
 from sympy.core.singleton import S
 from sympy.core.symbol import (Dummy, Symbol, Wild)
@@ -19,8 +19,9 @@
 from sympy.matrices import MatrixBase
 from sympy.utilities.misc import filldedent
 from sympy.polys import Poly, PolynomialError
-from sympy.functions import Piecewise, sqrt, sign
+from sympy.functions import Piecewise, sqrt, sign, sin, cos, tan, cot
 from sympy.functions.elementary.exponential import log
+from sympy.functions.elementary.integers import floor
 from sympy.series import limit
 from sympy.series.order import Order
 from sympy.series.formal import FormalPowerSeries
@@ -586,6 +587,12 @@ def eval_factored(f, x, a, b):
                             factored_function = function.factor()
                             if not isinstance(factored_function, Integral):
                                 function = factored_function
+
+        free_symbols = [a for a in self.free_symbols]
+        for a in free_symbols:
+            if function.has(tan(a)) and not isinstance(function,Integral):
+                P = limit(function, a, pi/2, dir="-") - limit(function, a, pi/2, dir="+")
+                function += P*floor((a-pi/2)/pi)
         return function
```
I had tried to add floor term like above shown code. But getting problem with `function.has(tan(a))` in if statement, because it's true when function has `tan(x)` but false when function has `tan(x/2)`, `tan(x/2+pi/4)` etc. How can I solve this ?

**Comment by jksuom** [comment]
I would try using `f.has(tan)`.
```
>>>f = atan(tan(x/4 + 2))
>>> f.has(tan)
True
```
The argument of `tan` can be any function of the integration variable, not `x`, `x/2` or `x/2 + pi/4` in general.

**Comment by vishalg2235** [comment]
If I identify only `tan` then how would I get that at which point I must calculate limits(point where discontinuity occurs) ? in `x` it's at `pi/2` in `x/2` it's at `pi`.

**Comment by jksuom** [comment]
The discontinuities of `tan(f(x))` are at points where `f(x)` is an odd multiple of `pi/2`.

**Comment by vishalg2235** [comment]
yes... How can I get that f(x) ?

**Comment by jksuom** [comment]
It is the argument of `tan`.

**Comment by vishalg2235** [comment]
I don't know how to get that argument?

**Comment by jksuom** [comment]
The arguments of a function are called `args`. It is a tuple. In case of a function of one variable, it is a tuple with a single item, for example
```
>>> tan(2*x + 1).args
(2*x + 1,)
```

**Comment by vishalg2235** [comment]
This works : 
```
exp = tan(x/2)
>>> exp.args
(x/2,)
```
But how to get args of : `-sqrt(3)*I*log(tan(x/2) - sqrt(3)*I)/3 + sqrt(3)*I*log(tan(x/2) + sqrt(3)*I)/3`

**Comment by jksuom** [comment]
I would search for the tan-terms, for example, as explained [here](http://docs.sympy.org/latest/tutorial/manipulation.html#walking-the-tree).

**Comment by vishalg2235** [comment]
Thanks! That was really helpful.
I had tried to implement it for `tan` like following: 
```
if not isinstance(function,Integral):
    args = []
    for arg in preorder_traversal(function):
        args.append(arg)
    for i in range(len(args)):
        if args[i].func == tan:
            a = args[i+1]
            P = limit(function, a, pi/2, dir="-") - limit(function, a, pi/2, dir="+")
            function += P*floor((a-pi/2)/pi)
```
I tried it to solve for `integrate(1/(cos(x)+2),x)` but in this case while computing limit of `function` raises "Not implemented error" from [here](https://github.com/sympy/sympy/blob/master/sympy/series/gruntz.py#L643). Please have a look here.

**Comment by jksuom** [comment]
There are also expression methods that do the same traversal looking for nodes of given types. For example, `expr.atoms(tan)` could be helpful.

**Comment by vishalg2235** [comment]
@jksuom the floor term for `tan` is added should create a different PR for it or should I commit it in #13758, otherwise the antiderivatives will come in complex-log terms?
Floor code added: 
```
if not isinstance(antideriv,Integral):
    sym = antideriv.free_symbols.pop()
    argtan = []
    for term in antideriv.atoms(tan):
        argtan.append(term.args)
    for arg in argtan:
         from sympy import solve
         a = arg[0]
         K = solve(a-pi/2,sym)[0]
         P = limit(antideriv, sym, K, dir="-") - limit(antideriv, sym, K, dir="+")
         antideriv += P*floor((a-pi/2)/pi)
```
Results : 
```
>>> from sympy import *
>>> x = symbols('x')
>>> integrate(1/(cos(x)+2),(x,0,3*pi))
sqrt(3)*pi
>>> integrate(1/(cos(x)+2),(x,0,2*pi))
2*sqrt(3)*pi/3
>>> integrate(1/(cos(x)+2),(x,0,4*pi))
4*sqrt(3)*pi/3
>>> integrate(1/(sin(x)+2),(x,0,1*pi))
2*sqrt(3)*pi/9
>>> integrate(1/(sin(x)+2),(x,0,2*pi))
2*sqrt(3)*pi/3
>>> integrate(1/(sin(x)+2),(x,0,3*pi))
8*sqrt(3)*pi/9
>>> integrate(1/(sin(x)+2),(x,0,pi/2))
sqrt(3)*pi/9
>>> integrate(1/(sin(x)+2),(x,0,3*pi/2))
4*sqrt(3)*pi/9
>>> integrate(1/(sin(x)+2),x)
2*sqrt(3)*atan(2*sqrt(3)*tan(x/2)/3 + sqrt(3)/3)/3 + 2*sqrt(3)*pi*floor((x/2 - pi/2)/pi)/3
```

**Comment by vishalg2235** [comment]
I think more discontinuous terms like `tan` should be covered. example: cot, sec, cosec. ?

**Comment by jksuom** [comment]
sym = antideriv.free_symbols.pop()

The definite integral is to be computed with respect to a given variable, not just any free symbol.

    argtan = []
    for term in antideriv.atoms(tan):
        argtan.append(term.args)

There should be at most one substituted `tan` term. The method will not work with several (different) terms.

I think that `tan` is currently the only substituted function used by SymPy's integrators. It is possible that `cot` will also be used some time but I doubt that other functions like `sec` or `cosec` would ever be used. `tan` and `cot` have the essential property that they take all real values once and only once in each period interval.

**Comment by vishalg2235** [comment]
```
if not isinstance(antideriv,Integral):
    sym = xab[0]
    argtan = []
    for term in antideriv.atoms(tan) | antideriv.atoms(cot):
        argtan.append(term.args)
    for arg in argtan:
        from sympy import solve
        a = arg[0]
        K = solve(a-pi/2,sym)[0]
        P = limit(antideriv, sym, K, dir="-") - limit(antideriv, sym, K, dir="+")
        antideriv += P*floor((a-pi/2)/pi)
```
I have used `xab` which was previously defined as the limits of `integrate`.

> The method will not work with several (different) terms.
>
Can you explain in more details, I didn't get what you are saying?

**Comment by jksuom** [comment]
This looks promising, but if there is more than one item in the `argtan` list (with different arguments), I am not sure if the method can be applied. That should probably be investigated more carefully with suitable examples. I also think that `solve` returns a list, in general. There could be several solutions, or none at all.

**Comment by vishalg2235** [comment]
Lets assume `antiderivative = f1(tan) + f2(tan) + f1(cot) + f2(cot) + continuous_part`. Then first we add floor to `f1(tan)`, then to `f2(tan)` and similarly we add "independent floor term" to each term making each one continuous.
Will this work?

**Comment by vishalg2235** [comment]
for `solve` I think we should use cases on number of solutions.

**Comment by jksuom** [comment]
Yes, I think that should work. That would apply in case antideriv is an Add. The floor terms could then be added to each argument of Add independently.

**Comment by vishalg2235** [comment]
Code : 
```
if not isinstance(antideriv,Integral):
    sym = xab[0]
    terms = tuple()
    if antideriv.is_Add:
        terms = antideriv.args
    else:
        terms = tuple((antideriv,))
    for term in terms:
        argtan = []
        for part in term.atoms(tan) | term.atoms(cot):
            argtan.append(part.args)
        for arg in argtan:
            from sympy import solve
            a = arg[0]
            K = solve(a-pi/2,sym)[0]
            P = limit(term, sym, K, dir="-") - limit(term, sym, K, dir="+")
            antideriv += P*floor((a-pi/2)/pi)
```

Result : It gives correct answer for `(1/(2+cos(x)))+(1/(3+sin(x)))` but gives wrong answer for examples given [here](http://www.reduce-algebra.com/reduce38-docs/trigint.pdf) in page 6.
`antideriv` of 3rd example has terms `(-3*log(tan(x/2) - 1), 3*log(tan(x/2) + 1), 8*atan(3*tan(x/2)))` here `log` is tending to `oo` that's why it gives `nan`.
```
>>> from sympy import *
>>> x = symbols('x')
>>> integrate((1/(2+cos(x)))+(1/(3+sin(x))),x)
2*sqrt(3)*atan(sqrt(3)*tan(x/2)/3)/3 + sqrt(2)*atan(3*sqrt(2)*tan(x/2)/4 + sqrt(2)/4)/2 + sqrt(2)*pi*floor((x/2 - pi/2)/pi)/2 + 2*sqrt(3)*pi*floor((x/2 - pi/2)/pi)/3
>>> integrate(3/(5+4*sin(x)),x)
2*atan(5*tan(x/2)/3 + 4/3) + 2*pi*floor((x/2 - pi/2)/pi)
>>> integrate(15/(cos(x)*(5-4*cos(x))),x)
nan
```

**Comment by jksuom** [comment]
This method is intended for those cases where conjugate log-terms have been combined to atan-terms. So the integrators producing the (raw) antiderivative have to be improved to do this.

**Comment by vishalg2235** [comment]
we can combine `log` terms as then `limit` will be finite number.
```
>>> from sympy import *
>>> x = symbols('x')
>>> limit(log(tan(x)+1)/log(tan(x)-1),x,pi/2)
1
>>> limit(log(tan(x)+1),x,pi/2)
oo
>>> limit(log(tan(x)+1),x,pi/2) - limit(log(tan(x)-1),x,pi/2)
nan
```

**Comment by vishalg2235** [comment]
@jksoum should I submit PR for this ?

**Comment by jksuom** [comment]
You could do that. It would be interesting to see if some integrals could be evaluated.

**Comment by vishalg2235** [comment]
I think it will work well if PR https://github.com/sympy/sympy/pull/13758 is also implemented.

**Comment by jksuom** [comment]
There should be more tests. You could probably find those by looking at unsolved integration issues.
