### ISSUE TITLE
erf has wrong limit in -oo

### ISSUE THREAD

**Issue by symbolique** [sympy/sympy#13750]
This could be one cause of #13733:
```py
>>> var('a x')
>>> limit(erf(-x), x, oo) # ok
-1
>>> limit(erf(1-x), x, oo) # ok
-1
>>> limit(erf(a-x), x, oo) # wrong
1
>>> limit(erf(sqrt(x)-x), x, oo) # wrong
1
```
There are multiple issues:
- `erf._eval_rewrite_as_tractable(z)` always rewrites for the `z->oo` case. This only works for the first two limits because `erf(1-x)` is rewritten as `-erf(x-1)`, but it can't be assumed in general.
- `_erfs` is neglected by the Gruntz implementation regardless of its argument, so the previous limitation causes a wrong result.

**Comment by Parapompadoo** [comment]
I would like to work on this.
Can someone please guide me a bit.

**Comment by normalhuman** [comment]
For real arguments, erf(z) is equal to sign(z) * erf(abs(z)), so the following rewrite produces correct limits for all aforementioned cases:
``
def _eval_rewrite_as_tractable(self, z):
    return (S.One - _erfs(abs(z))*exp(-z**2))*sign(z)
```
Unfortunately, this rewrite is not legitimate when z is complex; for example, `limit(erf(x*I), x, oo)` would return I instead of oo*I. Is it reasonable to check the type of argument when rewriting?
