### ISSUE TITLE
Inconsistent behaviour of power infinity (**oo)

### ISSUE THREAD

**Issue by Wrzlprmft** [sympy/sympy#13760]
Raising an expression to the power infinity behaves strange:

* A symbol (or general abstract expression) can be raised to the power infinity, but once it is simplified, it yields `nan`.
* A non-negative number smaller than one raised to the power infinity yields `0` – as expected.
* One raised to the power infinity yields `nan` and not `1` (which may be the source of all these problems).
* A number larger than one raised to the power infinity yields `oo` or `inf` as expected.

``` Python

from sympy import Symbol, oo, Rational, Float

x = Symbol("x", real=True)

x**oo                # x**oo
(x**oo).simplify()   # nan
(x**oo).subs({x:0})  # 0
Rational(1,2)**oo    # 0
Rational(1,1)**oo    # nan
Rational(3,2)**oo    # oo
Float(0.4)**oo       # 0
Float(1.0)**oo       # nan
Float(1.1)**oo       # inf
```

**Comment by jksuom** [comment]
This is explained in the [docstring](https://github.com/sympy/sympy/blob/master/sympy/core/power.py#L136) of `Pow`.

**Comment by Wrzlprmft** [comment]
@jksuom Thanks, that explains `1**oo is nan`, but it doesn’t cover `(x**oo).simplify() is nan` (which is the major annoyance here).

**Comment by jksuom** [comment]
What would you expect to get?

**Comment by Wrzlprmft** [comment]
What I put in, i.e. `(x**oo).simplify == x**oo`. I can still substitute `x` with a non-negative value other than one, so it’s not clear that the result is `nan`. Right now we have:

```Python
from sympy import Symbol, oo

x = Symbol("x", real=True)
expr = x**oo

expr.subs({x:0}).simplify()    # 0
expr.simplify().subs({x:0})    # nan
```

**Comment by jksuom** [comment]
I agree that `x**oo` would be a good choice though there may have been some particular reason for `nan`.

**Comment by Wrzlprmft** [comment]
> though there may have been some particular reason for `nan`.

In that case, `x**oo` should arguably directly evaluate to `nan` and there is no need to wait for a simplification attempt.

**Comment by jksuom** [comment]
It seems that the current version of SymPy is working this way already:
```
>>> x = Symbol("x", real=True)
>>> (x**oo).simplify()
x**oo
```

**Comment by Wrzlprmft** [comment]
Argh, stupid me. Should’ve updated.
