### ISSUE TITLE
Matrix.dot should be a little less lax for n x m matrices

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#13765]
See https://stackoverflow.com/questions/47839177/sympy-dot-product-results-in-a-list. If you have non-vector matrix and use `dot`, it takes the dot product of the matrices flattened out to a single vector:

```
>>> A = Matrix([[1, 2], [3, 4]])
>>> B = Matrix([[2, 3], [1, 2]])
>>> A
Matrix([
[1, 2],
[3, 4]])
>>> B
Matrix([
[2, 3],
[1, 2]])
>>> A.dot(B)
[11, 7, 16, 10]
```

The goal of `dot` is to be lax so that you can dot `1 x n` and `1 x n` without having to use `.T`, but for the case of an `n x m` matrix where neither `n` nor `m` are 1, it should probably give an exception rather than flattening the matrices, which is a bit arbitrary. 

Note that people coming from NumPy expect `dot` to be matrix multiplication. So the exception should perhaps indicate to use `*` to multiply matrices. Alternately we could just make `dot` multiply the matrices in this case, but I'm not a huge fan of that.

**Comment by asmeurer** [comment]
Apparently it's [documented](https://github.com/sympy/sympy/blob/1792d528d6c213a4fd488b6dad2de6d144278f94/sympy/matrices/matrices.py#L2366-L2368) that Matrix*vector gives a list of results. I think this isn't very helpful, as 1, it's inconsistent for n x m vs 1 x m matrices, 2, a list isn't as useful as a matrix, and 3, the result is exactly the same as if you just multiplied the matrix and the vector. 

But it would be a backwards incompatible change, and it's technically separate from flattening. Any thoughts?

**Comment by ahmed751995** [comment]
to make sure i understood well if we used B= n x m where n or m != 0 we should get error otherwise we should get a list of multiplying vectors

**Comment by asmeurer** [comment]
The behavior I'm suggesting is that it should only work if n or m are 1, and give an error otherwise. That isn't the behavior right now.

**Comment by ahmed751995** [comment]
I would like to work on it

**Comment by asmeurer** [comment]
OK, but be sure to coordinate with the existing pull request.

**Comment by siefkenj** [comment]
I am +1 for making `.dot` more sane and restricting it's input. When I reworked this code, it was quite contorted to stay compatible with the old functionality. Things would be much cleaner if it just worked on `1 x n` or `n x 1` matrices.

The error message for larger matrices should suggest how to flatten a matrix for use with `.dot`.

**Comment by asmeurer** [comment]
Is flattening a legit use-case? I guess if it's there someone must have used it. My guess is that most people using `dot` on a larger matrix would expect it to do multiplication, as in the SO question. 

What is the canonical way to flatten a matrix? `Matrix(list(M))`? Is there a better way that works even for sparse matrices?

**Comment by siefkenj** [comment]
`Matrix(list(M))` works for sparse matrices too, but won't return a sparse matrix. `M.reshape(1,len(M))` will preserve the type of `M`.

**Comment by sanyamg123** [comment]
I want to work on this issue. Can I work on it, if it isn't resolved yet?

**Comment by siefkenj** [comment]
@sanyamg123 This is being addressed by  #13768

**Comment by ac9888185875** [comment]
Is this issue still open or is resolved?
If it is opened, I would like to work on it.Can I?

**Comment by nunocalaim** [comment]
I just want to leave a note here that I am a numpy user and I have spent the last hour frustrated because I could not dot product two compatible matrices (e.g. (2,5) with (5, 3)) I found nowhere on the documentation that for such a case one uses * and I just found out by reading a closed issue on the github tracker of sympy.

Please!!! alert the user to use * instead of giving random errors.

The error I was getting was that the matrices were not compatible with sizes (5,2) and (5,3) so I kept trying to transpose the first matrix.

**Comment by asmeurer** [comment]
I've added a note to the deprecation removal issue. The deprecation notice should have had a `useinstead` added to it. I'll open an issue.

**Comment by asmeurer** [comment]
By the way, you can also use `@` if you are using Python 3.5 or newer. That will work both in SymPy and NumPy.
