### ISSUE TITLE
linsolve ignores equations with certain coefficients

### ISSUE THREAD

**Issue by normalhuman** [sympy/sympy#13770]
In SymPy 1.1.1, 
```
linsolve([sqrt(2)*(x-1), x+y], (x, y))
```
returns {(-y, y)}, which ignores the first equation. The expected output is {(1, -1)}. 

If sqrt(2) is replaced by 2 or 1/3 or 1.234, or sqrt(2.1), the output is correct.

**Comment by ArighnaIITG** [comment]
I am getting this correctly.

`>>> from sympy import *
>>> 
>>> x, y = symbols('x y')
>>> 
>>> linsolve([sqrt(2)*(x-1), x+y], (x, y))
{(1, -1)}
`

**Comment by watchduck** [comment]
Could you check the SymPy example from the Stackoverflow question this comes from? https://stackoverflow.com/questions/47879246/why-does-sympy-calculate-wrong-intersections-of-planes

**Comment by ylemkimon** [comment]
* 2 seems to work
* As 1.234 and sqrt(2.1) are floats, results are returned in floats: `{(1.0, -1.0)}`
* Regarding 1/3, if you are using Python 2, you should import `division` from `__future__` to get 0.333333, otherwise you will get zero. Also, to get SymPy Rational, you should do `S(1)/3`

**Comment by normalhuman** [comment]
Indeed, it works correctly in 1.1.2.dev. Closing the issue.
