### ISSUE TITLE
Per favore fate una doc decente

### ISSUE THREAD

**Issue by ridolfino** [sympy/sympy#13783]
La doc non è comprensibile, anzi è impresentabile....

**Comment by SourceCode2** [comment]
Hai completamente ragione.

**Comment by ylemkimon** [comment]
As most developers are native English speakers and mathematical terminologies are used, documentations are hard to read. If you don't mind, could you tell us which part(s) of documentation is hard to read?

**Comment by ridolfino** [comment]
I like the sympy lib, but I think the document is badly organized; can you redo it in a more understandable way? Maybe with more complete examples

**Comment by moorepants** [comment]
Related to last comment: https://github.com/sympy/sympy/issues/10456

**Comment by moorepants** [comment]
@ridolfino I think we would all like to see better documentation for SymPy. This is often a neglected part of open source software that is built mostly be volunteer work. Might you have some time to help us work on this topic? I'm happy to help you get started.

**Comment by asmeurer** [comment]
Please use English in the issue tracker. 

I think Jason's issue goes into this in more detail. If you have any concrete suggestions on how to improve the docs or which docs need improvement, please add them as a comment to issue #10456.

**Comment by ridolfino** [comment]
I can help you with the doc, but i need ti know perfectly the lib. Some1 can share examples with sympy pls?

**Comment by asmeurer** [comment]
The best way you can help as a new user is to indicate which docs you find lacking or confusing. These sorts of things tend to be difficult to see for those of us who already know the library well.
