### ISSUE TITLE
CDF of the Uniform distribution

### ISSUE THREAD

**Issue by Kiwiatomik** [sympy/sympy#13788]
Hi,

```
x = sp.symbols('x')
X = Uniform(x, 0, 1)
plot(cdf(X)(x),(x,-1,2),adaptive=False, num_of_points=200)
```
The code above displays the following plot:

![git_sympy_cdf_current](https://user-images.githubusercontent.com/33783067/34317931-443b956a-e7f5-11e7-8477-70134385fbc4.png)

It should rather look like this:

![git_sympy_cdf_right](https://user-images.githubusercontent.com/33783067/34317959-62cec74e-e7f6-11e7-9563-31face0a4efe.png)

In stats/crv_types.py, the cdf function is calculated from the pdf function (that cannot be plotted). I cannot tell exactly why it doesn't work, but the two following fixes might be a good starting point.

First, in stats/crv_types.py (line 2445 - 2449), change 

```
    def pdf(self, x):
        left, right = self.left, self.right
        return Piecewise(
            (S.One/(right - left), And(left <= x, x <= right)),
            (S.Zero, True))
```
to
```
    def pdf(self, x):
        left, right = self.left, self.right
        return (Piecewise((S.Zero, x <= left), (S.One / (right - left), x > left), (S.Zero, True)) 
                - Piecewise((S.Zero, x <= right), (S.One / (right - left), True)))
```

Second, in stats/crv_types.py (line 2451 - 2460), change 

```
    def compute_cdf(self, **kwargs):
        from sympy import Lambda, Min
        z = Dummy('z', real=True, finite=True)
        result = SingleContinuousDistribution.compute_cdf(self, **kwargs)(z)
        reps = {
            Min(z, self.right): z,
            Min(z, self.left, self.right): self.left,
            Min(z, self.left): self.left}
        result = result.subs(reps)
        return Lambda(z, result)
```

to

```
    def _cdf(self, x, ):
        return Piecewise((S.Zero, x < self.left), (S.One, x > self.right), 
                        ((x - self.right) / (self.left - self.right), True))
```

**Comment by normalhuman** [comment]
The cdf is not stored by distribution classes, it is computed  by `compute_cdf`  method from the pdf. The PDF of UniformDistribution class is implemented correctly. One issue with the `compute_cdf` method  is the substitutions
```
 reps = {
            Min(z, self.right): z,
            Min(z, self.left, self.right): self.left,
            Min(z, self.left): self.left}
        result = result.subs(reps)
```
which are apparently meant to simplify the outcome of integration, but are only valid on the interval between self.left and self.right.

**Comment by Kiwiatomik** [comment]
I see.

Then, what is currently the correct way to handle operations with different cdf? For instance, the distribution of the maximum of two variables is given by the product of both variables' cdf.

I would write something like this:
```
x = sp.symbols('x')
X = Uniform(x, 0, 1)
Y = Uniform(x, 1, 5)
cdf_max = cdf(X)(x) * cdf(Y)(x)
```
In this code, `cdf_max = x*(x/4 - 1/4)`. However, the true cdf of the maximum between X and Y is really different: `(-Min(0, x)/2 + Min(2, x)/2)*(-Min(1, x)/4 + Min(5, x)/4)`

**Comment by normalhuman** [comment]
The CDF of the maximum of two variables may or may not be the product of their CDFs - that depends on the joint distribution of those variables. Multivariate distributions are not currently implemented. I think this goes beyond the scope of this issue.

I like your proposed `_cdf` for UniformDistribution. Originally (in 1.1.1 and earlier) all CDFs were computed from given PDFs, which resulted in awkward integration  results like `cdf(Normal("x", 1, 2)`. This was recently changed with the addition of internal `_cdf` methods to some of the distributions. It makes sense for Uniform to be one of those with _cdf method. 

I do not understand the logic of your form of pdf: why is there the difference of two Piecewise functions?

**Comment by ethankward** [comment]
I think CDF's should be hardcoded for many more distributions, given that the integrator doesn't currently seem to be up to the task of computing them.

**Comment by Kiwiatomik** [comment]
The pdf function for a Uniform distribution on [0,1] looks like this:

![git_sympy_pdf](https://user-images.githubusercontent.com/33783067/34351539-38681208-ea58-11e7-935d-c6059331c39b.png)

It can be viewed as the difference between two step functions (the Piecewise functions in the code):

![git_sympy_piece1](https://user-images.githubusercontent.com/33783067/34351703-580afcb4-ea59-11e7-81e3-25b264ab2446.png)

and

![git_sympy_piece2](https://user-images.githubusercontent.com/33783067/34351709-5cb5abce-ea59-11e7-83fe-c6137875c94a.png)

Analytically, this pdf and the pdf currently implemented are equivalent. So why doing this? The main advantage is that you can plot this pdf with sympy.plotting.plot.

I don't know why the current pdf fails to plot though... And I don't know if it is worth changing the pdf.

**Comment by normalhuman** [comment]
The PDF plots for me as expected. What exact steps lead to its failure to plot? 

In any case, I wouldn't want to make the PDF more complicated for this reason. The current function, e.g., `Piecewise((1/4, (z >= 3) & (z <= 7)), (0, True))`  is correct and clear. If plot has an issue with this function, that's something to be fixed in plot, not in PDF.

**Comment by Kiwiatomik** [comment]
I have just updated sympy, and the pdf plots. Sorry about that...
