### ISSUE TITLE
Update documentation for n-th derivatives and array derivatives

### ISSUE THREAD

**Issue by Upabjojr** [sympy/sympy#13780]
After merging
* https://github.com/sympy/sympy/pull/13751
* https://github.com/sympy/sympy/pull/13655

We need to update the documentation and the SymPy tutorial.

**Comment by mohitiitb** [comment]
Hello, I am new to open source and would like to solve this issue.
Can you please guide me.

**Comment by mohitiitb** [comment]
Is this issue still open??

**Comment by yugeshk** [comment]
Hi, I am new to open source and would like to work on this issue.
As per my understanding, new documentation needs to be added [here](https://github.com/sympy/sympy/blob/master/doc/src/tutorial/calculus.rst) before _integration_.
I was thinking there could be two separate sub-headings for _n-th order_ and _array differentiation_ each having a couple of examples.

Is this fine?

**Comment by nityanandagohain** [comment]
I want to work on it
