### ISSUE TITLE
Applying doit() to Subs with Derivative changes the meaning of expression

### ISSUE THREAD

**Issue by normalhuman** [sympy/sympy#13795]
Consider the following: 
```
x, y = symbols('x y')
f = Function('f')
expr = Subs(Derivative(f(x, y), y), y, x)
```
The meaning of expr is clear: it's the partial derivative with respect to y, evaluated on the diagonal y=x. Now try `expr.doit()`: 
```
Derivative(f(x, x), x)
```
That's not the same thing; this is a derivative along the diagonal. For example, with f(x,y)=x+y the former derivative is equal to 1 and the latter is equal to 2. 

This behavior is responsible for #13791 because the method _eval_derivative of class Subs invokes Subs.doit(). I believe that any computation of derivatives of order 2 or higher of an expression with generic functions is likely to be incorrect due to this behavior: the first derivative will produce Subs(Derivative(...)) and the second derivative will apply doit, transforming the expression into an inequivalent one. Examples can be found in the linked issue.

### Possible resolution

I think that when an expression involves un-doable instances of Derivative(), the method Subs().doit should not substitute the variables of differentiation. Note that this would be different from the behavior of .subs method. If someone performs `Derivative(f(x, y), y).subs(y, x)`, it makes sense for them to get `Derivative(f(x, x), x)`. There is no expectation that the result of `subs` would be equivalent to original expression. But one expects such equivalence from `doit`. 

[The present `Subs().doit` method](https://github.com/sympy/sympy/blob/master/sympy/core/function.py#L1794) attempts to doit() the expression first, and then proceeds with subs regardless of the outcome. I sketched a conservative version of doit() below. This is a change of core functionality, and it does fail some tests which assume that Subs can operate freely with Derivative: [fails here](https://github.com/sympy/sympy/blob/master/sympy/core/tests/test_function.py#L254) and [here](https://github.com/sympy/sympy/blob/master/sympy/core/tests/test_function.py#L849). So this is not ready for a PR, but I hope for feedback. 

```
    def doit(self):
        expr = self.expr.doit()
        tied_vars = []
        for d in expr.atoms(Derivative):
            tied_vars.extend([v for v, count in d.args[1:]])    # can't substitute these variables
        subs_list = list(zip(self.variables, self.point))
        can_sub = [(var, pt) for (var, pt) in subs_list if var not in tied_vars]  # can do this
        var_remaining = [var for (var, pt) in subs_list if var in tied_vars]      # to be left un-subbed
        point_remaining = [pt for (var, pt) in subs_list if var in tied_vars] 
        if len(var_remaining) > 0:
            return Subs(expr.subs(can_sub), var_remaining, point_remaining)    
        else:
            return expr.subs(can_sub)
```

**Comment by asmeurer** [comment]
The proposed fix sounds correct to me. 

It can probably be made more lax. For instance, replacing a differentiation variable should be safe if the differentiated expression is free of that variable. For instance, `Subs(Derivative(f(x, y), y), y, z)` giving `Derivative(f(x, z), z)` is fine. 

How do the tests fail? In the first case, the substitution doesn't replace the differentiation variable because it substitutes a variable with a number. 

I'm also not so sure that `subs` should not be fixed as well. `subs` I think in general should respect mathematical equality. Structural substitution can be done with xreplace. And having `Subs` and `subs` be different could be confusing and lead to bugs.

**Comment by normalhuman** [comment]
I agree with changing subs, so that subs remains equivalent to Subs().doit(). The tests fail because the above sketch is too conservative in some ways; it also turned out to be too lax in some ways. This is important to get right, so I will summarize the situation here. 
 
Substitution `Derivative(A, B).subs(C, D)` should proceed only in the following three cases.  

### Substitution does not touch the variables in B

Tested with `len(B.free_symbols & (C.free_symbols | D.free_symbols)) == 0`. Avoids the following pitfalls:

```
Derivative(f(x, y), y).subs(y, x)  # currently returns Derivative(f(x, x), x), wrong 
Derivative(f(x, y), y).subs(x, y)  # currently returns Derivative(f(y, y), y), wrong 
```

Note that my first attempt did not fix the second case. 

### Replacing the variable of differentiation with new variables

Tested with `isinstance(B, Symbol) and B == C and len(A.free_symbols & D.free_symbols) == 0`. This allows `Derivative(f(x, y), y).subs(y, z)` to proceed, but prevents 
```
Derivative(f(x, y), exp(x+y)).subs(exp(x+y), z)  # currently returns Derivative(f(x, y), z), wrong
```

### Replacing an expression with an equivalent one

Tested with `C.equals(D)`

--- 

Is there anything I miss here? 

Also, I notice there is already a check in place when D is an expression: 
```
Derivative(f(x, y), y).subs(y, x+1)  # returns Subs(Derivative(f(x, y), y), (y,), (x + 1,)), correct
```
I suppose the above logic should be added in the same place, wherever that place is...

**Comment by asmeurer** [comment]
equals is an expensive check. I wouldn't do it in subs.

**Comment by asmeurer** [comment]
Derivatives on more complicated functions are going to be removed (https://github.com/sympy/sympy/issues/7027), so we should just test against things like `Derivative(F(f(x), g(x)), g(x))`. The fix for that issue can likely be made separately from this one, but any new tests added shouldn't rely on that behavior. 

I think the test for the second case should be `if B == C and D._diff_wrt and len(A.free_symbols & D.free_symbols) == 0` (use `_diff_wrt` instead of `isinstance(Symbol)`). 

There might be other corner cases involving matrix/tensor derivatives. @Upabjojr can you think of any?

**Comment by Upabjojr** [comment]
Just a quick test:
```python
In [1]: expr = sin(x*exp(y))

In [2]: Derivative(expr, y).subs(y, x)
Out[2]: 
d ⎛   ⎛   x⎞⎞
──⎝sin⎝x⋅ℯ ⎠⎠
dx           

In [3]: _.doit()
Out[3]: 
⎛   x    x⎞    ⎛   x⎞
⎝x⋅ℯ  + ℯ ⎠⋅cos⎝x⋅ℯ ⎠

In [8]: Derivative(expr, y).doit().subs(y, x)
Out[8]: 
   x    ⎛   x⎞
x⋅ℯ ⋅cos⎝x⋅ℯ ⎠
```

Yes, I agree we should fix `._eval_subs` for `Derivative`.

**Comment by normalhuman** [comment]
Case 1, "Substitution does not touch the variables in B", should be expanded. We want the following to be true (it's one of the tests): 
```
Derivative(g(x), x).subs(g(x), f(x)) == Derivative(f(x), x)
```
What matters is that none of variables are affected by substitution, even though there is overlap in the symbols they contain. In the notation of [_eval_subs](https://github.com/sympy/sympy/blob/master/sympy/core/function.py#L1463) the test for Case 1 can be stated as 
```
all(v.subs(old, new) == v for v in self.variables)
```

**Comment by normalhuman** [comment]
I'm trying to work out the rule for substituting functions (not expressions).  Example:  
```
Derivative(sin(x), x).subs(sin, exp)
```
Currently this returns `Derivative(exp(x), x)`. Is this wrong, because the derivative is actually cos(x), and substitution, which is placed after differentiation, should have no effect on it? Or is this correct, because `subs` here is not meant to be the evaluation of derivative at a point?

One of [current tests](https://github.com/sympy/sympy/blob/master/sympy/core/tests/test_function.py#L561) asserts that function substitution should be allowed to happen before differentiation: 
```
assert f(g(x)).diff(x).subs(g, Lambda(x, 2*x)).doit() == f(2*x).diff(x)
```

--- 

My current set of situations when `_eval_subs(self, old, new)` can go ahead with substitution (self being a Derivative):

1. Neither old nor new term contains any self.variables
2. Substitution replaces one of self.variables by an expression whose  variable(s) are not present in self.args[0]
3. Substitution replaces one of self.variables by an expression that does not depend on any other variables (replacing x by some g(x)).
4. self.args[0] == old, complete replacement of differentiated expression
5. old == new, trivial substitution
