### ISSUE TITLE
Should the output of arbitrary_point be changed for Plane objects?

### ISSUE THREAD

**Issue by normalhuman** [sympy/sympy#13799]
According to the docs, [arbitrary_point](http://docs.sympy.org/latest/_modules/sympy/geometry/plane.html#Plane.arbitrary_point) is supposed to parameterize a circle of radius 1 in the plane.  Maybe this what its output does, but it's hard to see how anyone could use it (scroll to the right to see the entire formula). 
```
>>> from sympy import *
>>> Plane(Point(1, 2, 3), Point(2, 3, 4), Point(0, 0, 0)).arbitrary_point()
Point3D(-(-2*sin(_t) + cos(_t) - 3)*(-2*sqrt(-84*sin(2*_t) - 216*sin(_t) - 171*cos(2*_t) - 1044*cos(_t) - 921) + 24*sin(_t) + 12*cos(_t) + 60)/(6*(4*sin(2*_t) + 24*sin(_t) + 3*cos(2*_t) + 36*cos(_t) + 49)) + (-2*sqrt(-84*sin(2*_t) - 216*sin(_t) - 171*cos(2*_t) - 1044*cos(_t) - 921) + 24*sin(_t) + 12*cos(_t) + 60)*cos(_t)/(4*sin(2*_t) + 24*sin(_t) + 3*cos(2*_t) + 36*cos(_t) + 49) + (-2*sqrt(-84*sin(2*_t) - 216*sin(_t) - 171*cos(2*_t) - 1044*cos(_t) - 921) + 24*sin(_t) + 12*cos(_t) + 60)/(4*sin(2*_t) + 24*sin(_t) + 3*cos(2*_t) + 36*cos(_t) + 49), (sin(_t) + 2)*(-2*sqrt(-84*sin(2*_t) - 216*sin(_t) - 171*cos(2*_t) - 1044*cos(_t) - 921) + 24*sin(_t) + 12*cos(_t) + 60)/(4*sin(2*_t) + 24*sin(_t) + 3*cos(2*_t) + 36*cos(_t) + 49) + (-2*sin(_t) + cos(_t) - 3)*(-2*sqrt(-84*sin(2*_t) - 216*sin(_t) - 171*cos(2*_t) - 1044*cos(_t) - 921) + 24*sin(_t) + 12*cos(_t) + 60)/(3*(4*sin(2*_t) + 24*sin(_t) + 3*cos(2*_t) + 36*cos(_t) + 49)), -(-2*sin(_t) + cos(_t) - 3)*(-2*sqrt(-84*sin(2*_t) - 216*sin(_t) - 171*cos(2*_t) - 1044*cos(_t) - 921) + 24*sin(_t) + 12*cos(_t) + 60)/(6*(4*sin(2*_t) + 24*sin(_t) + 3*cos(2*_t) + 36*cos(_t) + 49)))
```
Normally, parametric equation of a circle involves sin(t) and cos(t) in a linear way, not under square roots and mixed with sin(2t) and cos(2t). Simplifying didn't get make much difference.

My suggestion: instead of trying to fix the method, change it entirely so that it returns a point with two parameters s_, t_ where all three coordinates are linear functions of s_ and t_. This means changing a public method, but from what I can see, this method could hardly be used in practice. 

Also, #13789 proposes to implement a parameter finding routine, given a point on the entity. This was attempted in #13790 but since plane's arbitrary_point does not run through the entire plane, the parameter finding can't possibly work correctly. (It also won't work because `solve` will hang on such complex equations.)

**Comment by smichr** [comment]
👍 The object returned should be able to represent any point in the plane. To do so in some linear fashion would be highly desirable.
