### ISSUE TITLE
Should free_symbols return set() for undefined functions?

### ISSUE THREAD

**Issue by normalhuman** [sympy/sympy#13802]
Consider the following:
```
>>> from sympy import *
>>> f = Function('f')
>>> diff(f)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/sympy/sympy/core/function.py", line 1961, in diff
    return Derivative(f, *symbols, **kwargs)
  File "/home/ubuntu/sympy/sympy/core/function.py", line 1112, in __new__
    if len(variables) != 1:
TypeError: object of type 'property' has no len()
```

I understand that diff expects an expression rather than a Function, but some people have the idea of differentiating functions, and throwing this TypeError at them isn't nice.  Apparently, `diff` expects to get a set from `f.free_symbols` but doesn't. 
```
>>> f.free_symbols
<property object at 0x7fb96c6e93b8>
```

Here is another instance, with a slightly different error message but the same root cause: 
```
>>> x = Symbol('x')
>>> diff(f, x)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/sympy/sympy/core/function.py", line 1961, in diff
    return Derivative(f, *symbols, **kwargs)
  File "/home/ubuntu/sympy/sympy/core/function.py", line 1198, in __new__
    if symbol_set.difference(expr.free_symbols):
TypeError: 'property' object is not iterable
```

**Comment by ylemkimon** [comment]
A function itself has no variable or symbol and differentiation operation is not possible. I think it is a correct behavior, since a function cannot have `free_symbols`.

**Comment by normalhuman** [comment]
To clarify, I'm not saying that `f` should have actual free symbols, or that `diff(f)` should not be an error. I'm saying that SymPy core code expects that accessing `.free_symbols` property of a SymPy object will return a `set`, and throws an unintentional exception when it isn't., Pretty much any SymPy object has free_symbols property of type `set`, including Integers and Rationals. Examples: 
```
a = S(4)
print(a.free_symbols)  # set()
b = Rational(2, 3)
print(b.free_symbols)  # set()
M = Matrix([3,4])
print(M.free_symbols)  # set()
```
Having `f.free_symbols` be `set()` for undefined functions would be consistent and avoid that exception. 

From a user perspective, I don't think that "TypeError: 'property' object is not iterable" is a message that should be displayed to a user typing `diff(f, x)`. The user wasn't trying to iterate a property object.

**Comment by ylemkimon** [comment]
I think it's better to add a check for Function at the top of diff, and raise an error like: `Cannot differentiate a function without variable(s). Did you mean {function name}({variable name if given else x})?`.
