### ISSUE TITLE
Operations/simplification on bitvectors/modular rings?

### ISSUE THREAD

**Issue by pfalcon** [sympy/sympy#13821]
Sorry for dumb questions (I googled them up, I swear).

Can SymPy let me tell that `x` is a bitvector of size 8, or (somewhat) equivalently, that it's unsigned value modulo 256?

The can it perform simplification of `(x << 1) >> 1` to `x & 0x7f`? Or calculate that for `x = 255`, expression `x + 5 > 100` is false?

Actually, can SymPy simplify relations?

I get following (in the online SymPy Live Shell):

~~~ 
>>> k, m, n = symbols('k m n', integer=True)
>>> simplify((k > 5) & (k > 6))
k>5∧k>6
~~~

Thanks!

**Comment by normalhuman** [comment]
Bits and unsigned integers are not really mathematical concepts, they are details of hardware implementation. There are no bit shifts in SymPy, there is modular arithmetics performed by [`Mod`](http://docs.sympy.org/latest/modules/core.html#sympy.core.mod.Mod) function. Taking Mod by 256 amounts to working with 8-bit unsigned integers. For example:
```
>>>  (Mod(x+5, 256) > 100).subs(x, 255)
False
```
Also, 
```
>>> simplify(Mod(2*x, 256)/2)
Mod(x, 128)
```
expresses `(x << 1) >> 1` being `x & 0x7f`. 

The simplification of inequality systems can be achieved with [`reduce_inequalities`](http://docs.sympy.org/latest/modules/solvers/inequalities.html#sympy.solvers.inequalities.reduce_inequalities)
```
>>> reduce_inequalities([k > 5, k > 6])
(6 < k) & (k < oo)
```
The part with "k less than infinity" may seem redundant, but otherwise the answer is what one would expect.

**Comment by pfalcon** [comment]
@normalhuman: I appreciate the quick response! (And Happy New Year!)

> Bits and unsigned integers are not really mathematical concepts,

Of course they are. That's what good about math - anything which one can imagine and anything one can't is a mathematical concept ;-). For example, unsigned integers are also known as https://en.wikipedia.org/wiki/Natural_number , etc.

> they are details of hardware implementation.

But you're right, I'm interested in a mathematical formalism which describes workings of a binary computer.

> >>> simplify(Mod(2*x, 256)/2)
> Mod(x, 128)

That was it, great!

Let me try to abuse for attention for more stupid questions if you let:

1. The only way I found to extract "divisor" (128 in the example above) from Mod object is `simplify(Mod(2*x, 256)/2).args[1]`. Is that the correct way?

2. 

> >>> reduce_inequalities([k > 5, k > 6])
> (6 < k) & (k < oo)

That's cool too! But seems that reduce_inequalities() takes "conjunctive form", what if I have "or" disjunction? I'm not even able to write the formula, far less pass it to reduce_inequalities():

~~~
>>> x > 1 | x > 2
Traceback (most recent call last):
[...]
TypeError: BooleanAtom not allowed in this context.
~~~

**Comment by pfalcon** [comment]
I also decided to submit a dedicated feature request with some references and rough requirement ideas: https://github.com/sympy/sympy/issues/13823

**Comment by normalhuman** [comment]
Parentheses are required in `(x > 1) | (x > 2)`

But you are right, the `reduce_inequalities` takes a system of inequalities, which means they are joined by AND. The only way to express OR logic there is to negate the inequality and then negate the result:
```
reduce_inequalities([x <= 1, x <= 2]) 
```
returns x <= 1, the negation being x > 1. 

Yes, the sort of syntax and manipulation you'd like to see are not developed in SymPy.

**Comment by pfalcon** [comment]
> Parentheses are required in (x > 1) | (x > 2)
Ah, makes sense! One can only share a sentiment of regret that Python's boolean operators `or`/`and` aren't overridable (which have the right precedence), but reading why they aren't (https://www.python.org/dev/peps/pep-0335/), one can agree with the decision to not make them so.

Thanks again @normalhuman for insightful replies, closing this then, hope #13823 can survive for longer time to collect feedback.
