### ISSUE TITLE
Max & Min converting using SymPy

### ISSUE THREAD

**Issue by AAmberFan** [sympy/sympy#13831]
Why many languages likes js and R cannot be converted from Max & Min?
![image](https://user-images.githubusercontent.com/26391392/34533015-54ffb7d4-f086-11e7-945a-5708f6739d5d.png)

**Comment by normalhuman** [comment]
I suppose these should be added, considering  JavaScript does have `Math.max` and `Math.min`. 

Meanwhile, there is a workaround: Max(x, y) is equivalent to `(x+y+Abs(x-y))/2`, and Abs is supported. 

>>> jscode((1+y+Abs(1-y)) / 2)
'(1/2)*y + (1/2)*Math.abs(y - 1) + 1/2'

Similarly, Min(x, y) is equivalent to (x+y-Abs(x-y))/2.
