### ISSUE TITLE
solve/nonlinsolve: RuntimeError: run out of coefficient configurations

### ISSUE THREAD

**Issue by smichr** [sympy/sympy#13849]
```
>>> solve((t*(sqrt(5) + sqrt(2)) - sqrt(2), t), t)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "sympy\sympy\solvers\solvers.py", line 1157, in solve
    solution = _solve_system(f, symbols, **flags)
  File "sympy\sympy\solvers\solvers.py", line 1766, in _solve_sy
stem
    poly = g.as_poly(*symbols, extension=True)
  File "sympy\sympy\core\basic.py", line 707, in as_poly
    poly = Poly(self, *gens, **args)
  File "sympy\sympy\polys\polytools.py", line 128, in __new__
    return cls._from_expr(rep, opt)
  File "sympy\sympy\polys\polytools.py", line 239, in _from_expr

    return cls._from_dict(rep, opt)
  File "sympy\sympy\polys\polytools.py", line 183, in _from_dict

    domain, rep = construct_domain(rep, opt=opt)
  File "sympy\sympy\polys\constructor.py", line 237, in construc
t_domain
    result = _construct_simple(coeffs, opt)
  File "sympy\sympy\polys\constructor.py", line 44, in _construc
t_simple
    domain, result = _construct_algebraic(coeffs, opt)
  File "sympy\sympy\polys\constructor.py", line 92, in _construc
t_algebraic
    g, span, H = primitive_element(exts, ex=True, polys=True)
  File "sympy\sympy\polys\numberfields.py", line 879, in primiti
ve_element
    raise RuntimeError("run out of coefficient configurations")
RuntimeError: run out of coefficient configurations

>>> nonlinsolve((t*(sqrt(5) + sqrt(2)) - sqrt(2), t), t)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "sympy\sympy\solvers\solveset.py", line 2188, in nonlinso
lve
    system, symbols)
  File "sympy\sympy\solvers\solveset.py", line 1992, in _separat
e_poly_nonpoly
    poly = eq.as_poly(*symbols, extension=True)
  File "sympy\sympy\core\basic.py", line 707, in as_poly
    poly = Poly(self, *gens, **args)
  File "sympy\sympy\polys\polytools.py", line 128, in __new__
    return cls._from_expr(rep, opt)
  File "sympy\sympy\polys\polytools.py", line 239, in _from_expr

    return cls._from_dict(rep, opt)
  File "sympy\sympy\polys\polytools.py", line 183, in _from_dict

    domain, rep = construct_domain(rep, opt=opt)
  File "sympy\sympy\polys\constructor.py", line 237, in construc
t_domain
    result = _construct_simple(coeffs, opt)
  File "sympy\sympy\polys\constructor.py", line 44, in _construc
t_simple
    domain, result = _construct_algebraic(coeffs, opt)
  File "sympy\sympy\polys\constructor.py", line 92, in _construc
t_algebraic
    g, span, H = primitive_element(exts, ex=True, polys=True)
  File "sympy\sympy\polys\numberfields.py", line 879, in primiti
ve_element
    raise RuntimeError("run out of coefficient configurations")
RuntimeError: run out of coefficient configurations
```

**Comment by jksuom** [comment]
It is easy to create new coefficient configurations. This seems to suffice in most cases.
```
 def _coeffs_generator(n):
     """Generate coefficients for `primitive_element()`. """
-    for coeffs in variations([1, -1], n, repetition=True):
-        yield list(coeffs)
+    for coeffs in variations([1, -1, 2, -2, 3, -3], n, repetition=True):
+        # Two linear combinations with coeffs of opposite signs are
+        # opposites of each other. Hence it suffices to test only one.
+        if coeffs[0] > 0:
+            yield list(coeffs)
```

**Comment by jksuom** [comment]
It looks like `variations` will return a generator. So we should take `coeffs = list(coeffs)` before testing `coeffs[0]`.

**Comment by ArighnaIITG** [comment]
@smichr , @jksuom , I would like to proceed on this. Could you please guide me?

**Comment by jksuom** [comment]
You could modify `_coeffs_generator` in numberfields.py as shown in the patch above and run the `solve` and `nonlinsolve` commands presented by @smichr .

**Comment by skirpichev** [comment]
> This seems to suffice in most cases.

@jksuom, ``[1, -1, 2, -2, 3, -3]`` looks like a new set of magic numbers.  Shouldn't it be the sequence of integers up to ``n`` (by absolute value)?

**Comment by jksuom** [comment]
Any not-too-small set would suffice, in principle, but numbers like these have the least absolute value.

The primitive element theorem says that such an element can be obtained as a linear combination of generators. In most cases it is enough to take coefficients +/-1 (e.g. in `QQ(sqrt(2), sqrt(3))`).

**Comment by skirpichev** [comment]
> Any not-too-small set would suffice

This sounds not very quantitatively.

> In most cases

But we should carry about all cases.  So, probably, there should be an infinite stream of coefficient guesses if we can't use a bounded set, suitable for given polynomial degree of the primitive element.

**Comment by jksuom** [comment]
I think this would work in practice. If not, then one can add numbers to the set or use the iterative default method (with `ex=False`) for the construction.

**Comment by skirpichev** [comment]
> I think this would work in practice.

Of course.  Until you catch another instance of this bug with a little different input...

> If not, then one can add numbers

I believe, there exists some theoretical bound on size of these coefficients.  In which case using it - better.

> or use the iterative default method (with ex=False) for the construction.

Another approach could be - re-run primitive_element constrruction with ex=False, instead of throwing an exception.  Not reasons to blowup, if we can do the job by another way.  Unfortunately, now ex flag also changes output format, so it will require more severe rewriting of the primitive_element() method.

**Comment by jksuom** [comment]
> re-run primitive_element constrruction with ex=False, instead of throwing an exception.

This looks like a good idea before a generator for all coefficient combinations in Z^n starting from those with least absolute value is found.

**Comment by skirpichev** [comment]
> This looks like a good idea before a generator 

I think, this is better - as a fallback method.

> all coefficient combinations in Z^n

But there shouldn't be the need to search over all coeffs in Z^n.  For example, for extension list ``[x, y]``, where elements have minimal polynomials of degrees less than ``m`` - we can search primitive element as ``t = x + k*y``and the number of "bad" cases for coefficient ``k`` in ``Q`` will be strictly less than ``m**2``.  So, if we take ``m**2`` distinct rationals (or pairs in ``Z``) - there should be success for sure.  For ``n`` elements, probably we should search over ``m**n`` distinct lists.

No need for fallback method.  What do you think?

**Comment by jksuom** [comment]
I agree with your reasoning that something like `m**n` coefficient vectors would suffice. I would like to have a method of enumerating those vectors that would start from the neighbourhood of the origin and then proceed gradually to bigger vectors. Then it would not be necessary to consider some bounds.

**Comment by skirpichev** [comment]
In the Diofant - there is ``cantor_product()`` method.  Sage has similar method too.

Something like this:
```python
In [36]: from itertools import islice, tee
In [37]: from diofant.utilities.iterables import cantor_product
In [38]: from diofant import Integers
In [39]: i1 = (_ for _ in Integers if _ != 0)
In [40]: list(islice(cantor_product(*tee(i1, 3)), 10))
Out[40]: [(1, 1, 1), (1, 1, -1), (1, -1, 1), (1, -1, -1), (-1, 1, 1), (-1, 1, -1), (-1, -1, 1), (-1, -1, -1), (1, 1, 2), (1, -1, 2)]
```

**Comment by skirpichev** [comment]
> Then it would not be necessary to consider some bounds.

But there could be some bugs inside of this loop over stream coefficients.  Which may lead to non-termination of the computation.

This is why I usually find bounds useful.  In this example, we could indicate user that something is definitely wrong, not just too slow.
