### ISSUE TITLE
n-th order derivatives behave incorrectly with doit(), and do not denest

### ISSUE THREAD

**Issue by normalhuman** [sympy/sympy#13843]
I tried out n-th derivatives (#13751) and found a couple of oddities. The setup: 
```
from sympy import *
m, n = symbols('m n', integer=True)
x = symbols('x')
f = Function('f')
``` 
First of all, `doit` is wrong: 
```
>>> Derivative(f(x), (x, n)).doit()
Derivative(f(x), x)
```
The derivatives are unwilling to combine:
```
>>> Derivative(Derivative(f(x), (x, m)), (x, n))   
Derivative(Derivative(f(x), (x, m)), (x, n))
```
They do combine if a symbolic order is followed by numeric: 
```
>>> Derivative(Derivative(f(x), (x, m)), (x, 3))
Derivative(f(x), (x, m + 3))
```
But not the other way around: 
```
>>> Derivative(Derivative(f(x), (x, 3)), (x, n))
Derivative(Derivative(f(x), (x, 3)), (x, n))
```

**Comment by akash9712** [comment]
I'd like to work on this. 
Also, as per this current behaviour, 
```
>>> Derivative(Derivative(f(x, y), x), y) == Derivative(Derivative(f(x, y), y), x) # True only when f(x, y) is continuous
True
```
Is this the intended behaviour? The order in which the derivatives are being taken should not be interchangable unless the function can be determined to be continuous.

**Comment by normalhuman** [comment]
Commutativity of such derivatives is assumed [by design](https://github.com/sympy/sympy/blob/master/sympy/core/function.py#L931), and I think this is the correct decision. On sufficiently abstract level (distributions) derivatives [always commute](https://en.wikipedia.org/wiki/Symmetry_of_second_derivatives#Distribution_theory_formulation). The lack of commutativity only comes up in some edge cases in real analysis, and in those cases, SymPy wouldn't be able to compute the derivative anyway. When partial derivatives can be computed with CAS methods at all, they commute.

**Comment by asmeurer** [comment]
CC @Upabjojr
