### ISSUE TITLE
sample method for GammaInverseDistribution

### ISSUE THREAD

**Issue by gxyd** [sympy/sympy#13879]
Currently `GammaInverseDistribution` https://github.com/sympy/sympy/blob/master/sympy/stats/crv_types.py#L1186 doesn't have a `sample` method. An attempt was made to add in PR #11673 to add `sample` method. Though the tests haven't been added.

#### What needs to be done?

* Add docstring and tests for it.
* The contributor should make sure to send a PR with ownership of original commit retained to author of PR https://github.com/sympy/sympy/pull/11673 , i.e. the submitted PR should be based on top of PR #11673.

**Comment by ashish1500616** [comment]
I would like to work on this issue.

**Comment by 96mohitm** [comment]
Hi, @gxyd I would like to take up this issue, as I am new to Sympy, can you please guide me on sample method. Thanks!

**Comment by gxyd** [comment]
Yes, please go ahead. As mentioned in the "What needs to be done section?" section in issue description, you just need to add test case for it. 

Make sure you do this on top of commits of PR https://github.com/sympy/sympy/pull/11673

**Comment by gxyd** [comment]
Can you please decide which one of you will work on this? @ashish1500616 @96mohitm

**Comment by ashish1500616** [comment]
@96mohitm You can take up this issue.

**Comment by gxyd** [comment]
I just came across this issue https://github.com/sympy/sympy/issues/7358 . I've just commented it so I don't forget, will take a look later.

**Comment by gxyd** [comment]
@normalhuman this is a stat one. Would you like to take a look?

**Comment by 96mohitm** [comment]
@gxyd regarding the issue #13879 I need to make a pr over the pr #11673 how to clone this in my fork?
Can you give a example test for any other method so that i can get a reference. Thanks.

**Comment by vishalg2235** [comment]
@96mohitm are you working in this issue?

**Comment by 96mohitm** [comment]
Yes, @vishalg2235

**Comment by h-ranjan1110** [comment]
@96mohitm   are you working on this issue?

**Comment by 96mohitm** [comment]
@h-ranjan1110 go ahead.
