### ISSUE TITLE
Derivatives of negative order should be rejected

### ISSUE THREAD

**Issue by normalhuman** [sympy/sympy#13873]
This seems wrong:
```
>>> sin(x).diff(x, -1)
sin(x)
```
It's meaningless and it doesn't even print correctly:
```
>>> pprint(Derivative(sin(x), (x, -1)))
d         
──(sin(x))
dx 
``` 

An attempt to create a Derivative with negative order of differentiation should raise a ValueError in the `__new__` method of `Derivative` class.  I imagine the check being added [here](https://github.com/sympy/sympy/blob/master/sympy/core/function.py#L1176):

```
if count.is_negative:
    raise ValueError("Negative order derivatives are not allowed")
```

This is not entirely busywork because a user may have determined derivative order programmatically, and had a bug somewhere. It's better to inform them of the error than to ignore it.

**Comment by himanshuladia** [comment]
I would like to take this up.

**Comment by normalhuman** [comment]
Aside: one might consider that negative order derivatives can be [interpreted as integrals](https://math.stackexchange.com/a/1503626) and then maybe `diff(sin(x), (x, -1))` should pass the function to Integral. I don't think this would be the right decision. As the Math.SE post itself indicates, this is a hairy subject. For example, `diff(3, (x, -2))` if we wanted to implement it, would be `(3/2)*x**2 + b*x + c` with arbitrary b, c but `integrate` won't give `b*x` because it doesn't include constant term.  

And then there is the whole story of [fractional calculus](https://en.wikipedia.org/wiki/Fractional_calculus), with derivatives of arbitrary real order. This is very far from anything that Derivative class can feasibly support at the moment. If anyone wants to develop a Fractional Calculus module for SymPy, that could be interesting. But as a separate thing, not as an extension of Derivative. There are many different formulations of fractional derivatives, anyway.

**Comment by himanshuladia** [comment]
You might ask to add a fractional calculus module to the ideas page

For the negative order derivative, raising a ValueError at the place you told doesn't seem to work.

**Comment by asmeurer** [comment]
Yeah, it should raise an error. There are too many issues with arbitrary constants. We have `integrate`, and `dsolve(Eq(diff(f(x), x, 2), 3), f(x))` will take two "negative derivatives" with constants. 

Fractional calculus should be a separate function from `diff`. While it would be nice to have, it's too obscure for `diff`. Also I think there might be multiple definitions of a fractional derivative (but I could be misremembering that).

**Comment by smichr** [comment]
> Yeah, it should raise an error

I tried to remove this but there are a couple places that generate errors that I couldn't easily figure out what to do. I made note of them in commit "negative count related" 061efe5f8cc3bc475a1f1fc39f4474c7b6f60484 of #15049.

**Comment by smichr** [comment]
So here is a place where it arises and I am not sure of the best way to deal with this:
```
exprm2 = x*sin(x)*exp(x)
exprm2.diff((x, n))
Sum(
    Piecewise(
        (x*factorial(n)*Derivative(exp(x), (x, _k2))*Derivative(sin(x), (x, -_k2 + n))/(factorial(_k2)*factorial(-_k2 + n)),
            Eq(_k1, 0)),
        (factorial(n)*Derivative(exp(x), (x, _k2))*Derivative(sin(x), (x, -_k2 + n - 1))/(factorial(_k2)*factorial(-_k2 + n - 1)),
            Eq(_k1, 1)),
        (0, True)),
    (_k1, 0, n), (_k2, 0, n))
```
This is generated in `Mul._eval_derivative_n_times`. `-_k2+n-1` will be negative when `_k2==n`; this generates division by `zoo=factorial(-1)` which
drops that term from the sum when `_k1=1`...but is there a better way of
dropping it so we don't have to also encounter negative order derivatives?

Maybe `Max(-k2+n-1,0)` could be used to keep the order of the derivative from being 0 or...derivatives of negative order could arbitrarily be set to 0 so `x.diff(x,-1) = 0`?
