### ISSUE TITLE
cot(x).rewrite(sin) is broken

### ISSUE THREAD

**Issue by Akuli** [sympy/sympy#13882]
```python3
>>> cot(x).subs(x, 1.2)
0.388779569368205
>>> cot(x).rewrite(sin).subs(x, 1.2)
1.55511827747282
>>> cot(x).rewrite(sin)
2*sin(2*x)/sin(x)**2
```

Correct rewrite: cot x = (cos x)/(sin x) = (2 sin x cos x)/(2 sin² x) = sin(2x) / (2 sin² x)

The two should be in the denominator.

**Comment by Akuli** [comment]
Seems like fixing this would be simple as editing `cot._eval_rewrite_as_sin` in `sympy/functions/elementary/trigonometric.py`. I can create a pull request if nobody else wants to fix this.

**Comment by gxyd** [comment]
Yes, please submit a PR. You just need to fix this line https://github.com/sympy/sympy/blob/master/sympy/functions/elementary/trigonometric.py#L1389. Also write a test case for this.

**Comment by ssk497** [comment]
Hi, @gxyd I would like to take up this issue.Thanks!

**Comment by ArighnaIITG** [comment]
I am submitting a PR based on the above issue.. Thanks..!!
