### ISSUE TITLE
max & min

### ISSUE THREAD

**Issue by AAmberFan** [sympy/sympy#13887]
i found most language cannot be converted into max & min like octave,Fortran and others
(js and R have been fix , thx ;) )

**Comment by normalhuman** [comment]
A good issue for a beginner to tackle (preferably, adding more than just min and max): see the PRs #13832 and #13840 for an illustration of what needs to be done.

**Comment by sanyamg123** [comment]
I want to look into the issue.   Can you please guide me @normalhuman .
