### ISSUE TITLE
test case for syntax error on lambdify

### ISSUE THREAD

**Issue by gxyd** [sympy/sympy#13881]
See this issue https://github.com/sympy/sympy/issues/11044 . That issue was fixed in PR https://github.com/sympy/sympy/pull/11566. Though no test case was added for the `lambdify`.

#### What needs to be done?

Add test case that this works just fine:
```python
>>> from sympy import MatrixSymbol, lambdify
>>> x = MatrixSymbol('x', 3, 1)
>>> f = lambdify(x, x.T*x)
```

Test case needs to be added in appropriate file

**Comment by 96mohitm** [comment]
Hi, @gxyd I would like to take up this issue.

**Comment by gxyd** [comment]
Please go ahead.

**Comment by shril** [comment]
Hi, @gxyd 
Where should I add the test case?

**Comment by ArighnaIITG** [comment]
@gxyd , Could you elaborate as to what test case I should write?
I am getting this --

`>>> from sympy import MatrixSymbol, lambdify`
`>>> x = MatrixSymbol('x', 3, 1)`
`>>> f = lambdify(x, x.T*x)`
`>>> f`
`<function <lambda> at 0x7f279f32fa28>`

**Comment by mayankgagrwl** [comment]
I want to take this issue if still open..

**Comment by tanayag** [comment]
@mayankgagrwl I guess PR is all right but, we are waiting for #13984 to get solved!

**Comment by harsh-2711** [comment]
Can u please provide the test case file

**Comment by tanayag** [comment]
@harsh-2711 check PR #13966

**Comment by anubhavsinha98** [comment]
Hey is this issue still pending?

**Comment by llucifer97** [comment]
Hi, @gxyd I would like to take up this issue,if its still open.

**Comment by ajjayymahato** [comment]
Is this issue still open? If yes then I would like to take up this issue.

**Comment by gsteja025** [comment]
@gxyd i would like to take this issue if still open

**Comment by czgdp1807** [comment]
This issue can only be fixed after https://github.com/sympy/sympy/issues/13984 is fixed.

**Comment by SanjayMarreddi** [comment]
@gxyd Hello, Is this Issue still Open ? I would like to take it up !!

Thanks

**Comment by ayushbisht2001** [comment]
hi @gxyd  , I would like to take this issue if it is still open.

**Comment by sgautham2k** [comment]
Hi, I would like to work on this issue. How do I get started with it?

**Comment by fauzank339** [comment]
Hi, is this issue still open?
I wish to get started in it.
I am new to open source so I would appreciate help.

**Comment by anutosh491** [comment]
> Hey, I would like to work on this issue. I am new to open source so this would be a great kick start for me.

I guess there is an issue related to this which has to be sorted out first before implementing this ! Maybe you could go through other easy to fix issues .

**Comment by SravaniRaniMishra** [comment]
i am new to open source and would love to take this issue as my first case

**Comment by sparkykingmode** [comment]
Hi all, is this issue still open? I'd like to try and fix it

**Comment by akhila1729** [comment]
Hii,
I would like to take up this issue if it is still open.

**Comment by Shikharishere** [comment]
I would like to contribute if this issue is still open??

**Comment by lincyii** [comment]
Hi, I would like to contribute if this issue is still open as my first try. :)

**Comment by TanmayAgarwal123** [comment]
I would love to work on this issue, can you assign me
Regards,
Tanmay Agarwal

**Comment by 1e9abhi1e10** [comment]
> I would love to work on this issue, can you assign me Regards, Tanmay Agarwal

You don't need to ask for a contribution. Just check first if there are any existing pull requests cross-referenced in the issue(as for this issue there are already 2 open pull requests)
