### ISSUE TITLE
linsolve() yields wrong solution

### ISSUE THREAD

**Issue by LAV42** [sympy/sympy#13891]
```
from sympy import *

alpha, a0, a1 = symbols('alpha, a0, a1')
unknowns = [a0, a1]
systeq = [a0 - a1*alpha**2/2 - a1 + alpha*(a0 - 3*a1/2 + 1) + 1, -a1*alpha**2/(alpha**2 + 2) + alpha*(-(1 - 2/(alpha**2 + 2))*(a0 - a1) + 2*(-a1/2 + 1)/(alpha**2 + 2)) + (1 - 2/(alpha**2 + 2))*(-a0 + a1 - 1)]

print('solve', solve(systeq, unknowns))
print('linsolve', linsolve(systeq, unknowns))
```

Will produce 
```
solve {a0: 1/(alpha + 1), a1: 2/(alpha + 1)}
linsolve {(-1, 0)}
```
It found that `linear_eq_to_matrix` produces the wrong matrix.
I think that the problem resides in the fact that expr.coeff() does not return the right value since the expression must be expanded first. Using 
`systeq = [expand(x) for x in systeq]`
solved the problem.

**Comment by moorepants** [comment]
I think a cleaner way to do this internal to this function would be to use the the Jacobian of the set of equations to extract the coefficients.

**Comment by Mohit17067** [comment]
I am not sure about it but it is working fine for me
```
alpha, a0, a1 = symbols('alpha, a0, a1')
unknowns = [a0, a1]
systeq = [a0 - a1*alpha**2/2 - a1 + alpha*(a0 - 3*a1/2 + 1) + 1, -a1*alpha**2/(alpha**2 + 2) + alpha*(-(1 - 2/(alpha**2 + 2))*(a0 - a1) + 2*(-a1/2 + 1)/(alpha**2 + 2)) + (1 - 2/(alpha**2 + 2))*(-a0 + a1 - 1)]
print('linsolve', linsolve(systeq, unknowns))
```
produces 
`linsolve {(1/(alpha + 1), 2/(alpha + 1))}`

**Comment by ishanaj** [comment]
@LAV42 The issue seems to have been fixed in the current dev version of Sympy. The changes would be reflected in the next release.

**Comment by bansalnitish** [comment]
May I work on this issue if it is still up !

**Comment by RISHAV98** [comment]
I would like to solve this issue..should  I proceed???
