### ISSUE TITLE
(-x/4 - S(1)/12)**x - 1 simplifies to an inequivalent expression

### ISSUE THREAD

**Issue by ethankward** [sympy/sympy#13890]
>>> from sympy import *
    >>> x = Symbol('x')
    >>> e = (-x/4 - S(1)/12)**x - 1
    >>> e
    (-x/4 - 1/12)**x - 1
    >>> f = simplify(e)
    >>> f
    12**(-x)*(-12**x + (-3*x - 1)**x)
    >>> a = S(9)/5
    >>> simplify(e.subs(x,a))
    -1 - 32*15**(1/5)*2**(2/5)/225
    >>> simplify(f.subs(x,a))
    -1 - 32*(-1)**(4/5)*60**(1/5)/225
    >>> N(e.subs(x,a))
    -1.32255049319339
    >>> N(f.subs(x,a))
    -0.739051169462523 - 0.189590423018741*I

**Comment by normalhuman** [comment]
The expressions really are equivalent, `simplify` is not to blame.  SymPy is acting strangely when raising negative rationals to the power of 9/5: depending on what that rational is, it sometimes decides the minus sign can be simply moved out.    
```
>>> (-S(1)/5)**(S(9)/5)
-(-1)**(4/5)*5**(1/5)/25    # complex number as a result, understandably
>>> (-S(4)/5)**(S(9)/5)
-8*2**(3/5)*5**(1/5)/25    # now it's real, just moved -1 outside for some reason
```

**Comment by ethankward** [comment]
OK, "inequivalent" was the wrong word. But is it reasonable to expect sympy to try to keep the same complex root choice through simplification?

**Comment by normalhuman** [comment]
Yes, I think there should be consistency there.  The issue is at the level of SymPy taking in an object like (-1)**(S(4)/5) and parsing it into an expression tree. The trees are formed in significantly different ways for different exponents: 
```
>>> for k in range(1, 5):
...     srepr((-4)**(S(k)/5))
'Pow(Integer(-4), Rational(1, 5))'    #  complex
'Pow(Integer(-4), Rational(2, 5))'    # complex 
'Mul(Integer(2), Pow(Integer(-2), Rational(1, 5)))'   # complex, factoring out 2 is okay
'Mul(Integer(2), Pow(Integer(2), Rational(3, 5)))'    # real, where did the minus sign go? 
```
