### ISSUE TITLE
Solving trigonometric equations that can be reduced to polynomial

### ISSUE THREAD

**Issue by normalhuman** [sympy/sympy#13899]
Wolfram Alpha can [solve 2 * cos(x) * cos(2*x) = 1](http://www.wolframalpha.com/input/?i=solve+2*cos(x)*cos(2*x)+%3D+1), but SymPy can't.
```
>>> from sympy import *
>>> x = symbols('x', real=True)
>>> solve(2*cos(x)*cos(2*x) - 1, x)
... long stack trace ending with PolynomialError: only univariate polynomials are allowed
```
Or, 
```
>>> solveset(2*cos(x)*cos(2*x) - 1, x)
... another stack trace, ending with ValueError: y should be independent of x
```

Such equations can be rationalized by [tangent half-angle substitution](https://en.wikipedia.org/wiki/Tangent_half-angle_substitution) and passed to polynomial roots; this is apparently  what WolframAlpha does.  SymPy can do it too, if someone guides it step by step [as I did here](https://stackoverflow.com/a/48216793); but this ought to be automatic.

**Comment by jashan498** [comment]
I am on it :+1:

**Comment by normalhuman** [comment]
Fair warning: this is hard. SymPy has two solvers, `solve` (old, powerful, complicated, some might say messy) and `solveset` (new, clean, not yet as powerful but is supposed to be the future). I recommend working with `solveset`. Begin by studying its [`_solve_trig` helper](https://github.com/sympy/sympy/blob/master/sympy/solvers/solveset.py#L417), which is pretty short. At present it tries to rewrite things in terms of exp. This sometimes works, but other times (like in the above example) it obviously doesn't. 

The first goal would be to not throw that exception.
