### ISSUE TITLE
[FEATURE REQUEST] integer_log

### ISSUE THREAD

**Issue by smichr** [sympy/sympy#13908]
In a recent PR #13844, the following function may have been useful.

```python
def integer_log(y, x):
    """Returns (e, bool) where e is the largest nonnegative integer
    such that y >= x**e and bool is True if y == x**e"""
    assert x > 1
    y = as_int(y)
    x = as_int(x)
    if x == 2:
        e = y.bit_length() - 1
        return e, 2**e == y
    r = e = 0
    while y >= x:
        d = x
        m = 1
        while y >= d:
            y, r = divmod(y, d)
            e += m
            if y > d:
                d *= d
                m *= 2
    return e, y == 1 and r == 0
```
As tested in the following, it is much faster than `int(log(y, x))`

```
def go(n, b):
    a = [randint(1, 2**123) for i in range(n)]
    b = [randint(2, b) for i in range(n)]
    v1 = []
    t = time()
    for i in range(n):
        v1.append(int(log(a[i], b[i])))
    intlog = time() - t
    v2 = []
    t = time()
    for i in range(n):
        v2.append(integer_log(a[i], b[i]))
    this = time()-t
    for i in range(n):
        try:
            assert v1[i] == v2[i][0]
        except:
            print(a[i], b[i])
            print(v1[i], v2[i])
            return
    return this/intlog
>>> go(100, 42)
0.0016...
```

This fills in a gap left by 
* `multiplicity` - what is the power of x in y?
* `perfect_power` - can y be written as x**e?
* `integer_nthroot` - what is the largest integer x <= y**(1/n)?
* `is_square` - is x a square number

**Comment by smichr** [comment]
ping @Yathartha22

**Comment by ylemkimon** [comment]
It seems it's faster than CPython's log implementation, `math.log`.

**Comment by vishalg2235** [comment]
@smichr should I add this feature?

**Comment by Yathartha22** [comment]
Looks good @smichr  but could you enlighten me a bit on the logic by which `integer_log` solves for x>2.

**Comment by ArighnaIITG** [comment]
I have submitted PR #13911 based on this issue.

**Comment by smichr** [comment]
> logic by which integer_log solves for x>2

Do you mean how does it do it or why does it exclude x == 1? I'll assume you mean x == 1 because that's the shorter answer. If x == 1 we are looking for `1**e = y` for which there is only the trivial case when y == 1 (in which case e == 1). But this is ambiguous with the case for when y = 1 for which `x**0` is the solution (hence e == 0). So log(1, 1) could be 0 or 1 -- so base 1 is excluded as it is not single valued. There are more mathematical [answers here](https://math.stackexchange.com/questions/413713/log-base-1-of-1) and SymPy gives zoo for log(3, 1).

**Comment by smichr** [comment]
If you actually mean that you want the code explained, this is basically greedy base extraction using exponents of the base that are powers of two to quickly remove large multiples of the base. So for `integer_log(1800, 3)` we test remove 3 and are left with 600; remove 9 and are left with 66 and a total three 3s extracted so far. The next power to test would be 81 which is too large so we start over, extracting 3 from 33 to leave 22, then 9 from that to leave 2 which is less than 3 so we are done and have extracted six 3s. The process ended at 2 so it wasn't an exact extraction.

Let's compare this with the `digits` function results:

```
>>> from sympy.ntheory.factor_ import digits
>>> digits(1800, 3)
[3, 2, 1, 1, 0, 2, 0, 0]
```
The first element is the base and the remaining digits the number of powers. So 1800 is `2*3**6 + 3**5 + 3**4 + 2*3**2`...the leading power of 3 is `3**6` and that is the 6 that we found.

**Comment by Yathartha22** [comment]
One thing, consider

```
>>> integer_log(-8, 2)
(3, True)    # which is ok

>>> integer_log(4, -2)
# gives nothing
```
@smichr for the second case I think it should be `2`, because 4 can be expressed as (-2)**2 in terms of -2.

**Comment by Yathartha22** [comment]
The above code would give

```
>>> integer_log(27, 5)
(2, True)
```
which is wrong, the last return statement should be something like `x**e == orig_y`.

**Comment by smichr** [comment]
@Yathartha22 , good catch...how about 

```python
def integer_log(y, x):
    """Returns (e, bool) where e is the largest nonnegative integer
    such that |y| >= |x**e| and bool is True if y == x**e"""
    if x in (-2, 2):
        x = int(x)
        y = as_int(y)
        e = y.bit_length() - 1
        return e, x**e == y
    if x < 0:
        n, b = integer_log(y if y > 0 else -y, -x)
        return n, b and (n % 2 if y < 0 else not n % 2)
    x = as_int(x)
    y = as_int(y)
    assert x > 1
    assert y > 0
    r = e = 0
    while y >= x:
        d = x
        m = 1
        while y >= d:
            y, rem = divmod(y, d)
            r = r or rem
            e += m
            if y > d:
                d *= d
                m *= 2
    return e, r == 0 and y == 1

assert integer_log(27, 5) == (2, False)
assert integer_log(1, 2) == (0, True)
assert integer_log(1, 3) == (0, True)
assert integer_log(2, 3) == (0, False)
assert integer_log(3, 3) == (1, True)
assert integer_log(3*2, 3) == (1, False)
assert integer_log(3**2, 3) == (2, True)
assert integer_log(3*4, 3) == (2, False)
assert integer_log(3**3, 3) == (3, True)
assert integer_log(4, -2) == (2, True)
assert integer_log(-4, -2) == (2, False)
assert integer_log(8, -2) == (3, False)
assert integer_log(-8, -2) == (3, True)
assert integer_log(9, -3) == (2, True)
assert integer_log(-9, -3) == (2, False)
assert integer_log(27, -3) == (3, False)
assert integer_log(-27, -3) == (3, True)
```

**Comment by ArighnaIITG** [comment]
@smichr , I have implemented the above feature in my PR #13911 . 
And also added test cases.
Please review.

**Comment by Yathartha22** [comment]
This looks good @smichr I'll update.

**Comment by smichr** [comment]
I'll check back in a few hours.
