### ISSUE TITLE
The power of zoo

### ISSUE THREAD

**Issue by normalhuman** [sympy/sympy#13914]
`zoo` means complex infinity, the process of |z| -> oo as z varies in the complex plane. There is no base b other than 1 for which `b**z` has a limit as |z| -> oo. However this isn't recognized by SymPy:
```
>>> [b**zoo for b in [0, 1, -1, 2, -2, I, S.Half, -S.Half]]
[nan, nan, (-1)**zoo, 2**zoo, (-2)**zoo, I**zoo, (1/2)**zoo, (-1/2)**zoo]
```
`1**zoo` became nan in #8582, and recently (after 1.1.1) the same was done for `0**oo` although I couldn't locate the PR. But all of these should be `nan`; that is, `Pow(b, zoo)` should be `nan` regardless of `b`.

**Comment by vivonk** [comment]
Yes, it should. For this case, we can do like
`
- if a>1; a<sup>zoo</sup>=zoo , a<sup>-zoo</sup>=0
- if 0<a<1; a<sup>zoo</sup>=0, a<sup>-zoo</sup>=zoo
- if a<0; a<sup>zoo</sup>= undefined
`
But I don't know why you want to return nan for b>1 too.
I want to work on this issue, can you assign this to me?

**Comment by normalhuman** [comment]
You are thinking about positive infinity, oo. But zoo is complex infinity. And the base is in general complex too.  By default SymPy does not assume that the symbols are real.

**Comment by vivonk** [comment]
Sorry, I got it wrong. Thanks for the clarification.

**Comment by vivonk** [comment]
Yes, it should be `Nan`.
Can you assign to me? I want to work on this

**Comment by normalhuman** [comment]
We don't really assign issues here but you should feel free to work on it and submit a pull request.
