### ISSUE TITLE
Legendre polynomials should not rewrite "L_{-n}(x)  --->  L_{n-1}(x)"

### ISSUE THREAD

**Issue by normalhuman** [sympy/sympy#13916]
[Suggested 1st issue].  

The following should return the 3rd degree Legendre polynomial, `5*x**3/2 - 3*x/2`: 
```
from sympy import *; var('x k')
legendre(5 - k, x).subs(k, 2)
```
Instead, I get "ValueError: The index n must be nonnegative integer (got -4)". 

The culprit is a [strange rewriting rule](https://github.com/sympy/sympy/blob/97b7ec4949c4ecb9f6f4db65f4db96ef3b9e53a0/sympy/functions/special/polynomials.py#L789):
```
            # L_{-n}(x)  --->  L_{n-1}(x)
            if n.could_extract_minus_sign():
                return legendre(-n - S.One, x)
```
The function rewrites `legendre(5 - k, x)` as `legendre(k - 6, x)` (why?) and then complains that the value k-6 is negative. 

This rewriting rule should be removed and a test added to prevent it from reappearing.

**Comment by vivonk** [comment]
It is correct for n<sup>th</sup> order Legendre polynomial that 
L<sub>-n</sub>(x) = L<sub>n-1</sub>(x) .
It can be shown from 
[online calculator](http://keisan.casio.com/exec/system/1180573417) too that
the Legendre polynomial for -n is equivalent to the Legendre polynomial for n-1.

What this .subs(k,2) is doing ?

Another is if n is negative then why the code should produce `ValueError(
                    "The index n must be non-negative integer (got %r)" % n)`, instead it should give solution of `legendre(-n-1,x)`

I am interested in learning :smiley:, and in learning phase too.

**Comment by normalhuman** [comment]
`.subs(k, 2)` means substitute 2 for k. Replace k by 2. This is why the polynomial should become a polynomial of degree 3. 

Okay, I see now there is a convention to define [Legendre polynomials of negative order](http://functions.wolfram.com/Polynomials/LegendreP/02/). I didn't know about that, thanks for bringing it up. So let's keep the rewrite rule in place. But then, [this if-statement is wrong](https://github.com/sympy/sympy/blob/97b7ec4949c4ecb9f6f4db65f4db96ef3b9e53a0/sympy/functions/special/polynomials.py#L801). It should be:
```
            if n.is_negative:
                n = -n - S.One
```

This will allow the polynomial to evaluate.
