### ISSUE TITLE
sympy.S doesn't preserve numpy arrays of length 1, and unconditionally converts its member to float

### ISSUE THREAD

**Issue by nschloe** [sympy/sympy#13924]
When sympifying a numpy array of length 1, the array is unconditionally converted to a `float`
```python
import numpy
import sympy

sympy.S(numpy.array([1]))  # 1.0
sympy.S(numpy.array([1.0]))  # 1.0
sympy.S(numpy.array([sympy.S(1)]))   # 1.0
```
Compare this with arrays of any greater length
where data types and array structure are preserved:
```python
sympy.S(numpy.array([1, 1]))  # [1, 1]
sympy.S(numpy.array([1.0, 1.0]))  # [1.0, 1.0]
sympy.S(numpy.array([sympy.S(1), sympy.S(1)]))   # [1, 1]
```

This behavior leads other funny things like https://github.com/sympy/sympy/issues/13637:
```python
a = numpy.array([1])
b = sympy.S(1)
print(a*b)  # [1]
print(b*a)  # 1.00000000000000
```
(As @asmeurer explained before, in the product `b*a` the sympy number is the first factor so sympy takes care of the multiplication. The first thing it does then is that is sympifies the second factor, turning it into a `float`, which then gives the unexpected result.)

Perhaps one way to fix this is to disallow `float` on length-1 arrays in numpy.

**Comment by asmeurer** [comment]
This can be fixed by moving the code that tries to convert arrays above the code that tries `float` and `int` in `sympify`.

**Comment by nschloe** [comment]
Ah dang, @Shikhar1998 was working on it as well. Anyhow, feel free to merge #13926 or use whatever you came up with.
