### ISSUE TITLE
Link Geometry class names to their descriptions

### ISSUE THREAD

**Issue by normalhuman** [sympy/sympy#13936]
Real world use example: I open [Geometry module page](http://docs.sympy.org/dev/modules/geometry/index.html) and see that it has an entity I need (Segment). Yay. Except I can't click "Segment" to find what the parameters and methods are. These names should be clickable. 

Even if I scroll to the bottom, there's no link to Segment there. (By the way, why does the list on the bottom of that page has "Contains" as a separate item?)

**Comment by vivonk** [comment]
+1, this make easy to people as most of the people don't want to read whole documentation or iterate over whole page.

**Comment by gxyd** [comment]
For the contributor to this issue, we need to change \`Point\`  to :class:\`sympy.geometry.point.Point\`, similarly for other entities.

**Comment by gxyd** [comment]
@normalhuman I think "Contains" at the end of page should be removed?

**Comment by asrdav** [comment]
I am new here and I would like to try out to fix this issue.
