### ISSUE TITLE
Issue with sympy.poly function

### ISSUE THREAD

**Issue by michaelnowotny** [sympy/sympy#13944]
Dear SymPy developers,

I am experiencing an issue using the sympy.poly function when supplying an expression that is linear in the generating variable $x$ but has a denominator that involves a symbol, e.g. $expr = a * x / (1-b)$

Here is the Python code:
---------------------------
import sympy as sym
a, b = sym.symbols('a, b')
x = sym.Symbol('x')
sym.poly(a / (1 - b) * x , x)
---------------------------

The last line results in the error message
ValueError: can't raise polynomial to a negative power

However, the following two
---------------------------
sym.poly(a * x, x)
sym.poly(a / b * x , x)
---------------------------
work well.

It is not clear to me why having (1-b) in the denominator produces an error message while dividing by b works. I do not understand this behavior and think there might be a SymPy bug. Enlightenment is appreciated.

Michael

**Comment by coffe2code** [comment]
It doesn't give an error when i'm running it. The output is Poly(-a/(b - 1)*x, x, domain='ZZ(a,b)')

**Comment by michaelnowotny** [comment]
This is interesting. I am on Mac OS X High Sierra with Anaconda and SymPy version 1.1.1 and Python 3.6.4. I will have to try this on Linux. Which versions are you using?

**Comment by coffe2code** [comment]
I'm using ubuntu 16.04 with SymPy version 1.1.2dev. Before switching OS, try using 1.1.2dev

**Comment by asmeurer** [comment]
Indeed, it looks like this is broken in the 1.1.1 release, but it works in master. 

I bisected the fix to f6e72f83ecb6153b4f1e297a517e93d199e6b19c, which is from https://github.com/sympy/sympy/pull/13588. It looks like a suitable test was added in that PR.

**Comment by michaelnowotny** [comment]
It works for me in the dev version. Thank you for your help!
