### ISSUE TITLE
Add is_EmptySet for Interval

### ISSUE THREAD

**Issue by gxyd** [sympy/sympy#13956]
#### Reference to related PR's

See #11501 

#### What needs to be done?

Complete the PR #11501 . Addressing the comments left by @siefkenj would suffice I guess.
The contributor shouldn't forget to have `Fixes #11501 and Fixes #13956` in PR description.

**Comment by ArighnaIITG** [comment]
Can I work on this issue?
Do I have to create a PR on top of that PR?

**Comment by smichr** [comment]
per comment in closed PR, this appears to be implemented in master
