### ISSUE TITLE
Unusual Behavior with Circle CI Builds

### ISSUE THREAD

**Issue by Shikhar1998** [sympy/sympy#13967]
Recently, in PR #13955, #13966, #13934, #13938, #13710 I observed some unusual results with Circle CI.
In PR #13955, while running tests locally on `Prefixes` module an error was observed while running the same tests on `Circle CI` builds no error was recorded. 
A similar issue was also observed with PR #13710, in past.
To investigate repeated failing tests in PR's addressing the Issue #13881, I pulled the changes from PR #13966, #13934 &  #13938 and tried running them locally and got

![nothing](https://user-images.githubusercontent.com/13603266/35179649-69d8934c-fdc4-11e7-9951-9998d5d3abc9.PNG)

This seems pretty strange to me. I am currently running `sympy` on a `Windows` Platform, I am not sure if anyone can recreate these results on a `Linux` platform.

**Comment by ylemkimon** [comment]
What tests are you running on the CircleCI?

**Comment by Shikhar1998** [comment]
I am trying to understand the cases when `Circle CI` passes `tests` which must actually fail.

**Comment by ylemkimon** [comment]
What exact commands are you running on it?

**Comment by Shikhar1998** [comment]
Tests on these changes are passing `locally` but failing on `Circle CI`.

**Comment by ylemkimon** [comment]
Are you using `bin/test`, using `test` function from `sympy`, or running the tests directly by importing the test file?

**Comment by Shikhar1998** [comment]
I am using `bin/test`. Can you run these tests locally and verify:
1. For `sympy prefixes` module
2. and with changes in PR #13968

**Comment by ylemkimon** [comment]
SymPy tests are not fully compatible with `pytest`. For example, SymPy's test module imports `division` from `__future__` for all tests. There is some open issues regarding using `pytest` to test SymPy: #5641, #6817, #12927, #13062.

**Comment by ylemkimon** [comment]
But in this case, it seems it's not the problem with `pytest`, but rather with `lambdify`. On environments where `numpy` is not installed, lambdify uses `math`, `mpmath`, `sympy` modules for default and `f(Matrix([1, 2, 3]))` returns an array, `[14]`. On where `numpy` is installed, it uses `numpy`, and an Integer, `14` is returned.

**Comment by Shikhar1998** [comment]
Great!. Thanks for clarifying this. It had been bugging me for quite a while.
