### ISSUE TITLE
Add debugging messages to manualintegrate

### ISSUE THREAD

**Issue by normalhuman** [sympy/sympy#13987]
Some of the more complex algorithms in SymPy, such as Gruntz for limits and Meijer G for integrals, issue debugging messages. Examples from meijergint: 
```
from sympy.utilities.misc import debug
debug('Integrating', f, 'wrt %s from %s to %s.' % (x, a, b))
debug('Trying recursive Mellin transform method.')
debug('Try rewriting hyperbolics in terms of exp.')
```
These are shown if one uses `export SYMPY_DEBUG=True` before starting Python. I found them helpful in tracing integration issues, and I guess it's not just me.

I propose that manualintegrate.py should also issue `debug` messages when it attempts some transformation rule. It could be a message like 
```
debug("Trying to integrate {} by using {}".format(function, rule))
```
This way, when integration does something strange or goes into an infinite loop, we'll know where the problem is without tracing the different integration routines.

**Comment by abhayjindal51** [comment]
Hi @normalhuman ,
I would like to work on this issue.

**Comment by normalhuman** [comment]
Sure, go ahead. My guess is that a debug statement should be in [this function](https://github.com/sympy/sympy/blob/master/sympy/integrals/manualintegrate.py#L1196) where rule is the  rule being applied. Begin by inserting `print(rule)` in there to see how a printed rule looks like, what information it contains.

**Comment by ylemkimon** [comment]
Also it would be useful feature to show integration steps like SymPy Gamma(https://github.com/sympy/sympy_gamma/blob/master/app/logic/intsteps.py) and WolframAlpha.

**Comment by abhayjindal51** [comment]
I added the debugging messages. @ylemkimon could you please help me in getting started for showing integration steps

**Comment by normalhuman** [comment]
I don't think debugging messages need pretty recursive (hence resource-consuming) printing from intsteps. And it's probably not going to be available in the situations when we want to debug, because the process never finishes. The main issue with manualintegrate is going into infinite loops of rewriting the function.
