### ISSUE TITLE
Differential Equation [Part 4] URl broken

### ISSUE THREAD

**Issue by leesmith404** [sympy/sympy#13997]
Hi!  Thanks for putting this on the WEB.

I attempted to look at a tutorial for differential equations, but got a 404 error  ??

Do you know when this will be fixed?

Thanks in advance.

**Comment by normalhuman** [comment]
What is the broken link, and on what page? I don't see anything broken on http://docs.sympy.org/latest/tutorial/solvers.html#solving-differential-equations for example.

**Comment by normalhuman** [comment]
Closing this, pending a clarification of the issue.
