### ISSUE TITLE
Handle LaTeX parsing \matrix

### ISSUE THREAD

**Issue by bollwyvl** [sympy/sympy#14007]
Based on feedback on https://github.com/sympy/sympy/pull/13706#issuecomment-359944477, `\matrix` parsing should be added.

**Comment by asmeurer** [comment]
There are several ways to print matrices. We should try to support all of them.

**Comment by 8vasu** [comment]
@bollwyvl I have written this: https://github.com/sympy/sympy/pull/26098

@asmeurer I took your comment very seriously.
