### ISSUE TITLE
sqrt and other root functions should inherit from Function

### ISSUE THREAD

**Issue by normalhuman** [sympy/sympy#14000]
The functions sqrt, cbrt, root, and real_root, defined in `miscellaneous.py`, are plain Python functions, defined with `def sqrt(arg): ...` This is in contrast to all other mathematical SymPy functions, which inherit from class Function. As a result, one cannot use `sqrt(5.5, evaluate=False)` to create un-evaluated sqrt(5.5), the way it works with exp, log, and all others. 

Those functions should be rewritten, following the model used for other functions (see sympy.functions.elementary for many examples).

**Comment by Subhash-Saurabh** [comment]
@normalhuman If you are not currently working on this I would want to take this up.

**Comment by normalhuman** [comment]
Sure, go ahead.

**Comment by skirpichev** [comment]
> This is in contrast to all other mathematical SymPy functions, which inherit from class Function.

Which is not necessary a bad thing.

> As a result, one cannot use sqrt(5.5, evaluate=False) to create un-evaluated sqrt(5.5)

That's an example of a real issue, easy to fix from my point of view.  No need to introduce new classes for this, unevaluated Pow instance should be fine.

**Comment by asmeurer** [comment]
I also am not sure this should be done. We actually want to remove the separate redundant `exp` class https://github.com/sympy/sympy/issues/4898.  The problem with having separate classes is you lose the ability to work with Pow objects uniformly. Code that should work with any Pow may not work properly with sqrt (although to be sure if `sqrt` subclasses from `Pow`, any correct code for `Pow` should work for `sqrt` by Liskov).

**Comment by normalhuman** [comment]
Okay, let's amend the issue as "sqrt and other roots should support `evaluate` flag. @Subhash-Saurabh
