### ISSUE TITLE
Failed coercion of an expression with E and exp to a field element

### ISSUE THREAD

**Issue by normalhuman** [sympy/sympy#14027]
```
var('x')
f = 1/(1 + exp(x - S(1)/2)/(1 + exp(x)))
integrate(f, x)
```
throws 
> sympy.polys.polyerrors.CoercionFailed: can't convert 1/(1 + E + 2*exp(1/2)) of type <class 'sympy.core.power.Pow'> to ZZ(exp(1/2))

This is the same kind of an issue that #13970 dealt with, apparently there is more to be done.

**Comment by vivonk** [comment]
@normalhuman  I tried on the sympy 1.0 which is on [live](http://live.sympy.org) console of sympy and that was not throwing an error for this particular expression

**Comment by normalhuman** [comment]
That's interesting, thanks. SymPy 1.1.1 throws that exception, however, as does the current master branch.

**Comment by normalhuman** [comment]
The immediate reason for failure, inability to coerce E to a field element, is easy to fix:
```diff
diff --git a/sympy/polys/fields.py b/sympy/polys/fields.py
index 9f9fdb4..9338be5 100644
--- a/sympy/polys/fields.py
+++ b/sympy/polys/fields.py
@@ -7,6 +7,8 @@
 from sympy.core.compatibility import is_sequence, reduce, string_types
 from sympy.core.expr import Expr
 from sympy.core.mod import Mod
+from sympy.core.numbers import Exp1
+from sympy.core.singleton import S
 from sympy.core.symbol import Symbol
 from sympy.core.sympify import CantSympify, sympify
 from sympy.functions.elementary.exponential import ExpBase
@@ -218,7 +220,7 @@ def _rebuild(expr):
                 return reduce(add, list(map(_rebuild, expr.args)))
             elif expr.is_Mul:
                 return reduce(mul, list(map(_rebuild, expr.args)))
-            elif expr.is_Pow or isinstance(expr, ExpBase):
+            elif expr.is_Pow or isinstance(expr, (ExpBase, Exp1)):
                 b, e = expr.as_base_exp()
                 # look for bg**eg whose integer power may be b**e
                 choices = tuple((gen, bg, eg) for gen, (bg, eg) in powers
@@ -226,8 +228,8 @@ def _rebuild(expr):
                 if choices:
                     gen, bg, eg = choices[0]
                     return mapping.get(gen)**(e/eg)
-                elif e.is_Integer:
-                    return _rebuild(expr.base)**int(expr.exp)
+                elif e.is_Integer and e is not S.One:
+                    return _rebuild(b)**e
``` 
So, now E is understood to be an element of Z(exp(1/2)). However, there is another error, coming from     `gmpy_gcd(a, b)` getting Integer types instead of expected 'mpz' type, and I don't see why that is happening.

**Comment by normalhuman** [comment]
Turned out to be a bug that I introduced myself when fixing  #13970, not understanding why the code had `int` in the exponent. It's there because otherwise Integer type coerces mpz to Integer, and stuff breaks apart in gmpy methods. Fixing...
