### ISSUE TITLE
Latex output of vector error

### ISSUE THREAD

**Issue by VirtualAcoustics** [sympy/sympy#14041]
The latex output drops the B.x parenthesis squared in a vector expression i.e. L*(phi' + theta')**2*B.x. 
See code,
```python
import sympy as sp
import sympy.physics.mechanics as me


N_frame = me.ReferenceFrame('N')
A_frame = me.ReferenceFrame('A')
B_frame = me.ReferenceFrame('B')

R_length = sp.symbols('R')
L_length = sp.symbols('L')

theta, phi  = me.dynamicsymbols('theta, phi')
thetad, phid  = me.dynamicsymbols('theta, phi', 1)
t = sp.Symbol('t')

A_frame.orient(N_frame, 'Axis', (theta, N_frame.z))
B_frame.orient(A_frame, 'Axis', (phi, A_frame.z))

O_point = me.Point('O')
O_point.set_vel(N_frame, 0)

O_point = me.Point('O')
O_point.set_vel(N_frame, 0)

Q_point = O_point.locatenew('A', R_length*A_frame.x)
P_point = Q_point.locatenew('B', L_length*B_frame.x)

r = P_point.pos_from(O_point)
print(r)
r_dot = r.diff(t,N_frame).simplify()
print(r_dot)
print(sp.latex(r_dot))
r_ddot = r_dot.diff(t,N_frame).simplify()

# These two should be the same, r_ddot is correct:
print(r_ddot)
print(sp.latex(r_ddot))
```

**Comment by h-ranjan1110** [comment]
Can I work on this? Do you have any suggestion for me, I am a beginner.

**Comment by h-ranjan1110** [comment]
This is the output of print(sp.latex(r_ddot))  :

-  L \dot{\phi} + \dot{\theta}^{2}\mathbf{\hat{b}_x} + L \left(\ddot{\phi} + \ddot{\theta}\right)\mathbf{\hat{b}_y} -  R \dot{\theta}^{2}\mathbf{\hat{a}_x} + R \ddot{\theta}\mathbf{\hat{a}_y}

But it should be --

-  L \left(\dot{\phi} + \dot{\theta}\right)^{2}\mathbf{\hat{b}_x} + L \left(\ddot{\phi} + \ddot{\theta}\right)\mathbf{\hat{b}_y} -  R \dot{\theta}^{2}\mathbf{\hat{a}_x} + R \ddot{\theta}\mathbf{\hat{a}_y}

somehow these are missing left and right brackets. @moorepants it would be great if you could guide me as to where should I start?

**Comment by moorepants** [comment]
Go for it!

**Comment by rahulgo** [comment]
@moorepants 
I've been trying to read through the latex module, in particular the _print_Mul function. I'm having some difficulty isolating the code that causes the bug. Could you give me some pointers?

**Comment by moorepants** [comment]
Latex printing code for physics vectors is here: https://github.com/sympy/sympy/blob/master/sympy/physics/vector/vector.py#L216

**Comment by jashan498** [comment]
@rahulgo in the term `-L*(Derivative(phi(t), t) + Derivative(theta(t), t))**2` args[1] (which is `(Derivative(phi(t), t) + Derivative(theta(t), t))**2`) gets converted to `\dot{\phi} + \dot{\theta}^{2}`, which is a completely different term, for some reason [here](https://github.com/sympy/sympy/blob/c05c2755fec78ff19af89a4599f76edb2ee104af/sympy/printing/latex.py#L423).  
I think you should also have a look at [_print_Pow](https://github.com/sympy/sympy/blob/c05c2755fec78ff19af89a4599f76edb2ee104af/sympy/printing/latex.py#L489) too as printing of `args[1]` takes place in that function.
