### ISSUE TITLE
Extract common codes from printers

### ISSUE THREAD

**Issue by ylemkimon** [sympy/sympy#14044]
(i) Printers have similar methods to print similar functions. For example, `_print_Min` and `_print_Max` in `LaTeXPrinter` have the exact same codes except the function name:
https://github.com/sympy/sympy/blob/5fcbde2ed7385df250510bd5207f270cba990265/sympy/printing/latex.py#L813-L831
This can be simplified to:
```python
def _hprint_variadic_function(self, expr, exp=None): 
    args = sorted(expr.args, key=default_sort_key) 
    texargs = [r"%s" % self._print(symbol) for symbol in args] 
    tex = r"%s\left(%s\right)" % (self._print(expr.func), ", ".join(texargs))
 
    if exp is not None: 
        return r"%s^{%s}" % (tex, exp) 
    else: 
        return tex 

_print_Min = _print_Max \
    = _hprint_variadic_function
```

(ii) Printers have different methods of printing the name of the function used and the function class. For example, in `LaTeXPrinter`, `gamma` function class is printed using:
https://github.com/sympy/sympy/blob/5fcbde2ed7385df250510bd5207f270cba990265/sympy/printing/latex.py#L794-L798
whereas the name of `gamma` is hard coded in `_print_gamma`:
https://github.com/sympy/sympy/blob/5fcbde2ed7385df250510bd5207f270cba990265/sympy/printing/latex.py#L984-L990
The latter can be changed to:
```python
def _hprint_one_args_func(self, expr, exp=None):
    tex = r"\left(%s\right)" % self._print(expr.args[0])

    if exp is not None:
        return r"%s^{%s}%s" % (self._print(expr.func), exp, tex)
    else:
        return r"%s%s" % (self._print(expr.func), tex)
```

**Comment by jashan498** [comment]
@ylemkimon should I change this or this issue is meant to be someones starter issue?

**Comment by ylemkimon** [comment]
@jashan498 You can `\min` and `\max` to the `_special_function_classes`.

**Comment by h-ranjan1110** [comment]
@jashan498  are you working on this?

**Comment by jashan498** [comment]
Oh, I forgot about this issue. @h-ranjan1110 you can surely take this up : )

**Comment by h-ranjan1110** [comment]
@ylemkimon  can you please elaborate more on this issue moreover it would be great if you could guide where to start as I am a beginner, I have tried to understand those codes in latex.py.

**Comment by rahilhastu** [comment]
can I work on this issue? like @h-ranjan1110 I am also a beginner

**Comment by h-ranjan1110** [comment]
Yeah , go on.

**Comment by andyy143** [comment]
may i be assigned this issue

**Comment by gxyd** [comment]
@andyy143 there already is a PR open fixing this issue.

Also in sympy we don't 'assign' issues, you can just comment stating that you intend to work on it, and we'll let you know in case you're not sure if a PR is open.

**Comment by rtindru** [comment]
@gxyd Is someone actively working on this issue? If not, I'd love to contribute here.
