### ISSUE TITLE
erf in lambdify with NumPy discards the imaginary part of its argument

### ISSUE THREAD

**Issue by normalhuman** [sympy/sympy#14050]
I tried to lambdify `erf(x+I)` using NumPy as a backend:
```
from sympy import *
var('x')
f = lambdify(x, erf(x+I), "numpy")
```
Now `f(0.5)` returns 
> :1: ComplexWarning: Casting complex values to real discards the imaginary part
> 0.5204998778130465

Indeed, this value is `erf(0.5)`, not `erf(0.5+I)`. 

**The following is incorrect**, kept only for context. 

I understand that NumPy doesn't have own erf implementation, and `pycode` ends up using `scipy.special.erf`. But that function is capable of handling complex values:
```
>>> from scipy import special
>>> special.erf(0.5 + 1j)
(1.2048475583142182+1.024400881608446j)
```
So I don't see where exactly the issue is. For example, `f = lambdify(x, sin(x+I), "numpy")` works fine.

**Comment by normalhuman** [comment]
Turned out, `erf` is imported from `math`, not from `scipy.special`. And `math.erf` does not support complex arguments, hence the problem.

**Comment by jashan498** [comment]
@normalhuman  is there harm in using `special.scipy` for `NumPyPrinter` too? I see that both `_not_in_numpy` and `_known_functions_scipy_special` have same functions.

**Comment by normalhuman** [comment]
I think the concern with that is that a user may have NumPy but not SciPy.

**Comment by bjodah** [comment]
we could make the default module of lambdify be 'scipy'

**Comment by normalhuman** [comment]
As far as I know, lambdify does not support scipy at all: #7229

**Comment by jashan498** [comment]
can we use one from `sympy.functions.special.error_functions` ?

**Comment by normalhuman** [comment]
The idea of lambdify is to create a Python function for efficient numeric evaluation (as opposed to `expr.subs(x, value)`). Not using SymPy is the goal here. Besides, SymPy does not do any numeric evaluation itself, it relies on mpmath for that. 

If mpmath is used as the backend, `f = lambdify(x, erf(x+I), "mpmath")`, then evaluation works. But I wouldn't consider this an option when the backend is specified as NumPy, because mpmath objects and NumPy don't mix.
