### ISSUE TITLE
The method _intervals of a Piecewise expression sometimes incorrectly replaces default

### ISSUE THREAD

**Issue by normalhuman** [sympy/sympy#14052]
I noticed that `integrate(abs(sin(x)), (x, 0, 2*pi))` returns 0 and tried to investigate. It's rewritten as Piecewise, which is then piecewise_integrated to 
```
Piecewise((-cos(x), sin(x) >= 0), (cos(x), True))
```
So far so good; this piecewise is not expected to be continuous. Then it gets processed by the method `_intervals` of Piecewise, where something goes wrong: 
```
>>> x = symbols('x')
>>> Piecewise((-cos(x), sin(x) >= 0), (cos(x), True))._intervals(x)
[(2*pi, 2*pi, -1, 0), (0, pi, -cos(x), 0), (-oo, oo, -cos(x), 1)]
```
The last tuple is wrong: the default `cos(x)` got replaced by `-cos(x)`, which of course will make the integral 0. As far as I can tell, the issue is that [line 778](https://github.com/sympy/sympy/blob/master/sympy/functions/elementary/piecewise.py#L778), with 
```
                if cond is S.true:
                    default = expr
```
is preceded by `cond = cond.subs(sym, lower)`. So, if a condition is true at one point "lower", it's as if it is always true, and the corresponding expression becomes the default.  

This seems wrong to me, but I ran out of energy before having understood this method, so posting this for now.

**Comment by smichr** [comment]
> before having understood this method

I think the misunderstanding --probably mine -- was in confusing an And condition that is true for a given equality with a conditionless-True condition. The latter signifies the default in a list of expr, cond piecewise args. The former just means that the condition can be replaced by the equality.
