### ISSUE TITLE
Issue with complex symbolic exponentials

### ISSUE THREAD

**Issue by anoop-r-kulkarni** [sympy/sympy#14057]
Hi,

I define the following

```
from sympy import *
x=symbols("x",real=True)

f=(1+exp(I*x))**2
print(re(f))

Output:
(cos(x) + 1)**2 - sin(x)**2
```
whereas it should be (cos(x) + 1)**2 **+** sin(x)**2

The issue is clearly related to "I" in the expression and expansion of square term. Am I doing it wrong or is there a workaround?

Thanks and regards
~anoop

**Comment by ylemkimon** [comment]
The result seems to be correct. ([WolframAlpha](http://www.wolframalpha.com/input/?i=re((1%2Bexp(I*x))**2)))

**Comment by mithlesh4257** [comment]
Yes @ylemkimon, you are right. We will be getting **(cos(x)+1)**2 - **sin(x)**2** for above given 
**f = (1+exp(I*x))**2**.

**Comment by anoop-r-kulkarni** [comment]
thanks folks. seems right.
