### ISSUE TITLE
series(cos(x), x, pi, 3) does not display correctly

### ISSUE THREAD

**Issue by Roland-Sands** [sympy/sympy#14056]
`>>> series(cos(x), x, pi, 3) `
`-1 + (x - pi)**2/2 + O((x - pi)**3, (x, pi))`

**Comment by ylemkimon** [comment]
The result seems to be correct. ([WolframAlpha](http://www.wolframalpha.com/input/?i=expand+cos(x)+at+x%3Dpi))

**Comment by Roland-Sands** [comment]
It should display
`-1 + (x - pi)**2/2 + O((x - pi)**3)`
not
`-1 + (x - pi)**2/2 + O((x - pi)**3, (x, pi))`

When I saw this with nicer printing (was in SymPy live?) the extraneous bit at the end was x arrow pi,

**Comment by normalhuman** [comment]
Regarding calligraphic: [Wikipedia says](https://en.wikipedia.org/wiki/Big_O_notation#Typesetting): "commonly used calligraphic variants, like`\mathcal {O}`, are available, in LaTeX and derived typesetting systems."

**Comment by asmeurer** [comment]
`O((x - pi)**3)` would be incorrect. `O` without a second argument defaults to the order at 0. 

If you want nice printing you should use `pprint` or `latex`. The `str` printer does try to be readable, but the primary use of it is to produce a recreatable form of the expression. Therefore it always uses valid Python, using the syntax used to create the objects in the expression. 

```
>>> pprint(series(cos(x), x, pi, 3))
            2
     (x - π)     ⎛       3       ⎞
-1 + ──────── + O⎝(x - π) ; x → π⎠
        2
```

Regarding the calligraphy O, it is used sometimes (see for instance the logo on the right at https://en.wikipedia.org/wiki/Big_O_notation). However, I agree that usually it isn't, and I would support removing that.

**Comment by Roland-Sands** [comment]
If `O(x**3)` is correct then I just don't understand how `O((x - pi)**3)` can be incorrect
Then again, I am a novice in this area

**Comment by gxyd** [comment]
Hmm.. I can see that atleast Axiom doesn't use it:
```
(1) -> series(sin(x),x = %pi)

   (1)
                   1          3    1           5     1           7
     - (x - %pi) + - (x - %pi)  - --- (x - %pi)  + ---- (x - %pi)
                   6              120              5040
   + 
          1            9       1             11              12
     - ------ (x - %pi)  + -------- (x - %pi)   + O((x - %pi)  )
       362880              39916800
                     Type: UnivariatePuiseuxSeries(Expression(Integer),x,%pi)
```

So in Axiom is it supposed to be obvious from `O((x - %pi)^12)` that we are referring to `O` as `x -> 12`? Do other CAS's have support for sympy's equivalent of `O(x - pi, (x, 0))`?

**Comment by Roland-Sands** [comment]
Should I close this

**Comment by gxyd** [comment]
I think we can close this. But I agree here with Aaron on typesetting of big-O https://en.wikipedia.org/wiki/Big_O_notation#Typesetting . I think we can create a new issue for that.

**Comment by gxyd** [comment]
I opened issue https://github.com/sympy/sympy/issues/14163 for typesetting. This can be closed now.

**Comment by Roland-Sands** [comment]
ylemkimon gave a link to Wolfram alpha, and Wolfram alpha doesn't display it SymPy style
SymPy's notation here is most certainly at odds with standard mathematical practice
