### ISSUE TITLE
Sum(1/(2*n+1)**2, (n, 0, oo)).doit() doesn't simplify

### ISSUE THREAD

**Issue by Roland-Sands** [sympy/sympy#14055]
The sum is pi**2/8

`>>> a = Sum(1/(2*n+1)**2, (n, 0, oo)).doit()`
`>>> simplify(a)`
`-polylog(2, exp_polar(I*pi))/2 + pi**2/12`

**Comment by ylemkimon** [comment]
-polylog(2, exp_polar(I*pi))/2 == pi**2/24
