### ISSUE TITLE
_eval_nseries of Mul is defective

### ISSUE THREAD

**Issue by jksuom** [sympy/sympy#14068]
The series expansion of a product is computed as the product of expansions of the factors.

    def _eval_nseries(self, x, n, logx):
        from sympy import Order, powsimp
        terms = [t.nseries(x, n=n, logx=logx) for t in self.args]
        res = powsimp(self.func(*terms).expand(), combine='exp', deep=True)
        if res.has(Order):
            res += Order(x**n, x)
        return res

This is correct if the leading term of each series is constant but not in general.

For example, to compute the expansion of `f(x)/x**10` at `x = 0` to order `O(x**10)` it is necessary to compute the series of `f(x)` to order `O(x**20)`, the order `O(x**10)` does not suffice.

A working strategy could be the following.

- Compute the order `n0` of the leading term of the product as the sum of the orders of the leading terms of the factors.

- For each factor, compute `n - n0` terms of its series expansion (starting from its leading term of order `n1` and ending at order `n - n0 + n1`).

- Multiply the expansions (truncating at terms of order `n`).

**Comment by RavicharanN** [comment]
@jksuom Can I take this up?

**Comment by jksuom** [comment]
Yes, of course.

**Comment by sachin-4099** [comment]
I will take this up and come up with a PR soon.
