### ISSUE TITLE
latex(Equivalent) should use \Leftrightarrow

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#14099]
Currently `latex(Equivalent)` uses `\equiv` (≡)

```
>>> latex(Equivalent(x, y))
'x \\equiv y'
```

a much better symbol is `\Leftrightarrow`. `\equiv` generally means "identically equal", whereas `\Leftrightarrow` is more often used for "logically equivalent" (which is what `Equivalent` represents).

**Comment by SaiSakethAluru** [comment]
Hi, I would like to work on it.

**Comment by normalhuman** [comment]
Would `\iff` be an even better representation of "logically equivalent", considering its name? (The appearance is similar to `\Leftrightarrow`).

**Comment by asmeurer** [comment]
\iff seems to have less support (at least it wasn't working in Gitter, meaning KaTeX doesn't support it).

**Comment by SaiSakethAluru** [comment]
Do we need to change anything for the not equivalent printing also? Also can someone guide me as to how to update the test file as well?

**Comment by asmeurer** [comment]
Yes, they should both use `\Leftrightarrow`. 

For the tests, just change the instances of `\equiv` with `\Leftrightarrow` in the `test_latex.py` file. You can check it with `./bin/test latex`.

**Comment by SaiSakethAluru** [comment]
Thank you. I have made the required changes in PR #14102. please review.
