### ISSUE TITLE
Consider removing automatic log expansion

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#14095]
Right now `log` automatically expands rational numbers:

```
>>> log(Rational(3, 2))
-log(2) + log(3)
```

I think this is a bit too much for automatic simplification (https://github.com/sympy/sympy/wiki/Automatic-Simplification). 

See also the discussion at https://github.com/sympy/sympy/issues/5950.

**Comment by jksuom** [comment]
It would like to hear why this was originally implemented this way. If there is no particular reason, I am +1 for removal.

**Comment by abaokar-07** [comment]
@jksuom @asmeurer can you suggest how this should be done?

**Comment by asmeurer** [comment]
I think @smichr was the one who implemented it. 

@abaokar-07 removing it from the constructor should be easy enough. The hard part with changes like these is figuring out various test failures, because code came to rely on the automatic simplification, and it has to be modified (I haven't tried it yet, so I don't know how many test failures there will be, it could be easy or it could be hard).

**Comment by abaokar-07** [comment]
@asmeurer okay, I'll try
BTW what constructor are you talking about?

**Comment by smichr** [comment]
> I think @smichr was the one who implemented it.

I made changes around that area with #1827 but the code `elif arg.is_Rational and arg.q != 1:` predated that change. 

Part of the issue that may arise is that expressions like `log(2/3) - log(1/3)` will not simplify to `log(2)`  -- `expand_log` will have to be used. Maybe that's not too bad. The extraction of perfect powers will also need to be applied to the numerator and denominator, too. (`sqrt(28)` automatically simplifies to `2*sqrt(7)` so if that remains, it's reasonable to expect that powers would be extracted from the `log`.)

**Comment by asmeurer** [comment]
I'm curious to see how many tests fail. 

I think a single log is quite often very preferable to a sum or even a product. Since it's a single term, it's technically simpler (smaller), and much easier to deal with in expressions. Consider for instance that an addition might expand over other additions (like `log(3/4)*(x + y)`). Obviously you sometimes do want it expanded, but with no automatic evaluation you can have it whichever way you prefer.  

`log(2/3) - log(3/2)` isn't a particularly obvious simplification. I don't see why it should happen automatically (it's no more obvious than `(2*x + 2*y)/(x + y)` or even `(x - y)/(y - x)`, which don't simplify automatically either). As I wrote on the wiki page, the automatic simplifications should only be things that are very fast and almost never unwanted. It should also actually make the expression simpler. I think expanding rationals fails all three counts (the speed is debatable, but factoring or pulling out powers could be slow).

Was the squarefree thing reverted? `log(9)` and `log(18)` both remain as-is for me.

**Comment by abaokar-07** [comment]
@asmeurer @smichr  The line number 529 of the file sympy/functions/elementary/exponential.py is :
`return cls(arg.p) - cls(arg.q)`
If we change it to `return cls(Rational(arg.p,arg.q), evaluate=False)` , then it is not doing the simplification.
If the input is given as `log(Rational(3,2))` the the output is coming out to be log(3/2)

**Comment by jksuom** [comment]
It is not necessary to change the return line. It will suffice to remove those lines altogether as indicated by @smichr in his [comment](https://github.com/sympy/sympy/issues/5950#issuecomment-362839107). If an argument `arg` does not satisfies any of the conditions, the code will run to the end and return `None`. This return value will imply that `log(arg)` be used as such with no modifications. That will be the case with `arg = Rational(3, 2)` if the lines are removed.

**Comment by jksuom** [comment]
> I removed those lines and it didn't do automatic simplification

What did you get?

**Comment by abaokar-07** [comment]
I gave the input as log(Rational(3,2)) and I got the output as log(3/2)

**Comment by jksuom** [comment]
I think that is what was to be expected if we do not want `log(3) - log(2)`.

**Comment by abaokar-07** [comment]
But since we have removed the lines which tell what to do when rational argument is encountered, how will logarithm know what to return? But still it is returning the expected answer

**Comment by jksuom** [comment]
`.eval()` is called by `Application.__new__`, and if it returns `None`, then a new instance of the given class (`log`) with given argument(s) (`Rational(3, 2)`) is [created](https://github.com/sympy/sympy/blob/master/sympy/core/function.py#L254). This is the default behaviour.

**Comment by abaokar-07** [comment]
@jksuom So after removing the lines in [comment](https://github.com/sympy/sympy/issues/5950#issuecomment-362839107), will the problem be solved, except for if the tests fail?

**Comment by jksuom** [comment]
It will probably be solved if not too many tests fail (and those that fail can be reasonably fixed).

**Comment by abaokar-07** [comment]
@jksuom Shall I open a pull request with those lines removed?

**Comment by asmeurer** [comment]
I would start by running the tests locally (./bin/test), and reporting here what fails.

**Comment by abaokar-07** [comment]
@asmeurer @jksuom sorry that I am asking this again, but after we have made the changes, how to run the tests?
Actually I thought that I got that yesterday, but still I am unclear how to do it

**Comment by abaokar-07** [comment]
I've got it

**Comment by abaokar-07** [comment]
@asmeurer @jksuom I ran the test `(./bin/test)`. Shall I report the file names which in which "FAIL" was returned?

**Comment by abaokar-07** [comment]
@asmeurer @jksuom  Shall I report?

**Comment by jksuom** [comment]
How many failing tests were there?

**Comment by abaokar-07** [comment]
@jksuom 13 tests failed, 346 expected to fail, 12 expected to fail but pass and 12 exceptions were found

**Comment by jksuom** [comment]
Can you copy the lines where the 13 failures are reported?

**Comment by abaokar-07** [comment]
@jksuom yeah sure, here goes:
1. sympy\codegen\tests\test_cfunctions.py:test_log1p
2. sympy\core\tests\test_evalf.py:test_evalf_bugs
3. sympy\core\tests\test_expand.py:test_expand_log
4. sympy\functions\elementary\tests\test_exponential.py:test_log_values
5. sympy\functions\elementary\tests\test_exponential.py:test_log_base
6. sympy\functions\special\tests\test_gamma_functions.py:test_loggamma
7. sympy\integrals\tests\test_meijerint.py:test_expint
8. sympy\integrals\tests\test_transforms.py:test_sine_transform
9. sympy\physics\quantum\tests\test_density.py:test_entropy
10. sympy\solvers\tests\test_solvers.py:test_issue_6056
11. sympy\solvers\tests\test_solveset.py:test_nonlinsolve_complex
12. sympy\solvers\tests\test_solveset.py:test_issue_5132_1
13. sympy\solvers\tests\test_solveset.py:test_issue_5132_substitution
These files were reported, all of them game AssertionError

**Comment by jksuom** [comment]
Tests like `test_log1p` contain several parts. Could you add the exact line number of the failing assert?

**Comment by abaokar-07** [comment]
@jksuom sure
1. sympy\codegen\tests\test_cfunctions.py:test_log1p - line 35
2. sympy\core\tests\test_evalf.py:test_evalf_bugs - line 177
3. sympy\core\tests\test_expand.py:test_expand_log - line 304
4. sympy\functions\elementary\tests\test_exponential.py:test_log_values - line 176
5. sympy\functions\elementary\tests\test_exponential.py:test_log_base - line 191
6. sympy\functions\special\tests\test_gamma_functions.py:test_loggamma - line 356
7. sympy\integrals\tests\test_meijerint.py:test_expint - line 551
8. sympy\integrals\tests\test_transforms.py:test_sine_transform - line 667
9. sympy\physics\quantum\tests\test_density.py:test_entropy - line 166
10. sympy\solvers\tests\test_solvers.py:test_issue_6056 - line 1289
11. sympy\solvers\tests\test_solveset.py:test_nonlinsolve_complex - line line 1220
12. sympy\solvers\tests\test_solveset.py:test_issue_5132_1 - line 1264
13. sympy\solvers\tests\test_solveset.py:test_issue_5132_substitution - line 1423

**Comment by jksuom** [comment]
Thanks. It seems that some of those would probably not be hard to fix but then there are tests that are not directly connected with log and it more work may be required to fix them.

**Comment by abaokar-07** [comment]
@jksuom okay, I would like to fix it
BTW I think 6th, 7th, 11th, 12th and 13th of the above listed files might require work, rest all should not be hard, am I right?

**Comment by jksuom** [comment]
It seems that your line numbers differ from those of mine in some files. I'd have to run those tests locally to see what is going on exactly. But, in any case, you can try to fix those and show the `git diff` for the fixes.

**Comment by abaokar-07** [comment]
@jksuom okay I'll try at my end, starting from the files in which direct logarithm is involved, can you suggest what should be done?

**Comment by jksuom** [comment]
The simplest cases are those where the assert fails because a correct result is formatted differently. In those cases it is possible to edit the assert line to conform to the result.

**Comment by asmeurer** [comment]
@abaokar-07 if you push up your change to a provisional pull request, Travis will run the tests and it will be easier for everyone to see what is failing.

**Comment by abaokar-07** [comment]
@asmeurer so shall I open a pull request regarding to the changes done?

**Comment by abaokar-07** [comment]
@jksuom as @asmeurer suggested to push changes to a pull request, should I open a pull request by removing those lines in [comment](https://github.com/sympy/sympy/issues/5950#issuecomment-362839107) so that everyone sees what's failing?

**Comment by jksuom** [comment]
Yes, if you open a pull request after removing the lines having to do with Rationals in `log.eval`, then Travis will run the tests and we can see what is failing.
