### ISSUE TITLE
Sum(sin(n), (n, 1, oo)).is_convergent() is not implemented

### ISSUE THREAD

**Issue by ghost** [sympy/sympy#14103]
`>>> Sum(sin(n), (n, 1, oo)).is_convergent()`
Traceback (most recent call last):

  File "<ipython-input-7-5c5f3b72e2d9>", line 1, in <module>
    Sum(sin(n), (n, 1, oo)).is_convergent()

  File "C:\Users\Roland\Anaconda3\lib\site-packages\sympy\concrete\summations.py", line 528, in is_convergent
    "is not yet implemented" % (sequence_term))

NotImplementedError: The algorithm to find the Sum convergence of sin(n) is not yet implemented

**Comment by asmeurer** [comment]
Related https://github.com/sympy/sympy/issues/8328

What convergence check can be implemented to show that the sum does not converge?

**Comment by maurogaravello** [comment]
In this case, it is sufficient to check the limit of `sin(n)` as `n` tends to `oo`. Since the limit does not exist (in particular is different from `0`), the sum can not be convergent.

**Comment by anutosh491** [comment]
This seems to be implemented as of now , but going through some cases as discussed in the above closed PR (wasn't the correct solution for this ) I discovered that `Sum(expr , (n, x, y))` where expr is 0 gives `TypeError` .

![image](https://user-images.githubusercontent.com/87052487/134623100-bbb8e493-d1a7-4a01-aa7c-206a9ebb3809.png)

**Comment by oscarbenjamin** [comment]
@anutosh491 please use markdown code formatting rather than a screenshot so that it is copyable. A convenient way to make something that you can copy/paste straight into github is using isympy like this:
```python
In [19]: Sum(sin(n), (n, 1, oo)).is_convergent()
Out[19]: False

In [20]: Sum(sin(n)**2 + cos(n)**2 - 1, (n, 1, oo)).is_convergent()
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-20-81c82c21ecb9> in <module>
----> 1 Sum(sin(n)**2 + cos(n)**2 - 1, (n, 1, oo)).is_convergent()

~/current/sympy/sympy.git/sympy/concrete/summations.py in is_convergent(self)
    519             lim_ratio = limit_seq(ratio, sym)
    520             if lim_ratio is not None and lim_ratio.is_number:
--> 521                 if abs(lim_ratio) > 1:
    522                     return S.false
    523                 if abs(lim_ratio) < 1:

~/current/sympy/sympy.git/sympy/core/decorators.py in _func(self, other)
    264             if not isinstance(other, expectedcls):
    265                 return retval
--> 266             return func(self, other)
    267 
    268         return _func

~/current/sympy/sympy.git/sympy/core/expr.py in __gt__(self, other)
    377     def __gt__(self, other):
    378         from .relational import StrictGreaterThan
--> 379         return StrictGreaterThan(self, other)
    380 
    381     @sympify_return([('other', 'Expr')], NotImplemented)

~/current/sympy/sympy.git/sympy/core/relational.py in __new__(cls, lhs, rhs, **options)
    706                     raise TypeError("Invalid comparison of non-real %s" % me)
    707                 if me is S.NaN:
--> 708                     raise TypeError("Invalid NaN comparison")
    709             # First we invoke the appropriate inequality method of `lhs`
    710             # (e.g., `lhs.__lt__`).  That method will try to reduce to

TypeError: Invalid NaN comparison

```
