### ISSUE TITLE
Presicion lose in subtraction 

### ISSUE THREAD

**Issue by VahanArsenyan** [sympy/sympy#14116]
`c**2-real_root(real_root(c,1/6),3)` return something like 3.56e-15 where `c=5`. I have checked `c**2` is 25 with 110 precision and `real_root(real_root(c,1/6),3)` is 25 with 110 precision.
I can not understand from where comes 3.56e-15

**Comment by cbm755** [comment]
I can reproduce this:
````
c = S(5)
c**2-real_root(real_root(c,1.0/6),3)
````
But I think its the expected behaviour because the 1.0/6 is a floating point number.

If you want exactly the rational number 1/6, use:
````
>>> c = S(5)
>>> c**2-real_root(real_root(c,S(1)/6),3)
0
````
And this gives 0 as expected.

**Comment by VahanArsenyan** [comment]
Thanks @cbm755
