### ISSUE TITLE
Sum(1/log(log(n)), (n, 22, oo)).is_convergent() not implemented

### ISSUE THREAD

**Issue by ghost** [sympy/sympy#14111]
`>>> Sum(1/log(log(n)), (n, 22, oo)).is_convergent()`
Traceback (most recent call last):

  File "<ipython-input-19-50f193f491f8>", line 1, in <module>
    Sum(1/log(log(n)), (n, 22, oo)).is_convergent()

  File ".\sympy\concrete\summations.py", line 528, in is_convergent
    "is not yet implemented" % (sequence_term))

NotImplementedError: The algorithm to find the Sum convergence of 1/log(log(n)) is not yet implemented

Could someone please tell me the way to put the whole thing in code form
When I try to put the whole thing in code form, with that symbol under the tilde at the start and at the end , then none of it appears in code form

Is this a flaw in the is_convergent program
That whenever it encounters a sum whose convergence is unknown, it cause an error

**Comment by normalhuman** [comment]
You can post a code block by surrounding it with triple backticks ``` (so-called code walls). For example
```
>>> Sum(1/log(log(n)), (n, 22, oo)).is_convergent()
NotImplementedError: The algorithm to find the Sum convergence of 1/log(log(n)) is not yet implemented
```
> whenever it encounters a sum whose convergence is unknown, it cause an error

When a Python program encounters an input for which it does not have an algorithm, it may raise NotImplementedError to inform the user about its limitation. The docstring of the `is_convergent` method says as much:

> There are various tests employed to check the convergence like divergence test, root test, integral test, alternating series test, comparison tests, Dirichlet tests. It returns true if Sum is convergent and false if divergent and NotImplementedError if it can not be checked.

So rather than writing "causes an error" it would be more accurate to say "is not implemented" in the title.

**Comment by Roland-Sands** [comment]
> You can post a code block by surrounding it with triple backticks ```

I put 3 backticks at the beginning and at the end
It put multiple lines in code form, but 1 line was lost and the 3 backticks at the end were displayed

**Comment by jksuom** [comment]
> 3 backticks at the beginning

I have noticed that those have to be alone on the first line. If there is something else, the whole line will be lost.
