### ISSUE TITLE
limit_seq( n*n*(Sum(1/k, (k, 1, n)) - log(n + 1/2) - EulerGamma), n)  is not exact

### ISSUE THREAD

**Issue by Roland-Sands** [sympy/sympy#14125]
```
>>> limit_seq( n*(n*(Sum(1/k, (k, 1, n)) - log(n) - EulerGamma) - 1/2), n)
-1/12
>>> limit_seq( n*n*(Sum(1/k, (k, 1, n)) - log(n + 1/2) - EulerGamma), n)
0.0416666666666667
```

**Comment by normalhuman** [comment]
1/2 creates a Python float 0.5, which SymPy turns into Float object. Subsequent manipulations with floats produce more floats. This is explained in [Python numbers vs. SymPy Numbers](http://docs.sympy.org/latest/gotchas.html#python-numbers-vs-sympy-numbers)

To avoid this, use one of: `Rational(1, 2)`, `Rational('0.5')`, `S(1)/2`, `S.Half` in place of 1/2. 
```
>>> limit_seq( n*n*(Sum(1/k, (k, 1, n)) - log(n + S(1)/2) - EulerGamma), n)
1/24
```
