### ISSUE TITLE
I have doubts about the correctness of integrate(asin(x), (x, 0, 9))

### ISSUE THREAD

**Issue by Roland-Sands** [sympy/sympy#14147]
```
>>> integrate(asin(x), (x, 0, 9))
-1 + 9*asin(9) + 4*sqrt(5)*I
```
At first I thought it was clearly wrong, but now I'm not sure what I consider `asin` to be
```
>>> asin(2).evalf()
1.5707963267949 - 1.31695789692482*I
```

**Comment by normalhuman** [comment]
Looks correct to me, considering how the arcsin is [defined in the complex plane](https://en.wikipedia.org/wiki/Inverse_trigonometric_functions#Extension_to_complex_plane). Mathematica
```
Integrate[ArcSin[x], {x, 0, 9}]
-1 + 4 I Sqrt[5] + 9 ArcSin[9]
```
and Maple
```
integrate(arcsin(x), x = 0 .. 9)
-1+9*Pi*(1/2)-9*arccos(9)+(4*I)*sqrt(5)
```
return equivalent results.
