### ISSUE TITLE
Can't set bottom and top bounds of root isolation rectangle with dup_isolate_complex_roots_sqf()

### ISSUE THREAD

**Issue by skirpichev** [sympy/sympy#14159]
```python
In [9]: R, x = ring("x", ZZ)

In [10]: f = x**2 - 2*x + 3

In [11]: R.dup_count_complex_roots(f, inf=(QQ(1, 2), QQ(1)), sup=(QQ(2), QQ(3)))
Out[11]: 1

In [12]: R.dup_isolate_complex_roots_sqf(f, inf=(QQ(1, 2), QQ(1)), sup=(QQ(2), QQ(3)))
...
TypeError: can't multiply sequence by non-int of type 'mpq'
```

Perhaps, this is intentional, as it's possible to set left and right bounds:
```
In [13]: R.dup_isolate_complex_roots_sqf(f, inf=QQ(1, 2), sup=QQ(2))
Out[13]: 
[((mpq(1,2), mpq(-3,1)), (mpq(2,1), mpq(0,1))),
 ((mpq(1,2), mpq(0,1)), (mpq(2,1), mpq(3,1)))]
```

But I think it would be better to have ability to shrink the initial root isolation rectangle in vertical direction too.  Like, dup_count_complex_roots(), which has a different call convention: ``inf`` and ``sup`` are tuples.

Currently, in dup_isolate_complex_roots_sqf() - bottom and top bounds are hardcoded by Kojima's bound.

**Comment by skirpichev** [comment]
Or, in turn, dup_count_complex_roots() should use same specification of ``inf`` and ``sup`` as dup_isolate_complex_roots_sqf() currently does (to numbes, not tuples).

@jksuom, what do you think?

**Comment by jksuom** [comment]
Maybe it would be possible to have it both ways, tuples for setting the real and imaginary bounds and single numbers for real bounds (with hard-coded bounds for missing specifications).

**Comment by skirpichev** [comment]
I.e. functions for counting/isolating real roots should accept tuples for inf/sup?  Sounds odd.

**Comment by jksuom** [comment]
I understood this was about complex roots.

**Comment by skirpichev** [comment]
Oh, I didn't mention - there are methods for real roots too.  And for both real and complex.  All use same argument names (inf/sup) and same argument value convention, i.e. numbers; tuples - only in dup_count_complex_roots().
