### ISSUE TITLE
Typesetting of big-O symbol

### ISSUE THREAD

**Issue by gxyd** [sympy/sympy#14163]
Currently typesetting of big-O symbol uses the ordinary 'O', we can use the typesetting as defined here https://en.wikipedia.org/wiki/Big_O_notation#Typesetting .

**Comment by asmeurer** [comment]
What I was saying was that we should replace the calligraphy O with a normal O, not the other way around.

**Comment by jashan498** [comment]
Oh sorry, @asmeurer I didn't see your comment. Should I close this PR?

**Comment by jashan498** [comment]
I also read the issue wrong. But I just checked the master branch:
```
>>> pprint(series(cos(x), x, pi, 3))
            2
     (x - π)     ⎛       3       ⎞
-1 + ──────── + O⎝(x - π) ; x → π⎠
        2
```
The `O` here is ordinary O only, [see](https://github.com/sympy/sympy/blob/2c0a3a103baa547de12e332382d44ee3733d485f/sympy/printing/pretty/pretty.py#L1278).
