### ISSUE TITLE
On diop_solve returning (None, None)

### ISSUE THREAD

**Issue by Roland-Sands** [sympy/sympy#14172]
If `a*x + b*y + c = 0` has a solution then `diop_solve(a*x + b*y + c)` returns all pairs `(m,n)` where `m` and `n` are integers and  `a*m + b*n + c = 0`
If `a*x + b*y + c = 0` has no solution then `diop_solve(a*x + b*y + c)` returns `(m,n)` where `m` and `n` are both `None`
`None` is not an integer, so these 2 classes of returns have different forms
They would have the same form if, instead of returning `(None, None)`, SymPy returned `No solution` or the empty pair, `(,)`

**Comment by normalhuman** [comment]
The function diop_solve is internal to the module. The function intended for use is diophantine, which consistently returns a set of tuples (empty set if there are no solutions).
