### ISSUE TITLE
Converting to LaTeX 

### ISSUE THREAD

**Issue by VahanArsenyan** [sympy/sympy#14175]
`latex(ln(10))` was converted to `log{\left(10\right)}` which is in some fields is log10(10) or log2(10).
There is '\ln' in LaTeX and `ln(10)` should be converted to  it not to `log{\left(10\right)}`

**Comment by SaiSakethAluru** [comment]
I would like to work on this. Can someone please guide me?

**Comment by VahanArsenyan** [comment]
Thanks for replay
