### ISSUE TITLE
Some expressions not being evaluated at arbitrary positive integers

### ISSUE THREAD

**Issue by Roland-Sands** [sympy/sympy#14177]
```
>>> n = symbols('n', positive=True, integer=True)
>>> zeta(2*n)
zeta(2*n)
>>> zeta(-n)
zeta(-n)
>>> integrate((hermite(n, x))**(2)*exp(-x**2), (x, -oo, oo))
Integral(exp(-x**2)*hermite(n, x)**2, (x, -oo, oo))
```
The values of `zeta(2*n)` and `zeta(-n)` are given in the SymPy docs and the integral (which is related to the orthogonality of the Hermite polynomials) is 
``` 
 n      
2 ⋅√π⋅n!
```

**Comment by jksuom** [comment]
It is probably not hard to modify `zeta.eval()` to return `zeta(-n)` and `zeta(2*n)` as expressions involving Bernoulli numbers when `n` is a positive integer symbol.

**Comment by vishalg2235** [comment]
@jksuom what about the evaluated integral `Integral(exp(-x**2)*hermite(n, x)**2, (x, -oo, oo))` ?

**Comment by jksuom** [comment]
`meijerint` can compute that integral for numerical values of `n`. For symbolic values there does not seem to be an algorithm.

**Comment by Roland-Sands** [comment]
> For symbolic values there does not seem to be an algorithm

The Hermite polynomials have their own section in the orthogonal polynomials file
For the Hermite, Legendre, and other orthogonal polynomials in this file, could information be added on the interval over which they are orthogonal as well as the weighting
This would calculate the above integral (I think) as well as 
`Integral(exp(-x**2)*hermite(m, x)*hermite(n, x), (x, -oo, oo)) = 0`

**Comment by vandythong** [comment]
can anyone walk me through how to get started. im new here. Thank you!
