### ISSUE TITLE
Documentation fixes needed for Sphinx 1.7.0

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#14187]
Apparently the fix from https://github.com/sympy/sympy/pull/14181 is wrong. See https://github.com/sphinx-doc/sphinx/issues/4606#issuecomment-365160088. We need to revert the newlines before `:members:` and fix the issues in the docstrings. 

We may also consider disabling the `autodoc_inherit_docstrings` feature, as described in that comment. I don't think the feature really makes sense, since many superclass docstrings assume they are documenting the superclass, and also putting them on every subclass could clutter the documentation. 

But if others disagree we can leave it. The most important thing is to re-add the :members:, and fix the `eval` docstring.

**Comment by jksuom** [comment]
> We may also consider disabling the autodoc_inherit_docstrings feature, as described in that comment. I don't think the feature really makes sense, since many superclass docstrings assume they are documenting the superclass, and also putting them on every subclass could clutter the documentation.

I fully agree with this.

**Comment by jashan498** [comment]
@asmeurer @jksuom I have removed all the newlines. Where to disable the `autodoc_inherit_docstrings` feature?

**Comment by jksuom** [comment]
I think that the configuration value should be set in `doc/src/conf.py`.
(A comment line and then `autodoc_inherit_docstrings = False`.)
