### ISSUE TITLE
Problems with printing

### ISSUE THREAD

**Issue by ghost** [sympy/sympy#14194]
I was executing `Sum(m**38, (m, 1, n)).doit()` and I am using the IPython console

`print` works perfectly: individual terms `a_k*n**k` never split across lines and the output dynamically adjusts to the width of the window
`pprint` does split terms across lines, it split the `n**27, n**19, n**11, n**5` terms, and the output has some sort of default window size: increasing the width from that doesn't change the way it is displayed, but the output does adjust to decreasing the width from that default
Latex printing puts the whole thing on 1 line and ignores the width of the window

**Comment by oscargus** [comment]
I got this now (a bit to my surprise it breaks the lines...):
![image](https://user-images.githubusercontent.com/8114497/52736679-b3537080-2fca-11e9-9747-590b59e7317c.png)

Increasing the width doesn't change anything though. I would almost assume that it is something in IPython that makes the line breaks as the Sympy code does not consider this at all.

**Comment by asmeurer** [comment]
I think MathJax does line breaking. This could also be related to https://github.com/sympy/sympy/pull/15625.
