### ISSUE TITLE
Problems with limits

### ISSUE THREAD

**Issue by ghost** [sympy/sympy#14192]
`limit(cos(x), x, oo), limit(cos(x)*exp(x), x, oo), limit_seq(cos(n)), limit_seq(cos(n)*log(n)), limit_seq(cos(n)*exp(n))` return `<-1, 1>`
`limit_seq(sin(n)*factorial(n))` returns `<-oo, oo>`
`limit_seq((-1/5)**n)` hangs
`limit_seq((-1)**n), limit_seq((-2)**n), limit_seq((I)**n), limit_seq((I/3)**n), limit_seq((2*I)**n)` execute and return nothing

**Comment by sachin-4099** [comment]
`limit_seq((I)**n) ` and `limit_seq((2*I)**n)` these are the only cases which are still persisting,
Otherwise everything else is working fine. Please verify and let me know @oscarbenjamin.

**Comment by 0sidharth** [comment]
On current master,
```python
In [18]: limit(cos(x), x, oo), limit(cos(x)*exp(x), x, oo), limit_seq(cos(n)), limit_seq(cos(n)*log(n)), limit_seq(cos(n)*exp(n))
Out[18]: (<-1, 1>, <-∞, ∞>, <-1, 1>, <-∞, ∞>, <-∞, ∞>)

In [19]: limit_seq(sin(n)*factorial(n))
Out[19]: <-∞, ∞>

In [20]: limit_seq((-1/5)**n)
Out[20]: 0

In [21]: limit_seq((-1)**n), limit_seq((-2)**n), limit_seq((I)**n), limit_seq((I/3)**n), limit_seq((2*I)**n)
Out[21]: (<-1, 1>, <-∞, ∞>, nan, 0, zoo)
```
I think these are the expected answers and there is no longer and issue.

**Comment by jksuom** [comment]
Closing, as the current results are the expected ones.
