### ISSUE TITLE
unpolarify raises an exception when given a matrix entry

### ISSUE THREAD

**Issue by normalhuman** [sympy/sympy#14216]
```
>>> from sympy import *
>>> A = MatrixSymbol("A", 2, 2)
>>> unpolarify(A[0, 0])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/lvk/sympy/sympy/functions/elementary/complexes.py", line 1149, in unpolarify
    res = _unpolarify(eq, exponents_only, pause)
  File "/home/lvk/sympy/sympy/functions/elementary/complexes.py", line 1120, in _unpolarify
    return eq.func(*[_unpolarify(x, exponents_only, True) for x in eq.args])
  File "/home/lvk/sympy/sympy/functions/elementary/complexes.py", line 1120, in <listcomp>
    return eq.func(*[_unpolarify(x, exponents_only, True) for x in eq.args])
  File "/home/lvk/sympy/sympy/functions/elementary/complexes.py", line 1120, in _unpolarify
    return eq.func(*[_unpolarify(x, exponents_only, True) for x in eq.args])
  File "/home/lvk/sympy/sympy/functions/elementary/complexes.py", line 1120, in <listcomp>
    return eq.func(*[_unpolarify(x, exponents_only, True) for x in eq.args])
  File "/home/lvk/sympy/sympy/functions/elementary/complexes.py", line 1092, in _unpolarify
    if isinstance(eq, bool) or eq.is_Atom:
AttributeError: 'str' object has no attribute 'is_Atom'
```

This is problematic because some special functions call unpolarify. For example, 
```
loggamma(A[0, 0]).diff(A[0, 0])
```
fails with the above error.

**Comment by jashan498** [comment]
@normalhuman are below the expected outputs?
```
>>> unpolarify(A[0, 0])
A[0,0]
>>> unpolarify(A[0, 0]*A[1,1])
A[0, 0]*A[1,1]
```

**Comment by normalhuman** [comment]
Yes, the expected output is the original expression in these cases. 

Is it necessary to have a special case for MatrixElement? I wonder if other classes have this issue. What makes str appear in the process?

**Comment by jashan498** [comment]
`A[0,0].args =(A, 0, 0)`, here `A` is a `MatrixSymbol`. Now all these three arguments are [recursively](https://github.com/sympy/sympy/blob/d7bf2bf34a0aaa455648517e2372a82abd188298/sympy/functions/elementary/complexes.py#L1120) passed again one by one where `A.args=('A', 2, 2)`. Thus `A[0,0].args[0].args` is a string.

**Comment by jashan498** [comment]
So anything which ends this recursion for `MatrixSymbol` should work. I think any object whose all `args` doesnot end up to(or are)  `atoms` (as `MatrixBase` ending up to str) should be vulnerable.

**Comment by normalhuman** [comment]
So, the issue is that args of a SymPy expression may be of string type or of some other type that doesn't have `is_Atom` property. The current code has `isinstance(eq, bool)` check to guard against that but we see this isn't sufficient. I think the proper fix is to change the line 
```
if isinstance(eq, bool) or eq.is_Atom:
```
to 
```
if not isinstance(eq, Basic) or eq.is_Atom:
```
If eq inherits from [Basic](https://github.com/sympy/sympy/blob/master/sympy/core/basic.py#L29) then `is_Atom` will work; otherwise it's of some type that unpolarify can't work with, so it should be left alone.

**Comment by jashan498** [comment]
This looks good
