### ISSUE TITLE
solveset needs to clip solution with constraining set

### ISSUE THREAD

**Issue by smichr** [sympy/sympy#14223]
When a Piecewise is being solved by solveset, a check is not made that the solution is within the conditions under which the expression is constrained. This leads to spurious solutions as shown below. The solution should be clipped by the constraining set:

```diff
diff --git a/sympy/solvers/solveset.py b/sympy/solvers/solveset.py
index 1ce7e20..0595502 100644
--- a/sympy/solvers/solveset.py
+++ b/sympy/solvers/solveset.py
@@ -797,7 +797,7 @@ def _solveset(f, symbol, domain, _check=False):
                 in_set = in_set.as_set()
             if in_set.is_Interval:
                 dom -= in_set
-            solns = solver(expr, symbol, in_set)
+            solns = solver(expr, symbol, in_set) & in_set
             result += solns
     else:
         lhs, rhs_s = inverter(f, 0, symbol)
```

current behavior

```python
>>> solveset((Abs(x+Min(x,2))-2).rewrite(Piecewise),x,S.Reals)
{-1, 0, 1}
```
after fix
```python
>>> solveset((Abs(x+Min(x,2))-2).rewrite(Piecewise),x,S.Reals)
{-1, 1}
```

On review of the situation, there should be no need for clipping the result since the domain passed to `solver` was already identified as `in_set`. Perhaps the following is better:

```diff
diff --git a/sympy/solvers/solveset.py b/sympy/solvers/solveset.py
index 1ce7e20..ca3f6ad 100644
--- a/sympy/solvers/solveset.py
+++ b/sympy/solvers/solveset.py
@@ -848,13 +848,20 @@ def _solveset(f, symbol, domain, _check=False):
             # -- leave it alone
             return result

-        # whittle away all but the symbol-containing core
-        # to use this for testing
-        fx = orig_f.as_independent(symbol, as_Add=True)[1]
-        fx = fx.as_independent(symbol, as_Add=False)[1]
+        ### XXX improve this. result & domain should just work
+        # but consider the current state where an ImageSet doesn't
+        # know how to intersect with Complexes:
+        # >>> solveset(exp(x) - 1, x)
+        # Intersection(ImageSet(Lambda(_n, 2*_n*I*pi), S.Integers), Complexes(S.Reals x S.Reals, False))
+        if isinstance(result, (Interval, FiniteSet)):
+            result = result & domain

         if isinstance(result, FiniteSet):
             # check the result for invalid solutions
+            # whittle away all but the symbol-containing core
+            # to use this for testing
+            fx = orig_f.as_independent(symbol, as_Add=True)[1]
+            fx = fx.as_independent(symbol, as_Add=False)[1]
             result = FiniteSet(*[s for s in result
                       if isinstance(s, RootOf)
                       or domain_check(fx, symbol, s)])
```

**Comment by Yathartha22** [comment]
I will take this up.

**Comment by ishanaj** [comment]
@smichr I tried this with the modifications in PR #13913 and it gives the correct result.
```
>>>solveset((Abs(x+Min(x,2))-2).rewrite(Piecewise),x , S.Reals)  
{-1, 1}
```

**Comment by smichr** [comment]
@Yathartha22 , how about adding the diff as a PR to @ishanaj 's #13913?

@ishanaj , how about the following?

```
solveset((Abs(x+Min(x,2))-2).rewrite(Piecewise),x , Interval(0,2))
```

The 2nd diff that I showed above should really be applied. It would be a good exercise of collaboration if @Yathartha22 made that PR to yours. I will leave another note on your PR regarding your work on Min/Max and Piecewise rewriting.

**Comment by Yathartha22** [comment]
>  how about adding the diff as a PR to @ishanaj 's #13913?

That will be a good idea, because this issue seems in accordance with the PR.

**Comment by ishanaj** [comment]
```
>>> solveset((Abs(x+Min(x,2))-2).rewrite(Piecewise),x , Interval(0,2))
{-1, 1}    #as per PR #13913
```
>It would be a good exercise of collaboration if @Yathartha22 made that PR to yours.

Yeah, this seems cool!!!

**Comment by smichr** [comment]
That result should not include that -1...I think that is the part the @Yathartha22 could work out.

```
>>> solveset((Abs(x+Min(x,2))-2).rewrite(Piecewise),x , Interval(0,2))
{-1, 1}    #as per PR #13913
```

**Comment by smichr** [comment]
Uggh. Forget the diff and just see why this fails:

```
>>> solveset(x,x,Interval(2,3))
{0}
```

**Comment by Yathartha22** [comment]
>  just see why this fails:

This is due to [this](https://github.com/sympy/sympy/blob/master/sympy/solvers/solveset.py#L108). The condition evaluates to `True`, since `x1==f_x`. Either we fix it here or have another check before returning the solution in `_solveset`

**Comment by Yathartha22** [comment]
Alternate to `x_1==f_x`, we should use `(x1 == f_x and f_x != x)`.

**Comment by smichr** [comment]
This is what I concluded as well: `if not isinstance(s, FiniteSet) or x1 != x:` (see my 14223 branch for wip).

**Comment by Yathartha22** [comment]
@smichr the idea seems good. But what I figured out is that for any type of equations the helpers always return the result in the specified domain (be it _invert or _solve_as_poly or trigonometric etc), `_solveset` assumes that the `result` is in the specified domain (No bother to check again). The fix you suggested in a way becomes repetitive checking for the domain (once the helpers intersect and then _solveset again intersects, just to double check). If we go with your fix, I guess we don't need to worry about intersecting result with the domain in helpers (so we should remove it).
Another fix what I suggest is Piecewise should return the result by intersecting with the domain (in accordance like what the other helpers do), because currently piecewise evaluates the result only in sub-domains of the expr (not considering the domain)

Something like this: 
```
diff --git a/sympy/solvers/solveset.py b/sympy/solvers/solveset.py
index 1ce7e20..c611ae2 100644
--- a/sympy/solvers/solveset.py
+++ b/sympy/solvers/solveset.py
@@ -105,7 +105,7 @@ def _invert(f_x, y, x, domain=S.Complexes):
     else:
         x1, s = _invert_complex(f_x, FiniteSet(y), x)
 
-    if not isinstance(s, FiniteSet) or x1 == f_x or x1 != x:
+    if not isinstance(s, FiniteSet) or (x1 == f_x and f_x != x) or x1 != x:
         return x1, s
 
     return x1, s.intersection(domain)
@@ -799,6 +799,7 @@ def _solveset(f, symbol, domain, _check=False):
                 dom -= in_set
             solns = solver(expr, symbol, in_set)
             result += solns
+        result = result.intersect(domain)
     else:
         lhs, rhs_s = inverter(f, 0, symbol)
         if lhs == symbol:

```

**Comment by smichr** [comment]
> (x1 == f_x and f_x != x) or x1 != x

The first clause is the redundant, I believe, because if `x1 == f_x` the you can substitute that into `f_x != x` to give `x1 != x`...and that is the same as the second clause. So you are basically saying `x1 != x or x1 != x`.

**Comment by Yathartha22** [comment]
Ok I see, so why not we change the condition to just `if not isinstance(s, FiniteSet) or x1 != x:`
It seems obvious that if we do not get `x` in the lhs then the equation is not solved.

**Comment by smichr** [comment]
> why not we change the condition to just if not isinstance(s, FiniteSet) or x1 != x:

Yes, that is what should be done. There are lots of little issues that I have uncovered while looking at this. Would you @Yathartha22  and @ishanaj be interested in looking over what I've got or do you want to work on your own changes? I'll post the PR so you can see what you think.

**Comment by smichr** [comment]
We can try this as a multi-person PR. @Yathartha22 , if you make your change first, then I will make whatever changes are left as a PR to @ishanaj work rather as a separate PR (which I now just marked as WIP).

**Comment by Yathartha22** [comment]
Yeah sure @smichr would love to do it.
