### ISSUE TITLE
sin(2*pi/17) cannot be written as a surd

### ISSUE THREAD

**Issue by Roland-Sands** [sympy/sympy#14231]
Admittedly it's a bit obscure (and the result is not pretty), but it would give SymPy bragging rights, Wolfram alpha can't do it

`sin(2*pi/p)` and `cos(2*pi/p)` can explicitly written in terms of nested square roots when p is a Fermat prime
Thus, it can be done when p is one of 3‎, ‎5‎, ‎17‎, ‎257‎, ‎65 537

It's related to that constructive polygon theorem of Gauss

**Comment by jksuom** [comment]
That can be done by applying `.rewrite(sqrt)`.

**Comment by Roland-Sands** [comment]
```
>>> sin(2*pi*I/17).rewrite(sqrt)
      ⎛2⋅π⎞
ⅈ⋅sinh⎜───⎟
      ⎝ 17⎠
```

**Comment by normalhuman** [comment]
expand_trig also does that. Perhaps the docstring of trig functions should mention that evaluation at more values is possible with this method. It isn't very obvious.
