### ISSUE TITLE
Major performance regression in summation

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#14240]
See https://github.com/sympy/sympy_benchmarks/blob/master/benchmarks/sum.py. In sympy-1.1.1, the benchmark runs in a few seconds. In master, it takes several minutes. 

I bisected it to commit 1c658e00ffa5cec777dd2d9f9453135ab55e75d0, which is from https://github.com/sympy/sympy/pull/12587.

CC @smichr

**Comment by asmeurer** [comment]
Looks like it is spending a lot of time in `piecewise_fold`, trying to fold this expression:

```
Piecewise((Ts(0, ((), ((0, 1, -I/2), (1, 0, I/2)), ()), ext11Pi, 1)*Ts(0, ((), ((0, 1, -I/2), (1, 0, I/2)), ()), ext31Pi, 1)*Ts(int62ASU2L, ((), ((0, 1, -I/2), (1, 0, I/2)), ()), 1, ext21Pi)*Ts(int62ASU2L, ((), ((0, 1, -I/2), (1, 0, I/2)), ()), 1, ext41Pi), (int62ASU2L >= 0) & (int62ASU2L <= 2)), (0, True)) + Piecewise((Ts(0, ((), ((0, 1, -I/2), (1, 0, I/2)), ()), ext11Pi, 1)*Ts(0, ((), ((0, 1, -I/2), (1, 0, I/2)), ()), ext31Pi, 2)*Ts(int62ASU2L, ((), ((0, 1, -I/2), (1, 0, I/2)), ()), 1, ext21Pi)*Ts(int62ASU2L, ((), ((0, 1, -I/2), (1, 0, I/2)), ()), 2, ext41Pi), (int62ASU2L >= 0) & (int62ASU2L <= 2)), (0, True)) + Piecewise((Ts(0, ((), ((0, 1, -I/2), (1, 0, I/2)), ()), ext11Pi, 2)*Ts(0, ((), ((0, 1, -I/2), (1, 0, I/2)), ()), ext31Pi, 1)*Ts(int62ASU2L, ((), ((0, 1, -I/2), (1, 0, I/2)), ()), 1, ext41Pi)*Ts(int62ASU2L, ((), ((0, 1, -I/2), (1, 0, I/2)), ()), 2, ext21Pi), (int62ASU2L >= 0) & (int62ASU2L <= 2)), (0, True)) + Piecewise((Ts(0, ((), ((0, 1, -I/2), (1, 0, I/2)), ()), ext11Pi, 2)*Ts(0, ((), ((0, 1, -I/2), (1, 0, I/2)), ()), ext31Pi, 2)*Ts(int62ASU2L, ((), ((0, 1, -I/2), (1, 0, I/2)), ()), 2, ext21Pi)*Ts(int62ASU2L, ((), ((0, 1, -I/2), (1, 0, I/2)), ()), 2, ext41Pi), (int62ASU2L >= 0) & (int62ASU2L <= 2)), (0, True)) + Piecewise((Ts(1, ((), ((0, 1, -I/2), (1, 0, I/2)), ()), ext11Pi, 1)*Ts(1, ((), ((0, 1, -I/2), (1, 0, I/2)), ()), ext31Pi, 1)*Ts(int62ASU2L, ((), ((0, 1, -I/2), (1, 0, I/2)), ()), 1, ext21Pi)*Ts(int62ASU2L, ((), ((0, 1, -I/2), (1, 0, I/2)), ()), 1, ext41Pi), (int62ASU2L >= 0) & (int62ASU2L <= 2)), (0, True)) + Piecewise((Ts(1, ((), ((0, 1, -I/2), (1, 0, I/2)), ()), ext11Pi, 1)*Ts(1, ((), ((0, 1, -I/2), (1, 0, I/2)), ()), ext31Pi, 2)*Ts(int62ASU2L, ((), ((0, 1, -I/2), (1, 0, I/2)), ()), 1, ext21Pi)*Ts(int62ASU2L, ((), ((0, 1, -I/2), (1, 0, I/2)), ()), 2, ext41Pi), (int62ASU2L >= 0) & (int62ASU2L <= 2)), (0, True)) + Piecewise((Ts(1, ((), ((0, 1, -I/2), (1, 0, I/2)), ()), ext11Pi, 2)*Ts(1, ((), ((0, 1, -I/2), (1, 0, I/2)), ()), ext31Pi, 1)*Ts(int62ASU2L, ((), ((0, 1, -I/2), (1, 0, I/2)), ()), 1, ext41Pi)*Ts(int62ASU2L, ((), ((0, 1, -I/2), (1, 0, I/2)), ()), 2, ext21Pi), (int62ASU2L >= 0) & (int62ASU2L <= 2)), (0, True)) + Piecewise((Ts(1, ((), ((0, 1, -I/2), (1, 0, I/2)), ()), ext11Pi, 2)*Ts(1, ((), ((0, 1, -I/2), (1, 0, I/2)), ()), ext31Pi, 2)*Ts(int62ASU2L, ((), ((0, 1, -I/2), (1, 0, I/2)), ()), 2, ext21Pi)*Ts(int62ASU2L, ((), ((0, 1, -I/2), (1, 0, I/2)), ()), 2, ext41Pi), (int62ASU2L >= 0) & (int62ASU2L <= 2)), (0, True)) + Piecewise((Ts(2, ((), ((0, 1, -I/2), (1, 0, I/2)), ()), ext11Pi, 1)*Ts(2, ((), ((0, 1, -I/2), (1, 0, I/2)), ()), ext31Pi, 1)*Ts(int62ASU2L, ((), ((0, 1, -I/2), (1, 0, I/2)), ()), 1, ext21Pi)*Ts(int62ASU2L, ((), ((0, 1, -I/2), (1, 0, I/2)), ()), 1, ext41Pi), (int62ASU2L >= 0) & (int62ASU2L <= 2)), (0, True)) + Piecewise((Ts(2, ((), ((0, 1, -I/2), (1, 0, I/2)), ()), ext11Pi, 1)*Ts(2, ((), ((0, 1, -I/2), (1, 0, I/2)), ()), ext31Pi, 2)*Ts(int62ASU2L, ((), ((0, 1, -I/2), (1, 0, I/2)), ()), 1, ext21Pi)*Ts(int62ASU2L, ((), ((0, 1, -I/2), (1, 0, I/2)), ()), 2, ext41Pi), (int62ASU2L >= 0) & (int62ASU2L <= 2)), (0, True)) + Piecewise((Ts(2, ((), ((0, 1, -I/2), (1, 0, I/2)), ()), ext11Pi, 2)*Ts(2, ((), ((0, 1, -I/2), (1, 0, I/2)), ()), ext31Pi, 1)*Ts(int62ASU2L, ((), ((0, 1, -I/2), (1, 0, I/2)), ()), 1, ext41Pi)*Ts(int62ASU2L, ((), ((0, 1, -I/2), (1, 0, I/2)), ()), 2, ext21Pi), (int62ASU2L >= 0) & (int62ASU2L <= 2)), (0, True)) + Piecewise((Ts(2, ((), ((0, 1, -I/2), (1, 0, I/2)), ()), ext11Pi, 2)*Ts(2, ((), ((0, 1, -I/2), (1, 0, I/2)), ()), ext31Pi, 2)*Ts(int62ASU2L, ((), ((0, 1, -I/2), (1, 0, I/2)), ()), 2, ext21Pi)*Ts(int62ASU2L, ((), ((0, 1, -I/2), (1, 0, I/2)), ()), 2, ext41Pi), (int62ASU2L >= 0) & (int62ASU2L <= 2)), (0, True))
```

It is creating a cartesian product of the args: https://github.com/sympy/sympy/blob/d68f2996b04ab7aa214c05d8a1ae86a83ac43cc4/sympy/functions/elementary/piecewise.py#L991

This results in `2**12 = 4096` args for a new Piecewise. However, every Piecewise term in the above expression has the first condition as `(int62ASU2L >= 0) & (int62ASU2L <= 2)` and the second part is `(0, True)`. So the folding should be trivial. Why is it missing such an obvious case? This seems to be a major regression in `piecewise_fold`. 

@smichr, https://github.com/sympy/sympy/pull/12587 was a pretty big PR, and the description there isn't clear (and neither is the commit message of the above bisected commit). Can you comment on what the changes to `piecewise_fold` were made there, and why it no longer seems to fold Add terms at all? Was the idea to move the folding into the Piecewise constructor itself? This is problematic if it requires doing the Cartesian product of all piecewise terms first, as that's grossly inefficient for even a few piecewise terms (and it hangs if there are more than a few).

**Comment by smichr** [comment]
> So the folding should be trivial.  Why is it missing such an obvious case?

It was rewritten to be generally true. If someone has insight into how to optimize it for special cases, hopefully the added tests will guard against simple approaches which are *not* generally true. (Recall that before that PR, some other very simple cases were not being handled properly. The OP of the PR lists several such cases.)

**Comment by asmeurer** [comment]
What are the pitfalls of combining terms with identical conditions? I think it should be fine if those terms are all the first term, no?

Even if it were a sum of 12 Piecewise with all different conditions, surely the sum would be preferable to a single piecewise with 4096 terms. Replacing an expression of size `2*n` with an expression of size `2**n` is not a simplification.

**Comment by smichr** [comment]
> What are the pitfalls of combining terms with identical conditions

It would be best to give specific (simple) cases of interest. 

> Even if it were a sum of 12 Piecewise with all different conditions, surely the sum would be preferable to a single piecewise with 4096 terms

Nothing is forcing you to use `piecewise_fold` on an expression. But if you fold it -- or more importantly, if you are a solver or an integrator in SymPy that needs to work with a folded Piecewise -- there is an expectation that it is, indeed,  folded and no longer contains nested Piecewise. It's not about representational simplicity. If you know of a simple way to handle the integration of a sum of Piecewise with different conditions (which may or may not have variables in common with the expressions they govern) -- without folding -- it would be nice to replace what I did to make that work. BTW, I did not find it to be an easy conceptual problem.

**Comment by smichr** [comment]
> no longer seems to fold Add terms at all

Could you give an example of this, please?

**Comment by asmeurer** [comment]
> It would be best to give specific (simple) cases of interest.

```
Piecewise((a, cond1), *rest1) + Piecewise((b, cond1), *rest2)
```

This should be the same as

```
Piecewise((a + b, cond1), rest3)
```

where `rest3` is the piecewise fold of the piecewises created from `rest1` and `rest2`. 

That's if I have my math right, and it's late, so it's possible I don't. 

> Nothing is forcing you to use piecewise_fold on an expression. 

Well in this case it's being called by Sum.doit() at the end (the original summation has no Piecewise). So should it be removed? 

I think there are two distinct uses of folding. One where you really do want one piecewise, even if it's exponentially larger, and one where you just want to simplify an expression with Piecewise. Maybe `piecewise_fold` should have some flag to indicate the difference.

> Could you give an example of this, please?

I'm just looking at the code: https://github.com/sympy/sympy/blob/d68f2996b04ab7aa214c05d8a1ae86a83ac43cc4/sympy/functions/elementary/piecewise.py#L948-L997

Folding on `Add` (or any other function) happens in the `else` block, only *after* the Cartesian product is taken. 

At the very least, could code be re-added to combine piecewise terms with the exact same conditions?

**Comment by smichr** [comment]
> Piecewise((a, cond1), *rest1) + Piecewise((b, cond1), *rest2)

Great example, thanks. I see no reason that all Piecewise args of an Expr should not be combined before entering the cartestian product step. I'll think about this and see if I can come up with something that hopefully solve the unfavorable treatment for the OP example.

**Comment by moorepants** [comment]
FYI, I'm not seeing this regression here: http://www.moorepants.info/misc/sympy-asv/#sum.TimeSum.time_doit

**Comment by asmeurer** [comment]
@moorepants interesting. What if you import the benchmark and run it manually (make sure to pull in the benchmarks repo because of https://github.com/sympy/sympy_benchmarks/pull/43)?  For me, in master, it definitely takes minutes to run.

```py
import benchmarks.sum
ts = benchmarks.sum.TimeSum()
ts.setup()
ts.time_doit()
```

(remember to set PYTHONPATH so that it imports the git sympy and sympy_benchmarks). 

For me in master, it takes 4 minutes. In sympy-1.0, it takes 12 seconds. 

By the way, if you can run the benchmarks and report any other major regressions and mark the issues on the 1.2 milestone, so that I can look at them before a release, that would help a lot. 

@smichr also if integrating a Piecewise really does require folding first, it should probably prefer to split on Add and pull out constants on Mul if possible first (I don't know if it is already doing this or not, just a thought that I had earlier when thinking about this).

**Comment by asmeurer** [comment]
Or I guess you can just run

```
PYTHONPATH=/path/to/git/sympy time python -m benchmarks.sum
```

in the benchmarks repo to run the benchmark.

**Comment by moorepants** [comment]
I have run the benchmarks for all merged PRs up till March 20, 2018 here: 

http://www.moorepants.info/misc/sympy-asv

Maybe this was introduce in the last month. I'll run the PRs from this past month when I get to my office tomorrow.

**Comment by moorepants** [comment]
I've added a bunch of issues with performance regressions I see in the last year or two.

**Comment by asmeurer** [comment]
@moorepants can you confirm that this benchmarks is slower if you run it manually? I think there must be something wrong with your benchmark running if this isn't showing as slow for you.

**Comment by asmeurer** [comment]
Actually, I seem to remember asv just failing entirely on this benchmark, because it times out. So maybe that is the problem?

**Comment by moorepants** [comment]
The sum benchmark is timing out on master for me with asv.

**Comment by asmeurer** [comment]
Right. It's something I've [brought up](https://github.com/airspeed-velocity/asv/issues/623#issuecomment-381448438) with the asv guys before, that a timeout should be considered a performance regression, not a failure.
