### ISSUE TITLE
Taylor Series Expansion

### ISSUE THREAD

**Issue by RISHAV98** [sympy/sympy#14246]
Created Taylor expansion and its plotting.
This code can be used to return taylor expansion for any function ,function can be represented using  sympy and it also generate the plot for that function

**Comment by Roland-Sands** [comment]
I think there already is code for Taylor expansions for functions of 1 variable

**Comment by gxyd** [comment]
@RISHAV98 as Rolands pointed out. See http://docs.sympy.org/latest/modules/series/series.html#sympy.series.series.series . We already have a functionality to compute the taylor series expansion.

Or is there something else that you're trying to do?

**Comment by Roland-Sands** [comment]
Is the plotting of the Taylor polynomials something that is not already implemented

**Comment by RISHAV98** [comment]
the code is basically for plotting the taylor expansion series for any function and this code gives  plot function for the function sin(x) approximating up to the 9th term.
