### ISSUE TITLE
Conjugate transpose of a matrix is in sympy.physics.quantum

### ISSUE THREAD

**Issue by ghost** [sympy/sympy#14265]

**Comment by normalhuman** [comment]
I don't know about physics.quantum module, but conjugate transpose is implemented as a Matrix method `.H`, which works well enough for me.  
```
>>> A = Matrix([[1, 2+I], [3*I, I]])
>>> A.H
Matrix([
[    1, -3*I],
[2 - I,   -I]])
```

**Comment by Roland-Sands** [comment]
That means that it is implemented twice, for in the physics part the operation is called dagger

**Comment by evatiwari** [comment]
There is a separate implementation for dagger in ```physics.quantum```, because the ```.H``` function is not an attribute of the Bra and Ket objects. I think this issue could be closed.
