### ISSUE TITLE
log(I**I)

### ISSUE THREAD

**Issue by sidhantnagpal** [sympy/sympy#14262]
```
>> pprint(simplify(log(I**I)))
   ⎛ ⅈ⎞
log⎝ⅈ ⎠

>> pprint(simplify(log(I**I)).expand(complex=True))
               ⎛ ⅈ⎞      ⎛│ ⅈ│⎞      
- ⅈ⋅π⋅Heaviside⎝ⅈ ⎠ + log⎝│ⅈ │⎠ + ⅈ⋅π
```
#### Expected Result
```
 -π 
 ───
  2  
```
#### Related Issues
#7569 - simplify should call expand_complex
#13288 - Improve simplification

**Comment by normalhuman** [comment]
I also expected `(I**I).rewrite(exp)` to return `exp(-pi/2)`.

**Comment by sidhantnagpal** [comment]
Yes, though `log(I**I).evalf()` and `(I**I).is_real` print the correct value.

**Comment by abaokar-07** [comment]
@normalhuman I think we have to add that if the argument of log is complex and has powers, then return the expected value
for example
`>>> simplify(log(I**I)).expand(complex=True)
-pi/2
>>> simplify(log(I**(3*I))).expand(complex=True)
-3*pi/2`
i.e. , depending on the coefficient of `I` which is in the power

**Comment by abaokar-07** [comment]
@normalhuman   I think we have to add that if the argument of log is complex and has powers, then return the expected value
for example
`>>> simplify(log(I**I)).expand(complex=True)`
`-pi/2`
`>>> simplify(log(I**(3*I))).expand(complex=True)`
`-3*pi/2`
i.e. , depending on the coefficient of the `I` which is present in the power
