### ISSUE TITLE
Rational(a/b) returns a rational rather than an error

### ISSUE THREAD

**Issue by Roland-Sands** [sympy/sympy#14272]
```
>>> Rational(7/8)
7/8
>>> Rational(8/7)
2573485501354569
────────────────
2251799813685248
```

**Comment by andrewrocks** [comment]
Personally I like this behaviour, because it calculates rationals from floats for me.

```python
>>> Rational(0.5)
1/2
>>> Rational(0.24)
1080863910568919/4503599627370496
```

**Comment by asmeurer** [comment]
This is indeed intended behavior. Getting a rational from a float is a real use-case. Note that SymPy has no way to differentiate `Rational(8/7)` and `Rational(1.1428571428571428)`.

**Comment by normalhuman** [comment]
[Documentation](http://docs.sympy.org/dev/modules/core.html#rational) is clear on this point:

> Rational is unprejudiced in accepting input. If a float is passed, the underlying value of the binary representation will be returned
