### ISSUE TITLE
"ntheory", is that a better folder name than "number_theory" and "arithmetic"

### ISSUE THREAD

**Issue by Roland-Sands** [sympy/sympy#14287]

**Comment by ArighnaIITG** [comment]
Can you elaborate?

**Comment by moorepants** [comment]
It may not be a better name but it is not worth changing it because it will break the API.

**Comment by asmeurer** [comment]
I never had a problem with the ntheory name. If we were starting from scratch I might prefer number_theory, but as it is, it's already part of the API, and we don't take [API breakages](https://github.com/sympy/sympy/wiki/Deprecating-policy) lightly.
