### ISSUE TITLE
lambdify(sympy.abc.a, sympy.abc.a / 0 , "numpy") gives NameError

### ISSUE THREAD

**Issue by jsharkey13** [sympy/sympy#14283]
When using `lambdify(...)` with `"numpy"` as the module, if the expression involves the complex infinity `zoo` symbol then the result cannot subsequently be evaluated because a NameError is thrown.

A minimum working example:
```python
import sympy
import sympy.abc

expr = sympy.abc.a / 0
func = sympy.lambdify(sympy.abc.a, expr, "numpy")
eval_func = func(1)

print eval_func
```
gives
```
NameError: global name 'zoo' is not defined
```
from the line `eval_func = func(1)`.

Note that if `expr = sympy.oo` or `expr = sympy.oo * sympy.abc.a` instead, we get `inf` as the result; this makes sense.

This unhandled exception can be avoided by doing
```python
from sympy.utilities.lambdify import NUMPY_TRANSLATIONS
NUMPY_TRANSLATIONS["zoo"] = "nan"
```
first, which ensures `sympy` can map the `zoo` in the same way it already maps `oo`. The issue is what exactly `zoo` should map to and whether `nan` is appropriate, which may explain why it has not been mapped already? Since `numpy` has no corresponding complex infinity, surely `nan` is better than an unhandled exception?

**Comment by ArighnaIITG** [comment]
@jsharkey13 , I am taking this up.
Does this consist of only these changes in `sympy.utilities.lambdify.py` ?

```
-NUMPY_TRANSLATIONS = {}
+NUMPY_TRANSLATIONS = {
+    "zoo": "nan",
+}
```
By following this `git diff` methodology , we get --

```
>>> from sympy import *
>>> x = symbols('x')
>>> expr = x/0
>>> func = lambdify(x, expr, "numpy")
>>> func(1)
nan

```

Is there more to it? And what tests should be added?
`Assert` will not work because mapping will create `Assertion Error`.

**Comment by asmeurer** [comment]
The change should be made to the numpy printer. 

I guess printing nan for zoo makes the most sense. I don't know if there's any other reasonable thing to do with it.

**Comment by jsharkey13** [comment]
@ArighnaIITG, I think my proposed solution only works in versions `1.0` through `1.1.1` and that everything has been changed on master now.

I can't see how [`NumPyPrinter`](https://github.com/sympy/sympy/blob/master/sympy/printing/pycode.py#L289) or its parents deal with `oo` any longer, but I can confirm that the NameError for `zoo` is still thrown on master.

**Comment by asmeurer** [comment]
One would just need to add `_print_zoo` as a method to the printer, which returns `'nan'`.

**Comment by jsharkey13** [comment]
Whilst investigating further, I discovered that the same issue exists also for Negative Infinity.
(If `expr = sympy.oo * -1` above it gives `NameError: global name 'oo' is not defined`).

The following two methods fix this issue if added to both `MpmathPrinter` and `NumPyPrinter` in `sympy.printing.pycode`.

```python
 def _print_NegativeInfinity(self, expr):
    return "-inf"

def _print_ComplexInfinity(self, expr):
    return "nan"
```
Would it make more sense to just add them to the parent class `PythonCodePrinter` instead? It turns out that this is where `oo` is dealt with (by `_print_Infinity(...)`). They need to return something slightly different in this case, but it's the same behaviour:
```python
 def _print_NegativeInfinity(self, expr):
    return "float('-inf')"

def _print_ComplexInfinity(self, expr):
    return "float('nan')"
```
Or is it better to just add them to the NumPy and mpmath printers individually?

**Comment by jashan498** [comment]
Adding these methods to `PythonCodePrinter` should make more sense as behaviour for both these sub-classes is same on this (also, as far as I know, `PythonCodePrinter` is inherited only by these two classes).

**Comment by ArighnaIITG** [comment]
I also believe that adding the above methods in the `PythonCodePrinter` class sholud be meaningful. This can prevent future APIs, which might inherit `PythonCodePrinter`, to render the above `NameError` in both the negative and complex infinity. This might be a safe bet.
Also, I guess modifying the parent method is always preferable.
@asmeurer , views?
