### ISSUE TITLE
Sign of generator of an algebraic numberfield

### ISSUE THREAD

**Issue by jksuom** [sympy/sympy#14289]
`AlgebraicField` calls [`to_number_field`](https://github.com/sympy/sympy/blob/master/sympy/polys/domains/algebraicfield.py#L33) in order to create an `AlgebraicNumber` generating the extension field. This number is chosen positive in some cases where the sign can be determined.  This choice is currently implemented, at least in part, when the algebraic number is [created](https://github.com/sympy/sympy/blob/master/sympy/core/numbers.py#L2390), but the implementation is defective as it does not change the minimal polynomial.
```
>>> b = 1 - sqrt(2)
>>> a = to_number_field(b)
>>> a
-1 + sqrt(2)  # positive generator created
>>> minimal_polynomial(b)
_x**2 - 2*_x - 1  # this is correct
>>> minimal_polynomial(a)
_x**2 - 2*_x - 1  # but this is wrong, apparently copied from a.minpoly
>>> a.minpoly
PurePoly(_x**2 - 2*_x - 1, _x, domain='QQ')
>>> minimal_polynomial(-1 + sqrt(2))
_x**2 + 2*_x - 1  # this is the correct minimal polynomial of a
```
I think this could be fixed in two ways:
* Add code to create the changed minimal polynomial.
* Ignore the sign and remove the code changing it.

I am inclined to prefer the latter, simpler solution, but I would also like to hear other suggestions.

**Comment by skirpichev** [comment]
In the Diofant:
```python
n [11]: b = 1 - sqrt(2)

In [12]: a = to_number_field(b)

In [13]: a.root
Out[13]: 
    ___    
- ╲╱ 2  + 1

In [14]: a.minpoly
Out[14]: PurePoly(_x**2 - 2*_x - 1, _x, domain='ZZ')

In [15]: a.coeffs()
Out[15]: [1, 0]
```
I think, that's correct.  C.f. with Sympy:
```
In [7]: b = 1 - sqrt(2)

In [8]: a = to_number_field(b)

In [9]: a
Out[9]: -1 + √2

In [10]: a.root
Out[10]: -√2 + 1

In [11]: a.coeffs()
Out[11]: [-1, 0]

In [12]: a.minpoly
Out[12]: PurePoly(_x**2 - 2*_x - 1, _x, domain='QQ')
```

**Comment by jksuom** [comment]
That looks like the sign change was removed? I think that the sign should be the ignored in SymPy as well.

**Comment by vishalg2235** [comment]
I don't know in deep but yes. I think the sign should be ignored(but maybe this property is used somewhere) as the number must retain its original sign.

well I found
```
>>> a.args
(-sqrt(2) + 1, (-1, 0))
```
and as done [here](https://github.com/sympy/sympy/blob/master/sympy/core/numbers.py#L2406) the `minpoly` of `obj` (`a` here) is `minimal_polynomial` of `b`.

We can also check type of `a` [here](https://github.com/sympy/sympy/blob/master/sympy/polys/numberfields.py#L640) and then return the minimal polynomial of `a.args[0]*a.args[1][0]`.
```
>>> minimal_polynomial(a.args[0]*a.args[1][0])
_x**2 + 2*_x - 1
```

**Comment by skirpichev** [comment]
> That looks like the sign change was removed?

@jksuom, apparently so.

> We can also check type of a here and then return the minimal polynomial of a.args[0]*a.args[1][0]

Great idea!  But why not ``a.args[0]*a.args[1][42]``?

**Comment by vishalg2235** [comment]
a.args[1] has only two index 0 and 1. a.args[1][0] will be 1 for positive root and -1 for negative root.([here](https://github.com/sympy/sympy/blob/master/sympy/polys/numberfields.py#L640)) . 

Should I add a PR to remove the sign change?

**Comment by skirpichev** [comment]
> a.args[1] has only two index 0 and 1

How did you know that?

**Comment by vishalg2235** [comment]
Yes! Sorry my fault `len(sarg)` [here](https://github.com/sympy/sympy/blob/master/sympy/core/numbers.py#L2399) could be more than 2 if `alias` is present.

@skirpichev the PR you referenced seem to be of 'diofant' repository. can I open a PR to remove sign change of `a` when it negative in sympy. ?

**Comment by skirpichev** [comment]
> Sorry my fault len(sarg) here could be more than 2 if alias is present.

Wow!

> can I open a PR

Sure.
