### ISSUE TITLE
Assertion fails for identical expressions

### ISSUE THREAD

**Issue by akash9712** [sympy/sympy#14288]
```
>>> from sympy import *
>>> from sympy.stats import *
>>> Y = Poisson('Y', 4)
>>> P(Y > 3) == (32*(-S(71)/32 + 3*exp(4)/32)*exp(-4)/3)
False
>>> P(Y > 3).equals(32*(-S(71)/32 + 3*exp(4)/32)*exp(-4)/3)
True 
```
This issue came up while writing the tests for `probability` in drv.py. (Refer to [these comments](https://github.com/sympy/sympy/pull/14119/files/ec2766ff35ca3e979a39cdcd2a5c8e81d23d50fa#r167012288) )

**Comment by smichr** [comment]
The expressions are not identical. As @normalhuman said, 'str printer produces a more readable form of the expression' so it's not WYSIWYG in terms of the underlying expression. I suspect that this is the autodistribution of the 32 on the expression. Try ((-S(71)/32 + 3*exp(4)/32)*exp(-4))/3*32` instead.

**Comment by akash9712** [comment]
@smichr Thanks. This expression works.
Also, is this still an issue? The value shown as the return value on the python interpreter should evaluate as being equal to the actual return value of the function.

**Comment by smichr** [comment]
> value shown as the return value on the python interpreter

If you mean that if you see the same thing in response to an entry made at the interpreter and the output of a function, then "yes", they *should* be the same but there have been some bugs (or printing issues?) that have made this not true.

This is a well-known issue, the auto-expansion of the 2-arg Mul. The simplest example is `-(1 + x)` which will become `-1 - x`. In this case, there is no arg-fiddling possible. To get the first expr you have to use `Mul(-1, 1 + x, evaluate=False)` But if there is more than two args and the first two in the printed expression are a Number and Add then you can defeat the auto-expansion by permuting factors so the first two are *not* the Number and Add, e.g. `x*(1+y)*2` or `x*2*(1+y)` or `2*x*(1+y)` but not `2*(1+y)*x` will give a Mul with 3 factors.

I will close this.
