### ISSUE TITLE
Units are not simplified with simplify()

### ISSUE THREAD

**Issue by KOLANICH** [sympy/sympy#14281]
```python
from sympy.physics.units import *
(cm/mm).simplify()
```

expected `10`
got `centimeter/millimeter`

**Comment by bjodah** [comment]
I wouldn't call that badly broken, just a missed simplification opportunity. In the meantime you can use this:
```
In [8]: convert_to(cm/mm, 1)
Out[8]: 10.0000000000000
```
If you want you can try to implement a `_eval_simplify` method for `sympy.physics.units.quantities.Quantity`. Feel free to ping me in a pull request.

**Comment by abaokar-07** [comment]
@bjodah I would like to take this up

**Comment by abaokar-07** [comment]
@bjodah I would like to take this up

**Comment by Subhash-Saurabh** [comment]
Another issue related to mul/div  in units package
```
>>> 2*kilogram/(5*kilo*gram)
2*kilogram*Prefix(kilo, k, 3, 10)**(-1)/(5*gram)
```
Expected -> `0.6`

With `convert_to`
```
>>> convert_to(2*kilo*gram, kilogram)
kilogram*Prefix(kilo, k, 3, 10)/500

>>> convert_to(2*kilo*gram/kilogram,1)
0.002*Prefix(kilo, k, 3, 10)
```

**Comment by Kreijstal** [comment]
> Another issue related to mul/div in units package
> 
> ```
> >>> 2*kilogram/(5*kilo*gram)
> 2*kilogram*Prefix(kilo, k, 3, 10)**(-1)/(5*gram)
> ```
> 
> Expected -> `0.6`
> 
> With `convert_to`
> 
> ```
> >>> convert_to(2*kilo*gram, kilogram)
> kilogram*Prefix(kilo, k, 3, 10)/500
> 
> >>> convert_to(2*kilo*gram/kilogram,1)
> 0.002*Prefix(kilo, k, 3, 10)
> ```

I get the exact same thing, how are you supposed to stop getting the Prefix after convert_to?
