### ISSUE TITLE
poly(((x - 1)**2 + 1)*((x - 1)**2 + 2)*(x - 1)).all_roots() hangs

### ISSUE THREAD

**Issue by skirpichev** [sympy/sympy#14291]
bisected to 73fafba

**Comment by vishalg2235** [comment]
I found that the infinite loop occurs [here](https://github.com/sympy/sympy/blob/master/sympy/polys/rootoftools.py#L323). I am having some difficulty in understanding the code/work of this function. @skirpichev  @jksuom can you show me some examples that what `_refine_complexes` do ?

**Comment by smichr** [comment]
> what _refine_complexes do

Isn't this the routine that tries to locate each root within a rectangle that is horizontally and vertically distinct from every other root's rectangle?

**Comment by smichr** [comment]
The problem is that the complex roots of two equations may share the same real value so the roots will never be isolated to satisfy the assumptions of the routine (which wrongly assumed this would not be the case).

**Comment by vishalg2235** [comment]
@smichr I couldn't locate where in code it is checking the same real value of roots? please help!
And `complexes` in _refine_complexes() is:
```
[((0, 6) x (-6, 0), Poly(x**2 - 2*x + 3, x, domain='ZZ'), 1), ((0, 6) x (0, 6), Poly(x**2 - 2*x + 3, x, domain='ZZ'), 1), ((0, 4) x (-4, 0), Poly(x**2 - 2*x + 2, x, domain='ZZ'), 1), ((0, 4) x (0, 4), Poly(x**2 - 2*x + 2, x, domain='ZZ'), 1)]
```
What are those `(0, 6)`, `(0, -6)`?

**Comment by skirpichev** [comment]
> The problem is that the complex roots of two equations may share the same real value

Oh, again wrong (:  Complex roots of one equation may share the same real part (actually, we care about different conjugated pairs of roots, if coefficients of the equation are real).

BTW, @vishalg2235, I wonder what you did to "locate where in code it is"?

**Comment by vishalg2235** [comment]
@skirpichev I was trying to understand `_refine_complexes()` but couldn't understand what logic is applied here. Can you please get me more familiar with this code ?
