### ISSUE TITLE
Wrong latex output for fraction with a sqrt

### ISSUE THREAD

**Issue by Zeleznyj** [sympy/sympy#14309]
Latex output for some fractions, which involve a square root is wrong:
```
In [2]: x = sympy.symbols('x') 

In [4]: sympy.latex((2*sympy.sqrt(2)*x)/3)
Out[4]: '\\frac{2 x}{3} \\sqrt{2}'
```
The square root is incorrectly taken out of the fraction.
Without the variable x, the output is correct:
```
In [8]: sympy.latex(2*(sympy.sqrt(2))/3)
Out[8]: '\\frac{2 \\sqrt{2}}{3}'
```

 Tested on sympy version 1.1.1.

**Comment by jashan498** [comment]
setting `long_frac_ratio = 3` (ratio of number of terms in num to that in denom) should do the trick.
```
>>>latex((2*sqrt(2)*x)/3,  long_frac_ratio=3)
'\\frac{2 \\sqrt{2} x}{3}'
```

**Comment by asmeurer** [comment]
Even so, it would be nice for the LaTeX printer and the pretty printer to be consistent here. 

```
>>> pprint((2*sympy.sqrt(2)*x)/3)
2⋅√2⋅x
──────
  3
```

**Comment by jashan498** [comment]
Without above flag, it's not possible to have more than twice the terms in numerator than in denominator.
```
>>> pprint((a*b*c*d)/e)
a⋅b⋅c⋅d
───────
   e   

>>> latex((a*b*c*d)/e)
'\\frac{a b}{e} c d'
```
Should this rule in latex printer be changed? Why even is it required to have fixed number of terms in the numerator?

**Comment by normalhuman** [comment]
I agree: moving terms out from the numerator should not just happen by default. Changing `(a*b*c*d)/e` to `\frac{a b}{e} c d' is not always desirable.
