### ISSUE TITLE
The series (1/2)**floor(n/2) is reported as divergent

### ISSUE THREAD

**Issue by normalhuman** [sympy/sympy#14313]
In current master:
```
>>> var('n')
>>> Sum((S(1)/2)**floor(n/2), (n, 1, oo)).is_convergent()
False
```
The series actually converges.

**Comment by gxyd** [comment]
Just a question, wouldn't it better if we tag this as 'concrete' instead of 'series'? I remember may be I also tagged one `Sum` related issue as 'series' instead of 'concrete' (but I don't remember which).

**Comment by normalhuman** [comment]
Good point. `is_convergent` is a method of Sum, and Sum is in concrete. Even though the content of `is_convergent` is mostly about limits and not so much about concrete summation.  I'll fix the labels.

**Comment by maurogaravello** [comment]
This is due to the fact that `limit(floor(n/2), n, oo)` returns `floor(zoo)` instead of `oo`. Consequently, in the `is_convergent()` test of `Sum`, the following code returns `S.false`
```
        ###  -------- Divergence test ----------- ###
        try:
            lim_val = limit(sequence_term, sym, upper_limit)
            if lim_val.is_number and lim_val is not S.Zero:
                return S.false
```
Indeed, `lim_val` is `2**(-floor(zoo))` and `lim_val.is_number = True`.
