### ISSUE TITLE
Units: deprecate arguments "dimension" and "scale_factor" in Quantity

### ISSUE THREAD

**Issue by Upabjojr** [sympy/sympy#14319]
See https://github.com/sympy/sympy/issues/14318

**Comment by Upabjojr** [comment]
https://github.com/sympy/sympy/pull/14322

**Comment by asmeurer** [comment]
How about a PR improving the useinstead?

**Comment by asmeurer** [comment]
The plan is to do a 1.3 release in September, so we should improve any messaging for deprecations before then.

**Comment by asmeurer** [comment]
I'm planning on starting the 1.3 release branch tomorrow. If you want to improve the messaging for that release, please let me know ASAP.

**Comment by Davide-sd** [comment]
May I ask what is the reasoning behind the choice of moving from a nice one-liner:

```
l1 = Quantity('l1', length, meter) 
``` 

to:

```
l2 = Quantity('l2')
l2.set_dimension(length)
l2.set_scale_factor(meter)
```

**Comment by Upabjojr** [comment]
> May I ask what is the reasoning behind the choice of moving from a nice one-liner:

Dimensions and scale factors are not always universally defined.

For example, is the speed of light's dimension length/time or dimensionless? Same problem with SI and CGS units for electromagnetism, dimensions and scale factors are not the same for the same quantities.

**Comment by schymans** [comment]
Actually, to avoid that everyone has to refactor their code, how about still allowing the l1 = Quantity('l1', length, meter) notation but stating explicitly that this does the below behind the scenes? I know that doing things implicitly is not the best practice, but breaking backwards-compatibility also is not. And whoever used the old notation most likely had SI in mind anyway.
```
l2 = Quantity('l2')
SI.set_quantity_dimension(l2, length)
SI.set_quantity_scale_factor(l2, meter)
```

**Comment by Upabjojr** [comment]
It's been sending warnings since SymPy version 1.3. I am currently not working on the units module, so it's likely this warning will remain a few more versions.

I'm sorry about the change but this was an API design mistake.

**Comment by schymans** [comment]
OK, for those not wanting to refactor all their code, this might work:
```
def Quantity(name, dimension, scale_factor):
    """Re-defined Quantity for SI units"""
    from sympy.physics.units.systems import SI
    import sympy.physics.units.Quantity as sp_Quantity
    Q1 = sp_Quantity(name)
    SI.set_quantity_dimension(Q1, dimension)
    SI.set_quantity_scale_factor(Q1, scale_factor)
    return Q1
```
Sorry, can't test it right now, as I'm on a computer without python.
