### ISSUE TITLE
Improper results with inverse trigonometric functions

### ISSUE THREAD

**Issue by sidhantnagpal** [sympy/sympy#14320]
```python
>>> pprint(asin(sin(2)))
asin(sin(2))

>>> pprint(asin(sin(2)).simplify())
2

>>> pprint(asin(sin(2)).trigsimp())
asin(sin(2))
```
Using simplify, does not give the correct value as range of `asin` is `[-pi/2,pi/2]`. 
The other statements are not able to solve the same expression.

Having the ability to solve non-symbolic expressions involving compatible trigonometric functions would be useful.

**Comment by jksuom** [comment]
This was recently discussed on gitter. The attribute `inverse` does not differentiate between right inverse and left inverse. Therefore [this line](https://github.com/sympy/sympy/blob/master/sympy/simplify/simplify.py#L531) may lead to a wrong result.

**Comment by sidhantnagpal** [comment]
> The attribute inverse does not differentiate between right inverse and left inverse.

Yes, as you mentioned the line that leads to wrong result is integral to simplify. 
Reduction by inverse trigonometric functions themselves, would be useful in such cases, I think.
