### ISSUE TITLE
Fix args of Quantity.__new__ before release of SymPy 1.2

### ISSUE THREAD

**Issue by Upabjojr** [sympy/sympy#14354]
Recently, `Quantity(name, dim, scale, abbrev)` was changed to `Quantity(name, abbrev, dim, scale)` with the last two being deprecated.

Make sure that `Quantity(name, dim, scale, abbrev)` still works.

**Comment by asmeurer** [comment]
This should be easy to fix. If the second argument is not a string, interpret the arguments in the old way, with a deprecation warnings. 

By the way, the "feature" flag of the deprecation warnings should indicate which flags are actually deprecated.

**Comment by RavicharanN** [comment]
@asmeurer Reordering might cause problems, 'cause the unit tests are written such that Quantity takes only 2 arguments (name, abbrev). When dimension is passed as the second argument and is reordered, it throws a deprecation warning and the tests fail. 
Is it suggestable to skip the tests when the second argument is not a string?
