### ISSUE TITLE
Move set arithmetic operators to sympy/sets/sets.py

### ISSUE THREAD

**Issue by Upabjojr** [sympy/sympy#14366]
Set arithmetic operators such as `set_add` and the function application on sets (`set_function`) have been defined in `sympy/sets/setexpr.py` to support `SetExpr`.

They are actually of generic use for all sets, so they should rather stay in `sympy/sets/sets.py`.

**Comment by Upabjojr** [comment]
Let's do it before version 1.2, so no API break.

**Comment by abaokar-07** [comment]
Do we have to move all the set arithmetic operators?

**Comment by czgdp1807** [comment]
I am beginner, can I work on this?

**Comment by bhaveshpoddar94** [comment]
Beginner here. Can I look into this issue?
