### ISSUE TITLE
Invalid NaN comparison error in integrate(exp(I*x)*log(x), x)

### ISSUE THREAD

**Issue by normalhuman** [sympy/sympy#14375]
```
var('x')
integrate(exp(I*x)*log(x), x)
```
throws TypeError: Invalid NaN comparison. 

Both `exp(x)*log(x)` and `exp(2*I*x)*log(x)` are integrated successfully.

**Comment by jksuom** [comment]
Apparently SymPy `Or` tries to evaluate all arguments even if the first one is `False`.
```
> /home/jks/sympy/sympy/integrals/meijerint.py(1017)_check_antecedents()
-> Or(And(Ne(zos, 1), abs(arg_(1 - zos)) < pi),
(Pdb) p arg_(1 - zos)
nan
(Pdb) p 1 - zos
0
(Pdb) p zos
1
```

**Comment by normalhuman** [comment]
Good point, though it's not `Or`s fault, Python evaluates all arguments before passing them to a function.
