### ISSUE TITLE
Dsolve gives the answer in terms of integral

### ISSUE THREAD

**Issue by proy87** [sympy/sympy#14395]
`dsolve(Derivative(f(x), x, x) + 9*f(x)-sec(x), f(x))` gives `Eq(f(x), (C1 - Integral(sin(3*x)*sec(x), x)/3)*cos(3*x) + (C2 + Integral(cos(3*x)*sec(x), x)/3)*sin(3*x))`, but the answer can be expressed in terms of elementary functions.

**Comment by normalhuman** [comment]
dsolve does the right thing, the issue is with `integrate`, which is unable to handle these trigonometric integrals. 
```
>>> integrate(sin(3*x)*sec(x), x)
Integral(sin(3*x)*sec(x), x)
>>> integrate(cos(3*x)*sec(x), x)
Integral(cos(3*x)*sec(x), x)
```
The antiderivative is indeed elementary, and particularly simple in the second case. Looks like something that `manualintegrate` should do.
