### ISSUE TITLE
[Geometry] Improvements to Curves

### ISSUE THREAD

**Issue by AlexKaracaoglu** [sympy/sympy#14399]
Currently Curves are restricted to 2 dimensional Euclidean space. Adding on support for higher dimension curves wouldn't be too difficult and would allow for us to get the Frenet Frame of 3 dimensional curves. I would be willing to add this on if people think this would be a good idea

**Comment by woodscn** [comment]
I do think this would be a good idea, and I'm disappointed that the PR got dropped. Any chance this will be resurrected?
