### ISSUE TITLE
Incorrect improper integral evaluation

### ISSUE THREAD

**Issue by proy87** [sympy/sympy#14400]
I noticed that in a bunch of cases sympy incorrectly evaluates integrals.
One such example is `integrate(1/(1-x**2),(x,0,3))`. The integral is divergent, but sympy gives `-log(2)/2 + log(4)/2 + I*pi/2`.

The result is also not simplified, since `log(4)=2log(2)`.

**Comment by normalhuman** [comment]
This has been corrected recently. In the current master branch, 
```
>>> integrate(1/(1-x**2), (x,0,3))
nan
```
