### ISSUE TITLE
limit(3*sec(4*pi*x-x/3), x, 3*pi/(-2 + 24*pi)) raises IndexError

### ISSUE THREAD

**Issue by proy87** [sympy/sympy#14411]
`limit(3*sec(4*pi*x-x/3), x, 3*pi/(-2 + 24*pi))` IndexError: tuple index out of range

**Comment by jksuom** [comment]
In `fu.TR3`:

    def f(rv):
        if not isinstance(rv, TrigonometricFunction):
            return rv
        rv = rv.func(signsimp(rv.args[0]))
        if (rv.args[0] - S.Pi/4).is_positive is (S.Pi/2 - rv.args[0]).is_positive is True:
            fmap = {cos: sin, sin: cos, tan: cot, cot: tan, sec: csc, csc: sec}
            rv = fmap[rv.func](S.Pi/2 - rv.args[0])
        return rv

`signsimp` turns `rv` into a number. Probably the instance test should be repeated.

**Comment by Nikhilkoneru** [comment]
I would like to work on this issue.can I proceed?

**Comment by normalhuman** [comment]
@Nikhilkoneru There is already a PR for this issue, see the link above your message.
