### ISSUE TITLE
physics.mechanics mpprint doesn't work with some greek letters

### ISSUE THREAD

**Issue by ngoonee** [sympy/sympy#14425]
from sympy import diff
    from sympy.physics.mechanics import dynamicsymbols, mpprint
    mpprint(diff(dynamicsymbols('a')))
    mpprint(diff(dynamicsymbols('b')))
    mpprint(diff(dynamicsymbols('o')))
    mpprint(diff(dynamicsymbols('alpha')))
    mpprint(diff(dynamicsymbols('beta')))
    mpprint(diff(dynamicsymbols('theta')))

The first 3 lines print as expected, the characters a, b, and o with dot notation above. The latter 3 lines just print the alpha/beta/theta characters without any dot.

**Comment by jksuom** [comment]
mpprint seems to return correct unicode characters.
```
>>> mpprint(diff(dynamicsymbols('alpha')))
u'\u03b1\u0307'  # Greek alpha and combining dot above
```
The printed output probably depends on the available character set. (There may be 'a with dot above' but no 'alpha with dot above'.)

**Comment by moorepants** [comment]
@jksuom is correct, I don't think there are unicode symbols for this. But maybe it should return d alpha / dt instead so that there is no confusion.

**Comment by ngoonee** [comment]
With more testing it also depends what fontset is being used (obviously).

I think I'll either default to latex output or just restrict my code to using simple characters rather than the standard theta/alpha that my problem domain uses.

@moorepants that does make sense, and makes this sorta-kinda related to this? - https://github.com/sympy/sympy/issues/10173

**Comment by lilithxxx** [comment]
> I don't think there are unicode symbols for this

@moorepants there are Unicode characters available for this like aplha with a dot and so. I have made a PR regarding this(https://github.com/sympy/sympy/pull/14447). Please review.

**Comment by ngoonee** [comment]
@lilithxxx I tested making just that change on sympy 1.1.1 in my venv, and it doesn't seem to help in this situation:-

    a = dynamicsymbols('alpha')
    mpprint(a)  # prints the standard alpha symbol
    mpprint(diff(a))  # prints 'None'
    a  # Raises TypeError: object of Type 'NoneType' has no len()

The last line at least indicates that there's probably something else which needs to be done.

**Comment by lilithxxx** [comment]
This is the current behavior in my ipython shell:
```
In [1]: from sympy.physics.mechanics import *

In [2]: from sympy import *

In [3]: a = dynamicsymbols('alpha')

In [4]: mpprint(a)
α

In [5]: mpprint(diff(a))
α̇

In [6]: a
Out[6]: alpha(t)
```
There seems to be no issue related to mpprint @ngoonee

**Comment by ngoonee** [comment]
Odd, my ipython gives me this:-

    In [1]: from sympy.physics.mechanics import *

    In [2]: from sympy import *

    In [3]: a = dynamicsymbols('alpha')

    In [4]: mpprint(a)
    Out[4]: 'α'

    In [5]: mpprint(diff(a))
    Out[5]: 'α̇'

    In [6]: a
    Out[6]: alpha(t)
I get the same result when running a python script in shell. What font set do you use? (I use DejaVu Sans Mono)

**Comment by oscargus** [comment]
It seems like sometime the combining accent is combined with the preceeding character, sometimes with the proceeding. 

```
d = u"\N{COMBINING DIAERESIS}"

'ω' + d + 'ω'
Out[94]: 'ω̈ω'

'a' + d + 'a'
Out[95]: 'äa'
```
So it is not really consistent it seems.

Another interesting case:

```
' ' + d +'a'
Out[103]: ' ̈a'
```

(it is also worth noting that the diaresis is in different positions in the editor compared to the preview...)

**Comment by oscargus** [comment]
As I've read up more on this now. The combining accent (or combining diacritical mark as it should be called) is added after the character it is should be applied to in Python. However, as evident above, it is up to the terminal to render this correctly.

One can also note that one do not need a font for the combined character, only for the separate ones, as they will be rendered "on top" of each other. Hence, there is a difference between the character ä and the combined character a + ¨ = ä, which is only visible once actually examining the coding of the string.

From what I have seen so far in the code, it does the correct thing. It is just that the terminal doesn't always render it correctly. (Hence, the examples I posted above may look like nonsense if they actually are rendered correctly and not as in my browser and Spyder, to various degrees though.)

I will try to double-check this issue, but most likely there is nothing to be done, except for possibly adding a space afterwards if the last character is a combining accent, which seems to help in certain terminals.

**Comment by faze-geek** [comment]
What is there to work on this issue ,probably @moorepants can clarify in detail .

The example this issue was opened for
```
>>> from sympy.physics.mechanics import *
>>> from sympy import *
>>> a = dynamicsymbols('alpha')
>>> mpprint(a)
'α'
>>> mpprint(diff(a))
'α̇ ' # added space manually because of less terminal font hence ouput as expected.
>>> a
alpha(t)
```
The combining accent is now consistent-
Examples on master -
```
>>> d = u"\N{COMBINING DIAERESIS}"
>>> 'ω' + d + 'ω'
>>> 'a' + d + 'a'
>>> ' ' + d +'a'
```
Showing screen shots due to low font -

<img width="126" alt="Gsoc" src="https://user-images.githubusercontent.com/90216905/160234238-09936d20-40c7-4726-97e2-a6fe4acaf96a.png">

**Comment by oscarbenjamin** [comment]
I think this can just be closed now. It's a bug in various fonts. Even here if I paste this into the GitHub website:
```
In [9]: mpprint(diff(a))
Out[9]: 'α̇'

In [10]: print(mpprint(diff(a)))
α̇
```
I get a correct display in the "write" pane but in the "preview" pane the dot is printed to the right.
