### ISSUE TITLE
Avoid indeterminations

### ISSUE THREAD

**Issue by DavidArmendariz** [sympy/sympy#14441]
So my question is the following. Suppose I want to integrate the following function. 

    x,t,x0,x1,x2=symbols('x t x0 x1 x2')
    f=t*x1*x2
    r=integrate(f, t).subs(Abs(t/x)>1, False).simplify()
The integral is

    r=2*sqrt(x)*x1*x2*(t**2*sqrt((-t + x)/x) + t*x*sqrt((-t + x)/x) - 2*t*x - 2*x**2*sqrt((-t + x)/x) + 2*x**2)/(3*(-t + x))
However, this form is not convenient for me because when you simplify this expression further, you get
`   -(2/3) Sqrt[x] (-2 x + Sqrt[1 - t/x] (t + 2 x)) x1 x2`
And you don't have problems when substituing `t` with `x`. How con I avoid this indetermination with `r`?

**Comment by smichr** [comment]
This gives `t**2*x1*x2/2` in which there is no Abs. Please reopen if there is more information.
