### ISSUE TITLE
Limits at complex infinity are sometimes interpreted as limits at oo or -oo

### ISSUE THREAD

**Issue by normalhuman** [sympy/sympy#14456]
```
>>> var('z')
>>> limit(z**2/(z+1), z, zoo)
oo    # this is the limit at oo, not at zoo 
>>> limit(exp(z), z, zoo)
0      # this is the limit at -oo, not at zoo
```

The former behavior comes from ["all ok" branch](https://github.com/sympy/sympy/blob/master/sympy/series/limits.py#L193), which groups zoo with oo.
```
                    if z0 is S.NegativeInfinity:
                        inve = e.subs(z, -1/u)
                    else:    # both oo and zoo go here
                        inve = e.subs(z, 1/u)
```
The latter comes from [heuristics](https://github.com/sympy/sympy/blob/master/sympy/series/limits.py#L73), which groups zoo with -oo.  
```
    if abs(z0) is S.Infinity:
        rv = limit(e.subs(z, 1/z), z, S.Zero, "+" if z0 is S.Infinity else "-")
```

Possible solutions: 

1. Limit at zoo raises NotImplementedError
2. Limit at zoo is evaluated as a parametric limit, [as suggested here](https://github.com/sympy/sympy/issues/8341#issuecomment-371641653).

**Comment by asmeurer** [comment]
I think it should be an error for now. If we have a general way to make complex limits work, we can perform `lim(f(x), x, zoo)` as `complex_limit(f(1/x), x, 0)`. But my understanding is that right now we don't (my full understanding of what is implemented here is limited (no pun intended), so if there is more here someone please correct me). 

See also https://github.com/sympy/sympy/issues/8320.
