### ISSUE TITLE
sympy solve

### ISSUE THREAD

**Issue by proy87** [sympy/sympy#14479]
`solve([1024*pi**2*x**2 - 4096*pi**2*x + 9*y**2 - 72*y - 432 + 4096*pi**2, 18*y - 72])` raises `sympy.polys.polyerrors.NotAlgebraic: pi doesn't seem to be an algebraic element`

It seems that it can't construct the polynom: `poly = g.as_poly(*symbols, extension=True)`.

Indeed, `(pi**2*x).as_poly(x,y,extension=True)` raises the same error.

**Comment by normalhuman** [comment]
In current master branch:
```
>>> from sympy import *
>>> var('x y')
(x, y)
>>> solve([1024*pi**2*x**2 - 4096*pi**2*x + 9*y**2 - 72*y - 432 + 4096*pi**2, 18*y - 72])
[{x: (-3 + 8*pi)/(4*pi), y: 4}, {x: (3 + 8*pi)/(4*pi), y: 4}]
```

Also, 
```
>>> (pi**2*x).as_poly(x,y,extension=True)
Poly(pi**2*x, x, y, domain='ZZ[pi]')
```
