### ISSUE TITLE
Incorrect evaluation of limit(x/2*floor(3/x), x, 0, '+')

### ISSUE THREAD

**Issue by sidhantnagpal** [sympy/sympy#14478]
```python
In [1]: limit(x/2*floor(3/x), x, 0, '+')
```
SymPy live gives output as `Out[1]: 0`
Current master gives output as `Out[1]: zoo`

Correct answer should be `3/2`, as `{3/x} (fractional part notation)` is restricted to `[0,1)`.

**Comment by Malkhan52** [comment]
I think here sympy is solving this way L1 = floor(3/x) then limit(x/2*L1).
this can be understood from here:-
```
In[1]: limit(floor(3/(x-1))*x/2,x,1,'+')
Out[1]: floor(zoo)/2

IN[2]: limit(floor(3/(x-1))*x/2,x,1,'-')
Out[2]: floor(zoo)/2
```

**Comment by sidhantnagpal** [comment]
> I think here sympy is solving this way L1 = floor(3/x) then limit(x/2*L1)

I dont think that SymPy uses this because mathematically it would not be correct to consider `limit(f(x)g(x),x,0,'+')` as `limit(f(x),x,0,'+') * limit(g(x),x,0,'+')`, which would cause many limit errors.

Moreover the example you mentioned has limit approaching infinity which is why the property holds.

**Comment by Malkhan52** [comment]
Ah! sorry I didn't mean that,
I mean for my above-mentioned example result should be `oo` and `-oo`.
so, the problem with floor() evaluating with a limit

**Comment by 0sidharth** [comment]
I think the error is in the way `series` calculations are done - 
https://github.com/sympy/sympy/blob/75232383e71161a909cd6bc2c581f41a7160253e/sympy/core/mul.py#L1900

`self.args` contains `(1/2, _w, floor(3/_w))` which lead to `facs` being evaluated to `[1/2, _w, zoo]`. Maybe chaging `floor(3/x)` to  simply `3/x` for `limitinf` is a fix?
