### ISSUE TITLE
Function integrate Unable to Evaluate Trivial Integral

### ISSUE THREAD

**Issue by nicholashub** [sympy/sympy#14470]
This indefinite integral:

`integrate(1/sqrt(exp(x)+1), x)` 

should return `log((sqrt(exp(x)+1)-1)/(sqrt(exp(x)+1)+1))`.  Such solution can be obtained by using substitution `y=exp(x)` and `z=sqrt(y+1)`. However, sympy returns an unevaluated `Integral` object.

Based on the document from `help(integrate)`, sympy tries to find antiderivative by 

> using all available methods, ordered by performance (that is, try fastest method first, slowest last; in particular, polynomial integration is tried first, Meijer G-functions second to last, and heuristic Risch last

I assume Risch algorithm is also tried after polynomial integration and before heuristic Risch (correct me if I'm wrong). Not sure if the manual method is tried by `integrate`, I also tried:

`integrate(1/sqrt(exp(x)+1), x, manual=True)`

still not worked.

**Comment by normalhuman** [comment]
The part of Risch that is implemented does not cover expressions with roots. 

Manual integration considers the substitution y=exp(x), but does not know how to integrate `1/(y*sqrt(1+y))`
```
>>> from sympy.integrals.manualintegrate import substitution_rule
>>> substitution_rule((1/sqrt(exp(x)+1), x))
URule(u_var=_u, u_func=exp(x), constant=1, substep=DontKnowRule(context=1/(_u*sqrt(_u + 1)), symbol=_u), context=1/sqrt(exp(x) + 1), symbol=x)
```

Meijer G integration can handle `1/(y*sqrt(1+y))`, but it is not called by manual (doing so is hardly practical because manual tries many things essentially at random). 
```
>>> integrate(1/(y*sqrt(y+1)), y, meijerg=True)
Piecewise((-2*acoth(sqrt(y + 1)), Abs(y + 1) > 1), (-2*atanh(sqrt(y + 1)), True))
```

Expanding the manual integration to handle expressions like `1/(y*sqrt(1+y))` may be the most approachable solution here.  Presently, it does not see `z = sqrt(1+y)` as a viable substitution here, even though it reduces the integral to something it knows how to evaluate.
```
>>> from sympy.integrals.manualintegrate import manualintegrate
>>> manualintegrate(2/(z**2-1), z)
2*Piecewise((-acoth(z), z**2 > 1), (-atanh(z), z**2 < 1)) 
```

**Comment by nicholashub** [comment]
Thanks. I don't understand when you said "Expanding the manual integration to handle expressions like `1/(y*sqrt(1+y))`". How did you expand and jump to the `manualintegrate(2/(z**2-1), z)` after you mentioned that "manual method reduces the integral to something it knows how to evaluate" (I tested `integrate(1/(x*sqrt(1+x)), x, manual=True)` and it works)?

Are there any "pipeline" things (like pipeline used by Python's scikit-learn to link algorithms) in sympy that one can use to, for instance, implement manual integration N times? And hopefully, by doing so, many seemingly trivial expressions can be integrated automatically without too much human intervention?

**Comment by normalhuman** [comment]
There is a pipeline indeed, in manualintegrate module. It was missing a step necessary to handle this integral. If you are interested, see the PR #14480. 

By the way, `manual=True` means to use __only__ manualintegrate method, and no others. This option does not improve your chances of getting an answer. By default, `integrate` uses all available methods in some carefully chosen order.
