### ISSUE TITLE
Contains should not evaluate automatically

### ISSUE THREAD

**Issue by Upabjojr** [sympy/sympy#14485]
Currently we have:

```python
In [3]: Contains(x, Interval(1, 2))
Out[3]: x ≥ 1 ∧ x ≤ 2
```

I believe that `x ∈ [1, 2]` is a more meaningful syntax for this case.

We could have `Contains(x, Interval(1, 2)).rewrite(And)` to get the other form.

**Comment by abaokar-07** [comment]
Do we have to add `.rewrite(And)` only?

**Comment by Upabjojr** [comment]
First we need to discuss, what do you think about this proposal?

**Comment by abaokar-07** [comment]
I think that `x ∈ [1, 2]` is more easier and more user friendly as compared to `x ≥ 1 ∧ x ≤ 2`

**Comment by smichr** [comment]
This is part of #14449.

**Comment by asmeurer** [comment]
Agree it shouldn't evaluate to And automatically. However, trivial contains, like `Contains(1, {1, 2})` should probably automatically evaluate.
