### ISSUE TITLE
why _masked was moved on the solvers.solveset in solver.solveset?

### ISSUE THREAD

**Issue by kenanai** [sympy/sympy#14483]
I find there is an ImportErrror when I imported _masked:
`from sympy.solvers.solveset import _masked
ImportError                               Traceback (most recent call last)
<ipython-input-11-eca11328b747> in <module>()
----> 1 from sympy.solvers.solveset import _masked

ImportError: cannot import name '_masked'`

So I want to know why moved it but in the sympy repository the solveset.py still has it.

**Comment by smichr** [comment]
It works for me:

```
>>> from sympy.solvers.solveset import _masked
>>>
```
Are you in the correct directory when starting sympy?

**Comment by kenanai** [comment]
I checked it, but it still has this error.Then I uninstall the old sympy and  pip install sympy  == 1.1.1,  but it doesn't work. And I open the solveset.py, it really does't have the _masked func. So what's the problems?

**Comment by Yathartha22** [comment]
@kenanai `_masked` was added recently (see PR #14253 ), so it won't be imported from `1.1.1`, to use it use `1.1.2.dev`

```
>>> import sympy
>>> sympy.__version__
'1.1.2.dev'

>>> from sympy.solvers.solveset import _masked
>>>
```
And if you want to use the `.dev` version clone the repo `cd` into the folder and run `python setup.py install`

**Comment by smichr** [comment]
thanks, @Yathartha22
