### ISSUE TITLE
Limit with sin cannot be calculated

### ISSUE THREAD

**Issue by slacker404** [sympy/sympy#14503]
Sympy cannot currently calculate this limit.
limit(x-sqrt(x**2+sin(x)), x ,oo)
This limit equals to 0

**Comment by czgdp1807** [comment]
I think the following suggests that it can't be calculated conceptually too,
```python
>>> f = x - sqrt(x**2+sin(x))
>>> f
       _____________
      ╱  2          
x - ╲╱  x  + sin(x) 
>>> series(f, x)
          3/2      5/2      7/2        9/2        11/2        
         x      5⋅x      5⋅x      401⋅x      217⋅x        ⎛ 6⎞
x - √x - ──── + ────── - ────── + ──────── - ───────── + O⎝x ⎠
          2       24       48       5760        3840        
```
Wolfram Alpha - https://www.wolframalpha.com/input/?i=limit%28x-sqrt%28x**2+%2B+sin%28x%29%29%2C+x+%2Coo%29

Closing this for now. Thanks for the contributions. If you want to re-open it please let us know by commenting below. Apologies for inconveniences.
