### ISSUE TITLE
ambiguous behavior of ConditionSet

### ISSUE THREAD

**Issue by smichr** [sympy/sympy#14500]
```
Help on class ConditionSet in module sympy.sets.conditionset:

class ConditionSet(sympy.sets.sets.Set)
 |  Set of elements which satisfies a given condition.
 |
 |  {x | condition(x) is True for x in S}

...
```
Does that mean the "set of all x in S for which condition(x) is True" or "the set S if the condition(x) is True"?
```
>>> c = ConditionSet(x,x>5,Interval(1,7))
>>> c.subs(x,8)  # 8 is not in S
Interval(1, 7)
>>> 8 in c
False

>>> c = ConditionSet(x,x>5,S.Integers)
>>> c.subs(x,2*pi)  # 2pi is not an integer
S.Integers
>>> 2*pi in c
False

>>> c=ConditionSet(y,x>5,S.Integers)
>>> c.subs(x,4)
EmptySet()
>>> c.subs(x,6)
S.Integers
>>> 6 in c
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "...sympy\sets\sets.py", line 556, in __contains__
    raise TypeError('contains did not evaluate to a bool: %r' % symb)
TypeError: contains did not evaluate to a bool: x > 5
>>> 3 in c
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "...sympy\sets\sets.py", line 556, in __contains__
    raise TypeError('contains did not evaluate to a bool: %r' % symb)
TypeError: contains did not evaluate to a bool: x > 5

Perhaps an error at instantiation should be raise if the condition is not a function of the given variable?
```
Also, should there be a doit method or autoevaluation for something like this?
```
>>> ConditionSet(x,x>5,Interval(1,3))
ConditionSet(x, x > 5, Interval(1, 3))  <--- should this evaluate to False?
```

Other fixes:
`ConditionSet(x,x>5,Interval(1,7)).subs(x, 8)` should be S.EmptySet

`ConditionSet(x,x>5,Interval(1,7)).subs(x, Symbol('n', negative=True)` should be unchanged: the dummy is not there to help with the condition, only to test idientify where the element from the base_set should be tested in the condition.

**Comment by jksuom** [comment]
It should mean  "set of all x in S for which condition(x) is True". The role of `x` is comparable to the role of an integration variable in a definite integral: It can be replaced by another symbol but it does not make sense to replace it by a number.

I think `ConditionSet(x,x>5,Interval(1,3))` should evaluate to `EmptySet`.

**Comment by smichr** [comment]
So it's like a filter? If so, then ConditionSet(x, x> 5, S.Reals) -> Interval.open(0, 5). If I understand correctly, it is similar to ImageSet. We could write ImageSet(Lambda(x, 2*x), S.Integers) or ConditionSet(x, Eq(Mod(x, 2), 0), S.Integers) to mean "the set of even integers".

**Comment by smichr** [comment]
`ConditionSet(x,x>5,Interval(1,7)).subs(x, 8)` should be S.EmptySet
`ConditionSet(x,x>5,Interval(1,7)).subs(x, Symbol('n', negative=True)` should be unchanged: the dummy is not there to help with the condition, only to test idientify where the element from the `base_set` should be tested in the condition.

**Comment by smichr** [comment]
Current behavior of ConditionSet does not allow the dummy symbol to be replaced with anything but a symbol so `ConditionSet(x,x>5,Interval(1,7)).subs(x, 8)` is unchanged which looks right to me.

Containment also looks ok:
```
>>> 8 in ConditionSet(x,x>5,Interval(1,7))
False
>>> 0 in ConditionSet(x,x>5,Interval(1,7))
False
>>> 2 in ConditionSet(x,x>5,Interval(1,7))
False
>>> 6 in ConditionSet(x,x>5,Interval(1,7))
True
```

Treatment of a condition that is independent of the dummy symbol looks ok:

```
ConditionSet(y,x>5,S.Integers).subs(x, 8) -> S.Integers since the condition is always true
```

There are only 2 deficient behaviors that I see right now:

1. The following should not evaluate since the dummy is not there to help with the condition, only to identify how the element from the `base_set` should be tested in the condition.
```
ConditionSet(x,x>5,Interval(1,7)).subs(x, Symbol('n', negative=True)
```
2. containment tests when the condition is independent of the dummy variable
```
>>> 6 in ConditionSet(x,y>5,Interval(1,7))
Traceback (most recent call last):
...
TypeError: contains did not evaluate to a bool: y > 5
```
I believe the result should be false if the value is not in the base set; and if it is, then the condition should be returned:
```
>> 6 in ConditionSet(x,y>5,Interval(1,7))
y > 5
>> 0 in ConditionSet(x,y>5,Interval(1,7))
False
```

**Comment by jksuom** [comment]
I agree with this.

**Comment by smichr** [comment]
> containment tests when the condition is independent of the dummy variable

It appears that when a test is written as `foo in bah` must give True or False; the containment method can give a conditional answer, however.
