### ISSUE TITLE
Infinite recursion when evaluating the limit of 1/(log(n)**log(n))**(1/n)

### ISSUE THREAD

**Issue by normalhuman** [sympy/sympy#14514]
```
>>> var('n')
>>> limit((1/(log(n)**log(n)))**(1/n), n, oo)
RecursionError: maximum recursion depth exceeded while calling a Python object
```
This doesn't happen when the exponents are combined. 
```
>>> limit(1/(log(n)**(log(n)/n)), n, oo)
1
```

This limit comes up when 
```
Sum(1/log(n)**log(n), (n, 10, oo)).is_convergent()
```
attempts the ratio test.

**Comment by pulkit6559** [comment]
@normalhuman Are you working on this?

**Comment by normalhuman** [comment]
No, feel free to work on this.

**Comment by pulkit6559** [comment]
![debug](https://user-images.githubusercontent.com/31755917/48863464-732b8a00-edef-11e8-981b-c29a62b424ec.png)
@normalhuman  While trying to debug it i noticed that the simplified expression is different from the input, i think that might be causing a problem

**Comment by pulkit6559** [comment]
@normalhuman while i was trying to locate the bug, i came across this function `def mrv_leadterm(e, x):` in series/gruntz.py and i cannot figure out what it does, can you explain what it does?
It says `"""Returns (c0, e0) for e."""` what are e0 and c0 variables?

**Comment by normalhuman** [comment]
To work on limits, one needs to know something about the Gruntz algorithm, beginning with [this page](https://docs.sympy.org/latest/modules/series/series.html#the-gruntz-algorithm) and possibly continuing with the Gruntz thesis linked there.
