### ISSUE TITLE
ConditionSet free_symbols

### ISSUE THREAD

**Issue by smichr** [sympy/sympy#14510]
ConditionSet(a, b, s).free_symbols should be b.free_symbols - {a} + s.free_symbols

```
>>> ConditionSet(x,Eq(y,0),FiniteSet(z)).free_symbols
{z, x, y} < ---- only y and z
>>> ConditionSet(x,Eq(x,0),FiniteSet(z)).free_symbols
{z, x} <---- only z
>>> ConditionSet(x,Eq(y,0),FiniteSet(x, z)).free_symbols
{z, x, y} <---- ok
```

**Comment by abaokar-07** [comment]
I added function `free_symbols(self)`, I am getting the right results but after giving input as
`ConditionSet(x,Eq(y,0),FiniteSet(z)).free_symbols()`, the parenthesis in the last are extra thing
@smichr can you tell me what am I missing?

**Comment by abaokar-07** [comment]
Also for `ConditionSet(x,Eq(y,0),FiniteSet(x, z)).free_symbols` 
```
>>>a = FiniteSet(x, z).free_symbols
>>>a
{z, x}
>>>b = Eq(y, 0).free_symbols
>>>b
{y}
```

doing `(a|b)-{x}` gives output as `{z, x}`
it is obvious that according to what @smichr quoted

> ConditionSet(a, b, s).free_symbols should be b.free_symbols - {a} + s.free_symbols

if we do `(a|b)`, it gives output `{z, x, y}` and `(a|b)-c` will give `{z, y}`
how is `{z, x, y}` correct for the above input?

**Comment by smichr** [comment]
> how is {z, x, y} correct for the above input?

For `ConditionSet(x,Eq(y,0),FiniteSet(x, z)).free_symbols`, there is a difference in the `x` in the `base_set` and the dummy symbol that is the first argument. The dummy symbol just tells where to plug elements of the base set into the condition. So that instance of `x` is ignored. But since `x` appears in the base set, it is a free variable.
