### ISSUE TITLE
Regressions with calculating integrals with variable bounds (one weird regression) and improper integrals

### ISSUE THREAD

**Issue by alexeymuranov** [sympy/sympy#14516]
```
(bash-4.4) § ipython
Python 3.6.4 |Anaconda, Inc.| (default, Jan 16 2018, 18:10:19) 
Type 'copyright', 'credits' or 'license' for more information
IPython 6.2.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import sympy as smp

In [2]: smp.__version__
Out[2]: '1.1.1'

In [3]: from sympy import Symbol

In [4]: smp.init_printing()

In [5]: x = Symbol("x")

In [6]: expr = smp.log(x) * smp.sin(x)

In [7]: expr
Out[7]: log(x)⋅sin(x)

In [8]: t = smp.Symbol("t")

In [9]: expr.integrate((x, t, 1))
^C---------------------------------------------------------------------------
KeyboardInterrupt                         Traceback (most recent call last)
<ipython-input-9-cc643800895c> in <module>()

...

KeyboardInterrupt: 

In [10]: expr.integrate((x, t, 1))
Out[10]: 
1                 
⌠                 
⎮ log(x)⋅sin(x) dx
⌡                 
t              
```

So, when i execute `expr.integrate((x, t, 1))` first time, it seems to enter into an infinite loop, so i interrupt it with `<Ctrl-C>`.  Then i execute the **same line** again, and it returns something (though i was hoping for an expression, not an integral).

In the beginning of 2016, i could calculate this integral with
```
expr.integrate((x, t, 1)).limit(t, 0, '+')
```
It would find `−γ+Ci(1)`.

With still earlier versions of SymPy, i could calculate it with simply
```
expr.integrate((x, 0, 1))
```
but in the beginning of 2016 this was already returning `NaN`.

**Comment by normalhuman** [comment]
Yes, 1.1.1 gets into an infinite loop in manualintegrate module. Some of those loops were recently closed, so in the current development version (that you can clone from this repo) the integral evaluates. 
```
>>> import sympy as smp
>>> smp.var('x t')
>>> expr = smp.log(x) * smp.sin(x)
>>> expr.integrate((x, t, 1))
log(t)*cos(t) + log(t) - log(t**2)/2 - Ci(t) + Ci(1)
```

**Comment by alexeymuranov** [comment]
Thanks for the information.  Does the following work with the development version too?
```
expr.integrate((x, 0, 1))
```
If so, feel free to close.  I will be ready to close it myself when the fix is released.

**Comment by normalhuman** [comment]
```
>>> expr.integrate((x, 0, 1))
-EulerGamma + Ci(1)
```
We usually close issues as they get resolved in development. But the release of SymPy 1.2 should not be too far off.
