### ISSUE TITLE
Incorrect binomial simplifications with constant n

### ISSUE THREAD

**Issue by rwbogl** [sympy/sympy#14528]
SymPy incorrectly simplifies binomials coefficients of the form `binomial(1, k)` to zero for symbolic `k`, and `1` can be replaced by any integer constant. Below are some examples.

````python

# binomial(1, p) is zero if p < 0 or p > 1, and one for p = 0, 1.

binomial(1, -1) # 0
binomial(1, 1) # 1
binomial(1, 2) # 0

# Incorrect.
p = symbols("p")
binomial(1, p).simplify() # 0

# Also incorrect.
p = symbols("p", integer=True)
binomial(1, p).simplify() # 0

# Still incorrect.
p = symbols("p", positive=True, integer=True)
binomial(1, p).simplify() # 0
````
Replacing `.simplify` with `.combsimp` does not fix the issue, and the issue seems to exist for any positive integer upper value. Both `simplify` and `combsimp` are complicated, so I can't determine exactly where the simplifications are going wrong.

**Comment by normalhuman** [comment]
It's somewhat better in the current master branch, although the answer is still 0 if p is positive and integer.
```
>>> p = symbols("p")
>>> binomial(1, p).simplify()
binomial(1, p)
>>> combsimp(binomial(1, p))
-sin(pi*p)/(pi*p*(p - 1))
>>> p = symbols("p", integer=True)
>>> binomial(1, p).simplify()
binomial(1, p)
>>> combsimp(binomial(1, p))
1/(factorial(p)*factorial(-p + 1))
>>> p = symbols("p", integer=True, positive=True)
>>> binomial(1, p).simplify()
0
>>> combsimp(binomial(1, p))
0
```

**Comment by rwbogl** [comment]
With positive integers `simplify()` eventually finds its way through `combsimp` to `_gammasimp(expr, as_comb=True)`. The issue then happens at [these lines](https://github.com/sympy/sympy/blob/02dcba15e403c639760b5f3d6d4665394ea7790b/sympy/simplify/gammasimp.py#L76-L81). Specifically, the `if as_comb` branch simplifies the expression to 0. I am not yet sure what goes wrong here, but somehow trying to preserve integer arguments gives an incorrect simplification.

**Comment by rwbogl** [comment]
As I mentioned, the issue is in the `_rf` rewrites occurring in `_gammasimp`.  Specifically, the issue occurs in trying to rewrite `_rf(1, -p)` as a binomial times a gamma.

The first rewrite turns `gamma(2 - p)` into `_rf(1, 1 - p)`. This is automatically expanded to `(1 - p) * _rf(1, -p)`. For strictly integer `p`, this is incorrect, since the latter is undefined at `p = 1`. The code essentially assumes that `p != 1`.

The [second `_rf` rewrite in `_gammasimp`](https://github.com/sympy/sympy/blob/02dcba15e403c639760b5f3d6d4665394ea7790b/sympy/simplify/gammasimp.py#L79-L81) is where the zero actually occurs. `_rf(1, -p)` is replaced with `binomial(-p, -p) * gamma(1 - p)`. Under the current binomial behavior (see #14529), this evaluates to `gamma(1 - p)`, which is `zoo` since `p` is a positive integer. If the binomial behavior was changed so that `binomial(-p, -p)` was zero, we would get `nan`.

In any event, this chain of rewrites is correct only when `p != 1`. Since `p` is positive, the code assumes that `p > 1`. I think stopping the automatic expansion would fix this.

@normalhuman Is there a straightforward way to stop `_rf(1, 1 - x)` being rewritten as `(1 - x) *_rf(1, -x)`?

Here is a session demonstrating the problem:

````python
>>> p = symbols("p", positive=True, integer=True)
>>> expr = binomial(1, p)
>>> expr = expr.rewrite(gamma)
>>> expr
1/(gamma(-p + 2)*gamma(p + 1))
>>> any(isinstance(node, gamma) and not node.args[0].is_integer for node in preorder_traversal(expr))
False
>>> # Move on to _gammasimp(expr, as_comb=True).
>>> expr_rf = expr.replace(gamma, lambda n: _rf(1, (n - 1).expand()))
>>> expr_rf
1/((-p + 1)*_rf(1, -p)*_rf(1, p))
>>> # Neither (-p + 1) nor _rf(1, p) are issues in the next step.
>>> _rf(1, -p).replace(_rf, lambda a, b: binomial(a + b - 1, b) * gamma(b + 1))
zoo
````

**Comment by jeremies** [comment]
According to Wolfram Mathematica 8.0, SymPy should return the following:

```python
>>> p = symbols("p")
>>> combsimp(binomial(1, p))
-sin(pi*p)/(pi*p*(p - 1))
>>> p = symbols("p", integer=True, nonnegative=True)
>>> combsimp(binomial(1, p))
rf(2-p,p)/gamma(1+p)
>>> p = symbols("p", integer=True, negative=True)
>>> combsimp(binomial(1, p))
0
```

**Comment by rwbogl** [comment]
I am not sure that Mathematica's simplification in the first case is satisfactory either. Its resulting expression is undefined for the only "useful" values of `p`, namely 0 and 1. The second and third ones look fine for Wolfram's definition of the binomial, but SymPy does it slightly differently.
