### ISSUE TITLE
diff: quotient rule not applied

### ISSUE THREAD

**Issue by abaokar-07** [sympy/sympy#14526]
Quotient rule for differentiation is not applied for the following function:
```
In [12]: diff((x)/(1-x), x)
Out[12]:
    x         1
--------- + ------
        2   -x + 1
(-x + 1)
```
It still treats the expression as `x*(1-x)**-1` and applies product rule. That's why we are getting this result

**Comment by abaokar-07** [comment]
Please someone tell that if the problem is valid or not
I probably have a solution to this

**Comment by czgdp1807** [comment]
I don't think it is necessary to apply quotient rules here because quotient rule itself is derived from product rule. Just take the LCM, and you will get the same result as you are expecting from the quotient rule.

**Comment by abaokar-07** [comment]
But don't you think that the answer should be the one from coming from quotient rule, I mean then what's the point of different rules to differentiate functions?

**Comment by asmeurer** [comment]
More simple derivatives would be useful. However, this issue might not be easy to fix as changes could propagate to unexpected places.

**Comment by smichr** [comment]
cf #5553
