### ISSUE TITLE
Incorrect binomial documentation

### ISSUE THREAD

**Issue by rwbogl** [sympy/sympy#14529]
The [documentation](https://github.com/sympy/sympy/blob/bf02a32c7f9741c269c8ecf6353359d36c6ca766/sympy/functions/combinatorial/factorials.py#L719-L720) for `binomial` states:

> For the sake of convenience for negative 'k' this function will return zero no matter what valued is the other argument.

This is the usual definition of the binomial coefficient, but the implementation does not follow this. To be exact, `binomial(k, k)` returns `1`, even for negative `k`. See [these lines of `binomial`](https://github.com/sympy/sympy/blob/bf02a32c7f9741c269c8ecf6353359d36c6ca766/sympy/functions/combinatorial/factorials.py#L854-L856). For example:

````python
>>> binomial(-1, -1)
1
>>> binomial(0, 0)
1
>>> binomial(1, 1)
1
>>> k = symbols("k", integer=True, negative=True)
>>> binomial(k, k)
1
````

It shouldn't be hard to fix this either way (changing the documentation or the conditionals in `binomial`). Is there a preference as to which one should change?

**Comment by normalhuman** [comment]
The treatment of binomial was recently changed in #14019, it seems the docstring is out of date.

**Comment by rwbogl** [comment]
If I understand the discussion in #14019, `binomial` now uses Wolfram's gamma-limit rewrite, with some logic to handle edge-cases in the limit. In that case, shouldn't `binomial(n, k)` evaluate to 0 for negative integer `k`?

In either event, I do not think that #14019 modified the behavior for when `n` and `k` are equal. Both before and after its merging, `binomial(k, k)` would evaluate to 1.
