### ISSUE TITLE
don't use ConditionSet as a container for unsolved sets of equations

### ISSUE THREAD

**Issue by smichr** [sympy/sympy#14523]
We should probably have a different way to represents sets of unsolved equations. An existing test shows how ConditionSet is being used for this purpose:

```
def test_nonlinsolve_conditionset():
    # when solveset failed to solve all the eq
    # return conditionset
    f = Function('f')
    f1 = f(x) - pi/2
    f2 = f(y) - 3*pi/2
    intermediate_system = FiniteSet(2*f(x) - 3*pi, 2*f(y) - pi)
    symbols = FiniteSet(x, y)
    soln = ConditionSet(
        symbols,
        intermediate_system,
        S.Complexes)
    assert nonlinsolve([f1, f2], [x,y]) == soln
```

See also #14500

**Comment by valglad** [comment]
What is the issue with using ConditionSet?

**Comment by smichr** [comment]
For a single equation, `ConditionSet(x, Eq(f(x), 0), domain)` has the meaning: 'all values of x in the domain for which f(x) = 0". For multiple equations (as above) it doesn't have the same meaning and doesn't match the documentation:
```
Set of elements which satisfies a given condition.

{x | condition(x) is True for x in S}
```

So at least we should update the documentation to indicate what the multidimensional case means: the values for the symbols (in the given order and contained in the domain) which simultaneously satisfy the set of equations given by setting the expressions in the "condition" argument to zero.
