### ISSUE TITLE
Abs() reversing subtraction arguments

### ISSUE THREAD

**Issue by defgsus** [sympy/sympy#14532]
Hi there, 
i'm not sure if i got something wrong but the order of arguments in a subtraction seems to be reversed depending on the alphabetic order of the arguments:

```python
from sympy import *
from sympy.abc import a, b, c, x, y, z
#init_printing(use_unicode=True)
```

```python
%load_ext version_information
%version_information sympy
```

<table><tr><th>Software</th><th>Version</th></tr><tr><td>Python</td><td>2.7.12 64bit [GCC 5.4.0 20160609]</td></tr><tr><td>IPython</td><td>5.5.0</td></tr><tr><td>OS</td><td>Linux 4.4.0 116 generic x86_64 with Ubuntu 16.04 xenial</td></tr><tr><td>sympy</td><td>1.1.1</td></tr><tr><td colspan='2'>Sun Mar 18 19:56:24 2018 CET</td></tr></table>

# okay

```python
Abs(x - y)
```
[Out]:    Abs(x - y)

```python
Abs(x - z)
```
[Out]:    Abs(x - z)

# not okay
arguments get reverse order

```python
Abs(x - a)
```
[Out]:    Abs(a - x)

```python
Abs(y - x)
```
[Out]:    Abs(x - y)

```python
Abs(b - a)
```

[Out]:    Abs(a - b)

**Comment by jashan498** [comment]
I don't think it would be a good idea to change this behavior. There would be, for sure,  a good reason behind calling of  [as_ordered_terms method ](https://github.com/sympy/sympy/blob/3344afa65811e32d7e64e7aa204a360eabf32674/sympy/core/expr.py#L978).

**Comment by normalhuman** [comment]
This behavior is widespread in SymPy: functions try to bring their argument to some  canonical form.
```
>>> cos(b-a)
cos(a - b)
``` 
One benefit is that we know that `Abs(a-b) == Abs(b-a)` on the structural level, without examining the properties of Abs (or another function) every time two expressions need to be compared.

**Comment by defgsus** [comment]
Thanks a lot,
this seems all reasonable. So Sympy does this to all arguments of functions that are symmetric or mirrored around 0.0
```python
>>> sin(y - x)
-sin(x - y)
```
