### ISSUE TITLE
x // 1 gives floor(x), not x

### ISSUE THREAD

**Issue by nschloe** [sympy/sympy#14542]
Integer division is somewhat borked in sympy. For example, `x // 1` gives `floor(x)` and not the correct `x`.

**Comment by normalhuman** [comment]
Why should it give x, if `3.2 // 1 == 3.0`?

**Comment by smichr** [comment]
@nschloe , the "//" operator in Python is "truncate to integer less than or equal to arg" while "/" is normal division (more or less). So the 'floor' result (as indicated by @normalhuman) is a way to restate the result:

```
>>> (x//1).subs(x,-2.1) == floor(-2.1)
True
```

**Comment by nschloe** [comment]
Yes, thanks very much for the explanation. I had hit this issue with expressions like `(2*x)//2` which I had naively expected to evaluate to `x`. I guess a simple `/` is good enough.
