### ISSUE TITLE
solveset fails if floating-point numbers are used

### ISSUE THREAD

**Issue by taavirepan** [sympy/sympy#14541]
For example `solveset(sqrt(-x**2 - 2), x)` returns` {-sqrt(2)*I, sqrt(2)*I}`, as expected. However, when instead of integer a floating point is used (`solveset(sqrt(-x**2 - 2.0), x)`), then `EmptySet()` is returned.

**Comment by shardulsinghh** [comment]
I don't think the float data type is the issue, `solveset(sqrt(-x**2 - 4.0))` returns the correct answer. More accurately, in such an expression the correct answer is returned if only if the constant term is a perfect square, 4.0, 9,0, 16.0 etc.
 I'd like to fix this issue. I've been going over the code for a few hours now, can't seem to understand the following with the `solveset` method:
`f, mask = _masked(f, Abs)` 
   ` f = f.rewrite(Piecewise)`
1. Why exactly do we need the _masked method?
2.In the second line, is 'Piecewise an' object of the 'Piecewise' Class? If so it is no clear how it is implemented as an argument.

Also I am new to Open-Source, I'd love to try another approach if I am wrong.

**Comment by smichr** [comment]
> do we need the _masked method

One way you can use git/github to answer this is to search closed issues/PRs for that text...you will see it was introduced in #14341. That's a good place to start.

Sometimes there are lines in the code to deal with possibilities which may not be realized in all cases. So *if* there is an Abs argument it will be removed while rewriting (*if* there is something that can be rewritten as Piecewise).

**Comment by ishanaj** [comment]
```
>>> sqrt(2.0)
1.41421356237310
>>> sqrt(2)
sqrt(2)
```
`_solve_radical()` produces `{-1.4142135623731*I, 1.4142135623731*I}` initially but later uses `checksol` to recheck the solution, where the solution fails to satisfy the equation.

**Comment by czgdp1807** [comment]
The issue still persists on `master`. It is open for contributions. Please see, #14583 as well.

**Comment by oscargus** [comment]
Works in current master. Will add a test and close.

**Comment by oscarbenjamin** [comment]
Fixed in 9d0625bb7fd2e5a31da8642fb52ad4804773f302 from #21071

The PR notes that further improvements are possible: https://github.com/sympy/sympy/pull/21071#issuecomment-798884294
