### ISSUE TITLE
LUsolve raises IndexError even though system has a unique solution

### ISSUE THREAD

**Issue by bjodah** [sympy/sympy#14548]
I encountered (essentially) this:
```python
>>> Matrix([[2, 1], [1, 0], [1, 0]]).LUsolve(Matrix([3, 1, 1]))
...
IndexError: Index out of range: a[2]
```
The reason the matrix was not in a canonical format is because it is generated programmatically. Manually, removing the superfluous row allows the system to be solved:
```python
>>> Matrix([[2, 1], [1, 0]]).LUsolve(Matrix([3, 1]))
⎡1⎤
⎢ ⎥
⎣1⎦
```
What do you think, should we allow LUsolve to handle this kind of "apparently" overdetermined systems?

**Comment by moorepants** [comment]
Seems like removing duplicate rows from a system like this would be fine.

**Comment by normalhuman** [comment]
I'm aware of the meaning of "Needs Decision", but considering the only comment in ~8 months was in support of this change, and that the required modifications are minor, I went ahead with a PR.
