### ISSUE TITLE
Improper evaluation of Reciprocal Trigonometric Functions

### ISSUE THREAD

**Issue by sidhantnagpal** [sympy/sympy#14543]
Reciprocal Trigonometric Functions: `sec`, `csc`
```python
>>> sec(11)
sec(11)

>>> sec(pi + 11)
-1/cos(11)

>>> sec(2*pi + 11)
1/cos(11)

>>> print(sec(11) == sec(2*pi + 11))
False
```

**Comment by tboydamj** [comment]
Hi sidhantnagpal, I would like to work on this  issue.
I'm  relatively new to github but looking forward to contributing

**Comment by sidhantnagpal** [comment]
Hi @tboydamj - to take up an issue you should check if it has already been assigned or has existing Pull Request(s) (see reference) that fix the issue.

**Comment by tboydamj** [comment]
@sidhantnagpal  thanks for the clarification.
