### ISSUE TITLE
CartanType instantiation

### ISSUE THREAD

**Issue by maxencemayrand** [sympy/sympy#14569]
The current implementation of liealgebras has two ways to instantiate a
CartanType and hence also a RootSystem. For example,
```
c = CartanType('A7')
```
and
```
c = CartanType(['A', 7])
```
give the same thing. However, the former method only reads the first digit,
so, for example, `CartanType('A34')` will be exactly the same as `CartanType('A3')`
although it should be `CartanType(['A', 34])`.

**Comment by asmeurer** [comment]
Fixed by https://github.com/sympy/sympy/pull/14568

**Comment by oscarbenjamin** [comment]
So should this be closed?

**Comment by maxencemayrand** [comment]
@oscarbenjamin 

> So should this be closed?

Yes, it should.
