### ISSUE TITLE
Simple integral is incorrectly zero if constant is squared and real

### ISSUE THREAD

**Issue by moble** [sympy/sympy#14572]
The expression
```python
integrate(1/(x**2+y**2), x)
```
is fairly easy to integrate, but sympy gives wildly different answers depending on details of how it is input, including a completely incorrect answer for a trivial case.  Specifically, for the expression above, if we assume that `y` is real, we simply get 0 even though it should be `atan(x/y)/y`.  [Tested on sympy live](http://live.sympy.org/?evaluate=x%2C%20y%20%3D%20symbols(%22x%2C%20y%22%2C%20real%3DTrue)%0Aprint(integrate(1%2F(x**2%2B1)%2C%20x))%20%20%23%20prints%20%60atan(x)%60%2C%20which%20is%20correct%0Aprint(integrate(1%2F(x**2%2By)%2C%20x))%20%20%23%20prints%20a%20big%20ugly%20expression%20equivalent%20to%20correct%20%60atan(x%2Fsqrt(y))%2Fsqrt(y)%60%0Aprint(integrate(1%2F(x**2%2By**2)%2C%20x))%20%20%23%20incorrectly%20prints%200%3B%20should%20be%20%60atan(x%2Fy)%2Fy%60%0Aprint(integrate(1%2F(x**2%2By**2)%2C%20x%2C%20manual%3DTrue))%20%20%23%20prints%20incomplete%20Piecewise%20response%0A%0A%23--%0Ax%2C%20y%20%3D%20symbols(%22x%2C%20y%22)%0Aprint(integrate(1%2F(x**2%2B1)%2C%20x))%20%20%23%20prints%20%60atan(x)%60%2C%20which%20is%20correct%0Aprint(integrate(1%2F(x**2%2By)%2C%20x))%20%20%23%20prints%20a%20big%20ugly%20expression%20equivalent%20to%20correct%20%60atan(x%2Fsqrt(y))%2Fsqrt(y)%60%0Aprint(integrate(1%2F(x**2%2By**2)%2C%20x))%20%20%23%20prints%20a%20medium%20ugly%20expression%20equivalent%20to%20correct%20%60atan(x%2Fy)%2Fy%60%0Aprint(integrate(1%2F(x**2%2By**2)%2C%20x%2C%20manual%3DTrue))%20%20%23%20prints%20excessively%20complicated%20and%20incomplete%20Piecewise%20response%0A%23--%0A) and in a fresh install of sympy 1.1.1.

The following show some of the different results that we get:
```python
import sympy
x, y = sympy.symbols("x, y", real=True)
print(sympy.integrate(1/(x**2+1), x))  # prints `atan(x)`, which is correct
print(sympy.integrate(1/(x**2+y), x))  # prints a big ugly expression equivalent to correct `atan(x/sqrt(y))/sqrt(y)`
print(sympy.integrate(1/(x**2+y**2), x))  # incorrectly prints 0; should be `atan(x/y)/y`
print(sympy.integrate(1/(x**2+y**2), x, manual=True))  # prints incomplete Piecewise response
```

We get quite different results if we drop the `real=True` flag.  These are mostly correct, though overcomplicated and the piecewise result is still incomplete.  In particular, we do not get `0` for the case noted at the top of this comment:
```python
x, y = sympy.symbols("x, y")
print(sympy.integrate(1/(x**2+1), x))  # prints `atan(x)`, which is correct
print(sympy.integrate(1/(x**2+y), x))  # prints a big ugly expression equivalent to correct `atan(x/sqrt(y))/sqrt(y)`
print(sympy.integrate(1/(x**2+y**2), x))  # prints a medium ugly expression equivalent to correct `atan(x/y)/y`
print(sympy.integrate(1/(x**2+y**2), x, manual=True))  # prints excessively complicated and incomplete Piecewise response
```

This may be related to #12131, but is simpler.

**Comment by asmeurer** [comment]
The `integrate(1/(x**2+y**2), x)` for x, y real integral has been fixed in master. 

The incomplete Piecewise is indeed a bug, though. For reference, here is the result

```
>>> integrate(1/(x**2+y**2), x, manual=True)
Piecewise((atan(x/Abs(y))/Abs(y), y**2 > 0))
```

There should be an otherwise condition, at least with the unevaluated Integral (like what meijerint returns).

**Comment by moble** [comment]
As of 1.11.1, the examples above all seem to work satisfactorily.

**Comment by oscarbenjamin** [comment]
Thanks for checking up on this.
