### ISSUE TITLE
interaction of sympy and random

### ISSUE THREAD

**Issue by esandier** [sympy/sympy#14589]
I noticed the following strange behaviour when generating a random function
`import sympy, random

x = sympy.symbols('x')

random.seed(10)

y = 0

for i in range(4): y += sympy.sin(random.uniform(-10,10) * x)

random.seed(10)

z = 0

for i in range(4): z += sympy.sin(random.uniform(-10,10) * x)
`
I get different values for y and z.

**Comment by jksuom** [comment]
The values I get do not look different:
```
>>> random.seed(10)
>>> y = 0
>>> for i in range(4): y += sympy.sin(random.uniform(-10,10) * x)
... 
>>> y
-sin(1.42221890649771*x) + sin(1.42805189379827*x) + sin(1.56182602268941*x) - sin(5.87803535720997*x)
>>> random.seed(10)
>>> z = 0
>>> for i in range(4): z += sympy.sin(random.uniform(-10,10) * x)
... 
>>> z
-sin(1.42221890649771*x) + sin(1.42805189379827*x) + sin(1.56182602268941*x) - sin(5.87803535720997*x)
>>> 
```

**Comment by esandier** [comment]
Here is a screenshot :
 


    Le lundi 2 avril 2018 à 13:21:38 UTC+2, Kalevi Suominen <notifications@github.com> a écrit :  
 
 
The values I get do not look different:
>>> random.seed(10)
>>> y = 0
>>> for i in range(4): y += sympy.sin(random.uniform(-10,10) * x)
... 
>>> y
-sin(1.42221890649771*x) + sin(1.42805189379827*x) + sin(1.56182602268941*x) - sin(5.87803535720997*x)
>>> random.seed(10)
>>> z = 0
>>> for i in range(4): z += sympy.sin(random.uniform(-10,10) * x)
... 
>>> z
-sin(1.42221890649771*x) + sin(1.42805189379827*x) + sin(1.56182602268941*x) - sin(5.87803535720997*x)

**Comment by asmeurer** [comment]
I get

```
>>> y
sin(1.42805189379827*x) + sin(1.55778912915404*x) + sin(5.54243799539346*x) + sin(8.0835978129377*x)
>>> z
-sin(1.42221890649771*x) + sin(1.42805189379827*x) + sin(3.06291637379069*x) - sin(7.68145060132939*x)
```

and I get those same two values each time.

**Comment by asmeurer** [comment]
Actually after a second run, I get the same value. So it's probably related to the cache somehow.

**Comment by asmeurer** [comment]
@esandier you should be able to get consistent results by using `random.Random` instances, which are seeded independently (this is always a good practice anyway).

**Comment by esandier** [comment]
Indeed this works. Evaluating the loop within "with evaluate(False)" works as well.

**Comment by asmeurer** [comment]
Similar issue: https://github.com/sympy/sympy/issues/12628

**Comment by asmeurer** [comment]
Why did you close this? I don't think it was fixed.

**Comment by esandier** [comment]
Sorry,

I'm not familiar with how issues are handled, I thought I was supposed to close it after a while

Etienne
 

    Le mardi 1 mai 2018 à 21:33:31 UTC+2, Aaron Meurer <notifications@github.com> a écrit :  
 
 
Why did you close this? I don't think it was fixed.

**Comment by philippedemaria** [comment]
@esandier : Bonjour, pourriez vous m'écrire ? Je me suis inscrit en follower sur votre projet pywims. Je souhaiterais l'intégrer dans un de mes sites.
Merci.

**Comment by esandier** [comment]
Je vous ai répondu avec mon adresse u-pec.
cordialement,
ES
    Le mardi 18 juin 2019 à 02:53:36 UTC−4, philippedemaria <notifications@github.com> a écrit :  
 
 
@esandier : Bonjour, pourriez vous m'écrire ? Je me suis inscrit en follower sur votre projet pywims. Je souhaiterais l'intégrer dans un de mes sites.
Merci.
