### ISSUE TITLE
Sum on open intervals

### ISSUE THREAD

**Issue by Upabjojr** [sympy/sympy#14587]
Expression with limits should handle limits differently for `Integral` and `Sum`:
```
In [1]: Integral(x, (x, Interval.open(2, 5)))
Out[1]: 
5     
⌠     
⎮ x dx
⌡     
2     
```
This is correct, as the integral does not really care about open/closed intervals (unless you put a Dirac delta in it).

On the other hand:
```
In [2]: Sum(x, (x, Interval.open(2, 5)))
Out[2]: 
  5    
 ___   
 ╲     
  ╲   x
  ╱    
 ╱     
 ‾‾‾   
x = 2  
```
This result is wrong. The limits should be `(3, 4)`, as the interval is open.

**Comment by divyanshu132** [comment]
```
>>> Interval.open(5, 8)
Interval.open(5, 8)
>>> Interval.open(5, 8).start
5
>>> Interval.open(5, 8).end
8
>>> Interval(5, 8, left_open=True).start
5
>>> Interval.Ropen(5, 8).end
8
>>> Interval.Lopen(5, 8).start
5
```

@jksuom can you please have a look at this. I think the `return` in the below definition with `True, True` is not doing anything, Similar behavior for `Lopen`, `Ropen` as well.

```
def open(cls, a, b):
    """Return an interval including neither boundary."""
    return cls(a, b, True, True)
```
**So, should I proceed with manually incrementing and decrementing a and b.**

**Comment by czgdp1807** [comment]
The issue still persists on `master`.

**Comment by asmeurer** [comment]
https://github.com/sympy/sympy/pull/14597#issuecomment-598828831

**Comment by czgdp1807** [comment]
Closing in reference to https://github.com/sympy/sympy/pull/14597#issuecomment-600243716
