### ISSUE TITLE
limit((n**3*((n + 1)/n)**n)/((n + 1)*(n + 2)*(n + 3)), n, oo) is incorrect

### ISSUE THREAD

**Issue by ethankward** [sympy/sympy#14590]
```
>>> from sympy import *
>>> n = Symbol('n')
>>> limit((n**3*((n + 1)/n)**n)/((n + 1)*(n + 2)*(n + 3)), n, oo)
1
```

The answer should be `E` (`exp(1)`).

**Comment by Naba7** [comment]
I don't think it is incorrect.If you divide numerator and denominator by (n**(n+3)) as that is the highest power in both denominator and numerator,having coefficients as 1.The output is 1 .As 1/n tends to 0 when n tends to oo.

**Comment by ethankward** [comment]
You can verify numerically that it is not 1.

**Comment by oscarbenjamin** [comment]
Or analytically by seeing that the `n**3` will cancel the denominator leaving `(1+1/n)**n` which is well known as an expression with limiting value e (sometimes taken as the definition of e).

**Comment by Naba7** [comment]
Yes,sorry. I placed the brackets incorrectly. I get it now.

**Comment by Naba7** [comment]
Sympy puts the values of limits n->oo in (1+1/n)**n, where 1/n =0 as in
n->oo. So,it gives the result 1**oo as 1

**Comment by Naba7** [comment]
As in limits.py,in line ``244-257`` 
``        if all(ok(w) for w in e.as_numer_denom()):``
                    ``u = Dummy(positive=True)``
                    ``if z0 is S.NegativeInfinity:``
                        ``inve = e.subs(z, -1/u)``
                    ``else:``
                        ``inve = e.subs(z, 1/u)``
                    ``try:``
                        ``r = limit(inve.as_leading_term(u), u, S.Zero, "+")``
                        ``if isinstance(r, Limit):``
                            ``return self``
                        ``else:``
                            ``return r``
                    ``except ValueError:``
                            ``pass``
After cancelation of common factors in ``  if all(ok(w) for w in e.as_numer_denom())``,the function ``doit`` substitutes ``u`` to ``1/u`` hence making ``oo`` terms equal to ``0`` .So,a value of ``1`` is returned rather than ``exp(1)``.

**Comment by Naba7** [comment]
@oscarbenjamin Shall I make any changes to that or put a condition for special functions so that rather than evaluating an expr,it will return some certain values by analytically looking at the expression.

**Comment by oscarbenjamin** [comment]
I don't know the limits code so I can't really advise. If you have an idea for how to fix it then go ahead and try it and open a PR. Then someone can review and suggest changes if necessary.

**Comment by Naba7** [comment]
I think there should be a module calculating special limits such as this one in gruntz.py so that it would be easier to calculate limits rather than the regular system we use. Can I work on this during GSoC-19 ?
