### ISSUE TITLE
magnetic_constant does not evaluate to the correct number

### ISSUE THREAD

**Issue by RyanPeterson18** [sympy/sympy#14591]
Hello!

I found that when importing u0 or the magnetic_constant from sympy.physics.units in sympy 1.1.1, evaluating the constant is 3 sig figs off.

```
>>> from sympy.physics.units import u0
>>> u0.args
(magnetic_constant, Dimension(force/current**2), pi/2500, magnetic_constant)
>>> u0.scale_factor.evalf()
0.00125663706143592
```

The actual value of u0 should be pi/2500000 (0.00000125663706143592) like it evaluates to in version 1.0.

**Comment by lilithxxx** [comment]
This maybe because ```kilogram```'s ```scale_factor``` was changed to ```kilo``` from One and was given to ```gram```. This changed the ```scale_factor``` of magnetic constant by three sig figs as you said. I made a PR regarding this, let's see what others have to say.

**Comment by Upabjojr** [comment]
You should not use `scale_factor`. Use `convert_to` to transform it to some other units.
```python
In [4]: convert_to(u0, [meter, kilogram, second, ampere])
Out[4]: 
    π⋅kilogram⋅meter   
───────────────────────
              2       2
2500000⋅ampere ⋅second 
```
