### ISSUE TITLE
evalf and subs on polynomial give wrong result when cast to float

### ISSUE THREAD

**Issue by thomasguillet** [sympy/sympy#14601]
I'm trying to use `evalf` to evaluate polynomials as `float64` numbers without intermediate loss of precision.
I came across this unexpected behavior, which seems related to #7867 and #6974. I'm using sympy 1.1.1 from the anaconda distribution:

```
x, y = sympy.symbols("x y")
e = 5*x*y/2 - y*(35*(x**3)/2 - 15*x/2)

subst = {x:0.0, y:0.0}

e1 = e.subs(subst).evalf()
print e1, float(e1)

e2 = e.evalf(subs=subst)
print e2, float(e2)
```
with the following results:

```
0 0.0
0.e+0 2.0
```
So `float(e2)` evaluates to 2.0 instead of 0.0 and silently produces a wrong result.
This was very surprising to me; am I missing something about `evalf` and `subs` semantics and precision management?

**Comment by jksuom** [comment]
This looks like a bug in evalf. It tries to estimate the sum of two zeros repeatedly increasing the precision until finally giving up with error indication (accuracy -1).
```
In [10]: (x + y).evalf(subs={x: 0.0, y: 0.0}, verbose=True)
.
.
ADD: restarting with prec 405
### input 0.0
### output 0.0
### raw ((0, mpz(0), 0, 0), None, 415, None)

### input x
### output 0.0
### raw ((0, mpz(0), 0, 0), None, 415, None)

### input 0.0
### output 0.0
### raw ((0, mpz(0), 0, 0), None, 415, None)

### input y
### output 0.0
### raw ((0, mpz(0), 0, 0), None, 415, None)

### input x + y
### output 1.1818212630765741799371431375995946800446225561672e-125
### raw ((0, mpz(1), -415, 1), None, -1, None)

Out[10]: 0.e-125
```

**Comment by normalhuman** [comment]
Getting 1e-125 seems wrong, but it's particularly troublesome how the result ends up being 2.0 so often. Here is a simpler example of this behavior: 
```
>>> float((x + x*(x**2 + x)).evalf(subs={x: 0.0}))
2.0
```
