### ISSUE TITLE
__floordiv__ wrong calculations

### ISSUE THREAD

**Issue by kckennylau** [sympy/sympy#14610]
```
from sympy import*
print(9999//pi**9)
print(int(9999/pi**9))
print(float(9999/pi**9))
```
Output:
```
2
0
0.3354344889173148
```

**Comment by sidhantnagpal** [comment]
This gives correct answer for me locally as well as on [SymPy Live](http://live.sympy.org/).
```python
In [3]: print(9999//pi**9)
Out[3]: 0
```

**Comment by DennisMitchell** [comment]
@siddhanathan I'm not sure how SymPy Live does it, but its behavior is _very_ different from my local install.

**Local**

```python
>>> type(9999)
<type 'int'>
```

**SymPy Live**

```python
>>> type(9999)
<class 'sympy.core.numbers.Integer'>
```

If you manually cast to `int`, SymPy Live (which still uses SymPy 1.0) errors on the expression.

```python
>>> int(9999)//pi**9
Traceback (most recent call last):
  File "<string>", line 1, in <module>
TypeError: unsupported operand type(s) for //: 'int' and 'Pow'
```

Both my local machine and my web service use SymPy 1.1.1 and have the same issue the OP describes. [Try it online!](https://tio.run/##K6gsycjPM/7/P60oP1ehuDK3oFIhM7cgv6hEQYuLK0/BVsESCLgKijLzSjRKKgtSNfI0dRTy9PULMrW0LDUhSvxKc5NSizRAKjVxKv3/HwA "Python 3 – Try It Online")

**Comment by normalhuman** [comment]
SymPy 1.3, as well as the current master branch, output 0 for `9999//pi**9`. So does SymPy Live (running V 1.3 at present).

**Comment by sidhantnagpal** [comment]
Closing this, as it has been resolved.
