### ISSUE TITLE
Unnecessary loop in Matrix.nullspace

### ISSUE THREAD

**Issue by sciferr** [sympy/sympy#14620]
To me it seem that the inner loop in `Matrix.nullspace()` is only looping over pivot columns and the single free variable. However the element `reduced[piv_row, pos]` must be zero if the `reduced` matrix is in _reduced_ row echelon form since the column is a pivot columns.

    reduced, pivots = self.rref(simplify=simplify)

    free_vars = [i for i in range(self.cols) if i not in pivots]

    basis = []
    for free_var in free_vars:
        # for each free variable, we will set it to 1 and all others
        # to 0.  Then, we will use back substitution to solve the system
        vec = [S.Zero]*self.cols
        vec[free_var] = S.One
        for piv_row, piv_col in enumerate(pivots):
            for pos in pivots[piv_row+1:] + (free_var,):
                vec[piv_col] -= reduced[piv_row, pos]

Proposed solution would be

    reduced, pivots = self.rref(simplify=simplify)

    free_vars = [i for i in range(self.cols) if i not in pivots]

    basis = []
    for free_var in free_vars:
        # for each free variable, we will set it to 1 and all others
        # to 0.  Then, we will use back substitution to solve the system
        vec = [S.Zero]*self.cols
        vec[free_var] = S.One
        for piv_row, piv_col in enumerate(pivots):
            vec[piv_col] -= reduced[piv_row, free_var]

Sorry for my ignorance

**Comment by asmeurer** [comment]
I would try making the change and running the tests (`./bin/test matrices`). If they pass, you can make a pull request.
