### ISSUE TITLE
Abs(a) / sqrt(a**2) must be 1, not itself

### ISSUE THREAD

**Issue by neihousaigaai** [sympy/sympy#14629]
As you know, `sqrt(a**2) = |a|`, so the result of `Abs(a) / sqrt(a**2)` must be 1. But when I try
```python
print(sympy.simplify(sympy.Abs(a) / sympy.sqrt(a**2)))
```
, the result is still `Abs(a)/sqrt(a**2)`.

**Comment by jksuom** [comment]
`|a|` is real. Therefore it can be equal to `sqrt(a**2)` only if this is real.
```
>>> a = symbols('a', real=True)
>>> Abs(a)/sqrt(a**2)
1
```
If `a` is not real, then `sqrt(a**2)` is not real.

**Comment by neihousaigaai** [comment]
But the components of vector should be real, right?

I'm working with vector, and when I see `Abs(a) / sqrt(a**2)`, I feel confused.

**Comment by asmeurer** [comment]
CC @Upabjojr.

**Comment by neihousaigaai** [comment]
I have put `real=True` in the definition of `a`, but I think when I use variables in vector's component, the variables have to automatically set to real.

**Comment by asmeurer** [comment]
Are nonreal vector components a thing in SymPy?

**Comment by Upabjojr** [comment]
Not necessarily. You could have a 3d complex vector.

This is usually not the case as 3d vectors are most commonly used to represent points in space.

**Comment by Upabjojr** [comment]
I mean, a 3d complex vector is not the same as a 6d real vector, because some operators are expected to act differently.
