### ISSUE TITLE
binomial(n,n) needs simplify to become 1

### ISSUE THREAD

**Issue by cbm755** [sympy/sympy#14625]
After 76adb16333dffd42635f50f935a4a1badbe0a814, `binomial(n, n)` does not become 1.  Sure.

But even with appropriate assumptions, we need to simplify:
```
>>> n = Symbol('n', integer=True, positive=True)
>>> binomial(n, n)
⎛n⎞
⎜ ⎟
⎝n⎠
>>> simplify(_)
1
```

@sidhantnagpal: was that intentional?  Maybe its not important given that DTRT with `simplify`...  Thoughts?

**Comment by sidhantnagpal** [comment]
Yes, I think adding `if k.is_zero or (n.is_nonnegative and d.is_zero)` should fix this.

**Comment by sidhantnagpal** [comment]
Similar issue would be `binomial(n, n - 1)` for same assumptions on `n`.
And it could be fixed using `if (k - 1).is_zero or (n.is_nonnegative and (d - 1).is_zero)`.

Both the cases, will hold even if n is not an integer. So, tests with minimal assumptions would be:
```
In []: n = Symbol('n', nonnegative=True)
In []: binomial(n, n)
Out[]: 1
In []: binomial(n, n - 1)
Out[]: n
```
Though it should be checked that it doesn't break any case.
