### ISSUE TITLE
Inverse Fourier transform of a partial fraction decomposition looks to give a wrong answer

### ISSUE THREAD

**Issue by jankoslavic** [sympy/sympy#14624]
I am trying to replicate this:
https://math.stackexchange.com/questions/2280196/inverse-fourier-transform-of-a-partial-fraction-decomposition
with sympy.

With Mathematica I get just the same behavior as the above theory suggest. 

With sympy it looks wrong. At t<0, I get the result close to the correct one for t>0. (I was not able to include all the assumptions in sympy).

Here is the sympy code (the difference with regards to normalization due to the unitary FT is ok):

```
> import sympy as sym
> sym.init_printing()
> ω = sym.symbols('omega', real=True, positive=True) 
> R, λ = sym.symbols('R, lambda', complex=True)
> t = sym.symbols('t', real=True, positive=True)
> α = R/(sym.I*ω-λ)+sym.conjugate(R)/(sym.I*ω-sym.conjugate(λ))
> sym.inverse_fourier_transform(α, ω, -t) #note the - here!
```

and the Mathematica:

```
> a = InverseFourierTransform[ R/(I omega - lambda) +  Conjugate[R]/(I omega - Conjugate[lambda]), omega, t,   FourierParameters -> {1, -1}]
> Simplify[a, {Re[lambda] < 0, t > 0}]
 ```

Is the sympy result really wrong?

**Comment by asmeurer** [comment]
Which version of SymPy are you using? 

In 1.1.1, I get (after some time)

```
-2*pi*R*exp(-2*pi*lambda*t) - 2*pi*exp(-2*pi*t*conjugate(lambda))*conjugate(R)
```

This matches the result from the StackExchange, with negative `t`.

In master, I get

```pytb
  File "./sympy/integrals/transforms.py", line 1446, in inverse_fourier_transform
    return InverseFourierTransform(F, k, x).doit(**hints)
  File "./sympy/integrals/transforms.py", line 117, in doit
    self.function_variable, self.transform_variable, **hints)
  File "./sympy/integrals/transforms.py", line 1330, in _compute_transform
    self.__class__._name, **hints)
  File "./sympy/integrals/transforms.py", line 195, in wrapper
    res = func(*args, **kwargs)
  File "./sympy/integrals/transforms.py", line 1297, in _fourier_transform
    F = integrate(a*f*exp(b*I*x*k), (x, -oo, oo))
  File "./sympy/integrals/integrals.py", line 1403, in integrate
    risch=risch, manual=manual)
  File "./sympy/integrals/integrals.py", line 538, in doit
    function, xab[0], **eval_kwargs)
  File "./sympy/integrals/integrals.py", line 873, in _eval_integral
    return NonElementaryIntegral(f, x).doit(risch=False)
  File "./sympy/integrals/integrals.py", line 538, in doit
    function, xab[0], **eval_kwargs)
  File "./sympy/integrals/integrals.py", line 985, in _eval_integral
    h = heurisch_wrapper(g, x, hints=[])
  File "./sympy/integrals/heurisch.py", line 130, in heurisch_wrapper
    unnecessary_permutations)
  File "./sympy/integrals/heurisch.py", line 703, in heurisch
    solution = _integrate()
  File "./sympy/integrals/heurisch.py", line 614, in _integrate
    if m[y] == 0:  # No coefficient of I
TypeError: 'NoneType' object is not subscriptable
```

**Comment by asmeurer** [comment]
@vishalg2235 it looks like this bug was introduced with https://github.com/sympy/sympy/pull/13758. When using match, you always have to check if the result of the match is `None` first.

**Comment by jankoslavic** [comment]
thank you @asmeurer for looking into this issue (I am using version 1.1.1. and this version it works fine for negative time and positive real part of lambda.  

However, it looks like the default behavior is that the complex valued lambda has positive real part. Is it possible to assume negative real part of a complex valued symbol?

**Comment by jksuom** [comment]
match should probably be replaced by collect. It can handle sums with more than one term containing I.
