### ISSUE TITLE
regression: "factor" doesn't apply over matrix elements

### ISSUE THREAD

**Issue by cbm755** [sympy/sympy#14634]
Commands like `expand` and `factor` used to apply elementwise over matrices.  Factor no longer does so, I think after #13603, maybe commit 724929ed14d6b9c474d8386712d79a211385d19f

CC @Upabjojr

Example with v1.1.1:
```
>>> A = Matrix([[x**3 + x, x*(x+6)]])
>>> expand(A)
⎡ 3       2      ⎤
⎣x  + x  x  + 6⋅x⎦
>>> factor(A)
⎡  ⎛ 2    ⎞           ⎤
⎣x⋅⎝x  + 1⎠  x⋅(x + 6)⎦
```

But with  master, `factor` no longer works:
```
>>> factor(A)
⎡ 3               ⎤
⎣x  + x  x⋅(x + 6)⎦
```

**Comment by cbm755** [comment]
> Maybe inheriting Expr has changed the behaviour?

I thought the same, but I haven't looked any deeper.

@asmeurer @siefkenj can either of you confirm that `expand`/`factor`/`simplify`  should apply elementwise (`applyfunc`) to a Matrix?

**Comment by siefkenj** [comment]
`simplify` should pass through to `applyfunc`. I don't recall any code that handles `expand` or `factor`.

**Comment by cbm755** [comment]
Doesn't seem like the previous expand/factor behaviour was by design, so perhaps not an important regression.

**Comment by asmeurer** [comment]
Well `factor` has always worked on lists of elements (I never thought it was a good idea). 

```
>>> factor([x**2 + x, x**2 + 2*x + 1])
[x*(x + 1), (x + 1)**2]
```

So maybe it was related to that.
