### ISSUE TITLE
limit not exist 

### ISSUE THREAD

**Issue by RubelsiLopez** [sympy/sympy#14638]
what friends, I have been having a problem with sympy at the time of making a limit which would have to answer "does not exist" is returning the infinite value the code section would be this:

```
def limit(function,valor):
    x = Symbol('x')
    c=Limit(function, x, valor).doit()
    return c

```

I hope you can help me, thanks

**Comment by asmeurer** [comment]
I don't understand what your issue is here. Can you paste the expression you are using, and what output you expect?

**Comment by RubelsiLopez** [comment]
x = Symbol ('x')
a = Limit ((5-x) / (x-2), x, 2, "+"). doit ()
print (a)
oo
b = Limit ((5-x) / (x-2), x, 2, "-"). doit ()
print (b)
-oo
c = Limit ((5-x) / (x-2), x, 2) .doit ()
print (c)
oo here is the problem as investigated and check should leave a message as the limit does not exist or return any value equal to 0

**Comment by skirpichev** [comment]
> here is the problem

Someone didn't read the documentation? :-)  Again...  See docstring of limit().

**Comment by asmeurer** [comment]
@skirpichev if you're not going to be helpful, don't say anything at all. I won't say it again.

@RubelsiLopez you can get a two sided limit by using `dir='+-'`. See https://github.com/sympy/sympy/issues/14387 and linked issues about SymPy potentially changing the default from `dir='+'` to `dir='+-'`.

**Comment by skirpichev** [comment]
> if you're not going to be helpful

Could you define that exactly this means?  For me, pointing to the specific docstring is helpful enough.
