### ISSUE TITLE
Bug when solving multivariate polynomial systems with identical equations

### ISSUE THREAD

**Issue by apotschka** [sympy/sympy#14645]
Here's some output from [SymPy Live](http://live.sympy.org/), which runs SymPy 1.0:
```
>>> import sympy as sym
>>> x, y = sym.symbols('x, y')
>>> sym.solve([x*y - x - y], [x, y])
[{x: y/(y - 1)}]
>>> sym.solve([x*y - x - y, x*y - x - y], [x, y])
[]
```
The correct result of the last call to `solve` should be `[{x: y/(y - 1)}]` instead of `[]`.

**Comment by czgdp1807** [comment]
I would like to work on this issue. Can I make a PR on this, after working on its solution?. :-)

**Comment by oscargus** [comment]
This seems to have been solved in Diofant, see https://github.com/skirpichev/diofant/commit/cfdd6299131a98b032630223133ccd494e43c896 so it should be possible to find the solution there (although not in that commit).

**Comment by oscargus** [comment]
This appears to have been solved in the current master (not clear when and how). I'll add a test for it, which will close the issue.

```
sym.solve([x*y - x - y, x*y - x - y], [x, y])
Out[32]: [(y/(y - 1), y)]
```
