### ISSUE TITLE
simplify_logic hangs on on expression with 10 'or' statements

### ISSUE THREAD

**Issue by dcoukos** [sympy/sympy#14643]
Steps to reproduce issue: 
> from sympy.logic.boolalg import simplify_logic
> simplify_logic('a | b | c | d | e | f | g | h | i | j')

or 
> simplify_logic('a | b | c | d | e | f | g | h | i | j', form = 'dnf')

Then python hangs

**Comment by cboyer2016** [comment]
I would like to work on this issue. What should the expected output be?

**Comment by warnerjon12** [comment]
The source of the hanging is that the simplifier attempts to put the expression in minimal sum-of-product (DNF) or product-of-sum (CNF) form, and it does this using a truth table. Constructing a truth table for a function of n variables requires O(2^n) time. Hence it should only be used for shorter expressions, and larger expressions should not be simplified quite as much. I will make some changes, probably I will add a parameter for max variables to fully simplify an expression and then simplify the expression by halves, or some similar thing.

**Comment by warnerjon12** [comment]
Scrap that, converting to DNF or CNF form can generally require O(2^n) time for an arbitrary expression. What we need is a check to see if the expression already is in DNF or CNF form.

**Comment by oscargus** [comment]
I introduced an overrideable limit of eight variables (about five seconds on my computer) in #16134 so this should, in some sense, be fixed now.
