### ISSUE TITLE
ConditionSet solveset cannot calculate a complex I polynomials, return conditionSet

### ISSUE THREAD

**Issue by l-chenyao** [sympy/sympy#14642]
case 1：
```
from sympy import *
x = symbols('x',dtype = complex)
n1 = 0.5*x**3+x**2+0.5
solveset(n1,x)
```
_**result**_ : `{-2.20556943040059, 0.102784715200295 - 0.665456951152813*I, 0.102784715200295 + 0.665456951152813*I}`

case 2：
```
from sympy import *
x = symbols('x',dtype = complex)
n1 = 0.5*x**3+x**2+0.5+I  #**add I in the Polynomials**
solveset(n1,x)
```
**_result_**: `ConditionSet(0.5*x**3 + x**2 + 0.5 + I, x, Complexes(S.Reals x S.Reals, False))`

1. what is the means "Complexes(S.Reals x S.Reals, False)"
2. why case 2 cannot calculate a result ????
thanks you very much !

**Comment by oscargus** [comment]
This works in current master and returns:

```
FiniteSet(-2.28267560928153 - 0.312325580497716*I,
              -0.297354141679308 + 1.01904778618762*I,
               0.580029750960839 - 0.706722205689907*I)
```

(Also works symbolically if 0.5 is replaced by `S.Half`, but quite long.)

Will add a test and close.
