### ISSUE TITLE
Performance issue with lambdify() when it uses a list as argument

### ISSUE THREAD

**Issue by zenith997** [sympy/sympy#14654]
See the following example:

```
import sympy as sp
x , y = sp.symbols ('x, y')

expr = [x*y]
f1 = sp.lambdify([x,y], expr)
f2 = sp.lambdify([[x,y]], expr)
```

When I check the time that f1 and f2 take to perform a call on my computer, I see a great difference:

`%timeit f1(3,4)` 
Output:
181 ns ± 10 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)

`%timeit f2([3,4])`
Output:
6.02 µs ± 275 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)

When I use large lists, it can be 1000 times slower.

**Comment by asmeurer** [comment]
In the first case, the generated code is

```py
lambda x,y: ([x*y])
```

In the second case, it is

```py
lambda _0: (lambda x,y: ([x*y]))(*list(__flatten_args__([_0])))
```

[Here `__flatten_args__` is `sympy.utilities.flatten`](https://github.com/sympy/sympy/blob/d68f2996b04ab7aa214c05d8a1ae86a83ac43cc4/sympy/utilities/lambdify.py#L420).

So in addition to an extra function call, it is calling the `flatten` function. 

Probably this could be improved a lot simply by hard-coding the flattening, i.e., for the above, using `lambda _0: (lambda x,y: ([x*y]))(_0[0], _0[1])`.

In general, lambdify needs to be creating real functions, not just lambdas. That way, it could just generate

```py
def lambda_func(_0):
    x, y = _0
    return x*y
```

**Comment by asmeurer** [comment]
This is happening in the [lambdastr](https://github.com/sympy/sympy/blob/b4af86b9bd08c278c76f0079033e52ea342cc5f1/sympy/utilities/lambdify.py#L480) function in lambdify.py. It should be pretty easy to fix this to hard-code the unpacking.

**Comment by caley** [comment]
@asmeurer I can implement the hard-coded flattening if you like.  It needs to handle multiple nestings as well, I think.  For example
```
lambdastr([[x, [y, z]]], x*y*z)
```
should produce
```
'lambda _0: (lambda x, y, z: x*y*z)(_0[0], _0[1][0], _0[1][1])
```
