### ISSUE TITLE
Complex Number Multiplication Error

### ISSUE THREAD

**Issue by wferrick2016** [sympy/sympy#14652]
When multiplying two complex numbers it outputs the input by order of the real value of the complex number.
          Input:(1+2*I) * (3 +4*i)
          Output:  (1+2*_I_) * (3 +4*_I_)
The correct solution to this is -5 + 10_I_.

**Comment by wferrick2016** [comment]
The problem seems to be stemming from Sympy/sympy/core/mul.py not 100% sure though, I am currently trying to fix this and some help would be appreciated

**Comment by jksuom** [comment]
SymPy does not automatically expand the product, but can do that:
```
>>> e = (1+2*I)*(3 +4*I)
>>> e.expand()
-5 + 10*I
```

**Comment by wferrick2016** [comment]
O ok ill close the issue then
