### ISSUE TITLE
Issue with 3D line-to-dot distance

### ISSUE THREAD

**Issue by samkowskiykostya** [sympy/sympy#14668]
This is example on official site, which now fails even in simulator
>>> from sympy import Point, Line
>>> p1, p2 = Point(0, 0, 0), Point(1, 1, 1)
>>> s = Line(p1, p2)
>>> s.distance(Point(-1, 1, 1))
2*sqrt(6)/3
>>> s.distance((-1, 1, 1))
2*sqrt(6)/3

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/base/data/home/apps/s~sympy-live-hrd/49.400254913747479351/sympy/sympy/geometry/line.py", line 1187, in distance
    m = self.slope
  File "/base/data/home/apps/s~sympy-live-hrd/49.400254913747479351/sympy/sympy/geometry/line.py", line 540, in slope
    d1, d2 = (self.p1 - self.p2).args

**Comment by smichr** [comment]
This should be reported [here](https://github.com/sympy/sympy-live/issues) because it is not a problem in the current version of SymPy. (I'm not even sure it should be reported as a problem there, though, because when the code is updated there it should work.)

**Comment by sidhantnagpal** [comment]
This can be closed. SymPy live is updated to 1.2 in [sympy-live#120](https://github.com/sympy/sympy-live/pull/120).

**Comment by oscarbenjamin** [comment]
This example works fine in SymPy live now
