### ISSUE TITLE
Performance regression in Cholesky solve

### ISSUE THREAD

**Issue by moorepants** [sympy/sympy#14672]
Offending PR: https://github.com/sympy/sympy/pull/14474

Benchmark:

http://www.moorepants.info/misc/sympy-asv/#solve.TimeMatrixSolve2.time_cholesky_solve

**Comment by asmeurer** [comment]
The solve used to return a more compact solution, but it now returns a very large one (what appears to be the most general solution). 

According to the issue, the old algorithm was wrong. It assumed that symmetric and Hermitian were the same thing (they are only if the entries are real). However, if you multiply the old solution and simplify, you get the answer back (`simplify(A_sym*A_sym.cholesky_solve(b)) == b`).
