### ISSUE TITLE
error in integration of piecewise-constant function

### ISSUE THREAD

**Issue by nealeyoung** [sympy/sympy#14687]
Integrating a simply piecewise-constant function gives the wrong result:

```
from sympy import Symbol, Piecewise, integrate
x = Symbol('x', real=True)
Y = Piecewise((1, x <= 1), (2, True))
W = integrate(Y, x)
print("Y =", Y)
print("W =", W)
```

output is

```
Y = Piecewise((1, x <= 1), (2, True))
W = Piecewise((x, x <= 1), (2*x, True))
```

Note the discontinuity in W at x=1.  Surely, the integral should be continuous, specifically, it should be that W = Piecewise((x, x <= 1), (2*x-1, True))

Version information:

> About Jupyter Notebook
> Server Information:
> 
> You are using Jupyter notebook.
> 
> The version of the notebook server is: 5.4.1
> The server is running on this version of Python:
> Python 3.6.5 (default, Mar 29 2018, 15:37:32) 
> [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)]
> 
> Current Kernel Information:
> 
> Python 3.6.5 (default, Mar 29 2018, 15:37:32) 
> Type 'copyright', 'credits' or 'license' for more information
> IPython 6.3.1 -- An enhanced Interactive Python. Type '?' for help.

**Comment by smichr** [comment]
What version of SymPy are you running? It should be working in the current master.

**Comment by nealeyoung** [comment]
sympy.__version__  is 1.1.1

(installed using macports)

**Comment by nealeyoung** [comment]
Here's a workaround that worked for me: switching to definite integration:

```
from sympy import Symbol, Piecewise, integrate
x = Symbol('x', real=True)
x1 = Symbol('x1', real=True)
Y = Piecewise((1, x <= 1), (2, True))
W = integrate(Y, (x, 0, x1)).subs(x1, x)
print(Y)
print(W)
```

gives the correct output:

> Piecewise((1, x <= 1), (2, True))
> Piecewise((x, x <= 1), (2*x - 1, True))

**Comment by asmeurer** [comment]
I also get the right answer in master. It seems this has been fixed. I am hoping to get a release out "soon".
