### ISSUE TITLE
boolalg.SOPform() does not give the simplest form.

### ISSUE THREAD

**Issue by aiifabbf** [sympy/sympy#14700]
Hi, developers of Sympy.

@mpraiser and I were using `boolalg.SOPform()` to get the smallest sum of products. But it does not seem to give the *smallest* sum of products.

```python
In [136]: v
Out[136]: [A, B, C, D, E, F, G, H]

In [137]: q
Out[137]: 
(B ∧ D ∧ H ∧ ¬F) ∨ (B ∧ H ∧ ¬C ∧ ¬D) ∨ (B ∧ H ∧ ¬C ∧ ¬F) ∨ (B ∧ H ∧ ¬D ∧ ¬G) ∨
 (B ∧ H ∧ ¬F ∧ ¬G) ∨ (C ∧ G ∧ ¬B ∧ ¬D) ∨ (C ∧ G ∧ ¬D ∧ ¬H) ∨ (C ∧ G ∧ ¬F ∧ ¬H)
 ∨ (D ∧ F ∧ H ∧ ¬B) ∨ (D ∧ F ∧ ¬G ∧ ¬H) ∨ (B ∧ D ∧ F ∧ ¬C ∧ ¬H) ∨ (D ∧ E ∧ F ∧
 ¬B ∧ ¬C) ∨ (D ∧ F ∧ ¬A ∧ ¬B ∧ ¬C) ∨ (D ∧ F ∧ ¬A ∧ ¬C ∧ ¬H) ∨ (A ∧ B ∧ D ∧ F ∧
 ¬E ∧ ¬H)

In [138]: qq
Out[138]: 
(B ∧ D ∧ H ∧ ¬F) ∨ (B ∧ H ∧ ¬C ∧ ¬D) ∨ (B ∧ H ∧ ¬D ∧ ¬G) ∨ (C ∧ G ∧ ¬B ∧ ¬D) ∨
 (C ∧ G ∧ ¬D ∧ ¬H) ∨ (C ∧ G ∧ ¬F ∧ ¬H) ∨ (D ∧ F ∧ H ∧ ¬B) ∨ (D ∧ F ∧ ¬G ∧ ¬H) 
∨ (B ∧ D ∧ F ∧ ¬C ∧ ¬H) ∨ (D ∧ E ∧ F ∧ ¬C ∧ ¬H) ∨ (D ∧ F ∧ ¬A ∧ ¬C ∧ ¬H) ∨ (A 
∧ B ∧ C ∧ G ∧ ¬E ∧ ¬H)

In [139]: list(boolalg.truth_table(q, v)) == list(boolalg.truth_table(qq, v))
Out[139]: True

In [140]: len(q.args)
Out[140]: 15

In [141]: len(qq.args)
Out[141]: 12
```

`q` is the result `boolalg.SOPform()` gives me and it contains 15 product terms. `qq` is the result from another logic simplification program written by @mpraiser and it contains 12 product terms. They share the same truth table, but `qq` is obviously *simpler* than `q` since it contains less product terms than `qq`.

And when `boolalg.simplify_logic()` is performed on `q` and `qq`, they yield the same result as `q` as if `q` is the *simplest* already.

```python
In [155]: boolalg.simplify_logic(q, "dnf") == q
Out[155]: True

In [156]: boolalg.simplify_logic(qq, "dnf") == q
Out[156]: True
```

How can I solve this? Thanks:)

**Comment by oscarbenjamin** [comment]
Can you show the code you used to generate the above outputs? It's difficult to investigate this seeing only the output.

**Comment by oscargus** [comment]
The question if Quine-McCluskey is sub-optimal or if it is an issue in the Sympy implementation of Quine-McCluskey?

It should be possible to use the `qq` expression as a start here as that gives a longer expression compared to the original.

**Comment by oscargus** [comment]
May relate to #13649 in the sense that it is not clear what is minimized...

**Comment by oscargus** [comment]
I've found a simpler case where something similar happens:
```
In [48]: minterms = [[0, 1, 0, 0], [0, 1, 0, 1], [0, 1, 1, 0], [0, 1, 1, 1], [0, 0, 1, 1], [1, 0, 1, 1]]

In [49]: dontcares = [[1, 0, 0, 0], [1, 0, 0, 1], [1, 1, 0, 0], [1, 1, 0, 1]]

In [50]: print(SOPform([w, x, y, z], minterms, dontcares))
(x & ~w) | (y & z & ~w) | (y & z & ~x)

In [51]: print(SOPform([w, x, y, z], minterms))
(x & ~w) | (y & z & ~x)
```
As seen, the expression with don't cares gives a larger expression which should never happen.

The additional term is valid, but not required.

**Comment by oscargus** [comment]
After #16133 the solutions are:

```
((B & D & H & ~F) | (D & F & H & ~B) | (B & H & ~C & ~D) |
            (B & H & ~D & ~G) | (C & G & ~B & ~D) | (C & G & ~D & ~H) |
            (C & G & ~F & ~H) | (D & F & ~G & ~H) | (D & E & F & ~C & ~H) |
            (D & F & ~A & ~C & ~H) | (A & B & D & F & ~E & ~H))
```
and
```
 ((B | C | D) & (B | D | G) & (C | D | H) & (C | F | H) &
              (D | G | H) & (F | G | H) & (B | F | ~D | ~H) &
              (~B | ~D | ~F | ~H) & (D | ~B | ~C | ~G | ~H) &
              (A | H | ~C | ~D | ~F | ~G) & (H | ~C | ~D | ~E | ~F | ~G) &
              (B | E | H | ~A | ~D | ~F | ~G))
```
where the SOPform contains 11 terms, so one better.
