### ISSUE TITLE
lambdify should generate full functions

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#14702]
This has been discussed many times, but I don't think there's ever been a dedicated issue for it. 

Right now, lambdify generates a lambda, like `lambdify((x, y), x*y)` -> `lambda x, y: x*y`. This is where the function gets its name. However, this limits what can be done in a lambdified expression, because only expressions are allowed in a lambda. We already have several hacks in the lambdify code to work around this, for instance, a decorator to make sure ints are cast to NumPy arrays, and some code to hook in a docstring. 

It would be better if lambdify could generate a full function, like

```py
def lambdified_func(x, y):
    return x*y
```

This would let us do these various hacks directly as code generation. This would make things cleaner, and in some cases faster. It would also allow us to generate function with much improved introspection (for instance, we could give the function a real name and even inject its source into linecache so that `inspect.getsource` works). 

It would allow us to generate code constructs for expressions that aren't themselves expressions. For instance, the typecasting code could be generated only when it is needed. There may also be things that can't be code generated as expressions very easily (I'm not sure).

Some relevant issues:

https://github.com/sympy/sympy/issues/14654
https://github.com/sympy/sympy/issues/14671 (https://github.com/sympy/sympy/pull/14683)
https://github.com/sympy/sympy/issues/12463
https://github.com/sympy/sympy/issues/5642 (potentially)

**Comment by caley** [comment]
I've started looking this and have an initial working version(https://github.com/caley/sympy/commit/affbb726eb21f205f3e46ab411b36d2cdf8fe262).  Would it be useful to create a pull request for people to comment?  So far it improves on #14654 and addresses #12463.  I haven't thought about the other performance improvements, or refactoring yet, so would be happy to receive suggestions.

**Comment by asmeurer** [comment]
Yes, a pull request is the best way, even if the code is still work in progress. You can put `WIP` in the pull request description to indicate that it isn't ready for merging yet.

**Comment by Illviljan** [comment]
@asmeurer, Can this issue be closed now that #14713 is merged?

**Comment by asmeurer** [comment]
Yes
