### ISSUE TITLE
Symbol violates the commutativity of addition when it sometimes converts one-element arrays to scalar

### ISSUE THREAD

**Issue by NeilGirdhar** [sympy/sympy#14706]
```
from sympy import symbols
import numpy as np

for i in [2, 1]:
    z = np.zeros(i)
    xz = symbols('x') + z
    print(z.shape)
    print(xz.shape)
    print()
```
prints:
```
(2,)
(2,)

(1,)
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-165-14d0a2118753> in <module>()
      6     xz = symbols('x') + z
      7     print(z.shape)
----> 8     print(xz.shape)

AttributeError: 'Symbol' object has no attribute 'shape'
```

A scalar is  *definitely* not a numpy array with shape `(1,)`, `(1, 1)`, etc.
It's debatable whether a scalar is a numpy array with shape `()`, but I would simply return a numpy array in this case too.  Every library that has ever made the mistake of doing this dimension contraction had to eventually undo it (e.g., Theano).

The problem is that it's very easy to get the lone element from an array of size 1:
```
In [1]: o = np.ones([1 for _ in range(10)])

In [2]: o
Out[2]: array([[[[[[[[[[1.]]]]]]]]]])

In [3]: o.item()
Out[3]: 1.0
```
But it's very hard to go from an element and try to figure out what the shape it should have had and then give it the right shape.

Since this breaks my code, I can submit a patch within about a day if it will be accepted and if someone can point me to the right place in the code (I'm guessing tensor.py).

**Comment by bjodah** [comment]
Basic SymPy object don't carry a shape attribute, `ImmutableDenseNDimArray` does however, have you had a look at: http://docs.sympy.org/latest/modules/tensor/array.html#module-sympy.tensor.array ?

**Comment by NeilGirdhar** [comment]
Thanks for taking a look!  Unfortunately, I don't think `Array` helps me.

I have a function, say `f`, that transforms numpy arrays (say `A, B, C`) into one vector `v1`.  I want to pass in symbolic versions of those arrays to `f` to produce `v1`.  Let `v2` be a list of unique elements of `v1`.  From `v1` and v2`, I want to find a matrix `M` that maps `v1` to `v2`.

Each time `A, B, C` are passed (this time they are regular numpy arrays of numbers rather than symbolic variables) I don't need to store `f(A, B, C)`, but rather `M f(A, B, C)`, which is shorter.  In my case, it is much shorter.

Any inconsistencies between numpy and sympy complicate `f` greatly.

How is `Array` better than `ndarray` having `dtype=np.object` and containing `Symbol`?  It seems to me that the `ndarray` will do the usual `numpy` broadcasting that `f` does with regular `ndarray`s?  That seems to me to be better.

**Comment by asmeurer** [comment]
SymPy expressions aren't designed to interact directly with NumPy arrays. Generally if you want to work with NumPy arrays from SymPy expressions you should `lambdify` the expression first to create a compatible NumPy function.

**Comment by NeilGirdhar** [comment]
Playing with it a bit more, I see that SymPy seems to be violating the commutativity of addition:
```
z = np.zeros((1, 1))
z + symbols('x')
```
gives the right answer: `array([[x]], dtype=object)`, but
```
symbols('x') + z
```
gives `x`!!

**Comment by asmeurer** [comment]
Both SymPy and NumPy override the operators to try to "absorb" other objects into SymPy or NumPy (resp.) types. We could make `Symbol.__add__` return `NotImplemented` when it sees a NumPy array, but that could potentially break code that expects SymPy to convert NumPy arrays into SymPy NDimArray objects (the SymPy operators all just call `sympify`).

My best recommendation here is if you want to put SymPy objects (or any foreign objects, really) in NumPy arrays to always do it explicitly. Don't rely on NumPy's operators to create arrays automatically, because that will fail when the foreign objects have their own greedy operators. 

With that being said, perhaps making SymPy's NDimArray objects not automatically flatten would be a good change. Maybe @Upabjojr can comment more on why that behavior is there.

**Comment by NeilGirdhar** [comment]
> My best recommendation here is if you want to put SymPy objects (or any foreign objects, really) in NumPy arrays to always do it explicitly. 

How can I do the addition (`z + symbols(x)`) explicitly?  Using `np.broadcast_arrays` first?  It seems ugly.

> With that being said, perhaps making SymPy's NDimArray objects not automatically flatten would be a good change. Maybe @Upabjojr can comment more on why that behavior is there.

Thank you.  This is what I'm hoping for.

**Comment by asmeurer** [comment]
> How can I do the addition (z + symbols(x)) explicitly? Using np.broadcast_arrays first? It seems ugly.

Won't `z + numpy.array(x)` do what you want? I don't use NumPy that often, so I may be forgetting some of the details of broadcasting.

**Comment by NeilGirdhar** [comment]
> Won't z + numpy.array(x) do what you want?

Yup.

Nevertheless, I'd like to feel safe adding signals and arrays without worrying about order.  Therefore, I'm hoping that SymPy will keep addition commutative.

Also, since we can see that `ndarray + signal` does the right thing, I don't see why there should be a backwards compatibility question about changing `signal + ndarray` to match.

**Comment by Upabjojr** [comment]
Addition is commutative in SymPy. If you mix NumPy and SymPy objects, you could have unexpected behaviours (such as your example).

**Comment by NeilGirdhar** [comment]
@Upabjojr Yeah, that's a bug.

**Comment by Upabjojr** [comment]
The problem is that we cannot modify `__add__` in NumPy, so if the first object is a NumPy array, it will call the NumPy API.

If you find a way to make it call the SymPy API, please tell us.

**Comment by NeilGirdhar** [comment]
NumPy is not doing anything wrong.  When NumPy processes the addition it does the correct broadcasting and returns a numpy array whose shape is broadcasted shape.

The problem is that SymPy is doing this:
```
"""
    When all indices are contracted and components data are added to the tensor,
    accessing the data will return a scalar, no array object. In fact, arrays
    are dropped to scalars if they contain only one element.

    >>> A(i0, -i0)
    A(L_0, -L_0)
    >>> A(i0, -i0).data
    -18
"""
```
I looked, but can't seem to find where this is happening.  This is what needs to be removed.

**Comment by bjodah** [comment]
@NeilGirdhar since it is well documented (and presumably tested in the test suite) it doesn't really qualify as a bug. It may be bad design (I wouldn't be able to say since I hardly use that module), but I suspect that this behavior makes it easier to work with symbolic tensors, in which case it is really a trade-off: some APIs are more natural for certain workflows than others.

If the current implementation can be changed to facilitate another work-flow (in your case interacting with numpy arrays) we are usually happy to receive a pull-request fixing the issue. However, bear in mind that often it turns out that there are corner cases which makes it impossible to change the API without breaking backward compatibility (something SymPy is very reluctant to do, for good reasons).

In such cases the only viable way forward is to create a new class with an API matching the new work flow, and if that class is of general interest it usually a welcome addition to `SymPy`.

My familiarity with the `sympy.tensor` subpackage is superficial, but I believe `sympy.tensor.ndim_array` would match "numpy behaviour" better than what is found in `sympy.tensor.tensor`.

If you want to base your array object on numpy arrays rather than SymPy objects you can probably use yt's array as a starting point:
https://github.com/yt-project/yt/blob/938b91e623165723fd80d0efc96d450c939a1511/yt/units/yt_array.py#L305
they use SymPy with those arrays to perform dimensional analysis.

And since SymPy is in general backward compatible you should only need to write "adapters" once, and they should keep working even with new versions of SymPy.

**Comment by jksuom** [comment]
It seems to me that the conversion of numpy arrays of size 1 was solved in #13926. Only it does not work in this case (Symbol + ndarray)  because of the condition  `not strict`. Perhaps that should be discarded.

**Comment by NeilGirdhar** [comment]
> since it is well documented (and presumably tested in the test suite) it doesn't really qualify as a bug. It may be bad design (I wouldn't be able to say since I hardly use that module), but I suspect that this behavior makes it easier to work with symbolic tensors, in which case it is really a trade-off: some APIs are more natural for certain workflows than others.

The asymmetry (`x+y != y+x`) is not documented, and the asymmetry is a bug.  There are only two ways of repairing the asymmetry: change `x+y` to match `y+x` or vice versa.

> but I believe sympy.tensor.ndim_array would match "numpy behaviour" better than what is found in sympy.tensor.tensor.

An `ndarray` is just a rectangular list with arbitrary dimensions.  SymPy should not know anything about `ndarray`.  When doing operations on an `ndarray` containing SymPy objects, the usual NumPy broadcasting rules should apply—just like they do with `Fraction` (as shown above) and `Decimal`.  This has nothing to do with using a different SymPy type.

This has nothing to do with accommodating my workflow.  This has to do with restoring the invariants of `ndarray` operations.

> If you want to base your array object on numpy arrays rather than SymPy objects you can probably use yt's array as a starting point

Thanks for the pointer, but `YTarray` has nothing to do with this.  `YTarray` seems to have one symbol per array.  For me, each element is a symbol.  That's why I want to use a matrix of symbols.

>  And since SymPy is in general backward compatible you should only need to write "adapters" once, and they should keep working even with new versions of SymPy.

I totally agree with this principle.  However, we don't need an adapter here.  We don't need SymPy to do *anything* special with `ndarray`s of SymPy objects.  We just need SymPy to not discard dimensions of one-element `ndarray`s.  No other class type does that.

**Comment by NeilGirdhar** [comment]
> It is documented, but it's documented in the Python language docs, not the SymPy docs. See https://docs.python.org/3/library/numbers.html#implementing-the-arithmetic-operations. Any two libraries that do not explicitly know about each other will have that asymmetry if one of them doesn't cooperatively return NotImplemented for types it doesn't know about (as is the case for NumPy).

Okay, I see your point.  However, I consider NumPy's behavior to be the correct one, so all I would like SymPy to do is defer to NumPy by e.g. by returning `NotImplemented` when the RHS is an `ndarray`.

**Comment by asmeurer** [comment]
Maybe that was actually the point of the `strict` flag, but it still tries `float()`, which works on NumPy arrays with 1 element (that's NumPy's doing, not ours). So maybe we should leave the strict flag, but also make it so that length 1 arrays aren't converted to float when `strict=True` either.

**Comment by asmeurer** [comment]
Nice find. I agree that would be good to reference.

Do you want to give a try at a pull request implementing this? We just need to be careful that NumPy isn't imported in `sympify` if it isn't imported already (just copy what the existing numpy conversion code does). The [development workflow](https://github.com/sympy/sympy/wiki/Development-workflow) will help if you're new to the process.

**Comment by asmeurer** [comment]
Also, as noted in the other issue, I think it should continue to work if the array has rank 0 (`array.shape == ()`). Do you foresee any problems with that?

**Comment by NeilGirdhar** [comment]
I'm happy to submit a pull request.  Do you know where this conversion to scalar is happening?

**Comment by asmeurer** [comment]
I guess it's [here](https://github.com/sympy/sympy/blob/fb0d290816dcaefc1bc874dd7380e4ceba8af1d4/sympy/core/sympify.py#L59) and also [here](https://github.com/sympy/sympy/blob/fb0d290816dcaefc1bc874dd7380e4ceba8af1d4/sympy/core/sympify.py#L318) (I didn't double check, though).

**Comment by NeilGirdhar** [comment]
https://github.com/sympy/sympy/pull/14720
