### ISSUE TITLE
Derivative of _diff_wrt object treats object as scalar

### ISSUE THREAD

**Issue by varkor** [sympy/sympy#14719]
In https://github.com/sympy/sympy/pull/14221 it was decided that the default behaviour for `_diff_wrt` objects should be to treat the object as a completely unknown variable (rather than an unknown scalar).

```python
class Test(Expr):
	_diff_wrt = True
    # ...
```
Current behaviour:
```
In:  diff(2*t, t)
Out: 2
```
Expected behaviour:
```
In:  diff(2*t, t)
Out:
   d
───────(2 Test())
dTest()
```
cc https://github.com/sympy/sympy/pull/14221

**Comment by asmeurer** [comment]
See https://github.com/sympy/sympy/pull/14221#issuecomment-385788533

**Comment by asmeurer** [comment]
So as I said, the dummy substitution aspect of _diff_wrt = True should be abstracted somehow. This will probably require a new API. Or maybe the fix can be done in another way (I haven't dug deeper than this).

**Comment by smichr** [comment]
Think if the attribute `is_symbol` as meaning `not a scalar`:

```python
>>> class Test(Expr):
...     _diff_wrt = True
...     is_symbol = True
...
>>> t=Test()
>>> (3*t).diff(t)
3*Derivative(Test(), Test())
```

So together the attributes mean "you can differentiate wrt to it and should (or should not) treat it like a symbol when you do".

**Comment by smichr** [comment]
This can be closed after a few days to give people time to see how this can work.

**Comment by varkor** [comment]
@smichr: I'm not so familiar with the attributes, but not being a symbol doesn't intuitively imply "scalar" to me (for example: matrices, which were what led to this conversation initially).

**Comment by smichr** [comment]
I agree -- please take a look at the last commit in #15049
