### ISSUE TITLE
Better documentation for evalf(subs=...)

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#14732]
See https://stackoverflow.com/questions/50439037/what-exactly-is-the-subs-argument-of-the-evalf-method-of-sympy-expression-fo. The answers there are very confused about what the `subs` argument of `evalf` does. I tried to give a good explanation in [my own answer](https://stackoverflow.com/a/50459066/161801). But we should also improve the docstring of `evalf`, as well as the [evalf section of the tutorial](http://docs.sympy.org/latest/tutorial/basic_operations.html#evalf), to clarify why you would want to use `expr.evalf(subs=...)` over `expr.subs(...).evalf()` or `expr.evalf().subs(...)`.

**Comment by asmeurer** [comment]
Also this issue doesn't help the situation https://github.com/sympy/sympy/issues/6974

**Comment by 0110G** [comment]
I am new to open sourcing and would like to work on this issue.

**Comment by avishrivastava11** [comment]
@asmeurer I have made a PR which solves this issue. Pls review and merge if there's nothing to add.
