### ISSUE TITLE
LaTeX printing inconsistency with greater than two multiplied numerators.

### ISSUE THREAD

**Issue by gdahlm** [sympy/sympy#14743]
# Problem

When using `LaTeX=True` representation changes in undesirable ways which are inconstant from other printing methods.

# Summary

Given Newton's gravity formula `G*M*m/R**2` The ancillary `Pow()` function displaces numerators when more than two are present.  This happens despite attempts to use parentheses, reorder `srepr()` output, or wrap the equation in `Mul()`.

# Detailed Information

As this is _LaTeX_ specific, and the behavior is as expected with two terms in the denominator it should be relatively minor change to fix.

## Input:
```py
>>> sympify(G*M*m/R**2)
```
## Desired Output:
![gravrhc](https://user-images.githubusercontent.com/1113240/40526760-70dd93e6-5f9d-11e8-8c51-c494594702c7.png)

## Actual Output:
![image](https://user-images.githubusercontent.com/1113240/40526385-08aad9ca-5f9b-11e8-9e80-22444ee61c37.png)

## Additional troubleshooting performed: 
Adding non-visible terms to the denominator like `G*M*m/(R**2+1-1)`  or `G*M*m/(R*R)`does not change the behavior but adding and additional term that is not _exponentiation_ does.

```py
>>> sympify(G*M*m/(R**2+1))
```
![image](https://user-images.githubusercontent.com/1113240/40527093-4ec95464-5f9f-11e8-9c33-997be4ccb197.png)

This seems to result in the proper behavior when additional terms are added to the numerator as long as the order of operations is preserved.

```py
sympify(G*M*m*x*y*z/(R**2+1))
```
![image](https://user-images.githubusercontent.com/1113240/40527142-ab3b3a5a-5f9f-11e8-9394-abbe4a8dcee4.png)

# Steps to reproduce:
```py
>>> from sympy import *
>>> G, M, m, R = symbols ("G M m R")
>>> sympify(G*M*m / R**2)
G*M*m/R**2
>>> init_printing(use_latex=False)
>>> sympify(G*M*m / R**2)
G⋅M⋅m
─────
   2 
  R  
>>> srepr(G*M*m / R**2)
"Mul(Symbol('G'), Symbol('M'), Pow(Symbol('R'), Integer(-2)), Symbol('m'))"
>>> init_printing(use_latex=True)
"""Simulated Output, image attached.
G⋅M
───⋅m
   2 
  R
""" 
>>> init_printing(use_latex=False,use_unicode=False)
>>> srepr(G*M*m / R**2)
G*M*m
-----
  2 
 R  
```

## Software versions:
Ubuntu 18.04 LTS
Python 3.6.3
sympy==1.1.1
jupyter-qtconsole==4.3.1
jupyter-notebook==5.5.0
ipython==6.4.0

**Comment by asmeurer** [comment]
Looks like this is fixed in SymPy master:

```py
>>> latex(sympify("G*M*m/R**2"))
'\\frac{G M m}{R^{2}}'
```

Please reopen if you still see issues in SymPy master. We are working on a release that should be out "soon".
