### ISSUE TITLE
Should lambdify per default evalf() the input?

### ISSUE THREAD

**Issue by randolf-scholz** [sympy/sympy#14757]
Consider the following MWE:

    import time
    import sympy as sp
    
    x = sp.symbols("x")
    c = sp.sin(1)*sp.exp(2)-sp.atan(3)
    g1 = sp.lambdify(x, x*c        , 'numpy')
    g2 = sp.lambdify(x, x*c.evalf(), 'numpy')
    
    t = time.time()
    for k in range(1000000):
        temp = g1(k)
    print(time.time() - t)
    
    t = time.time()
    for k in range(1000000):
        temp = g2(k)
    print(time.time() - t)

Usually the goal of `lambdify` is to create a lambda function that can be rapidly evaluated in numpy. However if one forgets to `evalf()` the input the default behaviour can lead to big performance deficits. 

It is counter-intuitive (at least to me) that `lambdify` doesn't perform this crucial pre-processing step by default.

**Comment by asmeurer** [comment]
It probably makes sense for the NumPy backend. For other backends, like mpmath, you definitely don't want to do that.
