### ISSUE TITLE
IndexError from dsolve(Eq(y(x).diff(x)**2,9/4*(1+cos(2*y(x)))**2),y(x))

### ISSUE THREAD

**Issue by vloddos** [sympy/sympy#14760]
Can't solve the ode: y'^2=9/4\*(1+cos(2y))^2
But it can solve this ode in the other form: y'^2=9\*cos(y)^4

from sympy import dsolve,Function,cos
from sympy.abc import x

y=Function('y')
dsolve(Eq(y(x).diff(x)**2,9/4\*(1+cos(2*y(x)))**2),y(x)) #IndexError occurs

**Comment by asmeurer** [comment]
Here is the full traceback

```pytb
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "./sympy/solvers/ode.py", line 664, in dsolve
    return _helper_simplify(eq, hint, hints, simplify, ics=ics)
  File "./sympy/solvers/ode.py", line 689, in _helper_simplify
    sols = solvefunc(eq, func, order, match)
  File "./sympy/solvers/ode.py", line 5510, in ode_lie_group
    sol = sol[0]
IndexError: list index out of range
```

**Comment by jksuom** [comment]
This is the last piece of code:

                try:
                    sol = solve([r - rcoord, s - scoord], x, y, dict=True)
                except NotImplementedError:
                    continue
                else:
                    sol = sol[0]
 
NotImplementedError is not raised for an empty solution that results from an unevaluated integral.
```
(Pdb) p sol
[]
(Pdb) p scoord
Integral(cos(_y)**(-2.0), _y)
```
The floating point exponent seems to arise from floating point coefficients in Lie group methods.
```
> /home/jks/test/sympy/sympy/solvers/ode.py(5813)lie_heuristic_abaco1_simple()
-> fy = exp(integrate(factor, y))
(Pdb) p integrate(factor, y)
2.0*log(cos(_y))
```
There will be no error if 9/4 is replaced by the rational number `S(9)/4`.

**Comment by oscarbenjamin** [comment]
Should this be considered a bug in `integrate` rather than `dsolve`?

```julia
In [12]: integrate(cos(y)**-2)
Out[12]: 
sin(y)
──────
cos(y)

In [13]: integrate(cos(y)**-2.0)
Out[13]: 
⌠              
⎮    -2.0      
⎮ cos    (y) dy
⌡              
```

**Comment by asmeurer** [comment]
dsolve should never raise IndexError. 

The integral probably doesn't compute because SymPy treats the float 2.0 as unequal to exact integer 2, and SymPy can't compute the integral of `cos(x)**a`.

**Comment by Mohitbalwani26** [comment]
Example mentioned in this issue now works so shouldn't this issue be closed?
