### ISSUE TITLE
Implementation of `multivariate partial fraction decomposition`

### ISSUE THREAD

**Issue by ashishkg0022** [sympy/sympy#14763]
On performing apart on some expression I get a NotImplementedError. 
For example: 
```
apart(1/((a + c*x**(2*n))*(d + e*x**n)))
```
In mathematica ouput for above is `e^2/((c d^2+a e^2) (d+e x^n))-(c (-d+e x^n))/((c d^2+a e^2) (a+c x^(2 n)))` .
It will be good if it's implemented.

**Comment by asmeurer** [comment]
There is already an issue for this https://github.com/sympy/sympy/issues/6246

**Comment by jksuom** [comment]
If there are several variables, `apart` should be given another argument.

    apart(1/((a + c*x**(2*n))*(d + e*x**n)), x**n)

**Comment by ashishkg0022** [comment]
Thanks @jksuom . 
But there are other expressions like `(f*x)**m*(d + e*x**2)**q/(a + b*x**2 + c*x**4)` . Passing `x**2` or `x**4` is not resulting in any simplification.

**Comment by jksuom** [comment]
`apart` only works with rational functions of one variable (that may be an expression like `x**n`). In case of `(f*x)**m*(d + e*x**2)**q/(a + b*x**2 + c*x**4)`, the numerator is not a rational function of `x` because of the variable exponents `m` and `q`. It seems that the expression cannot be written as a rational function of any single variable.

**Comment by AmplitudeGravity** [comment]
If you want multi variable apart, the only version in market is using Mathematica,  [multivariateapart.wl](https://gitlab.msu.edu/vmante/multivariateapart) .
Looking forward some experts can transfer it to sympy and Julia's symengine.jl or symbolics.jl .
Even the Mathematica version, the package has a drawback, you can not choose the variable to perform the apart. The current version naively  take all the symbolic variables appeared in your function.

**Comment by oscarbenjamin** [comment]
It is better to comment on the open issue gh-6246
