### ISSUE TITLE
Spurious solutions when solving equation involving Abs(x)/x

### ISSUE THREAD

**Issue by ethankward** [sympy/sympy#14779]
```
>>> from sympy import *
>>> x = Symbol('x', real=True)
>>> e = sqrt(x**4 - 130*x**2 + 1089) + sqrt(x**4 - 130*x**2 + 3969) - 96*Abs(x)/x
>>> solve(e, x)
[0, -sqrt(130), sqrt(130)]
```

Only `sqrt(130)` is valid.

**Comment by czgdp1807** [comment]
I would like to work on this issue. I have found a very basic solution to fix this kind of issue.

**Comment by Yathartha22** [comment]
@czgdp1807 go ahead and create a PR with whatever fix you think is appropriate. It will help others to see whether the changes you made are good enough or not.

**Comment by czgdp1807** [comment]
@Yathartha22 Sure, I will make a PR as soon as possible.

**Comment by czgdp1807** [comment]
@Yathartha22 
After going through code of solvers.py I found that what I was trying to implement was already implemented in `_solve(f, *symbols, **flags)`. However, when I tried to solve the given equation in the issue by implementing, `_solve(e,x)`, it threw the following error,
`NameError: name '_solve' is not defined`.
Should I proceed with a PR or _solve method is sufficient and this issue should be closed?
Waiting for your comment. :-)

**Comment by asmeurer** [comment]
I'm not following what your proposed fix is. 

The problem is in the check machinery, which should be filtering 0 and -sqrt(130) because they aren't valid solutions.

**Comment by Yathartha22** [comment]
> when I tried to solve the given equation in the issue by implementing, _solve(e,x)

Why you are trying to implement  `_solve(e, x)`, when it's already present. As @asmeurer mentioned there might be some problem in the way `check` filters out spurious values. Try to figure out what and where it goes wrong.

**Comment by czgdp1807** [comment]
@Yathartha22 and @asmeurer I have made a PR on solving this issue at https://github.com/sympy/sympy/pull/14851.
It is failing some tests on my local system. Please help me in removing those failures and give your feedback on my code that I have added.
Thanks.
