### ISSUE TITLE
Organize the wiki sidebar

### ISSUE THREAD

**Issue by jlumpe** [sympy/sympy#14776]
The wiki contains nearly 500 pages, which are all listed in alphabetical order in the sidebar with no other form of organization. There is of course a lot of useful information in there but as it stands it is very difficult to find without using the search box.

I think this could be solved nicely by creating a custom sidebar. The pages could be grouped into a smaller number of general categories, each with its own index page that is linked to in the sidebar.

I can do this myself if it sounds like something that would be useful.

**Comment by jksuom** [comment]
I think that it is a good idea. You are welcome to do that.

**Comment by jlumpe** [comment]
Great, I'll try to put together a series of Wiki pages to get everything organized, including a sidebar page that won't actually be set as the sidebar until I finish and submit it for review.
