### ISSUE TITLE
Unexpected increasing of precision when using .evalf() method on a Piecewise function 

### ISSUE THREAD

**Issue by LostFan123** [sympy/sympy#14787]
This
```python
import sympy as sym

print((sym.S(58) / 7).evalf())
```  
will give `8.28571428571429`.  As docs say, 15 digits is a standard precision.

But if I put this fraction in a `Piecewise` and apply `.evalf()`:  
```python
x = sym.Symbol('x')
f = sym.Piecewise((x, x < 1),
                  ((sym.S(58) / 7), True))
print(f.evalf())
```
this will give:  
```python
Piecewise((x, x < 1), (8.2857142857142857142857142857142857142857142857142857, True))
```
Looks like a bug to me.

**Comment by asmeurer** [comment]
Looks like `Piecewise._eval_evalf` passes the `prec` to `evalf`, but `prec` is the binary precision and `evalf` takes the decimal precision. It needs to call `_eval_evalf` instead. Should be easy to fix.

**Comment by iamarshsingh** [comment]
I would like to work on this.

**Comment by avishrivastava11** [comment]
I want to take this issue if still open..

**Comment by avishrivastava11** [comment]
@asmeurer 
when you said 
>  It needs to call ` _eval_evalf `instead.
what does " it " refer to here ?
Because I have another solution by which `prec` will first get converted to decimal precision and then get passed on to `evalf` .
But I don't understand what you mean by 
>  It needs to call ` _eval_evalf `instead.
So pls explain what "it" is referring to, here.

**Comment by avishrivastava11** [comment]
@asmeurer 
I don't understand what exactly " it " was referring to in the below statement. 
>  It needs to call ` _eval_evalf `instead.

pls explain

**Comment by avishrivastava11** [comment]
@asmeurer 
I don't think calling `_eval_evalf` would be correct as you suggested earlier as then it would send the function into an infinite loop resulting in an error.
instead we could call `N` inside `evalf` which would then eventually result in the default decimal precision of (earlier binary) `prec`.
Pls let me know if I am wrong.

**Comment by iamarshsingh** [comment]
@asmeurer Please evaluate my pull request. I have given a small description of the issue and solution to it in the pull request. Thank You
