### ISSUE TITLE
Docstring typo in TensorProduct()

### ISSUE THREAD

**Issue by pozdneev** [sympy/sympy#14794]
In `TensorProduct()`, the prefix "non-" should not be the last word on a [line](https://github.com/sympy/sympy/blob/c2360561e9fe2119791149f5b097bd860e0ab4cc/sympy/physics/quantum/tensorproduct.py#L59):
![image](https://user-images.githubusercontent.com/640788/41286242-64bb2d54-6e47-11e8-8901-e612ebc001cf.png)

That is rendered as "non- commutative" (notice the space between a dash and a word that follows):
![image](https://user-images.githubusercontent.com/640788/41286123-0a80d92e-6e47-11e8-9dfa-76423d9f4834.png)

**Comment by sidhantnagpal** [comment]
Fixed in #14795
