### ISSUE TITLE
Limit involving log(factorial(x)) incorrect

### ISSUE THREAD

**Issue by ethankward** [sympy/sympy#14793]
From [here](https://mathematica.stackexchange.com/questions/174966/bug-wrong-limit-in-mathematica-11-1-1-and-current-wolframalpha), SymPy also gets this wrong but in a different way:

```
>>> from sympy import *
>>> x = Symbol('x')
>>> e = ((x + S(1)/2) * log(x) - x + log(2*pi)/2 - log(factorial(x)) + S(1)/(12*x))*x**3
>>> limit(e,x,oo)
-oo
>>> N(e.subs(x,1000))
0.00277777698412758
```

The correct answer is `1/360`.

**Comment by 0110G** [comment]
I am new to open source and wanted to ask what is S(1)  in the above code. Please help

**Comment by ethankward** [comment]
`S` is a shortcut for `sympify` that turns a value into a SympPy object.

**Comment by Naba7** [comment]
The correct answer is ``0.00277777698412758`` and if ``1/360`` is rounded it results to the output.
The error is in Mathematica not in sympy.

**Comment by Naba7** [comment]
I guess thats all and this issue can be closed.

**Comment by oscarbenjamin** [comment]
SymPy gives `-oo` for the limit so that isn't correct.

**Comment by Naba7** [comment]
The sign is negative because in the example ``-log(factorial(x))`` is used.
``log(factorial (x))`` gives an output as ``log(*a large number)`` . I
think it shows ``oo`` when we add or multiply.

**Comment by Naba7** [comment]
Ahh! sorry I get it. The problem is with limit() not with subs().
Can I take up this issue?

**Comment by Naba7** [comment]
subs() returns the actual value while limit() declares it to be ``oo``

**Comment by sachin-4099** [comment]
Works correctly on the current master:
```
In [1]: e = ((x + S(1)/2) * log(x) - x + log(2*pi)/2 - log(factorial(x)) + S(1)/(12*x))*x**3

In [2]: limit(e, x, oo)
Out[2]: 1/360
```
