### ISSUE TITLE
Exception during evaluation of limit (only locally, not in the live version)

### ISSUE THREAD

**Issue by pruvisto** [sympy/sympy#14811]
The following limit correctly evaluates to ∞ in the live version of sympy at http://live.sympy.org:

    limit(((1 + (Rational(2,3) ** (x + 1))) ** (2 ** x)) / (2 ** (Rational(4,3) ** (x - 1))), x, oo)

However, in `isympy` on my machine, I get the following exception

    [...]
    
    /usr/lib/python3.6/site-packages/sympy/series/gruntz.py in gruntz(e, z, z0, dir)
        662     # It might be nicer to rewrite the exactly to what they were initially,
        663     # but that would take some work to implement.
    --> 664     return r.rewrite('intractable', deep=True)
    
    AttributeError: 'NoneType' object has no attribute 'rewrite'

This happens both in the lates version 1.1.1 and in the version 1.0, which `live.sympy.org` uses. I do have a slightly different Python version (2.7.15 on my machine vs. 2.7.12 in the live version).

I have no idea why this different behaviour occurs. In any case, that limit is simple enough; Gruntz's algorithm (which is apparently used by sympy) should not have any problems with it, so this looks like a bug to me.

**Comment by smichr** [comment]
reopen per comments in #18990
