### ISSUE TITLE
PyPy test failures in combinatorics (ValueError: there were repeated elements.)

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#14827]
See for instance https://travis-ci.org/sympy/sympy/jobs/395547541

Here is the full traceback

```pytb
_______ sympy/combinatorics/tests/test_perm_groups.py:test_presentation ________
  File "/home/travis/.venv/site-packages/sympy-1.1.2.dev0-py2.7.egg/sympy/utilities/runtests.py", line 1270, in _timeout
    function()
  File "/home/travis/.venv/site-packages/sympy-1.1.2.dev0-py2.7.egg/sympy/combinatorics/tests/test_perm_groups.py", line 861, in test_presentation
    G = P.strong_presentation()
  File "/home/travis/.venv/site-packages/sympy-1.1.2.dev0-py2.7.egg/sympy/combinatorics/perm_groups.py", line 4086, in strong_presentation
    t = block_homomorphism(K_s, block)
  File "/home/travis/.venv/site-packages/sympy-1.1.2.dev0-py2.7.egg/sympy/combinatorics/homomorphisms.py", line 417, in block_homomorphism
    images = {g: Permutation([b[p[i]^g] for i in identity]) for g in group.generators}
  File "/home/travis/.venv/site-packages/sympy-1.1.2.dev0-py2.7.egg/sympy/combinatorics/homomorphisms.py", line 417, in <dictcomp>
    images = {g: Permutation([b[p[i]^g] for i in identity]) for g in group.generators}
  File "/home/travis/.venv/site-packages/sympy-1.1.2.dev0-py2.7.egg/sympy/combinatorics/permutations.py", line 924, in __new__
    raise ValueError('there were repeated elements.')
ValueError: there were repeated elements.
```

The failure only occurs on PyPy (I haven't seen it in the normal Python builds). 

@valglad @RavicharanN would you be able to get a fix for this soon? I'd like to get a release candidate out for 1.2 very soon, and this is a blocker.

**Comment by valglad** [comment]
I'll have a look at this tomorrow but not sure how long tracing down the bug and fixing will take. How soon would you like to get a release?

**Comment by asmeurer** [comment]
I'd like to have a release candidate by the end of the month and a final release by scipy.

**Comment by RavicharanN** [comment]
Looks like `{Permutation(0, 3, 1, 2): Permutation(1, 1), Permutation(3)(0, 1): Permutation(1, 1), Permutation(0, 1)(2, 3): Permutation(1, 0), Permutation(2, 3): Permutation(0, 0)}` are the repeated elements produced in `images = {g: Permutation([b[p[i]^g] for i in identity]) for g in group.generators}`. Can we just convert the lists `[1, 1]` and `[0, 0]` to sets before converting them to `Permutation(1, 1)` and `Permutation(0, 0)`? Or, is it a problem with `[b[p[i]^g] for i in identity]` producing multiple elements?

**Comment by valglad** [comment]
@asmeurer Does this happen in every PyPy build? I don't think any of that code uses randomization anywhere so it should be consistent. Perhaps something to do with how elements are ordered within a dictionary? I don't know much about how PyPy is different from CPython...
Also, I'm struggling to get it to work locally to run tests. I've installed PyPy and SymPy via `sudo pypy -m pip install sympy` and yet when I try to run `pypy somefile.py`, I get `no module named sympy`. Any idea why that would be? I don't think I can work out what's going on until I can run it locally and stackoverflow hasn't offered much insight so far.

**Comment by RavicharanN** [comment]
If PyPy is installed, @valglad this worked for me, `pypy bin/test sympy/combinatorics/tests/test_perm_grps.py`
It'll run the tests in pypy env

**Comment by valglad** [comment]
@RavicharanN Thanks, that worked and interestingly, now everything works even when I do it my usual way. Not sure what happened there but that doesn't matter. :+1:
