### ISSUE TITLE
Weird bug with simple ccode and Max and Abs functions

### ISSUE THREAD

**Issue by mdavidovic** [sympy/sympy#14829]
ccode should replace Max with fmax and Abs with fabs consistently. But here is what happens with:
ccode( Max( Abs(y), Abs(x) ) )
Output is 'fmax(Abs(x), fabs(y))'
Abs is not replaced in both cases! Can someone explain what is going on and how to fix this?

**Comment by mdavidovic** [comment]
I quick fixed it by adding key value pair in dict "known_functions_C89" in ccode.py file, "Max": "fmax".
This also fixes autowrap with cython backend that was originally failing.

**Comment by bjodah** [comment]
On SymPy master, this is what I get:
```
In [1]: ccode(Max(Abs(y), Abs(x)))
Out[1]: 'fmax(fabs(x), fabs(y))'
```

**Comment by mdavidovic** [comment]
I was using latest anaconda python 3.6 and sympy 1.1.1 installed via conda. On windows 10.

**Comment by bjodah** [comment]
OK, so until v1.2 is released I guess you can provide your own "known_function". Alternatively install the master branch if that is a viable option for you.
