### ISSUE TITLE
sympy.factor bug

### ISSUE THREAD

**Issue by zbzhen** [sympy/sympy#14842]
from sympy import factor, var
x = var("x")
a = 0.1 * 0.1 * x * x - 1
print factor(a)

# In SymPy 1.1.1 
# Wrong answer 1.0 * (0.01 * x - 0.1) * (0.01 * x + 0.1)
# Please check it.

**Comment by jksuom** [comment]
This was fixed by #13198:
```
In [1]: a = 0.1 * 0.1 * x * x - 1

In [2]: factor(a)
Out[2]: 1.0⋅(0.1⋅x - 1.0)⋅(0.1⋅x + 1.0)
```
