### ISSUE TITLE
Add test that no files are executable

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#14845]
In https://github.com/sympy/sympy/pull/14844 I fixed an issue where some files in the vector module were had the executable bit set. We should add a test that runs in Travis that goes through all the files in git and makes sure none have an executable bit set, unless they are in a whitelist (anything in `bin/` should be whitelisted, `setup.py`, a few scripts in `release/`, maybe something else). You can use `git ls-files -s` to list the files in git with their permissions.

It should be a new script in `bin` that runs in one of the Travis builds.

**Comment by A-Hilaly** [comment]
@asmeurer Can i take work on this ?

**Comment by A-Hilaly** [comment]
Hey ! Can i work on this ? @asmeurer

**Comment by ramvenkat98** [comment]
@asmeurer 

Hi, 

I would like to work on this and have a couple of questions about how to proceed. Is the task to write a Python script that asserts that only files in a particular whitelist have an executable bit set? If so, how do I determine what files are in this whitelist (besides ones like those in bin/ and setup.py as pointed out)? Also, how should I add this script to one of the Travis builds; looking through the bin/ directory, it seems that test_travis.sh is where I should add this, but I'm not familiar with how to go about doing this correctly.

Thank you!

**Comment by asmeurer** [comment]
A good way to check is that if a file doesn't have a shebang line (like `#!/usr/bin/env python` or `#!/bin/bash`) then it shouldn't be executable, because executing it wouldn't even work anyway. In fact, the script could perhaps just check for that, instead of using an explicit whitelist.
