### ISSUE TITLE
bspline_basis behaviour with non-increasing knot vector

### ISSUE THREAD

**Issue by moesphere** [sympy/sympy#14843]
The bspline_basis function should always return a (piecewise) function, also in the case of a non-increasing knot vector, where it currently returns a zero object (e.g. to make the basis spline callable).

Example

```
from sympy import bspline_basis
from sympy.abc import x
tau = [2,2,2,2,2]
bspline_basis(3,tau,0,x)
```

**Comment by normalhuman** [comment]
The behavior seems correct to me. The return value of `bspline_basis` is **never** a function; it is a SymPy expression. `Piecewise(...)` is an expression, and so is `Integer(0)`. Neither of them is callable. Both of them can be evaluated with `.subs(x, value)`. Both can be made callable with `lambdify(x, expression)`. I do not see a reason to prefer Piecewise to a plain Integer(0).  

An example that has both kinds of expressions, all of them being treated in the same way:
```
from sympy import *
from sympy.abc import x
tau = [2, 2, 2, 3, 3, 3]
basis = [bspline_basis(1, tau, k, x) for k in range(len(tau) - 2)]
print(basis)
print([b.subs(x, 2.5) for b in basis])
lambdified_basis = [lambdify(x, b) for b in basis]
print([f(2.5) for f in lambdified_basis])
```
Here `basis` is
```
[0, Piecewise((-x + 3, (x >= 2) & (x <= 3)), (0, True)), Piecewise((x - 2, (x >= 2) & (x <= 3)), (0, True)), 0]
```
which with subs-evaluation becomes
```
[0, 0.500000000000000, 0.500000000000000, 0]
```
or, with lambdify conversion and subsequent evaluation, 
```
[0, array(0.5), array(0.5), 0]
```
No need to treat 0 different from the rest.

**Comment by moesphere** [comment]
Thanks for the answer!

I was using SymPy from Julia, where in the case for a non-increasing knot vector (as described above), a non-callable object is created. However, for other knot vectors (i.e. not non-increasing), a callable object is returned.
