### ISSUE TITLE
Issue in documentation of solve method of solvers.py

### ISSUE THREAD

**Issue by czgdp1807** [sympy/sympy#14849]
The following part is what I get when I use solve() on my system:
`>>> solve(x-y**2,x,y)`
`[{x:y**2}]`
The following part is written in the docstring of solve():
 `>>> solve(x - y**2, x, y)`
  `[(y**2, y)]`

Clearly, they don't match and I think it should be fixed.

**Comment by jksuom** [comment]
This is what I get on my system: 
```
>>> sympy.__version__
'1.2.1.dev'
>>> from sympy.abc import x, y
>>> solve(x-y**2,x,y)
[(y**2, y)]
```

**Comment by czgdp1807** [comment]
Thanks for your swift response @jksuom . I will close this issue as well as the PR associated with it.
