### ISSUE TITLE
WARNING cdn.mathjax.org end-of-life

### ISSUE THREAD

**Issue by Naereen** [sympy/sympy#14859]
Apparently, the current version of the documentation still uses the deprecated cdn.mathjax.org website to load MathJax
https://github.com/sympy/sympy/blob/f43d15e88174ec8cd6d61f2a16c6c50a3af0fde0/doc/src/conf.py#L35

The doc display wrongly all maths formula, see screenshot:
![cdn mathjax is dead](https://user-images.githubusercontent.com/11994719/42170260-553d18c2-7e16-11e8-987e-0f486207b8e4.png)

See https://www.mathjax.org/cdn-shutting-down/ for more details on migrating to another service.

> Basically, a simple find-and-replace of `http://cdn.mathjax.org/mathjax/latest/` (as is used right now) to `https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/` could probably be enough.

**Comment by Naereen** [comment]
Nobody to fix this please?

**Comment by sidhantnagpal** [comment]
I think some discussion has went into it. This will be fixed by #14379.

**Comment by Naereen** [comment]
OK, good to know. Good luck!

**Comment by oscarbenjamin** [comment]
Closing as looks like this was fixed by #14379

**Comment by asmeurer** [comment]
That PR wasn't merged. IIRC this was never fixed.

**Comment by oscarbenjamin** [comment]
Okay reopened

**Comment by oscarbenjamin** [comment]
The docs from
[https://docs.sympy.org/latest/index.html](https://docs.sympy.org/latest/index.html)
are currently using
`https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML-full`
as referred to at the start of this issue so it isn't fixed.

**Comment by oscarbenjamin** [comment]
According to [https://www.mathjax.org/cdn-shutting-down/](https://www.mathjax.org/cdn-shutting-down/) the CDN shut down two years ago. It's clearly still working though. I think I read somewhere that they put in a redirect...

**Comment by asmeurer** [comment]
If you go to https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML-full in your browser you can see it is being redirected in Javascript. I guess we should just replace the URL with the one being redirected to. 

I guess as far as getting the latest version goes we will have to manually update `conf.py` whenever MathJax does a release.

**Comment by oscarbenjamin** [comment]
It redirects to:
`https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js`

The Mathjax organisation recommends that same URL on this page:
[https://www.mathjax.org/cdn-shutting-down/](https://www.mathjax.org/cdn-shutting-down/)

The patch in #14379 also uses the same URL (except version is 2.7.2).

Stack exchange is also using that URL (currently version 2.7.5 from view source):
[https://meta.stackexchange.com/questions/293237/mathjax-cdn-cdn-mathjax-org-will-be-shutting-down](https://meta.stackexchange.com/questions/293237/mathjax-cdn-cdn-mathjax-org-will-be-shutting-down)

I think SymPy should use that with 2.7.5 i.e.:
`https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js`

**Comment by Naereen** [comment]
Hi guys, yes exactly!
It's what I said last July…
Can someone merge this PR #15955 and close this issue asap?
Thanks!
