### ISSUE TITLE
`Lambda` does not accept indexed symbols.

### ISSUE THREAD

**Issue by akash9712** [sympy/sympy#14852]
`Lambda` raises an TypeError when the variable argument passed is an indexed symbol. Example:
```
>>> x1 = Indexed('x', 1)
>>> x1.is_Symbol
False
>>> Lambda(x1, x1**2)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/akash/sympy/sympy/core/function.py", line 1659, in __new__
    raise TypeError('variable is not a symbol: %s' % i)
TypeError: variable is not a symbol: x[1]
```

**Comment by asmeurer** [comment]
I think you just need to change `is_Symbol` to `is_symbol`, though you should check that everything else works with Indexed too.

**Comment by avishrivastava11** [comment]
@asmeurer @akash9712  I am starting to work on this issue if there's no one else working already

**Comment by akash9712** [comment]
@udiptya999 What version are you using? The error appears for me on both the master branch and 1.2.

**Comment by udiptya999** [comment]
@akash9712 Actually I am using 1.1.1.

**Comment by say2sankalp** [comment]
Here 
`
In [2]: sympy.__version__
Out[2]: '1.2.1.dev'
`
The error still persist in 1.2, @udiptya999  working in yours thats kool.

```
In [1]: from sympy import Indexed

In [2]: x1 = Indexed('x',1)

In [3]: x1
Out[3]: x[1]

In [4]: x1.is_symbol
Out[4]: True

In [5]: x1.is_Symbol
Out[5]: False

In [6]: from sympy import Lambda

In [7]: Lambda(x1,x1**3)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-7-84499696e159> in <module>()
----> 1 Lambda(x1,x1**3)

/Users/sankalp/Dev/sympy/sympy/core/function.py in __new__(cls, variables, expr)
   1657         for i in v:
   1658             if not getattr(i, 'is_Symbol', False):
-> 1659                 raise TypeError('variable is not a symbol: %s' % i)
   1660         if len(v) == 1 and v[0] == expr:
   1661             return S.IdentityFunction

TypeError: variable is not a symbol: x[1]
```

**Comment by say2sankalp** [comment]
The fix was easy,
in version 1.1.1  
the line 
   is_Symbol= true was present however in 
version 1.2.1.dev 
  this line was missing from indexed.py file
which was leading to error @akash9712  
I proposed fix and did request, @asmeurer  and all can close this if my fix satisfies the problem.

**Comment by say2sankalp** [comment]
@akash9712   can you explain for referencing ?

**Comment by akash9712** [comment]
@say2sankalp The reference is mentioned in the description of the PR. 
The issue no longer appears in the master branch. Closing this now.
