### ISSUE TITLE
rf(0, n).rewrite(factorial) is wrong

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#14871]
```py
>>> rf(0, n).rewrite(factorial)
0
>>> rf(0, 0)
1
>>> rf(0, -1)
-1
```

This leads to the wrong result:

```
>>> Sum((S(1)/10)**m*RisingFactorial(0, m)/factorial(m), (m, 0, oo)).rewrite(factorial).doit()
0
```

(the sum should be 1)

**Comment by ethankward** [comment]
The correct condition would be, for `x` and `k` integers, if `k` is positive, rewrite as `factorial(k + x - 1) / factorial(x - 1)`, if `k` is negative or `0`, rewrite as `(-1)**(-k) / factorial(-k)`. This fixes the problem but it means that the sum won't be evaluated at all since rewriting as factorial won't split the sum into two pieces (`m=0` and `m > 0`).

**Comment by asmeurer** [comment]
What if it made a piecewise if k doesn't have positive or negative assumptions? 

Anyway, the summation algorithms should probably be made to work with rf natively.

**Comment by ethankward** [comment]
Not exactly, piecewise sums are not evaluated either (a separate issue):

```
>>> e = 1/k**2
>>> print(Sum(e, [k, 1, oo]).doit())
pi**2/6
>>> e = Piecewise((1, Eq(k, 1)), (1/k**2, True))
>>> print(Sum(e, [k, 1, oo]).doit())
Sum(Piecewise((1, Eq(k, 1)), (k**(-2), True)), (k, 1, oo))
```

**Comment by avishrivastava11** [comment]
@asmeurer can you help me find out what is going wrong in this only error in the PR made by @ethankward 
Maybe I can help fix it; But I'm unable to find the thing which is going wrong.
This is the link to the Travis test error https://travis-ci.org/sympy/sympy/jobs/400566016

**Comment by smichr** [comment]
This will return a Piecewise for the rewrite:
```diff
diff --git a/sympy/functions/combinatorial/factorials.py b/sympy/functions/combinatorial/factorials.py
index 7f58a28..6018aab 100644
--- a/sympy/functions/combinatorial/factorials.py
+++ b/sympy/functions/combinatorial/factorials.py
@@ -616,8 +616,11 @@ def _eval_rewrite_as_FallingFactorial(self, x, k, **kwargs)
:
         return FallingFactorial(x + k - 1, k)

     def _eval_rewrite_as_factorial(self, x, k, **kwargs):
+        from sympy import Piecewise, Ne
         if x.is_integer and k.is_integer:
-            return factorial(k + x - 1) / factorial(x - 1)
+            return Piecewise(
+                (factorial(k + x - 1) / factorial(x - 1), Ne(k, 0)),
+                (S.One, True))

     def _eval_rewrite_as_binomial(self, x, k, **kwargs):
         if k.is_integer:
```
The `Sum` would need more introspection to know that when it is dealing with binary conditions (one of which is a `Ne`) that the `Piecewise` can resolve to default value for the 
```python
>>> var('m', integer=True)
>>> Sum((S(1)/10)**m*RisingFactorial(0, m)/factorial(m), (m, 0, oo)).rewrite(factorial).doit()
Sum(Piecewise((0, Ne(m, 0)), (10**(-m)/factorial(m), True)), (m, 0, oo))
```
NOTE: if you fold that expression and evaluate it you don't get 1, however:
```python
Piecewise((0, Ne(m, 0)), (exp(1/10), True))
```

**Comment by smichr** [comment]
cf #3204
