### ISSUE TITLE
RecursionError: maximum recursion depth exceeded on integrate, sympy 1.1.1

### ISSUE THREAD

**Issue by nasser1** [sympy/sympy#14877]
cross posted at 

[stackoverflow](https://stackoverflow.com/questions/51218097/recursionerror-maximum-recursion-depth-exceeded-on-integrate-sympy-1-1-1)

>which python
/opt/anaconda/bin/python

>pip list | grep sympy
sympy                              1.1.1

```
>python
Python 3.6.5 |Anaconda, Inc.| (default, Apr 29 2018, 16:14:56) 
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.

from sympy import *
x=symbols('x');
integrate(exp(1-exp(x**2)*x+2*x**2)*(2*x**3+x)/(1-exp(x**2)*x)**2,x)
```

gives

```
.....
 File "/opt/anaconda/lib/python3.6/site-packages/sympy/core/mul.py", line 1067, in <genexpr>
    a.is_commutative for a in self.args)
RecursionError: maximum recursion depth exceeded
>>> 

```

Thank you.,
--Nasser

**Comment by jksuom** [comment]
This should be handled by `risch_integrate` but it is currently unable to find an antiderivative. It tries to find the integral of `(2*x**3+x)/(1-exp(x**2)*x)**2` which probably cannot be evaluated in closed form. This leads to infinite recursion in `manualintegrate`. (It alternates between two intermediate integrands that differ by the sign of the integrating variable.)
