### ISSUE TITLE
It seems not easy to convert sympy.core.numbers.Float types to just native python float type

### ISSUE THREAD

**Issue by haoranShu** [sympy/sympy#14873]
as described in title

**Comment by asmeurer** [comment]
Can you explain in more detail what the problem is? Calling `float()` on a Float object works for me.

**Comment by haoranShu** [comment]
Sorry it was my bad! I used Float all the time. Please close this issue. I am really sorry.

**Comment by Ramimashkouk** [comment]
could you explain please, how it worked with you? @haoranShu 
I still can't convert sympy.core.numbers.Float to native python float, so I can deal with in my program

**Comment by karanprime** [comment]
Simply use `float()` with your sympy float. For example, if `n` is your sympy float, `float(n)` will return native python float.
