### ISSUE TITLE
Intersection of Circle and Line -> Problem

### ISSUE THREAD

**Issue by Bennyyy27** [sympy/sympy#14887]
Hi, 
I am totally new to GitHub so please be indulgent if I forget something at posting a new issue.

If I am focussing on one timestep, my model can be broken down to a simple circle and line from sympy.geometry. 
If I am plotting these two entities, an intersection is definitely taking place but, however, the intersection command does not return an intersection.
I already tried to find a solution or workaround for that. I've read something that the rational values used in sympy might be the problem for that.

Does anybody know how to solve this issue?

Thanks a lot!
Regards
Benny

`
from sympy.geometry import Circle, Line, Segment, Point

p1 = Point(0,0)
p2 = Point(1,2)
p4 = Point(4,1.5)

l1 = Segment(p1,p2)

l3 = Segment(p2,p4)

cm = l1.midpoint
r = 1.3
c = Circle(cm, r)

print("l1 midpoint:" + str(l1.midpoint))
print("Circle center:" + str(c.center))
print("Circle radius: " + str(c.radius))

intersect = c.intersection(l3)
print(intersect)

dis = cm.distance(l3.p1)
conn = Segment(cm, l3.p1)
print("Conn length : " + str(float(conn.length)))
print("Distance : " + str(float(dis)))
b = dis<conn
print("Distance to line smaller than radius? : " + str(b))

`

Edit: I noticed, that sympy v1.0 does lead to a correct intersection, but sympy geometry 1.1.1 on my laptop does not lead to the intersection.

**Comment by sidhantnagpal** [comment]
It works while taking r as `Rational` instead of `Float`.
```
In [1]: from sympy.geometry import Circle, Line, Segment, Point

In [2]: from sympy import S

In [3]: p1, p2, p4 = Point(0, 0), Point(1, 2), Point(4, 1.5)

In [4]: p4
Out[4]: Point2D(4, 3/2)

In [5]: l1, l3 = Segment(p1, p2), Segment(p2, p4)

In [6]: cm = l1.midpoint

In [7]: r = S(13)/10

In [8]: c = Circle(cm, r)

In [9]: c.intersection(l3)
Out[9]: [Point2D(25/37 + 78*sqrt(3)/185, -13*sqrt(3)/185 + 76/37)]

In [10]: pt = _[0]

In [11]: c.contains(pt)
Out[11]: True

In [12]: l3.contains(pt)
Out[12]: True

In [13]: import sympy; sympy.__version__
Out[13]: '1.2.1.dev'
```

**Comment by smichr** [comment]
duplicates #4748
