### ISSUE TITLE
Why does this integral hang Sympy?

### ISSUE THREAD

**Issue by JohnStone2017** [sympy/sympy#14892]
Edited to correct an error: Mathematica actually can't solve it either.

```
seconds = symbols('s')
sympy.integrate(120*(-2*sympy.cos(sympy.pi*s) + 3)* \
    sympy.tan(sympy.pi*sympy.cos(sympy.pi*s)/4), seconds)
```

After 10 minutes, Sympy still appears to be working on it, though I'm not sure whether I may have sent it into an infinite loop through some error. Mathematica, Maxima and Axiom rapidly return it unevaluated (I have never used Axiom before this, so may well have made an error with it). Is this integral not supported yet in Sympy, or have I made some error? Thank you.

(note: I originally said Mathematica could do it; but then I fixed an error in my Mathematica code, and Mathematica is unable to evaluate the corrected expression.)

**Comment by ethankward** [comment]
What type of object is "seconds"?

**Comment by JohnStone2017** [comment]
seconds is a Sympy symbol. I've added its declaration to the original post.

**Comment by jksuom** [comment]
SymPy has several integrators, and it tries them all if no additional hints are given. In this example, SymPy quickly finds that the three main integrators, risch, meijerint and manual, cannot evaluate the integral. The last one, heurisch, can be very slow and use a lot of resources, equations with hundreds of variables. It does not necessarily hang but the effect may look the same on the surface.

It is possible to exclude heurisch by explicitly choosing another integrator by adding `risch=True`, `meijerg=True` or `manual=True`. (It seems that this is currently the only of preventing heurisch from running as there is no keyword `heurisch`.)
