### ISSUE TITLE
Deprecate source

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#14905]
We ought to deprecate the `source` function. It is just a small wrapper around `inspect.getsource`, and for most users, using `??` in IPython/Jupyter is preferable. 

If someone wants to fix this issue, you need to add the SymPyDeprecationWarning to the `source` function, referencing this issue. See https://github.com/sympy/sympy/wiki/Deprecating-policy

**Comment by udiptya999** [comment]
I would like to take up this issue. But actually, this is my first time.

**Comment by smichr** [comment]
> We ought to deprecate

I will miss this dash of sugar. Can we keep it?

**Comment by GaurangTandon** [comment]
Hi @asmeurer , is there something remaining to be done in this issue after the last PR was merged? If so, then I can help. Please let me know. Thanks.

**Comment by sidhantnagpal** [comment]
The issue was resolved in #15064. Feel free to take up other issues.

**Comment by oscarbenjamin** [comment]
Yes it has been deprecated. I guess @asmeurer has kept it open with the "deprecation removal" label until the deprecation warning can be removed.
