### ISSUE TITLE
printer.py in sympy 1.2 seems to break subclassing from `Symbol`

### ISSUE THREAD

**Issue by tBuLi** [sympy/sympy#14911]
I maintain a project which depends heavily on `sympy`, called [`symfit`](https://github.com/tBuLi/symfit).

However, it seems that sympy 1.2 breaks this project because of the introduction of `_print_Variable` in `codeprinter.py`.

The problem seems to be caused by this: I essentially have an object called `Variable` which inherits from `sympy.Symbol`:
```python
class Variable(Symbol):
    pass
```
When calling `lambdify` on an expression containing this object, we end up (wrongfully) calling
```python
def _print_Variable(self, expr):
    return self._print(expr.symbol)
```
which in turn (rightfully) raises `AttributeError: 'Variable' object has no attribute 'symbol'`.

Before `sympy 1.2` my code wasn't experiencing this problem yet because `_print_Variable` did not exist. It seems to me the way the printing infrastructure is implemented here breaks duck typing, or has `Variable` always been a protected name and should I never have used it? 

The reason I think `sympy` breaks duck typing is because it seems to assume [here](https://github.com/sympy/sympy/blob/c96a971289a25014fc9454e82dffc40156238c3d/sympy/printing/printer.py#L272) that all of these objects are fundamental `sympy` types, which is not the case in this example. If probed again, this `Variable` would tell you that it is actually a `Symbol`. (Actually, the MRO in this case will also contain `Symbol`, whereas the [actual `Variable` from `sympy` ](https://github.com/sympy/sympy/blob/03268800330a27da9e43ebba9eb58c0b00683261/sympy/codegen/ast.py#L1314)does not inherit from `Symbol`.)

A workaround I see [here](https://github.com/sympy/sympy/blob/c96a971289a25014fc9454e82dffc40156238c3d/sympy/printing/printer.py#L264) is to make my `Variable` implement an explicit `self.printmethod` pointing to that of `symbol`, or maybe this should be solved in a more fundamental way?

A full traceback of the error this causes in `symfit` can be found here: tbuli/symfit#169. Ultimately, should this be resolved by redefining my API or is this an issue in `sympy`?

**Comment by asmeurer** [comment]
If you implement `_sympystr` on your object it will stop using that. 

I'm not sure if the default printers should be bypassing types that aren't included in SymPy. This is fundamentally a namespacing problem. The printer assumes a global namespace, which isn't the case in Python. Maybe we should extend it to work in a namespaced way somehow, either by pointing to the object itself, or by using the fully qualified name (including the module name).

**Comment by tBuLi** [comment]
Thank you for your quick reply. Defining `_sympystr` indeed solves the immediate problem. However, things just got a lot weirder. Let me provide a minimal example:
```python
from sympy import Symbol, lambdify

class Variable(Symbol):
    def _sympystr(self, printer, *args, **kwargs):
        return printer.doprint(self.name)
    _lambdacode = _sympystr

x = Variable('x')
y = 2*x
lambdify((x,), y, modules='numpy', dummify=False)
```
In `1.1.1` this runs without problems. However, in `1.2` it raises the following error:
```
Traceback (most recent call last):
  File "C:/Users/u0114255/stack/Code/symfit debug/171.py", line 10, in <module>
    lambdify((x,), y, modules='numpy', dummify=False)
  File "C:\ProgramData\Miniconda3\lib\site-packages\sympy\utilities\lambdify.py", line 456, in lambdify
    funcstr = funcprinter.doprint(funcname, args, expr)
  File "C:\ProgramData\Miniconda3\lib\site-packages\sympy\utilities\lambdify.py", line 661, in doprint
    argstrs, expr = self._preprocess(args, expr)
  File "C:\ProgramData\Miniconda3\lib\site-packages\sympy\utilities\lambdify.py", line 727, in _preprocess
    argrep = self._argrepr(arg)
  File "C:\ProgramData\Miniconda3\lib\site-packages\sympy\printing\codeprinter.py", line 105, in doprint
    if len(self._not_supported) > 0:
AttributeError: 'LambdaPrinter' object has no attribute '_not_supported'
```
Looking at the code around the line raising the error this makes little sense, as it looks like this:
```python
self._not_supported = set()
self._number_symbols = set()

lines = self._print(expr).splitlines()

# format the output
if self._settings["human"]:
    frontlines = []
    if len(self._not_supported) > 0:  # <- this raises the Exception
        frontlines.append(self._get_comment(
                "Not supported in {0}:".format(self.language)))
        for expr in sorted(self._not_supported, key=str):
            frontlines.append(self._get_comment(type(expr).__name__))
    for name, value in sorted(self._number_symbols, key=str):
        frontlines.append(self._declare_number_const(name, value))
    lines = frontlines + lines
    lines = self._format_code(lines)
    result = "\n".join(lines)
else: ...
```
So somewhere in these few lines, we somehow loose `self._not_supported`?

On a conceptual level I agree with you by the way, I think that making for example a dict mapping the default objects to their default printers would already solve this issue, but directly using the `__name__` attribute of the classes to convert to methods seems like a dangerous idea. Using the fully qualified name would also solve the issue but would perhaps make for very ambiguous method names, so I would definitely prefer a simple mapping.

**Comment by asmeurer** [comment]
It gets deleted at the bottom of the method. But the problem is that the method calls itself recursively in the _print call. Is _not_supported used outside of the function? If not, why can't it be a local variable? If so, a default should be added in `__init__` and it shouldn't be deleted.

**Comment by asmeurer** [comment]
Regarding the original issue, I think making the printing methods that are included in SymPy only dispatch to functions defined in SymPy is reasonable. It might break code that expects the opposite, though.

**Comment by tBuLi** [comment]
On a conceptual level, what kind of code are you afraid might break? Because any external code relying on this has been warned by the fact that all the methods nicely start with an underscore, and could therefore be changed in the future. (Of course still not something to change lightly)

Or are you worried that code inside SymPy might break?

I think the code here in a way already implicitly talks about sympy objects, since using the same name as an object you want to mimic is to my knowledge not a common duck-typing strategy. So since there is already an implicit assumption that we are talking about sympy's own objects here, why not make it explicit? 

To somewhat save duck-typing it could perhaps also be changed to checking `isinstance(expr, Symbol)` etc, since any subclass of Symbol will also answer this with `True`. However, in that case the order of such checks will become important.

**Comment by tBuLi** [comment]
The problem has been solved: it is because at some point also `printmethod = _numpycode` is required,  and since the model above doesn't have one it causes the error.

So although the Exception is not for helpful debugging, it is not really a problem with the printer code after all. So I guess this issue can be closed.
