### ISSUE TITLE
Matrix.dot between 2 complex vector is wrong, it do not conjugating one of the vector

### ISSUE THREAD

**Issue by mammalwong** [sympy/sympy#14920]
I am using sympy1.1.1
If I create v = Matrix([1j,1j,1j]),
v.dot(v) returns -3, it didn't conjugate one of the vector.

**Comment by cbm755** [comment]
I find this very strange too.  The reasoning might be that `numpy.dot` does it that way.  See https://github.com/cbm755/octsympy/issues/426

But actually on re-reading my old thread, it looks like I thought it was *SymPy*'s docs saying it was deliberate.  It is not.  SymPy docs don't seem to mention this at all (!)  I have updated my 2016 comment.

Very minimum: we should change these docs to note this non-standard surprising behaviour:
```
Return the dot product of two vectors of equal length. ``self`` must
be a ``Matrix`` of size 1 x n or n x 1, and ``b`` must be either a
matrix of size 1 x n, n x 1, or a list/tuple of length n. A scalar is returned.
```

But maybe we should fix this.  Would you like to help?  Grab the source from git, try to put a complex conjugate in.  Then run the test suite and see if any tests fail...

**Comment by mammalwong** [comment]
@cbm755 before any change is made, I think there are some additional things we have to consider:
-The dot product of complex number is not commutative, does v.dot(w) means <v|w> in this case?
- does the @ operator only means matrix multiplication now? Do we need to change the case v @ w if v is a row matrix and w is a column matrix?

**Comment by cbm755** [comment]
I looked at some other software.  I'm following @siefkenj's comment for the meaning of "physics convention" vs "math convention".

  * Matlab/Octave: "physics convention"
  * Maple: its rather complicated!  `DotProduct(u,v)` does physics convention if u is a column vector, math convention if u (yes u) is a row vector.
  * WolframAlpha (and probably Mathematica but I haven't checked): sum of elementwise product.
  * numpy.dot: sum of elementwise product
  * numpy.vdot: physics convention.

I agree about not changing `@`.

> I don't think we should break old behavior. 

Note is is *undocumented* old behaviour but this would be a argument in favour of having a warning.

**Comment by asmeurer** [comment]
I think we should create a different function, say `innerproduct`, that does the Hermitian inner product.

**Comment by amsuhane** [comment]
@siefkenj is the issue still open?  I would like to work on the issue.

**Comment by siefkenj** [comment]
@amsuhane as far as I know, yes.

**Comment by amsuhane** [comment]
I have edited the **dot** function by adding two kwargs to it (hermitian = False and convention = "maths").

If the hermitian is set to true then the **inner_product** function is called which returns the hermitian inner product. If a case arises where hermitian is set to false but one or both the matrices are complex, then a warning is returned which requests for dot function to be called with hermitian set to True.

I have shown the implementation below:
```
>>> from sympy import *
>>> v = Matrix([1j, 1j, 1j])
>>> v.dot(v)
Please set hermitian equals to True as matrix entered is complex
>>> v.dot(v, hermitian = True)
3.00000000000000

>>> x, y = symbols('x y')
>>> M = Matrix([x, y])
>>> q = Matrix([1j, 2j])

>>> M.dot(q, hermitian = True)
-1.0*I*x - 2.0*I*y

>>> q.dot(M, hermitian = True)
1.0*I*conjugate(x) + 2.0*I*conjugate(y)

>>> M.dot(q, hermitian = True, convention = "physics")
1.0*I*conjugate(x) + 2.0*I*conjugate(y)

>>> M.dot(M)
x**2 + y**2

>>> M.dot(M, hermitian = True)
x*conjugate(x) + y*conjugate(y)

```
Is the implementation right or should there be changes?

**Comment by siefkenj** [comment]
I think this is on the right track. I would change it a bit:

   * `convention` -> `conjugate_convention` and it should accept options of `'math'`, `'maths'`, `'physics'`, `'left'`, `'right'`, `None` (or possibly just `'left'` and `'right'`). If `conjugate_convention` is set, `hermitian` should be automatically set to `True`.
   * The warning should be changed to "**Warning: taking the non-Hermitian dot product of complex vectors. To suppress this warning, explicitly set `hermitian=False`.**"
   * The warning should only show up if the `hermitian` kwarg is unset. If it is set to `True` or `False` explicitly, it should not appear.

**Comment by amsuhane** [comment]
I have changed the function as suggested above:

The new implementation is as follows:

```
>>> from sympy import *
>>> v = Matrix([1j, 1j, 1j])

>>> v.dot(v)
Warning: taking the non-Hermitian dot product of complex vectors. To suppress this warning, explicitly set hermitian=False.
-3.00000000000000

>>> v.dot(v, hermitian = False)
-3.00000000000000

>>> v.dot(v, hermitian = True)
3.00000000000000

>>> v.dot(v, conjugate_convention = "right")
3.00000000000000

>>> v.dot(v, conjugate_convention = "any_invalid_convention")
Invalid conjugate_convention is entered.

```
Are there any other changes?

**Comment by siefkenj** [comment]
@amsuhane Do you have a PR for this? This discussion should happen there.
