### ISSUE TITLE
RecursionError with Piecewise.xreplace containing Indexed objects

### ISSUE THREAD

**Issue by richardotis** [sympy/sympy#14933]
Minimal example to reproduce the issue:

```python
from sympy import Piecewise, Symbol, ITE, MatrixSymbol

x = Symbol('x')
y = Symbol('y')

inp = MatrixSymbol('inp', 1, 1)
rep_dict = {y: inp[0, 0], x: inp[0, 0]}

p = Piecewise((1, ITE(y > 0, x < 0, True)))
z = p.xreplace(rep_dict)
```

```
---------------------------------------------------------------------------
RecursionError                            Traceback (most recent call last)
<ipython-input-44-46c498a48320> in <module>()
----> 1 z = p.xreplace(rep_dict)
      2 print(z)

/home/rotis/anaconda/envs/calphadpy3/lib/python3.5/site-packages/sympy/core/basic.py in xreplace(self, rule)
   1113 
   1114         """
-> 1115         value, _ = self._xreplace(rule)
   1116         return value
   1117 

/home/rotis/anaconda/envs/calphadpy3/lib/python3.5/site-packages/sympy/core/basic.py in _xreplace(self, rule)
   1134             args = tuple(args)
   1135             if changed:
-> 1136                 return self.func(*args), True
   1137         return self, False
   1138 

/home/rotis/anaconda/envs/calphadpy3/lib/python3.5/site-packages/sympy/functions/elementary/piecewise.py in __new__(cls, *args, **options)
    134 
    135         if options.pop('evaluate', True):
--> 136             r = cls.eval(*newargs)
    137         else:
    138             r = None

/home/rotis/anaconda/envs/calphadpy3/lib/python3.5/site-packages/sympy/functions/elementary/piecewise.py in eval(cls, *_args)
    183                     x = free.pop()
    184                     try:
--> 185                         c = c.as_set().as_relational(x)
    186                     except NotImplementedError:
    187                         pass

/home/rotis/anaconda/envs/calphadpy3/lib/python3.5/site-packages/sympy/logic/boolalg.py in as_set(self)
    144             reps = {}
    145             for r in self.atoms(Relational):
--> 146                 if periodicity(r, x) not in (0, None):
    147                     s = r._eval_as_set()
    148                     if s in (S.EmptySet, S.UniversalSet, S.Reals):

/home/rotis/anaconda/envs/calphadpy3/lib/python3.5/site-packages/sympy/calculus/util.py in periodicity(f, symbol, check)
    471     elif period is None:
    472         from sympy.solvers.decompogen import compogen
--> 473         g_s = decompogen(f, symbol)
    474         num_of_gs = len(g_s)
    475         if num_of_gs > 1:

/home/rotis/anaconda/envs/calphadpy3/lib/python3.5/site-packages/sympy/solvers/decompogen.py in decompogen(f, symbol)
     55         f1 = f.subs(gens[0], symbol)
     56         f2 = gens[0]
---> 57         result += [f1] + decompogen(f2, symbol)
     58         return result
     59 

/home/rotis/anaconda/envs/calphadpy3/lib/python3.5/site-packages/sympy/solvers/decompogen.py in decompogen(f, symbol)
     55         f1 = f.subs(gens[0], symbol)
     56         f2 = gens[0]
---> 57         result += [f1] + decompogen(f2, symbol)
     58         return result
     59 

/home/rotis/anaconda/envs/calphadpy3/lib/python3.5/site-packages/sympy/solvers/decompogen.py in decompogen(f, symbol)
     55         f1 = f.subs(gens[0], symbol)
     56         f2 = gens[0]
---> 57         result += [f1] + decompogen(f2, symbol)
     58         return result
     59 

... last 3 frames repeated, from the frame below ...

/home/rotis/anaconda/envs/calphadpy3/lib/python3.5/site-packages/sympy/solvers/decompogen.py in decompogen(f, symbol)
     55         f1 = f.subs(gens[0], symbol)
     56         f2 = gens[0]
---> 57         result += [f1] + decompogen(f2, symbol)
     58         return result
     59 

RecursionError: maximum recursion depth exceeded
```

Note that this will occur even if you pass `evaluate=False` to `Piecewise`.
This may be related to #14899

**Comment by richardotis** [comment]
In `sympy/functions/elementary/piecewise.py:173`, changing `c.free_symbols` to `c.expr_free_symbols` seems to fix the issue. Still analyzing.

**Comment by asmeurer** [comment]
CC @smichr

**Comment by asmeurer** [comment]
It also would help to bisect the issue.

**Comment by oscargus** [comment]
Now it behaves differently (still not working though):
Traceback (most recent call last):

  File "<ipython-input-1-0baf0b7b70fd>", line 10, in <module>
    z = p.xreplace(rep_dict)

  File "C:\Users\Oscar\sympy\sympy\core\basic.py", line 1192, in xreplace
    value, _ = self._xreplace(rule)

  File "C:\Users\Oscar\sympy\sympy\core\basic.py", line 1214, in _xreplace
    return self.func(*args), True

  File "C:\Users\Oscar\sympy\sympy\functions\elementary\piecewise.py", line 139, in __new__
    r = cls.eval(*newargs)

  File "C:\Users\Oscar\sympy\sympy\functions\elementary\piecewise.py", line 188, in eval
    c = c.as_set().as_relational(x)

  File "C:\Users\Oscar\sympy\sympy\logic\boolalg.py", line 150, in as_set
    if periodicity(r, x) not in (0, None):

  File "C:\Users\Oscar\sympy\sympy\calculus\util.py", line 451, in periodicity
    f = simplify(f)

  File "C:\Users\Oscar\sympy\sympy\simplify\simplify.py", line 579, in simplify
    return done(expr)

  File "C:\Users\Oscar\sympy\sympy\simplify\simplify.py", line 538, in done
    rv = e.doit() if doit else e

  File "C:\Users\Oscar\sympy\sympy\matrices\expressions\matexpr.py", line 708, in doit
    return args[0][args[1], args[2]]

TypeError: 'Dummy' object is not subscriptable
```

**Comment by jmansour** [comment]
I'm also encountering this issue for the example provided (same error as @oscargus), and also under other similar conditions (`Piecewise` & `MatrixSymbol` substitutions). 

My case is embedded in a more complex problem, but if it'd be useful I can try to distil it down to something simple and post it up here. 

Sympy 1.6.2

**Comment by oscarbenjamin** [comment]
The error has changed again:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/oscar/current/sympy/sympy.git/sympy/core/basic.py", line 1143, in xreplace
    value, _ = self._xreplace(rule)
  File "/home/oscar/current/sympy/sympy.git/sympy/core/basic.py", line 1165, in _xreplace
    return self.func(*args), True
  File "/home/oscar/current/sympy/sympy.git/sympy/functions/elementary/piecewise.py", line 136, in __new__
    r = cls.eval(*newargs)
  File "/home/oscar/current/sympy/sympy.git/sympy/functions/elementary/piecewise.py", line 187, in eval
    c = c.as_set().as_relational(x)
  File "/home/oscar/current/sympy/sympy.git/sympy/logic/boolalg.py", line 160, in as_set
    if periodicity(r, x) not in (0, None):
  File "/home/oscar/current/sympy/sympy.git/sympy/calculus/util.py", line 405, in periodicity
    f = f.subs(symbol, temp)
  File "/home/oscar/current/sympy/sympy.git/sympy/core/basic.py", line 953, in subs
    rv = rv._subs(old, new, **kwargs)
  File "/home/oscar/current/sympy/sympy.git/sympy/core/cache.py", line 72, in wrapper
    retval = cfunc(*args, **kwargs)
  File "/home/oscar/current/sympy/sympy.git/sympy/core/basic.py", line 1067, in _subs
    rv = fallback(self, old, new)
  File "/home/oscar/current/sympy/sympy.git/sympy/core/basic.py", line 1039, in fallback
    arg = arg._subs(old, new, **hints)
  File "/home/oscar/current/sympy/sympy.git/sympy/core/cache.py", line 72, in wrapper
    retval = cfunc(*args, **kwargs)
  File "/home/oscar/current/sympy/sympy.git/sympy/core/basic.py", line 1067, in _subs
    rv = fallback(self, old, new)
  File "/home/oscar/current/sympy/sympy.git/sympy/core/basic.py", line 1044, in fallback
    rv = self.func(*args)
  File "/home/oscar/current/sympy/sympy.git/sympy/matrices/expressions/matexpr.py", line 734, in __new__
    raise TypeError("First argument of MatrixElement should be a matrix")
TypeError: First argument of MatrixElement should be a matrix
```
That change is due to #20691 which made it an error to pass a non-matrix as the 1st argument of MatrixElement.

**Comment by oscargus** [comment]
Worth noting that it passed through:
```
File "/home/oscar/current/sympy/sympy.git/sympy/functions/elementary/piecewise.py", line 187, in eval
    c = c.as_set().as_relational(x)
```
which probably should be removed.

**Comment by oscarbenjamin** [comment]
> which probably should be removed.

You have a PR somewhere that removes that don't you? Does that fix this?

**Comment by oscarbenjamin** [comment]
This line attempts to replace a MatrixSymbol with a plain Dummy symbol:
https://github.com/sympy/sympy/blob/9dd704b071e5134a0e8beeeb1a2d2599536f5144/sympy/calculus/util.py#L405
That is called from here:
https://github.com/sympy/sympy/blob/9dd704b071e5134a0e8beeeb1a2d2599536f5144/sympy/logic/boolalg.py#L160
which is in turn called from here:
https://github.com/sympy/sympy/blob/9dd704b071e5134a0e8beeeb1a2d2599536f5144/sympy/functions/elementary/piecewise.py#L187
I think that:

1. `Boolean.as_set` should not check periodicity for a symbol that is not NumberKind.
2. The `periodicity` function should raise a straight error if the symbol is not NumberKind
3. Piecewise.eval should not call `as_set/as_relational`.

**Comment by oscargus** [comment]
> Does that fix this?

Not sure it became a PR, but I can try to see if I can dig it up and test.

**Comment by oscargus** [comment]
#22035 and it does indeed fix it! 
![image](https://user-images.githubusercontent.com/8114497/134420843-abe55229-c6ad-49bd-98b6-7b7d4e764126.png)

**Comment by oscargus** [comment]
>  it does indeed fix it!

Or at least hides the underlying bug...

**Comment by oscarbenjamin** [comment]
@bocklund @richardotis can you test #22035?

**Comment by oscarbenjamin** [comment]
> > it does indeed fix it!
> 
> Or at least hides the underlying bug...

I think there are at least two bugs. Maybe #22035 fixes the main bug here but then there remains a lower level bug which is just that Boolean.as_set should not check periodicity for a symbol that is not NumberKind as I said above. That doesn't change the fact that #22035 fixes a bug.

**Comment by bocklund** [comment]
@oscarbenjamin #22035 passes the pycalphad test suite after I removed the monkey patch. I also tested merging master into that branch and it looks good still. #22035 also removes the offending code that causes the slowness that I mentioned in #21494.

Getting #22035 merged for 1.9 would definitely solve our issues (and give us less code to maintain 😄)! Thanks @oscargus.

**Comment by oscarbenjamin** [comment]
Thanks for the testing @bocklund.

@oscargus #22035 is still in draft/WIP status. Is it possible that we could just roll with what's there and continue later or does it need further basic work?

If we were to merge it for 1.9 we'd need an rc2 (which is fine if it fixes this).

**Comment by oscargus** [comment]
The problem with #22035 is that some of the `stats` tests hang as the `Piecewise` returned is not simplified by `as_set().as_relational()`... (Proper hang I believe, the tests time out after 6 h.) I think this is related to the integration variables not being set to `extended_real`, but that in turn (as in #21985) causes other problems which are solved in #22052... 

I think it *may* work if #22052 and #21985 are merged first, but I guess that is not going to happen for 1.9. It can probably also be solved by looking into #22063. I am not fully sure that either will do it though.

(I believe it is the following test that hangs: https://github.com/sympy/sympy/blob/c4bcd7537439eb708f9f21e48c70606abb08c934/sympy/stats/tests/test_continuous_rv.py# It should be the one executed after the last reported successful test.)

**Comment by oscargus** [comment]
There are also two `laplace_transform` where the result changed a bit, that I am not really sure are correct. That is, not sure if they are expected to be as they were (with `s > 1`) or if that result is added because that is what SymPy returned at that stage...

**Comment by oscargus** [comment]
Oh yeah, it is the issue from #22075 that causes the hang. I've tried to remove the `extended_real` Dummy, but as I recall it, I added it because something else failed then.

**Comment by oscarbenjamin** [comment]
Maybe it's not possible to get the bigger fix in for 1.9 then

**Comment by oscarbenjamin** [comment]
A more direct and restricted fix for this is
```diff
diff --git a/sympy/logic/boolalg.py b/sympy/logic/boolalg.py
index 404acbc..0e2ad84 100644
--- a/sympy/logic/boolalg.py
+++ b/sympy/logic/boolalg.py
@@ -10,6 +10,7 @@
 from sympy.core.compatibility import ordered, as_int
 from sympy.core.decorators import sympify_method_args, sympify_return
 from sympy.core.function import Application, Derivative
+from sympy.core.kind import NumberKind
 from sympy.core.numbers import Number
 from sympy.core.operations import LatticeOp
 from sympy.core.singleton import Singleton, S
@@ -153,7 +154,7 @@ def as_set(self):
         from sympy.calculus.util import periodicity
         from sympy.core.relational import Relational
         free = self.free_symbols
-        if len(free) == 1:
+        if len(free) == 1 and all(x.kind is NumberKind for x in free):
             x = free.pop()
             reps = {}
             for r in self.atoms(Relational):
```
That gives
```python
In [1]: from sympy import Piecewise, Symbol, ITE, MatrixSymbol
   ...: 
   ...: x = Symbol('x')
   ...: y = Symbol('y')
   ...: 
   ...: inp = MatrixSymbol('inp', 1, 1)
   ...: rep_dict = {y: inp[0, 0], x: inp[0, 0]}
   ...: 
   ...: p = Piecewise((1, ITE(y > 0, x < 0, True)))
   ...: z = p.xreplace(rep_dict)

In [2]: p
Out[2]: 
⎧       ⎧x < 0  for y > 0
⎨1  for ⎨                
⎩       ⎩True   otherwise

In [3]: z
Out[3]: 
⎧       ⎧inp₀₀ < 0  for inp₀₀ > 0
⎨1  for ⎨                        
⎩       ⎩  True       otherwise 
```
@bocklund could you test that?

**Comment by smichr** [comment]
ITE is a BooleanFunction but can't be expressed as a set so that method should raise NotImplemented. Using `as_expr_free_symbols` helped because it was empty and thus circumvented the code that generated the error.

The code which is intending to rewrite And/Or canonically via writing as set and rewriting as a relational for univariate expressions can be folded into the `_canonical` function. I am testing locally and will push tomorrow.

**Comment by smichr** [comment]
@bocklund @richardotis can you test #22152?

**Comment by richardotis** [comment]
@smichr I ran it (specifically [1eb1f0c](https://github.com/sympy/sympy/pull/22152/commits/1eb1f0c1d697124a67b2f450785ce44dfc88fd6f)) against @bocklund's sympy1.9 PR for pycalphad which removes the monkey-patch ([542c3b](https://github.com/pycalphad/pycalphad/pull/375/commits/542c3b433cb07bcbd8587c5b59a2e825f84b6818)) and I see a big performance regression in the pycalphad test suite, 2x or maybe even 3x.

**Comment by smichr** [comment]
> I see a big performance regression in the pycalphad test suite, 2x or maybe even 3x.

As I mentioned, the use of `expr_free_symbols` allowed the simplification to be bypassed in the `eval` routine. You mentioned the confounding issue of getting an error with `evaluate=False` passed to the Piecewise. Could you try that again? Since I fixed `ITE` that problem should not appear and it will also allow the `eval` routine to be skipped.

**Comment by richardotis** [comment]
I just confirmed that all of pycalphad's calls to `Piecewise` already use `evaluate=False` because the patch we used allowed us to bypass the error I originally reported.

**Comment by smichr** [comment]
> I just confirmed that all of pycalphad's calls to `Piecewise` already use `evaluate=False`

One more try? I just pushed a change that I think will match your current behavior (though it may fail the test suite in the PR). It only uses the light form of canonicalization and it is bypassed when `evaluate=False`.

**Comment by richardotis** [comment]
Still seeing a similar slowdown with `f2334b`. I know this type of debugging is frustrating on your end so I'll see if I can identify a minimal example.

**Comment by richardotis** [comment]
Are you comfortable with accepting a pickle file? You would need to install pycalphad (`pip install` works), but the object itself is a SymPy object with a few light wrapper subclasses around `Symbol`, so tracebacks should be almost entirely inside sympy. I've confirmed that, if I call `pickle.load`, I can see the performance difference. I think this difference is representative of the performance issue.

Checked via `%timeit pickle.load(open('2021-09-25-pycalphad-sympy.pkl', 'br'))`:
- smichr/sympy@f2334b on bocklund/pycalphad@maint-bump-sympy-1.9: 4.38 s ± 169 ms
- sympy 1.8 on pycalphad develop: 385 ms ± 9.86 ms per loop

**Comment by richardotis** [comment]
I also suppose if you have to install pycalphad, I can also just provide a Python script to generate the object, so at least you can see what it's doing.

```python
from pycalphad import Database, Model
import requests
import pickle
db = requests.get('https://raw.githubusercontent.com/pycalphad/binder/develop/multicomponent-databases/mpea-02b.tdb').text
dbf = Database(db)
comps = ['FE', 'CR', 'CO','MN','VA']
mod = Model(dbf, comps, 'FCC_4SL')
pkl_str = pickle.dumps(mod.GM)
%timeit pickle.loads(pkl_str)
```

**Comment by richardotis** [comment]
sympy 1.8 on pycalphad develop:
![image](https://user-images.githubusercontent.com/6405510/134784168-c43d9fc3-6386-4cd9-a2c2-c3c3d4a2e228.png)

smichr/sympy@f2334b:
![image](https://user-images.githubusercontent.com/6405510/134784183-ea949df1-be18-46cd-949b-645e075c4fbf.png)

**Comment by smichr** [comment]
Thanks, but I am not able to do this level of investigation. My guess is that the Piecewise is being re-evaluated during the xreplace. Even if it is, however, the `as_set` should now fail for ITE. It would be interesting to see if and `and_or` are being generated with a print after line 41 of relational.py. And if not, then I don't know why a null xreplace would be taking any time.

**Comment by smichr** [comment]
@richardotis, could you put a print after line 41 `if and_or: print(and_or)` in core/relational.py to see what is actually passing through that code from your slow test?

**Comment by smichr** [comment]
ping @oscarbenjamin , @oscargus -- can either of you try the slow-down related expressions with the print statement I describe above?

**Comment by oscarbenjamin** [comment]
> sympy 1.8 on pycalphad develop:

@richardotis how did you produce those profile graphics?

**Comment by richardotis** [comment]
@oscarbenjamin snakeviz https://jiffyclub.github.io/snakeviz/

**Comment by oscarbenjamin** [comment]
Thanks @richardotis. They look good. I've used gprof2dot but haven't seen snakeviz. I'll give it a try.

**Comment by jmansour** [comment]
Hi folks. 

I'm getting results I'm not understanding with these changes.  Here's the test against `master` branch Sympy:

```python
from sympy import Piecewise, Abs, Symbol, MatrixSymbol
x = Symbol("x")
fn = Piecewise((1.0, Abs(x) < 0.5), (3., (Abs(x - 2) <= 0.5) | (Abs(x- 1) < 0.5)), (1.0, True))
print(fn)
# Piecewise((1.0, Abs(x) < 0.5), (3.0, (x <= 2.5) & (x > 0.5)), (1.0, True))
mat_x = MatrixSymbol(  'mat_x', 1,1)
subfn = fn.xreplace({x:mat_x[0,0],})
print(subfn)
# 1.0
```

Against `sympy==1.8` this test produces the `TypeError: 'Dummy' object is not subscriptable` error.

**Comment by oscarbenjamin** [comment]
> I'm getting results I'm not understanding with these changes.

I also don't understand that result.

**Comment by oscarbenjamin** [comment]
> > I'm getting results I'm not understanding with these changes.
> 
> I also don't understand that result.

I guess since this is closed that should be a new issue
