### ISSUE TITLE
Cannot convert Matrix to numpy array dtype

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#14943]
```py
>>> M = Matrix([[1, 2], [3, 4]])
>>> import numpy as np
>>> np.array(M)
array([[1, 2],
       [3, 4]], dtype=object)
>>> np.array(M, dtype=float)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: __array__() takes 1 positional argument but 2 were given
```

The problem is that `__array__` should take an optional argument, `dtype`. 

`matrix2numpy` already supports this argument, so this is trivial to fix.

**Comment by shubhscoder** [comment]
I would like to work on this. Can anyone get me started? Thanking you in advance!

**Comment by asmeurer** [comment]
@shubhscoder if you look right above your comment there is a link to a pull request that already fixes this issue. I would suggest looking for another issue as @ethankward has already fixed this one.

**Comment by shubhscoder** [comment]
Okay no problem . Will look for another issue. Thank you!
