### ISSUE TITLE
Cannot upgrade to latest version of Sympy with conda

### ISSUE THREAD

**Issue by davidrpugh** [sympy/sympy#14953]
I noticed that my SymPy install was out of date so I ran

```bash
conda update sympy
```

and got the following

```bash
Solving environment: done

## Package Plan ##

  environment location: /Users/drpugh/anaconda3

  added / updated specs: 
    - sympy


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    conda-4.5.8                |           py36_0         1.0 MB

The following packages will be UPDATED:

    conda: 4.5.4-py36_0 --> 4.5.8-py36_0

Proceed ([y]/n)? y
```

Which updated `conda` but not SymPy. I tried to remove SymPy and reinstall using

```bash
conda remove sympy
```

and got the following

```bash
Solving environment: done

## Package Plan ##

  environment location: /Users/drpugh/anaconda3

  removed specs: 
    - sympy


The following packages will be REMOVED:

    anaconda: 5.2.0-py36_3        
    sympy:    1.1.1-py36h7f3cf04_0

Proceed ([y]/n)? y
``` 

and then

```bash
conda install sympy
```

which yielded

```bash
Solving environment: done

## Package Plan ##

  environment location: /Users/drpugh/anaconda3

  added / updated specs: 
    - sympy


The following NEW packages will be INSTALLED:

    sympy: 1.1.1-py36h7f3cf04_0

Proceed ([y]/n)? n


CondaSystemExit: Exiting.
```

I tried completely uninstalling and reinstalling Anaconda entirely from a fresh download. Didn't resolve the issue.

I was able to download the most recent version using `pip`.  I try to avoid using `pip` now whenever possible as I worry about interaction effects of downloading the same package using `pip` and `conda` inadvertently.

**Comment by alexeymuranov** [comment]
Did you check ig Sympy 1.2 is in the repository you are using?  [`anaconda / packages`](https://anaconda.org/anaconda/sympy) currently has Sympy 1.1.1 as the latest version.

**Comment by davidrpugh** [comment]
I didn't check and am using the default repository.  In the past even when Anaconda comes with an older version of a package pre-installed, running `conda update` usually grabs the most recent version available.  I guess they just haven't updated the relevant repositories with the newer `sympy`.

**Comment by asmeurer** [comment]
conda-forge should have 1.2
