### ISSUE TITLE
`integrate` raised issue with variable of integration of type `Indexed`

### ISSUE THREAD

**Issue by akash9712** [sympy/sympy#14960]
This error was raised with the particular expression given below. 
```
from sympy import *
>>> x = Symbol('x')
>>> x1, x2 = Indexed('x', 1), Indexed('x', 2)
>>> pdf = exp(-x1**2/2 + x1 - x2**2/2 - S(1)/2)/(2*pi)
>>> integrate(pdf, (x1, -oo, oo))
...
AttributeError: 'Indexed' object has no attribute 'name'
```

**Comment by jksuom** [comment]
It seems that plain `Indexed` is not the proper type for these variables. It should probably be a subclass of both  `Symbol` and `Indexed`.

**Comment by ArifAhmed1995** [comment]
@jksuom Do you mean to use `x, y = symbols('x y', cls=Idx)` and then rest of the statements ?
Similar error results on doing so.

**Comment by jksuom** [comment]
No, that is not what I mean. I mean that the type of the indexed symbols to be used in the stats module should probably be both `Indexed` and `Symbols`. The objects created by `symbols('x y', cls=Idx)` will be of class `Idx` only.

**Comment by jksuom** [comment]
That looks feasible to me. `str` could be used.

**Comment by tBuLi** [comment]
Excuse me for commenting on a closed issue, but shouldn't the line giving this issue be changed to calling `str` on whatever it is given, rather than using `.name` directly? That seems more duck-typing friendly to me.

**Comment by asmeurer** [comment]
This is the line:

```
  File "./sympy/functions/elementary/complexes.py", line 1097, in <dictcomp>
    reps = {s: Dummy(s.name, polar=True) for s in eq.free_symbols}
```

I think it's OK to assume that the objects in free_symbols have `.name`. Calling str generally makes me uneasy because it works for any expression, and is usually an antipattern https://github.com/sympy/sympy/wiki/Idioms-and-Antipatterns#strings-as-input

**Comment by tBuLi** [comment]
Good point, I guess it could cause more problems than it solves. And true, this actually solves the inconsistency with IndexedBase objects not having a name like the rest of the symbols.
