### ISSUE TITLE
sympy.series is both a module and a function

### ISSUE THREAD

**Issue by cbm755** [sympy/sympy#14966]
Background: there was a bug, #14924, of which I will summarize the technical aspect as follows:

1.  A user reported that `help(sympy.fps)` includes the text:
```
See Also
========
sympy.series.formal.compute_fps
```
But that `help(sympy.series.formal.compute_fps)` doesn't actually work:
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-40-d915bd8fac6b> in <module>()
----> 1 help(sympy.series.formal.compute_fps)

AttributeError: 'function' object has no attribute 'formal'
```
2.  @asmeurer responded:

> this is an unfortunate side effect of the way Python names work.
> `sympy.series` is both a module and a function, and the function here take
> precedence because it is imported later. Directly importing this as
> `from sympy.series.formal import compute_fps` does work. Unfortunately,
> there's not much we can do here. The "see also" is designed to work with
> Sphinx, so we do not have other options on how it is formatted. SymPy is
> fundamentally a Python library and there are certain aspects of the Python
> programming language that users need to be familiar with when using the library.

3.  There was an further discussion of other broken links (like URLs to external projects).  That continues as #14925.

**Comment by cbm755** [comment]
My understanding is that @asmeurer means this "can't be fixed" (or perhaps won't be fixed b/c doing so would break the Sphinx links).  Therefore I close this issue.

**Comment by asmeurer** [comment]
Just to clarify something, we did NOT delete this issue or any other issue. I don't even know if it's possible to do that.

GitHub seems to have deleted every issue opened by @JohnStone2017, as well has his user profile (they all give 404). I have written to their support about it. I really do not want these issues to be deleted. GitHub allows comments to be hidden (they can still be viewed if you click on them), which was perfectly sufficient for this situation. So I personally find it unacceptable that GitHub deleted these issues and I hope they can be restored. I will let you know how GitHub support responds.

**Comment by asmeurer** [comment]
Regarding this issue being closed, yes, it is not fixable without breaking backwards compatibility. We would have to rename either the function `series`, rename the module `series`, or remove series from `__init__.py`. In the future, we should try to avoid using module names that are the same as function names, especially top-level module names.  If someone knows of a fix that I'm not aware of, let me know and reopen this issue. 

The "see also" section itself works correctly in Sphinx, because Sphinx just parses the dotted name as a module path.

**Comment by asmeurer** [comment]
After some discussion with GitHub, they have undeleted the issues.
