### ISSUE TITLE
Finding eigenvalues of a 4x4 matrix (symbolic)

### ISSUE THREAD

**Issue by thatlittleboy** [sympy/sympy#14982]
Consider the following:

```
from sympy import *
x, z = symbols('x z', real=True)
mat = Matrix([[1, cos(x/4 + z/4), cos(x/4 + z/4), cos(x/2)], [cos(x/4 + z/4), 1, 1, cos(x/4 - z/4)], [cos(x/4 + z/4), 1, 1, cos(x/4 - z/4)], [cos(x/2), cos(x/4 - z/4), cos(x/4 - z/4), 1]])
```

which is the matrix: 
![chrome_2018-07-27_01-07-28](https://user-images.githubusercontent.com/30731072/43302596-78abf004-9139-11e8-8474-d28cf45a6db6.png)

It is real and symmetric.

I am trying to calculate the eigenvalues, which I have been told is:
![chrome_2018-07-27_09-11-13](https://user-images.githubusercontent.com/30731072/43322583-05c848c8-917d-11e8-9cd6-781ad4f120ce.png)
 and has a relatively simple form.

But when I try to calculate the eigenvalues,

```
mat.eigenvals()
```

I get the 
> MatrixError: Could not compute eigenvalues for Matrix...

error.

I also tried:

```
lam = symbols('lambda')
cp = det(mat - lam * eye(4))
eigs = roots(Poly(cp, lam))
```

but it came back with an empty `{}`, which I presume means no roots found.
Any help with this would be appreciated.

**Comment by thatlittleboy** [comment]
I upgraded my Sympy to version 1.2 and there is no longer a MatrixError. However, I am getting only 1 zero eigenvalue, are there any other tricks to simplify the expressions other than `trigsimp()`?

>{-(3*cos(x/2)**2 + 6*cos(x/4 - z/4)**2 + 6*cos(x/4 + z/4)**2 + 1)/(3*(sqrt(-4*(3*cos(x/2)**2 + 6*cos(x/4 - z/4)**2 + 6*cos(x/4 + z/4)**2 + 1)**3 + (18*cos(x/2)**2 - 108*cos(x/2)*cos(x/4 - z/4)*cos(x/4 + z/4) - 18*cos(x/4 - z/4)**2 - 18*cos(x/4 + z/4)**2 - 2)**2)/2 + 9*cos(x/2)**2 - 54*cos(x/2)*cos(x/4 - z/4)*cos(x/4 + z/4) - 9*cos(x/4 - z/4)**2 - 9*cos(x/4 + z/4)**2 - 1)**(1/3)) - (sqrt(-4*(3*cos(x/2)**2 + 6*cos(x/4 - z/4)**2 + 6*cos(x/4 + z/4)**2 + 1)**3 + (18*cos(x/2)**2 - 108*cos(x/2)*cos(x/4 - z/4)*cos(x/4 + z/4) - 18*cos(x/4 - z/4)**2 - 18*cos(x/4 + z/4)**2 - 2)**2)/2 + 9*cos(x/2)**2 - 54*cos(x/2)*cos(x/4 - z/4)*cos(x/4 + z/4) - 9*cos(x/4 - z/4)**2 - 9*cos(x/4 + z/4)**2 - 1)**(1/3)/3 + 4/3: 1, -(3*cos(x/2)**2 + 6*cos(x/4 - z/4)**2 + 6*cos(x/4 + z/4)**2 + 1)/(3*(-1/2 + sqrt(3)*I/2)*(sqrt(-4*(3*cos(x/2)**2 + 6*cos(x/4 - z/4)**2 + 6*cos(x/4 + z/4)**2 + 1)**3 + (18*cos(x/2)**2 - 108*cos(x/2)*cos(x/4 - z/4)*cos(x/4 + z/4) - 18*cos(x/4 - z/4)**2 - 18*cos(x/4 + z/4)**2 - 2)**2)/2 + 9*cos(x/2)**2 - 54*cos(x/2)*cos(x/4 - z/4)*cos(x/4 + z/4) - 9*cos(x/4 - z/4)**2 - 9*cos(x/4 + z/4)**2 - 1)**(1/3)) - (-1/2 + sqrt(3)*I/2)*(sqrt(-4*(3*cos(x/2)**2 + 6*cos(x/4 - z/4)**2 + 6*cos(x/4 + z/4)**2 + 1)**3 + (18*cos(x/2)**2 - 108*cos(x/2)*cos(x/4 - z/4)*cos(x/4 + z/4) - 18*cos(x/4 - z/4)**2 - 18*cos(x/4 + z/4)**2 - 2)**2)/2 + 9*cos(x/2)**2 - 54*cos(x/2)*cos(x/4 - z/4)*cos(x/4 + z/4) - 9*cos(x/4 - z/4)**2 - 9*cos(x/4 + z/4)**2 - 1)**(1/3)/3 + 4/3: 1, -(3*cos(x/2)**2 + 6*cos(x/4 - z/4)**2 + 6*cos(x/4 + z/4)**2 + 1)/(3*(-1/2 - sqrt(3)*I/2)*(sqrt(-4*(3*cos(x/2)**2 + 6*cos(x/4 - z/4)**2 + 6*cos(x/4 + z/4)**2 + 1)**3 + (18*cos(x/2)**2 - 108*cos(x/2)*cos(x/4 - z/4)*cos(x/4 + z/4) - 18*cos(x/4 - z/4)**2 - 18*cos(x/4 + z/4)**2 - 2)**2)/2 + 9*cos(x/2)**2 - 54*cos(x/2)*cos(x/4 - z/4)*cos(x/4 + z/4) - 9*cos(x/4 - z/4)**2 - 9*cos(x/4 + z/4)**2 - 1)**(1/3)) - (-1/2 - sqrt(3)*I/2)*(sqrt(-4*(3*cos(x/2)**2 + 6*cos(x/4 - z/4)**2 + 6*cos(x/4 + z/4)**2 + 1)**3 + (18*cos(x/2)**2 - 108*cos(x/2)*cos(x/4 - z/4)*cos(x/4 + z/4) - 18*cos(x/4 - z/4)**2 - 18*cos(x/4 + z/4)**2 - 2)**2)/2 + 9*cos(x/2)**2 - 54*cos(x/2)*cos(x/4 - z/4)*cos(x/4 + z/4) - 9*cos(x/4 - z/4)**2 - 9*cos(x/4 + z/4)**2 - 1)**(1/3)/3 + 4/3: 1, 0: 1}

**Comment by jksuom** [comment]
It seems that the special trigonometric simplification, `fu`, is needed. `eigenvals` does not accept the `simplify` keyword but `charpoly` does. So the eigenvalues can be found as roots of the simplified characteristic polynomial:

    roots(mat.charpoly(simplify=fu))

**Comment by thatlittleboy** [comment]
@cbm755 Yes, I checked with some simple values (x=z=0) and (x=z=pi).

@jksuom Thanks, that seems to work well! Before I close this, can I check where is this documented at? I can't seem to find it anywhere in the documentation. 

- `charpoly` only appears twice in the pdf documentation, and neither mentions what kw arguments `charpoly` is allowed to take.  
- Where is the `fu` simplification method documented as well?

**Comment by jksuom** [comment]
It seems that the pdf documentation is incomplete and need be improved. For now, it is best to look at the docstrings: `help(Matrix.charpoly)` and `help(fu)` (or the code).
