### ISSUE TITLE
Proposal to add an extra argument to 'itermonomials' function

### ISSUE THREAD

**Issue by rpep** [sympy/sympy#14996]
Currently, in my use case for SymPy, we need to generate lists of monomials. The sympy.polys.itermonomials function is great for this purpose, but one thing that would be a useful addition for me would be to put a lower bound on the order of the monomials generated.

For e.g.

```
from sympy.polys import itermonomials
from sympy import symbols
dx, dy = symbols('dx dy')
minorder=1
maxorder = 2
monoms = itermonomials([dx, dy], maxorder, minorder=minorder)
print(monoms)

```

with expected output something like:
```
{'dx**2, dx*dy, dx, dy, dy**2}
```

At present it is possible to do this using itermonomials and some not-very-intelligent monomial order checking, but I'm sure there must be a better way:

```
def new_itermonomials(symbols, lower_order, upper_order):
    monoms = list(itermonomials(symbols, upper_order))
    new_monoms = []
    for monom in monoms:
        monom_dict = monom.as_powers_dict()
        order = 0
        for symbol in symbols:
            order += monom_dict[symbol]
            if order >= lower_order:
                new_monoms.append(monom)
    return set(new_monoms)
```

With input:
```
new_itermonomials([dx, dy], 2, 3)
```
This returns:
```
{dx**2, dx**2*dy, dx**3, dx*dy, dx*dy**2, dy**2, dy**3}
```
as we would expect.

**Comment by czgdp1807** [comment]
Can I work on this issue?

**Comment by rpep** [comment]
Sure! I wasn't sure whether anyone had a better suggestion than what I'd put forward though; there might be a more elegant way to generate only the monomials necessary rather than truncating the list as I did in that example code.

**Comment by czgdp1807** [comment]
Your issue is quite logical. I will search more on this and will try to resolve it as soon as possible. :-)

**Comment by rpep** [comment]
Thanks!

**Comment by czgdp1807** [comment]
I have found a faster approach to this issue. I will make a PR shortly.

**Comment by czgdp1807** [comment]
I have made a [PR](https://github.com/sympy/sympy/pull/15020). Please see and review.

**Comment by oscarbenjamin** [comment]
Closing as fixed by #15020

**Comment by rpep** [comment]
After coming to test this by replacing my own version with the Sympy version now it's reached Master, I've found a bug in this code which was merged in; I'm not sure whether to make a new issue given it's so related.

Unfortunately, the pull request by @czgdp1807 doesn't give the correct answers in some cases:

>>> itermonomials([x, y], 3, 0) # Correct
{1, x, x**2, x**2*y, x**3, x*y, x*y**2, y, y**2, y**3}
>>> itermonomials([x, y], 3, 1) # Correct
{x, x**2, x**2*y, x**3, x*y, x*y**2, y, y**2, y**3}
>>> itermonomials([x, y], 3, 2) # Incorrect
{x**2, x**2*y, x**3, x*y**2, y**2, y**3}
>>> itermonomials([x, y], 3, 3) # Incorrect
{x**3, y**3}

The last two are wrong, because they miss the monomials of order 2 and 3 which are cross terms of the input arguments (in the former case x*y and in the latter, x**2*y and x*y**2).

**Comment by czgdp1807** [comment]
Thanks for informing @rpep. I will correct it as soon as possible.

**Comment by rpep** [comment]
Thanks so much! Hope this isn't too much bother for you!

**Comment by czgdp1807** [comment]
I have made the PR. Please take a look.
