### ISSUE TITLE
lambdify does not work with certain MatrixSymbol names even with dummify=True

### ISSUE THREAD

**Issue by yashabk** [sympy/sympy#15009]
`lambdify` is happy with curly braces in a symbol name and with `MatrixSymbol`s, but not with both at the same time, even if `dummify` is `True`.

Here is some basic code that gives the error.
```
import sympy as sy
curlyx = sy.symbols("{x}")
v = sy.MatrixSymbol("v", 2, 1)
curlyv = sy.MatrixSymbol("{v}", 2, 1)
```

The following two lines of code work:
```
curlyScalarId = sy.lambdify(curlyx, curlyx)
vectorId = sy.lambdify(v,v)
```

The following two lines of code give a `SyntaxError`:
```
curlyVectorId = sy.lambdify(curlyv, curlyv)
curlyVectorIdDummified = sy.lambdify(curlyv, curlyv, dummify=True)
```

**Comment by asmeurer** [comment]
The default here should be to always dummify, unless dummify is explicitly False https://github.com/sympy/sympy/blob/a78cf1d3efe853f1c360f962c5582b1d3d29ded3/sympy/utilities/lambdify.py?utf8=%E2%9C%93#L742

**Comment by bPhysicist** [comment]
Is
```
import sympy as sy
curlyv = sy.MatrixSymbol("{v}", 2, 1)
curlyVectorId = sy.lambdify(curlyv, curlyv)
```
supposed to work without the Dummify option ?
