### ISSUE TITLE
Error in solveset in a rational function with a radical denominator

### ISSUE THREAD

**Issue by jsdeguzman6** [sympy/sympy#15024]
I'm using Sympy in order to get extrema and inflection points of certain functions.
When I used solveset in this case (I just put the function immediately to make reading easier):
```python
from sympy import S, diff, solveset, sqrt, symbols

x = symbols('x')
function = (x + 5)/sqrt(-x**2 - 10*x)
print(function)
solveset(function, x, S.Reals)
```
I get this error:
```
Traceback (most recent call last):
  File "...\stub.py", line 6, in <module>
    solveset(function, x, S.Reals)
  File "...\AppData\Local\Programs\Python\Python36\lib\site-packages\sympy\solvers\solveset.py", line 1127, in solveset
    return solveset(f.xreplace({symbol: r}), r, domain
  File "...\AppData\Local\Programs\Python\Python36\lib\site-packages\sympy\solvers\solveset.py", line 1145, in solveset
    return _solveset(f, symbol, domain, _check=True)
  File "...\AppData\Local\Programs\Python\Python36\lib\site-packages\sympy\solvers\solveset.py", line 942, in _solveset
    solver)
  File "...\AppData\Local\Programs\Python\Python36\lib\site-packages\sympy\solvers\solveset.py", line 717, in _solve_radical
    eq, cov = unrad(f)
TypeError: 'NoneType' object is not iterable
```
...which is somewhere around here:
https://github.com/sympy/sympy/blob/49a1c33d60a7359ad0acb7a13cd212b2e8d0ac80/sympy/solvers/solveset.py#L721-L723

**Comment by jksuom** [comment]
It seems that `unrad` returns `None`. It should mean that there are no radicals to remove, but that is probably not correct in this case because of the square root in the denominator.

**Comment by smichr** [comment]
As I recall, `unrad` gives you an expression whose roots contain (as a subset) the roots of the original expression. If there are no radicals to remove in the governing expression of the original expression (read: the numerator) then None will be returned. One does not need to solve a radical to get a solution to the given function. (The solver should have separated the numerator from the denominator before trying to solve as a radical equation.)

**Comment by oscargus** [comment]
In current master it produces `FiniteSet(Integer(-5))`, so I'll add a test and close this.
