### ISSUE TITLE
Lambdify can't deal with MatrixElements

### ISSUE THREAD

**Issue by willprice** [sympy/sympy#15037]
```python
m = MatrixSymbol('W', 1, 2)
lambdify([m[0,0], m[0,1]], m)
```

Results in the following error

```
  File "/home/will/.local/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2963, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  File "<ipython-input-123-d8fc2c009aba>", line 2, in <module>
    lambdify([m[0,0], m[0,1]], m)

  File "/usr/lib/python3.6/site-packages/sympy/utilities/lambdify.py", line 434, in lambdify
    func = eval(lstr, namespace)

  File "<string>", line 1
    lambda W[0, 0],W[0, 1]: (W)
```

I'm guessing this is probably due to the lack of support for `MatrixElement` objects in [`PythonCodePrinter`](https://github.com/sympy/sympy/blob/master/sympy/printing/pycode.py) which `lambdify` calls... but I'm very new to sympy and have only just started prodding around.

I'd be happy to do the work to fix this if someone could provide some guidance.

Thanks for the awesome project!

**Comment by willprice** [comment]
It seems that the `_EvaluatorPrinter` preprocesses arguments to handle those that don't map to valid python identifiers.

`lambdify` calls `_EvaluatorPrinter.doprint` to generate the lambda expression:

```python
    def doprint(self, funcname, args, expr):
        """Returns the function definition code as a string."""
        from sympy import Dummy

        funcbody = []

        if not iterable(args):
            args = [args]

        argstrs, expr = self._preprocess(args, expr)
...
```

Which calls `_EvaluatorPrinter._preprocess`

```python
    def _preprocess(self, args, expr):
        """Preprocess args, expr to replace arguments that do not map
        to valid Python identifiers.

        Returns string form of args, and updated expr.
        """
...
```

So it's probably at this stage that `MatrixElement`s should be handled so they're mapped to proper expressions, I see there is already code to handle `DeferredVector`s, perhaps the solution should be similar.

**Comment by sylee957** [comment]
Now, I think that it successfully gets lambdified, but features like
`lambdify([m[0, 0], m[0, 1]], m)` is not supported while
`lambdify([m[0, 0], m[0, 1]], m[0, 0])` is.

I think that the original issue is a bit of ambiguous type specification.
For example, how can a function return the parent array, if the array elements are passed to?

**Comment by asmeurer** [comment]
The parameter part of this is already fixed by the dummify logic in lambdify.

I'm also not sure if we should have a check for this. It's not too different from `lambdify(x, y)`. lambdify doesn't have any checks if the expression is meaningful. Things are a bit muddled here as well because lambdify currently does support retuning SymPy expressions and it's actually supported. So I think we would need to remove that before we could really change this in any way. Perhaps such a check if the modules list explicitly doesn't include sympy might be useful. Right now we have

```py
>>> x, y = symbols('x y')
>>> func = lambdify(x, y, 'numpy')
>>> func(0)
y
```

**Comment by asmeurer** [comment]
I think this should be closed as the original issue with MatrixElements parameters is fixed. We can open a new issue about consistency checks in lambdify if that is desired.

**Comment by asmeurer** [comment]
Opened an issue about the consistency checks at https://github.com/sympy/sympy/issues/18569.
