### ISSUE TITLE
Make settings kwargs explicit in `latex()`

### ISSUE THREAD

**Issue by moorepants** [sympy/sympy#15042]
See this comment: https://github.com/sympy/sympy/pull/15040#issuecomment-410574636

The documentation is much clearer and useful if we do:

`def my_func(a, b, c=None, d=True, f='leibowitz')`

versus:

`def my_func(a, b, **kwargs)`

because Sphinx will parse it and when viewing docstrings the kwargs are self documented. Many functions in SymPy could be improved like this. `latex()` is one of them.

**Comment by moorepants** [comment]
Related: https://github.com/sympy/sympy/issues/5987

**Comment by asmeurer** [comment]
This is a sub-issue of https://github.com/sympy/sympy/issues/14030

**Comment by yatna** [comment]
I would like to work on this

**Comment by moorepants** [comment]
Go for it!
