### ISSUE TITLE
IntegralTransform: default `_collapse_extra` missing return

### ISSUE THREAD

**Issue by cbm755** [sympy/sympy#15044]
I haven't quite narrowed this down to a particular problem, but this code looks wrong to me:
```py
    def _collapse_extra(self, extra):
        cond = And(*extra)
        if cond == False:
            raise IntegralTransformError(self.__class__.name, None, '')
```
I think that should end with `return cond`, at least the `doit` method looks to rely on this:
```py
            try:
                extra = self._collapse_extra(extra)
                return tuple([res]) + tuple(extra)
```

**Comment by jksuom** [comment]
I think you are right. It seems that this default `_collapse_extra` is actually used by many transforms. Only the (direct) Laplace and Mellin transforms have their own versions.
