### ISSUE TITLE
Derivative: when evaluate is False there is still some simplification

### ISSUE THREAD

**Issue by smichr** [sympy/sympy#15054]
`Derivative(f(x), x, x)` automatically collapses to `Derivative(f(x), (x, 2))`. If the Derivative is not to be evaluated then should even this be done? If this is automatic then we see
```
  2
 d
───(f(x))
  2
dx
```
rather than
```
   2
  d
─────(f(x))
dx dx
```

It would be easy to change this in #15049

**Comment by sidhantnagpal** [comment]
I would actually expect this to collapse:
```
In [4]: Derivative(f(x), x, x, x, x)
Out[4]: 
  4      
 d       
───(f(x))
  4      
dx       
```
For multi-variate functions, I would expect the output to be order-dependent (which it is):
```
In [5]: diffs = [x, x, x, y, y, z, z, z]

In [6]: Derivative(f(x, y, z), *diffs)
Out[6]: 
      8                
     ∂                 
───────────(f(x, y, z))
  3   2   3            
∂z  ∂y  ∂x             

In [7]: Derivative(f(x, y, z), x, y, x, z, z, y)
Out[7]: 
        6                  
       ∂                   
───────────────(f(x, y, z))
     2                     
∂y ∂z  ∂x ∂y ∂x         
```

**Comment by sidhantnagpal** [comment]
The issue is `evaluate` can have different meanings when trying to differentiate `f(x)` (`Function('f')`) and `sin(x)`.

**Comment by asmeurer** [comment]
I can't think of any advantage to distinguishing diff(f(x), x, x) and diff(f(x), (x, 2)). But if it falls out of the way evaluate=False works it's fine too. I agree that it should definitely keep the order.

**Comment by smichr** [comment]
OK. @bjodah , note that d.variables will give the uncollapsed list of variables: `f(x).diff(x,2).variables == (x, x)` so rather than checking that `len(d.args)==3` you could check `len(d.variables)==2`.

**Comment by bjodah** [comment]
@smichr Thanks, didn't think of that. I also realized that I was referring to Derivative in general (without `evaluate=False`) so I'm actually not convinced if it needs to canonicalize then..
