### ISSUE TITLE
Intersection between Plane and Segment3D returns points outside of the segment

### ISSUE THREAD

**Issue by smheidrich** [sympy/sympy#15069]
It seems to me that, as far as ``Plane.intersection`` is concerned, ``Segment3D`` is treated as if it wasn't delimited on both ends (i.e., as if it was a ``Line3D``), and so additional intersections that aren't actually within the segment are returned:
``` python
from sympy import Plane, Segment3D

plane = Plane([0,0,0], normal_vector=[1,1,1])

# this clearly has no intersection with the plane due to being cut off at z=1:
segment = Segment3D([0,0,1], [0,0,2])

intersections = plane.intersection(segment)

print(intersections) # yields: [Point3D(0, 0, 0)]

# basic sanity check: intersections should be part of the intersected objects
for intersection in intersections:
  assert intersection in plane # works fine
  assert intersection in segment # fails
```

The expected result is of course that ``Plane.intersections`` returns an empty list in this case.

An easy workaround for the time being is to just filter these out manually:
```python
def plane_segment3d_intersection(plane, segment):
  return [ x for x in plane.intersection(segment) if x in segment ]
```

But it would be nice if this could be fixed in sympy itself.

-----
Version info:
- Python 3.5.3
- Sympy 1.2-522-g0b350a21a (0b350a21a)

**Comment by czgdp1807** [comment]
I would like to work on this issue if it is not solved yet or anyone else is not working on this.
