### ISSUE TITLE
Rendered LaTeX in JupyterLab is centered justified as opposed to left justified in the notebook

### ISSUE THREAD

**Issue by moorepants** [sympy/sympy#15078]
In the new JupyterLab system SymPy rendered outpts are center justified:
![selection_227](https://user-images.githubusercontent.com/276007/43994665-bb309a56-9d55-11e8-87e7-300e968b2bc7.png)
But in the previous system (notebook server) the math is left justified:
![selection_228](https://user-images.githubusercontent.com/276007/43994669-d17f8ee8-9d55-11e8-9eda-bed4671862b6.png)
I personally prefer the notebook behavior (left justified), especially on wide screens. I'm not sure why it is different in both systems or if this is something in SymPy code or Jupyter code that causes this (I suspect it is something different in the Jupyter systems).

**Comment by asmeurer** [comment]
I'm sure it's a change in Jupyter. I would open an issue with them. They probably do it because the math is in equation format instead of inline, which we do because inline looks poor for larger equations.

**Comment by moorepants** [comment]
Opened here: https://github.com/jupyterlab/jupyterlab/issues/5107

**Comment by moorepants** [comment]
Fixed upstream here: https://github.com/jupyterlab/jupyterlab/pull/5115
