### ISSUE TITLE
[regression] lambdify with Matrix: `NameError: name 'Matrix' is not defined`

### ISSUE THREAD

**Issue by nschloe** [sympy/sympy#15071]
I'm trying to create a lambda function from a sympy expression that involves a dot product with a `sympy.Matrix`. Since at least sympy 1.2, this fails.

MWE:
```python
from sympy import Matrix
import sympy
import numpy


class dot(sympy.Function):
    pass


# def vector2vector(x):
#     out = numpy.array(x)
#     if len(out.shape) == 2 and out.shape[1] == 1:
#         out = out[:, 0]
#     return out

# mods = [{"ImmutableDenseMatrix": vector2vector}, "numpy"]

x = sympy.Symbol("x")
expr = dot(x, Matrix([[2], [1], [0]]))
f = sympy.lambdify(x, expr)

X = numpy.zeros((17, 3))
val = f(X)
```
Error message:
```
  File "<lambdifygenerated-1>", line 4, in _lambdifygenerated
NameError: name 'Matrix' is not defined
```

**Comment by asmeurer** [comment]
Bisected to 998946c03c0934b2bb638f182d728a31120488e7 CC @bjodah

**Comment by bjodah** [comment]
Mmmm yes, I remember you and I discussing that this could happen. `lambdify` was (and still is) quite under-tested. I opened gh-15085 with a test case that does pass. Is that viable?
