### ISSUE TITLE
Regression: Degradation of det function performance when applied to large matrices of polynomials.

### ISSUE THREAD

**Issue by petersbingham** [sympy/sympy#15086]
I was directed to post my issue from [stackoverflow](https://stackoverflow.com/questions/50398584/unhandled-exception-cant-unify-dmp-when-calculating-det-of-sympy-matrix) (although the exception seems to have changed slightly with my repo here).

This report is for different versions of sympy. I have ran the tests on windows 10. Other versions, which remain constant throughout are:
python: 2.7.14, 64 bit
mpmath: 1.0

I have attached a zip file containing five test files. The .py contains the test code. The .txt contain coefficients for the test polynomial. Run with all five files in the same path. There is code at the top of the .py file for loading and constructing the polynomial. The main test code is at the bottom. I can try and simplify on request but the issues only occur with certain polynomials.

Basically when running with sympy 1.0 I encounter no issues running the test code. However, in the .py test file note **line 92, where I wrap the expression in a sym.poly call**. I do this because it provides significant performance improvement. Without this it becomes unfeasible to run my calculations (I run for increasingly larger polynomials).

When I upgrade to sympy 1.1.1 (and also 1.2) I get the following exception from the attached test code (be sure to scroll right to the end):

```
PS C:\Users\Peter\Desktop\sympy_issue> python .\poly_issue_demo.py
Traceback (most recent call last):
  File ".\poly_issue_demo.py", line 96, in <module>
    symPoly = sym.polys.Poly(det, k)
  File "C:\Python27\lib\site-packages\sympy\polys\polytools.py", line 129, in __new__
    return cls._from_expr(rep, opt)
  File "C:\Python27\lib\site-packages\sympy\polys\polytools.py", line 239, in _from_expr
    rep, opt = _dict_from_expr(rep, opt)
  File "C:\Python27\lib\site-packages\sympy\polys\polyutils.py", line 365, in _dict_from_expr
    rep, gens = _dict_from_expr_if_gens(expr, opt)
  File "C:\Python27\lib\site-packages\sympy\polys\polyutils.py", line 304, in _dict_from_expr_if_gens
    (poly,), gens = _parallel_dict_from_expr_if_gens((expr,), opt)
  File "C:\Python27\lib\site-packages\sympy\polys\polyutils.py", line 214, in _parallel_dict_from_expr_if_gens
    raise PolynomialError("%s contains an element of the generators set" % factor)
sympy.polys.polyerrors.PolynomialError: Poly(-1.723162636630720360248902758158404281979152983998937180676324368544372684523711792611986180298271987e-194*k**18*I**4 + 1.993503159594273049683190177477060313029786086292605327364307180392403493596815806672298704461218768e-94*k**18*I**3 + 304745.0380088528742337835171220915479078443258452034656558732750692529360000519347983114120336091723*k**18*I**2 - 7.616252437071783433071679705124511154397078669668415285502907904902525890961053248731537632684712935e-196*k**11*I**3 + 2.32224886771847968027447760703299092849966094352660905127610728279175199819430305582309294014180503e-94*k**11*I**2 + 751450.1393509318953728494242558975815990885743042166883486516149087206644382471851353667650278870659*k**11*I - 3.471116165424268342478890060969273531998484318239836511730944788568903199073379091555434791464331627e-97*k**9*I**2 - 1104.631704682869552966089091530973374435453876381743096397150189169959388564818033135386696222711638*k**9*I + 1.117812269926931772995898364608020392388443238546894289188483707858058054817405799691883100682578498e-197*k**4*I**2 - 4.765162979673120996590135617192024450926233534404366965642988961643706946417093044274448727242985571e-96*k**4*I + 462770.1422200286012911780133228416598437028137357537546491553717334333256469520721580151378704535839*k**4 + 7.004789578062990559298633930765313869884833598632837805702152558972719920148207082613676172463392234e-99*k**2*I - 1360.544217906979458979713735797942600859232655243204997259899961766438931942881123846230707872535416*k**2 + 1.0, k, I, domain='RR') contains an element of the generators set
```
[poly_issue_demo.zip](https://github.com/sympy/sympy/files/2284887/poly_issue_demo.zip)

**Comment by jksuom** [comment]
Complex floating point coefficients have not been implemented in SymPy yet though there is some work being done (https://github.com/sympy/sympy/pull/12192). Those are necessary for converting SymPy expressions to polynomials by a `poly` call. Unfortunately, working with raw expressions can be time (and space) consuming. Expressions with exact (rational) complex coefficients can be converted to polynomials.

**Comment by petersbingham** [comment]
But it worked OK in 1.0. Is this known behaviour that has changed between versions?

**Comment by jksuom** [comment]
Did you compute successfully with polynomials in 1.0 using numbers like this?

 
-1360.393798360780044856477018417517128258181825797801822663234852702317479530758694403277270999911851 + 3.028755129743630048165040820491299486932384987680791282508318794359722116240588864740850378330409428e-98j

**Comment by petersbingham** [comment]
I believe so. The test code shown the coefficients of the polynomials used.

**Comment by petersbingham** [comment]
Sorry I should correct. The test file contains coefficients from which the final polynomial was constructed. Effectively the same result though.

**Comment by jksuom** [comment]
The imaginary part of the number above is negligent in comparison with the real part. Is it possible that a successful computation simply ignored the imaginary part?

**Comment by petersbingham** [comment]
Ah yes. It is possible but I will have to check this evening. So the 'breaking' change here is essentially that the later versions are not ignoring the small imaginary parts? So I could 'fix' in the latest by removing the small imaginary components. Thanks, I will investigate further and close if it is the case.

**Comment by jksuom** [comment]
The issue with this line

    new_poly_mat[i,j] = sym.poly(poly_mat[i,j])

is that it will create a polynomial of two variables, `k` and  the imaginary unit `I`. That will happen because complex floats are not implemented. This line will then raise an exception

    symPoly = sym.polys.Poly(det, k)

as it expects that det is a polynomial of one variable `k`. The second variable `I` is visible on the PolyError line. (This is something that may have changed since 1.0 though I have not checked that.)

**Comment by petersbingham** [comment]
Is it possible that in 1.0

`new_poly_mat[i,j] = sym.poly(poly_mat[i,j])`

the imaginary component has been dropped when creating the `new_poly_mat`?

**Comment by jksuom** [comment]
I don't think that was dropped in 1.0. It was probably a polynomial in `k` and `I`.

    det = new_poly_mat.det(method="berkowitz")

will also be a polynomial in `k` and `I`. The error message results when

    symPoly = sym.polys.Poly(det, k)

tries to transform it to a polynomial in the single variable `k`.

**Comment by petersbingham** [comment]
What you are saying may be correct in theory but it is not what I am observing. I've ran some additional tests and print to file the det repr prior to the call to `sym.polys.Poly` and the poly repr after. I ran these tests for:

1. Both 1.0 and 1.1.1 versions of sympy.
2. The polynomials constructed from the attached test files. Call this PolyBad.
3. Another polynomial, of the same nature as in 2. but causes no exception in either 1.0 or 1.1.1. This poly is smaller but it also has complex coefficients. Call this PolyGood.

This is what I observed:

1. The reprs of PolyGood both before and after the call to `sym.polys.Poly` contains I and k variables for both 1.0 and 1.1.1. This seems contrary to what you stated above: that I should get an exception since the Poly call will try to convert to Poly of single variable k. In other words, I am able to call `sym.polys.Poly(det, k)` with both I and k variables for certain polynomials with both 1.0 and 1.1.1 versions without getting an exception.
2. For both PolyBad and PolyGood I get different repr for the det prior to the call to `sym.polys.Poly`. For PolyBad with 1.1.1 the file is huge (6501KB), with 1.0 the file is 39KB.

**Comment by jksuom** [comment]
Can you give a (reasonably small) example of a polynomial `det` in `k` and `I` such that `Poly(det, k)` will succeed in 1.0 (or 1.1.1), and then also the result of that call. (Preferably as plain text files.)

**Comment by petersbingham** [comment]
I will but I'm going to close this and open two new tickets as I think there are two issues here:

1- The apparent `sym.polys.Poly(det, k)` one.
2- Degradation of the det function

Thanks

**Comment by petersbingham** [comment]
Reading the documentation here: [polytools.Poly](http://docs.sympy.org/latest/modules/polys/reference.html#sympy.polys.polytools.Poly) it appears that it is OK to call poly with only a single variable specified. It states that it will "Create a univariate polynomial, where y is a constant". In the case above y will be `I`. Perhaps I have misunderstood something?

**Comment by jksuom** [comment]
That should be true, and that is what happens in my tests on SymPy 1.2.
```
>>> from sympy import *
>>> from sympy.abc import k
>>> det = Poly(-1.723162636630720360248902758158404281979152983998937180676324368544372684523711792611986180298271987e-194*k**18*I**4 + 1.993503159594273049683190177477060313029786086292605327364307180392403493596815806672298704461218768e-94*k**18*I**3 + 304745.0380088528742337835171220915479078443258452034656558732750692529360000519347983114120336091723*k**18*I**2 - 7.616252437071783433071679705124511154397078669668415285502907904902525890961053248731537632684712935e-196*k**11*I**3 + 2.32224886771847968027447760703299092849966094352660905127610728279175199819430305582309294014180503e-94*k**11*I**2 + 751450.1393509318953728494242558975815990885743042166883486516149087206644382471851353667650278870659*k**11*I - 3.471116165424268342478890060969273531998484318239836511730944788568903199073379091555434791464331627e-97*k**9*I**2 - 1104.631704682869552966089091530973374435453876381743096397150189169959388564818033135386696222711638*k**9*I + 1.117812269926931772995898364608020392388443238546894289188483707858058054817405799691883100682578498e-197*k**4*I**2 - 4.765162979673120996590135617192024450926233534404366965642988961643706946417093044274448727242985571e-96*k**4*I + 462770.1422200286012911780133228416598437028137357537546491553717334333256469520721580151378704535839*k**4 + 7.004789578062990559298633930765313869884833598632837805702152558972719920148207082613676172463392234e-99*k**2*I - 1360.544217906979458979713735797942600859232655243204997259899961766438931942881123846230707872535416*k**2 + 1.0, k, I, domain='RR')
>>> Poly(det, k)
Poly((-304745.038008853 - 1.99350315959427e-94*I)*k**18 + (-2.32224886771848e-94 + 751450.139350932*I)*k**11 + (3.47111616542427e-97 - 1104.63170468287*I)*k**9 + (462770.142220029 - 4.76516297967312e-96*I)*k**4 + (-1360.54421790698 + 7.00478957806299e-99*I)*k**2 + 1.0, k, domain='EX')
```
I have been trying to figure out why your system would raise a PolynomialError.

**Comment by petersbingham** [comment]
I think it's the det function (as vastly different returns for PolyBad, at least for size) but I want to run a couple more tests. I'll add as a new issue later with detter definition and simpler reproduction.

**Comment by petersbingham** [comment]
Yes, with the latest version the resultant poly after the det is _much_ more complex. The fact that this has changed though is a regression bug, is it not? (I'll post the reproduction later, I just want to check that the det from sympy 1.0 works with the `sym.polys.Poly(det, k)` using 1.1.1. If it does then I'll know that `sym.polys.Poly(det, k)` is not a contributing factor here.

Basically the position I'm in is that I have to release my software with an old version of sympy, since the calculation break when I upgrade.

**Comment by asmeurer** [comment]
Related old mailing list post https://groups.google.com/forum/#!msg/sympy/vxOa1Et30x4/7uMgbfi_BAAJ, which links to https://github.com/sympy/sympy/issues/13805 and https://github.com/sympy/sympy/issues/11082

**Comment by jksuom** [comment]
It seems that the new implementation of the matrix module was not planned to work with polynomial objects. Their operations are not performed, presumably to save time. The resulting expressions that involve several Poly objects can not be handled by `sym.polys.Poly`.

With this patch I was able to run the demo code.
```
diff --git a/sympy/matrices/dense.py b/sympy/matrices/dense.py
index 9fa7822..f893ee6 100644
--- a/sympy/matrices/dense.py
+++ b/sympy/matrices/dense.py
@@ -190,7 +190,7 @@ def _eval_matrix_mul(self, other):
                 col_indices = range(col, other_len, other_cols)
                 vec = (mat[a]*other_mat[b] for a,b in zip(row_indices, col_indices))
                 try:
-                    new_mat[i] = Add(*vec)
+                    new_mat[i] = sum(vec, S.Zero)
                 except (TypeError, SympifyError):
                     # Block matrices don't work with `sum` or `Add` (ISSUE #11599)
                     # They don't work with `sum` because `sum` tries to add `0`
```
This could probably be included in the next release of SymPy.

**Comment by petersbingham** [comment]
Does this also explain why it works OK with some polynomial matrices and not others?
I have a new better demo using both good and bad polynomials. Would it still be useful to post here?

**Comment by jksuom** [comment]
The point is that matrices were initially not planned to work with polynomials. That they sometimes do is more or less accidental. The patch above is one place where handling of polynomials can be improved, but there may be other issues as well. It would probably be useful to post additional examples.

**Comment by petersbingham** [comment]
Some more tests: [new_test.zip](https://github.com/sympy/sympy/files/2295232/new_test.zip) 

The previous test code much simplified, with a couple of additional polynomials added. Rather than construct the polynomials I just eval them direct from the files. Some precision loss but I don't think it affects the issue from appearing. The code (which is in the new_test.py inside the attached zip) is basically the following function called on three different starting polynomial matrices:

```
def cal_det(file_name):
  with file(file_name+".dat", 'r') as f:
    poly_mat_str = f.read()
    poly_mat = eval(poly_mat_str)
    det = poly_mat.det(method="berkowitz")
    with file(file_name+"_det_"+sympy.__version__+".dat", 'wb') as f:
      f.write(repr(det))

cal_det("good_poly_matrix")
cal_det("bad_poly_matrix")
cal_det("bad_poly_matrix2")
```
The three names in the `cal_det` function calls at the bottom are the three polynomials contained in the files in the attached zip.

I've removed `sym.polys.Poly(det, k)` since there are no regression issues here (I've checked 1.0 against the determinants created with 1.1.1 and the behaviour is the same (ie exception)).

I've summarised my results in the table below. To reproduce these run the new_test.py twice: once with sympy 1.0 and again with 1.1.1. The output files will contain the sympy versions, so you can compare.

| Poly File Name   | Matrix Size | Max Poly Power | File Size v1.0 (KB) | File Size v1.1.1 (KB) | Time taken v1.0 (s) | Time taken v1.1.1 (s) |
|------------------|-------------|----------------|--------------------|----------------------|--------------------|----------------------|
| good_poly_matrix | 3x3         | 13             | 1.54               | 1.29                 | 0.0699             | 0.0632               |
| bad_poly_matrix  | 6x6         | 9              | 9.89               | 1750                 | 1.30               | 193                  |
| bad_poly_matrix2 | 6x6         | 2              | 0.303              | 290                  | 0.104              | 14.5                 |

3x3 seems OK (infact 1.1.1 appears marginally better here). 6x6 very much degraded, both for size of output and time required for calculation. Could obviously run for more matrix and poly sizes but hope this helps.

**Comment by asmeurer** [comment]
Perhaps a bit of topic to the issue at hand, but matrices naturally operate over fields, whereas Poly only forms a ring (1/Poly returns an Expr object). It would be more natural for matrices to operate over the polys domains rather than Poly itself. Matrices over non-fields could be useful (perhaps for agca), but there would need to be a clear separation between methods that require division and methods that don't.

**Comment by jksuom** [comment]
Thanks for the examples. It seems that changing `Add` to `sum` as I suggested above will suffice to solve also these issues. These are the results I get:
```
python new_test.py 
good_poly_matrix. Time taken: 0.090828
bad_poly_matrix. Time taken: 1.29784
bad_poly_matrix2. Time taken: 0.188008
```
I think that the patch should be merged into current code. (It is possible that the performance on some non-polynomial matrices would be slightly degraded but I don't expect that to be significant.)

**Comment by petersbingham** [comment]
Thanks. Looks like it might be fixed but maybe worth checking that we get no exception from the `sym.polys.Poly(det, k)`. If you leave your generated files here I can check if you think it's worth doing.

**Comment by jksuom** [comment]
There seem to be no problems with `Poly(det, k)` when `det` is produced by the patched code. The sizes of the three `det` files are 303, 9407 and 1330.

Are you interested in sending a PR on the patch?

**Comment by petersbingham** [comment]
Yes, I can send a PR if you want. Take it you need to send me the patch file?

**Comment by jksuom** [comment]
You can simply edit the single line in dense.py and apply git commit. (The patch will be created automatically by git or by GitHub. No physical patch file is necessary.) Follow the instructions in https://github.com/sympy/sympy/wiki/Development-workflow.

You should create a reasonable simple test matrix with Polynomial entries and assert that its determinant is a Poly (`det.is_Poly`) with the patch but not without it. A 4x4 sparse matrix would probably suffice. The polynomials could be simple and use integer coefficients. (Writing those will take less space than floating point numbers with 100 significant digits.)

**Comment by petersbingham** [comment]
OK, give me a day or two. Thanks again!

**Comment by jksuom** [comment]
`import Add` can be removed.

**Comment by petersbingham** [comment]
OK. Will do. Can you please assign to me. I will add my test into sympy\sympy\matrices\tests.

**Comment by jksuom** [comment]
You can add `test_issue_15086()` to test_matrices.py. I'll have suggestions for the matrices after some experiments.

**Comment by jksuom** [comment]
Here is one suggestion. First create a matrix with expression entries and then convert its entries to Polys by means of `applyfunc`.

    M = Matrix([[x, x, 0, 0], [x, 0, x, 0], [0, x, x, 0], [0, 0, x, x]])
    to_poly = lambda e: Poly(e, x)
    N = M.applyfunc(to_poly)
    assert N.det(method="berkowitz") == Poly(M.det())

**Comment by petersbingham** [comment]
I have all your suggested changes (and no more) ready. Passing your suggested test. Just running through all tests and checking that it fixes my own issues before PR.
Lots of thanks for fixing this and making my first sympy contribution so easy!

**Comment by petersbingham** [comment]
This is just a required change in usage: The following code works for all sympy versions:

```
try:
    from sympy.polys.polymatrix import PolyMatrix as sym_matrix
except ImportError:
    from sympy.matrices import Matrix as sym_matrix
```

**Comment by jksuom** [comment]
I would suggest the following:

    from sympy.polys.polymatrix import PolyMatrix as Matrix

(A try block should not be necessary, but if it is, then the except part could be `pass`.)
