### ISSUE TITLE
Warnings about autolev in install

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#15103]
When running setup.py install, there are some warnings

```
warning: no files found matching '*.tokens' under directory 'sympy/parsing/autolev'
warning: no files found matching '*.interp' under directory 'sympy/parsing/autolev'
warning: no files found matching '*.txt' under directory 'sympy/parsing/autolev'
```

See https://travis-ci.org/sympy/sympy/jobs/416949633#L1912

Indeed, the autolev submodule doesn't have any of these files. Were these included in setup.py, or are they generated somehow? If they are generated, should it be done at install time? If they shouldn't be there, then they should be removed from setup.py. 

CC @NikhilPappu @certik @moorepants

**Comment by asmeurer** [comment]
The files are the same as the LaTeX parser. But in the LaTeX parser submodule, those files are there. Any files that are generated by antlr should be checked into the repo, so that users don't have to run antlr. Only developers, who modify the parser, should have to re-run antlr. (when I say "antlr" here I mean the antlr generator, not the runtime which of course the users will need to run the submodule)

**Comment by NikhilPappu** [comment]
Aaron,
The .interp, .tokens etc are not needed so they could be removed from
setup.py. Also, those files aren't required for the parser to run. Only the
lexer, parser and listener files are required. The users do not need to run
antlr.

**Comment by asmeurer** [comment]
What about the ones in the LaTeX parser? Should they be removed too?

**Comment by NikhilPappu** [comment]
We could still include those files but I am not sure what they are for as
it runs just fine without them.

**Comment by NikhilPappu** [comment]
I guess they could be removed.

**Comment by asmeurer** [comment]
Also `MANIFEST.in` needs to be updated as well.
