### ISSUE TITLE
Expr.subs not working when symbols are defined with Symbol('')

### ISSUE THREAD

**Issue by saullocastro** [sympy/sympy#15127]
Why this is not working when I do `e.subs(dict(ab=1))`?
```
In [1]: from sympy import Symbol

In [2]: ab = Symbol('a_b')

In [3]: e = ab**2 + 2*ab

In [4]: e.subs(dict(ab=1))
Out[4]: a_b**2 + 2*a_b

In [5]: e.subs(dict(a_b=1))
Out[5]: 3
```

It is clear that `subs` is only working when I use the name `'a_b'` instead of the variable name. However, for slightly more complicated names like `Symbol(r'w_{,\xi}')` this workaround won`t work.

**Comment by jksuom** [comment]
`dict(ab=1)` denotes a dictionary having the string `'ab'` as its only key. To get a dictionary with key `ab` you have to write `{ab: 1}`.
```
>>> ab = Symbol('a_b')
>>> dict(ab=1)
{'ab': 1}
>>> {ab: 1}
{a_b: 1}
```

**Comment by smichr** [comment]
It would be nice if issues could be marked to self-close after a period of time. This one can be closed after a few days.

**Comment by saullocastro** [comment]
@smichr and @jksuom thank you!

**Comment by asmeurer** [comment]
@smichr now that we have a bot, these sorts of things are possible. You can open issues at https://github.com/sympy/sympy-bot for things that the bot could do. Is the idea to auto-close issues that are just questions once the question is answered and the discussion has stopped?

From a technical perspective, I'd have to figure out how to make the bot trigger after a set period of time. It's easiest to make the bot run after some activity. GitHub has [hooks](https://developer.github.com/webhooks/) that can be set up to trigger the bot for basically any kind of GitHub activity. I'd have to see if Heroku or some other service can let you put a hook on a timer. Or we can save the data in a data store and just check it whenever the bot runs for something else.
