### ISSUE TITLE
Sympy lambdify cannot handle lowergamma

### ISSUE THREAD

**Issue by CarloNicolini** [sympy/sympy#15134]
I need to lambdify an expression containing the `sympy.lowergamma` function.
However the lambdification of this expression results in an error, since the equivalent `mpmath` function is `mpmath.gammainc` and the names are different from `sympy.lowergamma`
Can the documentation contemple this cases?
Sympy 1.2
mpmath 1.0.0

**Comment by bjodah** [comment]
Looks like `MpmathPrinter` has a `_print_lowergamma` method. Could you provide a minimal (failing) example?

**Comment by CarloNicolini** [comment]
I believe I fixed this problem by providing the argument modules='mpmath'
Thanks!
