### ISSUE TITLE
Differentiation of product of non-commutative factors does not preserve the order of factors

### ISSUE THREAD

**Issue by mart-r** [sympy/sympy#15131]
When I have a product of non-commutative Function (of a non-commutative argument) and a non-commutative symbol, differentiation does not always preserve the order.

Example code:
```
import sympy
x = sympy.Symbol('x', commutative=False)
t = sympy.Symbol('t', commutative=False)
fx = sympy.Function('Fx', commutative=False)(x)
ft = sympy.Function('Ft', commutative=False)(t)
A = sympy.Symbol('A', commutative=False)
eq = fx * A * ft
print('eq:', eq)
eqdx = eq.diff(x)
print('diff x:', eqdx) 
eqdt = eq.diff(t)
print('diff t:', eqdt)
```
Output:
```
eq: Fx(x)*A*Ft(t)
diff x: Derivative(Fx(x), x)*A*Ft(t) # what one would expect
diff t: Derivative(Ft(t), t)*Fx(x)*A # derivative comes to the beginning, but shouldn't as they're not commutative 
```

Sympy version:
```
pip show sympy
Name: sympy
Version: 1.2
Summary: Computer algebra system (CAS) in Python
Home-page: http://sympy.org
Author: SymPy development team
Author-email: sympy@googlegroups.com
License: BSD
Location: /usr/local/lib/python2.7/dist-packages
Requires: mpmath
Required-by: 
```

I've got a fear it's got something to do with with the ` <class 'sympy.core.containers.Tuple'>` class.

When I (additionally) run:
```
print('eq:', eq, ['(arg, arg.is_commutative):', ] + [(arg, arg.is_commutative) for arg in sympy.preorder_traversal(eq)])
print('diff x:', eqdx, ['(arg, arg.is_commutative):', ] + [(arg, arg.is_commutative) for arg in sympy.preorder_traversal(eqdx)])
print('diff t:', eqdt, ['(arg, arg.is_commutative):', ] + [(arg, arg.is_commutative) for arg in sympy.preorder_traversal(eqdt)])
```

I get 
```
eq: Fx(x)*A*Ft(t) ['(arg, arg.is_commutative):', (Fx(x)*A*Ft(t), False), (Fx(x), False), (x, False), (A, False), (Ft(t), False), (t, False)]
diff x: Derivative(Fx(x), x)*A*Ft(t) ['(arg, arg.is_commutative):', (Derivative(Fx(x), x)*A*Ft(t), False), (Derivative(Fx(x), x), False), (Fx(x), False), (x, False), ((x, 1), None), (x, False), (1, True), (A, False), (Ft(t), False), (t, False)]
diff t: Derivative(Ft(t), t)*Fx(x)*A ['(arg, arg.is_commutative):', (Derivative(Ft(t), t)*Fx(x)*A, False), (Derivative(Ft(t), t), False), (Ft(t), False), (t, False), ((t, 1), None), (t, False), (1, True), (Fx(x), False), (x, False), (A, False)]
```

There is a `None` with a tuple of `(x, 1)` and `(t, 1)`. Turns out these args are of class ` <class 'sympy.core.containers.Tuple'>` so I've got a feeling that's the issue here.

Sorry if there's something similar somewhere already, my search did not amount to any useful issues.

**Comment by czgdp1807** [comment]
I would like to work on this issue. I would try my best to resolve the issue.

**Comment by czgdp1807** [comment]
I executed the code you provided on my local system, and it worked correctly, that is, the order was preserved. My sympy version 1.1.1 and I think this issue was created after sympy 1.2

**Comment by mart-r** [comment]
I copied my code from here (to make sure I hadn't made any changes to it while editing the post) and tried again in both python2 and python3 (sympy 1.2 still) and got the same result that I got previously.
So if 1.1.1 does in fact preserve the order, then the issue seems to stem from 1.2 indeed.
