### ISSUE TITLE
Wrong result for derivative of trace

### ISSUE THREAD

**Issue by Upabjojr** [sympy/sympy#15136]
```python
k = symbols("k")
X = MatrixSymbol("X", k, k)
B = MatrixSymbol("B", k, k)

expr = Trace(X**2*B)
```

The derivative returns:

```python
In [8]: expr.diff(X)
Out[8]: (I + X.T)*B.T*(I + X.T)
```

The correct result is `(X*B + B*X).T`

**Comment by smichr** [comment]
This was fixed in
```
commit cec1beddb1ae63c69851db0eef285236b539b71e
Author: Francesco Bonazzi <franz.bonazzi@gmail.com>
Date:   Tue Dec 11 22:36:47 2018 +0100

    Derivative of matrix expression is now implicit, i.e. no more parsers of ind
exed expressions.

:040000 040000 55eccc77fc2505b18601b12e4fa6186986f1c428 8efada38fb862fb2abef727f
1d44fe7109b18f5f M      sympy
```

The following can be uncommented in `sympy/matrices/expressions/tests/test_derivatives.py`
```python
    # Cookbook example 107:
    expr = Trace(X**2*B)
    # TODO: wrong result  <-- remove
    #assert expr.diff(X) == (X*B + B*X).T  < -- remove #
```

**Comment by arooshiverma** [comment]
Has this issue been worked upon? Can I contribute to this?

**Comment by vorabrijesh** [comment]
when I ran the above code on the terminal (which was downloaded with git clone)and on jupyter-notebook(through anaconda) it gives me different results,has this patch been updated?


![Screenshot from 2019-03-14 13-03-39](https://user-images.githubusercontent.com/33277439/54339817-eb96af00-465b-11e9-9d06-a835934963b9.png)

**Comment by oscarbenjamin** [comment]
Yes on master I get this:
```
In [1]: k = symbols("k") 
   ...: X = MatrixSymbol("X", k, k) 
   ...: B = MatrixSymbol("B", k, k) 
   ...:  
   ...: expr = Trace(X**2*B)                                                                                                                                  

In [2]: expr.diff(X)                                                                                                                                          
Out[2]: 
 T  T    T  T
B ⋅X  + X ⋅B 
```
which is equivalent to the form suggested by @Upabjojr above.

**Comment by shiksha11** [comment]
`k = symbols("k")
X = MatrixSymbol("X", k, k)
B = MatrixSymbol("B", k, k)

expr = Trace(X**2*B)`

I ran this code but I am getting this error:

TypeError: Mix of Matrix and Scalar symbols

**Comment by shiksha11** [comment]
> Yes on master I get this:
> 
> ```
> In [1]: k = symbols("k") 
>    ...: X = MatrixSymbol("X", k, k) 
>    ...: B = MatrixSymbol("B", k, k) 
>    ...:  
>    ...: expr = Trace(X**2*B)                                                                                                                                  
> 
> In [2]: expr.diff(X)                                                                                                                                          
> Out[2]: 
>  T  T    T  T
> B ⋅X  + X ⋅B 
> ```
> which is equivalent to the form suggested by @Upabjojr above.

This is not working. 
I ran this patch of code and i am getting type error.

TypeError: Mix of Matrix and Scalar symbols

**Comment by Upabjojr** [comment]
Forgot to close this issue.
