### ISSUE TITLE
sqrt(t**4 + 2*t**2 + 1) can't be simplified to t**2+1

### ISSUE THREAD

**Issue by retsyo** [sympy/sympy#15164]
I have over-use simplify but it is still a complex expression

```python
>>> t = symbols('t', real=True)
>>> simplify(trigsimp((sqrt(t**4 + 2*t**2 + 1)).simplify()))
sqrt(t**4 + 2*t**2 + 1)
```

**Comment by sidhantnagpal** [comment]
You could use `sqrt(factor(t**4 + 2*t**2 + 1))`.

**Comment by sidhantnagpal** [comment]
By the way, `trigsimp` is for trigonometric simplifications. I don't think it will be required here.
As for the original issue, the minimal example would be just `simplify(sqrt(t**4 + 2*t**2 + 1))`.

**Comment by retsyo** [comment]
In fact, the `sqrt(t**4 + 2*t**2 + 1)` is calculated ahead
```python
>>> t = symbols('t', real=True)
>>> A = Matrix([3*t-t**3, 3*t**2, 3*t+t**3])
>>> T = A.diff(t, 1).normalized().simplify()
>>> T
Matrix([
[-sqrt(2)*(t**2 - 1)/(2*sqrt(t**4 + 2*t**2 + 1))],
[              sqrt(2)*t/sqrt(t**4 + 2*t**2 + 1)],
[ sqrt(2)*(t**2 + 1)/(2*sqrt(t**4 + 2*t**2 + 1))]])
```

obviously the T can be written as 
```
[-sqrt(2)*(t**2 - 1)/(2*(t**2 + 1))],
[              sqrt(2)*t/(t**2 + 1)],
[ sqrt(2)*(t**2 + 1)/(2*(t**2 + 1))]
```

**Comment by normalhuman** [comment]
`factor(sqrt(t**4 + 2*t**2 + 1))` returns `t**2 + 1`. However, `factor(T)`  does not help with the matrix T in the previous comment.

**Comment by asmeurer** [comment]
`factor(deep=True)` simplifies the matrix.
