### ISSUE TITLE
Matrix.solve should not compute the inverse

### ISSUE THREAD

**Issue by isuruf** [sympy/sympy#15178]
`A.solve(b)` currently does `A.inv() * b` which is really slow when `b` has only 1 column

**Comment by souravsingh** [comment]
I am interested in taking a stab at this. What needs to be done?

**Comment by kss682** [comment]
Hi ,I am new to sympy and I would like to work on this issue.
Can someone guide me through it.
Thanks.

**Comment by isuruf** [comment]
For gaussian elimination, instead doing a rref calculation to compute the inverse, sympy should calculate the rref of the augmented matrix A|b and return the solution.

**Comment by ayushmankoul** [comment]
Hello @isuruf Can you please share the snippet of your code so that I can get familiar with this issue ? It seems more of decision issue as pointed out by @moorepants .I would like to work on this issue to get more familiar with Sympy code base. Please guide me how should I go about it ?

**Comment by FrackeR011** [comment]
hi @isuruf i would like to work on this if it is still unassigned .
i think in solve member function of matrix i have to check the condition of b having only one column . If condition is true calculate inverse using Gauss - Jordan elimination .

**Comment by ruchit2801** [comment]
Hi @isuruf, If the matrix is not a square matrix, then we have to raise a value error, because of under-determined or over-determined systems. And if the matrix is a square matrix, then we have to calculate rref of augmented matrix A|b and return right-most column as a solution. Is my logic correct? please clarify, so that I can work on code asap.

**Comment by isuruf** [comment]
See the conversation in https://github.com/sympy/sympy/pull/15341.

**Comment by shiksha11** [comment]
Hello everyone, I am new to sympy and I would like to work on this issue.
Can someone guide me through it?
Waiting for reply . 
Thanks :)

**Comment by souravgl0** [comment]
This issue should be closed as #15341 has been merged that addresses this.
