### ISSUE TITLE
Derivative.doit().doit() != Derivative.doit()

### ISSUE THREAD

**Issue by smichr** [sympy/sympy#15196]
As pointed out by @jksuom in #15049, a 2nd application of doit changes the initial instance of a "done" derivative. In the case below, an instance of `Derivative(f(x, g(x)), x, g(x))` appears in the doit result...so the 2nd application of doit does it again:
```python
>>> eq = Derivative(f(x, g(x)), x, g(x)) <--
>>> eq.doit()
Derivative(f(x, g(x)), (g(x), 2))*Derivative(g(x), x) + Derivative(f(x, g(x)), x, g(x))  <--
>>> _.doit() ==_
False
```

**Comment by shuhaowu** [comment]
I have seen a possible manifestation of this in the wild, resulting in incorrect results: https://notebooks.azure.com/anon-usgzlw/projects/sympy-ds-derivative-bug/html/sympybug.ipynb

**Comment by jmig5776** [comment]
I would like to fix this issue. @smichr Can you guide me what is exactly to be done.

**Comment by sidhantnagpal** [comment]
This issue seems to be fixed in master:
```py
In [4]: eq = Derivative(f(x, g(x)), x, g(x))                                    

In [5]: eq.doit()                                                               
Out[5]: 
   2                          ⎛   2          ⎞│      
  d                d          ⎜  ∂           ⎟│      
──────(f(x, g(x)))⋅──(g(x)) + ⎜─────(f(x, ξ))⎟│      
     2             dx         ⎝∂x ∂ξ         ⎠│ξ=g(x)
dg(x)                                                

In [6]: _.doit() == _                                                           
Out[6]: True
```

**Comment by smichr** [comment]
tested [here](https://github.com/sympy/sympy/pull/15049/files#diff-5f25427da46082ec269576baef49a5c4R310). Sorry I missed closing this.
