### ISSUE TITLE
Wrong linear_eq_to_matrix if equations not expanded

### ISSUE THREAD

**Issue by mcsoini** [sympy/sympy#15195]
I noticed that `linear_eq_to_matrix` doesn't yield the correct matrix if the linear equations are not fully expanded. For example
```python
>>> x1, x2, mu = symbols('x1, x2, mu')
>>> equations = Matrix([[mu * (x1 + x2) + mu],
>>>                     [5 * x2 - 1]])
>>> A, b = linear_eq_to_matrix(equations, symbols)
>>> A
```
gives the wrong result `Matrix([[0, 0], [0, 5]])`. This can be fixed by adding `equations = equations.expand()` prior to the `linear_eq_to_matrix` call. Would it make sense to include an `expand` call in the `linear_eq_to_matrix` method itself? Willing to submit the pull request.

**Comment by cbm755** [comment]
Maybe it will be fixed by #14999?  Can you check?  We'd certainly welcome a pull request that adds a test for this, either on top of #14999 or wait until it is merged...

**Comment by cbm755** [comment]
I think you meant
```
A, b = linear_eq_to_matrix(equations, [x1, x2])
```
And it seems this is still an issue on #14999: more specifically, I'm using:
```py
>>> x1, x2, mu = symbols('x1, x2, mu')
>>> equations = [mu * (x1 + x2) + mu, 5 * x2 - 1]
>>> A, b = linear_eq_to_matrix(equations, [x1, x2])
```

#14999 also breaks putting the equations as rows of a matrix: we should probably fix that.

**Comment by mcsoini** [comment]
Of course, my bad.

**Comment by cbm755** [comment]
So this will become a ValueError after #14999, certainly better than a wrong answer.

I think your original comment holds: we need to decide if `linear_eq_to_matrix` should automatically expand such things.

**Comment by smichr** [comment]
#14999 is a convenience function to extract coefficients from a trivially linear system (i.e. fully expanded). If you have a more complicated system of equations, consider either linsolve (which will expand your system and warn if there are persisting non-linear terms) or jacobian:

```python
>>> Matrix([[mu * (x1 + x2) + mu], [5 * x2 - 1]]).jacobian([mu, x1, x2])
Matrix([
[x1 + x2 + 1, mu, mu],
[          0,  0,  5]])
```

**Comment by cbm755** [comment]
@smichr thanks for addressing this

**Comment by cbm755** [comment]
@mcsoini after #15212 is merged, do you think you could make a test case from your example and submit it as a PR?

**Comment by cbm755** [comment]
I'm also curious if `a*(2*x+3*y)` works and `a*(sin(b)*x+(c+cos(b))*y)`.
