### ISSUE TITLE
Remove Permutation.print_cyclic flag

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#15201]
See the discussion at https://github.com/sympy/sympy/pull/15198. The Permutation printing should be handled in the SymPy printers, not on the object itself. The flag should be a flag to the printer. Any doctest that wants to change the printing should set the flag in `init_printing`. However, whichever is set as the default should be used everywhere. 

Since it is publicly documented, it will need to be deprecated https://github.com/sympy/sympy/wiki/Deprecating-policy.

Additionally, it would be best if the `str` printer printed a Python valid representation and the pretty printers only (pprint/latex) printed things like (1 2 3).

**Comment by sudz123** [comment]
Hi I am looking to fix this error. Could you guide me on this one a bit? 
From what I understood `permutations.py` has some functions which use `print_cyclic` flag. But since this is a global flag, it should not be used. Instead it should use something from the `printing` module? Do I need to go through the `printing` module thoroughly? How do I get started on this?

**Comment by valglad** [comment]
@sudz123 Users should send printing preferences via `init_printing`, not by changing class attributes. So `print_cyclic` from the `Permutation` class should be deprecated, and `init_printing` should get a new keyword argument so we could do `init_printing(cyclic=True)` (or something like that) if we wanted permutations to be printed in cyclic notation.`init_printing` is [here](https://docs.sympy.org/latest/_modules/sympy/interactive/printing.html#init_printing).

> Additionally, it would be best if the str printer printed a Python valid representation and the pretty printers only (pprint/latex) printed things like (1 2 3).

Right now, permutation printing is all specified in its `__repr__` - this should always return `Permutation(<list>)` (i.e. what's returned now when `Permutation.print_cyclic=False`). The new "cyclic" flag should only be relevant when `pprint` and `latex` are called. The printing module is huge, but you only need to work out how to make `pprint` and `latex` work properly with the new keyword argument. For example, for `pprint`, you'll need to add `'cyclic'` (or whatever you decide to call it) to `PrettyPrinter._default_settings` and write a new method `_print_Permutation`.

**Comment by asmeurer** [comment]
Your interpretation is correct. init_printing should display the same thing as pprint or latex, depending on which printer it selects.

**Comment by souravgl0** [comment]
@asmeurer , Please review my PR #15691. It's a WIP and the tests are failing. But I need your review to continue further.
