### ISSUE TITLE
Eq.integrate doesn't evaluate the integral

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#15218]
```
>>> Eq(x, y).integrate(x)
Eq(Integral(x, x), Integral(y, x))
```

The integrals should actually be evaluated.

**Comment by ayushmankoul** [comment]
Hello @asmeurer I would like to work upon this issue to get familiar with integrals module.There is another [issue](https://github.com/sympy/sympy/issues/15209) which has developed my interest to work on integrals module. I am seriously looking forward to work on implementation of Risch Algorithm in integrals module.Please guide me for the same and this issue.
