### ISSUE TITLE
PyDy examples need to include the PyDy license

### ISSUE THREAD

**Issue by moorepants** [sympy/sympy#15214]
There is a new directory in `sympy/parsing/autolev/tests`:

```
│   ├── pydy-example-repo
│   │   ├── chaos_pendulum.al
│   │   ├── chaos_pendulum.py
│   │   ├── double_pendulum.al
│   │   ├── double_pendulum.py
│   │   ├── __init__.py
│   │   ├── mass_spring_damper.al
│   │   ├── mass_spring_damper.py
│   │   ├── non_min_pendulum.al
│   │   └── non_min_pendulum.py
```

These examples are copied from PyDy, but the PyDy license isn't included. I don't care personally, but we should probably follow protocol and include the PyDy license.

**Comment by moorepants** [comment]
@NikhilPappu fyi

**Comment by NikhilPappu** [comment]
@moorepants Sure, I shall include it.

**Comment by FrackeR011** [comment]
i am not able to find PyDy license ? do you mean including this [citation](http://proceedings.asmedigitalcollection.asme.org/proceeding.aspx?articleid=1830918) ?

**Comment by moorepants** [comment]
https://github.com/pydy/pydy/blob/master/LICENSE.txt
