### ISSUE TITLE
Travis job .21 fails with NoSpaceLeftError

### ISSUE THREAD

**Issue by jksuom** [sympy/sympy#15224]
It seems that sage has grown too big.

**Comment by asmeurer** [comment]
CC @isuruf 

If we can't find a solution to this soon we should just disable the sage tests.

**Comment by asmeurer** [comment]
Is it possible to just install the core part of Sage that is needed for the Sage tests?

**Comment by isuruf** [comment]
It's possible to install `sagelib` which might not be enough depending on what modules you import from sage.

**Comment by asmeurer** [comment]
Also why are we pinning sage=8.1?

**Comment by isuruf** [comment]
sage>=8.2 failed with no space left error, because of more dependencies
