### ISSUE TITLE
TypeError: 'ConditionSet' object is not iterable when calculating definite integral

### ISSUE THREAD

**Issue by apalmer1377** [sympy/sympy#15285]
```
>>> from sympy import *
>>> from sympy.abc import x,y
>>> f = (4 * (1/y - 1) * exp(-2 * (1/y - 1))) / (y**2)
>>> integrate(f,(y,0,1))
...
    for s in singularities:
TypeError: 'ConditionSet' object is not iterable
```

A similar issue happened in issue #13433, though this was fixed inadvertently by the changes in #14097. In this instance, the singularities of the function are defined by the ConditionSet

```
ConditionSet(y, Eq(y*exp(2/y), 0), Interval(0, 1))
```

and so when trying to iterate over this, python throws an error. I think an easy fix would be to catch the exception and pass, but there could be a better solution.

**Comment by asmeurer** [comment]
Agree it should just catch it and pass.
