### ISSUE TITLE
Absolute value returns incorrect solution

### ISSUE THREAD

**Issue by jpskycak** [sympy/sympy#15298]
tried this on sympy.live to make sure it's not just a local error

`solve(sympify('Abs(x)'),symbols('x',real=True))`
`[]`

solution should be [0], not the empty set

**Comment by jksuom** [comment]
The symbol `x` that sympify will create in 'Abs(x)' is different from `symbols('x', real=True)`. Therefore there is no solution. The same symbol should be used. For example,
```
>>> from sympy import *
>>> x = symbols('x', real=True)
>>> solve(Abs(x), x)
[0]
```

**Comment by jpskycak** [comment]
Oh, got it. Thank you!
