### ISSUE TITLE
Heaviside rewritten as Piecewise does not set H0

### ISSUE THREAD

**Issue by jksuom** [sympy/sympy#15293]
The value of `Heaviside` at 0 is undefined by default. Therefore its piecewise expression involves the unknown value `Heaviside(0)`.
```
>>> from sympy import Heaviside, Piecewise
>>> from sympy.abc import x
>>> Heaviside(x).rewrite(Piecewise)
Piecewise((0, x < 0), (Heaviside(0), Eq(x, 0)), (1, x > 0))
```
It is often useful to fix the value, for example, for integration. The private method `_eval_rewrite_as_Piecewise(self, arg, H0=None)` of `Heaviside` can do that.
```
>>> Heaviside(x)._eval_rewrite_as_Piecewise(x, 1)
Piecewise((0, x < 0), (1, True))
```
However, the value `H0` is not passed over by the public `rewrite` method.
```
>>> Heaviside(x).rewrite(Piecewise, 1)
Heaviside(x)
>>> Heaviside(x).rewrite(Piecewise, H0=1)
Piecewise((0, x < 0), (Heaviside(0), Eq(x, 0)), (1, x > 0))
```
This should not be hard to fix. The argument `H0=None` should be replaced by a keyword argument `**kw`. One only has to be careful not to override `H0` if that has been set earlier but there is no keyword `H0`. Something like this would probably work:

        if not hasattr(self, 'H0') or 'H0' in kw:
            H0 = kw.get('H0')

The public `rewrite` accepts keyword arguments as `**hints`. It will also pass them over except at [one place](https://github.com/sympy/sympy/blob/master/sympy/core/basic.py#L1589) where `**hints` should be added. Then `Heaviside(x).rewrite(Piecewise, H0=1)` should give the same result as `Heaviside(x)._eval_rewrite_as_Piecewise(x, 1)`.

**Comment by aionkgp** [comment]
Hi, I want to give this bug a try and I am totally a beginner here, so would you please guide me a bit on this one. Thankyou

**Comment by jksuom** [comment]
You should start with https://github.com/sympy/sympy/wiki/Introduction-to-contributing and https://github.com/sympy/sympy/wiki/Development-workflow.

**Comment by ayushmankoul** [comment]
Hello, @jksuom I would like to work on this issue. I was going through your description of the issue and the codebase to understand the issue which I interpreted as that the value of Heaviside at 0 is undefined by default which can be resolved by fixing the piecewise expression for it. Please correct me if I am wrong, the possible changes we need to make in the code which you have mentioned in the description : 
1. The argument `H0=None` should be replaced by a keyword argument `**kw`  in `_eval_rewrite_as_Piecewise(self, arg, H0=None)` method defination.
2. The following code needs to incorporated in `_eval_rewrite_as_Piecewise`  to handle overriding of  `H0`
```
    if not hasattr(self, 'H0') or 'H0' in kw:
        H0 = kw.get('H0')

```
Are these changes we need to make in code or anything else? Please guide me how should I proceed about it ?

**Comment by jksuom** [comment]
I think that something like that should be done in `Heaviside._eval_rewrite_as_Piecewise` but that is not all. It should also be taken care that the keywords (`**hints`) will be passed to private methods if they are present. There should also be tests that would confirm the expected behaviour.

Also @aionkgp has shown interest in this so maybe we should wait a little to see how he is getting on.

**Comment by ayushmankoul** [comment]
Sure @jksuom Let us wait for the response from @aionkgp ,if he would like to continue to work on this issue.

**Comment by aionkgp** [comment]
I am also stuck at that part where we incorporate the above-mentioned code to get 'H0' from kw, beacuse the **hints is not passed to the private method `Heaviside._eval_rewrite_as_Piecewise`.

**Comment by jksuom** [comment]
[This](https://github.com/sympy/sympy/blob/master/sympy/core/basic.py#L1589) is the call where `**hints` are missing. They could be added as follows:

    if hints:
        rewritten = getattr(self, rule)(*args, **hints)
    else:
        rewritten = getattr(self, rule)(*args)

Most rules do not expect keyword parameters. Therefore the original line should be left as is if there are no hints. (Also all private `_eval_rewrite_as_Piecewise` should have `**kw` added as a parameter even if it is not used. You can find those by running `git grep 'def _eval_rewrite_as_Piecewise'`.)

**Comment by aionkgp** [comment]
@jksuom I have made the changes in the code where you have suggested as follows
```  if hasattr(self, rule):
             if hasattr(self, rule):
                if hints:
                   rewritten = getattr(self, rule)(*args, **hints)
                else:
                    rewritten = getattr(self, rule)(*args)
                if rewritten is not None:
                   return rewritten
```
and I think I got the right result
```
>>> from sympy import Heaviside, Piecewise
>>> from sympy.abc import x
>>> Heaviside(x).rewrite(Piecewise, H0=1)
Piecewise((0, x < 0), (1, True))
>>> Heaviside(x).rewrite(Piecewise, H0=0)
Piecewise((0, x <= 0), (1, True))
>>> Heaviside(x)._eval_rewrite_as_Piecewise(x, 1)
Piecewise((0, x < 0), (1, True))
>>> Heaviside(x)._eval_rewrite_as_Piecewise(x, 0)
Piecewise((0, x <= 0), (1, True))
```

and I have also added the **kw argument as parameter in all private `_eval_rewrite_as_Piecewise`
but upon running `./bin/test` for testing
I got many [test failed](https://pastebin.com/31RqhMUh) and which I can't understand

**Comment by jksuom** [comment]
It seems that the keyword `deep` is causing errors. It should be removed before calling the private rewrite method. Then `**hints` should be added to the call only if something else is left.

             if hasattr(self, rule):
                hints.pop('deep', None)
                if hints:
                   rewritten = getattr(self, rule)(*args, **hints)
                else:
                    rewritten = getattr(self, rule)(*args)
                if rewritten is not None:
                   return rewritten

There may be other errors. It would be easier to fix those if you send a PR even if some errors should remain.
