### ISSUE TITLE
LaTeX printing for Matrix Expression

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#15303]
```py
>>> A = MatrixSymbol("A", n, n)
>>> latex(trace(A**2))
'Trace(A**2)'
```

The bad part is not only is Trace not recognized, but whatever printer is being used doesn't fallback to the LaTeX printer for the inner expression (it should be `A^2`).

**Comment by ethankward** [comment]
What is the correct way to print the trace? AFAIK there isn't one built in to Latex. One option is ```\mathrm{Tr}```.

**Comment by asmeurer** [comment]
What's the difference between the two. It looks like we use both in different parts of the latex printer.

**Comment by jksuom** [comment]
`\operatorname` is intended for printing without parentheses (like `Tr M`).

**Comment by ruchit2801** [comment]
Hi! I want to work on this issue. You mean instead of printing 'Trace(A**2)', it should print 'Trace(A^2)' right?

**Comment by asmeurer** [comment]
@ruchit2801 this was already fixed at https://github.com/sympy/sympy/pull/15308. Be sure to look for pull request cross references on issues to see if they are already being worked on (notice the link above to "@ethankward ethankward referenced a pull request that will close this issue 28 days ago
**Add LaTeX printing for matrix symbol trace** #15308").
