### ISSUE TITLE
sympy solve

### ISSUE THREAD

**Issue by gitlyap** [sympy/sympy#15325]
Hi,

after the sympy version 1.1.1 (with python 3.7) there is a `RecursionError` when solving a equation (see minimal example): "RecursionError: maximum recursion depth exceeded while calling a Python object"
With version 1.1.1 the error does not occur.
minimal example:
```python
import sympy as sp
T1, T2, p1, p2, n = sp.symbols('T1 T2 p1 p2 n')
eq = sp.Eq(T1/T2, (p1*p2)**((n-1)/n))                 
sp.solve(eq)
```

**Comment by sidhantnagpal** [comment]
Bisected it to the commit https://github.com/sympy/sympy/commit/91cc3d5f6523385091a03ab4ae5deff68019389e from #14712. (CC @smichr)
Prior to it:
```
In [4]: T1, T2, p1, p2, n = symbols('T1 T2 p1 p2 n')

In [5]: eq = Eq(T1/T2, (p1*p2)**((n-1)/n))

In [6]: solve(eq)
Out[6]: 
⎡⎧              n - 1⎫⎤
⎢⎪              ─────⎪⎥
⎢⎨                n  ⎬⎥
⎢⎪T₁: T₂⋅(p₁⋅p₂)     ⎪⎥
⎣⎩                   ⎭⎦
```

**Comment by smichr** [comment]
minimal example:
```
>>> solve(y**(-1/x)-z,x)
```

**Comment by smichr** [comment]
ping @sidhantnagpal (see #15317)

**Comment by smichr** [comment]
Trying to solve for the `n` causes the recursion but with #15317 it doesn't...and then the previous solution can be returned:

```
>>> solve(eq)
[{T1: T2*(p1*p2)**((n - 1)/n)}]
```

**Comment by sidhantnagpal** [comment]
Commit https://github.com/sympy/sympy/pull/15317/commits/0c25eec3b9f2e342e25c353d5913b0059b5e726f looks good.
