### ISSUE TITLE
Global variable substitution

### ISSUE THREAD

**Issue by trenoduro** [sympy/sympy#15339]
Can something like **redefine()** be implemented?

```
from sympy import *

x, y = symbols("x y")

expr1 = 2*x + y
expr2 = x**2 + 2*y

x.redefine(symbols("foo"))
print(expr1, expr2)

x.redefine(2)
print(expr1, expr2)
```
Output:
```
2*foo + y, foo**2 + 2*y
4 + y, 4 + 2*y
```

**Comment by warnerjon12** [comment]
Assuming that symbols are stored as references (which I believe they are), this would be equivalent to assigning all properties of x to properties from the symbol foo. But then your variable in Python would have a different name than in SymPy and that could get confusing. It would make more sense to use expr1.subs(x, symbols("foo")) to change the expression accordingly.

**Comment by trenoduro** [comment]
Sadly using subs() when you have a lot of expressions and a lot of variables in inconvenient..

**Comment by leosartaj** [comment]
@trenoduro You can use a dictionary as an argument for subs. Something Like

```
from sympy import symbols

x, y, z, t = symbols("x y z t")

expr1 = 2*x + y

print(expr1.subs({x: z, y: t}))
>>> 2*z + t
```

I don't feel ``redefine`` is a good way to go. SymPy expressions are in general immutable. Something like ``redefine`` can cause potential confusion since it will mutate already created expressions.
