### ISSUE TITLE
create_expand_pow_optimization() is not robust

### ISSUE THREAD

**Issue by zachetienne** [sympy/sympy#15335]
Using SymPy 1.3:

```
import sympy as sp
from sympy.codegen.rewriting import create_expand_pow_optimization
expand_opt = create_expand_pow_optimization(7)
a = sp.symbols("a")
expr = a**(5) - a**2
print("should be a**5 - a**2:",expr)
print("should be a*a*a*a*a - a*a:",expand_opt(expr))
expr = a**(-5)
print("should be a**(-5):",expr)
print("should be equal to a**(-5):", expand_opt(expr))
```

Output is:
```
should be a**5 - a**2: a**5 - a**2
should be a*a*a*a*a - a*a: -a**2 + a*a*a*a*a
should be a**(-5): a**(-5)
should be equal to a**(-5): 1
```

Notice that it failed to optimize `-a**2` and more disturbingly `a**(-5)` was evaluated to `1`.

**Comment by asmeurer** [comment]
CC @bjodah

**Comment by zachetienne** [comment]
Replacing

```
return ReplaceOptim(
        lambda e: e.is_Pow and e.base.is_symbol and e.exp.is_integer and e.exp <= limit,
        lambda p: Mul(*([p.base]*p.exp), evaluate=False)
    )
```

with
```
return ReplaceOptim(
        lambda e: e.is_Pow and e.base.is_symbol and e.exp.is_integer and e.exp.is_nonnegative and e.exp <= limit,
        lambda p: Mul(*([p.base]*p.exp), evaluate=False)
    )
```
in line 224 of sympy/codegen/rewriting.py 

fixes the most egregious problem -- i.e., `a**(-5) = 1`. I'm still confused as to why multiplying by `-1` results in the optimization not being performed.

**Comment by asmeurer** [comment]
Looks like `replace` (via `xreplace`) doesn't respect unevaluated Muls. The issue is basically:

```py
>>> (-x).xreplace({x: Mul(a, a, evaluate=False)})
-a**2
```

because

```py
>>> Mul(-1, Mul(a, a, evaluate=False))
-a**2
```

I don't know how easy it is to fix. Unevaluated expressions are a bit fragile. It probably would be smarter to create a custom unevaluated Mul object for the code generator and replace it with that instead.

**Comment by bjodah** [comment]
Thank you for reporting this @zachetienne, would you mind opening a PR with your suggested fix, so that we at least aren't returning incorrect results?

**Comment by zachetienne** [comment]
I'm sorry, I have no idea how to submit a pull request. When I attempted the instructions, I was met with the error message:

remote: Permission to sympy/sympy.git denied to zachetienne.

**Comment by zachetienne** [comment]
I clicked the wrong button and closed the ticket. How to reopen?

**Comment by zachetienne** [comment]
Whoops, clicked the wrong button and closed the ticket. Reopening.

**Comment by zachetienne** [comment]
@bjodah : Sorry I have no experience in opening PRs. The patch is a one-liner above.

**Comment by zachetienne** [comment]
Here is the pull request: https://github.com/sympy/sympy/pull/15338

**Comment by bjodah** [comment]
So #15338 fixed the incorrect result. Next step would probably make e.g. `x**-4` print as `1.0/(x*x*x*x)`

**Comment by bjodah** [comment]
Handling negative exponent here: https://github.com/sympy/sympy/pull/16654
Still need to fix negative leading coefficient (e.g. `-x**4`)
