### ISSUE TITLE
C functions generated by autowrap are not compatible with SciPy optimization packages

### ISSUE THREAD

**Issue by j-m-t** [sympy/sympy#15348]
I would like to solve a system of nonlinear equations using SciPy's `fsolve` wrapper with a function generated by SymPy's `autowrap` module, using the Cython backend. Unfortunately, I am coming across problems with creating a C function that takes the `x0` argument as a one-dimensional array, as required by `fsolve`. This is possible using SymPy's `lambdify` module.  Before I get into those details, here are the packages I am using, and their version numbers:

``` python
import sys
import sympy
import numpy as np
import scipy
from scipy.optimize import fsolve
from sympy.utilities.autowrap import autowrap
from sympy.utilities.codegen import codegen
from sympy.abc import x,y,a,b,c

sys.version
'3.5.4 |Anaconda custom (64-bit)| (default, Nov  3 2017, 20:01:27) \n[GCC 7.2.0]'

sympy.__version__
'1.1.1'

np.__version__
'1.12.1'

scipy.__version__
'1.0.0'
```

First, I wanted to write up an example that I found __[here](https://www.mathworks.com/help/optim/ug/fsolve.html)__:

![equation1](http://www.sciweavers.org/tex2img.php?eq=%24%24f_1%20%3D%20%5Cexp%28-%5Cexp%28-%28x%2By%29%29%29%20-%20y%2A%28a%2Bx%5Eb%29%24%24&bc=White&fc=Black&im=jpg&fs=12&ff=arev&edit=0)

![equation2](http://www.sciweavers.org/tex2img.php?eq=%24%24f_2%20%3D%20x%2A%5Ccos%28y%29%20%2B%20y%2A%5Csin%28x%29%20-%20c%24%24&bc=White&fc=Black&im=jpg&fs=12&ff=arev&edit=0)

where `a=1`, `b=2`, and `c=0.5`

## Lambdify
Here is how I solve this problem with `lambdify` - I make use of the `IndexedBase` type to treat the variables as arrays.  This requires some hacking of the `IndexedBase` objects with `subs` but it works in the end:

```python
# Create array-like objects
guess = sympy.IndexedBase('endog')
args = sympy.IndexedBase('exog')
# Define symbols
endog = [x, y]
exog = [a, b, c]
# Substitute
subs = {x: guess[0], y: guess[1], a: args[0], b: args[1], c: args[2]}
# Define our equations
f1 = sympy.exp(-sympy.exp(-(x+y))) - y*(a+x**b)
f2 = x*sympy.cos(y) + y*sympy.sin(x) - c
# Substitute the SymPy variables with positions in the IndexedBase objects
l_f1 = f1.subs(subs)
l_f2 = f2.subs(subs)
# Lambdify
l_f = sympy.lambdify((guess, args), [l_f1, l_f2], modules=['numpy'])
```
This creates a function that takes data of the following form:
```python
# Declare endogenous data, something arbitrary
x_d = np.array([2,2])
# Declare our exogenous data
z_d = np.array([1,2,0.5])
```
Passing this into the function gives us the following:
```python
l_f(x_d,z_d)
[-9.0181489269383341, 0.48630118055707872]
```
Finally, we pass this function and the data into `fsolve`:
```python
l_results = fsolve(l_f, x0=x_d, args=(z_d), full_output=True); l_results[0]
array([ 0.35324662,  0.60608174])
```
This matches what was found in the link posted above, but it is really slow.  This is why I want to use C.

## Autowrap

I try something similar with `autowrap`, where I pass in the equations that have substitutions referencing the `IndexedBase` objects, but I get the following error:

```python
aw_f_test = autowrap([l_f1, l_f2], language='C99', backend='cython',
                     tempdir='cython/', args=[guess,args])
...
IndexException: 
Range is not defined for all indices in: endog[0]
```
Much like in issue __[#11033](https://github.com/sympy/sympy/issues/11033)__, it seems that the `IndexedBase` objects aren't understood to be arrays.

Another method that I tried, which I learned in issue __[#14049](https://github.com/sympy/sympy/issues/14049)__, involves using `MatrixSymbol` objects:
```python
endog_matrix = sympy.MatrixSymbol('endog_m', 2, 1)
exog_matrix = sympy.MatrixSymbol('exog_m', 3, 1)
subs_cg = {x: endog_matrix[0], y: endog_matrix[1], 
           a: exog_matrix[0], b: exog_matrix[1], c: exog_matrix[2]}
cg1 = f1.subs(subs_cg)
cg2 = f2.subs(subs_cg)
rhs_cg = sympy.Matrix([cg1, cg2])
lhs_cg = sympy.MatrixSymbol('F_cg', 2, 1)
code = codegen(('evaluate', sympy.Eq(lhs_cg, rhs_cg)), language='c')
print(code[0][1])
```
which produced the following:
```c
/******************************************************************************
 *                      Code generated with sympy 1.1.1                       *
 *                                                                            *
 *              See http://www.sympy.org/ for more information.               *
 *                                                                            *
 *                       This file is part of 'project'                       *
 ******************************************************************************/
#include "evaluate.h"
#include <math.h>

void evaluate(double *endog_m, double *exog_m, double *F_cg) {

   F_cg[0] = -(pow(endog_m[0], exog_m[1]) + exog_m[0])*endog_m[1] + exp(-exp(-endog_m[0] - endog_m[1]));
   F_cg[1] = sin(endog_m[0])*endog_m[1] + cos(endog_m[1])*endog_m[0] - exog_m[2];

}
```
I was very happy that this worked - I had trouble trying to figure out how to pass in array arguments.
Now, to create the C function:
```python
aw_cg = autowrap(sympy.Eq(lhs_cg, rhs_cg), language='C99', backend='cython',
                 tempdir='cython/', args=[endog_matrix, exog_matrix])
```
For this function, we need to be a bit more precise with how we declare our data:
```python
x_cg_d = np.array([2,2],ndmin=2,dtype='double')
z_cg_d = np.array([1,2,.5],ndmin=2,dtype='double')

aw_cg(x_cg_d, z_cg_d)
array([[-9.01814893],
       [ 0.48630118]])
```
We reproduce the results from the `lambdify` function we created earlier.
Unfortunately, I can't pass this function into `fsolve`:
```python
cg_results = fsolve(aw_cg, x0=x_cg_d, args=(z_cg_d), full_output=True)
...
ValueError: Buffer has wrong number of dimensions (expected 2, got 1)
```
After some digging, I found that the `fsolve` function requires the data passed into it to be in one-dimensional NumPy arrays, but the C function produced by `autowrap` requires data in a two-dimensional format.  How difficult would it be to allow for one-dimensional `MatrixSymbol` objects?  Would this conflict with how the C code is generated with `autowrap`?

I'm going to see what I could do to make this work, but any help or suggestions are greatly appreciated.  If this is feasible with the `lambdify` function, it should also work with the C code generated by `autowrap`.

**Comment by moorepants** [comment]
I suggest that you wrap the function generated with something that reshapes the arrays.

```python
f = autowrap(...)
f2 = lambda *args: f(*args).squeeze()
fsolve(f2, x0)
```

Also you may want to use ufuncity instead of autowrap because it creates humpy ufuncs by default which follow all numpy broadcasting rules.

**Comment by j-m-t** [comment]
Thanks @bjodah and @moorepants for your prompt responses.

@moorepants, I followed your suggestion and was able to pass the `autowrap` function to `fsolve` with a slightly modified wrapper function:

```python
def aw_cg2(x0, args):
    x0_1 = np.reshape(x0, (2, 1))
    args_1 = np.reshape(args, (3, 1))
    return aw_cg(x0_1, args_1).squeeze()
cg_results = fsolve(aw_cg2, x0=x_cg_d, args=(z_cg_d), full_output=True)

cg_results[0]
array([ 0.35324662,  0.60608174])
```
The reshape commands were necessary, since `fsolve` wants both the input and output in one-dimensional arrays.  It isn't the prettiest solution, I'll admit, but it works, and it has given a roughly 35 percent speed improvement as-is.  Thanks for the tip!

@bjodah, I will go through the 2017 tutorial.  I've also forked the repo - I will tinker with the code to see if I could allow for easier connections between `autowrap` code and SciPy functions.  Thanks!

**Comment by moorepants** [comment]
Note that we probably won't design autowrap or similar functions to generate code tailored for specific scipy functions (or other packages) due to lack of consistency and standards on IO to various functions. But we could provide some options in autowrap so that the IO of the functions are set by the user when calling autowrap, as @bjodah suggests.
