### ISSUE TITLE
Latex of ConditionSet gives 'FiniteSet' object has no attribute 'as_expr'

### ISSUE THREAD

**Issue by JMSS-Unknown** [sympy/sympy#15353]
Solving
`sol = nonlinsolve([(sin(a*x)),cos(a*x)],[x,a])`
gives
`ConditionSet((x, a), {sin(a*x), cos(a*x)}, Complexes(Reals x Reals, False))`
calling
`latex(sol)`
outputs
`AttributeError: 'FiniteSet' object has no attribute 'as_expr'`
with both versions 1.3 and 1.4.dev

**Comment by JMSS-Unknown** [comment]
Looking back at this, the set of equations should have no solutions. Albeit, I guess it should still be able to print.
`pprint` gives `{(x, a) | (x, a) in S.Complexes and {sin(a*x), cos(a*x)}}`
so should `latex` give something along the lines of
`\left\{\left(x, a\right) \mid \left(x, a\right) \in \mathbb{C} \wedge \left\{\sin{\left (a x \right )}, \cos{\left (a x \right )}\right\} \right\}`?

**Comment by oscargus** [comment]
How would 
![image](https://user-images.githubusercontent.com/8114497/52733030-f52be900-2fc1-11e9-9f38-75fef2d26adc.png)
do?

`\left\{\left( x, \  a\right) \mid \left( x, \  a\right) \in \mathbb{C} \wedge \left\{\sin{\left(a x \right)}, \cos{\left(a x \right)}\right\} \right\}` so I realize that it is exactly the same as you requested. In a PR soon near you.
