### ISSUE TITLE
Solveset throws PolificationError when x cancels out

### ISSUE THREAD

**Issue by JMSS-Unknown** [sympy/sympy#15351]
Trying to solve
`solveset((2*x-2)/(1+x)-(2*x)/(2+x))`
gives
`sympy.polys.polyerrors.PolificationFailed: can't construct a polynomial from -2*x*(x + 1) + 2*(x - 1)*(x + 2)`.
The actual equation should have no solutions.

I haven't yet looked into how that function works but I suspect that the issues has something to do with the fact that
`>>> expand(-2*x*(x + 1) + 2*(x - 1)*(x + 2))`
`-4`
and trying to call `poly_from_expr(expr)` when the expr is a whole number throws a PolyficationError.

This was tested with both Sympy version 1.3 and 1.4.dev

**Comment by llucifer97** [comment]
hi @JMSS-Unknown  I am taking up this issue.

**Comment by JMSS-Unknown** [comment]
@llucifer97 Are you still working on this issue? If not, I may have a look myself.

**Comment by llucifer97** [comment]
@JMSS-Unknow go ahead

**Comment by czgdp1807** [comment]
```python
>>> solveset((2*x-2)/(1+x)-(2*x)/(2+x))
∅
```
In the latest master the issue has been fixed. I am closing this for now. However, if there is a need to re-open this, please let us know. Thanks for contributions.
