### ISSUE TITLE
Solveset does not find solution when using Eq with stats

### ISSUE THREAD

**Issue by JMSS-Unknown** [sympy/sympy#15352]
`solveset(Eq(sympy.stats.P(sympy.stats.Normal(Dummy(),0,1)>0.2),Symbol("x")))`
The solution should just be `sympy.stats.P(sympy.stats.Normal(sympy.Dummy(),0,1)>0.2)`
which is
`{-erf(0.1*sqrt(2))/2 + erf(inf*sqrt(2))/2}`
but the actual output is
`EmptySet()`

When the above is rewritten without Eq
`>>> solveset(sympy.stats.P(sympy.stats.Normal(Dummy(),0,1)>0.2)-Symbol("x"))`
`{-erf(0.1*sqrt(2))/2 + erf(inf*sqrt(2))/2}`
which is the correct solution.

This was tested with Sympy versions 1.3 and 1.4.dev

**Comment by Yathartha22** [comment]
It seems the problem is because of the [trimming condition](https://github.com/sympy/sympy/blob/65be583547a8ff73e00db2ec71d5cab31943be2c/sympy/solvers/solveset.py#L915) placed within `_solveset` after [`2793397`](https://github.com/sympy/sympy/pull/14253/commits/2793397f5942b761abb70ab385f01c7c8b2d9050) was made.
I guess all the modifications to the equation must be done before sending it to `_solveset`.

CC @smichr

**Comment by JMSS-Unknown** [comment]
It seems to work if 0.2 is replaced with a rational

**Comment by JMSS-Unknown** [comment]
Also, I'm not sure if this is related to what @Yathartha22 stated about the trimming condition, but it seems that it is caused as there is a float inf being multiplied by a sympy sqrt and it does not simplify
```python
>>> solveset(Eq(erf(oo*sqrt(2)), Symbol("x")))
{1}
>>> solveset(Eq(erf(float("inf")*sqrt(2)), Symbol("x")))
EmptySet()

>>> oo*sqrt(2)
oo
>>> float("inf")*sqrt(2)
inf*sqrt(2)
```

As the 0.2 within
`solveset(Eq(sympy.stats.P(sympy.stats.Normal(Dummy(),0,1)>0.2),Symbol("x")))`
is not a rational, the simplified expression contains an `inf` leading to the issue

```python
>>> Eq(sympy.stats.P(sympy.stats.Normal(Dummy(),0,1)>0.2),Symbol("x"))
Eq(-erf(0.1*sqrt(2))/2 + erf(inf*sqrt(2))/2, x)
```

**Comment by JMSS-Unknown** [comment]
Not sure if this is related but
`solveset(Eq(oo, Symbol("x")))`
returns `EmptySet()` as opposed to `oo`

**Comment by Yathartha22** [comment]
> ..but it seems that it is caused as there is a float inf being multiplied by a sympy sqrt and it does not simplify

Ohk so as I see this problem, the result is unevaluated because SymPy does not takes `inf` into account when multiplication operation is performed (because it has `oo` instead). The result is as per SymPy's behaviour (does not approximates).

I guess we need @jksuom 's and @asmeurer 's points of view on this.

**Comment by asmeurer** [comment]
There was some discussion about replacing `Float('inf')` with `oo`. See https://github.com/sympy/sympy/issues/6965. I don't know if we ever decided if we should do it or not. IMHO we should, same as we did with nan, but there may be downsides to it I'm not aware of.

**Comment by jksuom** [comment]
> same as we did with nan

I agree. `_mpf_inf` and `_mpf_ninf` could be added to [special cases](https://github.com/sympy/sympy/blob/master/sympy/core/numbers.py#L1053) in `Float.__new__`. Something else could be changed as well, for instance, [these statements](https://github.com/sympy/sympy/blob/master/sympy/core/numbers.py#L955-L958).

**Comment by asmeurer** [comment]
I don't know how many places in the code look for or expect float inf, but we could keep compatibility by making oo and -oo instances of Float with the proper `_mpf_`.

**Comment by Yathartha22** [comment]
> but we could keep compatibility by making oo and -oo instances of Float with the proper `_mpf_`.

You mean `oo` and `-oo` should inherit `Float`? Probably I didn't get the point in doing so.

Also I was trying an example after applying changes in `Float` class

```python
>>> z = Normal('z', 0, 1)
>>> P(z > 0.2)
-erf(0.1*sqrt(2))/2 + erf(inf*sqrt(2))/2
```
and I couldn't figure out why `inf*sqrt(2)` doesn't simplifies and how `inf` gets here.
I will look in greater detail on working of `P` but till then any headstart will be really helpful.

**Comment by smichr** [comment]
In current master,
```python
>>> solveset(Eq(P(Normal(Dummy(),0,1)>0.2),Symbol("x")))
{0.297508312574009*sqrt(2)}
>>> solveset(Eq(P(Normal(Dummy(),0,1)>2/S(10)),Symbol("x")))
{sqrt(2)*(-sqrt(2)*sqrt(pi)*erf(sqrt(2)/10) + sqrt(2)*sqrt(pi))/(4*sqrt(pi))}
```
