### ISSUE TITLE
Contribution in polys/domains/domain.py

### ISSUE THREAD

**Issue by neeraj1909** [sympy/sympy#15363]
There are many methods in class Domain which are still in the phase of NotImplementedError.
I want to contribute in some not implemented methods.
![not_implemented_error](https://user-images.githubusercontent.com/20766288/46659142-fe4f1880-cbd1-11e8-8546-e442cb16e1ea.png)

**Comment by neeraj1909** [comment]
Does there anything still to implemented in SymPy.

I am an undergraduate student and have one contribution in open-source.
I want to contribute in SymPy.

**Comment by jksuom** [comment]
There is no shortage of not-yet-implemented features in SymPy. Many of those can be found by running `git grep TODO` in SymPy's root directory (git version). More can be found in open issues.

**Comment by neeraj1909** [comment]
I found many features which are yet to be implemented.
I have learnt how to contribute in open-source.
Looking forward for GSOC 2019
