### ISSUE TITLE
Functions don't respond to name

### ISSUE THREAD

**Issue by nathanielvirgo** [sympy/sympy#15360]
Symbols have a 'name' attribute, but functions don't:

```
>>> import sympy as sy
>>> x = sy.Symbol('x')
>>> x.name
'x'
>>> f = sy.Function('f')
>>> f.name
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: type object 'f' has no attribute 'name'
>>> f = sy.sin
>>> f.name
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: type object 'sin' has no attribute 'name'
```

From reading the source code of the printing system, I discovered that I can get the name of a function using `f.__name__`, but this is rather unexpected from a user point of view, and it would be helpful if either this could be documented, or if functions would respond to `.name` instead.

**Comment by czgdp1807** [comment]
I think I can work on it if it has not been solved yet.

**Comment by czgdp1807** [comment]
I have created a PR[https://github.com/sympy/sympy/pull/15460]. Please see if it solves your issue.
