### ISSUE TITLE
Convert all docstrings to the numpydoc format

### ISSUE THREAD

**Issue by moorepants** [sympy/sympy#15370]
Our docstrings do not use a consistent format. Most scientific Python packages use the numpydoc format (which sphinx supports with either the napoleon or numpydoc extensions). A fair amount of SymPy documentation does use this format and there is no other obvious common format present. There is discussion on this topic in #12710, #5987, and #4008. 

This issue can be a meta issue listing all files in SymPy that have docstrings that need to be converted to the consistent NumPyDoc format.

Here is SymPy's guide to writing documentation:

https://github.com/sympy/sympy/wiki/Writing-documentation

And the guide for the NumPyDoc format is below:

https://numpydoc.readthedocs.io/en/latest/format.html

Some tips (feel free to add):

- Every public method or function and the `__init__` method of public classes should have at least a "Parameters" and "Returns" section except for simple single input single output functions where the first line of the docstring may be sufficient. A "Raises" section is also quite useful as a minimum.
- Docstrings should be readable in both the terminal (plain text ascii/unicode) and readable as rendered HTML and PDF (via LaTeX).
- Ideally every docstring has and example section with one or more examples of use.
- Keep the first part of the docstring (above Parameters) simple for quick reading. Move complex explanations into the "Notes" section.
- If you are new to SymPy, it is recommended to submit a single pull request for a module to ease review.

Please edit and add to the following checklist. Add bullets for each module that needs converting below:

- [ ] https://github.com/sympy/sympy/blob/master/sympy/plotting/plot.py
- [x] https://github.com/sympy/sympy/blob/master/sympy/algebras/quaternion.py (needs Params/Returns)
- [x] https://github.com/sympy/sympy/blob/master/sympy/calculus/singularities.py (needs Params/Returns)
- [ ] https://github.com/sympy/sympy/blob/master/sympy/calculus/util.py (needs Params/Returns)
- [ ] https://github.com/sympy/sympy/blob/master/sympy/combinatorics/coset_table.py
- [ ] https://github.com/sympy/sympy/blob/master/sympy/combinatorics/fp_groups.py
- [ ] https://docs.sympy.org/dev/modules/simplify/simplify.html
- [ ] https://docs.sympy.org/dev/modules/series/series.html
- [ ] https://docs.sympy.org/dev/modules/crypto.html
- [ ] https://docs.sympy.org/dev/modules/ntheory.html

**Comment by asmeurer** [comment]
One thing that annoys me about NumPy Doc (and which we've currently [got patched in our version](https://github.com/sympy/sympy/commit/dc751a87b131ad53de0970ccedf366eba59d74b3#diff-8d68c80fca3c9baace6067cf224540a7)) is that it forces the section headers to be one of the predefined types, so you can't write your own custom header names (for example, https://github.com/sympy/sympy/blob/fd0e200ab363ecb53d95e91260b5aea284c092cc/sympy/core/function.py#L2059). Does Napoleon handle this better?

**Comment by moorepants** [comment]
Doesn't seem like it (https://sphinxcontrib-napoleon.readthedocs.io/en/latest/index.html see list of supported headers). Maybe that should be proposed upstream.

**Comment by moorepants** [comment]
We could also move "Hints" as a sub heading under "Notes" in your example.

**Comment by asmeurer** [comment]
I looked at the code and I don't think it would be hard to implement in Napoleon. 

So someone wanting to work on this could:

- Upstream a change to Napoleon to allow arbitrary section headers (I think one just needs to add some kind of configuration flag, and then guard against it in places like [here](https://github.com/sphinx-contrib/napoleon/blob/83bf1963096490dd666f93ef5a9ed1cb229fc3ec/sphinxcontrib/napoleon/docstring.py#L964)). 

- Once it gets in, try to replace our vendered numpydoc with Napoleon. 

We can also add missing things to existing docstrings independently. Is there anything that we can't do with the current numpydoc without upgrading to Napoleon?

**Comment by moorepants** [comment]
As far as I know, there is no difference in Napolean and Numpydoc. Napoleon just implements numpydoc's standard and is included with sphinx. I didn't not know that we forked numpydoc and made any changes. Note that this issue title should only refer to the numpydoc standard (plus the small sympy change), not that we have to use the actual napoleon implementation. I think we can open another issue focused on dropping our forked numpydoc in place of an updated napoleon. This issue should just focus on getting docs into standard format.

**Comment by moorepants** [comment]
I opened https://github.com/sympy/sympy/issues/15375 to track the switch away from our fork.

**Comment by asmeurer** [comment]
I agree. I actually don't like that we have a fork because there are probably upstream fixes that we don't have. But I don't like not being able to format docstrings in a way that feels to me the most conducive to explaining things even more.

**Comment by moorepants** [comment]
> But I don't like not being able to format docstrings in a way that feels to me the most conducive to explaining things even more.

I'm fond of just sticking to the standard even though there might be small details that I don't like. Same goes for PEP8.

**Comment by AnimeshSinha1309** [comment]
Can I try to take this issue and attempt to fix the doc-strings. Anyone other than @GaurangTandon working on this issue?

**Comment by moorepants** [comment]
Yes, go for it. There are plenty to improve. Many people can work on it.

**Comment by ckant787** [comment]
Sir,can I take this issue.

**Comment by moorepants** [comment]
Go for it. Multiple people can work on this. Submit one file or one sub-package at a time.

**Comment by pradumangoyal** [comment]
If no one is working on https://github.com/sympy/sympy/blob/master/sympy/algebras/quaternion.py, I will like to work on this. Please guide me through any specifics, if involved here.

**Comment by pradumangoyal** [comment]
I thought the issues mentioned in the points above are unresolved but the issue I mentioned has already been resolved. I think (1st point)[https://github.com/sympy/sympy/blob/master/sympy/plotting/plot.py] is not worked upon. @asmeurer @moorepants can I work on this?

**Comment by mijo2** [comment]
For calculus/util.py, there are still some functions which don't have a ```Returns``` section. I will create a PR for the same.

**Comment by prateekguptaiiitk** [comment]
Can I try to take this issue to fix some of the doc-strings? @asmeurer @moorepants

**Comment by mijo2** [comment]
@moorepants In core, the function ```sympify``` doesn't follow the numpy format even though it is one of the most used functions, should I create a PR to update the docstring of the same?

**Comment by Kush1101** [comment]
If the issue is still open, I would like to work on it.

**Comment by asmeurer** [comment]
I think this issue should be superseded by #19591. There is a lot of work to do there, but if you want to work on it, please let me and @Soumi7 know, as @Soumi7 will be working on this as part of GSoD.

**Comment by nashalex** [comment]
@asmeurer @Soumi7 i am working on fixing the docstrings in the simplify.py file.
