### ISSUE TITLE
disable replacement of expression in Derivative that introduces new symbols

### ISSUE THREAD

**Issue by smichr** [sympy/sympy#15386]
An assumption of the Derivative is that if a function is written as `f(x)` then it only depends on x. Replacement of `f(x)` with  `g(x,y)` will lead to inconsistent results depending on when the substitution takes place:
```
>>> (f(x)*g(y)).subs(f(x),x*y).diff(x,y).doit()
y*g(y).diff(y) + g(y)
>>> (f(x)*g(y)).diff(x,y).subs(f(x),x*y).doit()
y*g(y).diff(y)
```
Perhaps such substitution attempts should raise an error a suggested [here](https://github.com/sympy/sympy/issues/4719#issuecomment-427795376).

**Comment by FrackeR011** [comment]
@smichr  which case should raise an error first or second ?

**Comment by smichr** [comment]
Interesting question. Maybe neither but one should just be aware of the issue. Or else the first case (which would then take care of the second if the `_eval_subs` routine of Derivative is modified, too).
