### ISSUE TITLE
Avoid links to docs.sympy.org in the docs

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#15380]
Noticed at https://github.com/sympy/sympy/pull/15378/files#r224650857. There are several links in the docs to docs.sympy.org. These should be relative links.

We should also add some kind of check to the docs build that there are no links to docs.sympy.org so it is avoided in the future.

**Comment by TKO-berg** [comment]
What should be done? I am new to open-source and I couldn't understand the issue .

**Comment by asmeurer** [comment]
All the links to `docs.sympy.org` in the `doc/` directory need to be changed to use RST cross references.

**Comment by akshitt** [comment]
I could do this if it's not already fixed.

**Comment by asmeurer** [comment]
It hasn't been fixed yet.

**Comment by mohitacecode** [comment]
@asmeurer  what do you mean by  RST cross references ??

**Comment by asmeurer** [comment]
They should use relative links in RST. Take a look at how the existing links in the docs are done.

**Comment by Utkarsh1308** [comment]
Can I work on this issue?

**Comment by sameshl** [comment]
Is anyone working on this issue?I would like to work on this if no one is working on it.

**Comment by divyanshu132** [comment]
I'm taking this.

**Comment by divyanshu132** [comment]
Fixed in [#15941](https://github.com/sympy/sympy/pull/15941).
