### ISSUE TITLE
Sympy Latex Parser not working (?)

### ISSUE THREAD

**Issue by falematte** [sympy/sympy#15399]
If I try to use the sympy latex parser I got this error under Ubuntu (sympy installed by means of pip3):
![selection_250](https://user-images.githubusercontent.com/25055204/47086713-ccf5ce80-d209-11e8-9417-4067b6d8d950.jpg)

**Comment by sidhantnagpal** [comment]
The quotes do not seem to be ASCII. The usage could be `r"1 + a"`.

**Comment by falematte** [comment]
Thank you for the answer. My fault. It works like a charm. I think I copied it from the sympy page.

**Comment by Mohitbalwani26** [comment]
I would love to work on the issue so can you please guide me?

**Comment by sidhantnagpal** [comment]
The [docstring](https://github.com/sympy/sympy/blob/master/sympy/parsing/latex/__init__.py#L7-L24) for `parse_latex` should be fixed.
This will do it (correct the raw string notation, prevent the parameter description from being bold, and display the examples as a code block):
```
    r"""Converts the string ``s`` to a SymPy ``Expr``

    Parameters
    ==========

    s : str
        The LaTeX string to parse. In Python source containing LaTeX,
        *raw strings* (denoted with ``r"``, like this one) are preferred,
        as LaTeX makes liberal use of the ``\`` character, which would
        trigger escaping in normal Python strings.

    Examples
    ========

    >>> from sympy.parsing.latex import parse_latex  # doctest: +SKIP
    >>> expr = parse_latex(r"\frac {1 + \sqrt {\a}} {\b}")  # doctest: +SKIP
    >>> expr  # doctest: +SKIP
    (sqrt(a) + 1)/b
    >>> expr.evalf(4, subs=dict(a=5, b=2))  # doctest: +SKIP
    1.618
    """
```
