### ISSUE TITLE
collect() incorrect on fractional equations

### ISSUE THREAD

**Issue by qwanzaden** [sympy/sympy#15394]
Calling collect() on a equation with a fraction and more than one term does not collect the terms within the fraction. Below is a example of collect() working on a equation with a fraction, and then not working when a term is added to the equation.
```
>>> import sympy
>>> x, y = sympy.symbols('x y')
>>> equation = 1/(x*y + x)
>>> #correct output
>>> equation.collect(x)
1/(x*(y + 1))
>>> equation = 1 + 1/(x*y + x)
>>> #incorrect output, expected 1 + 1/(x*(y + 1))
>>> equation.collect(x)
1 + 1/(x*y + x)
>>> import platform; platform.python_version()
'3.6.5'
>>> sympy.__version__
'1.3'
```

**Comment by ADWright18** [comment]
Hello! (I'm new to contributing to open source). It seems that 1 + 1/(x*y + x) and 1/(x*y + x) are different objects and processed differently when collect is called. Hope this helps.
```
>>> import sympy
>>> x, y = sympy.symbols('x y')
>>> equation = 1/(x*y + x)
>>>
>>> equation.collect(x)
1/(x*(y + 1))
>>> type(equation)
<class 'sympy.core.power.Pow'>
>>>
>>> equation = 1 + 1/(x*y + x)
>>> equation.collect(x)
1 + 1/(x*y + x)
>>> type(equation)
<class 'sympy.core.add.Add'>
>>>
>>> import platform
>>> platform.python_version()
'3.6.5'
>>> sympy.__version__
'1.1.1'
```

**Comment by czgdp1807** [comment]
I would like to solve this issue if it hasn't been solved yet.

**Comment by qwanzaden** [comment]
The issue has not been solved yet, sans the workaround hinted at by @ADWright18, of splitting a equation into its individual components.
Thank you for looking into it.

**Comment by czgdp1807** [comment]
I have created a PR. Please see if it solves your issue. :-)
