### ISSUE TITLE
solve hangs on list of equations

### ISSUE THREAD

**Issue by oscarbenjamin** [sympy/sympy#15415]
While working on #15414 I found an intermittent case where `solve` hangs. I am not sure if this is the same as the intermittent problem but I'm reporting here a case that reliably hangs.

I'm finding that solve hangs when asked to solve a particular equation but only when that equation is given as a length-1 list of equations. This is fine:
```julia
In [6]: solve(Eq(y + 3*x**2/2, y + 3*x), y)
Out[6]: []
```

But this hangs:
```python
solve([Eq(y + 3*x**2/2, y + 3*x)], y)
```

**Comment by jksuom** [comment]
> But this hangs:

     solve([Eq(y + 3*x**2/2, y + 3*x)], y)

I have not been able to reproduce this on current master. Is is only seldom that it would hang?

**Comment by oscarbenjamin** [comment]
This hangs reliably for me on Linux with Python 3.6.2:

```console
$ git clone https://github.com/sympy/sympy.git
Cloning into 'sympy'...
remote: Enumerating objects: 236413, done.
remote: Total 236413 (delta 0), reused 0 (delta 0), pack-reused 236413
Receiving objects: 100% (236413/236413), 93.71 MiB | 2.81 MiB/s, done.
Resolving deltas: 100% (188572/188572), done.
$ cd sympy/
$ python
Python 3.6.2 (default, Aug 17 2017, 18:00:55) 
[GCC 4.6.3] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from sympy import *
>>> x, y = symbols('x y')
>>> solve([Eq(y + 3*x**2/2, y + 3*x)], y)
^CTraceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/space/enojb/current/sympy/test_install/sympy/sympy/solvers/solvers.py", line 1164, in solve
    solution = _solve_system(f, symbols, **flags)
  File "/space/enojb/current/sympy/test_install/sympy/sympy/solvers/solvers.py", line 1771, in _solve_system
    i, d = _invert(g, *symbols)
  File "/space/enojb/current/sympy/test_install/sympy/sympy/solvers/solvers.py", line 3036, in _invert
    rhs /= indep
  File "/space/enojb/current/sympy/test_install/sympy/sympy/core/decorators.py", line 91, in __sympifyit_wrapper
    return func(a, b)
  File "/space/enojb/current/sympy/test_install/sympy/sympy/core/decorators.py", line 125, in binary_op_wrapper
    if other._op_priority > self._op_priority:
KeyboardInterrupt
$ git status
# On branch master
nothing to commit (working directory clean)
$ git log
commit c8a6c129619e134652cb6de64ecfaacc6f733153
```

**Comment by oscarbenjamin** [comment]
Note that denesting the one-element list (as in the PR referenced above) will not solve the problem in general since it also can occur for a length-2 list:
```python
solve([Eq(y + 3*x**2/2, y + 3*x), Eq(x, 1)], y)
```
The bug is somewhere in the code that handles list of equations and is not unique to the 1-element case.

**Comment by jksuom** [comment]
The bug is in `_invert`:

    eq = sympify(eq)  # eq is the difference 3*x**2/2 - 3*x - y + y
    free = eq.free_symbols  # this is set([x, y]), which is wrong as eq is independent of the value of y
    if not symbols:
        symbols = free
    if not free & set(symbols):  # the intersection is non-empty, which is wrong
        return eq, S.Zero

    dointpow = bool(kwargs.get('integer_power', False))

    lhs = eq
    if eq.args:
        # make sure we are working with flat eq
        lhs = eq.func(*eq.args)  # lhs becomes 3*x**2/2 - 3*x with no y, but too late
    rhs = S.Zero

It looks like `eq` should be made flat before collecting its free symbols.

**Comment by smichr** [comment]
> should be made flat before collecting its free symbols

```diff
diff --git a/sympy/solvers/solvers.py b/sympy/solvers/solvers.py
index b7d66bb..6717b4c 100644
--- a/sympy/solvers/solvers.py
+++ b/sympy/solvers/solvers.py
@@ -2999,6 +2999,9 @@ def _invert(eq, *symbols, **kwargs):

     """
     eq = sympify(eq)
+    if eq.args:
+        # make sure we are working with flat eq
+        eq = eq.func(*eq.args)
     free = eq.free_symbols
     if not symbols:
         symbols = free
@@ -3008,9 +3011,6 @@ def _invert(eq, *symbols, **kwargs):
     dointpow = bool(kwargs.get('integer_power', False))

     lhs = eq
-    if eq.args:
-        # make sure we are working with flat eq
-        lhs = eq.func(*eq.args)
     rhs = S.Zero
     while True:
         was = lhs
```

**Comment by warnerjon12** [comment]
Yes, I have done this now
