### ISSUE TITLE
Inconsistent return types from solve

### ISSUE THREAD

**Issue by warnerjon12** [sympy/sympy#15420]
While working on issue #15415, I noticed that `_solve` and `_solve_system` give inconsistent return types. on the inputs `[x - 3]` and `x`, `_solve` gives `[3]` while `_solve_system` gives `{x: 3}`. According to the comments, it appears that `_solve_system` also sometimes gives a list of tuples rather than a dictionary. At the user level, we have `solve(x - 3, x)=[3]` while `solve([x - 3], x)={x: 3}`. Do we want wrapping in a list to change the return type or is this a bug? I am unsure how to proceed with #15415 unless I know what behavior is intended.

**Comment by smichr** [comment]
> Do we want wrapping in a list to change the return type

This is a known and documented behavior (see dosctring of solve). The keyword `dict` can be used to force the return type to always be a dictionary.
