### ISSUE TITLE
SymPy cannot compute the elliptic integral integrate(sqrt(1+cos(x)**2), x)

### ISSUE THREAD

**Issue by proy87** [sympy/sympy#15437]
integral of `sqrt(1+cos(x))**2` is non-elementary, but sympy gives another answer.

**Comment by ethankward** [comment]
What do you expect the result to be?

**Comment by proy87** [comment]
@ethankward , elliptic integral.

**Comment by ethankward** [comment]
Do you mean `sqrt(1+cos(x)**)`?

**Comment by proy87** [comment]
I mean `sqrt(1+cos(x)**2)`

**Comment by asmeurer** [comment]
Please include the full answer SymPy gives you when opening an issue. For me, `integrate(sqrt(1+cos(x)**2), x)` produces an unevaluated `Integral`, which is not incorrect (it just means SymPy cannot compute the integral).
