### ISSUE TITLE
Union does not work with Python set objects

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#15448]
```pytb
>>> Union({1}, {2})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "./sympy/sets/sets.py", line 1028, in __new__
    args = flatten(args)
  File "./sympy/sets/sets.py", line 1026, in flatten
    return sum(map(flatten, arg), [])
  File "./sympy/sets/sets.py", line 1026, in flatten
    return sum(map(flatten, arg), [])
  File "./sympy/sets/sets.py", line 1027, in flatten
    raise TypeError("Input must be Sets or iterables of Sets")
TypeError: Input must be Sets or iterables of Sets
```

There are probably other things in the sets module that don't work with Python sets either. Python sets should always be automatically converted to FiniteSet.

This is easy to fix, `Union` should call `_sympify` on its arguments.

**Comment by deepakkavoor** [comment]
I will take up this issue. I have just started contributing to sympy, so it might take a while.

**Comment by deepakkavoor** [comment]
@FrackeR011 Yes, I am

**Comment by kesarianubhav** [comment]
@FrackeR011  Are you still working on it ?

**Comment by FrackeR011** [comment]
No i am not . You should ask @deepakkavoor if he is .

**Comment by kesarianubhav** [comment]
@deepakkavoor  I want to work on this issue .  Are you working on it ?

**Comment by deepakkavoor** [comment]
@kesarianubhav alright go ahead

**Comment by kesarianubhav** [comment]
@m-agboola , I'm just started to work on it !!.

**Comment by kesarianubhav** [comment]
@m-agboola  , I'm working on it .

**Comment by jmig5776** [comment]
I would like to work on this issue if @kesarianubhav  are not working on it.

**Comment by vishal-vardhan** [comment]
is there anyone working on this?

**Comment by vishal-vardhan** [comment]
@asmeurer can i work on this

**Comment by vishal-vardhan** [comment]
@asmeurer please review this PR #15764

**Comment by vishal-vardhan** [comment]
@asmeurer shall i change the sets.py so that every function works with python sets.

**Comment by vishal-vardhan** [comment]
I've changed the Union class already ,if i may i will change every function next so that they work with python sets.

**Comment by supreet11agrawal** [comment]
@asmeurer . I saw https://github.com/sympy/sympy/pull/15479 which you mentioned above and tried to reproduce this result.
It is still giving an error while using `Union({1},{2})` or `Union({1,2},{3,4})` but not in case of `Union(Finiteset(1,2),Finiteset(3,4))`. Is it allright or still needs to be fixed?

**Comment by sannanansari** [comment]
Is this issue is open? I would like to contribute to this issue.

**Comment by oscargus** [comment]
@sannanansari  There are two ongoing PRs, #15479 and #15764. So probably better to work on something else.

**Comment by ritik-gupta** [comment]
issue solved? If not then i would like to contribute to this issue.
