### ISSUE TITLE
_sympify (set) gives FiniteSet where it should not

### ISSUE THREAD

**Issue by souravgl0** [sympy/sympy#15478]
>>> type(_sympify({Interval(0,1),Interval(2,3)}))
    <class 'sympy.sets.sets.FiniteSet'>

That is not a valid FiniteSet. In this case, It should just return the python set.
I came across this while working on #15448
Calling _sympify fails for the given example

**Comment by asmeurer** [comment]
I don't see the issue here. A set of sets is perfectly valid.

**Comment by souravgl0** [comment]
You are right. This is expected behavior. I am closing the issue.
