### ISSUE TITLE
2D integral of Gaussian times cosine hangs

### ISSUE THREAD

**Issue by mardukbp** [sympy/sympy#15486]
In isympy 1.3 the following integral hangs:

`integrate(integrate(exp(-x**2*n**2 - y**2*m**2 - x**2 - y**2)*cos(m*x - n*y), (x,-oo,oo)), (y,-oo,oo))`

Both Maxima and FriCAS calculate it in milliseconds, without any assumptions like integer, real, etc.

**Comment by normalhuman** [comment]
At least m, n should be declared positive, otherwise the integral need not converge (by default, m and n could even be complex). The best I could get is the following, with `.rewrite(exp)` applied to the integrand.
```
>>> m, n = symbols('m n', positive=True)
>>> x, y = symbols('x y')
>>> integrate((exp(-x**2*n**2 - y**2*m**2 - x**2 - y**2)*cos(m*x - n*y)).rewrite(exp), (x,-oo,oo), (y,-oo,oo)).simplify()
pi*((erf(I*n/(2*sqrt(m**2 + 1))) + 1)*erf(I*m/(2*sqrt(n**2 + 1))) + (erf(I*n/(2*sqrt(m**2 + 1))) + 1)*erfc(I*m/(2*sqrt(n**2 + 1))) + (erf(I*m/(2*sqrt(n**2 + 1))) + erfc(I*m/(2*sqrt(n**2 + 1))) + 1)*erfc(I*n/(2*sqrt(m**2 + 1))) + erf(I*n/(2*sqrt(m**2 + 1))) + 1)*exp(-(m**2*(m**2 + 1) + n**2*(n**2 + 1))/(4*(m**2 + 1)*(n**2 + 1)))/(4*sqrt(m**2 + 1)*sqrt(n**2 + 1))
```

**Comment by mardukbp** [comment]
Aha! I did not know about `rewrite(exp)`. Thanks!

In isympy m and n are integers. I do not see why the sign would have any influence on the result.

I noticed that `factor(integrate((exp(-x**2*n**2 - y**2*m**2 - x**2 - y**2)*cos(m*x - n*y)).rewrite(exp), (x,-oo,oo), (y,-oo,oo)))` yields

![integral](https://user-images.githubusercontent.com/1140106/48355185-c2591880-e693-11e8-995c-b8bed1362cd0.png)

which shows that SymPy only needs to know that `erf(x) + erfc(x) = 1` in order to yield the result.

How can one teach SymPy that relationship?

**Comment by jksuom** [comment]
> How can one teach SymPy that relationship?

SymPy knows the relationship but does not apply it automatically. `_.rewrite(erf)` can be used to yield a simplified result.

**Comment by mardukbp** [comment]
Great! Thanks!
