### ISSUE TITLE
NumPy printers return deprecation warning

### ISSUE THREAD

**Issue by Upabjojr** [sympy/sympy#15482]
```python
In [1]: from sympy import *

In [2]: M = MatrixSymbol("M", 3, 3)
   ...: N = MatrixSymbol("N", 3, 3)

In [3]: expr = M*N

In [4]: f = lambdify((M, N), expr, "numpy")

In [5]: f(eye(3), eye(3))
/home/francesco/workspace/sympy/sympy/matrices/matrices.py:2639: SymPyDeprecationWarning: 

Dot product of non row/column vectors has been deprecated since SymPy
1.2. Use * to take matrix products instead. See
https://github.com/sympy/sympy/issues/13815 for more info.

  useinstead="* to take matrix products").warn()
Out[5]: [1, 0, 0, 0, 1, 0, 0, 0, 1]
```
The result is wrong, it should be a 3x3 matrix.

**Comment by RituRajSingh878** [comment]
I'd like to work on this.

**Comment by asmeurer** [comment]
In general you shouldn't expect a meaningful result if you pass a SymPy type to a NumPy lambdified function.

**Comment by asmeurer** [comment]
In particular, SymPy's `dot` has different semantics than NumPy's. For NumPy it means matrix multiplication but for SymPy it is only a vector dot product (it used to treat matrices as folded vectors, but this behavior is deprecated).

**Comment by RituRajSingh878** [comment]
@asmeurer thanks for your clarification.
