### ISSUE TITLE
Potential hang in monomials during integration

### ISSUE THREAD

**Issue by sirnicolaf** [sympy/sympy#15498]
In the example given below, the `intermonomials` function is called from the `heurisch` function of the integration process. The problem I encounter is that before calling `internomomials`, the script subs some expression with polynomials. The expressions look something like this, `(27000.0 - 6902.92767267848*exp(-1.66666666666667*s) - 24100.2086229868*exp(-s/120))*exp(k10*s)` and the mapping it uses to sub over this example would be, `[(exp(k10*s), _x1), (exp(-s/120), _x0), (exp(-1.66666666666667*s), _x3), (s, _x2)] `. As you can see, the third exponential is exactly the second one at the 200th power. So the subbed expression would come out as, `_x1*(-6902.92767267848*_x0**200 - 24100.2086229868*_x0 + 27000.0)`, which isn't false, but it causes the `intermonomials` to go on for hours (maybe days, I have never seen it end) in the `for variable in item:` loop at line 85.
```
import sympy as sy

Z0 = sy.Function('Z0')
Z1 = sy.Function('Z1')
k01, k10, t, s= sy.symbols('k01 k10 t s', real=True, positive=True)

m = sy.Matrix([[sy.exp(-k10*t)]])

[a, b, c, d, e, f, g] = [100, 0.5, 0.83, 50, 0.6, 2, 120]
AIF_btf = a*(d*e*(1-sy.exp(-(t-b)/e))+f*g*(1-sy.exp(-(t-b)/g)))
AIF_atf = a*(d*e*sy.exp(-(t-b)/e)*(sy.exp((c-b)/e)-1)+f*g*sy.exp(-(t-b)/g)*(sy.exp((c-b)/g)-1))
AIF_sym = sy.Piecewise((0, t < b), (AIF_btf, sy.And(b<=t, t<c)), (AIF_atf, c<=t))

aif_eq = sy.Eq(Z0(t), AIF_sym)
c_vec  = sy.Matrix([[Z1(t)]])
f_vec  = sy.Matrix([[k01*Z0(t)]])

integrand = m*(m.subs(t, s)**-1)*f_vec.subs(aif_eq.lhs, aif_eq.rhs).subs(t, s)
solution  = sy.integrate(integrand[0], (s, 0, t))
```
This behavior can be "hotfixed" in the `_subterms` function of `heurisch` by replacing the `return expr.subs(mapping)` of line 460 by `return expr.xreplace(dict(mapping))` but I know this probably would be far from an ideal fix. Maybe this doesn't actually need to be fixed and I'm just doing something wrong, too.

Now here is the interesting part, I first talked about this issue and #15494 in the gitter chat thinking they weren't related at all. But for some reason I don't understand, when applying the fix I just talked about, the behavior from #15494 disappeared. Also, since @normalhuman talked about how SymPy prefers working with known rationals, I tried replacing `[a, b, c, d, e, f, g] = [100, 0.5, 0.83, 50, 0.6, 2, 120]` with `[a, b, c, d, e, f, g] = [100, sy.Rational('0.5'), 0.83, 50, sy.Rational('0.6'), 2, 120]` and got NaN as the result of the integral. I then needed to use one of the fixes I proposed in #15494 to get the good result, but it all worked out in the end. Seeing as both issues seem related only in my code, I'm assuming my script is the source of the problem, but I've been searching for a while without success.

**Comment by jksuom** [comment]
> [a, b, c, d, e, f, g] = [100, sy.Rational('0.5'), 0.83, 50, sy.Rational('0.6'), 2, 120]

If there is a single floating point number `0.83`, then all numbers are considered inexact. That will be much slower than computing with exact numbers as the arithmetic laws are not valid, and therefore coefficients are treated as expressions in `heurisch`.

**Comment by jksuom** [comment]
Actually, it seems that `nan` is created by `manualintegrate` as a result of division by zero. In principle, `heurisch` should be able to compute the integral but it does not succeed in this case, probably because of some unlucky choices in its cache. It looks like following patch would fix `manualintegrate`:
```
--- a/sympy/integrals/manualintegrate.py
+++ b/sympy/integrals/manualintegrate.py
@@ -130,6 +130,8 @@ def find_substitutions(integrand, symbol, u_var):
     results = []
 
     def test_subterm(u, u_diff):
+        if u_diff == 0:
+            return False
         substituted = integrand / u_diff
         if symbol not in substituted.free_symbols:
             # replaced everything already
```

**Comment by sirnicolaf** [comment]
> Actually, it seems that `nan` is created by `manualintegrate` as a result of division by zero.

Yes, I referenced this issue already in #15494. I had proposed two initial fixes, one being quite close to what you just wrote. I think I like your format better though.
