### ISSUE TITLE
Integrate returns wrong result (NaN)

### ISSUE THREAD

**Issue by sirnicolaf** [sympy/sympy#15494]
The following example will return NaN as the result of the integral when it is easy to prove (by hand or with wolfram) that the result is actually 

> 2*exp(3*s/2)/3 + exp(2*s)/2 - 0.769230769230769*exp(2.6*s)

```
import sympy as sy

Z0 = sy.Function('Z0')
Z1 = sy.Function('Z1')

k01, k10, t, s= sy.symbols('k01 k10 t s', real=True, positive=True)


integrand = (sy.exp(s/2)-2*sy.exp(1.6*s)+sy.exp(s))*sy.exp(s)
solution  = sy.integrate(integrand, s)
```

From what I found, the problem comes from _manualintegrate.py_ at line 133 in the _test_subterm_ function. In this function, the integrand is divided by the derivative of a subterm, but at one point, this subterm is a constant, which creates a division by 0. The result of this division should be NaN, undefined or infinity, but since it is not evaluated, it becomes the integrand multiplied by the complex infinity. This becomes problematic at line 135. Since the result of the division hasn't actually been evaluated, it still contains the _symbol_ and so the result fails the check in the _if symbol not in substituted.free_symbols:_. The _cancel()_ at line 139 then forces the result to become NaN but it seems like it happens too late and the NaN constant will still be used in the rules for the integral.

So, here are two of my proposed fixes, either move the _substituted = substituted.subs(u, u_var).cancel()_ from line 139 to line 134 so that it happens before the _if symbol not in substituted.free_symbols:_ check, or add a couple of lines (between 133 and 135) like 
```
from sympy import nan
if u_diff == 0 :
    substituted = nan
```
so that the rule containing the NaN constant isn't added/used. I think the first fix makes a lot more sense, but let me know what you guys think. If it's all good with you, should I make a PR with it and add something in the test file?

Here is an image of the part of _manualintegrate.py_ where the problem seems to occur.
![image](https://user-images.githubusercontent.com/43586954/48494996-103d6000-e7fd-11e8-92a9-5a2a38604f11.png)

**Comment by normalhuman** [comment]
One should consider the reason why `if symbol not in substituted.free_symbols` has different outcomes on lines 135 and 139.  If this condition is met on line 135, the substitution is **rejected**. If it is met on line 139, after subs-cancel, then the substitution is **accepted**. So, moving subs-cancel before the first `if` would be a change to the algorithm. 

By the way, SymPy strongly prefers having numbers like `1.6` as rationals. 
```
integrand = (sy.exp(s/2)-2*sy.exp(sy.Rational('1.6')*s)+sy.exp(s))*sy.exp(s)
```
integrates to `-10*exp(13*s/5)/13 + 2*exp(3*s/2)/3 + exp(2*s)/2`.

**Comment by sirnicolaf** [comment]
Yep, you're totally right. Also, I found out while trying to fix another weird behavior that the NaN return could also be "fixed" by changing the way `_substitutions` subs terms in `heurisch`. I have to admit I don't actually know what's exactly going on and what is causing those behaviors at the moment. For the rational part, my integrands generated while solving a non homogeneous system of first order differential equations so I wouldn't exactly know how to pass the terms as rationals for those that are. I think I'll be opening the other issue soon about the "apparent hang" in monomials while giving a generated integrand instead of a written one. Either way, should we try and delve into this present issue to figure out if there is a way to make the code fail proof?

**Comment by RituRajSingh878** [comment]
@sirnicolaf  are you still working in this issue.

**Comment by jksuom** [comment]
I would preferably try to prevent `manualintegrate` from returning `nan` by something like this:
```
--- a/sympy/integrals/manualintegrate.py
+++ b/sympy/integrals/manualintegrate.py
@@ -130,6 +130,8 @@ def find_substitutions(integrand, symbol, u_var):
     results = []
 
     def test_subterm(u, u_diff):
+        if u_diff == 0:
+            return False
         substituted = integrand / u_diff
         if symbol not in substituted.free_symbols:
```
