### ISSUE TITLE
solve misbehaves when variable is already initialized with some value

### ISSUE THREAD

**Issue by pulkit6559** [sympy/sympy#15501]
While working on issue #15492 i noticed another issue with solve function, although i'm not sure if its a bug or it was intended so.
When solving for a variable (say z) which was already initialized with some value, the solve function returns an empty list.

code to reproduce : 

```
>>> z,y = symbols("z,y")
>>> y = 15
>>> z = 12
>>> solve([z+y-35],z,dict=True)
```

output : 
`[ ]`

**Comment by pulkit6559** [comment]
Ideally, what i think should happen is, the variable z should be overwritten with the new value as a user might want to reuse it.

**Comment by sidhantnagpal** [comment]
y, z are no longer symbols as you redefine them as integers.

As for symbolic y and z, the correct result `[{z: -y + 35}]` is returned.
Are you looking for `.subs()` functionality for performing substitutions?

**Comment by smichr** [comment]
This is expected. Python only knows that z is now 12 and y 15 so you are asking for `solve([12+15-35])`. This is a gotcha discussed [here]( https://docs.sympy.org/latest/tutorial/gotchas.html).

**Comment by smichr** [comment]
closing, but feel free to continue discussion; it will appear under closed issues
