### ISSUE TITLE
dsolve: should check that roots give the expected number of roots

### ISSUE THREAD

**Issue by cbm755** [sympy/sympy#15527]
A recent change in #15408 means `dsolve` uses `roots` on the the characteristic polynomial of linear DEs.

Quoting help of `roots`:

> Only roots expressible via radicals will be returned.  To get
> a complete set of roots use RootOf class or numerical methods
> instead. By default cubic and quartic formulas are used in
> the algorithm.

So that's not good.

Its probably possible to cook-up an ODE where the current code fails, something where the charpoly is something like:

```py
>>> roots((x-5)*(x**5 - x**4 + 10), multiple=True)
[5]
```

- - - - -

Perhaps we should check that roots gave `n` roots and fall back on `RootOf` when it does not?  (Instead of just falling back when `roots` is empty.  But is that enough?  I'm out of my league here w.r.t. Polynomials; someone else should double-check that this fix is appropriate....

**Comment by cbm755** [comment]
CC @oscarbenjamin @jksuom

**Comment by cbm755** [comment]
There is also `Poly.all_roots` but I think it suffers from #15413 or something similar once you put `sqrt(2)` in a coefficient.

**Comment by oscarbenjamin** [comment]
Would rootof find the rational roots in those cases?

I think you're right but I have also question the validity of the rootof solutions anyway. Do they take into account multiple roots?

(I'm away from a computer for a few days)

**Comment by cbm755** [comment]
Also, there are no 'rational roots' in 'those cases'...

**Comment by oscarbenjamin** [comment]
`rootof` (lower case) tries to find the root and returns `RootOf` otherwise. It fails for irrational coefficients though. Hence #15408

The example you show above has rational root 5. Ideally we'd divide by `x-5` and then return `RootOf`s for the unsolvable factor.

**Comment by oscarbenjamin** [comment]
Actually it looks as if `rootof` does find the rational root as I suggested:
```julia
In [1]: p = ((x-5)*(x**5 - x**4 + 10)).expand()                                                                                                               

In [2]: p                                                                                                                                                     
Out[2]: 
 6      5      4            
x  - 6⋅x  + 5⋅x  + 10⋅x - 50

In [3]: [rootof(p, n) for n in range(6)]                                                                                                                      
Out[3]: 
⎡       ⎛ 5    4        ⎞            ⎛ 5    4        ⎞         ⎛ 5    4        ⎞         ⎛ 5    4        ⎞         ⎛ 5    4        ⎞⎤
⎣CRootOf⎝x  - x  + 10, 0⎠, 5, CRootOf⎝x  - x  + 10, 1⎠, CRootOf⎝x  - x  + 10, 2⎠, CRootOf⎝x  - x  + 10, 3⎠, CRootOf⎝x  - x  + 10, 4⎠⎦
```

So if `rootof` worked for irrational coefficients then it would be the best thing to use in this case. I don't understand the polynomial code well enough to know why it's hard to get that to work.

In the meantime I think you're right that checking to see if `roots` returns `n` roots is better than checking against an empty list. I'll send a PR.

**Comment by oscarbenjamin** [comment]
I've sent a PR #15550
