### ISSUE TITLE
Test data is not published to Azure Pipelines

### ISSUE THREAD

**Issue by divais** [sympy/sympy#15526]
Tests are running in the pipeline, but they aren't getting published to Azure Pipelines which provides excellent reporting capabilities that help you with:

- Easy analysis and troubleshooting for failed tests - the test reports show all relevant details (error message, stack trace, failing for how long, etc.) to make it easy to analyse failed tests.
- Timing analysis - Test duration information helps you figure out long running tests, so that you can improve test collateral to speed up the pipelines.
- Build-on-build trends/analytics help you get rich insights, detailed scenarios @ https://blogs.msdn.microsoft.com/devops/2018/10/25/test-analytics-in-azure-pipelines-is-now-at-your-fingertips/ 

![image](https://user-images.githubusercontent.com/17335060/48883742-3c815e00-ee47-11e8-9623-4041d63f5787.png)

The fix required is to use an XML reporter and update the YAML file to publish these test reports.

I am a Program Manager on the Azure Pipelines team and will be happy to raise a PR to address this.

**Comment by oscargus** [comment]
If you can provide a PR that will of course be much appreciated.

**Comment by oscargus** [comment]
However, note the discussion about possibly stop using Azure Pipelines: https://groups.google.com/forum/#!msg/sympy/jyYrYz8ys9o/p7IY4MCSAwAJ

Something I am missing is code coverage. I have not looked into it at all, but what support does Azure Pipelines have there. Is there something easy-to-use that is already built in?
