### ISSUE TITLE
A test, solve(d*(1+1/d)) is slow with a 5th degree polynomial d

### ISSUE THREAD

**Issue by normalhuman** [sympy/sympy#15532]
This test became slow recently (went from under 2 seconds to over 90 seconds on my machine), and occasionally times out. 

https://github.com/sympy/sympy/blob/27b9951fbf8715558efd038299a14554f35307d2/sympy/solvers/tests/test_solvers.py#L1775-L1776

Bisect points to #14348 which was a large project, and unfortunately some commits thwart bisect by raising an exception. 

> The first bad commit could be any of:
> 11c199557db1c5178024261c56fde81a19a5221e
> 6f8b22df68a83f3e7cca5107d1ce39042d718ff0
> a3701b21e9e5f89607f3a6c88f67336b5a7a905d
> 060df21fd3f5c5e5509863d74cf0941e7fa6ad32
> 7dc957c702af4b3690bc204dd3e65d0fdfcfd12c
> 15d1173a0b3118d0e569f4c2fc9d9cc0422947e3
> cc37e8cd1181e58978e803c7597b24b92d855402
> 18ac360ec20631b4db615a0cf8904c3b68dc616f
> bb8e32c964ef06cb6a5dc5a041244c589062bda2
> 1edecf7a64b2675fb3396e632c2efa1cf68ae5b5
> We cannot bisect more!

The slow part is checking the solutions, as  
```
solve(d*(1 + 1/d), check=False)
```
returns at once (with a wrong result, of course). However,  `solve(d*(1 + 1/d))` did return the correct answer in under 2 seconds previously, for example at 90554f11fb0c5f48bc939454fc9e9bdb07d2c1b8

**Comment by normalhuman** [comment]
This is a duplicate of #15340

**Comment by smichr** [comment]
closing as duplicate
