### ISSUE TITLE
test_tensor.py: test decorator runs tests during collection

### ISSUE THREAD

**Issue by oscarbenjamin** [sympy/sympy#15545]
I fond this while working through #15503 

Commit e320a34097dcc692002991b9680243fdb54055da introduces a decorator to `test_tensor.py`. The decorator is used to mark `test_` functions and suppress deprecation warnings from them. However it is not correctly implemented since it calls the `test_` function during collection rather than allowing the test-runner to call them.

The decorator is
```python
def filter_warnings_decorator(f):
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=SymPyDeprecationWarning)
        f()

...

@filter_warnings_decorator
def test_valued_tesnor_iter():
     ...
```
The decorator will call `f()` during import. Then `test_stuff` will be set to `None` since that's what the decorator returns. The test-runner then ignores it:
```console
$ bin/test sympy/tensor/tests/test_tensor.py -k test_valued_tensor_iter
==================== tests finished: 0 passed, in 3.37 seconds ======================
```

It should probably be something like (untested):
```python
def filter_warnings_decorator(f):
    @wraps(f)
    def wrapper():
        with warnings.catch_warnings():
            warnings.filterwarnings("ignore", category=SymPyDeprecationWarning)
            f()
    return wrapper
```

I would fix this as part of #15503 but I'm unsure of the purpose of this decorator since no warnings are emitted if I simply delete it.

Is it intended that warnings from the tested code will be raised in future? If so then I think it's best to remove the decorator for now and add code that tests for (rather than suppresses) the warnings when the code to emit the warnings is added.

**Comment by oscarbenjamin** [comment]
CC @Upabjojr

**Comment by Upabjojr** [comment]
Hi, thanks for reporting.

Yes, I probably made a mistake. Are you willing to fix it?

**Comment by oscarbenjamin** [comment]
The question is what is this code supposed to do? As I said it looks as if it should be suppressing warnings but there are no warnings if I just delete the decorator: the tests all pass and no warnings are raised.

Should there be warnings raised? Or should I just delete the decorator?

I don't see any point in fixing the decorator if it isn't actually doing anything.

**Comment by Upabjojr** [comment]
Well, there should be a deprecation warning on those things. So maybe there's another bug somewhere and the deprecation warning is not called.
