### ISSUE TITLE
Missing parentheses pretty printing MatMul and KroneckerProduct

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#15560]
It seems this case wasn't fixed with https://github.com/sympy/sympy/issues/15439

```py
>>> i, j = symbols('i j', integer=True)
>>> X = MatrixSymbol('X', 1, j*k)
>>> A1 = MatrixSymbol("A1", j, 1)
>>> A2 = MatrixSymbol("A2", k, 1)
>>> pprint(X*KroneckerProduct(A1, A2))
X⋅A₁ ⨂ A₂
```

The other way is parenthesized

```py
>>> B = MatrixSymbol('B', i, j)
>>> pprint(KroneckerProduct(B*A1, A2))
(B⋅A₁) ⨂ A₂
```

But there is no implied precedence between a matrix product and Kronecker product, so both ways should be parenthesized.

**Comment by OppenheimerAndTheMartians** [comment]
I'd like to fix this, I just forked the repo.

**Comment by asmeurer** [comment]
OK. A tip would be to look at how And/Or work. They also have the same precedence with respect to one another. 

```py
>>> pprint(And(x, Or(y, z)))
x ∧ (y ∨ z)
>>> pprint(Or(x, And(y, z)))
x ∨ (y ∧ z)
```

**Comment by rationa-kunal** [comment]
I would like to work on this issue as well !!
thanks
