### ISSUE TITLE
pretty() sometimes does not pretty print

### ISSUE THREAD

**Issue by markus2330** [sympy/sympy#15573]
Given the file bug2.py with the content:

```python
from sympy import *
from sympy.abc import a,b,c

expression = to_cnf(ITE(~c, ITE(~b, ~a, 0), 1), True)

s = pretty(expression).encode("utf-8")
print(s)
```

It seems like the content of the string s depends on how the program is executed:

```sh
$ python bug2.py
(c ∨ ¬b) ∧ (b ∨ c ∨ ¬a)
$ python bug2.py > x
$ cat x
And(Or(c, Not(b)), Or(b, c, Not(a)))
```

Expected behavior: the function "pretty" should always pretty-print.

I was able to reproduce the problem with sympy 1.0-3 (from Debian Stretch) and sympy-1.3 (from pip).

**Comment by asmeurer** [comment]
The `pretty` and `pprint` functions try to determine whether or not to use Unicode pretty printing or ASCII-only pretty printing automatically based on whether your environment supports Unicode. The relevant code is [here](https://github.com/sympy/sympy/blob/dd21c36eec81db24a606f6508e5fbacee5e22e17/sympy/printing/pretty/pretty_symbology.py#L75). 

It looks like this is an instance of https://stackoverflow.com/questions/492483/setting-the-correct-encoding-when-piping-stdout-in-python, where `sys.stdout.encoding` gets set to None. See the highest voted answer there (not the accepted answer) for a workaround. It looks like this is only an issue for Python 2. For me, Python 3 produces the Unicode output whether it is piped or not. 

You can force pretty/pprint to give Unicode output by setting `use_unicode=True`. 

I'm not sure if anything should be changed in SymPy. We could try to detect if stdout is a tty and set use_unicode to True (in Python 2). I don't know if it would work or break.

**Comment by markus2330** [comment]
Thank you for your detailed answers!

> The pretty and pprint functions try to determine whether or not to use Unicode pretty printing or ASCII-only pretty printing automatically based on whether your environment supports Unicode.

Line 91 `getattr(sys.stdout, 'encoding', None)` seems to be the problem. `pretty` cannot know if the produced string will be copied to stdout or somewhere else. I would not add further detections but simply do not use any detection if the function produces a string (and does not print by itself).

> I guess there's also a side issue here which is that we don't have a real ASCII pretty printer for logic expressions just prints a srepr.

Yes, this is also confusing.

**Comment by asmeurer** [comment]
Yes, the function was designed mainly for `pprint` and automatic printing (`init_printing`). `pretty` was an afterthought. We could change the default for `use_unicode` for `pretty` to True. Although note that this particular bug is in Python 2-only (we are dropping Python 2 support in a year), and for Python 3, things are even getting to the point where Unicode is supported even if the target environment doesn't support it (https://www.python.org/dev/peps/pep-0538/, https://www.python.org/dev/peps/pep-0540/).

**Comment by eric-wieser** [comment]
>  Although note that this particular bug is in Python 2-only

Presumably this can therefore now be closed?

**Comment by markus2330** [comment]
Yes! :rocket:
