### ISSUE TITLE
Non-private/hidden way of getting sympy version

### ISSUE THREAD

**Issue by MichaelClerx** [sympy/sympy#15582]
Hi all,

As far as I've been able to figure out, the only way to get Sympy's version number from within Python is to use the double underscore `.__version__` property (see for example the top google result for ["sympy version"](https://stackoverflow.com/questions/29824790)).

As double underscore properties are often "touch at your own risk" and/or undocumented, it'd be good to have some public way of accessing the sympy version, e.g. a `version()` method.

Sorry if this has already been done / discussed before!

**Comment by moorepants** [comment]
`__version__` is an exception to the rule of thumb. It is now almost universally standard that this is where you get the version number, especially in scientific python libs. It will not change, feel free to use it like it was public.

**Comment by MichaelClerx** [comment]
Really? NumPy and SciPy have a version module, for example.

And `__version__` is undocumented: https://docs.sympy.org/latest/search.html?q=__version__&check_keywords=yes&area=default

**Comment by moorepants** [comment]
Yes, really. I've been using all these packages for over 10 years and it has been the standard. Using `__version__` is perfectly ok:

```

In [1]: import numpy                                                                                                                                                                                               

In [2]: import scipy                                                                                                                                                                                               

In [3]: import sympy                                                                                                                                                                                               
im
In [4]: import pandas                                                                                                                                                                                              

In [5]: numpy.__version__                                                                                                                                                                                          
Out[5]: '1.15.2'

In [6]: scipy.__version__                                                                                                                                                                                          
Out[6]: '1.1.0'

In [7]: sympy.__version__                                                                                                                                                                                          
Out[7]: '1.3'

In [8]: pandas.__version__                                                                                                                                                                                         
Out[8]: '0.23.4'
```

It is undocumented because it is an informal standard in Python libraries.

**Comment by moorepants** [comment]
See PEP8: https://www.python.org/dev/peps/pep-0008/

**Comment by moorepants** [comment]
PEP 396 codifies it: https://www.python.org/dev/peps/pep-0396/#id25

**Comment by MichaelClerx** [comment]
PEP8 doesn't advocate it, it just says where to put "module level dunder names". PEP 396 is "deferred". 

I'm all for using standard names like __version__, but it (1) is explicitly not public and (2) is undocumented. Surely if its safe to use (despite looking like it's not) this should be documented?

**Comment by moorepants** [comment]
You can open a pull request to add something new if you want or to document it. But no one has had a problem with `__version__` in the history of SymPy. `__version__` has been in place at least since SymPy 0.5.0 (2007). You can be rest assured we will not change what `__version__` does. It is public from our perspective and likely derives from the ideas and traditions that helped create PEP 396. I have yet to find any other popular package that `__version__` isn't used as the defacto location for the version number.

**Comment by MichaelClerx** [comment]
Thanks

**Comment by moorepants** [comment]
Here is another old relative SO post: https://stackoverflow.com/questions/458550/standard-way-to-embed-version-into-python-package

**Comment by asmeurer** [comment]
Do not confuse private names (starting with a single underscore) with dunder names (starting and ending in two underscores). Dunder names are defined by the language and are not "private" in the sense that they should never be used by public API. Rather, they have very specific magic meanings. `__version__` is defined by PEP 396 as Jason pointed out. It is likely deferred because it defines a specification for external Python modules, but what it says is basically the standard used by most well developed Python packages.

See also [this section](https://www.python.org/dev/peps/pep-0008/#descriptive-naming-styles) of PEP 8:

> In addition, the following special forms using leading or trailing underscores are recognized (these can generally be combined with any case convention):
> - _single_leading_underscore: weak "internal use" indicator. E.g. from M import * does not import objects whose name starts with an underscore.
> - single_trailing_underscore_: used by convention to avoid conflicts with Python keyword, e.g.
>    Tkinter.Toplevel(master, class_='ClassName')
> - __double_leading_underscore: when naming a class attribute, invokes name mangling (inside class FooBar, __boo becomes _FooBar__boo; see below).
> - \_\_double_leading_and_trailing_underscore__: "magic" objects or attributes that live in user-controlled namespaces. E.g. \_\_init__, \_\_import__ or \_\_file__. Never invent such names; only use them as documented.
