### ISSUE TITLE
Indexed matrix-expression LaTeX printer is not compilable

### ISSUE THREAD

**Issue by Upabjojr** [sympy/sympy#15595]
```python
i, j, k = symbols("i j k")
M = MatrixSymbol("M", k, k)
N = MatrixSymbol("N", k, k)
latex((M*N)[i, j])
```

The LaTeX string produced by the last command is:
```
\sum_{i_{1}=0}^{k - 1} M_{i, _i_1} N_{_i_1, j}
```
LaTeX complains about a double subscript `_`. This expression won't render in MathJax either.

**Comment by Upabjojr** [comment]
It's pretty simple to solve, `_print_MatrixElement` of `LatexPrinter` is not calling `self._print` on the indices.

**Comment by axblount** [comment]
I'd like to work on this. When adding a test, should I expand `test_MatrixElement_printing` or add `test_issue_15595` just for this issue? Or both?

**Comment by supreet11agrawal** [comment]
The correct one should be `\sum_{i_{1}=0}^{k - 1} M_{i, i_1} N_{i_1, j}`.
Is that right?

**Comment by Upabjojr** [comment]
Tests can be put everywhere. I'd prefer to have them next to the other ones.
