### ISSUE TITLE
test_autowrap creates `wrapper_module_0.pyx`

### ISSUE THREAD

**Issue by oscarbenjamin** [sympy/sympy#15591]
Running the autowrap tests leaves a residual file `wrapper_module_0.pyx` in the cwd:
```console
$ git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
$ bin/test sympy/utilities/tests/test_autowrap.py -k test_cython_wrapper_compile_flags
==================================================================== test process starts =====================================================================
executable:         /Users/enojb/current/sympy/27venv/bin/python  (2.7.10-final-0) [CPython]
architecture:       64-bit
cache:              yes
ground types:       python 
numpy:              None
random seed:        64315091
hash randomization: on (PYTHONHASHSEED=881294686)

sympy/utilities/tests/test_autowrap.py[1] .                                                                                                               [OK]

========================================================= tests finished: 1 passed, in 0.24 seconds ==========================================================
$ git status
On branch master
Your branch is up to date with 'origin/master'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)

        wrapper_module_0.pyx

nothing added to commit but untracked files present (use "git add" to track)
```

The cause is [https://github.com/sympy/sympy/blob/sympy-1.3/sympy/utilities/autowrap.py#L315](https://github.com/sympy/sympy/blob/sympy-1.3/sympy/utilities/autowrap.py#L315) which ignores the `build_dir` argument when creating the `.pyx` file.

It would be easy enough to fix that so that the tests don't create this residual file but this is a bug in the code rather than the tests. Someone who understands how to use the autowrap module should test that it really works when using a different build directory.

**Comment by moorepants** [comment]
I think this PR https://github.com/sympy/sympy/pull/15354 should fix this.

**Comment by moorepants** [comment]
Can you check with the master branch and see if this is fixed? Is so, you can close the issue.

**Comment by oscarbenjamin** [comment]
Thanks @moorepants. I've just checked and this is fixed on master.

I'm closing this issue now.

**Comment by moorepants** [comment]
Thanks!
