### ISSUE TITLE
diff of Trace is wrong

### ISSUE THREAD

**Issue by nvhuynh16** [sympy/sympy#15614]
```
>>> A = MatrixSymbol('A', 3, 3)
>>> X = MatrixSymbol('X', 3, 3)
>>> diff(Trace(X@A), A)
3*A.T
```
According to the matrix cookbook, this should be `A.T`.

```
>>> diff(Trace(X.T@A@X), A)
6*A.T*X + 12*A*X
```
According to the [matrix cookbook](https://www.math.uwaterloo.ca/~hwolkowi/matrixcookbook.pdf), this should be `(A+A.T)*X` or `A*X + A.T*X`.

Also,
```
>>> diff(A, A)
Derivative(A, A)
```
This should be `Identity(9)`. This comes from

>  ∂AXB / ∂X = B^T ⊗ A

See page 13 of [MatCalc](http://www4.ncsu.edu/~pfackler/MatCalc.pdf). I don't know why it's not in the cookbook.

Some related issues:
#15126 
#5858
#10150 
#11568

**Comment by nvhuynh16** [comment]
Typo. I meant `diff(Trace(X@A), X)` and `diff(Trace(X.T@A@X), X)`.

**Comment by asmeurer** [comment]
@Upabjojr

**Comment by Upabjojr** [comment]
Almost simultaneous with my fix: https://github.com/sympy/sympy/pull/15615

I tested these cases, they all work after merging. I will add them as tests.

As for the identity matrix, I disagree:
```python
In [3]: X = MatrixSymbol("X", 3, 3)

In [4]: X = X.as_explicit()

In [5]: X
Out[5]: 
⎡X₀₀  X₀₁  X₀₂⎤
⎢             ⎥
⎢X₁₀  X₁₁  X₁₂⎥
⎢             ⎥
⎣X₂₀  X₂₁  X₂₂⎦

In [6]: X.diff(X)
Out[6]: 
⎡⎡1  0  0⎤  ⎡0  1  0⎤  ⎡0  0  1⎤⎤
⎢⎢       ⎥  ⎢       ⎥  ⎢       ⎥⎥
⎢⎢0  0  0⎥  ⎢0  0  0⎥  ⎢0  0  0⎥⎥
⎢⎢       ⎥  ⎢       ⎥  ⎢       ⎥⎥
⎢⎣0  0  0⎦  ⎣0  0  0⎦  ⎣0  0  0⎦⎥
⎢                               ⎥
⎢⎡0  0  0⎤  ⎡0  0  0⎤  ⎡0  0  0⎤⎥
⎢⎢       ⎥  ⎢       ⎥  ⎢       ⎥⎥
⎢⎢1  0  0⎥  ⎢0  1  0⎥  ⎢0  0  1⎥⎥
⎢⎢       ⎥  ⎢       ⎥  ⎢       ⎥⎥
⎢⎣0  0  0⎦  ⎣0  0  0⎦  ⎣0  0  0⎦⎥
⎢                               ⎥
⎢⎡0  0  0⎤  ⎡0  0  0⎤  ⎡0  0  0⎤⎥
⎢⎢       ⎥  ⎢       ⎥  ⎢       ⎥⎥
⎢⎢0  0  0⎥  ⎢0  0  0⎥  ⎢0  0  0⎥⎥
⎢⎢       ⎥  ⎢       ⎥  ⎢       ⎥⎥
⎣⎣1  0  0⎦  ⎣0  1  0⎦  ⎣0  0  1⎦⎦
```
The last result does not look like an identity matrix.

**Comment by nvhuynh16** [comment]
Great. I look forward to the next sympy version.

Answer `X.diff(X)` is just the identity matrix reshaped to (3,3,3,3).

As for the identity matrix itself, I am using the Magnus-Neudecker convention, which vectorizes matrices before computing derivatives. The point of me mentioning `det(X,X)` is that sympy should have an explicit answer for it considering how simple of an expression it is and how useful it can be for code generation. That said, the question of how to differentiate with respect to a matrix is not widely agreed [upon](https://en.wikipedia.org/wiki/Matrix_calculus#Other_matrix_derivatives). However, the Magnus-Neudecker convention seems to be popular. For example, as referenced in issue #15615, the matrix calculus paper (http://www.matrixcalculus.org/) agrees with the identity matrix, when you differentiate `X` by `X`.

I would caution using `X.diff(X)` as the answer because it is [unsuitable](https://en.wikipedia.org/wiki/Matrix_calculus#Other_matrix_derivatives). I have no problem with being the answer to `diff(X,X)` because if I want the Magnus-Neudecker convention, I would just reshape it to (9,9). However, it could be tricky to  implement `diff(A*X*B*v,X)` code generation given that the answer in Magnus-Neudecker convention is (B*v)^T ⊗ A.

**Comment by nvhuynh16** [comment]
My worry is that in the future, by not returning a matrix, standard matrix calculus will not work. For example, how would the chain rule work?

If the explicit matrices convention is used, there should be an easy way to get the Magnus-Neudecker convention. Maybe a function that converts between these two conventions?

That said, the original issue is probably addressed with the #15615 fix. So I have no problem with closing this issue.

**Comment by Upabjojr** [comment]
Maybe we can simply rename this issue.

**Comment by Upabjojr** [comment]
Anyway, I'm following the convention you would get from Ricci calculus. If reshaping is the way to convert to the other convention, just use that.
