### ISSUE TITLE
Jupyter notebook LaTeX output breaks when processed in LaTeX, ironically

### ISSUE THREAD

**Issue by mgeier** [sympy/sympy#15623]
Steps to reproduce:

* Create a Jupyter notebook (named, say, `mynotebook.ipynb`) with this content:

  ```python
  import sympy as sp
  sp.init_printing()
  1
  ```

* Convert it to LaTeX (you can remove the `--execute` flag if you saved the result in the notebook):

      python3 -m nbconvert mynotebook.ipynb --execute --to pdf

This creates the error (originating from LaTeX):

```
...
! LaTeX Error: Bad math environment delimiter.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.300     $$\begin{equation*}
                             1\end{equation*}$$
? 
! Emergency stop.
 ...                                              
                                                  
l.300     $$\begin{equation*}
                             1\end{equation*}$$
...
```

If you only convert `--to latex`, you'll see that this LaTeX code is generated:

```latex
...
\texttt{\color{outcolor}Out[{\color{outcolor}1}]:}
    
    $$\begin{equation*}1\end{equation*}$$
...
```

The reason for this error message is that the `equation*` environment is meant to be used in text mode, but sandwiching the whole thing between `$$` switches to math mode.

In this case the `$$` should simply be removed, but a general solution to this problem might be more involved.

**Comment by moorepants** [comment]
I wonder if this change https://github.com/sympy/sympy/pull/15367 caused this.

**Comment by mgeier** [comment]
Looks like it.

Please note that using a math environment (like `equation*`) is a step into the wrong direction, see #15329.

**Comment by asmeurer** [comment]
Ouch I didn't realize this broke nbconvert. We should definitely get this fixed before releasing. I wonder if we should add a test to the test suite that executes and nbconverts a simple SymPy notebook.

**Comment by mgeier** [comment]
Yeah, I guess such a test would be good.

You could also consider moving the notebooks from the [examples/](../blob/master/examples) directory to your docs.

This way they could be automatically executed (using my little `nbsphinx` extension) whenever the documentation is built. You could then make building the docs part of the CI tests.
And when generating the PDF of the docs, this error here would be spotted.

**Comment by asmeurer** [comment]
Actually we don't even ship the notebooks, the main reason being that we don't have automated testing for them. So I agree moving them to the docs and rendering them as part of the tests would be good.

**Comment by asmeurer** [comment]
I was pointed to https://github.com/computationalmodelling/nbval as a way to test the output of notebooks (apparently it's also not hard to do manually, see https://twitter.com/SylvainCorlay/status/1074744629512286215).

**Comment by moorepants** [comment]
There was discussion some time back about where notebooks belong. This was created but never populated:

https://github.com/sympy/sympy-notebooks

An then this was created separately:

https://github.com/sympy/quantum_notebooks

One key thing is that we wouldn't want to commit notebooks with outputs or have to host image binaries in the main sympy directory.

It is easy enough to execute the notebooks on travis with something like:

```
jupyter nbconvert --debug --ExecutePreprocessor.enabled=True --ExecutePreprocessor.timeout=300 --to=html nb.ipynb
```

**Comment by asmeurer** [comment]
Yeah but the problem with just executing the notebooks is that it doesn't check that the output stays the same. Ideally it would also test the output, like we do for doctests. 

I agree if a notebook has any kind of image output it should note be stored in this repo.

**Comment by moorepants** [comment]
Yes, sure. Just ensure it runs is better than not running and all, and checking the output is even better. The former is pretty low overhead to setup as an initial "test".

**Comment by mgeier** [comment]
The error in this issue occurred during the LaTeX run, so the `nbconvert` command would have to use `--to=pdf` to detect this error.
I guess `nbval` doesn't help in this case, because it looks at the output *in the notebook file* as opposed to the resulting HTML/LaTeX/PDF file, right?

My main question about the notebooks is: do you want their contents to be part of the documentation or not?

If yes, you should consider using `nbsphinx`.

If not, but you want to use them as regression tests, you should consider using `nbval`.

Theoretically, you could also do both. But I guess the content of the notebooks should very much depend on whether they are used as part of the user documentation or as part of the automated tests.

**Comment by asmeurer** [comment]
No, we would have to test that separately. My point about nbval is that if we have rendered notebooks in the docs, then we should actually test the output of the notebook cells, the same as we do with doctests. The point of doctests isn't to be regression tests (we have normal tests for that). They should rather be thought of as documentation that happens to be tested. It tests that the output of the documentation examples is actually what it says that it is, and if changes, we are aware of it and it gets updated. Sometimes this catches actual regressions as well, but that's not the point of it.
