### ISSUE TITLE
PermutationGroup.is_normal gives incorrect result if PermutationGroup is the trivial group

### ISSUE THREAD

**Issue by FabianBall** [sympy/sympy#15636]
Hey there,

I just encountered the following (independent of n):
```python
>>> from sympy.combinatorics import Permutation, PermutationGroup

>>> n = 2
>>> identity = Permutation(n-1)
>>> cycle = Permutation([(i+1)%n for i in range(n)])
>>> In = PermutationGroup(identity)
>>> Cn = PermutationGroup(cycle)
>>> In.is_normal(Cn)
False
```
I.e. I simply create two permutation groups, one containing the identity only, the other containing a cycle (thus being the cyclic group). ``is_normal`` should test if ``In`` is a normal subgroup of ``Cn`` (or of course for any other two groups). The result ``False`` is incorrect, as the trivial group on n elements is always a normal subgroup of any group on n elements.

If anybody could please double check this concern if I'm not terribly mistaken here?!

I assume the issue results from the implementation that uses ``coset_factor`` to check if the new permutation ``p = g*h*g^{-1}`` (``g \in G, H \in H``, H is tested to be a normal subgroup of G) is part of H.
In the above case, h is the identity permutation, therefore p is also the identity (because of ``g*h*g^{-1} = g*g^{-1}``). But there is no such factorization of the identity (and testing the above for the generators only, normally never gives the identity permutation, except for this case).

**Comment by smichr** [comment]
I am not sure if the [Rubik's cube issue](https://stackoverflow.com/questions/54228547/sympy-permutation-groups-parity-not-working-as-expected) is related or not.

**Comment by jksuom** [comment]
I think that the bug is where noted above: 
> there is no such factorization of the identity 

Therefore `coset_factor` returns, correctly, the empty list of generators for the identity. Unfortunately, the empty list is also returned to indicate the failure. To fix this, the [test](https://github.com/sympy/sympy/blob/master/sympy/combinatorics/perm_groups.py#L1833) should be skipped for `p1` equal to identity.

**Comment by FabianBall** [comment]
Alright, thank's for the feedback. From quickly inspecting the Rubik's cube issue, I can't see a relation, but if I find the time I will be looking at into more detail.
Anyway, I'll fix the original issue mentioned here.

**Comment by FabianBall** [comment]
I checked the Rubik's cube issue a bit and don't see a relation to the issue discussed here. But I have to admit that I did not completely got into the provided code there. However, no subgroup checks are involved in any way.

**Comment by jksuom** [comment]
The Rubik's cube issue is about parity. This issue has no connection with that.
