### ISSUE TITLE
ipython --classic disables variables pretty-printing

### ISSUE THREAD

**Issue by foxcpp** [sympy/sympy#15637]
### Problem

```
~
⟩ ipython

In [1]: from sympy import init_session                                                                                

In [2]: init_session(quiet=True, pretty_print=True)                                                                   


In [3]: Integral(1/x, x)                                                                                              
Out[3]: 
⌠     
⎮ 1   
⎮ ─ dx
⎮ x   
⌡     

In [4]:                                                                                                               
Exiting ...


~
⟩ ipython --classic

>>> from sympy import init_session                                                                                    

>>> init_session(quiet=True, pretty_print=True)                                                                       


>>> Integral(1/x, x)                                                                                                  
Integral(1/x, x)

>>> pprint(Integral(1/x, x))                                                                                          
⌠     
⎮ 1   
⎮ ─ dx
⎮ x   
⌡
```

### Expected behavior

Pretty-printing with `ipython --classic` should work the same way as it does without `--classic` value.

### Actual behavior

See above.

I'm not sure whether this is valid behavior but since description of `--classic` in IPy's help mentions only prompt this should not affect pretty-printing, right?

### Version information

IPython 7.1.1
SymPy 1.3
Python 3.7.1

**Comment by jksuom** [comment]
[This line](https://github.com/ipython/ipython/blob/master/IPython/terminal/ipapp.py#L125) seems to indicate that `--classic` was designed to internally disable pprint.

**Comment by foxcpp** [comment]
Oh, ok. I guess this is intended behavior then.

**Comment by asmeurer** [comment]
I suppose that line is there to disable the pretty printing that IPython does automatically to things like lists and dicts. But SymPy uses the same IPython printing machinery, because setting sys.displayhook over IPython's could cause issues. It seems even in ipython --classic IPython sets the displayhook:

```
>>> import sys

>>> sys.displayhook
<IPython.terminal.prompts.RichPromptDisplayHook object at 0x109367be0>
```

(also the output is not so "classic" in that it still prints a newline between the prompts). I suspect the classic mode is not used by many.
