### ISSUE TITLE
sqrt(I) is converted into -1**(-4)

### ISSUE THREAD

**Issue by proy87** [sympy/sympy#15653]
Why `sqrt(I)` is converted into `(-1)**(1/4)`?

**Comment by RituRajSingh878** [comment]
Here "I"(iota) refere to (-1)**1/2 ,

**Comment by normalhuman** [comment]
This is a reasonable question, because automatic evaluation is not always desirable. For comparison, `sqrt(-I)` is not automatically evaluated to `(-1)**(3/4)`.  

A thing to consider: if we do disable automatic evaluation here, how would one get `(-1)**(1/4)` when it is the desired?

**Comment by asmeurer** [comment]
I agree it should be left alone. We automatically canonicalize rational powers or rational numbers, but this isn't quite the same as that.

**Comment by AnimeshSinha1309** [comment]
As noted above, even after deleting line 3867 in *core/numbers.py*, any multiplication expression that `sqrt(I)` is in still gets evaluated to `(-1)**(1/4)`, as here:
```python
>>> from sympy import sqrt, I
>>> sqrt(I) * 2
2*(-1)**(1/4)
```
I am not sure, but I think it's due to these lines. Can someone cofirm.
https://github.com/sympy/sympy/blob/cf8b06968bd54c58ab19e7119165e7b3c6f5c904/sympy/core/mul.py#L544-L547

**Comment by AnimeshSinha1309** [comment]
Narrowing it down a bit more, these lines lines seem to where we need to look
https://github.com/sympy/sympy/blob/cf8b06968bd54c58ab19e7119165e7b3c6f5c904/sympy/core/mul.py#L300
`sqrt(I)` in **STEP 1 of Mul.flatten()** passes the check for `o.is_commutative` and gets split into **base = I, exp = 1/2**. And once `sqrt(I)` gets split into base and exponent, the atomic expression I will be converted to `(-1)^(1/2).
However, for number like `sqrt(1+I)` the evaluation does go into the Commutative expression section, but does not fall in any of the if branches so it's just not handled, and returned as is. Or so it seems to me.
