### ISSUE TITLE
Comparison with nan should return False instead of raising TypeError

### ISSUE THREAD

**Issue by normalhuman** [sympy/sympy#15655]
There is nothing mathematically wrong with this code, yet it raises a TypeError. 
```
>>> from sympy import *
>>> x, r = symbols('x r')
>>> integrate(exp(-r*x), (x, 0, oo)).subs(r, 0)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/k3/sympy/sympy/core/basic.py", line 997, in subs
    rv = rv._subs(old, new, **kwargs)
  File "/home/k3/sympy/sympy/core/basic.py", line 1109, in _subs
    rv = self._eval_subs(old, new)
  File "/home/k3/sympy/sympy/functions/elementary/piecewise.py", line 843, in _eval_subs
    c = c._subs(old, new)
  File "/home/k3/sympy/sympy/core/basic.py", line 1111, in _subs
    rv = fallback(self, old, new)
  File "/home/k3/sympy/sympy/core/basic.py", line 1088, in fallback
    rv = self.func(*args)
  File "/home/k3/sympy/sympy/core/relational.py", line 556, in __new__
    r = cls._eval_relation(lhs, rhs)
  File "/home/k3/sympy/sympy/core/relational.py", line 863, in _eval_relation
    return _sympify(lhs.__gt__(rhs))
  File "/home/k3/sympy/sympy/core/expr.py", line 339, in __gt__
    raise TypeError("Invalid NaN comparison")
TypeError: Invalid NaN comparison
```
The reason is that `integrate` returns  
```
Piecewise((1/r, pi/2 > Abs(arg(r))), (Integral(exp(-r*x), (x, 0, oo)), True))
```
and when r is replaced by 0, the comparison `pi/2 > nan` raises that exception. But logically, this only means that the condition `pi/2 > Abs(arg(r))` does not hold when r = 0. No need to panic, just say it's False. 

By the way, in NumPy all comparisons with `np.nan` return False

**Comment by asmeurer** [comment]
The same thing happens with complex numbers.

**Comment by normalhuman** [comment]
I wonder if it would make sense to have different behavior in conversion to bool vs in Piecewise. That is, if some code goes `if a < 2:` and `a` is `nan` or complex, then TypeError can still be raised. But if a Piecewise contains `(a < 2)` and `a` is `nan` or complex, that would be treated as False. 

In some sense, this distinction is already present: if `a` in the above examples is a newly declared `Symbol('a')` then coercion to bool fails but Piecewise works fine.

**Comment by asmeurer** [comment]
Fixing the evaluation in Piecewise would definitely be much simpler than changing the behavior of inequalities everywhere, especially if we try to change complex comparisons (changing nan would probably not affect anything because very few things compare against nan).

**Comment by normalhuman** [comment]
Alright then, maybe that would be a solution: catching TypeError within Piecewise methods.

I don't want to revisit #7776 and #7834 etc.
