### ISSUE TITLE
Matrix expressions sometimes gives Add and Mul instead of MatAdd and MatMul

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#15665]
```
>>> A = MatrixSymbol("A", n, n)
>>> B = MatrixSymbol("B", n, n)
>>> type(Mul(A, B))
<class 'sympy.matrices.expressions.matmul.MatMul'>
>>> type(Mul(-1, Mul(A, B)))
<class 'sympy.core.mul.Mul'>
```

In https://github.com/sympy/sympy/pull/15373, MatAdd and MatMul were made to subclass Add and Mul.

However, the code in Mul.flatten doesn't handle this case correctly. The problem is that in order to return the right type, it puts the args in the c_part, not the nc_part (the `nc_part` is a list of args, which are passed to Mul._make_args). But it doesn't take this logic into account when processing an arg that is itself a Mul. 

I don't know if there is a simple fix here. Mul.flatten was not designed to be able to return subclasses of Mul, and the current behavior of keeping the MatMul in c_part is a bit of a hack. 

This issue prevents some simplifications from working (in conjunction with other fixes at https://github.com/sympy/sympy/pull/15121), because the Mul/Add types that should be MatMul/MatAdd cause type checks in the matrix expressions module to fail. 

I would suggest reverting https://github.com/sympy/sympy/pull/15373 (CC @Upabjojr). It was also merged without any review.

**Comment by asmeurer** [comment]
There are also several places that call Mul._make_args instead of Mul (like in `gcd_terms`) that break when passed matrix expressions (but they should be fixed, since they wrongly assume that the args are already processed when they don't come from a pre-existing Mul).

**Comment by asmeurer** [comment]
I've reverted the PR at https://github.com/sympy/sympy/pull/15666. Until we can think of a better way to do Mul.flatten so that it can return subclasses, I would do this.

**Comment by Upabjojr** [comment]
OK.

**Comment by asmeurer** [comment]
Maybe we can make it work using the post-processors. 

Or maybe simpler would be if we see a matrix expression to just call MatMul on the args. 

The problem is handling nested Muls/MatMuls. We do want flatten to actually flatten, but we also want any Mul with a product of matrix expressions to also give a matrix expression.

**Comment by jmig5776** [comment]
I would also like to work on this issue.

**Comment by jmig5776** [comment]
I think I had done a quickfix for Mul.flatten in this PR #15692 . But I think the type from Mul(A,B) we should expect a Mul type only and if a user wants to do MatMul he should call it directly. Why we want Mul to return the object of its subclass i.e in this case MatMul is subclass of Mul

**Comment by jmig5776** [comment]
Moreover i think flatten is doing its work correctly we had to change something in Basic._exec_constructor_postprocessors to get more general working of Mul as expected.
