### ISSUE TITLE
simplify gives a wrong result

### ISSUE THREAD

**Issue by retsyo** [sympy/sympy#15684]
this short matrix calculation
```python
from sympy import *

s1 = Matrix([ [2,   0, 0], [0, 1./5, 0], [0,   0, 1]])*Matrix([ [cos((-60*pi)/180), -sin((-60*pi)/180), 0], [sin((-60*pi)/180),  cos((-60*pi)/180), 0], [0,0, 1]])
print(s1)
```
gives
```
Matrix([[1, sqrt(3), 0], [-0.1*sqrt(3), 0.100000000000000, 0], [0, 0, 1]])
```

then I try to make the same expression but in string into sympy expression
```python
with evaluate(False):
    s = sympify('Matrix([ [2,   0, 0], [0, 1./5, 0], [0,   0, 1]])*Matrix([ [cos((-60*pi)/180), -sin((-60*pi)/180), 0], [sin((-60*pi)/180),  cos((-60*pi)/180), 0], [0,0, 1]])')

s2 = simplify(s)

print('s2=')
print(s2)
```
which displays
```
s2=
Matrix([[1, 0.1*sqrt(3), 0], [-sqrt(3), 0.100000000000000, 0], [0, 0, 1]])
```

As you can see, `s2` is not the same value of `s1`, why?

In fact, in this code, simplify('A*B') is calculated by `B*A` which is obviously wrong for matrix

**Comment by retsyo** [comment]
aha, latest sympy has fixed this bug, but sympy supplied by anaconda does not yet
so I closed it

**Comment by jmig5776** [comment]
@retsyo  I implemented your code in sympy live there it gives the error which you have given, but when i implemented your code  on my development environment by forking the sympy repository then it is giving the expected result

![sympy issue](https://user-images.githubusercontent.com/39242494/50382985-24fcf580-06d1-11e9-8b11-02a9ea5f7310.PNG)

So in the new release may be your error will be rectified automatically.

**Comment by jmig5776** [comment]
I think so because the output of both of these is coming to be same in my developing environment.

**Comment by retsyo** [comment]
it is solved in the latest code, so we can close it now
