### ISSUE TITLE
Fourier Series of sin(x)

### ISSUE THREAD

**Issue by s1291** [sympy/sympy#15701]
Obviously the Fourier series of sin(x) is sin(x) but
Try the following:
```
from sympy import Function, sin, fourier_series, pi
from sympy.abc import x

f = Function('f')(x)
f = sin(x)

s = fourier_series(f) # or e.g: fourier_series(f, (x,-pi, pi))
s.truncate(2) # it works for n = 1 but for 2 the statement doesn't respond
```
*P.S*: I am using sympy 1.3.

**Comment by jmig5776** [comment]
I had added a ValueError such that if n in truncate is greater than the non zero terms in fourier series such that the sum of non zero terms becomes equal to the given function. Moreover an appropriate error message is also shown with the number of non zero terms in the respected fourier series

**Comment by s1291** [comment]
@jmig5776 : Are you serious? The function *must* not return an error in this case. That is a huge mistake and a huge limitation

**Comment by jmig5776** [comment]
@s1291 Mind your language . I had added the value error because if you go through the docstring of truncate it is clearly written there that we are required to return ```Return the first n nonzero terms of the series```. It means if the user is putting value greater than the length of the terms in series then it is an value error. 
I thought of returning the whole series if the value is greater than the length of the series.But that will be  not appropriate because user expects n terms to be returned.

**Comment by asmeurer** [comment]
Here is how I would suggest to fix this. We need to check if the input function has a finite Fourier series. A finite Fourier series is a finite linear combination of sines and cosines with arguments `n*x`. Probably applying the appropriate trig expansion functions from the `fu` module, and checking if it looks like a Fourier series should be sufficient. If it is, the FourierSeries object should instead return a subclass FiniteFourierSeries, which operates directly on the finite series.

**Comment by jmig5776** [comment]
@asmeurer Ohh okk okk I would like to work upon this issue and would like to do changes as you suggested.

**Comment by ShubhamKJha** [comment]
@jmig5776 are you still working on it?

**Comment by ShubhamKJha** [comment]
@asmeurer I have started working on this according to your suggestion.
