### ISSUE TITLE
dsolve fails to solve for initial condition which does not seem complicated

### ISSUE THREAD

**Issue by normalhuman** [sympy/sympy#15724]
Trying to solve `y' = 1/y` with initial condition `y(1) = 2`. Expected solution: `y = sqrt(2*x + 2)`. Works fine without ICS, fails with it. 
```
>>> from sympy import *
>>> x, y = Symbol('x'), Function('y')
>>> dsolve(y(x).diff(x) - 1/y(x), y(x))
[Eq(y(x), -sqrt(C1 + 2*x)), Eq(y(x), sqrt(C1 + 2*x))]
>>> dsolve(y(x).diff(x) - 1/y(x), y(x), ics={y(1): 2})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/k3/sympy/sympy/solvers/ode.py", line 680, in dsolve
    return _helper_simplify(eq, hint, hints, simplify, ics=ics)
  File "/home/k3/sympy/sympy/solvers/ode.py", line 723, in _helper_simplify
    solved_constants = solve_ics([s], [r['func']], cons(s), ics)
  File "/home/k3/sympy/sympy/solvers/ode.py", line 818, in solve_ics
    raise NotImplementedError("Couldn't solve for initial conditions")
NotImplementedError: Couldn't solve for initial conditions
```

**Comment by ethankward** [comment]
There could be a try / catch block on line 723 in `ode.py`. `solve_ics` can raise 4 different errors (either ValueError or NotImplementedError) that one might like to do different things with- or just ignore all of them and `pass`. Right now if any solution cannot be solved for it won't return partial results.

**Comment by oscarbenjamin** [comment]
The IC code isn't properly setup to handle the case of multiple general solutions. In this case one form works and the other does not:
```julia
In [12]: solve(sqrt(x+2)-2)                                                                                                                                   
Out[12]: [2]

In [13]: solve(-sqrt(x+2)-2)                                                                                                                                  
Out[13]: []
```
In the second case a simpler example is
```julia
In [18]: solve(Eq(sqrt(x), -2))                                                                                                                               
Out[18]: []
```
The code for handling ICs should consider that when there are multiple solution forms the ICs can be used to select the valid form. In this case one form is valid for positive ICs and one for negative ICs.

**Comment by sharma-kunal** [comment]
@oscarbenjamin @ethankward Can you please review the PR ?

**Comment by oscarbenjamin** [comment]
I think this might be the place that normally handles that but it should really be the very last thing that happens in `dsolve`:
[https://github.com/sympy/sympy/blob/fe3dea79551bbeab86011361af2364abc53105f6/sympy/solvers/ode.py#L2330](https://github.com/sympy/sympy/blob/fe3dea79551bbeab86011361af2364abc53105f6/sympy/solvers/ode.py#L2330)

**Comment by oscarbenjamin** [comment]
Sorry that last message was intended for the PR. I've recommented there.
