### ISSUE TITLE
apart is not working

### ISSUE THREAD

**Issue by proy87** [sympy/sympy#15738]
`1/(71699*x**2 + 1644500000*x - 13004200000000*E).apart(x)` returns unchanged expression

**Comment by jmig5776** [comment]
I think you are calling the apart function on denominator only which is like calling ```(71699*x**2 + 1644500000*x - 13004200000000*E).apart(x) ```.  I think the call should be like ```(1/(71699*x**2 + 1644500000*x - 13004200000000*E)).apart(x)``` but i had implemented it it is returning the unchanged expression in either case.

**Comment by jksuom** [comment]
The docstring of `apart` says that the default method (`full=False`) only works over the rational numbers. If there are irrational numbers like `E`, it is necessary to set `full=True`.
```
>>> (1/(71699*x**2 + 1644500000*x - 13004200000000*E)).apart(x, full=True)
RootSum(71699*_w**2 + 1644500000*_w - 13004200000000*E, Lambda(_a, (71699*_a/(1352190125000000000 + 1864776271600000000*E) + 13/(21378500000 + 29482628800*E))/(-_a + x)))
```
A more explicit expression can be obtained by `_.doit()`.

**Comment by proy87** [comment]
What does keyword `extension` do?

**Comment by jksuom** [comment]
It is used for factoring over an algebraic extension field.
```
>>> (1/(x**2 - 2)).apart(x, extension=sqrt(2))
-sqrt(2)/(4*(x + sqrt(2))) + sqrt(2)/(4*(x - sqrt(2)))
```
