### ISSUE TITLE
nsolve error: local variable 'x' referenced before assignment

### ISSUE THREAD

**Issue by anhhh11** [sympy/sympy#15746]
I run the following code but it return error 
UnboundLocalError: local variable 'x' referenced before assignment

```
n, x = sympy.symbols('n x')
e = 15
var = 11
e1 = n*e
var1 = n*var
std1 = sympy.sqrt(var1)
pdf = 1 / sympy.sqrt(2*math.pi*var1) * sympy.exp(-(x - e1)**2 / 2*var1)
inte = sympy.integrate(pdf,(x, 0, 10*60)) - 0.95
sympy.nsolve(inte, n, 1000)
```

**Comment by RituRajSingh878** [comment]
> I run the following code but it return error
> UnboundLocalError: local variable 'x' referenced before assignment
> 
> ```
> n, x = sympy.symbols('n x')
> e = 15
> var = 11
> e1 = n*e
> var1 = n*var
> std1 = sympy.sqrt(var1)
> pdf = 1 / sympy.sqrt(2*math.pi*var1) * sympy.exp(-(x - e1)**2 / 2*var1)
> inte = sympy.integrate(pdf,(x, 0, 10*60)) - 0.95
> sympy.nsolve(inte, n, 1000)
> ```
 Traceback (most recent call last)


UnboundLocalError                        
<ipython-input-21-6d9dfdff7dab> in <module>
----> 1 sympy.nsolve(inte, n, 1000)

~/sympy/sympy/utilities/decorator.py in func_wrapper(*args, **kwargs)
     89         dps = mpmath.mp.dps
     90         try:
---> 91             return func(*args, **kwargs)
     92         finally:
     93             mpmath.mp.dps = dps

~/sympy/sympy/solvers/solvers.py in nsolve(*args, **kwargs)
   2929 
   2930         f = lambdify(fargs, f, modules)
-> 2931         x = sympify(findroot(f, x0, **kwargs))
   2932         if as_dict:
   2933             return [dict([(fargs, x)])]

~/anaconda3/lib/python3.6/site-packages/mpmath/calculus/optimization.py in findroot(ctx, f, x0, solver, tol, verbose, verify, **kwargs)
    965             if error < tol * max(1, norm(x)) or i >= maxsteps:
    966                 break
--> 967         if not isinstance(x, (list, tuple, ctx.matrix)):
    968             xl = [x]
    969         else:

UnboundLocalError: local variable 'x' referenced before assignment

**Comment by asmeurer** [comment]
I believe this error comes from mpmath, and is fixed in the latest version. The real error is `ValueError: Could not find root using the given solver.
Try another starting point or tweak arguments.`

If you think the solver should be able to find a root near 1000, you should open an issue on the mpmath repo. 

Here is the expression `inte` by the way

```
-0.95 + 0.00546752833512523*sqrt(22)*sqrt(pi)*erf(15*sqrt(22)*n**(3/2)/2)/n + 0.00546752833512523*sqrt(22)*sqrt(pi)*erf(sqrt(22)*sqrt(n)*(-15*n + 600)/2)/n
```

I'm closing this as I think there is no issue with SymPy here.
