### ISSUE TITLE
Integer and StdFactKB memory leak

### ISSUE THREAD

**Issue by iblanes** [sympy/sympy#15778]
There is a memory leak in the Integer class. The internal ```_intcache``` caching dictionary does not have any size limitation and an instance of ```Integer``` and ```StdFactKB``` is kept for each integer that is ever used.

The following script reproduces the issue: a simple 100k "do-nothing" loop that takes around 350 Mb of memory.

```python3
import os
os.environ['SYMPY_USE_CACHE'] = 'no'

from sympy.parsing.sympy_parser import parse_expr

import gc
import objgraph

for i in range(100000):
    parse_expr('log({})'.format(i), local_dict=dict(), evaluate=False)

gc.collect()

print(objgraph.show_most_common_types(limit=10))
```

(the ```objgraph``` module is available at https://mg.pov.lt/objgraph/)

The script reports the following object usage:
```
dict      204547
StdFactKB 200468
Integer   199996
function  14659
tuple     4547
None
```

It seems that this issue can be resolved through https://github.com/sympy/sympy/pull/9294.

**Comment by asmeurer** [comment]
The fix should be similar to this one. https://github.com/sympy/sympy/pull/15453. Should be easy to fix.

**Comment by NoumbissiValere** [comment]
@asmeurer am interested in solving this issue. please can you tell me how go about solving it?

**Comment by iblanes** [comment]
@NoumbissiValere you already have a patch for this in #9294. It just needs to be tested for performance regressions.

**Comment by RituRajSingh878** [comment]
I would like to work on this.

**Comment by NoumbissiValere** [comment]
ok @iblanes  i will work in that direction

**Comment by NoumbissiValere** [comment]
@iblanes i have look at the commit of the patch in #9294 issue. i notice he
was instead removing the -intcache from the code. removing that won't
disable caching ? i don't understand. please can you give more light into
this issue?

**Comment by iblanes** [comment]
@NoumbissiValere #9294 changes the cache infrastructure being used from an adhoc (and unbounded) cache into a proper cache (notice the ```@cacheit``` annotation in the function).

**Comment by NoumbissiValere** [comment]
Ok. @iblanes please can you help me on how to perform the performance
regression test?

**Comment by NoumbissiValere** [comment]
@iblanes i successfully applied the patches 🙂. please how to do i perform
the regression performance test so that its correctness can be confirmed.

**Comment by NoumbissiValere** [comment]
It is ok, i have successfully done the regression performance test and they
were positive. the issue has been successfully resolved. yuppiiiiii. i just
solve my first open source issue. thanks @iblanes  for your help. i really
appreciate it
