### ISSUE TITLE
Sympy Cant calculate Phase of an complex Expression

### ISSUE THREAD

**Issue by Losspost** [sympy/sympy#15782]
Hi.
I am trying to calculate the following example equation:
arg(5*j*w)=-pi
Now i tried to solve for w, but it just gives me out an empty quantity.
My Code:
```
print(rueck_system_loesungen)
w_s = sp.symbols("\omega_s", real=True,positiv = True)
rueck_system_loesung = rueck_system_loesung[V4]/u_a
expr = sp.Eq(sp.tan(arg(rueck_system_loesung)),sp.tan(-sp.pi))
print(sp.latex(sp.re(rueck_system_loesung)))
a7_w_s = sp.solve(expr,w_s)
print(sp.latex(a7_w_s))
```

The Output ist :
<img src="https://latex.codecogs.com/gif.latex?{V_4:&space;G_s**3*u_a/((1.0*I*C_s*\omega_s&space;&plus;&space;2*G_s)*(1.0*I*C_s*\omega_s&space;-&space;G_s**2/(1.0*I*C_s*\omega_s&space;&plus;&space;2*G_s)&space;&plus;&space;2*G_s)*(1.0*I*C_s*\omega_s&space;&plus;&space;G_ein&space;-&space;G_s**2/(1.0*I*C_s*\omega_s&space;-&space;G_s**2/(1.0*I*C_s*\omega_s&space;&plus;&space;2*G_s)&space;&plus;&space;2*G_s)&space;&plus;&space;G_s))}" title="{V_4: G_s**3*u_a/((1.0*I*C_s*\omega_s + 2*G_s)*(1.0*I*C_s*\omega_s - G_s**2/(1.0*I*C_s*\omega_s + 2*G_s) + 2*G_s)*(1.0*I*C_s*\omega_s + G_ein - G_s**2/(1.0*I*C_s*\omega_s - G_s**2/(1.0*I*C_s*\omega_s + 2*G_s) + 2*G_s) + G_s))}" />

And
<img src="https://latex.codecogs.com/gif.latex?G_{s}^{3}&space;\Re{\left(\frac{1}{\left(1.0&space;i&space;C_{s}&space;\omega_s&space;&plus;&space;2&space;G_{s}\right)&space;\left(1.0&space;i&space;C_{s}&space;\omega_s&space;-&space;\frac{G_{s}^{2}}{1.0&space;i&space;C_{s}&space;\omega_s&space;&plus;&space;2&space;G_{s}}&space;&plus;&space;2&space;G_{s}\right)&space;\left(1.0&space;i&space;C_{s}&space;\omega_s&space;&plus;&space;G_{ein}&space;-&space;\frac{G_{s}^{2}}{1.0&space;i&space;C_{s}&space;\omega_s&space;-&space;\frac{G_{s}^{2}}{1.0&space;i&space;C_{s}&space;\omega_s&space;&plus;&space;2&space;G_{s}}&space;&plus;&space;2&space;G_{s}}&space;&plus;&space;G_{s}\right)}\right)}" title="G_{s}^{3} \Re{\left(\frac{1}{\left(1.0 i C_{s} \omega_s + 2 G_{s}\right) \left(1.0 i C_{s} \omega_s - \frac{G_{s}^{2}}{1.0 i C_{s} \omega_s + 2 G_{s}} + 2 G_{s}\right) \left(1.0 i C_{s} \omega_s + G_{ein} - \frac{G_{s}^{2}}{1.0 i C_{s} \omega_s - \frac{G_{s}^{2}}{1.0 i C_{s} \omega_s + 2 G_{s}} + 2 G_{s}} + G_{s}\right)}\right)}" />
And the final result:
<img src="https://latex.codecogs.com/gif.latex?\left&space;[&space;\right&space;]" title="\left [ \right ]" />

I tried to substitute all values except w but this didnt work either. I seems to have trouble with getting the imaginary or real part.
Greetings Losspost

**Comment by oscargus** [comment]
The equation you stated initially, arg(5jw)=-pi, cannot be solved when w is real. Any purely imaginary number will have an argument of +/- pi/2.

With that said, it seems like the equation you are actually trying to solve is something else.

**Comment by oscargus** [comment]
@Losspost Feel free to provide more details or close the issue.
