### ISSUE TITLE
Tangent line to Circle does not work

### ISSUE THREAD

**Issue by lourenko** [sympy/sympy#15797]
Running the code:
```
from sympy.geometry import Point, Line, Circle
Ri = 0.024127189424130748
Ci = Point(0.0864931002830291, 0.0819863295239654)
A = Point(0, 0.0578591400998346)
c = Circle(Ci, Ri)
Lax = Line(A, slope=0)
print(c.is_tangent(Lax)) # Gives False
I = c.tangent_lines(A)[1].p1
print(I[1]-A[1]) # But the distance of tangent is zero?
```
gives the horizontal line Lax is not tangent to the bottom of circle c. But measuring (and visually), the distance of circle to line gives zero. Can anyone check if I am doing something wrong please?

**Comment by RituRajSingh878** [comment]
I think this is due to many points after the decimal as you can see Lax.distance(Ci) and Ri has a very small difference (should be zero) due to this it is showing "false" for the tangent.

**Comment by oscarbenjamin** [comment]
@lourenko the problem is that they are not *exactly* tangent. There is a small difference.

You can eliminate rounding error within Sympy by using `Rational` as in 
```python
Ri = Rational('0.024127189424130748')
```
(note the quotes)

However this will not solve your problem since the numbers you are putting in are not precisely correct: Sympy is returning the correct answer for the numbers you give.

**Comment by oscarbenjamin** [comment]
@lourenko can you provide a complete example with all variables defined and the imports for any functions shown?

I can't run this because I don't know what `d0` etc are. Also I can't tell whether `pi`, `tan` etc are imported from Sympy or from numpy, or the math module etc.

**Comment by lourenko** [comment]
I solved the problem adding and subtracting `1e-14` to all numeric values. As @RituRajSingh878 and @oscarbenjamin stated, this should be a rounding error problem. Now the code is running fine. Thank for your attention patience.

**Comment by lourenko** [comment]
I solved the problem adding and subtracting `1e-14` to all numeric values. As @RituRajSingh878 and @oscarbenjamin stated, this should be a rounding error problem. Now the code is running fine. Thank for your attention patience.

**Comment by lourenko** [comment]
Btw @oscarbenjamin, I am using:
`d0 = 0.1412898146509956 #[meters]`
e
`d2g = 0.30038307607263465 #[meters]`
and importing like:
```
import numpy as np
from numpy import pi, sqrt, sin, cos, tan, arctan2
from sympy.geometry import Point, Line, Circle, Segment
from sympy import symbols as symbol
```

**Comment by oscarbenjamin** [comment]
The thing about something like `is_tangent` is that it requires *all* of your numbers to be exactly mathematically precise. The better solution here is either:
1. Use only exact calculations. Don't mix floats in and don't use numpy's pi, sqrt etc. Start with exact numbers from Sympy and use them to calculate everything, using only Sympy functions.
2. If you must use floats then you shouldn't ask a question like `is_tangent`. The question should be something like: is the distance smaller than some tolerance?
