### ISSUE TITLE
Poly.copy() does not copy unused generators

### ISSUE THREAD

**Issue by hackalog** [sympy/sympy#15798]
It looks to me like any generators that are not explicitly referenced in the a Poly expression  are dropped when performing a copy. This means `Poly.copy()` returns an unequal Poly object, which feels horribly wrong.

e.g.:
```
>>> import sympy
>>> from sympy.abc import x, y, z

>>> obj = sympy.Poly('x+y', x, y, z)
>>> o2 = obj.copy()
>>> obj == o2
False
>>> repr(obj), repr(o2)
("Poly(x + y, x, y, z, domain='ZZ')", "Poly(x + y, x, y, domain='ZZ')")
```
The same thing happens after pickling, leading to issues like those seen in https://github.com/sympy/sympy/issues/9918

In fact, it fails even the most basic:
```
>>> obj == obj.func(*obj.args)
False
```
Which should never happen : https://github.com/sympy/sympy/blob/28d913d3cead6c5646307ffa6540b21d65059dfd/sympy/core/basic.py#L704-L706

_Originally posted by @hackalog in https://github.com/sympy/sympy/issue_comments#issuecomment-455352417_

**Comment by czgdp1807** [comment]
Current status,
```python
Python 3.6.9 (default, Nov  7 2019, 10:44:02) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sympy
>>> from sympy.abc import x, y, z
>>> obj = sympy.Poly('x+y', x, y, z)
>>> o2 = obj.copy()
>>> obj == o2
True
>>> repr(obj), repr(o2)
("Poly(x + y, x, y, z, domain='ZZ')", "Poly(x + y, x, y, z, domain='ZZ')")
>>> obj == obj.func(*obj.args)
True
```
Closing for now. Please let us know if there is a need to re-open this. Thanks for the contributions.

**Comment by oscarbenjamin** [comment]
This was partially fixed in #18513 but no tests were added for this case. I'm going to reopen this as easy to fix.

This can be closed if tests are added for the fixed behaviour of copy/pickle.

**Comment by oscarbenjamin** [comment]
Some tests are in #15799 which could be revived.

**Comment by etaash** [comment]
I would like to work on this

**Comment by galbwe** [comment]
Hi. I would like to pick this up if no one is currently working on it.

**Comment by galbwe** [comment]
Adding tests for this in [PR 19550](https://github.com/sympy/sympy/pull/19550).

**Comment by atharva-bhange** [comment]
I think this issue can be closed right as the tests are written and pr is merged. @oscarbenjamin @asmeurer

**Comment by oscarbenjamin** [comment]
Yes it can be closed. Thank you for pointing this out!
