### ISSUE TITLE
Simplify the igcd method

### ISSUE THREAD

**Issue by oscargus** [sympy/sympy#15839]
In #15837 there was a suggestion in a review comment to simplify the `igcd`method (which wasn't really part of that pull request). Hence, there is a more or less ready solution that should be tested etc.

Although, I think the logic of `igcd` can be simplified a bit. The code seems to have some redundant checks:

https://github.com/sympy/sympy/blob/11e57159cb8bcaa1a75e1bf2119430f63d2f3815/sympy/core/numbers.py#L179-L201

The above code can be reduced to something like:
```
    if 1 in args:
        a = 1
        all(as_int(arg) for arg in args)
    else:
        a = abs(as_int(args[0]))
        for arg in args[1:]:
            b = as_int(arg)
            if b == 0:
                continue
            if b < 0:
                b = -b
            a = igcd2(a, b)
    return a
```

_Originally posted by @sidhantnagpal in https://github.com/sympy/sympy/pull/15837#issuecomment-457292210_

**Comment by supreet11agrawal** [comment]
I am taking up this issue is it's okay. @oscargus

**Comment by supreet11agrawal** [comment]
Sorry, I forgot to enter "NO ENTRY" in release notes. Tell me how to fix it @oscargus .

**Comment by supreet11agrawal** [comment]
I have done the necessary changes. Kindly review
