### ISSUE TITLE
regression: `Ne` simplifies incorrectly

### ISSUE THREAD

**Issue by cbm755** [sympy/sympy#15847]
Consider
```
a = Ne(x*(x+y), x**2 + x*y)
```
Before fd63f10ec66c437513bdfd983ce4d62ae7747373, `simplify(a)` gave False.  Now it gives True

I think it should be False because `Eq(a.lhs, a.rhs)` should (and does) simplify to True.  `Ne` is mathematical inequality, not structural inequality.

CC @smichr

**Comment by RituRajSingh878** [comment]
I would like to work.

**Comment by jmig5776** [comment]
@smichr I have query that what should `simplify(x**2 + x*y)` return. Now it is returning `x*(x + y)` but i think it should return `x**2 + x*y` unless and untill it is known that the given symbols hold ditributivity i.e  it is surely true.

**Comment by jmig5776** [comment]
`a.canonical` is `Ne(x*(x + y), x**2 + x*y)`

**Comment by RituRajSingh878** [comment]
@jmig5776  you can go through simplify doc for your answer. There is a definition defined for simplify--"Nonetheless, especially for interactive use, or when you don’t know anything about the structure of the expression, simplify() tries to apply intelligent heuristics to make the input expression “simpler”. "


> @smichr I have query that what should `simplify(x**2 + x*y)` return. Now it is returning `x*(x + y)` but i think it should return `x**2 + x*y` unless and untill it is known that the given symbols hold ditributivity i.e it is surely true.

**Comment by jmig5776** [comment]
Thanks @RituRajSingh878 
I think the below `_eval_simplify` function of class `Unequality` should `return not eq` because if the equality holds then the function should return that this Unequality does'nt hold true.
```
def _eval_simplify(self, ratio, measure, rational, inverse):
        eq = Equality(*self.args)._eval_simplify(
            ratio, measure, rational, inverse)
        if isinstance(eq, Equality):
            eq = self.func(*eq.args)
        return eq
```

**Comment by RituRajSingh878** [comment]
> I think the below `_eval_simplify` function of class `Unequality` should `return not eq` because if the equality holds then the function should return that this Unequality does'nt hold true.
> 
> ```
> def _eval_simplify(self, ratio, measure, rational, inverse):
>         eq = Equality(*self.args)._eval_simplify(
>             ratio, measure, rational, inverse)
>         if isinstance(eq, Equality):
>             eq = self.func(*eq.args)
>         return eq
> ```
> 

yup I checked it and I am currently trying to resolve.
Thanks, @jmig5776

**Comment by RituRajSingh878** [comment]
But I also solved.

**Comment by cbm755** [comment]
There is nothing wrong with more than one person doing a PR for the same issue.  Sometimes that will help everyone find the best solution.  And there is always need for constructive review.
