### ISSUE TITLE
`polytope_integrate`: Polygon vertex order assumption

### ISSUE THREAD

**Issue by jgersti** [sympy/sympy#15843]
The `Polygon` class has a positive area if the vertices are in ccw order. In contrast the default behaviour of `polytope_integrate` is given the same polygon that the integral of, for example, the one function is negative.

This inconsistent behaviour is especially noticeable because the `polytope_integrate` docs refer to the `Polygon` class docs which state "ccw => positive area". Only the API section gives an implicit statement that cw order is assumed.

In addition the reordering algorithm is apparently broken on debian 9 + python3.5.3 + sympy1.3
```
Traceback (most recent call last):
  File "/home/xxx/yyy/jump2d.py", line 41, in <module>
    B = simplify(polytope_integrate(_D, p0, clockwise=True))
  File "/home/xxx/.local/lib/python3.5/site-packages/sympy/integrals/intpoly.py", line 67, in polytope_integrate
    poly = point_sort(poly)
  File "/home/xxx/.local/lib/python3.5/site-packages/sympy/integrals/intpoly.py", line 1012, in point_sort
    n = len(poly)
TypeError: object of type 'Polygon' has no len()
```

**Comment by sharma-kunal** [comment]
I will be looking up on the issue.

**Comment by sharma-kunal** [comment]
@jgersti Can you please share the code of what were you trying to do. Especially the arguments passed.

**Comment by jgersti** [comment]
Here is the condensed source file which shows the second issue. The expected output is three times `1`.
[issue15843.py.txt](https://github.com/sympy/sympy/files/2796186/issue15843.py.txt)

(The first output might be because of other issues with the integration algotithm itself.)
