### ISSUE TITLE
summation(x**y*y, (y, -oo, oo)).doit() hangs in infinite loop

### ISSUE THREAD

**Issue by oscargus** [sympy/sympy#15852]
```
from sympy import symbols, summation, oo
y = symbols('y', integer=True)
x = symbols('x')
summation(x**y*y, (y, -oo, oo)).doit()
```

Hangs. The reason seems to be that `And(Abs(x) < 1, Abs(1/x) < 1)` is not evaluated to `False` here (which it should be possible to do as far as I can tell) and that instead the code goes into an infinite loop.
https://github.com/sympy/sympy/blob/1e999fc5159b830a9872b86675bc5f3692a9c1be/sympy/concrete/summations.py#L1176-L1179

**Comment by RituRajSingh878** [comment]
I want to work on this.
For x=2 it is returning the same expression so the problem is with x as what you say.

**Comment by jmig5776** [comment]
I would also like to work on this issue.

**Comment by asmeurer** [comment]
Even if it doesn't evaluate it shouldn't go into an infinite loop.

**Comment by asmeurer** [comment]
There should be a closed-form result, the same as `summation(x**n*n, (n, -oo, 1)) + summation(x**n*n, (n, 0, oo))`.

**Comment by oscargus** [comment]
I think the "best" way would be to sort out that `And(Abs(x) < 1, Abs(1/x) < 1)` evaluates to `False`. At least I cannot see any reason why it should not evaluate to that. Even if x is `-oo` or 0 and therefore sympy is hesitant to make any assumptions, the other should always be False.

**Comment by oscargus** [comment]
There is an approach by @jmig5776 in #15855 Also, @RituRajSingh878 said he wants to work on it. However, I guess that there are many possible solutions. The approach by @jmig5776 solves the hang issue, but it is unclear if it has other side effects.

Yes, it is most likely related to the problem that the `And` statement can not be determined to be `False`. 

I think a careful analysis of the code is required, but as I remember, the code tries to solve it as two summations as you did and then tries to figure out if they can be merged to one expression. This is where it seems to go wrong.

**Comment by jmig5776** [comment]
Yeah I tam trying the get the required answer rather than just getting returned the unevaluated integral.

**Comment by divyanshu132** [comment]
@asmeurer @oscargus in the definition of eval_sum_hyper() in /sympy/concrete/summations.py we are calling Sum(f, (i, a, b)) to calculate the old_sum but the value of none of the variables f="x**y*y", i="y", a="-oo", b="oo" is changed in any call that's why it takes infinite time!!
