### ISSUE TITLE
sym2poly bug

### ISSUE THREAD

**Issue by GoSim1** [sympy/sympy#15862]
the following code gives me an error message (octave):

syms s
A=1/s
[n d ]=numden(A)
sym2poly(n)

error message:
error: ss(1): out of bound 0
error: called from
    sym2poly at line 88 column 7

so sym2poly can't handle when the polynomial is a constant. I'm using it in an automatic script and need to be able to handle all types of polynomials. It should be an easy fix. Kind regards.

**Comment by cbm755** [comment]
I can confirm its an octsympy bug, please do file downstream so I don't forget about it...

**Comment by cbm755** [comment]
filed downstream

**Comment by cbm755** [comment]
FYI, fixed downstream
