### ISSUE TITLE
`octave_code` invalid code for complex expression

### ISSUE THREAD

**Issue by cbm755** [sympy/sympy#15870]
```
>>> a = 3*(1 - I)**2
>>> N(a)
-6.0*I

>>> octave_code(a)
'-3*1i*(1 - 1i)^2i'
```
That doesn't look right.  And its not:
```
octave:30> -3*1i*(1 - 1i)^2i
ans = 9.2211 - 11.101i
```

**Comment by oscargus** [comment]
I get `'3*(1 - 1i)^2'`. Can you try this in a "clean" python terminal? I have noted that once an error occurs, things tend to go wrong after that...

**Comment by cbm755** [comment]
I'm sorry, now I cannot reproduce it either, on 1.3 or master.  So either I was on some ancient branch or I caching gremlins...

(I've still got the terminal open where it happens but cannot produce it elsewhere)
