### ISSUE TITLE
Print MatrixSymbol boldface?

### ISSUE THREAD

**Issue by Upabjojr** [sympy/sympy#15871]
What about printing `MatrixSymbol` objects boldface?

In LaTeX this would be `\mathbf{M}`, similar logic could be applied to the pretty printer.

Boldface matrix symbols are easier to distinguish from scalar symbols. Furthermore it's the convention usually employed in books and papers.

**Comment by oscargus** [comment]
Good idea! (For the record, for MathML one would write `<mi mathvariant="bold">M</mi>`.)

**Comment by oscargus** [comment]
I'll give this a go once #15842 is merged (as there will be obvious conflicts otherwise).

**Comment by oscargus** [comment]
I called this parameter `mat_symbol_style` in #15877 with the options "bold" and "plain". Does this make sense? Are there more variants?
