### ISSUE TITLE
SolveSet: nonlinsolve return EmptySet() - Wrong Result

### ISSUE THREAD

**Issue by sharma-kunal** [sympy/sympy#15888]
I was trying to solve two non-linear equations

```
eq1 = (x+y)**2 - 9
eq2 = x**2 - y**2 -3/4
nonlinsolve((eq1, eq2), (c1, c2))
```

But it returns

```
EmptySet()
```

I tried figuring it out and found that 

```
is_zero_dimensional(polys, symbols):
```

this function return False. Can someone explain me what this function does ?

**Comment by jksuom** [comment]
That function is expected to return True if the solution set is finite, as it is in this example. There must be a bug in the implementation.

**Comment by sharma-kunal** [comment]
You mean it just checks if the solution set is finite without actually finding the solutions.

**Comment by ethankward** [comment]
Note that this works as expected if you use a rational value for `3/4` instead of a float.

**Comment by sharma-kunal** [comment]
yes you are right, I converted 3 to a sympy object using S(3) and the answer is correct.
So is that a bug or it was meant to work so.

**Comment by ethankward** [comment]
It's still a bug since SymPy is generally expected to work with floats.

**Comment by jksuom** [comment]
This is probably a case where floats have to be converted to rationals during computation.

**Comment by sharma-kunal** [comment]
using solve() gives the result even if I don't take rational(3,4) but gives answer in decimals.
Do you think same should be applied in solveset also.

**Comment by sharma-kunal** [comment]
As suggested by @ethankward, it works for rational value and sometimes it also gives correct result for equations in real domain. So I have applied a check for if the algo returns empty result with equations being in real domain than a `NotImplementedError` must be raised with proper details as suggested by @jksuom
