### ISSUE TITLE
dsolve doesn't know order-reducing substitutions

### ISSUE THREAD

**Issue by oscarbenjamin** [sympy/sympy#15881]
If an ODE only involves derivatives of the dependent variable then it is possible to use a substitution to to reduce the order of the ODE. This usually makes it easier to solved but `dsolve` doesn't know how to do it yet.

Here's an example:
```julia
In [1]: x = Symbol('x')                                                                                                                        

In [2]: f = Function('f')                                                                                                                      

In [3]: eq = f(x).diff(x, 2) + x * f(x).diff(x)**2                                                                                             

In [4]: eq                                                                                                                                     
Out[4]: 
            2     2      
  ⎛d       ⎞     d       
x⋅⎜──(f(x))⎟  + ───(f(x))
  ⎝dx      ⎠      2      
                dx       

In [5]: dsolve(eq)                                                                                                                             
---------------------------------------------------------------------------
NotImplementedError                       Traceback (most recent call last)
```

Since `f(x)` only appears as a derivative we can use the substitution `g(x) = f(x).diff(x)` to obtain a first order ODE:
```julia
In [6]: g = Function('g')                                                                                                                      

In [7]: eq_g = g(x).diff(x, 1) + x * g(x)**2                                                                                                   

In [8]: eq_g                                                                                                                                   
Out[8]: 
   2      d       
x⋅g (x) + ──(g(x))
          dx      

In [9]: dsolve(eq_g)                                                                                                                           
Out[9]: 
          2   
g(x) = ───────
             2
       C₁ + x 
```

This is a solution of the original ODE since
```julia
In [10]: sol = dsolve(eq_g).rhs                                                                                                                

In [12]: solf = integrate(sol, x)                                                                                                              

In [13]: solf                                                                                                                                  
Out[13]: 
      _____    ⎛         _____    ⎞       _____    ⎛       _____    ⎞
     ╱ -1      ⎜        ╱ -1      ⎟      ╱ -1      ⎜      ╱ -1      ⎟
-   ╱  ─── ⋅log⎜- C₁⋅  ╱  ───  + x⎟ +   ╱  ─── ⋅log⎜C₁⋅  ╱  ───  + x⎟
  ╲╱    C₁     ⎝     ╲╱    C₁     ⎠   ╲╱    C₁     ⎝   ╲╱    C₁     ⎠

In [14]: simplify(solf.diff(x, 2) + x*solf.diff(x)**2)                                                                                         
Out[14]: 0
```

It would be good to add a new solver in sympy/solvers.ode.py. The idea would be that the solver matches ODEs that only include on derivatives of the dependent variable. It would generate the ODE by substitution
```julia
In [15]: eq                                                                                                                                    
Out[15]: 
            2     2      
  ⎛d       ⎞     d       
x⋅⎜──(f(x))⎟  + ───(f(x))
  ⎝dx      ⎠      2      
                dx       

In [16]: eq.subs(f(x).diff(x), g(x))                                                                                                           
Out[16]: 
   2      d       
x⋅g (x) + ──(g(x))
          dx 
```
Then the solver should recursively call `dsolve` to solve *that* ODE and (if that works) integrate the result to get the solution to the original ODE.

This solver should appear in the matching order after all of the methods for linear ODEs but before the nonlinear methods (e.g. Liouville) here :[https://github.com/sympy/sympy/blob/master/sympy/solvers/ode.py#L309](https://github.com/sympy/sympy/blob/master/sympy/solvers/ode.py#L309).

**Comment by XtremeGood** [comment]
Hi, I 'm interested in fixing this bug but I' will have to see how to convert my math to symbolic computations.

**Comment by oscarbenjamin** [comment]
Hi @XtremeGood. If you want to work on this you'll need to use the latest master version of SymPy. The equation you show has two solutions under current master:
```julia
In [2]: f(x).diff(x, 1) + x * f(x).diff(x)**2                                                                                                  
Out[2]: 
            2           
  ⎛d       ⎞    d       
x⋅⎜──(f(x))⎟  + ──(f(x))
  ⎝dx      ⎠    dx      

In [3]: dsolve(_)                                                                                                                              
Out[3]: [f(x) = C₁, f(x) = C₁ - log(x)]
```

In terms of how to code this the method could be roughly as simple as
```python
eq = f(x).diff(x, 2) + x * f(x).diff(x)**2                                                                                             
new_eq = eq.subs(f(x).diff(x), g(x))                                                                                                   
if new_eq.has(f): # if new_eq has f then f appears outside of derivatives
    raise NotImplementedError
sol = dsolve(new_eq, g(x)) 
sol_f = Eq(f(x), integrate(sol.rhs, x))                                                                                               
```
The more complicated part is working out how to slot that into `dsolve`'s machinery. It needs to be split up into a matcher and a solver. The idea is that the matcher looks at the ODE and says whether this method will work. The solver later actually makes the solution. As a starting point here the matcher can just check `new_eq.has(f)`. That would need to go somewhere here:
[https://github.com/sympy/sympy/blob/master/sympy/solvers/ode.py#L1362](https://github.com/sympy/sympy/blob/master/sympy/solvers/ode.py#L1362)

Then the solver part has to be a function called `ode_<something>`, perhaps `ode_nth_order_substitution`.

**Comment by XtremeGood** [comment]
Hi @oscarbenjamin 
I will check that today.Thanks for the help.  :)

**Comment by XtremeGood** [comment]
Hi @oscarbenjamin 
For second degree non homogeneous equations there is a method called variation of parameters techniques.Also laplace transformations can solve these type of equation.Should I build such a system?

**Comment by XtremeGood** [comment]
Hi @oscarbenjamin 
Should I add a method in dsolve which which recursively try solving it for f(x).If not solvable then try substituting f'(x) and solve and return f(x).If still not then f''(x) to be substituted and so on.Will it be fine?
I still wonder why  sympy is not solving the equation by "Liouville ode" tactic already implemented.

**Comment by oscarbenjamin** [comment]
Hi again @XtremeGood.

If you add the code to match this type of ODE where I suggested then `classify_ode` will not return empty.

Perhaps you should open a new issue about the Liouville solver. The type of ODE referred to by this issue is more general than Liouville: it could be of any order.

**Comment by XtremeGood** [comment]
Hi @oscarbenjamin 
I googled about the liouville equation but couldn't find any major content.It says it has some things to do with lie groups which is not even taught in my college till even 3rd year of math course .Nevertheless for the time being I will write the recursion till maybe tomorrow and the thing you are telling is quite necessary in solving many equations,About liouville equations, I will try studying Lie groups first and try to make it work.

**Comment by XtremeGood** [comment]
Hi @oscarbenjamin 
One thing caught my mind,that if the equation contains f(x),f'(x),f''(x)etc then only the lowest order should be substituted can be substituted.To make it more clear consider eq = f(x).diff(x, 2) + x * f(x).diff(x)**2 + f(x).Now if I substitute it would make it some integro-differential equation that too non linear.It would further require complicated maths ranging from Fredholm Integral to I don't even know what it would be.
I

**Comment by oscarbenjamin** [comment]
This method should not be used if f(x) appears outside of derivatives. In dsolve it's not actually necessary to return NotImplementedError. We just need to test for this when deciding if the method matches the ODE. I recommend just to test `if eq.subs(...).has(f(x))`.

**Comment by XtremeGood** [comment]
Done it, please see,I do have a github account but 'm not familiar to merge,pull requests etc.
https://github.com/XtremeGood/Sympy-Contrib/blob/master/Sympy%20Edit.py

**Comment by XtremeGood** [comment]
Oh sorry I closed it by mistake.There was some message from sympy bot to edit it and I messed it up.Posting again.

**Comment by ShubhamKJha** [comment]
I would like to work on this issue. Is there any lead on the way it should be worked upon?

**Comment by oscarbenjamin** [comment]
This is mostly done in #15992

**Comment by ShubhamKJha** [comment]
Thanks @oscarbenjamin

**Comment by XtremeGood** [comment]
Am I a part of this merge?

**Comment by asmeurer** [comment]
Yes, if you look the first commit on that pull request is your commit.

**Comment by XtremeGood** [comment]
Thanks @asmeurer, @oscarbenjamin and  @smichr for the great help in first merge!!

**Comment by oscarbenjamin** [comment]
Thanks @XtremeGood for your help!

There are many more issue with dsolve if you look...
