### ISSUE TITLE
ASCII printer generates Unicode (at least in physics.vector)

### ISSUE THREAD

**Issue by oscargus** [sympy/sympy#15884]
As noted in https://github.com/sympy/sympy/pull/15849 the printing function in physics.vector adds dots on top of variables to indicate derivatives (Newton style). However, it seems like these are not properly converted to ASCII later when the ASCII version is derived. This should be sorted out in pretty_symbology and replace the dots with a proper number of `'`.

Note that there are currently tests that will have to be changed, e.g. https://github.com/sympy/sympy/blob/cb8a524e930266fe2f4cda39d7d0b1523c4fa38b/sympy/physics/vector/tests/test_printing.py#L239

where the expected result should be `'omega\'\'\' n_x'` (or `"omega''' n_x"` which may be easier to read and type...).

**Comment by shivanikohlii** [comment]
I'll be working on this bug!

**Comment by oscargus** [comment]
Great @shivanikohlii !

I was checking out the code for another reason and noted that it said:
https://github.com/sympy/sympy/blob/24c34f0e4ceb34b316dbd315df8eebca5ce33693/sympy/printing/pretty/pretty_symbology.py#L199-L200

which should be compared to
https://github.com/sympy/sympy/blob/24c34f0e4ceb34b316dbd315df8eebca5ce33693/sympy/physics/vector/printing.py#L195-L196

I am not sure if it is related (and possibly even solves it), but please change the first code to use the correct combining accents as shown below. (Basically the first code use two times double dots while there is a combining accent with four dots.)

**Comment by oscargus** [comment]
I think that the easiest way to do this is to simply use the property `_use_unicode` which is inherited from `PrettyPrinter`

https://github.com/sympy/sympy/blob/24c34f0e4ceb34b316dbd315df8eebca5ce33693/sympy/printing/pretty/pretty.py#L50-L51

and then do something different.

You can ignore the comment about the combining accents above. I will fix that in another PR since it requires a bit more thinking (right now, the accents are put on the next character, usually a space, rather than on the symbol name, so just performing the change above is not enough to make it work "properly").
