### ISSUE TITLE
Canonical and pi

### ISSUE THREAD

**Issue by oscargus** [sympy/sympy#15899]
```
>>> from sympy import symbols, pi
>>> x = symbols('x')
>>> (x > 2).canonical
x > 2
>>> (x > pi).canonical
pi < x
>>> (pi < x).canonical
pi < x
>>> (-pi > -x).canonical
-pi > -x
>>> (-x < -pi).canonical
-pi > -x
>>> (x > -2).canonical
x > -2
>>> (x > -pi).canonical
x > -pi
>>> (x > pi/2).canonical
x > pi/2
>>> (pi/2 < x).canonical
x > pi/2
>>> (-pi < x).canonical
x > -pi
```

For all these expressions except the second to fifth, the method does what it is supposed to do, put the symbol on the left hand side and the number of the right hand side. Any idea @smichr ? (The same hold for `Eq`, just happened to try with `<` and `>`)

It messes things up a bit for #15898 (I do not think that it may be sorting things out directly anyway, but I ran across it trying to figure out to get some other cases to simplify as well and with the current behavior there is no way to simplify a piecewise with `Eq(x, pi)`).

**Comment by smichr** [comment]
> Any idea

Probably just trying to be as fast as possible and not get bogged down with things that aren't very "simple". It could be that any `foo` such that `foo.is_number is True` could be put on the rhs. I knew about the difference when working on that. I don't remember now the rationale for not using `number` instead of `Number`. Maybe a diff would have a comment?

**Comment by jmig5776** [comment]
@oscargus, @smichr What  is exactly needed to be done here?

**Comment by oscargus** [comment]
@smichr I didn't see anything like that in the diff. It wasn't really clear how the earlier code handled that case either.

@jmig5776 Ideally, all `Relational` should look identical in their canonical form if they express the same thing, so `x <= 2*y`, `y >= x/2`, `-2*x >= -4*y`, and `x - 2*y <= 0` should all give the same result.

It is less important which, but most likely something like the first, so at least one term doesn't have an integer coefficient in front of it and all others are >= 1. There is of course a bound on how well this can be done. We would still like to keep it symbolic and no point in e.g. evaluating large integrals just to figure out if they are larger than one or not.

The main "problem" at the moment is that `pi` is not treated as a "number" (as it is not a `Number`, while e.g. `pi/2` is it seems).

I think that this can be obtained if rather than putting values which are `Number`s on the rhs, one put expressions with free variables to the lhs. The rest should stay though, so that the expressions are ordered in the same way etc. 

Further improvements may include:
- [ ] `(-x <= y).canonical` and `(x >= -y).canonical` giving the same result. Here one need to decide on either having a (leading) positive coefficient on the lhs or always using `<=` or `<`. One of them can always be satisfied. I think leading positive coefficient, but maybe `<=`/`<` is easier to implement. (Use the `ordered` to determine which one should be on the lhs based on whatever logic that uses and then make the relation normalized). **I think this should be included as standard.**

- [ ] In case of `Rational` (with integers) coefficients, multiply with a suitable number to get rid of the denominators.

- [ ] In case of integer coefficients >= 1, divide by the gcd of these integers.

- [ ] Move all expressions to lhs and all constants to rhs. (Drawback of this is that e.g `x - y = 0` is less readable than `x = y` in the output. Will assist the simplifications though if it doesn't matter which of these identical expressions are used.)

- [ ] In case of "identical non-integer coefficients" (e.g. `pi`), divide by a good number. (Very hard for the general case, but could be worth implementing if one can figure out a way to identify "simple symbolical numbers", `pi`, `sqrt(2)` etc.)

Clearly, there is a trade-off between time spent in making the expression canonical and how many different variants of the same expression becomes identical. One way to find a good starting point is probably to run functions which gives Piecewise results, e.g. integrals, summations, and solve equations. If a user writes very complicated expressions in inconsistent ways, it is of course useful if sympy can help, but also, somehow, less important to be able to simplify.

I will probably attempt to improve the simplification of logic expressions, for example, now `Eq(x, y) & (x <= y)` is not simplified to `Eq(x, y)`. This would be a big help for that.

**Comment by oscargus** [comment]
I have worked a bit on `simplify` for `Relational` (no ready PR yet). The gcd stuff will to some extent be handled there, so basically it is the original issue (always get constants to the rhs) and always normalize the type of relation (first point in the list) that need to be sorted out here.

**Comment by oscargus** [comment]
There is an issue in the current version of canonical:

```
>>> (-y <= y).canonical
 y <= -y
````

or rather in reversed:
```
(-y <= y).reversed
 y <= -y
```

**Comment by jmig5776** [comment]
A lot of work is needed in this issue, I am trying to understand the domain of this issue before making any suggestions or fix.

**Comment by oscargus** [comment]
I agree that it sounded a bit complicated. However, after working with #15905 now, many of those things happens in the simplification rather than here I have realized. Hence, I believe that it should be quite feasible to implement something that does the following:

Assume that each relation have a left hand side, `lhs`, and a right hand side `rhs`. No need to move terms back and forth, that will `simplify`handle. I will use <=> do denote a comparison operator.

The following assumptions should hold for all expressions:

1) expr and number gives: expr <=> number (so expr will be rhs, number will be lhs, this is not always working now)
2) expr and expr gives expr1 <=> expr2 where the order is determined by `ordered`

3) For == and != the sign is selected such that the leading symbol of expr1 does not start with a `-` (not sure how easy this is to determine)
4) For <, <=, >, >= only < and <= are used, no possibility to change the sign

Examples: 

`pi == x` gives `x == pi`, 1)
`pi  >= -x` gives `-x <= pi`, 1), 4)
`pi <= -x` gives `x <= -pi`, 1), 4)
`y == x` gives `x == y`, 2) (ordered sort in alphabetical order I think)
`y != -x` gives `x != -y`, 2), 3)
`-y  >= -x` gives `-x <= -y`, 2), 4)
`x >= y` gives `-x <= -y`, 2), 4)

Note that most of this is already implemented. The only things are the special case of `pi` (and probably some other constants), and make sure that only < and <= is used in the canonical inequalities.

**Comment by ShubhamKJha** [comment]
The ambiguity is happening because ```pi``` is technically not a number and hence doesn't include is_Number property. Infact, ```log(4), sin(10), exp(3)``` these would also fail the requirements for rhs.
```
>>> log(x) <= log(2)
>>> _.canonical
>>> log(2) >= log(x)
```
A better fix would be to check if ```rhs.free_symbols``` is empty. This would make the rhs free of any variables.

**Comment by oscargus** [comment]
@ShubhamKJha I also think that is better. Thanks!

There is now a PR #16004 that have implemented something which at least solves this problem and I think more as well.

**Comment by smichr** [comment]
Could `-x <= pi` be made `x >= -pi`?

**Comment by oscargus** [comment]
Yes, but somehow one will have to select between having either only </<= (or >/>=) or lhs not starting with a minus to get consistent canonical relations. Now, I selected the </<= approach (partly because simplifications becomes easier if there are fewer variants to test, partly because it seemed like extracting sign may be a bit time consuming in certain situations, maybe I'm wrong here though).

**Comment by oscargus** [comment]
Also, `(-x <= pi).reversedsign` gives `x >= pi` if explicitly needed for e.g. printing. I can change the default, but based on matching etc, I think it makes sense to go with direction rather than sign. (I also think that there are some ambiguous cases when it comes to sign, but do not remember exactly now. This evolved during the development.)

**Comment by oscargus** [comment]
@smichr My memory is clearly limited. Turns out that I went for the no starting minus on the left-hand side approach. So `(-x <= pi).canonical` will indeed become `x >= -pi` in #16004.

This means that I should make sure to reverse all `>` and `>=` inequalities if I should be able to use fewer patterns.
