### ISSUE TITLE
Solve of quartic with numeric coefficients gives Piecewise

### ISSUE THREAD

**Issue by oscarbenjamin** [sympy/sympy#15896]
From #15090.

Solving a quartic with known numeric coefficients leads to a Piecewise solution (with conditions in terms of pure numbers):
```python
solve(i*x**4 + x**3 + x**2 + 1)
```
(The output is long so omitted.)

Each solution is given as piecewise
```julia
In [71]: [type(s) for s in solve(i*x**4 + x**3 + x**2 + 1)]                                                                                    
Out[71]: [Piecewise, Piecewise, Piecewise, Piecewise]
```

An example of one of the piecewise conditions
```julia
In [85]: solve(i*x**4 + x**3 + x**2 + 1)[2].args[0].args[1]                                                                                    
Out[85]: 
               2           
 3    (3/8 - ⅈ)    15⋅ⅈ    
─── - ────────── + ──── = 0
256       12        16     
```
This condition is always false.

**Comment by oscargus** [comment]
Isn't this related to complex values really being polynomials in `I`? Hence, the numerical coefficients must be complex?

Interesting with the empty fractional though.a

**Comment by smichr** [comment]
As I recall, rather than return NotImplemented when a decision can't (easily) be made as to whether a certain set of conditions or other applies to the 4 roots, the possibilities are enumerated and returned in a Piecewise. That it survives is testament to the fact that some condition(s) didn't evaluate and a decision was not made. If you run simplify on the conditions they will simplify; perhaps this should be done automatically if all coefficients are numbers:
```
>>> [simplify(c) for i in solve(I*x**4 + x**3 + x**2 + 1) for e,c in i.args]
[False, True, False, True, False, True, False, True]
```

**Comment by smichr** [comment]
(Even a simple `_mexpand` from sympy.core.function would be a sufficient level of simplification.)

**Comment by oscargus** [comment]
Hmm, looking at this now. 

Is that 
```
solve(i*x**4 + x**3 + x**2 + 1)
```
or
```
solve(I*x**4 + x**3 + x**2 + 1)
```
?

**Comment by oscarbenjamin** [comment]
It should be `I` rather than `i`. The output here was changed in d3eab468768801dff2c810a5dc5d6d446d6db01c from #19485. I guess this is because the polynomial now factorises:
```python
In [2]: factor(I*x**4 + x**3 + x**2 + 1)
Out[2]: 
          ⎛ 3          ⎞
ⅈ⋅(x - ⅈ)⋅⎝x  - ⅈ⋅x + 1⎠
```
If we change one of the coefficients so that it doesn't factorise (e.g. `I*x**4 + 2*x**3 + x**2 + 1` then we also would have a Piecewise previously but that output was improved by 34b4723a7c40c527343875328570b170d83675cb from https://github.com/sympy/sympy/pull/21276.

I guess either of those two commits could have closed this issue.
