### ISSUE TITLE
Matching failure for simple linear expression

### ISSUE THREAD

**Issue by oscarbenjamin** [sympy/sympy#15907]
This match works:
```julia
In [20]: x, y, z = symbols('x y z')                                                                                                            

In [21]: a = Wild('a')                                                                                                                         

In [22]: b = Wild('b')                                                                                                                         

In [23]: (x + (y-1)*z).match(a*x + b*z)                                                                                                        
Out[23]: {a: 1, b: y - 1}
```
However removing the `a` Wild from the pattern means it longer matches:
```julia
In [24]: (x + (y-1)*z).match(x + b*z) 
```

**Comment by pathakcodes** [comment]
I want to work on it. Please assign me this.

**Comment by oscargus** [comment]
@pathakcodes it seems that one can only assign people that are somehow "members" of sympy. Not sure how it works in detail, but your name does not show up when trying to assign you, not even typing your name works, despite having commented on the issue.

**Comment by pathakcodes** [comment]
OK , So i am working and will send PR . PLease check how to assign me this.Thanks

**Comment by pathakcodes** [comment]
@oscargus sir , I have checked the match function as well as associated functions. I think it requires one more try till then can you guide me in right direction or point out the problem part.
<pre>&gt;&gt;&gt; (x + (y-1)*z).match(a*x + (y-1)*z)
{a_: 1}
</pre>
above thing works but ,
<pre>&gt;&gt;&gt; (x + (y-1)*z).match(x + b*z)
</pre>
this gives a none  or no match instead of 
`b : (y-1)`

**Comment by oscarbenjamin** [comment]
Hi @pathakcodes, yes that's the problem. Have you looked through the matching code to find the solution?

I would probably start by following through what happens when you call match in a debugger.

**Comment by pathakcodes** [comment]
@oscargus Yes sir , I have seen the core module match part . I think I had to check more with "Sympify".
Ok , will get back once problem is spotted . Can you guide where problem could be. Thanks

**Comment by smichr** [comment]
It would be good to see if this works with #19261.
