### ISSUE TITLE
Rademacher Distribution not added to sympy docs

### ISSUE THREAD

**Issue by supreet11agrawal** [sympy/sympy#15904]
Description of sympy.stats.Rademacher from https://github.com/sympy/sympy/blob/master/sympy/stats/frv_types.py#Rademacher is not added to the docs https://docs.sympy.org/dev/modules/stats

**Comment by supreet11agrawal** [comment]
I see a similar problem with https://github.com/sympy/sympy/blob/master/sympy/stats/drv_types.py . Only Geometric and Poisson distribution are added to the docs

**Comment by divyanshu132** [comment]
I'll take this
