### ISSUE TITLE
Function for proper divisors

### ISSUE THREAD

**Issue by adhoc-king** [sympy/sympy#15927]
A function returning the list of proper divisors seems to be missing

**Comment by adhoc-king** [comment]
#15928

**Comment by jhanwar** [comment]
I am working on it.

**Comment by adhoc-king** [comment]
@jhanwar Have a look at this PR #15928 
Kindly suggest/make changes there

**Comment by XtremeGood** [comment]
Hi if this still needs a solution I had previously solved problems on project euler in python which requires such programs as requirement in solving many problems.At that time I had not much idea of sympy so I builded these number theory stuff from scratch.So please tell me if it needs a fix.
