### ISSUE TITLE
Function for perfect, deficient, abundant numbers

### ISSUE THREAD

**Issue by adhoc-king** [sympy/sympy#15926]
There should be a separate function for checking whether a number is perfect, deficient or abundant. If you liked this idea then I can add a pull request.

- [x] perfect
- [ ] deficient
- [ ] abundant

**Comment by asmeurer** [comment]
I think it would be good to have. 

For perfect numbers, there are only [51 known ones](https://en.wikipedia.org/wiki/Mersenne_prime), so we could just check against a list. I don't know if there is an efficient way to test if a number is abundant.

**Comment by adhoc-king** [comment]
I think ntheory/factor_.py would be the appropriate place

**Comment by adhoc-king** [comment]
@asmeurer I can think of the following heuristics for this.
1. All primes and its powers are deficient.
2. Every multiple of abundant and perfect number is abundant.

**Comment by jhanwar** [comment]
This will need some changes. Please suggest. I have checked outputs. It takes some time to calculate 40th Perfect Numbers to 51th Perfect Numbers. but We can show it with symbol. 
I also have test cases for Perfect Numbers. I can add them if you want to.
I have not added comments yet. Comments can also be added.

**Comment by divyanshu132** [comment]
I'm working on deficient and will try to cover abundant as well.
