### ISSUE TITLE
series of sin(x) around x=pi wrong

### ISSUE THREAD

**Issue by terben** [sympy/sympy#15931]
It seems that a simple series expansion of `sin(x)` around `x=pi` does not give the correct answer:

```
In [1]: import sympy as sp

In [2]: x = sp.symbols('x')

In [3]: sp.series(sp.sin(x), x, sp.pi)
Out[3]: pi + (x - pi)**3/6 - (x - pi)**5/120 - x + O((x - pi)**6, (x, pi))

In [4]: sp.__version__
Out[4]: '1.3'

```
The leading term of the series should be `-(x-pi)` and not `pi`!

**Comment by oscarbenjamin** [comment]
It's showing up a little strangely. The `-x` is over by the `O`.

**Comment by terben** [comment]
Thanks! Great that it is only a display issue and no real bug!

**Comment by oscarbenjamin** [comment]
No problem. So can you close this or do you think that should be fixed?

**Comment by terben** [comment]
From my side we can close it. Fixing it at some point is certainly a *nice to have* but not essential.
