### ISSUE TITLE
arg() expression should evaluate

### ISSUE THREAD

**Issue by lxkain** [sympy/sympy#15945]
Hi,

let's say I have

X = 𝐴/(2𝑖𝜋𝐹+𝑎)

Currently, if I do arg(X) I obtain

arg(𝐴/(2𝑖𝜋𝐹+𝑎))

in other words, it just wraps the original expression. However, shouldn't this evaluate to

sym.atan(sym.im(X)/sym.re(X))

which is

−atan((2𝜋𝐹)/𝑎)

?

**Comment by oscarbenjamin** [comment]
The simplification `arg(X) = atan(im(X)/re(X))` isn't valid without assumptions on `X`:
[https://en.wikipedia.org/wiki/Argument_(complex_analysis)#Computing_from_the_real_and_imaginary_part](https://en.wikipedia.org/wiki/Argument_(complex_analysis)#Computing_from_the_real_and_imaginary_part)

**Comment by lxkain** [comment]
Does it make a difference that I issued

A, t, a, F = sym.symbols('A t a F', real=True, positive=True)

?

**Comment by jksuom** [comment]
You could try using `arg(X).rewrite(atan2)` to introduce atan.

**Comment by lxkain** [comment]
Thank you, I tried rewrite(atan), which didn't work, but atan2 works!
