### ISSUE TITLE
Matrix exponential for dsolve

### ISSUE THREAD

**Issue by oscarbenjamin** [sympy/sympy#15946]
Previous PRs: #15449, #14445 , #14338 , #14536 , #11510 , #9235
Issues: #15574, #15474, #15407, #14312

Currently the only n equations ODE system solver in dsolve is for handling linear constant coefficient homogeneous ODE systems and is broken for non-diagonalizable systems.

The class of ODEs solved is `dx/dt = A x` where `x` is a vector and `A` a constant matrix. The solution to these ODEs is straight-forward and comes from the matrix exponential: `x = exp(A t) x0` with `x0` the initial condition vector.

A single (fixed) n equation solver could solve all of these classes of equations but currently there are multiple solvers for different special cases:
1. `_linear_2eq_order1_type1`
2. `_linear_3eq_order1_type1`
3. `_linear_3eq_order1_type2`
4. `_linear_3eq_order1_type3`
5. `_linear_neq_order1_type1`

These should be deleted and combined into a single fixed neq solver.

Multiple PRs have attempted to fix the n equations solver by adding the matrix exponential to the dsolve module. Looking now I see that it is possible to directly calculate the exp of a matrix but it doesn't always do sin/cos:
```julia
In [12]: M = Matrix([[0, 1], [-1, 0]])                                                                                            

In [13]: M                                                                                                                        
Out[13]: 
⎡0   1⎤
⎢     ⎥
⎣-1  0⎦

In [14]: exp(M*t)                                                                                                                 
Out[14]: 
⎡   ⅈ⋅t    -ⅈ⋅t         ⅈ⋅t      -ⅈ⋅t⎤
⎢  ℯ      ℯ          ⅈ⋅ℯ      ⅈ⋅ℯ    ⎥
⎢  ──── + ─────    - ────── + ───────⎥
⎢   2       2          2         2   ⎥
⎢                                    ⎥
⎢   ⅈ⋅t      -ⅈ⋅t      ⅈ⋅t    -ⅈ⋅t   ⎥
⎢ⅈ⋅ℯ      ⅈ⋅ℯ         ℯ      ℯ       ⎥
⎢────── - ───────     ──── + ─────   ⎥
⎣  2         2         2       2     ⎦
```
In #15449 I found that it was more useful to have the Jordan form of the matrix exponential and wrote a function to compute that with sin/cos rewriting. Maybe that could go somewhere in matrices rather than ode.py...

**Comment by shikhar2333** [comment]
Can you tell what's the name of the n-equation solver which is currently implemented?

**Comment by oscarbenjamin** [comment]
It's called `_linear_neq_order1_type1`

**Comment by mijo2** [comment]
@oscarbenjamin What should be done next? Making a general function for solving a system of ODEs in ```systems.py``` or moving on to working for a new solver?

**Comment by oscarbenjamin** [comment]
I think that this issue can be closed now but perhaps you could open a new issue to track progress of the work described in the roadmap.

I would say that the next step is to implement whichever part it is that can eliminate as much as possible of the old code. I'm not sure if that's the non-homogeneous case or the non-constant coefficient homogeneous case.

**Comment by mijo2** [comment]
@oscarbenjamin Ok, I would open a new issue to track the progress.

**Comment by mijo2** [comment]
@oscarbenjamin This issue can be closed now. The new issue that keeps tracks of the changes in ```systems.py```: https://github.com/sympy/sympy/issues/19178
