### ISSUE TITLE
Wrong result from summation

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#15943]
```py
>>> Sum(binomial(n, k)*factorial(n - k), (k, 0, n)).doit()
zoo*(n + 1)*binomial(n, n + 1)*lowergamma(n + 1, 1) + E*factorial(n)
```

The result is clearly wrong, as it has a `zoo` term even though the summation is finite.

**Comment by smichr** [comment]
> come from the factorial being negative

I saw this when working on derivatives. The code was using the zoo result to essential cancel out terms rather than minding whether the factorial argument was negative and avoiding those terms.

**Comment by jksuom** [comment]
`eval_sum_hyper` evaluates finite sums by computing [two infinite sums](https://github.com/sympy/sympy/blob/master/sympy/concrete/summations.py#L1159-L1160) and taking their difference. In this case, the computation is doomed as both sums are divergent:
```
>>> hypersimp(binomial(n, k)*factorial(n - k), k)
1/(k + 1)
```
Apparently, the helper function `_eval_sum_hyper` should return `None` for divergent sums.

**Comment by jksuom** [comment]
Correction: The series are not divergent. `zoo` comes from the computation of the second series starting from `k = n + 1`. That makes `factorial(n - k)` infinite on [this line](https://github.com/sympy/sympy/blob/master/sympy/concrete/summations.py#L1139). Probably `f` should be simplified before attempting `f.subs(i, 0)`.

**Comment by oscargus** [comment]
Look at https://github.com/skirpichev/diofant/commit/271d86a634a87af8640e0023f2a3335a916ace89 to see one way to fix(?) it.

**Comment by asmeurer** [comment]
It should perhaps use similar logic to `_eval_interval`. Maybe even use `f._eval_interval(i, None, 0)`.

**Comment by divyanshu132** [comment]
@jksuom I have tried `simplify(f) `and that resolves the problem of `zoo` for `Sum(binomial(n, k)*factorial(n - k), (k, 0, n)).doit() `. The result is `-E*(n + 1)*factorial(n)*lowergamma(n + 1, 1)/factorial(n + 1) + E*factorial(n)`

**Comment by jksuom** [comment]
It would probably suffice to use `combsimp` instead of full `simplify` that is much more expensive. That could be applied to the argument `f` of `eval_sum_hyper`.

**Comment by oscargus** [comment]
Or `limit` instead of `_eval_interval`?

**Comment by asmeurer** [comment]
[`_eval_interval`](https://github.com/sympy/sympy/blob/38174f7373a86ac92527dd7120cd92c668a38560/sympy/core/expr.py#L834) is just a wrapper that tries `subs` and falls back to `limit` if it returns nan or infinity (it also has some singularity logic, but that isn't relevant if only one value is evaluated).
