### ISSUE TITLE
Integral inconsistently forces evaluation of integrals in the integrand

### ISSUE THREAD

**Issue by oscarbenjamin** [sympy/sympy#15956]
I'm not sure what the right behaviour here is but this seems inconsistent:
```julia
In [25]: integrate(x*Integral(y),(x,0,1))                                                                                         
Out[25]: 
⌠     
⎮ y dy
⌡     
──────
  2   

In [26]: integrate(Integral(y),(x,0,1))                                                                                           
Out[26]: 
 2
y 
──
2 
```

Why does the second example force the integration of the sub-integral when the first does not? From quick testing it seems that the former case is more common: the sub-integral only gets evaluated when it is the only part of the integrand.

**Comment by jksuom** [comment]
It seems to be the intended behaviour if the class of the integrand is `Integral`. Iterated integrals are [automatically denested](https://github.com/sympy/sympy/blob/master/sympy/concrete/expr_with_limits.py#L47-L50).

**Comment by oscarbenjamin** [comment]
I wondered if that was the case. It seems like a quirk but I can't think of a situation where this is actually problematic since someone can just use `Integral` if they don't want to evaluate the subintegral and `doit` if they do...

Closing
