### ISSUE TITLE
Finding the matrix element index in Add expression

### ISSUE THREAD

**Issue by Ashutosh1995** [sympy/sympy#15966]
I have an addition expression in sympy involving Matrix Element.

I want to find the index of the Matrix element in that expression.

I referred [this](https://stackoverflow.com/questions/48018843/how-to-find-the-index-of-an-element-in-symbolic-matrix-based-on-a-symbol) but didn't get any help.

The expression looks like this:

`-0.178571403026581*P[0, 2] + 0.267857104539871
`
where,

`PMat = MatrixSymbol('P', len(3), len(3))
`
I want to find 0,2 as 1st and 2nd index.

Is there any way ?

**Comment by sidhantnagpal** [comment]
This works fine. See https://docs.sympy.org/latest/modules/matrices/expressions.html for more information.
```
In [3]: P = MatrixSymbol('P', 3, 3)                                             

In [4]: P[0, 2]                                                                 
Out[4]: P₀₂

In [5]: print(_)                                                                
P[0, 2]
```

**Comment by Ashutosh1995** [comment]
I actually wanted the index to be returned, as in 0 and 2.

**Comment by oscarbenjamin** [comment]
Use `_.args` instead.

**Comment by Ashutosh1995** [comment]
Yeah that did, thanks a lot !!
