### ISSUE TITLE
Wrong result from discrete logarithm

### ISSUE THREAD

**Issue by jksuom** [sympy/sympy#15977]
The Pollard rho method for computing the discrete logarithm may produce wrong results. From [this comment](https://github.com/diofant/diofant/pull/785#issuecomment-462963925):
```
In [1]: from sympy.ntheory.residue_ntheory import _discrete_log_pollard_rho

In [2]: n, a, b = 11, 7, 31; _discrete_log_pollard_rho(n, a, b, rseed=0)
Out[2]: 2

In [3]: (b**2 - a)%n
Out[3]: 8
```
In this example, `b = 31` is not a generator of the multiplicative group modulo 11, in particular, `a = 7` is not one of its powers (mod 11). Yet, the algorithm returns the wrong result 2.

The code, taken from a handbook, is not intended for production use as such. It is necessary to check the validity of the result `mod_inverse(r, order) * (ab - aa) % order` before it is returned.

**Comment by jksuom** [comment]
There are two things to consider: If `order` is not a prime, it is necessary to check that `mod_inverse(r, order)` exists, the condition `r != 0` does not suffice. And secondly, it has to be checked that `e = mod_inverse(r, order) * (ab - aa) % order` really does satisfy `(pow(a, e, n) - b) % n == 0`.

**Comment by divyanshu132** [comment]
I'll try to fix this.

**Comment by divyanshu132** [comment]
@jksuom a small improvement instead of `(pow(a, e, n) - b) % n == 0`, it should be `(pow(b, e, n) - a) % n == 0`

**Comment by jksuom** [comment]
Yes, I seem to have confused the roles of `a` and `b.`
