### ISSUE TITLE
presimplify odes

### ISSUE THREAD

**Issue by smichr** [sympy/sympy#15983]
It seems like it would make sense to make sure that all mutliplicative constants in a Derivative are removed before attempting to solve the ODE, e.g. right after `eq = hints.pop('eq', eq)` do
```python
reps = {}
for d in eq.atoms(Derivative):
    if d.expr != func and d.variable_count[0][0] == x:
        reps[d] = d.doit(deep=False)
eq = eq.xreplace(reps)
eq = expand_mul(eq) # ??? is this a bad idea?
```
The motivation for doing this is that matchers will then not need to worry about superficially complicated derivatives -- they will be looking for `f(x).diff(x, n)`-like entities.

**Comment by smichr** [comment]
This is already handled in the `eq, func_ = _preprocess(eq, func)` step.

**Comment by XtremeGood** [comment]
Ok.
