### ISSUE TITLE
Value error in limit

### ISSUE THREAD

**Issue by proy87** [sympy/sympy#15984]
`Limit((-x + log(exp(x) + 1))/x, x, oo, dir='-').doit()` raises `ValueError: cannot compute leadterm`

**Comment by nileshpatra** [comment]
can I please take this issue?

**Comment by jksuom** [comment]
[This piece of code](https://github.com/sympy/sympy/blob/master/sympy/series/limits.py#L250-L254) should be put in a try-except block. The `ValueError`  should be caught and the execution should continue to let `gruntz` handle the limit.
