### ISSUE TITLE
Special case for printing Add(One, Mul(NegativeOne, expr)) and similar.

### ISSUE THREAD

**Issue by nickovs** [sympy/sympy#15982]
Currently when printing `Add` objects, numbers typically get placed at the end of the argument list. When the `Add` object has only two arguments, one is a positive rational and the other is a two-argument `Mul` for which one of the arguments is a negative rational, it would typically look better to print with the number first. For instance one would very seldom choose to write $-p+1$ rather than $1-p$ and in most cases one would likely write $2-{2/3}x^2$ rather than $-{2/3}x^2+2$.

It would be probably be useful to special-case the printing of `Add` objects in these cases so that the rational value is presented first and the negative expressions is presented second, since the will look much more natural in the majority of cases.

**Comment by oscarbenjamin** [comment]
Agreed. This has bothered me for years:
```julia
In [1]: 1 - x                                                                                                                                                 
Out[1]: -x + 1
```
Not sure what the best solution is though...

**Comment by nickovs** [comment]
It turns out it's not too hard to fix, since the ordering of arguments for printing an `Add` all funnels through one function. I've written a patch here https://github.com/sympy/sympy/commit/c52ebc834a89275433f7cbd3b596f66f6930a59c which works with the text command line and with the LaTeX printing in Jupyter Lab, and should also work with MathML and the rest. That said, since I have absolutely no experience with either the Sympy code or the general development approach in this project I'd like to get some feedback from the Sympy maintainers before offering up a pull request.

**Comment by oscarbenjamin** [comment]
The patch seems quite specific since it's only for two terms and only if they are Rational+Rational*expr. I think that we can specifically check that any of the muls has `.args[0]==-1` since this gets factored out:
```julia
In [1]: srepr(-2*x)                                                                                                                                           
Out[1]: "Mul(Integer(-1), Integer(2), Symbol('x'))"
```
I guess that the main thing is just to order the terms so that the first term is not Mul(-1,...).

In any case I'm not very experienced with this area of SymPy so it's hard for me to advise on the best general way to incorporate this functionality. The best way to get feedback is by opening a PR.

Be aware though that perhaps hundreds of doctests would need fixing before the PR ultimately gets accepted. It's still worth putting in the PR with the general approach before fixing all those tests though.

**Comment by nickovs** [comment]
The code above works because even though the -1 gets factored out for storing the expression, the call to `Mul.make_args()` (which seems to be standard in most of the printing code) merges the -1 back in to the other constant.

There is a more general question as to if this sort of printing behaviour is appropriate for more complex addition expressions. My feeling is that if we start trying to reorder 1+2x-3*x**2 then we will descend into a huge set of highly subjective cases, so I am inclined to err on the side of simplicity. That said, if someone can come up with a coherent model for deciding when the constant should be at the front for longer expressions then I'd be happy to code it.

I will have a look at running the doctests and see just how many my patch breaks. If it's dozens rather than hundreds then I will look into fixing them and including that in the PR.

**Comment by nickovs** [comment]
It seems that there are 42 doctests that fail. I will have a look at rectifying the problems. Of course doing so is going to change the PR from being a small change in one file to being changed spread over 30+ files!

**Comment by nickovs** [comment]
I've fixed up a large number of `doctest` cases and submitted a PR.

One open question in my mind is if this should only be applied to `Rational` numbers or if there are other classes of number that should be included. For instance it might make since to include `NumberSymbol` for cases like `pi - x` vs `-x + pi`.

**Comment by oscargus** [comment]
Even though, of course, a more general solution would be better, I think that the 77 doctest issues show that this happens quite often and therefore that this specific patch will improve the situation often enough. I have not studied the code in detail, I just wanted to support the general idea.

**Comment by nickovs** [comment]
Interestingly, when I update the code to move all `Number` and `NumberSymbol` values to the front when one multiplicand is a negative `Number`, no more `doctest` cases fail. This might indicate that the more general cases are actually rather rare.

**Comment by oscarbenjamin** [comment]
I think it's best to comment on the detail of the code on the PR (#15985).

**Comment by asmeurer** [comment]
Your patch ignores the order if the order argument is passed to the printer. Changing the default ordering is fine, but `order='lex'` and so on should continue to give that exact order for polynomials. 

It might be better to make this change in `as_ordered_terms`. Unfortunately, that may result in even more changes, as that affects the sort key ordering as well as the printing ordering (it may even unearth some bugs, see for instance https://github.com/sympy/sympy/pull/13059).

**Comment by nickovs** [comment]
Thanks for the comment @asmeurer. I can certainly move the code to as_ordered_terms and honour the support for the `order`. Before I head off to do all that it would be helpful to know (a) if this is something that you think is useful and, if so, (b) what your opinion is regarding in which circumstances this should be applied?

**Comment by asmeurer** [comment]
I think it's a good change. The `1 - x` thing has bothered me before. The only potential concern I can think of is that these special orders could fail to be transitive. I don't know if that would ever cause an issue. One could always switch to default_sort_key if it is.

**Comment by asmeurer** [comment]
I guess technically this order isn't transitive. We have `1 > -x**2` and `-x**2 > x`, but `x > 1`. For printing it isn't an issue (actually that's the whole point), but for other uses I don't know. Since nothing apparently broke in the tests I guess it isn't a problem. 

Actually we already have a precedent for this, which is that order terms (like O(x**2)) reverse the order of polynomials. So I think it's a non-issue.

**Comment by nickovs** [comment]
Since this only changes the ordering for printing and print-like activities it should never break the mathematises, only the representation. The order in the underlying `Add` object remains the same so any manipulation that depends on the old order should be totally unaffected. 


<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
