### ISSUE TITLE
No result for ask(Q.rational(x/y))

### ISSUE THREAD

**Issue by divyanshu132** [sympy/sympy#16001]
```
>>> ask(Q.rational(3))
True
```
This is correct.

But, the queries in `p/q` form or for `float` queries there is no output.
```
>>> ask(Q.rational(3/1))
>>> 

```
```
>>> ask(Q.rational(1/3))
>>> 
```

```
>>> ask(Q.rational(0.5))
>>> 

```
```
>>> ask(Q.rational(22/7))
>>> 

```

**Comment by jksuom** [comment]
A single float can denote both rational and irrational numbers. Hence the query must return nothing for floats. I don't know why that happens for 3/1 as well. That should probably be changed.

**Comment by divyanshu132** [comment]
But if the query is in the form of` p/q`, then also it should directly return `True` for `rational`.

**Comment by jksuom** [comment]
```
>>> type(3/1)
<type 'float'>
>>> type(1/3)
<type 'float'>
>>> type(0.5)
<type 'float'>
>>> type(22/7)
<type 'float'>
```
Python interpreter converts the numbers to floats before feeding them to SymPy. SymPy has no means of finding out their original form.

**Comment by divyanshu132** [comment]
Got the point, thanks @jksuom, Basicaly Sympy is not getting the actual form which was given by user by default python converts it in float. So, should I close it?

**Comment by jksuom** [comment]
Yes, I think so.

**Comment by oscarbenjamin** [comment]
There is a discussion of this in the docs that has some tips: [https://docs.sympy.org/latest/gotchas.html#python-numbers-vs-sympy-numbers](https://docs.sympy.org/latest/gotchas.html#python-numbers-vs-sympy-numbers)

I'll close this now.
