### ISSUE TITLE
Inherit properties for integral variables

### ISSUE THREAD

**Issue by oscargus** [sympy/sympy#16014]
Consider the following code. 

https://github.com/sympy/sympy/blob/c6726a1e221d437bb2f56a86df75b9b7fab2bf06/sympy/utilities/tests/test_wester.py#L2571-L2577

The comments are not correct anymore, no errors are raised. However, with the default x and y (`from sympy.abc import x, y`) the result is, after a few seconds:
![image](https://user-images.githubusercontent.com/8114497/52919296-2c233700-3301-11e9-8e35-3bab6351d608.png)

However, setting the obvious assumptions on x and y as
```
    x = symbols('x', real=True, positive=True)
    y = symbols('y', real=True)
```
leads to, more or less instantly:
![image](https://user-images.githubusercontent.com/8114497/52919308-64c31080-3301-11e9-8722-d0d76a8bf5ac.png)

It should be useful to assume that x is real and limited by a and b, so positive, and that y is real, in most integrals. 

It can be noted that writing it inside a single integrate does not change anything.

**Comment by oscargus** [comment]
It seems like the key thing here is to set `x` to be positive.

**Comment by asmeurer** [comment]
Should this be closed?

**Comment by oscargus** [comment]
Yes, I think it can be.
