### ISSUE TITLE
Is this correct?

### ISSUE THREAD

**Issue by proy87** [sympy/sympy#16018]
`Pow((2**(1/2)/2)**(1/6), -1 ,evaluate=False).match(a+b*I)` returns `{a_: -2**(1/12) + 1/(2**(1/12)*2**(5/6)/2), b_: -2**(1/12)*I}` but input is real number.

**Comment by jksuom** [comment]
How are `a` and `b` defined? With `exclude=[I]`?

**Comment by proy87** [comment]
No, Just wilds.

**Comment by jksuom** [comment]
There is no unique result, if `I` can be included in `a` and `b`.

**Comment by proy87** [comment]
OK. Thank you.
