### ISSUE TITLE
exp(log(2**(log(exp(x))))) returns 2**log(exp(x)) , instead of 2**x i.e. a fully simplified expression

### ISSUE THREAD

**Issue by nileshpatra** [sympy/sympy#16026]
```
>>> exp(log(2**(log(exp(x)))))
2**log(exp(x))
```
also tried for natural log for base ambiguity
```
>> simplify(exp(ln(2**(ln(exp(x))))))
2**log(exp(x))
```

**Comment by jksuom** [comment]
It is not simplified because `log` is a multivalued function. `log(exp(x))` may differ from `x` by a multiple of `2*pi*I`.

**Comment by nileshpatra** [comment]
@jksuom , got it , thanks :+1:

**Comment by asmeurer** [comment]
You can create `x` with the assumption `real=True` to make `log(exp(x))` reduce to `x`.
