### ISSUE TITLE
Wiki: Development Workflow rebase setting not found and broken links

### ISSUE THREAD

**Issue by dandiez** [sympy/sympy#16034]
Hello,

I'm getting started with the Development Workflow wiki and I could not find in Github GUI the setting for "sync does rebase" . Does anyone know if that setting is still relevant for the current Github GUI version and where to find it?
I was also trying to do the "Set up SSH keys", however the links seem to be broken.
Does anyone know where I could look to get started?

Is it ok to just edit the wiki if and when I get information on these things?

Thanks!

**Comment by oscargus** [comment]
https://help.github.com/en/articles/adding-a-new-ssh-key-to-your-github-account should be useful for setting up the SSH keys.

**Comment by dandiez** [comment]
Thank you, I have added the link to the wiki.

**Comment by sidhantnagpal** [comment]
Thanks for pointing out. I have updated the obsolete links in the References section. See https://github.com/sympy/sympy/wiki/Development-workflow#references.
