### ISSUE TITLE
Circle radius should be real

### ISSUE THREAD

**Issue by smichr** [sympy/sympy#16067]
In #15273 a decision was made to not forbid the creation of circles with imaginary radius. I'm not sure this is a useful idea (though looking at imaginary coordinates has been a fruitful and interesting endeavor for [some](https://phantomgraphs.weebly.com/)). Since all Points in geometry are expected to be real, it seems like it would have been better to insist that all geometry parameters are real.

The machinery of Point can be used to make a parameter Rational and insist on being real by doing something like `r = Point(r, 0, evaluate=evaluate).x` as noted in #15816.

cf [here](https://github.com/sympy/sympy/pull/15273#discussion_r219672628)

**Comment by asmeurer** [comment]
You mean it should be positive? 

I think it's a good idea. Complex geometry can have different properties than real geometry. For example, two real circles may intersect in the complex plane

```py
>>> solve([x**2 + y**2 - 1, (x - 2)**2 + (y - 2)**2 - 1], [x, y])
[(1 - sqrt(2)*I/2, 1 + sqrt(2)*I/2), (1 + sqrt(2)*I/2, 1 - sqrt(2)*I/2)]
```

Actually there's a theorem in algebraic geometry that tells you that two curves in the complex plane always intersect, except in certain degenerate cases. 

So it's not just a question of allowing complex constants in the geometric objects. If you are working over C, the parameters themselves must take on complex values. This is fundamentally different than the parameters taking on real values. And only doing it when one of the constants is nonreal would be incorrect, as my example shows. You either only work over C^2 or only work over R^2.
