### ISSUE TITLE
`subs` doesn't substitute symbols with unicode text in python 2

### ISSUE THREAD

**Issue by Strilanc** [sympy/sympy#16087]
In python 2.7

```
print(sympy.Symbol(u"s").subs({u"s": 1}))
```

should output

```
1
```

but instead outputs

```
s
```

(If you use the dictionary `{"s": 1"}` then it does work, regardless of whether the symbol has a unicode text or not. If you use the dictionary `{u"s": 1"}` then it fails regardless of the symbol text type.)

**Comment by asmeurer** [comment]
Probably due to this line:
https://github.com/sympy/sympy/blob/b68caad822d3ad0ae1fa09c78c9ed2db927e73cb/sympy/core/basic.py#L944

It should be using `isinstance(s[0], string_types)`.

**Comment by supreet11agrawal** [comment]
Running tests, will send PR asap
