### ISSUE TITLE
srepr does not represent unicode strings correctly in python 2

### ISSUE THREAD

**Issue by Strilanc** [sympy/sympy#16086]
In python 2.7:

```python
import sympy
s = sympy.Symbol(u"text")
print(sympy.srepr(s))
```

outputs:

```
Symbol(text)
```

instead of:

```
Symbol(u"text")
```

or `"text"`.

**Comment by abhijeet47** [comment]
I would like to work on it.

**Comment by sharma-kunal** [comment]
I would like to work on the issue. Can you please explain how to proceed ?

**Comment by Pranay144** [comment]
If we try something like this:

`import sympy`
`from sympy.abc import *`
`s = (u"text")`
`print(sympy.srepr(s))`

Outputs:

'text'

**Comment by czgdp1807** [comment]
@Strilanc Is the following good?
```python
>>> s = Symbol(u"text")
>>> srepr(s)
"Symbol('text')"
```

**Comment by Strilanc** [comment]
That's still technically incorrect in python 2, unless sympy removes the distinction between a `unicode` and a `str`. For python 3 it would be fine.

**Comment by teresafds** [comment]
I tried to install  sympy git version with python2 using 
`python2 setupegg.py develop`
but it throws  
`SymPy requires Python 3.5 or newer. Python 2.7 detected`

Is this issue still valid?

**Comment by oscarbenjamin** [comment]
No it isn't. Thanks for pointing this out!
