### ISSUE TITLE
Incorrect result of cancel

### ISSUE THREAD

**Issue by proy87** [sympy/sympy#16105]
`(-1 + 3*I)/(-1 + 3*I).cancel()` returns `-(-1 + 3*I)*(1 + 3*I)/10` instead of `1`.

**Comment by sidhantnagpal** [comment]
It looks like the expression is being reduced even before `cancel` is called.
```
In [2]: (-1 + 3*I)/(-1 + 3*I)                                                   
Out[2]: (-1 - 3*I)*(-1 + 3*I)/10
```

**Comment by jksuom** [comment]
`expand` will simplify expressions of this type.

**Comment by smichr** [comment]
Note, too, that applying cancel in this way would only act on the expression within the preceding parens (i.e. the denominator). But that issue aside, the `expand` is your ticket for 1 in this case.
