### ISSUE TITLE
[LGTM] non-iterable loop variable

### ISSUE THREAD

**Issue by smichr** [sympy/sympy#16118]
This [line](https://lgtm.com/projects/g/sympy/sympy/snapshot/dist-1950035-1542114507979/files/sympy/stats/joint_rv.py?sort=name&dir=ASC&mode=heatmap#L108) should read `for i in range(len(other)):` or `for i in range(len(rvs)):`. Either is fine; the latter is more direct.

**Comment by smichr** [comment]
@rneatherway Do you know if there is a better way to do the following so it doesn't raise an LGTM warning? `[Dummy() for i in z]` -- that will warn that the loop variable `i` is not used.

One could do `list(map(Dummy, [None]*len(z)))` but that looks obtuse; would it warn if `_` were used as the loop variable: `[Dummy() for _ in z]`?

**Comment by oscargus** [comment]
Unfortunately, the LGTM issues have not been updated since mid July, so it has been fixed already:
https://github.com/sympy/sympy/blob/a302bbeb5fa4418be4ad82b6b5b3607de3f2d65d/sympy/stats/joint_rv.py#L149

**Comment by smichr** [comment]
Thx.

**Comment by smichr** [comment]
I will see if anyone has an idea about the other question I asked.

**Comment by oscargus** [comment]
Probably "If you want to remove only this alert (and not other similar alerts), you can add the comment lgtm [py/unused-loop-variable] to the end of line 1128" may be the easiest approach, but it would indeed be interesting to avoid comments like this in the code.

**Comment by smichr** [comment]
One could have a dummies iterator:
```python
def dummies(name=''):
    return numbered_symbols(name, cls=Dummy)

>>> old = (x, y)
>>> list(zip(old, take(dummies(), len(old))))
[(x, _0), (y, _1)]
```

**Comment by asmeurer** [comment]
> @rneatherway Do you know if there is a better way to do the following so it doesn't raise an LGTM warning? `[Dummy() for i in z]` -- that will warn that the loop variable `i` is not used.
> 
> One could do `list(map(Dummy, [None]*len(z)))` but that looks obtuse; would it warn if `_` were used as the loop variable: `[Dummy() for _ in z]`?

Where is this coming from? I only found one instance of this grepping through the code, in `test_function.py`, and lgtm seems to be showing an older version of the file without it https://lgtm.com/projects/g/sympy/sympy/latest/files/sympy/core/tests/test_function.py?sort=name&dir=ASC&mode=list.

This really shouldn't be giving a warning. Unused loop variables happen all the time. Python forces you to bind a variable to make a loop, so they should never be warned about being unused.

This is one reason I'm not a huge fan of linting tools. You see the linter give a warning for something that's perfectly fine, and assume the linter is God and replace the code with something that reads worse. Even extremely conservative linters like pyflakes have false positives in the SymPy codebase.

**Comment by asmeurer** [comment]
Although to be sure, the line in `test_functions.py` would be better as `symbols('xi_:3', cls=Dummy)`.

**Comment by rneatherway** [comment]
That's a good question, we already have a concept of variables that it is acceptable not to use, and as the queries are open-source you can see that (if you know the right place to look!). Your underscore intuition matches ours:

https://github.com/Semmle/ql/blob/66013272dabbca841b0e3362dff71faea7acd78b/python/ql/src/Variables/Definition.qll#L136

```
predicate name_acceptable_for_unused_variable(Variable var) {
    exists(string name |
        var.getId() = name |
        name.regexpMatch("_+") or name = "empty" or
        name.matches("%unused%") or name = "dummy" or
        name.regexpMatch("__.*")
    )
}
```

Or if you aren't a fan of the query at all you can disable it in the configuration file.

Again, sorry for the misleading output arising from LGTM timing out on `sympy` for some time.

**Comment by smichr** [comment]
Thanks for the report, @rneatherway .
