### ISSUE TITLE
Add function for Goldbach's conjecture

### ISSUE THREAD

**Issue by divyanshu132** [sympy/sympy#16113]
Goldbach's conjecture says, Every even integer greater than 2 can be expressed as the sum of two primes.
https://en.wikipedia.org/wiki/Goldbach%27s_conjecture

```
Take for example:
100 = 3 + 97
4 = 2 + 2
```

**Comment by jhanwar** [comment]
I would like to take this issue.

**Comment by divyanshu132** [comment]
> I would like to take this issue.

@jhanwar I myself working on this.

**Comment by smichr** [comment]
SymPy is not really the vehicle for proving a conjecture like this.
