### ISSUE TITLE
[LGTM]: loop variable not used in diophantine

### ISSUE THREAD

**Issue by smichr** [sympy/sympy#16110]
Instances of `for v1 in` should be changed to `for var in` (2 of them) in diophantine.py.

Here is a test case:

```
eq=(x**2 + y**2 +3*x- 5)
diophantine(eq,permute=True)
master:
{(1, -1), (1, 1), (-4, 1), (-4, -1)}
corrrected:
{(1, -1), (4, -1), (-1, 1), (-4, -1), (-4, 1), (-1, -1), (4, 1), (1, 1)}
```

**Comment by FrackeR011** [comment]
Replacing `for  v1 in` with `for var in` gives this output:
```
>>> eq=(x**2 + y**2 +3*x- 5)
>>>  diophantine(eq,permute=True)
{(-4,), (-1,), (1,), (4,)}
```

**Comment by smichr** [comment]
Indeed. var is used for the free symbols. So then change `var[0]` to `v1[0]` inside those two loops.
