### ISSUE TITLE
symbolic divisor_sigma

### ISSUE THREAD

**Issue by smichr** [sympy/sympy#16123]
`divisor_sigma(a**k*b**j, 1)` where `a` and `b` are prime and `k` and `j` are positive integers is `(a**(k+1)-1)/(a-1)*(b**(j + 1) -1)/(b - 1)`. Right now, the only case that is recognized symbolically is `divisor_sigma(a) -> a + 1`.
```python
def eval(cls, n):
    ...
    if n.is_integer:
        if n.is_Mul or n.is_Pow:  # prime is already handled
            p = []
            for b, e in (_.as_base_exp() for _ in Mul.make_args(n)):
                if b.is_prime and e.is_positive:
                    p.append((b**(e + 1) - 1)/(b - 1))
                else:
                    return
            return Mul(*p)

>>> divisor_sigma(2**3*3**5)
5460
>>> a,b = var('a b',prime=True)
>>> j,k=var('j k', integer=True, positive=True)
>>> eq = a**j*b**k
>>> eq.subs({a:2,j:3,b:3,k:5})
5460
```

**Comment by divyanshu132** [comment]
I'm taking this.

**Comment by divyanshu132** [comment]
@smichr can you please crosscheck the result of above substitution will be `1944` and for the current master I'm able to evaluate it.

**Comment by divyanshu132** [comment]
sorry, I misunderstood the purpose of divisor_sigma(). I will do the required changes.
