### ISSUE TITLE
Solve ignores dict=True when bools are in the input equations

### ISSUE THREAD

**Issue by oscarbenjamin** [sympy/sympy#16138]
The docstring for solve says:
```
        'dict'=True (default is False)
            return list (perhaps empty) of solution mappings
```

However when given a list of Eqs where one of the Eqs has auto-evaluated to `True` it doesn't return a list of dicts:
```julia
In [1]: solve([True, Eq(x, 0)], [x])                                                                                                                          
Out[1]: x = 0

In [2]: solve([True, Eq(x, 0)], [x], dict=True)                                                                                                               
Out[2]: x = 0

In [3]: solve([Eq(x, 0)], [x], dict=True)                                                                                                                     
Out[3]: [{x: 0}]
```

**Comment by RituRajSingh878** [comment]
https://github.com/sympy/sympy/blob/0d93891268729373339dddc759f7320c85dc4851/sympy/solvers/solvers.py#L981
I have gone through the code and I find that when bool is present it returns directly without checking other flags so in such case all flag is useless.

**Comment by oscarbenjamin** [comment]
I wonder why it does that. That line was add in #13204.

I would think that solve should return an empty list of any equation is `False` and ignore any equation that is `True` but maybe I'm misunderstanding...

**Comment by sidhantnagpal** [comment]
Is this related to #13534? (which happens to be when relational operators are involved)

**Comment by oscarbenjamin** [comment]
They do look related and both are coming from the same line of code so both issues here can be closed by a single PR I guess.

The difference in this issue is that it shouldn't be calling the inequality solver here. These bools are coming from evaluated Eqs e.g.:
```julia
In [5]: eqs = [Eq(x, x), Eq(x, 1)]                                                                                                                            

In [6]: eqs                                                                                                                                                   
Out[6]: [True, x = 1]

In [7]: solve(eqs)                                                                                                                                            
Out[7]: x = 1

In [8]: solve(eqs, dict=True)                                                                                                                                 
Out[8]: x = 1
```
So #13534 is solved by propagating dict=True through to `reduce_inequalities` whereas this issue is solved by not assuming that a bool represents an inequality.

**Comment by sharma-kunal** [comment]
@oscarbenjamin Why can't we just ignore the `Boolean Values` in solve e.g: 

```
solve([True, Eq(x, 0)], [x], dict=True)
```
is equivalent to 

```
solve([Eq(x, 0)], [x], dict=True) 
```

**Comment by oscarbenjamin** [comment]
We should ignore Trues in the input. If there is a False then we should return an empty list.

We have to imagine that these bools have come from evaluated Eqs. True means an equation that is trivially true and therefore tells us nothing about any of the variables we are interested in. Those can be ignored. False means that the equation was unsatisfiable: that means it cannot have any solutions.
```julia
In [29]: Eq(x, x+1)                                                                                                                                           
Out[29]: False

In [30]: Eq(x, x)                                                                                                                                             
Out[30]: True
```
