### ISSUE TITLE
 sympy/sympy/functions/elementary/exponential.py

### ISSUE THREAD

**Issue by AkashAli506** [sympy/sympy#16132]
I think comments should need to be added in each function of " sympy/sympy/functions/elementary/exponential.py" file so everyone can easily understand the functionality of the functions.

**Comment by oscarbenjamin** [comment]
What sort of comments would you want to add?

A PR that makes the code easier to understand would seem reasonable.

**Comment by oscarbenjamin** [comment]
Perhaps adding something to the docs might make sense instead/also.
