### ISSUE TITLE
Dsolve: TypeError with too many functions

### ISSUE THREAD

**Issue by oscarbenjamin** [sympy/sympy#16146]
This is invalid since I'm asking to solve for 3 functions from 2 ODEs but the error should be detected properly rather than failing in this way:
```julia
In [2]: dsolve([f(t).diff(t), g(t).diff(t)], [f(t), g(t), h(t)])                                                                                              
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-2-a1291c436ca5> in <module>
----> 1 dsolve([f(t).diff(t), g(t).diff(t)], [f(t), g(t), h(t)])

~/current/sympy/sympy/sympy/solvers/ode.py in dsolve(eq, func, hint, simplify, ics, xi, eta, x0, n, **kwargs)
    606                     pass
    607                 else:
--> 608                     if eq[i].coeff(diff(func[i],t,ode_order(eq[i], func[i]))).is_negative:
    609                         eq[i] = -eq[i]
    610         match['eq'] = eq

~/current/sympy/sympy/sympy/solvers/deutils.py in ode_order(expr, func)
    109     """
    110     a = Wild('a', exclude=[func])
--> 111     if expr.match(a):
    112         return 0
    113 

~/current/sympy/sympy/sympy/core/basic.py in match(self, pattern, old)
   1605         """
   1606         pattern = sympify(pattern)
-> 1607         return pattern.matches(self, old=old)
   1608 
   1609     def count_ops(self, visual=None):

~/current/sympy/sympy/sympy/core/symbol.py in matches(self, expr, repl_dict, old)
    478             return None
    479         repl_dict = repl_dict.copy()
--> 480         repl_dict[self] = expr
    481         return repl_dict
    482 

~/current/sympy/sympy/sympy/core/basic.py in __hash__(self)
    124         h = self._mhash
    125         if h is None:
--> 126             h = hash((type(self).__name__,) + self._hashable_content())
    127             self._mhash = h
    128         return h

TypeError: unhashable type: 'list'
```

**Comment by ShubhamKJha** [comment]
@oscarbenjamin I will take this issue. What properly needs to be done here?

**Comment by oscarbenjamin** [comment]
The code that checks the arguments for `dsolve` isn't working properly. This should give a message to the user explaining that they have provided invalid arguments rather than failing in the middle like this.

**Comment by XtremeGood** [comment]
dsolve requires too many fixes. Can I choose it as my gsoc project?

**Comment by oscarbenjamin** [comment]
`dsolve` needs a lot of work. I think there is something for dsolve listed in the GSOC projects.

**Comment by oscarbenjamin** [comment]
Can you please use the mailing list for that kind of discussion though. This page is for discussin this particular issue with dsolve.

**Comment by ShubhamKJha** [comment]
@oscarbenjamin I will try to work on the code as you suggested.

@XtremeGood I think this is happening because the code of `dsolve` is tied to whole `ode` module and this module has been worked upon by many I guess. I will try to look into whole `ode` module for some time to make it more consistent and expandable.

**Comment by divyanshu132** [comment]
@oscarbenjamin [can we do something like this](https://github.com/sympy/sympy/blob/cf7322f5dba866c85ab3cfa2ad237e573b008a43/sympy/solvers/ode.py#L1543).

```
if len(funcs) > len(eq):
        raise ValueError("Number of functions given is more than number of equations %s" % funcs)
```

**Comment by oscarbenjamin** [comment]
Yes. I thought there already was a line checking that but maybe not.
