### ISSUE TITLE
shortcut for is_perfect

### ISSUE THREAD

**Issue by smichr** [sympy/sympy#16144]
Since "Every even perfect number ends in 6 or 28 base 10" that would be a good first check for the newly added `is_perfect` function in ntheory: 
```python
last2 = n%100
if last2 != 28 and last2%10 != 6:
    return False
```

**Comment by jhanwar** [comment]
I will take this

**Comment by Mohitbalwani26** [comment]
i would like to work on this issue can you please guide me?

**Comment by supreet11agrawal** [comment]
@Mohitbalwani26 , @jhanwar has already submitted a PR for this issue. If you are new, I suggest you to look issues under _Easy to Fix_ label.
