### ISSUE TITLE
Overriding the imaginary unit

### ISSUE THREAD

**Issue by ethren** [sympy/sympy#16147]
In case we import * from sympy
We could override many variables, for example the imaginary unit, `I`

In this example: 

```
from sympy import *
t = symbols('t')
I = symbols('I', positive=True)
expr1 = t**2  + I*S(4)
eq1 = Eq(expr1, 0)
solveset(eq1, t)
```

**Output**:
`{-2*I*sqrt(I), 2*I*sqrt(I)}`

Now in the solution expression, there are two `I`. The first one is the imaginary unit while the second (argument of sqrt is the one defined by the user).

Should Sympy warn the user when he/she overrides  Sympy variables? or simply the user should be careful when choosing variable names?

**Comment by oscarbenjamin** [comment]
The user should be careful when choosing variable names.

There is no way for SymPy to detect that you have written something like `I=1`. It would be possible to give a warning for `Symbol('I')` but SymPy defines so many different symbols that you could override that that isn't useful. If you display your output using pprint/init_printing in a unicode capable terminal you can see
```julia
In [1]: from sympy import * 
   ...: t = symbols('t') 
   ...: I = symbols('I', positive=True) 
   ...: expr1 = t**2  + I*S(4) 
   ...: eq1 = Eq(expr1, 0) 
   ...: solveset(eq1, t)                                                                                                                                      
Out[1]: {-2⋅ⅈ⋅√I, 2⋅ⅈ⋅√I}
```
so it is possible to tell those two apart.

**Comment by ethren** [comment]
I think this is the same case in the symbolic toolkit of Matlab and it is the same behaviour
