### ISSUE TITLE
Equal functions evaluated as unequal

### ISSUE THREAD

**Issue by supreet11agrawal** [sympy/sympy#16155]
To reproduce the issue,
```
>>> from sympy import Symbol, expand
>>> alpha = Symbol("alpha", positive = True)
>>> beta = Symbol("beta", positive = True)
>>> f1 = alpha*beta/(alpha**3 + 3*alpha**2*beta + alpha**2 + 3*alpha*beta**2 + 2*alpha*beta + beta**3 + beta**2)
>>> f2 = alpha*beta/((alpha + beta)**2*(alpha + beta + 1))
```
Both `f1` and `f2` are equal as denominator of `f1` is just the expansion of denominator of `f1`.
Now,
```
>>> f1 == f2
False
>>> f1 == expand(f2)
True
```
I think that `f1 == f2` should be evaluated to `True`.

**Comment by divyanshu132** [comment]
I think this is the default behavior of Sympy please look at the below example.
```
>>> from sympy import *
>>> x=symbols('x', positive=True)
>>> y=x**2 + 2*x + 1
>>> z=(x+1)*2
>>> y==z
False
>>> y==expand(z)
True
```

**Comment by divyanshu132** [comment]
I think this is the default behavior of Sympy please look at the below example.
```
>>> from sympy import *
>>> x=symbols('x', positive=True)
>>> y=x**2+1+2*x
>>> z=(x+1)**2
>>> y==z
False
>>> y==expand(z)
True
```

**Comment by sidhantnagpal** [comment]
Yes, that is intended behaviour (`==` refers to structural equality). See the gotchas section https://docs.sympy.org/latest/tutorial/gotchas.html#equals-signs for more information.
