### ISSUE TITLE
Deprecate _cache_is_diagonalizable and _cache_eigenvects

### ISSUE THREAD

**Issue by sylee957** [sympy/sympy#16163]
See issue #15887

Also remove these lines
```
    # XXX Remove these after deprecation is done for issue #15887
    '_cache_eigenvects', '_cache_is_diagonalizable']
```
in test_pickling

**Comment by oscargus** [comment]
Should one set a milestone for when this should happen? (There is a clear risk that there will be PR suggested within the next few days, which are most likely not usable when the actual removal should happen.)

**Comment by asmeurer** [comment]
I don't know the full context here, but is it necessary to deprecate these? They are private attributes (they start with an underscore), so can't we just remove them?

**Comment by sylee957** [comment]
There are also some public keywords to deprecate
https://github.com/sympy/sympy/blob/e6509ea7b1e4bc14cd3276d993a1691b124343f8/sympy/matrices/matrices.py#L1437-L1448

I have just added every related bulk to undergo deprecation cycle.
But whatever, I'm fine with making either the private attributes removed before next release.
Though it may need some decision to remove the keywords.

**Comment by asmeurer** [comment]
I see. Those are definitely public API.
