### ISSUE TITLE
WE CAN GENERATE INTEGRATE CLASS INSTEAD OF INTEGRATE FUNCTION AND USE THE OBJECT OF INTEGRATE CLASS

### ISSUE THREAD

**Issue by drishyakumar** [sympy/sympy#16165]

**Comment by oscarbenjamin** [comment]
Can you edit the title of this so it isn't in all caps. It looks like you're shouting at me...

Also can you edit the description below to be more informative?

**Comment by drishyakumar** [comment]
Sorry sir
I will change it
