### ISSUE TITLE
add function to test for unchanged expression

### ISSUE THREAD

**Issue by smichr** [sympy/sympy#16177]
In #2942 there was a lot of discussion about tests that write `assert foo == foo`.

An idea that I left there was this function which I still think could be used for cases when you want to assert that what you typed remained unchanged:

```python
def unchanged(func, *args):
    """Return True if `func` applied to the `args` is unchanged.

    Examples
    ========

    >>> unchanged(cos, 1)  # instead of assert cos(1) == cos(1)
    True
    """
    f = func(*args)
    return f.func == func and f.args == tuple([sympify(a) for a in args])
```

**Comment by oscarbenjamin** [comment]
I guess that could be used e.g. here [https://github.com/sympy/sympy/pull/15923#discussion_r262006408](https://github.com/sympy/sympy/pull/15923#discussion_r262006408)

**Comment by FrackeR011** [comment]
I think this should be go in `sympy/sympy/utilities/misc`.

**Comment by supreet11agrawal** [comment]
I'll take this

**Comment by supreet11agrawal** [comment]
@smichr @oscarbenjamin should we add this function to `utilities/pytest.py` if we are just going to use it for testing. Or are we planning to use to this method for general purpose (other than testing) as well?

**Comment by oscarbenjamin** [comment]
It will be just for testing but probably doesn't want to go in pytest.py. The pytest.py file is supposed to be a compatibility layer that either imports functions from pytest or defines them if pytest isn't installed. Since this function isn't defined in pytest it should go somewhere else.

I guess I'd put this in utilities/misc.py.

**Comment by supreet11agrawal** [comment]
@smichr, currently only arguments like `cos(x)` can be checked using `unchanged` function. I don't think it is possible to check something like if `cos(x)*exp(x)` is changing using it. Should we look into this as well. I saw a few cases where this might be used. For instance, see this
https://github.com/sympy/sympy/blob/00252f18af78cdc3013042e7ef264af8161c9366/sympy/core/tests/test_arit.py#L348
The main idea here was to check if `exp(x)*exp(y)` reamins unchanged.I don't think that the test written here is useful as well

**Comment by oscarbenjamin** [comment]
I think it's best to open a new issue for that.
