### ISSUE TITLE
Discrepancy between `gf_edf_zassenhaus` and reference material

### ISSUE THREAD

**Issue by TuomLarsen** [sympy/sympy#16173]
I was comparing the implementation of Equal Degree Factorization by Cantor and Zassenhaus with the referenced book Modern Computer Algebra and it seems the [code](https://github.com/sympy/sympy/blob/master/sympy/polys/galoistools.py#L1894) is missing one condition.

The book reads:

    g1 <- gcd(a, f)
    if g1 != 1 then return g1

The later line is missing from the code, shouldn't there be something like:

    r = gf_random(2*n - 1, p, K)
    g = gf_gcd(r, f, p, K)
    if g != [K.one]: return g

instead of just the first line, as there is now?

**Comment by asmeurer** [comment]
Permalink to the line https://github.com/sympy/sympy/blob/e6509ea7b1e4bc14cd3276d993a1691b124343f8/sympy/polys/galoistools.py#L1894

**Comment by jksuom** [comment]
There are two references. The implementation seems to follow the pseudocode given in "Algorithms for Computer Algebra" that does not contain this test. It is not essential for the method of Cantor and Zassenhaus. It is possible that the random polynomial `r` has a common factor with `f` but the probability is small. The method consists of computing `h = r**e ` modulo `f` where `e = (q - 1)/2` (in case of odd characteristics). Then the probability of `h - 1` having a common factor with `f` is over 50 %.

I think that this issue could be closed.
