### ISSUE TITLE
Improve RSA Documentation

### ISSUE THREAD

**Issue by sylee957** [sympy/sympy#16181]
`encipher_rsa` and `decipher_rsa` docs only informs about encrypting with public key and decrypting with private key. But it is also possible to encrypt message using private key and decrypting it with public key.

The examples may also contain a process of 'signing' a message with private key,
and verifying the message by comparing the original message, with deciphered message with public key.

**Comment by hannah-kari** [comment]
Hi! I'd like to work on this issue. Is that alright?

**Comment by sylee957** [comment]
@hannah-kari 
You can go on. We don't reserve a specific someone to handle an issue. I can inform you that we are using [sphinx](http://www.sphinx-doc.org/en/master/), [numpydoc](https://numpydoc.readthedocs.io/en/latest/) extensions, to build our docs. And you can test out the build if you navigate to `/doc` folder.

**Comment by Naba7** [comment]
As you said no specific someone is assigned,can I take this issue

**Comment by sylee957** [comment]
@Naba7 
Honestly, anyone who gets proposal accepted first can get listed as contributor.

Though, we're not making this a sort of competition, which can discourage people from sharing information each other.
And I think you can use [Co-Author](https://help.github.com/en/articles/creating-a-commit-with-multiple-authors) system, or ask other people for listing your name, if you have your original ideas merged during a discussion process.

**Comment by Naba7** [comment]
@sylee957  thank you. I am not taking this up as a competition.I just want to know more and learn from it.So,I want to take up issues.Its no bad if other person resolves it.I will learn if I work on the issue,the sole reason I asked for taking up on this issue.
