### ISSUE TITLE
Cloning into local repo command

### ISSUE THREAD

**Issue by Naba7** [sympy/sympy#16193]
In the installation guides of sympy,the cloning of sympy repo is written as git://github.com/sympy/sympy.git . It should be https://github.com/Naba7/sympy.git using https or git@github.com:Naba7/sympy.git using SSH.

**Comment by asmeurer** [comment]
The command is correct. You generally want to clone from the main repo, as that is what is updated (if you do a `git pull` after cloning from your fork, you won't get the latest updates). Our [dev guide](https://github.com/sympy/sympy/wiki/Development-workflow) also uses the "clone from the base repo, add your fork as a remote" git workflow.

**Comment by asmeurer** [comment]
Or are you saying it should use the https URL instead of git://? I don't know if it makes a big difference. The SSH url is not ideal because it requires having your SSH key on GitHub. As far as I know git:// urls should work everywhere, but maybe there are some advantages to https://.

**Comment by asmeurer** [comment]
According to https://gist.github.com/grawity/4392747, git:// URLs do not do server verification. So I guess https:// should be preferred.

**Comment by Naba7** [comment]
So,shall I change it?
