### ISSUE TITLE
Function to return Total Energy in physics/mechanics 

### ISSUE THREAD

**Issue by ritesh99rakesh** [sympy/sympy#16201]
At present, there is are functions to calculate kinetic energy and potential energy of a rigid body in ```sympy/physics/mechanics/rigidbody.py``` but no function to return the total energy of the rigid body. I propose the following PR. Please let me know your views about it.

**Comment by sidhu1012** [comment]
Is this issue up? I would like to work on this issue.

**Comment by sidhu1012** [comment]
What is the difference between potential energy @property function and potentiat energy setter function?

**Comment by oscarbenjamin** [comment]
It is decided that we don't need a function to return total energy. It is easy for a user to compute the total energy using the existing API by adding the potential and kinetic energy themselves.

https://github.com/sympy/sympy/pull/18838#issuecomment-702682980
