### ISSUE TITLE
Core: Enhancing the unchanged function

### ISSUE THREAD

**Issue by supreet11agrawal** [sympy/sympy#16215]
This issue follows from https://github.com/sympy/sympy/issues/16177.
For solving this issue, an `unchanged` function was added in `expr.py` through PR https://github.com/sympy/sympy/pull/16189
Currently, this `unchanged` function works perfectly for checking if an expression remains unchanged if the expression is something like `cos(x)` or `exp(x)`. However, for expressions like https://github.com/sympy/sympy/blob/00252f18af78cdc3013042e7ef264af8161c9366/sympy/core/tests/test_arit.py#L348 this function is insufficient. The idea here is to improve the `unchanged` function or maybe introduce a new one which checks if expressions of this form remain unchanged or not

**Comment by Vinayak-Shukla** [comment]
I'd like to work on this, should I get started?

**Comment by supreet11agrawal** [comment]
Yes, you can

**Comment by Vinayak-Shukla** [comment]
can you assign it to me then?

**Comment by smichr** [comment]
Try `unchanged(Mul, exp(x), exp(y)`; every expression has a `func` so `unchanged(foo.func, *foo.args) == foo` is an invariant for an expression that doesn't have unevaluated args.

**Comment by supreet11agrawal** [comment]
Yes, that is working. In this case, I'll just change the test which I mentioned above.
