### ISSUE TITLE
documentation: incorrect citation for scipy.stats.f_oneway

### ISSUE THREAD

**Issue by hirschmichael** [sympy/sympy#16229]
The documentation page of scipy.stats.f_oneway cites "Heiman, G.W. Research Methods in Statistics. 2002." I didn't find that title. It is probably an error. There are a few books by Gary W. Heiman, which could be the correct source, see e.g.  https://openlibrary.org/authors/OL37433A/Gary_W._Heiman

SciPy Release: 1.2.1, February 10, 2019
https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.f_oneway.html#scipy.stats.f_oneway

**Comment by sylee957** [comment]
Is there any SymPy relevant issue about the docs?

If not, you may have to report to the SciPy issue tracker.
https://github.com/scipy/scipy

**Comment by hirschmichael** [comment]
You are right. Sorry I've got the wrong page.
