### ISSUE TITLE
Maximum value of a function

### ISSUE THREAD

**Issue by supreet11agrawal** [sympy/sympy#16239]
To the best of my knowledge, Sympy currently is unable to find the maximum value of a given function. This can be used in many places.
While searching for this, I came across https://groups.google.com/forum/#!topic/sympy/Na_p5pm1I7M, but I wasn't able to find if it was implmented.

**Comment by supreet11agrawal** [comment]
One trivial solution I had in mind was to make a set of boundary points and points where differential is zero. And then check for every such point finding `lim(f, x, x0)` where `x0` belongs to the set. The maximum value will be the result and the corresponding point will be global maxima. This is one of the most basic approach we can try.

**Comment by oscarbenjamin** [comment]
What you suggest sounds like finding the maximum of a real function of a real variable. There are other kinds of function. So probably what you want is something like max / argmax for real functions which could go in calculus or solvers maybe.

**Comment by oscargus** [comment]
Note that there are some general CAS tests in `test_wester.py` that will pass with this:

https://github.com/sympy/sympy/blob/3d8300a569cfeed57bd36908240862ca330204b0/sympy/utilities/tests/test_wester.py#L2247-L2257

I might even think an optimization module could be added as there may be other optimization methods later on that can be added.

Just as solve/solveset, methods `minimize` and `maximize` can be extended to use special methods depending on the input type. For polynomials taking the derivative and finding the roots is clearly a feasible way.

I can also imagine functions for finding all (local) minimal and maximal points etc.

**Comment by supreet11agrawal** [comment]
> I can also imagine functions for finding all (local) minimal and maximal points etc.

I was actually thinking about the same. A set can be obtained containing all the stationary points which can be broken further for different applications.

**Comment by supreet11agrawal** [comment]
> I might even think an optimization module could be added as there may be other optimization methods later on that can be added.

I am not sure about this though. It can be added but are there enough such optimization methods that we are planning to implement?
Maybe @asmeurer @jksuom can help as well
