### ISSUE TITLE
regression: `factor(f, x, deep=True)` 

### ISSUE THREAD

**Issue by cbm755** [sympy/sympy#16240]
Consider the factorable expression f:
```
>>> g = (x+3)*(x+4)*(y+5)*(y+6)
>>> f = g.expand()

 2  2       2         2        2                        2              
x ⋅y  + 11⋅x ⋅y + 30⋅x  + 7⋅x⋅y  + 77⋅x⋅y + 210⋅x + 12⋅y  + 132⋅y + 360
```

Good:
```
>>> f.factor(x)
                ⎛ 2            ⎞
(x + 3)⋅(x + 4)⋅⎝y  + 11⋅y + 30⎠
```

Regression:
```
>>> f.factor(x, deep=True)
(x + 3)⋅(x + 4)⋅(y + 5)⋅(y + 6)
```
(I think this should do the same as above)

This is a regression from 1.3, bisected to 9b879cc1dd0acee7d2f741dadea22ebd4f010732

CC @normalhuman

**Comment by jksuom** [comment]
It would probably suffice to include the parameters to [`_try_factor`](https://github.com/sympy/sympy/blob/master/sympy/polys/polytools.py#L6322):

`fac = factor(expr)` -> `fac = factor(expr, *gens, **args)`

(as `deep` has been popped already).
