### ISSUE TITLE
Linear Algebra Solve Problem

### ISSUE THREAD

**Issue by kholdeman** [sympy/sympy#16245]
I'm converting a university coursework to Python.  Eigen values and vectors were demonstrated and then shown how to "solve" the problem the original way.  I found the following case where sympy only finds the trivial solution:
```
A =  
> [[ 15  -4   1]
 [-10  12  -6]
 [ 20   4  -2]]
```
The following code that demonstrates these problems was run under Anaconda3 which included Python 3.7.1, sympy 1.3 and numpy 1.15.4.  The parts above the "######" line demonstrate that numpy and sympy can solve these Eigen problems satisfactorily.  Below that line shows that sy.solve struggles.  (By copying and pasting the the following code in a Python source code file, it should run immediately.)
```python
import numpy as np
import sympy as sy
from sympy.matrices.dense import Matrix
from sympy import symbols as syms

def printEigenVectors(ww, vv):
    print('EigenValues=', ww, '\nEigenVetors=\n', vv)
    for ii in range(Anp.shape[0]):
        DotAvv = np.dot(Anp, vv[:,ii])
        wwvv = ww[ii]*vv[:,ii]
        print('%d: Value:%s, Vector:%s\n\tdiff:[%s %s]' % 
            (ii, ww[ii], DotAvv.T, DotAvv[0] - wwvv[0], DotAvv[1] - wwvv[1]))

Anp = np.array([[15,-4,1],[-10,12,-6],[20, 4, -2]])
print('A=\n', Anp)
ww, vv = np.linalg.eig(Anp)
print("\nHere's the numpy solution to this problem:")
printEigenVectors(ww, vv)

Am = Matrix(Anp)
x1, x2, x3 = syms('x1:4')
x = Matrix([[x1, x2, x3]]).T

print("\nThe sympy solution also works:")
eVects = Am.eigenvects()
print('eVects=')
for ii, ev in enumerate(eVects):
    print('Solution %d' % (ii))
    print('eVal=%s' % (ev[0].evalf()))
    print('eVect(s)=')
    for jj in range(ev[1]):
        print(jj)
        print('%s' % (ev[2][jj].evalf()))

print("\nsy.solve does correctly calculate the Eigenvalues:")
λ = syms('λ')
I3 = sy.eye(Am.shape[0])

mEigenValues = sy.solve(sy.Eq((Am - λ*I3).det(), 0), λ)  # Okay
print('Eigenvalues=', mEigenValues)
mEigenValues = Matrix(mEigenValues).evalf()
print("\nHere's sympy's evalf() Eigenvalues=\n", mEigenValues, "\n")

print('##############################################################')
print("Why does sympy only find the trivial vectors for this problem?")
for ev in mEigenValues:  # [-0.3722813232690143, 5.37228132326901]:
    print('ev=', ev)
    DotAmx = Am*x
    evx = ev*x
    Sol = sy.solve(sy.Eq(Am*x, evx))
    print('Sol=', Sol)
    print()
```

**Comment by oscarbenjamin** [comment]
I've edited your post to using backticks (github markdown for including code) so that the code comes out properly. However it hasn't come out properly. I think maybe your tabs have turns into `>` signs. Can you edit it so that the code comes out such that it can be copy pasted to test?

**Comment by kholdeman** [comment]
Thanks for checking this submission.  I verified I could copy source code from the Preview version into a source file and execute it correctly.  Apparently you retrieved the source code by getting into edit mode in my original entry.  Thanks for the backticks suggestion.  I've now edited my original version as suggested.  (The λ didn't get copied into my Windows source file, but the program ran anyway.)  (I'm in a steep learning curve at the moment.)

**Comment by sylee957** [comment]
```python
mEigenValues = Matrix(mEigenValues).evalf()
```

You may have been using eigenvalues of floating point values, and currently, SymPy is not very numerically stable for these kind of equations.

And you may already know that, you have to use algebraically exact eigenvalues, or a tiny numerical residual can cause the whole eigensystem to be invalid (If the routine itself is not been based on the numerical approximations)

<img src="https://user-images.githubusercontent.com/34944973/54434931-b5981e80-4772-11e9-8802-ff9123eb6d44.png" width="512px">

Instead, you may have to solve this equation

<img src="https://user-images.githubusercontent.com/34944973/54435052-f8f28d00-4772-11e9-9e3c-0cecae9b618d.png" width="786px">

And, for getting a non-trivial solution, you may better have to use `nullspace`, than calling `solve`.

**Comment by kholdeman** [comment]
Thanks for your help.  I’m aware that rounding errors can affect the Eigen calculations.  My verification was that the full Eigen calculation results were correct to within around 1e-15 which I find acceptable.  I tried feeding the sy.solve Eigen vectors directly into the first Eigen value calculation, but it hasn’t solved it for at least 1.5 hour as opposed to minimal time for the evalf() version.  How long do you suggest I wait?
    
Is the code below what you had in mind for performing the nullspace calculation?  It returns an empty list for that calculation.

My focus on this problem is the sy.solve routine.  It finds answers for some of the matrices I've tried, but a few it doesn't.  I'm wondering, if it can't solve this problem, are there other similar, non-Eigen problem types it will also struggle with?  For now, the sympy eigenvects() routine gives me the answer I need.
```python
import numpy as np
import sympy as sy
from sympy.matrices.dense import Matrix
from sympy import symbols as syms
import pdb
from pdb import set_trace as ST

Am = Matrix ([[15,-4,1],[-10,12,-6],[20, 4, -2]])
x1, x2, x3 = syms('x1:4')
x = Matrix([[x1, x2, x3]]).T
λ = syms('λ')
I3 = sy.eye(Am.shape[0])
mEigenValues = sy.solve(sy.Eq((Am - λ*I3).det(), 0), λ)  # Okay
print('Eigenvalues=', mEigenValues)
# mEigenValues = Matrix(mEigenValues).evalf()
# print("\nHere's sympy's evalf() Eigenvalues=\n", mEigenValues, "\n")

print('##############################################################')
print("Here's sympy's nullspace report:")
for ev in mEigenValues:  # [-0.3722813232690143, 5.37228132326901]:
    print('ev=', ev)
    DotAmx = Am*x  # Matrix([Am.dot(x)]).T
    evx = ev*x
    # Sol = sy.solve(sy.Eq(DotAmx, evx))
    # print('Sol=', Sol)
    Nullspace = (DotAmx - evx).nullspace()  # - - - - - - - - - - - - Here’s the nullspace calculation
    print('Nullspace=', Nullspace)
    print()
```

**Comment by oscarbenjamin** [comment]
You aren't using nullspace correctly since you're asking for the null space of a vector rather than a matrix. Try:
```
(Am - ev*eye(3)).nullspace()
```

**Comment by kholdeman** [comment]
Thanks.  That worked for the exact solution.  Mr. Lee's comment was correct that using the evalf() value is off enough that the nullspace method didn't find the solution.  From my perspective, it would be nice if sy.solve performed the nullspace calculation for me if the null solution was found.  I'm guessing a fairly straight forward (detailed) addition.  Although making this sy.solve enhancement wouldn't help without knowing the difference between an exact solution and the evalf() version.  I'm willing to close this issue for now, but could I add a comment later to this issue if I have a follow-up question?

**Comment by oscarbenjamin** [comment]
I think that your issue here represents a reasonable suggestion for improvement to `solve` but now that we have identified the problem it might be better to open a separate issue (referring back to this one) for it. Essentially you want solve to give a solution (or family of solutions) for an underdetermined system but it doesn't always do so. In some cases it does:
```
In [5]: solve([x+y], [x,y])                                                                                                                                   
Out[5]: {x: -y}
```

**Comment by kholdeman** [comment]
Another problem report, [sympy Issue Report #16590](https://github.com/sympy/sympy/issues/16590), was opened as oscarbenjamin suggested referencing this problem.  If that looks like what he had in mind, should I close this one?

**Comment by oscarbenjamin** [comment]
A few things were discussed here. If you think the other issue covers all that needs fixing in SymPy then this one can be closed.

**Comment by kholdeman** [comment]
See [Solving an Underdetermined System #16590](https://github.com/sympy/sympy/issues/16590), for a more concise discussion of this issue.
