### ISSUE TITLE
Optional dependencies test failing

### ISSUE THREAD

**Issue by sylee957** [sympy/sympy#16264]
https://travis-ci.org/sympy/sympy/jobs/506581245
https://travis-ci.org/sympy/sympy/jobs/506571691

I see some recent jobs failing while grepping the libraries.
Restarting does not help

**Comment by jksuom** [comment]
Would it be possible to run those tests on 3.7?

**Comment by sylee957** [comment]
Unfortunately, none of other versions are working
https://travis-ci.org/sylee957/sympy/jobs/506706490
https://travis-ci.org/sylee957/sympy/jobs/506706489
I ran the roulette on my local travis, though

**Comment by sylee957** [comment]
Guess it’s succeeding after 
https://travis-ci.org/sympy/sympy/jobs/506806064

**Comment by asmeurer** [comment]
These are just conda 500 errors, right?

**Comment by sylee957** [comment]
Yes. But it had been failing constantly for some hours.
Were there any issues upstream?
