### ISSUE TITLE
BlockMatrix not forming a single matrix in some cases

### ISSUE THREAD

**Issue by oscargus** [sympy/sympy#16278]
Consider the following code:
https://github.com/sympy/sympy/blob/3d8300a569cfeed57bd36908240862ca330204b0/sympy/utilities/tests/test_wester.py#L1322-L1343

The comments are incorrect. However, the resulting matrix is
![image](https://user-images.githubusercontent.com/8114497/54477006-cf357680-4803-11e9-8e91-01c90da477be.png)

so the BlockMatrix consists of several BlockMatrices. Note that A22 is a single matrix, so something (do not) happen when merging in two dimensions.

**Comment by AnimeshSinha1309** [comment]
Can I please try to work on this issue. I see the following example is a simpler version of the same.
```python
>>> X1 = Matrix([1])
>>> X2 = Matrix([2])
>>> BlockMatrix([X1, X2])
Matrix([
[1],
[2]])
>>> BlockMatrix([[X1], [X2]])
Matrix([
[Matrix([[1]])],
[Matrix([[2]])]])
```

**Comment by oscargus** [comment]
Sure! Go ahead!

(If you see indications in the code that it should be like this, it can be worth rethinking, but I can personally not see any reason for it. Or there should at least be a method to convert it to a "real" matrix.)

**Comment by oscargus** [comment]
After checking the code it may be that it is supposed to be like this. However, it should be useful to convert it to a regular matrix and/or that the comparison works properly... So it may be that there is nothing to fix here...

**Comment by AnimeshSinha1309** [comment]
Yeah, there might be no code to change, but if that is true then we can fix the tests. I am unsure of what to do, but adding a either changing the code here to convert the matrices to lists before merging:
https://github.com/sympy/sympy/blob/41490b75f3621408e0468b0e7b6dc409601fc6ff/sympy/matrices/immutable.py#L62
Or to change the tests change by adding a call to `ImmutableDenseMatrix.tolist()`.

**Comment by oscargus** [comment]
I have not worked with this part either, so I am not sure how it should behave. My guess is that a BlockMatrix and a Matrix should be equal if they have the same elements, independent of how the BlockMatrix is constructed, but I am not fully sure that is the case...

**Comment by oscarbenjamin** [comment]
I think maybe this is how it is supposed to work:
```julia
In [11]: BM = BlockMatrix([[ones(2), zeros(2)], [zeros(2), ones(2)]])                                                                                         

In [12]: BM                                                                                                                                                   
Out[12]: 
⎡⎡1  1⎤  ⎡0  0⎤⎤
⎢⎢    ⎥  ⎢    ⎥⎥
⎢⎣1  1⎦  ⎣0  0⎦⎥
⎢              ⎥
⎢⎡0  0⎤  ⎡1  1⎤⎥
⎢⎢    ⎥  ⎢    ⎥⎥
⎣⎣0  0⎦  ⎣1  1⎦⎦

In [13]: BM.as_explicit()                                                                                                                                     
Out[13]: 
⎡1  1  0  0⎤
⎢          ⎥
⎢1  1  0  0⎥
⎢          ⎥
⎢0  0  1  1⎥
⎢          ⎥
⎣0  0  1  1⎦
```

The example you've given doesn't make sense as a block matrix though because the dimension don't match up.

Probably the auto-concatenation for one dimension should be prevented.

**Comment by oscargus** [comment]
Well, somehow they do match up. I'm not arguing if it is a good example or not. It should be possible to convert to an explicit matrix, so now that I know the name of the method: 

@AnimeshSinha1309 if you want, you can make sure that `as_explicit()` returns a proper matrix instead of failing as:

```
>>> B.as_explicit()
Traceback (most recent call last):

  File "<ipython-input-41-2c2c77629ff2>", line 1, in <module>
    B.as_explicit()

  File "C:\Users\Oscar\sympy\sympy\matrices\expressions\matexpr.py", line 304, in as_explicit
    for i in range(self.rows)])

  File "C:\Users\Oscar\sympy\sympy\matrices\expressions\matexpr.py", line 304, in <listcomp>
    for i in range(self.rows)])

  File "C:\Users\Oscar\sympy\sympy\matrices\expressions\matexpr.py", line 303, in <listcomp>
    for j in range(self.cols)]

  File "C:\Users\Oscar\sympy\sympy\matrices\expressions\matexpr.py", line 253, in __getitem__
    return self._entry(i, j)

  File "C:\Users\Oscar\sympy\sympy\matrices\expressions\blockmatrix.py", line 173, in _entry
    return self.blocks[row_block, col_block][i, j]

  File "C:\Users\Oscar\sympy\sympy\matrices\expressions\matexpr.py", line 252, in __getitem__
    if self.valid_index(i, j) != False:

  File "C:\Users\Oscar\sympy\sympy\matrices\expressions\matexpr.py", line 238, in valid_index
    (self.rows is None or

  File "C:\Users\Oscar\sympy\sympy\matrices\expressions\matexpr.py", line 158, in rows
    return self.shape[0]

  File "C:\Users\Oscar\sympy\sympy\matrices\expressions\blockmatrix.py", line 61, in shape
    numrows += M[i, 0].shape[0]

AttributeError: 'Integer' object has no attribute 'shape'
```

**Comment by oscarbenjamin** [comment]
In a block matrix all blocks in the same block-column should have the same number of columns. Likewise all blocks in the same block-row should have the same number of rows. Otherwise the block matrix formulas don't apply.

BlockMatrix allows passing in inconsistent objects (which it shouldn't):
```julia
In [24]: BlockMatrix([[1, ones(2, 2)], [zeros(5, 1), Symbol('x')**2]])                                                                                        
Out[24]: 
⎡     ⎡1  1⎤⎤
⎢ 1   ⎢    ⎥⎥
⎢     ⎣1  1⎦⎥
⎢           ⎥
⎢⎡0⎤        ⎥
⎢⎢ ⎥        ⎥
⎢⎢0⎥        ⎥
⎢⎢ ⎥     2  ⎥
⎢⎢0⎥    x   ⎥
⎢⎢ ⎥        ⎥
⎢⎢0⎥        ⎥
⎢⎢ ⎥        ⎥
⎣⎣0⎦        ⎦

In [25]: _.as_explicit()                                                                                                                                      
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-25-1c7e4e509267> in <module>
----> 1 _.as_explicit()

~/current/sympy/sympy/sympy/matrices/expressions/matexpr.py in as_explicit(self)
    302         return ImmutableDenseMatrix([[    self[i, j]
    303                             for j in range(self.cols)]
--> 304                             for i in range(self.rows)])
    305 
    306     def as_mutable(self):

~/current/sympy/sympy/sympy/matrices/expressions/matexpr.py in rows(self)
    156     @property
    157     def rows(self):
--> 158         return self.shape[0]
    159 
    160     @property

~/current/sympy/sympy/sympy/matrices/expressions/blockmatrix.py in shape(self)
     59         M = self.blocks
     60         for i in range(M.shape[0]):
---> 61             numrows += M[i, 0].shape[0]
     62         for i in range(M.shape[1]):
     63             numcols += M[0, i].shape[1]

AttributeError: 'One' object has no attribute 'shape'
```

It should be possible to convert the example to an explicit matrix but not by creating an inconsistent intermediate matrix in between.

The error you've shown is a bug somewhere in this though...

**Comment by oscargus** [comment]
I do not worry to much about the block matrix as such, but it would, as you say, be useful to be able to create a Matrix in this way.

**Comment by smichr** [comment]
Perhaps like this?
```python
def B(ntop, matrices):
  """Return a matrix filled by provided submatrices.
  Submatrices must be in order from left to right, top to
  bottom order; there are ntop matrices in the top row.

  Examples
  ========

  >>> from sympy import ones
  >>> B(3, [ones(2,1), ones(3,3)*2, ones(2,2)*3,
  ...   ones(1,1)*4, ones(2,2)*5, ones(1,2)*6, ones(1,2)*7])
  Matrix([
    [1, 2, 2, 2, 3, 3],
    [1, 2, 2, 2, 3, 3],
    [4, 2, 2, 2, 5, 5],
    [6, 6, 7, 7, 5, 5]])
  """
  b = matrices
  q = list(range(len(b)))
  dat = [i.rows for i in b]
  active = [q.pop(0) for _ in range(ntop)]
  cols = sum([b[i].cols for i in active])
  rows = []
  while any(dat):
      r = []
      for a, j in enumerate(active):
          r.extend(b[j][-dat[j], :])
          dat[j] -= 1
          if dat[j] == 0 and q:
              active[a] = q.pop(0)
      if len(r) != cols:
        raise ValueError('gaps detected')
      rows.append(r)
  return Matrix(rows)
```

**Comment by oscargus** [comment]
Yes, something like that may also be useful. However, I also think that it can be useful to somehow "just concatenate" matrices as in the example (i.e. not have to specify the number of matrices in a row etc, the dimensions are correct in the example). I do not object on having both functionalities though.

I guess that two things emerged here (which I wasn't aware of):
 - [ ] BlockMatrix should return an error on construction of matrices that are not really block matrices (i.e. block matrix algorithms cannot be applied)
 - [ ] There should be a way to construct explicit matrices similar to BlockMatrix, although the requirements on the block matrix algorithm suitability does not have to apply.

Possibly the first can return a non-BlockMatrix instead? Or are there instances where one really would like to have a BlockMatrix? (Of course, one may want to keep it as a BlockMatrix to simplify some algorithms, but are there special methods that can only be applied to BlockMatrices?)

**Comment by smichr** [comment]
> are there special methods that can only be applied to BlockMatrices

I wouldn't say "only", rather, there are methods that are optimized based on the structure. See, for example, notes on inversion [here](https://en.wikipedia.org/wiki/Block_matrix).

**Comment by oscargus** [comment]
Definitely, that is what I meant. With methods, I referred to Sympy methods, so any calls that only exists for BlockMatrix. If not, I do not see the, strict, problem with allowing the input as in the example and return a Matrix rather than a BlockMatrix. All subsequent operations will still work, although they may not be as efficient.

**Comment by smichr** [comment]
Just occurred to me: the right thing to do is make vertical and horizontal lines go through all interior corners of non-aligning block and return a BlockMatrix with those identified blocks as the new blocks, e.g.
```
Matrix([
    [1, 2, 2, 2, 3, 3],
    [1, 2, 2, 2, 3, 3],
    [4, 2, 2, 2, 5, 5],
    [6, 6, 7, 7, 5, 5]])

Matrix([
    [1, | 2, | 2, 2, | 3, 3],
    [1, | 2, | 2, 2, | 3, 3],
--------+----+-------+------
    [4, | 2, | 2, 2, | 5, 5],
--------+----+-------+------
    [6, | 6, | 7, 7, | 5, 5]])
```
Now each row has 4 blocks.

**Comment by smichr** [comment]
I reviewed the [source](https://math.unm.edu/~wester/cas/book/Wester.pdf) of this test and the matlab [page about creating matrices](https://www.mathworks.com/help/matlab/math/creating-and-concatenating-matrices.html). I think the chosen test is obtuse: rows of matrices should share a common row height and each row (once concatenated) should have the same number of columns.

**Comment by oscargus** [comment]
Yes, it is probably chosen to provide some distinction between functionalities. I think this test does that though, right? It is only the fact that the number of columns in the concatenated matrices differs that could not be handled (at least not with `BlockMatrix`, but then there are good reasons for that). As I mentioned in #16454 I agree with you that it is probably better to allow something like this directly in `Matrix` as the functionality as such is quite useful.
