### ISSUE TITLE
Equality should return None if no condition is given.

### ISSUE THREAD

**Issue by ShubhamKJha** [sympy/sympy#16286]
In the following code segment
```py
>>> from sympy import Q,ask,symbols
>>> x,y = symbols('x y')
>>> x == y
False
>>>
```
Since the symbols don't have other relations, the result should have been `None` instead of `False`. Is it the desired behaviour?

**Comment by sylee957** [comment]
I guess it should

<img src="https://user-images.githubusercontent.com/34944973/54486074-4af7f780-48c6-11e9-9a17-8250ae3a53ff.png" width="256px">

`__eq__` for basic objects designed to quickly test if both symbolic expressions are in the exactly same tree form, without much concerns of mathematical properties, by hash testing.

You would have to get the result as you desired, you may have to use `(x - y).is_zero`, or even symbolic relational like `Eq(x, y)`, which are designed to handle mathematical properties.

So, I guess the first one would only be valid, for situations where exact formatting comparisons are needed,
and if you have to use more smarter one with some cost of performance, you have to use latter methods, furthermore mixed with `simplify` or such.

There is a tutorial section for this
https://docs.sympy.org/latest/tutorial/gotchas.html#equals-signs

You may also have to see issue #16089

**Comment by ShubhamKJha** [comment]
Thanks @sylee957 I think I should close this issue.
