### ISSUE TITLE
No function to calculate force in rigid body file

### ISSUE THREAD

**Issue by abhinavsagar** [sympy/sympy#16290]
There is no function to calculate the force acting on a body in **rigidbody`** file in **mechanics** module. I wonder how such an important feature might be missing.

**Comment by arooshiverma** [comment]
@abhinavsagar 
Should another function be added which takes in all the forces and calculate the net force?

**Comment by abhinavsagar** [comment]
@arooshiverma Yes . If you are working on it, let me know.

**Comment by arooshiverma** [comment]
Yes I'll work on it.

**Comment by arooshiverma** [comment]
I am thinking that we can take all the force vectors in an array which we'll pass as a parameter to the function. And then do the vector addition of all the forces.
Any suggestions/criticism on this?

**Comment by abhinavsagar** [comment]
@arooshiverma That looks good but make sure to take acceleration into account appropriately. I think you'll have to make use of helper functions and integrate those with already present fucntions. Make a PR and we'll see.

**Comment by czgdp1807** [comment]
Closing this in reference to https://github.com/sympy/sympy/pull/16320#issuecomment-566892928
Thanks for raising the issue.
