### ISSUE TITLE
collect_const() does cannot collect rationals

### ISSUE THREAD

**Issue by mpjuers** [sympy/sympy#16296]
`collect_const()` does not seem to support the collecting of numeric rationals in SymPy 1.3. This is probably a duplicate of [13107](https://github.com/sympy/sympy/issues/13107), but I've provided a description below.

    In [41]: var('a:d')
    In [42]: f = a + b + c / 2 + d / 2
    In [43]: print(collect_const(f, Rational(1, 2), Numbers=True))
    a + b + (c/2 + d/2)

I'm expecting `a + b + 1 / 2 * (c + d)`

**Comment by AnimeshSinha1309** [comment]
I would like to work on fixing this issue.

**Comment by anubhav4sachan** [comment]
> 
> 
> I would like to work on fixing this issue.

Are you still working on this issue?

**Comment by AnimeshSinha1309** [comment]
I am sorry, did not manage to work on this yet, trying to resume.
I believe that the issue is being cause by `Factors.div`, where the behvaior for `a*2` and `a/2` changes:
https://github.com/sympy/sympy/blob/aefdd023dc4f73c441953ed51f5f05a076f0862f/sympy/simplify/radsimp.py#L618-L621
```python
>>> Factors(a/2)
Factors({1/2: 1, a: 1})
>>> Factors(2*a)
Factors({2: 1, a: 1})
>>> Factors(1/2)
Factors({0.500000000000000: 1})
>>> Factors(2)
Factors({2: 1})
>>> Factors(1/2*a).div(Factors(1/2))
(Factors({a: 1}), Factors({}))
>>> Factors(2*a).div(Factors(1/2))
(Factors({2: 1, a: 1}), Factors({0.500000000000000: 1}))
>>> Factors(a/2).div(Factors(1/2))
(Factors({1/2: 1, a: 1}), Factors({0.500000000000000: 1}))
```
I don't know if this will take changes to the `Factors` class or the `collect_const()` function.
Please do tell me what the expected behavior for both these functions should be, and if everything here looks OK.

**Comment by jksuom** [comment]
> Factors({1/2: 1, a: 1})

I think that this is expected to be `Factors({2: -1, a: 1})`, in the same way as `Factors(S(1)/2)` becomes `Factors({2: -1})`.

**Comment by AnimeshSinha1309** [comment]
This is what I wanna do to fix the issue, the problem is that the Number Half is not a rational, any way around this issue?
```python
factors = dict(Mul._from_args(c).as_powers_dict())
# Handle all rational Coefficients
for f in factors.keys():
    if type(f) is Rational:
        factors[f.p] = (factors[f.p] if f.p in factors else 0) + factors[f]
        factors[f.q] = (factors[f.q] if f.q in factors else 0) - factors[f]
        factors.pop(f)
```

**Comment by jksuom** [comment]
>  the problem is that the Number Half is not a rational

That should be no problem as it is an instance of Rational.
```
In [1]: isinstance(S.Half, Rational)
Out[1]: True
```
