### ISSUE TITLE
No function to calculate linear and angular acceleration of a Rigid Body

### ISSUE THREAD

**Issue by arooshiverma** [sympy/sympy#16310]
There doesn't exist any function to calculate the linear or angular acceleration of a Rigid Body in the mechanics folder

**Comment by sylee957** [comment]
Ref #16290

**Comment by abhinavsagar** [comment]
@arooshiverma I think you could work on this one also as this is more or less similar to the other one.

**Comment by arooshiverma** [comment]
Yes I am working on this.

**Comment by czgdp1807** [comment]
Closing this in reference to https://github.com/sympy/sympy/pull/16320#issuecomment-566892928
Thanks for raising the issue.
