### ISSUE TITLE
For non-real expressions isn't the is_positive property always False?

### ISSUE THREAD

**Issue by ShubhamKJha** [sympy/sympy#16313]
Consider the following code using master
```py
In [1]: from sympy import Q, ask, symbols
In [2]: x,y = symbols('x y', real=False)
In [3]: (x).is_positive
Out[3]: False
In [4]: (x*y).is_positive
In [5]: (-x).is_positive
In [6]:
```
First two results I understand. Should not the third result be `False`? Since `x` is not-real therefore `(-x)` should also be not real.

**Comment by jksuom** [comment]
I agree. It seems that the wrong value `real=None` is entered into `_assumptions` of `-x` when it is created.

**Comment by ShubhamKJha** [comment]
No actually `real = None` may apply no assumptions is given to it. Infact I am looking into the core files to grasp the logic behind all the old assumptions and I think the code for `_eval_pos_neg`(called by `_eval_is_positive`) is wrong in `Mul` class. If my case is correct I will fix it then.

**Comment by ShubhamKJha** [comment]
@jksuom you are right `_assumptions` is calling assumptions related functions. And the code in `Mul` is wrong for sure, I fixed this in new assumptions at #16213 and will improve the code of old assumptions also.

**Comment by ShubhamKJha** [comment]
I believe something more is there
```py
>>> from sympy import symbols
>>> p = symbols('p', real=False)
>>> (-p).is_real
>>> q = symbols('q', real=False, complex=True)
>>> (-q).is_real
False
>>>
```
Do you understand the assumptions happening here? Are there any non-real numbers when multiplied by `-1` produces real numbers?
I have been going through `core` modules to understand the logic of old assumptions. But there are mostly no comments and sometimes even the code seems to be a rough-work. The fact that they get their work done is amusing.

**Comment by ShubhamKJha** [comment]
@asmeurer what is your opinion about this?

**Comment by oscarbenjamin** [comment]
It looks like you understand the problem and how to fix it so I would just go open a PR. You don't need to wait for opinions.
