### ISSUE TITLE
Increase test coverage

### ISSUE THREAD

**Issue by oscargus** [sympy/sympy#16318]
As Codecov is now actively reporting the coverage status for Sympy it is also a good idea to try to increase the test coverage.

Go to: https://codecov.io/gh/sympy/sympy and click on "sympy" at the bottom where it says files. You will now see all the modules and the coverage of these. There are columns with green, yellow and red dots. Green are covered, yellow are partially covered (e.g. an if-clause which has only evaluated to true, not to false), and red which are not covered.

As you can see some modules are well covered, some less well (quite a lot of the not covered lines comes from the rubi integral module which is currently not tested at all, and if I understand correctly is not ready for use).

The task is to write tests that uses the red lines (and the yellow lines in a new way).

For test that creates exceptions one writes:
`raises(ExpextedError, lambda: function_call_that_causes_the_error)`

For the other tests it is not just about covering the code, it is also required that the result is correct. If one is unsure, there may be examples in the documentation that if nothing else can be added.

When creating a pull request please write `NO ENTRY` for the release note description.

Finally, note that some things are inherently hard to cover. For example, things that reads from and writes to files and things that rely on external libraries as these are not included in the test coverage runs (except for mpmath). The same thing for interactive commands and for plot commands.

**Comment by tusharlock10** [comment]
I want to help regarding this

**Comment by tusharlock10** [comment]
Can you tell me a bit how to increase coverage?

**Comment by oscargus** [comment]
Have you read the above? Probably better that you ask questions, but basically: find code that is not tested/covered, add tests so that it is covered. You can for example look at #16303 and #16325 to see what it may look like. There is a directory `tests` in every module and a file `test_yyy` that is for the file `yyy` (most of the time).

**Comment by kangzhiq** [comment]
Hello, I would like to work on this issue.  I have 2 questions:
1. Just for sure, by saying this:

> The task is to write tests that uses the red lines (and the yellow lines in a new way).

do you mean that we should add tests to the lines missed and lines partials? The verb 'uses' make me a little bit confused.

2. Based on what you said and the coverage of each module, may I start with utilities or deprecated or geometry to find missed test?

Thank you!

**Comment by oscargus** [comment]
Correct! Uses may not be the correct word, no.

Sure, go ahead!

**Comment by ritesh99rakesh** [comment]
@oscargus could you give an example for exceptions error, I am not able to figure it out.

**Comment by oscargus** [comment]
@ritesh99rakesh Looking at Codecov one can see that e.g. the exception in the following function is not tested:
https://github.com/sympy/sympy/blob/master/sympy/combinatorics/graycode.py#L387-L408

To test this we would like to enforce inputs that causes the if-clause to be true, e.g. `get_subset_from_bitstring(['c', 'a', 'c'], '1100')` (super_set has length 3, bitstring length 4).

This can be confirmed as:
```
In [1]: from sympy.combinatorics.graycode import get_subset_from_bitstring

In [2]: get_subset_from_bitstring(['c', 'a', 'c'], '1100')
   ...: 
Traceback (most recent call last):

  File "<ipython-input-2-c58d0133e833>", line 1, in <module>
    get_subset_from_bitstring(['c', 'a', 'c'], '1100')

  File "C:\Users\Oscar\sympy\sympy\combinatorics\graycode.py", line 406, in get_subset_from_bitstring
    raise ValueError("The sizes of the lists are not equal")

ValueError: The sizes of the lists are not equal
```


A test would hence look like:
`raises(ValueError, lambda: get_subset_from_bitstring(['c', 'a', 'c'], '1100'))`

(Which I just added in an upcoming PR, but there are plenty of other untested exceptions in almost every module.)

**Comment by Sc0rpi0n101** [comment]
I have tried this for the stats module in #16557 

Would anyone like to review the changes?

**Comment by BasileiosKal** [comment]
Hello, i made a pr yesterday to increase the coverage for the Quaternion.py file. Could you please review the changes? I also would like to keep working on this if that’s ok.

**Comment by wuziqiqiqi** [comment]
Hello, I was trying to write tests for intpoly.py. However, when I try to run test_intpoly.py using coverage, I only got 6% of line coverage. Is there any other test file I need to include? or any suggestion for why that number doesn't match what's on codecov, which is 71.459% ?

**Comment by oscarbenjamin** [comment]
I ran the tests for coverage using `pytest`:
```
$ pytest sympy/integrals/tests/test_intpoly.py --cov=sympy.integrals.intpoly --cov-report=html
```
That gives 85% coverage. I wonder if some of the uncovered code is actually needed though. The module seems to have a lot of random geometry functions.

Excluding the slow tests:
```
$ pytest -m 'not slow' sympy/integrals/tests/test_intpoly.py --cov=sympy.integrals.intpoly --cov-report=html
```
gives a coverage of 80%. Note that codecov reports the coverage not including slow tests. I think we should aim to increase coverage with tests that are not slow and only use slow tests where they are unavoidable.

**Comment by BenSandeen** [comment]
Hi!  I'm brand new to this project, so I thought I'd start by adding tests that verify that exceptions are being thrown when they should be.

However, I've found a few instances where exceptions should probably be thrown but aren't.  When I run pytest with these tests, it of course fails, and it tells me not to commit.  I'm not exactly familiar enough with the code base to make some of the fixes to the code, but I don't want to get rid of these tests that catch legitimate edge cases.

What should I do in this scenario?

**Comment by oscarbenjamin** [comment]
If you open a pull request with the added tests then maybe someone can help you figure out what to do for the cases that should raise errors (or can advise whether they should be errors).

**Comment by oscargus** [comment]
I close this as we currently do not have a good idea how to systematically deal with coverage.

**Comment by oscarbenjamin** [comment]
> I close this as we currently do not have a good idea how to systematically deal with coverage.

I think we do want coverage. I didn't enable codecov in Actions just partly because I didn't have time but also because it seemed to be unreliable and I wanted to know if there was a better alternative.

One approach would be to do something like the benchmarks job on Actions and then use something like `diff-cover` to produce a report for the "comment on PR" Actions workflow.

It's also possible that Codecov has improved. The problems I remember with it were:

1. It was unreliable in its report of overall coverage and often said things like "this PR will decrease coverage by 20%" for no apparent reason.
2. Only the diff coverage seemed meaningful but it didn't update after the PR was pushed again so after trying to increase coverage the updated results were not shown.
3. It was very slow to load in the web UI if you tried to look at the what was covered or not.
