### ISSUE TITLE
Simple Matrix Expression does not evaluate to Zero

### ISSUE THREAD

**Issue by hsaliak** [sympy/sympy#16326]
A simple Matrix Expression created with the following code does not evaluate to zero as expected
```
x = MatrixSymbol('x',2,2)                                               
y = MatrixSymbol('y',2,2)  
Matrix((x.T*y - y.T * x)).equals(zeros(*x.shape))  # expect this to return True
```
Expect: last statement to return `True`
Actual: the last statement returns `None`

The doc
https://docs.sympy.org/latest/tutorial/matrices.html#zero-testing explains this limitation and suggests filing an issue whenever such a scenario is discovered - 
_discovery of any zero test failings can provide some good examples to improve SymPy, so if you have encountered one, you can report the issue to SymPy issue tracker [8] to get detailed help from the community._

I am using:
Name: sympy version: 1.3
Requires: mpmath
Python Version: 3.7

**Comment by oscarbenjamin** [comment]
What makes you think that this should be zero? I get:
```
In [28]: x = MatrixSymbol('x',2,2)                                                
    ...: y = MatrixSymbol('y',2,2)   
    ...: Matrix((x.T*y - y.T * x))                                                                                                             
Out[28]: 
⎡                  0                     x₀₀⋅y₀₁ - x₀₁⋅y₀₀ + x₁₀⋅y₁₁ - x₁₁⋅y₁₀⎤
⎢                                                                             ⎥
⎣-x₀₀⋅y₀₁ + x₀₁⋅y₀₀ - x₁₀⋅y₁₁ + x₁₁⋅y₁₀                    0                  ⎦
```
That would be zero if the matrices were symmetric but we don't know that they are.

**Comment by hsaliak** [comment]
OK That was PEBCAK, I will close the issue.
