### ISSUE TITLE
S(0)**real(!=0) should be (0 or zoo) and hence non-positive. 

### ISSUE THREAD

**Issue by ShubhamKJha** [sympy/sympy#16332]
Consider the following code from master:
```py
>>> from sympy import symbols, ask, Q
>>> from sympy.abc import x,y,z
>>> p = symbols('p', real=True, zero=False)
>>> q = symbols('q', zero=True)
>>> (q**p).is_positive
>>>
```
Since `0**a`(where a is real and non-zero) should always be (0 or `zoo`). Therefore, the result should have been `False`.

**Comment by ShubhamKJha** [comment]
Also in the master, the following code segment works:
```py
In [7]: from sympy import symbols

In [8]: p = symbols('p', zero=True)

In [9]: q = symbols('q', odd=True)

In [10]: (p**q).is_positive
Out[10]: False
```

**Comment by sandeepbvv11** [comment]
> ```python
> (q**p).is_positive
> ```

**Comment by sandeepbvv11** [comment]
>>> from sympy import symbols, ask, Q
>>> from sympy.abc import x,y,z
>>> p = symbols('p', real=True, zero=False)
>>> q = symbols('q', zero=True)
>>> (q**p).is_positive
>>>

I dont think for this it should return false as zero is neither positive nor negative and we check for positive if it is greater than zero and negative if it is less than zero. I think it should return something like undetermined for these cases.

**Comment by ShubhamKJha** [comment]
Since zero is not positive the result should be `None`  there's no ambiguity in it. Also because the other result can be `zoo` which is also not considered positive.
