### ISSUE TITLE
No function for calculating polar moment of inertia and section modulus in continuum_mechanics in beam.py

### ISSUE THREAD

**Issue by abhinavsagar** [sympy/sympy#16392]
There is currently no function to calculate polar moment of inertia and section modulus of the beam . Both of these quantities are important in further future works in this module.

**Comment by arooshiverma** [comment]
Can I work on this?

**Comment by abhinavsagar** [comment]
Sure, feel free.

**Comment by arooshiverma** [comment]
Here the Beam is 2D, so along what axis should the polar moment be? Usually it is along the beam, right?

**Comment by abhinavsagar** [comment]
@arooshiverma There is a separate class for 3D beams. Checkout from line no 1493. I think you'll have to calculate it in all 3 directions.

**Comment by arooshiverma** [comment]
Yeah got it. Will do it.

**Comment by arooshiverma** [comment]
I think it'll be better if we just determine it wrt the axis perpendicular to the area we input in the definition of the 3D Beam. As that's the one used in further calculations(usually) and it's difficult to represent the other 2 polar MOIs as the axes here are ambiguous.
