### ISSUE TITLE
[Discussion] markov chain implementation idea

### ISSUE THREAD

**Issue by kangzhiq** [sympy/sympy#16391]
Hello,

I am a student who wants to work with SymPy for GSoC 2019. I would like to ask for some advice about contributing to the Probability module.

Since I am interested in the project Probability [https://github.com/sympy/sympy/wiki/GSoC-2019-Ideas#probability](url), especially in topics like implementing stochastic processes: markov chain, random walks, etc. I would like to know if you have ideas or approaches about it. 

1. After looking into the documentation of SymPy, I found the Probability module doesn't have implemented for the stochastic processes mentioned above. So firstly the implementation of these algorithms will be interesting to do.  
2. Besides, could you please tell me what else could also be added to the module? Anything relative to this topic will be wellcome.
3. If there are some high priority ideas which need to be implemented among the suggested ideas of this project, please telll me and I will be glad to accomplish it. 
4. If you have other ideas(Algorithms, new version of some function, cleaning up code, documentation to do) for this module, I am always willing to discuss with you about it. 

Thank you in advance!

**Comment by czgdp1807** [comment]
Markov chains have been added to `sympy.stats`. Closing this for now. Thanks for the contributions.
