### ISSUE TITLE
Piecewise simplification of and/or with re/im

### ISSUE THREAD

**Issue by oscarbenjamin** [sympy/sympy#16417]
Not sure what's going on here but this Piecewise is simplifying when it should not:
```julia
In [30]: z = Symbol('z')                                                                                                                       

In [31]: Piecewise((1, Or(Eq(im(z), 0), Gt(re(z), 0))), (2, True), evaluate=False)                                                             
Out[31]: 
⎧1  for im(z) = 0 ∨ re(z) > 0
⎨                            
⎩2          otherwise        

In [32]: _.doit()                                                                                                                              
Out[32]: 1
```

**Comment by smichr** [comment]
does #16414 address this?

**Comment by oscarbenjamin** [comment]
No, I get the same result with #16414.

**Comment by oscargus** [comment]
It is not #15898 that breaks it either. The identical function is returned from `_eval_simplify()` in `Piecewise` both before and after #16414.

**Comment by oscargus** [comment]
It is the following line that messes up:
`c = c.as_set().as_relational(x)`

c = `Eq(im(z), 0) | (re(z) > 0)` and x = `z`
returns
`(-oo < z) & (z < oo)`

**Comment by oscargus** [comment]
Then, since the constraints contain `oo` and/or `-oo`, they are replaced with `True`.

**Comment by smichr** [comment]
So perhaps you can't use `as_set` when the variable involves the `re` function because it could contain an imaginary part`?

**Comment by smichr** [comment]
I see that there is already a check for a complex domain:
https://github.com/sympy/sympy/blob/0202faa12dbcdee2330ce768294fc2fb2a1d0108/sympy/functions/elementary/piecewise.py#L962-L970
