### ISSUE TITLE
add sympy.printing Markdown format

### ISSUE THREAD

**Issue by evan0greenup** [sympy/sympy#16416]
If there is a function in sympy.printing for printing expression as markdown formula. It would be awesome.

**Comment by oscarbenjamin** [comment]
What does "markdown formula" mean? Normally mathematical expressions are included with embedded latex in markdown/rst.

The latex form is readily available:
```julia
In [35]: latex(x**2)                                                                                                                           
Out[35]: 'x^{2}'
```

**Comment by evan0greenup** [comment]
I am not very experienced in this aspect. But here is the [link](https://csrgxtu.github.io/2015/03/20/Writing-Mathematic-Fomulars-in-Markdown/) as reference.

**Comment by oscarbenjamin** [comment]
That's just LaTeX. Sympy has a function for this as I showed.

**Comment by oscargus** [comment]
I close this issue as there is already support for what is requested.
