### ISSUE TITLE
Add algorithm to solve 'a*sin(b*x)-c*exp(d*x)'.

### ISSUE THREAD

**Issue by stevenleeS0ht** [sympy/sympy#16486]
There seems no algorithm to solve equation `a*sin(b*x)-c*exp(d*x) == 0`. If implemented it will be awesome.

**Comment by oscarbenjamin** [comment]
Do you know of an algorithm to solve this kind of equation?

What would the solutions be? Thinking graphically I guess that e.g. `sin(x)-exp(x)` would have infinitely many negative real roots. I would guess that they can't be written in closed form though. You can find some numerically with nsolve though:
```julia
In [10]: nsolve(sin(x)-exp(x), x, 0)                                                                                                           
Out[10]: -15.7079634186507

In [11]: sin(_)-exp(_)                                                                                                                         
Out[11]: -1.03283041832792e-16
```

**Comment by oscarbenjamin** [comment]
Closing as I don't think that there is a way to solve this kind of equation analytically.
