### ISSUE TITLE
collect does not respect non-commutative symbols

### ISSUE THREAD

**Issue by kmaddock** [sympy/sympy#16488]
collect() should respect non-commutative symbols

`a, b, c = symbols("a b c", commutative=False)`
`collect(a*c + b*c, c)`

Actual result:
`c(a+b)`

Expected result:
`(a+b)c`

https://live.sympy.org/?evaluate=a%2C%20b%2C%20c%20%3D%20symbols(%22a%20b%20c%22%2C%20commutative%3DFalse)%0A%23--%0A(a%20%2B%20b)%20*%20c%0A%23--%0Acollect(expand((a%20%2B%20b)%20*%20c)%2C%20c)%0A%23--%0A

**Comment by smichr** [comment]
duplicates #3741
