### ISSUE TITLE
Add missing continuous probability distributions to docs

### ISSUE THREAD

**Issue by sidhantnagpal** [sympy/sympy#16494]
See the implemented continuous probability distributions in [`crv_types.__all__`](https://github.com/sympy/sympy/blob/master/sympy/stats/crv_types.py#L67-L104) and add the missing things to https://github.com/sympy/sympy/blob/master/doc/src/modules/stats.rst.

The documented distributions can be seen at https://docs.sympy.org/dev/modules/stats.html.
It would be nice to have the implemented distributions listed as well, at the top of the module.

**Comment by znxftw** [comment]
I have gone through the files and have identified the missing names in [stats.rst](https://github.com/sympy/sympy/blob/master/doc/src/modules/stats.rst) and can start working on filling it up immediately.

> It would be nice to have the implemented distributions listed as well, at the top of the module.

Was this in reference to stats.rst ?

**Comment by sidhantnagpal** [comment]
> Was this in reference to stats.rst ?

Yes. For finite, discrete and continuous types.

**Comment by znxftw** [comment]
I've submitted a PR #16497 making the required changes.
