### ISSUE TITLE
is_scalar is true for matrix symbols and expressions?

### ISSUE THREAD

**Issue by sylee957** [sympy/sympy#16510]
```python
>>> from sympy import *
>>> A = MatrixSymbol('A', 3, 3)
>>> A.is_scalar
True
```

I see `is_scalar` was introduced in #15049

Edit
See current status at https://github.com/sympy/sympy/issues/16510#issuecomment-592611393

**Comment by arooshiverma** [comment]
Can you explain why it should not be scalar?

**Comment by sylee957** [comment]
Well, matrices having different numbers at each slots are not evidently scalars.
Though I'm not very clear about the definitions for 1*1 matrix, or such like
http://mathworld.wolfram.com/ScalarMatrix.html to be considered scalar, so that it can be properly interpreted by SymPy

**Comment by asmeurer** [comment]
The release notes for that PR say is_scalar has something to do with differentiation? @smichr

**Comment by arooshiverma** [comment]
"Expr has a default attribute is_scalar=True which makes Expr().diff(Expr()) == 1" according to the Release notes of the PR.
But,
```
>>> A=MatrixSymbol('A',3,3)
>>> A.is_scalar
True
>>> A.diff(A)==1
False
```
Also,
according to [Wikipedia](https://en.m.wikipedia.org/wiki/Matrix_calculus#Derivatives_with_matrices) quotes: "The three types of derivatives that have not been considered are those involving vectors-by-matrices, matrices-by-vectors, and matrices-by-matrices. These are not as widely considered and a notation is not widely agreed upon."

**Comment by asmeurer** [comment]
So it's specifically for things that give 1 when self differentiated instead of another identity?

**Comment by arooshiverma** [comment]
Yes. It seems so.

**Comment by arooshiverma** [comment]
I guess since the definition of a scalar matrix is different from what we percieve for normal expressions, there must be a different function for matrices. (Moreover differentiation of a matrix with respect to a matrix isn't agreed upon)

**Comment by arooshiverma** [comment]
```
  @property
    def is_scalar(self):
        if self/self[0,0] == Identity(self.shape[0]):
            return True
        return False
```

Adding this to matexpr.py file solves the issue I guess

**Comment by asmeurer** [comment]
Matrix differentiation is defined in sympy.

**Comment by asmeurer** [comment]
Also is_scalar for matrices should always be False. See the discussion at https://github.com/sympy/sympy/issues/16504.

**Comment by arooshiverma** [comment]
http://mathworld.wolfram.com/ScalarMatrix.html
According to this, Scalar matrices have a different definition as compared to the discussion at #16504.

**Comment by arooshiverma** [comment]
And if a user is typing is_scalar for a matrix, he will probably go with the definition of scalar matrices. What we can do is define a new is_scalarmatrix() and edit the is_scalar() one.

**Comment by asmeurer** [comment]
I haven't seen that term used very often. I didn't even know myself what it meant exactly until I clicked that link.

**Comment by arooshiverma** [comment]
So I guess the is_scalarmatrix() need not be added?
Only the is_scalar() should be edited so as to return false in the case of matrices?

**Comment by sylee957** [comment]
I've also found an issue with vectors.

```python
>>> from sympy.vector import CoordSys3D

>>> C = CoordSys3D('C')
>>> v = 3*C.i + 4*C.j + 5*C.k
>>> v.is_scalar
True
```

**Comment by czgdp1807** [comment]
Currently for `master`,
```python
>>> A = MatrixSymbol('A', 3, 3)
>>> A.is_scalar
False
>>> from sympy.vector import CoordSys3D
>>> C = CoordSys3D('C')
>>> v = 3*C.i + 4*C.j + 5*C.k
>>> v.is_scalar
True
```
