### ISSUE TITLE
Testing of examples?

### ISSUE THREAD

**Issue by oscargus** [sympy/sympy#16518]
While working on  #16501 I ran the examples I changed manually to see that it still worked etc. I noticed that one example has probably not been working in any Python 3 version.

Is there are simple way to run all the examples? Should there be? Maybe not during the regular tests, but maybe a way to simply run all the examples and see that there at least are no exceptions or errors would probably be useful before, e.g., releasing a new version.

**Comment by sylee957** [comment]
The examples are not tested like, doctests I guess.
Ideally, I think the examples should be translated to tutorials to be integrated with doctests.

**Comment by oscargus** [comment]
Turns out that there is a command for this. `examples/all.py` runs all the examples. I will try to enable this.
