### ISSUE TITLE
lambdify: upper/lowergamma should fail with modules='math'

### ISSUE THREAD

**Issue by cbm755** [sympy/sympy#16535]
Let
```
f = lowergamma(a, x)
```
There is no `math.lowergamma` nor `math.gammainc`, so lambdifying this without mpmath should fail and do the "unsupported function" thing.

But it does not:
```
F = lambdify((a, x), f, modules='math')
F?
Signature: F(a, x)
Docstring:
Created with lambdify. Signature:

func(a, x)

Expression:

lowergamma(a, x)

Source code:

def _lambdifygenerated(a, x):
    return (lowergamma(a, x))
```

**Comment by cbm755** [comment]
Is anything about lambdify easy to fix?  If you're willing to dig in and learn, this might be...

**Comment by AkbarHabeeb** [comment]
I am working on it @cbm755 
Since I am a newbie, let me make it clear.
In lambdify function, while using lower/uppergamma in its expressions with module=math should fail. Am I right?

**Comment by cbm755** [comment]
@AkbarHabeeb you should check if `math.uppergamma` (or similar name) exists (for example, `math.sin` exists).

**Comment by AkbarHabeeb** [comment]
For mpmath
`f = lowergamma(a, x);F = lambdify((a, x), f, modules='mpmath')
F(5,2)`
1.26367241624907

For math & numpy
`f = lowergamma(a, x);F = lambdify((a, x), f, modules='math')
F(5,2)`
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "<lambdifygenerated-188>", line 2, in _lambdifygenerated
    return (lowergamma(a, x))
NameError: global name 'lowergamma' is not defined

Here, the existing system is mentioning that the lowergamma is not there in _math_ module, which is the same for numpy as well. 

For scipy
`f = lowergamma(a, x);F = lambdify((a, x), f, modules='scipy')`
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/base/data/home/apps/s~sympy-live-hrd/56.412575950366508090/sympy/sympy/utilities/lambdify.py", line 397, in lambdify
    buf = _get_namespace(m)
  File "/base/data/home/apps/s~sympy-live-hrd/56.412575950366508090/sympy/sympy/utilities/lambdify.py", line 515, in _get_namespace
    _import(m)
  File "/base/data/home/apps/s~sympy-live-hrd/56.412575950366508090/sympy/sympy/utilities/lambdify.py", line 148, in _import
    "can't import '%s' with '%s' command" % (module, import_command))
ImportError: can't import 'scipy' with 'import numpy; import scipy; from scipy import *; from scipy.special import *' command

I tried all these things in sympy live shell. In case  #16536 we can make it generate gammainc & gammaincc for lower and upper gamma functions respectively.

I find these inferences, **can you please elaborate what you mean by 'unsupported function thing'?** 

And it will be really helpful If you can say 'how to generate below like codes?'
Signature: F(a, x)
Docstring:
Created with lambdify. Signature:
func(a, x)

Expression:
lowergamma(a, x)

Source code:
def _lambdifygenerated(a, x):
    return (lowergamma(a, x))

**Comment by AkbarHabeeb** [comment]
> @AkbarHabeeb you should check if `math.uppergamma` (or similar name) exists (for example, `math.sin` exists).

Thanks for your reply.
Yes, I searched on it. 
Findings,
mpmath : Has gammainc function, and works fine.
scipy : Has gammainc function but our code generation gives lower/uppergamma. 
numpy & math   : Don't have gammainc function.

**Comment by cbm755** [comment]
Sorry TL;DR

> can you please elaborate what you mean by 'unsupported function thing'?

try some other function that is not supported with `math` and see what lambdify does.

**Comment by fotisAnagnostopoulos** [comment]
Hello,

I would also like to try this. May i?

**Comment by asmeurer** [comment]
This isn't so simple. I'm not even sure if this is what it should do. lambdify supports multiple modules, so `lambdify((a, x), lowergamma(a, x), ['math', something else])` could still work. There are also things like `_imp_`. 

I would argue that the current behavior of not doing any namespace checking is standard in lambdify. If we want to change it, we should look into changing it wholesale, but not without considering what the implications of that are.

**Comment by cbm755** [comment]
Shouldn't it do the same as this:
````
>>> F = lambdify(x,LambertW(x),modules='math')

>>> F?
Signature: F(x)
Docstring:
Created with lambdify. Signature:

func(x)

Expression:

LambertW(x)

Source code:

def _lambdifygenerated(x):
    return (  # Not supported in Python:
  # LambertW
LambertW(x))
```

Unsupported functions get flagged as "Not supported"?  Looks straightforward enough to me...  Am I missing something?

**Comment by cbm755** [comment]
> the current behavior of not doing any namespace checking is standard in lambdify....

Then where does the above `LambertW` behaviour come from?
