### ISSUE TITLE
Point on a  field 

### ISSUE THREAD

**Issue by abhinav28071999** [sympy/sympy#16555]
Suppose i initialize a field 
v=x*y*R.i + 2*y*z*R.j + 3*x*z*R.k 
now i want to find value of v at (1,2,3). How do we do this?

**Comment by sidhantnagpal** [comment]
> How do we do this?

`subs` should work:
```py
In [4]: v.subs({x: 1, y: 2, z: 3})                                              
Out[4]: 2*R.i + 12*R.j + 9*R.k
```

**Comment by abhinav28071999** [comment]
thanks
