### ISSUE TITLE
Fix docstrings of #16516

### ISSUE THREAD

**Issue by sylee957** [sympy/sympy#16553]
#16516
See comments from @sidhantnagpal 

At least simply removing some backticks should work.

**Comment by aneesh98** [comment]
Can I make those changes?

**Comment by sylee957** [comment]
Sure, go on.
We don’t reserve a specific person to do a task though.

**Comment by Sc0rpi0n101** [comment]
@aneesh98  you still working on this issue?

**Comment by aneesh98** [comment]
Yes I am

**Comment by Sc0rpi0n101** [comment]
I have removed the extra backticks in #16564 
@aneesh98  Would you like to review that?
You can also work on other issues in the docstring

**Comment by aneesh98** [comment]
Yeah Okay Fine, I'll look for other issues.
