### ISSUE TITLE
What should be the definition of infinite?

### ISSUE THREAD

**Issue by ShubhamKJha** [sympy/sympy#16579]
Consider the following code,
```python
>>> from sympy import symbols
>>> x = symbols('x', real=True, finite=False)
>>> x.is_infinite  # None
>>>
```
Isn't `real and not finite => infinite`?

**Comment by oscarbenjamin** [comment]
I'm not sure why this happens but you are correct: it should give False.

**Comment by ShubhamKJha** [comment]
Ok then, I will update both the old and new assumptions with this.

**Comment by jksuom** [comment]
However, see the commit message of commit 48c71643.

**Comment by ShubhamKJha** [comment]
@jksuom I don't intend to change the commit [48c7164](https://github.com/sympy/sympy/commit/48c71643a7631154df8eba1f3bf12acba81c0fb4), it is correct.

Adding `complex  ->  finite | infinte` to the `_assume_rules` fixes this issue. A complex number can either be finite or infinite only.

**Comment by oscarbenjamin** [comment]
@sylee957 why have you closed this?

**Comment by oscarbenjamin** [comment]
This seems to fix it:
```diff
diff --git a/sympy/core/assumptions.py b/sympy/core/assumptions.py
index ce4dd30f2e..71c8e54fbd 100644
--- a/sympy/core/assumptions.py
+++ b/sympy/core/assumptions.py
@@ -195,7 +195,7 @@
 
     'imaginary      ->  !real',
 
-    'infinite       ->  !finite',
+    'infinite       ==  !finite',
     'noninteger     ==  real & !integer',
     'nonzero        ==  real & !zero',
 ])
```

Then I get:
```julia
In [1]: x = symbols('x', real=True, finite=False)                                                                                              

In [2]: x.is_infinite                                                                                                             
Out[2]: True
```

**Comment by oscarbenjamin** [comment]
Marking as easy to fix

**Comment by sylee957** [comment]
I guess it was an accident to close this issue

**Comment by ShubhamKJha** [comment]
@oscarbenjamin the following diff fixes this issue
```diff
diff --git a/sympy/core/assumptions.py b/sympy/core/assumptions.py
index a1712c18a..b275d0e32 100644
--- a/sympy/core/assumptions.py
+++ b/sympy/core/assumptions.py
@@ -176,6 +176,7 @@
     'even           ==  integer & !odd',

     'real           ==  negative | zero | positive',
+    'complex        ->  infinite | finite',
     'transcendental ==  complex & !algebraic',

     'negative       ==  nonpositive & nonzero',
```
Converting to `infinite  == !finite` would not be a good option since there can be symbols which cannot be finite and infinite (see the commit message of commit [48c7164](https://github.com/sympy/sympy/commit/48c71643a7631154df8eba1f3bf12acba81c0fb4).)

**Comment by oscarbenjamin** [comment]
Fair enough. Feel free to send a PR.

**Comment by sylee957** [comment]
I see one of example that is neither finite nor infinite, can be NaN.
I don't think that NaN belongs to extended real number system, but we would have to deal with it.
 but I guess the original intent of 48c71643a7631154df8eba1f3bf12acba81c0fb4 states about NaN.

**Comment by asmeurer** [comment]
I agree that fact is correct. Although IMHO we should really have complex -> finite.

**Comment by ShubhamKJha** [comment]
> I agree that fact is correct. Although IMHO we should really have complex -> finite.

@asmeurer `zoo` is complex in the current system. Also, this would break code since `real` in core still means `extended_real`.
