### ISSUE TITLE
Problem with plotting discontinuities in the current master

### ISSUE THREAD

**Issue by ishanaj** [sympy/sympy#16572]
I have tried plotting the discontinuities as mentioned [here](https://github.com/sympy/sympy/blob/d383496deb5bed647ed930fd0194c0f57dba495d/examples/beginner/plot_discont.ipynb)
But the current master doesn't give the output. It is simply displaying a blank plot.
Although SymPy version 1.3 gives the correct result.
```
>>> from sympy import LambertW, Symbol
>>> from sympy.plotting import plot
>>> x = Symbol('x')
>>> plot(LambertW(x))
```
Output from the current master:
![image](https://user-images.githubusercontent.com/29159034/55670311-6be9b200-58a0-11e9-92db-1220adb526aa.png)

Same goes for `sqrt()` plots and `plot(1/x,(x, 0, 3))`

**Comment by oscargus** [comment]
I think this was fixed in #17409 (although I didn't see this issue at the time, will add a test for it as well).

![image](https://user-images.githubusercontent.com/8114497/63349696-3976b800-c35c-11e9-954b-69de48aa5588.png)
