### ISSUE TITLE
deprecate default value of rhs in Eq

### ISSUE THREAD

**Issue by friyaz** [sympy/sympy#16587]
Previously, rhs of equation was assumed to be zero if not provided.
```
>>> Eq(expr) == Eq(expr, 0)
True
```

This was leading to confusion for users and sympy

User will now have to explicitly provide rhs.  

The PR that implement this is #16567.

**Comment by oscarbenjamin** [comment]
Do we know what version this will be remove in is? The code in the PR says deprecated since version 1.5. Does that mean this will be removed in version 1.6?

**Comment by FrackeR011** [comment]
>>> Does that mean this will be removed in version 1.6?

No. I think it means that this code will raise deprecation warning from version on wards. The feature can be removed in any version after version 1.5.

**Comment by dandiez** [comment]
Is it worth considering to add an `Eqz(expr)` function as an alias for `Eq(expr, 0)` ?
It seems quite common to have the rhs be zero and might make it easier to transition.
This is quite subjective, but for me it also seems easier to read `Eqz(expr)` than `Eq(expr, 0)`.

**Comment by asmeurer** [comment]
Most functions that accept Eq also just accept expressions and implicitly assume they equal 0. The exception is the new assumptions system, but we have `Q.nonzero(expr)`.
