### ISSUE TITLE
parsing expressions with powers

### ISSUE THREAD

**Issue by sashaalesin** [sympy/sympy#16591]
`from sympy.parsing.sympy_parser import (
    parse_expr,
    standard_transformations,
    implicit_multiplication_application,
)`

`transformations = (standard_transformations + (implicit_multiplication_application,))`

`expr1 = parse_expr('2**n * 3**n')`
`expr2 = parse_expr('2**n3**n', transformations=transformations)`

`print(type(expr1), expr1.args, expr1) --> <class 'sympy.core.power.Pow'> (6, n) 6**n`
`print(type(expr2), expr2.args, expr2) --> <class 'sympy.core.mul.Mul'> (3**n, 2**n) 3**n*2**n`

and if i will do something with expr1 and expr2 i will get wrong results:

`
print(expr1 - expr2) --> 6**n - 3**n*2**n        # Not Zero!!!
`

i have tried simplify, powsimp (force=True too), powdenest, also i have tried create var('n', positive=True, integer=True) and set parameter local_dict into parse_expr and use another transformations in parsing, but i could not get 0.
Maybe somebody tell me how i can get zero after expr1 - expr2?

Thank you

**Comment by smichr** [comment]
The '3' got parsed as a Symbol in expr2:
```python
>>> srepr(expr2)
"Mul(Pow(Integer(2), Symbol('n')), Pow(Symbol('3'), Symbol('n')))"
                                       ^^^^^^^^^^^
```

**Comment by sashaalesin** [comment]
This is bug? Or what? :(

**Comment by smichr** [comment]
> how i can get zero after expr1 - expr2?

The hack is to do `expr2 = expr2.subs(Symbol('3'), 3)` and work with that until the bug is fixed.

**Comment by sashaalesin** [comment]
Thank you, but i have this bug not only for '3', i can't fix this bug automatically for all cases :)
I hope, that this bug will be fix.

**Comment by smichr** [comment]
I'm not sure how easy this will be to fix: you have an ambiguous expression. `n3` is a valid variable name so either you have a syntax error -- one of the powers is missing an argument as in `2**n3*?**n` or `2**?*n3**n` or it should be split (as in this case you want). But if there is more than 1 number, then what?
`2**n32**n` could have a base of 32 or 2 and or `2**n2.3**n` could have a base of 2.3 or .3 or 3. Perhaps the simplest thing to do is raise a parsing error if any Symbol not in a locals dictionary is created whose name is a number.
