### ISSUE TITLE
Type Error while subclassing Point and Point2D 

### ISSUE THREAD

**Issue by D-K-E** [sympy/sympy#16609]
While I was sub classing `Point` and `Point2D`, I had the following error:

`TypeError: object.__init__() takes exactly one argument (the instance to initialize)`

I am trying to do a normally very simple inheritance. I am quite confused why the child takes `object` as its parent instead of `Point` or `Point2D`   
Here is the relative portion of my code:
```python

import numpy as np
from sympy.geometry.point import Point as SymPoint
from sympy.geometry.point import Point2D as SymPoint2D


class Point2Dx(SymPoint2D):
    "Regroups methods with respect to point in 2d"

    def __init__(self, x=0, y=0,
                 coordlist=None,
                 degree=0):
        if coordlist is not None:
            assert len(coordlist) == 2
            argx = coordlist[0]
            argy = coordlist[1]
        else:
            argx = x
            argy = y
        #
        super(Point2Dx, self).__init__(argx, argy)
        self.angle_degree = degree
        self.radian = self.angle_degree * np.pi / 180
        self.old_x = 0
        self.old_y = 0
        self.new_y = 0
        self.new_x = 0
        self.x = argx
        self.y = argy
```
For your information I also tried the following:

```python

class Point2Dx(SymPoint2D):
    "Regroups methods with respect to point in 2d"

    def __init__(self, x=0, y=0,
                 coordlist=None,
                 degree=0):
        if coordlist is not None:
            assert len(coordlist) == 2
            argx = coordlist[0]
            argy = coordlist[1]
        else:
            argx = x
            argy = y
        #
        super(SymPoint2D, self).__init__(argx, argy)
        self.angle_degree = degree
        self.radian = self.angle_degree * np.pi / 180
        self.old_x = 0
        self.old_y = 0
        self.new_y = 0
        self.new_x = 0
        self.x = argx
        self.y = argy
```
and the following:
```python

class Point2Dx(SymPoint2D):
    "Regroups methods with respect to point in 2d"

    def __init__(self, x=0, y=0,
                 coordlist=None,
                 degree=0):
        if coordlist is not None:
            assert len(coordlist) == 2
            argx = coordlist[0]
            argy = coordlist[1]
        else:
            argx = x
            argy = y
        #
        super().__init__(argx, argy)
        self.angle_degree = degree
        self.radian = self.angle_degree * np.pi / 180
        self.old_x = 0
        self.old_y = 0
        self.new_y = 0
        self.new_x = 0
        self.x = argx
        self.y = argy
```
Sympy version : 1.3

**Comment by oscarbenjamin** [comment]
I don't know what you're trying to do but subclassing is probably not the best approach.

I guess that problem you are seeing is caused by the fact that initialises in `__new__` rather than `__init__` so you should define `__new__` rather than `__init__` if you want to override that.

As I said though, subclassing is probably not the best way to solve your actual problem.

**Comment by D-K-E** [comment]
I am trying to implement a point in 5 dimensions. First 2 is for coordinates, and 3 other for R, G, B channels. 
I will use 3d points for modeling points on gray scale images, and then see what can I do afterwards.

The thing is packages like `numpy` are good for manipulating matrices, but don't work well for representing what's inside those matrices. I was thinking if I can use `sympy` to fill up that niche. 

But this goes out of the scope of this issue so I am closing it.

**Comment by oscarbenjamin** [comment]
Why not use a 2D point for the position coordinates and a 3D point for the colour?

**Comment by D-K-E** [comment]
To be honest with you I don't think I can come up with a good reason not to use 2d for positions and 3d for colors at this stage, at least without further experimentation. 

My initial idea for using a single object for both was due to the fact that there is an underlying relation between the position of a pixel and its color. This relation is apparent if the position of the light source is known. Those who are closer to light are brighter than those who are further for example. 
Plus, I am also looking for solid way to define geometric entities on an image based on pixel values and their positions. My goal is to do arithmetic operations with those entities afterwards.
