### ISSUE TITLE
Differentiation of Sum of two Matrix expressions raises TypeError

### ISSUE THREAD

**Issue by Sc0rpi0n101** [sympy/sympy#16606]
According to the discussion on Gitter,

```
>>> X = MatrixSymbol('X',3,5)
>>> y = MatrixSymbol('y',5,1)
>>> w = MatrixSymbol('w',3,1)
>>> diff(w.T * X * X.T * w, w) # looks good
2*X*X.T*w
>>> diff(y.T* X.T *w, w) # looks good
X*y
>>> diff(w.T * X * X.T * w + y.T* X.T *w, w) # raises TypeError for some devices
X*y + 2*X*X.T*w
```
The provided code raises an Exception with TypeError : int object is not iterable in some environments including a Jupyter Notebook tried in Mozilla Firefox.

But there seems to be no error on my device and the expression gives correct result for both Python 2 and Python 3.

My Environment:

debian - 9 stretch (amd64)

conda sympy-dev-py27 with mpmath
python 2.7.13

conda sympy-dev-py37 with mpmath
python 3.7.1

**Comment by sidhantnagpal** [comment]
This seems to be working on master https://github.com/sympy/sympy/issues/16613#issuecomment-481276789.
By the way, on 1.3, I get (confirmed on SymPy Live for Python 2.7.12 and on Colab for Python 3.6.7):
```py
In [1]: X = MatrixSymbol('X', 3, 5) 
   ...: y = MatrixSymbol('y', 5, 1) 
   ...: w = MatrixSymbol('y', 3, 1) 
   ...: diff(w.T * X * X.T * w + y.T * X.T * w)
...
TypeError: BooleanAtom not allowed in this context.
```

**Comment by Sc0rpi0n101** [comment]
It worked for me on master too 
But failed on jupyter which I guess uses 1.3

So I guess it will be fixed with 1.4?

**Comment by gabrieldernbach** [comment]
I am went from the version 1.3 to the actual git master. I am now on 1.5.dev by `pip install git+https://github.com/sympy/sympy@master` and it works fine. Thanks

**Comment by Sc0rpi0n101** [comment]
That means it's a 1.3 or before issue is fixed in current master
@asmeurer  Hope it's fixed for 1.4 too ?

**Comment by sidhantnagpal** [comment]
Yes, it works for 1.4.

**Comment by Sc0rpi0n101** [comment]
Well, then it's solved
