### ISSUE TITLE
Sum of individually valid derivatives gives type error

### ISSUE THREAD

**Issue by gabrieldernbach** [sympy/sympy#16613]
When i try the derivative of the individual elements of a sum I get
the correct results. However when I take the derivative of the sum of the elements
I get a type error. (tried in python, ipython, jupyter notebook each with sympy 1.3)

```
X = MatrixSymbol('X',3,5)
y = MatrixSymbol('y',5,1)
w = MatrixSymbol('w',3,1)

# part a yields correct result
diff(w.T * X * X.T * w, w)
# part b yields correct result
diff(y.T* X.T *w, w)
# however a + b gives a type error.
diff(w.T*X*X.T*w + y.T*X.T*w, w)
```

**Comment by sidhantnagpal** [comment]
Tracking this issue at #16606.
