### ISSUE TITLE
`x+y` uses Mul somewhere (Querry)

### ISSUE THREAD

**Issue by rotuna** [sympy/sympy#16622]
Hi,

This is the code that I used.

`import sympy`

`x,y = sympy.symbols('x,y')`

`z = x + y `

I used ipdb.set_trace() in the `__new__` function in `class AssocOp`

When I did this I found that this function was called 4 times. The following is the value of `cls` for each call 

1. <class 'sympy.core.mul.Mul'>
2. <class 'sympy.core.add.Add'>
3. <class 'sympy.core.add.Add'>
4. <class 'sympy.core.add.Add'>

Is there a reason why this is happening?

Thanks

**Comment by sylee957** [comment]
Actually, I think that you can see your first three lines happening even with `import sympy`

SymPy initializes a lot of stuff after import, like creating tables for sympify or evalf, so if you want to trace or benchmark, you would have to segregate a specific code to execute.

**Comment by rotuna** [comment]
Oh. Thanks. 

Out of curiosity: why though? This function would ideally be called only when two symbols interact somehow, right? 

Also, is there some documentation about these things somewhere?

I'd be happy to help document whatever I understand if you guys would want it.

**Comment by asmeurer** [comment]
You can check higher up in the stack when the breakpoint is called to see where it is coming from. 

A lot of times these things are done at import time, but it would be better to refactor them so that they aren't, because it slows down the import time to instantiate classes. There are some places where this is not so trivial, however (such as the singleton classes).

**Comment by asmeurer** [comment]
Looks like Mul is being called from the creation of `Complexes` (possibly elsewhere too). This is one of the singleton instances, so it may not be easy to do anything about it.

**Comment by rotuna** [comment]
Thanks, this helped but I ended up having more issues :) #16718
