### ISSUE TITLE
Geometry: Line-Segment-Intersection can run into memory problems

### ISSUE THREAD

**Issue by jpmaterial** [sympy/sympy#16628]
Hi,

when determining a line-segment-intersection, depending on the geometry, sympy can take up som much memory that the script will crash.

I'm on Windows, using CPython 3.7.3 on sympy commit b97cbe99, although the issue exists in version 1.3 too.

Example code:
<pre>
#!Python -u

import sys, os, time, math

sys.stderr.write(str(os.getpid())+time.strftime(': starting @ %d%b%y, %H:%M\n'))
	
from sympy.geometry import Point, Point2D, Line, Segment, intersection
from sympy import *
import sympy

sys.stderr.write('sympy version: '+sympy.__version__+'\n')

p0=Point2D(249/5, 497999/10000)
p1x=3*(-19659028262*sqrt(405639795226) + 676896692394731 + 6704069269*sqrt(630547164901) + 33200*sqrt(255775022850776494562626))/(2000*(sqrt(255775022850776494562626) + 995999*sqrt(405639795226) + 995999*sqrt(630547164901) + 811280586451))
p1y=(-498000*sqrt(255775022850776494562626) - 995999*sqrt(630547164901) + 90004251917891999 + 496005510002*sqrt(405639795226))/(10000*(sqrt(255775022850776494562626) + 995999*sqrt(405639795226) + 995999*sqrt(630547164901) + 811280586451))
p1=Point2D(p1x, p1y)

sys.stderr.write('p1: '+str(p1)+'\n')

p2=Point2D(497/10, -497/10)
p3=Point2D(-497/10, -497/10)

l=Line(p0,p1)
s=Segment(p2,p3)
ints=intersection(l,s)

sys.stderr.write(str(os.getpid())+time.strftime(': done @ %d%b%y, %H:%M\n'))
</pre>

**Comment by smichr** [comment]
I don't recall how the containment check is being done but a manual check as follows seems to work:

```
def slix(s,l):
    assert isinstance(s, Segment) and isinstance(l, Line)
    hit = intersection(l, Line(s))
    if not hit: return []
    m1 = s.p1 - hit
    m2 = hit - s.p2
    # are the slopes from end points to hit the same and
    # is the hit.x between the end points?
    if And(Eq(m1.y*m2.x,m1.x*m2.y), (s.p1.x-hit.x)*(s.p2.x-hit.x)<=0): return [hit]
    return []
```

**Comment by smichr** [comment]
Changes in #16668 avoid a crash. There probably exists a similar problem in 3D but I have not looked into that.
