### ISSUE TITLE
gauss_jordan_solve freevar parameter is confusing

### ISSUE THREAD

**Issue by dandiez** [sympy/sympy#16633]
gauss_jordan_solve() freevar parameter is explained in the docstring a bit weirdly.
It is under (input) parameters as a List, even though the parameter section talks about True and False and the default value is False.
It does not appear under the return parameters, however, if you specify freevar as True, then gauss_jordan_solve() returns 3 instead of 2 things.
It would also be good to have an example showing how to use that parameter (i.e. showing that three things are returned) and maybe even explain what the returned indices of the free variables might be useful for.

**Comment by oscarbenjamin** [comment]
I agree that the freevars parameter is not explained well. Would you like to submit a PR to explain it better?
