### ISSUE TITLE
ModuleNotFoundError:No module named 'sympy'

### ISSUE THREAD

**Issue by HJCFLY** [sympy/sympy#16638]
I installed mpmath first.but when i use sympy ,ModuleNotFoundError: No module named 'sympy'
please help me

**Comment by oscarbenjamin** [comment]
That means you haven't installed SymPy.

Are you sure you installed SymPy? Do you have more than one Python installation on your computer?

**Comment by oscarbenjamin** [comment]
This is most likely not an issue with SymPy but a problem with your installation.

I think it would be better to ask for help with this on the mailing list:
[https://groups.google.com/forum/#!forum/sympy](https://groups.google.com/forum/#!forum/sympy)

I'm going to close this issue since it is probably not something to be fixed in SymPy.

**Comment by HJCFLY** [comment]
![image](https://user-images.githubusercontent.com/38662362/56080293-ba172c00-5e31-11e9-91ef-c50a2fb026fc.png)
i install it

**Comment by oscarbenjamin** [comment]
Yes but you may not be running the same Python installation that you installed it with.

Can you ask for help on the mailing list? Make sure to explain in detail what operating system you are using, how you installed Python and how you installed SymPy.

**Comment by LOUYIJITUAN** [comment]
The reason for the error is that there are multiple versions of sympy in the environment. Therefore, run the '**`pip uninstall sympy`**' command in cmd until it is prompted that the module is not installed, and then reinstall it.
If it still doesn't work, you can check the location through "**`pip show sympy`**" and manually delete it. Be sure to ensure that there are no sympy related files on the C drive.
Finally, good luck to you
