### ISSUE TITLE
Wrong result with limits

### ISSUE THREAD

**Issue by rvinuela** [sympy/sympy#16708]
I was porting a problem from Maxima to Sympy, having to solve this limit:
```
limit(( B * ti * v(ti) - sqrt(m) * sqrt(-2 * B * d * v(ti) + m * v(ti)**2) + m * v(ti))/(B * v(ti)), B, 0)
```
Symbol "m" was declared as positive: m = symbols('m',positive = True)
and the result that it gives is:
```
-oo * sign( (m * sqrt(v(ti)**2) - m * v(ti))/v(ti))
```
But it should be:  `ti + d/v(ti)` 
(is the result of a physics problem)

- Tried the gruntz method.
- Tried with dir+ and dir-, etc, always the same result. 
- Tried replacing v(ti) with a vi symbol.

You can copy/paste the same line of code into Maxima and run it, they are compatible.

**Comment by oscarbenjamin** [comment]
I've edited your code examples using backticks so that the code comes out properly in the browser:
https://help.github.com/en/articles/creating-and-highlighting-code-blocks

**Comment by pragyanmehrotra** [comment]
I would like to take a look at this issue, what's the symbol "d" in the above equation?

**Comment by rvinuela** [comment]
> I would like to take a look at this issue, what's the symbol "d" in the above equation?

The symbol "d" represents a distance, it can safely be assumed to be positive, this is a motion equation. Nevertheless the only symbol that needs to be defined positive is mass which is "m". As I already pointed out, also v(ti) can be replaced by the symbol "vi", with the same result.

**Comment by sachin-4099** [comment]
I think the assumptions are required for the variable `v(ti)` or `vi`.  If `vi` is set to positive, the limit evaluates correctly:
```
In [1]: m = symbols('m',positive = True)
In [2]: vi = symbols('vi', positive = True)
In [3]: B, ti, d = symbols('B ti d')
In [4]: y = ( B * ti * vi - sqrt(m) * sqrt(-2 * B * d * vi + m * (vi)**2) + m * vi)/(B * vi)

In [5]: y.limit(B, 0)
Out[5]:
d + ti*vi
---------
    vi
```

**Comment by rvinuela** [comment]
You are correct, if I define Vi to be positive the limit is d + ti/vi, if I define it negative the limit is +00, so it is weird that Maxima did not complain and assume it to be positive. Vi is the initial velocity so in my case it is not accurate to assume that it will be always positive, but from your analysis it looks that only positive values of Vi have a valid root, I will check the physics of this but this is most probably the reason and it is not a bug.

Thanks a lot.

> I think the assumptions are required for the variable `v(ti)` or `vi`. If `vi` is set to `positive`, the limit evaluates correctly:
> 
> ```
> In [1]: m = symbols('m', positive = True)
> In [2]: vi = symbols('vi', positive = True)
> In [3]: B, ti, d = symbols('B ti d')
> In [4]: y = ( B * ti * vi - sqrt(m) * sqrt(-2 * B * d * vi + m * (vi)**2) + m * vi)/(B * vi)
> 
> In [5]: y.limit(B, 0)
> Out[5]:
> d + ti*vi
> ---------
>     vi
> ```

**Comment by sachin-4099** [comment]
We will add this as a testcase.
