### ISSUE TITLE
bin/coverage_doctest.py does not work

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#16716]
```pytb
$./bin/coverage_doctest.py
DOCTEST COVERAGE for /Users/aaronmeurer/Documents/Python/sympy/sympy/sympy
======================================================================

Traceback (most recent call last):
  File "./bin/coverage_doctest.py", line 601, in <module>
    no_color=args.no_color, sphinx=args.sphinx)
  File "./bin/coverage_doctest.py", line 541, in go
    verbose=verbose, no_color=no_color, exact=False, sphinx=sphinx)
  File "./bin/coverage_doctest.py", line 549, in go
    any(name in file for name in skip_paths))):
NameError: name 'skip_paths' is not defined
```

It works if you remove the skip_paths check, but we should look into the history of the file to see what that was, because clearly something broke at some point.

**Comment by smichr** [comment]
> look into the history of the file to see what that was

It was initially a way to skip testing of mpmath in 24eeabe2fe23a1d5103e61c3b8d1ed10c44d9795; it was removed in 9b204c3d1a3e4f6753a7d5186f3074ef13641f36 when mpmath (the only thing being skipped) was removed. The simple fix is to just define `skip_paths` as an empty list.

**Comment by asmeurer** [comment]
https://github.com/sympy/sympy/pull/16729#issuecomment-487160414

**Comment by sylee957** [comment]
I'm not sure that every not frequently used utilities are working.
For example `diagnose_imports` is failing
```
python bin/diagnose_imports
Traceback (most recent call last):

    from sympy.core.compatibility import builtins
ModuleNotFoundError: No module named 'sympy'
```
And also, I see some utilities have optional arguments, but are they correctly tested?
I think that every executable utilites may need to be tested, if there can be a way to do.

**Comment by evatiwari** [comment]
Hi, I would like to work on this issue. Can someone guide me a little bit regarding this?

**Comment by asmeurer** [comment]
I don't think there are any existing pull requests. You should start by running the script and posting whatever output you get here. Then we can figure out what needs to be done to fix whatever errors come up.

**Comment by evatiwari** [comment]
@asmeurer this is what I am getting. From what I understand of this, the object returned by ```inspect.getfullargspec(fobj)``` does not have a keywords attribute. 
```
(sympy-dev) D:\Documents\sympy>python bin/coverage_doctest.py --no-sphinx
DOCTEST COVERAGE for D:\Documents\sympy\sympy
======================================================================

sympy.abc: ←[0;33mDoctests:←[0m ←[0;32m100% (0 of 0)←[0m
Traceback (most recent call last):
  File "bin/coverage_doctest.py", line 623, in <module>
    doctests, total_sphinx, num_functions = go(sympy_top, file, verbose=args.verbose,
  File "bin/coverage_doctest.py", line 562, in go
    _doctests, _total_sphinx,  _num_functions = go(sympy_top, '%s/%s' % (file, F),
  File "bin/coverage_doctest.py", line 562, in go
    _doctests, _total_sphinx,  _num_functions = go(sympy_top, '%s/%s' % (file, F),
  File "bin/coverage_doctest.py", line 579, in go
    return coverage(get_mod_name(file, sympy_top), verbose=verbose,
  File "bin/coverage_doctest.py", line 509, in coverage
    f_dt, f = process_function(f_name, member, obj,
  File "bin/coverage_doctest.py", line 311, in process_function
    full_name = _get_arg_list(name, obj)
  File "bin/coverage_doctest.py", line 231, in _get_arg_list
    if argspec.keywords:
AttributeError: 'FullArgSpec' object has no attribute 'keywords'
```

**Comment by asmeurer** [comment]
You should rerun the script to check what the actual issues are. Some of the errors listed here may no longer be accurate. Any problems are likely due to the script being written for an older version of Python. It only needs to support the newest version of Python.

**Comment by s-hanko** [comment]
I guess I forgot to mention that I had already run the script. My trace was the same as the previous user's, but I'll post it here:
```

======================================================================

sympy.abc: Doctests: 100% (0 of 0)
Traceback (most recent call last):
  File "./coverage_doctest.py", line 623, in <module>
    doctests, total_sphinx, num_functions = go(sympy_top, file, verbose=args.verbose,
  File "./coverage_doctest.py", line 562, in go
    _doctests, _total_sphinx,  _num_functions = go(sympy_top, '%s/%s' % (file, F),
  File "./coverage_doctest.py", line 562, in go
    _doctests, _total_sphinx,  _num_functions = go(sympy_top, '%s/%s' % (file, F),
  File "./coverage_doctest.py", line 579, in go
    return coverage(get_mod_name(file, sympy_top), verbose=verbose,
  File "./coverage_doctest.py", line 509, in coverage
    f_dt, f = process_function(f_name, member, obj,
  File "./coverage_doctest.py", line 311, in process_function
    full_name = _get_arg_list(name, obj)
  File "./coverage_doctest.py", line 231, in _get_arg_list
    if argspec.keywords:
AttributeError: 'FullArgSpec' object has no attribute 'keywords'

```
This doesn't _look_ to me like it's about being written for an older version of Python, unless the name of `keywords` has changed in recent python versions.

With the new code I proposed the output looks like this:
```
======================================================================

sympy.abc: Doctests: 100% (0 of 0)
sympy.algebras.quaternion: Doctests: 81% (13 of 16)
sympy.assumptions.ask: Doctests: 25% (1 of 4)
sympy.assumptions.ask_generated: Doctests: 0% (0 of 2)
Traceback (most recent call last):
  File "./coverage_doctest.py", line 624, in <module>
    doctests, total_sphinx, num_functions = go(sympy_top, file, verbose=args.verbose,
  File "./coverage_doctest.py", line 563, in go
    _doctests, _total_sphinx,  _num_functions = go(sympy_top, '%s/%s' % (file, F),
  File "./coverage_doctest.py", line 563, in go
    _doctests, _total_sphinx,  _num_functions = go(sympy_top, '%s/%s' % (file, F),
  File "./coverage_doctest.py", line 580, in go
    return coverage(get_mod_name(file, sympy_top), verbose=verbose,
  File "./coverage_doctest.py", line 480, in coverage
    c_dt, c, source = process_class(member, obj, c_skipped, c_md,
  File "./coverage_doctest.py", line 400, in process_class
    assert None, type(doc)
AssertionError: <class 'property'>
```

After looking into it, it seems like the `AssertionEror` is caused by `PredicateMeta` lacking an `obj.__doc__`.

**Comment by asmeurer** [comment]
The getargspec stuff has changed in the past, especially since Python 2 (I don't know if the script was ever updated to work with Python 3).

**Comment by s-hanko** [comment]
Right. As I mentioned before, it looks like `keywords` isn't in use anymore. Looking closer, it seems like it used to be the name of the `**` parameter, which is now named `varkw`. That means that the updated code should be this:
```
    if argspec.varkw:
        arg_list.append(argspec.varkw)
```
The output produced by this code is as follows:
```
======================================================================

sympy.abc: Doctests: 100% (0 of 0)
sympy.algebras.quaternion: Doctests: 81% (13 of 16)
sympy.assumptions.ask: Doctests: 25% (1 of 4)
sympy.assumptions.ask_generated: Doctests: 0% (0 of 2)
Traceback (most recent call last):
  File "./coverage_doctest.py", line 624, in <module>
    doctests, total_sphinx, num_functions = go(sympy_top, file, verbose=args.verbose,
  File "./coverage_doctest.py", line 563, in go
    _doctests, _total_sphinx,  _num_functions = go(sympy_top, '%s/%s' % (file, F),
  File "./coverage_doctest.py", line 563, in go
    _doctests, _total_sphinx,  _num_functions = go(sympy_top, '%s/%s' % (file, F),
  File "./coverage_doctest.py", line 580, in go
    return coverage(get_mod_name(file, sympy_top), verbose=verbose,
  File "./coverage_doctest.py", line 480, in coverage
    c_dt, c, source = process_class(member, obj, c_skipped, c_md,
  File "./coverage_doctest.py", line 400, in process_class
    assert None, type(doc)
AssertionError: <class 'property'>
```

**Comment by asmeurer** [comment]
It looks like it doesn't handle the dynamic docstrings used in the assumptions. It should probably just skip the docstring in that case. 

There's also a lot of unPythonic code like using `assert None` instead of raising an exception or using `type(doc) is str` instead of `isinstance(doc, str)`. Those could be fixed along the way.

**Comment by s-hanko** [comment]
Just to clarify, do you think that we should skip the docstrings only in the case where they're dynamic docstrings or just skip them in general since dynamic docstrings aren't being handled correctly?

Yeah, the code using `assert None` like that was throwing me off a bit. I think `TypeError` exceptions would be more appropriate. I'll keep an eye out for other weird things that might be in there and fix them if I see them.

**Comment by asmeurer** [comment]
The whole point of the script is to see which docstrings have doctests, so skipping every docstring doesn't make sense.

**Comment by s-hanko** [comment]
It looks like the dynamic docstring was of type `property`, so I added the following code to skip it (it also adds the file to the skipped list
```
elif isinstance(doc, property):
        # skip class with dynamic doc
        c_sk.append(c_name)
        return False, False, None
```

I also noticed that there are a number of variable names that are abbreviated which makes the code more difficult to read, and I was thinking about changing them to make them clearer (so for example, c_mdt and f_mdt could  be changed to c_missing_doctest and f_missing_doctest).

**Comment by asmeurer** [comment]
That all sounds good.
