### ISSUE TITLE
Polygon-line(segment) intersections with rational values or integers works, but not with float.

### ISSUE THREAD

**Issue by lauritk** [sympy/sympy#16719]
I have troubles to get polygon and line segment intersections work with floats. It seems to work with integers and rational values. Any suggestions?

The code:
```
import sympy

pt1 = (207.9, 373.6)
pt2 = (175.0, 175.0)
rect = sympy.Polygon(*[
                       sympy.Point(168.0, 165.0, evaluate=False),
                       sympy.Point(182.0, 165.0, evaluate=False),
                       sympy.Point(182.0, 185.0, evaluate=False),
                       sympy.Point(168.0, 185.0, evaluate=False)
                       ], evaluate=False)
intersect = rect.intersection(l)
```

**Comment by oscarbenjamin** [comment]
Your code is missing `l = sympy.Line(pt1, pt2)` I guess.

With that I get:
```julia
In [32]: rect.intersect(l)                                                                                                                  
Out[32]: ∅

In [33]: rect.doit().intersect(l)                                                                                                           
Out[33]: {Point2D(172130/993, 165), Point2D(175420/993, 185)}
```

**Comment by lauritk** [comment]
That's true, accidently erased it. I used Segment, but it's same with Line.

The missing code is `l = sympy.Segment(x, y, evaluate=False)`

**Comment by oscarbenjamin** [comment]
Is this the same as #4748 ?

**Comment by lauritk** [comment]
I am not sure.

Problem seems to be line 677 in ellipse.py. Code `return list(ordered([Point(i) for i in result if i in o]))` causes result to be empty list, but previous line `result = solve([ellipse_equation, Line(o.points[0], o.points[1]).equation(x, y)], [x, y])` have two intersection coordinates.

If I change `result if i in o` to `result if i not in o`, things work and results are looking right. Not sure why there is this IF-statement. Also it seems that coordinates are "casted" as Point() in the loop, which converts values to rational values, which in the other hand kills the point of using `evaluate=False` in the first place. I though `evaluate=False` would have speeded the process, when the accuracy is not that important.

**Comment by lauritk** [comment]
I guess `return list(ordered([Point(i) for i in result if i in o]))` is for returning points in the Ray or Segment. Without it the code returns intersection of Line. I don't know why this works with rationals, but not with floats.

**Comment by smichr** [comment]
> I am not sure.

It's the same. And now SymPy converts all Floats to Rationals (unless you create unevaluated Points).

> I don't know why this works with rationals, but not with floats.

I think geometry would need a major overhaul to work with approximations.

**Comment by smichr** [comment]
duplicates #4748
