### ISSUE TITLE
log(-oo) -> oo

### ISSUE THREAD

**Issue by smichr** [sympy/sympy#16737]
Should `log(-oo)` be `oo + I*pi`?
https://github.com/sympy/sympy/blob/833dbd819e1ef946f107ebe3b535bd445fd5bd1e/sympy/functions/elementary/exponential.py#L546-L547

**Comment by jksuom** [comment]
Perhaps that would be the best choice. `log` has branch cut along the negative real axis so there is no unique limit in the complex plane. The limit of the principal branch is `oo + I*pi` from the upper half plane (including real axis) and `oo - I*pi` from the lower half plane. However, I think that we can consider `log(-oo)` as the limit along the real axis (that is the common use case) so the "upper half limit" could be taken.
