### ISSUE TITLE
all(Rational(float(i)) == 0 for i in ('inf', '-inf', 'nan'))

### ISSUE THREAD

**Issue by smichr** [sympy/sympy#16738]

**Comment by jksuom** [comment]
It seems to me that it is an error to let such conversions pass silently. float -> Rational conversions appear e.g. in some solvers. I think that bad input data should be rejected.

**Comment by smichr** [comment]
The following should be modified 
https://github.com/sympy/sympy/blob/082df75b2a29cbc02737281352faae913dc02c74/sympy/core/numbers.py#L1487-L1495

to use `_not_a_coeff` from `polys`:

```python
  if _not_a_coeff(p):
      pass  # error to raise below
  elif isinstance(p, (float, Float)): 
     return Rational(*_as_integer_ratio(p)) 
 elif not isinstance(p, string_types): 
     try: 
         p = sympify(p) 
     except (SympifyError, SyntaxError): 
         pass  # error will raise below 
 else:
```

**Comment by smichr** [comment]
I don't know why this didn't autoclose with the merge.
