### ISSUE TITLE
coeff() fails with non-commutative argument

### ISSUE THREAD

**Issue by riccardo-guida** [sympy/sympy#16752]
Diffgeom results in a wrong result for the double Lie Bracket of three vectors 
Commutator(Commutator(v1,v2),v3)
where
v1 = exp(r)*e_r + exp(r**2)*e_theta
v2 = sin(theta)*e_r
v3 = e_theta+e_r 
xs = r,    theta   = spherical.coord_functions()
es = e_r,  e_theta = spherical.base_vectors() 

Full example in [sympy googlegroup thread](https://groups.google.com/forum/#!topic/sympy/zmGIsxmzV0c).

This leads to violation of Jacobi identities for Commutator.

Ideas:
> It looks like there is a bug in Expr.coeff. It cannot find the coefficient of e_r in Commutator(v1, v2), apparently because of non-commutativity.  K Souminen

**Comment by jksuom** [comment]
This issue is actually not concerned with differential geometry. It presents itself already with core expressions.
```
>>> from sympy import *
>>> x, y, z = symbols('x y z')
>>> a, b = symbols('a b', commutative=False)
>>> e = x*a + y*a + z*b
>>> e.coeff(a)
0
>>> e.coeff(b)
z
```

**Comment by jksuom** [comment]
It looks like this part of `coeff` should be revised to handle more than a single match for  a non-commutative argument.
https://github.com/sympy/sympy/blob/b8fe457a02cc24b3470ff678d0099c350b7fef43/sympy/core/expr.py#L1504-L1519
