### ISSUE TITLE
unexpected result for r == 0 where r is a real symbol

### ISSUE THREAD

**Issue by Greg1950** [sympy/sympy#16761]
In response to commands

`p = symbols("p", positive=True)  # create a symbol representing a positive real number`  
`print("p is negative, p is zero, p is positive: ", p < 0, "\b,", p == 0, "\b,", p > 0)`    
`r = symbols("r", real=True)     # create a symbol representing a real number`  
`print("r is negative, r is zero, r is positive: ", r < 0, "\b,", r == 0, "\b,", r > 0) `  

I get output

`p is negative, p is zero, p is positive:  False, False, True`    
`r is negative, r is zero, r is positive:  r < 0, False, r > 0`  

The first line of output is as I would expect.  The second is not.  It's reasonable that SymPy respond with "r < 0" and "r > 0" for the comparisons `r < 0` and `r > 0`, for the value of `r` is unknown and so SymPy cannot assign boolean values to those comparisons.  

Based on similar reasoning, **I would expect the comparison `r == 0` to result in output "r = 0", but instead one gets `False`.** 

In a similar vein, the commands

`nn = symbols("nn", nonnegative=True)  # create a symbol representing a nonnegative real number`  
`print("nn is negative, nn is zero, nn is positive: ", nn<0, "\b,", nn==0, "\b,", nn>0)`

gives output

`nn is negative, nn is zero, nn is positive:  False, False, nn > 0`

I would expect the comparison `nn == 0` to result in answer "nn = 0" as it's not known whether `nn` represents the real number zero.

**Comment by smichr** [comment]
`Eq(r, 0)` will not evaluate becuase the sign is not known; `r==0` because r is not the number 0 *right now*. `==` is used to test structural identity.
