### ISSUE TITLE
Weird Float

### ISSUE THREAD

**Issue by proy87** [sympy/sympy#16768]
Why does `Float('2.', dps='')*Integer(48)` give `100`?

**Comment by jksuom** [comment]
`Float('2.', dps='')*Integer(48)` will have binary precision 7 which is translated to decimal precision 1 by mpmath. Therefore the product will be printed as `1.e+2`.

**Comment by proy87** [comment]
Still didn't understand? What is `Float('2.', dps='')` translated to?

**Comment by jksuom** [comment]
```
>>> a = Float('2.', dps='')
>>> a
2.
>>> a._mpf_
(0, mpz(1), 1L, 1L)
>>> a._prec
7
```
`a._mpf_` says that mantissa, exponent and bitcount are all 1 (so the value is 1<<1).
`a._prec` is a value set by SymPy by default as `dps` is a null string.

**Comment by smichr** [comment]
> What is `Float('2.', dps='')` translated to?

"Give me the float with least precision necessary to represent '2.'."

Now, any operations you do with that number will have about 1 digit of precision. If you used `dps=2` operations would give about 2 digits of precision.
```python
>>> Float('2.', 2)*1234
2.5e+3
```

**Comment by smichr** [comment]
Here's an example where you can see several issues at play:
```python
>>> (2**(I+Float(.1,4))).n(10)
0.8244500588 + 0.6848219206*I
>>> (2**(I+Float(.1,4))).expand().n(10)
0.8244528264 + 0.6848242195*I
```
1. the evalf result depends on the initial state of the expression (expanded vs unexpanded)
2. the precision of 10 determines the output precision
3. the accuracy is limited by the low precision float -- note how they two exressions only agree to 5 decimal places.
