### ISSUE TITLE
as_int() fails on np.int64

### ISSUE THREAD

**Issue by clinssen** [sympy/sympy#16779]
Steps to reproduce:

```python
import numpy as np
from scipy.core.compatibility import as_int
as_int(np.int64(123))
```

Yields:

```
ValueError: 123 is not an integer
```

Perhaps a clean solution would involve adding np.int64 to SYMPY_INTS in https://github.com/sympy/sympy/blob/8dcb72f6abe5c7edf94ea722429c0bb9f7eef54d/sympy/core/compatibility.py#L769 from outside of sympy?

**Comment by oscarbenjamin** [comment]
The relevant code seems to be
https://github.com/sympy/sympy/blob/8dcb72f6abe5c7edf94ea722429c0bb9f7eef54d/sympy/core/compatibility.py#L417-L425
which comes from #16081.

Maybe this could use `__index__` rather than checking against an explicit list of types:
```python
>>> np.int64(2).__index__()
2
```

**Comment by clinssen** [comment]
I can verify that `as_int(np.int64(123))` worked without a hitch before #16081 was merged.

Using `__index__()` when this method is present seems like a good idea—it was designed to address exactly this issue (https://www.python.org/dev/peps/pep-0357/).

**Comment by namannimmo10** [comment]
> ```python
> import numpy as np
> from scipy.core.compatibility import as_int
> as_int(np.int64(123))
I'm working on this issue. 
@oscarbenjamin, this works fine on SymPy Live. But shows ValueError in the terminal. Why is it so?

**Comment by oscarbenjamin** [comment]
I don't know why. I just tested and it seems to work okay on SymPy Live. I tried with 1.5.1 locally (same version as SymPy Live) and I see the error:
```julia
In [1]: import numpy as np                                                                                                                     

In [2]: from sympy.core.compatibility import as_int                                                                                            

In [3]: as_int(np.int64(123))                                                                                                                  
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
~/current/sympy/sympy/sympy/core/compatibility.py in as_int(n, strict)
    418         if strict and not isinstance(n, SYMPY_INTS + (Integer,)):
--> 419             raise TypeError
    420         result = int(n)

TypeError: 

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
<ipython-input-3-c71c97dc8984> in <module>
----> 1 as_int(np.int64(123))

~/current/sympy/sympy/sympy/core/compatibility.py in as_int(n, strict)
    423         return result
    424     except TypeError:
--> 425         raise ValueError('%s is not an integer' % (n,))
    426 
    427 

ValueError: 123 is not an integer
```
