### ISSUE TITLE
When call print_latex, use "()" instead of "[]" for Matrix 

### ISSUE THREAD

**Issue by stevenleeS0ht** [sympy/sympy#16789]
When print_latex a Matrix, 

$\left(\begin{matrix}a & b\\c & d\end{matrix}\right)$

is more common than

$\left[\begin{matrix}a & b\\c & d\end{matrix}\right]$

Since there is no Vector in sympy,

$\left(\begin{matrix}x\\y\end{matrix}\right)$

looks more comfortable than

$\left[\begin{matrix}x\\y\end{matrix}\right]$

**Comment by sylee957** [comment]
You can use `mat_delim`
```python
init_printing(
    latex_printer=lambda x, **kwargs: latex(x, mat_delim="(",**kwargs)
)
Matrix([[1, 2], [3, 4]])
```

**Comment by oscargus** [comment]
It is actually possible to pass `latex` settings directly to `init_printing`, so

`init_printing(mat_delim='(')`

is probably easier.

**Comment by asmeurer** [comment]
I think we should keep [ as the default for matrices. It's easier to distinguish between large ( ) that might be used for tall expressions.

**Comment by eric-wieser** [comment]
Can this be closed, based on @sylee957's comment?

**Comment by oscarbenjamin** [comment]
Yes, I think so
