### ISSUE TITLE
Error with beta in parse_expr

### ISSUE THREAD

**Issue by proy87** [sympy/sympy#16795]
`from sympy.parsing.sympy_parser import (standard_transformations, parse_expr)`
`parse_expr('(alpha - beta*y)/(2*beta + 1)', transformations=standard_transformations)`

`TypeError: unbound method as_base_exp() must be called with beta instance as first argument`

**Comment by asmeurer** [comment]
parse_expr by default uses the SymPy names from `from sympy import *`. `beta` is defined as the beta function. You can either remap it with `local_dict`, like `parse_expr(..., local_dict={'beta': Symbol('beta')})`, or you can whitelist which SymPy functions you want to allow with the `global_dict` parameter.

**Comment by asmeurer** [comment]
`sympy.abc._clash`, `sympy.abc._clash1`, and `sympy.abc._clash2` may be helpful as well:

```
>>> sympy.abc._clash1
{'C': C, 'O': O, 'Q': Q, 'N': N, 'I': I, 'E': E, 'S': S}
>>> sympy.abc._clash2
{'beta': beta, 'zeta': zeta, 'gamma': gamma, 'pi': pi}
>>> sympy.abc._clash
{'C': C, 'O': O, 'Q': Q, 'N': N, 'I': I, 'E': E, 'S': S, 'beta': beta, 'zeta': zeta, 'gamma': gamma, 'pi': pi}
```

You can pass these as the `locals_dict` to automatically make all single letter names and/or greek letter names produce symbols. This is documented in the `sympify` docstring, but not the `parse_expr` docstring.

**Comment by proy87** [comment]
@asmeurer , thank you.
