### ISSUE TITLE
summation doesn't accepts Range as limits

### ISSUE THREAD

**Issue by czgdp1807** [sympy/sympy#16806]
#### Problem
As said in the title I cannot pass `Range` as limits in the `summation`. However, `integrate` accepts the analogous `Interval` as limits. 

#### Example of problem
```
Python 3.6.7 (default, Oct 22 2018, 11:32:17) 
[GCC 8.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from sympy import *
>>> limits = Range(1, 50)
>>> i = symbols('i', positive=True, integer=True)
>>> summation(i, (i, limits))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/gagandeep/sympy/sympy/concrete/summations.py", line 847, in summation
    return Sum(f, *symbols, **kwargs).doit(deep=False)
  File "/home/gagandeep/sympy/sympy/concrete/summations.py", line 161, in __new__
    obj = AddWithLimits.__new__(cls, function, *symbols, **assumptions)
  File "/home/gagandeep/sympy/sympy/concrete/expr_with_limits.py", line 356, in __new__
    pre = _common_new(cls, function, *symbols, **assumptions)
  File "/home/gagandeep/sympy/sympy/concrete/expr_with_limits.py", line 38, in _common_new
    limits, orientation = _process_limits(*symbols)
  File "/home/gagandeep/sympy/sympy/concrete/expr_with_limits.py", line 123, in _process_limits
    raise ValueError('Invalid limits given: %s' % str(symbols))
ValueError: Invalid limits given: ((i, Range(1, 50, 1)),)
>>> x = symbols('x', real=True, positive=True)
>>> limits0 = Interval(3, 8)
>>> integrate(x, (x, limits0))
55/2
```

#### Other comments/references
I am working on https://github.com/sympy/sympy/pull/16576 to add certain multivariate distributions. I observed that `Range` wasn't being accepted by the summation  but the sets of discrete distributions are usually described as either `Range` or pre-defined sets, like, `S.Naturals`. I have to make changes as in [this line of code](https://github.com/sympy/sympy/pull/16576/files#diff-f5bd154f958178a67c12702770445325R104). However, I think, this should have been handled by summation itself.

**Comment by smichr** [comment]
> should have been handled by summation itself.

sounds good

**Comment by czgdp1807** [comment]
@smichr If you haven't started solving it then I can try working on it by tomorrow, as soon as I am done with some distributions. I will tell you if I can handle this issue. I think it requires some changes to the way arguments are handled by `summation` at its entry point, though I haven't seen the function yet.
