### ISSUE TITLE
Some issues with Range

### ISSUE THREAD

**Issue by sylee957** [sympy/sympy#16817]
1. I see `Range(0, -1, 1)` returns `Range(0, 0, 1)`, but latex printer seems like bugged
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
~\Miniconda3\envs\sympy_dev_37\lib\site-packages\IPython\core\formatters.py in __call__(self, obj)
    343             method = get_real_method(obj, self.print_method)
    344             if method is not None:
--> 345                 return method()
    346             return None
    347         else:

~\Documents\GitHub\sympy\sympy\core\basic.py in _repr_latex_(self)
    425         """
    426         from sympy.printing.latex import latex
--> 427         s = latex(self, mode='plain')
    428         return "$\\displaystyle %s$" % s
    429 

~\Documents\GitHub\sympy\sympy\printing\latex.py in latex(expr, fold_frac_powers, fold_func_brackets, fold_short_frac, inv_trig_style, itex, ln_notation, long_frac_ratio, mat_delim, mat_str, mode, mul_symbol, order, symbol_names, root_notation, mat_symbol_style, imaginary_unit, gothic_re_im)
   2580     }
   2581 
-> 2582     return LatexPrinter(settings).doprint(expr)
   2583 
   2584 

~\Documents\GitHub\sympy\sympy\printing\latex.py in doprint(self, expr)
    207 
    208     def doprint(self, expr):
--> 209         tex = Printer.doprint(self, expr)
    210 
    211         if self._settings['mode'] == 'plain':

~\Documents\GitHub\sympy\sympy\printing\printer.py in doprint(self, expr)
    247     def doprint(self, expr):
    248         """Returns printer's representation for expr (as a string)"""
--> 249         return self._str(self._print(expr))
    250 
    251     def _print(self, expr, **kwargs):

~\Documents\GitHub\sympy\sympy\printing\printer.py in _print(self, expr, **kwargs)
    285                 printmethod = '_print_' + cls.__name__
    286                 if hasattr(self, printmethod):
--> 287                     return getattr(self, printmethod)(expr, **kwargs)
    288             # Unknown object, fall back to the emptyPrinter.
    289             return self.emptyPrinter(expr)

~\Documents\GitHub\sympy\sympy\printing\latex.py in _print_Range(self, s)
   1832         dots = r'\ldots'
   1833 
-> 1834         if s.start.is_infinite:
   1835             printset = dots, s[-1] - s.step, s[-1]
   1836         elif s.stop.is_infinite:

AttributeError: 'int' object has no attribute 'is_infinite'
Range(0, 0, 1)
```

2. Range having infinite beginning and finite ending
<img src=https://user-images.githubusercontent.com/34944973/57584479-afc27d80-7516-11e9-9fa7-6ea58234be38.png width=256px>

returns different result than the range having finite beginning and infinite ending.

<img src=https://user-images.githubusercontent.com/34944973/57584489-db456800-7516-11e9-8e1e-e23698d54134.png width=256>

The range from the infinity to 0, with positive step size should be empty range?

3. Is it right that the first element of the range beginning from the infinity to some finite ending is infinity like this?
<img src=https://user-images.githubusercontent.com/34944973/57584506-3a0ae180-7517-11e9-8e65-2c0af7982867.png width=256px>

**Comment by smichr** [comment]
> 1. Is it right that the first element of the range beginning from the infinity to some finite ending is infinity

yep...you will never get away from infinity. This is intentional. It raises an error if you try to iterate over it, however.

**Comment by smichr** [comment]
> The range from the infinity to 0, with positive step size should be empty range?

In order to allow Range to be used where range is used, it is necessary to not allow this to evaluate to Set notation.

**Comment by smichr** [comment]
> 1. Range having infinite beginning and finite ending

Yes, we know how this ends so we show what we know; and for infinite end, we know how it start.

**Comment by smichr** [comment]
> 1. Range(0, -1, 1)

This is a bug that slipped through instantiation, apparently:
```
>>> [type(i) for i in Range(1,3,2).args]
[<class 'sympy.core.numbers.One'>, <class 'sympy.core.numbers.Integer'>, <class 'sympy.core.numbers.Integer'>]
>>> [type(i) for i in Range(0, -1, 1).args]
[<type 'int'>, <type 'int'>, <type 'int'>]
```

**Comment by sylee957** [comment]
For the difference with python range,
Python range does not canonicalize to ```range(0, 0, 1)``` though.

```python
>>> range(-1, -5)
range(-1, -5)
>>> range(0)
range(0, 0)
>>> range(-1, -5).stop
-5
>>> range(0).stop
0
```

**Comment by smichr** [comment]
> Python range does not canonicalize

SymPy does: Range(0,0,1) is the canonical EmptySet form of a Range. There is no additional sanitizing that would need to happen when using Range: the stop will always be a step away from inf or sup. I can't verify now but check `range(1,4,2)` vs `Range(1,4,2)`: the latter will be shown as `Range(1, 5, 2)` and that is intentional, again, for canonicalization.
