### ISSUE TITLE
Make amendments to check method in sympy.stats.crv_types 

### ISSUE THREAD

**Issue by czgdp1807** [sympy/sympy#16842]
#### Changes to be made
Due to the merging of https://github.com/sympy/sympy/pull/16765 , some changes are needed to be made to `sympy.stats.crv_types` in the way, `check` method uses `_value_check` function. 
The task is to rewrite the `check` method in `sympy.stats.crv_types` for distributions which uses `_value_check` in the following manner,
```
_value_check(<cond1> <bool_op1> <cond2> <bool_op2> <cond3> <bool_op3> . . . <bool_opn> <condn>, msg)
```
`condi` is  the ith condition, `bool_opi` is the ith bool operator and msg is message. n > 0 or at least one bool operator should be there to make the change to `_value_check`.
The above `_value_check` can be rewritten as,
```
_value_check((<cond1>, <cond2>, <cond3>, . . ., <condn>), msg)
```
For detailed discussion threads, see the links in references.

#### Other comments/references
1. Related PRs - https://github.com/sympy/sympy/pull/16765, https://github.com/sympy/sympy/pull/16571
2. Current Code - [sympy.stats.crv_types](https://github.com/sympy/sympy/blob/master/sympy/stats/crv_types.py)
3. Priority - Low
4. Difficulty - Easy

**Comment by solus9** [comment]
Hi @czgdp1807,
`_value_check((<cond1>, <cond2>, <cond3>, . . ., <condn>), msg)` does this prototype means that you wanted a common msg, or somehow a customized message for each condition that is raising an error? Even then I don't understand how one can make it raise a customized error. Do you have any suggestions?
Thanks

**Comment by czgdp1807** [comment]
@solus9 Take a look at how `_value_check` is defined in `sympy.stats.rv` and go through the current code given in the references. I hope you will surely get your answer.

**Comment by solus9** [comment]
@czgdp1807 I went through the code and references and I understand that 
```
_value_check(alpha > 0, "Shape parameter Alpha must be positive.")
_value_check(beta > 0, "Shape parameter Beta must be positive.")
```
can be rewritten as 
`_value_check((alpha > 0, beta > 0), 'message')`
but then how can I make the `'message'` corresponds to the condition which is raising the error
Thank you for your time

**Comment by czgdp1807** [comment]
@solus9 As already said in the issue, there should be at least one boolean operator in the condition for the `_value_check` to be rewritten. Take a look at the following example,
```
_value_check(a.is_positive and b.is_positive, "a and b should be positive") # type of _value_check to be rewritten
_value_check((a.is_positive, b.is_positive), "a and b should be positive") # rewritten form of the above _value_check.
```
The messages are passed as an argument to the `_value_check`.

**Comment by solus9** [comment]
Please review the PR, and do let me know if there are further changed need to be done.
Thanks again.
