### ISSUE TITLE
Trig functions incorrect

### ISSUE THREAD

**Issue by RaenonX** [sympy/sympy#16846]
I ran the code below on [Sympy Live](https://live.sympy.org/) ang got the following results:

```
>>> sin(x) == 1/csc(x)
False
>>> cos(x) == 1/sec(x)
False
>>> tan(x) == 1/cot(x)
False
```

These three statements should be true all the time.

**Comment by ethankward** [comment]
`==` test for exact, not symbolic equality. You can do something like `simplify(sin(x) - 1/csc(x)) == 0`.

**Comment by RaenonX** [comment]
> `==` tests for exact, not symbolic equality. You can do something like `simplify(sin(x) - 1/csc(x)) == 0`.

Got it, is that the usage of `simplify()` the key, or making all the thing to a side is the key?

**Comment by ethankward** [comment]
The key is doing something that `simplify` knows how to deal with, which isn't guaranteed for any arbitrary expression.

**Comment by RaenonX** [comment]
I see. Thanks for the clarification. Do I need to close this issue?
