### ISSUE TITLE
BlockMatrix is printed with the wrong shape by NumPyPrinter

### ISSUE THREAD

**Issue by tBuLi** [sympy/sympy#16857]
`BlockMatrix` objects are printed with the wrong shape by NumPyPrinter. Below is a small minimal example:
```python
>>> from sympy import *
>>> import inspect
>>> import numpy
>>> 
>>> a_is = [MatrixSymbol('a_{}'.format(i), 100, 1) for i in range(3)]
>>> A = BlockMatrix([[a_i for a_i in a_is]])
>>> A.shape
(100, 3)
>>> 
>>> func = lambdify(a_is, A)
>>> print(inspect.getsource(func))
def _lambdifygenerated(a_0, a_1, a_2):
    return (array([[a_0, a_1, a_2]]))
>>> 
>>> # Evaluate the lambda function to compare the shape
>>> a_arrays = [numpy.ones(a_i.shape) for a_i in a_is]
>>> ans = func(*a_arrays)
>>> print(ans.shape)
(1, 3, 100, 1)
```
Now, this last shape should've been `(100, 3)`. Looking at the code generated by lambdify it is also clear why this happens: the `Matrix` representing the `BlockMatrix` is printed without accounting for the block nature of the matrix. 

After looking at the `numpy` docs I think the solution is very simple: use [numpy.block](https://docs.scipy.org/doc/numpy/reference/generated/numpy.block.html). So my suggested solution is to add the following code to the `NumPyPrinter`:
```python
def _print_BlockMatrix(self, expr):
    return '{0}({1})'.format(self._module_format('numpy.block'),
                             self._print(expr.args[0].tolist()))
```
This solves the problem. I wouldn't mind creating a PR for this if people agree and point me in the right direction as to where to put the tests.

**Comment by sylee957** [comment]
The test can be put under
https://github.com/sympy/sympy/blob/master/sympy/printing/tests/test_pycode.py
simply by declaring a function without arguments.

Thanks for reporting the issue.
Please don't mind opening up a new PR

**Comment by tBuLi** [comment]
I created PR #16867 to address this issue. I added the test to `test_numpy` though, it seemed like a more natural place. Let me know if it really has to be `test_pycode`.
