### ISSUE TITLE
Negated assumptions not handled correctly by __lt__

### ISSUE THREAD

**Issue by oscarbenjamin** [sympy/sympy#16915]
Coming from #16666

> > more likely problem for users and one that came up a few times in this PR is when assumptions are declared negatively
> 
> I think you have the right behavior here `negative=False` doesn't imply anything about being real since `I.is_negative` is also False.

It's the right behaviour for the wrong reason because after this PR we still have:
```
In [1]: x = Symbol('x', extended_negative=False)                                                                                  

In [2]: x < 0                                                                                                                     
Out[2]: False
```

This is due to this code in `Expr.__lt__` (that I didn't substantively change):
https://github.com/sympy/sympy/blob/b9604c5f59c587c8ecc5461e62ae70d96a4bfda5/sympy/core/expr.py#L365-L369

I have to say I don't understand exactly why that code is written the way it is but it doesn't handle the negative assumption case correctly.

_Originally posted by @oscarbenjamin in https://github.com/sympy/sympy/pull/16666#issuecomment-496582983_

**Comment by ShubhamKJha** [comment]
I believe `dif = self - other` should be considered only when both `self` and `other` are `extended_real`. 
With this diff
```diff
diff --git a/sympy/core/expr.py b/sympy/core/expr.py
index f2f781a16..b795b7346 100644
--- a/sympy/core/expr.py
+++ b/sympy/core/expr.py
@@ -362,7 +362,7 @@ def __lt__(self, other):
         n2 = _n2(self, other)
         if n2 is not None:
             return _sympify(n2 < 0)
-        if self.is_extended_real or other.is_extended_real:
+        if self.is_extended_real and other.is_extended_real:
             dif = self - other
             if dif.is_extended_negative is not None and \
                     dif.is_extended_negative is not dif.is_extended_nonnegative:
```
all tests pass except one:
https://github.com/sympy/sympy/blob/fc66c081b1f5a90654db46cd4f2612f94d7185e8/sympy/functions/elementary/tests/test_piecewise.py#L851-L857

The result I am getting is:
```
⎧      B⋅x        for a > 2 ∧ a < ∞  # ( a < oo) is added
⎪
⎪⎧A⋅x  for x < 0
⎪⎪
⎪⎨B⋅x  for x < 1      for a < 1
⎨⎪
⎪⎩nan  otherwise
⎪
⎪⎧B⋅x  for x < 1
⎪⎨                    otherwise
⎩⎩nan  otherwise
```

**Comment by oscarbenjamin** [comment]
> I believe `dif = self - other` should be considered only when both `self` and `other` are `extended_real`.

I agree.

Can the part after not be simplified as well?
```diff
diff --git a/sympy/core/expr.py b/sympy/core/expr.py
index f2f781a165..6aac4565e2 100644
--- a/sympy/core/expr.py
+++ b/sympy/core/expr.py
@@ -362,11 +362,10 @@ def __lt__(self, other):
         n2 = _n2(self, other)
         if n2 is not None:
             return _sympify(n2 < 0)
-        if self.is_extended_real or other.is_extended_real:
-            dif = self - other
-            if dif.is_extended_negative is not None and \
-                    dif.is_extended_negative is not dif.is_extended_nonnegative:
-                return sympify(dif.is_extended_negative)
+        if self.is_extended_real and other.is_extended_real:
+            neg = (self - other).is_extended_negative
+            if neg is not None
+                return sympify(neg)
         return StrictLessThan(self, other, evaluate=False)
 
     def __trunc__(self):
```

**Comment by ShubhamKJha** [comment]
> Can the part after not be simplified as well?

yeah, it can be simplified since with `self` and `other` both being `extended_real`, the second part is redundant. But the test failure needs to be looked into. There since `a` is finite including `a < oo` makes sense but the same doesn't happen for `a < 1`.

**Comment by oscarbenjamin** [comment]
Knowing that a is finite is not enough to know that a<oo is True since a might be `I` or something. The test should be changed to `a, b = symbols('a, b', real=True)`.

**Comment by ShubhamKJha** [comment]
I think the test should remain there changed with correct results. The current master produced the wrong results since in it:
```python
>>> x = symbols('x', finite=True)
>>> x < oo
True
>>> x > -oo
True
``` 
which are wrong, since `x` can be `complex`

**Comment by oscarbenjamin** [comment]
> the test should remain there changed with correct results

Seems reasonable.

A PR for this should also change the 3 other relational methods `__le__`, `__ge__`, `__gt__` which will probably lead to other test failures.

**Comment by ShubhamKJha** [comment]
Yeah, I am testing that.

Also, there is this test:
https://github.com/sympy/sympy/blob/a6232c17a6d3c79e95353924df3a3cd062df0708/sympy/core/tests/test_expr.py#L1848-L1852
I am not able to track the issue mentioned.

**Comment by oscarbenjamin** [comment]
It's #11122. Although that test was modified in my PR so that it probably doesn't work as intended any more.

**Comment by ShubhamKJha** [comment]
Although the comment in https://github.com/sympy/sympy/issues/11122#issue-155313221 makes sense, personally I think the result should be unevaluated. Instead, `extended_nonpositive = True` should be used in place of `extended_positive = False`.

The other wrong result https://github.com/sympy/sympy/issues/16915#issuecomment-498208248 comes due to another issue in `add`:

```python
>>> from sympy import symbols, oo
>>> x = symbols('x', finite=True)
>>> (oo - x).is_extended_positive
True
>>>
```
which is wrong since `x` can be `I` or any complex number.
