### ISSUE TITLE
as_independent changed behaviour

### ISSUE THREAD

**Issue by proy87** [sympy/sympy#16920]
In earlier versions of sympy `(1/(2*x**2+2)).as_independent(x, as_Add=False)` returned
(1/2, 1/(x**2 + 1)), but now it returns `(1, 1/(2*x**2 + 2))`. How can I efficiently strip out constants (non-symbol), so `(1/(y*x**2+y))` becomes `(1/y, 1/(x**2+1))`?

**Comment by smichr** [comment]
```python
>>> factor_terms(1/(2*x**2+2)).as_independent(x, as_Add=False)
(1/2, 1/(x**2 + 1))
```

**Comment by proy87** [comment]
@smichr , I don't want to factor, `1/(2x^2+4x+1)` should become `(1/2, 1/(x^2+2x+1))`, not `(1/2, 1/(x+1)^2)`

**Comment by oscarbenjamin** [comment]
The suggestion seems to work for that case also
```julia
In [28]: factor_terms(1/(2*x**2+4*x+2)).as_independent(x, as_Add=False)                                                           
Out[28]: 
⎛          1      ⎞
⎜1/2, ────────────⎟
⎜      2          ⎟
⎝     x  + 2⋅x + 1⎠
```
