### ISSUE TITLE
[Discussion] Exporting expression of RVs to External Libraries

### ISSUE THREAD

**Issue by ritesh99rakesh** [sympy/sympy#16942]
There are 2 objective to this topic:
1. Use external libraries to sample from simple distributions. Here we can use `numpy`, `scipy`, `pymc3` and `stan` for doing sampling for simple distributions. Eg.
```python
>>> # NumPy
>>> X = Normal('X', 0, 1)
>>> c = export_normal(X, numpy=True, size=3)
>>> c['numpy']
array([-0.85648314, -1.67294285,  1.32458402])

>>> # PyMC3
>>> X = Normal('X', 0, 1)
>>> c = export_normal(X, pymc3=True, size=3)
>>> c['pymc3'][:]['X']
array([ 0.70263423, -0.59543018, -0.36750535])
```
2. Use external libraries for doing inference. When performing probabilistic inference, often we don't have the final distribution in closed form. In such situations, we can use sampling-based methods given in `PyMC3` and `stan` to get the sample (refer [pymc3/sampling](https://docs.pymc.io/api/inference.html) and [stan/sampling](https://mc-stan.org/rstan/reference/stanmodel-method-sampling.html)). Here I propose that we should be able to sample for compound distributions for which we can't find the final distribution in closed form. 
---
**Note from my proposal:** I couldn't find a general method to compute the density of compound RV (I believe that such general formula doesn't exist, because it would require integrating out at least one parameter, e.g. non-conjugate prior in machine learning). But for some instances, it is possible as given [here](https://en.wikipedia.org/wiki/Compound_probability_distribution#Examples).

---
Therefore, whenever we are not able to simplify the compound distribution, we should give an option to the user to export the RV to `pymc3` or `stan` for inference. *This will require us to break down the distribution into priors and likelihood distribution.* Eg.
```python3
# Suppose we have a normal distribution RV `X` with hyperparameter `mu` and `sigma`
# distributed uniformly in [10, 20]. Since we cannot find the exact distribution of `X`,
# we can export `X` to pymc3 to do inference by sampling.
# For this we have to find the distributions of `mu` and `sigma` and
# then run `pymc3` model to do inference.
>>> mu = Uniform('mu', 10, 20)
>>> sigma = Uniform('sigma', 10, 20)
>>> X = Normal('X', mu, sigma)
>>> E(X)
NotImplementedError: 
Expectations of expression with unindexed joint random symbols cannot
be calculated yet.

>>> trace = export_compound_normal(X, pymc3=True, size=100)
>>> import numpy as np
>>> np.mean(trace[:]['X'])
15.01604506092257
```

**Implementation**
First case:
```python3
def export_normal(rv, *args, **kwargs):
    if len(kwargs) == 0:
        raise ValueError('Please enter the library to'
                         ' which the random is to be exported.')
    objs = {}
    name = rv.args[0].name
    mu, sigma = rv.pspace.distribution.args
    if isinstance(mu, Symbol) or isinstance(sigma, Symbol):
        raise ValueError('Symbolic parameters cannot be '
                        ' exported.')
    mu, sigma = int(mu), int(sigma)
    if kwargs.get('numpy', False):
        objs['numpy'] = np.random.normal(mu, sigma, size=kwargs.get('size', 1))
    if kwargs.get('pymc3', False):
        pymc3_model = pm.Model()
        with pm.Model() as model:
            X = pm.Normal(name, mu, sigma)
            objs['pymc3'] = pm.sample(size, chains=1)
    return objs
```
Second case: For this I will send a PR with basic prototype for discussion.

I have gone through `lambdify.py` in `sympy/utilities/lambdify.py` and will follow a similar path for `Probability export`.

Ping @Upabjojr @sidhantnagpal @czgdp1807

**Comment by czgdp1807** [comment]
I wrote the first case implementation just for the purpose of proposal. I think we may need to implement a framework to export random symbols without much changes to the original code. One idea can be as to convert the `args` of the distribution of the `RandomSymbol`. This can be done by adding a method like, `export` to the class `RandomSymbol`. 

`mu, sigma = int(mu), int(sigma)` -> `mu, sigma = float(mu), float(sigma)`
@sylee957 Please add the `GSoC` label to it. Thanks.

**Comment by oscarbenjamin** [comment]
Maybe this could be part of lambdify

**Comment by Upabjojr** [comment]
I suggest to create some new printer classes. Have a look at how printers are implemented in sympy/printing folder.

**Comment by Upabjojr** [comment]
@ritesh99rakesh also lambdify is a good function to have a look upon. It can be extended to export the sampling.

**Comment by ritesh99rakesh** [comment]
@sidhantnagpal @Upabjojr I have the following suggestion for implementation for *first case*:
At present we have `sample` function is many of the distributions. We could modify these to include other libraries like `pymc3`, `numpy`, `tensorflow` and `stan`.
Also having such functions will help us to sample for `compound distributions` where we can find the final distribution in closed form (see *note* [here](https://github.com/sympy/sympy/issues/16942#issue-451161002)).
Moreover, since we are using external libraries, we will be able to sample from distributions from which we currently have not implemented sample function.

Example:
```python3
class NormalDistribution(SingleContinuousDistribution):
    ...
    def sample(self):
         if len(kwargs) == 0:
        raise ValueError('Please enter the library to'
                         ' which the random is to be exported.')
        objs = {}
        name = self.name
        mu, sigma = self.mean, self.std
        if isinstance(mu, Symbol) or isinstance(sigma, Symbol):
            raise ValueError('Symbolic parameters cannot be '
                        ' exported.')
        mu, sigma = float(mu), float(sigma)
        if kwargs.get('numpy', False):
            objs['numpy'] = np.random.normal(mu, sigma, size=kwargs.get('size', 1))
        if kwargs.get('pymc3', False):
            with pm.Model() as model:
                X = pm.Normal(name, mu, sigma)
                objs['pymc3'] = pm.sample(size, chains=1)
        return objs
```

**Comment by ritesh99rakesh** [comment]
@Upabjojr Thank you for your suggestion. I will look into both printer class and will also look for implementation style in lambdify and will get back to you by tonight.

**Comment by Upabjojr** [comment]
@ritesh99rakesh at this point, just create many methods (e.g. `_sample_numpy`, `_sample_scipy`, `_sample_pymc3`, ... ). The code looks cleaner this way.

**Comment by Upabjojr** [comment]
The method `sample` could then be moved to a superclass and have a global parameter specifying which secondary method to call.

**Comment by ritesh99rakesh** [comment]
@Upabjojr I have written the logic for `_sample_numpy` and `_sample_scipy` and wanted to raise a PR, but I am having difficultly deciding the place to keep the code. Should I make another file or should these functions be inside there distribution type eg. for continuous distributions the functions should be in `sympy/stats/crv_types.py`.

I believe that creating a separate file for sample wrapper would be better since sampling for all distributions could be written in the same file.

**Comment by Upabjojr** [comment]
They should be methods of the classes. There is already a "sample" function, just try to continue the existing code.

**Comment by Upabjojr** [comment]
If you add methods, add them next to "def sample(...): ... "

**Comment by czgdp1807** [comment]
Closing in favour of #19061
