### ISSUE TITLE
Sphinx build failing

### ISSUE THREAD

**Issue by sylee957** [sympy/sympy#16945]
The recent build had failed after sphinx had been updated to 2.1.0, 
https://travis-ci.org/sympy/sympy/builds/540395440
I've confirmed that the fail is due to the update today.

**Comment by moorepants** [comment]
Maybe Sphinx should be pinned to a specific version on CI and only updated manually.

**Comment by oscarbenjamin** [comment]
So the duplicate references are in:

1. doc/src/modules/holonomic/operations.rst
2. doc/src/modules/holonomic/convert.rst

They both have references to
```
.. module:: sympy.holonomic.holonomic
```
I've tried deleting each and either way I get an error e.g.:
```
don't know which module to import for autodocumenting 'HolonomicFunction.integrate' (try placing a "module" or "currentmodule" directive in the document, or giving an explicit module name)
make: *** [html] Error 2
```

**Comment by sylee957** [comment]
I think that `..module::` directive was used for mananging the context, allowing usage like `HolonomicFunction.integrate` instead of `sympy.holonomic.holonomic.HolonomicFunction.integrate`, so without the directive, it should be latter.

However, I think that it still fails with
```
duplicate object description of sympy.simplify.cse_main, other instance in modules/rewriting, use :noindex: for one of them
Makefile:49: recipe for target 'html' failed
```
and it seems like `module` directive is used in more places than holonomic.

I'm still not sure if sympy had been using deprecated features, or they had introduced some regressions.
If no good solution comes out in days, I'd support pinning down.

**Comment by sidhantnagpal** [comment]
+1 to pinning (at least until a resolution). A version prior to 2.0 could be used, given that formatting has also been affected with the new version, ref: https://github.com/sympy/sympy/issues/16585.

**Comment by jksuom** [comment]
The original error message suggests using the :noindex: directive. Could that be possible?
