### ISSUE TITLE
sympy.stats.finite_rv doesn't support symbolically sized sample spaces

### ISSUE THREAD

**Issue by czgdp1807** [sympy/sympy#16961]
#### What is the problem?
The current problem faced by sympy.stats.finite_rv is unable to process symbolically sized dimensions. One suggestion from my side on this is to return un-evaluated results in such cases as is being done with `MultivariateEwens`, `Multinomial` which are discrete mulitvariate distributions.

#### Example of problem
```
In [21]: from sympy.stats import Binomial, E

In [22]: from sympy import symbols

In [23]: n, p = symbols('n, p')

In [24]: X = Binomial('X', n, p)

In [25]: E(X)
...
ValueError: n is not an integer
```

#### Other comments/references
[1] https://github.com/sympy/sympy/issues/16944#issuecomment-498644930

ping @oscarbenjamin @Upabjojr

**Comment by czgdp1807** [comment]
I am working on it.

**Comment by czgdp1807** [comment]
See, https://github.com/sympy/sympy/pull/19123

**Comment by Smit-create** [comment]
Also related #19687

**Comment by czgdp1807** [comment]
Duplicate and older to https://github.com/sympy/sympy/issues/20447
Closing this one.
