### ISSUE TITLE
SyntaxWarning in Python 3.8

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#16973]
Comparing integers with `is` gives a syntax warning in Python 3.8.

```
/home/aaronmeurer/Documents/python/sympy/sympy/sympy/solvers/diophantine.py:3185: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if feasible is 1:  # it's prime and k == 2
/home/aaronmeurer/Documents/python/sympy/sympy/sympy/plotting/plot.py:645: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if self.xscale is 'log':
/home/aaronmeurer/Documents/python/sympy/sympy/sympy/plotting/plot.py:674: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if self.xscale is 'log':
/home/aaronmeurer/Documents/python/sympy/sympy/sympy/plotting/plot.py:681: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if self.xscale is 'log':
```

**Comment by asmeurer** [comment]
We should also make sure our compileall on Travis would catch these.

**Comment by asmeurer** [comment]
There are more that aren't part of the main `import sympy`. You can get the full list with 

```
python3.8 -We:literal -m compileall -f -q sympy
```

```
sympy/core/tests/test_containers.py:55: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  assert Tuple(1, 2) is not (1, 2)
sympy/geometry/tests/test_plane.py:199: SyntaxWarning: "is" with a literal. Did you mean "=="?
  assert len(pl8.intersection(Ray3D(Point3D(0, 2, 3), Point3D(1, 0, 3)))) is 0
sympy/physics/vector/printing.py:153: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if len(base_split) is not 1:
sympy/plotting/plot.py:645: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if self.xscale is 'log':
sympy/plotting/plot.py:674: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if self.xscale is 'log':
sympy/plotting/plot.py:681: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if self.xscale is 'log':
sympy/polys/agca/modules.py:360: SyntaxWarning: "is" with a literal. Did you mean "=="?
  elif elem is 0:
sympy/solvers/diophantine.py:3185: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if feasible is 1:  # it's prime and k == 2
sympy/utilities/codegen.py:277: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if dt is "int" and not element.is_integer:
sympy/utilities/codegen.py:279: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if dt is "float" and not element.is_real:
sympy/vector/coordsysrect.py:170: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if transformation.name is 'spherical':
sympy/vector/coordsysrect.py:172: SyntaxWarning: "is" with a literal. Did you mean "=="?
  elif transformation.name is 'cylindrical':
```

**Comment by vighneshq** [comment]
If no one else is working on this, can I take this up?

**Comment by vighneshq** [comment]
If this hasn't been taken up, can I have a look at this?

**Comment by oscarbenjamin** [comment]
Yes, go ahead

**Comment by vighneshq** [comment]
In sympy/core/tests/test_containers.py should I just remove,  ``` assert Tuple(1, 2) is not (1, 2) ```
since replacing it with "!=" doesn't make sense given there is already another assertion of the form, ``` assert (Tuple(1, 2) != (1, 2)) is False ```?

**Comment by asmeurer** [comment]
I'm not sure what that is supposed to test. Maybe replace it with `assert not isinstance(Tuple(1, 2), tuple)`.

**Comment by vighneshq** [comment]
I am not completely comfortable with Travis yet, should I change 
``` python -We:invalid -m compileall -f -q sympy/; ``` to ``` python -We:invalid,literal -m compileall -f -q sympy/;``` for it to handle that?

**Comment by vighneshq** [comment]
I am not really comfortable working with Travis yet, can someone guide me on what I should be changing there?

**Comment by oscarbenjamin** [comment]
Try running the command yourself to see if it raises an error

**Comment by vighneshq** [comment]
> There are more that aren't part of the main `import sympy`. You can get the full list with
> 
> ```
> python3.8 -We:literal -m compileall -f -q sympy
> ```
> 
> ```
> sympy/core/tests/test_containers.py:55: SyntaxWarning: "is not" with a literal. Did you mean "!="?
>   assert Tuple(1, 2) is not (1, 2)
> sympy/geometry/tests/test_plane.py:199: SyntaxWarning: "is" with a literal. Did you mean "=="?
>   assert len(pl8.intersection(Ray3D(Point3D(0, 2, 3), Point3D(1, 0, 3)))) is 0
> sympy/physics/vector/printing.py:153: SyntaxWarning: "is not" with a literal. Did you mean "!="?
>   if len(base_split) is not 1:
> sympy/plotting/plot.py:645: SyntaxWarning: "is" with a literal. Did you mean "=="?
>   if self.xscale is 'log':
> sympy/plotting/plot.py:674: SyntaxWarning: "is" with a literal. Did you mean "=="?
>   if self.xscale is 'log':
> sympy/plotting/plot.py:681: SyntaxWarning: "is" with a literal. Did you mean "=="?
>   if self.xscale is 'log':
> sympy/polys/agca/modules.py:360: SyntaxWarning: "is" with a literal. Did you mean "=="?
>   elif elem is 0:
> sympy/solvers/diophantine.py:3185: SyntaxWarning: "is" with a literal. Did you mean "=="?
>   if feasible is 1:  # it's prime and k == 2
> sympy/utilities/codegen.py:277: SyntaxWarning: "is" with a literal. Did you mean "=="?
>   if dt is "int" and not element.is_integer:
> sympy/utilities/codegen.py:279: SyntaxWarning: "is" with a literal. Did you mean "=="?
>   if dt is "float" and not element.is_real:
> sympy/vector/coordsysrect.py:170: SyntaxWarning: "is" with a literal. Did you mean "=="?
>   if transformation.name is 'spherical':
> sympy/vector/coordsysrect.py:172: SyntaxWarning: "is" with a literal. Did you mean "=="?
>   elif transformation.name is 'cylindrical':
> ```

These warnings are generated even when the compileall command is run without any warning flags. Using any type of category such as 'invalid' or 'literal' with ``` python -We ``` results in a warning, however the process still exits with an exit code of 0. 

Running ``` python -We -m compileall -f -q sympy/ ``` does create an error and the process exits with a non-zero exit code. Modifying the command in the .travis.yml to this would seem to work, I guess.

**Comment by oscarbenjamin** [comment]
Which of the arguments is it that actually turns the warning into an error?

**Comment by vighneshq** [comment]
Just ``` -We ```
Using any label along with it, displays it as warning.

**Comment by oscarbenjamin** [comment]
Yeah give that a try. If you send a PR we can easily see how your changes compare to the original code and can discuss further

**Comment by vighneshq** [comment]
Alright, thanks a lot :). I will send the PR after adding the changes. 

Just wanted to ask one last thing, wrapping literals with an ``` int() ``` or an ```str()``` gets ride of the warning. However, that seemed to be the incorrect way to go about it, and I am using the comparison operators along with the ``` isinstance() ``` function to handle it right now. Is that alright, or should I switch?

**Comment by asmeurer** [comment]
The whole point of the warnings it that you shouldn't use `is` to compare built in types. So the `is` comparison should be removed completely. Wrapping would just be a bandaid on the problem.
