### ISSUE TITLE
Equality test between Dict and dict does not pass 

### ISSUE THREAD

**Issue by kangzhiq** [sympy/sympy#16984]
The equality test beween a `Dict` object and a `dict` object does not pass. I ran into this issue while manipulating the dictionaries in Sparse Array module.
```
>>> from sympy import Dict
>>> a = Dict({1:3,2:4})
>>> b = {1:3,2:4}
>>> a == b
False
```

For comparison, the contrainer `Tuple` can handle this equality test:
```
>>> from sympy import Tuple
>>> a = Tuple(1, 2, 3, 4)
>>> b = (1, 2, 3, 4)
>>> a == b
True
```

**Comment by smichr** [comment]
This has been solved in the current master:
```python
>>> a = Dict({1:3,2:4})
>>> b = {1:3,2:4}
>>> a == b
True
```

**Comment by kangzhiq** [comment]
Ah ok, I didn't know it. Thank you!
