### ISSUE TITLE
frac(zoo) gives TypeError

### ISSUE THREAD

**Issue by oscargus** [sympy/sympy#16992]
```

In [1]: from sympy import frac, zoo

In [2]: frac(zoo)
Traceback (most recent call last):

  File "<ipython-input-2-eb6875922196>", line 1, in <module>
    frac(zoo)

  File "C:\Users\Oscar\sympy\sympy\core\function.py", line 458, in __new__
    result = super(Function, cls).__new__(cls, *args, **options)

  File "C:\Users\Oscar\sympy\sympy\core\function.py", line 277, in __new__
    evaluated = cls.eval(*args)

  File "C:\Users\Oscar\sympy\sympy\functions\elementary\integers.py", line 333, in eval
    return real + S.ImaginaryUnit*imag

TypeError: unsupported operand type(s) for +: 'NoneType' and 'Zero'
```

Not sure what should happen, but not this. 

I am trying to cover these lines in a test:
https://github.com/sympy/sympy/blob/51630a792b1ff403151e70bdd692a0d290eb09ca/sympy/functions/elementary/integers.py#L311-L312

Clearly, they are covered by calling `frac(zoo)` since the `NoneType` comes from that line, but I do not really want an exception...

**Comment by oscarbenjamin** [comment]
I think it should return nan instead of None so that `frac(zoo) -> nan`.

**Comment by oscargus** [comment]
oo gives `AccumBounds(0, 1)` so an option may be `AccumBounds(0, 1) + I*AccumBounds(0, 1)` or something. Not sure when one would like to call it though. Even for oo.

**Comment by jksuom** [comment]
I think that `nan` would be the best choice (for `oo` as well unless a "real nan" is implemented).
