### ISSUE TITLE
[Discussion] Get handle to the plot generated by Beam.plot_shear_force

### ISSUE THREAD

**Issue by QuantumNovice** [sympy/sympy#17002]
I am sorry if this is a stupid question I can't seem to manipulate the plot generated by b.plot_shear_force()

b = Beam(x, E, I)
...
b.plot_shear_force()

How do I get a handle to the plot?

**Comment by jashan498** [comment]
I don't think you can change the plot returned by `b.plot_shear_force`. But still what kind of changes you want to do on it?

**Comment by QuantumNovice** [comment]
I want to  change
- Change axis ticks
- Turning grid on and changing grid space
- Adding legends, the usual matplotlib stuff

**Comment by oscarbenjamin** [comment]
Can you get a handle to the plot using gca?
https://matplotlib.org/3.1.0/api/_as_gen/matplotlib.pyplot.gca.html

That's not ideal though. I think that `plot_shear_force` or a related function should return a handle to the figure/axes

**Comment by moorepants** [comment]
The method should at least return the sympy plot object, no?

**Comment by QuantumNovice** [comment]
@moorepants It returns the sympy plot object. On calling the function it plotted the shear force, I just assumed this would return none. 
Also plt.gca or plt.gcf works.
Thank you @moorepants @oscarbenjamin  @jashan498
