### ISSUE TITLE
[GSoC][Discussion] Compound distributions

### ISSUE THREAD

**Issue by ritesh99rakesh** [sympy/sympy#17007]
**Compound Distributions**

SymPy allows for the creation of compound RVs. The density can be calculated for these variables but, the probability of an event can't be calculated:
```python
>>> x = Symbol('x')
>>> N = Normal('N', 0, 1)
>>> M = Normal('M', N, 1)
>>> simplify(density(M)(x).doit())
exp(-x**2/4)/(2*sqrt(pi))
>>> P(M > 2)
RuntimeError: maximum recursion depth exceeded while calling a Python object
```
At present, if a given expression contains compound RVs, the probability space is taken as a `JointPSpace`:
```python
if any(isinstance(arg, RandomSymbol) for arg in args):
    pspace = JointPSpace(symbol, CompoundDistribution(dist))
```
(stats/crv_types.py and stats/drv_types.py)

Which assumes that the RV belongs to `JointPSpace`. This concept mixes both joint and compound distributions and complicates the further computation of compound RV.

To solve this issue, I plan to implement compound RVs in a separate file(`compound_rv.py`), Very similar to joint distribution. This also requires to implement a separate class of probability space called `CompoundPSpace`. An object of this class will be created if the parameters of the given RV are found to be distributed according to another RV.

For example, while creating a compound continuous RV:
```python
def compound_rv(cls, sym, *args):
    args = list(map(sympify, args))
    dist = cls(*args)
    args = dist.args
    dist.check(*args)
    return CompoundPSpace(sym, dist).value
```
(similar to `multivariate_rv()` for `joint_rv`)

I couldn't find a general method to compute the density of compound RV *(I believe that such general formula doesn't exist, because it would require integrating out at least one parameter, e.g. non-conjugate prior in machine learning)*. But for some instances, it is possible as given [here](https://en.wikipedia.org/wiki/Compound_probability_distribution#Examples).

Consider the following code of how this case can be dealt with:
```python
class CompoundPSpace(PSpace):
    def __new__(cls, s, distribution):
        dist = compute_compound_type(distribution)
        return Basic.__new__(cls, s, dist)
```

`compute_compound_type` is a function to find the resulting distribution after compounding. This can be done in stages:

  1. Find out what my original distribution is. Say, `mu ~ Normal('mu', mu0, sigma0**2)`.
  2. Find out how the distribution is compounded, i.e. which parameter is compounded and which distribution it is. Say `X ~ Normal('X', mu, sigma**2)`
  3. Return the resultant distribution with the modified parameters. In our case, it is `Normal`, `X ~ Normal('X', mu0, sigma0**2 + sigma**2)`

Code for above example would like:
```python
def compute_compound_type(distribution, **kwargs):
    ...
    if isinstance(distribution, NormalDistribution):
        mean, var = distribution.args()
        if isinstance(mean, NormalDistribution) and not \
            isinstance(var, RandomVariable):
            dens = density(mean)
            return NormalDistribution(dens.args[0], var + dens.args[1])
```
An unevaluated object would be returned if the type of distribution can't be evaluated.

Compound distributions are very common in Machine Learning especially Probabilistic ML. A well known example from Probabilistic ML is that of Negative Binomial distribution(NBD). The NBD arises as a continuous mixture of Poisson distributions (i.e. a compound probability distribution) where the mixing distribution of the Poisson rate is a gamma distribution.
```python
>>> k = Symbol("k", positive=True)
>>> theta = Symbol("theta", positive=True)
>>> lamda = Gamma("lamda", k, theta)
>>> X = Poisson("x", lamda)
>>> # therefore above function would return
>>> compute_compuound_type(X)
NegativeBinomial("x", k, theta/(theta+1))
```

ping @Upabjojr @sidhantnagpal @czgdp1807 
I would love to know your views and suggestion on this.

**Comment by sidhantnagpal** [comment]
> This also requires to implement a separate class of probability space called `CompoundPSpace`.

I'd start by first looking into `joint_rv.py` (which was worked on in last GSoC) before considering another class. That'd probably help fixing (or at least identifying) the recursion errors.

Also see https://github.com/sympy/sympy/pull/16934 aimed at fixing some of those bugs and improving the coverage.

**Comment by czgdp1807** [comment]
Can you please show the exact traceback of `P(M > 2) ` in your description?  Just copy and paste it here from the terminal. 
Regarding `CompoundPSpace`, it's a good idea to decouple the two concepts in implementation. Since,  the API would be very similar to the existing one, so not much discussion is needed on that. However, can you make a PR for prototype with some tests so that your ideas become more clear. 
I think making two prototypes will be better one for decoupling the `JointPSpace` and `CompoundPSpace`. The second should aim at adjusting the current implementation for compound distributions without adding extra classes. Do it only if it's possible.

**Comment by ritesh99rakesh** [comment]
> > This also requires to implement a separate class of probability space called `CompoundPSpace`.
> 
> I'd start by first looking into `joint_rv.py` (which was worked on in last GSoC) before considering another class. That'd probably help fixing (or at least identifying) the recursion errors.
> 
@sidhantnagpal I believe that compound distributions should manually identify individual distributions and converted the overall distribution to the final closed form. Reason for this is that most of the time, we don't have the closed form solution for compound distributions and hence we might get infinite recursion.
Please let me know your thoughts on this.

**Comment by ritesh99rakesh** [comment]
> Can you please show the exact traceback of `P(M > 2) ` in your description? Just copy and paste it here from the terminal.
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ritesh/Desktop/sympy/sympy/stats/rv.py", line 775, in probability
    result = pspace(condition).probability(condition, **kwargs)
  File "/home/ritesh/Desktop/sympy/sympy/stats/rv.py", line 396, in probability
    result = space.probability(condition.__class__(space.value, 0))
  File "/home/ritesh/Desktop/sympy/sympy/stats/crv.py", line 452, in probability
    result = space.probability(condition.__class__(space.value, 0))
  File "/home/ritesh/Desktop/sympy/sympy/stats/crv.py", line 452, in probability
    result = space.probability(condition.__class__(space.value, 0))
  File "/home/ritesh/Desktop/sympy/sympy/stats/crv.py", line 452, in probability
    result = space.probability(condition.__class__(space.value, 0))
  [Previous line repeated 966 more times]
  File "/home/ritesh/Desktop/sympy/sympy/core/relational.py", line 652, in __new__
    r = cls._eval_relation(lhs, rhs)
  File "/home/ritesh/Desktop/sympy/sympy/core/relational.py", line 961, in _eval_relation
    return _sympify(lhs.__gt__(rhs))
  File "/home/ritesh/Desktop/sympy/sympy/core/expr.py", line 377, in __gt__
    if me.is_complex and me.is_extended_real is False:
  File "/home/ritesh/Desktop/sympy/sympy/core/assumptions.py", line 266, in getit
    return _ask(fact, self)
  File "/home/ritesh/Desktop/sympy/sympy/core/assumptions.py", line 321, in _ask
    _ask(pk, obj)
  File "/home/ritesh/Desktop/sympy/sympy/core/assumptions.py", line 309, in _ask
    a = evaluate(obj)
  File "/home/ritesh/Desktop/sympy/sympy/core/expr.py", line 854, in _eval_is_negative
    extended_negative = self.is_extended_negative
  File "/home/ritesh/Desktop/sympy/sympy/core/assumptions.py", line 266, in getit
    return _ask(fact, self)
  File "/home/ritesh/Desktop/sympy/sympy/core/assumptions.py", line 321, in _ask
    _ask(pk, obj)
  File "/home/ritesh/Desktop/sympy/sympy/core/assumptions.py", line 321, in _ask
    _ask(pk, obj)
  File "/home/ritesh/Desktop/sympy/sympy/core/assumptions.py", line 309, in _ask
    a = evaluate(obj)
  File "/home/ritesh/Desktop/sympy/sympy/stats/rv.py", line 259, in _eval_is_positive
    return self.symbol.is_positive
  File "/home/ritesh/Desktop/sympy/sympy/core/assumptions.py", line 266, in getit
    return _ask(fact, self)
  File "/home/ritesh/Desktop/sympy/sympy/core/assumptions.py", line 309, in _ask
    a = evaluate(obj)
  File "/home/ritesh/Desktop/sympy/sympy/core/expr.py", line 844, in _eval_is_positive
    extended_positive = self.is_extended_positive
  File "/home/ritesh/Desktop/sympy/sympy/core/assumptions.py", line 266, in getit
    return _ask(fact, self)
  File "/home/ritesh/Desktop/sympy/sympy/core/assumptions.py", line 309, in _ask
    a = evaluate(obj)
  File "/home/ritesh/Desktop/sympy/sympy/core/expr.py", line 861, in _eval_is_extended_positive
    from sympy.polys.numberfields import minimal_polynomial
  File "<frozen importlib._bootstrap>", line 1007, in _handle_fromlist
RecursionError: maximum recursion depth exceeded while calling a Python object
```
> Regarding `CompoundPSpace`, it's a good idea to decouple the two concepts in implementation. Since, the API would be very similar to the existing one, so not much discussion is needed on that. However, can you make a PR for prototype with some tests so that your ideas become more clear.
> I think making two prototypes will be better one for decoupling the `JointPSpace` and `CompoundPSpace`. The second should aim at adjusting the current implementation for compound distributions without adding extra classes. Do it only if it's possible.

Yes, @czgdp1807 I agree with you and will raise a PR for decoupling `JointPSpace` and `CompoundPSpace`.

**Comment by czgdp1807** [comment]
Closing in favour of #19332
