### ISSUE TITLE
Operations with MatrixSymbol should use the symbol, not the name

### ISSUE THREAD

**Issue by tBuLi** [sympy/sympy#17015]
`MatrixSymbol`'s can be set with an `Symbol`, such as
```python
x = MatrixSymbol(Symbol('x'), 3, 4)
```
However, some lines inside `MatrixSymbol` then use the `name` string, and not the object provided:

```python
def _eval_subs(self, old, new):
    # only do substitutions in shape
    shape = Tuple(*self.shape)._subs(old, new)
    return MatrixSymbol(self.name, *shape)

def doit(self, **hints):
    if hints.get('deep', True):
        return type(self)(self.name, self.args[1].doit(**hints),
                self.args[2].doit(**hints))
    else:
        return self
```
This breaks some of my code, where I have a Symbol subclass which does not only depend on a name. I would therefore propose changing the `self.name` here to `self.args[0]`.

As an additional question, in the `IndexedBase` class we call this kind of symbol a `label` instead, and then extract the `name` as `label.name`. Wouldn't it be more consistent to do the same thing here?

I will make a PR for the first, and let me know if the second idea is a good one, then I can also add that.

**Comment by smichr** [comment]
The PR with Indexed is running into these nuances. If an object accepts a Symbol in lieu of a string, then when recreating the object it is a good idea to stick with the same type -- as I think you are saying. But the last commit at 17009 shows that even some difference of using Symbol and Dummy can be troublesome because for `d=Dummy(), str(d) != d.name`.

**Comment by tBuLi** [comment]
Thanks for your reply. I'm not even sure it should be the same type, but the same instance, right? For example, in my tests for this PR I added an assumption and that already fails because the assumptions are not passed along. And for me personally it is even worse because I use a subclass, which sympy will not be able to initiate.

With dummies, I'm not familiar with that particular PR I must say, I will have to read up on it. But I think it indeed makes sense that you would inherit assumptions from such a model, but also I would think you should keep track of the exact instance, not just it's identifying qualities right? And then `Dummy`'s should be happy again?

(I admit btw that the heavy use of `__new__` and lack of tracking instances still confuses me.)
