### ISSUE TITLE
Missing NumPy matrix expression printers

### ISSUE THREAD

**Issue by anpandey** [sympy/sympy#17013]
The `NumPyPrinter` class currently does not implement the printing of the following matrix expressions which might have corresponding built-in NumPy functions:

* `DiagonalizeVector`
* `KroneckerProduct`
* `ZeroMatrix`
* `OneMatrix`
* `FunctionMatrix`
* `Adjoint`
* `HadamardProduct`
* `DiagonalMatrix`
* `DiagonalOf`

**Comment by vighneshq** [comment]
I will try and implement these if it's fine. 
One question, is ```DiagonalMatrix``` going to be removed (see #16682), if so there's no need to write add that one in.

**Comment by anpandey** [comment]
Sure, by all means go ahead! The PR at #17027 starts with stubs of the methods that need to be implemented.

**Comment by vighneshq** [comment]
@anpandey I already have a separate branch with some of the functions which would clash with your PR. Is there a way I can instead add you as a coauthor in mine?
