### ISSUE TITLE
isqrt gives incorrect results

### ISSUE THREAD

**Issue by mdickinson** [sympy/sympy#17034]
The `isqrt` function in `sympy.core.power` gives incorrect results for some inputs. For example:

```
>>> from sympy.core.power import isqrt
>>> n = 4503599761588224
>>> s = isqrt(n)
>>> s  # correct result is 67108864
67108865
>>> s**2 <= n  # expect True
False
```

or

```
>>> isqrt(9999999999999999)  # should be 99999999
100000000
```

Versions: Python 3.7.3, SymPy 1.4, macOS 10.14.5

## Analysis

For small values of `n`, the [current implementation](https://github.com/sympy/sympy/blob/3febfc43ca0aa23d916ef06057e8c6d396a955e7/sympy/core/power.py#L23-L27) uses `math.sqrt` (aliased to `_sqrt`):

```
    if n < 17984395633462800708566937239552:
        return int(_sqrt(n))
```

The main problem is that the bound used for `n` here is much too large, at almost `2**104`.

*If* (and it's quite a big if) we can assume that Python floats are IEEE 754 binary64 format _and_ that `math.sqrt` supplies a correctly-rounded (using round-ties-to-even) square root function, then the largest bound that can safely be used here is `4503599761588224`, or `2**52 + 2**27`.

If we can assume IEEE 754 binary64 `float`s but can't assume a correctly-rounded `math.sqrt`, then `int(_sqrt(n + 0.5))` is still safe for smallish `n`, where the definition of "smallish" depends on how accurate `math.sqrt` is. For example, if `_sqrt(n)` is known to be accurate to within 2 ulps, then it's possible to show that `int(_sqrt(n + 0.5))` is safe for `n < 2**50`. (The `+0.5` is necessary here: `int(_sqrt(n))` wouldn't be safe even for tiny `n`, since e.g. if the result of `_sqrt(25)` is off by a single ulp downwards, `int(_sqrt(25))` would produce `4` instead of `5`.)

Whether `math.sqrt` is correctly rounded or not will depend on the platform: Python's `math.sqrt` just wraps the `sqrt` function from C's math library. On modern x64 hardware, one would expect and hope that C's `sqrt` gets mapped to the appropriate SSE2 instruction, in which case it'll be correctly rounded. But on ARM there may well not be a hardware sqrt instruction to map to, and a hand-implemented libm sqrt could easily be incorrectly rounded for some inputs.

In the unlikely (but possible) case of non-IEEE 754 binary64 `float`s, it's probably safer to avoid using `math.sqrt` at all. But this case is likely to be exceedingly rare, and doesn't seem worth worrying about in practice.

I guess one option for fixing this while retaining performance for small `n` would be to continue to use the `int(_sqrt(n))` code, but then to check the result is correct before returning it, falling back to the slow integer-only path if that check doesn't pass.

**Comment by oscarbenjamin** [comment]
Thanks @mdickinson for reporting and looking into this.

I think that the simple fix is that we should reduce the threshold to 4503599761588224 and check the result before returning it with
```
if s**2 <= n and (s+1)**2 > n:
    return s
# Fall back to integer_nthroot
```
Using sqrt as a potential speed-boost is fine but the correctness of integer calculations in SymPy should not depend in any way on the underlying floating point configuration.

It might also be worth using a sqrt-specific integer root finder if timings show that it can be faster than integer_nthroot (for large or small integers):
https://en.wikipedia.org/wiki/Integer_square_root#Using_only_integer_division

**Comment by mdickinson** [comment]
> I think that the simple fix is that we should reduce the threshold to 4503599761588224 and check the result before returning [...]

Agreed. I've created a PR along those lines in #17038.

> It might also be worth using a sqrt-specific integer root finder [...]

In case it's of interest, I recently added a `math.isqrt` function for Python 3.8, that uses only integer arithmetic. There's [equivalent pure Python code](https://github.com/python/cpython/blob/45e0411eee023b21acf1615e995d26058d66c0f1/Modules/mathmodule.c#L1515-L1535) in the comments.

**Comment by mdickinson** [comment]
Ah, sorry @ritesh99rakesh: I missed that you'd already opened a PR for this.

**Comment by ritesh99rakesh** [comment]
@mdickinson No problem I will close my PR.

**Comment by ritesh99rakesh** [comment]
@oscarbenjamin these are my findings for comparison between sqrt-specific integer root finder and and integer_nthroot:
*test code*
```python
import time
from sympy import integer_nthroot

def int_div(y):
    x_k = y
    x_k_ = y//2
    while x_k != x_k_ and x_k - x_k_ != 1:
        x_k = x_k_
        x_k_ = (x_k_ + y//x_k_)//2

def int_2ndroot(y):
    return integer_nthroot(y, 2)


if __name__ == "__main__":
    num = [20, 10000, 12345678, 4503599761588224]
    print("sqrt-specific integer root")
    print("*"*30)
    for i in num:
        start = time.time()
        int_div(i)
        end = time.time()
        print(f'for n={i}, time={end-start}')
    print("integer_nthroot")
    print("*"*20)
    for i in num:
        start = time.time()
        int_2ndroot(i)
        end = time.time()
        print(f'for n={i}, time={end-start}')
```
*Results*
```python
sqrt-specific integer root
******************************
for n=20, time=1.6689300537109375e-06
for n=10000, time=2.6226043701171875e-06
for n=12345678, time=2.86102294921875e-06
for n=4503599761588224, time=9.059906005859375e-06
integer_nthroot
********************
for n=20, time=1.4066696166992188e-05
for n=10000, time=5.245208740234375e-06
for n=12345678, time=4.76837158203125e-06
for n=4503599761588224, time=3.0040740966796875e-05
```
As we can see that `integer_nthroot` is faster for both small and very large numbers and is only slightly worse than `sqrt-specific integer root` for middle range numbers. I suggest that we should use `integer_nthroot` function.
Please let me if I have made any mistake in my analysis.

**Comment by oscarbenjamin** [comment]
Thanks @ritesh99rakesh for the timings. I tested with larger integers and the difference is more pronounced:
```console
$ python -m timeit -s 'from t import int_div, int_2ndroot; from random import randint' 'n = randint(1, 10**1000); int_div(n)'
20 loops, best of 5: 14.1 msec per loop
$ python -m timeit -s 'from t import int_div, int_2ndroot; from random import randint' 'n = randint(1, 10**1000); int_2ndroot(n)'
20000 loops, best of 5: 16.3 usec per loop
```
(I put the code you showed in a file called t.py)

I wonder why the times are so different. I haven't looked closely but it looks like the algorithm in `int_div` is essentially the same as `integer_nthroot` except simplified a bit because it's specialised for n=2:
https://github.com/sympy/sympy/blob/ffa2a22cb06ecd7de1b95875f5d732ea37b990ac/sympy/core/power.py#L83-L89

**Comment by oscarbenjamin** [comment]
I see now that we're using a fast-path specialised for sqrt here:
https://github.com/sympy/sympy/blob/ffa2a22cb06ecd7de1b95875f5d732ea37b990ac/sympy/core/power.py#L67

That in turn comes from gmpy (if installed - which it is for my timings above):
https://github.com/fredrik-johansson/mpmath/blob/ac5f60fd17774cd7a92632dad9ae3a174bdd1b6d/mpmath/libmp/libintmath.py#L314

I guess that that ends up here:
https://gmplib.org/repo/gmp-6.1/file/tip/mpn/generic/sqrtrem.c

So it's not surprising that it's a lot faster for large integers.
