### ISSUE TITLE
is_square gives incorrect answers

### ISSUE THREAD

**Issue by charlesgriffiths** [sympy/sympy#17044]
from sympy.ntheory.primetest import is_square
from math import sqrt

print( 216000, "is square:", is_square( 216000 ) )
print( "sqrt( 216000 ) is:", sqrt( 216000 ))

> 216000 is square: True
> sqrt( 216000 ) is: 464.75800154489

related:
from sympy.ntheory import perfect_power

print( perfect_power( 216000, [2] ))
print( perfect_power( 216000, [2], factor = False ))

> (60, 3)
> False

**Comment by charlesgriffiths** [comment]
or return integer_nthroot( n, 2 )[1]

**Comment by smichr** [comment]
> or return integer_nthroot( n, 2 )[1]

`is_square` is supposed to give a quick confirmation that something is not a square, so that might be a reason to avoid a more direct calculation of the integer square root.

**Comment by charlesgriffiths** [comment]
> > or return integer_nthroot( n, 2 )[1]
> 
> `is_square` is supposed to give a quick confirmation that something is not a square, so that might be a reason to avoid a more direct calculation of the integer square root.

You have a very good point. I ran a test of three different solutions, and which is the fastest depends on the size of n.

In place of "if perfect_power(n, [2]): return True" in the current version

Solution a: if perfect_power(n, [2], factor=False): return True
Solution b: pp = perfect_power(n, [2], big=False)
                  return pp and 2 == pp[1]
Solution c: return integer_nthroot( n, 2 )[1]

Offset 1
Average time taken by a: 0.08400182247161865
Average time taken by b: 0.10072704315185547
Average time taken by c: 0.07971318721771241

Offset 2^100
Average time taken by a: 0.08720964431762696
Average time taken by b: 0.11071744918823243
Average time taken by c: 0.08440198898315429

Offset 2^10000
Average time taken by a: 0.4392880868911743
Average time taken by b: 0.9468696451187134
Average time taken by c: 0.53567138671875

Offset 2^1000000  (done with a smaller sample size)
Average time taken by a: 536.8559837341309
Average time taken by b: 12332.743930816651
Average time taken by c: 680.6759834289551

Of course very large n would probably benefit significantly from trailing(n) as "if 1 == trailing(n)%2: return False" and tests involving largeMod as posted earlier.


Here is the program I used for timing.

from sympy.ntheory import perfect_power
from sympy.core.power import integer_nthroot


def is_squareA( n, prep=True ):
  if prep:
    n = int(n)
    if n < 0:
      return False
    if n in [0, 1]:
      return True

  m = n & 127
  if not ((m*0x8bc40d7d) & (m*0xa1e2f5d1) & 0x14020a):
    m = n % 63
    if not ((m*0x3d491df7) & (m*0xc824a9f9) & 0x10f14008):
      if perfect_power(n, [2], factor=False):
        return True
  return False
  
  
def is_squareB( n, prep=True ):
  if prep:
    n = int(n)
    if n < 0:
      return False
    if n in [0, 1]:
      return True
    
  m = n & 127
  if not ((m*0x8bc40d7d) & (m*0xa1e2f5d1) & 0x14020a):
    m = n % 63
    if not ((m*0x3d491df7) & (m*0xc824a9f9) & 0x10f14008):
      pp = perfect_power(n, [2], big=False)
      return pp and 2 == pp[1]
  return False


def is_squareC( n, prep=True ):
  if prep:
    n = int(n)
    if n < 0:
      return False
    if n in [0, 1]:
      return True
    
  m = n & 127
  if not ((m*0x8bc40d7d) & (m*0xa1e2f5d1) & 0x14020a):
    m = n % 63
    if not ((m*0x3d491df7) & (m*0xc824a9f9) & 0x10f14008):
      return integer_nthroot( n, 2 )[1]
  return False

  
  
# import time module to calculate times 
import time 

# initialise lists to save the times 
aTime = [] 
bTime = [] 
cTime = [] 


offset = 1
#offset = pow( 2, 100 )
#offset = pow( 2, 10000 )
#offset = pow( 2, 1000000 )
trials = 100000

for n in range( trials ):
  a = is_squareA( offset + n )
  b = is_squareB( offset + n )
  c = is_squareC( offset + n )
  if a != b or a != c:
    print( "failed to be equal", (offset+n), a, b, c )

    
for k in range( 50 ): 

  start = time.time() 
  for n in range( trials ):
    is_squareA( offset + n )
  stop = time.time() 
  aTime.append(stop-start) 
  

  start = time.time() 
  for n in range( trials ):
    is_squareB( offset + n )
  stop = time.time() 
  bTime.append(stop-start)   

  
  start = time.time() 
  for n in range( trials ):
    is_squareC( offset + n )
  stop = time.time() 
  cTime.append(stop-start)   
  

print( "Offset", offset )
print( "Average time taken by a:", str(sum(aTime)/50)) 
print( "Average time taken by b:", str(sum(bTime)/50)) 
print( "Average time taken by c:", str(sum(cTime)/50))
