### ISSUE TITLE
improve documentation of permutations, et al.

### ISSUE THREAD

**Issue by smichr** [sympy/sympy#17062]
On the mailing list @asmeurer observed:

> The docstring of multiset_partitions describes how to count 
partitions. It mentions the nT function, but not where to get it. It's 
in `sympy.functions.combinatorial.numbers`. Also the docstring creates its own version of the Stirling numbers of the second kind, but there is a `stirling` function in the same 
module. So the documentation of `multiset_partitions` could be 
improved. Also, some of these functions should probably be included in 
the default namespace (`sympy/__init__.py`).

**Comment by Abhi58** [comment]
I want to work on this issue. Can you please explain a bit about what needs to be updated in docs?

**Comment by smichr** [comment]
* `nT` is already referenced in the See Also so nothing to do there
* use the `stirling` function instead of the S2 code in the `multiset_partitions` docstring (in utilities.iterables)

**Comment by Abhi58** [comment]
Thanks @smichr , so do we need:

```
>> from sympy.functions.combinatorial.numbers import stirling
>> stirling(5,2)
>> 15 
```
and remove the S2 code method from  https://docs.sympy.org/latest/modules/utilities/iterables.html ?

**Comment by Abhi58** [comment]
@smichr please have a look into the PR #17191
