### ISSUE TITLE
Simplify returns incorrect result with trig functions

### ISSUE THREAD

**Issue by moble** [sympy/sympy#17063]
[This sympy live calculation](https://live.sympy.org/?evaluate=alpha%2C%20beta%2C%20gamma%2C%20theta%20%3D%20symbols(%27alpha%20beta%20gamma%20theta%27)%0A%23--%0Aexpr%20%3D%20(-sin(beta%2F2)*sin(alpha%2F2%20-%20gamma%2F2)*sin(alpha%2F2%20%2B%20gamma%2F2)%2F(2*cos(beta%2F2)*cos(alpha%2F2%20%2B%20gamma%2F2)**2)%20%2B%20sin(beta%2F2)*cos(alpha%2F2%20-%20gamma%2F2)%2F(2*cos(beta%2F2)*cos(alpha%2F2%20%2B%20gamma%2F2)))%2F(sin(alpha%2F2%20%2B%20gamma%2F2)**2%2Fcos(alpha%2F2%20%2B%20gamma%2F2)**2%20%2B%201)%20%2B%20(sin(alpha%2F2%20-%20gamma%2F2)*sin(alpha%2F2%20%2B%20gamma%2F2)*cos(beta%2F2)%2F(2*sin(beta%2F2)*cos(alpha%2F2%20-%20gamma%2F2)**2)%20-%20cos(beta%2F2)*cos(alpha%2F2%20%2B%20gamma%2F2)%2F(2*sin(beta%2F2)*cos(alpha%2F2%20-%20gamma%2F2)))%2F(sin(alpha%2F2%20-%20gamma%2F2)**2%2Fcos(alpha%2F2%20-%20gamma%2F2)**2%20%2B%201)%0A%23--%0Aprint(mathematica_code(expr))%0A%23--%0A%23%20Using%20Mathematica%20to%20Simplify%20that%20output%20results%20in%20-Cos%5Balpha%5D*Cot%5Bbeta%5D%0A%23--%0A%23%20That%20is%20also%20the%20result%20that%20one%20can%20get%20using%20basic%20trig%20identities%0A%23--%0Aexpr%0A%23--%0Asimplify(expr)%0A%23--%0A%23%20That%20is%20the%20incorrect%20result%0A%23--%0A]) shows an incorrect result when applying `simplify` to a fairly large (but ultimately basic) expression involving lots of trig functions.  I get the same result on version 1.4 on my own computer, and was getting this result from 1.3 before I updated today.

---

**EDIT:** Note that Ethan reduced this to a much simpler expression below, so that's obviously a better MWE.

---

I'm sorry that I haven't been able to cut it down to smaller size and still get an error; I have tried.  The MWE is this:
```python
alpha, beta, gamma = symbols('alpha beta gamma')
expr = (-sin(beta/2)*sin(alpha/2 - gamma/2)*sin(alpha/2 + gamma/2)/(2*cos(beta/2)*cos(alpha/2 + gamma/2)**2) + sin(beta/2)*cos(alpha/2 - gamma/2)/(2*cos(beta/2)*cos(alpha/2 + gamma/2)))/(sin(alpha/2 + gamma/2)**2/cos(alpha/2 + gamma/2)**2 + 1) + (sin(alpha/2 - gamma/2)*sin(alpha/2 + gamma/2)*cos(beta/2)/(2*sin(beta/2)*cos(alpha/2 - gamma/2)**2) - cos(beta/2)*cos(alpha/2 + gamma/2)/(2*sin(beta/2)*cos(alpha/2 - gamma/2)))/(sin(alpha/2 - gamma/2)**2/cos(alpha/2 - gamma/2)**2 + 1)
simplify(expr)
```
The output is
```python
-2*cos(alpha)*cos(beta)/sin(2*beta)
```
[which could be further simplified to `-cos(alpha)*csc(beta)`].  It should be
```python
-cos(alpha)*cot(beta)
```
as verified by Mathematica (directly using the output of `print(mathematica_code(expr))`), and by direct calculation using trig identities.  This isn't just a matter of `simplify` refusing to do something that may not always be true; this is really the wrong result.

The expression looks big and ugly, but is actually pretty simple when you stare at it for a minute:
<img width="802" alt="Screen Shot 2019-06-20 at 2 11 30 PM" src="https://user-images.githubusercontent.com/1470769/59871428-91497080-9365-11e9-8f1b-b586d53bf7d3.png">

Those denominators can be simplified immediately to `1/cos**2` of the respective arguments.  Then you just cancel, group terms, and apply standard trig identities, and get the correct result.  Sympy will actually correctly simplify each fraction individually, but then it refuses to further simplify the sum — but at least that sum would be correct, unlike what it does with this whole expression.  (Of course, this happened in the middle of a much longer calculation, so I didn't know it was going wrong, and have spent the past few days wondering why I was getting inconsistent results when using this wrong answer.)

**Comment by ethankward** [comment]
I was able to reduce your problem expression `(cos(a - b) + cos(a + b))/(sin(b/2)*cos(b/2))`, which SymPy incorrectly simplifies to `8*cos(a)*cos(b)/sin(2*b)`.

**Comment by moble** [comment]
Thanks @ethankward!  That's true even though it correctly simplifies the numerator and denominator separately, and then correctly simplifies that ratio.  It gets the same wrong answer with the equivalent expression `(2*cos(a)*cos(b))/(sin(b/2)*cos(b/2))`, but actually gets the right answer with the inequivalent expression `(cos(a - b) + cos(a + b))/(sin(b)*cos(b))`.

**Comment by ethankward** [comment]
Specifically something goes wrong in `simplify.fu.TRmorrie`.

**Comment by smichr** [comment]
A smaller MWE:
``python
>>> TRmorrie(cos(b)/cos(b/2))
4*sin(b/2)*cos(b)/sin(2*b)
```

**Comment by moble** [comment]
Thanks @ethankward and @smichr.  That works for me.
