### ISSUE TITLE
Deprecate python 2 support in code printers and and python codegen

### ISSUE THREAD

**Issue by sylee957** [sympy/sympy#17082]
See #16901
Remove `standard='python2'` for `render_as_module` and `pycode` and `PythonCodePrinter`

**Comment by czgdp1807** [comment]
Should we keep this issue? https://github.com/sympy/sympy/pull/18381#issuecomment-589713427 suggest that we can still have Python2 code printers.

**Comment by sylee957** [comment]
I think that as the roadmap of #18381 is modified, the PR can just close this issue instead.
