### ISSUE TITLE
[Discussion] Latex printer for "digital logic"

### ISSUE THREAD

**Issue by oscargus** [sympy/sympy#17084]
I've been playing around with a special LaTeX printer for "digital logic" (it is simply boolean algebra, but the printing is, sometimes, different, when used in digital logic).

Instead of `Xor(z, x & (y | x & ~z))` printing as 
![image](https://user-images.githubusercontent.com/8114497/60033841-a4cc4280-96a9-11e9-8312-0b45893ee9cd.png)

it now prints as
![image](https://user-images.githubusercontent.com/8114497/60033857-ad247d80-96a9-11e9-977e-52b27ccb6e80.png)

or
![image](https://user-images.githubusercontent.com/8114497/60033852-aa298d00-96a9-11e9-90d0-bf90954f0e1d.png)

which is consistent with the standard within the area, see e.g https://fiverr-res.cloudinary.com/images/t_main1,q_auto,f_auto/gigs/114471177/original/9d851e05798f19d3e65eaced9bd8c3e399253d75/do-help-in-digital-logic-design-assignments-and-quizzes.jpeg

However, a simple Googling gives that `And` is sometimes represented using `&` or `.` (and `Or` is still represented using 
![image](https://user-images.githubusercontent.com/8114497/60033657-4a32e680-96a9-11e9-9d04-4c4ff09a8afe.png) ), see e.g. https://cs.lmu.edu/~ray/notes/digitallogic/ and https://maecellesther.wordpress.com/2017/10/02/it-1-boolean-algebra-and-digital-logic/

Now, the discussion points:

 - Is this of interest to SymPy?
 Personally I think so. The option is that I have a separate package for it. However, I would prefer to keep this within the SymPy project. It is not less useful to someone working in quantum physics than the quantum physics package is to me... The benefit of a separate package is that there are things that may be even more specialized later, like generating LaTeX for Karnaugh maps, and random boolean logic simplification assignments etc, which may be not be as easy to sell as a SymPy functionality.

If it is of interest to SymPy:

 - Should this be a separate printer?
  The alternative is to have (quite a few) options sent to the LaTeX printer. It affects bracketing of And and use of symbols.

- Should everything be configurable?
  Right now, the style for Not can be changed (as we tend to use prime is Sweden (Europe?), but most examples on the net use bar).

 - What should the defaults be?

 - Should it reside in logic or printing?

(We have changed to Python in the first year programming courses, so being able to point at SymPy in the first year digital design/switching theory courses should be really useful.)

**Comment by oscargus** [comment]
I've decided to create a separate package for this. More info once that is available...

**Comment by oscarbenjamin** [comment]
This all sounds like stuff that would be useful in SymPy. You probably know more than anyone else how it should be done though...

Another option is to start as a separate package and then propose for inclusion once it is stable. I'm not sure what is the best license to use in that scenario...
