### ISSUE TITLE
Printing of Laplace transform of undefined function

### ISSUE THREAD

**Issue by oscarbenjamin** [sympy/sympy#17098]
See also #7219 which is about applying Laplace transform rules for derivatives and integrals of unknown functions.

Currently the Laplace transform of an unknown function prints like:
```julia
In [2]: t, s = symbols('t, s')

In [3]: y = Function('y')

In [4]: laplace_transform(y(t), t, s)
Out[4]: LaplaceTransform(y(t), t, s)
```
I wonder if the LaplaceTransform of an undefined function should print like `Y(s)` as in
```python
>>> LaplaceTransform(y(t), t, s)
Y(s)
```
There are other notations like `L{y}(s)` that could also be used.

Then after adding the properties in #7219 you could have something like
```python
>>> laplace_transform(Integral(y(t), t), t, s) 
Y(s)/s
```

**Comment by sylee957** [comment]
I think that it prints in non-trivial way for LaTeX, as same as other integral transforms
<img src=https://user-images.githubusercontent.com/34944973/60123730-1d72f200-97c3-11e9-9b80-43b2d3cb511e.png width=256px>

About printing like `Y(s)`, there can be some questions like, what if the undefined function is already in a capital letter,
And also, the notation would not be self-contained if the variable and original function goes implicit. The latex notation currently being used, contains all the necessary information, however.

Though I see it can be possible to add an optional way of printing some symbols.

**Comment by hanspi42** [comment]
Doing this automatically will not work, but I am writing a helper function to facilitate it in #22376.

Example here: https://github.com/sympy/sympy/pull/22376#issuecomment-971505183

**Comment by hanspi42** [comment]
One such example is now also a test case:

https://github.com/sympy/sympy/blob/b5191b805eba30488a54cc0e46dbab66052a0429/sympy/utilities/tests/test_wester.py#L2936-L2957

**Comment by hanspi42** [comment]
This has now become the next step on #24561 ;)
