### ISSUE TITLE
missing trig values for pi/5 pi/8 pi/10 pi/12

### ISSUE THREAD

**Issue by gschintgen** [sympy/sympy#17106]
Hi, I noticed some inconsistencies in regard to the "special" trigonometry angles:

```
In [3]: atan(tan(pi/12))
Out[3]:
π
──
12

In [4]: atan(tan(5*pi/12))
Out[4]: atan(√3 + 2)
```
So, `tan(pi/12)` and `tan(5*pi/12)` are both automatically evaluated to their exact value, but for 5pi/12 the inverse function `atan` isn't aware of the exact angle. The same holds for other values, e.g.:
```
In [5]: acos(cos(pi/12))
Out[5]:
    ⎛√2   √6⎞
acos⎜── + ──⎟
    ⎝4    4 ⎠

In [6]: acos(cos(pi/5))
Out[6]:
    ⎛1   √5⎞
acos⎜─ + ──⎟
    ⎝4   4 ⎠
```
In another case, the return value is quite suboptimal:
```
In [18]: tan(pi/5)
Out[18]:
    ________
   ╱ 5   √5
  ╱  ─ - ──
╲╱   8   8
────────────
   1   √5
   ─ + ──
   4   4

In [19]: sqrt(radsimp(expand(_**2)))
Out[19]:
  __________
╲╱ 5 - 2⋅√5
```

I'd quite like to contribute some improvements:
- check that pi/2 pi/3 pi/4 pi/5 pi/6 pi/8 pi/10 pi/12 are all fully implemented in a consistent manner. (They all involve at most two radicals, sometimes nested, just like some values that are already implemented.)
- add test cases?

Would such a pull request be ok? I'm not a hugely experienced Python coder, but I do know my way around code and this should be fairly low hanging fruit.

**Comment by oscarbenjamin** [comment]
> Would such a pull request be ok?

Yes it would, thanks.

The code for evaluating these things seems to be here:
https://github.com/sympy/sympy/blob/c36eaa91c111d7052f49b58744beb2c8afae9182/sympy/functions/elementary/trigonometric.py#L578
https://github.com/sympy/sympy/blob/c36eaa91c111d7052f49b58744beb2c8afae9182/sympy/functions/elementary/trigonometric.py#L2310

**Comment by gschintgen** [comment]
Hi, my work on this is progressing well (there's indeed a number of inconsistencies), but now I could need some guidance:

The `cst_table` dictionaries in `asin`, `acos`, `atan`, `acot` have somewhat grown in size and are partially redundant (in a pairwise fashion asin/acos, atan/acot). So I'd like to factor out both tables and put them in the class `InverseTrigonometricFunction`. But having the dictionaries as simple data members of this base class fails miserably: isympy won't even start. To me it seems that as soon as isympy encounters a `sqrt` in this data member it tries to pull in other stuff, notably trigonometry related things that are not yet in place. (But I'm not quite sure about this interpretation of the trace that is shown.) The same happens if I try to make both dicts global variables in the module.

I can work around this issue using the following construct:
```
class InverseTrigonometricFunction(Function):
    """Base class for inverse trigonometric functions."""

    def _get_atan_table():
        return {
            sqrt(3)/3: S.Pi/6,
            -sqrt(3)/3: -S.Pi/6,
            [...]
            (2 + sqrt(3)): 5*S.Pi/12,
            -(2 + sqrt(3)): -5*S.Pi/12
        }
```

And then in `atan.eval` and `acot.eval` I retrieve this table using `cls._get_atan_table()`.

This is working fine, but I'd like to know if this is the right way to proceed? Or is there a more elegant/pythonic way to factor out such common data?

**Comment by oscarbenjamin** [comment]
I think that seems fine. It would be easier to comment on the approach if you send a pull request so we can see it in detail.

**Comment by gschintgen** [comment]
> I think that seems fine. It would be easier to comment on the approach if you send a pull request so we can see it in detail.

Thanks for your reply! I've submitted a PR. Any review would be very welcome.
