### ISSUE TITLE
[Discussion] For fixing lambert problem to return incomplete solution

### ISSUE THREAD

**Issue by jmig5776** [sympy/sympy#17127]
This issue discussion is to discuss about the plan to solve the problem for lambert for not returning all solutions. Please go through conversation in #16890 . 
ping @smichr @aktech @Yathartha22 @Shekharrajak

**Comment by smichr** [comment]
One of the challenges is to know when to return multiple solutions. For `log(x**2)-log(4)` there are 2 real solutions: +/-2. But for `2*log(x)-log(4)` there is a single real solution of 2.

The user may enter an expression in a variety of forms. Recognizes that those forms have one or more solutions in terms of lambert requires manipulation to identify a few patterns or else many patterns. Knowing which of the solutions to return (like the sample problem above) requires keeping track of the expression of interest, i.e. the expression entered by the user.

**Comment by jmig5776** [comment]
Yeah, I agree with you @smichr that user can enter an expression in many forms and it might be tough and complex problem to solve for us. I searched for something to how to deal with equations with logarithms, and I got this amazing [link](https://www.maplesoft.com/support/help/Maple/view.aspx?path=MathApps%2FSolvingLogarithmicEquations), which I think explains the cautions and steps that we should be aware while solving equations involving logarithms.

**Comment by jmig5776** [comment]
@smichr I think we should design the Lambert solver such that we should not need to convert equations to log form. Pardon me if it is not a useful suggestion

**Comment by jmig5776** [comment]
An [issue](https://math.stackexchange.com/questions/1404137/using-lamberts-w-function-to-solve-this-equation) at stackexchange which helps to understand our problem.

**Comment by smichr** [comment]
#16890 was committed.
