### ISSUE TITLE
Matrices should not use is_zero for a zero matrix

### ISSUE THREAD

**Issue by oscarbenjamin** [sympy/sympy#17131]
Integrating a zero matrix returns the scalar zero. I think this is because matrices define is_zero as True for a zero matrix:
```julia
In [1]: M = Matrix([[0, 0]])                                                                                                      

In [2]: M                                                                                                                         
Out[2]: [0  0]

In [3]: integrate(M, t)                                                                                                           
Out[3]: 0

In [4]: M.is_zero                                                                                                                 
Out[4]: True
```
I think the error here is in Matrix.is_zero (which should always be False) rather than integrate. In the assumptions system is_zero means the scalar zero so is_zero can never be True for a matrix.

**Comment by smichr** [comment]
I had to work around this in simplify -- it *does* seem like it should only refer to scalars.

**Comment by oscarbenjamin** [comment]
I think that this attribute should be renamed `is_zero_matrix` and matrices should have `is_zero = False`.

I can see the advantage of querying properties like this on matrix elements though. Maybe matrices could have attributes `any` and `all` as proxy objects to compute queries over the elements e.g.:
```
if M.all.is_zero:
    #  All elements are zero
```
Then `M.all.is_x` can be equivalent to `fuzzy_and(e.is_x for e in M)` and `M.any` likewise for `fuzzy_or`.

If matrices were immutable and the proxy objects were Expr then the normal assumptions machinery could be used for inferences around positive, nonnegative, complex etc.

**Comment by sylee957** [comment]
There is `is_ZeroMatrix` used in matrix expressions though.

So we would either have to decide
1. Deprecate both `is_zero` and `is_ZeroMatrix` and use `is_zero_matrix` instead, and use `isinstance` for the context it should strictly match the class?

2. Update `is_ZeroMatrix`?

**Comment by oscarbenjamin** [comment]
I might be wrong but it seems to me that deprecation is unnecessary in this case. I don't think many users will be using it. I would say let's just rename the is_zero attribute for matrices. The is_ZeroMatrix uses capitals so I would assume that it means `isinstance(obj, ZeroMatrix)`. If it doesn't mean that then we should change the spelling.

**Comment by sylee957** [comment]
I may open up a new PR to pull out only the `is_zero` change from #18255
