### ISSUE TITLE
numerical instability when solving n=385 linear equations with Float coefficients

### ISSUE THREAD

**Issue by simbr80** [sympy/sympy#17136]
I use Sympy solve() function to solve a large number of equations. All variables in the equations are defined as symbols. Variables can start with the letter P or F. I use solve() to express one specific P variable (the one that I observe) with only F variables, so I use solve() to substitute all other P variables with F variables. The sum of the coefficients before the F variables is ideally 1 or almost 1 (e.g.: 0.99).

This produces good results till a certain point where the number of equations becomes pretty big and also their length. There the Sympy solve() function starts to give me wrong results. The sum of the coefficients becomes negative (e.g. -7,...). It looks like that the solve() function gets problems with substituting and carrying over all variables and their coefficients.

Is there a way to correct this problem?

Dictionary of equations under link:
(https://drive.google.com/open?id=1VBQucrDU-o1diCd6i4rR3MlRh95qycmK)

     import json
     from sympy import Symbol, Add, Eq, solve

    # Get data

    # data from link above
    with open("C:\\\\Test\\dict.json") as f:
        equations = json.load(f)

    comp =[]
    expressions = []

    for p, equation_components in equations.items():
        p = Symbol(p)
        comp.append(p)
        expression = []
        for name, multiplier in equation_components.items():
            if type(multiplier) == float or type(multiplier) == int: 
                expression.append(Symbol(name) * multiplier)
            else:
                expression.append(Symbol(name) * Symbol(multiplier))
        expressions.append(Eq(p, Add(*expression)))

    # Solution for variable P137807

    print("Solving...")

    # Works for slice :364 !!!!!
    solutions = solve(expressions[:364], comp[:364], simplify=False, rational=False)

    # Gives wrong results for slice :366 and above !!!!!
    # solutions = solve(expressions[:366], comp[:366], simplify=False, rational=False)

    vm_symbol = Symbol("P137807")

    solution_1 = solutions[vm_symbol]

    print("\n")
    print("Solution_1:")
    print(solution_1)
    print("\n")

    #Sum of coefficients

    list_sum = []

    for i in solution_1.args:
        if str(i.args[1]) != "ANaN":
            list_sum.append(i.args[0])
    coeff_sum = sum(list_sum)

    print("Sum:")
    print(coeff_sum)

**Comment by smichr** [comment]
Without solving the whole system, how do you know that the coefficient is correct? When I solve the system I get
```python
# s is the solution dictionary
>>> eq=s[Symbol('P137807')]
>>> for i in eq.args:
...   a,b=i.as_coeff_Mul()
...   if not b.is_Symbol:assert b.has(Symbol('ANaN'))
>>>
>>> len(eq.args)
2348
>>> ind,dep=eq.as_independent(Symbol('ANaN'))
>>> len(dep.args)
139
>>> sum([i.as_coeff_Mul()[0] for i in ind.args])
142.87872201275660
>>> sum([i.as_coeff_Mul()[0] for i in dep.args])
0.072048677877450838
```

**Comment by simbr80** [comment]
I don't know if the coefficient (sum) is correct without solving the whole system. But I know that if the data is perfect, the coefficient (sum) of the system should always be 1. If the data is not perfect, the coefficient (sum) is <1 but still should be near 1. This assumption is based on the fact that every equation in _expressions_ is drawn up in a way that the sum of the coefficients on the right side, if the data is perfect, always gives 1. Furthermore, the right sides of all equations are always only additions (e.g. Pn = 0.3*F1+0.3*F2+0.4F3), never subtractions.  

So it follows from the above that at every step taken while solving the system the sum of the coefficients should be 1 or near 1, since we in fact are only substituting the variables on the right side (Ps with Fs). If it is negative then there must be an error.

When I run the above code with :364 equations in _expressions_ the result gives a sum of the coefficients near 1 (0.982667073501027) and the result in represented with additions only. When I run the code with _:365_ the sum of the coefficient starts to drop (0.653917057086150) and the result has some elements that are subtracted while already missing all elements from the last (365th) equation (F2261-F2267 and P120795, P159326, P176478, P290218, P291837, P309088, P327358, P347929). This pattern goes on when I run :366 or more equations. The sum of the coefficient turns into negative, the result has elements that are subtracted and there are elements missing...

So can you please tell me how you managed to solve the whole system (your solution dictionary?!) without the above mentioned errors. Your _len(q.args)_ looks almost correct since there are 2374 Fs, the last one F2374. Also your sum of the coeff. (_sum([i.as_coeff_Mul()[0] for i in ind.args])_) looks correct.

When I solve the whole system I get _len(q.args)_ 2364 (missing some F variables) and a sum of the coeff. of -8.08382122789392.

**Comment by smichr** [comment]
I did it manually with the following code which is pretty ugly in the current state. The system takes unbearably long on my older computer. We need a better solver for sparse linear systems. @oscarbenjamin has already identified some improvements in #16861:

```python
s = {}
reps = {}
v = set()
for (i, e) in enumerate(expressions):
    v.add(e.lhs)  # all P variables are on the left (though may be on the right, too
    (ind, dep) = e.rewrite(Add).as_independent(e.lhs, as_Add=1)
    reps[e.lhs] = -ind / dep.as_coeff_Mul()[0]

while 1:
    do = 1
    done = True
    while do:
        do = 0
        r = {}  # current definitions, Eq(x, expr indep of x)
        for k in reps:
            if not reps[k].free_symbols & set(v):
                r[k] = reps[k]
                do += 1
        print(do, 'defined')
        if do:
            done = False
        for k in r:
            ok = reps.pop(k)
            v.remove(k)
        for k in reps:
            reps[k] = reps[k].xreplace(r)
        s.update(r)
        if not r:
            done = True
            break
    if done:
        break
    eqs = [k - reps[k] for k in reps]
    eqs = sorted(eqs, key=lambda i: len(i.free_symbols & v))
    reps = {}
    for i in range(len(eqs)):
        x = list(eqs[i].free_symbols & v)[0]
        (ind, dep) = eqs[i].as_independent(x, as_Add=1)
        xis = -ind / dep.as_coeff_Mul()[0]
        for j in range(i + 1, len(eqs)):
            eqs[j] = eqs[j].xreplace({x: xis})
        reps[x] = xis

got={}
v=set(v)
eqs = [k - reps[k] for k in reps]
while 1:
    todo = len(v)
    eqs = sorted(eqs, key=lambda i: len(i.free_symbols & v))
    done=[]
    was = eqs[:]
    for i in range(len(eqs)):
        x = list(eqs[i].free_symbols & v)
        if len(x) == 1:
            done.append(i)
        x = x[0]
        (ind, dep) = eqs[i].as_independent(x, as_Add=1)
        xis = -ind / dep.as_coeff_Mul()[0]
        if done and done[-1]==i:
            got[x]=xis
            v.remove(x)
            for j in range(i):
                eqs[j] = eqs[j].xreplace({x: xis})
        for j in range(i + 1, len(eqs)):
            eqs[j] = eqs[j].xreplace({x: xis})
        print(i,'/',todo)
    for i in reversed(done):
        ok = eqs.pop(i)
    if was == eqs:
        break

sol = s
sol.update(got)
assert len(eqs) == 0
print(len(sol)) # -> 385
```

**Comment by simbr80** [comment]
In the mean time do you have any suggestions what library or other programing language I could use to solve this kind of equations with these many symbolic variables?

Do you have any idea why solve() breaks, since for me it looks kind of arbitrary. When I use it, it works in 99% of the time, but for the rest 1% I can't figure why it breaks.

**Comment by smichr** [comment]
You could try `sympy.solvers.solveset.linsolve`. I would be interested to know the results.

**Comment by smichr** [comment]
I suspect what you are seeing is a result of losing precision in your result. One way to work around this is the use `nsimplify(expressions, rational=True)` as your equations. Then evaluate to float after you get your true solution.

The Hilbert matrix is a classically ill-behaved matrix wrt numerical stability. Using a naive solver compare
```
n = 30
v = var('n:%s' % n)
b = var('b:%s' % n)
hrat = = lambda n: Matrix(n,n,lambda i,j: S(1)/(i+j+1))
req = list(hrat(n)*Matrix(v)-Matrix(b))
rat = naive_solve(req, dict=True)
req[0].xreplace(rat)
0 <-- the answer exactly satisfies the initial RATIONAL form of the Hilbert matrix

hfloat = lambda n: Matrix(n,n,lambda i,j: 1.0/(i+j+1))
feq = hfloat(n)*Matrix(v)-Matrix(b)
flo = naive_solve(feq, dict=True)
feq[0].xreplace(flo)
6.11180439591408e-10*y0 + 1.8291175365448e-6*y1 - 1.6666259765625*y10
+ 3.75*y11 + 5.25*y12 - 0.0625*y13 + 0.6458740234375*y14 +
0.6666259765625*y15 + 0.333251953125*y16 + 2.58349609375*y17 -
3.25*y18 + 1.98957824707031*y19 + 1.26957893371582e-5*y2 - 2.65625*y20
- 0.333343505859375*y21 + 0.5833740234375*y22 - 0.3333740234375*y23 -
3.2603759765625*y24 + 3.91650390625*y25 - 3.0*y26 -
0.6822509765625*y27 - 3.791748046875*y28 + 0.25*y29 -
0.000244140625*y3 - 0.00032806396484375*y4 + 0.091156005859375*y5 -
0.348968505859375*y6 - 0.25*y7 - 2.79166412353516*y8 -
0.177093505859375*y9  <-- non-cancellation is the result of accumulated errors
```

**Comment by simbr80** [comment]
As you suggested I converted the floats to rationals with nsimplify().

I tried to use linsolve() but the problem is that it takes forever, even with only two equations (:2) to solve. I suspect it has something to do with the build-in simplify function, which  I can't set to false.

I also tried it with solve (), with simplify=False (`solve(expressions_rat[:190], comp[:190], simplify=False)`), but after around :190 equations the function look like it hangs. So I am not sure if there are any other arguments I could pass to solve() to make it work with rationals.

**Comment by smichr** [comment]
I am testing a different solver which I will post here.

**Comment by smichr** [comment]
If `ssolve` hangs, try replacing each Float with a higher precision Float, e.g. `[i.replace(lambda x:x.is_Float, lambda x:x.n(30)) for i in expressions]`, and compare the two solutions.

**Comment by smichr** [comment]
Here is a demonstration of the ill-behaving Hilbert matrix where the exact result is substituted into a floating form of the Hilbert system
```
def do(n):
    v=var('x:%s'%n**2)
    b=eye(n)
    hfloat = lambda n: Matrix(n,n,lambda i,j: 1.0/(i+j+1))
    H = hfloat(n)
    feq = list(H*Matrix(n,n,v)-Matrix(b))
    feq = [nsimplify(i,rational=True) for i in feq]
    s = ssolve(feq,v)
    I = Matrix(n,n,[s[i] for i in v])
    print((H*I).n(2))

>>> do(3)
Matrix([[1.0, 0, 0], [0, 1.0, 0], [0, 0, 1.0]])
>>> do(10)
Matrix([[1.0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 1.0, 0, 0, 0, 0, 0, 0, 0, 0],[-1.5e-10, 0, 1.0, 0, 0, 0, 0, 0, 0, 4.8e-6], [0, 0, 0, 1.0, 0, 0, 0, 0, 0,0], [-2.9e-11, -2.8e-9, 3.0e-8, 0, 1.0, 0, 0, 1.5e-5, 3.8e-6, -2.4e-6], [-2.2e-11, 7.5e-9, 0, 0, 0, 1.0, 0, 0, -7.6e-6, 2.4e-6], [0, 0, 1.2e-7, 0, 0, 0, 1.0, 0, 0, -1.9e-6], [0, 0, 0, 0, 0, 0, 0, 1.0, 0, 0], [1.5e-11, 0, 0, -7.2e-7, 0, 0, 1.1e-5, 0, 1.0, 4.8e-7], [0, 0, 0, 0, 0, 0, 0, 0, 0, 1.0]])
>>> do(20)
Matrix([[1.0, 0, 2.9e+2, -1.1e+4, 1.7e+5, 4.1e+5, 3.2e+7, -5.0e+7, 7.8e+8, -2.4e+9, 5.2e+9, 3.4e+9, 1.3e+10, 4.5e+10, 8.4e+10, -3.7e+10, 4.7e+9, -6.2e+9, 1.1e+9, 5.0e+7], [0, 1.0, -4.0, 3.2e+3, 9.3e+4, 4.5e+5, -1.1e+7, 9.4e+7, -4.6e+7, 1.7e+7, 1.7e+9, 1.9e+10, 7.1e+9, 5.2e+10, 3.8e+10, 4.1e+10, -2.0e+10, 4.5e+8, -7.7e+8, 1.3e+8], [0, 0, 1.8e+2, -7.0e+3, 1.1e+5, -2.4e+5, -6.4e+6, 1.6e+8, 6.1e+8, -2.5e+9, -5.1e+9, 1.9e+10, 1.9e+10, 5.7e+10, 2.1e+10, -1.0e+10, 3.6e+9, -2.3e+9, -1.8e+8, 1.2e+8], [0, 0, 1.6e+2, -3.2e+3, -2.7e+4, 2.2e+6, -9.8e+4, 3.5e+7, -1.7e+7, 1.3e+9, 3.0e+8, 1.2e+10, 6.0e+9, 4.7e+10, 6.1e+10, 2.1e+9, -8.0e+9, 3.3e+9, -1.9e+9, 0], [0, 0, -50., 5.6e+3, 3.8e+4, 1.1e+6, 5.2e+6, 1.1e+8, 4.9e+8, 1.4e+9, -2.0e+9, 1.5e+10, 8.9e+9, 3.9e+10, 5.2e+10, 2.7e+10, -7.5e+9, -2.2e+9, -1.5e+9, 1.0e+8], [0, 0, 2.0e+2, -2.7e+3, 1.8e+5, 1.0e+6, 1.8e+7, -6.2e+7, 7.3e+8, -3.5e+9, 1.2e+8, 5.9e+9, 2.0e+10, -7.4e+9, 8.8e+10, -1.9e+10, 1.3e+9, -4.6e+9, 1.2e+8, -1.6e+7], [0, 0, -1.2e+2, 2.4e+3, 8.3e+4, 3.2e+6, -3.3e+7, 1.9e+8, -3.2e+8, -3.6e+8, -2.9e+9, 1.7e+10, -2.6e+10, 7.1e+10, -3.0e+9, 3.4e+10, -1.3e+10, 4.9e+9, -1.7e+9, 1.8e+8], [-0.00099, -0.27, 1.8e+2, -8.1e+3, 6.7e+4, -4.3e+5, -9.7e+6, -4.6e+7, 7.3e+8, -2.6e+9, 6.0e+9, -4.7e+9, 3.2e+10, 2.1e+10, 4.3e+10, -3.1e+10, 2.6e+9, -5.9e+9, 1.0e+9, -3.8e+7], [-0.0013, 0.31, 60., 7.5e+2, 7.9e+4, 9.3e+5, 8.5e+5,1.7e+7, -3.6e+8, -1.1e+9, -7.0e+9, 1.7e+10, -9.7e+9, 3.3e+10, -2.2e+10, -9.5e+9, -1.3e+10, 8.1e+8, -2.3e+8, 1.6e+8], [0, 0, 1.4e+2, -1.1e+3, 2.2e+5, 1.7e+5, -1.1e+6, 6.3e+7, -1.8e+8, -1.2e+9, 1.1e+9, 9.7e+9, 6.4e+9, 2.1e+10, 4.8e+10, -3.2e+9, -7.1e+9, -1.4e+8, 1.9e+8, -4.7e+7], [-0.0020, 0.50, 72., 6.2e+2, 2.9e+4, 1.3e+6, 1.0e+7, 1.0e+8, 1.9e+8, 4.2e+8, -5.4e+9, 6.9e+9, 2.9e+9, 2.7e+10, 2.9e+10, 2.3e+10, -4.4e+8, -4.3e+8, -9.2e+7, 1.7e+8], [0.0020, 0,64., -3.7e+3, 1.2e+5, 1.2e+6, 1.9e+7, 2.5e+7, 1.1e+8, -2.0e+9, -1.7e+9, -1.1e+10, 1.7e+10, 4.7e+10, 4.5e+10, -2.0e+10, -4.7e+9, -2.0e+9, 1.1e+8, 1.1e+7], [0, 0.50, 55., -5.7e+2, 1.5e+4, 1.8e+6, 1.8e+6, 2.0e+7, 7.9e+7, -2.9e+8, -4.5e+9, 8.9e+9, 1.0e+10, 3.7e+10, 2.8e+10, 5.0e+9, -9.5e+9, -4.1e+8, -7.0e+8, 5.7e+7], [-0.0020, -0.25, 44., 1.1e+3, 8.4e+4, -2.1e+5, 9.7e+6, 7.9e+6, 3.2e+8, -5.6e+8, -3.5e+9, -2.6e+9, 1.7e+10, 2.3e+10, 2.9e+10, -9.7e+9, 3.7e+9, -3.7e+8, 8.0e+7, 5.0e+7], [-0.0010, 0.088, 68., -1.1e+2, 2.2e+4, 1.1e+6, 1.5e+7, -1.7e+7, 9.4e+6, -1.1e+9, -9.2e+7, 5.4e+9, -1.8e+10, 3.5e+10, 4.6e+9,-4.7e+9, -5.0e+9, 7.8e+8, 2.2e+8, 9.6e+7], [0.00043, 0.22, 1.1e+2, 1.2e+3, 1.5e+4, 8.6e+5, 5.6e+6, 6.2e+7, 1.0e+8, -1.2e+9, 2.6e+9, 5.9e+9, -6.7e+9, 3.6e+10, 2.1e+10, 2.2e+9, -4.1e+9, -2.5e+9, -8.8e+7, 4.2e+7], [0, 0.13, 12., 2.0e+3, 2.3e+4, 5.5e+5, 8.3e+6, -7.3e+6, 1.5e+8, -1.6e+9, -5.7e+9, 3.7e+9, 8.4e+9, 1.2e+10, 2.3e+10, 1.3e+10, -8.3e+9, 3.8e+8, -4.2e+8, 7.9e+7], [-0.00037, 0, 16., -6.1e+2, 2.8e+3, 7.7e+5, -7.4e+6, 8.7e+6, 1.4e+8, -1.6e+9, 1.6e+9, 1.9e+9, 7.7e+9, 2.5e+10, 1.3e+10, 1.7e+9, -6.6e+9, 6.5e+8, -5.9e+8, 3.0e+7], [0.00011, 0, 42., -2.4e+3, 1.2e+4, 8.3e+5, -6.5e+6, 3.8e+7, 2.6e+7, -4.8e+8, 1.4e+9, 1.9e+9, 2.3e+8, 3.9e+10, 2.6e+10, -1.5e+10, -3.3e+9, 5.0e+7, -1.5e+8, 2.9e+7], [0, 0, 56., -1.4e+3, 8.1e+4, 6.1e+4, -1.0e+7, 1.4e+8, 1.6e+8,1.3e+8, -5.2e+8, 1.2e+10, 1.4e+10, 3.3e+10, 7.7e+9, -2.4e+9, -1.0e+10, -3.1e+8, -7.5e+7, 7.5e+7]])
```
So the exact solution (using equations with Rational) does not check with the original equations containing Floats. If the following is used, the identity matrix results in all 3 cases:
```python
def do(n):
    v=var('x:%s'%n**2)
    b=eye(n)
    H = Matrix(n,n,lambda i,j: S(1)/(i+j+1))
    feq = list(H*Matrix(n,n,v)-Matrix(b))
    s = ssolve(feq,v)
    I = Matrix(n,n,[s[i] for i in v])
    print((H*I).n(2))
```

**Comment by smichr** [comment]
Just checking...in your expressions something like "P137807": {"P137807": 2, "F123": 3} in the big dictionary that is in the json file gets converted to `Eq(P137807, 2*P137807 + 3*F123)` which is equivalent to `P137807 + 3*F123 = 0`. Is that what you intended? Or did you just key each equation to one of the variables -- whether it contained that variable or not -- and intend that the above should represent equation `2*P137807 + 3*F123 = 0`?

**Comment by simbr80** [comment]
The big dictionary is an actual sample of real data I am trying to process. All equations are the result of a recursion process. The processed data can be in form of a graph (and not necessarily a tree). The variable on the lfs (parent nodes) may or may not be also represented on the rhs. Ether way, the goal is to represent the 1st P variable from the 1st equation on the lhs with only F variables (finite children in the graph) . Therefore I need to solve the  whole system of linear equations. The sum of the coefficients on the rhs should be ideally always 1, but since certain data may be missing, the result may be less than 1. This is the case in the example from the json file, but still till the :364 equation the sum is, as stated above, 0.982667073501027.

**Comment by simbr80** [comment]
I would like to try out your code, but i experience a problem importing `from sympy.solvers.solveset import linear_coeffs`....?!

**Comment by smichr** [comment]
You probably need to download the latest version of SymPy...or go to "Code" on this page (top left) and navigate there and copy the routine and paste it into a script locally.

**Comment by smichr** [comment]
Results with Rational coefficients look great. Takes about 12 min online at repl.it:
```python
sol = ssolve(eq,v)
print(len(sol))
for j,k in enumerate(list(ordered(sol))):
    if j%10==0:
        print(k,sol[k].replace(lambda i:i.is_Symbol and i.name.startswith('F'),lambda i:S.One).n(2))
P114820 1.0
P117249 3.3e-6*ANaN + 0.85
P120333 1.0
P121246 1.0
P123817 2.8e-6*ANaN + 0.84
P124556 2.8e-6*ANaN + 0.84
P127675 1.0
P130283 1.0
P131322 1.0
P132886 1.0
P136020 1.1e-6*ANaN + 0.98
P143420 1.0
P147712 1.0
P157851 1.0
P162613 1.0
P170346 1.0
P179654 1.0
P186667 0.97
P190220 1.0
P191831 1.0
P193003 1.0
P203142 1.0
P223436 1.0
P232637 1.0
P253172 4.4e-7*ANaN + 0.98
P268583 1.0
P279493 1.0
P292620 1.0
P315169 1.0
P330241 1.0e-6*ANaN + 1.0
P351739 1.0
P367157 1.0
P382661 1.0
P413800 1.0
P448320 1.0
P480523 1.0
P527699 1.0
P594614 1.0
P686393 1.0
```

**Comment by simbr80** [comment]
I tried to run the code but I encountered the following error: `NameError: name 'ordered' is not defined`...

**Comment by smichr** [comment]
> I encountered the following error

put `from sympy import *` at the top of the script

**Comment by simbr80** [comment]
The results really look promising. I ran it on my computer and the whole process (conversion to rational + solving) took 166 seconds, even faster then only solve() with the wrong answer, which took 175 s.

**Comment by oscarbenjamin** [comment]
I tried the original code from the OP but solving for the full system with
```
solutions = solve(expressions, comp, simplify=False, rational=False)
```
and on master it takes 4m31s and gives a sum of 1.96128998110663

With #16550 it takes 2m27s and I get a sum of 0.982667072863146.

I don't what's actually correct here but some speed up possibly occurs from #16550...
