### ISSUE TITLE
Subs() gives incorrect result

### ISSUE THREAD

**Issue by GDelimpa** [sympy/sympy#17135]
In this case subs() gives incorrect results:
`x0, x1 = sympy.symbols('x0 x1')`
`psi = x0-x1`
`dic = {}`
`dic[x0] = 0.5*x1`
`dic[x1] = 0.5*x1`
`psi.subs(dic)`
`Out[192]: -0.25*x1`
Obviously, it should return 0. How can this be?

Edit: apparently it does not handle well the substitution of x0:
`yo=x0`
`yo.subs(dic)`
`Out[197]: 0.25*x1`

**Comment by jksuom** [comment]
It looks like dic defines two substitutions, one for x0 and another for x1: `yo = x0 -> 0.5*x1 -> 0.5*0.5*x1`. If the keyword `simultaneous=True`, the substitution of x0 will be delayed.

**Comment by GDelimpa** [comment]
Thank you!

**Comment by oscarbenjamin** [comment]
Can this be closed then?
