### ISSUE TITLE
Adapting to Tensorflow 2.0 API

### ISSUE THREAD

**Issue by czgdp1807** [sympy/sympy#17149]
#### What is the problem?
Tensorflow has made several changes to its API while migrating from 1.x to 2.x. The `Session` approach is discarded and `Function` approach is going to be used. Technically, they are going to make eager mode default for Tensorflow 2.0.
So, we will have to make changes to some of the sympy codebase so that it is ready before, tf 2.x release.

#### Other comments/references
Refer, [this proposal](https://github.com/tensorflow/community/blob/b1d83bf2ee3fc72650140b89656e29932db36226/rfcs/20180918-functions-not-sessions-20.md) for knowing the changes. [This migration guide](https://www.tensorflow.org/beta/guide/migration_guide) will also be helpful. Read the thread at https://github.com/sympy/sympy/pull/17103.
ping @asmeurer

**Comment by czgdp1807** [comment]
I am working on this. I don't know upto which depth tensorflow is used in sympy. First I will study about it and then I will start a PR. https://github.com/sympy/sympy/pull/17103 just removes the deprecation warnings.

**Comment by oscarbenjamin** [comment]
@czgdp1807 is this fixed by #17103 now?
