### ISSUE TITLE
imaginary result for Abs()

### ISSUE THREAD

**Issue by gschintgen** [sympy/sympy#17152]
The following gives an imaginary value for Abs():

```
>>> Abs(log(-1)-log(-1+0.000000000001*I)).n()
2.93883150098839e-8⋅ⅈ
>>> Abs(log(-1)-log(-1+0.000000000001*I))
   _____________________________________________
  ╱                                           2
╲╱  -6.28318530717759⋅π + 9.86960440108307 + π
```

**Comment by smichr** [comment]
Evaluation with Floats will be subject to such limitations. It needs more precision for the small value in order to compute the actual result.

Try
```python
>>> abs(nsimplify(eq,rational=True)).n()
1.00323846264338e-12
>>> abs(log(-1)-log(-1+x*I)).n(subs={x:0.000000000001})
1.00000000000000e-12
```

**Comment by gschintgen** [comment]
Thanks for the quick reply. I think what's been bothering me about the result is not so much the various numerical effects that can happen with floats (cancellation and such), but rather the unexpected order of computation.

Indeed, if I compute this modulus naively step by step, I find a real-valued (but inaccurate) result:
```
>>> log(-1)-log(-1+0.000000000001*I)
-5.0e-25 - 3.14159265358879⋅ⅈ + ⅈ⋅π
>>> (log(-1)-log(-1+0.000000000001*I)).n()
-5.0e-25 + 1.00021136526226e-12⋅ⅈ
>>> Abs(_)
1.00021136526226e-12
```
Even if float issues led to completely bogus values for `re+im*I`, it'd be quite unexpected to have a negative value for `re**2+im**2` (leading to the imaginary sqrt result).

I think what is ultimately causing the unexpected result is that the automatic evaluation of the first logarithm-of-a-float is done **symbolically**, keeping the symbol `pi` around, and not completely numerically:
```
>>> log(-1.0)
ⅈ⋅π
>>> _.n()
3.14159265358979⋅ⅈ
```
But for a CAS that's arguably the right thing to do, given that the imaginary part is exactly zero and at this step of the evaluation of the original Abs-expression a completely numeric result is *not* explicitly asked for.

Since there's no actual bug to point to, I'll close this. Sorry for the noise.
