### ISSUE TITLE
[Feature request]: add new code printer for maple

### ISSUE THREAD

**Issue by stevenleeS0ht** [sympy/sympy#17161]
[User manual](https://maplesoft.com/documentation_center/maple2019/UserManual.pdf)
[Programming Guide](https://maplesoft.com/documentation_center/maple2019/ProgrammingGuide.pdf)

**Comment by oscarbenjamin** [comment]
This seems like a fine feature request. It just needs someone with the motivation to put the time in.

Would you be interested in working on this?

**Comment by stevenleeS0ht** [comment]
Not a bad idea, but I need to get more familiar with the architecture of sympy at first.

**Comment by stevenleeS0ht** [comment]
@oscarbenjamin , Do you want me submit my commits in single time, or continuously submit commit as development flow?

**Comment by stevenleeS0ht** [comment]
I have create a pull request #17266 , please have a look.

**Comment by oscargus** [comment]
I think that once you have basic functionality (which looks like it may be quite soon), we can merge it and then you can add features along the way. In the best of worlds, people start to use it and provides feedback. Although the main feedback increase probably comes at the next release of SymPy, not sure how many runs it from master...

**Comment by voffch** [comment]
Maybe I'm missing something because I don't really know anything about the github workflow, but shouldn't this issue be closed by now? After all, the maple code printer is already there, it works, and the relevant pull request was merged a long time ago.

**Comment by oscarbenjamin** [comment]
Yes, this can be closed. Thanks all.
