### ISSUE TITLE
MatPow inconsistency

### ISSUE THREAD

**Issue by Pristine-Cat** [sympy/sympy#17175]
Matrix([[1,0],[0,1]])**x 
!= 
MatPow (Matrix([[1,0],[0,1]]), x).doit ()

Same with matrices other than identity.

**Comment by Pristine-Cat** [comment]
Discovered that sympy.matrices.common.__pow__() and sympy.matrices.expressions.matpow.doit() are two separate implementations of raising a matrix to a power. __pow__ was making use of _matrix_pow_by_jordan_blocks() whereas matpow.doit() was not. Added it in and it fixes the inconsistency but breaks one single instance of a test which I think was being masked by the fact that matpow did not actually raise the matrix to a power in that case. Is there any intentional reason why matpow would not make use of _matrix_pow_by_jordan_blocks()?

**Comment by jksuom** [comment]
>  Is there any intentional reason why matpow would not make use of _matrix_pow_by_jordan_blocks()?

The construction of Jordan blocks is based on the assumption that matrix entries belong to an algebraically closed field (i.e., currently only complex numbers) where roots of characteristic polynomials can be found. `matpow` is expected to deal with symbolic expressions for which there is very little support for polynomial equations.
