### ISSUE TITLE
[Discussion][GSoC] Random Walks

### ISSUE THREAD

**Issue by ritesh99rakesh** [sympy/sympy#17197]
**Random walks**:
References:
[1] https://en.wikipedia.org/wiki/Random_walk
[2] http://www.mit.edu/~kardar/teaching/projects/chemotaxis%28AndreaSchmidt%29/random.htm
[3] http://mathworld.wolfram.com/RandomWalk1-Dimensional.html
Textbooks
[1] "Principles of Random Walk" by Frank Spitzer
[2] Random walk: A modern introduction

The aim would be to implement random walks in one, two and three dimensions since these are the ones that are most often used. I plan to implement them in the cartesian space pertaining to the dimension of the walk.

 I also plan to implement Gaussian Random walk, reference:  (http://physics.gu.se/~frtbm/joomla/media/mydocs/LennartSjogren/kap2.pdf).

This issue is raised for the following purposes(in the order as they are mentioned):

    - Discussion of API for Random Matrices.

    - Discussion of the class structure for Random Matrices and its associated features.

We will first dicuss API and after completion we will move to the discussion of class structure, if needed.

Ping @Upabjojr @sidhantnagpal

**Comment by ritesh99rakesh** [comment]
Each random walk will be implemented as a separate class. I plan to do so because there are many results like the probability of reach a certain coordinate, which have a direct result in a one-dimensional walk but not in a multidimensional walk. I also plan to implement functions that would compute the properties of a given random walk.

   A functioning but quite naive prototype of a random walk in one dimension is given below.
   ```python
   class RandomWalk_1D(Basic):
       def __init__(self, p=S.Half, init_position=S.Zero, step_size=1):
           self.p = p
           self.q = S.One - p
           self.step_size = step_size
           self._position = init_position
           self._path = [0]

        def position(self):
            """ Returns current position """
            return self._position

        def path(self):
            """ Return the path taken to the current position """
            return self._path

        def move(self):
            """ Take a single step """
            if random.random() < self.p:
                self_position += 1
            else:
                self._position -= 1
            self._update_path(self.position())

        def walk(self, n):
            """ Takes a walk in n steps """
            for i in range(n):
                self.move()

        def _update_path(self, n):
            self._path += [n]

        def expected_right(self, steps):
            """ Return number of expected steps
                taken in right direction """
            return self.p*steps

        def expected_left(self, steps):
            """ Return number of expected steps
                taken in left direction """
            return self.q*steps

        def prob_position(self, pos=0, steps):
            """ Probability that we are position=pos
                after N steps starting from position=self._position """
            dist = pos - self._position
            if abs(dist) > steps or (steps + dist) % 2 == 0:
                return 0
            else:
                n1 = (steps + dist)/2
                n2 = (steps - dist)/2
                return Binomial(steps, n1)*self.p**n1*self.q**n2

        def prob_distance(self, dist=1, steps):
            """ Probability that we are at distance=dist
                from position=self._position after N steps """
            return self.prob_position(dist+self._position, steps)

        def moment(self, t, steps):
            """ Returns moment `mu` of prob_distance distribution """
            d = Symbol('d', Integer=True)
            return summation((d**t)*prob_distance(d, steps), (d, -steps, steps))

        def mean(self, steps):
            """ Returns mean """
            return moment(1, steps)

        def variance(self, steps):
            """ Returns variance """
            return moment(2, steps)

        def skewness(self, steps):
            """ Returns skewness """
            return moment(3, steps)

        def kurtosis(self, steps):
            """ Returns kurtosis """
            return moment(4, steps)
   ```
   Example usage:
   ```python
   >>> RWalk = RandomWalk_1D()
   >>> RWalk.move()
   RWalk.position()
   1
   >>> RWalk.walk(steps=5)
   >>> RWalk.path()
   [0, 1, 2, 1, 0, 1, 0]
   >>> RWalk.expected_right(steps=10)
   5
   >>> RWalk.prob_position(pos=3, steps=2)
   0
   ```

**Comment by Upabjojr** [comment]
@czgdp1807 has already done / is handling this part.

**Comment by czgdp1807** [comment]
@ritesh99rakesh 
I think @Upabjojr meant that the discussion on stochastic process is concluded and since 1d random walk is also a discrete time stochastic process(afaik), so you can directly open a PR by adding 1d random walks to `stochastic_process_types.py` following the api that has been decided. 
Make sure that you don't simulate random walks as you are suggesting, as I think sympy is meant for symbolic computation, so queries for random walks like the probability that it will be in a state `x` provided it is in a state `y` right now should be computed sympy. The algorithm you may have to think. 
In addition for multiple dimension random walks we may need to discuss the API but that can be done later after completing single dimension random walks.

**Comment by czgdp1807** [comment]
All the probability queries should be handled by `probability` method. Though you can call utility methods from inside the `probability`.

**Comment by czgdp1807** [comment]
Feel free to refer, https://github.com/sympy/sympy/issues/16895 and may be apply that in the work of random walks.

**Comment by czgdp1807** [comment]
Sorry, I forgot to mention one more thing. First I want to know, have you started working on `RandomWalk`? Please read the following proposal before moving on further.
Actually, I would suggest you to not work on it as it might cause distraction to you for your work on the issues you are currently working on, that is, related to sampling and compound distributions. As I got to know from our chat room that, those are quite important so if you are busy working on them then do let me know, I can take this part of task and you can carry on with your work.
If you feel that you can do something related to `RandomWalk` then also no problem while simultaneously proceeding on your current PRs. But make sure to tell me about your decision before the beginning of phase 3. Thanks.

**Comment by ritesh99rakesh** [comment]
@czgdp1807 According to our work division, I was supposed to work on Random Walk and you were supposed to work on Random Matrices. Since you have already written Stochastic process class I thought I should start with RandomWalk. I think I will work on RandomWalk as already decided.
