### ISSUE TITLE
limit()

### ISSUE THREAD

**Issue by stepfencurryxiao** [sympy/sympy#17195]
Hello, I want to know how limit () is written. Can you show me the code?

**Comment by stepfencurryxiao** [comment]
There's a little bit more code in this library. Can you tell me which Python file the limit () code is in?：）

**Comment by oscarbenjamin** [comment]
It's mostly in the series package:
https://github.com/sympy/sympy/tree/master/sympy/series
Try looking in the file limits.py but the others are also relevant.

I'm closing this as this is not an issue with SymPy. Please use the mailing list or stackoverflow to ask general questions.

**Comment by stepfencurryxiao** [comment]
Ok,think you
