### ISSUE TITLE
Matrix power is not implemented correctly

### ISSUE THREAD

**Issue by Pristine-Cat** [sympy/sympy#17203]
Matrix __pow__() operation does not seem to be implemented very rigorously leading to some erroneous cases. This issue has evolved from #17179 and a fix has been suggested by @oscarbenjamin to make matrix power work as such:

1. For `M**n` where n is a non-negative integer the result is always well defined. It can be computed from the Jordan form including for symbolic n (that satisfies the assumptions). The trivial case n=0 always gives the identity.

2. If n is a negative integer then the matrix needs to be invertible but otherwise the result is as in case 1.

3. If n is an integer, not known to be positive or negative then it can evaluate if the matrix is invertible but should remain unevaluated otherwise. Substitution of a negative integer for n should raise. Substitution of a nonnegative integer should evaluate.

4. If n is rational p/q then this is the pth power of the qth root of M (or the qth root of the pth power?). As for integers negative n is only allowed for invertible M. The qth root is not unique and does not always exist e.g. `[[0, 1], [0, 0]]` has no square root so this can raise. Where the roots exist there can be up to q**N possibilities if M is NxN.

4a. If M is positive definite then I think it has a unique positive definite qth root so we use that.

4b. If M has negative or non-real eigenvalues then provided it is not defective we can just take the pth root of each eigenvalue (taking SymPy's definition of the pth root for scalars).

4c. If M is defective then the Jordan form method can still work using pth roots of the eigenvalues.

5. If n is irrational or non-real complex then `M**n = exp(n*log(M))` - `log(M)` exists iff M is invertible and is unique if M is positive definite. If M is not positive definite then different choices to log(M) will not give equivalent results so raise? This can be taken as the definition of correctness although it might still be easiest to compute via the Jordan form method.

6. All of the above assumes that the entries of M are complex-valued. If M has matrices or operators or something as entries then only integer powers can be defined? The result could depend on whether the elements are invertible...

The problem is that some tests as well as probably some code out in the wild is coded to the current particular implementation and will break when we correct the power function.

**Comment by jksuom** [comment]
> is unique if M is positive definite.

The logarithm of a positive real number has infinitely many values though SymPy will choose the principal value. We should probably use the principal value also for matrix logarithms.

**Comment by Pristine-Cat** [comment]
Making progress cleaning up.

> 1. For `M**n` where n is a non-negative integer the result is always well defined. It can be computed from the Jordan form including for symbolic n (that satisfies the assumptions). The trivial case n=0 always gives the identity.
> 2. If n is a negative integer then the matrix needs to be invertible but otherwise the result is as in case 1.
> 3. If n is an integer, not known to be positive or negative then it can evaluate if the matrix is invertible but should remain unevaluated otherwise. Substitution of a negative integer for n should raise. Substitution of a nonnegative integer should evaluate.

Yes. Except for 3, I am new to SymPy but the convention seems to be not to evaluate in .subs() but rather do subs().doit() for evaluation? Which works as per point 3.

> 4. If n is rational p/q then this is the pth power of the qth root of M (or the qth root of the pth power?). As for integers negative n is only allowed for invertible M. The qth root is not unique and does not always exist e.g. `[[0, 1], [0, 0]]` has no square root so this can raise. Where the roots exist there can be up to q**N possibilities if M is NxN.

`M**(p/q)` is `(M**p)**(1/q)` and roots for matrices are calculated using the Jordan method, so might as well just do the whole method on p/q in one go. Test cases and live code evaluate matrix roots doing something like `M**0.5` or `M**(1/3)`, as well as since floating point numbers are finite then every floating point number is rational, and thus must accept all floats as valid and attempt the pow by Jordan.
 
> 4a. If M is positive definite then I think it has a unique positive definite qth root so we use that.

If the matrix is positive definite then pow by Jordan blocks returns the positive definite root.
 
> 4b. If M has negative or non-real eigenvalues then provided it is not defective we can just take the pth root of each eigenvalue (taking SymPy's definition of the pth root for scalars).

qth root you mean? So in this case diagonalize and do the power on the diagonal? Would this give a different answer from Jordan method?

> 4c. If M is defective then the Jordan form method can still work using pth roots of the eigenvalues.

So defective by Jordan method.

> 1. If n is irrational or non-real complex then `M**n = exp(n*log(M))` - `log(M)` exists iff M is invertible and is unique if M is positive definite. If M is not positive definite then different choices to log(M) will not give equivalent results so raise? This can be taken as the definition of correctness although it might still be easiest to compute via the Jordan form method.

Logarithm of matrix is not implemented, so again, Jordan method, which should give the principal value.

> 2. All of the above assumes that the entries of M are complex-valued. If M has matrices or operators or something as entries then only integer powers can be defined? The result could depend on whether the elements are invertible...

Let Jordan method return symbolic entries in matrix if appropriate operations are supported by objects. So basically all these cases boil down to using _matrix_pow_by_jordan_blocks() no?

So I have all this slightly tweaked and cleaned up but the problem is that there is an invalid test case that was working before which is now broken.
```
    A = zero determinant matrix
    n = Symbol('n', integer=True, nonnegative=True)
    raises(ValueError, lambda: A**n)
```
This is obviously a typo and should be:
```
    n = Symbol('n', integer=True, negative=True)
    raises(ValueError, lambda: A**n)
```
Since any matrix to any positive integer is always possible whereas any zero determinant matrix to negative power is impossible.

So my question is of an administrative nature, should I just do the PR knowing it will fail this test or is there a special procedure for fixes that break tests?

**Comment by oscarbenjamin** [comment]
> the convention seems to be not to evaluate in .subs() but rather do subs().doit() for evaluation?

There isn't an always clear convention for when evaluation should be automatic and when it should only happen on doit. When doit is required there is usually an alternative that that calls doit (e.g. integrate vs Integral).

Note for your other questions: I think that matrix power by jordan blocks is probably always the way to calculate the answer. I was trying to enumerate the situations in which the result would be well-defined and how it should be defined. This is needed to verify that the results are correct but doesn't necessarily have anything to do with how you calculate things.

For example the Jordan method is a generalisation of diagonalisation that works for non-diagonalisable (square) matrices. The point of using the Jordan decomposition is that we can distinguish these cases by their Jordan blocks rather than handling diagonalisable matrices as a separate case.

Also invertibility can be seen from the Jordan form. If the matrix is non-invertible then zero is an eigenvalue and at least one Jordan block will have zeros on the diagonal (and will also be non-invertible). So if the intention is to otherwise use the Jordan method there's no need to check for invertibility first.

> So my question is of an administrative nature, should I just do the PR knowing it will fail this test or is there a special procedure for fixes that break tests?

You should add new tests covering anything that is changed including from the other PR and to cover any cases that are relevant and don't seem to be already tested. If a test is incorrect then you should change it but try to be sure you haven't misunderstood the test you are changing (I often discover something from looking closely at tests that I *think* are incorrect).

**Comment by Pristine-Cat** [comment]
> Also invertibility can be seen from the Jordan form. If the matrix is non-invertible then zero is an eigenvalue and at least one Jordan block will have zeros on the diagonal (and will also be non-invertible). So if the intention is to otherwise use the Jordan method there's no need to check for invertibility first.

_matrix_pow_by_jordan_blocks() checks for zero eigenvalues and raises on this which I propagate up where appropriate.

> You should add new tests covering anything that is changed including from the other PR and to cover any cases that are relevant and don't seem to be already tested. If a test is incorrect then you should change it but try to be sure you haven't misunderstood the test you are changing (I often discover something from looking closely at tests that I _think_ are incorrect).

Done and done, will be opening new PR.
