### ISSUE TITLE
Solving agebric equations by Sympy

### ISSUE THREAD

**Issue by pouyan89** [sympy/sympy#17207]
Hi !

I have two hard equations which I tried to solve them with a numerical values by using Sympy:

```

from sympy import *
import sympy as sy
import math
 
s,v=symbols('s v')
 
s=((4.13 + I*568)/(4*(s+v))) -(5/6) * ((1400*s+120*I)/(v+4*I*s))
 
v=((570*s+I*3700)/(21*(2*v-s))) + (8/13) * ((77000*v - I*1400)/(v+s))
sol=solve([s,v],[v,s])


```
But when I run it and try to get numerical values for s and v I dont get numerical values! Must i use nsolve? how can I do that? I get even error when I use nsolve!

**Comment by oscargus** [comment]
You are overwriting your symbols s and v with the equations s and v. A start would be to call the equations something else. Note that the expressions are solved to be equal to zero.

**Comment by oscarbenjamin** [comment]
I changed it to:
```python
from sympy import *
import sympy as sy
import math
 
s,v=symbols('s v')
 
a=((4.13 + I*568)/(4*(s+v))) -(5/6) * ((1400*s+120*I)/(v+4*I*s))
 
b=((570*s+I*3700)/(21*(2*v-s))) + (8/13) * ((77000*v - I*1400)/(v+s))
sol=solve([a,b],[v,s])
```
and I got the solutions:
```julia
In [66]: sol                                                                                                                      
Out[66]: 
[(-0.162613185171929 - 0.0249380780103703⋅ⅈ, -0.324382159556932 - 0.0391046643075021⋅ⅈ), (0.000180831943743341 + 0.0217340522158
04⋅ⅈ, -0.485508698606858 - 0.104289860625461⋅ⅈ), (0.000200755978814712 + 0.0162842058745204⋅ⅈ, -0.00114958377399168 + 0.00027812
8093578111⋅ⅈ)]
```
So I think it works fine.

I'm going to close this as not an issue in SymPy. In future to ask for help it is better to use the mailing list or stackoverflow.

**Comment by pouyan89** [comment]
> 
> 
> You are overwriting your symbols s and v with the equations s and v. A start would be to call the equations something else. Note that the expressions are solved to be equal to zero.

Thank you very much but the equations are these as I mentioned:
s=((4.13 + I*568)/(4*(s+v))) -(5/6) * ((1400*s+120*I)/(v+4*I*s))
 
v=((570*s+I*3700)/(21*(2*v-s))) + (8/13) * ((77000*v - I*1400)/(v+s))

or better :
s-((4.13 + I*568)/(4*(s+v))) -(5/6) * ((1400*s+120*I)/(v+4*I*s))=0
 
v-((570*s+I*3700)/(21*(2*v-s))) + (8/13) * ((77000*v - I*1400)/(v+s))=0

But thanks for the help
