### ISSUE TITLE
v1.4 projection point3D to a plane gives 'list index out of range' error

### ISSUE THREAD

**Issue by benedict1986** [sympy/sympy#17231]
Hi, thanks a lot for so nice project. However I am currently experiencing an issue while projecting a Point3D to a Plane. 

I am using SymPy version 1.4 and Python 3.7.3 managed by anaconda 2019.03.

I am printing out the following arguments. Can you please help to see what could be wrong? Thanks a lot

    > print(point)
    Point3D(-0.254097283, 0.225122645, 1.437058)

    > print(plane)
    Plane(Point3D(0, 0, 0), (0, 1, 0))

    > print(Line3D(point, point + Point(plane.normal_vector)))
    Line3D(Point3D(-0.254097283, 0.225122645, 1.437058), Point3D(-0.254097283, 1.225122645, 1.437058))

    > print(plane.is_parallel(Line3D(point, point + Point(plane.normal_vector))))
    False

    > print(plane.intersection(Line3D(point, point + Point(plane.normal_vector))))
    []

    > print(point in plane)
    False

    > print(plane.projection(point))
    File "C:\Users\Admin\.conda\envs\trp\lib\site-packages\sympy\geometry\plane.py", line 790, in projection
    return self.intersection(Line3D(rv, rv + Point3D(self.normal_vector)))[0]
    IndexError: list index out of range
    `

**Comment by oscarbenjamin** [comment]
It seems to work fine for me:
```julia
In [5]: point = Point3D(-0.254097283, 0.225122645, 1.437058)                                                                      

In [6]: plane = Plane(Point3D(0, 0, 0), (0, 1, 0))                                                                                

In [7]: print(plane.projection(point))                                                                                            
Point3D(-254097283/1000000000, 0, 718529/500000)
```
But then my Point looks different to yours when I print it (it has rationals instead of floats):
```julia
In [8]: point                                                                                                                     
Out[8]: Point3D(-254097283/1000000000, 45024529/200000000, 718529/500000)
```
I have to use `evaluate=False` to get what you have:
```julia
In [15]: point = Point3D(-0.254097283, 0.225122645, 1.437058, evaluate=False)                                                     

In [16]: plane = Plane(Point3D(0, 0, 0), (0, 1, 0))                                                                               

In [17]: point                                                                                                                    
Out[17]: Point3D(-0.254097283000000, 0.225122645000000, 1.43705800000000)

In [18]: plane                                                                                                                    
Out[18]: Plane(Point3D(0, 0, 0), (0, 1, 0))

In [19]: print(plane.projection(point))                                                                                           
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-19-ea454072964b> in <module>
----> 1 print(plane.projection(point))

~/current/sympy/sympy/sympy/geometry/plane.py in projection(self, pt)
    788         if rv in self:
    789             return rv
--> 790         return self.intersection(Line3D(rv, rv + Point3D(self.normal_vector)))[0]
    791 
    792     def random_point(self, seed=None):

IndexError: list index out of range
```
The reason is
```julia
In [20]: plane.intersection(Line3D(point, point + plane.normal_vector))                                                           
Out[20]: []
```
That list is returned from
https://github.com/sympy/sympy/blob/fa8328d1cd9e7af7c81fdef579e788038465b665/sympy/geometry/plane.py#L407-L419
From the debugger at line 419:
```
(Pdb) p p
Point3D(-254097283/1000000000, 277555756156289/10000000000000000000000000000000, 718529/500000)
(Pdb) p p not in self
True
(Pdb) p c
[-0.225122645000000]
(Pdb) p a
Point3D(-0.254097283000000, 1.0*_Dummy_199 + 0.225122645, 1.43705800000000)
(Pdb) p a.subs(t, c[0])
Point3D(-254097283/1000000000, 277555756156289/10000000000000000000000000000000, 718529/500000)
```
So what happens here is that solve returns the float solution c which is approximately but not exactly correct because it using floats. When this gets substituted into a it is converted to rational. The resulting point fails the p in self test because it is only approximately correct.

You can avoid this problem by not using `evaluate=False`. The fix for this in general is that the geometry module should not convert to rational implicitly and various routines should be fixed to handle floats properly (i.e. by using tolerances rather than exact checks).

**Comment by benedict1986** [comment]
Hi oscarbenjamin, thank you for your answer. It looks good now. No more such error happens. However, the performance seems affected quite a lot. Now it takes about 10 to 20 seconds to convert 120 points into Point3D and take similar time to project 120 Point3D to a Plane. Is there any good way to improve the performance? Thanks

**Comment by oscarbenjamin** [comment]
It's slow converting the points because it uses nsimplify. It would be faster to use Rational and you can do that yourself e.g.:
```
Point3D(Rational(-0.254097283), Rational(0.225122645), Rational(1.437058))
```
That's about 100x faster on my machine but it creates more complicated rationals which might slow down the subsequent calculations.

**Comment by benedict1986** [comment]
Hi oscarbenjamin, thanks a lot. It is much faster and I do not need much subsequent calculations at the moment.
