### ISSUE TITLE
plot_parametric can not be imported

### ISSUE THREAD

**Issue by singladur** [sympy/sympy#17252]
I have tried to import plot_parametric from sympy and I can not.
I am using sympy 1.4 and I have tried in two different environments: Thonny 3.2 and Spider 3.3.4 (with Anaconda) and Python 3. 
I can import plot and plot_implicit but plot_parametric can not be imported. When I import the whole sympy, it rises no error but it does not import plot_parametric.

Additional: typing "from sympy import plot_parametric" rises an error, however "from sympy.plotting import plot_parametric" works fine.  However both ways of importing work fine for plot or plot_implicit.

**Comment by oscarbenjamin** [comment]
I can import it as
```
from sympy.plotting import plot_parametric
```
Is that unclear in the documentation?

**Comment by sylee957** [comment]
https://github.com/sympy/sympy/blob/8ca4a683d58ac1f61cfd2e4dacf7f58b9c0fefab/sympy/__init__.py#L83

I see it does not belong to the global namespace.
Would it be viable to make it importable with sympy main?

**Comment by oscarbenjamin** [comment]
I guess that if the others are imported then this can be as well. It just needs to be added to the line highlighted by @sylee957 above.
