### ISSUE TITLE
xreplace with Range issue

### ISSUE THREAD

**Issue by oscargus** [sympy/sympy#17256]
I've found a weird error when trying to finalize some summation changes...

```
from sympy import Symbol, Range, Sum
x = Symbol('x')
s1 = Sum(x + 1, (x, 1, 9))
s2 = Sum(x + 1, (x, Range(1, 10)))
```
s1 is now `Sum(x + 1, (x, 1, 9))` and s2 is `Sum(x + 2, (x, 0, 8))`

Now:
```
a = Symbol('a')
r1 = s1.xreplace({x:a})
r2 = s2.xreplace({x:a})
```
which leads to r1 being `Sum(a + 1, (a, 1, 9))` as expected, but r2 is `Sum(a + 2, (x, 0, 8))` so the x in the summation limits has not been replaced.

The reason seems to be:
```
In [19]: srepr(s1)
Out[19]: "Sum(Add(Symbol('x'), Integer(1)), Tuple(Symbol('x'), Integer(1), Integer(9)))"

In [20]: srepr(s2)
Out[20]: "Sum(Add(Symbol('x'), Integer(2)), (Symbol('x'), Integer(0), Integer(8)))"
``` 
so when providing a range, the result is not a Tuple. (Interestingly enough it is a Tuple after xreplace.)

I am working on this, but since it is a part of another PR with a different purpose (to get that to pass), I describe the issue in more detail here. (Although I am not a big fan of opening Issues just to directly close them through a PR.) Also, when you try to write it down, the debugging becomes more systematic, I had not noticed the difference in srepr when I started writing this, despite having looked at a few...

**Comment by sylee957** [comment]
It looks like `Range` is interpreted into making a not well defined sympy object.
Also, I see integrals are starting to accept `Range` as intervals, but this may have to be disallowed because integrals should not be accepting discrete domains I believe.

**Comment by oscarbenjamin** [comment]
> integrals should not be interpreting the discrete set

I agree. Also Sum should not accept Intervals so this shouldn't happen:
```
In [25]: Sum(x, (x, Interval(2, 3)))                                                                                              
Out[25]: 
  3    
 ___   
 ╲     
  ╲    
  ╱   x
 ╱     
 ‾‾‾   
x = 2 
```

**Comment by oscargus** [comment]
I fixed the `Range` issue for `Sum`and `Product` in #17259 (actually, even for `Integral`, but that is another story...).

I agree that `Range` should not be supported/used in `Integral` (and `Interval` not in `Sum` and `Product`). Didn't do anything about it though. One reason being that `Sum` and `Product` accepts non-integer limits, otherwise one could use `ExprWithIntLimits` (or whatever it is called).

**Comment by oscarbenjamin** [comment]
I don't think it's reasonable for Sum/product to accept non-integer limits. It leads to broken behaviour:
```
In [1]: summation(1, (x, 0, S.Half))                                                                                              
Out[1]: 3/2
```

**Comment by oscargus** [comment]
Me neither, but there are tests for it in the code. (And then I am not just considering oo...)

Longer (old) discussion: #5822

One may also consider summation over sets, where of course the set members may take on any value.

Some comments regarding Interval: #14587 (which from some perspective makes sense, summation of all the integer points in an interval). And a fix #14597

Here are some other links:
https://www.sciencedirect.com/science/article/pii/S0377042704003851
https://math.stackexchange.com/questions/766440/summation-with-non-integer-induces

**Comment by oscarbenjamin** [comment]
The discussion in #14587 doesn't seem right since Interval does not represent an integer interval. Maybe it did before but now we have:
```
In [11]: S(5)/2 in Interval(2, 3)                                                                                                 
Out[11]: True
```
Otherwise I can see the sense in summing from -1/2 to 1/2 as suggested in #5822.

Clearly right now this isn't consistent though.

**Comment by oscargus** [comment]
I interpreted the interval discussion that for summation one takes all integer points into the interval (since it is a summation), and sum over those. But I agree that it isn't consistent.
