### ISSUE TITLE
Sums with infinite lower limit don't pretty-print correctly.

### ISSUE THREAD

**Issue by oscarbenjamin** [sympy/sympy#17258]
We have nice pretty printing for Sum:
```julia
In [27]: n = Symbol('n')                                                                                                          

In [28]: Sum(n, (n, -oo, 1))                                                                                                      
Out[28]: 
  1     
 ___    
 ╲      
  ╲     
  ╱    n
 ╱      
 ‾‾‾    
n = -∞  
```
However if the dummy symbol is finite and the lower limit infinite then
```julia
In [29]: n = Symbol('n', integer=True)                                                                                            

In [30]: Sum(n, (n, -oo, 1))                                                                                                      
Out[30]: 
  1    
 ___   
 ╲     
  ╲    
  ╱   n
 ╱     
 ‾‾‾   
False
```
I believe this happens because:
```julia
In [34]: Eq(n, -oo)                                                                                                               
Out[34]: False

In [35]: Eq(n, -oo, evaluate=False)                                                                                               
Out[35]: n = -∞
```
So evaluate=False should probably be used for this somewhere in the printing code.

**Comment by oscargus** [comment]
This is a direct consequence of `-oo` is not integer. Actually, with the current assumptions, SymPy should have complained upon creating the object as you are saying that you want a variable to take on a value that breaks against its assumptions. Just as it should if you put another non-integer value in the summation.

This is what I have been talking about when real and integer stopped including `oo`. There are clearly legitimate cases where you want to declare a variable integer and/or real and still let it be `oo` at a later stage. Time for extended_integer I guess...

**Comment by asmeurer** [comment]
I remember seeing this issue before. It might be a duplicate. The issue, as I recall, is that the printer uses `Eq` to print the lower bound instead of just printing it directly.

**Comment by asmeurer** [comment]
I swear I reported this before but I can't find it so ¯\\\_(ツ)_/¯ ‏.

I don't think it's necessary to reuse the Equality printer in the Sum printer. It's not that difficult to print "var = lower_limit". `_print_Relational` is only a couple of lines.  But even if we did reuse it, we should use `evaluate=False` to make sure it doesn't evaluate to something that isn't a Relational from under us. This issue shows one way that can happen, but there would could be others too if some weird assumptions were put on the variable. For example:

```py
>>> n = Symbol('n', odd=True)
>>> pprint(Sum(n, (n, 0, 2)))
  2
 ___
 ╲
  ╲
  ╱   n
 ╱
 ‾‾‾
False
```

(never mind what that sum should actually return when evaluated; that's a whole separate issue)

**Comment by oscarbenjamin** [comment]
> There are clearly legitimate cases where you want to declare a variable integer and/or real and still let it be `oo` at a later stage

Maybe but I don't think that this is one. The dummy variable in the sum is an integer and is finite for every term in the sum. Using oo like this as a sum limit is a (reasonable) abuse of notation but should not be interpreted literally. According to the definition of Sum in the docstring this should be defined as `f(oo)+f(oo+1)+...` but that is not a meaningful definition.

An infinite sum like this is a short-hand for the limit definition
```
Sum(f(n), (n, -oo, b)) = Sum(f(n), (n, a, b)).limit(n, -oo)
```
so It's the limit of finite sums. The limit n, oo also does not imply that n itself needs to become infinite: that's another abuse of notation.

I think that the formal inconsistency in standard notation is showing here in the failed output. The printing code just needs to be fixed so it doesn't depend on the Eq being formally correct.

**Comment by oscargus** [comment]
> (never mind what that sum should actually return when evaluated; that's a whole separate issue)

I actually tried that today as I thought it was a good idea to also inherit the odd and even properties of the limits. The summation doesn't take it into account (as far as I can tell), but one gets some rather interesting results from time to time as some expressions use it to simplify the output, most prominently `(-1)**n`. Took me a while to realize what was happening...
