### ISSUE TITLE
Incorrect value for hbar in sympy.physics.units

### ISSUE THREAD

**Issue by CameronKing** [sympy/sympy#17264]
The numerical value given for hbar differs from the CODATA recommended one of: [1.054571817e-34 J s](https://physics.nist.gov/cuu/pdf/wallet_2018.pdf).

**Comment by oscarbenjamin** [comment]
That seems like it would be easy enough to fix. Could you send a pull request?

**Comment by CameronKing** [comment]
Sure, I can do that.

**Comment by CameronKing** [comment]
I submitted a PR #17273 to update hbar and the closely associated physical constants (G and kB).
