### ISSUE TITLE
[Feature Request]: add new printer for Rust Lang

### ISSUE THREAD

**Issue by stevenleeS0ht** [sympy/sympy#17265]
It would be awesome if there is a printer for [rust-lang](https://www.rust-lang.org/).

**Comment by sylee957** [comment]
There's already https://github.com/sympy/sympy/blob/master/sympy/printing/rust.py,
but some things may be updated or improved upon, since I see it is rarely being developed for now
Also see the thread #10554

**Comment by sylee957** [comment]
I may close this issue to guide to the issue #10554
