### ISSUE TITLE
Some confusing (Potential error) on source code (master branch) of sympy

### ISSUE THREAD

**Issue by stevenleeS0ht** [sympy/sympy#17274]
Here is some code in sympy master branch which make me feel it is error. But I am not sure.

# 1

sympy/sets/handlers/add.py

```python3
@dispatch(Interval, Infinity)
def _set_sub(x, y):
    if self.start is S.NegativeInfinity:
        return Interval(-oo, oo)
    return FiniteSet(-oo)

@dispatch(Interval, NegativeInfinity)
def _set_sub(x, y):
    if self.start is S.NegativeInfinity:
        return Interval(-oo, oo)
    return FiniteSet(-oo)
```
What does `self` mean? or x?

# 2

sympy/physics/quantum/density.py

```python3
    def _print_operator_name_pretty(self, printer, *args):
        return prettyForm(unichr('\N{GREEK SMALL LETTER RHO}'))
```

`unichr` is a feature of python2. This module is not for compatibility. Hence I think there is something wrong.

# 3

sympy/core/numbers.py

```python3
    def _sage_(self):
        import sage.all as sage
        return sage.NaN
```

`sage` is not a dependency of sympy, and this module is obviously not for example or testing.
Should there be an `try` block?

# 4

sympy/functions/special/bessel.py

```python3
    elif method == "scipy":
        from scipy.optimize import newton
        try:
            from scipy.special import spherical_jn
            f = lambda x: spherical_jn(n, x)
        except ImportError:
            from scipy.special import sph_jn
            f = lambda x: sph_jn(n, x)[0][-1]
```

Since `scipy` is not a dependency of sympy. I don't know if it is necessary to use `try` block to import optional dependency. Or use `sympy.external.import_module`.

# 5

sympy/utilities/_compilation/compilation.py

```python3
                for path in glob.glob(k.pathname):
                    _per_file_kwargs[path] = v
```

glob is defined in module glob which is part of python standard library. But it need to be imported first.

**Comment by oscargus** [comment]
1. Not sure how the dispatch magic works, but I understand you concern. Worth looking more into.
 2. Agreed. This line is not covered in the tests, so it may very well fail in Python 3.
 3. The `_sage_` methods are only (supposed to be) called by Sage, so it should be OK. But clearly, it would be safer to use try and show a better error message. Quite a lot of instances though and I do not think there is much gain. Also, I think the error message should say that it cannot find sage and I think the only addition one could make is to tell the user to install Sage if they want to run this.
 4. Somehow similar to 3. I guess if the user decides to use the scipy switch without scipy installed, then, well, there will be an error. 
 5. Agreed. Code not covered, so may very well be an error.

**Comment by oscargus** [comment]
Some more about 1. 

The code is not covered in tests and looking at the other methods clearly confirms your suspicions. Would be nice to add tests and correct this.

```
In [27]: a = SetExpr(Interval(0, 5))

In [28]: c = SetExpr(oo)

In [29]: a-c
Traceback (most recent call last):

  File "<ipython-input-29-6f0e715cd956>", line 1, in <module>
    a-c

  File "C:\Users\Oscar\sympy\sympy\core\decorators.py", line 91, in __sympifyit_wrapper
    return func(a, b)

  File "C:\Users\Oscar\sympy\sympy\core\decorators.py", line 129, in binary_op_wrapper
    return func(self, other)

  File "C:\Users\Oscar\sympy\sympy\sets\setexpr.py", line 52, in __sub__
    return _setexpr_apply_operation(set_sub, self, other)

  File "C:\Users\Oscar\sympy\sympy\sets\setexpr.py", line 95, in _setexpr_apply_operation
    out = op(x, y)

  File "C:\Users\Oscar\sympy\sympy\sets\sets.py", line 2085, in set_sub
    return _apply_operation(_set_sub, x, y, commutative=False)

  File "C:\Users\Oscar\sympy\sympy\sets\sets.py", line 2065, in _apply_operation
    out = op(x, y)

  File "C:\Users\Oscar\sympy\sympy\multipledispatch\dispatcher.py", line 198, in __call__
    return func(*args, **kwargs)

  File "C:\Users\Oscar\sympy\sympy\sets\handlers\add.py", line 60, in _set_sub
    if self.start is S.NegativeInfinity:

NameError: name 'self' is not defined
```

**Comment by oscargus** [comment]
Oh, and here is the coverage information for 1.

https://codecov.io/gh/sympy/sympy/src/master/sympy/sets/handlers/add.py

If you (or someone else) decides to fix it, please add tests for the remaining cases as well.

**Comment by oscarbenjamin** [comment]
> 3\. The `_sage_` methods are only (supposed to be) called by Sage, so it should be OK. But clearly, it would be safer to use try and show a better error message. Quite a lot of instances though and I do not think there is much gain. Also, I think the error message should say that it cannot find sage and I think the only addition one could make is to tell the user to install Sage if they want to run this.

I don't think there should be any change to error messages from `_sage_` methods. Users shouldn't use these methods.

**Comment by stevenleeS0ht** [comment]
@oscargus ,

What 
""" python3
In [27]: a = SetExpr(Interval(0, 5))

In [28]: c = SetExpr(oo)

In [29]: a-c
```
are supposed to return?

**Comment by oscargus** [comment]
I would assume that the logic in the incorrect code is correct, so replacing self with x should be enough. Not sure about the mathematical aspects either.

**Comment by stevenleeS0ht** [comment]
For 2nd error point, I don't know it usage.
For 5th error point, it is File System IO intensive function, I don't know the convention of these kind of test.

**Comment by bjodah** [comment]
The 5th one is my fault. The `_compilation` submodule is used internally by our tests (if you run `$ git grep _compilation` you'll see some files using it: `sympy/codegen/tests/test_*.py`).

I ported that code over from another library of mine, and I missed to import `glob`. We should add that import statement.

Usually test coverage is of course of high priority. But since we have the conventional leading underscore in `_compilation` to indicate that it is not public API, we need not stress too much about the test coverage (unless we want to promote this to public API and drop the underscore, but that module needs to see more testing on several platforms in that case).

Either way, nice catch!
