### ISSUE TITLE
How to do sigma over functions

### ISSUE THREAD

**Issue by h-jia** [sympy/sympy#17286]
How to define and calculate function like this:

<a href="https://www.codecogs.com/eqnedit.php?latex=\sum_{t=1}^{n}&space;\frac{C}{(1&plus;r)^{t}}=\sum_{t=n&plus;1}^{m}&space;\frac{B}{(1&plus;r)^{t}}" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\sum_{t=1}^{n}&space;\frac{C_{t}}{(1&plus;r)^{t}}=\sum_{t=n&plus;1}^{m}&space;\frac{B_{t}}{(1&plus;r)^{t}}" title="\sum_{t=1}^{n} \frac{C}{(1+r)^{t}}=\sum_{t=n+1}^{m} \frac{B}{(1+r)^{t}}" /></a>

where C and B are constant, n=5 and m=50

what I have tried is to 
```
from sympy import *

B = [None, 102, 41231, 31214, 43221]
C = [None, 313213, 42313, 4231, 412131]

r = symbols('r')
def funcr(r):
     for n in range(1, 6):
            a = sum(Ct[0] / ((1 + r) ** j ) for j in range(1, n))
            b = sum(Bt[0] / ((1 + r) ** j ) for j in range(n + 1, 51))
            return a - b

print(solve(funcr, r))
```

But I get this error:
`could not parse '<function funcr at 0x109aba1e0>'' failed, because of exception being raised:
SyntaxError: invalid syntax (<string>, line 1)`

**Comment by smichr** [comment]
Try `solve( funcr(r) , r )`.

FYI...the mailing list is a good place to ask questions. The issue page is the place for raising issues that need some sort of fix by SymPy.

A link to the mailing list is given on the wiki page.
