### ISSUE TITLE
Travis-CI problem: CondaHTTPError: HTTP 504 when attempt to retrieve symengine.

### ISSUE THREAD

**Issue by stevenleeS0ht** [sympy/sympy#17285]
The Error message is below:

```
CondaHTTPError: HTTP 504 GATEWAY_TIMEOUT for url <https://conda.anaconda.org/symengine/label/dev/linux-64/python-symengine-0.3.0.136.g511453a-py36_1.tar.bz2>
Elapsed: 00:59.713644
CF-RAY: 4fd2f2e64c34e1d2-ORD
An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
```

That is what make pull request auto test always failed.

**Comment by stevenleeS0ht** [comment]
Please consider to use latest package for py36_1:


python-symengine | 0.3.0.136.g511453a | py36_1 | python-symengine-0.3.0.136.g511453a-py36_1.tar.bz2
|---|---|---|---

**Comment by oscargus** [comment]
There is really no way to automatically sort that out. People with a bit more bits can restart individual tests. Other than that one can open and close the PR and all tests will restart. Or just push something new.

(I've noticed that during evenings in the US this particular problem happens more frequently.)

**Comment by sylee957** [comment]
Today, I see every tests are failing for the last hour. Is there a way to check their server status?

**Comment by oscargus** [comment]
Closing this as we are not using Travis any more.
