### ISSUE TITLE
ceiling(pos) > 0 should be true

### ISSUE THREAD

**Issue by smichr** [sympy/sympy#17309]
Also, shouldn't `floor(neg) < 0`, `floor(pos) >= 0` and `ceiling(neg) <=0` evaluate to True, too?

**Comment by oscarbenjamin** [comment]
To clarify I guess that you mean that e.g. this should evaluate to True:
```julia
In [4]: floor(Symbol('x', negative=True)) < 0
Out[4]: ⌊x⌋ < 0
```
