### ISSUE TITLE
[Discussion]: request to rename the local decorator variable of dispatch from _ to (_df, _ddf or something else)

### ISSUE THREAD

**Issue by stevenleeS0ht** [sympy/sympy#17316]
`_` is often used in place occupier which only take a place in order to satisfy the syntax requirement.

For example `_, _ext = os.path.splitext(filename)`, this code is to get extension name filename, the base name of this file is unimportant, in other word, `_` will be forgotten after this statement.

If using `_` as a local variable name, it might get big trouble.

Please look the following code.

```python3
def helloworld(a):
    _ = getvar(a)  # written by AUTHOR A

    # About 50 lines of code

    _, _ext = os.path.split  # added by AUTHOR B

    # About 50 lines of code

return _

```

Author B didn't read through the entire code of this function. it just add a function to get extension name. Then the entire behavior of this function changes.

The same logic can apply in dispatch in sympy.

But if the name of return value changes as _df (standing for decorator function) or _ddf (standing for dispatch decorator function). It can efficiently avoid the situation above.

How is your opinion?

**Comment by stevenleeS0ht** [comment]
@sylee957 , @smichr , please have a look on this issue. If you agree with me, I will modified this and submit in PR #17284

**Comment by asmeurer** [comment]
_ should never be used if the variable is actually used again as in your example. I don’t like it for dispatch functions either because it confuses pyflakes, though arguably that’s something that should be fixed in pyflakes.
