### ISSUE TITLE
Contracting tensors of rank 2 does not apply the metric.

### ISSUE THREAD

**Issue by cjayross** [sympy/sympy#17328]
So to demonstrate this issue, I'll use the Anti de Sitter metric:
![equation](https://latex.codecogs.com/gif.latex?g_%7B%5Cmu%5Cnu%7D%20%3D%20%5Cbegin%7Bbmatrix%7D%20-1%20%26%200%20%26%200%20%26%200%5C%5C%200%20%26%20%5Ccos%5E2%28t%29%20%26%200%20%26%200%5C%5C%200%20%26%200%20%26%20%5Ccos%5E2%28t%29%5Csinh%5E2%28%5Cchi%29%20%26%200%5C%5C%200%20%26%200%20%26%200%20%26%20%5Csin%5E2%28%5Ctheta%29%5Ccos%5E2%28t%29%5Csinh%5E2%28%5Cchi%29%20%5Cend%7Bbmatrix%7D)

When performing a contraction using ``sympy.tensor.Tensor`` objects with the ``replace_with_arrays`` method, for some reason I am getting that
![equation](https://latex.codecogs.com/gif.latex?g_%7B%5Cmu%5Cnu%7Dg%5E%7B%5Cmu%5Cnu%7D%20%5Cne%20g%5E%5Cmu_%5Cmu)

The expression ![equation](https://latex.codecogs.com/gif.latex?g_%7B%5Cmu%5Cnu%7Dg%5E%7B%5Cmu%5Cnu%7D) yields the correct result with ``4``, but the right hand side returns
![equation](https://latex.codecogs.com/gif.latex?g%5E%5Cmu_%5Cmu%20%3D%20%5Csin%5E2%28%5Ctheta%29%5Ccos%5E2%28t%29%5Csinh%5E2%28%5Cchi%29%20&plus;%20%5Ccos%5E2%28t%29%5Csinh%5E2%28%5Cchi%29%20&plus;%20%5Ccos%5E2%28t%29%20-%201)

The right hand side's result makes sense as an ordinary trace, however, in this context the metric should be used to raise an index prior to contraction which doesn't happen here.

Here is code that replicates this issue:
```python
>>> from sympy import *
>>> from sympy.tensor.tensor import *
>>> from collections import namedtuple

>>> t, chi, theta, phi = symbols('t chi theta phi', real=True)
>>> array = Array(
        [[-1, 0, 0, 0], 
         [0, cos(t)**2, 0, 0],
         [0, 0, cos(t)**2*sinh(chi)**2, 0],
         [0, 0, 0, sin(theta)**2*cos(t)**2*sinh(chi)**2]]
        )
>>> metric_id = namedtuple('MetricId', ['name', 'antisym'])
>>> g = TensorIndexType('g', metric=metric_id('g', False), dim=4, dummy_fmt='g')
>>> adesit = tensorhead('A', [g, g], [[1], [1]])
>>> mu, nu = tensor_indices('mu nu', g)
>>> repl = {g: array, adesit(-mu, -nu): array}

>>> (adesit(mu, nu) * adesit(-mu, -nu)).replace_with_arrays(repl)
4
>>> adesit(mu, -mu).replace_with_arrays(repl)
sin(theta)**2*cos(t)**2*sinh(chi)**2 + cos(t)**2*sinh(chi)**2 + cos(t)**2 - 1
```

My theory is that the issue is due to the fact that the ``Tensor._extract_data`` method calls ``_TensorDataLazyEvaluator.data_contract_dum`` before the call to ``Tensor._match_indices_with_other_tensor``. Since ``data_contract_dum`` returns a scalar, the operations in ``_match_indices_with_other_tensor`` are ignored.

**Comment by drybalka** [comment]
There are some other problems with `.replace_with_arrays()` method, unfortunately. I am currently working on this issue.

**Comment by cjayross** [comment]
@drybalka That's good to hear. What are you planning on doing (out of curiosity)?

**Comment by rashti-alireza** [comment]
Hi all,
I also have some issues for lowering and raising indices of tensor of rank 3 and higher.
