### ISSUE TITLE
Wrong unicode printing for ConditionSet / Contains

### ISSUE THREAD

**Issue by gschintgen** [sympy/sympy#17339]
Somehow unicode prettyprinting a combination of ConditionSet, Contains and fractions breaks down (see Out[33]):
```
In [32]: solveset(Abs(x) - n, x, S.Reals)
Out[32]: {x | x ∊ {-n, n} ∧ (n ∈ [0, ∞))}

In [33]: solveset(Abs(2*x) - n, x, S.Reals)
Out[33]:
⎧        ⎧-n   n⎫                                       ⎫
⎨x | x ∊ ⎨───, ─⎬ ∧ (n         , ─ ∈ [0, ∞), 2         )⎬
⎩        ⎩ 2   2⎭                                       ⎭

In [34]: pprint(_, use_unicode=False)
           -n   n
{x | x in {---, -} and Contains(n/2, Interval(0, oo))}
            2   2
```

**Comment by gschintgen** [comment]
I'm also now noticing that the two "element of" glyphs are actually two different ones. In `pretty.py` there seems to be a mix of `u"\N{SMALL ELEMENT OF}"` and `u" \N{ELEMENT OF} "`.

(The second one seems preferable in my opinion: at least on my devices it looks better.)

**Comment by anirudnits** [comment]
I would like to work on this, if nobody else is.

**Comment by oscargus** [comment]
Go ahead @anirudnits 

Probably the issue is that when printing the second set (`Contains`), something goes wrong with the multi-line printing.

**Comment by anirudnits** [comment]
@oscargus thanks, I'll look into it!

**Comment by anirudnits** [comment]
@oscargus  can you give me some pointers? feeling quite lost with the whole codebase.Thanks

**Comment by gschintgen** [comment]
It's not only fractions that are affected, exponents too:
```
In [65]: ConditionSet(x, Contains(x**2, Integers))
Out[65]: {x | ( 2    , x  ∈ ℤ)}
```

**Comment by oscargus** [comment]
@anirudnits This is the function:

https://github.com/sympy/sympy/blob/e0f45aea9f283b1781a75e79ba47c93e46fc8bf6/sympy/printing/pretty/pretty.py#L1974-L2000

My guess is that it is the following line that doesn't work properly:

https://github.com/sympy/sympy/blob/e0f45aea9f283b1781a75e79ba47c93e46fc8bf6/sympy/printing/pretty/pretty.py#L1999-L2000

`_print_seq` is shown here:
https://github.com/sympy/sympy/blob/e0f45aea9f283b1781a75e79ba47c93e46fc8bf6/sympy/printing/pretty/pretty.py#L2063-L2103

I'd look at the different parts and try to figure out why merging certain combinations doesn't work. I'm not really into the details of the pretty printer myself.

**Comment by anirudnits** [comment]
Thanks, I'll look into it.
