### ISSUE TITLE
solveset: current state of _solve_trig and _invert

### ISSUE THREAD

**Issue by gschintgen** [sympy/sympy#17334]
**[I have slightly updated this post.]**

This is a (rather long) summary/discussion issue that outlines some *specific* shortcomings I noticed while reviewing solveset's capabilities for solving trigonometric equations. (As such it's a complement to/part of https://github.com/sympy/sympy/issues/12340. See also: https://github.com/sympy/sympy/issues/13084)

What bothers me most is that all `solveset(trig equation)` calls always ends up in a substitution based solver, either `_solve_trig1` or `_solve_trig2`. Both solvers have in common that they completely lose the information what the actual trig function was (sin? cos? etc.)

**[fixed for solveset_real]** Here's an example for which `.rewrite(exp)` is used (by `_solve_trig1`):
```
In [19]: solveset(sin(x) - sin(1), x, S.Reals)
Out[19]: Union(Intersection(ImageSet(Lambda(_n, -I*(I*(2*_n*pi + atan(sin(1)/cos(1))) + log(sqrt(cos(1)**2 + sin(1)**2)))), Integers), Real
s), Intersection(ImageSet(Lambda(_n, -I*(I*(2*_n*pi - atan(sin(1)/cos(1)) + pi) + log(sqrt(cos(1)**2 + sin(1)**2)))), Integers), Reals))

In [20]: solveset(sin(x) - sqrt(5)/3, x, S.Reals)
Out[20]: Union(ImageSet(Lambda(_n, 2*_n*pi + atan(sqrt(5)/2)), Integers), ImageSet(Lambda(_n, 2*_n*pi - atan(sqrt(5)/2) + pi), Integers))
```
(Sorry, unicode doesn't always work out fine for copy&paste.)
It's clearly noticeable that an exponential equation has in fact been solved, the determination of complex arguments being responsible for the `atan`s. The first example can be properly simplified using `simplify`, but that's not always the case! Just try: `solveset(tan(x)-tan(pi/5),x,S.Reals)`...

Yet, there's a powerful alternative solver for these basic equations: `_invert`. Compare the above with:
```
In [25]: from sympy.solvers.solveset import _invert

In [26]: _invert(sin(x), sin(1), x, S.Reals)
Out[26]: (x, ImageSet(Lambda(_n, (-1)**_n + _n*pi), Integers))

In [27]: _invert(sin(x), sqrt(5)/3, x, S.Reals)
Out[27]: (x, ImageSet(Lambda(_n, (-1)**_n*asin(sqrt(5)/3) + _n*pi), Integers))

In [28]: _invert(tan(x), tan(pi/5), x, S.Reals)
Out[28]: (x, ImageSet(Lambda(_n, _n*pi + pi/5), Integers))
```

Don't get me wrong: `_solve_trig1` and `_solve_trig2` are very important parts of solveset, they're fundamental for solving equations with *mixed* trig functions. But for equations that are amenable to a more direct approach, they're hardly optimal.

Currently `_invert` is already called upon by other solvers, but not by `_solve_trig`! (Neither by `solve_decomposition` nor `nonlinsolve`)

Examples:
```
In [34]: from sympy.solvers.solveset import _solve_as_poly, _solve_as_rational

In [35]: _solve_as_poly(tan(x)-tan(pi/5), x, S.Reals)
Out[35]: ImageSet(Lambda(_n, _n*pi + pi/5), Integers)

In [36]: _solve_as_rational(tan(x)-tan(pi/5), x, S.Reals)
Out[36]: ImageSet(Lambda(_n, _n*pi + pi/5), Integers)
```
Nice and easy.

In essence: solvers calling `solveset` for trig equations will often produce unusable results for simple equations, while solvers internally calling `_invert` fare better for these types of situation. That's unfortunate.

**1st conclusion: some trig equations *require* `_invert`**

Preliminary local testing shows that calling `_invert` in `_solve_trig` for equations containing only a single trig instance is indeed beneficial! (Fixes or improves upon https://github.com/sympy/sympy/issues/11218, https://github.com/sympy/sympy/issues/12340)

But there's a catch: `_invert` isn't perfect either. Examples:
```
In [41]: _invert(sin(x), 1, x, S.Reals)
Out[41]: (x, ImageSet(Lambda(_n, (-1)**_n*pi/2 + _n*pi), Integers))
```
**[fixed for solveset_real]** `_invert_real` tries to be too "clever" with its use of (-1)**n for sin and csc.
```
In [42]: _invert(sinh(x), 1, x, S.Reals)
Out[42]: (sinh(x), {1})
```
**[fixed for solveset_real]** Hyperbolic functions are not implemented, possibly because `_solve_trig` is supposed to handle all hyperbolic equations when called via `solveset`, but currently:
```
In [43]: solveset(sinh(x)-1, x, S.Reals)
Out[43]: ConditionSet(x, Eq((exp(2*x) - 2*exp(x) - 1)*exp(-x)/2, 0), Reals)
```
not useful...

`_invert_complex` has no code at all for handling trigonometric or hyperbolic functions, yet other solvers do call `_invert` if they're working with substitutions. The following is returning a `ConditionSet` because of this missing support for hyperbolic functions in `_invert_complex`:
```
In [1]: from sympy.solvers.solveset import _solve_as_poly, _solve_as_rational

In [2]: eq = expand((x + 1)**2).subs(x, sinh(x))

In [3]: _solve_as_poly(eq, x, S.Complexes)
```

**2nd conclusion: make `_invert_real` and `_invert_complex` as powerful as possible**

So if nobody tells me otherwise, I'll work on the following:
- [x] improve _invert_real
- [ ] improve _invert_complex (trig)
- [ ] improve _invert_complex (hyperbolic)
- [ ] call _invert in _solve_trig when appropriate (e.g. single trig instance)
- [ ] test cases

**Comment by gschintgen** [comment]
Related issues:
* This one currently hangs (v1.4 and master):
```
solveset(sec(x) - cos(2), x, S.Reals)
```
* As per its docstring `_invert`'s return value should contain "the information
    about the domain in which they are valid". This often entails a simple `.intersect(S.Reals)`, e.g. for `invert_real(exp(x), y, x)`. But:
```
In [32]: invert_real(sin(x), 2, x)
Out[32]:
⎛   ⎧    n                      ⎫⎞
⎜x, ⎨(-1) ⋅asin(2) + n⋅π | n ∊ ℤ⎬⎟
⎝   ⎩                           ⎭⎠
```

**Comment by oscargus** [comment]
Seems like there has been some (although little) progress since this was posted as `solveset(sinh(x)-1, x, S.Reals)` now returns

![image](https://user-images.githubusercontent.com/8114497/154773988-36e5817b-1a4b-4c41-8eca-43bd6e9c8d9c.png)

**Comment by gschintgen** [comment]
It's 2023 and in the meantime @smichr has implemented inversion of trig equations over the reals in  #25769. This leads to some very nice improvements!
I guess the next step is to improve `_invert_complex`.
With current master:
```
In [29]: solveset(tan(x)-tan(pi/5), x, Reals)
Out[29]: 
⎧      π │      ⎫
⎨n⋅π + ─ │ n ∊ ℤ⎬
⎩      5 │      ⎭
```
whereas without the domain specification it's still returning a huge unreadable mess.
Here are some of the other mentioned examples:
```
In [30]: solveset(sin(x) - sin(1), x, S.Reals)
Out[30]: {2⋅n⋅π + 1 │ n ∊ ℤ} ∪ {2⋅n⋅π - 1 + π │ n ∊ ℤ}

In [31]: solveset(sin(x) - sqrt(5)/3, x, S.Reals)
Out[31]: 
⎧            ⎛√5⎞ │      ⎫   ⎧            ⎛√5⎞     │      ⎫
⎨2⋅n⋅π + asin⎜──⎟ │ n ∊ ℤ⎬ ∪ ⎨2⋅n⋅π - asin⎜──⎟ + π │ n ∊ ℤ⎬
⎩            ⎝3 ⎠ │      ⎭   ⎩            ⎝3 ⎠     │      ⎭

```
NIce.

But there's always a but:
```
In [33]: solveset(sin(x) - 2, x, S.Reals)
Out[33]: {2⋅n⋅π + asin(2) │ n ∊ ℤ} ∪ {2⋅n⋅π + π - asin(2) │ n ∊ ℤ}
```
Over the reals this equation has no solutions, so there's some domain check missing. (I have some vague memory of my own experiments in which domain handling proved to be delicate, because adding the restrictions in `invert`'s framework using sets I quickly hit limitations of sympy's set handling.)

Equations involving hyperbolic trig functions could also see some improvements by using inversion instead of rewriting to exp:
```
In [39]: solveset(sinh(x)-cosh(2), x, Reals)
Out[39]: 
⎧   ⎛                  _______________    ⎞⎫
⎪   ⎜⎛     4⎞  -2     ╱        4    8   -2⎟⎪
⎨   ⎜⎝1 + ℯ ⎠⋅ℯ     ╲╱  1 + 6⋅ℯ  + ℯ  ⋅ℯ  ⎟⎬
⎪log⎜──────────── + ──────────────────────⎟⎪
⎩   ⎝     2                   2           ⎠⎭
```
Returning  `asinh(cosh(2))` would be faster and nicer.

**Comment by gschintgen** [comment]
On current master:
```
In [1]: solveset(sinh(x)-cosh(2), x, Reals)
Out[1]: {asinh(cosh(2))}
```
