### ISSUE TITLE
Use warns rather than raises to test for warnings

### ISSUE THREAD

**Issue by oscarbenjamin** [sympy/sympy#17364]
I get failures running the tests under pytest. These are from #17124 (@drybalka @Upabjojr) and are caused by using `raises` instead of `warns` to test for deprecation warnings.

The reason this is not seen under the standard test runner is that it turns warnings into exceptions. This is problematic because it means that the tests can't distinguish between raising an exception and emitting a warning. It also means that deprecated functions cannot be tested properly because the warning will always lead to an exception that aborts the function.
```
=============================================== FAILURES ================================================
__________________________________________ test_tensorsymmetry __________________________________________
[gw4] linux -- Python 3.6.3 /home/cosc/enojb/linux/current/sympy/36venv/bin/python

    def test_tensorsymmetry():
        with raises(SymPyDeprecationWarning):
>           tensorsymmetry([1]*2)
E           Failed: DID NOT RAISE <class 'sympy.utilities.exceptions.SymPyDeprecationWarning'>

sympy/tensor/tests/test_tensor.py:1970: Failed
____________________________________________ test_tensorhead ____________________________________________
[gw4] linux -- Python 3.6.3 /home/cosc/enojb/linux/current/sympy/36venv/bin/python

    def test_tensorhead():
        with raises(SymPyDeprecationWarning):
>           tensorhead('A', [])
E           Failed: DID NOT RAISE <class 'sympy.utilities.exceptions.SymPyDeprecationWarning'>

sympy/tensor/tests/test_tensor.py:1974: Failed
____________________________________________ test_TensorType ____________________________________________
[gw4] linux -- Python 3.6.3 /home/cosc/enojb/linux/current/sympy/36venv/bin/python

    def test_TensorType():
        with raises(SymPyDeprecationWarning):
            sym = TensorSymmetry.no_symmetry(1)
>           TensorType(sym, 2)

sympy/tensor/tests/test_tensor.py:1979: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

cls = <class 'sympy.tensor.tensor.TensorType'>, index_types = TensorSymmetry((), ((2),)), symmetry = 2
kw_args = {}

    def __new__(cls, index_types, symmetry, **kw_args):
        deprecate_TensorType()
>       assert symmetry.rank == len(index_types)
E       AttributeError: 'int' object has no attribute 'rank'

sympy/tensor/tensor.py:1487: AttributeError
```
The last failure here is possibly an example where the code that is not tested because of the deprecation exception may not work any more.

The correct way to do this is to use `warns_deprecated_sympy`:
```python
from sympy.utilities.pytest import warns_deprecated_sympy, ignore_warnings
from sympy.utilities.exceptions import SymPyDeprecationWarning

def test_deprecated_function():
    # Asserts that the warning is emitted.
    with warns_deprecated_sympy():
        deprecated_function(1)

    # Suppress the warning while still testing the function
    with ignore_warnings(SymPyDeprecationWarning):
        assert deprecated_function(1) == 1
        assert deprecated_function(2) == 2
```

I have already removed all examples of raises(Warning) from the codebase but they keep coming back which makes me wonder if there is some out of date documentation somewhere. Also it would probably be good to fix the test runner so that it no longer allows this.

**Comment by sameshl** [comment]
I would like to work on this. But looks like you have already replaced raises(Warning) from the codebase @oscarbenjamin. Can you guide me on how I could fix the test runner?

**Comment by oscarbenjamin** [comment]
Thanks for offering to work on this.

I did remove raises(Warning) from the codebase before but then a few examples of it have come back in sympy/tensor/tests/test_tensor.py from #17124. Those should be removed and possibly the tests using those need to be fixed as well.

For a simple fix to the test runner I suggest to modify raises so that if someone does `raises(SomeWarningClass)` then an error should be raised. That will stop contributors from accidentally using this in future.

A more complicated fix would be to make it so that warnings are not immediately turned into errors under the test runner. This is tricky because we do want unexpected warnings to cause test failures so something clever with warnings control would be needed. For now I suggest just do the simple fix I suggested above since it is a lot easier.

**Comment by sameshl** [comment]
Thanks for the explanation @oscarbenjamin. I looked into sympy/tensor/tests/test_tensor.py but I didn't find any instances of `raises(Warning)`. Correct me if I am wrong. Meanwhile, I am working on the test runner issue.

**Comment by oscarbenjamin** [comment]
It's `raises(SymPyDeprecationWarning)`. If you look at the failure message in the OP it shows the filenames and line numbers.

**Comment by sameshl** [comment]
@oscarbenjamin I have fixed the first three errors. Can you guide me on how I could go about the last one?

**Comment by oscarbenjamin** [comment]
I'm afraid I don't know the tensor module really.

What happens if you change it to warns? Does the test just fail then? If so what code would you use to show the failure?

**Comment by sameshl** [comment]
@oscarbenjamin I did not quite get you. I wanted to know how I could tackle the last error, ie, `sympy/tensor/tensor.py:1487: AttributeError`

**Comment by oscarbenjamin** [comment]
I think that the test is just incorrect: that's not how TensorType is used. It should be changed to the equivalent of:
```julia
In [35]: from sympy.tensor.tensor import TensorSymmetry, TensorType, tensorsymmetry, TensorIndexType                              

In [36]: sym2 = TensorSymmetry.fully_symmetric(2)                                                                                 

In [37]: Lorentz = TensorIndexType('Lorentz', dummy_fmt='L')                                                                      

In [38]: S2 = TensorType([Lorentz]*2, sym2)                                                                                       
/Users/enojb/current/sympy/sympy/sympy/core/decorators.py:38: SymPyDeprecationWarning: 

deprecate_TensorType has been deprecated since SymPy 1.5. Use
tensor_heads() instead. See
https://github.com/sympy/sympy/issues/17108 for more info.

  _warn_deprecation(wrapped, 3)
```

**Comment by drybalka** [comment]
@oscarbenjamin is right, the test is incorrect, that's my fault. I guess I did not notice that because of the deprecation. It should have been something like what was suggested:
```
def test_TensorType():
    with raises(SymPyDeprecationWarning):
        sym = TensorSymmetry.fully_symmetric(2)
        Lorentz = TensorIndexType('Lorentz')
        S2 = TensorType([Lorentz]*2, sym2)
```

**Comment by sameshl** [comment]
@drybalka I see. I can update that test. Btw, how could I go about trying to fix 

```
cls = <class 'sympy.tensor.tensor.TensorType'>, index_types = TensorSymmetry((), ((2),)), symmetry = 2
 kw_args = {}
 
     def __new__(cls, index_types, symmetry, **kw_args):
         deprecate_TensorType()
      assert symmetry.rank == len(index_types)
 E       AttributeError: 'int' object has no attribute 'rank'
 
 sympy/tensor/tensor.py:1487: AttributeError
```

**Comment by oscarbenjamin** [comment]
That's the test that failed because it is incorrect. @drybalka suggested a fixed version of the test above.
