### ISSUE TITLE
test and doctest scripts do not work from other directories

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#17369]
The `path_hack` in the `test` and `doctest` scripts is supposed to make it so that something like

```
cd bin
./doctest
```

still tests the git SymPy. 

But the problem is that the tests and doctests run in a subprocess by default, which does not inherit the sys.path. So the above will test the globally installed SymPy unless `--no-subprocess` is used. 

The simplest solution would be for `path_hack` to set PYTHONPATH in os.environ so that it gets inherited. Or maybe it should be done in the run_tests_in_subprocess function, I'm not sure.

**Comment by asmeurer** [comment]
Thinking about it, it should be run_tests_in_subprocess's responsibility to make sure the subprocess test runner tests the same sympy that it is called from.

**Comment by sameshl** [comment]
I would like to work on this. I was not able to find where ` run_tests_in_subprocess` was defined. Can you help me out?

**Comment by asmeurer** [comment]
I remembered the name wrong. It's `run_in_subprocess_with_hash_randomization` in `sympy.utilities.runtests`.

**Comment by Soniyanayak51** [comment]
Hi,
Beginner here. Would like to work on this issue. Any leads would help. This would be my first pr.
Thanks in advance.

**Comment by asmeurer** [comment]
We need to make it so that run_in_subprocess_with_hash_randomization in sympy.utilities.runtests starts the subprocess Python in such a way so that when it import sympy, it imports the same sympy. I'm not sure what the best way to do this is. Probably the easiest way is to set the PYTHONPATH environment variable in the subprocess call, but you might Google around to see if there is a better way to do it.
