### ISSUE TITLE
Reorganise ComplexRegion

### ISSUE THREAD

**Issue by oscarbenjamin** [sympy/sympy#17370]
This comes from working on #17280.

ComplexRegion looks a bit of a mess to me. If I summarise briefly the class structure it looks like:
```python
class ImageSet(Set):
    ...

class ComplexRegion(Set):
    def __new__(cls, sets, polar=True):
        if polar == True:
            obj = ImageSet.__new__(cls, Lambda((r, theta), r*(cos(theta) + I*sin(theta))), sets)
        elif polar == False:
            obj = ImageSet.__new__(cls, Lambda((x, y), x + I*y), sets)
        obj._sets = sets
        obj._polar = polar
        return obj

    @property
    def args(self):
        return (self._sets, self._polar)
```
This makes ComplexRegion something of a pseudo-subclass of ImageSet. It uses `ImageSet.__new__(cls, ...)` with `cls=ComplexRegion` although there is no inheritance relationship between them. The args are emulated over the top using a property that is separate from the underlying _args seen by methods of `Basic`:
```julia
In [2]: S1 = ComplexRegion(Interval(0, 1)**2)                                                                                     

In [3]: S1.args                                                                                                                   
Out[3]: 
⎛      2       ⎞
⎝[0, 1] , False⎠

In [4]: S1._args                                                                                                                  
Out[4]: 
⎛                        2⎞
⎝(x, y) ↦ x + y⋅ⅈ, [0, 1] ⎠
```
We also have in `.args` a boolean parameter to distinguish between polar and rectangular form (those should just be separate classes).

One way to clean this up would be:
```python
class ImageSet(Set):
    ...

class ComplexRegion(ImageSet):
    ...

class PolarComplexRegion(ComplexRegion):
   ...

class RectangularComplexRegion(ComplexRegion):
   ...
```
Then for backwards compatibility `ComplexRegion(..., polar=True/False)` can return instances of `PolarComplexRegion` or `RectangularComplexRegion`.

On the other hand I can't really tell what the purpose of ComplexRegion is. It is basically just a weird wrapper around ImageSet so why not just use ImageSet directly?

Also after a quick grep I can't tell if ComplexRegion is actually used anywhere. Do we even need this class?

**Comment by asmeurer** [comment]
It is used for `S.Complexes`, which is defined as Reals x Reals. Actually this is a bit problematic because it does a lot of computation in the initializer, which is done at import time due to Complexes being installed on the SingletonRegistry.

**Comment by asmeurer** [comment]
Actually SingletonRegistry is smart enough to not initialize the classes until they are first accessed, but it is accessed at import time because of https://github.com/sympy/sympy/blob/7b388734060b2004d1bb300c75a5657db4ac8554/sympy/solvers/solveset.py#L94.

**Comment by oscarbenjamin** [comment]
When I ask about the purpose of the class I mean because we can just use an ImageSet for everything it does. S.Complexes can just as easily be defined as:
```julia
In [3]: ImageSet(Lambda((x, y), x+I*y), S.Reals, S.Reals)
Out[3]: {x + ⅈ⋅y | x ∊ ℝ , y ∊ ℝ}
```
If that doesn't work for some reason then maybe ImageSet should be improved.

I do see the value in having Complexes as a separate class but if it is to be implemented over ImageSet then we can do that directly without the awkward middleman ComplexRegion class.

**Comment by asmeurer** [comment]
And even if you remove those the instance is created in `__init__.py` so that `sympy.Complexes` works. 

I'm guessing we could get a reasonable import time speedup if we just made Complexes a standalone class that did nothing when initialized.

**Comment by asmeurer** [comment]
I agree that the logic of as much as possible should be in ImageSet. The only value I see of having things on top of that is for nicer printing.
