### ISSUE TITLE
Incorrect results given by some limit expressions

### ISSUE THREAD

**Issue by ArighnaIITG** [sympy/sympy#17380]
There are some limit expressions which give incorrect results. For example -

```
>>> from sympy import *
>>> x = symbols('x')
>>> limit(x*(((x + 1)**2 + 1)/(x**2 + 1) - 1), x, oo)
0
```
while the answer actually should be `2`.

Also,

```
>>> from sympy import *
>>> x = symbols('x')
>>> limit(x*(-1 + (x + log(x + 1) + 1)/(x + log(x))), x ,oo)
0
```
while the actual answer should be `1`.

**Comment by oscarbenjamin** [comment]
Removing the milestone as this is a longstanding issue and not a regression.

**Comment by sachin-4099** [comment]
can be closed in favour of: https://github.com/sympy/sympy/pull/18340
