### ISSUE TITLE
ImageSet evalf?

### ISSUE THREAD

**Issue by gschintgen** [sympy/sympy#17382]
I may be missing something obvious (if so feel free to enlighten me and close this issue), but I find it quite difficult to apply numeric evaluation (`evalf`) to the complicated ImageSets that `solveset` sometimes returns for trigonometric equations.

Here's a modestly sized example:
```
In [1]: solveset(2*cos(x)*cos(2*x) - 1, x, S.Reals)
Out[1]:
⎧              ⎛   ________________________________________________________⎞        ⎫   ⎧              ⎛   ______________________________
⎪              ⎜  ╱     3 ___             2/3      2/3      3 ____________ ⎟        ⎪   ⎪              ⎜  ╱     3 ___             2/3
⎪              ⎜╲╱  - 2⋅╲╱ 2 ⋅(67 + 9⋅√57)    + 8⋅2    + 11⋅╲╱ 67 + 9⋅√57  ⎟        ⎪   ⎪              ⎜╲╱  - 2⋅╲╱ 2 ⋅(67 + 9⋅√57)    + 8
⎨2⋅n⋅π + 2⋅atan⎜───────────────────────────────────────────────────────────⎟ | n ∊ ℤ⎬ ∪ ⎨2⋅n⋅π - 2⋅atan⎜─────────────────────────────────
⎪              ⎜                        6 ____________                     ⎟        ⎪   ⎪              ⎜                        6 _______
⎪              ⎝                      3⋅╲╱ 67 + 9⋅√57                      ⎠        ⎪   ⎪              ⎝                      3⋅╲╱ 67 + 9
⎩                                                                                   ⎭   ⎩

__________________________⎞              ⎫
  2/3      3 ____________ ⎟              ⎪
⋅2    + 11⋅╲╱ 67 + 9⋅√57  ⎟              ⎪
──────────────────────────⎟ + 2⋅π | n ∊ ℤ⎬
_____                     ⎟              ⎪
⋅√57                      ⎠              ⎪
                                         ⎭
```
Neither `.n()`, nor `N()` or `evalf()` can be used. So I tried applying `subs`, `replace`, `xreplace` and after some struggling I figured this out:
```
In [1]: solveset(2*cos(x)*cos(2*x) - 1, x, S.Reals)
Out[1]:
⎧              ⎛   ________________________________________________________⎞        ⎫   ⎧              ⎛   ______________________________
⎪              ⎜  ╱     3 ___             2/3      2/3      3 ____________ ⎟        ⎪   ⎪              ⎜  ╱     3 ___             2/3
⎪              ⎜╲╱  - 2⋅╲╱ 2 ⋅(67 + 9⋅√57)    + 8⋅2    + 11⋅╲╱ 67 + 9⋅√57  ⎟        ⎪   ⎪              ⎜╲╱  - 2⋅╲╱ 2 ⋅(67 + 9⋅√57)    + 8
⎨2⋅n⋅π + 2⋅atan⎜───────────────────────────────────────────────────────────⎟ | n ∊ ℤ⎬ ∪ ⎨2⋅n⋅π - 2⋅atan⎜─────────────────────────────────
⎪              ⎜                        6 ____________                     ⎟        ⎪   ⎪              ⎜                        6 _______
⎪              ⎝                      3⋅╲╱ 67 + 9⋅√57                      ⎠        ⎪   ⎪              ⎝                      3⋅╲╱ 67 + 9
⎩                                                                                   ⎭   ⎩

__________________________⎞              ⎫
  2/3      3 ____________ ⎟              ⎪
⋅2    + 11⋅╲╱ 67 + 9⋅√57  ⎟              ⎪
──────────────────────────⎟ + 2⋅π | n ∊ ℤ⎬
_____                     ⎟              ⎪
⋅√57                      ⎠              ⎪
                                         ⎭

In [2]: a = Wild('a')

In [3]: _1.replace(atan(a), lambda a: atan(a).evalf())
Out[3]: {2⋅n⋅π + 0.485061711258717 | n ∊ ℤ} ∪ {2⋅n⋅π - 0.485061711258717 + 2⋅π | n ∊ ℤ}
```
But more complicated results need multiple such `.replace` calls.

I also tried extracting the Lambda's expression in order to apply evalf() (which worked if IIRC), but didn't follow through with recreating a new simplified lambda in order to substitute it back in.

So: am I missing an obvious alternative? If not, I think it could be worthwile to make ImageSets compatible with `evalf`. (Proposal: apply evalf to the lambda's expression, but not the baseset? Yes, `pi` would then also be evalfed, which is unfortunate.)

I have other examples (for S.Complexes, will file a PR) where the solution set is valid, complete and correct. It's rather nice when `evalf`ed, but the exact solution is a total mess spanning pages of screen output.

**Comment by gschintgen** [comment]
Minor update: with current master, calling `.evalf()` on the solveset result no longer raises an AttributeError. That's good. (Probably thanks to set evalf work by @Maelstrom6 ).
But the set is left unevaluated nonetheless.

(I'm not complaining, just documenting the current state.)

**Comment by Maelstrom6** [comment]
I'll have a look into it sometime this week. Sorry that this issue got left out in the cold.

**Comment by Maelstrom6** [comment]
I'm not going to make a PR for this because we might eventually change the whole `evalf` situation (#20479). I'm not sure how happy @oscarbenjamin will be with adding more mess with `evalf` in the mean time. 

But you can add the following to your personal fork:

In `sympy/core/expr.py`, add the following function to the `Expr` class:
```python
def _eval_evalf(self, prec): 
     return self.func(*[arg._evalf(prec) for arg in self.args]) 
```

In `sympy/core/function.py`, add the following function to the `Lambda` class:
```python
def _eval_evalf(self, prec):
    from sympy.core.evalf import prec_to_dps
    return self.func(self.args[0], self.args[1].evalf(n=prec_to_dps(prec)))
```

This is kind of a quick-fix, but I think it should work for just about everything.

**Comment by oscarbenjamin** [comment]
Until #20493 is merged adding this to `Lambda` seems like a reasonable fix.

It looks like #20493 has stalled. If someone could help out with that (or take over) then that would be good.

**Comment by sidhu1012** [comment]
> Until #20493 is merged adding this to `Lambda` seems like a reasonable fix.
> 
> It looks like #20493 has stalled. If someone could help out with that (or take over) then that would be good.

Actually I'm working on it but I'm having exams these days so I'm not being able to work much on it.
