### ISSUE TITLE
Add more SciPy functions to code printer

### ISSUE THREAD

**Issue by oscargus** [sympy/sympy#17396]
Here is a list of special functions supported in SciPy: https://docs.scipy.org/doc/scipy/reference/special.html

Many of them are not supported in the SciPyPrinter and should be added.

**Comment by asmeurer** [comment]
For each we also need to make sure to check that the functions are defined in the same way. Sometimes one function will be normalized and the other won't, or the argument order may be different.

**Comment by oscargus** [comment]
It also makes sense both to test the text output and the function of the lambdified version (numerical results). See e.g. #17394 for an example of what the code may look like (note that there is a dictionary if it is just a matter of function names and the arguments are in the same direction etc), and what tests may look like, both using `print` and `lambdify`.

**Comment by Psycho-Pirate** [comment]
I would like to work on this issue, please guide me through this!

**Comment by m93a** [comment]
Bump.

**Comment by mitanshu001** [comment]
I would like to work on this issue

**Comment by m93a** [comment]
@mitanshu001 you can use my PR as a tutorial :) Plus I haven't had time to add tests yet, but I'll do it soon.

**Comment by sylee957** [comment]
You should take a look at `pycode.py` and `SciPyPrinter`.

**Comment by i-m-vivek** [comment]
Can I work on this issue?

**Comment by shubham-khantwal** [comment]
i would like to work on it . Though i am completely beginner i believe trying is better than doing nothing.
can somebody guide me ?  and what does module_format implies ? i see it a lot of time as self._module_format('scipy.sparse.coo_matrix')

**Comment by asmeurer** [comment]
You should look for the definition of the function https://github.com/sympy/sympy/blob/9fa2d4aa4683d24937f42d96f7fba4333ee6067a/sympy/printing/pycode.py#L122

It looks like it is related to a printer setting which controls whether it is printed as scipy.sparse.coo_matrix or just coo_matrix.

**Comment by m93a** [comment]
As I mentioned, I believe that [the PR I've done](https://github.com/sympy/sympy/pull/18185/files) is pretty much self-explanatory in terms of what you need to do.

**Comment by shubham-khantwal** [comment]
Thank you for guiding me . shubham From: Michal GrňoSent: 07 March 2020 03:20 AMTo: sympy/sympyCc: SHUBHAM KHANTWAL; CommentSubject: Re: [sympy/sympy] Add more SciPy functions to code printer (#17396) As I mentioned, I believe that the PR I've done is pretty much self-explanatory in terms of what you need to do.—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.
