### ISSUE TITLE
How to simplify 'a*c+b*c+d' ?

### ISSUE THREAD

**Issue by CloudTsang** [sympy/sympy#17422]
`sympy.simplify(expr)` can simplify `a*c+b*c` to `(a+b)*c`.
But not working on `a*c+b*c+d` and `a*c+b*c+d*e` and those that can only be partly simplified to `A*B`.
Is there any way to get `(a+b)*c+d = sympy.simplify(a*c+b*c+d)`?

Sorry for my poor English and hope for your responses!

**Comment by ethankward** [comment]
You can call `collect(a*c + b*c + d, c)`. General questions are better asked on the Google Groups site (https://groups.google.com/forum/#!forum/sympy) rather than in the issue tracker.

**Comment by asmeurer** [comment]
See also https://github.com/sympy/sympy/issues/11869
