### ISSUE TITLE
potential problem with `_is_connected`

### ISSUE THREAD

**Issue by smichr** [sympy/sympy#17420]
In line 568 the `v.is_Relational` should be replaced with `isinstance(v, Relational)` because if any v evaluates it will be a bool not a Boolean (and, thus, will not have the `is_Relational` attribute). I did get this to trigger/fail but am not sure, now, how I did so.

https://github.com/sympy/sympy/blob/9315cc8172f8758c10cb239fb457853b4eee2870/sympy/functions/elementary/miscellaneous.py#L567-L581

**Comment by oscargus** [comment]
I think (cannot dig up the thread right now), that the "correct" solution would be to have all relational return `S.true` and `S.false`. Clearly, much more tedious though...

In the light of this, is there any use of `is_Relational`? I.e. are there cases where it can be guaranteed to not have been evaluated?

**Comment by oscarbenjamin** [comment]
Do they not return S.true/S.false?
```julia
In [51]: x>0                                                                                                                      
Out[51]: x > 0

In [52]: (x>0).subs(x, 1)                                                                                                         
Out[52]: True

In [53]: type(_)                                                                                                                  
Out[53]: sympy.logic.boolalg.BooleanTrue

In [58]: (x>0).subs(x, 1).is_Relational                                                                                           
Out[58]: False
```

**Comment by smichr** [comment]
Ah...so something I did sent unsympified values to Max and, apparently Max did not sympify them before running them through this routine so smthng like 1<2 evaluated to True rather than S.true.

**Comment by smichr** [comment]
Not being able to reproduce this, and seeing that the 2nd line of `MinMaxBase.__new__` sympifies args, I am closing this.
