### ISSUE TITLE
Incorrect evaluation of acos(-I + acosh(cosh(cosh(1) + I)))

### ISSUE THREAD

**Issue by ethankward** [sympy/sympy#17421]
`-I + acosh(cosh(cosh(1) + I))` should be equivalent to `cosh(1)`, and this can be confirmed:

```
>>> N(-I + acosh(cosh(cosh(1) + I)))
1.54308063481524 + 0.e-20*I
>>> N(cosh(1))
1.54308063481524
```

Taking `acos`, the sign gets flipped:

```
>>> a = -I + acosh(cosh(cosh(1) + I))
>>> N(acos(a))
3.60377845017333e-22 - 1.0*I
>>> N(acos(cosh(1)))
1.0*I
```

Trying with explicit evaluation:

```
>>> a = -I + acosh(cosh(cosh(1) + I))
>>> N(acos(a))
3.60377845017333e-22 - 1.0*I
>>> N(a)
1.54308063481524 + 0.e-20*I
>>> acos(_)
1.15320910405546e-20 - 1.0*I
>>> acos(1.54308063481524 + 0.e-20*I)
0.999999999999997*I
>>> acos(1.54308063481524)
0.999999999999997*I
```

**Comment by ethankward** [comment]
Actually, I think this is more of a mpmath issue- will close unless anyone feels otherwise.

**Comment by oscarbenjamin** [comment]
What makes you think it is an issue with mpmath rather than sympy?

**Comment by ethankward** [comment]
Never mind. I guess the issue is that any positive imaginary part no matter how small is going to cause the sign to flip from `I` to `-I`.

**Comment by smichr** [comment]
perhaps related to #6137? See this [comment](https://github.com/sympy/sympy/issues/6137#issuecomment-37004430).

**Comment by oscarbenjamin** [comment]
Maybe evalf should have some understanding of branch cuts at least so that it doesn't report excess precision near to them.

**Comment by ethankward** [comment]
Or maybe it would help if `a = -I + acosh(cosh(cosh(1) + I))` could be recognized as real.

**Comment by ethankward** [comment]
Or maybe just any way to simplify `acosh(cosh(x))`? As far as I know there's nothing in `trigsimp` that deals with inverse compositions.
