### ISSUE TITLE
Inconsistency with summation order and empty sequence

### ISSUE THREAD

**Issue by oscargus** [sympy/sympy#17424]
```
In [9]: Sum(1, (x, 6, 5), (y, -oo, oo)).doit()
Out[9]: 0

In [10]: Sum(1, (y, -oo, oo), (x, 6, 5)).doit()
Out[10]: NaN
```

The reason is that summing over `(x, 6, 5)` leads to 0 as it represents an empty summation range. But summing NaN over an empty summation range is apparently still NaN. Should it be NaN? NaN*0 = 0, so maybe it should be 0?
￼

**Comment by oscarbenjamin** [comment]
For finite a, b these sums are both zero:
```julia
In [17]: a, b = symbols('a, b', finite=True)                                                                                      

In [18]: Sum(1, (y, a, b), (x, 6, 5)).doit()                                                                                      
Out[18]: 0

In [19]: Sum(1, (x, 6, 5), (y, a, b)).doit()                                                                                      
Out[19]: 0
```
So taking the limit as a, b go to +-infinity should give zero in both cases.

**Comment by oscargus** [comment]
Good to have it confirmed, thanks. The same issue does not arise for Products (both combinations gives the expected 1). I'll try to sort it out.
