### ISSUE TITLE
Test that optional dependencies are tested on Travis

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#17428]
We have an external dependency build on Travis that runs with all the optional dependencies installed. But by default, these tests are skipped if the dependencies aren't installed, so we don't know if the optional dependency build is actually testing the optional dependencies. If they aren't installed correctly, they would be silently skipped, and no one would notice without inspecting the build log.

We should have a script in `bin/` that just imports all the optional dependencies, so that we can be sure that they really are installed.

**Comment by asmeurer** [comment]
A better idea would be to hook `import_module` in that run so that it raises ImportError on failure. That way we know no external imports are silently skipped.

**Comment by oscarbenjamin** [comment]
I think it would be best to adjust the skip code so that it doesn't skip when `ON_TRAVIS`. Everywhere we have:
```
    if numpy is None:
        skip('Numpy is not installed')
```
We should really have a decorator that checks instead like doctest_depends_on. That decorator could raise if it would otherwise skip the test on Travis.

**Comment by asmeurer** [comment]
Maybe we can check if the `OPTIONAL_DEPENDENCIES` environment variable is set in `import_module` and raise ImportError in that case. 

I'm not sure about skip, since tests are also skipped for other reasons, some which may be legitimate on Travis. Actually some tests are specifically skipped on Travis.

**Comment by oscarbenjamin** [comment]
> Actually some tests are specifically skipped on Travis.

If you mean the "too slow for Travis" tests then we should also git rid of that. Those tests should just be skipped by default in all contexts using `@skip`.

**Comment by oscarbenjamin** [comment]
The problem with calling skip from inside the test function is that there's no way to control the skipping logic from outside. Hence this issue but hence also the fact that I can't ask the test runner to run the slow tests but *not* the ones that are too slow for travis.

**Comment by oscargus** [comment]
Another reason is that `pyglet` require a display. I think that I may have been able to sort that out though, without skip or blacklisting (except for the doctests), in #17362. I should need a few more runs with it though as it seems like `xvfb` doesn't really start at the moment.

**Comment by oscarbenjamin** [comment]
We could have a `@not_on_travis` decorator for these things. Then when doing local testing it would be possible to ask a test runner to run only the tests that would be run on Travis.

**Comment by asmeurer** [comment]
I also think skip() is not used in every instance where an optional dependency is used, but this is actually a good opportunity to figure out a standard way to do this, and document it. I know some of the GSoC students had a difficult time working out the proper way to import things like clang and lfortran.

**Comment by Arpan612** [comment]
@asmeurer Sir, I have worked out an algorithm to import all optional dependencies, however, I am not able to code it. Could you please give me an example where similar work has been done?

> We have an external dependency build on Travis that runs with all the optional dependencies installed. But by default, these tests are skipped if the dependencies aren't installed, so we don't know if the optional dependency build is actually testing the optional dependencies. If they aren't installed correctly, they would be silently skipped, and no one would notice without inspecting the build log.

> We should have a script in `bin/` that just imports all the optional dependencies, so that we can be sure that they really are installed.

**Comment by ekdnam** [comment]
Hello all! Can I work on this issue?

**Comment by oscarbenjamin** [comment]
I think that the first thing needed is to ensure that all skipping logic is controlled by decorators. Any functions that are supposed to be skipped in any situation should be marked with decorators indicating the reason for skipping so that the test script can decide to error in a situation where it expects not to skip any tests (e.g. in the optional dependency build). That means auditing all uses of skip throughout the codebase. Different versions of the skipping decorators would be needed for when running under pytest or under the sympy test runner.

**Comment by ekdnam** [comment]
Can you give some examples of the functions that would be skipped?

**Comment by Bhavna777** [comment]
I would like to work on this issue. Please guide me as to how to proceed.
@asmeurer @oscarbenjamin

**Comment by eagleoflqj** [comment]
Bye travis.
