### ISSUE TITLE
ProductSet of 0 or 1 sets

### ISSUE THREAD

**Issue by oscarbenjamin** [sympy/sympy#17458]
The following inconsistency demonstrates a potential flaw in the definition of ProductSet:
```julia
In [10]: [(1,)*n in ProductSet(*(Reals,)*n) for n in range(10)]                                                                   
Out[10]: [False, False, True, True, True, True, True, True, True, True]
```
There are two problems:

1. The empty ProductSet should not be the empty set. It should be the set containing only the empty tuple `FiniteSet(())`:
https://en.wikipedia.org/wiki/Empty_product#Nullary_Cartesian_product
2. A ProductSet of one set evaluates to the underlying set meaning that there is no way to represent the set of 1-tuples of elements from the underlying set. I think this evaluation should be disallowed so that ProductSet(Reals) is the set of 1-tuples of real numbers. This problem doesn't have a direct mathematical analogue since this ambiguity around 1-tuples is common in mathematical literature. Working in Python though we need to have well-defined behaviour for this - looking through ImageSet and ProductSet it is clear that they cannot be fixed without having more precise programmatic definitions. One implication of this change would be that `Reals != Reals**1`.

**Comment by asmeurer** [comment]
> This problem doesn't have a direct mathematical analogue since this ambiguity around 1-tuples is common in mathematical literature. 

Depends on what literature. If you get low enough in the foundations, there are people who make the proper distinctions between sets that are equal and sets that are isomorphic. Even something like (AxB)xC vs. Ax(BxC) are considered by some. In fact AxA isn't strictly the same thing as A^2, the latter being the set of functions from 2 (={1, 2}) to A. I'm not sure if we should make such a distinction in SymPy's set module. 

However, I do think it's a good idea for ProductSet to always be a set of tuples (your point 2), so that indexing is uniform.

**Comment by oscarbenjamin** [comment]
> Even something like (AxB)xC vs. Ax(BxC) are considered by some.

I actually think that we should make that distinction in SymPy. Currently ProductSets are flattened which leads to inconsistent results. Consider how it should work:
```julia
In [13]: S1 = Reals                                                                                                               

In [14]: S2 = Integers                                                                                                            

In [15]: x1 = pi                                                                                                                  

In [16]: x2 = 3                                                                                                                   

In [17]: x1 in S1                                                                                                                 
Out[17]: True

In [18]: x2 in S2                                                                                                                 
Out[18]: True

In [19]: (x1, x2) in S1 * S2                                                                                                      
Out[19]: True
```
Now see where it goes wrong:
```julia
In [20]: S3 = S1 * S2                                                                                                             

In [21]: x3 = (x1, x2)                                                                                                            

In [22]: x3 in S3                                                                                                                 
Out[22]: True

In [23]: (x3, x3) in S3 * S3                                                                                                      
Out[23]: False    # <------------------ should be True
```

**Comment by asmeurer** [comment]
It's probably good, though there should be easy ways to flatten them. Python distinguishes between nested and flattened tuples, so I guess we should too. 

But I think A^n should be considered as a shortcut for `Ax...xA` (flattened) if `n` is an integer. I think for an actual set of functions (whatever that would mean for SymPy sets) we should have a separate object (such things become more relevant if you consider infinite products of sets).

**Comment by oscarbenjamin** [comment]
There could be a ProducSet.flatten() method. I wonder if there could be something more general that is potentially more useful like a reshape method: `(S1*(S2*S3)).reshape(((None, None), None))->((S1*S2)*S3)` (the Nones would be ignored so it would always be possible to reshape using an object of the desired shape). We could also have flatten since it would be straightforward to implement on top of reshape.
