### ISSUE TITLE
a complex symbol should be assumed to be finite

### ISSUE THREAD

**Issue by laolux** [sympy/sympy#17480]
According to the documentation of the ask method of the assumption module `Note that every complex number is finite.` However, this is not the case:

    import sympy

    a = sympy.symbols('a', complex=True)
    print('show the assumptions of a: ',a.assumptions0)
    print('is a complex? ',sympy.ask(sympy.Q.complex(a)))
    print('is a finite? ',sympy.ask(sympy.Q.finite(a)))

So to be consistent with the documentation a complex symbol should be assumed finite. Or the documentation should be changed.

Personally I prefer a complex number being finite, as I would usually define a complex number `c` as `c=a+ib` with both `a` and `b` real and thus finite. But I acknowledge that this might break existing code and thus a change of documentation instead might be preferable.

**Comment by gschintgen** [comment]
This has been changed in 1.5. See https://github.com/sympy/sympy/wiki/Release-Notes-for-1.5
```
In [34]: a = Symbol('a', complex=True)

In [35]: ask(Q.finite(a))
Out[35]: True                                                                                                                  
In [36]: a.is_finite
Out[36]: True
```
