### ISSUE TITLE
Lambda function hash is incorrect with canonical variables

### ISSUE THREAD

**Issue by oscarbenjamin** [sympy/sympy#17498]
Lambad functions with different variables compare equal and have the same hash:
```julia
In [3]: l1 = Lambda(x, x**2)                                                                                                      

In [4]: l2 = Lambda(y, y**2)                                                                                                      

In [5]: l1                                                                                                                        
Out[5]: 
     2
x ↦ x 

In [6]: l2                                                                                                                        
Out[6]: 
     2
y ↦ y 

In [7]: l1 == l2                                                                                                                  
Out[7]: True

In [8]: hash(l1)                                                                                                                  
Out[8]: 2981442439609583076

In [9]: hash(l2)                                                                                                                  
Out[9]: 2981442439609583076
```
This works because `__eq__` substitutes the variables between the functions and `_hashable_content` uses `.xreplace(self.canonical_variables)`:
```julia
In [10]: l1.xreplace(l1.canonical_variables)                                                                                      
Out[10]: 
       2
_0 ↦ _0 
```
However if the Lambda already has canonical variables then this fails:
```julia
In [11]: l3 = l1.xreplace(l1.canonical_variables)                                                                                 

In [12]: l3 == l1                                                                                                                 
Out[12]: True

In [13]: hash(l3)                                                                                                                 
Out[13]: -5452272484929813656  # <--------- The hash is different!

In [14]: l3.xreplace(l3.canonical_variables)          # This is why                                                                            
Out[14]: 
       2
_1 ↦ _1 
```
This seems like a deficiency in canonical_variables: it does not guarantee to result in canonical variables. I looked and canonical_variables doesn't seemed to be used anywhere apart from in `Lambda` and in `Basic.as_dummy`. The `as_dummy` method seems to be used only in `Integrals`.

Should `canonical_variables` be changed? This behaviour matches the docstring but isn't useful for canonicalisation as is the intended purpose in Lambda.

**Comment by oscarbenjamin** [comment]
I think the problem here is that Lambda overrides `__eq__` in order to have:
```python
>>> Lambda(x, x**2) == Lambda(y, y**2)                                                                                        
True
```
Other objects with bound variables don't do this e.g.:
```python
>>> Integral(x, (x, y)) == Integral(z, (z, y))                                                                                
False
```
Because of that the `as_dummy()` method doesn't work for Lambda:
```python
In [8]: Integral(x, (x, y)).as_dummy()                                                                                            
Out[8]: 
y         
⌠         
⎮ _0 d(_0)
⌡         
          
In [9]: Lambda(x, x**2).as_dummy()                                                                                                
Out[9]: 
     2
x ↦ x 
```
This fails because `as_dummy()` uses `replace` and `replace` checks whether the new expression is equal to the old expression:
https://github.com/sympy/sympy/blob/30c90c3c234488fa0eb36fa4adc657167baa359e/sympy/core/basic.py#L1521
Here the `Lambda.__eq__` method intervenes and claims that the replaced expression is equal to the original one so `replace` gives up and returns the old expression.

This invalidates these tests:
https://github.com/sympy/sympy/blob/30c90c3c234488fa0eb36fa4adc657167baa359e/sympy/core/tests/test_basic.py#L278-L282
The as_dummy doesn't do anything here since:
```julia
In [11]: Lambda(x, x+1) == Lambda(_0, _0+1) 
Out [11]: True

In [13]: Lambda(x, x+1).as_dummy()                                                                                                
Out[13]: x ↦ x + 1
```
The only conclusion I can come to here is that it is a bad idea for Basic subclasses to redefine `__eq__`. They should accept the conclusions of `Basic` that objects with unequal args are unequal.

The original problem with `as_dummy` remains for Integral and other classes though. If the object already has canonicalised variables then canonical_variables/as_dummy forces it to have non-canonical variables:
```julia
In [17]: I.as_dummy()                                                                                                             
Out[17]: 
y         
⌠         
⎮ _0 d(_0)
⌡         
          
In [18]: I.as_dummy().as_dummy()                                                                                                  
Out[18]: 
y         
⌠         
⎮ _1 d(_1)
⌡         
          
In [19]: I.as_dummy().as_dummy() == I.as_dummy()                                                                                  
Out[19]: False
```
This causes `dummy_eq` (which uses `as_dummy`) to fail:
```julia
In [20]: I.dummy_eq(I)                                                                                                            
Out[20]: True

In [21]: I.dummy_eq(I.as_dummy())                                                                                                 
Out[21]: False
```

**Comment by oscarbenjamin** [comment]
I think we need to make it so that `Lambda` functions with different variables compare unequal i.e.:
```python
>>> Lambda(x, x**2) == Lambda(y, y**2)
False
```
 Any opinions?

Running through the test suite this comparison behaviour doesn't actually seem to be used in anything (although it is tested).

**Comment by asmeurer** [comment]
I always thought Lambda's approach to dummy variables was a bad one. I recall some older issues discussing this.

**Comment by asmeurer** [comment]
See the discussions at https://github.com/sympy/sympy/issues/5539 and the cross referenced issues to it.

**Comment by asmeurer** [comment]
Also I meant "bound variables", not "dummy variables".

**Comment by oscarbenjamin** [comment]
I think the most important thing that I've realised from looking closely at this in the case of Lambda is that there don't seem to be any benefits to this canonical comparison. AFAICT there is no code anywhere that does anything *useful* with Lambda functions as a result of this behaviour.

**Comment by oscarbenjamin** [comment]
Connected to the above problems with Lambda is the fact that `.replace` doesn't work for `ImageSet`:
```julia
In [12]: ImageSet(Lambda(x, x**2), Interval(0, 1))                                                                                
Out[12]: 
⎧ 2             ⎫
⎨x  | x ∊ [0, 1]⎬
⎩               ⎭

In [13]: ImageSet(Lambda(x, x**2), Interval(0, 1)).xreplace({x:y})                                                                
Out[13]: 
⎧ 2             ⎫
⎨y  | y ∊ [0, 1]⎬
⎩               ⎭

In [14]: ImageSet(Lambda(x, x**2), Interval(0, 1)).replace(x, y)                                                                  
Out[14]: 
⎧ 2⎫
⎨y ⎬
⎩  ⎭

In [15]: ImageSet(Lambda(x, x**2), Interval(0, 1)).replace(lambda e: x, lambda e: e is y)                                         
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-15-f45f145951ac> in <module>
----> 1 ImageSet(Lambda(x, x**2), Interval(0, 1)).replace(lambda e: x, lambda e: e is y)

~/current/sympy/sympy/sympy/core/basic.py in replace(self, query, value, map, simultaneous, exact)
   1537             return expr
   1538 
-> 1539         rv = bottom_up(self, rec_replace, atoms=True)
   1540 
   1541         # restore original expressions for Dummy symbols

~/current/sympy/sympy/sympy/simplify/simplify.py in bottom_up(rv, F, atoms, nonbasic)
   1146             args = tuple([bottom_up(a, F, atoms, nonbasic) for a in args])
   1147             if args != rv.args:
-> 1148                 rv = rv.func(*args)
   1149             rv = F(rv)
   1150         elif atoms:

~/current/sympy/sympy/sympy/sets/fancysets.py in __new__(cls, flambda, *sets)
    301     def __new__(cls, flambda, *sets):
    302         if not isinstance(flambda, Lambda):
--> 303             raise ValueError('first argument must be a Lambda')
    304 
    305         if flambda is S.IdentityFunction:

ValueError: first argument must be a Lambda
```
I'm not sure why `replace(x, y)` gives `{y}` but the second problem is because `replace` tried to substitute the `rec_replace` symbol for the `Lambda` in the `ImageSet`. There is a note in the replace function that this may not work:
https://github.com/sympy/sympy/blob/3d8a56298c71a67dedb0472f94e3746d04ddd117/sympy/core/basic.py#L1525-L1528

The effect of making `Lambda` with different variables compare unequal would be that the same would apply to `ImageSet`:
```julia
In [7]: s1 = ImageSet(Lambda(x, 2*x), S.Integers)                                                                                 

In [8]: s2 = ImageSet(Lambda(y, 2*y), S.Integers)                                                                                 

In [9]: s1                                                                                                                        
Out[9]: {2⋅x | x ∊ ℤ}

In [10]: s2                                                                                                                       
Out[10]: {2⋅y | y ∊ ℤ}

In [11]: s1 == s2                                                                                                                 
Out[11]: False
```
Maybe it would be better to canonicalise the dummy variables in `Lambda/ImageSet` than have them compare unequal.

**Comment by oscarbenjamin** [comment]
> Maybe it would be better to canonicalise the dummy variables in `Lambda/ImageSet` than have them compare unequal.

Note that `as_dummy` fails for both so this isn't immediately possible right now.

**Comment by smichr** [comment]
PurePolys created with different symbols compare equal. 

But it seems like there should be some comparison that will tell you whether two objects are the same. Consider:

```python
>>> a, b = [PurePoly(i) for i in (x, y)]
>>> hash(a) == hash(b)
>>> a.free_symbols
{}
>>> a.atoms()
{x}
>>> a == b
```

For representational purposes the two are not the same -- they have different atoms. For mathematical purposes, they are the same. But if `==` doesn't tell us that -- and maybe it should -- then what canonical equality test should be used to indicate that they aren't identical?

**Comment by oscarbenjamin** [comment]
> PurePolys created with different symbols compare equal.

I don't think that they should compare equal with `==` if they are different in *any* way. The implication of comparing equal with `==` is that e.g. they can be retrieved interchangeably from the cache or that only one will be stored in a set etc.
```julia
In [1]: {PurePoly(x), PurePoly(y)}                                                                       
Out[1]: {PurePoly(x, x, domain='ZZ')}
```
If we want these to compare equal with `==` then we should make sure that they are equivalent which we can do by e.g. always using the same symbol.

You can see the effect this has on cacheing in this example:
```python
from sympy import *
from sympy.core.cache import cacheit

@cacheit
def f_cache():
    return PurePoly(Dummy())
problems like this.
def f_nocache():
    return PurePoly(Dummy())

assert f_cache().args == f_cache().args     # passes
assert f_nocache().args == f_nocache().args # fails
```
The test failure in the OP of #17794 is due to this.

Any time we mess around with `__eq__` in a `Basic` subclass we will have this problem somewhere. When we think we want to objects to compare equal the solution is to give them canonical args so that `Basic.__eq__` can compare them.

**Comment by smichr** [comment]
> we will have this problem somewhere

Makes sense. I'm guessing that internals interacting with PurePoly will need to be rewritten.

**Comment by asmeurer** [comment]
I think the only reason that PurePoly has a symbol at all is for printing. It's supposed to just represent an abstract polynomial. Its args representation could just be the internal representation (the list or dict of coefficients).

**Comment by jksuom** [comment]
`Poly.args` returns the polynomial as an expression. `PurePoly.args` could be different, but we would still want to have the ability to represent a pure polynomial as an expression. The issue could be solved by using canonical generators. There could be `PurePoly.__init__` that would assign new `gens`. I think that indexed symbols like `X_0`, `X_1`,... would usually suffice. The name (without indices) could be given as a keyword argument (with default `X`, for example).

**Comment by asmeurer** [comment]
I guess the Lambda issue was fixed. Is there an issue for PurePoly? I like the idea of only storing the coefficients and using canonical indexed symbols for the generators. That would also make it clear to the user that PurePoly does not care about the generator names.

**Comment by oscarbenjamin** [comment]
With all of these bound symbol classes it is reasonable to ask whether we should canonicalise the symbols or have them compare unequal with `dummy_eq`. In the case of PurePoly it seems quite clear that canonicalising the symbols is reasonable: the whole point of the class is that it is like Poly except that the identity of the generators is ignored so replacing the generators with canonical symbols is understandable.

If we did the same with Lambda then we wouldn't need to use `dummy_eq` everywhere (3740e189026ed1724a1e7c8536e8288231a65e9a). In 1.6 we have:
```julia
In [4]: ImageSet(Lambda(x, x**2), Reals) == ImageSet(Lambda(y, y**2), Reals)                                                      
Out[4]: True
```
Current master now gives `False`:
```julia
In [1]: ImageSet(Lambda(x, x**2), Reals) == ImageSet(Lambda(y, y**2), Reals)                                                      
Out[1]: False
```
If `Lambda` used canonical variables then comparisons of `ImageSet`, `ConditionSet` etc would be unchanged.

Another case where this comes up is in `Subs`:
```julia
In [3]: Subs(x, x, 1) == Subs(y, y, 1)                                                                                            
Out[3]: True
```

**Comment by asmeurer** [comment]
My point is that with PurePoly, we don't even have to store a symbol at all, because you really only need to store the coefficients. You only need a symbol for printing, and presently for converting to Poly, but I'm suggesting to modify that so there's no symbol stored, and printing would just use standard "symbol" names, and any other method that would use the stored symbol should require an explicit set of generators to be passed. This is already how Poly itself works. The internal representation in the layers below Poly only store the coefficients. The generators are only stored on Poly itself. 

```py
>>> Poly(x*y**2, x, y).rep
DMP([[mpz(1), mpz(0), mpz(0)], []], ZZ, None)
```

With the other classes we have to store something as they use Lambdas, so the question of canonicalizing the bound symbols is relevant.

**Comment by oscarbenjamin** [comment]
PurePoly still has free symbols and will need to have some way of generating canonical symbols for `as_expr`.
```julia
In [17]: PurePoly(x**2) / PurePoly(x)                                                                                             
Out[17]: x

In [18]: PurePoly(x**2) / PurePoly(y)                                                                                             
Out[18]: 
 2
x 
──
y 

In [19]: PurePoly(x**2 + y, x).free_symbols                                                                                       
Out[19]: {y}
```

**Comment by asmeurer** [comment]
Isn't the `PurePoly(x**2) / PurePoly(y)` one wrong? PurePoly(x) is supposed to be the same as PurePoly(y).

**Comment by oscarbenjamin** [comment]
Maybe division of Poly should be disallowed
