### ISSUE TITLE
Make the Sphinx modules headers match the filenames

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#17493]
Right now it's hard to navigate the "SymPy Modules Reference" subheaders at https://docs.sympy.org/latest/index.html, because the names are not in alphabetical order.  There are two issues here:

- The header names are inconsistent. For example, things like "SymPy Core" should just be "Core". It would be best if each header was just the name of the submodule.

- The headers are not in order. They are listed in this file https://github.com/sympy/sympy/blob/master/doc/src/modules/index.rst. 

CC @moorepants @certik @lglattly

**Comment by sachin-4099** [comment]
Sir, I would like to take this issue. I am new to the community. Please guide me as to what to do.

**Comment by nerdishhomosapein** [comment]
I would like to fix  this issue

**Comment by Aarthi-V** [comment]
Hi. Can I work on this issue? I am new to open source and this looks like a good first issue.

**Comment by certik** [comment]
Yes, you can all work on this issue! We would really appreciate it.

**Comment by oscarbenjamin** [comment]
Hi @Aarthi-V it looks as if someone is already working on this in #17499

**Comment by gunjanmimo** [comment]
**i would like to fix this issue**

**Comment by oscarbenjamin** [comment]
Hi @gunjanmimo, this is fixed now in #17499
