### ISSUE TITLE
Add link to GitHub in the Sphinx documentation

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#17492]
Right now the docstrings in Sphinx have a "source" link that shows the source code for a file. But the way it works is that it pulls in the source for each file in RST and shows that. It would be better if it just linked to GitHub. This would also speed up the docs build time, because it currently spends a lot of time syntax highlighting the source. 

We should see if the "source" extension can be modified or replaced with something that links to the source on GitHub. Maybe there is already an extension that does this. If not, we should just write something. 

For the source link, if the docs can detect a git repo it should include the commit hash in the URL (like https://github.com/sympy/sympy/blob/99c6670e65207e879342cb5b1dd11cbffd5cb5ab/sympy/functions/special/delta_functions.py). Otherwise it should just have the plain link (e.g., building the docs from the source tarball), like https://github.com/sympy/sympy/tree/master/sympy/functions/special.

CC @moorepants @certik @lglattly

**Comment by sylee957** [comment]
I see the patch in `diofant` works with little modification.
But it may have to be improved to use the commit hash of the current work, than the simple redirection to the master.
