### ISSUE TITLE
should And and Or short-circuit and avoid invalid args if possible

### ISSUE THREAD

**Issue by smichr** [sympy/sympy#17530]
For ` Or(x+y>0, x - y < 0).subs(x,oo).subs(y,oo)` return True or raise an Error? While `x + y` is defined and it is positive, the difference evaluates to nan and the comparison raises a TypeError. If short-circuiting is better than raising an error then this diff might be of use:

```diff
diff --git a/sympy/logic/boolalg.py b/sympy/logic/boolalg.py
index bc1da80..49b51c6 100644
--- a/sympy/logic/boolalg.py
+++ b/sympy/logic/boolalg.py
@@ -40,6 +40,8 @@ def as_Boolean(e):

     """
     from sympy.core.symbol import Symbol
+    if e is S.NaN:
+        return e
     if e == True:
         return S.true
     if e == False:
@@ -679,6 +681,25 @@ def _new_args_filter(cls, args):
             newargs.append(x)
         return LatticeOp._new_args_filter(newargs, And)

+    def _eval_subs(self, old, new):
+        args = []
+        bad = None
+        for i in self.args:
+            try:
+                i = i.subs(old, new)
+            except:  # store any problem
+                if bad is None:
+                    bad = i
+                continue
+            if i == False:
+                return S.false
+            elif i != True:
+                args.append(i)
+        if bad is not None:
+            # let it raise
+            bad.subs(old, new)
+        return self.func(*args)
+
     def _eval_simplify(self, **kwargs):
         from sympy.core.relational import Equality, Relational
         from sympy.solvers.solveset import linear_coeffs
@@ -797,6 +818,25 @@ def _new_args_filter(cls, args):
             newargs.append(x)
         return LatticeOp._new_args_filter(newargs, Or)

+    def _eval_subs(self, old, new):
+        args = []
+        bad = None
+        for i in self.args:
+            try:
+                i = i.subs(old, new)
+            except:  # store any problem
+                if bad is None:
+                    bad = i
+                continue
+            if i == True:
+                return S.true
+            elif i != False:
+                args.append(i)
+        if bad is not None:
+            # let it raise
+            bad.subs(old, new)
+        return self.func(*args)
+
     def _eval_as_set(self):
         from sympy.sets.sets import Union
         return Union(*[arg.as_set() for arg in self.args])
```

**Comment by oscarbenjamin** [comment]
Not sure about the answer to your question but this is potentially a reason for using `x < y` rather than `x - y < 0` since:
```
In [4]: Or(x+y>0, x < y).subs(x,oo).subs(y, oo)                                                                                   
Out[4]: True
```
I don't know if True makes sense in the original context of your problem though...

**Comment by czgdp1807** [comment]
I think short-circuiting is better because if something else invalid hasn't come into picture then why to raise error for it.

**Comment by oscarbenjamin** [comment]
> My opinion that I've expressed elsewhere is that invalid inequalities should give False, so I'm in favor of this as it moves in that direction.

I certainly think that the exceptions from inequalities are awkward. I can also imagine having a lot of bugs from not considering the implication of `if not (x < y):` but then we have that with `if not x.is_positive` I guess...

What would that mean for something like `I <= I` or `I <= I+1`? If those don't give True then e.g. `m<=m+1` still can't evaluate.

**Comment by oscargus** [comment]
Maybe worth pointing out that there at least will be a dedicated `InvalidComparison` exception if #17443 is merged (and completed). (A bit too busy with work and life at the moment though...).

For the original question, I think that relations should be evaluated from left to right (and therefore not sorted...). So `True`. There will of course be issues when simplifying relationals that will possibly break this at a later stage, but for what it is worth. My main argument would be the similarity to programming languages. `if a is not None and a[0]...`.
