### ISSUE TITLE
integral with DiracDelta: doit ok but evalf wrong

### ISSUE THREAD

**Issue by smichr** [sympy/sympy#17552]
The [following integral](https://stackoverflow.com/questions/57717365/sympy-evalf-on-integral-of-dirac-function) is calculated correctly but evaluated incorrectly:

```python
>>> f = Integral((x**3)*DiracDelta(x - 2), (x, 0, 3))
>>> f.doit()
8
>>> f.n()
0
```
related to #17383, #17321?

**Comment by jksuom** [comment]
These do not look like related as no numerical evaluation is attempted.

**Comment by asmeurer** [comment]
It doesn't look like evalf handles delta integrals correctly at all. It should probably give an exception if encountered.

**Comment by pylang** [comment]
This  was addressed in an earlier [issue](https://github.com/sympy/sympy/issues/17546).   I suggest moving discussion there.
