### ISSUE TITLE
incorrect roots of quartic polynomials

### ISSUE THREAD

**Issue by Gyslain** [sympy/sympy#17563]
I'm having incorrect roots of generic quartic polynomials. Given this code : 
```
x = symbols('x')

expr1 = Rational(1/2)*x**4 + x**2 - 1 # quartic
res1 = simplify(solveset(expr1, x)) # gives {-I*sqrt(1 + sqrt(3)), -sqrt(-1 + sqrt(3)), sqrt(-1 + sqrt(3)), sqrt(-sqrt(3) - 1)}
assert simplify(expr1.subs(x,res1.args[0])) == 0 # the first root is correct

c = symbols('c[0:5]')
expr2 = c[0]*x**4 + c[1]*x**3 + c[2]*x**2 + c[3]*x + c[4] # generic quartic
roots = solveset(expr2, x) # finding the generic roots
res2 = simplify(roots.subs({c[0]:Rational(1/2), c[1]:0, c[2]:1, c[3]:0, c[4]:-1})) # => substituting coefficients gives a long expression
res2.evalf() # => gives wrong roots : {-1.0⋅ⅈ, 1.0⋅ⅈ}
```
`res1` is correct while `res2` is not.

**Comment by jksuom** [comment]
The generic formula for roots of a quadric (Ferrari's method) assumes that certain expressions of the coefficients are non-zero. The implementation already takes care of one of the special cases by returning Piecewise expressions. https://github.com/sympy/sympy/blob/0aa3d116b03474ff19cb23213a12a167fcf094c7/sympy/polys/polyroots.py#L359-L360
However, this example leads to a more special case that is handled separately in the code.
https://github.com/sympy/sympy/blob/0aa3d116b03474ff19cb23213a12a167fcf094c7/sympy/polys/polyroots.py#L313-L316
To fix the issue, these should be added to the Piecewise solutions.

**Comment by sachin-4099** [comment]
Can you elaborate as to where to add exactly and what are the small changes that might be required??
@jksuom

**Comment by jksuom** [comment]
There should be a third Piecewise condition `Eq(f, 0)` that would return the values given on line 316. Those expressions cannot be used verbatim since the meaning of `y1` and `y2` is different on line 360, One should find expressions that are equal to those on line 316 when `f` is 0.
