### ISSUE TITLE
inaccurate rendering of pi**(1/E)

### ISSUE THREAD

**Issue by clsn** [sympy/sympy#17616]
This claims to be version 1.5.dev; I just merged from the project master, so I hope this is current.  I didn't notice this bug among others in printing.pretty.

```
In [52]: pi**(1/E)                                                               
Out[52]: 
-1___
╲╱ π 

```
LaTeX and str not fooled:
```
In [53]: print(latex(pi**(1/E)))                                                 
\pi^{e^{-1}}

In [54]: str(pi**(1/E))                                                          
Out[54]: 'pi**exp(-1)'
```

**Comment by oscarbenjamin** [comment]
I can confirm this bug on master. Looks like it's been there a while

**Comment by ethankward** [comment]
https://github.com/sympy/sympy/blob/2d700c4b3c0871a26741456787b0555eed9d5546/sympy/printing/pretty/pretty.py#L1814

`1/E` is `exp(-1)` which has totally different arg ordering than something like `1/pi`.

**Comment by cbm755** [comment]
@ethankward nice!  Also, the use of `str` there isn't correct:
```
>>> pprint(7**(1/(pi)))                                                                                                                                                          
pi___
╲╱ 7 

>>> pprint(pi**(1/(pi)))                                                                                                                                                        
pi___
╲╱ π 

>>> pprint(pi**(1/(EulerGamma)))                                                                                                                                                
EulerGamma___
        ╲╱ π 
```
(`pi` and `EulerGamma` were not pretty printed)

**Comment by asmeurer** [comment]
I guess str is used because it's hard to put 2-D stuff in the corner of the radical like that. But I think it would be better to recursively call the pretty printer, and if it is multiline, or maybe even if it is a more complicated expression than just a single number or symbol name, then print it without the radical like

```
  1
  ─
  e
π
```

or

```
 ⎛ -1⎞
 ⎝e  ⎠
π

**Comment by 0sidharth** [comment]
I would like to take up this issue. @asmeurer @oscarbenjamin currently, 
```
2**(1/x)
``` 
prints as 
```
x ___
╲╱ 2 
```

Since it is preferred to print 1/irrational numbers like `π`, `e` without the square root sign, I wanted to get your opinion on the case of symbols too, i.e. is the current behaviour preferred or
```
 1
 ─
 x
2 
```
