### ISSUE TITLE
Add Bernoulli process to sympy.stats.stochastic_process_types

### ISSUE THREAD

**Issue by czgdp1807** [sympy/sympy#17611]
Since, the stochastic processes have already been added to `sympy.stats`. So, the purpose of https://github.com/sympy/sympy/pull/15058 is partially over. We now need to add Bernoulli process to `sympy.stats.stochastic_process_types` to complete the work. https://github.com/sympy/sympy/pull/15058 has been closed and this issue keeps track of the incomplete task. 

PS - It will be great if some interested can pick this up as a part of his/her GSoC project.

**Comment by Pranay144** [comment]
I can work on this.
[MITRES_6_012S18_L21AS.pdf](https://github.com/sympy/sympy/files/3619537/MITRES_6_012S18_L21AS.pdf)
And is this enough for reference?

**Comment by czgdp1807** [comment]
Feel free to start the work. Please read the 
work associated with stochastic processes at this [report](https://gist.github.com/czgdp1807/199ae335a28bcfc4a6bcd02138c4108e).

**Comment by Saanidhyavats** [comment]
I want to contribute on this issue. Is this issue open?

**Comment by czgdp1807** [comment]
Yes it is for GSoC 2020.

**Comment by Saanidhyavats** [comment]
How shall I start? Shall I create a new function for this purpose.

**Comment by czgdp1807** [comment]
You can start by studying the current code base of stochastic processes. After that, think of the API which we can use for Bernoulli processes.

**Comment by Smit-create** [comment]
I am working on this.

**Comment by Smit-create** [comment]
```
class BernuolliProcess(DiscreteTimeStochasticProcess):
    index_set = S.Naturals0
    
    def __new__(cls, sym, p):
        if p > 1 or p < 0:
            raise ValueError("Probability must be in between 0 and 1")
        p = sympify(p)
        sym = _symbol_converter(sym)
        state_space = _set_converter(set([(0,1)]))
        obj=Basic.__new__(cls, sym, state_space, BernoulliDistribution(p))
        obj.p=p
        return obj
    
    def first_passage_time(self, state):
        n = symbols('n', natural=True)
        pdf = binomial(n-1, state-1)*(self.p**state)*(1 - self.p)**(n-state)
        return DiscreteDistributionHandmade(pdf, set = S.Naturals)
    
    def prob_k_success(self,n,k):
        if k<=n:
            return (binomial(n, k) * self.p**k * (1 - self.p)**(n - k))
        else:
            raise ValueError("k must be less than or equal to n.")


```
@czgdp1807  Is this correct format to continue? Should I add anymore methods? or Suggest some changes if required

**Comment by czgdp1807** [comment]
I think the code is okay for a PR. However, can you show some examples and references you have used for writing this?

**Comment by Smit-create** [comment]
> I think the code is okay for a PR. However, can you show some examples and references you have used for writing this?

Yes surely, I just showed the workflow, I would surely make it more self-explainable  and easy-to-use.
