### ISSUE TITLE
Refine with sign

### ISSUE THREAD

**Issue by maurogaravello** [sympy/sympy#17647]
Consider the following code:
```
from sympy import *
x = Symbol('x', real = True)

expr = sign(x)
expr2 = refine(expr, Q.positive(x))
expr3 = refine(expr, Q.positive(x) & Q.nonzero(x))
expr4 = refine(expr, Q.positive(x + 1))
```
All the returned expression are `sign(x)`. However, at least for `expr3` and `expr4`, the results should be `1`. This probably is due to the lack of capabilities for `refine`. A PR similar to #17019 should fix this behaviour. 

Related issues: #8326 and #17052.

**Comment by kmm555** [comment]
I would like to work on this issue.
Can someone guide me on exactly what has to be done?

**Comment by maurogaravello** [comment]
@kmm555 you can write a function in `refine.py` similar to `refine_abs()`, which returns `0` if the argument is equal to `0`, `1` if positive and so on (see the possible output of `sign` in `complexes.py`
