### ISSUE TITLE
__new__ of IndexedBase upcasts subclass of Symbol to Symbol

### ISSUE THREAD

**Issue by theHamsta** [sympy/sympy#17652]
First, thanks for creating SymPy. We're using it in a code generation framework: https://github.com/mabau/pystencils

We noticed that our tests are failling when using the current master of SymPy. To reproduce run:

```bash
git clone https://github.com/mabau/pystencils
cd pystencils
pip install -e . 
pip install --upgrade --ignore-installed git+https://github.com/sympy/sympy.git
python setup.py quicktest
``` 
While

```bash
git clone https://github.com/mabau/pystencils
cd pystencils
pip install -e . 
pip install --upgrade --ignore-installed git+https://github.com/sympy/sympy.git@sympy-1.4
python setup.py quicktest
```
should work fine.

The reason for this failure seems to be in the call of the constructor of  `sympy.IndexedBase`. We're a calling it with a subclass of  `sympy.Symbol` (`pystencils.data_types.TypedSymbol`) which is essentially a sympy Symbol with type information.

Is there a reason why the out-commented line is necessary? It causes our TypeSymbol to lose its type information by re-constructing a new Symbol. When I out-comment this line everything works fine again. 

In sympy/tensor/indexed.py
```python
    def __new__(cls, label, shape=None, **kw_args):
        assumptions, kw_args = _filter_assumptions(kw_args)
        if isinstance(label, string_types):
            label = Symbol(label)
        elif isinstance(label, Symbol):
            assumptions = label._merge(assumptions)
            # label = Symbol(label.name)
        elif isinstance(label, (MatrixBase, NDimArray)):
            return label
        elif isinstance(label, Iterable):
            return _sympify(label)
        else:
            label = _sympify(label)

        if is_sequence(shape):
            shape = Tuple(*shape)
        elif shape is not None:
            shape = Tuple(shape)

        offset = kw_args.pop('offset', S.Zero)
        strides = kw_args.pop('strides', None)

        if shape is not None:
            obj = Expr.__new__(cls, label, shape)
        else:
            obj = Expr.__new__(cls, label)
        obj._shape = shape
        obj._offset = offset
        obj._strides = strides
        obj._name = str(label)

        IndexedBase._set_assumptions(obj, assumptions)
        return obj
```

@mabau

**Comment by bjodah** [comment]
If tests pass without the commented line I don't see any problem removing it. Would you mind opening a PR? If you do, would you please also add a regression test (a test which fails using the current code), and then add a commit removing the line which you've commented here.
