### ISSUE TITLE
Slow import of polyhedron

### ISSUE THREAD

**Issue by oscarbenjamin** [sympy/sympy#17658]
This line makes up 20% of the time taken to import sympy:
https://github.com/sympy/sympy/blob/84db1c1d5939f51a7d6d1f67888a31444b90e4ed/sympy/combinatorics/polyhedron.py#L825-L827

I'm not sure what it is doing that is slow but I think there should be a way to statically encode whatever it is that is calculated there.

**Comment by sylee957** [comment]
I have made Permutation as atom in #17340, but I guess that the printers should be updated to print using `.array_form` instead of `.args`
