### ISSUE TITLE
Expressions including Bra and Ket do not result in InnerProduct or OuterProduct expressions

### ISSUE THREAD

**Issue by oscarlazoarjona** [sympy/sympy#17665]
Products of two linear combinations of `Bra` and `Ket` objects should result in linear combinations of `InnerProduct` and `OuterProduct` objects depending on whether the product is to the left or to the right. For instance

```python
>>> from sympy.physics.quantum import Bra, Ket
>>> from sympy import sin, cos, symbols
>>> psi1 = Ket("0")
>>> psi2 = Ket("1")

>>> alpha, beta = symbols("alpha, beta", real=True)
>>> phi1 = alpha*psi1 + beta*psi2
>>> phi2 = alpha*psi1 + beta*psi2

>>> print((psi1.adjoint()*psi2))
>>> print(psi2*psi1.adjoint())
<0|1>
|1><0|
```
Returns the right objects, but 
```python
>>> print(((phi1.adjoint()*phi2)).expand())
>>> print((phi2*phi1.adjoint()).expand())
alpha**2*<0|*|0> + alpha*beta*<0|*|1> + alpha*beta*<1|*|0> + beta**2*<1|*|1>
alpha**2*|0>*<0| + alpha*beta*|0>*<1| + alpha*beta*|1>*<0| + beta**2*|1>*<1|
```
returns `Mul` objects instead (as can be seen by the asterisk between bras and kets). The classes `Bra` and `Ket` are meant to be extended with classes that let the user define how `doit()` will evaluate the `InnerProduct` and `OuterProduct` objects. However, if we get `Mul` objects instead, they cannot be evaluated by `doit()` calls.

**Comment by oscarlazoarjona** [comment]
@oscargus what do you think?

**Comment by certik** [comment]
@oscarlazoarjona I think this looks like a bug, although perhaps there needs to be a pass that goes over the expression and converts `<0| * |0>` to `<0|0>`?

**Comment by oscarlazoarjona** [comment]
> @oscarlazoarjona I think this looks like a bug, although perhaps there needs to be a pass that goes over the expression and converts `<0| * |0>` to `<0|0>`?

I wrote a function that interprets this sort of thing:

```
>>> for i, comb in enumerate(combs):
>>>     print i, comb, "----->", 
>>>     combf = interpret_term(comb)
>>>     print combf
0 alpha*|0>*<1|*<2|*|3>*|4>*|5> -----> alpha*<1|4>*<2|3>*|0>*|5>
1 alpha*<0|*|1>*<2|*|3>*|4>*<5| -----> alpha*<0|1>*<2|3>*|4><5|
2 alpha*<0|*|1>*|2>*|3>*<4|*|5> -----> alpha*<0|1>*<4|5>*|2>*|3>
3 alpha*|0>*|1>*<2|*<3|*|4>*<5| -----> alpha*<3|4>*|0>*|1><2|*<5|
4 alpha*<0|*<1|*|2>*<3|*|4>*<5| -----> alpha*<1|2>*<3|4>*<0|*<5|
5 alpha*<0|*|1>*|2>*<3|*<4|*<5| -----> alpha*<0|1>*|2><3|*<4|*<5|
6 alpha*|0>*<1|*<2|*<3|*<4|*<5| -----> alpha*|0><1|*<2|*<3|*<4|*<5|
7 alpha*<0|*|1>*|2>*|3>*|4>*|5> -----> alpha*<0|1>*|2>*|3>*|4>*|5>
8 alpha*|0>*<1|*<2|*|3>*<4|*<5| -----> alpha*<2|3>*|0><1|*<4|*<5|
9 alpha*|0>*|1>*|2>*|3>*|4>*<5| -----> alpha*|0>*|1>*|2>*|3>*|4><5|
10 alpha*<0|*<1|*|2>*<3|*<4|*|5> -----> alpha*<1|2>*<4|5>*<0|*<3|
11 alpha*<0|*|1>*|2>*<3|*|4>*|5> -----> alpha*<0|1>*<3|4>*|2>*|5>
12 alpha*<0|*<1|*|2>*|3>*<4|*<5| -----> alpha*<0|3>*<1|2>*<4|*<5|
13 alpha*<0|*|1>*|2>*|3>*<4|*<5| -----> alpha*<0|1>*|2>*|3><4|*<5|
14 alpha*|0>*<1|*|2>*|3>*<4|*|5> -----> alpha*<1|2>*<4|5>*|0>*|3>
15 alpha*<0|*<1|*|2>*<3|*|4>*|5> -----> alpha*<0|5>*<1|2>*<3|4>
16 alpha*|0>*|1>*|2>*<3|*|4>*<5| -----> alpha*<3|4>*|0>*|1>*|2><5|
17 alpha*<0|*|1>*|2>*<3|*<4|*|5> -----> alpha*<0|1>*<4|5>*|2><3|
18 alpha*|0>*<1|*|2>*<3|*<4|*<5| -----> alpha*<1|2>*|0><3|*<4|*<5|
19 alpha*<0|*<1|*|2>*|3>*|4>*|5> -----> alpha*<0|3>*<1|2>*|4>*|5>
20 alpha*|0>*|1>*|2>*|3>*<4|*<5| -----> alpha*|0>*|1>*|2>*|3><4|*<5|
21 alpha*|0>*<1|*|2>*|3>*|4>*|5> -----> alpha*<1|2>*|0>*|3>*|4>*|5>
22 alpha*|0>*<1|*<2|*|3>*|4>*<5| -----> alpha*<1|4>*<2|3>*|0><5|
23 alpha*<0|*<1|*|2>*<3|*<4|*<5| -----> alpha*<1|2>*<0|*<3|*<4|*<5|
24 alpha*|0>*|1>*|2>*<3|*<4|*|5> -----> alpha*<4|5>*|0>*|1>*|2><3|
25 alpha*<0|*|1>*|2>*<3|*|4>*<5| -----> alpha*<0|1>*<3|4>*|2><5|
26 alpha*|0>*<1|*|2>*<3|*|4>*|5> -----> alpha*<1|2>*<3|4>*|0>*|5>
27 alpha*<0|*<1|*|2>*|3>*<4|*|5> -----> alpha*<0|3>*<1|2>*<4|5>
28 alpha*<0|*<1|*<2|*|3>*|4>*<5| -----> alpha*<1|4>*<2|3>*<0|*<5|
29 alpha*|0>*<1|*|2>*|3>*<4|*<5| -----> alpha*<1|2>*|0>*|3><4|*<5|
30 alpha*|0>*|1>*|2>*<3|*|4>*|5> -----> alpha*<3|4>*|0>*|1>*|2>*|5>
31 alpha*|0>*<1|*|2>*<3|*<4|*|5> -----> alpha*<1|2>*<4|5>*|0><3|
32 alpha*|0>*|1>*|2>*|3>*<4|*|5> -----> alpha*<4|5>*|0>*|1>*|2>*|3>
33 alpha*<0|*<1|*|2>*|3>*|4>*<5| -----> alpha*<0|3>*<1|2>*|4><5|
34 alpha*<0|*<1|*<2|*|3>*<4|*|5> -----> alpha*<2|3>*<4|5>*<0|*<1|
35 alpha*<0|*<1|*<2|*<3|*<4|*<5| -----> alpha*<0|*<1|*<2|*<3|*<4|*<5|
36 alpha*|0>*|1>*|2>*<3|*<4|*<5| -----> alpha*|0>*|1>*|2><3|*<4|*<5|
37 alpha*|0>*<1|*|2>*<3|*|4>*<5| -----> alpha*<1|2>*<3|4>*|0><5|
38 alpha*<0|*|1>*<2|*<3|*|4>*<5| -----> alpha*<0|1>*<3|4>*<2|*<5|
39 alpha*<0|*<1|*<2|*|3>*|4>*|5> -----> alpha*<0|5>*<1|4>*<2|3>
40 alpha*|0>*|1>*<2|*|3>*|4>*<5| -----> alpha*<2|3>*|0>*|1>*|4><5|
41 alpha*<0|*<1|*<2|*<3|*|4>*|5> -----> alpha*<2|5>*<3|4>*<0|*<1|
42 alpha*|0>*<1|*<2|*|3>*<4|*|5> -----> alpha*<2|3>*<4|5>*|0><1|
43 alpha*<0|*|1>*<2|*<3|*<4|*|5> -----> alpha*<0|1>*<4|5>*<2|*<3|
44 alpha*<0|*<1|*<2|*|3>*<4|*<5| -----> alpha*<2|3>*<0|*<1|*<4|*<5|
45 alpha*|0>*|1>*<2|*|3>*<4|*|5> -----> alpha*<2|3>*<4|5>*|0>*|1>
46 alpha*<0|*|1>*<2|*|3>*<4|*<5| -----> alpha*<0|1>*<2|3>*<4|*<5|
47 alpha*<0|*<1|*<2|*<3|*<4|*|5> -----> alpha*<4|5>*<0|*<1|*<2|*<3|
48 alpha*|0>*|1>*<2|*<3|*<4|*<5| -----> alpha*|0>*|1><2|*<3|*<4|*<5|
49 alpha*<0|*|1>*<2|*<3|*|4>*|5> -----> alpha*<0|1>*<2|5>*<3|4>
50 alpha*|0>*<1|*<2|*<3|*|4>*<5| -----> alpha*<3|4>*|0><1|*<2|*<5|
51 alpha*|0>*|1>*<2|*|3>*|4>*|5> -----> alpha*<2|3>*|0>*|1>*|4>*|5>
52 alpha*<0|*|1>*<2|*|3>*|4>*|5> -----> alpha*<0|1>*<2|3>*|4>*|5>
53 alpha*<0|*<1|*<2|*<3|*|4>*<5| -----> alpha*<3|4>*<0|*<1|*<2|*<5|
54 alpha*|0>*|1>*<2|*<3|*|4>*|5> -----> alpha*<2|5>*<3|4>*|0>*|1>
55 alpha*<0|*|1>*<2|*<3|*<4|*<5| -----> alpha*<0|1>*<2|*<3|*<4|*<5|
56 alpha*|0>*<1|*<2|*<3|*<4|*|5> -----> alpha*<4|5>*|0><1|*<2|*<3|
57 alpha*|0>*|1>*<2|*|3>*<4|*<5| -----> alpha*<2|3>*|0>*|1><4|*<5|
58 alpha*<0|*|1>*<2|*|3>*<4|*|5> -----> alpha*<0|1>*<2|3>*<4|5>
59 alpha*<0|*|1>*|2>*|3>*|4>*<5| -----> alpha*<0|1>*|2>*|3>*|4><5|
60 alpha*|0>*|1>*<2|*<3|*<4|*|5> -----> alpha*<4|5>*|0>*|1><2|*<3|
61 alpha*|0>*<1|*|2>*|3>*|4>*<5| -----> alpha*<1|2>*|0>*|3>*|4><5|
62 alpha*|0>*|1>*|2>*|3>*|4>*|5> -----> alpha*|0>*|1>*|2>*|3>*|4>*|5>
63 alpha*|0>*<1|*<2|*<3|*|4>*|5> -----> alpha*<2|5>*<3|4>*|0><1|
```
Is this the sort of thing you mean? Can it be made so that that function executes every time a `Ket` or `Bra` function is involved? Where would this be added?

I think some of these expressions are ambiguous however. What does `<0|*<1|*|2>` mean? Is it `<1|2>*<0|` or `<0|x<1|x|2>` (where `x` denotes tensor product)? In my opinion `Bra(0)*Bra(1)*Ket(2)` should raise an error, and `Bra(0)*(Bra(1)*Ket(2))` should evaluate to `<1|2>*<0|`.

**Comment by oscarbenjamin** [comment]
The reason this works for individual Bra and Kets is that it is handled in `Bra/Ket.__mul__`. So it doesn't work when a `Mul` is created:
```julia
In [11]: print(psi1.adjoint()*psi2)                                                                                                            
<0|1>

In [12]: print(Mul(psi1.adjoint(), psi2))                                                                                                      
<0|*|1>
```
This means that it pretends to work in simple cases but actually all core routines (Add, Mul, flatten, expand, factor) etc cannot handle these. Even a single scalar breaks it:
```julia
In [15]: print(psi1.adjoint()*(2*psi2))                                                                                                        
2*<0|*|1>
```
Making this work the way you want would require a reworking of something. It might be possible to rearrange the core Mul routines so that they guarantee to call `term.__mul__` for non-commutative terms. I think that's the wrong direction though: subclasses of Expr should not define `__mul__` because it will only end being inconsistent with `Mul` somehow. You could perhaps define a new kind of `Mul` analogous to `MatMul`.

Probably the simplest thing is not converting to inner/outer product at all. Then the Bras and Kets are just non-commutative symbols that work in all the normal ways. When you need to evaluate the inner/outer products in an expression you can make a special function to do that.

**Comment by oscarlazoarjona** [comment]
> Probably the simplest thing is not converting to inner/outer product at all. Then the Bras and Kets are just non-commutative symbols that work in all the normal ways. When you need to evaluate the inner/outer products in an expression you can make a special function to do that.

The reason I wanted this to work this way is because I want to write an `angular_momentum` module in which angular momentum operators are defined in an abstract way. Something like

```
>>> Sx = JxOperator("S")
>>> Sx
Sx
>>> basis = [AngularMomentumKet(1/S(2), -1/S(2)), AngularMomentumKet(1/S(2), 1/S(2))]
>>> Sx_matrix = Sx.matrix_form(basis)
>>> pprint(Sx_matrix)
⎡ 0   1/2⎤
⎢        ⎥
⎣1/2   0 ⎦
```

My strategy for `matrix form` is to define the action of `Sx` on `AngularMomentumKet` objects and extend the `InnerProduct` class so that
```
>>> [[ (ui.adjoint()*Jx.apply(uj)).doit() for uj in basis] for ui in basis]
```
works. As I understand this is the way in which the classes `HermitianOperator` and `Ket` are meant to be used. However, the way things are done currently the if the `Jx.apply` returns anything more complicated than a pure `Ket` object, the multipication with `ui.adjoint()` will return a `Mul` and `doit()` won't to anything :(

I guess you are suggesting something like:
```
>>> [[ find_and_apply_scalar_products(ui.adjoint()*Jx.apply(uj)) for uj in basis] for ui in basis]
```
correct?

> Making this work the way you want would require a reworking of something. It might be possible to rearrange the core Mul routines so that they guarantee to call `term.__mul__` for non-commutative terms. I think that's the wrong direction though: subclasses of Expr should not define `__mul__` because it will only end being inconsistent with `Mul` somehow. You could perhaps define a new kind of `Mul` analogous to `MatMul`.

I like that idea better, however I thought this was just what the classes `OuterProduct` and `InnerProduct` were meant to do (hence I made this Issue). I've noticed that `MatrixSymbol` objects raise an error when one tries to do an operation that is not matrix-matched. Something similar could be done for manipulating Dirac algebra objects...

**Comment by oscarlazoarjona** [comment]
I've also noticed that `.expand()` does not work for expressions with `MatrixSymbol`.

```python
In [19]: >>> A = MatrixSymbol('A', 2, 2)
    ...: >>> B = MatrixSymbol('B', 2, 2)
    ...: >>> C = MatrixSymbol('C', 2, 2)
    ...: >>> MatMul(A, B, C)
    ...: 
Out[19]: A*B*C

In [20]: (A+B)*(C+A)
Out[20]: (A + B)*(A + C)

In [21]: ((A+B)*(C+A)).expand()
Out[21]: (A + B)*(A + C)
```

**Comment by oscarbenjamin** [comment]
Are you testing with master? I get:
```julia
In [30]: expand((A+B)*(C+A))                                                                                                                   
Out[30]: 
                   2
A⋅C + B⋅A + B⋅C + A 

In [31]: ((A+B)*(C+A)).expand()                                                                                                                
Out[31]: 
                   2
A⋅C + B⋅A + B⋅C + A 
```

We really need a better solution than growing lots of `*Add` and `*Mul` classes that all have to reimplement everything. Perhaps something like #14490.

**Comment by czgdp1807** [comment]
ping @oscarlazoarjona Any comments from your side on [the above](https://github.com/sympy/sympy/issues/17665#issuecomment-536329901).

**Comment by oscarlazoarjona** [comment]
Apologies for not responding. I was not testing with the master branch, but with Anaconda's distribution. The master works correctly for me too.

I also think a multiple dispatch approach would make a lot of sense, but from what I gathered of the discussion for #14490 the effort to bring multiple dispatch to the core of sympy has stopped (possibly because the benchmarks were not successful?) I don't feel confident of coming up with successful benchmarking myself in the near future though.

**Comment by oscarbenjamin** [comment]
I think that #14490 is a big task. Something *like* that is needed but we need someone with the experience, time and dedication to see it through (I'm not volunteering right now!)

**Comment by czgdp1807** [comment]
@oscarlazoarjona @kenluck2001 Would you like to take a look at it?

**Comment by oscarlazoarjona** [comment]
> @oscarlazoarjona @kenluck2001 Would you like to take a look at it?

You mean #14490 ? I did have a look at it, and as @oscarbenjamin says, I think it is a big task for me at this moment. I could implement the `angular_momentum` module with the approach described above

> ```python
> >>> [[ find_and_apply_scalar_products(ui.adjoint()*Jx.apply(uj)) for uj in basis] for ui in basis]
> ```

at some point in the not-so-distant future.

**Comment by m93a** [comment]
Bump. Is there anything I can do to help with this issue?

**Comment by oscarbenjamin** [comment]
The easiest way to get this working would be with a function that post-processes the expression. Something like `braketsimp(expr)`.

Making it work naturally with `Add` and `Mul` in a reasonable way is a big task. There should not be any code in the core that special cases this so what is needed is some way of making `Add` and `Mul` extendable by other types so they can override the behaviour of `flatten`. This is also needed for matrices and for other things so it is an important problem.

**Comment by oscarbenjamin** [comment]
I guess you could do this with a new Mul class like `QExprMul` that could cancel `Bra` and `Ket`. You'd have to make it so that `QExpr.__mul__` returns these instead of `Mul`.

**Comment by m93a** [comment]
Haha, I just found out that the `qapply` function from `sympy.physics.quantum` does exactly what the OP asked.

```python
>>> qapply(2 * Bra('m') * Ket('n'))
2 <m|n>
```

Calling `qapply` automatically on multiplication shouldn't be too hard then. But I'll focus on my other PRs first 🙂

**Comment by oscarbenjamin** [comment]
Good work!

I tend to think that automatic evaluation is not as good as controllable evaluation anyway. Why not try it to see if `qapply` works and consider whether there is any need for anything to be changed?

**Comment by m93a** [comment]
`qapply` indeed does work, even for custom `Bra` and `Ket` classes. So, if automatic evaluation isn't needed, and I agree that it probably isn't, this issue can be closed.

**Comment by certik** [comment]
If at all possible, I would also prefer if `qapply` is not done by default. I think it's a good design if SymPy (and SymEngine) only does the bare minimum automatically, and leave the rest to the user. In SymEngine, the bare minimum is determined by internal data structures that are designed for the most efficient manipulation (i.e, it can't even represent `x+x`, only `2*x` or `x+y`). But beyond that, the user should choose what he wants to do.

**Comment by ellisonbg** [comment]
The code to convert products of bras and kets to inner products, outer products, and tensor products is mostly there already and is separate from qapply. I agree with @certik about qapply not being applied by default. There are a lot of symbolic manipulations that users may want to do that are not possible once qapply has been called on an expression.

There are some additional cases that #19538 #19540 will address. Closing this one for now as I think the existing capabilities of qapply and these other two issues will cover these usage cases. Feel free to reopen if more discussion is needed.

**Comment by oscarbenjamin** [comment]
> There are a lot of symbolic manipulations that users may want to do that are not possible once qapply has been called on an expression.

Maybe the custom `__mul__` methods should be removed then because they trigger the manipulations of `qapply` but only in `a*b` and not `Mul(a, b)` etc:
```python
In [6]: e1 = Bra(0)*Ket(1) + Bra(0)*Ket(2)

In [7]: e2 = Mul(Bra(0), Ket(1)) + Mul(Bra(0), Ket(2))

In [8]: e1
Out[8]: ⟨0❘1⟩ + ⟨0❘2⟩

In [9]: e2
Out[9]: ⟨0❘⋅❘1⟩ + ⟨0❘⋅❘2⟩

In [10]: factor(e1)
Out[10]: ⟨0❘1⟩ + ⟨0❘2⟩

In [11]: factor(e2)
Out[11]: ⟨0❘⋅(❘1⟩ + ❘2⟩)

In [14]: qapply(e2) == e1
Out[14]: True
```
In general I think any time some Basic subclass implements `__mul__` etc methods then we are in trouble because it always makes them inconsistent with what `Mul` would do and then `A*B` is not the same as `(x*y).subs({x:A, y:B})` etc.

SymPy needs something more systematic for handling types that are like vector space algebras like vectors, operators, quaternions etc. These things need some special handling somehow but the core does not define the right kind of extensibility to make them work properly. When someone adds `__mul__` to a type they are trying to work around these limitations but in a way that will inevitably fail for anything nontrivial. The same applies to making new Add/Mul types like `MatAdd`, `VectorAdd`. That just isn't scalable. There should be something more algebraically general that can encompass all of these things.

Btw @ellisonbg if you are interested in reviewing quantum things take a look at gh-24349.

**Comment by ellisonbg** [comment]
Yeah, it would be really nice if the builtin operations like `Mul` had a better way for subclasses of `Expr` to declare special handling. A bit of clarification about how these methods work today:

* The logic in the `__mul__`, `__rmul__`, and `__new__` apply transformations that should always be applied. For quantum, this includes things like converting products of bra and keys to inner, outer, and tensor products. However, following the overall sympy design principles, these "always applied" transformations should be as minimal as possible.
* The conversion of products of bra and keys to inner, outer, and tensor products is done in these special methods rather than qapply. Instead, qapply operates at a different level where it takes symbolic products of bras, kets and operators and actually tries to compute the new states, operators, or scalars that result (using a completely different set of special methods like `_eval_innerproduct`).

Based on the constraints in the design of the core classes like `Mul` today and of Python itself, I believe that `sympy.physics.quantum` makes a decent set of tradeoffs. Definitely not perfect or ideal, but hopefully getting close to the zen of Python.

I may eventually have a look at the qapply refactor PR above, but there are some other issues related to tensor products, and products of bras and kets that I would like to tackle first. Getting the logic for qapply right for all the cases involving tensor products in quite subtle and I want to make sure that the expressions we are giving to qapply are as clean as possible for these cases.

**Comment by oscarbenjamin** [comment]
> Yeah, it would be really nice if the builtin operations like `Mul` had a better way for subclasses of `Expr` to declare special handling.

There is a way to do this now with `.kind` and postprocessors although it probably needs improvement. See e.g. gh-26623 which does this for vectors.

**Comment by ellisonbg** [comment]
Ohh, nice I will have a look!
