### ISSUE TITLE
Cycle is not a Basic instance and is mutable

### ISSUE THREAD

**Issue by oscarbenjamin** [sympy/sympy#17661]
I'm not sure whether this is a problem or what the fix should be but I find this surprising. The Cycle class from combinatorics is a subclass of dict rather than Basic and is therefore mutable. It also implements `__missing__` which means it can be unintentionally mutated:
```julia
In [1]: from sympy.combinatorics.permutations import Cycle                                               

In [2]: c1 = Cycle(1, 2)                                                                                 

In [3]: c2 = Cycle(1, 2)                                                                                 

In [4]: c1 == c2                                                                                         
Out[4]: True

In [5]: srepr(c1)                                                                                        
Out[5]: 'Cycle(1, 2)'

In [6]: c1 == c2                                                                                         
Out[6]: False

In [7]: c1.keys()                                                                                        
Out[7]: dict_keys([1, 2, 0])

In [8]: c2.keys()                                                                                        
Out[8]: dict_keys([1, 2])

In [9]: c2                                                                                               
Out[9]: Cycle(1, 2)

In [10]: c1                                                                                              
Out[10]: Cycle(1, 2)
```
I don't really know what this class is used for: it isn't used outside of the permutations module as far as I can tell but it does have e.g. printing support which suggests it is supposed to be seen by users.

Maybe this should be made a proper immutable Basic subclass.

**Comment by jksuom** [comment]
It seems to me that Cycle can be regarded as a sparse representation of a permutation. It could probably be made unique by omitting all keys that coincide with their values. So maybe the line `self[arg] = arg` could be removed from `__missing__`.

**Comment by oscarbenjamin** [comment]
I think this is basically an internal class used by Permutation. It probably shouldn't have any printing support but otherwise I guess it isn't necessary to change anything.

If the Cycle class is intended to be used by users then it should subclass Basic.

**Comment by sachin-4099** [comment]
> It seems to me that Cycle can be regarded as a sparse representation of a permutation. It could probably be made unique by omitting all keys that coincide with their values. So maybe the line `self[arg] = arg` could be removed from `__missing__`.

True, this is working.

**Comment by sachin-4099** [comment]
In [1]: from sympy.combinatorics.permutations import Cycle

In [2]: c1 = Cycle(1, 2)

In [3]: c2 = Cycle(1, 2)

In [4]: c1 == c2
Out[4]: True

In [5]: srepr(c1)
Out[5]: 'Cycle(1, 2)'

In [6]: c1 == c2
Out[6]: True

In [7]: c1.keys()
Out[7]: dict_keys([1, 2])

In [8]: c2.keys()
Out[8]: dict_keys([1, 2])

In [9]: c2
Out[9]: Cycle(1, 2)

In [10]: c1
Out[10]: Cycle(1, 2)

These are the output after the changes.

**Comment by sachin-4099** [comment]
What are your suggestions @oscarbenjamin @jksuom ?

**Comment by oscarbenjamin** [comment]
I think that we need to decide whether `Cycle` is an internal class or not. If it is an internal class then printing support should be removed. If it is not an internal class then it should subclass Basic.

**Comment by sachin-4099** [comment]
>  So maybe the line self[arg] = arg could be removed from __missing__.

What about this change?

**Comment by sachin-4099** [comment]
> I think that we need to decide whether `Cycle` is an internal class or not. If it is an internal class then printing support should be removed. If it is not an internal class then it should subclass Basic.

Please let me know about the final decision, then I will make the necessary changes following your instructions.

**Comment by smichr** [comment]
> decide whether `Cycle` is an internal class or not

As I recall, it wasn't the intention to have this be internal. It was intended as an alternate representational form for a Permutation -- a "batteries included" sort of form for those working in combinatorics.

**Comment by sachin-4099** [comment]
Okay, so then according to @oscarbenjamin it should subclass Basic, what should be done finally?
Shall I just go ahead with this change:
> So maybe the line self[arg] = arg could be removed from missing.

Or some other changes are also required @smichr @jksuom

**Comment by oscarbenjamin** [comment]
If this subclasses Basic then it will be immutable and will not subclass dict so `self[arg]=arg` won't make sense any more. The information about the cycle will need to be stored in args somehow.

**Comment by sachin-4099** [comment]
So what should be the next step, how should we proceed to implement this? 
@oscarbenjamin @smichr @jksuom

**Comment by smichr** [comment]
As @jksuom said,
```diff
diff --git a/sympy/combinatorics/permutations.py b/sympy/combinatorics/permutations.py
index 6c1a212..df6a145 100644
--- a/sympy/combinatorics/permutations.py
+++ b/sympy/combinatorics/permutations.py
@@ -311,9 +311,8 @@ class Cycle(dict):
     """
     def __missing__(self, arg):
         """Enter arg into dictionary and return arg."""
-        arg = as_int(arg)
-        self[arg] = arg
-        return arg
+        # don't mutate upon a request for missing
+        return as_int(arg)
```

**Comment by sachin-4099** [comment]
so just returning **as_int(arg)** will do?
@smichr @jksuom @oscarbenjamin
