### ISSUE TITLE
Plots do not seem to show up in the JupyterLab notebook interface

### ISSUE THREAD

**Issue by moorepants** [sympy/sympy#17660]
Example:
![Selection_579](https://user-images.githubusercontent.com/276007/65691130-2aeb8280-e025-11e9-9497-d12c4f092fae.png)

In the classic notebook interface you must type:

```
% matplotlib notebook # or the png backend
import sympy
from sympy.abc import x
sympy.plot(x**2)
```

But adding the matplotlib line in JupyterLab doesn't do anything.

![Selection_580](https://user-images.githubusercontent.com/276007/65691314-7a31b300-e025-11e9-8229-233ed3d54eb7.png)

**Comment by Tamoghna-Bhattacharjee** [comment]
![solving plot issue](https://user-images.githubusercontent.com/53398531/66646596-3b664480-ec44-11e9-9c8e-1796a0fdc1a7.JPG)

**Comment by moorepants** [comment]
What version of JupyterLab are you using? %matplotlib does not work for me, as shown above.

**Comment by moorepants** [comment]
Weird, just tried the same code as shown above that was not working and now it is.
![Selection_593](https://user-images.githubusercontent.com/276007/66655613-36c47080-ebf1-11e9-8f43-5a10062fc91e.png)

**Comment by moorepants** [comment]
I see, if you don't give an argument to `%matplotlib`, in this case `inline`, it doesn't work.

**Comment by moorepants** [comment]
A couple more notes for others that hit tihs:

`%matplotlib notebook` does not seem to work in JupyterLab

`%matplotlib widget` is a new command but you have to install https://github.com/matplotlib/jupyter-matplotlib which takes several commands to install
