### ISSUE TITLE
Add Jones calculus module to sympy.physics.optics

### ISSUE THREAD

**Issue by oscarlazoarjona** [sympy/sympy#17679]
Let's add a module that provides Jones matrices for half, quarter, and generic phase retarders. Also linear polarizers and polarizing prisms.

**Comment by kmm555** [comment]
I want to work on this where should I start from?

**Comment by oscarlazoarjona** [comment]
> I want to work on this where should I start from?

I just added a pull request #17818 doing this, maybe you could review it?
