### ISSUE TITLE
Unclear documentation in Quaternion.rotate_point()

### ISSUE THREAD

**Issue by mgeier** [sympy/sympy#17678]
I'm neither a mathematician nor a native English speaker, so please correct me if I'm wrong!

The current documentation of the static method `sympy.algebras.Quaternion.rotate_point()` looks like this:

https://github.com/sympy/sympy/blob/0ace745eac76d054af75f3d578b9d567e3581a80/sympy/algebras/quaternion.py#L542-L559

What I don't understand is:

    This point will be the axis of rotation.

Doesn't the quaternion `r` determine the axis of rotation?
Or if `r` is a tuple, its first element?

And I think this might also be a bit unclear:

    Angle to be rotated.

The thing that's rotated is `pin`, isn't it?
So the angle itself is not rotated?
Also, if `r` is a tuple, the angle is actually the second element of `r`.

And finally:

    The coordinates of the quaternion after rotation.

Shouldn't this say "The coordinates of the *point* after rotation"?

BTW, the point is rotated around the origin, which isn't mentioned anywhere, but probably that's obvious to everyone?

**Comment by jksuom** [comment]
Indeed, it seems that the parameter descriptions are wrong. The code indicates that `pin` is the point that is rotated and `r` is a quaternion or a tuple (axis, angle) that defines the rotation. Please send a PR with a suggestion for better docstring.

**Comment by mgeier** [comment]
cc @Geektrovert who was the original author of the docstring.
