### ISSUE TITLE
`bspline_basis` returns uncontinuous piecewise with knots repeated at both ends

### ISSUE THREAD

**Issue by John-Qu** [sympy/sympy#17687]
Hello,

I'm using SymPy's bspline package to generate b-splines to design a mechanical cam profile, so I need to use splines with order `6` and knots with repeated start and endpoint, e.g. `[0, 0, 0, 0, 0, 0, pi / 4, pi / 2, 3 * pi / 4, pi, pi, pi, pi, pi, pi]` .

I found the `bspline_basis_set` returns nine basis splines just as it promised and suits my purpose well in derivating for velocity and acceleration, except for the center one bs[4] which is not continuous at knots  `pi/4, pi/2, 3*pi/4`, as shown here.

![](https://tva1.sinaimg.cn/large/006y8mN6ly1g7jliddvi4j30zk0qo784.jpg)

I wonder it is the feature of repeated knots at both ends that cause `bspline_basis` fail to function well. So with the following simple experiment, it shows a similar result.

```python
from sympy import *
from sympy.abc import x
import numpy as np

knots = np.array([0, 0, 1, 2, 2])
order = len(knots) - 1
degree = order - 1
bs = bspline_basis(degree, knots, 0, x)
print(latex(bs))
plot(bs, (x, 0, knots[-1]),
     title="B-spline of order "+str(order)+"\nwith knots: "+str(knots))
```

$$
\begin{cases} - \frac{3 x^{3}}{4} + x^{2} & \text{for}\: x \geq 0 \wedge x \leq 1 \\- \frac{x^{2}}{2} + x & \text{for}\: x \geq 1 \wedge x \leq 2 \\0 & \text{otherwise} \end{cases}
$$

![](https://tva1.sinaimg.cn/large/006y8mN6ly1g7jlhqmi9uj30zk0qo75q.jpg)

I really appreciate the SymPy functions, and it really helps me of solving my cam design problem. 

I have tried scipy.interpolate.Bspline. It generates splines as it is. But I can't derivate them with the unknown coefficients.

![](https://tva1.sinaimg.cn/large/006y8mN6ly1g7k85cn90yj30zi0u00wb.jpg)

I would like to read your source codes and see if I can find why it is not continuous at the middle splines among them. But I am a newbie to python and sympy, so I think it is better to let you know this issue and hope for some tips for me.

Thanks.

John Qu

**Comment by jksuom** [comment]
It looks like this was fixed by https://github.com/sympy/sympy/pull/16359. The error should not occur in current master.

**Comment by John-Qu** [comment]
Thank you very much. I see the diffs and appreciate these fix works. Now my curves become smooth. Great.

**Comment by John-Qu** [comment]
It has been fixed in the current Sympy/master branch. 
I use the sympy which is acquired for me automatically by Pycharm's Conda env. It is not up to date.
