### ISSUE TITLE
Inequalities with noncommutatives

### ISSUE THREAD

**Issue by oscarbenjamin** [sympy/sympy#17708]
We currently have this test:
https://github.com/sympy/sympy/blob/4fc50841e38205561523e0a9d0e5da173988b04a/sympy/core/tests/test_expr.py#L218-L224

While working on #17699 I hit a snag with this and it's a basic definitional problem that needs to be clarified. In SymPy ordering relations i.e. `<`, `<=`, `>`, `>=` are only defined between extended real objects. However the extended reals are commutative. This means that any non-commutative objects should not be usable in inequalities.

But we have a test that requires that we *can* use non-commutative objects in inequalities? Can anyone clarify what the test is supposed to represent? Obvious examples of non-commutatives like matrices, quaternions, operators etc are unordered. What is an example of an order non-commutative set? Should this be allowed?

**Comment by sylee957** [comment]
https://en.wikipedia.org/wiki/Partially_ordered_set#Examples 
I see `string` can have inequality defined, but the string concatenation operator is not commutative.

**Comment by oscarbenjamin** [comment]
In SymPy I think that commutativity refers to `*` (not usually defiend for strings) rather than `+`.

**Comment by sylee957** [comment]
There are some definitions for the partial orderings of a matrix
https://www.math.uni-augsburg.de/htdocs/emeriti/pukelsheim/1989d.pdf
and in this material, it notes that some matrix partial ordering can preserve the relational even if a Kronecker product or a matrix multiplication is applied.

**Comment by jksuom** [comment]
I don't think that `test_relational_noncommutative` would be needed. There are ordered sets with a composition law but its properties (commutativity, associativity) seem unrelated to the order.

I guess SymPy could continue to allow unevaluated expressions like `Lt(A, B)`, but there should be no need for tests as long as no meaning is assigned to the expressions.

**Comment by oscarbenjamin** [comment]
I added this commit in #17699 at the same time as opening this issue:
https://github.com/sympy/sympy/commit/0c5c4bd5a3967137298202ec22f4fe1f164a06a1
That disallows both `A<B` and `Lt(A, B)`

Should I revert that?

**Comment by jksuom** [comment]
Reverting may not be necessary as long as there are no comparisons between other instances of `Expr` than extended reals. (Ordinals are `Basic` but not `Expr`.) However, maybe something like this would work also in the future: If one of the objects is complex (or infinite), then both have to be extended real.

**Comment by oscarbenjamin** [comment]
In terms of the tests making that change only required commenting out `test_relational_noncommutative` shown above. Everything else seems to work fine.

I don't think there is any concrete non-commutative-but-ordered type in SymPy right now. That test asserts that it should work for the symbolic case but I don't see why it should without any useful example of what that could mean.

**Comment by jksuom** [comment]
Ordinals are ordered and non-commutative (both addition and multiplication), but as they do not inherit from `Expr`, this piece of code does not affect them. So I think you commit is OK.

**Comment by oscarbenjamin** [comment]
I commented the test out with a link pointing back to this issue. I'll take this as fixed and close this issue now.
