### ISSUE TITLE
`plot_implicit` with `And` ignoring relations

### ISSUE THREAD

**Issue by ricopicone** [sympy/sympy#17710]
With `sympy` 1.4 and Python 3.7.3, using `And` for intersecting relations in `plot_implicit` respects only one of the inequalities. Working example below.

```python
import sympy as sp
sp.var('x,y',real=True)
sp.plot_implicit((y > x)&(y > 2),y_var=y,x_var=x)
```

The resulting plot is below; it doesn't respect `y > 2`.

![image](https://user-images.githubusercontent.com/4192991/66358107-4e1c0900-e926-11e9-9347-ed98abd32829.png)

**Comment by sylee957** [comment]
There can be something wrong with the composite boolean expressions with interval arithmetic

This is a minimal example of what's probably going wrong
```python3
>>> from sympy import *
>>> from sympy.plotting.experimental_lambdify import experimental_lambdify
>>> from sympy.plotting.intervalmath import interval

>>> x, y = symbols('x y')

>>> experimental_lambdify((x, y), (y > x) & (y > 2))(
...     interval(0.2, 0.4), interval(1.2, 1.4)
... )
(True, True)
```

I may suspect a naive usage of `and` is causing some problems.
