### ISSUE TITLE
[Warning]:  Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.

### ISSUE THREAD

**Issue by stevenleeS0ht** [sympy/sympy#17721]
When I run isympy,

it print the following warning message in console
```
 Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
```

Is which config file is wrong?

**Comment by cbm755** [comment]
I get this for any QT programs on Fedora 30.  I don't think its a SymPy bug.

I also get
`xkbcommon: ERROR: Key "<CAPS>" added to modifier map for multiple modifiers; Using Control, ignoring Lock`

Please do re-open with info about your system if I'm wrong and this is unique to SymPy.

**Comment by asmeurer** [comment]
isympy sets up matplotlib when it starts this is probably related to that. Does just running `ipython` and then

```
%matplotlib
```

give the same warning?

**Comment by jksuom** [comment]
I used to get xkb-related errors but those vanished with proper XKBOPTIONS in /etc/default/keyboard.
