### ISSUE TITLE
linsolve error; ValueError: Got rows of variable lengths: [1, 3]

### ISSUE THREAD

**Issue by ArchangelEkim** [sympy/sympy#17722]
Can anyone tell me if this is a bug and if there is a method to get around this please, cause it seems like the linsolve() function is broken?
A similar question was asked in issue #17430 but this doesn't solve my problem when used in jupyter or qtconsole or spyder. This function would be really useful if it worked for my uni study.

Parameters given are: *system* in form of Ax=b and variables *c* in a tuple of Sympy Symbols
![image](https://user-images.githubusercontent.com/42601907/66694509-028ba580-ed00-11e9-85db-f8e1567a5306.png)
![image](https://user-images.githubusercontent.com/42601907/66694519-1505df00-ed00-11e9-9861-02ea8f1dd249.png)

**Comment by ArchangelEkim** [comment]
Worked out the problem I was trying to solve using an immutable matrix, but the linsolve() function only takes mutable matrices. However is there an easy way of transforming a immutable matrix into a mutable one?

**Comment by jksuom** [comment]
There is a method, `.as_mutable()`, for that purpose.

**Comment by ArchangelEkim** [comment]
> There is a method, `.as_mutable()`, for that purpose.

Thanks, I should've looked harder :)

**Comment by oscarbenjamin** [comment]
I'm going to reopen this because I think that `linsolve` should work with immutable matrices. In general I would like to phase out non-`Basic` mutable matrices so I think we need all APIs to work with immutable matrices.

This can be fixed by adding a call to `as_mutable` inside `linsolve`.

**Comment by sylee957** [comment]
Actually, I would think that casting to the `MutableDenseMatrix` would not be the best idea since it can introduce redundancy to other stuff like `SparseMatrix`

What I read about the code in `linsolve`, is that it is using the wrong type check with `Matrix`, which should be replaced with `MatrixBase`.
So comparison with `Matrix` would have to be changed with `MatrixBase`.

But I also see some things wrong with `gauss_jordan_solve` itself with the immutable matrix.

**Comment by oscarbenjamin** [comment]
Does `linsolve` actually do anything clever with sparse matrices?

**Comment by oscarbenjamin** [comment]
```julia
In [15]: linsolve((ImmutableSparseMatrix.eye(20), ones(20, 1)))                                                                                               
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-15-1233698b97ab> in <module>
----> 1 linsolve((ImmutableSparseMatrix.eye(20), ones(20, 1)))

~/current/sympy/sympy/sympy/solvers/solveset.py in linsolve(system, *symbols)
   2465                     symbols for which a solution is being sought must
   2466                     be given as a sequence, too.
-> 2467                 '''))
   2468             system = [
   2469                 _mexpand(i.lhs - i.rhs if isinstance(i, Eq) else i,

ValueError: 
When passing a system of equations, the explicit symbols for which a
solution is being sought must be given as a sequence, too.
```
