### ISSUE TITLE
Travis failing due to conda removing setuptools

### ISSUE THREAD

**Issue by oscarbenjamin** [sympy/sympy#17736]
Tests are failing on unrelated PRs. See e.g.:
https://travis-ci.org/sympy/sympy/builds/598249776?utm_source=github_status&utm_medium=notification
https://travis-ci.org/sympy/sympy/jobs/598249791

The error is:
```
RemoveError: 'setuptools' is a dependency of conda and cannot be removed from
conda's operating environment.
```

**Comment by ethankward** [comment]
There is a workaround [here](https://github.com/conda/conda/issues/9337#issuecomment-542462030).

**Comment by oscarbenjamin** [comment]
Maybe this is fixed:
https://github.com/conda/conda/issues/9337#issuecomment-542873350

**Comment by oscarbenjamin** [comment]
I think it's fixed.
