### ISSUE TITLE
[Feature Request]: add 'jupyter' or 'qtconsole' as isympy -c option

### ISSUE THREAD

**Issue by stevenleeS0ht** [sympy/sympy#17733]
It would be awesome if add 'jupyter' to isympy -c option for jupyter qtconsole.

**Comment by stevenleeS0ht** [comment]
@asmeurer , @certik , @smichr , what's your opinion on this proposal?

In my point view, qtconsole have better support on formula and plotting display.

**Comment by certik** [comment]
I think that's fine with me.

**Comment by asmeurer** [comment]
I think the option should be 'qtconsole' to open the qtconsole. Jupyter means a lot of things, and most people associate it with the notebook. 

This also basically duplicates https://github.com/sympy/sympy/issues/5731.
