### ISSUE TITLE
eigenvector fails for this matrix

### ISSUE THREAD

**Issue by zhedie** [sympy/sympy#17732]
Sympy fails when getting the eigenvector of the following matrix with the codes:

```python
Delta, omega_m, G=sympy.symbols('Delta, omega_m, G', real=True)
chi=sympy.diag(1,1,-1,-1)
M=sympy.Matrix([[-Delta, G, 0, G],
               [G, omega_m, G, 0],
               [0, G, -Delta, G],
               [G, 0, G, omega_m]])
H=chi * M
P,D=H.eigenvects()

NotImplementedError: Can't evaluate eigenvector for eigenvalue -sqrt(Delta**2/2 + omega_m**2/2 - sqrt(Delta**4 - 2*Delta**2*omega_m**2 - 16*Delta*G**2*omega_m + omega_m**4)/2)
```
How can I get this solved? Thanks.

**Comment by ethankward** [comment]
As a workaround, you can declare your variables to be positive instead of simply real.

**Comment by zhedie** [comment]
Yean, you are right maybe. But I need the solution for some parameters with negative value.
I find the code works with sympy=1.1 but fails with sympy=1.4.
