### ISSUE TITLE
lambdify: some sympy.functions.special.polynomials not working 

### ISSUE THREAD

**Issue by PrometheusPi** [sympy/sympy#17746]
I wanted to `lambdify` a function that contains a `laguerre` function.
```python
import sympy as sym

x = sym.symbols("x")
n = sym.symbols("n")

tmp = sym.lambdify((x,n), sym.laguerre(n, x))

tmp(1,1)
```
Calling the function `tmp` resulted in the error:
```
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-72-8bd08f449acf> in <module>()
----> 1 tmp(1,1)

~/anaconda/install/envs/jupyter/lib/python3.6/site-packages/numpy/__init__.py in <lambda>(_Dummy_156, _Dummy_157)

NameError: name 'laguerre' is not defined
```

The same occurs for other `sympy.functions.special.polynomials`like 
 - `hermite(n,x)`
 - `chebyshevt(n,x)`
 - `legendre(n,x)`

but not for e.g.:
  - `gegenbauer(0,n,x)`

Why is this error thrown? (Is it not yet implemented? Do I have to define/load something before that is so far missed?)

In case that this is the current status of sympy:
Is there a way to replace the currently  missing name `laguerre` by e.g.: `scipy.special.laguerre` or (a bit more complicated) `numpy.polynomial.laguerre.lagval` in the code?
How could I do that? (Following the discussion in #7232 (on a different topic), I got the impression that function need an extra "lambdify-implementation".)

**Comment by asmeurer** [comment]
What version of symPy are you using? This works for me in 1.4. 

SciPy support was add recently. But you can work around it for older versions by specifying the replacement manually, like

```py
lambdify((n, x), laguerre(n, x), ['numpy', {'laguerre': scipy.special.eval_laguerre}])
```

See the documentation for lambdify for more info.

**Comment by PrometheusPi** [comment]
@asmeurer Thanks for your quick reply. 

Sorry for not stating the version right away. I am working with version `1.1.1`.
Your solution for older versions worked perfectly. 

Thank you very much for your help.

(I will close the issue now, since it is solved.)
