### ISSUE TITLE
Break sympy.physics.vector.frame.RefererenceFrame.orient() into 5 seperate methods.

### ISSUE THREAD

**Issue by moorepants** [sympy/sympy#17758]
`sympy.physics.vector.frame.RefererenceFrame.orient()` is a very long, complicated, and unwieldy method and there are just two many different types of arguments that it accepts, which requires very detailed explanations. It should be broken up into sub-methods. These could be:

`ReferenceFrame.orient_body()`
`orient_axis()`
`orient_dcm()`
etc.

**Comment by moorepants** [comment]
We created "Orienter" classes in sympy.vector. Maybe we should do the same here.

**Comment by sksingh1202** [comment]
I would like to try to work on this issue.

**Comment by sksingh1202** [comment]
I was trying to understand the method orient() and I think that there is probably some minor issue with the following part of the code:
for i, v in enumerate(amounts):
                if not isinstance(v, Vector):
                    amounts[i] = sympify(v)
Shouldn't it be ""if isinstance(v, Vector):"" in the second line instead of ""if not isinstance(v, Vector)"" and then raising a type error if v is not an instance of Vector.
@moorepants could you please check it out, whether I have mistaken it or not.

**Comment by moorepants** [comment]
I don't see any apparent issue with the lines you show.

**Comment by sksingh1202** [comment]
Thank you very much but shouldn't the amount of rotation be assigned to the array "amounts[ ]" once we have checked whether the input "v" is of the type Vector which has not been checked elsewhere within the function? And according to the lines which I have mentioned, the amount of rotation is being assigned to the array "amounts[ ]" if "v" is not an instance of Vector.
Could you please help me out in understanding these lines.
Thank you.

**Comment by sksingh1202** [comment]
I have read the code further and found out that it has been verified that the argument "v" is an instance of the type Vector in the later part of the code in the same method. Also, I have now understood the purpose of the lines to which I had referred earlier too.
Thank you very much for your help. :)

**Comment by sksingh1202** [comment]
I have gone through the method "orient". However, I am still not very sure that whether I have to create new methods viz. orient_body( ), orient_axis( ) etc. in the same file "frame.py" or whether I have to make a new class with sub-classes for each method and put it in a new file in the same way as it has already been done for "orienters.py"? @moorepants could you please help.

**Comment by moorepants** [comment]
These should be added to the existing ReferenceFrame class in that file.

**Comment by sksingh1202** [comment]
Thank you very much. I am almost done with the five methods and would try to open a PR very soon.

**Comment by sksingh1202** [comment]
I have opened a new PR for this issue but it has not passed all the checks. I tried to view the details given by Travis CI but wasn't unable to understand them. Could you please suggest regarding what can be done further.

**Comment by moorepants** [comment]
Yes, it is still open. If you want to take it up, please assess @ sksingh1202's work and if it is worth building on, build your commits on theirs.

**Comment by sidhu1012** [comment]
@moorepants The new functions should be private  and the existing orient() should call those private methods? This wont change the api.
Or shall the old orient() be replaced by new 5 orient functions?

**Comment by moorepants** [comment]
Neither. @sksingh1202 had the right idea in his PR. Make 5 new public methods and make the `orient()` method call those methods. The changes should be backwards compatible. Eventually `orient()` could be deprecated if it makes sense to.

**Comment by sidhu1012** [comment]
@moorepants I shall start a new PR, @sksingh1202 's PR is messing with code it shouldn't.
Starting fresh would save both time and energy.

**Comment by moorepants** [comment]
I think there is a single incorrectly committed file, which can be undone on that PR. It seems to me that his code is on the right track, so building on it is a good idea. You could start by verifying the tests run and making some explicit tests for the new methods.

**Comment by sidhu1012** [comment]
@moorepants  I tried working on @sksingh1202 PR but  it gave error:
remote: Permission to sksingh1202/sympy.git denied to sidhu1012.
fatal: unable to access 'https://github.com/sksingh1202/sympy.git/': The requested URL returned error: 403

**Comment by sidhu1012** [comment]
@moorepants Am I doing something wrong or shall I start a new PR?

**Comment by moorepants** [comment]
This works for me:

```
git fetch upstream pull/18798/head:pr-18798 && git checkout pr-18798
```

`upstream` points to this repo on my machine.

**Comment by sidhu1012** [comment]
Thanks @moorepants it worked
