### ISSUE TITLE
PR #16762 causes a reduction of precision to 16 significant digits

### ISSUE THREAD

**Issue by zachetienne** [sympy/sympy#17756]
If original expressions contained more than 16 significant digits, PR #16762 (merged) will occasionally result in a loss of significance to 16 significant digits.

Below is an example code that demonstrates the issue. The result from the final `print(eval)` should be `0.561584136985528994504178506743` to 30 significant digits (using Mathematica & SymPy 1.4 to confirm). Instead the result is off at the 16th significant digit.

With the below example code, I was able to quickly `git bisect` the problem to PR #16762. Note that this issue is independent of the one I had originally reported regarding PR #16762 (i.e., #17735 ) and was patched via PR #17740 .

```python
from sympy import *
M,r_at_max_density,x1,x2,x5,x7,x8,x10,x11,x12 = symbols('M r_at_max_density x1 x2 x5 x7 x8 x10 x11 x12',real=True)

expr = sqrt(4*M*x2**2*x5*(r_at_max_density**4 + x1*x10 - 2*x1*x11 - x12*(-x1 + x10))**2/(r_at_max_density**3*x7*x8**2*(x10 - 3*x11 + 2*x12)**2) + 1)/2
expr = expr.subs(x5,N('0.0977149162432475031936229342404',30))
expr = expr.subs(M, N('0.35190117650401031568208054523',30))
expr = expr.subs(x2, N('0.230823341810098541835951942887',30))
expr = expr.subs(x7, N('0.428572274457365406350449494195',30))

expr = expr.subs(x8, N('0.0966594956075474769169134801223',30))
# print(expr)
## ^ above is where this breaks.

expr = expr.subs(r_at_max_density,N('0.390911862903463913632151616184',30))
expr = expr.subs(x10,N('0.152812084558656566271750185933',30))
expr = expr.subs(x11,N('0.137562344465103337106561623432',30))
expr = expr.subs(x12,N('0.174259178881496659302933610355',30))
expr = expr.subs(x1,N('0.220745448491223779615401870086',30))

print(expr)
print(Abs(expr - N('0.561584136985528994504178506743',30)))
assert Abs(expr - N('0.561584136985528994504178506743',30)) < 1e-29
```
After analyzing the result of each `subs()` from SymPy with Mathematica, I was able to backtrace the loss of precision to the `x8` substitution, during which

```
sqrt(1 + 0.0170992456333788667034850458615*(r_at_max_density**4 + x1*x10 - 2*x1*x11 - x12*(-x1 + x10))**2/(r_at_max_density**3*x8**2*(x10 - 3*x11 + 2*x12)**2))/2
```

becomes

```
0.676416129939598001037750342485*sqrt(0.546401770664503357632415162049 + (r_at_max_density**4 + x1*x10 - 2*x1*x11 - x12*(-x1 + x10))**2/(r_at_max_density**3*(x10 - 3*x11 + 2*x12)**2))
```

In SymPy 1.4 (or if the original commit, c1e25a4, is reverted), the post-subs() expression is very different (one might even argue that it is simpler):

```
sqrt(1 + 1.83015512336985250895612217047*(r_at_max_density**4 + x1*x10 - 2*x1*x11 - x12*(-x1 + x10))**2/(r_at_max_density**3*(x10 - 3*x11 + 2*x12)**2))/2
```
Analyzing the PR, I noticed that there is a suspicious multiplication by 1.0, which (when converting the expression to a string) reduces the digits of significance to 16. I added a comment to the affected line on the commit for PR #16762 : https://github.com/sympy/sympy/commit/c1e25a445f1c27829ea8cf0e04dbdd6d749834ce 

That line of code is still in master.

**Comment by zachetienne** [comment]
To follow up, the line of commit c1e25a445f1c27829ea8cf0e04dbdd6d749834ce in question is:

```python
big = 1.0*abs(i)
```

If I increase the precision to 50, *a la*:
```python
big = (1.0*abs(i)).evalf(50)
```
then the problem disappears. Further if I adjust precision to 20 the assertion in the above example code fails with 20 significant digits of agreement. 

So I'm now becoming convinced that this line of code is at fault, but how to fix? We can't assume a limited precision on any evaluation after all.

**Comment by smichr** [comment]
With this
```python
            c, m = zip(*[i.as_coeff_Mul() for i in self.args])
            if any(i.is_Float for i in c):  # XXX should this always be done?
                big = -1
                for i in c:
                    if abs(i) >= big:
                        big = abs(i)
                if big > 0 and big != 1:
                    from sympy.functions.elementary.complexes import sign
                    bigs = (big, -big)
                    c = [sign(i) if i in bigs else i/big for i in c]
                    addpow = Add(*[c*m for c, m in zip(c, m)])**e
                    return big**e*addpow
```
I get the following[*] for `expr` after the `x8` substitution,
```python
0.676416129939598001037750342485*sqrt(0.546401770664503357632415162049 + (r_at_max_density**4 + x1*x10 - 2*x1*x11 - x12*(-x1 + x10))**2/(r_at_max_density**3*(x10- 3*x11 + 2*x12)**2))
```
Note: I actually had to do this somewhat manually, but would be interested to see if this resolves the issue.

I'm not sure why `1.0*abs(i)` would cause the problem. The intent of the `float` and making `big` to be a Float was: 1) only do this if some coefficient is a Float since (I think) `factor_terms` will handle the Rational case 2) coefficients equal to +/-|big| will be +/-1 and all others will be Float if the normalizing `big` is Float. This 2nd goal can be met by just using `sign` for coefficients matching `big` and letting the other terms take care of themselves: if `big` is Float then everything will become a Float and if not, then only the coefficients that were already Float will become Floats, e.g. `sqrt(3 + .3*x) -> sqrt(3)*(sqrt(1 + 0.1*x)`

**Comment by zachetienne** [comment]
@smichr : Thanks for the new patch! It fixes the problem. With it my SymPy-based code's unit tests (which involve validating hundreds of complicated expressions against trusted versions) all pass again!

Regarding the issue of `1.0*abs(i)`: I found that the `i`'s in `for i in c` included Rationals from the expression. Then, for example if `i` was `2/3`, setting `big` to `1.0*abs(i)` was setting the value of `big` to something like `0.6666666666666667`, which is incorrect at the 16th significant digit.

I'll create a PR.

**Comment by zachetienne** [comment]
@smichr : Well drat. The SymPy testing infrastructure fails with your latest patch (PR #17764 ):

```
File "/home/travis/virtualenv/python3.8.0/lib/python3.8/site-packages/sympy-1.5.dev0-py3.8.egg/sympy/core/expr.py", line 2134, in sympy.core.expr.Expr.as_content_primitive
Failed example:
    ((5*(x*(1 + y)) + 2.0*x*(3 + 3*y))**2).as_content_primitive()
Expected:
    (1, 121.0*x**2*(y + 1)**2)
Got:
    (25, 4.84*x**2*(y + 1)**2)
```

Any thoughts?

**Comment by smichr** [comment]
I suspect the doctest (to more accurately show what it intended) should be written as `((x*(1 + y) + 0.4*x*(3 + 3*y))**2).as_content_primitive()` and the failing test 2993 should be
```python
def test_issue_2993():
    x = Symbol('x')
    assert str((2.3*x - 4)**0.3) == '2**(2/3)*(0.575*x - 1)**0.3'
    assert str((2.3*x + 4)**0.3) == '2**(2/3)**(0.575*x + 1)**0.3'
    assert str((-2.3*x + 4)**0.3) == '2**(2/3)**(1 - 0.575*x)**0.3'
    assert str((-2.3*x - 4)**0.3) == '2**(2/3)**(-0.575*x - 1)**0.3'
    assert str((2.3*x - 2)**0.3) == '2**(1/3)*(x - 0.869565217391304)**0.3'
    assert str((-2.3*x - 2)**0.3) == '2**(1/3)*(-x - 0.869565217391304)**0.3'
    assert str((-2.3*x + 2)**0.3) == '2**(1/3)*(0.869565217391304 - x)**0.3'
    assert str((2.3*x + 2)**0.3) == '2**(1/3)*(x + 0.869565217391304)**0.3'
    assert str((2.3*x - 4)**Rational(1, 3)) == '2**(2/3)*(0.575*x - 1)**(1/3)'
    eq = (2.3*x + 4)
    assert eq**2 == 16.0*(0.575*x + 1)**2
    assert (1/eq).args == (eq, -1)  # don't change trivial power
    # issue 17735
    q=.5*exp(x) - .5*exp(-x) + 0.1
    assert int((q**2).subs(x, 1)) == 1

```

**Comment by zachetienne** [comment]
Thanks @smichr! Could you also comment on the failure:

```
________________ sympy/core/tests/test_power.py:test_issue_2993 ________________
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.8.0/lib/python3.8/site-packages/sympy-1.5.dev0-py3.8.egg/sympy/utilities/runtests.py", line 1317, in _timeout
    function()
  File "/home/travis/virtualenv/python3.8.0/lib/python3.8/site-packages/sympy-1.5.dev0-py3.8.egg/sympy/core/tests/test_power.py", line 470, in test_issue_2993
    assert str((2.3*x - 4)**Rational(1, 3)) == '1.5874010519682*(0.575*x - 1)**(1/3)'
AssertionError
```

**Comment by zachetienne** [comment]
@smichr: I applied your suggested fixes to the PR. Both failed. 

For the doctest, I think maybe you meant something like

`(25*(x*(1 + y) + 0.4*x*(3 + 3*y))**2).as_content_primitive()`

instead of

`((x*(1 + y) + 0.4*x*(3 + 3*y))**2).as_content_primitive()`, as the original was

`((5*(x*(1 + y)) + 2.0*x*(3 + 3*y))**2).as_content_primitive()`?

Or did you mean to change the result of the doctest to

`(1, 4.84*x**2*(y + 1)**2)`?

Also I'm not sure what's going on with the continued failure of 

```python
assert str((2.3*x - 4)**0.3) == '2**(2/3)*(0.575*x - 1)**0.3'
```
and the like.

**Comment by smichr** [comment]
> Or did you mean to change the result of the doctest to

yes

**Comment by smichr** [comment]
> for the #2993 test

Ah. 
```python
def test_issue_2993():
    x = Symbol('x')
    assert str((2.3*x - 4)**0.3) == '1.5157165665104*(0.575*x - 1)**0.3'
    assert str((2.3*x + 4)**0.3) == '1.5157165665104**(0.575*x + 1)**0.3'
    assert str((-2.3*x + 4)**0.3) == '1.5157165665104**(1 - 0.575*x)**0.3'
    assert str((-2.3*x - 4)**0.3) == '1.5157165665104**(-0.575*x - 1)**0.3'
    assert str((2.3*x - 2)**0.3) == '1.28386201800527*(x - 0.869565217391304)**0.3'
    assert str((-2.3*x - 2)**0.3) == '1.28386201800527*(-x - 0.869565217391304)**0.3'
    assert str((-2.3*x + 2)**0.3) == '1.28386201800527*(0.869565217391304 - x)**0.3'
    assert str((2.3*x + 2)**0.3) == '1.28386201800527*(x + 0.869565217391304)**0.3'
    assert str((2.3*x - 4)**Rational(1, 3)) == '2**(2/3)*(0.575*x - 1)**(1/3)'
    eq = (2.3*x + 4)
    assert eq**2 == 16.0*(0.575*x + 1)**2
    assert (1/eq).args == (eq, -1)  # don't change trivial power
    # issue 17735
    q=.5*exp(x) - .5*exp(-x) + 0.1
    assert int((q**2).subs(x, 1)) == 1
```

And if you replace 4 in the first assertion with `pi.n(25)` does the answer, `1.409759279075053698919295*(0.732112738222718487993671*x - 1)**0.3` differ from what you get in master (and thus demonstrate that the issue you raised is fixed)?

**Comment by smichr** [comment]
What...that is what the test was originally in 2993...try it in your local modified master to see what `str((2.3*x - 4)**0.3)` gives.

**Comment by zachetienne** [comment]
@smichr : The build with the correct doctest result (`(1, 4.84*x**2*(y + 1)**2)`) passes the doctest! (See https://travis-ci.org/sympy/sympy/jobs/600435937)

Meanwhile, in my local modified master, `isympy` gives me:

```
In [1]: x = Symbol('x')

In [2]: str((2.3*x - 4)**0.3)
Out[2]: '1.5157165665104*(0.575*x - 1)**0.3'
```
consistent with the original `test_issue_2993()`. So I went ahead and replaced the `test_issue_2993()` with the version you just sent, with two exceptions

1) I replaced the `1.5157165665104**`'s with `1.5157165665104*` (those were clearly just small typos on your part; see https://github.com/zachetienne/sympy/commit/434800fa2cf0011362eaa0404365d5ab94e74413 for the specific differences).

2) The test 
```python
eq = (2.3*x + 4)
assert eq**2 == 16.0*(0.575*x + 1)**2
```
fails because the *exact* number 16 is pulled out of the expression with the latest patch, yielding 
```python
eq**2 == 16*(0.575*x + 1)**2
```
I updated the test accordingly.

For completeness, the full PR is here:
https://github.com/sympy/sympy/pull/17764/files

Tests are ongoing on Travis, and once complete I'll update this comment. I anticipate the tests will pass, but we'll see.

**Comment by smichr** [comment]
Looking good. What does `str((2.3*x - pi.n(25))**0.3)` give in your branch and is it different than master? This would be a more targeted test for the issue.

**Comment by zachetienne** [comment]
@smichr : 

> What does str((2.3*x - pi.n(25))**0.3) give in your branch and is it different than master? This would be a more targeted test for the issue.

After a fresh `pip install -U git+https://github.com/sympy/sympy.git`, then running `str((2.3*x - pi.n(25))**0.3)` in `isympy` yields:

```
'1.409759279075053698919295*(0.732112738222718487993671*x - 1)**0.3'
```

Doing the same, but using my branch, yields
```
'1.409759279075053698919295*(0.732112738222718487993671*x - 1)**0.3'
```

... exactly the same result. So it doesn't seem to reproduce the problem.

**Comment by smichr** [comment]
What if you change the 2.3 to 3.3?

**Comment by zachetienne** [comment]
in SymPy's current master, that yields:
```
'1.43071846409179*(x - 0.9519977738150889113852785)**0.3'
```
in my branch:
```
'1.43071846409179*(x - 0.9519977738150889113852785)**0.3'
```
Again, same result. 

I simplified my unit test for this issue somewhat and just committed. By the way, the latest Travis build with the PR associated with this ticket (#17764 ; though prior to my unit test simplification patch) seems to be well on its way to passing without problem: https://travis-ci.org/sympy/sympy/builds/600453822 .

**Comment by smichr** [comment]
> Again, same result.

hmm...well thanks for indulging my curiosity. BTW, if you want a Float that captures all the digits you provide you can do `Float('.12345678901234567890', '')`.
