### ISSUE TITLE
Point.vel() should calculate the velocity if possible

### ISSUE THREAD

**Issue by moorepants** [sympy/sympy#17761]
If you specify the orientation of two reference frames and then ask for the angular velocity between the two reference frames the angular velocity will be calculated. But if you try to do the same thing with velocities, this doesn't work. See below:

```
In [1]: import sympy as sm                                                                               

In [2]: import sympy.physics.mechanics as me                                                             

In [3]: A = me.ReferenceFrame('A')                                                                       

In [5]: q = me.dynamicsymbols('q')                                                                       

In [6]: B = A.orientnew('B', 'Axis', (q, A.x))                                                           

In [7]: B.ang_vel_in(A)                                                                                  
Out[7]: q'*A.x

In [9]: P = me.Point('P')                                                                                

In [10]: Q = me.Point('Q')                                                                               

In [11]: r = q*A.x + 2*q*A.y                                                                             

In [12]: Q.set_pos(P, r)                                                                                 

In [13]: Q.vel(A)                                                                                        
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-13-0fc8041904cc> in <module>
----> 1 Q.vel(A)

~/miniconda3/lib/python3.6/site-packages/sympy/physics/vector/point.py in vel(self, frame)
    453         if not (frame in self._vel_dict):
    454             raise ValueError('Velocity of point ' + self.name + ' has not been'
--> 455                              ' defined in ReferenceFrame ' + frame.name)
    456         return self._vel_dict[frame]
    457 

ValueError: Velocity of point Q has not been defined in ReferenceFrame A
```

The expected result of the `Q.vel(A)` should be:

```
In [14]: r.dt(A)                                                                                         
Out[14]: q'*A.x + 2*q'*A.y
```

I think that this is possible. Maybe there is a reason it isn't implemented. But we should try to implement it because it is confusing why this works for orientations and not positions.

**Comment by grassknoted** [comment]
Hi @moorepants, I think I could fix this. It would be implemented as a part of `ReferenceFrame` in `sympy/physics/vector/frame.py`, right?

**Comment by moorepants** [comment]
No, it is part of Point. There are some nuances here and likely not a trivial PR to tackle. I'd recommend some simpler ones first if you are new to sympy and dynamics.

**Comment by grassknoted** [comment]
Sure, understood. Thank you @moorepants .

**Comment by sidhu1012** [comment]
> No, it is part of Point. There are some nuances here and likely not a trivial PR to tackle. I'd recommend some simpler ones first if you are new to sympy and dynamics.

I would like to work on this issue.

**Comment by sidhu1012** [comment]
The current Point.vel() returns velocity already defined in a reference frame , it doesn't calculate velocity between two points , so it would require a new function to calculate velocity between two points.

**Comment by moorepants** [comment]
The idea is that if there is sufficient information about the relative position of points, that Point.vel() can determine there is sufficient information and calculate the velocity. You should study how ReferenceFrame does this with ang_vel().

**Comment by sidhu1012** [comment]
> The idea is that if there is sufficient information about the relative position of points, that Point.vel() can determine there is sufficient information and calculate the velocity. You should study how ReferenceFrame does this with ang_vel().

Okay on it!!

**Comment by sidhu1012** [comment]
@moorepants pls check my PR and tell if something's missing or wrong.
