### ISSUE TITLE
linsolve does not accept ImmutableMatrix

### ISSUE THREAD

**Issue by sharmaeklavya2** [sympy/sympy#17762]
`solvers.linsolve` doesn't accept an `ImmutableMatrix` as the augmented-matrix form of linear equations.

```pycon
>>> from sympy import ImmutableMatrix, Matrix, linsolve
>>> A = ImmutableMatrix([[1, 1, 7], [1, -1, 3]])
>>> linsolve(A)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../venv/lib/python3.7/site-packages/sympy/solvers/solveset.py", line 2185, in linsolve
    raise ValueError("Invalid arguments")
ValueError: Invalid arguments
>>> linsolve(Matrix(A))
{(5, 2)}
```

It took me a long time to figure out that using `ImmutableMatrix` was the reason for the error. I found this out after looking in the code, which has instances of `isinstance(system, Matrix)` at many places. I think we can fix this by checking for a base type, perhaps `MatrixBase`.

**Comment by sylee957** [comment]
Also related to #17722.
