### ISSUE TITLE
update docstrings to show how to create many reference frames (and points)

### ISSUE THREAD

**Issue by moorepants** [sympy/sympy#17760]
It is common to do:

```
from sympy.physics.vector import ReferenceFrame
A = ReferenceFrame('A')
B = ReferenceFrame('B')
C = ReferenceFrame('C')
D = ReferenceFrame('D')
```

It would be nice to do:

```
A, B, C, D = reference_frames('A, B, C, D')
```

like `sympy.symbols()`. It would need to support setting the options for the frames too.

Same goes for `sympy.physics.vector.Point()`.

**Comment by smichr** [comment]
```python
>>> from sympy.physics.vector import ReferenceFrame
>>> A,B = symbols('A B', cls=ReferenceFrame)
```

What options do you want to set?

**Comment by moorepants** [comment]
Oh, yes, I forgot about that!

The `__init__` method of ReferenceFrame has several optional parameters. Point may also.

**Comment by smichr** [comment]
```python
>>> from sympy.physics.vector import ReferenceFrame, Point
... A,B = symbols('A B', cls=ReferenceFrame, indices=('1', '2', '3'))
>>> A.indices
(1, 2, 3)
```

**Comment by moorepants** [comment]
Great. Gonna leave this open until I (or someone) adds this to the documentation as an example.

**Comment by grassknoted** [comment]
Hi @moorepants , I've submitted a PR that updates the doctrings, as you said. Please do have a look at it!
