### ISSUE TITLE
linear_coeffs fails for pure sp.numbers.Float expressions

### ISSUE THREAD

**Issue by mcsoini** [sympy/sympy#17774]
The `sympy.solvers.solveset.linear_coeffs` method (and therefore also the `linear_eq_to_matrix` method) throws an unjustified error if the input expression `eq` is a constant numerical value of type `sympy.numbers.Float`. For other built-in numerical types (and implicit conversion of integers) this works as expected:

```python
In [19]: import sympy as sp
    ...: from sympy.solvers.solveset import linear_coeffs
    ...: syms = sp.symbols('x y')
    ...: x, y = syms
In [20]: linear_coeffs(1, *syms)  # works as expected
Out[20]: [0, 0, 1]
In [21]: linear_coeffs(sp.numbers.One(), *syms)  # works as expected
Out[21]: [0, 0, 1]
In [22]: linear_coeffs(sp.numbers.Integer(1), *syms)  # works as expected
Out[22]: [0, 0, 1]
In [23]: linear_coeffs(sp.numbers.Float(1.0), *syms)  # throws ValueError
Traceback (most recent call last):
ValueError: nonlinear term encountered: 1.00000000000000
```

If the expression has a variable dependency, it works as well:
```python
In [24]: linear_coeffs(x * sp.numbers.Float(1.0), *syms)  # works as expected
Out[24]: [1.00000000000000, 0, 0]
```

I traced this back to the `core.numbers.as_coeff_add` method, which contains a `self.is_Rational` condition. Ultimately this keeps the `Float` in the `linear_coeffs` local `terms` variable, which makes the expression look nonlinear.
(if the expression is not a pure number, the `core.expr.Expr.as_coeff_add` method is used, which works as expected).
 
I understand that the `self.is_Rational` condition is probably necessary for other applications, such as simplifications. What would be a good fix for this? An early check for constant expressions in  `linear_coeffs`?

**Comment by smichr** [comment]
Perhaps
```python
    eq = _sympify(eq)
    if not eq.has(*syms):
        return [S.Zero]*len(syms) + [eq]
    c, terms = eq.as_coeff_add(*syms)
```
tested with
```python
>>> linear_coeffs(1.,x)
[0, 1.00000000000000]
>>> linear_coeffs(1.)
[1.00000000000000]
```

**Comment by mcsoini** [comment]
Thanks @smichr, that does the job. I was patching this as 
```python
    if isinstance(eq, sp.numbers.Float):
        c, terms = eq, tuple()
    else:
        c, terms = _sympify(eq).as_coeff_add(*syms)
```
but returning early is of course preferable.
