### ISSUE TITLE
linsolve returns wrong result when a line of the matrix is negative

### ISSUE THREAD

**Issue by AstusRush** [sympy/sympy#17782]
linsolve(Matrix([[1, 1, 1, 6], [-1, -2, -4, -11], [1, 4, 16, 27]])) calculates {(3, 9/2, 1/2)}
The correct result would be {(3, 2, 1)}
linsolve(Matrix([[1, 1, 1, 6], [1, 2, 4, 11], [1, 4, 16, 27]])) however returns the correct result.
Thus I assume that the second row of the matrix is the problem.
A possible solution would be to check all rows of a matrix that is an argument of linsolve and make them positive if they are completely negative.

**Comment by grassknoted** [comment]
Hi @AstusRush , I tried the following to reproduce the bug:
```
>>> from sympy import Matrix, linsolve
>>> linsolve(Matrix([[1, 1, 1, 6], [-1, -2, -4, -11], [1, 4, 16, 27]]))
{(3, 2, 1)}
>>> linsolve(Matrix([[1, 1, 1, 6], [1, 2, 4, 11], [1, 4, 16, 27]])) 
{(3, 2, 1)}
>>> sympy.__version__
'1.4'
```
Seems to me like it is working fine.
Could you please confirm the version of sympy you are using, and any other specific steps you took to get the error.

**Comment by AstusRush** [comment]
I am unable to reproduce the problem. It now always works correctly despite not changing anything on my code. Previously it consistently produced the wrong output...

Since the problem seems to be resolved I will close this issue.
