### ISSUE TITLE
Wrong limit

### ISSUE THREAD

**Issue by Trollipop42** [sympy/sympy#17792]
For
`n=Symbol('n')`
`limit(factorial(n)/sqrt(n)*(E/n)**n,n,oo)`
sympy returns the correct value `sqrt(2*pi)`.

But
`n = Symbol('n',positive=True,integer=True)`
`limit(factorial(n)/sqrt(n)*(E/n)**n,n,oo)`
sympy returns 0.

sympy version 1.4

**Comment by namannimmo10** [comment]
@skirpichev What needs to be done to fix this issue?
