### ISSUE TITLE
limits argument of sympy.codegen.ast.Type.cast_check is not used

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#17804]
See https://github.com/sympy/sympy/blob/d85c30ef80cb6a4b9c53250bf4f549c8759b1141/sympy/codegen/ast.py#L1037. The limits argument is not used. It says the default is `default_limits`, which is not defined anywhere (I am removing the default bit from the docs in https://github.com/sympy/sympy/pull/17698 to fix a Sphinx warning).

**Comment by bjodah** [comment]
Yup, my bad. Has to be a left-over from an earlier state, safe to drop.

**Comment by rationa-kunal** [comment]
Can you explain issue !

**Comment by praneethratna** [comment]
@bjodah Hi , I'm new to open source and would like to contribute in fixing this issue , Could you please explain me about how to fix this issue?
