### ISSUE TITLE
sympify("abs(x)*5",evaluate=False) crashes

### ISSUE THREAD

**Issue by Volker-Weissmann** [sympy/sympy#17811]
Long story short: The following program crashes:
```
import sympy
sympy.sympify("abs(x)*5",evaluate=False)
```
with the message:
> Traceback (most recent call last):
>   File "bugreport2.py", line 3, in <module>
>     sympy.sympify("abs(x)*5",evaluate=False)
>   File "/home/volker/.local/lib/python3.7/site-packages/sympy/core/sympify.py", line 384, in sympify
>     expr = parse_expr(a, local_dict=locals, transformations=transformations, evaluate=evaluate)
>   File "/home/volker/.local/lib/python3.7/site-packages/sympy/parsing/sympy_parser.py", line 964, in parse_expr
>     code = compile(evaluateFalse(code), '<string>', 'eval')
>   File "/home/volker/.local/lib/python3.7/site-packages/sympy/parsing/sympy_parser.py", line 974, in evaluateFalse
>     node = EvaluateFalseTransformer().visit(node)
>   File "/usr/lib/python3.7/ast.py", line 262, in visit
>     return visitor(node)
>   File "/usr/lib/python3.7/ast.py", line 317, in generic_visit
>     value = self.visit(value)
>   File "/usr/lib/python3.7/ast.py", line 262, in visit
>     return visitor(node)
>   File "/usr/lib/python3.7/ast.py", line 326, in generic_visit
>     new_node = self.visit(old_value)
>   File "/usr/lib/python3.7/ast.py", line 262, in visit
>     return visitor(node)
>   File "/home/volker/.local/lib/python3.7/site-packages/sympy/parsing/sympy_parser.py", line 1047, in visit_BinOp
>     new_node.args = self.flatten(new_node.args, sympy_class)
>   File "/home/volker/.local/lib/python3.7/site-packages/sympy/parsing/sympy_parser.py", line 996, in flatten
>     if isinstance(arg, ast.Call) and arg.func.id == func:
> AttributeError: 'Call' object has no attribute 'id'

sympy.\_\_version\_\_ is '1.4' and sys.version is '3.7.3 (default, Oct  7 2019, 12:56:13) \n[GCC 8.3.0]'

**Comment by ethankward** [comment]
I guess the desired output here is `5*Abs(x)` (not `5*abs(x)` where `abs` is a dummy function)? I'm unclear on how `sympify` is supposed to interact with built in Python functions.

**Comment by asmeurer** [comment]
The `abs` from `type(abs)` is not the same as the `abs` printed from `type(e)`. 

The key is 

```py
>>> type(type(e))
<class 'sympy.core.function.UndefinedFunction'>
```

But this should be `Abs`. 

`abs` should be parsed as the built-in `abs`. Is parse_expr not using the builtins?
