### ISSUE TITLE
Migrate docs Makefile to use Sphinx makefile mode

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#17817]
If you look at Makefiles generated by a newer version of Sphinx, they use

```makefile

# Catch-all target: route all unknown targets to Sphinx using the new
# "make mode" option.  $(O) is meant as a shortcut for $(SPHINXOPTS).
%: Makefile
	@$(SPHINXBUILD) -M $@ "$(SOURCEDIR)" "$(BUILDDIR)" $(SPHINXOPTS) $(O)
```

See for instance the [one in sphinx-math-dollar](https://github.com/sympy/sphinx-math-dollar/blob/master/docs/Makefile). 

We should migrate our Makeflie to use this. That way we can use the newer features of Sphinx that aren't hardcoded into our Makefile, like `make latexpdf`. 

This is not straightforward because we have some custom modifications in our Makefile, so those will need to be left intact. 

We should also add a `make all` target that makes everything that is built on Travis (html, man, and pdf).

**Comment by sylee957** [comment]
I had an another idea of using a python script instead of `makefile` that can have same functionality as the original one. Which can be more better for Windows users and can resolve #16460.

**Comment by asmeurer** [comment]
I think Sphinx also supports makefile mode for make.bat. We would need to add support for the extra things to the make.bat as well. If batch is too hard to write we can rewrite in Python, but I think for Unix we should stick to the Makefile because make automatically handles dependencies and not rebuilding things that are already built (related: https://github.com/sympy/sympy/issues/11715).
