### ISSUE TITLE
Sympy does not know, that "7" is real.

### ISSUE THREAD

**Issue by Volker-Weissmann** [sympy/sympy#17810]
Long story short: The following program:
```
import sympy

x = sympy.symbols("x")
f = sympy.Abs(x)
d = sympy.diff(f, x)
print(d.subs(x, 7))
```
should output 1 instead of
> Subs(Derivative(re(x), x), x, 7)
It works if we use x = sympy.symbols("x",real=True) instead, but sympy should know that 7 is real and therefore output 1.

**Comment by oscarbenjamin** [comment]
Maybe Derivative should translate `Derivative(re(x), x)` to `re(Derivative(x, x))` (at least under doit):
```julia
In [12]: Derivative(re(x), x).doit()                                                                                                                          
Out[12]: 
d        
──(re(x))
dx
```

**Comment by oscarbenjamin** [comment]
Actually I guess both abs and re are not complex differentiable so neither derivative should evaluate if x is not known to be real.

**Comment by Volker-Weissmann** [comment]
I just noticed that I mixed up the definition of real differentiable and complex differentiable on the real domain. abs(x) is real differentiable but not complex differentiable on the real domain.
For d/dx abs(x) to be one, both x and the infinitesimal differences in the definition of the derivation have to be real. Therefore it is not sufficient, that we run d.subs(x, real number), but we also have to use sympy.symbols("x", real=True). If I use sympy.symbols("x", real=True), it prints "1".

**Comment by oscarbenjamin** [comment]
I wonder if this should be changed so that it just returns unevaluated:
```julia
In [1]: abs(x).diff(x)                                                          
Out[1]: 
⎛      d                 d        ⎞        
⎜re(x)⋅──(re(x)) + im(x)⋅──(im(x))⎟⋅sign(x)
⎝      dx                dx       ⎠        
───────────────────────────────────────────
                     x 
```
