### ISSUE TITLE
sympify("N*exp(x)") crashes

### ISSUE THREAD

**Issue by Volker-Weissmann** [sympy/sympy#17812]
Long story short: The following program crashes:
```
import sympy
sympy.sympify("N*exp(x)")
```
With the message:

> Traceback (most recent call last):
>   File "sympycrash.py", line 2, in <module>
>     sympy.sympify("N*exp(x)")
>   File "/home/volker/.local/lib/python3.7/site-packages/sympy/core/sympify.py", line 384, in sympify
>     expr = parse_expr(a, local_dict=locals, transformations=transformations, evaluate=evaluate)
>   File "/home/volker/.local/lib/python3.7/site-packages/sympy/parsing/sympy_parser.py", line 966, in parse_expr
>     return eval_expr(code, local_dict, global_dict)
>   File "/home/volker/.local/lib/python3.7/site-packages/sympy/parsing/sympy_parser.py", line 879, in eval_expr
>     code, global_dict, local_dict)  # take local objects in preference
>   File "<string>", line 1, in <module>
> TypeError: unsupported operand type(s) for *: 'function' and 'exp'

sympy.\_\_version\_\_ is '1.4' and sys.version is '3.7.3 (default, Oct 7 2019, 12:56:13) \n[GCC 8.3.0]'

**Comment by ethankward** [comment]
`N` is a SymPy function. What did you expect this example to do?

**Comment by Volker-Weissmann** [comment]
> `N` is a SymPy function. What did you expect this example to do?

Oh, I'm sorry, I didn't know that "N" was a reserved function name. I thought it would return symbols("N")*exp(symbols("x")).

You can close this issue.
