### ISSUE TITLE
Wrong result for as_leading_term()

### ISSUE THREAD

**Issue by maurogaravello** [sympy/sympy#17847]
`as_leading_term()` does not properly work for `Add` expressions, when two terms simplifies.
More precisely:
```
e = 1 - cos(x) + x**6
res = e.as_leading_term(x)
```
In this case `res = x**6`, instead of `x**2 / 2`.

In the case 
```
e = 1 + cos(x) + x**6
res = e.as_leading_term(x)
```
the result `2` is correct. Another case of wrong result is `e = sin(x) - x + x**7`, i.e. when the terms `sin(x)` and `-x` disappear, without producing the hidden term `-x**3/6`. 

The wrong code should be in `add.py` at the line 874:
```
expr = expr.func(*[t.as_leading_term(x) for t in expr.args]).removeO()
```
where, in the case `e = 1 - cos(x) + x**6`, `func` is `Add` and the list is `[1, x**6, -1]`. So adding returns `x**6`.

See also #17836

**Comment by smichr** [comment]
Note that the following gives the correct result:
```python
>>> (1 - cos(x)).as_leading_term(x)
x**2/2
```
So if two terms give canceling values, perhaps they should be added together and have the leading term of their sum be used instead.

**Comment by jksuom** [comment]
There is a bug in `Add._eval_as_leading_term()`. It adds together the leading terms of the arguments. If the sum is zero (which is the case with `1 - cos(x)`), then the power series expansion of the sum is used (and that will give the correct result). But if the sum of the leading terms is not zero (as with `1 - cos(x) + x**6`), then the non-zero sum (`x**6`) is returned. This is often wrong as some non-leading terms (like `x**2/2` of `-cos(x)`) may dominate the sum. Therefore, only the leading terms of lowest order should be added together. It the sum is zero, then the series expansion should be computed. (See https://github.com/sympy/sympy/pull/17381/files#r329456262.)

**Comment by sachin-4099** [comment]
This can be closed, everything seems resolved here. @oscarbenjamin
