### ISSUE TITLE
Printing booleans doesn't seem to work as in the example

### ISSUE THREAD

**Issue by MauriceHendrix** [sympy/sympy#17854]
The example for printing in https://github.com/sympy/sympy/blob/master/sympy/printing/str.py#L70-L74
Suggests handling booleans with
`def _print_BooleanTrue(self, expr)`
and
`def _print_BooleanFalse(self, expr)`

This isn't working for me. However what does work is to use
`def _print_bool` instead

**Comment by oscarbenjamin** [comment]
Those are for printing SymPy's symbolic Boolean True and False:
```julia
In [1]: S.true                                                                                                                                                
Out[1]: True

In [2]: type(_)                                                                                                                                               
Out[2]: sympy.logic.boolalg.BooleanTrue
```

**Comment by asmeurer** [comment]
Is this from the documentation or were you just reading the source code?

**Comment by MauriceHendrix** [comment]
I was just given the link to https://github.com/sympy/sympy/blob/master/sympy/printing/str.py#L70-L74 just starting out with sympy really
