### ISSUE TITLE
set Rationals doesn't display correctly in Jupyter notebook Out cells

### ISSUE THREAD

**Issue by Greg1950** [sympy/sympy#17862]
I am experimenting with SymPy 1.5.dev.  Apparently version 1.5 will introduce a  set `Rationals` (type `sympy.sets.fancysets.Rationals`).  This new set displays in Jupyter notebook _Out_ cells as $Rationals()$ rather than $\Bbb Q$, the latter being the standard notation in mathematics for the set of rational numbers.  (Enclosure here by $...$ indicates LaTeX math mode code.)

This is inconsistent with the behavior of other commonly encountered sets such as the `Complexes`, `Reals`, `Integers`, and `Naturals`, which display in Jupyter notebooks with their standard mathematical symbols $\Bbb C$, $\Bbb R$, $\Bbb Z$, and $\Bbb N$.

**Comment by asmeurer** [comment]
We should make sure the other printers are updated for Rationals as well.

**Comment by jgulian** [comment]
This is my first time working with open source. I fixed the change in my recent pull request. While working on this problem, I found that complex number set printing is a bit irregular. str(S.Complexes) returns S.Complexes unlike str(S.Integers) which returns Integers.

**Comment by oscarbenjamin** [comment]
Closing as fixed in #17984
