### ISSUE TITLE
TypeError: 'NoneType' object is not iterable in solveset

### ISSUE THREAD

**Issue by proy87** [sympy/sympy#17882]
`solveset(-8*x**2/(9*(x**2 - 1)**(4/3)) + 4/(3*(x**2 - 1)**(1/3)), x)`  TypeError: 'NoneType' object is not iterable in `eq, cov = unrad(f)`

**Comment by jksuom** [comment]
https://github.com/sympy/sympy/blob/8c59469874775705f78bdb18461cd0b50479af57/sympy/solvers/solveset.py#L740
`unrad(f)` may return `None` if it cannot find the radicals. The return value should be checked before extracting `eq` and `cov`.

**Comment by jksuom** [comment]
`unrad` should probably be fixed to return something useful.

**Comment by naveensaigit** [comment]
I have also noticed that - 

unrad(4*root(x,2)-4) gives (x-1,[]) whereas for some reason, unrad(4*x**(1/2)-4) or unrad(4*x**0.5-4) returns NoneType

**Comment by kushagra1599** [comment]
Hi, I am new to the open source community. I would really like to help in solving this issue if it is not assigned someone. It would a big help to me if someone can help me how to start this project..

**Comment by naveensaigit** [comment]
I already started working on this issue. I hope you don't mind

**Comment by mishra-tanay** [comment]
I would like to work on this issue

**Comment by imnitishng** [comment]
So what I am thinking is adding some kind of warning statement if `unrad(f)` finds no radicals in the equation `f`, if not then return the normal `(eq, cov)`.

**Comment by imnitishng** [comment]
> I have also noticed that -
> 
> unrad(4 * root(x,2)-4) gives (x-1,[]) whereas for some reason, unrad(4 * x**(1/2)-4) or unrad(4*x**0.5-4) returns NoneType

@naveensaigit I think sympy handles float exponents (like 0.5 or 1/2 in your case) and `sqrt()` differently, 0.5 does not evaluate to an expression with √ as a radical. Which is why `unrad()` returns `None` since the input expression has no radicals in it.

**Comment by Saanidhyavats** [comment]
I want to contribute on this issue. Is this issue still open?
