### ISSUE TITLE
Add scipy's LambertW to lambdify

### ISSUE THREAD

**Issue by bjodah** [sympy/sympy#17898]
Example:
```python
>>> sympy.lambdify([x], sympy.LambertW(x,-1), 'mpmath')(0.1)
mpc(real='-4.0280964896101148', imag='-3.9124245486903741')
>>> sympy.lambdify([x], sympy.LambertW(x,-1), 'scipy')(0.1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<lambdifygenerated-9>", line 2, in _lambdifygenerated
NameError: name 'LambertW' is not defined
```

Note that SciPy has [an implementation of the Lambert W function](https://docs.scipy.org/doc/scipy-1.3.2/reference/generated/scipy.special.lambertw.html#scipy.special.lambertw).
The appropriate patch goes into [SciPyPrinter](https://github.com/sympy/sympy/blob/1d769658a90a143ee1effd8a8c2c6a7e50825bca/sympy/printing/pycode.py#L856).

**Comment by spider0061** [comment]
I would like to work on this issue. Can anyone please guide me on this as I am new to open source and this is my first issue.
