### ISSUE TITLE
Inconsistent execution times for Legendre/Jacobi simbols

### ISSUE THREAD

**Issue by St333p** [sympy/sympy#17907]
As far as I know the Legendre symbol is a particular case of the Jacobi symbol. In other words to calculate the Legendre symbol it's enough to check the primality of the second parameter and calculate the Jacobi symbol.
On sympy 1.4 (latest on pip3) I get this result:
```
>>> timeit("sympy.legendre_symbol(1012,1009)",setup, number=100000)
0.8614236980029091
>>> timeit("sympy.jacobi_symbol(1012,1009)",setup, number=100000)
0.30404673799785087
>>> timeit("sympy.isprime(1009)",setup, number=100000)
0.18222121800135938
```
Clearly the time required to calculate a Legendre symbol is far bigger than the primality check plus the Jacobi calculation. I this a bug or a desired behavior?

**Comment by ethankward** [comment]
They have entirely separate implementations.

**Comment by jksuom** [comment]
It seems that the implementation of `legendre_symbol` is inefficient. It even calls `isprime` twice, the second time in `is_quad_residue`.

**Comment by giorgosgiapis** [comment]
Is anybody currently working towards a fix?

**Comment by St333p** [comment]
In my modest opinion in this case a possible fix is implementing `legendre_symbol(a,b)` like this:

```
def legendre_symbol(a, b):
    assert isprime(b) and b != 2, "the second parameter has to be an odd prime"
    return jacobi_symbol(a, b)
```

**Comment by giorgosgiapis** [comment]
I think so too.

**Comment by giorgosgiapis** [comment]
I did some more testing and as it turns out when implemented using Jacobi symbol, the runtime increases. What seems to be the problem here is that the function `as_int()` takes a lot of time. No matter how we choose to implement `legendre_symbol()`, `as_int()` will be called twice. This means that the primality check & pow in `is_quad_residue` is faster than the `jacobi_symbol` method. The reason for the inconsistency mentioned is just on `as_int()` call.

**Comment by giorgosgiapis** [comment]
As a reference, without the above change, I am getting
```py
In [2]: timeit.timeit("sympy.legendre_symbol(1012,1009)",setup="import sympy", number=100000)
Out[2]: 1.04446601868
```
while after modifying the code
```py
In [2]: timeit.timeit("sympy.legendre_symbol(1012,1009)",setup="import sympy", number=100000)
Out[2]: 0.538429021835
```
