### ISSUE TITLE
Runtime error in transolve

### ISSUE THREAD

**Issue by proy87** [sympy/sympy#17906]
`solveset(7**(x^2)-49**x, x)` correctly gives `{0, 2}`, while `solveset(7**(x^2-80)-49**x, x)` gives runtime error. That's because inside transolve `factor` rewrites 7**80 and `powdenest` inside transolve rewrites it back.

**Comment by spider0061** [comment]
Hi, I am new to open source I would like to work on this issue of it is not assigned to anyone. It would be of great help if anyone help in getting started with it.

**Comment by Shekharrajak** [comment]
@spider0061 please goa ahead. I see there is enough information present in issue description to go further. You can try debugging for this example and check where it is breaking. You can use wolframalpha online solver to cross check the final solution.

**Comment by oscargus** [comment]
Seems to be fixed in current master. Adding test that will close it.
