### ISSUE TITLE
Solve inverse Laplace of denominator and numerator  with same degree 

### ISSUE THREAD

**Issue by roy77** [sympy/sympy#17903]
ilaplace(s^2/(1+s^2),s,t) can not be solved. But, when I convert it 

s^2/(1+s^2)=(s^2+1-1)/(1+s^2)=1-1/(1+s^2)

ilaplace(1-1/(1+s^2),s,t) can solve this expression.

**Comment by ethankward** [comment]
With actual SymPy functions:

```
>>> from sympy import *
>>> from sympy.abc import t, s
>>> inverse_laplace_transform(s**2 / (1 + s**2), s, t)
InverseLaplaceTransform(s**2/(s**2 + 1), s, t, _None)
>>> inverse_laplace_transform(1 - 1 / (1 + s**2), s, t)
-sin(t)*Heaviside(t) + DiracDelta(t)
```

**Comment by hanspi42** [comment]
I think this can be solved by letting `_inverse_laplace_transform` check whether the function is a rational fraction, and if yes, apply `.apart()` to it before continuing.

In @ethankward's example, the following works:

`inverse_laplace_transform((s**2 / (1 + s**2)).apart(), s, t)`

**Comment by jksuom** [comment]
> whether .apart() should be applied for all rational fractions,

I think that it would be useful to always try to split the function into a sum of simpler components. Inverse Laplace transform primarily works by looking for the results in a table (via inverse Mellin transform). Simple pieces will more probably be found there.

**Comment by hanspi42** [comment]
Hmm ... wouldn't it then be better to include that in `inverse_mellin_transform` right away? Or is there an application of `inverse_mellin_transform` that would suffer from this?

**Comment by jksuom** [comment]
> wouldn't it then be better to include that in inverse_mellin_transform right away?

That looked like a good idea to me as well but there seemed to be some implementation issues (https://github.com/sympy/sympy/pull/16383). Maybe `apart` should only be attempted with rational fractions.

**Comment by hanspi42** [comment]
> > wouldn't it then be better to include that in inverse_mellin_transform right away?
> 
> That looked like a good idea to me as well but there seemed to be some implementation issues (#16383). Maybe `apart` should only be attempted with rational fractions.

... and then with giving the integration variable, like `inverse_laplace_transform((s**2 / (1 + s**2)).apart(s), s, t)` ... I will try to implement this.

**Comment by hanspi42** [comment]
> 
> 
> > wouldn't it then be better to include that in inverse_mellin_transform right away?
> 
> That looked like a good idea to me as well but there seemed to be some implementation issues (#16383). Maybe `apart` should only be attempted with rational fractions.

Question: would a restricted `expand` like

```
f = f.expand(deep=True, modulus=None, power_base=False,
             power_exp=False, mul=True, log=False, multinomial=True,
             basic=True, complex=False, func=False, trig=False)
```

be a good idea to try for functions that are not rational fractions?

**Comment by jksuom** [comment]
There is already `expand_mul`. This is not much different so it may not help much.
