### ISSUE TITLE
ast_parser is unable to parse `lambda`

### ISSUE THREAD

**Issue by czgdp1807** [sympy/sympy#17913]
Please refer, https://github.com/sympy/sympy/pull/17875#issuecomment-553509249

Probably, the problem is with the following piece of code,

https://github.com/sympy/sympy/blob/c5f875bd9689d4b357b8166bf9e87a89c7af56b1/sympy/parsing/ast_parser.py#L61-L66

However, exploring other parts of code is also recommended for fix.

**Comment by aditisingh2362** [comment]
I would like to work on this issue. Could you guide me and if there are any prerequisites?

**Comment by czgdp1807** [comment]
Feel free to work on this issue. The comment has a sample code which is causing problems. Fixing that bug and adding test for `visit_Lambda` would be enough to close this issue. Try to see if the problem is in the snippet provided in the description.

**Comment by aditisingh2362** [comment]
I just wanted to see the object type of a. Thus I tried printing dump(a).

```
def parse_expr(s, local_dict):
    global_dict = {}
    exec_('from sympy import *', global_dict)
    try:
        a = parse(s.strip(), mode="eval")
    except SyntaxError:
        raise SympifyError("Cannot parse %s." % repr(s))

    a = Transform(local_dict, global_dict).visit(a)
    print(dump(a))
    e = compile(a, "<string>", "eval")

    return eval(e, global_dict, local_dict)
```
For the test:
```
#tests Transform.visit_Lambda
  parse_expr('lambda a:a',{}) == a
```
dump(a) gave me the following result:
```
Expression(body=Call(func=Name(id='Lambda', ctx=Load()), args=[Tuple(elts=[arg(arg='a', annotation=None)], ctx=Load()), Call(func=Name(id='Symbol', ctx=Load()), args=[Str(s='a')], keywords=[])], keywords=[]))
```
If the object is an Expression type, why is that given as ast.arg object?
I've read the documentation for AST and couldn't understand the reason. Could you guide me with the suitable resource or whether I'm headed in the right direction?

**Comment by czgdp1807** [comment]
I will be able to explore the problem after my end semester examinations(ending on 7th December). @asmeurer Can you please provide some suggestions on this issue? Thanks.

**Comment by davefern** [comment]
Thats what im struggling to understand as well. 

Lambda AST Parsing still has issue with recognizing expression type in compile()
        We can dump a, the transformed node expression and we see the expected:
        
        Expression(
            body=Call(
                func=Name(id='Lambda', ctx=Load()), 
                args=[Tuple(elts=[arg(arg='a', annotation=None, type_comment=None)], ctx=Load()), 
                      Call(func=Name(id='Integer', ctx=Load()), args=[Constant(value=2, kind=None)], keywords=[])
                ]#Args
                , keywords=[]
            )#Body Call
        )#Expression
        
        But when we pass it into compile we get a type error claiming this object is a AST arg object.
        
        expected some sort of expr, but got <_ast.arg object at 0x10075da00>

**Comment by davefern** [comment]
try:
        e = compile(a, "<string>", "eval")
    except:
        print("Error")
        return

would this be a good fix for now?

**Comment by risubaba** [comment]
Is this bug still open ?
```
In [30]: parse_expr('lambda a : a+1' ,{})                                                                
Out[30]: a ↦ a + 1
```
Isn't this the correct output?

**Comment by czgdp1807** [comment]
Seems so. At least the errors are removed. Will close this by tomorrow if no further issues reported.

**Comment by czgdp1807** [comment]
Closing this as per the above comment. Thanks.
