### ISSUE TITLE
Convert log(a+bi) into x+iy

### ISSUE THREAD

**Issue by proy87** [sympy/sympy#17948]
How can I rewrite logarithm of a complex number as complex number?

**Comment by jksuom** [comment]
First `x, y = log(a + b*I).as_real_imag()`, and then `x + I*y`.

**Comment by proy87** [comment]
@jksuom , what if I need to rewrite it inside more complex expression, like sin(log(a+b*I))? Is there anyway to use rewrite or similar function?

**Comment by jksuom** [comment]
> Is there anyway to use rewrite or similar function?

It seems that there is no such function in SymPy. Perhaps it would suffice to define a function, say, `log_as_complex` that could be used instead of `log` if necessary.

**Comment by proy87** [comment]
I'm asking because certain expressions can't be simplified without this, like `1-e**(i*pi/3)*e**(i*pi/3)`

**Comment by oscarbenjamin** [comment]
Do you mean for e and i to be the mathematical constants? If so then you should use capitals `E` and `I`:
```julia
In [3]: 1-E**(I*pi/3)*E**(I*pi/3)                                                                                                 
Out[3]: 
     2⋅ⅈ⋅π
     ─────
       3  
1 - ℯ     

In [4]: simplify(_)                                                                                                               
Out[4]: 
        2/3
1 - (-1) 
```
Otherwise it isn't clear to me what you want to do with `sin(log(a+b*I))`. What do you want to end up with and why?

**Comment by proy87** [comment]
`1-E**(I*pi/3)*E**(I*pi/3)` should be simplified to `3/2 - (i sqrt(3))/2`

**Comment by oscarbenjamin** [comment]
You can do that with `as_real_imag` as well:
```julia
In [12]: expr = 1-E**(I*pi/3)*E**(I*pi/3)                                                                                         

In [13]: expr                                                                                                                     
Out[13]: 
     2⋅ⅈ⋅π
     ─────
       3  
1 - ℯ     

In [14]: x, y = expr.as_real_imag()                                                                                               

In [15]: x + I*y                                                                                                                  
Out[15]: 
3   √3⋅ⅈ
─ - ────
2    2
```
The one line way to do this is
```julia
In [22]: expr.expand(complex=True)                                                                                                
Out[22]: 
3   √3⋅ⅈ
─ - ────
2    2  
```

**Comment by proy87** [comment]
Great!
