### ISSUE TITLE
How do you get the the "B" in Object("B")?

### ISSUE THREAD

**Issue by enjoysmath** [sympy/sympy#17963]
Using the abstract object from the categories module.

Object("B").free_symbols returns "Object("B")" .  How do I get the "B".

Second, how complex of an expression can these base symbols "B" have? 

Can I do "B_1", etc?  If not, then can I attach data to the objects in the regular python attribute way?

Thanks.

**Comment by asmeurer** [comment]
You can use the `name` attribute, like `Object("B").name`. It works the same as with Symbol (Object subclasses from Symbol).

**Comment by asmeurer** [comment]
I didn't see the second part. The name can be any string. You can also put assumptions on it, since it uses the same API as Symbol, although I'm not sure if any assumptions are meaningful. 

Does that answer your questions?

**Comment by enjoysmath** [comment]
Yep.  Thanks!
