### ISSUE TITLE
Periodicity of trigonometric function

### ISSUE THREAD

**Issue by JSS95** [sympy/sympy#17976]
(This issue is from https://stackoverflow.com/questions/58419941/periodicity-of-sympy-trigonometric-function/58424464#58424464, by me.)

Sympy's trigonometric functions takes periodic argument into account.

```
from sympy import pi, sin, Symbol

n = Symbol('n', integer=True)

>>> sin(2*pi + 4)
sin(4)

>>> sin(n*pi)
0
```
However, it seems that it does not support this feature...
```
n = Symbol('n', integer=True)

>>> sin(2*n*pi + 4)
sin(2*n*pi + 4)  # Expected sin(4)
```
`.simplify()` or `.doit()` was not working.

I know that `trigsimp` can do the job, but isn't `.simplify()` supposed to do it?

**Comment by oscarbenjamin** [comment]
Perhaps the automatic evaluation can be improved to handle this.

It seems that the `_peeloff_pi` function doesn't work in this case
https://github.com/sympy/sympy/blob/029936987c7b35fcc6b347b580d4c154792344e7/sympy/functions/elementary/trigonometric.py#L94
because `.as_two_terms()` groups the `n` with the `pi`:
```julia
In [1]: (2*n*pi).as_two_terms()                                                                                                   
Out[1]: (2, π⋅n)
```

**Comment by smichr** [comment]
maybe `_peelof_pi` could be modified as
```python
        elif a.is_Mul:
            K, p = a.as_two_terms()
            if p is S.Pi and K.is_Rational:
                break
            K = a.coeff(S.Pi)
            if K and K.is_rational:
                break
```

**Comment by oscarbenjamin** [comment]
We might as well skip out `as_two_terms` and go straight for `coeff` in that case:
```julia
In [1]: (2*pi).coeff(pi)                                                                                                          
Out[1]: 2

In [2]: (2*n*pi).coeff(pi)                                                                                                        
Out[2]: 2⋅n
```
However the case that coeff gives zero needs to be handled specially:
```
In [3]: (2*n).coeff(pi)                                                                                                           
Out[3]: 0
```
Ultimately what we are doing here is computing the remainder modulo `pi/2` so maybe it makes sense just to do `a % (pi / 2)`...

**Comment by sachin-4099** [comment]
I totally agree with the fact that we can skip out as_two_terms and go straight for coeff, as coeff is covering whatever as_two_terms is able to do and what it is not is even covered by coeff.

But it is not able to verify that whether 'a' had a pi term or not, ultimately when we get the result as 0.
So this can be handled separately, but when such a case arises, what is the actual arg of sin such as:
sin(2n +4), then the output after simplification should remain the same isn't it i.e sin(2n + 4).

So _peeloff_pi will return (2n + 4, 0), so I think there is no need to handle 0 specially:

FInally _peeloff_pi should be:
    
for a in Add.make_args(arg):

    if a is S.Pi:
        K = S.One
        break
    elif a.is_Mul:
        K = a.coeff(S.Pi)
        if K and K.is_rational:
            break
else:
    return arg, S.Zero

**Comment by sachin-4099** [comment]
@oscarbenjamin, after making the mentioned changes the peeloff function works well, but runtime error occurs when calculating sin(2*n*pi + 4), will have to make changes in the code of trigonometric functions in **core module**

**Comment by sachin-4099** [comment]
After changing the _peeloff_pi function it gives the this result:

In [1]: from sympy.functions.elementary.trigonometric import _peeloff_pi as peel
In [2]: from sympy import pi
In [3]: n = Symbol('n', integer=True)

`In [4]: peel(2*n*pi + 4)`
`Out[4]: (pi*(2*n mod 1/2) + 4, 2*pi*n - pi*(2*n mod 1/2))`   ## should be `(4, 2*pi*n)`

`pi*(2*n mod 1/2)` should become 0 as n is an integer. 
How to implement this @oscarbenjamin @smichr?? 
`

**Comment by sachin-4099** [comment]
https://github.com/sympy/sympy/blob/a8ea8dee2aa9a6d5574c116c63148085679a42ec/sympy/functions/elementary/trigonometric.py#L123-L125

Do we have the liberty to change **S.half to (1/2)** ?? 
Because that resolves the issue. @oscarbenjamin @smichr

**Comment by jmig5776** [comment]
@sachin-4099 First of all you should start a PR if you have proper understanding on how to deal with this issue. Rest of the error will be tackled after we will review your PR.

**Comment by jmig5776** [comment]
You should consider the idea of @smichr and add test cases to verify the change

**Comment by sachin-4099** [comment]
I am getting errors after making changes @oscarbenjamin @smichr @jmig5776 
Actually if we want to solve this issue, we should take **mod with 2*pi** as period of sin is 2*pi.
But I am not able to understand why are we using _peeloff_pi for this, which takes argument mod (pi/2)

**Comment by sachin-4099** [comment]
Please review the PR, @smichr @oscarbenjamin @jmig5776 
Suggest the changes required to merge the PR.
The required problem has been handled, but other problems are arising.
