### ISSUE TITLE
[ANN] The development of GAlgebra now officially moves to pygae/galgebra

### ISSUE THREAD

**Issue by utensil** [sympy/sympy#17980]
The development of GAlgebra now officially moves to [pygae/galgebra](https://github.com/pygae/galgebra). Alan Bromborsky (@brombo, account deleted by himself), the author of GAlgebra, is back on active developments on GAlgebra using a new Github account @abrombo and the maintenance efforts will be shared by members of the GAlgebra development team in [Pythonic Geometric Algebra Enthusiasts](https://github.com/pygae), namely @abrombo , @hugohadfield, @eric-wieser and me.
Also, GAlgebra has released 0.4.4 on [PyPI](https://pypi.org/project/galgebra/) and [Conda Forge](https://anaconda.org/conda-forge/galgebra) along with its new online documentation https://galgebra.readthedocs.io/ , see [Changelog](https://galgebra.readthedocs.io/en/latest/changelog.html).

A follow-up PR will be submited to change the reference to https://github.com/brombo/galgebra in SymPy (https://github.com/sympy/sympy/blob/master/sympy/galgebra.py) accordingly.

**Comment by asmeurer** [comment]
Please do announcements on the mailing list, not the issue tracker.

**Comment by utensil** [comment]
I thought it's kind of needed for the PR.

**Comment by utensil** [comment]
The announcement is posted at https://groups.google.com/forum/#!topic/sympy/2k7105j3Fi0 instead.
