### ISSUE TITLE
series does not give the same expansion depending on whether simple expression is simplified or not

### ISSUE THREAD

**Issue by dsenech** [sympy/sympy#18008]
Consider the following simple rational function of w:
```
w = symbols('w')
Y = w*(1 + w*(1 - w))/((1 + w*(1 - w)) - (1 - w)*(1 - w))
```
A series about w=infinity gives:
print_python(series(Y,w,oo,n=4))
```
e = -45/(16*w**3) - 3/(16*w**2) - 1/(8*w) + Rational(1, 4) + w/2 + O(w**(-4), (w, oo))
```
if I simplify the expression before computing the series, the coefficient of 1/w**3 is not the same!
print_python(series(Y.simplify(),w,oo,n=4))
```
e = -9/(32*w**3) - 3/(16*w**2) - 1/(8*w) + Rational(1, 4) + w/2 + O(w**(-4), (w, oo))
```
This is a serious problem...

**Comment by smichr** [comment]
A workaround is to request a higher order series. The 4th order term is correct in the 5th order expression:
```python
>>> for i in range(4,7):print(i, Y.series(w,oo,i))
(4, -45/(16*w**3) - 3/(16*w**2) - 1/(8*w) + 1/4 + w/2 + O(w**(-4), (w, oo)))
(5, -135/(32*w**4) - 9/(32*w**3) - 3/(16*w**2) - 1/(8*w) + 1/4 + w/2 + O(w**(-5), (w, oo)))
(6, -81/(32*w**5) - 135/(32*w**4) - 9/(32*w**3) - 3/(16*w**2) - 1/(8*w) + 1/4 + w/2 + O(w**(-6), (w, oo)))
>>> Y.series(w,oo,5).series(w,oo,4)
-9/(32*w**3) - 3/(16*w**2) - 1/(8*w) + 1/4 + w/2 + O(w**(-4), (w, oo))
```

**Comment by jksuom** [comment]
Probably related to https://github.com/sympy/sympy/issues/14068.

**Comment by allenmac347** [comment]
Hi, first time open source contributor here. Mind if i try to fix this issue?
