### ISSUE TITLE
Is it possible to calculate limit of real-valued limit?

### ISSUE THREAD

**Issue by proy87** [sympy/sympy#18010]
`limit(-x + (x**3 + x**2)**(1/3), x, -oo)` returns unevaluated limit.
Is it possible to make it return `-oo`? Assumption of `real=True` doesn't help.

**Comment by ethankward** [comment]
What do you mean by "unevaluated"? In master and 1.4 it returns `oo*sign(1 + (-1)**(1/3))`.

**Comment by proy87** [comment]
How t understand `oo*sign(1 + (-1)**(1/3))`?

**Comment by asmeurer** [comment]
I think the `sign` is misleading, or possibly even wrong. 

The expression in question is not real valued for negative x. You can see for instance `(-x + (x**3 + x**2)**(S(1)/3)).subs(x, -2).evalf()` gives a complex number. You can see that `arg((-x + (x**3 + x**2)**(S(1)/3)).subs(x, -1000000)).evalf()` approaches `arg(1 + (-1)**(1/3))` (which is pi/6) and `abs((-x + (x**3 + x**2)**(S(1)/3)).subs(x, -1000000)).evalf()` approaches infinity. That means that in the limit, the value approaches the infinite value with argument pi/6.

**Comment by proy87** [comment]
How to force real-valued root?

**Comment by asmeurer** [comment]
Normally the `oo*sign(...)` is for real expressions, meaning the sign of the infinity depends on the sign of some symbolic value. For instance, 

```py
>>> limit(a*x, x, oo)
oo*sign(a)
```

But I don't know if the logic for it is correct for complex signs.

**Comment by asmeurer** [comment]
> How to force real-valued root?

Use `real_root`. However, `limit(-x + real_root(x**3 + x**2, 3), x, -oo)` gives a NotImplementedError.

**Comment by proy87** [comment]
When variable is positive, then I got `1/3`.
