### ISSUE TITLE
Inconsistency in simplifying trigonometrics

### ISSUE THREAD

**Issue by JSS95** [sympy/sympy#18016]
```
>>> from sympy import *
>>> from sympy.abc import theta

>>> expr1 = sin(theta) + cos(theta)
>>> expr1.simplify()
sin(theta)+cos(theta)

>>> expr2 = 2*sin(theta) + 2*cos(theta)
>>> expr2.simplify()
2*sqrt(2)*sin(theta + pi/4)
```

Shouldn't `expr1.simplify()` return `sqrt(2)*sin(theta + pi/4)`?

**Comment by mbasil09** [comment]
I think the problem arises due to the default value of "ratio=1.7" in simplify.
You get the correct answer by entering your own value of ratio, (this case ratio=2.0)
If you explicitly call expr1.trigsimp() you get the desired expression.

**Comment by JSS95** [comment]
> I think the problem arises due to the default value of "ratio=1.7" in simplify.
> You get the correct answer by entering your own value of ratio, (this case ratio=2.0)
> If you explicitly call expr1.trigsimp() you get the desired expression.
> quoting from simplfy.py - " In some cases, applying :func:simplify may actually result in some more
> complicated expression. The default ratio=1.7 prevents more extreme
> cases: if (result length)/(input length) > ratio, then input is returned
> unmodified.  "

Thanks! Didn't know such feature before.
