### ISSUE TITLE
sqrtdenest drops I

### ISSUE THREAD

**Issue by smichr** [sympy/sympy#18041]
As described [here](https://stackoverflow.com/questions/59296496/converting-all-redundant-floats-in-a-string-to-integers/59305338#59305338):

```python
>>> -sqrt(-2 + 2*sqrt(3)*I)
-sqrt(-2 + 2*sqrt(3)*I)
>>> sqrtdenest(_), nsimplify(_)
(-1 + sqrt(3), -1 - sqrt(3)*I)
```

The `nsimplify` result is the right one.

**Comment by gschintgen** [comment]
On 1.4 I get a "tuple index out of range error" which is suspiciously similar to the one of #12420. So it may well be that the patch in PR #17318 was not totally correct...
I'll look into it as soon as I find the time (which should be soon I hope).

**Comment by asmeurer** [comment]
I don't know if the fix in #17318 was right or not, but it looks like the `if` block is False (when it was evaluated as True it lead to IndexError). So assuming the fix is right, the code after that block is incorrect, which wasn't modified by you. Likely this was a latent bug that already existed.

**Comment by asmeurer** [comment]
Is the sqrtdenest code supposed to treat `I` as a square root? It looks like functions like `sqrt_depth` do not.

**Comment by asmeurer** [comment]
This makes it give the right answer. But I don't know if it's correct

```diff
diff --git a/sympy/simplify/sqrtdenest.py b/sympy/simplify/sqrtdenest.py
index e437987d83..1db0f40483 100644
--- a/sympy/simplify/sqrtdenest.py
+++ b/sympy/simplify/sqrtdenest.py
@@ -33,6 +33,8 @@ def sqrt_depth(p):
     >>> sqrt_depth(1 + sqrt(2)*sqrt(1 + sqrt(3)))
     2
     """
+    if p is S.ImaginaryUnit:
+        return 1

     if p.is_Atom:
         return 0
```

**Comment by asmeurer** [comment]
This is the only test that fails

```
Traceback (most recent call last):
  File "/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/simplify/tests/test_sqrtdenest.py", line 187, in test_issue_12420
    assert _sqrt_match(4 + I) == []
AssertionError

```

However, the actual sqrtdenest tests inside of that test still give the correct answers. It's only the internal function that gives a different result.

**Comment by asmeurer** [comment]
I've pushed the fix up to https://github.com/sympy/sympy/pull/18042. I hope someone who knows more about the algorithm can confirm whether this is correct. I'm guessing it is, but I don't know if the algorithm makes any assumptions about the square roots being real.
