### ISSUE TITLE
Sympy Continuum mechanics results look wrong in the given example

### ISSUE THREAD

**Issue by vishalgp** [sympy/sympy#18045]
Sympy continuum mechanics Beam Class:
the results for bending moment diagram and calculation of bending moment reaction look wrong. for the example shown in Example 1.
moment should be 158 and bending moment diagram at the point of application of bending moment should go up instead of going down.
https://docs.sympy.org/latest/modules/physics/continuum_mechanics/beam_problems.html#example-1

**Comment by moorepants** [comment]
Can you provide a calculation that shows the correct answer of 158?

The up/down issue may just be that you are choosing a different sign convention.

**Comment by moorepants** [comment]
Yes, I see that 12*9+8*5*2.5-50=158.

**Comment by moorepants** [comment]
But, that doesn't account for the application location of the 50 kn-m moment. If it was applied at the wall contact then you just add it, but you may not if applied at the location it is at.

**Comment by moorepants** [comment]
So I think I'm convinced this example is wrong. It seems that we need to investigate what is happening in `solve_for_reaction_loads()`. For some reason an extra 100 kn-m is added.

**Comment by dnaneet** [comment]
@moorepants 

[Here is a handwritten solution](https://pages.mtu.edu/~dnaneet/2150/notes/problems/sfd_bmd_cantilever_UDL_Moment_PtLoad) to [example 1](https://docs.sympy.org/latest/modules/physics/continuum_mechanics/beam_problems.html), through my webpage at my university.  

I've also solved this problem with what seems to be the UPDATED functionality in python.  You can [access the colab notebook here](https://colab.research.google.com/drive/1gVxUt53dSYRvFFlV7jSLK1YtGsmLev34).  

The major difference between this sympy/beam package's functionality is that a positive applied moment (by convention, counterclkws = positive) NEEDS to be assigned a negative sign in the code, for accurate bending moment diagram.  

Thanks.

**Comment by moorepants** [comment]
Thanks for the hand solution. We need someone to figure out what is incorrect in the code and correct it now.

**Comment by Psycho-Pirate** [comment]
I would like to work on this issue.

After going through the code, i think the default sign convention is wrong(upward and counterclockwise positive). The problem can be fixed by setting default sign convention as 
upward forces and clockwise moment as positive.
This will solve many errors in other examples as well.
In example 2, the moment given in question is in clockwise direction, however in the figure it is shown in counterclockwise direction and is inputted as positive, and the results are correct according to the question. Here the depiction of bending moment is wrong and this will also be solved by changing the defaults. @moorepants @dnaneet

**Comment by jashan498** [comment]
>After going through the code, i think the default sign convention is wrong(upward and counterclockwise positive)

Yes, the sign conventions used in the two examples are wrong. Everything else seems to work just fine.
User can set any direction to positive as long as upward forces & clockwise moments have similar signs (please correct if Im worng). I recently saw a similar confusion about sign conventions [here](https://groups.google.com/d/msg/sympy/MhRJ1Ahl8i0/roNHvKt6AQAJ) in the mailing list.
 Maybe we should mention about the correct sign conventions somewhere in the docs?

**Comment by Psycho-Pirate** [comment]
> Maybe we should mention about the correct sign conventions somewhere in the docs?

I will add it in the beam and beam problems docstrings.

**Comment by moorepants** [comment]
>  Maybe we should mention about the correct sign conventions somewhere in the docs?

Yes, a lucid explanation about how a user should deal with sign conventions would be a good thing to do first.

**Comment by nopria** [comment]
Issues are still present, I investigated and I believe I found what the problem exactly is and proposed a solution here:
https://github.com/sympy/sympy/issues/20204

Please jump in the discussion.

**Comment by moorepants** [comment]
This is @dnaneet's handwritten solution from above:

![image](https://github.com/user-attachments/assets/f794a062-6a06-4f56-a05b-339574009562)

The sympy 1.13 docs show that the sympy solution matches their solution:

![image](https://github.com/user-attachments/assets/52b8133c-4dcb-4a71-b6d0-0a9e1d019d2d)

The handwritten solution has Ay = 52 kn (positive) and SymPy gives -52 kn, but this could be sign convention.

This may have fixed it: https://github.com/sympy/sympy/pull/20431 I'm closing this issue, reopen if it is not fixed.
