### ISSUE TITLE
Issue with finding domain of 1/(exp(x)-2) using continous_domain

### ISSUE THREAD

**Issue by AoWangDrexel** [sympy/sympy#18051]
Not sure why I keep on receiving the error: 

> TypeError: cannot determine truth value of Relational

I'd expect (-oo, ln(2))U(ln(2),oo)

```
from sympy.calculus.util import continuous_domain
from sympy import Symbol, S, tan, log, pi, sqrt

f = 1/(exp(x)-2)
display(f)
continuous_domain(f, x, S.Reals)

```

**Comment by jksuom** [comment]
This error does not appear in the current master and probably not in v.1.5.

**Comment by AoWangDrexel** [comment]
Oh yes! Thank you
