### ISSUE TITLE
cubic spline interpolation issue

### ISSUE THREAD

**Issue by dcsaba89** [sympy/sympy#18069]
Incorrect cubic spline interpolation in sympy v1.4

Based on my investigation sympy v1.4 produced incorrect cubic spline as a result of the below code. However this issue already has been resolved in sympy v1.5. I encourage the developers to add this input X, Y as a test case.

```py
import sympy as sym
import numpy as np

X = [1, 2, 3, 4, 5]
Y = [0, 1, 0, 1, 0]

x = sym.symbols('x')
N = len(X)
xx = np.linspace(1, 5, 100)
plt.plot(X, Y, "o")
splines = []
for k in range(1, N):
    S = sym.interpolating_spline(k, x, X, Y)
    splines.append(S)
    yy = [S.subs(x, t) for t in xx]
    plt.plot(xx, yy, "-")
plt.grid()
```

Results in sympy v1.4:
```
case k=1:
Piecewise((x - 1, (x >= 1) & (x <= 2)), (3 - x, (x >= 2) & (x <= 3)), (x - 3, (x >= 3) & (x <= 4)), (5 - x, (x >= 4) & (x <= 5)))
case k=2:
Piecewise((-7*x**2/5 + 26*x/5 - 19/5, (x >= 1) & (x <= 5/2)), (9*x**2/5 - 54*x/5 + 81/5, (x >= 5/2) & (x <= 7/2)), (-7*x**2/5 + 58*x/5 - 23, (x >= 7/2) & (x <= 5)))
case k=3:
Piecewise((35*x**3/9 - 73*x**2/3 + 421*x/9 - 79/3, (x >= 1) & (x <= 3)), (-31*x**3/9 + 113*x**2/3 - 1169*x/9 + 415/3, (x >= 3) & (x <= 5)))
case k=4:
Piecewise((-x**4/3 + 4*x**3 - 50*x**2/3 + 28*x - 15, (x >= 1) & (x <= 5)))


>>> splines[2].subs(x, 2.9999)
>>> −0.000577671114996292
>>> splines[2].subs(x, 2.999999999999999)
>>> −2.8421709430404⋅10^−14
>>> splines[2].subs(x, 3.0001)
>>> −5.33302215555904
>>> splines[2].subs(x, 3.000000000000001)
>>> −5.33333333333337
```

Results in sympy v1.5:
```
case k=1:
Piecewise((x - 1, (x >= 1) & (x <= 2)), (3 - x, (x >= 2) & (x <= 3)), (x - 3, (x >= 3) & (x <= 4)), (5 - x, (x >= 4) & (x <= 5)))
case k=2:
Piecewise((-7*x**2/5 + 26*x/5 - 19/5, (x >= 1) & (x <= 5/2)), (9*x**2/5 - 54*x/5 + 81/5, (x >= 5/2) & (x <= 7/2)), (-7*x**2/5 + 58*x/5 - 23, (x >= 7/2) & (x <= 5)))
case k=3:
Piecewise((x**3 - 7*x**2 + 15*x - 9, (x >= 1) & (x <= 3)), (-x**3 + 11*x**2 - 39*x + 45, (x >= 3) & (x <= 5)))
case k=4:
Piecewise((-x**4/3 + 4*x**3 - 50*x**2/3 + 28*x - 15, (x >= 1) & (x <= 5)))

>>> splines[2].subs(x, 2.9999)
>>> 1.99990068949774⋅10^−8
>>> splines[2].subs(x, 2.999999999999999)
>>> 0
>>> splines[2].subs(x, 3.0001)
>>> 1.99990068949774⋅10^−8
>>> splines[2].subs(x, 3.000000000000001)
>>> 0
```

Issue summary:
`
Cubic spline was incorrectly constructed by sympy v1.4, the resulting cubic piecewise polynomial is not continuous in knot $x=3$ where $(lim_{x\to 3-} S(x) \eq 0 \neq 5 + 1/3 = lim_{x\to 3+} S(x)$.
`

However by sympy v1.5, the same cubic spline is constructed correctly and the convergence is more accurate.

Please add this case to the unittests.

**Comment by jksuom** [comment]
The fix was probably https://github.com/sympy/sympy/pull/16359.

**Comment by ehiggins98** [comment]
I would like to work on this issue.

**Comment by jksuom** [comment]
I think that the issue was fixed already.

**Comment by ehiggins98** [comment]
It looked to me like [#16359](https://github.com/sympy/sympy/pull/16359/files) fixed the original bug, but this issue requests that a case be added to the unit tests, which #16359 may not have done. However, it does look like the example in the doc was updated in that PR, so is that sufficient?

**Comment by jksuom** [comment]
>  However, it does look like the example in the doc was updated in that PR, so is that sufficient?

I think that it should suffice. It is not likely that the same error could accidentally reappear.

**Comment by ehiggins98** [comment]
Sounds good. This should probably be marked as closed then?

**Comment by jksuom** [comment]
I think so. There is no dedicated unit test for the bug but the docstring example did already bring it forth. Closing.
