### ISSUE TITLE
fastcache vs functools.lru_cache performance

### ISSUE THREAD

**Issue by pbrady** [sympy/sympy#18070]
As of Python 3.5, `functools.lru_cache` was rewritten in C.  It's able to use an internal dictionary API and is therefore more performant than `fastcache`.  I'm not sure if this will actually make a difference but its probably worth investigating

**Comment by asmeurer** [comment]
We have just dropped Python 2 support and 3.5 is now the lowest version we support. If fastcache is no longer needed then we should definitely drop it, as there's no reason to have a dependency that we don't need, even an optional one. 

We should benchmark it in all the Python versions we support, as the dictionary implementation changed in 3.6 which could potentially affect things.
