### ISSUE TITLE
`ask` function needs `except KeyError: ` condition

### ISSUE THREAD

**Issue by JSS95** [sympy/sympy#18106]
I am deeply interested in new assumption system, and trying with custom queries. But this led to an error when I meddled with assumptions.

I'll exemplify with `Q.mersenne`, which is provided as an example in sympy's documentation page.

```
>>> from sympy.assumptions import register_handler, ask, Q
>>> from sympy.assumptions.handlers import AskHandler
>>> class MersenneHandler(AskHandler):
...     # Mersenne numbers are in the form 2**n - 1, n integer
...     @staticmethod
...     def Integer(expr, assumptions):
...         from sympy import log
...         return ask(Q.integer(log(expr + 1, 2)))
>>> register_handler('mersenne', MersenneHandler)
>>> ask(Q.mersenne(7))
```

So far, so good.
But when I extended this to Symbol and taught it a silly fact: "If n is mersenne, then n is mersenne.", it raised an error.

```
>>> from sympy.assumptions import register_handler, ask, Q
>>> from sympy.assumptions.handlers import AskHandler
>>> from sympy.logic.boolalg import conjuncts
>>> class MersenneHandler(AskHandler):
...     # Mersenne numbers are in the form 2**n - 1, n integer
...     @staticmethod
...     def Integer(expr, assumptions):
...         from sympy import log
...         if ask(Q.integer(log(expr + 1, 2))):
...             return True
...     @staticmethod
...     def Symbol(expr, assumptions):
...         if expr in conjuncts(assumptions):
...             return True
>>> register_handler('mersenne', MersenneHandler)

>>> from sympy import Symbol
>>> n = Symbol('n', integer=True)
>>> ask(Q.mersenne(n), Q.mersenne(n))
```
This raised:
```
 Traceback (most recent call last)
   1300         # See if there's a straight-forward conclusion we can make for the inference
   1301         if local_facts_.is_Atom:
-> 1302             if key in known_facts_dict[local_facts_]:
   1303                 return True
   1304             if Not(key) in known_facts_dict[local_facts_]:

KeyError: Q.mersenne
```

(Of course, my original code wasn't about simply adding this kind of tautologic fact.)
I tested by adding `except KeyError: pass` condition and it resolved the error.

Maybe this small condition will be harmless to be added in the code?

**Comment by ShubhamKJha** [comment]
Hi @JSS95, I'm glad that you are interested in New Assumptions.

The whole system is still not mature. This error comes from the fact that the `straight-forward conclusion` portion of code checks on pre-compiled data stored in `ask_generated.py` file. This ask_generated file has to be manually generated from the already defined assumptions and clauses. Adding new facts or handlers doesn't update this pre-compiled list, but I agree this behavior should not happen.

Much of the code in `assumptions` was changed for speeding up the querying mechanism. We still require some cleaning up here and there, and this portion comes under that. AFAIK, this portion needs to be redone (or removed).

I will try to look up into that when I get time.
