### ISSUE TITLE
sympy.Rational presents rational numbers in a weird way

### ISSUE THREAD

**Issue by Alexander986** [sympy/sympy#18108]
In []: sympy.Rational(3/7)
Out []: 7720456504063707/18014398509481984

**Comment by ShubhamKJha** [comment]
It happens because of Floating point error (Float values are not the most accurate in Python and other languages). 
I believe Rational should be called as `sympy.Rational(3, 7)`.
Calling it with a `float` value approximates the resulting Rational number:
```py
>>> from sympy import *
>>> Rational(3/7)
7720456504063707/18014398509481984
>>> Rational(3, 7)
3/7
>>> 3/7
0.42857142857142855
>>> 7720456504063707/18014398509481984
0.42857142857142855
>>> 
```
It looks like a good approximation.

**Comment by sylee957** [comment]
This is a known gotcha that cannot be resolved without modifying the python internals.

You can also use parsers.
```python
from sympy.parsing.sympy_parser import parse_expr
parse_expr('3/7')
```

**Comment by Alexander986** [comment]
Thank you!
