### ISSUE TITLE
vector power is not implemented?

### ISSUE THREAD

**Issue by yufengwhy** [sympy/sympy#18105]
p1, p2, p3, p4 = symbols('p1, p2, p3, p4')  
p = Matrix([p1, p2, p3, p4])  
p**2

> ---------------------------------------------------------------------------
NonSquareMatrixError                      Traceback (most recent call last)
<ipython-input-11-ab546129d7fc> in <module>
----> 1 p**2

~/anaconda3/lib/python3.7/site-packages/sympy/core/decorators.py in binary_op_wrapper(self, other)
    127                     if f is not None:
    128                         return f(self)
--> 129             return func(self, other)
    130         return binary_op_wrapper
    131     return priority_decorator

~/anaconda3/lib/python3.7/site-packages/sympy/matrices/common.py in __pow__(self, exp)
   2223     def __pow__(self, exp):
   2224         if self.rows != self.cols:
-> 2225             raise NonSquareMatrixError()
   2226         a = self
   2227         jordan_pow = getattr(a, '_matrix_pow_by_jordan_blocks', None)

NonSquareMatrixError:

**Comment by ethankward** [comment]
What is the result you expected to get?

**Comment by yufengwhy** [comment]
element wise power as  p**2 == p1**2, p2**2, p3**2, p4**2  
p1, p2, p3, p4 = symbols('p1, p2, p3, p4')
p = Matrix([p1, p2, p3, p4])
p**2

**Comment by ethankward** [comment]
Squaring a matrix is not the same thing as elementwise power.

Try this:

```
>>> from sympy import *
>>> from sympy.abc import x, y, z
>>> v = Matrix([x, y, z])
>>> v.applyfunc(lambda x: x**2)
Matrix([
[x**2],
[y**2],
[z**2]])
```

**Comment by yufengwhy** [comment]
thx a lot
