### ISSUE TITLE
ImageSet of n**2-1 returns EmptySet as intersection with Integers (diophantine bug)

### ISSUE THREAD

**Issue by gschintgen** [sympy/sympy#18114]
```
In [1]: ImageSet(Lambda(n, n**2 - 1), S.Integers).intersect(S.Integers)
Out[1]: ∅
```

**Comment by gschintgen** [comment]
This one's a bug in `diophantine`:
```
In [1]: diophantine(x**2 - 1 - y)
Out[1]: set()
```
The equation has rather trivial integer solutions.

**Comment by gschintgen** [comment]
```
In [14]: from sympy.solvers.diophantine import diop_quadratic                                                                  
In [15]: diop_quadratic(m**2 - n - 1, k)                                                                                       
Out[15]:
⎧⎛    2    ⎞⎫
⎨⎝k, k  - 1⎠⎬
⎩           ⎭

In [16]: diophantine(m**2 - n - 1, k)
Out[16]: set()
```
The solutions are discarded somewhere inside `diophantine`.

**Comment by gschintgen** [comment]
Actually, when `diop_quadratic` is invoked via `diophantine` the signs of the coefficients are negated. So the issue can be reproduced as follows:
```
In [1]: from sympy.solvers.diophantine import diop_quadratic

In [2]: diop_quadratic(m**2 - n - 1, k)
Out[2]:
⎧⎛    2    ⎞⎫
⎨⎝k, k  - 1⎠⎬
⎩           ⎭

In [3]: diop_quadratic(-m**2 + n + 1, k)
Out[3]: set()
```

**Comment by Smit-create** [comment]
```
>>>ImageSet(Lambda(n, n**2 - 1), S.Integers).intersect(S.Integers)
ImageSet(Lambda(n, n**2), Integers)
```
I am getting the above output upon running that

**Comment by gschintgen** [comment]
Strange. I've just checked again on my setup:
- current master returns `EmptySet`
- current master with a quick typo fix (as in the PR): `ImageSet(Lambda(n, n**2 - 1), Integers)`

**Comment by Smit-create** [comment]
> Strange. I've just checked again on my setup:
> 
> * current master returns `EmptySet`
> * current master with a quick typo fix (as in the PR): `ImageSet(Lambda(n, n**2 - 1), Integers)`

Okay, then it may also be fixed with the PR
