### ISSUE TITLE
diophantine gives wrong result depending on alphabetic order of variables (_diop_quadratic)

### ISSUE THREAD

**Issue by gschintgen** [sympy/sympy#18122]
```
In [1]: diophantine(x**2 - y)
Out[1]:
⎧⎛    2⎞⎫
⎨⎝t, t ⎠⎬
⎩       ⎭

In [2]: diophantine(y**2 - x)
Out[2]: {(0, 0)}
```
Both cases end up (correctly AFAICT) in `_diop_quadratic` with a discriminant of 0. Source link:
https://github.com/sympy/sympy/blob/4ff82aaf85967bcf040871912fe872e16a9895cd/sympy/solvers/diophantine.py#L946
Then the algorithm ensures that it's the first variable that's having a nonzero coefficient for the quadratic term. It does so by calling itself with the variables switched if necessary:
https://github.com/sympy/sympy/blob/4ff82aaf85967bcf040871912fe872e16a9895cd/sympy/solvers/diophantine.py#L975-L976
It's in this "inverted" solver call that the incomplete `(0,0)` solution arises.

I'll leave it up to someone more familiar with this part of the codebase to find the actual error.

**Comment by oscarbenjamin** [comment]
> I'll leave it up to someone more familiar with this part of the codebase to find the actual error.

At this stage you might be the most familiar with this part of the codebase :)

**Comment by jksuom** [comment]
There is a typo in this condition: https://github.com/sympy/sympy/blob/270cf6880b441599bda9706e3c8caf696ef20302/sympy/solvers/diophantine.py#L1006-L1008
There should be only one `*` between `sqc` and `g`,

Interchanging the roles of `x` and `y` on line 976 makes the coefficient `A` of `x**2` negative, so the gcd of `A` and `C` will also be taken negative on line 981: https://github.com/sympy/sympy/blob/270cf6880b441599bda9706e3c8caf696ef20302/sympy/solvers/diophantine.py#L981
 It follows that the power `sqc**g` will be `zoo` as the square root `sqc` of `C` is 0.

**Comment by gschintgen** [comment]
> There is a typo in this condition: [...]
> There should be only one `*` between `sqc` and `g`,

Ha! I got so close :-)
Thanks @jksuom for spotting and @Smit-create for the PR!
