### ISSUE TITLE
Regression in `is_subset` for Range, FiniteSet

### ISSUE THREAD

**Issue by lr4d** [sympy/sympy#18124]
I'm guessing this was introduced in #17848 .

```
import sympy
from sympy.sets import Range, FiniteSet

print(f"SymPy version: {sympy.__version__}")
print(Range(-3, 4, 1).is_subset(FiniteSet(-10, 10)))
```

Output at commit 99663a6d90 on master branch:
```
SymPy version: 1.6.dev
None
```
Behavior is as expected on 1.5:
```
SymPy version: 1.5
False
```

**Comment by gschintgen** [comment]
You're right: in the new `is_subset` infrastructure there's no handler for (Range, FiniteSet).
https://github.com/sympy/sympy/blob/master/sympy/sets/handlers/issubset.py

It shouldn't be difficult to add one though, at least for non-symbolic Ranges:
- check `Range.size` and return False if it's infinite or larger than `FiniteSet`'s size
- check (using `fuzzy_and`) that all elements of `Range` are contained in `FiniteSet`.

For symbolic Ranges this may also be possible in some cases, but I'm not familiar with the specifics of `Range`.
