### ISSUE TITLE
How to use rewrite?

### ISSUE THREAD

**Issue by proy87** [sympy/sympy#18125]
`(tan(x)*sec(x)*csc(x)**2).rewrite([tan, sec], tan)`
How to rewrite it in terms of tan and sec? Right now it rewrites in terms of tan only.

**Comment by Mohitbalwani26** [comment]
To rewrite an expression in terms of a function, `use expr.rewrite(function)`.
For your example i guess you just need to change `csc(x)**2` to either` tan` or `sec` so you can break it into 2 variables` first_half = tan(x)*sec(x)`  and` later_half = (csc(x)**2).rewrite(tan) #here you can replace tan with sec also`.finally` print(first_half * later_half)`

**Comment by Mohitbalwani26** [comment]
@proy87 is your problem solved?

**Comment by proy87** [comment]
Yes.
