### ISSUE TITLE
Unexpected outputs  predefined input in sympy/core/numbers.py

### ISSUE THREAD

**Issue by MeIbtihajnaeem** [sympy/sympy#18143]
**The input is** 
>> Comp(_,3.14)
**expected output** 
True
**Actual output** 
     Throwing exception 
Traceback (most recent call last):
  File "/usr/lib/python3.6/code.py", line 91, in runcode
    exec(code, self.locals)
  File "<console>", line 1, in <module>
NameError: name '_' is not defined

Is this a bug or not kindly guide me i want to start contributing in sympy .

**Comment by ShubhamKJha** [comment]
Closing this in reference to https://github.com/sympy/sympy/pull/18142#issuecomment-569208477
