### ISSUE TITLE
Unexpected evalf impact on sqrt printing

### ISSUE THREAD

**Issue by skywodd** [sympy/sympy#18148]
Hello,

I'm having some troubles with ``sqrt()`` and ``evalf()`` with Sympy 1.4 and 1.5.

- If I ``print(sqrt(x))``, the output is "sqrt(x)" as expected.
- Now, if i ``print(sqrt(x).evalf())``, the output is "x**0.5".

I known, internally ``sqrt(x)`` is just a shortcut for ``Pow(x, S.Half)``. But for my use-case, I *really* need to display the result as "sqrt(x)", not "x**0.5". 

The problem is, by reading the ``StrPrinter``'s class source code, it should already display the "sqrt(...)" format by default according to the docstring of ``StrPrinter._print_Pow()``. And it's true, until ``evalf()`` is used.

Using ``print_tree()``,  it seem ``evalf()`` replace ``S.Half`` with ``Float(0.5)``. And because ``StrPrinter`` use ``is S.Half`` to detect the special case of ``sqrt()``, everything break and the output is always "x**0.5".

Here a minimal example of the problem :
``` python
import sympy as sp
from sympy.printing.tree import print_tree

x = sp.Symbol("x")
fx = sp.sqrt(x)
fxf = fx.evalf()

# Without evalf(), StrPrinter work as expected
print(fx)
print_tree(fx)

# With evalf(), StrPrinter is not working as expected
print(fxf)
print_tree(fxf)
```

This issue may be related to #18054 but I'm not really sure because I have the same output with 1.4 and 1.5.

PS I use ``evalf()`` to shrink a very big output expression into a simple expression with only constants and sub-expressions with variables, like "x*12+sqrt(x/7)+16.864" for example.

**Comment by oscarbenjamin** [comment]
You could turn the the `0.5` exponents back into `S.Half`:
```julia
In [13]: expr = cos(1)**2 + sqrt(x)                                                                                                                           

In [14]: expr                                                                                                                                                 
Out[14]: 
        2   
√x + cos (1)

In [15]: expr.evalf()                                                                                                                                         
Out[15]: 
 0.5                    
x    + 0.291926581726429

In [16]: expr.evalf().replace(lambda e: e.is_Pow and e.exp == 0.5, lambda e: sqrt(e.base))                                                                    
Out[16]: √x + 0.291926581726429
```

**Comment by sylee957** [comment]
You can also use `nfloat`

**Comment by skywodd** [comment]
I've tested both solutions and it's working perfectly now.

Thanks!
