### ISSUE TITLE
trigsimp does not simplify expression

### ISSUE THREAD

**Issue by namannimmo10** [sympy/sympy#18144]
`trigsimp(sin(x)**2 - (sin(2*x) / tan(x))) `
 gives output: ` sin(x)**2 - sin(2*x)/tan(x)`

**Comment by jksuom** [comment]
`fu` is more efficient.
```
>>> fu(sin(x)**2 - sin(2*x)/tan(x))
-3*cos(2*x)/2 - 1/2
```

**Comment by namannimmo10** [comment]
> `fu` is more efficient.

oh, I see. i forgot about `fu` existing. 
Anyways, do you have any idea how to fix this issue?

**Comment by jksuom** [comment]
It looks like `trigsimp` was not intended to do everything that `fu` does, presumably to save time. One could add various parts of `fu` to `trigsimp` but it is not obvious how those should be chosen to be generally useful.

**Comment by namannimmo10** [comment]
okay! Thanks.

**Comment by gschintgen** [comment]
There's also:
```
trigsimp(sin(x)**2 - (sin(2*x) / tan(x)), method="fu")
```
which returns the same result as plain `fu`.
https://docs.sympy.org/latest/modules/simplify/simplify.html#sympy.simplify.trigsimp.trigsimp
