### ISSUE TITLE
sympy integration bug...doesn't check with wolfram alpha...

### ISSUE THREAD

**Issue by wm2015email** [sympy/sympy#18154]
I've attached screen snapshots.

![bad](https://user-images.githubusercontent.com/17484682/71544643-416ce700-2950-11ea-825a-b2df819e223c.png)

![good](https://user-images.githubusercontent.com/17484682/71544645-43cf4100-2950-11ea-8527-a7d89e04daf5.png)

![stuff10](https://user-images.githubusercontent.com/17484682/71544714-c952f100-2950-11ea-867f-f7a5c0271ae6.png)

![tmp3](https://user-images.githubusercontent.com/17484682/71544725-de2f8480-2950-11ea-89df-6493dfc8e137.png)

**Comment by wm2015email** [comment]
sympy version is: '1.1.1'

**Comment by wm2015email** [comment]
also using ActiveState Python 3.5 on Windows 10....

**Comment by risubaba** [comment]
The integration is correct.
Your simplification is wrong.
a**4 after going into the bracket will become a**8

**Comment by oscarbenjamin** [comment]
You will get a nicer answer if you use Rational rather than Float:
```julia
In [17]: (1 / (x**2 + a**2)**(3/2)).integrate(x)                                                                                                              
Out[17]: 
                      -3.0  
0.564189583547756⋅√π⋅a    ⋅x
────────────────────────────
             ________       
            ╱      2        
           ╱      x         
          ╱   1 + ──        
         ╱         2        
       ╲╱         a         

In [18]: (1 / (x**2 + a**2)**(S(3)/2)).integrate(x)                                                                                                           
Out[18]: 
        x        
─────────────────
         ________
        ╱      2 
 3     ╱      x  
a ⋅   ╱   1 + ── 
     ╱         2 
   ╲╱         a 
```
The answer also comes out nicer if you declare your symbols as positive:
```julia
In [20]: x, a = symbols('x, a', positive=True)                                                                                                                

In [21]: (1 / (x**2 + a**2)**(S(3)/2)).integrate(x)                                                                                                           
Out[21]: 
       x       
───────────────
      _________
 2   ╱  2    2 
a ⋅╲╱  a  + x 
```

**Comment by gschintgen** [comment]
If I'm reading this right, there's no fundamental issue here, except the usual gotcha of `3/2` vs `S(3)/2`, i.e. `Rational` vs. `Float`. For further information, see here: https://docs.sympy.org/latest/gotchas.html#python-numbers-vs-sympy-numbers

Closing.
