### ISSUE TITLE
Boolean algebra on sets and other mutually-exclusive values?

### ISSUE THREAD

**Issue by abl** [sympy/sympy#18150]
Hello! I think I might be misusing the logic pieces of Sympy and might need a different type of solver...but I'm hoping it's just user error. :)

I'm trying to simplify expressions that contain sets and inversions thereof. The actual sets are significantly larger but this expresses the core of it:

```python
from sympy import *
from sympy.logic.boolalg import *

# This is the set of all fruit:
apple, banana, orange = symbols("apple,banana,orange")

# I'd like to be able to express the following...
# ~apple -> banana | orange
# ~banana -> apple | orange
# ~orange -> apple | banana

# Here are some independent properties:
rotten, clean = symbols("rotten,clean")

allergic = apple | banana

edible = ~allergic & ~rotten & clean
# clean & ~rotten & ~(apple | banana)

simplified = simplify_logic(edible)
# clean & ~apple & ~banana & ~rotten

# The ultimate goal:
goal = clean & ~rotten & orange
```

I've tried adding constraints using `Implies`, `Equivalent`, and `Xor` but nothing seems to remove `~apple & ~banana` from the output of `simplify_logic` - and some of the approaches are exponential to the size of the set...

**Comment by abl** [comment]
Searched for a few new terms and found #7950 - seems similar insofar as I think I could map this in to that.

**Comment by abl** [comment]
The simplest solution I can find is `simplify_logic(simplified.replace(~apple, banana | orange).replace(~banana, apple | orange))` but this presupposes quite a bit and doesn't help with problems like `(apple | banana) & (banana | orange)`.

Continuing from above, the simplest solution I can find to that is:

```python
# h/t pyeda for onehot
onehot = Or(And(~apple, ~banana, orange), And(~apple, banana, ~orange), And(apple, ~banana, ~orange))

orand = (apple | banana) & (banana | orange)

simplified_orand = simplify_logic(orand & onehot)
# banana & ~apple & ~orange

final_orand = simplify_logic(simplified_orand.replace(~apple, banana | orange).replace(~banana, apple | orange).replace(~orange, apple | banana))
# banana
```

**Comment by oscargus** [comment]
No, it is not related to the simplification. The thing is that you need to replace `~apple` with `banana | orange` explicitly. There is no functionality to state a number of boolean relations and end up with a simplified one. When you perform `simplify_logic(edible)` it does exactly that, simplifies the expression which at the moment doesn't know about oranges.

**Comment by xchani** [comment]
I meet a similar but a lit bit different problem: `(orand & onehot) >> banana`. It can be simplified to `true` without explicit substitution.

**Comment by asmeurer** [comment]
Perhaps you can make use of `satisfiable`:

```
apple, banana, orange = symbols("apple,banana,orange")

clauses = [
~apple >> (banana | orange),
~banana >> (apple | orange),
~orange >> (apple | banana),
]

rotten, clean = symbols("rotten,clean")

allergic = apple | banana

edible = ~allergic & ~rotten & clean
```

```
>>> satisfiable(And(edible, *clauses))
{rotten: False, banana: False, clean: True, apple: False, orange: True}
>>> list(satisfiable(And(edible, *clauses), all_models=True))
[{rotten: False, banana: False, clean: True, apple: False, orange: True}]
```

From here we see that `~rotten & ~banana & clean & ~apple & orange` is equivalent to your formulation, since it's the only model. Removing `~apple & ~banana` seems to be incorrect (if you add `apple` or `banana` to the `satisfiable()` clauses the result becomes UNSAT).

> I meet a similar but a lit bit different problem: (orand & onehot) >> banana. It can be simplified to true without explicit substitution.

`simplify_logic` seems to be able to do this:

```
>>> simplify_logic((orand & onehot) >> banana)
True
```

**Comment by xchani** [comment]
> `simplify_logic` seems to be able to do this:

Yes, that's what I did and works well.
