### ISSUE TITLE
Suggestion on `core.evaluate` module

### ISSUE THREAD

**Issue by mcpl-sympy** [sympy/sympy#18161]
As I understand, `core.evaluate` module is first developed to handle the global value of `evaluate` parameter. Then, it is extended to handle `distribute` parameter as well.
Since more global parameters might appear in the future, I think this module can be renamed to `core.parameters` for clarity.

Besides that, if more parameters are added, it will be annoying to have all `global_foo[0]`, `global_bar[0]`, and so on. I am thinking of a dict-like handler named `global_parameters` to manage every global parameters. It will behave like this:

1. Its `__getitem__()` method returns `global_foo` object.
```
>>> global_parameters
{'evaluate': [True], 'distribute': [True]}
>>> global_parameters['evaluate']
[True]
```

2. It has `foo` property that returns or sets the value of global `foo`.
```
>>> global_parameters.evaluate
True
>>> global_parameters.evaluate = False
>>> global_parameters.evaluate
False
>>> global_parameters
{'evaluate': [False], 'distribute': [True]}
```

3. Its properties are not `bool` - They are callable new classes so that they can be used as context manager.
```
>>> from sympy.abc import x
>>> with global_parameters.evaluate(False):
         print(x + x)
x + x
```

I have already written a code which satisfies suggestion 1 and 2. It seems to be working well. How does everyone think about it?

**Comment by oscarbenjamin** [comment]
Is your code thread-safe?

**Comment by mcpl-sympy** [comment]
> Is your code thread-safe?

I didn't check it.
`global_parameters` works as singleton and relegates every operations to `global_foo` it contains, so hopefully it will cause no problem as long as `global_foo` does the job right.

Can you suggest the way to check its thread safety?

**Comment by oscarbenjamin** [comment]
We should really use thread local storage rather than global variables. Mutable global variables that are not thread-local are not thread-safe.

**Comment by mcpl-sympy** [comment]
> We should really use thread local storage rather than global variables. Mutable global variables that are not thread-local are not thread-safe.

Thanks. I didn't know about thread safety before. I'm curious: does the current approach in `core.evaluate` satisfies thread safety? How does it achieve this?
Also, then how can I ensure the thread safety of `global_parameters`? Will blocking suggestion 2 (make the global parameter mutable by implementing setter) do?

**Comment by oscarbenjamin** [comment]
I don't think that the current approach is thread-safe because it just uses a list. That list will be shared between threads so if one thread sets global evaluate to True then it will affect the other threads. To be thread-safe this global needs to use thread-local storage.
