### ISSUE TITLE
Is it correct that Mul expands an expression?

### ISSUE THREAD

**Issue by proy87** [sympy/sympy#18170]
Why `Mul(2,(x+1))` gives `2x+2` instead of `2(x+1)`?

**Comment by smichr** [comment]
It's a [feature](https://github.com/sympy/sympy/issues/4596) that usually does what you want (depending on what you are doing and who you are ;-)). It can be disabled with `evaluate=False`:

```python
>>> with evaluate(False):
...    2*(x+1)
2*(x + 1)
>>> Mul(2, x + 1, evaluate=False)
2*(x + 1)
```

**Comment by proy87** [comment]
No, it can't be disabled.
Because `1/(2(x+1)).as_numer_denom()` returns `1, 2x+2`. Same with fraction and there is no flag for `evaluate=False`.

**Comment by smichr** [comment]
Whenever the first two args of an expression (or subexpression) are a rational and a sum, the rational will be expanded into the sum. To avoid this you either have to use 'evaluate=False' while building up your expression as you want it to appear or use careful placement of arguments
```python
>>> 1/(x+1)/2
1/(2*(x + 1))
```
Or you can use `factor_terms` to pull out such factors:
```
>>> 1/(2*(x + 1))
1/(2*x + 2)
>>> factor_terms(_)
1/(2*(x + 1))
```
