### ISSUE TITLE
How to extend lambdify?

### ISSUE THREAD

**Issue by m93a** [sympy/sympy#18183]
I have defined my own classes that extend `Bra`, `Ket` and `InnerProduct` from `sympy.physics.quantum`. I want to make them output custom code when used with lambdify. Something like this:
```python
>>> lambdify( (m,n), MyInnerProduct(MyBra(m),MyKet(n)) )
lambda (m,n): 1 if m==n else 0
```
I read through the code but I wasn't able to find a way to define lambdify code output for my custom class.

**Comment by m93a** [comment]
I was able to extend the `pycode` method by implementing a [`_pythoncode` method](https://github.com/sympy/sympy/blob/7f92c96417d066700d096105282d6fe47ea085ef/sympy/printing/pycode.py#L79), which is the `printmethod` for python. My code now does this:
```python
>>> MyInnerProduct._pythoncode = lambda *args: 'None'
>>> pycode(MyInnerProduct(MyBra('a'),MyKet('b')))
'None'
```

However `lambdify` doesn't reflect this. Does it use a different `printmethod`?

**Comment by m93a** [comment]
I figured out that monkey-patching `AbstractPythonCodePrinter` with method called `_print_(class name)` was the way.

I append an example for anyone facing the same problem:
```python
from sympy.printing.pycode import AbstractPythonCodePrinter

def _print_inner_prod(self, expr):
    bra,ket = expr.args
    
    
    if not isinstance(bra, OrthogonalBra) or not isinstance(ket, OrthogonalKet):
        print(bra.func, ket.func)
        raise NotImplementedError('Only implemented for orthogonal states')
    
    if len(ket.args) != len(bra.args):
        raise ValueError('Cannot multiply a ket that has a different number of labels.')

    conditions = []

    for i in range(len(ket.args)):
        conditions.append('{a} == {b}'.format(
            a = self._print(ket.args[i]),
            b = self._print(bra.args[i])
        ))

    return '(1 if {c} else 0)'.format(
        c = ' and '.join(conditions)
    )

AbstractPythonCodePrinter._print_InnerProduct = _print_inner_prod
```
This specific example is related to the PR request #18182

**Comment by oscarbenjamin** [comment]
It might be worth adding a rewrite to `KroneckerDelta` so you can do `MyInnerProduct(...).rewrite(KroneckerDelta)`. Then you could use that in the printers.

I think that the printers are extended by adding methods like `_print_MyInnerProduct` which are checked against the name of the class. It would be better if is was at least possible to define the printing method as a method on `MyInnerProduct` but I don't think that's currently supported.

**Comment by m93a** [comment]
Talking about `KroneckerDelta`… It currently not supported by the code printer. You can check out my PR #18185 for this.
