### ISSUE TITLE
`trigsimp` for hyperbolic trig functions should be better documented

### ISSUE THREAD

**Issue by proy87** [sympy/sympy#18197]
How can I convert `sinh(a)sinh(b)+cosh(a)cosh(b)` into `cosh(a+b)`?

**Comment by gschintgen** [comment]
The internal helper `TR10i` does as it is intended: it applies a certain precise transformation to trigonometric functions. It is not applicable here.

`trigsimp` works just fine for your example. (It uses Osborne's rule to apply trig rules, notably those of Fu's algorithm, that is TR10i and others, to hyperbolic trig functions.)

The use of `trigsimp` for *hyperbolic* trig functions could be better documented in `trigsimp`'s docstring. I'll mark this issue as a documentation issue.
