### ISSUE TITLE
Cancel doesn't expand the product of irrational conjugates

### ISSUE THREAD

**Issue by meganly** [sympy/sympy#18205]
```
>>> cancel((2+I)*(3-I))
>>> 7+I

>>> cancel((2+I)*(2-I))
>>> (2+I)*(2-I)
```

I would have expected cancel to return 5.

**Comment by jksuom** [comment]
I think that `cancel` was designed to remove common factors from the numerator and denominator of a rational expression. The result `7 + I` looks accidental. `expand` is the function that is typically used for simplifying products like `(2 + I)*(2 - I)`.

**Comment by ShubhamKJha** [comment]
It happens because somewhere during the execution of`cancel`, `expand` is also called. The expanded results are then checked to form a `Poly` object.
https://github.com/sympy/sympy/blob/6be36ff06dce9b806012703102bd04fd227cdb52/sympy/polys/polytools.py#L6621-L6625

The results are like this.
```py
>>> p1,q1 = ((2-I)*(2+I)).as_numer_denom()
>>> p1, q1
((2 - I)*(2 + I), 1)
>>> p2,q2 = ((2+I)*(3+I)).as_numer_denom()
>>> p2, q2
((2 + I)*(3 + I), 1)
>>> parallel_poly_from_expr((p1, q1))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/shubhamkjha/Dev/opensource/sympy/sympy/polys/polytools.py", line 4311, in parallel_poly_from_expr
    return _parallel_poly_from_expr(exprs, opt)
  File "/home/shubhamkjha/Dev/opensource/sympy/sympy/polys/polytools.py", line 4366, in _parallel_poly_from_expr
    raise PolificationFailed(opt, origs, exprs, True)
sympy.polys.polyerrors.PolificationFailed: can't construct polynomials from (2 - I)*(2 + I), 1
>>> parallel_poly_from_expr((p2, q2))
([Poly(5*I + 5, I, domain='ZZ'), Poly(1, I, domain='ZZ')], {'gens': (I,), 'domain': ZZ, 'polys': False})
>>>
```
This apparently is creating a `Poly` with `I` as a generator. I assume this is not intended.

**Comment by meganly** [comment]
> I think that `cancel` was designed to remove common factors from the numerator and denominator of a rational expression.

I actually think it does a little more: `cancel` takes any rational function and puts it into the standard canonical form p/q where p and q are expanded polynomials with no common factors.  Obviously `(2+I)*(2-I)` is not a rational function, but I thought `cancel` would try to intelligently mimic the behavior with rational functions.

**Comment by asmeurer** [comment]
I agree that `cancel` should expand as well. 

This is failing because of this

```py
>>> from sympy.polys import parallel_poly_from_expr
>>> a = (2+I)*(2-I)
>>> b = (2+I)*(3-I)
>>> parallel_poly_from_expr((b, 1))
([Poly(I + 7, I, domain='ZZ'), Poly(1, I, domain='ZZ')], {'gens': (I,), 'domain': ZZ, 'polys': False})
>>> parallel_poly_from_expr((a, 1))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "./sympy/polys/polytools.py", line 4311, in parallel_poly_from_expr
    return _parallel_poly_from_expr(exprs, opt)
  File "./sympy/polys/polytools.py", line 4366, in _parallel_poly_from_expr
    raise PolificationFailed(opt, origs, exprs, True)
sympy.polys.polyerrors.PolificationFailed: can't construct polynomials from (2 - I)*(2 + I), 1
```

**Comment by asmeurer** [comment]
Just `Poly(a)` also fails (but not `Poly(b)`).

**Comment by iamabhishek0** [comment]
I don't think `7+I`is accidental because according to Documentation 
> cancel() will take any rational function and put it into the standard canonical form, p/q, where p and q are **_expanded polynomials_** with no common factors, and the leading coefficients of p and q do not have denominators (i.e., are integers).
