### ISSUE TITLE
StrPrinter does not print class names properly

### ISSUE THREAD

**Issue by mcpl-sympy** [sympy/sympy#18223]
For some classes, StrPrinter does not dynamically print the name of their subclasses.

For example:
```python
>>> from sympy import Derivative
>>> from sympy.abc import x
>>> class Deriv(Derivative):
...     pass
>>> print(Deriv(x,x))
Derivative(x, x)    # Expected Deriv(x, x)
```

I found that this is because in `StrPrinter._print_Derivative()`, class name is fixed to be `'Derivative'`.

Many other classes are same. Will it be OK to fix this to `expr.__class__.__name__` for not all, but a few suitable classes?

**Comment by asmeurer** [comment]
It should do that for every class. See also https://github.com/sympy/sympy/issues/6751

**Comment by mcpl-sympy** [comment]
I was wrong. Since StrPrinter displays the object in mathematical sense, it would be better to use current approach. It is ReprPrinter which displays the object in programming sense.
