### ISSUE TITLE
Intersection of ImageSets raises Index Error

### ISSUE THREAD

**Issue by proy87** [sympy/sympy#18237]
`ImageSet(Lambda(n, 2*n), S.Integers).intersect(ImageSet(Lambda(n, 3*n), S.Integers))` raises `IndexError`.

**Comment by gschintgen** [comment]
With current master:
```
In [33]: ImageSet(Lambda(n, 2*n), S.Integers).intersect(ImageSet(Lambda(n, 3*n), S.Integers))
Out[33]: {6⋅n | n ∊ ℤ}
```
This should be one of the cases taken care of by #18200. I'm fairly confident that intersections of Integer-based ImageSets work fine in master. If not, please don't hesitate to file a new issue.
