### ISSUE TITLE
nonlinsolve raises TypeError

### ISSUE THREAD

**Issue by proy87** [sympy/sympy#18248]
`nonlinsolve([x*y**3-sqrt(2)/3, x*y**6-4/(9*( sqrt (3)))],x,y)`

**Comment by oscarbenjamin** [comment]
Looks like a bug in polys:
```
>>> from sympy import *
>>> from sympy.abc import x, y
>>> nonlinsolve([x*y**3-sqrt(2)/3, x*y**6-4/(9*( sqrt (3)))],x,y)


Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/enojb/current/sympy/sympy/sympy/solvers/solveset.py", line 3400, in nonlinsolve
    if is_zero_dimensional(polys, symbols):
  File "/Users/enojb/current/sympy/sympy/sympy/polys/polytools.py", line 6796, in is_zero_dimensional
    return GroebnerBasis(F, *gens, **args).is_zero_dimensional
  File "/Users/enojb/current/sympy/sympy/sympy/polys/polytools.py", line 6808, in __new__
    polys, opt = parallel_poly_from_expr(F, *gens, **args)
  File "/Users/enojb/current/sympy/sympy/sympy/polys/polytools.py", line 4311, in parallel_poly_from_expr
    return _parallel_poly_from_expr(exprs, opt)
  File "/Users/enojb/current/sympy/sympy/sympy/polys/polytools.py", line 4325, in _parallel_poly_from_expr
    f, g = f.unify(g)
  File "/Users/enojb/current/sympy/sympy/sympy/polys/polytools.py", line 385, in unify
    _, per, F, G = f._unify(g)
  File "/Users/enojb/current/sympy/sympy/sympy/polys/polytools.py", line 400, in _unify
    dom, lev = f.rep.dom.unify(g.rep.dom, gens), len(gens) - 1
  File "/Users/enojb/current/sympy/sympy/sympy/polys/domains/domain.py", line 265, in unify
    return K0.unify_with_symbols(K1, symbols)
  File "/Users/enojb/current/sympy/sympy/sympy/polys/domains/domain.py", line 245, in unify_with_symbols
    return K0.unify(K1)
  File "/Users/enojb/current/sympy/sympy/sympy/polys/domains/domain.py", line 321, in unify
    return K0.__class__(K0.dom.unify(K1.dom), *_unify_gens(K0.orig_ext, K1.orig_ext))
  File "/Users/enojb/current/sympy/sympy/sympy/polys/domains/algebraicfield.py", line 31, in __init__
    self.ext = to_number_field(ext)
  File "/Users/enojb/current/sympy/sympy/sympy/polys/numberfields.py", line 1051, in to_number_field
    minpoly, coeffs = primitive_element(extension, gen, polys=True)
  File "/Users/enojb/current/sympy/sympy/sympy/polys/numberfields.py", line 837, in primitive_element
    g = minimal_polynomial(gen, x, polys=True)
  File "/Users/enojb/current/sympy/sympy/sympy/polys/numberfields.py", line 655, in minimal_polynomial
    result = _minpoly_compose(ex, x, domain)
  File "/Users/enojb/current/sympy/sympy/sympy/polys/numberfields.py", line 523, in _minpoly_compose
    if dom.is_QQ and _is_sum_surds(ex):
  File "/Users/enojb/current/sympy/sympy/sympy/simplify/simplify.py", line 211, in _is_sum_surds
    if not ((y**2).is_Rational and y.is_extended_real):
TypeError: unsupported operand type(s) for ** or pow(): 'Tuple' and 'int'
```

**Comment by jksuom** [comment]
This is the same issue as in https://github.com/sympy/sympy/issues/17276: The `ext` argument of `AlgebraicField.__init__()` may sometimes contain a tuple (minimal polynomial, root). That should be checked and only the root should be assigned to `orig_ext`. `to_number_field()` can make use of the tuple as a short-cut: https://github.com/sympy/sympy/blob/ee2c2666ee735ff616fd7c912e23ae968e8d90e7/sympy/polys/numberfields.py#L1048-L1049

**Comment by mohitacecode** [comment]
I am working on this issue.

**Comment by mohitacecode** [comment]
The tuple returned is of type:
((minimal polynomial, root))
so I did these changes:(But again this(`TypeError: 'Pow' object is not subscriptable`) is showing.
```
diff --git a/sympy/polys/domains/algebraicfield.py b/sympy/polys/domains/algebraicfield.py
index a6f1c569d3..cfa1c5de5e 100644
--- a/sympy/polys/domains/algebraicfield.py
+++ b/sympy/polys/domains/algebraicfield.py
@@ -27,7 +27,11 @@ def __init__(self, dom, *ext):
 
         from sympy.polys.numberfields import to_number_field
 
-        self.orig_ext = ext
+        if type(ext) is tuple:
+            self.orig_ext = ext[0][1:]
+        else:
+            self.orig_ext = ext
         self.ext = to_number_field(ext)
         self.mod = self.ext.minpoly.rep
         self.domain = self.dom = dom
```

**Comment by jksuom** [comment]
> if type(ext) is tuple:

The situation is a little more complicated. `ext` is a tuple of length 1 and its sole element is again a tuple (of length 2). See how `to_number_field()` handles it in the [comment](https://github.com/sympy/sympy/issues/18248#issuecomment-571193537) above.

**Comment by mohitacecode** [comment]
Ok I have changed it but it is now showing 

```
 File "/home/mohit/Documents/sympy-master/sympy/sympy/polys/domains/domain.py", line 103, in convert_from
    raise CoercionFailed("can't convert %s of type %s from %s to %s" % (element, type(element), base, self))
sympy.polys.polyerrors.CoercionFailed: can't convert ANP([mpq(3,1)], [mpq(1,1), mpq(0,1), mpq(-2,1)], QQ) of type <class 'sympy.polys.polyclasses.ANP'> from QQ<sqrt(2)> to QQ<sqrt(2) + sqrt(3)>
```

**Comment by jksuom** [comment]
It seems that TypeError was fixed. That could be tested independently of nonlinsolve. But another issue turns up: Conversion from one number field to another has not been implemented. It looks like there should be a method `AlgebraicField.from_AlgebraicField`. Its implementation could probably be based on the `numberfields` module.

**Comment by mohitacecode** [comment]
Okay I agree with you but `numberfields` module looks large is there any particular point where I can start from?

**Comment by jksuom** [comment]
Perhaps `to_number_field` and its dependencies `primitive_element` and `field_isomorphism. ANP is a low level representation of elements of an algebraic field analogous to DMP. Its principal part is the list of coefficients for representing an algebraic number as a polynomial in the primitive element.

**Comment by mohitacecode** [comment]
I found this on `stackexchange` is it ANP's?

```
Represent an algebraic number a by a finite list of integers and two rational numbers. The integers are the coefficients of a polynomial that has a as a root, and the two rational numbers are the bounds of an interval that contains exactly one distinct root of the polynomial.
```

**Comment by jksuom** [comment]
That is a more verbose explanation.

**Comment by mohitacecode** [comment]
Okay I will take a look on `numberfields` module and will start implementing `AlgebraicField.from_AlgebraicField` ASAP.

So should I follow the given definition?

**Comment by jksuom** [comment]
What do you mean by "given definition"?

**Comment by mohitacecode** [comment]
>Represent an algebraic number a by a finite list of integers and two rational numbers. The integers are the coefficients of a polynomial that has a as a root, and the two rational numbers are the bounds of an interval that contains exactly one distinct root of the polynomial.

I was referring to this.

**Comment by jksuom** [comment]
That is not how ANP was implemented. I think that we should abide by that. No need for new representations.

**Comment by mohitacecode** [comment]
Okay sure

**Comment by mohitacecode** [comment]
I have understand how `to_number_field` works. But I have some little uncertainity that about `AlgebraicField.from_AlgebraicField` what should be its input and output like? can you please put some light on it?

**Comment by jksuom** [comment]
It should have parameters `(K1, a, K0)` where `K0` and `K1` are instances of `AlgebraicField` and `a` is an element of `K0`. The method should convert `a` to an element of `K1`. That could probably be done by first converting `a` to a SymPy expression.

**Comment by mohitacecode** [comment]
Okay I am thinking to use `AlgebraicField.to_sympy` to convert an `a` to an sympy expression and then returning `return k1(a)`.
What do you think? will this be sufficient?

**Comment by jksuom** [comment]
There is also `.from_sympy`. That is probably what `K1(a)` would call after running some checks.

**Comment by mohitacecode** [comment]
>Okay I am thinking to use AlgebraicField.to_sympy to convert an a to an sympy expression and then returning return k1(a)

Sorry for late reply I rethink and find out that we probably can not use `AlgebraicField.to_sympy` 
since we are not passing `self` in `AlgebraicField.from_AlgebraicField`. Is there any another method we can use?

**Comment by jksuom** [comment]
`K1` will be `self` in `K1.from_sympy()`.

**Comment by mohitacecode** [comment]
I am using this implemenation now.
I am using this (`a = N(a)`) beacuse without this it was showing this error.
`sympy.polys.polyerrors.CoercionFailed: expected `Rational` object, got -sqrt(2)`
what do you think ?
```
    def from_AlgebraicField(K1, a, K0):
        a = K0.to_sympy(a)
        a = N(a)
        return K1(a)
```

**Comment by jksuom** [comment]
Are the fields `K0` and `K1` as in [this comment](https://github.com/sympy/sympy/issues/18248#issuecomment-585246497) and what is the value of `a`?

**Comment by mohitacecode** [comment]
As you mentioned `K0` and `K1` will be instances of AlgebraicField and `a` is an element of `K0`.
and `a` will be of type `ANP`

**Comment by jksuom** [comment]
But are their values equal to what was shown in the comment?

    ANP([mpq(3,1)], [mpq(1,1), mpq(0,1), mpq(-2,1)], QQ) of type <class 'sympy.polys.polyclasses.ANP'> from QQ<sqrt(2)> to QQ<sqrt(2) + sqrt(3)>

**Comment by mohitacecode** [comment]
Yes it is same

```
k0 = QQ<sqrt(2)>
k1 = QQ<sqrt(2) + sqrt(3)>
a = ANP([mpq(3,1)], [mpq(1,1), mpq(0,1), mpq(-2,1)], QQ)
```

**Comment by jksuom** [comment]
> sympy.polys.polyerrors.CoercionFailed: expected Rational object, got -sqrt(2)

Where does this error appear?

**Comment by mohitacecode** [comment]
from the error it seems that it occurs in `gmpyrationalfield.py", line 44`.

these are only the last lines of error.
```
  File "/home/mohit/Documents/sympy-master/sympy/sympy/polys/domains/gmpyrationalfield.py", line 44, in from_sympy
    raise CoercionFailed("expected `Rational` object, got %s" % a)
sympy.polys.polyerrors.CoercionFailed: expected `Rational` object, got -sqrt(2)
```

**Comment by mohitacecode** [comment]
I tried using `a = N(a)` and it solves but the answer comming seems bit absurd.

here it is:
```
>>> nonlinsolve([x*y**3-sqrt(2)/3, x*y**6-4/(9*( sqrt (3)))],x,y)
FiniteSet((135172622308969151362646202540044470995633/156083899754301874613622599150379091580000, 10*32546339005083698656375407096853289599330446428569705753691643480924405875393895**(1/3)/3910326406787134179600682539), (135172622308969151362646202540044470995633/156083899754301874613622599150379091580000, -5*32546339005083698656375407096853289599330446428569705753691643480924405875393895**(1/3)/3910326406787134179600682539 - 5*10848779668361232885458469032284429866443482142856568584563881160308135291797965**(1/3)*3**(5/6)*I/3910326406787134179600682539), (135172622308969151362646202540044470995633/156083899754301874613622599150379091580000, -5*32546339005083698656375407096853289599330446428569705753691643480924405875393895**(1/3)/3910326406787134179600682539 + 5*10848779668361232885458469032284429866443482142856568584563881160308135291797965**(1/3)*3**(5/6)*I/3910326406787134179600682539))
```

**Comment by jksuom** [comment]
> from the error it seems that it occurs in gmpyrationalfield.py", line 44.

I still cannot see where that would be called. There is no such error on my system:
```
>>> K0 = QQ.algebraic_field(sqrt(2))
>>> K1 = QQ.algebraic_field(sqrt(2), sqrt(3))
>>> a = K0(3); a
ANP([mpq(3,1)], [mpq(1,1), mpq(0,1), mpq(-2,1)], QQ)
>>> K1.from_sympy(K0.to_sympy(a))
ANP([mpq(3,1)], [mpq(1,1), mpq(0,1), mpq(-10,1), mpq(0,1), mpq(1,1)], QQ)
```

**Comment by mohitacecode** [comment]
It is working now.
I want to ask few things:
1.)When we used `return K1.from_sympy(a)` it is running fine.
2.)But what I have done initially is `return K1(a)` it throws error.

and both `return K1.from_sympy(a)`  and `return K1(a)` returns same thing.
It seems intersting to me I would really love to know the reason that why it is throwing the error in this case(`return K1(a)`).

```
>>> K1(K0.to_sympy(a))
ANP([mpq(3,1)], [mpq(1,1), mpq(0,1), mpq(-10,1), mpq(0,1), mpq(1,1)], QQ)
>>> K1.from_sympy(K0.to_sympy(a))
ANP([mpq(3,1)], [mpq(1,1), mpq(0,1), mpq(-10,1), mpq(0,1), mpq(1,1)], QQ)
```

**Comment by mohitacecode** [comment]
I will make a pr very soon.
