### ISSUE TITLE
Interval(0, 1).union(FiniteSet(1, x)) drops 'x'

### ISSUE THREAD

**Issue by gschintgen** [sympy/sympy#18241]
Somehow `x` is discarded in the second example:
```
In [1]: Interval(0, 1).union(FiniteSet(2, x))
Out[1]: [0, 1] ∪ {2, x}                                                                                                        
In [2]: Interval(0, 1).union(FiniteSet(1, x))
Out[2]: [0, 1]
```

**Comment by gschintgen** [comment]
Found it.
https://github.com/sympy/sympy/blob/ee2c2666ee735ff616fd7c912e23ae968e8d90e7/sympy/sets/handlers/union.py#L138
`Interval.contains(x)` returns a relational. This must be wrapped in `fuzzy_bool` to obtain a sane value.

I'll submit a PR.

**Comment by oscarbenjamin** [comment]
`Interval.contains` should give `Contains` rather than `Relational`:
```julia
In [13]: S = Interval(0, 1)                                                                                                                    

In [14]: S.contains(x)                                                                                                                         
Out[14]: 0 ≤ x ∧ x ≤ 1

In [15]: S.contains(I)                                                                                                                         
Out[15]: False

In [16]: S.contains(x).subs(x, I)                                                                                                              
---------------------------------------------------------------------------
TypeError 
```

**Comment by gschintgen** [comment]
> ```julia
> In [16]: S.contains(x).subs(x, I)                                                                                                              
> ---------------------------------------------------------------------------
> TypeError
> ```

That's unfortunate indeed. However I'd venture to say that is a separate issue. If `Interval.contains(x)` were to return a `Contains` object, the present issue would remain:
```
In [1]: i = Interval(0, 1)

In [2]: i.contains(x)
Out[2]: 0 ≤ x ∧ x ≤ 1

In [3]: bool(_)
Out[3]: True

In [4]: Contains(x, i)
Out[4]: x ∈ [0, 1]                                                                                                                         
In [5]: bool(_)
Out[5]: True 
```
The `if not b.contains(x)` part I quoted above is incorrect either way since it's not in accordance with Sympy's ternary logic. A one line fix (`if b.contains(x) != True` or `if not fuzzy_bool(...)`) is necessary either way.

That being said, I think the `contains` issue above merits its own issue. (It's also peculiar that `contains` may return any of the following types: boolean, Contains, Relational. Intuitively that's at least one too much.) I'll file a separate issue.
