### ISSUE TITLE
parse_expr requires local_dict to be a dict since sympy 1.5

### ISSUE THREAD

**Issue by terrorfisch** [sympy/sympy#18259]
4839dbe267bd7115208b942c697d559dfe70bd6b introduced an `isinstance` check on the local_dict argument which broke my code/hack to dynamically insert IndexedBased. Is there a reason for not allowing `Mapping` like `eval` does?

I guess the recommended way to do what I want to do is using a transformation?

**Comment by oscarbenjamin** [comment]
Can you give a short example of how you are using `parse_expr`?

**Comment by terrorfisch** [comment]
I wrote a convenience wrapper for sympify for the users of my library that accepts something like `'a[i]'`.

Here is the shortened code:
```python
class IndexedBasedFinder(dict):
    """Acts as a symbol lookup and determines which symbols in an expression a subscripted."""

    def __getitem__(self, k) -> sympy.Expr:
        """magic"""

    def __contains__(self, k) -> bool:
        return True

def get_subscripted_symbols(expression: str) -> set:
    # track all symbols that are subscipted in here
    indexed_base_finder = IndexedBasedFinder()
    sympy.sympify(expression, locals=indexed_base_finder)
    return indexed_base_finder.indexed_base

def my_sympify(expr: Union[str, Number, sympy.Expr, numpy.str_], **kwargs) -> sympy.Expr:
    try:
        return sympy.sympify(expr, **kwargs, locals=sympify_namespace)
    except TypeError:
        if True:
            indexed_base = get_subscripted_symbols(expr)
            return sympy.sympify(expr, **kwargs, locals={**{k: sympy.IndexedBase(k)
                                                            for k in indexed_base},
                                                         **sympify_namespace})
```

**Comment by oscarbenjamin** [comment]
I guess the officially recommended way is to write a transformer like `auto_symbol`:
https://github.com/sympy/sympy/blob/a1fc659e21ad217a1658d0cdea018918142ec976/sympy/parsing/sympy_parser.py#L532-L533

**Comment by terrorfisch** [comment]
What do you think about having a configurable context dependency as a toolbox for writing your own transformer? If I can come up with something reasonable are you interested in a pull request?
```python
expr_lookup = defaultdict(lambda: 'Symbol',
                          (('(', 'Function'),
                           ('[', 'IndexedBase')))

result.extend([(NAME, expr_lookup[nextTokVal]),
               (OP, '('),
               (NAME, repr(str(name))),
               (OP, ')'),
            ])
```

I will close this as the mapping compability of sympify was never explicitly documented although I vote for using the same interface as eval does.

**Comment by oscarbenjamin** [comment]
I don't know `parse_expr` myself. Possibly something like that would make the internal code cleaner as well. Ultimately I think we need a completely different way of parsing that doesn't involve `eval` but I guess that's a bit of a rewrite.

**Comment by asmeurer** [comment]
Subclassing dict or the relevant [collections abc](https://docs.python.org/3/library/collections.abc.html) should fix this for your code.
