### ISSUE TITLE
how to obtain particular output formation

### ISSUE THREAD

**Issue by handsomeboydy** [sympy/sympy#18262]
It really helped me a lot in my job,for which I really appreciate,but I want to obtain a result in the formation of a ratio of  two polynomials,rather than the formation in the picture below,what should I do?
![IMG_20200108_103804](https://user-images.githubusercontent.com/54144431/71946156-f9797a00-3203-11ea-99be-d22bf18fa28f.jpg)

**Comment by oscarbenjamin** [comment]
To get help with sympy ask on StackOverflow or the sympy mailing list. I recommend copy/pasting the text rather than sending a photo.

This place is for tracking bugs in sympy.
