### ISSUE TITLE
Incorrect results by `sympy.limit`

### ISSUE THREAD

**Issue by czgdp1807** [sympy/sympy#18265]
#### Description of the problem

Refer issues,

1. https://github.com/sympy/sympy/issues/13382
```
>>> import sympy
>>> from sympy.abc import n
>>> limit(n*(((n + 1)**2 + 1)/(n**2 + 1) - 1), n, oo)
0
```
The answer should be `2`.

2. https://github.com/sympy/sympy/issues/13403

Calculation of the following limit gives an incorrect result:
```
>>> import sympy
>>> from sympy.abc import n
>>> limit(n*(-1 + (n + log(n + 1) + 1)/(n + log(n))), n ,oo)
oo
```
The answer should have been  `1`.

3. https://github.com/sympy/sympy/issues/13416
```
>>> from sympy.abc import n
>>> limit((-n**3*log(n)**3 + (n - 1)*(n + 1)**2*log(n + 1)**3)/(n**2*log(n)**3), n ,oo) 
-1
```
The correct answer should have been 1.

4. https://github.com/sympy/sympy/issues/13462

The following code was run using sympy version 1.0, python version 3.4, Anaconda installation.
```
import sympy as spy
import sympy.abc as abc


N, k = spy.symbols('N, k', positive = True)
es = 1 - (1 - 1/(2*N))**k
e = 2*N*es
spy.pprint(e)
c0 = spy.limit(e, N, spy.oo)
spy.pprint(c0)
c1 = spy.limit(N*(e-c0), N, spy.oo)
spy.pprint(c1)
c2 = spy.limit((e-c0-c1/N)*(N*N), N, spy.oo)
spy.pprint(c2)
c2x = spy.limit(e*N*N-c0*N*N-c1*N, N, spy.oo)
spy.pprint(c2x)
```

It prints
 

```

    ⎛           k    ⎞
    ⎜  ⎛     1 ⎞     ⎟
2⋅N⋅⎜- ⎜1 - ───⎟  + 1⎟
    ⎝  ⎝    2⋅N⎠     ⎠
k
   2    
  k    k
- ── + ─
  4    4
-∞
 3    2     
k    k    k 
── - ── + ──
24   8    12

```
As you can see, the result for c2 is wrong, although it is able to calculate c2x correctly. 

If you are interested in fixing any of the above issues, refer the existing PRs attempting to fix the above issues.

#### References/Other comments

**Comment by asmeurer** [comment]
What is the purpose of this issue?

**Comment by czgdp1807** [comment]
Actually, the other four issues were stalled. So, I thought referencing them in one issue and putting it in the first page so that new contributors can try solving it. Let me know if there is a need to reopen the previous four issues and closing this one.

**Comment by oscarbenjamin** [comment]
That would make sense if you gathered the relevant useful information in this issue but if all it does is refer to the others I don't see the advantage in having this instead of them.

**Comment by czgdp1807** [comment]
I will edit the description shortly.

**Comment by asmeurer** [comment]
It's not clear to me that the issues all have the same underlying cause. So my preference would be to have separate issues, as a single issues with multiple parts tend to be closed prematurely by accident. 

At any rate, it would be good to copy the relevant information over here.
