### ISSUE TITLE
There is a mistake on the tutorial of SymPy 1.5.1

### ISSUE THREAD

**Issue by zr9558** [sympy/sympy#18282]
The website link is: [Advanced Expression Manipulation](https://docs.sympy.org/1.5.1/tutorial/manipulation.html#walking-the-tree)

```
>>> expr = 2**x + x*y
>>> srepr(expr)
```
"Add(Pow(Integer(2), Symbol('x')), Mul(Symbol('x'), Symbol('y')))"
is correct. However, the graph is incorrect.

![image](https://user-images.githubusercontent.com/8390499/72141664-3d1fdf80-33ce-11ea-9b7e-25af2ef0a455.png)

**Comment by ShubhamKJha** [comment]
It looks like that the graph is instead a representation of `x**2 + x*y`. The tutorial afterwards is explained with that in mind. 
It is easy to correct that. Simply needs to change to `expr = x**2 + x*y` in `sympy\doc\src\tutorial\manipulation.rst`.

**Comment by zr9558** [comment]
> It looks like that the graph is instead a representation of `x**2 + x*y`. The tutorial afterwards is explained with that in mind.
> It is easy to correct that. Simply needs to change to `expr = x**2 + x*y` in `sympy\doc\src\tutorial\manipulation.rst`.

Yeah~~~~

**Comment by asmeurer** [comment]
This was supposed to have been fixed already.

**Comment by asmeurer** [comment]
I guess the dotprinter is fixed, but the tutorial output is inconsistent. The example and preceding text should use `x**2`
