### ISSUE TITLE
is_polynomial doesn't count assumptions

### ISSUE THREAD

**Issue by proy87** [sympy/sympy#18284]
`n=Symbol('n',integer=True, positive=True)`
`(x**n).is_polynomial(x) `returns `False`. Shouldn't it be `True`?

**Comment by gschintgen** [comment]
This should be the relevant docstring:
https://github.com/sympy/sympy/blob/921379b4a781a781bf2543f81e785ca45d7370f1/sympy/core/expr.py#L2522-L2532

So I'd say it works as intended and documented.
