### ISSUE TITLE
expand_trig deep False

### ISSUE THREAD

**Issue by proy87** [sympy/sympy#18288]
I want to convert `sin(x**2+2)` to `sin(x**2)cos(2)+cos(x**2)sin(2)`, but `expand_trig` expands further.
`deep=False` doesn't help. How can I apply only sum/difference formulas for trigs?

**Comment by gschintgen** [comment]
There's no publicly documented function to do this very specific manipulation.
But in Fu's algorithm for simplifying trig expressions various standard transformations are needed. Those are all implemented as separate internal helpers in https://github.com/sympy/sympy/blob/master/sympy/simplify/fu.py. More specifically:
```
In [15]: from sympy.simplify.fu import TR10

In [16]: TR10(sin(x**2+2))
Out[16]:
   ⎛ 2⎞                    ⎛ 2⎞
sin⎝x ⎠⋅cos(2) + sin(2)⋅cos⎝x ⎠
```

**Comment by proy87** [comment]
@gschintgen , thank you.
