### ISSUE TITLE
Complexes and ComplexRegion have incorrect .contains() logic

### ISSUE THREAD

**Issue by gschintgen** [sympy/sympy#18280]
Below `x` is just a general symbol:
```
In [1]: i1 = Interval(1, 2)

In [2]: i2 = Interval(3, 5)

In [3]: cr = ComplexRegion(i1*i2)

In [4]: cr.contains(x)
Out[4]: True

In [5]: cr
Out[5]: {x + y⋅ⅈ | x, y ∊ [1, 2] × [3, 5]}
```
This is because a symbolic `Boolean` expression is incorrectly used in a plain `if`:
https://github.com/sympy/sympy/blob/957f468b80325e33a40c37bbb50a6ca09e9784f8/sympy/sets/fancysets.py#L1264-L1271
Since the Sympy logic expression is neither a (Python) `False` nor `None`, it is interpreted as `True`.

The same bug is a few lines further down in the polar region handling.

If I'm reading the code correctly, there's more to fix: after all product sets are checked, `_contains` returns `False`, but the actual result could just as well be unknown, i.e. `None`.
(IIRC it is `Set.contains()` that then transforms a `None` value returned by a `_contains` method into a `Contains` object.)

**Comment by gschintgen** [comment]
Also: at creation a polar ComplexRegion seems to canonicalize `theta` to a subset of `[0, 2pi)`, but `_contains` then checks whether `arg(other)` (lying in `(-pi, pi]`) is contained in the correct argument range. This must also be fixed (preferably so that the canonicalization is done relative to the principal argument instead of [0, 2pi)).

**Comment by oscarbenjamin** [comment]
I'm not sure why ComplexRegion is there at all. Its only real use is defining Complexes but it would be easier and less confusing to do that directly from ImageSet.

It also conflates complex numbers with tuples of real numbers:
```julia
In [4]: S = ComplexRegion(Interval(0, 1)*Interval(0, 1))                                                                                       

In [5]: 1 + I in S
Out[5]: True

In [6]: (1, 1) in S
Out[6]: True
```
That carries over to Complexes:
```julia
In [7]: (1, 1) in Complexes
Out[7]: True
```

**Comment by gschintgen** [comment]
> I'm not sure why ComplexRegion is there at all.

I'm not really sure about that but I've stumbled over these issues due to a failing `nonlinsolve` doctest while locally testing some (supposedly) unrelated changes to `Interval`.

**Comment by gschintgen** [comment]
I've submitted a draft PR. Unfortunately this issue runs deeper than I initially thought:
While it's easy enough to fix `ComplexRegion._contains()`, there are now a number of failures in `solveset` tests. I investigated the first one and essentially it comes down to this:
Current master is quite "optimistic" when it comes to membership in `Complexes`:
```
In [10]: Complexes.contains(1/x)
Out[10]: True
```
whereas with the corrected membership tests that don't erroneously return `True` due to the bug detailed in the OP, the result is a `Contains` object:
```
In [2]: Complexes.contains(1/x)
Out[2]:
1
─ ∈ ℂ
x
```
I'll investigate a bit more, but I'm not sure how far I will go with this.
For completeness's sake, here's the example that I analyzed:
```
In [11]: solveset_complex(4*x*(1 - a * sqrt(x)), x)
Out[11]: 
⎧   1 ⎫
⎪0, ──⎪
⎨    2⎬
⎪   a ⎪
⎩     ⎭
```
That's what is expected by the test suite. With the code of the PR, this raises an exception, because internally an `Intersection(Complexes, FiniteSet(1/a**2))` (IIRC) is no longer reduced to only the FiniteSet and then it's no longer iterable...

Do note that the expected answer is not always mathematically valid, so one could argue that it's an incorrect test result. But I suspect the other failures are of a similar nature.
In order to not cripple `solveset` I suppose one could forcibly reduce such `Intersection(Complexes, X)` to simply `X` (in strategic places in `solveset`, not generally), but that's rather a hackish workaround than a proper solution.

**Comment by oscarbenjamin** [comment]
I don't think `solveset` really handles arbitrary parameters correctly in general (#16861). It's not clear what is the best approach.

**Comment by gschintgen** [comment]
> I don't think `solveset` really handles arbitrary parameters correctly in general (#16861). It's not clear what is the best approach.

Right, I've seen #16861 but forgot to chime in: IMHO it would be a valuable addition to Sympy! (And I think the piecewise presentation of the solution sets is more readable than the conditionset version.)

I'll have a look at a few other test suite failures with the draft PR and sum it up here.

**Comment by gschintgen** [comment]
The rabbit hole goes deeper...
With (almost) current master:
```
In [1]: z = Symbol('z')

In [2]: print(z.is_real)
None

In [3]: Reals.contains(z)
Out[3]: -∞ < z ∧ z < ∞

In [4]: print(z.is_complex)
None

In [5]: Complexes.contains(z)
Out[5]: True
```
If it were the other way around (e.g. `zoo` being accepted as `is_complex`, as it may have been before the "complex implies finite" changes), that could arguably be fine, but this rather surprising (and wrong).

(As for `Out[3]` I intend to submit a PR to change the output to a `Contains` object unless z is known to be `extended_real`.)
