### ISSUE TITLE
General polynomial congruence - Discussion

### ISSUE THREAD

**Issue by abhinav28071999** [sympy/sympy#18291]
In #18195 I implemented quadratic congruence, and it is possible to extend it to a general polynomial congruence. In general for prime modulus we have to do a naive search(there is no way around this) and when it is composite modulus we can use Hensel lifting to obtain all roots.
With this we can also extend the solvers module. The _solve_modular function does not support general polynomial congruence. Moreover since the quadratic congruence has been implemented we can also extend the _solve_modular function to accept quadratic function.       
If it sounds good to you i would like to work on this.

**Comment by asmeurer** [comment]
It sounds good. We already implement some number theory concepts that require inefficient algorithms, like `discrete_log` and `factorint`. Maybe it makes sense to have a user warning that gets emitted for cases where it is highly likely to not complete in a reasonable amount of time.

**Comment by abhinav28071999** [comment]
This has been solved.
