### ISSUE TITLE
NotImplementedError in limit 

### ISSUE THREAD

**Issue by proy87** [sympy/sympy#18306]
`limit(sin ( sqrt (x))/ sqrt ( sin (x)),x,0,'+')`

**Comment by mohitacecode** [comment]
Yeah I think this limit is unsolvable. Any suggestion @oscarbenjamin

**Comment by proy87** [comment]
@mohitacecode , the value of the limit is `1`.

**Comment by jksuom** [comment]
The implementation of expansions (and limits) of non-integer powers is currently restricted to positive exponents. Therefore, the denominator `sqrt(sin(x))` will not be handled. It seems that all real exponents could be accepted.
```
--- a/sympy/core/power.py
+++ b/sympy/core/power.py
@@ -1558,7 +1558,7 @@ def e2int(e):
 
             nuse = n - ei
 
-            if e.is_extended_real and e.is_positive:
+            if e.is_real:
                 lt = b.as_leading_term(x)
 
                 # Try to correct nuse (= m) guess from:
```
