### ISSUE TITLE
bug in _solve_trig1

### ISSUE THREAD

**Issue by proy87** [sympy/sympy#18315]
I noticed the following bug in solveset.
`(sin(x)+cos(x/2)).rewrite(exp).subs(exp(I*x), y)` outputs `-I*(y - 1/y)/2 + exp(I*x/2)/2 + exp(-I*x/2)/2`
`(sin(x)+cos(x/2)).rewrite(exp).subs(exp(x), y))` outputs `y**(I/2)/2 - I*(y**I - y**(-I))/2 + y**(-I/2)/2`

If `x` is real, then
`(sin(x)+cos(x/2)).rewrite(exp).subs(exp(I*x), y)` outputs `-I*(y - 1/y)/2 + exp(I*x/2)/2 + exp(-I*x/2)/2`
`(sin(x)+cos(x/2)).rewrite(exp).subs(exp(x), y))` outputs `y**(I/2)/2 - I*(y**I - y**(-I))/2 + y**(-I/2)/2`

So, if arg is not an integer multiple, then `subs` doesn't handle it.

Next,
`(sinh(x)+cosh(x/2)).rewrite(exp).subs(exp(I*x), y)` outputs `exp(x/2)/2 + exp(x)/2 - exp(-x)/2 + exp(-x/2)/2`
`(sinh(x)+cosh(x/2)).rewrite(exp).subs(exp(x), y))` outputs `y/2 + exp(x/2)/2 + exp(-x/2)/2 - 1/(2*y)`

If `x` is real, then
`(sinh(x)+cosh(x/2)).rewrite(exp).subs(exp(I*x), y)` outputs `exp(x/2)/2 + exp(x)/2 - exp(-x)/2 + exp(-x/2)/2`
`(sinh(x)+cosh(x/2)).rewrite(exp).subs(exp(x), y))` outputs `sqrt(y)/2 + y/2 - 1/(2*y) + 1/(2*sqrt(y))`

With hyperbolic function the situation is similar, except once thing: only when symbol is real, then `subs` performs what is expected.

How to make it work properly?
If I change symbol to real before using solveset, how will this influence the result (solving on complex domain)?

**Comment by gschintgen** [comment]
I guess `_solve_trig1` needs some pre-processing on the arguments. Something similar, or even identical, to what is done in `_solve_trig2`:
https://github.com/sympy/sympy/blob/c4423ca61ebcc9db91eefcbd2ffef7aa2b07d690/sympy/solvers/solveset.py#L598-L619

Foremost this is intended to reduce the degrees of the resulting polynomial (`_solve_trig1` could probably use that too...), but as far as I remember it also handles rationals well.

I've also been wondering if this absence of pre-processing is not the actual reason `_solve_trig2` is needed at all. AFAIR I stumbled over the PR introducing `_solve_trig2` and it was added as an alternative to `_solve_trig1` for cases where it could not solve the equation, but maybe those deficiencies were only a symptom of the present issue.

**Comment by mijo2** [comment]
Hi @gschintgen, I would like to help you on this issue, will that be ok?

**Comment by gschintgen** [comment]
> 
> 
> Hi @gschintgen, I would like to work with you on this issue, will that be ok?

Feel free to investigate further and submit a PR.

**Comment by mijo2** [comment]
Hi @gschintgen, I am new to the community and I have been busy with some other issue. Sorry for the late response. I wanted to know what kind of behaviour do we need from the sympy modules. Like regarding this issue, what is supposed to be the correct answer? Like for ```exp(I*x/2)```, should it be substituted by ```sqrt(y)``` everywhere where ever possible?

**Comment by gschintgen** [comment]
That'd be an improvement, but I think that more advanced pre-processing would be better: Compare what happens with e.g. `sin(x/2)` if you call `_solve_trig1` and what is done in `_solve_trig2`. Rational coefficients should ideally be extracted before `.subs`titution. But beware of #18427. (i.e. the preprocessing cited in my previous comment is not without issue either...)

A step-by-step comparison of `_solve_trig1` and `_solve_trig2` should help you along: the basic principle is the same, just the rewriting is different. (And the missing pre-processing in trig1...)

**Comment by mijo2** [comment]
Ok got it! Will start with the comparisons and will try to investigate this issue further.

**Comment by mijo2** [comment]
@gschintgen when I ran (sin(x/2)).rewrite(exp).subs(exp(I*x), y) with a debugger, it never reached or used ```_solve_trig``` function.

**Comment by gschintgen** [comment]
I've filed a draft PR that would fix this issue: #19507.
(It leads to rather nice improvements in the main trig solver.)
