### ISSUE TITLE
Error in trigsimp

### ISSUE THREAD

**Issue by proy87** [sympy/sympy#18332]
`trigsimp((34*(-sin(x) - cos(x))*exp(5*x) + 121*(17 - 5*sqrt(17))*exp(x*(7 - sqrt(17))/2) + 121*(17 + 5*sqrt(17))*exp(x*(sqrt(17) + 7)/2))*exp(-6*x)/408)`

**Comment by smichr** [comment]
What is the error?
```python
>>> eq.equals(trigsimp(eq))
True
```

**Comment by proy87** [comment]
I think it is fixed, because a couple of days ago there was `KeyError` at live.sympy.org
