### ISSUE TITLE
Clean up gotchas in _eval_Mod

### ISSUE THREAD

**Issue by sylee957** [sympy/sympy#18338]
Things like
```python
Mod(factorial(4, evaluate=False), 3)
Mod(factorial(5, evaluate=False), 6)
```
shouldn't return python integers, but sympy integers.

I see `_eval_Mod` in `factorial` and `binomial` have such pitfalls.
When you see `return 0`, it should be changed to `return S.Zero`.

**Comment by asmeurer** [comment]
Shouldn't it be automatically sympified?

**Comment by sylee957** [comment]
I don’t think that it is.
I see a lot of _eval does not sympify, and I thought that this was left on purpose that post-sympify can slow down things slightly for stuff which can be resolved in a more careful review.

**Comment by namannimmo10** [comment]
I'm working on this issue.

**Comment by oscarbenjamin** [comment]
> Shouldn't it be automatically sympified?

We don't generally have auto-sympification of return values. We could add that e.g. here:
https://github.com/sympy/sympy/blob/c580299ec3f05c5e8fb554a0b60a327cf2c11258/sympy/core/function.py#L294-L297
That would involve unnecessary auto-simplification in most cases. I think this is the kind of thing that would be better handled by mypy.
