### ISSUE TITLE
There isn't a public API method to update a Symbol's assumptions.

### ISSUE THREAD

**Issue by l-johnston** [sympy/sympy#18344]
# System
- Windows 10
- Python 3.8.1
- Sympy 1.5.1

# Description
There isn't a public API method to update a Symbol's assumptions after instantiation. Currently, the only way to set assumptions is to use the Symbol constructor.

# What I tried:
```python
>>> from sympy import Symbol
>>> from sympy.core.assumptions import StdFactKB
>>> x = Symbol("x")
>>> x.assumptions0
{"commutative": True}
>>> x.assumptions0.update(StdFactKB({"real": True}))
>>> x.assumptions0
{"commutative": True}
```
The update is ignored - not even raising an exception!

# Workaround
```python
>>> from sympy import Symbol
>>> from sympy.core.assumptions import StdFactKB
>>> x = Symbol("x")
>>> x._assumptions.update(StdFactKB({"real": True}))
>>> x.assumptions0
{"commutative": True, "real": True, "extended_real": True, ...}
```
The workaround requires the use of the private variable Symbol._assumptions.

**Comment by oscarbenjamin** [comment]
Symbol objects are immutable and the assumptions are not supposed to be changed. Modifying the assumptions in any way is not supported and will lead to unpredictable behaviour. The `_assumptions` attribute is a private internal attribute that should not be depended on.

**Comment by l-johnston** [comment]
The documentation doesn't state that Symbol objects are immutable and the Symbol.assumptions0 dictionary still exposes update.

**Comment by asmeurer** [comment]
Every SymPy object is immutable, not just Symbol. This is stated in the tutorial https://docs.sympy.org/1.5.1/tutorial/basic_operations.html?highlight=immutable. If you have suggestions for other places it should be mentioned let us know.

Python doesn't have an immutable dictionary type, so the assumptions dictionaries have to be mutable.

**Comment by oscarbenjamin** [comment]
The `_assumptions` dictionary is internal and need to be mutable because for many objects it gets updated as properties are queried:
```julia
In [4]: s = exp(x)                                                                                                                             

In [5]: s._assumptions                                                                                                                         
Out[5]: {}

In [6]: s.is_positive                                                                                                                          

In [7]: s._assumptions                                                                                                                         
Out[7]: 
{'positive': None,
 'finite': None,
 'complex': None,
 'rational': None,
 'algebraic': None,
 'commutative': True,
 'zero': False,
 'extended_real': None,
 'extended_positive': None,
 'negative': None,
 'extended_negative': None}
```
I view all of that as an internal implementation detail that can be changed in any future release of SymPy.

In general in Python you should not access names that begin with underscore as that is the convention for indicating that something is private.

**Comment by l-johnston** [comment]
I agree.

There is a default_assumptions attribute that is settable, but does not appear to have any affect. What is the purpose of default_assumptions?

**Comment by asmeurer** [comment]
Attributes in SymPy generally shouldn't be modified either, unless the docs specifically say you should set them. Python makes you go out of your way to make an attribute read-only, and there's generally no point to doing so.

**Comment by asmeurer** [comment]
I'm not sure I understand what default_assumptions is. Maybe I'm misreading the code (the old assumptions core code is quite complicated), but it seems like it's a feature that is currently unused anywhere.

**Comment by oscarbenjamin** [comment]
The `default_assumptions` is a class attribute so it belongs to instances of the metaclass `ManagedProperties`. The idea is that any time you create a new instance of a `Basic` type it will initially receive a copy of the default assumptions from its class:
```julia
In [8]: class A(Basic): 
   ...:     is_positive = True 
   ...:                                                                                                                                        

In [9]: A.default_assumptions                                                                                                                  
Out[9]: 
{'positive': True,
 'extended_nonpositive': False,
 'extended_nonzero': True,
 'infinite': False,
 'extended_negative': False,
 'complex': True,
 'imaginary': False,
 'extended_real': True,
 'commutative': True,
 'zero': False,
 'real': True,
 'nonpositive': False,
 'nonnegative': True,
 'extended_positive': True,
 'finite': True,
 'extended_nonnegative': True,
 'hermitian': True,
 'nonzero': True,
 'negative': False}

In [10]: a = A()                                                                                                                               

In [11]: a.assumptions0                                                                                                                        
Out[11]: {}

In [12]: a._assumptions                                                                                                                        
Out[12]: 
{'positive': True,
 'extended_nonpositive': False,
 'extended_nonzero': True,
 'infinite': False,
 'extended_negative': False,
 'complex': True,
 'imaginary': False,
 'extended_real': True,
 'commutative': True,
 'zero': False,
 'real': True,
 'nonpositive': False,
 'nonnegative': True,
 'extended_positive': True,
 'finite': True,
 'extended_nonnegative': True,
 'hermitian': True,
 'nonzero': True,
 'negative': False}
```

**Comment by l-johnston** [comment]
In my library, I use sympy `factor` to factor an algebraic expression consisting of real, positive variables and operators from the set {*, /, **, sqrt}. This algebraic expression is an arbitrary string where I don't know the exact set of variables ahead of time. In `factor`, sympy will instantiate the variables in the string expression, but with the default assumption {"commutative": True}. I'd like to be able to tell sympy that all the variables are real and positive by default.

**Comment by oscarbenjamin** [comment]
You could use `posify`:
```julia
In [3]: from sympy import parse_expr, factor, posify                                                                                           

In [4]: expr = parse_expr('x**2 - y**2')                                                                                                       

In [5]: expr                                                                                                                                   
Out[5]: 
 2    2
x  - y 

In [6]: factor(expr)                                                                                                                           
Out[6]: (x - y)⋅(x + y)

In [7]: posify(expr)                                                                                                                           
Out[7]: 
⎛ 2    2              ⎞
⎝x  - y , {x: x, y: y}⎠

In [8]: posify(expr)[0].args[0].args[0]                                                                                                        
Out[8]: x

In [9]: posify(expr)[0].args[0].args[0].is_positive                                                                                            
Out[9]: True
```

**Comment by asmeurer** [comment]
You shouldn't rely on functions like `factor` accepting string input. It's better to use `sympify` or `parse_expr` to parse your strings first. 

The following will make `positive` the default for any symbols created by sympify

```py
>>> sympify('x + y', {'Symbol': lambda x: Symbol(x, positive=True)})
x + y
>>> sympify('x + y', {'Symbol': lambda x: Symbol(x, positive=True)}).is_positive
True
```

Or alternately you could replace the symbols with positive versions after parsing using something like `posify` as suggested by @oscarbenjamin.

**Comment by l-johnston** [comment]
My final workaround looks like:
```python
>>> from sympy import sympify, Symbol, sqrt, factor
>>> expr = "sqrt(x**2)" # arbitrary expression where I don't know the variables ahead of time
>>> rules = {"Symbol": lambda x: Symbol(x, real=True, positive=True), "sqrt": sqrt}
>>> factor(sympify(expr, rules))
x
```

I agree with closing the issue.

**Comment by sylee957** [comment]
I wonder if it can be a good idea to make sets callable and make something like
`S.Reals(x)` return another `x` coerced with `real=True` unless it was explicitly specified as `real=False` before.
