### ISSUE TITLE
simplify not working on Array (but working on sympy expressions)

### ISSUE THREAD

**Issue by ritzvik** [sympy/sympy#18361]
As far as I remember, simplify could operate on Arrays previously. Kindly see the snippet below :
```
>>> from sympy.abc import x
>>> from sympy import sin, cos, simplify, Array
>>> import sympy
>>> sympy.__version__
'1.5'
>>> A = Array([sin(2*x) - 2*sin(x)*cos(x), 0])
>>> simplify(A)
[-2*sin(x)*cos(x) + sin(2*x), 0]
>>> simplify(sin(2*x) - 2*sin(x)*cos(x))
0

```

Now it is not working on Array, but working on same expressions when each element on Array is simplified individually.

**Comment by sylee957** [comment]
As done in the matrix, `_eval_simplify` can be added to apply for each array elements.

**Comment by ritzvik** [comment]
> As done in the matrix, `_eval_simplify` can be added to apply for each array elements.

Yes I know alternatives are there. But I guess `simplify` used to work with `Array` in `v1.3`. Having the old functionality back would be good :)

**Comment by ritzvik** [comment]
@sylee957 Should I give it a try?

**Comment by mohitacecode** [comment]
@ritzvik can I try it?

**Comment by ritzvik** [comment]
> @ritzvik can I try it?

Well, the go ahead is not mine to give 😄

**Comment by mohitacecode** [comment]
Sure

**Comment by preetmishra** [comment]
@sylee957 Can I work on this?

**Comment by klakho0400** [comment]
it was working on v 1.4
will try to solve it
