### ISSUE TITLE
Difference between free_symbols and has

### ISSUE THREAD

**Issue by proy87** [sympy/sympy#18360]
Is there any difference between using `x in f.free_symbols` and `f.has(x)`? Except special cases for Integral etc.

**Comment by smichr** [comment]
`has` will be faster since it returns as soon as it sees the symbol(s) of interest, *no matter where they occur* (which is what you refer to as the "special case".

BTW, the mailing list would be a good place to raise such questions which aren't really an issue that needs to be fixed.
