### ISSUE TITLE
Sympy docs show SymPy 1.5.1 twice

### ISSUE THREAD

**Issue by namannimmo10** [sympy/sympy#18372]
![Screenshot from 2020-01-18 12-32-20](https://user-images.githubusercontent.com/43007653/72660104-f7c36980-39ee-11ea-8196-9f964d6bc1bb.png)
Here it shows SymPy 1.5.1 twice.

**Comment by mohitacecode** [comment]
@namannimmo10 where to edit these docs?

**Comment by ShubhamKJha** [comment]
Looks like the last line here was duplicated while docs were updated for sympy 1.5.1 https://github.com/sympy/sympy_doc/blob/fee564226584ab6042e8acb9574a09546ec6a20c/releases.txt#L21
Ping @oscarbenjamin

**Comment by oscarbenjamin** [comment]
That comes from running the release script. I guess because I ran the script twice it added the line twice.

This issue should be opened against `sympy_doc` rather than `sympy`.

**Comment by ShamanthNyk** [comment]
Can i work on this issue?

**Comment by asmeurer** [comment]
This should be fixed.
