### ISSUE TITLE
Invalid result in Limit

### ISSUE THREAD

**Issue by COOLIRON2311** [sympy/sympy#18378]
`Limit(ln(exp(3*x)+x)/ln(exp(x)+x**100), x, oo).doit()` gives the output of `9` although `3` was expected.
Sympy 1.5 on CPython 3.7.4 on Windows 10 64 bit.

**Comment by jksuom** [comment]
On 1.6, I get this:
```
In [10]: Limit(ln(exp(3*x)+x)/ln(exp(x)+x**100), x, oo).doit()
Out[10]: 3
```

**Comment by COOLIRON2311** [comment]
1.5.1 also gives 9
