### ISSUE TITLE
classify_ode doesn't recognise nth_linear_constant_coeff_undetermined_coefficients

### ISSUE THREAD

**Issue by Mohitbalwani26** [sympy/sympy#18408]
> ```julia
> In [58]: eq = f(x).diff(x, 2) - 49*f(x) - sinh(3*x)                                                                                     
> 
> In [59]: classify_ode(eq)                                                                                                         
> Out[59]: 
> ('nth_linear_constant_coeff_variation_of_parameters', 
>  'nth_linear_constant_coeff_variation_of_parameters_Integral')
> 
> ```
Although `dsolve(eq)` gives the correct answer but it should also classify this equation as `nth_linear_constant_coeff_undetermined_coefficients`
If it could have identified then solution time will also reduce as 'nth_linear_constant_coeff_variation_of_parameters' is slower than `nth_linear_constant_coeff_undetermined_coefficients`

**Comment by oscarbenjamin** [comment]
It doesn't look like `sinh` or `cosh` are checked for at all.

**Comment by Mohitbalwani26** [comment]
`sinh(x)` can be written as `(exp(x) - exp(-x))/2` so shouldn't the classifiers identify this?

**Comment by oscarbenjamin** [comment]
Yes. We can do that now:
```julia
In [1]: eq = f(x).diff(x, 2) - 49*f(x) - sinh(3*x)

In [2]: classify_ode(eq)
Out[2]: 
('nth_linear_constant_coeff_variation_of_parameters',
 'nth_linear_constant_coeff_variation_of_parameters_Integral')

In [3]: classify_ode(eq.rewrite(exp))
Out[3]: 
('nth_linear_constant_coeff_undetermined_coefficients',
 'nth_linear_constant_coeff_variation_of_parameters',
 'nth_linear_constant_coeff_variation_of_parameters_Integral')
```
However I think it would be better to handle `sinh` and `cosh` as well as `sin` and `cos` internally. If the user uses `sinh` then we should try to give them an answer in that form.

**Comment by Mohitbalwani26** [comment]
so `eq.rewrite(exp)`  should be used in `classify_ode`?

**Comment by oscarbenjamin** [comment]
I think it is better to not use rewrite. Rather the solver should handle sinh and cosh explicitly (like it does for sin and cos even though they can be written with exp).
