### ISSUE TITLE
Unpickling simple expressions errors

### ISSUE THREAD

**Issue by drhagen** [sympy/sympy#18438]
Unpickling SymPy expressions containing variables and constants appears to be broken when the the unpickling occurs in a separate process.

I ran the following script in a process on Python 3.7.6 or 3.8.1 using SymPy 1.5.1 on Ubuntu 18.04:

```
from sympy.parsing.sympy_parser import parse_expr
import pickle
from pathlib import Path
file = Path(f'temp1.pickle')
file.write_bytes(pickle.dumps(parse_expr('a/2')))
```

This prints out 15596. (I'll leave aside the observation that 15k seems like a lot of bytes to store this three-character expression.)

I then run the following script in a separate process:

```
import pickle
from pathlib import Path
file = Path(f'temp1.pickle')
pickle.loads(file.read_bytes())
```

This raises the following exception:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/david/anaconda/envs/old/lib/python3.7/site-packages/sympy/core/singleton.py", line 176, in __call__
    super(Singleton, self).__call__(*args, **kwargs)
TypeError: __new__() takes 1 positional argument but 3 were given
```

The variable and the constant are both needed to cause this exception. If I run enough commands in the second process, it suddenly starts working for reasons that are unclear.

**Comment by oscarbenjamin** [comment]
I tried the above by opening one isympy session to write the pickle and the another to read the pickle and it worked fine:
```
In [1]: import pickle 
   ...: from pathlib import Path 
   ...: file = Path(f'temp1.pickle') 
   ...: pickle.loads(file.read_bytes())                                                                                                        
Out[1]: 
a
─
2
```
Can you generate a piece of code that I can run starting from a single process (e.g. with multiprocessing or fork etc) to reproduce the problem?

> This prints out 15596

I get 9983 but yeah, that's surprisingly large either way.

**Comment by jksuom** [comment]
`pickle` will also include all attributes (and probably each one will take several bytes).
```
>>> from sympy.parsing.sympy_parser import parse_expr
>>> e = parse_expr('a/2')
>>> len(dir(e))
309
```

**Comment by drhagen** [comment]
Here is a one-shot script that reproduces the behavior:

```
import os
import pickle
from multiprocessing import Process, get_start_method, set_start_method
from pathlib import Path
from sympy.parsing.sympy_parser import parse_expr

if get_start_method(allow_none=True) is None:
    set_start_method('spawn')

def f():
    print('process id:', os.getpid())
    # Read
    import pickle
    from pathlib import Path
    file = Path('temp1.pickle')
    print(pickle.loads(file.read_bytes()))

if __name__ == '__main__':
    print('process id:', os.getpid())
    # Write
    file = Path('temp1.pickle')
    print(file.write_bytes(pickle.dumps(parse_expr('a/2'))))

    # Spawn
    p = Process(target=f)
    p.start()
    p.join()
```

Note that the the `set_start_method('spawn')` is required. It runs to completion if the start method is `'fork'`.

I am using Python installed via conda. The behavior is the same whether sympy is installed via conda or pip.

**Comment by drhagen** [comment]
Further investigation reveals that the behavior is seen in SymPy 1.5.1 and 1.5, but not in 1.4 and earlier.

**Comment by oscarbenjamin** [comment]
Thanks. Bisected to 9efefdd7d09a9eee72d6f866613ca1b7a8f2bae0

I guess this is something to do with instantiating `Complexes`. Not sure how that's in the pickle...

**Comment by oscarbenjamin** [comment]
Looking through the output of `pickle.dumps` it seems the large size of the pickle is because it stores the assumptions not very efficiently. Probably we should make it so that pickle only stores the assumptions for symbols and adding pickle support for the `FactKB` could make it smaller I think (it's basically a dict).

**Comment by jksuom** [comment]
It looks like the culprit is `Half`. Its pickle string contains the arguments 1 and 2.
```
In [41]: pickle.dumps(S.Half, 0)
Out[41]: b'csympy.core.numbers\nHalf\np0\n(L1L\nL2L\ntp1\nRp2\n(dp3\nb.'
```
In a fresh python session, it cannot be loaded:
```
>>> import pickle
>>> s = b'csympy.core.numbers\nHalf\np0\n(L1L\nL2L\ntp1\nRp2\n(dp3\nb.'
>>> pickle.loads(s)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jks/sympy/sympy/core/singleton.py", line 176, in __call__
    super(Singleton, self).__call__(*args, **kwargs)
TypeError: __new__() takes 1 positional argument but 3 were given
>>> 
```

**Comment by oscarbenjamin** [comment]
I think there should be a cleanup of Singletons. I remember around the time of the offending commit discovering this:
```julia
In [1]: from sympy.core.singleton import Singleton

In [2]: class A(metaclass=Singleton):
   ...:     pass 
   ...:

In [3]: a = A(1)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-3-7f95e1a053ca> in <module>
----> 1 a = A(1)

~/current/sympy/sympy.git/sympy/core/singleton.py in __call__(self, *args, **kwargs)
    176         if self not in Singleton._instances:
    177             Singleton._instances[self] = \
--> 178                 super(Singleton, self).__call__(*args, **kwargs)
    179                 # Invokes the standard constructor of SomeClass.
    180         return Singleton._instances[self]

TypeError: object() takes no parameters

In [4]: a = A()

In [5]: a = A(1)

In [6]: a = A(1, 3, 4, 6, 6)
```
What happens is that arguments to the constructor are ignored after the singleton instance is created. That means that you can see errors depending on the order in which things happen:
```python
>>> from sympy import S
>>> import pickle
>>> s = b'csympy.core.numbers\nHalf\np0\n(L1L\nL2L\ntp1\nRp2\n(dp3\nb.'
>>> pickle.loads(s)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/space/enojb/sympy/sympy.git/sympy/core/singleton.py", line 178, in __call__
    super(Singleton, self).__call__(*args, **kwargs)
TypeError: __new__() takes 1 positional argument but 3 were given
>>> S.Half
1/2
>>> pickle.loads(s)
1/2
```
A workaround for this failure is to do `from sympy import S; S.Half` before attempting to unpickle.

**Comment by oscarbenjamin** [comment]
> A workaround for this failure is to do `from sympy import S; S.Half` before attempting to unpickle.

This also explains why this isn't picked up in the pickling tests. We should test unpickling in a subprocess.

**Comment by asmeurer** [comment]
`Half` also gives problems when trying to subclass Rational. There was some discussion on Gitter about this a while back. https://gitter.im/sympy/sympy?at=5dfacdedb1701e50ca4aa5cd. I think the basic design of it is broken from an object oriented point of view. I'm not sure how to fix it. 

There are also a ton of issues with pickling in SymPy https://github.com/sympy/sympy/issues?utf8=%E2%9C%93&q=is%3Aopen+pickle. We have a [pickling test file](https://github.com/sympy/sympy/blob/master/sympy/utilities/tests/test_pickling.py), but it's incomplete and littered with xfails. We use so many metaclasses and metaprogramming that it breaks pickle's standard assumptions on how to recreate serialized objects. I know if you use cloudpickle things tend to work better, so I recommend that for practical usage at this time.

**Comment by oscarbenjamin** [comment]
It seems that `Singleton` *sub*classes should usually override `__getnewargs__`. I have a diff that seems to fix this:
```diff
diff --git a/sympy/core/numbers.py b/sympy/core/numbers.py
index 8ff2149dcf..f64688717c 100644
--- a/sympy/core/numbers.py
+++ b/sympy/core/numbers.py
@@ -2605,6 +2605,9 @@ class Zero(IntegerConstant, metaclass=Singleton):
 
     __slots__ = ()
 
+    def __getnewargs__(self):
+        return ()
+
     @staticmethod
     def __abs__():
         return S.Zero
@@ -2667,6 +2670,9 @@ class One(IntegerConstant, metaclass=Singleton):
 
     __slots__ = ()
 
+    def __getnewargs__(self):
+        return ()
+
     @staticmethod
     def __abs__():
         return S.One
@@ -2720,6 +2726,9 @@ class NegativeOne(IntegerConstant, metaclass=Singleton):
 
     __slots__ = ()
 
+    def __getnewargs__(self):
+        return ()
+
     @staticmethod
     def __abs__():
         return S.One
@@ -2775,6 +2784,9 @@ class Half(RationalConstant, metaclass=Singleton):
 
     __slots__ = ()
 
+    def __getnewargs__(self):
+        return ()
+
     @staticmethod
     def __abs__():
         return S.Half
diff --git a/sympy/functions/elementary/miscellaneous.py b/sympy/functions/elementary/miscellaneous.py
index 9f6b7cbd25..7aeee2c516 100644
--- a/sympy/functions/elementary/miscellaneous.py
+++ b/sympy/functions/elementary/miscellaneous.py
@@ -49,6 +49,13 @@ def __new__(cls):
         #construct "by hand" to avoid infinite loop
         return Expr.__new__(cls, Tuple(x), x)
 
+    @property
+    def args(self):
+        return ()
+
+    def __getnewargs__(self):
+        return ()
+
 Id = S.IdentityFunction
```
I'm still not sure why the bisected commit affects this though.

**Comment by jksuom** [comment]
> Singleton subclasses should usually override __getnewargs__

This looks like the proper fix.

**Comment by asmeurer** [comment]
> We should test unpickling in a subprocess.

We should test both. There are possible bugs where unpickling can break in the same process, e.g., if an unpickled object does not compare equal to the pickled object because of some bad `__eq__` implementation.

**Comment by mohitacecode** [comment]
I am working on this issue.
