### ISSUE TITLE
Infinite looping while computing Limit of Expression  in 1.5.1

### ISSUE THREAD

**Issue by pneudecorb** [sympy/sympy#18452]
This doesn't appear to happen using sympy 1.4.

The following will cause sympy to hang,

Limit(abs(log(x))**x,x,0).doit()

However, the following succeeds, 

Limit(abs(log(x))**x,x,0, '-').doit() --> 1

but, the following triggers the infinite recursion

Limit(abs(log(x))**x,x,0, '+').doit()

**Comment by ethankward** [comment]
Bisected to commit 73369023393b148038958406e0cce92bd4036f59. Before this it raised `NotImplementedError`.

**Comment by sachin-4099** [comment]
In the current master, for the given expressions, the answer evaluates quickly:
```
In [1]: Limit(abs(log(x))**x,x,0).doit()
Out[1]: 1

In [2]: Limit(abs(log(x))**x,x,0, '-').doit()
Out[2]: 1

In [3]: Limit(abs(log(x))**x,x,0, '+').doit()
Out[3]: 1
```

**Comment by gschintgen** [comment]
I can confirm @sachin-4099 's results. This only needs tests.

**Comment by akhil-dh1** [comment]
@gschintgen I can add tests but where do we need to add tests, can you guide me I am new to the community.

**Comment by sachin-4099** [comment]
> @gschintgen I can add tests but where do we need to add tests, can you guide me I am new to the community.

Add the tests to `test_limits` present in `series` module.
