### ISSUE TITLE
Evaluate square roots

### ISSUE THREAD

**Issue by proy87** [sympy/sympy#18475]
How to simplify `-48*sqrt(4 + 2*sqrt(5))/(1 + sqrt(5))**(3/2)` to `-24`?

**Comment by gschintgen** [comment]
You can use `nsimplify`:
```
In [1]: nsimplify(-48*sqrt(4 + 2*sqrt(5))/(1 + sqrt(5))**(S(3)/2))
Out[1]: -24
```
https://docs.sympy.org/1.5.1/modules/simplify/simplify.html?highlight=nsimplify#sympy.simplify.simplify.nsimplify


Note that questions about using Sympy are best asked in other channels (mailing list, stackoverflow).
