### ISSUE TITLE
Why acot(0) is pi/2?

### ISSUE THREAD

**Issue by proy87** [sympy/sympy#18480]
From the plot it is clearly seen, that inverse cotangent is not continuous at x=0.

**Comment by jksuom** [comment]
I think that `acot(0)` is correct but the values of `acot(x)` for negative `x` are wrong. Principal values can be obtained by adding `pi`.

**Comment by abhinav28071999** [comment]
I am taking this. Will send a pr soon.

**Comment by gschintgen** [comment]
AFAICT there's nothing to fix: there are two customary but incompatible definitions for `acot`:
- one that respects `acot(z) == atan(1/z)`
- one that respects `acot(z) + atan(z) == pi/2`

The first one is the one given by DLMF (https://dlmf.nist.gov/4.23) which is also in current use in Sympy. If I remember this correctly I read a while ago that in older editions of Abramowitz-Stegun the second definition was given, but in its successor (DLMF) the first one was retained.

The discontinuity is also documented in the docstring.

**Comment by gschintgen** [comment]
See also: #13679.

**Comment by jksuom** [comment]
[Wikipedia](https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Arctangent_Arccotangent.svg/294px-Arctangent_Arccotangent.svg.png) seems to conform to the second definition, but I agree that we can retain the first one. So there is nothing to fix and this can be closed.
