### ISSUE TITLE
Incorrect evaluation of limit

### ISSUE THREAD

**Issue by proy87** [sympy/sympy#18482]
`limit(sqrt (x**2 + 6*x) + (x**3 + x**2)/(x**2 + 1),x,-oo)` is `2`
`limit((x**3 + x**2 + sqrt(x*(x + 6))*(x**2 + 1))/(x**2 + 1),x,-oo)` is `1`, but should be `-2`, since expressions are equivalent.

**Comment by proy87** [comment]
Also, `limit((2*exp(3*x)/(exp(2*x) + 1))**(1/x),x,oo)` should be `E`.

**Comment by proy87** [comment]
Same as above.
`limit(x + (1 - x**2)*exp(1/x)/(x + 2),x,oo)` is `1`. `imit((x*(x + 2) + (1 - x**2)*exp(1/x))/(x + 2),x,oo)` should be `1`, but it is `2`.

**Comment by sachin-4099** [comment]
No longer an issue. All limits are getting evaluated correctly. The issue can be closed @oscarbenjamin @czgdp1807.

**Comment by oscarbenjamin** [comment]
Most examples do seem to be fixed. When were they fixed?

This example is still incorrect:
```
In [6]: limit((2*exp(3*x)/(exp(2*x) + 1))**(1/x),x,oo)                                                                                         
Out[6]: 
 7/3
ℯ 
```

**Comment by sachin-4099** [comment]
>Most examples do seem to be fixed. When were they fixed?
I myself don't know, perhaps: https://github.com/sympy/sympy/pull/18340

Merged 18 days ago, and the issue was opened 26 days ago.

**Comment by sachin-4099** [comment]
> This example is still incorrect:
> 
> ```
> In [6]: limit((2*exp(3*x)/(exp(2*x) + 1))**(1/x),x,oo)                                                                                         
> Out[6]: 
>  7/3
> ℯ 
> ```

Will have to debug mrv_leadterm for this in gruntz.py

**Comment by Saanidhyavats** [comment]
@oscarbenjamin can you give some directions on how to start with it? I have gone through all the steps which is involved in calculating the above limit but unable to get the bug

**Comment by Saanidhyavats** [comment]
> Same as above.
> `limit(x + (1 - x**2)*exp(1/x)/(x + 2),x,oo)` is `1`. `imit((x*(x + 2) + (1 - x**2)*exp(1/x))/(x + 2),x,oo)` should be `1`, but it is `2`.

The above query is showing the expected result which is 1
