### ISSUE TITLE
Incorrect evaluation of AccumBounds

### ISSUE THREAD

**Issue by proy87** [sympy/sympy#18481]
Possibly, I didn't understand the definition of `AccumBounds`, but, as for me, it is an interval, from which function can take any value.
So, `sin(oo)` is `<-1,1>` as sine can take any value from the interval `[-1,1]`.
On the other hand, `atan(1/sin(0))` can take only two values: `-pi/2` and `pi/2`. It is not an interval. But sympy still gives `AccumBounds`.
Is it correct behavior? If it correct, could I distinguish these two cases?

**Comment by jksuom** [comment]
`AccumulationBounds` only gives an interval containing the set of accumulation values. It does not imply that all values in the interval are accumulation values. It is hard to describe the set of accumulation values in general. It can be almost any closed set, not only two points or an interval. AFAIK there is no function or method in SymPy that would distinguish between the different possibilities.

**Comment by proy87** [comment]
@jksuom , thank you for clarification.
