### ISSUE TITLE
Bug in Mul

### ISSUE THREAD

**Issue by proy87** [sympy/sympy#18507]
`Mul(zoo, zoo, 0)` returns `zoo`, but should be `NaN`.

**Comment by jksuom** [comment]
https://github.com/sympy/sympy/blob/ef7bd27551b8f8fa7d55c85e51d8bb10a329545f/sympy/core/mul.py#L294-L296
This should not return, the last argument 0 will be ignored.

**Comment by mohitacecode** [comment]
I am working on this issue
