### ISSUE TITLE
NotImplementedError in limit

### ISSUE THREAD

**Issue by proy87** [sympy/sympy#18508]
`limit(sin(x)/sqrt(1-cos(x)),x,0) `

**Comment by gschintgen** [comment]
Can reproduce with 1.5 but not with master:
```
In [1]: limit(sin(x)/sqrt(1-cos(x)), x, 0)
Out[1]: √2

In [2]: limit(sin(x)/sqrt(1-cos(x)), x, 0, dir='+')
Out[2]: √2

In [3]: limit(sin(x)/sqrt(1-cos(x)), x, 0, dir='-')
Out[3]: -√2
```
The given result is correct, at least given Sympy's documented (but IMO incorrect) interpretation that limits are by default computed to the right.

I'm not sure if this can be closed right away or if we should add a regression test. Given the intricate nature of limit computations, I'd say it's best to add the test(s).

(BTW, with 1.5 all three variants above are raising the exception.)

**Comment by mijo2** [comment]
@gschintgen I can add the tests. Should I create a PR regarding same?
