### ISSUE TITLE
pi raised to infinity gives incorrect result

### ISSUE THREAD

**Issue by proy87** [sympy/sympy#18509]
`pi**oo` should be `oo`.

**Comment by gschintgen** [comment]
I get a perfectly valid result. Would you mind elaborating and showing *exact* (as in copy&paste) input and output?

**Comment by Smit-create** [comment]
I get the following output on master:
```
>>> from sympy import *
>>> pi**oo
pi**oo
```

**Comment by gschintgen** [comment]
> 
> 
> I get the following output on master:
> 
> ```
> >>> from sympy import *
> >>> pi**oo
> pi**oo
> ```

Me too, so I don't see the incorrect result announced in the title. AFAICT it's just not auto-evaluated.

**Comment by proy87** [comment]
@gschintgen , it is unexpected, because `2**oo` gives `oo` instead of `2**oo`.
Moreover, `2**oo / 3**oo` gives `NaN`, but `2**oo / pi**oo` gives `oo` and this is indeed incorrect.

**Comment by gschintgen** [comment]
> @gschintgen , it is unexpected, because `2**oo` gives `oo` instead of `2**oo`.

I agree that it's not optimal.

> Moreover, `2**oo / 3**oo` gives `NaN`, but `2**oo / pi**oo` gives `oo` and this is indeed incorrect.

That is indeed an issue, thanks for pointing it out.

**Comment by gschintgen** [comment]
I think there are two issues here to be fixed:
1. `pi**oo` does not auto-evaluate (but also other expressions; see below).
2. The wrong quotient result that still shouldn't return `oo` but NaN.

This behavior is not limited to `pi`:
```
In [1]: E**oo
Out[1]: ∞

In [2]: (E + 1)**oo
Out[2]:
       ∞
(1 + ℯ)

In [3]: 2**oo / (E + 1)**oo
Out[3]: ∞
```

**Comment by oscarbenjamin** [comment]
I think the problem is that the logic for evaluating `a**oo` is in `Rational._eval_power`, `Float._eval_power` and `Exp1._eval_power` rather than being handled generally in `Pow.__new__`. If this would evaluate in general then it would handle cases like this as well:
```julia
In [2]: x = Symbol('x', prime=True)                                                                                                            

In [3]: (x - 1).is_positive                                                                                                                    
Out[3]: True

In [4]: x > 1                                                                                                                                  
Out[4]: True

In [5]: x**oo                                                                                                                                  
Out[5]: 
 ∞
x 
```

For `oo / pi**oo` I think that the bug comes down to this:
```
In [2]: (1/pi**oo).is_extended_positive                                                                                                        
Out[2]: True
```

**Comment by sachin-4099** [comment]
```
In [3]: 2**oo / (E + 1)**oo
Out[3]:  oo*(1 + E)**(-oo)
```
Will this suffice, that is the result remains partially unevaluated.

**Comment by oscarbenjamin** [comment]
> Will this suffice, that is the result remains partially unevaluated.

Ideally it would evaluate but this is an improvement. An unevaluated result is always better than an incorrect evaluation.

**Comment by sachin-4099** [comment]
So shall I just start by committing the minor change pointed out by @skirpichev

**Comment by oscarbenjamin** [comment]
We should not copy changes from @skirpichev's fork for copyright reasons and also because I believe that in that fork the meanings of the assumptions is different from here.

**Comment by oscarbenjamin** [comment]
I have an old PR #16403 that tried to fix assumptions for `Pow`. That lead to a rabbit-hole of introducing `extended_real` etc and changing finite handling everywhere. The original PR is probably not usable now as the meanings of everything have changed since then. Probably it would be easier to fix those problems now.

To fix this particular issue we just need to find the place that gives the wrong result and change it.

**Comment by oscarbenjamin** [comment]
This fixes the wrong result:
```diff
diff --git a/sympy/core/power.py b/sympy/core/power.py
index b2e7c76b5d..545cbc07ee 100644
--- a/sympy/core/power.py
+++ b/sympy/core/power.py
@@ -506,7 +506,7 @@ def _eval_is_extended_positive(self):
             if self.base.is_extended_nonnegative:
                 return True
         elif self.base.is_positive:
-            if self.exp.is_extended_real:
+            if self.exp.is_real:
                 return True
         elif self.base.is_extended_negative:
             if self.exp.is_even:
```

**Comment by sachin-4099** [comment]
```
In [3]: 2**oo / (E + 1)**oo
Out[3]:  oo*(1 + E)**(-oo)
```
This change is producing this result only

**Comment by gschintgen** [comment]
> 
> 
> ```
> In [3]: 2**oo / (E + 1)**oo
> Out[3]:  oo*(1 + E)**(-oo)
> ```
> 
> This change is producing this result only and not NaN

I think the posted fix is for the wrong `oo` result, i.e. the second issue of this comment: https://github.com/sympy/sympy/issues/18509#issuecomment-579974293.

Having `(E+1)**oo` auto-evaluate requires more than just a one-line change. (See first part of linked comment.)

**Comment by sachin-4099** [comment]
> > ```
> > In [3]: 2**oo / (E + 1)**oo
> > Out[3]:  oo*(1 + E)**(-oo)
> > ```
> > 
> > 
> > This change is producing this result only and not NaN
> 
> I think the posted fix is for the wrong `oo` result, i.e. the second issue of this comment: [#18509 (comment)](https://github.com/sympy/sympy/issues/18509#issuecomment-579974293).
> 
> Having `(E+1)**oo` auto-evaluate requires more than just a one-line change. (See first part of linked comment.)
I know that thing but not evaluating to the fully correct result is fine right. I will make a PR soon then
