### ISSUE TITLE
exp(x)*erf(x*I) and exp(-x)*erf(x*I) don't work

### ISSUE THREAD

**Issue by namannimmo10** [sympy/sympy#18514]
```
>>> exp(x)*erf(x*I)
exp(x)*erf(I*x)
>>> exp(-x)*erf(x*I)
exp(-x)*erf(I*x)
```
The correct result can be found here: https://www.wolframalpha.com/input/?i=+exp%28x%29*erf%28I*x%29+

**Comment by oscarbenjamin** [comment]
There is nothing incorrect about this. You can use rewrite if you want the other form:
```
In [3]: exp(x)*erf(I*x)                                                                                                                        
Out[3]: 
 x         
ℯ ⋅erf(ⅈ⋅x)

In [4]: _.rewrite(erfi)                                                                                                                        
Out[4]: 
   x        
ⅈ⋅ℯ ⋅erfi(x)
```

**Comment by namannimmo10** [comment]
I thought it would give the integral representation. 
![MSP2532134h623i42ihieg600001388a2939104128b](https://user-images.githubusercontent.com/43007653/73429752-6515b980-4362-11ea-8d6f-d4c5f1857a08.gif)

**Comment by sylee957** [comment]
```
>>> from sympy import *
>>> x = Symbol('x')
>>> t = Symbol('t')
>>> expr = 2*I*exp(x)/sqrt(pi)*Integral(exp(t**2), (t, 0, x))
>>> expr
2*I*exp(x)*Integral(exp(t**2), (t, 0, x))/sqrt(pi)
>>> expr.doit()
I*exp(x)*erfi(x)
```
At least converting back from integrals work.

Integrals are often more complicated than original functions, so I don't think that functions should automatically evaluate to integrals (even if it gives more generalized form for special functions), than making integrals to automatically end up with special functions.

But I think that you should begin with adding `_eval_rewrite_as_Integral` if you want to add such features.
