### ISSUE TITLE
DimensionSystem arg handling inconsistency

### ISSUE THREAD

**Issue by oscarbenjamin** [sympy/sympy#18529]
@Upabjojr there is a problem in `DimensionSystem.__new__` that means it does not satisfy the `obj == obj.func(*obj.args)` invariant. Demo:
```python
from sympy.physics.units.dimensions import DimensionSystem
from sympy.physics.units.definitions.dimension_definitions import length, time, velocity
ds = DimensionSystem((length, time), (velocity,))
print(ds)
print(ds.func(*ds.args))
```
Output:
```
DimensionSystem((Dimension(length, L), Dimension(time, T)),
    (Dimension(velocity),), {length: {length: 1}, time: {time: 1}, Dimension(velocity): {velocity: 1}})
DimensionSystem((Dimension(length, L), Dimension(time, T)),
    (Dimension(velocity),), {length: {length: 1}, time: {time: 1}, velocity: {velocity: 1}})
```
(Note velocity rather than Dimension(velocity).)

_Originally posted by @oscarbenjamin in https://github.com/sympy/sympy/pull/18513#issuecomment-580946465_

**Comment by oscarbenjamin** [comment]
This is happening somewhere in `DimensionSystem.__new__`:
https://github.com/sympy/sympy/blob/74227f900b05009d4eed62e34a166228788a32ca/sympy/physics/units/dimensions.py#L331

I took a look but I can't really understand what the arg-handling there is supposed to do.

**Comment by Upabjojr** [comment]
> I took a look but I can't really understand what the arg-handling there is supposed to do.

That class was a bit of a mess. I made some refactoring and tried to keep compatibility with the previous version. It's time to simplify that class a bit.

**Comment by oscarbenjamin** [comment]
I actually have a fix for this now:
```diff
diff --git a/sympy/physics/units/dimensions.py b/sympy/physics/units/dimensions.py
index 8f1e532..8b52ac7 100644
--- a/sympy/physics/units/dimensions.py
+++ b/sympy/physics/units/dimensions.py
@@ -387,7 +387,7 @@ def parse_dict(d):
                 raise ValueError("Dimension %s both in base and derived" % dim)
             if dim.name not in dimensional_dependencies:
                 # TODO: should this raise a warning?
-                dimensional_dependencies[dim] = Dict({dim.name: 1})
+                dimensional_dependencies[dim.name] = Dict({dim.name: 1})
 
         base_dims.sort(key=default_sort_key)
         derived_dims.sort(key=default_sort_key)
```
That's already included in #18513. Does it look correct to you?

**Comment by Upabjojr** [comment]
> Does it look correct to you?

Yes, it does.

**Comment by Upabjojr** [comment]
Thanks for the fix, I'm a bit busy in this period.
