### ISSUE TITLE
BadRequestError

### ISSUE THREAD

**Issue by mohitacecode** [sympy/sympy#18536]
For
`M = Matrix(8, 8, [x+i for i in range (64)])`  `sympy live` gives this error

`BadRequestError: The value of property "globals" is longer than 1048487 bytes.`

I tried in my system it works fine but in `sympy live` it gives error.

**Comment by mohitacecode** [comment]
`M.rref()` also gives `Unable to process statement due to its excessive size.` error

**Comment by sb369** [comment]
i would like to take this issue

**Comment by oscarbenjamin** [comment]
This issue should be opened against the sympy live repo:
https://github.com/sympy/sympy-live

**Comment by mohitacecode** [comment]
Ok I am closing it here will open it against sympy live.

**Comment by mohitacecode** [comment]
@sb369 I have opened it against sympy-live repo you can refer to this link (https://github.com/sympy/sympy-live/issues/143)
