### ISSUE TITLE
TypeError: rref() got an unexpected keyword argument 'dotprodsimp'

### ISSUE THREAD

**Issue by mohitacecode** [sympy/sympy#18538]
`M.rref(dotprodsimp=True)` gives TypeError.
even though we have a test in test_matrices.py using this statement.

**Comment by oscarbenjamin** [comment]
You need to provide enough code to reproduce this. What is `M`?

**Comment by mohitacecode** [comment]
here M = Matrix(8, 8, [x+i for i in range (64)])

**Comment by oscarbenjamin** [comment]
It works fine for me on master:
```julia
In [1]: M = Matrix(8, 8, [x+i for i in range (64)])                                                                                            

In [2]: M.rref(dotprodsimp=True)                                                                                                               
Out[2]: 
⎛⎡1  0  -1  -2  -3  -4  -5  -6⎤        ⎞
⎜⎢                            ⎥        ⎟
⎜⎢0  1  2   3   4   5   6   7 ⎥        ⎟
⎜⎢                            ⎥        ⎟
⎜⎢0  0  0   0   0   0   0   0 ⎥        ⎟
⎜⎢                            ⎥        ⎟
⎜⎢0  0  0   0   0   0   0   0 ⎥        ⎟
⎜⎢                            ⎥, (0, 1)⎟
⎜⎢0  0  0   0   0   0   0   0 ⎥        ⎟
⎜⎢                            ⎥        ⎟
⎜⎢0  0  0   0   0   0   0   0 ⎥        ⎟
⎜⎢                            ⎥        ⎟
⎜⎢0  0  0   0   0   0   0   0 ⎥        ⎟
⎜⎢                            ⎥        ⎟
⎝⎣0  0  0   0   0   0   0   0 ⎦        ⎠
```

**Comment by mohitacecode** [comment]
It works on my master as well but I checked it on sympy live. Even now it shows the same error.

can I know why some things works on our local system but not on sympy live?

**Comment by gschintgen** [comment]
Sympy live uses 1.5 or 1.5.1, not an internal development version (aka master). The `dotprodsimp` feature is a rather recent addition that is not part of an official release build yet.

**Comment by mohitacecode** [comment]
Ok thanks :)

**Comment by oscarbenjamin** [comment]
> can I know why some things works on our local system but not on sympy live?

Firstly as @gschintgen says there can be a version difference. The other possibility is that it's a bug in sympy live in which case you should open an issue in the sympy-live repo (not here). You may find that there is already an open issue there.
