### ISSUE TITLE
no way to see transform function;  weird output from fourier_transform

### ISSUE THREAD

**Issue by vainaijr** [sympy/sympy#18549]
1) when I apply an IntegralTransform, like fourier transform, then it does not show the function, it give me something like this,
![Screenshot (478)](https://user-images.githubusercontent.com/43755000/73609104-aaa9df00-460d-11ea-827c-75de3776fae2.png)

how do I see the transform function being applied?

2) fourier transform, inverse fourier transform gives weird output, when changing simplify
![Screenshot (476)](https://user-images.githubusercontent.com/43755000/73609076-6e767e80-460d-11ea-9b2d-8150cdd3d8b9.png)

**Comment by sylee957** [comment]
What do you mean by transform function? Do you mean that they should be represented as formal integral symbol with `exp(-I*w*t)`?

**Comment by vainaijr** [comment]
Yes, for Laplace, Mellin transforms also.

**Comment by sylee957** [comment]
But I think that you can rewrite things to integral by .rewrite(Integral) if you want to see how the notation looks like.

I don’t think that there is any problem of representing things like done before

**Comment by vainaijr** [comment]
oh, I did not know that, then it is fine.

**Comment by oscarbenjamin** [comment]
There does seem to be a printing bug maybe: "undefined control sequence operatorname"

**Comment by sylee957** [comment]
I get different outputs and the printing works fine

![image](https://user-images.githubusercontent.com/34944973/73614904-f2009180-4646-11ea-9708-30bd2335730e.png)

what's your sympy version?

**Comment by vainaijr** [comment]
oh, I use colab, it uses sympy version 1.1.1, that would be the reason.
