### ISSUE TITLE
Follow PEP8 guidelines in sympy.crpyto

### ISSUE THREAD

**Issue by r0cketr1kky** [sympy/sympy#18556]
Follow PEP8 guidelines for the crypto.py file in sympy.crypto

**Comment by oscarbenjamin** [comment]
I don't think we need an issue for this.

**Comment by sylee957** [comment]
Generally, I’d open up a separate PR for pep8 issue, because if you had not made columnar transposition cipher up to the expected quality, it can block merging the PR entirely.

**Comment by r0cketr1kky** [comment]
Okay, should I raise another issue regarding the Pep8 guidelines?

**Comment by oscarbenjamin** [comment]
> Okay, should I raise another issue regarding the Pep8 guidelines?

This has been discussed before and I don't think that using pep8 everywhere is considered a good idea. Look for existing issues before opening new ones
