### ISSUE TITLE
Solving performance issue

### ISSUE THREAD

**Issue by yarnaid** [sympy/sympy#18586]
I have performance issues with following expressions.
~~~python3
f = cos(x)/sin(x)**Rational(7,4)
integrate(f, x)
~~~
Takes 107 seconds. But if substitute `a` instead of power and after replace `a` with 7/4, it's much faster -- 1.5 sec.

~~~python3
f = cos(x)/sin(x)**y
integrate(f,x).subs(y, Rational(7,4))
~~~

Also
~~~python3
f = (3*x + 1)/sqrt(y*x**2+2)
limit(f, x, -oo)
~~~
Is endless.
Maybe it can be optimized somehow?

**Comment by oscarbenjamin** [comment]
Some integrals are slow because the Risch algorithm is unpredictable. I assume that's the problem there.

For the limit I don't know but I guess the result depends on assumptions on y. Have you tried with e.g. `y = Symbol('y', positive=True)`?

**Comment by Jonty16117** [comment]
> Some integrals are slow because the Risch algorithm is unpredictable. I assume that's the problem there.
> 
> For the limit I don't know but I guess the result depends on assumptions on y. Have you tried with e.g. `y = Symbol('y', positive=True)`?

with positive y, it gives the result as:
-3/(sqrt(y))

**Comment by sachin-4099** [comment]
Currently on master, the `limit` evaluates instantly:
```
In [1]: f = (3*x + 1)/sqrt(y*x**2+2)

In [2]: %time limit(f, x, -oo)
Wall time: 31.2 ms
Out[2]:
 -3
-----
  ___
\/ y
```

**Comment by oscargus** [comment]
(Exactly) the same issue as in #18511. Closing this as it is newer.
