### ISSUE TITLE
Incosistent result in Order

### ISSUE THREAD

**Issue by iamabhishek0** [sympy/sympy#18606]
```
>>> from sympy import *
>>> Order(1)
O(1)
>>> Order(2)
O(1)
>>> Order(0)
0

```

**Comment by oscarbenjamin** [comment]
That does not seem inconsistent to me. From the definition here:
https://en.wikipedia.org/wiki/Big_O_notation#Formal_definition
we have
'''
if and only if for all sufficiently large values of x, the absolute value of f(x) is at most a positive
constant multiple of g(x)
'''
Here if g(x) is 0 then f(x) must be zero.

**Comment by iamabhishek0** [comment]
@oscarbenjamin I agree with you but
```>>> type(Order(1))
<class 'sympy.series.order.Order'>
>>> type(Order(0))
<class 'sympy.core.numbers.Zero'>
```
`Order(0)` doesn't return Order type object .In #13715 AttributeError is raised because of this.

**Comment by jksuom** [comment]
I also think that an `Order(0)` object of Order type would be useful and simplify coding. Making it Zero has one advantage though: it will automatically disappear from sums, but that could probably be easily arranged in `Add.flatten()` even if it were an Order instance.

**Comment by iamabhishek0** [comment]
@jksuom @oscarbenjamin What do you suggest? Should I go ahead and make the changes?

**Comment by jksuom** [comment]
> Should I go ahead and make the changes?

I think that it is worth a try.
