### ISSUE TITLE
Incorrect density, cdf calculation in DiscreteUniform

### ISSUE THREAD

**Issue by Smit-create** [sympy/sympy#18611]
```
>>> from sympy.stats import density, DiscreteUniform, cdf
>>> X = DiscreteUniform('X', [1, 1, 1, 2, 2])
>>> dict(density(X).items())
{1: 1/5, 2: 1/5}
>>> cdf(X)
{1: 1/5, 2: 2/5}
```
Issue is:
Considering that the arguments in the `DiscreteUniformDistribution`, it should be kept as finite set, and therefore should produce `density` as `{1: 1/2, 2: 1/2}`,
Also as `density` is wrongly evaluated, `cdf` produces wrong result, as it should attain value of `1` at some point in the domain of the distribution, which is not satisfied in the above result.

**Comment by czgdp1807** [comment]
> X = DiscreteUniform('X', [1, 1, 1, 2, 2])

Why would someone pass such args?
What does other CAS produce in similar conditions?

**Comment by Smit-create** [comment]
I have changed this because from [this comment](https://github.com/sympy/sympy/issues/10104#issuecomment-154070977), it was necessary to check that repeated arguments are not passed otherwise density and cdf are produced wrongly.
