### ISSUE TITLE
diophantine(), diop_quadratic() missing solutions

### ISSUE THREAD

**Issue by kgorlen** [sympy/sympy#18628]
With sympy version 1.5.1:

```
from sympy import *
from sympy.solvers.diophantine import diop_quadratic

a, b, x, y = symbols('a b x y', integer=True, positive=True)
f = -a*x + x**2 - b*y + y**2
g = f.subs([(a, 15), (b, 8)])
print('diophantine   (', g, ') solutions:', diophantine(g))
print('diop_quadratic(', g, ') solutions:', diop_quadratic(g))
h = f.subs([(a, 8), (b, 15)])
print('diophantine   (', h, ') solutions:', diophantine(h))
print('diop_quadratic(', h, ') solutions:', diop_quadratic(h))
print(g.subs([(x, 16), (y, 4)]))

```
Output:

```
diophantine   ( x**2 - 15*x + y**2 - 8*y ) solutions: {(15, 8)}
diop_quadratic( x**2 - 15*x + y**2 - 8*y ) solutions: {(15, 0), (0, 8), (15, 8), (0, 0)}
diophantine   ( x**2 - 8*x + y**2 - 15*y ) solutions: {(8, 15), (4, 16)}
diop_quadratic( x**2 - 8*x + y**2 - 15*y ) solutions: {(0, 0), (0, 15), (8, 0), (4, 16), (4, -1), (8, 15)}
0

```
First, I expect diophantine() to return the same solutions as diop_quadratic(), but it doesn't.

Second, the function f() is symmetric in x and y, so the solutions to g() and h() should be symmetric, but they aren't.  For example, (16, 4) is a solution to g(), but is missing from the solution set.

**Comment by ethankward** [comment]
`diophantine` is doing additional filtering on the results to match the assumptions on `x` and `y` as positive integers. `diop_quadratic` has no such checks.

**Comment by kgorlen** [comment]
I see, thanks.  Zero isn't considered positive, so I should have:

`a, b, x, y = symbols('a b x y', integer=True, negative=False)
`

Then the output is:

```
diophantine   ( x**2 - 15*x + y**2 - 8*y ) solutions: {(15, 0), (0, 8), (15, 8), (0, 0)}
diop_quadratic( x**2 - 15*x + y**2 - 8*y ) solutions: {(15, 0), (0, 8), (15, 8), (0, 0)}
diophantine   ( x**2 - 8*x + y**2 - 15*y ) solutions: {(0, 0), (0, 15), (8, 0), (4, 16), (8, 15)}
diop_quadratic( x**2 - 8*x + y**2 - 15*y ) solutions: {(0, 0), (0, 15), (8, 0), (4, 16), (4, -1), (8, 15)}
0

```
So the issue is with diop_quadratic(g), which is missing the solution (16, 4).

**Comment by kgorlen** [comment]
I've investigated this further.  The problem appears to actually be in `transformation_to_DN` and `find_DN`:

```
from sympy import *
from sympy.solvers.diophantine import transformation_to_DN, find_DN, diop_DN

d, e, x, y = symbols('d e x y', integer=True)

f = x**2 + y**2 + d*x + e*y         
g = f.subs([(d, -15), (e, -8)])
h = f.subs([(d, -8), (e, -15)])

print(f'transformation_to_DN({g}) =')
A, B = transformation_to_DN(g)
print('A:', A)
print('B:', B)
D, N = find_DN(g)
print(f'find_DN({g}) = {D}, {N}')
print(f'diop_DN({D}, {N}) = {diop_DN(D, N)}')
print('')

print(f'transformation_to_DN({h}) =')
A, B = transformation_to_DN(h)
print('A:', A)
print('B:', B)
D, N = find_DN(h)
print(f'find_DN({h}) = {D}, {N}')
print(f'diop_DN({D}, {N}) = {diop_DN(D, N)}')
```

Output:

```
transformation_to_DN(x**2 - 15*x + y**2 - 8*y) =
A: Matrix([[-1/2, 0], [0, -1]])
B: Matrix([[15/2], [4]])
find_DN(x**2 - 15*x + y**2 - 8*y) = -4, 289
diop_DN(-4, 289) = [(15, 4)]

transformation_to_DN(x**2 - 8*x + y**2 - 15*y) =
A: Matrix([[-1/4, 0], [0, -1/2]])
B: Matrix([[4], [15/2]])
find_DN(x**2 - 8*x + y**2 - 15*y) = -4, 1156
diop_DN(-4, 1156) = [(16, 15), (30, 8), (0, 17)]

```
My math isn't strong, but shouldn't `transformation_to_DN(x**2 - 15*x + y**2 - 8*y)` return:

`A: Matrix([[-1/2, 0], [0, -1/4]])
`

and `find_DN(x**2 - 15*x + y**2 - 8*y)` also return `-4, 1156`?

I don't understand the method used by these functions, and the link to the paper _Solving the equation ax^2 + bxy + cy^2 + dx + ey + f = 0, John P.Robertson, May 8, 2003_  ([http://www.jpr2718.org/ax2p.pdf](url)) is broken.

**Comment by jksuom** [comment]
The transformation is not unique. It seems that the one defined by `Matrix([[-1/2, 0], [0, -1]])` would also be valid. However, `diop_DN(-4, 289)` does not return the non-primitive solution `(17, 0)` of `x**2 + 4*y**2 = 289`because `cornacchia` does not find the trivial solution `(1, 0)` of the equation `x**2 + 4*y**2 = 1`:
```
>>> from sympy.solvers.diophantine.diophantine import cornacchia
>>> cornacchia(1, 4, 1)
set()
```
That looks like a bug in `cornacchia`.

**Comment by kgorlen** [comment]
From [http://www.numbertheory.org/php/cornacchia.html](url), it appears that `cornacchia` isn't applicable because a + b > m.
