### ISSUE TITLE
Feature Request: Make euler_equations more gracious

### ISSUE THREAD

**Issue by cweickhmann** [sympy/sympy#18653]
Consider this: I have two expressions. Under some conditions one becomes constant or zero.
I want to get the Euler-Lagrange equation of both expressions. Unfortunately, the evaluation of the one that is constant/zero fails with a `ValueError`.

Mathematically, I would expect to simply get an empty list of equations or the Lagrangian just evaluate to zero, which would be fine.

Hence my request: Make `euler_equations` come back with e.g. an empty list instead of throwing a `ValueError` if it evaluates a constant.

**Consider this MWE**:
```python
import sympy as sp
x, y, z = sp.symbols("x y z")
f, g, h = sp.symbols("f g h", cls=sp.Function, args=(x,y))
f, g, h = f(), g(), h()
expr1 = f.diff(x)*g.diff(y) # <-- function of x, y
expr2 = f.diff(x)*h.diff(z) # <-- not a function of x or y anymore.

sp.euler_equations(expr1, (f,), (x,y)) # <-- this works, because expr1 is still a function of f(x,y)

sp.euler_equations(expr2, (f,), (x,y)) # <-- this fails.
```

Error message
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-12-f86f0a617a44> in <module>
----> 1 sp.euler_equations(expr2, (f,), (x,y))

/usr/local/lib/python3.6/dist-packages/sympy/calculus/euler.py in euler_equations(L, funcs, vars)
     90             raise ValueError("Variables %s don't match args: %s" % (vars, f))
     91 
---> 92     order = max(len(d.variables) for d in L.atoms(Derivative)
     93                 if d.expr in funcs)
     94 

ValueError: max() arg is an empty sequence
```

**Comment by matta-varun** [comment]
I would like to work on this. Can you guide me how to start on this since this is the first issue that I am taking up. Thanks.

**Comment by cweickhmann** [comment]
Quite honestly, I am the wrong person to ask, I'm barely a user of sympy. ;-)

**Comment by matta-varun** [comment]
Oh then fine. This feels like a good issue to start on. I request anyone who can guide me on this to kindly do so. Thanks in advance.

**Comment by MaqOwais** [comment]
Above equation is zero since differentiation of h(x,y) with respect to z will be zero...

And also there should be a check for L = 0 since it happens a lot that L will be zero most of the times

**Comment by czgdp1807** [comment]
I have created a PR https://github.com/sympy/sympy/pull/20760 which gives the following results on your code,
```python
[Eq(-Derivative(g(x, y), x, y), 0)]
[True]
```
The second one is getting evaluated. We can keep it un-evaluated. Let me know which one is better.

**Comment by cweickhmann** [comment]
Hey, thanks for taking this on!
I think it is fine if it is getting evaluated as long as it does not throw a ValueError anymore and I feel returning an empty list is what you would expect from math courses. So, leave it like you proposed.

Anyone else with opinions on this?

**Comment by oscarbenjamin** [comment]
It would be better to give an empty list.

**Comment by czgdp1807** [comment]
I have made the change for returning empty list. See, https://github.com/sympy/sympy/pull/20760

**Comment by czgdp1807** [comment]
The issue isn't fixed yet. Re-opening.
