### ISSUE TITLE
Feature Request: Sequences - chaining and interlacing

### ISSUE THREAD

**Issue by sr-murthy** [sympy/sympy#18661]
Would it be possible to contribute some functionality that implements the chaining and interlacing of multiple sequences? I don't see any way of doing this currently directly via the package. Chaining might be useful with respect to finite sequences: given two sequences `S` and `T`, of lengths `m` and `n` respectively, the chain of `S` and `T` will be a chain of length `m + n` with the first `m` elements being the sequence of `S` and the last `n` elements the sequence of `T`.

By interlacing I mean constructing a new sequence from two sequences by taking pairs of elements, one from each sequence, at a time.

**Comment by sylee957** [comment]
Yes, sequence module looks like lacking some features.

**Comment by sr-murthy** [comment]
I'd like to work on this, starting with chaining of finite sequences.

**Comment by sr-murthy** [comment]
For clarification, consider the example of two sequences given `S = sequence(n**2, (n, 0, 10))` and `T = sequence(n**3, (n, 0, 10))`.

*  for chaining these two it would be nice to do something like
```
   >>> from sympy.series.sequences import chain
    >>> C = chain(S, T, (n, 0, 10))
    >>> SeqFormula((n**2; n**3), (n, 0, 10))
    >>> list(C)
    >>> [0, 1, 4, 9, 16, 25, 36, 49, 64, 81, 100, 0, 1, 8, 27, 64, 125, 216, 343, 512, 729, 1000]
```

* by interlacing I mean something like
```
    >>> from sympy.series.sequences import interlace
    >>> ilace = interlace(S, T, (n, 0, 10))
    >>> ilace
    >>> SeqFormula((n**2, n**3), (n, 0, 10))
    >>> list(ilace)
    >>> [0, 0, 1, 1, 4, 8, 9, 27, 16, 64, 25, 125, 36, 216, 49, 343, 64, 512, 81, 729, 100, 1000]

**Comment by sylee957** [comment]
I wonder how you are going to find a merged sequence formula, like merging `2n` and `2n+1` to `n`.

**Comment by sr-murthy** [comment]
I did think about this - chaining (finite) sequences is like concatenating two strings, and I'm not sure you can have a simple rational expression as the generating function for the chained sequence. For your example of sequences `{2n}` and `{2n + 1}`, say, each defined on the ordered set `{1,...,10}`, the chained sequence (of length `20`) it could be described by a piecewise function `P = P(n, i)`, where  `n` runs over `{1,..,10}` as normal and and `i` runs over `{1,..,20}`, such that 

    P(n, i) = 2n, 1 <= i <= 10
    P(n, i) = 2n + 1, 11 <= i <= 20

**Comment by sylee957** [comment]
On the other hand, I don't think that you should extend `SeqFormula` to accept much more complicated logic, but adding new symbolic classes like `SeqChain` or `SeqInterlace` would be better.

For example, I see your example is already reserved to give a sequence of tuples
```python3
n = Symbol('n')
SeqFormula((n**2, n**3), (n, 0, 10))
```

**Comment by sr-murthy** [comment]
Yes I think you would need to have new types of sequence classes for chain and interlace.

BTW the tuple notation was actually for the interlacing example, but obviously the tuples would have to be unpacked, so 1, 1, 4, 8, 9, 27, ... rather than (1, 1), (4, 8), (9, 27), ... etc.

**Comment by sr-murthy** [comment]
Chaining is obviously only sensible for finite sequences, but interlacing would work for infinite sequences. Interlacing would also work for sequences of different lengths - as with the `itertools.izip` method in Python 3 you can zip two iterables of different lengths

    zip_longest('ABCD, 'xy', fillvalue='') --> Ax By C D

**Comment by sylee957** [comment]
I'd expect `SeqFormula` to be agnostic about iterables. 
For example, there can be some particular interest of creating a sequence of non scalar types like vectors or matrices, and finding a interpolation or summation formula as a whole.

**Comment by sr-murthy** [comment]
Yes, I think sequences should be treated generically in this context.

**Comment by sr-murthy** [comment]
I'm going to leave this as a feature request - note, I've updated the title.

**Comment by Saanidhyavats** [comment]
I am contributing on this. I have a doubt whether the number of elements of both sequence should be same for finding the interlace as we are forming a a pair by taking individual elements from both the sequences.

**Comment by sr-murthy** [comment]
Interlace should work in a similar way to Python `itertools.zip_longest` (https://github.com/sympy/sympy/issues/18661#issuecomment-586676361). The sequences don't have to be of the same length - you keep taking pairs of elements, one from each sequence, until we run out of elements in one or both sequences.  If `S` and `T` are the following sequences

    S = (a, b, ..., z)
    T = (1, 2, ..., 10)

then the interlace of `S` and `T` should be a sequence of length `|S| + |T| = 26 + 10 = 36` and be generated as the single sequence

    a, 1, b, 2, ..., j, 10, k, l, ..., z

The 10th element of `S` is  `j` and for `T` it's `10`, which is also the last element of `T`, but then the interlacing should continue to generate `S` - elements of `T` with index > 10 should be considered nulls and should be ignored. This should be equivalent to the following in Python

    >>> for x in (x for x in itertools.chain(*itertools.zip_longest('abcdefghijklmnopqrstuvwxyz', range(1, 11))) if x):
    ...     print(x)
    a
    1
    b
    2
    j
    10
    k
    l
    m
    ...
    z

**Comment by sr-murthy** [comment]
Interlacing is easy enough in Python - it's just a composition of `zip` with `itertools.chain`.
You don't have to worry about generating functions unlike Sympy.

    def interlace(*seqs):
    """
    Generates the sequence obtained by interlacing a sequence of sequences
    (of the same length), e.g.
    ::
        (1, 2, 3), (4, 5, 6), (7, 8, 9) -> 1, 4, 7, 2, 5, 8, 3, 6, 9

    The arguments can be separate sequences (generators, lists, tuples) or
    an unpacked iterable of such sequences (use * to unpack an iterable
    argument), e.g.
    ::
        digits(123), digits(456), digits(789) -> 1, 4, 7, 2, 5, 8, 3, 6, 9
        digits(123), [4, 5, 6], (7, 8, 9)     -> 1, 4, 7, 2, 5, 8, 3, 6, 9
        *[digits(123), [4, 5, 6], (7, 8, 9)]  -> 1, 4, 7, 2, 5, 8, 3, 6, 9
    """
    for e in itertools.chain(*zip(*seqs)):
        yield e

**Comment by sr-murthy** [comment]
Interlacing isn't restricted to two sequences - you can obviously interlace multiple sequences, but perhaps you may want to work on two sequences to start with.

**Comment by oscarbenjamin** [comment]
Before deciding how to handle things like interlacing I think it would be good to focus on use cases. What symbolic operations do chaining or interlacing allow? Where in the rest of sympy would we want to use these features and for what?

**Comment by sr-murthy** [comment]
I'm not sure about any specific symbolic operations supported by chaining and interlacing - I was thinking about the applications though, of which there are plenty. As with (pointwise) addition of sequences chaining and interlacing (and deinterlacing) are natural operations to think about when working with finite sequences.

**Comment by oscarbenjamin** [comment]
With finite sequences we can just do everything in Python with lists. I don't see why we would want symbolic classes for this if we can't think of any application for them.

**Comment by sylee957** [comment]
I had thought of stuff like #18489 if it means interlacing in symbolic way.

**Comment by oscarbenjamin** [comment]
If those were sequences rather than sets then I guess it's possible that interlacing could be simplified. You would need to know which order to interlace the sequences in though or the result would not be able to simplify.

**Comment by sr-murthy** [comment]
In either interlacing or chaining the order of generation would be determined by the order of the input sequences, so interlacing sequences S and T would produce a different sequence to interlacing T and S.

In my view the utility of adding this support is to extend the set of operations you can currently perform on sequences, and there are plenty of concrete physical applications, but which don't necessarily have a symbolic description.

**Comment by oscarbenjamin** [comment]
I think a clearer rationale is needed. For example above you say that interlacing sequences of different lengths should truncate the longer sequence but why should that happen? Without even a hypothetical use case there is no way to answer that question.

Extending the set of operations is not a motivation in itself because having more operations can only be an improvement if the operations are useful. The applications you mention (DNA sequencing and signal analysis) seem non-symbolic and are probably better handled by other libraries already.

**Comment by sr-murthy** [comment]
Fine, I'm closing. I don't think sympy is the right library for sequences - it seems rather restricted.

**Comment by oscarbenjamin** [comment]
I'm not saying that this can't be included. I just think that there needs to be some target for what you could do with it.

The situation right now in sympy is that the sequences module is hardly used anywhere. I can only see two other modules in sympy that use it: fourier.py and formal.py. Neither of them uses any finite sequences as far as I can tell.
