### ISSUE TITLE
Move matrix tests out of matrices.py and common.py

### ISSUE THREAD

**Issue by sylee957** [sympy/sympy#18666]
I guess @Pristine-Cat had not finished the work for the part.
So I'd open up this issue to be grabbed up by more wider audiences.

I'd expect you to create each files below and migrate the tests from `test_matrices.py` and `test_common.py`. For example, you should migrate all the determinant-related tests to `test_determinant.py`.

- [x] `test_determinant.py`
- [x] `test_decompositions.py`
- [x] `test_eigen.py`
- [x] `test_reductions.py`
- [x] `test_subspaces.py`
- [x] `test_solvers.py`

**Comment by mohitacecode** [comment]
Ok I am working and will make a pr soon

**Comment by mohitacecode** [comment]
All the tests which are added for issues should also be moved?
I am assuming that I have to move them to.

**Comment by mohitacecode** [comment]
I also want to know that if some test is using determinant but the aim of test is to test something else.
should we also add that test?

**Comment by sylee957** [comment]
If you find something ambiguous, it’s fine to keep them in matrices.py for a while

**Comment by mohitacecode** [comment]
> All the tests which are added for `issues` should also be moved?
 what about these?

**Comment by mohitacecode** [comment]
Can I first make a pr for only  `test_determinant.py`?

**Comment by sylee957** [comment]
I’d try to move most of the test_issue stuff, only except for the ones named like expression_blowup

**Comment by sylee957** [comment]
Yes, and I’d recommend doing it one by one

**Comment by mohitacecode** [comment]
Okay I will make a pr for `test_determinant.py` now.

**Comment by sksingh1202** [comment]
I guess work has been done only in creating test_determinant.py .I'd like to work on this issue too.

**Comment by sylee957** [comment]
Yes, you can work on creating other files not taken up, if possible.

**Comment by mohitacecode** [comment]
>Yes, you can work on creating other files not taken up, if possible.

IMO,there can be conflict if some test function which has been already moved to some file will get again moved to another file.
so it will be better if one pr is complete then only to start another.

**Comment by mohitacecode** [comment]
since we are done with `test_determinant.py` I will start doing changes for `test_decompositions.py`  and will submit a pr very soon.

**Comment by sksingh1202** [comment]
I have started doing work on test_solvers.py and would be submitting a pr very soon.

**Comment by sksingh1202** [comment]
I have made a pr for test_solvers.py.

**Comment by sksingh1202** [comment]
@sylee957 , as there is already a file with the name test_solvers.py in sympy/solvers/tests/test_solvers.py, is it fine for the file with solver-related test cases to be named with the same name or should I change it to something like test_matixsolvers.py?

**Comment by sylee957** [comment]
Technically, there is no problem of having the duplicate filename in the test suite, as well as there is no problem of having the duplicate filename in the python.

I’d rather not touch about the naming consistency of prefixing ‘test_’.

**Comment by sksingh1202** [comment]
Thank you very much for your help.

**Comment by smitgajjar** [comment]
@sylee957 I have started migrating test cases for subspaces to test_subspaces.py. I would submit a PR soon!

**Comment by smitgajjar** [comment]
Please review the changes made in the PR.

**Comment by guptabhaskar** [comment]
Please review the changes made in PR.

**Comment by guptabhaskar** [comment]
Please review the changes made in the new PR.

**Comment by sylee957** [comment]
Okay, I see the work is roughly done, but I still see that some more subtle works are needed to move the tests like 
https://github.com/sympy/sympy/blob/a1fbd0066219a7a1d14d4d9024d8aeeb5cb8d51a/sympy/matrices/tests/test_matrices.py#L3021

**Comment by Arpan612** [comment]
@sylee957 Can I work on the work left in test_matrices.py?

**Comment by mohitacecode** [comment]
the files mentioned in the issues are already created you have to identify the test in test_matrices.py and test_commonmatrix.py and move them to their related test file. for example all the solvers related test should be transferred to test_solvers.py.

**Comment by Arpan612** [comment]
@mohitacecode Is the function code on from the line 3021 to be sent to test_commonmatrix.py?

**Comment by mohitacecode** [comment]
I think `test_reductions.py` should be the file.(but still I am not sure).
You move the test you think should be moved and open a pr it will be easy to review all at once.

just for future reference : My humble opinion will not to delete comments from gitter,pr or any issue It will other person refering your comments invalid.

**Comment by Arpan612** [comment]
Thanks a lot.

**Comment by Arpan612** [comment]
@sylee957 Please review my PR.

**Comment by Arpan612** [comment]
> Okay, I see the work is roughly done, but I still see that some more subtle works are needed to move the tests like
> https://github.com/sympy/sympy/blob/a1fbd0066219a7a1d14d4d9024d8aeeb5cb8d51a/sympy/matrices/tests/test_matrices.py#L3021

Sir, you said that these functions needed to be moved, that's why I sent that PR. Could you tell me which parts of the code need to be moved?

**Comment by sylee957** [comment]
Well, I have only pointed to 17827 test, but not the ones below.
I think that only these can move to `test_reductions`
https://github.com/sympy/sympy/blob/a1fbd0066219a7a1d14d4d9024d8aeeb5cb8d51a/sympy/matrices/tests/test_matrices.py#L2618-L2655
https://github.com/sympy/sympy/blob/a1fbd0066219a7a1d14d4d9024d8aeeb5cb8d51a/sympy/matrices/tests/test_matrices.py#L3000-L3005

**Comment by Arpan612** [comment]
@sylee957 Could you please highlight what work is left here?

**Comment by Saanidhyavats** [comment]
@sylee957 let me know if some work is left otherwise this issue can be closed.

**Comment by Sohaib03** [comment]
Is this issue open?

**Comment by sylee957** [comment]
I think that every issues were resolved
