### ISSUE TITLE
Implement gaussian prime

### ISSUE THREAD

**Issue by sylee957** [sympy/sympy#18660]
I see there are lots of ntheory stuff for gaussian integers, like finding gaussian prime
```python3
from sympy.ntheory.primetest import isprime
from sympy.core.compatibility import as_int

def is_gaussian_prime(a, b):
    """Test if a + b*I is a Gaussian prime number.
    
    References
    ==========
    
    .. [1] https://oeis.org/wiki/Gaussian_primes
    """
    a = as_int(a)
    b = as_int(b)
    if a == 0:
        b = abs(b)
        return isprime(b) and b % 4 == 3
    elif b == 0:
        a = abs(a)
        return isprime(a) and a % 4 == 3
    return isprime(a**2 + b**2) 

is_gaussian_prime(2, 5)
```

Similarly, I see that gaussian integers can have euclidean division, gcd, every stuff
Though it can be more complicated because the division may not be unique. 
But I wonder if any computational method can be able to generalize such finds.

At least using `ZZ[I]` seems like giving a wrong result for computing modulus.
```
from sympy import *

p = ZZ[I](3 + 2*I)
q = ZZ[I](-1 + 3*I)
p % q
```

**Comment by abhinav28071999** [comment]
I am taking this.

**Comment by 2019202009ankush** [comment]
@sylee957 I want to work on this

**Comment by abhinav28071999** [comment]
I am working on this, and will submit a pr by tomorrow.
