### ISSUE TITLE
rewrite log(12)/log(2) as 2 + log(3)/log(2)

### ISSUE THREAD

**Issue by smichr** [sympy/sympy#18674]
I am not sure how to rewrite the quotient of logs to remove powers of the denominator's factors. I thought it could be recognized in `logcombine` but that function already does this
```python
>>> logcombine(log(12)/log(2))
log(12**(1/log(2)))
```
So maybe this is something that should be done by `expand_log` with a keyword `factor` is used to factor arguments before running.
```
>>> (log(12)/log(2)).replace(
...    lambda x: x.func is log and x.args[0].is_Integer, 
...    lambda x: log(factorint(x.args[0], visual=True)))
log(2**2*3**1)/log(2**1)
>>> expand_log(_)
(log(3) + 2*log(2))/log(2)
>>> expand(_)
log(3)/log(2) + 2
```
Not sure...seems like there should be an easy way to expand logs of integers.

**Comment by asmeurer** [comment]
I think logcombine is too aggressive with the power rule. I've noticed in other places that it can mess up other potential simplifications. Perhaps a good start here would be to have flags in logcombine() to selectively disable the two types of combination rules it does. But more generally, it should try to do it last, so that other types of combinations can be done first.

**Comment by kushagra219** [comment]
We can maybe write a new function, if that sees two log functions are being divided. Then it treats the denominator value as the base of numerator log function
Suppose in this case, if we can make
`log(12)/log(2) = log(12, 2)`
then we can easily reach
` log(3)/log(2) + 2`

**Comment by sankalp24** [comment]
Hello, Is this issue still open? I would like to contribute to this issue. I have been well versed with the codebase of sympy and have sufficient proficiency over python language. I also have a basic idea on how to move forward with this issue. Can I work on this issue?

**Comment by asmeurer** [comment]
SymPy cannot represent two-argument logs yet. log(x, y) is automatically rewritten as log(x)/log(y). I'm having a hard time finding the issue for this.

**Comment by asmeurer** [comment]
https://github.com/sympy/sympy/issues/6888

**Comment by sankalp24** [comment]
We can check the number in the numerator and reduce it to the product of its prime factors. 
For instance log(12) could be written as log( 2*2*3) and then pass this numerator to logcombine() to check if it is further simplified.
So here the numerator becomes log(2) + log(2) + log(3) = 2*log(2) + log(3).

**Comment by smichr** [comment]
> reduce it to the product of its prime factors

yes...see OP example using `replace`
