### ISSUE TITLE
Nested floor and ceiling don't fully evaluate

### ISSUE THREAD

**Issue by ethankward** [sympy/sympy#18689]
```
>>> floor(floor(x) + 1) + x
x + floor(floor(x)) + 1
>>> x + floor(floor(x)) + 1
x + floor(x) + 1
```

Same idea with `ceiling`.

**Comment by asmeurer** [comment]
For me `floor(floor(x))` does evaluate. The problem is the logic for stipping off 1 happens after that.

**Comment by shubham-khantwal** [comment]
it seems it is #18689 is logically correct. it's not an issue.
