### ISSUE TITLE
FallingFactorial rewrite to gamma error

### ISSUE THREAD

**Issue by smichr** [sympy/sympy#18686]
@rwst wrote in #8492:
_____
The gamma rewrite of ff is wrong IMHO:
```python
In [75]: ff(x,y)
Out[75]: FallingFactorial(x, y)

In [76]: _.rewrite('gamma')
Out[76]: 
    y          
(-1) ⋅Γ(-x + y)
───────────────
     Γ(-x)     

In [77]: gamma(-5)
Out[77]: zoo

In [78]: ff(5,y)
Out[78]: FallingFactorial(5, y)

In [79]: _.rewrite('gamma')
Out[79]: 0
```
_____
It seems like it should be
```python
>>> (factorial(x)/factorial(x-y)).rewrite(gamma)
gamma(x + 1)/gamma(x - y + 1)
```

**Comment by smichr** [comment]
Hmmm. The conditions on x and y are complicated so the rewrite to gamma cannot be so simple. Here is a tested Piecewise for `ff` (and `rf(x, y)` can be expressed as `ff(x + y - 1, y))` so I don't duplicate the effort for that:
```
>>> pprint(f(x, y))
⎧⎧         x!
⎪⎪      ────────        for x ≥ 0
⎪⎪      (x - y)!
⎪⎪
⎪⎪    -y
⎪⎨(-1)  ⋅(-x + y - 1)!                 for y < 0
⎪⎪────────────────────  for x < y
⎪⎪     (-x - 1)!
⎪⎪
⎪⎪        zoo           otherwise
⎪⎩
⎪
⎪               1                      for y = 0
⎨
⎪               x                      for y = 1
⎪
⎪               0                  for x > 0 ∧ x < y
⎪
⎪⎧    y
⎪⎪(-1) ⋅(-x + y - 1)!
⎪⎪───────────────────  for x < 0
⎪⎪     (-x - 1)!
⎪⎨                                     otherwise
⎪⎪        x!
⎪⎪     ────────        otherwise
⎪⎪     (x - y)!
⎩⎩
```
When folded it looks like this:
```
⎧         x!
⎪      ────────        for x ≥ 0 ∧ y < 0
⎪      (x - y)!
⎪
⎪    -y
⎪(-1)  ⋅(-x + y - 1)!
⎪────────────────────  for x < y ∧ y < 0
⎪     (-x - 1)!
⎪
⎪        zoo               for y < 0
⎪
⎪         1                for y = 0
⎨
⎪         x                for y = 1
⎪
⎪         0            for x > 0 ∧ x < y
⎪
⎪    y
⎪(-1) ⋅(-x + y - 1)!
⎪───────────────────       for x < 0
⎪     (-x - 1)!
⎪
⎪         x!
⎪      ────────            otherwise
⎩      (x - y)!
```
The code for it is:
```python
f = lambda x, y: Piecewise(
(Piecewise(
    (factorial(x)/factorial(x-y), Ge(x, 0)),
    ((-1)**-y*factorial(y-x-1)/factorial(-x - 1), Lt(x, y)),
    (zoo,True)),
Lt(y,0)),
(1,
Eq(y, 0)),
(x,
Eq(y, 1)),
(0,
And(Gt(x, 0), Lt(x, y))),
(Piecewise(
    ((-1)**y*factorial(y - x - 1)/factorial(-x - 1), Lt(x, 0)),
    (factorial(x)/factorial(x-y), True)),
True))
```
And the code was tested with the following:
```python
for i in range(-5,5):
 for j in range(-5,5):
  assert ff(i,j)==f(i,j),(ff(i,j),f(i,j),i,j)

for i in range(1000):
   i,j=[randint(-30,30) for do in range(2)]
   assert ff(i,j)==f(i,j),(ff(i,j),f(i,j),i,j)
```

**Comment by smichr** [comment]
On second thought...I don't see the problem. The gamma rewrite gives the right value when the 5 is substituted. So I am closing this issue.

**Comment by sachin-4099** [comment]
> Hmmm. The conditions on x and y are complicated so the rewrite to gamma cannot be so simple. Here is a tested Piecewise for `ff` (and `rf(x, y)` can be expressed as `ff(x + y - 1, y)` so I don't duplicate the effort for that:
> 
> ```
> >>> pprint(f(x, y))
> ⎧⎧         x!
> ⎪⎪      ────────        for x ≥ 0
> ⎪⎪      (x - y)!
> ⎪⎪
> ⎪⎪    -y
> ⎪⎨(-1)  ⋅(-x + y - 1)!                 for y < 0
> ⎪⎪────────────────────  for x < y
> ⎪⎪     (-x - 1)!
> ⎪⎪
> ⎪⎪        zoo           otherwise
> ⎪⎩
> ⎪
> ⎪               1                      for y = 0
> ⎨
> ⎪               x                      for y = 1
> ⎪
> ⎪               0                  for x > 0 ∧ x < y
> ⎪
> ⎪⎧    y
> ⎪⎪(-1) ⋅(-x + y - 1)!
> ⎪⎪───────────────────  for x < 0
> ⎪⎪     (-x - 1)!
> ⎪⎨                                     otherwise
> ⎪⎪        x!
> ⎪⎪     ────────        otherwise
> ⎪⎪     (x - y)!
> ⎩⎩
> ```

So what should this finally return in this case when we don't have any conditions on x and y :
In [75]: ff(x,y)
Out[75]: FallingFactorial(x, y)

In [76]: _.rewrite('gamma')
**Out[76]: gamma(x + 1)/gamma(x - y + 1)???** 

if yes, then is this the code for `def _eval_rewrite_as_gamma(self, x, k, **kwargs)` in **ff**:
```
return Piecewise(
(Piecewise(
    (factorial(x)/factorial(x-y), Ge(x, 0)),
    ((-1)**-y*factorial(y-x-1)/factorial(-x - 1), Lt(x, y)),
    (zoo,True)),
Lt(y,0)),
(1,
Eq(y, 0)),
(x,
Eq(y, 1)),
(0,
And(Gt(x, 0), Lt(x, y))),
(Piecewise(
    ((-1)**y*factorial(y - x - 1)/factorial(-x - 1), Lt(x, 0)),
    (factorial(x)/factorial(x-y), True)),
True))
```

**Comment by sachin-4099** [comment]
> >>> [ff(x,y).rewrite(gamma).subs(dict(x=1,y=1)) for i in range(-2,3)]
> [0, 0, 0, 0, 0]
> ```

Shouldn't this be [1, 1, 1, 1, 1]??

**Comment by sachin-4099** [comment]
In this case:
>In [78]: ff(5,y)
>Out[78]: FallingFactorial(5, y)
>In [79]: _.rewrite('gamma')
>Out[79]: 0

what is the correct result?

**Comment by smichr** [comment]
> Shouldn't this be [1, 1, 1, 1, 1]??

no, `[1/6, 1/2, 1, 1, 0]`, e.g.
```python
>>> ff(x,-2)
1/((x + 1)*(x + 2))
>>> _.subs(x,1)
1/6
```

**Comment by smichr** [comment]
> what is the correct result, when one argument is an Integer and the other one is a Symbol?

In my ffrewrite branch I try to give the answer for this in terms of Piecewise. Lots of other places in SymPy make assumptions about the variables and so the Piecewise answer isn't expected and lots of tests fail. But I think the answer for `ff(5,y).rewrite(gamma)` should be:
```
⎧  120              
⎪────────  for y < 0
⎪Γ(6 - y)           
⎪                   
⎪   1      for y = 0
⎪                   
⎨   5      for y = 1
⎪                   
⎪   0      for y > 5
⎪                   
⎪  120              
⎪────────  otherwise
⎩Γ(6 - y)           
```
Hmm...those special values are covered by the functions (which are both the same). So the rewrite must be simpler. This works: define `f(x,y)` as
```
⎧   Γ(x + 1)               
⎪ ────────────    for x ≥ 0
⎪ Γ(x - y + 1)             
⎪                          
⎨    y                     
⎪(-1) ⋅Γ(-x + y)           
⎪───────────────  otherwise
⎪     Γ(-x)                
⎩                          
```
And that passes the tests:
```python
for i in range(-5,5):
 for j in range(-5,5):
  assert ff(i,j)==f(i,j),(ff(i,j),f(i,j),i,j)

for i in range(1000):
   i,j=[randint(-30,30) for do in range(2)]
   assert ff(i,j)==f(i,j),(ff(i,j),f(i,j),i,j)
```

**Comment by sachin-4099** [comment]
```
def _eval_rewrite_as_gamma(self, x, k, **kwargs):
            from sympy import gamma
            
            if (And(Ge(x, 0), Lt(k, 0))):
                return (factorial(x)/factorial(x-k)).rewrite(gamma)
            elif (And(Lt(x, k), Lt(k, 0))):
                return ((-1)**-k*factorial(k-x-1)/factorial(-x - 1)).rewrite(gamma)
            elif Lt(k, 0):
                return zoo
            elif Eq(k, 0):
                return 1
            elif Eq(k, 1):
                return x
            elif (And(Gt(x, 0)), Lt(x, k)):
                return 0
            elif Lt(x, 0):
                return ((-1)**k*factorial(k-x-1)/factorial(-x - 1)).rewrite(gamma)
            else:
                return (factorial(x)/factorial(x-k)).rewrite(gamma)
```

This is how the function looks like in my branch

**Comment by sachin-4099** [comment]
for i in range(-5,5):
 for j in range(-5,5):
  assert ff(i,j)==ff(i,j).rewrite(gamma)

for i in range(1000):
   i,j=[randint(-30,30) for do in range(2)]
   assert ff(i,j)==ff(i,j).rewrite(gamma)

ff(5, y).rewrite(gamma)

ff(x, y).rewrite(gamma)

[ff(x,i).rewrite(gamma).subs(x,1) for i in range(-2,3)]

[ff(x,y).rewrite(gamma).subs({x:1,y:i}) for i in range(-2,3)]

All these 6 regression tests are working as expected.

**Comment by sachin-4099** [comment]
> Hmm...those special values are covered by the functions (which are both the same). So the rewrite must be simpler. This works: define `f(x,y)` as
> 
> ```
> ⎧   Γ(x + 1)               
> ⎪ ────────────    for x ≥ 0
> ⎪ Γ(x - y + 1)             
> ⎪                          
> ⎨    y                     
> ⎪(-1) ⋅Γ(-x + y)           
> ⎪───────────────  otherwise
> ⎪     Γ(-x)                
> ⎩                          
> ```

I will try this however.

**Comment by smichr** [comment]
Here is another way this problem is exhibited:
```python
>>> Product(i,(i,a,b)).doit()
RisingFactorial(a, -a + b + 1)
>>> _.rewrite(gamma)
gamma(b + 1)/gamma(a)
>>> _.subs(a,-2).subs(b,-1)
0     # <--------------------- wrong
>>> Product(i,(i,-2,-1)).doit()
2
```

**Comment by sachin-4099** [comment]
> Here is another way this problem is exhibited:
> 
> ```python
> >>> Product(i,(i,a,b)).doit()
> RisingFactorial(a, -a + b + 1)
> >>> _.rewrite(gamma)
> gamma(b + 1)/gamma(a)
> >>> _.subs(a,-2).subs(b,-1)
> 0     # <--------------------- wrong
> >>> Product(i,(i,-2,-1)).doit()
> 2
> ```

Will just make the changes to rising factorial as well.

**Comment by smichr** [comment]
> Will just make the changes to rising factorial as well.

look at the mods I made in my branch -- I make the changes in ff and make rf rewriting go through ff.

**Comment by smichr** [comment]
I just updated my branch now.

**Comment by sachin-4099** [comment]
How can I see the changes of your branch?

**Comment by sachin-4099** [comment]
Can you become active on gitter?
