### ISSUE TITLE
Bug in fields

### ISSUE THREAD

**Issue by abhinav28071999** [sympy/sympy#18694]
`2.1 in FF(5)`
`Out[268]: False`
`2 in FF(5)`
`Out[269]: True`
As expected but:

`2.0 in FF(5)` raises error but `2 in FF(5.0)` works fine.
Is this a bug?

**Comment by sylee957** [comment]
In my tests, I can't see any problem in `2.0 in FF(5)`. 
Can you double check?

**Comment by abhinav28071999** [comment]
![err](https://user-images.githubusercontent.com/41710346/74954361-03101780-5429-11ea-94c1-e3a4245421fa.png)
I guess it's been resolved in current version, cause it is working fine on sympy live.
