### ISSUE TITLE
Eq not working with vectors

### ISSUE THREAD

**Issue by crazyminecuber** [sympy/sympy#18692]
I want to set up a vector relation and be able to solve for a certain variable.

    from sympy.physics.vector import *
    from sympy import * 

    t,l = symbols("t l")
    R = ReferenceFrame('R')
    eq1 = Eq(5*R.x + t*R.y, l*R.x + 4*R.y
    solve(eq1,t)

Then I get this error. 

    Traceback (most recent call last):
      File "stackoverflow_test.py", line 6, in <module>
        Eq(5*R.x + t*R.y, l*R.x + 4*R.y)
      File "/usr/lib/python3.8/site-packages/sympy/core/relational.py", line 474, in __new__
        lhs = _sympify(lhs)
      File "/usr/lib/python3.8/site-packages/sympy/core/sympify.py", line 418, in _sympify
        return sympify(a, strict=True)
      File "/usr/lib/python3.8/site-packages/sympy/core/sympify.py", line 340, in sympify
        raise SympifyError(a)
    sympy.core.sympify.SympifyError: SympifyError: 5*R.x + t*R.y

I see no reason why this should not work.

**Comment by sylee957** [comment]
I don't think that stuff in `physics.vector` is intended to be compatible with the stuff outside of mechanics.

You should switch to `sympy.vector`
```python3
from sympy.vector import *
from sympy import * 

t, l = symbols("t l")
R = CoordSys3D('R')
eq1 = Eq(5*R.x + t*R.y, l*R.x + 4*R.y)
solve(eq1, t)
```

**Comment by crazyminecuber** [comment]
In this stack exchange question, which i posted (https://stackoverflow.com/questions/60225204/vector-equation-in-sympy),  the lead developer of the project considered this to be a bug and told me to report it here. What is the logic with having different types of vectors by the way?

**Comment by crazyminecuber** [comment]
The code that you provided does not work the way I imagined either. 
Code:

    from sympy.vector import *
    from sympy import * 

    t, l = symbols("t l")  
    R = CoordSys3D('R')
    eq1 = Eq(5*R.x + t*R.y, l*R.x + 4*R.y)
    s = solve(eq1, t) 
    print(eq1)
    print("")
    print(s)

Output:

    Eq(5*R.x + R.y*t, R.x*l + 4*R.y)

    [(R.x*l - 5*R.x + 4*R.y)/R.y]

Expected:

     Eq(5*R.x + R.y*t, R.x*l + 4*R.y)

     [4]

**Comment by sylee957** [comment]
Okay, I see there is a problem with the solver applied to the vector module as well.
I'm not sure that you should use `i, j, k` instead of `x, y, z`, but neither do they work.

**Comment by 2019202009ankush** [comment]
hi @sylee957 I want to solve this issue ..could you please the location of source code .

**Comment by moorepants** [comment]
> What is the logic with having different types of vectors by the way?

The physics vector was created first to be use for mechanics problems. The sympy.vector was created later in an attempt at making it an immutable type and would eventually replace sympy.physics.vector if it ever obtained feature parity.

**Comment by moorepants** [comment]
I can see it being using to solve sympy.physics.vector equations. So, I'd consider this a feature request, not a bug. sympy.physics.vector can't do everything normal sympy types can, thus a feature request.

**Comment by faze-geek** [comment]
@moorepants
I think this feature would be great to add .I would like to work on it !
The initial idea I had was to make a separate `solve_vector()` method where we can use subs() and make all other components of the vector 0 then solve for each variable . 

I would appreciate your assistance to solve this issue !

**Comment by moorepants** [comment]
Feel free to give it a shot. A `solve_vector` function or method that resides in the sympy.physics.namespace could be helpful.

**Comment by faze-geek** [comment]
> Feel free to give it a shot. A `solve_vector` function or method that resides in the sympy.physics.namespace could be helpful.

Just a small doubt . Doesn't the above comment [#18692](https://github.com/sympy/sympy/issues/18692#issuecomment-590915670) suggest that this should reside in sympy.vector instead of sympy.physics !?
Thanks anyways !

**Comment by moorepants** [comment]
The existing `solve()` functions should work with `sympy.vector`. If it doesn't then the task is to fix `solve()`. If you want it to work with `sympy.physics.vector` then you need a specialized function in that module.

**Comment by moorepants** [comment]
To solve vector equations, you must expressed the vector in the desired reference frame and extract the measure numbers. This is how to solve the original equation:

```python
from sympy.physics.vector import *
from sympy import * 

t,l = symbols("t l")
R = ReferenceFrame('R')
eq1 = 5*R.x + t*R.y - l*R.x - 4*R.y
solve(eq1.to_matrix(R) ,t)
```

which returns:

```
{t: 4}
```
