### ISSUE TITLE
There is a problem or limitation when the Limit is calculated

### ISSUE THREAD

**Issue by M-Oliv3** [sympy/sympy#18707]
I would like to know the limit when p>1 , if I write the next code. 
```
from sympy import Symbol, Limit, S

n = Symbol('n')
p = Symbol('p', positive=True, real=True, nonzero=True)

Limit(1/(p**n),n,S.Infinity).doit()
```
The anwser is a Error message.
I think that it could have a option in the assumption names like p = Symbol('p', positive=True, real=True, nonzero=True, p>1) or for  
p = Symbol('p', positive=True, real=True, nonzero=True) the answser could be {1 , 0} for p=1 and p>1

**Comment by oscarbenjamin** [comment]
There isn't currently a way to express assumptions like `p>1`. The new assumptions can express that but don't have any code to handle it.

A work around is to make a substitution for a symbol that represents p-1 and declare that as positive:
```
In [11]: p = Symbol('p')                                                                                                                       

In [12]: pm1 = Symbol('p', positive=True)  # represents p-1                                                                                    

In [13]: e = 1/p**n                                                                                                                            

In [14]: e2 = e.subs(p, pm1+1)                                                                                                                 

In [15]: e2.limit(n, oo)                                                                                                                       
Out[15]: 0
```

**Comment by anutosh491** [comment]
This doesn't return an error message on master currently . Can be marked as easy to fix as this issue only needs tests for different values of p and the general expression to be closed .
```
>>> Limit(1/(p**n),n,S.Infinity).doit()
exp(-oo*sign(log(p)))
```
