### ISSUE TITLE
Bug in mod_inverse

### ISSUE THREAD

**Issue by abhinav28071999** [sympy/sympy#18706]
`mod_inverse(FF(97)(12), 97)` returns `1/12`. Which should be wrong.

**Comment by dubesar** [comment]
@abhinav28071999  please can you tell what is FF(97)(12)?

**Comment by jksuom** [comment]
`mod_inverse` is for integers. For elements `a = FF(97)(12)` of a finite field one should use division `1/a` or `a.invert()`.
