### ISSUE TITLE
Cannot modify MutableDenseNDimArray

### ISSUE THREAD

**Issue by msligo** [sympy/sympy#18715]
Hello,

My understanding is that you should be able to modify the values in a MutableDenseNDimArray, however, since the update to version 1.5, I have not been able to do so.

Minimal working example:

`import sympy`
`p = sympy.MutableDenseNDimArray.zeros(3)`
`p[0] = 5`

The above code gives the following error: "ValueError: Only a tuple index is accepted"

I've tried searching for information on this error, but I can't find anything. The above code works in version 1.4.

**Comment by oscarbenjamin** [comment]
In 1.5 and on master you need to use `p[[0]] = 5` to get the same effect. That also works on 1.4.

Bisect shows the behaviour was changed in fcf9b2f2ebeac66472549e47d751b8c55a98b568 which is part of #17226

I am not sure I understand the purpose of the change @kangzhiq @Upabjojr

**Comment by msligo** [comment]
Yes! Thank you, that worked. I'm also curious to know why it was changed though.

**Comment by oscarbenjamin** [comment]
I'm also curious why it was changed. I would expect that an integer would be a valid index for a 1D array. I'm reopening this. @kangzhiq @Upabjojr
