### ISSUE TITLE
Not able to solve such equation 

### ISSUE THREAD

**Issue by MaqOwais** [sympy/sympy#18723]
`from sympy import *`
`from sympy.abc import x, y`

`sys = 2**x+6**x-5`
`solve(sys)`

![Screen Shot 2020-02-25 at 7 48 35 PM](https://user-images.githubusercontent.com/57854867/75255392-df254b00-5807-11ea-9a23-e6d1b87bb5f5.png)

**Comment by smichr** [comment]
Do you know a way to solve such equations on paper? If not, you can use `nsolve` with an intial guess of the the roots location. This is so well behaved, however, it is not too hard to succeed:
```
>>> eq
2**x + 6**x - 5
>>> nsolve(_, 1).round(3)
0.682
```

**Comment by MaqOwais** [comment]
`from sympy import *`
`from sympy.abc import x, y`

`sys = 5**(x - 3) - 3**(2*x + 1)`
`solve(sys)`

> [log(375**(1/log(5/9)))]


But such equations are being able to solve under ' solve '...

**Comment by oscarbenjamin** [comment]
The solvability of this kind of equation is very sensitive to the form of the equation e.g.:
```julia
In [1]: sys = 5**(x - 3) - 3**(2*x + 1) 
   ...: solve(sys)                                                                                                                             
Out[1]: 
⎡   ⎛      1    ⎞⎤
⎢   ⎜   ────────⎟⎥
⎢   ⎜   log(5/9)⎟⎥
⎣log⎝375        ⎠⎦

In [2]: sys = 5**(x - 3) - 3**(2*x + 1) + 1 
   ...: solve(sys)                                                                                                                             
---------------------------------------------------------------------------
NotImplementedError
```
Certain special cases can be solved but you should not be surprised when similar but slightly different problems can not be solved. This is not just a limitation of sympy.

**Comment by smichr** [comment]
Yes, the homogeneous vs inhomogeneous case. When homogeneous, the terms can be equated and then manipulated with `log` to get them into a linear form.
