### ISSUE TITLE
periodicity computation of trigonometric functions

### ISSUE THREAD

**Issue by j3parera** [sympy/sympy#18736]
The period of a sine or cosine function is computed correctly except when the argument is expressed as a product of pi with a frequency portion plus a constant phase portion. The use of the `periodicity` function at `sympy.calculus.util` doesn't fix it. Expanding the argument with `expand_mul` can help but not always (see last code example), although, at least in this case, `periodicity` does work.

```python
from sympy import *
x = Symbol('x')

e0 = cos(S.Pi*x/4)
print(e0.period(), '-> OK')

e1 = cos(S.Pi*x/4 + 10)
print(e1.period(), '-> OK')

e2 = cos(S.Pi*x/4 + S.Pi/4)
print(e2.period(), '-> OK')

e3 = cos(S.Pi*(x/4 + 1/4))
try:
    e3.period()
except NotImplementedError as e:
    print(e, '-> Not OK')

from sympy.calculus.util import periodicity
print(periodicity(e3, x), '-> Not OK')

e4 = expand_mul(e3)
print(e4.period(), '-> OK')

e5 = expand_mul(cos(S.Pi*(x/4 + 1)))
try:
    e5.period()
except AttributeError as e:
    print(e)
```

**Comment by smichr** [comment]
This might be as simple as using `expand_mul` in the two `_period` functions in trigonometric.py at the start: `f = self.args[0]` -> `f = expand_mul(self.args[0])`.

**Comment by j3parera** [comment]
I'm glad it was so easy to fix.
Unfortunately I've seen that the same problem arises with complex exponentials using the `periodicity` function. The solution might be more difficult because in this case `expand_mul` is not enough. The function also fails with the real and imaginary parts, although in this case `period()` does work.

```python
from sympy import *
x = Symbol('x', real=True)

e0 = exp(S.ImaginaryUnit*S.Pi*x/4)
print(periodicity(e0, x), '-> OK')

e1 = exp(S.ImaginaryUnit*S.Pi*x/4 + S(10))
print(periodicity(e1, x), '-> OK')

e2 = exp(S.ImaginaryUnit*S.Pi*x/4 + S.Pi/4)
print(periodicity(e2, x), '-> OK')

e3 = exp(S.ImaginaryUnit*S.Pi*(x/4 + S(1)/4))
print(periodicity(e3, x), '-> Not OK')
print(periodicity(re(e3), x), '-> Not OK')
print(periodicity(im(e3), x), '-> Not OK')
print(re(e3).period(), '-> OK')
print(im(e3).period(), '-> OK')

e4 = exp(expand_mul(S.ImaginaryUnit*S.Pi*(x/4 + S(1)/4)))
print(periodicity(e4, x), '-> Not OK')
print(periodicity(re(e4), x), '-> Not OK')
print(periodicity(im(e4), x), '-> Not OK')
print(re(e4).period(), '-> OK')
print(im(e4).period(), '-> OK')
```
