### ISSUE TITLE
Inconsistency in the sign criterion new draw method.

### ISSUE THREAD

**Issue by amartinhernan** [sympy/sympy#18753]
In the `sympy.physics.continuum_mechanics` module when you apply a load the sign criteria for a moment is positive if it is counterclockwise, but if you introduce a positive moment the `draw()` method sketch a clockwise moment. Probably the error can be solved by switching the lines 1629 and 1631.
https://github.com/sympy/sympy/blob/021a32ba040753994c4bc8e0a21fc3ef5a863368/sympy/physics/continuum_mechanics/beam.py#L1627-L1631

**Comment by smichr** [comment]
ping @moorepants

**Comment by moorepants** [comment]
This is likely the correct fix.
