### ISSUE TITLE
Incorrect parenthesizing of Integral

### ISSUE THREAD

**Issue by Ryand1234** [sympy/sympy#18758]
On running this code,
```python
>>> from sympy import *
>>> init_session(quiet=True)
Python 3.7.5 (default, Nov 20 2019, 09:21:52) 
[GCC 9.2.1 20191008] on linux
Type "help", "copyright", "credits" or "license" for more information.
(SymPyConsole)
>>> latex(Integral(-Integral(y**2,y),y))
```
The output of the above code is:
```LaTex
\int - \int y^{2}\, dy\, dy
```
![equation](https://latex.codecogs.com/gif.latex?%5Cint-%5Cint%5C%2Cy%5E%7B2%7D%5C%2Cdy%5C%2Cdy)
But for better view, it should be parenthesized to:
```LaTex
\int \left(- \int y^{2}\, dy\right)\, dy
```
![equation](https://latex.codecogs.com/gif.latex?%5Cint%5Cleft%28-%5Cint%5C%2Cy%5E%7B2%7D%5C%2Cdy%5Cright%29%5C%2Cdy)

**Comment by asmeurer** [comment]
The pretty printer handles this by making the leftmost integral sign bigger

```
>>> pprint(Integral(-Integral(y**2,y),y))
⌠
⎮  ⌠
⎮  ⎮  2
⎮ -⎮ y  dy dy
⎮  ⌡
⌡
```

**Comment by Ryand1234** [comment]
No, the latex equation printed was wrong

**Comment by Ryand1234** [comment]
> No, the latex equation printed was wrong

Not wrong but should be parenthesized for clearity

**Comment by Ryand1234** [comment]
This issue is same as #18731

**Comment by sylee957** [comment]
The difficult part is mangling with the precedence such that it does not add up some unnecessary parenthesis for printing Add and Mul.

**Comment by Ryand1234** [comment]
The problem can be solved by checking if the integral had a negative sign .
The same problem happened with the derivative as mentioned in #18731 .
