### ISSUE TITLE
Series expansion for sqrt(1+e+e^2 cos(theta)) seems bugged if x0 !=0

### ISSUE THREAD

**Issue by bth5032** [sympy/sympy#18762]
to reproduce run (in jupyter for `display` commands to work)
```
#Extra terms for dipole expansion
e = symbols("epsilon")
g0 = symbols("g", cls=Function)
g0 = sqrt(1 + e**2 - 2* (e)*cos(psi))
g1 = Lambda(e, diff(sqrt(1 + e**2 - 2* (e)*cos(psi)), e))
g2 = Lambda(e, diff(diff(sqrt(1 + e**2 - 2* (e)*cos(psi)), e), e))
g3 = Lambda(e, diff(diff(diff(sqrt(1 + e**2 - 2* (e)*cos(psi)), e), e),e))

print("first derivative:")
display(g1)
print("second derivative:")
display(g2)
print("expected expansion around 0:")
display(1 + e*g1(0) + (1/2)*e**2 * g2(0))
print("expected expansion around 1:")
display(1 + e*g1(1) + (1/2)*e**2 * g2(1))

print("Expand around 0:")
display(g0.series(x=e,x0=0,n=3))

print("Expand around 1:")
display(g0.series(x=e,x0=1,n=3))
``` 

You'll see sympy correctly evaluates the derivatives `g1`, `g2`, `g3`, and computes the correct expansion for `g0.series(x=e,x0=0,n=3)`, but the expansion around 1 has about 100 extra terms (this also occurs for `x0=.5`, so I think it's any nonzero `x0`). It looks like the expression was differentiated many more times than twice as you have terms of order cosine**5

I've attached an image of the partial output (the full expansion is too large to take a screenshot):
![sympy_bug](https://user-images.githubusercontent.com/6195617/75721808-dd3b0c00-5c8d-11ea-80a2-be9398851f80.PNG)

Thanks!

**Comment by jksuom** [comment]
It seems that computation of order terms is sensitive to the format of the argument which makes an order computed in `Pow._eval_nseries` too wide. This can be fixed, at least in this case, by changing the format:
```
--- a/sympy/core/power.py
+++ b/sympy/core/power.py
@@ -1625,7 +1625,7 @@ def e2int(e):
         # either b0 is bounded but neither 1 nor 0 or e is infinite
         # b -> b0 + (b - b0) -> b0 * (1 + (b/b0 - 1))
         o2 = order*(b0**-e)
-        z = (b/b0 - 1)
+        z = (b - b0)/b0
         o = O(z, x)
         if o is S.Zero or o2 is S.Zero:
             infinite = True
```
