### ISSUE TITLE
Introduce 'evaluate' keyword argument in MatAdd and MatMul

### ISSUE THREAD

**Issue by mcpl-sympy** [sympy/sympy#18764]
``MatAdd`` and ``MatMul`` are behaving differently from ``Add`` and ``Mul``.

Here is an example:
```python
>>> from sympy import Add, MatAdd, Symbol, MatrixSymbol
>>> x = Symbol('x')
>>> Add(x, x, evaluate=True)
2*x
>>> Add(x, x, evaluate=False)
x + x

>> A = MatrixSymbol('A', 2,2)
>>> MatAdd(A, A)
A + A
>>> MatAdd(A, A, evaluate=True)
A + A
```

I believe it would be better to add ``evaluate`` option which canonicallizes the object, so that

```python
>>> MatAdd(A, A, evaluate=True)
2*A
```

**Comment by sylee957** [comment]
I had seen https://github.com/sympy/sympy/issues/16484#issuecomment-477878619 that things were not originally designed to use any automatic evaluation.
But I think that things can look different at this moment, and I also didn't like the inconsistency there before. But this may need some agreements because this is more of a design issue.
After `evaluate` is introduced in matadd, matmul, it should also be added in matpow or hadamard stuff.

**Comment by mcpl-sympy** [comment]
@sylee957 
If sympy's matrices are designed that way, then setting `evaluate`'s default value as `False` honours this.
This is similar to `Derivative`: since `Derivative` should not be automatically evaluated, its default `evaluate` is `False`.

`evaluate` is used everywhere in sympy core. Since this change does not break backward compatibility, I strongly suggest that it is necessary.

**Comment by oscarbenjamin** [comment]
Handling evaluate consistently is important. I think it should be done in general across all of sympy as in #17372.

I don't see why we should change the default to `evaluate=True` for MatAdd etc though. You can use `a+b` or `MatAdd(a, b).doit()` if you want it to evaluate.

**Comment by mcpl-sympy** [comment]
@oscarbenjamin
I am not object to letting `evaluate=False` as default for `MatExpr`s. In fact, my PR #18765 already does it in that way.

Why I am proposing to add `evaluate` option is purely for the consistency with sympy core. When I used matrix module at the first time, it was very confusing that `MatAdd(A, -A, evaluate=True)` does not return zero matrix while `Add(x, -x, evaluate=True)` does. I believe many will be same.

**Comment by oscarbenjamin** [comment]
I agree that there should be an evaluate option. Also we should ensure that in general `func(a, b, evaluate=True)` is the same as `func(a, b).doit()`.

**Comment by asmeurer** [comment]
Note that the matrix expressions use a slightly different design than the rest of SymPy, where the base classes are completely unevaluated by default, and `doit()` evaluates them. IMO this design is much simpler and we should strive to keep it.

Having an evaluate flag on the matrix expr classes for consistency is probably fine, but we should be careful that we don't break this cleaner design by making it more like the less clean core design. If anything we should strive to do the reverse, by making the core more like the matrix expressions.

**Comment by mcpl-sympy** [comment]
@asmeurer 
Which-one-is-better in this case seems to be controversial. One may prefer `Add(x, x)` to return `2*x`; another may want `x+x`. Furthermore, one might want every expressions to be evaluated in one session, and not in another.

In sympy core, this behavior can be easily switched by changing `global_parameters.evaluate`. Just do `global_parameters.evaluate = False` and one can happily have every expressions unevaluated.  
If we want sympy core to return unevaluated expressions by default (as you suggested), modifying `global_parameters = _global_parameters(evaluate=True, distribute=True)` to `global_parameters = _global_parameters(evaluate=False, distribute=True)` in `core/parameters` module and releasing is all it takes.

However, current matrix module is not. Even if one wants every matrix expressions to be evaluated by default in a session, or on the other way around, wants `A+A` not to be evaluated but to return `MatAdd(A, A)`, there is no way to give this freedom of choice.

Introducing `evaluate=False` option in matrix module does not harm its design a bit, but only allows more degree of freedom to the user and gives coherence to sympy.

**Comment by asmeurer** [comment]
The idea behind the matrix expressions design is that you should only use the classes directly if you want an unevaluated expression. If you want evaluation you should use a function or an operator. You can always force evaluation on an unevaluated expression by calling `doit`. It is the other way around that is challenging, because you can't "unevaluate" an already evaluated expression. That is why the global `evaluate` flag exists for the core. But with the matrix expressions design where everything is unevaluated by default, this sort of thing is not needed.

**Comment by mcpl-sympy** [comment]
@asmeurer

In that point of view, unevaluated form is better indeed. I agree with that core should not be evaluated by default. Why I am insisting though, is to enhance architecture consistency and user experience.  

Using operator (e.g. `x + y`) is restricted because you cannot pass keyword argument with it. To access every feature, on must eventually call the class constructor.  
However, there is a alrge discrepancy beteeen core and matrix on how classes behave. Some classes take `evaluate` option, some don't. In core, `doit(deep=False)` does not evaluate the expression, while it does in matrix (I think core shoud follow matrix's design in this case). All of these combined, sympy lacks integrity between its modules.

If we write a manual on how to call the classes (so that one can pass keyword arguments), current sympy will be like:
> Use `Add`, `Mul`, `Pow` for scalar. Pass `evaluate=True` to get evaluated result. Pass `evaluate=False` to get unevaluated result.  
> Use `MatAdd`, `MatMul`, `MatPow` for matrix to get unevaluated result. Use `Add`, `Mul`, `Pow` for matrix to get evaluated result. Applying `doit` also gives evaluated result.
> Use `TensAdd`, `TensMul`  for tensor (...)  
> Use `VectorAdd`, `VectorMul` for vector (...) 

With this PR and #18769, I am trying to simplify this manual to this:
> Use `Add`, `Mul`, `Pow` every time. Pass `evaluate=True` to get evaluated result. Pass `evaluate=False` to get unevaluated result.

**Comment by oscarbenjamin** [comment]
There is a lot of inconsistency around sympy for these things. See #17280
