### ISSUE TITLE
Add fuzzy logic comparison functions

### ISSUE THREAD

**Issue by oscarbenjamin** [sympy/sympy#18778]
There are many bugs in sympy that come from using inequalities in a bool context e.g.:
```julia
In [5]: def f(x): 
   ...:     if x < 0: 
   ...:         return 'negative' 
   ...:     else: 
   ...:         return 'nonnegative' 
   ...:                                                                                                                                        

In [6]: f(1)                                                                                                                                   
Out[6]: 'nonnegative'

In [7]: f(-1)                                                                                                                                  
Out[7]: 'negative'

In [8]: f(Symbol('y'))                                                                                                                         
--------------------------------------------------------------------------
TypeError: cannot determine truth value of Relational
```
The solution to this is to use `x.is_negative` which gives a fuzzy bool (True, False, None) and does not raise. That works for comparisons with zero but not for other comparisons like `x<1`:
```
if x < 1: # raises for symbol x

if (x - 1).is_negative: # works but creates a new expression needlessly

if (x < 1) is S.true: # works but not obvious

if (x < 1) == True: # works but not obvious
```
I suggest adding new functions that can replace the use of `Eq`, `Ne`, `Lt` etc and return fuzzy bools. The new functions can have names analogous to those of the old assumptions that also use fuzzy logic e.g.:
```python
is_equal(x, y)
is_unequal(x, y)
is_less_than(x, y)
is_less_than_or_equal(x, y)
...
```
These can be used in place of e.g. `Eq(x, y) is S.true` and return True, False, None. The implementation of `Eq` should then become
```python
class Eq(Relational):
    def __new__(cls, lhs, rhs):
        value = is_equal(lhs, rhs)
        if value is True:
            return S.true
        elif value is False:
            return S.false
        else:
            # Return unevaluated
            return Relational.__new__(cls, lhs, rhs)
```
This would cleanly separate the evaluation layer from the querying layer so that evaluation is built on top of querying and querying does not in itself involve creating new instances and evaluating them. Internal code should be changed to use these functions rather than creating Relational instances.

Some of the names can be long e.g. `is_less_than_or_equal` so perhaps an alternative is to use LaTeX-style short names:
```
is_eq(x, y)
is_ne(x, y)
is_lt(x, y)
is_le(x, y)
```
Another possibility is something like
```
cmp(x, '<=', y)
```
which might be more readable for someone new to the codebase.

Making this happen is as simple as taking the code out of the various `Relational.__new__` methods and putting them into separate functions.

**Comment by asmeurer** [comment]
> works but creates a new expression needlessly

Wouldn't that happen internally anyway?

**Comment by sylee957** [comment]
I only have concerns that this can make things like `is_eq` big because it can accept any expressions.
So managing such things would be an another concern.

I was also undecided about how things like `x > 2` should be handled in binary evaluations or should be coerced into `(x-2).is_positive`.
As far as I can see, sympy doesn't have logics for simple inequalities like triangle inequality, so the things should be directed to make such implementations easier.

**Comment by oscarbenjamin** [comment]
The `is_eq` function would just be the body of `Equality.__new__` so it won't be any bigger than that would be anyway. Currently `Equality.__new__` defers to `_eval_Eq` where appropriate.

Currently `Expr.__lt__` and `Lt.__new__` will usually end up doing `(lhs-rhs).is_negative` but that's partly just because there is no `is_lt` function to call. Asking whether `Add(a, -b)` is negative is not inherently any easier than asking whether `a < b`. We just only have an API for one of these and not the other. If we had `is_lt` we could move some of the logic from `Add._eval_is_negative` there and use `is_lt` as part of `Add._eval_is_negative`.

For inequalities the current situation is this:
- `LessThan(a, b)` calls `a.__lt__(b)`  (not `a<b` because of #7951)
- `Expr.__lt__(a, b)` usually calls `(a - b).is_extended_negative`
- If `is_extended_negative` is None then `Expr.__lt__` returns `LessThan(a, b, evaluate=False)`

I would propose to change that to:
- `Expr.__lt__` returns `LessThan(a, b)`.
- `LessThan(a, b)` calls `is_lt(a, b)` and evaluates or not from there.
- The `is_lt` function has some logic of its own (taken from current `Expr.__lt__`) and calls `_eval_is_lt` if present.
- At least for now `is_lt` will mostly defer to `(a - b).is_extended_negative`.
- Various `__lt__` methods around sympy should become `_eval_is_lt` instead.

That way all logic always go through the same function `is_lt`.

**Comment by asmeurer** [comment]
Ideally `ask(x < y)` would work.

**Comment by oscarbenjamin** [comment]
> Ideally `ask(x < y)` would work.

Yes, but that doesn't help us here unless we plan to stop evaluating `x < y` automatically.

**Comment by asmeurer** [comment]
I think it isn't a problem if it gives True or False, since ask(True) and ask(False) do what you'd expect. However, this is a problem

```py
>>> I > 3
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "./sympy/core/expr.py", line 403, in __gt__
    return self._cmp(other, ">", StrictGreaterThan)
  File "./sympy/core/expr.py", line 348, in _cmp
    raise TypeError("Invalid comparison of non-real %s" % me)
TypeError: Invalid comparison of non-real I
```

I think we should strongly consider making that return False instead, for reasons I've outlined in other issues.

**Comment by shubham-khantwal** [comment]
how can I work with this issue?

**Comment by smichr** [comment]
> [regarding `I > 3`]...I think we should strongly consider making that return False instead, for reasons I've outlined in other issues.

I thought it would be better to leave it unevaluated, but I am now in favor with returning False since a pure imaginary evaluates as False in terms of sign:
```python
>>> ok = Dummy(negative=False, positive=False, zero=False)  # not inconsistent
>>> I.is_negative
False
>>> I.is_positive
False
>>> I.is_zero
False
```

**Comment by smichr** [comment]
> Some of the names can be long e.g. `is_less_than_or_equal` so perhaps an alternative is to use LaTeX-style short names:
> 
> ```
> is_eq(x, y)
> is_ne(x, y)
> is_lt(x, y)
> is_le(x, y)
> ```
> 
> Another possibility is something like
> 
> ```
> cmp(x, '<=', y)
> ```
> 
> which might be more readable for someone new to the codebase.

What about `x.lt(y)` or just `lt(x,y)` which is very similar to the current Lt(x, y)? The difference being that the lowercase version always returns something while the uppercase can remain unevaluated in keeping with things like `sum vs Sum`.

**Comment by smichr** [comment]
The `is_*` naming scheme can be extended to the `fuzzy_*` names, too: `is_and(*x) -> fuzzy_and(x)` (note different signature).

**Comment by smichr** [comment]
How is teaching someone to use `if is_lt(x, 1):` for `if x < 1` easier than teaching them to use `if (x < 1) == True:`? And if it is, we needn't create anything new: `fuzzy_bool` already handles this, doesn't it?
```python
>>> from sympy.core.logic import fuzzy_bool as b
>>> from sympy.abc import x
>>> b(x < 1) is None
>>> True
>>> fuzzy_bool(Eq(x,1)) is None
True
>>> var('x', negative=1)
x
>>> fuzzy_bool(x<1)
True
>>> type(_)
<class 'bool'>
```

**Comment by oscarbenjamin** [comment]
I would expect `is_lt` not to raise like `I < 1`.

It's important to separate the things that are above and below the symbolic layer so contributors know what code to use in each situation. The relational `x < 1` is a symbolic Boolean so converting that to a fuzzy bool is backwards.

Most importantly we need a system for evaluating inequalities without converting them to `Add`. Right now something like `a**y < b**z` is evaluated by checking `(b**z - a**y).is_positive` which in turn usually leads to `(b**z - a**y).n()`. There should be a place to add a specific handler for comparing two Pows e.g.:
```
In [3]: 2**x < 2**(x+1)                                                                                                                        
Out[3]: 
 x    x + 1
2  < 2 
```
When there are no symbols this is handled using `.evalf()` but that has its own problems:
```
In [5]: exp(exp(exp(100))) < 2 # hangs...
```
These queries would be trivial to resolve through a `Pow._eval_is_lt` method but are instead handled by the overly complex `Expr.__lt__` and `Add._eval_is_negative` methods.

**Comment by smichr** [comment]
> I would expect `is_lt` not to raise like `I < 1`.

That is a separate issue and at least @asmeurer and I agree that this should not raise. And since `I.is_*ive` is False I don't see why not to just return False or leave it unevaluated if that seems too much like letting something pass silently.

The remaining ideas seem reasonable.

**Comment by smichr** [comment]
> It's important to separate the things that are above and below the symbolic layer

I wonder if I am starting to see this more clearly now as I work with the Lambda equality issue. Throughout the sets module we use `a==b` to query whether two sets are the same. But if we are dealing with ImageSets that are the same mathematically but are written in different symbols then (eventually) the `==` will fail. But we were just relying on Python's operator when we really should have been checking if `a.as_dummy() == b.as_dummy()` or `is_eq(q, b)` or `a.dummy_eq(b)`. Any of the latter would tell if the Python equality holds after unifying bound variables.
