### ISSUE TITLE
CG() docs are wrong?

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#18781]
See https://twitter.com/lahelena/status/1235503518972329984

**Comment by asmeurer** [comment]
I'm not familiar with the physics here, so someone who is will need to confirm.

**Comment by redeboer** [comment]
Just noticed that the docstring is indeed wrong (as shown in the tweet):
https://github.com/sympy/sympy/blob/f522c61ab51ca3e27eaeabe08c2c1c0417e6f246/sympy/physics/quantum/cg.py#L161-L162

but that the reprs are correct, for instance:
https://github.com/sympy/sympy/blob/f522c61ab51ca3e27eaeabe08c2c1c0417e6f246/sympy/physics/quantum/cg.py#L218-L221

See also the docs:
https://docs.sympy.org/latest/modules/physics/quantum/cg.html
