### ISSUE TITLE
doit(deep=False): core vs matrices

### ISSUE THREAD

**Issue by mcpl-sympy** [sympy/sympy#18787]
In sympy core, `doit(deep=False)` does not evaluate unevaluated expression.
```python
>>> from sympy import Symbol, Add
>>> x = Symbol('x')
>>> expr1 = Add(x, -x, evaluate=False)
>>> expr1 # unevaluated
x - x
>>> expr1.doit(deep=False) # still unevaluated
x - x
```

However, in matrix module,  `doit(deep=False)` returns evaluated expression.
```python
>>> from sympy import MatrixSymbol, MatAdd
>>> A = MatrixSymbol('A', 2,2)
>>> expr2 = MatAdd(A, -A)
>>> expr2 # unevaluated
A -A
>>> expr2.doit(deep=False) #evaluated
ZeroMatrix(2, 2)
```

I think matrix module is doing it right. Shall we change core's `doit`?

**Comment by oscarbenjamin** [comment]
See #17280

**Comment by mcpl-sympy** [comment]
@oscarbenjamin 
Thanks! This is encouraging.

**Comment by oscarbenjamin** [comment]
My point is that this is a general problem and not something to think about just for matrices. I made a start at trying to solve it in #17372 but then got distracted cleaning up various things in sets.
