### ISSUE TITLE
Use NameConstant instead of Name for True and False

### ISSUE THREAD

**Issue by w495** [sympy/sympy#18789]
https://github.com/sympy/sympy/blob/f469375c923d8dc50c6632b21f39b7da3d252548/sympy/parsing/sympy_parser.py#L1088

I've stumble over this bug with python3 debug build.
If you clone default python and build it without ```-DNDEBUG``` and run something like this:
```
from sympy.parsing.sympy_parser import parse_expr

parse_expr('2*2', False)
``` 
you will get:
```
.../python3/src/Python/compile.c:3173: int compiler_nameop(struct compiler *, identifier, expr_context_ty): Assertion `!_PyUnicode_EqualToASCIIString(name, "None") && !_PyUnicode_EqualToASCIIString(name, "True") && !_PyUnicode_EqualToASCIIString(name, "False")' failed.
```

This occurs due to the ```assert```-block in python source:
https://github.com/python/cpython/blob/master/Python/compile.c#L3526

This issue doesn't happen if you build python with ```-DNDEBUG``` option. But ideologically ```NameConstant``` and ```Name``` are very different things. 

I've tried to replace  this four ```ast.Name(id='False', ...)```  to ```ast.NameConstant(id='False', ...)``` and it completely solved the problem. But this fix will work only for python3.* 

If you allow, I can send a pool request with it. But with this we should agree to bury python2, IMHO.

Otherwise we should invent a more ~~dirty~~ complex solution. For example:
1) Create a dummy variable ```__False = False```.
2) Put it to ```globals```.
3) Replace ```ast.Name(id='False', ...)``` to  ```ast.Name(id='__False', ...)```.

As I see it, ```NameConstant``` should be used instead of  ```Name``` for ```True``` and ```False```.

**Comment by oscarbenjamin** [comment]
Python 2 support is already removed in master. The next release will not support Python 2.

**Comment by w495** [comment]
Great
