### ISSUE TITLE
Operations on AccumBounds should be amended

### ISSUE THREAD

**Issue by jksuom** [sympy/sympy#18795]
Some operations on AccumBounds fail unexpectedly.
```
>>> from sympy import *
>>> a = AccumBounds(-1, 1)
>>> r = symbols('r', real=True)
>>> (a + r)/a
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jks/test/sympy/sympy/core/decorators.py", line 91, in __sympifyit_wrapper
    return func(a, b)
  File "/home/jks/test/sympy/sympy/calculus/util.py", line 1215, in __div__
    if S.Zero in self and S.Zero in other:
  File "/home/jks/test/sympy/sympy/calculus/util.py", line 1554, in __contains__
    raise TypeError("input failed to evaluate")
TypeError: input failed to evaluate
```
This is caused by the test `S.Zero in self` that raises if it cannot determine the truth value. This test should be replaced by something like `self.min.is_nonpositive and self.max.is_nonnegative` that will return None in such cases. The other tests with S.Zero in `__div__` and `__rdiv__` should be handled similarly. In addition, these lines https://github.com/sympy/sympy/blob/f469375c923d8dc50c6632b21f39b7da3d252548/sympy/calculus/util.py#L1218-L1222
can be extended to two other cases where `self/other.max/min.is_zero`.

Other operations should also be amended. For instance,
```
>>> b = AccumBounds(-oo, oo)
>>> b + r
AccumBounds(-oo, oo)
>>> b + tan(r)
AccumBounds(tan(r) - oo, tan(r) + oo)
```
The real number `r` is absorbed by the cover-all AccumBounds object `b` but the extended real `tan(r)` is not absorbed. However, it probably should be. So the arguments `tan(r) - oo` and `tan(r) + oo` of AccumBounds should be `-oo` and `oo`.

**Comment by oscarbenjamin** [comment]
Should `tan(r)` be considered `extended_real`? It can be `zoo`:
```julia
In [5]: tan(r).is_extended_real                                                                                                                               
Out[5]: True

In [6]: tan(pi/2)                                                                                                                                             
Out[6]: zoo
```

**Comment by jksuom** [comment]
I think that `tan(r)` should be considered extended real for generic real `r`even if it evaluates to `zoo` for some specific arguments.

**Comment by Ryand1234** [comment]
> So the arguments `tan(r) - oo` and `tan(r) + oo` of AccumBounds should be `-oo` and `oo`.

Can't this can be done by checking if both the variable are of type AccumBounds it will perform the addition but if one of the variable is not of type AccumBounds then it will just ignore that variable and print AccumBound of other variable?

**Comment by jksuom** [comment]
That should be implemented in the `__add__` method of AccumBounds, and only in case min is `-oo` and/or max is `oo`. So an argument of the sum should not be `nan`.

**Comment by Ryand1234** [comment]
@jksuom should the output of the above case be like this?
```python
>>> from sympy import *
>>> a = AccumBounds(-1,1)
>>> r = symbols('r',real=True)
>>> a+r
AccumBounds(r - 1, r + 1)
>>> (a+r)/a
AccumBounds(-1, 1)*AccumBounds(r - 1, r + 1)
```
