### ISSUE TITLE
Fix documentation for FormalPowerSeries 

### ISSUE THREAD

**Issue by leosartaj** [sympy/sympy#18808]
Currently, formatting of the documentation for [``FormalPowerSeries``](https://docs.sympy.org/latest/modules/series/formal.html) is broken. 

On first look docs for the following function needs to be fixed (mostly latex):

* ``coeff_bell``
* ``compose``
* ``inverse``

**Comment by sudoWin** [comment]
I would like to fix it

**Comment by smitgajjar** [comment]
I am working on it, I will make a PR soon!
