### ISSUE TITLE
Resolve timeouts in test_digits.py

### ISSUE THREAD

**Issue by sylee957** [sympy/sympy#18800]
https://travis-ci.org/sympy/sympy/jobs/659764490?utm_medium=notification&utm_source=github_status
It can be because of the added feature in #18659 which involved random tests.

Ping @sr-murthy

**Comment by sylee957** [comment]
I inspect that the timeouts are due to some wrong samples like `[0, 0, ...]`.
It needs better sampling in my opinion.

**Comment by smichr** [comment]
```python
        digits = (
            random.choices(range(base), k=m) if py_version[0] == 3 and py_version[1] >= 6
            else [random.choice(range(base)) for i in range(m)]
        )
        while digits[0] == 0:
            random.shuffle(digits)
```
should be
```python
        digits = (
            random.choices(range(base), k=m) if py_version[0] == 3 and py_version[1] >= 6
            else [random.choice(range(base)) for i in range(m)]
        )
        if digits[0] == 0:  # make sure first digit is nonzero
            digits[0] = random.choice(range(1, base))
```

**Comment by oscarbenjamin** [comment]
You can also do `if py_version >= (3, 6)`.

Is there any advantage in using `random.choices` besides speed? If not then I would just use the list comprehension like:
```
digits = [random.randrange(1, base)] + [random.randrange(base) for _ in range(m)]
```
