### ISSUE TITLE
Arguments in initialising singleton Half

### ISSUE THREAD

**Issue by MooVI** [sympy/sympy#18813]
I came across this while trying to dump and then load SymPy expressions using PyYAML. Occasionally it would work and sometimes it would not. It turns out that the root cause was this behaviour:

```
In [1]: import sympy                                                                                          

In [2]: sympy.numbers.Half(1,2)                                                                               
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-2-25975122b392> in <module>
----> 1 sympy.numbers.Half(1,2)

~/.local/lib/python3.7/site-packages/sympy/core/singleton.py in __call__(self, *args, **kwargs)
    174         if self not in Singleton._instances:
    175             Singleton._instances[self] = \
--> 176                 super(Singleton, self).__call__(*args, **kwargs)
    177                 # Invokes the standard constructor of SomeClass.
    178         return Singleton._instances[self]

TypeError: __new__() takes 1 positional argument but 3 were given

In [3]: sympy.numbers.Half()                                                                                  
Out[3]: 1/2

In [4]: sympy.numbers.Half(1,2)                                                                               
Out[4]: 1/2 
```

So the reason why this is happening is that once Half is initialised it ignores any erroneous arguments (the relevant code is literally in the error message).

Should it always throw an error, or never throw an error? Or is the idea that because you should always be using S.Half this ambiguity should not be seen? [Obviously I only found this because PyYAML was trying to reconstruct the classes programmatically.]

Related, I guess, to issue #5303

**Comment by MooVI** [comment]
Actually this seems to fail with `pickle`  (i.e. if I `pickle.dump` just `S.Half` then attempt to `pickle.load` in a different session before `S.Half` is initialised, I get the error message above) as well even at highest protocol level, which seems to be a regression of #5303 ?

**Comment by oscarbenjamin** [comment]
Are you using master?

**Comment by oscarbenjamin** [comment]
#18438

**Comment by oscarbenjamin** [comment]
We need to test unpickling in a subprocess

**Comment by MooVI** [comment]
Ah, my bad, I had forgotten that the machine I tested this on I had installed from pip rather than GitHub and therefore not updated. Also I hadn't initially connected the issue with pickling or I would probably have found #18438.

It's unfortunate that the `Singleton` stuff means things can't work consistently with PyYAML but I guess it can't be helped.

**Comment by oscarbenjamin** [comment]
> It's unfortunate that the `Singleton` stuff means things can't work consistently with PyYAML but I guess it can't be helped.

Is this still not fixed on master?

**Comment by MooVI** [comment]
No, you're right, it works with PyYAML too! Not sure why I thought PyYAML wouldn't use __getnewargs__ as well.

Thanks for your help -- apologies again for not realising I wasn't on master.
