### ISSUE TITLE
disjoint_union() in sets

### ISSUE THREAD

**Issue by sava-1729** [sympy/sympy#18833]
Has evaluating the disjoint union of a collection of sets been implemented in SymPy? I could not find it therefore I'd like to implement it. Here's the definition: [https://en.wikipedia.org/wiki/Disjoint_union](url)

I was thinking of creating a class ``DisjointUnion`` derived from ``Set`` (just like the classes ``Union``, ``Intersection``, etc.), which would do the job. 
If each argument is iterable, the elements of the ``DisjointUnion`` can be simply represented as 2-tuples (or pairs), where the first element of each tuple would be an element of one of the original iterable sets, and the second element would denote the index of the set from which it originates. 
However, if any of the arguments isn't iterable, I'm not sure how to represent the elements. Any views/ideas/suggestions would be greatly appreciated.

**Comment by sylee957** [comment]
I'd stick to allowing only sympy `Set` objects. 
Getting it work with arbitrary iterables can introduce a lot of abuse.

**Comment by shubham-khantwal** [comment]
how can i contribute to this issue?

**Comment by sava-1729** [comment]
> I'd stick to allowing only sympy `Set` objects.
> Getting it work with arbitrary iterables can introduce a lot of abuse.

Yes, indeed, I'll only allow ``Set`` objects to be given as arguments. But even then, every ``Set`` need not be iterable, right? For eg, if we consider two closed intervals A = [1,2] and B = [1,2]. Clearly the two closed intervals are equal. But the disjoint union of the two would be 
C = { (x, i) | (x ∈ A and i = 1) OR (x ∈ B and i = 2) }
So this set would look like the union of the sets:
{ (x, 1) | x ∈ A } U { (x, 2) | x ∈ B }
So what we need is some standard object to represent pairs as above, but we need something that is valid for every class derived from Set, such as interval, union, etc, because in the above case we don't have any way to store intervals with multiple dimensions? And also that won't be sufficient because ``Set`` could be anything.
Btw, have k-cells, i.e., rectangles in R^n, been implemented? If not, I'd like to start with that, and it will probably give me a better idea of how to go about this.

**Comment by sava-1729** [comment]
I think I found it,
Given any collection of sets { A_i } where i varies from 0 to n, I'll define the disjoint union as:
(A_1 × {1}) U (A_2 × {2}) U ..... U (A_n × {n})
This way, it will be entirely defined using existing functions and classes in sympy.

**Comment by oscarbenjamin** [comment]
It would be good to think of some use for the disjoint union before making any decisions about how to define it. I see some imprecise/contradictory usages of the term.

**Comment by sava-1729** [comment]
> It would be good to think of some use for the disjoint union before making any decisions about how to define it. I see some imprecise/contradictory usages of the term.

So the only use I know of, is in category theory, where the disjoint union is the coproduct in the category of sets.
[https://en.wikipedia.org/wiki/Coproduct](url)

**Comment by sylee957** [comment]
I see there are two definitions of the disjoint union that the 'external' disjoint one is the union made artificially disjoint, and the 'internal' disjoint union is the regular union made of the actually disjoint sets.
https://ncatlab.org/nlab/show/disjoint+union

And I see `DirectProduct` had used internal. So if the naming consistency matters, 
I'm thinking of naming like `ExternalDisjointUnion` or `external_disjoint_union`.

**Comment by sava-1729** [comment]
Ah okay, that sounds good, I'll rename it.
