### ISSUE TITLE
Galois Multiplication (gf_mul) does not work for FiniteFields (FF)

### ISSUE THREAD

**Issue by DLade** [sympy/sympy#18839]
Version: sympy 1.5.1 
Python: 3.7
OS: Linux

`gt.gf_mul([1,0,0,0,1], [1,0,1], 2, FF)`

results in 
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File ".../sympy/polys/galoistools.py", line 554, in gf_mul
>     coeff += f[j]*g[i - j]
> TypeError: unsupported operand type(s) for +=: 'NoneType' and 'int'

but in ZZ it works

`gt.gf_mul([1,0,0,0,1], [1,0,1], 2, ZZ)`
> [mpz(1), mpz(0), mpz(1), mpz(0), mpz(1), mpz(0), mpz(1)]

**Comment by DLade** [comment]
One way to "work around":
`from sympy.polys.domains.finitefield import FiniteField
FF = FiniteField(2)
gt.gf_mul([1,0,0,0,1], [0,0,1,0,1], 2, FF)`

> [SymmetricModularIntegerMod2(1), SymmetricModularIntegerMod2(0), SymmetricModularIntegerMod2(1), SymmetricModularIntegerMod2(0), SymmetricModularIntegerMod2(1), SymmetricModularIntegerMod2(0), SymmetricModularIntegerMod2(1)]

**Comment by jksuom** [comment]
The last argument of `gf_mul` is expected to be a domain. `FF` (as defined in SymPy) is not a domain and it has no valid elements:
```
In [11]: isinstance(FF, Domain)
Out[11]: False

In [12]: FF.zero
             <--- None
```
A domain like `FF(2)` should be used (as the comment above shows).
```
In [13]: isinstance(FF(2), Domain)
Out[13]: True

In [14]: FF(2).zero
Out[14]: SymmetricModularIntegerMod2(0)
```

**Comment by DLade** [comment]
It's a little bit strange, but ok, calling like that:
```
from sympy.polys.domains.finitefield import FiniteField as FF

p = 2
gt.gf_mul([1,0,0,0,1], [1,0,1], p, FF(p))
```

**Comment by DLade** [comment]
I think I got something wrong. 

`gf_mul` already calculates in the finite field of `p` and the domain in my case is `ZZ`.
