### ISSUE TITLE
Typo Error in the SymPy's Architecture Documentation/User Guide

### ISSUE THREAD

**Issue by death-angel-141** [sympy/sympy#18830]
A small typing error relating to SymPy's Architecture documentation under the heading of Basic Usage.

![documentation_bug](https://user-images.githubusercontent.com/61632737/76438296-d07e8c80-63e0-11ea-8668-b051d459ec8b.PNG)

where the 2 should be replaced by 3.

**Comment by sylee957** [comment]
I can't locate where it is, but it looks like a problem indeed.

**Comment by death-angel-141** [comment]
> 
> 
> I can't locate where it is, but it looks like a problem indeed.


It's in the Sympy Architecture Documentation under the heading of Basic Usage


![svlee_share](https://user-images.githubusercontent.com/61632737/76494759-90102480-645b-11ea-990e-564cd7f9094a.PNG)

**Comment by ashutosh1919** [comment]
@death-angel-141 , can you provide URL for the doc? I want to work on this issue.

**Comment by bhpayne** [comment]
Looks like this was fixed -- see https://github.com/sympy/sympy-paper/blob/master/architecture.tex#L101
