### ISSUE TITLE
continuous_domain fails to return the correct domain for log(tan(f(x))

### ISSUE THREAD

**Issue by ThomasHickman** [sympy/sympy#18857]
```
from sympy import *
from sympy.calculus.util import continuous_domain

x = Symbol("x")
print(continuous_domain(log(tan(x)), x, S.Reals))
print(continuous_domain(log(tan(x)**2 + 1), x, S.Reals))
```
Prints:
```
Interval.open(0, pi/2)
Interval(-oo, oo)
```
which is incorrect.

I've had a bit of a digging in the source code, and it looks like the general topic in #11047 is resolved, this will return the correct answer, as the `continuous_domain` determines that `1/log(tan(x))` has no solution (which is incorrect), so returns the wrong value.

**Comment by Arpan612** [comment]
Hello. I am working on this issue and will be sending a PR soon.
