### ISSUE TITLE
Improper docstring in codegen.array_utils.recognize_matrix_expression

### ISSUE THREAD

**Issue by smitgajjar** [sympy/sympy#18891]
Docstring of code example under heading 
*Recognize some more complex traces* 
is not proper here: https://docs.sympy.org/latest/modules/codegen.html#sympy.codegen.array_utils.recognize_matrix_expression
resulting in a broken code formatting.

**Comment by Arpan612** [comment]
`>>>expr = Sum(A[i, j]*B[j, i], (i, 0, N-1), (j, 0, N-1))
>>>cg = parse_indexed_expression(expr)
>>>recognize_matrix_expression(cg)`

This should be the code. The answer must be Trace(A*B).

**Comment by Arpan612** [comment]
>>> expr = Sum(A[i, j]*B[j, i], (i, 0, N-1), (j, 0, N-1))
>>> cg = parse_indexed_expression(expr)
>>> recognize_matrix_expression(cg)

This should be the code. The answer must be Trace(A*B).
We need to rewrite the lines in the alignment above and also make sure it is accessible via the interactive SymPy shell.

**Comment by Sc0rpi0n101** [comment]
There needs to be a blank line between the example and this line
https://github.com/sympy/sympy/blob/70381f282f2d9d039da860e391fe51649df2779d/sympy/codegen/array_utils.py#L1281

**Comment by Arpan612** [comment]
@asmeurer @sylee957 I have used the view page source option of chrome and extracted the HTML of the documentation onto my code editor (Atom). Then I removed the bugs. Could you please tell me how to send a PR for my work? Or should I directly send the HTML file here?

**Comment by sylee957** [comment]
Unfortunately, we don’t edit html files.
You should edit the respective rst or python source file which contains the docstring

**Comment by smitgajjar** [comment]
@Arpan612 That is not how it should be done! Just change the docstring of function `recognize_matrix_expression` codegen/array_utils.py

**Comment by mohitacecode** [comment]
I think the PR will solve the issue.
