### ISSUE TITLE
No usage of constructor argument "name" in CCodeConverter class

### ISSUE THREAD

**Issue by smitgajjar** [sympy/sympy#18906]
In `CCodeConverter` class of `c_parser.py` module, constructer argument "name" is not used in any instance variables or methods. So, it can be removed.

[https://github.com/sympy/sympy/blob/0d77d28d1be6758d8d921068c7d54e32befe11b3/sympy/parsing/c/c_parser.py#L83-L87](https://github.com/sympy/sympy/blob/0d77d28d1be6758d8d921068c7d54e32befe11b3/sympy/parsing/c/c_parser.py#L83-L87)

**Comment by Sc0rpi0n101** [comment]
Sure, if it's not used anywhere, it can be removed

**Comment by smitgajjar** [comment]
Okay, I'll make a PR for that soon!
