### ISSUE TITLE
clarify minlex docstring

### ISSUE THREAD

**Issue by smichr** [sympy/sympy#18915]
It is not clear in in the `minlex` docstring that the result is the *rotation* (and perhaps reversal) giving the smallest elements first that is sought.

Perhaps "Return a tuple obtained by rotations of ``seq`` which puts the smallest elements first. If ``directed`` is..."
```
def minlex(seq, directed=True, is_set=False, small=None):
    """
    Return a tuple where the smallest element appears first; if
    ``directed`` is True (default) then the order is preserved, otherwise
    the sequence will be reversed if that gives a smaller ordering.

    If every element appears only once then is_set can be set to True
    for more efficient processing.

    If the smallest element is known at the time of calling, it can be
    passed and the calculation of the smallest element will be omitted.
```

**Comment by Arpan612** [comment]
def minlex(seq, directed=True, is_set=False, small=None):
" " "
"minlex" is used to put smaller elements first by rotation of the elements in a particular direction. Here our main objective is to place the smallest element possible at the start of the string.

"minlex" remembers a particular order in which elements are to be rotated and this order is followed if directed = 'True', which is by default as well.

If directed = 'False', "minlex" has the option of following the order it remembers or following the reverse order. "minlex" will follow that order which will result in a smaller ordering.

If every element appears only once then is_set can be set to True for more efficient processing.

If the smallest element is known at the time of call, it can be passed and the calculation of the smallest element will be omitted.

@smichr @sylee957 Is it fine?

**Comment by smichr** [comment]
What about this further edit?
```
def minlex(seq, directed=True, is_set=False, small=None):
" " "return a tuple representing the rotation of the sequence in which the lexically smallest elements appear first, e.g. `cba ->acb`.

If ``directed`` is False then the smaller of the sequence and the reversed sequence is returned, e.g. `cba -> abc`.

For more efficient processing, ``is_set`` can be set to True if there are no duplicates in the sequence and ``smallest`` can be given if it is known.
```

**Comment by ashutosh1919** [comment]
@smichr , I have modified docstring for minlex. Please review PR #18949 .

**Comment by ashutosh1919** [comment]
@smichr , Please close this issue if #18949 has resolved it.
