### ISSUE TITLE
(suggestion) Refactor code for NotImplementedError to avoid revealing code in traceback

### ISSUE THREAD

**Issue by smitgajjar** [sympy/sympy#18917]
Consider the following:
<pre>
In [1]: from sympy.parsing.sym_expr import SymPyExpression                                                                                                                                       

In [2]: src = """ 
   ...: char a='2'; 
   ...: """                                                                                                                                                                                      

In [3]: a=SymPyExpression(src, 'c')                                                                                                                                                              
---------------------------------------------------------------------------
NotImplementedError                       Traceback (most recent call last)
<ipython-input-3-a8a3005726bd> in <module>
----> 1 a=SymPyExpression(src, 'c')

~/Desktop/sympy/sympy/parsing/sym_expr.py in __init__(self, source_code, mode)
    112                     elif mode.lower() == 'c':
    113                         if cin:
--> 114                             self._expr = parse_c(source_code)
    115                         else:
    116                             raise ImportError("Clang is not installed, cannot parse C code")

~/Desktop/sympy/sympy/parsing/c/c_parser.py in parse_c(source)
    655         src = converter.parse(source, flags = [])
    656     else:
--> 657         src = converter.parse_str(source, flags = [])
    658     return src

~/Desktop/sympy/sympy/parsing/c/c_parser.py in parse_str(self, source, flags)
    162             for child in self.tu.cursor.get_children():
    163                 if child.kind == cin.CursorKind.VAR_DECL:
--> 164                     self._py_nodes.append(self.transform(child))
    165                 elif (child.kind == cin.CursorKind.FUNCTION_DECL):
    166                     self._py_nodes.append(self.transform(child))

~/Desktop/sympy/sympy/parsing/c/c_parser.py in transform(self, node)
    195                 handler = None
    196             if handler:
--> 197                 result = handler(node)
    198                 return result
    199 

~/Desktop/sympy/sympy/parsing/c/c_parser.py in transform_var_decl(self, node)
    244                         value = Float(val)
    245                     else:
--> 246                         raise NotImplementedError()
    247                     return Variable(
    248                         node.spelling

NotImplementedError:
</pre>

Instead of showing the whole traceback, we can just show suitable error message which indicates that particular feature is not implemented!
Other reason: this exception should be ideally used in case of abstract methods of base classes. 

It can be done in the following way:

- In a separate module, create a new class named `CustomNotImplementedError` extending Exception class
- Import CustomNotImplementedError from that module and raise it wherever required in `try` block
- Show appropriate error message by `print(CustomNotImplementedError)` function in `except` block

(Typical word search of NotImplementedError shows 1475 occurences in the codebase, hence it is an exhaustive task)

**Comment by sylee957** [comment]
What is the advantage of showing a subset of traceback than the full traceback?
I don't think that this is more useful for a debugging purpose, because seeing where the function is being called is often useful.

And as you have noted, even if you change every error, not every commits can follow up the rule in the future and it will be more and more complicated.

**Comment by smitgajjar** [comment]
I agree with your points, but I thought that in case, sympy is used in some production-level environment, it will be better not to show traceback, which is irrelevant for the end-user. (Also, if he/she doesn't understand the error, then he will feel that something is wrong with code!) 

Anyways, your reasons seem more appropriate here, since sympy is mostly useful for educational and research purposes. 
Hence, closing the issue!
