### ISSUE TITLE
No option to use Common Sub-expression Detection in 'lambdify'

### ISSUE THREAD

**Issue by fh9g12** [sympy/sympy#18916]
This is less an issue and more a question / potential lack of understanding on my part. And I thought this was probably the best Forum for it....

A bit of context - I am using Sympy to build up the equations of motion of a flexible multi-link manipulator. As part of this I have matrices with a lot of sin / cos evaluations. 

When numerically integrating my system that largest bottleneck was in evaluating the generated 'Lambda expressions' of these matricies. Below is a snippet of the %prun output showing the lambda bottleneck

![image](https://user-images.githubusercontent.com/15157018/77167117-4a7fd700-6aad-11ea-99e5-5f7e447db02b.png)

To resolve this I have 'monkey patched' the 'doprint' method in the _EvaluatorPrinter class (found in the lambdify.py file) with the following method. The additional lines (in comment blocks) use the 'cse' method to split out the common sub expressions, I then add this to the generated function definition

`
def doprint(self, funcname, args, expr):
        """Returns the function definition code as a string."""
        from sympy import Dummy,cse,Symbol

        funcbody = []

        if not iterable(args):
            args = [args]

        argstrs, expr = self._preprocess(args, expr)

        ## --------------- Addition -----------------
        replacments, exprs = cse(expr,symbols=(Symbol(f'rep_{i}')for i in range(100)))
        expr = exprs[0]
        ## --------------- Addition -----------------

        # Generate argument unpacking and final argument list
        funcargs = []
        unpackings = []

        for argstr in argstrs:
            if iterable(argstr):
                funcargs.append(self._argrepr(Dummy()))
                unpackings.extend(self._print_unpacking(argstr, funcargs[-1]))
            else:
                funcargs.append(argstr)
        arg_vars = ', '.join(funcargs)
        funcsig = f'def {funcname}({arg_vars}):'

        # Wrap input arguments before unpacking
        funcbody.extend(self._print_funcargwrapping(funcargs))

        funcbody.extend(unpackings)

        ## --------------- Addition -----------------
        for variable, expression in replacments:
            funcbody.append(f'{variable} = {expression}')
        ## --------------- Addition -----------------

        funcbody.append('return ({})'.format(self._exprrepr(expr)))

        funclines = [funcsig]
        funclines.extend('    ' + line for line in funcbody)

        return '\n'.join(funclines) + '\n'
` 

This makes some of my lambda functions up to 7 times faster, as shown (rather qualativly) in the image below
 
![image](https://user-images.githubusercontent.com/15157018/77167385-db56b280-6aad-11ea-8fb5-8e544f4e5e1b.png)

I couldn't find a simple way of doing this within the current sympy framework, have I missed a trick, or is this something that could be consdiered for inclusion? I understand for large matricies cse is unrelible, but for small to meduim sized matrices it seems like a easy win in terms of performnace?

**Comment by moorepants** [comment]
This is a desired feature. I think the main hurdle was that lambdify produced lambda functions and we'd need to produced proper functions to take advantage of intermediate expressions. Your monkey patch does this, but to make it universal there is likely some more work to be done for a patch to introduce this feature.

**Comment by asmeurer** [comment]
We already produce proper functions, so this shouldn't be too hard to implement.

**Comment by fh9g12** [comment]
Is it worth me converting this into a pull request with the addtions below, or is this approach a little far off what a proper implementation would look like?

- use an actual infinite generator sequence and not one bounded to 100
- have a 'cse' key word argument in the lambdify method (default false), that when true would do the above reduction

**Comment by moorepants** [comment]
If you are willing to give it a shot it would be nice to see this. I'd start by seeing if your patch works with any of the lambdify related tests and then setting up some tests that would ensure that lambdify with and without cse give the same results for the different types of lambdify inputs.

**Comment by bjodah** [comment]
OK, so this is hopefully resolved in gh-21546, feel free to re-open / open a new issue if I'm mistaken.
