### ISSUE TITLE
SinglePatternODESolver class can be inherited only by solvers of order 1 ODE

### ISSUE THREAD

**Issue by tnzl** [sympy/sympy#18926]
At present, all the pattern matching based single ODE solvers that have been refactored into solver classes are for the first-order ODEs only.
https://github.com/sympy/sympy/blob/c770bc7ede4c22962bacce96bb2388e5df1c47b7/sympy/solvers/ode/single.py#L233-L234 
This condition blocks the implementation of any second or higher-order single ODE solvers based on a pattern matching. This condition should be present in the `_verify` function of first-order solvers.
Or is it the case that `SinglePatternODESolver` is only meant for order 1 ODEs and I am missing something?

**Comment by oscarbenjamin** [comment]
The `SinglePatternOdeSolver` class is still a work in progress. It is expected that it will need to be modified as new subclasses are added.

**Comment by tnzl** [comment]
Thanks for the reply. I will open a PR to move condition to check order for `SinglePatternODESolver` to `_verify` and remove it from `_matches`.
