### ISSUE TITLE
ntheory/primetest/is_extra_strong_lucas_prp edge case

### ISSUE THREAD

**Issue by sukop** [sympy/sympy#18921]
In the cited paper "Frobenius Pseudoprimes" p. 876, the second condition on being an "extra strong" Lucas pseudoprime reads:

    V_{2^ts} ≡ 0 mod n, where 0 ≤ t < r-1

However, the code for [is_extra_strong_lucas_prp()](https://github.com/sympy/sympy/blob/126485017c60e249c21dd68c46f70ea7b0584e1e/sympy/ntheory/primetest.py#L401) reads:

    if V == 0:
        return True
    for r in range(1, s):
        V = (V*V - 2) % n
        if V == 0:
            return True

When `V == 0` and `s == 1`, by the above definition ("s" is "r" there), the number should not be declared as a pseudoprime. Perhaps the code should read as:

    for r in range(1, s):
        if V == 0:
            return True
        V = (V*V - 2) % n

**Comment by Arpan612** [comment]
Hi, I am working on this issue.

**Comment by Arpan612** [comment]
@sukop I have done some work on this code. Could you please send me a link to the cited paper you are talking about?

**Comment by sukop** [comment]
It's [the one](http://www.ams.org/journals/mcom/2001-70-234/S0025-5718-00-01197-2/) in the docstring [references](https://github.com/sympy/sympy/blob/126485017c60e249c21dd68c46f70ea7b0584e1e/sympy/ntheory/primetest.py#L421). Thanks!

**Comment by Arpan612** [comment]
I think using this should work

`for r in range(1, s):
    if V == 0:
        return True
    V = (V*V - 2) % n`

I wanted to implement something more but it is throwing an error. I will submit a PR for this bit for now as this looks correct. If I am able to implement the additional bit, I will submit another PR.

**Comment by sukop** [comment]
Thank you!

**Comment by Arpan612** [comment]
Glad to help! :)
