### ISSUE TITLE
90 degree rotation of matrix elements

### ISSUE THREAD

**Issue by sylee957** [sympy/sympy#18948]
I think that transpose matrix elements clockwise is often given as a coding test problem.

![image](https://user-images.githubusercontent.com/34944973/77502452-42091100-6e9e-11ea-817a-af5e34b93b29.png)

I see lots of people approach this problem in naive or overly complicated way.

But I have found an article that gives the most rigorous solution about this.

https://blogs.sas.com/content/iml/2013/10/18/rotating-matrices.html

It is by permuting the rows and applying the usual transposition. (And rotating anticlockwise can also be done in similar manner by permuting the columns instead of rows)

```python3
>>> A = MatrixSymbol('A', 4, 4)
>>> A = A.as_explicit()
>>> A
Matrix([
[A[0, 0], A[0, 1], A[0, 2], A[0, 3]],
[A[1, 0], A[1, 1], A[1, 2], A[1, 3]],
[A[2, 0], A[2, 1], A[2, 2], A[2, 3]],
[A[3, 0], A[3, 1], A[3, 2], A[3, 3]]])
>>> A[::, ::-1].T
Matrix([
[A[0, 3], A[1, 3], A[2, 3], A[3, 3]],
[A[0, 2], A[1, 2], A[2, 2], A[3, 2]],
[A[0, 1], A[1, 1], A[2, 1], A[3, 1]],
[A[0, 0], A[1, 0], A[2, 0], A[3, 0]]])
>>> A[::-1, ::].T
Matrix([
[A[3, 0], A[2, 0], A[1, 0], A[0, 0]],
[A[3, 1], A[2, 1], A[1, 1], A[0, 1]],
[A[3, 2], A[2, 2], A[1, 2], A[0, 2]],
[A[3, 3], A[2, 3], A[1, 3], A[0, 3]]])
```

And it even works with rectangular matrices

```python3
>>> A = MatrixSymbol('A', 3, 4).as_explicit()
>>> A
Matrix([
[A[0, 0], A[0, 1], A[0, 2], A[0, 3]],
[A[1, 0], A[1, 1], A[1, 2], A[1, 3]],
[A[2, 0], A[2, 1], A[2, 2], A[2, 3]]])
>>> A[::, ::-1].T
Matrix([
[A[0, 3], A[1, 3], A[2, 3]],
[A[0, 2], A[1, 2], A[2, 2]],
[A[0, 1], A[1, 1], A[2, 1]],
[A[0, 0], A[1, 0], A[2, 0]]])
>>> A[::-1, ::].T
Matrix([
[A[2, 0], A[1, 0], A[0, 0]],
[A[2, 1], A[1, 1], A[0, 1]],
[A[2, 2], A[1, 2], A[0, 2]],
[A[2, 3], A[1, 3], A[0, 3]]])
```

I think that we can have an API like 
https://mathworks.com/help/matlab/ref/rot90.html https://docs.scipy.org/doc/numpy/reference/generated/numpy.rot90.html

**Comment by Arpan612** [comment]
I am working on it sir.

**Comment by Arpan612** [comment]
@sylee957 Sir, the objective is to make a function for executing the 90-degree rotation task right?

**Comment by sylee957** [comment]
Yes. I think that you can mimic the numpy API (except for axis if it is only for 2d array)

**Comment by iammosespaulr** [comment]
@Arpan612 hey mate,are you done with this ?

**Comment by iammosespaulr** [comment]
@sylee957 I can do this ... shall I add rot90 as a function and r90 as a property as well ?

**Comment by Arpan612** [comment]
@iammosespaulr Hi friend, I am working on it. I humbly request you to solve some other issues as I claimed it first.

**Comment by iammosespaulr** [comment]
@Arpan612 sure ... It's just that it's been 5 hours ... I'll submit a pr ... you do too ... the sooner the better ... 🥂

**Comment by Arpan612** [comment]
Could you please solve some other issue as I have already started the work here?

**Comment by iammosespaulr** [comment]
MKay ... I haven't submitted a pr ... go ahead ... I'll work on other issues 😄

**Comment by sylee957** [comment]
The feedback I can give about the commit is that you can better define k=1, k=-1 to define clockwise and anticlockwise rotation.
And you can just apply the rotation iteratively if k=2 or more. 
(I think that you only need to consider k=0, 1, 2, 3 because the rotation parameter can be taken into modulo-4)

**Comment by iammosespaulr** [comment]
Ohhh thanks @sylee957  ... I'll go ahead with that then.

**Comment by iammosespaulr** [comment]
> The feedback I can give about the commit is that you can better define k=1, k=-1 to define clockwise and anticlockwise rotation.
> And you can just apply the rotation iteratively if k=2 or more.
> (I think that you only need to consider k=0, 1, 2, 3 because the rotation parameter can be taken into modulo-4)

Question ... what bout -2 , -3 and so on ... would iterative rotation in the anticlockwise direction be useful ?

**Comment by sylee957** [comment]
You can fist take modulo operation like `-2 % 4`, `-3 % 4` and they simply fall into category of rotating clockwise 2 or 1 times.

**Comment by iammosespaulr** [comment]
Ha yes!! They do ... I'll add them too

**Comment by sylee957** [comment]
I also think that there is no need to actually rotate two times for `k=2`, but you can use `A[::-1, ::-1]`

**Comment by Arpan612** [comment]
@sylee957 Sir, since I claimed this issue first, please give me the first chance to submit a PR.

**Comment by sylee957** [comment]
Unfortunately, we don’t assign issues to specific person, but someone who come up with working patch first.
If the patch gets stalled, you can grab on. But in my opinion, you have other PRs to complete.

**Comment by Arpan612** [comment]
@sylee957 Okay Sir.Please review my PR.

**Comment by sylee957** [comment]
I think that you should agree on who’s going to continue the work or not

**Comment by sylee957** [comment]
Or maybe I can just deal with the conflict by making a new patch myself adding the author information of you too if you request

**Comment by iammosespaulr** [comment]
@sylee957 I've added the tests as well ...

**Comment by iammosespaulr** [comment]
@sylee957 I only took this issue because it was stagnant for over 5 hours ... I leave it up to you, to choose which PR to merge ... 😄

**Comment by Arpan612** [comment]
@iammosespaulr Oh, don't worry. There are many issues open for over a year.

**Comment by Arpan612** [comment]
> MKay ... I haven't submitted a pr ... go ahead ... I'll work on other issues

@iammosespaulr So may I work on the issue please?

**Comment by iammosespaulr** [comment]
>  If the patch gets stalled, you can grab on. But in my opinion, you have other PRs to complete.
@Arpan612 you might wanna consider this tho ...

**Comment by Arpan612** [comment]
I think it is best that @sylee957 sir does this and gives the credit to both of us as we both have done the work. What say? @iammosespaulr 

> Or maybe I can just deal with the conflict by making a new patch myself adding the author information of you too if you request
