### ISSUE TITLE
Addition of tensor and matrix with same shape

### ISSUE THREAD

**Issue by Davide-sd** [sympy/sympy#18956]
Little example:

```
import sympy as sp
A = sp.Array([[1, 2], [3, 4]])
B = sp.eye(2)
```

```
A + B

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-32-151064de832d> in <module>
----> 1 A + B

/usr/local/lib/python3.7/dist-packages/sympy/tensor/array/ndim_array.py in __add__(self, other)
    370 
    371         if not isinstance(other, NDimArray):
--> 372             raise TypeError(str(other))
    373 
    374         if self.shape != other.shape:

TypeError: Matrix([[1, 0], [0, 1]])
```

Whereas:

```
B + A
```

works as expected.

**Comment by oscarbenjamin** [comment]
Instead of raising `TypeError` it should return `NotImplemented`. Both examples should raise though so `Matrix.__add__` should also return `NotImplemented`.

**Comment by sylee957** [comment]
I think that one of the problem in the sympy codebase are there are so many different array classes inter-operating well.
I may have different ideas like `Matrix + Array` should always return `Array` if it is two dimensional.

**Comment by sidhu1012** [comment]
> Instead of raising `TypeError` it should return `NotImplemented`. Both examples should raise though so `Matrix.__add__` should also return `NotImplemented`.

It should return NotImplemented or shall give NotImplementedError?

**Comment by sylee957** [comment]
NotImplemented is a reserved method for builtin operator overrides and cannot be used interchangably with NotImplementedError
https://docs.python.org/3/library/constants.html#NotImplemented

**Comment by sidhu1012** [comment]
In matrix __add__ method it shows matrix like objects can be added which implies matrix + array = matrix
Then similarly array + matrix shouldn't be array?

**Comment by sylee957** [comment]
I'd not be against defining addition between matrix and arrays.
However, I'd not agree on if matrix + array and array + matrix should return different types. They should be symmetric.

**Comment by sidhu1012** [comment]
> However, I'd not agree on if matrix + array and array + matrix should return different types. They should be symmetric.

Till then they should return NotImplemented then.

**Comment by sidhu1012** [comment]
@oscarbenjamin @sylee957 Pls check the PR
