### ISSUE TITLE
 Buy with sympify 

### ISSUE THREAD

**Issue by abhinav28071999** [sympy/sympy#18967]
when sympify is used on field elements it converts them to ZZ.
`a = FF(9221)`
`sympify(a(30000))` gives `2337` 
and strangely `sympify(a(9754254))` gives `-1564`.
Is this a bug?

**Comment by jksuom** [comment]
> it converts them to ZZ.

It converts them to Integers:
```
>>> K = FF(9221)
>>> a = K(30000)
>>> a
SymmetricModularIntegerMod9221(2337)
>>> sympify(a)
2337
>>> type(_)
<class 'sympy.core.numbers.Integer'>
>>> K(2337) == a
True
```
`sympify` will convert a SymmetricModularIntegerMod9221 to its Integer representative having the smallest absolute value, so it can also be negative. That can be used to regenerate the modular integer. If one wants to use only non-negative representatives, keyword `symmetric=False` must be set.
