### ISSUE TITLE
Inconsistencies in draw function of beam class

### ISSUE THREAD

**Issue by Psycho-Pirate** [sympy/sympy#18964]
In Sympy continuum mechanics Beam Class, the draw function produces wrong diagrams.
`E, I = symbols('E, I')`
`b = Beam(10, E, I)`
`b.apply_support(0,'pin')`
`b.apply_support(8.3, 'roller')`
`b.apply_load(-1, 2, 2)`
`b.apply_load(-2, 4, -2)`
`b.apply_load(3, 6.3, -1)`
`b.draw().show()`
![image](https://user-images.githubusercontent.com/50932406/77707099-26ab1c80-6fea-11ea-9325-0d6f0f20a310.png)

Here the point load is positive and parabolic load is negative but they have same directions.
`b.apply_load(1, 2, 2)`
`b.apply_load(2, 4, -2)`
`b.apply_load(-3, 6.3, -1)`

![image](https://user-images.githubusercontent.com/50932406/77707131-39bdec80-6fea-11ea-9233-ed654da90e11.png)

Changing the signs of all the loads changes the direction of unit load and moment load but parabolic load acts on the same direction.
There is also an inconsistency with sign convention of point load and moment load.
See [this](https://groups.google.com/forum/#!msg/sympy/MhRJ1Ahl8i0/roNHvKt6AQAJ).
 Upward forces and clockwise moments should have same signs(positive or negative) as discussed [here](https://github.com/sympy/sympy/issues/18045). 
The draw function assigns downward direction to positive point loads and clockwise direction to positive moment loads, regardless of the sign convention user chooses.

**Comment by moorepants** [comment]
The draw function has to assume a sign convention for forces and moments, independent conventions for each. It might be better to have a documented default sign conventions for the draw function and also let the user optionally set them to the sign conventions they've chosen to describe their problem in.

**Comment by Psycho-Pirate** [comment]
I think we can rely on the signs of reaction forces as they will always act along positive Y direction.
So all the forces with same signs as the reaction forces must act along positive Y and all the other forces should act in the opposite direction. What do you suggest @moorepants

**Comment by Psycho-Pirate** [comment]
What do you suggest @moorepants ?

**Comment by moorepants** [comment]
It looks like the parabolic load should be on the bottom of the beam for the second case.

**Comment by Psycho-Pirate** [comment]
> It looks like the parabolic load should be on the bottom of the beam for the second case.

Yes, there are three errors basically. 
1. The parabolic and ramp loads do not change direction even when signs are changed
2. The point loads and moment act along wrong directions
3. The draw function assumes a sign convention (positive point loads always act along negative Y)
irrespective of what the user chose.


> I think we can rely on the signs of reaction forces as they will always act along positive Y direction.
> So all the forces with same signs as the reaction forces must act along positive Y and all the other forces should act in the opposite direction.

What do you think about this?

**Comment by moorepants** [comment]
All of the plotting and drawing for the beam has to assume  that a positive force/moment is in the direction of the positive y/z coordinate axes, for example.

**Comment by Psycho-Pirate** [comment]
> All of the plotting and drawing for the beam has to assume that a positive force/moment is in the direction of the positive y/z coordinate axes, for example.

I think that will restrict the user to choose a certain sign convention while using the draw function.
What I am suggesting is that we can check signs of reaction forces and use that to define the sign which will produce a +y load.
As we know a reaction force will always act in +y direction, If it is negative, all negative loads act along +y and so on

**Comment by moorepants** [comment]
Whatever is chosen just needs to be documented clearly so the user understands. I personally think it would be more confusing if the diagram changes directionality based on the sign of specific forces. Sometimes you will have two or more reaction forces and they have different signs. So I'm not sure that will work consistently.

**Comment by Psycho-Pirate** [comment]
> Whatever is chosen just needs to be documented clearly so the user understands. I personally think it would be more confusing if the diagram changes directionality based on the sign of specific forces. Sometimes you will have two or more reaction forces and they have different signs. So I'm not sure that will work consistently.

I see. I will start by adding documentation regarding this and also fixing the problem with parabolic and ramp loads directions.

**Comment by nopria** [comment]
Issues are still present, I investigated and I believe I found what the problem exactly is and proposed a solution here:
https://github.com/sympy/sympy/issues/20204

Please jump in the discussion.
