### ISSUE TITLE
System of modular linear equations

### ISSUE THREAD

**Issue by abhinav28071999** [sympy/sympy#18966]
Does sympy support solving a system of modular linear equations?

**Comment by abhinav28071999** [comment]
I think  that sympy probably does not support this. Sympy also does not allow matrix elements to be fields.
When `A = Matrix([FF(17)(5)])` then `A[0]` gives `5` instead of `SymmetricModularIntegerMod17(5)`.

**Comment by sylee957** [comment]
There is `inv_mod` for matrix.

**Comment by abhinav28071999** [comment]
Got it but the final output of `inv_mod` is not modulo `n`, that is probably some minor bug??

**Comment by sylee957** [comment]
What do you mean by the output is not modulo n?
If the output integers exceed the range of 0-n, it can be a bug

**Comment by abhinav28071999** [comment]
i checked it's working. My code was multiplying the inverse with another matrix and i got confused. I  checked the inv_mod and it's working.
