### ISSUE TITLE
The solve_for_reaction_loads function produces wrong results for triangular loads 

### ISSUE THREAD

**Issue by Psycho-Pirate** [sympy/sympy#18979]
In sympy's physics continuum mechanics beam class, the `solve_for_reaction_loads()` gives wrong results when triangular load is applied.
See this example
![image](https://user-images.githubusercontent.com/50932406/77799320-895bf100-709a-11ea-8b5e-1c7d459e2a23.png)
`b = Beam(6, E, I)`
`b.apply_support(0,'pin')`
`b.apply_support(6, 'roller')`
`b.apply_load(-20, 0, 1, 6)`
`b.draw().show()`
`b.solve_for_reaction_loads(R_0, R_6)`
`print(b.reaction_loads)`
`{R_0: 120, R_6: 240}`
It gives 120 and 240 as reaction loads

Here is the correct solution:
![image](https://user-images.githubusercontent.com/50932406/77799913-caa0d080-709b-11ea-9456-4101a971e0a7.png)
![image](https://user-images.githubusercontent.com/50932406/77799941-d8eeec80-709b-11ea-8f90-3543f3820e92.png)

**Comment by moorepants** [comment]
Can you paste complete functioning code so it is easier for others to run and reproduce your results?

**Comment by Psycho-Pirate** [comment]
`from sympy import *`
`from sympy.physics.continuum_mechanics.beam import Beam`
`E, I, R_0,R_6 = symbols('E, I, R_0, R_6')`
`b = Beam(6, E, I)`
`b.apply_support(0, 'pin')`
`b.apply_support(6, 'roller')`
`b.apply_load(-20, 0, 1, 6)`
`b.solve_for_reaction_loads(R_0, R_6)`
`print(b.reaction_loads)`
@moorepants

**Comment by moorepants** [comment]
Curious if it works if you only use apply_load, instead of apply_support?

**Comment by moorepants** [comment]
I also edited your last comment with a better markdown syntax.

**Comment by Psycho-Pirate** [comment]
> I also edited your last comment with a better markdown syntax.

Thanks.


> Curious if it works if you only use apply_load, instead of apply_support?

```>>> from sympy import *
>>> from sympy.physics.continuum_mechanics.beam import Beam
>>> E, I, Ay, By = symbols('E, I, Ay, By')
>>> b = Beam(6, E, I)
>>> b.apply_load(-20, 0, 1, 6)
>>> b.apply_load(Ay, 0, -1)
>>> b.apply_load(By, 6, -1)
>>> b.solve_for_reaction_loads(Ay, By)
>>> print(b.reaction_loads)
{Ay: 120, By: 240}```

Still the same error

**Comment by moorepants** [comment]
I vaguely recall that there could be confusion about what the F in `F*<x-a>^1` might mean. I guess it is the slope of the force per distance ramp function, but you can confuse it with the maximum load at the end of the beam. Double check that.

**Comment by moorepants** [comment]
This example https://docs.sympy.org/latest/modules/physics/continuum_mechanics/beam_problems.html#example-11 may help you see the relationship.

**Comment by Psycho-Pirate** [comment]
> I vaguely recall that there could be confusion about what the F in `F*<x-a>^1` might mean. I guess it is the slope of the force per distance ramp function, but you can confuse it with the maximum load at the end of the beam. Double check that.

Yes, replacing it with the slope gives the correct results. But there is no documentation for that.
In the beam docstrings [here](https://docs.sympy.org/latest/modules/physics/continuum_mechanics/beam.html#sympy.physics.continuum_mechanics.beam.Beam.apply_load), it says magnitude. Also in [example 3](https://docs.sympy.org/latest/modules/physics/continuum_mechanics/beam_problems.html#example-3), the magnitude is taken for ramp load, the solution is wrong because of that.

**Comment by moorepants** [comment]
This needs to be documented better, for sure. I think there are some prior open issues or mailing lists posts were this was discussed. I recommend browsing for those, reading them, and then opening a pull request to improve the documentation if you would like to.

**Comment by moorepants** [comment]
See: https://github.com/sympy/sympy/issues/15981

**Comment by moorepants** [comment]
Closing as this is a duplicate of #15981

**Comment by Psycho-Pirate** [comment]
> This needs to be documented better, for sure. I think there are some prior open issues or mailing lists posts were this was discussed. I recommend browsing for those, reading them, and then opening a pull request to improve the documentation if you would like to.

Sure I will open a pr fixing this as well as example 3.

**Comment by Psycho-Pirate** [comment]
I don't want to bug you with this, but please go through my gsoc proposal. I have posted it [here](https://groups.google.com/forum/#!topic/sympy/ZBzmefbBFSU) on the mailing list. I would really appreciate some feedback! Sorry for any inconvenience caused. @moorepants

**Comment by moorepants** [comment]
@Psycho-Pirate I will have a look at people's proposals before submission only if I have extra time. They will all be reviewed after submission by the SymPy mentors for sure.
