### ISSUE TITLE
[Feature Request]:Calculate GIC in logic expression.

### ISSUE THREAD

**Issue by stevenleeS0ht** [sympy/sympy#18982]
GIC means gate-input-cost, it equals to how many wires entering gates in the logic circuit.

**Comment by sylee957** [comment]
I think that you can recursively count all the nodes in the trees.
```
A, B, C, D = symbols('A:D')
expr = B & D | A & ~B & C | A & ~C & ~D

def gic(expr):
    return len(expr.args) + sum(gic(x) for x in expr.args)

gic(expr)
```

**Comment by Arpan612** [comment]
@sylee957 Can you mention the file where we can implement this?

**Comment by sylee957** [comment]
Unfortunately, you should provide some statement that this can be useful for some symbolic 
boolean logic computation, or it is just going to serve a purpose of introducing a trivial method that computes something that can be tedious by hand.

**Comment by oscargus** [comment]
I have added this as a method `gateinputcount` in #21973. I can see the usefulness as this is often used as a cost measure for the complexity of a digital circuit.

**Comment by sylee957** [comment]
I thought that we could have a public API like `count_ops` that counts the function symbols + variables from the expression tree for more general use (if it was not implemented before yet)
I think that you don't need the restriction wrt to the class of expressions, because I think that the boolean expression that 'makes sense' can still use unrestricted function because they would purely be composed of boolean operations.

**Comment by oscargus** [comment]
There is a significant difference here that motivates the use of a special function.

For example, `a + b` is one add operation so `count_ops` should return one. `a & b` is clearly one and operation. However, the cost commonly associated with it is the gate input count: two. The reason one prefer to use gate input count is that it provides a measure of the total number of pins needed for a PCB. It may not be a very useful measure nowadays, as things tend to be integrated, but it has lived on to be a first-order approximation of the complexity of a boolean expression. 

So it is simply a slightly different cost metric that is not straightforwardly mapped to `count_ops` (and even if it was, it would be convenient to have a separate function for it).
