### ISSUE TITLE
Possibly incorrect limit related to Stirling's formula

### ISSUE THREAD

**Issue by daschuel** [sympy/sympy#18992]
The following integral, related to Stirling's Formula, gives different results based on different definitions of the variable:

var('x')
print(limit(x/((factorial(x)**(1/x))), x, oo))
E

var('n', positive=True, integer=True)
print(limit(n/((factorial(n)**(1/n))), n, oo))
oo

According to [Wikipedia](https://en.wikipedia.org/wiki/E_(mathematical_constant)#Asymptotics), E should be the correct answer. I wasn't sure whether this *should* be different if the variable is assumed to be an integer, but the appearance of factorial (rather than gamma) in the Wikipedia article leads me to believe that going through integer values should give the same result.

This may be redundant with some of the similar issues listed below, but none are the same exact attempted limit, so I'll post this, but feel free to close it if it's too redundant.

**Comment by sachin-4099** [comment]
Closing in favour of: https://github.com/sympy/sympy/pull/19292
