### ISSUE TITLE
Wrong matrix element fetched from BlockMatrix

### ISSUE THREAD

**Issue by jlherren** [sympy/sympy#18996]
Given this code:
```
from sympy import *
n, i = symbols('n, i', integer=True)
A = MatrixSymbol('A', 1, 1)
B = MatrixSymbol('B', n, 1)
C = BlockMatrix([[A], [B]])
print('C is')
pprint(C)
print('C[i, 0] is')
pprint(C[i, 0])
```
I get this output:
```
C is
⎡A⎤
⎢ ⎥
⎣B⎦
C[i, 0] is
(A)[i, 0]
```
`(A)[i, 0]` is the wrong here. `C[i, 0]` should not be simplified as that element may come from either `A` or `B`.

**Comment by sylee957** [comment]
I was aware of the problem that the coordinates were loosely handled even if the matrix had symbolic dimensions
I also think that `C[3, 0]` should be undefined because there is no guarantee that n is sufficiently large to contain elements.

**Comment by jlherren** [comment]
`C[3, 0]` should just stay unevaluated, since it might be valid (I assume that's what you mean by 'undefined'). It should be possible to handle some cases properly, for example `C[n, 0]` should return `B[n - 1, 0]`.

If I get some time I might have a go at it, seems to be a nice first PR.
