### ISSUE TITLE
can't import sympy

### ISSUE THREAD

**Issue by Electrowolf2** [sympy/sympy#19003]
Hi everyone

I am quite new to this python language, I am using ironpython and install sympy package for it, with no apparent problem, but when I try to import sympy to my code I get the following error

![imagen](https://user-images.githubusercontent.com/56281145/77843294-ec13c200-7158-11ea-8a00-310e5df54440.png)

I really don't know what to do or how to repair it, I would really appreciate your help

**Comment by sylee957** [comment]
Sympy had deprecated support for python 2.7 after last release. What is your sympy version? Does ironpython support python3?

**Comment by iammosespaulr** [comment]
apparently ironpython3 is not recommended for use and ironpython2 isn't deprecated .So it's mostly not an issue on sympy's part.

**Comment by oscarbenjamin** [comment]
The current release of sympy (1.5) should work on Python 2. If it does not then that is a bug and it is an issue for sympy.

**Comment by Electrowolf2** [comment]
Thanks for your quick responses, the version of ironpython that I installed is 2.7.9 and the version of the sympy that I installed using pip is 1.5.1.

I didn't really understand very well what I should do, whether to use a previous version of ironpython or a previous version of sympy ... or really what they suggest, the point is that what I would like is to use ironpython together with sympy , but still do not succeed, I reiterate my thanks for your help.

**Comment by oscarbenjamin** [comment]
SymPy 1.5.1 should work with Python 2.7. It does work with CPython 2.7. If it does not work with IronPython then maybe that is a bug in IronPython (I'm not sure).

To get something working you could try different versions of IronPython or different versions of sympy. I don't know whether either of those would make a difference.

**Comment by Electrowolf2** [comment]
Hello everyone again, I greet you with the happy news that you have already solved the problem, although I still don't know how well the solution will go, but for now I have to explore it.

Taking your comments into account I provided different versions of sympy, until version 1.1.1 works without any kind of error, so I will have to test it to see if it works for my purposes.

Again, thank you very much for your support and I hope you will help me in my next doubts that I will be posting, believe me, hehe, greetings to all.

**Comment by oscarbenjamin** [comment]
Sorry it is unclear to me what you mean.

Which versions of sympy work with IronPython 2.7?

Which versions do not work with IronPython 2.7?

**Comment by Electrowolf2** [comment]
from the most current sympy 1.5 to the sympy 1.2 version, all those gave me errors when trying to import, the only version that did not give me errors and with which I am working and so far has not given me problems is 1.1.1, with ironpython version 2.7

**Comment by eagleoflqj** [comment]
Just made a Dockerfile that can run sympy 1.4 with the latest development of ironpython3.
```Dockerfile
FROM mcr.microsoft.com/dotnet/sdk:6.0
RUN apt update && apt install -y dos2unix fakeroot libc-dev libunwind8
RUN git clone --depth=1 https://github.com/IronLanguages/ironpython3
WORKDIR ironpython3
RUN pwsh make.ps1 && pwsh make.ps1 package && cp -r Src/StdLib/Lib bin/Release/net6.0/
RUN bin/Release/net6.0/ipy -m ensurepip && bin/Release/net6.0/ipy -m pip install sympy==1.4
CMD bin/Release/net6.0/ipy
```
As ironpython's development continues, newer version of sympy can be supported automatically.
