### ISSUE TITLE
problems expanding a series

### ISSUE THREAD

**Issue by iammosespaulr** [sympy/sympy#19010]
ideally expanding [ (1 + x)<sup>2/3</sup> = x<sup>2/3</sup> + (2/3) x<sup>1</sup> + 1/3 x<sup>0</sup>](http://www.wolframalpha.com/input/?i=(1%20%2Bx%20)%5E%202%2F3)
but sympy doesn't do that.
```python3
>>> expand_func((1 + x)**(2/3))
(x + 1)**0.666666666666667
>>> ((1 + x)**(2/3)).expand(func=True)
(x + 1)**0.666666666666667
>>> 
```

**Comment by oscarbenjamin** [comment]
Firstly you should use Rational rather than Float e.g.:
```
In [3]: ((1 + x)**(S(2)/3)).expand()                                                                                              
Out[3]: 
       2/3
(x + 1)   
```
Secondly I don't know why you think that should expand to a finite sum of terms. The formula you showed is clearly incorrect (try x=0).

**Comment by iammosespaulr** [comment]
@oscarbenjamin sorry that seems to be an oversight on my part. It came up as I was working on another issue, I forgot to verify it 😅 .

**Comment by iammosespaulr** [comment]
it happens to be [(1 + x)<sup>2/3</sup> = 1 + (2/3) x<sup>1</sup> - (1/9) x<sup>2</sup> + (4/81) x<sup>3</sup> - (7/243) x<sup>4</sup> + ... ](http://www.wolframalpha.com/input/?i=(1%20%2B%20x%20)%5E(2%2F3))
