### ISSUE TITLE
QRdecomposition() returning non-square results

### ISSUE THREAD

**Issue by jrexmo** [sympy/sympy#19017]
The following gives us two matrices that do multiply to the original, but are not square:
```python 
>>> from sympy.matrices import eye
>>> A = eye(3, 4)
>>> B = A.T*A
>>> B.QRdecomposition()
(Matrix([
[1, 0, 0],
[0, 1, 0],
[0, 0, 1],
[0, 0, 0]]), Matrix([
[1, 0, 0, 0],
[0, 1, 0, 0],
[0, 0, 1, 0]]))
```
It looks like this is the result of padding with extra rows/columns - this algorithm seems somewhat non-standard, but I could be mistaken. In addition, this bug seems to be a bit different than #4520. Would it be ridiculous to try to reimplement QR-decomposition here, I really don't know why extra rows and columns are being padded on?

**Comment by sylee957** [comment]
I don't think that the result is wrong. You can pad an extra column that is orthogonal to rest of the columns in Q, and pad zero rows below R.
The reason I had made them to be non-square for rank deficient cases is that it is economical for running gram-schmidt method.

And this is also how Wolfram have made their QRDecomposition to be.
