### ISSUE TITLE
How to generate results for queries like `P(Eq(X(j), 2), Eq(X(1), i))`?

### ISSUE THREAD

**Issue by czgdp1807** [sympy/sympy#19012]
In the query, `P(Eq(X(j), 2), Eq(X(1), i))`, X represents a Markov chain(discrete/continuous). Here, i and j are symbols.
Currently,
```python
>>> from sympy import symbols
>>> i, j = symbols('i, j', integer=True)
>>> P(Eq(X[j], 2), Eq(X[1], i))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/czgdp1807ssd/sympy_project/sympy/sympy/stats/stochastic_process_types.py", line 196, in __getitem__
    if time not in self.index_set:
  File "/home/czgdp1807ssd/sympy_project/sympy/sympy/sets/sets.py", line 672, in __contains__
    raise TypeError('did not evaluate to a bool: %r' % c)
TypeError: did not evaluate to a bool: None
```
This issue should discuss what all needs to be done to support such queries.

**Comment by Smit-create** [comment]
`X` is which process?

**Comment by czgdp1807** [comment]
> X represents a Markov chain(discrete/continuous).

**Comment by Kitchlew** [comment]
I understand how discreet markov chains work and I can see that you want after the j-1th "jump" a person lands on the state "2" given that currently they're sitting on state "i", what I dont get is what sort of input and output formats are you looking for. Do you want the code to produce j x i matrix with indices containing corresponding solutions or do you want sympy to churn out a general trinomial type function. I cant fully visualize what your expectation from the above expression is. Please elaborate. We can create a function that takes definite values for i and j ,return probabilities accordingly. Knowing j is crucial as if we dont know the number of instances(j) an infinte number of permutations is possible hence the errors

**Comment by Kitchlew** [comment]
The number of values that "i" can take are restricted by the transition matrix used to define the discreet markov chain. Hence, for a transition matrix of order 3 one must ensure that the value assigned to i corresponds to any one of three space states.

**Comment by oscarbenjamin** [comment]
I think the idea is that it would be a symbolic expression involving the symbols i and j.

**Comment by czgdp1807** [comment]
Well, we can return a Matrix in case of discrete Markov chains but in continuous that won't be possible. In fact in discrete time Markov chains we don't know the upper bound of `j`. Any how, would it be possible to return half done result and then allowing substitution of i and j to continue from that half done result.

**Comment by naveensaigit** [comment]
For queries of this type, I am thinking of the following appoach - `P(Eq(Y[a], b), Eq(Y[c], d))` would be returned as it is if `a` or `c` is not substituted, else a matrix (P^(b-a)) can be returned. How do we handle it for `ContinuousMarkovChain`?

**Comment by czgdp1807** [comment]
> How do we handle it for `ContinuousMarkovChain`?

As far as I remember in `ContinuousMarkovChain` the algorithm for queries is the same but the transition probabilities are generated from generator matrix and are time dependent in which we pass the difference `t = (a-c)` and `P` becomes `exp(t*gen_mat)`  and `P[next_state, curr_state]` will be the direct answer. So, I think even if `a`, `b`, `c` and `d` all are symbols, may be we can return `P[next_state, curr_state]`, though only if `P` supports symbolic indices which is supported,
```python
In [1]: M = Matrix([[1, 2], [3, 4]])

In [2]: M[x, y]
Out[2]: 
⎛⎡1  2⎤⎞      
⎜⎢    ⎥⎟[x, y]
⎝⎣3  4⎦⎠      

In [4]: _.subs({x: 1, y: 1})
Out[4]: 4
```

**Comment by naveensaigit** [comment]
That looks good, I'll start implementing this then

**Comment by naveensaigit** [comment]
I'm having a problem using indices in matrices raised to power a-c. Its directly getting evaluated leading to a messy output. Can you suggest anything? @czgdp1807 
``` python
>>> from sympy import *
>>> from sympy.stats import *
>>> a,b,c,d = symbols('a b c d')
>>> T = Matrix([[Rational(1,10), Rational(4, 10), Rational(5, 10)], [Rational(3,10), Rational(4,10), Rational(3,10)], [Rational(7,10), Rational(2,10), Rational(1,10)]])
>>> T**(a-c)[d, b]
Long evaluated matrix...
>>> Pow(T, a-c)[d, b]
Long evaluated matrix...
>>> Pow(T, a-c, evaluate=False)[d,b]
TypeError: 'Pow' object is not subscriptable
```

**Comment by naveensaigit** [comment]
ping @czgdp1807

**Comment by czgdp1807** [comment]
When symbols will be used then these kind of results should be expected. May be, long evaluated matrix will be better since user can just substitute and re-evaluation of matrix exponentiation will be avoided for every access. @Upabjojr @Smit-create Thoughts?

**Comment by naveensaigit** [comment]
@czgdp1807 Should we go ahead with returning the evaluated matrix?

**Comment by czgdp1807** [comment]
You can. If any change would be required we will discuss in the PR.
