### ISSUE TITLE
Evaluating fourier series in sympy vs in paper

### ISSUE THREAD

**Issue by SanjayLo** [sympy/sympy#19044]
I'm new to Python. I was working with Fourier series and plotting the results. I did use Sympy. 
First, I solved Fourier series in paper and then plotted the results(file name: Fourier-final). The second one(file name: Fourier-new is from documentation.

[Fourier-final.txt](https://github.com/sympy/sympy/files/4413516/Fourier-final.txt)
[Fourier-new.txt](https://github.com/sympy/sympy/files/4413523/Fourier-new.txt)

Fourier-final-graph:
![Final_Fourier_Plot](https://user-images.githubusercontent.com/17606095/78111147-dda7fd80-7419-11ea-960a-e9f01af3d66f.png)

Fourier-new-graph:
![Fourier_new](https://user-images.githubusercontent.com/17606095/78111126-d680ef80-7419-11ea-8f69-6a9a12443919.png)

**Comment by sylee957** [comment]
I thought that something had gone wrong, but now I think that it's a gotcha as you have specified the integral as `s = fourier_series(x, (x, 0, pi))` rather than `s = fourier_series(x, (x, -pi, pi))`.
