### ISSUE TITLE
 Bug in Expressions

### ISSUE THREAD

**Issue by abhinav28071999** [sympy/sympy#19055]
When a field element is substituted it seems that the final value loses      it's field property.
Eg.
`a = x**2`
`a.subs(x, FF(29)(12))` returns 144.
But `FF(29)(12)**2`     should  give                            SymmetricModularIntegerMod29(28).

**Comment by jksuom** [comment]
`subs` will sympify its arguments as all components of a SymPy expression have to be instances of Basic. So `FF(29)(12)` becomes `Integer(12)`. That will also happen with Python objects:
```
In [1]: a = x**2

In [2]: b = 12

In [3]: type(b)
Out[3]: int

In [4]: a.subs(x, b)
Out[4]: 144

In [5]: type(_)
Out[5]: sympy.core.numbers.Integer
```
I would not consider this a bug.
