### ISSUE TITLE
Allowing users to make custom probability distributions

### ISSUE THREAD

**Issue by czgdp1807** [sympy/sympy#19057]
As of now, there are plenty of probability distributions defined already in the package, for example [here](https://github.com/sympy/sympy/blob/master/sympy/stats/crv_types.py). We can add more such distributions to it but that will just lead to a forever increasing code size. To avoid this probably we can allow users to inherit some classes from `sympy.stats` to make their own custom distributions. I am not sure if this is already allowed but if not then following can be done to expose the framework of distribution types,

1. Bring some of the classes like, `SingleContinuousDistribution`, etc to `sympy.stats` namespace so that they can be imported and inherited in the custom distribution.
2. Add some examples in the documentation of the process of doing this.

Comments from community are needed to think and decide on this.

**Comment by sylee957** [comment]
How are you going to verify that the distribution is valid?
I think that it involves computing symbolic integrals for verifying the distributions or finding some other properties. And it can be slow

**Comment by sylee957** [comment]
I may agree on adding a user-definable API, however, I don't think that 'increasing code size' is a convincing reason to reject adding new stuff for it.

**Comment by Smit-create** [comment]
I think we can provide such custom-defined distributions by the user. 
We can do to verify that the distribution is valid by integrating/summation over the pdf/pmf to can check whether it leads to 1 on its domain or else raise an error that the pdf/pmf defined is incorrect.
Providing this will need strong support of integrate and Sum as this will be computing all other functions as well as checking the defined pdf as well.

**Comment by Smit-create** [comment]
I think instead of moving `SingleContinuousDistribution`, we can use `ContinuousDistributionHandmade` as IMO, it was made for a similar purpose, but require some checks for validating pdf/pmf

**Comment by Smit-create** [comment]
We can define custom distribution in sympy as:
```
>>> from sympy import Lambda
>>> from sympy.abc import x
>>> from sympy.stats.crv import ContinuousDistributionHandmade
>>> from sympy import Lambda
>>> expr = 4*x**3
>>> pdf = Lambda(x, expr)
>>> pdf
Lambda(x, 4*x**3)
>>> defined_dist = ContinuousDistributionHandmade(pdf, set=Interval(0,1))
```

We can also define custom continuous RV as:
```
>>> pdf = 4*x**3
>>> rv_new = ContinuousRV(x, pdf,set=Interval(0, 1))
>>> E(rv_new)
4/5
>>> P(rv_new > 2)
0
>>> P(rv_new < 1)
1
>>> P(rv_new < 1/2)
0.0625000000000000
>>> rv_new.pspace
SingleContinuousPSpace(x, ContinuousDistributionHandmade(Lambda(x, Piecewise((4*x**3, (x >= 0) & (x <= 1)), (0, True))
), Interval(0, 1)))

```
I think the proposed is present currently but need some improvement as
(i) Moving ContinuousDistributionHandmade and other Handmade Distributions to sympy.stats namespace while ContinuousRV is already present. 
(ii) Adding checks for validating pdf/pmf
(iii) Adding more tutorials/documentation helping user to understand the usage

**Comment by Smit-create** [comment]
Can [this](https://github.com/sympy/sympy/issues/19057#issuecomment-608252107) be considered as a fix?

**Comment by czgdp1807** [comment]
> Moving ContinuousDistributionHandmade and other Handmade Distributions to sympy.stats namespace while ContinuousRV is already present.

I would like to have this.

> Adding checks for validating pdf/pmf

A simple check method can be added to `ContinuousDistributionHandmade` as is the case with the distribution classes defined in `*_types.py`.

> Adding more tutorials/documentation helping user to understand the usage

Much needed.
