### ISSUE TITLE
Plots are displaying incorrectly on the development documentation website

### ISSUE THREAD

**Issue by moorepants** [sympy/sympy#19051]
See: https://docs.sympy.org/dev/modules/physics/continuum_mechanics/beam.html#sympy.physics.continuum_mechanics.beam.Beam.plot_bending_moment

Other possible related issues:

- #18901
-  #19023
- #18974

Here are a couple of examples:

![image](https://user-images.githubusercontent.com/276007/78207512-c0455480-7456-11ea-94d2-6e2325a9fc70.png)

![image](https://user-images.githubusercontent.com/276007/78207555-de12b980-7456-11ea-9758-f726af7fc2c0.png)

**Comment by moorepants** [comment]
This is also the case on the examples page: https://docs.sympy.org/dev/modules/physics/continuum_mechanics/beam_problems.html#examples

**Comment by moorepants** [comment]
Everything seems to work on the "lastest" version of the docs: https://docs.sympy.org/latest/modules/physics/continuum_mechanics/beam_problems.html#examples

**Comment by moorepants** [comment]
The plots are also displaying incorrectly on the plotting page. Compare:

https://docs.sympy.org/dev/modules/plotting.html

and

https://docs.sympy.org/latest/modules/plotting.html

**Comment by moorepants** [comment]
Actually, the root cause seems to be a regression in matplotlib's behavior. 

```
conda create -n mpl3.1 python=3 sympy "matplotlib=3.1.*"
conda activate mpl3.1
```

create `plot_test.py`

```python
from sympy import symbols
from sympy.plotting import plot
x = symbols('x')
p1 = plot(x*x, show=False)
p2 = plot(x, show=False)
p1.append(p2[0])
p1.show()
```

```
git checkout sympy-1.5.1
python plot_test.py
```

This is SymPy 1.5.1 + Matplotlib 3.1 and gives this output:

![image](https://user-images.githubusercontent.com/276007/78269038-e7833c80-74bd-11ea-986b-584c37960d4b.png)

Now

```
git checkout master
```

SymPy 1.6dev + MPL 3.1 gives:

![image](https://user-images.githubusercontent.com/276007/78269149-07b2fb80-74be-11ea-8e64-e3cd7d820fd2.png)


Now with SymPy 1.6dev = MPL 3.2:

![image](https://user-images.githubusercontent.com/276007/78269219-25806080-74be-11ea-8b53-e715908831f9.png)

**Comment by moorepants** [comment]
So I think we need to build our docs with matplotlib < 3.2 and we should open some issues on matplotlib to see if we can get this fixed upstream or if there are work arounds. This seems like output behavior that was likely not properly deprecated by MPL.

**Comment by moorepants** [comment]
I opened https://github.com/matplotlib/matplotlib/issues/17004 over at matplotlib.

**Comment by Smit-create** [comment]
Can this be relatable? Using `xlim` produces the below plot. matplotlib version = `3.1.1`

![Screenshot from 2020-04-05 19-25-39](https://user-images.githubusercontent.com/55887635/78500356-84bacb00-7773-11ea-95d5-e17c52f1ab67.png)

**Comment by moorepants** [comment]
Possibly, but I wasn't seeing any issues with matplotlib 3.1 (only 3.2), so maybe this isn't the same issue.

**Comment by oscarbenjamin** [comment]
I'm adding the 1.6 milestone because this is a regression since 1.5.
