### ISSUE TITLE
why to_cnf("A & E") will raise an Exception?

### ISSUE THREAD

**Issue by Loner233** [sympy/sympy#19053]
```python
from sympy.logic.boolalg import to_cnf
to_cnf(something here)
```
I tried `to_cnf("A & B")`, It's OK.
But it will raise an Exception when the string contains "E", like`to_cnf("A & E")`.
The error : 
 ```error
TypeError: expecting bool or Boolean, not `E`.
```

**Comment by smichr** [comment]
`E` stands (by default) for the irrational number *e*. If you `from sympy.abc import A, B, E` then it will work. That's the short answer. The longer answer would get into how to override how SymPy parses strings.

**Comment by Loner233** [comment]
I tried `from sympy.abc import A, B, E`, but the `to_cnf("A & E")` still didnt work.I think I should try to override the way how sympy parses string. Anyway, thank you very much.

**Comment by asmeurer** [comment]
You shouldn't rely on string inputs. It is better to create the expression and then pass it to to_cnf. If you need to parse a string, use `sympify()`.
