### ISSUE TITLE
Confusing dummy name in series expansion of multivariable function

### ISSUE THREAD

**Issue by mcpl-sympy** [sympy/sympy#19065]
```python
>>> from sympy import Function
>>> from sympy.abc import x,y
>>> f = Function('f')
>>> f(x,y).series(y, n=2)
```
The result is, displaying in LaTeX,

![image](https://quicklatex.com/cache3/61/ql_37726da71820e225fd8972d2d918a361_l3.png)

In second term, first `x` in `f(x,x)` is free symbol while the second one is dummy symbol.
Clearly the dummy symbol needs to take some other name.

**Comment by smichr** [comment]
Note that SymPy will not be confused (if Dummy was actually used) as to which variable is the real `x`. And you can always use `.as_dummy()` to disambiguate what you see:
```
>>> f(x,y).series(y, n=2).as_dummy()
            / d           \|        / 2\
f(x, 0) + y*|---(f(x, _0))||     + O\y /
            \d_0          /|_0=0        
```
But a better method of selecting a unique symbol by the series method would be good, too. (And I know you are already making progress toward this end in #19066.)
