### ISSUE TITLE
Sphinx builds failing

### ISSUE THREAD

**Issue by jksuom** [sympy/sympy#19084]
It seems that all Sphinx jobs (# 15) have been failing after Travis updated to v.3.0.0 a couple of days ago. The old version 2.4.4 gave warnings but did not fail.

**Comment by oscarbenjamin** [comment]
The `set_smart_bounds` method in matplotlib is deprecated. It was removed in #18870 but that was reverted because it caused #19051. Now the build fails because of the deprecation warnings from a newer version of matplotlib complaining about the use of `set_smart_bounds`.
