### ISSUE TITLE
Expanding logarithm to the terms of a summation

### ISSUE THREAD

**Issue by rladeira** [sympy/sympy#19100]
How can I expand logarithms to the sub terms of a summation? 

Let's take this code as an example. 

```python
import sympy as sp

p, f, a, b = sp.symbols('p, f, a, b', real=True, positive=True)
E = sp.symbols('E', real=True)

E = (1 + f*b)**p + (1 - a*f)**(1 - p)

print(sp.log(E))
```
The output is: 

`log((-a*f + 1)**(1 - p) + (b*f + 1)**p)`

If I try:

```
log_e = sp.expand_log(sp.log(E), force=True)

print(log_e)
```
Even when `expand_log` is applied, the ouput is the same:

`log((-a*f + 1)**(1 - p) + (b*f + 1)**p)`

How can I achieve the following result?

`(1 - p)*log(-a*f + 1) + p*log(b*f + 1)`

Thanks in advance

**Comment by Smit-create** [comment]
I think the output is correct, as `log((-a*f + 1)**(1 - p) + (b*f + 1)**p)` is not always eqaul to `(1 - p)*log(-a*f + 1) + p*log(b*f + 1)`
```python
>>> from sympy import *
>>> from sympy.abc import p, f, a, b
>>> p, f, a, b = symbols('p, f, a, b', real=True, positive=True)
>>> expr = (1 + f*b)**p + (1 - a*f)**(1 - p) # You defined this
>>> output = expand_log(log(expr))
>>> output
log((-a*f + 1)**(1 - p) + (b*f + 1)**p)
>>> # This will produce the expected result, notice the * instead of + in expr_1
>>> expr_1 = (1 + f*b)**p * (1 - a*f)**(1 - p) 
>>> log_expr_1 = log(expr_1)
>>> log_expr_1
log((-a*f + 1)**(1 - p)*(b*f + 1)**p)
>>> expected_output = expand_log(log_expr_1)
>>> expected_output
p*log(b*f + 1) + log((-a*f + 1)**(1 - p))
>>> # Substituing same values in both expression to check if they are equal
>>> output.subs({f:3, b:1, a:Rational(1,4), p:Rational(1,2)}) 
log(5/2)

>>> exptected_output.subs({f:3, b:1, a:Rational(1,4), p:Rational(1,2)})
-log(2) + log(4)/2

```
Hence, I think the result produced is correct, as mathematically, the expected result is not always equal to result obtained.

**Comment by oscarbenjamin** [comment]
> The output is:
> 
> `log((-a*f + 1)**(1 - p) + (b*f + 1)**p)`
>
> How can I achieve the following result?
> 
> `(1 - p)*log(-a*f + 1) + p*log(b*f + 1)`

It seems to me that maybe you are expecting this:
```
log(  (-a*f + 1)**(1 - p) + (b*f + 1)**p  )
--->  log(  (-a*f + 1)**(1 - p) )   +   log(  (b*f + 1)**p. )
--->  (1 - p)*log(-a*f + 1) + p*log(b*f + 1)
```
but this is incorrect. The problem is in the first step since `log(x + y) != log(x) + log(y)`.

**Comment by rladeira** [comment]
Oh, you both are right.  The behavior is correct for the expression which I've typed above.

Actually, I mistyped the equation. What I meant was:

```
E = (1 + f*b)**p * (1 - a*f)**(1 - p)
```

For this case, `expand_log` works as I expected:

```
log_e = sp.expand_log(sp.log(E), force=True)

print(log_e)
```
Output:
```p*log(b*f + 1) + (1 - p)*log(-a*f + 1)```


Thanks @Smit-create and @oscarbenjamin for pointing out the silly mistake.

Best regards.
