### ISSUE TITLE
why Sum().doit() doesn't work 

### ISSUE THREAD

**Issue by Lenintel** [sympy/sympy#19103]
Input: 
`import sympy as sy`
`from sympy.abc import i, k, N, n, Q, P`
        `from sympy import Sum, oo`
        `Sum(sy.cos(2*sy.pi*n*P)*sy.sin(2*(N-n)*sy.pi*Q), (n, -oo, N)).doit()`

It doesn't find the closed form. Can you help me?
Thanks in advance.

**Comment by oscarbenjamin** [comment]
This is not the right place to ask for help with using sympy. You can use stackoverflow or the sympy mailing list for that.

Github issues is for reporting a bug. If you have a reason to think that a closed form exists and that sympy should be able to compute it then it makes sense to open an issue like this.

**Comment by Lenintel** [comment]
I'm asking because the closed form exists ( I computed it with other programs) and I belive that the code is well done.

**Comment by oscarbenjamin** [comment]
So what is the closed form answer then?

Are any of the symbols supposed to be integers or is anything else assumed about them in order for the closed form to exist?
