### ISSUE TITLE
Sum(cos(j**2*x)/j**2, (j,1,12) ) return problem

### ISSUE THREAD

**Issue by asukaminato0721** [sympy/sympy#19119]
```
from sympy import *
from sympy.printing import *
j=symbols("j")
plot(
    Sum(
        cos(j**2*x)/j**2,
        (j,1,12)
        ),
        (x,0,2*pi)
    )
```

![image](https://user-images.githubusercontent.com/30024051/79178409-b6c3d100-7df4-11ea-9b8f-ebd3ac7720d3.png)

**Comment by sylee957** [comment]
`Sum` returns unevaluated, so you shouldn't use `Sum` but `summation` to get the expanded form because numpy cannot handle any symbolic summations.
But I think that sympy should reject such inputs like `Sum`, `Integral` in plots other than performing the impractical computation.

**Comment by asukaminato0721** [comment]
![image](https://github.com/user-attachments/assets/459dd276-c9a0-4fa4-9897-32cda1547c84)
