### ISSUE TITLE
1/tan wrong but cot works

### ISSUE THREAD

**Issue by wuyudi** [sympy/sympy#19115]
This code can work properly.

```
from sympy import *
α,x,β=symbols("α x β")
solveset(Eq(cot(α*x+β),0),x)
```

![image](https://user-images.githubusercontent.com/30024051/79139890-9ff68d80-7da6-11ea-99f7-03d03216bf65.png)

But

```
from sympy import *
α,x,β=symbols("α x β")
solveset(Eq(1/tan(α*x+β),0),x)
```

returns 

![image](https://user-images.githubusercontent.com/30024051/79139923-ad137c80-7da6-11ea-96a5-393519be3a02.png)

**Comment by gschintgen** [comment]
The first equation (with `cot`) needs to use another algorithm, based on function inversion. This is a known issue. See #17334 for a summary and references to other issues.

The second equation (with `1/tan`) is solved correctly. No equation of type `1/f(z) == 0` can have a solution in C. (Note that `cot` and `1/tan` are not strictly identical, they have different domains.)
There have been other discussions about how to treat removable singularities in `solveset`. For now they're treated as what they are: singularities hence not solutions. But given that `trigsimp` sometimes simplifies them away I won't claim that `solveset` will be perfectly consistent when they do come up...

I think this issue can be closed, but thanks for your interest! If anything else comes up, feel free to add it.
