### ISSUE TITLE
the result of integrate(1/(2+sin(x)),x) seems weird.

### ISSUE THREAD

**Issue by asukaminato0721** [sympy/sympy#19112]
I use Mathematica to plot it.

```mma
Integrate[1/(2 + Sin[x]), x]
Plot[%, {x, 0, 2 Pi}]
```

![image](https://user-images.githubusercontent.com/30024051/79110111-402dc180-7d69-11ea-90a4-c649e49f98db.png)

But sympy gives

```py
from sympy import *
from sympy.plotting import *
plot(
    integrate(
        1/(2+sin(x)),x
    )
)
```

![image](https://user-images.githubusercontent.com/30024051/79110147-5045a100-7d69-11ea-9ab7-f6967814412d.png)

**Comment by oscarbenjamin** [comment]
The result from sympy looks fine to me. The integrand is positive and continuous for all real x so the antiderivative can be continuous and increasing as well. The result from mathematica looks like it can be improved.

The antiderivative from sympy is
```julia
In [9]: I = integrate(1/(2+sin(x)), x)                                                                                            

In [10]: I                                                                                                                        
Out[10]: 
     ⎛    ⎛        ⎛x⎞     ⎞     ⎢x   π⎥⎞
     ⎜    ⎜2⋅√3⋅tan⎜─⎟     ⎟     ⎢─ - ─⎥⎟
     ⎜    ⎜        ⎝2⎠   √3⎟     ⎢2   2⎥⎟
2⋅√3⋅⎜atan⎜─────────── + ──⎟ + π⋅⎢─────⎥⎟
     ⎝    ⎝     3        3 ⎠     ⎣  π  ⎦⎠
─────────────────────────────────────────
                    3 
```
This is the same as the result from mathematica but has an additional floor term in the numerator that cancels the discontinuity giving a continuous result.

Normally I would validate this result by differentiating it but it seems that diff/simplify have trouble with the floor:
```julia
In [13]: simplify(I.diff(x))                                                                                                      
Out[13]: 
   ⎛⎛              2    ⎞                                  ⎞
   ⎜⎜⎛     ⎛x⎞    ⎞     ⎟ ⎛ d       ⎞│              4⋅√3   ⎟
√3⋅⎜⎜⎜2⋅tan⎜─⎟ + 1⎟  + 3⎟⋅⎜───(⌊ξ₁⌋)⎟│   x - π + ──────────⎟
   ⎜⎝⎝     ⎝2⎠    ⎠     ⎠ ⎝dξ₁      ⎠│ξ₁=─────   cos(x) + 1⎟
   ⎝                                      2⋅π              ⎠
────────────────────────────────────────────────────────────
                    ⎛              2    ⎞                   
                    ⎜⎛     ⎛x⎞    ⎞     ⎟                   
                  3⋅⎜⎜2⋅tan⎜─⎟ + 1⎟  + 3⎟                   
                    ⎝⎝     ⎝2⎠    ⎠     ⎠                   

In [14]: simplify(I.diff(x) - 1/(2 + sin(x)))                                                                                     
Out[14]: 
   ⎛⎛              2    ⎞                                  ⎞                                   
   ⎜⎜⎛     ⎛x⎞    ⎞     ⎟ ⎛ d       ⎞│              4⋅√3   ⎟                                   
√3⋅⎜⎜⎜2⋅tan⎜─⎟ + 1⎟  + 3⎟⋅⎜───(⌊ξ₁⌋)⎟│   x - π + ──────────⎟⋅(sin(x) + 2)                      
   ⎜⎝⎝     ⎝2⎠    ⎠     ⎠ ⎝dξ₁      ⎠│ξ₁=─────   cos(x) + 1⎟                              2    
   ⎝                                      2⋅π              ⎠                ⎛     ⎛x⎞    ⎞     
───────────────────────────────────────────────────────────────────────── - ⎜2⋅tan⎜─⎟ + 1⎟  - 3
                                    3                                       ⎝     ⎝2⎠    ⎠     
───────────────────────────────────────────────────────────────────────────────────────────────
                               ⎛              2    ⎞                                           
                               ⎜⎛     ⎛x⎞    ⎞     ⎟                                           
                               ⎜⎜2⋅tan⎜─⎟ + 1⎟  + 3⎟⋅(sin(x) + 2)                              
                               ⎝⎝     ⎝2⎠    ⎠     ⎠ 
```

**Comment by wuyudi** [comment]
this seems to be a bug of mma
![image](https://user-images.githubusercontent.com/30024051/79180177-c513ec00-7df8-11ea-8421-60bf9c479770.png)

**Comment by wuyudi** [comment]
Well , this seems out of my knowledge. Since

![image](https://user-images.githubusercontent.com/30024051/79181190-5e440200-7dfb-11ea-9251-68dc0faddebf.png)

So I have no idea about which one is right.

**Comment by jksuom** [comment]
By definition, an indefinite integral (or antiderivative) of a function `f` is a differentiable function whose derivative is `f`. A differentiable function must be continuous, so the correct indefinite integral is one that is continuous.

**Comment by oscarbenjamin** [comment]
The discontinuous answer from mathematica and the youtube video are valid in any real range of x that does not include the discontinuities. The result from sympy is better because it is valid for any real range of x.

I'm not sure what happens if we consider x over the complex plane though...
