### ISSUE TITLE
is_integer returns None with expression in open interval (0, 1)

### ISSUE THREAD

**Issue by j3parera** [sympy/sympy#19145]
Any possible value of the expression defined by:
```python
d = Symbol('d', real=True, positive=True)
a = 1 / (1 + d)
```
is always in the open interval (0, 1). Note that `d` is qualified as `positive` and thus cannot be 0.
The tests:
```python
a > 0    # returns True
a < 1    # returns True
```
both return the correct value `True`. But the tests:
```python
a.is_integer         # returns None
ask(Q.integer(a))    # returns None
```
both return `None` when they should be `False`.

**Comment by oscarbenjamin** [comment]
I think it's fine if `is_integer` gives `None` in some cases. It is intended to be a cheap way of checking so it should only give the correct answer when it is cheap to compute.

In this particular case it might be: we have `Pow(1+d, -1)` so if we know that the base of the Pow is greater than one and finite and that the exponent is negative then we can return a result here. Maybe something like:
```diff
diff --git a/sympy/core/power.py b/sympy/core/power.py
index bf66ceb3a5..cf325b3731 100644
--- a/sympy/core/power.py
+++ b/sympy/core/power.py
@@ -590,6 +590,8 @@ def _eval_is_integer(self):
         if b.is_Number and e.is_Number:
             check = self.func(*self.args)
             return check.is_Integer
+        if e.is_negative and b.is_positive and (b > 1) is S.true:
+            return False
 
     def _eval_is_extended_real(self):
         from sympy import arg, exp, log, Mul
```

**Comment by smichr** [comment]
cf #10458

**Comment by j3parera** [comment]
I agree that `is_integer` must remain cheap; maybe `ask(Q.integer(a))` not so much. And I also agree that the answer `None` is not an error. I just point it out in case it can be considered a mistake or just an improvement or leave as it is.
Anyway, regarding the solution you propose I think is not complete because it would not fix the case in which the expression was bounded in the (-1, 0) interval. The expression tree for: `a = -1/(1+d)` results in `Mul(-1, Pow(1+d, -1))` so there would be no problem but the expression tree for `a = 1/-(1+d)` is `Pow(-d-1, -1)`. In this case the conditions after `e.is_negative` should be the opposite: `b.is_negative and (b < 1) is S.true`. By the way, can't both conditions be grouped into `(b > 1) is S.true` (`(b < 1)` for the negative case)? In other words, isn't it redundant to check `b.is_positive` (or negative)?

**Comment by oscarbenjamin** [comment]
> I agree that `is_integer` must remain cheap; maybe `ask(Q.integer(a))` not so much.

Yes, that seems right to me. I'm not sure that the relationship between the new and the old assumptions is really agreed yet but to me it makes sense that the old assumptions are for cheap queries as part of evaluation whereas the new assumptions are for more complex or slower queries that are not to be used in evaluation but can be used in higher-level routines like `simplify`.

> In this case the conditions after `e.is_negative` should be the opposite: `b.is_negative and (b < 1) is S.true`

Yes, good point.

> By the way, can't both conditions be grouped into `(b > 1) is S.true` (`(b < 1)` for the negative case)? In other words, isn't it redundant to check `b.is_positive` (or negative)?

It isn't redundant because inequalities raise if either side is complex e.g.:
```julia
In [35]: sqrt(-1) < 2                                                                                                             
---------------------------------------------------------------------------
TypeError
```
checking `b.is_positive` guards against that because `b` has to be real if it is positive. Also I thought it would be good to avoid evaluating the Relational (`b > 1`) if it all possible. What we really need is an `is_greater_than` function (#18778).

**Comment by j3parera** [comment]
> It isn't redundant because inequalities raise if either side is complex ...

Ok, I see. Thanks.

On the other hand, regarding relationals a new related question arise. Both
```python
a >= 0    # returns True
a <= 1    # returns True
```
return `True`, even though, strictly speaking, the equalities would only be `True` in the limit, since the symbol `d` is qualified as `positive`. It seems that for `a >= 0` the case `+oo` is included. But for the equality in `a <= 1` to hold `d` should include 0, which is not the case as corretly returned by `d.is_nonzero`.

**Comment by oscarbenjamin** [comment]
I'm not sure I understand your question. On master I get this:
```julia
In [1]: d = Symbol('d', real=True, positive=True) 
   ...: a = 1 / (1 + d)                                                                                                                        

In [2]: a >= 0                                                                                                                                 
Out[2]: True

In [3]: a > 0                                                                                                                                  
Out[3]: True

In [4]: a <= 1                                                                                                                                 
Out[4]: True

In [5]: a < 1                                                                                                                                  
Out[5]: True
```
Those all seem correct to me.

Since d is both real and positive it is also finite because real implies finite (since sympy 1.5).

**Comment by j3parera** [comment]
Fool of me. I was meaning that `>=` should be 'great _and_ equal' not 'geat _or_ equal. Sorry. :-$
