### ISSUE TITLE
limit(besseli(1, 3 *x)/(x *besseli(1, x)**3), x , oo) return TypeError

### ISSUE THREAD

**Issue by wuyudi** [sympy/sympy#19154]
`besseli(1, 3 *x)` could work

`(x *besseli(1, x)**3)` could work
but when I use
```python
limit(besseli(1, 3 *x)/(x *besseli(1, x)**3), x , oo)
```

TypeError: unsupported operand type(s) for //: 'mpf' and 'int'

**Comment by Saanidhyavats** [comment]
The type error is coming due to the misplacement of brackets in `limit(besseli(1, 3 *x)/(x *besseli(1, x)**3), x , oo)` . Replace it with `limit((besseli(1, 3 *x)/(x *besseli(1, x)**3)), x , oo)`.

**Comment by Saanidhyavats** [comment]
> `besseli(1, 3 *x)` could work
> 
> `(x *besseli(1, x)**3)` could work
> but when I use
> 
> ```python
> limit(besseli(1, 3 *x)/(x *besseli(1, x)**3), x , oo)
> ```
> 
> TypeError: unsupported operand type(s) for //: 'mpf' and 'int'

Initially it is giving type error but on doing the same thing for the 2nd time error is not coming

**Comment by 0sidharth** [comment]
This stems from `besseli(1, oo)` remaining reevaluated (value is `oo`), and then being checked for infinities. `besseli(1, oo).is_infinite` throws this error to be precise. While this condition may be added to the `eval` method to prevent this error, the limit still remains unevaluated. Probably `aseries` or `leading_term` support needs to be added for `besseli` to get the expected limit (`2*pi/sqrt(3)`)

**Comment by oscarbenjamin** [comment]
The error comes from:
```
besseli(1, oo).evalf()
```
