### ISSUE TITLE
pprint of diff(f(x)* g(x), (x, n)) has overlapping elements

### ISSUE THREAD

**Issue by asukaminato0721** [sympy/sympy#19156]
![image](https://user-images.githubusercontent.com/30024051/79817366-dc148a00-8374-11ea-88ae-e398e1ece7dd.png)

I don't know whether it's the problem of jupyter or sympy.

```python
diff(f(x)* g(x), (x, n))
```

**Comment by oscarbenjamin** [comment]
I think that output is correct. What is wrong with it?

The only thing I can see is that n-k1 is always nonnegative so the max isn't needed.

**Comment by smichr** [comment]
With a symbolic order of derivative there is no nice answer. You could replace `Max(0, n - k1)` with `n - k1`, however. (That's another example of where Sum could try tidy of expressions it returns by using information from the limits, right @oscarbenjamin? What replacement could you make that would allow such things to evaluate?)

**Comment by wuyudi** [comment]
What I mean is that, the `g(x)` is messed up with the fraction. With is not so pretty.

**Comment by sylee957** [comment]
I don't think that this is an issue of sympy functions or printing, but from the external LaTeX renderer.
I have tried with some other LaTeX renderers and they rendered fine, but I see the overflowing issue exits in mathjax, so it can be an issue of mathjax, but it depends on your LaTeX renderer used in the backend. Can you provide any information about the LaTeX backend you are using?

**Comment by asmeurer** [comment]
That looks like it is probably a bug with MathJax, unless we are generating bad LaTeX somehow.

**Comment by wuyudi** [comment]
My environment is jupyter, and the render is mathjax. Which comes from [here](https://stackoverflow.com/a/42446768/13040423) . So it seems to be a problem with mathjax.

**Comment by oscarbenjamin** [comment]
> What replacement could you make that would allow such things to evaluate?

In general you would need to be able to refine based on inequalities (which is probably what Sum should do). Does the formula generating this example even need the max though?

**Comment by smichr** [comment]
Negative order of differentiation raises an error so I suppose there is no need for the guard on the order via Max.

**Comment by asmeurer** [comment]
Here's the latex that is generated

```
\sum_{k_{1}=0}^{n} \frac{n! \frac{d^{k_{1}}}{d x^{k_{1}}} f{\left(x \right)} \frac{d^{\max\left(0, - k_{1} + n\right)}}{d x^{\max\left(0, - k_{1} + n\right)}} g{\left(x \right)}}{k_{1}! \left(- k_{1} + n\right)!}
```

I don't see anything wrong with it. 

It seems to render correctly [here](https://www.mathjax.org/#demo), which means it is either an issue with MathJax 2 (that site uses MathJax 3, but I believe Jupyter still uses version 2), or it is related to the equation environment we use (I forget what we do exactly, but it isn't `$$`).

**Comment by shilpiprd** [comment]
I tried the same code with pprint. My background in jupyter as well. For me it worked fine.
![Screenshot from 2021-11-12 15-00-48](https://user-images.githubusercontent.com/72646134/141444951-b8b32bc9-bd1c-4de7-8511-5de27aaa8e19.png)

**Comment by shilpiprd** [comment]
I tried the same thing. My environment is jupyter as well. For me it worked correctly.
![Screenshot from 2021-11-12 15-01-02](https://user-images.githubusercontent.com/72646134/141445114-371815af-b01c-4cc9-bdef-3393a3d60ff5.png)

**Comment by asukaminato0721** [comment]
![image](https://github.com/user-attachments/assets/6a6052f6-3e08-4caf-beb3-1d8397d7346c)
