### ISSUE TITLE
Gaussian Optics / Refractive index not considered

### ISSUE THREAD

**Issue by LukasHeller** [sympy/sympy#19169]
Dear sympy maintainers,

please correct me, if I am wrong, but I fear that the beam waist in 

class sympy.physics.optics.gaussopt.BeamParameter

is not correctly computed.

From the source:

def w_0(self):
        """
        The beam waist (minimal radius).

        See Also
        ========

        w : the beam radius at `1/e^2` intensity

        Examples
        ========

        >>> from sympy.physics.optics import BeamParameter
        >>> p = BeamParameter(530e-9, 1, w=1e-3)
        >>> p.w_0
        0.00100000000000000
        """
        return sqrt(self.z_r/pi*self.wavelen)

After  transmission through a surface with the refractive index changing, the Rayleigh length z_r would change, while wavelength stays the same. According to this implementation, w_0 changes, which is not physical.

If I might help to solve this, I would be happy to contribute. 
However, I have not a very good understanding of sympy, and this code is interfaced of course with sympy.

Best regards,
Lukas

**Comment by oscarbenjamin** [comment]
I don't know the physics so well but you are of course welcome to correct it. Many contributors can help with the sympy aspects but I'm not sure how many would know the physics for this case.

**Comment by faze-geek** [comment]
Here the formula implemented is incorrect .This will fix itself once the correct formula is used .The relation between Rayleigh length `z_r` and beam waist `w_0` involves the refractive index too .
Check out beam parameters from wikipedia-
https://en.wikipedia.org/wiki/Gaussian_beam

I'll open up a pull request on this issue soon .
