### ISSUE TITLE
LambertW with lambdify

### ISSUE THREAD

**Issue by LIVazquezS** [sympy/sympy#19180]
Dear team of Sympy,

I post this on the mail list and they recommend me to start an issue because it was supposed to be already solved. So, I will post again what I wrote on the mail list. Thanks for your hard work!

Hello Everyone!

I am trying to solve ODE with sympy and I obtain a solution in terms of the LambertW function. When I try to evaluate this function and then I obtain an error.

A bit of code.

km, vmax, t = sym.symbols('k_{m} v_{max} t ')
S0 = sym.symbols('[S]_{0}')
S = sym.Function('[S]')
dSdt = S(t).diff(t)
eq1_mm = sym.Eq(dSdt, -(vmax*S(t))/(S(t)+km))
sol_mm = sym.dsolve(eq1_mm, ics={S(0):S0})

S0_mm=1.0
vmax_mm = 1.0
km_mm = 1.0
sol_mm_init = sol_mm.subs({S0:S0_mm, vmax:vmax_mm, km:km_mm})
data = np.linspace(0,10,100)
f_S_mm = sym.lambdify(t, sol_mm_init.rhs, 'numpy')
F_S_mm = f_S_mm(data)

Then I obtained the following error when I evaluate the function.

NameError                                 Traceback (most recent call last)
<ipython-input-77-d8c2dfc1cc8b> in <module>
     12 data = np.linspace(0,10,100)
     13 f_S_mm = sym.lambdify(t, sol_mm_init.rhs, 'numpy')
---> 14 F_S_mm = f_S_mm(data)

<lambdifygenerated-16> in _lambdifygenerated(t)
      1 def _lambdifygenerated(t):
----> 2     return (1.0*LambertW(2.71828182845905*exp(-1.0*t)))

NameError: name 'LambertW' is not defined

Does any one of you have an idea how I can solve this issue?

Regards,

Luis

**Comment by asmeurer** [comment]
This should be easy to fix. We just need to add scipy.special.lambertw to the scipy lambdify dictionary.

**Comment by sylee957** [comment]
Actually, I don't think that this is an issue but a mistake.

There is no lambertw in numpy, and sympy already supports printing lambertw in scipy.
So it works after changing the line
`f_S_mm = sym.lambdify(t, sol_mm_init.rhs, 'scipy')`

**Comment by asmeurer** [comment]
Ah, I didn't notice that @LIVazquezS was explicitly setting lambdify to use 'numpy'. You can also omit the argument and it will work, because it adds scipy automatically.

**Comment by LIVazquezS** [comment]
Hello,

I tried using code by @sylee957  and it does not work on my case. Same if I try without option. 

My try:

from scipy.special import lambertw
data = np.linspace(0,25,1000)
f_S_mm = sym.lambdify(t, sol_mm_init.rhs,'scipy')
F_S_mm = f_S_mm(data)

---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-96-c269fbac05b9> in <module>
      2 data = np.linspace(0,25,1000)
      3 f_S_mm = sym.lambdify(t, sol_mm_init.rhs,'scipy')
----> 4 F_S_mm = f_S_mm(data)

<lambdifygenerated-24> in _lambdifygenerated(t)
      1 def _lambdifygenerated(t):
----> 2     return (1.0*LambertW(220264.657948067*exp(-1.0*t)))

NameError: name 'LambertW' is not defined

So, still the same issue. I check the version of scipy that I have is 1.5.1.

Cheers,

Luis

**Comment by asmeurer** [comment]
What version of SymPy are you using?

**Comment by LIVazquezS** [comment]
I have version 1.5.1.

In [1]: import sympy                                                                                                    

In [2]: print(sympy.__version__)                                                                                        
1.5.1

**Comment by sylee957** [comment]
Unfortunately, I don't think that it was merged in the previous release.
#18805
