### ISSUE TITLE
Something weird in SymPy commit history ("first" commit shows for all files)

### ISSUE THREAD

**Issue by certik** [sympy/sympy#19181]
When you look at the front page at GitHub, this is how it looks for me right now:

![Screenshot_2020-04-23 sympy sympy](https://user-images.githubusercontent.com/20568/80139971-8999c000-8564-11ea-9cc6-02111d5b3130.png)

What is going on with that "first" commit? That looks unprofessional, why would we have commits like that --- we should have proper commit messages.

When you click on it, it leads to https://github.com/sympy/sympy/commit/9d3fa8b4d4963c059c139f3860b8cc1d611adbae. 1742 modified files? What is going on?

That commit was merged as part of https://github.com/sympy/sympy/pull/18488. That PR however only shows a simple fix and a test, that got reviewed and merged.

I am afraid this is one downside of GitHub, that it didn't provide any easy clues to notice that the history of that PR is probably screwed up.

@asmeurer do you know what is going on here?

More importantly for the future: I wonder if there is a way for the sympy-bot to detect such mistakes and prevent a merge. What are some ideas how to detect such mistakes?

**Comment by certik** [comment]
If you look at some files that show the "first" commit, that otherwise do not have a complicated history, such as:

https://github.com/sympy/sympy/commits/master/CODE_OF_CONDUCT.md

Then you can see, that the "first" commit is not listed there. Weird.

**Comment by oscarbenjamin** [comment]
See #18548

**Comment by asmeurer** [comment]
@certik if you click on the "first" commit you can see the PR it comes from. 

> More importantly for the future: I wonder if there is a way for the sympy-bot to detect such mistakes and prevent a merge. What are some ideas how to detect such mistakes?

We already do that. The bot now warns if any files are added are removed in a commit, even if the final diff is the same, so that we can tell people to squash such mistakes.  You can see the discussion in the issue Oscar linked to.

**Comment by asmeurer** [comment]
I'm going to close this because there's nothing we can do about it now, and the underlying issues are already being discussed in the other issue.

**Comment by certik** [comment]
Ok, cool. Thanks for adding a check for this in the sympy-bot.
