### ISSUE TITLE
Bug with solve function

### ISSUE THREAD

**Issue by tiamkoukpari** [sympy/sympy#19186]
I found a bug in Sympy's solve function.

from sympy import solve
from sympy.abc import x
solve(x**5 - 6*x**3 - 6*x**2 + x - 6)

I attached a .png of the error below. The same thing in Matlab returns

syms x
eqn = x^5 - 6*x^3 - 6*x^2 - 6 == 0
S = solve(eqn)

S =

root(z^5 - 6*z^3 - 6*z^2 - 6, z, 1)
root(z^5 - 6*z^3 - 6*z^2 - 6, z, 2)
root(z^5 - 6*z^3 - 6*z^2 - 6, z, 3)
root(z^5 - 6*z^3 - 6*z^2 - 6, z, 4)
root(z^5 - 6*z^3 - 6*z^2 - 6, z, 5)

<img width="487" alt="solve_error" src="https://user-images.githubusercontent.com/51718564/80237338-6e38be80-8611-11ea-981d-3084db2cb684.png">

**Comment by smitgajjar** [comment]
This issue is same as #19157 , which is resolved by #19165

**Comment by tiamkoukpari** [comment]
Do you mean it has been fixed? Most recent sympy still produces the error.
Let me know!

**Comment by smitgajjar** [comment]
Actually, when you raised it in the mailing list, the same was opened as an issue here! So, since it is recently fixed, it will not be reflected now. It will be reflected in the next release of SymPy. If you want to get rid of error now, you can clone this repo and use it!

**Comment by tiamkoukpari** [comment]
Ok great thank you!
