### ISSUE TITLE
Slowdown in cholesky_solve between sympy 1.5 and 1.6

### ISSUE THREAD

**Issue by oscarbenjamin** [sympy/sympy#19200]
See #19199.

I've used `asv` to bisect a significant slowdown in the `cholesky_solve` benchmark:
```
$ asv find sympy-1.5.1..master solve.TimeMatrixSolve2.time_cholesky_solve
...
· Greatest regression found: a8a3a3b0 <pull/18576/head~1>
```
That has bisected to commit a8a3a3b0 from #18564.

The benchmark can be tested easily with
```python
# t.py

import sympy
from sympy import *

n = 3

A = sympy.Matrix(n, n, lambda i, j: sympy.Symbol('a{}{}'.format(i, j)))
b = sympy.Matrix(n, 1, lambda i, j: sympy.Symbol('b{}{}'.format(i, j)))
A_sym = sympy.Matrix(n, n, lambda i, j:
                     sympy.Symbol('a{}{}'.format(*sorted((i, j)))))

def time_cholesky_solve():
    A_sym.cholesky_solve(b)

# pprint(A_sym.cholesky_solve(b))
```
That matrix is:
```julia
In [2]: A_sym                                                                                                                                  
Out[2]: 
⎡a₀₀  a₀₁  a₀₂⎤
⎢             ⎥
⎢a₀₁  a₁₁  a₁₂⎥
⎢             ⎥
⎣a₀₂  a₁₂  a₂₂⎦

In [3]: b                                                                                                                                      
Out[3]: 
⎡b₀₀⎤
⎢   ⎥
⎢b₁₀⎥
⎢   ⎥
⎣b₂₀⎦
```

Both master and 1.5.1 give complicated results but on 1.5.1 it takes roughly a millisecond whereas on master it takes a couple of seconds:
```console
$ git checkout master
$ python -m timeit -s 'from t import time_cholesky_solve' 'time_cholesky_solve()'
1 loop, best of 5: 2.36 sec per loop

$ git checkout sympy-1.5.1
$ python -m timeit -s 'from t import time_cholesky_solve' 'time_cholesky_solve()'
1 loop, best of 5: 1.61 msec per loop
```

Running cProfile gives:
```
   Ordered by: cumulative time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
       58    0.004    0.000    9.004    0.155 __init__.py:1(<module>)
    749/1    0.019    0.000    8.908    8.908 {built-in method builtins.exec}
        1    0.000    0.000    8.908    8.908 t.py:1(<module>)
        1    0.000    0.000    6.444    6.444 matrices.py:2198(cholesky_solve)
        1    0.000    0.000    6.444    6.444 solvers.py:204(_cholesky_solve)
        1    0.000    0.000    6.149    6.149 matrices.py:390(is_positive_definite)
        1    0.000    0.000    6.149    6.149 eigen.py:675(_is_positive_definite)
      2/1    0.000    0.000    6.149    6.149 matrices.py:367(_eval_is_positive_definite)
      2/1    0.000    0.000    6.149    6.149 eigen.py:623(_eval_is_positive_definite)
        1    0.000    0.000    5.236    5.236 matrices.py:370(eigenvals)
        1    0.000    0.000    5.236    5.236 eigen.py:80(_eigenvals)
    579/3    0.006    0.000    3.203    1.068 <frozen importlib._bootstrap>:986(_find_and_load)
    579/3    0.004    0.000    3.202    1.067 <frozen importlib._bootstrap>:956(_find_and_load_unlocked)
    556/3    0.004    0.000    3.202    1.067 <frozen importlib._bootstrap>:650(_load_unlocked)
    528/3    0.006    0.000    3.202    1.067 <frozen importlib._bootstrap_external>:777(exec_module)
    979/5    0.001    0.000    3.199    0.640 <frozen importlib._bootstrap>:211(_call_with_frames_removed)
      750    0.001    0.000    2.983    0.004 densearith.py:1609(dmp_div)
 9537/750    0.065    0.000    2.981    0.004 densearith.py:1358(dmp_rr_div)
        1    0.000    0.000    2.968    2.968 polyroots.py:788(roots)
   465/61    0.002    0.000    2.870    0.047 euclidtools.py:1561(dmp_inner_gcd)
      714    0.001    0.000    2.839    0.004 densearith.py:1654(dmp_quo)
   414/61    0.001    0.000    2.833    0.046 euclidtools.py:1525(_dmp_inner_gcd)
   429/61    0.001    0.000    2.833    0.046 euclidtools.py:1269(dmp_zz_heu_gcd)
   429/61    0.001    0.000    2.833    0.046 euclidtools.py:891(_dmp_rr_trivial_gcd)
   306/19    0.002    0.000    2.832    0.149 euclidtools.py:938(_dmp_simplify_gcd)
   115/40    0.002    0.000    2.785    0.070 simplify.py:395(simplify)
        1    0.000    0.000    2.264    2.264 matrices.py:114(charpoly)
        1    0.000    0.000    2.264    2.264 determinant.py:329(_charpoly)
       60    0.001    0.000    2.234    0.037 polytools.py:6610(cancel)
```
It looks like the time is spent computing the eigenvalues in `is_positive_definite`.

**Comment by oscarbenjamin** [comment]
CC @Pristine-Cat @sylee957

**Comment by moorepants** [comment]
> It looks like the time is spent computing the eigenvalues in is_positive_definite.

Checking a symbolic matrix for positive definiteness has little practical utility, especially when that matrix gets larger. We really need to be able to set an assumption on the matrix and then the solver solves it under that assumption. Hopefully there is a flag to turn of the positive definite check.

**Comment by Pristine-Cat** [comment]
Don't have time to look into this but probably a non-ideal case of expression goes to charpoly which does the dotprodsimp stuff. Try with environment variable set to confirm:
```
SYMPY_DOTPRODSIMP="0"
```

**Comment by moorepants** [comment]
Would the determinant check here: https://www.gaussianwaves.com/2013/04/tests-for-positive-definiteness-of-a-matrix/ be a better test than trying to calculate eigenvalues? This still all relies on checking if symbolic expressions are zero, which is not a generally solvable problem without assumptions on each symbol.

**Comment by oscarbenjamin** [comment]
Thanks. I tried `SYMPY_DOTPRODSIMP="0"` but it doesn't make any difference to the timing or the output in this case. The profile does show that dotprodsimp is called but it makes up a very small portion of the time and apparently does not affect the end result of `cholesky_solve`.

The change to `_cholesky_solve` in the identified commit (a8a3a3b) is:
```diff
@@ -263,21 +263,25 @@ def _cholesky_solve(M, rhs, dotprodsimp=None):
     pinv_solve
     """
 
+    if M.rows < M.cols:
+        raise NotImplementedError(
+            'Under-determined System. Try M.gauss_jordan_solve(rhs)')
+
     hermitian = True
+    reform    = False
 
     if M.is_symmetric():
         hermitian = False
-        L = M.cholesky(hermitian=hermitian, dotprodsimp=dotprodsimp)
-    elif M.is_hermitian:
-        L = M.cholesky(hermitian=hermitian, dotprodsimp=dotprodsimp)
-    elif M.rows >= M.cols:
-        L = M.H.multiply(M, dotprodsimp=dotprodsimp).cholesky(
-                hermitian=hermitian, dotprodsimp=dotprodsimp)
-        rhs = M.H.multiply(rhs, dotprodsimp=dotprodsimp)
-    else:
-        raise NotImplementedError('Under-determined System. '
-                                    'Try M.gauss_jordan_solve(rhs)')
+    elif not M.is_hermitian:
+        reform = True
 
+    if reform or M.is_positive_definite is False:
+        H         = M.H
+        M         = H.multiply(M, dotprodsimp=dotprodsimp)
+        rhs       = H.multiply(rhs, dotprodsimp=dotprodsimp)
+        hermitian = not M.is_symmetric()
+
+    L = M.cholesky(hermitian=hermitian, dotprodsimp=dotprodsimp)
     Y = L.lower_triangular_solve(rhs, dotprodsimp=dotprodsimp)
 
     if hermitian:
```
It seems that checking `is_positive_definite` leads to the slowdown.

**Comment by oscarbenjamin** [comment]
This diff more or less reverts the change to `cholesky_solve` from that commit and seems to fix the problem:
```diff
diff --git a/sympy/matrices/solvers.py b/sympy/matrices/solvers.py
index 7c40ad3cac..7196bab217 100644
--- a/sympy/matrices/solvers.py
+++ b/sympy/matrices/solvers.py
@@ -220,25 +220,21 @@ def _cholesky_solve(M, rhs):
     pinv_solve
     """
 
-    if M.rows < M.cols:
-        raise NotImplementedError(
-            'Under-determined System. Try M.gauss_jordan_solve(rhs)')
 
     hermitian = True
-    reform    = False
 
     if M.is_symmetric():
         hermitian = False
-    elif not M.is_hermitian:
-        reform = True
-
-    if reform or M.is_positive_definite is False:
-        H         = M.H
-        M         = H.multiply(M)
-        rhs       = H.multiply(rhs)
-        hermitian = not M.is_symmetric()
+        L = M.cholesky(hermitian=hermitian)
+    elif M.is_hermitian:
+        L = M.cholesky(hermitian=hermitian)
+    elif M.rows >= M.cols:
+        L = M.H.multiply(M).cholesky(hermitian=hermitian)
+        rhs = M.H.multiply(rhs)
+    else:
+        raise NotImplementedError('Under-determined System. '
+                                    'Try M.gauss_jordan_solve(rhs)')
 
-    L = M.cholesky(hermitian=hermitian)
     Y = L.lower_triangular_solve(rhs)
 
     if hermitian:
```

**Comment by oscarbenjamin** [comment]
That seems to pass all tests in matrices. It doesn't look like `cholesky_solve` is used directly in the rest of the codebase so maybe that will be fine.

I'm wondering though whether there are similar problems with other functions. It looks like the same sort of change was made in `LDL_solve` and maybe other places. Looking at the benchmarks it seems that only `cholesky_solve` is timed with this particular matrix. The other benchmarks all use the matrix `A` rather than `A_sym` which is symmetric.

**Comment by oscarbenjamin** [comment]
If anyone wants to think of a good way of doing this like perhaps the determinant suggestion from @moorepants then go ahead. Otherwise at some point I will just make a PR to revert some of the changes.

We should probably add more benchmarks.

**Comment by moorepants** [comment]
I support reverting. I prefer that the documentation warns the user that their matrix must be positive definite or you'll get bad results (garbage in - garbage out) over having these performance decreases.

**Comment by oscarbenjamin** [comment]
Maybe also `is_positive_definite` should be a lot faster. It doesn't take long to compute the eigenvalues of this matrix. But I see now that we don't compute the eigenvalues of this matrix because we get here:
https://github.com/sympy/sympy/blob/85810bb51de460e5d27ea24b22ed80b738366602/sympy/matrices/eigen.py#L670-L673
This means that when we get to compute the eigenvalues we aren't computing them for M but for
```
Matrix([
[a00/2 + conjugate(a00)/2, a01/2 + conjugate(a01)/2, a02/2 + conjugate(a02)/2],
[a01/2 + conjugate(a01)/2, a11/2 + conjugate(a11)/2, a12/2 + conjugate(a12)/2],
[a02/2 + conjugate(a02)/2, a12/2 + conjugate(a12)/2, a22/2 + conjugate(a22)/2]])
```
and computing eigenvalues of *that* matrix takes a lot longer:
https://github.com/sympy/sympy/blob/85810bb51de460e5d27ea24b22ed80b738366602/sympy/matrices/eigen.py#L644-L649

If we ultimately just compute the eigenvalues I'm not sure why we need to construct an alternative hermitian matrix first...

**Comment by Pristine-Cat** [comment]
If I recall correctly the non-positive definite case is detected in the cholesky algorithm directly and an exception thrown.

**Comment by moorepants** [comment]
But isn't impossible to calculate the eigenvalues of a 5x5 or larger matrix? The mechanics package easily has matrices that need fast Cholesky solves for matrices of 20, 30, 40 dimension etc.

**Comment by moorepants** [comment]
One other thing, can't the eigenvalues for a matrices of order 2 to 4 all be pre-computed?

**Comment by oscarbenjamin** [comment]
> But isn't it impossible to calculate the eigenvalues of a 5x5 or larger matrix?

It's not *necessarily* impossible (trivial example: the identity matrix). However there is not a general formula for 5x5 or bigger which means that it will often not be possible if there are free symbols and may involve "rootof" solutions if there are no free symbols.

> The mechanics package easily has matrices that need fast Cholesky solves for matrices of 20, 30, 40 dimension etc.

I'm guessing that these are relatively sparse, close to diagonal, have special structure etc so there is still a good chance that the eigenvalues can be computed.

In any case I think that the `is_positive_definite` routine catches the exception if the eigenvalues are not computed.

**Comment by moorepants** [comment]
> I'm guessing that these are relatively sparse, close to diagonal, have special structure etc so there is still a good chance that the eigenvalues can be computed.

Unfortunately that is not true.

**Comment by oscarbenjamin** [comment]
Out of interest why do you want a Cholesky solve rather than some other kind of solve?

**Comment by moorepants** [comment]
For positive definite matrices, Cholesky solve is supposed to be O(n^3/3) instead of O(2*n^3/3) for LU decomposition. Turns out that the mass matrix derived from the Newton-Euler equations is guaranteed to be positive definite for many cases, thus you can save half the computing costs for forming it.

**Comment by oscarbenjamin** [comment]
> Cholesky solve is supposed to be O(n^3/3) instead of O(2*n^3/3)

I would be surprised if that is noticeable among all the other performance variations in sympy (or in symbolic manipulation more generally).

**Comment by oscarbenjamin** [comment]
@moorepants it would be really useful to have some idea of performance in more realistic situations so if you have some Cholesky-heavy code to try out comparing master with 1.5 it would be great to know whether you see a difference.

**Comment by moorepants** [comment]
> I would be surprised if that is noticeable among all the other performance variations in sympy (or in symbolic manipulation more generally).

For larger and the mechanics package it matters in two ways: the solve could happen in 5 seconds instead of 10 and secondly the resulting expressions have half the operations and thus any numerical code generated from these expressions run twice as fast. The second part is a huge deal when you desire to evaluate the solution numerically millions and millions of times.

**Comment by moorepants** [comment]
Here is a test that requires pydy:

```python
from pydy.models import n_link_pendulum_on_cart
sys = n_link_pendulum_on_cart(n=4)
M = sys.eom_method.mass_matrix
F = sys.eom_method.forcing
M.LUsolve(F)
M.cholesky_solve(F)
```

Set `n` to higher numbers to get mass matrices of  that order.

**Comment by moorepants** [comment]
Here are a couple of examples:

```
In [12]: sys = n_link_pendulum_on_cart(n=10)                                                                                                                                                                                                                                              

In [13]: M = sys.eom_method.mass_matrix                                                                                                                                                                                                                                                   

In [14]: F = sys.eom_method.forcing                                                                                                                                                                                                                                                       

In [15]: %time sol = M.LUsolve(F)                                                                                                                                                                                                                                                         
CPU times: user 1.1 s, sys: 4 ms, total: 1.1 s
Wall time: 1.1 s

In [16]: %time sol = M.cholesky_solve(F)                                                                                                                                                                                                                                                  
CPU times: user 450 ms, sys: 0 ns, total: 450 ms
Wall time: 449 ms

In [17]: sys = n_link_pendulum_on_cart(n=20)                                                                                                                                                                                                                                              

In [18]: M = sys.eom_method.mass_matrix                                                                                                                                                                                                                                                   

In [19]: F = sys.eom_method.forcing                                                                                                                                                                                                                                                       

In [20]: %time sol = M.LUsolve(F)                                                                                                                                                                                                                                                         
CPU times: user 6.51 s, sys: 3.99 ms, total: 6.52 s
Wall time: 6.52 s

In [21]: %time sol = M.cholesky_solve(F)                                                                                                                                                                                                                                                  
```

The last one is still running after about 30 seconds.

**Comment by oscarbenjamin** [comment]
> Here is a test that requires pydy:

Thanks. I can confirm that that example is much slower on current master (I didn't wait for it to finish) because of the slowdown in `cholesky_solve` and the time seems to be spent computing the eigenvalues.

I think that example would make a good benchmark.

**Comment by sylee957** [comment]
I have brought up the speed up to some factors in #19205
but it is still a lot slow than 1 milliseconds
```
-         2.03±0s       49.5±0.3ms     0.02  solve.TimeMatrixSolve2.time_cholesky_solve
```

**Comment by oscarbenjamin** [comment]
> I have brought up the speed up

Thanks @sylee957. I don't think that closes this issue but it's a good improvement in any case.

**Comment by sylee957** [comment]
With the fuzzy test added in #19205 I have brought down up the speed comparable to the original.
`-         2.03±0s      1.69±0.01ms     0.00  solve.TimeMatrixSolve2.time_cholesky_solve`

**Comment by oscarbenjamin** [comment]
Thanks @sylee957. The benchmark itself is fairly trivial though. What happens if you use the pydy examples above for different n?

I've opened #19221 to revert the changes to `cholesky_solve` and `LDLsolve` and also added more benchmarks for the regression (including one pydy example) in https://github.com/sympy/sympy_benchmarks/pull/71

**Comment by oscarbenjamin** [comment]
I just tried with #19205 and the pydy example with n=4. On sympy-1.5 I get:
```julia
In [1]: from pydy.models import n_link_pendulum_on_cart 
   ...: sys = n_link_pendulum_on_cart(n=4) 
   ...: M = sys.eom_method.mass_matrix 
   ...: F = sys.eom_method.forcing                                                                                                                            

In [2]: %time ans = M.cholesky_solve(F)                                                                                                                       
CPU times: user 170 ms, sys: 3.8 ms, total: 173 ms
Wall time: 173 ms
```
On master that is slow in `is_positive_definite` (haven't waited for it to complete).

With #19205 I find that it is still slow but not in `is_positive_definite` (haven't waited for it to complete).

With #19221 which reverts the changes to `cholesy_solve` and `LDLsolve` it is still slow so there must be another performance regression. Oh, looks like I also need to revert changes to `cholesky`. With some extra changes (not pushed yet) I get:
```julia
In [2]: from pydy.models import n_link_pendulum_on_cart 
   ...: sys = n_link_pendulum_on_cart(n=4) 
   ...: M = sys.eom_method.mass_matrix 
   ...: F = sys.eom_method.forcing                                                                                                                            

In [3]: %time ans = M.cholesky_solve(F)                                                                                                                       
CPU times: user 234 ms, sys: 2.66 ms, total: 237 ms
Wall time: 236 ms
```

**Comment by oscarbenjamin** [comment]
After merging #19205 the benchmarks don't show any major regression but there is still a regression in `LDLsolve` which we can see using the systems generated by this function:
```python
# tim.py
import time

def makeMF(n):
    from pydy.models import n_link_pendulum_on_cart
    sys = n_link_pendulum_on_cart(n=n)
    M = sys.eom_method.mass_matrix
    F = sys.eom_method.forcing
    return M, F

for n in range(1, 10):
    M, F = makeMF(n)
    start = time.time()
    #M.cholesky_solve(F)
    M.LDLsolve(F)
    delta = time.time() - start
    print('n=%d time=%.2e secs' % (n, delta))
```

With sympy-1.5 we have this for cholesky/LDL:
```
$ python tim.py # cholesky
n=1 time=2.14e-02 secs
n=2 time=5.47e-02 secs
n=3 time=9.79e-02 secs
n=4 time=1.71e-01 secs
n=5 time=2.32e-01 secs
n=6 time=3.67e-01 secs
n=7 time=5.26e-01 secs
n=8 time=6.25e-01 secs
n=9 time=8.00e-01 secs

$ python tim.py   # LDL
n=1 time=1.42e-02 secs
n=2 time=4.04e-02 secs
n=3 time=7.61e-02 secs
n=4 time=1.43e-01 secs
n=5 time=2.27e-01 secs
n=6 time=3.37e-01 secs
n=7 time=4.74e-01 secs
n=8 time=6.44e-01 secs
n=9 time=8.39e-01 secs
```

With current master (after #19205) we have:
```
$ python tim.py # cholesky
n=1 time=2.31e-02 secs
n=2 time=6.78e-02 secs
n=3 time=6.66e+00 secs
^C
KeyboardInterrupt

$ python tim.py # LDL
n=1 time=1.51e-02 secs
n=2 time=8.80e-02 secs
^C
KeyboardInterrupt
```
I've added these examples with n=1,2,3 to the benchmarks in https://github.com/sympy/sympy_benchmarks/pull/71 but only n=1 is used with cholesky/LDL because the others were all too slow. There is improvement since #19205 but there is still a regression on master relative to sympy 1.5.

The regression now seems to be caused by the use of `expand_mul` in cholesky/LDL. The use of `expand_mul` is intended to help zero-detection and pivot finding in Gaussian elimination type routines. However I think it isn't needed in cholesky/LDL because the whole point is that pivoting is not needed in these algorithms.

I've tried this diff to remove the `expand_mul` calls:
```diff
diff --git a/sympy/matrices/decompositions.py b/sympy/matrices/decompositions.py
index ac1dbc00c3..000e5a2e51 100644
--- a/sympy/matrices/decompositions.py
+++ b/sympy/matrices/decompositions.py
@@ -257,7 +257,7 @@ def _cholesky(M, hermitian=True):
     if not hermitian and not M.is_symmetric():
         raise ValueError("Matrix must be symmetric.")
 
-    dps = _get_intermediate_simp(expand_mul, expand_mul)
+    dps = lambda x: x
     L   = MutableDenseMatrix.zeros(M.rows, M.rows)
 
     if hermitian:
@@ -460,7 +460,7 @@ def _LDLdecomposition(M, hermitian=True):
     if not hermitian and not M.is_symmetric():
         raise ValueError("Matrix must be symmetric.")
 
-    dps = _get_intermediate_simp(expand_mul, expand_mul)
+    dps = lambda x: x
     D   = MutableDenseMatrix.zeros(M.rows, M.rows)
     L   = MutableDenseMatrix.eye(M.rows)
```
With that we can recover something like the 1.5 speed:
```
$ python tim.py # cholesky
n=1 time=1.55e-02 secs
n=2 time=4.37e-02 secs
n=3 time=8.48e-02 secs
n=4 time=1.54e-01 secs
n=5 time=2.87e-01 secs
n=6 time=4.11e-01 secs
n=7 time=6.22e-01 secs
n=8 time=7.81e-01 secs
n=9 time=1.00e+00 secs

$ python tim.py # LDL
n=1 time=1.51e-02 secs
n=2 time=4.26e-02 secs
n=3 time=8.27e-02 secs
n=4 time=1.51e-01 secs
n=5 time=2.49e-01 secs
n=6 time=3.69e-01 secs
n=7 time=5.18e-01 secs
n=8 time=7.25e-01 secs
n=9 time=9.18e-01 secs
```

I think that we should:

1. apply something like that diff
2. also extend the benchmarks to test as many as possible of the matrix methods with these particular examples from pydy.

I think these examples represent a good benchmark of a realistic workload for matrices. I'm concerned that the changes like adding `expand_mul` have been applied quite broadly and it is clear that we didn't have good benchmarking coverage for this sort of case when the changes were made.

@sylee957 thank you for your help on this with #19205 and for closing other release blockers. If you want to work on the above then go ahead. Otherwise at some point I will do it.
