### ISSUE TITLE
'cosec' parsing error

### ISSUE THREAD

**Issue by sashaalesin** [sympy/sympy#19218]
```
>>> a = "cosec(x)"
>>> parse_expr(a)
cosec(x)
```
```
>>> transformations = (standard_transformations +
                   (implicit_multiplication_application,))
>>> a = "cosec(x)"
>>> parse_expr(a, transformations=transformations)
c**2*e*o*s*x
```
Maybe it's okay, but why parsing of 'cos(x)' or 'sec(x)' with this transformations give result not `c*o*s*x` and `s*e*c*x`?

**Comment by sylee957** [comment]
I don't think that `cosec` is a valid sympy function, but it works with `csc`

**Comment by sashaalesin** [comment]
Oh, okay, i'm sorry for this issue. Thank you!
