### ISSUE TITLE
Something is wrong in expression

### ISSUE THREAD

**Issue by proy87** [sympy/sympy#19211]
```
f=-2*x*sqrt(x + 4) + x*sqrt(2*x - 1) - 2*sqrt((x + 4)*(2*x - 1))*sqrt(x + 4) + 2*sqrt((x + 4)*(2*x - 1))*sqrt(2*x - 1)
s=-sqrt(1153)*cos(atan(108*sqrt(47319)/31319)/3)/9 - Integer(11)/18
f.subs(x,s).evalf()
```
Last operation clearly gives something close to 0, but `s` is not the root of `f`.

**Comment by smichr** [comment]
The value of s is negative and makes some sqrt imaginary but if they cancel and produce 0 why isn't it fair to consider s as a root?

**Comment by proy87** [comment]
My bad. Missed that.
