### ISSUE TITLE
Require the benchmarks to pass on Travis

### ISSUE THREAD

**Issue by oscarbenjamin** [sympy/sympy#19224]
For some time now the benchmark suite has been running on Travis as an allowed failure. They seem fairly stable and reliable. I haven't noticed any spurious failures from them and I've found them useful when investigating PRs that look like they might have performance implications. 

However the benchmarks are an allowed failure so even if they fail then Travis reports a successful build and the PR can still be merged. This also means that you won't see the benchmarks unless you explicitly go in to Travis to look for them.

In order to pick up on regressions like #19200 I think it would be good to make passing the benchmarks required for a successful Travis build. Then if a PR makes any benchmark fail (currently the threshold is set at a 50% increase in runtime) it will not be mergeable.

If it turns out to be problematic then we can try using a different threshold or make the benchmarks an allowed failure again.

I also think that we should use benchmarks for performance regressions in a similar way to regression tests. If a PR fixes a performance regression then a benchmark should be added if possible that demonstrates the fix.

Similarly if the purpose of any PR is to improve performance then I think we should normally expect relevant benchmarks to be added that demonstrate the improvement in performance before the PR is merged (if existing benchmarks don't already show the improvement).

**Comment by asmeurer** [comment]
If Travis can detect 50% regressions without false positives, that is great. I was thinking we would have to limit it to only 2x regressions or maybe even more. 

I also just found out that Pandas has a benchmarking CI. We should look at what they use and if we can reuse it. https://tomaugspurger.github.io/maintaing-performance.html https://github.com/asv-runner/asv-runner. CC @TomAugspurger

**Comment by oscarbenjamin** [comment]
Something else that might help would be timing the tests in the normal test suite and using the slow decorator to pick up on regressions:

1. The tests could fail if any slow test takes less than 10 seconds
2. The tests could fail if any not slow test takes more than 20 seconds

That would force keeping the slow decorators up to date and would also highlight where a test has significantly slowed down. There have been examples where a test that was not slow became very slow without anyone noticing: that's a missed opportunity to identify a regression.
