### ISSUE TITLE
as_poly() with GF(p) result in negative coefficient

### ISSUE THREAD

**Issue by carlushuang** [sympy/sympy#19240]
example:
```
from sympy import *
x = symbols('x')
f = 5*x**3+x+1
print(f.as_poly(domain='GF(3)'))
```
print as follow:
`Poly(-x**3 + x + 1, x, modulus=3)`
Here observe the `x**3` have negative coefficient `-1`

But from definition of Galois Field, the modulo should be positive integer right?

**Comment by jksuom** [comment]
The representatives of a finite field or ring can be chosen in two ways: either the representative of least absolute value or the least nonnegative one. It is controlled by the keyword `symmetric` that is `True` by default. To get the nonnegative representatives, you can write `f.as_poly(domain=GF(3, symmetric=False))`.

**Comment by carlushuang** [comment]
@jksuom Thanks got it, it works.
