### ISSUE TITLE
Simplification with sqrt and powers

### ISSUE THREAD

**Issue by sashaalesin** [sympy/sympy#19255]
![image](https://user-images.githubusercontent.com/22159301/81026306-5a4b5300-8e82-11ea-9080-70103f40a8c4.png)
```
x = var('x', positive=True)
```
i have an expression (integrand function):
```
r_1 = 1 / sqrt((x**2 - 4*x + 5)**3)
```
I get data from user and i want to check it:
```
u_1 = (x - 2)*(x**2 - 4*x + 5)/sqrt((x**2 - 4*x + 5)**3)
diff_u_1 = diff(u_1, x)
>>> (x - 2)*(2*x - 4)/sqrt((x**2 - 4*x + 5)**3) - (x - 2)*(6*x - 12)/(2*sqrt((x**2 - 4*x + 5)**3)) + (x**2 - 4*x + 5)/sqrt((x**2 - 4*x + 5)**3)
simplify(diff_u_1 - r_1)
>>> 0
```
Good! But if user write this:
```
u_2 = (x - 2)/sqrt(x**2 - 4*x + 5)
diff_u_2 = diff(u_2, x)
>>> (2 - x)*(x - 2)/(x**2 - 4*x + 5)**(3/2) + 1/sqrt(x**2 - 4*x + 5)
```
`diff_u_2` is equal to `r_1`, but i was use all of simplification functions and i can't get `diff_u_2 - r_1 = 0`.
Okay, maybe i need to rewrite `r`?
```
r_2 = 1 / (x**2 - 4*x + 5)**(3/2)
```
Yes, in this case
```
simplify(diff_u_2 - r_2)
>>> 0
```
But if user write this one more time:
```
u_1 = (x - 2)*(x**2 - 4*x + 5)/sqrt((x**2 - 4*x + 5)**3)
diff_u_1 = diff(u_1, x)
>>> (x - 2)*(2*x - 4)/sqrt((x**2 - 4*x + 5)**3) - (x - 2)*(6*x - 12)/(2*sqrt((x**2 - 4*x + 5)**3)) + (x**2 - 4*x + 5)/sqrt((x**2 - 4*x + 5)**3)
```
I can't get `diff_u_1 - r_2 = 0`.

Please, tell me which function can simplify `diff_u_1 - r_2` and `diff_u_2 - r_1` to `0`, i really have tried with `factor`, `powdenest`, `expand_power_base`, `expand_power_exp`, `cancel`, `powsimp`, `simplify` and it's combinations. Thanks!

**Comment by smichr** [comment]
`minpoly` confirms that these are zero; `unrad` suggests that it is so:
```python
>>> z=diff_u_1 - r_2
>>> minpoly(z)
_x
>>> unrad(z)
(0, [])

>>> eq2=diff_u_2 - r_1
>>> minpoly(z)
_x
>>> unrad(eq2)
(0, [])
```

**Comment by sashaalesin** [comment]
Thank you!
