### ISSUE TITLE
sympy.polys.factortools.dmp_zz_mignotte_bound improvement

### ISSUE THREAD

**Issue by lagamura** [sympy/sympy#19253]
The method `dup_zz_mignotte_bound(f, K)` can be significantly improved by using the **Knuth-Cohen bound** instead. After our research with Prof. Ag.Akritas we have implemented the Knuth-Cohen bound among others, and compare them among dozens of polynomials with different degree, density and coefficients range. Considering the results and the feedback from Mr.Kalevi Suominen, our proposal is that the mignotte_bound should be replaced by the knuth-cohen bound.
Also, `dmp_zz_mignotte_bound(f, u, K)` for mutli-variants polynomials should be replaced appropriately.

**Comment by jksuom** [comment]
Please send in a PR. It is not necessary to remove the old Mignotte bound method, it will suffice to implement a new one.

**Comment by lagamura** [comment]
After completing our job with `dup_zz_mignotte_bound(f, K)` we may try also fixing `dmp_zz_mignotte_bound(f, u, K)` as was said above. We try to understand how `dmp_degree_list(f, u)` works and what it returns on multi-variants polynomials. Could someone help us? Even better with some examples maybe?

**Comment by jksuom** [comment]
I think that you could ignore `dmp_zz_mignotte_bound`. I'm not sure that Mignotte bound is applicable to multivariate polynomials.

**Comment by smichr** [comment]
Just noting something here: I just read an [article that might be of interest](https://www.quantamagazine.org/new-math-measures-the-repulsive-force-within-polynomials-20200514/) in which in says,

>Dimitrov proved that all non-cyclotomic polynomials must have a root that’s at least log 2 divided by four times the degree of the polynomial outside the unit circle; that is, (log 2)/(4d)
