### ISSUE TITLE
`dummy_eq` failing for equal Sum

### ISSUE THREAD

**Issue by smichr** [sympy/sympy#19266]
`dummy_eq` should treat a Dummy variable in `self` as a Wild (actually or idiomatically) to see if two expressions are equivalent or not. The following test fails:
```python
from sympy import Sum, Dummy
from sympy.abc import x, a c
assert not Sum(x, (x, a, Dummy())).dummy_eq(Sum(x, (x, a, c)))
```
If `Dummy -> c` then the two are equivalent (and that is the purpose and intended output of the method)), so the current test is wrong. This is corrected in #19261.

And, of course, if that is fixed then the following is wrong (and fixed by #19261, too) since `x` and `y` are structurally bound symbols whose identity does not matter mathematically:
```python
from sympy import Sum, Dummy
from sympy.abc import x, a c
assert not Sum(x, (x, a, Dummy())).dummy_eq(Sum(y, (y, a, c)))
```

**Comment by oscarbenjamin** [comment]
I guess I thought of `dummy_eq` as comparing "modulo Dummy symbols" so a non-Dummy would not be expected to match a Dummy.

**Comment by oscarbenjamin** [comment]
The suggestion her makes it so that a `Dummy` takes the role of a `Wild` in `match`. But we already have match and I didn't think that was the purpose of `dummy_eq`.

I guess I viewed `dummy_eq` as having this purpose: expressions involving `Dummy` don'e compare equal even if they are created with the same expression so you compare them with `dummy_eq which compares modulo the identity of the Dummies.

If we are changing the meaning here then what is the *purpose* of `dummy_eq`?

**Comment by smichr** [comment]
The default behavior is to match Dummy on `self` to symbols on the right. The purpose of `dummy_eq` was to make easy the comparison of expressions that acquire Dummy symbols (e.g. `dsolve`) with an expected form that is written in terms of user-defined Symbols. e.g. 
```
(_C1 + 2*x).dummy_eq(c + 2*x) -> True
```
The enhanced behavior is to let the user select one (or more in the referenced PR) symbol of any type in the `other` arg and see if it can be matched to a symbol on the left.

In either case, conversion of structurally bound symbols to canonical form is also done or else matching other symbols would fail, i.e. `Sum(x, (x, 1, a)).match(Sum(y, (y, 1, W_)))` will fail.

> expressions involving `Dummy` don'e compare equal even if they are created with the same expression so you compare them with `dummy_eq which compares modulo the identity of the Dummies

This would be very restricted but I could see the benefit of this: matching Dummy -> Dummy. Since you have to write an expression to compare to something that has Dummies in it you might as well create new Dummy symbols to match. If you like this idea then perhaps we could split the functionality at present to

dummy_eq: `Dummy<-Dummy` matching
struct_eq: `symbol <- specified symbol` matching, e.g. (a + 2).struct_eq(b + 2, b) # same when b treated like Wild

Both would still have to make bound symbols canonical before doing the comparison (this just clarifying why we would have `struct_eq` instead of simply `match`).

**Comment by smichr** [comment]
But thinking more about this...I think the original intent must have been to match Dummy to Dummy unless the `symbol` was specified (in which case the specified symbol in `other` would be treated like a Dummy). This is an unecessary restriction.

**Comment by smichr** [comment]
@jksuom , do you have any ideas here? Should `dummy_eq` be enhanced to allow for general structural-equality testing or should it be limited to Dummy<->Dummy matching. Right now it allows Dummy<-Symbol matching in addition to Dummy<->Dummy but maybe that should be deprecated in favor of a function that does generic Symbol<-Symbol matching which, if we make `match` ignore bound symbols, would just be a light modification to a matching query that replaces all symbols of one expression (`other`) with Wild so the expression can be tested against the reference expression.

**Comment by jksuom** [comment]
The docstring of dummy_eq does not say so much but it seems to me that the method is actually used to test "equality up to bound variables", i.e., whether two expressions are the same except that their bound variables may have different names. I think that the type of the bound variables, Dummy or Symbol, should not matter. Maybe the name of the method should be changed to avoid confusion.

**Comment by smichr** [comment]
> except that their bound variables may have different names

It really intended to make matching expressions with generated dummies easier. I hope the version in #19261 clarifies the operation better and separates its behavior from `match`.

**Comment by jksuom** [comment]
> It really intended to make matching expressions with generated dummies easier.

So it is not exactly what I had expected? Maybe there should be another method for testing equality up to bound variables. That would be the one to be used for comparing Sums etc. instead of `dummy_eq`.

**Comment by oscarbenjamin** [comment]
I think the difficulty is that regardless of the docstring the actual behaviour of `dummy_eq` does two different things:

1. It compares modulo Dummy symbols to compensate for the fact that they normally compare unequal.
```
In [1]: e1 = 1 + Dummy()                                                                                                                       

In [2]: e2 = 1 + Dummy()                                                                                                                       

In [3]: e1 == e2                                                                                                                               
Out[3]: False

In [4]: e1.dummy_eq(e2)                                                                                                                        
Out[4]: True
```
2. It compares modulo bound symbols whether they are Dummy or not.
```
In [5]: i1 = Integral(x, (x, 1, 2))                                                                                                            

In [6]: i2 = Integral(y, (y, 1, 2))                                                                                                            

In [7]: i1 == i2                                                                                                                               
Out[7]: False

In [8]: i1.dummy_eq(i2)                                                                                                                        
Out[8]: True
```
I think that it makes sense to put those two behaviours together in one function although it's not quite what I would want in the main use case for `dummy_eq` which is in testing. Looking at `git grep dummy_eq` it seems the only uses of `dummy_eq` in the sympy codebase are in tests.

For testing purposes there is no need to compare modulo bound symbols: the test can be written with the expected bound symbols. A function to compare modulo dummies is needed because we can't use `assert f(input) == output` when the output has `Dummy` symbols.

**Comment by smichr** [comment]
I suppose we only use it in testing and not, for example, in Eq is because of caching: we wouldn't want to store an arbitrary expression for a given expression. I think I ran into the trouble with some other object (Lambda?).

If "it makes sense to put those two behaviours together in one function" then we have that now: a function which will ignore the identity of structural dummies (bound symbols) and actual Dummy symbols.

> For testing purposes there is no need to compare modulo bound symbols

Agree. And the ode suite (a.k.a "my mnemesis") is a punishing gauntlet for test handling.

Part of the rational for this function is that it is a special case of matching wherein we seek a symbol->symbol match, not an arbitrary symbol->expr.

Whether it is better to split `dummy_eq` into pure `Dummy->Dummy` matching and 1:1 symbol matching is still an open question. Note that tests for Poly-with-Dummy-gen use `dummy_eq` like `minpoly(x).dummy_eq(x)` so that could be `minpoly(x).sym_eq(x)` (or something like that).

**Comment by smichr** [comment]
> the actual behaviour of `dummy_eq` does two different things:

The most helpful thing it does is compare modulo bound symbols.

This issue should probably not be fixed by modifying `dummy_eq` to handle more than one Dummy symbol. And if it's not, then `dummy_eq` is not the function to test for a "match" between the Sums of the OP.
