### ISSUE TITLE
Bspline error with symbolic knots

### ISSUE THREAD

**Issue by markdewing** [sympy/sympy#19262]
The following code uses a symbolic value in the knots, and results in an error
```
from sympy import *
x = Symbol('x')

Delta = Symbol('Delta',positive=True)
knots = [i*Delta for i in range(4)]

basis = bspline_basis_set(1, knots, x)
print(basis)
```
The error is
```
Traceback (most recent call last):
  File "bspline_sym.py", line 11, in <module>
    basis = bspline_basis_set(1, knots, x)
  File "/home/sympy/git2/sympy/sympy/functions/special/bsplines.py", line 210, in bspline_basis_set
    return [bspline_basis(d, tuple(knots), i, x) for i in range(n_splines)]
  File "/home/sympy/git2/sympy/sympy/functions/special/bsplines.py", line 210, in <listcomp>
    return [bspline_basis(d, tuple(knots), i, x) for i in range(n_splines)]
  File "/home/sympy/git2/sympy/sympy/functions/special/bsplines.py", line 166, in bspline_basis
    result = _add_splines(A, b1, B, b2)
  File "/home/sympy/git2/sympy/sympy/functions/special/bsplines.py", line 50, in _add_splines
    elif lower_2 < lower and upper_2 <= lower:
  File "/home/sympy/git2/sympy/sympy/core/relational.py", line 384, in __nonzero__
    raise TypeError("cannot determine truth value of Relational")
TypeError: cannot determine truth value of Relational
```

The code in bsplines.py decomposes the conditionals in the Piecewise expression, and expects each side of the conditional to be in particular order - the rhs is expected to the numerical (or fixed) value.
This order is respected in cases where the knots are numbers, or where the knots are expressions.   When a knot is an individual symbol the order changes and break expectations.

The issue appears because the bare symbol `Delta` is a knot.   If the range is changed to something like `range(2,5)`, then the issue does not appear because every knot is a multiplicative expression.

A workaround is to multiply the knots by a dummy symbol and remove the symbol later.
```
dummy = Symbol('dummy',positive=True)
knots = [i*Delta*dummy for i in range(4)]
print(knots)
basis = bspline_basis_set(1, knots, x)
basis = [b.subs(dummy, 1) for b in basis]
print(basis)
```

**Comment by smichr** [comment]
> The code in bsplines.py decomposes the conditionals in the Piecewise expression, and expects each side of the conditional to be in particular order

The code for the `bspline_basis` calls `_add_splines` with Piecewise objects. A better strategy would be to store the expr and range data as a list of tuples, `(expr, (low, high))`, pass that to the `_add_splines` and at the end of `bsplines_basis`, return a Piecewise. It is too fragile to expect the Piecewise to be in a certain state. You can see this by making the assumption that `x` is `nonnegative`...a new error will arise because the Relational, `x >= 0` evaluates to True so the first `And` becomes a single Relational and violates the assumptions of the `_add_splines` routine.

I suspect that your idea of multiplying by a dummy works because it keeps the Relational in the expected order by making the canonical representation match the expected order.

**Comment by smichr** [comment]
If `x` is passed to `_add_splines` and the intial lines of that function are changed to this:
```python
def _add_splines(c, b1, d, b2, x):
    """Construct c*b1 + d*b2."""
    def iv(cond):
        """return the interval corresponding to the condition

        Conditions of Piecewise are And objects
        (or a single Relational if assumptions are made on
        x so that x >= 0 evaluates). When an And, the non-x
        arguments must be sortable (e.g. positive); they specify
        the interval of the expression for the spline.
        """
        from sympy.logic.boolalg import And
        def nonx(r):
            return r.lhs if r.rhs == x else r.rhs
        if cond.is_Relational:
            return (S.Zero, nonx(cond))
        if isinstance(cond, And):
            return sorted(list(map(nonx, cond.args)))
        raise TypeError('unexpected cond type: %s' % cond)
    if b1 == S.Zero or c == S.Zero:
        rv = piecewise_fold(d * b2)
    elif b2 == S.Zero or d == S.Zero:
        rv = piecewise_fold(c * b1)
    else:
        new_args = []
        # Just combining the Piecewise without any fancy optimization
        p1 = piecewise_fold(c * b1)
        p2 = piecewise_fold(d * b2)

        # Search all Piecewise arguments except (0, True)
        p2args = list(p2.args[:-1])

        # This merging algorithm assumes the conditions in
        # p1 and p2 are sorted
        for arg in p1.args[:-1]:
            expr = arg.expr
            cond = arg.cond

            lower = iv(cond)[0]

            # Check p2 for matching conditions that can be merged
            for i, arg2 in enumerate(p2args):
                expr2 = arg2.expr
                cond2 = arg2.cond

                lower_2, upper_2 = iv(cond2)
...
```

and the call is changed from `result = _add_splines(A, b1, B, b2)` to `result = _add_splines(A, b1, B, b2, x)` then the following two tests do not raise:
```python
x = Symbol('x')
Delta = Symbol('Delta',positive=True)
knots = [i*Delta for i in range(4)]
basis = bspline_basis_set(1, knots, x)
y=Symbol('y',nonnegative=True)
Delta = Symbol('Delta',positive=True)
knots = [i*Delta for i in range(4)]
basis2 = bspline_basis_set(1, knots, y)
assert basis[0].subs(x,y) == basis2[0]
```

**Comment by markdewing** [comment]
@smichr Thanks for fixing this!
