### ISSUE TITLE
Rewrite sign as abs

### ISSUE THREAD

**Issue by oscarbenjamin** [sympy/sympy#19277]
In sympy the `sign` function is defined as
```
    sign(z)  :=  z / Abs(z)
```
for all complex non-zero `z`. There should be a way to rewrite the sign in terms of `Abs` e.g.:
```
>>> sign(x).rewrite(Abs)                                                                                                                   
 x 
───
│x│
```
I'm not sure how the possibility of `x` being zero should be handled currently we have
```
>>> sign(0)                                                                                                                               
0
>>> 0 / Abs(0)                                                                                                                            
nan
```
Maybe `sign(0)` should be `nan` as well. Otherwise maybe rewrite as Abs would have to be careful about the possibility of the arg being zero (that would make the rewrite fail in most cases).

**Comment by smichr** [comment]
Getting nan for `sign(0)` would be pretty [non-intuitive](https://en.wikipedia.org/wiki/Sign_function) for any mathematical programmer given it's non-derivative definition.

If a rewrite request cannot be fulfilled under all conditions and the request was not for Piecewise, I think the rewrite should return None.

**Comment by oscarbenjamin** [comment]
Actually I think it's fine if the rewrite doesn't always work. At least something like this could rewrite:
```julia
In [2]: sign(1+I).rewrite(Abs)                                                                                                                 
Out[2]: sign(1 + ⅈ)
```

**Comment by sylee957** [comment]
You can use piecewise like
```
Piecewise(
    (0, Eq(x, 0)),
    (x / Abs(x), Ne(x, 0))
)
```

**Comment by oscarbenjamin** [comment]
Originally this question comes from SO:
https://stackoverflow.com/questions/61676438/integrating-and-deriving-absolute-functions-sympy/61681347#61681347

The original question was about `diff(Abs(x))`:
```
In [2]: x = Symbol('x', real=True)                                                                                                             

In [3]: Abs(x).diff(x)                                                                                                                         
Out[3]: sign(x)
```
Maybe the result from `diff` should be a `Piecewise` or at least an `ExprCondPair` guarding against `x=0`.

**Comment by jksuom** [comment]
The problem is that real-valued functions like abs, re, im, arg,... are not holomorphic and have no complex derivative. See also https://github.com/sympy/sympy/issues/8502.

**Comment by dhruvmendiratta6** [comment]
@jksuom could we add conditions in the `Derivative` class of the functions module which would check if the expression is an instance of a non-holomorphic function, in such a case it could raise an error or in the case of `Abs` simply  check the domain. I believe all the classes in `sympy/functions/elementary/complexes.py` could be checked.

**Comment by jksuom** [comment]
Would it be possible to add an `_eval_derivative` method raising an error to those functions?

**Comment by oscarbenjamin** [comment]
When would it raise?

**Comment by jksuom** [comment]
If the function is non-holomorphic, there is no derivative to be returned.

**Comment by oscarbenjamin** [comment]
There is a reasonable derivative of `Abs` when defined over the reals though e.g.:
```julia
In [1]: x = Symbol('x', real=True)                                                                                                

In [2]: Abs(x).diff(x)                                                                                                            
Out[2]: sign(x)
```

**Comment by jksuom** [comment]
Maybe there should be two functions, one defined on reals and the other on complexes.

**Comment by dhruvmendiratta6** [comment]
> Would it be possible to add an `_eval_derivative` method raising an error to those functions?

In the `Derivative` class in `sympy.function`?



> When would it raise?

As suggested, if the function is non-holomorphic or in the case of `Abs()` it could be a check on the domain of the argument.


> Maybe there should be two functions, one defined on reals and the other on complexes.

I am not sure if there are any non-holomorphic functions on Real numbers. In my opinion only the `Abs()` function would fall in this case. Hence I think this could be done using one function only.

**Comment by dhruvmendiratta6** [comment]
```
def _eval_derivative(self, expr):
    if isinstance(expr,[re, im, sign, arg, conjugate]):
	raise TypeError("Derivative not possible for Non-Holomorphic functions")
    if isinstance(expr,Abs):
	if Abs.arg[0].free_symbols.is_complex:
	    raises TypeError("There is a complex argument which makes Abs non-holomorphic")
```
This is something I was thinking but I am not sure about it as `Derivative` class already has a method with the same name. I also think that appropriate changes also need to be made in the `fdiff()` method of the `Abs` class.
@jksuom I wanted to know if there are more non-holomorphic functions in sympy/functions/elementary/complexes.py to which an error can be raised.

**Comment by jksuom** [comment]
Those functions in complexes.py have a `_eval_derivative` method. Maybe that would be the proper place for raising an error if that is desired.

**Comment by oscarbenjamin** [comment]
Are there any other examples of functions that raise when differentiated?

I just tried
```julia
In [83]: n = Symbol('n', integer=True, positive=True)                                                                             

In [84]: totient(n).diff(n)                                                                                                       
Out[84]: 
d             
──(totient(n))
dn 
```

**Comment by dhruvmendiratta6** [comment]
@oscarbenjamin I am not sure if this is a situation when it should raise, for example: if `n` here is a prime number the derivative wrt `n` would hence be `1` . Although in sympy 
```
>>> x = Symbol('x', real=True, prime=True)
>>> totient(x).evalf()
ϕ(x)
```
is the output and not `x-1`.Maybe this kind of functionality can be added.
@jksuom I think your way is correct and wanted to ask if the error to be raised is appropriately `TypeError`?

**Comment by oscarbenjamin** [comment]
I don't think that the totient function should be differentiable. I was just trying to think of functions where it might be an error to differentiate them.

I think it's better to leave the derivative of Abs unevaluated. You might have something like `Abs(f(x))` where `f` can be substituted for something reasonable later.

**Comment by jksuom** [comment]
@dhruvmendiratta6 Yes, I think that `TypeError` would be the appropriate choice. Note, however, that raising errors would probably break some tests. It may be desirable to add some try-except blocks to handle those properly.

**Comment by oscarbenjamin** [comment]
What about something like this:
```julia
In [21]: x = Symbol('x', real=True)                                                                                               

In [22]: f = Function('f')                                                                                                        

In [23]: e = Derivative(Abs(f(x)), x)                                                                                             

In [24]: e                                                                                                                        
Out[24]: 
d         
──(│f(x)│)
dx        

In [25]: e.subs(f, cosh)                                                                                                          
Out[25]: 
d          
──(cosh(x))
dx         

In [26]: e.subs(f, cosh).doit()                                                                                                   
Out[26]: sinh(x)
```

**Comment by dhruvmendiratta6** [comment]
@oscarbenjamin From what I understand you are suggesting that `diff()` should not be evaluating `Abs` by default and maybe `doit()` should be used to evaluate it. I think it is evaluated by default due to https://github.com/sympy/sympy/blob/0f598f042929f9de97bd8ba25ac06a0e4d36881b/sympy/core/expr.py#L3450-L3452 
and
https://github.com/sympy/sympy/blob/7c11a00d4ace555e8be084d69c4da4e6f4975f64/sympy/core/function.py#L2431-L2434
as `Abs()` does not have a `diff()` method itself. I think `diff` could be defined for `Abs` but I am not sure about it being a possible solution to the problem.

**Comment by dhruvmendiratta6** [comment]
@jksuom Any suggestion on how this can be done?

**Comment by asmeurer** [comment]
I think rewrite in general can't avoid having situations where things are only defined correctly in the limit, unless we return a Piecewise. For example, `sinc(x).rewrite(sin)`.

**Comment by asmeurer** [comment]
```py
>>> pprint(sinc(x).rewrite(sin))
⎧sin(x)
⎪──────  for x ≠ 0
⎨  x
⎪
⎩  1     otherwise
```

**Comment by dhruvmendiratta6** [comment]
I made `_eval_rewrite_as_Abs()` for the `sign` class which gives the following:
```
>>> sign(x).rewrite(Abs)
Piecewise((0, Eq(x, 0)), (x/Abs(x), True))
```
Although as discussed earlier raising an error in `_eval_derivative()` causes some tests to break :
```
File "c:\users\mendiratta\sympy\sympy\functions\elementary\tests\test_complexes.py", line 414, in test_Abs
    assert Abs(x).diff(x) == -sign(x)
 File "c:\users\mendiratta\sympy\sympy\functions\elementary\tests\test_complexes.py", line 833, in test_derivatives_issue_4757
    assert Abs(f(x)).diff(x).subs(f(x), 1 + I*x).doit() == x/sqrt(1 + x**2)
 File "c:\users\mendiratta\sympy\sympy\functions\elementary\tests\test_complexes.py", line 969, in test_issue_15893
    assert eq.doit() == sign(f(x))
```
The first two are understood but in the third one both `f` and `x` are real and still are caught by the newly raised error which doesn't make sense as I raised a `TypeError` only if the argument is not real.

**Comment by dhruvmendiratta6** [comment]
Can someone checkout the PR. Tests seem to have been passed but it still shows some checks are pending.
