### ISSUE TITLE
Simple Trigonometric Equation

### ISSUE THREAD

**Issue by carlos-contreras-velasquez** [sympy/sympy#19278]
Hi, any help or explanation about this?

for the following code lines:

import sympy as sp
x, y = sp.symbols('x y')
sp.solveset(sp.sin(x)-1/2,x,domain=sp.Reals)

I get the right answer in sympy.live.org (and written in symbols).

but I get empty set, when I run it in my computer (either in jupyter or qtconsole).
and I have the same version (1.5.1) in both cases.

If I use solve instead solveset, as:

sp.solve(sp.sin(x)-1/2,x)

I get the right answer in symy.live.org, even written in symbols, but limited
to the [0,2pi] interval.

In my computer I get those numbers as well, but numerical.

So, solveset fails in my computer, in jupyter and qtconsole, even having the same version.
A solve gives me something, but not the fancy symbolic answer you can get in sympy.live.
What could be going on?

Thanks a lot.
Carlos

**Comment by smichr** [comment]
Try replace 1/2 with `S.Half`; I think live does this automatically.

**Comment by carlos-contreras-velasquez** [comment]
Wow! Thanks a lot. That works like a charm. Now, is it possible to automatize that for all or most rational numbers.
