### ISSUE TITLE
[GSoC Discussion] Adding Poisson Process

### ISSUE THREAD

**Issue by Smit-create** [sympy/sympy#19274]
Currently, we have DTMC, CTMC, and Bernoulli Process as the stochastic processes in `stats/stochatic_process_types.py`. Therefore, I plan to add more such processes.
We can divide(for API discussion) the stochastic processes into two categories:

**Case 1**  The processes which follow certain distribution at any time t:
(i) Poisson Process -> Poisson Distribution
(ii) Gamma Process -> Gamma Distribution
(iiI) Wiener Process -> Normal Distribution
(iv) Bernoulli Process -> Bernoulli Distribution(0/1) (Implemented)
(v) Random Walks -> Bernoulli Distribution(-1/1)

**Case 2** The processes which have no distribution:
(i) Birth Death process (should be inherited from CTMC)

So, for **Case 1** we can create a generalized framework to calculate( Expectation and Probability), in order to avoid the repetition of code in each of the classes. As, in Bernoulli Process, we will convert the Random Indexed RV to simple RV with the same name and distribution (As we already have ready-made functions for simple RV for calculating E and P) and return the E and P.

For **Case 2**, we already have P and E in CTMC and requires testing of its generalization.

ping @czgdp1807 @Upabjojr @jmig5776

**Comment by czgdp1807** [comment]
I'd suggest to move with designing APIs with the help of some use cases(like picking up examples from textbooks, wikipedia, research papers). In addition, some processes can be built on top of Markov chains.

**Comment by Smit-create** [comment]
For, the examples of using the processes in the **Case 1**, I have found some real-life example problems related to them [here](https://www.probabilitycourse.com/chapter11/11_1_2_basic_concepts_of_the_poisson_process.php)

Suppose if we take example 1 from the given link, then we could possibly solve it as:
```python
>>> from sympy import Eq, S
>>> from sympy.stats import PoissonProcess , P
>>> X = PoissonProcess ('X', lamda=10)
>>> P(Eq(X(S(1)/3), 2))
xxxxx         
```
In the same way, we could solve the examples of other processes too.

Therefore, the API will be the same as the API of simple RV/ simple distribution classes as in `*_types.py`, i.e, at the initialization, we need to provide the parameters that are necessary to define the distribution of the Process. The only internal difference here would be on the developer side to take care of the distribution as they vary with the time. But at the user end, we will have the same API as we have for simple RV.

For the implementation details:
https://github.com/sympy/sympy/blob/585377cc1f8876fec65968dacffd284a4572b3c9/sympy/stats/stochastic_process.py#L49-L63
As we point to the individual classes to handle the expectation and probability of the indexed RV, we need to define these methods in the respective process classes. So, to calculate E and P of expression of indexed RV using the available functions in stats, we need to convert them to simple RV with the same name and distribution and indexed RV.
So, we will globally define two functions say, `_expectation_stoch` and `_probablility_stoc`, 
(i) which will take the expression of the indexed RV, 
(ii) covert it to simple RV expression based on given process.
(iii) calculate E/P and return to the calling method of respective process classes.

Therefore all the processes in **Case 1** will commonly share two functions, which will avoid us from code repetition. 
So, it will be like:
```python

class ProcessName(...):
    def __init__(...):
        pass

    @property
    def symbol(self):
        pass

    @property
    def state_space(self):
        pass

    def distribution(self):
        pass

    def expectation(...):
        return _expectation_stoch(...)

    def probability(...):
        return _probability_stoch(...)
```

**Comment by czgdp1807** [comment]
How will we solve the following part of Example 11.2 in the same link,
```
Given that the third arrival occurred at time t=2, find the probability that the fourth arrival occurs after t=4.
```

**Comment by Smit-create** [comment]
> `Given that the third arrival occurred at time t=2, find the probability that the fourth arrival occurs after t=4.`

Consider, PP as Poisson process with `lamda=2`
X1 = PP(1)
X2 = PP(2)
X05 = PP(0.5)
We can use as :
```python

>>> X05 = Poisson('X05', 2*0.5)
>>> X2 = Poisson('X2', 2*2)
>>> P(Eq(X05, 1))
exp(-1)  # Answer of 'a' there will be 1st arrival at time 0.5 secs
>>> P(Eq(X2, 0))
exp(-4)  # Answer of 'c' as there will be no arrival between t=2 and t=4, so using memory less property
```
They can be done in the above way, if we want to handle them directly as `P(Eq(X4, 4), Eq(X2, 3))`
then we need to add some additional code which will handle the memoryless property( can't be directly converted to simple RV as it will treat both of them independent and will generate wrong answer.)

**Comment by czgdp1807** [comment]
What about?
```python
>>> N = PoissonProcess('N', 2)
>>> P(Eq(N(4), 4), Eq(N(2), 3))
```

**Comment by Smit-create** [comment]
Converting them to simple RV, will consider them as independent and produce an incorrect result. So, we need to add some code to apply the memory less property by which it gets converted to
```python
>>> P(Eq(N(2), 0)
```

**Comment by czgdp1807** [comment]
> Converting them to simple RV

Where are they converted to simple RVs? I think we are just discussing how the interface should like. `N(t)` should be handled by `probability` to forward the call to the method of `PoissonProcess` which will solve the given query.

**Comment by czgdp1807** [comment]
I think that `probability` methods of each sub-class of stochastic processes should be able to handle the queries. If there is anything common down the hierarchy in these methods then that should be factored out and placed into the parent class.

**Comment by Smit-create** [comment]
> Where are they converted to simple RVs? I think we are just discussing how the interface should like.

I understand I am trying to explain how we will use the available E and P if possible to use in our code. When the call will go to the method of the given process, I think this should happen,
(i) Using the given condition, we will apply memoryless property, and convert `P(expr, condition)` to `P(expr_new)` which satisfies the given conditions. We will then solve P(expr_new).

For, solving `P(expr_new)` we need to decide whether to implement new method or use the existing ones, as we had used while adding Bernoulli Process

**Comment by Smit-create** [comment]
> We should just make the interface as good as possible and then discuss about the details of implementation

The interface will allow handling the queries in the same way, as in the current implementation,
```python
>>> N = PoissonProcess('N', 2)
>>> P(Eq(N(4), 4), Eq(N(2), 3))
# This will produce required answer of 'c'
>>> P(Eq(N(0.5), 1)
# This will produce required answer of 'a'
```

**Comment by Smit-create** [comment]
I will try to give an running example by tomorrow.

**Comment by Smit-create** [comment]
I have just tried to provide a rough idea of how this can, and will be improved:
```python
from sympy.stats import Poisson, Gamma, Bernoulli, Normal

dict_rv_subs = {'Poisson': lambda rv: Poisson(rv.name, lamda=rv.pspace.process.lamda*rv.key),
                'Wiener': lambda rv: Normal(rv.name, mean=0, std=sqrt(rv.key)),
                'Bernoulli': lambda rv: Bernoulli(rv.name, p=rv.pspace.process.p, succ=rv.pspace.process.success, fail=rv.pspace.process.failure),
                'RandomWalk': lambda rv: Bernoulli(rv.name, p=rv.pspace.process.p, succ=1, fail=-1),
                'Gamma': lambda rv: Gamma(rv.name, theta=1/rv.pspace.process.jump_size, k=rv.pspace.process.jump_rate*rv.key)
               }


def _rvindexed_subs(process, expr, condition=None):
        """
        Substitutes the RandomIndexedSymbol with the RandomSymbol with
        same name, distribution and probability as RandomIndexedSymbol.

      Parameters
      ==========

      process : str
           Key value of dict_rv_subs RandomVariable used to substitute
      expr: RandomIndexedSymbol, Relational, Logic
            Condition for which expectation has to be computed. Must
            contain a RandomIndexedSymbol of the process.
      condition: Relational, Logic
            The given conditions under which computations should be done.

        """

        rvs_expr = random_symbols(expr)
        if len(rvs_expr) != 0:
            swapdict_expr = {}
            for rv in rvs_expr:
                if isinstance(rv, RandomIndexedSymbol):
                    newrv = dict_rv_subs[process](rv)
                    swapdict_expr[rv] = newrv
            expr = expr.subs(swapdict_expr)
        rvs_cond = random_symbols(condition)
        if len(rvs_cond)!=0:
            swapdict_cond = {}
            for rv in rvs_cond:
                if isinstance(rv, RandomIndexedSymbol):
                    newrv = dict_rv_subs[process](rv)
                    swapdict_cond[rv] = newrv
            condition = condition.subs(swapdict_cond)
        return expr, condition


def _expectation_stoch(process, expr, condition=None, evaluate=True, **kwargs):
        """
        Computes expectation.

        Parameters
        ==========


      process : str
           Key value of dict_rv_subs RandomVariable used to substitute
        expr: RandomIndexedSymbol, Relational, Logic
            Condition for which expectation has to be computed. Must
            contain a RandomIndexedSymbol of the process.
        condition: Relational, Logic
            The given conditions under which computations should be done.

        Returns
        =======

        Expectation of the RandomIndexedSymbol.

        """
        new_expr, new_condition = _rvindexed_subs(process, expr, condition)

        new_pspace = pspace(new_expr)
        if new_condition is not None:
            new_expr = given(new_expr, new_condition)
        if new_expr.is_Add:  # As E is Linear
            return Add(*[new_pspace.compute_expectation(
                        expr=arg, evaluate=evaluate, **kwargs)
                        for arg in new_expr.args])
        return new_pspace.compute_expectation(
                new_expr, evaluate=evaluate, **kwargs)

def _probability_stoch(process, condition, given_condition=None, evaluate=True, **kwargs):
        """
        Computes probability.

        Parameters
        ==========

      process : str
           Key value of dict_rv_subs RandomVariable used to substitute
        condition: Relational
                Condition for which probability has to be computed. Must
                contain a RandomIndexedSymbol of the process.
        given_condition: Relational/And
                The given conditions under which computations should be done.

        Returns
        =======

        Probability of the condition.

        """
        new_condition, new_givencondition = _rvindexed_subs(process, condition, given_condition)

        if isinstance(new_givencondition, RandomSymbol):
            condrv = random_symbols(new_condition)
            if len(condrv) == 1 and condrv[0] == new_givencondition:
                return BernoulliDistribution(_probability_stoch(new_condition), 0, 1)

            if any([dependent(rv, new_givencondition) for rv in condrv]):
                return Probability(new_condition, new_givencondition)
            else:
                return _probability_stoch(new_condition)

        if new_givencondition is not None and \
                not isinstance(new_givencondition, (Relational, Boolean)):
            raise ValueError("%s is not a relational or combination of relationals"
                    % (new_givencondition))
        if new_givencondition == False:
            return S.Zero
        if new_condition == True:
            return S.One
        if new_condition == False:
            return S.Zero
        if not isinstance(new_condition, (Relational, Boolean)):
            raise ValueError("%s is not a relational or combination of relationals"
                    % (new_condition))
        if new_givencondition is not None:  # If there is a condition
        # Recompute on new conditional expr
            return _probability_stoch(process, given(new_condition, new_givencondition,evaluate=evaluate, **kwargs), **kwargs)
        result = pspace(new_condition).probability(new_condition, **kwargs)
        if evaluate and hasattr(result, 'doit'):
            return result.doit()
        else:
            return result

class PoissonProcess(ContinuousTimeStochasticProcess):
    index_set = _set_converter(Interval(0, oo))

    def __new__(cls, sym, lamda):
        sym = _symbol_converter(sym)
        lamda = _sympify(lamda)
        return Basic.__new__(cls, sym, lamda)

    @property
    def state_space(self):
        return S.Naturals0

    @property
    def symbol(self):
        return self.args[0]

    @property
    def lamda(self):
        return self.args[1]


    def distribution(self, rv):
        return PoissonDistribution(self.lamda*rv.key)

    def density(self, x):
        return (self.lamda*x.key)**x / factorial(x) * exp(-(self.lamda*x.key))


    def expectation(self, expr, condition=None, evaluate=True, **kwargs):
        return _expectation_stoch('Poisson', expr, condition=condition, evaluate=True, **kwargs)

    def probability(self, condition, given_condition=None, evaluate=True, **kwargs):
        if given_condition is not None: # use memory less property
            cond_rv = random_symbols(given_condition)
            if cond_rv:
                max_key_cond = max([rv.key for rv in cond_rv])
            expr_rv = random_symbols(condition)
            if expr_rv:
                max_key_expr = max([rv.key for rv in expr_rv])
            if max_key_expr==max_key_cond: #can be  handled by simple RV
                return _probability_stoch('Poisson', condition, given_condition=given_condition, evaluate=True, **kwargs)
            else:
                from sympy import Abs, Le, Eq, Ge
                process = expr_rv[0].pspace.process
                swap_dict_expr={}
                for rv in expr_rv:
                    swap_dict_expr[rv]=process(rv.key-max_key_cond)
                lhs = condition.args[0].subs(swap_dict_expr)
                rhs = condition.args[1]-given_condition.args[1]
                if (isinstance(condition,(Le, Eq, Ge)) or isinstance(given_condition,(Le, Eq, Ge))) and rhs>0:
                    rhs-=S.One
                condition = condition.__class__(lhs, rhs)
        return _probability_stoch('Poisson', condition, given_condition=None, evaluate=True, **kwargs)

```
Using this to find the answers of 11.1 and 11.2 of the above link:
```python
>>> from sympy import Eq, S
>>> from sympy.stats import P
>>> from sympy.stats.stochastic_process_types import PoissonProcess
>>> Y = PoissonProcess('Y', 10)
>>> P(Eq(Y(S(1)/3), 2)).evalf()
0.198188851929180            # 11.1 'a'
>>> (P(Eq(Y(S(1)/3), 3))*P(Eq(Y(S(2)/3), 7))).evalf()
0.0325439914084338        # 11.1 'b'
>>> X = PoissonProcess('X', 2)
>>> P(Eq(X(0.5),0))
0.367879441171442        # 11.2 'a'
>>> P(Eq(X(3),0), Eq(X(1),0))
exp(-4)                             # 11.2 'b'
>>> P(Eq(X(4),4),Eq(X(2),3))
exp(-4)                           # 11.2 'c'
>>> P(Eq(X(4),4),Eq(X(2),3)) == P(Eq(X(2),0))
True

```

**Comment by Upabjojr** [comment]
```python
>>> N = PoissonProcess('N', 2)
>>> P(Eq(N(4), 4), Eq(N(2), 3))
```

I would recommend squared brackets to access the time-step, i.e. `N[2]`.

**Comment by oscarbenjamin** [comment]
> I would recommend squared brackets to access the time-step, i.e. `N[2]`.

I think of square brackets as representing a subscript so it should always be an integer. The argument to a Poisson process is a non-negative real number the square brackets might look strange with something like `N[1/2]`.

**Comment by czgdp1807** [comment]
n.b. https://github.com/sympy/sympy/blob/bea29026d27cc50c2e6a5501b6a70a9629ed3e18/sympy/stats/stochastic_process_types.py#L122-L132

**Comment by czgdp1807** [comment]
> ```python
> (P(Eq(Y(S(1)/3), 3))*P(Eq(Y(S(2)/3), 7)))
> ```

`P(Eq(Y(S(1)/3), 3) & Eq(Y(S(2)/3), 7))` provides a more natural transformation of the problem. The code can assume that the two events are independent. 
What about `11.2 d` and `11.2 e`? There are some more good problems at https://www.probabilitycourse.com/chapter11/11_1_5_solved_probs.php

Some nice features to have in `PoissonProcess`,

i. https://www.probabilitycourse.com/chapter11/11_1_3_merging_and_splitting_poisson_processes.php
ii. https://www.probabilitycourse.com/chapter11/11_1_4_nonhomogeneous_poisson_processes.php

**Comment by Smit-create** [comment]
> What about `11.2 d` and `11.2 e`?

Continuing the session of [https://github.com/sympy/sympy/issues/19274#issuecomment-626301000](https://github.com/sympy/sympy/issues/19274#issuecomment-626301000), both the problems and can be solved using the current available functions of sympy but require few steps as follows,
For solving 11.e and 11.d,
```python
>>> t = symbols('t', positive=True)
>>> X = PoissonProcess('X', 2)
>>> Z = P(X(t)<1)  # shows the distribution of interarrival times with t as RV
>>> Z
exp(-2*t)
>>> cdf_of_t = 1 - Z
>>> pdf_of_t = cdf_of_t.diff(t)
>>> pdf_of_t
2*exp(-2*t)     # we got the exact pdf as followed by exponential dist.
>>> C = ContinuousRV(t, density=pdf_of_t, set=Interval(0,oo)) # custom RV as per our need
>>> E(C)
1/2
>>> variance(C)
1/4
```


> i. https://www.probabilitycourse.com/chapter11/11_1_3_merging_and_splitting_poisson_processes.php
> ii. https://www.probabilitycourse.com/chapter11/11_1_4_nonhomogeneous_poisson_processes.php

I will see this, and let you know how to handle them

**Comment by Smit-create** [comment]
For the other functions, I think that they can be implemented once we have a Poisson Process framework. So we first need to implement the basic framework and then make some minor changes to extend it if it needs

**Comment by czgdp1807** [comment]
Implementing is not a concern. Can you just solve the problem using fake APIs for now?

**Comment by Smit-create** [comment]
For, merging and splitting of Poisson process, we can add two methods for this, for example,
```python
>>> X = PoissonProcess('X', 10)
>>> Y = PoissonProcess('Y', 3)
>>> Y.merge(X)
>>> Y.lamda
13
>>> N1, N2, N3 = X.split([2, 3, 5])
>>> N2.lamda
3
>>> N1, N2 = X.split([3, 4])   # raise error as they don't sum to 10
... Error
>>> t = symbols('t', positive=True)
>>> N1(t).pspace.process.density(N1(t))   # 11.3 'a'
(2*t)**N1(t)*exp(-2*t)/factorial(N1(t))
>>> X.joint_distribution(N1(t), N2(t))      # 11.3 'b'
JointDistributionHandmade(Lambda((N2(t), N1(t)), (2*t)**N1(t)*(3*t)**N2(t)*exp(-5*t)/(factorial(N1(t))*factorial(N2(t)))))
```

**Comment by Smit-create** [comment]
Questions from [https://www.probabilitycourse.com/chapter11/11_1_5_solved_probs.php](https://www.probabilitycourse.com/chapter11/11_1_5_solved_probs.php)
```python
>>> # Question 1
>>> P(Eq(X(2), 0)).evalf()
0.367879441171442
>>> P(Eq(X(1), 2) & Eq(X(2), 2) & Eq(X(3), 3) & Eq(X(4), 4))
0.00845845520228829
>>> # Question 2
>>> lamda = symbols('lamda', positive=true)
>>> X = Poisson('X',lamda)
>>> Y = Poisson('Y',lamda)
>>> expr=P(Eq(X + t, 2) & Eq(t + Z, 3))  # needs a minor fix in Independent PSpace to do this
>>> Sum(expr, (t,0,3)).doit()
2*lamda**5*exp(-3*lamda)/3 + 2*lamda**3*exp(-3*lamda) + 2*lamda*exp(-3*lamda)
>>> # Question 3
>>> covariance(X(t2)-X(t1), X(t2)).simplify()
lamda*t2
>>> covariance(X(t1)-X(t2), X(t1)).simplify()
lamda*t1
>>> # Question 4 needs some knowledge of assumptions module. Trying to figure that out
>>> # Question 5 will be simple Poisson Process after merging
>>> # Question 6
>>> B = Binomial('B', 4, S(1)/3)
>>> P(B>=2)
11/27
```

**Comment by czgdp1807** [comment]
> ```python
> >>> Y.merge(X)
> ```

What about, `Z = X + Y`? The definition given [here](https://www.probabilitycourse.com/chapter11/11_1_3_merging_and_splitting_poisson_processes.php)?

> ```python
> >>> N1, N2, N3 = X.split([2, 3, 5])
> ```

Should we limit splitting to only 2 processes? There isn't any information [here](https://www.probabilitycourse.com/chapter11/11_1_3_merging_and_splitting_poisson_processes.php) for splitting a Poisson process into arbitrary number of processes.

I see that, queries involving a given time interval having some number of events are quite common. So, there should be a nice and easy interface for such queries. Say, `P(Eq(X(t2) - X(t1), n))` or `P(Eq(X, n), Interval(t1, t2))`. I would prefer the second one as it requires least pre-processing. Any thoughts @Upabjojr

**Comment by czgdp1807** [comment]
> ```python
> >>> B = Binomial('B', 4, S(1)/3)
> >>> P(B>=2)
> 11/27
> ```

This is just last few steps of the problem. `P(t1 < t2, Eq(N1(t1), 2) & Eq(N2(t2), 3))`. Though this is quite a complex problem and may be we cannot design a generic algorithm for such queries as the processes are in the given condition and not in main expression whose probability is to be found out. So, are you able to observe a pattern in the queries? How can we generalise probability queries for PoissonProcess?

**Comment by Smit-create** [comment]
> What about, `Z = X + Y`? The definition given [here](https://www.probabilitycourse.com/chapter11/11_1_3_merging_and_splitting_poisson_processes.php)?

I would prefer going by `.merge()`, as the reason I see is we don't support adding any stochastic process, also it may be necessary only for Poisson Process. Therefore, we can provide a method and document it well and highlight its purpose. But, I can go either way depending on everyone's opinion, as for the latter, we just need to add `__add__` to the class.

> Should we limit splitting to only 2 processes?
Okay, we can, but for more, it can be possible as the child process will be independent.

> `P(Eq(X, n), Interval(t1, t2))`
This sounds good and seems the best option, as I see that almost all the problems will be solved using this.

**Comment by czgdp1807** [comment]
> I would prefer going by `.merge()`, as the reason I see is we don't support adding any stochastic process, also it may be necessary only for Poisson Process.

I couldn't get why will it matter to support `__add__` only in Poisson process. Though on the API, what do you say, `+` or `.merge` @Upabjojr ? `.merge` will modify one of the stochastic processes, so IMO, that doesn't seem good, merging should create a new process keeping the original processes intact.

**Comment by oscarbenjamin** [comment]
Given a process `N1(t)` and another `N2(t)` is the merge just giving the sum `N1(t)+N2(t)`? Is it not already possible to add these as random variables?

**Comment by czgdp1807** [comment]
But then we may have to expose the internals of Poisson process. I think abstracting by allowing adding PoissonProcess objects will seem intuitive to end user. That's just about the interface.

**Comment by Smit-create** [comment]
> Is it not already possible to add these as random variables?

It is possible to add `N1(t) + N2(t)` as they are Random variables but we don't allow `N1 + N2` presently as they are processes.

>  I think abstracting by allowing adding PoissonProcess objects will seem intuitive to end user.

Okay, then we should go with `X + Y`, but only for poisson process?

**Comment by czgdp1807** [comment]
> Okay, then we should go with `X + Y`, but only for poisson process?

Yes for now. Can you just summarise the discussion in the description(https://github.com/sympy/sympy/issues/19274#issue-614510687) like we APIs we arrived at for different purposes/queries? like, splitting, merging, general format of probability queries that PoissonProcess will be able to handle. Mostly, they will contain expressions with Eq, Gt, Lt operators, and And, Or, Not logical operators, and in given part there may be an interval of timings or just some past value of X(t).

**Comment by Smit-create** [comment]
To summarise the above discussion, some examples of the API decided are:
```python
>>> from sympy.stats import PoissonProcess, E, P,
>>> from sympy import symbols, Eq, Interval
>>> N = PoissonProcess('N', 2)
>>> n, t1, t2 = symbols('n t1 t2', positive=True)
>>> # Probability
>>> P(N(t) < n)    # distribution followed by n-th arrival time
...
>>> P(Eq(N, 2), Interval(t1, t2))
...
>>> P(N > 3, Interval(t1, t2))
...
>>> # Expectation
>>> E(N(t1)**2 + N(t2))
...
>>> E(N, Interval(t1, t2))
...
>>> # Merging
>>> M = PoissonProcess('M', 5)
>>> X = M + N
>>> X.lamda
7
>>> # Splitting
>>> Y, Z = M.split(1, 4)
>>> Y.lamda
1
>>> Z.lamda
4
```

**Comment by czgdp1807** [comment]
Looks good. You can raise a PR for implementing the above APIs. If anyone wants to suggest any improvement they can do here.

**Comment by Smit-create** [comment]
> ```python
> >>> P(Eq(N, 2), Interval(t1, t2))
> ...
> >>> P(N > 3, Interval(t1, t2))
> ...
> ```

I think this can cause a break across stats as all the args are sent to their respective methods using `pspace` and `pspace`  supports only rvs. Though we can handle, this can change the present uniformity

**Comment by czgdp1807** [comment]
We can decide that thing once a PR is made.

**Comment by Smit-create** [comment]
Some primary errors while making this API,
```python
>>> X = PoissonProcess('X', 2)
>>> Eq(X, 2)   # this works
Eq(X, 2)
>>> Ge(X,2)   # this doesn't
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/smit/Smitlunagariya/sympy/sympy/core/relational.py", line 793, in __new__
    r = cls._eval_relation(lhs, rhs)
  File "/home/smit/Smitlunagariya/sympy/sympy/core/relational.py", line 1071, in _eval_relation
    return _sympify(lhs.__ge__(rhs))
  File "/home/smit/Smitlunagariya/sympy/sympy/core/sympify.py", line 439, in _sympify
    return sympify(a, strict=True)
  File "/home/smit/Smitlunagariya/sympy/sympy/core/sympify.py", line 360, in sympify
    raise SympifyError(a)

sympy.core.sympify.SympifyError: SympifyError: NotImplemented
>>> GreaterThan(X(1),2)
X(1) >= 2
```

**Comment by Smit-create** [comment]
Can this be designed as
`>>> P(X(t)>3, Interval(t1, t2))  #  t belongs to interval t1 to t2`

**Comment by Smit-create** [comment]
Until we decide the API of Poisson, Gamma, Wiener Process,? Should I implement Random Walks Process as they are much similar to BernoulliProcess:
```python
>>> R = RandomWalk('R', p=0.3, reward=3, loss=-2) 
>>> E(R[3])
...
>>> P(R[3] > 2)   
...
>>> R.path(start_position=4, steps=10) # random generated path with given dist. of reward and loss
...
>>> expr = R[1] + R[3] + R[5]  
>>> P(Eq(expr, 3))
...
```

**Comment by czgdp1807** [comment]
Let's move step by step. I'd suggest to at least make a PR on Poisson process. Failing tests are okay. We will discuss the solutions there.

**Comment by czgdp1807** [comment]
Can you create a new issue for discussion on Random walks?

**Comment by Upabjojr** [comment]
> Can this be designed as
> `>>> P(X(t)>3, Interval(t1, t2)) # t belongs to interval t1 to t2`

`Interval(t1, t2)` is not a conditional expression. 

SymPy already has the `Contains` operator:

```python
In [2]: Contains(x, Interval(0, 1))
Out[2]: x ∈ [0, 1]
```

**Comment by czgdp1807** [comment]
> I would suggest `P(X(t) > 3, Contains(X(t), Interval(t1, t2)))`

This seems really good. @Smit-create Can you make the change in your PR?

**Comment by Upabjojr** [comment]
Passing and interval without conditional should not behave like a conditional. I would suggest to raise an exception in that case.

**Comment by Smit-create** [comment]
Yes, on #19387 , I get:
```python
>>> X = PoissonProcess("X", lamda=3)
>>> P(X(t1) < 4, Interval(1, 2))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/smit/Smitlunagariya/sympy/sympy/stats/rv.py", line 806, in probability
    return pspace(condition).probability(condition, given_condition, evaluate, **kwargs)
  File "/home/smit/Smitlunagariya/sympy/sympy/stats/stochastic_process.py", line 55, in probability
    return self.process.probability(condition, given_condition, evaluate, **kwargs)
  File "/home/smit/Smitlunagariya/sympy/sympy/stats/stochastic_process_types.py", line 1308, in probability
    intervals, rv_swap = get_timerv_swaps(condition, given_condition)
  File "/home/smit/Smitlunagariya/sympy/sympy/stats/stochastic_process_types.py", line 1135, in get_timerv_sw
aps
    % (condition))
ValueError: Interval(1, 2) is not a relational or combination of relationals
```

**Comment by Smit-create** [comment]
@czgdp1807 Gamma and Wiener Process follows similar properties as Poisson Process, If the Poisson Process implementation looks good, should I make a pr for the other two processes?

**Comment by czgdp1807** [comment]
It seems like that, Gamma, Wiener and Poisson process can have a common interface as increments(X(t2) - X(t1)) of all of these, follow some special distributions. Can you check if that's the case?

**Comment by Smit-create** [comment]
> Can you check if that's the case?

Yes, all of these have similar properties and follow some special distribution. See: [https://en.wikipedia.org/wiki/Wiener_process#Characterisations_of_the_Wiener_process](https://en.wikipedia.org/wiki/Wiener_process#Characterisations_of_the_Wiener_process)
So, once the Poisson process framework is finalized, the same can be used for the other two.

**Comment by czgdp1807** [comment]
So, can we have a parent class common to these three process implementing some methods common to these three. The distribution followed by `X(t2) - X(t1)` can be stored as an attribute or a property in each of the three process.

**Comment by czgdp1807** [comment]
https://en.wikipedia.org/wiki/Counting_process can be relevant. It seems like, Poisson, Weiner and Gamma process are counting processes. So, we can have a class, `CountingProcess` with methods common to these three process.

**Comment by Smit-create** [comment]
Yes. Also, then if Poisson Process API looks good then I will create a framework of the Counting Process(with all common methods) and make Poisson Process as its child. and then add Gamma and Weiner upon that?

**Comment by Upabjojr** [comment]
> The distribution followed by `X(t2) - X(t1)` can be stored as an attribute or a property in each of the three process.

What about going for the implementation of the joint distribution?

**Comment by czgdp1807** [comment]
> Also, then if Poisson Process API looks good then I will create a framework of the Counting Process(with all common methods) and make Poisson Process as its child. and then add Gamma and Weiner upon that?

Yes, that would be better.

> What about going for the implementation of the joint distribution?

I cannot get your point. How can we use joint distribution for, `X(t2) - X(t1)`?

**Comment by Upabjojr** [comment]
> I cannot get your point. How can we use joint distribution for, `X(t2) - X(t1)`?

Maybe some unevaluated expression? But it's not important, just get rid of `getattr` please.
