### ISSUE TITLE
as_dummy() needs to give option to retain the original assumptions

### ISSUE THREAD

**Issue by mcpl-sympy** [sympy/sympy#19294]
`Symbol.as_dummy(self)` does not retain its assumptions.

```
>>> from sympy import Symbol
>>> x = Symbol('x', positive=True)
>>> x.is_positive
True
>>> dummy_x = x.as_dummy()
>>> dummy_x.is_positive # return None
```

Although this behavior is intended according to the docstring, still it would be good to give option to retain the assumptions.

This issue will be easy to fix.

**Comment by najkr** [comment]
I'd like to work on this, if help is wanted.

**Comment by oscarbenjamin** [comment]
Why do you want to retain the assumptions? If the symbol is a bound dummy symbol any assumptions on it should not affect the meaning of the expression.

**Comment by mcpl-sympy** [comment]
@oscarbenjamin   
In `diffgeom` module, there `as_dummy` is used to replace certain free symbols to `Dummy`. Inspired by this, I was trying to tranfrom an expression to `Lambda`. (For example, `x+y` to `Lambda((x,y), x+y)`).  

I found out that in this case, assumptions on `Dummy`s can matter.

**Comment by oscarbenjamin** [comment]
Why do the assumptions matter?

There are problems with Lambda and `as_dummy` (#17498)

**Comment by mcpl-sympy** [comment]
Oh, never mind.  

I thought that the expression inside `Lambda` can be subject to simplification, such as `Lambda(x, sqrt(x**2+2*x+1))` to `Lambda(x, x+1)` with positive `x`.  
However, checking again I found that it actually isn't. Then it will no longer be a problem.
