### ISSUE TITLE
LaTeX Parser  : expression has pi as a free symbol !?

### ISSUE THREAD

**Issue by oliverstefanov** [sympy/sympy#19298]
When I use the latex parser, special symbols like pi are recognized as Symbols along other usual symbols like "x"

For example :

`expr = 2*pi*x

print(expr.free_symbols)  # yields {x} without pi, OK

tex = latex(expr)

expr2 = parse_latex(tex)

print(expr2)  # returns 2*(pi*x) again, as expected

print(expr2.free_symbols)  # yields {pi,x} !?`

This is a problem as I need to use the free_symbols set to perform subsequent operations like taking the derivative. I tried removing pi by converting the free_symbols to a list but I haven't succeeded as doing this check triggered errors or unexpected behavior, probably because pi then also gets overwritten in some way, not sure though.

How can I go about resolving this ? Do I need to modify stuff in the LaTeX.g4 grammar file?

Thanks

**Comment by sylee957** [comment]
The problem is that LaTeX does not define `\pi` as any special constant, but as usual greek alphabets like alpha or beta. 
You may better substitute it to sympy constant.
`parse_latex('2 \pi x').subs('pi', S.Pi)`
And I'd note that if you use `pi` instead of `\pi`, you get an english alphabet

**Comment by oliverstefanov** [comment]
Great, this solution works well, thanks! Seems to work best with 'pi' in the subs in my case
