### ISSUE TITLE
Classes in diffgeom module are better be Atom, not only Basic

### ISSUE THREAD

**Issue by mcpl-sympy** [sympy/sympy#19300]
Let me exemplify with `Manifold`. `Manifold` has two arguments: its name in `Symbol`, and its dimension. Although these arguments do make `Manifold` object unique, they do not comprise mathematical tree structure. This means they should not be substitutable nor counted as free symbol.

Currently, `Manifold`, `Patch` and `CoordSystem` are `Basic` object, not `Atom`. This makes such strange result:

```python
>>> from sympy.diffgeom import Manifold
>>> from sympy import symbols
>>> m, n = symbols('m n')
>>> manifold = Manifold('m', 2)
>>> manifold.subs(m, n) # Its name is substituted
Manifold(n, 2)
```

When it comes to `BaseScalarField`, such behavior can be actually treacherous:
```python
>>> from sympy.diffgeom.rn import R2_r # This 2D Cartesian coordinate
>>> from sympy import Symbol
>>> o = Symbol('origin')
>>> expr = R2_r.x + o # This is a scalar field, with no dependency on Symbol('origin')
>>> expr.subs(o,3) == R2_r.x + 3
False
```

This will be avoidable by changing their superclass from `Basic` to `Atom`. If this sounds OK, I will make a PR myself.

**Comment by oscarbenjamin** [comment]
I don't understand why anything needs to be changed here

**Comment by mcpl-sympy** [comment]
@oscarbenjamin 
I wrote wrong example in my previous version. Modified it.

Seeing the second example about `BaseScalarField`, I believe you will clearly see what's the problem here.

**Comment by oscarbenjamin** [comment]
I don't think I understand diffgeom well enough to see what should happen in this case.

**Comment by mcpl-sympy** [comment]
@oscarbenjamin 
`expr = R2_r.x+3` is a scalar field defined in 2D Cartesian coordinate system, which is same as "f(x+y) = x+ 3". Mathematically, this function has nothing to do with a symbol named 'origin'. However, `R2_r.x` contains it in its `args` for printing, which makes itself mathematically dependent on `Symbol('origin')`.

**Comment by sylee957** [comment]
`R2_r.x + o` is just a formal addition of two symbols named `R2_r.x` and `o`. This also applies for symbols in Vector module as well. I don't think that it is inside the scope of `subs` to find some hidden relation between them.

**Comment by mcpl-sympy** [comment]
@sylee957  
`R2_r.x` is not `Symbol`. It is `BaseScalarField`, which is a subclass of `AtomicExpr` and it is a callable object. According to `diffgeom` module, `R2_r.x + o` serves as scalar field by using `rcall` method.

Now, the problem is:  
Suppose you made a coordinate system `R2_c` which has internal name `'C'`. 
```python
>>> from sympy.diffgeom import CoordSystem, Patch, Manifold
>>> M = Manifold('R2', 2)
>>> P = Patch('Origin', M)
>>> R2_c = CoordSystem('C', P, ['x', 'y'])
```
With its two base scalars, `R2_c.x` and `R2_c.y`, you wish to build a scalar field which contains  arbitrary constants `Symbol('C')` and `Symbol('D').  
To do this, you need to do 
```python
>>> from sympy import symbols
>>> R2_c.x, R2_c.y = R2_c.coord_functions()
>>> C, D = symbols('C D')
>>> s_field = R2_c.x + R2_c.y + C + D
```
Later, you decide that this `Symbol('D')` should be determined to 1. So you run,
```python
>>> s_field_2 = s_field.subs(D, 1)
>>> s_field_2 == R2_c.x + R2_c.y + C + 1
True
```
So far, so good. But this gives completely different result when you determine `C` to some other value.
```python
>>> s_field_3 = s_field.subs(C, 3)
>>> s_field_3 == R2_c.x + R2_c.y + 3 + D
False
```

This forces the user to limit the choice in selecting the names, which is unnecessary.


Also, here is another wierd example caused by sympifying:
```
>>> Patch('Origin', M)
Patch(Origin, Manifold(R2, 2))
>>> Patch('O', M)
Patch(<class 'sympy.series.order.Order'>, Manifold(R2, 2))
```

**Comment by sylee957** [comment]
I agree that it should not use plain sympify for `Patch('O', M)`, but there should be further discussion about how to store string arguments in SymPy other than using `Symbol`, before introducing a lot of atomic classes.

**Comment by mcpl-sympy** [comment]
@sylee957   
Why should these not be atomic class? According to the documentation, `Atom` are the objects with no subexpressions. These classes exactly fall down to that definition.

**Comment by jksuom** [comment]
It seems to me that `diffgeom` classes could could, in fact, be subclasses of `Atom`. Currently, `Manifold` is a `Basic` object with two arguments, `name` and `dim`. These are sympified when the object is created so that `name` will be a `Symbol` with some assumptions. That does not make much sense as only the name string will ever be needed. It is probably not necessary to make `dim` a SymPy `Integer` either. So I think that `Manifold` could be an `Atom` with no `args`, only two attributes that could be Python objects.

**Comment by mcpl-sympy** [comment]
I am currently working on this.
