### ISSUE TITLE
octave_code produces exponentation code that is incompatible with MATLAB

### ISSUE THREAD

**Issue by allen-adastra** [sympy/sympy#19302]
[Doc](https://docs.sympy.org/latest/modules/printing.html?highlight=octave#sympy.printing.octave.octave_code) says `octave_code` should be compatible with MATLAB, but `octave_code` expresses exponentiation in the form `a**b`, which is valid in Octave but not in MATLAB. It would make more sense for it to be `a^b`, which is valid in both languages.

**Comment by moorepants** [comment]
The documentation you link to shows it creating `^` not `**`. Can you provide some code that reproduces the issue you are facing?

**Comment by allen-adastra** [comment]
> The documentation you link to shows it creating `^` not `**`. Can you provide some code that reproduces the issue you are facing?

Ah, taking a second look, it looks like it was a mistake on my end.
