### ISSUE TITLE
Lambdify produces error with MatrixSlice when indexing the 0th column.

### ISSUE THREAD

**Issue by FedericoV** [sympy/sympy#19310]
This is on Sympy 1.5.1

This works:
``
X = MatrixSymbol("X", 10, 10)
lambdify(X, X[1, 1:5])
``

This doesn't, if we change the 0 to a 1.
``
X = MatrixSymbol("X", 10, 10)
lambdify(X, X[0, 1:5])
``
and gives this error:

``
Traceback (most recent call last):

  File "C:\Users\ShitPoster\Anaconda3\envs\REMI\lib\site-packages\IPython\core\interactiveshell.py", line 3331, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  File "<ipython-input-12-61ec0633bbc7>", line 2, in <module>
    lambdify(X, X[0, 1:5])

  File "C:\Users\ShitPoster\Anaconda3\envs\REMI\lib\site-packages\sympy\utilities\lambdify.py", line 802, in lambdify
    c = compile(funcstr, filename, 'exec')

  File "<lambdifygenerated-3>", line 2
    return (X[, 1:5])
              ^
SyntaxError: invalid syntax
``

**Comment by sylee957** [comment]
This was already resolved in #19201

**Comment by FedericoV** [comment]
Excellent, thanks.  I should just install the latest version of master and that should fix everything?

**Comment by sylee957** [comment]
Yes, you have to use the sympy git version to track down the newest changes.
I don't think that we fix the issues for the older versions. But fortunately, new release will be soon.

**Comment by oscarbenjamin** [comment]
You can install the prerelease 1.6rc1 with
```
$ pip install -U --pre sympy
```

**Comment by FedericoV** [comment]
Thank you so much for the help.  Closing this issue.
