### ISSUE TITLE
Adding new test cases to test_systems.py

### ISSUE THREAD

**Issue by mijo2** [sympy/sympy#19312]
PR #11510 modified some of the old solvers and added some new test cases. The old solvers will be removed soon, but we need the test cases.

The new test cases need to be added in ```test_sysode_linear_neq_order1``` in ```test_systems.py```. But, only those test cases which are of the form: Linear, n equations, Constant coefficient, Homogeneous(have a look at [this](https://docs.sympy.org/dev/modules/solvers/ode.html#linear-n-equations-order-1-type-1), but note that defective matrices can be handled now) and among them, those which are not already in ```test_systems.py```. Just the new test cases have to be added without modifying the old ones.

**Comment by najkr** [comment]
I'd like to do this and would open a pull request soon.

**Comment by vaish3496** [comment]
I'd like to take this issue.
I have 3-4 test cases ready with me. This is the first contribution I am trying to make so please guide me if I go somewhere wrong. :)

**Comment by vaish3496** [comment]
@mijo2 I have a quick question. In this example, when I check `dsolve(eq17) == sol17` in Juptyer Notebook it returns `True` and `assert dsolve(eq17) == sol17` returns no error.
But when I run the tests it throws the following error `Traceback (most recent call last):
  File "/home/vaish3496/sympy/sympy/solvers/ode/tests/test_systems.py", line 369, in test_sysode_linear_neq_order1
    assert dsolve(eq18) == sol18
AssertionError
`
`eq17 = [Eq(x(t).diff(t), 10*x(t) + 2*y(t)), Eq(y(t).diff(t), 3*x(t) - 9*y(t))]
    sol17 = [Eq(x(t), 2*C1*exp(t*(Rational(1/2) + sqrt(385)/2)) + 2*C2*exp(t*(Rational(1/2) - sqrt(385)/2))),
            Eq(y(t), C1*(Rational(-19/2) + sqrt(385)/2)*exp(t*(Rational(1/2) + sqrt(385)/2)) + C2*(-sqrt(385)/2 - Rational(19/2))*exp(t*(Rational(1/2) - sqrt(385)/2)))]
    
assert dsolve(eq17) == sol17
    assert checksysodesol(eq17, sol17) == (True, [0, 0])`

Can you guide me and tell where am I going wrong?

**Comment by mijo2** [comment]
@vaish3496 Actually, we only need the test cases from the PR, the solutions have to be just replaced with whatever solution ```dsolve``` is returning. For the given example:

```
In [5]: eq17 = [Eq(x(t).diff(t), 10*x(t) + 2*y(t)), Eq(y(t).diff(t), 3*x(t) - 9*y(t))] 

In [6]: dsolve(eq17)                                                                                                                                                                                        
Out[6]: 
[Eq(x(t), C1*(19/6 - sqrt(385)/6)*exp(t*(1/2 - sqrt(385)/2)) + C2*(19/6 + sqrt(385)/6)*exp(t*(1/2 + sqrt(385)/2))),
 Eq(y(t), C1*exp(t*(1/2 - sqrt(385)/2)) + C2*exp(t*(1/2 + sqrt(385)/2)))]
```

The solution obtained here has to be used. You might be thinking, then how are we sure that ```dsolve``` gives the right answer. That's where ```checksysodesol``` comes into the picture. It checks if the solution is correct or not.

So, for every test case that you find based on the conditions that I have given in this issue, update the solution with the new one using the output from ```dsolve```. I hope this is clear, if not, then feel free to ask doubts.

**Comment by mijo2** [comment]
> I'd like to take this issue.

Anyone is free to take up the issue and submit a PR. Feel free to contribute :)

**Comment by vaish3496** [comment]
> we only need the test cases from the PR,
@mijo2 I didnt get this part. 
The example which I have used won't do?

**Comment by mijo2** [comment]
@vaish3496 It would do surely, but we want the test cases from that PR specifically. That's the primary target. Anything extra is welcome.

**Comment by vaish3496** [comment]
@mijo2 I copy-pasted the solution of dsolve(eq17) but the tests are still throwing the same error.

**Comment by vaish3496** [comment]
@mijo2 I am getting the following output for `eq17`
`[Eq(x(t), 2*C1*exp(t*(1/2 + sqrt(385)/2)) + 2*C2*exp(t*(1/2 - sqrt(385)/2))),
 Eq(y(t), C1*(-19/2 + sqrt(385)/2)*exp(t*(1/2 + sqrt(385)/2)) + C2*(-sqrt(385)/2 - 19/2)*exp(t*(1/2 - sqrt(385)/2)))]`

whereas you mentioned 
`[Eq(x(t), C1*(19/6 - sqrt(385)/6)*exp(t*(1/2 - sqrt(385)/2)) + C2*(19/6 + sqrt(385)/6)*exp(t*(1/2 + sqrt(385)/2))),
 Eq(y(t), C1*exp(t*(1/2 - sqrt(385)/2)) + C2*exp(t*(1/2 + sqrt(385)/2)))]
`

**Comment by mijo2** [comment]
@vaish3496 So, the catch here is that the solution that you just copy-paste actually contain fractions like ```19/6```. These fractions are evaluated by Python and thus the sympy module expects the fractions in ```Rational(19,6)``` but sees something like ```3.1666666...``` and so on. 

So, where you see fractions like these, just replace them with ```Rational(19,6)```.

**Comment by vaish3496** [comment]
@mijo2 I already tried using `Rational` but no luck

**Comment by mijo2** [comment]
@vaish3496 You made a branch from the master branch am I correct?

**Comment by vaish3496** [comment]
@mijo2 Sorry but I dont know how to do that

**Comment by mijo2** [comment]
@vaish3496 I think you first need to work on git fundamentals, as it is extremely crucial you work on that before contributing to any opensource project. There are lots of materials out there and get your fundamentals strong.

But, here is a rough walkthrough of how to do this:
1. Create a fork in github in your account.
2. Clone the fork with ```git clone https://github.com/vaish3496/sympy.git```
3. Set upstream: ```git add remote upstream https://github.com/sympy/sympy.git```
4. Make a new branch: ```git checkout -b 19312_issue_fix```
5. Update the files as required and make sure the test cases pass.
6. Push the changes using git command: ```git add .``` ```git commit -m "Type your commit message"```, ```git push origin 19312_issue_fix```.
7. Create a Pull Request from the GitHub's website by going to your own fork. This is easy.
8. Fill in the PR details properly and look for other PRs which have done the same to get an idea.

But, I would highly recommend you work properly on git fundamentals before contributing. After understanding the git fundamentals, please check out [Intro to Contributing](https://github.com/sympy/sympy/wiki/Introduction-to-contributing) page and go through it thoroughly along with the associated links.

**Comment by vaish3496** [comment]
@mijo2 I had already done all the things upto point 5.

**Comment by mijo2** [comment]
> I had already done all the things upto point 5.

So you were using a created branch from a cloned repo? Or did you install sympy in your notebook using pip?

**Comment by mijo2** [comment]
Just create a new branch after you have done ```git pull upstream master``` if you have not done it already.

**Comment by vaish3496** [comment]
@mijo2 Now I am getting no errors. I figured out where I was going wrong.
One thing I would like to clarify is I need to add test cases involving 

> Linear, n equations, Constant coefficient, Homogeneous

equations, right?

**Comment by mijo2** [comment]
Yes, that's right. One the test cases of that form.

**Comment by najkr** [comment]
@vaish3496 I'm sorry, I didn't see you were just ahead of me when I opened that pull request. However, it seems you've not included quite the right tests, so I would just leave mine open as well.

**Comment by vaish3496** [comment]
@mijo2 I'm sorry, I misunderstood the test cases. I have closed my PR.

**Comment by oscarbenjamin** [comment]
Are the other test cases not ready to be added because the non-homogeneous solver is not ready yet?
