### ISSUE TITLE
Idea to implement CoordSystem's _fill_gaps_in_transformations

### ISSUE THREAD

**Issue by mcpl-sympy** [sympy/sympy#19318]
Currently, `CoordSystem` in `diffgeom` module has unimplemented method called `_fill_gaps_in_transformations`. This method is supposed to establish the transformation relation between two non-directly connected coordinate systems.

I am planning to implement this method. Using path finding algorithm, the shortest path to connect two systems (the coordinate systems between these) will be found. Then, the base scalars will be transformed successively. Once the relation is found, both coordinate systems will be added to each other's `transforms`.

Should there be anything more needed, or something that I should keep in mind, please leave a comment here.

**Comment by sylee957** [comment]
I think that some classes in the `diffgeom` are using mutable objects like `transforms` or `coord_systems`, but they shouldn't be using them extensively than cacheing.
And I think that this makes the future unclear about whether `transforms` dict should be replaced by other stuff and be deprecated.

**Comment by mcpl-sympy** [comment]
@sylee957 
I totally agree. Especially, I have tried many times to make `transforms` immutable, but none of them were successful. Perhaps I'll make another issue page, and resolve that matter first.
