### ISSUE TITLE
parse latex should not evaluate

### ISSUE THREAD

**Issue by max-yue** [sympy/sympy#19337]
from sympy.parsing.latex import parse_latex

```
print(parse_latex('1+1'))  # 1 + 1
print(parse_latex('0+1'))  # 1
print(parse_latex('1*2'))  # 2
```

The first one is not evaluated, that is great, but the second and third just evaluate the converted latex, which is not I wanted; I hope there could be a parameter for me to specify whether to evaluate the converted latex, let's say `parse_latex('1*2', evaluate=False)`

**Comment by sylee957** [comment]
I think that the fundamental problem is Add and Mul removing identity even if evaluate=False is given

```
Add(0, 1, evaluate=False)
Mul(0, 1, evaluate=False)
```

**Comment by max-yue** [comment]
Will you consider fix this? I think when I specify evaluate is False, there is no need to do so?&nbsp;


岳祥&nbsp;&nbsp;
中国 上海市区 | 学生 - 复旦大学





&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "S.Y. Lee"<notifications@github.com&gt;; 
发送时间: 2020年5月17日(星期天) 下午2:33
收件人: "sympy/sympy"<sympy@noreply.github.com&gt;; 
抄送: "Ung"<yx931112@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [sympy/sympy] parse latex should not evaluate (#19337)





 
I think that the fundamental problem is Add and Mul removing identity even if evaluate=False is given
 Add(0, 1, evaluate=False) Mul(0, 1, evaluate=False)

**Comment by sylee957** [comment]
I think that this should be fixed, but fixed in the way that sympy operations does not remove identities aggressively

```
diff --git a/sympy/core/operations.py b/sympy/core/operations.py
index bcf9c8ad23..c07ed3b3cb 100644
--- a/sympy/core/operations.py
+++ b/sympy/core/operations.py
@@ -29,7 +29,6 @@ class AssocOp(Basic):
     def __new__(cls, *args, **options):
         from sympy import Order
         args = list(map(_sympify, args))
-        args = [a for a in args if a is not cls.identity]

         # XXX: Maybe only Expr should be allowed here...
         from sympy.core.relational import Relational
@@ -44,6 +43,7 @@ def __new__(cls, *args, **options):
             obj = cls._exec_constructor_postprocessors(obj)
             return obj

+        args = [a for a in args if a is not cls.identity]
         if len(args) == 0:
             return cls.identity
         if len(args) == 1:
```
This should work for this case `parse_latex('0+1')` and `parse_latex('0*1')` although it prints weird, but the real problem is that a lot of tests can break after introducing this.

**Comment by max-yue** [comment]
lat = r'(2 + 3) \div 3 - 4 \times 5' 
print(parse_latex(lat))  # (2 + 3) / 3 - 20
which is not what I want, since 4 \times 5 evaluate to 20.
and 
class AssocOp(Basic):
     def __new__(cls, *args, **options):
         from sympy import Order
         args = list(map(_sympify, args))  # also we should not simplify args when evaluate is False.

I do think sympy should support some context management, such as:
with evaluate_context(evaluate=False):
    # anything should not be evaluated or simplified
    ...
