### ISSUE TITLE
[GSoC Discussion] Compound Distributions

### ISSUE THREAD

**Issue by Smit-create** [sympy/sympy#19332]
The current compound distributions in the `stats` don't provide expected results and are not tested as:
```python
>>> N = Normal('N',1,3)
>>> M = Normal('M',N,2)
>>> E(M)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/smit/Smitlunagariya/sympy/sympy/stats/rv.py", line 763, in expectation
    result = pspace(expr).compute_expectation(expr, evaluate=evaluate, **kwargs)
  File "/home/smit/Smitlunagariya/sympy/sympy/stats/joint_rv.py", line 126, in compute_expectation
    cannot be calculated yet.'''))
NotImplementedError:
Expectations of expression with unindexed joint random symbols cannot
be calculated yet
```
Therefore, I plan to add compound distributions from scratch.
The API, for using them will be same of other random variables for example:
```python
>>> M = Normal('M', 1, 3)
>>> N = Normal('N', M, 2)
>>> density(N)(x)
...
>>> E(N)
...
>>> P(N>2)
...
```
The mathematical implementation according to the definition of compound distributions [here](https://en.wikipedia.org/wiki/Compound_probability_distribution#Definition) can become unreliable as of now because we are not always sure, that the `integrate` will evaluate the results correctly.
For example, the  implementation of Normal distribution compounded with another Normal Distribution:
```python
>>> from sympy import integrate, oo
>>> from sympy.stats import Normal, density
>>> from sympy.abc import x,y,z
>>> N = Normal('N', 1, 2)
>>> M = Normal('M', x, 1) # We will compound M with x and x will follow distribution of N
>>> expr1 = density(M)(y)
>>> expr1
sqrt(2)*exp(-(-x + y)**2/2)/(2*sqrt(pi))    # dist. of M parametrized by x
>>> expr2=density(N)(x) 
>>> expr2
sqrt(2)*exp(-(x - 1)**2/8)/(4*sqrt(pi))      # dist. of x
>>> expr3 = integrate(expr1*expr2, (x,-oo,oo)).simplify()   # the dist. of M free from x.
>>> expr3
sqrt(10)*exp(-y**2/10 + y/5 - 1/10)/(10*sqrt(pi))      # the dist. of M with mean 1, correctly reached
>>> integrate(expr3, (y,-oo,oo)).simplify()
-erfc(sqrt(10)/10)/2 - erf(sqrt(10)/10)/2 + 3/2    #  It is correct but should evaluate to one itself.
```
Related issues #17007, #16855, #11135
ping @czgdp1807 @Upabjojr @jmig5776

**Comment by czgdp1807** [comment]
Can you try some combinations(may be first two or three) from https://en.wikipedia.org/wiki/Compound_probability_distribution#Examples ? Just post the session here. We can think of improving them. Work on compound distributions is stalled since 2018 AFAIK. It certainly needs to be improved a lot.

**Comment by Smit-create** [comment]
1.` Compounding a normal distribution with variance distributed according to an inverse gamma distribution (or equivalently, with precision distributed as a gamma distribution) yields a non-standardized Student's t-distribution`
```python
>>> from sympy.stats import *
>>> from sympy import integrate,oo, symbols
>>> x=symbols('x', positive=True)
>>> y=symbols('y')
>>> G = Gamma('G',1 ,2)
>>> N = Normal('N', 0, x)
>>> expr1 = density(N)(y)
>>> expr1
sqrt(2)*exp(-y**2/(2*x**2))/(2*sqrt(pi)*x)
>>> expr2 = density(G)(x)
>>> expr2
exp(-x/2)/2
>>> expr3 = integrate(expr1*expr2, (x,0,oo)).simplify()
>>> expr3          # dist. of N parameterized by x,it should be free from x after integrate
Piecewise((sqrt(2)*meijerg(((1, 1/2, 1), ()), ((), ()), 32/polar_lift(y)**2)/(8*pi), 2*Abs(arg(y)) <= pi/2),
(sqrt(2)*Integral(exp(-(x**3 + y**2)/(2*x**2))/x, (x, 0, oo))/(4*sqrt(pi)), True))
>>> integrate(expr3, (y,-oo,oo)).simplify()  # check if we got the correct pdf 
Traceback (most recent call last):
  File "/home/smit/Smitlunagariya/sympy/sympy/polys/polyutils.py", line 211, in _parallel_dict_from_expr_if_g
ens
    monom[indices[base]] = exp
KeyError: polar_lift(y)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/smit/Smitlunagariya/sympy/sympy/polys/polytools.py", line 6350, in factor
    return _generic_factor(f, gens, args, method='factor')
  File "/home/smit/Smitlunagariya/sympy/sympy/polys/polytools.py", line 6022, in _generic_factor
    return _symbolic_factor(sympify(expr), opt, method)

  File "/home/smit/Smitlunagariya/sympy/sympy/polys/polytools.py", line 5962, in _symbolic_factor
    coeff, factors = _symbolic_factor_list(together(expr, fraction=opt['fraction']), opt, method)
  File "/home/smit/Smitlunagariya/sympy/sympy/polys/polytools.py", line 5921, in _symbolic_factor_list
    poly, _ = _poly_from_expr(base, opt)
  File "/home/smit/Smitlunagariya/sympy/sympy/polys/polytools.py", line 4276, in _poly_from_expr
    rep, opt = _dict_from_expr(expr, opt)
  File "/home/smit/Smitlunagariya/sympy/sympy/polys/polyutils.py", line 368, in _dict_from_expr
    rep, gens = _dict_from_expr_if_gens(expr, opt)
  File "/home/smit/Smitlunagariya/sympy/sympy/polys/polyutils.py", line 307, in _dict_from_expr_if_gens
(poly,), gens = _parallel_dict_from_expr_if_gens((expr,), opt)
  File "/home/smit/Smitlunagariya/sympy/sympy/polys/polyutils.py", line 217, in _parallel_dict_from_expr_if_g
ens
    "the set of generators." % factor)
sympy.polys.polyerrors.PolynomialError: polar_lift(y) contains an element of the set of generators.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>

  File "/home/smit/Smitlunagariya/sympy/sympy/integrals/integrals.py", line 1545, in integrate
    return integral.doit(**doit_flags)
  File "/home/smit/Smitlunagariya/sympy/sympy/integrals/integrals.py", line 534, in doit
    function, xab[0], **eval_kwargs)
  File "/home/smit/Smitlunagariya/sympy/sympy/integrals/integrals.py", line 915, in _eval_integral
    return f.piecewise_integrate(x, **eval_kwargs)
  File "/home/smit/Smitlunagariya/sympy/sympy/functions/elementary/piecewise.py", line 373, in piecewise_inte
grate
    return self.func(*[(integrate(e, x, **kwargs), c) for e, c in self.args])
File "/home/smit/Smitlunagariya/sympy/sympy/functions/elementary/piecewise.py", line 373, in <listcomp>
    return self.func(*[(integrate(e, x, **kwargs), c) for e, c in self.args])
  File "/home/smit/Smitlunagariya/sympy/sympy/integrals/integrals.py", line 1545, in integrate
    return integral.doit(**doit_flags)
  File "/home/smit/Smitlunagariya/sympy/sympy/integrals/integrals.py", line 594, in doit
    function, xab[0], **eval_kwargs)
  File "/home/smit/Smitlunagariya/sympy/sympy/integrals/integrals.py", line 1069, in _eval_integral
    h = meijerint_indefinite(g, x)
  File "/home/smit/Smitlunagariya/sympy/sympy/integrals/meijerint.py", line 1621, in meijerint_indefinite
    res = _meijerint_indefinite_1(f.subs(x, x + a), x)

  File "/home/smit/Smitlunagariya/sympy/sympy/integrals/meijerint.py", line 1646, in _meijerint_indefinite_1
    gs = _rewrite1(f, x)
  File "/home/smit/Smitlunagariya/sympy/sympy/integrals/meijerint.py", line 1569, in _rewrite1
    g = _rewrite_single(g, x, recursive)
  File "/home/smit/Smitlunagariya/sympy/sympy/integrals/meijerint.py", line 1435, in _rewrite_single
    coeff, m = factor(f.argument, x).as_coeff_mul(x)
  File "/home/smit/Smitlunagariya/sympy/sympy/polys/polytools.py", line 6356, in factor
    raise PolynomialError(msg)
sympy.polys.polyerrors.PolynomialError: polar_lift(y) contains an element of the set of generators.
```
2.` Compounding a Gaussian distribution with variance distributed according to an exponential distribution (or with standard deviation according to a Rayleigh distribution) yields a Laplace distribution.`
```python
>>> x=symbols('x',positive=True)
>>> N = Normal('N', 0, x)
>>> expr1 = density(N)(y)
>>> expr1
sqrt(2)*exp(-y**2/(2*x**2))/(2*sqrt(pi)*x)
>>> R = Rayleigh('R',2)
>>> expr2 = density(R)(x)
>>> expr2
x*exp(-x**2/8)/4
>>> expr3 = integrate(expr1*expr2, (x, 0, oo)).simplify()
>>> expr3            # dist of compounded N, should be free from x
Piecewise((exp(-y/2)/4, 2*Abs(arg(y)) <= pi/2), (sqrt(2)*Integral(exp(-(x**4 + 4*y**2)/(8*x**2)), (x, 0, oo))
/(8*sqrt(pi)), True))
>>> integrate(expr3, (y,-oo,oo)).simplify()    # check if we got the correct pdf
Integral(Piecewise((exp(-y/2)/4, 2*Abs(arg(y)) <= pi/2), (sqrt(2)*Integral(exp(-(x**4 + 4*y**2)/(8*x**2)), (x
, 0, oo))/(8*sqrt(pi)), True)), (y, -oo, oo))
```

**Comment by czgdp1807** [comment]
The problem here is that the pdf of compound distributions are not computed correctly, see for example below. So, that should be fixed. Now, a simple way of doing this is to check if the expression under integral is whether a random or not and if it is then marginalise it(see, https://en.wikipedia.org/wiki/Compound_probability_distribution#Definition). This way, we will not be adding any new classes for compound distributions. Current implementation can be modified. Once we have the pdf, `E`, `Variance` can be computed easily.
P.S. Are there any distributions with more than one parameter distributed according to a certain distribution. For example both mean and variance distributed according to some other distributions.

**Comment by czgdp1807** [comment]
The example which I forgot above,
```python
>>> from sympy.stats import *
>>> R = Rayleigh("R", 0.01)
>>> N = Normal("N", 0, R)
>>> density(N)(x)
∞                               
⌠                               
⎮                          2    
⎮                        -x     
⎮                        ────   
⎮                     2     2   
⎮            -5000.0⋅R   2⋅R    
⎮ 5000.0⋅√2⋅ℯ          ⋅ℯ       
⎮ ─────────────────────────── dR
⎮              √π               
⌡                               
0             
```
`dR` doesn't makes any sense. The above wikipedia link suggests to marginalise the pdf which should have happened automatically as soon as a random expression was observed under the integral.

**Comment by Smit-create** [comment]
> he above wikipedia link suggests to marginalise the pdf which should have happened automatically as soon as a random expression was observed under the integral.

I understand that the current Compund Distributions are not upto the mark. In [https://github.com/sympy/sympy/issues/19332#issuecomment-629735790](https://github.com/sympy/sympy/issues/19332#issuecomment-629735790) I am trying to show that while marginalizing, integrate doesn't evaluate to produce correct pdf always. I have shown considering that `x` is a RV(which follows some dist.) and followed the steps to show that integrate doesn't always marginalize(i.e free from x)

**Comment by czgdp1807** [comment]
Well, that's the issue which is related to `integrals` module. We shouldn't worry about why are they not working and stuff. At least, the unevaluated `Integral` should be correct, as the expression under it shouldn't be random.

**Comment by Smit-create** [comment]
```python
>>> x=symbols('x',positive=True)
>>> N = Normal('N', 0, x)    # consider x as RV, it will follow some dist.
>>> expr1 = density(N)(y)
>>> expr1         # density consisting x, ie RV
sqrt(2)*exp(-y**2/(2*x**2))/(2*sqrt(pi)*x)  
>>> R = Rayleigh('R',2)
>>> expr2 = density(R)(x)
>>> expr2      # the distribution x will follow in N
x*exp(-x**2/8)/4
>>> expr3 = integrate(expr1*expr2, (x, 0, oo)).simplify() # to remove x, lets marginalize 'x' to remove it
>>> expr3    # after marginalizing x still remains
Piecewise((exp(-y/2)/4, 2*Abs(arg(y)) <= pi/2), (sqrt(2)*Integral(exp(-(x**4 + 4*y**2)/(8*x**2)), (x, 0, oo))
/(8*sqrt(pi)), True))      
```

> At least, the unevaluated `Integral` should be correct, as the expression under it shouldn't be random.

But the case is unevaluated still consists of random variable here `x` in `expr3`

**Comment by czgdp1807** [comment]
Yes, so that expression is incorrect, a good algorithm should be able to detect that marginalisation is needed and will return the correct unevaluated integral.

**Comment by Smit-create** [comment]
Have I understood correctly? that:
1. Check if the dist. is compound
2. Try to marginalize and check if it consists of a single RV, if single RV then that's the pdf and we have successfully marginalized or else return pdf in the unevaluated Integral form.
3. Successfully marginalized and use that pdf to form a distribution using a custom RV and will get a corresponding Pspace.
4. If not marginalized then give it a `JointPspace`, as pdf is unevaluated integral with two RVs.

**Comment by czgdp1807** [comment]
Well, suppose we have, `X = Normal('X', R, G)` where, `R` and `G` are random variables. So, the PDF can be represented as, `Integral(density(X).subs({R:r, G:g})*density(R)(r)*density(G)(g))`. I do not know if it's correct but the underlying idea is to extend the marginalisation from one parameter to arbitrary number of parameters(can be checked using `is_random`).
Returning custom RV can be an option. We can evaluate the integral in default case, otherwise leave it as it is. Marginalisation is a success or failure shouldn't be our concern. Just make sure that if any parameter is random expression marginalise the PDF and make it non-random. So, `Normal('X', R, G)`->Custom RV.

**Comment by czgdp1807** [comment]
Any news on this?

**Comment by Smit-create** [comment]
I got your point. I'm waiting for phase 2 to begin so, I will open a PR for the same and discuss if something later pops up.

**Comment by Smit-create** [comment]
> Returning custom RV can be an option. We can evaluate the integral in default case, otherwise leave it as it is.

Suppose, X = Normal('X', R, 2) where `R` is a rv, then the pdf of `X = Integral(density(X).subs({R:r})*density(R)(r)`. Now if try to return a custom RV then, it will raise an error in the case pdf is not equal to 1.
```python
>>> from sympy.stats import *
>>> from sympy.abc import x,y,z
>>> N = Normal('N',1,3)
>>> M = Normal('M',x,2)
>>> expr1 = density(M)(y)
>>> expr1
sqrt(2)*exp(-(-x + y)**2/8)/(4*sqrt(pi))
>>> pdf = Integral(expr1*density(N)(x), (x, -oo, oo))
>>> pdf
Integral(exp(-(-x + y)**2/8)*exp(-(x - 1)**2/18)/(12*pi), (x, -oo, oo))
>>> pdf.doit()
-(-3*sqrt(26)*pi*(1 - y)*exp(9*(1 - y)**2/104)*erf(3*sqrt(26)*(1 - y)/52)/52 - 3*sqrt(26)*pi*(1 - y)*exp(9*(1
 - y)**2/104)/52)*exp(-y**2/8 + y/4 - 1/8)/(3*pi**(3/2)*(1 - y)) + (-3*sqrt(26)*pi*(1 - y)*exp(9*(1 - y)**2/1
04)*erf(3*sqrt(26)*(1 - y)/52)/52 + 3*sqrt(26)*pi*(1 - y)*exp(9*(1 - y)**2/104)/52)*exp(-y**2/8 + y/4 - 1/8)/
(3*pi**(3/2)*(1 - y))

>>> X = ContinuousRV(y, pdf.doit()) # takes infinite time
...
KeyboardInterrupt
>>> X = ContinuousRV(y, pdf) # takes infinite time
...
KeyboardInterrupt

```
In this case the custom rv got hanged because of:
https://github.com/sympy/sympy/blob/d2015750b5ed097ce5e0cda0ad85330f4266ed4f/sympy/stats/crv_types.py#L152-L157

**Comment by Smit-create** [comment]
Hi @czgdp1807, Any thoughts on [https://github.com/sympy/sympy/issues/19332#issuecomment-636638652](https://github.com/sympy/sympy/issues/19332#issuecomment-636638652)?

**Comment by Smit-create** [comment]
I am thinking of the following implementation:

1. Create a new file say `compound_dist.py`
2. Implement `CompoundDistribution` and `CompoundPSpace` in it.
3. How will a distribution become an instance of CompoundDistribution ?: Check while initialization of CRV, FRV or DRV, if any of its argument is random, then Make it an instance of `CompoundDistribution`.
4. CompoundDistribution will be similar to other stats distributions classes and will contain:
     (i) `set`-on which distribution is defined
     (ii) `pdf`-marginalized pdf in terms of all the random parameters
5. CompoundPSpace will be similar to other stats pspaces: and will contain methods like `compute_expectation`, `compute_density`, ...

Another way around to avoid all this:

1. Create a function/class say `handle_compound`.
2. During the initialization of CRV, FRV, or DRV, if any of its arguments are random, call `handle_compound`.
3. This will take the dist as an argument, marginalize it with all random parameters, and then check if the parent dist is Continuous return `ContinuousRV(x, marginalized_pdf)`, or if parent dist is Discrete return `DiscreteRV(x, marginalized_pdf)` or if Finite then return `FiniteRV(x, marginalized_pmf)
`, where `ContinuousRV`, `DiscreteRV`, and `FiniteRV` are used to create custom distributions with pdf and set an argument
4. The benefit in this method is to avoid creating extra classes for Compound Distributions and handle them using the existing code itself, as after all they are reduced down to any of CRV, DRV or FRV after marginalization.

What are thoughts on which way should we go by @czgdp1807 @Upabjojr ?

**Comment by czgdp1807** [comment]
Do we need in any case, the random variable arguments of any compound random variable? May be using the first seems better, it doesn't lead to any information loss.

**Comment by Smit-create** [comment]
> Do we need in any case, the random variable arguments of any compound random variable?

The Compound Random Variable will be created only when any of the arguments while creating CRV, FRV or DRV  is random, we can raise an error if no argument is random while specifically creating Compound Random Variable.

> May be using the first approach seems better, it doesn't lead to any information loss.

Okay, I will try to make a PR/draft as soon some basic structure is built...

**Comment by Upabjojr** [comment]
Should the compound-distribution related classes be subclasses of the joint-distribution related classes?

**Comment by Smit-create** [comment]
> Should the compound-distribution related classes be subclasses of the joint-distribution related classes?

Yes, they can be viewed as the subclasses of Joint Distributions.

**Comment by czgdp1807** [comment]
How? Can you explain with an example? How the methods defined in Joint distributions will be reusable in compound distributions?

**Comment by Upabjojr** [comment]
Maybe an abstract superclass of both compound and joint distributions?

**Comment by Smit-create** [comment]
Actually, after starting to implement the plan, I realized the following things:
1. We can initially handle Compound distributions with not more than 1 random argument because consider the following example:
   (i) `P = Poisson('D', 3), N = Normal('N', 1, 3), G = Gamma('G', P, N)`, In this case, P is Discrete and N is Continuous, so it becomes a question of whether to integrate or do summation, as there are no such resources for this on Wikipedia too. So, initial we can support 1 random argument.
2. If the pdf gets marginalized and becomes free from RV, it has reduced to DRV/CRV, so the `compute_density`, `compute_expectation`, etc. need to access the same way as DRV/CRV/FRV, so I need to copy the same code in the CompoundPSpace(From DR, CR, FR pspaces) and also there will be three cases to handle them separately, so instead of accumulating them all at a single pspace, we can let the respective pspace to handle the computation.
3. If the pdf has not actually marginalized(because the integral may be too complex) we can output the unevaluated for that cases. 
I am sharing my draft so that it becomes more clear from that. Thanks!

**Comment by czgdp1807** [comment]
Marginalisation should happen only when required, i.e., when density is called on compound RV. Internal representation should be parameters as random variables. I don't know how joint distribution relate to compound distribution. The earlier one is a combination of RVs(can be compound) and the latter one is the parameters of a RV being an RV. So, a compound RV can be part of joint distribution. I don't think both of these should be mixed, it will lead to unnecessary coupling and difficulty in maintenance. If possible and useful, the algorithm for marginalisation can be reused from joint distribution inside the PDF of compound distribution.

**Comment by Smit-create** [comment]
>  If possible and useful, the algorithm for marginalization can be reused from joint distribution inside the PDF of compound distribution.

Yes, only that is required and so I have implemented it separately from Joint Dist.

**Comment by czgdp1807** [comment]
Can we close the related issues, the links to which are mentioned in the OP?

**Comment by Smit-create** [comment]
#16855, I think the question here is not related to Finite RV but can be Joint Distribution with the finite set. So, I will try to provide the solution and close it.
