### ISSUE TITLE
acot(x) should be range (0,pi)

### ISSUE THREAD

**Issue by nifengcn** [sympy/sympy#19356]
As is shown in https://en.wikipedia.org/wiki/Inverse_trigonometric_functions, Range of the acot(x) is (0, pi), not (-pi/2, pi/2). If the conclusion is agreed on, I can fix it by opening a pull request.

**Comment by jksuom** [comment]
See https://github.com/sympy/sympy/issues/18480

**Comment by nifengcn** [comment]
@jksuom I think (0,pi) will make the acot a continuous function. The definition is better. if range in (-pi/2, pi/2), it will be hard to decide the result of the acot(0). -pi/2 or pi/2?

**Comment by jksuom** [comment]
> (0,pi) will make the acot a continuous function

That is true but it was decided not to change the implementation.

**Comment by gschintgen** [comment]
> I think (0,pi) will make the acot a continuous function. The definition is better.

There are also arguments for the current definition:
* It has the property `acot(z) == atan(1/z)` which is consistent with `cot(z) == 1/tan(z)`.
* The resulting function is odd, which is also nice to have.
* It's compatible with mpmath to which SymPy is strongly coupled when it comes to numeric evaluation. See https://github.com/sympy/sympy/issues/13679#issuecomment-352142835 

Note that I don't feel that strongly about either definition, it's just that in this context the current definition seems quite sensible and coherent.
