### ISSUE TITLE
Expand does not work as expected

### ISSUE THREAD

**Issue by InCogNiTo124** [sympy/sympy#19350]
I tried a simple expansion today and was surprised with the result

![image](https://user-images.githubusercontent.com/12953598/82155932-87333900-9878-11ea-9176-e5b369ea6326.png)

I expected a simple (x^2-6x+9)

edit: the behaviour changed appropriately after I put x to be a real symbol

**Comment by sylee957** [comment]
I think that this works fine both in master and sympy live.
I see the printing is weird
Did you try again after clearing the console?

**Comment by oscarbenjamin** [comment]
The printing is the issue I think.

**Comment by InCogNiTo124** [comment]
> I think that this works fine both in master and sympy live.
> I see the printing is weird
> Did you try again after clearing the console?

A hard refresh with cache invalidation had fixed the issue, so I'm closing this
