### ISSUE TITLE
sign error in as_real_imag method of cotangent

### ISSUE THREAD

**Issue by DaveWitteMorris** [sympy/sympy#19366]
It was reported in sage trac ticket #29400 that the imaginary part of the cotangent of a symbolic expression is sometimes incorrect. I tracked this down to a bug in the `as_real_imag` method of sympy's cotangent class (`functions.elementary.trigonometric.cot`). The imaginary part is the negative of what it should be.

I could not get git push to work, so I am attaching a patch instead. It just deletes a minus sign from the `as_real_imag` method (and also from the corresponding test). 

[cot_as_real_imag.patch.txt](https://github.com/sympy/sympy/files/4648565/cot_as_real_imag.patch.txt)

I do not understand sympy or the sage-sympy interface, but I was able to put together the following sage test that demonstrates the problem.
```
import sympy
function_list = [sympy.sin, sympy.cos, sympy.tan, sympy.sec, sympy.csc, sympy.cot]
a, b = sympy.symbols('a b', real=True)
z = a + b*I
test_pt = {a:1, b:3}

for f in function_list:
    re, im = f(z).as_real_imag(z)
    f_re_im = (re.subs(test_pt) + im.subs(test_pt)*I).n()
    if abs(f(z).subs(test_pt).n() - f_re_im) > 10^(-10):
        print("{}: error = {} ({} vs. {})".format(
            str(f), 
            f(z).subs(test_pt).n() - f_re_im, 
            f(z).subs(test_pt).n(6), 
            f_re_im.n(6)))
```
The output (without the patch) is:
```
cot: error = -1.99585789446276*I (0.00449854 - 0.997929*I vs. 0.00449854 + 0.997929*I)
```
Note that the imaginary part of ```f_re_im``` (which uses the values from ```as_real_imag```) is the negative of what it should be, so deleting the minus sign solves the problem.

**Comment by DaveWitteMorris** [comment]
Two further comments:

1. The above `sage` code works in python if two changes are made: add the line `from sympy import I` near the start, and change `10^(-10)` to `10**(-10)` in line 9.

2. The attached pdf file (cotz.pdf) calculates the real and imaginary parts of `cot z`. It establishes that the patch gives the correct definition of `as_real_imag`.
[cotz.pdf](https://github.com/sympy/sympy/files/4652357/cotz.pdf)

**Comment by gschintgen** [comment]
Thanks for your detailed report! I'll file a pull request with your patch commit shortly. (I also checked the hyperbolic trig functions; they're fine.)

**Comment by DaveWitteMorris** [comment]
Thanks for making the pull request!
