### ISSUE TITLE
Clean up flake8 warnings from doctests

### ISSUE THREAD

**Issue by oscarbenjamin** [sympy/sympy#19374]
Currently flake8 runs on the main code but not on doctests. It has a `--doctests` argument to check the doctests as well.

For example:
```console
$ flake8 --doctests sympy/matrices/determinant.py 
sympy/matrices/determinant.py:545:9: F401 'sympy.MatrixSymbol' imported but unused
sympy/matrices/determinant.py:545:9: F401 'sympy.eye' imported but unused
sympy/matrices/determinant.py:545:9: F401 'sympy.det' imported but unused
```
That can be fixed with
```diff
diff --git a/sympy/matrices/determinant.py b/sympy/matrices/determinant.py
index 647541afef..f3bb9a4067 100644
--- a/sympy/matrices/determinant.py
+++ b/sympy/matrices/determinant.py
@@ -542,7 +542,7 @@ def _det(M, method="bareiss", iszerofunc=None):
     Examples
     ========
 
-    >>> from sympy import Matrix, MatrixSymbol, eye, det
+    >>> from sympy import Matrix
     >>> M = Matrix([[1, 2], [3, 4]])
     >>> M.det()
     -2
```

Running flake8 on the whole of sympy with
```
$ flake8 --doctests sympy
```
leads to 698 warnings almost all of which are F401 (unnecessary import) and so easily fixable.

These should all be fixed and then we should add the `--doctest` argument on Travis.

I'm marking this as easy to fix.

**Comment by InCogNiTo124** [comment]
I'd like to take up on the task of cleaning the imports if I may

**Comment by oscarbenjamin** [comment]
Yes, go ahead.

**Comment by InCogNiTo124** [comment]
I was working on this cleanup and I found a curious situation:

sympy supports multiple dispatch as per argument type, as defined in the docs of `sympy/multipledispatch/core.py`: (lines 22-38)
```
Examples
    --------

    >>> from sympy.multipledispatch import dispatch
    >>> @dispatch(int)
    ... def f(x):
    ...     return x + 1

    >>> @dispatch(float)
    ... def f(x):
    ...     return x - 1

    >>> f(3)
    4
    >>> f(3.0)
    2.0

```

`flake8`, on the other hand, reports an error `F811 redefinition of unused 'f' from line 27`
which makes sense from its point of view but it seems that's a wanted behaviour

This could be easily solved by invoking `flake8 --doctests --ignore=F811` in Travis, but I just wanted to make sure that's a correct way, and if it's not I'd like to know a better solution

**Comment by InCogNiTo124** [comment]
Also, doctest from `sympy/core/singleton.py` (line 49) throws a warning about comparing Singleton and a literal with `is`, and although technically not an error, I'd like to know is there anything for me to remove a warning

This is the output I get:
![Screenshot_20200521_044553](https://user-images.githubusercontent.com/12953598/82517703-fa110e00-9b1d-11ea-9cc5-c7faf7efdb82.png)

**Comment by oscarbenjamin** [comment]
I think we can write it like:
```
>>> x = 0
>>> x is S.Zero
```
to avoid the warning.

Multiple dispatch gives lots of flake8 warnings. These have been suppressed with a flake8 flag:
https://github.com/sympy/sympy/blob/0f598f042929f9de97bd8ba25ac06a0e4d36881b/sympy/sets/handlers/intersection.py#L14-L16
I guess we can do the same in the doctests if needed.

Ultimately it would be good to find a better way of using multiple dispatch so we don't repeat the same function name #17795.

**Comment by InCogNiTo124** [comment]
I will add the noqa then, since I feel this second solution is out of my scope

**Comment by asmeurer** [comment]
I've said this before, but I'm not a fan of when linters force you to write code in a less clear way, and especially when this is done so in documentation.

**Comment by asmeurer** [comment]
Having noqa cluttering the documentation is also not great. Although it isn't so bad if Sphinx automatically removes it like it does for # DOCTEST: +SKIP.

**Comment by InCogNiTo124** [comment]
Hey, what would you like me to do with `sympy/utilities/runtests.py`? `flake8 --doctests sympy/utilities/runtests.py` reports an `F403` (which is interesting I guess since it has no doctest code)

**Comment by oscarbenjamin** [comment]
I think we can avoid using noqa for multiple dispatch by making all the functions called `_` as is done for single dispatch.

**Comment by oscarbenjamin** [comment]
I don't see any 403 from
```
$ flake8 --doctests sympy/utilities/runtests.py
(no output)
```

**Comment by InCogNiTo124** [comment]
> I don't see any 403 from
> 
> ```
> $ flake8 --doctests sympy/utilities/runtests.py
> (no output)
> ```

this is interesting, I just had the output and now it's gone :smile:

**Comment by InCogNiTo124** [comment]
> > I don't see any 403 from
> > ```
> > $ flake8 --doctests sympy/utilities/runtests.py
> > (no output)
> > ```
> 
> this is interesting, I just had the output and now it's gone smile

I found a quirk:
```~/repos/sympy$ flake8 --doctests sympy/utilities/
sympy/utilities/runtests.py:9:1: F403 'from sympy.testing.runtests import *' used; unable to detect undefined names
sympy/utilities/benchmarking.py:9:1: F403 'from sympy.testing.benchmarking import *' used; unable to detect undefined names
sympy/utilities/randtest.py:9:1: F403 'from sympy.testing.randtest import *' used; unable to detect undefined names
sympy/utilities/decorator.py:195:9: F821 undefined name '__all__'
sympy/utilities/decorator.py:204:9: F821 undefined name '__all__'
sympy/utilities/tmpfiles.py:9:1: F403 'from sympy.testing.tmpfiles import *' used; unable to detect undefined names
sympy/utilities/quality_unicode.py:9:1: F403 'from sympy.testing.quality_unicode import *' used; unable to detect undefined names
sympy/utilities/pytest.py:9:1: F403 'from sympy.testing.pytest import *' used; unable to detect undefined names
sympy/utilities/_compilation/compilation.py:513:25: F821 undefined name 'A'
~/repos/sympy$ cd sympy
~/repos/sympy/sympy$ flake8 --doctests utilities/
sympy/utilities/decorator.py:195:9: F821 undefined name '__all__'
sympy/utilities/decorator.py:204:9: F821 undefined name '__all__'
sympy/utilities/_compilation/compilation.py:513:25: F821 undefined name 'A'
```
I could not find any `flake8` settings in any of the directories, though.

**Comment by oscarbenjamin** [comment]
I think it needs to be run from the root directory. Those modules in `sympy/utilities` are deprecated stubs because they were moved to `sympy/testing` and the star imports are marked with F401. 

Maybe it should be marked as F403 as well or maybe the star imports should be replaced with explicit imports. Actually I guess explicit imports and `__all__` are better.

I see no output from
```
$ flake8 sympy/utilities/
```
but I do see the same warnings with
```
$ flake8 --doctest sympy/utilities/
```

I think that the proper fix is to figure out which names would have been importable from those modules in sympy 1.5.1 and add all of them as explicit imports in the stub module. Example:
```
$ git checkout sympy-1.5.1
Checking out files: 100% (1083/1083), done.
Previous HEAD position was 56de84d6f2 solvers.ode: Removed corner cases test case
HEAD is now at 70381f282f Merge pull request #18084 from oscarbenjamin/pr_lambdify_fix
$ python
Python 3.8.1 (v3.8.1:1b293b6006, Dec 18 2019, 14:08:53) 
[Clang 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> ns = {}
>>> exec('from sympy.utilities.randtest import *', ns)
>>> del ns['__builtins__']
>>> list(ns)
['print_function', 'division', 'uniform', 'Random', 'randrange', 'randint', 'is_sequence', 'as_int', 'Tuple', 'comp', 'I', 'Symbol', 'nsimplify', 'random_complex_number', 'verify_numerically', 'test_derivative_numerically']
```
I don't think we need `print_function` or `division`. Most of the others are probably not needed so check which things are actually defined in the module:
```
$ git grep 'def' sympy/utilities/randtest.py
sympy/utilities/randtest.py:def random_complex_number(a=2, b=-1, c=3, d=1, rational=False, tolerance=None):
sympy/utilities/randtest.py:def verify_numerically(f, g, z=None, tol=1.0e-6, a=2, b=-1, c=3, d=1):
sympy/utilities/randtest.py:def test_derivative_numerically(f, z, tol=1.0e-6, a=2, b=-1, c=3, d=1):
sympy/utilities/randtest.py:def _randrange(seed=None):
sympy/utilities/randtest.py:        def give(a, b=None, seq=seed):
sympy/utilities/randtest.py:def _randint(seed=None):
sympy/utilities/randtest.py:        def give(a, b, seq=seed):
$ git grep 'class' sympy/utilities/randtest.py
$
```
The intersection of these two lists should be added as an explicit import e.g.:
```
from sympy.testing.randtest import random_complex_number, verify_numerically, test_derivative_numerically
```
On the other hand maybe all of the keys from `ns` could be added. The stub modules only exist for backwards compatibility so we might as well try to make them as similar as possible to how they used to be. In which case:
```
from sympy.testing.randtest import print_function, division, ...
```
