### ISSUE TITLE
Suggestion: allow evaluate option to subs

### ISSUE THREAD

**Issue by mcpl-sympy** [sympy/sympy#19371]
Just as `diff` method with `evaluate=False` returns `Derivative`, I think it would be nice to allow `evaluate=False` option (which is by default `True`) for `subs` method to return `Subs`.  

Here is an example:
```python
>>> from sympy.abc import x,y
>>> (x+y).subs(x,1)
y + 1
>>> (x+y).subs(x,1, evaluate=False)
Subs(x+y, x, 1)
>>> (x+y).subs(x,1, evaluate=False).doit()
y + 1
```

How is it? If this is OK, I can make a PR for this.

**Comment by oscarbenjamin** [comment]
That seems reasonable to me
