### ISSUE TITLE
Implement color cycler for plotting.

### ISSUE THREAD

**Issue by sylee957** [sympy/sympy#19384]
This is supported by matplotlib in their `plot` API, but sympy plotting bypasses that by using the the artist API, so there is a problem that multiple plots always having the same color by default.
If matplotlib provides some API for getting the color cycles, it can be mirrored here, however we can develop our own color cycler if that is not possible.

And the same issue should be investigated for different plotting APIs like contour or 3d plots, whether it cycles the colors or not.

```python3
import matplotlib.pyplot as plt
import numpy as np

x = np.linspace(-10, 10, 100)
y = np.cos(x)
y2 = np.sin(x)
b = plt.plot(x, y, x, y2, x, y)
```
![image](https://user-images.githubusercontent.com/34944973/82475596-b3b0b480-9b07-11ea-993c-928e5f0e946e.png)

```python3
from sympy import *

x = Symbol('x')
plot(cos(x), sin(x), (x, -10, 10))
```
![image](https://user-images.githubusercontent.com/34944973/82475614-bad7c280-9b07-11ea-9f95-3cde18acb265.png)

**Comment by jondo** [comment]
In the meantime, I'm using the following workaround: https://github.com/sympy/sympy/issues/20378#issuecomment-721784288
