### ISSUE TITLE
latex to sympy parse error

### ISSUE THREAD

**Issue by max-yue** [sympy/sympy#19393]
lat = '1 \times 2'
expr = parse_expr(lat, evaluate=False)

I notice the origin latex2sympy repo support this convert, while sympy raise an exception.

File "C:\Users\user\Anaconda3\lib\ast.py", line 35, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
  File "<unknown>", line 1
    Integer (1 )\Symbol ('times2' )
                                  ^
SyntaxError: unexpected character after line continuation character

**Comment by sylee957** [comment]
You should use `parse_latex`.
And you should use double slashes `\\` or raw strings for `\times` because it can become tab because of how python handles escape sequences.
```
from sympy.parsing.latex import parse_latex
lat = r'2 \times 3'
parse_latex(lat)
```

**Comment by oscarbenjamin** [comment]
@max-yue does `parse_latex` do what you want?

I think this can be closed.

**Comment by max-yue** [comment]
Thank you, your answer do help, but `1 \ times 2` still fail.

**Comment by oscarbenjamin** [comment]
How does it fail? I get this:
```julia
In [8]: from sympy.parsing.latex import parse_latex                                                                               

In [9]: parse_latex(r"1 \times 2 ")                                                                                               
Out[9]: 2
```

**Comment by max-yue** [comment]
when we do parsing, evaluate is False, so 1 \times 2 should give us Mul(1, 2) rather than 2.

**Comment by oscarbenjamin** [comment]
Unfortunately `evaluate=False` does not stop identities from being filtered:
```julia
In [1]: Mul(1, 2, evaluate=False)                                                                                                 
Out[1]: 2
```
