### ISSUE TITLE
object p from Permutation.__mul__() doesn't have p.__dict__['_cyclic_form']

### ISSUE THREAD

**Issue by Back2Basics** [sympy/sympy#19408]
```
from sympy.combinatorics import Permutation 
alpha = Permutation(1,2)
beta = Permutation(3,4,5)
omega = alpha*beta

print(omega.__dict__['_cyclic_form'])
```
KeyError: '_cyclic_form'

FYI:  if you use jupyter notebook to print out the object at each step, then the __repr__() adds the key '_cyclic_form'
by using the line:
`cycles = Permutation(self).cyclic_form`
So I suggest using the same logic as the __repr__() to add omega.__dict__['_cyclic_form']
There might be a shorter way to do this.

**Comment by jksuom** [comment]
`_cyclic_form` is a class attribute.
```
>>> from sympy.combinatorics import Permutation 
>>> alpha = Permutation(1,2)
>>> beta = Permutation(3,4,5)
>>> omega = alpha*beta
>>> print(omega.__class__.__dict__['_cyclic_form'])
None
```
Do you suggest that it should always be an instance attribute as well?

**Comment by Back2Basics** [comment]
I was going to say alpha and beta both have a "_cyclic_form" in their dictionaries but I realized too late that I had printed the __repr__() in both those cases which then added "_cyclic_form" to each and I though it was inconsistent that omega didn't have the attribute after a __mul__().  But it turned out that the default case was to not have "_cyclic_form" at all.
