### ISSUE TITLE
Define anticommutation relations for fermionic operators

### ISSUE THREAD

**Issue by Marco-Di-Tullio** [sympy/sympy#19423]
Hi!
I work with fermionic operators, and found the functions defined over **sympy.physics.secondquant** very useful. Nontheless, it lacks two fundamental and seemingly easy to deploy tools. 

1. Defining an Anticommutator: only commutators are defined in this file. There is an AntiCommmutator function defined in sympy.physics.quantum , but it doesn't work properly with sympy.physics.secondquant.
2. Automatically understand the fermionic anticommutation relations, as it already does when performing permutations: I mean, subtitute 
![imagen](https://user-images.githubusercontent.com/13991676/82765659-0b446e00-9def-11ea-987e-b3ac2f8eb203.png)
whenever it shows up.

This would make this package really stronger for obtaining analytical results.
Thank you in advance.

**Comment by Stam21** [comment]
@Marco-Di-Tullio hello buddy, I would like to get started with this issue but I don't have a clue about quantum physics, I just started learning. So I would really appreciate if you could share some sympy code of yours so I can better understand what you proposing.
e.g. how you concluded that anticommutator doesn't work properly for secondquant?

**Comment by Marco-Di-Tullio** [comment]
Hi @Stam21 ! Thank you for reaching out, really appreciate it.

1. The commutator is defined in the library **sympy.physics.secondquant** like so
![imagen](https://user-images.githubusercontent.com/13991676/84428904-a6b24d00-abfd-11ea-83cd-879fa5053da8.png)
It would be useful to also have the anticommutator defined, which should be equally done as the commutator, just with a sign change.
![imagen](https://user-images.githubusercontent.com/13991676/84428931-b467d280-abfd-11ea-943e-855eedb07e8c.png)

2. Bosons and Fermions are the two families of fundamental particles in physics. They can be mathematically defined though operators obeying a mathematical relation. For instance, suppose you have a particle of the family of bosons which is moving with a certain speed. In physics we represent this situation by saying that we created a boson with this speed over the vacuum. This "creation" is mathematically constructed by applying an operator on an empty state (the vacuum). These operators are those being defined in this library **sympy.physics.secondquant** as Bd and Fd (create a boson and create a fermion respectively). You can also find B and F, which correspond to the inverse operation (i.e. destruction). The argument of B( ), Bd( ), F( ) and Fd( ) will be the speed of our particle, or in a general situation "the mode" (modes can be speeds, energies, spins, or many other degrees of freedom). Mathematically speaking, and this is where my question was pointing, these operators are completely defined by commutation and anticommutation relations.
For bosons  we have
 ![imagen](https://user-images.githubusercontent.com/13991676/84429842-30164f00-abff-11ea-86d4-ece270864815.png)
For fermions we have instead
 ![imagen](https://user-images.githubusercontent.com/13991676/84429854-360c3000-abff-11ea-9cac-76f8300beaac.png)
The library **sympy.physics.secondquant** automatically understands the commutation relationships for bosons and the fermionic anticonmutators that returns zero. But it struggles with the fermionic anticommutation relation returning a delta. The other cases it replaces every time a commutator shows up with the appropriate symbol, but not in this case.

In the meantime I also noticed some inconsistencies with the contractions. I think the main issue might be lying here, but I am not entirely sure about this.
`adi = Fd(Symbol("i"))`
`aj = F(Symbol("j"))`
`con = contraction(adi,aj)`
This returns
![imagen](https://user-images.githubusercontent.com/13991676/84427805-e24c1780-abfb-11ea-83cd-e69245edcf60.png)
which is the correct answer, but duplicate. This should not be a problem, but if I now call `evaluate_deltas(con)` the answer given is
![imagen](https://user-images.githubusercontent.com/13991676/84427993-1cb5b480-abfc-11ea-9a70-b769b2bb829a.png)
Which is wrong. It is contracting the wrong indices.
This problem shows up every time I `contract`, or use the `doit` and `wicks` commands.

**Comment by Marco-Di-Tullio** [comment]
Regarding point 2, I can add some example code:
`adi=Fd(Symbol("i"))`
`aj = F(Symbol("j))`
`wicks(adi*aj+aj*adi)`
The returned value is this one
![imagen](https://user-images.githubusercontent.com/13991676/84430659-63a5a900-ac00-11ea-826f-5b85c9c7a50a.png)
which even understands an "a" as an index argument.

**Comment by akirakyle** [comment]
related: https://github.com/sympy/sympy/issues/5980

**Comment by Stam21** [comment]
@Marco-Di-Tullio Hey Marco, regarding the fermionic anticommutation relation returning a delta, the reason that contraction returns duplicate result is because you don't define above_fermi/below_fermi  inside the symbol of F and Fd.

E.g.   In case that they are above_fermi: 
`i,j = symbols('i j',above_fermi=True))`
`con = contraction(F(i),Fd(j))`  
`evaluate_deltas(con)`

        In case that they are below_fermi:
`i,j = symbols('i j',below_fermi=True))`
`con = contraction(Fd(i),F(j))`
`evaluate_deltas(con)`

Also with the wicks method: 
`i,j = symbols('i j',above_fermi=True)`
`con = contraction(Fd(i),F(j))`
`wicks(Fd(i)*F(j)+F(j)*Fd(i))`

**Comment by Marco-Di-Tullio** [comment]
You are absolutely right! I just tested what you said, and it is working properly. Thank you very much for your time.
