### ISSUE TITLE
Sympy contains calls to print without parentheses

### ISSUE THREAD

**Issue by eric-wieser** [sympy/sympy#19434]
Found while investigating something else.

There are bits of code like:

https://github.com/sympy/sympy/blob/4e53a868e8d3b0e5bf241dca9df61c4ce2c339dd/sympy/utilities/iterables.py#L423-L426

and

https://github.com/sympy/sympy/blob/4e53a868e8d3b0e5bf241dca9df61c4ce2c339dd/examples/advanced/pidigits.py#L24-L26

and

https://github.com/sympy/sympy/blob/4e53a868e8d3b0e5bf241dca9df61c4ce2c339dd/sympy/interactive/printing.py#L243-L249

Which presumably were missed in a python 2 -> python 3 conversion, and should instead say `print()`.

**Comment by sidhu1012** [comment]
Can I work on this issue?

**Comment by eric-wieser** [comment]
Go for it :)

**Comment by sidhu1012** [comment]
Okay , thanks

**Comment by sidhu1012** [comment]
Changes done, PR submitted
