### ISSUE TITLE
[GSoC Discussion] Sampling from Stochatic Processes 

### ISSUE THREAD

**Issue by Smit-create** [sympy/sympy#19454]
After completing the sampling from the external libraries, we can think of sampling from the stochastic processes. Something similar to the sample path that is followed by the stochastic process, we can use the same for random sampling at any given time. One of the examples, I found is [http://theanalysisofdata.com/probability/7_2.html](http://theanalysisofdata.com/probability/7_2.html)

**Comment by czgdp1807** [comment]
For example if a Markov process is in state `p` at time `t`, then `sample` on Markov process should give it's next state(based on the probabilities) at time `t+1`.

**Comment by Smit-create** [comment]
I will stimulate and show a live example

**Comment by Smit-create** [comment]
A random simulation of a Simple Random Walk as:

![Screenshot from 2020-05-30 11-54-21](https://user-images.githubusercontent.com/55887635/83321373-d7dd6580-a26c-11ea-9e51-30e4b08d0fc5.png)

**Comment by Smit-create** [comment]
A random simulation of Poisson Process:
![Screenshot from 2020-05-30 12-08-41](https://user-images.githubusercontent.com/55887635/83321613-6e5e5680-a26e-11ea-9d3d-87b7906c4d01.png)

**Comment by Smit-create** [comment]
@czgdp1807 @Upabjojr Does this type of sampling look good for Stochastic Processes? For, Markov Chains I need to look into more details for their simulation

**Comment by Upabjojr** [comment]
Is there a way to test that the generated walk actually conforms to the properties of the generating distribution?

By the way, I'm still convinced that it's bad to reuse the same name for the sampling function of `sample` for stochastic processes. I would prefer `sample` to return a warning about using a different name, e.g. `sample_iter`. Functions should return stable types if possible.

**Comment by czgdp1807** [comment]
May be, `sample_stoch`?

**Comment by Smit-create** [comment]
I tried to simulate DTMC as:

![Screenshot from 2020-06-01 09-01-22](https://user-images.githubusercontent.com/55887635/83373633-b1dbd080-a3e6-11ea-9eea-504edbbcfddb.png)


> Is there a way to test that the generated walk actually conforms to the properties of the generating distribution?

Can be checked by asserting that every element in the `sample` is present in the `state_space`

**Comment by czgdp1807** [comment]
We can set `random.seed` for deterministic tests.

**Comment by czgdp1807** [comment]
Is it even possible to sample continuous time processes? The time is real in that case.

**Comment by Smit-create** [comment]
> Is it even possible to sample continuous time processes?

I didn't find any related resources to it. By the way, are the above comments look good for implementing? I wish we could add plots but it requires more features in sympy's `plotting` ...

**Comment by czgdp1807** [comment]
We can add plotting after some support for sampling stochastic processes is added.

**Comment by Upabjojr** [comment]
> Is it even possible to sample continuous time processes? The time is real in that case.

Try to look into external libraries for sampling, SymPy should not be a numeric library. Numeric stuff should call external libraries.

**Comment by Smit-create** [comment]
> Try to look into external libraries for sampling

We will be using `random` to generate random time for CTMP, and for DTMC will use `scipy` for sampling from finite distribution at each state as in [https://github.com/sympy/sympy/issues/19454#issuecomment-636595027](https://github.com/sympy/sympy/issues/19454#issuecomment-636595027)

For API can we use it as:
```python
>>> X = PoissonProcess('X', 4)
>>> sample_stochastic(X, max_time=10)
...
```

The reason I see, that we can't use `next` i.e return an iterator, is for Continuous-time processes like Poisson Process, each sample is dependent on previous time value as well as a previous sample value. So, I think we should take `max_time` as an argument. if we use an iterator and use `next` then, all the samples will be independent of each other.

**Comment by czgdp1807** [comment]
For continuous time stochastic processes, what will be the time quantum? Like, if the first value from `sample_stochatic` is for time t = 0, then the next value should be of which time stamp? t = 0.01 or t = 1 or t = 0.0001?

**Comment by Smit-create** [comment]
>  Like, if the first value from `sample_stochatic` is for time t = 0, then the next value should be of which time stamp? t = 0.01 or t = 1 or t = 0.0001?

The time will also be sampled randomly until it is less than `max_time`.
For reference see: [https://github.com/sympy/sympy/issues/19454#issuecomment-636287099](https://github.com/sympy/sympy/issues/19454#issuecomment-636287099)

**Comment by czgdp1807** [comment]
What's the logic behind sampling time randomly? Can you provide references where time has been sampled randomly?

**Comment by Smit-create** [comment]
> What's the logic behind sampling time randomly? Can you provide references where time has been sampled randomly?

I have referred from Nptel lectures:
[https://nptel.ac.in/courses/111/102/111102096/](https://nptel.ac.in/courses/111/102/111102096/), week 3, last lecture(0:35 sec)
![Screenshot from 2020-06-03 13-58-49](https://user-images.githubusercontent.com/55887635/83614173-78e85b00-a5a2-11ea-9728-202d97e1c20a.png)

**Comment by czgdp1807** [comment]
Looks good. So, I don't think there is more to discuss on this topic. We can decide more in the PR. Add sampling support first only for one stochastic process and then extend it further for others in future.
