### ISSUE TITLE
Sum.doit() gives incorrect results with Random Indexed Variables

### ISSUE THREAD

**Issue by Smit-create** [sympy/sympy#19456]
While working on #19428, I came across the following error
```python
>>> from sympy.stats import *
>>> from sympy import symbols, S, Eq, Sum
>>> B = BernoulliProcess('B', S(1)/2, 1, -1)
>>> t = symbols('t', positive=True, integer=True)
>>> expr = Sum(B[t], (t,0,5))
>>> expr
Sum(B[t], (t, 0, 5))
>>> expr.doit()  # this should not consider B[t] equal in all the cases as it is random variable
6*B[t]          # incorrect result
```
Expected behaviour, it should produce: `B[0] + B[1] + B[2] + B[3] + B[4] + B[5]`

**Comment by czgdp1807** [comment]
That's quite a problem. Can you please make a PR to fix it?

**Comment by Smit-create** [comment]
> Does the problem exist with parent class of `RandomIndexedSymbol`?

I need to look into it

**Comment by Smit-create** [comment]
> Does the problem exist with parent class of `RandomIndexedSymbol`?

The problem I see here is:
```python
>>> B = BernoulliProcess('B',0.2)
>>> B[t]
B[t]
>>> B[t].free_symbols
{B[t]}
```
Free symbols is returning B[t], but I think for RandomIndexedSymbol, we should return `{B[t], t}` if t is symbolic else` {B[t]}` when t is not symbolic??
