### ISSUE TITLE
latex parsing of "\left" and "\right"

### ISSUE THREAD

**Issue by oliverstefanov** [sympy/sympy#19464]
There seems to be an issue in the latex parser when dealing the "\left" and "\right" tags . Can you reproduce this issue ? 

```
from sympy import *
from sympy.parsing.latex import parse_latex
from sympy.printing import latex

x, y = symbols('x y')
expr = integrate(x**2 * exp(x),x)
expr_latex = latex(expr)
print(expr_latex)  # \left(x^{2} - 2 x + 2\right) \exp \left(x\right)
expr2 = parse_latex(expr_latex)
print(expr2)  # (exp*left(right*x))*left(2*right + x**2 - 2*x)
```

PS : sorry i can get the code to format properly despite using the "insert code" quotes (?)

**Comment by sylee957** [comment]
You have to use ``` instead of ` for formatting multi line code

**Comment by asmeurer** [comment]
See also https://github.com/sympy/sympy/issues/14005
