### ISSUE TITLE
New limits function

### ISSUE THREAD

**Issue by latot** [sympy/sympy#19460]
Hi!

I would like if there is this function to can return all the values from all directions of the limit, in 2 dims, we only have 2 directions, but when we start with 3 dims this start to increase, and with 4...., well a lot more, the idea es can get all limits that can exist in a specific point.

This can be used in the actual "limit" function too, when is asked if there exist "one" limit, so all the limits should be the same, is call the "limits" function and compare the results.

Thx.

**Comment by anutosh491** [comment]
Do you know of a way , we could go about implementing this?? @latot

**Comment by oscarbenjamin** [comment]
It's pretty straight-forward to calculate the limit from both negative and positive directions (and this is already used for finding a bidirectional limit). SymPy doesn't really have the concept of a multidimensional limit.

**Comment by anutosh491** [comment]
> It's pretty straight-forward to calculate the limit from both negative and positive directions (and this is already used for finding a bidirectional limit). SymPy doesn't really have the concept of a multidimensional limit.

Yeah correct, who wouldn't like to have multidimensional limits in sympy ..... only if we could have a clear direction to proceed but sadly needs more thought I feel .

**Comment by latot** [comment]
Yes, there is simple ways to do that, with some things to notice, lets pick the example, ```f(x, y)```, and the limit over ```x'```, and ```y'```.

1) get the limits in ```f(x'+, y)```, now there is one func ```f(y)```
2) get the limits in ```f(y'+)``` and ```f(y'-)```

We can always get the limit from one to one, until there is no more variables and get the final limit.

Considerations, the next points is when happens to have ```oo*0```, or ```oo/00``` or any similar.

imagine ```z=x/y```, where ```x``` and ```y``` go to ```inf```. The hard part in this concept, is that as independent variables, they can reach a specific point in several ways, imagine  a ```x``` ```y``` line in a graph, like ```x(t)``` ```y(t)``` and the only condition is that ```x``` and ```y``` go to infinity, there is infinite ```x``` and ```y``` that accomplish that conditions, and everyone of them can reach a different limit.

This limits are the hardest ones...

Lest follow the example ```x/y```, there is only 3 cases:

1) where ```x(t) >>> y(t)```, the limit is inf
2) where ```x(t) <<< y(t)``` the limit is 0
3) when ```x(t)/y(t)``` converge, the limit is k, so any number, not really, how x and y go to positive inf, that means is any positive value.

I don't have a way solve this cases..., maybe someone else can have an idea or method.

**Comment by oscarbenjamin** [comment]
Asking for all the possible limits from all directions does not seem well defined to me. Even for two real variables there are infinitely many directions like `limit(f(x + t*cos(theta), y + t*sin(theta)), t, 0)`. Asking for a unique limit (if one exists) that is valid from all directions is something that could be useful but you wouldn't use a "limits" function to make that.

Without any concrete examples of how this could be useful or even well defined I don't think that this open issue is helpful.

**Comment by anutosh491** [comment]
> Without any concrete examples of how this could be useful or even well defined I don't think that this open issue is helpful.

+1 . I come back to this issue quite some times to think if we can produce something related to what the issue demands , but without some examples or usecases of how this would work out .... I am not sure how to proceed here . Maybe a could close label should be added here ?

**Comment by oscarbenjamin** [comment]
I'm just going to close this. I think if someone can come up with something well defined then this can be reconsidered.
