### ISSUE TITLE
Collect doesn't replace dummy variables with the input syms

### ISSUE THREAD

**Issue by hungpham2511** [sympy/sympy#19486]
Sympy version 1.6.0

Note: sympy v.1.5.0 works correctly as specified by the expected output.

Given this short code snippet
```
import sympy as sym

s = sym.symbols('s')
expr = sym.exp(-s)

d = sym.collect(expr, sym.exp(s), evaluate=False)
```
Expected output:
```
{exp(s) ** (-1): 1}
```
Actual output:
```
In [41]: d
Out[41]: {1/_Dummy_28: 1}
```

**Comment by smichr** [comment]
Maybe fixed 9 days ago with #19431

**Comment by friyaz** [comment]
In the development version, I get:
```python
>>> sym.collect(expr, sym.exp(s), evaluate=False)
{exp(-s): 1}
```

**Comment by hungpham2511** [comment]
Awesome. Look like it's solved. Thank everyone for your comments. I will close the issue.
