### ISSUE TITLE
backport lru_cache required for Python2

### ISSUE THREAD

**Issue by pbrady** [sympy/sympy#19493]
I am in the process of excising fastcache (see #19492) and decided to remove the backported lru_cache as well since its unnecessary for python >= 3.5.  However, these test suite requires 2.7 support.

Should 2.7 be removed from the test suite?

**Comment by oscarbenjamin** [comment]
2.7 is removed from the test suite except for a test that checks that a nice error message is given when trying to import sympy in Python 2.x.

**Comment by pbrady** [comment]
Thanks for clarification!  I'll remove the backported cache then
