### ISSUE TITLE
Stray *1.0 in the output of simplify

### ISSUE THREAD

**Issue by Volker-Weissmann** [sympy/sympy#19505]
```
from sympy import *
x = symbols("x")
print(simplify(1.0*x/1.0))
```
Outputs "1.0*x", but i think it should output "x".

**Comment by smichr** [comment]
It is 1.0 since 1.0 is not an exact number in the context of an expression so if x is replaced with 2 the answer would be 2.0.

**Comment by Volker-Weissmann** [comment]
Is it possible to somehow remove this stray "1.0". I tried dividing by 1.0 but this doesn't work.

**Comment by oscarbenjamin** [comment]
Use `nsimplify` to convert floats to rationals:
https://docs.sympy.org/latest/modules/simplify/simplify.html#nsimplify

**Comment by Volker-Weissmann** [comment]
> Use `nsimplify` to convert floats to rationals:
> https://docs.sympy.org/latest/modules/simplify/simplify.html#nsimplify

Doesn't work with units:
`print(sympy.nsimplify(1.0*meter))`
outputs 1.0*meter
