### ISSUE TITLE
should ConditionSet allow assumptions on bound variables?

### ISSUE THREAD

**Issue by smichr** [sympy/sympy#19517]
Should assumptions on dummy args should be supported?
```python
>>> n = Symbol('n', negative=True)
>>> ConditionSet(n, n < 2, S.Integers)
Integers
```
But that set should be "all integers less than 2"....or is that a garbage-in-garbage-out result?

**Comment by oscarbenjamin** [comment]
That's garbage in, garbage out. If there are assumptions on a dummy symbol then they should not contradict the implied context so in this case `integer=True` is fine but anything stronger than that is not.

**Comment by oscarbenjamin** [comment]
We could try to warn/raise in this situation https://github.com/sympy/sympy/issues/17341#issuecomment-639408994

**Comment by smichr** [comment]
Here are two examples that might help clarify the issue:
```
a. ConditionSet(pi, y < 4, S.Integers)
b. ConditionSet(1,x<2,S.Integers)
```
If the symbol is a constant then that means there is 1 or 0 elements in the set being represented. `ConditionSet(x, x< 2, Integers)` means "all integers less than 2", the "all" by merit of the `x` and "integers" by merit of the base and "less than 2" by merit of the condition. So it seems like "a." should give the empty set while "b." should be `{1}`.

**Comment by oscarbenjamin** [comment]
> a. ConditionSet(pi, y < 4, S.Integers)
> b. ConditionSet(1,x<2,S.Integers)

These are nonsensical. If `pi` is a number then we can't use it as the all quantifier like this.

a. "The set of pi for all pi in Z where y < 4".
b. "The set 1 for all 1 in Z where x < 2"

We can't quantify with concrete numbers "for all pi in Z" so the first arg for condition set has to be something that maps a symbol/symbols to the baseset. Both of these examples should raise.

A PiecewiseSet should be used for that kind of conditional set. A ConditionSet is about choosing a subset of the baseset.

**Comment by smichr** [comment]
Does this make sense?
```
ConditionSet(x, y > 5, Interval(1, 7)))
```

**Comment by oscarbenjamin** [comment]
> Does this make sense?

I think that it does make sense. As you say it would be better expressed as a PiecewiseSet:
```julia
In [33]: Piecewise((Interval(1, 7), y>5),(S.EmptySet,True))                                                                                    
Out[33]: 
⎧[1, 7]  for y > 5
⎨                 
⎩  ∅     otherwise
```

> The intersections allows for assumptions on x.

I think that the assumptions on x should be ignored as x is a bound (dummy) symbol in this context.

**Comment by smichr** [comment]
> We could try to warn/raise in this situation

Here is a situation where an error is now raised because the solution is not positive.
```
    x, y, z = symbols('x y z', positive=True)
    a, b = symbols('a b')
    assert solveset_real(a**x - b**x, x) == ConditionSet(
        x, (a > 0) & (b > 0), FiniteSet(0))
```

**Comment by oscarbenjamin** [comment]
Maybe `solveset` could warn/raise if the assumptions on the symbol are inconsistent with the domain. I think that makes more sense than ConditionSet doing it although we could do both.
