### ISSUE TITLE
simplify ConditionSet

### ISSUE THREAD

**Issue by smichr** [sympy/sympy#19520]
The following
```
ConditionSet(x + 1, x + 1 < 1, Integers)
```
could be
```
Conditionset(x, x < 0, Integers)
```
I'm not sure if this should happen from a `canonical` routine or `simplify` routine.

**Comment by oscarbenjamin** [comment]
I'm not sure that using `x+1` there should be supported at all. It's like
```
In [9]: Lambda(x+1, x+1)                                                                                                                       
---------------------------------------------------------------------------
BadSignatureError
```

**Comment by smichr** [comment]
More complicated expressions are passed from unsolved equations in `solveset`.

**Comment by oscarbenjamin** [comment]
Can you give an example?

**Comment by smichr** [comment]
I am mistaken. Maybe it was some other set-related function. But I agree that this should be actively discouraged.

**Comment by smichr** [comment]
@oscarbenjamin , there is an example now.

**Comment by oscarbenjamin** [comment]
I don't understand what the example is. I tried that and get:
```julia
In [1]: solveset(Abs(x + 4*Abs(x + 1)), x, Reals)                                                                                              
Out[1]: {-4/3, -4/5}
```
