### ISSUE TITLE
Should Dagger of TensorProduct change the order?

### ISSUE THREAD

**Issue by cshaa** [sympy/sympy#19541]
In quantum mechanics it's standard to write:
```
( |A>|B> )† = <B|<A|
```
This way, one can apply the products step by step and get a correct result:
```
( |A>|B> )† |A>|B> = <B|<A|A>|B> = <B| ‖A‖² |B> = ‖A‖² <B|B> = ‖A‖² ‖B‖²
```

However in sympy, Dagger simply „walks through“ the tensor product and doesn't change the order of the kets:
```python
srepr(qapply( Dagger(TensorProduct( Ket('A'), Ket('B') )) ))
> TensorProduct( Bra('A'), Bra('B') )
```

The advantage of this is that when we work on the product space H₁⊗H₂, the first argument of TensorProduct is always from H₁ and the second one is always from H₂. This can presumably result in simpler distribution/expansion/evaluation rules.
The obvious disadvantage is that it's nonstandard to write bra-kets like this.

How do Dagger and TensorProduct behave on matrices and row/column vectors? Do they work correctly, or does this behavior produce invalid results there?

**Comment by evatiwari** [comment]
In the [documentation](https://docs.sympy.org/latest/modules/physics/quantum/tensorproduct.html?highlight=tensorproduct#module-sympy.physics.quantum.tensorproduct), something along these lines has been mentioned:
We can take the dagger of a tensor product (note the order does NOT reverse like the dagger of a normal product):
```
>>> from sympy.physics.quantum import Dagger
>>> Dagger(tp)
where tp is:
>>> tp = TensorProduct(A, B)
```
I thought the "normal" product of two bras/kets is basically their tensor product, as given by this [link].(https://docs.microsoft.com/en-us/quantum/concepts/dirac-notation)  under the tensor product notation section.

**Comment by evatiwari** [comment]
In tensor products, the order does not change on applying dagger. On changing the order, we get the transpose of the original answer. 
```
>>> from sympy import *
>>> from sympy.physics.quantum import TensorProduct, Dagger
>>> A = Matrix([1,2,3])
>>> B = Matrix([4,5])
>>> Dagger(TensorProduct(A, B))
Matrix([[4, 5, 8, 10, 12, 15]])
>>> TensorProduct(Dagger(A), Dagger(B))
Matrix([[4, 5, 8, 10, 12, 15]])
>>> TensorProduct(Dagger(B), Dagger(A))
Matrix([[4, 8, 12, 5, 10, 15]])
```
This could be verified manually. I am guessing this issue could be closed, because it works perfectly fine with row/column vectors.

**Comment by ellisonbg** [comment]
Nielsen & Chuang, Exercise 2.28 has a clear statement of the fact that dagger, conjugate, and transpose don't change the order of the arguments of the tensor product.
