### ISSUE TITLE
Simplify for heavy symbols

### ISSUE THREAD

**Issue by saareliad** [sympy/sympy#19561]
Hi (this is a question):
I have a simple expression for which the free symbols are
```
{\beta_{1}, \beta_{2}, \epsilon, \eta, g_{t}, m, v}
```
where `m,v,  \eta, g_{t}` are tensors and the rest are scalars.
As there is a major cost-difference for operations in the expression, we want to optimize the costly operations (tensor-tensor).

How can we do it with Sympy?
The `count_ops` measure is not good of course.

As a reference I add an example expression:
![image](https://user-images.githubusercontent.com/22762845/84682961-1fd3dc00-af3f-11ea-8e7e-280c3d67a852.png)

**Comment by oscarbenjamin** [comment]
Github issues are for changes in sympy. If you have a question about using sympy then you can ask on the mailing list:
https://groups.google.com/forum/#!forum/sympy
Or otherwise on stackoverflow:
https://stackoverflow.com/questions/tagged/sympy
