### ISSUE TITLE
Travis status not being reported in github

### ISSUE THREAD

**Issue by oscarbenjamin** [sympy/sympy#19589]
Sometimes when a build on Travis completes successfully the PR on github does not update and just says "Pending — The Travis CI build is in progress".

Googling this leads to a number of other reports over the years and it seems maybe the solution is to migrate to Github Apps:
https://travis-ci.community/t/github-status-not-posted-on-commits-on-repositories-using-legacy-service-integration/7798

I'm not sure if sympy is currently using the "legacy service integration" or not but apparently that is a common cause of this issue.

Does anyone know how to check whether this has already been done? Should we do the migration as described here?
https://docs.travis-ci.com/user/migrate/legacy-services-to-github-apps-migration-guide/

**Comment by oscarbenjamin** [comment]
I don't know if the problem is to do with Travis or Github or if it is the legacy service integration but it is happening frequently and possible getting worse.

**Comment by oscarbenjamin** [comment]
It seems that core Python had a problem with github/Travis integration and fixed it by migrating from the legacy API:
https://mail.python.org/archives/list/python-dev@python.org/message/ZABQWCQKUNKNO5XUCNIMB7GELSXTA646/

**Comment by naveensaigit** [comment]
This could be closed now imo since we have migrated to github actions

**Comment by oscarbenjamin** [comment]
Yes, I guess so
