### ISSUE TITLE
no public documentation for ZZ_I and QQ_I

### ISSUE THREAD

**Issue by gschintgen** [sympy/sympy#19583]
See https://docs.sympy.org/dev/modules/polys/internals.html#concrete-domains

Basic docstrings are in place, but they're not referenced in doc/src/modules/polys/internals.rst.

At least the existence of the classes in gaussiandomains.py could be acknowledged. (I think some `autoclass` references should do the trick.)

**Comment by SriLikesToSing** [comment]
hi im a complete beginner to this open source project how should I start making the documentation for this?

**Comment by gschintgen** [comment]
> how should I start making the documentation for this?

Consult the Style Guide: https://docs.sympy.org/latest/documentation-style-guide.html

Then look at how the (very basic) documentation linked in the OP looks. That's the result of the docstrings present in `sympy/polys/domains/*.py` and the references in `doc/src/modules/polys/internals.rst`.

The classes `GaussianRationalField` and `GaussianIntegerRing` need the same treatment.

**Comment by Raghibshams456** [comment]
@SriLikesToSing  are u working on this???

**Comment by Rahul-3000** [comment]
hey, I want to contribute for documentation. plz someone guide me.

**Comment by Abhayram-A-Nair** [comment]
If this isn't being worked on can i start working on this? I'm pretty much new to open source and work like to start contributing

**Comment by oscarbenjamin** [comment]
Anyone is welcome to work on this but it might be difficult if you are not already relatively familiar with the sympy codebase. I don't see where any of the other poly domains are documented but it might be possible to build something from existing documentation if there is any.

**Comment by Abhayram-A-Nair** [comment]
okay i will try to go through the codebase to better understand the issue and try fix the issue

**Comment by elysian12** [comment]
Hello, I am a noobie in open source contribution and I wanna contribute to this project.
Please Guide me on How I can fix this issue.
