### ISSUE TITLE
RuntimeError in nonlinsolve

### ISSUE THREAD

**Issue by proy87** [sympy/sympy#19587]
```
n,m = symbols('n m')
nonlinsolve([32*2**m*2**n - 4**n, 27*3**m - 3**(-n)], m, n)
```

raises `RuntimeError: maximum recursion depth exceeded`

**Comment by gschintgen** [comment]
I can confirm this on master. (With `real=True` it's working though)
Here's a slightly simpler reproducer:
```
solveset(-2**n + 4*2**(log(3**(-n))/log(3)))
```
(for general i.e. complex `n`)

**Comment by MaqOwais** [comment]
Related : https://github.com/sympy/sympy/issues/18552
