### ISSUE TITLE
powdenest(sqrt(sin(x)**2), force=True) does not work

### ISSUE THREAD

**Issue by meganly** [sympy/sympy#19627]
Since `powdenest(sqrt(x**2), force=True)` gives `x`, I would expect `powdenest(sqrt(sin(x)**2), force=True)` to be `sin(x)`.

**Comment by smichr** [comment]
But `sqrt(sin(3*pi/2)**2)` != `sin(3*pi/2)`, the former being 1 and the latter being -1.

**Comment by smichr** [comment]
Knowing that x is positive is not sufficient to guarantee that the result will be positive.

**Comment by meganly** [comment]
I didn't realize that force=True changes variables to positive.  I thought force=True should do the simplification regardless of the assumptions.

**Comment by oscarbenjamin** [comment]
It's difficult to know what the valid rules should be with something like `force=True` since by definition it should break the normal mathematical rules.

**Comment by meganly** [comment]
Yes, that is difficult.  I should have read the documentation better, but it seems weird to me that force=True makes symbols positive instead of forcing the simplification.  I feel like force should just do it and deal with wrong results.

When solving an integral by trig substitution, I'd want to simplify `sqrt(sin(x)**2))` to `sin(x)`.  This is valid because I can assume x is in some appropriate domain like 0<x<pi.  However, I'm lazy and don't want to define assumptions.  Is there a way to force the simplification without assumptions?

**Comment by smichr** [comment]
You can use `replace` to do this, e.g.
```python
>>> eq=1/sqrt(sin(x)**2)
>>> eq.replace(lambda x: x.is_Pow and abs(x.exp) is S.Half and x.base.is_Pow
...   and x.base.exp == 2, lambda x: x.base.base**(x.exp*2))
1/sin(x)
```

**Comment by meganly** [comment]
Thanks!  Assumptions can be tricky.  Should 'x/x' not reduce to 1 because we haven't specified that x is not 0?

**Comment by smichr** [comment]
> Should `x/x` not reduce to 1 because we haven't specified that x is not 0?

Technically, yes. And even if you say that x *is* zero it will reduce to 1 because the flattening routine does not check for the assumptions when making this simplification. I'm not sure how much it would slow things down to check assumptions...or how desirable would be the result.

**Comment by meganly** [comment]
It seems to me there has to be a balance between being technically correct and getting somewhere.  It's interesting that Sympy does some simplifications without checking assumptions, but not others.  Why does `logcombine` with `force=True` do the force the simplification but `powdenest` with `force=True` change symbols to positive?

**Comment by smichr** [comment]
> Why does `logcombine` with `force=True` force the simplification but `powdenest` with `force=True` change symbols to positive?

historical, simplicity, mathematical myopia (often by myself). A change to replace all non-symbol bases with dummies at the outset if the force flag is true would be an appropriate change, I think:

```python
def powdenest(expr, ...):
  def core_base(pow):
    if not isinstance(pow, Pow):
        return pow
    return core_base(pow.base)
  if force:
    reps = {k: Dummy(positive=True) for k in [core_base(p) for p in expr.atoms(Pow)] if not k.is_positive is None]}
    if reps:
        ireps = {v: k for for k,v in reps.items()}
        return powdenest(expr.subs(reps), other args).xreplace(ireps)
  ...
```

**Comment by oscarbenjamin** [comment]
> ```python
> >>> powdenest(sqrt(sin(x)**2),force=1)
> Abs(sin(x))
> ```

That's what I get on master:
```
In [1]: powdenest(sqrt(sin(x)**2),force=1)                                                                                                     
Out[1]: │sin(x)│
```

**Comment by smichr** [comment]
> That's what I get on master:

Hmm. I tried this several times under Windows and did not see this result. Will check again later.

**Comment by smichr** [comment]
Looks like a difference in how Function and Symbol are handled:
```python
>>> from sympy.abc import x
>>> f=Function('f', positive=1)
>>> sqrt(f(x)**2)
Abs(f(x))
>>> var('x', positive=1)
x
>>> sqrt((x)**2)
x
```

**Comment by oscarbenjamin** [comment]
I see this with a vanilla symbol:
```python
>>> from sympy import *
>>> x = Symbol('x')
>>> powdenest(sqrt(sin(x)**2),force=1)
Abs(sin(x))
```
That's current master.

**Comment by smichr** [comment]
> I see this with a vanilla symbol:

yes, agreed. But a function and a symbol, both defined as positive, are being treated differently when taking `sqrt` of the same per example that I gave. That's an issue in itself and might fix this issue if it is fixed.

**Comment by oscarbenjamin** [comment]
That's due to this
https://github.com/sympy/sympy/blob/35fe74cdd23f53a38c5b1f0ade556d49d4e98c66/sympy/functions/elementary/complexes.py#L524-L525

**Comment by smichr** [comment]
> That's due to this

I figured it was there somehow but didn't have time to sleuth. Nice find. This can be removed since functions can now carry assumptions.

**Comment by asmeurer** [comment]
An example from a gitter user: `(y**(1/(1 - alpha))**(1 - alpha)`. It should simplify if `y` is positive and `0 < alpha < 1`, but there's no way to tell powdenest the second assumption. It would be useful if force=True just did a structural replacement, ignoring the assumptions requirements. If the user does force=True, it is on them to verify the mathematical correctness of the replacement.

**Comment by asmeurer** [comment]
A simple workaround is to manually denest with a pattern and `replace`:

```py
>>> expr = ((y**(1/(1 - alpha)))**(1 - alpha))
>>> a, b, c = Wild('a'), Wild('b'), Wild('c')
>>> expr.replace((a**b)**c, a**(b*c))
y
```

**Comment by thorek1** [comment]
and while we are at it here is a more complicated example highlighting the same issue with exp()
```
from sympy import *
var("y, alpha, x, beta, delta",positive = True,real=True)
a, b, c, d, e, f = Wild('a'), Wild('b'), Wild('c'), Wild('d'), Wild('e'), Wild('f')
expr = (exp(delta/(1-alpha))*x**(beta/(1-alpha))*y**((1-beta)/(1-alpha)))**(1-alpha)

exp_trial = powdenest(expr, force=True)
exp_trial2 = simplify(expr, force=True)

tmp  = expr.replace((a*exp(b))**c, a**c*exp(b*c)).replace((a*b**c)**d, a**d*b**(c*d))
while tmp != expr:
    tmp = expr
    expr = expr.replace((a*b**c)**d, a**d*b**(c*d))
    expr = expr.replace((a*exp(b))**c, a**c*exp(b*c))
```

it would be great if powdenest and simplify could handle this case with force=True. for now I will resort to the while loop to iron out these cases.

this problem is quite relevant for economics where many problems have exponents (e.g. production functions: `y=a*k**alpha*l**(1-alpha)`). Using sympy to solve systems of equations of such nature would be great. for now I guess I will have to do manual solving by hand with the while loop. do you have any other ideas?

**Comment by smichr** [comment]
The PR to appear shortly gives:
```python
def test_issue_19627():
    # if you use force the user must verify
    assert powdenest(sqrt(sin(x)**2), force=True) == sin(x)
    assert powdenest((x**(S.Half/y))**(2*y), force=True) == x
    e = 1 - a
    expr = (exp(z/e)*x**(b/e)*y**((1 - b)/e))**e
    assert powdenest(expr, force=True) == x**b*y**(1 - b)*exp(z)
```

**Comment by smichr** [comment]
@thorek1, that was a helpful example, thanks

**Comment by smichr** [comment]
@meganly you might be interested in this change, too

**Comment by asmeurer** [comment]
Indeed `exp` also muddles the water in terms of doing this manually, because it is (currently, https://github.com/sympy/sympy/issues/4898) distinct from `Pow`, so it requires separate replacement patterns.

**Comment by thorek1** [comment]
here is another example written with SymPy.jl which comes from economics (simple RBC model):
```
exx = [1 - (alpha*(k/l)^(alpha-1)+(1-delta)),
        c/(1-l) - w,
        k - (1-delta)*k - i,
        y - i - c,
        y - k^alpha*l^(1-alpha),
        w - (1-alpha)*y/l]

varss = [y, l, w, k, i, c]
solve(exx,varss,force=true)
```
this does not solve but it should and it does if you use the replacements discussed earlier.

the solution should look like this:
```
6-element Vector{Pair{Sym, Sym}}:
 k => delta^(1/(alpha - 1))*(alpha - 1)/(2*(alpha^(alpha/(alpha - 1)) - alpha^(1/(alpha - 1))))
 l => k*(alpha/delta)^(1/(alpha - 1))
 w => (k/l)^alpha*(1 - alpha)
 c => -delta*k + k^alpha*l^(1 - alpha)
 i => delta*k
 y => c + i
```
it would be great if the we could get this to solve using force = true
