### ISSUE TITLE
Maximum time limit exceeded error in Travis

### ISSUE THREAD

**Issue by Smit-create** [sympy/sympy#19628]
The 20th job on the Travis gives the following error and gets terminated:
`The job exceeded the maximum time limit for jobs, and has been terminated.`

For references see the following builds:

1. [https://travis-ci.org/github/sympy/sympy/jobs/701240167](https://travis-ci.org/github/sympy/sympy/jobs/701240167)
2. [https://travis-ci.org/github/sympy/sympy/jobs/701359347](https://travis-ci.org/github/sympy/sympy/jobs/701359347)
3. [https://travis-ci.org/github/sympy/sympy/jobs/701194656](https://travis-ci.org/github/sympy/sympy/jobs/701194656)

**Comment by sylee957** [comment]
Did you try after #19606?

**Comment by Smit-create** [comment]
Yes, it passed when I restarted the job. Thanks!
