### ISSUE TITLE
`rsolve` gives None for linear homogeneous recurrence relation

### ISSUE THREAD

**Issue by Smit-create** [sympy/sympy#19630]
```python
>>> from sympy import rsolve, Function, symbols
>>> n = symbols('n', integer=True)
>>> F = Function('F')
>>> eq = F(n+3) - 3*F(n+1) + 2*F(n)
>>> print(rsolve(eq, F(n), {F(1):0, F(2):8, F(3):-2}))
None
```
While this works when we don't pass initial condition as:
```python
>>> print(rsolve(eq, F(n)))
(-2)**n*C0 + C1*(C0 + C1*n)/C0
```

Expected answer: `F(n) = 2*n + (-2)**n`

**Comment by naveensaigit** [comment]
The issue here is that `solve` is unable to find values of `C0` and `C1`-
https://github.com/sympy/sympy/blob/c3087c883be02ad228820ff714ad6eb9af1ad868/sympy/solvers/recurr.py#L820-L825
We could raise a warning saying sympy is unable to solve for the constants and return the general solution. That would be more helpful than just returning `None`

**Comment by oscarbenjamin** [comment]
The equations for `C0` and `C1` do not have any solution. Are they correct?

The equations are:
```
(Pdb) p equations
[-2*C0 + C1*(C0 + C1)/C0, 4*C0 - 8 + C1*(C0 + 2*C1)/C0, -8*C0 + 2 + C1*(C0 + 3*C1)/C0]
(Pdb) p symbols
[C0, C1]
```
That is:
```python
In [79]: equations = [-2*x + y*(x + y)/x, 4*x - 8 + y*(x + 2*y)/x, -8*x + 2 + y*(x + 3*y)/x]                                      

In [80]: equations                                                                                                                
Out[80]: 
⎡       y⋅(x + y)            y⋅(x + 2⋅y)             y⋅(x + 3⋅y)⎤
⎢-2⋅x + ─────────, 4⋅x - 8 + ───────────, -8⋅x + 2 + ───────────⎥
⎣           x                     x                       x     ⎦

In [81]: solve(equations, [x, y])                                                                                                 
Out[81]: []
```

**Comment by naveensaigit** [comment]
> The equations for `C0` and `C1` do not have any solution. Are they correct?

Yes, they don't have a solution and I verified the same on Wolfram. However, Wolfram is still able to solve the recurrence relation and reports the correct answer - [Try this](https://www.wolframalpha.com/input/?i=F%28n%2B3%29+-+3*F%28n%2B1%29+%2B+2*F%28n%29%3D0%2C+F%281%29%3D0%2CF%282%29%3D8%2CF%283%29%3D-2)
I think we're missing something here.

**Comment by oscarbenjamin** [comment]
Why are there three equations for two symbols?

If this is a third order recurrence then there should be three arbitrary constants. Perhaps this is related to the problem in #17982

**Comment by oscarbenjamin** [comment]
The symbols come from here:
https://github.com/sympy/sympy/blob/bd327ec88c7fdec7791874da6c1529361daf7eb5/sympy/solvers/recurr.py#L617-L624
The poly there has a multiple root:
```
(Pdb) p poly
_Z**3 - 3*_Z + 2
(Pdb) p roots(poly, Z)
{-2: 1, 1: 2}
```
That also happens with the example from #17982:
```
(Pdb) p poly
_Z**3 + 10*_Z**2 + 32*_Z + 32
(Pdb) p roots(poly, Z)
{-2: 1, -4: 2}
```
Maybe the problem is that multiple roots are not handled. Looping over `roots(poly, Z).keys()` ignores the multiplicity of the roots.

**Comment by naveensaigit** [comment]
Yes, currently sympy is not able to solve linear recurrences with order>=2 properly. Some other related issues are #8697, #11261. Infact, some equations with order 1 are also a problem as mentioned in #13629. I think most of the issues from `rsolve` arise from the mistake you pointed out. I'll see how it can be fixed.

**Comment by naveensaigit** [comment]
This can be closed now

**Comment by oscarbenjamin** [comment]
Oh yes, thanks.
