### ISSUE TITLE
Lambdify does not work with Integral

### ISSUE THREAD

**Issue by oscarbenjamin** [sympy/sympy#19641]
```
In [36]: lambdify(z, Integral(1, (x, 0, z)))(1)                                                                                                
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-36-276a7bc694f7> in <module>
----> 1 lambdify(z, Integral(1, (x, 0, z)))(1)

<lambdifygenerated-3> in _lambdifygenerated(z)
      2     return (  # Not supported in Python with SciPy:
      3   # Integral
----> 4 Integral(1, (x, 0, z)))

NameError: name 'Integral' is not defined
```
This could use numerical integration routines from scipy, mpmath etc.

**Comment by sylee957** [comment]
Does scipy support vectorization over parameters for integrals, or it only expects scalar arguments?

**Comment by ehren** [comment]
`scipy.integrals.quad` and `scipy.integrals.nquad` will always return a single float as the actual result of integration (so I think they will also only accept an integrand function that has scalar arguments even though multiple scalar arguments are supported by nquad). But I'm not sure whether there's a function in scipy that handles 'broadcasting' in a more optimal way than just using numpy.vectorize. This seems to be asked in https://stackoverflow.com/questions/57350391/scipy-integrate-quad-quadrature-nquad-cannot-integrate-vector-parameterized (More discussion in the pull #20134).

**Comment by sylee957** [comment]
It looks like we would have to document clearly about how some sympy functions can be vectorized or not with scipy lambdify. I find it confusing that some functions can be evaluated to grid and some functions cannot, and this have important application for developing plotting module.

**Comment by moorepants** [comment]
I think it is reasonable to build in `numpy.vectorize()` into our lambdify printers for numpy/scipy functions that aren't vectorized by default. This would allow things to just work and is probably fine for the majority of use cases.
