### ISSUE TITLE
Introducing Str class to core

### ISSUE THREAD

**Issue by mcpl-sympy** [sympy/sympy#19677]
This topic is briefly discussed in [google groups page](https://groups.google.com/u/2/g/sympy/c/tNm1LDcEXA4).

Currently, many classes use `Symbol` for instance naming. However, since the purpose of `Symbol` is to represent the mathematical scalar whose assumptions are defined, it would be better to introduce `Str` class for this purpose.

Any opinion, please?

**Comment by oscarbenjamin** [comment]
I think that a string object that doesn't do anything apart from comparing equal/unequal and can be substituted seems reasonable to me.

Awkwardly sympify already accepts strings and parses them e.g. `sympify('1+1')` so it isn't possible to use `sympify` here without deprecating/removing parsing from there.

**Comment by mcpl-sympy** [comment]
@oscarbenjamin 
I think `sympify` doesn't have to convert `str` to `Str`, since `Str` is likely to be limited to internal use only.

**Comment by oscarbenjamin** [comment]
That would create a special case that would end up needing to be handled in many places e.g. Tuple:
https://github.com/sympy/sympy/blob/e926fc095fd6402f4d01dc4bf119e63e9fb56a76/sympy/core/containers.py#L50

**Comment by mcpl-sympy** [comment]
My hunch is that `sympify('x') -> Symbol('x')`-behavior does not need to be changed immediately. `Tuple('x')` can return `Tuple(Symbol('x'))` as before with no problem. User will expect 'x' to be transformed to scalar more than they expect it to be transformed to `Str`.

**Comment by oscarbenjamin** [comment]
Okay so the string inputs would not be processed by `simpify/_sympify` but would be explicitly converted to Str when a string argument is expected and needs to be made Basic. Maybe that could work.

The other side to this is that we should deprecate using sympify to parse strings but that's not easy because it's widespread and widely used.
