### ISSUE TITLE
int of product of two C^infinity class function returns Piecewise

### ISSUE THREAD

**Issue by karoldem** [sympy/sympy#19672]
```
from sympy import *

x,m1,m2,s1,s2 = symbols('x,\mu_1, \mu_2, \sigma_1, \sigma_2')

x1 = exp(-1*(x-m1)**2/(2*s1))/(s1*sqrt(2*pi))
x2 = exp(-1*(x-m2)**2/(2*s2))/(s2*sqrt(2*pi))

e = integrate (x1*x2, (x,-oo, oo))
```
Did I do sth wrong? Because my math tells me it should return something C^infinity class

**Comment by jksuom** [comment]
The result will depend discontinuously on s1 and s2. The integrand is undefined if either of them is zero. The integral does not exist if `1/s1 + 1/s2` is nonpositive.

**Comment by karoldem** [comment]
> The result will depend discontinuously on s1 and s2. The integrand is undefined if either of them is zero. The integral does not exist if `1/s1 + 1/s2` is nonpositive.

damn, thanks
