### ISSUE TITLE
Is xreplace faster that subs?

### ISSUE THREAD

**Issue by proy87** [sympy/sympy#19707]
What is the preferred function to use, when I want to substitute `Symbol('a')` with `Symbol('b')`? Is `xreplace` faster than `subs`?
Do they perform it differently, i.e. can I get two different results from `e.xreplace({a:b})` and e.subs(a, b)?

**Comment by smichr** [comment]
xreplace will replace bounds symbols while subs should not so `Integral(x + 1, (x, 1, 3)).subs(x, y)` is unchanged. If you don't have to worry about bound symbols then `xreplace` should be faster.

**Comment by proy87** [comment]
@smichr, thank you.
