### ISSUE TITLE
fu.py contains outdated link for reference

### ISSUE THREAD

**Issue by sylee957** [sympy/sympy#19701]
http://rfdz.ph-noe.ac.at/fileadmin/Mathematik_Uploads/ACDCA/DESTIME2006/DES_contribs/Fu/simplification.pdf had gone.

Maybe it can be replaced by http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.657.2478&rep=rep1&type=pdf

**Comment by smichr** [comment]
That would be better than https://web.archive.org/web/20180721233609/http://rfdz.ph-noe.ac.at/fileadmin/Mathematik_Uploads/ACDCA/DESTIME2006/DES_contribs/Fu/simplification.pdf
