### ISSUE TITLE
[GSoC][Discussion] Matrix Distributions

### ISSUE THREAD

**Issue by Smit-create** [sympy/sympy#19723]
### Proposal
For adding new matrix distributions in `sympy.stats`, I think it probably can be constructed with `random_matrix_models.py`(to avoid creating new Random Symbol) for them, some of the examples of Matrix distributions are [Wishart](https://en.wikipedia.org/wiki/Wishart_distribution), [MatrixGamma](https://en.wikipedia.org/wiki/Matrix_gamma_distribution), [Normal-Wishart](https://en.wikipedia.org/wiki/Normal-Wishart_distribution), etc, It is because
1.  The current `JointRandomSymbol` is not a subclass of `MatrixSymbol` and so doesn't have a `shape` as its attribute,

2.  The `pdf` method of current Joint Distributions are defined like
https://github.com/sympy/sympy/blob/1f7cbeee19200aac259f4ffb8ec208b9b77fd5cf/sympy/stats/joint_rv_types.py#L146-L153
Suppose `X = MatrixGamma('X',1,2,[[1,0], [0,1]]))`
So, makes it difficult to handle queries if we have `density(X)([[1,2],[2,1]])` and `density(X)(T)` (`T` is a `MatrixSymbol`) as the second one should also be supported IMO. If we handle it some way, then it might raise errors for functions like `marginal_distribution`, `expectation` etc.

So, it should be implemented under `random_matrix_models.py`
ping @czgdp1807 @Upabjojr

**Comment by czgdp1807** [comment]
Can you suggest an example problem from some mathematics documents which uses matrix distributions?

**Comment by Upabjojr** [comment]
If you replace `ImmutableMatrix` with `.as_immutable()`... does that method exist in matrix expressions?

**Comment by Upabjojr** [comment]
Ideally the code should be written once and should work with both implicit-element and explicit-element matrices.

**Comment by Smit-create** [comment]
> Can you suggest an example problem from some mathematics documents which uses matrix distributions?

I haven't got many resources for this but, by googling I get a few from [wolfram](https://reference.wolfram.com/language/guide/MatrixDistributions.html) which shows that they can be extended further in `random_matrix_models.py` as a few of the examples there are already present in the file and we could add some of the remaining ones. 
Also, [this](https://encyclopediaofmath.org/wiki/Matrix_variate_distribution) gives some basic examples and definitions of Matrix Distributions

> Ideally the code should be written once and should work with both implicit-element and explicit-element matrices.

I actually think that they should be a part of `random_matrix_models.py` and not Joint Distributions as I noticed some difference in the pdf of [MatrixNormal Distribution](https://encyclopediaofmath.org/wiki/Matrix_variate_distribution){Matrix Dist.} and [Multivariate Normal Distribution](https://en.wikipedia.org/wiki/Multivariate_normal_distribution){Joint Dist.}
