### ISSUE TITLE
Limit with negative base

### ISSUE THREAD

**Issue by proy87** [sympy/sympy#19739]
`(-1/4)**x` as `x->oo`
Wolframalpha gives `0`, sympy raises `NotImplementedError: Result depends on the sign of sign(-log(4) + I*pi)`.
Why is that and what is the correct behavior?

**Comment by sachin-4099** [comment]
On current master:
```
In [6]: y
Out[6]:
    x
-1/4

In [7]: limit(y, x, oo)
Out[7]: 0
```

Can you mention which sympy version are you using?

**Comment by aaryandewan** [comment]
> On current master:
> 
> ```
> In [6]: y
> Out[6]:
>     x
> -1/4
> 
> In [7]: limit(y, x, oo)
> Out[7]: 0
> ```
> 
> Can you mention which sympy version are you using?

I'm getting the same error in version 1.4

**Comment by sachin-4099** [comment]
Nothing much can be done since SymPy 1.6.1 is already released. Hopefully, the correct result will be produced in the upcoming versions.

**Comment by sachin-4099** [comment]
This issue only needs a test in order to be closed.

**Comment by aaryandewan** [comment]
@sachin-4099 I'd like to add a test for this. Can you please guide a me a bit? For which version exactly are going to add a test?

**Comment by sachin-4099** [comment]
You will have to add the test to series/test_limits.py file present in the current codebase.

**Comment by aaryandewan** [comment]
@sachin-4099 I have added the test. Do I also have to make changes to some other files as well? (like docs/realease/notes...) Or can I open a pull request?

**Comment by sachin-4099** [comment]
Just open a pull request.

**Comment by Goku2699** [comment]
@sachin-4099 is the issue resolved or should I give it a try?

**Comment by sachin-4099** [comment]
> @sachin-4099 is the issue resolved or should I give it a try?

The above issue is resolved and a PR to add the required testcase has already been done.
