### ISSUE TITLE
Remove python2 compatiblity support from LaTeX parser

### ISSUE THREAD

**Issue by sylee957** [sympy/sympy#19751]
https://github.com/sympy/sympy/blob/1eaefeb714cc05d87ea2f938813e5e859caa2b32/sympy/parsing/latex/LaTeX.g4#L18

I've tried several attempts to drop the line and rebuild the parser, but had not been successful due to some errors.

**Comment by aleriv-umich** [comment]
what did you call to rebuild the parser?  And did you replace Python2 with anything?
