### ISSUE TITLE
Adding test cases for systems of ODEs

### ISSUE THREAD

**Issue by mijo2** [sympy/sympy#19763]
PR [#11510](https://github.com/sympy/sympy/pull/11510/files) introduced some method to fixing the problems that the `dsolve` faced to solve systems of ODEs.  But, it has already been solved by the solvers added in the past few months. 

We want to remove the PR but there are some test cases added in the PR that can be used to check the current functionality added. We want test cases added in `test_linear_2eq_order1` and `test_linear_2eq_order1_type2` to be added in `test_systems.py`. But, adding those test cases should be done in the following manner:
1. Copy the equation in appropriate type(information about types given below)
2. Use `dsolve` to get the solution. 
3. Copy that solution in `test_systems.py` and verify the solution as done for the other test cases in `test_systems.py`

Now, about the types, there are 4 types of linear first order systems of ODEs. Type 1: Linear first order constant coefficient homogeneous, Type 2: Linear first order constant coefficient non-homogeneous, Type 3: Linear first order non-constant coefficient homogeneous and Type 4: Linear first order non-constant coefficient non-homogeneous. Add the test cases into appropriate functions in `test_systems.py`. Test cases that are of Type 2, 3, or 4(if any) have to be added only, test cases of type 1 have already been added into the master. 

I will demonstrate an example of how to do this for a single test case:
```
eq = (Eq(diff(x(t),t), 5*t*x(t) + 2*y(t)), Eq(diff(y(t),t), 2*x(t) + 5*t*y(t)))
```
Its easy to see that this system is of type 3. Now, in `test_sysode_linear_neq_order1_type3`, we have already defined `x` and `y` as symbols instead of functions, so we change the above system by using `f` instead of `x` and `g` instead of `y`.

```
eq = (Eq(diff(f(t),t), 5*t*f(t) + 2*g(t)), Eq(diff(g(t),t), 2*f(t) + 5*t*g(t)))
```

Now, we will get the solution for this system using `dsolve`
```
In [30]: dsolve(eq)                                                                                                                                                                                         
Out[30]: 
[Eq(f(t), (-C1/2 + C2/2)*exp(5*t**2/2 - 2*t) + (C1/2 + C2/2)*exp(5*t**2/2 + 2*t)),
 Eq(g(t), (C1/2 - C2/2)*exp(5*t**2/2 - 2*t) + (C1/2 + C2/2)*exp(5*t**2/2 + 2*t))]
```
We got the solution, now to add a test case, we will write the below for adding the test case in `test_sysode_linear_neq_order1_type3`:
```
eqs8 = (Eq(diff(f(t),t), 5*t*f(t) + 2*g(t)), Eq(diff(g(t),t), 2*f(t) + 5*t*g(t)))
sol8 = [Eq(f(t), (-C1/2 + C2/2)*exp(5*t**2/2 - 2*t) + (C1/2 + C2/2)*exp(5*t**2/2 + 2*t)),
        Eq(g(t), (C1/2 - C2/2)*exp(5*t**2/2 - 2*t) + (C1/2 + C2/2)*exp(5*t**2/2 + 2*t))]
assert dsolve(eqs8) == sol8
assert checksysodesol(eqs8, sol8) == (True, [0, 0])
```

If there are rationals like `2/3` in the solution, then those have to be replaced by `Rational(2, 3)`.
This has to be done for every test case which fits our criteria. Submit a PR by adding the test cases into appropriate functions in `test_systems.py`.

**Comment by mioppolo** [comment]
I'll have a crack at this PR if it's still open once I've had a read throught the wiki.

**Comment by mijo2** [comment]
@aaryandewan That function is in the PR that I have mentioned. In that PR, check the file `sympy/solvers/tests/test_ode.py`

**Comment by dsaw** [comment]
I checked a couple of equations in the assert function given in the PR. It seems the `dsolve` method does not completely solve them with loads of terms & unevaluated integrals.
```
>>> eq2 = (Eq(diff(x(t), t), k1), Eq(diff(y(t), t), k2))
>>> dsolve(eq2)
[Eq(x(t), C1 + Integral(k1, t)), Eq(y(t), C2 + Integral(k2, t))]
>>> dsolve(eq10)
[Eq(x(t), -sqrt(6)*C1*exp(-sqrt(6)*t + 3*t)/2 - C1*exp(-sqrt(6)*t + 3*t) - C2*exp(sqrt(6)*t + 3*t) + sqrt(6)*C2*exp(sqrt(6)*t + 3*t)/2 - sqrt(6)*exp(-sqrt(6)*t + 3*t)*Integral(-16*sqrt(6)*exp(-3*t + sqrt(6)*t)/3 + 23*exp(-3*t + sqrt(6)*t)/2, t)/2 - exp(-sqrt(6)*t + 3*t)*Integral(-16*sqrt(6)*exp(-3*t + sqrt(6)*t)/3 + 23*exp(-3*t + sqrt(6)*t)/2, t) - exp(sqrt(6)*t + 3*t)*Integral(23*exp(-3*t - sqrt(6)*t)/2 + 16*sqrt(6)*exp(-3*t - sqrt(6)*t)/3, t) + sqrt(6)*exp(sqrt(6)*t + 3*t)*Integral(23*exp(-3*t - sqrt(6)*t)/2 + 16*sqrt(6)*exp(-3*t - sqrt(6)*t)/3, t)/2), Eq(y(t), C1*exp(-sqrt(6)*t + 3*t) + C2*exp(sqrt(6)*t + 3*t) + exp(-sqrt(6)*t + 3*t)*Integral(-16*sqrt(6)*exp(-3*t + sqrt(6)*t)/3 + 23*exp(-3*t + sqrt(6)*t)/2, t) + exp(sqrt(6)*t + 3*t)*Integral(23*exp(-3*t - sqrt(6)*t)/2 + 16*sqrt(6)*exp(-3*t - sqrt(6)*t)/3, t))]
```
The solution on Wolfram Alpha to the last one, which is considerably shorter.
![wolframalphasol](https://user-images.githubusercontent.com/5353891/88477262-2d2baf80-cf5c-11ea-8c42-928a91af0971.PNG)
I think the function was updated after that. Probably we need different test cases?

**Comment by mijo2** [comment]
Well type2 and type4 system of ODEs have unevaluated integrals and if a user wishes to evaluate it, then they can do so by calling `doit` in each of the equations. This was decided when solvers for these types were created for better validity of the solutions and this might be changed in future. For now, you just paste the new solution you are getting from `dsolve` for all of these test cases.

**Comment by dsaw** [comment]
Have added pr for the test cases #19888

**Comment by sidhu1012** [comment]
How many test cases are remaining? I'm up for them

**Comment by suryam35** [comment]
I would like to work on this issue by adding test cases to type3 , type4.
How many test cases should I add for each of them ?

**Comment by kunalsingh2002** [comment]
I would like to work on this issue by adding test cases to type 3 and 4 , how many test cases should I add ?

**Comment by oscarbenjamin** [comment]
There already is a PR #19888. It's not quite right though because I think that the output of `dsolve` has changed since the PR was written and also it has merge conflicts. I suggest starting from that PR (reusing the original commits) and then resolving the merge conflicts and updating any tests that no longer pass if the output from dsolve has changed.

**Comment by suryam35** [comment]
I did not quite understand what you said over there. I am not able to understand how to use the original commits and what else to do with it. Could you please explain in detail

**Comment by suryam35** [comment]
On adding test case of type 3 I encountered the following error in which dsolve does not simplify much the equation but on printing the solution it gets simplified and pushes the '-' sign inside and thus raises an assertion error.
dsolve solution : [Eq(f(t), -**(C1/2 - C2/2)***exp(5*t**2/2 - 2*t) + (C1/2 + C2/2)*exp(5*t**2/2 + 2*t)), Eq(h(t), (C1/2 - C2/2)*exp(5*t**2/2 - 2*t) + (C1/2 + C2/2)*exp(5*t**2/2 + 2*t))]

Simplified solution : [Eq(f(t), **(-C1/2 + C2/2)***exp(5*t**2/2 - 2*t) + (C1/2 + C2/2)*exp(5*t**2/2 + 2*t)), Eq(h(t), (C1/2 - C2/2)*exp(5*t**2/2 - 2*t) + (C1/2 + C2/2)*exp(5*t**2/2 + 2*t))]

**Comment by suryam35** [comment]
On adding test case of type 3 I encountered the following error in which dsolve does not simplify much the equation but on printing the solution it gets simplified and pushes the '-' sign inside and thus raises an assertion error.
dsolve solution : [Eq(f(t), **-(C1/2 - C2/2)**exp(5t2/2 - 2*t) + (C1/2 + C2/2)exp(5t2/2 + 2t)), Eq(h(t), (C1/2 - C2/2)exp(5t**2/2 - 2t) + (C1/2 + C2/2)exp(5t**2/2 + 2*t))]

Simplified solution : [Eq(f(t), **(-C1/2 + C2/2)**exp(5t2/2 - 2*t) + (C1/2 + C2/2)exp(5t2/2 + 2t)), Eq(h(t), (C1/2 - C2/2)exp(5t**2/2 - 2t) + (C1/2 + C2/2)exp(5t**2/2 + 2*t))]

**Comment by suryam35** [comment]
On adding test case of type 3 I encountered the following error in which dsolve does not simplify much the equation but on printing the solution it gets simplified and pushes the '-' sign inside and thus raises an assertion error.
dsolve solution : [Eq(f(t), _**-(C1/2 - C2/2)**_exp(5t2/2 - 2t) + (C1/2 + C2/2)exp(5t2/2 + 2t)), Eq(h(t), (C1/2 - C2/2)exp(5t2/2 - 2t) + (C1/2 + C2/2)exp(5t**2/2 + 2*t))]

Simplified solution : [Eq(f(t), _**(-C1/2 + C2/2)**_exp(5t2/2 - 2t) + (C1/2 + C2/2)exp(5t2/2 + 2t)), Eq(h(t), (C1/2 - C2/2)exp(5t2/2 - 2t) + (C1/2 + C2/2)exp(5t2/2 + 2t))]

**Comment by oscarbenjamin** [comment]
You might need to use `evaluate=False`:
```

In [1]: 2*(x + y)
Out[1]: 2⋅x + 2⋅y

In [2]: Mul(2, x+y, evaluate=False)
Out[2]: 2⋅(x + y)
```
