### ISSUE TITLE
stats: Should `P(X > 1, evaluate=False)` return `Probability(X > 1)` or unevaluated Integral?

### ISSUE THREAD

**Issue by Smit-create** [sympy/sympy#19798]
On current master, `P(X > 1, evaluate=False)` produces unevaluated Integral. However, according to the discussions on Gitter, it was suggested by @czgdp1807 that we should make `P(X > 1, evaluate=False)` to return a Symbolic probability object as `Probability(X > 1)`. Symbolic `Probability` class has been added with `doit` method recently and so, `P(X > 1, evaluate=True)` should return `Probability(X > 1).doit()`.
More clearly the current scenario is:
```py
In [1]: from sympy.stats import *

In [2]: X = Normal('X', 1, 2)

In [3]: P(X > 1, evaluate=False)
Out[3]:

∞
⌠
⎮             2
⎮     -(z - 1)
⎮     ──────────
⎮         8
⎮ √2⋅ℯ
⎮ ────────────── dz
⎮      4⋅√π
⌡
1

```
Proposal to change the behavior to:

```py
In [5]: P(X > 1, evaluate=False)
Out[5]: Probability(X > 1)
```
ping @czgdp1807 @Upabjojr

**Comment by Upabjojr** [comment]
What about:

1. `P(X > 1, evaluate=False)` ==> return `Probability` object,
2. `P(X > 1).doit(evaluate=False)` ==> return unevaluated integral.

**Comment by czgdp1807** [comment]
Agreed with @Upabjojr , seems like a good idea and will also help in making APIs unambiguous.

**Comment by Smit-create** [comment]
> `P(X > 1).doit(evaluate=False)` ==> return unevaluated integral.

Do you mean `Probability(X > 1).doit(evaluate=False)` ==> return unevaluated integral ?

**Comment by czgdp1807** [comment]
I think he meant to say what you are suggesting. What `doit` does is a different issue, what we need right now is `evaluate=False` to return `Probability(X > 1)`. Output of `doit` depends on how much the input can be processed before giving results and return type is variable so we cannot do much about it.

**Comment by Upabjojr** [comment]
Maybe we don't need to deal with `.doit()` at all. We already have `Probability(X > 1).rewrite(Integral)`... which is supposed to return the `Integral` object.

**Comment by Upabjojr** [comment]
Maybe `P(X > 1, evaluate=False)` should raise a warning about the change.

**Comment by Smit-create** [comment]
While working on `P` and `E`, I also see a similar problem with `density`. For example:
```py
In [1]: from sympy.stats import *

In [2]: X = Normal('X', 1, 2)

In [3]: Y = Normal('Y', 3, 4)

In [4]: density(X + Y, evaluate=False)(z)
Out[4]:
∞
⌠
⎮                 ∞

⎮                 ⌠
⎮                 ⎮              2
⎮              2  ⎮      -(X - 1)
⎮      -(Y - 3)   ⎮      ──────────
⎮      ────────── ⎮          8
⎮          32     ⎮  √2⋅ℯ          ⋅δ(X + Y - z)
⎮  √2⋅ℯ          ⋅⎮  ─────────────────────────── dX
⎮                 ⎮              4⋅√π
⎮                 ⌡
⎮                 -∞
⎮  ──────────────────────────────────────────────── dY
⎮                        8⋅√π
⌡
-∞

```
Another problem is that the `class Density` is present in `sympy.stats.rv` which should be moved to `symbolic_probability.py` as well as it should be added with rewrite(Integral) methods. 
Should I make the similar change for `Density` too in my PR #19819 ?

**Comment by Upabjojr** [comment]
If you are going to apply this logic to the density class, so maybe we need the `CDF` class as well.
