### ISSUE TITLE
wrong result in limit operation

### ISSUE THREAD

**Issue by p506738532** [sympy/sympy#19801]
```
In[2]:
x,y=symbols("x y")
limit((1/2)**x,x,oo,'-')
Out[2]:
0
```
I expect result of it is 'oo',I want to konw if I'm wrong or the code.

**Comment by sylee957** [comment]
I don't think that the result is wrong mathematically because you have given x to approach infinity. Did you mean that x should approach minus infinity?

**Comment by p506738532** [comment]
@sylee957 thanks for your reply. i mean when x approach minus nifinity, the result is oo. in anoter words, limit((1/2)**x,x,oo,'-')=oo, What is the  matter with me?

**Comment by sylee957** [comment]
You shouldn’t supply as dir=‘-‘, but use
limit((1/2)**x,x,-oo)
For points at infinity, there are only one directions, so we don’t encode dir

**Comment by p506738532** [comment]
@sylee957 thank you very much,i did't know how to use 'limit' correctly
