### ISSUE TITLE
Enhancement: Handle SymPy objects in NumPy 

### ISSUE THREAD

**Issue by Yukti-09** [sympy/sympy#19817]
import numpy as np
from sympy import *
a = symbols(a)
b = symbols(b)
c = symbols(c)
x = [a b c]
print(np.linalg.norm(x))

I should get something like sqrt(a^2+b^2+c^2)
Instead, I get SyntaxError: invalid syntax.

**Comment by Yukti-09** [comment]
https://github.com/numpy/numpy/issues/16927#issue-663490288 
This could prove to be beneficial.

**Comment by oscarbenjamin** [comment]
The syntax error is because your code is not valid Python code. You can write this like:
```python
import numpy as np
from sympy import *
a = symbols('a')
b = symbols('b')
c = symbols('c')
x = [a, b, c]
print(np.linalg.norm(x))
```
With that you will get an error from numpy:
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
AttributeError: 'Add' object has no attribute 'sqrt'

The above exception was the direct cause of the following exception:

TypeError                                 Traceback (most recent call last)
~/current/sympy/sympy/g.py in <module>
      5 c = symbols('c')
      6 x = [a, b, c]
----> 7 print(np.linalg.norm(x))

<__array_function__ internals> in norm(*args, **kwargs)

~/current/sympy/38venv/lib/python3.8/site-packages/numpy/linalg/linalg.py in norm(x, ord, axis, keepdims)
   2475             else:
   2476                 sqnorm = dot(x, x)
-> 2477             ret = sqrt(sqnorm)
   2478             if keepdims:
   2479                 ret = ret.reshape(ndim*[1])

TypeError: loop of ufunc does not support argument 0 of type Add which has no callable sqrt method
```
This suggests that numpy expects a `sqrt` method. Really though I don't think that you should try to use numpy functions like this with sympy objects. Instead using sympy:
```julia
In [5]: M = Matrix([a, b, c])

In [6]: M
Out[6]: 
Matrix([
[a],
[b],
[c]])

In [7]: M.norm()
Out[7]: 
   ____________________
  ╱    2      2      2 
╲╱  │a│  + │b│  + │c│ 
```

**Comment by Yukti-09** [comment]
But, 
import numpy as np
from sympy import *
a = symbols('a')
b = symbols('b')
c = symbols('c')
x = Matrix([a*cos(b),a*sin(b),c])
print(x.norm())

We know that the output should be √(a^2+c^2)
I'm getting:
sqrt(Abs(c)**2 + Abs(a*sin(b))**2 + Abs(a*cos(b))**2)
So the main idea was to create a function which could evaluate sin^2x+cos^2x=1

**Comment by Yukti-09** [comment]
Thanks!
