### ISSUE TITLE
ENH: Handle trignometry identities in norm

### ISSUE THREAD

**Issue by Yukti-09** [sympy/sympy#19827]
import numpy as np
from sympy import *
a = symbols('a')
b = symbols('b')
c = symbols('c')
x = Matrix([acos(b),asin(b),c])
print(x.norm())

Gives an output
sqrt(Abs(c)**2 + Abs(asin(b))**2 + Abs(acos(b))**2)
Output we are supposed to get sqrt(Abs(c)**2+Abs(a)**2)

https://github.com/numpy/numpy/issues/16929#issue-664159890

@oscarbenjamin

**Comment by eric-wieser** [comment]
Why would you expect `a` in the output if your input does not use it?

**Comment by Yukti-09** [comment]
It is a Pythagorean identity
sin2(t) + cos2(t) = 1
(Read as sin square t+cos square t is equal to 1).
Similarly, when we take a**2(Read as a square) common from
Abs(asin(b))**2 + Abs(acos(b))**2
We should be left with a**2

It would be great if we could incorporate this and other Pythagorean identities.

**Comment by eric-wieser** [comment]
You realize that `acos(b)` is very different from `a * cos(b)`, right?

**Comment by Yukti-09** [comment]
I'm sorry, was a typing mistake. However, I did mean a * cos(b)

**Comment by Yukti-09** [comment]
CODE:
import numpy as np
from sympy import *
a = symbols('a')
b = symbols('b')
c = symbols('c')
x = Matrix([a*cos(b),a*sin(b),c])
print(x.norm())
OUTPUT:
sqrt(Abs(c)**2 + Abs(a*sin(b))**2 + Abs(a*cos(b))**2)
EXPECTED OUTPUT:
sqrt(Abs(c)**2 + Abs(a)**2)

**Comment by eric-wieser** [comment]
What do you get if you call `.simplify()`?

**Comment by Yukti-09** [comment]
import numpy as np
from sympy import *
a = symbols('a')
b = symbols('b')
c = symbols('c')
x = Matrix([a * cos(b),a * sin(b),c])
print(x.norm().simplify())
OUTPUT:
sqrt(Abs(c)**2 + Abs(a * sin(b))**2 + Abs(a * cos(b))**2)

**Comment by eric-wieser** [comment]
And what if you tell sympy that a and b are real?

**Comment by eric-wieser** [comment]
That fixes the problem:
```python
In [2]: from sympy import *
   ...: a = symbols('a', real=True)
   ...: b = symbols('b', real=True)
   ...: c = symbols('c', real=True)

In [4]: x = Matrix([a*cos(b),a*sin(b),c])

In [5]: x.norm()
Out[5]: sqrt(a**2*sin(b)**2 + a**2*cos(b)**2 + c**2)

In [6]: x.norm().simplify()
Out[6]: sqrt(a**2 + c**2)
```

**Comment by eric-wieser** [comment]
If you were deliberately working with complex numbers, then gh-19830 tracks the underlying issue. It sounds like you were not though, as the complex-valued solution is `sqrt(Abs(c)**2 + Abs(a)**2*cos(2*Im(b)))`
