### ISSUE TITLE
Simple integral hangs

### ISSUE THREAD

**Issue by proy87** [sympy/sympy#19833]
`atan(x)/(x^2+1),(x,7,oo)`

**Comment by Yukti-09** [comment]
I ran the code:
```
from sympy import *
x = symbols('x')
exp = atan(x)/(x**2+1)
h = integrate(exp, (x,7,oo))
print(h.simplify())
```
OUTPUT:
```
-atan(7)**2/2 + pi**2/8
```
It didn't seem to hang for me.
@eric-wieser

**Comment by oscarbenjamin** [comment]
Yes, the integral seems to work fine for me on master and in 1.6 and 1.5. The result also matches what I get from numerical integration.

@proy87 what version of sympy are you using?

Could you show the exact code to reproduce the problem?

**Comment by proy87** [comment]
Strange. It works.
