### ISSUE TITLE
Should perfect_power use is_square instead simple modulo check?

### ISSUE THREAD

**Issue by sethtroisi** [sympy/sympy#19843]
`perfect_power` uses `n % 10 in [2,3,7,8]`[[1]](https://github.com/sympy/sympy/blob/58e1e9abade7c38c66871fd06bf76ebac8c1df78/sympy/ntheory/factor_.py#L464-L477) as a prefilter to determine if N can be square this is a less complete check than the one present in `is_square` [[2]](https://github.com/sympy/sympy/blob/58e1e9abade7c38c66871fd06bf76ebac8c1df78/sympy/ntheory/primetest.py#L88-L94)

It seems like
```
    not_square = n % 10 in [2, 3, 7, 8]  # squares cannot end in 2, 3, 7, 8
    min_possible = 2 + not_square
```
could be changed to
```
    not_square = is_square(n)
    min_possible = 2 + not_square
```
My thought is

case 1: `n is not a square`
case 1a:  `not_square == True`,  `is_square` will filter n in roughly the same speed; maybe even faster because it avoids modulo and list check with multiplications.
case 2b: `not_square == False`, `is_square` has a better change to filter n, otherwise both call `integer_nthroot(n,2)`
case 2: `n is a square`: new code performs extra filter checks (should be very fast compared to eventual `integer_nthroot(n, 2)`)

Happy to write this up as a PR if someone agrees or proposes a way I can benchmark.

**Comment by oscarbenjamin** [comment]
I don't know this code so well but what you say seems reasonable. I guess you could time it by timing the effect on calling perfect_power for a range of small integers and a range of large integers.

**Comment by sethtroisi** [comment]
I started looking at this but the change grew out of scope as it needs to handle `big=False` and `candidates`...
