### ISSUE TITLE
Solving inequality using solveset and solve

### ISSUE THREAD

**Issue by friyaz** [sympy/sympy#19840]
Can we solve inequalitites of type `!=` using solveset.
```python
from sympy import *
from sympy.abc import x
solveset(x != 0, x, S.Integers)
# -> Integers
```
The result according to me should be:
```python
Complement(Integers, FiniteSet(0))
```
Similarly, using solve
```python
>>> solve(x != 0, x)
[]
>>> solve(x > 0 or x < 0, x)
TypeError: cannot determine truth value of Relational
```
Maybe there is a simple way to do this which I cannot find.

**Comment by Upabjojr** [comment]
`Unequality(x, 0)`

or

`Not(Eq(x, 0))`

**Comment by Upabjojr** [comment]
Don't use `or`... it's a Python operator that always returns a boolean, not a logical expression. Use `|` instead, or the `Or( ... )` class in SymPy.
