### ISSUE TITLE
pi*cos(n), pi is not extracted

### ISSUE THREAD

**Issue by proy87** [sympy/sympy#19850]
Neither `as_coeff_mul`, nor `as_coeff_Mul` can extract `pi`.

**Comment by Raghibshams456** [comment]
hey @proy87 can u explain..please..

**Comment by proy87** [comment]
`pi*cos(n).as_coeff_mul()` return `(1, (pi*cos(n),))`, not `(pi, (cos(n),))`

**Comment by oscarbenjamin** [comment]
Both methods are intended to extract Rational coefficients only by default. You can inform `as_coeff_mul` that e.g. anything not containing `n` should be considered part of the coefficient:
```
In [8]: (pi*cos(n)).as_coeff_mul(n)                                                                                               
Out[8]: (π, (cos(n),))
```

**Comment by oscarbenjamin** [comment]
I'm closing this since it is by design.
