### ISSUE TITLE
Bug in limit_seq

### ISSUE THREAD

**Issue by proy87** [sympy/sympy#19868]
`limit_seq(1/gamma(n+S.One/2), n)` gives `oo`, but the correct answer is `0`.

**Comment by sachin-4099** [comment]
On the current master:
```
In [1]: limit_seq(1/gamma(n+S.One/2), n)
Out[1]: 0
```

This issues only needs a test in order to be closed.

**Comment by tashakim** [comment]
I added a test for this issue, wondering if it looks ok?
