### ISSUE TITLE
Question/Feature request -- Discriminant of equation

### ISSUE THREAD

**Issue by abhaydhiman** [sympy/sympy#19884]
`solveset(Eq(3*x**3 + 6*x**2 - 9*x, 0), x)` This can give the roots for the equation but what if any user just wants to know that is its real roots exists or not or the roots are equal or not. This feature can be added to give just a general idea of roots for any equation. 
The discriminant of a polynomial is a function of its coefficients which gives an idea about the nature of its roots. For a quadratic polynomial a*x^2 + b*x + c, the formula of discriminant is given by the following equation:
`D = b^2 – 4*a*c`

for more info:-
    link1:- https://www.bbc.co.uk/bitesize/guides/zcwhjty/revision/1

   link2(online discriminant calculator):-  https://www.solumaths.com/en/math-apps/calc-online/discriminant#:~:text=%20Calculate%20the%20discriminant%20of%20a%20polynomial%20allows,the%20equation%20has%20two%20distinct%20roots.%20More%20

**Comment by jksuom** [comment]
There is a function `discriminant` for computing the discriminant of a polynomial. The number of real roots is given by `count_roots`,
```
In [1]: e = 3*x**3 + 6*x**2 - 9*x

In [2]: discriminant(e)
Out[2]: 11664

In [3]: count_roots(e)
Out[3]: 3
```

**Comment by abhaydhiman** [comment]
ok, I didn't know this before.
