### ISSUE TITLE
Wrong result for sqrtdenest

### ISSUE THREAD

**Issue by sylee957** [sympy/sympy#19914]
`sqrtdenest(sqrt(-8-sqrt(63)))`  gives `-3*sqrt(2)*I/2 + sqrt(14)*I/2`, but they are numerically different because
```
-3*sqrt(2)*I/2 + sqrt(14)*I/2 -> -0.250491650172672*I
sqrt(-8-sqrt(63)) -> 3.99214903694661*I```

**Comment by coproc** [comment]
The correct solution should be one of `+/-(3*sqrt(2)*I/2 + sqrt(14)*I/2)`. The problem is in `_sqrt_numeric_denest` if `vad < 0`. Then also `vad1 = 1/vad < 0`. `sqrt(vad)*sqrt(vad1)` should cancel to 1, but is converted to `(I*sqrt(|vad|))*(I*sqrt(|vad1|) = I**2 = -1`. To fix this
````python
    return (sqrt(vad/2) + sign(b)*sqrt((b**2*r*vad1/2).expand())).expand()
````
could be replaced by 
````python
    s1,s2 = sign(vad),sign(b)
    if sign(vad) == sign(b) == -1:
        s1 = s2 = 1
    return (s1*sqrt(vad/2) + s2*sqrt((b**2*r*vad1/2).expand())).expand()
````

**Comment by sylee957** [comment]
I don't think that any formula involving sign is easy to understand or modify, so I'd try to avoid using them if I can figure out

**Comment by coproc** [comment]
> I don't think that any formula involving sign is easy to understand or modify, so I'd try to avoid using them if I can figure out
good point! I was actually thinking already into the same direction. This formula seems to work:

```python
    sqrt(vad/2) + b*sqrt(r)/sqrt(2*vad)
```

Then the last lines of `_sqrt_numeric_denest` would look like this:
```python
    if sqrt_depth(vad) < depthr + 1 or (vad**2).is_Rational:
        return (sqrt(vad/2) + b*radsimp(sqrt(r)/sqrt(2*vad))).expand()
```

**Comment by sylee957** [comment]
Unfortunately, this doesn't look like working
```
from sympy import *

for a in range(-10, 10):
    for b in range(-10, 10):
        for r in range(-10, 10):
            expr = sqrt(a + b*sqrt(r))
            denested = sqrtdenest(expr)
            if expr != denested:
                diff = abs(expr.evalf() - denested.evalf())
                if diff > 0.00001:
                    print(a, b, r, diff)
```

The result I've arrived is
```
    d = sqrt(d2)
    s = 2*(a + d)
    if sqrt_depth(s) < sqrt_depth(r) + 1 or (s**2).is_Rational:
        s1, s2 = sign(s), sign(b)
        if s1 == s2 == -1:
            s1 = 1
        res = s1 * (s + 2 * b * sqrt(r)) / (2 * sqrt(s))
        return res.expand()
```
which uses similar formula as the original article, but still with the sign

**Comment by coproc** [comment]
> Unfortunately, this doesn't look like working

This is because of the overall sign. Currently also `expr == -denested` is allowed.

Your code snipped looks good. May I suggest the following simplification:

```python
    d = sqrt(d2)
    s = a + d
    if sqrt_depth(s) < sqrt_depth(r) + 1 or (s**2).is_Rational:
        s1, s2 = sign(s), sign(b)
        if s1 == s2 == -1:
            s1 = 1
        res = s1 * (s + b * sqrt(r)) / sqrt(2 * s)
        return res.expand()
```

**Comment by coproc** [comment]
And I guess the call of `radsimp` should be added again:
```python
        res = s1 * (s + b * sqrt(r)) * radsimp(1 / sqrt(2 * s))
```
