### ISSUE TITLE
Structural equality for numbers (Rational and Float)

### ISSUE THREAD

**Issue by Davide-sd** [sympy/sympy#19915]
I'm trying to understand what's triggering [this issue](https://github.com/sympy/sympy/issues/19774), which could be related to [this question](https://groups.google.com/g/sympy/c/8uSZNb6-z54).

Following the trace, I realized that `Rational` and `Float` are not implementing a proper structural equality by overloading `__eq__`. In fact:

```
(S(5) / 2) == S(2.5)
# True
```

**Comment by oscarbenjamin** [comment]
There are some longstanding issues about this

**Comment by Davide-sd** [comment]
Yeah, I can imagine! :)

I'm not yet sure about this, but I believe the following incorrect result may be a manifestation of this actual issue:

```
expr1 = exp(S(5) / 2 * x)
expr2 = exp(2.5 * x)
expr1.equals(expr2)
# False
```

Basically, we can't currently trust the results of equals() when comparing rationals with floats...

**Comment by oscarbenjamin** [comment]
The key question is whether we have to be consistent with unsympified types:
```
In [5]: S(1) == 1 == 1.0 == S(1.0)                                                                                                             
Out[5]: True
```
At some point I thought that consistency was maybe important to maintain transitivity of `__eq__` even when mixing sympy and non-sympy objects. I'm wondering whether it's better just to ditch that and make Float/Rational compare unequal. They already do when used as part of any larger object:
```
In [7]: exp(1.0*x) == exp(1*x)                                                                                                                 
Out[7]: False

In [8]: 1.0*x == 1*x                                                                                                                           
Out[8]: False

In [9]: S(1.0) == S(1)                                                                                                                         
Out[9]: True
```

**Comment by Davide-sd** [comment]
May I ask an example of mixing sympy and non-sympy objects?

**Comment by oscarbenjamin** [comment]
You can mix sympy and non-sympy objects like e.g.:
```
In [10]: x = Symbol('x')                                                                                                                       

In [11]: 2*x                                                                                                                                   
Out[11]: 2⋅x
```
Here `2` gives a Python `int` rather than a sympy `Integer`. This is handled by "sympifying" the int to an Integer:
```
In [13]: srepr(2*x)                                                                                                                            
Out[13]: "Mul(Integer(2), Symbol('x'))"
```
The reason we have to be careful about `==` for structural equality is because the behaviour of `==` is baked into to Python's built in types such as `set` and `dict`:
```julia
In [14]: x = 1                                                                                                                                 

In [15]: y = 1.0                                                                                                                               

In [16]: x == y                                                                                                                                
Out[16]: True

In [17]: {x, y}                                                                                                                                
Out[17]: {1}

In [18]: {y, x}                                                                                                                                
Out[18]: {1.0}
```
A `set` can only contain one of `x` or `y` if `x == y`. In SymPy that would be mostly unacceptable so we have
```julia
In [19]: x = exp(2*t)                                                                                                                          

In [20]: y = exp(2.0*t)                                                                                                                        

In [21]: x == y                                                                                                                                
Out[21]: False

In [22]: {x, y}                                                                                                                                
Out[22]: 
⎧ 2.0⋅t   2⋅t⎫
⎨ℯ     , ℯ   ⎬
⎩            ⎭

In [23]: {y, x}                                                                                                                                
Out[23]: 
⎧ 2.0⋅t   2⋅t⎫
⎨ℯ     , ℯ   ⎬
⎩            ⎭
```
That doesn't work with a plain Float though:
```
In [24]: x = Integer(2)                                                                                                                        

In [25]: y = Float(2)                                                                                                                          

In [26]: x == y                                                                                                                                
Out[26]: True
```
It works with `sets` though because the hashes are broken:
```
In [27]: {x, y}                                                                                                                                
Out[27]: {2.0, 2}

In [28]: {y, x}                                                                                                                                
Out[28]: {2.0, 2}
```
If we fixed the hashes then it wouldn't be possible to store those as two separate elements in the set which would create all kinds of problems.

We could solve that by having `Integer(2) != Float(2)` but then it would break transitivity in
```julia
In [29]: Integer(2) == 2 == 2.0 == Float(2.0)                                                                                                  
Out[29]: True
```
I am wondering whether the loss of transitivity actually matters though especially given that it only applies when mixing sympy and non-sympy types. There is no good reason *within* sympy for doing that e.g. like:
```julia
In [34]: x = Integer(2)                                                                                                                        

In [35]: y = 2                                                                                                                                 

In [36]: {x, y}                                                                                                                                
Out[36]: {2}

In [37]: {y, x}                                                                                                                                
Out[37]: {2}

In [38]: {x, y}.pop().args                                                                                                                     
Out[38]: ()

In [39]: {y, x}.pop().args                                                                                                                     
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-39-ac0acc52a727> in <module>
----> 1 {y, x}.pop().args

AttributeError: 'int' object has no attribute 'args'
```
I think this kind of problem would only come up if there was a bug that mixed sympified and unsympified objects somewhere.

**Comment by Davide-sd** [comment]
Thanks for the time invested to write that answer! :+1: 

If I understand correctly, the fact that `Float(2) == Integer(2) # True` was implemented to mimic Python behavior. In Python, if two objects are equal then their hashes are very likely to be the same (right?)

> It works with `sets` though because the hashes are broken:

I'm not sure I understand your sentence... I would state that within Sympy there are inconsistencies between hashes and equality, implemented to mimic Python behavior. So, even though `Float(2) == Integer(2) # True`, it happens `hash(Float(2)) != hash(Integer(2))` because of their different hashable contents.

> I think this kind of problem would only come up if there was a bug that mixed sympified and unsympified objects somewhere.

So, the current situation is that there are parts of Sympy that expects `==` to perform actual structural equality, and likely older parts of the codebase that expects "a Pythonic behavior".

**Comment by oscarbenjamin** [comment]
The hash invariant is currently broken in sympy:
https://www.asmeurer.com/blog/posts/what-happens-when-you-mess-with-hashing-in-python/

The invariant is that if `a == b` then `hash(a) == hash(b)`. Without that there is the possibility for dicts and sets to become non-deterministic.

SymPy's Float violates this:
```julia
In [3]: x = 1                                                                                                                                  

In [4]: y = 1.0                                                                                                                                

In [5]: z = Float(1.0)                                                                                                                         

In [6]: x == y == z                                                                                                                            
Out[6]: True

In [7]: hash(x)                                                                                                                                
Out[7]: 1

In [8]: hash(y)                                                                                                                                
Out[8]: 1

In [9]: hash(z)                                                                                                                                
Out[9]: 3842495219584272973
```
Fixing that according to the current behaviour of `==` would then mean that sets containing Float could not contain both `Integer(1)` and `Float(1)`.

I think now that the proper fix is actually changing `==` so that `Integer(1) != Float(1)` since the current behaviour does not match sympy's definition of "structural equality". The implication of this change is that transitivity of `==` would be broken when mixing int, float, Integer and Float but I think that's reasonable.

Note that full proper structural equality would require that Floats are only equal when they have the same precision:
```julia
In [17]: x = Float(3, 1)                                                                                                                       

In [18]: y = Float(3, 10)                                                                                                                      

In [19]: x                                                                                                                                     
Out[19]: 3.

In [20]: y                                                                                                                                     
Out[20]: 3.000000000

In [21]: x == y                                                                                                                                
Out[21]: True

In [22]: x._prec                                                                                                                               
Out[22]: 7

In [23]: y._prec                                                                                                                               
Out[23]: 37
```
If we *really* used structural equality for `Float` then we also need `Out[21]` to be `False`.
