### ISSUE TITLE
Feature Request -- Showing main steps while performing computations.

### ISSUE THREAD

**Issue by abhaydhiman** [sympy/sympy#19928]
Sympy is just showing the output or the desired result for any mathematical/ physics equations (that's pretty much like an extraordinary scientific calculator just showing the answer for the question) but it would be better to add functionality for displaying the main steps for solving any particular equation.

> Example
`integrate(x**2, (x, 0, 1))` gave the output `1/3` but it would be better to make it somewhat like this `integrate(x**2, (x, 0, 1), show_steps = True)` i.e. adding a parameter that may take bool value(default = False) and according to that if the `show_steps` is `True` then the Sympy should return main steps for finding the proper solution along with the answer.

**Comment by oscarbenjamin** [comment]
It is a lot more work to implement things in a way that shows the steps rather than giving the result but it is not impossible.

In the case of indefinite integrals this has already been done (although incomplete):
```julia
In [8]: from sympy.integrals.manualintegrate import integral_steps                                                                             

In [9]: integral_steps(x**2, x)                                                                                                                
Out[9]: PowerRule(base=x, exp=2, context=x**2, symbol=x)
```

**Comment by abhaydhiman** [comment]
> It is a lot more work to implement things in a way that shows the steps rather than giving the result but it is not impossible

I know that may take lots of time and efforts but that makes the Sympy even better I guess and to be honest that functionality came in my mind(not so sure if that's good or bad) and I just want to share with you all.

**Comment by oscarbenjamin** [comment]
Thank you for the suggestion.

This is implemented for integrals and you can see it on sympy gamma:
https://gamma.sympy.org/input/?i=integrate%28x**2%2C+x%29

It can be implemented for other parts of sympy. Feel free to contribute something if you have some ideas.

Otherwise I think this is too broad a feature request to be useful as an open issue so I'm going to close it.
