### ISSUE TITLE
`P(Eq(X, constant number))` gives 0 for Continuous Rvs

### ISSUE THREAD

**Issue by Smit-create** [sympy/sympy#19939]
```py
>>> from sympy.stats import *
>>> from sympy import sqrt, Eq, symbols
>>> Y = Gamma('Y', 2, 3)
>>> P(Eq(Y, 3)) # incorrect
0
>>> N = Normal('N', 1, 2)
>>> P(Eq(N, 0)) # incorrect
0
```

While this works fine with FRV and DRV:
```py
>>> X = Poisson('X', 2)
>>> P(Eq(X, 2))
2*exp(-2)
>>> density(X)(2)
2*exp(-2)
>>> X = Binomial('X',5, 0.4)
>>> P(Eq(X, 2))
0.345600000000000
>>> density(X).dict[2]
0.345600000000000
```
The problem for CRV comes from:
https://github.com/sympy/sympy/blob/589c82d7e7152d71b7054ccf65f2c13803f7b20c/sympy/stats/crv.py#L522-L523
The `domain.set` for `P(Eq(N, 0))` is `FiniteSet(0)` and instead of returning `0`, it should be made to `return sum(self.pdf(x) for x in domain.set) if isinstance(domain.set, FiniteSet)`
ping @Upabjojr @czgdp1807

**Comment by jksuom** [comment]
>  N = Normal('N', 1, 2)
 P(Eq(N, 0)) # incorrect
0

What would you expect to get?

**Comment by Smit-create** [comment]
> What would you expect to get?

It should be:
```py
>>> density(N)(0) # it is equal to P(Eq(N, 0))
sqrt(2)*exp(-1/8)/(4*sqrt(pi))
>>> density(N)(0).evalf()
0.176032663382150
```

**Comment by jksuom** [comment]
`P` denotes a probability measure. For a continuous random variable, it is the integral of the density. The value of the integral on any one-point set is 0.

**Comment by Smit-create** [comment]
> The value of the integral on any one-point set is 0.

yes, I thought a bit and think that is absolutely true, but I had such doubt because, if we consider some stochastic process which follows some continuous distribution on the basis of parameter time and following independent increments, then we suppose that `Process(t+n)=x` and `Process(n)=y` then the probability is `P(Eq(Process(t), x-y))`, now if the distribution is continuous, it will give 0, but I think in this case it should not be...

**Comment by Maelstrom6** [comment]
I think relating to this issue is the definition of "almost surely": Mathematically, if _X = a almost surely_ this means that for all epsilon > 0, we have P(|X - a| < epsilon) = 1. Or in reference to sympy, `limit(P(abs(X - a) < epsilon), epsilon, 0, dir='+') == 1`. This is a fairly complicated definition to handle symbolically though. 

I have updated #19931 to reflect this correction. Apologizes for the confusion caused.

**Comment by jksuom** [comment]
I would use the value of the probability density of `Process(t) ` at `x - y` instead of the probability `P(Eq(Process(t), x-y))`.

**Comment by Upabjojr** [comment]
> ```python
> >>> from sympy.stats import *
> >>> from sympy import sqrt, Eq, symbols
> >>> Y = Gamma('Y', 2, 3)
> >>> P(Eq(Y, 3)) # incorrect
> 0
> >>> N = Normal('N', 1, 2)
> >>> P(Eq(N, 0)) # incorrect
> 0
> ```

These results are correct.

**Comment by Upabjojr** [comment]
> I would use the value of the probability density of `Process(t) ` at `x - y` instead of the probability `P(Eq(Process(t), x-y))`.

@Smit-create where are you using `P(Eq( ... ))` ? I agree that it should be preferrable to use the density.

SymPy can handle the density of discrete RVs as well, thanks to `DiracDelta` (which can turn discrete pmf into continuous distributions).

**Comment by Smit-create** [comment]
> These results are correct.

Yes, I found my mistake

> where are you using `P(Eq( ... ))` ?

I would change that to use the density

**Comment by czgdp1807** [comment]
Just saying, this wasn't a issue in the first place. `P(Eq(X, constant))` is zero always AFAIK.

**Comment by Smit-create** [comment]
Yeah, I'm sorry. I just got confused a bit.
