### ISSUE TITLE
How do I extend SymPy pretty printing for new structures in Jupyter notebook?

### ISSUE THREAD

**Issue by catskillsresearch** [sympy/sympy#19942]
Note: I've [posted this in Math StackExchange,](https://math.stackexchange.com/questions/3786168/how-do-i-extend-sympy-pretty-printing-for-new-structures-in-jupyter-notebook) which is not normal place for SymPy (StackOverflow is more usual but doesn't have math notation to express the question).  So please answer there or here if you can (or both):

In Jupyter notebook if we execute this code:

    import sympy as sp
    sp.init_printing()
    x,y=sp.symbols('x,y')
    x**2+sp.sin(y)

We will get a nice output, with no further coding, due to [SymPy's pretty printing process][3], which is the MathJax-formatted version of

$x^2 + \sin{y}$

Now suppose we do:

    class MetricSpace:
        def __init__(self, M, d):
            self.M = M
            self.d = d
            
        def __repr__(self):
            return f"$({self.M}, {self.d})$ {self.__class__.__name__}"
    
    Re,d=sp.symbols(r'\Re,d')
    
    MetricSpace(Re,d)

Then the output we get is

    $(\Re, d)$ MetricSpace

If we do instead

    from IPython.core.display import Markdown
    Markdown(repr(MetricSpace(Re,d)))

then I get the desired output, which is the MathJax-formatted version of:

* $(\Re, d)$ MetricSpace

**Question:** How do we code the above so that SymPy's pretty printer provides the desired output in Jupyter notebok without having to wrap it in `Markdown(repr(...))`?

  [1]: https://meta.stackexchange.com/questions/106281/mathjax-should-also-work-in-stackoverflow
  [2]: https://en.wikipedia.org/wiki/Catch-22
  [3]: https://docs.sympy.org/latest/tutorial/printing.html

**Comment by eric-wieser** [comment]
Sympy isn't (and can't be\*) involved here at all, just define `_repr_latex_` which is a jupyter hook.

\*Sympy only knows about math-mode latex, and doesn't support switching to text mode.

**Comment by catskillsresearch** [comment]
Actually I got a [perfect answer from Izaak van Dongen on  StackOverflow.](https://stackoverflow.com/questions/63342423/how-do-i-extend-sympy-pretty-printing-for-new-structures-in-jupyter-notebook)
