### ISSUE TITLE
 get integrate Upper limit problem

### ISSUE THREAD

**Issue by wenyanwen** [sympy/sympy#20006]
I want know Knowing the value of the integral, the lower limit of the integral, and the integral formula, how to find the upper limit of the integral

**Comment by wenyanwen** [comment]
solve(integrate(fun, (xx, X_start, X)) + length_segement, X)  

I found that the results of this method sometimes have no results when inversely inferring coordinates based on distance in curve fitting.

**Comment by oscarbenjamin** [comment]
Can you give an example of the problem that you are having?

**Comment by wenyanwen** [comment]
x, limit = symbols("x limit")
x_start = 1
x_end = 2.345

func = x ** 2 + x + 1
result = integrate(sqrt(1 + func ** 2), (x, x_start, x_end))
upper_limit = solve(integrate(sqrt(1 + func ** 2), (x, x_start, limit)) - result, limit)
print("Two order:")
print("function = %s, x_start = %f, x_end = %f" % (sqrt(1 + func ** 2), x_start, x_end))
print("integrate_result = %f" % (result))
print(upper_limit)

**Comment by wenyanwen** [comment]
You can try the code above

**Comment by oscarbenjamin** [comment]
Thank you for opening this issue but there is not enough information here to see what could be improved in sympy so I'm going to close this now. If you can provide more detail about the problem then maybe this issue can be reopened.
