### ISSUE TITLE
Better way of handling deprecation removal issues

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#20015]
I've noticed that virtually all SymPy developers misunderstand the purpose of the "deprecation-removal" tag on GitHub. 

The idea, as outlined at https://github.com/sympy/sympy/wiki/Deprecating-policy, is twofold. One, whenever there is a deprecation, there should be an issue to track the eventual removal of it (hence the name "deprecation **removal**"). And two, the deprecation warnings are supposed to point people to that issue. So the issue text should contain information relevant for end-users on why the feature is deprecated and how to fix their code. 

That was the idea behind this, but I've not seen anyone (other than myself) do it that way. So I'm wondering if we should just change it to something that doesn't confuse the developers so much. 

Instead, I see people using the label for issues relating to deprecating a feature, rather than *removing* an existing deprecation. And people never properly fill out useful information in the issue, despite the fact that the warnings link to it. I've also seen people link to the PR that removed the warning, rather than an issue. Of people won't create new issues for removing the deprecation but just reuse the one about making the deprecation.

Should we try to track the removal of deprecations? Maybe it isn't that important, since people seem to remove deprecations eventually anyway. I've also noticed the removal issues can prompt people looking for easy to fix issues to try to remove deprecations prematurely. As an aside, we don't currently have a policy on how long deprecations last, but maybe we should adopt one to remove the ambiguity here. 

For explaining the deprecation to users, maybe instead of doing it in issues, we should do it in documentation instead. I think the original motivation for issues was so that it could have a discussion forum for each deprecation in case people have questions. But I'm not sure if this has really been necessary. This also ties in nicely with the idea of documenting what things are deprecated https://github.com/sympy/sympy/issues/19806.

**Comment by sylee957** [comment]
I think that the old policy have problems because

1. When the deprecation is done while working on a PR, there can be no existing issue for deprecation removal yet, so where should the `issue=` be targeting to?
2. Usually, when the discussions are made inside the PR, the issue would contain no useful information or we would just have to copy paste
3. There are even more places where people do discussions like mailing list, so we can't track up the discussions there.

And since a lot of the sympy workflow is done by opening up a sample PR and discussing everything there rather than creating an issue and start things in such 'committee' manner, I think that the deprecating policy can be changed to adapt to this.

**Comment by asmeurer** [comment]
I think we can write down the reasoning. There is a lot of stuff in a PR that isn't very helpful to an end-user seeking more information about a deprecation. And as you note, the discussion can be spread out, so to be helpful to people, it should be written down. But it would be better to write it down in the actual documentation, rather than an issue. 

I also think that we can be more verbose in the deprecation warning messages themselves. I've seen very long messages from libraries like NumPy and Pandas, and they end up being very helpful.

**Comment by asmeurer** [comment]
For example, look at these deprecation warnings from NumPy:

```py
>>> import numpy as np
>>> a = np.arange(4).reshape((2, 2))
>>> a[[[0, 1], [0, 1]]]
__main__:1: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
array([0, 3])
>>> a[[10], 0:0]
__main__:1: DeprecationWarning: Out of bound index found. This was previously ignored when the indexing result contained no elements. In the future the index error will be raised. This error occurs either due to an empty slice, or if an array has zero elements even before indexing.
(Use `warnings.simplefilter('error')` to turn this DeprecationWarning into an error and get more details on the invalid index.)
  a[[10], 0:0]
array([], shape=(1, 0), dtype=int64)
```

**Comment by asmeurer** [comment]
This is something I'd like to tackle at some point as part of my documentation work. Before I do it we should make sure we all agree on what the policy should be. It would be nice if we could use SymPEPs for this, but the progress on those has stalled, and I don't want to block one on the other, especially given that we already have a rough policy on the wiki. 

So I think what I'd like to do is move the current deprecation policy from the wiki into the documentation, then update it there. Then I can work on modifying all the existing deprecations so that they are documented in the documentation rather than in "removal" issues. Having the policy itself in the docs isn't such a bad thing, as it affects users, and even if it's more of a "contributor documentation", we need to be putting more of that in the docs instead of the wiki. If we do eventually finish formalizing a SymPEP process, we can look at moving it there.

**Comment by oscarbenjamin** [comment]
Documentation of deprecations definitely needs improvement.

**Comment by moorepants** [comment]
> So I think what I'd like to do is move the current deprecation policy from the wiki into the documentation, then update it there.

:+1:  to that. This will then allow for review and comments on any updates and changes, which is probably sufficient and no SymPEP needed.

**Comment by asmeurer** [comment]
I hope so. I've started writing this now, and I want to write something about how public APIs need to go through deprecations and private APIs don't, but this starts to open the can of worms about what is public and what is private. For now, I'm just mentioning a few broad rules, but saying that nothing exact has been codified yet.

**Comment by asmeurer** [comment]
I've made a pull request https://github.com/sympy/sympy/pull/22900. 

I plan to update all the deprecations in SymPy to give them more informative messages and to document them, but I don't want to do this until I am sure we are in agreement on doing so. So please review what I have there and let me know if you disagree with any of it.
