### ISSUE TITLE
Gravity

### ISSUE THREAD

**Issue by sidhu1012** [sympy/sympy#20020]
Since Gravity comes under mechanics , shouldn't it have gravity and related functs like Gravitational Force , gravitational potential etc?

If yes I would like to ad them

**Comment by moorepants** [comment]
Currently you have to apply forces to points manually. It is common to apply a gravitational force to each particle and body in the system. A function that takes in a gravity force vector and a list of particles and bodies and outputs a list of (force vector, point) tuples would be a useful addition.

**Comment by sidhu1012** [comment]
> Currently you have to apply forces to points manually. It is common to apply a gravitational force to each particle and body in the system. A function that takes in a gravity force vector and a list of particles and bodies and outputs a list of (force vector, point) tuples would be a useful addition.

You mean a function to return a list of gravitational force vector on every point in the system?

**Comment by moorepants** [comment]
I mean "A function that takes in a gravity force vector and a list of particles and bodies and outputs a list of (force vector, point) tuples ".

**Comment by sidhu1012** [comment]
> I mean "A function that takes in a gravity force vector and a list of particles and bodies and outputs a list of (force vector, point) tuples ".

In which file this function shall be added?  Mechanics/particle? Or vectors?

**Comment by VirtualAcoustics** [comment]
Isn't that what the function "gravity" in sympy/physics/mechanics/functions.py does?

**Comment by moorepants** [comment]
Hah! Yes. It is already there.

Closing this. Please reopen if you had something more in mind.

**Comment by sidhu1012** [comment]
> Hah! Yes. It is already there.
> 
> Closing this. Please reopen if you had something more in mind.

I was thinking that mechanics\particle.py should have a function to calculate gravitational force of a particle w.r.t to another particle so that if user wishes to calculate for just 2 particle system he could do it directly (scalar value).
And have a similar function in class particle to  calculate gravitational potential of tha particle at a specified distance.
