### ISSUE TITLE
Complex Square Roots

### ISSUE THREAD

**Issue by GarkGarcia** [sympy/sympy#20024]
This is a follow up of https://github.com/mathics/Mathics/issues/793. I was wondering if you guys would consider implementing complex square roots? Currently the `Pow` function does not attempt to compute the square root of a complex number:

```
>>> from sympy import Pow, I, Integer
>>> d = Integer(1) / Integer(2)
>>> Pow(1 + I, d)
sqrt(1 + I)
```

## References
* **Wikipedia article on complex square roots:** https://en.wikipedia.org/wiki/Square_root#Square_roots_of_negative_and_complex_numbers

**Comment by GarkGarcia** [comment]
I expected the output of `Pow` to look something like this:

```
>>> from sympy import Pow, I, Integer
>>> d = Integer(1) / Integer(2)
>>> Pow(1 + I, d)
sqrt(-2 + 2 * sqrt(2))/(-2 + 2* sqrt(2)) + sqrt(-2 + 2 * sqrt(2))/2 * I
```

**Comment by Maelstrom6** [comment]
`sqrt(1 + I)` certainly does look simpler than `sqrt(-2 + 2 * sqrt(2))/(-2 + 2* sqrt(2)) + sqrt(-2 + 2 * sqrt(2))/2 * I`. I suspect that's the reason why it doesn't convert it to explicit rectangular form. However, if you do want it in explicit rectnagular form, you could do the following:
```python
from sympy import *

number = sqrt(1 + I)
real = re(number)
imaginary = im(number)
rectangular = real + imaginary*I
print(rectangular)

# check your desired solution is equivalent:
print((real - sqrt(-2 + 2 * sqrt(2))/(-2 + 2* sqrt(2))).simplify() == 0)
print((imaginary - sqrt(-2 + 2 * sqrt(2))/2).simplify() == 0)
```
Which gives:
```python
2**(1/4)*sqrt(sqrt(2)/4 + 1/2) + 2**(1/4)*I*sqrt(1/2 - sqrt(2)/4)
True
True
```
Check [this question](https://stackoverflow.com/questions/41324497/sympy-and-square-roots-of-complex-numbers) out if you want a basic function to get all its roots.

**Comment by oscarbenjamin** [comment]
I think it's better that complex square roots do not evaluate by default. Automatic evaluation makes it harder to express results in different forms and clearly in this case no evaluation can give a simpler result.

You can use `expand` with `complex=True` to get this in the form `x + I*y`:
```julia
In [14]: e = sqrt(1 + I)                                                                                                                                      

In [15]: e                                                                                                                                                    
Out[15]: 
  _______
╲╱ 1 + ⅈ 

In [16]: e.expand(complex=True)                                                                                                                               
Out[16]: 
          ________               ________
4 ___    ╱ √2   1    4 ___      ╱ 1   √2 
╲╱ 2 ⋅  ╱  ── + ─  + ╲╱ 2 ⋅ⅈ⋅  ╱  ─ - ── 
      ╲╱   4    2            ╲╱   2   4  
```

**Comment by GarkGarcia** [comment]
Fair enough, `expand` does the job. Thanks for the help!
