### ISSUE TITLE
Substitution where assumptions of symbols is disregarded

### ISSUE THREAD

**Issue by rikardn** [sympy/sympy#20036]
I am looking for a way of substituting symbols in an expression that only considers the names of the symbols and not their assumptions. For example:

```
import sympy

x, y = sympy.symbols('x y', real=True)
expr = x + y
expr.subs({'x': 2})
```

Nothing gets substituted here because the sympification of 'x' will not get the ```real=True``` assumption. The same situation arise if one would try ```expr.evalf(subs={'x': 2})```. I am looking for a way of doing the substitution either given a default sympification of symbols or by disregarding assumptions. I already use the workaround of substituting with using the correct symbol object directly, but I believe it would be very useful if sympy could do this from the string.

If nothing like this is available today I would be happy to try to implement it and submit a PR. In that case do you think it should be done as

```
expr.subs({'x': 2}, assumptions=False)
```

which I personally think is best, or as

```
expr.subs({'x': 2}, sympify_default_assumptions={'real': True})
```

or something different, like a global default sympification setting.

**Comment by oscarbenjamin** [comment]
You could use
```python
assumptions = {'real': True}                                                                                                                         
expr = expr.replace(lambda s: s.is_Symbol, lambda s: Symbol(s.name, **assumptions))    
```

**Comment by sylee957** [comment]
I'd also find an option to ignore all the assumptions about symbols can be useful.
Actually, assumptions should have no reason to be tied with symbols at the first place. In new assumptions module, it shows how assumptions can be supplied externally.

**Comment by rikardn** [comment]
@sylee957 The assumptions module looks interesting. I like the idea of providing assumptions when needed and not directly on the symbols. It would save a lot of headaches. I'll consider not using assumptions on my symbols until needed and then potentially applying them via the idea from @oscarbenjamin

**Comment by rikardn** [comment]
Since I have solved my problem using as per my previous comment I could use subs, sympify and evalf as usual. I only add assumptions when needed. Then my initial suggestions are not needed so I'll close this issue.
