### ISSUE TITLE
sym.inverse_laplace_transform()

### ISSUE THREAD

**Issue by albarber42** [sympy/sympy#20059]
When performing (6*(s + 50))/(s*(s**2 + 40*s + 300)) it will not evaluate the the Inverse Laplace Transform.  However it will evaluate the constituents of the partial fraction decomposition expression.

**Comment by josephcslater** [comment]
This command was preceded by 


```import sympy as sym
from sympy.abc import *
sym.init_printing()
s, t, omega= sym.symbols("s, t, omega", real = True)
x = sym.Function('x')
y = sym.Function('y')
f = sym.Function('f')
```

**Comment by josephcslater** [comment]
I've created a work around. 

```
def ilt(expr):
    ilt = 0
    expanded = sym.apart(expr).as_ordered_terms()
    print('Expanded this is ', expanded)
    for term in expanded:
        print('Terms are ', term)
        print(sym.inverse_laplace_transform(term, s, t))
        ilt += sym.inverse_laplace_transform(term, s, t)
    return ilt
```

**Comment by josephcslater** [comment]
You should edit the label and make this "easy" as I have provided a workaround.

**Comment by sylee957** [comment]
I had given similar ideas whether this can be integrated as a default strategy, or the whole `Integral` object can come up with its own partial fraction decomposition such that users can control how a single `Integral` is split into multiple problems.
But I'm not sure if this can be marked as easy because because there can be a lot of obstacles messing up with the integrals.

**Comment by jksuom** [comment]
There is an [open PR](https://github.com/sympy/sympy/pull/16383) on using `apart` for the inverse Laplace transform. It seems that there are some remaining issues that are not trivial to solve.

**Comment by josephcslater** [comment]
It seems that if there is a returned flag "accomplished/not accomplished", one could loop through multiple different attempts until one works. I don't know that it should be default, but it shouldn't return as failed without trying this first.
