### ISSUE TITLE
Add a test that lambdify works with numba

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#20070]
We should have a test in our test suite that tests that lambdify() works properly if you jit it with `numba.jit`. If we have that, then numba can add it to their integration tests to avoid potentially breaking it in the future (and we can also avoid breaking it too). 

See https://github.com/numba/numba/issues/2328

**Comment by xavierdurawa** [comment]
Happy to give this a stab.  New to the project and open source so I'll ask for a little patience :)
Should the test go in sympy/sympy/utilities/tests/test_lambdify.py?

**Comment by moorepants** [comment]
@xavierdurawa Thanks for looking into this. I think this test might belong here: https://github.com/sympy/sympy/tree/master/sympy/external/tests as there are similar tests.

**Comment by asmeurer** [comment]
Yes. Be sure to mimic what is done with other tests to make it so the test doesn't fail if numba is not installed. Also, `numba`, should be added to the optional dependency list in .travis.yml.

**Comment by anurag-r20** [comment]
Hi. I would like to work on this issue. I am just getting started with open source contributions and I would really like to fix this issue if its open.
Thankyou

**Comment by ayushbisht2001** [comment]
I would like to work on this issue.

**Comment by Uttam-Singhh** [comment]
Please assign me this issue and guide me on what to do??

**Comment by khanatif271** [comment]
Let me work on this issue.

**Comment by oscarbenjamin** [comment]
Anyone is free to work on any issue. We don't assign issues in sympy. If you can see what needs doing then go ahead.

**Comment by abbyjng** [comment]
I've started taking a look at this issue and would appreciate some guidance, if anyone could help. What are the different things jit is used for / should be tested for? I understand I should test it on a simple formula such as a lambdified sin(x), but what else should be looked at? I am having trouble finding examples of numba.jit being used, which is why I ask here. Thanks!
