### ISSUE TITLE
n - floor(n/pi + 1/2.)*pi sometimes yields wrong results

### ISSUE THREAD

**Issue by sebastianprobst** [sympy/sympy#20076]
`n - floor(n/pi + 1/2.)*pi` should be equal to `atan(tan(n))`

However, for large values of n this fails sometimes.
Example n=260515:
`atan(tan(260515)) = 260515 - 82924*pi`
`260515 - floor(260515/pi + 1/2.)*pi = 260515 - 82925*pi` (factor before pi is wrong, should be 82924)

**Comment by weakit** [comment]
This seems to be an issue with sympy's `floor`:

```python
>>> expr = 260515/pi + Rational('1/2')

>>> N(expr)
82924.9999991702 

>>> floor(expr) # when expr is passed symbolically
82925 

>>> floor(N(expr)) # when expr is passed a numerical approximation
82924 
```

**Comment by weakit** [comment]
I did a bit of digging around and noticed that this is happening because of the lower precision used by `get_integer_part` in the `evalf` module:

https://github.com/sympy/sympy/blob/b6c328e2f057ba81513d19a1451ace358ecc8233/sympy/core/evalf.py#L306-L316

```python
>>> evalf.evalf(expr, 30, {})
((0, 82925, 0, 17), None, 40, None)
>>> 82925 * 2 ** 0  # hence the result
82925

>>> evalf.evalf(expr, 53, {})
((0, 2849281304137889, -35, 52), None, 63, None)
>>> 2849281304137889 * 2 ** -35  # should work properly with higher precision
82924.99999917022
```

Seems to be a simple fix.

**Comment by weakit** [comment]
This seems to be the same issue as #19991.

**Comment by asmeurer** [comment]
I didn't notice it was doing that. Are both issues fixed if we remove the fixed 30 precision and replace it with the input precision?

**Comment by weakit** [comment]
The input is symbolic here, and that's the main problem. The function "assumes" precision to be 30 and then tries to find if any extra precision is required. I don't really understand how that's supposed to work, and in this case, it doesn't for some reason.

Increasing that assumed precision will reduce the error, but won't completely get rid of it. Right now, I have no idea how to figure out what precision to use for a given input. You could have something like:
![image](https://user-images.githubusercontent.com/34541656/93327783-77346180-f838-11ea-9975-a44c7174aaf7.png)
and it should still work.

Even Mathematica isn't perfect:
![image](https://user-images.githubusercontent.com/34541656/93328344-3a1c9f00-f839-11ea-8759-8363555b887a.png)

Increasing the precision is a partial solution tho, and will fix this case and probably also the ones in #19991.

**Comment by jksuom** [comment]
`get_integer_part` may fail when its argument, `expr`, is close to an integer. In that case, `calc_part` sets the flag `is_int`
```
    def calc_part(re_im, nexpr):
        from sympy.core.add import Add
        n, c, p, b = nexpr
        is_int = (p == 0)
        nint = int(to_int(nexpr, rnd))
```
and computes the `mpf` value of the difference `re_im - nint` where `re_im` is essentially  the input `expr` and `nint` is an approximating integer:
```
        if is_int:
            # make sure that we had enough precision to distinguish
            # between nint and the re or im part (re_im) of expr that
            # was passed to calc_part
            ire, iim, ire_acc, iim_acc = evalf(
                re_im - nint, 10, options)  # don't need much precision
            assert not iim
```
If the result is very small (`size > prec`), then the flag `is_int` is recomputed, and the final result is calculated by the next `if` statement:
```
            size = -fastlog(ire) + 2  # -ve b/c ire is less than 1
            if size > prec:
                ire, iim, ire_acc, iim_acc = evalf(
                    re_im, size, options)
                assert not iim
                nexpr = ire
                n, c, p, b = nexpr
                is_int = (p == 0)
                nint = int(to_int(nexpr, rnd))
        if not is_int:
```
However, the flag should also be recomputed when the difference is greater (`size <= prec`). This is one way of doing that (though not necessarily the best way):
```
--- a/sympy/core/evalf.py
+++ b/sympy/core/evalf.py
@@ -363,6 +363,8 @@ def calc_part(re_im, nexpr):
                 n, c, p, b = nexpr
                 is_int = (p == 0)
                 nint = int(to_int(nexpr, rnd))
+            else:
+                is_int = (ire[2] == 0)
         if not is_int:
             # if there are subs and they all contain integer re/im parts
             # then we can (hopefully) safely substitute them into the
```
