### ISSUE TITLE
Add incomplete and regularized beta functions and regularized gamma functions

### ISSUE THREAD

**Issue by peteroupc** [sympy/sympy#20098]
I found that these functions are missing in SymPy.  They are described in MathWorld at:

https://mathworld.wolfram.com/IncompleteBetaFunction.html
https://mathworld.wolfram.com/RegularizedBetaFunction.html
https://mathworld.wolfram.com/RegularizedGammaFunction.html

For what I seek to do, the regularized beta function is important because it is the beta distribution's cumulative distribution function.

**Comment by pjrenzov** [comment]
Hello, I am new to open source and want to work this issue. It will be very helpful if someone can guide me where to start.

**Comment by naveensaigit** [comment]
There is a PR (#18727) which started implementing Incomplete Beta, but it has stalled. I went through Wolfram Functions and we can broadly classify the functions into 2 types for implementation purpose.

![\begin{align*}
\text{a. Normal Beta Functions}
\end{align*}
](https://render.githubusercontent.com/render/math?math=%5Cdisplaystyle+%5Cbegin%7Balign%2A%7D%0A%5Ctext%7Ba.+Normal+Beta+Functions%7D%0A%5Cend%7Balign%2A%7D)

![\begin{align*}
\hspace{1cm}\text{1. Beta Function - } B(a, b) = \int_{0}^{1} t^{a - 1} (1-t)^{b - 1}dt
\end{align*}](https://render.githubusercontent.com/render/math?math=%5Cdisplaystyle+%5Cbegin%7Balign%2A%7D%0A%5Chspace%7B1cm%7D%5Ctext%7B1.+Beta+Function+-+%7D+B%28a%2C+b%29+%3D+%5Cint_%7B0%7D%5E%7B1%7D+t%5E%7Ba+-+1%7D+%281-t%29%5E%7Bb+-+1%7Ddt%0A%5Cend%7Balign%2A%7D)

![\begin{align*}
\hspace{1cm}\text{2. Central Beta Function - } \beta(a) = B(a, a)
\end{align*}](https://render.githubusercontent.com/render/math?math=%5Cdisplaystyle+%5Cbegin%7Balign%2A%7D%0A%5Chspace%7B1cm%7D%5Ctext%7B2.+Central+Beta+Function+-+%7D+%5Cbeta%28a%29+%3D+B%28a%2C+a%29%0A%5Cend%7Balign%2A%7D)

![\begin{align*}
\text{b. Incomplete Beta Functions}
\end{align*}
](https://render.githubusercontent.com/render/math?math=%5Cdisplaystyle+%5Cbegin%7Balign%2A%7D%0A%5Ctext%7Bb.+Incomplete+Beta+Functions%7D%0A%5Cend%7Balign%2A%7D)

![\begin{align*}
\hspace{1cm}\text{1. Generalized Incomplete Beta Function - } B(z_1, z_2; a, b) = \int_{z_1}^{z_2} t^{a-1}(1 - t)^{b-1} dt
\end{align*}
](https://render.githubusercontent.com/render/math?math=%5Cdisplaystyle+%5Cbegin%7Balign%2A%7D%0A%5Chspace%7B1cm%7D%5Ctext%7B1.+Generalized+Incomplete+Beta+Function+-+%7D+B%28z_1%2C+z_2%3B+a%2C+b%29+%3D+%5Cint_%7Bz_1%7D%5E%7Bz_2%7D+t%5E%7Ba-1%7D%281+-+t%29%5E%7Bb-1%7D+dt%0A%5Cend%7Balign%2A%7D%0A)

![\begin{align*}
\hspace{1cm}\text{2. Incomplete Beta Function - } B(z; a, b) = \int_{0}^{z} t^{a-1}(1 - t)^{b-1} dt
\end{align*}](https://render.githubusercontent.com/render/math?math=%5Cdisplaystyle+%5Cbegin%7Balign%2A%7D%0A%5Chspace%7B1cm%7D%5Ctext%7B2.+Incomplete+Beta+Function+-+%7D+B%28z%3B+a%2C+b%29+%3D+%5Cint_%7B0%7D%5E%7Bz%7D+t%5E%7Ba-1%7D%281+-+t%29%5E%7Bb-1%7D+dt%0A%5Cend%7Balign%2A%7D)

![\begin{align*}
\text{b. Regularized Beta Functions}
\end{align*}
](https://render.githubusercontent.com/render/math?math=%5Cdisplaystyle+%5Cbegin%7Balign%2A%7D%0A%5Ctext%7Bb.+Regularized+Beta+Functions%7D%0A%5Cend%7Balign%2A%7D%0A)

![\begin{align*}
\hspace{1cm}\text{1. Generalized Regularized Incomplete Beta Function - } I(z_1, z_2; a, b) = \frac{B(z_1, z_2; a, b)}{B(a, b)}
\end{align*}](https://render.githubusercontent.com/render/math?math=%5Cdisplaystyle+%5Cbegin%7Balign%2A%7D%0A%5Chspace%7B1cm%7D%5Ctext%7B1.+Generalized+Regularized+Incomplete+Beta+Function+-+%7D+I%28z_1%2C+z_2%3B+a%2C+b%29+%3D+%5Cfrac%7BB%28z_1%2C+z_2%3B+a%2C+b%29%7D%7BB%28a%2C+b%29%7D%0A%5Cend%7Balign%2A%7D)

![\begin{align*}
\hspace{1cm}\text{2. Regularized Incomplete Beta Function - } I(z; a, b) = \frac{B(z; a, b)}{B(a, b)}  \hspace{0.2cm}(\text{Not always true})
\end{align*}](https://render.githubusercontent.com/render/math?math=%5Cdisplaystyle+%5Cbegin%7Balign%2A%7D%0A%5Chspace%7B1cm%7D%5Ctext%7B2.+Regularized+Incomplete+Beta+Function+-+%7D+I%28z%3B+a%2C+b%29+%3D+%5Cfrac%7BB%28z%3B+a%2C+b%29%7D%7BB%28a%2C+b%29%7D++%5Chspace%7B0.2cm%7D%28%5Ctext%7BNot+always+true%7D%29%0A%5Cend%7Balign%2A%7D)

Right now, we have only the regular `beta` function implemented. IMO, we can just implement 2 classes - one for incomplete beta functions and another for regularized beta functions. Central beta can be added to existing `beta` class. I was thinking of the following API

``` python
>>> from sympy import beta, incomplete_beta, regularized_beta
>>> beta(a, b) #Existing
>>> beta(a) #Central beta
>>> incomplete_beta([z1, z2], a, b) #Generalized Incomplete beta
>>> incomplete_beta(z, a, b) #Incomplete beta
>>> regularized_beta([z1, z2], a, b) #Generalized Regularized beta
>>> regularized_beta(z1, a, b) #Regularized beta
```
Does this look good @oscarbenjamin ?

**Comment by oscarbenjamin** [comment]
> ```python
> >>> beta(a, b) #Existing
> >>> beta(a) #Central beta
> ```

It's better not to have a class that doesn't know how many args it has. If `beta(a)` is automatically converted to `beta(a, a)` and always has 2 args then that's fine. Otherwise I would make a common base class and have `beta` and `centralbeta` as subclasses.

**Comment by naveensaigit** [comment]
> > ```python
> > >>> beta(a, b) #Existing
> > >>> beta(a) #Central beta
> > ```
> 
> It's better not to have a class that doesn't know how many args it has. If `beta(a)` is automatically converted to `beta(a, a)` and always has 2 args then that's fine. Otherwise I would make a common base class and have `beta` and `centralbeta` as subclasses.

I'd go with the option of converting `beta(a)` to `beta(a, a)` since this is the only difference between beta and central beta. It would only duplicate code. Are the others fine?

**Comment by naveensaigit** [comment]
There is a closed form for the Generalized Incomplete Beta Function in terms of Meijer G function. Infact - 
``` python
>>> from sympy import *
>>> t, a, b, z1, z2 = symbols('t a b z1 z2')
>>> Integral(t**(a-1)*(1-t)**b, (t, z1, z2)).doit(meijerg=True)
-z1**a*gamma(a)*hyper((a, 1 - b), (a + 1,), z1*exp_polar(2*I*pi))/gamma(a + 1) + z2**a*gamma(a)*hyper((a, 1 - b), (a + 1,), z2*exp_polar(2*I*pi))/gamma(a + 1)
```
@oscarbenjamin Should I use this definition instead of the integral definition?

**Comment by oscarbenjamin** [comment]
We should probably base our definitions on something like DLMF in general:
https://dlmf.nist.gov/8.17
Or perhaps fungrim:
http://fungrim.org/topic/Beta_function/

**Comment by naveensaigit** [comment]
I see that these definitions don't include the generalized beta function, but substituting `z1 = 0` and simplifying the expression I mentioned above

> ``` python
> -z1**a*gamma(a)*hyper((a, 1 - b), (a + 1,), z1*exp_polar(2*I*pi))/gamma(a + 1) + z2**a*gamma(a)*hyper((a, 1 - b), (a + 1,), z2*exp_polar(2*I*pi))/gamma(a + 1)
> ```

gives the same formula that is mentioned in these sites. So, I'll go ahead and add them.
