### ISSUE TITLE
Viewer mode 'file' broken in recent versions

### ISSUE THREAD

**Issue by shankar1729** [sympy/sympy#20094]
Using sympy.preview with viewer=file complains that no such viewer is available on the system. This seems to be due to a check starting line 140 in old versions (eg. 1.1) of sympy/printing/preview.py:

```
if viewer == "file":
            if filename is None:
                SymPyDeprecationWarning(feature="Using viewer=\"file\" without a "
                    "specified filename", deprecated_since_version="0.7.3",
                    useinstead="viewer=\"file\" and filename=\"desiredname\"",
                    issue=7018).warn()
```

that seem to be missing in more recent versions (eg. 1.6). It seems that the intent was to remove the deprecation warning and replace it with an error. However, removing the entire block leads to the code further down searching for 'file' amongst system viewers leading to the reported error. The most localized fix to this error is to add back a code block:

```
if viewer == "file":
        pass
elif viewer == "StringIO":  #currently if viewer == ... in the code
        ...
```

I have not bisected to  find which version this was broken in; I only saw this in comparing between version 1.1 and 1.6 found in two different anaconda installations.

Best,
Shankar

**Comment by oscargus** [comment]
This was fixed in #19904 and it seems like it only affected 1.6. (Introduced in #18392)
