### ISSUE TITLE
solveset(1/sqrt(x)) causes RecursionError: maximum recursion depth exceeded

### ISSUE THREAD

**Issue by RonAvitzur** [sympy/sympy#20097]
`solveset(1/sqrt(x))` fails with _RecursionError: maximum recursion depth exceeded while calling a Python object_ in the interactive interpreter with SymPy 1.6.1

For comparison `solveset(1/x)` returns `EmptySet` and `solve(1/sqrt(x))` gives `[]`

**Comment by maurogaravello** [comment]
In master `solveset(1/sqrt(x))` fails, but restricting to the real numbers, i.e. `solveset(1/sqrt(x), x, Reals)`, the result is `EmptySet`.

**Comment by dsaw** [comment]
Related to https://github.com/sympy/sympy/issues/15350. `solveset` doesn't seem to handle denominators with radicals.

**Comment by maurogaravello** [comment]
The issue is due to `_invert_complex`, which is unable to invert the equation. Instead `_invert_real` does the job.
A possible solution is to add the following lines to `_invert_complex`.

```
    if f.is_Pow:
        # only the case symbol**(exponent)=0 with negative exponent is treated
        if g_ys == FiniteSet(0):
            base, expo = f.args
            if isinstance(base, Dummy) and expo.is_negative:
                return (base, S.EmptySet)
```

This takes care only of the situation like `x**p = 0` with `p < 0`. This seems quite unsatisfactory.

**Comment by RonAvitzur** [comment]
The particular bug report I was investigating: _When I apply Solve to_ `2/(3*sqrt(x,3))=0` _or_ `2/(3*x^(1/3))=0` _Graphing Calculator crashes._

**Comment by oscarbenjamin** [comment]
> This takes care only of the situation like `x**p = 0` with `p < 0`. This seems quite unsatisfactory.

Can we not say that any `f(x)**p = 0` with `p < 0` has no solutions?

I guess you're thinking of something like this:
```julia
In [3]: eq = 1/(1 + 1/x)                                                                                                                       

In [4]: eq                                                                                                                                     
Out[4]: 
  1  
─────
    1
1 + ─
    x

In [5]: eq.subs(x, 0)                                                                                                                          
Out[5]: 0

In [6]: solveset(eq, x)                                                                                                                        
Out[6]: ∅
```
I would think that any singularity of the function is implicitly excluded from the domain so empty set is correct for this.

I see that this is not consistently applied for trigonometric functions though:
```julia
In [8]: solveset(1/tan(x), x)                                                                                                                  
Out[8]: 
⎧        π        ⎫   ⎧        3⋅π        ⎫
⎨2⋅n⋅π + ─ | n ∊ ℤ⎬ ∪ ⎨2⋅n⋅π + ─── | n ∊ ℤ⎬
⎩        2        ⎭   ⎩         2         ⎭

In [11]: solveset(1/(1 + 1/sin(x)), x)                                                                                                         
Out[11]: {2⋅n⋅π | n ∊ ℤ} ∪ {2⋅n⋅π + π | n ∊ ℤ}

In [10]: solveset(1/log(x), x)                                                                                                                 
Out[10]: ∅

In [13]: solveset(1/(1 + 1/(1-exp(x))), x)                                                                                                     
Out[13]: {2⋅n⋅ⅈ⋅π | n ∊ ℤ} \ {2⋅n⋅ⅈ⋅π + log(2) | n ∊ ℤ}
```

This example suggests an attempt to rule out such singularities:
```julia
In [15]: solveset(1/(1 + 1/LambertW(x)), x)                                                                                                    
Out[15]: {x | x ∊ ℂ ∧ (W(x) = 0)} \ {x | x ∊ ℂ ∧ (W(x) + 1 = 0)}
```

**Comment by maurogaravello** [comment]
I agree that we can treat also the case `f(x)**p = 0` with `p<0`.

With such a change,  `solveset(1/(1 + 1/(1-exp(x))), x)` and `solveset(1/(1 + 1/LambertW(x)), x)` both return `EmptySet`.

Instead `solveset(1/tan(x), x)` works as you said. This is due to the function `_solve_trig1`, which rewrites the expression in exponential form.

**Comment by oscargus** [comment]
This seems to work on the current master, so if a test is added it can be closed.

**Comment by oscarbenjamin** [comment]
Bisected the fix to 8cfb626c8fbd6031492f6b50a8c215d74a69ee7a from #21032 although that was subsequently improved by #21276

**Comment by oscargus** [comment]
I'm working on a PR with tests for this and whatever other issues I find that have been fixed elsewhere.

**Comment by oscarbenjamin** [comment]
Okay, so I removed the easy to fix label then
