### ISSUE TITLE
Allow symbols to specify the order of derivatives

### ISSUE THREAD

**Issue by peteroupc** [sympy/sympy#20110]
I want to compute the summation of higher-order derivatives of the same function, similar to:

    expr2=(1+exp(k))/(1+exp(k+1))
    summation(diff(expr2,k,m).subs(k,0)/factorial(m), (m, 0, 2))

The expression above fails (and returns 0) because `m` is treated as another symbol rather than the order of differentiation (that is, second-order, third-order, etc.).  Thus, in this example, `diff(expr2,k,m)` differentiates with respect to `k` then with respect to `m` (rather than differentiating `m` times with respect to `k`), and I understand that this may be the intended behavior.

Moreover, I don't see a way to specify the order of a derivative as a number (or as a symbol that evaluates to a number), other than via the syntax `diff(expr2, x, i)` where `i` is the desired order and can only be a number (not a symbol).

Therefore, I request a way to allow symbols to specify the order of differentiation, so that they can serve as the symbol for summation, etc.

**Comment by oscarbenjamin** [comment]
You can do this with tuples:
```julia
In [1]: x, n = symbols('x, n')                                                                                                                 

In [2]: exp(x).diff((x, n))                                                                                                                    
Out[2]: 
  n    
 d ⎛ x⎞
───⎝ℯ ⎠
  n    
dx     

In [3]: diff(exp(x), (x, 2*n))                                                                                                                 
Out[3]: 
  2*n    
 d   ⎛ x⎞
─────⎝ℯ ⎠
  2*n    
dx       

In [4]: Derivative(exp(x), (x, 3*n))                                                                                                           
Out[4]: 
  3*n    
 d   ⎛ x⎞
─────⎝ℯ ⎠
  3*n    
dx       

In [5]: y = Symbol('y')                                                                                                                        

In [6]: Derivative(exp(x), (x, n), (y, n))                                                                                                     
Out[6]: 
   2*n     
  d    ⎛ x⎞
───────⎝ℯ ⎠
  n   n    
dy  dx   
```

**Comment by peteroupc** [comment]
Thank you, that works fine.  Closing.
