### ISSUE TITLE
Warn the user when trees of points or trees of reference frames are not self consistent.

### ISSUE THREAD

**Issue by moorepants** [sympy/sympy#20129]
sympy.physics.vector has Point and ReferenceFrame. These can be positioned and oriented relative to objects of their same type, respectively. The user is expected to define relative positions and orientations in a consistent manner and the relationships among the objects should be tree graphs. It would be helpful to warn the user if they set positions and orientations that create incorrect graphs, for example adding a cyclic branch; the graphs should be acyclic. You can also create inconsistencies when it comes to calculating velocities and angular velocities, which is done automatically if possible. Here is a point example:

```
N = ReferenceFrame('N')
O = Point('O')
P = Point('P')
Q = Point('Q')
P.set_vel(N, N.x)
Q.set_vel(N, N.y)
O.set_pos(P, 5*N.z)
O.set_pos(Q, 6*N.y)
O.vel(N)
```

The velocities of O in N are different depending on if you calculate based on P or Q. It is also impossible to choose between P or Q. Right now, P or Q will be chosen based on which comes first in `_pos_dict.items()`. We should warn the user that this graph is inconsistent when trying to calculate the velocity of O in N. This same thing can happen with ReferenceFrame.

I suspect there will be issues when users have kinematic loops and may want to define the loop of point positions that specify the loop. Currently, that is not supported. If you specify a loop through a succession of set_pos() or locate_new() calls, you get an invalid point tree. Kinematic loops have to be dealt with by adding the algebraic equation and forming DAEs instead.

These warnings need some careful thought. The first step would be to define precisely what graphs are consistent and non consistent, in terms of physics.vector's capabilities and design. Once that is defined, some methods to check for consistencies can be added. There will be inconsistencies related purely to position and orientation as well as inconsistencies related to the automated calculation of velocities.

There is discussion in this PR that is relevant: https://github.com/sympy/sympy/pull/20049

**Comment by sidhu1012** [comment]
If we have multiple points defined at a same level , currently automated velocity would choose the point which comes first, but what I suggest is that we calculate all possible velocities of shortest path by and update _vel_dict by a dictionary

p._vel_dict[frame] = { point1 : calculated_velocity, point2 : calc_velocity}

point1 , point2 being two points with velocity defined with required frame at same level.

This could give user a choice to choose between any velocity he requires

If he updates p's velocity using set_vel(frame) then the dictionary is overridden by user defined velocity.

**Comment by moorepants** [comment]
That's not what we'd want. The goal is to calculate the correct velocity or none at all.

**Comment by sidhu1012** [comment]
> That's not what we'd want. The goal is to calculate the correct velocity or none at all.

Got it
