### ISSUE TITLE
Remove `index_of` from `DiscreteMarkovChain`

### ISSUE THREAD

**Issue by czgdp1807** [sympy/sympy#20138]
After merging of https://github.com/sympy/sympy/pull/20042 named states such as `Symbol` objects are required to be accessed by `index_of` as shown by the example below,

https://github.com/sympy/sympy/blob/b88c69a1edf941c211a49fee9a8a56be790f4196/sympy/stats/stochastic_process_types.py#L688-L696

The above should be made as simple as the following,

```python
     >>> sunny, cloudy, rainy = symbols('Sunny, Cloudy, Rainy') 
     >>> Y = DiscreteMarkovChain("Y", [sunny, cloudy, rainy], T) 
     >>> P(Eq(Y[3], rainy), Eq(Y[1], cloudy)).round(2) 
     0.36
  
     >>> E(Y[3], Eq(Y[1], cloudy)) 
     0.38*Cloudy + 0.36*Rainy + 0.26*Sunny 
```

If possible try doing the same for strings as well but only after making the stuff possible.

**Comment by naveensaigit** [comment]
I'm thinking of adding a function in `MarkovProcess` called `replace_with_index` which would do the following - 
```
def replace_with_index(self, condition):
        if isinstance(condition, Relational):
            if condition.rhs.is_symbol:
                try:
                    return Eq(condition.lhs, self.state_space.index(condition.rhs))
                except (NameError, ValueError) as e:
                    raise NameError('%s not found in the state space'%condition.rhs)
            else:
                return condition
        else:
            return condition
```
We can call it before computing the probability/expectation. Would this be fine?
I've implemented it and it gives the desired output
```
>>> from sympy.stats import DiscreteMarkovChain, TransitionMatrixOf, P, E
>>> from sympy import Matrix, MatrixSymbol, Eq, symbols
>>> T = Matrix([[0.5, 0.2, 0.3],[0.2, 0.5, 0.3],[0.2, 0.3, 0.5]])
>>> sunny, cloudy, rainy = symbols('Sunny, Cloudy, Rainy')
>>> Y = DiscreteMarkovChain("Y", [sunny, cloudy, rainy], T)
>>> P(Eq(Y[3], rainy), Eq(Y[1], cloudy)).round(2)
0.36
>>> E(Y[3], Eq(Y[1], cloudy))
0.38*Cloudy + 0.36*Rainy + 0.26*Sunny
```
Also, since we can't use strings as rhs of an equation, how do you plan to implement it for strings?

**Comment by czgdp1807** [comment]
> how do you plan to implement it for strings?

Strings won't be allowed if `index_of` is removed. The names of `Symbols` can be used as strings by the end user.

**Comment by czgdp1807** [comment]
You can raise a PR. We can test your approach there.
