### ISSUE TITLE
Integrate dyanamic symbols wrt time

### ISSUE THREAD

**Issue by sidhu1012** [sympy/sympy#20160]
On running this

from sympy.physics.vector import dynamicsymbols, Point, ReferenceFrame
t = dynamicsymbols._t
u = dynamicsymbols('u')
N = ReferenceFrame('N')
O = Point('O')
O.set_vel(N, u * N.x)
p = integrate(O.vel(N),(t,1,2))

This error rises:-

AttributeError                            Traceback (most recent call last)
<ipython-input-28-d36b4ee55c62> in <module>
      5 O = Point('O')
      6 O.set_vel(N, u * N.x)
----> 7 p = integrate(O.vel(N),(t,1,2))

~\Anaconda3\lib\site-packages\sympy\integrals\integrals.py in integrate(*args, **kwargs)
   1540         'manual': kwargs.pop('manual', None)
   1541         }
-> 1542     integral = Integral(*args, **kwargs)
   1543 
   1544     if isinstance(integral, Integral):

~\Anaconda3\lib\site-packages\sympy\integrals\integrals.py in __new__(cls, function, *symbols, **assumptions)
     85                 useinstead="the as_expr or integrate methods of Poly").warn()
     86 
---> 87         obj = AddWithLimits.__new__(cls, function, *symbols, **assumptions)
     88         return obj
     89 

~\Anaconda3\lib\site-packages\sympy\concrete\expr_with_limits.py in __new__(cls, function, *symbols, **assumptions)
    492 
    493     def __new__(cls, function, *symbols, **assumptions):
--> 494         pre = _common_new(cls, function, *symbols, **assumptions)
    495         if type(pre) is tuple:
    496             function, limits, orientation = pre

~\Anaconda3\lib\site-packages\sympy\concrete\expr_with_limits.py in _common_new(cls, function, *symbols, **assumptions)
     23     (function, limits, orientation). This code is common to
     24     both ExprWithLimits and AddWithLimits."""
---> 25     function = sympify(function)
     26 
     27     if isinstance(function, Equality):

~\Anaconda3\lib\site-packages\sympy\core\sympify.py in sympify(a, locals, convert_xor, strict, rational, evaluate)
    404     try:
    405         a = a.replace('\n', '')
--> 406         expr = parse_expr(a, local_dict=locals, transformations=transformations, evaluate=evaluate)
    407     except (TokenError, SyntaxError) as exc:
    408         raise SympifyError('could not parse %r' % a, exc)

~\Anaconda3\lib\site-packages\sympy\parsing\sympy_parser.py in parse_expr(s, local_dict, transformations, global_dict, evaluate)
   1006         code = compile(evaluateFalse(code), '<string>', 'eval')
   1007 
-> 1008     return eval_expr(code, local_dict, global_dict)
   1009 
   1010 

~\Anaconda3\lib\site-packages\sympy\parsing\sympy_parser.py in eval_expr(code, local_dict, global_dict)
    901     """
    902     expr = eval(
--> 903         code, global_dict, local_dict)  # take local objects in preference
    904 
    905     return expr

<string> in <module>

AttributeError: 'function' object has no attribute 'x'

**Comment by moorepants** [comment]
Integrating physics.vector.Vector objects is known not to work. What is the use case for this? It currently isn't implemented because there is no apparent need.

**Comment by sidhu1012** [comment]
> . What is the use case for this? 

Calculating work done by a particle , work energy theorem

**Comment by moorepants** [comment]
Only for the most trivial cases can you calculate work analytically. The entire premise of this packages is to formulate the equations of motion, which are ODEs or DAEs in time. Some of those can be expressions for power, which are then numerically integrated, just like the equations for determining the states. The only useful integrals, that can be computed analytically, are likely those for computing inertial quantities.

If you think there is a necessity to add functionality for calculations of work in an analytical fashion, please provide a full working example of this. You can use the current functionality to do this. Then show why being able to integrate a vector quantity is useful to reduce or replace the code you wrote in the example.

**Comment by sidhu1012** [comment]
Working example :- https://github.com/sidhu1012/Work-Energy-Theorem/blob/master/Work-energy%20theorem.ipynb

**Comment by sidhu1012** [comment]
Adding intgration to dynamin symblos can give backwards capability as
pos.dt -> vel, vel.dt -> acc
but
integrate(acc,t) wont give vel

**Comment by moorepants** [comment]
I looked at your example. It is a bit too simple for the vector/mechanics packages as these are setup to deal with general 3D rigid body motion. Solving the problem you show is more like a high school physics, which can be done with bare SymPy code. If you really need to use Vector, then Vector.magnitude() can get the scalar quantities you may need to calculate work. Only for the simplest examples will analytic integration work, so I don't see the point in supporting integration of Vector. Going to close this issue. Feel free to reopen if you develop a more pertinent need.
