### ISSUE TITLE
non-factorable expressions can cause dsolve to quit prematurely 

### ISSUE THREAD

**Issue by bigfooted** [sympy/sympy#20179]
The very first of the Kamke ODE's of first order, first degree fails:

```python
from sympy import Function,dsolve,Eq,Derivative,diff,symbols,factor_list
from sympy.abc import x

y=Function('y')(x)
a0,a1,a2,a3,a4 = symbols('a0, a1, a2, a3, a4')
ode1 = y.diff(x)-(a4*x**4 + a3*x**3 + a2*x**2 + a1*x + a0)**(-1/2)
print(dsolve(ode1,y))
```

> ~/anaconda3/lib/python3.8/site-packages/sympy/solvers/ode/single.py in _matches(self)
>     676         eq = eq.collect(f(x), func = cancel)
>     677         eq = fraction(factor(eq))[0]
> --> 678         roots = factor_list(eq)[1]
>     679         if len(roots)>1 or roots[0][1]>1:
>     680             for base,expo in roots:

This is caused by missing exception handling of factor_list in class Factorable(SingleODESolver)
If try .. except is placed around factor_list, dsolve continues and solves the ODE by direct integration.

 ```python
     try:
            roots = factor_list(eq)[1]
        except:
          return False 
```

**Comment by oscarbenjamin** [comment]
It seems that `factor_list` can not handle negative powers:
```julia
In [24]: factor_list(1/(1+x))                                                                                                                  
---------------------------------------------------------------------------
PolynomialError                           Traceback (most recent call last)
<ipython-input-24-b1aae42f8c5c> in <module>
----> 1 factor_list(1/(1+x))

~/current/sympy/sympy/sympy/polys/polytools.py in factor_list(f, *gens, **args)
   6274 
   6275     """
-> 6276     return _generic_factor_list(f, gens, args, method='factor')
   6277 
   6278 

~/current/sympy/sympy/sympy/polys/polytools.py in _generic_factor_list(expr, gens, args, method)
   6008 
   6009         if fq and not opt.frac:
-> 6010             raise PolynomialError("a polynomial expected, got %s" % expr)
   6011 
   6012         _opt = opt.clone(dict(expand=True))

PolynomialError: a polynomial expected, got 1/(x + 1)
```
The docstring for `factor_list` just says "Compute a list of irreducible factors of f." It's not clear to me whether it should be able to handle expressions like this or not.

If not then I guess `factor` should be used instead of `factor_list`.

**Comment by bigfooted** [comment]
Yes, factor returns the original expression instead of throwing an error, which is already better. Because of the limitation, I suspect that factor_list is used by functions that expect and only work on polynomials with positive powers.

factor just reorganizes the expression, so the result still needs to be split at the top-level multiplication operators (there is probably a nice command to get the first level operand and its arguments). 

So to make this work for more general cases and not potentially break other things, a local implementation of factor_list might be best I think.

**Comment by oscarbenjamin** [comment]
The docstring for `factor_list` should be changed to clarify its intended scope.

We can extract the factors after calling factor with:
```julia
In [1]: Mul.make_args(factor(x**2-1))                                                                                                          
Out[1]: (x + 1, x - 1)
```

**Comment by bigfooted** [comment]
This below works 
```python        
roots = [f.args if f.func.is_Pow else (f,1) for f in list(Mul.make_args(factor(eq)))]
```

**Comment by bigfooted** [comment]
Also, I think factor_list should be able to handle this expression in the first place. If it is not factorizable, it should return the original expression, like factor does. An expression similar to the above can also be placed in factor_list.

**Comment by oscarbenjamin** [comment]
I'm not sure if the intention for `factor_list` is to be a slim wrapper around the `Poly.factor_list` method:
```julia
In [1]: e = x**2 + x                                                                                                                           

In [2]: factor_list(e)                                                                                                                         
Out[2]: (1, [(x, 1), (x + 1, 1)])

In [3]: p = Poly(e, x)                                                                                                                         

In [4]: p                                                                                                                                      
Out[4]: Poly(x**2 + x, x, domain='ZZ')

In [5]: p.factor_list()                                                                                                                        
Out[5]: (1, [(Poly(x, x, domain='ZZ'), 1), (Poly(x + 1, x, domain='ZZ'), 1)])
```
If so then that's fine but the docstring should clarify the intended scope.

**Comment by oscarbenjamin** [comment]
> This below works

That looks good to me
