### ISSUE TITLE
Support multivariate expressions in DiscreteMarkovChain

### ISSUE THREAD

**Issue by naveensaigit** [sympy/sympy#20180]
We should be able to process queries of the type 
``` python
>>> T=Matrix([[0.4, 0.3, 0.3],[0.1, 0.4, 0.5],[0.5, 0.25, 0.25]])
>>> Y=DiscreteMarkovChain(Y, [0, 1, 2], T)
>>> P(Eq(Y[1], Y[2]), Eq(Y[3], 1))
>>> P(Gt(Y[1], Y[2]), Eq(Y[3], 1))
```
As discussed in https://github.com/sympy/sympy/pull/20150#issuecomment-700498420

**Comment by naveensaigit** [comment]
I have thought of the following approach. Please review @czgdp1807 
`n = no_of_state_spaces`

1. `P(Eq(Y[a], Y[b]), Eq(Y[c], k))`

    ``` python
    if c<=min(a,b):
        s=0
        for i in range(0, n):
            s+= P(Eq(Y[a], i), Eq(Y[b], i)) * P(Eq(Y[b], i), Eq(Y[c], k))
        print(s)
    else:
        Probability(Eq(Y[a], Y[b]))
    ```
    Complexity for this would be `O(2*n*time_for_normal_query)`

2. `P(Gt(Y[a], Y[b]), Eq(Y[c], k))`

    ``` python
    if c<=min(a,b):
        s=0
        for i in range(0, n):
            if i<=n//2:
                for j in range(0, i)
                    s+= P(Eq(Y[a], i), Eq(Y[b], j)) * P(Eq(Y[b], j), Eq(Y[c], k))
            else:
                s+=P(Eq(Y[a], i)
                for j in range(i, n):
                    s -= P(Eq(Y[a], i), Eq(Y[b], j)) * P(Eq(Y[b], j), Eq(Y[c], k))
        print(s)
    else:
        Probability(Gt(Y[a], Y[b]))
    ```
    Complexity for this would approximately be `O(2*n^2*time_for_normal_query)`

Once we do this, we can easily extend the code for Ge, Le and Lt

**Comment by czgdp1807** [comment]
I think other than `Eq` every other `Relational` object would require iterating through `state_space_size^2` values.

**Comment by naveensaigit** [comment]
Yes. Also, can it be implemented for `And`, `Or`? I couldn't think of anything that would work in polynomial time

**Comment by naveensaigit** [comment]
Should I start implementing the above code?

**Comment by czgdp1807** [comment]
> Should I start implementing the above code?

Sure. I think the only change needed is for the case `if(condition, Relational)`, rest depends on it.

**Comment by naveensaigit** [comment]
I was trying to add this when I encountered something  - 
```
>>> P(Eq(Y[10], 1), Eq(Y[1], Y[11]))
Matrix([
[0.285728345, 0.339271847, 0.374999808],
[0.285708662,  0.33929153, 0.374999808],
[0.285708662, 0.339291018,  0.37500032]])[Y[11], 1]
```
I am unable to understand how this matrix came about. Could you please explain? @czgdp1807

**Comment by czgdp1807** [comment]
Is that query valid? How can we interpret it? To me it seems like given that the state at time 11 equals that of time 1 then find the probability that state time 10 will be 1. Basically this means we want our process to decipher from both the future and the past which IMHO isn't expected from a Markov Process. This should have given an error.

**Comment by naveensaigit** [comment]
Yes. But what about this - 
``` python
>>> P(Eq(Y[10], 0), Gt(Y[1], Y[5]))
>>> Matrix([
[0.28745, 0.33767, 0.37488],
[0.28502,  0.3401, 0.37488],
[0.28502, 0.33978,  0.3752]])[Y[5], 0]
```
I think it will become complex if `RandomIndexedSymbol` exists both in `condition` and `given_condition`. We should probably limit the no. of RandomIndexedSymbols in the given_condition to 1.

**Comment by czgdp1807** [comment]
Even then in case of `Eq(Y[1], Y[5])`, what does it actually mean? Does this mean, `And(*[Eq(Y[1], i) & Eq(Y[5], i) for i in self._state_index])` Or, `Or(*[Eq(Y[1], i) & Eq(Y[5], i) for i in self._state_index])`. If former is the case then it really isn't possible as a chain can achieve only one state at one time and in the case of latter, it can be answered. I don't think such queries can be interpreted unambiguously. It's more like garbage in garbage out IMHO. We may not need to handle such cases by extra checks, let it be whatever it is.

**Comment by naveensaigit** [comment]
Ok then, just wanted to know if the answer is valid or not.

**Comment by czgdp1807** [comment]
> Can I assume that `given_condition` will have only a single `RandomIndexedSymbol`? That would clear the confusion I guess

Yes. Write it in the notes of the docstring as well.

**Comment by czgdp1807** [comment]
> Are there any other issues that are important to be fixed in `DiscreteMarkovChain`?

Not sure. For that more testing is needed in different scenarios. May be the sampling part for stochastic processes can be checked.



> If not, then I can work on `density()` to return entire probability density at time `t`. [#20150 (comment)](https://github.com/sympy/sympy/pull/20150#issuecomment-702597358)

Open a separate issue for this.

**Comment by naveensaigit** [comment]
Sure, I'll do that

**Comment by naveensaigit** [comment]
I was about to open an issue for this when I noticed #19012. This is definitely a super-set of what we want to achieve. I'll continue the discussion there
