### ISSUE TITLE
infinite recursion in nonlinsolve

### ISSUE THREAD

**Issue by keithbriggs** [sympy/sympy#20199]
Trying

`nonlinsolve([b],[ω[0],ω[1]])`

on

```
b=exp(1.0⋅ⅈ⋅(ω₀⋅t₀ + ω₁⋅t₁))+exp(1.0⋅ⅈ⋅(ω₀⋅t₁ + ω₁⋅t₀))
```

gives 

> 
RecursionError: maximum recursion depth exceeded in comparison

**Comment by keithbriggs** [comment]
Here is a MWE:

```
  t0,t1=sp.Symbol('t0'),sp.Symbol('t1')
  w0,w1=sp.Symbol('w0'),sp.Symbol('w1')
  sol=nonlinsolve([sp.exp(1j*(w0*t0+w1*t1))+sp.exp(1j*(w0*t1+w1*t0))],[w0,w1])
```

>   File "/usr/local/lib/python3.6/dist-packages/mpmath/libmp/libmpf.py", line 637, in mpf_gt
>     if s == fnan or t == fnan:
> RecursionError: maximum recursion depth exceeded in comparison

**Comment by MaqOwais** [comment]
This should be closed as this issue is resolved in https://github.com/sympy/sympy/pull/21255
