### ISSUE TITLE
DOC: spelling error in solveset

### ISSUE THREAD

**Issue by keithbriggs** [sympy/sympy#20198]
The documentation for solveset contains the spelling error "non linear" several times.   This should be "nonlinear".

**Comment by shitalmule04** [comment]
I would like to work on this issue

**Comment by Sc0rpi0n101** [comment]
Was this fixed with #20201 or are there any other instances @keithbriggs?

**Comment by shitalmule04** [comment]
@Sc0rpi0n101 , It is partially fixed. I am looking into it.

**Comment by keithbriggs** [comment]
I think that was all.

________________________________

**Comment by naveensaigit** [comment]
All occurences of "non linear" are removed from solveset. I think this can be closed now.
