### ISSUE TITLE
Using multipledispatch for handlers in assumptions module

### ISSUE THREAD

**Issue by JSS95** [sympy/sympy#20209]
Related to #20153 and #20148

As implemented in #20153 for polyadic predicate, we can use multipledispatch instead of handler classes for monadic predicates as well.

Benefits:
1. Handlers will be no longer dispatched by class "name", which is treacherous.
2. Instead of having multiple handlers registered in `Predicate.handlers` attribute, we can have only one handler and dispatch everything to it.

Please refer to #20153 to see how handlers will be implemented.

**Comment by JSS95** [comment]
Sorry for the meager explanation. This is still a draft in my head, and I will update after some trials.

**Comment by asmeurer** [comment]
This also offers a simpler path for users to register their own custom handlers.
