### ISSUE TITLE
Beam module, wrong sign in two integration steps

### ISSUE THREAD

**Issue by nopria** [sympy/sympy#20204]
I noticed that the first example at https://docs.sympy.org/latest/modules/physics/continuum_mechanics/beam_problems.html gives uncorrect results, but it seems there is a more general bug regarding **the sign of the integration of vertical loads**. As you can easily verify (see the code below), the shear **V** is calculated by integrating the vertical loads **q** without the needed sign change. In fact, regardless of user convention about coordinate system, the relation between V and q is **-q =dV/dx**, whereas the code seems to use **q=dV/dx**. This leads to wrong results, as in the above mentioned example and in the code below.

```python
from sympy import *
from sympy.physics.continuum_mechanics.beam import Beam
E,I = symbols('E,I')
b = Beam(1, E, I) # beam length=1
M,R = symbols('M,R')
b.apply_load(1,0,0) # uniform positive distributed vertical load=1
b.apply_load(M,0,-2) # add moment reaction at left end
b.apply_load(R,0,-1) # add force reaction at left end
b.bc_deflection.append((0,0)) # vertical displacement=0 constraint (cantilever beam fixed at left end)
b.bc_slope.append((0,0)) # rotation=0 constraint (cantilever beam fixed at left end)
b.solve_for_reaction_loads(M,R)
b.reaction_loads
b.plot_loading_results(subs={E: 20E9, I: 3.25E-6}) # the shear force diagram is wrong, it has positive slope instead of negative
```
![Figure_1-opt](https://user-images.githubusercontent.com/4848618/96190919-52b8cb80-0f43-11eb-9c8d-6a48416280bf.png)

# Follow up

After more investigations I discovered that there is one more bug: in other integrations the equations **V = dM/dx** and **EJ v'' = M** are used, whereas in at least one of the two there should be a negative sign. On which of the two to put the negative sign depends on the coordinate system. I prepared a table showing that:

![github-signes-table-opt](https://user-images.githubusercontent.com/4848618/96264151-2f823080-0fc4-11eb-86a6-93ee0efe68c3.png)

I think that the best way to quickly make the code working correctly is to choose the (**V = dM/dx**, **-EJ v'' = M**) option and explain in the docs that the user has NOT complete freedom in coordinate system choice.

In a quick and dirty fix attempt I made the following changes to `beam.py`:
- line 839 -->  return integrate(-self.load, x)
- line 1079 -->  slope_curve = integrate(-S.One/(E*I)*self.bending_moment(), x) + C3
- line 1177 -->  slope_curve = integrate(-self.bending_moment(), x) + C3

With the above corrections the first tests seem to give correct results, but before committing I guess someone more expert of the module should jump in the discussion.

Of course the documentation should be changed accordingly, to let the user know that only the last two coordinate systems (below in the table) are allowed.

To allow the user to choose also among the first 2 coordinate systems of the table above, an option should be added to the module, so the code would compute using (**-V = dM/dx**, **EJ v'' = M**) or (**V = dM/dx**, **-EJ v'' = M**) depending on which coordinate system the user wants to adopt.

**Comment by Psycho-Pirate** [comment]
[See this](https://github.com/sympy/sympy/pull/18886)
I did encounter this issue too and I believe that the above pr will solve it. The functions are fine. We just have to assign same signs to the forces acting in +Y direction and the moment acting along -Z direction. I have added a note regarding this and explaining it in the above pr.

**Comment by nopria** [comment]
It is not possible to fix the issue for all possible (righthand, of course) coordinate systems unless a specific option is added. Beam module must know in advance which one between (V = dM/dx, -EJ v'' = M) vs. (-V = dM/dx, EJ v'' = M) calculations to use, and that depends upon the coordinate system adopted by the user. The table above shows all the possible cases.

**Comment by Psycho-Pirate** [comment]
The functions use a right handed coordinate system and the moment is calculated about the rightmost point of the beam in every case. The user is given the freedom to select +ve or -ve signs for forces acting in the +y or -ve y direction. However the user should note that:
1. If positive sign is selected for forces acting along +Y direction then the moment acting along -Z direction should also have the positive sign.
2. If negative sign is selected for forces acting along +Y direction then the moment acting along -Z direction should also have the negative sign.
Same goes for forces along -Y and moments along +Z.
I came to this conclusion after finding out that the functions calculate moment about the rightmost point of the beam.

If the above criteria is fulfilled and moments and forces are inputted considering them, the code gives the right answer everytime.
Some examples are wrong currently because the PR i made hasnt been merged yet.

**Comment by nopria** [comment]
I can't follow your explanation because I don't know which axes Y and Z are for you. Which is the horizontal and which is the vertical axis? Habits are very different over the world.

However there are only 2 kind of coordinate systems (i.e. sign conventions) options which the code must deal with:
- coordinate systems having positive rotation that brings the positive **horizontal** axis **towards** the positive **vertical** axis, which must use the equations **-V = dM/dx**   and   **EJ v'' = M**
- coordinate systems having positive rotation that brings the positive **vertical** axis **towards** the positive **horizontal** axis, which must use the equations **V = dM/dx**   and  **-EJ v'' = M**

This is very clear from the table I posted.
With "vertical" and "horizontal" axis I mean the 2 axes coplanar with the external forces (and the sheet of paper).

I hope that you choose to follow the latter option, since all the books I know use that kind of coordinate system and sign convention. If this is the case, the only advice the user should really receive is to **stick to a coordinate system that brings the positive vertical axis towards the positive horizontal axis**.

**Comment by Psycho-Pirate** [comment]
I think we both are saying the same thing.


> 
> 
> I can't follow your explanation because I don't know which axes Y and Z are for you. Which is the horizontal and which is the vertical axis? Habits are very different over authors and over the world.

I am considering x axis to be on the horizontal with positive x axis on the right and positive y to be pointing upwards and positive z coming out of the page.
> 
>     1. If positive sign is selected for forces acting along +Y direction then the moment acting along -Z direction should also have the positive sign.
> 
>     2. If negative sign is selected for forces acting along +Y direction then the moment acting along -Z direction should also have the negative sign.
>        Same goes for forces along -Y and moments along +Z.
What I meant by this is that if the **user** considers the rotation that brings the **positive vertical axis** towards the **positive horizontal axis** as **positive**, then the **user** should also consider the force acting along the **upward vertical** direction as **positive** as well. If this rotation is considered to be negative then this force should also be negative.

Same goes for the rotation that brings the **positive horizontal axis** towards the **positive vertical axis** and the force acting in **downward vertical**. These should have the same signs as well.

It doesn't matter what coordinate system the user uses, the only thing that should be kept in mind is that:
Considering the beam lying across the horizontal axis:
1. **Clockwise moment and Upward force** should have the same sign.
2. **Anticlockwise moment and Downward force** should have the same sign and this sign should be opposite to the one shared by Clockwise moment and Upward force.

As long as these are followed, the user is free to assign positive or negative signs and the code will always give the correct answer.

**Comment by nopria** [comment]
Let's calm down. This is a subject apparently simple, but it's easy to fall in error.

First of all I would like to agree on the fact that, for the bi-dimensional beam, there is complete equivalence between coordinate system and sign convention for internal forces. When you choose a coordinate system, you automatically choose the sign convention for internal forces, and viceversa, when you choose a sign convention for internal forces, you automatically choose a coordinate system. I hope we agree on that. Such equivalence is shown in my table.

I'm sorry for the long post, I know how hard is to follow other people reasonings, and it took me a long time to write it, but for the beam module this is a critical issue which needs to be properly investigated and complete consensus must be reached about it.

For brevity and clarity, below I will use the "+" symbol in place of the word "positive".

> I am considering x axis to be on the horizontal with positive x axis on the right and positive y to be pointing upwards and positive z coming out of the page.
> 1. If positive sign is selected for forces acting along +Y direction then the moment acting along -Z direction should also have the positive sign.
> 2. If negative sign is selected for forces acting along +Y direction then the moment acting along -Z direction should also have the negative sign. Same goes for forces along -Y and moments along +Z.

Here we are saying the same thing (but such explanation is really complex, I wouldn't use it in the documentation). Therefore I believe the code will use the equations **V = dM/dx** and **-EJ v'' = M**.

> What I meant by this is that if the user considers the rotation that brings the positive vertical axis towards the positive horizontal axis as positive, then the user should also consider the force acting along the upward vertical direction as positive as well. If this rotation is considered to be negative then this force should also be negative.

This is not completely correct. The 4th coordinate system in my table is a counter-example of +rotation that brings the +vertical axis towards the +horizontal axis, where where vertical axis is **downward** and the same equations above mentioned are valid.

> Same goes for the rotation that brings the positive horizontal axis towards the positive vertical axis and the force acting in downward vertical. These should have the same signs as well.

This is not correct. The 2nd coordinate system in my table "brings the +horizontal axis towards the +vertical axis and the force acting in downward vertical", but in this case the other set of equations must be used; **-V = dM/dx** and **EJ v'' = M**.

> 1. Clockwise moment and Upward force should have the same sign.
> 2. Anticlockwise moment and Downward force should have the same sign and this sign should be opposite to the one shared by Clockwise moment and Upward force.

I understand what you mean, indeed this is a description of the last two coordinate systems in my table, but I think the best way to describe this category of coordinate systems is "the +rotation brings the +vertical axis towards the +horizontal axis", or, in terms of internal forces, I would just plainly describe the 2 possible choices:
- upward forces and clockwise moments are positive, or
- downward forces and counterclockwise moments are positive

Finally I would like to stress again on the importance of the table I posted, which I believe is correct and is a very concise and clear way to summarize the subject.

**Comment by Psycho-Pirate** [comment]
I still believe that the code is functional if we take care while assigning signs.
It would be really helpful if you could give some example in which the code gives wrong output and how your fix can help.
Maybe there is a bigger problem which I'm not able to see, an example will really help me understand.

**Comment by nopria** [comment]
I have "sympy   1.6.2    py37hc8dfbb8_1   conda-forge" in my conda environment, is it ok or I should install the master version to make the tests? And how can I install the master? Sorry I'm new to Github.

**Comment by Psycho-Pirate** [comment]
It should be fine, you can always refer to the [installation guide](https://docs.sympy.org/latest/install.html#installation) if you get stuck.

**Comment by nopria** [comment]
The simplest cantilever example I gave at beginning still gives wrong results. With the chosen coordinate system displayed below and a positive uniform vertical load, shear is positive and moment is negative, whereas `sympy` gives a negative shear and a positive moment. Reactions are correct.

![esempio1_sympy-opt](https://user-images.githubusercontent.com/4848618/96725806-98e1b500-13b1-11eb-8a25-59b32e849d78.png)

**Comment by Psycho-Pirate** [comment]
Like I said before, you have to be careful about signs while entering values.
The code provides the user the freedom to choose sign convention. This means that you can assign + sign to either upward or downward force.
```python
b.apply_load(1,0,0) 
b.apply_load(M,0,-2) 
b.apply_load(R,0,-1)
```
When the above lines are entered, the code assumes that the **uniform distributed load(udl)** and the **reaction force R**, are acting along the **same direction**. Note that this direction can be either upward or downward.
When the function `solve_for_reaction_loads` is called, the code finds out that the reaction force is acting in **opposite direction**.
Since the given udl was positive and reaction force R is acting opposite to that, the value of R becomes negative. Hence the moment comes positive too.
```python
print(b.reaction_loads)
{M: 1/2, R: -1}
```
In order to get correct results, you should input the force as `b.apply_load(-1,0,0)`. Basically if your force is acting along the reaction force, input them with the same signs. If they act along opposite direction, either input the force with negative sign or the reaction force with negative sign. 

I hope this clears it out.

**Comment by nopria** [comment]
> When the above lines are entered, the code assumes that the uniform distributed load(udl) and the reaction force R, are acting along the same direction. Note that this direction can be either upward or downward.

Yes, of course, it could not be otherwise. In fact the positive direction in my example is downward, so load=1 is a downward force, and the reaction is negative, so R=-1 is un upward force. That's all correct.

> In order to get correct results, you should input the force as b.apply_load(-1,0,0).

I already get correct results regarding reactions, I don't understand why you say that I should change the sign of loads.

> Basically if your force is acting along the reaction force, input them with the same signs. If they act along opposite direction, either input the force with negative sign or the reaction force with negative sign.

I don't understand what you mean here. Reactions are unknowns, I can't input my loads depending on unknowns. I just expect R reaction to be (given the coordinate system of my example) downward if R>0 and upward if R<0. As it comes out, R=-1 so it's upward and that's correct. 

As I said, the problem in my example are not the reactions, which are correct, but the **shear force sign** (I get V<0, while, given the signs convention, it's clearly V>0). And this problem is due to the fact that the code, as far as I understand, computes the shear force as **q=dV/dz** (line 839 --> `return integrate(self.load, x)`) instead of **-q=dV/dz** (`return integrate(-self.load, x)`).

**Comment by Psycho-Pirate** [comment]
> I don't understand what you mean here. Reactions are unknowns, I can't input my loads depending on unknowns. I just expect R reaction to be (given the coordinate system of my example) downward if R>0 and upward if R<0. As it comes out, R=-1 so it's upward and that's correct.

Yeah, you are right, i guess i misunderstood it.

> As I said, the problem in my example are not the reactions, which are correct, but the **shear force sign** (I get V<0, while, given the signs convention, it's clearly V>0). And this problem is due to the fact that the code, as far as I understand, computes the shear force as **q=dV/dz** (line 839 --> `return integrate(self.load, x)`) instead of **-q=dV/dz** (`return integrate(-self.load, x)`).

I get it now, I think this should fix it.

> To allow the user to choose also among the first 2 coordinate systems of the table above, an option should be added to the module, so the code would compute using (-V = dM/dx, EJ v'' = M) or (V = dM/dx, -EJ v'' = M) depending on which coordinate system the user wants to adopt.

Regarding this, shouldn't the code be independent of the coordinate systems chosen by the user. Shouldn't  **(V = dM/dx, -EJ v'' = M)** be used regardless of the sign convention adopted by the user, just like **-q=dV/dz** ?


Please have a look @jashan498 @moorepants @ishanaj

**Comment by nopria** [comment]
> Regarding this, shouldn't the code be independent of the coordinate systems chosen by the user. Shouldn't (V = dM/dx, -EJ v'' = M) be used regardless of the sign convention adopted by the user, just like -q=dV/dz ?

Unfortunately no. The code cannot be completely independent of sign conventions, because it uses the equations **±V = dM/dx** and **±EJ v'' = M** whose sign depends on the coordinate system chosen by the user (my table above shows the correspondence). Such correspondence, if you do the math, comes directly from equilibrium analysis.

If you are thinking "why other structural softwares are not taking this into account", I guess the reason is that usually a structural software does not give to users complete freedom about coordinate system, therefore the correct sign of the equations can be set in advance.

If `beam` module wants to give complete freedom to the user (which I think is a good and rare feature), it must know in advance if the chosen coordinate system is such that:
- the positive rotation brings the positive **vertical** axis towards the positive **horizontal** axis (vertical --> horizontal), or
- the positive rotation brings the positive **horizontal** axis towards the positive **vertical** axis (horizontal --> vertical),

In terms of internal forces those 2 categories of coordinate systems could be described as:
- _on the right hand side of a beam section_, a positive shear force gives a **negative** moment, or
- _on the right hand side of a beam section_, a positive shear force gives a **positive** moment.

**Comment by nopria** [comment]
Since I'm not expert of GitHub, I just would like to know what happened to PR#20431 which would solve this horrible issue in Beam module (currently giving totally wrong results). Thanks.
