### ISSUE TITLE
[Question] Shouldn't Sympy array support broadcasting as numpy array does?

### ISSUE THREAD

**Issue by sidhu1012** [sympy/sympy#20224]
Currently Sympy arrays support operations only with arrays, otherwise they give error.

Example:-

A = Array([[1, 2], [3, 4]])
A + 2 
Would give error 

Numpy gives Array([3,4],[5,6]) #Adds 2 to every element

Shouldn't  the same thing happen in sympy  Array also?

**Comment by oscarbenjamin** [comment]
Although that sort of thing can be useful in numpy it is conceptually a bit messy. It's not mathematically valid to add a scalar to an array. If we were going down that road we'd end up thinking about the whole broadcasting arrangement as well.

**Comment by sylee957** [comment]
I saw some stuff in array_utils that deals with elementwise addition, but I don't think that they are documented and I'm not sure how it can be describe other operators like elementwise multiplications.

**Comment by sidhu1012** [comment]
I think adding broadcasting compatibility to arrays would be a nice addition as arrays currently support addition to arrays only that too of similar shape.

But it again raises the same question, what should matrix + array or matrix * array give? An array or a matrix?

**Comment by oscarbenjamin** [comment]
> But it again raises the same question, what should matrix + array or matrix * array give? An array or a matrix?

To me that raises the question why any of these things should be supported. SymPy arrays do not really have the same uses as numpy arrays. There needs to be a reason to add these features or otherwise it is best not to add them.

**Comment by czgdp1807** [comment]
I don't know about this but it would be great to have the automatic casting of arrays to matrices. In fact, the differentiation of dY/dX where X and Y both are matrices is amazing. In fact, it would be great to have a feature like reduce_sum, reduce_mean for multi-dimensional arrays in SymPy. This way, it would be easy to compare results with other automatic differentiation libraries which dY/dX(like autodiff in tensorflow). @Upabjojr Any thoughts?

P.S. What is the algorithm that has been used to support, things like dY/dX. Especially the invariant of this algorithm like, if Y = W*X*X, if we make an expression tree for this, it will translate to Y = Z*X where Z = W*X. So if we have dZ/dX then how will we propagate this information to dY/dX? Just curious how SymPy handles arbitrary expressions involving matrices and then generating derivatives for those expressions.

**Comment by Upabjojr** [comment]
The expression
```python
A = Array([[1, 2], [3, 4]])
A + 2
```

can be expressed as
```python
from sympy.tensor.array.expressions import OneArray
A = Array([[1, 2], [3, 4]])
A + 2*OneArray(2, 2).as_explicit()
```

We don't need broadcasting. Broadcasting can laready be dealt with `tensorproduct` and `OneArray`.
