### ISSUE TITLE
Runtime increases exponentially with exponent for particular formulas  >>>sign(((a * b) ** 10))

### ISSUE THREAD

**Issue by ducktalez** [sympy/sympy#20225]
I recently realized that my program needs forever to evaluate a formula.
The problem seems to be within the following (reduced example)-expression and the runtime increases exponentially with the size of the exponent.

```
from sympy import sympify
a = sympify('sign(((a * b) ** 2))')           # time: <1s
b = sympify('sign(((a * b) ** 200))')         # time: ~10s
c = sympify('sign(((a * b) ** 400))')         # time: >120s
```

Is there a solution to this, does anyone know why that occurs?
I currently deactivated sympify, no time to debug this now...

**Comment by ducktalez** [comment]
Ah, that is actually a very accurate solution to the problem... Thank you very much!

**Comment by oscarbenjamin** [comment]
I'm reopening because this should be fixed in sympy and then the issue can be closed.
