### ISSUE TITLE
Arbitrary Functions

### ISSUE THREAD

**Issue by ieshaan12** [sympy/sympy#20243]
I was thinking we could have arbitrary functions implemented such that 

<a href="https://www.codecogs.com/eqnedit.php?latex=y&space;=&space;\begin{cases}&space;&&space;0,&space;\text{&space;if&space;}&space;x&space;\leq&space;0&space;\\&space;&&space;x,&space;\text{&space;if&space;}&space;0&space;<&space;x&space;\leq&space;10&space;\\&space;&&space;x^{2},&space;\text{&space;if&space;}&space;x&space;>&space;10&space;\end{cases}" target="_blank"><img src="https://latex.codecogs.com/gif.latex?y&space;=&space;\begin{cases}&space;&&space;0,&space;\text{&space;if&space;}&space;x&space;\leq&space;0&space;\\&space;&&space;x,&space;\text{&space;if&space;}&space;0&space;<&space;x&space;\leq&space;10&space;\\&space;&&space;x^{2},&space;\text{&space;if&space;}&space;x&space;>&space;10&space;\end{cases}" title="y = \begin{cases} & 0, \text{ if } x \leq 0 \\ & x, \text{ if } 0 < x \leq 10 \\ & x^{2}, \text{ if } x > 10 \end{cases}" /></a>

Is there any data structure to implement this kind of stuff, where no particular order is followed? I'd be more than willing to contribute towards this!

**Comment by oscarbenjamin** [comment]
Are you familiar with `Piecewise`:
```julia
In [1]: y = Piecewise((0, x<=0), (x, (0<x)&(x<=10)), (x**2, x>10))

In [2]: y
Out[2]: 
⎧0   for x ≤ 0 
⎪              
⎪x   for x ≤ 10
⎨              
⎪ 2            
⎪x   otherwise 
⎩              
```
