### ISSUE TITLE
Expression with square root doesn't simplify well

### ISSUE THREAD

**Issue by saidctb** [sympy/sympy#20251]
consider the following expression

```
from sympy import sqrt, Symbol

x1, x2 = Symbol('x1',positive=True,real=True), Symbol('x2',positive=True,real=True)     

e = sqrt(-x1 + sqrt(x1**2 + x2**2))*(x1 + sqrt(x1**2 + x2**2))/x2            

e.simplify()                                                                            
sqrt(-x1 + sqrt(x1**2 + x2**2))*(x1 + sqrt(x1**2 + x2**2))/x2

(e**2).simplify()                                                                       
x1 + sqrt(x1**2 + x2**2)
```
but this expression simplifies well

```
(sqrt(-x1 + sqrt(x1**2 + x2**2))*sqrt(x1 + sqrt(x1**2 + x2**2))/x2).simplify() == 1
True
```

what I expect is to have 
```
e.simplify() == sqrt(x1 + sqrt(x1**2 + x2**2))
```

**Comment by coproc** [comment]
The minimal polynomial can help here:
```python
>>> x = Symbol('x')
>>> p = minpoly(e, x); p
x**4 - 2*x**2*x1 - x2**2
>>> solve(p, x)
[-sqrt(x1 - sqrt(x1**2 + x2**2)), sqrt(x1 - sqrt(x1**2 + x2**2)), -sqrt(x1 + sqrt(x1**2 + x2**2)), sqrt(x1 + sqrt(x1**2 + x2**2))]
```
The correct term can be chosen manually ... See also #19726. Maybe the function `simplify_term_of_radicals` proposed there would also work here.

**Comment by saidctb** [comment]
> The minimal polynomial can help here:
> 
> ```python
> >>> x = Symbol('x')
> >>> p = minpoly(e, x); p
> x**4 - 2*x**2*x1 - x2**2
> >>> solve(p, x)
> [-sqrt(x1 - sqrt(x1**2 + x2**2)), sqrt(x1 - sqrt(x1**2 + x2**2)), -sqrt(x1 + sqrt(x1**2 + x2**2)), sqrt(x1 + sqrt(x1**2 + x2**2))]
> ```
> 
> The correct term can be chosen manually ... See also #19726.

thanks for your answer
