### ISSUE TITLE
Information Theory Measures

### ISSUE THREAD

**Issue by naveensaigit** [sympy/sympy#20286]
It would be really good for the `stats` module to have functions to calculate self-information, entropy, Kullback-Leibler divergence, etc. Currently, there are a lot of problems related to `H` in stats. Some of them are - 
``` python
>>> from sympy import *
>>> from sympy.stats import *
>>> n,p=symbols('n p')
>>> B=Binomial('B', n, p)
>>> H(B)
AttributeError: 'Density' object has no attribute 'values'

>>> m, s = symbols('m s')
>>> N=Normal("N", m, s)
>>> H(N)
Hangs
```
[Introduction to Information Theory](https://colab.research.google.com/github/d2l-ai/d2l-en-colab/blob/master/chapter_appendix-mathematics-for-deep-learning/information-theory.ipynb)

**Comment by evatiwari** [comment]
I would like to take a crack at it, atleast with the errors given by ```H```. Can somebody guide me regarding the same?

**Comment by naveensaigit** [comment]
I observed that `H` is really slow for continuous distributions when the parameters are symbolic as it applies the definition`H(X) = E[-log(P(x))]`. What if we do use the closed form of entropy for distributions where it is known and then proceed to integrate/sum if this is not available? For eg, if mu and sigma are known, the current definition will do. Else, we can use the expression for entropy of normal distribution which is `0.5*log(2*pi*e*sigma**2)`. @czgdp1807 What do you think?

**Comment by czgdp1807** [comment]
> What if we do use the closed form of entropy for distributions where it is known and then proceed to integrate/sum if this is not available?

I did this according to https://github.com/sympy/sympy/pull/15693#issuecomment-458133155 

IMO, using the existing knowledge will speed things up but it will require a lot of places to be modified i.e., increasing in maintenance burden. The more important question is, "Do we really need `H` to be fast for the use case you are suggesting?". Though what about other cases, i.e., when the parameters are numerical? Is `H` able to produce results in reasonable time?

**Comment by czgdp1807** [comment]
> I would like to take a crack at it, atleast with the errors given by `H`. Can somebody guide me regarding the same?

@evatiwari Sure. The bug in the OP seems to be related to `pdf.values` which needs to be updated according to the new API of `Density`.
https://github.com/sympy/sympy/blob/dfcc2839de10ab80ce2a12fc3b4b0b0a02110808/sympy/stats/rv_interface.py#L137

**Comment by czgdp1807** [comment]
> self-information, entropy, Kullback-Leibler divergence,

All such measures can go to `rv_interface.py`.

**Comment by naveensaigit** [comment]
> The more important question is, "Do we really need `H` to be fast for the use case you are suggesting?". Though what about other cases, i.e., when the parameters are numerical? Is `H` able to produce results in reasonable time?

The numerical performance is quite good, but sympy being a symbolic library might be expected to give decent results even if the same methods are called symbolically.

**Comment by czgdp1807** [comment]
For producing symbolic results, we need integrate feature of SymPy which may or not be efficient. It hangs because integration is difficult with exponential functions. We need more opinions on this. @Upabjojr @jksuom

**Comment by Upabjojr** [comment]
> What if we do use the closed form of entropy for distributions where it is known and then proceed to integrate/sum if this is not available?

We have already the possibility to add pre-computed results for CDF, quantiles and moments. For example, if you define a method `_cdf` returning a value different than `None` in a distribution class, then the returned value will be considered the pre-computed CDF and the integration will be skipped.

**Comment by czgdp1807** [comment]
We may need to do the same for `entropy`. So we can do it, the reason why I am afraid to not do it is because, of the burden it will introduce and since the use case is only limited to very few CRVs whose PDF have exponential and all the parameters are symbolic. If more practical cases(examples from statistical literature where entropy is applied) can be found out where we need usage of some pre-computed results then we can surely go for this design change.

**Comment by evatiwari** [comment]
I made the following changes to https://github.com/sympy/sympy/blob/dfcc2839de10ab80ce2a12fc3b4b0b0a02110808/sympy/stats/rv_interface.py#L136
. Please let me know if I have understood the problem correctly here.
```
if isinstance(pdf, dict):
            return sum([-prob*log(prob, base) for prob in pdf.values()])
```
I did it since the function doit() in the Density class returns a dict itself
https://github.com/sympy/sympy/blob/425353e982439dc64f3d33876cce291aac628ed8/sympy/stats/rv.py#L837

**Comment by czgdp1807** [comment]
May be opening a PR would be better to see how these changes will work. Or you can test locally before opening a PR,

```python
>>> import sympy
>>> sympy.test("/home/czgdp1807ssd/sympy_project/sympy/sympy/stats")
```

**Comment by evatiwari** [comment]
@czgdp1807  Thanks a lot, I was clueless about what tests to run since test_rv.py did not give me any affirmation.

**Comment by evatiwari** [comment]
The above PR only solved the issue with entropy with respect to Binomial, but when tried for Normal distribution, it still hangs, and on interrupting, the errors are as follows :
```
KeyError: log(sqrt(2)*exp(-(N - m)**2/(2*s**2))/(2*sqrt(pi)*s))
```
and
```
sympy.polys.polyerrors.PolynomialError: log(sqrt(2)*exp(-(N - m)**2/(2*s**2))/(2*sqrt(pi)*s)) contains an element of the set of generators.
```
I will look into this and try fixing it, any inputs are appreciated.
