### ISSUE TITLE
[bug] subs option to evalf isn't working for sets

### ISSUE THREAD

**Issue by amy12xx** [sympy/sympy#20291]
Evalf does not seem to work on solveset. 

Code to replicate:
```
from sympy.stats import Uniform, cdf
from sympy import Symbol, Eq, solveset, solve

x = Symbol("x")
a = Symbol("a")
b = Symbol("b")

D = Uniform("d", a, b)
F_x = cdf(D)(x)

u = Symbol("u")
expr = solveset(Eq(F_x, u), x)
expr.evalf(subs={u:0.6, a: 0, b: 2})
>> returns {a - u*(a - b)}
```

If instead I use solve, it works:

```
expr = solve(Eq(F_x, u), x)[0]
expr.evalf(subs={u:0.6, a: 0, b: 2})
>> returns 1.20000000000000
```

**Comment by Maelstrom6** [comment]
Looks like `Set.evalf` with a subs argument does not work. That is, `FiniteSet(a).evalf(subs={a: 1})` returns `FiniteSet(a)`. As a workaround for now, I suggest you do `expr.subs({u: 0.6, a: 0, b: 2}).evalf()`.

I'll have a PR out as soon as I know my changes don't break the build somewhere else.

Note that between your version and master, that cdf has become piecewise. SymPy is unable to solve for `x` and just throws an error. Hopefully by 1.8, there will be no more piecewise pdf's, pmf's and cdf's.

**Comment by amy12xx** [comment]
Thanks, yes I have used the evalf() on the solve output to proceed.
