### ISSUE TITLE
Wrong result in elliptic_pi() - Legendre complete elliptic integral of the third kind

### ISSUE THREAD

**Issue by rpoleski** [sympy/sympy#20290]
I'm calculating elliptic integral of the 3rd kind and I'm getting a result that differs from calculations using other packages:

```python
import sympy
print(sympy.functions.special.elliptic_integrals.elliptic_pi(0.011113210074206086, 0.009829707966223095))
1.58351233460505
```

I have sympy v1.0 and 1.6.2 on different computers and they both give this result. I've checked the calculation in other places 
([here](https://keisan.casio.com/exec/system/1244988714), [here](https://calcresource.com/eval-elliptic3.html), and after changing convention k vs sqrt(k) [here](https://functions.wolfram.com/webMathematica/FunctionEvaluation.jsp?name=EllipticPi3)) and the result is:
`1.5796363`
Does anyone know what's the cause of the discrepancy? Is there other python package that gives correct result?

**Comment by jksuom** [comment]
The parameters of `elliptic_pi` in the two other places above are `n` and `k` while in SymPy they are `n` and `m` where `m = k**2`. Hence the results will be different if the same parameter values are given in all cases.

**Comment by oscarbenjamin** [comment]
@rpoleski does that answer your question?

**Comment by rpoleski** [comment]
Yes. Thanks.
