### ISSUE TITLE
Update docs Makefile to use sphinx-build -M

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#20313]
If you run sphinx-quickstart with a recent version of Sphinx, it generates a much simpler Makefile than the one used by SymPy, because all the logic is in Sphinx itself behind the `-M` flag. We should update our Makefile to use this. This might not be straigthforward, since we have a lot of custom stuff in our Makefile that needs to be maintained. We should make sure all the make targets continue to work after doing this. 

See also this discussion https://github.com/sympy/sympy/pull/20309#discussion_r509638954

**Comment by sylee957** [comment]
I think that almost all the options were options were customized and I'm not sure all the options like `htmlapi, web, htmlhelp, livehtml, cheatsheet, texinfo, info, man` were used or working any more.

**Comment by asmeurer** [comment]
Duplicate of #20313
