### ISSUE TITLE
Issue while using trigsimp()

### ISSUE THREAD

**Issue by KKVANONYMOUS** [sympy/sympy#20325]
While going through `trigsimp()` I encountered an issue.

The following code works successfully as expected
```
>>> from sympy import *
>>> x= Symbol('x')
>>> y=Symbol('y')
>>> expr=cos(x)**2-sin(y)**2+1
>>> trigsimp(expr)
cos(x)**2 + cos(y)**2
```
But, this one yields `cos(x)**2 - cos(y)**2 + 1` rather than `cos(x)**2 + sin(y)**2`
```
>>> expr=cos(x)**2-cos(y)**2+1
>>> trigsimp(expr)
cos(x)**2 - cos(y)**2 + 1
```
Any idea where I am going wrong ?

**Comment by akshatsood2249** [comment]
Hey @KKVANONYMOUS  I believe this issue is arising as you are using an updated version of `trigsimp` , in order to solve it use `trigsimp(exp, method="old")` to access the old version. It produces the correct results.

**Comment by KKVANONYMOUS** [comment]
ohhk, Thank You so much
