### ISSUE TITLE
gram schmidt bug `def _orthogonalize(cls, *vecs, **kwargs):` at line 107 + fix

### ISSUE THREAD

**Issue by alfie-nsugh** [sympy/sympy#20334]
I tried to orthogonalise 2 complex vectors but it gave me the wrong answer but I found out where the mistake was:
it used to say

- `def project(a, b):
        return b * (a.dot(b, hermitian=True) / b.dot(b, hermitian=True))`
But it should be
- `def project(a, b):
        return b * (b.dot(a, hermitian=True) / b.dot(b, hermitian=True))`

(In the file subspaces.py in the function: `def _orthogonalize(cls, *vecs, **kwargs):` at line 107.)

I found the mistake when orthogonalising 
`v1 = Matrix([1,I,0])
v2 = Matrix([I,0,-I])`
with the code in the first bullet point you get this:

`v1 = Matrix([1,I,0])
v2 = Matrix([I,0,-I])
W = [v1,v2]
GS = GramSchmidt(W)`

with GS= [Matrix([
[1],
[I],
[0]]), Matrix([
[3*I/2],
[ -1/2],
[   -I]])]
but these two vectors multiplied with the standard complex inner product you get 2i which is unequal to zero.

And with code in the second bullet point you do get zero hence they are orthogonal. 
In the slides of my university textbook the formulas correspond to code in the second bullet point:
![img](https://user-images.githubusercontent.com/40834779/97086834-16156000-1626-11eb-85df-0de8297e0f2e.png)
The formula I denoted in red being the formula I'm refering to. I'm a little unfamiliar with github, but I do want to contribute by making this software better since I really like sympy.

I hope what I wrote down is sort of readable and convincing enough for someone to fix this problem.

**Comment by sylee957** [comment]
I think that QRdecomposition gives the correct result 
I don't see any good reason that orthogonalize had to be implemented differently than QRdecomposition, so if normalize keyword can be comprehended for QRdecomposition, it can be better to reuse the QRdecomposition for this.

**Comment by sylee957** [comment]
I can't see the difference in your example, but maybe the ordering of the dot product `a.dot(b, hermitian=True)` should be reversed in this case

**Comment by alfie-nsugh** [comment]
Apologies, I edited the post, the dot product needs to be switched around in order to get orthogonal vectors in this case is what I meant as well.
