### ISSUE TITLE
Link in "Introduction to contributing" not working

### ISSUE THREAD

**Issue by akshatsood2249** [sympy/sympy#20343]
The link which is supposed to redirect the user to the `architecture` page [here](https://github.com/sympy/sympy/wiki/Introduction-to-contributing#peruse-the-documentation) is not working and says "page not found".

**Comment by rishabhvarshney14** [comment]
guide.html is not present in [sympy_doc](https://github.com/sympy/sympy_doc) in version [1.6](https://github.com/sympy/sympy_doc/tree/gh-pages/1.6) and [latest](https://github.com/sympy/sympy_doc/tree/gh-pages/latest) or [dev](https://github.com/sympy/sympy_doc/tree/gh-pages/dev) but it is present in [1.5](https://github.com/sympy/sympy_doc/blob/gh-pages/1.5/guide.html). 
Maybe including it in latest and dev will fix this.
[Here](https://web.archive.org/web/20200403130424/https://docs.sympy.org/latest/guide.html) is the archive of the page.

**Comment by akshatsood2249** [comment]
Ok got it Thank You !!
