### ISSUE TITLE
Wrong result for conditional probability

### ISSUE THREAD

**Issue by 4rozenwolves** [sympy/sympy#20354]
Sympy seems to give wrong result for the following problem:

On 1 day in 1000, there is a fire and the fire alarm rings.
On 1 day in 100, there is no fire and the fire alarm rings (false alarm)
On 1 day in 10,000, there is a fire and the fire alarm does not ring (defective alarm).
On 9,889 days out of 10,000, there is no fire and the fire alarm does not ring.
If the fire alarm rings, what is the (conditional) probability that there is a fire?
Written p(there is a fire | fire alarm rings)

I solve it as:
X = Bernoulli('X', S(1)/1000 + S(1)/10000)
Y = Bernoulli('Y', S(1)/1000 + S(1)/100)
P(Eq(X, 1), Eq(Y, 1))
  11 
─────
10000

which is wrong, the correct answer is:
S(1)/1000 / (S(1)/1000 + S(1)/100)
1/11

**Comment by oscarbenjamin** [comment]
The result from sympy is correct. Since X and Y are independent the probability `P(X=1|Y=1)` is just equal to `P(X=1)` which is `11/10000`.

**Comment by 4rozenwolves** [comment]
Thank you for the answer.
Can you tell me how I am supposed to solve the problem correctly?

**Comment by oscarbenjamin** [comment]
We want to know `P(B | A)` which is `P(A & B) / P(A)`. We know `P(A & B)` and `P(A) = P(A & B) + P(A & ~B)`  so
```
P(B | A) = (1/1000) / (1/1000 + 1/100) = 1/11
```
There is no way in sympy to work with events rather than random variables so it isn't possible to ask sympy to simply solve a problem like this for you.
