### ISSUE TITLE
Outdated/wrong examples for plotting geometric structures

### ISSUE THREAD

**Issue by sayandip18** [sympy/sympy#20367]
The [example code](https://docs.sympy.org/dev/modules/plotting.html#plotting-geometric-entities) intended for plotting geometric structures shows blank 3D space when executed

![Screenshot from 2020-11-01 18-23-02](https://user-images.githubusercontent.com/42385886/97804278-c7df0d00-1c74-11eb-945b-23beab412e04.jpg)

This should be changed. `plot_parametric()` or `plot()` may be used.

**Comment by carbonox-infernox** [comment]
I came to this Github project just to look for this issue, since I ran into it as well, but I cannot get plot_parametric() or plot() to work either.

**Comment by sayandip18** [comment]
@carbonox-infernox Both `plot()` and `plot_parametric()` are working for me. Do you have matplotlib installed? What exact commands did you use?

**Comment by carbonox-infernox** [comment]
I wasn't sure which plot to import, so I tried it two ways:

```
from sympy.plotting import plot
from sympy import Circle, Point

p = plot(axes='label_axes=True')
c = Circle(Point(0,0), 1)
t = c.tangent_lines(c.random_point())
p[0] = c
p[1] = t
```

and as above, but with
```
from sympy.plotting.plot import plot
```
instead

This is with Python 3.8.6, sympy 1.7.1, and matplotlib 3.3.3

**Comment by sayandip18** [comment]
Only the instructions in the section titled ["Plotting Geometric Entities"](https://docs.sympy.org/latest/modules/plotting.html#plotting-geometric-entities) are wrong. The rest is all right.

**Comment by carbonox-infernox** [comment]
What commands should work? Like I said, I tried to apply your suggestion of using plot instead of Plot, and that didn't help. What exactly am I doing wrong?

**Comment by sayandip18** [comment]
```
>>> from sympy import symbols
>>> from sympy.plotting import plot
>>> x = symbols('x')
>>> plot(x)
```
will give you the straight line `y=x`.

**Comment by carbonox-infernox** [comment]
Ok, that one does work for me, but I'm still looking for something that plots geometry correctly. This is the minimum viable code for my use-case that should either work, or at least give a helpful error:

```
tri = Triangle(Point2D(0, 2*sqrt(3)), Point2D(1, 2*sqrt(3)), Point2D(1/2, 5*sqrt(3)/2))
p = Plot(visible=False)
for i in range(len(tri.sides)):
    p[i] = tri.sides[i]
p.show()
```

For me, this produces an empty 3D plot. Furthermore, indexing p throws ```IndexError: list index out of range```

**Comment by sayandip18** [comment]
Yes, these instructions don't work. The `Plot` object cannot be used with geometric classes like the Triangle class or the Circle class. The solution is either adding a new plotting module that can work with geometric classes or simply using `plot_implicit()` to plot geometric structures.

**Comment by carbonox-infernox** [comment]
Oh, ok. I must have misunderstood you earlier. You seemed to imply that simply swapping Plot for plot or plut_implicit would make geometry plot, but what you meant is that those alternatives work for _their_ respective purposes, not for geometry. Sorry for the confusion.

**Comment by sayandip18** [comment]
No worries! I'll try to update this section of the docs asap. Might also add the new plotting feature if the Sympy community approves.
