### ISSUE TITLE
Linear programming with simplex method

### ISSUE THREAD

**Issue by sylee957** [sympy/sympy#20391]
SymPy currently lacks any linear optimization method.
While most of the optimization optimization methods are numeric, simplex method can use exact arithmetics.

I have picked the tableau implementation of http://web.tecnico.ulisboa.pt/mcasquilho/acad/or/ftp/FergusonUCLA_LP.pdf however, I have implemented naive random pivoting method to break out of cycling problems.
I'd reference the code example here if some people needs the implementation

```
from sympy import *
import random


# Pivot operation for simplex method
# http://web.tecnico.ulisboa.pt/mcasquilho/acad/or/ftp/FergusonUCLA_LP.pdf pp.16
def pivot(M, i, j):
    p = M[i, j]
    MM = Matrix.zeros(M.rows, M.cols)
    for ii in range(M.rows):
        for jj in range(M.cols):
            if ii == i and jj == j:
                MM[ii, jj] = 1 / M[i, j]
            elif ii == i and jj != j:
                MM[ii, jj] = M[ii, jj] / M[i, j]
            elif ii != i and jj == j:
                MM[ii, jj] = -M[ii, jj] / M[i, j]
            else:
                MM[ii, jj] = M[ii, jj] - M[ii, j] * M[i, jj] / M[i, j]
    return MM


# Simplex method with randomized pivoting
# http://web.tecnico.ulisboa.pt/mcasquilho/acad/or/ftp/FergusonUCLA_LP.pdf
def simplex(M, R, S):
    while True:
        B = M[:-1, -1]
        A = M[:-1, :-1]
        C = M[-1, :-1]
        if all(B[i] >= 0 for i in range(B.rows)):
            piv_cols = []
            for j in range(C.cols):
                if C[j] < 0:
                    piv_cols.append(j)

            if not piv_cols:
                return M, R, S
            random.shuffle(piv_cols)
            j0 = piv_cols[0]

            piv_rows = []
            for i in range(A.rows):
                if A[i, j0] > 0:
                    ratio = B[i] / A[i, j0]
                    piv_rows.append((ratio, i))

            if not piv_rows:
                assert False, 'Unbounded'
            piv_rows = sorted(piv_rows, key=lambda x: (x[0], x[1]))
            piv_rows = [(ratio, i) for ratio, i in piv_rows if ratio == piv_rows[0][0]]
            random.shuffle(piv_rows)
            _, i0 = piv_rows[0]
            
            M = pivot(M, i0, j0)
            R[j0], S[i0] = S[i0], R[j0]
        else:
            for k in range(B.rows):
                if B[k] < 0:
                    break
            
            piv_cols = []
            for j in range(A.cols):
                if A[k, j] < 0:
                    piv_cols.append(j)
            
            if not piv_cols:
                assert False, 'Infeasible'
            random.shuffle(piv_cols)
            j0 = piv_cols[0]
            
            ratio = B[k] / A[k, j0]
            piv_rows = [(ratio, k)]
            for i in range(A.rows):
                if A[i, j0] > 0 and B[i] > 0:
                    ratio = B[i] / A[i, j0]
                    piv_rows.append((ratio, i))
            
            piv_rows = sorted(piv_rows, key=lambda x: (x[0], x[1]))
            piv_rows = [(ratio, i) for ratio, i in piv_rows if ratio == piv_rows[0][0]]
            random.shuffle(piv_rows)
            _, i0 = piv_rows[0]
            
            M = pivot(M, i0, j0)
            R[j0], S[i0] = S[i0], R[j0]
            

# Maximize Cx + D constrained with Ax <= B and x >= 0
# Minimize y^{T}B constrained with y^{T}A >= C^{T} and y >= 0
def linear_programming(A, B, C, D):
    M = Matrix([[A, B], [-C, D]])
    r_orig = ['x_{}'.format(j) for j in range(M.cols - 1)]
    s_orig = ['y_{}'.format(i) for i in range(M.rows - 1)]
    
    r = r_orig.copy()
    s = s_orig.copy()
    
    M, r, s = simplex(M, r, s)
    
    argmax = []
    argmin_dual = []
    
    for x in r_orig:
        for i, xx in enumerate(s):
            if x == xx:
                argmax.append(M[i, -1])
                break
        else:
            argmax.append(S.Zero)
            
    for x in s_orig:
        for i, xx in enumerate(r):
            if x == xx:
                argmin_dual.append(M[-1, i])
                break
        else:
            argmin_dual.append(S.Zero)
            
    return M[-1, -1], argmax, argmin_dual
```
```
A = Matrix([[0, 1, 2], [-1, 0, -3], [2, 1, 7]])
B = Matrix([3, -2, 5])
C = Matrix([[1, 1, 5]])
D = Matrix([0])

# (11/3, [0, 1/3, 2/3], [0, 2/3, 1])
linear_programming(A, B, C, D)
```

I add some information about the usage as much as I recall:

When `x` is a column vector of variables, `y` is a column vector of dual variables, and when the objective is either 

1. Maximizing `Cx` constrained to `Ax <= B and x >= 0`
2.  Minimizing `y^{T}B` constrained to `y^{T}A >= C^{T} and y >= 0`

(All in implicit matrix notations in TeX form)
(Both problems are mathematically equivalent and can be simultaneously computed with this algorithm)

I also introduced `D` even if this is a bit redundant because simplex algorithm needs that tiny corner of the matrix to store the intermediate result.

`linear_programming` returns a triplet of solutions `optimum, argmax, argmax_dual` where `argmax` is `x` and `argmax_dual` is `y`.

The possible exceptions raised by `simplex` are `'unbounded'` and `'infeasible'` where `'unbounded'` means the minimum or maximum are infinities, and `'infeasible'` means there is no satisfiable region for all the inequality specifications.
Both exceptions are sufficient and necessary for handling all the practical cases
However, I suggest these exceptions should be more polished before release.

I would also set the other big objective to provide an interface from `a list of sympy inequalities, equations <=> argument to linear_programming` because it's more intuitive to work with arbitrary inequalities and equational constraints for most of the small problems.
I believe that there are ways to convert linear expressions to matrix, and also to convert arbitrary inequality and equational constraints by using auxiliary variables. (The point is that you should finally be able to provide a method to make this work with every linear equations and inequality constraints)
Also, there should be a way to convert maxima to minima objective by flipping signs.

**Comment by oscarbenjamin** [comment]
It would be great to be able to use this to answer assumptions queries involving inequalities like:
```
ask(x+y>3, (x>2)&(y>1))
```

**Comment by naveensaigit** [comment]
We could also implement one of the integer point methods which are efficient for some cases when the simplex has exponential complexity. Where should this be added?

**Comment by sylee957** [comment]
Right now, we first need to conclude about the common user interface to how to accept inputs according to different constraint specifications,
We can use various inputs from matrix form to equational form, however, I've concluded about how to balance between  generality and efficiency for parsing.

**Comment by sylee957** [comment]
We can have integer point methods too, but I think that it's a completely different problem for finding feasible or optimal solution for integers.

**Comment by oscarbenjamin** [comment]
We can have multiple interfaces to the underlying algorithm. There should be one that just takes relations as input but it also makes sense to have one that takes matrix input since that's what will be used internally anyway.

**Comment by naveensaigit** [comment]
> We can have integer point methods too, but I think that it's a completely different problem for finding feasible or optimal solution for integers.

My bad, I meant interior point methods. They are guaranteed to be faster than the simplex method, although they might be hard to implement. Some literature [here](http://www.math.umbc.edu/~potra/talk0930.pdf) and [here](https://cloudflare-ipfs.com/ipfs/bafykbzacec222ccmkfrs7diqizxig6hutvipw4sucf4x3abo6ttfshtkmkhb2?filename=Dimitris%20Bertsimas%2C%20John%20N.%20Tsitsiklis%20-%20Introduction%20to%20Linear%20Optimization-Athena%20Scientific%20%281997%29.pdf) (See Pg 411)

**Comment by sylee957** [comment]
Is interior point method done by exact arithmetics or gives only the numerically approximated solution?

**Comment by naveensaigit** [comment]
> Is interior point method done by exact arithmetics or gives only the numerically approximated solution?

It is an iterative method, so it does not give exact solutions. But from what I've read, it seems to give really accurate results. An added benefit is that it can be extended even to nonlinear programming

**Comment by sylee957** [comment]
The exactness and precision are different problems, and we always need solvers for exact arithmetics in case we need the precise proof, even if you’d claim that the the numeric result can be rationalized, there are always badly conditioned cases that can make it not perfect.

I’d just suggest a parallel implementation or using scipy if you need that implementation.

**Comment by naveensaigit** [comment]
> I’d just suggest a parallel implementation or using scipy if you need that implementation.

I was thinking more along the lines of how we calculate determinant using various methods where we pass in the method as string. Default could be simplex and if in case, its takes a long time (which is very rare, but there are cases where simplex is exponential), then the end user can use interior point method which is guaranteed to run in polynomial time.

**Comment by sylee957** [comment]
Yes, I have the similar idea if someone is going to implement different methods, and if one algorithm is not direct superior and compatible with others.

**Comment by naveensaigit** [comment]
So, would the linear (and possibly non-linear) programming methods be a submodule of `matrices`? What is the idea?

**Comment by mayankray2020** [comment]
@sylee957 @oscarbenjamin can this be a GSoC idea??

**Comment by smichr** [comment]
cf #22389 and #21687

**Comment by smichr** [comment]
added in #25440
