### ISSUE TITLE
Documentation conflict

### ISSUE THREAD

**Issue by RicardoSQueen** [sympy/sympy#20408]
When studying the Reference Frame implementation it says in [https://docs.sympy.org/latest/modules/physics/vector/api/classes.html#referenceframe](url):
![image](https://user-images.githubusercontent.com/64474885/98745016-7f6cd100-2391-11eb-8e56-a0eac0d36d96.png)
Testing that out it gives:
![image](https://user-images.githubusercontent.com/64474885/98745074-9d3a3600-2391-11eb-96c5-24bec4267cbb.png)
which seems to be ok.
And in another url: [https://docs.sympy.org/latest/modules/physics/vector/vectors.html](url)
![image](https://user-images.githubusercontent.com/64474885/98745141-c064e580-2391-11eb-9a94-764cee905084.png)
And that one seems to be the opposite

**Comment by moorepants** [comment]
The second one is old and needs correcting.

**Comment by theanshm** [comment]
I would like to fix this issue.
