### ISSUE TITLE
travis giving html error randomly

### ISSUE THREAD

**Issue by sidhu1012** [sympy/sympy#20409]
Makefile:49: recipe for target 'html' failed
make: *** [html] Error 1

**Comment by naveensaigit** [comment]
This happens if building the documentation fails. It is likely that there is something in the docstring. Where are you facing this?

**Comment by sidhu1012** [comment]
> This happens if building the documentation fails. It is likely that there is something in the docstring. Where are you facing this?

Thanks!! PR #20318

**Comment by naveensaigit** [comment]
I can see the following warnings in the log (https://travis-ci.org/github/sympy/sympy/jobs/742924327#L1370) - 
```
/home/travis/build/sympy/sympy/sympy/physics/vector/frame.py:docstring of sympy.physics.vector.frame.ReferenceFrame.orient:22: WARNING: Unexpected indentation.
/home/travis/build/sympy/sympy/sympy/physics/vector/frame.py:docstring of sympy.physics.vector.frame.ReferenceFrame.orient:23: WARNING: Block quote ends without a blank line; unexpected unindent.
/home/travis/build/sympy/sympy/sympy/physics/vector/frame.py:docstring of sympy.physics.vector.frame.ReferenceFrame.orientnew:22: WARNING: Unexpected indentation.
/home/travis/build/sympy/sympy/sympy/physics/vector/frame.py:docstring of sympy.physics.vector.frame.ReferenceFrame.orientnew:23: WARNING: Block quote ends without a blank line; unexpected unindent.
/home/travis/build/sympy/sympy/sympy/physics/vector/frame.py:docstring of sympy.physics.vector.frame.ReferenceFrame.orientnew:38: WARNING: Unexpected indentation.
```
The log is slightly misleading because when it fails to build documentation, the error message is somewhere in between as opposed to the end!

**Comment by sylee957** [comment]
There is an option like 
https://www.sphinx-doc.org/en/master/man/sphinx-build.html#cmdoption-sphinx-build-keep-going
which may be able to exit the build once at the point where it had failed

But I'm not sure it's a good idea to encourage such trial-and-error approach for contributors because we are running out of the resources #20374

**Comment by sidhu1012** [comment]
Once the resources problem is fixed , exiting the build at the point where it had failed is a better option.
