### ISSUE TITLE
DiracDelta does not allow symbolic derivative?

### ISSUE THREAD

**Issue by oe1rsa** [sympy/sympy#20415]
from sympy import DiracDelta, symbols, diff

t = symbols('t')
n = symbols('n', integer=True, positive=True)

this gives the expected result
diff(DiracDelta(t), t, 3)

DiracDelta(t, 3)
 but only if the parameter is a constant

when using a symbol it does not work
diff(DiracDelta(t), t, n)
this will give zero respectively <class 'sympy.core.numbers.Zero'>

I would have expected the result
DiracDelta(t, n)

**Comment by akshatsood2249** [comment]
The issue here is that `DiracDelta(t,n)` evaluates only for non-integral `n` and fails even for positive `n`, I believe that is why you are getting this error from SymPy

**Comment by oe1rsa** [comment]
Sorry, I am not sure I understand.
If I invoke DiracDelta(t, 0.5), I get the Error:
Error: the second argument of DiracDelta must be             a non-negative integer, 0.500000000000000 given instead.

So what do you mean by "evaluates only for non-integral n" ?

**Comment by oscarbenjamin** [comment]
There is a confusion about how to specify the nth derivative here:
```python
In [1]: f(x, y).diff(x, 2)                                                                                             
Out[1]: 
  2         
 ∂          
───(f(x, y))
  2         
∂x          

In [2]: f(x, y).diff(x, y)                                                                                             
Out[2]: 
   2          
  ∂           
─────(f(x, y))
∂y ∂x         

In [3]: f(x, y).diff((x, 2))                                                                                           
Out[3]: 
  2         
 ∂          
───(f(x, y))
  2         
∂x          

In [4]: f(x, y).diff((x, y))                                                                                           
Out[4]: 
  y         
 ∂          
───(f(x, y))
  y         
∂x
```
When you write `diff(DiracDelta(t), t, n)` that means differentiate with respect to t and then differentiate with respect to n. Since the function does not depend on n the result is zero. If you want to differentiate with respect to t n times then you need to pass a tuple:
```python
In [5]: diff(DiracDelta(t), (t, n))                                                                                    
Out[5]: 
  n      
 d       
───(δ(t))
  n      
dt       

In [6]: diff(DiracDelta(t), t, n)                                                                                      
Out[6]: 0
```

**Comment by oe1rsa** [comment]
Oh, thank you so much. But there is still something odd. Compoare:

pprint(DiracDelta(t, 3))

pprint(diff(DiracDelta(t), (t,3)))

pprint(diff(DiracDelta(t), (t,n)))

They give:

 (3)    
δ    (t)

 (3)    
δ    (t)

  n      
 d       
───(δ(t))
  n      
dt       

Why do I not get
 (n)    
δ    (t)
for the last one? As far as I understand the operator notation means that the expression is not evaluated yet, correct?

**Comment by oscarbenjamin** [comment]
Yes, that's correct. Actually `DiracDelta` does not support having a symbolic second argument but that could be fixed:
```python
In [1]: DiracDelta(t, n)                                                                                               
---------------------------------------------------------------------------
ValueError: Error: the second argument of DiracDelta must be             a non-negative integer, n given instead. 
```
To make that evaluate `DiracDelta` would need to have an `_eval_derivative_n_times` method. The method would need to check for or be able to handle more complicated cases as well e.g.: 
```python
In [8]: f = DiracDelta(exp(t))                                                                                         

In [9]: diff(f, (t, 1))                                                                                                
Out[9]: 
 t  (1) ⎛ t⎞
ℯ ⋅δ    ⎝ℯ ⎠

In [10]: diff(f, (t, 2))                                                                                               
Out[10]: 
⎛ t  (2) ⎛ t⎞    (1) ⎛ t⎞⎞  t
⎝ℯ ⋅δ    ⎝ℯ ⎠ + δ    ⎝ℯ ⎠⎠⋅ℯ 

In [11]: diff(f, (t, 3))                                                                                               
Out[11]: 
⎛ 2⋅t  (3) ⎛ t⎞      t  (2) ⎛ t⎞    (1) ⎛ t⎞⎞  t
⎝ℯ   ⋅δ    ⎝ℯ ⎠ + 3⋅ℯ ⋅δ    ⎝ℯ ⎠ + δ    ⎝ℯ ⎠⎠⋅ℯ 

In [12]: diff(f, (t, 4))                                                                                               
Out[12]: 
⎛ 3⋅t  (4) ⎛ t⎞      2⋅t  (3) ⎛ t⎞      t  (2) ⎛ t⎞    (1) ⎛ t⎞⎞  t
⎝ℯ   ⋅δ    ⎝ℯ ⎠ + 6⋅ℯ   ⋅δ    ⎝ℯ ⎠ + 7⋅ℯ ⋅δ    ⎝ℯ ⎠ + δ    ⎝ℯ ⎠⎠⋅ℯ 
```
Even if the derivative does not evaluate symbolically you can still substitute for the symbol and cause evaluation:
```python
In [13]: diff(DiracDelta(t), (t, n))                                                                                   
Out[13]: 
  n      
 d       
───(δ(t))
  n      
dt       

In [14]: diff(DiracDelta(t), (t, n)).subs(n, 4).doit()                                                                 
Out[14]: 
 (4)    
δ    (t)
```
