### ISSUE TITLE
Solving linear recurrences

### ISSUE THREAD

**Issue by naveensaigit** [sympy/sympy#20424]
Is there a way to solve linear recurrences using generating functions? Or maybe even to get an asymptotic bound? It would be a great addition to sympy if its not currently present

**Comment by oscarbenjamin** [comment]
There is rsolve:
https://docs.sympy.org/latest/modules/solvers/solvers.html#sympy.solvers.recurr.rsolve

**Comment by oscarbenjamin** [comment]
There are open issues with rsolve though: https://github.com/sympy/sympy/issues?q=is%3Aopen+is%3Aissue+label%3Asolvers.rsolve

**Comment by naveensaigit** [comment]
I'll take a look and see if I can resolve anything
