### ISSUE TITLE
simplify() returns wrong result when applied to a certain trigonometric expression

### ISSUE THREAD

**Issue by sami-b95** [sympy/sympy#20430]
The `simplify()` function from sympy returns a wrong result when applied to the following trigonometric expression:

<img src="https://render.githubusercontent.com/render/math?math=\cos\left(\frac{\beta}{2}\right) \sin\left(\frac{\beta}{2}\right) \cos(\beta) \cos(\gamma)^2 \sin(\gamma)">

The latter gets simplified to:

<img src="https://render.githubusercontent.com/render/math?math=\frac{\cos(2\beta - 2\gamma) - \cos(2\beta %2B 2\gamma)}{16}">

instead of:

<img src="https://render.githubusercontent.com/render/math?math=\cos(\gamma)\frac{\cos(2\beta - 2\gamma) - \cos(2\beta %2B 2\gamma)}{16}">

Here is a piece of code that reproduces the issue:
```python
from sympy import cos, simplify, sin, symbols

beta, gamma = symbols("\\beta \gamma", real=True)
expression = cos(beta / 2) * sin(beta / 2) * cos(beta) * cos(gamma) ** 2 * sin(gamma)
simplified_expression = simplify(expression)
print(expression)
print(simplified_expression)
```

**Python version**: 3.8
**SymPy version**: 1.6.2

**Comment by smichr** [comment]
TRmorrie is ignoring the power on the `cos(g)` factor. The fix might be
```diff
diff --git a/sympy/simplify/fu.py b/sympy/simplify/fu.py
index 7fce72d38a..b9f0e39a75 100644
--- a/sympy/simplify/fu.py
+++ b/sympy/simplify/fu.py
@@ -1206,8 +1206,8 @@ def f(rv, first=True):
                             c.remove(cc)
                     new.append(newarg**take)
                 else:
-                    no.append(c.pop(0))
-            c[:] = no
+                    b = cos(c.pop()*a)
+                    other.append(b**coss[b])

         if new:
             rv = Mul(*(new + other + [
```
