### ISSUE TITLE
FiniteSet contains equal Elements

### ISSUE THREAD

**Issue by phgilde** [sympy/sympy#20432]
When defining a FiniteSet like this:
`FiniteSet(I*7+I*(sqrt(7)-7), I*5+I*(sqrt(7)-5))`
It keeps both elements, even though they are equal (`I*sqrt(7)`). I think equality in FiniteSets should be checked with `.equals()`, but at the moment I think its checked with `hash()` as FiniteSet in its core uses a `set()`.

**Comment by oscarbenjamin** [comment]
The `.equals` function is very slow so it should not be used by default in `FiniteSet`. There should be some way to simplify the `FiniteSet` though so that we can see that it only has one element.

**Comment by mridul7ahuja** [comment]
Using `simplify` on each of the elements would produce a singleton in this case, but again that might be very slow to apply on all elements for other cases. Please let me know if there is a more generalizable solution to use. I'm new here and would love to contribute!

**Comment by oscarbenjamin** [comment]
It should be possible to call `simplify` on the set but that currently doesn't do anything:
```python
In [105]: S = FiniteSet(1, cos(1)**2 + sin(1)**2)                                                                                 

In [106]: simplify(S)                                                                                                             
Out[106]: 
⎧      2         2   ⎫
⎨1, cos (1) + sin (1)⎬
⎩                    ⎭

In [107]: FiniteSet(*(simplify(x) for x in S))                                                                                    
Out[107]: {1}
```
I think we can add an `_eval_simplify` method to `FiniteSet` to make this work.

**Comment by mridul7ahuja** [comment]
```
from sympy.simplify.simplify import simplify

def _eval_simplify(self):
    return FiniteSet(*[simplify(elem) for elem in self])
```
@oscarbenjamin should I go ahead and add this to `FiniteSet`?

**Comment by oscarbenjamin** [comment]
Yes, that looks good. I think that `_eval_simplify` should take `**kwargs` and pass them on when calling simplify recursively.

**Comment by mridul7ahuja** [comment]
```
from sympy.simplify.simplify import simplify

def _eval_simplify(self, **kwargs):
    return FiniteSet(*[simplify(elem) for elem in self], **kwargs)
```
If this is okay, should I now make a pull request?

**Comment by oscarbenjamin** [comment]
The `kwargs` should be passed to `simplify`. Otherwise yes, go ahead and open a pull request.

**Comment by akshatsood2249** [comment]
> The `kwargs` should be passed to `simplify`. Otherwise yes, go ahead and open a pull request.

I believe `kwargs` should be passed on to _eval_simplify itself, it works fine.
