### ISSUE TITLE
Why is there no square function?

### ISSUE THREAD

**Issue by edmundsj** [sympy/sympy#20455]
Why is there no square function? I find myself regularly needing to square quantities which are composites of multiple variables, and it's a real pain to be typing ``x*x*f*f*c*c*4*pi*pi``, when what I really want to do (and can do in numpy) is ``sq(x*f*c*2*pi)``.

EDIT: I know there is a power function, but squaring quantities is so common (and implemented in almost every package I am aware of) that it deserves its own function.

**Comment by oscarbenjamin** [comment]
Normally squaring is done using exponentiation:
```python
In [1]: (x*y)**2                                                                                                                  
Out[1]: 
 2  2
x ⋅y 
```

**Comment by asmeurer** [comment]
If you are doing code generation and want `x**2` to generate `x*x` you can use https://docs.sympy.org/latest/modules/codegen.html#sympy.codegen.rewriting.create_expand_pow_optimization
