### ISSUE TITLE
Mistake in a limit computation

### ISSUE THREAD

**Issue by singladur** [sympy/sympy#20482]
As user of sympy I was surprised when computing:

```
>>> x = sympy.symbols("x")
>>> sympy.limit((2*x+12)/(sympy.Abs(x+6)),x,-6)
2
```

While this limit does not exists. However, when computing lateral limits, sympy does the job:
```
l_left = sympy.limit((2*x+12)/(sympy.Abs(x+6)),x,-6,"-")
l_right = sympy.limit((2*x+12)/(sympy.Abs(x+6)),x,-6,"+")
```

Both lateral limits are correct.

Is it a mistake with the function sympy.Abs or a bug in the sympy.limit algorithm?

All the best.

**Comment by oscarbenjamin** [comment]
The `limit` function computes a one-sided limit by default. Use `"+-"` for a two-sided limit.

**Comment by singladur** [comment]
Thank you for your alcaration.
The sympy guide is not clear at this point and seems to indicate that if no
option is given, the result would be the two-sided limit. Indeed, no
mention to option "+-" is done there.  I appreciate your mail and will
clarify this point to my colleagues and my students.
All the best

**Comment by singladur** [comment]
Trying again, I am really confused. If I try to compute the limit when x
goes to 0 of the function |x|/x which, does not exists, it gives as answer
1 without options (what agrees with your explanation) but it also gives 1
when option "+-" is given. Indeed it does not compute properly the limit
from left which should be -1, right? I am using the absolute value as Abs.
Should I use a different function?

Thanks again

**Comment by oscarbenjamin** [comment]
You can use either `Abs` or `abs`.

What version of sympy are you using? With 1.7 I get:
```python
In [15]: limit(abs(x)/x, x, 0)                                                                                                    
Out[15]: 1

In [16]: limit(abs(x)/x, x, 0, '+')                                                                                               
Out[16]: 1

In [17]: limit(abs(x)/x, x, 0, '-')                                                                                               
Out[17]: -1

In [18]: limit(abs(x)/x, x, 0, '+-')                                                                                              
---------------------------------------------------------------------------
ValueError: The limit does not exist since left hand limit = -1 and right hand limit = 1
```

**Comment by singladur** [comment]
Oh, thank you.
I believe it had something to do with the version that we were using
(1.5.2). In any case, we will update to last version.
I have tried my self  with 1.7 and your code:

limit(abs(x)/x, x, 0, '+-')

I run it using Thonny, and the shell throws an error. I copy the error.

Traceback (most recent call last):
  File "<pyshell>", line 1, in <module>
  File "/Users/TanoNisejo/Library/Python/3.7/lib/python/site-packages/sympy/series/limits.py",
line 65, in limit
    return Limit(e, z, z0, dir).doit(deep=False)
  File "/Users/TanoNisejo/Library/Python/3.7/lib/python/site-packages/sympy/series/limits.py",
line 329, in doit
    % (l, r))
ValueError: The limit does not exist since left hand limit = -1 and
right hand limit = 1


I believe that the right thing would be obtaining what you pasted,
simply the last sentence. However, on my computer it throws two errors
in file "limits.py" from sympy. Is it a problem of sympy or a problem
in my installation?


Thanks for all the help

**Comment by oscarbenjamin** [comment]
> I believe that the right thing would be obtaining what you pasted, simply the last sentence. However, on my computer it throws two errors in file "limits.py" from sympy. Is it a problem of sympy or a problem in my installation?

I do not understand what you mean. Above you showed the expected output:
```
>>> limit(abs(x)/x, x, 0, '+-')
Traceback (most recent call last):
  File "<pyshell>", line 1, in <module>
  File "/Users/TanoNisejo/Library/Python/3.7/lib/python/site-packages/sympy/series/limits.py",
line 65, in limit
    return Limit(e, z, z0, dir).doit(deep=False)
  File "/Users/TanoNisejo/Library/Python/3.7/lib/python/site-packages/sympy/series/limits.py",
line 329, in doit
    % (l, r))
ValueError: The limit does not exist since left hand limit = -1 and
right hand limit = 1
```
That error is correct.

Did you get a different error running some other command with SymPy 1.7? If so what command and what error?

**Comment by singladur** [comment]
I mean that python shouldnt throw a runtime error but just the result that
the limit does not exit. But this is just an opinion.

I am happy with your answers and the behaviour of sympy.

Thanks!

**Comment by oscarbenjamin** [comment]
It would be better if the error was called e.g. `NonexistentLimitError` rather than `ValueError`. Otherwise I think an exception is fine. You can always catch the error and you can make your own function to catch it e.g.:
```
def mylimit(*args):
    try:
        return limit(*args)
    except ValueError:
        print('The limit does not exist')
        return nan
```

**Comment by singladur** [comment]
Yes, it looks like a neat solution. Thanks for all the help!

**Comment by oscarbenjamin** [comment]
No problem. I'll close this as solved. Thanks for reporting!

**Comment by singladur** [comment]
I still find some strange behavior when computing limits with sympy. For instance:
`sy.limit(abs(x)*sy.sin(1/x),x,0)
sy.limit(abs(x)*sy.sin(1/x),x,0,"+")
sy.limit(abs(x)*sy.sin(1/x),x,0,"-")`
all give the right answer 0 but
`sy.limit(abs(x)*sy.sin(1/x),x,0,"+-")`
freezes sympy who outputs:
`Limit(sin(1/x)*Abs(x), x, 0, dir='+-')`
[This is in version 1.7 in previous versions it throws an exception]

**Comment by oscarbenjamin** [comment]
Yes, there does seem to be a problem:
```python
In [9]: limit(abs(x)*sin(1/x),x,0)                                                                                                
Out[9]: 0

In [10]: limit(abs(x)*sin(1/x),x,0, "-")                                                                                          
Out[10]: 0

In [11]: limit(abs(x)*sin(1/x),x,0, "+-")                                                                                         
Out[11]: 
    ⎛   ⎛1⎞    ⎞
lim ⎜sin⎜─⎟⋅│x│⎟
x─→0⎝   ⎝x⎠    ⎠
```
Can you open a new issue for that?

**Comment by singladur** [comment]
of course!

**Comment by asmeurer** [comment]
limit is inconsistent compared to other SymPy functions in that it doesn't always return the unevaluated Limit object. IMHO it should do that, with some flag or something to pass the exception through if you want to see the message. 

There have been discussions on making limits two-sided by default. That would break backwards compatibility, however, and there are some other issues as well (see https://github.com/sympy/sympy/issues/8320).

**Comment by oscarbenjamin** [comment]
In the most recent example sympy is able to compute the limit from each side but somehow the two-sided limit (`+-`) fail.
