### ISSUE TITLE
Utility for getting generator index of FracField

### ISSUE THREAD

**Issue by sylee957** [sympy/sympy#20501]
FracField don't have any utility to get the index of the generator
```
R, x, y, z = ring('x y z', QQ)
R.index(x)
F, x, y, z = field('x y z', QQ)
F.index(x)
# AttributeError: 'FracField' object has no attribute 'index'
```
So a boilerplate is needed to get the index like `F.ring.index(x.numer)`

**Comment by wsdookadr** [comment]
Since the field has an implicit ring structure, and the `index` method is already available on the ring object, it's possible to get the index using this:

```python3
F.ring.index(x.to_poly())
```

The `x.to_poly()` casts from `FracElement` to `PolyElement` and then the `index` method is called.

I wonder if this is the way to go
