### ISSUE TITLE
Quantum Operators and states are scalars, not Matrix. Also for exp(A), A is a matrix, but exp(A) is a scalar

### ISSUE THREAD

**Issue by yunweilu** [sympy/sympy#20510]
Quantum Operators and states are scalars, not Matrix.
So, when I calculate sigmaz()*|a>, it becomes 
|a> 0
0  -|a>

**Comment by ellisonbg** [comment]
Could you give us more information about what you are trying to do?

**Comment by ellisonbg** [comment]
Going to close for now, please feel free to reopen if you want to continue the discussion.
