### ISSUE TITLE
Attribute error in stats module

### ISSUE THREAD

**Issue by kirk86** [sympy/sympy#20529]
The following working example throws the following error:
`AttributeError: 'Intersection' object has no attribute 'as_coeff_Mul'`

MWE
```
import sympy
import sympy.stats as stats
sympy.init_printing()

X = stats.Exponential('x', 1)
a = sympy.symbols('a', positive=True)
stats.P(X >= a).simplify()
```

**Comment by czgdp1807** [comment]
This issue is since 1.5.

**Comment by Maelstrom6** [comment]
Seems to be a problem with `integrate` instead of `stats`:

```python
from sympy import *
_z = Dummy('z')
a = symbols('a', positive=True)
x = Integral(exp(-_z), (_z, Intersection(Interval(0, oo), Interval(a, oo))))
print(x.doit())
```

**Comment by czgdp1807** [comment]
This can be closed then.

**Comment by kirk86** [comment]
Sorry if I may ask why should this be closed?, Isn't it still a problem in `integrate`? Did I miss something or is this solved?

**Comment by czgdp1807** [comment]
https://github.com/sympy/sympy/issues/20535 has been opened.

**Comment by kirk86** [comment]
Got it! Thanks.
