### ISSUE TITLE
typings/stubs for sqrt

### ISSUE THREAD

**Issue by nschloe** [sympy/sympy#20536]
The following code yields and error when checked with pyright:
```
pyright --lib demo.py
```
```python
import sympy

sympy.sqrt(3) * 3
```
```
  3:1 - error: Operator "*" not supported for types "Pow" and "Literal[3]"
    Operator "*" not supported for types "Pow" and "Literal[3]" (reportGeneralTypeIssues)
```
It works fine with other types, e.g., `Rational(2, 5)`.

**Comment by oscarbenjamin** [comment]
Should that not be considered a bug in pyright?

**Comment by nschloe** [comment]
I opened the same bug at pyright; let's see what they say.

**Comment by oscarbenjamin** [comment]
It's not easy to set type hints for things like this because currently there is no way to correctly hint the return value of sympify given that it handles arbitrarily nested lists:
```
In [1]: sympify([[[[[1]]]]])                                                                                                      
Out[1]: [[[[[1]]]]]
```

**Comment by oscarbenjamin** [comment]
Can you give a link to the pyright issue?

**Comment by nschloe** [comment]
It's liked above (by GitHub).

**Comment by oscarbenjamin** [comment]
Sorry, I missed that!

**Comment by nschloe** [comment]
From the pyright devs:

> Sympy doesn't appear to contain inlined types or packaged type stubs. You will need type information if you want to use it with a type checker.

**Comment by oscarbenjamin** [comment]
It looks like the `--lib` option to pyright should not be used with a library that does not have full type annotations.

I'm going to close this issue. I'm not opposed to adding type annotations but there's already an issue for that: https://github.com/sympy/sympy/issues/17945

**Comment by nschloe** [comment]
I should add that I found the issue with [coc-pyright](https://github.com/fannheyward/coc-pyright), the hottest completion plugin for Python in [n]vim. Apparently `--lib` is the default setting there. Okay, so let's see how the ecosystem develops here.
