### ISSUE TITLE
TypeError when printing Circle

### ISSUE THREAD

**Issue by James-G-Hill** [sympy/sympy#20577]
```
a, b, delta = symbols(r"a, b, \delta")

open_disc = Circle(Point(a, b), delta)
open_disc
```
The code above in JupyterLab causes 'TypeError: cannot determine truth value of Relational'. Stack trace below:

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
~/.virtualenvs/general/lib/python3.7/site-packages/IPython/core/formatters.py in __call__(self, obj)
    343             method = get_real_method(obj, self.print_method)
    344             if method is not None:
--> 345                 return method()
    346             return None
    347         else:

~/.virtualenvs/general/lib/python3.7/site-packages/sympy/geometry/entity.py in _repr_svg_(self)
    199             # Expand bounds by a fraction of the data ranges
    200             expand = 0.1  # or 10%; this keeps arrowheads in view (R plots use 4%)
--> 201             widest_part = max([xmax - xmin, ymax - ymin])
    202             expand_amount = widest_part * expand
    203             xmin -= expand_amount

~/.virtualenvs/general/lib/python3.7/site-packages/sympy/core/relational.py in __nonzero__(self)
    382 
    383     def __nonzero__(self):
--> 384         raise TypeError("cannot determine truth value of Relational")
    385 
    386     __bool__ = __nonzero__

TypeError: cannot determine truth value of Relational
```
Strangely, the definition of the Circle **DOES** get printed but after the stack trace:

𝐶𝑖𝑟𝑐𝑙𝑒(𝑃𝑜𝑖𝑛𝑡2𝐷(𝑎,𝑏),𝛿)

**Comment by oscarbenjamin** [comment]
Is this a regression in sympy 1.7?

**Comment by James-G-Hill** [comment]
Hello, sorry, I just checked and I was using a version 1.6(2)? and had this problem.  Then I immediately upgraded to 1.7 and found that the problem is still there.  So no, it exists in sympy 1.7 but existed in earlier version as well.

**Comment by sylee957** [comment]
The problem is jupyter looks up for `_repr_svg_` (even if it doesn't prints out by default) and for circle with non-numeric definitions, it is giving errors because it can't drawn with svg.

I first see that the problem is `bounds` is implemented even if it's not numeric, but it may not be changed because `bounds` can be implemented to have mathematical meanings, so there should be a logic for `_repr_svg_` to check whether the actual geometric object (or bounds) is numeric or not

**Comment by sylee957** [comment]
A simple fix would be changing `_repr_svg_` with
```
        try:
            bounds = self.bounds
        except (NotImplementedError, TypeError):
            # if we have no SVG representation, return None so IPython
            # will fall back to the next representation
            return None

        for x in bounds:
            if not x.is_number:
                return None
```
