### ISSUE TITLE
A strange behavior of limit function

### ISSUE THREAD

**Issue by singladur** [sympy/sympy#20578]
There is a strange behavior of computing limits in some cases. For instance the following computations:
`limit(abs(x)*sin(1/x),x,0)`
`limit(abs(x)*sin(1/x),x,0,"+") `
`limit(abs(x)*sin(1/x),x,0,"-")`
all give the right answer 0 but
`limit(abs(x)*sin(1/x),x,0,"+-")`
freezes sympy who outputs:
Limit(sin(1/x)*Abs(x), x, 0, dir='+-')
[This is in version 1.7; in previous versions it throws an exception]

**Comment by sidhu1012** [comment]
In current master 
`limit(abs(x)*sin(1/x),x,0,"+-")`
outputs
`Limit(sin(1/x)*Abs(x), x, 0, dir='+-')`

So this issue is already fixed in master.

**Comment by oscarbenjamin** [comment]
The limit should evaluate to 0. Both the left and right-sided limits do so the two sided limit should evaluate as well.

**Comment by 0sidharth** [comment]
This was fixed (`limit(abs(x)*sin(1/x),x,0,"+-")` now outputs 0) in bd444d3 from #21731, which improved the leading term handling of cos and sin when the arg is infinite. This could be closed if a regression test is added

**Comment by praneethratna** [comment]
@oscarbenjamin  Hey , can i take up this issue and add the regression test?

**Comment by praneethratna** [comment]
Hey! Can I work on this issue?
