### ISSUE TITLE
Complex exponentials are not recognized by domains

### ISSUE THREAD

**Issue by sylee957** [sympy/sympy#20617]
```python3
>>> from sympy import *

>>> x = Symbol('x')
>>> w = exp(I*2*pi/3)
>>> Poly([w**2, w, 1], x, extension=True)
Poly(exp(-2*I*pi/3)*x**2 + exp(2*I*pi/3)*x + 1, x, domain='ZZ(exp(I*pi/3))')
>>> w = w.expand(complex=True)
>>> Poly([w**2, w, 1], x, extension=True)
Poly((-1/2 - sqrt(3)*I/2)*x**2 + (-1/2 + sqrt(3)*I/2)*x + 1, x, domain='QQ<sqrt(3) + I>')
```

Only the second one gets recognized as algebraic extension

**Comment by oscarbenjamin** [comment]
I think it's because `_eval_is_algebraic` gives None

**Comment by asmeurer** [comment]
What's the point of checking the assumptions system first if `extension=True` has to be provided explicitly anyway? Shouldn't Poly just try to convert any numeric coefficients to algebraic extensions when `extension=True`, and fallback to non-algebraic extensions when if fails?

**Comment by oscarbenjamin** [comment]
I'm not sure but maybe calling minpoly on every unrecognised object might be slow. It seems that `is_algebraic` is a lot faster than `minpoly`:
```python
In [1]: e = cos(pi/11)

In [2]: %time e.is_algebraic
CPU times: user 333 µs, sys: 4 µs, total: 337 µs
Wall time: 342 µs
Out[2]: True

In [3]: %time minpoly(e)
CPU times: user 32.5 ms, sys: 2.51 ms, total: 35.1 ms
Wall time: 32.9 ms
Out[3]: 
    5       4       3       2          
32⋅x  - 16⋅x  - 32⋅x  + 12⋅x  + 6⋅x - 1

In [4]: e
Out[4]: 
   ⎛π ⎞
cos⎜──⎟
   ⎝11⎠
```
At the moment `construct_domain` checks `is_algebraic` on every element that is not rational, float or pure complex.

The changes in #20274 mean that after that checking if there are irrational algebraics then they will be processed to extract the elementary irrational parts. So if we have something like
```
construct_domain([1 + sqrt(2), 1 - sqrt(2), 1 + cbrt(3), 2 * cbrt(3), ...])
```
then after the initial scan the algebraics `[sqrt(2), cbrt(3)]` are extracted. At that point the minimal polynomial is constructed once for each of those and then the primitive element algorithm builds a common minimal polynomial. If we had a larger matrix and called `construct_domain` there could be thousands of elements in the matrix but only one or two irrationals whose minpoly needs to be computed.
