### ISSUE TITLE
Greek letter printing: "\nu" is printed as "u"

### ISSUE THREAD

**Issue by sschuldenzucker** [sympy/sympy#20652]
Something's wrong here:
```
>>> from sympy import *
>>> str(symbols("\nu"))
'u'

# Expected:
# '\\nu'
```

Other greek letters work as expected (I didn't do exhaustive testing though):
```
>>> str(symbols("\mu"))
'\\mu'
```

I also get the issue where `\nu` renders to "u" for mathjax printing in jupyter, so it doesn't seem to be a problem of `str()` rendering.

Sympy version: 1.6.2, on Windows. I hit the same issue in sympy live, though.

Perhaps related?: #5057

**Comment by oscarbenjamin** [comment]
In a Python string `\n` means a newline character. You need to double the slash or use a raw string:
```python
In [1]: '\nu'
Out[1]: '\nu'

In [2]: print('\nu')

u

In [3]: print('\\nu')
\nu

In [4]: print(r'\nu')
\nu

In [5]: symbols('\nu')
Out[5]: u

In [6]: symbols('\\nu')
Out[6]: \nu

In [7]: symbols(r'\nu')
Out[7]: \nu
```
I recommend always using raw-strings for LaTeX.

**Comment by sschuldenzucker** [comment]
Ohhh lol! 🤦‍♂️ And then I guess the whitespace is filtered out at some point, so it doesn't look any different! My bad, thanks a lot for the pointer!
