### ISSUE TITLE
Array differentiation of not sympy expression

### ISSUE THREAD

**Issue by carlos-adir** [sympy/sympy#20655]
I noticed that the function ```derive_by_array``` doesn't accept as argument an integer or a float.
```python
import sympy as sp
from sympy.abc import x, y, z

U = sp.Array([x, y, z])
E = 2
G = sp.derive_by_array(E, U)
```

This code gives the following error:
```
AttributeError: 'int' object has no attribute 'diff'
```

It could be solved using a verification in the begin of the function:
```python
if isinstance(E, (int, float)):
    return sp.Array([0 for i in range(len(U))])
```

**Comment by Abhishek-IOT** [comment]
@asmeurer can please help me how I can get forward with this issue

**Comment by akshatsood2249** [comment]
Well `1` can be passed on to as `[1]` for correct functioning. Apart from that I would love look out for that **error** message

**Comment by oscarbenjamin** [comment]
The `derive_by_array` function should sympify its arguments:
```python
In [3]: derive_by_array(sympify(E), sympify(U))
Out[3]: [0  0  0]
```

**Comment by rohit11544** [comment]
import sympy as sp
from sympy.abc import x, y, z

U = sp.Array([x, y, z])
E = 2
G = sp.derive_by_array(sympify(E), sympify(U))

this fixes #20655

**Comment by oscarbenjamin** [comment]
This is a valid issue. Since `derive_by_array` is not a private function (it is imported at top-level) it should sympify its arguments if necessary.

**Comment by sidhu1012** [comment]
> This is a valid issue. Since `derive_by_array` is not a private function (it is imported at top-level) it should sympify its arguments if necessary.

I'll fix it.
