### ISSUE TITLE
log() does not return exact answer when used for a different base

### ISSUE THREAD

**Issue by evatiwari** [sympy/sympy#20662]
When finding the log of a number to the base 2, I do not get the final simplified form. Am I using it correctly? Is there a way around it?
```
>>> from sympy import log
>>> log(36, 2)
2 + log(9)/log(2)
```

**Comment by oscarbenjamin** [comment]
What do you expect to see as output?

**Comment by evatiwari** [comment]
@oscarbenjamin 5.1699, basically, the final number.

**Comment by kc611** [comment]
For a numerical evaluation you either use `N(log(36, 2))` or `log(36, 2).evalf()`.

Reference : [Numerical Evaluation](https://docs.sympy.org/latest/modules/evalf.html)
