### ISSUE TITLE
Inconsistent result from printing symbol with subscripts in terminal

### ISSUE THREAD

**Issue by JSS95** [sympy/sympy#20675]
Symbol with subscript "x" is printed normally, but other alphabet subscripts are not.

```python
In [1]: kx, ky, kz = symbols("k_x k_y k_z", real=True)

In [2]: kx
Out[2]: kₓ

In [3]: ky
Out[3]: k_y

In [4]: kz
Out[4]: k_z
```

Is this a bug?

**Comment by JigarJoshi04** [comment]
I did not found that issue.
Kindly tell me the steps to reproduce.


![20675](https://user-images.githubusercontent.com/49904152/103166325-ec0b3480-4846-11eb-8f3a-328c3e69ead2.png)

**Comment by JSS95** [comment]
@JigarJoshi04 

I encountered this issue in terminal (with `isympy` session). It seems that this is a bug related to pretty printing.

```python
In [1]: kx, ky, kz = symbols("k_x k_y k_z", real=True)

In [2]: pretty(kx)
Out[2]: 'kₓ'

In [3]: pretty(ky)
Out[3]: 'k_y'
```

**Comment by JigarJoshi04** [comment]
Yeah, now I faced the same issue.
I'll look into it in a more detailed way.



![sympy pretty error](https://user-images.githubusercontent.com/49904152/103167942-7064b400-4855-11eb-9c03-6be07a7f159b.png)

**Comment by jksuom** [comment]
Unicode subscript `y` is not defined in all versions of Python:
```
IPython console for SymPy 1.7.dev (Python 3.6.12-64-bit) (ground types: gmpy)

In [7]: import unicodedata

In [8]: unicodedata.lookup('LATIN SUBSCRIPT SMALL LETTER X')
Out[8]: 'ₓ'

In [9]: unicodedata.lookup('LATIN SUBSCRIPT SMALL LETTER Y')
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-9-a5f503844d50> in <module>()
----> 1 unicodedata.lookup('LATIN SUBSCRIPT SMALL LETTER Y')

KeyError: "undefined character name 'LATIN SUBSCRIPT SMALL LETTER Y'"
```

**Comment by oscarbenjamin** [comment]
See also #20207

**Comment by oscarbenjamin** [comment]
It seems that unicode only defines some subscript latin letters:
https://en.wikipedia.org/wiki/Unicode_subscripts_and_superscripts#Latin_and_Greek_tables

If there is no subscript `y` then there's nothing SymPy can do about that...

**Comment by JSS95** [comment]
I'm closing this, then.
