### ISSUE TITLE
Weird behaviour of Eq.simplify() with Vector as arguments.

### ISSUE THREAD

**Issue by sidhu1012** [sympy/sympy#20677]
While working on #18692 I found something weird , is this intentional behavior?

from sympy.vector import *
from sympy import *

R = CoordSys3D('R')
T = CoordSys3D('T')
a = 5 * R.x + 5 * T.x
eq = Eq(a, 5*R.x)
print(eq.simplify())

Got -
Eq(T.x, 0)

Expected-
Eq( 5 * R.x + 5 * T.x, 5*R.x) i.e unevaluated expression or False, even None could have been better.

**Comment by oscarbenjamin** [comment]
That's not just for vectors:
```
In [2]: Eq(5*x + y, 5*x + 1).simplify()
Out[2]: y = 1
```
Why would this give False?

It should always be a symbolic Boolean so it should never be None.

**Comment by sidhu1012** [comment]
Oh yes, `simplify` with `Eq` tries to simplify and rewrite args.

**Comment by sidhu1012** [comment]
> ```
> In [2]: Eq(5*x + y, 5*x + 1).simplify()
> Out[2]: y = 1
> ```
Why is `y = 1 ` returned? Shouldn't it be returned in case of solve? And `simplify` returning `S.true` or `S.false` .

**Comment by naveensaigit** [comment]
> > ```
> > In [2]: Eq(5*x + y, 5*x + 1).simplify()
> > Out[2]: y = 1
> > ```
> 
> Why is `y = 1 ` returned? Shouldn't it be returned in case of `solve`? And `simplify` returning `S.true` or `S.false` .

Its just simplification of the equation, similar to the one above.
``` python
>>> from sympy import *
>>> from sympy.abc import x,y
>>> Eq(5*x + y, 5*x + 1).simplify()
Eq(y, 1)
>>> solve(Eq(5*x + y, 5*x + 1), y)
[1]
```
`solve` doesn't return an `Eq` object.

**Comment by sidhu1012** [comment]
> ``` python
> >>> from sympy import *
> >>> from sympy.abc import x,y
> >>> Eq(5*x + y, 5*x + 1).simplify()
> Eq(y, 1)
```

Yes this one seems right.
