### ISSUE TITLE
Permutation documentation incorrect re cycle order

### ISSUE THREAD

**Issue by FifiBonacci** [sympy/sympy#20689]
https://docs.sympy.org/latest/modules/combinatorics/permutations.html
says "Caution: when the cycles have common elements between them then the order in which the permutations are applied matters. The convention is that the permutations are applied from right to left. In the following, the transposition of elements 2 and 3 is followed by the transposition of elements 1 and 2:
Permutation(1, 2)(2, 3) == Permutation([(1, 2), (2, 3)])"

In fact, Permutation applies the cycles from left to right, as in the composition operator *
Here is a short example:

```
>>> from sympy.combinatorics import Permutation
>>> Permutation(1, 2)(2, 3).list()  # documentation sez does (2,3) first
[0, 3, 1, 2]
>>> a,b = Permutation(3)(1, 2),Permutation(2, 3)
>>> (a*b).list()  # does (1,2) first
[0, 3, 1, 2]
>>> (b*a).list()  # does (2,3) first
[0, 2, 3, 1]
>>> [ b(a(i)) for i in range(4)]  # explicitly do (1,2) first
[0, 3, 1, 2]
```

**Comment by lastcodestanding** [comment]
Yes, I just checked this out. For some reason it multiplies Permutations using `__Mul__()`  rather than using `rmul()` and thus results in this error. Changing it, however, causes a bunch of failed tests. If anyone can help me here, I'm happy to work on it.

**Comment by oscarbenjamin** [comment]
Maybe it's just a case of correcting the docs.

**Comment by lastcodestanding** [comment]
I can fix that right away if that is the case. However, as the documentation correctly says, right to left is the conventional way to do it.

**Comment by oscarbenjamin** [comment]
I don't know much about the combinatorics module but that sounds like a change that isn't backwards compatible.

**Comment by FifiBonacci** [comment]
I am just a user, but IMHO, changing the documentation, not the behavior, seems the most sensible approach.

**Comment by oscargus** [comment]
@FifiBonacci can you please check the documentation in #20719 and see if that solves the issue?

**Comment by FifiBonacci** [comment]
Yes, that looks great.
Thanks!

From: Oscar Gustafsson ***@***.***>
Reply-To: sympy/sympy ***@***.***>
Date: 2021 September 28, Tuesday at 6:44 AM
To: sympy/sympy ***@***.***>
Cc: ***@***.***" ***@***.***>, Mention ***@***.***>
Subject: Re: [sympy/sympy] Permutation documentation incorrect re cycle order (#20689)

NPS WARNING: *external sender* verify before acting.


@FifiBonacci<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FFifiBonacci&data=04%7C01%7Cdcanright%40nps.edu%7C8d9fc352fa764559be4208d982861b70%7C6d936231a51740ea9199f7578963378e%7C0%7C0%7C637684334828956201%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=shh49UAWclsXbYVXBa8i03NeYYYXr8OYkSHqNHuERW8%3D&reserved=0> can you please check the documentation in #20719<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fsympy%2Fsympy%2Fpull%2F20719&data=04%7C01%7Cdcanright%40nps.edu%7C8d9fc352fa764559be4208d982861b70%7C6d936231a51740ea9199f7578963378e%7C0%7C0%7C637684334828956201%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=4sKiew1X1LpG79TJr%2FX%2F3pyWrVV%2FBtuJjQ5%2BYXKrhSQ%3D&reserved=0> and see if that solves the issue?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fsympy%2Fsympy%2Fissues%2F20689%23issuecomment-929223661&data=04%7C01%7Cdcanright%40nps.edu%7C8d9fc352fa764559be4208d982861b70%7C6d936231a51740ea9199f7578963378e%7C0%7C0%7C637684334828966194%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Q1zMmFHXJfrDnvGenizG4J9T%2Fu4ddrwFqqIXtqXVNok%3D&reserved=0>, or unsubscribe<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAJQE4XFLLEGVQHZCARBKETTUEHBEFANCNFSM4VMQ6HTA&data=04%7C01%7Cdcanright%40nps.edu%7C8d9fc352fa764559be4208d982861b70%7C6d936231a51740ea9199f7578963378e%7C0%7C0%7C637684334828966194%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=%2Fd5mQqJfttf0rnwmMJM81XYRYaGlg0UyulmyG%2BIylRI%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cdcanright%40nps.edu%7C8d9fc352fa764559be4208d982861b70%7C6d936231a51740ea9199f7578963378e%7C0%7C0%7C637684334828976194%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Cmi14wwWQfG%2BhFsjSa9KIM4ew5tJgrDktd8gJOigUlU%3D&reserved=0> or Android<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cdcanright%40nps.edu%7C8d9fc352fa764559be4208d982861b70%7C6d936231a51740ea9199f7578963378e%7C0%7C0%7C637684334828976194%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=o7QWqPvHkst4poSt5r4Ldr0jZms%2FZ5Q0GO5yDA9DU0E%3D&reserved=0>.
