### ISSUE TITLE
Series is not simplified to final answer in output in sympy 1.7.1

### ISSUE THREAD

**Issue by Shardul555** [sympy/sympy#20697]
I run the code for this expression in the terminal having installed sympy version 1.7.1 but here the coefficients of y**2 and y are not simplified to final answer. Anyone guide me regarding this issue whether it is done with some purpose or this should be fixed?(Sympy live shell is giving simplified output)
```
>>> from sympy import *
>>> from sympy.abc import y
>>> var('p_0 p_1 p_2 p_3 b_0 b_1 b_2')
(p_0, p_1, p_2, p_3, b_0, b_1, b_2)
>>> Q = (p_0 + (p_1 + (p_2 + p_3/y)/y)/y)/(1 + ((p_3/(b_0*y) + (b_0*p_2 - b_1*p_3)/b_0**2)/y + (b_0**2*p_1 - b_0*b_1*p_2 - p_3*(b_0*b_2 - b_1**2))/b_0**3)/y)
>>> Q.series(y, n=3)
y*(b_0*p_2/p_3 + b_0*(-p_2/p_3 + b_1/b_0)) + y**2*(b_0*p_1/p_3 + b_0*p_2*(-p_2/p_3 + b_1/b_0)/p_3 + b_0*(-p_1/p_3 + (p_2/p_3 - b_1/b_0)**2 + b_1*p_2/(b_0*p_3) + b_2/b_0 - b_1**2/b_0**2)) + b_0 + O(y**3)
>>> simplify(y*(b_0*p_2/p_3 + b_0*(-p_2/p_3 + b_1/b_0)))
b_1*y
>>> simplify(y**2*(b_0*p_1/p_3 + b_0*p_2*(-p_2/p_3 + b_1/b_0)/p_3 + b_0*(-p_1/p_3 + (p_2/p_3 - b_1/b_0)**2 + b_1*p_2/(b_0*p_3) + b_2/b_0 - b_1**2/b_0**2)))
b_2*y**2

```

_Originally posted by @Shardul555 in https://github.com/sympy/sympy/issues/9173#issuecomment-752021479_

**Comment by oscarbenjamin** [comment]
Can you explain what exactly is the issue?

**Comment by Shardul555** [comment]
```
>>> Q.series(y, n=3)
y*(b_0*p_2/p_3 + b_0*(-p_2/p_3 + b_1/b_0)) + y**2*(b_0*p_1/p_3 + b_0*p_2*(-p_2/p_3 + b_1/b_0)/p_3 + b_0*(-p_1/p_3 + (p_2/p_3 - b_1/b_0)**2 + b_1*p_2/(b_0*p_3) + b_2/b_0 - b_1**2/b_0**2)) + b_0 + O(y**3)
```
This is the ouput obtained on sympy 1.7.1 version, 
```
>>> Q.series(y, n=3)
b_2*y**2 + b_1*y + b_0 + O(y**3)
```
This is the output obtained on sympy live shell 
I am not understanding that when on previous versions(used on sympy live shell) simplified output was obtained then why in the current release, output is not simplified to final expression.

**Comment by 0sidharth** [comment]
`git bisect` says 5dc58b7 caused this change.

**Comment by oscarbenjamin** [comment]
CC @sachin-4099 

Maybe something like `ratsimp` could be used with the coefficients of the series.

**Comment by sachin-4099** [comment]
> Maybe something like `ratsimp` could be used with the coefficients of the series.

Yeah, I guess so. Someone can try and find out the most optimal simplification method which can be used to resolve the issue.

**Comment by Shardul555** [comment]
Ok so I will try to do it. Thanks for suggestion@oscarbenjamin

**Comment by Shardul555** [comment]
> `git bisect` says [5dc58b7](https://github.com/sympy/sympy/commit/5dc58b715362d9332078fd7560b322d7a7eeddd1) caused this change.

@0sidharth but this change is not merged finally, so may be ```git bisect``` have given some wrong result, actually I don't have much idea about ```git bisect```

**Comment by Shardul555** [comment]
I tried to change ```_eval_nseries ```function in power.py and expr.py a bit, but errors were occuring for many test cases in different files.
Adding ```ratsimp``` to ```series```function in ```expr.py``` solve purpose a little bit but I need a function other than collect which will simplify inputs like following:
input: ```(8*c**4*v**2 + 6*c**2*v**4 + 5*v**6)/(16*c**6) + 1```
ouput needed: ```5*v**6/(16*c**6) + 3*v**4/(8*c**4) + v**2/(2*c**2) + 1```

output obtained through collect:
```
>>> collect((8*c**4*v**2 + 6*c**2*v**4 + 5*v**6)/(16*c**6) + 1 , v)
1 + (8*c**4*v**2 + 6*c**2*v**4 + 5*v**6)/(16*c**6)
```
@oscarbenjamin , @sachin-4099 can you guide me in this case.
