### ISSUE TITLE
Limit not terminating

### ISSUE THREAD

**Issue by 0sidharth** [sympy/sympy#20704]
The following limit does not terminate, it does not give a `RecursionError` either, it just keeps computing for a long time (for a few minutes at least, did not try ahead of that). I am attaching the output on running with `SYMPY_DEBUG=True`

```
IPython console for SymPy 1.7.dev (Python 3.8.5-64-bit) (ground types: python, debugging: on)

These commands were executed:
>>> from __future__ import division
>>> from sympy import *
>>> x, y, z, t = symbols('x y z t')
>>> k, m, n = symbols('k m n', integer=True)
>>> f, g, h = symbols('f g h', cls=Function)
>>> init_printing()

Documentation can be found at https://docs.sympy.org/dev


In [1]: limit(x*(abs(1/x + y) - abs(y - 1/x))/2, x, 0)
DEBUG: parsing of expression [(1/2, 1, None, None)] with symbol _w 
DEBUG: returned None
DEBUG: parsing of expression [(_w, 1, None, None)] with symbol _w 
DEBUG: returned ([], [(_w, 1, None, None)], 1, False)
DEBUG: parsing of expression [(_w, 1, None, None)] with symbol _w 
DEBUG: returned ([], [(_w, 1, None, None)], 1, False)
DEBUG: parsing of expression [(_w, 1, None, None)] with symbol _w 
DEBUG: returned ([], [(_w, 1, None, None)], 1, False)
DEBUG: parsing of expression [(-1/2, 1, None, None)] with symbol _w 
DEBUG: returned None
DEBUG: parsing of expression [(_w, 1, None, None)] with symbol _w 
DEBUG: returned ([], [(_w, 1, None, None)], 1, False)
DEBUG: parsing of expression [(-1, 1, None, None)] with symbol _w 
DEBUG: returned None
DEBUG: parsing of expression [(_w, 1, None, None)] with symbol _w 
DEBUG: returned ([], [(_w, 1, None, None)], 1, False)
DEBUG: parsing of expression [(-1, 1, None, None)] with symbol _w 
DEBUG: returned None
DEBUG: parsing of expression [(_w, 1, None, None)] with symbol _w 
DEBUG: returned ([], [(_w, 1, None, None)], 1, False)
DEBUG: parsing of expression [(_w, 1, None, None)] with symbol _w 
DEBUG: returned ([], [(_w, 1, None, None)], 1, False)
DEBUG: parsing of expression [(1/2, 1, None, None)] with symbol _w 
DEBUG: returned None
DEBUG: parsing of expression [(_w, 1, None, None)] with symbol _w 
DEBUG: returned ([], [(_w, 1, None, None)], 1, False)
DEBUG: parsing of expression [(_w, 1, None, None)] with symbol _w 
DEBUG: returned ([], [(_w, 1, None, None)], 1, False)
DEBUG: parsing of expression [(_w, 1, None, None)] with symbol _w 
DEBUG: returned ([], [(_w, 1, None, None)], 1, False)
DEBUG: parsing of expression [(_w, 1, None, None)] with symbol _w 
DEBUG: returned ([], [(_w, 1, None, None)], 1, False)
DEBUG: parsing of expression [(-1/2, 1, None, None)] with symbol _w 
DEBUG: returned None
...
```
(keeps repeating)
This limit was correctly computing to 0 before the changes in 5dc58b7 (using `git bisect`). I have been trying to debug this, probably some error in `sympy/core/mul.py:_eval_nseries`, but I am not able to exactly pinpoint the error or the fix.

**Comment by oscarbenjamin** [comment]
CC @sachin-4099

**Comment by czgdp1807** [comment]
> DEBUG: parsing of expression [(1/2, 1, None, None)] with symbol _w 
> DEBUG: returned None
> DEBUG: parsing of expression [(_w, 1, None, None)] with symbol _w 
> DEBUG: returned ([], [(_w, 1, None, None)], 1, False)
> DEBUG: parsing of expression [(_w, 1, None, None)] with symbol _w 
> DEBUG: returned ([], [(_w, 1, None, None)], 1, False)
> DEBUG: parsing of expression [(_w, 1, None, None)] with symbol _w 
> DEBUG: returned ([], [(_w, 1, None, None)], 1, False)
> DEBUG: parsing of expression [(-1/2, 1, None, None)] with symbol _w 
> DEBUG: returned None
> DEBUG: parsing of expression [(_w, 1, None, None)] with symbol _w 
> DEBUG: returned ([], [(_w, 1, None, None)], 1, False)
> DEBUG: parsing of expression [(-1, 1, None, None)] with symbol _w 
> DEBUG: returned None
> DEBUG: parsing of expression [(_w, 1, None, None)] with symbol _w 
> DEBUG: returned ([], [(_w, 1, None, None)], 1, False)
> DEBUG: parsing of expression [(-1, 1, None, None)] with symbol _w 
> DEBUG: returned None
> DEBUG: parsing of expression [(_w, 1, None, None)] with symbol _w 
> DEBUG: returned ([], [(_w, 1, None, None)], 1, False)
> DEBUG: parsing of expression [(_w, 1, None, None)] with symbol _w 
> DEBUG: returned ([], [(_w, 1, None, None)], 1, False)

I am not much familiar with the code base of `limit` API but it seems like the above sequence of steps is repeating.
