### ISSUE TITLE
Wrong results of evalf only for some values of the precision

### ISSUE THREAD

**Issue by maneandrea** [sympy/sympy#20733]
I found some expression `expr` on which `expr.evalf(prec, subs={x:n})` returns zero for some integers `n` even though it shouldn't. This happens only for some seemingly random values of the precision `prec`.

Here is a minimal working example

```python
#!/usr/bin/env python
import sympy
from sympy.abc import x

# Some valid mathematical expression
expr = 1/((x - 9)*(x - 8)*(x - 7)*(x - 4)**2*(x - 3)**3*(x - 2))


def example(prec):
    # This is the string 1.( prec-2 zeroes )1
    almost1 = '1.'+(prec-2)*'0'+'1'
    
    # We replace the integer 1
    res1 = expr.evalf(prec, subs={x:1})
    
    # We replace a Float veeery close to 1
    res_almost1 = expr.evalf(prec, subs={x:sympy.Float(almost1,prec)})

    return res1, res_almost1

wrong = [str(a) for a in range(10,1001) if example(a)[0] == 0]
print(','.join(wrong))
```
This expression is not zero at `x=1` so the print should be empty, however I get

```
11,20,22,29,31,38,40,49,58,67,76,78,85,87,94,96,105,114,123,132,134,141,143,150,152,159,161,170,179,188,190,197,199,206,208,215,217,226,235,244,253,255,262,264,271,273,282,291,300,309,311,318,320,327,329,338,347,356,365,367,374,376,383,385,392,394,403,412,421,423,430,432,439,441,448,450,459,468,477,486,488,495,497,504,506,515,524,533,542,544,551,553,560,562,571,580,589,598,600,607,609,616,618,625,627,636,645,654,663,665,672,674,681,683,692,701,710,719,721,728,730,737,739,748,757,766,775,777,784,786,793,795,802,804,813,822,831,833,840,842,849,851,858,860,869,878,887,896,898,905,907,914,916,925,934,943,952,954,961,963,970,972,981,990,999
```

Furthermore it can be checked that `example(prec)[1]` is arbitrarily close to the correct answer for high enough `prec`, so the problem has to do with the fact that we are replacing an `int`.

**Comment by sidhu1012** [comment]
Check #20479

**Comment by maneandrea** [comment]
@sidhu1012 Thanks for the link. Could you elaborate a bit? Are you saying that you understand the cause, or just that the two issues are related?

**Comment by sidhu1012** [comment]
> @sidhu1012 Thanks for the link. Could you elaborate a bit? Are you saying that you understand the cause, or just that the two issues are related?

It's a known issue. `.evalf` has some long standing precision issues. That issue link I shared elaborates what you have encountered here from development point of view.

**Comment by maneandrea** [comment]
I see, but is it obvious to you why this issue arises only for some specific weird values of the precision rather than, say, only precisions lower than a certain threshold?

**Comment by oscarbenjamin** [comment]
> That issue link I shared elaborates what you have encountered here

I don't think it does. That issue is about evalf on non-standard objects like FiniteSet not being able to pass on precision settings properly when recursing. The expression here is a combination of Mul, Add, Pow so that doesn't apply.

This is a more direct way to show the bug:
```python
In [13]: expr = 1/((x - 9)*(x - 8)*(x - 7)*(x - 4)**2*(x - 3)**3*(x - 2))

In [14]: expr.subs(x, 1)
Out[14]: -1/24192

In [15]: expr.subs(x, 1).n()
Out[15]: -4.13359788359788e-5

In [16]: expr.evalf(subs={x:1})
Out[16]: -4.13359788359788e-5

In [17]: expr.evalf(20, subs={x:1})
Out[17]: 0
```

**Comment by maneandrea** [comment]
Let me add that this is a pretty major problem. It's likely to arise when users want to have numerical errors under control in evaluations, which they think to accomplish by passing the precision explicitly. Ironically, passing the precision explicitly is what makes evaluation unreliable.

I'm sad that this issue has been effectively abandoned.

**Comment by oscarbenjamin** [comment]
It is a significant problem. Most likely it is not difficult to fix though (e.g. a typo somewhere or something like that). The issue is just waiting for someone to work through patiently with a debugger and find out where the evaluation goes wrong.

**Comment by faze-geek** [comment]
@oscarbenjamin 
> The issue is just waiting for someone to work through patiently with a debugger and find out where the evaluation goes wrong.

I did spend some time on debugging .This particularly fails on n= 2 ,11,20 ,22 ,19 ,38 ,40 (not that I see any definite pattern here) . After a basic debug of the recursive structure I think the code bombs at the last recursion before returning the answer .
See line on evalf.py-
`1737                                 result = evalf(self, prec + 4, options)`

**Comment by oscarbenjamin** [comment]
The problem is here:
https://github.com/sympy/sympy/blob/e70690ddc3d5c296cd3241aebf5f68d2d010b344/sympy/core/evalf.py#L713-L715
If the bit count `bc` is large then this can send the mantissa to zero. The bit count only increases in this loop though. Depending on precisely what the precision is the loop will enter this block a different number of times. For this particular expression whenever this is hit three times the mantissa is wiped out.

This looks like the fix:
```diff
diff --git a/sympy/core/evalf.py b/sympy/core/evalf.py
index 0cabbdd..659bee9 100644
--- a/sympy/core/evalf.py
+++ b/sympy/core/evalf.py
@@ -710,9 +710,10 @@ def evalf_mul(v: 'Mul', prec: int, options: OPT_DICT) -> TMP_RES:
         man *= m
         exp += e
         bc += b
-        if bc > 3*working_prec:
+        while bc > 3*working_prec:
             man >>= working_prec
             exp += working_prec
+            bc -= working_prec
         acc = min(acc, w_acc)
     sign = (direction & 2) >> 1
     if not complex_factors:
```

**Comment by faze-geek** [comment]
> The problem is here:
> https://github.com/sympy/sympy/blob/e70690ddc3d5c296cd3241aebf5f68d2d010b344/sympy/core/evalf.py#L713-L715
> If the bit count `bc` is large then this can send the mantissa to zero. The bit count only increases in this loop though. Depending on precisely what the precision is the loop will enter this block a different number of times. For this particular expression whenever this is hit three times the mantissa is wiped out.

I'll check if this test breaks some tests or not and open a pr soon for this!
