### ISSUE TITLE
A function where its second derivative should be equal to the negative of itself

### ISSUE THREAD

**Issue by mshemuni** [sympy/sympy#20744]
I know the title sounds weird. But, I have a function where its second derivative should be equal to the negative of itself.
Such as:

```
f = a*sin(𝑥) + b*cos(𝑥)
f'' = -(a*sin(𝑥) + b*cos(𝑥))
```
I notice with the second derivative of the function above I get:
`−(𝑎sin(𝑥)+𝑏cos(𝑥))`

However, the negative of the function is:
`−𝑎sin(𝑥)−𝑏cos(𝑥)`

The sign is not distributed to the function.
Can that be the problem? 

The weird part is, the second derivative of the function is NOT equal to the negative of the function itself, but the reverse is true. The negative of the second derivative of the function is equal to the function itself.

Here a [jupyter notebook](https://github.com/mshemuni/epic/blob/main/examples/sympy_negative.ipynb).

In the notebook, I printed the version number and did some other tests.

jupyter notebook: https://github.com/mshemuni/epic/blob/main/examples/sympy_negative.ipynb

**Comment by maneandrea** [comment]
`==` does not check for mathematical equality

from the documentation [https://docs.sympy.org/dev/tutorial/gotchas.html#equals-signs](https://docs.sympy.org/dev/tutorial/gotchas.html#equals-signs)
