### ISSUE TITLE
sympy.vector  Implicit_Region result wrong for perimeter of unit circle  version 1.7.1

### ISSUE THREAD

**Issue by woodringct** [sympy/sympy#20748]
Using vector_integrate in the examples in the documentation:

from sympy.vector import ImplicitRegion
c2 = ImplicitRegion((x, y), (x - 2)**2 + (y - 1)**2 - 9)
vector_integrate(1, c2)
12*pi

should this not be 6*pi since the radius of the circle is 3?

It seems like you always get the correct answer multiplied by a factor of 2 for any given radius.

**Comment by friyaz** [comment]
@woodringct Thanks for pointing this out. This is a bug. I don't know how I missed this. 

The PR for this has been made. It was due to an incorrect substitution.
