### ISSUE TITLE
diffgeom.CoordSystem.transform with indirect relation raises KeyError

### ISSUE THREAD

**Issue by dboeckenhoff** [sympy/sympy#20742]
Below code is a minimal example for an indirect transform via a temporary intermediate coordinate system. `parabolic2D.transform(poloidal)` raises a KeyError.

MWE:
```
"""
2D manifold coordinate systems
"""
import sympy
import sympy.diffgeom

CARTESIAN2D = "cartesian2D"
POLOIDAL = "poloidal"
PARABOLIC2D = "parabolic2D"

m = sympy.diffgeom.Manifold("M", 2)
p = sympy.diffgeom.Patch("P", m)
RELATIONS = {}

# #########
# cartesian
# #########
x, y = sympy.symbols("x y")

# #########
# poloidal
# #########
r, theta = sympy.symbols("r theta", nonnegative=True)
RELATIONS[(CARTESIAN2D, POLOIDAL)] = sympy.Lambda(
    (x, y),
    sympy.Matrix(
        [
            sympy.sqrt(x ** 2 + y ** 2),
            sympy.atan2(y, x)
        ]
    )
)
RELATIONS[(POLOIDAL, CARTESIAN2D)] = sympy.Lambda(
    (r, theta),
    sympy.Matrix(
        [
            r * sympy.cos(theta),
            r * sympy.sin(theta)
        ]
    )
)

# #########
# parabolic
# #########
sigma, tau = sympy.symbols("sigma tau")
RELATIONS[(PARABOLIC2D, CARTESIAN2D)] = sympy.Lambda(
    (sigma, tau),
    sympy.Matrix(
        [
            sigma * tau,
            1 / 2 * (tau**2 - sigma**2)
        ]
    )
)

cartesian2D = sympy.diffgeom.CoordSystem(CARTESIAN2D, p, [x, y], RELATIONS)
poloidal = sympy.diffgeom.CoordSystem(POLOIDAL, p, [r, theta], RELATIONS)
parabolic2D = sympy.diffgeom.CoordSystem(PARABOLIC2D, p, [sigma, tau], RELATIONS)


if __name__ == "__main__":
    print(parabolic2D.transform(poloidal))  # raises a KeyError
    print(poloidal.transform(parabolic2D))  # raises a KeyError
```

This raises a KeyError.

> Traceback (most recent call last):
>   File "/opt/anaconda/envs/py38/lib/python3.8/pdb.py", line 1703, in main
>     pdb._runscript(mainpyfile)
>   File "/opt/anaconda/envs/py38/lib/python3.8/pdb.py", line 1572, in _runscript
>     self.run(statement)
>   File "/opt/anaconda/envs/py38/lib/python3.8/bdb.py", line 580, in run
>     exec(cmd, globals, locals)
>   File "<string>", line 1, in <module>
>   File "/home/IPP-HGW/dboe/git/tfields/tfields/bases/manifold_2.py", line 1, in <module>
>     """
>   File "/opt/anaconda/envs/py38/lib/python3.8/site-packages/sympy/diffgeom/diffgeom.py", line 480, in transform
>     transf = self.transformation(sys)
>   File "/opt/anaconda/envs/py38/lib/python3.8/site-packages/sympy/diffgeom/diffgeom.py", line 354, in transformation
>     return self._indirect_transformation(self, sys)
>   File "/opt/anaconda/envs/py38/lib/python3.8/site-packages/sympy/core/cache.py", line 72, in wrapper
>     retval = cfunc(*args, **kwargs)
>   File "/opt/anaconda/envs/py38/lib/python3.8/site-packages/sympy/diffgeom/diffgeom.py", line 376, in _indirect_transformation
>     path = cls._dijkstra(sys1, sys2)
>   File "/opt/anaconda/envs/py38/lib/python3.8/site-packages/sympy/diffgeom/diffgeom.py", line 414, in _dijkstra
>     visit(sys1)
>   File "/opt/anaconda/envs/py38/lib/python3.8/site-packages/sympy/diffgeom/diffgeom.py", line 406, in visit
>     path_dict[sys][2] = 1
> KeyError: parabolic2D
> 

I think I found the reson already: In dijkstra routing the comparison is done between a CoordSystem and sympy.Str
DEBUGGING:

```
Uncaught exception. Entering post mortem debugging
Running 'cont' or 'step' will restart the program
> /opt/anaconda/envs/py38/lib/python3.8/site-packages/sympy/diffgeom/diffgeom.py(406)visit()
-> path_dict[sys][2] = 1
(Pdb) path_dict
{cartesian2D: [0, [], 0], poloidal: [0, [], 0], parabolic2D: [0, [], 0]}
(Pdb) sys
parabolic2D
(Pdb) hash(sys)
-2150956724454717966
(Pdb) [hash(k) for k in path_dict]
[6233656281303402583, 5480353473597806494, -1340528192013030397]
(Pdb) type(sys)
<class 'sympy.diffgeom.diffgeom.CoordSystem'>
(Pdb) [type(k) for k in path_dict]
[<class 'sympy.core.symbol.Str'>, <class 'sympy.core.symbol.Str'>, <class 'sympy.core.symbol.Str'>]
```

**Comment by Halfogerty** [comment]
I started looking into this, I noticed another bug in addition to the type mismatch in the Dijkstra algorithm.  Your example only gives the forward transformation from parabolic2D to cartesian2D, so in order to solve `poloidal.transform(parabolic2D)` the `transform `method will need to calculate the inverse transformation from cartesian2D to parabolic2D, which will raise an exception, see https://github.com/sympy/sympy/issues/21356
