### ISSUE TITLE
Expected Value of the Product of Two Uniform RVs Fails

### ISSUE THREAD

**Issue by craymichael** [sympy/sympy#20756]
See title. As these variables are independent, I would expect this to give the result `E[XY] = E[X] * E[Y] = 0 * 0 = 0`

```python
from sympy import stats

X = stats.Uniform('X', -1, +1)
Y = stats.Uniform('Y', -1, +1)

stats.E(X * Y)
```

Results in `TypeError: 'NegativeInfinity' object cannot be interpreted as an integer`

**Comment by oscarbenjamin** [comment]
This shouldn't raise an error but if `X` and `Y` are independent then the relationship should be `E[X*Y] = E[X]*E[Y]` and not `E[X]+E[Y]` (although both give zero in this case).

**Comment by craymichael** [comment]
Whoops that's my mistake - guess I need more coffee...edited in the question
