### ISSUE TITLE
Alternative way to access the frequency of each variable in an expression

### ISSUE THREAD

**Issue by evatiwari** [sympy/sympy#20772]
The line at https://github.com/sympy/sympy/blob/ab39cbb48e23284889ca851c35845ec9b66a37c9/sympy/core/function.py#L2292
uses ```variable_count``` to access the frequency of each variable in an ```Expr```, but ```variable_count ```is not an attribute of ```Expr```, which int turn leads to issues like #20037 . Any leads on how to fix this would be appreciated.

**Comment by oscarbenjamin** [comment]
I replied in the issue.

**Comment by evatiwari** [comment]
@oscarbenjamin thanks a lot, I'll try to help.

**Comment by hyadav2k** [comment]
@oscarbenjamin Kindly close this issue also.
Thanks.

**Comment by oscarbenjamin** [comment]
Ah, yes. This has been fixed.
