### ISSUE TITLE
understanding parse_expr with bool expression in function arguments

### ISSUE THREAD

**Issue by yanghao** [sympy/sympy#20787]
Sympy version: 1.7.1
Python version: 3.8.5
OS: Ubuntu 20.04

I know using bool expression this way is wrong and won't get the desired result (I have read the gotcha section), but just wondering how sympy handles bool expression in general.

This code works (e.g. no exception generated):

```
from sympy.parsing.sympy_parser import parse_expr

x_str = "IF(c < 1, 0, 1)"
# c_str = "IF(d == 0, 0, IF(d == 1, 1, 2))"
c_str = "IF(d == 0, 0, 1)"
x = parse_expr(x_str)
c = parse_expr(c_str)
d = {"x": x, "c": c}
print("local dict:")
print(d)
x = parse_expr(x_str, local_dict=d)
c = parse_expr(c_str, local_dict=d)
```

This code does NOT work:

```
from sympy.parsing.sympy_parser import parse_expr

x_str = "IF(c < 1, 0, 1)"
c_str = "IF(d == 0, 0, IF(d == 1, 1, 2))"
# c_str = "IF(d == 0, 0, 1)"
x = parse_expr(x_str)
c = parse_expr(c_str)
d = {"x": x, "c": c}
print("local dict:")
print(d)
x = parse_expr(x_str, local_dict=d)
c = parse_expr(c_str, local_dict=d)
```

With exception generated:

```
local dict:
{'x': IF(c < 1, 0, 1), 'c': IF(False, 0, IF(False, 1, 2))}
Traceback (most recent call last):
  File "t.py", line 11, in <module>
    x = parse_expr(x_str, local_dict=d)
  File "/usr/lib/python3/dist-packages/sympy/parsing/sympy_parser.py", line 1008, in parse_expr
    return eval_expr(code, local_dict, global_dict)
  File "/usr/lib/python3/dist-packages/sympy/parsing/sympy_parser.py", line 902, in eval_expr
    expr = eval(
  File "<string>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/sympy/core/expr.py", line 399, in __lt__
    return self._cmp(other, "<", StrictLessThan)
  File "/usr/lib/python3/dist-packages/sympy/core/expr.py", line 340, in _cmp
    raise TypeError("Invalid comparison of non-real %s" % me)
TypeError: Invalid comparison of non-real IF(False, 0, IF(False, 1, 2))
```
Any idea why the second case can not be parsed properly? Thanks!

**Comment by nlchar** [comment]
Does sympy version 2.5 exist? As I know the latest release is 1.7.1. Correct me if I'm wrong.

**Comment by yanghao** [comment]
Yes it is 1.7.1 ... sorry I mixed it up with networkx version ....

**Comment by oscarbenjamin** [comment]
I don't get any exception running this with version 1.7.1 or with master.

**Comment by naveensaigit** [comment]
This is reproducible on SymPy Live (v 1.5.1)

**Comment by oscarbenjamin** [comment]
SymPy Live has lots of issues compared to master because it is running an older version of sympy.

@yanghao are you sure you are using sympy 1.7.1? Can you show the output from running this:
```python
from sympy import __version__
print('sympy version', __version__)

from sympy.parsing.sympy_parser import parse_expr

x_str = "IF(c < 1, 0, 1)"
c_str = "IF(d == 0, 0, IF(d == 1, 1, 2))"
# c_str = "IF(d == 0, 0, 1)"
x = parse_expr(x_str)
c = parse_expr(c_str)
d = {"x": x, "c": c}
print("local dict:")
print(d)
x = parse_expr(x_str, local_dict=d)
c = parse_expr(c_str, local_dict=d)
```
When I run it I get:
```console
$ python t.py 
sympy version 1.7.1
local dict:
{'x': IF(c < 1, 0, 1), 'c': IF(False, 0, IF(False, 1, 2))}
```

**Comment by yanghao** [comment]
@oscarbenjamin Indeed the latest version from pip install is still 1.5.1 ... somehow I addicted to the "fact" (probably from the sympy documentation I was viewing is version 1.7.1) that I was using the latest sympy.

On 1.7.1 indeed there is no error. And I had an even more complicated case also running through just fine.

Thanks a lot and sorry for the mis-information.

**Comment by oscarbenjamin** [comment]
Okay thanks for reporting this and it's good that we've cleared it up now.

Possibly you got 1.5.1 from pip if you used pip under Python 2.7. The last sympy release to support Python 2.7 is 1.5.1. Newer releases are only for Python 3.x.

**Comment by yanghao** [comment]
Now that you mind me I might have installed it directly from apt (apt install python3-sympy), which for ubuntu seems still at 1.5.1.

I am using python3.8 or python3.9, long dropped python2 already :-)
