### ISSUE TITLE
Vector Equality Operation Bug

### ISSUE THREAD

**Issue by nlchar** [sympy/sympy#20784]
Hello. Please, have a look at [this collab notebook](https://colab.research.google.com/drive/1CHdGhZ23tdRW6evb2d56gRY5CUr2nL4l?usp=sharing). 
Here I try to check if A' x B' = (A x B)', where x is cross-product and (') is expressing a vector in coordinate system X into coordinate system X'. However, sympy fails to conclude the equality of these vectors until the expand operation on the vectors is performed.

**Comment by nlchar** [comment]
sympy.version == 1.7.1

**Comment by oscarbenjamin** [comment]
This is explained in the docs:
https://docs.sympy.org/latest/gotchas.html#double-equals-signs

Comparing with `==` compares expressions to see if they have the exact same form.
