### ISSUE TITLE
Strange behaviour of singleton

### ISSUE THREAD

**Issue by sayandip18** [sympy/sympy#20795]
```
>>> sympify(0.0) == S.false
True
>>> S.false == sympify(0.0)
False
```
Both should produce the same result

**Comment by oscarbenjamin** [comment]
Yes, it should be False. @AaronStiff opened another issue #20796 following on from this. I don't think we need two issues so @AaronStiff could have just commented here but since there is now more useful information in #20796 I'll close this one.

**Comment by AaronStiff** [comment]
Oops. Didn't see this one. Sorry about that. I created the issue right after discussing it with @asmeurer.
