### ISSUE TITLE
Basic: a has_free method method is needed

### ISSUE THREAD

**Issue by oscarbenjamin** [sympy/sympy#20809]
While working on #20780 and in the discussions in https://github.com/sympy/sympy/pull/20757#issuecomment-758815994 I've realise that there is a need for a new primitive in `Basic`.

The problem is to determine whether or not a `Basic` expression contains another expression but taking into account bound vs free symbols. We can normally take account of this distinction using `free_symbols` and `subs` does this already but `xreplace` and `replace` do not:
```python
In [1]: I = Integral(x, (x, 0, 1))

In [2]: I
Out[2]: 
1     
⌠     
⎮ x dx
⌡     
0     

In [3]: I.doit()
Out[3]: 1/2

In [4]: I.has(x)
Out[4]: True

In [5]: I.doit().has(x)
Out[5]: False

In [6]: I.free_symbols
Out[6]: set()

In [7]: x in I.free_symbols
Out[7]: False

In [8]: I.subs(x, y)
Out[8]: 
1     
⌠     
⎮ x dx
⌡     
0     

In [10]: I.xreplace({x: y})
Out[10]: 
1     
⌠     
⎮ y dy
⌡     
0 
```
The logic for distinguishing between free and bound symbols is contained in `subs` (`_eval_subs`) and `free_symbols` to ensure that symbols bound by an expression are not "propagated" out as free symbols to the outer expression.

However `free_symbols` only works for symbols. In some contexts other expressions can be used in place of symbols e.g.:
```python
In [11]: Poly(sin(x)**2, sin(x))
Out[11]: Poly((sin(x))**2, sin(x), domain='ZZ')
```
This is not handled uniformly though because of the use of `free_symbols` in contexts where a non-symbol could also be treated as a "symbol":
```python
In [17]: (1/f(x)).is_polynomial(f(x))
Out[17]: True

In [18]: (1/x).is_polynomial(x)
Out[18]: False
```
That particular problem is caused by the use of `free_symbols` here:
https://github.com/sympy/sympy/blob/9d610300d8b9b38c66b0e26be642fe7a3e15ef1e/sympy/core/expr.py#L2546-L2549

It would be possible to fix `is_polynomial` by using `has` so instead of
```python
        if self.free_symbols.intersection(syms) == set():
```
we could use
```python
        if self.has(*syms):
```
However that uses `has` which is a lower-level `Basic` routine that ignores the distinction between free and bound symbols:
```python
In [5]: I = Integral(x, (x, 0, 1))

In [6]: I
Out[6]: 
1     
⌠     
⎮ x dx
⌡     
0     

In [7]: I.doit()
Out[7]: 1/2

In [8]: I.free_symbols
Out[8]: set()

In [9]: I.doit().free_symbols
Out[9]: set()

In [10]: I.has(x)
Out[10]: True

In [11]: I.doit().has(x)
Out[11]: False
```

I think that what is needed is a new `Basic` primitive for these kinds of situations. Checking `free_symbols` doesn't work because that's only for symbols. Checkins with `has` doesn't work because it's doesn't understand free vs bound symbols/expressions.

I propose a new method/function for `Basic` called `has_free` that will check if an expression contains another expression but with no bound variables. It could be implemented like:
```python
def has_free(obj, syms):
    return _find_free(obj, syms) is not None

def _find_free(obj, syms):
    if obj in syms:
        return obj
    bound = set(getattr(obj, 'bound_symbols', []))
    for arg in obj.args:
        subobj = _find_free(arg, syms)
        if subobj:
            if not bound or not subobj.free_symbols & bound:
                return subobj
```
Actually though there is a case that this does not handle which is when the same symbol is both free and bound:
```python
In [18]: Integral(x, (x, 0, x)).bound_symbols
Out[18]: [x]

In [19]: Integral(x, (x, 0, x)).free_symbols
Out[19]: {x}

In [20]: has_free(Integral(x, (x, 0, x)), {x})
Out[20]: False
```
Maybe something else is needed. Perhaps `has_free` needs a special implementation for classes like `Integral`...

Maybe it should be a `Basic` method...

**Comment by ckmganesh** [comment]
Is integral the only function which encounters this problem.I guess many other functions can face this problem if I'm not wrong

**Comment by hyadav2k** [comment]
> Actually though there is a case that this does not handle which is when the same symbol is both free and bound:
> 
> ```python
> In [18]: Integral(x, (x, 0, x)).bound_symbols
> Out[18]: [x]
> 
> In [19]: Integral(x, (x, 0, x)).free_symbols
> Out[19]: {x}
> 
> In [20]: has_free(Integral(x, (x, 0, x)), {x})
> Out[20]: False
> ```
> 

@oscarbenjamin, what if we add:
``` py
def has_free(obj, syms):
        if obj.free_symbols == set(obj.bound_symbols):
            return obj.doit().free_symbols == syms
        return _find_free(obj, syms) is not None
```
in the code you suggested, this covers the edge case metioned `Integral(x, (x, 0, x)).has_free({x})`.

**Comment by oscarbenjamin** [comment]
We definitely can not use `doit` here. The `doit` function evaluated integrals which in general can be extremely slow. The `has_free` function is needed in situations where it should fast. In fact I want it to be faster than `has` which is already too slow.

> Is integral the only function which encounters this problem.

There are other expression classes that have bound symbols. I don't know of a full list:
```python
In [23]: Sum(x, (x, 0, 4))
Out[23]: 
  4    
 ___   
 ╲     
  ╲    
  ╱   x
 ╱     
 ‾‾‾   
x = 0  

In [24]: Sum(x, (x, 0, 4)).free_symbols
Out[24]: set()

In [25]: Lambda(x, 2*x)
Out[25]: x ↦ 2⋅x

In [26]: Lambda(x, 2*x).free_symbols
Out[26]: set()

In [27]: ConditionSet(x, x>2, Integers)
Out[27]: {x | x ∊ ℤ ∧ (x > 2)}

In [28]: ConditionSet(x, x>2, Integers).free_symbols
Out[28]: set()
```
Another issue is that not all classes with bound symbols have the `bound_symbols` property:
```python
In [11]: M = FunctionMatrix(4, 4, Lambda((i, j), i+j))

In [12]: M
Out[12]: [i + j]

In [13]: M.as_explicit()
Out[13]: 
⎡0  1  2  3⎤
⎢          ⎥
⎢1  2  3  4⎥
⎢          ⎥
⎢2  3  4  5⎥
⎢          ⎥
⎣3  4  5  6⎦

In [14]: M.free_symbols
Out[14]: set()

In [15]: M.bound_symbols
---------------------------------------------------------------------------
AttributeError 
```

**Comment by oscarbenjamin** [comment]
> in the code you suggested, this covers the edge case metioned `Integral(x, (x, 0, x)).has_free({x})`.

What is actually needed is some code specifically for `Integral` that can determine if a sub-expression of either the integrand or the limits contains a bound variable. Because multiple integrals are flattened this is more complicated than it otherwise would be:
```python
In [20]: Integral(x, (x, exp(y)), (y, z))
Out[20]: 
   y        
z ℯ         
⌠ ⌠         
⎮ ⎮  x dx dy
⌡ ⌡         
            

In [21]: Integral(x, (x, exp(y)), (y, z)).doit()
Out[21]: 
 2⋅z
ℯ   
────
 4  
```
Here `exp(y)` is not free because `y` is bound and becomes `z` so `has_free({exp(y)})` should be `False`.

It would be too much for `has_free` to say that `exp(2*z)` is free in the unevaluated integral (there would be no way to know that without evaluating the integral). The definition of what `has_free` should give is more or less that it matches what you would be able to substitute with `subs`:
```python
In [23]: Integral(x, (x, exp(y)), (y, z)).subs(exp(y), t)
Out[23]: 
   y        
z ℯ         
⌠ ⌠         
⎮ ⎮  x dx dy
⌡ ⌡         
```

**Comment by hyadav2k** [comment]
@oscarbenjamin, Can you please tell what should be the output for the following:
```
1) Integral(f(x),f(x)).has_free({x})
2) Integral(f(x),(f(x),0,x)).has_free({f(x)})
3) Integral(f(x),(f(x),0,x)).has_free({x})
```
IMO,
```
1) True
2) False
3) True
```

**Comment by oscarbenjamin** [comment]
That's correct

**Comment by hyadav2k** [comment]
It gives true for the 2nd case `Integral(f(x),(f(x),0,x)).has_free({f(x)})`

**Comment by oscarbenjamin** [comment]
Do you mean the sample code I gave above?

As I said that code does not entirely work and needs to be improved. There needs to be a specific implementation for Integral I think.

**Comment by hyadav2k** [comment]
> Do you mean the sample code I gave above?
> 
Yes, I meant that.

>As I said that code does not entirely work and needs to be improved. There needs to be a specific implementation for Integral I think.
>
It works for most cases. 
I fixed it in the case when the same symbol is both free and bound, even if `f(x)` is same instead of symbol like in `Integral(f(x),(f(x),0,f(x))).has_free({f(x)})`.
Kindly suggest should I make a PR and then improve it further or some other idea.
My approach: Stored in the list for bound and free symbols and then took their intersection and checked if `syms` lie in the intersection or not.

**Comment by oscarbenjamin** [comment]
If you show your code here I'm sure I can find an example that doesn't work. We need to do more than just check free and bound symbols.

**Comment by hyadav2k** [comment]
Sure, I added in `has_free` function:
``` py
def has_free(obj, syms):
    fs=[]
    bs=[]
    arg=Symbol('arg')
    from sympy import Function
    from sympy.core.numbers import Integer
    for i in range(1,len(obj.args)):
        arg=obj.args[i]
        if isinstance(arg,Tuple):
            larg=list(arg)
            l=len(larg)
            if l == 1:
                if isinstance(larg[0],Symbol) or isinstance(larg[0],Function):
                    bs.append(larg[0])
            elif l == 2:
                bs.append(larg[0])
                if not isinstance(larg[1],Integer):
                    fs.append(larg[1])
            elif l == 3:
                bs.append(larg[0])
                if not isinstance(larg[1],Integer):
                    fs.append(larg[1])
                if not isinstance(larg[2],Integer):
                    fs.append(larg[2])
    if set(fs).intersection(set(bs)) is not None:
        if syms == set(fs).intersection(set(bs)):
            return True
    return _find_free(obj, syms) is not None
```

**Comment by oscarbenjamin** [comment]
Is that to be used with the same `_find_free` function above?

I don't this approach can work in general as it needs to explore all args recursively. Here's an example that fails:
```python
In [4]: has_free(Integral(x, (x, 0, f(x)+1)), {f(x)})
Out[4]: False
```
Also you should check that `obj` is an `Integral` before presuming to understand the meaning of its `args`.

**Comment by hyadav2k** [comment]
>Is that to be used with the same _find_free function above?
>
Yes, the code added is for handling the case when the same symbol is both free and bound, I am using `_find_free` provided by you for other cases. `has_free(Integral(x, (x, 0, f(x)+1)), {f(x)})` is handled by `find_free`. 

``` py
def has_free(obj, syms):
    fs=[]
    bs=[]
    arg=Symbol('arg')
    from sympy import Function
    from sympy.core.numbers import Integer
    for i in range(1,len(obj.args)):
        arg=obj.args[i]
        if isinstance(arg,Tuple):
            larg=list(arg)
            l=len(larg)
            if l == 1:
                if isinstance(larg[0],Symbol) or isinstance(larg[0],Function):
                    bs.append(larg[0])
            elif l == 2:
                bs.append(larg[0])
                if not isinstance(larg[1],Integer):
                    fs.append(larg[1])
            elif l == 3:
                bs.append(larg[0])
                if not isinstance(larg[1],Integer):
                    fs.append(larg[1])
                if not isinstance(larg[2],Integer):
                    fs.append(larg[2])
    if set(fs).intersection(set(bs)) is not None:
        if syms == set(fs).intersection(set(bs)):
            return True
    for arg in fs:
        if arg.has(list(syms)[0]):
            return True
    return _find_free(obj, syms) is not None

def _find_free(obj, syms):
    if obj in syms:
        return obj
    bound = set(getattr(obj, 'bound_symbols', []))
    for arg in obj.args:
        subobj = _find_free(arg, syms)
        if subobj:
            if not bound or not subobj.has(list(bound)[0]):
                return subobj
```

@oscarbenjamin, this covers all the cases mentioned till now.
Kindly give your opinion.
Thanks

**Comment by oscarbenjamin** [comment]
This case should give False:
```python
In [9]: I = Integral(x, (x, 0, f(x)), (f(x), 0, y))

In [10]: I
Out[10]: 
y f(x)             
⌠  ⌠               
⎮  ⎮   x dx d(f(x))
⌡  ⌡               
0  0               

In [11]: I.doit()
Out[11]: 
 3
y 
──
6 

In [12]: has_free(I, {f(x)})
Out[12]: True
```

**Comment by hyadav2k** [comment]
``` py
if set(fs).intersection(set(bs)) is not None:
  if syms == set(fs).intersection(set(bs)):
      if fs.index(list(syms)[0]) >= bs.index(list(syms)[0]):
          return True
      else:
          flag=False
if flag:
  for arg in fs:
      if arg.has(list(syms)[0]):
          return True
return _find_free(obj, syms) is not None
```
flag is initially set to True.

These changes will resolve it, but this way it will be more of a hit and trial approach. I will try to find some better approach.
Kindly suggest if some idea comes up.
Thank you for answering.

**Comment by oscarbenjamin** [comment]
I commented on #20852 but I think it is better to say this here in the issue:

The way I would think about this for integral is something like:
```python
In [5]: a = Integral(x, (y, 0, z), (t, m, n))

In [6]: a
Out[6]: 
n z        
⌠ ⌠        
⎮ ⎮ x dy dt
⌡ ⌡        
m 0 
```
Now for `a.has_free(syms)` we should work inwards from the outermost integral:

1. If either m or n `has_free(syms)` return True.
2. Otherwise if the inner `Integral(x, (y, 0, z)).has_free(syms)` for a subexpression that is not masked by `t` then return True

For that I think that there needs to be a helper function that can extract the actual expressions from the inner integral that match syms.

**Comment by oscarbenjamin** [comment]
Maybe what is actually needed is a generator that can return expressions from syms that are free in the expression like:
```python
def iter_free_in(expr, syms):
    if expr in syms:
        yield expr
    elif hasattr(expr, _eval_iter_free_in):
        # Special method for some classes like Integral:
        yield from expr._eval_iter_free_in(syms)
    else:
        for arg in expr.args:
            yield from iter_free_in(arg)
```
Then `has_free` is just:
```python
def has_free(expr, syms):
    for _ in iter_free_in(expr, syms):
        return True
    else:
        return False
```
I think we need something like `iter_free_in` to be able to implement the logic for `Integral` because we need to loop over the expressions from syms that are free in the integrand to determine whether they are bound by the integration variable.

**Comment by asmeurer** [comment]
I find the proposed method here to be confusing. I don't think "free" or "bound" makes sense for larger subexpressions. I also don't understand why it's needed over just checking if x is in free_symbols. The example given was Poly, but I think the generators of a Poly are not bound. Expression generators could be thought of being represented by a dummy bound variable, but that is don't implicitly.

**Comment by oscarbenjamin** [comment]
Perhaps `has_free` is not a good name but this is definitely needed in many places like `Poly/poly`, `linsolve`, `solve`, `integrate` etc.

The basic problem is wanting to do something like this:
```python
In [8]: eqs = [f(x) + g(x) - 1, f(x) - g(x)]

In [9]: linsolve(eqs, [f(x), g(x)])
Out[9]: {(1/2, 1/2)}
```
Here we treat `f(x)`, `g(x)` as symbols although they are not atomic symbols and don't appear in `free_symbols`:
```python
In [10]: f(x).free_symbols
Out[10]: {x}
```
When the inputs are nonlinear `linsolve` should give an error:
```python
In [1]: linsolve([f(x)**2 - g(x)], [f(x), g(x)])
---------------------------------------------------------------------------
PolyNonlinearError 
```
However this fails to detect other kinds of nonlinearity:
```python
In [3]: linsolve([f(x) - exp(g(x))], [f(x), g(x)])
Out[3]: 
⎧⎛ g(x)      ⎞⎫
⎨⎝ℯ    , g(x)⎠⎬
⎩             ⎭
```
The reason that fails is because:
```python
In [4]: g(x) in exp(g(x)).free_symbols
Out[4]: False
```
The code that extracts the linear coefficients from the equation concludes that `exp(g(x))` is a "constant" term because known of the "unknowns" are contained in its free symbols.

That could be fixed by using `has` instead of `free_symbols` but then it would fail in the case of bound symbols which are currently handled correctly:
```python
In [9]: linsolve([x - Integral(x, (x, 0, z))], [x, y])
Out[9]: 
⎧⎛z        ⎞⎫
⎪⎜⌠        ⎟⎪
⎨⎜⎮ x dx, y⎟⎬
⎪⎜⌡        ⎟⎪
⎩⎝0        ⎠⎭

In [10]: linsolve([x - Integral(x, (x, 0, x))], [x, y])
...
NonlinearError: Integral(x, (x, 0, x)) contains an element of the set of generators.
```

We also need this to much faster than `has`. In #20780 I've made linsolve much faster for sparse systems. In that PR the main slow part for a sparse system is converting from Expr into the DomainMatrix representation which needs something like `has_free`.

If you try the integral from #19651 and interrupt after around 30 seconds you'll find it is making a load of calls to `has` that are slow from this line:
https://github.com/sympy/sympy/blob/07a6388bc237a2c43e65dc3cf932373e4d06d91b/sympy/integrals/heurisch.py#L706
The `has` call is slow because it is called with a large number of `syms` and the internal implementation of `has` does nothing to handle that case efficiently.

In #20780 I have a more efficient implementation for extracting the coefficients from a linear equation but it can not correctly handle all cases because neither `free_symbols` nor `has` does the right thing in all cases. At the moment it uses `free_symbols` (at the bottom) just because that is more efficient than `has`:
```python
def _linear_eq_to_dict(eqs, syms):
    syms = set(syms)
    eqsdict, eqs_rhs = [], []
    for eq in eqs:
        rhs, eqdict = _lin_eq2dict(eq, syms)
        eqsdict.append(eqdict)
        eqs_rhs.append(rhs)
    return eqsdict, eqs_rhs


def _lin_eq2dict(a, symset):
    if a in symset:
        return S.Zero, {a: S.One}
    elif a.is_Add:
        terms_list = defaultdict(list)
        coeff_list = []
        for ai in a.args:
            ci, ti = _lin_eq2dict(ai, symset)
            coeff_list.append(ci)
            for mij, cij in ti.items():
                terms_list[mij].append(cij)
        coeff = Add(*coeff_list)
        terms = {sym: Add(*coeffs) for sym, coeffs in terms_list.items()}
        return coeff, terms
    elif a.is_Mul:
        terms = terms_coeff = None
        coeff_list = []
        for ai in a.args:
            ci, ti = _lin_eq2dict(ai, symset)
            if not ti:
                coeff_list.append(ci)
            elif terms is None:
                terms = ti
                terms_coeff = ci
            else:
                raise PolyNonlinearError
        coeff = Mul(*coeff_list)
        if terms is None:
            return coeff, {}
        else:
            terms = {sym: coeff * c for sym, c in terms.items()}
            return  coeff * terms_coeff, terms
    elif a.is_Equality:
        return _lin_eq2dict(expand_mul(a.lhs - a.rhs), symset)
    elif not a.free_symbols & symset:
        return a, {}
    else:
        raise PolyNonlinearError
```

**Comment by asmeurer** [comment]
Derivative has an extended way of specifying what is a "symbol" for the purposes of differentiation which includes functions like f(x) but still excludes arbitrary expressions. Should we extend that to other methods that operate on symbols? The examples you give fail because they try to treat f(x) as a symbol, which is a common thing to do. But these operations still wouldn't make sense if you replaced f(x) with an arbitrary expression.

**Comment by oscarbenjamin** [comment]
There are other cases like:
```python
In [1]: linsolve([f(x).diff(x) + g(x).diff(x), f(x).diff(x) - f(x)], [f(x).diff(x), g(x).diff(x)])
Out[1]: {(f(x), -f(x))}
```
Here we want `f(x).diff(x)` to be treated as being "independent" of `f(x)` although:
```python
In [2]: f(x).diff(x).has(f(x))
Out[2]: True
```
Perhaps different situations call for different things here. The awkward thing is handling classes like `Integral` that have bound symbols but maybe what would be most useful is if they had a way to report when some subexpression was "masked" through bound symbols. Then it would be easier to build recursive crawlers but the crawlers could still be domain specific...

**Comment by smichr** [comment]
> what would be most useful is if they had a way to report when some subexpression was "masked" through bound symbols

That is what `as_dummy` can be used for:

Recall
```python
>>> Integral(f(x),(f(x),1,2))
Integral(f(x), (f(x), 1, 2))
>>> _.as_dummy()
Integral(_0, (_0, 1, 2))
>>> Integral(f(x),(x,1,2))
Integral(f(x), (x, 1, 2))
>>> _.as_dummy()
Integral(f(_0), (_0, 1, 2))
```
so if an expression has dummy symbols in it then it will not be found with `has` in the dummy form.
```python
def has_free(expr, x):
    if isinstance(x, Symbol):
        return x in expr.free_symbols
    return expr.as_dummy().has(x)
```

**Comment by hyadav2k** [comment]
> That is what `as_dummy` can be used for:
> 
@smichr, this case seems to fail for using `as_dummy`.
```py
In [1]: Integral(x, (x, 0, f(x)+1))
Out[1]:
f(x) + 1
   ⌠
   ⎮     x dx
   ⌡
   0

In [2]: Integral(x, (x, 0, f(x)+1)).as_dummy()
Out[2]:
f(x) + 1
   ⌠
   ⎮     _0 d(_0)
   ⌡
   0

In [3]: Integral(x, (x, 0, f(x)+1)).as_dummy().has(x)
Out[3]: True

In [4]: Integral(x, (x, 0, f(x)+1)).doit()
Out[4]:
          2
(f(x) + 1)
───────────
     2

In [5]: Integral(x, (x, 0, f(x)+1)).has_free({x})
Out[5]: False
```

**Comment by oscarbenjamin** [comment]
> @smichr, this case seems to fail for using `as_dummy`.

That output from `has_free` does not seem correct to me:
```
In [5]: Integral(x, (x, 0, f(x)+1)).has_free({x})
Out[5]: False
```
There `x` is free in the result as you can see if you use `doit`.

The reason we need `has_free` is to handle situations in which we want to check for a non-symbol subexpression but where some part of that subexpression might be bound e.g.:
```python
In [22]: I = Integral(Derivative(f(x)), (x, 0, y))

In [23]: I
Out[23]: 
y            
⌠            
⎮ d          
⎮ ──(f(x)) dx
⎮ dx         
⌡            
0            

In [24]: I.doit()
Out[24]: -f(0) + f(y)

In [25]: I.has(f(x))
Out[25]: True

In [26]: I.doit().has(f(x))
Out[26]: False
```
We can see here that `has` does not work if we care about the bound symbols. Using `free_symbols` is more careful with respect to bound symbols but doesn't work if we are looking for a non-symbol subexpression like `f(x)`.

Maybe `as_dummy()` does work:
```python
In [29]: I.as_dummy()
Out[29]: 
y                 
⌠                 
⎮  d              
⎮ ───(f(_0)) d(_0)
⎮ d_0             
⌡                 
0                 

In [30]: I.as_dummy().has(f(x))
Out[30]: False
```
It would be nice if we could do that without creating a new expression though and the problem that `has` is very slow when called with a large number of inputs remains.

**Comment by smichr** [comment]
> It would be nice if we could do that without creating a new expression though

That's the only benefit I see of the method: the `as_dummy` already does all the heavy lifting to determine what is masked by dummy variables. But we don't need a heavy lift for `has_free`.  But you should be able to test the final `has_free` against the little function I suggest. Anything that has the `as_dummy` method will need special handling for determining `has_free` results, I think.

And I am not coming up with a better name that connotes the `has` idiom than `has_free`.

**Comment by smichr** [comment]
Just thinking...
- we already have the free_symbols and bound_symbols attributes
- an expression cannot have a sub-expression `s` if `s` contains a symbol that is not also a free symbol; if `s` contains all symbols that are both free and bound, it *might* be in the expression
- when `s` has all ambigous symbols then you might as well use the `as_dummy` method to resolve the query and maybe that method could be faster if it would create unevaluated expressions (I don't recall if it does) . Don't you have to go through all that work to figure out if the expression is actually free or not?
- can we make `has` be any faster? perhaps the expressions being tested could be sorted by free and bound symbols and then a query could only check the appropriate symbol-containing sub-expressions

**Comment by oscarbenjamin** [comment]
> * can we make `has` be any faster?

Absolutely. When testing against a large number of simple patterns it is extremely slow because it turns each pattern into a slow match function and recurses the full expression tree applying each pattern one by one to each node in the tree. If the tree has `n` operations and there are `p` patterns then this needs `n x p` pattern matches. By far the most common uses of `has` are either
```python
expr.has(*expressions)
expr.has(*types)
```
and each of those can have much more efficient matching. In the case of matching expressions we can use a set with `O(1)` containment testing to reduce the complexity from `n x p` to `n`. In the case of types we can use `isinstance(expr, tuple_of_types)` which is not `O(1)` but is far more efficient than using a loop.

Let's test this with a moderately sized expression:
```python
from sympy import *
from sympy.abc import x, y, z, t

expr = 1+cos(t)
for i in range(10):
    expr = 1 + expr**2 + expr

print(expr.count_ops()) # 4094

def has_expressions(expr, *expressions):
    patterns = set(expressions)
    tocheck = [expr]
    for subexpression in tocheck:
        if subexpression in patterns:
            return True
        tocheck.extend(subexpression.args)
    return False

def has_types(expr, *types):
    tocheck = [expr]
    for subexpression in tocheck:
        if isinstance(subexpression, types):
            return True
        tocheck.extend(subexpression.args)
    return False
```
Timings for this are:
```python
In [3]: x10 = symbols('x:10')

In [4]: x100 = symbols('x:100')

In [5]: %time expr.has(x)
CPU times: user 32.8 ms, sys: 2.13 ms, total: 34.9 ms
Wall time: 33.4 ms
Out[5]: False

In [6]: %time expr.has(t)
CPU times: user 188 µs, sys: 1e+03 ns, total: 189 µs
Wall time: 197 µs
Out[6]: True

In [7]: %time expr.has(*x10)
CPU times: user 494 ms, sys: 1.92 ms, total: 496 ms
Wall time: 498 ms
Out[7]: False

In [8]: %time expr.has(*x100)
CPU times: user 4.7 s, sys: 14.2 ms, total: 4.71 s
Wall time: 4.74 s
Out[8]: False
```
It seems that `has` is cached so repeated runs will be faster but in practice we are unlikely to repeat the exact same `has` calls so we should only care about the first time cost. With the `has_expressions` function I wrote above we get:
```python
In [9]: %time has_expressions(expr, x)
CPU times: user 3.68 ms, sys: 122 µs, total: 3.81 ms
Wall time: 3.87 ms
Out[9]: False

In [10]: %time has_expressions(expr, t)
CPU times: user 94 µs, sys: 1 µs, total: 95 µs
Wall time: 101 µs
Out[10]: True

In [11]: %time has_expressions(expr, x10)
CPU times: user 4.11 ms, sys: 48 µs, total: 4.15 ms
Wall time: 4.18 ms
Out[11]: False

In [12]: %time has_expressions(expr, x100)
CPU times: user 3.68 ms, sys: 19 µs, total: 3.7 ms
Wall time: 3.71 ms
Out[12]: False
```
Notice that with many patterns the time taken does not depend on the number of patterns being matched. Actually it does because of the time taken to construct a set which calls `__hash__` on each of the symbols. We could make `has_expressions` faster still if it takes a set argument instead of `*args`. Then in a situation where the caller already has a set it does not need to be converted from a set to a tuple and back. This would potentially be significant as a speed up in a situation where you test a small expression with a large number of patterns.

In the types case this isn't as much faster:
```python
In [4]: types = [sin, exp, cosh, tanh, Abs, re, im]

In [5]: %time has_types(expr, *types)
CPU times: user 37.2 ms, sys: 492 µs, total: 37.7 ms
Wall time: 38.1 ms
Out[5]: False

In [6]: %time expr.has(*types)
CPU times: user 173 ms, sys: 1.06 ms, total: 174 ms
Wall time: 175 ms
Out[6]: False
```
Exactly how you optimise this depends on the balance of preferring positive vs negative matches. In the positive match case we can shortcut and return True without recursing the whole expression tree. If we prefer instead to optimise negative matches (which I think are more common) then we can do something like:
```python
def has_types(expr, *types):
    flat = [expr]
    for e in flat:
        flat.extend(e.args)
    types_found = set(map(type, flat))
    return any(issubclass(t, types) for t in types_found)
```
That gives:
```python
In [13]: %time has_types(expr, *types)
CPU times: user 2.45 ms, sys: 65 µs, total: 2.51 ms
Wall time: 2.87 ms
Out[13]: False
```

**Comment by smichr** [comment]
I'm not sure that `x` should be considered free in `Integral(x + f(x), (f(x), 0, 1))` -- it is implicitly bound by merit of being in a dummy expression.

**Comment by oscarbenjamin** [comment]
> I'm not sure that `x` should be considered free in `Integral(x + f(x), (f(x), 0, 1))` -- it is implicitly bound by merit of being in a dummy expression.

It depends what the interpretation of the integral actually is. If the integral makes sense then it probably means that `x` and `f(x)` need to be treated as being independent "symbols". That's what both `integrate` and `doit` do:
```python
In [3]: e = 2*x + 3*f(x)

In [4]: e.diff(f(x))
Out[4]: 3

In [5]: integrate(e, f(x))
Out[5]: 
              2   
           3⋅f (x)
2⋅x⋅f(x) + ───────
              2

In [6]: integrate(e, (f(x), 0, 1))
Out[6]: 2⋅x + 3/2
```
Here `x` is clearly free in the evaluated integral. We could question whether that integral really makes sense though.

**Comment by smichr** [comment]
@oscarbenjamin , should the `has_types` be like this?
```python
def has_types(expr, *types):
    flat = [expr]
    for e in flat:
        flat.extend(e.args)
    types_found = set(map(type, flat))
    return any(issubclass(t, T) for t in types_found for T in types)  <--iteration over types

```

**Comment by smichr** [comment]
And maybe these for positive/negative checking:
```
def no_types(expr, *types):
    # use when expecting none of the types to be present
    flat = [expr]
    for e in flat:
        flat.extend(e.args)
    types_found = set(map(type, flat))
    return any(issubclass(t, T) for t in types_found for T in types)

def has_types(expr, *types):
    # use when expecting one of the types to be present
    flat = [expr]
    while flat:
        i = flat.pop()
        t = type(i)
        if any(issubclass(t, T) for T in types):
            return True
        flat.extend(i.args)
    return False
```

**Comment by smichr** [comment]
Another idea for the `has_types` would be a booby-trap for the object of interest, e.g.
```python
>>> class bad(Basic):
...     def __new__(*args):
...         assert None
...
>>> def ht(expr, *types):
...     try:expr.replace(lambda x: any(issubclass(type(x), T) for T in types), bad)

...     except AssertionError:return True
...     return False
...
>>> eq = x + 2*y**2
>>> ht(eq, Add)
True
>>> ht(eq, Pow)
True
>>> ht(eq, cos)
False
```
