### ISSUE TITLE
possible bug in solveset and surprising difference between solve and nonlinsolve

### ISSUE THREAD

**Issue by thomassligon** [sympy/sympy#20825]
[testSolve1.py.txt](https://github.com/sympy/sympy/files/5837198/testSolve1.py.txt)
[testSolve1.docx](https://github.com/sympy/sympy/files/5837199/testSolve1.docx)
The attached testSolve1.py (remove the .txt) should reproduce all of the issues. In addition to clarifying if this is a bug, I am interested in any comments you may have.
The attached testSolve1.docx explains how to run the test program and what to expect.

**Comment by oscarbenjamin** [comment]
It's generally easier to understand if you put the code inline like below. Also it's better if you write your text directly rather than in a word attachment.

Actually the code is very convoluted. Why does the code use `exec` and globals? It would be a lot easier to read if you wrote the code directly rather than putting it into a string and calling `exec`.

I had to use a debugger to extract the actual expression from your code. I've also renamed the symbols because it's unreadable with symbol names like `[1]`.

After that I have what I think is the code that demonstrates the problem:
```python
a, b, c, d, e, f, g, h, i, j = symbols('a:j')
x = Symbol('x')

eq = (
        2*b*g + b*j*x
      - 2*c*x*(b*d*x + 2*b*e + e*x**2 + i)/(a*h + 2*i*x - 1)
      - f*h*(b*d*x + 2*b*e + e*x**2 + i)/(a*h + 2*i*x - 1)
      + g*x**2 - x + c
    )

sol = solve(eq, x)  # hangs or takes a long time
```
The equation that we want to solve is
```python
In [9]: eq
Out[9]: 
                      ⎛                   2    ⎞           ⎛                   2    ⎞           
                2⋅c⋅x⋅⎝b⋅d⋅x + 2⋅b⋅e + e⋅x  + i⎠       f⋅h⋅⎝b⋅d⋅x + 2⋅b⋅e + e⋅x  + i⎠      2    
2⋅b⋅g + b⋅j⋅x - ──────────────────────────────── + c - ────────────────────────────── + g⋅x  - x
                        a⋅h + 2⋅i⋅x - 1                       a⋅h + 2⋅i⋅x - 1   
```
Interrupting I find that it seems to be stuck in `checksol`. Calling `solve` with `check=False` gives a result in about 1 second:
```python
sol = solve(eq, x, check=False)
```
The resulting solution is fairly long. I think it comes from the cubic formula. Apparently checking the correctness of those solutions takes a long time.

The nonlinsolve function does not use `checksol` like this I believe.

**Comment by thomassligon** [comment]
Thanks!

First, I should apologize for the `exec`s. Of course, in a test program, they are of no value. The reason for them is that the "real" program deals with an undetermined number of variables and equations, and this is how I deal with that. In that program, the loop over j can have different ranges.

Then, the symbol [1] is in fact cumbersome. However, I currently write it as Square1, and could easily abbreviate it (e.g. S1). I am currently using it because the 2 papers on which I am basing my work (both written a long time ago by famous mathematicians) use this unusual symbol, and it was very nice to have it in the Latex version of the output. To explain that better, let's look at the symbol bm1, which is b subscripted by minus one, or b_{-1} in Latex. Now my difficulty here is that the Latex version appears where I don't want it. For example, I wrote
`exbm1 = 2*Roundm1*b1*bm1+Roundm1+Squarem1m2*bm1*bm2+Squarem11*b1*b2+Squarem1*bm1**2+2*Squarem1*bm2-bm1`
which I could abbreviate as
`exbm1 = 2*Rm1*b1*bm1+Rm1+Sm1m2*bm1*bm2+Sm11*b1*b2+Sm1*bm1**2+2*Sm1*bm2-bm1`
I would like to see b1 and bm1 everywhere except `print(latex(...))`, where b_1 and b_{-1} are good.
How can I do that? Both `print(exbm1)` and `print(repr(exbm1))` and my debugger give me the Latex version. I have even considered using `b1=Symbol('b1')` and writing an extra print routine that would replace b1 by `b1L=Symbol('b_1')`.
By the way, I can't read your Out[9]. That's why I use Latex, which I paste into a Word document, just to look at the output.
In addition, your definition of the symbols a through j uses the same symbol on the lhs and on the rhs, which seems like unnecessary redundancy. I thought that writing `S1 = Symbol('\[1\]')` was an elegant way of defining S1 for use in the code and '\[1\]' for use in the Latex output.

Now, I am testing `solve(...,check=False)` and `nonLinSolve` for solving 8 equations for 8 variables simultaneously.

Finally, the mathematics that I am analyzing here has never been solved analytically, only numerically. Solving the equations explicitly would benefit the pure mathematics by enabling new theorems. If that doesn't succeed, at least automating parts of the numerical solution, calculating higher order approximations, would benefit the applied mathematics.

**Comment by oscarbenjamin** [comment]
> In addition, your definition of the symbols a through j uses the same symbol on the lhs and on the rhs, which seems like unnecessary redundancy.

I would trade a bit of redundancy for readability every time!

**Comment by oscarbenjamin** [comment]
> the "real" program deals with an undetermined number of variables and equations, and this is how I deal with that. In that program, the loop over j can have different ranges.

The solution to this in Python is to use lists or tuples or some other container rather than raw variables. For example:
```python
In [7]: x = symbols('x:10')

In [8]: x
Out[8]: (x₀, x₁, x₂, x₃, x₄, x₅, x₆, x₇, x₈, x₉)

In [9]: eq = [xi - n for n, xi in enumerate(x)]

In [10]: eq
Out[10]: [x₀, x₁ - 1, x₂ - 2, x₃ - 3, x₄ - 4, x₅ - 5, x₆ - 6, x₇ - 7, x₈ - 8, x₉ - 9]

In [11]: for n in range(len(x)):
    ...:     print(x[n], '=', solve(eq[n], x[n]))
    ...: 
x0 = [0]
x1 = [1]
x2 = [2]
x3 = [3]
x4 = [4]
x5 = [5]
x6 = [6]
x7 = [7]
x8 = [8]
x9 = [9]
```
The difference is that you write `eq[2]` rather than `eq2`.

**Comment by thomassligon** [comment]
Thanks! The response is very useful. Even though I don't have a final answer for whether
`sol = solve(eq, x, check=False)`
does everything I need, I think it is time to close the issue.
