### ISSUE TITLE
Solving functional equations

### ISSUE THREAD

**Issue by peteroupc** [sympy/sympy#20836]
I have come across an interesting problem: solving an equation for a function that satisfies different parameters.  However, the equation is not exactly a _differential_ equation. An example of this kind of equation is:

    f(n) = f(n*2) + z/sqrt(2*n)
    
One solution to this example is: `(1+sqrt(2))*z/sqrt(n)`.

Is there a way to solve equations like this with SymPy?  Neither `solve` nor `dsolve` seem to help.

```
In [93]: solve(f(n) - (f(n*2) + c/sqrt(2*n)))                                                                                                                              
Out[93]: [{z: √2⋅√n⋅(f(n) - f(2⋅n))}]

In [94]: dsolve(f(n) - (f(n*2) + c/sqrt(2*n)))                                                                                                                             


ValueError: The function cannot be automatically detected for f(n) - f(2*n) - sqrt(2)*z/(2*sqrt(n)).
```

**Comment by oscarbenjamin** [comment]
This is called a "functional equation":
https://en.wikipedia.org/wiki/Functional_equation

SymPy has a solver for recurrence relations which are a special case similar to differential equations:
https://docs.sympy.org/latest/modules/solvers/solvers.html#sympy.solvers.recurr.rsolve

Otherwise no I don't think there is anything in sympy that would solve something like the equation you show.

**Comment by naveensaigit** [comment]
Yes, `rsolve` is the one that has to be used. However, it cannot solve many types of recurrences currently. It can only solve recurrences of the type `a1(n)*f(n+k) + a2(n)*f(n+k-1) + .... + ak(n)*f(n) = g(n)`
``` python
>>> rsolve(Eq(f(n), f(2*n)+ z/sqrt(2*n)), f(n))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Naveen S Thota\sympy\sympy\solvers\recurr.py", line 744, in rsolve
    "'%s(%s + k)' expected, got '%s'" % (y.func, n, h))
ValueError: 'f(n + k)' expected, got 'f(2*n)'
```

**Comment by peteroupc** [comment]
I've managed to solve the functional equations I had in mind by writing them into a different form, since the only `n` I care about are power-of-2 integers. For example, `f(n) = f(n*2) + z/sqrt(2*n)` becomes `g(n) = g(n*2) + z/sqrt(2*2**n)`. See example:

```
In [250]: rsolve(Eq(f(n), f(n+1) + z/sqrt(2*2**n)), f(n)).simplify()                                                                                                   
Out[250]: 
 -n  ⎛ n              ⎞
 ─── ⎜ ─              ⎟
  2  ⎜ 2              ⎟
2   ⋅⎝2 ⋅C₀ + z + √2⋅z⎠

In [251]: rsolve(Eq(f(n), f(n+1) + z/(4*2**n)), f(n)).simplify()                                                                                                       
Out[251]: 
      -n  
     2  ⋅z
C₀ + ─────
       2  
```

However, this issue should be left open to address the issue of supporting more general functional equations.

**Comment by oscarbenjamin** [comment]
The C0 symbol is there because this is the general solution. You need to give an initial condition to get a unique solution:
```python
In [3]: rsolve(Eq(f(n), f(n+1) + z/sqrt(2*2**n)), f(n), {f(1):1})
Out[3]: 
                    -n            
                    ───           
                     2            
     √2⋅z       √2⋅2   ⋅z⋅(√2 + 2)
-z - ──── + 1 + ──────────────────
      2                 2  
```

> * It works only if the "independent term" (like `z/(4*2**n)`) is a sum of hypergeometric functions

Do you know of an approach that can work more generally?

> However, this issue should be left open to address the issue of supporting more general functional equations.

The issue would be more useful if it listed actual techniques or algorithms that could be implemented to solve them. I don't know functional equations so well so I'm not sure what can be done beyonds just listing a table of equations with known solutions.

**Comment by peteroupc** [comment]
> The C0 symbol is there because this is the general solution. You need to give an initial condition to get a unique solution:
> 
> ```python
> In [3]: rsolve(Eq(f(n), f(n+1) + z/sqrt(2*2**n)), f(n), {f(1):1})
> Out[3]: 
>                     -n            
>                     ───           
>                      2            
>      √2⋅z       √2⋅2   ⋅z⋅(√2 + 2)
> -z - ──── + 1 + ──────────────────
>       2                 2  
> ```
> 
> > * It works only if the "independent term" (like `z/(4*2**n)`) is a sum of hypergeometric functions
> 
> Do you know of an approach that can work more generally?
> 
> > However, this issue should be left open to address the issue of supporting more general functional equations.
> 
> The issue would be more useful if it listed actual techniques or algorithms that could be implemented to solve them. I don't know functional equations so well so I'm not sure what can be done beyonds just listing a table of equations with known solutions.

I don't know much about ways to solve functional equations.  In fact, this page was the first time I knew such equations existed.

**Comment by asmeurer** [comment]
I don't know if there are general methods for solving functional equations like there are for ODEs, other than recurrence relations. Usually when you see one solved the methods seem heuristic and specific to the equation in question. Generally you plug in different values into the equation until you get some relationships that produce a system of equations that you can solve for the solution. 

It also often matters if the function is known to be continuous or differentiable. If you want to find examples, look for questions on math competitions like math olympiads and Putnam exams. If there are some general methods, we could add a `funsolve` function similar to `dsolve`.

**Comment by asmeurer** [comment]
If you search Google Scholar for "functional equations" there are a lot of resources, although it can be hard to separate out things for solving them symbolically and more theoretical results.

**Comment by peteroupc** [comment]
Here is the context of this issue.  The functional equation in this issue's opening post came from the proof of Proposition 10 in Nacu and Peres (2005), "[Fast simulation of new coins from old](https://projecteuclid.org/euclid.aoap/1106922322)".  There, the solution to the equation is a constant or linear function that depends on `n`.

**Comment by peteroupc** [comment]
In the meantime, my particular case is settled.

For the equation `f(n) = f(n*2) + g(n)`, it's enough to sum `f(n) = g(n) + g(n*2) + g(n*4) + ...` to get the solution.  I can assume that the sum converges, and in that case, that sum is the solution I need.

I will close this issue for now, since there are no other functional equations I care about at the moment.
