### ISSUE TITLE
diff(Product(...)) does not evaluate the derivative

### ISSUE THREAD

**Issue by oscarbenjamin** [sympy/sympy#20848]
Usually Derivative gives an unevaluated derivative and doit is used to evaluate it:
```python
In [4]: Derivative(x**2, x)
Out[4]: 
d ⎛ 2⎞
──⎝x ⎠
dx    

In [5]: Derivative(x**2, x).doit()
Out[5]: 2⋅x

In [6]: diff(x**2, x)
Out[6]: 2⋅x
```
The diff function is used to create the derivative and call doit but it doesn't work with a Product:
```python
In [8]: Derivative(Product(x, (y, 1, z)), x)
Out[8]: 
  ⎛  z    ⎞
∂ ⎜─┬─┬─  ⎟
──⎜ │ │  x⎟
∂x⎜ │ │   ⎟
  ⎝y = 1  ⎠

In [9]: Derivative(Product(x, (y, 1, z)), x).doit()
Out[9]: 
 z  
x ⋅z
────
 x  

In [10]: diff(Product(x, (y, 1, z)), x)
Out[10]: 
  ⎛  z    ⎞
∂ ⎜─┬─┬─  ⎟
──⎜ │ │  x⎟
∂x⎜ │ │   ⎟
  ⎝y = 1  ⎠
```
Here `Out[10]` should be the same as `Out[9]`.

**Comment by hailcpy** [comment]
Can i debug this

**Comment by asmeurer** [comment]
Probably because it doesn't actually know how to differentiate a Product. [9] only works because the original Product evaluates first and then the derivative does. We could implement the general Leibniz rule (https://en.wikipedia.org/wiki/Product_rule#A_product_of_more_than_two_factors). I'm not sure if there are concerns with that formula if the product is infinite. 

Outside of this, I'm not sure if Derivative.doit() should recursively call doit() before evaluating.

**Comment by Maelstrom6** [comment]
> We could implement the general Leibniz rule (https://en.wikipedia.org/wiki/Product_rule#A_product_of_more_than_two_factors). I'm not sure if there are concerns with that formula if the product is infinite.

I think it does work for infinite products if they converge. [Wiki Proof](https://proofwiki.org/wiki/Derivative_of_Infinite_Product_of_Analytic_Functions).

**Comment by hyadav2k** [comment]
@Maelstrom6, is this issue open, can I take it?
Thanks.

**Comment by Maelstrom6** [comment]
Feel free to work on it👍. #20851 is working on this but the author is fairly busy at the moment. Maybe have a look at the discussion there for some ideas on how to tackle the problem.

**Comment by hyadav2k** [comment]
@Maelstrom6 I tried something like with the code you suggested with respect to the discussions:
```
def _eval_derivative(self, x):
        from sympy import Sum
        limits = list(self.limits)
        if any(x in limit[1:].free_symbols for limit in reversed(limits)):
            return None
        return self * Sum(self.function.diff(x) / self.function, self._args[1:], **self.assumptions0)
```
It covers if `x` is in the free symbols of any of the lower or upper limits, it returns unevaluated.

**Comment by Maelstrom6** [comment]
Looks good. You can open up a PR for it and we can do a few finishing touches there.

**Comment by hyadav2k** [comment]
Sure, thanks a lot!
