### ISSUE TITLE
Incorrect factoring

### ISSUE THREAD

**Issue by bbuzz31** [sympy/sympy#20854]
Sorry if this is expected behavior, but to me the result of the following factor is blatantly wrong. 
```
import sympy as sym
r    = sym.symbols('r')               
tk   = sym.symbols('t_k')              
tk1  = sym.symbols('t_{k-1}')  
expr = r**2*tk1**2 - 2*r*tk*tk1 + tk**2
fact  = sym.factor(expr)
print(expr)
print(fact)
```
If you evaluate the quadratic after sympy has factored (stored in `fact`) you will see it results incorrectly in a positive middle term.

**Comment by oscarbenjamin** [comment]
You haven't shown any output from the above so it's unclear to me what you think is wrong. This is what I get with the current master version of sympy:
```python
In [6]: import sympy as sym
   ...: r    = sym.symbols('r')
   ...: tk   = sym.symbols('t_k')
   ...: tk1  = sym.symbols('t_{k-1}')
   ...: expr = r**2*tk1**2 - 2*r*tk*tk1 + tk**2
   ...: fact  = sym.factor(expr)
   ...: print(expr)
   ...: print(fact)
r**2*t_{k-1}**2 - 2*r*t_k*t_{k-1} + t_k**2
(r*t_{k-1} - t_k)**2

In [7]: expr
Out[7]: 
 2        2                      2
r ⋅t_{k-1}  - 2⋅r⋅tₖ⋅t_{k-1} + tₖ 

In [8]: fact
Out[8]: 
                2
(r⋅t_{k-1} - tₖ) 

In [9]: expand(fact)
Out[9]: 
 2        2                      2
r ⋅t_{k-1}  - 2⋅r⋅tₖ⋅t_{k-1} + tₖ 

In [10]: expand(fact) == expr
Out[10]: True
```
I don't see anything that is incorrect. Do you get the same output when running this?

**Comment by bbuzz31** [comment]
Ah I had a legacy term in my jupyter notebook. Sorry been staring at equations for too long today.

**Comment by oscarbenjamin** [comment]
Long day I guess. We've all been there :)
