### ISSUE TITLE
Mark `linsolve()` in Sympy as "implicit/lazy" and then lambdify

### ISSUE THREAD

**Issue by zgbkdlm** [sympy/sympy#20855]
is it possible for `lambdify` to recoginize `linsolve()`? For example, if I have an expression involving `linsolve()`, would `lambdify` be able to convert it to e.g., `numpy.linalg.solve()`?

As an example, let

```python
from sympy import MatrixSymbol, linsolve, lambdify

A = MatrixSymbol('A', 3, 3)
b = MatrixSymbol('b', 3, 1)

func = lambdify((A, b), linsolve((A, b)), modules="numpy")
```

Is it possible to generate a function like `func(A, b) = np.linalg.solve(A, b)`?

The above code for sure does not work. It will first fail at linsolve((A, b)).

My attempt would be somehow _mark `linsolve((A, b))` as an implicit/lazy expression_ so that lambdify can recognize it and thus link it with np.linalg.solve. But I don't find no ways to do this.

**Comment by oscarbenjamin** [comment]
The `linsolve` function is not a "symbolic" function. It could be possible to create a symbolic object representing the solution of a system of linear equations though.

For now does it work with `inv(A)`?

**Comment by sylee957** [comment]
I think that we can reuse `MatrixSolve` for this

**Comment by zgbkdlm** [comment]
> I think that we can reuse `MatrixSolve` for this

Thanks, the `MatrixSolve` work!
