### ISSUE TITLE
Rounding modes for evalf()/.n()

### ISSUE THREAD

**Issue by peteroupc** [sympy/sympy#20869]
Add a rounding mode option to `evalf()` and `.n()`, which determines how the unit in the last place is rounded if the result can't be represented exactly.  Examples of rounding modes include _floor_, _ceiling_, and _half up_.

For my purposes, especially, _floor_ and _ceiling_ are useful to ensure that the rounded result (from `evalf` or `.n()`) is a lower or upper bound on the true result.

In the meantime, we can emulate _floor_ and _ceiling_ modes by multiplying by an integer, using the existing `floor` and `ceiling`, and dividing by the same integer, as follows:

```
expr = sin(3)
expr2 = floor(expr*1000) / 1000
pprint(expr2.n())
expr2 = ceiling(expr*1000) / 1000
pprint(expr2.n())
```

**Comment by asmeurer** [comment]
Is there already support for this in mpmath? If not, it should be implemented there first.

**Comment by peteroupc** [comment]
Withdrawn.  I have found a suitable alternative to rounding modes by writing a helper function that uses `floor` and `ceiling`.
