### ISSUE TITLE
reduce_inequalities() gives impossible answer.

### ISSUE THREAD

**Issue by dispencermoore** [sympy/sympy#20861]
When calling reduce_inequalities() on a set of inequalities, it gives me an answer that is impossible, rather than saying False. 
Here is the sample of code:
"""
from sympy import *
x, y, z = symbols('x y z')
init_printing(use_unicode=True)

inequalities = [((6/((x)+x))<0), (x>=2), (x>=7)]
print(reduce_inequalities((inequalities), x))
"""
And it prints out:
"""
(7 <= x) & (-oo < x) & (x < 0) & (x < oo)
"""
It states that x can somehow be both greater than or equal to 7, but also at the same time less than 0. When looking at the reduce_inequalities() function, it appears to already call sympify on the inequalities, so I do not think that is the issue. In the first inequality, when I changed the "/" to "*" it properly stated it as False.

**Comment by Maelstrom6** [comment]
The simplification for the logic module is very poor. As a small workaround, you could always call it a second time:

```python
print(reduce_inequalities(reduce_inequalities((inequalities), x)))
# output: False
```

**Comment by dispencermoore** [comment]
Calling it twice does not work on all inequalities, but commit that skirpichev added worked for me. An example of calling it twice not working would be [(2*x<10), (x>2)].
