### ISSUE TITLE
Logic simplification not simplifying good enough

### ISSUE THREAD

**Issue by oscargus** [sympy/sympy#20870]
Just stumbled across this case which seems to trigger an issue in the logic simplification (not sure if it is solved by #20245, do not have time to test now, just wanted to post the case).

```
from sympy import *

a, b, c, d = symbols('a b c d')
bad = SOPform([a, b, c, d], [1, 2, 3, 4, 5, 6, 8, 9, 11, 12, 14, 15])
````

This gives `(b & ~d) | (d & ~b) | (a & b & c) | (a & c & d) | (a & ~b & ~c) | (a & ~c & ~d) | (b & ~a & ~c) | (c & ~a & ~b) | (c & ~a & ~d) | (d & ~a & ~c)` but e.g. the `(a & b & c)` and `(a & c & d)` terms are redundant, only one is needed. It should be enough with `(b & ~d) | (d & ~b)` and four of the remaining eight terms (pair-wise redundant).

**Comment by Uttam-Singhh** [comment]
Can I work on it??
