### ISSUE TITLE
Treating all non-zero numbers as True

### ISSUE THREAD

**Issue by che2712** [sympy/sympy#20880]
In this example of inference.py, only 1 is considered as True and 0 as False whereas all non-zero numbers must be considered as True.

>>> pl_true( A & B, {A: 1, B: True})
True

>>> pl_true( A & B, {A: 2, B: True})
>>> pl_true( A & B, {A: 1, B: 2})
>>> pl_true( A & B, {A: -2, B: -3})

**Comment by smichr** [comment]
You might consider using `Symbol._sanitize`:

```python
>>> a={x:2, y: None}
>>> Symbol._sanitize(a)
>>> a
{x:True}
```

I think removal of None is consistent with the behavior of `pl_true`.

**Comment by oscarbenjamin** [comment]
I don't understand the purpose of `pl_true`. It doesn't look like a very useful function and most of the code in the function seems unnecessary.

Treating all nonzero numbers as true does not seem useful so I'm going to close this.
