### ISSUE TITLE
Failing Master build due to Deprecations in NumPy 1.20

### ISSUE THREAD

**Issue by Sc0rpi0n101** [sympy/sympy#20892]
Looking at the traceback in the failing Travis build in master, there are a lot of deprecation warnings that are causing the build to fail. 

It looks like NumPy has updated their data type aliases and deprecated some of the existing ones like np.int, np.complex, etc. (numpy/numpy#14882) in their latest [1.20 release](https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations). Just looking at the no of failures, it looks like we have a lot of instances of these which we need to update

**Comment by oscarbenjamin** [comment]
We also need to unpin the versions of the dependencies in the optional dependency job on Github Actions so that these errors show up there as well.

**Comment by asmeurer** [comment]
(that's issue #20623)

**Comment by oscarbenjamin** [comment]
This is fixed now in https://github.com/sympy/sympy/pull/20944
