### ISSUE TITLE
Incorrect inequality solving: False returned instead of answer

### ISSUE THREAD

**Issue by ischurov** [sympy/sympy#20902]
I discovered pretty weird behaviour of `solve` with rather simple inequality: it returns `False` instead of actual answer, and, which is even more strange, this behaviour fixes itself after several other inequalities are solved.

```
import sys
import sympy
from sympy import solve
from sympy.abc import x, t
f = (t / ((1 + t) ** 2))
print(f"{sys.version=}")
print(f"{sympy.__version__=}")
print(f"{solve(f.subs({t: 3 * x + 2}).diff(x) > 0, x)=}")
print(f"{solve(f.subs({t: 3 * x + 3}).diff(x) > 0, x)=}")
print(f"{solve(f.subs({t: 3 * x + 4}).diff(x) > 0, x)=}")
print(f"{solve(f.subs({t: 3 * x + 2}).diff(x) > 0, x)=}")
```

Output:

```
sys.version='3.9.0 (v3.9.0:9cf6752276, Oct  5 2020, 11:29:23) \n[Clang 6.0 (clang-600.0.57)]'
sympy.__version__='1.8.dev'
solve(f.subs({t: 3 * x + 2}).diff(x) > 0, x)=False
solve(f.subs({t: 3 * x + 3}).diff(x) > 0, x)=(-4/3 < x) & (x < -2/3)
solve(f.subs({t: 3 * x + 4}).diff(x) > 0, x)=(-5/3 < x) & (x < -1)
solve(f.subs({t: 3 * x + 2}).diff(x) > 0, x)=(-1 < x) & (x < -1/3)
```

Note that outputs of the third and last lines are different despite the fact that expressions are equal.

Expected output:

```
sys.version='3.9.0 (v3.9.0:9cf6752276, Oct  5 2020, 11:29:23) \n[Clang 6.0 (clang-600.0.57)]'
sympy.__version__='1.8.dev'
solve(f.subs({t: 3 * x + 2}).diff(x) > 0, x)=(-1 < x) & (x < -1/3)
solve(f.subs({t: 3 * x + 3}).diff(x) > 0, x)=(-4/3 < x) & (x < -2/3)
solve(f.subs({t: 3 * x + 4}).diff(x) > 0, x)=(-5/3 < x) & (x < -1)
solve(f.subs({t: 3 * x + 2}).diff(x) > 0, x)=(-1 < x) & (x < -1/3)
```

**Comment by AaronStiff** [comment]
As a temporary workaround, you could use `solveset` instead of `solve` and pass `domain = "S.Reals"` to it. For example,

```py
print(f"{solveset(f.subs({t: 3 * x + 2}).diff(x) > 0, x, domain = S.Reals)=}")
```

**Comment by akshatsood2249** [comment]
Hello ... Being tyro in Open Source and SymPy can you please explain why for some issues these functions are created `def test_sympyissue_20902( )` . Like how they help in resolving any issue??

**Comment by 0sidharth** [comment]
@akshatsood2249 They are regression tests. They do not fix the issue directly but serve as a check downstream to ensure that further changes to the code do not bring back this issue. They increase code coverage.
