### ISSUE TITLE
Have an idea for matrices : finding rank of matrices using row-echelon form

### ISSUE THREAD

**Issue by ayushbisht2001** [sympy/sympy#20903]
I have an idea of implementing a function for evaluating the rank of matrices using row-echelon form . I would like to discuss on this topic .  
Since we know that , 
If A is matrix of order  m x n ,
then,  rank(A) <= min(m, n)

algorithm : 
1. convert the matrix into row-echelon form
2.  we get linearly independent rows 
3.  rank = number of linearly independent rows

**Comment by oscarbenjamin** [comment]
There is already a rank method:
```python
In [49]: M = Matrix([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [50]: M
Out[50]: 
⎡1  2  3⎤
⎢       ⎥
⎢4  5  6⎥
⎢       ⎥
⎣7  8  9⎦

In [51]: M.rank()
Out[51]: 2
```

**Comment by sylee957** [comment]
I may close this since we already have the feature.
But feel free to suggest other unique ideas, like if we can have a fully symbolic operator for matrix rank or if we should improve the documentation about the existing features.
