### ISSUE TITLE
Failing github builds.

### ISSUE THREAD

**Issue by jksuom** [sympy/sympy#20938]
All travis-ci builds have been failing for over a week, see https://travis-ci.org/github/sympy/sympy/builds. It seems that the failures occur in several modules: quantum, fourier, matrices, plotting,...
Is it expected that github-actions should have found those?

**Comment by oscarbenjamin** [comment]
That's because of #20623. Github actions has pinned versions for numpy etc so it isn't picking up the latest numpy version which has deprecated `np.complex` etc.

The issue itself for those particular failures is #20892

I'll close this one since we already have the other two issues.
