### ISSUE TITLE
Bug handling parenthesis in linear_eq_to_matrix?

### ISSUE THREAD

**Issue by marcdelabarrera** [sympy/sympy#20940]
I am trying to use linear_eq_to_matrix, here is a simplified example: 

```
beta,kappa,y,pi=sym.symbols('beta,kappa,y,pi')
sym.linear_eq_to_matrix([beta*(kappa*y+pi)], (y,pi))
```

I expect to get ((beta*kappa, beta), (0) ), but I get ((0,0), (0)). However, if I multiply beta "by hand" and run: 

```
sym.linear_eq_to_matrix([(beta*kappa*y+beta*pi)], (y,pi))
```
Then I obtain the desired result. Any clue why this might be happening? I am having similar problems with linsolve.

**Comment by oscarbenjamin** [comment]
What version of sympy are you using?

I tried with 1.7.1 and master and I get:
```python
In [2]: import sympy as sym

In [3]: beta,kappa,y,pi=sym.symbols('beta,kappa,y,pi')
   ...: sym.linear_eq_to_matrix([beta*(kappa*y+pi)], (y,pi))
Out[3]: ([β⋅κ  β], [0])
```

**Comment by marcdelabarrera** [comment]
Thank you! Indeed, it was an old-version issue. Should have checked before. (it also solved the linsolve problem)

Best, 

Marc
