### ISSUE TITLE
Incorrect Latex Printing when MatrixSymbol contains Superscript

### ISSUE THREAD

**Issue by maxmunzel** [sympy/sympy#20959]
## SymPy Version
1.6.2

## Minimum Example in Jupyter Lab:

![Screenshot 2021-02-14 at 17 12 28](https://user-images.githubusercontent.com/5411096/107882192-3e341200-6ee8-11eb-9b9e-d8b38408c4fc.png)

## Issue:

While LaTeX supports nested superscripts, it wants them separated by `{...}` blocks.

`{x^{4}}^{2} % works`
`x^{4}^{2} % Error: Double Superscript`

The fix should be streight-forward: Add braces around symbol names when generating LaTex.
I can implement the fix the upcoming weeks.

## Final Words

The SymbolicMatrix functionality of SymPy (and SymPy in General) is simply wonderful. Thank you to everyone involved!

**Comment by AniketShahane** [comment]
Hey I wanted to work on this issue can you guide me.

**Comment by oscargus** [comment]
This seems to be a problem for MatrixSymbol only, not for Symbol. The change seem to be to add some detection of MatrixSymbol here:
https://github.com/sympy/sympy/blob/448e6188602a57df729cec5658fbaafc577bb398/sympy/printing/latex.py#L648-L649

**Comment by oscargus** [comment]
Probably one should also fix
https://github.com/sympy/sympy/blob/448e6188602a57df729cec5658fbaafc577bb398/sympy/printing/latex.py#L1689
and
https://github.com/sympy/sympy/blob/448e6188602a57df729cec5658fbaafc577bb398/sympy/printing/latex.py#L1701
by adding {} around `%s`
