### ISSUE TITLE
SyntaxWarning "is" did you mean "==" - Octave syms package not working properly

### ISSUE THREAD

**Issue by G0rocks** [sympy/sympy#20962]
Working on a Stewart platform forward kinetics in 2D problem in a group project.
Received matlab code from colleague and it won't run because plot.py in plotting and diophantine.py in solvers>diophantine has if-statements where the string "is" is used instead of == to compare two values.

**Comment by G0rocks** [comment]
Hi I fixed the problem with those specific files, created a pull request here: https://github.com/sympy/sympy/pull/20963
Working on passing the sympy-bot checks

**Comment by G0rocks** [comment]
Oh, wait, my inexperience in git and github messed this up, I unlinked the issue from my fork of the sympy repo but this issue is still closed.

**Comment by G0rocks** [comment]
All checks passed!
https://github.com/sympy/sympy/pull/20963

**Comment by oscarbenjamin** [comment]
Exactly which use of `is` is causing a problem?

**Comment by G0rocks** [comment]
There were a couple of them, I changed them in the sympy files octave was using on my computer, octave was using sympy v1.4.
I can set up the files again to check the error messages but looking at [this page](https://realpython.com/courses/python-is-identity-vs-equality/#:~:text=The%20%3D%3D%20operator%20compares%20the,you%27re%20comparing%20to%20None%20.) I realize the difference between "is" and "==" and looking at your comment on the pull request where you say "Most of these changes are not needed. It is fine (and even recommended) to use is when comparing with None and with other singletons like S.One and False etc. I can't see which changes are actually needed." I understand it better.

Now I'm wondering why the code from my colleague isn't working and it makes me wonder if warnings stop the octave code from running or if you need errors to stop the code from running? I've searched a little online and after disabling/enabling warnings, found out that warnings in fact do not stop your code from running, only errors do. This means that the use of "is" is just causing the symbolic package octave uses to freak out a little but there are other reasons behind the code not working (there were more errors, my colleague made this in matlab and there were some matlab specific functions which I've substituted for octave/matlab ok functions).

So you're right, but then if "is" is recommended (especially in the cases that it was being used), why does the symbolic package issue warnings when "is" is used?

**Comment by oscarbenjamin** [comment]
The use of `is` is recommended for singletons where it is guaranteed that there will be only one instance e.g. `is None`. It can fail for things like strings or ints where sometimes caching means that `is` works but sometimes it doesn't. That's why a warning was added in more recent Python versions to catch this sort of thing. I'm fairly sure that sympy already fixed the places where that happens so the reason you're seeing this is presumably because you have an older sympy version 1.4 that is running with a newer Python version. If you used a more recent sympy then you wouldn't see the problem.

In any case the warning is just a warning. It shouldn't stop your code from running.

**Comment by G0rocks** [comment]
Yeah, thanks Oscar, that makes sense. I might look into updating sympy for octave but I think it's fine until a new version of octave is released.
I'm closing the issue since it is unnecessary. I also closed the pull request.
Thanks again :)
