### ISSUE TITLE
Float conversion precision error

### ISSUE THREAD

**Issue by PierreGuilmin** [sympy/sympy#20978]
Hi sympy community,

First thanks for this amazing library! 🎉 

I am wondering what causes a precision error in the following code:
```python
>>> from sympy import symbols
>>> x = symbols("x")
>>> result = (12 * x / 10.0).evalf(subs={x: 1})
>>> result
1.20000000000000
>>> float(result)
1.2000000000000002
```

Is there a better way to convert `result` to `float` or to do the calculation?

**Comment by oscarbenjamin** [comment]
Both `result` and `float(result)` are the same. It's just that `result` is a sympy `Float` and doesn't print as many digits.

> Is there a better way to convert `result` to `float` or to do the calculation?

If you don't use evalf or float at all you can get the result exactly:
```python
In [7]: (12 * x / 10).subs(x, 1)
Out[7]: 6/5
```

**Comment by PierreGuilmin** [comment]
Alright, thank you. Actually I think the issue is related to the `10.0`, because:

```python
>>> (12 * x / 10.0).subs(x, 1)
1.20000000000000
>>> (12 * x / 10).subs(x, 1)
6/5
```

Also I do have to use `evalf` because I need a `float` after my computation. I was confused by this sentence from the documentation:
> To numerically evaluate an expression with a Symbol at a point, we might use `subs` followed by `evalf`, but it is more efficient and numerically stable to pass the substitution to `evalf` using the `subs` flag, which takes a dictionary of `Symbol: point` pairs. -- https://docs.sympy.org/latest/tutorial/basic_operations.html#evalf
