### ISSUE TITLE
Why isn't the asserted value given as the output?

### ISSUE THREAD

**Issue by almighty123789** [sympy/sympy#20972]
```
>>> sympy.__version__
'1.8.dev'
>>> f = integrate(2*t*sign(t**2 - 1), t)
>>> pprint(f,use_unicode = False)
    /
   |
   |       / 2    \
2* | t*sign\t  - 1/ dt
   |
  /
```
```
  assert integrate(2*t*sign(t**2 - 1), t) == Piecewise(
            (t**2, t < -1), (-t**2 + 2, t < 1), (t**2, True))
```
As you can see, I get an unevaluted Integral object , but in the second piece of code the same integral is used as a test ( line 674, test_integral.py )
I wanted to know why does is it not given as ouput, when the same integral has a value asserted? 
Is it just to make sure that if any changes are made, they are consistent?

**Comment by 0sidharth** [comment]
This is because t has been declared to be real in the test you speak of
https://github.com/sympy/sympy/blob/013ea847f6e465bb25201fbf1974abc74206f010/sympy/integrals/tests/test_integrals.py#L663

```py
In [1]: f = integrate(2*t*sign(t**2 - 1), t)
pr
In [2]: print(f)
2*Integral(t*sign(t**2 - 1), t)

In [3]: t = symbols('t', real=True)

In [4]: f = integrate(2*t*sign(t**2 - 1), t)

In [5]: print(f)
Piecewise((t**2, t < -1), (2 - t**2, t < 1), (t**2, True))
```

**Comment by almighty123789** [comment]
Oh yes, I missed  it. Thanks , I will close the issue .
