### ISSUE TITLE
question: A regression or expected change of 1.6 -- how to mitigate?

### ISSUE THREAD

**Issue by yarikoptic** [sympy/sympy#20981]
`sympy-1.6rc1~376^2~16` (09158212e3e5ec8b3de7d168afae6d6f798d0635) "Make Relational not subclass from Expr" (https://github.com/sympy/sympy/pull/18053) made the following code

```python
import sympy
import sys

class Term(sympy.Symbol):
    _term_flag = True

    def __add__(self, other):
        if self == other:
            return self
        return sympy.Symbol.__add__(self, other)

print("Sympy %s Python: %s" % (sympy.__version__, sys.version))

T=Term("t"); 
print((T >= 0) * (T+1.0e-14))
```
fail 
```
(git)lena:~/proj/misc/sympy[tags/sympy-1.6rc1~376^2~16]git
$> python /tmp/sympy-repro.py       
Sympy 1.6.dev Python: 3.9.1 (default, Dec  8 2020, 07:51:42) 
[GCC 10.2.0]
Traceback (most recent call last):
  File "/tmp/sympy-repro.py", line 15, in <module>
    print((T >= 0) * (T+1.0e-14))
TypeError: unsupported operand type(s) for *: 'GreaterThan' and 'Add'
```
whenever before it was ok
```
(git)lena:~/proj/misc/sympy[tags/sympy-1.6rc1~376^2~16]git
$> git co HEAD^
Previous HEAD position was 09158212e3 Make Relational not subclass from Expr
HEAD is now at 121ccd7687 Merge pull request #18166 from Upabjojr/fix_tensor_partial_derivative

$> python /tmp/sympy-repro.py
Sympy 1.6.dev Python: 3.9.1 (default, Dec  8 2020, 07:51:42) 
[GCC 10.2.0]
(t + 1.0e-14)*(t >= 0)
```

leading to a number of errors of nipy tests  https://github.com/nipy/nipy/issues/466  .

~~If it is not a regression, ~~ It is documented breakage but could you please direct ignorant in sympy me on the easiest way to mitigate (i.e. fix the code above)?

**Comment by oscarbenjamin** [comment]
To me this is nonsensical as a symbolic expression:
```
(t + 1.0e-14)*(t >= 0)
```
What exactly do you think that this is or what is it used for?

**Comment by yarikoptic** [comment]
ha ha -- what a great question I have not even asked myself with my Python rotten mind:
```ipython
In [1]: T=0; ((T >= 0) * (T+1.0e-14))
Out[1]: 1e-14

In [2]: T=1e-14; ((T >= 0) * (T+1.0e-14))
Out[2]: 2e-14
```
so indeed implicit casting of bools into `0`, `1` numerals is a paradigm I have used/relied on quite a bit in Python world.  newbee sympy question: What would be a proper sympy way to create such a conditional ?

**Comment by oscarbenjamin** [comment]
The proper sympy way would be to use a Piecewise:
```python
In [28]: T = Symbol('T')

In [29]: p = Piecewise((T + 1e-14, T >= 0), (0, True))

In [30]: p
Out[30]: 
⎧T + 1.0e-14  for T ≥ 0
⎨                      
⎩     0       otherwise

In [31]: p.subs(T, 1e-14)
Out[31]: 2.00000000000000e-14

In [32]: p.subs(T, 0)
Out[32]: 1.00000000000000e-14

In [33]: p.subs(T, -1)
Out[33]: 0
```
Alternatively you could use Heaviside:
```python
In [34]: p = Heaviside(T, 1) * (T + 1e-14)

In [35]: p
Out[35]: (T + 1.0e-14)⋅θ(T, 1)

In [36]: p.subs(T, 1e-14)
Out[36]: 2.00000000000000e-14

In [37]: p.subs(T, 0)
Out[37]: 1.00000000000000e-14

In [38]: p.subs(T, -1)
Out[38]: 0
```
https://docs.sympy.org/latest/modules/functions/elementary.html#piecewise
https://docs.sympy.org/latest/modules/functions/special.html#sympy.functions.special.delta_functions.Heaviside

**Comment by yarikoptic** [comment]
sweet, thank you @oscarbenjamin !!!
