### ISSUE TITLE
integrate(1 / (x ** 2 * sqrt(x ** 2 - 1))) gives wrong integral (lost sign when x < 0)

### ISSUE THREAD

**Issue by SenchoPens** [sympy/sympy#20982]
With Python 3.8.7 and sympy 1.7.1:
Integral is wrong, because when x < 0 it shoud be negative:
```
>>> integrate(1 / (x ** 2 * sqrt(x ** 2 - 1)))
⎧       _________
⎪      ╱      1         1
⎪ⅈ⋅   ╱  -1 + ──   for ──── > 1
⎪    ╱         2       │ 2│
⎪  ╲╱         x        │x │
⎨
⎪      ________
⎪     ╱     1
⎪    ╱  1 - ──      otherwise
⎪   ╱        2
⎩ ╲╱        x
```
But with `manual=True` the answer is correct:
```
>>> integrate(1 / (x ** 2 * sqrt(x ** 2 - 1)), manual=True)
⎧   ________
⎪  ╱  2
⎨╲╱  x  - 1
⎪───────────  for x > -1 ∧ x < 1
⎩     x
```

**Comment by SenchoPens** [comment]
Oh, and why does this happen?
```
>>> integrate(1 / x)
log(x)
```
It must be `log(|x|)`.

**Comment by mpeychev** [comment]
Some related examples where there are discrepancies related to the sign assumptions:

```
x = Symbol('x', real=True, nonzero=True)

>>> integrate(sqrt(x) * sqrt(x**3))
x**3/3

>>> integrate(log(x/sqrt(x**5)))
x*log(x**(-3/2)) + 3*x/2

>>> integrate(x + log(exp(x*log(x))))
x**2*log(x)/2 + x**2/4

>>> integrate(-log(x) + log(x**2) + 1)
x*log(x)
```

I believe these results are correct for `x > 0` but not in general. In particular, if one assigns the integrand to `f` and the result of the integration to `F`, SymPy fails to prove that `simplify(F.diff(x) - f) == 0` for all these cases.

**Comment by oscarbenjamin** [comment]
I think there is confusion over what it is that sympy returns when you call integrate with no limits. The returned result should be an antiderivative such that `F.diff(x) = f` for any values of x such that `F` and `f` are both defined.

In the case of e.g. `integrate(1/x, x) = log(x)` you suggest that it should be `log(|x|)` but the difference between `log(|x|)` and `log(x)` for negative `x` is `I*pi` which is a constant. You could imagine that the constant of integration is defined differently for different regions of `x` and in this case the two regions (positive and negative x) are separated by a singularity at `x=0` at which neither `1/x` or `log(x)` is defined. More generally you should think of this derivative as applying in the complex plane though in which case the `log(|x|)` form definitely doesn't work.

https://en.wikipedia.org/wiki/Logarithm#Derivative_and_antiderivative
