### ISSUE TITLE
ANTLR runtime and generated code versions disagree: 4.9.1!=4.7.2

### ISSUE THREAD

**Issue by adnion** [sympy/sympy#20999]
I tried
`pip install antlr4-python3-runtime==4.9.1`
Warning still present. I run `pip uninstall antlr4-python3-runtime` to remove it.
Again
`pip install antlr4-python3-runtime==4.7.2`
Warning still present

**Comment by oscarbenjamin** [comment]
Can you explain a bit more? What warning are you seeing? What code do you run to see the warning?

**Comment by adnion** [comment]
Using a clean venv solved it.
Is there a way to use ANTLR runtime version 4.9.1?

code to run:
```
import sympy
from sympy.parsing.latex import parse_latex
sympy.parsing.latex.parse_latex('1+1')
```
warning:
```
ANTLR runtime and generated code versions disagree: 4.9.1!=4.7.2
ANTLR runtime and generated code versions disagree: 4.9.1!=4.7.2
```
steps to solve the issue:
1. pip install sympy in a clean venv.
2. Get Error `ImportError: LaTeX parsing requires the antlr4 python package, provided by  pip (antlr4-python2-runtime or antlr4-python3-runtime) or conda (antlr-python-runtime)`
3. pip install antlr4-python3-runtime==4.7.2

**Comment by xiezhipeng-git** [comment]
use antlr4-python3-runtime-4.13.1
then 
Error evaluating expression: LaTeX parsing requires the antlr4 Python package, provided by pip (antlr4-python3-runtime) or conda (antlr-python-runtime), version 4.11
Evaluated result: None
is 
sympy need update antlr4-python3-runtime and change need version?

**Comment by jcomeauictx** [comment]
I solved this by upgrading antlr4: `sudo apt -t testing install libantlr4-runtime-java`, deleting generated files *{Lexer,Parser,Listener}.py *.interp, *.tokens, etc., and rebuilding them. Just upgrading the packages won't do it.
