### ISSUE TITLE
Both eye and zeros are slow for large matrices

### ISSUE THREAD

**Issue by oscarbenjamin** [sympy/sympy#21003]
The `eye` and `zeros` functions are slow for large matrices e.g.:
```
In [6]: %time ok = zeros(1000)
CPU times: user 5.53 s, sys: 38.2 ms, total: 5.57 s
Wall time: 5.6 s
```
It's not hard to make a list of zeros more quickly than this:
```
In [7]: %time ok = [S.Zero] * 1000**2
CPU times: user 4.46 ms, sys: 803 µs, total: 5.26 ms
Wall time: 5.31 ms
```

**Comment by hyadav2k** [comment]
@oscarbenjamin, This seems to work faster for my local, for `zeros`.
```
--- a/sympy/matrices/common.py
+++ b/sympy/matrices/common.py
@@ -1173,10 +1173,8 @@ def zeros(kls, rows, cols=None, **kwargs):
         """
         if cols is None:
             cols = rows
-        klass = kwargs.get('cls', kls)
-        rows, cols = as_int(rows), as_int(cols)
-
-        return klass._eval_zeros(rows, cols)
+        from sympy import Matrix
+        return Matrix([[0]*cols]*rows)

     @classmethod
     def companion(kls, poly):
```
```
In [1]: %time ok = zeros(1000)
Wall time: 1.25 s
```
Reference:
https://stackoverflow.com/a/44921249

Moreover, `NumPy` also has a `fill` method which it uses for [zeros](https://github.com/numpy/numpy/blob/fb215c76967739268de71aa4bda55dd1b062bc2e/numpy/matlib.py#L147-L149)

For `eye`, `NumPy` uses `zeros` and then assign `1` using iterator `flat` for the Diagonal. [NumPy eye](https://github.com/numpy/numpy/blob/v1.20.0/numpy/lib/twodim_base.py#L205-L217)

Kindly share your opinion,
Thanks.

**Comment by oscarbenjamin** [comment]
We can't use numpy. The internal data structure used by Matrix is a flat list and as I showed the list can be created in a few milliseconds so it should be possible to make zeros just as fast.

**Comment by hyadav2k** [comment]
No, I'm also suggesting the same, to implement using lists, should the diff implemented above be applied?
```
-        klass = kwargs.get('cls', kls)
-        rows, cols = as_int(rows), as_int(cols)
-
-        return klass._eval_zeros(rows, cols)
+        from sympy import Matrix
+        return Matrix([[0]*cols]*rows)
```

**Comment by oscarbenjamin** [comment]
It should be like:
```python
In [1]: rows = 1000

In [2]: cols = 1000

In [3]: %time ok = Matrix._new(rows, cols, [S.Zero]*(rows*cols), copy=False)
CPU times: user 1.97 ms, sys: 2.53 ms, total: 4.5 ms
Wall time: 4.52 ms
```
That takes 5 milliseconds. It directly creates the list that is used as the internal data for the resulting matrix. The `copy=False` argument is used to prevent `sympify` from being called (which otherwise slows it down to around 1 second).
