### ISSUE TITLE
solve returns incomplete solution for x**n = 1

### ISSUE THREAD

**Issue by hyadav2k** [sympy/sympy#21014]
For the equation below, `solve `does not return a complete set of solutions, as what if `n `is an even Integer or maybe any odd integer except for 1, or a fraction with numerator as even.
```
In [1]: solve(x**n-1, x)
Out[1]: [1]
```

**Comment by smichr** [comment]
`solve` (unlike `solveset`) does not guarantee a complete solution and has no way to represent conditional solutions. You could add the case of `n` being zero, too, which has a solution of `0`.

**Comment by hyadav2k** [comment]
What `solveset` does seem to be the most viable solution, to not to compute.
```
In [1]: s = solveset(x**n - 1, x)

In [2]: print(s)
ConditionSet(x, Eq(x**n - 1, 0), Complexes)                                
```
Maybe if we can do the same for `solve`, it will be fine.
@smichr, Kindly share your opinion.
Thanks.

**Comment by oscarbenjamin** [comment]
The equivalent for solve would be returning an empty list `[]` but there is no way in the solve API to distinguish between "can't solve the equation" and "equation has no solutions". That's why `solveset` has a different API. It is probably not helpful to change `solve` in cases like this but we could make use of solvset instead

**Comment by hyadav2k** [comment]
In the original issue, we can't use `solveset` instead of `solve` in the `odesimp` function, since it returns `ConditionSet` on the cases which were correctly solved by `solve`.
For e.g.
'''
In [5]: C1,C2=symbols('C1 C2')

In [6]: eq = Eq(Piecewise((sqrt(C1 - 2*f(x)), Eq(n, 0))), C2 + x)

In [7]: s=solveset(eq, f(x))

In [8]: print(s)
ConditionSet(f(x), C1 - 2*f(x) >= 0, Intersection(ImageSet(Lambda(x, C1/2 - x**2/2), Intersection(FiniteSet(C2 + x), Interval(0, oo))), Reals))

In [9]: s=solve(eq, f(x))

In [10]: print(s)
[Piecewise((C1/2 - (C2 + x)**2/2, Eq(n, 0)), (nan, True))]

'''

The issue occurs in `solve` at:
https://github.com/sympy/sympy/blob/9e8f62e059d83178c1d8a1e19acac5473bdbf1c1/sympy/solvers/solvers.py#L2570-L2571
Here if we put a check like `if any(isinstance(s, Symbol) for s in lhs.exp.free_symbols):` to see it doesn't return for an undefined symbol `n`, but working forward with this approach raises an error in other cases. 
The best would be to make `solve` return the passed equation as a solution, just like how `solveset` returns the same equation.
This will also resolve distinction between ` "can't solve the equation" and "equation has no solutions".`
Kindly share your opinion.
Thanks.

**Comment by oscarbenjamin** [comment]
> In the original issue, we can't use `solveset` instead of `solve` in the `odesimp` function, since it returns `ConditionSet` on the cases which were correctly solved by `solve`.

There are many cases that solve can handle but that solveset can not. Extending the capabilities of solveset is an ongoing project. This issue is about solve though and I can see @smichr's point that there's not much solve can do in this situation.

I'm going to close this.
