### ISSUE TITLE
AppliedPredicate should not be atom

### ISSUE THREAD

**Issue by JSS95** [sympy/sympy#21017]
`AppliedPredicate` has `is_Atom = True` by class attribute.

```python
>>> from sympy import Q
>>> from sympy.abc import x
>>> Q.positive(x).is_Atom
True
```

The comment says not to change this and making `is_Atom = False` indeed raised error in `logic/inference` module. However this should be fixed because applied predicate is a function applied to arguments and thus never should be atom. This attribute makes many tree-recursive operations not applied to the arguments in `AppliedPredicate`. There must be some way to allow inference on applied predicate without making it atom.

**Comment by asmeurer** [comment]
I agree with this. I also want to say that the idea that Atom should be the indicator of leaf notes in an expression tree is very misguided. The indicator of such should be an empty .args. Leaf nodes should not need to have a special attribute or be a subclass of a certain class. And conversely I don't think you should be able to fool algorithms into thinking you are a leaf node by pretending to be an Atom with is_Atom.
