### ISSUE TITLE
Support orienting adjacent reference frames in arbitrary orders

### ISSUE THREAD

**Issue by moorepants** [sympy/sympy#21036]
Suppose you want to establish relative orientation among frames A, B, C, D, and E as such:

```
A ----- B
|
|-------C----D
        |
        |----E
```

A is the root of the tree, B, D, and E are leaves. You do this now with code that looks like:

```python
B.orient(A)
C.orient(A)
D.orient(C)
E.orient(C)
```

This will establish rotation matrices for each connection in the above graph. But a user may, for whatever reason, do something like (call this the alternative use case):

```python
B.orient(A)
A.orient(C)
C.orient(D)
E.orient(C)
```
This currently does not work because with every call of `X.orient()` all adjacent relationships to `X` will be cleared. That is, calling `.orient()` assumes `self`'s orientation relationships should be overwritten. This is sometimes needed, for example if I do:

```python
B.orient(A, ...)
A.orient(B, ...)
```

Anything that was defined in `B.orient(A, ...)` should be fully replaced with the relationships established with `A.orient(B, ...)` because they may be inconsistent with each other. Or if a user tries to do a loop:

```python
B.orient(A)
C.orient(B)
A.orient(C)
```

The last line should raise an error and say something like "Loops in graph not allowed", but what it does is overwrites all relationships to `A` in the last line, effectively undoing the first line.

The alternative use case should work. There is no reason we shouldn't allow construction of the graph in any sequence. Overwriting the relationships to `self` in calls to `orient()` is unnecessary. I think it was implemented like that because it was easier than checking the graph for consistency in a more thorough way.

I think the relationships between points do not have this issue and you can establish them in any order you like. It would be nice if frames also allowed that.

Here is some code that shows how the method `ReferenceFrame._dcm()` wipes relationships of `self`:

```ipython
IPython 7.21.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import sympy as sm

In [2]: import sympy.physics.mechanics as me

In [3]: A, B, C = sm.symbols("A, B, C", cls=me.ReferenceFrame)

In [4]: a, b, c = sm.symbols('a, b, c')

In [5]: B.orient(A, 'Axis', (a, A.x))

In [6]: A._dcm_dict
Out[6]: 
{B: Matrix([
 [1,      0,       0],
 [0, cos(a), -sin(a)],
 [0, sin(a),  cos(a)]])}

In [7]: B._dcm_dict
Out[7]: 
{A: Matrix([
 [1,       0,      0],
 [0,  cos(a), sin(a)],
 [0, -sin(a), cos(a)]])}

In [8]: C._dcm_dict
Out[8]: {}

In [9]: B.orient(C, 'Axis', (b, C.x))

In [10]: A._dcm_dict
Out[10]: {}

In [11]: B._dcm_dict
Out[11]: 
{C: Matrix([
 [1,       0,      0],
 [0,  cos(b), sin(b)],
 [0, -sin(b), cos(b)]])}

In [12]: C._dcm_dict
Out[12]: 
{B: Matrix([
 [1,      0,       0],
 [0, cos(b), -sin(b)],
 [0, sin(b),  cos(b)]])}

In [13]: sm.__version__
Out[13]: '1.7.1'
```

**Comment by moorepants** [comment]
@angadhn I've opened an issue for this topic that we discussed last night.

**Comment by moorepants** [comment]
A minimum enhancement here would be to explain in the various `.orient*()` documentation that any call to `X.orient*()` will remove any prior relationships to `X` and that to construct a chain or tree of relative oriented reference frames requires that only un-oriented  frames can be added to the ends of the chain/branches.

**Comment by shattar** [comment]
I'm adding a reference to a previously closed/rejected pull request here. #13824
It is very similar, however, the solution there was to allow loops in a graph.

**Comment by sidhu1012** [comment]
> Or if a user tries to do a loop:
> 
> ```python
> B.orient(A)
> C.orient(B)
> A.orient(C)
> ```
> 
> The last line should raise an error and say something like "Loops in graph not allowed", but what it does is overwrites all relationships to `A` in the last line, effectively undoing the first line.
> 
> The alternative use case should work. There is no reason we shouldn't allow construction of the graph in any sequence. Overwriting the relationships to `self` in calls to `orient()` is unnecessary. I think it was implemented like that because it was easier than checking the graph for consistency in a more thorough way.
> 
> I think the relationships between points do not have this issue and you can establish them in any order you like. It would be nice if frames also allowed that.


#2171 fixed almost all of the problems mentioned here. Only this part is left to be done.

**Comment by sidhu1012** [comment]
@moorepants I was wondering if instead of giving error in case of loops in frames, shouldn't we raise `warning`  as we did in velocity.

**Comment by sidhu1012** [comment]
> @moorepants I was wondering if instead of giving error in case of loops in frames, shouldn't we raise `warning`  as we did in velocity.

@moorepants So it should be a warning or an error?

**Comment by moorepants** [comment]
I guess we should be consistent with what we did with point relationships.

**Comment by moorepants** [comment]
I think something like that is needed. We may even need a graph object to manage these things in these modules.
