### ISSUE TITLE
Incorrect computation of a basic limit, regression from 1.6.2 to 1.7.1

### ISSUE THREAD

**Issue by nathancarter** [sympy/sympy#21038]
Using SymPy 1.6.2:

```python
from sympy import *
var('x')
limit( sin(pi*x)/(3*x-12), x, 4 )  # gives the answer pi/3
```

Manual calculation using l'Hôpital's rule verifies that the above answer is correct.

Using SymPy 1.7.1:

```python
from sympy import *
var('x')
limit( sin(pi*x)/(3*x-12), x, 4 )  # gives the answer 0
```

**Comment by nathancarter** [comment]
Seems related to #21031

**Comment by oscarbenjamin** [comment]
Bisected to 267a4fdc881cfb6c9b3ad6db7d41266b94d65692 from #19432 CC @sachin-4099 @jksuom

**Comment by jksuom** [comment]
This seems to result from a bug in `leadterm`:
```
>>> f = sin(pi*x)/(3*x-12)
>>> f.subs(x, x + 4)
>>> g = f.subs(x, x + 4)
>>> g.leadterm(x)
(0, 0)
```
The output should be `(pi/3, 0)`:
```
>>> g.nseries(x, 0, 3)
pi/3 - pi**3*x**2/18 + O(x**3)
```
It looks like `sin._eval_as_leading_term` should be fixed.
