### ISSUE TITLE
Limit of "limit (((1+x)**(1/x)-(1+2*x)**(1/(2*x)))/asin (x),x,0)" is wrong with v1.7.1

### ISSUE THREAD

**Issue by basheewang** [sympy/sympy#21031]
I am trying to calculate this limit, and I get wrong answer with sympy 1.7.1:
```
Python 3.8.3 (tags/v3.8.3:6f8c832, May 13 2020, 22:37:02) [MSC v.1924 64 bit (AMD64)]
Type 'copyright', 'credits' or 'license' for more information
IPython 7.21.0 -- An enhanced Interactive Python. Type '?' for help.
In [1]: from sympy import *
In [2]: x=symbols('x')
In [3]: limit (((1+x)**(1/x)-(1+2*x)**(1/(2*x)))/asin (x),x,0)
Out[3]: 0
```
However, when I calculate same expression with sympygamma website, and I get the correct answer: 

https://www.sympygamma.com/input/?i=limit+%28%28%281%2Bx%29**%281%2Fx%29-%281%2B2*x%29**%281%2F%282*x%29%29%29%2Fasin+%28x%29%2Cx%2C0%29

Please help to check if there is any bug, or what I have done wrong.

**Comment by oscarbenjamin** [comment]
SymPy Gamma uses sympy 1.6.2 so that's the difference.

I've bisected this to 14a7d0045f64a29a384ff633e53b1b36e3a96a2d from #19646 (CC @sachin-4099 @jksuom )
