### ISSUE TITLE
Wrong Handling by Piecewise

### ISSUE THREAD

**Issue by almighty123789** [sympy/sympy#21033]
```
>>> z  =  symbols('z')
>>> f  =  Piecewise((Rational(1, 4), z == 0), (2*z, True))
>>> f.subs(z, 0)
0
```

**Comment by oscarbenjamin** [comment]
It should be `Eq(z, 0)`

**Comment by almighty123789** [comment]
Oh okay, but why should the Eq be used?  I take f to be a function of z, and since I want to evaluate the value of the function at the point  z=0, shouldn't subs be used? Since we use subs for other functions as well.

**Comment by oscarbenjamin** [comment]
Print the result out:
```python
In [16]: z = symbols('z')

In [17]: z == 0
Out[17]: False

In [18]: Piecewise((Rational(1, 4), z == 0), (2*z, True))
Out[18]: 2⋅z

In [19]: Piecewise((Rational(1, 4), False), (2*z, True))
Out[19]: 2⋅z
```
You are passing `False` to the `Piecewise` so that case is always removed. The `==` function is a Python operation that always returns True or False to indicate structural equality. The `Eq` class represents symbolic equality and is what should be used in a `Piecewise`.

**Comment by almighty123789** [comment]
@oscarbenjamin  Thanks a lot ! . I didn't completely understand the use of Eq  . 
I will close the issue now.
