### ISSUE TITLE
Error in https://docs.sympy.org/latest/documentation-style-guide.html

### ISSUE THREAD

**Issue by ks147** [sympy/sympy#21043]
I was trying to figure out how to write `rst` files and I noticed an error in the style guide. I may be wrong and might have missed something here but when I follow these instructions 

![image](https://user-images.githubusercontent.com/37146279/110106807-23123f00-7dd0-11eb-88a6-3b2638ddbeec.png)

I get the following error in terminal 

```
(base) evilmorty@Rust-Bucket:~/Documents/sympy/doc$ make html
rm -rf _build/logo
mkdir -p _build/logo
python ./generate_logos.py -d
INFO:root: File saved: ./_build/logo/sympy-notail.svg
INFO:root: File saved: ./_build/logo/sympy-notailtext.svg
INFO:root: File saved: ./_build/logo/sympy-notext.svg
ERROR:root:rsvg-convert: command not found. Install librsvg
make: *** [Makefile:144: logo] Error 127
```

I opened the file `sympy/doc/Makefile` and saw that there was no option called `html` rather there was an option `htmlhelp`
when I ran `make htmlhelp` It completed the required build and I was able to see the documentation in my browser. I feel this could be because of changes to `Makefile` in the most recent version, if this is the case then the docs should be updated

**Comment by oscarbenjamin** [comment]
> ERROR:root:rsvg-convert: command not found. Install librsvg

Are you sure you have installed librsvg?

**Comment by ks147** [comment]
It shows already installed
```
(base) evilmorty@Rust-Bucket:~$ sudo apt-get install librsvg2-bin
Reading package lists... Done
Building dependency tree       
Reading state information... Done
librsvg2-bin is already the newest version (2.48.9-1ubuntu0.20.04.1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```

**Comment by oscarbenjamin** [comment]
Have you tried running `rsvg-convert` directly?

**Comment by ks147** [comment]
I didn't install imagemagick, that's what was causing the issue.
