### ISSUE TITLE
FWHT gives a wrong result.

### ISSUE THREAD

**Issue by alxfed** [sympy/sympy#21048]

**Comment by alxfed** [comment]
the fwht([4, 2, 2, 0, 0, 2, -2, 0]) is [1,  1,  0, 1, 0, 0, 1, 0] **_not_** [8, 0, 8, 0, 8, 8, 0, 0] as in your example. The transform produces a **_wrong result_**!

**Comment by oscarbenjamin** [comment]
I don't know the Hadamard transform myself but according to wikipedia there is a `1/sqrt(2)` normalisation constant that is "sometimes omitted".

With that factor omitted the result here seems correct according to the wikipedia definition:
```python
In [24]: H = Matrix([1])

In [25]: H = BlockMatrix([[H, H], [H, -H]])

In [26]: H = BlockMatrix([[H, H], [H, -H]])

In [27]: H = BlockMatrix([[H, H], [H, -H]])

In [28]: H = H.as_explicit()

In [29]: H
Out[29]: 
⎡1  1   1   1   1   1   1   1 ⎤
⎢                             ⎥
⎢1  -1  1   -1  1   -1  1   -1⎥
⎢                             ⎥
⎢1  1   -1  -1  1   1   -1  -1⎥
⎢                             ⎥
⎢1  -1  -1  1   1   -1  -1  1 ⎥
⎢                             ⎥
⎢1  1   1   1   -1  -1  -1  -1⎥
⎢                             ⎥
⎢1  -1  1   -1  -1  1   -1  1 ⎥
⎢                             ⎥
⎢1  1   -1  -1  -1  -1  1   1 ⎥
⎢                             ⎥
⎣1  -1  -1  1   -1  1   1   -1⎦

In [31]: (H * Matrix([4, 2, 2, 0, 0, 2, -2, 0])).transpose()
Out[31]: [8  0  8  0  8  8  0  0]
```
https://en.wikipedia.org/wiki/Hadamard_transform

**Comment by alxfed** [comment]
@oscarbenjamin 
Yeah, let's not normalize the orthogonal basis functions, how cute. :)

Why take the examples for Mathrowks then (that's where they come from, there is no doubt about it)? In order to make it more confusing (after **_not mentioning_** this lack of normalization)?

**Comment by oscarbenjamin** [comment]
The example from Mathworks does not use the `1/sqrt(2)` normalisation either. If you use that then the result is:
```
[2⋅√2  0  2⋅√2  0  2⋅√2  2⋅√2  0  0]
```
Mathworks uses a `1/N` in their definition for fwht but not ifwht. Sympy's definition seems to be the other way round.

**Comment by alxfed** [comment]
True. You have a point. Thank your for your cooperation. :)
