### ISSUE TITLE
are there performance or memory benchmarks for prime generation with sympy?

### ISSUE THREAD

**Issue by rzeta0** [sympy/sympy#21051]
Is there any evidence that speed or memory performance would be improve with:

1. a different algorithm / data structure

2. implementation in C?

I did a search but couldn't find any reports or write-ups of such experiments.

**Comment by AbhiSahane0** [comment]
Can I solve this issue

**Comment by rzeta0** [comment]
ive written a very simple pure python and rather naive prime generator just to see the difference 

it seems for primes up to 1000,  simply doesn't perform very well

is thi because it is optimised for larger ranges?


```
class PrimeGenerator():
  def __init__(self, length=10):
    # initial lengthlargest_factor = int(math.sqrt(self.length))
    self.length = length
    # largest factor for sieve
    self.largest_factor = int(math.sqrt(self.length))

    # initialise mask
    self.primes_mask = numpy.ones(length)
    # set first item 1 to false
    self.primes_mask[0] = 0
    
    #call sieve
    self.sieve_mask()

    # initialise primes list
    self.primes = [x+1 for x in range(self.length) if self.primes_mask[x]]
    pass
  
  def sieve_mask(self):
    for factor in range(2,self.largest_factor+1):
      for multiple in range(factor*2, self.length+1, factor):
        #print(factor, multiple)
        self.primes_mask[multiple-1] = 0
        pass
      #print()
      pass
    
    pass

  def get_list(self):
    return self.primes
  
  def nth_prime(self,n):
    return self.primes[n-1]
```


<img width="608" alt="Screenshot 2021-03-10 at 04 09 12" src="https://user-images.githubusercontent.com/73765323/110575674-366a3500-8157-11eb-8f68-79b18fda54be.png">
<img width="1099" alt="Screenshot 2021-03-10 at 04 10 38" src="https://user-images.githubusercontent.com/73765323/110575679-379b6200-8157-11eb-81fe-7cb7a3b1a880.png">
<img width="574" alt="Screenshot 2021-03-10 at 04 11 17" src="https://user-images.githubusercontent.com/73765323/110575681-3833f880-8157-11eb-907f-583d0834cbfb.png">

**Comment by oscarbenjamin** [comment]
Your prime generator caches all of the primes so it doesn't make sense to use timeit which will run in a loop: every iteration after the first is simply retrieving from the cache.

To generate many primes like this in sympy you can use sieve:
```
In [1]: %time ok = sieve[1:1001]
CPU times: user 6.3 ms, sys: 374 µs, total: 6.68 ms
Wall time: 6.5 ms

In [2]: %time ok = sieve[1:1001]
CPU times: user 21 µs, sys: 12 µs, total: 33 µs
Wall time: 37 µs
```
Note that this also caches so the second call is a lot faster.

**Comment by oscarbenjamin** [comment]
> I ask because most users will use the prime(nth) function and a dynamically extending sieve might be useful.

That's what `sieve` is for. Maybe it can be made clearer in the documentation.

**Comment by rzeta0** [comment]
Yes I think the guides / documentation should point users to sieve.

For clarity - what's the intended use case for prime(nth) ?

**Comment by oscarbenjamin** [comment]
> For clarity - what's the intended use case for prime(nth) ?

I don't know. Probably it can be made more efficient.

**Comment by smichr** [comment]
There are several ways to generate primes of interest, e.g. `primerange`, `nextprime`, etc... The Sieve is an internal detail that you mostly don't need to worry about. If you want the 100th prime you can get that with `prime(100) -> 541` without worrying about how many primes have been calculated in Sieve. See documentation in `ntheory/generate.py`.

**Comment by rzeta0** [comment]
@smichr thanks for your input

I think user-facing documentation that points to the right function for the various scenarios would be good. Example scenarios:
 * a small number of random nth prime queries - performance not an issue for p < 10,0000
 * a series of interrogations of primes in a range - a function that takes a hint at the range being queries so a sieve can be built
 * sequential access to primes in order - optimised for experimental maths where all primes in large ranges are queried
 * .. etc ..
