### ISSUE TITLE
Updating readme.md

### ISSUE THREAD

**Issue by bhav09** [sympy/sympy#21072]
Hello Maintainers,

I am really happy to see such an enriching repo of Sympy, all the contributors have done an un-explicable job! I am willing to contribute to it too. I have realised a few changes in readme can make the markdown even more appealing.

The changes I want to propose:

1. Adding a contents section to markdown which would take the readers on a walk on all the topics.
2. Adding a section that would help navigate some really basic yet important features of Sympy.

The reason I am proposing this to you is, despite being a really wonderful curation of Sympy, the repo still can be overwhelming to a beginner who seeks knowledge. To make it easier for them, I wish to contribute to the above-mentioned areas.

Please assign the issue to me. Thank you :)

**Comment by bhav09** [comment]
Hello @asmeurer, can you please assign the issue to me. That would be helpful. Thanks :)

**Comment by variable-jain** [comment]
Hello @asmeurer, I want to work on this issue. Please assign this issue to me.

**Comment by bhav09** [comment]
@Smit-create can you please review the PR? And confirm whether issues are assigned on a first come first serve basis because @variable-jain is acting unethical and stealing issues and forcing PRs. Please look into it. Thanks.

**Comment by oscarbenjamin** [comment]
I don't think this is needed. The README is not that long.
