### ISSUE TITLE
is_polynomial claims that x is a polynomial of y

### ISSUE THREAD

**Issue by rikardn** [sympy/sympy#21088]
I am working on implementing `is_polynomial` in symengine and I found a strange behaviour in the corresponding method in sympy. The following example return `True` which would imply that `x` is a polynomial in `y` but I would think it should return `False`. Have I misunderstood something?

```python
import sympy
x, y = sympy.symbols('x y')

x.is_polynomial(y)
Out[3]: True
```

**Comment by oscarbenjamin** [comment]
Considered as a polynomial in the generator `y` the expression `x` is a constant polynomial e.g.:
```python
In [1]: (y*x**2 + y*x + y).is_polynomial(x)
Out[1]: True

In [2]: (y*x + y).is_polynomial(x)
Out[2]: True

In [3]: (y).is_polynomial(x)
Out[3]: True
```

**Comment by rikardn** [comment]
Ok, but are there any cases when `is_polynomial`would give different results between having an argument or not?

```python
In [1]: (y*x**2 + y*x + y).is_polynomial()
Out[1]: True

In [2]: (y*x + y).is_polynomial()
Out[2]: True

In [3]: (y).is_polynomial()
Out[3]: True
```

All give the same results as when asking for polynomials in `x`. Also 

```python
z = sympy.Symbol('z')
(y*x**2 + y*x + y).is_polynomial(z)
Out[12]: True
```

gives `True`. My feeling is that it doesn't matter if I ask for polynomials in a variable.

**Comment by rikardn** [comment]
Ok I found an example which I think explains the difference.

```python
(x**(-2)).is_polynomial(x)
Out[1]: False

(x**(-2)).is_polynomial(y)
Out[1]: True
```

**Comment by oscarbenjamin** [comment]
Any non-polynomial function (`sqrt`, `exp`, `sin`, ...) of a symbol would give an example:
```python
In [8]: exp(x).is_polynomial()
Out[8]: False

In [9]: exp(x).is_polynomial(y)
Out[9]: True
```
If no arguments are given then all free symbols from the expression are treated as the generators.

**Comment by rikardn** [comment]
Thanks @oscarbenjamin I understand now.

If `is_polynomial` has no argument: all free_symbols are taken as variables in the polynomial.
Arguments to `is_polynomial`: symbols in free_symbols and not in arguments are taken as constants

```python
(sympy.sin(x)).is_polynomial(x)
Out[1]: False

(sympy.sin(x)).is_polynomial(y)
Out[2]: True
```
