### ISSUE TITLE
Incorrect latex with unevaluated Mul

### ISSUE THREAD

**Issue by proy87** [sympy/sympy#21094]
`latex(Mul(6, S.Half, evaluate=False))` gives `6 1/2`, so there is no `numbersep`.

**Comment by iam-abbas** [comment]
Hello, I am trying to get myself familiar with the code base and I would like to take a look at this issue. Could you elaborate a little more on what is expected output and the problem?

**Comment by proy87** [comment]
The correct output should be `6 \cdot 1/2`

**Comment by namannimmo10** [comment]
The correct output should be: 
```ruby
>>> latex(Mul(6, S.Half, evaluate=False))
'6 \\cdot  \\frac{1}{2}'
```

This is an easy fix @iam-abbas , you probably need to make changes here:
https://github.com/sympy/sympy/blob/2346054bb4888ef7eec2f6dad6c3dd52bf1fe927/sympy/printing/latex.py#L521

**Comment by proy87** [comment]
Yes, the problem is here: `if _between_two_numbers_p[0].search(last_term_tex) and _between_two_numbers_p[1].match(term_tex):`

Don't understand why regex is used instead of testing whether it is a number.

**Comment by iam-abbas** [comment]
I have noticed another issue due to the same problem
```Python
>>> sympy.latex(sympy.Mul(sympy.Rational(2, 3),sympy.Rational(5, 7), evaluate=False))
'\\frac{2}{3} \\frac{5}{7}'
```
I believe it should be `'\\frac{2}{3} \\cdot \\frac{5}{7}'`.

I found the above in tests. I fixed the issue by checking for the number in `term` instead of the latex version of term. Should I change the tests as well and include them in the PR?

**Comment by proy87** [comment]
Similarly `latex(Add(16, Mul(-1,-1,evaluate=False), evaluate=False))` outputs `16--1`. Here the problem is with `_needs_add_brackets` function. Don't understand why we need it if there is a `_needs_brackets` function.

**Comment by Shashvat6264** [comment]
Hi, I am trying to get myself familiar with the code base and I would like to take a look at this issue. Could you elaborate a little more on the current problem?

**Comment by proy87** [comment]
It doesn't work.
```
expr = Mul(Integer(2),S.Half, S.One/3, evaluate=False)
>>> latex(expr)
'2 \\frac{1}{2} \\frac{1}{3}'
```

**Comment by oscargus** [comment]
> It doesn't work.

Is it the cdot that is missing or what do you expect?

**Comment by proy87** [comment]
@oscargus , it looks like it is not in 1.9 version.
