### ISSUE TITLE
Não consigo plotar gráficos em 2D nem 3D

### ISSUE THREAD

**Issue by DanielMarinelle** [sympy/sympy#21095]
Olá pessoal, Bom dia Não consigo plotar gráficos visto que estou tentando fazer uma vídeo aula ajudando a entender gráficos de funções para minha universidade.

**Comment by bjodah** [comment]
Hi Daniel, thank you for your interest in SymPy. Would you mind trying to write issues in English? Google translate is probably fine. Thanks!
