### ISSUE TITLE
expand should not split infinite sums

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#21151]
```py
>>> expr = Sum(-log(1 + 3/(4*k)) + 3/(4*k), (k, 1, oo))
>>> expr.evalf()
0.348510627655664
>>> pprint(expr.expand(), order='none')
  ∞                     ∞
 ____                  ____
 ╲                     ╲
  ╲                     ╲
   ╲      ⎛     3 ⎞      ╲   3
   ╱  -log⎜1 + ───⎟ +    ╱  ───
  ╱       ⎝    4⋅k⎠     ╱   4⋅k
 ╱                     ╱
 ‾‾‾‾                  ‾‾‾‾
k = 1                 k = 1
```

The sum in question converges, but the split sums clearly do not (the second is a harmonic series).

Note you have to print this manually with `order='none'` otherwise the printer will hang trying to numerically evaluate it (a known issue, see for instance https://github.com/sympy/sympy/issues/19790 and https://github.com/sympy/sympy/issues/10800).

**Comment by sylee957** [comment]
My opinion is that explicit calls of `expand` for sum or limit or integrals should be left as formal operation on trees, rather than mathematically correct operation (I'm not sure convergence can be determined easily or cheaply.)
(But it can be carefully applied for `doit`)

**Comment by asmeurer** [comment]
For me, this was part of a larger expression. I called expand() (actually factor(), which called expand()) to try to simplify it, but it resulted in an expression that was mathematically wrong. Functions like expand() should never perform operations that are mathematically incorrect. 

There's no need to check convergence. expand() should not expand infinite sums, unless possibly force=True is provided.

**Comment by sylee957** [comment]
For mathematical correctness of expansion, integral would already be doing wrong like
```
from sympy import *

x = Symbol('x')
Integral((exp(I/x) - 1) * sin(x), (x, 0, oo)).expand()
```

(Which is an example from https://doi.org/10.1145/2016567.2016569)

**Comment by priyanshu-panwar** [comment]
Hello masters, this is Priyanshu Panwar eagerly looking to participate in GSOC 2021 via SymPy org. Can I please work on this issue if you people can allow me and guide me a bit?

**Comment by sylee957** [comment]
I'm fine with changing the behavior of summation, despite some counterexamples that are hard to answer, but I hope these sort of things can get organized for a better solution in future. So you can go on.

**Comment by meganly** [comment]
@priyanshu-panwar are you still working on this issue?

We can change `_eval_expand_basic` in the `AddWithLimits` class to prevent expansion of integrals and sums with infinite limits as follows:

``` python
--- a/sympy/concrete/expr_with_limits.py
+++ b/sympy/concrete/expr_with_limits.py
@@ -592,7 +592,7 @@ def _eval_factor(self, **hints):
 
     def _eval_expand_basic(self, **hints):
         summand = self.function.expand(**hints)
-        if summand.is_Add and summand.is_commutative:
+        if summand.is_Add and summand.is_commutative and self.has_finite_limits:
             return Add(*[self.func(i, *self.limits) for i in summand.args])
         elif isinstance(summand, MatrixBase):
             return summand.applyfunc(lambda x: self.func(x, *self.limits))
```

I'm happy to create a PR for this.

**Comment by asmeurer** [comment]
Feel free to take over things like this with comments that are over a year old.
