### ISSUE TITLE
Strange behaviour of evalf on cubic roots

### ISSUE THREAD

**Issue by step135** [sympy/sympy#21160]
```
z=-(8+sqrt(65))**(Symbol("2")/3)+(8+sqrt(65))**(Symbol("4")/3)
z.evalf()
```
<img src="https://render.githubusercontent.com/render/math?math=-%2016.0622577482985%5E%7B0.333333333333333%20%5Ccdot%202%7D%20%2B%2016.0622577482985%5E%7B0.333333333333333%20%5Ccdot%204%7D">

It is supposed that the result is a float number, not a semi-evaluated expression.

**Comment by oscarbenjamin** [comment]
That's because you've put symbols in the expression. A `Symbol` with the name `2` is not the same as the number `2`. Use `S("2")` rather than `Symbol("2")`.

**Comment by step135** [comment]
Replacing `Symbol` with `S` fixes the issue. They have different behavior, but shows as the same:
```python
>>> type(S("x"))
<class 'sympy.core.symbol.Symbol'>
>>> type(Symbol("x"))
<class 'sympy.core.symbol.Symbol'>
```

**Comment by oscarbenjamin** [comment]
This is explained in the tutorial. I'm closing this as there is no issue. Feel free to use the mailing list to ask questions about using sympy.
