### ISSUE TITLE
Documentation about dsolve_system not up-to-date

### ISSUE THREAD

**Issue by rotton** [sympy/sympy#21164]
I am new to SymPy (but have used [OctSymPy](https://github.com/cbm755/octsympy) in the past).
I just read through the documentation and noticed that there are some formatting errors.
https://github.com/sympy/sympy/blob/9e8f62e059d83178c1d8a1e19acac5473bdbf1c1/sympy/solvers/ode/systems.py#L2043
Til line 2056;
https://github.com/sympy/sympy/blob/9e8f62e059d83178c1d8a1e19acac5473bdbf1c1/sympy/solvers/ode/systems.py#L2056 
It is rendered as plain text in the documentation, not as code. Probably just a blank line missing or so. If I was familiar with RST syntax and doxygen, I could probably just fix it by myself.

Also, when I execute this line (either locally or in SymPy Live Shell),
https://github.com/sympy/sympy/blob/9e8f62e059d83178c1d8a1e19acac5473bdbf1c1/sympy/solvers/ode/systems.py#L2035

I get the following error:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named systems
```

**Comment by oscarbenjamin** [comment]
The issue with SymPy Live is that it needs to be updated to latest SymPy and Python 3.x:
https://github.com/sympy/sympy-live/issues/175

The formatting problem is just that a blank line is needed before the doctest examples. I'll mark this as easy to fix for adding the blank lines.

**Comment by rotton** [comment]
> The issue with SymPy Live is that it needs to be updated to latest SymPy and Python 3.x:
> [sympy/sympy-live#175](https://github.com/sympy/sympy-live/issues/175)

You are right. I had SymPy 1.5.1 locally before; after upgrading to 1.7.1 via `pip`, it does not throw an error anymore.
