### ISSUE TITLE
Printing of Rational Functions with floats can be improved.

### ISSUE THREAD

**Issue by Jatin2020-24** [sympy/sympy#21161]
```python
from sympy import pprint, Symbol
x = Symbol('x')
pprint((2*x + 5)/(2.5*x))

Out[1]:  
0.4.(2.x + 5)
_____________
     x
```
Output should be -
```python
  (2.x + 5)
 ____________
     2.5.x
```

**Comment by oscarbenjamin** [comment]
There is no 2.5 in the resulting expression:
```python
In [60]: expr = (2*x + 5)/(2.5*x)

In [61]: expr
Out[61]: 
0.4⋅(2⋅x + 5)
─────────────
      x      

In [62]: expr.args
Out[62]: 
⎛     1         ⎞
⎜0.4, ─, 2⋅x + 5⎟
⎝     x         ⎠
```

**Comment by Jatin2020-24** [comment]
ok, I understand my mistake.

**Comment by Jatin2020-24** [comment]
It is my misunderstanding.
So no need of this issue.
I am closing this issue.

**Comment by Jatin2020-24** [comment]
I am reopening this issue.

**Comment by Jatin2020-24** [comment]
> There is no 2.5 in the resulting expression:
> 
> ```python
> In [60]: expr = (2*x + 5)/(2.5*x)
> 
> In [61]: expr
> Out[61]: 
> 0.4⋅(2⋅x + 5)
> ─────────────
>       x      
> 
> In [62]: expr.args
> Out[62]: 
> ⎛     1         ⎞
> ⎜0.4, ─, 2⋅x + 5⎟
> ⎝     x         ⎠
> ```

Why floating point number 2.5 is converted to 0.4 ?

It should remain as it is.

**Comment by asmeurer** [comment]
This seems to be the same issue as https://github.com/sympy/sympy/issues/5521, and it should be closed for the same reason I described there. Fixing this would mean fundamentally changing the way SymPy represents expressions, and it wouldn't really be worth it. If you really want to represent the expression in that way for printing, you can construct it manually using evaluate=False. 

```
>>> sympify('(2*x + 5)/(2.5*x)', evaluate=False)
(2*x + 5)/((2.5*x))
```
