### ISSUE TITLE
Discuss about the integration of `linsolve`, `nonlinsolve` with `solveset`.

### ISSUE THREAD

**Issue by MaqOwais** [sympy/sympy#21172]
I've planned to work on this topic so, to get better clarity for the integration of `linsolve`, `nonlinsolve` with `solveset`, i.e to enhance the functionality of `solveset`, I've opened this.

Any ideas, suggestions regarding this topic are welcome to discuss here : )

**Comment by smichr** [comment]
Maybe the [discussion page](https://github.com/sympy/sympy/discussions) is a better place for this? Any concrete issues that need to be fixed can be opened here.

**Comment by oscarbenjamin** [comment]
Since this is on the discussion page now I'll close this: https://github.com/sympy/sympy/discussions/21181
