### ISSUE TITLE
Irregular Boundary conditions of Integer set as it returns the same.

### ISSUE THREAD

**Issue by MaqOwais** [sympy/sympy#21170]
**case 1**

```
>>> d = Range(0,5)
>>> d
Range(0, 5, 1)

>>> d.boundary
Range(0, 5, 1)

>>> set(d.boundary)
{0, 1, 2, 3, 4}

>>> d.sup
4

>>> d.inf
0
```
**case 2**

```
>>> d=S.Integers
>>> d.boundary
Integers

>>> set(d.boundary)
# hangs

>>> d.inf
-oo

>>> d.sup
oo

```

**case 3**
```
>>> R = Interval(20,80)
>>> R
Interval(20, 80)

>>> R.boundary
FiniteSet(20, 80)

>>> set(R.boundary)
{80, 20}

>>> R.sup
80

>>> R.inf
20
```

**case 4**

```
>>> R = Reals
>>> R.boundary
EmptySet

>>> set(R.boundary)
set()

>>> R.inf
-oo

>>> R.sup
oo
```
From the above cases ( 1 & 2 ), it's clear that the conditions for boundary should be changed for `S.Integers`.
I think should be made very similar to `Reals`.
Due to this irregularity, this issue has arisen #19794 (specifically, case 2).Where `solveset` calls `solve_univariate_inequality`.
Related PR --> #21156

**Comment by oscarbenjamin** [comment]
> From the above cases ( 1 & 2 ), it's clear that the conditions for boundary should be changed for `S.Integers`.

It's not clear to me that it should be changed. If the integers are viewed as a subset of the reals then every integer is a boundary point since there is no open set around any integer that remains a subset of the integers.

**Comment by MaqOwais** [comment]
> It's not clear to me that it should be changed. If the integers are viewed as a subset of the reals then every integer is a boundary point since there is no open set around any integer that remains a subset of the integers.

Oh, Actually I thought here boundary conditions are just starting and ending points (which was it meant literally) of a particular set. 
Now it's clear that "_If the integers are viewed as a subset of the reals then every integer is a boundary point since there is no open set around any integer that remains a subset of the integers._".

Thanks for your explanation : )
