### ISSUE TITLE
Incorrect residue of `x**2*cot(pi*x)/(x**4 + 1)`

### ISSUE THREAD

**Issue by sylee957** [sympy/sympy#21176]
```
x = Symbol('x')
residue(x**2*cot(pi*x)/(x**4 + 1), x, -sqrt(2)/2 - sqrt(2)*I/2)
```
~Gives `AttributeError: 'int' object has no attribute 'removeO'`~
Now it gives wrong result

**Comment by oscarbenjamin** [comment]
This fixes it:
```diff
diff --git a/sympy/core/mul.py b/sympy/core/mul.py
index 5fb540a627..db84a3a62e 100644
--- a/sympy/core/mul.py
+++ b/sympy/core/mul.py
@@ -1904,7 +1904,7 @@ def coeff_exp(term, x):
                 res += Order(x**n, x)
             return res
 
-        res = 0
+        res = S.Zero
         ords2 = [Add.make_args(factor) for factor in facs]
 
         for fac in product(*ords2):
```

**Comment by 0sidharth** [comment]
I think the value of the residue being calculated is wrong. According to wolfram, it should be -0.1796 - 0.1716i
https://www.wolframalpha.com/input/?i=residue%28x**2*cot%28pi*x%29%2F%28x**4+%2B+1%29%2C+-sqrt%282%29%2F2+-+sqrt%282%29*I%2F2%29

**Comment by 0sidharth** [comment]
@oscarbenjamin @sylee957 should this issue be reopened, or should a new issue be opened for the above error?
