### ISSUE TITLE
Document parse_expr in the sympify() docstring

### ISSUE THREAD

**Issue by thomasaarholt** [sympy/sympy#21207]
In the example below, sympy raises a fuss because it is missing a multiplier between `2` and `x`.
It looks like it attempts to sympify the expression `'could not parse '2x'`, which is strange and confusing.

```python
import sympy as sp
sp.sympify("2x+1")

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
ValueError: Error from parse_expr with transformed code: "Integer (2 )Symbol ('x' )"

The above exception was the direct cause of the following exception:

SyntaxError                               Traceback (most recent call last)
c:\users\thomasaar\documents\github\sympy\sympy\core\sympify.py in sympify(a, locals, convert_xor, strict, rational, evaluate)
    478         a = a.replace('\n', '')
--> 479         expr = parse_expr(a, local_dict=locals, transformations=transformations, evaluate=evaluate)
    480     except (TokenError, SyntaxError) as exc:

c:\users\thomasaar\documents\github\sympy\sympy\parsing\sympy_parser.py in parse_expr(s, local_dict, transformations, global_dict, evaluate)
   1016     except Exception as e:
-> 1017         raise e from ValueError(f"Error from parse_expr with transformed code: {code!r}")
   1018 

c:\users\thomasaar\documents\github\sympy\sympy\parsing\sympy_parser.py in parse_expr(s, local_dict, transformations, global_dict, evaluate)
   1014     try:
-> 1015         return eval_expr(code, local_dict, global_dict)
   1016     except Exception as e:

c:\users\thomasaar\documents\github\sympy\sympy\parsing\sympy_parser.py in eval_expr(code, local_dict, global_dict)
    908     """
--> 909     expr = eval(
    910         code, global_dict, local_dict)  # take local objects in preference

SyntaxError: invalid syntax (<string>, line 1)

During handling of the above exception, another exception occurred:

SympifyError                              Traceback (most recent call last)
<ipython-input-37-d8899059adbf> in <module>
      1 import sympy as sp
----> 2 sp.sympify("2x")

c:\users\thomasaar\documents\github\sympy\sympy\core\sympify.py in sympify(a, locals, convert_xor, strict, rational, evaluate)
    479         expr = parse_expr(a, local_dict=locals, transformations=transformations, evaluate=evaluate)
    480     except (TokenError, SyntaxError) as exc:
--> 481         raise SympifyError('could not parse %r' % a, exc)
    482 
    483     return expr

SympifyError: Sympify of expression 'could not parse '2x'' failed, because of exception being raised:
SyntaxError: invalid syntax (<string>, line 1)
```

**Comment by sidhu1012** [comment]
It's a known issue  [parsing ideas](https://github.com/sympy/sympy/wiki/GSoC-Ideas#parsing) and needs to be solved.

Till then please use `sympify(2*x + 1)`.

**Comment by thomasaarholt** [comment]
From your link: "The parsing module also supports a Python parser, with special extensions to support things like implicit multiplication (2a -> 2*a) and implicit function application (sin x -> sin(x)), which uses the Python tokenize module."

Do you know what these "special extensions" are?

**Comment by asmeurer** [comment]
To parse non-Python syntax, use `parse_expr`. `sympify` only parses Python syntax (with some exceptions, which may be removed in the future, see https://github.com/sympy/sympy/issues/20625).

```py
>>> from sympy.parsing.sympy_parser import standard_transformations, implicit_multiplication_application
>>> transformations = (standard_transformations + (implicit_multiplication_application,))
>>> parse_expr("2x + 1", transformations=transformations)
2*x + 1
```

Personally I think there should be a way to access this without as much typing, but we can open a separate issue for that.

**Comment by asmeurer** [comment]
> Personally I think there should be a way to access this without as much typing, but we can open a separate issue for that.

https://github.com/sympy/sympy/issues/21226

**Comment by asmeurer** [comment]
Perhaps a relevant thing to be done for this issue would be to mention parse_expr in the sympify docstring. Right now it isn't mentioned at all.

**Comment by Jatin2020-24** [comment]
@asmeurer I have documented parse_expr() in sympify() docstring. Please review [PR](https://github.com/sympy/sympy/pull/21230) based on it.

**Comment by Sharath-a26** [comment]
U can make use of symbol() in Sympy module .

**Comment by srishti387** [comment]
Hi, I want to work on this.

**Comment by thomasaarholt** [comment]
Hi @srishti387. If you would like to improve the docstring, please take a look at and finish the PR that @Jatin2020-24 started (now closed, not merged) in #21230. That would close this issue. 

If you would like to improve the underlying problem, read and comment on #20625 and/or #21226. :)

**Comment by cjaitej** [comment]
Hello, I would like to work on this.

**Comment by thomasaarholt** [comment]
Hi @cjaitej! I suggest you go ahead reading the closed PR and issues I linked to above, and try making a new PR :)

**Comment by cjaitej** [comment]
@thomasaarholt Could pls check my PR. and merge it? :)

**Comment by cjaitej** [comment]
.

**Comment by faisalmujawar148** [comment]
Is this issue still open? if so, I would like to work on this.

**Comment by jofish920** [comment]
There is an example of `parse_expression` in the current version of the `sympify` :

    To parse non-Python syntax, use ``parse_expr`` from ``sympy.parsing.sympy_parser``.

    >>> from sympy.parsing.sympy_parser import parse_expr
    >>> parse_expr("2x+1", transformations="all")
    2*x + 1

    For more details about ``transformations``: see :func:`~sympy.parsing.sympy_parser.parse_expr`

This seems to satisfy [thomasaarholt's comment](#issuecomment-922951168), with
an apparently broken "See Also" reference replaced by a link following the example?

I have the feeling that either I'm missing something here, or this is an issue that has
just accidentally missed being closed.
