### ISSUE TITLE
Problem in latex printing

### ISSUE THREAD

**Issue by Jatin2020-24** [sympy/sympy#21204]
```python
a = "6-(-8)"
expr = sympify(a, evaluate=False)
print(latex(expr))
```
output 6 - - 8
Should be 6 - (-8)

Is this expected behaviour?

**Comment by Jatin2020-24** [comment]
@moorepants please suggest how to start solving this issue.

**Comment by moorepants** [comment]
Write a unit test in the printing latex module that defines the expected behavior.
