### ISSUE TITLE
assign_to for latex

### ISSUE THREAD

**Issue by priyanshuone6** [sympy/sympy#21218]
Is there any way in SymPy's latex printing to assign latex symbols to another latex symbol like `latex(cos(x), assign_to='y')`, so it should give back `y = cos(x)` in latex.
SymPy already has this `assign_to` feature in [C code printers](https://docs.sympy.org/latest/modules/printing.html#module-sympy.printing.c), [Rcode printers](https://docs.sympy.org/latest/modules/printing.html#module-sympy.printing.rcode), Fortran, JavaScript, Julia etc. but I can not see that for latex.

**Comment by oscarbenjamin** [comment]
You can use an equation like this:
```
In [15]: latex(Eq(y, cos(x)))
Out[15]: 'y = \\cos{\\left(x \\right)}'
```
The latex printer is not a code printer like the others so it doesn't need an `assign_to`.
