### ISSUE TITLE
Using SymPy For Website

### ISSUE THREAD

**Issue by Ephraim-Bryski** [sympy/sympy#21224]
I'm interested in using a CAS for a website. While there are JavaScript CAS, SymPy has generally been recommended to me. Would it be possible to use SymPy and pyjs in combination for a website? Is this often done, and are there any issues associated with it?

**Comment by oscarbenjamin** [comment]
This seems like a more suitable question for the mailing list.

**Comment by asmeurer** [comment]
I don't know if this has been tried before. I would expect something like this would not be easy, but please report back if you have any success with it.

**Comment by asmeurer** [comment]
> This seems like a more suitable question for the mailing list.

We can convert issues like this into discussions.
