### ISSUE TITLE
Make parse_expr with transformations easier to type

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#21226]
Right now to parse an expression with non-standard transformations like implicit multiplication, you have to do

```py
>>> from sympy.parsing.sympy_parser import standard_transformations, implicit_multiplication_application
>>> transformations = (standard_transformations + (implicit_multiplication_application,))
>>> parse_expr("2x + 1", transformations=transformations)
2*x + 1
```

This is too much typing. We should add some kind of shortcut, like `transformations='all'`, to do this common case.

**Comment by ebab** [comment]
I would like to implement this in order to practice the workflow.

**Comment by NtemKenyor** [comment]
Now you can just do this:

x = parse_expr("2x + 1", transformations="all")
print(x)

@ebab, you can still improve the answer.

**Comment by ebab** [comment]
@NtemKenyor I do not think that it is enough to check if a string was passed or not. Hence I decided to make my own pull request which specifically checks for `all` and has added documentation.

**Comment by NtemKenyor** [comment]
I agree. I thought about it but I thought it would make people free as d
can pass any string and it still works...

Perhaps your idea is better🥺...

**Comment by smichr** [comment]
What about assigning an int to each transformation that corresponds to a power of 2 so `transformation=3` would be the 0th and 1th element in the logical list of transformations?

**Comment by NtemKenyor** [comment]
I totally agree👍 and it's a great approach.
I did not think this way before now🤯🤯🤯

**Comment by smichr** [comment]
> I did not think this way before now

Perhaps something like the following could be added to iterables and then used:
```python
def int_select(i, L):
    """select items from L based on which bits are 1 in the binary representation of i. e.g.
    i = 1 selects item 0 from L, i = -1 selects all items, i = 0 selects none. Any other i must
    not be larger than 2**n - 1 where n is the number of elements in L

    Examples
    ========

    >>> from sympy.utilities.iterables import ibin
    >>> ibin(13)[::-1]
    [1, 0, 1, 1]
    >>> int_select(13, range(4))
    [0, 2, 3]
    """
    if i == 0:
        return []
    if i == -1:
        return L[:]
    if i < 0 or i >= 2**len(L):
        raise ValueError
    return [L[j] for j, b in enumerate(ibin(i)[::-1]) if b]
```

**Comment by smichr** [comment]
Does anyone have preferences for any or all of these:
```python
def parse_expr(..., xforms=None):
    """
    ...
    xforms : int or iterable, options
        When provided, selects the transformations to use by either selecting
        them according to the position of 1s in the binary representation of
        i or by index provided in the iterable, or as the integers given in a
        comma/dash separated string.

        i    transform
        --  --------------------
        0   lambda_notation,
        1   auto_symbol,
        2   repeated_decimals,
        3   auto_number,
        4   rationalize,
        5   factorial_notation,
        6   implicit_multiplication,
        7   implicit_application,
        8   implicit_multiplication_application,
        9   convert_equals_signs,
        10  function_exponentiation,
        11  convert_xor,

    Examples
    ========

    >>> from sympy.parsing.sympy_parser import parse_expr
    >>> parse_expr("1/2")
    1/2
    >>> type(_)
    <class 'sympy.core.numbers.Half'>
    >>> from sympy.parsing.sympy_parser import standard_transformations,\\
    ... implicit_multiplication_application
    >>> transformations = (standard_transformations +
    ...     (implicit_multiplication_application,))
    >>> parse_expr("2x", transformations=transformations)
    2*x
    >>> parse_expr("2x", xforms=31+2**8)
    2*x
    >>> parse_expr("2x", xforms=(1,2,3,4,5,8))
    2*x
    >>> parse_expr("2x", xforms='1-5, 8')
    2*x
```

**Comment by oscarbenjamin** [comment]
I would at use strings or named constants or something rather than integer codes.

**Comment by smichr** [comment]
> I would at use strings or named constants

What strings would be nice to type? First letters from each of the hyphenated words? `ima -> implicit_multiplication_application`, `st -> standard_transformations`, `st, ima -> standard_transformations + (implicit_multiplication_application,)`. If I ever used these I would nearly always have to look up the names to make sure I get the single or plural form right (e.g. `convert_equals_signs` has double plural) and I would prefer to just type their index number as in the `1-5, 8` case.

Indirect addressing by binary digit is not my preference anymore.

**Comment by oscarbenjamin** [comment]
I think anyone would need to consult the docs to figure out how to write this code. With integer codes that also applies to anyone who has to *read* the code afterwards.

Something like:
```
parse_expr(string, implicit_multiplication=True)
```
is a big improvement over the code shown in the OP.

**Comment by smichr** [comment]
> s a big improvement over the code shown in the OP.

Yes, but how would you modify the signature to allow you to specify the order? At least one transformation indicates that it should be run after another. 

In light of your "read the code" concern, I'm not sure that even allowing "all" as a keyword makes much sense. If more transformations are added then the meaning of "all" changes with time; and it never tells what is actually being done.

If people don't like typing a lot they can add their own shortcuts. At least adding an list of all transforms in the file would be a start toward making things easier, e.g.
```
xform = (
lambda_notation, 
auto_symbol, 
repeated_decimals, 
auto_number, 
rationalize, 
factorial_notation, 
implicit_multiplication, 
implicit_application, 
implicit_multiplication_application, 
convert_equals_signs,
function_exponentiation, 
convert_xor, 
}
```
Then one can use it as they wish:
```python
from sympy.parsing.sympy_parser import xform
parse_expr(expr, transformations=xform[:5]+xform[8])
```

**Comment by oscarbenjamin** [comment]
> Yes, but how would you modify the signature to allow you to specify the order?

I think if someone wants to do that then they can use the current way.

> At least one transformation indicates that it should be run after another.

I expect that most users don't want to have to think about the order and would much rather that we did that for them. We can just define an order and then include or not include the transformations based on the keyword arguments.
