### ISSUE TITLE
Incorrect assumption for is_hermitian

### ISSUE THREAD

**Issue by JSS95** [sympy/sympy#21228]
An object being antihermitian implies it being not hermitian in new assumption system. (and vice versa)

```python
>>> ask(Q.hermitian(x), Q.antihermitian(x))
False
```

But in old assumptions system, it does not.

```python
>>> x = Symbol('x', antihermitian=True)
>>> print(x.is_hermitian)
None
```

Is this an error of core/assumptions module?

**Comment by oscarbenjamin** [comment]
A matrix or operator can be neither hermitian nor antihermitian so that's a bug in the new assumptions.

I don't think that hermitian/antihermitian should be part of the old assumptions.

**Comment by JSS95** [comment]
It is true that an operator being not hermitian does not mean that it is antihermitian.   But doesn't an operator ***being hermitian*** means that it is ***not antihermitian***?

**Comment by ebab** [comment]
The zero operator is an operator which is hermitian and antihermitian, and it is the only such operator (unless the characteristic of the ground field is 2).
Hence this is an error and `None` would be the correct output. Maybe there should be a `nonzero` assumption for operators.
It would also make sense to introduce `positive` and `negative` assumptions for operators etc.

**Comment by JSS95** [comment]
Thanks. Didn't notice that!
