### ISSUE TITLE
Nested logarithms add unnecessary order term to series expansions

### ISSUE THREAD

**Issue by 0sidharth** [sympy/sympy#21227]
What works - 
```py
In [1]: f = log(x)

In [2]: f.nseries(x, 0, logx=y)
Out[2]: y

In [3]: f.nseries(x, 0, logx=-x)
Out[3]: -x

```
What doesn't work - 
```py
In [4]: f = log(-log(x))

In [5]: f.nseries(x, 0, logx=y)
Out[5]: 
           ⎛ 6⎞
log(-y) + O⎝x ⎠

In [6]: f.nseries(x, 0, logx=-x)
Out[6]: 
      ⎛ 6⎞
-x + O⎝x ⎠

In [7]: f = log(log(x))

In [8]: f.nseries(x, 0, logx=y)
Out[8]: 
          ⎛ 6⎞
log(y) + O⎝x ⎠

In [9]: f.nseries(x, 0, logx=-x)
Out[9]: 
           ⎛ 6⎞
ⅈ⋅π - x + O⎝x ⎠

In [10]: f.nseries(x, 0, logx=x)
Out[10]: 
     ⎛ 6⎞
x + O⎝x ⎠

```
From the documentation of `nseries` - The optional ``logx`` parameter can be used to replace any log(x) in the returned series with a symbolic value to avoid evaluating log(x) at 0. A symbol to use in place of log(x) should be provided.

I would expect no Order term to be added in any of the expansions shown above.

**Comment by 0sidharth** [comment]
Another example - 
```py
In [4]: a = 2*sqrt(x)*log(sqrt(x))/pi + sqrt(x)*(1 - 2*EulerGamma)/pi

In [5]: a.series(x)
Out[5]: 
   ⎛log(x)   2⋅γ   1⎞    ⎛ 6⎞
√x⋅⎜────── - ─── + ─⎟ + O⎝x ⎠
   ⎝  π       π    π⎠        

```

**Comment by anutosh491** [comment]
Yeah the order term seem a bit unnecessary and addressing this isn't too tough . I'm worried about tests in `gruntz.py` .I think there are a good number of tests which depend on this result which as follows .

```
>>> log(log(1/x)).nseries(x, n = 1, logx=-y)
log(y) + O(x)
``` 
After fixing this locally , I realized all these tests would end up failing so we might have to think what is a possible approach here .
