### ISSUE TITLE
sympify("1+Q") fails

### ISSUE THREAD

**Issue by zachetienne** [sympy/sympy#21233]
```
import sympy as sp
print(sp.sympify("Q+1"))
```
fails with
```
TypeError: unsupported operand type(s) for +: 'AssumptionKeys' and 'One'
```
It seems replacing `Q` with `N`, `O`, or `S` yields the same issue. Other uppercase letters and all lowercase letters work fine.

**Comment by zachetienne** [comment]
By the way, this bug did not exist a week ago. I'm using sympy-dev.

**Comment by zachetienne** [comment]
Turns out that Q, N, O, and S are reserved keywords, and the latest SymPy-dev has become stricter at enforcing this. 

Replacing `sp.sympify("Q+1")` with 
```
import sympy as sp
custom_global_dict = {}
exec('from sympy import *', custom_global_dict)
del custom_global_dict['Q']
custom_parse_expr = lambda expr: sp.parse_expr(expr, global_dict=custom_global_dict)
custom_parse("Q+1")
```
is a valid workaround. I just hope that more keywords do not become reserved, which would break other notebooks.

**Comment by oscarbenjamin** [comment]
I think that if this worked before and will now break people's notebooks then it should be considered a regression.

Bisected to 8b23826867677e3442497799339264a4b1009188 @JSS95

**Comment by oscarbenjamin** [comment]
I forgot about this one before releasing SymPy 1.8. I'm still not sure I understand what change caused this.

@JSS95 do you know why this changed?

**Comment by oscarbenjamin** [comment]
See also the discussion in #21291

**Comment by JSS95** [comment]
Yes. `Q` is now a reserved keyword which returns `AssumptionKeys` such as `Q.even`, `Q.positive`, etc. In fact, SymPy documentation has explicitly warned (https://docs.sympy.org/latest/gotchas.html#symbols) not to use `Q` for symbol name [since 2010](https://github.com/sympy/sympy/commit/72d7ade8dd107474054c2f02c37a7684fbd9a98d).

**Comment by JSS95** [comment]
Maybe parser can be improved so that `'Q.even'`, `'S.One'`, `'N(...)'`, `'O(...)'` returns desired classes but `'Q'`, `'S'`, etc (without period or parantheses) returns a symbol.
