### ISSUE TITLE
Can't get joule/m^3 to simplify into pascal

### ISSUE THREAD

**Issue by dyc3** [sympy/sympy#21234]
Sample:
```python
from sympy.physics.units import *
print(joule/meter**3)
print(simplify(joule/meter**3))
```
I expected one of these to give me pascal as the unit, but instead I get `joule/meter**3` in both cases.

If I try `(joule/meter**3).convert_to(pascal)` instead, I get `AttributeError: 'Mul' object has no attribute 'convert_to'`. However, `convert_to(joule/meter**3, pascal)` succeeds.

I also tried `sympy.physics.units.util.quantity_simplify(joule/meter**3)`, but that also gives me `joule/meter**3`

**Comment by golmdav** [comment]
I'd like to work on this issue.

**Comment by arjundashrath** [comment]
@dyc3 I looked over this and tested some parts of it, from what I understood, is that quantity_simplify() only works when the parameters are of the same unit, in the code, there is an example:

>>> quantity_simplify(kilo*foot*inch)
    250*foot**2/3

This works because foot and inch are both units of length, unlike your expression.
Let me know if I have erred somewhere!
I'm looking more into the code and will let you know if I find something :)

**Comment by dyc3** [comment]
For `quantity_simplify`, the docs state:

> Return an equivalent expression in which prefixes are replaced
    with numerical values and **all units of a given dimension are the
    unified** in a canonical manner.

So technically, this is expected behavior. However, I think that `quantity_simplify` should be expanded to cover cases like this, where the dimensions of the unit in the expression can be simplified into a different unit. These types of unit simplifications are not necessarily intuitive to end users, so being able to have sympy cover it would help.

For example:

- `joule/meter**3` -> `pascal`
- `ampere * ohm` -> `volt`
- `farad * ohm` -> `second`
- `joule / second` -> `watt`


It also might be nice to have this extra feature gated behind a flag argument that defaults to true.

**Comment by dyc3** [comment]
Opened a PR: 23218
