### ISSUE TITLE
Duplicate methods in `Points` documentation

### ISSUE THREAD

**Issue by angadsinghsandhu** [sympy/sympy#21246]
At the webpage for the documentation for the _Point_ class in `sympy.geometry.point` [(Visit Page)](https://docs.sympy.org/latest/modules/geometry/points.html). There seems to be a repetition of the same method `evalf`. 

Another method named `n` seems seems to be given a little below where evalf is mention. `n` seems to have the same description, example and parameters. The _Point_ class does not seem to have any fore-mentioned `n` method.

Even the [source] link to the code for both `evalf` and `n` seems to redirect to the same code : [link](https://github.com/sympy/sympy/blob/9e8f62e059d83178c1d8a1e19acac5473bdbf1c1/sympy/geometry/point.py#L449-L478)

**Comment by arjundashrath** [comment]
**var.n()** also works like **var.evalf()** it seems, I have submitted **PR#49** in the docs repo correcting the example and replacing it with var.n()

**Comment by angadsinghsandhu** [comment]
Could you please send the GitHub permalink where `.n()` function is defined? 

also,
Do we even need `var.n()` to begin with. Isn't it redundant code?

**Comment by oscarbenjamin** [comment]
> Could you please send the GitHub permalink where `.n()` function is defined?

https://github.com/sympy/sympy/blob/9e8f62e059d83178c1d8a1e19acac5473bdbf1c1/sympy/geometry/point.py#L855

> Do we even need `var.n()` to begin with. Isn't it redundant code?

Yes, it's redundant but it's been there a long time and it would break backwards compatibility to remove it.

Note that it's not just the `Point` class that has both `n` and `evalf` methods. They are defined for all of `Expr`.
