### ISSUE TITLE
[Question]What's the difference between modules "vector" and "physics.vector" ?

### ISSUE THREAD

**Issue by weipeng1999** [sympy/sympy#21261]
I just want to use sympy to help me learn the equations in atmosphere science, which are mainly the fluid mechanics equations.
After reading the documention, I was confused. There are two modules in sympy have the ability to deal with 3d physical quantities, so what is the difference bet between them, and what the module shall I used to achieve my goal?

**Comment by sidhu1012** [comment]
`physics.vector` is meant to be used within the physics module like in mechanics whereas `sympy.vector` can be used in all other cases like mathematical vectors and all.

**Comment by weipeng1999** [comment]
> `physics.vector`意味着可以像在力学中那样在物理模块中`sympy.vector`使用，而可以在所有其他情况下使用，例如数学矢量和所有。

Thank you.
But I still confused with the reason why we need the special vector system for physics, while the variables of physics vector system seems have no relationships with the normal ones and no methods to convert to the normal ones?
For example, the ReferenceFrame and CoordsSym3D seem play the same role in their systems, but why they cannot convert to each other? That is a little weird.

**Comment by asmeurer** [comment]
I think they are intended to be merged eventually. @moorepants or @Upabjojr would know more.

**Comment by weipeng1999** [comment]
> 我认为它们最终将被合并。@moorepants或@Upabjojr会了解更多。
If they are merged, the new system would be more intelligibility and powerful! I like that.

**Comment by moorepants** [comment]
physics.vector has a set of mutable types that are specifically designed for use in physics.mechanics. sympy.vector was created to make a more general immutable type for vector analysis. The idea was that physics.mechanics could use sympy.vector eventually, but it's never been taken further. I, personally, haven't seen a clear path forward on that front. I've tried to come up with an immutable vector design that would work well for physics.mechanics but have never landed on a design that would work. I don't have any current intention of removing or changing physics.vector. It's helpful to have classes that do only what they need to do for the purpose of mechanics. sympy.vector does too much and doesn't do it efficiently.

**Comment by moorepants** [comment]
>  But I still confused with the reason why we need the special vector system for physics, while the variables of physics vector system seems have no relationships with the normal ones and no methods to convert to the normal ones?

physics.vector was created first, specifically for physics.mechanics use. sympy.vector came later with the goal of making a general purpose vector class.

>  For example, the ReferenceFrame and CoordsSym3D seem play the same role in their systems, but why they cannot convert to each other? That is a little weird.

It's not weird, it's simply that no one has spent the time to make any direct connections. You are welcome to make contributions for that.

**Comment by moorepants** [comment]
> I just want to use sympy to help me learn the equations in atmosphere science, which are mainly the fluid mechanics equations.

If you are doing 3D fluids then you'll need to use sympy.vector, as sympy.physics.vector provides vectors that are only a function of a single variable, where as you need time and space.

**Comment by weipeng1999** [comment]
> > I just want to use sympy to help me learn the equations in atmosphere science, which are mainly the fluid mechanics equations.
> 
> If you are doing 3D fluids then you'll need to use sympy.vector, as sympy.physics.vector provides vectors that are only a function of a single variable, where as you need time and space.

It may be a misunderstanding but do you mean the physics.vector only work for time variations while the vector can work for both time variation and space distribution🤔

**Comment by moorepants** [comment]
> It may be a misunderstanding but do you mean the physics.vector only work for time variations while the vector can work for both time variation and space distribution

Yes.

**Comment by faze-geek** [comment]
I believe answers to the questions are justified . Making a direct connection between `sympy.physics.vector` and `sympy.vector`
can be a task for the future but currently this could be closed !
