### ISSUE TITLE
Solutions of cubic equation

### ISSUE THREAD

**Issue by proy87** [sympy/sympy#21263]
`roots(x**3+3*x**2+3*x+y*z*t+1,x)` gives the roots involving absolute values.
Wolframalpha gives other roots: https://www.wolframalpha.com/input/?i=x%5E3%2B3x%5E2%2B3x%2Babc%2B1%3D0%2C+solve+for+x

**Comment by oscarbenjamin** [comment]
Are the roots actually different or are they different but equivalent expressions?

**Comment by oscarbenjamin** [comment]
Looks like Wolfram Alpha uses a "complete the cube" formula i.e.:
```
x**3 + 3*x**2 + 3*x + 1 = - y*z*t
(x + 1)**3 = -y*z*t
```
The result from SymPy comes from the general cubic formula which often gives complicated representations.

**Comment by oscarbenjamin** [comment]
I guess that the strategy for identifying this would be to take the coefficient say `a` of `x**2` i.e.:
```
x**3 + a*x**2 + b*x + c
```
Then you can substitute `x -> x - a/3` i.e.:
```
In [24]: x, a, b, c = symbols('x, a, b, c')

In [25]: p = x**3 + a*x**2 + b*x + c

In [26]: p
Out[26]: 
   2              3
a⋅x  + b⋅x + c + x 

In [27]: p.subs(x, x - a/3)
Out[27]: 
           2                              3
  ⎛  a    ⎞      ⎛  a    ⎞       ⎛  a    ⎞ 
a⋅⎜- ─ + x⎟  + b⋅⎜- ─ + x⎟ + c + ⎜- ─ + x⎟ 
  ⎝  3    ⎠      ⎝  3    ⎠       ⎝  3    ⎠ 

In [28]: p.subs(x, x - a/3).expand()
Out[28]: 
   3    2                       
2⋅a    a ⋅x   a⋅b              3
──── - ──── - ─── + b⋅x + c + x 
 27     3      3  
```
That gives the depressed cubic which may or may not have a linear term. In your example:
```
In [29]: p = x**3+3*x**2+3*x+y*z*t+1

In [30]: p
Out[30]: 
         3      2          
t⋅y⋅z + x  + 3⋅x  + 3⋅x + 1

In [31]: p.subs(x, x-1).expand()
Out[31]: 
         3
t⋅y⋅z + x 
```

**Comment by proy87** [comment]
@oscarbenjamin , I don't think that the roots are equaivalent.

**Comment by smichr** [comment]
The solutions, when susbtituted into the orginal equation, all simplify to `x*y*t/2 - sqrt(x**2*y**2*t**2)/2` which is only zero if any value is 0 or all are positive.
