### ISSUE TITLE
Matrix Logarithm

### ISSUE THREAD

**Issue by mammalwong** [sympy/sympy#21272]
when applying sympy.ln/log on a matrix M, the result is a unevaluated expression of log(M), since sympy supports real valued matrix power and matrix exponential already, can we have matrix evaluated matrix logarithm that may be base on jordan form?

**Comment by mammalwong** [comment]
I actually found matrices has its own .log() method, but sympy.ln/log is not calling this matrix method automatically, not sure if it is by design?

**Comment by oscarbenjamin** [comment]
The design is a bit of a mess. I don't think `exp(matrix)` should work. There should be a separate `MatrixExponential` in matrix expressions.

**Comment by mammalwong** [comment]
In user's point of view I think both sympy.exp/log should works with matrice, I spent a while to finally understand matrice has its own .log member method, while both sympy.exp and ** operator works with matrice

**Comment by oscarbenjamin** [comment]
It would be better to choose what is the right interface and then document it properly rather than making things like `exp` and `log` work implicitly I think. We also need the ordinary `exp` function not to wrap a matrix because it doesn't work properly e.g. with `MatrixSymbol` so there needs to be a separate `MatrixExp` function anyway.

**Comment by mammalwong** [comment]
Is it possible to let sympy.exp/log return matrix expression when the input is matrix and return scalar expression when the input is scalar?

**Comment by oscarbenjamin** [comment]
It's possible but it would be better not to I think. A matrix exponential is a very different thing from the exponential of a complex number so it should be a separate function.

**Comment by mammalwong** [comment]
I think they are actually the same, both matrix and complex/real number exponential are base on the same limit, limit n -> oo on (1+ x/n)**n, it is just the limit of computation making we have to implement matrix exp/log with different techniques

**Comment by oscarbenjamin** [comment]
They are very much not the same. They do not even have the same rules like `exp(a + b) = exp(a)*exp(b)` so it will is problematic to conflate them in SymPy.

**Comment by mammalwong** [comment]
I get what you mean, I agree they are not the same now :)

**Comment by oscarbenjamin** [comment]
I'm going to close this because the logarithm is implemented:
```python
In [4]: M = Matrix([[1, 2], [3, 4]])

In [5]: simplify(M.exp())
Out[5]: 
⎡                                       5   √33                                     5   √33⎤
⎢                                       ─ - ───                                     ─ - ───⎥
⎢⎛      √33                       √33⎞  2    2     ⎛       √33                √33⎞  2    2 ⎥
⎢⎝- 41⋅ℯ    - 14 + 2⋅√33 + 7⋅√33⋅ℯ   ⎠⋅ℯ         2⋅⎝- √33⋅ℯ    - 3 + √33 + 3⋅ℯ   ⎠⋅ℯ       ⎥
⎢──────────────────────────────────────────────  ──────────────────────────────────────────⎥
⎢                 -55 + 9⋅√33                                  3⋅(-11 + √33)               ⎥
⎢                                                                                          ⎥
⎢                                     5   √33                                5   √33       ⎥
⎢                                     ─ - ───                                ─ - ───       ⎥
⎢    ⎛       √33                √33⎞  2    2            ⎛              √33⎞  2    2        ⎥
⎢  3⋅⎝- √33⋅ℯ    - 7 + √33 + 7⋅ℯ   ⎠⋅ℯ                  ⎝-√33 + 7 + 4⋅ℯ   ⎠⋅ℯ              ⎥
⎢  ──────────────────────────────────────────           ────────────────────────────       ⎥
⎣                 -33 + 7⋅√33                                     11 - √33                 ⎦

In [6]: M.exp().log()
Out[6]: 
⎡1  2⎤
⎢    ⎥
⎣3  4⎦
```

**Comment by mammalwong** [comment]
Thanks
