### ISSUE TITLE
Quartic roots returns Piecewise

### ISSUE THREAD

**Issue by proy87** [sympy/sympy#21287]
`roots(x**4 - x**2*(3 + 5*I) + 2*x*(-1 + I) - 1 + 3*I, x)` returns 4 `Piecewise` roots.

**Comment by smichr** [comment]
When it is not trivial to simplify the conditions that are used to select the correct root, a Piecewise is used. If you simplify the Piecewise they will evaluate:
```python
>>> p = roots(...)
>>> ks=[i.xreplace({e:e.simplify() for e in i.atoms(Eq)}) for i in p]
>>> for i in ks:print(i.n(3))
-2.08 - 1.39*I
1.96 + 0.799*I
-0.597 - 0.0929*I
0.715 + 0.683*I
```
Those solutions match those given at [wolfram](https://www.wolframalpha.com/input/?i=SOLUTIONS+OF+x**4+-+x**2*%283+%2B+5*I%29+%2B+2*x*%28-1+%2B+I%29+-+1+%2B+3*I)

**Comment by smichr** [comment]
While it would be unwise to try simplify the whole expression, it would be advantageous to simplify the conditions of the Piecewise before assembling the Piecewise in the quartic routine.

**Comment by oscarbenjamin** [comment]
An `expand` on the condition is sufficient:
```python
In [1]: r1, *r = roots(x**4 - x**2*(3 + 5*I) + 2*x*(-1 + I) - 1 + 3*I, x)

In [2]: r1.args[0][1]
Out[2]: 
               2          
     (-3 - 5⋅ⅈ)           
-1 + ─────────── + 3⋅ⅈ = 0
          12              

In [3]: r1.args[0][1].expand()
Out[3]: False
```
