### ISSUE TITLE
How to simplify trig expression

### ISSUE THREAD

**Issue by proy87** [sympy/sympy#21281]
How to simplify `(32*sin(2*x)*cos(2*x)**5 - 32*sin(2*x)*cos(2*x)**3 - 64*sin(2*x)*cos(2*x) + 35*sin(4*x) - sin(12*x))/(8*sin(4*x))` to `0`? Neither `simplify`, nor `trigsimp` works.

**Comment by smichr** [comment]
rewrite in terms of `exp`:
```python
 eq=(32*sin(2*x)*cos(2*x)**5 - 32*sin(2*x)*cos(2*x)**3 - 64*sin(2*x)*cos(2*x) + 35*sin(4*x) - sin(12*x))/(8*sin(4*x))
 eq.rewrite(exp).expand()
0
```
