### ISSUE TITLE
Liouville ODE fails to match

### ISSUE THREAD

**Issue by naveensaigit** [sympy/sympy#21290]
Liouville ODE with multiple terms fails to match.
``` python
In [1]: eq = f(x).diff(x, 2) + f(x)**2*f(x).diff(x)**2 + x**2*f(x).diff(x)

In [2]: eq
Out[2]: 
                              2     2
 2 d           2    ⎛d       ⎞     d
x ⋅──(f(x)) + f (x)⋅⎜──(f(x))⎟  + ───(f(x))
   dx               ⎝dx      ⎠      2
                                  dx


In [3]: dsolve(eq, hint="Liouville")
Out[3]: 
                            -ⅈ⋅π
                            ─────          ⎛      ⅈ⋅π  3    ⎞
                     3 ___    3            ⎜     ℯ   ⋅f (x) ⎟
         ⎛      3⎞   ╲╱ 3 ⋅ℯ     ⋅Γ(1/3)⋅γ  ⎜1/3, ──────────⎟
         ⎜     x ⎟                        ⎝         3     ⎠
C₁ + C₂⋅γ⎜1/3, ──⎟ + ────────────────────────────────────── = 0
         ⎝     3 ⎠                  9⋅Γ(4/3)


In [4]: eq = f(x).diff(x, 2) + (f(x)**2 + n*f(x))*f(x).diff(x)**2 + x**2*f(x).diff(x)

In [5]: eq
Out[5]: 
                                           2   2
 2 d          ⎛         2    ⎞ ⎛d       ⎞   d
x ⋅──(f(x)) + ⎝n⋅f(x) + f (x) ⎠⋅⎜──(f(x))⎟  + ───(f(x))
   dx                           ⎝dx      ⎠    2
                                             dx

In [6]: dsolve(eq, hint="Liouville")
ValueError: ODE x**2*Derivative(f(x), x) + (n*f(x) + f(x)**2)*Derivative(f(x), x)**2 + Derivative(f(x), (x, 2))
does not match hint Liouville
```

Applying this diff
``` ps
diff --git a/sympy/solvers/ode/ode.py b/sympy/solvers/ode/ode.py
index fe2c44ca33..98bad21983 100644
--- a/sympy/solvers/ode/ode.py
+++ b/sympy/solvers/ode/ode.py
@@ -1295,7 +1295,7 @@ def _powers(expr):
         # Differential Equations", pg. 98

         s = d*f(x).diff(x, 2) + e*df**2 + k*df
-        r = reduced_eq.match(s)
+        r = reduced_eq.collect(f(x).diff(x)).match(s)
         if r and r[d] != 0:
             y = Dummy('y')
             g = simplify(r[e]/r[d]).subs(f(x), y)
```

I get -

``` python
In [1]: eq = f(x).diff(x, 2) + (f(x)**2 + n*f(x))*f(x).diff(x)**2 + x**2*f(x).diff(x)

In [2]: dsolve(eq, hint="Liouville")
Out[2]: 
                        f(x)
                        ⌠
                       ⎮     3   2
                       ⎮    y   y ⋅n
         ⎛      3⎞    ⎮    ──  ────
         ⎜     x ⎟    ⎮    3    2
C₁ + C₂⋅γ⎜1/3, ──⎟ +  ⎮   ℯ  ⋅ℯ     dy = 0
         ⎝     3 ⎠    ⌡

In [3]: checkodesol(eq, _)
Out[3]: (True, 0)
```
All tests pass as well.

**Comment by oscarbenjamin** [comment]
This is one of things that should be more fixable in general by refactoring these solvers into classes. We can make sure that these things are done consistently for each solver:
https://github.com/sympy/sympy/blob/ecbb8368b11aa7122aaaf3688594d7dad30ac18e/sympy/solvers/ode/single.py#L263-L265

**Comment by YaserAlOsh** [comment]
Greetings everyone. I'm new in contributing to SymPy, I would like to do this issue as my first.
I have reproduced what @naveensaigit have done on my local environment.
Then I implemented the diff suggested, and it seems to me that it works.

Should I try and implement the idea of @oscarbenjamin for the ode solver? Or is it to be done later by refactoring?

**Comment by oscarbenjamin** [comment]
You could add the diff and also a regression test in `test_single.py`.

Ultimately this should be refactored though and that would also fix this and probably other issues as well. See https://github.com/sympy/sympy/issues/18348 and the linked pull requests.

**Comment by YaserAlOsh** [comment]
Thanks for explaining. I see It seems that issue was a GSoC project idea but is still not completed.
So I was trying to add a regression test for liouville ode
As far as I understood (maybe I'm wrong), I needed to add an equation and its solution in the examples of liouville ode

Line 990:
`def _get_examples_ode_sol_liouville():
+    n = Symbol('n')
+    _y = Dummy('y')
       return {
            'hint': "Liouville",
            'func': f(x),
            'examples':{
..
+    'liouville_08': {
+       'eq': x**2*diff(f(x),x) + (n*f(x) + f(x)**2)*diff(f(x),x)**2 + diff(f(x), (x, 2)),
+        'sol': [Eq(C1 + C2*lowergamma(1/3, x**3/3) + Integral(exp(_y**3/3)*exp(_y**2*n/2), (_y, f(x))), 0)],
 +    }
..
`
I added the n and _y symbol inside the definition, but I'm not sure about the _y symbol? I used  Dummy('y') like the _u symbol in the same file.

The lower_gamma function was missing, so I had to import it
`from sympy.functions import airyai, airybi, besselj, bessely, lowergamma`

Hopefully I did not miss up.

**Comment by oscarbenjamin** [comment]
Looks good to me

**Comment by YaserAlOsh** [comment]
For some reason the test is failing, even though the expected and the actual solutions look matching to me.

![Screenshot 2021-04-12 213409](https://user-images.githubusercontent.com/25433731/114606271-25f42f80-9cac-11eb-98f9-b55cc172093f.png)

**Comment by oscarbenjamin** [comment]
My guess is that it's something to do with the dummy symbol. Maybe `dummy_eq` doesn't work properly with this example.

**Comment by YaserAlOsh** [comment]
I see. Maybe I can use another example for now. or if @naveensaigit can provide one.
dummy_eq seems to be defined somewhere else. It's called 3 times in test_single but not defined there.

**Comment by oscarbenjamin** [comment]
The problem is `NonElementaryIntegral`: https://github.com/sympy/sympy/issues/15433

It prints as `Integral` but compares unequal. The actual solution returned has a `NonElementaryIntegral` in it.
```python
In [1]: from sympy.integrals.risch import NonElementaryIntegral

In [2]: C1, C2 = symbols('C1, C2')

In [3]: _y = Dummy('y')

In [4]: sol = Eq(C1 + C2*lowergamma(S(1)/3, x**3/3) + NonElementaryIntegral(exp(_y**3/3)*exp(_y**2*n/2), (_y, f(x))), 0)

In [5]: eq = f(x).diff(x, 2) + (f(x)**2 + n*f(x))*f(x).diff(x)**2 + x**2*f(x).diff(x)

In [10]: dsolve(eq, hint='Liouville').dummy_eq(sol)
Out[10]: True
```

**Comment by YaserAlOsh** [comment]
This fixes it. It's Interesting to me how an issue from 2018 relates to this issue.
I will be linking a pull request.
