### ISSUE TITLE
Tutorial bug no shape function in sympy

### ISSUE THREAD

**Issue by bobbydurrett** [sympy/sympy#21331]
This page of tutorial:

https://docs.sympy.org/latest/tutorial/matrices.html

has this code:

from sympy import shape

which results in this error:

ImportError: cannot import name 'shape' from 'sympy'

The tutorial seems to refer to a function shape() which is not in SymPy.

**Comment by oscarbenjamin** [comment]
The `shape` function is new in SymPy 1.8 which was released a week ago. Unless you installed/updated in the last week then you won't have that function available.

**Comment by bobbydurrett** [comment]
Thanks. I was using SymPy 1.7.1
