### ISSUE TITLE
Integration of the same expression yields different results

### ISSUE THREAD

**Issue by habitzreuter** [sympy/sympy#21357]
```
In [3]: a = Symbol('a', real = True)

In [4]: m = (a*y + x**2)*(x**(a-1))

In [5]: Integral(m, x).doit()
Out[5]:
⎧   a      2  a      a
⎪a⋅x ⋅y   x ⋅x    2⋅x ⋅y
⎪────── + ───── + ──────  for a ≠ -2
⎪a + 2    a + 2   a + 2
⎨
⎪               y
⎪      log(x) + ──        otherwise
⎪                2
⎩               x

```
Now, distributing the `(a*y + x**2)` terms:
```
In [6]: Integral(m.expand(), x).doit()
Out[6]:

    ⎛⎧   a             ⎞   ⎛⎧ 2  a             ⎞
    ⎜⎪  x              ⎟   ⎜⎪x ⋅x              ⎟
    ⎜⎪  ──    for a ≠ 0⎟   ⎜⎪─────   for a ≠ -2⎟
 a⋅y⋅⎜⎨  a              ⎟ + ⎜⎨a + 2             ⎟
    ⎜⎪                 ⎟   ⎜⎪                  ⎟
    ⎜⎪log(x)  otherwise⎟   ⎜⎪log(x)  otherwise ⎟
    ⎝⎩                 ⎠   ⎝⎩                  ⎠

```
_Originally posted by @habitzreuter in https://github.com/sympy/sympy/pull/21124#discussion_r616263027_

**Comment by oscarbenjamin** [comment]
Looking at this are these not both correct?

If you try substituting different values for `a` do you not get the same result either way? Note that `a=0` makes the first Piecewise term disappear because it's multiplied by `a`.

**Comment by habitzreuter** [comment]
I believe there was some issue when I pasted the code, as I now realized that the result rendered here is not the same as shown in the terminal. In the first solution the last term is `2*(x**a)*y` instead of `2*x*(y**a)`.
For `a=0` the result is different:
```
In [10]: Integral(m, x).doit().subs(a, 0)
Out[10]:
 2
x
── + y
2

In [11]: Integral(m.expand(), x).doit().subs(a, 0)
Out[11]:
 2
x
──
2
```

**Comment by jksuom** [comment]
The two antiderivatives differ only by a constant `y`, which is acceptable.

**Comment by habitzreuter** [comment]
Nice, my mistake. Thanks!

**Comment by oscarbenjamin** [comment]
I guess the problem in #21124 must have been something else then...

**Comment by oscarbenjamin** [comment]
I opened #21360 which discusses some issues to do with Piecewise.simplify that I noticed from this example.

**Comment by oscarbenjamin** [comment]
I'll close this since it seems to be correctly handled.
