### ISSUE TITLE
`radsimp` gives wrong result for `1 / (x + sqrt(x**2))`

### ISSUE THREAD

**Issue by sylee957** [sympy/sympy#21355]
I got into an accidental discovery of this issue while developing #21343
Generally, even if `1 / (x + sqrt(x**2))` can have a nonzero denominator for `x > 0`, the expression is not rationalizable because multiplying `x - sqrt(x**2)` makes the denominator zero. (`x - sqrt(x**2)` should also not be rationalizable.)

I saw that `radsimp(1 / (x + sqrt(x**2)))` gives `zoo*(x + sqrt(x**2))` which should be a wrong result.
I think that it needs a test for intermediate zero or `NaN, zoo`.

**Comment by ShirAvneri** [comment]
Hey, I would like to work on this issue @sylee957
