### ISSUE TITLE
Can't lambdify Heaviside function to numpy 

### ISSUE THREAD

**Issue by petschge** [sympy/sympy#21411]
Minimal test that reproduces the problem I ran into is given by

```python
import sympy
import numpy as np
from sympy import sin, Heaviside, N

x = sympy.symbols("x", real=True)
f = Heaviside(x)
# f = sin(x) # works
print(N(f.subs(x,1)))

pyf = sympy.utilities.lambdify(x, f, 'numpy')
print(pyf(1))
```

which dies with
```
Traceback (most recent call last):
  File "./minimal.py", line 12, in <module>
    print(pyf(1))
  File "<lambdifygenerated-1>", line 2, in _lambdifygenerated
NameError: name 'Heaviside' is not defined
```

using Python 3.7.3, numpy 1.20.2 and sympy 1.8.

This is likely related to either issue #13176 or #18636

**Comment by bjodah** [comment]
There is this PR: #21411
Do you have any comments on that PR @petschge , e.g. what do you think about the idea of having a printer option?
If you have the time and know how, do feel free to fork that PR and modify it to use a printer option.

**Comment by petschge** [comment]
I am not sure I can comment competently. IMHO Heaviside(0) should probably default to 1/2, but if I get an error message that clearly tells me "you need to explicitly set Heaviside(0) for lambdify to work" I would happy set whatever is best for my problem. That would certainly better than the current unclear "name 'Heaviside' is not defined" without instruction for me how to make it work.

**Comment by hanspi42** [comment]
I agree with petschge that an undefined Heaviside(0) should default to 1/2 when lambdifying.

**Comment by bjodah** [comment]
@hanspi42, thank you for letting us know. Yes, different names (and different number of arguments) is the issue here. Translating the name (to uncapitalized version) is easy, it's deciding on a default for the second argument, and its customization point which is "up for debate".

**Comment by hanspi42** [comment]
Just to let you know, pull request https://github.com/sympy/sympy/pull/21452, when accepted, will change `Heaviside(0)` to `1/2`.

**Comment by petschge** [comment]
Does that imply the minimal example above will then magically begin to work?

**Comment by hanspi42** [comment]
> Does that imply the minimal example above will then magically begin to work?

Not yet, but it makes fixing lambdify easier since sympy's Heaviside will not have numpy-incompatible arguments anymore.

**Comment by hanspi42** [comment]
Pull request https://github.com/sympy/sympy/pull/20411 will solve it.

**Comment by hanspi42** [comment]
As I thought, solving this is now very simple, see pull request above :)
