### ISSUE TITLE
Limit gives AccumBounds for unfactored expression

### ISSUE THREAD

**Issue by oscarbenjamin** [sympy/sympy#21415]
The limit below is computed differently when the expression is expanded:
```python
In [79]: expr = (x - 1)*cos(1/(x - 1))

In [80]: expr
Out[80]: 
           ⎛  1  ⎞
(x - 1)⋅cos⎜─────⎟
           ⎝x - 1⎠

In [81]: expr.limit(x, 1)
Out[81]: 0

In [82]: expr.expand()
Out[82]: 
     ⎛  1  ⎞      ⎛  1  ⎞
x⋅cos⎜─────⎟ - cos⎜─────⎟
     ⎝x - 1⎠      ⎝x - 1⎠

In [83]: expr.expand().limit(x, 1)
Out[83]: <-2, 2>
```
Maybe `factor_terms` or `factor` could be used somewhere.

**Comment by oscarbenjamin** [comment]
From SO:
https://stackoverflow.com/questions/67352206/calculate-multivariable-limits-with-sympy/67355466#67355466

**Comment by 0sidharth** [comment]
This was fixed in bd444d3 from #21731, which improved the leading term handling of `cos` and `sin` when the arg is infinite. This could be closed if a regression test is added

**Comment by harkynX** [comment]
Hey! Can I work on this issue?

**Comment by sidhu1012** [comment]
> Hey! Can I work on this issue?

Yes sure, this issue can be closed of you add a regression test for it.
