### ISSUE TITLE
Bug in simplify?

### ISSUE THREAD

**Issue by Matth32** [sympy/sympy#21422]
Hello,

I'm using simplify function in trigonometric function and result seems wrong.
My script is :
```
from sympy import *
init_printing(use_latex=true)

Xi, Om, t, b,  = symbols ('xi omega_n t b')
display("************Equation de base************")
y = 1-cos(sqrt(1-Xi**2)*Om*t)*exp(-Xi*t*Om)+(sin(sqrt(1-Xi**2)*Om*t)*exp(-Xi*t*Om)*(Om-Xi*b))/(sqrt(1-Xi**2)*b)
display(y)

display("************Simplification Equation de base************")
simpeq=simplify(y)
display(simpeq
```
Results are:
![image](https://user-images.githubusercontent.com/83581603/116864072-90432480-ac07-11eb-9b2a-a45cecd40b9c.png)

Twe two functions are not the same because I have a positive exponential in the simplified equation which tends towards infinity when t (time) is infinity.

Any help?
Thanks

**Comment by oscarbenjamin** [comment]
The whole numerator is multiplied by a negative exponential on the far right so the positive exponential cancels with that.

**Comment by Matth32** [comment]
Ahh How I can missed the final parenthesis... thanks a lot

**Comment by oscarbenjamin** [comment]
No problem
