### ISSUE TITLE
`expr_free_symbols` returns non-symbols

### ISSUE THREAD

**Issue by smichr** [sympy/sympy#21444]
```python
>>> (2*exp(x)-3).expr_free_symbols
{x, 2, -3}
>>> [i.is_Symbol for i in _]
[True, False, False]
```

Non-symbols are being returned. Shouldn't the result just be `{x}`?

**Comment by hyadav2k** [comment]
@smichr, this is occurring as there is no check for `j` being a `symbol` or not.
https://github.com/sympy/sympy/blob/34e0476f9be51b4a4015682c95f35076ec342bfa/sympy/core/expr.py#L2440

Maybe this will work.
```py
diff --git a/sympy/core/expr.py b/sympy/core/expr.py
index 1c7ef70b6a..9ddbe818dd 100644
--- a/sympy/core/expr.py
+++ b/sympy/core/expr.py
@@ -2437,7 +2437,7 @@ def expr_free_symbols(self):
         >>> t.free_symbols
         {x, y}
         """
-        return {j for i in self.args for j in i.expr_free_symbols}
+        return {j for i in self.args for j in i.expr_free_symbols if j.is_symbol}

     def could_extract_minus_sign(self):
         """Return True if self is not in a canonical form with respect
```
Output after the diff:
```py
In [1]: (2*exp(x)-3).expr_free_symbols
Out[1]: {x}
```
Thanks.

**Comment by hyadav2k** [comment]
@smichr, If the above `diff` looks viable, can I raise a PR?
Thanks.

**Comment by smichr** [comment]
It looks like the root cause is that `expr_free_symbols` is returning atoms instead of symbols.

**Comment by hyadav2k** [comment]
> Symbol should have the method instead, not AtomicExpr.
>
Sure, I have raised a PR in favor of the changes.
Thanks.
