### ISSUE TITLE
Documentation: shape not working in sympy live

### ISSUE THREAD

**Issue by user-na** [sympy/sympy#21446]
I am not sure if this belongs here, but while using the sympy docs I encountered an issue when using shape in the live  shell:

```
from sympy import shape
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: cannot import name shape

```

**Comment by oscarbenjamin** [comment]
This is because sympy live is still using an old version of sympy:
https://github.com/sympy/sympy-live/issues/175
