### ISSUE TITLE
Numeric computation docs typo

### ISSUE THREAD

**Issue by gkaissis** [sympy/sympy#21456]
https://github.com/sympy/sympy/blob/master/doc/src/modules/numeric-computation.rst

Under "Lambdify":
"GPUs manufacturer" should read "GPU manufacturers" and the section ends abruptly

**Comment by rprkh** [comment]
Can I work on this?

**Comment by sidhu1012** [comment]
> Can I work on this?

Yes you can, you neet to send a PR with the changes.
