### ISSUE TITLE
Banner doesn't load on PyPI page

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#21468]
At https://pypi.org/project/sympy/, the banner from the README doesn't load. I think we would either have to make it an absolute URL, or process the README in setup.py to remove the banner.

**Comment by hackman01** [comment]
I would like to work on this issue
I am new to open source community 
help me with a little guide

I had tried to understand the source code of setup.py
but didn't understood how to process readme in that

**Comment by Prateek93a** [comment]
Hey @asmeurer , I believe removing the banner is better than setting absolute path. Also, I have seen many other repository pages on PyPI that don't have images in their descriptions.
@hackman01 If you are still working on this and need help, you need to add `long_description` field in the `setup` function. Have look at this [article](https://dustingram.com/articles/2018/03/16/markdown-descriptions-on-pypi/) for better understanding. 
You will have to read the README.md file and filter out the line containing banner before setting the string  your read to `long_description`.  If you're not working on this, I would like to raise the PR.

**Comment by hackman01** [comment]
Thanks for the help, I had removed the banner and made possible changes according to my understanding, please review it.
#21484
