### ISSUE TITLE
No real root for cubic equation

### ISSUE THREAD

**Issue by zwang1995** [sympy/sympy#21471]
_For the following case, no real root can be obtained:_

```
import sympy as sp
Z = sp.Symbol('Z')
f = (Z ** 3) - (0.9974913169672125 * Z ** 2) + (0.02026793177290897 * Z) - 5.7170883853351635e-05
print(sp.solve(f))
>> [0.00338165220261848 + 0.e-23*I, 0.0173077034078967 - 0.e-23*I, 0.976801961356697 - 0.e-23*I] 
```
_**No real roots !!!**_

Does anybody have any idea about getting the real root for this case.
Thank you!

**Comment by oscarbenjamin** [comment]
You can get them like:
```python
In [7]: [r.n(4) for r in real_roots(f)]
Out[7]: [0.003382, 0.01731, 0.9768]
```
That's the same as the answers you got. Just the answers from solve have nonsignificant floating point imaginary parts added.

**Comment by smichr** [comment]
If a polynomial equation is given with Floats, `solve` should just use `nroots` which will automatically take care of the spurious imaginary parts.

**Comment by zwang1995** [comment]
@oscarbenjamin @smichr 
Thanks for your suggestions!
