### ISSUE TITLE
Stale link in documentation

### ISSUE THREAD

**Issue by rickhg12hs** [sympy/sympy#21482]
I'm confident that this link is stale given the subject that appears when clicking on it.  I also notice other references to the same website which also are bad.

https://github.com/sympy/sympy/blob/46e00feeef5204d896a2fbec65390bd4145c3902/sympy/solvers/diophantine/diophantine.py#L1926

**Comment by naveensaigit** [comment]
Thanks @rickhg12hs, this should be fixed. If you are looking for the pdf, you can use [Wayback Machine](https://web.archive.org/web/20160323033111/http://www.jpr2718.org/ax2p.pdf)

**Comment by moorepants** [comment]
Yeh, looks like three instances: https://github.com/sympy/sympy/search?q=jpr2718&type=

That URL should be removed.

**Comment by rickhg12hs** [comment]
> That URL should be removed.

Any problem linking to the Wayback Machine?

**Comment by naveensaigit** [comment]
> > That URL should be removed.
> 
> Any problem linking to the Wayback Machine?

I don't think so. Please feel free to make a PR.

**Comment by asmeurer** [comment]
[This paper](https://projecteuclid.org/journals/rmjm/rocky-mountain-journal-of-mathematics/DownloadAcceptedPapers/201123-Robertson.pdf) from last year appears to be about the same thing, although I didn't look closely to verify if that is truly the case. Perhaps we should contact the author and ask.

**Comment by n4i9kita** [comment]
@naveensaigit, is the issue resolved  ? 
If not, can I work on it ?

**Comment by naveensaigit** [comment]
> @naveensaigit, is the issue resolved ?
> If not, can I work on it ?

It is not yet resolved. You can open a PR with the changed links

**Comment by n4i9kita** [comment]
Ok. I have done it. 
It was my first contribution.
It is showing a message "First-time contributors need a maintainer to approve running workflows".

**Comment by rickhg12hs** [comment]
> Ok. I have done it.

There are a few other stale links to www.jpr2718.org that you might want to change too.

**Comment by naveensaigit** [comment]
> It is showing a message "First-time contributors need a maintainer to approve running workflows".

One of the maintainers will approve it after which tests will run

**Comment by n4i9kita** [comment]
ok.
Thanks.

**Comment by n4i9kita** [comment]
@rickhg12hs , I will look into it .
Thanks for informing.

**Comment by n4i9kita** [comment]
I could find only one more stale link -  [http://www.jpr2718.org/pell.pdf](http://www.jpr2718.org/pell.pdf)  - in reference to solving Pell Equation ( written by the same author John P. Robertson)
I have changed it with this one  [here](https://web.archive.org/web/20160323033128/http://www.jpr2718.org/pell.pdf)

**Comment by n4i9kita** [comment]
Should I submit a new pr for the same ?
