### ISSUE TITLE
`expand_trig` for `csch`, `sech`

### ISSUE THREAD

**Issue by sylee957** [sympy/sympy#21495]
Although we have fixed #21365, it should be extended further for `csch, sech`.
The behavior for `csc, sec` was to expand it in denominator with `cos, sin`, so it could be taken as a reference.
 
```python3
>>> from sympy import *

>>> x, y = symbols('x y')
>>> expand_trig(tanh(x + y))
(tanh(x) + tanh(y))/(tanh(x)*tanh(y) + 1)
>>> expand_trig(csch(x + y))
csch(x + y)
>>> expand_trig(sech(x + y))
sech(x + y)
>>> expand_trig(csc(x + y))
1/(sin(x)*cos(y) + sin(y)*cos(x))
>>> expand_trig(sec(x + y))
1/(-sin(x)*sin(y) + cos(x)*cos(y))
```

**Comment by LucyMountain** [comment]
I am working on this issue. I have fixed the problem in the title, but have also realised there is an issue with coth(a+b) as well so I will work that out before sending the pull request.

**Comment by LucyMountain** [comment]
Submitted pull request: https://github.com/sympy/sympy/pull/21567
