### ISSUE TITLE
[GSoC] [Track]Implement Joint classes

### ISSUE THREAD

**Issue by sidhu1012** [sympy/sympy#21519]
The following tasks need to be implemented(#9809)-

- [x] `Joints` abstract class
- [x] `PinJoint` class
- [x] `SlidingJoint` class
- [x] `CylindricalJoint` class
- [x] `PlanarJoint` class

ping @moorepants @Sc0rpi0n101

**Comment by moorepants** [comment]
As before, please try to build off of the old prs so those commits are included in sympy.

**Comment by sidhu1012** [comment]
I'll start a fresh PR but would `co-author` to include others, fresh PR would help in focusing on less code and less mess.

**Comment by sidhu1012** [comment]
@moorepants [Three Link Conical Pendulum](https://pydy.readthedocs.io/en/latest/examples/three-link-conical-pendulum.html) is an example of which type of joint?

**Comment by moorepants** [comment]
I don't know what "co-author" means. Are you building on the prior work or not? I prefer incorporating prior author commits so that they get proper credit.

**Comment by sidhu1012** [comment]
By "co-author" I mean, I'll make a multiple author commit , so that everyone can get their credits .

**Comment by namannimmo10** [comment]
> I'll make a multiple-author commit

I think you should pull down the original PR and edit on a branch that starts from that PR, then it will include commits from the prior author and you. (cherry-pick all the commits)

**Comment by sidhu1012** [comment]
@moorepants  Can you please share a couple of examples for all the four Joint type, something like:
```
PinJoint - examples
SlidingJoint -  examples
CylindricalJoint - examples
PlanarJoint - Examples
```

So that I can differentiate between join types.

Thanks

**Comment by moorepants** [comment]
I shared them all in the meeting. The pydy `examples` and `docs` folders has them.

**Comment by sidhu1012** [comment]
Diagram to be done :- https://github.com/sympy/sympy/pull/21564#issuecomment-865745168

**Comment by TJStienstra** [comment]
@sidhu1012 and @moorepants the joints have been implemented.

**Comment by moorepants** [comment]
Congrats!
