### ISSUE TITLE
sp.integrate("x",x) ==> xx,    while sp.integrate(x,x) ==> x**2/2

### ISSUE THREAD

**Issue by MRYingLEE** [sympy/sympy#21522]
The same happened on both sympy-1.8 and sympy-1.7.1.

To my surprise, SymPy Live Shell( Python console for SymPy 1.5.1 (Python 2.7.12)) works normally. In other words, 
sp.integrate("x",x) ==> x**2/2  while sp.integrate(x,x) ==> x**2/2.

Sorry, I am new to Sympy. Is there something wrong with my environment?

#integrals

**Comment by MRYingLEE** [comment]
I found integrate("x")==> x**2/2, which is normal. So I will use this way to integrate.

**Comment by asmeurer** [comment]
Probably `x` was defined with some assumptions, which makes it different from "x", which gets converted to a symbol without assumptions.

In general, you should avoid passing strings to functions, to avoid this issue. `integrate(x, x)` is the better way to do this. We plan to deprecate and remove passing strings to functions at some point.
