### ISSUE TITLE
sympify() does not obey boolean parameter 'evaluate' if its input is a list

### ISSUE THREAD

**Issue by lassikor** [sympy/sympy#21536]
Hi,
the function sympify (sympy.core.sympify) does not obey the boolean parameter 'evaluate' if the input of the function is a list of string expressions.
Simple test case:
`sympify("x+3*x",evaluate=False)`
->`x+3*x`
`sympify(["x+3*x","2*x+4*x"], evaluate=False)`
->`[4*x, 6*x]`

This should be easily fixed by adding the missing parameter 'evaluate=evaluate' when calling sympify with iterables (and dicts):
https://github.com/sympy/sympy/blob/c0993ea7b111efb35d48697148230b7a84cd5fc9/sympy/core/sympify.py#L435-L448

BR
Lassi Korhonen

**Comment by mostlyaman** [comment]
Hi,
I have verified that adding `evaluate=evaluate` at line 437 and 444 fixes the issue.
However, I am new to open source and cannot confirm if any other changes are required except the two mentioned lines.
The fix seems to work. Here is an example output.
`>>> sympify(["x+3*x","x+2*x"], evaluate=False)`
`[x + 3⋅x, x + 2⋅x]`
May I work on this issue?

**Comment by oscarbenjamin** [comment]
> if any other changes are required

Some tests would also need to be added in `sympy/core/tests/test_sympify.py` but otherwise that sounds good.

**Comment by mostlyaman** [comment]
> Some tests would also need to be added in `sympy/core/tests/test_sympify.py`

I have completed the mentioned changes and have a pull request ready. However, I do not know how to add the tests mentioned. 

While trying the changes, I noticed that evaluate and strict were absent in the lines 437 and 444 while other parameters namely convert_xor and rational were present. Maybe evaluate was skipped. 

strict parameter is still absent in the above mentioned lines but it seems to register nonetheless unlike evaluate which needed to be added.  Here is an example output for strict parameter. I used this strict example from https://docs.sympy.org/latest/modules/core.html 
`>>> sympify(['2*x+3*x+0.5', None], evaluate = False, strict= False)`
`[2⋅x + 3⋅x + 0.5, None]`

`>>> sympify(['2*x+3*x+0.5', None], evaluate = False, strict= True)`

`Traceback (most recent call last):
  ...  /sympy/core/sympify.py", line 433, in sympify
    raise SympifyError(a)
sympy.core.sympify.SympifyError: SympifyError: ['2*x+3*x+0.5', None]
`

**Comment by oscarbenjamin** [comment]
> Should I make the pull request?

Yes, go ahead. If further changes are needed then you can always push more commits after opening the PR.
