### ISSUE TITLE
Possibility of extended algebra system.

### ISSUE THREAD

**Issue by shamEiNew** [sympy/sympy#21535]
This is not an issue but a feature addition/suggestion at a scale.
I think in near future sympy must have a complete algebra system which includes rings and groups. This is a difficult task probably also there exist systems like GAP (written in C). I don't know whether it is possible to somehow use that or it must be made from scratch.

**Comment by oscarbenjamin** [comment]
Can you expand on what exactly this would be? Also there are probably existing open issues about this.

**Comment by oscarbenjamin** [comment]
Without further information this issue is not useful so I'm going to close it.
