### ISSUE TITLE
right and left derivative with sympy

### ISSUE THREAD

**Issue by zfranciolla** [sympy/sympy#21544]
I want to calculate a sharp point, which is the point where right and left derivatives differ, but I cannot find a function that permits calculating the two singularly, Any help? thanks

**Comment by naveensaigit** [comment]
Hi, you can use [`sympy.calculus.singularities.singularities`](https://docs.sympy.org/latest/modules/calculus/index.html#sympy.calculus.singularities.singularities). I'm including the examples from the documentation

``` python
from sympy.calculus.singularities import singularities
from sympy import Symbol, log
>>> x = Symbol('x', real=True)
>>> y = Symbol('y', real=False)
>>> singularities(x**2 + x + 1, x)
EmptySet
>>> singularities(1/(x + 1), x)
FiniteSet(-1)
>>> singularities(1/(y**2 + 1), y)
FiniteSet(I, -I)
>>> singularities(1/(y**3 + 1), y)
FiniteSet(-1, 1/2 - sqrt(3)*I/2, 1/2 + sqrt(3)*I/2)
>>> singularities(log(x), x)
FiniteSet(0)
```

**Comment by asmeurer** [comment]
You can use `limit` on the derivative. For example:

```py
>>> limit(asec(x).diff(x), x, 1, '+')
oo
```

**Comment by oscarbenjamin** [comment]
Closing as fixed because `limit` can be used.
