### ISSUE TITLE
Fix for hanging of sympy, when value is too big

### ISSUE THREAD

**Issue by michalmicpaw** [sympy/sympy#21579]
Hi.

I've found semi solution to upgrade sympy when it hangs aftercomputing very high numbers.

I.E.
```py
latex(expand("10.0**10.0**10.0", evaluate=True))
latex(expand("10.0*10.0**10000", evaluate=True))
```

etc.

I don't want to sew it by my own. I'd like to get this feature in official review of version. Here is my semi solution:

I have two functions:

```py
from mpmath import log10 as _log10
from mpmath import power as _pow

def checkIf_Pow_MaxValReached(b, e):
    b = str(b)
    e = str(e)
    
    if _pow(e, 1) * _log10(b) > 10000:
        raise ValueError("too high pow val")


def checkIf_Mul_MaxValReached(val1, val2):
    val1 = str(val1)
    val2 = str(val2)
    
    if _log10(val1) + _log10(val2) > 10000:
        raise ValueError("to high mul val")


```

These functions are checking if value has more than 10000 digits. They are taking two values. First one checks for **power** operations. Second is **multiply** operation checker. And now, I call one of them in `__mul__` method and other in `_eval_power` method. Like this:

```py
    def __mul__(self, other):
        if isinstance(other, Number) and global_parameters.evaluate:
            rhs, prec = other._as_mpf_op(self._prec)
            checkIf_Mul_MaxValReached(self.num, other._eval_evalf(prec))
            return Float._new(mlib.mpf_mul(self._mpf_, rhs, prec, rnd), prec)
        return Number.__mul__(self, other)
```

```py
    def _eval_power(self, expt):
        """
        expt is symbolic object but not equal to 0, 1

        (-p)**r -> exp(r*log(-p)) -> exp(r*(log(p) + I*Pi)) ->
                  -> p**r*(sin(Pi*r) + cos(Pi*r)*I)
        """
        if self == 0:
            if expt.is_positive:
                return S.Zero
            if expt.is_negative:
                return S.Infinity
        if isinstance(expt, Number):
            if isinstance(expt, Integer):
                prec = self._prec
                checkIf_Pow_MaxValReached(self.num, expt.p)
                return Float._new(
                    mlib.mpf_pow_int(self._mpf_, expt.p, prec, rnd), prec)
            elif isinstance(expt, Rational) and \
                    expt.p == 1 and expt.q % 2 and self.is_negative:
                return Pow(S.NegativeOne, expt, evaluate=False)*(
                    -self)._eval_power(expt)
            expt_copy = expt
            expt, prec = expt._as_mpf_op(self._prec)
            mpfself = self._mpf_
            try:
                checkIf_Pow_MaxValReached(self.num, expt_copy._eval_evalf(prec))
                y = mpf_pow(mpfself, expt, prec, rnd)
                return Float._new(y, prec)
            except mlib.ComplexResult:
                re, im = mlib.mpc_pow(
                    (mpfself, fzero), (expt, fzero), prec, rnd)
                return Float._new(re, prec) + \
                    Float._new(im, prec)*S.ImaginaryUnit
```

When value is going to be too high, it throws exception, before calculating it

These methods are inside **Float class** in **sympy/core/numbers.py**. It will be necessary to apply then to all classes. But one issue with them, is that they don't cover **Imaginary** numbers, so some of functions are not working properly, i.e:

`latex(expand("tan(pi/2 + 0.1**10)", evaluate=True))`
throws an exception.

Will it be possible to add this functionality afrer necessary corrections to official review? There could be **boolean switch** to turn on/off this feature.

Thanks Mike

**Comment by oscarbenjamin** [comment]
A lot more is needed to make this work consistently. Probably just giving an unevaluated Pow etc is better than raising an exception.

**Comment by michalmicpaw** [comment]
Ok. But I need to be done it. Will some do this? I will be using sympy at my website. I have to secure of hanging process.

**Comment by oscarbenjamin** [comment]
Right now the best way to prevent this kind of thing from hanging is to use a time out.

**Comment by michalmicpaw** [comment]
Timeout doesnt stop thread when pythons multiply is processing. Can you do something to avoid sympy hanging when computing formulas?

**Comment by oscarbenjamin** [comment]
We already have open issues for this e.g.: #6835 #20668 so I'm going to close this one. Feel free to open a pull request but we don't need another open issue.
