### ISSUE TITLE
What is_number means?

### ISSUE THREAD

**Issue by proy87** [sympy/sympy#21577]
Why `S.Infinity.is_number` is `True` and `S.NaN.is_number` is `True`, while `sin(S.Infinity)` is False?

**Comment by smichr** [comment]
In the current master, `sin(oo)` gives `AccumBounds(-1, 1)`. Feel free to reopen if there is another issue.

**Comment by proy87** [comment]
Why `S.NaN.is_number` gives `True` and why `S.Infinity.is_number` (as well as `S.ComplexInfinity.is_number`) also gives `True`? I just can't understand what `is_number` means in SymPy.

**Comment by oscarbenjamin** [comment]
Basically `is_number=True` means that it is possible to `evalf()` an expression to get a complex float (or possibly nan/infinity).

The docs are not so clear:
https://docs.sympy.org/latest/modules/core.html#sympy.core.expr.Expr.is_number
https://github.com/sympy/sympy/blob/d17907e248abe9f1b3d8aa98701ba6d48bd948d9/sympy/core/expr.py#L404-L455
