### ISSUE TITLE
Position-velocity in inertial/rotating frame

### ISSUE THREAD

**Issue by shiningsurya** [sympy/sympy#21575]
Hello

i feel this is a silly question but i cannot figure out. i have searched through the docs but to no avail. Please excuse me if this has been answered before. 

i am trying to find the position, velocity of a point defined in a rotating frame from an inertial frame. 

```
import sympy as s_
import sympy.physics.vector as s_vec

omega = s_vec.dynamicsymbols('omega')
I  = s_vec.ReferenceFrame('I')
U = I.orientnew ('U', 'Axis', [0, I.z])
w = omega * I.z
U.set_ang_vel (I, w)
O  = s_vec.Point ('Origin')
P  = O.locatenew('P', 3 * I.x)
P.set_vel (I, 0.)
```
`P.vel(I)` works 
`P.vel(U)` fails

i am totally lost about how to compute the position. i do not see any method i can use to compute. 
it feels like i am missing something fundamental here so hoping you can tell me that. 

Sorry for the trouble.

**Comment by moorepants** [comment]
Velocities of points have never been automatically calculated. You have to do that yourself. Although the latest version of sympy (or maybe the next release) will have this limited ability.

**Comment by shiningsurya** [comment]
Sorry for the trouble. i ended up writing the equations and am numerically integrating it. 
My bad. Thanks!! ^_^
