### ISSUE TITLE
Factor when irrational roots

### ISSUE THREAD

**Issue by proy87** [sympy/sympy#21636]
How to factor `(x**3 - 19*x**2 - 2*sqrt(2)*x**2 + 2*sqrt(11)*x**2 - 38*sqrt(11)*x - 39*sqrt(3)*x - 2*sqrt(22)*x + 2*x + 38*sqrt(2)*x - 38 + 39*sqrt(6) + 38*sqrt(22))`?
`x=sqrt(2)` is an irrational root here.

**Comment by oscarbenjamin** [comment]
You can use `extension=True` to factor over an algebraic number field containing the coefficients:
```python
In [11]: e
Out[11]: 
 3       2         2          2                                                                     
x  - 19⋅x  - 2⋅√2⋅x  + 2⋅√11⋅x  - 38⋅√11⋅x - 39⋅√3⋅x - 2⋅√22⋅x + 2⋅x + 38⋅√2⋅x - 38 + 39⋅√6 + 38⋅√22

In [12]: factor(e, extension=True)
Out[12]: 
         ⎛ 2                                                ⎞
(x - √2)⋅⎝x  + x⋅(-19 - √2 + 2⋅√11) - 38⋅√11 - 39⋅√3 + 19⋅√2⎠
```

**Comment by proy87** [comment]
Thank you.
