### ISSUE TITLE
doit() method *sometimes* ignores floor and ceiling within Sum

### ISSUE THREAD

**Issue by rajkk1** [sympy/sympy#21651]
**Summary of problem**: the `doit()` method will sometimes (depending on the expression) ignore any `floor` or `ceiling` that is located inside a `Sum`.

**Example detailing the bug**

The following code sets up the problem:

```
from sympy import floor, Sum, Symbol
i = Symbol('i')
a = Sum(floor(2*2**(-i)), (i, 1, 2))
b = floor(2*2**(-1)) + floor(2*2**(-2))
```

Note that these two expressions `a` and `b` are the same, just `a` is written with the summation notation and `b` is written out explicitly. They both equal `1`. 

Printing these variables give us the expected results:

![image](https://user-images.githubusercontent.com/10404731/122962576-da35c480-d385-11eb-8927-94dff7f43a0c.png)

However, if we run the `doit()` method on them we see a discrepancy:

![image](https://user-images.githubusercontent.com/10404731/122962993-2bde4f00-d386-11eb-8fc3-cb365bb5790f.png)

where we see that the `floor` function inside the summation has been ignored. The same issue also arises when using the `ceiling` method (i.e. the `doit()` method ignores it when it is in a summation).

However it seems like this problem is not consistent, e.g. if you remove the `2*` from the expression it works fine. More precisely if you run

```
from sympy import floor, Sum, Symbol
i = Symbol('i')
a = Sum(floor(2**(-i)), (i, 1, 2))
b = floor(2**(-1)) + floor(2**(-2))
print(a.doit())
print(b.doit())
```
you get the exptected results (this works for `ceiling` too)

(bug discovered on sympy version 1.8 on python 3.7.3)

**Comment by oscargus** [comment]
The problem arises since
```
k = Symbol('k', positive=True, integer=True)
floor(2*2**(-k))
```
returns `2/2**k` so for some reason the floor is missing there.

(Summation replaces the original variable with a dummy variable with additional assumptions, such as integer, and in this case, positive.)

**Comment by oscargus** [comment]
This doesn't happen for the equivalent `floor(2**(-k+1))`.
