### ISSUE TITLE
Some file's license is MIT

### ISSUE THREAD

**Issue by Huangxiaodui** [sympy/sympy#21663]
The license file "sympy/sympy/parsing/latex/LICENSE.txt" is MIT License.
Whether the license description of the software need to be changed and the MIT license need to be added.

**Comment by oscarbenjamin** [comment]
The MIT license is compatible with BSD and MIT-licensed code can be redistributed under BSD provided the copyright notice is retained. Here the copyright notice is in `sympy/sympy/parsing/latex/LICENSE.txt`. Perhaps it should also be mentioned in the main LICENSE file.
