### ISSUE TITLE
Limit hangs

### ISSUE THREAD

**Issue by proy87** [sympy/sympy#21661]
`limit((x**(x + 1)*(ln(x) + 1) + 1)/x, x, 11)` hangs.

**Comment by 0sidharth** [comment]
The limit computes for me on master - 
```py
In [1]: limit((x**(x + 1)*(ln(x) + 1) + 1)/x, x, 11)
Out[1]: 
3138428376722                       
───────────── + 285311670611⋅log(11)
      11                            

```
What version of sympy are you using?

**Comment by 0sidharth** [comment]
This was fixed in 748294e from #21253

**Comment by oscarbenjamin** [comment]
This can be closed if a test is added.

**Comment by mostlyaman** [comment]
`limit((x**(x + 1)*(ln(x) + 1) + 1)/x, x, 11)`
A time bound test against this expression is required? Should any other expression be included?

**Comment by 0sidharth** [comment]
Just adding this test to `test_limits.py` should be sufficient, similar to how the other tests in that file are
