### ISSUE TITLE
SymPy banner does not display on PyPI

### ISSUE THREAD

**Issue by slel** [sympy/sympy#21669]
The SymPy page on PyPI,

- https://pypi.org/project/sympy/

has the title "SymPy", a row of badges (pypi, build, gitter, DOI, codecov),
and then the SymPy banner which currently is not displaying properly.

Temporary glitch? Easy fix? Tricky content delivery network issue?

**Comment by oscarbenjamin** [comment]
Thanks for reporting this.

I think that this is already fixed by using an absolute URL in the README.md file. It won't show on PyPI until a new release is issued.

The fix was 4a74b6f1952 in #21484 and the original issue was #21468

**Comment by slel** [comment]
Forgot to check closed issues. Sorry for the noise.

**Comment by oscarbenjamin** [comment]
No problem. Thanks for the report!
