### ISSUE TITLE
Permanent of a matrix not implemented atm?

### ISSUE THREAD

**Issue by programizer** [sympy/sympy#21685]
M.per() gives
AttributeError: MutableDenseMatrix has no attribute per.
Even SymPy Live on documentation page:
https://docs.sympy.org/latest/modules/matrices/matrices.html#sympy.matrices.matrices.MatrixDeterminant.per

**Comment by oscarbenjamin** [comment]
SymPy Live runs an older version of SymPy. Latest version gives:
```python
In [1]: M = Matrix([[1, 2], [3, 4]])

In [2]: M
Out[2]: 
⎡1  2⎤
⎢    ⎥
⎣3  4⎦

In [3]: M.per()
Out[3]: 10
```
