### ISSUE TITLE
Create a figure to explain the ``parent_axis``, ``child_axis``, ``parent_pos``, and ``child_pos`` vectors in ``Joint``.

### ISSUE THREAD

**Issue by moorepants** [sympy/sympy#21705]
The ``Joint`` class in mechanics has the ability to arbitrarily align and position the joint. For the non-trivial cases it is a bit difficult to understand. A figure is needed to help the user more clearly understand the relationship of the 4 vectors and the two connected bodies. I sketched this figure as a possible starting point:
![P6220674](https://user-images.githubusercontent.com/276007/122892875-15b09e80-d346-11eb-9317-59a63030e490.JPG)

Ideally, we create an SVG figure that can be modified and stored in the codebase.

@sidhu1012, fyi

**Comment by soma2000-lang** [comment]
@moorepants  Can I work on this isssue?Please assign me this.

**Comment by moorepants** [comment]
Anyone can work on any issue. We don't assign people. Just open a "work in progress/draft" PR and link to this issue, then people will know you are working on it.
