### ISSUE TITLE
`Physics.vector` not respecting leading `-` sign

### ISSUE THREAD

**Issue by sidhu1012** [sympy/sympy#21729]
The Vector class of sympy/physics isn't considering the leading negative sign( all comments [here]https://github.com/sympy/sympy/pull/21674#discussion_r667299559) ).

If we do something like

`-A.x.magnitude()` , it is being treated as `-(A.x.magnitude)`

Another example could be

`-A.x.angle_between(N.x)` is being treated as `-(A.x.angle_between(N.x)`.

Which is leading to wrong result.

But if we do,

```
a = -A.x
a.angle_between(N.x) or N.x_angle_between(-A.x) or (-A.x). angle_between(N.x)
```
 then it works fine.

**Comment by moorepants** [comment]
Good catch on the `magnitude()` that does also give ambiguous behavior.

**Comment by moorepants** [comment]
@asmeurer, is this a limitation we have to deal with with Python? And is how all of SymPy works?

**Comment by sidhu1012** [comment]
> Good catch on the `magnitude()` that does also give ambiguous behavior.

This bahaviour is shown by all Vector functions.

**Comment by moorepants** [comment]
> This bahaviour is shown by all Vector functions.

Yes, but it only matters for some of vector's methods. For example, it doesn't matter for `.dot()`.

**Comment by oscarbenjamin** [comment]
This is just how Python works:
https://docs.python.org/3/reference/expressions.html#operator-precedence

**Comment by moorepants** [comment]
Thanks @oscarbenjamin. I think the solution for these are then to document the gotchas well, so users will be informed about the possible issues.

**Comment by moorepants** [comment]
This is fixed by #https://github.com/sympy/sympy/pull/21749
