### ISSUE TITLE
Solved! I'm unable to get all intersections for segments

### ISSUE THREAD

**Issue by Lischip** [sympy/sympy#21727]
Hey! I've been used plotly to visualise my issue. I can't seem to find all intersections. I singled out 6 segments (that form 2 triangles). I was expecting to find 2 intersections, but I only got one. I was wondering if there was something I'm overlooking.

```
import plotly.express as px
import plotly.graph_objects as go
from sympy import Point3D, Segment3D
import numpy as np

fig = px.scatter_3d()

colors=["pink","blue"]
order=["1", "3"]

p1_min_plane = [np.array([-256.16666667, -256.16666667, -252.16666667]), np.array([425.16666667, -85.83333333, -81.83333333]), np.array([-85.83333333, 425.16666667, -81.83333333])]
p3_max_plane = [np. array([ 303.83333333, -117.16666667, -117.16666667]), np.array([335.16666667,   8.16666667, -85.83333333]), np.array([335.16666667, -85.83333333,   8.16666667])]

all_planes = p1_min_plane, p3_max_plane
for plane in all_planes:
    fig.add_trace(go.Scatter3d(name=order.pop(0), x=[plane[0][0], plane[1][0], plane[2][0], plane[0][0]], y=[plane[0][1], plane[1][1], plane[2][1], plane[0][1]], z=[plane[0][2], plane[1][2], plane[2][2], plane[0][2]], showlegend=True, surfaceaxis=1, mode="lines", surfacecolor=colors.pop(), line = dict(color = "pink", width=3), opacity=0.4))

intersections = []

plane = p1_min_plane
comp = p3_max_plane
for permutation in [[plane[0], plane[1]], [plane[0], plane[2]], [plane[1], plane[2]]]:
    line = Segment3D(Point3D(permutation[0]), Point3D(permutation[1]))
    for comp_permutation in [[comp[0], comp[1]], [comp[0], comp[2]], [comp[1], comp[2]]]:
        line2 = Segment3D(Point3D(comp_permutation[0]), Point3D(comp_permutation[1]))
        intersection = line.intersection(line2)
        if intersection != []:
            intersections.append(intersection)

print(intersections[0])

for intersection in intersections:
    fig.add_trace(go.Scatter3d(x=[float(intersection[0].x)], y=[float(intersection[0].y)], z=[float(intersection[0].z)], hovertext="AAA", showlegend=False))
    
fig.show()
```

![image](https://user-images.githubusercontent.com/4721925/125064708-38b2b080-e0b1-11eb-843c-888544b2eeb6.png)

Thanks in advance!

**Comment by oscarbenjamin** [comment]
Can you be more precise about what is not working? Which segments should have an intersection that doesn't seem to be found? Can you just show the minimal SymPy code that doesn't work?

Note that you have opened a GitHub issue which implies you are reporting a bug in SymPy. If you are just asking for help with using SymPy then that's fine but it should be opened as a "discussion" rather than an "issue". Actually the best thing would be to ask about this in the mailing list in that case:
https://groups.google.com/g/sympy

**Comment by Lischip** [comment]
Ah, I'm so sorry! I was not aware. Will ask further questions in the mailing list. Thank you! I did realise it was a mistake on my end. It was just a rounding error. I will close the issue now 😄.
