### ISSUE TITLE
Sympy is simply wrong calculating limits

### ISSUE THREAD

**Issue by donno2048** [sympy/sympy#21733]
For example, take this code:
```py
from sympy import limit, sqrt, symbols
x = symbols('x')
print(limit((sqrt(1 - x) - 2) / (2 + (x - 5) ** (1 / 3)), x, -3))
```

It will print `0`, but it's trying to calculate 

![image](https://user-images.githubusercontent.com/61805754/125193487-443edc80-e255-11eb-8d92-e5c09f881d0c.png)

Which is `-3`, don't believe me?

![image](https://user-images.githubusercontent.com/61805754/125193543-8cf69580-e255-11eb-8dd0-e54f81ccd571.png)

**Comment by johan-naizu** [comment]
True it's -3

**Comment by jksuom** [comment]
`(-8)**(S(1)/3)` denotes the principal value of the cube root of `-8` which is not `-2`:
```
>>> (-8)**(S(1)/3)
2*(-1)**(1/3)
>>> ((-8)**(S(1)/3)).equals(1 + I*sqrt(3))
True
```
Hence the limit will be 0 in SymPy. In order to get `-2`, one should use `-(5 - x)**(S(1)/3)` in the denominator:
```
>>> limit((sqrt(1 - x) - 2) / (2 - (5 - x) ** (S(1) / 3)), x, -3)
-3
```

**Comment by donno2048** [comment]
@jksuom The fact that using `**(1/3)` gives another result than `**(S(1)/3)` is a bit confusing anyway...

**Comment by oscarbenjamin** [comment]
The Python expression 1/3 creates an inexact float. It isn't possible for sympy to override that unless you call some sympy function as part of the expression e.g. `S(1)/3` or more directly `Rational(1, 3)`.

**Comment by donno2048** [comment]
I thought this is the reason, thanks
