### ISSUE TITLE
Bugs report: fraction power error

### ISSUE THREAD

**Issue by stevenleeS0ht** [sympy/sympy#21732]
Looking for the following code:

```python3
>>> from sympy import *
>>> c, n ,r = symbols('c n r')
>>> (r + 1)**-n == 1/(r+1)**n
True
>>> (r+1)**-n == (1/(r+1))**n
False
```

Why the second one is false?

**Comment by stevenleeS0ht** [comment]
@smichr , @asmeurer  please have a look.

**Comment by oscarbenjamin** [comment]
These expressions are not equivalent for all values of the symbols:
```python
In [24]: c, n ,r = symbols('c n r')

In [25]: expr1, expr2 = (r+1)**-n, (1/(r+1))**n

In [26]: expr1
Out[26]: 
       -n
(r + 1)  

In [27]: expr2
Out[27]: 
       n
⎛  1  ⎞ 
⎜─────⎟ 
⎝r + 1⎠ 

In [28]: expr1.subs(r, -2).subs(n, S.Half)
Out[28]: -ⅈ

In [29]: expr2.subs(r, -2).subs(n, S.Half)
Out[29]: ⅈ
```
This is discussed here:
https://docs.sympy.org/latest/tutorial/simplification.html#powers

If `n` is an integer then they are equivalent:
```python
In [30]: n = Symbol('n', integer=True)

In [31]: (r+1)**-n == (1/(r+1))**n
Out[31]: True
```

**Comment by stevenleeS0ht** [comment]
@oscarbenjamin , Is there any equivalent tools in `sympy` which provide similar functionality as `Refine` function or `Assumptions` rule in `Wolfram Mathematica`?

https://reference.wolfram.com/language/ref/Assumptions.html
https://reference.wolfram.com/language/ref/Refine.html

**Comment by smichr** [comment]
If `n` is an integer or if the base is positive then these are equivalent:
```
>>> c, n ,r = symbols('c n r', nonnegative=True)
>>> expr1, expr2 = (r+1)**-n, (1/(r+1))**n
>>> expr1==expr2
True
```

**Comment by stevenleeS0ht** [comment]
@smichr , possibly could close.
