### ISSUE TITLE
Error in the sympy tutorial in the matrix section

### ISSUE THREAD

**Issue by EPort5317** [sympy/sympy#21795]
Here is the page in question:
https://docs.sympy.org/latest/tutorial/matrices.html#shape

In the tutorial it says:

>>> from sympy import shape
M = Matrix([[1, 2, 3], [-2, 0, 4]])
M
⎡1   2   3⎤
⎢            ⎥
⎣-2  0  4⎦
shape(M)
(2, 3)

but when I tried it in a Jupyter python notebook, it said:

>>> ImportError                               Traceback (most recent call last)
<ipython-input-2-e4a181c16606> in <module>
----> 1 from sympy import shape
      2 M = Matrix([[1, 2, 3], [-2, 0, 4]])
      3 M
ImportError: cannot import name 'shape' from 'sympy' (/opt/anaconda3/lib/python3.7/site-packages/sympy/__init__.py)

I thought it might be a problem with the notebook or that I might have just had an older version downloaded, but when I tried it in SympyLive it gave me this:

>>> Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: cannot import name shape

I tried importing shape from numpy instead, and tried again in the notebook:

>>> from numpy import shape
M = Matrix([[1, 2, 3], [-2, 0, 4]])
M
⎡1   2   3⎤
⎢            ⎥
⎣-2  0  4⎦
shape(M)
(2, 3) 

This appears to be correct. However, when I tried this in the SymPy Live Shell I got this:

>>> from numpy import shape
... 
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/base/data/home/apps/s~sympy-live-hrd/66.426491309333028408/lib/numpy/__init__.py", line 140, in <module>
    from . import _distributor_init
ImportError: cannot import name _distributor_init

So this solution may just be a coincidence. If shape() is currently supported in sympy, is this the correct solution or is there something else I need to do to make it available? 
The versions in the notebook I was using are as follows:
Numpy: 1.18.1
Sympy: 1.5.1

**Comment by oscarbenjamin** [comment]
You need to use the latest version of SymPy (1.8). SymPy Live does not use the latest version: https://github.com/sympy/sympy-live/issues/175
