### ISSUE TITLE
Installation failed on Python 3.9.5 on Windows 10

### ISSUE THREAD

**Issue by delgh1** [sympy/sympy#21800]
Symptom:
I ran `python.exe ./setup.py install`, at the end of the output:

> ...
> Installing isympy-script.py script to C:\Users\xxxxx\AppData\Local\Programs\Python\Python39\Scripts
> error: [Errno 2] No such file or directory: 'C:\\Users\\xxxxx\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\setuptools\\cli-64.exe'

`[Errno 2]` <--- obvious typo?
I heard that cli-64.exe does not exist in this version of python. Please address this issue for latest python releases.

**Comment by oscarbenjamin** [comment]
Do you have setuptools installed?

**Comment by delgh1** [comment]
> Do you have setuptools installed?
Yes, `setuptools-56.0.0`.

I installed vanilla Python 3.9.5.
I ran `py -m pip install --upgrade pip` to upgrade pip from 21.1.1 to 21.2.1, then I also upgraded setuptools to 57.4.0.
So this issue is solved. I recommend adding `"remember to upgrade pip and setuptools"` in the doc for newbies like me.
Case closed.

**Comment by oscarbenjamin** [comment]
I think that we should just get rid of the setup.py and have a pyproject.toml.

For development I install in editable mode with `pip install -e .`. If you just want the latest release then you can just do `pip install sympy` which will also download it for you.

**Comment by asmeurer** [comment]
As far as I know editable installs are still a work in progress for pyproject.toml (there was a PEP very recently accepted about it).

**Comment by oscarbenjamin** [comment]
The current state of the art is that a minimal setup.py is still needed for editable installs:
https://snarky.ca/what-the-heck-is-pyproject-toml/

All that is needed is:
```python
# setup.py
import setuptools

if __name__ == "__main__":
    setuptools.setup()
```

I expect that soon it will not even be necessary to have that. For now though we could strip back to that and remove all reference to setup.py from the README or any other installation instructions. The setup.py also has things that don't work like benchmarks, audit etc so it would be good to just get rid of those.

What I'm not sure about is whether to use setuptools, poetry or flit for packaging and building wheels etc. I don't quite understand what the implications are in choosing between them beyond which one you happen to use for building wheels (which very few people in sympy do).

**Comment by asmeurer** [comment]
@delgh1 "Errno" isn't a typo. It's short for "error number". In low level code, errors are represented by numbers, in this case, 2 (which based on the message means "No such file or directory"). The error in this case is most likely coming from Windows.

**Comment by delgh1** [comment]
@asmeurer thank you for the clarification. From a newbie point of view I would say "Err no", "ErrNo", "Erronum", or "ErroNum" are easier to understand.

**Comment by asmeurer** [comment]
The term errno dates from the early C days when bytes were expensive and shorter names were preferred over verbose readable ones.
