### ISSUE TITLE
Upload built docs for on PR CI builds

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#21829]
If you look at the matplotlib CI, they have a special build that builds their docs and uploads them somewhere. For example, go to some matplotlib PR https://github.com/matplotlib/matplotlib/pulls and click the "Check the rendered docs here!" build in the checks section at the bottom. 

I think they are using a combination of GitHub Actions and Circle CI. CC Matplotlib devs @tacaswell @story645 @Qulogic. How hard would it be to just copy what matplotlib is using to SymPy?

**Comment by story645** [comment]
@larsoner most recently touched this in #20680 which relies on https://github.com/marketplace/actions/run-circleci-artifacts-redirector and looks to be fairly general?

**Comment by larsoner** [comment]
> How hard would it be to just copy what matplotlib is using to SymPy?

The redirector step is just about trivial. Getting docs to build with artifacts on CircleCI is also fairly easy (IMO) for someone familiar with CIs

> looks to be fairly general?

Yep, create CircleCI artifacts and you can use [run-circleci-artifacts-redirector](https://github.com/marketplace/actions/run-circleci-artifacts-redirector) / [circleci-artifacts-redirector-action](https://github.com/larsoner/circleci-artifacts-redirector-action). The GitHub action just saves a couple of clicks from the standard CircleCI page where you'd have to login via GitHub, then click the "artifacts" tab, then click a link.

So far I think it's used by NumPy, SciPy, matplotlib, etc. so should hopefully work for you, too!

**Comment by oscargus** [comment]
I think it may be possible to do using https://github.com/actions/upload-artifact as well.

If I get it right (which I may not), there will be an artifact for the sphinx build then and not as nice at matplotlib where you have it clearly visible in the test list.

**Comment by asmeurer** [comment]
https://github.com/sympy/sympy/issues/23460
