### ISSUE TITLE
Integration is NOT correct!

### ISSUE THREAD

**Issue by weishanlee** [sympy/sympy#21831]
![126897533-1aa3c024-1fe0-4923-83ef-eab344d1efe9](https://user-images.githubusercontent.com/44011158/128466418-c403aada-cbd0-41d1-a816-fd850465e32d.jpg)

The answer should be π/12

**Comment by Arnab1181412** [comment]
Yes I see that also the answer should be pi/12

**Comment by weishanlee** [comment]
I tried many computer algebra systems, such as Mathematica, Maple, that are proprietary, and some open-source ones, such as sagemath, as well as sympy. Sympy is the more promising one. There are at least two reasons for it. First, it is implemented to python easily. Second, it is free. I will promote this lovely library to my class in the upcoming temrs.

**Comment by jksuom** [comment]
It seems that the bug is in `Integral.doit` that makes `atan` and `acot` continuous by adding `floor` terms. In some cases, `doit` may be iterated. Then the `floor` terms should be added only on the final round. Something like this will be needed to fix this:
```
--- a/sympy/integrals/integrals.py
+++ b/sympy/integrals/integrals.py
@@ -602,7 +602,11 @@ def try_meijerg(function, xab):
                             function = ret
                             continue
 
-            if not isinstance(antideriv, Integral) and antideriv is not None:
+            final = hints.get('final', True)
+            # doit may be iterated but floor-terms making atan and acot
+            # continuous should only be added on the final round.
+            if (final and not isinstance(antideriv, Integral) and
+                antideriv is not None):
                 for atan_term in antideriv.atoms(atan):
                     atan_arg = atan_term.args[0]
                     # Checking `atan_arg` to be linear combination of `tan` or `cot`
@@ -1098,6 +1102,7 @@ def _eval_integral(self, f, x, meijerg=None, risch=None, manual=None,
                             # method was set to False already
                             new_eval_kwargs = eval_kwargs
                             new_eval_kwargs["manual"] = False
+                            new_eval_kwargs['final'] = False
                             result = result.func(*[
                                 arg.doit(**new_eval_kwargs) if
                                 arg.has(Integral) else arg
```
