### ISSUE TITLE
Piecewise plot with abs not working properly

### ISSUE THREAD

**Issue by mrepetto94** [sympy/sympy#21830]
I tried

```
from sympy import *

x = Symbol("x")

f = Piecewise(
    (3*x + 1, And(0 <= x, x < 3)),
    (abs(2 - x), And(3 <= x, x <= 6))
)

plot(f);
```
But it seems like the plot function does not take into account the absolute value whereas:

```
from sympy import *

x = Symbol("x")

f = abs(2 - x)

plot(f);
```
 works perfectly. Let me know If you need further information.

**Comment by oscargus** [comment]
Do you get something like?
![image](https://user-images.githubusercontent.com/8114497/132130898-4002fa09-7f6b-4045-933a-dc097116068f.png)

I spent some time trying to figure out the problem before realizing that in this case the x-axis is a bit weirdly positioned so it looks like there are negative numbers...

**Comment by oscargus** [comment]
That is with current master I should say, so there might have been an issue in earlier versions.

**Comment by mrepetto94** [comment]
You are right, I got the same plot. I did not spot the shift upward the origin
