### ISSUE TITLE
RecursionError and TypeError in nonlinsolve

### ISSUE THREAD

**Issue by proy87** [sympy/sympy#21890]
`nonlinsolve([4*x**3*y**4 - 2*y, 4*x**4*y**3 - 2*x],x,y)` raises RecursionError

If there is an assumption that the variables are real:
```
x,y = symbols('x y', real=True)
nonlinsolve([4*x**3*y**4 - 2*y, 4*x**4*y**3 - 2*x],x,y)
```
then `TypeError: Invalid comparison of non-real 2**(2/3)*sqrt(3)*I/(2*x)`

**Comment by proy87** [comment]
Another recursion error is `nonlinsolve([(1 - 4*x**2)*exp(-2*x**2 - 2*y**2), -4*x*y*exp(-2*x**2)*exp(-2*y**2)], x,y)`.

**Comment by oscargus** [comment]
Interesting semi-related issue:

```
In [15]: (x*I).is_extended_real

In [16]: (I/x).is_extended_real
Out[16]: False
```

It seems like they should evaluate to the same thing.

For your first equation, relationals are formed with the following arguments and only the last one triggers the exception.

```
2**(2/3)/(2*x) 0
(-2**(2/3)/4 - 2**(2/3)*sqrt(3)*I/4)/x 0
(-2**(2/3)/4 - 2**(2/3)*sqrt(3)*I/4)/x 2**(2/3)/(2*x)
(-2**(2/3)/4 + 2**(2/3)*sqrt(3)*I/4)/x 0
(-2**(2/3)/4 + 2**(2/3)*sqrt(3)*I/4)/x 2**(2/3)/(2*x)
(-2**(2/3)/4 + 2**(2/3)*sqrt(3)*I/4)/x (-2**(2/3)/4 - 2**(2/3)*sqrt(3)*I/4)/x
```

**Comment by oscarbenjamin** [comment]
> Interesting semi-related issue:
> 
> ```
> In [15]: (x*I).is_extended_real
> 
> In [16]: (I/x).is_extended_real
> Out[16]: False
> ```
> 
> It seems like they should evaluate to the same thing.

I presume these are with x declared as real. If x is real then `x*I` can also be real if `x` is zero. However `I/x` is not real for any real value of `x`.

**Comment by oscargus** [comment]
> However `I/x` is not real for any real value of `x`.

Good point!

**Comment by oscarbenjamin** [comment]
I'm not sure I understand what you mean as I don't see an error:
```python
In [3]: (-2**(S(2)/3)/4 - 2**(S(2)/3)*sqrt(3)*I/4)/x >= 2**(S(2)/3)/(2*x)
Out[3]: 
   2/3    2/3            
  2      2   ⋅√3⋅ⅈ       
- ──── - ─────────    2/3
   4         4       2   
────────────────── ≥ ────
        x            2⋅x 

In [4]: (-2**(S(2)/3)/4 + 2**(S(2)/3)*sqrt(3)*I/4)/x >= (-2**(S(2)/3)/4 - 2**(S(2)/3)*sqrt(3)*I/4)/x
Out[4]: 
   2/3    2/3           2/3    2/3     
  2      2   ⋅√3⋅ⅈ     2      2   ⋅√3⋅ⅈ
- ──── + ─────────   - ──── - ─────────
   4         4          4         4    
────────────────── ≥ ──────────────────
        x                    x  
```

**Comment by oscargus** [comment]
The `TypeError: Invalid comparison of non-real 2**(2/3)*sqrt(3)*I/(2*x)` comes from executing that comparison in the code, although I currently cannot remember exactly where.

**Comment by oscargus** [comment]
```
In [32]: x = Symbol('x', real=True)

In [33]: 2**(S(2)/3)*sqrt(3)*I/(2*x) >= S(0)
Traceback (most recent call last):

  File "/tmp/ipykernel_31233/3956615599.py", line 1, in <module>
    2**(S(2)/3)*sqrt(3)*I/(2*x) >= S(0)

  File "/local/data1/miniconda3/lib/python3.8/site-packages/sympy/core/decorators.py", line 266, in _func
    return func(self, other)

  File "/local/data1/miniconda3/lib/python3.8/site-packages/sympy/core/expr.py", line 369, in __ge__
    return GreaterThan(self, other)

  File "/local/data1/miniconda3/lib/python3.8/site-packages/sympy/core/relational.py", line 706, in __new__
    raise TypeError("Invalid comparison of non-real %s" % me)

TypeError: Invalid comparison of non-real 2**(2/3)*sqrt(3)*I/(2*x)
```

Does not happen without the real assumption.

**Comment by smichr** [comment]
`Mul._eval_is_real_imag` probably needs to be improved to consider numerator and denominator separately; it is assuming the expression has a denominator of 1, so it is not resolving the case of `((1+I)/x).is_real` when `x` is real; and if it doesn't resolve then it won't trigger the error when forming the relational.
