### ISSUE TITLE
Generalized (complex) order integrals [Feature request + Bug report]

### ISSUE THREAD

**Issue by donno2048** [sympy/sympy#21899]
You can generalize the order of integrals like so:

```py
from sympy import gamma, diff, integrate, symbols, powsimp
def generalized_order_integral(f, order, x): # integral of "f" of order "order" by the symbol "x"
    t = symbols('t')
    return diff(integrate(powsimp(x - t, order) * f.subs(x, t), (t, 0, x)), x) / gamma(order + 1) + f.subs(x, 0)
```

Then, for any natural `order` this will be equivalent to the integral with this order from the standard definition and for any complex (including real) `order` if you derive it you will get the integral of order `order - 1` if it's defined.

This is defined wherever `gamma` is defined.

For example:

```py
>>> from sympy import gamma, diff, integrate, symbols, powsimp
>>> def generalized_order_integral(f, order, x):
...     t = symbols('t')
...     return diff(integrate(powsimp(x - t, order) * f.subs(x, t), (t, 0, x)), x) / gamma(order + 1) + f.subs(x, 0)
...
>>> from sympy import exp, I
>>> x = symbols('x')
>>> generalized_order_integral(x, 1, x)
x**2/2
>>> generalized_order_integral(x ** 2, 1, x)
x**3/3
>>> generalized_order_integral(exp(x), 0, x)
exp(x)
>>> generalized_order_integral(exp(x), 1, x)
exp(x)
>>> generalized_order_integral(gamma(1 + I) * exp(x), 1 + I, x)
(exp(x)*gamma(1 + I) - gamma(1 + I))/gamma(2 + I) + gamma(1 + I)
>>> generalized_order_integral(x ** 2, I, x) # https://www.wolframalpha.com/input/?i=D%5BIntegrate%5BPower%5Bx-t%2Ci%5D%28t**2%29%2C%7Bt%2C0%2Cx%7D%5D%2Cx%5D%2Fgamma%281%2Bi%29
x**3/(3*gamma(1 + I))
>>> generalized_order_integral(x ** 5, 2, x) # https://www.wolframalpha.com/input/?i=D%5BIntegrate%5BPower%5Bx-t%2C2%5D%28t**5%29%2C%7Bt%2C0%2Cx%7D%5D%2Cx%5D%2Fgamma%283%29
x**6/12
```

Even if not used for fractional derivatives this is useful to calculate the nth integral of a function fast and easily.

As you might notices the two last examples returned an incorrect result while wolfram does it correctly this is probably a bug.

**Comment by oscarbenjamin** [comment]
There is a related issue for the nth integral: #16687

I think it would be reasonable to add a function for computing this or perhaps even a symbolic class to represent integrals of arbitrary/complex order. Are there useful identities that can be applied with this definition of the kth integral (for complex k) when working with it symbolically (i.e. without actually evaluating the integral or reducing it to an ordinary integral)?

**Comment by donno2048** [comment]
I mean there is the known property that the differential of order `n` of the integral of order `z` is the integral of order `z - n`, other than that I have no idea.

**Comment by donno2048** [comment]
@oscarbenjamin would it be ok if I made a PR simply adding this function? (to `sympy.integrals`)

**Comment by oscarbenjamin** [comment]
> @oscarbenjamin would it be ok if I made a PR simply adding this function? (to `sympy.integrals`)

I'm not sure. It's useful but also the function is quite simple so it can just be done directly for anyone who wants it.

As a metapoint in general it is a bad idea to address a question like that to a specific person because if they don't answer then others who could answer might not respond.

**Comment by donno2048** [comment]
> I'm not sure. It's useful but also the function is quite simple so it can just be done directly for anyone who wants it.

I don't think it's an obvious formula some people might assume it can't be done

**Comment by oscarbenjamin** [comment]
I would prefer to have an example of a "what do you use this for" to motivate it. There are a lot formulas that we can just add to SymPy and we can't add everything. SymPy makes it easy to make your own formulas so it shouldn't be necessary to try and include every possible formula in SymPy itself. This could just be a note in the docs or something.

If there was a way to make use of this for something in SymPy itself then that would help to think about how to design it. Also if it was a symbolic class instead and could be used with identities and so on then that would be different because then it's not so easy for someone to just write down the formula.
