### ISSUE TITLE
incorrect result of nonlinsolve

### ISSUE THREAD

**Issue by proy87** [sympy/sympy#21908]
`nonlinsolve([(x**2 + 2*x - y**2)*exp(x), -2*y*exp(x)],x,y)` returns `(x,0)`, but clearly there are two solutions `(0,0)` and `(-2,0)`.

**Comment by oscarbenjamin** [comment]
This is already fixed on master
```python
In [1]: nonlinsolve([(x**2 + 2*x - y**2)*exp(x), -2*y*exp(x)],x,y)
Out[1]: {(-2, 0), (0, 0)}
```
It was fixed in ec9397e269c1ea7496add29c19586a746b78ee38 from #21276.

This can be closed if a test is added for this system.
