### ISSUE TITLE
Wrong Integration

### ISSUE THREAD

**Issue by Geschiiii** [sympy/sympy#21906]
Hallo together, i want to report an erroneous Integral 

    from __future__ import division
    import numpy as np
    import sys
    import matplotlib as mpl
    import matplotlib.pyplot as plt
    from scipy.optimize import least_squares
    from scipy.integrate import solve_ivp
    from sympy.plotting import plot
    from sympy import *
    init_printing()
    
    x,t = symbols('x t')
    
    y = (1 - x)
    
    exp = Pow(y,-1)
    
    res = integrate(exp,x)

results in - log( x - 1) but it must be -log( 1 - x )

see https://www.wolframalpha.com/input/?i=integral+%281-x%29%5E-1

Best regards

**Comment by oscarbenjamin** [comment]
Both answers are correct as antiderivatives as the differ by a constant (`-log(-1) = -I*pi`). The answers give real values for different ranges of real `x` i.e. `log(x - 1)` is real for `x > 1` whereas `log(1-x)` is real for `x < 1`.
