### ISSUE TITLE
Deprecated `np.float` used in `test_sympify.py`

### ISSUE THREAD

**Issue by oscarbenjamin** [sympy/sympy#21912]
The test function here uses e.g. `np.float` rather than `np.float64`:
https://github.com/sympy/sympy/blob/81f1401300956b27e5dff870c37022421c7e37bb/sympy/core/tests/test_sympify.py#L721-L740
That gives warnings with recent numpy releases:
```python
>>> import numpy as np
>>> np.float
<stdin>:1: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
<class 'float'>
```
Those should be changed to e.g. `numpy.float64`.

**Comment by Kwanzoe** [comment]
Could I be assigned to fix this?

**Comment by ayushk7102** [comment]
Hello, I am submitting a pull request with the necessary changes
