### ISSUE TITLE
AtributeError in atoms for Matrix 

### ISSUE THREAD

**Issue by proy87** [sympy/sympy#21934]
`Expr(Matrix([1,2]),Matrix([3,4])).atoms()` raises `AtributeError`.

**Comment by oscarbenjamin** [comment]
The `Expr` class does not automatically sympify its args:
```
In [4]: Expr(None).atoms()
---------------------------------------------------------------------------
AttributeError
```
However the Expr class is not intended to be used like this. It is really an abstract base class so you shouldn't try to instantiate it.

**Comment by proy87** [comment]
@oscarbenjamin, just an example.
If I create some custom class that inherits `Expr`, I will get the same error.
For example, if I need a set of matrices wrapper.

Moreover, `Add(Matrix([1,2]), Matrix([3,4]), evaluate=False)` doesn't respect the `evaluate` flag. If it did respect this flag, there would be again the `AttributeError`.

**Comment by oscarbenjamin** [comment]
A subclass of Expr needs to sympify its args:
```python
In [22]: class MyExpr(Expr):
    ...:     def __new__(cls, *args):
    ...:         args = (sympify(arg) for arg in args)
    ...:         return super().__new__(cls, *args)
    ...: 

In [23]: MyExpr(Matrix([1,2]),Matrix([3,4])).atoms()
Out[23]: {1, 2, 3, 4}
```

**Comment by proy87** [comment]
@oscarbenjamin , got it!
