### ISSUE TITLE
Factoring semiprimes with close factors

### ISSUE THREAD

**Issue by warm-ice0x00** [sympy/sympy#21937]
Using examples from [Sage Thematic Tutorials](https://doc.sagemath.org/html/en/thematic_tutorials/explicit_methods_in_number_theory/integer_factorization.html):
```Python
a = sympy.nextprime(2 ** 40) * sympy.nextprime(2 ** 300)
b = sympy.nextprime(2 ** 90) * sympy.nextprime(2 ** 91)
```
`a` has 103 digits, and `b` has 55 digits.
On my computer, `a` can be factored in a few seconds. However, factoring `b` takes about an hour.
The [integer factorization calculator](https://www.alpertron.com.ar/ECM.HTM) can factor both in a few seconds.
Can `sympy.factorint` be accelerated?
I used the default arguments of `sympy.factorint` in SymPy 1.8.

Update:
```Python
a = 2425967623052370772757633156976982469681
b = 1451730470513778492236629598992166035067
print(sympy.isprime(a), sympy.isprime(b))  # True True
```
Factoring `a * b` (79 digits) on the same computer took 4 days and 6 hours.

**Comment by smichr** [comment]
closing as a sub-issue to be handled by #19031
