### ISSUE TITLE
Make `Body` and `ReferenceFrame` analogous 

### ISSUE THREAD

**Issue by sidhu1012** [sympy/sympy#21964]
`Body` and `ReferenceFrame` are analogous in dynamics, and all the joint classes , jointsmethod and class body follow it, but rest of physics module doesn't.

Example - 

```
>>> A = Body('A')
>>> N = ReferenceFrame('N')
>>> A.dcm(N) # Works
>>> A.dcm(A) # Works

>>> N.dcm('A') # Error but should work

```

So where ever ReferenceFrame works on being passed as arg, passing body to same arg should also work.

It can be done simply by - 
```
if isinstance(frame, Body):
    frame = Body.frame
```

cc - @moorepants

**Comment by mohajain** [comment]
I would like to work on this.  

> It can be done simply by -
> 
> ```
> if isinstance(frame, Body):
>     frame = Body.frame
> ```

Where do I have to add this line?

**Comment by sidhu1012** [comment]
> Where do I have to add this line? 
> 

In physics module wherever we can pass `ReferenceFrame`, we should be able to pass `Body`.

**Comment by mohajain** [comment]
The physics module is really vast, I'm unable to find such functions. Please guide me through, I'm new to sympy.

**Comment by sidhu1012** [comment]
The one's that I remember are Physics.mechanics.functions module(Inertia and all) , physics.mechanics.vector.frame (orient functions) and many more.

All of the functions would be in mechanics and vector sub module.

**Comment by mohajain** [comment]
Thanks a lot!
Do I have to change these lines 
```
if not isinstance(frame, ReferenceFrame):
        raise TypeError('Need to define the inertia in a frame')
```
to something like
```
if not isinstance(frame, ReferenceFrame) and not isinstance(frame, Body):
        raise TypeError('Need to define the inertia in a frame')
```
as well?

**Comment by mohajain** [comment]
Thanks a lot!
Do I have to change these lines
```
if not isinstance(frame, ReferenceFrame):
        raise TypeError('Please enter a valid ReferenceFrame')
```
to something like this
```
if not isinstance(frame, ReferenceFrame) and not isinstance(frame, Body):
        raise TypeError('Please enter a valid ReferenceFrame')
```
as well?

**Comment by sidhu1012** [comment]
Only change required is to add seperate check if frame's a body before checking frame.

**Comment by moorepants** [comment]
It would be nice if duck typing worked, i.e. add all methods to body that mimic ReferenceFrame.

**Comment by sidhu1012** [comment]
> It would be nice if duck typing worked, i.e. add all methods to body that mimic ReferenceFrame.

Yes that's the end goal,  Body should have everything possible that Particle, Rigid body and Reference Frame has.

**Comment by yasphy** [comment]
Is this issue still open?

**Comment by Infinil** [comment]
I would like to work on this issue. I am pretty new to open source development so I think this problem will be a great way to start

**Comment by TJStienstra** [comment]
The current solutions here seem to focus on checking on every usage whether something is not a `Body`. Wouldn't it be better to instead change the `Body` class such that it responds as a `ReferenceFrame`?
I am currently experimenting with something like:
```py
def __getattr__(self, name):
    if hasattr(self.frame, name):
        return self.frame.__getattribute__(name)
    else:
        raise AttributeError
```
[This](https://stackoverflow.com/a/2405617) is why I use `__getattr__`. This part will solve the direct calls on the `Body`, when an attribute is needed like `body.x`. But it will give error on the isinstance checks. I have not yet figured out how to nicely [fake a type](https://stackoverflow.com/questions/6803597/how-to-fake-type-with-python), also not sure if we should even want it.

**Comment by sujantkumarkv** [comment]
Hey there!
I request a response on the status of this issue.

@TJStienstra @sidhu1012 @mohajain @yasphy @Infinil

**Comment by sujantkumarkv** [comment]
Hey!
As far as I read (and please correct me): `BodyBase` has been implemented but `Body` hasn't been deprecated according to pull #24234. 

So, as per this issue, we started off with making `Body` and  `ReferenceFrame` analogous but currently stand on leaving it as composition and because `Body` would be deprecated sooner or later.
I came via GSOC Ideas'23 from [Bug burn](https://github.com/sympy/sympy/wiki/GSoC-Ideas#classical-mechanics-bug-burn-down) prioritizing to solve & close as many PRs. 

So, with all said above, doesn't it fit that this issue can be closed now or after deprecating `Body`?

**Comment by sujantkumarkv** [comment]
> `Body` and `ReferenceFrame` are analogous in dynamics, and all the joint classes , jointsmethod and class body follow it, but rest of physics module doesn't.
> 
> Example -
> 
> ```
> >>> A = Body('A')
> >>> N = ReferenceFrame('N')
> >>> A.dcm(N) # Works
> >>> A.dcm(A) # Works
> 
> >>> N.dcm('A') # Error but should work
> ```
> 
> So where ever ReferenceFrame works on being passed as arg, passing body to same arg should also work.
> 
> It can be done simply by -
> 
> ```
> if isinstance(frame, Body):
>     frame = Body.frame
> ```
> 
> cc - @moorepants

I would also like to mention regarding the original issue:
`A.dcm(N)` doesn't work & neither does `N.dcm(A)`, `A.dcm(A)` returns :: `Matrix([[1, 0, 0],
[0, 1, 0],
[0, 0, 1]])`

**Comment by sujantkumarkv** [comment]
Hey @TJStienstra, 

Based on [this comment](https://github.com/sympy/sympy/issues/24256#issuecomment-1464884548) of yours, I would think that it's best to close this issue as to keep things in order and clean.
Thanks.

**Comment by shishir-11** [comment]
I think this issue needs to be closed since Body has been deprecated
