### ISSUE TITLE
Add `orient` functions to `Body`

### ISSUE THREAD

**Issue by sidhu1012** [sympy/sympy#21965]
Since `Body` and `ReferenceFrame` are analogous , all the orient functions should be added to class body so that we can simply do:-

```
>>> A = Body('A')
>>> B = Body('B')
>>> A.orent_axis(B, axis , angle)
```

cc - @moorepants

**Comment by mostlyaman** [comment]
Hello, I would like to work on this issue. 

 I understand the changes required. I need to implement the 7 `orient` functions namely `orient_axis`, `orient_explicit`, `orient_body_fixed`, `orient_space_fixed`, `orient_quaternion`, `orient` and `orientnew` from `ReferenceFrame` to `Body`.
I would like to ask about the docstrings. I believe they also need to be updated when transferred to Body. Like for example, 
orient_axis which looks like this in ReferenceFrame
```python
    def orient_axis(self, parent, axis, angle):
        """Sets the orientation of this reference frame with respect to a
        parent reference frame by rotating through an angle about an axis fixed
        in the parent reference frame.

        Parameters
        ==========

        parent : ReferenceFrame
            Reference frame that this reference frame will be rotated relative
            to.
```
would look like this in Body
```python
    def orient_axis(self, parent, axis, angle):
        """Sets the orientation of this body with respect to a
        parent body by rotating through an angle about an axis fixed
        in the parent Body.

        Parameters
        ==========

        parent : Body
            Body that this Body will be rotated relative to.
```

**Comment by sidhu1012** [comment]
> would look like this in Body
> ```python
>     def orient_axis(self, parent, axis, angle):
>         """Sets the orientation of this body with respect to a
>         parent body by rotating through an angle about an axis fixed
>         in the parent Body.
> 
>         Parameters
>         ==========
> 
>         parent : Body
>             Body that this Body will be rotated relative to.
> ```


It should work with both frame and body.

**Comment by mostlyaman** [comment]
@sidhu1012  I am new to sympy physics module. I have read quite a bit of documentation.  To my understanding, Body objects have a reference frame. So, to use orient functions on a body is equivalent to operating on its reference frame. So, from your example above.
```
 >>> A = Body('A')
 >>> B = Body('B')
 >>> A.orent_axis(B, axis , angle)
```
Can this be done like this?
```
A= Body('A')
B= Body('B')
A_new_frame = A.frame.orient_axis(B.frame, axis, angle)
A.frame = A_new_frame
```
Does this make sense to you?

**Comment by moorepants** [comment]
Let's now add `orient` and `orientnew` as I'd like to see those no longer used (we can de-emphasize or hide them in the documentation).

**Comment by sidhu1012** [comment]
> Can this be done like this?
> 
> ```
> A= Body('A')
> B= Body('B')
> A_new_frame = A.frame.orient_axis(B.frame, axis, angle)
> A.frame = A_new_frame
> ```

This can simply be done by
```
>>>  A= Body('A')
>>>  B= Body('B')
>>> A.frame.orient_axis(B.frame, axis, angle)
 ```

**Comment by AsRaNi1** [comment]
If this issue is not resolved, can i work on this?

**Comment by sujantkumarkv** [comment]
Hey there!
I would request the team to reply if this issue needs help?

**Comment by basantbhandari** [comment]
can i work on it if this issue is not resolved

**Comment by shishir-11** [comment]
Is there any work left on this issue . I think it should be closed now .

**Comment by moorepants** [comment]
Body has been deprecated, so closing.
