### ISSUE TITLE
failure in master?

### ISSUE THREAD

**Issue by smichr** [sympy/sympy#21968]
I saw the following in the most recent run of #21903

```console
________________________________________________________________________________
 sympy/matrices/expressions/tests/test_blockmatrix.py:test_BlockMatrix_2x2_inverse_numeric 
Traceback (most recent call last):
  File "/home/runner/work/sympy/sympy/sympy/matrices/expressions/blockmatrix.py", line 313, in schur
    inv = (d[mat].T*d[mat]).inv()*d[mat].T if generalized else d[mat].inv()
  File "/home/runner/work/sympy/sympy/sympy/matrices/matrices.py", line 2204, in inv
    return _inv(self, method=method, iszerofunc=iszerofunc,
  File "/home/runner/work/sympy/sympy/sympy/matrices/inverse.py", line 459, in _inv
    rv = M.inverse_GE(iszerofunc=iszerofunc)
  File "/home/runner/work/sympy/sympy/sympy/matrices/matrices.py", line 2189, in inverse_GE
    return _inv_GE(self, iszerofunc=iszerofunc)
  File "/home/runner/work/sympy/sympy/sympy/matrices/inverse.py", line 245, in _inv_GE
    raise NonInvertibleMatrixError("Matrix det == 0; not invertible.")
sympy.matrices.common.NonInvertibleMatrixError: Matrix det == 0; not invertible.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/sympy/sympy/sympy/matrices/expressions/tests/test_blockmatrix.py", line 234, in test_BlockMatrix_2x2_inverse_numeric
    assert block_collapse(K.inv()).as_explicit() == K.as_explicit().inv()
  File "/home/runner/work/sympy/sympy/sympy/matrices/expressions/blockmatrix.py", line 722, in block_collapse
    result = rule(expr)
  File "/home/runner/work/sympy/sympy/sympy/strategies/core.py", line 8, in exhaustive_rl
    new, old = rule(expr), expr
  File "/home/runner/work/sympy/sympy/sympy/strategies/core.py", line 41, in chain_rl
    expr = rule(expr)
  File "/home/runner/work/sympy/sympy/sympy/strategies/core.py", line 8, in exhaustive_rl
    new, old = rule(expr), expr
  File "/home/runner/work/sympy/sympy/sympy/strategies/core.py", line 30, in conditioned_rl
    return rule(expr)
  File "/home/runner/work/sympy/sympy/sympy/strategies/core.py", line 92, in switch_rl
    return rl(expr)
  File "/home/runner/work/sympy/sympy/sympy/matrices/expressions/blockmatrix.py", line 821, in bc_inverse
    return blockinverse_2x2(Inverse(reblock_2x2(expr.arg)))
  File "/home/runner/work/sympy/sympy/sympy/matrices/expressions/blockmatrix.py", line 838, in blockinverse_2x2
    MI = expr.arg.schur(formula).I
  File "/home/runner/work/sympy/sympy/sympy/matrices/expressions/blockmatrix.py", line 325, in schur
    raise NonInvertibleMatrixError('The given matrix is not invertible. Please set generalized=True \
sympy.matrices.common.NonInvertibleMatrixError: The given matrix is not invertible. Please set generalized=True             to compute the generalized Schur Complement which uses Moore-Penrose Inverse

________________________________________________________________________________
_____ sympy/assumptions/tests/test_matrices.py:test_invertible_BlockMatrix _____
Traceback (most recent call last):
  File "/home/runner/work/sympy/sympy/sympy/assumptions/tests/test_matrices.py", line 54, in test_invertible_BlockMatrix
    assert ask(Q.invertible(BlockMatrix([
AssertionError
```

**Comment by oscarbenjamin** [comment]
Note that the failure was with Python 3.10rc1 which might be significant since it has recently been added to CI.

I've installed 3.10rc1 locally and I can't reproduce this failure after 100 runs of the test.

Unfortunately the test script does not have good control of random seeds so it is not usually possible to reproduce random failures after seeing them in CI. Ideally the test script would reset all seeds before each test function is called so that the seed can be used to reproduce failures. (I haven't actually tried using the seed in this case because it hasn't worked previously.)

**Comment by oscarbenjamin** [comment]
I also saw the same failures here (also on Python 3.10rc1):
https://github.com/sympy/sympy/pull/21996#issuecomment-910696937

**Comment by oscarbenjamin** [comment]
After hundreds of runs I managed to reproduce this once under Python 3.10rc1 when running:
```
bin/test sympy/assumptions/tests/test_matrices.py -k test_invertible_BlockMatrix
```
The output I got was:
```
============================= test process starts ==============================
executable:         /Users/enojb/current/sympy/310venv/bin/python  (3.10.0-candidate-1) [CPython]
architecture:       64-bit
cache:              yes
ground types:       python 
numpy:              1.21.2
random seed:        13741568
hash randomization: on (PYTHONHASHSEED=3913382816)

sympy/assumptions/tests/test_matrices.py[1] F                             [FAIL]

________________________________________________________________________________
_____ sympy/assumptions/tests/test_matrices.py:test_invertible_BlockMatrix _____
Traceback (most recent call last):
  File "/Users/enojb/current/sympy/sympy/sympy/assumptions/tests/test_matrices.py", line 54, in test_invertible_BlockMatrix
    assert ask(Q.invertible(BlockMatrix([
AssertionError

============= tests finished: 0 passed, 1 failed, in 0.12 seconds ==============
DO *NOT* COMMIT!
```
I tried setting the random seed and hash seed like:
```
PYTHONHASHSEED=3913382816 bin/test --seed=13741568 sympy/assumptions/tests/test_matrices.py -k test_invertible_BlockMatrix
```
but that did not reproduce the failure again.

The failure is intermittent but somehow not reproducible by setting seed and hash-seed. Maybe something in sympy is ignoring the hash seed somewhere. It could also be a bug in Python 3.10 (in which case it would be good to report it before 3.10 is released).

**Comment by oscarbenjamin** [comment]
I tried this diff to see if I could get a debugger into a process where the test fails:
```diff
diff --git a/sympy/assumptions/tests/test_matrices.py b/sympy/assumptions/tests/test_matrices.py
index ca9898d077..d8325edc33 100644
--- a/sympy/assumptions/tests/test_matrices.py
+++ b/sympy/assumptions/tests/test_matrices.py
@@ -51,10 +51,19 @@ def test_invertible_BlockMatrix():
     X = Matrix([[1, 2, 3], [3, 5, 4]])
     Y = Matrix([[4, 2, 7], [2, 3, 5]])
     # non-invertible A block
-    assert ask(Q.invertible(BlockMatrix([
-        [Matrix.ones(3, 3), Y.T],
-        [X, Matrix.eye(2)],
-    ]))) == True
+    try:
+        assert ask(Q.invertible(BlockMatrix([
+            [Matrix.ones(3, 3), Y.T],
+            [X, Matrix.eye(2)],
+        ]))) == True
+    except AssertionError:
+        M = BlockMatrix([
+            [Matrix.ones(3, 3), Y.T],
+            [X, Matrix.eye(2)],
+        ])
+        breakpoint()
+        Qinv = Q.invertible(M)
+        ask(Qinv)
     # non-invertible B block
     assert ask(Q.invertible(BlockMatrix([
         [Y.T, Matrix.ones(3, 3)],
```
After hundreds more runs I still haven't managed to reproduce the failure again.

**Comment by oscarbenjamin** [comment]
Okay I have managed to finally get a debugger in there. This is to do with the new dispatch mechanism for assumptions.

The failing tests are for BlockMatrix but they fail due to a recursive call to something like this:
```python
ask(Q.invertible(eye(2))`
```
That should go to the MatrixBase handler and usually does. However very occasionally it goes to the MatrixExpr handler:
https://github.com/sympy/sympy/blob/719bb152482d2139775a412719c4e47f25204b9f/sympy/assumptions/handlers/matrices.py#L163-L173

@JSS95 do you have any idea why that might happen?

**Comment by oscarbenjamin** [comment]
This is a more straight-forward way to reproduce this but this script might need to be run thousands of times to see a failure:
```python
from sympy import eye, ask, Q, Matrix, BlockMatrix

#D = eye(2)
#P = Q.invertible(D)
#if not ask(P):
#    breakpoint()

X = Matrix([[1, 2, 3], [3, 5, 4]])
Y = Matrix([[4, 2, 7], [2, 3, 5]])
M = BlockMatrix([
    [Matrix.ones(3, 3), Y.T],
    [X, Matrix.eye(2)],
])
Minv = Q.invertible(M)
if not ask(Minv):
    breakpoint()
    D = eye(2)
    Dinv = Q.invertible(D)
    res = ask(Dinv)
    print(res)
```

**Comment by oscarbenjamin** [comment]
> might need to be run thousands of times

e.g. on Unix:
```
$ for x in `seq 1 1000`; do python t.py ; echo $x ; done
```

**Comment by oscarbenjamin** [comment]
I think that the nondeterminism comes from looping over a set here:
https://github.com/sympy/sympy/blob/966ddc8d8bd09896acb7a31bd2ad29cdf8fbf53f/sympy/multipledispatch/utils.py#L40-L43
In context that set is a set of types. Ordering of types does not seem to be deterministic even if the hash seed is set because the hash of the classes changes from one run to another nondeterministically.

The PyPI version of multipledispatch seems to use an OrderedDict:
https://github.com/mrocklin/multipledispatch/blob/880e700c6fd5c17a4cd0fc0f14ec3c1fbf4255b7/multipledispatch/utils.py#L50-L66

I would have thought that the topological sort should be enough to make this work regardless of iteration order...

**Comment by oscarbenjamin** [comment]
The basic premise in multipledispatch seems to be that it is possible to decide on an ordering of registered types before looking at the type of the object to be dispatched:
https://github.com/sympy/sympy/blob/966ddc8d8bd09896acb7a31bd2ad29cdf8fbf53f/sympy/multipledispatch/dispatcher.py#L291-L296
This is a basic design flaw. As a result the following is nondeterministic:
```python
from sympy.multipledispatch import dispatch

class A: pass

class B: pass

class C(A, B): pass

class D(B, A): pass

@dispatch(A)
def f(a):
    print('A method')

@dispatch(B)
def f(B):
    print('B method')

c = C()
d = D()

f(c)
f(d)
```
Running this repeatedly gives e.g.:
```console
$ python z.py 
A method
A method
$ python z.py 
B method
B method
```
The PyPI multiple dispatch library makes this deterministic by using `OrderedDict` but that doesn't really make the dispatch well defined. If the ordering that dispatchers are matched to should correspond to the MRO then it isn't possible to compute that ordering without knowing which class is being dispatched.

**Comment by oscarbenjamin** [comment]
Not sure what to do about this but at least using an OrderedDict (or maybe just a dict since they are all ordered) would make this deterministic.

**Comment by JSS95** [comment]
I had no idea that multipledispatch could be nondeterministic like this. Thanks for finding out. I wonder why this had not happened before redesigning the predicate...
