### ISSUE TITLE
Assumptions on domains and intervals

### ISSUE THREAD

**Issue by oscargus** [sympy/sympy#21978]
```
In [4]: S.Complexes.is_real

In [5]: S.Reals.is_real

In [6]: Interval(0, 1).is_positive

In [7]: Interval(0, 1).is_real
```

It seems like it can be useful for this to actually return something. Not sure if this breaks the idea of what Intervals and domains are for, but, e.g., `function_range` only works for ranges that are finite and real, so being able to test that easily should be useful.

**Comment by oscarbenjamin** [comment]
The (old) assumptions system should only be used for expressions (Expr) representing number-like quantities. See here:
https://docs.sympy.org/dev/guides/assumptions.html#interpretation-of-the-predicates

See also #19474

What you want here is probably something involving `is_subset` i.e.:
```python
In [10]: Interval(0, 1).is_subset(Reals)
Out[10]: True

In [12]: Interval(0, 1).is_subset(Interval(0, x))
```

**Comment by oscargus** [comment]
Closing this as I got a good answer!
