### ISSUE TITLE
Improvements in Maths and Sciences

### ISSUE THREAD

**Issue by abhyareddy** [sympy/sympy#21980]
Mathematics and Sciences are much more fun when you understand their importance in real life. Showing few real life examples alongside the serious theories and problems can attract more reach. But too many examples are not ideal too. Any one could help add the info.

**Comment by abhyareddy** [comment]
I can help sympy improve in all the subjects if you think it's worth it.

**Comment by moorepants** [comment]
More diverse examples for the documentation is welcome.

**Comment by abhyareddy** [comment]
Thank you. Am I allowed to help?

**Comment by abhyareddy** [comment]
@moorepants

**Comment by moorepants** [comment]
Anyone can help improve SymPy. See our introduction to contributing to get started: https://github.com/sympy/sympy/wiki/introduction-to-contributing

**Comment by oscarbenjamin** [comment]
I don't think that we need to keep an issue open for this unless there is a specific proposal for what to add. Otherwise this can just be discussed on the mailing list or elsewhere but open ended issues like this are problematic because they will never be closed.
