### ISSUE TITLE
Should UnevaluatedExpr.is_real query its argument?

### ISSUE THREAD

**Issue by bjodah** [sympy/sympy#21991]
Consider this:
```python
>>> from sympy import symbols as s, UnevaluatedExpr as UE
>>> r, s = s('r s', real=True)
>>> (r + s).is_real
True
>>> UE(r + s).is_real
>>>  # that is, it was "None"
```
Currently I need to treat UnevaluatedExpr as a special case in some logic. I don't see any reason why `.is_real`, `.is_complex` etc. can't be made to return `self.args[0].is_real`, ...?

But perhaps I'm missing something?

**Comment by oscarbenjamin** [comment]
The question is whether you want to allow evaluation of expressions containing UnevaluatedExpr:
```python
In [1]: cos(UnevaluatedExpr(0))
Out[1]: cos(0)

In [2]: x = Symbol('x', zero=True)

In [3]: cos(0)
Out[3]: 1
```

**Comment by bjodah** [comment]
I don't think so. I would argue that it's unrelated for my use case, and that I think it is (very) good that it's not evaluated.

Here's an example:
```python
In [4]: x, y, z = symbols('x y z', real=True)
In [5]: ccode(Abs(exp(UnevaluatedExpr(UnevaluatedExpr(y+z) + x))))
Out[5]: '// Not supported in C:\n// re\nexp(re(x + y + z))'
```

**Comment by oscarbenjamin** [comment]
> I would argue that it's unrelated for my use case

The assumptions can be implemented like this:
```diff
diff --git a/sympy/core/expr.py b/sympy/core/expr.py
index 6ff45211dd..265994bc81 100644
--- a/sympy/core/expr.py
+++ b/sympy/core/expr.py
@@ -4006,6 +4006,9 @@ def doit(self, **kwargs):
         else:
             return self.args[0]
 
+    def _eval_is_zero(self):
+        return self.args[0].is_zero
+
 
 
 def unchanged(func, *args):
```
However that change will cause expressions involving UnevaluatedExpr to evaluate in some situations:
```python
In [1]: cos(UnevaluatedExpr(0))
Out[1]: 1
```
The mechanism that prevents expressions involving UnevaluatedExpr from evaluating is basically just the fact that it has no properties that any evaluation code checks for. If you add assumptions to it then that will change:
https://github.com/sympy/sympy/blob/ed4604016775a113f0c4aa754ece296699bb24ce/sympy/functions/elementary/trigonometric.py#L576-L577

**Comment by bjodah** [comment]
Oh, I see. Thank you. I did not anticipate that (I never looked into exactly how UnevaluatedExpr achieved its special treatment). So how would we advise users to treat this case? Running a pre-processing pass in the printing process? In this particular case, I can rewrite the tree to "lift" the expression inside `re(...)` if its argument is `UnevaluatedExpr` and `.args[0].is_real` holds. But it feels very much like treating a single edge case...

**Comment by bjodah** [comment]
OK, so thinking about this a little more. In this context (this special case of code printing), the user probably wants most of UnevaluatedExpr, but not everything. So one can create a subclass an overload in accordance with your suggestion:

```python
class UnevaluatedRealPropagatingExpr(UnevaluatedExpr):
    def _eval_is_real(self):
        return self.args[0].is_real
```

this is probably the cleanest solution. Thanks again!
