### ISSUE TITLE
Reorganizing the SymPy Documentation

### ISSUE THREAD

**Issue by nanjekyejoannah** [sympy/sympy#22007]
## Abstract

SymPy documentation is currently difficult to navigate for users since the key topics are hidden in a big table of contents. After an audit of the documentation, this documentation discusses a way forward for the reorganization of the SymPy documentation. 

## Scope

The main aim of the reorganization is to achieve the following goals:

- Reorganize the documentation following the [Diátaxis documentation structure](https://diataxis.fr/).
- Migrate a few agreed-upon contents from the wiki pages.
- Ensure the documentation pages are responsive.

## Proposed Documentation Structure

As pointed out earlier, we propose using the Diátaxis documentation structure. The structure dictates that the documentation is divided into four main parts; *Getting started, How-to guides, Reference, and Explanation*. According to SymPy's needs, Diátaxis's four-category documentation structure works better than other tools we know of like DITA and Redhat's modular documentation system. The structure gives a clear scope and sets a clear tone on where each piece of information should go,  for both users and documentation authors.

### Content for each of the categories

This is a discussion on what type of SymPy documentation should live in each of the Diátaxis documentation categories.

**Getting Started**

The sections on installation and tutorial from the documentation can be migrated to this category. In addition, we propose collecting any other information and quick links under a common "About SymPy" section, also in this category. See the detailed table of contents for the full layout of sections.

**How-to Guides**

The documentation style guide, including any information on how to write tutorials and documentation, should go in this category.

**Reference**

This category can have the SymPy Modules reference. As advised, we will then have a clear distinction between public and internal APIs.

**Explanation**

The SymPy documentation under Gotchas and Pitfalls should perfectly fit in this category but we can also have the documentation on SymPy special topics here as well.

**Contributor Guide**

This consists of details on environment setup, developer workflow, and style guides to aid comprehension of the SymPy development process.

**Tutorials**

This is a collection of SymPy tutorials.

## A New Sphinx Theme

We also discussed the potential of changing the documentation theme from ``classic``. I proposed the ``Furo`` theme used by CPython, NumPy, and Pandas, etc., but this is still up for decision and suggestions. In my view, this would give us a better layout for seamless navigation of the documentation.

## Progress

- [x] Getting Started (#21747)
- [x] Contributor Guide (#21894 )
- [x] Tutorials (#22002)
- [x] Explanation (#22001)
- [x] How-to Guides (#22102)
- [ ] Public reference (#22209 #22006)
- [ ] Internal reference (#22444 #22105)
- [ ] Elaborate on the meaning of the categories (#22007 #22504)
- [ ] Change the theme

cc @asmeurer @oscarbenjamin

**Comment by asmeurer** [comment]
Can you add PR numbers to the checklist?

Another thing you didn't mention but I think was planned was changing the Sphinx theme so that the sidebar has better organization.

**Comment by moorepants** [comment]
> I proposed the Furo theme used by CPython, NumPy, and Pandas, etc., but this is still up for decision and suggestions.

I'm fine with a different theme, but it'd be nice to keep some SymPy green in the color scheme. Maybe that's not to hard with the other theme options?

**Comment by moorepants** [comment]
The Diátaxis system has 4 categories. What is the reasoning for having 6 categories for us? Is it not possible to fit everything into the 4 categories. I thought that was the main design idea of the system.

**Comment by nanjekyejoannah** [comment]
There are sections where we felt could not belong in the 4 categories perfectly, so we have two extra ones, tutorials and contributing. I think 4 categories in a guideline, most people who use Diátaxis may have some more sections.

Again, if you think these extra categories fit in the 4 Diátaxis categories, you can share your view.

**Comment by moorepants** [comment]
> Again, if you think these extra categories fit in the 4 Diátaxis categories, you can share your view.

For example, the new contributor guide could/should go in "Getting Started". Getting started can be subsectioned into "Getting Started: Users" and "Getting Started: Developers".

**Comment by moorepants** [comment]
Also, tutorials seems to be clearly "How-To Guides".

**Comment by nanjekyejoannah** [comment]
Can we get consensus on this @asmeurer @oscarbenjamin

**Comment by asmeurer** [comment]
I don't feel particularly strongly about it either way. I agree they could probably fit into the main Diataxis categories, but it also seems to fine to me to have them at the top level so that they are easier to find.

**Comment by oscarbenjamin** [comment]
I also don't feel strongly about this. The main thing is just that it is navigable so that someone can come to the docs and intuitively click through the links to get to the right place.

**Comment by asmeurer** [comment]
@moorepants I recommend reading about [Diataxis](https://diataxis.fr/) or watching [this presentation](https://www.youtube.com/watch?v=t4vKPhjcMZg) for the difference between tutorials and how-to guides. We should probably have something in the main page that makes the differences between the different Diataxis sections clear to people who don't already know about it. 

I think we should just stick with the ordering that is there. I kind of like having the getting started and how to contribute sections on the top-level, even if they technically could go in the other sections. Let me know if you feel strongly otherwise Jason.

**Comment by moorepants** [comment]
If we are going with this system, then we should go with it as is. Otherwise, starting with a modified version will just set the stage for people adding new main categories in the future. My suggestion is that we stick with the four categories, but I don't know the fine details of how to fit each of our existing pages into the categories. That can be up to @nanjekyejoannah.

I've read and watched the diataxis stuff some time ago. Thanks.

**Comment by moorepants** [comment]
> Also, tutorials seems to be clearly "How-To Guides".

Just ignore that. Mistake,

**Comment by moorepants** [comment]
So "contributing guide" and "getting started" are the two non-diataxis categories. Those are the ones that need to be merged into the others. My statements above, just confused which of the 6 were the non-diataxis categories, which is irrelevant to my point. My point is that we stick with the 4 categories of the system.

**Comment by asmeurer** [comment]
@nanjekyejoannah what do you think about this? I'm inclined to go with whatever you think is better here, since you have thought about this more than we have.

**Comment by nanjekyejoannah** [comment]
@asmeurer, we can merge them, the question is where? IMHO, both are most suited for how-to-guide

**Comment by moorepants** [comment]
Putting them there is probably fine. We can always shift things around among the categories at a later date.
