### ISSUE TITLE
State of the docs for release

### ISSUE THREAD

**Issue by oscarbenjamin** [sympy/sympy#22000]
I'm opening this to discuss what to do with the docs for the upcoming 1.9 release.

I just fixed the docs build in https://github.com/sympy/sympy_doc/pull/50 and after merging #21996 the dev docs have updated again. The current dev docs from master can be seen here:
https://docs.sympy.org/dev/index.html

The docs are currently a work in progress with @nanjekyejoannah's GSOD project under way to reorganise them. I want to put out a SymPy release ASAP at which point the dev docs will become the actual docs.

Are we okay with releasing the docs as they are or are there urgent fixes that are needed first? We can always push an update to the docs after release as well if further improvements are made.

CC @nanjekyejoannah @asmeurer

**Comment by asmeurer** [comment]
I don't see any problems with the current state of the docs in dev, but @nanjekyejoannah should confirm there aren't any known things that aren't yet resolved. It's worth pointing out that if there do end up being any issues, we can push up hotfixes to the docs repo without doing an actual release. 

On the other hand, reverting @nanjekyejoannah's PRs for the release branch shouldn't be hard, if we want to wait until the reorganization is completed before making it live in the "latest" docs. 

We have our meeting tomorrow, so let's discuss this then.

**Comment by moorepants** [comment]
Will all the urls redirect?

I think it might be best to have this major doc overhaul in a branch and in the next release, once it is complete.

**Comment by nanjekyejoannah** [comment]
Yes, we have made sure URLs redirect.

**Comment by oscarbenjamin** [comment]
I've reverted the doc changes in the 1.9 release branch 60af7dd25e493f248343a49e3533726eec39ccfd (release issue #22008).

The changes can continue on master but won't feature in the 1.9 release.
