### ISSUE TITLE
False KeyError in Symengine tests

### ISSUE THREAD

**Issue by mostlyaman** [sympy/sympy#22012]
Originated from https://github.com/sympy/sympy/pull/21988#discussion_r701142517

While working on PR #21988 while and running symengine tests, tests are failing for some reason.
The setup for recreating the bug is as follows.
```python
aman@amanUBUNTU:~/sympy$ USE_SYMENGINE=1 python3
Python 3.8.5 (default, May 27 2021, 13:30:53) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from sympy import solve, expand, symbols
>>> from sympy.physics.vector.functions import kinematic_equations, dynamicsymbols
>>> u1, u2, u3 = dynamicsymbols('u1, u2, u3')
>>> q1, q2, q3 = symbols('q1 q2 q3')
>>> eq = kinematic_equations([u1, u2, u3], [q1, q2, q3], 'body', 'XYX')
>>> eq = [expand(i) for i in eq ]
>>> td = solve(eq, [u1, u2, u3], dict = True)
>>> td
[{u1(t): 0, u2(t): 0, u3(t): 0}]
>>> # Although td[0] has u1 as a key, it gives a keyerror on giving it as a index
>>> td[0][u1]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
KeyError: u1(t)
>>> # We can also verify that u1 is there through this
>>> list(td[0].keys())
[u1(t), u2(t), u3(t)]
>>> u1 in list(td[0].keys())
True
```
This keyerror only happens when env variable USE_SYMENGINE is set to 1.
```python
>>> td[0]   # without USE_SYMENGINE=1
{u1(t): 0, u2(t): 0, u3(t): 0}
>>> td[0][u1]
0
```
fyi - @oscarbenjamin

**Comment by isuruf** [comment]
`solve` would transform symengine objects to sympy objects and therefore `td` contains `sympy` objects while `u1` is a symengine object. Although they are equal, they have different hashes and that's why there is a KeyError.

**Comment by mostlyaman** [comment]
@isuruf That is certainly the case. Using sympify on u1 before using it as a index gives no KeyError. Thanks for your help.
