### ISSUE TITLE
get spin operator for large S 

### ISSUE THREAD

**Issue by EliaStocco** [sympy/sympy#22017]
https://github.com/sympy/sympy/blob/46e00feeef5204d896a2fbec65390bd4145c3902/sympy/physics/quantum/spin.py#L246
Hello,
I am Elia Stocco,
I would like to to simulate a 1D Heisenberg model (spin chain),  with variable value of spin.
Then I would exactly diagonalize the Hamiltonian in order to study the differences in the spectrum between integer and half-integer spin values (do you think `sympy` could be suitable for this task for 8 atoms chains?). 
Anyway, I did not manage to get the spin operators (Jx,Jy,Jz), I think there could be a little problem in the code, I paste here mine
```
#%%
from sympy.physics.quantum.spin import JxKet,JyKet,JzKet
from sympy.physics.quantum import represent
from sympy.physics.quantum.operatorset import state_to_operators
from sympy import S
from IPython.display import display

#%%
s = S(1)/2
#
O2,Ox=state_to_operators(JxKet(s,-s))
print("------------------\nAxis : x")
display("O2:",represent(O2))
display("Ox",represent(Ox))
#
O2,Oy=state_to_operators(JyKet(s,-s))
print("------------------\nAxis : y")
display("O2:",represent(O2))
display("Oy",represent(Oy))
#
O2,Oz=state_to_operators(JzKet(s,-s))
print("------------------\nAxis : z")
display("O2:",represent(O2))
display("Oz",represent(Oz))
```
The variable named `O2` should be a multiple of the identity matrix but it is quite always confused with the Pauli sigmas. 
Am I doing something wrong?
Is there another ways to get Jx,Jy,Jz and J^2 for arbitrary spin values?
Thank you very much for your help

**Comment by oscargus** [comment]
I do not really have any idea about the actual topic, but consider the following lines
https://github.com/sympy/sympy/blob/25a3b8ec67a2c0ae99d0be2e9f01d294e207e1ad/sympy/physics/quantum/operatorset.py#L148-L150

Hence, you are getting a set of two operators. You may have realized that, but I was a bit confused by the wording that you expect the first operator to be a specific one and a set is in general not ordered, so if you rerun the code you may (at some stage) actually get the operators in different order. Hence, maybe `state_to_operators` are not doing what you expect?

**Comment by ogauthe** [comment]
@EliaStocco you are confusing `O2` and `Ox`: if you write
```
Ox, O2 = state_to_operators(JxKet(s,-s))
display("Ox:", represent(Ox))
display("O2", represent(O2))
```
then you can clearly recognize the expressions of spin-1/2 S^x and **S**^2 operators. The documentation does not precise the return order for operators, so this is expected behavior. To be fair, the quantum mechanics par of sympy documentation looks pretty obscure to me.

Considering your problem, you may be able to construct a 8-site spin-1/2 Heisenberg chain, however you will probably have difficulties diagonalizing it formally using sympy, the matrices being too large. You should consider using numerics, numpy is perfectly suited for the job.

**Comment by EliaStocco** [comment]
I followed the advice of @ogauthe but I think that even reversing the order ( `Ox, O2 = state_to_operators(JxKet(s,-s))` instead of  `O2,Ox=state_to_operators(JxKet(s,-s))` )  "sometimes" the function return the correct operators and "sometimes" it return them in reversed order, I don't understand where the source of "randomness" is (and why there should be).
I am running the code on Windows 10 in a jupyter notebook (restarting the kernel every time): results are not always the same.
I apologize for the name of the topic, it is not clear (because of my distraction).
I personally have also found other methods to study the physical system of my interest but it still seemed correct to let you know about this strange behavior of the library that I found

**Comment by oscarbenjamin** [comment]
The return value is a set:
```python
In [17]: type(state_to_operators(JxKet(s,-s)))
Out[17]: set
```
In Python a set does not have a deterministic order from one run of a process to another:
https://docs.python.org/3/library/stdtypes.html#set-types-set-frozenset

**Comment by EliaStocco** [comment]
I get it, thank you very much
