### ISSUE TITLE
malformed expression in Mul?

### ISSUE THREAD

**Issue by smichr** [sympy/sympy#22021]
Just don't want this to be forgotten: [discussion about issue](https://github.com/sympy/sympy/pull/21925#pullrequestreview-738464331) in #21925

A suggestion to use `Add(*bargs)` instead of `Add._from_args(bargs)` suggests that in some cases, `bargs` is not properly ordered. It would be better to identify the issue than to use the evaluated `Add` at this low level, I think. It will need some investigation. It could be that the insertion of `ar` at slot 0 is not correct in some cases.

**Comment by oscarbenjamin** [comment]
What is needed is something equivalent to `Add(*args)`. I'm not sure what else could be equivalent to that without being equally slow...
