### ISSUE TITLE
DeprecationWarning under Python 3.10 when importing sympy

### ISSUE THREAD

**Issue by oscarbenjamin** [sympy/sympy#22026]
Running under Python 3.10 importing SymPy gives a deprecation warning:
```
>>> import sympy
/Users/enojb/current/sympy/sympy/sympy/external/importtools.py:4: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
  from distutils.version import LooseVersion
```
If this is not fixed then when Python 3.10 is released the latest versions of sympy and python will show this warning every time anyone imports sympy.

This is because sympy uses disutils which is now deprecated:
https://www.python.org/dev/peps/pep-0632/

According to the PEP the replacement for distutils.version is packaging. Since this is used at runtime using packaging would mean having a runtime dependency.

There are several uses of LooseVersion in the codebase:
```console
$ git grep LooseVersion
bin/authors_update.py:from distutils.version import LooseVersion
bin/authors_update.py:if LooseVersion(git_ver) < LooseVersion(minimal):
bin/mailmap_update.py:from distutils.version import LooseVersion
bin/mailmap_update.py:if LooseVersion(git_ver) < LooseVersion(minimal):
setup.py:    from distutils.version import LooseVersion
setup.py:        if mpmath.__version__ < LooseVersion(min_mpmath_version):
sympy/conftest.py:from distutils.version import LooseVersion as V
sympy/external/importtools.py:from distutils.version import LooseVersion
sympy/external/importtools.py:        if LooseVersion(modversion) < LooseVersion(min_module_version):
sympy/external/tests/test_numpy.py:from distutils.version import LooseVersion
sympy/external/tests/test_numpy.py:    if LooseVersion(numpy.__version__) >= LooseVersion('1.17'):
sympy/interactive/printing.py:from distutils.version import LooseVersion as V
sympy/interactive/session.py:from distutils.version import LooseVersion as V
sympy/printing/tensorflow.py:from distutils.version import LooseVersion as V
```
The most important case is `sympy/external/importtools.py` which uses `LooseVersion` as part of `import_module` which is itself very widely used around the codebase. The reason for using `LooseVersion` is to compare the versions of dependencies like numpy to check that the minimum supported version is installed.

As I see it there are two options:

1. Add a runtime dependency on packaging and use the version handling tools it provides:

    https://packaging.pypa.io/en/latest/version.html

2. Don't bother checking versions at runtime in `import_module`. It is the job of installers like pip and conda to make sure that the user has a valid combination of versions. SymPy should just make sure to provide accurate version requirements in setup.py.

I would lean towards option 2. I also doubt that many of the version requirements are actually needed anyway.

**Comment by moorepants** [comment]
Option 3 could be to vendor that function into SymPy. We just need a decent version comparison function.

Depending on setuptools shouldn't be that onerous, as it is widely used. Any conda environment that has python will have setuptools and if people use pip it is unlikely (or maybe impossible) to not have it installed. It's hard to imagine not having setuptools available, but maybe there are some weird edge use cases.

**Comment by asmeurer** [comment]
It's possible to add soft dependencies that are just there for version pinning in conda. I don't know about pip. We could also just silence the warning for now. I'm -1 to adding a dependency on setuptools.

**Comment by asmeurer** [comment]
If you look at the source, LooseVersion is very simple. It could be replaced with a one-liner https://github.com/pypa/distutils/blob/main/distutils/version.py

**Comment by oscarbenjamin** [comment]
To be clear it is not setuptools that contains this it is "packaging" which is itself a separately installable package. I think packaging is used in setuptools but setuptools vendors it.

Generally I dislike the way that sympy vendors things (multipledispatch, pytest fork etc) that could just be dependencies. Each vendored thing adds to maintainance efforts and ends up being out of date because it is not maintained in the way that the external package is.

Do other Python projects check versions of dependencies at runtime though? If you install via pip or conda then the whole point is that they are supposed to give you a consistent set of versions. For a local install we should really encourage something like `pip install .` rather than `python setup.py install`. In fact I think we should remove the `setup.py` completely in favour of `setup.cfg` or remove both in favour of `pyproject.toml`.

It does look like version comparison is reasonably simple so it could be added as a function. The version checks have not been updated in a long time and are currently used to check:

1. `numpy >= 1.6.1` (released in 2011)
2. `cython >= 0.15.1` (released 2012)
3. `matplotlib >= 1.1.0` (released 2011)

I don't think that these checks are actually useful so we can just remove them and record version requirements as extras in `pyproject.toml`.

**Comment by moorepants** [comment]
> Do other Python projects check versions of dependencies at runtime though?

One main use case is to give different behavior based on different versions of dependencies (i.e. support a range of versions). Not sure if that happens in SymPy though. I certainly have to do it in packages that support ranges of SymPy versions though :(

> For a local install we should really encourage something like pip install . rather than python setup.py install. In fact I think we should remove the setup.py completely in favour of setup.cfg or remove both in favour of pyproject.toml.

Recommending `pip install` as the primary install method in our docs is a good thing, but removing `setup.py` in favor of these other options isn't great (yet). For example, in conda-forge we have to manually delete `project.toml` files often to properly build packages. `pip` and the new reliance on `project.toml` can screw up installations when you are controlling dependencies from the point of view of the package manager.

**Comment by oscarbenjamin** [comment]
I opened #22039 to vendor in the version parsing logic from distutils.

**Comment by oscarbenjamin** [comment]
> For example, in conda-forge we have to manually delete `project.toml` files often to properly build packages. `pip` and the new reliance on `project.toml` can screw up installations when you are controlling dependencies from the point of view of the package manager.

Do you have a reference with more detail explaining this?
