### ISSUE TITLE
should version_tuple return a tuple instead of a list?

### ISSUE THREAD

**Issue by smichr** [sympy/sympy#22041]
```python
>>> f=version_tuple
>>> f('2.3')
[2, 3]  <-- should be (2, 3) according to doc/inline comment
```

**Comment by oscarbenjamin** [comment]
Yes, it was supposed to be a tuple https://github.com/sympy/sympy/pull/22039#discussion_r703067077

It's not a major problem though as it's a purely internal function and a list works fine for ordering comparisons.
