### ISSUE TITLE
RecursionError in solveset

### ISSUE THREAD

**Issue by proy87** [sympy/sympy#22044]
`solveset(y**2+Rational(12/15),y)`

**Comment by oscargus** [comment]
Which version? Seems to work in both 1.8 and current master for me.

```
⎧-√3602879701896397⋅ⅈ   √3602879701896397⋅ⅈ⎫
⎨─────────────────────, ───────────────────⎬
⎩       67108864              67108864     ⎭
```

**Comment by proy87** [comment]
How can I install the development version?

**Comment by oscarbenjamin** [comment]
```
git clone https://github.com/sympy/sympy.git
cd sympy
```
You can just import sympy from there but if you want to install then
```
pip install .
```
or if you want to install and also test changes to the code then
```
pip install -e .
```

**Comment by proy87** [comment]
Thank you.
