### ISSUE TITLE
Add Rem(ainder) function?

### ISSUE THREAD

**Issue by oscargus** [sympy/sympy#22090]
Related to #22089

So far, `Mod(x, y)` has been printed in C as `x % y`. This is only correct if the sign of x and y are the same (or rather both being either non-negative or non-positive). Typically, if a language has support for both modulo and remainder, `Mod` has the same sign as the divisor/denominator and the remainder the same sign as the dividend/numerator, see this historic version of the Wikipedia page: https://en.wikipedia.org/w/index.php?title=Modulo_operation&oldid=764138354 The new version of the page use the terms floored (modulo) and truncated (remainder): https://en.wikipedia.org/wiki/Modulo_operation There is also a Euclidean modulo operation, where the result is always non-negative. The Python operation `%` corresponds to the modulo/floored version, as do SymPy's `Mod`.

It may make sense to add a `Rem` function to SymPy, if nothing else to simplify printing of these things (by rewriting to the version that is supported in the particular language) and to clarify the difference between these.

| x | y | mod(x, y) | rem(x, y) |
|--|--|--------|-----|
| 5 | 3 | 2 | 2|
| -5 | 3 | 1 | -2 |
| 5 | -3 | -1 | 2 |
| -5 | -3 | -2 | -2 |

To rewrite `Mod(x, y)` to `Rem`, one can use `Rem(Rem(x, y) + y,  y)` (unless one know that x and y are both non-negative or non-positive, then it is just `Rem(x, y)`).

**Comment by bjodah** [comment]
Just to complicate things further: C99 defines a function called [remainder](https://en.cppreference.com/w/c/numeric/math/remainder), which for 5.0, 3.0 gives -1.0.
Fortran 77 has `mod` which is essentially "rem" here, and Fortran 90+ has `modulo` which is our "mod".

A suitable place for a designated class for code printing might be in `sympy.codegen.ast`.

**Comment by asmeurer** [comment]
It would be good to be able to distinguish the two, but I don't think we should use the names Mod and Remainder to do so. I don't think it will be obvious at all that they are different or which is which, and it's not a standard convention as far as I'm aware for the two to mean those things (see also [np.remainder](https://numpy.org/doc/stable/reference/generated/numpy.remainder.html)). I think it would be better to add a keyword argument to Mod to allow the different behaviors, which would either return separate FloorMod, TruncatedMod, etc. class or just be stored in the `args`. Or we could just add those classes directly in the codegen module.

**Comment by oscargus** [comment]
Numpy made a bad choice there... Going against `math.remainder` and, what they even explicitly name, behaving as the modulus operator in Python.

Well, all language that has named two functions called something like mod and rem follows this convention. But, e.g. Fortran has mod and modulo, and many languages only support one of them.

**Comment by asmeurer** [comment]
I agree that it's weird when NumPy sometimes uses a completely different name for the function version of an operator for no apparent reason. They do this in many other places too.

But even so, I don't see this is a good way to differentiate these two concepts. Names like FloorMod and TruncatedMod are much clearer (and even those names could probably be improved).

**Comment by asmeurer** [comment]
This Wikipedia article gives four different conventions and uses pretty good names for them: floored, truncated, Euclidean, and rounded https://en.wikipedia.org/wiki/Modulo_operation

**Comment by asmeurer** [comment]
I also would have preferred if we hasn't used the name Rem for the reasons outlined above.
