### ISSUE TITLE
evalf(), .n or N of Point2D produces error. 

### ISSUE THREAD

**Issue by mjfwest** [sympy/sympy#22109]
The following code produces the error `TypeError: evalf() got multiple values for argument 'n'`.  I would expect it to produce `𝑃𝑜𝑖𝑛𝑡2𝐷(6,6)`

```python
from sympy import N, symbols
from sympy.geometry import Point2D, Segment2D

a,b,c = symbols('a,b,c')

eq1 = a + b + c
subs = {a:1,b:2,c:3}
eq1.n(n=5, subs=subs)

eq2 = a * b * c
eq2.n(n=5, subs=subs)

p = Point2D(eq1 ,eq2)
p.n(n=5, subs=subs)
```

**Comment by oscarbenjamin** [comment]
Probably `Point2D` should subclass `EvalfMixin` rather than define its own `.evalf` method. Otherwise a quick fix to the evalf method could be:
```diff
diff --git a/sympy/geometry/point.py b/sympy/geometry/point.py
index 858cd44..a005e84 100644
--- a/sympy/geometry/point.py
+++ b/sympy/geometry/point.py
@@ -446,7 +446,7 @@ def equals(self, other):
             return False
         return all(a.equals(b) for a, b in zip(self, other))
 
-    def evalf(self, prec=None, **options):
+    def evalf(self, *args, **options):
         """Evaluate the coordinates of the point.
 
         This method will, where possible, create and return a new Point
@@ -474,7 +474,7 @@ def evalf(self, prec=None, **options):
         Point2D(0.5, 1.5)
 
         """
-        coords = [x.evalf(prec, **options) for x in self.args]
+        coords = [x.evalf(*args, **options) for x in self.args]
         return Point(*coords, evaluate=False)
 
     def intersection(self, other):
```

**Comment by praneethratna** [comment]
> Probably `Point2D` should subclass `EvalfMixin` rather than define its own `.evalf` method. Otherwise a quick fix to the evalf method could be:
> 
> ```diff
> diff --git a/sympy/geometry/point.py b/sympy/geometry/point.py
> index 858cd44..a005e84 100644
> --- a/sympy/geometry/point.py
> +++ b/sympy/geometry/point.py
> @@ -446,7 +446,7 @@ def equals(self, other):
>              return False
>          return all(a.equals(b) for a, b in zip(self, other))
>  
> -    def evalf(self, prec=None, **options):
> +    def evalf(self, *args, **options):
>          """Evaluate the coordinates of the point.
>  
>          This method will, where possible, create and return a new Point
> @@ -474,7 +474,7 @@ def evalf(self, prec=None, **options):
>          Point2D(0.5, 1.5)
>  
>          """
> -        coords = [x.evalf(prec, **options) for x in self.args]
> +        coords = [x.evalf(*args, **options) for x in self.args]
>          return Point(*coords, evaluate=False)
>  
>      def intersection(self, other):
> ```

Since it has its own `evalf` method will change the argument name from `prec` to `n` works?

**Comment by oscarbenjamin** [comment]
> Since it has its own `evalf` method , changing the argument name from `prec` to `n` works.

That could also be done. The proper fix is to delete this method and subclass `EvalfMixin`.

**Comment by mjfwest** [comment]
Also, the following doesn't work for Segment2D, but with a different error.
```python
from sympy import N, symbols
from sympy.geometry import Point2D, Segment2D

a,b,c = symbols('a,b,c')

eq1 = a + b + c
subs = {a:1,b:2,c:3}
eq1.n(n=5, subs=subs)

eq2 = a * b * c
eq2.n(n=5, subs=subs)

p = Point2D(eq1 ,eq2)
q = Point2D(eq2 ,eq1)
seg = Segment2D(p,q)
seg.evalf(n=5, subs=subs)
```

Gives the error `AttributeError: 'Point2D' object has no attribute '_eval_evalf'`
Is this related enough to be filed in the same issue?

**Comment by oscarbenjamin** [comment]
> Is this related enough to be filed in the same issue?

Yeah, I think so. Basically all of these classes should inherit from `EvalfMixin`.
