### ISSUE TITLE
Feature request: use **kwargs for subs() and evalf()

### ISSUE THREAD

**Issue by normanius** [sympy/sympy#22108]
I consider the following example a bit hard to read.

```python
x,y,t = symbols("x y t")
expr = x**2 + y**2

expr.subs([(x,t+1), (y,2)])
expr.evalf(subs={x:t+1, y:2})
```

Wouldn't it be more intuitive if the following was possible?

```python
expr.subs(x=t+1, y=2)
expr.evalf(x=t+1, y=2)
```

This request requires subs() and evalf() to be extended such that they support key-word arguments: subs(**kwargs), evalf(**kwargs)

I don't know the sympy package too well. However, I expect that the [class `EvalfMixin`](https://github.com/sympy/sympy/blob/770107bb70af3f262b86ab09a9ccee7d459ceb3d/sympy/core/evalf.py#L1420) and the function [_subs()](https://github.com/sympy/sympy/blob/770107bb70af3f262b86ab09a9ccee7d459ceb3d/sympy/core/basic.py#L959) would have to be modified such that they first check if the kwargs-keys (if strings) match with symbol names (or expressions) used in the current expression. This might be a not so trivial task.

**Comment by oscarbenjamin** [comment]
In Python keyword arguments to a function call are translated to strings e.g.:
```python
>>> def f(**kwargs):
...     print(kwargs)
... 
>>> f(x=1)
{'x': 1}
>>> f(x**2=1)
  File "<stdin>", line 1
SyntaxError: keyword can't be an expression
```
The function f would not be able to receive a symbol or other expression for substitution.

The `subs=` argument to evalf is unfortunate. I would prefer that a dict of substitution values be provided as a first positional argument and that all other parameters should be keyword only. That can't really be changed now though.

For `subs` I think that the best format is:
```python
expr.subs({x:t+1, y:2})
```

**Comment by normanius** [comment]
I agree. For expressions, this request does not make sense a lot and I would be fine to suppress expression-substitution altogether:

```python
# This should not be supported.
expr.subs(**{"x**2":1}
```

The substitution of a variable with a number, however, is very common and I think the requested improvement would be intuitive.

Couldn't it be possible in `EvalifMixIn.evalf()` to merge the content of the `subs` argument with kwargs as follows:

```
subs = {} if subs is None else subs
atom_names = {a.name: a for a in expr.atoms() if hasattr(a, "name")}
for key, value in kwargs.items():
    if key in subs:
        # raise or warn or ignore: a variable-subsitution was declared twice
        pass
    if key not in atom_names:
        # raise or warn: it is possible to substitute only atomic expressions through kwargs
    subs[atom_names[key]] = value
```

Something similar could be done with the function `subs()`.

**Comment by normanius** [comment]
Addition: I just noticed that

```python
expr.subs({x:t+1, y:2})
```

already is supported, and I agree that this is more intuitive than `expr.subs([(x,1), (y:2)]`. This probably should be changed in the tutorial, though.

From a user perspective, it would be good if `evalf()` and `subs()` keep a similar interface.

**Comment by oscarbenjamin** [comment]
> Couldn't it be possible in `EvalfMixIn.evalf()` to merge the content of the `subs` argument with kwargs as follows:

What if two symbols have the same name?

```python
In [1]: x1, x2 = symbols('x, x', cls=Dummy)

In [2]: x1
Out[2]: x

In [3]: x2
Out[3]: x

In [4]: x1.name
Out[4]: 'x'

In [5]: x2.name
Out[5]: 'x'

In [6]: x1 == x2
Out[6]: False
```
String input to `subs` should not be allowed.

**Comment by normanius** [comment]
Thanks for pointing this out. I again have to admit that I'm not an expert user of sympy.

If it is common to use different python variables x1 and x2 that point to the same math symbol x it can indeed be misleading to substitute by name.

However, isn't it natural to substitute by name rather than by symbol?

```python
x,y,z = symbols("x x x")
expr = x+y+z      # => 3*x
expr.subs({z:3})  # => 9
```

While semantically, everything makes sense, it is not very reader friendly. Setting "z" to 3 turns an expression "3*x" into "9" can be surprising. 

But I agree that accepting kwargs where the keys will address variables by name can be misleading and possibly violate the API design of sympy. Please close this feature request if it doesn't make sense at this point.

**Comment by oscarbenjamin** [comment]
Maybe the tutorial should be improved to show using a dict.

> However, isn't it natural to substitute by name rather than by symbol?

Sometimes it is necessary to make a symbol that is not the same as any other symbol even if it has the same name. That's what `Dummy` is for. Also symbols with the same name but different assumptions are not interchangeable. Generally symbols should be treated as opaque and strings should not be used.

**Comment by normanius** [comment]
Summary: because kwargs are represented as strings, it is not feasible to follow up on this feature request => close!

**Comment by asmeurer** [comment]
subs does sort of support this already

```py
>>> (x + y).subs(dict(x=1, y=2))
3
```

In other words, if the dict passed to subs has string keys, they are converted to symbol names. This is a convenience, but I wouldn't recommend it outside of interactive use for the reasons Oscar stated. The biggest issue with strings is that they don't include information like assumptions. 

```py
>>> x = Symbol('x', real=True)
>>> (x + y).subs(dict(x=1, y=2))
x + 2
```

Additionally, subs has some actual keyword arguments which would clash if we used `**kwargs`.
