### ISSUE TITLE
Broken link in the documentation section on the Introduction-to-contributing webpage

### ISSUE THREAD

**Issue by dominiclopes** [sympy/sympy#22129]
The link  http://docs.sympy.org/latest/guide.html on the webpage https://github.com/sympy/sympy/wiki/Introduction-to-contributing#documentation is not found

**Comment by oscarbenjamin** [comment]
Marking as easy to fix. Anyone can edit the wiki

**Comment by anutosh491** [comment]
I'll take this one .Thanks

**Comment by anutosh491** [comment]
The SymPy Guides/How-to Guides section is present in the SymPy 1.10.dev/1.9.dev versions but wasn't accompanied with the latest release . Hence two links weren't pointing to any address resulting in "Page Not Found" error. I have fixed those links .The changes can be reviewed and the issue can be closed .

**Comment by 0sidharth** [comment]
Closing this as @anutosh491 has edited the wiki. Thanks!
