### ISSUE TITLE
arbitrary function inversion

### ISSUE THREAD

**Issue by joeyskeys** [sympy/sympy#22132]
Is there any way to get the inverse function of any given expr?
For example:

```
x = symbols('x')
y = x ** 2

inverse(y, x)
# This function suppose to give the result x = sqrt(y)
```

**Comment by sylee957** [comment]
No, but you can use `solve` or `solveset`

**Comment by smichr** [comment]
cf [here](https://stackoverflow.com/questions/60854658/finding-the-inverse-of-a-function-in-python-possibly-using-sympy/60855622#60855622) for an example and similar question
