### ISSUE TITLE
Problem with solving simple separable ODE

### ISSUE THREAD

**Issue by nickme68** [sympy/sympy#22155]
I want to solve by SymPy simple separable equation y'=e^(y-x), but SymPy can't solve it!
```
from sympy import *
x = symbols("x")
y = Function("y")
eq = Eq(Derivative(y(x), x), exp(y(x)-x))
dsolve(eq, y(x))
```
But it solves successfuly similar equation y'=e^(y+x).

Follоwing code
```
eq = Eq(Derivative(y(x), x), exp(y(x)-x))
print(classify_ode(eq,y(x)))
```
returns

`('factorable', 'separable', '1st_power_series', 'lie_group', 'separable_Integral')
`

The method for 'factorable' seems broken. Explicitly using the second method,

`dsolve(eq, y(x), hint='separable')
`

quickly returns the correct solution.

For the second equation y'=e^(y+x), the list of methods is

`('separable', '1st_power_series', 'lie_group', 'separable_Integral')
`

so in this case the problematic method 'factorable' is not used. 

Experiments have shown that those equations cannot be solved if their exponents have a minus sign.

**Comment by oscarbenjamin** [comment]
The problem is that the factorable hint calls `dsolve` recursively but for this example ODE the recursive call will also end up being handled by factorable again leading to infinite recursion. It looks like the last line here is intended to prevent the infinite recursion:
https://github.com/sympy/sympy/blob/19b187982f90c868b987a8bbea085874647c98aa/sympy/solvers/ode/single.py#L897-L902
That check fails though because the expressions being compared are unequal:
```
903  ->	                return fraction(factor(self.eqs[0]))[0]-eq!=0
904  	            return True
905  	        for i in factors:
906  	            if i.has(f(x)):
907  	                self.eqs.append(i)
908  	        return len(self.eqs)>0 and len(factors)>1
(Pdb) p self.eqs[0]
-exp(-x + y(x)) + Derivative(y(x), x)
(Pdb) p fraction(factor(self.eqs[0]))[0]
Derivative(y(x), x) - exp(-x)*exp(y(x))
(Pdb) p eq
exp(x)*Derivative(y(x), x) - exp(y(x))
```
The ultimate fix is that factorable should not be a solver hint and should just be part of the preprocessing done by dsolve. Maybe for now that check could be improved. This diff fixes the example shown:
```diff
diff --git a/sympy/solvers/ode/single.py b/sympy/solvers/ode/single.py
index 7523b45..a3e5c42 100644
--- a/sympy/solvers/ode/single.py
+++ b/sympy/solvers/ode/single.py
@@ -892,14 +892,8 @@ def _matches(self):
             if len(self.eqs)>0:
                 return True
         roots = solve(eq, df)
-        if len(roots)>0:
+        if len(roots)>1:
             self.eqs = [(df - root) for root in roots]
-            if len(self.eqs)==1:
-                if order>1:
-                    return False
-                if self.eqs[0].has(Float):
-                    return False
-                return fraction(factor(self.eqs[0]))[0]-eq!=0
             return True
         for i in factors:
             if i.has(f(x)):

```
That might potentialy cause problems in other cases though. I'm not sure I understand the logic of this code.

**Comment by nickme68** [comment]
By the way [online version](https://live.sympy.org/) of SymPy (version 1.5.1) solves this kind of equations correctly!

**Comment by mohajain** [comment]
I would like to help

**Comment by oscarbenjamin** [comment]
> I would like to help

You could try applying the diff I showed as a PR to see if it breaks any of the tests.

**Comment by oscarbenjamin** [comment]
> By the way [online version](https://live.sympy.org/) of SymPy (version 1.5.1) solves this kind of equations correctly!

Using `git bisect` shows that this was working until 1a26cdd3230b543775c77ba2493500166c0ff984 from  #18623

**Comment by oscarbenjamin** [comment]
CC @Mohitbalwani26

**Comment by Mohitbalwani26** [comment]
> CC @Mohitbalwani26

Looking into it. Thanks

**Comment by mohajain** [comment]
@oscarbenjamin  Sure

**Comment by Mohitbalwani26** [comment]
@mohajain are you trying this?
Also i think this diff will work : 
```diff
--- a/sympy/solvers/ode/single.py
+++ b/sympy/solvers/ode/single.py
@@ -875,13 +875,13 @@ class Factorable(SingleODESolver):
     has_integral = False

     def _matches(self):
-        eq = self.ode_problem.eq
+        orig_eq = self.ode_problem.eq
         f = self.ode_problem.func.func
         x = self.ode_problem.sym
         order =self.ode_problem.order
         df = f(x).diff(x)
         self.eqs = []
-        eq = eq.collect(f(x), func = cancel)
+        eq = orig_eq.collect(f(x), func = cancel)
         eq = fraction(factor(eq))[0]
         factors = Mul.make_args(factor(eq))
         roots = [fac.as_base_exp() for fac in factors if len(fac.args)!=0]
@@ -899,7 +899,7 @@ def _matches(self):
                     return False
                 if self.eqs[0].has(Float):
                     return False
-                return fraction(factor(self.eqs[0]))[0]-eq!=0
+                return fraction(factor(self.eqs[0]))[0]-eq!=0 and simplify(orig_eq - fraction(factor(self.eqs[0]))[0])!=0
             return True
         for i in factors:
             if i.has(f(x)):
```

**Comment by Mohitbalwani26** [comment]
we just need to make sure that the `orig_eq` and the equation formed by `fraction(factor(self.eqs[0]))[0]` is equal.

**Comment by oscarbenjamin** [comment]
Something like this is better:
```diff
diff --git a/sympy/solvers/ode/single.py b/sympy/solvers/ode/single.py
index 7523b45..31ea3d2 100644
--- a/sympy/solvers/ode/single.py
+++ b/sympy/solvers/ode/single.py
@@ -875,13 +875,13 @@ class Factorable(SingleODESolver):
     has_integral = False
 
     def _matches(self):
-        eq = self.ode_problem.eq
+        eq_orig = self.ode_problem.eq
         f = self.ode_problem.func.func
         x = self.ode_problem.sym
         order =self.ode_problem.order
         df = f(x).diff(x)
         self.eqs = []
-        eq = eq.collect(f(x), func = cancel)
+        eq = eq_orig.collect(f(x), func = cancel)
         eq = fraction(factor(eq))[0]
         factors = Mul.make_args(factor(eq))
         roots = [fac.as_base_exp() for fac in factors if len(fac.args)!=0]
@@ -894,13 +894,9 @@ def _matches(self):
         roots = solve(eq, df)
         if len(roots)>0:
             self.eqs = [(df - root) for root in roots]
-            if len(self.eqs)==1:
-                if order>1:
-                    return False
-                if self.eqs[0].has(Float):
-                    return False
-                return fraction(factor(self.eqs[0]))[0]-eq!=0
-            return True
+            # Avoid infinite recursion
+            matches = self.eqs != [eq_orig]
+            return matches
         for i in factors:
             if i.has(f(x)):
                 self.eqs.append(i)
```
I think that some tests for `classify_ode` will need to be updated.

**Comment by mohajain** [comment]
> Something like this is better:
> 
> ```diff
> diff --git a/sympy/solvers/ode/single.py b/sympy/solvers/ode/single.py
> index 7523b45..31ea3d2 100644
> --- a/sympy/solvers/ode/single.py
> +++ b/sympy/solvers/ode/single.py
> @@ -875,13 +875,13 @@ class Factorable(SingleODESolver):
>      has_integral = False
>  
>      def _matches(self):
> -        eq = self.ode_problem.eq
> +        eq_orig = self.ode_problem.eq
>          f = self.ode_problem.func.func
>          x = self.ode_problem.sym
>          order =self.ode_problem.order
>          df = f(x).diff(x)
>          self.eqs = []
> -        eq = eq.collect(f(x), func = cancel)
> +        eq = eq_orig.collect(f(x), func = cancel)
>          eq = fraction(factor(eq))[0]
>          factors = Mul.make_args(factor(eq))
>          roots = [fac.as_base_exp() for fac in factors if len(fac.args)!=0]
> @@ -894,13 +894,9 @@ def _matches(self):
>          roots = solve(eq, df)
>          if len(roots)>0:
>              self.eqs = [(df - root) for root in roots]
> -            if len(self.eqs)==1:
> -                if order>1:
> -                    return False
> -                if self.eqs[0].has(Float):
> -                    return False
> -                return fraction(factor(self.eqs[0]))[0]-eq!=0
> -            return True
> +            # Avoid infinite recursion
> +            matches = self.eqs != [eq_orig]
> +            return matches
>          for i in factors:
>              if i.has(f(x)):
>                  self.eqs.append(i)
> ```

I have tested this diff and all the tests are working. Should I open a PR for this?

**Comment by oscarbenjamin** [comment]
Yes, go ahead
