### ISSUE TITLE
Integration of sin(x)**2 won't evaluate if 2 is a float or Decimal

### ISSUE THREAD

**Issue by MiguelGuthridge** [sympy/sympy#22154]
Refer to example input:

```py
In [1]: integrate(sin(x)**2, x)
Out[1]:
x   sin(x)⋅cos(x)
─ - ─────────────
2         2

In [2]: from decimal import Decimal

In [3]: integrate(sin(x)**Decimal(2), x)
Out[3]:
⌠
⎮    2.0
⎮ sin   (x) dx
⌡

In [4]: integrate(sin(x)**2.0, x)
Out[4]:
⌠
⎮    2.0
⎮ sin   (x) dx
⌡
```

If I'm missing something, a quick link to the docs where this is explained would be great! It just seems that this logic doesn't make much sense to me.

**Comment by smichr** [comment]
Floats are inexact and thus 2.0 is not the same as 2 as far as integration is concerned. If you integrate with an exponent of 2.1 it will remain unevaluated, too.

**Comment by MiguelGuthridge** [comment]
Oh cool that makes sense, thanks!
