### ISSUE TITLE
When I pprint(y), why does sympy not continue multiplying the () () expressions?

### ISSUE THREAD

**Issue by NSC9** [sympy/sympy#22174]
`#!/usr/bin/env python
# coding: utf-8

# In[1]:

from IPython.display import Image
from IPython.core.display import HTML 
from sympy import *; x,h,y = symbols("x h y")
Image(url= "https://i.imgur.com/cbI4LpK.png")

# In[2]:

x0 = 3; y0 = 0.9   #storing our point data in code
F = lambdify(x,(3*x)/(x+7))   #representing our function 
F(x)

# In[15]:

m = diff(F(x))

# In[21]:

y = m*(x - x0) + y0
y

# In[ ]:

`

**Comment by oscarbenjamin** [comment]
I don't really understand your point. Maybe you just need to use `expand`. Here's a copy/paste from `isympy`:
```python
In [1]: from IPython.display import Image
   ...: from IPython.core.display import HTML
   ...: from sympy import *; x,h,y = symbols("x h y")

In [2]: x0 = 3; y0 = 0.9 #storing our point data in code
   ...: F = lambdify(x,(3*x)/(x+7)) #representing our function
   ...: F(x)
Out[2]: 
 3⋅x 
─────
x + 7

In [3]: m = diff(F(x))

In [4]: m
Out[4]: 
    3⋅x        3  
- ──────── + ─────
         2   x + 7
  (x + 7)         

In [5]: y = m*(x - x0) + y0
   ...: y
Out[5]: 
        ⎛    3⋅x        3  ⎞      
(x - 3)⋅⎜- ──────── + ─────⎟ + 0.9
        ⎜         2   x + 7⎟      
        ⎝  (x + 7)         ⎠      

In [7]: expand(y)
Out[7]: 
          2                                            
       3⋅x              9⋅x          3⋅x            9  
- ────────────── + ────────────── + ───── + 0.9 - ─────
   2                2               x + 7         x + 7
  x  + 14⋅x + 49   x  + 14⋅x + 49    
```
If you are just asking for help with using sympy then github issues is not the right place.
