### ISSUE TITLE
When I pprint(y), why does sympy not continue multiplying the () () expressions?

### ISSUE THREAD

**Issue by NSC9** [sympy/sympy#22173]
[picture of my code](https://i.imgur.com/jf3m60N.png)

[picture of problem](https://i.imgur.com/cbI4LpK.png)

**Comment by oscarbenjamin** [comment]
An image is not a good way to show code to someone. Sending just a link to the picture is even worse. I'm unwilling to click the links and I'm just going to close this as invalid. If you are looking for help rather than reporting a bug then use StackOverflow.
