### ISSUE TITLE
Simple limit crashes

### ISSUE THREAD

**Issue by mmsbrggr** [sympy/sympy#22181]
Tried versions: 1.7, 1.8. 1.9rc1

```python
from sympy import *

expression = sympify("(-1)**n * 2**(-n)")
print(limit(expression, Symbol("n"), oo))
```

The limit of `(-1)**n * 2**(-n)` as `n` to `oo` is obviously `0`, but sympy crashes.

**Comment by 0sidharth** [comment]
It seems that currently `(-1)**(1/n)` (1/n as sympy substitutes to bring n->0) is rewritten as `exp(I*pi/n)` and `2**(1/n)` is rewritten as `exp(log(2)/n)` which leads to the `NotImplementedError` with `(-log(2) + I*pi)`

**Comment by mmsbrggr** [comment]
I don't quite understand. How is `(-1)**(1/n)` and `2**(1/n)` related to the limit I am trying to solve?

**Comment by mmsbrggr** [comment]
> It seems that currently `(-1)**(1/n)` (1/n as sympy substitutes to bring n->0) is rewritten as `exp(I*pi/n)` and `2**(1/n)` is rewritten as `exp(log(2)/n)` which leads to the `NotImplementedError` with `(-log(2) + I*pi)`

I don't quite understand. How is `(-1)**(1/n)` and `2**(1/n)` related to the limit I am trying to solve?

**Comment by jksuom** [comment]
Alternating sequences like `(-1)**n * 2**(-n)` are handled by `limit_seq` that restricts `n` to integers. It should be used for such sequences. The factor `(-1)**n` is a discontinuous complex function of `n` if that is allowed to take arbitrary real values. There is no general support for limits of such functions in SymPy.

**Comment by mmsbrggr** [comment]
> Alternating sequences like `(-1)**n * 2**(-n)` are handled by `limit_seq` that restricts `n` to integers. It should be used for such sequences. The factor `(-1)**n` is a discontinuous complex function of `n` if that is allowed to take arbitrary real values. There is no general support for limits of such functions in SymPy.

Perfect. Thanks, `limit_seq` does the job. I was confused as `limit` did not work even when I added `integer=True` as an assumption to the symbol `n`.
