### ISSUE TITLE
Can't import sympy

### ISSUE THREAD

**Issue by LeCoqHardi** [sympy/sympy#22190]
>>> from sympy import *
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'sympy'

How can I fix that please ? Of course before I did "pip install sympy" and it was successfully installed.

Thanks :)

**Comment by oscarbenjamin** [comment]
This is some problem with your setup like you have multiple Python installations and you've installed sympy in one but run the code in another. This is not a sympy issue.
