### ISSUE TITLE
Move bottom_up and walk to simplify.traversaltools and move that file elsewhere

### ISSUE THREAD

**Issue by oscargus** [sympy/sympy#22204]
I've started to nest a bit in the import dependencies and one thing that will at least not make it harder is to move `bottom_up` and `walk` (and maybe more?) to `simplify.traversaltools`. On the other hand, it seems like these functions should maybe not be in `simplify` at all, but in `core` or `utilities` as they do not really rely on anything in `simplify` (they do hardly rely on anything from Sympy).

Then, the questions is where they should end up?

I assume that this involves deprecating the current locations as part of it.

**Comment by oscargus** [comment]
There are also the `strategies` which has a `bottom_up` as well. Are these related in any way? (Looks like it, but not fully clear.)

Seems like `use` from `simplify.traversaltools` is not used in the code base.

**Comment by oscargus** [comment]
In addition, the `walk` function in `Basic.replace` looks very similar to `bottom_up`, except for some arguments. Would it make sense to merge these?

**Comment by oscarbenjamin** [comment]
These could maybe be moved to basic.py to go alongside `preorder_traversal`. They could then be reimported back to where they were previously defined.

A problem I've found when trying to restructure imports is that the core imports sympy.logic.

**Comment by oscargus** [comment]
OK! Will move it to `basic.py`, but will let the tests of #22206 finish to see if anything else breaks.

Yes, parts of logic (`boolalg.py`) should maybe reside in `core`, but I seem to recall that it is not so easy to sort out for other import reasons...

**Comment by oscarbenjamin** [comment]
A `traversal.py` module is also fine

**Comment by oscarbenjamin** [comment]
> Yes, parts of logic (`boolalg.py`) should maybe reside in `core`, but I seem to recall that it is not so easy to sort out for other import reasons...

I think the root of the problem is the fact that Symbol subclasses Boolean. A subclass relationship needs a full non-delayed import.
