### ISSUE TITLE
Bug in the evaluation of a log limit

### ISSUE THREAD

**Issue by falematte** [sympy/sympy#22220]
![image](https://user-images.githubusercontent.com/25055204/135870730-d6592bc8-2ae6-446a-9db3-78e3aed5efd2.png)
The limit is evaluated differently at the discontinuity points. In one case (atan) right and left limits are different while in the other they are evaluated the same.

**Comment by 0sidharth** [comment]
Is `i` here the square root of negative one? Could you add a SymPy code snippet that shows the issue?

**Comment by oscarbenjamin** [comment]
Please don't send images. You can use isympy in a terminal or in spyder or something and then just copy/paste both equations and the code e.g.:
```python
In [12]: from sympy import *

In [13]: x = Symbol('x')

In [14]: expr = exp(sin(x**2))

In [15]: expr
Out[15]: 
    ⎛ 2⎞
 sin⎝x ⎠
ℯ       

In [16]: expr.limit(x, 0)
Out[16]: 1
```
Then the code can be copy/pasted.

**Comment by falematte** [comment]
Yes it is! I can also post a .py. Here it is:

```
from sympy import *
init_printing()

#lines required to generate the function needed
r, R0, Delta, delta_prime = symbols('r R_0 Delta Delta_d', real=True, positive=True)
L = symbols('L', positive=True)
theta_0 = symbols('theta_0', real=True)
m = Matrix([[cos(theta_0)-delta_prime, -r* sin(theta_0)],[sin(theta_0), r*cos(theta_0)]])
  
matrix_s_alpha_inverted = simplify(m**-1)
  
R_ = R0 + r* cos(theta_0) - Delta
  
inverse_of_J_s_alpha = simplify((-matrix_s_alpha_inverted[2]*matrix_s_alpha_inverted[1]+ matrix_s_alpha_inverted[3]*matrix_s_alpha_inverted[0])/ R_)
J_s_alpha = inverse_of_J_s_alpha**-1  
integrand = simplify(J_s_alpha/R_**2)

#first expression to compare
exp_without_atan = simplify(simplify(integral_with_delta_eq_0).subs(R0, r+L))
# second expression to compare (equivalent to the first one except for a constant term)
exp_equiv_with_atan = ( 2*r/(sqrt(L) * sqrt(L+ 2*r)))* atan(tan(theta_0/2)*sqrt(L)/sqrt(L+2*r) )
  

#plot to verify the equivalence
#plot(exp_equiv_with_atan.subs(r, 0.2).subs(L,2), exp_without_atan.subs(r, 0.2).subs(L,2), (theta_0, -2*pi, 2*pi))


# I show that the limit of the first expression give the correct result

limit(exp_equiv_with_atan.subs(r, 0.2).subs(L,2), theta_0, -pi, '-').evalf()
limit(exp_equiv_with_atan.subs(r, 0.2).subs(L,2), theta_0, -pi, '+').evalf()

# these limits they instead give 0

limit(exp_without_atan.subs(r, 0.2).subs(L,2), theta_0, -pi, '+').evalf()
limit(exp_without_atan.subs(r, 0.2).subs(L,2), theta_0, -pi, '-').evalf()

#these limits should have different values from right or from left.

```

**Comment by oscarbenjamin** [comment]
What is `integral_with_delta_eq_0`?

**Comment by falematte** [comment]
> What is `integral_with_delta_eq_0`?

Sry, I forgot to paste a line. Now everything should be self-contained.

**Comment by jksuom** [comment]
The limit of `log` at `-oo` has only been implemented for the principal branch. Hence the two log-terms have the same asymptotic form as `tan(theta/2)` tends to `-oo` though they should differ by `2*pi*I`, This is the same issue as in e.g. https://github.com/sympy/sympy/issues/21721,

**Comment by falematte** [comment]
> The limit of `log` at `-oo` has only been implemented for the principal branch. Hence the two log-terms have the same asymptotic form as `tan(theta/2)` tends to `-oo` though they should differ by `2*pi*I`, This is the same issue as in e.g. #21721,

Thank you for the answer. I got your point!

In my opinion, the problem is rather urgent since the original integral is quite simple and can come up in a number of practical application. Therefore either this integral is not anymore  solved using the logarithms either we will have wrong results in a whole class of expressions.

**Comment by falematte** [comment]
Just to add a remark to my last message. The fact that the limits of this function  are wrong results in a wrong evaluation of  a bunch of indefinite and definite integrals. This is how I spotted the bug. I wasn't interessed in the limit by itself. This is why I think that this bug is serious. It is better to have sympy that does not give you a result, e.g. integrate not giving any results, that having wrong results.

**Comment by oscarbenjamin** [comment]
Can you show the integral examples?

**Comment by falematte** [comment]
In te previous snippet:
`integrate(integrand.subs(Delta, 0).subs(delta_prime, 0), theta_0, conds='none')`

if you try instead to integrate from -pi to pi you get 0. This is wrong.

**Comment by falematte** [comment]
This is somehow related to https://github.com/sympy/sympy/issues/3735

**Comment by torhans** [comment]
Maybe a simpler example:

```
from sympy import *
a=Symbol(r'a', real=True)
x=Symbol(r'x')
print(integrate(1/((1+(x-a)**2)*(1+x**2)),(x,-oo,oo)))
#>0
#Wolfram Alpha gives: 2*pi/(a**2+4)  for ( -1 < imag(a) < 1)
#https://www.wolframalpha.com/input/?i=integrate%281%2F%28%281%2B%28x-a%29%5E2%29*%281%2Bx%5E2%29%29%2Cx%2C-infinity%2Cinfinity%29
import sympy
print(sympy.__version__)
#>'1.9'
```
Which I expect boils down to the following problem

`
expr=log(x-I)-log(-x-I)
expr2=logcombine(expr,force=True)
print(expr2)
#> log((x - I)/(-x - I))
print(limit(expr,x,oo))
#> -I*pi
print(limit(expr2,x,oo))
#> I*pi
limit(expr,x,oo)==limit(expr2,x,oo)
#> False
`

**Comment by anutosh491** [comment]
> Maybe a simpler example:
> Which I expect boils down to the following problem
> 
> expr=log(x-I)-log(-x-I)
> expr2=logcombine(expr,force=True)
> print(expr2)
> #> log((x - I)/(-x - I))
> print(limit(expr,x,oo))
> #> -I*pi
> print(limit(expr2,x,oo))
> #> I*pi
> limit(expr,x,oo)==limit(expr2,x,oo)
> #> False

I've noticed this multiple times and I had also opened an issue for the same related to another expression . The thing is that, limit of an expression mainly at `oo/-oo` differ drastically from limits of the expression simplified in different forms, this includes `logcombine`, `powsimp`, `trigsimp`, `expand` and all of that . Like it won't be very tough to find `limit(expr , x, oo)` and `limit(expr.trigsimp/ expr.powsimp , x, oo )` giving different results .
. I would surely like to fix this but honestly speaking I don't know of anything that could ensure consistency among all expressions which are eventually same at the core . May @jksuom could hep us with this by pointing out what could be done to ensure consistency between limits which are one and the same

**Comment by anutosh491** [comment]
The above question boils down to something like this `expr = (-log(tan(x/2) - I) +log(tan(x/2) + I))`  or maybe `log((tan(x/2) + I)/(tan(x/2) - I))`, if limit at pi/-pi can be correctly addressed for this we are done . I don't think the leading term implementing is correct and it should be corrected 

```
>>> expr = (-log(tan(x/2) - I) +log(tan(x/2) + I))
>>> # while calculating limit at pi we would need shifting by pi so...
>>> expr.subs(x, x + pi)
-log(-cot(x/2) - I) + log(-cot(x/2) + I)
>>> _.as_leading_term(x)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\anuto\sympy\sympy\sympy\core\cache.py", line 70, in wrapper
    retval = cfunc(*args, **kwargs)
  File "C:\Users\anuto\sympy\sympy\sympy\core\expr.py", line 3447, in as_leading_term
    obj = self._eval_as_leading_term(x, logx=logx, cdir=cdir)
  File "C:\Users\anuto\sympy\sympy\sympy\core\add.py", line 1073, in _eval_as_leading_term
    n0 = min.getn()
  File "C:\Users\anuto\sympy\sympy\sympy\core\expr.py", line 1288, in getn
    raise NotImplementedError('not sure of order of %s' % o)
NotImplementedError: not sure of order of log(-1/x)
```
The answer we would want here is `2*I*pi`

**Comment by anutosh491** [comment]
> ```
> expr=log(x-I)-log(-x-I)
> expr2=logcombine(expr,force=True)
> print(expr2)
> #> log((x - I)/(-x - I))
> print(limit(expr,x,oo))
> #> -I*pi
> print(limit(expr2,x,oo))
> #> I*pi
> limit(expr,x,oo)==limit(expr2,x,oo)
> #> False
> ```

I realize through my comment and this one that a check would be responsible for this , check this out . So my comment involved something like above involved `series` and `leading term` computation of `log(-cot(x/2) - I)`
![image](https://user-images.githubusercontent.com/87052487/160238423-91da447c-fd1b-4ac0-9df9-ae35b7d19eae.png)

This is graph for the above written expression and the clearly the `imaginary part` is `negative` at `0` though the `real part` tends to `oo`.
So if we see sympy results 
```
>>> expr = log(-cot(x/2) - I)
>>> limit(expr, x, 0)
oo
>>> expr.series(x, cdir = 1)
I*pi + log(2) - log(x) + I*x/2 + x**2/24 + x**4/2880 + O(x**6)
```
Here the first term is `I*pi` but it should be negative (`-I*pi`) and hence this seems to be an error due to this block (line 1051- 1054)
```
        if a.is_real and a.is_negative and im(cdir) < 0:
            res -= 2*I*S.Pi
```
Now our `cdir` is 1 and we need to allow for im(cdir) <=0 to subtract `2*I*S.Pi` and get the correct result. 
After making the change we have the following . This would also solve the error you've made note of 
```
>>> expr.series(x, cdir = 1)
-I*pi + log(2) - log(x) + I*x/2 + x**2/24 + x**4/2880 + O(x**6)
>>> limit(log(x-I)-log(-x-I), x, oo)
I*pi
>>> limit(log((x - I)/(-x - I)), x, oo)
I*pi
```

**Comment by jksuom** [comment]
I have briefly described the expected behavior of `log._eval_as_leading_term` at the origin in [this comment](https://github.com/sympy/sympy/issues/22453#issuecomment-967249025). Its behavior at `-oo` should be similar under the transformation `z -> 1/z` that will map `-oo+` to `0-`.

**Comment by anutosh491** [comment]
> I have briefly described the expected behavior of `log._eval_as_leading_term` at the origin in [this comment](https://github.com/sympy/sympy/issues/22453#issuecomment-967249025). Its behavior at `-oo` should be similar under the transformation `z -> 1/z` that will map `-oo+` to `0-`.

Yeah the idea would be somewhat similar to what I wrote above ! Will try out all possible approaches .

**Comment by anutosh491** [comment]
> expr=log(x-I)-log(-x-I)

> I have briefly described the expected behavior of `log._eval_as_leading_term` at the origin in [this comment](https://github.com/sympy/sympy/issues/22453#issuecomment-967249025). Its behavior at `-oo` should be similar under the transformation `z -> 1/z` that will map `-oo+` to `0-`.

Okay so the fix I was proposing was through the `_eval_nseries` method and eventually getting it through `grutnz ` , but your comment prompts that we could get this through leading term too ! I'll probably go for both , I am quite happy with the above wolfram approach I prompted . Gives us lot of clarity when to subtract I*Pi and when to not . I'll analyze your method more in depth too !
