### ISSUE TITLE
1.9 is not on PyPI

### ISSUE THREAD

**Issue by yurivict** [sympy/sympy#22235]
https://pypi.org/project/sympy/

**Comment by oscarbenjamin** [comment]
Yes, I just haven't quite finished the release. It took longer than expected and then I became busy at work...

**Comment by oscarbenjamin** [comment]
The release issue is #22008 so we don't need this one

**Comment by asmeurer** [comment]
I guess people are confused because there is a tag pushed to GitHub. Was that a mistake? We should push the tags and the packages at the same time so that everything is in sync.
