### ISSUE TITLE
bug with symbols

### ISSUE THREAD

**Issue by Antonio-Costa00** [sympy/sympy#22246]
from fractions import Fraction
from pprint import pprint
from sympy import *
import numpy as np

> symbols('x')
> 
> g = 9.81; y0 =100;  v0 = 55; m = 80; c = 15
> 
> y = y0 + (m / c) * (v0 + m * g / c) * (1 - exp((c / m) * x)) - (m * g / c) * x
> print('Equation:')
> print("y(x) =", y)

The error: 

NameError: name 'x' is not defined
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
/tmp/ipykernel_8162/2957177485.py in <module>
      3 g = 9.81; y0 =100;  v0 = 55; m = 80; c = 15
      4 
----> 5 y = y0 + (m / c) * (v0 + m * g / c) * (1 - exp((c / m) * x)) - (m * g / c) * x
      6 print('Equation:')
      7 print("y(x) =", y)

NameError: name 'x' is not defined

However, when I do this in another cell
> h, l = symbols('h l')
 
I can run my code 

Equation:
y(x) = -52.32*h - 572.373333333333*exp(0.1875*h) + 672.373333333333

**Comment by smichr** [comment]
When you use `var('x')` a Python name `x` is assigned to `Symbol('x')`; `symbols` does not do this, so all you did is create a `Symbol` object but didn't assign it to any Python variable...so it's undefined. Try
```python
x = symbols('x')
```

**Comment by Antonio-Costa00** [comment]
> When you use `var('x')` a Python name `x` is assigned to `Symbol('x')`; `symbols` does not do this, so all you did is create a `Symbol` object but didn't assign it to any Python variable...so it's undefined. Try
> 
> ```python
> x = symbols('x')
> ```



> When you use `var('x')` a Python name `x` is assigned to `Symbol('x')`; `symbols` does not do this, so all you did is create a `Symbol` object but didn't assign it to any Python variable...so it's undefined. Try
> 
> ```python
> x = symbols('x')
> ```



> When you use `var('x')` a Python name `x` is assigned to `Symbol('x')`; `symbols` does not do this, so all you did is create a `Symbol` object but didn't assign it to any Python variable...so it's undefined. Try
> 
> ```python
> x = symbols('x')
> ```

That's true. Thank you for the help. The code is running now.

**Comment by Antonio-Costa00** [comment]
That's true. Thank you for the help.
