### ISSUE TITLE
The test function need to be updated, No module named 'sympy.integrals.rubi.rubi'

### ISSUE THREAD

**Issue by hanqing0521** [sympy/sympy#22274]
`sympy.test("rubi_tests",blacklist=[])` return  No module named 'sympy.integrals.rubi.rubi'.
As far as I know,  it should be sympy.integrals.rubi.rubimain, please change the files in RubiFolder/rubi_tests/tests .

**Comment by ayushk7102** [comment]
I would like to work on this issue
