### ISSUE TITLE
Unexpected False condition

### ISSUE THREAD

**Issue by marouane-miftah** [sympy/sympy#22333]
Using:
sympy 1.9
python 3.9.7

```
from sympy.abc import a
condition = (a <= 2019) & (a == 2019)
print(condition)
```
Why is this condition False while clearly a = 2019 is a solution to the above?

Thanks

**Comment by praneethratna** [comment]
`==` is for exact structural testing which basically means we are asking if `a = b` .
The condition is False as `a` is type of Sympy Symbol.
```
>>> from sympy.abc import a
>>> type(a)
<class 'sympy.core.symbol.Symbol'>
```
But if you define `a` as Sympy Integer it will return `True`.
```
>>> from sympy import Integer
>>> a = Integer(2019)
>>> type(a)
<class 'sympy.core.numbers.Integer'>
>>> (a <= 2019) & (a == 2019)
True
```
