### ISSUE TITLE
`Tr` moved from `core` to `physics.quantum`

### ISSUE THREAD

**Issue by oscargus** [sympy/sympy#22330]
See discussion in  #22297.

**Comment by ellisonbg** [comment]
The above linked PR was merged, can this issue be closed or are there still tasks to complete before the issue can be closed?

**Comment by oscarbenjamin** [comment]
It used to be necessary to create an issue like this to be linked to from the deprecation warning but that isn't needed any more because we have sections in the docs e.g.:
https://docs.sympy.org/latest/explanation/active-deprecations.html#sympy-core-trace
