### ISSUE TITLE
How to plot vector in sympy 1.9

### ISSUE THREAD

**Issue by fxb342** [sympy/sympy#22378]
I have been scouring the documentation and other sources (stackoverflow, google) for information on how I could plot a 2D vector. I saw in recent update to 1.9, a new Vector module was introduced. Looking through the examples in the docs I saw that a 3D Cartesian coordinate system could be called on. For my purposes I just have a x,y coordinate vector that I would like to show via plot function or on some Cartesian graph, but I can't seem to find any usable documentation on this. Does anyone know how I could show a simple vector (e.g [3,2] ) on a plot?

**Comment by oscarbenjamin** [comment]
I don't  know what you mean by "plot a vector". Do you mean that you want to draw an arrow? If so just use matplotlib:
https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.arrow.html

This does not seem a valid issue for SymPy so I'm going to close it. Please use the mailing list, stackoverflow or GitHub discussions to ask questions about using SymPy.
