### ISSUE TITLE
Implementing raising and lowering operator in sympy.physics.quantum

### ISSUE THREAD

**Issue by dw61** [sympy/sympy#22382]
I am learning quantum mechanics this semester and use sympy frequently. We are covering angular momentum raising and lowering [operators](https://en.wikipedia.org/wiki/Ladder_operator) for spin half particles. I read the documentations for sympy.physics.quantum and there seems to be no implementation. How feasible is it to implement this computation?

[e.g.](https://easyspin.org/easyspin/documentation/spinoperators.html)
for spin-1/2 particles, J+ = hbar/2 * Matrix([[0, 1], [0, 0]])
for spin-1 particles, J+ = hbar*sqrt(2) * Matrix([[0, 1, 0], [0, 0, 1], [0, 0, 0]])
Similar for for spin-3/2 particles and more

Thanks!

**Comment by oscarbenjamin** [comment]
I don't know the answer to your question but this should go to the mailing list rather than being a GitHub issue.
