### ISSUE TITLE
sympy.vector.divergence gives incorrect answers in cylindrical coordinates

### ISSUE THREAD

**Issue by fountain23** [sympy/sympy#22384]
I have discovered an issue with sympy.vector.divergence function, when used in cylindrical coordinates.

Sometimes it gives correct answers, but sometimes is gives incorrect answers.

See the example below.  

divergence( 1 * rhat )  returns 0, when it should return 1/R
divergence( R * rhat ) returns 2, the correct answer.

```
from sympy.vector import CoordSys3D, divergence

N = CoordSys3D('N', transformation='cylindrical', vector_names=("r", "phi", "z"), variable_names=("R", "PHI", "Z"))

#  Variables
R = N.R
PHI = N.PHI
Z = N.Z

#  Basis Unit Vectors
rhat = N.r
phihat = N.phi
zhat = N.z

print( divergence( R * rhat )
#  2   correct answer
print( divergence( 1 * rhat )
#  0  WRONG!!  should be 1/R

```

**Comment by oscarbenjamin** [comment]
If you don't rename the vectors then they are apparently `i`, `j` and `k`:
```python
In [4]: from sympy.vector import CoordSys3D, divergence
   ...: 
   ...: N = CoordSys3D('N', transformation='cylindrical')

In [5]: N.base_vectors()
Out[5]: (i_N, j_N, k_N)
```
Does the vectors code actually understand that these should be the cylindrical unit vectors rather than the Cartesian ones?

**Comment by fountain23** [comment]
It would appear so.  divergence() gives correct answers in cylindrical coordinates for various polynomials I have tried, for example:
divergence( R**3 * rhat )
#  4 R^2

So it seems to be using the correct formula for divergence in cylindrical coordinates.  I looked at the divergence() source code.  There is not specific code for cylindrical coordinates.  Rather, it does a general case transformation for any curvilinear coordinate system, by using lame coefficients.

divergence() works properly when there is a variable, R, in the argument, but it gives wrong answers when given only a constant.

divergence( R * rhat )  #  2 correct
divergence( 7 * rhat )  #  0 Wrong!  should be 7/R

My first guess would be that the divergence() code is trying to use some attribute that it expects to be part of a variable (i.e. R._CoordSys), but can't find it when passed a constant.
