### ISSUE TITLE
singledispatch as a replacement for the current printing system

### ISSUE THREAD

**Issue by ThePauliPrinciple** [sympy/sympy#22387]
In https://github.com/sympy/sympy/pull/22365 @oscarbenjamin suggested that `singledispatch` from `functools` might be able to replace the current printing system, solving several of its issues.

I have attempted a start at such a replacement, however, there are currently some unfornate issues that might make this not a good idea at this time:
- `singledispatchmethod` was only introduced in python 3.8, so can not be used until support for 3.7 is dropped
- Single dispatch uses annotations and while forward annotations are possible, `singledispatchmethod` still needs the class available during class instantiation, this could cause severe circular import issues
- Subclassing does not currently work with `singledispatchmethod` directly, a `_print` method would need to be defined in every subclass of `Printer` (and then running the printing capabilities of the parent with super())

I am looking for both more potential issues as well as solutions to any of the raised issues.

Here is an example of how to use single dispatch in python (3.8):

```python
from functools import singledispatchmethod
class sympysingledispatchmethod(singledispatchmethod):
    def __get__(self, obj, cls=None):
        def _method(*args, **kwargs):
            if getattr(self,'dispatch_hook',False):
                hook=getattr(obj,self.dispatch_hook)
                if hasattr(args[0],hook):
                    return getattr(args[0],hook)(obj,*args[1:],**kwargs)
            method = self.dispatcher.dispatch(args[0].__class__)
            return method.__get__(obj, cls)(*args, **kwargs)

        _method.__isabstractmethod__ = self.__isabstractmethod__
        _method.register = self.register
        update_wrapper(_method, self.func)
        return _method

class cls(): 
    def _printmethod(self,printer):
        print("dispatch hook",printer)
class cls2(): pass
class cls3(): pass

class Printer():
    printMethod='_printmethod'

    @sympysingledispatchmethod
    def _print(self,obj):
        print('fall back')
    _print.dispatch_hook="printMethod"

    @_print.register
    def _(self,obj:cls2):
        print('got cls2')

Printer()._print(cls())
Printer()._print(cls2())
Printer()._print(cls3())


class subPrinter(Printer):
    @sympysingledispatchmethod
    def _print(self,obj):
        print('fall back to parent class... ',end='')
        return super()._print(obj)
    _print.dispatch_hook="printMethod"

    @_print.register
    def _(self,obj:cls2):
        print('subclassed')
subPrinter()._print(cls2())
subPrinter()._print(cls3())
Printer()._print(cls2())
```
```
dispatch hook <__main__.Printer object at 0x7fd7dcc142d0>
got cls2
fall back
subclassed
fall back to parent class... fall back
got cls2
```
Sidenote: the `singledispatchmethod` can also just be directly copied for lower versions of python:
```python
from functools import singledispatch,update_wrapper


class singledispatchmethod:
    """Single-dispatch generic method descriptor.
    Supports wrapping existing descriptors and handles non-descriptor
    callables as instance methods.
    """

    def __init__(self, func):
        if not callable(func) and not hasattr(func, "__get__"):
            raise TypeError(f"{func!r} is not callable or a descriptor")

        self.dispatcher = singledispatch(func)
        self.func = func

    def register(self, cls, method=None):
        """generic_method.register(cls, func) -> func
        Registers a new implementation for the given *cls* on a *generic_method*.
        """
        return self.dispatcher.register(cls, func=method)

    def __get__(self, obj, cls=None):
        def _method(*args, **kwargs):
            method = self.dispatcher.dispatch(args[0].__class__)
            return method.__get__(obj, cls)(*args, **kwargs)

        _method.__isabstractmethod__ = self.__isabstractmethod__
        _method.register = self.register
        update_wrapper(_method, self.func)
        return _method

    @property
    def __isabstractmethod__(self):
        return getattr(self.func, '__isabstractmethod__', False)
```
```

**Comment by oscarbenjamin** [comment]
There is also sympy's vendored multiple dispatch module.

I think at some point the printing code for all the different classes was located with the classes but then it was refactored to put all the printing code in one place. The centralised printing code then needs to know about all of different classes to be printed which is not good.

A better approach would be if the detailed printing code was centralised but the printers were still extensible from outside. For example you could have something like:
```python
# in sympy/printing:

class ArrayPrint:
    def __init__(self, rows, cols, entries):
        ...

class PrettyPrinter:
    # Some dispatch mechanism for ArrayPrint and detailed code for printing a 2D array

class StrPrinter:
    # different code for printing an ArrayPrint

# in sympy/matrices:

class Matrix:
    def _pretty_print(self):
        return ArrayPrint(self.rows, self.cols, self.tolist())
```
This way the detailed printing code for exactly how to pretty print is located in printers but a class like Matrix can still describe how to print itself without needing to add code to the printing module. The complicated parts of printing can then be centralised but the printers are still extensible from outside.

**Comment by ThePauliPrinciple** [comment]
In the SymPy multidispatch, would it be possible to delay the lookup of the class from the annotation until the first time the dispatch is actually performed? That might solve the importing issue.

**Comment by ThePauliPrinciple** [comment]
Using abstract baseclasses, it is also possible to have the dispatch be based on the name and module of the class:
```python
from sympy.multipledispatch import dispatch
from abc import ABC

class undefinedABC(ABC):
    pattern={'__name__':'undefined'}
    #this should also included '__module__' for any
    #SymPy classes to avoid any name clashes
    #Ideally this is generated for all SymPy classes
    #using a script, with the docstring set to something
    #along the lines of:
    """
    Abstract baseclass for {self.pattern['__name__']} in module
    {self.pattern['__module__']} with docstring {docstring of the sympy class}
    """
    @classmethod
    def __subclasshook__(cls,C):
        for key, value in cls.pattern.items():
            if not getattr(C,key,None) == value:
                return NotImplemented
        return True

class Printer():
    @dispatch()
    def _print(self, obj: int):
        print('int:', obj)

    @dispatch()
    def _print(self, obj: float):
        print('float:',obj)

    @dispatch()
    def _print(self, obj: list):
        print('list:')
        for i in obj:
            self._print(i)

    @dispatch()
    def _print(self, obj: undefinedABC):
        print('undefined')

class undefined: pass


class subPrinter(Printer):

    @dispatch()
    def _print(self, obj: float):
        print('subclass float:', obj)

    @dispatch()
    def _print(self, obj: object):
        super()._print(obj)

Printer()._print([1,[0.1]])
Printer()._print(undefined())
subPrinter()._print([1,[0.1]])
```

I really dislike having to redefine the same function name every time though. Imagine a situation where you wish to print an object the same way as the parent class in some cases (depending on the value) and in a different way than the parent class for other cases. This now requires code duplication since the printing for the printing function for the parent class might already be redefined. So different names would be better (but the name should not be used to determine how to dispatch). I think it is possible to do this with the SymPy dispatcher by using the class rather than the wrapper function, but I am not sure how.

If the names are unique, it is then also possible to do the dispatch decoration with a metaclass e.g.
```python
class Printer(metaclass=SympyClassDispatcherMeta,dispatchers=['print']):
...
```
Could indicate that it should put any method with name "_print_*" under the "_print" dispatcher. 

It would still be a concert whether the parent class of the printer should take priority or whether the parent class of the object being printed should take priority (e.g. if an `Expr` is being printed, but no method for `Expr` is present in the printer, should it look for `Expr` in the parent printer, or for `Basic` in the printer first). Currently the `object` dispatch in the above example will make it work like the former, but the latter could be set up by the metaclass by adding methods like
```python
@dispatch
def _print_Expr(self,obj: Expr):
    return super()._print_Expr(obj)
```
Whenever such a method is available in a parent class

Then all that is needed is 
- checking if the object being printed already has an appropriate printing method and use that instead
- some method to keep track of the "printing level" `_print_level` (pre-dispatch/post-dispatch method in the `Dispatcher` class?)
- annotate all printing methods

This would leave the current code more or less as-is except for annotations (which should be introduced anyways), but now dispatches based on class (or class name + module in case of circular imports) rather than class and method name matching

**Comment by oscarbenjamin** [comment]
I don't think we need a special dispatching mechanism. Object-oriented single dispatch can generally be done with methods. The only reason it isn't like that now for the printers is because it was problematic to distribute the detailed code for formatting strings and handling alignment, brackets and other things. 

The approach I suggest above solves all of these problems by making it possible to centralise the detailed printing code and reduce duplication while still allowing the printers to be extensible from outside.

The situation where single dispatch is useful is if you want to dispatch on classes that you don't control like `int`, `list` etc. There could be a single dispatch mechanism for those I suppose but most the classes handled by the printers are Basic subclasses and they could just have their own `_pretty_print` methods.

**Comment by ThePauliPrinciple** [comment]
I was working under the impression that whatever dispatching was being done, it should still allow for the current format in addition to anything new, so that user defined custom printers/ custom printing methods in classes can still be used in exactly the same way. Surely that should be a requirement.

In that case, I don't see how one can avoid custom dispatching, since you need to figure out if you have to deal with `object._pretty_print` or `Printer._print_Class`, which is exactly the special dispatching that I feel is required (on top of that, `_print_level` should be increased as `_print` is being called recursively).

**Comment by oscarbenjamin** [comment]
Any changes would need to be backwards compatible somehow but if we're looking for a better structure then we should go all the way perhaps by introducing new Printer classes and making the old ones depend on the new or something.

**Comment by ThePauliPrinciple** [comment]
Alright, since there is already work being done on the printing system I will close this issue.
