### ISSUE TITLE
Upgrading to 1.9 broke assumptions with evaluate=False

### ISSUE THREAD

**Issue by proy87** [sympy/sympy#22428]
The following code worked in 1.8:
```
from sympy.core.parameters import evaluate
from sympy.abc import x, h
f=2**x**7
with evaluate(False):
    fh=f.xreplace({x: x+h})
    bool(fh.exp.is_rational)
```

But in 1.9 it raises `TypeError: invalid input: Mod(1*(2*0) + 1*(1*1), (1*1)*(1*2))`

**Comment by oscarbenjamin** [comment]
I had a quick debug of this and I can see that there are things that could be done but it also makes me think that maybe doing anything nontrivial in `evaluate(False)` is probably not something that can really be made to work.
