### ISSUE TITLE
Increase the usage of augmented assignment statements

### ISSUE THREAD

**Issue by elfring** [sympy/sympy#22440]
:eyes: Some source code analysis tools can help to find opportunities for improving software components.
:thought_balloon: I propose to [increase the usage of augmented assignment statements](https://docs.python.org/3/reference/simple_stmts.html#augmented-assignment-statements "Augmented assignment statements") accordingly.

Would you like to integrate anything from a transformation result which can be generated by a command like the following?
(:point_right: Please check also for questionable change suggestions because of an evolving search pattern.)
```
[Markus_Elfring@fedora lokal]$ perl -p -i.orig -0777 -e 's/^(?<indentation>\s+)(?<target>\S+)\s*=\s*\k<target>[ \t]*(?<operator>[+\-%&|^@]|\*\*?|\/\/?|<<|>>)/$+{indentation}$+{target} $+{operator}=/gm' $(find ~/Projekte/sympy/lokal -name '*.py')
```

:crystal_ball: How will the development interests evolve further also according to update candidates in 504 lines of this software?

**Comment by oscarbenjamin** [comment]
I don't understand what this issue is about

**Comment by elfring** [comment]
:thought_balloon: Can you follow [the rationale from the Python enhancement proposal 203](https://www.python.org/dev/peps/pep-0203/#rationale "Proposal for augmented assignments") (from 2000-07-13)?

**Comment by oscarbenjamin** [comment]
Your posts look like they are generated by a bot. If you are an actual human then please say so. Please explain what the purpose of this issue is because the text above is not sufficient for anyone to meaningfully do anything.

**Comment by elfring** [comment]
* :thought_balloon: I hope that the provided information can get more software development attention.
  How much do you understand the referenced data sources?
* Do any factors hinder the wider application of [functionality which became generally available with Python 2](https://docs.python.org/3/whatsnew/2.0.html#augmented-assignment "Augmented assignments")? :thinking:

**Comment by oscarbenjamin** [comment]
I blocked the account and reported it as spam to GitHub
