### ISSUE TITLE
Acceptance of Symbols in Rational()

### ISSUE THREAD

**Issue by toaster-code** [sympy/sympy#22442]
I would like to build a rational but when it envolves symbols like 'x' or even "pi", is gives a type error.

Example:
```Python
import sympy as sym
sym.pprint(sym.Rational(1/10))

>1/2
```
Now with a symbol:
```Python
import sympy as sym
PI  = sym.Symbol('PI')
sym.pprint(sym.Rational(PI/2))

>lib\site-packages\sympy\core\numbers.py in __new__(cls, p, q, gcd)
   1624 
   1625                 if not isinstance(p, Rational):
-> 1626                     raise TypeError('invalid input: %s' % p)
   1627 
   1628             q = 1

TypeError: invalid input: PI/2
```

It should be possible to allow symbols so fractions could be represented like PI/2, etc.

Note: I know it is doable by removing symbols from Rational() method ( by doing `Rational(1/2)*PI )` , but this means each time I would like to represent an equation built in execution time I would need to check for symbols and remove them beforehand.

**Comment by ThePauliPrinciple** [comment]
Since a rational number is defined as a ratio of integer numbers, pi can't be a part of a rational, so this should certainly not be allowed. 

A case could be made for allowing a symbol in `Rational` if and only if the symbol is a Rational itself (`assert symbol.is_Rational == True`), although I don't see why this would ever be needed.

I would be surprised if there is no solution in SymPy for what you are trying to do, I just don't think that solution is related to `Rational`.

**Comment by toaster-code** [comment]
> Since a rational number is defined as a ratio of integer numbers, pi can't be a part of a rational, so this should certainly not be allowed.
> 
> A case could be made for allowing a symbol in `Rational` if and only if the symbol is a Rational itself (`assert symbol.is_Rational == True`), although I don't see why this would ever be needed.
> 
> I would be surprised if there is no solution in SymPy for what you are trying to do, I just don't think that solution is related to `Rational`.

I agree with you about PI when thinking on it as PI, but if I consider pi as a symbol (like x = Symbol('x') ), why not allow this to be done? I dont know if it is difficult do be done or not, so I would consider this issue as 'suggestion' instead of a bug.

**Comment by ThePauliPrinciple** [comment]
Because you could end up with a `Rational` object that is in fact not a rational.
> so I would consider this issue as 'suggestion

I don't think there is an issue here at all. 

> but this means each time I would like to represent an equation built in execution time I would need to check for symbols and remove them beforehand.

I think this can be done with the SymPy library already, just not with `Rational`. Can you give an example of what you are trying to accomplish without mentioning `Rational`? Surely there is no demand for the use of `Rational`.

**Comment by toaster-code** [comment]
Thank you @ThePauliPrinciple for your time.

The need is very simple indeed. My request was to allow Rational to deal with constants (like pi) automatically. I managed to avoir this problem by filtering (using if) to check if there is a constant before using Rational().
My code is very big to share, but I am using `Rational(a)` where `a` is only a float number multiplied by PI, or may be an integer, or only a float number. When it's a float times pi it is directly exposed as a symbol, like:

```
import sympy as sym
pi = sym.Symbol('pi')
a = 0.3333333*pi
#sometimes a = float number like 0.666666 or 0.5, or even an integer like 0 or 1...
Rational(a)
>TypeError


```

To avoid that error I've put an if to find if `a` is of type sympy.core.symbol.Symbol :
```

if type(a) is sym.core.mul.Mul:
   if (type(a/x) is sym.core.numbers.Float) or (type(a/x) is sym.core.numbers.Integer):
        return sym.Rational(a/x)
elif (type(a) is sym.core.numbers.Float) or (type(a) is sym.core.numbers.Integer):
   return sym.Rational(a)
else:
    raise Exception('Error')

```

**Comment by ThePauliPrinciple** [comment]
Maybe this helps:
```python
from sympy import Symbol,nsimplify

pi = Symbol('pi')
expr=nsimplify(0.3333333*pi)
print(expr)
print(type(expr.args[0]))
```

**Comment by toaster-code** [comment]
This sure helps! I am not expert in this package and despite still thinking that Rational could do the job I am happy with the alternative. Thank you very much for your time.
:)
