### ISSUE TITLE
Remove unused release scripts

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#22471]
We should remove the unused release scripts in release/. I know the fabfile is not used any more (and hasn't been in a really long time). Is rever.xsh still used at all @oscarbenjamin? If not, we should remove it too. Otherwise it's confusing, e.g., when a dependency is updated and it appears to be relevant in these scripts but it isn't.

**Comment by oscarbenjamin** [comment]
Yes, I'm not sure if everything from the old scripts has been included in the new scripts but I don't use the old ones in the release at all. Maybe I should just move everything except the new scripts into an `old` folder or something.

**Comment by asmeurer** [comment]
We should just delete them. If we need code from the old scripts we can retrieve it from the git history. I did a similar thing with the fabfile when I upgraded to rever, and that file is still there even now. But all it has ever done is confuse people when they grep for some dependency that changed or something similar. 

I was going to make a PR for this but I wanted confirmation first that the rever script is indeed not used at all. Since that seems to be the case, I'm going to go ahead and do this.

**Comment by asmeurer** [comment]
Actually, if rever is indeed not used at all any more, that means the release/README file is completely out of date. So maybe it would be better if you did this (if you have a change), because that needs to be updated with the current process. Ideally everything in the release process should be documented to the point that someone who has never done a release before can do it (assuming they have the proper access).

**Comment by oscarbenjamin** [comment]
Yes, the instructions need to be updated. I haven't finished making changes to the process and I was planning to update the README once I was happy with the process. The main thing I wanted to fix was updating the authors file.

**Comment by oscarbenjamin** [comment]
I will clean things up as part of the 1.11 release.

**Comment by oscarbenjamin** [comment]
Fixed in #23791. Instructions are being updated in #23780.
