### ISSUE TITLE
Benchmarks builds are failing on CI

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#22479]
The benchmarks build has been failing on GitHub Actions. This is the error:

```
Run asv machine --yes --config asv.conf.actions.json
  asv machine --yes --config asv.conf.actions.json
  shell: /usr/bin/bash -e {0}
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.9.8/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.9.8/x64/lib
· Config file /home/runner/work/sympy/sympy/asv.conf.json not found.
```

The first build to have the failure seems like an unrelated change https://github.com/sympy/sympy/actions/workflows/runtests.yml?query=branch%3Amaster+event%3Apush. I'm not sure what exactly broke. There haven't been any pushes to the benchmarks repo recently, and asv hasn't been updated recently either.

**Comment by smichr** [comment]
dup #22459
