### ISSUE TITLE
nan + MatExpr -> ?

### ISSUE THREAD

**Issue by smichr** [sympy/sympy#22482]
Is there are  reason to not let `nan + MatExpr` collapse to `nan`?

From the test suite:
```python
    z = zeros(2)
    ...
    a = Add(z, S.NaN)
    # assert a == Add(S.NaN, z) # See the XFAIL above
    assert isinstance(a, Add)
    assert a.args == (S.NaN, z)
```

**Comment by praneethratna** [comment]
Why is `Add(z, S.NaN)` is not `nan` while `Add(S.NaN, z)` returns `nan` ? should'nt both return the same output?

**Comment by sylee957** [comment]
I think that it is already collapsing to `NaN` in `Add` and raises error in `MatAdd` constrion
