### ISSUE TITLE
latex print, the exponent is too far from the base

### ISSUE THREAD

**Issue by leslielee619** [sympy/sympy#22511]
i use 'sp.pprint' want to print $A^2$ ranther than A**2，but sympy print is very ugly, the exponent is too far from the base.

![图片](https://user-images.githubusercontent.com/27109334/142176993-8e47cc60-2773-4d9b-b4dd-0026a871e8af.png)

i think its sympy's problem, not ide, because i run code in spyder and pycharm and their console and notebook, its same.  

the code as follows:
```
# -*- coding: utf-8 -*-
"""
@time: 2021-11-17 下午 02:37
@author: leslie lee
"""
import sympy as sp

I, B, A, b0, b1 = sp.symbols('I, B, A, b0, b1')

def ietration(b0, b1):
    sp.pprint(b1)
    sp.pprint(sp.expand(B*b0 + A*b1))
    print('-'*50)
    return b1, sp.expand(B*b0 + A*b1)

for i in range(10):
    b0, b1 = ietration(b0, b1)
```

**Comment by oscarbenjamin** [comment]
Do you have a specific proposal for how to improve this using unicode/ascii in a monospace font?

Otherwise my suggestion is to use a latex-based viewer e.g. you can use a jupyter notebook and use `display` instead of `pprint`.

**Comment by ThePauliPrinciple** [comment]
Sympy is definately able to print the latex code that you are looking for.
In google Colab:
![afbeelding](https://user-images.githubusercontent.com/35560762/142187126-1ba2370a-d048-46fa-bc43-ba8fc0ec129f.png)

**Comment by leslielee619** [comment]
> 
> 
> Sympy is definately able to print the latex code that you are looking for. In google Colab: ![afbeelding](https://user-images.githubusercontent.com/35560762/142187126-1ba2370a-d048-46fa-bc43-ba8fc0ec129f.png)

**Comment by leslielee619** [comment]
> 
> 
> Do you have a specific proposal for how to improve this using unicode/ascii in a monospace font?
> 
> Otherwise my suggestion is to use a latex-based viewer e.g. you can use a jupyter notebook and use `display` instead of `pprint`.

i have no suggestion, im used to using pycharm, not notebook or colab, so i copy the sympy latex print in a it blog website.

**Comment by leslielee619** [comment]
> 
> 
> Sympy is definately able to print the latex code that you are looking for. In google Colab: ![afbeelding](https://user-images.githubusercontent.com/35560762/142187126-1ba2370a-d048-46fa-bc43-ba8fc0ec129f.png)

I just

**Comment by oscarbenjamin** [comment]
> i copy the sympy latex print into a it blog website.

That sounds like the best approach to me. You can render the LaTex with Mathjax

**Comment by leslielee619** [comment]
> That sounds like the best approach to me. You can render the LaTex with Mathjax  

thank you. 

yesterday, i just think its a bug, so i create a issue. actually i have no need to use sympy print latex in IDE, there are a lot of alternatives.

save the note in website is very convient, you can see your note in anywhere, anytime. i often use CSDN, a china blog website, it also allow you write a private note, this website use katex+markdown.
i also install texlive+texmaker in my pc.
