### ISSUE TITLE
evalf factors a constant

### ISSUE THREAD

**Issue by proy87** [sympy/sympy#22512]
`((x - 2)**2).evalf()` returns `4.0*(0.5*x - 1)**2`.
Shouldn't it be just `(x-2)**2` ?

**Comment by smichr** [comment]
Evalf will always attempt to convert Integers to Floats and when it does so in a Pow, it makes the base canonical wrt constants -- the largest coeff in the base will be 1 (which will be recast to Float when `x` is given a value because of the 0.5.

**Comment by smichr** [comment]
cf #16762
