### ISSUE TITLE
ode_2nd_power_series_ordinary returns expressions containing the coefficient variable r

### ISSUE THREAD

**Issue by Mentastin** [sympy/sympy#22525]
Running
```
eqn = 4.0*N*sqrt(N - 1)*rho(s) + (4*s**2*(N - 1) + (N - 2*s*(N - 1))**2)*Derivative(rho(s), (s, 2))
dsolve(eqn,rho(s), n=5)
```
with Sympy 1.8 yields the output
```
Eq(rho(s), -1.33333333333333*s**3*r(2.0)/N + 1.33333333333333*s**3*r(2.0) + C2*(1 - 2.0*s**2*sqrt(N - 1.0)/N) + C1*s*(1.0 - 0.666666666666667*s**2*sqrt(N - 1.0)/N) + O(s**5))
```
There should be no "r(2.0)" in this expression.

The issue seems to be solved by replacing ```sol = solve(teq, maxf)``` with ```sol = solve(teq, maxf, rational=True)``` on line 3465
and ```rhs = solve(req, maxf)``` with ```rhs = solve(req, maxf, rational=True)``` on line 3479.

Given that the rational=True flag should be default, I do not understand how this works. Maybe a separate / root issue?

The issue was also raised here: https://stackoverflow.com/questions/70022717/strange-r-appears-in-dsolve-output-using-sympy

**Comment by smichr** [comment]
see #22524 :-)
