### ISSUE TITLE
nfloat should not evaluate args of undefined functions

### ISSUE THREAD

**Issue by smichr** [sympy/sympy#22524]
When solving an expression with at least one Float, solve will convert all numbers to Floats -- even those in undefined functions. This [breaks the `ode` routines](https://stackoverflow.com/questions/70022717/strange-r-appears-in-dsolve-output-using-sympy/70027868?noredirect=1#comment123790934_70027868) and is (in general) a bad idea since there is no way to know what input a function wants -- maybe it only takes integer input.

e.g.
```python
>>> f=Function('f')
>>> var('x')
>>> eq=f(2)*4.0 + x
>>> solve(eq,x)
[-4.0*f(2.0)]
>>> (eq-x).n()
4.0*f(2)
```

Note in the last expression that `evalf` does not evaluate the arg of `f` -- and it shouldn't, perhaps in contradiction to sentiments in #20479 and referencing issues.

**Comment by Mentastin** [comment]
The function seems to behave correctly when setting ```rational=True```, even though it would seem from the docs that this should be the default behaviour and thus redundant:
```
>>> f=Function('f')
>>> var('x')
>>> eq=f(2)*4.0 + x
>>> solve(eq,x, rational=True)
[-4*f(2)]
```

**Comment by oscarbenjamin** [comment]
Where is the code that converts everything to Float?

**Comment by smichr** [comment]
> Where is the code that converts everything to Float?

#22524 (it is in `nfloat`)
