### ISSUE TITLE
sympy.limit

### ISSUE THREAD

**Issue by LKlinke** [sympy/sympy#22520]
```
test = sympy.S("-p0*s*(1 - sqrt(-c**2*t**2 + 1))/(c*t*(-1 + p0*s*(1 - sqrt(-c**2*t**2 + 1))/(c
*t))*(1 - p2)*(-c*p2 + 1))")
```

`test.limit("t", 1) == test.subs("t", 1)` should evaluate to True but does not. 

`test.subs("t", 1)` is the correct result also for the limit case ( `test.limit("t",1)` ).
(Wolframalpha, does evaluate the limit call correctly)

**Comment by anutosh491** [comment]
I guess you should also frame a better title for the issue than just sympy.limits . It's beneficial for everyone including newcomers...if you could maybe name your title precisely, according to the exact issue which you want to be addressed. Thank You for reporting !

**Comment by jksuom** [comment]
It seems that  `limit` and `subs` give two structurally different but mathematically equivalent expressions (`==` means structural equality).

**Comment by oscarbenjamin** [comment]
https://docs.sympy.org/latest/gotchas.html#double-equals-signs

**Comment by jksuom** [comment]
Closing as `limit` and `subs` are not expected to produce structurally equal results.
```
>>> test = S("-p0*s*(1 - sqrt(-c**2*t**2 + 1))/(c*t*(-1 + p0*s*(1 - sqrt(-c**2*t**2 + 1))/(c*t))*(1 - p2)*(-c*p2 + 1))")
>>> t = symbols('t')
>>> test.limit(t, 1).equals(test.subs(t, 1))
True
```
