### ISSUE TITLE
allow for specification of symbols for `Expr.as_coefficients_dict`

### ISSUE THREAD

**Issue by smichr** [sympy/sympy#22531]
On SO the question often arises about how to get the coefficients of terms in sum.
* [example1](https://stackoverflow.com/questions/22955888/how-to-extract-all-coefficients-in-sympy)
* [example2](https://stackoverflow.com/questions/69958709/collecting-sub-expressions-of-a-multivariate-polynomial-function-in-sympy/69959128?noredirect=1#comment123675865_69959128)
* [example3](https://stackoverflow.com/questions/70037738/how-to-get-the-coefficients-of-the-equation-in-sympy/70040012#70040012)

In one of the answers I suggested the following whose code:
```python
def codict(expr, *x):
  collected = Poly(expr, *x).as_expr()
  i, d = collected.as_independent(*x, as_Add=True)
  rv = dict(i.as_independent(*x, as_Add=False)[::-1] for i in Add.make_args(d))
  if i:
      assert 1 not in rv
      rv.update({S.One: i})
  return rv
```
Examples:
```python
>>> var('a x z y')
(a, x, z, y)
>>> expr = 3 + x + x**2 + a*x*2
>>> codict(expr, x)
{x**2: 1, x: 2*a + 1, 1: 3}
>>> codict(expr+y+z, x)
{x**2: 1, x: 2*a + 1, 1: y + z + 3}
>>> codict(expr+y+z, x,y)
{y: 1, x**2: 1, x: 2*a + 1, 1: z + 3}
>>> codict(expr+y+z, x,y,z)
{y: 1, z: 1, x**2: 1, x: 2*a + 1, 1: 3}
```
It might make sense to let this be renamed `as_coefficients_dict` so one may indicate the symbols of interest for the collection of coefficients.

In [example3](https://stackoverflow.com/questions/70037738/how-to-get-the-coefficients-of-the-equation-in-sympy/70040012#70040012) I showed how Polys can return the raw information about terms and their coefficients. It should be easy to create an "all_coeffs" response for a multivariate expression by returning 0 for any missing monomials and generating all monomials as partitions of the maximum order represented, n, in k variables, e.g. for `z**4 + x**2*y + 2*y**2` the maximum order is 4 and there are are three generators so all coefficients would correspond to monomials of:
```python
>>> Poly(Add(*[Mul(*i) for i in subsets([x]*4+[y]*4+[z]*4, 4)])).monoms()
[(4, 0, 0), (3, 1, 0), (3, 0, 1), (2, 2, 0), (2, 1, 1), (2, 0, 2), (1, 3, 0), (1, 2, 1), (1, 1, 2), (1, 0, 3), (0, 4, 0), (0, 3, 1), (0, 2, 2), (0, 1, 3), (0, 0, 4)]
```
<there's probably a better way of generating those or that Polynomial>

**Comment by oscarbenjamin** [comment]
I think this makes sense as an improvement of `as_coefficients_dict`. Also it would be better if it didn't return a defaultdict because those can be awkward in some situations.
