### ISSUE TITLE
give Expr a generic `base` and `exp` attribute

### ISSUE THREAD

**Issue by smichr** [sympy/sympy#22530]
Would it make sense to give Expr `base` and `exp` attributes so the base or exponent can be retrieved directly instead of having to select it from the tuple? `eq.base` instead of `eq.as_base_exp()[0]`?

**Comment by ThePauliPrinciple** [comment]
`git grep '\.base '` and `git grep 'def base('` show that this attribute is already used a throughout SymPy, but I don't think it always is in the same context. It might cause confusing. Although I do understand the convenience it would provide.

**Comment by anutosh491** [comment]
> `git grep '\.base '` and `git grep 'def base('` show that this attribute is already used throughout SymPy, but I don't think it always is in the same context.

Yeah I remember using `.base` and `.exp` in a previous Pr , hence my first take on this was that It's already implemented but now 
that you've pointed this out , I realize that it might not be be functioning consistently throughout sympy . Surely should be implemented for overall convenience and consistency .

**Comment by oscarbenjamin** [comment]
I think `as_base_exp` is fine for this. `Expr` already has too many attributes so I wouldn't want to add more unless they are really needed.

**Comment by smichr** [comment]
`as_base_exp()[0]` is only used 3 times...so let's keep it as is.

**Comment by ThePauliPrinciple** [comment]
perhaps `as_base_exp(base_only = True)` and `as_base_exp(exp_only = True)` could work as optional arguments? (at least it is easier to understand what is going on)
