### ISSUE TITLE
Powsimp fails to recognise negated Add exponent

### ISSUE THREAD

**Issue by oscarbenjamin** [sympy/sympy#22546]
From SO:
https://stackoverflow.com/questions/70073361/sympy-how-is-it-possible-to-simplify-power-of-sum

It should be possible for powsimp to combine the `n+1` and `n-1` powers:
```python
In [44]: x, y = symbols('x, y', positive=True)

In [45]: n = symbols('n', positive=True, integer=True)

In [46]: a = n + 1

In [47]: e = (x + y)**a / (x + 2*y)**a

In [48]: e
Out[48]: 
       n + 1          -n - 1
(x + y)     ⋅(x + 2⋅y)      

In [49]: powsimp(e)
Out[49]: 
       n + 1          -n - 1
(x + y)     ⋅(x + 2⋅y)      

In [50]: powsimp(e, force=True)
Out[50]: 
       n + 1          -n - 1
(x + y)     ⋅(x + 2⋅y)  
```
Without the `+1` it works:
```python
In [51]: a = n

In [52]: e = (x + y)**a / (x + 2*y)**a

In [53]: e
Out[53]: 
       n          -n
(x + y) ⋅(x + 2⋅y)  

In [54]: powsimp(e)
Out[54]: 
         n
⎛ x + y ⎞ 
⎜───────⎟ 
⎝x + 2⋅y⎠ 
```

**Comment by steph1611** [comment]
Do you think that modifying the line 393 in powsimp.py  (_exp_c, exp_t = e.as_coeff_Mul(rational=True_) 
to
exp_c, exp_t = factor_terms(e).as_coeff_Mul(rational=True)
is a solution ?

**Comment by smichr** [comment]
> is a solution ?

I was hoping for something like that...but I tried something different in my 22546 branch.

**Comment by smichr** [comment]
I opened a PR for this in #22578
