### ISSUE TITLE
Wrong use of isinstance in sympy/simplify/powersimp.py

### ISSUE THREAD

**Issue by ThePauliPrinciple** [sympy/sympy#22542]
Line 618 in sympy/simplify/powersimp.py reads `    if b.is_Pow or isinstance(b.func, exp) and e != 1:`. I don't think there is ever a case when `b.func` is an instance of `exp` (and if it was, it would be an incorrect use of `.func`).

I believe this is meant to read `b.func == exp` or `isinstance(b, exp)`.

**Comment by ThePauliPrinciple** [comment]
I also wonder if there are any instances of `exp` that do not have `.is_Pow == True`

**Comment by oscarbenjamin** [comment]
I'd go with `isinstance(b, exp)`
