### ISSUE TITLE
Evaluation of  "1/sqrt(x)==sqrt(1/x)" gives False.

### ISSUE THREAD

**Issue by xfliu** [sympy/sympy#22547]
As title, this is a very "simple" expression but gives wrong result.

``
>from __future__ import division
>from sympy import *
>x = symbols('x')
>1/sqrt(x)==sqrt(1/x)
False

I think this is a bug of sympy. Thanks ahead if the developing team could solve this problem.

**Comment by ThePauliPrinciple** [comment]
This is the expected behaviour, see also https://docs.sympy.org/latest/gotchas.html#double-equals-signs

**Comment by xfliu** [comment]
Here is new version of the code

` simplify(1/sqrt(x)-sqrt(1/x))==0`

However, it also gives "False."


> This is the expected behaviour, see also https://docs.sympy.org/latest/gotchas.html#double-equals-signs

**Comment by jksuom** [comment]
The result is `False` because the two expressions are different for some values of `x`:
```
n [49]: sqrt(1/x).subs(x, -1)                  
Out[49]: ⅈ

In [50]: 1/sqrt(x).subs(x, -1)
Out[50]: -ⅈ
```

**Comment by ThePauliPrinciple** [comment]
If you give `x` the assumption that it is positive, it will find the equality:
```python
from sympy import *
x = Symbol('x', positive = True)
Eq(S.One/sqrt(x),sqrt(S.One/x))
```

**Comment by xfliu** [comment]
Many thanks for your easy-to-understand example codes.

**Comment by xfliu** [comment]
A further question: is it possible (through some settings of sympy) to evaluate the expression in the scope of real numbers: both the variable and the results are real numbers.

That is, the expression "sqrt(x)" automatically implies that "x" is a non-negative real number.

**Comment by ThePauliPrinciple** [comment]
Yes, see https://docs.sympy.org/latest/guides/assumptions.html#predicates

e.g. `nonnegative = True` See the table in the link

**Comment by smichr** [comment]
No, you have to explicitly create symbols with the attributes you desire, e.g. `x = Symbol('x', positive=True)`; if you have an expression and you want to make all plain symbols positive you can use `posify` on it, e.g. `posify(Eq(1/sqrt(x),sqrt(1/x)))-> (True, {_x:x}`.

**Comment by xfliu** [comment]
Thanks again. I got the idea of the assumptions of variables.

But there is still some problem in my case.

Assume that p is polynomial with variable x. For all possible x that sqrt(p) is well defined in the scope of real number, it is expected that "1/sqrt(p) - sqrt(1/p)==True". 

If p is simple, we can set the range of the variable to be positive or non-negative. But for a general p, it is difficult to set the range of x explicitly.

Any further advice? Thanks ahead.


>

**Comment by ThePauliPrinciple** [comment]
The assumptions should "propagate" through the expressions if it is possible e.g.:
```python
from sympy import *
x = Symbol('x', nonnegative = True)
p = 3 + 4*x + 5*x**2
Eq(1/sqrt(p),sqrt(1/p))
```
But it is hard to understand for me what your concert is precisely. Could you give a code example of what is not working as expected for you?

**Comment by xfliu** [comment]
Here is a sample code

`from sympy import *
... x = Symbol('x', nonnegative = True)
... p = x-1
... Eq(1/sqrt(p),sqrt(1/p))
`
It does output True.

**Comment by ThePauliPrinciple** [comment]
Because it is not for all values of nonnegative `x`, any value of `x` below 1 will lead to an inequality

**Comment by ThePauliPrinciple** [comment]
Are you perhaps looking to find for which values of `x` the equality holds?

**Comment by xfliu** [comment]
Let me further explain the scenario in my case.

I am developing an auto-test system for math exercises. 

The correct answer is set as "sqrt(1/p)" (p is a random expression) for one exercise. But students may input the answer in unexpected way; suppose it is given by "1/sqrt(p)".  

The sympy computation result outputs ``False`` if  we evaluate ``simplify( 1/sqrt(p) - 1/sqrt(p))==0``.  But I hope it to output ``True`` with proper setting of sympy

**Comment by ThePauliPrinciple** [comment]
But it is the wrong answer if the value of p can be lower than `0`

**Comment by xfliu** [comment]
Basically, I have got one answer to my question is to set proper range of x for a specified "p".

Maybe the design of SymPy and Maxima differ from each other here. You see, the Maxima code below will generate True.
```
1/sqrt(x-1)-sqrt(1/(x-1));
```

**Comment by xfliu** [comment]
> 

Yes, your argument is mathematically strict and correct.  I think Maxima evaluate the code under another reasonable assumption.

In setting an exercise for auto-test, we want a simple way to set the variable and the problems.

**Comment by xfliu** [comment]
Another viewpoint related to this discussion:

The following cod generate True. It is quite reasonable.
```
from sympy import *
x = Symbol('x', nonnegative = True)
Eq(1/x-1/x, 0)
```
But if you substitute "x=0" as below, then it generates False.
cod generate True.
```
from sympy import *
x = Symbol('x', nonnegative = True)
Eq(1/0-1/0, 0)
```

This is because ``infinity- infinity`` gives NaN. Thus it is not equal to `` 0 ``.

**Comment by ThePauliPrinciple** [comment]
I agree that this is inconsistent. I believe that this was discussed before and there is not a straightforward way to deal with it that does not break a lot of other things.

**Comment by xfliu** [comment]
Since the value of x as zero in evaluating "1/x-1/x" is excluded automatically, 
it is also expected to only consider the reasonable of range of x in evaluating "1/sqrt(x-1)" (by excluding the part x<=1 automatically), when everything is limited to the scope of real numbers.

**Comment by ThePauliPrinciple** [comment]
I disagree, dealing with the divided by zero singularity is completely different since it is not mathematically well defined. This in contrast with `1/sqrt(x-1)` for values smaller than 1. 

"when everything is limited to the scope of real numbers"
I'm not aware of how you can impose such a limitation in SymPy, but it might be possible. It certainly should not be the default behaviour

**Comment by xfliu** [comment]
Here is the result from Maxima. It is more natural to me. 

```
(%i1) 1/sqrt(x-1)-sqrt(1/(x-1));
(%o1)                                  0
(%i5) x:-1;       
(%o5)                                 - 1
(%i6)  1/sqrt(x-1)-sqrt(1/(x-1));
(%o6)                            - sqrt(2) %i
````

**Comment by ThePauliPrinciple** [comment]
I believe the SymPy equivalent would be `(1/sqrt(x-1)-sqrt(1/(x-1))).subs(x,-1)`

**Comment by smichr** [comment]
I've been using `cse` a bit for such issues and wonder if you might do

`posify(cse(Eq(1/sqrt(x-1),sqrt(1/(x-1))), list=False)[1])[0]` or, in older versions than current, `posify(cse(Eq(1/sqrt(x-1),sqrt(1/(x-1))))[1][0])[0]`

**Comment by xfliu** [comment]
> I've been using `cse` a bit for such issues and wonder if you might do
> 
> `posify(cse(Eq(1/sqrt(x-1),sqrt(1/(x-1))), list=False)[1])[0]` or, in older versions than current, `posify(cse(Eq(1/sqrt(x-1),sqrt(1/(x-1))))[1][0])[0]`

This is very helpful!  I tried several examples to confirm this. For example, the following code will output ``True``. 

```
from sympy import *
x = symbols('x')
f=sin(x**2-3*x+1)
g=1/sqrt(f)-sqrt(1/f)
posify(cse(g)[1][0])[0]==0
```
( SymPy 1.5.1 (Python 2.7.12))

**Comment by smichr** [comment]
The only other suggestion I have would be to use signsimp before cse so any trivial differences in sign would be eliminated:

`signsimp(exp(x-y)-1/exp(y-x)) -> 0`

**Comment by xfliu** [comment]
> The only other suggestion I have would be to use signsimp before cse so any trivial differences in sign would be eliminated:
> 
> `signsimp(exp(x-y)-1/exp(y-x)) -> 0`

It is said that ``simplify`` applies several operation to simplify an expression. I am wondering whether ``signsimp`` is applied in the ``simpify`` processing or not.

**Comment by xfliu** [comment]
By the way, I created one complex example and want to find the most efficient way to adjust whether it equals to zero or not.

The idea in the code below is to apply ``cse + posify`` first to remove some redundant terms (here, just ``1/sqrt(1/f)-sqrt(f)``), then restore the variables by ``subs`` and finally apply ``simplify``. 

```
>>> import sympy
>>> from sympy import *
>>> x = symbols('x')
>>>  f=sin(x**2-3*x+1)
>>> g=1/sqrt(1/f)-sqrt(f)+sin(2*x)-2*sin(x)*cos(x) - (x**2+2*x+1)/(x+1)**2+1
>>> g
-2*sin(x)*cos(x) + sin(2*x) - sqrt(sin(x**2 - 3*x + 1)) + 1 + 1/sqrt(1/sin(x**2 - 3*x + 1)) - (x**2 + 2*x + 1)/(x + 1)**2
>>> g_by_cse = cse(g)
>>> g_by_cse
([(x0, 2*x), (x1, x**2 + 1), (x2, -sin(3*x - x1))], [-sqrt(x2) - 2*sin(x)*cos(x) + sin(x0) + 1 + 1/sqrt(1/x2) - (x0 + x1)/(x + 1)**2])
>>> g_by_posify = posify(g_by_cse[1])
>>> g_by_posify
([-2*sin(_x)*cos(_x) + sin(_x0) + 1 - (_x0 + _x1)/(_x + 1)**2], {_x2: x2, _x0: x0, _x1: x1, _x: x})
>>> g_by_simplify = simplify(g_by_posify[0][0])
>>> g_by_simplify
(-_x0 - _x1 + (_x + 1)**2*(-sin(2*_x) + sin(_x0) + 1))/(_x + 1)**2
>>> simplify(g_by_simplify.subs(g_by_posify[1]).subs(g_by_cse[0]))
```
In short:
```
def my_simplify(g):
  g_by_cse = cse(g)
  g_by_posify = posify(g_by_cse[1])
  g_by_simplify = simplify(g_by_posify[0][0])
  return simplify(g_by_simplify.subs(g_by_posify[1]).subs(g_by_cse[0]))

import sympy
from sympy import *
x = symbols('x')
f=sin(x**2-3*x+1)
g=1/sqrt(1/f)-sqrt(f)+sin(2*x)-2*sin(x)*cos(x) - (x**2+2*x+1)/(x+1)**2+1
my_simplify(g)
```

This idea works well for the following example: (Note that there is a redundant term  ``sin(2*x)-2*sin(x)*cos(x)`` inside).
```
g=240*x**2*sin(10*x**3 + 1)**7/cos(10*x**3 + 1)**9 - 240*x**2*sin(10*x**3 + 1)**7/cos(10*x**3 + 1+sin(2*x)-2*sin(x)*cos(x))**9
```
If I run ``simplify(g)==0``, then the processing of trigonometric function takes so long time that I have to stop it.

In this case ``my_simplify(g)==0`` outputs ``True``.
