### ISSUE TITLE
Error in ODE-Solver-Documentation

### ISSUE THREAD

**Issue by T-KS** [sympy/sympy#22558]
On page https://docs.sympy.org/latest/modules/solvers/ode.html
should'nt the description of 2nd_power_series_ordinary be
P(x)*y''(x) + Q(x)*y'(x) + R(x)*y(x)=0
and 2nd_power_series_regular same
P(x)*y''(x) + Q(x)*y'(x) + R(x)*y(x)=0
instead of P(x)*y''(x) + Q(x)*y'(x) + R(x)=0 both?

**Comment by ThePauliPrinciple** [comment]
Yes, I also understand a second order homogeneous differential equation to have `y(x)` in the last term. (for convenience https://docs.sympy.org/latest/modules/solvers/ode.html#nd-power-series-regular)

**Comment by oscarbenjamin** [comment]
This is probably just a typo

**Comment by T-KS** [comment]
Yes, I also think it's a typo, but I didn't find a place to correct it (or an email ...)

**Comment by ThePauliPrinciple** [comment]
A PR needs to be made which fixes the typos here
https://github.com/sympy/sympy/blob/ed0bfd1e47345c8bd45ef542eef18f6a21c55685/sympy/solvers/ode/ode.py#L2279-L2291
and here
https://github.com/sympy/sympy/blob/ed0bfd1e47345c8bd45ef542eef18f6a21c55685/sympy/solvers/ode/ode.py#L2424-L2435

**Comment by KuldeepBorkar** [comment]
Ok, I will fix the typo quickly.
