### ISSUE TITLE
Benchmarks builds are failing on CI

### ISSUE THREAD

**Issue by hanspi42** [sympy/sympy#22552]
The problem described in #22459 has returned, see https://github.com/sympy/sympy/runs/4327728192?check_suite_focus=true for an example.

**Comment by oscarbenjamin** [comment]
The change in #22481 needs to be reverted

**Comment by hanspi42** [comment]
I agree. @smichr, can you revert?

**Comment by asmeurer** [comment]
Sorry, I didn't realize it would immediately break again once the upstream issue was fixed. I should have symlinked the file instead of renaming it.
