### ISSUE TITLE
Dict storing key,value pairs as non-Basic

### ISSUE THREAD

**Issue by ThePauliPrinciple** [sympy/sympy#22579]
Currently, `Dict` stores its `key,value` pairs as `frozenset`. I believe this might be a typo:
https://github.com/sympy/sympy/blob/ed0bfd1e47345c8bd45ef542eef18f6a21c55685/sympy/core/containers.py#L227-L238
line 235 should probably read:
```python
        obj = Basic.__new__(cls, *elements)
```
Although it might be intended for efficiency reasons.

**Comment by oscarbenjamin** [comment]
> Although it might be intended for efficiency reasons.

It's okay to store a parallel more efficient data structure but as you say the args should be Basic.

**Comment by ThePauliPrinciple** [comment]
This is a bit of a special case, since `args` are `Basic`, only `_args` are not.

**Comment by oscarbenjamin** [comment]
If we're happy with the content of args then is there a good reason it shouldn't be stored in `_args`?

**Comment by ThePauliPrinciple** [comment]
curently there are different things stored in `args` and `_args`.
```python
>>> from sympy import *
>>> d=Dict({'a':1})
>>> print(d.args, d._args)
((a, 1),) (frozenset({(a, 1)}),)
```

**Comment by oscarbenjamin** [comment]
But can we not make it so that `args` is derived from `_args` is is usually the case for Basic subclasses?
