### ISSUE TITLE
Append "What's Next" page to tutorial

### ISSUE THREAD

**Issue by bertiewooster** [sympy/sympy#22586]
Append to the [tutorial](https://docs.sympy.org/dev/tutorial/index.html#tutorial) a "What's Next" page directing learners to the [Guides](https://docs.sympy.org/dev/guides/index.html#guides) in the documentation.

[Idea discussed on Google Group, supported by @asmeurer Aaron Meurer.](https://groups.google.com/g/sympy/c/clEogTV1uS4/m/jHd0uWXZAwAJ)

**Comment by bertiewooster** [comment]
I drafted a [What's Next page on the Wiki](https://github.com/sympy/sympy/wiki/Tutorial:-What's-Next-page)

# What's Next

### Congratulations on finishing the SymPy tutorial! The next step to help you get started is to go to the [guides](https://docs.sympy.org/dev/guides/index.html#guides) for instructions on how to do different key developer tasks:
*   [Getting Started](getting_started/index.html)
*   [Contributing to SymPy](contributing/index.html)
*   [Assumptions](assumptions.html)
*   [Symbolic and fuzzy booleans](booleans.html)

Intermediate SymPy users and developers might want to visit the [explanation](https://docs.sympy.org/dev/explanation/index.html#explanation) section for common pitfalls and advanced topics.

The [SymPy API Reference](https://docs.sympy.org/dev/reference/index.html#reference) has a detailed description of the SymPy API.

**Comment by oscarbenjamin** [comment]
I think that something like this is definitely needed. Ideally it would focus on user tasks before developer tasks though.

**Comment by bertiewooster** [comment]
@oscarbenjamin That makes sense. Which tasks would be considered user rather than developer--the following? other? 

- [Guides](https://docs.sympy.org/dev/guides/index.html#guides)
    - [Getting Started](https://docs.sympy.org/dev/guides/getting_started/index.html)
    - [Assumptions](https://docs.sympy.org/dev/guides/assumptions.html)
    - [Symbolic and fuzzy booleans](https://docs.sympy.org/dev/guides/booleans.html)
- [Explanation](https://docs.sympy.org/dev/explanation/index.html#explanation)
    - [Gotchas and Pitfalls](https://docs.sympy.org/dev/explanation/gotchas.html)
    - [SymPy Special Topics](https://docs.sympy.org/dev/explanation/special_topics/index.html)
- [Reference Documentation](https://docs.sympy.org/dev/reference/index.html)
    - [Basics](https://docs.sympy.org/dev/reference/public/basics/index.html#basic-modules)
    - [Logic](https://docs.sympy.org/dev/reference/public/logic/index.html#logic)
    - [Matrices](https://docs.sympy.org/dev/reference/public/matrices/index.html#matrices-modules)
    - [Number Theory](https://docs.sympy.org/dev/reference/public/numbertheory/index.html#numtheory-module)
    - [Physics](https://docs.sympy.org/dev/reference/public/physics/index.html#physics-docs)
    - [Utilities](https://docs.sympy.org/dev/reference/public/utilities/index.html#utilities)
    - [Topics](https://docs.sympy.org/dev/reference/public/topics/index.html#topics)

(The existing documentation doesn't make an obvious distinction between user and developer tasks, which we might want to address later.)

**Comment by bertiewooster** [comment]
@oscarbenjamin Thinking about this further, while it seems reasonable to distinguish between user and developer content, we'd probably want to do so throughout the documentation in addition to on this What's Next page. (There were relevant topics from all three other categories Diataxis framework categories, so we can't for example just point users to one category and developers to the other two.) That task seems much bigger, might be controversial, and might not be something we want to do soon considering the documentation was just reorganized into the four Diataxis framework categories.

How about if we have the What's Next page mirror the [documentation (1.10 dev) homepage](https://docs.sympy.org/dev/index.html)? Then if we update the documentation to distinguish between user and developer content, we can similarly update the What's Next page.

**Comment by oscarbenjamin** [comment]
I just mean that when someone has only just gotten to the end of the tutorial they are more likely to want to read further information about using SymPy rather than see information about contributing to SymPy. Maybe the problem is just that the "guides" section is skewed towards information for contributors.

**Comment by bertiewooster** [comment]
Ah, I understand. I concur and suggest that Contributing to SymPy be moved down to be the last topic in the [Guides section](https://docs.sympy.org/dev/guides/index.html#guides).
