### ISSUE TITLE
Incorrect result from minpoly(cos(pi/9))

### ISSUE THREAD

**Issue by Leowbattle** [sympy/sympy#22605]
I believe that sympy returns the incorrect answer for `minpoly(cos(pi/9))`.

sympy 1.8 and sympy gamma (as of 05/12/2021) return `8*x**3 - 6*x + 1`, but the correct answer is `8*x**3 - 6*x - 1` which I verified by hand and with [Wolfram Alpha](https://www.wolframalpha.com/input/?i=minpoly%28cos%28pi%2F9%29%29).

```py
In [1]: from sympy import *

In [2]: x=symbols("x")

In [3]: p=minpoly(cos(pi/9),x)

In [4]: p
Out[4]: 8*x**3 - 6*x + 1

In [5]: N(p.subs(x,cos(pi/9)))
Out[5]: 2.00000000000000

In [6]: p=8*x**3 - 6*x - 1

In [7]: N(p.subs(x,cos(pi/9)))
Out[7]: 0.e-124
```

I think the bug is [here](https://github.com/sympy/sympy/blob/82cc5a598f236b32b5f7adf530802503c121b080/sympy/polys/numberfields/minpoly.py#L440), the code should be `return 8*x**3 - 6*x - 1`

**Comment by ThePauliPrinciple** [comment]
I agree that this is a typo. The documentation in the code refers to https://mathworld.wolfram.com/TrigonometryAngles.html (table between eq. 11 and eq. 12), which also states `8*x**3 - 6*x - 1`, yet the code reads `8*x**3 - 6*x + 1`

https://github.com/sympy/sympy/blob/82cc5a598f236b32b5f7adf530802503c121b080/sympy/polys/numberfields/minpoly.py#L428-L440

**Comment by skieffer** [comment]
Yes, you're right, it should be `8*x**3 - 6*x - 1`, which is familiar from the proof of the impossibility of the trisection! Thanks for catching this!

**Comment by Leowbattle** [comment]
Ok, if nobody else has started yet, I will try to work on this one. I just wanted to wait and see if it was sympy or me that had the wrong answer.

**Comment by Leowbattle** [comment]
[Link to PR](https://github.com/sympy/sympy/pull/22610)
