### ISSUE TITLE
factor_terms should not expand `0**(x +/- i)`; where i = integer

### ISSUE THREAD

**Issue by smichr** [sympy/sympy#22613]
```python
>>> factor_terms(0**(x - 2) - 1)
0**x*zoo - 1

>>> factor_terms(0**(x + 2) - 1)
-1
>>> factor_terms((0**(x + 2) - 1).subs(x,-2))
0
```

**Comment by MishraAditya12126** [comment]
hello @smichr its actually factoring 0**(x+/-i) because the precedence of the exponent is more than the precedence of the function call that's why it get simplified into 0 first after then factoring of the remaining part occurs

**Comment by faze-geek** [comment]
@smichr This could be fixed once we approach the `as_content_primitive` method differently ! As per what I could see , this expression should be dealt differently
```
>>> (0**(x - 2)).as_content_primitive()
(zoo, 0**x)

>>> (0**(x - 2)).as_content_primitive() # This would do it for us 
(1, 0**(x -2))
```
