### ISSUE TITLE
Reorder topics on documentation's SymPy Guides page

### ISSUE THREAD

**Issue by bertiewooster** [sympy/sympy#22629]
Move _Contributing to SymPy_ to be last on [SymPy Guides page](https://docs.sympy.org/dev/guides/index.html#guides), so order of top-level guides is:

- Getting Started
- Assumptions
- Symbolic and fuzzy booleans
- Contributing to SymPy

Per:

"when someone has only just gotten to the end of the tutorial they are more likely to want to read further information about using SymPy rather than see information about contributing to SymPy"
_Originally posted by @oscarbenjamin in https://github.com/sympy/sympy/issues/22586#issuecomment-987038028_

**Comment by AdvaitPote** [comment]
Hey I would like to work on this.

**Comment by AdvaitPote** [comment]
I searched but couldn't find it in the code anywhere. Could you please tell me where the changes have to be made.

**Comment by NikhilSDate** [comment]
This is from the [General Guidelines](https://docs.sympy.org/dev/guides/contributing/documentation-style-guide.html)

> The SymPy documentation found at docs.sympy.org is generated from docstrings in the source code and dedicated narrative documentation files in the doc/src directory. Both are written in reStructuredText format extended by Sphinx.

In particular, for reordering the topics, you would probably have to make edits to the [index.rst](https://github.com/sympy/sympy/blob/master/doc/src/guides/index.rst) file in doc/src/guides

**Comment by bertiewooster** [comment]
@KuldeepBorkar Once you make a change to a documentation file such as [index.rst](https://github.com/sympy/sympy/blob/master/doc/src/guides/index.rst), how do you build the documentation to verify that your change turns out as planned in the HTML file?

**Comment by KuldeepBorkar** [comment]
@bertiewooster using sphinx

**Comment by KuldeepBorkar** [comment]
@bertiewooster using sphinx (On your command line you can try running the command ``` $ sphinx-build -b html sourcedir builddir ``` where sourcedir is the source dir)
Hope you find this helpful

**Comment by bertiewooster** [comment]
@KuldeepBorkar Thanks! I already followed the instructions on the [documentation style guide](https://docs.sympy.org/dev/guides/contributing/documentation-style-guide.html) to install [Sphinx](http://www.sphinx-doc.org/). 

I also installed the Sphinx extensions `numpydoc`, `sphinx_math_dollar`, and `matplotlib` using, respectively,

```py
pip install numpydoc
pip install sphinx-math-dollar
pip install matplotlib
```

When I then ran
`$ sphinx-build -b html sourcedir builddir` I got the error

```py
Extension error:
Could not import extension sympylive (exception: No module named 'sympylive')
```

Where can I obtain the sympylive Sphinx extension? It's not on [Sphinx's list of third-party extensions](https://github.com/orgs/sphinx-contrib/repositories). (I understand from the [documentation style guide](https://docs.sympy.org/dev/guides/contributing/documentation-style-guide.html) that it has _No bearing on documentation source format_, but the documentation won't build without it.

P.S. I plan to add this information to the [documentation style guide](https://docs.sympy.org/dev/guides/contributing/documentation-style-guide.html) so future documentation contributors won't have to ask these questions! :-)

**Comment by oscarbenjamin** [comment]
I agree that it is problematic that it is difficult to build the docs on Windows but does Docker make it much easier than the other options like virtual machines or WSL?

(Genuine question coming from a long time non-Windows user)

**Comment by skieffer** [comment]
Maybe just depends on what people are most accustomed to -- could be Docker for some, virtual machines for others?

I can't speak for Windows either, but, working on a Mac, I like having the option to run a container rather than install things locally.

**Comment by ThePauliPrinciple** [comment]
WSL works great, but it does come with `mypy` errors for me (I think they are related to the filesystem somehow, e.g.:
```
sympy/solvers/ode/subscheck.py:9: error: Name "Order" already defined (by an import)
sympy/solvers/ode/ode.py:251: error: Name "Order" already defined (by an import)
```

**Comment by oscarbenjamin** [comment]
I can't remember what I installed on my Mac for this but I think it was all stuff that I routinely use like LaTeX etc and then just the other Python packages that I put in a venv.

**Comment by oscarbenjamin** [comment]
> WSL works great, but it does come with `mypy` errors for me (I think they are related to the filesystem somehow, e.g.:

That might be related to having a different version of mypy or using a different version of Python rather than WSL. One of the reasons I delayed running mypy in CI was because it's so flakey like that. Possibly there is something that can be fixed there or maybe we should just add a `type: ignore` for those.

**Comment by oscarbenjamin** [comment]
> WSL works great, but it does come with `mypy` errors for me (I think they are related to the filesystem somehow, e.g.:

Does the error go away if you do e.g.:
```diff
diff --git a/sympy/solvers/ode/subscheck.py b/sympy/solvers/ode/subscheck.py
index 2925e61..99016bc 100644
--- a/sympy/solvers/ode/subscheck.py
+++ b/sympy/solvers/ode/subscheck.py
@@ -6,7 +6,7 @@
 
 from sympy.logic.boolalg import BooleanAtom
 from sympy.functions import exp
-from sympy.series import Order
+from sympy.series.order import Order
 from sympy.simplify.simplify import simplify, posify, besselsimp
 from sympy.simplify.trigsimp import trigsimp
 from sympy.simplify.sqrtdenest import sqrtdenest
```

**Comment by ThePauliPrinciple** [comment]
> Does the error go away if you do e.g.:

Yes, it happens when you have a module and object with the same name (ignoring case).

**Comment by oscarbenjamin** [comment]
> > Does the error go away if you do e.g.:
> 
> Yes, it happens when you have a module and object with the same name (ignoring case).

The ignoring case part is probably Windows-specific because Windows filesystems ignore case. Otherwise though I think it would be good to fix it by using fully explicit imports.

**Comment by bertiewooster** [comment]
OK, I got around the problem of Sphinx not finding sympy-live by removing that requirement from doc/src/conf.py

```py
            #   'sphinx.ext.mathjax', 'numpydoc', 'sympylive', 'sphinx_reredirects',
              'sphinx.ext.mathjax', 'numpydoc', 'sphinx_reredirects',
```

Now `sphinx-build` gives the output below, terminating with

```py
Extension error (numpydoc.numpydoc):
Handler <function mangle_signature at 0x7fda1f938430> for event 'autodoc-process-signature' threw an exception (exception: .separatevars(), .expand(log=True)
```

`sphinx-build` produced seven HTML files, three in the top level and four in /special_topics.

Here's the full `sphinx-build` output:

```py
sympy % sphinx-build -b html doc/src ../sympy-contributing/doc
Running Sphinx v4.3.0
making output directory... done
WARNING: favicon file '../_build/logo/sympy-notailtext-favicon.ico' does not exist
[autosummary] generating autosummary for: aboutus.rst, citing.rst, explanation/gotchas.rst, explanation/index.rst, explanation/special_topics/classification.rst, explanation/special_topics/finite_diff_derivatives.rst, explanation/special_topics/index.rst, guides/assumptions.rst, guides/booleans.rst, guides/contributing/build-docs.rst, ..., tutorial/gotchas.rst, tutorial/index.rst, tutorial/intro.rst, tutorial/manipulation.rst, tutorial/matrices.rst, tutorial/preliminaries.rst, tutorial/printing.rst, tutorial/simplification.rst, tutorial/solvers.rst, wiki.rst
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 259 source files that are out of date
updating environment: [new config] 259 added, 0 changed, 0 removed
/Users/jemonat/Projects/sympy/venv/lib/python3.9/site-packages/numpydoc/docscrape.py:418: UserWarning: Unknown section Explanation in the docstring of <function powsimp at 0x7fda1e4dbaf0> in /Users/jemonat/Projects/sympy/sympy/simplify/powsimp.py.
  warn(msg)
/Users/jemonat/Projects/sympy/venv/lib/python3.9/site-packages/numpydoc/docscrape.py:418: UserWarning: Unknown section Explanation in the docstring of <function Expr.args_cnc at 0x7fda1db310d0> in /Users/jemonat/Projects/sympy/sympy/core/expr.py.
  warn(msg)
WARNING: error while formatting signature for sympy.algebras.Quaternion.to_rotation_matrix: Handler <function mangle_signature at 0x7fda1f938430> for event 'autodoc-process-signature' threw an exception (exception: The section Examples appears twice in the docstring of <function Quaternion.to_rotation_matrix at 0x7fda1eb18670> in /Users/jemonat/Projects/sympy/sympy/algebras/quaternion.py.)
Creating redirect file 'install.html' pointing to '{new_target}'.
Creating redirect file 'documentation-style-guide.html' pointing to '{new_target}'.
Creating redirect file 'gotchas.html' pointing to '{new_target}'.
Creating redirect file 'special_topics/classification.html' pointing to '{new_target}'.
Creating redirect file 'special_topics/finite_diff_derivatives.html' pointing to '{new_target}'.
Creating redirect file 'special_topics/intro.html' pointing to '{new_target}'.
Creating redirect file 'special_topics/index.html' pointing to '{new_target}'.

Extension error (numpydoc.numpydoc):
Handler <function mangle_signature at 0x7fda1f938430> for event 'autodoc-process-signature' threw an exception (exception: .separatevars(), .expand(log=True), sympy.core.add.Add.as_two_terms(), is not a item name in "A mostly naive separation of a Mul or Add into arguments that are not\nare dependent on deps. To obtain as complete a separation of variables\nas possible, use a separation method first, e.g.:\n\n* separatevars() to change Mul, Add and Pow (including exp) into Mul\n* .expand(mul=True) to change Add or Mul into Add\n* .expand(log=True) to change log expr into an Add\n\nThe only non-naive thing that is done here is to respect noncommutative\nordering of variables and to always return (0, 0) for `self` of zero\nregardless of hints.\n\nFor nonzero `self`, the returned tuple (i, d) has the\nfollowing interpretation:\n\n* i will has no variable that appears in deps\n* d will either have terms that contain variables that are in deps, or\n  be equal to 0 (when self is an Add) or 1 (when self is a Mul)\n* if self is an Add then self = i + d\n* if self is a Mul then self = i*d\n* otherwise (self, S.One) or (S.One, self) is returned.\n\nTo force the expression to be treated as an Add, use the hint as_Add=True\n\nExamples\n========\n\n-- self is an Add\n\n>>> from sympy import sin, cos, exp\n>>> from sympy.abc import x, y, z\n\n>>> (x + x*y).as_independent(x)\n(0, x*y + x)\n>>> (x + x*y).as_independent(y)\n(x, x*y)\n>>> (2*x*sin(x) + y + x + z).as_independent(x)\n(y + z, 2*x*sin(x) + x)\n>>> (2*x*sin(x) + y + x + z).as_independent(x, y)\n(z, 2*x*sin(x) + x + y)\n\n-- self is a Mul\n\n>>> (x*sin(x)*cos(y)).as_independent(x)\n(cos(y), x*sin(x))\n\nnon-commutative terms cannot always be separated out when self is a Mul\n\n>>> from sympy import symbols\n>>> n1, n2, n3 = symbols('n1 n2 n3', commutative=False)\n>>> (n1 + n1*n2).as_independent(n2)\n(n1, n1*n2)\n>>> (n2*n1 + n1*n2).as_independent(n2)\n(0, n1*n2 + n2*n1)\n>>> (n1*n2*n3).as_independent(n1)\n(1, n1*n2*n3)\n>>> (n1*n2*n3).as_independent(n2)\n(n1, n2*n3)\n>>> ((x-n1)*(x-y)).as_independent(x)\n(1, (x - y)*(x - n1))\n\n-- self is anything else:\n\n>>> (sin(x)).as_independent(x)\n(1, sin(x))\n>>> (sin(x)).as_independent(y)\n(sin(x), 1)\n>>> exp(x+y).as_independent(x)\n(1, exp(x + y))\n\n-- force self to be treated as an Add:\n\n>>> (3*x).as_independent(x, as_Add=True)\n(0, 3*x)\n\n-- force self to be treated as a Mul:\n\n>>> (3+x).as_independent(x, as_Add=False)\n(1, x + 3)\n>>> (-3+x).as_independent(x, as_Add=False)\n(1, x - 3)\n\nNote how the below differs from the above in making the\nconstant on the dep term positive.\n\n>>> (y*(-3+x)).as_independent(x)\n(y, x - 3)\n\n-- use .as_independent() for true independence testing instead\n   of .has(). The former considers only symbols in the free\n   symbols while the latter considers all symbols\n\n>>> from sympy import Integral\n>>> I = Integral(x, (x, 1, 2))\n>>> I.has(x)\nTrue\n>>> x in I.free_symbols\nFalse\n>>> I.as_independent(x) == (I, 1)\nTrue\n>>> (I + x).as_independent(x) == (I, x)\nTrue\n\nNote: when trying to get independent terms, a separation method\nmight need to be used first. In this case, it is important to keep\ntrack of what you send to this routine so you know how to interpret\nthe returned values\n\n>>> from sympy import separatevars, log\n>>> separatevars(exp(x+y)).as_independent(x)\n(exp(y), exp(x))\n>>> (x + x*y).as_independent(y)\n(x, x*y)\n>>> separatevars(x + x*y).as_independent(y)\n(x, y + 1)\n>>> (x*(1 + y)).as_independent(y)\n(x, y + 1)\n>>> (x*(1 + y)).expand(mul=True).as_independent(y)\n(x, x*y)\n>>> a, b=symbols('a b', positive=True)\n>>> (log(a*b).expand(log=True)).as_independent(b)\n(log(a), log(b))\n\nSee Also\n========\n.separatevars(), .expand(log=True), sympy.core.add.Add.as_two_terms(),\nsympy.core.mul.Mul.as_two_terms(), .as_coeff_add(), .as_coeff_mul()")
```

**Comment by skieffer** [comment]
FWIW, if building just the HTML docs is enough, then the following Dockerfile seems to work:

```dockerfile
FROM python:3.8.12-slim-buster

RUN apt-get update
RUN apt-get install -y make librsvg2-bin imagemagick graphviz git

COPY requirements.txt /tmp
RUN egrep "phinx|mpmath|matplotlib" /tmp/requirements.txt > /tmp/req_min.txt
RUN pip install --upgrade pip
RUN pip install -r /tmp/req_min.txt

CMD cd /sympy/doc; make html
```

If you saved this as `release/Dockerfile.htmldoc`, then you could build the image with

```
$ cd release
$ docker build -f Dockerfile.htmldoc -t sympy_htmldoc .
```

and once you had the image you could build the docs at any time with

```
$ docker run --rm -v /path/to/the/sympy/repo:/sympy sympy_htmldoc
```

The image weighs in at 679MB. If you wanted to also build LaTeX docs I think the image might be 5 to 10 times as large. But I find HTML docs are enough, if I just want to check that things are looking about right.

**Comment by bertiewooster** [comment]
@skieffer thanks! That worked for me: it wrote the HTML documentation to my local sympy repository's doc/_build/html folder.

It'd be great to document this method. Do you concur that we should include it in the [documentation guidelines page](https://docs.sympy.org/dev/guides/contributing/documentation-style-guide.html), attaching the Dockerfile to the page so people can download it?

**Comment by skieffer** [comment]
> Do you concur that we should include it in the documentation guidelines page, attaching the Dockerfile to the page so people can download it?

Sure! I'm just wondering if maybe the Dockerfile -- or a version of it -- should be provided in the `release` directory, maybe with commented instructions on how to use it. Maybe someone more familiar with the plans for the `release` dir can comment. @oscarbenjamin @asmeurer ?

**Comment by oscarbenjamin** [comment]
I think it would make more sense to put the Docker file in the doc directory. The instructions for building the docs could be updated to suggest using it as an option.

**Comment by bertiewooster** [comment]
OK. I'll make a separate issue for helping folks build the docs using Docker.

**Comment by asmeurer** [comment]
Another idea would be to use something like this https://numpy.org/devdocs/dev/development_gitpod.html

**Comment by KuldeepBorkar** [comment]
> but `$ sphinx-build -b html sourcedir builddir` still throws the `Could not import extension sympylive` error. Do I have to import sympy-live into Sphinx somehow?

@bertiewooster I realized this problem comes when we are outside the sympy/doc folder.

Doing a ``git bash`` in ``sympy/doc`` and then just run the command;

``sphinx-build -b html sourcedir builddir`` 
(Here, sourcedir is the source directory so it should be src
and the builddir is the directory in which we will see the build, so it can be named anything like SymPyBuild.
So, this command can be used like this;
sphinx-build -b html src SymPyBuild)
