### ISSUE TITLE
Wrong indefinite integration when variable is element of MatrixSymbol

### ISSUE THREAD

**Issue by fdraxler** [sympy/sympy#22624]
The integral 1/x is wrongly evaluated by sympy when x is a `MatrixElement`:
![\intx x^{-1}](https://render.githubusercontent.com/render/math?math=\int_xx^{-1}=1\neq\log(x))

## Code to reproduce
```python
integrate(1/x, x)  # -> log(x)

a = MatrixSymbol("a", 1, 1)
integrate(1/a[0, 0], a[0, 0]) # -> 1 ≠ log(a[0, 0])
```

However, the definite integral is correctly computed:
```python
integrate(1/x, (x, 1, 2)) # -> log(2)
integrate(1/a[0, 0], (a[0, 0], 1, 2)) # -> log(2)
```

## Workaround
Substitute `a[0, 0]` with some other variable, integrate, and substitute back:
```python
integrate((1/a[0, 0]).subs(a[0, 0], x), x).subs(x, a[0, 0]) # -> log(a[0, 0])
```

## Notes
- 1 is never a good answer to an indefinite integral (as pointed out in the documentation, terms independent of the variable are dropped).
- If the integrand is a polynomial in `a[0, 0]`, the integral is evaluated correctly.

Have a great day!

**Comment by smichr** [comment]
This is handled correctly in #22539:
```python
>>> integrate(1/x, x)  # -> log(x)
log(x)
>>>
>>> a = MatrixSymbol("a", 1, 1)
>>> integrate(1/a[0, 0], a[0, 0])
log(a[0, 0])
```
