### ISSUE TITLE
Bug sympy.limit() returns incorrect solution

### ISSUE THREAD

**Issue by babycamel** [sympy/sympy#22636]
$\lim_n \rightarrow \infty} (1+1/n)^n$

`from sympy import *

n = symbols('n')

expr = Pow((1 + (1/n)),n)

limit_expr = limit(expr, n, 00) 

limit_expr
`
should return e not 1.

**Comment by anutosh491** [comment]
Positive infinity in Sympy is represented by oo (2 small o's in succession) or using S.Infinity . 
You could try that out for the correct answer and the following issue can be closed !

**Comment by babycamel** [comment]
S.Infinity worked. oo's though an error. This was on colab. Thanks for the hint.

**Comment by anutosh491** [comment]
`oo` should have worked to , can't think of a reason why it wouldn't but anyways glad to help !
@oscarbenjamin the issue could be closed !
