### ISSUE TITLE
Integral transforms need a re-write: discussion

### ISSUE THREAD

**Issue by hanspi42** [sympy/sympy#22633]
There were several comments in https://github.com/sympy/sympy/pull/22630 that inidcate that the integral transforms should be re-written.  Here I would like to collect all open points, such that we can discuss how to solve it.

The ones I remember:
- `laplace_transform` now works with applying rules; the basic infrastructure for this should be included in `IntegralTransform` already such all integral transforms inherit it.
- This should be done in a way such that users can supply their own rules.
- The `**hints` mechanism is outdated, it should be replaced by named keywords
- Integral transforms should either return tuples or expressions according to the value of `noconds`, but if `noconds==False` and they cannot evaluate the transform, they should still return a tuple where the conditions are present but have a value like, e.g., `None`.
- Maybe matchpy should be used for rules instead of sympy's own matching method.

@oscarbenjamin, @oscargus and @asmeurer, and of course anybody else, do you have more points to add?

**Comment by oscarbenjamin** [comment]
The general integration routines should be able to make use of the transforms code when evaluating appropriate definite integrals.

**Comment by asmeurer** [comment]
> Integral transforms should either return tuples or expressions according to the value of noconds, but if noconds==False and they cannot evaluate the transform, they should still return a tuple where the conditions are present but have a value like, e.g., None.

This is only helpful if the condition is a boolean, so I think it should be True in that case. This is saying that the unevaluated transform is always correct, which is trivially true.

**Comment by hanspi42** [comment]
> > Integral transforms should either return tuples or expressions according to the value of noconds, but if noconds==False and they cannot evaluate the transform, they should still return a tuple where the conditions are present but have a value like, e.g., None.
> 
> This is only helpful if the condition is a boolean, so I think it should be True in that case. This is saying that the unevaluated transform is always correct, which is trivially true.

How could we deal with the following case?  If I transform `sinh(2*t)*f(t)`, I will get `L = LaplaceTransform(f(t), t, s-2)/2 - LaplaceTransform(f(t), t, s+2)/2`, so the tuple to be returned would be `L, a, c`. It is no problem to let the condition `c` be `True` in this case, but what about the convergence plane `a`?  In this case the correct solution would be the convergence plane of the Laplace transform of `f(t)` plus 2.  And I do not have a good idea how to formulate this.

**Comment by oscarbenjamin** [comment]
There could be a special symbolic function that represents the convergence plane like `LaplaceConvergenceBound(f(t))`

**Comment by hanspi42** [comment]
Side question: you keep on mentioning matchpy a lot; is that something that will be coming in the near future, or should we already use it nor for the re-write of the integral transforms?
