### ISSUE TITLE
Bra Ket substitution does not work

### ISSUE THREAD

**Issue by Talos878** [sympy/sympy#22653]
import sympy as symbol
from sympy.physics.quantum import AntiCommutator as AntiCalms
from sympy.physics.quantum import Operator, Dagger
import sympy.physics.quantum as q
kx = q.Ket('kx')
ky = q.Ket('ky')
test = 3*kx - ky
symbol.pprint(test)
test.subs(ky, kx)
symbol.pprint(test)

3⋅❘kx⟩ - ❘ky⟩
3⋅❘kx⟩ - ❘ky⟩

I would expect the substitution to replace ky by kx and evaluate to 2*❘kx⟩

**Comment by ThePauliPrinciple** [comment]
This is the expected behaviour. SymPy does not use mutable objects generally, so you have to assign the result:
```python
>>> test=test.subs(ky, kx)
2*|kx>
```

**Comment by Talos878** [comment]
oh my god, :/
