### ISSUE TITLE
`Medium` not hashable

### ISSUE THREAD

**Issue by oscargus** [sympy/sympy#22664]
This shows up as an issue in the LaTeX-printing, but is probably an issue elsewhere as well.

```
from sympy.physics.optics import Medium
Medium('m')
```
gives
```
Traceback (most recent call last):

  File "C:\Users\Oscar\miniconda3\lib\site-packages\IPython\core\formatters.py", line 345, in __call__
    return method()

  File "C:\Users\Oscar\sympy\sympy\core\_print_helpers.py", line 64, in _repr_latex_
    s = latex(self, mode='plain')

  File "C:\Users\Oscar\sympy\sympy\printing\printer.py", line 373, in __call__
    return self.__wrapped__(*args, **kwargs)

  File "C:\Users\Oscar\sympy\sympy\printing\latex.py", line 3011, in latex
    return LatexPrinter(settings).doprint(expr)

  File "C:\Users\Oscar\sympy\sympy\printing\latex.py", line 254, in doprint
    tex = Printer.doprint(self, expr)

  File "C:\Users\Oscar\sympy\sympy\printing\printer.py", line 293, in doprint
    return self._str(self._print(expr))

  File "C:\Users\Oscar\sympy\sympy\printing\printer.py", line 332, in _print
    return printmethod(expr, **kwargs)

  File "C:\Users\Oscar\sympy\sympy\printing\latex.py", line 1569, in _print_Symbol
    if expr in self._settings['symbol_names']:

TypeError: unhashable type: 'Medium'
```

**Comment by oscargus** [comment]
It also needs a proper `srepr` method as any additional arguments are not returned.

```
In [10]: srepr(Medium('m', 3))
Out[10]: "Medium('m')"
```

**Comment by ThePauliPrinciple** [comment]
The problem is a badly written `__new__` method:
https://github.com/sympy/sympy/blob/81cd2630631e315586f796646a7f9268e71bf484/sympy/physics/optics/medium.py#L71-L89

It's simply not storing its arguments in `_args`.

**Comment by NikhilSDate** [comment]
Could the issue also be because Medium does not properly override `__hash__`?. Creating a`__hash__` method as 
```
    def __hash__(self):
        return super().__hash__()
```
fixes the issue.
As an aside, how should `_hashable_content` be implemented for Medium, considering that `__eq__` only checks if the refractive indices are equal. I guess the hashable content should only include the refractive index so that `__hash__` and `__eq__` remain consistent. Am I right here?

**Comment by oscargus** [comment]
@ThePauliPrinciple it is indeed not really following the traditional design guidelines, but has been hanging around for eight years or so. (Still no-one seems to have tried to render a LaTeX for it...)

@NikhilSDate yes, that is one of the options. I agree with you that there should be some resemblance between `__hash__` and `__eq__`, but I am not in a position to say what is important for `Medium`. 

Still, probably the best way is to change `Medium` from inheriting `Symbol` to `Expr`(?) and then store all the arguments to make it a "proper" SymPy class. It may be that it solves the hash issue as well then.

**Comment by NikhilSDate** [comment]
If there is a consensus that such a change is needed, I can go ahead and change `Medium` so that it inherits from `Expr` and stores its arguments in `_args`. Should I go ahead?
