### ISSUE TITLE
ModuleNotFoundError: No module named 'sympy'

### ISSUE THREAD

**Issue by shivensharma01** [sympy/sympy#22660]
I tried uninstalling and installing both sympy and mpmath using pip, several times in different drives , in the C drive as well as in the D drive where I'm trying to build my application, but each time this error (ModuleNotFoundError: No module named 'sympy') is thrown in my face. Please help

**Comment by mostlyaman** [comment]
Please give the locations where you are building your application. You need to add the location where you have installed sympy to PATH environment variable. Add the location where sympy and mpmath are stored to PATH variable using this guide and try running your application.
https://www.architectryan.com/2018/03/17/add-to-the-path-on-windows-10/

**Comment by oscarbenjamin** [comment]
This is almost certainly not a sympy issue. Use the mailing list or stackoverflow to ask for help with using sympy.
