### ISSUE TITLE
Explain rel_op and rop values in core.relational

### ISSUE THREAD

**Issue by bertiewooster** [sympy/sympy#22674]
`rel_op` is a property of a relational. `rop` is used to instantiate a relational.

-----

Good idea to have a table of the valid values for `rop`: the documentation says "Valid values can be found in the keys of Relational.ValidRelationOperator," and I can't find "ValidRelationOperator" anywhere else in the documentation.

_Originally posted by @bertiewooster in https://github.com/sympy/sympy/discussions/22603#discussioncomment-1760085_

**Comment by smichr** [comment]
The reference is to an attribute of a sympy object:
```python
>>> from sympy import Relational
>>> list(Relational.ValidRelationOperator)
[None, '==', 'eq', '!=', '<>', 'ne', '>=', 'ge', '<=', 'le', '>',
'gt', '<', 'lt']
```
But a table of the values instead of a pointer to the data would be helpful.

**Comment by bertiewooster** [comment]
Is there a primer (newbie guide) to creating doctests? The [Development workflow](https://github.com/sympy/sympy/wiki/Development-workflow) wiki page mentions them several times, and it seems like I should include some for this issue. But I can't find an explanation of how to write doctests, where to put them, etc.

**Comment by oscarbenjamin** [comment]
The general doctest docs for Python are here:
https://docs.python.org/3/library/doctest.html

There are some SymPy-specific nuances that should be explained somewhere though like the fact that all imports need to be explicit and the doctests run with a particular printer enabled.

**Comment by bertiewooster** [comment]
Thanks! I added that [doctest link](https://docs.python.org/3/library/doctest.html) to the Development workflow wiki.

When I try to run that the doctest for the file I'm editing, I get import errors:

```
(venv) sympy % python sympy/core/relational.py -v
Traceback (most recent call last):
  File "/Users/jemonat/Projects/sympy/sympy/core/relational.py", line 3, in <module>
    from .basic import Atom, Basic
ImportError: attempted relative import with no known parent package
```

I ran `pip install -e .` and, just in case it was needed,  `python -m setup install` successfully; those didn't fix the issue. Is there something else I need to do?

**Comment by asmeurer** [comment]
I guess there's this https://docs.sympy.org/latest/documentation-style-guide.html#examples-section

**Comment by asmeurer** [comment]
You can't run files inside of SymPy directly. Something like `python sympy/core/relational.py` won't work. To run the doctests use the `./bin/doctest` script or the `sympy.doctest()` function.

**Comment by bertiewooster** [comment]
Great, thanks @asmeurer! This worked for me:

`./bin/doctest sympy/core/relational.py`
