### ISSUE TITLE
Sympify error in subs

### ISSUE THREAD

**Issue by proy87** [sympy/sympy#22675]
```
x = Symbol('x', real=True)
y = Symbol('y', real=True)
cy = Function(x, real=True)
(x*y).subs(y,cy)
```
Why do I get `sympy.core.sympify.SympifyError: SympifyError: x`?

**Comment by ThePauliPrinciple** [comment]
`Function` creates a new class (not an instance) that represents something like `cos`. 
In this case the error makes sense, what does it mean to multiply `x` with `f`? `x*f(x)` does make sense though. If it is the latter that you want you can do
`cy = Function('f', real = True)(x)`

**Comment by proy87** [comment]
Got it. Thank you!
In earlier versions, though, it was allowable to do so.
