### ISSUE TITLE
Mention dockerfile in documentation style guide

### ISSUE THREAD

**Issue by bertiewooster** [sympy/sympy#22708]
It would be good to mention this dockerfile somewhere e.g. here:
https://docs.sympy.org/latest/documentation-style-guide.html#installation

_Originally posted by @oscarbenjamin in https://github.com/sympy/sympy/issues/22658#issuecomment-997291692_

**Comment by skieffer** [comment]
@bertiewooster Were you already working on this? If not, I'm happy to write something.

**Comment by bertiewooster** [comment]
@skieffer I haven’t started writing anything. Go for it!

Ultimately I think the documentation contributing guidance should be made easier to follow, for example by putting it all in one place (currently it’s split between the wiki and docs.SymPy.org) and providing an end-to-end example (pick a page to improve, find the src file, make the change including a doctest, build the documentation using Docker, verify the change, run doctest, etc).
