### ISSUE TITLE
TypeError when lambdify'ing Heaviside

### ISSUE THREAD

**Issue by FranzAtGithub** [sympy/sympy#22726]
The following code generates a `TypeError: heaviside() takes from 2 to 3 positional arguments but 1 were given`

```python
import sympy

x1 = sympy.symbols('x1', real=True)
x2 = sympy.symbols('x2', real=True)

f = sympy.Max(sympy.S.Zero, sympy.Min(x1, x2))
g = sympy.tensor.array.derive_by_array(f, (x1, x2))

pyf = sympy.lambdify((x1, x2), f, 'numpy')
pyg = sympy.lambdify((x1, x2), g, 'numpy')

point = {x1: 1, x2: 2}

f_val = f.subs(point)
print(f"f_val: {f_val}")
g_val = g.subs(point)
print(f"g_val: {g_val}")

pyf_val = pyf(*point.values())
print(f"pyf_val: {pyf_val}")
pyg_val = pyg(*point.values())
print(f"pyg_val: {pyg_val}")
```

It is unclear to me why. When using `pyg??` in an IPython shell I can see the code of pyg to be

```python
def _lambdifygenerated(x1, x2):
    return (  # Not supported in Python with numpy:
  # ImmutableDenseNDimArray
[Heaviside(-x1 + x2)*Heaviside(Min(x1, x2)), Heaviside(x1 - x2)*Heaviside(Min(x1, x2))])
```

If I manually define

```python
def _pyg(x1, x2):
    return (  # Not supported in Python with numpy:
  # ImmutableDenseNDimArray
[sympy.Heaviside(-x1 + x2)*sympy.Heaviside(sympy.Min(x1, x2)), sympy.Heaviside(x1 - x2)*sympy.Heaviside(sympy.Min(x1, x2))])
```
and use `_pyg` instead of `pyg` it works just fine.

It seems to be related [#21411](https://github.com/sympy/sympy/issues/21411) but that is resolved already.

I used sympy version 1.9 and numpy version 1.21.5.

**Comment by oscargus** [comment]
> TypeError: heaviside()

Note the small h. This is the NumPy function that gives the type error although it is printed as the sympy function in the code (that is why your own function is working, it uses SymPy, not NumPy).

The other thing is:
> # Not supported in Python with numpy:
>  # ImmutableDenseNDimArray

So lambdify doesn't know how to deal with ImmutableDenseNDimArray. Hence, it just print the SymPy code for it. (How this turns into heaviside later I do not understand.)

For now, you can use 'sympy' instead, but I may suggest that you are actually aiming for something larger...
