### ISSUE TITLE
polys/numberfields: Improvements in `field_isomorphism()` implementation

### ISSUE THREAD

**Issue by skieffer** [sympy/sympy#22736]
I think there are a few places where the implementation of the `field_isomorphism()` function could be sped up, simplified, and made safer.

I will open a draft PR to show the changes I want to make. I realize this is a lot to read, but even if it just gets a cursory review, I want to document the reasons for the changes I'm making.

# Background

Given two algebraic numbers `a` and `b`, the `field_isomorphism()` function,

* [in the docs](https://docs.sympy.org/dev/modules/polys/numberfields.html#sympy.polys.numberfields.subfield.field_isomorphism)
* [in the code](https://github.com/sympy/sympy/blob/5d4477c8d2fcb3dc8c46fff3e604f7790ce22640/sympy/polys/numberfields/subfield.py#L160)

tries to write `a` as a polynomial in `b`. In other words, it is checking whether `a` belongs to the number field `Q(b)`.

Internally, it relies on two separate methods for answering this question:

* [`field_isomorphiam_pslq()`](https://github.com/sympy/sympy/blob/5d4477c8d2fcb3dc8c46fff3e604f7790ce22640/sympy/polys/numberfields/subfield.py#L82) which is fast, but might be inconclusive, and
* [`field_isomorphism_factor()`](https://github.com/sympy/sympy/blob/5d4477c8d2fcb3dc8c46fff3e604f7790ce22640/sympy/polys/numberfields/subfield.py#L136) which is slower, but definitely gives an answer.

I want to make improvements in both of the internal methods.

# Proposed Improvements

# Safety

As [noted earlier](https://github.com/sympy/sympy/pull/22464#discussion_r748897805) by @oscarbenjamin, we might want a `try/finally` block here

https://github.com/sympy/sympy/blob/5d4477c8d2fcb3dc8c46fff3e604f7790ce22640/sympy/polys/numberfields/subfield.py#L98-L100

when setting `mp.dps`.

# Speed

As noted in Issue #15743, `evalf` can be very slow when evaluating a sum whose actual value is zero. We have evaluation of zero sums in the internal method  `field_isomorphism_factor()`:

https://github.com/sympy/sympy/blob/5d4477c8d2fcb3dc8c46fff3e604f7790ce22640/sympy/polys/numberfields/subfield.py#L150-L154

and this can be quite slow.

**EXAMPLE:** Under the existing implementation, this call:

```python
a = CRootOf(x**4 + x**3 + x**2 + x + 1, -1)
a._reset()
b = exp(2*I*pi/5)
assert field_isomorphism(a, b) == [1, 0]
```

takes 9.44 seconds, but with the proposed changes, it will take only 0.74 seconds!

**QUESTION:** Are there any gotchas with swapping the order of `evalf` and `+/-` that I'm overlooking? (See my PR.) Or is this fine?

# Simplifications

Both internal methods `field_isomorphism_factor()` and `field_isomorphism_pslq()` seem to be taking unmotivated steps, which may even waste time. I want to cut these steps and simplify the code, but I want to ask if there may be something I'm missing here.

### How this function works

The basic idea is simple. Let `f(x)` be the minimal polynomial for the algebraic number `a` over `Q`, and try factoring `f(x)` over the field `Q(b)`. Then the number `a` belongs to the field `Q(b)` if and only if we find the linear factor `x - a` among the factors of `f(x)`.

### How the current implementation seems needlessly complex

As we search through the factors of `f(x)`, we consider each linear factor `x - c`, as we should. But we seem to be checking not just whether `c == a`, but also whether `-c == a`:

https://github.com/sympy/sympy/blob/5d4477c8d2fcb3dc8c46fff3e604f7790ce22640/sympy/polys/numberfields/subfield.py#L140-L154

The only reason I can think of for doing this would be to try to speed up the case where `a` was a square root. For example, suppose `a == sqrt(2)` and `f(x) == x**2 - 2`. If `sqrt(2) in Q(b)`, then `f(x)` will split over `Q(b)` into the linear factors `x - sqrt(2)` and `x + sqrt(2)`. The existing code seems to be saying, "If we happened to get the linear factor `x + sqrt(2)` first, let's look ahead and try negating the constant term in case that gives the number we're looking for."

But I don't see this as an important optimization, because we were going to get the linear factor we needed on the very next iteration anyway!

More generally, this could anticipate any case where `f(x)` was an _even function_, but I don't think there's any strong motivation to do this.

On the flip side, I think this extra step is just going to _waste_ time in any case where `-a` is _not_ a conjugate of `a`, i.e. where `f(-a) != 0`. And you don't have to look far for such a case, e.g. `f(x) == x**3 - 2`.

**QUESTION:** Am I missing some reason why this extra step is valuable?

### How this function works

First, what is the PSLQ algorithm? I am no expert, but my understanding is that you pass it a list `[r1, r2, ..., rn]` of real numbers, and it tries to find an integer-linear combination of these numbers that is nearly equal to `0`.

So, how do we use PSLQ to try to write `a` as a polynomial in `b`?

0. The algebraic numbers `a` and `b` must be real. If not, give up immediately.
1. Let `f` and `g` be the minimal polynomials of the two algebraic numbers `a` and `b`, resp.
2. Let `n` and `m` be the degrees of `f` and `g` resp.
2. Let `A` and `B` be floating point evaluations of `a` and `b` resp.
3. Form the list of real numbers, `basis = [1, B, B**2, ..., B**(m-1), -A]`.
4. Ask the PSLQ algorithm for an integer-linear combination of `basis` that is (nearly) equal to zero.
5. This amounts to writing `A` _approximately_ as a polynomial in `B` with integer coeffs.
   Form this polynomial `h(x)` and now check whether in fact `h(b) == a` _exactly_, by asking whether `f(h) % g` is the zero polynomial.

### How the current implementation seems needlessly complex

Again the code plays around with +/- cases: we check not just whether `h(b) == a` but also whether `-h(b) == a`.

https://github.com/sympy/sympy/blob/5d4477c8d2fcb3dc8c46fff3e604f7790ce22640/sympy/polys/numberfields/subfield.py#L118-L129

I'm guessing the idea here may have been to try the same "optimization" (I don't think it is one!) as we just considered in the `field_isomorphism_factor()` function, but in this case I don't think it actually applies at all.

PSLQ has given us an integer-linear combination of `[1, B, B**2, ..., B**(m-1)]` which is approximately equal to `A`. The only reason to check the "negated case" would be if you believed this _same_ linear combination might actually be closer to `-A`. I think this would represent a serious flaw in the PSLQ algorithm. I don't know much about PSLQ, but I'd be surprised if it would ever return such a result.

I note that in fact line 127 quoted above has _no unit test coverage_, and I think it is probably unreachable, due to PSLQ _not_ suffering from the flaw it would take to get there.

So again I want to simplify the code by throwing out the +/- cases.

**QUESTION:** Is there any reason to keep the +/- cases here?

**Comment by oscarbenjamin** [comment]
> As [noted earlier](https://github.com/sympy/sympy/pull/22464#discussion_r748897805) by @oscarbenjamin, we might want a `try/finally` block here

Actually it would be better to use a non-global context:
https://mpmath.org/doc/current/basics.html#temporarily-changing-the-precision

**Comment by oscarbenjamin** [comment]
> **QUESTION:** Is there any reason to keep the +/- cases here?

Not that I know of. The changes you suggest seem reasonable to me.
