### ISSUE TITLE
Algebra in non-type variable subscript space

### ISSUE THREAD

**Issue by NSC9** [sympy/sympy#22759]
[stackoverflow post](https://stackoverflow.com/questions/70502608/algebra-in-non-type-variable-subscript-space)

Summarize the problem trying to solve: this math problem using Python Sympy in Jupyter Notebook IDE: [picture of math problem](https://i.stack.imgur.com/UCEg7.png)

Describe what you’ve tried: [picture of my jupyter notebook](https://i.stack.imgur.com/a2JT8.png)

Here I have imported sympy, created a non-type variable `a_n`, then tried to rewrite the expression in my notebook. The problem I came across was trying to do algebra in the subscript space.

```
from sympy import *

a_n = symbols('a_n')

Eq(a_n,3*a_n-2)
```
--------------------------------------------------------------------------------------------------------------------------------------------
Update after 6 hours:

with help from the comment by user dancxviii from stackoverflow I have changed the code to be
```
from sympy import *
from sympy import sequence
from sympy.abc import n
a_n = symbols("a_n")
a_n1 = symbols("a_{n-1}")
a_n2 = symbols("a_{n-2}")
a_n3 = symbols("a_{n-3}")
e1 = Eq(a_n,3*a_n2+(28*a_n2*a_n3)/a_n1)
e1
```
displayed in LateX on notebook it looks like [this ](https://i.imgur.com/wcOoaYv.png)

Hoping to be able to do .subs() on a_n and replace the actual value of n if that's possible

**Comment by NSC9** [comment]
[this](url)

**Comment by ThePauliPrinciple** [comment]
`"a_n"` isn't actually something that SymPy recognises as an object with a "subscript" in a mathematical sense, the string is just considered a unique identifier. You can use `subs` with these symbols if you replace the entire symbol.

Maybe you want to use `Indexed` here instead: https://docs.sympy.org/latest/modules/tensor/indexed.html

**Comment by sylee957** [comment]
I think that it is better to use functional notation `a(n)` if you want to compute something, because sympy is never able to recognize such expression as functions.
You can even use `rsolve` because it can recognize such format
https://docs.sympy.org/latest/modules/solvers/solvers.html#sympy.solvers.recurr.rsolve
although I'm not sure if the solver for the specific equation is implemented in.
