### ISSUE TITLE
Not simplifying integer expression while using .subs(...)

### ISSUE THREAD

**Issue by Yalikesifulei** [sympy/sympy#22758]
I've ran into weird functionality of `.subs(...)` method used with `Poly`.
Let's first define a polynomial with some unknown coefficients:
<img width="272" alt="image" src="https://user-images.githubusercontent.com/9929658/147511079-408f4d50-c619-487f-9d06-df9c5a0dafac.png">
If there are some specific values for them, one may want to substitute these values and get resulting polynomial coefficients:
<img width="316" alt="image" src="https://user-images.githubusercontent.com/9929658/147511218-707bd3e8-e4f6-4322-ae7d-31487b3f432a.png">
But using integer values of `a`, `b` and `c` doesn't work as intended and provides false answer. However, if a float value of `b` is given, it gives another result, but without numerical value of sqrt(2):
<img width="374" alt="image" src="https://user-images.githubusercontent.com/9929658/147511404-4d04d8c7-fdd7-4099-a68b-fee9595363e0.png">
Finally, using float value of `c` leads to desired result, since all divisions and exponentiations are done with float values:
<img width="345" alt="image" src="https://user-images.githubusercontent.com/9929658/147511469-bed79bf7-6682-409f-a56a-03c80e1cfc64.png">
So, is it really the inteded functionality of `.subs(...)` function? Personally, I find it a bit confusing, since Python itself makes no difference in such calculations. I guess this way of work is wanted in some cases, but not with polynomials, since it breaks some other functions like `.coeff_monomial(...)`.

**Comment by oscarbenjamin** [comment]
If you use `ipython` or `isympy` in the terminal then it makes pretty text output that you can include directly in github like this:
```python
In [410]: x, a, b, c = symbols('x, a, b, c')

In [411]: expr = (x - exp(a/c))*(x - sqrt(c)*exp(b/c))

In [412]: expr
Out[412]: 
⎛     a⎞ ⎛      b    ⎞
⎜     ─⎟ ⎜      ─    ⎟
⎜     c⎟ ⎜      c    ⎟
⎝x - ℯ ⎠⋅⎝- √c⋅ℯ  + x⎠
```
This way you can also copy-paste the code from github and it's easier to read than a screenshot.

You don't show what `expr` is in your examples so here it is:
```python
In [413]: expr.subs({a: 0, b:1, c:2})
Out[413]: 
        ⎛        1/2⎞
(x - 1)⋅⎝x - √2⋅ℯ   ⎠

In [414]: Poly(_)
Out[414]: Poly(x**2 - x*(exp(1/2))*(sqrt(2)) - x + (exp(1/2))*(sqrt(2)), x, exp(1/2), sqrt(2), domain='ZZ')

In [415]: expr.subs({a: 0, b:1.0, c:2})
Out[415]: (x - 1)⋅(x - 1.64872127070013⋅√2)

In [416]: Poly(_)
Out[416]: 
Poly(1.0*x**2 - 1.64872127070013*x*(sqrt(2)) - 1.0*x + 1.64872127070013*(sqrt(2)), x, sqrt(2), domain='RR')

In [417]: expr.subs({a: 0, b:1.0, c:2.0})
Out[417]: (x - 2.33164398159712)⋅(x - 1)

In [418]: Poly(_)
Out[418]: Poly(1.0*x**2 - 3.33164398159712*x + 2.33164398159712, x, domain='RR')
```
Notice that the first two polynomials include `sqrt(2)` as a generator along with `x` and the first also includes `exp(1/2)`. If `sqrt(2)` is a generator then any term involving `sqrt(2)` is for a different monomial e.g.:
```python
In [419]: Poly(expr.subs({a: 0, b:1.0, c:2}))
Out[419]: 
Poly(1.0*x**2 - 1.64872127070013*x*(sqrt(2)) - 1.0*x + 1.64872127070013*(sqrt(2)), x, sqrt(2), domain='RR')

In [420]: Poly(expr.subs({a: 0, b:1.0, c:2})).coeff_monomial(x*sqrt(2))
Out[420]: -1.64872127070013
```
If you want this to be considered strictly an univariate polynomial in `x` then you should specify the generator `x` explicitly:
```python
In [421]: Poly(expr.subs({a: 0, b:1, c:2}), x)
Out[421]: Poly(x**2 + (-sqrt(2)*exp(1/2) - 1)*x + sqrt(2)*exp(1/2), x, domain='EX')

In [422]: _.coeff_monomial(x)
Out[422]: 
      1/2    
- √2⋅ℯ    - 1
```
