### ISSUE TITLE
manualintegrate outputs wrong result

### ISSUE THREAD

**Issue by mizusato** [sympy/sympy#22757]
The expression `manualintegrate(sin(x),y)` produces a wrong result.
```
>>> from sympy import *
>>> from sympy.integrals.manualintegrate import *
>>> x,y = symbols('x y')
>>> manualintegrate(sin(x),y)  // wrong
-cos(x)
>>> manualintegrate(log(x),y)  // correct
y*log(x)
```
version: SymPy 1.9

**Comment by MiguelAMLucero** [comment]
Is this issue available to work on?

**Comment by smichr** [comment]
It is open and there is no referencing PR...it's available.

**Comment by dianet97** [comment]
@smichr  @oscarbenjamin manualintegrate doesn't seem to work for any of the standard trigonometric functions, i.e,
`manualintegrate(trig(x),y)` 
returns the wrong answer. Weirdly enough it does work for inverse trigonometric functions (atan,asin,acos,acot,acsc,asec). As an example:
`>>>>manualintegrate(asin(x),y) `
`y*asin(x)`
This begs the question if Log and these inverse trig functions are treated similarly in the code (for this instance anyways)? Turning on the debugging and stepping through we find that   `def integral_is_subclass(*klasses):` in manualintegrate.py  hits a *kclasses argument of `(<class 'sympy.core.mul.mul>, log, atan, asin, acos, acot, acsc, asec)` at some point

**Comment by MiguelAMLucero** [comment]
@smichr @oscarbenjamin @ddtcode when you run
 `>>> integral_steps(sin(x), y)` 
the output is `TrigRule(func='sin', arg=x, context=sin(x), symbol=y)`, 
but when you run `>>> integral_steps(log(x),y)` 
the rule comes out as `ConstantRule(constant=log(x), context=log(x), symbol=y)`. 
The same ConstantRule comes out with inverse trig functions. It should detect trig functions in this case as constants.
Also, I tried to run the same integral in symPy gamma, and this happened
<img width="635" alt="Screen Shot 2021-12-28 at 20 40 19" src="https://user-images.githubusercontent.com/92400491/147628468-6400acc9-9c47-4974-8ad8-e0d6b3d2c432.png">

**Comment by ddtcode** [comment]
@MiguelAMLucero Sorry for not "@-ing" you in my previous message!

**Comment by ddtcode** [comment]
**I think I might have found the issue**.  In `manualintegrate.py` there is a `def key(integral)` being called right after `integral = IntegralInfo(integrand, symbol)` (line 1292). This function  has the following conditionals: 

`        if isinstance(integrand, TrigonometricFunction): return TrigonometricFunction`
`        elif isinstance(integrand, Derivative):  return Derivative`
`        elif symbol not in integrand.free_symbols: return Number`
`        else : .....`
 That is,  if you have a trigonometric function it never hits the case of if you're doing a sort of "partial-antiderivate" (where you'd want the constant rule applied)  like in our case.  Change the order of these if statements fixes the problem. Changing to:
`        if symbol not in integrand.free_symbols: return Number`
`        elif isinstance(integrand, Derivative):  return Derivative`
`        else isinstance(integrand, TrigonometricFunction): return TrigonometricFunction`
`        else : .....`
Gives us :
`>>>>manualintegrate(sin(x),y)`
`y*sin(x)`

I wonder of the possible adverse effects though.

**Comment by ddtcode** [comment]
The change fails on 4 tests in (surprisingly)  sympy/physics/control/tests/test_control_plots.py

**Comment by MiguelAMLucero** [comment]
@ddtcode @smichr @oscarbenjamin 
I added a second condition inside key, to check if the argument of the trig function and the symbol are the same, seems to work, but let's see after the sympy tests
`if isinstance(integrand, TrigonometricFunction) and integrand.args == symbol:
            return TrigonometricFunction
        elif isinstance(integrand, Derivative):
            return Derivative
        elif symbol not in integrand.free_symbols:
            return Number`
If this works, can I make a PR?

**Comment by ddtcode** [comment]
@MiguelAMLucero  When I tried that it didn't pass the test I mentioned.

**Comment by ddtcode** [comment]
It seems that the test fail regardless of whether or not I make changes. Makes me think I have some library mismatch somewhere causing these errors. Consequently, I don't know if my current fix is actually right

**Comment by oscarbenjamin** [comment]
You could just open a pull request with the changes and then we can see if the tests fail in CI.

**Comment by MiguelAMLucero** [comment]
So the test failed even without the changes? could that be something else? 
Thank you very much, I'll open the PR to see if it fails

**Comment by MiguelAMLucero** [comment]
ohh sorry @oscarbenjamin I didn't notice that you were commenting to @ddtcode. my bad

**Comment by oscarbenjamin** [comment]
Anyone is welcome to open a PR.

**Comment by ddtcode** [comment]
@MiguelAMLucero @oscarbenjamin I'm trying to do one now
