### ISSUE TITLE
Imaginary Exponents, decimal expressions

### ISSUE THREAD

**Issue by JoshZeidner** [sympy/sympy#22756]
**_I_** to the exponent 2/3 gives me a decimal power expression.

_not a critical bug but fairly important for complex analysis._

shown here: https://gist.github.com/JoshZeidner/3cedc22657021a1b412a4466a9315592#file-untitled0-ipynb

**Comment by praneethratna** [comment]
You can use sympy Rational for avoiding the simplification of 2/3.
```
>>> I**(Rational(2, 3))
I**(2/3)
```

**Comment by JoshZeidner** [comment]
@praneethratna, thanks. Works with Quaternions too: https://gist.github.com/JoshZeidner/02354370bafff3b887d1472b4fb5d740
