### ISSUE TITLE
gcd function has different behaviors for different symbols

### ISSUE THREAD

**Issue by auntyellow** [sympy/sympy#22766]
```python
from sympy import *

a, b, c, d, e, f, g, h, j, k, m, n, p, q, r, s = symbols('a, b, c, d, e, f, g, h, j, k, m, n, p, q, r, s')
print(gcd(j*(b*k - e*j), -k*(-b*k + e*j)))
print(gcd(m*(b*n - e*m), -n*(-b*n + e*m)))
print(gcd(p*(b*q - e*p), -q*(-b*q + e*p)))
print(gcd(r*(b*s - e*r), -s*(-b*s + e*r)))
```

output:
```
b*k - e*j
b*n - e*m
-b*q + e*p
-b*s + e*r
```

the result has no problem (both positive and negative are right).

looks different behaviors before and after 'o' (I haven't tested 'o' yet).

**Comment by oscarbenjamin** [comment]
It's just about the ordering of the generators. You can get a consistent ordering by specifying what you want the leading generator to be:
```python
   ...: print(gcd(j*(b*k - e*j), -k*(-b*k + e*j), b))
   ...: print(gcd(m*(b*n - e*m), -n*(-b*n + e*m), b))
   ...: print(gcd(p*(b*q - e*p), -q*(-b*q + e*p), b))
   ...: print(gcd(r*(b*s - e*r), -s*(-b*s + e*r), b))
b*k - e*j
b*n - e*m
b*q - e*p
b*s - e*r
```
The default ordering for symbols is prescribed by this:
https://github.com/sympy/sympy/blob/27613158382a668605a21616706a8d64a3573997/sympy/polys/polyutils.py#L13-L21
Spelled out more clearly that is:
```python
In [8]: ''.join(sorted(_gens_order, key=_gens_order.__getitem__))
Out[8]: 'xyzpqrstuvwabcdefghijklmno'
```

**Comment by auntyellow** [comment]
`xyzpqrstuvwabcdefghijklmno`, that's interesting : -)
