### ISSUE TITLE
From Sympy Import cursived?

### ISSUE THREAD

**Issue by NSC9** [sympy/sympy#22771]
```
From Sympy Import cursived
cursived = symbols('cursived')

```
https://en.wikipedia.org/wiki/%E2%88%82

Adding this non-type symbol would be useful when I simply want to symbolize written math using LateX outputs in Jupyter Notebook. 

Could add this to the .abc module like so
```
In [ ] from Sympy.abc import cursived
In [ ] cursived
```
```
Out [1]  <picture of Unicode: U+2202>
```

https://docs.sympy.org/latest/modules/abc.html

https://github.com/sympy/sympy/blob/master/sympy/abc.py 

In the github link, we could add cursived after line 79 

Note: cursived is read as "cursive d" as described in the linked wikipedia page. 

Could also use "partial" instead of "cursived"

**Comment by ThePauliPrinciple** [comment]
You can get the symbol using `Symbol('\partial')`. Would that work in your case? Can you give an example of what you actually want to do? Maybe there are better solutions already in SymPy.

**Comment by NSC9** [comment]
> You can get the symbol using `Symbol('\partial')`. Would that work in your case? Can you give an example of what you actually want to do? Maybe there are better solutions already in SymPy.

That will work! Thanks, how do you know about `Symbol('\partial')?` Not sure where to find that in the docs

**Comment by ThePauliPrinciple** [comment]
It's not really a feature, the name of this symbol will just be `'\partial'`, which is then interpreted as the "cursive d" symbol by the LaTeX interpreter, but not by SymPy.
