### ISSUE TITLE
SymPy seems to think that 0/0 = 0

### ISSUE THREAD

**Issue by nathancarter** [sympy/sympy#22791]
```
Python 3.7.12 (default, Oct 12 2021, 03:36:26) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sympy
>>> sympy.__version__
'1.9'
>>> x,y = sympy.symbols('x,y')
>>> (x/(x+y)).subs({x:0,y:0})
0
```

**Comment by oscargus** [comment]
The reason is that the substitution is done one symbol at a time. You can use `.subs(..., simultaneous=True)` to get something along the line of what you expect.

**Comment by nathancarter** [comment]
Ah, thanks.  It is normal CAS behavior (though disappointing anyway) that it simplifies `0/(0+y)` to 0 without knowing what y is.  Since this is what lots of CAS do, no shade on SymPy in particular. :)  Thanks again!

**Comment by smichr** [comment]
It is the same for `x*y` -- it's not 0 unless `y` is finite; `x/y` just appears a bit more egregious because it is ignoring division by 0. Note that another way to leave expressions alone is to do substitutions in an `evaluate(False)` context:
```python
>>> with evaluate(False):
...   (x/(x+y)).subs({x:0,y:0})
...
0/(0 + 0)
>>> _.n()
nan
>>> (x/(x+y)).subs({x:0,y:0},simultaneous=1)
nan
```

**Comment by faze-geek** [comment]
This doesn't seem to be an issue which potentially needs some work ,hence should be closed ??

**Comment by oscargus** [comment]
Yeah, and just as `x/x` is evaluated to `1`.

Yes, I think that this can be closed Feel free to reopen.
