### ISSUE TITLE
docs: Support `make livehtml` in the Docker image

### ISSUE THREAD

**Issue by skieffer** [sympy/sympy#22800]
> By the way, `make livehtml` will also open a live server, and in addition, it live rebuilds the docs whenever an update is made.

_Originally posted by @asmeurer in https://github.com/sympy/sympy/issues/22655#issuecomment-997471982_

**Comment by skieffer** [comment]
We should support `make livehtml` in the Docker image built by `doc/Dockerfile.htmldoc`.

**Comment by bertiewooster** [comment]
Per another comment, how about modifying doc/requirements.html to remove the versions of dependencies? For example, instead of pinned:

`matplotlib==3.4.3`

simply

`matplotlib`

**Comment by skieffer** [comment]
> how about modifying doc/requirements.html to remove the versions of dependencies?

Will do.
