### ISSUE TITLE
let some sort of EmptySet represent null object in geometry

### ISSUE THREAD

**Issue by smichr** [sympy/sympy#22807]
Projections and intersections that are non-existant could be represented by EmptySet. Currently, projections raise an error and intersections return `[]`:

```python
>>> s
Segment2D(Point2D(0, 0), Point2D(0, 1))
>>> t
Segment2D(Point2D(1, 0), Point2D(2, 1/2))
>>> s.projection(t)
Segment2D(Point2D(0, 0), Point2D(0, 1/2))
>>> t.projection(s)
Traceback (most recent call last):
...
AttributeError: 'EmptySet' object has no attribute 'direction'

>>> s.intersection(t)
[]
```

Alternatively a geometric "Null" object -- not sure what it should be called, maybe GeometricEmptySet? -- could be created and used instead, so all geometric methods with it could return a null result (rather than giving EmptySet geometry related methods. e.g.
`GeometricEmptySet.projection(Line(Eq(x,0))) -> GeometricEmptySet`.

**Comment by praneethratna** [comment]
`GeometricEmptySet` is great but why not just `EmptySet` as both represent the same right? Also should `t.projection(s)` return `EmptySet` instead of an error?

**Comment by smichr** [comment]
> Why can't we use `EmptySet`

I can't see the forest because a Tree is in my way! It *is* using EmptySet and I guess that's fine. In the case above the EmptySet should be detected before trying to do the next step: `projected` in the following test in "sympy/sympy/geometry/line.py", line 976, in projection" was probably EmptySet
```python
if self.direction.dot(projected.direction) < 0:
```
That should have been detected and the routine should have returned EmptySet.

There will be no problem using EmptySet in geometry as long as there is no method of Set that could be confused with a method of GeometricEntity.

So for this issue, the fix is to make `projection` return EmptySet when there is no projection of one entity onto another and see if other cases where EmptySet is returned that the right thing is being done so there is not a property error raised internal to a function when it would make sense to return the EmptySet from the function.

**Comment by asmeurer** [comment]
I disagree that EmptySet should be used in geometry. The type of the returned object should be a geometry object, so unless a function always returns a Set, EmptySet should not be used. It seems that the geometry objects mixin Set (not sure if I agree that's a great idea, but it's already there), but there is a separate GeometryEntity class that has several methods. If a geometry method returns EmptySet, it won't have any of the methods of GeometryEntity. So I think it would be a good idea to make a distinct EmptySpace object that subclasses GeometryEntity for use in the geometry module.
