### ISSUE TITLE
Non-SI units mentioned in the SI missing/incomplete in SymPy

### ISSUE THREAD

**Issue by faze-geek** [sympy/sympy#22819]
I was going through the `physics ` module when I came across PR #22741 (which changed the state of l unit , added L in  `physics.units`) .I realised that though L is not an Si unit of volume (m^3 is)  it is mentioned in Wikipedia as a Non SI unit accepted by SI( ml is) . I feel there is a lack of such units for other physical quantities .
Like °C-Celsius ,f-fahrenheit for Temperature . Like cal-calorie for Energy . Like t-tonne for Mass 
I feel such units could be included since SymPy is very broadly used and currently some such units Min( minute ), L ( litre ) are already present in` physics/units/__init__.py`.

**Comment by Alt-Shivam** [comment]
Hey @faze-geek 
I would like to work on this issue.
Thanks

**Comment by faze-geek** [comment]
Welcome @Alt-Shivam , good to hear that you feel this issue makes sense !
Wait for some other suggestions (Ping @oscarbenjamin , Ping @oscargus ) .Then we can start working on this issue.
Regards.

**Comment by Alt-Shivam** [comment]
Yeah, let's see :)

**Comment by oscargus** [comment]
I think that we only should add non-SI units to `si` that actually are officially accepted, https://en.wikipedia.org/wiki/Non-SI_units_mentioned_in_the_SI

If not, there will be quite a bit arbitrary if a unit should be added or not.

**Comment by faze-geek** [comment]
> I think that we only should add non-SI units to `si` that actually are officially accepted, https://en.wikipedia.org/wiki/Non-SI_units_mentioned_in_the_SI

Yes actually I wanted to handle this itself but didn't know the page which I referred online and its examples were credible or not . 
I'll work on this issue as soon as possible .
Thanks .
