### ISSUE TITLE
dsolve works in v1.8 but fails in 1.9 on this function

### ISSUE THREAD

**Issue by DwaipayanDeb** [sympy/sympy#22815]
The following code works in v1.8 but shows errors in v1.9 of sympy

```from sympy import *
t,y=symbols('t y')
f=symbols('f',cls=Function)
y=f(t)
eq1=Eq(y.diff(t,2)+exp(-t)*y.diff(t),-y)
dsolve(eq1)

**Comment by oscarbenjamin** [comment]
This has been fixed on master since version 1.9. The fix was a8d12f4058928f636077e1943a196807fdfbc7c4 from #22217.

Current master gives the same as 1.8:
```python
In [1]: t,y=symbols('t y')
   ...: f=symbols('f',cls=Function)
   ...: y=f(t)
   ...: eq1=Eq(y.diff(t,2)+exp(-t)*y.diff(t),-y)
   ...: dsolve(eq1)
Out[1]: 
          ⎛ 4    4  -2⋅t    3  -t    2    ⎞        ⎛ 3  -t    3  -3⋅t    2    2  -2⋅t      -t    ⎞        
          ⎜t    t ⋅ℯ       t ⋅ℯ     t     ⎟        ⎜t ⋅ℯ     t ⋅ℯ       t    t ⋅ℯ       t⋅ℯ      ⎟    ⎛ 6⎞
f(t) = C₂⋅⎜── - ──────── + ────── - ── + 1⎟ + C₁⋅t⋅⎜────── - ──────── - ── + ──────── - ───── + 1⎟ + O⎝t ⎠
          ⎝24      24        6      2     ⎠        ⎝  12        24      6       6         2      ⎠
```
That's a series solution although ideally `dsolve` would not return series solutions by default (#15916).

**Comment by praneethratna** [comment]
Should a test be added for this case and this issue can be closed?

**Comment by oscarbenjamin** [comment]
Yes, a test could be added.

**Comment by smichr** [comment]
A test was added in the referenced PR. Another test is not needed unless it is testing something uniquely special to the change that was made. Perhaps one of you can assess that -- is this failing case something that the change in the PR (which is tested) would be expected to have fixed?

**Comment by oscarbenjamin** [comment]
I agree. This can just be closed.
