### ISSUE TITLE
Make it easier to find contribution guidelines on mailing list site

### ISSUE THREAD

**Issue by bertiewooster** [sympy/sympy#22810]
New SymPy community members frequently email the mailing list asking how to contribute. While the link is at the top of the [mailing list page](https://groups.google.com/g/sympy), the link text isn't descriptive--it's only the word "here":

> If you are interested in contributing, please start [here](https://github.com/sympy/sympy/wiki/Introduction-to-contributing).

Recommend changing the link text to something more descriptive, for example:

> Here's how to [start contributing to SymPy](https://github.com/sympy/sympy/wiki/Introduction-to-contributing) if you are interested.

Making the link text descriptive also serves as a call to action, and helps with SEO (search engine optimization).

**Comment by asmeurer** [comment]
I changed it like you suggested.

**Comment by bertiewooster** [comment]
Great, thanks for the quick improvement!
