### ISSUE TITLE
`parse_expr` evaluates `is None` expression to False since 1.9

### ISSUE THREAD

**Issue by mbergnl** [sympy/sympy#22822]
Since version 1.9 `parse_expr`  evaluates a `is None` expression to False instead of True (as I would expect) when logic_data passed contains a  a None value.

```python
from sympy.parsing.sympy_parser import parse_expr

logic = "some_parameter is None"
data = {'some_parameter': None}
print(parse_expr(logic, data))  # evaluates to True in 1.8 and False in 1.9
data = {'some_parameter': 'got it'}
print(parse_expr(logic, data))  # evaluates to False
```

Expected result is True, False and not False, False

**Comment by oscarbenjamin** [comment]
This changed in 4677007e5041194d28017299a40fdebcc0a15952 from #19501

**Comment by Alt-Shivam** [comment]
Yes, @mbergnl same with SymPy 1.5.1

![image](https://user-images.githubusercontent.com/81817735/148647455-e788b5ef-4ec8-47f1-95c3-e7630a4c9088.png)

I am looking into the code 
Will be really happy If I could do something about this issue.
Thanks :)
