### ISSUE TITLE
No replacement of Indexed in Sum

### ISSUE THREAD

**Issue by pkrezel** [sympy/sympy#22826]
for i in range(0, 6):
    exec(f"c_{i} = symbols('c_{i}')")
y = symbols("y")
x = (c_1/c_0)*y
for i in range(2, 6):
    exec(f"t_{i}=c_0**{i-1}*c_{i}/c_1**{i}")
eq_x = 1 -x + Sum(Indexed('t',k)*x**k, (k,2,5)).doit()

x is replace but but not the Indexed

**Comment by oscarbenjamin** [comment]
It looks like you're expecting `exec` to do something that it doesn't do.

I'm closing this. GitHub issues are not for getting help with using SymPy. For that you can use the mailing list or StackOverflow:
https://groups.google.com/g/sympy

**Comment by pkrezel** [comment]
Excuse-me to have complicated  the problem.
However, if I do:
x = (c_1/c_0)*y
t_2=c_0*c_2/c_1**2
t_3=c_0*c_2/c_1**2
eq_x = 1 -x + Sum(Indexed('t',k)*x**k, (k,2,3)).doit()

The values associated to Indexed('t',k) are not replaced.

**Comment by oscarbenjamin** [comment]
1. Please use backticks to format code in GitHub
2. Please actually show the output that you see
3. Please clearly explain how it differs from what you expected
4. Please clearly explain why you expected to see something different

When I try this it seems to be working fine:
```python
In [1]: for i in range(0, 6):
   ...:     exec(f"c_{i} = symbols('c_{i}')")
   ...: 

In [2]: x = (c_1/c_0)*y
   ...: t_2=c_0*c_2/c_1**2
   ...: t_3=c_0*c_2/c_1**2
   ...: eq_x = 1 -x + Sum(Indexed('t',k)*x**k, (k,2,3)).doit()

In [3]: eq_x
Out[3]: 
             2  2          3  3     
    c₁⋅y   c₁ ⋅y ⋅t[2]   c₁ ⋅y ⋅t[3]
1 - ──── + ─────────── + ───────────
     c₀          2             3    
               c₀            c₀  
```
The assignments to `t_2` and `t_3` above are not expected to have any effect on `eq_x`. You need to use `.subs` to replace those:
```python
In [5]: t = IndexedBase('t')

In [6]: eq_x.subs({t[2]: c_0*c_2/c_1**2, t[3]: c_0*c_2/c_1**2})
Out[6]: 
               2          3
    c₁⋅y   c₂⋅y    c₁⋅c₂⋅y 
1 - ──── + ───── + ────────
     c₀      c₀        2   
                     c₀   
```
As I mentioned above these are questions for StackOverflow. GitHub is for reporting bugs.

**Comment by pkrezel** [comment]
Thank you for your explanations.
