### ISSUE TITLE
Can't filter results 

### ISSUE THREAD

**Issue by meeker0** [sympy/sympy#22828]
Please add option to filter results from `solve()`
I was solving a problem where only non rational or integer values are needed !
So, it would be great if `solve()` had a flag like `filter = int/float`

**Comment by oscarbenjamin** [comment]
You can do this with `solve` by setting assumptions on the symbol to be solved for:
```python
In [8]: x = Symbol('x', integer=True)

In [9]: p = (x - 1)*(x**2 + 1)

In [10]: solve(p, x)
Out[10]: [1]

In [11]: x = Symbol('x', complex=True)

In [12]: p = (x - 1)*(x**2 + 1)

In [13]: solve(p, x)
Out[13]: [1, -ⅈ, ⅈ]
```
You can also just filter the solutions after they are returned from solve:
```python
In [16]: sol = solve(p, x)

In [17]: sol
Out[17]: [1, -ⅈ, ⅈ]

In [18]: [s for s in sol if s.is_real]
Out[18]: [1]
```
You can also use `solveset`:
```python
In [19]: solveset(p, x)
Out[19]: {1, -ⅈ, ⅈ}

In [20]: solveset(p, x, Reals)
Out[20]: {1}
```
