### ISSUE TITLE
limit function gives wrong answer in some cases

### ISSUE THREAD

**Issue by er888kh** [sympy/sympy#22824]
I was using `isympy` to solve a few limits, all of which were related to L'Hopital's rule. I found out that some of the answers were wrong. For example:
```python
f = (x ** 2 + 10 * x + 16) / (12 + 6 * cbrt(x))
print(limit(f, x, -8))
# Says 0
```
Which by L'Hopital's rule should have been `-12`. Interestingly, if one changes the variable `x` to `t**3` and takes the limit as `t` approaches `-2`, `isympy` can successfully find the correct limit.
I am using Sympy 1.9 with python 3.10.1 on Arch Linux.

**Comment by oscarbenjamin** [comment]
In SymPy `cbrt(x) = x**Rational(1, 3)` uses the principle value so the denominator is not zero at `x=-8`:
```python
In [27]: denom(f).subs(x, -8)
Out[27]: 
        3 ____
12 + 12⋅╲╱ -1 

In [28]: denom(f).subs(x, -8).n()
Out[28]: 18.0 + 10.3923048454133⋅ⅈ
```
You can use `real_root` to get the real cube root for negative values:
```python
In [30]: f = (x ** 2 + 10 * x + 16) / (12 + 6 * real_root(x, 3))

In [31]: f.limit(x, -8)
Out[31]: -12
```
https://en.wikipedia.org/wiki/Cube_root#Complex_numbers

**Comment by er888kh** [comment]
Thank you, now I understand. So is this not an issue? Should it be closed?

**Comment by oscarbenjamin** [comment]
Yes, it should be closed.
