### ISSUE TITLE
example where solve failed

### ISSUE THREAD

**Issue by pkrezel** [sympy/sympy#22821]
```
x, c_0, c_1, c_2, t = symbols("x c_0 c_1 c_2 t")
eq = c_0 + c_1*x+c_2*x**2
c_0 = t
a_0, a_1, a_2, a_3, a_4, a_5 = symbols("a_0 a_1 a_2 a_3 a_4 a_5 ")
a_6, a_7, a_8, a_9 = symbols("a_6 a_7 a_8 a_9 ")
a_0 = 0
x = a_0 + a_1*t + a_2*t**2 + a_3*t**3 + a_4*t**4 + a_5*t**5 +  a_6*t**6 + a_7*t**7 + a_8*t**8 + a_9*t**9 
eq1 = eq.expand()
eq2= collect(eq1,t)
p = Poly(eq,t)
L = p.all_coeffs()
L = list(reversed(L))
solve(L[1:6], [a_1, a_2, a_3, a_4, a_5])  # OK
solve(L[1:7], [a_1, a_2, a_3, a_4, a_5, a_6]) # Begins to fail, but works in "scientific workplace"
```

**Comment by oscarbenjamin** [comment]
It is not clear what point you are making. The code shown does not seem to demonstrate anything interesting.

Can you explain what the problem is?

**Comment by smichr** [comment]
This and your previous issue suggest that there is some confusion about how python and sympy interact. You define `eq` in terms of symbols and then define those symbols after already defining the equation. This does not change the equation. There is never a version of equation that depends on `t`. One way to make progress in understanding is to let the interactive prompt be your instructor. Print your variables after each command to see what happened. e.g. after defining `c_0 = t` if you checked the value of `eq` you would find that it had not changed.
```python
>>> x, c_0, c_1, c_2, t = symbols("x c_0 c_1 c_2 t")
>>> eq = c_0 + c_1*x+c_2*x**2
>>> eq
c_0 + c_1*x + c_2*x**2
>>> c_0 = t
>>> eq
c_0 + c_1*x + c_2*x**2
>>> c_0
t
>>> eq = c_0 + c_1*x+c_2*x**2
>>> eq
c_1*x + c_2*x**2 + t
```
