### ISSUE TITLE
subs failure

### ISSUE THREAD

**Issue by pkrezel** [sympy/sympy#22820]
x = symbols("x")
c_0 = symbols("c_0")
c_1 = symbols("c_1")
c_2 = symbols("c_2")

eq = c_0 + c_1*x+c_2*x**2

t = symbols("t")
c_0 = t

a_0 = symbols("a_0")
a_1 = symbols("a_1")
a_2 = symbols("a_2")
a_3 = symbols("a_3")
a_4 = symbols("a_4")
a_5 = symbols("a_5")

x = a_0+a_1*t+a_2*t**2+a_3*t**3+a_4*t**4+a_5*t**5

eq = c_0 + c_1*x+c_2*x**2

If I do eq.subs(a_0, 0), nothing change !

**Comment by ThePauliPrinciple** [comment]
SymPy objects are not mutable generally, so you should be doing `eq = eq.subs(a_0, 0)`

**Comment by anutosh491** [comment]
```
x = symbols("x")
c_0 = symbols("c_0")
c_1 = symbols("c_1")
c_2 = symbols("c_2")

eq = c_0 + c_1*x + c_2*x**2

t = symbols("t")
c_0 = t

a_0 = symbols("a_0")
a_1 = symbols("a_1")
a_2 = symbols("a_2")
a_3 = symbols("a_3")
a_4 = symbols("a_4")
a_5 = symbols("a_5")

x = a_0+a_1*t + a_2*t**2 + a_3*t**3 + a_4*t**4 + a_5*t**5

eq = c_0 + c_1*x + c_2*x**2
```
Is this what you mean ! The equations you posted above lack operators here and there . Anyways this works perfectly fine for me

**Comment by smichr** [comment]
The replacement worked, but unless you save it to a new variable or print it, you won't see the result. Consider the pure SymPy-free example:
```python
>>> s = "A"
>>> s.replace("A", "B")
'B'
>>> s
'A'
```
`s` didn't change, but the result of the replacement is not the same as `s`. If you want `s` to have the new value then you have to re-assign it as `s = s.replace("A","B")` as @ThePauliPrinciple pointed out for the SymPy example.

This is not an issue with SymPy. But if you have more questions, the mailing list would be a good place to raise them.
