### ISSUE TITLE
Error in latex for sum with indexed

### ISSUE THREAD

**Issue by pkrezel** [sympy/sympy#22825]
for i in range(1, 5):
    exec(f"t_{i} = symbols('t_{i}')")
x = symbols("x")
sum1 = 1 -x + Sum(Indexed('t',k)*x**k, (k,2,5)) $ OK 
sum1.doit() $ OK 
latex(sum1) $ KO
x^{5} {t}{5} + x^{4} {t}{4} + x^{3} {t}{3} + x^{2} {t}{2} - x + 1=0

**Comment by oscarbenjamin** [comment]
I don't see any problem. Please explain with actual words what the problem is.

**Comment by oscarbenjamin** [comment]
Presumably you want `latex(sum1.doit())`

**Comment by pkrezel** [comment]
Normally the latex code should be:
x^{5} t_{5} + x^{4} t_{4} + x^{3} t_{3} + x^{2} t_{2} - x + 1=0

**Comment by oscarbenjamin** [comment]
This is already fixed if you use the latest version of SymPy:
```python
In [49]: latex(sum1.doit())
Out[49]: 'x^{5} {t}_{5} + x^{4} {t}_{4} + x^{3} {t}_{3} + x^{2} {t}_{2} - x + 1'
```
