### ISSUE TITLE
Change unit prefix when simplifying units

### ISSUE THREAD

**Issue by rikardn** [sympy/sympy#22838]
Is there a way of automatically changing he prefix of units like:

```python
> from sympy.physics import units
> sympy.simplify(units.kg / 1000)
kilogram/1000
```

If not, would it be useful to let simplification (or `units.convert_to` or similar) be able to automatically change the prefix, outputting `gram`, in this case?

**Comment by Alt-Shivam** [comment]
Hey @rikardn 
I think [this](https://stackoverflow.com/questions/42340642/how-to-convert-unit-prefixes-in-sympy/54334341) can help.

**Comment by ThePauliPrinciple** [comment]
```python
>>> from sympy.physics import units
>>> units.convert_to(units.kg/1000, units.g)
g
```

**Comment by rikardn** [comment]
Thanks, but I was thinking something that does this automatically like:

```python
>>> units.convert_to(units.kg/1000)
gram
>>> unit.convert_to(unit.kg/1000000)
microgram
```

**Comment by ThePauliPrinciple** [comment]
That's still ambiguous to me. Would `kg/2` then be `0.5kg` or `500g` or `5hg` and why? I don't think automatic selection of a prefix should be the default, since that way you can't prevent it from happening. A function which converts it to the "closest" prefix (by some metric) could be nice.

**Comment by smichr** [comment]
This is not exactly what you are asking but might generate some ideas:
```python
def mag(x):
    """
    >>> [mag(Integer(10)**-i) for i in range(10)]
    [0, -1, -2, -3, -3, -3, -6, -6, -6, -9]
    >>> [mag(Integer(10)**i) for i in range(10)]
    [0, 1, 2, 3, 3, 3, 6, 6, 6, 9]
    """
    a = abs(x)
    if a < 1000 and 1000*a > 1:
        return int(log(a, 10))
    if a < 1:
        -int(log(1/a, 10**3))*3
    return int(log(a, 10**3))*3

def npre(x, u):
    from sympy.physics.units.prefixes import PREFIXES as P
    from sympy.physics.units.prefixes import prefix_unit
    i = mag(x)
    for k in P:
        if P[k].args[2] == i:
            return x/10**i*prefix_unit(u,{k: P[k]})[0]

>>> npre(333, m)
3.33*hectometer
```

**Comment by rikardn** [comment]
Thanks @ThePauliPrinciple and @smichr for your thoughts and suggestions. I realize that what I was thinking is only going to work if the multipliers directly correspond to available prefixes. For other numbers (like 333) it would be less clear what to do. Perhaps "engineering" form and finding closest prefix could be one useful thing, but now I believe this to be implementation specific rather than something that could go into sympy.
