### ISSUE TITLE
Update documentation, Wiki, README to not use git://

### ISSUE THREAD

**Issue by oscargus** [sympy/sympy#22853]
See https://github.blog/2021-09-01-improving-git-protocol-security-github/

I do not really know which combinations we should encourage instead.

**Comment by oscarbenjamin** [comment]
We should definitely update the instructions in the guide. Somewhere it says' to use the `git://` protocol.

I've always used ssh keys myself.

**Comment by Onkar627** [comment]
In the readme do we have to only remove this:-
To get the git version do-
$ git clone git://github.com/sympy/sympy.git

**Comment by Onkar627** [comment]
In the readme do we have to only remove this?:-
To get the git version do-
$ git clone git://github.com/sympy/sympy.git

**Comment by oscargus** [comment]
That is one place, but we should replace it with another, valid, url. Not
sure if it should be https or ssh though. And one should check the
documentation and wiki as well (wiki is not a PR though).

**Comment by Onkar627** [comment]
In the documentation section in installation guide should we remove the whole installation thriugh git guidlines and then change other methods to methods of installation only.

**Comment by sumit-158** [comment]
Hey, there! Is anyone is working on this if not can I  work on this??

**Comment by oscargus** [comment]
No, it should still use git, it is just that links with git:// does not work any more.

I'm about to prepare a PR (using https instead). Primarily wanted to discuss which protocol to use instead. (There are just two places.)

**Comment by oscarbenjamin** [comment]
I've always used `git@` with ssh:
```
origin	git@github.com:oscarbenjamin/sympy.git (fetch)
origin	git@github.com:oscarbenjamin/sympy.git (push)
```
Is there any reason to prefer using https? If you use https then how do you authenticate (I presume it ignores your ssh keys)?

**Comment by oscargus** [comment]
https works well if you are going to fetch it. The way it was written was for downloading it, not contributing. (For the script it is enough to download.) 

The option was writing about how to set up ssh-keys etc and it didn't seem to be the place for that in README.
