### ISSUE TITLE
checksol returns False if solution dict is empty or if values are original symbols themselves.

### ISSUE THREAD

**Issue by NikhilSDate** [sympy/sympy#22859]
`checksol` returns `False` if the solution dictionary passed is empty in many cases where the equation has solutions. 
For example: `checksol(a + b, {})`, `checksol(x**2-y**2, {})`, and `checksol(sin(x), {})` all return `False`. I think the correct return value should be `None` here since all of these equations have solutions but cannot be directly simplified to zero.

The same problem exists if the solution dict uses the original symbols themselves or even other symbols as values. 
For example, `checksol(a + b, {a: a, b: b})`, `checksol(x**2-y**2, {x: a, y: b})`, and `checksol(sin(x), {x: x})` all return `False`.
Again, I think the correct return value should be `None` in all cases.

Is this behavior of `checksol` a legitimate issue? If so, I have a possible fix for which I can submit a PR.

**Comment by smichr** [comment]
I think the behavior is right. `checksol` answers whether the equation is always zero at the given point. An expression like `a + b` is not always zero so the answer is False.

**Comment by oscarbenjamin** [comment]
This seems to be a misunderstanding of what checksol should work. Note firstly that checksol is the partner to solve so you should interpret the solution argument as being something that solve would have returned e.g.:
```python
In [78]: eq = a + b

In [79]: eq
Out[79]: a + b

In [80]: [sol] = solve(eq, a, dict=True)

In [81]: sol
Out[81]: {a: -b}

In [82]: eq.subs(sol)
Out[82]: 0

In [83]: checksol(eq, sol)
Out[83]: True
```
The definition of `solve` is that it returns something that you can substitute into the equation and that makes it zero (after simplification). In different situations `solve` may return different numbers of results in the dict:
```python
In [84]: solve([a+b, a], [a, b], dict=True)
Out[84]: [{a: 0, b: 0}]

In [85]: solve([a+b], [a, b], dict=True)
Out[85]: [{a: -b}]

In [86]: solve([a+b], [a], dict=True)
Out[86]: [{a: -b}]
```
For `solve` to return the empty dict would imply that nothing needs to be substituted in order to bring the equation to zero. That isn't the case in your examples e.g.:
```python
In [91]: checksol(a+b, {})
Out[91]: False
```

**Comment by oscarbenjamin** [comment]
This does seem somewhat inconsistent though:
```python
In [93]: solve([0], [a])
Out[93]: []
```
That could have returned `[{}]` indicating that there do exist solutions but that solving the equations gave no information to constrain any of the variables.

**Comment by NikhilSDate** [comment]
Ok I see. I was trying to work on another issue and I needed a function that returned `False` if the solution passed was definitely incorrect (at least one equation evaluated to a nonzero number when the values were substituted in), `True` if the solution was definitely correct, and `None` otherwise. It seems I have incorrectly assumed that `checksol` should do this. Does such a function exist?

**Comment by smichr** [comment]
> Does such a function exist?

`fuzzy_and(checksol(eq, sol) for eq in eqs)`

**Comment by NikhilSDate** [comment]
> fuzzy_and(checksol(eq, sol) for eq in eqs)

Wouldn't that still return `False` if checksol returns `False` on any of the equations (as it currently does for empty solution dicts)?

**Comment by NikhilSDate** [comment]
Closing since the original issue was a misunderstanding on my part.
