### ISSUE TITLE
Sets are `UndefinedKind`

### ISSUE THREAD

**Issue by TomFryers** [sympy/sympy#22860]
```python
>>> import sympy
>>> sympy.FiniteSet(0, 1).kind
UndefinedKind
```
Maybe this should be `SetKind`, or `SetKind(NumberKind)`. The latter would introduce some complications, such as
```python
>>> sympy.FiniteSet(0, sympy.Matrix([1,2])).kind
???
>>> sympy.EmptySet.kind
???
```
Perhaps `SetKind` should take any number of parameters, making the results above `SetKind(NumberKind, MatrixKind)` and `SetKind()`.

**Comment by oscarbenjamin** [comment]
I think `SetKind(NumberKind)` makes sense.

If we wanted to support mixed kinds then it should be something like `SetKind(UnionKind(NumberKind, MatrixKind(NumberKind)))`. A set of mixed kinds is unlikely to be useful though so it can just be `SetKind(UndefinedKind)`.

**Comment by me-t1me** [comment]
Is this the requirement
```python
>>>sympy.FiniteSet(0, 1).kind
NumberKind
>>> sympy.FiniteSet(0, sympy.Matrix([1,2])).kind
MatrixKind(NumberKind)
>>> sympy.EmptySet.kind
UndefinedKind
```

**Comment by oscarbenjamin** [comment]
No, the kind of a set should not be equal to the kind of its elements, A set of numbers is not NumberKind: it should be something like `SetKind(NumberKind)` so that the kind clearly shows it is not a number but also shows that its elements are numbers.

The case of Integral is very different since the kind of an integral is equal to the kind of the integrand e.g. an integral of a number is a number and an integral of a matrix is a matrix etc.

**Comment by me-t1me** [comment]
So `Setkind` is kind of similar to `MatrixKind`, and this property should be in `Set` class right?

**Comment by oscarbenjamin** [comment]
Yes

**Comment by me-t1me** [comment]
So can you assign me this issue?

**Comment by oscarbenjamin** [comment]
We don't assign issues. Anyone is free to work on this if they want to.

**Comment by oscarbenjamin** [comment]
This was added in #22860:
```python
In [1]: FiniteSet(1, 2).kind
Out[1]: SetKind(NumberKind)

In [2]: FiniteSet({1}, {2}).kind
Out[2]: SetKind(SetKind(NumberKind))

In [3]: ImageSet(Lambda(n, Matrix([[0, 1], [0, 0]]) ** n), Integers).kind
Out[3]: SetKind(MatrixKind(NumberKind))

In [4]: FiniteSet(1, {2}).kind
Out[4]: SetKind(UndefinedKind)

In [5]: EmptySet.kind
Out[5]: SetKind()

In [6]: (FiniteSet(1, 2) * FiniteSet(3, 4)).kind
Out[6]: SetKind(TupleKind(NumberKind, NumberKind))
```
