### ISSUE TITLE
matrices/repmatrix.py doesn't catch AttributeError from pure python operator module

### ISSUE THREAD

**Issue by memorable** [sympy/sympy#22868]
Line 702 of `matrices/repmatrix.py` (method `_getitem_RepMatrix`) attempts to use the Python core method `operator.index()`:
```python
        try:
           return self._rep.getitem_sympy(index_(i), index_(j))
```
(`index_` has been assigned to `operator.index`)

If that throws an exception, it is intended to be caught on line 703: 
```python
        except (TypeError, IndexError):
```

That should work in most normal circumstances.  However, with CPython there are two implementations of `operator` module: the C implementation and the pure Python implementation.  If the pure python implementation is being used, in some cases it will throw an `AttributeError` instead of the expected `TypeError`, and the SymPy code fails.  This could affect someone when doing, for instance, a matrix slicing operation.

I'm not sure if this is a problem with SymPy, or CPython, or mostly a non-problem.  But at least it's now documented.

**Comment by oscarbenjamin** [comment]
How exactly have you come across this?

**Comment by memorable** [comment]
Via my own build of CPython, in which I hadn't added the C module _operator to the inittab, so that it would be automatically loaded.  Python then fall back onto the pure Python operator module.  I've now corrected my Inittab to fix this problem for myself.  I don't know enough about the Python ecosystem to know if anyone else would ever find themselves in that situation, but the pure Python operator module must exist for a reason.

**Comment by oscarbenjamin** [comment]
What was the input to `operator.index` that lead to `AttributeError`?

I would say that this is a bug in the stdlib. Neither PEP 357 nor the docs specify what error should be raised but it's not hard to see where the error comes from:
https://github.com/python/cpython/blob/91e33ac3d08a1c6004c469da2c0e2a97b5bdc53c/Lib/operator.py#L87-L89

My guess is that no one ever used the pure Python implementation of operator.py. I presume that it is there for other implementations (e.g. pypy) but I also presume that other implementations would want to use their own version of the operator module so it's probably unused.

https://docs.python.org/3/library/operator.html#operator.index
https://www.python.org/dev/peps/pep-0357/
https://docs.python.org/3/reference/datamodel.html#object.__index__

**Comment by memorable** [comment]
I originally hit the problem with `sympy.Matrix([[1, 2], [2, 1]]) ** -1` but was later able to reproduce it with `sympy.Matrix([[1, 2], [2, 1]])[0,:]` which results in the same error but a much shorter call stack.  In either case, `operator.index` was being fed a Python slice object and then failing to access the slice's `__index__` attribute.

And I agree -- slice objects don't have `__index__` attributes.

So it sounds like it's probably a non-problem for all practical purposes, although technically a stdlib bug, or charitably just undocumented behavior.

In my case the issue helped me discover that I was loading the wrong operator module, and likely suffering some performance penalty for that, so I'm happy to have tracked it down.

Thanks for your investigation.

**Comment by oscarbenjamin** [comment]
Thanks for reporting this but having looked at it I don't think there's anything to be done here so I'll close it.
