### ISSUE TITLE
RecursionError in trigsimp

### ISSUE THREAD

**Issue by proy87** [sympy/sympy#22878]
`trigsimp(8*sqrt(2)*(-exp(2*I*t)*sin(2*t) + (-1 + 2*I)*exp(2*I*t)*cos(2*t) + 1 + I)*exp(-t*(1 + 2*I)), method='fu')`

**Comment by oscarbenjamin** [comment]
More directly the problem is:
```python
In [16]: (-t - 2*I*t + 2951*t*(1 + 2*I)).extract_additively(-t)
---------------------------------------------------------------------------
RecursionError
```

**Comment by smichr** [comment]
MWE: `(-t -t*(1+I)).extract_additively(-t)`
