### ISSUE TITLE
Solving an equality doesn't work with powers of ten by the degree of 11 or so

### ISSUE THREAD

**Issue by piiskop** [sympy/sympy#22880]
My code:

MASS_PROTON = 1.6726219e-27 ELEMENTARYCHARGE = 1.6E-19 library(Ryacas) equality = paste(MASS_PROTON * 35e6 ^ 2, "/ radius ==", ELEMENTARYCHARGE * 35e6 * .5 * sin(pi / 2), sep = " ") equality radiusOfProton = eval(parse(text = yac_str(y_rmvars(paste("Solve(", equation, ", radius)", sep = "")))))
The result:

Error in eval(parse(text = yac_str(y_rmvars(paste("Solve(", equation, :
object 'Undefined' not found
Calls: ... withCallingHandlers -> withVisible -> eval -> eval -> eval -> eval
Execution halted

The solver should recognize that it's possible to cancel out some degrees of ten before trying to do a calculation with a large or very zero-close number. If I perfom the calculation manually:

2.0489618275e-12 / 2.8e-12

then I see the correct result:

[1] 0.7317721

I was suggested to report the [issue](https://github.com/r-cas/ryacas/issues/61) here.

**Comment by smichr** [comment]
There doesn't seem to be a problem:
```python
>>> MASS_PROTON = 1.6726219e-27
>>> ELEMENTARYCHARGE = 1.6E-19
>>> eq = Eq(MASS_PROTON*35e6**2/radius,ELEMENTARYCHARGE*35e6*.5*sin(pi/2))
>>> solve(eq)
[0.731772081250000]
```

Feel free to reopen if there is something specifically wrong.

**Comment by smichr** [comment]
? did you mean "solve" instead of "Solve"?

**Comment by piiskop** [comment]
I mean that this issue has occured in _RStudio_ with _Ryacas_. The guy behind _Ryacas_ sent me here. I don't even know who you are and what you do.
