### ISSUE TITLE
Why does Sympy evaluate this expression as False?

### ISSUE THREAD

**Issue by NSC9** [sympy/sympy#22903]
```from sympy import E, factorial,Eq
E**factorial(E)

E**factorial(E).evalf()

Eq(E**factorial(E),E**factorial(E).evalf())
```

 [picture of jupyter notebook LaTeX](https://i.imgur.com/PoKret9.png)

`E**factorial(E)` returns the symbolic expression in LaTeX

`E**factorial(E).evalf()` returns `70.8681052120441`

yet, `Eq(E**factorial(E),E**factorial(E).evalf())` returns `False`

**Comment by praneethratna** [comment]
`Eq` in sympy is used to check whether two expressions are same mathematically.Here `E**factorial(E)` is an expression whereas `E**factorial(E).evalf()` is a Sympy Float number so they are not equivalent.You can use `evaluate = false` to prevent the evaluation.
```
>>> Eq(E**factorial(E),E**factorial(E).evalf(), evaluate = false)
Eq(exp(factorial(E)), 70.8681052120441)
```

**Comment by NSC9** [comment]
> `Eq` in sympy is used to check whether two expressions are same mathematically.Here `E**factorial(E)` is an expression whereas `E**factorial(E).evalf()` is a Sympy Float number so they are not equivalent, since it can be definitely shown that they are not equivalent `Eq(E**factorial(E),E**factorial(E).evalf())` evaluates to `false`. You can use `evaluate = false` to prevent the evaluation.
> 
> ```
> >>> Eq(E**factorial(E),E**factorial(E).evalf(), evaluate = false)
> Eq(exp(factorial(E)), 70.8681052120441)
> ```

Thank you for this. One change I would make though is false should be False. Otherwise I got traceback error "NameError: name 'false' is not defined"

**Comment by asmeurer** [comment]
Just to be clear, Eq is not actually designed to check if two expressions are equal. You should use the `equals` method for that. It does happen to evaluate to True or False in simple cases where it can evaluate, but for more complicated cases it won't. 

In this case, the floating point number on the right is only computed to a finite precision (~15 digits), whereas the left-hand side is an exact irrational quantity, so SymPy treats them as unequal.
