### ISSUE TITLE
Should Float(...)/S.Zero really give ComplexInfinity?

### ISSUE THREAD

**Issue by bjodah** [sympy/sympy#22931]
Consider this:
```python
In [10]: Float(1)/S.Zero
Out[10]: zoo

In [11]: Float(1).is_real
Out[11]: True

In [12]: S.Zero.is_real
Out[12]: True
```
I would have expected `oo` (sympy.core.numbers.Infinity) being produced, no?

**Comment by jakoblem** [comment]
No, it should either be "undefined" (as in Maple) or "ComplexInfinity" (as in Mathematica). ComplexInifinity has its argument/phase undefined/undetermined which is needed for 1/0. In the real case, it is ambiguous as 1/0 could be the left or the right side limit of 1/x, that is, either minus or plus `oo`. Recall that minus/plus in the real case corresponds to phase.

**Comment by bjodah** [comment]
So maybe something along the lines of `PlusMinusInfinity`. I would expect `(Float(0)/Float(0)).is_real` to return `True`, no?

**Comment by oscarbenjamin** [comment]
Infinity is not considered real in sympy in any case.

**Comment by bjodah** [comment]
Thinking about this a bit more: floating point has signed zeroes. So I think `Float(1)/Float(0)` should unambiguously return `Float(float('inf'))`, and `Float(1)/Float(-0.0)` should arguably return `Float(-float('inf'))`. This shouldn't interfere with people not working with floats, but arguably help those who do (me included, I came across this and had to handle this case).

**Comment by bjodah** [comment]
But I can't seem to construct a -0.0 `Float` (tried with `Float._new((1,0,0,0), 15)` but no luck). That's unfortunate, floating point systems really should support signed zeros (I think Kahan has written a paper on the subject...)

**Comment by jakoblem** [comment]
S.Zero is not a sympy.core.numbers.Float so it is not clear that Float(1)/S.Zero should be. You can use e.g., NumPy: 
With `import numpy as np` the call `1/np.copysign(0.0,-1)` returns `-inf`

**Comment by oscarbenjamin** [comment]
Signed zeros are more useful in a non-symbolic context where there isn't a better way to represent the result of underflow.

I think if this is needed for something like codegen then it is better to have a specific representation of what should be machine floating point types.

**Comment by bjodah** [comment]
Not code generation in this case, was investigating an algorithm, and I was putting expressions in NumPy arrays (where some elements were symbolic others of floating point type). Since our Float cannot represent signed zeroes, I'm closing this issue. Perhaps a `IEEEFloat` could be added at some point (which would have finite precision, but be parametric).
