### ISSUE TITLE
quantile() is not publicly documented

### ISSUE THREAD

**Issue by gschintgen** [sympy/sympy#22930]
sympy.stats.quantile is not publicly documented.
See: https://docs.sympy.org/dev/modules/stats.html#interface
A suitable docstring is in the code, so all that's missing is a reference to it in https://github.com/sympy/sympy/blob/master/doc/src/modules/stats.rst

**Comment by mohajain** [comment]
Thanks, I'll take this one.

**Comment by jesv99** [comment]
Where could I find the format for proper documentation?

**Comment by oscarbenjamin** [comment]
Take a look here:
https://docs.sympy.org/latest/documentation-style-guide.html
