### ISSUE TITLE
polys/numberfields: Convenience constructors for `AlgebraicField`

### ISSUE THREAD

**Issue by skieffer** [sympy/sympy#22954]
I'd like to propose a pair of new constructor methods, to support a couple of common use cases.

## Use Case 1

* You want a number field `Q(a)`,
* AND you have the minimal polynomial `f(x)` for `a`,
* AND you don't care _which_ root of `f` `a` is. (E.g. it's a Galois field, so it doesn't matter.),
* AND, OPTIONALLY you want an `alias` for `a` so that field elements print nicely.

## Use Case 2

* You want the `n`th cyclotomic field.
* You probably want the primitive element to be aliased either `"zeta"` or `f"zeta{n}"`.

## The Current Situation

For Use Case 1, you have to do this:
```python
alpha = AlgebraicNumber(CRootOf(f, -1), alias="alpha")
K = QQ.algebraic_field(alpha)

```
which has several problems:

* It's too long.
* You shouldn't have to import `CRootOf`.
* You shouldn't have to choose an index for `CRootOf`.

Use Case 2 is similar, and you also have to import `cyclotomic_poly`:

```python
zeta = AlgebraicNumber(CRootOf(cyclotomic_poly(19), -1), alias="zeta")
K = QQ.algebraic_field(zeta)
```

## Proposal

Alongside the `QQ.algebraic_field()` method (which takes one arg, being an `Expr`) I would propose two additional methods:

```python
    def alg_field_from_poly(self, poly, alias=None, root_index=-1):
        alpha = AlgebraicNumber(CRootOf(poly, root_index), alias=alias)
        return self.algebraic_field(alpha)

    def cyclotomic_field(self, n, alias="zeta", ss=False, gen=None, root_index=-1):
        if ss:
            alias += str(n)
        return self.alg_field_from_poly(cyclotomic_poly(n, gen), alias=alias, root_index=root_index)

```

Then the above examples become

```python
K = QQ.alg_field_from_poly(f, "alpha")
```

and

```python
K = QQ.cyclotomic_field(19)
```

## Rationale

For a "canonical" default root, `-1` is the best index to pass to `CRootOf`. In common cases like quadratic or cyclotomic fields, this will select the root you tend to think of: the positive square root, or the square root with positive imaginary part, or `exp(2*I*pi/n)` for the `n`th cyclotomic field.

**Comment by oscarbenjamin** [comment]
How would `to_sympy` or `from_sympy` work if we don't know which root is the generator?

**Comment by skieffer** [comment]
We still do. These methods choose the root for you.

**Comment by oscarbenjamin** [comment]
I think this seems reasonable.
