### ISSUE TITLE
Releasing sympy 1.10

### ISSUE THREAD

**Issue by oscarbenjamin** [sympy/sympy#22963]
This issue is to track the release of sympy 1.10. The release notes for 1.10 are here:
https://github.com/sympy/sympy/wiki/Release-Notes-for-1.10

The issue for the previous release (1.9) was #22008

There have been various changes to the way that the mailmap and authors files are kept up to date (#22703, #22711, #22725, #22754, #22913, #22955, #22957).

The versions will be updated on master (#22958) and the 1.10 release branch (#22962) shortly.

There are no known release blockers at this time.

**Comment by oscargus** [comment]
I'm tagging a few PRs with 1.10, primarily related to deprecations that I think would make sense to get in. Feel free to untag them. 

(While I'm not in any way involved in the release work, so I shouldn't "complain", maybe it is possible to give a bit of a heads-up before starting a new release? In that way one can try to get things in for a week or so without the work of targeting different branches etc. I think this can especially be worthwhile for "less controversial" stuff like deprecation removals and other types of cleanup.)

**Comment by oscarbenjamin** [comment]
I've been wanting to get this release out for a while. The main thing holding it up was wanting to get a resolution for how to handle the AUTHORS file. Ideally releases would just be frequent enough that we don't really need much of a heads up.
