### ISSUE TITLE
limit(acosh(1 + 1/x)*sqrt(x), x, oo) is evaluated incorrectly .

### ISSUE THREAD

**Issue by faze-geek** [sympy/sympy#22986]
I was using SymPy to find limits of couple of intractable functions at `oo` (S.Infinity) and they gave wrong results .
```
>>> x = Symbol('x')
>>> limit(acosh(1 + 1/x)*sqrt(x), x, oo)
0 ---> correct answer is sqrt(2)
```
[Wolfram limit calculator reference](https://www.wolframalpha.com/input?i=limit+calculator&assumption=%7B%22F%22%2C+%22Limit%22%2C+%22limitfunction%22%7D+-%3E%22acosh%281+%2B+1%2Fx%29*sqrt%28x%29%22&assumption=%7B%22F%22%2C+%22Limit%22%2C+%22limit%22%7D+-%3E%22infinity%22)

I will report more related wrong results when I come across them !

**Comment by anutosh491** [comment]
Working on this one .We could introduce ` _eval_nseries` for `acosh` based on the `log` function hence branch cuts would be cover for the same . Otherwise getting this would be tricky !
@jksuom what would be the best approach here ?
