### ISSUE TITLE
Lambdify Error: 'NameError: name 'cot' is not defined'

### ISSUE THREAD

**Issue by EstebanCardenas** [sympy/sympy#22992]
When attempting to lambify an expression with cot:

![image](https://user-images.githubusercontent.com/53832358/152084811-cb95a2ef-cbf5-42d7-a88f-149d0af55687.png)

The following error is displayed:

![image](https://user-images.githubusercontent.com/53832358/152084855-8215ed21-55cc-45e7-a992-954a7807f34c.png)

**Comment by oscargus** [comment]
NumPy does not have `cot` although it seems like SymPy assumes that it does.

For now, adding 
```
expr = expr.rewrite(sp.tan)
```
before lambifying should make it work.

**Comment by oscargus** [comment]
Seems also to be a problem with the standard Python math variant.

**Comment by oscargus** [comment]
Tuned out to be a simple fix, see #22993.

**Comment by EstebanCardenas** [comment]
Great, thank you @oscargus
