### ISSUE TITLE
Numeric integration is not documented

### ISSUE THREAD

**Issue by oscarbenjamin** [sympy/sympy#23025]
I looked in both of these pages and I can't find any mention of the fact that SymPy can compute integrals numerically:
https://docs.sympy.org/latest/modules/integrals/integrals.html
https://docs.sympy.org/latest/tutorial/calculus.html#integrals

SymPy's numeric integration (from mpmath) is very accurate and useful and would be preferred by many users over using lambdify/scipy. Here is how it is used:
```python
In [58]: integral = Integral(sqrt(2)*x, (x, 0, 1))

In [59]: integral
Out[59]: 
1        
⌠        
⎮ √2⋅x dx
⌡        
0        

In [60]: integral.evalf()
Out[60]: 0.707106781186548

In [61]: integral.evalf(50)
Out[61]: 0.70710678118654752440084436210484903928483593768847

In [62]: Integral(exp(-(x ** 2)), (x, -oo, oo))
Out[62]: 
∞         
⌠         
⎮     2   
⎮   -x    
⎮  ℯ    dx
⌡         
-∞        

In [63]: Integral(exp(-(x ** 2)), (x, -oo, oo)).evalf()
Out[63]: 1.77245385090552

In [64]: Integral(exp(-(x ** 2)), (x, -oo, oo)).n()
Out[64]: 1.77245385090552

In [65]: Integral(exp(-(x ** 2)), (x, -oo, oo)).doit()  # symbolic integration
Out[65]: √π

In [66]: _.n()
Out[66]: 1.77245385090552
```
In many cases where symbolic integration is not possible it is still possible to compute the integral numerically. It is also useful as a way of checking the result of an integration routine. Integration can be over infinite intervals and can include infinite integrands:
```python
In [69]: Integral(1 / sqrt(x), (x, 0, 1)).evalf()
Out[69]: 2.00000000000000
```

Currently only 1D integrals are supported. In mpmath there are functions that can do 2D and 3D integrals but sympy's evalf does not have the code to make use of them.

**Comment by moorepants** [comment]
Yes, that does look like something that needs some documentation! Very nice feature.

**Comment by oscarbenjamin** [comment]
Actually I see that it is mentioned here:
https://docs.sympy.org/latest/modules/evalf.html#sums-and-integrals

I think it should also be shown in other places as well though and should be in the tutorial.

As mentioned there it is also possible to numerically evaluate sums including infinite sums:
```python
In [4]: Sum(1 / n ** 2, (n, 1, oo))
Out[4]: 
  ∞     
 ____   
 ╲      
  ╲   1 
   ╲  ──
   ╱   2
  ╱   n 
 ╱      
 ‾‾‾‾   
n = 1   

In [5]: Sum(1 / n ** 2, (n, 1, oo)).evalf()
Out[5]: 1.64493406684823
```
That should be documented more clearly here as well:
https://docs.sympy.org/latest/modules/concrete.html
(Maybe summations should be part of the tutorial)

I think that alternatives for numeric integration could be discussed here as well such as showing how to use scipy's `quad` etc functions with `lambdify` and also mpmath's multiple integral routines:
https://docs.sympy.org/latest/modules/numeric-computation.html

The multiple integral routines can be used like:
```python
In [12]: expr = exp(-(x ** 2) - y ** 2)

In [13]: f = lambdify((x, y), expr, "mpmath")

In [14]: from mpmath import quad, inf

In [15]: quad(f, [-inf, inf], [-inf, inf]) # slow
Out[15]: mpf('3.1415926535897931')
```

Since evalf with multiple integrals is slow I'm not sure it should be enabled by default. One way to improve the prominence of numerical integration functionality would be to add a function like `nintegrate` that is analogous to `integrate` but always computes definite integrals numerically:
https://reference.wolfram.com/language/ref/NIntegrate.html

With an `nintegrate` function it would definitely make sense to include multiple integration even if it is slow since users will have explicitly asked for it.

**Comment by moorepants** [comment]
I would be nice is lambdify could accept an integral expression and generate the appropriate code (without having to manually manage functions like `quad`).

**Comment by oscarbenjamin** [comment]
> I would be nice is lambdify could accept an integral expression and generate the appropriate code (without having to manually manage functions like `quad`).

Yes, or perhaps `nintegrate` could just have an argument for doing this like `nintegrate(x**2, (x, 0, 1), mode='scipy')`.

I think that in general `lambdify` is not such a good public interface for most of the situations where users want to use it:

1. Use numpy/numexpr etc to evaluate expressions with numpy arrays: why not have a `nevaluate` or `nsubs` function so you just do `nsubs(expr, {x: xarray, y:yarray})`.
2. Use SymPy to evaluate an expression that does not have any free symbols such as a definite integral: `nevaluate(expr, mode='scipy')`
3. Use sympy to compute Jacobian and then use scipy to find a minimum/maximum of a function: `nminimize(expr, guess, mode='scipy')`
4. Use scipy's `solve_ivp` or mpmath's version etc: that could just be `ndsolve(odes, tarray, ics_dict, mode='scipy')`

All of these possibilities could use `lambdify` internally but we don't actually need that to be the public interface for users.

**Comment by oscarbenjamin** [comment]
> All of these possibilities could use `lambdify` internally but we don't actually need that to be the public interface for users.

It would also be good to be able to evaluate these things *without* using `lambdify` because `lambdify` is not safe for untrusted input (it uses `eval`). The examples above could all be implemented on top of `nsubs`.

**Comment by soma2000-lang** [comment]
Can O work on this

**Comment by oscarbenjamin** [comment]
Anyone can work on any issue. Explicit permission is not needed.

**Comment by ThePauliPrinciple** [comment]
Numerical methods can fail horribly when applied to the wrong function though, I'd rather have sympy say that it doesn't know how to numerically integrate an expression when it isn't sure it can safely use the algorithm it wishes to use than that it gives a wrong answer.

**Comment by oscarbenjamin** [comment]
> I'd rather have

I'm not sure what you are suggesting or which part of the above you are referring to. The functionality for computing an integral with mpmath already exists in sympy and is more accurate than anything provided by any other widely used Python libraries. The routines already use variable precision and attempt to estimate the accuracy of the output:
```
In [3]: Integral(abs(sin(x)), (x, 0, 4)).evalf()
Out[3]: 2.346

In [4]: _._prec  # low precision result
Out[4]: 16

In [5]: Integral(abs(sin(x)), (x, 0, 4)).doit()
Out[5]: cos(4) + 3

In [6]: Integral(abs(sin(x)), (x, 0, 4)).doit().evalf()
Out[6]: 2.34635637913639

In [7]: _._prec  # high precision result
Out[7]: 53
```
The main suggestion here is just to make it clearer to users that this functionality exists if they want to use it.

**Comment by ThePauliPrinciple** [comment]
```python
>>> from sympy import *
>>> from sympy.abc import x
>>> x0=1
>>> Integral(sin(x)*DiracDelta(x - x0), (x, 0, pi)).evalf()
0
>>> Integral(sin(x)*DiracDelta(x - x0), (x, 0, pi)).doit().evalf()
0.841470984807897
```
Note that this is was specifically chosen here as something to "break" it and obviously you shouldn't expect a delta function to integrate numerically, but there might be cases where you don't realise you're dealing with a delta function (or something similar to it) because it is hidden symbolically and SymPy should be telling you that it's going to fail the numerical integration. Or at the very least, it should be documented which parts of SymPy are expected to give accurate results and which are not.

**Comment by moorepants** [comment]
> Use numpy/numexpr etc to evaluate expressions with numpy arrays: why not have a nevaluate or nsubs function so you just do nsubs(expr, {x: xarray, y:yarray}).

One reason not to do something like this, is that the code generation step can be computationally costly and separating the algorithm printing from the numerical evaluation is typically preferable.

**Comment by moorepants** [comment]
> All of these possibilities could use lambdify internally but we don't actually need that to be the public interface for users.

lambdify, for better or worse, is the current interface. Ideally, lambdify would work for any sympy expression we throw at it.

**Comment by oscarbenjamin** [comment]
> > Use numpy/numexpr etc to evaluate expressions with numpy arrays: why not have a nevaluate or nsubs function so you just do nsubs(expr, {x: xarray, y:yarray}).
> 
> One reason not to do something like this, is that the code generation step can be computationally costly and separating the algorithm printing from the numerical evaluation is typically preferable.

Ideally it should be possible to do this without printing or compiling any code. There should just be something that recurses the expression tree just like subs and instead of generating printed code it just evaluates the expression.

Here's an example of what I mean:
```python
operations = {
    Add: np.add,
    Mul: np.multiply,
    Pow: np.power,
    exp: np.exp,
}

def nsubs(expr, replacement):
    rep = replacement.get(expr, None)
    if rep is not None:
        return rep
    args = expr.args
    if args:
        args_n = [nsubs(a, replacement) for a in args]
        return operations[type(expr)](*args_n)
    elif expr.is_Number:
        return np.array(float(expr))
    elif expr.is_ImaginaryUnit:
        return np.array(complex(expr))
    else:
        raise NotImplementedError
```
With that we have:
```python
In [76]: expr = exp(2 * x) + y ** 4

In [77]: vals_sub = {x: np.arange(10), y: 2}

In [78]: vals_lam = [np.arange(10), 2]

In [79]: %time f = lambdify((x, y), expr)
CPU times: user 4 ms, sys: 0 ns, total: 4 ms
Wall time: 4.27 ms

In [81]: %time ok = f(*vals_lam)
CPU times: user 0 ns, sys: 0 ns, total: 0 ns
Wall time: 119 µs

In [82]: %time ok = nsubs(expr, vals_sub)
CPU times: user 0 ns, sys: 0 ns, total: 0 ns
Wall time: 266 µs

In [86]: %timeit f(*vals_lam)
6.41 µs ± 23.3 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)

In [88]: %timeit nsubs(expr, vals_sub)
36.4 µs ± 829 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)
```
What you can see is that while `nsubs` is slower than `f` it is in fact much faster than `lambdify` itself. So for a single evaluation it would be faster to use nsubs.

With large enough arrays there is no difference:
```python
In [90]: %time ok = f(np.linspace(0, 1, 10**6+1), 1)
CPU times: user 60 ms, sys: 0 ns, total: 60 ms
Wall time: 58.6 ms

In [91]: %time ok = nsubs(expr, {x:np.linspace(0, 1, 10**6+1), y:1})
CPU times: user 52 ms, sys: 4 ms, total: 56 ms
Wall time: 52.3 ms
```
Note that e.g. scipy's `quad` function typically only calls the function about 20 times so the overhead of lambdify doesn't get amortised away e.g.:
```python
from scipy.integrate import quad

def quad_lam(expr, sym, start, end):
    f = lambdify(sym, expr)
    return quad(f, start, end)

def quad_sub(expr, sym, start, end):
    f = lambda v: nsubs(expr, {sym:v})
    return quad(f, start, end)
```
Here `nsubs` is faster than `lambdify`:
```python
In [111]: %time quad_lam(exp(x), x, 0, 1)
CPU times: user 0 ns, sys: 0 ns, total: 0 ns
Wall time: 2.29 ms
Out[111]: (1.7182818284590453, 1.9076760487502457e-14)

In [112]: %time quad_sub(exp(x), x, 0, 1)
CPU times: user 0 ns, sys: 0 ns, total: 0 ns
Wall time: 492 µs
Out[112]: (1.7182818284590453, 1.9076760487502457e-14)
```

**Comment by oscarbenjamin** [comment]
> SymPy should be telling you that it's going to fail the numerical integration

Yes, but I would consider that to be a bug in `evalf` rather than a reason not to document the numerical integration functionality. It is deliberate functionality that integrals can be evaluated numerically using mpmath's highly accurate numerics and that should be documented.

**Comment by ThePauliPrinciple** [comment]
I'm in favour of more documentation, but against more numerical evaluation functions that have possible bugs that are not documented.

I like the idea of an "evaluator" without printing, but I'd rather see it as a class dispatcher than an assumptions if-tree for customizations purposes if that is possible.

**Comment by dhananjaypai08** [comment]
Can you please tell where all can we specifically mention the use case of computing numeric integrals in the documentation
I think in the eval tutorial and in basic concrete module we can add usage of numeric integral.

**Comment by asmeurer** [comment]
> Ideally it should be possible to do this without printing or compiling any code. There should just be something that recurses the expression tree just like subs and instead of generating printed code it just evaluates the expression.

My concern with doing this this way instead of using `lambdify` is that there are a lot of workarounds for various functions in the NumPy printer to handle differences in SymPy or NumPy semantics, or translations of SymPy functions to NumPy equivalents, which would have to be repeated here. nsubs can just be

```py
def nsubs(expr, replacement):
    vars = list(replacement.keys())
    if set(vars) != expr.free_symbols:
        raise ValueError("All symbols must be evaluated")
    f = lambdify(vars, expr)
    return f(**replacement)
```

The exact logic would be a little more complicated than that to handle other types of replacement types and to handle non-Python keyword symbol names, but that's the basic idea. 

Is the performance difference that important? Which is faster in the case where it takes longer (large expression or arrays)? Can we make lambdify faster?

**Comment by oscarbenjamin** [comment]
> My concern with doing this this way instead of using `lambdify` is that there are a lot of workarounds for various functions in the NumPy printer to handle differences in SymPy or NumPy semantics, or translations of SymPy functions to NumPy equivalents, which would have to be repeated here

I personally consider the fact that these are in the printing code to be a design mistake. It would be much better if there were rewrite rules for generating an equivalent numpy expression that would take care of that sort of thing and then a separate phase of either evaluating or printing the numpy expression.

**Comment by chandra20500** [comment]
Hi I want to solve this issue please assign it to me.

**Comment by Jay-sanjay** [comment]
Hello , Sir I am a fresher towards contributing for open source.
can you suggest me some beginner friendly issues
I will solve this issue
