### ISSUE TITLE
Request for addition of derived theorems

### ISSUE THREAD

**Issue by marvelous-benji** [sympy/sympy#23031]
Hello mine is not an issue, but an inquiry. By introduction, I am a graduate of pure Mathematics and also a Python developer and would be contributing to Sympy(Though this would be my first). I just wanted to ask if it's allowed to contribute code using derived mathematical techniques created by the author to solution to problems if they appear to be effective and simpler?.

**Comment by oscarbenjamin** [comment]
I'm not sure I understand the question. Probably the answer is yes. The mailing list is a better place to discuss this though:
https://groups.google.com/g/sympy
