### ISSUE TITLE
Deprecate redundant methods in `carmichael`

### ISSUE THREAD

**Issue by oscargus** [sympy/sympy#23057]
The following static methods are redundant and should be deprecated:

https://github.com/sympy/sympy/blob/dc4f807f4116c449b82433fe4ae583dfab06bf5c/sympy/functions/combinatorial/numbers.py#L109-L119

Just look at where `is_square` and `isprime` is imported from and point to that as `useinstead`. For `divides` it is enough to type the corresponding Python code as `useinstead`.

**Note that there is a change in the deprecation procedure**, see #22900 , so it makes sense to wait with introducing these deprecations until that is merged and done (and to follow the new procedure).

**Comment by asmeurer** [comment]
In #22900 there is no more `useinstead`. You should just write a deprecation message describing what is deprecated and what to use instead (see the documentation in the PR which will be at https://docs.sympy.org/dev/guides/contributing/deprecations.html when it is merged).

Also just to be clear, we are no longer using "deprecation removal issues" anymore either, so once the deprecation here is added we can just close this issue.
