### ISSUE TITLE
display bug while using pretty_print with sympy.vector object in the terminal

### ISSUE THREAD

**Issue by rajeev2010** [sympy/sympy#23058]
The following code jumbles some of the outputs in the terminal, essentially by inserting the unit vector in the middle -
```python
from sympy import *
from sympy.vector import CoordSys3D, Del

init_printing()

delop = Del()
CC_ = CoordSys3D("C")
x,    y,    z    = CC_.x, CC_.y, CC_.z
xhat, yhat, zhat = CC_.i, CC_.j, CC_.k

t = symbols("t")
ten = symbols("10", positive=True)
eps, mu = 4*pi*ten**(-11), ten**(-5)

Bx = 2 * ten**(-4) * cos(ten**5 * t) * sin(ten**(-3) * y)
vecB = Bx * xhat
vecE = (1/eps) * Integral(delop.cross(vecB/mu).doit(), t)

pprint(vecB)
print()
pprint(vecE)
print()
pprint(vecE.doit())
```

Output:
```python
⎛     ⎛y_C⎞    ⎛  5  ⎞⎞    
⎜2⋅sin⎜───⎟ i_C⋅cos⎝10 ⋅t⎠⎟
⎜     ⎜  3⎟           ⎟    
⎜     ⎝10 ⎠           ⎟    
⎜─────────────────────⎟    
⎜           4         ⎟    
⎝         10          ⎠    

⎛     ⌠                           ⎞    
⎜     ⎮       ⎛y_C⎞    ⎛  5  ⎞    ⎟ k_C
⎜     ⎮ -2⋅cos⎜───⎟⋅cos⎝10 ⋅t⎠    ⎟    
⎜     ⎮       ⎜  3⎟               ⎟    
⎜  11 ⎮       ⎝10 ⎠               ⎟    
⎜10  ⋅⎮ ─────────────────────── dt⎟    
⎜     ⎮             2             ⎟    
⎜     ⎮           10              ⎟    
⎜     ⌡                           ⎟    
⎜─────────────────────────────────⎟    
⎝               4⋅π               ⎠    

⎛   4    ⎛  5  ⎞    ⎛y_C⎞ ⎞    
⎜-10 ⋅sin⎝10 ⋅t⎠⋅cos⎜───⎟ k_C ⎟
⎜                   ⎜  3⎟ ⎟    
⎜                   ⎝10 ⎠ ⎟    
⎜─────────────────────────⎟    
⎝           2⋅π           ⎠    ```

**Comment by smichr** [comment]
You can control print order as described [here](https://stackoverflow.com/a/58541713/1089161).

**Comment by gutow** [comment]
I can verify that this seems to be an issue specific to pretty print. The Latex renderer outputs what you want. This should be fixable. Here is an image of the output for your vectors from the latex rendered in Jupyter.
![image](https://user-images.githubusercontent.com/1231317/153658279-1cf4d387-2101-4cb3-b182-131ed3cbe1b8.png)

Admittedly the small outer parenthesis are not stylistically great, but the ordering is what you expect.

**Comment by asmeurer** [comment]
The LaTeX printer ought to be using \left and \right for parentheses.

**Comment by wermos** [comment]
@asmeurer I'd like to make the required change in the LaTeX printer. Should I do it in the PR I have already opened, or should I make a new PR for this `\left(` and `\right)` change?

**Comment by gutow** [comment]
@wermos I suggest making a separate pull request as this issue is about pretty print spacing on the command line output.

**Comment by wermos** [comment]
@gutow Thanks, I have created a separate branch for it, and will make a new PR soon.

**Comment by rajeev2010** [comment]
Another related issue - pretty_print is showing the unit vector several times (normal print is fine).
```python
from sympy import *
from sympy.vector import CoordSys3D, Del

init_printing()

delop = Del()
CC_ = CoordSys3D("C")
x,    y,    z    = CC_.x, CC_.y, CC_.z
xhat, yhat, zhat = CC_.i, CC_.j, CC_.k

t = symbols("t")
#ten = symbols("10", positive=True)
ten = UnevaluatedExpr(10)
eps, mu = 4*pi*ten**(-11), ten**(-5)

Bx = 2 * ten**(-4) * cos(ten**5 * t) * sin(ten**(-3) * y)
vecB = Bx * xhat

print(vecB)
print()
pprint(vecB)
```

Output:

```python
(2*10**(-4)*cos(t*10**5)*sin(C.y*10**(-3)))*C.i

⎛    -4    ⎛    5⎞    ⎛      -3⎞⎞             
⎝2⋅10  ⋅cos⎝t⋅10 ⎠ i_C⋅sin⎝y_C⋅10  ⎠ i_C⎠ i_C
```

**Comment by wermos** [comment]
I have fixed the bug as well as added a new test case for this.
