### ISSUE TITLE
tensor PartialDerivative behaves in unexpected (wrong?) way

### ISSUE THREAD

**Issue by harmvanderheijden** [sympy/sympy#23073]
I'm trying to do some symbolic GR work in sympy, but I get stuck on behaviour of tensor PartialDerivative that I don't understand and can't seem to deal with.

Bringing it down to simplest case, I have a tensor (g) with 1 upper index (a) in 2 dimensions and I take the partial derivative with respect to both dimensions (index -b). However, when I look at the result after `replace_with_arrays`, it seems that it has swapped the a and -b indices. In more complicated cases (taking the partial derivative of  rank 2 tensor, it seems the indices are reversed.

Am I missing something simple (please tell me what it is, then), or is this a bug? I can't seem to find a way to compensate for this behaviour. I'm trying to implement an (well-known) expression like `PartialDerivative(g(-a,-b), x(m)) + PartialDerivative(g(-a,-m), x(b)) - PartialDerivative(g(-b,-m),x(a))` where the changing order of indices a, b, m is crucial, but the eventual added result is wrong, due (I think) to the fact that PartialDerivative does not give properly ordered output after `replace_with_arrays`.

Here is the basic code for the artificial rank 1 example:
```
import sympy
from sympy.tensor.tensor import TensorIndexType, tensor_indices, tensor_heads
from sympy.tensor.toperators import PartialDerivative
Lorentz = TensorIndexType('Lorentz', dummy_name='L', dim=2)
a, b = tensor_indices('a,b', Lorentz)
r, theta = sympy.symbols("r, theta")
x, g = tensor_heads('x g', [Lorentz])
repl = {x(a): [r, theta], g(a): [0, r]}
def Show(T):
    print(T.get_indices())
    print(T.replace_with_arrays(repl))
pd = PartialDerivative(g(a),x(b))
# we expect to see one 1 at a==1, -b==0, because the partial derivative vanishes except for dg(1)/dx(0)
# but somehow the indices are reversed, so the 1 is at a==0, -b==1
Show( pd ) # --> gives [a, -b], [[0, 1], [0, 0]] instead of [a, -b], [[0, 0], [1, 0]]
```

**Comment by ThePauliPrinciple** [comment]
I agree that this is a bug somehow. It seems that `PartialDerivative` and `derive_by_array` put the "function" and "variable" indices in opposite order in the resulting derivative. `PartialDerivative` takes the function indices first and then the variable indices while `derive_by_array` takes the variable indices first and then the function indices.

Either they need to be made consistent or this needs to be taken into account in `PartialDerivative`'s `_extract_data` (which uses `derive_by_array`)

**Comment by harmvanderheijden** [comment]
Thanks! That completely explains it. 

As a quick hack, I created an own copy of "derive_by_array" and swapped the order of indices like this:
```
#new_array = [[y.diff(x) for y in Flatten(expr)] for x in Flatten(dx)]
new_array = [[y.diff(x) for x in Flatten(dx)] for y in Flatten(expr)]
```
Now the partial derivatives come out correctly, also in the more complicated case with partial derivatives of a metric tensor to calculate Christoffel symbols. This is great! 

Probably the cleaner solution is update PartialDerivative to correct the output from derive_by_array, as other code may be calling derive_by_array directly and depend on its current ordering of indices. I'm afraid my python and git skills are not sufficient to implement a proper solution of this bug in sympy, but I'm happy to help out with testing or in other ways.

**Comment by harmvanderheijden** [comment]
FYI, this is the slightly more complex example that I alluded to: Christoffel symbols in 2d polar coordinates. With the above change to derive_by_array, then now come out correctly:
```
import sympy
from sympy.tensor.tensor import TensorIndexType, tensor_indices, tensor_heads
#from sympy.tensor.toperators import PartialDerivative 

Lorentz = TensorIndexType('Lorentz', dummy_name='L', dim=2)
m0, m1, m2, a, b, c, m, n = tensor_indices('m0, m1, m2, alpha beta gamma mu nu', Lorentz)
r, theta = sympy.symbols("r, theta")
x = tensor_heads('x', [Lorentz])
g = tensor_heads('g', [Lorentz, Lorentz])
metric_array = [[1, 0], [0, r**2]]
repl = {Lorentz: metric_array, x(a): [r, theta], g(-m0,-m1): metric_array}
def Show(T):
    print(T.get_indices())
    print(T.replace_with_arrays(repl))
pd = g(a,c)/2*(PartialDerivative(g(-a,-b),x(m)) + PartialDerivative(g(-a,-m),x(b)) - PartialDerivative(g(-b, -m),x(a)))
Show(pd)
```
Gives the textbook result:
```
[L_0, gamma, -L_0, -beta, -mu]
[[[0, 0], [0, -r]], [[0, 1/r], [1/r, 0]]]
```
I'm really impressed that sympy can do this, with such elegant notation!

**Comment by Upabjojr** [comment]
@harmvanderheijden if you have found a way to fix this bug, can you please open a PR so we can fix SymPy's code?

**Comment by Upabjojr** [comment]
Another option would be to change the order of the free indices of `PartialDerivative`. That is, `PartialDerivative(g(a), x(b))` prints to the traditional form `\frac{\partial g_a}{\partial x_b}` or sometimes even `\partial_{x_b} g_a`... in the last case the indices `a` and `b` are flipped in their order. It's just a matter of convention.

**Comment by ThePauliPrinciple** [comment]
> It's just a matter of convention.

As long as `.get_indices()` and `.replace_with_arrays` match I think it is fine. Note that it also contracts along `L_0` here (because it appears as both a co and contravariant index), which makes sense, but it doesn't drop them from `.get_indices`. It might be more consistent to either drop it for both methods or for neither method.

**Comment by Upabjojr** [comment]
> but it doesn't drop them from `.get_indices`. It might be more consistent to either drop it for both methods or for neither method.

`.get_indices()` returns all indices, even the contracted ones. You should use `.get_free_indices()` to only get the uncontracted indices.

**Comment by harmvanderheijden** [comment]
Sorry, I don't have a proper fix. I've looked at the code for a fair bit,
but it's too complicated for my limited python skills. I can just barely
implement an ugly adhoc solution for my own particular purpose, but not
something that I'm reasonably sure of will be bug-free and up to the
high coding standards of sympy. Happy to help with testing, though.

**Comment by Upabjojr** [comment]
For the wikipedia page on [Ricci calculus](https://en.wikipedia.org/wiki/Ricci_calculus#Partial_derivative)

![img](https://wikimedia.org/api/rest_v1/media/math/render/svg/17f53a721623a4a3ddbf0d164ce2b94cb666f9a5)

It looks like there are two ways of interpreting the indices of a partial derivative. The order on the LHS or RHS of this expression. We are currently using the LHS in `PartialDerivative`. Shall we change the index order or the way the array is computed?

**Comment by harmvanderheijden** [comment]
@Upabjojr 
![png latex](https://user-images.githubusercontent.com/39855156/154766647-c2f634d0-eade-4039-867b-3b90ead2b54e.png)

Regarding the order of indices for PartialDerivative, I think the current LHS is the correct one, for two reasons:
- it is used in the concise notation (left expression in the above equation), which (I think) is the "proper" notation, whereas things like the middle and righthand expression in that equation are longhand versions which are used for clarification in textbooks but not often used otherwise
- in said "proper" notation, it is actually mandatory to use LHS indices, since the use of the comma as a delimiter requires it. No textbook I've ever seen uses comma delimiters and RHS indices, it would be extremely confusing and counter-intuitive. On the other hand, the longhand versions can be written so suggest both LHS and RHS.

So, my vote is to keep the output of PartialDerivative the same, using LHS, and change something else.

**Comment by Upabjojr** [comment]
OK, fixed! Thanks for reporting this issue @harmvanderheijden
