### ISSUE TITLE
Add matrix derivative examples to the documentation.

### ISSUE THREAD

**Issue by Upabjojr** [sympy/sympy#23084]
Should we add examples of matrix derivatives to the documentation in SymPy version 1.10 ?

Matrix derivatives have become quite stable with the latest upgrades to the code of last autumn. I think this feature should be announced publicly.

Cfr. https://github.com/sympy/sympy/pull/23088

**Comment by oscarbenjamin** [comment]
This was done in #23090 and #23088 for the 1.10 branch and master
