### ISSUE TITLE
Problem with `gf_edf_zassenhaus()`

### ISSUE THREAD

**Issue by skieffer** [sympy/sympy#23174]
This:

```python
from sympy import Poly, cyclotomic_poly
    f = Poly(cyclotomic_poly(17), modulus=2)
    print(f.factor_list())
```

never terminates.

It gets stuck in `gf_edf_zassenhaus()`.

`gf_edf_zassenhaus()` is a probabilistic algorithm, but each iteration has at least a 1/2 chance of success. (And on my test case exactly 1/2 chance.)

On several test runs, I managed to get through 10 iterations without success. Each time, that's a 1 in 1024 chance. This can't be right.

-------------------

The existing code does seem to be a correct implementation of Alg 8.9 from [Geddes92], but something is clearly wrong.
My best guess is that maybe using a random polynomial `r` ignores the assumption `v(x) in W` of Thm 8.13? (Again in Geddes.)
I'm not sure.

Anyway, handling the case `p = 2` with Alg 3.4.8 from [Cohen93] instead seems to work. And it seems to promise to be much faster in general, since the test polynomial `h` is now computed with a loop of `n - 1` iterations, instead of `2**(n*N - 1) - 1`.

For example, in the case of `cyclotomic_poly(17)`, this is 7 iterations instead of 32,767.

**Comment by oscarbenjamin** [comment]
Possibly relevant #16173

**Comment by skieffer** [comment]
Correction: Never mind the bit about an exponential number of iterations. That was just a mis-translation of Alg 8.9.
