### ISSUE TITLE
SymPy quantum built-in gates

### ISSUE THREAD

**Issue by BoltzmannEntropy** [sympy/sympy#23209]
Hello,
I am trying to replicate the behaviour of the unitary UF2 (see below), using the built-in SymPy gates. 
First, this is the program that works: 
```
from sympy import Matrix, symbols, sqrt, init_printing
from sympy import * 
from sympy.physics.quantum import TensorProduct
from IPython.display import display_pretty

init_printing(use_latex=True)

U_I = Matrix([[1,0],[0,1]])
U_H = 1/sqrt(2)*Matrix([[1, 1],[1,-1]])
U_Z=Matrix([[1,0],[0,-1]])
U_X=Matrix([[0,1],[1,0]])
U_CNOT=Matrix([[1,0,0,0],
             [0,1,0,0],
             [0,0,0,1],
             [0,0,1,0]])

U_XI = TensorProduct(U_X,U_I)
U_IX = TensorProduct(U_I,U_X)

UF0=TensorProduct(U_I,U_I)
UF1=U_CNOT
UF2=U_XI*U_CNOT*U_XI
UF3= U_IX

U_XI, UF0, UF1, UF2, UF3
```

Now using the SymPy gates:
```
from sympy import Matrix, symbols, sqrt, init_printing
from sympy import * 
import sympy 
from sympy.physics.quantum import TensorProduct
from IPython.display import display_pretty
init_printing(use_latex=True)
from sympy.physics.quantum.circuitplot import circuit_plot
from sympy.physics.quantum.qubit import Qubit, measure_all
from sympy.physics.quantum.gate import I, X, Y, Z, H, S, T,CNOT
from sympy.physics.quantum import represent
from sympy.physics.quantum.qapply import qapply

U_XI = TensorProduct(X(2),I)
U_IX = TensorProduct(I,X(2))

UF0=TensorProduct(I,I)
UF1=CNOT
UF2=U_XI*represent(CNOT(1,0),nqubits=2)*U_XI
UF3= U_IX
qapply(UF2 * Qubit('01'))
```
I am not sure, how to get the same result as in my first program and how to display the unitary of the circuit. 

Thanks,

**Comment by oscargus** [comment]
First, AFAIK there is really no active developer that had any knowledge of the quantum module (not quantum physics). However, I guess that if one can breakdown any potential bugs, it is probably still possible to fix them.

I may not follow completely here, but could the problem be that the `I` that you import from `quantum.gate` is not a gate, but the imaginary unit? Try importing and using `IdentityGate` instead. 

```
from sympy import Matrix, symbols, sqrt, init_printing
from sympy import * 
import sympy 
from sympy.physics.quantum import TensorProduct
from IPython.display import display_pretty
init_printing(use_latex=True)
from sympy.physics.quantum.qubit import Qubit, measure_all
from sympy.physics.quantum.gate import IdentityGate, X, Y, Z, H, S, T,CNOT
from sympy.physics.quantum import represent
from sympy.physics.quantum.qapply import qapply
U_I = IdentityGate(2)
U_XI = TensorProduct(X(2),U_I)
U_IX = TensorProduct(U_I,X(2))

UF0=TensorProduct(U_I,U_I)
UF1=CNOT
UF2=U_XI*represent(CNOT(1,0),nqubits=2)*U_XI
UF3= U_IX
qapply(UF2 * Qubit('01'))
```

Not sure how to get these into matrix form for comparison, but at least UF0 seems like it can be correct one into matrix form... Also, UF1 is your code will be the CNOT class, not an instance of it. So it needs two(?) arguments.

**Comment by BoltzmannEntropy** [comment]
Many thanks for your response. It seems after all the the use of I and not identitygate is correct. 
```
%matplotlib inline
from IPython.display import display
from sympy import init_printing
init_printing(use_latex=True)
from sympy import sqrt, symbols, Rational
from sympy import expand, Eq, Symbol, simplify, exp, sin
from sympy.physics.quantum import *
from sympy.physics.quantum.qubit import *
from sympy.physics.quantum.gate import *
from sympy.physics.quantum.grover import *
from sympy.physics.quantum.gate import I, X, Y, Z, H, S, T,CNOT, IdentityGate
from sympy.physics.quantum.qft import QFT, IQFT, Fourier
from sympy.physics.quantum.circuitplot import circuit_plot

# psi = Qubit('00')/sqrt(2) + Qubit('11')/sqrt(2); psi
psi = Qubit('01')

circuits = [CNOT(0,1)*Z(1)*H(1)*CNOT(1,0)*H(1)*I, 
            CNOT(0,1)*(TensorProduct(Z(1),H(1)))*CNOT(1,0)*H(1),
            CNOT(0,1)*(TensorProduct(Z(1),H(1)))*CNOT(1,0)* (TensorProduct(H(1),I))
            ]
# circuits = [CNOT(0,1)*(TensorProduct(Z(1),H(1)))*CNOT(1,0)*H(1)*IdentityGate(1) ,
#CNOT(0,1)*(TensorProduct(Z(1),H(1)))*CNOT(1,0)*(TensorProduct(H(1),IdentityGate(1)))]
# H(1)*CNOT(1,0), H(1)*CNOT(1,0)*X(1), H(1)*CNOT(1,0)*Z(1), H(1)*CNOT(1,0)*Z(1)*X(1),
for circuit in circuits:
    circuit_plot(circuit, nqubits=2)
    display(Eq(circuit*psi,qapply(circuit*psi)))
```
What I don't get is why the gates on the third circuit "disappear" when they are plotted:
<img width="579" alt="image" src="https://user-images.githubusercontent.com/91342039/156923616-f0c1238f-6eaa-48cb-a521-eaaa5270885c.png">

While this should have been the result (H and Z in parallel):
<img width="159" alt="image" src="https://user-images.githubusercontent.com/91342039/156923693-91312148-45f5-4bf4-b3c3-adbe52776f81.png">

**Comment by oscargus** [comment]
(This may not be the reason, but I guess there is maybe still a few `I` in the example?)

Is it the same problem with the second figure? (Just guessing that `(TensorProduct(Z(1),H(1)))` is the parallel connection...)

Just quickly browsing the source, it seems like those gates are not identified correctly as only multiplications are dealt with here:
https://github.com/sympy/sympy/blob/94a6ee85d9d74c0d4fb49a18d9f576267b093b64/sympy/physics/quantum/circuitplot.py#L157-L166

Is it possible that the authors thought that one should use some other gate corresponding to the TensorProduct?

**Comment by BoltzmannEntropy** [comment]
Thanks for digging! There is not even a single example of a circuit in parallel or one that includes a TensorProduct:
https://gist.github.com/rpmuller/5843312

**Comment by oscargus** [comment]
I noted that there is a function to generate random circuits in `quantum.gate`. Can probably be worth running it a few times and see if it is even possible to create it... (If I hadn't broken my matplotlib I'd do it myself...)

**Comment by BoltzmannEntropy** [comment]
Indeed, TensorProducts are complexly ignored in the plotting routine:

<img width="614" alt="image" src="https://user-images.githubusercontent.com/91342039/156940257-bbac6bf6-72a3-43f1-9358-ac4cc1b92e0a.png">
