### ISSUE TITLE
Sympy Assumptions Doing Nothing

### ISSUE THREAD

**Issue by cgbsu** [sympy/sympy#23244]
Hello, I have encountered a bit of an issue which it seems like sympy should be able to handle: 

```Python
from sympy.physics.quantum.constants import hbar

k_0 = sp.Symbol( "k_0" )
total_energy = sp.Symbol( 'E' )
mass = sp.Symbol( "m" )

k_0_squared = sp.Eq( k_0 ** 2, ( ( 2 * total_energy * mass ) / ( hbar ** 2 ) ) )

with sp.assuming( k_0_squared, sp.Q.real( total_energy ), sp.Q.positive( total_energy ), 
              sp.Q.real( mass ), sp.Q.positive( mass ), 
              sp.Q.real( total_energy ), sp.Q.positive( total_energy ), 
              total_energy > Potential.DEFAULT_POTENTIAL, 
              sp.Q.real( Potential.DEFAULT_POTENTIAL ), sp.Q.positive( Potential.DEFAULT_POTENTIAL ), 
              sp.Q.positive( hbar ), sp.Q.real( hbar ) ): 
    print( sp.ask( sp.Q.positive( k_0 ) ) )
```
Output: `None`

Here basically what is happening is `k_0_squared` is a fraction `k_0^2 = 2mE/hbar` I tell sympy to assume that everything in that fraction is real and positive, but it can not infer that k_0 is then positive.

Thanks, 
 - Chris

**Comment by oscarbenjamin** [comment]
The code shown doesn't run because there are lots of missing imports and undefined variables.

I think a lot of what you're expecting to happen here is not really implemented yet in sympy (and can be improved). In any case though it seems that the basic premise of what you want here doesn't work:

Assuming that `k_0^2 > 0` does not imply that `k_0 > 0` because the square of a negative real number is positive.

**Comment by cgbsu** [comment]
> The code shown doesn't run because there are lots of missing imports and undefined variables.
> 

It is a snippet/minimal example from a JupyterLab notebook (there is a lot in between, and I did not include `import sympy as sp`)

> ... In any case though it seems that the basic premise of what you want here doesn't work:
> 
> Assuming that `k_0^2 > 0` does not imply that `k_0 > 0` because the square of a negative real number is positive.
>

While its true `k_0^2 > 0` does not imply that `k_0 > 0`, if all the variables/constants that make up `k_0^2` 
are real and positive, `k_0` is real and positive.

> I think a lot of what you're expecting to happen here is not really implemented yet in sympy (and can be improved). ...

Also do you have a suggestion for something that has this kind of capability?

**Comment by oscarbenjamin** [comment]
> While its true `k_0^2 > 0` does not imply that `k_0 > 0`, if all the variables/constants that make up `k_0^2`
> are real and positive, `k_0` is real and positive (like in my example if `k_0^2 = 2mE/hbar` and `m > 0` and `E > 0` and `hbar > 0`)

Think carefully about this: the square of a negative number is positive. Any positive solution for `k_0` in your equation is also matched by a negative solution.

**Comment by cgbsu** [comment]
if `m >= 0` and `E >= 0` and `hbar > 0` is greater than zero, then `2mE/hbar >= 0` -> `sqrt(2mE/hbar) >= 0`


The solution for the root of [this equation](https://www.desmos.com/calculator/nsznn9dzcx) which has one positive solution and non-zero value for `sqrt((2^2)-(4*(-2)*1))` in the quadratic equation.

Though your right, in the te first expression, if there was a minus sign in there somewhere `a` and `b` are positive but if we don't know `a >= b` and `a - b` we don't know `a > b`, then we could get a negative value 


In addition: I did include an assumption that could have contributed if there were a negative value `total_energy > Potential.DEFAULT_POTENTIAL`, so if I had substituted my other `k_1^2 = 2*(V_0-E)m/hbar^2` for `k_0^2 = 2mE/hbar` this also could have worked.

**Comment by oscarbenjamin** [comment]
Suppose your equation was `x^2 = 1`. The rhs is positive. Does that imply that `x` is positive?

**Comment by cgbsu** [comment]
> Suppose your equation was `x^2 = 1`. The rhs is positive. Does that imply that `x` is positive?

No

**Comment by oscarbenjamin** [comment]
I don't know whether your argument is based on something in the code that you *haven't* shown (as I said the OP code is incomplete) but as far as I can tell the output `None` from `ask` is correct. No equation involving only the square of `k_0` can determine the sign of `k_0` regardless of any assumptions about the other variables in the equation.

**Comment by cgbsu** [comment]
Ctrl+F and search [here](https://github.com/cgbsu/ResearchSpring2022SymbolicNotebooks0/blob/borked/work/learn_sympy_qm/tunneling/tunnel_ideal_0.ipynb)

**Comment by ThePauliPrinciple** [comment]
```
k_0=-sqrt(2)
total_energy = 1
mass = 1
hbar = 1
(-sqrt(2))**2 = 2*1*1*1
```
Here a negative `k_0` has a solution to the equation with all constants being positive.

**Comment by cgbsu** [comment]
> ```
> k_0=-sqrt(2)
> total_energy = 1
> mass = 1
> hbar = 1
> (-sqrt(2))**2 = 2*1*1*1
> ```
> 
> Here a negative `k_0` has a solution to the equation with all constants being positive.

Your correct, I would need more constraints
