### ISSUE TITLE
Sympy can't solve integral

### ISSUE THREAD

**Issue by NGeorgescu** [sympy/sympy#23246]
I tried solving the integral in [this reddit post](https://www.reddit.com/r/mathmemes/comments/tfchgw/wifi_question/).
[Wolfram alpha can solve it](https://www.wolframalpha.com/input?i=integrate%28%28x%5E3*cos%28x%2F2%29%2B1%2F2%29*sqrt%284-x%5E2%29%2C%28x%2C-2%2C2%29%29). But in sympy this is the result:

```

Python 3.9.7 (default, Sep 10 2021, 14:59:43) 
[GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sympy as sp
>>> sp.__version__
'1.10'
>>> x = sp.var('x')
>>> sp.integrate((x**3*sp.cos(x/2)+1/2)*sp.sqrt(4-x**2),(x,-2,2))
1.0*Integral(1.0*x**3*sqrt(4 - x**2)*cos(x/2), (x, -2, 2)) + 1.0*Integral(0.5*sqrt(4 - x**2), (x, -2, 2))

```

Interestingly, if you break up the expression, you get:

```
>>> sp.integrate(x**3*sp.sqrt(4 - x**2)*sp.cos(x/2),(x,-2,2)) + sp.integrate(0.5*sp.sqrt(4 - x**2),(x,-2,2))
Integral(x**3*sqrt(-(x - 2)*(x + 2))*cos(x/2), (x, -2, 2)) + 1.0*pi

```
so it seems to be the first part of the expression there that is giving the engine some issue.

**Comment by praneethratna** [comment]
I'm not sure but seems like the problem here is with trigonometric function as multiplicand since, 
```
>>> integrate(x**3*sqrt(4 - x**2),(x,-2,2))
0
```
and `integrate(x**3*sqrt(4 - x**2)*cos(x/2),(x,-2,2))` should also be `0`.

**Comment by NGeorgescu** [comment]
Careful: remember integration by parts. ∫vdu = uv-∫udv, integration is additive, i.e ∫(f(x)+g(x))dx = ∫f(x)dx + ∫g(x)dx, but (f(x)g(x))dx ≠ ∫f(x)dx × ∫g(x)dx and the reason for this should be somewhat intuitive, if you consider g(x) in the latter example to be a "weighting" function applied to f(x), e.g. f(x) might go above and below the axis equally over some period, but if you weight the positive portion or negative portions of those graphs more highly then you end up with a non-zero integral for the product ∫f(x)g(x)dx

**Comment by NGeorgescu** [comment]
Hey! Found another meme integral that sympy can't solve:

    >>> sp.integrate((3*x**3-x**2+2*x-4)/sp.sqrt(x**2-3*x+2),(x,0,1))
    Integral((x - 1)*(3*x**2 + 2*x + 4)/sqrt((x - 2)*(x - 1)), (x, 0, 1))

From [this post](https://www.reddit.com/r/mathmemes/comments/tnijs3/so_his_pin_is_298126694_thats_pretty_stupid/).  Once again, [Wolfram can solve it](https://www.wolframalpha.com/input?i=Integral%5B%283*x%5E3-x%5E2%2B2*x-4%29%2Fsqrt%28x%5E2-3*x%2B2%29%2C%7Bx%2C0%2C1%7D%5D). 

Also:

    Python 3.10.2 (main, Jan 15 2022, 19:56:27) [GCC 11.1.0] on linux
    >>> sp.__version__
    '1.9'

**Comment by oscarbenjamin** [comment]
In both of the cases that you have linked Wolfram Alpha does not compute the definite integral in an exact symbolic form. Instead it computes an approximate numeric result. If you want to do the same with SymPy then you can use `Integral(...).evalf()`:
```python
In [6]: Integral((x**3*cos(x/2)+1/2)*sqrt(4-x**2),(x,-2,2)).evalf()
Out[6]: 3.14159265358979

In [8]: Integral((3*x**3-x**2+2*x-4)/sqrt(x**2-3*x+2),(x,0,1)).evalf()
Out[8]: -2.98126694400554
```
This should be better documented though. Closing in favour of #23025.
