### ISSUE TITLE
mechanics dot() doesn't work for vectors and dyadics

### ISSUE THREAD

**Issue by moorepants** [sympy/sympy#23268]
```python
import sympy as sm
import sympy.physics.mechanics as me

dx, dy, dz, m = sm.symbols('dx, dy, dz, m')

N = me.ReferenceFrame('N')

r_O_Bo = dx*N.x + dy*N.y + dz*N.z

U = me.outer(N.x, N.x) + me.outer(N.y, N.y) + me.outer(N.z, N.z)

I_Bo_O = m*(me.dot(me.dot(r_O_Bo, r_O_Bo), U) - me.outer(r_O_Bo, r_O_Bo))
```

This fails with an error stating that `me.dot()` only works with vectors. This should work with vectors dotted with dyadics.

**Comment by faze-geek** [comment]
Dot of a `vector` X `dyadic `gives a vector . 
SymPy allows this -

```
>>> from sympy.physics.vector import ReferenceFrame, outer
>>> N = ReferenceFrame('N')
>>> D1 = outer(N.x, N.y)
>>> D1.dot(N.y)
N.x
>>> (N.y).dot(D1)
0
```

Just pointed out since it is relevant , to know about this issue I'll have to look into the particular code snippet above .

**Comment by faze-geek** [comment]
@moorepants Could you recheck the example here `me.dot(r_O_Bo, r_O_Bo)`
```
>>> a = dot(r_O_Bo,r_O_Bo)
100
>>> a.is_Vector
False
>>> a.is_scalar
True
```

**Comment by moorepants** [comment]
Ah, I was trying to dot a scalar and a dyadic, which is incorrect.
