### ISSUE TITLE
`physics.units`: `Prefix` does not print clean LaTeX

### ISSUE THREAD

**Issue by dyc3** [sympy/sympy#23280]
`Prefix` does not appear to have an implemented LaTeX representation for pretty printing.

For example, printing LaTeX for the prefix `milli` gives:

![image](https://user-images.githubusercontent.com/1808807/159921665-e916012d-7b36-40cf-816f-9f3fca3d015c.png)

**Comment by oscargus** [comment]
This is slightly improved in https://github.com/sympy/sympy/pull/23646

However, the prefix handling seems a bit arbitrary in that sometimes the prefix is turned into a number and sometimes not. (But that is really another issue.)
