### ISSUE TITLE
Lambda appearance in IPython notebook: use LaTeX `\mapsto`

### ISSUE THREAD

**Issue by dpsanders** [sympy/sympy#2328]
I have just (5 minutes ago) discovered `sympy.Lambda`.
I was using the standard Python `lambda`, which seems to work OK -- is `sympy.Lambda` some kind of wrapper around Python's `lambda`?

However, it would be great if instead of the LaTeX representation looking like
 
    \Lambda(x, x^2)

it gave instead the standard mathematical notation for an anonymous function, namely:

    x \mapsto x^2

I would be happy to make this change if someone points me to the right place in the source code...

**Comment by jcrist** [comment]
Closed by #7660.
