### ISSUE TITLE
Regression in is_integer for Mul of Pow

### ISSUE THREAD

**Issue by oscarbenjamin** [sympy/sympy#23287]
This should give None as output rather than False:
```python
In [9]: x = symbols('x') # no assumptions set

In [10]: (x**2/2).is_integer
Out[10]: False
```
This is a regression tracked to 9bb7873c96821234591ff0d72eca249590ea22b4 from #22250

CC @smichr

**Comment by smichr** [comment]
Looks like `if not numerators and denominators and all(is_gt(_...` should be `if not unknown and not numerators...`
