### ISSUE TITLE
is_real issue

### ISSUE THREAD

**Issue by proy87** [sympy/sympy#23309]
`x = Symbol('x', real=True)`
`(x*I).is_real` returns `None`, not `False`.

Is it correct?

**Comment by gschintgen** [comment]
For x=0, the expression is indeed real, so depending on x the correct answer can be True or False, hence is_real returns None meaning undecidable.

**Comment by proy87** [comment]
@gschintgen , I see.

**Comment by oscarbenjamin** [comment]
If you declare `x` to be nonzero then the query can be resolved:
```python
In [1]: x = symbols('x', nonzero=True)

In [2]: (I*x).is_real
Out[2]: False
```
Note that nonzero=True also implies real=True:
https://docs.sympy.org/latest/guides/assumptions.html#predicates

**Comment by proy87** [comment]
@oscarbenjamin , why nonzero implies real? Can't complex number be nonzero?

I have an arbitrary expression, involving real (nonzero) variables. I want to check whether this expression has imaginary part. What is the best way to do this? `(x*I).is_real` or `(x*I).has(I)`?

Also, if I set a `nonzero` assumption, where is it used? I'm afraid it could break my code.

**Comment by oscarbenjamin** [comment]
> why nonzero implies real?

That's just the way the predicate is defined in sympy (see the docs I linked). Probably it is trying to be similar to `nonnegative` and `nonpositive`.

> Can't complex number be nonzero?

You can define a symbol representing a nonzero complex number with `Symbol(..., complex=True, zero=False)`.

> I want to check whether this expression has imaginary part. What is the best way to do this? `(x*I).is_real` or `(x*I).has(I)`?

It really depends on the context. With `has` you have a purely structural check. The assumptions system is for semantic checks that involve the assumptions on the symbols. You probably should check `is_real`.

**Comment by proy87** [comment]
@oscarbenjamin , thank you!
