### ISSUE TITLE
Matrix right division fails due to decorator 

### ISSUE THREAD

**Issue by chrisjohgorman** [sympy/sympy#23356]
Hello,

I am trying to get the following code to work.  I can get this working by multiplying by `a*b.inv()` but think we should be able to perform the same calculation with a right division operation.  This operation fails due to a decorator for `__rtruediv__` in `sympy/core/expr.py`.  A simple commenting out of the decorator allows this to proceed.  (I have attached a patch that does just this, but suspect that there is a better solution.)
[octsympy-1079.patch.txt](https://github.com/sympy/sympy/files/8475733/octsympy-1079.patch.txt)

```
In [25]: a
Out[25]: 
⎡9   19⎤
⎢      ⎥
⎣19  41⎦

In [26]: b
Out[26]: 
⎡1  3⎤
⎢    ⎥
⎣4  8⎦


In [27]: a / b
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Input In [27], in <cell line: 1>()
----> 1 a / b

File ~/src/sympy/sympy/core/decorators.py:106, in call_highest_priority.<locals>.priority_decorator.<locals>.binary_op_wrapper(self, other)
    104         if f is not None:
    105             return f(self)
--> 106 return func(self, other)

File ~/src/sympy/sympy/matrices/common.py:2729, in MatrixArithmetic.__truediv__(self, other)
   2727 @call_highest_priority('__rtruediv__')
   2728 def __truediv__(self, other):
-> 2729     return self * (self.one / other)

TypeError: unsupported operand type(s) for /: 'One' and 'MutableDenseMatrix'
```

**Comment by chrisjohgorman** [comment]
Further investigation into the error after the decorator, line 2729, can be rewritten as `
return self * other.inv()`, which is works, but is also probably not desired.  I believe the original reading should be something like, in matrix terms, `A * B**(-1)`.  I will wait on playing with this further until someone more experienced than me can comment.

**Comment by cbm755** [comment]
It might be that SymPy is not intending to support system solves via this operator (I mean, maybe it was just a coincidence that it worked before).  But I'm not sure the current state.

Do the docs give any indication of what should happen and what what classes of objects?

Assuming this is a regression, then Gaussian elimination would be better than explicitly inv computation for example.

**Comment by chrisjohgorman** [comment]
I took a look through the documentation and didn't see anything for division.  So, I suppose that sympy is not supporting division as it's not a common matrix operation.  Given this appears to be a regression, are you suggesting doing something like the following to get back our [1, 2; 3, 4] matrix?
```
a = Matrix([[9, 19], [19, 41]])
b = Matrix([[1, 3], [4, 8]])
c = b.row_join(eye(2))
d = c.rref()
e = d[0]
e.col_del(0)
e.col_del(0)
a*e
```
Or is there a better solution?

**Comment by oscarbenjamin** [comment]
There is no matrix division operation in Python. The operation you show above is:
```python
In [100]: b.T.solve(a.T).T
Out[100]: 
⎡1  2⎤
⎢    ⎥
⎣3  4⎦
```
The transposes are needed because you're expecting the product `a*inv(b)` For `inv(b)*a` it's just `a.solve(b)`.

**Comment by cbm755** [comment]
Ok, we'll do this downstream then, thanks @oscarbenjamin for the hints on `a.solve(b)` and similar.
