### ISSUE TITLE
`sympy.parsing.latex.parse_latex` raising an error with `antlr4-python3-runtime==4.10`

### ISSUE THREAD

**Issue by harpiano18** [sympy/sympy#23355]
`sympy==1.10.1`
`antlr4-python3-runtime==4.10`
Python 3.8.8 on Ubuntu 20.04LTS

When trying to use `sympy.parsing.latex.parse_latex` on a string, I get the following error:
```
>>> from sympy.parsing.latex import parse_latex 
>>> poly = '4y^2+4a^4-8ya^2'
>>> print(parse_latex(poly))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/sofia/anaconda3/lib/python3.8/site-packages/sympy/parsing/latex/__init__.py", line 35, in parse_latex
    return _latex.parse_latex(s)
  File "/home/sofia/anaconda3/lib/python3.8/site-packages/sympy/parsing/latex/_parse_latex_antlr.py", line 73, in parse_latex
    lex = LaTeXLexer(stream)
TypeError: 'NoneType' object is not callable
```

No issue found with `antlr4-python3-runtime==4.9.3`

**Comment by wermos** [comment]
The LaTeX parser still uses the Python2 ANTLR runtime. There have been efforts to update the parser ([here](https://github.com/sympy/sympy/issues/19751) and [here](https://github.com/sympy/sympy/issues/22625)) but they have been unsuccessful so far.

**Comment by asmeurer** [comment]
Unfortunately, the way antlr works it is pinned to a specific version of the runtime. It's actually only supposed to work for version 4.7. I had thought there was some code that checked the version and printed a warning, but maybe there isn't. 

We might consider updating the runtime to a newer version, if it isn't difficult to do.

**Comment by xrmx** [comment]
Took a stab at this here https://github.com/sympy/sympy/pull/23369

Also trying to get an accessible version from antlr runtime for being able to choose a parser at runtime https://github.com/antlr/antlr4/pull/3658
