### ISSUE TITLE
ODE hint doesn't match

### ISSUE THREAD

**Issue by KangOxford** [sympy/sympy#23387]
**Input**
```python
from sympy import *
t  = Symbol("t")
b0 = Function("b0")(t)
b1 = Function("b1")(t)
b2 = Function("b2")(t)
B = Function("B")(t)
expr = Eq(b0+b1*B+b2*B*B + B.diff(t),0)
dsolve(expr,hint = "1st_rational_riccati")
```
**output**
```ODE B(t)**2*b2(t) + B(t)*b1(t) + b0(t) + Derivative(B(t), t) does not match hint 1st_rational_riccati```

**Comment by KangOxford** [comment]
<img width="785" alt="image" src="https://user-images.githubusercontent.com/37290277/163944008-1be8c6b5-a6cc-43be-a629-fa7f180bd429.png">

**Comment by praneethratna** [comment]
I think you need to define `b0(t)` , `b1(t)` and `b2(t)` with definite values of `t` like `t**2` , since Sympy is unable detect `b0(t)` , `b1(t)` and `b2(t)` as Rational functions.

**Comment by oscarbenjamin** [comment]
The `1st_rational_riccati` solver cannot solve equations that have undefined functions in. It isn't possible to write down the general solution for a Riccati ODE in terms of arbitrary functions.
