### ISSUE TITLE
For some reason I am unable to solve this Inequation 

### ISSUE THREAD

**Issue by HlexNC** [sympy/sympy#23391]
```py
print(solveset(cos(sqrt(3-8*x-3*x**2)) + (2*x+5)/(x+2), '>='))
```
<img src="https://user-images.githubusercontent.com/66517969/164003884-512d68e6-63b6-49c2-bd3d-bdafa8e54806.png" width="500">
The correct answer is:
<img src="https://user-images.githubusercontent.com/66517969/164003928-ee409221-36e2-46b7-b813-1fcbcdd82372.png" width="500">

**Comment by oscarbenjamin** [comment]
That is not the correct answer.

**Comment by oscarbenjamin** [comment]
Also the code as shown doesn't run.

**Comment by HlexNC** [comment]
> That is not the correct answer.

But I am not answering... I am asking how to fix the problem. I am the one asking a question.

**Comment by oscarbenjamin** [comment]
Asking questions is not what GitHub issues are for. You can use stackoverflow for that or the sympy mailing list:
https://stackoverflow.com/
https://groups.google.com/g/sympy
