### ISSUE TITLE
Documentation website 404

### ISSUE THREAD

**Issue by micahscopes** [sympy/sympy#23398]
When I navigate to https://docs.sympy.org/ I'm getting a 404 from github pages.

**Comment by ctrlaltf2** [comment]
It appears that HackerRank has (frivilously?) DMCA'd the documentation repository, resulting in the GitHub pages throwing a 404: https://github.com/github/dmca/blob/master/2022/04/2022-04-15-hackerrank.md

Infringing material is allegedly in the "solvers" section of the documentation? I can imagine either:
1. HackerRank copy-pasted sympy documentation example code into official exam solutions (highly likely)
or
2. Sympy documentation included HackerRank exam solutions into example documentation code (I don't see this happening but it's possible)

**Comment by micahscopes** [comment]
Well that's obnoxious.

**Comment by jhobbs** [comment]
Anyone have a good workaround for viewing the docs?

**Comment by asmeurer** [comment]
I have posted about this on the SymPy mailing list https://groups.google.com/g/sympy/c/yuJXymiJqws.

I am going to close this issue. As I noted on the list, we are looking into the DMCA claim and working on getting the site back up as soon as possible.
