### ISSUE TITLE
`PrimeIdeal._reduce_poly` needs work

### ISSUE THREAD

**Issue by skieffer** [sympy/sympy#23403]
This method was kept private in v1.10. It should be repaired before v1.11.

There are different ways to "reduce" an algebraic number mod a prime ideal.
I would say the existing method lands halfway between the functionality offered by
the `nfmodpr` and `nfeltreduce` methods of PARI. While it could be useful in some
circumstances, it's not really a canonical or well-recognized form of reduction.
In many cases it's essentially the same as `nfmodpr`, but it would fail there in
cases where the rational prime `p` divided the index of the number field.

It's also a funny operation in that it accepts a poly, instead of one of our
classes that more directly represents an algebraic number.

I think an attempt at a function like `nfmodpr` is a bit premature right now.

What we do need right now is a function like PARI's `nfeltreduce`, in order to best resolve #23402.
And for this there is a simple algorithm in the literature, namely Alg 1.4.12 of Cohen's second
book (Advanced Topics in Computational Number Theory).

**Comment by oscarbenjamin** [comment]
I think this looks good but I haven't really followed in detail what the different functions are doing...

**Comment by skieffer** [comment]
Ah, I meant to elaborate on the PR, and explain:

* Basically, this adds the `Submodule.reduce_element()` method.
* Everything else is a bunch of conversion and convenience methods, so that you can do this reduction on any of the three classes, `AlgebraicNumber`, `ANP`, and `PowerBasisElement`, that represent algebraic numbers.
