### ISSUE TITLE
`CRootOf` should have a `lazy` option

### ISSUE THREAD

**Issue by skieffer** [sympy/sympy#23418]
When you construct a `CRootOf`, it makes an initial approximation of the roots
right then, at construction time. It would be good if `CRootOf` offered a `lazy` option, so
that these approximations wouldn't be computed until they were needed.

I imagine this might have many applications, but at the moment I just have one application in mind:
When you form an `AlgebraicNumber` whose root is given by a `CRootOf`, it can be extremely slow, due
to this approximation of roots.

This is not good, because there are many things you can do with an `AlgebraicNumber` that do not
require these approximations at all. For many applications, it is just wasted time.

For example, just forming a field:

```python
>>> import time
>>> from sympy import QQ
>>> t0 = time.time(); k = QQ.cyclotomic_field(47); t1=time.time();
>>> print(t1-t0)
39.494821071624756
```

can take 40 seconds. This should be instantaneous.

**Comment by oscarbenjamin** [comment]
Why does `lazy` need to be an option? Shouldn't delayed computation just be automatic?

Maybe it makes more sense to have a separate class for a RootOf that is only intended to have defined algebraic behaviour i.e. it can represent a root of a polynomial without specifying which root. With that we could also represent roots of polynomials over arbitrary domains including domains involving symbols (i.e. algebraic functions).

**Comment by skieffer** [comment]
> Shouldn't delayed computation just be automatic?

Good question. Basically I was just erring on the conservative side. But maybe you're right -- maybe this would always be better.
