### ISSUE TITLE
Easy-to-Fix : Change year in SymPy license.

### ISSUE THREAD

**Issue by faze-geek** [sympy/sympy#23424]
Over the past 2 weeks some new contributors showed up at SymPy's Google Group / GitHub page (particularly because of GSoC) wanting to start their open source journey. A few had also requested if they could be pointed out to some easy quick fixes. I accidently came across one, it can be labelled `Easy to Fix`  and `good first issue`.

The fix is to simply change the year in the licenses from 2021 to 2022 mimicing #20952 (which changed 2020 to 2021 more than a year ago).

**Comment by Saksham-13** [comment]
Opened a pull request regarding this.
