### ISSUE TITLE
simplify() and together() can't simplify such a simple formula, Why?

### ISSUE THREAD

**Issue by Gritbadger** [sympy/sympy#23429]
I have simple expr, i.e. 
![image](https://user-images.githubusercontent.com/101034640/165564835-87bd7806-c4c9-4274-b011-21b5f0fa68c6.png)
But neither simplify() nor together()  and all other reduce functions can reduce this expression to a simple form, like **B/T*t**, this is very simple, if do it by hand, it can be simplified very quickly。

**Comment by Gritbadger** [comment]
Thanks, I know, I didn't define B and T to be positive, so python didn't simplify it just to be on the safe side.
In addition, can I convert the derivative form, like 
![image](https://user-images.githubusercontent.com/101034640/165586816-30dfb285-e5e8-44dc-a933-ac46cfd8113e.png)
 into a more concise 
![image](https://user-images.githubusercontent.com/101034640/165586866-db5e60c4-dc3e-4a10-8f6e-977e54b7325e.png)
 form in sympy? What function can I use?

**Comment by oscarbenjamin** [comment]
That's to do with printing. I'm closing this because GitHub issues are not for getting help with using sympy. You can use the mailing list for that:
https://groups.google.com/g/sympy
