### ISSUE TITLE
Can I convert the derivative form more simply?

### ISSUE THREAD

**Issue by Gritbadger** [sympy/sympy#23431]
Can I convert the derivative form, like 
![image](https://user-images.githubusercontent.com/101034640/165586816-30dfb285-e5e8-44dc-a933-ac46cfd8113e.png)
 into a more concise 
![image](https://user-images.githubusercontent.com/101034640/165586866-db5e60c4-dc3e-4a10-8f6e-977e54b7325e.png)
 form in sympy? What function can I use?

_Originally posted by @Gritbadger in https://github.com/sympy/sympy/issues/23429#issuecomment-1111301250_

**Comment by faze-geek** [comment]
What is the motivation for this issue? Anyways **d(x)/dt** and **x'(t)** are the same and concise representation would not have any mathematical advantage over the other. This is related to the printing module and could be closed I guess .
