### ISSUE TITLE
Why `Eq((x**2)/2, 0)` returns False?

### ISSUE THREAD

**Issue by auntyellow** [sympy/sympy#23439]
I tried sympy 1.10.1
```
from sympy import *

x = symbols('x')
print(Eq((x**2)/2, 0))
```
The result is `False`.
I think `Eq((x**2)/2, 0)` should be the same as `Eq(x**2, 0)`.

**Comment by oscarbenjamin** [comment]
This has already been fixed on master in a3277e4067edbd3178450a4c37824326ed01579e from  #23289
