### ISSUE TITLE
Error displaying indexes in VS Code

### ISSUE THREAD

**Issue by jiboncom** [sympy/sympy#23436]
I am not sure if this is a Sympy bug or a VS Code one. 
When working with Idx I am unable to display my equations. I get the following error:
`ParseError: KaTeX parse error: Undefined control sequence: \nobreakJ at position 33: …_{0\mathrel{..}\̲n̲o̲b̲r̲e̲a̲k̲J̲ ̲- 1}`

As you may see, there is an space missing between the "\nobreak" and the index upper limit "J".

My code is:
```
import sympy as sp
J = sp.symbols('J')
j = sp.Idx('j', J)
display(j)
```

**Comment by ThePauliPrinciple** [comment]
This is definately a bug (introduced by me). Can you confirm whether https://github.com/sympy/sympy/pull/23437 fixes the issue for you?

**Comment by jiboncom** [comment]
> This is definately a bug (introduced by me). Can you confirm whether #23437 fixes the issue for you?

Like a charm! Many thanks. Wasn't expecting an answer so quickly. 

<img width="184" alt="image" src="https://user-images.githubusercontent.com/19602667/165748180-58b9f718-8535-479b-945c-295f7ec460ff.png">
