### ISSUE TITLE
Simplifying inequalities

### ISSUE THREAD

**Issue by parsarahimi** [sympy/sympy#23441]
I am trying to simplify something similar to this
`x = Symbol("x", positive=True)
eq1 = (x < 1)
eq2 = (x < 2)
display(simplify(eq1 & eq2))
`
Which outputs x<1∧x<2 instead of x<1 only which is to be expected.

**Comment by oscarbenjamin** [comment]
Seems to be working to me:
```python
In [1]: x = Symbol("x", positive=True); eq1 = (x < 1); eq2 = (x < 2); display(simplify(eq1 & eq2))
x < 1

In [2]: eq1 & eq2
Out[2]: x < 1 ∧ x < 2

In [3]: simplify(eq1 & eq2)
Out[3]: x < 1
```
What version of sympy are you using?

**Comment by oscarbenjamin** [comment]
Okay, I'll close this then. Thanks for reporting!
