### ISSUE TITLE
Getting True Valuations of A Logical Formula

### ISSUE THREAD

**Issue by alpaylan** [sympy/sympy#23453]
I have a logical expression and I want to get all variable assignments that make it true. I first thought of creating the truth table and filtering out the `True` rows but that(not surprisingly) is unfeasible. Is there any easy way of doing this?

**Comment by eagleoflqj** [comment]
Try converting your expression to Disjunctive Normal Form but I don't think it better than a truth table in terms of time complexity. See https://en.wikipedia.org/wiki/Boolean_satisfiability_problem
I'm going to close the issue as it seems irrelevant to sympy.
