### ISSUE TITLE
integrate(sqrt(53225*t**2 - 66732*t + 23013), t) fails to integrate

### ISSUE THREAD

**Issue by Zhang-Junzhi** [sympy/sympy#23485]
`sqrt(53225*t**2 - 66732*t + 23013)` is integratable.

The indefinite integral should be `(111576969*asinh((53225*t-33366)/10563)+(125*2129**(3/2)*t-166830*sqrt(2129))*sqrt(53225*t**2-66732*t+23013))/(250*2129**(3/2))`

But `integrate(sqrt(53225*t**2 - 66732*t + 23013), t)` just returns `Integral(sqrt(53225*t**2 - 66732*t + 23013), t)`.

**Comment by eagleoflqj** [comment]
I plan to support all kinds of `sqrt(a+bx+cx^2)` after #23489 is merged, using manual integration. While there might be ways to support that in other integration methods, manual method is a must for providing steps in [SymPy Beta](https://sympy-beta.vercel.app/).
