### ISSUE TITLE
Integral fails to integrate

### ISSUE THREAD

**Issue by jaded0** [sympy/sympy#23495]
Attempting to integrate:
`integrate(z*sec(z)*tan(z))`

Expected behavior is that it either successfully computes and shows the antiderivative or it returns an error or warning. 

This is really those two issues. By hand, the result is x*sec(x)-ln(|sec(x)+tan(x)|)

**Comment by eagleoflqj** [comment]
This formula should be applied
![Screenshot from 2022-05-15 12-43-52](https://user-images.githubusercontent.com/26783539/168484098-69d314f3-aaea-4b9f-b520-7106bb9d392c.png)
I think we can do it in manual integration.

**Comment by gxyd** [comment]
@eagleoflqj I was thinking of this integral, I'm also interested in SymPy having the capability to be able to solve integrals of the form:


![image](https://user-images.githubusercontent.com/7712241/168797786-5c7d0e90-1a2a-41bd-9a8f-4f715ea029c0.png)


Have you already sent in a PR fixing this type of issue? I'll happy to my put my comments in that case.

If not, I can try to work on it.

**Comment by gxyd** [comment]
Though for this, neither is the Risch Algorithm able to find its integral.
```py
>>> integrate(x * sec(x) * tan(x), x)
∫𝑥tan(𝑥)sec(𝑥)𝑑𝑥
```

**Comment by oscarbenjamin** [comment]
The integral can be computed with a rewrite to sin/cos:
```python
In [111]: f = z*sec(z)*tan(z)

In [112]: i = integrate(f, z)

In [113]: i
Out[113]: 
⌠                   
⎮ z⋅tan(z)⋅sec(z) dz
⌡                   

In [114]: i.rewrite('sincos')
Out[114]: 
⌠            
⎮ z⋅sin(z)   
⎮ ──────── dz
⎮    2       
⎮ cos (z)    
⌡            

In [115]: i.rewrite('sincos').doit()
Out[115]: 
        2⎛z⎞                     ⎛   ⎛z⎞    ⎞    2⎛z⎞      ⎛   ⎛z⎞    ⎞      ⎛   ⎛z⎞    ⎞    2⎛z⎞      
   z⋅tan ⎜─⎟                  log⎜tan⎜─⎟ - 1⎟⋅tan ⎜─⎟   log⎜tan⎜─⎟ - 1⎟   log⎜tan⎜─⎟ + 1⎟⋅tan ⎜─⎟   log
         ⎝2⎠         z           ⎝   ⎝2⎠    ⎠     ⎝2⎠      ⎝   ⎝2⎠    ⎠      ⎝   ⎝2⎠    ⎠     ⎝2⎠      
- ─────────── - ─────────── + ─────────────────────── - ─────────────── - ─────────────────────── + ───
     2⎛z⎞          2⎛z⎞                2⎛z⎞                  2⎛z⎞                  2⎛z⎞                
  tan ⎜─⎟ - 1   tan ⎜─⎟ - 1         tan ⎜─⎟ - 1           tan ⎜─⎟ - 1           tan ⎜─⎟ - 1           t
      ⎝2⎠           ⎝2⎠                 ⎝2⎠                   ⎝2⎠                   ⎝2⎠                

⎛   ⎛z⎞    ⎞
⎜tan⎜─⎟ + 1⎟
⎝   ⎝2⎠    ⎠
────────────
  2⎛z⎞      
an ⎜─⎟ - 1  
   ⎝2⎠      

In [116]: F = collect(_, z, together).trigsimp()

In [117]: F
Out[117]: 
  z         ⎛   ⎛z⎞    ⎞      ⎛   ⎛z⎞    ⎞
────── + log⎜tan⎜─⎟ - 1⎟ - log⎜tan⎜─⎟ + 1⎟
cos(z)      ⎝   ⎝2⎠    ⎠      ⎝   ⎝2⎠    ⎠

In [118]: simplify(F.diff(z) - f)
Out[118]: 0
```
This is more or less the answer suggested in the OP except that without the Abs it can be valid for nonreal z as well.

**Comment by eagleoflqj** [comment]
> If not, I can try to work on it.

I plan to implement it in manual integration as it's more relevant to my [SymPy Beta](https://github.com/eagleoflqj/sympy_beta). You are familiar with risch so please go ahead as you want.
