### ISSUE TITLE
parse_latex f'(x)

### ISSUE THREAD

**Issue by eagleoflqj** [sympy/sympy#23515]
parse_latex should handle f'(x), f''(x) and so on. But currently it throws an exception.
There are 2 possible solutions.
1. parse as `Function("f'")(x)`, and let users substitute it to `Derivative(f(x), x)` on demand.
2. parse as `Derivative(f(u), u).subs(u, x)`, where `u` is a `Dummy`. The substitution is needed for parsing `f'(0)`, but that case you will get a `Subs` object, and if you convert it back to latex it will be very different from `f'(0)`.

I propose to implement solution 1. What do you think?

**Comment by asmeurer** [comment]
> if you convert it back to latex it will be very different from f'(0).

I see that as separate issues. One is that have the cleanest way to represent f'(0) (https://github.com/sympy/sympy/issues/4719), and another is that the LaTeX and pretty printers could be smarter about how they print things like f(x).diff(x).subs(x, 0), which could be printed as "f'(0)".
