### ISSUE TITLE
MatMul's coeff is not working. It throws an error about args_cnc.

### ISSUE THREAD

**Issue by JRF-2018** [sympy/sympy#23519]
I get an error when I try to take a "coeff" on a matrix.

``` python
from sympy import *
N = Symbol("N", integer=True)
x1 = Symbol("x1")
M1 = MatrixSymbol("M1", N, N)
M2 = MatrixSymbol("M2", N, N)
z = (M2 + 2 * (M2 + Identity(N)) * M1 + Identity(N))
z.coeff(M1)
```
leads to
```
Traceback (most recent call last):
  ...
AttributeError: 'list' object has no attribute 'difference'

```

For example, define the following function ...

```python
def _MatMul_fixed_args_cnc (self, cset=False, warn=True, split_1=True):
  c = [x for x in self.args if x.is_commutative]
  nc = [x for x in self.args if not x.is_commutative]
  if cset:
    clen = len(c)
    c = set(c)
    if clen and warn and len(c) != clen:
      raise ValueError('repeated commutative arguments: %s' %
                       [ci for ci in c if list(self.args).count(ci) > 1])
  return [c, nc]

def fix_MatMul_args_cnc ():
  MatMul.args_cnc = _MatMul_fixed_args_cnc
```

If you use it, it will work.

``` python
>>> fix_MatMul_args_cnc()
>>> z.coeff(M1)
2*I + 2*M2

```

With matrices, taking the coeff from the left and taking it from the right have different meanings, so I thought it might be what you intended to throw an exception, so I didn't make a pull request. I also don't want to use pull requests because I'm not familiar with GitHub and I don't speak English well.

**Comment by oscargus** [comment]
It seems like `MatMul.args_cnc` is not advanced enough for this use case. I made a change in the original `args_cnc` instead of adding your (as one would need to determine when it should be used otehrwise): #23645

Now your code returns 2*I  + 2*M2

**Comment by JRF-2018** [comment]
Thanks!
