### ISSUE TITLE
Simplify and trigsimp output is wrong

### ISSUE THREAD

**Issue by helloliver** [sympy/sympy#23531]
Here is the problem:

```python
q = Symbol("q", positive = True)
m = Matrix([
[-2*cosh(q/3),      exp(-q),            1],
[      exp(q), -2*cosh(q/3),            1],
[           1,            1, -2*cosh(q/3)]])
```

In theory, the product of `m` and its nullspace vector is zero vector, but in practice neither `simplify(m * m.nullspace()[0])` nor `trigsimp(m * m.nullspace()[0])` is zero vector.

Indeed, the result is right because it is equal to zero vector. But it is not the simplest form.

**Comment by oscarbenjamin** [comment]
Rewriting to exponential works in this case:
```python
In [21]: v = m*m.nullspace()[0]

In [22]: v.as_immutable().rewrite(exp).applyfunc(ratsimp)
Out[22]: 
⎡0⎤
⎢ ⎥
⎢0⎥
⎢ ⎥
⎣0⎦
```

**Comment by helloliver** [comment]
@oscarbenjamin Thanks for your solution. I appreciate it.
