### ISSUE TITLE
solve() giving incorrect solutions

### ISSUE THREAD

**Issue by ethanholdahl** [sympy/sympy#23557]
When using solve for the following:
`solve(x**3-x**2-y,x)`

I got a solution that is incorrect. Not sure what the issue is, but the result doesn't match Wolfram Alpha.

**Comment by smichr** [comment]
What version of SymPy are you using? All solutions substituted into the original equation simplify to 0 for me and replacing `y` with -0.1 matches the 3 real numerical solutions of `[-0.27956, 0.41261, 0.86695]`.

**Comment by ethanholdahl** [comment]
It seems that I am (gladly) mistaken and the solve() function was working perfectly fine.
I was using sympy 1.10.1 through the caracas package in R and was getting strange results when trying to evaluate the function.
Since the (unevaluated) output was the same in python and the result differed, at least cosmetically, from Wolfram Alpha, I assumed there was a mistake.

Thank you for your time spent in this fruitless issue.
