### ISSUE TITLE
Getting escaped string instead of pretty printing

### ISSUE THREAD

**Issue by akriegman** [sympy/sympy#23558]
When I try to display symbols in the repl, they get displayed as PyObjects with an escaped string representation, instead of the usual pretty printing. MWE:
```
julia> @vars x
(x,)

julia> x^2
PyObject ' 2\nx '
```
I have no idea what I may have done to trigger this. It worked correctly the last time I used SymPy.jl, and it seems like it's supposed to just work out of the box according to the docs. I'm not sure what's supposed to happen normally, but it's not happening.

**Comment by oscarbenjamin** [comment]
I expect that this is more to do with the julia wrapper than sympy itself.

**Comment by akriegman** [comment]
Sorry, I thought this was the SymPy.jl repo! Whoops!

**Comment by oscarbenjamin** [comment]
No problem!
