### ISSUE TITLE
Typo in docs

### ISSUE THREAD

**Issue by kessido** [sympy/sympy#23579]
https://github.com/sympy/sympy/blob/df0ccac5deddc9afd8a009382769cc9cbb2ae80f/sympy/ntheory/partitions_.py#L146
Need to be changed to $10^{10}$.
https://docs.sympy.org/latest/modules/ntheory.html#sympy.ntheory.partitions_.npartitions

**Comment by eagleoflqj** [comment]
Yes, it's also wrong on current master https://docs.sympy.org/dev/modules/ntheory.html?highlight=npartitions#sympy.ntheory.partitions_.npartitions
Are you willing to make a PR to correct that?

**Comment by ritikBhandari** [comment]
Can I make the PR?

**Comment by eagleoflqj** [comment]
Yes, please. Since there is no PR linked to it now.
