### ISSUE TITLE
add See Also in partitions for ordered_partitions

### ISSUE THREAD

**Issue by smichr** [sympy/sympy#23572]
`ordered_partitions` is significantly faster than the multiset-outputting `partitions` function but no mention is made of it in `partitions`. It should be mentioned in `partitions` that this alternate function exists if the user desires the flat partition. The API is not the same, however, and I'm not sure if `ordered_partitions` could be non-destructively modified to permit the same input parameters.

```python
t=time();(sum(1 for i in partitions(61)),time()-t)
(1121505, 2.12000012397766)
t=time();(sum(1 for i in aP(61)),time()-t)
(1121505, 0.690999984741211)
```

**Comment by grgkaran03** [comment]
Hi!
I would like to work on this issue. Can you please tell me the approach to solve this? 
I don't understand where should this info be mentioned to the user?

**Comment by smichr** [comment]
Look for other examples of See Also in SymPy and then add such a section to the `partitions` function for the function `ordered_partitions` which returns an expanded form of the dictionary that `partitions` returns,
```python
>>> list(partitions(5))
[{5: 1}, {4: 1, 1: 1}, {3: 1, 2: 1}, {3: 1, 1: 2}, {2: 2, 1: 1}, {2: 1, 1: 3}, {
1: 5}]
>>> list(ordered_partitions(5))
[[1, 1, 1, 1, 1], [1, 1, 1, 2], [1, 1, 3], [1, 2, 2], [1, 4], [2, 3], [5]]
```
Mention should also be made that if one just wants to count the partitions, the `nT` function from `sympy.functions.combinatorial.numbers` can be used.

**Comment by grgkaran03** [comment]
@smichr , Thanks for the response!
I wanted to ask if I am mentioning `nT` function from` sympy.functions.combinatorial.numbers`, should I add that too in see also or just mention it in the description?

**Comment by grgkaran03** [comment]
@smichr 
Please review the additions...
