### ISSUE TITLE
Use subs by referring to a symbol's label

### ISSUE THREAD

**Issue by nheinsdorf** [sympy/sympy#23607]
Some function in my code returns a sympy.Matrix, but not the symbols that were used to create the matrix. I now want to substitute some of its value using its subs() method, without using the symbols, but rather their labels. 

Some piece of code to recreate the behavior would be the following:

```
import sympy as sp
x = sp.Symbol('x', real=True)
m = sp.Matrix([[0, x], [0, 0]])
x = 'something_else'
print(m.subs(x, 10))
```

I know that I could just return the symbols that were used to create the matrix, or use something like `list(m.free_symbols)`, but I think it would be a nice feature if I could do something like this instead:
```
m.subs('x', 10)
```

**Comment by oscarbenjamin** [comment]
There are already too many places in sympy that accept strings. We should be removing those rather than adding more.

**Comment by asmeurer** [comment]
The requested behavior would also be inconsistent with the other functions that do accept strings right now. Right now, `some_function('x')` is equivalent to `some_function(sympify('x'))` which would produce `some_function(Symbol('x'))`. But the requested behavior here is to somehow find every symbol named `'x'` independent of assumptions and replace it.

> Some function in my code returns a sympy.Matrix, but not the symbols that were used to create the matrix. I now want to substitute some of its value using its subs() method, without using the symbols, but rather their labels.

Returning the symbols used in an expression is a good pattern to follow. You can use `free_symbols`, but with the caveat that that might return more than you want if you have symbolic constants. 

Another thing to be aware of is that if you always use exactly the same symbols, you can just create them again, like

```py
def some_function():
    x = Symbol('x', real=True)
    return Matrix([[0, x], [x, 0]])

...

x = Symbol('x', real=True)
some_function().subs(x, 10)
```

Two symbols with the same name and assumptions are always considered equal, so there's no issue with creating the same symbol more than once. SymPy will treat both symbol objects as identical.

A third pattern that sometimes makes sense if you just have a handful of symbols used everywhere is to just define them once at the top of the file

```py
x = Symbol('x')

...

def your_function():
    return Matrix([[0, x], [x, 0]])

...

some_function().subs(x, 10)
```

**Comment by nheinsdorf** [comment]
Ok, I understand why this is inconsistent with other functions. Thank you!
