### ISSUE TITLE
integrate(1/sqrt(1-exp(2*x)))

### ISSUE THREAD

**Issue by eagleoflqj** [sympy/sympy#23619]
Origin: https://www.zhihu.com/question/510014861

**Comment by mjg** [comment]
That solution is valid for negative x only [*]. If you tell SymPy more, you get a solution, e.g.:
```
import sympy as sym
x = sym.Symbol("x", positive=True)
sym.integrate(1/sym.sqrt(1-sym.exp(-2*x)), x)
```
gives you
```
acosh(exp(x))
```
which is the nicer form to represent the result from the note. (Being a SymPy novice, I don't know how to specify the assumption `x < 0`, so I changed to the variable to `-x > 0` ... Can this be done with domains like for solveset?)

[*] ... in the reals. Admittedly, SymPy simply choses a principal branch on other occasions.
