### ISSUE TITLE
the first element of `sympy.Array` object won't show in latex output

### ISSUE THREAD

**Issue by viocha** [sympy/sympy#23620]
when the array length is greater than 10,  the latex environment will be `\begin{array} \end{array}`, and because of the missing mandatory arguments of `array` environment , the first element 0 is taken for the arguments.
![image](https://user-images.githubusercontent.com/66580331/173239078-44806fc5-980f-4403-8a11-ea3988431b0c.png)

it may be due to the method `sympy.printing.latex.LatexPrinter._print_NDimArray` 
![image](https://user-images.githubusercontent.com/66580331/173239113-4a62fad1-590e-4fe6-bcc9-5dc4bf7aa924.png)

one alternative solution is using `array` environment like `\beg{array}{} ... \end{array}`

and the same problem in matrix printing is handled properly
![image](https://user-images.githubusercontent.com/66580331/173239697-cd5bcc13-f69f-4ba1-8712-27d1e28a8b39.png)

**Comment by eagleoflqj** [comment]
I can confirm the problem on master. And your solution looks good!
Are you willing to make a PR for that?
