### ISSUE TITLE
Add a flag to remove automatic rationalization of fractional value in nsimplify

### ISSUE THREAD

**Issue by rishacha** [sympy/sympy#23626]
For a conversion like this - 

```py
raw_value = (0.707106781-0j)
value = sympy.nsimplify(raw_val, constants=(sympy.pi,), rational=False)
sympy.latex(value,full_prec=False)
```
Current output:
I get the value as `sqrt(2)/2` and the latex as $\frac{\sqrt{2}}{2}$

Expected output:
I need value as `1/sqrt(2)` and latex as $\frac{1}{\sqrt{2}}$

Is it possible to add a flag that removes any automatic rationalization in this case?

**Comment by eagleoflqj** [comment]
I don't think this kind of conversion should be added to `nsimplify`. You can define a function to convert `sqrt(n)/n` to `Pow(n, -S.Half, evaluate=False)` and use the function to post-process the result of `nsimplify`.

**Comment by eagleoflqj** [comment]
Could you offer more examples that can represent your need, with expected output?

**Comment by oscarbenjamin** [comment]
What flag are you proposing to add and what would it do? What function would the flag be added to?

**Comment by rishacha** [comment]
#### Proposed flag --> `derationalize`
The above flag would be `False` by default. If it's `True` - Don't rationalize the fraction.

I'm not sure what's the best place we can add such a flag but I have 2 suggestions -->

1. https://github.com/sympy/sympy/blob/7f72eb9bc20b4b24ade8436f98c51ae6be883e08/sympy/parsing/sympy_parser.py#L912-L915
2. https://github.com/sympy/sympy/blob/7f72eb9bc20b4b24ade8436f98c51ae6be883e08/sympy/simplify/simplify.py#L1375-L1376

**Comment by rishacha** [comment]
This seems related - fredrik-johansson/mpmath/issues/236

`mpmath` hasn't resolved this issue and hence, sympy is the best option. 

```py
mpmath.identify('0.707106781')
```
**Output**: `'sqrt(((4-sqrt(0))/8))'`

**Comment by oscarbenjamin** [comment]
> This seems related - [fredrik-johansson/mpmath/issues/236](https://github.com/fredrik-johansson/mpmath/issues/236)

I don't think it is related.

In the case of `parse_expr` you can already do this although there is an awkward 1 in the result:
```python
In [3]: parse_expr('1/sqrt(2)', evaluate=False)
Out[3]: 
  1 
1⋅──
  √2
```
For `nsimplify` it doesn't make any sense to add this. The underlying algorithm will compute the polynomial `2*x**2 - 1` and then find the roots of that. Any flag like `derationalize` would be a post-processing operation so it might as well just be handled by a separate function called `derationalize` which you could use with the output of `nsimplify` like:
```python
derationalize(nsimplify(0.707106781-0j))
```
The question then is what `derationalize` should do. What class of expressions should it operate on and how do you define which of many equivalent forms is the preferred "derationalised" one?

Your particular problem though is that you believe you have a number of the form $$\frac{1}{\sqrt{n}}$$ and you want to identify the output of `nsimplify` with that. If that's all you want then you can just do:
```python
In [5]: val = nsimplify(0.707106781-0j)

In [5]: Pow(1/val, -1, evaluate=False)
Out[5]: 
1 
──
√2
```

**Comment by rishacha** [comment]
I am fine with the above method but is there a way to figure out if the value is a fraction? I can use this flag to apply - `Pow(1/val, -1, evaluate=False)`. 

I need to identify if the value is a fraction because if the value is an integer, 
```py
val = sympy.nsimplify(1,rational=False)
sympy.latex(sympy.Pow(1/val, -1, evaluate=False))
>>>> '1^{-1}'

val = sympy.nsimplify(2)
sympy.latex(sympy.Pow(1/val, -1, evaluate=False))
>>>> '\\frac{1}{\\frac{1}{2}}'
```

**Comment by oscarbenjamin** [comment]
You can use `val.is_Rational` for that. I think this is going beyond what GitHub issues are for though. You should use the mailing list to ask for help with using SymPy.

I'm going to close this issue now because I don't see any clear description of anything that should be improved in SymPy.
