### ISSUE TITLE
No algorithms are implemented to solve equation -x**x*(log(x) + 1) + exp(x)

### ISSUE THREAD

**Issue by NSC9** [sympy/sympy#23657]
```
from sympy import E,Eq,solve,diff,Integral
from sympy.abc import x
f = E**x
g = x**x
eq3 = Eq(diff(f),diff(g))
solve(eq3)[0]
```
```
> NotImplementedError                       Traceback (most recent call last)
> Input In [12], in <cell line: 1>()
> ----> 1 solve(eq3)[0]
> 
> File ~/.local/lib/python3.8/site-packages/sympy/solvers/solvers.py:1095, in solve(f, *symbols, **flags)
>    1091 #
>    1092 # try to get a solution
>    1093 ###########################################################################
>    1094 if bare_f:
> -> 1095     solution = _solve(f[0], *symbols, **flags)
>    1096 else:
>    1097     solution = _solve_system(f, symbols, **flags)
> 
> File ~/.local/lib/python3.8/site-packages/sympy/solvers/solvers.py:1709, in _solve(f, *symbols, **flags)
>    1706 # ----------- end of fallback ----------------------------
>    1708 if result is False:
> -> 1709     raise NotImplementedError('\n'.join([msg, not_impl_msg % f]))
>    1711 if flags.get('simplify', True):
>    1712     result = list(map(simplify, result))
> 
> NotImplementedError: multiple generators [exp(x), log(x), x**x]
> No algorithms are implemented to solve equation -x**x*(log(x) + 1) + exp(x)
```

**Comment by eagleoflqj** [comment]
It's expected unless there exists a closed form solution.

**Comment by NSC9** [comment]
> It's expected unless there exists a closed form solution.

So does that mean I can't calculate the area between the curves Derivative(E^x) and Derivative(x^x) using sympy? My next step was to do:

`Integral(diff(f)-diff(g),(x,0,b)).evalf()`

but I don't know the upper bound `b` which I would find from finding the intersection of both functions using:

```
eq3 = Eq(diff(f),diff(g))
solve(eq3)[0]
```

**Comment by asmeurer** [comment]
If you're just looking for a number, you are better off using a numeric solver like `nsolve`. It looks like that is the case since you are going to call `evalf()` at the end. 

`solve()` is for cases where you want a closed-form analytic solution. For more complex equations, the solution may exist but not be expressible in a nice form (which is likely the case for this equation).

**Comment by NSC9** [comment]
> If you're just looking for a number, you are better off using a numeric solver like `nsolve`. It looks like that is the case since you are going to call `evalf()` at the end.
> 
> `solve()` is for cases where you want a closed-form analytic solution. For more complex equations, the solution may exist but not be expressible in a nice form (which is likely the case for this equation).

I tried `b = nsolve(eq3,2)` and got `2.08710845301751`. This looks kind of close to the actual intersecting x-value. 

Then `Integral(diff(f)-diff(g),(x,0,b)).evalf()` outputted '3.41721925173319'.

This should be the solution for what I was wanting, assuming I used nsolve correctly. Thank you eagleoflqj and asmeurer.
