### ISSUE TITLE
julia_code generates invalid Julia code

### ISSUE THREAD

**Issue by moble** [sympy/sympy#23667]
The [documentation for `julia_code`](https://docs.sympy.org/latest/modules/printing.html?highlight=julia_code#sympy.printing.julia.julia_code) shows a pretty simple example of generating Julia code:
```python
>>> julia_code(x**2*y*A**3)
'(x.^2.*y)*A^3'
```
Unfortunately, that snippet will produce an error if you actually try to use it in Julia:
```
syntax: invalid syntax "2.*"; add space(s) to clarify
```
The problem is an unfortunate ambiguity in Julia's syntax (which will not be changed).  The reason is that `2.` is one thing (the floating-point number 2), and `.*` is another thing (broadcasting — aka Hadamard — multiplication), and julia can't tell which one you mean, so it results in an error.

In this case, the correct code needs at least one extra space, between the `2` and the `.*`:
```julia
(x.^2 .*y)*A^3
```
I don't know if it's worth looking for just this case of a literal integer followed by a `.`, but a simple and robust alternative would be to emit code that is *closer* to most code styles anyway, and just put spaces around binary operators by default, like this:
```julia
(x .^ 2 .* y) * A ^ 3
```
Of course, most code styles also make an exception for `^`, and suggest that no spaces need to be used — but leave the door open for using them.  But here, it's much safer to include them, in case you have an expression like `2.^x`, which would result in a similar error.

**Comment by bjodah** [comment]
Would adding an extra parenthesis also work? In that case we can simply adjust the operator precedence table for the Julia printer to have it emit parenthesis for e.g. all binary operators.  I wonder if this is a problem in the Octave printer too?

**Comment by moble** [comment]
From the Julia side, parentheses everywhere would technically be acceptable, as long as the precedence trick also involved plain numbers, so that `2.^x` and `x.^2` would become `(2).^(x)` and `(x).^(2)`.  But I think this would really harm readability.  On the other hand, spaces everywhere would mostly improve readability.  And as you say, extra spaces never hurt — at least in terms of Julia's ability to parse an expression.  So I agree that spaces are probably better.

**Comment by asmeurer** [comment]
We should do whichever one is most commonly used in Julia code. Is there a commonly accepted Julia code style? 

Making code more readable is not a top priority for the code printers, but whenever it can be done without too much work, it should try to produce readable output.

**Comment by cocolato** [comment]
In the process of fixing the issue https://github.com/sympy/sympy/pull/23729, I found another problem.
The default printer will use the vectorized "dot" operators to print julia code when the arg is not a symbol.
https://github.com/sympy/sympy/blob/9eb90912999188bd84292028b569948da5b0be67/sympy/printing/julia.py#L178-L179
But this vectorization operation performs poorly when applied to non-vector objects.
The python code:
```
>>> x = Symbol("x")
>>> julia_code(x**10)
'x.^10'
```

The julia benchmark res:
```
julia> using BenchmarkTools

julia> x = 10
10

julia> @btime x ^ 10
  22.478 ns (1 allocation: 16 bytes)
10000000000

julia> @btime x .^ 10
  493.969 ns (5 allocations: 96 bytes)
10000000000
```

**Comment by cocolato** [comment]
I think the application scenario for julia_code() should be to print the correct Julia Code without considering all possible variable cases. Specific variable types should be made compatible by the user, for example:
```
julia> x = [1 2 3]
1×3 Matrix{Int64}:
 1  2  3

julia> expr = Meta.parse("x+1")
:(x + 1)

julia> import Base.+

julia> (+)(vec::Matrix{Int64}, n::Int64) = vec .+ n
+ (generic function with 209 methods)

julia> eval(expr)
1×3 Matrix{Int64}:
 2  3  4
```

**Comment by moble** [comment]
@asmeurer

> Is there a commonly accepted Julia code style?

[BlueStyle](https://github.com/invenia/BlueStyle) is the most common one I've seen; it's based on PEP8, and generally similar.  The only other one I know of is [SciMLStyle](https://github.com/SciML/SciMLStyle), which has precisely the same recommendation for binary operators.  Both of them say this:

> Surround most binary operators with a single space on either side [...]. Binary operators that may be excluded from this guideline include: the [range operator](https://docs.julialang.org/en/v1/base/math/#Base.::) (`:`), [rational operator](https://docs.julialang.org/en/v1/base/math/#Base.://) (`//`), [exponentiation operator](https://docs.julialang.org/en/v1/base/math/#Base.:^-Tuple{Number,Number}) (`^`), [optional arguments/keywords](https://docs.julialang.org/en/v1/manual/functions/#Optional-Arguments-1) (e.g. `f(x=1; y=2)`).

So adding spaces is definitely recommended over parentheses, and is much more common in my experience.

**Comment by cocolato** [comment]
> @cocolato This is one of the classic problems in julia, that even old pros fall into constantly: when using `@btime`, you have to remember to interpolate variables, by putting `$` in front of them:
> 
> ```julia
> julia> using BenchmarkTools
> 
> julia> x = 10
> 10
> 
> julia> @btime $x ^ 10
>   5.366 ns (0 allocations: 0 bytes)
> 10000000000
> 
> julia> @btime $x .^ 10
>   5.370 ns (0 allocations: 0 bytes)
> 10000000000
> ```
> 
> In fact, you can look at the machine-level code that gets created, and see that it's identical:
> 
> ```julia
> julia> f1(x) = x ^ 10;
> julia> f2(x) = x .^ 10;
> 
> julia> @code_native debuginfo=:none f1(x)
> 	.section	__TEXT,__text,regular,pure_instructions
> 	subq	$8, %rsp
> 	movabsq	$power_by_squaring, %rax
> 	movl	$10, %esi
> 	callq	*%rax
> 	popq	%rcx
> 	retq
> 	nopw	(%rax,%rax)
> 
> julia> @code_native debuginfo=:none f2(x)
> 	.section	__TEXT,__text,regular,pure_instructions
> 	subq	$8, %rsp
> 	movabsq	$power_by_squaring, %rax
> 	movl	$10, %esi
> 	callq	*%rax
> 	popq	%rcx
> 	retq
> 	nopw	(%rax,%rax)
> ```

I see, thank you for your explanation!
