### ISSUE TITLE
Image not readable in dark theme

### ISSUE THREAD

**Issue by TJStienstra** [sympy/sympy#23706]
While working on #23705 I noticed that some images are not readable in the new dark theme. An example is [the rolling disc](https://docs.sympy.org/dev/modules/physics/mechanics/examples/rollingdisc_example.html). This should be fixable by adding something like the following to the svg:
```svg
  <style>
        path { fill: black; }
        @media (prefers-color-scheme: dark) {
            path { fill: white; }
        }
  </style>
```
But somehow this does not seem to work. Any suggestions how to fix this?

**Comment by TJStienstra** [comment]
I have also played around a bit with `currentColor`, but did not get that to work either.

**Comment by asmeurer** [comment]
Didn't see this issue when I opened https://github.com/sympy/sympy/issues/24695. I am closing it in favor of that issue. I'll comment on that issue some ideas.
