### ISSUE TITLE
Cannot specify ODE initial conditions as just f(0)

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#23702]
Suppose you want to solve an ODE and solve for the constants in terms of the unevaluated value of a function at a given point. For example, solve `f(x).diff(x) - f(x)` and solve the constants at `f(0)`. I would expect something like this to work

```py
>>> dsolve(f(x).diff(x) - f(x), f(x), ics={f(0): f(0)})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/aaronmeurer/Documents/Python/sympy/sympy/./sympy/solvers/ode/ode.py", line 605, in dsolve
    hints = _desolve(eq, func=func,
  File "/Users/aaronmeurer/Documents/Python/sympy/sympy/./sympy/solvers/deutils.py", line 209, in _desolve
    hints = classifier(eq, func, dict=True, ics=ics, xi=xi, eta=eta,
  File "/Users/aaronmeurer/Documents/Python/sympy/sympy/./sympy/solvers/ode/ode.py", line 1013, in classify_ode
    raise ValueError("Enter valid boundary conditions for Function")
ValueError: Enter valid boundary conditions for Function
```

I would have expected this to give `Eq(f(x), f(0)*exp(x))`.

To do this, you have to create a separate symbol:

```py
>>> f0 = symbols('f0')
>>> dsolve(f(x).diff(x) - f(x), f(x), ics={f(0): f0})
Eq(f(x), f0*exp(x))
```

**Comment by nasser1** [comment]
I am not sure it is valid to say initial conditions are   f(0)=f(0). This is rejected in Mathematica also as it is replaced by `True` and is no longer an equation

```
In[4]:= DSolve[{f'[x] == f[x], f[0] == f[0]}, f[x], x]
Out[4]= DSolve[{Derivative[1][f][x] == f[x], True}, f[x], x]

DSolve::deqn: Equation or list of equations expected instead of True in the first argument {(f^\[Prime])[x]==f[x],True}.
```

And in Maple, it ignores the whole initial conditions

```
dsolve([diff(f(x),x)=f(x), f(0)=f(0)])
                       f(x) = _C1 exp(x)

```
Which is the same result one gets from `dsolve([diff(f(x),x)=f(x))`

**Comment by asmeurer** [comment]
It seems the only reason this doesn't work is that there's an explicit check that the value doesn't contain `f`, but I don't see any reason why this shouldn't work, though. Maybe a more reasonable check would be to ensure the value doesn't contain `x`.

**Comment by asmeurer** [comment]
Fix at https://github.com/sympy/sympy/pull/23708

**Comment by asmeurer** [comment]
> That's perfectly valid, although it I wonder if it shouldn't raise an error if it can't solve for all the constants.

It's probably better not to. There are surely legitimate reasons to only give partial initial conditions. And anyways, that's already supported.

**Comment by asmeurer** [comment]
> I don't see why it's invalid. Ideally there would be a way to get the output in terms of f(0) and f'(0) etc without needing to explicitly say f(0): f(0) though.

I don't see a need for a separate syntax. f(0): f(0) is verbose, but it makes sense if you read `ics={f(a): y}` as "substitute x with a then replace f(a) with y". In fact that *is* the logic. The only thing I had to change was removing the check that prevented it from working.
