### ISSUE TITLE
review use of `mul.prod`

### ISSUE THREAD

**Issue by smichr** [sympy/sympy#23711]
from discussion in #23698 

For 1024 random symbols `Mul(*syms)` takes 0.025 seconds while `mul.prod` takes 22.3 s. 

There is about a 10% slowdown for the int case if we do this:
```python
def prod(f, start=1):
    """return an int if all elements are ints else a SymPy expression"""
    from sympy.utilities.iterables import sift
    n, s = sift(f, lambda x: type(x) is int, binary=True)
    if start != 1:
        if type(start) is int:
            n.append(start)
	else:
	    s.append(start)
    if n:
        from math import prod as p
        return p(n) if not s else p(n)*Mul(*s)
    return Mul(*s)
```
But it seems better to me to just update internal uses of prod on ints to use `math.prod` and use Mul(*factors) or (or perhaps a rewrite of mul.prod as sprod to handle non-ints) for others and deprecate `mul.prod`.

Although it should be possible to use `Mul(*factors)` there are some irritating problems as noted [here](https://github.com/sympy/sympy/pull/23679#pullrequestreview-1024222649) that did not allow this in some places in `holonomic.py`.

**Comment by oscargus** [comment]
With #23714 all internal use of `mul.prod` is removed. There it is most often replaced by `math.prod`, although there may be cases where `Mul(* ...)` is better.
