### ISSUE TITLE
[Bug] LaTeX printing with significant figures incorrect for certain numbers

### ISSUE THREAD

**Issue by MilesCranmer** [sympy/sympy#23719]
I think there is a bug in the precision of constants when converting sympy floats into LaTeX. When you are controlling precision before the decimal point, `sympy.latex` seems to have one additional decimal of precision than expected. 

Here is an MWE:
```python
>>> sympy.latex(sympy.Float("12.34", 4))  # Correct
'12.34'

>>> sympy.latex(sympy.Float("12.34", 3))  # Correct
'12.3'

>>> sympy.latex(sympy.Float("12.34", 2))  # Incorrect, this has 3 significant figures
'12.0'

>>> sympy.latex(sympy.Float("12.34", 1))  # Incorrect, this has 2 significant figures
'1.0 \\cdot 10^{1}'
```
According to the rules of significant figures (https://en.wikipedia.org/wiki/Significant_figures), any number appearing after the decimal point, when you have nonzeros before it, is added to the number of significant figures. Therefore, these last two examples have one more significant figure than expected.

e.g., if someone sees `12.3` and `12.0`, one would normally assume they both have 3 significant figures.

The expected behavior according to rules of significant figures should be:
```python
>>> sympy.latex(sympy.Float("12.34", 2))
'12'
# (or '1.2 \cdot 10^{1}')

>>> sympy.latex(sympy.Float("12.34", 1))
'1 \\cdot 10^{1}'
```

This only occurs when you are next to a decimal point, then the definition of significant figures seems to change when printing numbers in LaTeX.

Thanks,
Miles

**Comment by eagleoflqj** [comment]
```py
>>> from sympy import *
>>> latex(Float('12.34', 2), full_prec=True)
'12.'
```
Does it fit your requirement?

**Comment by MilesCranmer** [comment]
Ah, yes, thank you! I didn't know that flag would solve it. Closing this issue...
