### ISSUE TITLE
IndexedBase non-commutivity fails

### ISSUE THREAD

**Issue by chrisculver** [sympy/sympy#23721]
Hi there, 

I believe I've found a bug relating to the IndexedBase class, where it doesn't seem to respect non-commutivity of objects.  If I have two non-commuting IndexedBase objects `t` and `u`, I would expect that `t[0]*u[0]+u[0]*t[0]!=2*t[0]*u[0]`.  The below code highlights the issue, showing that all the objects have `commutivity=False`, yet the addition of `t[0]*u[0]` with `u[0]*t[0]` simplified to `2t[0]u[0]`

    import sympy as sp                                                                                  
                                                                                                    
    t=sp.IndexedBase('t',commutative=False)                                                             
    u=sp.IndexedBase('u',commutative=False)                                                             
                                                                                                      
    print('t commutativity is {}'.format(t._assumptions['commutative']))                                    
    print('t[0] commutativity is {}'.format(t[0]._assumptions['commutative']))                           
    print('u commutativity is {}'.format(u._assumptions['commutative']))                                    
    print('u[0] commutativity is {}'.format(u[0]._assumptions['commutative']))                          
                                                                                                    
    print(t[0]*u[0]+u[0]*t[0])    
    
The output I get in sympy version 1.10.1 is 

    t commutativity is False
    t[0] commutativity is False
    u commutativity is False
    u[0] commutativity is False
    2*t[0]*u[0]

**Comment by ThePauliPrinciple** [comment]
Problem is already here:
```python
>>> print(u[0]*t[0])
t[0]*u[0]
```

**Comment by oscarbenjamin** [comment]
Seems to be an assumptions problem:
```python
In [4]: u[0]._assumptions['commutative']
Out[4]: False

In [5]: u[0].is_commutative
Out[5]: True
```
Looks like the fix is
```diff
diff --git a/sympy/tensor/indexed.py b/sympy/tensor/indexed.py
index 8119a2a..9c9b6f3 100644
--- a/sympy/tensor/indexed.py
+++ b/sympy/tensor/indexed.py
@@ -139,7 +139,6 @@ class Indexed(Expr):
     True
 
     """
-    is_commutative = True
     is_Indexed = True
     is_symbol = True
     is_Atom = True
```
I'm not sure if there's any particular reason why `Indexed` sets commutative to True.

Probably the assumptions system should detect a case like this where `is_commutative` contradicts `_assumptions['commutative']` and cause an error somewhere.

**Comment by comp-phys-marc** [comment]
Instead of making a change to the source of the class one may also set this property dynamically: `Indexed.is_commutative = False`.

**Comment by oscarbenjamin** [comment]
I've already shown how to fix this so marking as easy to fix.

**Comment by bcallen95** [comment]
Sorry for reviving this, but the original issue still persists!

**Comment by bcallen95** [comment]
Thanks @oscarbenjamin for pointing me in the right direction! Installation via `pip install sympy` in Google Colab results in the same output as shown in the original post. Changing the command to `pip install git+https://github.com/sympy/sympy` fixes the issue! I noticed that the `is_commutative` attribute is still true, though.

**Comment by oscarbenjamin** [comment]
> I noticed that the `is_commutative` attribute is still true, though.

Yes, I see that:
```python
In [4]: t[0].is_commutative
Out[4]: False

In [5]: u[0].is_commutative
Out[5]: False

In [6]: t.is_commutative
Out[6]: True

In [7]: u.is_commutative
Out[7]: True
```
Not sure where that is coming from.

**Comment by bcallen95** [comment]
Looks like in sympy-master/sympy/tensor/indexed.py Lines 437-438 it is explicitly set as true instead of setting the attribute based on the kwarg.

**Comment by oscarbenjamin** [comment]
Actually it looks like the same problem:
https://github.com/sympy/sympy/blob/0582397407417790e8bcae9a4b882a797d2437ce/sympy/tensor/indexed.py#L428

**Comment by shishir-11** [comment]
Mathematically speaking , when talking about commutativity , we need to have a Group with defined operation and elements and it is the property of the Group . Why are we making an element to be commutative or non commutative here ?

**Comment by ThePauliPrinciple** [comment]
You could understand an "indexed" to be all sorts of things, not neccesarily an element of a tensor. There doesn't have to be a geometric interpretation to that index, it could be an index into some series too. For example, I abuse indexed all the time to write relations like x[i] = x[i-1] + x[i-2], or use them e.g. to indicate the layer in a neural network. It's not exactly what it's meant for, but I don't think there's really an alternative in sympy that you could use for the code printers.

I do believe that the tensor module in sympy (which uses indexed under the hood) has an implementation of the Group based commutativity that you are describing.

**Comment by shishir-11** [comment]
I made the changes asked in my PR, kindly recommend amy changes and tests we need to add , thanks.
