### ISSUE TITLE
TypeError: unsupported operand type(s) for @: 'Symbol' and 'Symbol'

### ISSUE THREAD

**Issue by GGGGGGGG5566** [sympy/sympy#23737]
Hi sympy,

I'm quite new to this library. Currently, I'm trying to parse a string "abc@mmw * 2 * 5" with the following code

```python=
parse_expr("abc@mmw * 2 * 5")
```

The result I epected to get is "10 * abc@mmw", where "abc@mmw" is actually a function (name).    
However, it seems that the parser treats @ as a Symbol. 

The current workaround for this issue I came up with is replacing all @ with _ before parsing. 
I am wondering is there any better way to deal with this kind of issue? Thanks!

**Comment by eagleoflqj** [comment]
I think having `@` in function name is too rare to be supported in SymPy parser. Your workaround is fine.
