### ISSUE TITLE
Optional dependency tests failing with Aesara

### ISSUE THREAD

**Issue by oscarbenjamin** [sympy/sympy#23733]
The optional dependency tests are now failing in the Aesara tests but only on pypy and CPython 3.11:
https://github.com/sympy/sympy/runs/7210465165?check_suite_focus=true

The test that fails is this one:
https://github.com/sympy/sympy/blob/997749da1838628eaeb077c7ab32da6666912e13/sympy/printing/tests/test_aesaracode.py#L608-L614

It's only the most recent merge commit on the master branch that shows this failure but it also shows up in all PRs now. Something must have changed in between 14 and 22 hrs ago and it looks like it's the release of Aesara 2.7.5 which was 18 hrs ago:
https://pypi.org/project/aesara/#history

CC @brandonwillard

**Comment by brandonwillard** [comment]
We just recently added a rewrite that removes unnecessary conjugate `Op`s applied to floats, so my guess is that the expected/reference graph has one such sub-graph that isn't in canonical form.

**Comment by oscarbenjamin** [comment]
I think the reason it fails only on pypy and 3.11 is because we don't install pymc there and pymc currently pins `aesara==2.7.4` so it's only the pypy and 3.11 jobs where Aesara 2.7.5 gets installed.

Actually I can reproduce this locally with CPython 3.8 and Aesara 2.7.5:
```python
In [1]: from sympy.printing.aesaracode import aesara_code
WARNING (aesara.tensor.blas): Using NumPy C-API based implementation for BLAS functions.

In [2]: from sympy.printing.tests.test_aesaracode import theq

In [3]:      xt, yt = aesara_code(x, dtypes={x:'complex128'}), aesara_code(y, dtypes={y: 'complex128'
   ...: })
   ...:      from sympy.functions.elementary.complexes import conjugate
   ...:      from aesara.tensor import as_tensor_variable as atv
   ...:      from aesara.tensor import complex as cplx
   ...:      assert theq(aesara_code(y*conjugate(x)), yt*(xt.conj()))
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-3-5104cf8662e7> in <module>
      3 from aesara.tensor import as_tensor_variable as atv
      4 from aesara.tensor import complex as cplx
----> 5 assert theq(aesara_code(y*conjugate(x)), yt*(xt.conj()))

AssertionError: 

In [4]: aesara_code(y*conjugate(x))
Out[4]: Elemwise{mul,no_inplace}.0

In [5]: yt*(xt.conj())
Out[5]: Elemwise{mul,no_inplace}.0

In [6]: theq(aesara_code(y*conjugate(x)), yt*(xt.conj()))
Out[6]: False
```
The `theq` function is supposed to compare two Aesara objects:
https://github.com/sympy/sympy/blob/997749da1838628eaeb077c7ab32da6666912e13/sympy/printing/tests/test_aesaracode.py#L97-L98

**Comment by oscarbenjamin** [comment]
> my guess is that the expected/reference graph has one such sub-graph that isn't in canonical form.

How would you check that from the expressions generated above?

**Comment by brandonwillard** [comment]
Yeah, that's the problem:
```python
import aesara

aesara.dprint(aesara_code(y*conjugate(x)), print_type=True)
# Elemwise{mul,no_inplace} [id A] <TensorType(float64, ())>
# |y [id B] <TensorType(float64, ())>
# |x [id C] <TensorType(float64, ())>

**Comment by brandonwillard** [comment]
It looks like the test needs new test variables with `Symbol.is_complex` set and accounted for during conversion to Aesara.

**Comment by oscarbenjamin** [comment]
Oh I see:
```python
In [7]: import aesara

In [8]: aesara.dprint(aesara_code(y*conjugate(x)), print_type=True)
Elemwise{mul,no_inplace} [id A] <TensorType(float64, ())>
 |y [id B] <TensorType(float64, ())>
 |x [id C] <TensorType(float64, ())>
Out[8]: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>

In [9]: aesara.dprint(yt*(xt.conj()), print_type=True)
Elemwise{mul,no_inplace} [id A] <TensorType(complex128, ())>
 |y [id B] <TensorType(complex128, ())>
 |Elemwise{conj,no_inplace} [id C] <TensorType(complex128, ())>
   |x [id D] <TensorType(complex128, ())>
Out[9]: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>
```

**Comment by oscarbenjamin** [comment]
What does Aesara do with `is_complex`? The symbols `x` and `y` here have not been given any assumptions which usually means they sort of default to complex but they don't have `is_complex -> True` because they can also represent things like infinity etc which doesn't count as complex in SymPy.

**Comment by brandonwillard** [comment]
Sorry, I was just trying to reference any indicator that might tell the conversion process that the Aesara type should be complex.

**Comment by brandonwillard** [comment]
> Maybe the test should be changed to use that...

Yes, that appears to the be most expedient fix.

**Comment by oscarbenjamin** [comment]
I think that's the right fix. The test is already setting `dtypes` for some of the generated expressions but not all of them. I've opened #23734 so that both things being tested for equality are generated with the same dtypes.

**Comment by oscarbenjamin** [comment]
Thanks @brandonwillard
