### ISSUE TITLE
To have stated symbols as variable in sympy.

### ISSUE THREAD

**Issue by Harpreet-30** [sympy/sympy#23744]
I m trying to generate a c file using codegen function. I have added all the expression in one matrix to give codegen. But I want it to take only some specific symbols as variable others as constant. How to do so?

**Comment by oscarbenjamin** [comment]
I'm closing this since GitHub issues are for discussing improvements to SymPy.

Please use the mailing list or StackOverflow to ask for help with using SymPy. (You will need to provide more information than you have done here.)
