### ISSUE TITLE
Use of trigsimp to find tangent addition property

### ISSUE THREAD

**Issue by Manon-Oreins** [sympy/sympy#23763]
I was trying to naviguate between the two following expressions using the function trigsimp of sympy:

$$
\tan{(x+y)} 
$$

$$
\frac{\tan{x} + \tan{y}}{1 - \tan{x}\tan{y}}
$$ 

When I use trigsimp on the second one, no simplification occurred but when I use expand_trig on the first one then it becomes like the second one. The problem is, I can't go back from the second expression to the first one using trigsimp. Is it a bug ?

**Comment by smichr** [comment]
Fu algorithms alone are able to do this. `trigsimp`, like `simplify` is a generally-good-enough algorithm; targetted routines can sometimes do better.
```python
>>> eq = tan(x + y)
>>> eq == fu(eq.expand(trig=True))
True
```
