### ISSUE TITLE
Cannot lazy load from sympy submodules

### ISSUE THREAD

**Issue by neutrinoceros** [sympy/sympy#23787]
Importing anything from `sympy.utilities` cascades into importing the whole `sympy` package, which seems to break lazy loading as is otherwise well implemented in the rest of the package

```
python -X importtime -c "import sympy.utilities" 2> tuna.log && tuna tuna.log
```
<img width="1260" alt="Screenshot 2022-07-16 at 20 00 55" src="https://user-images.githubusercontent.com/14075922/179366827-0254d14d-df6f-4098-9c7b-7051334e96c9.png">

related to https://github.com/sympy/sympy/issues/14854

**Comment by neutrinoceros** [comment]
ah, I just figured out that the problem is not specifically with `sympy.utilities`, it just happened to be the first module to trigger this import cascade in the specific case I was interested in, so any module being imported after than *looked* free, but it seems that lazy loading is in fact not implemented in other parts of the code either.

**Comment by asmeurer** [comment]
Lazy loading isn't really implemented for any part of SymPy, because so many modules depend on one another. We might be able to make specific parts of utilities that don't actually use the rest of SymPy loadable lazily, if it's something that would be useful for people.

**Comment by asmeurer** [comment]
I guess your use case https://github.com/yt-project/unyt/pull/253 is trying to improve the general import time. I don't know if we can get anywhere there with lazy importing, because like I said, the submodules all typically depend on one another. I do think there are things we can do to improve the import time of sympy generally.

**Comment by neutrinoceros** [comment]
I opened this with a light heart thinking I could probably resolve this myself in under an hour, now it doesn't sound like a low hanging fruit at all :/

> I do think there are things we can do to improve the import time of sympy generally.

any specific pointers ?

**Comment by asmeurer** [comment]
I don't know if there's low-hanging fruit with that anymore either, but a good place to start would be to try to profile the import and see if it is doing anything at import time that can be delayed. It might also be possible that there are some files that only have helpers and don't have any top-level names which can be removed from being import with the main `import sympy`.

**Comment by neutrinoceros** [comment]
So I think this is now a duplicate of https://github.com/sympy/sympy/issues/14854, might as well close it. Thanks again for your replies !
