### ISSUE TITLE
How to collect additive terms for matrix?

### ISSUE THREAD

**Issue by helloliver** [sympy/sympy#23796]
There is a function named `collect` which can collect additive terms of an expression. For example:

```python
>>> d = collect(a*x**2 + b*x**2 + a*x - b*x + c, x, evaluate=False)
>>> d[x**2]
a + b
>>> d[x]
a - b
>>> d[S.One]
c
```

But I want to collect additive terms for matrix, like:

$$
\left[\begin{matrix}a^{2} + b + c^{2} + 1\\a + b^{2} + c\end{matrix}\right]
=
\left[\begin{matrix} 1 & 0 & 1 \\ 0 & 1 & 0 \end{matrix}\right]
\left[\begin{matrix} a^2 \\ b^2 \\ c^2 \end{matrix}\right]
+
\left[\begin{matrix} 0 & 1 & 0 \\ 1 & 0 & 1 \end{matrix}\right]
\left[\begin{matrix} a \\ b \\ c \end{matrix}\right]
+
\left[\begin{matrix} 1 \\ 0 \end{matrix}\right]
$$

Is there any good idea to do this?

**Comment by oscarbenjamin** [comment]
GitHub issues are not for getting help with using SymPy. Please use the mailing list or StackOverflow:
https://groups.google.com/g/sympy
