### ISSUE TITLE
Unexpected derivative result with many variables.

### ISSUE THREAD

**Issue by KelSolaar** [sympy/sympy#23803]
Hello,

I'm trying to compute the derivative of the following function with Sympy:

$$g\left(x\right)=400\cdot(f\left(x\right)/(f\left(x\right)+27.13))+0.1$$

where

$$f\left(x\right)=(x\cdot R/100)^{0.42}$$

The [Desmos plot](https://www.desmos.com/calculator/3n4imuqnzh) is as follows:

![image](https://user-images.githubusercontent.com/99779/179731902-eaad5b1a-05ee-4791-a394-9fb147e7883d.png)

and matches the derivative Mathematica computes for :

$$\frac{2.48575\times 10^6 (F R)^{91/25}-13243.7 (F R)^{203/50}}{(F R)^{211/50} \left((F R)^{21/50}+187.694\right)^3}$$

![image](https://user-images.githubusercontent.com/99779/179732148-f913a533-5aee-446f-8c1e-d0edbee6f9ef.png)

However, Sympy produces a different derivative:

$$\frac{10^{\frac{4}{25}} \left(\frac{25967381832 \left(F_{L} R_{c}\right)^{\frac{21}{50}}}{5} - 19142928 \cdot 10^{\frac{4}{25}} \left(F_{L} R_{c}\right)^{\frac{21}{25}}\right)}{F_{L} R_{c} \left(1000 \cdot 10^{\frac{12}{25}} \left(F_{L} R_{c}\right)^{\frac{63}{50}} + 220811070 \cdot 10^{\frac{4}{25}} \left(F_{L} R_{c}\right)^{\frac{21}{50}} + 813900 \cdot 10^{\frac{8}{25}} \left(F_{L} R_{c}\right)^{\frac{21}{25}} + 19968681097\right)}$$

![image](https://user-images.githubusercontent.com/99779/179732502-fb0f9684-71dd-4ea2-b2e9-2f93749a57e6.png)

If I compute the derivative while pinning/hardcoding R to 0.8, it then matches the Desmos and Mathematica output.

The code I used is as follows:

```python
from sympy import Rational, lambdify, symbols, simplify

F, R = symbols("F_L, R_c")

f = (F * R / 100) ** Rational(21, 50)
g = 400 * (f / (f + Rational(2713, 100))) + Rational(1, 10)

f_g = lambdify([F, R], g)
f_d_g = lambdify([F, R], g.diff(F, R))

simplify(g.diff(F, R))
```

Cheers,

Thomas

**Comment by oscarbenjamin** [comment]
This is what you are asking SymPy to compute:
```python
In [17]: Derivative(g, F, R)
Out[17]: 
         ⎛                     21       ⎞
         ⎜                     ──       ⎟
     2   ⎜       4/25          50       ⎟
    ∂    ⎜  40⋅10    ⋅(F_L⋅R_c)       1 ⎟
─────────⎜───────────────────────── + ──⎟
∂R_c ∂F_L⎜                21          10⎟
         ⎜                ──            ⎟
         ⎜  4/25          50            ⎟
         ⎜10    ⋅(F_L⋅R_c)     2713     ⎟
         ⎜────────────────── + ────     ⎟
         ⎝        10           100      ⎠
```
Note that it is a double derivative wrt F and R.

**Comment by KelSolaar** [comment]
Yes but is it expected that the output is different from Mathematica?

**Comment by oscarbenjamin** [comment]
If you don't ask the same question why would you expect the same answer?

**Comment by oscarbenjamin** [comment]
In the desmos output you are just asking for `g'(x)` so it should be a single derivative wrt one of your variables like `g.diff(F)`.

**Comment by KelSolaar** [comment]
Yes, and I realised that I did the same while plotting with Mathematica! However, if I try to evaluate the computed double-derivative in both I do not get the same values which prompted my initial question.

**Comment by oscarbenjamin** [comment]
Your two different lines are just the difference between these:
```python
In [35]: e1 = g.diff(F, R).subs(R, 0.8)

In [36]: e2 = g.diff(F).subs(R, 0.8)

In [37]: plot(e1, e2, (F, 0, 4), ylim=(0, 4))
Out[37]: <sympy.plotting.plot.Plot at 0x7f1fe2269ca0>
```
They are not the same derivatives.

**Comment by KelSolaar** [comment]
Hi Oscar,

Thanks again for your time.

> Above you said that Desmos matches Mathematica but that can't be true because you aren't using them to compute the same thing.

They do but only because I plotted the derivative whilst using 0.8 for `R` in both cases, which I only realised after your post. Let's forget the plots as they made the situation confusing.

In Mathematica, as per my image and [according to the docs](https://wolfram.com/xid/0p2n-r5c), I computed the derivative with respect to `F` and `R`:

```text
f[F_, R_] := (F * R / 100)^0.42
g[F_, R_] := 400*(f[F, R]/(f[F, R] + 27.13)) + 0.1

Simplify[D[g[F, R], F, R]]

Rationalize[Simplify[D[g[F, R], F, R]]]
```

or alternatively:

```text
Rationalize[
 Simplify[
  D[400*(((F * R / 100)^0.42)/(((F * R / 100)^0.42) + 27.13)) + 0.1, 
   F, R]]]
```

This produces the following derivative:

$$\frac{2.48575\times 10^6 (F R)^{91/25}-13243.7 (F R)^{203/50}}{(F R)^{211/50} \left((F R)^{21/50}+187.694\right)^3}$$

Sympy, for what I think is the same query, yields:

```python
from sympy import Rational, lambdify, symbols, simplify

F, R = symbols("F_L, R_c")

f = (F * R / 100) ** Rational(21, 50)
g = 400 * (f / (f + Rational(2713, 100))) + Rational(1, 10)

simplify(g.diff(F, R))
```

$$\frac{10^{\frac{4}{25}} \left(\frac{25967381832 \left(F_{L} R_{c}\right)^{\frac{21}{50}}}{5} - 19142928 \cdot 10^{\frac{4}{25}} \left(F_{L} R_{c}\right)^{\frac{21}{25}}\right)}{F_{L} R_{c} \left(1000 \cdot 10^{\frac{12}{25}} \left(F_{L} R_{c}\right)^{\frac{63}{50}} + 220811070 \cdot 10^{\frac{4}{25}} \left(F_{L} R_{c}\right)^{\frac{21}{50}} + 813900 \cdot 10^{\frac{8}{25}} \left(F_{L} R_{c}\right)^{\frac{21}{25}} + 19968681097\right)}$$

Once evaluated numerically, the two functions produce different results:

Mathematica: `g[0.5, 0.5]` --> `1.28701`
Sympy: `f_d_g(0.5, 0.5)` --> `0.8301124813014463` where `f_d_g = lambdify([F, R], g.diff(F, R))`

This result was unexpected and felt like an issue and I chose not to post on the mailing list because of that. I'm happy to do so if you prefer continuing the discussion over there. Please let me know.

Cheers,

Thomas

**Comment by oscarbenjamin** [comment]
> Mathematica: `g[0.5, 0.5]` --> `1.28701`
> Sympy: `f_d_g(0.5, 0.5)` --> `0.8301124813014463` where `f_d_g = lambdify([F, R], g.diff(F, R))`

In Mathematica you're substituting into the function but in SymPy you're substituting into its derivative. Here's the same numbers but with both computed using SymPy:
```python
In [11]: g.subs({F:0.5, R:0.5})
Out[11]: 1.28700980309999

In [12]: g.diff(R, F).subs({F:0.5, R:0.5})
Out[12]: 0.830112481301446
```

> This result was unexpected and felt like an issue and I chose not to post on the mailing list because of that.

If you think you've found a bug then this is absolutely the right place to report it. Increasingly though we're seeing GitHub issues being used as a way of getting help when it is not the right forum so I find myself needing to point that out explicitly. Starting with something like the mailing list can be better in any case though because it can help to clear up any misunderstandings before putting something on the issue tracker.

Clear numbers (like the ones you showed above) are often the best way to communicate what a potential bug is. There are lots of ways that I can verify whether the number 0.83 is the correct result for this. Here's a simple check using numerical forward difference:
```python
In [28]: F, R = symbols('F, R')

In [29]: g = 400*(((F * R / 100)**0.42)/(((F * R / 100)**0.42) + 27.13)) + 0.1

In [30]: gR = (g.subs(R, 0.5+1e-3) - g.subs(R, 0.5))/1e-3

In [31]: gRF = (gR.subs(F, 0.5+1e-3) - gR.subs(F, 0.5))/1e-3

In [32]: gRF
Out[32]: 0.829142565862639
```
That's only an approximate check but it would be good enough to confirm if the answer was way out.

**Comment by KelSolaar** [comment]
Ah! Brilliant, thank you @oscarbenjamin! I would have never figured that out. This might worth a note in the documentation highlighting the difference between both. Thanks again for the detailed explanation and the time taken.

> Starting with something like the mailing list can be better in any case though because it can help to clear up any misunderstandings before putting something on the issue tracker.

Dully noted! Maybe issue templates could help you redirect people? I made some a few months ago and found them to stir the crowd relatively well: https://github.com/colour-science/colour/issues/new/choose, OpenimageIO has some good ones: https://github.com/OpenImageIO/oiio/issues/new/choose

Have a great day!

Thomas

**Comment by oscarbenjamin** [comment]
> Maybe issue templates could help you redirect people?

Yes, I've been thinking about this. Having opened issues recently with scipy, cpython, matplotlib, etc I see that all of those use issue templates that clearly point to other places.

> This might worth a note in the documentation highlighting the difference between both.

What note should there be? To me it looks like the mistake was in your Mathematica code.

**Comment by KelSolaar** [comment]
> What note should there be? To me it looks like the mistake was in your Mathematica code.

Yes, I was stupid, been too much work lately.
