### ISSUE TITLE
How to check the expression

### ISSUE THREAD

**Issue by AntonVMakarov** [sympy/sympy#23818]
Hi, I am new to sympy, and I don't understand how to check that the expression I've created is variable "x" or some symbol:
expr = sympify("x")
How to understand that expression is "x"?
I can do it like this:
if str(expr.func) == "x"
But, what is the best practice to do such testing?
Or what if I need to understand that expression is some number (int or decimal)?

**Comment by oscarbenjamin** [comment]
Please use the mailing list for help with using SymPy:
https://groups.google.com/g/sympy
