### ISSUE TITLE
Probabilist's Hermite polynomials vs physicist's

### ISSUE THREAD

**Issue by FabricioS** [sympy/sympy#23829]
Dear Sympy community,
looking at the [docs](http://lidavidm.github.io/sympy/modules/functions/special.html?highlight=hermite#sympy.functions.special.polynomials.hermite), it is written that the function provides the probabilist's Hermite polynomials (orthogonal wrt weight $exp(-x^2/2)$ while the examples would correspond to the physicist's Hermite polynomials (orthogonal with respect to $exp(-x^2)$).

See https://en.wikipedia.org/wiki/Hermite_polynomials#Definition

**Comment by oscarbenjamin** [comment]
Yes, it seems the doc should say $e^{-x^2}$:
```python
In [19]: Matrix(5, 5, lambda i, j: integrate(hermite(i, x)*hermite(j, x)*exp(-x**2/2), (x, -oo, oo)))
    ...: 
Out[19]: 
⎡ √2⋅√π       0       2⋅√2⋅√π       0       12⋅√2⋅√π  ⎤
⎢                                                     ⎥
⎢   0      4⋅√2⋅√π       0      24⋅√2⋅√π        0     ⎥
⎢                                                     ⎥
⎢2⋅√2⋅√π      0      36⋅√2⋅√π       0       408⋅√2⋅√π ⎥
⎢                                                     ⎥
⎢   0      24⋅√2⋅√π      0      528⋅√2⋅√π       0     ⎥
⎢                                                     ⎥
⎣12⋅√2⋅√π     0      408⋅√2⋅√π      0      10896⋅√2⋅√π⎦

In [20]: Matrix(5, 5, lambda i, j: integrate(hermite(i, x)*hermite(j, x)*exp(-x**2), (x, -oo, oo)))
Out[20]: 
⎡√π   0     0      0      0   ⎤
⎢                             ⎥
⎢0   2⋅√π   0      0      0   ⎥
⎢                             ⎥
⎢0    0    8⋅√π    0      0   ⎥
⎢                             ⎥
⎢0    0     0    48⋅√π    0   ⎥
⎢                             ⎥
⎣0    0     0      0    384⋅√π⎦
```

**Comment by asmeurer** [comment]
@FabricioS how did you end up at the above docs link? This is a link to the docs that were built on someone else's fork, which are quite out of date. The actual docs are at https://docs.sympy.org/latest/modules/functions/special.html?highlight=hermite#sympy.functions.special.polynomials.hermite, which appear to be correct.

**Comment by FabricioS** [comment]
Dear Aaron,
this link is the third one showing up when searching "sympy Hermite polynomial" (on duckduckgo)...
Sorry for the noise :/
