### ISSUE TITLE
Integral(function, *symbols, **assumptions) should have an argument that breaks as soon as a miscellaneous symbols appear

### ISSUE THREAD

**Issue by NSC9** [sympy/sympy#23831]
I am using complex in the ordinary sense, not in the complex number sense. 

'Complex' and impossible integrals have exponential run times compared to non-complex solvable integrals. 

Complex Integrals include those whose Integral(f,x).doit() results in something with Ei,gamma,Piecewise,li,erf,atan,Si,Ci,hyper,fresnel,or Li

One solution might be to add an argument such as Integral(function,x, Complex = False, Impossible = False)

As soon as the compiler sees one of the symbols like Ei, Piecewise, etc... then break the process. 

Often these complex and impossible integrals crash my IDE. Also, if am integrating stuff with x**(p/q), I've noticed that if p and/or q are larger than 4,  then run times and likelihood of IDE crashes occur more often.

**Comment by oscarbenjamin** [comment]
I suggest discussing these ideas on the mailing list before opening a SymPy issue:
https://groups.google.com/g/sympy

The suggestions/issues referred to here are not clear enough to be useful as an open issue so I'm going to close this.
