### ISSUE TITLE
ccode excessively slow when using user_functions

### ISSUE THREAD

**Issue by eschnett** [sympy/sympy#23839]
I am using `ccode` with `user_functions`. This is very slow. This code

```Python
from sympy import *
expr = Symbol('a')
for i in range(0, 18):
    expr = Function('muladd')(Rational(1, 2), Symbol(f'a{i}'), expr)

expr
ccode(expr, user_functions={'muladd':'muladd'})
```
takes more than 10 seconds to run. When I increase the `18` to `20`, the time grows exponentially. In my actual application I have to wait for many minutes for `ccode` to finish.

The issue goes away when I use only built-in functions.

I am aware of https://github.com/sympy/sympy/issues/15377. The issue here seems similar. I am using SymPy 1.10.1 with Python 3.9.12, both installed via Anaconda, on macOS.

**Comment by bjodah** [comment]
Thank you for reporting this, and thanks for the reproducer, it's very helpful. I'm looking at the output of `python -m cProfile` through `python -m pstats` right now and I'm trying to figure out why this is causes an exponential runtime.

A work-around for your example in the meantime would be:
`ccode(expr, allow_unknown_functions=True)`
which does not suffer from the exponential runtime, not sure if it helps with your original problem though.

**Comment by eschnett** [comment]
Thank you for the quick fix (which I haven't tried yet), and for the pointer to `allow_unknown_functions=True` (which works for me).

**Comment by eschnett** [comment]
I spoke too soon. The `allow_unknown_functions=True` work-around does not work for me. (It doesn't properly output the arguments to `muladd`; there are e.g. terms such as `AtildeUD00**2` in the (supposed) C output.) Time to update `SymPy`.

**Comment by oscarbenjamin** [comment]
The fix is only on SymPy's master branch so you'd need to install from git.

**Comment by bjodah** [comment]
> I spoke too soon. The `allow_unknown_functions=True` work-around does not work for me. (It doesn't properly output the arguments to `muladd`; there are e.g. terms such as `AtildeUD00**2` in the (supposed) C output.) Time to update `SymPy`.

Oh, that doesn't sound right. Would you mind opening a separate issue showcasing the `**2` in the output from ccode?

**Comment by eschnett** [comment]
I am successfully using a git checkout.

I cannot reproduce the problem with `allow_unknown_functions=True`.

Thank you very much again!
