### ISSUE TITLE
solveset is wrong for radical equations in real domain

### ISSUE THREAD

**Issue by tna20141** [sympy/sympy#23856]
```
>>> solveset(sqrt(-x**2-x+8), x)
⎧  1   √33    √33   1⎫
⎨- ─ + ───, - ─── - ─⎬
⎩  2    2      2    2⎭
>>> solveset(sqrt(-x**2-x+8), x, domain=S.Reals)
∅
```
As can see, the expression has 2 real roots and is reported as such when the `domain` argument is not provided.
However when provided `domain=S.Reals` it returns an empty set.

I traced it down to these lines in `solveset.py:_invert_real`:
```
base_positive = solveset(base >= 0, symbol, S.Reals)
_inv, _set = _invert_real(base, res, symbol)
return (_inv, _set.intersect(base_positive))
```
Seems the domain of the base is determined (correctly) and then intersected with `_set` (in this case `{8}`) to yield an empty set.

**Comment by oscarbenjamin** [comment]
This is fixed on master since ca9d61958762759a091ef7fcf224802b3e851a1b from #23341:
```python
In [1]: solveset(sqrt(-x**2-x+8), x, domain=S.Reals)
Out[1]: 
⎧  1   √33    √33   1⎫
⎨- ─ + ───, - ─── - ─⎬
⎩  2    2      2    2⎭
```
