### ISSUE TITLE
solveset returns an invalid root when solving over real domain

### ISSUE THREAD

**Issue by tna20141** [sympy/sympy#23858]
```
>>> solveset((x - 2)/sqrt(x**2 - 4*x + 3/2), x, domain=S.Reals)
{2}
```
2 shouldn't be a root since it's not in the function under square root's domain (i.e. `x**2 - 4*x + 3/2` is less than 0 with `x=2`).

**Comment by oscarbenjamin** [comment]
There is more discussion about this in #23028. Feel free to continue the discussion there but I'll close this as a duplicate.

**Comment by smichr** [comment]
Note: the denominator is not negative with x=2 unless, say, the sign before 3/2 is negative. Even still,  2 is a real number that satisfies the equation. It would only be excluded as a singularity if it set the denominator to zero (which it doesn't). I am not aware of a SymPy function which requires that all functions or powers (like sqrt) must be real as well.
