### ISSUE TITLE
There is some issues with this package. see below

### ISSUE THREAD

**Issue by RajrupDasid** [sympy/sympy#23867]
![Screenshot_20220802_103843](https://user-images.githubusercontent.com/60233333/182296447-e6a8bdb9-4a0f-43e3-9ce8-777619b1bd15.png)

I was just trying to follow your documentation sir, and wrote some logical expressions 
but there is some problem with this package ,
if you look closely , there is a circular import issue 
when I tried to perform this  mathematical problem--------------------------------------------
**### f(x,y)=xy+x2+sin(2y)
# Importing Library
import sympy
#defining Symbols
x=sympy.symbols("x")
y=sympy.symbols("y")
#equation
f=x*y+x**2+sympy.sin(2*y)
#differentiate wtr x
df_dx=sympy.diff(f,x)
print("The derivative of f(x,y) wrt x is "+str(df_dx))**

it shows a circular import error for symbol , there is no such module
in fact you can clearly see this in the attached screenshots.

am i doing anything wrong here?

**Comment by oscarbenjamin** [comment]
You've probably created a file called sympy.py. That's a standard gotcha in Python.

Please use the mailing list or stackoverflow for help with using SymPy. GitHub issues are not to be used for support so I'm closing this.

**Comment by RajrupDasid** [comment]
No I have not if you look my file wasn't with that name !
And i fixed the problem all with my own , any way thanks
