### ISSUE TITLE
Using SymPy to calculate reduced density matrix

### ISSUE THREAD

**Issue by hamide89** [sympy/sympy#23860]
If this issue doesn't go along with the community's guidelines, I would like to apologize in the beginning.

I have been trying to solve a problem that needs me to take partial trace of a density matrix and find the reduced density matrix. I have been searching for days and couldn't figure out how to approach the problem. 
Any help is appreciated.

**Comment by oscarbenjamin** [comment]
Your question is fine but it should be asked on the mailing list (and more detail should be provided e.g. an example of any code that you have tried):
https://groups.google.com/g/sympy

GitHub issues are for e.g. reporting bugs or suggesting changes to SymPy so I'll close this.
