### ISSUE TITLE
Enhancement: Stochastic differential equations

### ISSUE THREAD

**Issue by jonaslandsgesell** [sympy/sympy#23863]
Is there a plan to support solving stochastic differential equations (SDE) like ${\rm d} X_t=a(X_t,t)\,{\rm d}t+b(X_t,t)\,{\rm d}W_t$.

For the mean time I found this project interesting https://github.com/cchuang2009/PySDE/blob/master/demo/sdedemo.ipynb

**Comment by oscarbenjamin** [comment]
There is no plan to support SDEs. Very little can be done with them analytically.

The stats module has some very basic support for stochastic processes:
https://docs.sympy.org/latest/modules/stats.html#stochastic-processes

**Comment by oscarbenjamin** [comment]
I'm going to close this because it isn't useful to have an open issue for a feature request without any clear specification for what would be implemented and how. It's better to discuss something like this on the mailing list:
https://groups.google.com/g/sympy
