### ISSUE TITLE
sympy/physics/secondquant: wicks() crashes when argument contains NO()

### ISSUE THREAD

**Issue by behnle** [sympy/sympy#23878]
I tried to run examples from https://nucleartalent.github.io/ManyBody2018/doc/pub/secondquant/html/secondquant-bs.html Unfortunately, sympy does not behave as it probably used to do when this example was created. The following simple input leads to a crash:
```
>>> from sympy import *
>>> from sympy.physics.secondquant import *
>>> p,q,r,s=symbols('p q r s', dummy=True)
>>> pqsr=Fd(p)*Fd(q)*F(s)*F(r)
>>> n_pqsr=NO(pqsr)
>>> wicks(n_pqsr)

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/site-packages/sympy/physics/secondquant.py", line 2917, in wicks
    e = e.doit(wicks=True)
  File "/usr/local/lib/python3.9/site-packages/sympy/core/operations.py", line 432, in doit
    terms = [term.doit(**hints) for term in self.args]
  File "/usr/local/lib/python3.9/site-packages/sympy/core/operations.py", line 432, in <listcomp>
    terms = [term.doit(**hints) for term in self.args]
  File "/usr/local/lib/python3.9/site-packages/sympy/physics/secondquant.py", line 1984, in doit
    return self._remove_brackets()
  File "/usr/local/lib/python3.9/site-packages/sympy/physics/secondquant.py", line 2022, in _remove_brackets
    raise SubstitutionOfAmbigousOperatorFailed(self[i])
sympy.physics.secondquant.SubstitutionOfAmbigousOperatorFailed: f+(p)
```
Expected behaviour: Output should probably be zero, as the argument is claimed to be in normal order.
To some extent, i do understand the error message about ambiguos operators (it is not specified whether p/q/r/s are below or above the Fermi level, but for application of the Wick theorem this is essential).

In the quoted example (Exercise 10 on the linked page), this expression was used for a general definition of the normal-ordered Hamiltonian. The question would now be, how to define the normal-ordered Hamiltonian properly if this is an intended behavior.

Used sympy version: 1.7, but sympy live running 1.5.1 behaves the same way.

Many thanks in advance.

**Comment by oscarbenjamin** [comment]
The secondquant module is unmaintained for some time now. If you are interested in improving it then go ahead.

I confirmed that this bug goes back to at least SymPy 1.0 and is likewise still present in the current SymPy 1.10.1 release as well as master.

**Comment by behnle** [comment]
Dear @oscarbenjamin,
thank you very much for your quick response.
To be honest, i am not sure whether this is a bug or actually intended behavior.
My question rather was: if this IS intended behavior, then what it the proper way to define the normal ordered Hamiltonian.
To be honest, i don't think that i can contribute much as my Python skills are only sufficient for reading but not writing code.

**Comment by oscarbenjamin** [comment]
> i am not sure whether this is a bug or actually intended behavior.

I'm not sure anyone who would read this knows the answer to that. Whoever originally wrote this code is long gone and there is no one around now actively maintaining it.

I don't know enough about the Physics to be able to say what these functions should reasonably do or what is a good solution to your problem.

You might get a better answer by asking about this on the mailing list:
https://groups.google.com/g/sympy

**Comment by behnle** [comment]
This might actually be false alarm.
For everybody encountering the same issue with the quoted examples from https://github.com/NuclearTalent:
- add `` from sympy import Dummy``
- replace ``dummy=true`` by ``cls=Dummy``
- good luck, it worked for me, at least

As the lines of code in sympy/secondquant are older than the broken example, i wonder how this has ever worked.
I asked the owner of said repository to fix the examples.

**Comment by oscarbenjamin** [comment]
Ah, yes. It should be `cls=Dummy`. Looks like `dummy=True` worked a long time ago but was deprecated in 0.7.0 in 2011 in 8cd799cddc10662b73b437a013e99e41059ae088
