### ISSUE TITLE
Make inequalities solver page easier to understand

### ISSUE THREAD

**Issue by bertiewooster** [sympy/sympy#23880]
The [inequalities solver page](https://docs.sympy.org/dev/modules/solvers/inequalities.html) is currently confusing to visitors because there is no indication of which solver to use for the general case. Suggest adding a paragraph at the top of the page (source at `doc/src/modules/solvers/inequalities.rst`) explaining that `reduce_inequalities` is the top-level function which will call the others as needed.

Visitors are likely to find this page via a web search, so putting a note on it would help them.

**Comment by asmeurer** [comment]
A lot of these functions aren't even public (and some of the ones that are probably don't need to be). 

It's a (harder) [open issue](https://github.com/sympy/sympy/issues/23037) to separate the internal and public functions in the API docs, but maybe for now they could be split by sections on the page, similar to how they are in the [ODE docs](https://docs.sympy.org/dev/modules/solvers/ode.html).
