### ISSUE TITLE
Using nsolve on an inequality gives unexpected result

### ISSUE THREAD

**Issue by bertiewooster** [sympy/sympy#23885]
Attempting to use `nsolve` on an inequality 

```py
>>> from sympy import nsolve, Symbol
>>> x = Symbol('x')
>>> nsolve(x < 0.5, x, 1)
1.00000000000000
```

gives an unexpected result. `nsolve` isn't designed to handle inequalities, just "[a nonlinear equation system](https://docs.sympy.org/dev/modules/solvers/solvers.html?highlight=nsolve#sympy.solvers.solvers.nsolve)", so perhaps it should detect them and throw an error like "nsolve cannot accept inequalities"?

A user might think `nsolve` will solve inequalities in analogy to [`solve`](https://docs.sympy.org/dev/modules/solvers/solvers.html?highlight=nsolve#sympy.solvers.solvers.solve), which (at least currently) accepts both equations and inequalities.

**Comment by oscarbenjamin** [comment]
It seems like `mpmath` accepts this:
```python
In [2]: from mpmath import findroot

In [3]: findroot(lambda x: False, 1)
Out[3]: mpf('1.0')
```
I guess that's because False is sort of like 0 in Python.

Something like this is needed:
```diff
diff --git a/sympy/solvers/solvers.py b/sympy/solvers/solvers.py
index f67ca56..ccd1c3b 100644
--- a/sympy/solvers/solvers.py
+++ b/sympy/solvers/solvers.py
@@ -3015,6 +3015,8 @@ def nsolve(*args, dict=False, **kwargs):
         # assume it's a SymPy expression
         if isinstance(f, Eq):
             f = f.lhs - f.rhs
+        elif f.is_Relational:
+            raise TypeError
         syms = f.free_symbols
         if fargs is None:
             fargs = syms.copy().pop()
```
