### ISSUE TITLE
Note that `solveset` can solve for only one equation and symbol

### ISSUE THREAD

**Issue by bertiewooster** [sympy/sympy#23886]
> `solveset` cannot solve a system of equations (more than one equation), correct?

That's correct. The three arguments to solveset can be:

1. An expression, equation, inequality, or unequality.
2. A single symbol or expression.
3. A Set.

_Originally posted by @oscarbenjamin in https://github.com/sympy/sympy/issues/23802#issuecomment-1207382179_

However, solveset [Input API section](https://docs.sympy.org/dev/modules/solvers/solveset.html?highlight=solveset#input-api-of-solveset) includes the plural(s) for equation and variable, so simply removing each of the four `(s)` would correct this.

    Equation(s)
    The equation(s) to solve.

    Variable(s)
    The variable(s) for which the equation is to be solved.

**Comment by Shreyash-cyber** [comment]
Fixed it sir and also check for any typing error

**Comment by oscarbenjamin** [comment]
I think this was fixed in #23895
