### ISSUE TITLE
Indentation error in note's list

### ISSUE THREAD

**Issue by Arthur-Milchior** [sympy/sympy#23898]
In https://docs.sympy.org/latest/tutorial/solvers.html there is an indentation error. 

 
![2022-08-08-191807_745x624_scrot](https://user-images.githubusercontent.com/357361/183475891-d41b9c62-5172-4457-b870-1efd13d9291c.png)

I'd love to try to fix it, but https://github.com/sympy/sympy/issues/23897 means I can't compile the documentation to try fixes

**Comment by Arthur-Milchior** [comment]
![2022-08-09-025946_761x565_scrot](https://user-images.githubusercontent.com/357361/183539966-fdf83784-db89-4e98-8c96-60740202617c.png)

I tried locally. The style seems very different. So, I can both state that I can't reproduce the problem and note that the only interest of this fact is to save time to other people in similar position to mine

**Comment by oscarbenjamin** [comment]
You should compare with the dev docs rather than the previous release:
https://docs.sympy.org/dev/tutorials/intro-tutorial/solvers.html

**Comment by oscarbenjamin** [comment]
Also I think this kind of alignment problem with unicode output is to do with the font support in your browser. Basically your browser doesn't have the right monospace fonts or something.

**Comment by Arthur-Milchior** [comment]
@oscarbenjamin
Thanks.

Clearly explains why I couldn't reproduce. Dev doc has it fixed. Which clearly explains why I could not reproduce locally.


![2022-08-12-095405_841x632_scrot](https://user-images.githubusercontent.com/357361/184310253-ebaa1fb2-07e7-4e66-b296-9d7c3863bdda.png)
