### ISSUE TITLE
1.11rc1 breaks Algebra_with_Sympy downstream package...

### ISSUE THREAD

**Issue by gutow** [sympy/sympy#23908]
I am not sure this is a reason to hold up the release. To simplify extracting the equation class proposed in https://github.com/sympy/SymPEPs/pull/1, I used eval(..) to redefine all the sympy functions against an extension of the Function class after a standard load of sympy. This is a pretty bad hack, but I haven't had time yet to set up loading of sympy in a piecemeal way that would do this correctly. The current method leads to a metaclass conflict. I will try to work on it, but may have to pin to sympy 1.10.1 until I can work this out.

**Comment by oscarbenjamin** [comment]
I don't quite understand what you are describing. Can you make a small example that demonstrates what worked in sympy 1.10.1 but doesn't work with sympy 1.11rc1?

If you can make a small example then I can bisect to see what changed in sympy.

**Comment by gutow** [comment]
With 1.10.1 import works. `from algebra_with_sympy import *` Yields no errors and the rest of the code works as expected.
With 1.11rc1 import fails.
```
In [1]: from algebra_with_sympy import *
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Input In [1], in <cell line: 1>()
----> 1 from algebra_with_sympy import *

File ~/.local/share/virtualenvs/Algebra_with_SymPy-gdZZnYBt/lib/python3.8/site-packages/algebra_with_sympy/__init__.py:6, in <module>
      1 """
      2 .. include:: ../docs/intro.md
      3 """
      4 __docformat__ = "numpy"
----> 6 from algebra_with_sympy.algebraic_equation import *
      7 from algebra_with_sympy.preparser import *
      8 # Set the output formatting defaults

File ~/.local/share/virtualenvs/Algebra_with_SymPy-gdZZnYBt/lib/python3.8/site-packages/algebra_with_sympy/algebraic_equation.py:820, in <module>
    817 if func not in skip:
    818     execstr = 'class ' + str(func) + '(' + str(
    819         func) + ',EqnFunction):\n    pass\n'
--> 820     exec(execstr, globals(), locals())

File <string>:1, in <module>

TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases

```
I consider the loop causing the error, lines 817ff, very sketchy because of the way it uses `exec()`. It is on my list of things to change, but I have not got to it yet.

Thanks for looking at this.

**Comment by oscarbenjamin** [comment]
Can you make a self-contained example that demonstrates something that no longer works in 3.11 (without directly needing the `algebra_with_sympy` package)?

**Comment by gutow** [comment]
> Can you make a self-contained example that demonstrates something that no longer works in 1.11 (without directly needing the `algebra_with_sympy` package)?

I will try to get to this before the end of the day. Many of the operations/functions that are skipped in that loop had related metaclass conflicts. One of the sympy functions has probably been modified to behave like those. I will have to step through the code to find which one.

**Comment by gutow** [comment]
Here's the minimum that causes the error. It may very well be a problem with other sympy functions, but `piecewise_exclusive` is the one causing problems here.
```
from sympy import *

class dummyFunctionExtention(Function):
    """
    Extension of the sympy Function class.
    """
    def __new__(cls, *args, **kwargs):
        self.n = len(args)
        return super().__new__(cls, *args, **kwargs)

class piecewise_exclusive(piecewise_exclusive,dummyFunctionExtention):
    pass
```
The output is:
```
TypeError                                 Traceback (most recent call last)
Input In [2], in <cell line: 9>()
      6         self.n = len(args)
      7         return super().__new__(cls, *args, **kwargs)
----> 9 class piecewise_exclusive(piecewise_exclusive,dummyFunctionExtention):
     10     pass

TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases

```
The majority of the functions in the following list also have the same problem and have since I started building this code as an extension of Sympy rather than part of it. As I could not figure it out and it did not cause problems, I just skipped them. 
```
skip = ('sqrt', 'root', 'Min', 'Max', 'Id', 'real_root', 'cbrt',
            'unbranched_argument', 'polarify', 'unpolarify',
            'piecewise_fold', 'E1', 'Eijk', 'bspline_basis',
            'bspline_basis_set', 'interpolating_spline', 'jn_zeros',
            'jacobi_normalized', 'Ynm_c')
```

The way `piecewise_exclusive` has been rewritten may make it one I can also skip. Generic python functions work without needing extensions. Is `piecewise_exclusive` no longer a sympy function?

I have also verified that `piecewise_exclusive` + the `skip` list above are the only objects listed in `fuctions.__all__` that exhibit this issue. I can redefine all the others by redeclaring them as shown above.

**Comment by oscarbenjamin** [comment]
The `piecewise_exclusive` function is new in SymPy 1.11 and it just an ordinary Python function so it's not surprising that you can't subclass it. Same goes for a bunch of the others e.g. `sqrt`.

In the case of `Min` it should be possible to subclass it but it gives a different error:
```
TypeError                                 Traceback (most recent call last)
<ipython-input-18-765cc2e5048c> in <module>
      9         return super().__new__(cls, *args, **kwargs)
     10 
---> 11 class Min(Min,dummyFunctionExtention):
     12     pass
     13 

TypeError: Cannot create a consistent method resolution
order (MRO) for bases Expr, Application
```
I see the same error with both SymPy 1.10 and 1.11 though.

**Comment by gutow** [comment]
I will modify Algebra_with_Sympy to account for this and wrap the class extension of functions in a `try...except` so that future additions to `functions.__all__` will result in a warning if they cannot be extended. That will prevent breaking things that already work and provide some time for me to make updates.

As I said at the beginning this should not block release of SymPy 1.11.

I do suppose the MRO issue should be looked into, but I have not got to the point where I understand it enough to even make it an issue.

**Comment by oscarbenjamin** [comment]
> I do suppose the MRO issue should be looked into

I think you just need to make sure both superclasses use the same metaclass. Multiple inheritance is not something that can generally be expected to work with classes that were not explicitly designed for it though. Because of that and other issues the approach you've taken looks flakey.

**Comment by gutow** [comment]
> I think you just need to make sure both superclasses use the same metaclass. Multiple inheritance is not something that can generally be expected to work with classes that were not explicitly designed for it though. Because of that and other issues the approach you've taken looks flakey.

I agree and hope to have time to rebuild the code so that SymPy is imported piecemeal to provide its standard functionality and more stability.

Thanks.
