### ISSUE TITLE
test_pinjoint_arbitrary_axis fails if ran separately

### ISSUE THREAD

**Issue by TJStienstra** [sympy/sympy#23933]
When running `bin/test sympy/physics/mechanics` all tests pass, but if I run `bin/test sympy/physics/mechanics/tests/test_joint` the [test_pinjoint_arbitrary_axis](https://github.com/sympy/sympy/blob/b1f35f8daf5efa9f801f905cf1037000d69b0278/sympy/physics/mechanics/tests/test_joint.py#L153) fails.
```
sympy\physics\mechanics\tests\test_joint.py[8] ....F...                                      [FAIL]
sympy\physics\mechanics\tests\test_jointsmethod.py[7] .......                                  [OK]
___________________________________________________________________________________________________
___________ sympy\physics\mechanics\tests\test_joint.py:test_pinjoint_arbitrary_axis_______________
Traceback (most recent call last):
  File "...\sympy\physics\mechanics\tests\test_joint.py", line 223, in test_pinjoint_arbitrary_axis
    assert angle.xreplace({omega: 1}) == 0
AssertionError
````
This fail is due to the fact that when running this test separately the angle is not simplified (when done it is `0`). It is only simplified when testing the entire module.

The test fails for [line 223](https://github.com/sympy/sympy/blob/b1f35f8daf5efa9f801f905cf1037000d69b0278/sympy/physics/mechanics/tests/test_joint.py#L223), [line 250](https://github.com/sympy/sympy/blob/b1f35f8daf5efa9f801f905cf1037000d69b0278/sympy/physics/mechanics/tests/test_joint.py#L250) and [line 282](https://github.com/sympy/sympy/blob/b1f35f8daf5efa9f801f905cf1037000d69b0278/sympy/physics/mechanics/tests/test_joint.py#L282).

**Comment by TJStienstra** [comment]
Issue could be solved easily by using `assert A.ang_vel_in(N).cross(A.x + A.y) == 0`, which is just an easier computation for the same check.

**Comment by TJStienstra** [comment]
Found it. [Vector.simp = True](https://github.com/sympy/sympy/blob/b1f35f8daf5efa9f801f905cf1037000d69b0278/sympy/physics/mechanics/tests/test_functions.py#L14) in the `test_function.py` is the cause of the simplification. It should be noted that only the aforementioned test fails within the mechanics module, when commenting out this line.

**Comment by TJStienstra** [comment]
Adding `Vector.simp = True` to `test_joint.py` seems most ideal to me.

**Comment by moorepants** [comment]
I think we should avoid using `Vector.simp = True` and probably deprecate it. If a user wants to simplify things they should do it with the correct functions/methods.

**Comment by moorepants** [comment]
If you are compelled to do so :)

**Comment by TJStienstra** [comment]
Due to the deprecations and modified tests introduced by the interframe, there are no tests failing anymore. Shall I just remove that `Vector.simp = True` in the mechanics tests or also in the vector tests. For the latest it will probably mean that some functions just start with `Vector.simp = True` and end with `Vector.simp = False`. Since for example one tests even checks this simplification system and another one is asserting a dictionary containing some simplified vectors.

**Comment by moorepants** [comment]
>  So, my proposal would be to only remove it in test_functions.py.

Sounds fine to me. Probably a "if it ain't broke, don't fix it" case, as I mentioned yesterday. Trying to get rid of Vector.simp will probably be more work that expected.

**Comment by TJStienstra** [comment]
While implementing this fix I'm running into the problem that the symengine actually requires a lot of these simplifications. So I can either put approximately 10 simplify statements, due to the difference between sympy and the symeninge.
So maybe it is actually nicer to keep that `Vector.simp = True` statement in and just repeat it in the `test_joint.py` file.

**Comment by TJStienstra** [comment]
In agreement with @moorepants the second option has been chosen, since the first with its accompanying problems is not worth the effort.
