### ISSUE TITLE
`expand(0**(1 - x)) -> 0`

### ISSUE THREAD

**Issue by TomasVaskevicius** [sympy/sympy#23952]
Consider the following example:

```
p, q = sp.symbols("p q", real=True, nonnegative=True)
k1,k2 = sp.symbols("k1 k2", integer=True, nonnegative=True)
n = sp.Symbol("n", integer=True, positive=True)

expr = sp.Sum(sp.Abs(k1 - k2)*p**k1 *(1-q)**(n-k2), (k1,0,n), (k2,0,n))
expr
```
![image](https://user-images.githubusercontent.com/8312273/185812098-b24235b0-778a-4270-bdcd-6420d8a6ab7d.png)

In the above expression, we always have a constant term equal to n, which results from the values k1 = 0, k2 = n.
This is verified by first substituting a specific value of n into the expression and computing the sum.
```
# The correct result.
display(expr.subs(n,3).doit())
display(expr.subs(n,3).doit().subs(p,0).subs(q,1))
```
![image](https://user-images.githubusercontent.com/8312273/185812103-154ad7bd-423a-4a8d-b0a2-01e672a99be4.png)

However, if we first substitute q = 0 and p=1, the constant term does not survive:
```
# The incorrect result, the constant term disappears.
expr.subs(p,0).subs(q,1).doit()
```

![image](https://user-images.githubusercontent.com/8312273/185812108-55bf8ffc-6640-487b-8cc8-b0764c6ac132.png)

**Comment by oscarbenjamin** [comment]
The substitution gives this:
```python
In [26]: expr.subs(p,0).subs(q,1)
Out[26]: 
  n      n                          
 ___    ___                         
 ╲      ╲                           
  ╲      ╲     k₁  -k₂ + n          
  ╱      ╱    0  ⋅0       ⋅│k₁ - k₂│
 ╱      ╱                           
 ‾‾‾    ‾‾‾                         
k₂ = 0 k₁ = 0 
```
I guess something somewhere confuses that with zero by not accounting for the possibility that $0^0 = 1$.

**Comment by smichr** [comment]
`apart(0**(3-x), x)` gives 0
`expand(0**(3 - x))` gives 0

A base of 0 should not expand an `Add` exponent `e` unless `e.is_zero is False`.

**Comment by smichr** [comment]
I suspect these lines

https://github.com/sympy/sympy/blob/88664e6e0b781d0a8b5347896af74b555e92891e/sympy/core/power.py#L1040-L1042

can be

```python
if e.is_Add and e.is_commutative and (
            b.is_zero is False or e.is_zero is False):
        return Mul(*[self.func(b, x) for x in e.args])
return self  # nothing changed so no need to re-evaluate
```

**Comment by oscarbenjamin** [comment]
Improving expand would be good. Also the basic wrong result comes from this:
```python
In [12]: 0**x
Out[12]: 
 x
0 

In [13]: 0**x * 0
Out[13]: 0
```
The last product should not be zero if `x` is not known to be nonnegative.

**Comment by smichr** [comment]
I suspect the fix I suggest above is doomed to fail as is the desire to have `0*0**x` not be 0. My previous suggestion would require not expanding `x**(1 - y)` to `x*x**-y` and I'm guessing that will cause a lot of failures. We might need to fall back to just
```python
if e.is_Add and e.is_commutative and (
            b != 0 or e.is_zero is False):
        return Mul(*[self.func(b, x) for x in e.args])
return self  # nothing changed so no need to re-evaluate
