### ISSUE TITLE
Feature Request / Q: lambdify change order of checking to support iterable subclasses of Symbol

### ISSUE THREAD

**Issue by Xyhlon** [sympy/sympy#24006]
I want to extend the functionality of the Symbol class and want to make it backed with data. Thus I would like to make my Symbol iterable with the data and improve the usability, however when I try to convert an expression with my custom Symbol the check in 
 [here](https://github.com/sympy/sympy/blob/c56d9750312ef700f7af51a875d12d0ab8e52124/sympy/utilities/lambdify.py#L1184) prevents the expression from being converted into a function. Hence I would like to ask, if it is possible to change the order of the checks or first check if the element is a subclass of Symbol?

**Comment by ThePauliPrinciple** [comment]
You can make your class also a subclass of `sympy.utilities.iterables.NotIterable` to make it pass that check. There are some SymPy classes like `Tuple` that are currently `Basic` and iterable, so changing the order would change the behaviour for those classes.

**Comment by ThePauliPrinciple** [comment]
Also, I wonder if there doesn't already exist something in SymPy that can do what you want. Could you maybe show some examples of what you are trying to do?

**Comment by Xyhlon** [comment]
Thank you so much this is the solution I was looking for. 

Also thank you for your interest:
I would like to have a source of data, like a dataframe from pandas, from which a Symbol can take the data needed for computation automatically. The Symbols name is the same as the columns in the csv and the dataframe. Furthermore I would like to still be able to do symbolic and analytic manipulations and then calculate the desired equation with the necessary data from the data source. Basically, I want to create a seamless environment for interacting with pandas, numpy, matplotlib, sympy, physipy and uncertainties to ease the process of creating lab reports and enhance the productivity of the analysis of data.
```
filepathtocsv.csv
s,b,t,q,r
0,1,2,3,5
1,2,4,5,6
7,4,2,1,3

P.loaddata(filepathtocsv)
q = s*b
hec = sin(q/t)
P.eval(hec) # evaluates hec, calculates the values of hec and creates a new Symbol hec
```
I hope this gives a little idea what I am trying to achieve. Here the github [link](https://github.com/Bierbunker/Lab-Tool/tree/max_dev) to my project it, is very much a work in progress.

**Comment by oscarbenjamin** [comment]
Sounds like this is solved so I'll close the issue.
