### ISSUE TITLE
inconsistet sympy printing for passing to do fittingby scipy, symfit and lmfit

### ISSUE THREAD

**Issue by karimzadehz** [sympy/sympy#24023]
Hi  sympy!
I'm trying to implement a custom model using Fit .
I read the doc to see how to do that.
Unfortunately, there are some errors in my code and it seems to me that might be related to my model that is driven from sympy.
Here, I try to show very simple one of my problem:

    `import numpy as np
    import sympy as sp
    from symfit import Fit
    from symfit import parameters, variables, Model
    
    L_vals = np.array([0.299, 0.295, 0.290, 0.284, 0.279, 0.273, 0.268, 0.262, 0.256, 0.250])
    K_vals = np.array([2.954, 3.056, 3.119, 3.163, 3.215, 3.274, 3.351, 3.410, 3.446, 3.416])
    VA_vals = np.array([0.919, 0.727, 0.928, 0.629, 0.656, 0.854, 0.955, 0.981, 0.908, 0.794])
    
    gamma, alpha, beta, eta, L, K, VA = sp.symbols('gamma, alpha, beta, eta, L, K, VA')
    y = gamma - (1 / eta) * sp.log(alpha * L ** -eta + beta * K ** -eta)
    
    gamma, alpha, beta, eta = parameters('gamma, alpha, beta, eta')
    L, K, VA = variables('L, K, VA')
    model = Model({VA: y})
    fit = Fit(model, L=L_vals, K=K_vals, VA=VA_vals)
    fit_result = fit.execute()`

Please kindly let me know how deal with it.
Regards,
ZK

**Comment by oscarbenjamin** [comment]
Please use the mailing list to ask for help with using SymPy:
https://groups.google.com/g/sympy

GitHub issues are for reporting problems with SymPy rather than for getting help.
