### ISSUE TITLE
Beam - inconsistent convention used on draw()

### ISSUE THREAD

**Issue by Davide-sd** [sympy/sympy#24043]
The `draw()` method of the `Beam` class is used to plot a schematic view of the loads applied on the beam. I mainly use it to verify that I have applied the loads where they should. It doesn't compute anything. However, I came to the realization that it is inconsistent with the sign convention used by the class, which might leads to confusion. 

This is what I understood by reading [the documentation](https://docs.sympy.org/latest/modules/physics/continuum_mechanics/beam.html?highlight=beam#sympy.physics.continuum_mechanics.beam.Beam) and looking at the symbolic results. For the purpose of computation, positive loads are directed downward, negative loads are directed upwards. Symbolic loads (such as support reactions) are assumed positive, hence directed downwards.

Instead, the `draw()` method always plots symbolic reactions and loads directed towards the top.

A few simple examples should clarify the situation.

```python
from sympy import *
from sympy.plotting import PlotGrid
from sympy.physics.continuum_mechanics import Beam
init_printing()

E, I, P = symbols('E, I, P')
R1, R2 = symbols('R1, R2')
L = symbols("L", positive=True)

b1 = Beam(L, E, I)
b1.apply_load(R1, 0, -1)
b1.apply_load(R2, L, -1)
b1.apply_load(5, L/4, -1)
b1.bc_deflection = [(0, 0), (L, 0)]
b1.solve_for_reaction_loads(R1, R2)
p1 = b1.draw()

b2 = Beam(L, E, I)
b2.apply_load(R1, 0, -1)
b2.apply_load(R2, L, -1)
b2.apply_load(-5, L/4, -1)
b2.bc_deflection = [(0, 0), (L, 0)]
b2.solve_for_reaction_loads(R1, R2)
p2 = b2.draw()

b3 = Beam(L, E, I)
b3.apply_load(R1, 0, -1)
b3.apply_load(R2, L, -1)
b3.apply_load(P, L/4, -1)
b3.apply_load(5, L/2, -1)
b3.bc_deflection = [(0, 0), (L, 0)]
b3.solve_for_reaction_loads(R1, R2)
p3 = b3.draw()

p1.title = "W = +5 -> " + str(b1.reaction_loads)
p2.title = "W = -5 -> " + str(b2.reaction_loads)
p3.title = "W = P + 5 -> " + str(b3.reaction_loads)
PlotGrid(2, 2, p1, p2, p3)
```

![index](https://user-images.githubusercontent.com/9921777/189521427-d97df3fa-24fe-4528-a7af-a43131d9498a.png)

However, let's look at the results:
* top-left plot with positive numeric load. Symbolic results are computed with the above convention (positive loads downward, symbolic loads downward): in words, reaction loads have opposite direction than the load. Intuitively, the plot appears correct, but this is just by chance as the `draw()` method doesn't compute anything. A user comparing symbolic results and the schematic view might think that the reaction loads are directed in the opposite direction that what it is currently drawn, which would be wrong. The correct plot would have the reaction loads pointing downward: the user then looks at the symbolic results, see that they must be directed opposite to the numeric load, so in reality the reaction loads would be directed upward. Essentially, if I use the current schematic to perform computations by hand, I would get reaction loads with opposite sign than the ones computed by SymPy.
* top-right plot with negative numeric load. As the (symbolic) reaction loads are positive, a user might get the impression that there is agreement between what is computed by SymPy and the direction illustrated in the schematic. This is wrong. Again, by doing computations by hand based on the schematics, I'll get opposite signs on the reactions than what computed by SymPy.
* Bottom-left plot: positive numeric load and symbolic load. The `Beam` class consider both loads directed downward. The `draw()` method consider the symbolic load directed upward. This results in a conceptual mess. If we do computations by hand based on the schematic, we'll get different results than SymPy.

I believe that the `draw()` method should use the same convention as used by the class. Sure, reaction loads will be pointed downwards in the schematic view, which is pretty much against what we usually use in hand written computations. But at least this will bring coherence with the symbolic results.

I'm probably going to add a few more inconsistencies on this issue about the `draw()` method later on.

**Comment by Davide-sd** [comment]
Dealing with moments: according to the convention of the class, positive moments are in the counterclockwise direction. Negative moments in the clockwise direction. The class doesn't care about assumptions on symbolic moments and symbolic moments are assumed positive. To apply a negative symbolic moment one should use the "minus" sign.

```python
E, I = symbols("E, I")
L = symbols("L", positive=True)
R1, R2 = symbols("R1, R2")
M1, M2 = symbols("M1, M2")
M3 = symbols("M3", positive=True)
M4 = symbols("M4", negative=True)
b = Beam(L, E, I)
b.apply_load(R1, 0, -1)
b.apply_load(R2, L, -1)
# apply positive moment in counterclockwise direction
b.apply_load(M1, 0, -2)
# apply negative moment in clockwise direction
b.apply_load(-M2, L/4, -2)
# apply positive moment in counterclockwise direction
b.apply_load(M3, L/2, -2)
# apply positive moment in counterclockwise direction
b.apply_load(M4, 3*L/4, -2)
b.bc_deflection = [(0, 0), (L, 0)]
b.draw().show()
```
![index](https://user-images.githubusercontent.com/9921777/189712178-52a245ec-8504-4e55-8365-1dd458fd6d62.png)

Let's see what the `draw` method  does:

* `M2` is wrong: the method doesn't consider the "minus" sign.
* `M4` is wrong: the method considers assumptions on symbolic moments.

Again, trying to manually compute the support reactions with the above diagram will lead to incorrect results.

**Comment by Davide-sd** [comment]
When a negative distributed load is applied, the loads are going to hide the beam:

```python
E, I = symbols("E, I")
L = symbols("L", positive=True)
R1, R2 = symbols("R1, R2")

b1 = Beam(L, E, I)
b1.apply_load(2, 0, 0, L/2)
b1.bc_deflection = [(0, 0), (L, 0)]
p1 = b1.draw()

# adding negative distributed load
b2 = Beam(L, E, I)
b2.apply_load(2, 0, 0, L/2)
b2.apply_load(-3, L/2, 0, L)
b2.bc_deflection = [(0, 0), (L, 0)]
p2 = b2.draw()

PlotGrid(2, 1, p1, p2)
```

![index](https://user-images.githubusercontent.com/9921777/189715527-69aba0fa-fe9e-4d71-b127-ff35060621a0.png)


When trying to visualize symbolic distributed loads an error will be raised:

```python
E, I = symbols("E, I")
L = symbols("L", positive=True)
R1, R2 = symbols("R1, R2")
w = symbols("w")
b1 = Beam(L, E, I)
b1.apply_load(w, 0, 0, L/2)
b1.bc_deflection = [(0, 0), (L, 0)]
b1.draw().show()

# TypeError: cannot determine truth value of Relational
```

**Comment by moorepants** [comment]
@Davide-sd thanks for reporting these. There are several prior issues where we worked out the sign convention ideas for the code. There has been general confusion on how to approach it. Knowing whether a symbol is positive, negative, or undefined is certainly important. I don't doubt that the draw() method needs some improvements to make things consistent.
