### ISSUE TITLE
Truss - create and expose an attribute to get the length of the members

### ISSUE THREAD

**Issue by Davide-sd** [sympy/sympy#24040]
The `Truss` class can be used as a starting point to compute node deflections thanks to the principle of virtual works or energy methods. However, these computations require the knowledge of the member lengths. The class already computes them internally. It would be nice to be able to access them via some attribute: `members_lengths` maybe?

**Comment by Davide-sd** [comment]
@AdvaitPote do you think it can be included?

**Comment by AdvaitPote** [comment]
Sure. Adding an additional attribute to give the length of a member would not be problem.
