### ISSUE TITLE
disagreement in calculating left eigen vectors

### ISSUE THREAD

**Issue by ecopeng** [sympy/sympy#24057]
I spotted some disgreements between the left eigen vectors calculated using sympy vs. scipy. I used a third method with R to test which is working and which not and found that sympy just could not agree with the other two (which themselves agree with each other):

**The results in R as a benchmark:**
```
eigen(t(matrix(c(
		 0,0,0,0.45,
		 0.92,0.86,0,0,
 		 0,0.08,0.8,0.83,
		 0,0.02,0.19,0), nrow=4, byrow=TRUE)))
```
which gives
$values
[1]  1.00911849  0.80796999 -0.15445857 -0.00262991
$vectors
          [,1]        [,2]         [,3]         [,4]
[1,] 0.3560529 -0.69149039  0.023457396  0.386597866
[2,] 0.3905430 -0.60728640 -0.003938256 -0.001105128
[3,] 0.5708830  0.39086500 -0.195179778 -0.212444868
[4,] 0.6283273  0.01639575  0.980479013  0.897445289

**Left eigen vectors derived from the same matrix using sympy:**
```
from sympy import Matrix
mat = Matrix([
	[0.00, 0.00, 0.00, 0.45],
	[0.92, 0.86, 0.00, 0.00], 
	[0.00, 0.08, 0.80, 0.83],
	[0.00, 0.02, 0.19, 0.00]])
mat.left_eigenvects()
```
gives
[
(0.807969994528574, 1, [Matrix([[-0.691490391695322, -0.607286399994165, 0.390864997233702, 0.0163957467861256]])]), 
(1.00911848719356, 1, [Matrix([[-0.367723827185572, -0.403344469776664, -0.589595720734859, -0.648922974609852]])]), 
(-0.00262991019554735, 1, [Matrix([[0.488905411462149, -0.00139758405028541, -0.268665335757296, 1.13494123321861]])]), 
(-0.154458571526590, 1, [Matrix([[0.0287659419952231, -0.00482950685782489, -0.239350102195014, 1.2023671401884]])])
]

**Left eigen vectors derived from the same matrix using scipy:**
```
import scipy
mat = np.array([
	[0.00, 0.00, 0.00, 0.45],
	[0.92, 0.86, 0.00, 0.00], 
	[0.00, 0.08, 0.80, 0.83],
	[0.00, 0.02, 0.19, 0.00]])
scipy.linalg.eig(mat, left = True, right = False)
```
which gives
(array([ 1.00911849+0.j,  0.80796999+0.j, -0.00262991+0.j, -0.15445857+0.j]), 
array([
[-0.3560529 ,  0.69149039,  0.38659787,  0.0234574 ],
[-0.390543  ,  0.6072864 , -0.00110513, -0.00393826],
[-0.57088295, -0.390865  , -0.21244487, -0.19517978],
[-0.62832726, -0.01639575,  0.89744529,  0.98047901]]))

**Comment by oscarbenjamin** [comment]
What exactly is different? They return their results in different formats but otherwise they look similar to me. Note that eigenvectors are only defined up to multiplication by an arbitrary nonzero constant e.g. here the difference is just a minus sign (which is arbitrary):
```python
In [33]: from sympy import Matrix
    ...: mat1 = Matrix([
    ...: [0.00, 0.00, 0.00, 0.45],
    ...: [0.92, 0.86, 0.00, 0.00],
    ...: [0.00, 0.08, 0.80, 0.83],
    ...: [0.00, 0.02, 0.19, 0.00]])

In [34]: import scipy
    ...: mat = np.array([
    ...: [0.00, 0.00, 0.00, 0.45],
    ...: [0.92, 0.86, 0.00, 0.00],
    ...: [0.00, 0.08, 0.80, 0.83],
    ...: [0.00, 0.02, 0.19, 0.00]])
    ...: es = scipy.linalg.eig(mat, left = True, right = False)

In [35]: es[0][1]
Out[35]: (0.8079699945285749+0j)

In [36]: mat1.left_eigenvects()[0]
Out[36]: 
(0.807969994528574, 1, [[-0.691490391695322  -0.607286399994165  0.390864997233702  0.0163957467861
256]])

In [37]: mat1.left_eigenvects()[0][0]
Out[37]: 0.807969994528574

In [39]: mat1.left_eigenvects()[0][2]
Out[39]: [[-0.691490391695322  -0.607286399994165  0.390864997233702  0.0163957467861256]]

In [40]: es[1][:,1]
Out[40]: array([ 0.69149039,  0.6072864 , -0.390865  , -0.01639575])

In [41]: es[1][:,1] * -1
Out[41]: array([-0.69149039, -0.6072864 ,  0.390865  ,  0.01639575])
```

**Comment by ecopeng** [comment]
Thanks for the clarification.
scipy and sympy do give the same set of (left) eigenvalues, but then why their associated left eigenvectors are inconsistent unless you scale them? Does this scaling have something to do with the differences in their precision (i.e., sympy give more digits after decimal than scipy does)?

**Comment by oscarbenjamin** [comment]
> why their associated left eigenvectors are inconsistent unless you scale them?

They are not inconsistent. Eigenvectors are not uniquely defined because any multiple of an eigenvector is also an eigenvector. You can make them almost unique by requiring them to have unit length but then the sign is still arbitrary so you will always be left with two possible choices even for a unit eigenvector.

**Comment by oscarbenjamin** [comment]
Closing because I don't see any issue here.

**Comment by ecopeng** [comment]
Thanks!
