### ISSUE TITLE
Is there some functions can rewrite “x**3” to "x*x*x"?

### ISSUE THREAD

**Issue by TimoTokki** [sympy/sympy#24068]
I want to use sympy's simplification result of expressions in C++, but the form of sympy's powers, i.e. "**", is not supported by c++.
So, I wonder if there is a function that can convert "x**3" to "x*x*x"?

**Comment by oscarbenjamin** [comment]
Maybe you want `cxxcode`:
```
In [58]: cxxcode(x**3)
Out[58]: 'std::pow(x, 3)'
```
I'm closing because GitHub issues are not for getting help with using SymPy.

**Comment by asmeurer** [comment]
For generating C++ directly cxxcode should do what you want, but you can also use https://docs.sympy.org/latest/modules/codegen.html#sympy.codegen.rewriting.create_expand_pow_optimization to rewrite the expression directly.

**Comment by TimoTokki** [comment]
Thank you both very much for your quick and enthusiastic help. Your answers have helped me a lot.
I'm also sorry for asking for help via GitHub issues.
Finally, I hope I can contribute to the development of SymPy in the future.
