### ISSUE TITLE
Compare expressions but disregarding constant values

### ISSUE THREAD

**Issue by soerenab** [sympy/sympy#24069]
Hi,

Thanks a lot for creating ```sympy``` I find it very helpful. I wondering if I can somehow use ```sympy``` to compare two expressions but to disregard potential differences in constants in the expressions, e.g. 
```2*x``` should equal ```2.1*x``` or ```3*exp(2*x)``` should equal ```4*exp(3*x)```. I would like to use this function to compare the "structure" of two expressions. Is this currently possible with sympy, and if so, how would I do that? If it is currently not possible, is it possible to implement this (and if so, how could this be implemented)? Thanks a lot!

**Comment by smichr** [comment]
I view this as wanting to define a custom canonical form in which all products are stripped of leading number Float or Rational. `mycan = lambda expr: expr.replace(lambda x: x.is_Mul, lambda x: x.as_coeff_Mul()[1])` should put an expression in canonical form. 

![image](https://user-images.githubusercontent.com/90703/191094789-5bcbc874-db73-4940-ab9c-2dad327e3a7b.png)

**Comment by soerenab** [comment]
Thanks for the quick answer! Hmm, I think I may have biased you with my examples above but I actually meant any constants, not just coefficients. So while you solution works fine for the cases above, it would not work for e.g. ```2 * x - 3``` should equal ```2.1 * x - 2.4```, right? Is there any way I can extend it to cover such cases as well? Also, I would actually want ```2 * x``` != ```x```, which with the approach above would be regarded as equal, I believe

**Comment by soerenab** [comment]
One idea that I had was to introduce a generic ```<constant>``` token which returns ```True``` if compared to another ```<constant>``` token (regardless of constant values) but ```False``` otherwise. But I am not sure if this is feasible and how/where I would introduce this. I am also not sure about potential implications for expression simplification.

**Comment by oscarbenjamin** [comment]
Maybe what you want is `match`:
```python
In [33]: e1 = 3*exp(2*x)

In [34]: e2 = 4*exp(3*x)

In [35]: nums = e1.atoms(Number)

In [36]: nums
Out[36]: {2, 3}

In [37]: wilds = symbols(f'w:{len(nums)}', multiple=True, cls=Wild)

In [38]: rep = dict(zip(nums, wilds))

In [39]: rep
Out[39]: {2: w₀, 3: w₁}

In [40]: e1.subs(rep)
Out[40]: 
    x⋅w₀
w₁⋅ℯ    

In [41]: e1.subs(rep).matches(e2)
Out[41]: {w₀: 3, w₁: 4}
```

**Comment by smichr** [comment]
Sure: just modify `mycan`:
```python
>>> mycan = lambda expr: expr.replace(lambda x: x.is_Mul, lambda x: x.as_coeff_Mul()[1])
>>> mycan(2*x+3) == mycan(3*x-4)
True
```
I avoid `match` for the most part but you should give both a try and see how they work for you in terms of accuracy and speed.

**Comment by oscarbenjamin** [comment]
Closing because this is not reporting any issue with sympy.
