### ISSUE TITLE
pygletplot is using deprecated threading.event.isSet()

### ISSUE THREAD

**Issue by chatcannon** [sympy/sympy#24074]
`isSet()` is deprecated in favour of `is_set()`

https://docs.python.org/3/library/threading.html#threading.Event.is_set

When I try to run `sympy.test("sympy/plotting/pygletplot")`, this causes errors because the threading library interprets a `DeprecationWarning` inside a thread as an exception and `raise`s it outside the thread.

It seems like the only place using this function is plot_mode_base.py

https://github.com/sympy/sympy/search?q=isSet

The `is_set` alternative was added in Python 2.6, so I don't think we need to use `isSet` for backwards compatibility any more: https://docs.python.org/2.6/library/threading.html#threading.Event.is_set

**Comment by oscarbenjamin** [comment]
The pyglet tests are blacklisted when run in CI I think.
