### ISSUE TITLE
test_autowrap_store_files_issue_gh12939 fails if the current directory is not writeable

### ISSUE THREAD

**Issue by chatcannon** [sympy/sympy#24075]
This test (in `sympy/utilities/tests/test_autowrap.py`) tries to write to `./tmp` but does not check that the current directory is writeable, so it fails with "Permission denied".

Since (as far as I can tell) the `sympy.test` changes to the `site-packages` directory before running the tests, so that a relative filename will resolve correctly, running this test against the system sympy installation will fail even when the python executable is called from a writeable current directory.

**Comment by oscarbenjamin** [comment]
I guess you mean this:
https://github.com/sympy/sympy/blob/007d962672034698a5d152de9086e63c3becfa74/sympy/utilities/tests/test_autowrap.py#L261-L269
Yes, that looks like it should be fixed.

**Comment by bjodah** [comment]
We should probably use [tempfile.mkdtemp](https://docs.python.org/3/library/tempfile.html#tempfile.mkdtemp)

**Comment by oscarbenjamin** [comment]
Can the `tempdir` argument to `autowrap` be used rather than `chdir`?

**Comment by bjodah** [comment]
I don't think so. I believe the test exercises passing a *relative* path being passed to the `tempdir` kwarg (cf. gh-12939). But if we put a `os.chdir` in the `finally` block too, restoring the working directory to whatever it was at test entry (which we get from `os.getcwd` and stash away prior to changing directory), then I think we're fine?
