### ISSUE TITLE
wrong eigenvalue

### ISSUE THREAD

**Issue by lightsaber1997** [sympy/sympy#24083]
I tried to get an eigenvalue of a symmetric matrix.
And the simplified form of the eigenvalue seems like a complex number, which feels weird considering that eigenvalues of a symmetric matrix should be real.
I'm not sure whether the `eigenval()` is wrong or `simplify()` is not working.

```
from sympy import *
A = Matrix([
    [14, 4, 13],
    [4, 6, 5],
    [13, 5, 13]
])

# d = A.evalf().eigenvals()
d = A.eigenvals()
for key in d:
    display(simplify(key))
```

[output]
```
11 + 229*3**(2/3)/(3*(5526 + sqrt(5490291)*I)**(1/3)) + (16578 + 3*sqrt(5490291)*I)**(1/3)/3
(-458*3**(2/3)/3 + (1 - sqrt(3)*I)*(66 + (-1 + sqrt(3)*I)*(16578 + 3*sqrt(5490291)*I)**(1/3))*(5526 + sqrt(5490291)*I)**(1/3)/6)/((1 - sqrt(3)*I)*(5526 + sqrt(5490291)*I)**(1/3))
(-458*3**(2/3)/3 + (1 + sqrt(3)*I)*(66 + (-1 - sqrt(3)*I)*(16578 + 3*sqrt(5490291)*I)**(1/3))*(5526 + sqrt(5490291)*I)**(1/3)/6)/((1 + sqrt(3)*I)*(5526 + sqrt(5490291)*I)**(1/3))
```

**Comment by oscarbenjamin** [comment]
All three eigenvalues are real. Their expressions just involve complex numbers due to casus irreducibilus:
https://en.wikipedia.org/wiki/Casus_irreducibilis
