### ISSUE TITLE
DOC: Mention that Float cannot represent negative zero

### ISSUE THREAD

**Issue by chatcannon** [sympy/sympy#24088]
The documentation for sympy.Float mentions that the Float type cannot represent infinity and NaN. Given that IEEE 754 floats also have separate values for positive and negative zero, but sympy Float does not (not even if passing mpf tuple `(1,0,0,0)` to the constructor), the documentation should mention this difference.

**Comment by metabiswadeep** [comment]
Could you please tell the location where documentation for sympy.float is present because I cant seem to fin it.

**Comment by nicholasmanha** [comment]
> NaN

https://docs.sympy.org/latest/modules/core.html?highlight=float#sympy.core.numbers.Float

**Comment by nicholasmanha** [comment]
Doc for float: https://docs.sympy.org/latest/modules/core.html?highlight=float#sympy.core.numbers.Float
