### ISSUE TITLE
Sympy doesn't simplify square root.

### ISSUE THREAD

**Issue by PoSayDone** [sympy/sympy#24090]
sqrt(256^x) gives sqrt(256^x), but answer is 16^x

**Comment by smichr** [comment]
SymPy `powsimp` will make this change when it is valid (e.g. `x` is real`. If you substitute `x=I` you will find the expressions differ.

![image](https://user-images.githubusercontent.com/90703/192560072-5718972a-d61f-48ac-bccd-843e162e001e.png)

**Comment by PoSayDone** [comment]
@smichr, thank you, thats working! but how to define vars as real if im using ```simplfy('sqrt(2x**(4*x)*16**(x))')```?  The only way is to manually define x as real before or I could somehow automaticly make all vars which are coming from simplify real?

**Comment by oscarbenjamin** [comment]
You need to manually define the assumptions:
https://docs.sympy.org/latest/guides/assumptions.html#applying-assumptions-to-string-inputs

**Comment by PoSayDone** [comment]
> You need to manually define the assumptions: https://docs.sympy.org/latest/guides/assumptions.html#applying-assumptions-to-string-inputs

thank you!
