### ISSUE TITLE
parse_latex should not use evaluate=False by default

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#24116]
Right now parse_latex creates all expressions with evaluate=False:

```py
>>> from sympy.parsing.latex import parse_latex
>>> parse_latex(r'1 + 1')
1 + 1
```

It really should evaluate by default, and only try to create unevaluated expressions when an `evaluate=False` flag is passed, similar to `parse_expr`:

```py
>>> parse_expr(r'1 + 1')
2
```

There are certainly use-cases for parsing LaTeX into unevaluated expressions, but the default use-case is just to take a LaTeX formula and put it into SymPy. This should not be done in way that can create broken expressions. Unevaluated expressions can cause all sorts of issues depending on what sort of evaluation is skipped.

This may need to be done as a deprecation, since the current behavior is being relied on by many people.

**Comment by 1e9abhi1e10** [comment]
How to approach this issue to fix it?

**Comment by sylee957** [comment]
This have little backward compatibility problem, but I'd rather wait for the projects like `lark` transition to finish

**Comment by wermos** [comment]
@sylee957 Now that #25324 is merged, I think we can resume discussion on this issue.

As far as I understand, we want the default behavior to be to evaluate the expression, except if `evaluate=False` is passed into the LaTeX parser. Is that correct? If so, this is a pretty easy change to make to the Lark-based LaTeX parser.

**Comment by sylee957** [comment]
I think that evaluating by default makes the code a lot more simpler.

**Comment by asmeurer** [comment]
Yes, that is the behavior we want. Unevaluated expressions are broken in a lot of ways and should be avoided in most contexts.
