### ISSUE TITLE
Flux in two dimensions using sympy.vector.vector_integrate

### ISSUE THREAD

**Issue by Morten10** [sympy/sympy#24123]
I am having trouble calculating the following example
https://www.khanacademy.org/math/multivariable-calculus/integrating-multivariable-functions/line-integrals-in-vector-fields-articles/a/flux-in-two-dimensions
where F is 
![image](https://user-images.githubusercontent.com/115358235/194711492-d7940252-df9b-40c9-af82-3e61d5a1fc8f.png)
and r(t) is
![image](https://user-images.githubusercontent.com/115358235/194711516-bdb02bcf-4a66-4910-95db-68918877d9e0.png)

```
from sympy import sin, cos, exp, pi, symbols
from sympy.vector import CoordSys3D, ParametricRegion, ImplicitRegion, vector_integrate
from sympy.abc import r, x, y, z, theta, phi,a
C = CoordSys3D('C')
F=C.x**2*C.i+C.y*C.j
display('F=',F)
semicircle = ParametricRegion((3*cos(theta), 3*sin(theta)), (theta, 0, 2*pi))
flux = vector_integrate(F, semicircle)
display('flux=',flux)
```

**Comment by oscarbenjamin** [comment]
GitHub issues are not for getting help with using SymPy. Please use the mailing list for that.
