### ISSUE TITLE
Matrix is not recognized as iterable

### ISSUE THREAD

**Issue by TJStienstra** [sympy/sympy#24130]
While playing around with checking whether objects are iterable, I noticed that `Matrix` is not recognized as iterable by a lot of methods (using `__iter__`). A preferable method to check whether some object is iterable is using the `Iterable` class from `collections.abc`. Currently this gives the following result:
```py
from collections.abc import Iterable
from sympy import Matrix
print(isinstance(Matrix([1, 2, 3]), Iterable))  # prints False
from symengine import Matrix
print(isinstance(Matrix([1, 2, 3]), Iterable))  # prints True
```
The reason why one can currently loop over `Matrix` is the implemented `__getitem__` method in `RepMatrix`.
Another issue I see that is partially related is #5643

**Comment by asmeurer** [comment]
Why does it fail? `iter(Matrix)` seems to work just fine.

**Comment by TJStienstra** [comment]
From [the collections.abc docs](https://docs.python.org/3/library/collections.abc.html):
_Checking `isinstance(obj, Iterable)` detects classes that are registered as [Iterable](https://docs.python.org/3/library/collections.abc.html#collections.abc.Iterable) or that have an `__iter__()` method, but it does not detect classes that iterate with the `__getitem__()` method. The only reliable way to determine whether an object is [iterable](https://docs.python.org/3/glossary.html#term-iterable) is to call iter(obj)._

Probably I should just use a `try` `except` statement, but personally I'd rather use `isinstance(obj, Iterable)`

**Comment by asmeurer** [comment]
If this is for SymPy code, you should use the iterable() helper in the utilities module https://github.com/sympy/sympy/blob/master/sympy/utilities/iterables.py#L2898

**Comment by TJStienstra** [comment]
Oh thanks, I'm indeed playing a bit around with some new stuff for the mechanics module.
Is this still a problem we'd like to see fixed or shall I close this issue?

**Comment by asmeurer** [comment]
I guess we can register `Matrix` as `Iterable`, assuming that doesn't have any other impact. Or manually define `__iter__`. Though it honestly sounds like `Iterable` is kind of useless for this reason.

`iterable()` will still be better for SymPy code regardless though because it filters out some things that you usually don't want to actually treat as iterable (like `str` and various SymPy classes that include `NotIterable`).

**Comment by TJStienstra** [comment]
Yeah, will make sure to use `iterable()`.

As far I know it is good python practice to define `__next__` and `__iter__` when an object should be iterable.
However it is probably not worth the effort (time difference is low).

**Comment by oscarbenjamin** [comment]
I think that making Matrix iterable was a mistake just like allowing single indexing (#24007). Probably it's just a consequence of defining `__len__`.
