### ISSUE TITLE
Matrix expressions should be less strict about shape checks

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#24149]
I think the fundamental problem in the matrix expressions is that it validates dimensions using symbolic, structural equality. In other words, behavior like this:

```
>>> var('n m k l', integer=True)
(n, m, k, l)
>>> MatrixSymbol("A", n, m)*MatrixSymbol("B", k, l)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/aaronmeurer/Documents/Python/sympy/sympy/./sympy/matrices/expressions/matexpr.py", line 27, in __sympifyit_wrapper
    return func(a, b)
  File "/Users/aaronmeurer/Documents/Python/sympy/sympy/./sympy/core/decorators.py", line 106, in binary_op_wrapper
    return func(self, other)
  File "/Users/aaronmeurer/Documents/Python/sympy/sympy/./sympy/matrices/expressions/matexpr.py", line 127, in __mul__
    return MatMul(self, other).doit()
  File "/Users/aaronmeurer/Documents/Python/sympy/sympy/./sympy/matrices/expressions/matmul.py", line 60, in __new__
    validate(*matrices)
  File "/Users/aaronmeurer/Documents/Python/sympy/sympy/./sympy/matrices/expressions/matmul.py", line 249, in validate
    raise ShapeError("Matrices %s and %s are not aligned"%(A, B))
sympy.matrices.common.ShapeError: Matrices A and B are not aligned
```

The problem here is that this expression is completely valid if `m` and `k` are equal. There's no reason mathematically to assume they aren't. 

We could instead allow any multiplication of any shapes unless the inner dimensions are explicitly not equal, like `(n x k) * (k + 1 x m)`. If we did this, there would be no need for GenericIdentity or GenericZeroMatrix or GenericOneMatrix. We could just use `n = Dummy('n', integer=True); Identity(n)`.

Of course, we would still want a strict validation function where inner dimensions are required to be exactly equal, but this should be something like an optional flag to `doit`, rather than something that is automatically called in the constructor. 

One problem with this approach is the assumptions system is still not very good at handling generic constraints like `Ne(k, m)`, although in principle the new assumptions machinery is capable of representing them. This isn't just for user constraints: you would need this to validate dimensions across multiple operations, e.g., `(n x n) * (m x m) * (n + 1 x n + 1)` should never validate, because it would imply that `n = m = n + 1`.

_Originally posted by @asmeurer in https://github.com/sympy/sympy/pull/24141#discussion_r998771206_

**Comment by sylee957** [comment]
The only problem is that this needs complicated implementation of propositional theorem prover to solve this.
There can be other interpretation of this, like using object like `MatAdd(), MatMul()` to be used instead of `GenericZeroMatrix, GenericOneMatrix`. It can make sense mathematically for introducing the ground terms for `MatAdd, MatMul` itself.

**Comment by sylee957** [comment]
But I am +1 for making unevaluated expression for `MatAdd, MatMul` regardless of shape without exceptions.

**Comment by asmeurer** [comment]
The theorem proving aspect can be poor or even non-existent to begin with. It's only needed for better validation. SymPy is already capable of detecting that simple things like n = n + 1 are  invalid.

**Comment by asmeurer** [comment]
> There can be other interpretation of this, like using object like MatAdd(), MatMul() to be used instead of GenericZeroMatrix, GenericOneMatrix. 

That's effectively already what it is. Maybe it would be simpler to not have the separate class, I don't know. It still needs to print specially. It still wouldn't have a meaningful `shape`. If you look at the implementation of `GenericZeroMatrix`, it's basically just a small class that raises TypeError when you call `shape` on it. 

It doesn't really change much with respect to this suggestion to do that. The real problem is that either way, there's no meaningful thing that can be returned from `shape`. My original idea with it was to have a generic shape object instead of a generic matrix (https://github.com/sympy/sympy/pull/15986), but I decided that the generic matrix was simpler. This is basically a revisit of https://github.com/sympy/sympy/pull/15986, but in a much simpler way by making all shapes effectively generic.
