### ISSUE TITLE
Define non-negative integers as a symbol 

### ISSUE THREAD

**Issue by isakhammer** [sympy/sympy#24143]
I am trying to do some of the funny integrals in Fourier transforms in Sympy and to be able to do the integrals I need to define a symbol as a non-negative integer, i.e. n = 0,1, 2, 3, .... However, I am able to define positive integers, but I am not able to include the zero. Any idea how to include zero as well?
![image](https://user-images.githubusercontent.com/43385748/196543882-f06cf1ce-9013-48a9-a557-1b943b570e72.png)

**Comment by bjodah** [comment]
Try with `nonnegative=True` instead of `positive=True`.
https://docs.sympy.org/latest/guides/assumptions.html#predicates

Feel free to reopen if needed.
