### ISSUE TITLE
take so long to generate a dynamical function with 6000 variables

### ISSUE THREAD

**Issue by chen78-sys** [sympy/sympy#24144]
x = np.array(sympy.symbols('x0:%d'%(6000)))
func_obj = np.dot(a_b_list,x) 

where a_b_list is a 1-D float array with the size of 6000
a_b_list = [1.0, 2.0, 3.0, 4.0, ... 6000.0]
expect the func_obj = 1.0x0+2.0x1+3.0x2+4.0x3+....+6000.0x5999

It took so long and I gave up the waiting for its completeness. 

found the  **return func(self, other)** below in sympy\core\decorators.py run so long and it add each element in the function one by one e.g., 1.0x0, 1.0x0+2.0x1
the speed become more slow when the variables reach 1000

 @wraps(func)
        def _func(self, other):
            # XXX: The check for _op_priority here should be removed. It is
            # needed to stop mutable matrices from being sympified to
            # immutable matrices which breaks things in quantum...
            if not hasattr(other, '_op_priority'):
                try:
                    other = sympify(other, strict=True)
                except SympifyError:
                    return retval
            if not isinstance(other, expectedcls):
                return retval
            **return func(self, other)**

**Comment by moorepants** [comment]
SymPy is not designed to be mixed with NumPy code in the fashion you show. Also, given that you are using floats as coefficients to your equations, my guess is that you likely may not need SymPy at all. If you do need SymPy, a large dot product can be represented by with two MatrixSymbol objects and the floats could be introduced after lambdifying your matrix expressions.

**Comment by oscarbenjamin** [comment]
Adding SymPy expressions with repeated use of `__add__` has quadratic complexity. Rather than using a numpy array you should use sympy matrices or otherwise just a list comprehension:
```python
In [23]: x = sympy.symbols('x0:%d'%(6000))

In [24]: a_b_list = range(1, 6000+1)

In [25]: ok = Matrix(x).dot(Matrix(a_b_list))
```
