### ISSUE TITLE
Integration parameter cannot be substituted

### ISSUE THREAD

**Issue by blackyblack** [sympy/sympy#24157]
While integrated function and integral upper/lower limits can be substituted, integration parameter cannot.

Code snippet to validate this behavior:
```python
from sympy import Integral, symbols
f, x, a = symbols('f x a')
integral = Integral(f, (x, a, 1))
integral.subs(f, 0)
>>> Integral(0, (x, a, 1))
integral.subs(x, 0)
>>>Integral(f, (x, a, 1))
integral.subs(a, 0)
>>>Integral(f, (x, 0, 1))
```

**Comment by eagleoflqj** [comment]
It doesn’t make sense to substitute `x` mathematically.

**Comment by blackyblack** [comment]
I have a general integral form as a template. I want to substitute it's function which may have x or y or t or whatever as a parameter. It is true that we can use x in an integral and substitute the parameter of function instead. But it is an unnecessary limitation and IMO it should not be forced.

**Comment by eagleoflqj** [comment]
`subs` is not meant to do that job. It substitutes free variable only.
You can do something like this:
```py
from sympy import symbols, Integral
x, y = symbols('x y')
i = Integral(x**2, (x, 0, 1))
j = Integral(i.args[0].subs(x, y), i.args[1].subs(x, y))
print(j)
```
and it gives you `Integral(y**2, (y, 0, 1))`

**Comment by blackyblack** [comment]
X is free variable here. So if it is substituted in integrand, it is only logical to substitute it in integral limits as well.

**Comment by oscarbenjamin** [comment]
> X is free variable here

I'm not sure which integral you are referring to but in the OP example `x` is not a free variable:
```python
In [12]: i = Integral(f, (x, a, 1))

In [13]: i
Out[13]: 
1     
⌠     
⎮ f dx
⌡     
a     

In [14]: i.free_symbols
Out[14]: {a, f}

In [15]: i.bound_symbols
Out[15]: [x]
```
Mathematically it is not meaningful to substitute a variable that is not free but obviously it makes sense structurally. That's why `xreplace` which operates structurally can do this:
```python
In [16]: i.xreplace({x:y})
Out[16]: 
1     
⌠     
⎮ f dy
⌡     
a 
```
Obviously the integration variable can't just be a number though so you'll get an error if you try to set it to zero:
```
In [18]: i.xreplace({x:0})
---------------------------------------------------------------------------
ValueError: Invalid limits given: ((0, a, 1),)
```
