### ISSUE TITLE
Incorrect Inequality Simplification

### ISSUE THREAD

**Issue by u7122029** [sympy/sympy#24195]
Suppose I have the following code:
```py
import sympy as sp
x = sp.Symbol("x")
y = sp.Symbol("y")
print(sp.And(x <= y, x != y).simplify())

# Output:
# >>> x <= y
```
This is clearly incorrect. Could this be an issue with the simplifier?

**Comment by oscarbenjamin** [comment]
You need to use `Ne` rather than `!=`:
```
In [1]: x != y
Out[1]: True

In [2]: Ne(x, y)
Out[2]: x ≠ y
```

**Comment by u7122029** [comment]
If that's the case then I think the syntax is inconsistent. We are able to use other relational operators such as `==`, `<=`, `>=`, etc, but why not `!=`? Should I open another issue for this?

**Comment by oscarbenjamin** [comment]
The `==` and `!=` operators are for structural equality:
https://docs.sympy.org/latest/explanation/gotchas.html#equals-signs

This is because `==` and `!=` are used by Python container objects like `set`, `dict` etc.
