### ISSUE TITLE
fps (formal power series) and series issue

### ISSUE THREAD

**Issue by GodOfDeathSam** [sympy/sympy#24196]
Running the following code:
```
series(log(x),x,1)
```
Getting the following output:
![image](https://user-images.githubusercontent.com/87801374/198850195-1c3b817a-f21b-40f2-acd6-50875958dcb2.png)
First term should be (x-1) but it's coming to be -1
Same output when i try
```
fps(log(x),x,1).truncate()
```

**Comment by oscarbenjamin** [comment]
There is also an `x` term.
