### ISSUE TITLE
unable to solve trig functions

### ISSUE THREAD

**Issue by FedDragon1** [sympy/sympy#24207]
Hi all,

It seems the solver cannot correctly solve this expression:

```py
>>> x = Symbol("x")
>>> y = (x - 5) ** 2 + (sin(x) - sin(5)) ** 2
>>> solve(y)
[]
>>> solveset(y)
ConditionSet(x, Eq((x - 5)**2 + (sin(x) - sin(5))**2, 0), Complexes)
```

The solver gives me no result, where the actual result should be 5.

**Comment by smichr** [comment]
You can try `solve(y.args) -> [{x: 5}]` -- try when the terms of an expression can be separated additively in terms of generators (here `x` and `sin(x)`).

**Comment by FedDragon1** [comment]
@smichr Thank you! 
This does help - but only if the right hand of the equation is 0.
In other words, 
```py
>> (x - 5) ** 2 + (sin(x) - sin(5)) ** 2 - 0.5
>> solve(_.args)
[]
```
does not actually work when the results should be around −5.84505589 and −4.01827472.

**Comment by oscarbenjamin** [comment]
Most transcendental equations such as this cannot be solved analytically. You can use nsolve though:
```python
In [5]: nsolve((x - 5) ** 2 + (sin(x) - sin(5)) ** 2 - 0.5, -6)
Out[5]: 4.29432948444949
```
