### ISSUE TITLE
Mod sometimes contracts incorrectly with float factors

### ISSUE THREAD

**Issue by GinaMuuss** [sympy/sympy#24215]
With sympy version 1.11.1 I get: 

```python
from sympy.abc import phi
print(Mod(4.0*Mod(phi, 1) , 2))
print(Mod(4*Mod(phi, 1) , 2))
```
Observed behaviour:
```
0
2*(Mod(2*(Mod(phi, 1)), 1))
```
Expected behaviour:
Probably the latter, since 0 is just wrong for example for phi=0.9.

**Comment by oscarbenjamin** [comment]
There is an intermediate result that fails:
```
In [2]: Mod(2*(Mod(phi, 1)), 1)
Out[2]: 0
```
It goes wrong somewhere around here but the code is bizarrely complicated so I don't immediately see what the problem is:
https://github.com/sympy/sympy/blob/e8c22f6eac7314be8d92590bfff92ced79ee03e2/sympy/core/mod.py#L137-L151

**Comment by smichr** [comment]
cf #13581

**Comment by jksuom** [comment]
It seems that the piece of code above will handle `Mod(x*b, q)`, where `b = Mod(y, q)`, as follows if `a = Mod(x, q)` is not an instance of `Mod`:
Compute `a = Mod(x, q)` on line 139.
Append `a` to `non_mod` on line 146.
Compute `prod_mod = 1` on line 147.
Compute `prod_non_mod = a` on line 148.
Compute `prod_mod1 = y` on line 149.
Compute `net = y` on line 150.
Return `a*Mod(y, q) = a*b` on line 151.

We now have `x = a + n*q` for some integer `n`. It follows that `x*b = a*b + n*b*q`, so `Mod(x*b, q)` is `a*b` only if `n*b` is an integer.

**Comment by jksuom** [comment]
If `Mod(x, q)` is an instance of `Mod`, then `Mod(x*Mod(y, q), q)` becomes `Mod(x*y, q)`. This is not correct in general either.

We have `y = b + m*q`, where `b = Mod(y, q)` and `m` is an integer. It follows that `x*y = x*b + m*x*q`, so `Mod(x*y, q)` is `Mod(x*b, q) = Mod(x*Mod(y, q), q)` if and only if `m*x` is an integer.

If `p` has several factors that are instances of `Mod`, the result will also be wrong in general. For instance, if `p = a*b` where `a = Mod(x, q)` and `b = Mod(y, q)`, then `x = a + n*q` and `y = b + m*q` for some integers `n` and `m`. Hence

    x*y = a*b + a*m*q + b*n*q + n*m*q**2 = a*b + (a*m + b*n + n*m*q)*q

and therefore `Mod(a*b, q)` is the same as `Mod(x*y, q)` if and only is `a*m + b*n + n*m*q` is an integer.

Hence it seems that the denesting block starting on line 137 should also check that all factors of `p` as well as `q` are integers.

**Comment by praneethratna** [comment]
Do you mean the following change?
```diff
diff --git a/sympy/core/mod.py b/sympy/core/mod.py
index ec8b7156c1..3c84517166 100644
--- a/sympy/core/mod.py
+++ b/sympy/core/mod.py
@@ -134,7 +134,7 @@ def number_eval(p, q):
             for arg in p.args:
                 both_l[isinstance(arg, cls)].append(arg)

-            if mod_l and all(inner.args[1] == q for inner in mod_l):
+            if mod_l and all(inner.args[1] == q for inner in mod_l) and (t.is_Integer for t in p.args):
                 # finding distributive term
                 non_mod_l = [cls(x, q) for x in non_mod_l]
                 mod = []
```

**Comment by jksuom** [comment]
> (t.is_Integer for t in p.args)

`t.is_Integer` means that `t` is an instance of `Integer`. In a well-formed `Mul` object only one argument may be an Integer so this condition will never be satisfied. `t.is_integer` should be used instead. That will cover e,g, symbols like `n = Symbol('n', integer=True)`. Moreover, also `q` should be an integer.

**Comment by praneethratna** [comment]
For this change,
```diff
diff --git a/sympy/core/mod.py b/sympy/core/mod.py
index ec8b7156c1..487d28eab5 100644
--- a/sympy/core/mod.py
+++ b/sympy/core/mod.py
@@ -134,7 +134,7 @@ def number_eval(p, q):
             for arg in p.args:
                 both_l[isinstance(arg, cls)].append(arg)

-            if mod_l and all(inner.args[1] == q for inner in mod_l):
+            if mod_l and all(inner.args[1] == q for inner in mod_l) and all(t.is_integer for t in p.args) and q.is_integer:
                 # finding distributive term
                 non_mod_l = [cls(x, q) for x in non_mod_l]
                 mod = []
```
`Mod(Mod(x + 2, 4)*(x + 4), 4)` now returns `Mod((x + 4)*(Mod(x + 2, 4)), 4)` instead of `Mod(x*(x + 2), 4)` and 
`Mod(Mod(x + 2, 4)*4, 4)` now returns `4*(Mod(Mod(x + 2, 4), 1))` instead of `0`, are they the correct output?
