### ISSUE TITLE
Binomial Doesn't Evaluate as it Should

### ISSUE THREAD

**Issue by galvinograd** [sympy/sympy#24227]
**Description**

```python
n = var('n', Natural=True)

# return 0
Sum(0**(1-n) *  binomial(3, 2*n + 1), (n, 0, 1)).doit()

# return 1
Sum(0**(1-n) *  binomial(3, 2*n + 1), (n, 0, 1)).rewrite(factorial).doit()
```

**Environment**

 - Python 3.9.13
 - conda 22.9.0
 - sympy  1.10.1. py39h2804cbe_0  conda-forge
 - MacOS 13.0

**Comment by oscarbenjamin** [comment]
This was already fixed in e934618846f82e15368d2eeef1a8294c6917b8bd from #23962. The fix is in master but not yet released.

Current master behaviour:
```python
In [1]: Sum(0**(1-n) *  binomial(3, 2*n + 1), (n, 0, 1)).doit()
Out[1]: 1
```
