### ISSUE TITLE
Multivariable limit should be undefined, but gives unity.

### ISSUE THREAD

**Issue by galenseilis** [sympy/sympy#24225]
The following uses composition of single-variable limits, and gives unity.

```python
from sympy import *

y = Symbol('y', complex=True)
x = Symbol('x', complex=True)

f = (log(1 + x) + log(1 + y)) / (x + y)

print(limit(limit(f, x, 0, dir='+-'), y, 0, dir='+-'), limit(limit(f, y, 0, dir='+-'), x, 0, dir='+-'))
```

But it seems that there exist directions in which (0,0) can be approached that are not equal, so the multivariable limit is undefined.
- https://math.stackexchange.com/questions/4570653/help-with-this-2-variables-limit
- https://www.wolframalpha.com/input?i=lim+%28ln%281%2Bx%29%2Bln%281%2By%29%29%2F%28x%2By%29+at+%280%2C0%29

Is there a way to evaluate multivariable limits in SymPy?

**Comment by oscarbenjamin** [comment]
Multivariable limits are only defined if you choose how to approach the limit which you can do in the way shown in the SO question:
```python
In [1]: from sympy import *
   ...: 
   ...: y = Symbol('y', complex=True)
   ...: x = Symbol('x', complex=True)
   ...: 
   ...: f = (log(1 + x) + log(1 + y)) / (x + y)

In [2]: print(limit(limit(f, x, 0, dir='+-'), y, 0, dir='+-'), limit(limit(f, y, 0, dir='+-'), x, 0,
   ...: dir='+-'))
1 1

In [3]: alpha = symbols('alpha')

In [4]: f.subs(x, x+alpha*x**2).subs(y, -x+alpha*x**2)
Out[4]: 
   ⎛   2        ⎞      ⎛   2        ⎞
log⎝α⋅x  - x + 1⎠ + log⎝α⋅x  + x + 1⎠
─────────────────────────────────────
                     2               
                2⋅α⋅x                

In [5]: f.subs(x, x+alpha*x**2).subs(y, -x+alpha*x**2).limit(x, 0)
Out[5]: 
2⋅α - 1
───────
  2⋅α

In [6]: f.subs(y, 1/(1+x)-1).limit(x, 0)
Out[6]: 0
```
Note that it isn't just the "direction" that matters but also how "fast" each variable approaches the limit e.g. if one variable goes like $x^2$ another like $x$ then that can change the value of the limit. The iterated limits that you asked for are defined and `limit` gives the correct result. If you want to approach along a different path then you will need to specify the path as I showed above.
