### ISSUE TITLE
sympy.physics.vector.ReferenceFrame does not sympify

### ISSUE THREAD

**Issue by pbsds** [sympy/sympy#24230]
Sympy version: 1.11.1

Minimal repro:

```python
from sympy import symbols, sympify, collect
from sympy.physics.vector import *
N = ReferenceFrame('N')
x0, x1, x2 = symbols("x:3")
X = x0*N.x + x1*N.y + x2*N.z
sympify(X)
```

Fails with `ValueError: Error from parse_expr with transformed code: "Symbol ('x0' )*N .x +Symbol ('x1' )*N .y +Symbol ('x2' )*N .z "`

This has the consequence of breaking any library function which unconditionally uses `sympify`, such as `collect`. Example:

```python
collect(X.normalize(), 1/X.magnitude())
```

Possibly related? #8121 #6668

**Comment by moorepants** [comment]
By design, the objects in sympy.physics.vector are mutable and do not subclass from Basic and thus are not sympyfiable. It is expected behavior.

**Comment by oscarbenjamin** [comment]
@moorepants should this be closed then?

**Comment by moorepants** [comment]
Yes.
