### ISSUE TITLE
mypy tests failing

### ISSUE THREAD

**Issue by bertiewooster** [sympy/sympy#24231]
The [mypy test is producing five errors](https://github.com/sympy/sympy/actions/runs/3414593061/jobs/5682788659). They occurred in #24013 which does not modify these Python files, so I believe something else has changed.

```
sympy/core/evalf.py:1749: error: Incompatible default for argument "eps" (default has type "None", argument has type "Expr")  [assignment]
sympy/core/evalf.py:1750: error: Incompatible default for argument "options" (default has type "None", argument has type "Dict[str, Any]")  [assignment]
sympy/combinatorics/free_groups.py:96: error: Function "Type[Expr]" could always be true in boolean context  [truthy-function]
sympy/printing/smtlib.py:74: error: Incompatible default for argument "settings" (default has type "None", argument has type "Dict[Any, Any]")  [assignment]
sympy/printing/smtlib.py:434: error: Incompatible default for argument "symbol_table" (default has type "None", argument has type "Dict[Any, Any]")  [assignment]
```

**Comment by oscarbenjamin** [comment]
Does it depend on the mypy version? What version are you using?

**Comment by bertiewooster** [comment]
This is the automated tests upon a pull request, so it's automatically using this version:

```
Collecting mypy
  Downloading mypy-0.990-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (18.2 MB)
```

**Comment by oscarbenjamin** [comment]
How did you identify that https://github.com/sympy/sympy/pull/24013 was responsible? Is it possible that the difference is just the mypy version? (You should be able to see the version in the CI output.)

**Comment by oscarbenjamin** [comment]
Version 0.990 was only just released and so is now being used in CI:
https://pypi.org/project/mypy/#history

**Comment by Ishanned** [comment]
It is the same story for #24219. The tests passed for previous commit a day before, and the commit I made some hours ago fails the tests. The new commit, as is the case with #24013, does not modify the files that failed the test.

**Comment by asmeurer** [comment]
We should unrequire the mypy tests until this is resolved. That was the reason to have it in a separate build on CI.

**Comment by oscarbenjamin** [comment]
These things are not really that hard to fix. Example
```
sympy/core/evalf.py:1749: error: Incompatible default for argument "eps" (default has type "None", argument has type "Expr")  [assignment]
```
That's this line.
https://github.com/sympy/sympy/blob/eeb263cd04fbdd54a2fb245304afb88463f8ddb3/sympy/core/evalf.py#L1749-L1750
The type of `eps` has been declared as `Expr` but the default value is `None` which is not `Expr` so although mypy previously allowed it that's not a valid type hint.

**Comment by oscarbenjamin** [comment]
The fix here is probably just declaring the types to be e.g. `Optional[Expr]` rather than `Expr`. It's not hard to test this locally:
```console
$ pip install -U mypy
Requirement already satisfied: mypy in ./38venv/lib/python3.8/site-packages (0.950)
Collecting mypy
  Downloading mypy-0.990-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (17.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 17.9/17.9 MB 11.4 MB/s eta 0:00:00
Requirement already satisfied: typing-extensions>=3.10 in ./38venv/lib/python3.8/site-packages (from mypy) (4.0.1)
Requirement already satisfied: mypy-extensions>=0.4.3 in ./38venv/lib/python3.8/site-packages (from mypy) (0.4.3)
Requirement already satisfied: tomli>=1.1.0 in ./38venv/lib/python3.8/site-packages (from mypy) (1.2.3)
Installing collected packages: mypy
  Attempting uninstall: mypy
    Found existing installation: mypy 0.950
    Uninstalling mypy-0.950:
      Successfully uninstalled mypy-0.950
Successfully installed mypy-0.990

[notice] A new release of pip available: 22.2 -> 22.3
[notice] To update, run: pip install --upgrade pip
$ mypy sympy
sympy/utilities/lambdify.py:779: note: By default the bodies of untyped functions are not checked, consider using --check-untyped-defs  [annotation-unchecked]
sympy/utilities/lambdify.py:852: note: By default the bodies of untyped functions are not checked, consider using --check-untyped-defs  [annotation-unchecked]
sympy/utilities/lambdify.py:884: note: By default the bodies of untyped functions are not checked, consider using --check-untyped-defs  [annotation-unchecked]
sympy/core/evalf.py:1749: error: Incompatible default for argument "eps" (default has type "None", argument has type "Expr")  [assignment]
sympy/core/evalf.py:1749: note: PEP 484 prohibits implicit Optional. Accordingly, mypy has changed its default to no_implicit_optional=True
sympy/core/evalf.py:1749: note: Use https://github.com/hauntsaninja/no_implicit_optional to automatically upgrade your codebase
sympy/core/evalf.py:1750: error: Incompatible default for argument "options" (default has type "None", argument has type "Dict[str, Any]")  [assignment]
sympy/core/evalf.py:1750: note: PEP 484 prohibits implicit Optional. Accordingly, mypy has changed its default to no_implicit_optional=True
...
```
The message even suggests that there is a tool that can fix this automatically:
https://github.com/hauntsaninja/no_implicit_optional

**Comment by oscarbenjamin** [comment]
So 4 of the errors are to do with a change to the way that mypy checks optional arguments and are because of incorrect type hints in the codebase. They can be fixed with the tool I showed. 

The other error is pointing at this line:
https://github.com/sympy/sympy/blob/eeb263cd04fbdd54a2fb245304afb88463f8ddb3/sympy/combinatorics/free_groups.py#L96
That just looks like a bug to me.

**Comment by asmeurer** [comment]
I unrequired mypy tests to merge for now. Once we have these fixed we can re-require them. Although if this sort of thing happens a lot we might consider leaving them unrequired.

**Comment by oscarbenjamin** [comment]
> That just looks like a bug to me.

To be clear I mean that the SymPy code is buggy and mypy is correctly pointing that out.
