### ISSUE TITLE
Simultaneous equation solving issue

### ISSUE THREAD

**Issue by GodOfDeathSam** [sympy/sympy#24252]
I'm running the following code:
```
from sympy.abc import *
from sympy import *
L = x**2 + y**2 + z**2 - lamda*(x**2 + y**2 - z + 2+ s**2)
solve(L.diff(Matrix([x,y,z,lamda,s])))
```
and getting a different output from this code:
```
from sympy.abc import *
from sympy import *
L = x**2 + y**2 + z**2 - lamda*(x**2 + y**2 - z + 2+ a**2)
solve(L.diff(Matrix([x,y,z,lamda,a])))
```
All I've done is use the symbol s instead of a. I also tried checking ```ask(Q.zero(s))``` but it returned none. I don't know why using the symbol `s` doesn't show all the solutions
![image](https://user-images.githubusercontent.com/87801374/201497541-40696e24-6237-41c2-ae47-888ca63dc1c7.png)

**Comment by oscarbenjamin** [comment]
This seems to be already fixed on master by commit e934618846f82e15368d2eeef1a8294c6917b8bd from #23962
