### ISSUE TITLE
Why is there not a simply curve fitting method with Sympy?

### ISSUE THREAD

**Issue by NSC9** [sympy/sympy#24255]
Say I am looking at a pay chart:
```
If you have been at the company for 1 year you get $1
If you have been at the company for 2 years, you get $1.36
...
10 years, $5.76

...
100 years, $16.01
```
Why is there not a simple way to input this data and have Sympy return a curve of best fit expressed as an algebraic or transcendental function?

I know there are ways to do this with numpy, but they are complicated and require you to know what variables do what to manipulate the curve. It is not easy one-click or 'one sympy function call"

Ideally, I have a matrix A and i do from `sympy import curvefitter` and then do `curvefitter(A)` and Sympy will try to return an algebraic or transcendental function that best fits the data for my matrix.

Say the company does not tell me what they will pay me if I make it to year 150, how could I accurately compute and predict this value at year 150 if I know the pay per year for the first 100 years?

[potential relevant source](https://www.mathworks.com/matlabcentral/answers/179598-creating-a-matrix-for-each-point-point-in-a-data-set)

**Comment by bjodah** [comment]
There actually exists a tool which uses SymPy to achieve something very similar to what you describe:

https://github.com/MilesCranmer/PySR

And as you can tell by looking at how much effort has been put into that project, it is not quite as easy to solve in a general manner as one might guess.

Feel free to reopen this issue if needed.
