### ISSUE TITLE
Implementation of an inertia class

### ISSUE THREAD

**Issue by TJStienstra** [sympy/sympy#24257]
This issue is coupled to the experimental mechanics development described in #24234. Feel free to comment down below and suggest improvements or even discuss a different approach.

## Issue
Currently inertias are stored in a `tuple` in the format `(Dyadic, Point)`. While it is convenient to use a standard data type to store the location and the quantity, it can be confusing for the user to keep track of the order of arguments in these `tuples`.

## Solution
Therefore, the objective is to implement special class for the inertia. However here there are several considerations to keep in mind:
- It is preferred to keep it fully backward compatible, so the class should act as a `tuple`
  - This can be done by inheritance, however this will cause also operation as `__add__` to exist.
  - Implement `__getitem__`, so the main property of how a inertia is treated stays the same.
- The naming should remain clear. Currently there is already a `inertia` function to create a inertia `Dyadic`, so a class called `Inertia` would be confusing.

## Implementation
A new `inertia.py` file will be created, to which all inertia objects will be moved (solving the circular import problems with `functions.py`).
Below are a few coding examples of how the inertia class could look like:
### InertiaTuple with inheritance
```py
class InertiaTuple(tuple):
    def __new__(cls, point, dyadic):
        # Switch order if given in the wrong order
        if isinstance(dyadic, Point) and isinstance(point, Dyadic):
            point, dyadic = dyadic, point
        if not isinstance(point, Point):
            raise TypeError('Reference point should be of type Point')
        if not isinstance(dyadic, Dyadic):
            raise TypeError('Inertia value should be expressed as a Dyadic')
        return super().__new__(cls, (dyadic, point))

    @classmethod
    def from_tensor(cls, point, frame, ixx, iyy, izz, ixy=0, iyz=0, izx=0):
        return cls(point, inertia(frame, ixx, iyy, izz, ixy, iyz, izx))

    @property
    def point(self):
        return self[1]

    @property
    def dyadic(self):
        return self[0]
```
### Inertia with __getitem__
```py
class Inertia:
    def __init__(self, point, dyadic):
        # Switch order if given in the wrong order
        if isinstance(dyadic, Point) and isinstance(point, Dyadic):
            point, dyadic = dyadic, point
        if not isinstance(point, Point):
            raise TypeError('Reference point should be of type Point')
        if not isinstance(dyadic, Dyadic):
            raise TypeError('Inertia value should be expressed as a Dyadic')
        self._point = point
        self._dyadic = dyadic

    @classmethod
    def from_tensor(cls, point, frame, ixx, iyy, izz, ixy=0, iyz=0, izx=0):
        return cls(point, inertia(frame, ixx, iyy, izz, ixy, iyz, izx))

    @property
    def point(self):
        return self._point

    @property
    def dyadic(self):
        return self._dyadic

    def __getitem__(self, item):
        if item == 0:
            return self.dyadic
        elif item == 1 or item == -1:
            return self.point
        raise IndexError('Inertia index out of range.')
```

One could also argue for the mass and masscenter to be stored in this class as well. This would allow for things like a `parallel_axis` method to be implemented as well. So if you have a good proposal, feel free to comment it down below.

**Comment by moorepants** [comment]
Is a NamedTuple sufficient? or a DataClass?

**Comment by moorepants** [comment]
We never implemented this before because, mostly, of the idea that if you are adding a class for something that has so few properties and no methods, then it is probably overkill. Do you imagine other methods for this class?

Some other thoughts:

- Current methods/functions that except `(Point, Dyadic)` could accept `(Dyadic, Point)` also. That solves the issue of forgetting the order. We already do this in other locations with similar issues.
- Methods/functions could be adopted with key word arguments, i.e. `RigidBody(..., inertia_dyadic=Dyadic, inertia_point=Point)`.
- A NamedTuple could be a very simple way to associate a point and a dyadic.

Inertia is a property of a rigid body and it has several properties: 1) tensor basis, 2) scalars, 3) reference point. The Dyadic only contains 1 and 2. There isn't a mathematical way to include 3 (that I know of). So it does seem useful to have all 3 things grouped together.

I assume RigidBody() will accept tuples for inertia, as it always has, as well as any new class that lumps them together?

**Comment by TJStienstra** [comment]
`NamedTuple` or a `dataclass` could indeed also be used, while I would have to check whether you can easily force typing and maybe change order. The main point is that I would prefer dealing with parsing inertias in one location, so not every method has to take it into account saving us from possible bugs.

As for your last question, I would like something like the following:
`RigidBody(..., inertia=(P1, inertia(...))` -> `self._inertia = <InertiaClass>(P1, inertia(...))`
Note that here the entire type checking happens in the `<InertiaClass>`.

**Comment by TJStienstra** [comment]
@moorepants would you be pro having all magic methods of a `tuple` still implemented in this class, e.g. `__add__`?
