### ISSUE TITLE
Implementation of load classes

### ISSUE THREAD

**Issue by TJStienstra** [sympy/sympy#24258]
This issue is coupled to the experimental mechanics development described in #24234. Feel free to comment down below and suggest improvements or even discuss a different approach.

## Issue
Currently loads are stored in a `tuple` in the format `(location, Vector)`. While it is convenient to use a standard data type to store the location and the quantity, it can be confusing for the user to keep track of the order of arguments in these `tuples`. Also the fact that you have to check the type of the location to know whether you are dealing with a torque or a force is suboptimal.

## Solution
Therefore, the objective is to implement special class for the loads, using a `LoadBase` from which `Force` and `Torque` inherit. However here there are several considerations to keep in mind:
- It is preferred to keep it fully backward compatible, so the class should act as a `tuple`
  - However this would add a lot of functionality which is by no means expected. An example is `__add__`, e.g. `(P1, N.x) + (P1, N.y) = (P1, N.x, P1, N.y)`.
  - One can again use the `__getitem__` method to keep the most important property that was used in tact.

## Implementation
```py
class LoadBase(ABC):
    """Abstract base class for the various loading types."""

    def __init__(self, location, vector):
        self._location = self._get_location(location)
        self._vector = self._get_vector(vector)

    def __repr__(self):
        return f'Load(location={self.location}, vector={self.vector})'

    @staticmethod
    @abstractmethod
    def _generate_location(location):
        raise NotImplementedError

    @staticmethod
    @abstractmethod
    def _generate_vector(vector):
        raise NotImplementedError

    def __getitem__(self, item):
        if item == 0:
            return self.location
        elif item == 1 or item == -1:
            return self.vector
        raise IndexError('Load index out of range.')

    def __eq__(self, other):
        if isinstance(other, self.__class__) or (
            isinstance(other, tuple) and len(other) == 2):
            if self[0] == other[0]:
                return self[1] == other[1]
        return False

class Force(LoadBase):
        def __init__(self, point, force):
        super().__init__(point, force)

    def __repr__(self):
        return f'Force(point={self.point}, force={self.force})'

    @staticmethod
    def _generate_location(point):
        if isinstance(point, BodyBase):
            return point.masscenter
        if isinstance(point, Point):
            return point
        raise TypeError('Force location should of type Point.')

    @staticmethod
    def _generate_vector(force):
        if isinstance(force, Vector):
            return force
        raise TypeError('Force vector should be of type Vector.')

    @property
    def point(self):
        return self._location

    @property
    def force(self):
        return self._vector

class Torque(LoadBase):...
```

**Comment by TJStienstra** [comment]
In the implementation of loads, the same point about necessity applies as for the inertias as mentioned in [#24257 (comment)](https://github.com/sympy/sympy/issues/24257#issuecomment-1313481126).
A further question is whether methods as `__add__` should be supported, which have a nice meaning in loads. However here the question is what should happen if someone tries to add a force to a torque:
- Should it raise an error
- Should it return a list with both (or even not a list but a special class)
The same applies for two of the same kind of loads, e.g. forces, that are applied on different locations. This would result in something like the following:
```py
def __eq__(self, other):
    if isinstance(other, self.__class__) or (
        isinstance(other, tuple) and len(other) == 2):
        if self[0] == other[0]:
            return self[1] == other[1]
    return False

def __add__(self, other):
    other = _parse_load(other)  # converts a possible tuple to a load
    if isinstance(other, self.__class__):
        if self._location == other._location:
            return self.__class__(self._location,
                                  self._vector + other._vector)
        raise ValueError(f'{self._location} is a different load location as'
                         f' {other._location}.')
    else:
        raise ValueError(
            f'{type(self)} is a different load type as {type(other)}.')

def __radd__(self, other):
    return LoadBase.__add__(_parse_load(other), self)

def __sub__(self, other):
    other = _parse_load(other)
    return self.__add__(other.__class__(other._location, -other._vector))

def __rsub__(self, other):
    return LoadBase.__sub__(_parse_load(other), self)

def __mul__(self, other):
    return self.__class__(self._location, self[1] * other)

def __rmul__(self, other):
    return self.__class__(self._location, other * self[1])

def __truediv__(self, other):
    return self.__class__(self._location, self._vector / other)
```

**Comment by brocksam** [comment]
> However here the question is what should happen if someone tries to add a force to a torque:
> 
> * Should it raise an error

I vote we keep the return type consistent, in which case it makes most sense to raise an error here.
