### ISSUE TITLE
npartitions gives incorrect results

### ISSUE THREAD

**Issue by Pontus-vB** [sympy/sympy#24267]
```npartitions(n)``` gives incorrect results for n=1001, 1055, 1077, 1110, 1111, ... . The results are off by one, sometimes up, sometimes down. For example, ```npartitions(1001)``` gives 25032297938763929621013218349795 but the correct value ought to be 25032297938763929621013218349796. I checked against Sage, Pari, [OEIS](https://oeis.org/A000041), and [WolframAlpha](https://www.wolframalpha.com/input?i=partitions+of+1001).

Testing in [SageMathCell](https://sagecell.sagemath.org/?z=eJxtzLEKgzAQxvFd8B2ukwm0JTgK9ywhpTm5IZdwpoOI726x1slv-E8_Pk4la4VpTmVuG8oKAiygQcZoeuecHdoGvit-N7j3KSVo5cpZJiP2FGGMKJ_0iuoz-QvD9D-64c8PUJSlGuoEF1nv8GYiXA71OFC_dnYDHf85yQ==&lang=sage&interacts=eJyLjgUAARUAuQ==) with
```
import sympy
for n in range(2000):
    p_sympy=sympy.npartitions(n)
    p_sage=number_of_partitions(n)
    if p_sympy!=p_sage: print(f'n={n}, diff={p_sympy-p_sage:2}')
```
gives the output
```
n=1001, diff=-1
n=1055, diff= 1
n=1077, diff= 1
n=1110, diff= 1
n=1111, diff=-1
n=1259, diff= 1
n=1339, diff=-1
n=1373, diff=-1
n=1623, diff= 1
n=1636, diff= 1
n=1637, diff= 1
n=1662, diff= 1
n=1701, diff= 1
n=1703, diff=-1
n=1715, diff= 1
n=1729, diff=-1
n=1889, diff= 1
n=1903, diff= 1
```

**Comment by smichr** [comment]
What about a modification of `npartitions` like this:
```python
...
    prec = p = int(pbits*1.1 + 100)
    if int(0.24*n**0.5 + 4) > 10**5:
        raise ValueError("Input too big") # Corresponds to n > 1.7e11
    sq23pi = mpf_mul(mpf_sqrt(from_rational(2, 3, p), p), mpf_pi(p), p)
    sqrt8 = mpf_sqrt(from_int(8), p)
    q = 1
    rep = 0
    si = s = fzero
    while rep < 2:  # iterate until we get the same value 3 times in a row
        a = _a(n, q, p)
        d = _d(n, q, p, sq23pi, sqrt8)
        ad = mpf_mul(a, d)
        was = si
        s = mpf_add(s, ad, prec)
        si = to_int(s)
        if si == was:
            rep += 1
        else:
            rep = 0
        if verbose:
            print("step", q, to_str(a, 10), to_str(d, 10))
        # On average, the terms decrease rapidly in magnitude.
        # Dynamically reducing the precision greatly improves
        # performance.
        p = bitcount(abs(to_int(d))) + 50
        q += 1
    return int(to_int(mpf_add(s, fhalf, prec)))
```

**Comment by smichr** [comment]
Otherwise, a minimum of M=12 is needed to handle 1001 -- I didn't check other values.

**Comment by Pontus-vB** [comment]
@smichr With your modification I get incorrect results already for ```npartitions(356)```: 413766180933342363 vs the correct value 413766180933342362. I don't know the algorithm used in ```npartitions``` well enough, so I'm afraid I cannot help with the solution to this issue.

**Comment by asmeurer** [comment]
How do you test against OEIS? The page only seems to go up to n=49.

**Comment by ehren** [comment]
There's a "b-file" in the links section with 10000 terms: https://oeis.org/A000041/b000041.txt

**Comment by Pontus-vB** [comment]
That's how I discovered this bug - testing my python programs for various OEIS sequences against the b-files.

**Comment by Pontus-vB** [comment]
Experimenting a bit, replacing 0.24 with 0.26 in the line
```M = max(6, int(0.24*n**0.5 + 4))```
seems to work correctly up to at least n=25000. But it would of course be preferable to have a method that provably works for all n.

**Comment by oscarbenjamin** [comment]
SAGE has various functions for interacting with OEIS:
https://doc.sagemath.org/html/en/reference/databases/sage/databases/oeis.html

Perhaps SymPy could have a function for retrieving values for a particular OEIS sequence. That could then be used in some CI job.

**Comment by smichr** [comment]
I wonder if this is an example of SymPy trying to do things numerically that are better left to other tools (mpmath, FLINT, etc...). But how do you know which things are needed for symbolic work and which aren't?

**Comment by Pontus-vB** [comment]
@smichr Increasing the target value of ```rep``` in your modification seems only to delay the first incorrect result. The first values of n for which the result is incorrect are:
 - 356 with ```rep < 2```
 - 1636 with ```rep < 3```
 - 2532 with ```rep < 4```
 - 4477 with ```rep < 5```
 - 5106 with ```rep < 6```
 - 10231 with ```rep < 7```
 - 12526 with ```rep < 8```
 - 13051 with ```rep < 9```
 - 16402 with ```rep < 10```

**Comment by smichr** [comment]
Thanks for checking.

**Comment by maciejskorski** [comment]
Will try to dive deeper into it.

So the mistake appears for many arguments, but particularly [with `n=1001` under the default setup](https://sagecell.sagemath.org/?z=eJzLzC3ILypRKK7MLajk5cpTsFUwNDAw5OUqiAcL2YJJvbyCxKKSzJLM_LxijTxNsGxieqptXmluUmpRfH5aPJp8YnFxKtBUmCG2EPUACEkmvw==&lang=sage&interacts=eJyLjgUAARUAuQ==) of other params (if any)

**Comment by jksuom** [comment]
pari/gp seems to be using the same series but with a couple of more terms in https://pari.math.u-bordeaux.fr/cgi-bin/gitweb.cgi?p=pari.git;a=blob;f=src/modules/part.c;h=6060186bf8a14774fd9e4512d0e9db1b18083aad;hb=HEAD on line 25. So maybe we should have `0.24*n**0.5 + 6` instead of https://github.com/sympy/sympy/blob/e4c27fa9aec9eb642a2360a4f22f7a297410947a/sympy/ntheory/partitions_.py#L175

**Comment by maciejskorski** [comment]
> So maybe we should have `0.24*n**0.5 + 6` instead of

As per the literature, actually more. I gave the reference and the number in my post above.

**Comment by Pontus-vB** [comment]
I just now noted that there is another function for the number of partitions, ```sympy.functions.combinatorial.numbers.partition```, which seems to give correct results. This function computes the number of partitions recursively, keeping a list of all values computed so far.

Do we need both of these (maybe because one or the other performs better depending on the use case), or can we just replace the incorrect ```npartitions``` by ```partition```? Or better to proceed with #24293?

**Comment by smichr** [comment]
```
from time import *
t=time();ok=[npartitions(i) for i in range(1,1000)];print(time()-t)
from sympy.functions.combinatorial.numbers import partition
t=time();ok2=[partition(i) for i in range(1,1000)];print(time()-t)
```
This shows that `npartitions` takes nearly 200X longer than `partition` but it uses a caching mechanism whereas the npartitions is done in place. If M is less than some threshold, we should be using `partition`. Any ideas what is a good limit to use?
