### ISSUE TITLE
Not showing sin(360°) = 0 , showing -2.44929359829471e-16. How to fix it ? 

### ISSUE THREAD

**Issue by 1e9abhi1e10** [sympy/sympy#24262]
Hello everyone , I am beginner and got this issue please help!
`from mpmath import radians`
`from sympy import *`
`x = symbols("x")`
`expr1 = sin(x)`
`expr1.subs(x,radians(360))`
`-2.44929359829471e-16`

I am getting this instead of 0.
How to fix it?

**Comment by oscarbenjamin** [comment]
That's a rounding error because you are using the floating point `radians` function `mpmath`. Use SymPy's symbolic `rad` function instead:
```python
In [6]: from sympy import rad, sin

In [7]: rad(360)
Out[7]: 2⋅π

In [8]: sin(rad(360))
Out[8]: 0
```

**Comment by 1e9abhi1e10** [comment]
Thanks for quick answer!
