### ISSUE TITLE
Implementation of actuators

### ISSUE THREAD

**Issue by TJStienstra** [sympy/sympy#24264]
This issue is coupled to the experimental mechanics development described in #24234. Feel free to comment down below and suggest improvements or even discuss a different approach.

## Issue
It would be ideal to have an abstract base class representing a `Actuator`. This `Actuator` should represent two coupled loads acting upon two different bodies. Examples of actuators are springs, dampers, but a more complex actuator would for example be a muscle.

## Solution
TODO

## Implementation
TODO

**Comment by brocksam** [comment]
Having investigated the possibility of adding classes for a torsional linear spring and torsional linear damper (as subclasses of `TorqueActuator`), @TJStienstra and I have decided that this is a fools errand and not worth doing. To implement these classes neatly would require the angle between the `target_frame` and `reaction_frame` to be known. There is no neat way to determine the angle between frames so this would need to be passed as an extra argument by the user. If this is done then having a subclass provides no benefit as it results in a clunkier API. A torsional linear actuator can be instantiated using (an adaptation of) the following code:
```python
import sympy as sm
import sympy.physics.mechanics as me 

k = sm.Symbol('k')  # spring stiffness
theta = sm.Symbol('theta')  # equilibrium angle
q = me.dynamicsymbols('q')  # angle between frames
N = me.ReferenceFrame('N')
A = me.ReferenceFrame('A')
A.orient_axis(N, q, N.z)

torque = -k * (q - theta)
actuator = me.TorqueActuator(torque, N.z, N, A)
