### ISSUE TITLE
solve returns dict when dict=False

### ISSUE THREAD

**Issue by proy87** [sympy/sympy#24270]
`solve([2*z + 2*x, 4*z + 2*y, 2*x + 4*y - 7], x, y, z, dict=True)` returns `{x: 7/10, y: 7/5, z: -7/10}`. Just a dict, not a list of dicts.

**Comment by oscarbenjamin** [comment]
I can't reproduce this:
```python
In [2]: solve([2*z + 2*x, 4*z + 2*y, 2*x + 4*y - 7], x, y, z, dict=True)
Out[2]: [{x: 7/10, y: 7/5, z: -7/10}]
```

**Comment by proy87** [comment]
I'm sorry.
`solve([2*z + 2*x, 4*z + 2*y, 2*x + 4*y - 7], x, y, z, dict=False)` returns `{x: 7/10, y: 7/5, z: -7/10}`.

**Comment by oscarbenjamin** [comment]
I think that this is expected even though it is something that I personally find strange:
https://docs.sympy.org/dev/explanation/solve_output.html#single-dictionary

**Comment by proy87** [comment]
Very strange.
Thank you!

Should I close it?

**Comment by oscarbenjamin** [comment]
Yes, let's close this.

The behaviour of `solve` when used without `dict=True` is strange but changing it would break things.
