### ISSUE TITLE
There are (again) problems with auto_int_to_Integer in jupyter

### ISSUE THREAD

**Issue by appomsk** [sympy/sympy#24280]
Kernel is freezing with output in VS Code and browser notebooks, and with no any output in qtconsole. I checked it with Python 3.10.8 on Linux and Windows. 

Sample session in qtconsole:

```
Jupyter QtConsole 5.4.0
Python 3.10 (main, Sep  6 2022, 21:22:27) [GCC 12.2.0]
IPython 8.5.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from sympy import init_session

In [2]: init_session(quiet=1, auto_int_to_Integer=1)

In [3]: 1
Out[3]: 
```

There are no problems running this in IPython in terminal. And there are no problems with ``auto_symbols=1``.

**Comment by oscarbenjamin** [comment]
This is the error seen with running the above commands while jupyter is launched from the terminal:
```python
$ jupyter qtconsole
[IPKernelApp] ERROR | Exception in message handler:
Traceback (most recent call last):
  File "/home/oscar/current/sympy/sympy.git/38venv/lib/python3.8/site-packages/ipykernel/kernelbase.py", line 406, in dispatch_shell
    await result
  File "/home/oscar/current/sympy/sympy.git/38venv/lib/python3.8/site-packages/ipykernel/kernelbase.py", line 730, in execute_request
    reply_content = await reply_content
  File "/home/oscar/current/sympy/sympy.git/38venv/lib/python3.8/site-packages/ipykernel/ipkernel.py", line 394, in do_execute
    if res.error_before_exec is not None:
AttributeError: 'NoneType' object has no attribute 'error_before_exec'
```
I don't know whether that's a bug in jupyter or if it's a bug that something in sympy is returning None when it shouldn't.

**Comment by asmeurer** [comment]
> I don't know whether that's a bug in jupyter or if it's a bug that something in sympy is returning None when it shouldn't.

It's the latter. The fix is simple https://github.com/sympy/sympy/pull/24327. I have no idea how to add a test for it, though.
