### ISSUE TITLE
Can I get all the subgroup from a Permutation Groups?

### ISSUE THREAD

**Issue by dirocCen** [sympy/sympy#24332]
If I have a Permutation Groups liske this:
1 2 3 4
1 4 3 2
2 1 4 3
2 3 4 1
3 2 1 4
3 4 1 2
4 1 2 3
4 3 2 1

How can I enumerate all the subgroups?
I checked the methods "sympy.combinatorics.perm_groups.PermutationGroup.subgroup" and "sympy.combinatorics.perm_groups.PermutationGroup.subgroup_search". It seems could not get the result I want, is it possible?

**Comment by oscarbenjamin** [comment]
I think `subgroup_search` should do what you want. You haven't shown any code to create the group so I can't give a demonstration.

In any case GitHub issues are not supposed to be used for getting help with using SymPy. For that use the SymPy mailing list or StackOverflow.

**Comment by dirocCen** [comment]
Thanks for your reply. This question has been solved,  and I will be careful not to ask questions about usage on github issue later.
