### ISSUE TITLE
correct documentation for `interpolating_spline`

### ISSUE THREAD

**Issue by smichr** [sympy/sympy#24342]
The documentation says, about the `y` values: "list of strictly increasing integer values". This must have been a copy and paste error. While the `x` values must be strictly increasing, the `y` values need not be so. In fact, the first example shows a case where they are not and the second examples shows where there are repeated values. The `y` values are simply the `y` values for the corresponding `x` values. In addition, it does not appear that `x` or `y` values must be integers.

**Comment by harshagr70** [comment]
hey!! i would like to work upon this issue
