### ISSUE TITLE
underscore in name causing printing issue

### ISSUE THREAD

**Issue by ravi160822** [sympy/sympy#24345]
on Colab
```
from sympy import *

query = MatrixSymbol('query', 2, 2)
weightsquery = MatrixSymbol('weightsquery', 2, 2)
qw = Matrix(Matrix(query)*Matrix(weightsquery).transpose())
qw
```
<img width="1061" alt="Screenshot 2022-12-04 at 8 35 06 PM" src="https://user-images.githubusercontent.com/114392296/205498352-86ae8b36-8c01-46bb-a6ab-9357ee628c4a.png">

```
from sympy import *

query = MatrixSymbol('query', 2, 2)
weights_query = MatrixSymbol('weights_query', 2, 2)
qw = Matrix(Matrix(query)*Matrix(weights_query).transpose())
qw
```
<img width="1241" alt="Screenshot 2022-12-04 at 8 35 25 PM" src="https://user-images.githubusercontent.com/114392296/205498366-91e27dbc-3432-4c16-8de7-7cb8de12d1cc.png">

the output does not get displayed in latex on using `_` in names

**Comment by ThePauliPrinciple** [comment]
The output does get displayed, colab is just not converting it automatically to an image for some reason. I can render the latex code this produces perfectly fine outside of colab.

**Comment by ravi160822** [comment]
closing it here, have raised the same on Colab repo
