### ISSUE TITLE
quantity_simplify won't work across dimension with sympy.core.relational object for derived units

### ISSUE THREAD

**Issue by kompre** [sympy/sympy#24350]
Hello,

I have trouble evaluating a piecewise function which terms are quantity defined with different, but compatible, units. For what I gathered I should be able to use the function in `sympy.physycs.units.util.quantity_simplify()` with the arguments `across_dimensions=True, unit_system=SI` to work with different units, but it won't simplify if applied to a Piecewise function.

**(NOTE: writing this I discovered that the issue is more likely caused by quantity_simplify() not being able to work with the sympy.core.relational object that define the condition in the PIecewise function. More at the end)**

I've prepared a little example:

1. let's define a simple Piecewise function that will return a if a<b, otherwise it return b:
```
from sympy import *
import sympy.physics.units as u

var('a b')

p = Piecewise(
    (a, a<b),
    (b, True)
)
p
```
![image](https://user-images.githubusercontent.com/11796345/205864013-5bce19e7-981c-4c2c-ae9d-5247577ed4bb.png)

2. Now I use the `.subs()` method to evaluate the piecewise function, using different dimensions, but of the same type: 

```
p.subs({
    a: 1*u.cm,
    b: 2*u.m,
})
```
the Piecewise won't evaluate to a single value because it does not simplify `cm` and `m`:
![image](https://user-images.githubusercontent.com/11796345/205864777-39da51e2-c033-4914-b305-7d81f1eea688.png)

3. I apply then the quantity_simplify() method:
```
u.util.quantity_simplify(p.subs({
    a: 1*u.cm,
    b: 2*u.m,
}))
```
Now the piecewise has been properly evaluated to `a`, so the method works if the dimensions are of the same "type":
![image](https://user-images.githubusercontent.com/11796345/205865619-1bfa9ab1-2ed7-4be8-afdf-069749ab6481.png)

4. This stops working if I use derived units and mix them together. I've modified the above expressions to use `newton` and `kg*m/s**2` which dimensionally are the same:
```
u.util.quantity_simplify(p.subs({
    a: 1*u.N,
    b: 2*u.kg*u.m/u.s**2,
}))
```
Even if the expression make dimensionally sense, the piecewise function won't evaluate
![image](https://user-images.githubusercontent.com/11796345/205866347-12aac2a0-2600-482c-b034-582b715bfb7d.png)

5. Then I tried to use the args `across_dimensions` with the proper `unit_system`:
```
u.util.quantity_simplify(p.subs({
    a: 1*u.N,
    b: 2*u.kg*u.m/u.s**2,
}), across_dimensions=True, unit_system=u.systems.SI)
```
the output hasn't changed
![image](https://user-images.githubusercontent.com/11796345/205866901-4a42002b-d2e5-4129-9096-bdcd124201f0.png)

The issue seems to be the relational object, which `quantity_simplify()` seems not be able to work with; indeed if I isolate the just the relation:
```
r = 1*u.N < 2 * u.kg*u.m/u.s**2
print(type(r))
u.util.quantity_simplify(r, across_dimensions=True, unit_system=u.systems.SI)
```
The relation can't be evaluated:
![image](https://user-images.githubusercontent.com/11796345/205870801-992dd837-2337-4447-b1f5-9dcdcba1f4b3.png)

It is the same also for an equality:
```
f = Eq(1*u.N, 2*u.kg*u.m/u.s**2)
print(type(f))
u.util.quantity_simplify(f, across_dimensions=True, unit_system=u.systems.SI)
```
![image](https://user-images.githubusercontent.com/11796345/205871185-ad73fe73-1bc1-41f1-9435-d22987dd1d87.png)

I think the `across_dimension` flag is not passed to each side of the relational object, while the simplification works if the units are of the same "type":
```
r = 1*u.cm < 2 * u.m
print(type(r))
u.util.quantity_simplify(r)
```
![image](https://user-images.githubusercontent.com/11796345/205872535-f4a937e0-66a9-4f8f-a9e9-339139630ce4.png)

The workaround would be to call the `quantity_simplify()` to each term at `.subs()`, but it is kinda ugly...
```
qs = lambda x: u.util.quantity_simplify(x, across_dimensions=True, unit_system=u.systems.SI)

p.subs({
    a: qs(1*u.N),
    b: qs(2*u.kg*u.m/u.s**2),
})
```
![image](https://user-images.githubusercontent.com/11796345/205873780-60c40972-dc88-4762-aeb7-660c7456f423.png)

**Comment by 1e9abhi1e10** [comment]
[https://github.com/sympy/sympy/blob/master/sympy/physics/units/util.py#L154](url)
` quantity_simplify(expr, across_dimensions: bool=False, unit_system=None):`
in that function expr doesn't support relational

**Comment by kompre** [comment]
I found out the solutions to my issue: I don't have to use `quantity_semplify()` method, but I simply need to call the `convert_to()` with a suitable set of units in order to get the relational to simplify.

For general case I would set the base units of the unit system as `target_units`, so that it will simplify without any ambiguity:
```
# get the base units of the unit system
si = u.UnitSystem.get_default_unit_system()
print(si._base_units)

# apply convert to the piecewise function
u.convert_to(p.subs({
    a: 1*u.N,
    b: 2*u.kg*u.m*u.s**-2,
}), target_units = si._base_units)
```
![image](https://user-images.githubusercontent.com/11796345/208056889-79124dd7-2870-454a-ab28-16f092c3f91e.png)

If I want instead to display the result in a particular unit, I would have to pass the exact set of relevant unit:
```
u.convert_to(p.subs({
    a: 1*u.N,
    b: 2*u.kg*u.m*u.s**-2,
}), target_units = [u.N, u.m, u.kg])
```
![image](https://user-images.githubusercontent.com/11796345/208057454-6a316693-da4d-4dec-8c26-1aa90d9e20f7.png)

Probably it would be simpler to always pass the `_base_units` and then chain the result to the wanted unit:
```
# get the base units of the unit system
si = u.UnitSystem.get_default_unit_system()
print(si._base_units)

u.convert_to(
    u.convert_to(p.subs({
        a: 1*u.N,
        b: 200*u.kg*u.cm*u.s**-2,
    }), target_units = si._base_units),
    target_units = u.N
)
```
