### ISSUE TITLE
New User: Errors using Indexed expressions with diff and Sum while using codegen

### ISSUE THREAD

**Issue by a-jp** [sympy/sympy#24352]
Hi,

Very new to Sympy.  Hoping to generate a Sum of an indexed expression, then form a simple expression, and then take derivatives.  Finally, I'd like to output the solution using codegen. I'm really struggling, I suspect my use of Sum and or indexed expressions is wrong.  All help really appreciated:

```python
import sympy as sm

# would prefer to use the first one of these
#Ns = sm.symbols('Ns', cls=sm.Idx) # gives IndexError: tuple index out of range
Ns = 10 # gives FIXME: No specialized handling of type <class 'sympy.concrete.summations.Sum'>

sp = sm.Idx('sp', Ns)
S = sm.IndexedBase('S')[sp]
total = sm.Sum(S, sp)
#total = sm.Function('total')(sp) # gives FIXME: No specialized handling of type <class 'sympy.core.function.Derivative'>

# construct simple expression
func = sm.log(S/total)
print(func)

# derivative of Sum
d_total = total.diff(S)
print(d_total)

# derivative of expression
d_func = func.diff(S)
print(d_func)

# print
from sympy.utilities.codegen import codegen
codegen( [("func", func), ("dfunc", d_func)], language="C", prefix="test", to_files=True, header=False, empty=False)
```

**Comment by oscarbenjamin** [comment]
GitHub issues are for thinking about how to improve SymPy. If there is a feature request or a bug to report then say explicitly what that is. Otherwise for getting help with using SymPy you should use the mailing list or StackOverflow:
https://groups.google.com/g/sympy

I'm going to close this but it can be reopened if a concrete issue is described.

**Comment by asmeurer** [comment]
The issue here (as noted on the list) is that the code generators can't handle summations, which is https://github.com/sympy/sympy/issues/10194
