### ISSUE TITLE
Belongs summation

### ISSUE THREAD

**Issue by ravi160822** [sympy/sympy#24366]
<img width="532" alt="Screenshot 2022-12-11 at 6 35 49 AM" src="https://user-images.githubusercontent.com/114392296/206881638-c0831e20-1913-43ba-ba11-66226693dfc8.png">

I think this is not there currently

**Comment by oscarbenjamin** [comment]
Please explain in more detail what you are referring to or I suggest closing this issue.

**Comment by ravi160822** [comment]
how do I show the `belongs to` symbol in summation?
here k belongs to RELv

**Comment by ThePauliPrinciple** [comment]
That notation used there is rather condense, I'm not sure it's well defined unless you explain what these symbols are.

Maybe you can use something along the lines of

```python
from sympy import IndexedBase, Idx, Function, log, Symbol, Sum

g=Function('g')

REL = IndexedBase('REL')
n=Symbol('n')
k = Idx('k',n)

Sum(g(REL[k])/log(k+1),k)
```
to help you achieve what you want.
![afbeelding](https://user-images.githubusercontent.com/35560762/206895157-39692048-0229-4804-bd91-1fdab783951a.png)

But please, try to actually explain what you are asking about.
