### ISSUE TITLE
Issues with upgrading from SymPy 0.7.1 to 0.7.2, 0.7.3, or 0.7.4

### ISSUE THREAD

**Issue by petarmaric** [sympy/sympy#2439]
Hi, I'm the author of [beam_integrals](https://bitbucket.org/petar/beam_integrals), a project heavily reliant on SymPy. Our extensive test suite is demonstrating weird issues when upgrading from SymPy `0.7.1` to `0.7.2` or `0.7.3`.

What's causing these issues?
# Testing environments
## Ubuntu 10.04 32bit @ our Jenkins CI

| SymPy version | gmpy version | SYMPY USE CACHE | Tests pass? | Test run time | Details |
| --- | --- | --- | --- | --- | --- |
| 0.7.1 | not installed | **undefined** | YES | 17840.769s | http://ci.petarmaric.com/job/beam_integrals/49/ |
| 0.7.2 | not installed | **undefined** | **NO**, stopped | ~15 hours | http://ci.petarmaric.com/job/beam_integrals/50/ |
| 0.7.1 | 1.10-1 via Ubuntu package | **undefined** | YES | 15928.379s | http://ci.petarmaric.com/job/beam_integrals/51/ |

Notes:
1. These tests were performed before I was made aware of the memory leak caused by the SymPy internal caching issues, soon afterwards I've [patched our test suite](https://bitbucket.org/petar/beam_integrals/commits/5bcca1e) to avoid the memory leak
2. http://ci.petarmaric.com/job/beam_integrals/50/ has been stopped manually as it ate our entire RAM and most of the swap (memory leak due to SymPy internal caching issues, see previous note)
## Ubuntu 12.04 64bit @ DigitalOcean Cloud

| SymPy version | gmpy version | SYMPY USE CACHE | Tests pass? | Test run time | Test error details |
| --- | --- | --- | --- | --- | --- |
| 0.7.1 | not installed | no | YES | 10068.788s |  |
| 0.7.1 | 1.14-3build1 via Ubuntu package | no | YES | 7787.417s |  |
| 0.7.2 | not installed | no | YES | 8278.762s |  |
| 0.7.2 | 1.14-3build1 via Ubuntu package | no | **NO** | 368.534s | https://gist.github.com/petarmaric/6346863 |
| 0.7.3 | not installed | no | **NO** | 47966.926s | https://gist.github.com/petarmaric/6350717 |
| 0.7.3 | 1.14-3build1 via Ubuntu package | no | **NO** | 763.135s | https://gist.github.com/petarmaric/6351831 |
| 0.7.3 | 2.0.2 via source code install | no | **NO** | 810.033s | https://gist.github.com/petarmaric/6352787 |

Notes:
1. 3 droplets were created (sympy-0-7-1, sympy-0-7-2 and sympy-0-7-3) which were setup identically, with the exception of pinning the SymPy version, by editing `beam_integrals/requirements.txt` locally
2. gmpy2 was installed from source, based on the [official instructions](https://gmpy2.readthedocs.org/en/latest/intro.html#installing-gmpy2-on-unix-linux)
### How I've tested beam_integrals on DigitalOcean Cloud
1. Log into DigitalOcean Control Panel at https://www.digitalocean.com/login
2. Create a new Ubuntu 12.04 64bit Droplet with 2048 MB of RAM
   - Wait until the server is up and login as root
3. Update the system:
   
   ```
   aptitude update
   aptitude safe-upgrade
   ```
4. Install various system monitoring utilities:
   
   ```
   aptitude install htop iftop
   ```
5. Install the Ubuntu packages required to build and test beam_integrals:
   
   ```
   aptitude install build-essential python-dev mercurial python-pip
   ```
6. Install beam_integrals package in the "development" mode, along with the rest of its requirements:
   
   ```
   hg clone https://bitbucket.org/petar/beam_integrals
   cd beam_integrals
   python setup.py develop
   pip install -r requirements-test.txt
   ```
7. **[OPTIONAL]** It's strongly recommended to install gmpy. Without it code will still run correctly, but much slower at high precision. Install it as an Ubuntu package, to avoid  compiling it manually:
   
   ```
   aptitude install python-gmpy
   ```
8. Reboot the server, to apply kernel updates and clear disk cache from RAM (to start fresh)
   - Wait until the server is up and login as root
9. Run unit tests with SymPy internal caching disabled (see https://bitbucket.org/petar/beam_integrals/commits/5bcca1e for details):
   
   ```
   cd beam_integrals
   SYMPY_USE_CACHE=no python setup.py nosetests
   ```

**Comment by petarmaric** [comment]
I'm on sick leave (yay?), so I finally have some time to try and figure out which SymPy commit introduced a regression that caused beam_integrals tests to fail.

Please note, this is all done **without** gmpy installed and **without disabling** the SymPy internal cache.
If the variables:

* `gmpy_installed` (no, 1.x via Ubuntu package, 2.x via source code install) and

* `sympy_cache` (disabled, enabled but without the memory leak warning) 

were introduced it would result in way too many testing variations for me to handle right now.


# How to test beam_integrals on DigitalOcean Cloud


1. Log into DigitalOcean Control Panel at https://www.digitalocean.com/login

1. Create a new Ubuntu 14.04 64bit Droplet with 2048 MB of RAM
    * Wait until the server is up and login as root *// I know, I know... It's easy and I'm lazy and I'm very sick right now*

1. Update the system:

    ```
    aptitude update
    aptitude safe-upgrade
    ```

1. Install the Ubuntu packages required to build and test beam_integrals and SymPy:

    ```
    aptitude install build-essential python-dev mercurial git python-pip
    ```

1. Install beam_integrals package in the "development" mode, along with the rest of its requirements:

    ```
    hg clone https://bitbucket.org/petar/beam_integrals ~/beam_integrals
    cd ~/beam_integrals
    python setup.py develop
    pip install -r requirements-test.txt
    ```

1. Remove the SymPy 0.7.1 package that beam_integrals installed as its dependency:

    ```
    pip uninstall sympy
    ```

1. Clone the SymPy repository:

    ```
    git clone git://github.com/sympy/sympy.git ~/sympy
    ```

1. Switch over to SymPy 0.7.1 and install it in the "development" mode:

    ```
    cd ~/sympy
    git checkout sympy-0.7.1
    pip install -e .
    ```

1. Make sure SymPy 0.7.1 works correctly:

    ```
    cd ~/sympy
    ./bin/test
    ./bin/doctest
    ```

1. Reboot the server, to apply kernel updates and clear disk cache from RAM (to start fresh)
    * Wait until the server is up and login as root

1. Run the entire beam_integrals test suite for SymPy 0.7.1 (merely a sanity test), without disabling the SymPy internal cache
   (see https://bitbucket.org/petar/beam_integrals/commits/5bcca1e and https://github.com/sympy/sympy/issues/2439#issuecomment-23942357 for details):

    ```
    cd ~/beam_integrals
    IGNORE_SYMPY_MEMORY_LEAK=yes python setup.py nosetests
    ```


# Using beam_integrals to find a regression in SymPy > 0.7.1


From now on we'll only run tests within `tests.characteristic_equation_solvers.test_solvers`
(as the full beam_integrals test suite takes almost 2 hours to complete), in stop-on-failure mode and with generally lowered verbosity:

1. Save this in `~/test.sh`:

    ```
    #!/bin/bash
    (cd ~/beam_integrals && IGNORE_SYMPY_MEMORY_LEAK=yes MPMATH_NOGMPY=yes python setup.py -q nosetests -x --tests tests.characteristic_equation_solvers.test_solvers)
    ```
   
1. And make the `~/test.sh` executable:

    ```
    chmod +x ~/test.sh
    ```

1. To further decrease the reporting verbosity and also disable coverage plugins please remove the `~/beam_integrals/setup.cfg` file:

    ```
    rm ~/beam_integrals/setup.cfg
    ```

Verify that SymPy 0.7.1 is "good" and SymPy 0.7.6 is "bad":

1. Switch over to SymPy 0.7.6 to make sure tests fail:

    ```
    cd ~/sympy
    git checkout sympy-0.7.6
    ~/test.sh
    ```

1. Switch over to SymPy 0.7.1 to make sure tests still pass:

    ```
    cd ~/sympy
    git checkout sympy-0.7.1
    ~/test.sh
    ```

Now let's use `git bisect` to figure out which commit introduced a regression between SymPy 0.7.1 and 0.7.6:

```
cd ~/sympy
git bisect start sympy-0.7.6 sympy-0.7.1
git bisect run ~/test.sh
git bisect reset
```


# The results


It seems b84674d is the commit that introduced this regression.
Full `git bisect` output can be found at https://gist.github.com/petarmaric/5985ad8674247e0de78a

I've also ran `~/test.sh` against the current master (50b4f3d ATM)

```
cd ~/sympy
git checkout master
pip install mpmath
~/test.sh
```

and, unfortunately, the tests still fail:

```
root@sympy-beam-ingrals-test:~/sympy# ~/test.sh
F
======================================================================
FAIL: tests.characteristic_equation_solvers.test_solvers.test_find_best_root(1, 1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/beam_integrals/nose-1.3.4-py2.7.egg/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/root/beam_integrals/tests/characteristic_equation_solvers/test_solvers.py", line 31, in check_find_best_root
    assert_less_equal(mu_m_error, t.MAX_ERROR_TOLERANCE)
AssertionError: 0.00000000000000032162452993532729844684607400882247424678888277467224259784769572226917549479169303989821176790032008305968824678769927238903329590530768150168932 not less than or equal to 1e-16

----------------------------------------------------------------------
Ran 1 test in 0.392s

FAILED (failures=1)
```

If it's worth anything, the current master generates the AssertionError with the number:

```
0.00000000000000032162452993532729844684607400882247...932
```

while **all** of the `git bisect` "bad" commits (https://gist.github.com/petarmaric/5985ad8674247e0de78a) return:

```
0.00000000000000012246467991473531772260659322749979...412
```

I've tried @cbm755 suggestion from https://github.com/sympy/sympy/issues/8821#issuecomment-70229490 to try his merge request #8826, but it resulted in the **exact** same failure as for the current master (50b4f3d ATM):

```
root@sympy-beam-ingrals-test:~/sympy# ~/test.sh
F
======================================================================
FAIL: tests.characteristic_equation_solvers.test_solvers.test_find_best_root(1, 1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/beam_integrals/nose-1.3.4-py2.7.egg/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/root/beam_integrals/tests/characteristic_equation_solvers/test_solvers.py", line 31, in check_find_best_root
    assert_less_equal(mu_m_error, t.MAX_ERROR_TOLERANCE)
AssertionError: 0.00000000000000032162452993532729844684607400882247424678888277467224259784769572226917549479169303989821176790032008305968824678769927238903329590530768150168932 not less than or equal to 1e-16

----------------------------------------------------------------------
Ran 1 test in 0.375s

FAILED (failures=1)
```

**Comment by petarmaric** [comment]
Can't prove it right now, but I have a "feeling" that this line https://github.com/sympy/sympy/commit/b84674d6ee847b352d0676f15be88e7e8ebedf10#diff-6cd5274897d73197c25bc41e9afe63e4R565 (L565-L566) is causing issues with https://bitbucket.org/petar/beam_integrals/src/9a74e91d5a5f50e2639a7e3aeb6de9a486d6e59d/beam_integrals/characteristic_equation_solvers.py?at=default#cl-46 (see the comment on L50-L51)

**Comment by asmeurer** [comment]
@smichr that was your commit.

**Comment by cbm755** [comment]
@petamaric: if you're right, my change in #8826 won't help because the new path still runs that same code (as you've already discovered).

**Comment by cbm755** [comment]
> Can't prove it right now, but I have a "feeling" that ...

@petarmaric one way to "prove" it would be a minimum (non)-working example---several lines of code that demonstrate what does wrong.  I expect you're in a better position that we are to do this, as you (obviously) understand the `beam_integrals` code better.

This would go a long way to getting this resolved!

**Comment by petarmaric** [comment]
@cbm755 ask and ye shall receive

I've created [a gist](https://gist.github.com/petarmaric/09480183061f5c7fb7e7) with a minimal working example showcasing which SymPy versions/commits are causing beam_integrals tests to fail. As an added bonus, the code has no external dependencies besides SymPy itself.

The testing environment was based on instructions in https://github.com/sympy/sympy/issues/2439#issuecomment-70339616

The results are very interesting:

1. SymPy v0.7.1 - PASS. All `mpmath_root` and `sympy_root` pairs are the same.

1. SymPy v0.7.6 - FAIL. All `mpmath_root`'s are equal to their values from SymPy v0.7.1. However `sympy_root`'s get **zero-clipped at about the 39th decimal**, independent of `decimal_precision` used.

1. SymPy b84674d - FAIL. Same problem as with SymPy v0.7.6

1. SymPy 829bc1b (parent commit of b84674d) - PASS. Same results as with SymPy v0.7.1

IMO, this pretty much proves that b84674d introduced a regression.

**Comment by petarmaric** [comment]
If we remove the context, we can make the minimal working example even shorter:

```python
>>> from sympy import mpmath, Float

>>> text = '3.141592653589793238462643383279502884197169399375105820974944592307816406286208998628034825342117068'
>>> decimal_precision = 100

>>> mpmath.mp.dps = decimal_precision

>>> mpmath_num = mpmath.mpf(text)
>>> sympy_num = Float(mpmath_num, decimal_precision)

>>> print "mpmath_num = %s\nsympy_num  = %s" % (mpmath_num, sympy_num)
mpmath_num = 3.141592653589793238462643383279502884197169399375105820974944592307816406286208998628034825342117068
sympy_num  = 3.141592653589793115997963468544185161590576171875000000000000000000000000000000000000000000000000000
```

This test was done with SymPy 0.7.5 on Python 2.7.8 win-amd64 |Anaconda 2.1.0 (64-bit)|

**Comment by petarmaric** [comment]
In fact, after close inspection of the results discussed in my previous 2 comments I noticed something even more interesting:

```python
>>> from sympy import mpmath, Float

>>> text = '3.141592653589793238462643383279502884197169399375105820974944592307816406286208998628034825342117068'
>>> decimal_precision = 100

>>> mpmath.mp.dps = decimal_precision

>>> mpmath_num = mpmath.mpf(text)
>>> sympy_num = Float(mpmath_num, decimal_precision)

>>> print "mpmath_num = %s\nsympy_num  = %s" % (mpmath_num, sympy_num)
mpmath_num = 3.141592653589793238462643383279502884197169399375105820974944592307816406286208998628034825342117068
sympy_num  = 3.141592653589793115997963468544185161590576171875000000000000000000000000000000000000000000000000000

>>> diff = mpmath_num - sympy_num
>>> print diff
0.0000000000000001224646799147353177226065932275001058209749445923078164062862089986280348253421170680078538784935795

>>> print mpmath.log10(diff)
-15.91198914827844864114174208533867293255232912230592779427060130266807642186107421296808278366048327
```

It seems not only are the SymPy values getting zero-clipped at about the 39th decimal, but there are also digit-level inaccuracies long before that.

Judging from the `diff` I'd say they are introduced at about the 16th decimal, and `log10` of the `diff` is about 15.9 which [looks suspiciously familiar](http://en.wikipedia.org/wiki/Floating_point#Internal_representation)... Something in `sympy.Float` seems to be lowering it's numeric precision to the level of `float64`, independent of high of a decimal precision is used.

**Comment by cbm755** [comment]
Thanks @petarmaric "context-free" is exactly what I meant.  This does look like a bug in creating a Float from an mpf object: probably intermediate result converted to double precision.  I'll take a look into this.

Note that `sympify(mpmath_num)` should work if that helps you work around.

**Comment by cbm755** [comment]
Have to do something else now, here's what I've found so far...

>  IMO, this pretty much proves that b84674d introduced a regression.

Could be.  As I think you mentioned earlier, ln 565 causes mpf input to eventually get to this line:

````
                      _mpf_ = mpmath.mpf(
                        S.NegativeOne**num[0]*num[1]*2**num[2])._mpf_
````

This creates a 15 digit Float (that is it calls Float again to do the `num[1]*2**num[2]` bit).

Deleting this bit:
````
elif isinstance(num, mpmath.mpf):
    num = num._mpf_
````
sort of helps with your problem:
````
mpmath.mp.dps = 100
a = mpmath.mpf(str(pi.evalf(128)))
sin(a)    % good, 2.8689e-102
b = Float(a, 100)
sin(b)    % good, 2.86889280175964e-102
````

Note however:
````
c = Float(a)
srepr(c)   % but this has the wrong prec
"Float('3.1415926535897932', prec=15)"
````
I tihnk this is because `c` just copied the mpf object... and technically it does have 15 digits of precision so it follows spec.  @smichr may have been trying to avoid this "problem", based on his tests.

Perhaps the right fix is `S.NegativeOne**num[0]*num[1]*2**_sympify(num[2]))._mpf_`, that is to `_sympify()` the exponent to prevent Python `float` from coming from `2**<int>`.  It bothers me that this line makes a Float internally.

More later (couple days at least), but if @smichr has ideas go for it.

**Comment by petarmaric** [comment]
@cbm755 this is turning into a quite interesting discussion, thanks for the effort so far.

>  It bothers me that this line makes a *Float* internally.

Sorry, but I'm not sure if you meant Python float or SymPy **F**loat here?

> I tihnk this is because  `c`  just copied the mpf object... and technically it does have (at least) 15 digits of precision so it follows spec. @smichr may have been trying to avoid this "problem", based on his tests.

I solve most of these issues in `beam_integrals` by forcing a `decimal_precision` kwarg onto all functions performing numerical computations, to control the decimal precision explicitly between any API calls.
Is there a reason that this mpmath call ` _mpf_ = mpmath.mpf(S.NegativeOne**num[0]*num[1]*2**num[2])._mpf_` is:

1. done with the mixed SymPy/Python/mpmath eval and not pure mpmath code, i.e. using `mpmath.power()` instead of `2**num[2]`?

1. doing computations in the mpmath default context precision, and not using the `prec` arg already provided within its owner `Float.__new__(cls, num, prec=15)` to create a local mpmath context via `mpmath.workdps()` before any mpmath related computations commence? I ask because `mpmath.mpf()` gives different results depending on the mpmath context:

```py
>>> from sympy import mpmath

>>> mpmath.mpf('1/3')
mpf('0.33333333333333331')

# Changing the mpmath context gives different results
>>> mpmath.mp.dps = 50
>>> mpmath.mpf('1/3')
mpf('0.33333333333333333333333333333333333333333333333333311')

# Forcing a Python float here is not a very good idea
>>> mpmath.mpf(1/3.0)
mpf('0.33333333333333331482961625624739099293947219848632813')
```

**Comment by cbm755** [comment]
Well it does both: `2**num[2]` makes a Python float and then S.NegativeOne stuff makes a SymPy Float.  Then it converts the SymPy Float to an `mpf`, then finally to a SymPy Float.   At very least, this is sub-optimal.

Your point 1. sounds reasonable.  Maybe try to patch it and see if it fixes anything?  Sorry I don't understand your point 2., probably because I've not dug deep enough into this code yet.

--------------------------------------------------------

We have the minimal nonworking example, so just need someone to dig it and fix it now.

This is a long thread.  For the benefit of others who might get here, here the minimal nonworking example (or https://github.com/sympy/sympy/issues/2439#issuecomment-70603659)
````
mpmath.mp.dps = 100
a = mpmath.mpf(str(pi.evalf(128)))  # a is 100 digit pi in mpf format
sin(a)    # good, 2.8689e-102
b = Float(a, 100)   # bad, b has only 15 digits precision
sin(b)
0.000000000000000122464....
````
I think you should change the title to "loss in precision when converting mpf to Float".

**Comment by cbm755** [comment]
@petarmaric a further thought: if you'd like to help but don't have time to really dive into the code, a PR for an "@xfail" test of the minimal nonworking example would probably be well-received!

**Comment by petarmaric** [comment]
RE point 2: currently all mpmath related code within `Float.__new__()` is executed in the mpmath default context. I might be in a situation where I want to keep the mpmath default context precision low (say 25 decimals) yet I wish to create a new `sympy.Float` at high precision (say 300 decimals).
As the code is right now any mpmath calls within ` Float.__new__(cls, num, prec) ` would be executed at 25 decimals instead of the desired 300 decimals. To amend this we should maybe build a new, local, mpmath context (i.e. via `mpmath.workdps()`)  at the start of `Float.__new__()` and set it's decimal precision to `prec`. Anything else is bound to create accuracy issues, like the one shown in the code sample above.

RE changing the title: I may be in favor of creating a new issue instead whilst keeping this one open, as my original tests on top of this issue have shown there may be even more problems with SymPy > 0.7.1 (i.e. https://gist.github.com/petarmaric/6346863).

RE `@xfail` test: Sure, any documentation on how this is done?

**Comment by cbm755** [comment]
Sure new issue fine with me: it is nicely self contained.  CC me.

Re: @xfail documentation, I'm not sure.  But for example, look in `sympy/core/tests/test_evalf.py`, `sympy/core/tests/test_numbers.py`.  Basically write the test that should pass and then put `@XFAIL` before it:

````
@XFAIL
def test_float_from_mpf_issue_xxxx()
    ....
````
where xxxx is the new issue number.

**Comment by cbm755** [comment]
> ... where I want to keep the mpmath default context precision low (say 25 decimals) yet I wish to create a new sympy.Float at high precision (say 300 decimals).

Minimal nonworking example please?

**Comment by cbm755** [comment]
> RE @xfail test: Sure, any documentation on how this is done?

Oops, maybe I only answered the `@XFAIL` part of this, more generally:
https://github.com/sympy/sympy/wiki/Development-workflow

**Comment by jcrist** [comment]
ping @cbm755 , @petarmaric : what is the status of this?

**Comment by cbm755** [comment]
Maybe there are more issues here but I summarized my view here: https://github.com/sympy/sympy/issues/2439#issuecomment-70807571

@petarmaric do you have time to work on this?  If not, let us know.  Re-reading the above, my suggestions were:
    1.  File new issue for https://github.com/sympy/sympy/issues/2439#issuecomment-70807571.  
    2.  Make PR for XFAIL test.

**Comment by petarmaric** [comment]
@jcrist, @cbm755: I'd love to work on this, but I'm afraid I won't have any spare time till October, as I'm split between spending time with my newborn and working the PhD thesis.

I think it may be for the best to open a new issue, and once it is fixed I'll use beam_integrals tests to check again if there are more regressions in SymPy > 0.7.1

**Comment by oscarbenjamin** [comment]
The minimum working example described above now works fine:
```julia
In [13]: import mpmath                                                                                                            

In [14]: mpmath.mp.dps = 100 
    ...: a = mpmath.mpf(str(pi.evalf(128)))  # a is 100 digit pi in mpf format 
    ...: sin(a)    # good, 2.8689e-102 
    ...: b = Float(a, 100)   # bad, b has only 15 digits precision 
    ...: sin(b)                                                                                                                   
Out[14]: 2.8689e-102
```

Can anyone summarise what exactly is still to fix here?

**Comment by smichr** [comment]
> I think you should change the title to "loss in precision when converting mpf to Float".
> Can anyone summarise what exactly is still to fix here?

As you have confirmed, the loss of precision when converting mpf to Float has been resolved.
