### ISSUE TITLE
sympy.physics.units doesn't support Temperature scales

### ISSUE THREAD

**Issue by 1e9abhi1e10** [sympy/sympy#24405]
I am wondering that `sympy.physics.units` don't support temperature units.
Would it be a solution to be able to enter values as Celsius (Fahrenheit) and then automatically convert them to Kelvin?
Not understand how these should be implemented.
Can we make`convert_from_Celsius` and `convert_to_Celsius` functions that make things easy

**Comment by smichr** [comment]
see #13379 and ref to PR that proposed a solution

**Comment by bjodah** [comment]
Yes, this is a very well known issue with any system handling temperature scales. @1e9abhi1e10, let us know if you make progress on this issue. Closing for now.
