### ISSUE TITLE
 KaTeX parse error when displaying cross derivatives.

### ISSUE THREAD

**Issue by marcdelabarrera** [sympy/sympy#24400]
I'm trying to display the cross derivative of a general function `f` in VSCode.
```
x, y = sym.symbols('x, y')
f = Function('f')(x,y)
f.diff(x_hat,y_hat)
```
I get a `ParseError: KaTeX parse error: Double subscript at position 91: …2}}{\partial _x_̲ss*exp(\hat{x})…`.

It seems `sympy` is taking the correct derivative (I can see it if I use `print(f.diff(x_hat,y_hat))`, but not if I try to `display` it using a Jupiter Notebook. 

Is this behaviour expected? I'm using ```sympy 1.10.1```

**Comment by oscarbenjamin** [comment]
The code doesn't run because of missing imports and symbols not being defined.

If `latex(f.diff(x_hat,y_hat))` gives valid LaTeX then this is most likely a bug in Jupyter or something else rather than SymPy.

**Comment by asmeurer** [comment]
I think this isn't valid LaTeX, but it's impossible to know the source of the problem without seeing your symbol definitions.

**Comment by asmeurer** [comment]
Most likely the issue is your symbol names are not valid LaTeX. This is something that's been brought up before. Ideally the latex printer would automatically escape such things, but doing so requires a bit of work.

**Comment by marcdelabarrera** [comment]
Indeed, thank you, indeed is not problem of sympy. My simbols are '\hat{x}' and it seems it has problems with the '\hat{}' and the cross derivatives. With standard symbols it works.

**Comment by asmeurer** [comment]
Like I said, it's kind of a bug if the LaTeX printer generates invalid LaTeX. This is likely just a duplicate of https://github.com/sympy/sympy/issues/14718, which should be fixed by https://github.com/sympy/sympy/pull/15939, but again, it's impossible to know for sure unless you give us the exact code that generates that expression.
