### ISSUE TITLE
After going through as_set(), the boundary of "LessThan" becomes open.

### ISSUE THREAD

**Issue by chisakiShinichirouToshiyuki** [sympy/sympy#24412]
``` py
import sympy

x = sympy.var('x')
ne = sympy.Ne(x, 2)
ineq = x<=3
complex_condition = ineq1 & ne


print(complex_condition)
# Output: (x <= 3) & Ne(x, 2)

print(complex_condition.as_set())
# Output: Union(Interval.open(-oo, 2), Interval.Lopen(2, 3))

print(complex_condition.as_set().as_relational(x))
# Expected output: (x > -oo) & (x <= 3) & Ne(x, 2)
# Actual output: (x > -oo) & (x < 3) & Ne(x, 2)


```

**Comment by oscarbenjamin** [comment]
The quick fix is that the code here should be changed to check whether the intervals are closed or open at the other ends:
https://github.com/sympy/sympy/blob/9b9f5bde7d2c622de4f39cdd96cc5cd88e5f1006/sympy/sets/sets.py#L1418-L1425
Something like this:
```diff
diff --git a/sympy/sets/sets.py b/sympy/sets/sets.py
index 2068175..d7ea77f 100644
--- a/sympy/sets/sets.py
+++ b/sympy/sets/sets.py
@@ -1419,10 +1419,16 @@ def as_relational(self, symbol):
                 all(isinstance(i, Interval) for i in self.args)):
             # optimization to give 3 args as (x > 1) & (x < 5) & Ne(x, 3)
             # instead of as 4, ((1 <= x) & (x < 3)) | ((x <= 5) & (3 < x))
+            #
+            # XXX: This should be ideally be improved to handle any number of
+            # intervals and also not to assume that the intervals are in any
+            # particular sorted order.
             a, b = self.args
-            if (a.sup == b.inf and
-                    not any(a.sup in i for i in self.args)):
-                return And(Ne(symbol, a.sup), symbol < b.sup, symbol > a.inf)
+            if a.sup == b.inf and a.right_open and b.left_open:
+                mincond = symbol > a.inf if a.left_open else symbol >= a.inf
+                maxcond = symbol < b.sup if b.right_open else symbol <= b.sup
+                necond = Ne(symbol, a.sup)
+                return And(necond, mincond, maxcond)
         return Or(*[i.as_relational(symbol) for i in self.args])
 
```
A better fix would be to rewrite this with a routine that can take any number of intervals as a subset of the args and merge them iteratively.

**Comment by 1e9abhi1e10** [comment]
> The quick fix is that the code here should be changed to check whether the intervals are closed or open at the other ends:
> 
> https://github.com/sympy/sympy/blob/9b9f5bde7d2c622de4f39cdd96cc5cd88e5f1006/sympy/sets/sets.py#L1418-L1425
> 
> 
> Something like this:
> ```diff
> diff --git a/sympy/sets/sets.py b/sympy/sets/sets.py
> index 2068175..d7ea77f 100644
> --- a/sympy/sets/sets.py
> +++ b/sympy/sets/sets.py
> @@ -1419,10 +1419,16 @@ def as_relational(self, symbol):
>                  all(isinstance(i, Interval) for i in self.args)):
>              # optimization to give 3 args as (x > 1) & (x < 5) & Ne(x, 3)
>              # instead of as 4, ((1 <= x) & (x < 3)) | ((x <= 5) & (3 < x))
> +            #
> +            # XXX: This should be ideally be improved to handle any number of
> +            # intervals and also not to assume that the intervals are in any
> +            # particular sorted order.
>              a, b = self.args
> -            if (a.sup == b.inf and
> -                    not any(a.sup in i for i in self.args)):
> -                return And(Ne(symbol, a.sup), symbol < b.sup, symbol > a.inf)
> +            if a.sup == b.inf and a.right_open and b.left_open:
> +                mincond = symbol > a.inf if a.left_open else symbol >= a.inf
> +                maxcond = symbol < b.sup if b.right_open else symbol <= b.sup
> +                necond = Ne(symbol, a.sup)
> +                return And(necond, mincond, maxcond)
>          return Or(*[i.as_relational(symbol) for i in self.args])
>  
> ```
> 
> A better fix would be to rewrite this with a routine that can take any number of intervals as a subset of the args and merge them iteratively.

I checked it , it works! 
Opened a [PR](https://github.com/sympy/sympy/pull/24414)

**Comment by oscarbenjamin** [comment]
We should wait until the PR is actually merged before closing the issue. I have now merged the PR though so this can stay closed.

**Comment by chisakiShinichirouToshiyuki** [comment]
Thanks for the feedback.
As this is my first report, I did not know the normal process. Appreciate the support!

**Comment by oscarbenjamin** [comment]
Thanks for reporting!
