### ISSUE TITLE
Lens or Mirror not mentioned in transverse_magnification in physics.optics

### ISSUE THREAD

**Issue by 1e9abhi1e10** [sympy/sympy#24438]
Here is the [traverse_magnification](https://github.com/sympy/sympy/blob/master/sympy/physics/optics/utils.py#L671)  formula in `physics. optics` this formula is for the mirror but it is not mentioned here. Should we add the same for the lens?
```  
  so: sympifiable
        Lens-object distance.
  si: sympifiable
        Lens-image distance.

traverse_magnification for lens = si/so
```

**Comment by sylee957** [comment]
I'm not sure if the arithmetic is too trivial there such that we don't need to implement the function for this.

**Comment by swastik959** [comment]
can we add a parameter in the magnification function itself

**Comment by oscarbenjamin** [comment]
> I'm not sure if the arithmetic is too trivial there such that we don't need to implement the function for this.

This is probably true of everything in the optics module. I'm not sure what purpose it serves beyond listing what look like standard textbook formulae.

**Comment by 1e9abhi1e10** [comment]
> > I'm not sure if the arithmetic is too trivial there such that we don't need to implement the function for this.
> 
> This is probably true of everything in the optics module. I'm not sure what purpose it serves beyond listing what look like standard textbook formulae.

There is a difference of (-) sign in their transverse magnifications
for lens it should be `si/so`
and for mirror it should `(-(si/so))`

**Comment by sylee957** [comment]
I think that it's better to the definition in the documentation to make it reasonable (let's say, add some word like 'mirrored') because it is better for backward compatibility

**Comment by shishir-11** [comment]
I have made the required changes to the docstring , kindly review my PR . It might be the solution to the issue unless there is some addition to lens formula of transverse magnification .
