### ISSUE TITLE
`PermutationGroup.is_cyclic` incorrect on "unnamed" S3

### ISSUE THREAD

**Issue by skieffer** [sympy/sympy#24432]
If we construct a group `G` that's isomorphic to S3, but don't use the `SymmetricGroup` function to form it, then `G.is_cyclic` is coming up `True`.

```python
In [1]: from sympy.combinatorics import *

In [2]: S3 = SymmetricGroup(3)

In [3]: G = PermutationGroup(*S3.generators)

In [4]: G.order()
Out[4]: 6

In [5]: ' '.join(str(g.order()) for g in G.elements)
Out[5]: '3 3 2 2 1 2'

In [6]: G.is_cyclic
Out[6]: True
```

I think the `is_cyclic` property method is fine up until the end. It ends like this:

https://github.com/sympy/sympy/blob/d505ea97427cdd03d83dda553c9b4481c812fb54/sympy/combinatorics/perm_groups.py#L3222-L3232

Let's talk about what's happening here. First, let $G$ be the group, given by generators $\langle g_i \rangle$. For any prime $p$ dividing the order of the group, let $H_p$ be the subgroup $\langle g_i^p \rangle$ generated by the $p$ th powers of the given generators.

The for-loop is saying, "If $G$ is cyclic, then for all $p$ dividing the order of the group, $[G : H_p] = p$," which I think is true. Fine.

But the last three lines, after the for-loop, want to say the converse is also true, which it must not be, since $S_3 = \langle (012), (01) \rangle$ appears to be a counterexample.

The question is whether there's a good way to save this. In other words, there is always the last ditch, brute force method, where we just look through all the elements of the group for a generator:

```python
n = self.order()
for g in self.elements:
  if g.order() == n:
    self._is_cyclic = True
    return True
self._is_cyclic = False
return False
```
but it seems like we *almost* had a better method here, and it would be nice if we could patch it. I'm wondering if anyone whose group theory is not as rusty as mine might know a way.

If $G^p$ is the subgroup of $G$ consisting of all products of $p$ th powers of elements of $G$, it seems like the theorem we wanted might have been true with $G^p$ in place of $H_p$? I don't know.

But it does seem like the discrepancy between $G^p$ and $H_p$ might be the issue here. In the case of $S_3$ presented as $\langle (012), (01) \rangle$, $H_3$ is just $\lbrace e, (01) \rbrace$ which does have index $3$ (hence the failure), whereas $G^3 = G$ and has index $1$, and the test would not have failed.

**Comment by jksuom** [comment]
I think that it is best to start by checking that the group is abelian (by calling `is_abelian`, not just looking at `_is_abelian`).

A finite abelian group G is the product of its p-components G(p) for primes p dividing the order n of G. The subgroup G(p) consists of those elements of G whose order is a power of p. Its order is the highest power $p^e$ of p dividing n and it is generated by the m'th powers of the generators of G where $m = n/p^e$. It is cyclic if and only if at least one of its generators has order $p^e$.

A finite abelian group G is cyclic if and only if all of its p-components are cyclic. The "only if" part is clear as all subgroups of a cyclic group are cyclic. The inverse implication follows as the product of cyclic groups of mutually prime order is cyclic. For example, consider two cyclic groups G and H of orders m and n, and generated by a and b, respectively. Then the elements of GxH are the products $a^e b^f$, where $e = 0,\ldots, m-1$ and $f = 0,\ldots, n-1$. If m and n are relatively prime, it follows from the Chinese Remainder Theorem that, for each pair (e, f), there is a unique $k = 0,\ldots, mn-1$ such that $k \equiv e \pmod{m}$ and $k \equiv f \pmod{n}$. Then $a^k = a^e$ and $b^k = b^f$, and therefore $(ab)^k = a^k b^k = a^e b^f$; hence GxH is a cyclic group of order mn generated by ab.

**Comment by skieffer** [comment]
Okay, so if none of the earlier tests succeeds, we'll determine whether the group actually is abelian or not. If not, it's not cyclic either. If so, we find the Sylow p-subgroups G(p), and apply the fundamental theorem of finite abelian groups. Sounds like a plan. I didn't realize we could pass from generators of G to generators of G(p) in the way you describe (or think of using G(p)).

So for each $p$ dividing $n$, we want to know whether, raising all generators of $G$ to the $m$ power, we would get an element of order $p^e$. I think this is equivalent to asking whether $p^e$ divides the order of some generator. This is because, if generator $g$ has order $r$, we can write $r = p^k \cdot (m, r)$ for some $0 \leq k \leq e$. But the order of $g^m$ is $r/(m, r) = p^k$.

So what would be a good way to implement this. At this point in the procedure, we've already factored $n$, so we have all the $(p, e)$ pairs. I guess next we compute the order of each $g$ generating $G$. Then for each $(p, e)$ we reduce the orders of the $g$'s mod $p^e$, looking for a 0. In other words, I'm thinking this is better than factoring the order of each $g$.

**Comment by jksuom** [comment]
It is not necessary to explicitly compute the generators of G(p). It looks like it would suffice to see if any $n/p$'th power of a generator of G would be non-trivial.
