### ISSUE TITLE
about convert equation  to latex 

### ISSUE THREAD

**Issue by lishuaiCN** [sympy/sympy#24464]
it's a useful repo, and when I want to convert equation with "=" to latex, there was an error.

<code>
import sympy
from sympy import latex, pi, sin, asin, Integral, Matrix, Rational, log
from sympy.abc import x, y, mu, r, tau, a, b, c
formula_latex = latex(x-y**2 = 0, mat_symbol_style = 'equation')
print(formula_latex)
</code>

here is the error:
  File "<ipython-input-53-c9554c562bb3>", line 7
    formula_latex = latex(x-y**2 = 0, mat_symbol_style = 'equation')
                         ^
SyntaxError: keyword can't be an expression

**Comment by ThePauliPrinciple** [comment]
That is because that is not how you can use the `=` operator in python. In sympy, if you want to indicate a symbolic equal, you have to use `Eq(x-y**2,0)`

**Comment by lishuaiCN** [comment]
> That is because that is not how you can use the `=` operator in python. In sympy, if you want to indicate a symbolic equal, you have to use `Eq(x-y**2,0)`

thank you so much
