### ISSUE TITLE
Documentation of is_extra_strong_lucas_prp

### ISSUE THREAD

**Issue by Pontus-vB** [sympy/sympy#24476]
I suspect that the following sentence in the documentation of ``ntheory.primetest.is_extra_strong_lucas_prp`` shouldn't be there:

> With these parameters, there are no counterexamples below 2^64 nor any known above that range.

It doesn't say to what it would be a counterexample, but I assume it means a composite number for which the function returns ``True``. But in the example section, the first "counterexamples" are found to be 989, 3239, 5777, 10877, which are definitely below 2^64.

**Comment by cyclotomicextension** [comment]
I think you are correct about this.
