### ISSUE TITLE
`sympy.ntheory.elliptic_curve.EllipticCurve` can't verify it's points via `__contains__`, generated by `points` call

### ISSUE THREAD

**Issue by DarkNisa** [sympy/sympy#24517]
By following this code we can see:

`>>> from sympy.ntheory.elliptic_curve import *`
`>>> elliptic_curve = EllipticCurve(a4=-5, a6=1, modulus=47)`
`>>> elliptic_curve_points = list(elliptic_curve.points())`
`>>> elliptic_curve.__contains__(elliptic_curve_points[0])`
`False`

This error arises, because during `__contains__` computations the
`Eq` substitution operations are done without (mod 47).

This bug also affect possibility of making any operations on points,
via `EllipticCurvePoint` class, because it uses ` __contains__` to verify
if the given point lies on the elliptic curve.

**Comment by varunseth5788** [comment]
from sympy import *

class ModEllipticCurve(EllipticCurve):
    def __contains__(self, P):
        x, y = P
        f = self.f(x)
        return y*y % self.mod == f % self.mod

mod = 47
ec = ModEllipticCurve(-5, 1, mod)
points = list(ec.points())

print(ec.__contains__(points[0]))  # True
print(ec.__contains__((1, 1)))     # False



Is this right??

**Comment by DarkNisa** [comment]
So the problem here is much deeper than it seems. I haven't used a lot sympy library,
so i don't know how many things work here, and the initial idea was to find library to
make computations under elliptic curves and points, to create a specific digital signature
for myself. And I found this implementation. So firstly we have here `EllipticCurvePoint`
class which we can use to make operations under points, but it bounded to curve itself
in `__init__` constructor, which uses `__contains__` method to check, whether a point
lies on bounded elliptic curve. So the `EllipticCurve` implies from its `__init__` constructor
that we can create elliptic curves under some given modulus. And even properly returns
the list of all points that lie on this curve taking into account given modulus. And the
simplest test of belonging of point from this list to a elliptic curve breaks everything.
It happens when in `__contains__` method we substitute points into elliptic curve via
`self._eq.subs({self.x: x1, self.y: y1, self.z: z1})`, which literally substitute point and make
no modulus under arithmetic. That's why I don't think that it's a good idea to create
inherited class here, but may be there a way to specify a domain in symbolic equation
or make proper calculations under such domain like `points` method have. Of course
there may be brute force solution where we apply modulus directly modifying equation
before substitution in `contains` method, but I don't think this is good way of solving such
problem.

**Comment by oscarbenjamin** [comment]
> Of course
> there may be brute force solution where we apply modulus directly modifying equation
> before substitution in `__contains__` method, but I don't think this is good way of solving such
> problem.

I don't see any problem with doing that except that maybe it should be done when creating the equation in the first place.

A simple fix is this:
```diff
diff --git a/sympy/ntheory/elliptic_curve.py b/sympy/ntheory/elliptic_curve.py
index b9cdbcd870..23983d5960 100644
--- a/sympy/ntheory/elliptic_curve.py
+++ b/sympy/ntheory/elliptic_curve.py
@@ -77,7 +77,11 @@ def __contains__(self, point):
             raise ValueError('Invalid point.')
         if self.characteristic == 0 and z1 == 0:
             return True
-        return self._eq.subs({self.x: x1, self.y: y1, self.z: z1})
+        values = {self.x: x1, self.y: y1, self.z: z1}
+        eq = self._eq
+        if self.characteristic != 0:
+            eq = Eq((eq.lhs - eq.rhs) % self.characteristic, 0)
+        return eq.subs(values)
 
     def __repr__(self):
         return 'E({}): {}'.format(self._domain, self._eq)
```
It would also be good though to review all other uses of `_eq` to make sure that they handle the modulus appropriately. Potentially it would be better to modify the equation so that it always has the modulus in it from the moment it is created but a review is needed of the handful of other places that use `._eq` in this class.

**Comment by DarkNisa** [comment]
> So the problem here is much deeper than it seems. I haven't used a lot sympy library,
> so i don't know how many things work here $\dots$

Ok. Let me show, how I see this problem can be solved. As I see `Eq` class has a method
`as_poly`, which converts equation into polynomial `Poly` object. To my surprise it supports
operations under specified domain so the following is possible:
`elCurve = EllipticCurve(a4=-5, a6=1, modulus=47)`
`badPoint = elCurve.points().pop()`
`elPoly = Poly(elCurve._eq.as_poly().expr, domain=elCurve._domain)`
`elPoly`
$\text{Poly}(-x^{3}+5 x z^{2} + y^{2} z - z^{3}, x, y, z, domain=\mathbb{F}_{47})$
`values = dict(zip((x, y, z), (*badPoint, 1)))`
`elPoly.subs(values)`
$0$
So my idea is probably ask for feature to add similar behavior to `Eq` class
as its already realized in `Poly`, so the `subs` in `__contains__` method will
work out the box. and the only thing that will need to be changed in 
`EllipticCurve` class is to add `domain` flag to `Eq` where an elliptic curve
equation is constructed, so the `_domain` field of `EllipticCurve` can be
properly used, without breaking any abstraction layers, with previously
proposed solutions.

**Comment by oscarbenjamin** [comment]
> may be it is possible
> to replace elliptic curve creation by `Eq` class to `Poly`

That is the best approach I think.

**Comment by DarkNisa** [comment]
I replaced all usage of `Eq` class into `Poly` in my copy of
`sympy` library, cloned via `git clone`, and tested it. so it seems
it works now as it should, even found a bug in `points_x` method,
but I don't know how to properly make a **pull request** to the
project, may you help me with it?

**Comment by oscarbenjamin** [comment]
There is a guide for new contributors here:
https://docs.sympy.org/dev/contributing/new-contributors-guide/index.html

**Comment by DarkNisa** [comment]
Thanks. I made pull request using the instruction above. [#25141](https://github.com/sympy/sympy/pull/25141)
But it cant pass one test because I changed `__repr__` accordingly,
so instead of printing `Eq(lhs, rhs)` my version prints `Eq(lhs-rhs, 0)`,
because I use only `Poly` now. So I don't know what to do with it.

**Comment by oscarbenjamin** [comment]
Either the doctest should be changed or the `__repr__` should be changed. The `Eq` could still be stored just for use in `__repr__` to keep the output the same.
