### ISSUE TITLE
rot_axis1, rot_axis2 and rot_axis3 should use the right-hand rule 

### ISSUE THREAD

**Issue by evbernardes** [sympy/sympy#24528]
When following the right hand rule, the rotation matrices should be:
```math
\begin{alignat}{1}
R_x(\theta) &= \begin{bmatrix}
1 &  0            &  0           \\
0 &  \cos \theta  & -\sin \theta \\[3pt]
0 &  \sin \theta & \cos \theta 
\end{bmatrix} \\[6pt]
R_y(\theta) &= \begin{bmatrix}
\cos \theta & 0 & \sin \theta \\[3pt]
0           & 1 &  0           \\[3pt]
-\sin \theta & 0 &  \cos \theta 
\end{bmatrix} \\[6pt]
R_z(\theta) &= \begin{bmatrix}
\cos \theta & -\sin \theta & 0 \\[3pt]
\sin \theta &  \cos \theta & 0 \\[3pt]
0           &  0           & 1 
\end{bmatrix}
\end{alignat}
```
But the functions on `sympy.matrices.dense` define them as the opposite of this instead.

**Comment by oscarbenjamin** [comment]
What exactly do you mean by the right hand rule? The right hand rule has I understand it as a convention that determines the direction of the positive z axis. No equations are affected by the choice of left or right hand rule as it just means that the z axis goes in the other direction.

**Comment by evbernardes** [comment]
The [right-hand rule](https://en.wikipedia.org/wiki/Right-hand_rule) is the convention mostly used to define what a rotation around an axis mean.

Using the right-hand rule, for example, a rotation of 90 degrees around the `z`-axis aligns the vector `x` with the vector `y`. Using the opposite convention a rotation of 90 degrees around the `z`-axis would align the vector `x` with the vector `-y`. , which is how this is implemented in these functions. 

It is usually assumed that everything is following the right-hand rule convention.

**Comment by evbernardes** [comment]
This test (that passes) shows how this convention is unconventional and inconsistent with the definitions in `Quaternion`, for example:
```python
    q1 = Quaternion.from_axis_angle([1, 0, 0], pi / 2)
    q2 = Quaternion.from_axis_angle([0, 1, 0], pi / 2)
    q3 = Quaternion.from_axis_angle([0, 0, 1], pi / 2)
    assert rot_axis1(- pi / 2) == q1.to_rotation_matrix()
    assert rot_axis2(- pi / 2) == q2.to_rotation_matrix()
    assert rot_axis3(- pi / 2) == q3.to_rotation_matrix()
```

**Comment by oscarbenjamin** [comment]
> Using the right-hand rule, for example, a rotation of 90 degrees around the `z`-axis aligns the vector `x` with the vector `y`. Using the opposite convention a rotation of 90 degrees around the `z`-axis would align the vector `x` with the vector `-y`. , which is how this is implemented in these functions.

In the right hand rule convention the positive z-axis points towards you (assuming x positive to the right and y positive upwards). In the left hand rule convention the z-axis points away from you. When you swap conventions from right to left then for the screw you need to reverse the direction of your thumb. Either way no equations are changed.

Coordinate geometry in the abstract is completely independent of left or right hand convention. The convention dictates a relationship between coordinates in a coordinate system and actual physical space. Switching convention does not affect anything in any of our equations but reverses the interpreted "direction" of pseudovectors like angular velocity and also the interpretation of the sense of rotation between clockwise and anticlockwise as seen looking in the direction of the pseudovector.

Here is how `rot_axis3` behaves:
```python
In [5]: rot_axis3(pi/2) * Matrix([1, 0, 0])
Out[5]: 
⎡0 ⎤
⎢  ⎥
⎢-1⎥
⎢  ⎥
⎣0 ⎦
```
In the right hand convention the z-axis points towards you and this is an anticlockwise rotation of pi/2 as seen looking in the positive z direction. In the left hand convention the z-axis points away from you and this is a clockwise rotation around the positive z direction.

Likewise:
```python
In [6]: rot_axis1(pi/2) * Matrix([0, 1, 0])
Out[6]: 
⎡0 ⎤
⎢  ⎥
⎢0 ⎥
⎢  ⎥
⎣-1⎦
```
In the right hand convention the z-axis points towards you and hence the rotated vector points away from you. In this case the rotation is anticlockwise when seen looking along the positive x-axis. In the left hand convention the z-axis points away from you and so the rotated vector points toward you. In this case the rotation would clockwise be around the positive x axis.

The relevance of the left or right hand rule is only in whether the rotation is interpreted as clockwise or anticlockwise:
https://en.wikipedia.org/wiki/Rotation_matrix#Non-standard_orientation_of_the_coordinate_system

**Comment by evbernardes** [comment]
Yep, exactly! 

My point is that almost everyone uses the anticlockwise convention, so I found it a bit surprising that the other convention is used in these implementations.

Almost every reference you can find, not only Wikipedia, will give the matrices defined for anticlockwise rotation.

**Comment by evbernardes** [comment]
In #24569 we are discussing adding a clear indication of this in the docstring.
