### ISSUE TITLE
laplace_tranform of derivatives the coefficient was missed

### ISSUE THREAD

**Issue by weekstars** [sympy/sympy#24536]
![image](https://user-images.githubusercontent.com/122853436/212814476-aeffd248-c15c-4c37-828d-f5ab7f5e5176.png)
When implementing the Laplace transformation to derivatives, I was confused why the coefficient was missed

**Comment by 1e9abhi1e10** [comment]
I thought this is fixed on the master since SymPy 1.11.1 was released. The fix will be in SymPy 1.12.

**Comment by weekstars** [comment]
I have just read the previous issue about it. Thank you.
