### ISSUE TITLE
bilinear discretization of continuous transfer function in Control API

### ISSUE THREAD

**Issue by zolabar** [sympy/sympy#24544]
Continuous transfer functions $$H(s)=\frac{b_0+b_1 s+b_2 s^2+...}{a_0+b_1 s+a_2 s^2+...}$$

can be discretized to $H(z)$ with the bilinear (Möbius/Tustin) formula (leads to trapezoidal integration rule in the time domain)

$$s(z)=\frac{2}{T}\frac{z-1}{z+1}$$

where $T$ is the sample period, $H(z)$ is important when implementing digital control strategies.

The expression s(z) is substitued into $H(s)$ and $H(z)$ is obtained, see

[https://en.wikipedia.org/wiki/Bilinear_transform](https://en.wikipedia.org/wiki/Bilinear_transform)

A similar Möbius or bilinear transform is used in a totaly different engineering application (fluid power engineering) in

Lauer-Baré Z. and Gaertig E., [*Conformal Mappings with SymPy: Towards Python-driven Analytical Modeling in Physics*. Lauer-Baré, Z. & Gaertig, E. In Agarwal, M., Calloway, C., Niederhut, D., & Shupe, D., editors, Proceedings of the 20th Python in Science Conference, pages 85 - 93, 2021. ](https://conference.scipy.org/proceedings/scipy2021/lauer_bare_gaertig.html)

The conference talk can be seen on the [Enthought YouTube channel](https://www.youtube.com/watch?v=P5ybpjv2uDA).

References on the Möbius/bilinear transform in the context of discretizations of continuous transfer functions can be found here

Oppenheim AV. Discrete-time signal processing. Pearson Education; 1999.

Lyons RG. Understanding digital signal processing, 3/E. Pearson Education; 1997.

The following bilinear function for SymPy's Control API

https://docs.sympy.org/latest/modules/physics/control/lti.html

exists already in numerical form in 

https://docs.scipy.org/doc/scipy/reference/generated/scipy.signal.bilinear.html

Here is the proposed bilinear transform,

    """
    Discretizes H(s) (just a Sympy rational polynomial in) to H(z) with the bilinear Method and ample rate T
    It Returns falling coeffs vof H(z) from numerator and denominator
    i.e. H(z) = (az+b)/(cz+d) is return as [a, b], [c, d]
    
    The latex formulae of the continuous input formula and the dicretized numerator and denominator are returned
    
    """

  """

def bilinear(H):
   
    print('H(s)='+sym.latex(H))
    print()
    
    HZ = H.subs(s, (2/T)*(z-1)/(z+1))

    zaehler, nenner = sym.fraction(sym.simplify(HZ))
    
    HZzaehler = sym.collect(sym.expand(zaehler, z), z)
    
    HZzaehler = sym.poly(HZzaehler, z)
    
    HZnenner = sym.collect(sym.expand(nenner, z), z)
    
    HZnenner = sym.poly(HZnenner, z)
    
    print('discrete numerator:\n' + sym.latex(HZzaehler.expr))
    print()
    
    print('discrete denominator:\n' +sym.latex(HZnenner.expr))    
    
    zaehler_coefs = HZzaehler.coeffs()
    
    nenner_coefs = HZnenner.coeffs()
    
    return zaehler_coefs, nenner_coefs

  """
A jupyter notebook example is attached.

[sympy_contrlol_api_discretize_bilinear.zip](https://github.com/sympy/sympy/files/10445059/sympy_contrlol_api_discretize_bilinear.zip)

**Comment by oscarbenjamin** [comment]
I don't understand what the purpose of this issue is. Are you suggesting that this function should be added to sympy?

**Comment by zolabar** [comment]
> I don't understand what the purpose of this issue is. Are you suggesting that this function should be added to sympy?

Hello Oscar, yes.

for instance if I have a sympy control api transfer function H,

with H.bilinear() I could obtain the coefficients of the numerator and denominator polynomials of the discretized transfer function.

for use in scipy, control or matlab

**Comment by sylee957** [comment]
It doesn't look much more involved than `.subs`, but I'd assume a same and better recipe should be found for symbolic computation, like purely using `poly` with `prem` or something.

**Comment by faze-geek** [comment]
> It doesn't look much more involved than `.subs`

Control api doesn't support `.subs` as of now.

```
>>> tf = TransferFunction(s**2 + 2*s + 1,s + 1,s)
>>> pprint(tf.subs({s:2}))
 2
s  + 2⋅s + 1
────────────
   s + 1

```

**Comment by faze-geek** [comment]
> 

> with H.bilinear() I could obtain the coefficients of the numerator and denominator polynomials of the discretized transfer function.

Not sure but I guess something like extracting coefficients is available in `MATLAB` - https://www.mathworks.com/help/control/ug/extract-model-coefficients.html

I believe this will be a useful addition in the Sympy codebase too.

**Comment by zolabar** [comment]
thank you for the feedback. I think that an impulse invariant symbolic discretization method would also be great, sympy offers the tools for that, since the partial fraction decompostion is already there :)

For H beeing a continuous transfer function in s (H(s))

H.bilinear() could return  the coefficients of the numerator and denominator polynomials of the discretized transfer function, computed with the bilinear transform method.

and

H.impinvar() could return  the coefficients of the numerator and denominator polynomials of the discretized transfer function, computed with the impulse invariant method.
