### ISSUE TITLE
Polygon.encloses_point() seems not to work properly

### ISSUE THREAD

**Issue by inetphantom** [sympy/sympy#24564]
Hello
I enconutered a bug. See following code, I would expect that the assertion does not fail.
It is a four sided polygon, point X is defenitly inside and should be enclosed. Or am I wrong?

```python
from sympy import Point2D, Polygon

a = Point2D(0.54284805059433, 0.373753279447556)
b = Point2D(0.447052538394928, 0.364999771118164)
c = Point2D(0.517921566963196, 0.533397793769836)
d = Point2D(0.444990664720535, 0.530372083187103)

x = Point2D(0.45, 0.45)

poly = Polygon(a, b, c ,d)

assert poly.encloses_point(x)

```

**Comment by MythicSTR** [comment]
I am new to SymPy but here's what I tried. I traced the points in Desmos ([https://www.desmos.com/calculator](url)). And it forms a Z-shape. The point (0.45, 0.45) is not enclosed in the polygon you defined.

**Comment by oscarbenjamin** [comment]
I guess d and c are the wrong way round:
```
In [48]: Polygon(a, b, d, c).encloses_point(x)
Out[48]: True
```
