### ISSUE TITLE
laplace_transform - incorrect convergence condition

### ISSUE THREAD

**Issue by Davide-sd** [sympy/sympy#24594]
```python
t, s = symbols("t, s")
a = symbols("a", real=True, positive=True)
expr = exp(a * t)

laplace_transform(expr, t, s)
# out:  (1/(-a + s), a, True)
```

Up to SymPy 1.9, the last element of the resulting tuple (the convergence condition) used to be `Ne(s / a, 1)`... Is it correct the new output?

**Comment by hanspi42** [comment]
Yes. The pole is at `s==a`, so convergence is given for `re(s)>a`, which is the meaning of the second returned argument. The old condition was not correct, it just stated that you should not evaluate the new expression at `s=a`.

I am currently te-writing a lot of the Laplace transform code; if you are interested, the plan is here: #24561

**Comment by hanspi42** [comment]
Does the "thumbs-up" emoji signify that you are happy with the response and the issue can be closed again?

**Comment by Davide-sd** [comment]
Yep, I'm closing it.
