### ISSUE TITLE
Dagger of constants breaks

### ISSUE THREAD

**Issue by akhmerov** [sympy/sympy#24664]
```python
import sympy.physics.quantum
sympy.physics.quantum.Dagger(1)
```
raises 
```python
---------------------------------------------------------------------------
UnboundLocalError                         Traceback (most recent call last)
Cell In[6], line 2
      1 import sympy.physics.quantum
----> 2 sympy.physics.quantum.Dagger(1)

File /opt/conda/lib/python3.10/site-packages/sympy/physics/quantum/dagger.py:85, in Dagger.__new__(cls, arg)
     83 elif hasattr(arg, 'conjugate') and hasattr(arg, 'transpose'):
     84     obj = arg.conjugate().transpose()
---> 85 if obj is not None:
     86     return obj
     87 return Expr.__new__(cls, arg)

UnboundLocalError: local variable 'obj' referenced before assignment
```
I believe that either a more human-readable error or falling back to e.g. only complex conjugation would be better.

Do people have any preference for how this should be handled?

Related issue #17403

**Comment by sylee957** [comment]
I guess that first we could just make sure `obj` exists in any if-else statements.

**Comment by sylee957** [comment]
Also, there's a problem with sympify I guess
because `Dagger(S.One)` works

**Comment by akhmerov** [comment]
Oassing all the arguments through sympify would change the current behavior quite profoundly (e.g. now Dagger will work on numpy arrays without modifying their type). Would this be desired behavior?

**Comment by ThePauliPrinciple** [comment]
The constructor of this class does not use `sympify`/`_sympify`

https://github.com/sympy/sympy/blob/43eed48717b638272a9b8269cde20f460a6b9d6c/sympy/physics/quantum/dagger.py#L80-L94
