### ISSUE TITLE
Euler's formula is not used for simplification

### ISSUE THREAD

**Issue by NotWearingPants** [sympy/sympy#24677]
[Exact trigonometric values on Wikipedia](https://en.wikipedia.org/wiki/Exact_trigonometric_values) includes many values, and it appears sympy knows them, but when using `exp(I*x)` it only knows about multiples of `pi/2`:
```py
>>> exp(I*pi)
-1
>>> exp(I*pi/2)
I
>>> exp(I*pi/3)
exp(I*pi/3)
>>> cos(pi/3)+I*sin(pi/3)
1/2 + sqrt(3)*I/2
```
It should use Euler's formula: `exp(I*x) = cos(x) + I*sin(x)`

**Comment by ThePauliPrinciple** [comment]
You can do something like this:
```python
(exp(I*pi/3)).rewrite(cos)
```

I think unless `exp(I*x)` results in only one term, it's more "simplified" in its `exp` form. Of course, that's a matter of opinion.

**Comment by ThePauliPrinciple** [comment]
I think this is the more typical use in sympy:
```python
sinx = (exp(I*x) - exp(-I*x))/(2*I)
sinx.simplify().subs(x,pi/3)
```
Which gives the answer you were expecting.
Possibly what you see is a bug, but I'm not sure.

I don't know if it is possible to modify simplify as a user, nor am I aware of how it works internally. Usually I try permutations of `rewrite`, `simplify` and `subs` if I am looking for something specific. At the end of the day, the goal of simplify is to improve the speed of algorithms acting on sympy objects, not neccesarily to obtain a pleasing representation.

**Comment by oscarbenjamin** [comment]
A function like this would be useful to have in sympy:
```python
def algsimp(a):
    p = minpoly(a, polys=True)
    [asimp] = [r for r in p.all_roots() if p.same_root(r, a)]
    return asimp
```
That can simplify any expression representing an algebraic number to a canonical form.
```python
>>> print(algsimp(sin_(pi/3)))
sqrt(3)/2
>>> print(algsimp(exp(I*pi/3)))
1/2 + sqrt(3)*I/2
```

More generally I often find it annoying that exponential expressions which are usually quite easy to manipulate get turned into radicals which are harder to manipulate so I don't think that adding more evaluation rules is necessarily a good idea.

**Comment by hanspi42** [comment]
> [Exact trigonometric values on Wikipedia](https://en.wikipedia.org/wiki/Exact_trigonometric_values) includes many values, and it appears sympy knows them, but when using `exp(I*x)` it only knows about multiples of `pi/2`:

If you include variables, it becomes quite simple:
```
(cos(x*pi/3)+I*sin(x*pi/3)).rewrite(exp)
```

Is that what you wanted?

**Comment by smichr** [comment]
The PR I opened shows that some things become more complicated when doing this automatically. The [suggest](https://github.com/sympy/sympy/issues/24677#issuecomment-1421014549) to use `rewrite(cos)` is the way for the user to do the Euler rewrite for multiples of `I*pi` other than 1/2.

**Comment by oscarbenjamin** [comment]
I also think that many "exact trigonometric values" should not be used automatically. It is better to have trig and exp rather than complicated radicals e.g.:
```python
In [5]: cos(pi/15)
Out[5]:
                  ________
                 ╱ √5   5
           √3⋅  ╱  ── + ─
  1   √5      ╲╱   8    8
- ─ + ── + ───────────────
  8   8           2
```
I think that nested radicals should be avoided: they should not be introduced automatically. There can be a function for this but it should be something like `to_radical`:
https://reference.wolfram.com/language/ref/ToRadicals.html
