### ISSUE TITLE
SVG images in the docs are not visible in dark mode

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#24695]
I'm sorry that I didn't pick up on this when I added the Furo theme. The SVG images in the docs do not support dark mode. For example, at https://docs.sympy.org/dev/modules/physics/vector/vectors.html:

<img width="772" alt="Screen Shot 2023-02-09 at 2 57 42 PM" src="https://user-images.githubusercontent.com/71486/217948696-6a6efe4d-018d-4613-b8b5-1b1571af159b.png"><img width="771" alt="Screen Shot 2023-02-09 at 2 57 48 PM" src="https://user-images.githubusercontent.com/71486/217948689-86bc1a8e-1266-450f-8660-595a75bfec25.png">

I'm not sure what the correct way to fix this is. 

Here's all the SVG files in the repo. Basically all of them are in the physics module:

```
$ git ls-files | grep svg
banner.svg
doc/ext/convert-svg-to-pdf.py
doc/src/logo/sympy-use-text.svg
doc/src/logo/sympy.svg
doc/src/modules/physics/mechanics/api/CylindricalJoint.svg
doc/src/modules/physics/mechanics/api/PinJoint.svg
doc/src/modules/physics/mechanics/api/PlanarJoint.svg
doc/src/modules/physics/mechanics/api/PrismaticJoint.svg
doc/src/modules/physics/mechanics/api/SphericalJoint.svg
doc/src/modules/physics/mechanics/api/WeldJoint.svg
doc/src/modules/physics/mechanics/api/joint_explanation.svg
doc/src/modules/physics/mechanics/examples/four_bar_linkage.svg
doc/src/modules/physics/mechanics/examples/pendulum_nonmin.svg
doc/src/modules/physics/mechanics/examples/rollingdisc.svg
doc/src/modules/physics/vector/kin_1.svg
doc/src/modules/physics/vector/kin_1pt.svg
doc/src/modules/physics/vector/kin_2.svg
doc/src/modules/physics/vector/kin_2pt.svg
doc/src/modules/physics/vector/kin_3.svg
doc/src/modules/physics/vector/kin_4.svg
doc/src/modules/physics/vector/kin_angvel1.svg
doc/src/modules/physics/vector/kin_angvel2.svg
doc/src/modules/physics/vector/kin_angvel3.svg
doc/src/modules/physics/vector/kin_rolling.svg
doc/src/modules/physics/vector/simp_rot.svg
doc/src/modules/physics/vector/vec_add.svg
doc/src/modules/physics/vector/vec_cross.svg
doc/src/modules/physics/vector/vec_dot.svg
doc/src/modules/physics/vector/vec_fix_notfix.svg
doc/src/modules/physics/vector/vec_mul.svg
doc/src/modules/physics/vector/vec_rep.svg
doc/src/modules/physics/vector/vec_simp_der.svg
doc/src/modules/vector/coordsys_rot.svg
```

**Comment by asmeurer** [comment]
CC @sympy/mechanics

**Comment by faze-geek** [comment]
An issue related to this was raised earlier #23706 but didn't seem to get resolved by given suggestions.

**Comment by moorepants** [comment]
One option is to disable the dark mode. The black background with the SymPy green side bar isn't really aesthetically pleasing in the first place.

![image](https://user-images.githubusercontent.com/276007/218018105-1dfcce8b-c0ad-424e-9e9f-28436b7a58e8.png)

**Comment by asmeurer** [comment]
You can always disable the dark mode with the button at the top if you don't like it. By default it only does it if your system is set to dark mode. I personally don't really like dark mode either which is why I never use it. But I believe a lot of people do like it.

**Comment by asmeurer** [comment]
The Furo theme defines only-light and only-dark for images that appear only in dark or light mode. It should be possible to use this to either define separate images that appear only in light or dark mode, or to modify the SVG source itself to change the colors. This should be preferred over `@media (prefers-color-scheme: dark)` because the Furo theme uses an additional selector on top of `prefers-color-scheme` so that you can manually override it with the button at the top.

**Comment by asmeurer** [comment]
Also all the colors are part of the custom theming so if we don't like how something looks we can fix it.

**Comment by moorepants** [comment]
> You can always disable the dark mode with the button at the top if you don't like it.

Yes, but I meant that we disable the button and not allow dark mode.

**Comment by TJStienstra** [comment]
Personally, I quite like the dark mode and I rather switch manual if I encounter an image which has bad readability. If possible I would like a fix that the svg changes color. This can be done on two levels as far as I know:
- Inside the svg as explained [here](https://stackoverflow.com/a/67190894). However as I [noted previously](https://github.com/sympy/sympy/issues/23706#issue-1289014356) I could not get that to work.
- On the html level, as is also done for the theme-icon. Just not sure how that would exactly work.

**Comment by asmeurer** [comment]
Have you tried doing the same trick you tried with the svg except using `only-dark` instead of `prefers-color-scheme`? I'm not sure how css variables work inside of svgs. If it's not possible to do that, then I think we either need to use separate SVGs (one can be generated from the other in the Makefile I guess), or we can try to use some Javascript to fix them.

**Comment by TJStienstra** [comment]
Just tried `only-dark` as well, but I do not get it to work. If I have to guess, the scripting code is stripped out, when building the documentation. However this is going beyond what I know about svgs and building websites.

**Comment by asmeurer** [comment]
I doubt that, but you can easily check with the web inspector. I would suggest playing around with it there as it's much faster than rebuilding the docs each time.

**Comment by asmeurer** [comment]
Actually I'm not sure if you can edit svg files in the web inspector, since they aren't inline in the HTML, but what you can do is build the docs then edit the SVG file from `_build/html` directly and reload the page, rather than editing the source and rebuilding with Sphinx. Alternatively, copy the SVG inline in the HTML so that it is easier to edit in the web inspector. 

My guess is that SVG files cannot access the CSS from the DOM, or if they can, it's only if they are inline. So likely this trick won't work. But I'm not completely sure about that.

**Comment by TJStienstra** [comment]
Thanks for the suggestion, this is indeed way better than building again (editing the SVG in `_build/html`). What I do notice when using inspect element on both a SVG from the documentation and on the theme-icon is:
- A documentation image is just an reference to the image `src="../../../../_images/rollingdisc.svg"`
- The theme-icon is defined on the HTML page itself and uses `stroke="currentColor"`

When trying to use `stroke="currentColor"` in the SVG file, it still doesn't work.

**Comment by harshitmathur2000** [comment]
I have managed to make the following modification. If this is suitable then I would like to work on it.
<img width="576" alt="image" src="https://user-images.githubusercontent.com/74778498/218259972-1ae172a0-e8a1-448c-8f62-458b51f4f053.png">

**Comment by harshitmathur2000** [comment]
> Personally, I quite like the dark mode and I rather switch manual if I encounter an image which has bad readability. If possible I would like a fix that the svg changes color. This can be done on two levels as far as I know:
> 
> * Inside the svg as explained [here](https://stackoverflow.com/a/67190894). However as I [noted previously](https://github.com/sympy/sympy/issues/23706#issue-1289014356) I could not get that to work.
> * On the html/css level, as is also done for the theme-icon. Just not sure how that would exactly work.

Can you tell in which file you made these changes?

**Comment by TJStienstra** [comment]
`doc/src/modules/physics/mechanics/examples/rollingdisc.svg` is one of the file I worked with, but the four bar linkage svg als has a few words, which become unreadable in the dark theme.

**Comment by theWiseAman** [comment]
- I think this might be related to these files `vector.rst` and `kinematics.rst` files. Is there any way to set color directives for the images like the below code snippet. I saw some `@media` queries for texts in the `_build/html` which gets automatically generated from the .rst files itself. Are there helpful documentation on .rst files?
```rst
.. image:: vec_rep.*
   :height: 175
   :width: 350
   :align: center
```
- Secondly I propose that we can hard-code a color scheme in SVG files which is consistent in both view modes.

**Comment by theWiseAman** [comment]
> * Secondly I propose that we can hard-code a color scheme in SVG files which is consistent in both view modes if nothing works. The color that I used is closer to black but doesn't hide and moreover is consistent with the overall docs theme.
>   ![image](https://user-images.githubusercontent.com/77196231/218361158-4785707d-8178-4469-a81f-fc2b63d77c11.png)
>   ![image](https://user-images.githubusercontent.com/77196231/218361273-f945f6f9-2bfc-4cc4-81ed-e65d580679e0.png)

@asmeurer Check my PR #24707 which highlights SVGs changes according to my second proposals. I had coincidently tried almost similar methods that @TJStienstra but they weren't working so I decided to change the primary color of the SVGs.

**Comment by asmeurer** [comment]
I think we should keep the vector images black (or white in dark mode). I would rather just have two copies of the images for each color than do this.

**Comment by sylee957** [comment]
I guess the matplotlib directives are fine because they force the background color to be white.
I wonder if it can be done for all other vector images, instead of transparent background color. I'm not sure if the color can be easily adaptive.

**Comment by TJStienstra** [comment]
I just had another play in another repo of mine. The following seems to work:

Use in SVG's the following format:
```
<?xml version="1.0" encoding="UTF-8"?>
<!-- Do set an id and viewBox, do not set width or height. -->
<svg id="someNameId" version="1.1" viewBox="0 0 15 9" xmlns="http://www.w3.org/2000/svg">
    <!-- SVG content use currentColor for stuff that is black in light theme and white in dark theme. -->
    <circle cx="50" cy="50" r="50" fill="currenctColor" />
</svg>
```

In the RST file use the raw HTML instead:
```
.. raw:: html

    <!--Make sure to set the same viewBox and here you can set the width-->
    <svg class="align-center" viewBox="0 0 231.0395 70.457903" width="800px">
        <use xlink:href="path_to_svg.svg#someNameId"></use>
    </svg>
```

**Comment by asmeurer** [comment]
Can you make a PR so that we can see it in the docs preview?

**Comment by TJStienstra** [comment]
Just played a bit around this and noticed the following two problems:
- Getting the path right is a bit nasty, as this is the path after building the documentation, e.g. `../../../_static/vec_rep.svg`.
- The image should be in the `_static` folder.

This I would say is both rather suboptimal and would require some kind of workaround.
