### ISSUE TITLE
`ReferenceFrame.orient` method gives incorrect result if orienting about the y-axis (potentially significant error, IMO)

### ISSUE THREAD

**Issue by angadhn** [sympy/sympy#24718]
Simple rotations between two reference frames $N$ and $E$ about the y-axis result in the incorrect results when using express (and direction cosine matrices, from where the results are possibly computed).

Three simple tests below to show the differences in results for rotations about y v/s x (and z). In all cases a positive rotation rotation (counter-clockwise) is provided via an angle $phi$. The `express` function is then invoked to show the incorrect/inconsistent outputs.

## y-rotation (inconsistent and incorrect)
```
from sympy.physics.mechanics import ReferenceFrame
from sympy import symbols
phi = symbols("phi")
N = ReferenceFrame('N')
E = ReferenceFrame('E')
E.orient(N, 'Axis', (phi, N.y))
E.x.express(N)
```
Output is: $\cos\phi \hat{\bf n}_x - \sin\phi\hat{\bf n}_z$

## x-rotation (consistent and correct)
```
E.orient(N, 'Axis', (phi, N.x))
E.y.express(N)
```
Output is:  $\cos\phi \hat{\bf n}_y + \sin\phi\hat{\bf n}_z$

## z-rotation (consistent and correct)
```
E.orient(N, 'Axis', (phi, N.x))
E.y.express(N)
```
Output is: $\cos\phi \hat{\bf n}_x + \sin\phi\hat{\bf n}_y$.

@moorepants, I have not checked if this issue is limited only to using the `Axis` approach in `.orient`- checks with `Space` and `Body` might be needed but I imagine its impacts on research results could be quite significant any time a rotation about a y-axis is involved.

**Comment by moorepants** [comment]
I'm not seeing why you state the y rotation is incorrect. Here is some code that shows the direction cosine matrix:

```
In [23]: import sympy as sm

In [24]: import sympy.physics.mechanics as me

In [25]: sm.__version__
Out[25]: '1.11.1'

In [26]: A = me.ReferenceFrame('A')

In [27]: B = me.ReferenceFrame('B')

In [28]: theta = sm.symbols('theta')

In [29]: B.orient_axis(A, A.y, theta)

In [30]: B.dcm(A)
Out[30]: 
Matrix([
[cos(theta), 0, -sin(theta)],
[         0, 1,           0],
[sin(theta), 0,  cos(theta)]])

In [31]: B.x.express(A)
Out[31]: cos(theta)*A.x - sin(theta)*A.z

In [32]: B.y.express(A)
Out[32]: A.y

In [33]: B.z.express(A)
Out[33]: sin(theta)*A.x + cos(theta)*A.z
```

These all look correct to me and match what you show above. This rotates B with respect to A about the positive A.y=B.y axis.

**Comment by moorepants** [comment]
Also, for your X and Z rotations you should the exact same input code (both rotations about x) and then show different results.

**Comment by angadhn** [comment]
Oh dammit- I agave seen one too many wrong answers while grading my exam that I got confused by my own solution with so many wrong solutions…. 😂 closing!
