### ISSUE TITLE
Solve returns `1=0`

### ISSUE THREAD

**Issue by yohad** [sympy/sympy#24715]
This is my code:
```
from sympy import *
init_printing()
x, y = symbols("x, y")
solve(x * y + 1, 1, x)
```

and I get
```
{1: 0, x: 0}
```
which must be a bug, right?

My sympy version is 1.10.1.

**Comment by 1e9abhi1e10** [comment]
I think it will be the right way to solve this
``` python 
>>> solve(x*y+1, x, y)

⎡⎛-1    ⎞⎤
⎢⎜───, y⎟⎥
⎣⎝ y    ⎠⎦
```

**Comment by oscarbenjamin** [comment]
When you ask to solve for something like `1` then you should expect fairly nonsensical results.

**Comment by hanspi42** [comment]
> When you ask to solve for something like `1` then you should expect fairly nonsensical results.

Interestingly, it is kind of correct ;)

```python
In [2]: (x * y + 1).subs({x: 0, 1: 0})
Out[2]: 0
```

**Comment by smichr** [comment]
While solving for a constant (i.e. isolating a constant) might be helpful for a single equation, perhaps this should be disabled for systsems of equations.

**Comment by hanspi42** [comment]
> While solving for a constant (i.e. isolating a constant) might be helpful for a single equation, perhaps this should be disabled for systsems of equations.

Maybe, but the original poster does not use a system of equation. It is just one equation, and `solve` is asked to solve it for two variables, like

```
from sympy import *
x, y, z = symbols("x, y, z")
solve(x * y + z, z, x)
```

with `1` instead of `z`

Aren't we just facing the problem of presenting the solver with an underdefined situation?

**Comment by theWiseAman** [comment]
@yohad I think you should use the below code.

**Code**
```python
from sympy import *
x, y = symbols("x, y")       
solve(x * y + 1, 1, x, y)
```
**Output**
```powershell
[(-x⋅y, x, y)]
```
I think the bug you mentioned wasn't a bug. It wasn't solvable in terms of just `x` only that's why it reported that. You should mention `y` also as a variable.

**Comment by sylee957** [comment]
This is garbage-in garbage-out situation, and 
We already allow defining `Symbol('0'), Symbol('1')` so even if we try to raise errors for this, we need to think of other cases for consistency.

**Comment by cyclotomicextension** [comment]
I ran the same code as OP provided and got `[0]`

**Comment by Sourabh5768** [comment]
Dear team,

I am excited to contribute to this project and offer my skills. Please let me support the team's efforts and collaborate effectively. Looking forward to working with you all.

**Comment by theWiseAman** [comment]
@hanspi42 @oscarbenjamin Should we close this issue?

**Comment by hanspi42** [comment]
Nobody objects to closing ;)
