### ISSUE TITLE
Lambdify slowed down by automated docstring

### ISSUE THREAD

**Issue by TJStienstra** [sympy/sympy#24743]
When experimenting with some mechanics problem I ran into the problem of a long runtime of `lambdify`. Using line profile I found that of the approximate 7 hours of running `lambdify` 84.8% was spend on [expr_str = str(expr)](https://github.com/sympy/sympy/blob/b0a27be36c69dc48d7b2145be82b77d5bffc56a0/sympy/utilities/lambdify.py#L898) (additionally 1.6% was spend on wrapping this string).

Would it be an option to either have a timeout on this line or a keyword argument in `lambdify` to not put the expression in the docstring? Another option would be to have some custom to string function, that just figures out the first 78 characters, as only the first 78 are put into the docstring.

**Comment by TJStienstra** [comment]
Here is some simple code, which shows similar behaviour:
```py
from sympy import lambdify, symbols, S, eye, zeros, Matrix


def faddeev_leverrier(A):
    assert A.is_square

    n = A.shape[0]
    Mk = zeros(n, n)
    In = eye(n)
    c = [S.One]

    for k in range(1, n + 1):
        Mk = A * Mk + c[-1] * In
        ck = -(A * Mk).trace() / k
        c.append(ck)

    detA = c[-1]
    adjA = Mk
    pA = c

    if n % 2 == 1:
        detA = -detA
    else:
        adjA = -adjA
    return detA, adjA, pA


def inv(A):
    detA, adjA, pA = faddeev_leverrier(A)
    if detA == 0:
        raise ZeroDivisionError
    return adjA / detA


n = 4
A = Matrix(n, n, symbols(f'a:{n * n}'))
A_inv = inv(A)

lambdify(symbols(f'a:{n * n}'), A_inv, cse=True)
```

**Comment by moorepants** [comment]
I'd be fine with disabling the equation in the docstring entirely. Even for short equations if dummies are subbed in it is unreadable. It only really adds something to the simplest of equations. The docstring should show the expected inputs and outputs (type, shape, etc).

**Comment by bjodah** [comment]
Please don't disable docstrings by default. At least I find them very useful. I'm open to some heuristic which turns it off for large expressions (arguably it's only useful for relatively small expressions). Maybe `count_ops` is useful? (I'm hoping it's a cheap evaluation)

**Comment by TJStienstra** [comment]
`count_ops` can also get expensive, though I would deem it quite useful to know (especially if `cse=True`). I would really be pro if there is an option to just somehow get the first 78 characters of the string without going through the entire structure. Difficulty is that the expression can also be a tuple of lists of tuples of expressions or something.

**Comment by bjodah** [comment]
Maybe a cheaper heuristic could be made, e.g.:
```pycon
>>> count_ops(A_inv)
33776

>>> def metric_pre(e):
...     i = 0
...     for arg in preorder_traversal(e):
...         i += 1
...     return i
... 

>>> def metric_post(e):
...     i = 0
...     for arg in postorder_traversal(e):
...         i += 1
...     return i
... 

>>> 

>>> metric_pre(A_inv)
68405

>>> metric_post(A_inv)
68405

>>> %timeit count_ops(A_inv)
77.8 ms ± 243 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)

>>> %timeit metric_pre(A_inv)
24.6 ms ± 654 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)

>>> %timeit metric_post(A_inv)
19.5 ms ± 39.3 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

```

**Comment by moorepants** [comment]
> Maybe count_ops is useful?

count_ops is quite expensive for large expressions.

**Comment by bjodah** [comment]
This is cheap:

```pycon
>>> def too_big_for_docstring(expr, limit=200):
...     i = 0
...     for _ in postorder_traversal(expr):
...         i += 1
...         if i > limit:
...             return True
...     return False
... 

>>> too_big_for_docstring(A_inv)
True

>>> %timeit too_big_for_docstring(A_inv)
58.8 µs ± 62.8 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)

```

so we can add a kwarg to lambdify called e.g. "include_docstring", it could default to a number, e.g. 1000, which is used as the `limit` argument for too_big_for_docstring. Passing `False` or `0` disables docstring unconditionally, passing `True` or `-1` enables it unconditionally. And perhaps we should disallow `1` since it's hard to know if the user intended to pass `True` or wanted to disable printing by setting the limit very low. I guess the limit corresponds to "maximum number of nodes in the expression tree for which a docstring is generated".

**Comment by moorepants** [comment]
Here is an example with 2.6M operations:
```
Python 3.8.15 | packaged by conda-forge | (default, Nov 22 2022, 08:46:39) 
Type 'copyright', 'credits' or 'license' for more information
IPython 8.4.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from sympy import postorder_traversal

In [2]: from sympy.physics.mechanics.models import n_link_pendulum_on_cart

In [3]: import sympy as sm

In [4]: import sympy.physics.mechanics as me

In [5]: %time sys = n_link_pendulum_on_cart(25)
CPU times: user 27.9 s, sys: 68.5 ms, total: 27.9 s
Wall time: 27.9 s

In [6]: %time f = sum((sys.mass_matrix_full @ sys.forcing_full)[:])
CPU times: user 2.79 s, sys: 17 µs, total: 2.79 s
Wall time: 2.79 s

In [7]: %time f.count_ops()
CPU times: user 25.4 s, sys: 51.9 ms, total: 25.4 s
Wall time: 25.4 s
Out[7]: 2634302

In [8]: var_syms = list(me.find_dynamicsymbols(f))

In [9]: syms = list(f.free_symbols); syms.remove(me.dynamicsymbols._t)

In [10]: args = syms + var_syms

In [11]: %time sm.lambdify(args, f, cse=True)
CPU times: user 1min 27s, sys: 832 ms, total: 1min 28s
Wall time: 1min 28s
Out[11]: <function _lambdifygenerated(l16, m3, l22, g, l20, l10, l14, l9, m19, m11, l0, l6, m20, m8, m25, l18, m9, m7, l19, l4, m22, m4, l2, m14, m6, m0, l5, m1, m15, l11, m21, l24, m17, m18, l3, m12, l13, m2, m24, m23, l17, l7, l8, m10, l12, l1, m13, l15, l21, l23, m16, m5, _Dummy_20432, _Dummy_20430, _Dummy_20423, _Dummy_20393, _Dummy_20386, _Dummy_20431, _Dummy_20397, _Dummy_20383, _Dummy_20403, _Dummy_20413, _Dummy_20392, _Dummy_20421, _Dummy_20385, _Dummy_20411, _Dummy_20427, _Dummy_20381, _Dummy_20406, _Dummy_20422, _Dummy_20415, _Dummy_20407, _Dummy_20390, _Dummy_20400, _Dummy_20419, _Dummy_20402, _Dummy_20388, _Dummy_20410, _Dummy_20425, _Dummy_20394, _Dummy_20417, _Dummy_20404, _Dummy_20420, _Dummy_20398, _Dummy_20416, _Dummy_20405, _Dummy_20399, _Dummy_20389, _Dummy_20408, _Dummy_20387, _Dummy_20396, _Dummy_20426, _Dummy_20429, _Dummy_20409, _Dummy_20395, _Dummy_20414, _Dummy_20391, _Dummy_20428, _Dummy_20424, _Dummy_20418, _Dummy_20382, _Dummy_20412, _Dummy_20401, _Dummy_20384)>

In [12]: %paste
>>> def too_big_for_docstring(expr, limit=200):
...     i = 0
...     for _ in postorder_traversal(expr):
...         i += 1
...         if i > limit:
...             return True
...     return False

## -- End pasted text --

In [14]: too_big_for_docstring(f)
Out[14]: True

In [15]: %timeit too_big_for_docstring(f)
95.5 µs ± 658 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)
```

`too_big_for_docstring()` looks like a nice solution. Thanks @bjodah .

**Comment by brocksam** [comment]
@bjodah are you planning on submitting a PR for this? Or can I do it to help you out?

**Comment by brocksam** [comment]
PR #24754 opened for this.

**Comment by Peter230655** [comment]
> > Maybe count_ops is useful?
> 
> 
> 
> count_ops is quite expensive for large expressions.

I find it very useful to get an idea how large my mass matrices and force vectors are. Compared to the time it takes to get Kane's equations with large ops counts, I do not think, it adds that much (of course only my 'feel' I did not do any statistics)

**Comment by moorepants** [comment]
I don't think we want to be using count_ops in library code for things that might see large expressions. It will just add undue slowness. It would be nice to speed up count_ops though. I suspect that it must not be very optimized.

**Comment by Peter230655** [comment]
...but you are not against using count_ops as a 'stand alone' method to be used in sympy.physics.mechanics code, like I write it, so I can see how large the terms are?

**Comment by brocksam** [comment]
> ...but you are not against using count_ops as a 'stand alone' method to be used in sympy.physics.mechanics code, like I write it, so I can see how large the terms are?

It's absolutely fine for you to use `count_ops` in your code that use `sympy.physics.mechanics`. It is just slow for large expressions, which is why we'd want to avoid using it internally in library code. But if you're happy with that slowness in your specific use case, then by all means use it as much as you want.

**Comment by Peter230655** [comment]
Thanks, Sam, all clear!
