### ISSUE TITLE
Potential Bug in sympy/tensor/array/array_derivatives.py

### ISSUE THREAD

**Issue by Skylion007** [sympy/sympy#24742]
I was doing some static analysis and found an if statement that looks like a bug on line 112: https://github.com/sympy/sympy/blob/b0a27be36c69dc48d7b2145be82b77d5bffc56a0/sympy/tensor/array/array_derivatives.py#L115
```python
if isinstance(expr, MatrixCommon) or isinstance(expr, MatrixCommon):
```
 , but both sides of that expression are redundant. Is it suppose to be?
```python
if isinstance(expr, MatrixCommon) or isinstance(v, MatrixCommon):
```

**Comment by sylee957** [comment]
I think that it would be good to provide a unit test example that covers that case as well. It is unlikely that such behavior is covered in test cases.

**Comment by Skylion007** [comment]
@sylee957 So it looks like the bug would occur when v is a MatrixCommon but expr is a MatrixExpr.

**Comment by Skylion007** [comment]
@sylee957 Turns out the code was covered, but just the test case was incorrect. I have fixed the bug and the test case in the PR.

**Comment by Skylion007** [comment]
Yikes, this bug has been known for two years and no one bothered to fix it: https://github.com/sympy/sympy/commit/e9b3849b9bd922219f53fd1316ef822d3904239f#r56905951
