### ISSUE TITLE
plot3d Glitching Planes Issue?

### ISSUE THREAD

**Issue by hugistaken** [sympy/sympy#24773]
Hi, I'm trying to plot this equation using plot3d:

w0*(0.000151266505444914*w0/(Abs(w0) + Abs(w1)) + 7.22456102976048e-6*w1/(Abs(w0) + Abs(w1)))/(Abs(w0) + Abs(w1)) + w1*(7.22456102976048e-6*w0/(Abs(w0) + Abs(w1)) + 0.000126158427486168*w1/(Abs(w0) + Abs(w1)))/(Abs(w0) + Abs(w1))

I'm just seeing three overlapping planes:
![image](https://user-images.githubusercontent.com/102199762/221088588-eceab270-b9eb-40f6-800c-e1f40e8029c0.png)

This is the actual code for plotting that gpt recommended. Equation variables is a list of sympy variables including w0 and w1.:
variance = sympy.Piecewise(
    (0, equation_variables[0] == 0),
    (0, equation_variables[1] == 0),
    (
        portfolio_variance,
        equation_variables[0] != 0 and equation_variables[1] != 0,
    ),
)
variance = sympy.simplify(variance)
plot3d(
    variance,
    (equation_variables[0]),
    (equation_variables[1]),
)

**Comment by oscargus** [comment]
This is most likely related to Matplotlib. The 3D-handling there is a bit ad-hoc when it comes to the ordering of things. It basically orders the objects in a given order and then just draw them, so intersections etc are not handled well, See https://matplotlib.org/stable/api/_as_gen/mpl_toolkits.mplot3d.art3d.Poly3DCollection.html#mpl_toolkits.mplot3d.art3d.Poly3DCollection.set_zsort

Not sure if a `zsort` argument can be passed through from `plot3D` though (and it may break other cases...).

If you use the pygletplot backend (if that works on your platform), it will have proper OpenGL-based 3D rendering.

**Comment by hugistaken** [comment]
It's alright, I was able to get it done with other graphing libraries.
