### ISSUE TITLE
Speed up KanesMethod _f_d computation

### ISSUE THREAD

**Issue by TJStienstra** [sympy/sympy#24790]
When I was experimenting with the numerical stability in `KanesMethod` I ran into some extremely big expressions, this resulted in `KanesMethod` becoming rather slow. When profiling I saw that I could actually spend over 90% of the time on the `msubs` to compute the forcing vector ([code line](https://github.com/sympy/sympy/blob/4f48aad04cdb34e31e821ef9f6e9aa1af0ac637d/sympy/physics/mechanics/kane.py#L458)).

Here is a quick explanation of what `_f_d` actually is. `_f_d` is as already mentioned the forcing vector. It is the part in the equations of motion that is independent of the $\dot{\bar{u}}$'s. See the equation below (note that this is only part of the equations of motion).
$$k_d \dot{\bar{u}} = \bar{f}_d$$

Coming back to the problem there are basically two approaches:
- Speed up `msubs`. `xreplace` might actually be faster (not sure, this would need some testing/investigation).
- Look whether there is a smarter way to compute $\bar{f}_d$.

I'd like to go for the last option in this issue. Currently we choose to write out the entire equations to then go through the $\dot{\bar{u}}$'s by zeros. The equations of motion exist out of two parts:
- $\bar{f}_r$ (`self._fr`): generalized active forces
- $\bar{f}^*_r$ (`self._frstart`): generalized inertia forces

Let us first discuss the generalized active forces. The generalized active forces are basically the loads, i.e. forces and torques, acting upon a system mapped to the configuration manifold, which is based on virtual work. It doesn't matter if you don't follow this sentence, the important part is that they depend on purely on the loads. From loads it is known that we generally say that they do not depend on accelerations. This means that we do not have to do a substitution of the $\dot{\bar{u}}$'s for $\bar{f}_r$. For those of you who will complain and say that loads can actually depend on the acceleration. The current implementation of `KanesMethod` will actually the accelerations of these forces to become zero, letting them disappear from both the mass matrix and forcing vector.

Now let's discuss the generalized inertia forces. I failed in writing some mathematical formulas here showing how $\bar{f}^\*_r$ is computed in the code. However what you can basically see especially in [this line](https://github.com/sympy/sympy/blob/4f48aad04cdb34e31e821ef9f6e9aa1af0ac637d/sympy/physics/mechanics/kane.py#L442) that it consists out of a part that is linearly dependent on the $\bar{\dot{u}}$'s and a part that is not, namely `nonMM`. As we already have this split, we can just use `nonMM`. We should just need to add [a similar transformation](https://github.com/sympy/sympy/blob/4f48aad04cdb34e31e821ef9f6e9aa1af0ac637d/sympy/physics/mechanics/kane.py#L449) as is done for $f^*_r$, when there are dependent generalized speeds: `nonMM = nonMM[:p, :]  + (self._Ars.T * nonMM[p:o, :])`

Conclusion. I would like to replace `self._f_d = -msubs(self._fr + self._frstar, udot_zero)` for `self._f_d = -(self._fr - nonMM)` and add `nonMM = nonMM[:p, :]  + (self._Ars.T * nonMM[p:o, :])` under the if statements if there are any dependent generalized speeds. This would include loads that are dependent on the acceleration to the forcing vector, which more clearly shows that they are currently not supported. The main advantage is that it saves traversing the final equations of motion.

Can someone check if all my math was correct here?

**Comment by TJStienstra** [comment]
Just tested the implementation with line profile for one of the Whipple bicycle models I've written. For comparison I left in the old implementation. It has a total of 8 generalized coordinates and 5 velocity constraints. The final answer still matched the values from Basu-Mandal. As for the speed up:
- 45.1% of the time was spend on `self._f_d = -msubs(self._fr + self._frstar, udot_zero)`
- 2.0% of the time was spend on the new implementation.

**Comment by moorepants** [comment]
This example uses the auxiliary speed functionality on the bicycle model: https://github.com/pydy/pydy/pull/462 Could be a quick way to ensure the aux speeds are still handled.

**Comment by moorepants** [comment]
Here is a quick test on speed also:

```
sympy(master)$ ipython
Python 3.8.16 | packaged by conda-forge | (default, Feb  1 2023, 16:01:55) 
Type 'copyright', 'credits' or 'license' for more information
IPython 8.11.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from sympy.physics.mechanics.models import n_link_pendulum_on_cart

In [2]: %time n_link_pendulum_on_cart(20)
CPU times: user 16.2 s, sys: 28.4 ms, total: 16.2 s
Wall time: 16.2 s
Out[2]: <sympy.physics.mechanics.kane.KanesMethod at 0x7f440f607a30>

In [3]:                                                                                                  
Do you really want to exit ([y]/n)? 
sympy(master)$ git checkout sympy-1.11.1
sympy((sympy-1.11.1))$ ipython
Python 3.8.16 | packaged by conda-forge | (default, Feb  1 2023, 16:01:55) 
Type 'copyright', 'credits' or 'license' for more information
IPython 8.11.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from sympy.physics.mechanics.models import n_link_pendulum_on_cart

In [2]: %time n_link_pendulum_on_cart(20)
CPU times: user 21.5 s, sys: 60.3 ms, total: 21.5 s
Wall time: 21.6 s
Out[2]: <sympy.physics.mechanics.kane.KanesMethod at 0x7feb1d9f0a60>
```

**Comment by TJStienstra** [comment]
> This example uses the auxiliary speed functionality on the bicycle model: [pydy/pydy#462](https://github.com/pydy/pydy/pull/462) Could be a quick way to ensure the aux speeds are still handled.

Thanks for sharing. Just ran it comparing the current `master` with some version before this update. When trying to subtract and simplify the full forcing vector it keeps running for a long time, though it should simplify to zero. If I substitute random values between 0 and 1 I get practically the same answer every time, the differences are in the order of E-16

**Comment by moorepants** [comment]
Cool, sounds good!
