### ISSUE TITLE
In a Jupyter Notebook, `xypic_draw_diagram` only outputs a string

### ISSUE THREAD

**Issue by James-G-Hill** [sympy/sympy#24812]
In a cell in my `ipynb`, within `Visual Studio Code`, if I run the following code in a cell the output is a string rather than rendered latex:

```
from sympy.categories import (
    Diagram,
    NamedMorphism,
    Object,
    xypic_draw_diagram
)

G = Object("G")
H = Object("H")
L = Object("L")

t = NamedMorphism(G, H, "t")
s_p = NamedMorphism(H, L, "s`")

s = s_p * t
d = Diagram([t, s_p, s])
d

xypic_draw_diagram(d)
```

The output is:

```
'\\xymatrix{\nG \\ar[r]^{t} & H \\ar[d]^{s`} \\\\\n& L \n}\n'
```

Wrapping the line `xypic_draw_diagram(d)` in the `latex` function only changes the output to the following string:

```
'\\mathtt{\\text{\\textbackslashxymatrix\\{\nG \\textbackslashar[r]\\textasciicircum\\{t\\} \\& H \\textbackslashar[d]\\textasciicircum\\{s`\\} \\textbackslash\\textbackslash\n\\& L \n\\}\n}}'
```

Interestingly, if I use `preview_diagram` then I will receive a `png` output, so it seems that there is rendering taking place in that situation (although it renders to an external file and doesn't appear beneath my Jupyter Notebook cell).

**Comment by oscarbenjamin** [comment]
For `xypic_draw_diagram` the example in the docstring suggests that it is expected to return something like the output that you showed. You probably need to process that externally with xypic to produce graphical output. If you are hoping that vscode would do that then that's a vscode issue.

> Interestingly, if I use `preview_diagram` then I will receive a `png` output, so it seems that there is rendering taking place in that situation

This is also sort of as documented (although the docs are not very clear). Basically preview runs latex on something and produces an image.

**Comment by James-G-Hill** [comment]
Okay, thanks, I think this can be closed then.

**Comment by oscarbenjamin** [comment]
Okay thanks for reporting!
