### ISSUE TITLE
Bug with milli prefix

### ISSUE THREAD

**Issue by FuzzyLitchi** [sympy/sympy#24832]
What happened:
```
In [1]: from sympy.physics.units import milli, W
In [2]: milli*W == 1
Out[2]: True
In [3]: W*milli
Out[3]: watt*Prefix(milli, m, -3, 10)
```
What I expected to happen: milli*W should evaluate to milli watts / mW

`milli*W` or more generally `milli` times some unit evaluates to the number 1. I have tried this with Watts and Volts, I'm not sure what other cases this happens. I'm using sympy version 1.11.1-1 on Arch Linux with Python 3.10.9. If you cannot reproduce I would be happy to be of any assitance.

**Comment by smichr** [comment]
I get a 1 for all of the following (and some are redundant like "V" and "volt"):
```python
W, joule, ohm, newton, volt, V, v, volts, henrys, pa, kilogram, ohms, kilograms, Pa, weber, tesla, Wb, H, wb, newtons, kilometers, webers, pascals, kilometer, watt, T, km, kg, joules, pascal, watts, J, henry, kilo, teslas
```

**Comment by FuzzyLitchi** [comment]
Plus it's only milli.
```
In [65]: for p in PREFIXES:
    ...:     print(p, PREFIXES[p]*W)
    ...:
Y 1000000000000000000000000*watt
Z 1000000000000000000000*watt
E 1000000000000000000*watt
P 1000000000000000*watt
T 1000000000000*watt
G 1000000000*watt
M 1000000*watt
k 1000*watt
h 100*watt
da 10*watt
d watt/10
c watt/100
m 1
mu watt/1000000
n watt/1000000000
p watt/1000000000000
f watt/1000000000000000
a watt/1000000000000000000
z watt/1000000000000000000000
y watt/1000000000000000000000000
```

**Comment by Sourabh5768** [comment]
Dear team,

I am excited to contribute to this project and offer my skills. Please let me support the team's efforts and collaborate effectively. Looking forward to working with you all.

**Comment by 1e9abhi1e10** [comment]
@Sourabh5768  Thanks for showing interest, you don't need to ask for a contribution If you know how to fix an issue, you can just make a pull request to fix it.

**Comment by HieuLCM** [comment]
I looked at the code and change it a little bit to fix this issue. If anyone has time, please take a look at the pull request.
