### ISSUE TITLE
Change type annotation for `Mul`

### ISSUE THREAD

**Issue by sylee957** [sympy/sympy#24871]
https://github.com/sympy/sympy/blob/5c03f65eeab34368bec9a7f76feffaf2f0b7a110/sympy/core/mul.py#L164

This is wrong and should be changed to `tuple[Expr, ...]`

**Comment by 1e9abhi1e10** [comment]
Should I fix this change in #24867?

**Comment by brocksam** [comment]
> https://github.com/sympy/sympy/blob/5c03f65eeab34368bec9a7f76feffaf2f0b7a110/sympy/core/mul.py#L164
> 
> This is wrong and should be changed to `tuple[Expr, ...]`

We need to use `typing.Tuple` here for compatibility with Python 3.8. Alternatively we can use `from __future__ import annotations` to allow use of `tuple` in the type hint. 

See the import of `typing.Tuple`, which for some reason is imported as `tTuple`, perhaps a typo? 

https://github.com/sympy/sympy/blob/5c03f65eeab34368bec9a7f76feffaf2f0b7a110/sympy/core/mul.py#L1

I can't see any name clashes so not sure there's a need to import under an alias.

**Comment by brocksam** [comment]
> Should I fix this change in #24867?

Unrelated issues should probably be in separate PRs.

**Comment by 1e9abhi1e10** [comment]
@sylee957 Same issue in `sympy_parser`?
https://github.com/sympy/sympy/blob/65962f3bf69e5f4b0ff0f5a3dbe72c944de64498/sympy/parsing/sympy_parser.py#L13-L14

**Comment by Vsoni27** [comment]
I have changed all the code but the release note check is not passing
I read the release note documentation but didn't know how to write it.
Please help me out
