### ISSUE TITLE
Polygon.angles needs correction and clarification

### ISSUE THREAD

**Issue by smichr** [sympy/sympy#24885]
SO issue [here](https://stackoverflow.com/questions/75684964/python-sympy-polygon-angles-return-wrong-values) gives an example where external instead of internal angles are being reported.

The routine tries to determine whether the polygon is being defined in a cw or ccw manner by using the orientation in moving from the 2nd to last vertex to the first. Then decides whether an internal or external angle should be computed by comparing the orientation at each vertex.

**Comment by smichr** [comment]
This routine will give the same internal angles regardless of orientation:
```python
def angles(self):
    args = self.vertices
    ret = {}
    direction = [self._isright(args[i-2],args[i-1],args[i]) for i in range(len(args))]
    t = direction.count(True)
    f = len(direction) - t
    assert t != f
    cw = t > f
    for i in range(len(args)):
        a, b, c = args[i - 2], args[i - 1], args[i]
        ang = Ray(b, a).angle_between(Ray(b, c))
        if cw ^ direction[i]:
            ret[b] = 2*S.Pi - ang
        else:
            ret[b] = ang
    return ret
```
I am not sure if direction should be considered or not. It is also possible to have `t==f` as for `Polygon(((0,1),(0,0),(1,1),(1,0))`. I am also not sure what to do in that case.

**Comment by TiloRC** [comment]
I have an idea, though it's a big inelegant: we can simply compute the angles for both cw and ccw and then find the sum of the interior angles. The interior angles of a polygon should always add up to (n-2)*180, so we go with the direction that correctly sums up to 180. The time complexity is still O(n) but admittedly there's probably a better way to do this.

**Comment by smichr** [comment]
> interior angles of a polygon should always add up to (n-2)*180

That's nice -- I had forgotten this simple relationship (blush). We can do better than starting over, though. The sum of the reflex angles (not the definition of the "external" angles) is `2pi(n - 2)` -- this is just twice the sum of the internals. So if the total of the angles computed with `cw=True` divided by pi is too large we just subtract all angles from `2*pi`
```python
def angles(self):
    args = self.vertices
    n = len(args)
    ret = {}
    for i in range(n):
        a, b, c = args[i - 2], args[i - 1], args[i]
        ang = Ray(b, a).angle_between(Ray(b, c))
        if self._isright(a, b, c):
            ret[b] = 2*S.Pi - ang
        else:
            ret[b] = ang
    # internal sum should be pi*(n - 2)
    if (sum(ret.values())/S.Pi/(n - 2)).n() > 1.5:
        two_pi = 2*S.Pi
        for b in ret:
            ret[b] = two_pi - ret[b]
    return ret
```

**Comment by Aadi1605** [comment]
IS IT STILL OPEN? 
 I WANT TO CONTRIBUTE

**Comment by smichr** [comment]
Under the title at the top of the page the word "Open" or "Closed" appears to indicate the status of a PR. And if any pull request mentions this issue you will see a reference to the PR in the discussion thread.

**Comment by TiloRC** [comment]
I like your approach but I don’t think it works in all cases. From what I understand, when we do the calculation wrongly, we’re calculating 2*pi minus each interior angle (not the reflex angles or  the exterior angles). Maybe we call these the complements of the interior angles? 

Notice we would expect the sum of the complements of the interior angles to be `pi*(n+2)`, not `2pi(n - 2)`. Consider that we would expect the sum of all the interior angles and their complements to add up to 
```2*pi*n```
This implies that the complements of the interior angles add up to 
```2*pi*n - (n-2)*pi = pi*(n+2)```

Your implementation depends on the following value to be positive to detect we have calculated the wrong values:
```pi*(n+2)/ ((n-2)*pi) - 1.5```
Or simplified:
```(n+2)/(n-2) - 1.5```
However, if n is greater than 10, say n=11, this method makes a mistake
```(11+2)/(11-2) - 1.5 = -.0555 ```
Thus I suggest subtracting by 1 instead of 1.5

**Comment by smichr** [comment]
The code has been updated to reflect the corrections of @TiloRC (with thanks).

**Comment by TiloRC** [comment]
Does anyone else think that the  _isright() method has a really strange name? In the same file there's a method in the triangle class called is_right() which checks if a triangle is a right triangle. However, _isright() is a static method for the polynomial class that checks if three points are ordered in a cw or ccw manner. Wouldn't it make a lot more sense for it to be named _iscw or _is_cw?


Also, the angles we find when we're wrong are called the conjugates of the interior angles (not the reflex angles, exterior angles, or complements of the interior angles): https://en.wikipedia.org/wiki/Angle#Combining_angle_pairs.

**Comment by TiloRC** [comment]
I tried implementing [smichr](https://github.com/smichr)'s function but there was one test that failed because wrong was None which seemed to be related to another bug which I created an issue for: https://github.com/sympy/sympy/issues/24948.

**Comment by TiloRC** [comment]
I made the change I suggested and the new function passes all test cases.

**Comment by TiloRC** [comment]
I made a pull request that should fix this issue using the code [smichr](https://github.com/smichr) and I worked on.
