### ISSUE TITLE
`simplify(asinh(2)-oo)->0`

### ISSUE THREAD

**Issue by smichr** [sympy/sympy#24928]
The first of the following is [wrong](https://groups.google.com/g/sympy/c/jdPOcIz7ZAY):
```python
>>> simplify(asinh(2)-oo)
0
>>> simplify(asinh(2)+oo)
oo
```
While `simplify(asin(2)-oo)` leaves the `asin(2)` unsimplified (because it is complex), the value of `asinh(2)` is real and finite.

**Comment by ThePauliPrinciple** [comment]
It looks like  `asinh(2).is_real` and `asinh(2).is_complex` return `None`, maybe that is the problem?
