### ISSUE TITLE
`commutative=True` appearing the assumptions of symbols

### ISSUE THREAD

**Issue by cbm755** [sympy/sympy#24931]
I haven't yet bisected this but on SymPy 1.11:

```
x = Symbol('x', positive=True)
x._assumptions.generator
{'positive': True}
```

But on both the 1.12 tag and the `master` branch, we have:

```
x._assumptions.generator
{'positive': True, 'commutative': True}
```

Note: that  `'commutative': True` has appeared despite not being specified explicitly.   I initially thought that https://github.com/sympy/sympy/pull/24895 was related but I may need to bisect to be sure.

**Comment by cbm755** [comment]
Ok it was fairly recent: bisect points to 40f0f6cfa2af216247476d3f416c715fefde6335

Has the release happened?  Is it too late to hold on this?

**Comment by cbm755** [comment]
Wait!  I see from that commit that I can simply use `x._assumptions_orig`.  That's absolutely fine as its a private method anyway.

In that case I don't think this is a regression and I will try to resolve it downstream.  Likely I will come back here and close this.

**Comment by cbm755** [comment]
easy fix downstream, ignore

**Comment by oscarbenjamin** [comment]
Thanks for reporting and investigating.

I commented on gh-8873 at the time I was making that change. I still think that the general change referred to there should be reverted but I just didn't want to do that so close to the 1.12 release.

Can you reply to my question there?
