### ISSUE TITLE
Composition order of permutations when applied to sequences

### ISSUE THREAD

**Issue by Krzmbrzl** [sympy/sympy#24949]
Accdording to the documentation
> The product of two permutations p and q is defined as their composition as functions, (p*q)(i) = q(p(i))

This works great as long as  we are only considering the image of a single point:
```
>>> p = Permutation([1, 0, 2, 3])
>>> q = Permutation([2, 3, 1, 0])
>>> (p * q)(2)
1
>>> q(p(2))
1
>>> p(q(2))
0
```

However, when we instead apply the permutation to a sequence of elements, the evaluation order seems to be exactly the reverse:
```
>>> p = Permutation([1, 0, 2, 3])
>>> q = Permutation([2, 3, 1, 0])
>>> seq = ["a", "b", "c", "d"]
>>> (p * q)(seq)
['d', 'c', 'b', 'a']
>>> q(p(seq))
['c', 'd', 'a', 'b']
>>> p(q(seq))
['d', 'c', 'b', 'a']
```

Does that mean the application to sequences is inconsistent to the evaluation of image points or is there some indirection going on that reverses the apparent evaluation order?

**Comment by oscarbenjamin** [comment]
I'm not sure but see gh-20689 and gh-20719 for some previous discussion related to this.

So we have:
```python
In [8]: seq = range(4)

In [9]: [(p * q)(i) for i in seq]
Out[9]: [3, 2, 1, 0]

In [10]: (p * q)(seq)
Out[10]: [3, 2, 1, 0]

In [11]: [q(p(i)) for i in seq]
Out[11]: [3, 2, 1, 0]

In [12]: q(p(seq))
Out[12]: [2, 3, 0, 1]

In [13]: p(q(seq))
Out[13]: [3, 2, 1, 0]
```
The code handling this is here:
https://github.com/sympy/sympy/blob/1ad6a33e2652151a2e4a5ada196924be4f7c008a/sympy/combinatorics/permutations.py#L1648-L1659

In the scalar case we have
```python
return self._array_form[i]
```
In the sequence case it is:
```python
return [i[j] for j in self._array_form]
```
These do seem to be reversed in some sense. Calling `p(i)` gives `array[i]` where as calling `p(seq)` gives `[seq[i] for i in array]` rather than `[array[i] for i in seq]`. Your list of strings example though shows that it couldn't work that way because we can't index a list with strings though.

Honestly I can't tell from the code what the definition of a permutation is supposed to be here. Maybe the fundamental problem is that `(p * q)` is backwards. If I was to expect any identity to hold here it would be that `(p * q)(x) = p(q(x))`. According to that it is this one that is inconsistent with all of the others:
```python
In [11]: [q(p(i)) for i in seq]
Out[11]: [3, 2, 1, 0]
```
Perhaps the change should be:
```diff
diff --git a/sympy/combinatorics/permutations.py b/sympy/combinatorics/permutations.py
index 6c82372..1e20994 100644
--- a/sympy/combinatorics/permutations.py
+++ b/sympy/combinatorics/permutations.py
@@ -1651,7 +1651,7 @@ def __call__(self, *i):
                     raise TypeError(
                         "{} should be an integer between 0 and {}"
                         .format(i, self.size-1))
-                return self._array_form[i]
+                return self._array_form.index(i)
             # P([a, b, c])
             if len(i) != self.size:
                 raise TypeError(
```
Then we have:
```python
In [18]: from sympy.combinatorics import Permutation

In [19]: p = Permutation([1, 0, 2, 3])

In [20]: q = Permutation([2, 3, 1, 0])

In [21]: seq = range(4)

In [22]: [p(q(i)) for i in seq]  # different from current behaviour
Out[22]: [3, 2, 1, 0]

In [23]: p(q(seq))
Out[23]: [3, 2, 1, 0]

In [24]: (p * q)(seq)
Out[24]: [3, 2, 1, 0]

In [25]: [(p * q)(i) for i in seq]
Out[25]: [3, 2, 1, 0]
```
Does that all seem correct?

**Comment by oscarbenjamin** [comment]
Maybe the confusion in gh-20689 follows from just not qute identifying the bug here.

**Comment by jksuom** [comment]
> Does that mean the application to sequences is inconsistent to the evaluation of image points

Yes, it does. The application `p(x)`, where `p` is a permutation of size `n`, has two different meanings depending on the type of `x`:
* If `x` is an integer `i` in `range(n)`, then `p(x)` is defined as the image of `i` under the bijective mapping `p` of `range(n)` onto itself.
* If `x = (x0, ..., xn-1)` is a sequence of length `n`, then `p(x)` is the sequence `y = (y0, ..., yn-1)` where `yi = xp(i)` for each `i` in `range(n)`.

These two definitions behave differently under composition of two permutaions `p` and `q`. If `x` is an integer, then `p(q(x)` is given by $(p\circ q)(x)$ where $p\circ q$ denotes the standard composition of mappings, but if `x` is a sequence, then `p(q(x))` is $(q\circ p)(x)$.
This means that there are two possible ways of defining the composition `p*q` of permutations, either $p\circ q$ or $q\circ p$. It is customary in the theory of permutations to use the latter definition, and it has also been chosen in SymPy.

**Comment by Krzmbrzl** [comment]
> This means that there are two possible ways of defining the composition p*q of permutations, either or . It is customary in the theory of permutations to use the latter definition, and it has also been chosen in SymPy.

Yeah - that's the issue of right-to-left vs left-to-right. See also [the answers to this post](https://mathoverflow.net/q/151258).

> These two definitions behave differently under composition of two permutaions p and q

This confused me (a lot), but I have now figured it out why the composition works the way it does for sequences (I think for applying permutations on integers, it is relatively straight forward to see why it works that way).
I have [written out my reasoning / proof](https://math.stackexchange.com/q/4663548/573633) for this in a Q&A style. I'm sharing this here in case someone else has trouble figuring this out by themselves.

Anyway, this means that SymPy is working as intended and this is not a bug. Thus, I'm closing this issue.

**Comment by jksuom** [comment]
It seems that some additional explanation might be helpful:

For `i` in `range(n)`, if `x` has items $x_i$, then `q(x) = y` has items $y_i = x_{q(i)}$, so `p(q(x)) = p(y) = z` has items $z_i = y_{p(i)} = x_{q(p(i))} = x_{(q\circ p)(i)}$.
Hence $p(q(x)) = (q\circ p)(x)$.
