### ISSUE TITLE
ReferenceFrame should have attributes to access unit dyads and its unit dyadic

### ISSUE THREAD

**Issue by moorepants** [sympy/sympy#24965]
ReferenceFrame has `.x,.y,.z` to access the unit vectors. It would be nice if you could access unit dyads also with `.xx,.xy,.xz,...`. Then you can construct dyadics without having to do `outer(N.x, N.x)`. This is a simple fix and addition. It would need to be documented and shown in some examples.

**Comment by moorepants** [comment]
We could add an attribute for the unit dyadic. Maybe `N.dyadic` or `N.unit`. Not sure what the best name would be.

**Comment by moorepants** [comment]
Yes that's the idea. No linear algebra knowledge needed. `.xx` should simply execute `outer(self.x, self.x)`.

**Comment by abhishek-kuma** [comment]
I made a function inside ReferenceFrame class that returns unit_dyadics of a given reference frame.
The code is like this
`def unit_dyadics(N):
    """
    Returns a dictionary of unit dyadics in the given reference frame N.
    parameters :
        N : ReferenceFrame
        The reference frame in which to create the unit dyadics.

    returns :
        dict
        A dictionary of unit dyadics with keys of the form "xx", "xy", "xz", etc.
    """
    unit_dyadics = {}
    for i, b1 in enumerate(N):
        for j, b2 in enumerate(N):
            unit_dyadics[b1.name + b2.name] = outer(b1, b2) if i == j else 0
    return unit_dyadics`

**Comment by abhishek-kuma** [comment]
def unit_dyadics(N):
    """
    Returns a dictionary of unit dyadics in the given reference frame N.
    parameters :
        N : ReferenceFrame
        The reference frame in which to create the unit dyadics.

    returns :
        dict
        A dictionary of unit dyadics with keys of the form "xx", "xy", "xz", etc.
    """
    unit_dyadics = {}
    for i, b1 in enumerate(N):
        for j, b2 in enumerate(N):
            unit_dyadics[b1.name + b2.name] = outer(b1, b2) if i == j else 0
    return unit_dyadics

**Comment by moorepants** [comment]
> I made a function inside ReferenceFrame class that returns unit_dyadics of a given reference frame.

No, that is not what we are looking for. A unit dyadic is simply an identity matrix.

**Comment by moorepants** [comment]
More info on unit dyads and the unit dyadic can be found here: https://moorepants.github.io/learn-multibody-dynamics/mass.html
