### ISSUE TITLE
Mark sympy.test as a *test*, so it doesn't block pytest when I use "from sympy import *" in a test file.

### ISSUE THREAD

**Issue by canercetin-randomguy** [sympy/sympy#25015]
I am not sure how can I explain this better, but please read this issue https://github.com/pytest-dev/pytest/issues/10859#issuecomment-1493407470

Thanks.

sympy.test => https://github.com/sympy/sympy/blob/master/sympy/testing/runtests.py#L336

**Comment by oscarbenjamin** [comment]
> I am not sure how can I explain this better, but please read this issue

That doesn't explain anything. You shouldn't use `from sympy import *` in a pytest module I guess. I don't see what could or should be changed in sympy here.

**Comment by oscarbenjamin** [comment]
Closing for now. This can be reopened if a clearer suggestion or rationale is given.
