### ISSUE TITLE
`parse_latex` throws `ImportError`

### ISSUE THREAD

**Issue by baloe** [sympy/sympy#25031]
I keep getting 
```
ImportError: LaTeX parsing requires the antlr4 Python package, provided by pip (antlr4-python3-runtime) or conda (antlr-python-runtime), version 4.10
```
when trying to parse Latex, e.g. 
```python
from sympy.parsing.latex import parse_latex
expr = parse_latex(r"\frac {1 + \sqrt {\a}} {\b}")
```
(example from https://docs.sympy.org/latest/modules/parsing.html#experimental-mathrm-latex-parsing)

I did install with
```
pip install antlr4-python3-runtime
```

Relevant packages:
```
# Name                    Version                   Build  Channel
antlr4-python3-runtime    4.12.0                   pypi_0    pypi
sympy                     1.11.1          pypyh9d50eac_103    conda-forge
```

**Comment by sylee957** [comment]
Did you tried pinning the version to `4.10.0`

I see in the tutorial
https://docs.sympy.org/latest/modules/parsing.html#runtime-installation

**Comment by baloe** [comment]
You're right, I oversaw that!
 It does work when pinning to `4.10.0`. Thanks!
