### ISSUE TITLE
Refactor `sympy.physics.mechanics._pathway` to use `extension_velocity` instead of `shortening_velocity`

### ISSUE THREAD

**Issue by brocksam** [sympy/sympy#25035]
The `shortening_velocity` attribute should be refactored to `extension_velocity` as this is more intuitive for mechanics problems.

https://github.com/sympy/sympy/blob/480254b6dd53f8d0b54ec757e438ad2d19a50cd9/sympy/physics/mechanics/_pathway.py#L72-L76

The reason being that using `shortening_velocity`  causes some confusion when creating a simple model like a forced mass-spring-damper system; the spring stiffness needs to be defined as `stiffness * pathway.length` while the damper damping needs to be defined as `damping * -pathway.shortening_velocity` in order to generate the correct EoMs. Having to use different signs for terms that will end up in the EoMs with the same sign is unintuitive.

**Comment by moorepants** [comment]
Not sure if this helpful but I talk about some related things here: https://moorepants.github.io/learn-multibody-dynamics/loads.html#springs-dampers (not too in depth).

**Comment by brocksam** [comment]
> Not sure if this helpful but I talk about some related things here: https://moorepants.github.io/learn-multibody-dynamics/loads.html#springs-dampers (not too in depth).

This is useful, thanks!

**Comment by brocksam** [comment]
Having ruminated on this further and after reading the linked resource above, I believe that the most logical conventions in `sympy.physics.mechanics` would be that rates of change in length of pathways are positive extensions and that expansile forces of actuators are positive. Equivalent conventions should be used for the `TorqueActuator` class.

**Comment by moorepants** [comment]
You can probably choose any sign conventions you want, but the key thing is to document them clearly so people know how to use them. We have this same issue in the continuum mechanic package. There has been lots of confusion on the sign conventions.
