### ISSUE TITLE
`python setup.py test` is fails due to assumption of incorrect encoding

### ISSUE THREAD

**Issue by AllenJonathan** [sympy/sympy#25047]
When I try to run the tests using the `python setup.py test` in the command prompt I get this error.

`
Traceback (most recent call last):
  File "D:\Projects\Google Summer of Code\sympy\setup.py", line 308, in <module>
    long_description=(Path(__file__).parent / 'README.md').read_text(),
  File "C:\Users\Allen\AppData\Local\Programs\Python\Python310\lib\pathlib.py", line 1135, in read_text
    return f.read()
  File "C:\Users\Allen\AppData\Local\Programs\Python\Python310\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 9463: character maps to <undefined>
`

There line `long_description=(Path(__file__).parent / 'README.md').read_text()` causes the error. Upon trying to solve I found that it is using cp1252 encoding to decode the READme file. Just adding a `long_description=(Path(__file__).parent / 'README.md').read_text(encoding="UTF-8")` solves the problem.

**Comment by sylee957** [comment]
This is likely fixed in #24964
Have you tried `master`?

**Comment by AllenJonathan** [comment]
Sorry @sylee957. My local repo seems wasn't up to date. I'm closing the issue.
