### ISSUE TITLE
Lambdify with cse wrong result

### ISSUE THREAD

**Issue by jokasimr** [sympy/sympy#25043]
Using `lambdify` with `cse=True` sometimes returns the wrong result.
Minimal example:
```python
import sympy as sp
c = sp.symbols("c")
x = sp.symbols("x0", real=True)
poly = c*x**2 + c*(x**4 - x**2)

f = sp.lambdify((c, x), poly, cse=True)  #  <- `cse=True` makes the difference
g = sp.lambdify((c, x), poly, cse=False)

#  wrong result, AssertionError: 256 /= 16
assert f(1, 2) == g(1, 2), f"{f(1, 2)} /= {g(1, 2)}"
```

**Cause**
The issue seems to be related to the filtering of symbols to be excluded in the `tree_cse` function around here [https://github.com/sympy/sympy/blob/master/sympy/simplify/cse_main.py#L655](https://github.com/sympy/sympy/blob/53a36aa71956c988e2b6ce33db0d8cbcbdfacfbb/sympy/simplify/cse_main.py#L655).

From what I can tell, the cse method aims to avoid name collisions between symbols already in the expression and the symbols representing common subexpressions.
This is done by adding all symbols found in the expression to an `excluded_symbols` set and filtering the `symbols` iterator to exclude them.
However, symbols are equal iff their names and assumptions match, so this approach does not avoid symbol *name collisions*:

```python
from sympy import Symbol
Symbol("x") in {Symbol("x", real=True)}  # returns False
```

**Suggested solution**
In the `tree_cse` function, instead of filtering `symbols` from all symbols occuring in the expression, 
filter from all symbols sharing `name` with some symbol in the expression.

If this can be considered a sufficient fix for the issue I'd be happy to provide a PR.

**Comment by bjodah** [comment]
I think your analysis and proposed fix is spot on. A PR would be most welcome.

**Comment by ThePauliPrinciple** [comment]
I'm not so sure the name clash issue should be handled by CSE. In SymPy, symbols with different assumptions are considered to be different. I think it is better to solve this in lambdify or the code printers, since the issue isn't that CSE is doing something that it shouldn't, but that lambdify does not process an expression correctly because there is a variable name clash when printing.

You can get the same issue without using CSE:

```python
from sympy import Symbol, lambdify
x0 = Symbol('x0')
y0 = Symbol('y0')
x0r = Symbol('x0', real = True)
fx = lambdify((x0), x0+x0r)
fy = lambdify((x0), x0+y0)
assert fy(1)==(x0+y0).subs(x0, 1) #no issue without name clash
assert fx(1)==(x0+x0r).subs(x0, 1) # issue with name clash without CSE
```

**Comment by bjodah** [comment]
But it already does (and has to). The only difference will be that we are somewhat stricter. Which will also be good for non-codegen purposes (it's super confusing to print expressions in a notebook which contains different symbols with the same name...)

And I think that the name clash in lambdify without CSE that you point out should also be fixed.
