### ISSUE TITLE
Piecewise plot only plots from -10 to 10

### ISSUE THREAD

**Issue by 1nikolas** [sympy/sympy#25041]
This looks to me like a feature but didn't find any obvious way to plot this beyond -10 and 10.

Here is a simplified example.

Code:
```
import sympy as sym

t = sym.symbols('t')
x = sym.Piecewise(
        (0, (t>-2) & (t<=2)),
        (1, True)
    )
sym.plot(x, xlim=(-20,20))
```

Output:
![image](https://user-images.githubusercontent.com/30593419/230640979-57627035-951a-45a9-83ad-5244cd5ecb10.png)

Thanks

**Comment by sylee957** [comment]
`xlim` is usally an option to crop the range of the existing plots, and it can't draw the plots automatically beyond the pre-drawn plot.
If you want to draw the plots with more larger range, you should just control the range instead.

```python
t = sym.symbols('t')
f = sym.Piecewise(
        (0, (t>-2) & (t<=2)),
        (1, True)
    )
sym.plot(f, (t, -20, 20))
```

**Comment by 1nikolas** [comment]
thanks this works
