### ISSUE TITLE
print_mathml uses the deprecated table <mfenced>

### ISSUE THREAD

**Issue by OrzTanLaLa** [sympy/sympy#25044]
`<mfenced>` is deprecated and non-standard(according to https://developer.mozilla.org/en-US/docs/Web/MathML/Element/mfenced).
1.`<mfenced close="}" open="{">` has no affect on Edge.But `print_mathml()` generates `<mfenced close="}" open="{">`.It should be taken place by `<mo>`.
2.When turn x*sqrt(y) into mathml, x is between `<mfenced><mrow>` and `</mrow></mfenced>`, but `<mfenced>` doesn't seem to have any meaning, that is, there won't be difference if you delete `<mfenced></mfenced>`.So `<mfenced>` in this situation should be cut out.
3.In other cases, `<mfenced>` s are also not supposed to be used because it's deprecated and non-standard.
All in all, `<mfenced>` shouldn't be use at all.

**Comment by OrzTanLaLa** [comment]
I'm too lazy to check all code, but found out that `<mfenced>` is mainly used for brackets, such as:
https://github.com/sympy/sympy/blob/94fc2abcc5bce59c19476f5a404f8c773d3510b9/sympy/printing/mathml.py#L663
https://github.com/sympy/sympy/blob/94fc2abcc5bce59c19476f5a404f8c773d3510b9/sympy/printing/mathml.py#L750
https://github.com/sympy/sympy/blob/94fc2abcc5bce59c19476f5a404f8c773d3510b9/sympy/printing/mathml.py#L1105
and so on...I'm too lazy to going on.
But something interesting is to use <mfenced> for functions:
https://github.com/sympy/sympy/blob/94fc2abcc5bce59c19476f5a404f8c773d3510b9/sympy/printing/mathml.py#L1167
It saved a lot of things : )
But there're also something I can't understand, for example:
https://github.com/sympy/sympy/blob/94fc2abcc5bce59c19476f5a404f8c773d3510b9/sympy/printing/mathml.py#L950
I wonder why sum needs `<mfenced>`(Forgive me for not understanding `<mfenced>` well)
In total, there're 32 `<mfenced>`s in https://github.com/sympy/sympy/blob/master/sympy/printing/mathml.py,either for brackets or for...I don't know.

**Comment by OrzTanLaLa** [comment]
Oh,There's one mistake in my first comment.

> 2.When turn x*sqrt(y) into mathml, x is between <mfenced><mrow> and </mrow></mfenced>, but <mfenced> doesn't seem to have any meaning, that is, there won't be difference if you delete <mfenced></mfenced>.So <mfenced> in this situation should be cut out.

There isn't a problem.Instead, it was (x+y)*sqrt(x),so there's certainly a `<mfenced>`.
But it's sure that `<mfenced>` shouldn't be used.

**Comment by OrzTanLaLa** [comment]
Oh,There's one mistake in my first comment.

> 2.When turn x*sqrt(y) into mathml, x is between <mfenced><mrow> and </mrow></mfenced>, but <mfenced> doesn't seem to have any meaning, that is, there won't be difference if you delete <mfenced></mfenced>.So <mfenced> in this situation should be cut out.

There isn't a problem.Instead, it was (x+y)*sqrt(x),so there's certainly a `<mfenced>`.
But it's sure that `<mfenced>` shouldn't be used.

**Comment by sylee957** [comment]
I think that we may need some changes, but it can be nontrivial because `mfenced` is used a lot.

**Comment by sylee957** [comment]
The deprecation was quite modern, and sympy had not been active for updating the mathml printer.
