### ISSUE TITLE
Substituting Tensor into Mul returns Mul rather than TensMul

### ISSUE THREAD

**Issue by Kishore96in** [sympy/sympy#25051]
When I substitute a tensor into a Mul (using `subs` or `replace`), I would expect the output to be a `TensMul`, but it remains a `Mul`.

(in isympy prompt)
```
In [1]: from sympy import symbols
In [2]: from sympy.tensor.tensor import TensorIndexType, tensor_indices, TensorHead
In [3]: R3 = TensorIndexType('R3', dim=3)
In [4]: i = tensor_indices("i", R3)
In [5]: K = TensorHead("K", [R3])
In [7]: expr = (x*2).replace(x, K(i))
In [9]: type(expr)
Out[9]: sympy.core.mul.Mul
```

This is a problem in more complicated expressions, since the user might not even notice that one of the terms has the wrong type, and then they might wonder why various methods (e.g. expand) don't work as expected.

One possible way to fix this (but only for `subs`) is to check in `Mul._eval_subs` if the argument `new` is a `TensExpr`, and cast the output accordingly.

However, this would not fix the issue for `xreplace` and `replace`. Any ideas on how this can be fixed? Is it acceptable to add a check in `AssocOp.__new__`?

Sympy version: 1.11.1
Python version: 3.10.10
OS: Arch Linux

**Comment by asmeurer** [comment]
This should be handled with postprocessors, similar to https://github.com/sympy/sympy/blob/master/sympy/matrices/expressions/matexpr.py#L518. 

More generally, it might be a good idea to make tensor expressions and matrix expressions share some code, but that could be a lot of work.

**Comment by Kishore96in** [comment]
I've made a PR: https://github.com/sympy/sympy/pull/25056
