### ISSUE TITLE
`Determinant.doit()` should allow a recurisve call to `doit()` by calling `doit(deep=True)`

### ISSUE THREAD

**Issue by mrettl** [sympy/sympy#25053]
Considering:
```python
>>> import sympy as sy
>>> sy.__version__
'1.11.1'
>>> A = sy.eye(2, 2)
>>> B = sy.eye(2, 2)
>>> AB = sy.MatMul(A, B)
>>> detAB = sy.Determinant(AB)
>>> detAB.doit()
Determinant(Matrix([
[1, 0],
[0, 1]]))**2
```

I would expect `detAB.doit()` to return 1 instead of a squared determinant of the identity matrix.
The reason is, that the determinat does not call `doit()` recursivly.
A recursive call (as shown below) would lead to the expected result.
```python
>>> sy.Determinant(AB.doit()).doit()
1
```

The behaviour of  [`Determinant.doit()`](https://github.com/sympy/sympy/blob/26f7bdbe3f860e7b4492e102edec2d6b429b5aaf/sympy/matrices/expressions/determinant.py#L45) is unexpected, since most other matrix expression perform a recursive call by default:

- [`Inverse.doit()`](https://github.com/sympy/sympy/blob/26f7bdbe3f860e7b4492e102edec2d6b429b5aaf/sympy/matrices/expressions/inverse.py#L66)
- [`Trace.doit()`](https://github.com/sympy/sympy/blob/26f7bdbe3f860e7b4492e102edec2d6b429b5aaf/sympy/matrices/expressions/trace.py#L106)
- ...

Would be nice, if the current version:
```python
class Determinant(Expr):
    ...
    def doit(self, expand=False, **hints):
        try:
            return self.arg._eval_determinant()
        except (AttributeError, NotImplementedError):
            return self
```

could be replaced by something like this:

```python
class Determinant(Expr):
    ...
    def doit(self, **hints):
        arg = self.arg
        if hints.get('deep', True) and isinstance(arg, Basic):
            arg = arg.doit(**hints)
        _eval_determinant = getattr(arg, '_eval_determinant', None)
        if _eval_determinant is not None:
            result = _eval_determinant()
            return result if result is not None else Determinant(arg)
        else:
            return Determinant(arg)
```
This is inspired by [`Transpose.doit()`](https://github.com/sympy/sympy/blob/26f7bdbe3f860e7b4492e102edec2d6b429b5aaf/sympy/matrices/expressions/transpose.py#L33)

**Comment by oscarbenjamin** [comment]
Yes, that seems reasonable.

Not catching `AttributeError` is also good. I'm not sure if there is a need to catch `NotImplementedError`. It shouldn't be necessary to check `isinstance(arg, Basic)`.

I guess I'd write that as:
```python
    def doit(self, **hints):

        arg = self.arg
        if hints.get('deep', True):
            arg = arg.doit(**hints)

        _eval_determinant = getattr(arg, '_eval_determinant', None)
        if _eval_determinant is not None:
            result = _eval_determinant()
            if result is not None:
                return result

        return Determinant(arg)
```

**Comment by mrettl** [comment]
I don't think there is a need to catch `NotImplementedError`.  Except for `Trace.doit()`, no other Matrix Expression (Adjoint, DotProduct, Hadamard, Inverse, MatAdd, MatMul, MatPow, Transpose) catch it.

I found only one potential raise of a NotImplementedError in [PermutationMatrix._eval_determinant()](https://github.com/sympy/sympy/blob/bce780e23c0408e76c83d1c2866b469baa1e1e66/sympy/matrices/expressions/permutation.py#L95).

```python
class PermutationMatrix(MatrixExpr):
    ...
    def _eval_determinant(self):
        sign = self.args[0].signature()
        if sign == 1:
            return S.One
        elif sign == -1:
            return S.NegativeOne
        raise NotImplementedError
```

However, this raise statement is not reachable, due to the implementation of [`Permutation.signature()`](https://github.com/sympy/sympy/blob/bce780e23c0408e76c83d1c2866b469baa1e1e66/sympy/combinatorics/permutations.py#L2280)

```python
class Permutation(Atom):
    ...
    def signature(self):
        if self.is_even:
            return 1
        return -1
```
