### ISSUE TITLE
docstring of center_of_mass is not present in online documentation

### ISSUE THREAD

**Issue by moorepants** [sympy/sympy#25081]
sympy.physics.mechanics.functions.center_of_mass is not shown in the online documentation.

I don't think this is the only one missing from mechanics, so it would be work checking if all functions and classes are present.

The sphinx autodoc settings just need to be updated to cover everything in all the modules.

**Comment by varunseth5788** [comment]
Can I work on this issue.

**Comment by ykw1793** [comment]
Hi, I am a new contributor and would like to work on this issue.
