### ISSUE TITLE
Cannot import the stats module directly.

### ISSUE THREAD

**Issue by alex180500** [sympy/sympy#25121]
```py
import sympy as sp
print(sp.stats)
```
With output:
```bash
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'sympy' has no attribute 'stats'
```
What is going on? I cannot call the stats module if not by importing the single functions from the module.

**Comment by oscarbenjamin** [comment]
This is just how imports work in Python:
https://docs.python.org/3/reference/simple_stmts.html#import

If you do `import sympy.stats` first then the stats module will be available as `sp.stats` or you can do `import sympy.stats as stats`.
