### ISSUE TITLE
When n is small, `perfect_power` is slow

### ISSUE THREAD

**Issue by haru-44** [sympy/sympy#25138]
`sympy.ntheory.factor_.perfect_power` is a function to check if n is a perfect power. In general, checking whether a number is a perfect power is easier than doing a prime factorization.

Naive implementations, such as the following, are at a speed disadvantage when n is large.

```python
import math
from sympy.ntheory import factorint

def perfect_power_naive(n):
    f = factorint(n)
    g = math.gcd(*f.values())
    if g == 1:
        return False
    return math.prod(p**(e//g) for p, e in f.items()), g
```

However, when n is small, it outperforms `perfect_power`.

```python
%%time
for n in range(2, 100_000):
    perfect_power(n)
```

```
CPU times: total: 2.69 s
Wall time: 2.68 s
```

```python
%%time
for n in range(2, 100_000):
    perfect_power_naive(n)
```

```
CPU times: total: 1.06 s
Wall time: 1.06 s
```

I would like to improve it to be fast at any n, but I don't have a good idea. For now, I report it here.

**Comment by smichr** [comment]
If you haven't done so already, an improvement can be made by selecting a better algorithm when the input is a below a given threshold.

**Comment by asmeurer** [comment]
I think it's worth optimizing this. perfect_power is currently used in the automatic evaluation of numeric constants (see `Integer._eval_power`), so making it faster for common cases would improve SymPy overall.

**Comment by haru-44** [comment]
I see. However, we cannot use this code as is. It is circular because it calls `perfect_power` in `factorint`.

For the same reason, the code in numbers.py calls `perfect_power` more than once when it is not perfect power.
https://github.com/sympy/sympy/blob/67c72efedfbddc20589f463fe1a8c813640b6349/sympy/core/numbers.py#L2049-L2054
So, one idea would be to modify it as follows.

```python
dict = Integer(b_pos).factors(limit=2**15)
```

Detect perfect power regardless of the value of `limit'.

```python
>>> factorint(1009**10, limit=10)
{1009: 10}
>>> factorint((7*10007)**13, limit=5)
{70049: 13}
```

**Comment by haru-44** [comment]
It would be something like this. Now we have to decide on the threshold.

```python
def perfect_power_new(n, candidates=None, big=True, factor=True):
    THRESHOLD = 2**22
    if n <= THRESHOLD:
        factors = {}
        multi = 1
        g = t = bit_scan1(n)
        if t:
            if g == 1:
                return False
            n >>= t
            if n == 1:
                if not big:
                    g = min(factorint(g).keys())
                return math.prod(p**(e//g) for p, e in factors.items()), g
            factors[2] = t
        while is_square(n):
            n = isqrt(n)
            multi <<= 1
        for p in primerange(3, THRESHOLD**(1/3)):
            t = 0
            while n % p == 0:
                n //= p
                t += multi
            if t:
                g = gcd(g, t)
                if g == 1:
                    return False
                factors[p] = t
                if n == 1:
                    break
            if n < p**3:
                g = gcd(g, multi)
                if g == 1:
                    return False
                factors[n] = multi
                break
        if not big:
            g = min(factorint(g).keys())
        return math.prod(p**(e//g) for p, e in factors.items()), g
```
