### ISSUE TITLE
singular_value_decomposition fails after simplifying a matrix

### ISSUE THREAD

**Issue by custal** [sympy/sympy#25162]
If I create a matrix with a few symbols in then ask for the singular value decomposition then a result is returned without issue, however if I first simplify the matrix before the decomposition I get the error:

`Traceback (most recent call last):
  File "C:\Users\custal\Documents\software\sandbox\test\block_unitary.py", line 22, in <module>
    print(N.singular_value_decomposition())
  File "C:\Users\custal\AppData\Local\pypoetry\Cache\virtualenvs\test-ErjjmaXI-py3.10\lib\site-packages\sympy\matrices\matrices.py", line 2150, in singular_value_decomposition
    return _singular_value_decomposition(self)
  File "C:\Users\custal\AppData\Local\pypoetry\Cache\virtualenvs\test-ErjjmaXI-py3.10\lib\site-packages\sympy\matrices\decompositions.py", line 1319, in _singular_value_decomposition
    S[i, i] = sv
  File "C:\Users\custal\AppData\Local\pypoetry\Cache\virtualenvs\test-ErjjmaXI-py3.10\lib\site-packages\sympy\matrices\immutable.py", line 69, in __setitem__
    raise TypeError("Cannot set values of {}".format(self.__class__))
TypeError: Cannot set values of <class 'sympy.matrices.immutable.ImmutableDenseMatrix'>`

This is the code I run to generate the error. The first 2 print statements run without error.

```
import sympy as sp
from sympy.matrices import Matrix

theta = sp.Symbol("theta", real=True)

w = 0
x = sp.exp(sp.I*theta)
y = sp.exp(-sp.I*theta)
z = sp.exp(sp.I*theta)

s = sp.Symbol("s")

U = Matrix([[w, x], [y, z]])
I = Matrix([[1, 0], [0, 1]])

s = sp.sqrt(2/(3+sp.sqrt(5)))
M = s*U
N = sp.simplify(s*U)

print(M == N)
print(M.singular_value_decomposition())
print(N.singular_value_decomposition())
```

**Comment by oscarbenjamin** [comment]
The code should create a mutable matrix using `zeros` rather than `S.zeros`:
https://github.com/sympy/sympy/blob/4323bf2be3fc64294ac83333eb6a42f45d097595/sympy/matrices/decompositions.py#L1316-L1319

**Comment by DarkNisa** [comment]
Instead of working with `zeros` matrix which has been used for construction of diagonal matrix over singular values, I simply used `diag` class method and it solved the problem. So I created a pull request.

**Comment by DarkNisa** [comment]
Pull request is merged, so u may try current state of library,
check the code again and close the issue.

**Comment by oscarbenjamin** [comment]
This is fixed now.
