### ISSUE TITLE
The series expansion gives a wrong result.

### ISSUE THREAD

**Issue by ZhuangMaMS** [sympy/sympy#25180]
```
import sympy
x0= 1.1
x = sympy.symbols('x')
U = sympy.cos(x)-sympy.cos((0.4+x)/2)
U.series(x,x0,5)
```
the result is 
```
0.327334030606502 - 0.163757712045309*(0.909090909090909*x - 1)**2 + 0.178798224590481*(0.909090909090909*x - 1)**3 + 0.0248814990342418*(0.909090909090909*x - 1)**4 - 0.550387980049768*x + O((x - 11/10)**5, (x, 11/10))
```
It is different from the result using Mathematica,
```
Series[Cos[x] - Cos[(0.4 + x)/2], {x, 1.1, 4}]
```
and the result is 
$-0.278093-0.550388 (x-1.1)-0.135337 (x-1.1)^2+0.134334 (x-1.1)^3+0.0169944 (x-1.1)^4+O\left((x-1.1)^5\right)$.
Can you tell me the reason? Thanks.

**Comment by oscarbenjamin** [comment]
The sympy result is the same as the Mathematica result. It is just that the linear term is expanded:
```
In [54]: -0.27 - 0.55*(x - 1.1)
Out[54]: 0.335 - 0.55⋅x
```

**Comment by ZhuangMaMS** [comment]
The coefficient of the second order is `- 0.163757712045309` in sympy while `-0.135337` in Mathematica. And the coefficient of the third order is also different.

**Comment by oscarbenjamin** [comment]
```
In [55]: expand(0.163757712045309*(0.909090909090909*x - 1)**2)
Out[55]: 
                   2                                          
0.135336952103561⋅x  - 0.297741294627834⋅x + 0.163757712045309
```

**Comment by ZhuangMaMS** [comment]
Thanks! I understand what you mean. I need the coefficients of different orders about `(x-1.1)` not `(0.909090909090909*x - 1)`. Can you tell me how to operate in sympy ? Because 'x0' is a variable in my codes, the form of in `( )` is seemingly uncontrollable in sympy.
