### ISSUE TITLE
New Assumptions: handle relational assumptions as much as possible with existing sat solver

### ISSUE THREAD

**Issue by TiloRC** [sympy/sympy#25195]
As SymPy's new assumption system can't do much with relational assumptions, I'm adding new functionality so that it will be able to work with them. My first step is to do as much as I can with the existing SAT solver; there will be functionality that will probably require an SMT solver to achieve (e.g. ask(x > 10,  x > y & y > 10 )), so I will not touch this sort of thing yet. 

Here's some examples of functionality I wish to add:
- ask(Q.positive(x),   x > 10) # should return True instead of None which it currently returns. 
- ask(Q.zero(x),   Q.ne(x,0) ) # should return False instead of None

Here's something a bit more tricky but I still want to accomplish with this issue because the sat solver should be able to deal with it. 
- ask( Q.zero(x),   Q.eq(x, y) | Q.eq(x,z) & Q.positive(y) & Q.negative(z) ) # should return False

Edit: fixed typo

**Comment by TiloRC** [comment]
To deal with my first two examples and examples like them I propose we derive unary assumptions from relational assumptions. So if x>10 is an assumption, the current system just ignores that; instead we can add Q.positive(x) as an assumption. Of course, Q.positive(x) does not contain as much information, but that is the limitation of the current system. To avoid losing that information I believe we would need to use an SMT solver. 

Here's a function that does what I'm proposing. 
```
def _extract_unary_assumptions(binary_assump):
    """
    Takes a relational assumption (e.g. x>0, Q.eq(x,1)) and returns unary assumptions it implies.
    Returns True if it does not imply any unary assumptions.
    Parameters
    ==========
    binary_assump : Boolean
    
    Returns
    =======
    Boolean
    Examples
    ========
    
    >>> from sympy import Q
    >>> from sympy.abc import x, y
    >>> _extract_unary_assumptions(Q.gt(x,0))
    Q.positive(x)
    """
    arg1, arg2 = binary_assump.arguments
    if len(arg1.free_symbols) == 0:
        # reverse relation if the first argument contains no variables
        binary_assump = binary_assump.reversed
        arg1, arg2 = binary_assump.arguments

    if len(arg1.free_symbols) > 0 and len(arg2.free_symbols) == 0:
        operations = {
            Q.eq: [(arg2.is_positive, Q.positive(arg1)),
                   (arg2.is_negative, Q.negative(arg1)),
                   (arg2.is_zero, Q.zero(arg1))],
            Q.ne : [(arg2.is_zero, ~Q.zero(arg1) )],
            Q.gt: [(arg2.is_positive or arg2.is_zero, Q.positive(arg1))],
            Q.lt: [(arg2.is_negative or arg2.is_zero, Q.negative(arg1))],
            Q.ge: [(arg2.is_positive, Q.positive(arg1)),
                   (arg2.is_zero, Q.positive(arg1) | Q.zero(arg1))],
            Q.le: [(arg2.is_negative, Q.negative(arg1)),
                   (arg2.is_zero, Q.negative(arg1) | Q.zero(arg1))]
        }
        
        for operation, conditions in operations.items():
            if binary_assump.function == operation:
                for condition, assumption in conditions:
                    if condition:
                        return assumption
        return True
```

I think in the [ask](https://github.com/sympy/sympy/blob/master/sympy/assumptions/ask.py#L358) function right before the assumptions are converted to CNF would be a good place to call this function. We could loop through the assumptions and replace binary assumptions with the results of _extract_unary_assumptions.

**Comment by TiloRC** [comment]
Thinking more deeply about the last example
- ask( Q.zero(x), Q.eq(x, y) | Q.eq(x,z) & Q.positive(y) & Q.negative(z) ) # should return False
I've come to the conclusion that it would be incredibly impractical to implement this functionality using the existing sat solver. To do this example you would need to first replace all the y's with x and check if Q.zero(x) was true and then trt replacing all z's with x and checking if Q.zero(x). Now you can imagine examples with much longer or statements which would make you need to run the sat solver a lot of time. Furthermore, if there are multiple clauses like this, you could end up with an explosion of possibilities and you would need to run the sat solver for each one. 

Thus, this sort of example will have to wait for SMT solver functionality.

**Comment by sylee957** [comment]
The problem is we don't have any SMT solver. I think that getting a full implementation of that can be involved, or less performant, so using an existing API with hard dependency is good.
For example, Z3 is MIT licensed.

**Comment by TiloRC** [comment]
After meeting with my GSoC mentors and doing some more work, I don't think the stuff I mention in this thread is important.
