### ISSUE TITLE
minor error in MatrixCalculus.diff doc

### ISSUE THREAD

**Issue by 17cspence** [sympy/sympy#25202]
In [the documentation for matrix diff](https://docs.sympy.org/latest/modules/matrices/matrices.html#sympy.matrices.matrices.MatrixCalculus.diff) it says "Calculate the derivative of each element in the matrix. args will be passed to the **integrate** function." (Bold added.) Shouldn't that be the "diff" function or something like that? I don't see the integrate function in the source for diff.

**Comment by sylee957** [comment]
Maybe it was because of naive copy. I'd delete the statement because that's too generic.
