### ISSUE TITLE
Return value of A.LUsolve(b) can't be interacted with

### ISSUE THREAD

**Issue by hpaantee** [sympy/sympy#25208]
I have a system of equations Ax=b. A has a shape of 576x576. 
Here, A is a sparse matrix where some entries might contain a symbol. 
I can use A.LUsolve(b) just fine  (~15min) to solve for a symbolic solution of x.

**However**, I can't do anything with the result. Just trying to print() will never return. 
Printing A works.

**Comment by sylee957** [comment]
Why is the printing needed for working with the result?
You can get the entries of the matrix by `b[i, j]`.
For large expressions, printing can potentially be very slow, but this can be investigated only if you can share the code.

**Comment by hpaantee** [comment]
Maybe the printing example was a bit missleading. What I meant is that for the most part I cannot interact with it. 
Things not working (never returning):
- trying to lambdify (modules=['numpy', 'scipy', 'sympy'])
- validating the solution by multiplying with the original matrix A
- printing just the first element solution[0, 0]
- .subs
However, some of its member functions work, like .shape, .free_symbols
Here a minimal working example to reproduce my problem:

```
import sympy

from sympy.parsing.sympy_parser import parse_expr

with open('matrix_A.txt', 'r') as f:
    string = f.read()
A = parse_expr(string)
b = sympy.zeros(576, 1)
b[0,0] = 1
print('solve...')
res = A.LUsolve(b)
print('solving worked!')
```

[matrix_A.txt](https://github.com/sympy/sympy/files/11674694/matrix_A.txt)

**Comment by oscarbenjamin** [comment]
LUsolve can generate very large complicated expressions. Any operations with those expressions can be slow.

**Comment by hpaantee** [comment]
So I was able to significantly speed it up via using symengine. Solving it now takes less than a minute. But any operation on it still never finishes it. And trying to lambdify it returns a non-descriptive 
`"RuntimeError: -1.14183378644392e+50 + 8.20975478115991e+48*I"`
But that might be an error of symengine...

**Comment by oscarbenjamin** [comment]
With or without SymEngine it will be more accurate and more efficient to lambdify the matrices and use BLAS (i.e. `np.linalg.solve`) to solve the linear equations numerically.

**Comment by hpaantee** [comment]
I did not yet have the chance to accuracy, but symengine/symengine.py#442 solved my problem.
