### ISSUE TITLE
Incorrect result returned by `to_anf`

### ISSUE THREAD

**Issue by lweqx** [sympy/sympy#25218]
```py
from sympy import symbols, simplify
a, b = symbols("a b")
f = a ^ ~(a ^ b ^ ~b)

print(f.to_anf()) # prints `a`
print(simplify(f)) # prints `False`
```

Simplifying `f` (correctly) results in `false`. According to [its documentation](https://docs.sympy.org/latest/modules/logic.html#sympy.logic.boolalg.to_anf), `f.to_anf()` should also thus return `false`:
> ANF is a canonical normal form, which means that two equivalent formulas will convert to the same ANF.

**Comment by oscarbenjamin** [comment]
It seems that Xor does not define the `to_anf` method and inherits the implementation from BooleanFunction:
https://github.com/sympy/sympy/blob/781f3257a1521f99fe1a2709d8335337f9ff7981/sympy/logic/boolalg.py#L539-L550

That method filters out repeating arguments using a set. That makes sense for something like `And(x, x) -> And(x)` but not for `Xor(x, x)`:
```
In [3]: Xor(x)
Out[3]: x

In [4]: Xor(x, x)
Out[4]: False
```
The method should be changed to not use a set (the subclass constructor can filter args with a set if it makes sense for the given type):
```diff
diff --git a/sympy/logic/boolalg.py b/sympy/logic/boolalg.py
index 049a02de5d..751526f296 100644
--- a/sympy/logic/boolalg.py
+++ b/sympy/logic/boolalg.py
@@ -539,15 +539,15 @@ def _to_nnf(cls, *args, **kwargs):
     @classmethod
     def _to_anf(cls, *args, **kwargs):
         deep = kwargs.get('deep', True)
-        argset = set()
+        new_args = []
         for arg in args:
             if deep:
                 if not is_literal(arg) or isinstance(arg, Not):
                     arg = arg.to_anf(deep=deep)
-                argset.add(arg)
+                new_args.append(arg)
             else:
-                argset.add(arg)
-        return cls(*argset, remove_true=False)
+                new_args.append(arg)
+        return cls(*new_args, remove_true=False)
 
     # the diff method below is copied from Expr class
     def diff(self, *symbols, **assumptions):
```
Maybe BooleanFunction just should not define this method at all but at least with the change above it should not produce something incorrect.

**Comment by abhiphile** [comment]
@oscarbenjamin I think this issue can be closed after merging this PR .Kindly review the PR .

**Comment by abhiphile** [comment]
This Issue can be closed after merging this PR.
