### ISSUE TITLE
Ask returns False when it should return None when using relational assumptions

### ISSUE THREAD

**Issue by TiloRC** [sympy/sympy#25221]
These examples are correct:
```
>>> print(ask(Q.transcendental(x), Q.algebraic(x)))
False
>>> print(ask(Q.transcendental(x), Q.algebraic(x) | Q.positive(x)))
None
```
However, if we replace Q.positive(x) with x > 0  or Q.gt(x,0) we get False instead of None:
```
>>> print(ask(Q.transcendental(x), Q.algebraic(x) |  (x >0) )
False
```

**Comment by prady0t** [comment]
As clearly stated in the documentation, it's a work in progress.  https://github.com/sympy/sympy/blob/2d008c2e64a14f17883b06109279a23430992775/sympy/assumptions/ask.py#L434
https://github.com/sympy/sympy/blob/2d008c2e64a14f17883b06109279a23430992775/sympy/assumptions/ask.py#LL431C1-L440C1

**Comment by asmeurer** [comment]
It looks like the `_extract_all_facts` helper function is dropping predicates with more than one arg. https://github.com/sympy/sympy/blob/2d008c2e64a14f17883b06109279a23430992775/sympy/assumptions/ask.py#L345

**Comment by TiloRC** [comment]
If you have a nonsense assumption like Q.positive(x,y) where there is more than 1 argument, it behaves like this as well.
```
>>> ask(Q.transcendental(x), Q.algebraic(x) | Q.positive(x,y))
False
```
Is this something that should be fixed? This shouldn't be an issue if people are constructing queries with the right syntax. But maybe Q.positive(x,y) should throw an error?

**Comment by oscarbenjamin** [comment]
> But maybe Q.positive(x,y) should throw an error?

Yes, maybe it should.

**Comment by asmeurer** [comment]
> But maybe Q.positive(x,y) should throw an error?

This used to be an error but a recent refactor of the predicates made it not one. In SymPy 1.0:

```py
>>> Q.positive(x, y)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: __call__() takes 2 positional arguments but 3 were given
```

We should reintroduce this type check.

**Comment by TiloRC** [comment]
Fixed by https://github.com/sympy/sympy/pull/25246
