### ISSUE TITLE
ecm bug

### ISSUE THREAD

**Issue by frktrk** [sympy/sympy#25239]
Hi!
Running the factorization below ends in a wrong result. A 47 factor is missing

ecm(87567239118838619296100386576471206763, B1=200000, B2=2000000, max_curve=300, seed=1234)
Result:
{47: 1, 4969: 1, 21529: 1, 16055056483: 1, 23080289344401529: 1}
Expected result:
{47: 2, 4969: 1, 21529: 1, 16055056483: 1, 23080289344401529: 1}

Reproduced the same bug with 54180621257240427046019992014174494350633, similarly a 47 factor is missing.

The basic factorint deals with both correctly.

**Comment by aphi** [comment]
I don't think there's a bug. ecm returns the set of prime factors, not a dict of factors with quantities (which is what factorint does).

`{47, 4969, 21529, 16055056483, 23080289344401529}`

**Comment by oscarbenjamin** [comment]
Yes, I think this is expected behaviour.

**Comment by frktrk** [comment]
yo guys, yeah I made a mistake with that. it was supposed to be a list for sure. the error is in the details. there should have been two of those 47 factors
