### ISSUE TITLE
Invalid calculation of the limit of the mod function

### ISSUE THREAD

**Issue by ArianKG** [sympy/sympy#25230]
The limit of the function `mod(x, a)` as x approaches to `m * a` (where m is an integer) is undefined, since it matters if we approach it to the positive or the negative one. By approaching x to the positive one, the result should be 0; but when x approaches to the negative one, it should be `a`. However, SymPy outputs 0 to both of them. Interesting that when I used the floor-definition of the mod function (`mod(x, a) = x - a * (floor(x / a))`), SymPy could calculate both correctly.

Example of the issue and the result being incompatible with the expectation:
Code:
```print(sympy.limit(sympy.Mod(x, 3), x, 3, '-'))```
Result:
```0```
Expected:
 ```3```

**Comment by madt2709** [comment]
Is it so obvious that it should return `a` instead of `0`? 

By applying mod(x,a) you are implicitly restriction your solution space to $\mathbb{Z}_a$ in which case `0 == a`. 

Whilst `x - a * (floow(x / a))` is a function in the reals so `0` and `a` are not equivalent.

**Comment by madt2709** [comment]
From a maths pov, using the mod function over the reals doesn't make much sense since everything would be 0... (eg `mod(2,3) = 0` since `3*2/3 = 2`)

my personal preference would be to restrict the usage of `mod` to integers before changing how limits are calculated.

**Comment by asmeurer** [comment]
SymPy's Mod is defined for real numbers. It isn't stated clearly in the docs, but it does use the floor definition.

**Comment by anutosh491** [comment]
I just had a look at this . So we have a wrong result for `limit(Mod(x, 3), x, 3, '-')` when approaching from the left hand side but also while we approach from right `limit(Mod(x, 3), x, 3, '+')` the result although being correct is being returned by through `gruntz` which might not be preferable .

We should try resolving this through the leading term approach and as we have pretty concrete leading term and series methods for the floor function , we should be using the floor rewrite for the limit . I'll submit a PR for this soon !

**Comment by anutosh491** [comment]
Closed through #25279
