### ISSUE TITLE
py2-import CI check is failing

### ISSUE THREAD

**Issue by oscarbenjamin** [sympy/sympy#25274]
The py2-import CI check is failing.

See e.g. here:
https://github.com/sympy/sympy/actions/runs/5321129428/jobs/9636345318?pr=25267

The error message is:
```
  Warning: The support for python 2.7 will be removed on June 19. Related issue: https://github.com/actions/setup-python/issues/672
  Version 2.7 was not found in the local cache
  Error: The version '2.7' with architecture 'x64' was not found for Ubuntu 20.04.
  The list of all available versions can be found here: https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json
```
As you can see in https://github.com/actions/setup-python/issues/672 this fails because Python 2.7 has been removed from the standard github actions setup-python action:

SymPy does not support Python 2.x any more but there is a check that importing sympy under an old Python version gives an error message:
https://github.com/sympy/sympy/blob/68a011f75ec8a2c2edb2f3ee7de2349af0b0d567/sympy/__init__.py#L15-L18
The py2 import check is just to see that someone who attempts to import sympy under Python 2.x will see this error message:
https://github.com/sympy/sympy/blob/68a011f75ec8a2c2edb2f3ee7de2349af0b0d567/bin/test_py2_import.py#L17-L25
The reason this is tested for is because if someone added some syntax to the `__init__.py` that was not valid in older Python versions (e.g. f-strings) then someone importing under Python 2.7 would see a SyntaxError rather than the hopefully helpful error message.

We could just remove this check but I do think that it is helpful to show this message. Note that the issue is not purely about Python 2 because newer features are added in any Python versions so the same problem could apply to someone using e.g. Python 3.7. We could change the CI check to test for an older 3.x version rather than 2.7 though.

Adding 2.7 in for the test would probably mean building it from source or using a different runner image or something so it is just a bit of work to set up and then another thing to maintain.

For now I have made this CI check not required so a PR can be merged even if it fails.

**Comment by oscarbenjamin** [comment]
Does anyone have any views about just dropping this check?

We could run it with Python 3.5 as a quick fix.

I would rather not go down the route of creating a CI job with nontrivial setup.

**Comment by abhishek-kuma** [comment]
Still the test cases are failing eg : [https://github.com/sympy/sympy/actions/runs/5338452356/jobs/9676223966?pr=25267#step:3:9](url)

**Comment by sylee957** [comment]
What about pypy2.7?

**Comment by 1e9abhi1e10** [comment]
Should be removed?
https://github.com/sympy/sympy/blob/9d4517c6b1840aa2c2dfd1617aea32ccedc7041d/.github/workflows/runtests.yml#L354-L366

**Comment by oscarbenjamin** [comment]
> Should be removed?
> https://github.com/sympy/sympy/blob/9d4517c6b1840aa2c2dfd1617aea32ccedc7041d/.github/workflows/runtests.yml#L354-L366

Ideally we would keep the test but use a python version that is still available in CI
