### ISSUE TITLE
laplace_transform returns nan

### ISSUE THREAD

**Issue by proy87** [sympy/sympy#25293]
`laplace_transform((1/(t-1))*sin(4*pi*(t-1))*DiracDelta(t-1)*(Heaviside(t-1/4)-Heaviside(t-2)), t, s)` returns `(nan, -oo, True)`.

**Comment by oscarbenjamin** [comment]
CC @hanspi42

**Comment by hanspi42** [comment]
> What exactly is `DiracDelta(t-1)/(t-1)` supposed to be? That does not seem well defined.

It isn't, but '1/(t-1))*sin(4*pi*(t-1))*DiracDelta(t-1)' is '4*pi*sinc(4*pi*(t-1))*DiracDelta(t-1)', and that is well defined: it has an area of '4*pi'.

However, my implementation will try to do '(1/(t-1))*sin(4*pi*(t-1))).subs(t, 1)', and that does not work. The only thing that would work is 'limit(1/(t-1))*sin(4*pi*(t-1)), t, 1)'.

I guess I will have to write my own substitution routine that tries to substitute, and if NaN results, tries to solve it by limit.

**Comment by hanspi42** [comment]
The following works too:

```
x = (1/(t-1))*sin(4*pi*(t-1))*DiracDelta(t-1)*(Heaviside(t-1/4)-Heaviside(t-2))
y = x.rewrite(sinc).simplify()
laplace_transform(y, t, s)
```

It gives the correct result.
