### ISSUE TITLE
Limit calculation with base E error

### ISSUE THREAD

**Issue by SamUnimelb** [sympy/sympy#25298]
I am using sympy to analyse the marginal distribution of 2-D exponential distribution given that the distribution function is implemented as:

from sympy import *
'''x, y are 2-D random variables and ρ is the correlation variable. '''
x, y = symbols("x, y", real=True, nonnegative=True)
ρ = symbols("ρ", real=True)
def F(x, y, ρ=0): 
    '''Because probability will be 0 directly if either x or y less than 0, so no need for a piecewise discusstion actually. 
    But if implemented as a Piecewise object reports different error to this one.'''
    return 1 - E ** (-x) - E ** (-y) - E ** (-x - y - ρ * x * y)

Then I call this function F using:

limit(F(x, y, ρ), y, +oo)

Then in jupyter lab the whole implementation yields the following error log:

---------------------------------------------------------------------------
NotImplementedError                       Traceback (most recent call last)
Cell In[19], line 14
     11     return 1 - E ** (-x) - E ** (-y) - E ** (-x - y - ρ * x * y)
     13 # F(x, y, ρ)
---> 14 limit(F(x, y, ρ), y, +oo)

File C:\Dev_Tools\Anaconda3\lib\site-packages\sympy\series\limits.py:64, in limit(e, z, z0, dir)
     13 def limit(e, z, z0, dir="+"):
     14     """Computes the limit of ``e(z)`` at the point ``z0``.
     15 
     16     Parameters
   (...)
     61      limit_seq : returns the limit of a sequence.
     62     """
---> 64     return Limit(e, z, z0, dir).doit(deep=False)

File C:\Dev_Tools\Anaconda3\lib\site-packages\sympy\series\limits.py:362, in Limit.doit(self, **hints)
    358         raise ValueError("The limit does not exist since "
    359                 "left hand limit = %s and right hand limit = %s"
    360                 % (l, r))
    361 else:
--> 362     r = gruntz(e, z, z0, dir)
    363 if r is S.NaN or l is S.NaN:
    364     raise PoleError()

File C:\Dev_Tools\Anaconda3\lib\site-packages\sympy\series\gruntz.py:711, in gruntz(e, z, z0, dir)
    708         raise NotImplementedError("dir must be '+' or '-'")
    710 try:
--> 711     r = limitinf(e0, z)
    712 except ValueError:
    713     r = limitinf(e0, z, leadsimp=True)

File C:\Dev_Tools\Anaconda3\lib\site-packages\sympy\core\cache.py:70, in __cacheit.<locals>.func_wrapper.<locals>.wrapper(*args, **kwargs)
     67 @wraps(func)
     68 def wrapper(*args, **kwargs):
     69     try:
---> 70         retval = cfunc(*args, **kwargs)
     71     except TypeError as e:
     72         if not e.args or not e.args[0].startswith('unhashable type:'):

File C:\Dev_Tools\Anaconda3\lib\site-packages\sympy\series\gruntz.py:452, in limitinf(e, x, leadsimp)
    450 e = e.rewrite('tractable', deep=True, limitvar=x)
    451 e = powdenest(e)
--> 452 c0, e0 = mrv_leadterm(e, x)
    453 sig = sign(e0, x)
    454 if sig == 1:

File C:\Dev_Tools\Anaconda3\lib\site-packages\sympy\core\cache.py:70, in __cacheit.<locals>.func_wrapper.<locals>.wrapper(*args, **kwargs)
     67 @wraps(func)
     68 def wrapper(*args, **kwargs):
     69     try:
---> 70         retval = cfunc(*args, **kwargs)
     71     except TypeError as e:
     72         if not e.args or not e.args[0].startswith('unhashable type:'):

File C:\Dev_Tools\Anaconda3\lib\site-packages\sympy\series\gruntz.py:546, in mrv_leadterm(e, x)
    538 #
    539 # The positive dummy, w, is used here so log(w*2) etc. will expand;
    540 # a unique dummy is needed in this algorithm
   (...)
    543 # improved, or just find limits of Re and Im components separately.
    544 #
    545 w = Dummy("w", positive=True)
--> 546 f, logw = rewrite(exps, Omega, x, w)
    547 series = calculate_series(f, w, logx=logw)
    548 try:

File C:\Dev_Tools\Anaconda3\lib\site-packages\sympy\series\gruntz.py:631, in rewrite(e, Omega, x, wsym)
    629     sig = sign(g.exp, x)
    630     if sig != 1 and sig != -1:
--> 631         raise NotImplementedError('Result depends on the sign of %s' % sig)
    632 if sig == 1:
    633     wsym = 1/wsym  # if g goes to oo, substitute 1/w

NotImplementedError: Result depends on the sign of -sign(x*ρ + 1)

Whereas if I ignore the correlation variable ρ the whole thing runs correctly, whereas this is not true because if y goes to infinity under the given condition, nothing is depend on -sign(x*ρ + 1). So I just kindly raise this situation as an issue for people to check and many thanks.

**Comment by SamUnimelb** [comment]
resolved... ρ value here should be bigger than 0... my bad...

**Comment by oscarbenjamin** [comment]
> ρ value here should be bigger than 0

Yes, it does. Here is `f`:
```python
In [74]: f
Out[74]: 
     -x    -y    -x - y - ρ⋅x⋅y
1 - ℯ   - ℯ   - ℯ  
```
The first three terms are well defined for `y -> oo`. Factoring `exp(-x)` from the last term we are left with:
```python
In [75]: exp(factor(-y-rho*x*y))
Out[75]: 
 -y⋅(1 + ρ⋅x)
ℯ  
```
So we need to know whether `1 + ρ⋅x` is negative, positive or zero. Assuming `rho` and `x` to be nonnegative is sufficient for this to be positive. It is not a *necessary* condition though because we might still have `|ρ⋅x| < 1` even if `rho` or `x` is negative.

Ideally `limit` would return a `Piecewise` for these things:
```python
In [88]: Piecewise((1 - exp(-x), 1 + rho*x > 0), (1 - 2*exp(-x), Eq(1 + rho*x, 0)), (-oo, True))
Out[88]: 
⎧      -x               
⎪ 1 - ℯ     for ρ⋅x > -1
⎪                       
⎨       -x              
⎪1 - 2⋅ℯ    for ρ⋅x = -1
⎪                       
⎩   -∞       otherwise 
```
Thanks for reporting in any case.
