### ISSUE TITLE
sum gives unexpected results on Matrices

### ISSUE THREAD

**Issue by impossiblearchitect** [sympy/sympy#25297]
Evaluating `sum` on a list of `Matrix`es throws an exception:

```python
sum([sympy.Matrix([[1,2],[3,4]]),sympy.Matrix([[9,10],[11,12]])])

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Input In [46], in <cell line: 1>()
----> 1 sum([sympy.Matrix([[1,2],[3,4]]),sympy.Matrix([[9,10],[11,12]])])

File ~/anaconda3/envs/gpgpu/lib/python3.8/site-packages/sympy/core/decorators.py:106, in call_highest_priority.<locals>.priority_decorator.<locals>.binary_op_wrapper(self, other)
    104         if f is not None:
    105             return f(self)
--> 106 return func(self, other)

File ~/anaconda3/envs/gpgpu/lib/python3.8/site-packages/sympy/matrices/common.py:2949, in MatrixArithmetic.__radd__(self, other)
   2947 @call_highest_priority('__add__')
   2948 def __radd__(self, other):
-> 2949     return self + other

File ~/anaconda3/envs/gpgpu/lib/python3.8/site-packages/sympy/core/decorators.py:106, in call_highest_priority.<locals>.priority_decorator.<locals>.binary_op_wrapper(self, other)
    104         if f is not None:
    105             return f(self)
--> 106 return func(self, other)

File ~/anaconda3/envs/gpgpu/lib/python3.8/site-packages/sympy/matrices/common.py:2728, in MatrixArithmetic.__add__(self, other)
   2725 if getattr(other, 'is_MatrixLike', False):
   2726     return MatrixArithmetic._eval_add(self, other)
-> 2728 raise TypeError('cannot add %s and %s' % (type(self), type(other)))

TypeError: cannot add <class 'sympy.matrices.dense.MutableDenseMatrix'> and <class 'int'>
```

This can be worked around by using `sympy.MatAdd(...).doit()`, but I would argue that since `A + B` works when `A` and `B` are `Matrix`es, `sum` should also work. (I'm not entirely sure why `sum` of a single `Matrix` gives the sum of the flattened `Matrix` -- it feels like if anything it should be a row vector or something -- but certainly it's a bug that it doesn't work on lists of `Matrix`es.)

**Comment by oscarbenjamin** [comment]
Python's `sum` function is basically this:
```python
def sum(items, start=0):
    total = start
    for item in items:
        total += item
    return total
```
If you pass a single Matrix as the items iterable then it will loop over the elements of the matrix:
```python
In [3]: M = Matrix([[1, 2], [3, 4]])

In [4]: for element in M: print(element)
1
2
3
4

In [5]: sum(M)
Out[5]: 10
```
Personally I think that making `Matrix` iterable like this was a mistake but that's not something that can be changed now. If Matrix wasn't iterable then you would get an error instead.

When you call sum with a list of matrices you get:
```python
In [6]: sum([M, M])
...
TypeError: cannot add <class 'sympy.matrices.dense.MutableDenseMatrix'> and <class 'int'>
```
This is because it is trying to add `0` to a matrix:
```python
In [7]: 0 + M
...
TypeError: cannot add <class 'sympy.matrices.dense.MutableDenseMatrix'> and <class 'int'> 
```
I don't think that should be changed: adding a number and a matrix should be an error. By implication `sum(matrices)` is not something that can be made to work.

There are various workarounds:
```python
n [9]: matrices = [M, M, M]

In [10]: sum(matrices[1:], matrices[0])
Out[10]: 
⎡3  6 ⎤
⎢     ⎥
⎣9  12⎦

In [14]: from sympy.matrices.expressions.special import GenericZeroMatrix

In [15]: sum(matrices, GenericZeroMatrix())
Out[15]: 
⎡3  6 ⎤
⎢     ⎥
⎣9  12⎦

In [12]: Add(*matrices)
Out[12]: 
⎡3  6 ⎤
⎢     ⎥
⎣9  12⎦

In [18]: from functools import reduce

In [20]: reduce(lambda a, b: a + b, matrices)
Out[20]: 
⎡3  6 ⎤
⎢     ⎥
⎣9  12⎦
```

**Comment by sylee957** [comment]
> but I would argue that since A + B works when A and B are Matrixes, sum should also work.

Sum does not work with other non-mathematical arithmetic objects, like strings or lists. I'd try to stick with `reduce` for clarity.
`sum` has quite weird design, such as forcing defaults to `0`, and refuses strings by trivial cases. (https://stackoverflow.com/questions/3525359/python-sum-why-not-strings) 
I'd assume that python developers discourage `sum` to be reusable to custom objects, looking at such cases.
