### ISSUE TITLE
Trying to work with algebraic identities

### ISSUE THREAD

**Issue by Tond3** [sympy/sympy#25296]
hey guys,
I am working with algebraic identities using the native Python IDE. For example, when I try the boolean for 
(a+b)**2 == a**2 + 2*a*b + b**2 I get false even though this is true. I have done expand((a+b)**2) and I get the true result 
a**2 + 2*a*b + b**2. Any reason why this happening? 
![Screenshot 2023-06-27 at 3 11 33 pm](https://github.com/sympy/sympy/assets/45801115/8218ed6b-6ecc-4442-88c5-e77c4d642a37)

**Comment by oscarbenjamin** [comment]
This is explained in the tutorial:
https://docs.sympy.org/latest/tutorials/intro-tutorial/gotchas.html#equals-signs

**Comment by Tond3** [comment]
Okay, thanks. That was helpful
