### ISSUE TITLE
make randprime select prime in range with more equal probability

### ISSUE THREAD

**Issue by smichr** [sympy/sympy#25301]
In `randprime` there is this observation:

```
        Note that due to implementation difficulties,
        the prime numbers chosen are not uniformly random.
        For example, there are two primes in the range [112, 128),
        ``113`` and ``127``, but ``randprime(112, 128)`` returns ``127``
        with a probability of 15/17.
```

Should this be addressed in some way or should the approach be made more transparent in the docstring: a random number in the desired range is chosen, `n`; then the prime before `n` is returned if it is not lower than the lower bound, else the prime after n is returned if it is not larger than the upper bound. You can check the distribution of values returned for a given range with `multiset([randprime(12, 18) for i in range(1000)]) -> {17: 724, 13: 276}`. Perhaps randomly returning one of `b, n (if prime), a` where `b` is the prime before `n` and `a` the one after, would be better. I don't think -- especially for a very large range -- that computing all primes in the range then randomly selecting one is the way to go. But perhaps this could be used when the range is covered by the existing sieve.

**Comment by haru-44** [comment]
Even if `randprime` is not uniformly random, it is unlikely to be a practical problem, and I thought it would be sufficient to include a note so as not to mislead users.

For example, in the case of a random selection of 100-bit prime numbers, the difference between the current and proposed methods is negligibly small. I also think it would be better to let the user choose whether to use the `sieve` method or not. How about the following?

```python
def randprime(a, b, uniform=False):
    if a >= b:
        return
    a, b = map(int, (a, b))
    if uniform:
        sieve.extend(b)
        left_idx = bisect_left(sieve._list, a)
        right_idx = bisect_left(sieve._list, b)
        if left_idx == right_idx:
            return sieve._list[left_idx]
        r = randint(left_idx, right_idx - 1)
        return sieve._list[r]
    n = randint(a - 1, b)
    p = nextprime(n)
    if p >= b:
        p = prevprime(b)
    if p < a:
        raise ValueError("no primes exist in the specified range")
    return p
```

**Comment by smichr** [comment]
Let's see if anyone else has an opinion. I suspect that you are right, imagining that a user just wants a prime in a given range and doesn't care which one is obtained. If they did they could also do `choice(list(randrange(a, b+1))`.
