### ISSUE TITLE
How should `subs()` be handled for Transfer Functions

### ISSUE THREAD

**Issue by faze-geek** [sympy/sympy#25315]
Right now, `.subs()` does not work with `TransferFunction` and `TransferFunction` Matrix class.
I think it should be supported as it is common to evaluate an input transfer function at a particular frequency `jw`.

Some control packages support the direct substitution:
**MATLAB**
```
>> t = tf([1 3],[1 1 1 1])
>> value = evalfr(t, 2);
>> value
    0.3333
```
**Python-control**
```
>>> tf = control.TransferFunction([1,3], [1,1,1,1])
>>> substituted_tf = control.evalfr(tf, 2)               # Same name, a coincidence :)
>>> substituted_tf
(0.3333333333333333+0j)
```

Relevant Comment :
1. https://github.com/sympy/sympy/pull/19390#issuecomment-640556483

**Comment by moorepants** [comment]
`.subs()`, `.xreplace()`, `.evalf()` and similar standard SymPy functions should all work with `TransferFunction`.

**Comment by moorepants** [comment]
This shows current functionality:

```
In [1]: from sympy.physics.control import TransferFunction

In [2]: import sympy as sm

In [3]: a, b, c, s = sm.symbols('a, b, c, s')

In [4]: tf = TransferFunction(a*s, b*s**2 + c*s, s)

In [5]: tf
Out[5]: TransferFunction(a*s, b*s**2 + c*s, s)

In [6]: d, e, f, w = sm.symbols('d, e, f, omega')

In [7]: tf.subs({s: d})
Out[7]: TransferFunction(a*s, b*s**2 + c*s, s)

In [8]: tf.xreplace({s: d})
Out[8]: TransferFunction(a*d, b*d**2 + c*d, d)

In [9]: tf.evalf(subs={a: 1.2})
Out[9]: TransferFunction(1.2*s, b*s**2 + c*s, s)

In [11]: tf.xreplace({s: sm.I*w})
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[11], line 1
----> 1 tf.xreplace({s: sm.I*w})

File ~/miniconda/lib/python3.9/site-packages/sympy/core/basic.py:1230, in Basic.xreplace(self, rule)
   1168 def xreplace(self, rule):
   1169     """
   1170     Replace occurrences of objects within the expression.
   1171 
   (...)
   1228 
   1229     """
-> 1230     value, _ = self._xreplace(rule)
   1231     return value

File ~/miniconda/lib/python3.9/site-packages/sympy/core/basic.py:1252, in Basic._xreplace(self, rule)
   1250     args = tuple(args)
   1251     if changed:
-> 1252         return self.func(*args), True
   1253 return self, False

File ~/miniconda/lib/python3.9/site-packages/sympy/physics/control/lti.py:374, in TransferFunction.__new__(cls, num, den, var)
    371 num, den = _sympify(num), _sympify(den)
    373 if not isinstance(var, Symbol):
--> 374     raise TypeError("Variable input must be a Symbol.")
    376 if den == 0:
    377     raise ValueError("TransferFunction cannot have a zero denominator.")

TypeError: Variable input must be a Symbol.
```

`.subs()` did not seem to replace the values. .`xreplace()` worked. Trying to sub in `sm.I*w` isn't allowed because the transfer function variable must be a symbol.

So I do see the necessity of having a special function that evaluates at `sm.I*w`. What it should return needs some discussion.

**Comment by faze-geek** [comment]
To address the points mentioned in https://github.com/sympy/sympy/pull/25335, I suggested the following modifications:

1. Name of the function let's keep `evalfr` in full form as `eval_frequency` (or maybe even `evaluate_frequency`) so that there is no confusion for users. `evalfr` is the standard function in MALTAB and python-control so I went ahead with the name but it is clashing with Sympy.
2. We will return an expression for `TransferFunction` and a matrix for `TransferFunctionMatrix`.


This diff would do the job - 
```
-    def evalfr(self,other):
+    def eval_frequency(self,other):
         """
         Returns the system response at any point in the real or complex plane.

@@ -841,7 +841,7 @@ def eval_frequency(self,other):
         """
-        argnew = TransferFunction(arg_num, arg_den, self.var)
+        argnew = TransferFunction(arg_num, arg_den, self.var).to_expr()
```

Now -
```
>>> tf1 = TransferFunction(1, s**2 + 2*s + 1, s)
>>> omega = 0.1
>>> tf1.eval_frequency(I*omega)
1/(0.99 + 0.2*I)
>>> tf2 = TransferFunction(s**2, a*s + p, s)
>>> tf2.eval_frequency(2)
4/(2*a + p)
>>> tf2.eval_frequency(I*2)
-4/(2*I*a + p)
```

Kindly let me know if this makes sense, then I'll send in a pr.

**Comment by faze-geek** [comment]
Hi @Sc0rpi0n101 @moorepants, what are your views on the above comment as the reverting pr https://github.com/sympy/sympy/pull/25409 has been merged.

**Comment by moorepants** [comment]
I see the need for a method that evaluates the transfer function at a specific frequency, i.e. that you only substitute the transfer function variable with I*omega. And yes I agree that it should return regular sympy expressions. It should work with omega being any valid sympy type: Symbol, Float, Function, Expr, etc.

**Comment by moorepants** [comment]
The other methods: `subs()`, `xreplace()`, `evalf()` etc should do as expected substitutions on any variables or expressions present and return a new TransferFunction. Subbing the tranfer function variable with something other than a symbol should raise an error.

`eval_freq` or `eval_frequency` or `eval_at_frequency` all seem like reasonable names. If we say `eval_frequency` then the user should pass in only a sympyfiable that represents omega (`I` should be used internally).

**Comment by faze-geek** [comment]
> Subbing the tranfer function variable with something other than a symbol should raise an error.

As of now, `subs()`, is intentionally not working with any type
```
>>> tf = TransferFunction(s, 1 + s, s)
>>> tf.subs({s:2})
TransferFunction(s, s + 1, s)
>>> p = Symbol('p')
>>> tf.subs({s:p})
TransferFunction(s, s + 1, s)
```


> `eval_freq` or `eval_frequency` or `eval_at_frequency` all seem like reasonable names. If we say `eval_frequency` then the user should pass in only a sympyfiable that represents omega (`I` should be used internally).

Should user not be allowed to check system response of a point in real plane ?

```
>>> tf2 = TransferFunction(s**2, a*s + p, s)
>>> tf2.eval_frequency(2)
4/(2*a + p)
>>> tf2.eval_frequency(I*2)
-4/(2*I*a + p)
```

**Comment by moorepants** [comment]
> Should user not be allowed to check system response of a point in real plane ?

Sure, but then you can't use the word "frequency". Frequency implies it is only on the imaginary axis, no?

**Comment by moorepants** [comment]
> As of now, subs(), is intentionally not working with any type

Why is it "intentionally" not working?

**Comment by faze-geek** [comment]
> Why is it "intentionally" not working?

I should say "intentionally not allowed to work". Kindly go through this [comment](https://github.com/sympy/sympy/pull/19390#issuecomment-640556483) once.
