### ISSUE TITLE
Questions about errors in float calculations

### ISSUE THREAD

**Issue by haru-44** [sympy/sympy#25317]
In `sympy.ntheory.factor_.perfect_power` you will find the following code:

https://github.com/sympy/sympy/blob/42803477e04fa26e309b587fff5388e6e269f48b/sympy/ntheory/factor_.py#L557-L561

As noted in the comments, if $b$, where $b^e=n$, is clearly not going to be an integer, the calculation is terminated before calling `integer_nthroot`. However, the `b` computed here agrees with the $b$ we want to find exactly if we ignore the error.

```math
b^e = n \iff e \log{b} = \log{n} \iff b = 2^{\log{n} / e}
```

If that is the case, it is more meaningful to use the result of the calculation in the answer (we use `r` to match the existing variable name).

```python
logn = math.log2(n)
if logn/e < 40:
    r = int(2.0**(logn/e) + 0.5)
    exact = r**e == n
else:
    r, exact = integer_nthroot(n, e)
```

The question is what to do with the threshold. What is the smallest `logn/e` such that `int(2.0**(logn/e) + 0.5)**e != n`? Here, `n` should only consider perfect power.

Do you have any good ideas?

**Comment by hanspi42** [comment]
I am not sure I understand this.

In `int(2.0**(logn/e) + 0.5)**e != n`, take log2 on both sides: `log2(int(2.0**(logn/e) + 0.5)) != logn/e`

Substitute logn/e=x: `log2(int(2.0**x + 0.5)) != x`

Then `int(2.0**x + 0.5) != 2**x`

This just asks "is x an integer", or do I misunderstand?

**Comment by hanspi42** [comment]
OK, understood.

But as I see it, both $n$ and $e$ are integers, so could you check this in SymPy itself like so?:

```
n = 2**12
ni = Integer(n)
e = 1
ei = Integer(e)
r = ratsimp((log(ni)/log(2)/ei))
if r.denominator == 1:
    print("Success")
```

**Comment by oscarbenjamin** [comment]
> Why not use SymPy data types, then?

There is a circularity problem here. The SymPy expressions simplify by using routines like `perfect_power` under the hood so we can't have `perfect_power` use SymPy expressions.

**Comment by oscarbenjamin** [comment]
Is it a problem just to use `integer_nthroot`?

Would it make sense to move this check inside `integer_nthroot`?

**Comment by haru-44** [comment]
My explanation was insufficient.

My goal is to modify the `perfect_power` code to make it faster. Since it is faster to compute `int(2.0**(logn/e) + 0.5)` than to compute `integer_nthroot`, I want to use `int(...) `would like to use `int(...)` whenever possible. However, if `logn/e` is large, it cannot be calculated correctly, so I am considering logic to use `integer_nthroot` when `logn/e` is large, and use `int(...)` when `logn/e` is small. The question was what to do with that threshold.

**Comment by oscarbenjamin** [comment]
If this check is sufficient to predict the output of `integer_nthroot` then would it not make sense to use it in `integer_nthroot` function so that `integer_nthroot` is faster?

**Comment by haru-44** [comment]
Experiments. The code I had originally thought was too slow, so I modified it.

```python
import math
from sympy.ntheory import sieve
from sympy.core.power import integer_nthroot
sieve.extend(10_000)

def perfect_power1(n):
    """ Current Version """
    logn = math.log2(n)
    max_possible = int(logn) + 2
    candidates = sieve.primerange(2, max_possible)
    for e in candidates:
        if logn/e < 40:
            b = 2.0**(logn/e)
            if abs(int(b + 0.5) - b) > 0.01:
                continue
        r, exact = integer_nthroot(n, e)
        if exact:
            return int(r), e
    return False

def perfect_power2(n):
    """ Proposed Version """
    logn = math.log2(n)
    max_possible = int(logn) + 2
    candidates = sieve.primerange(2, max_possible)
    for e in candidates:
        if logn/e < 40:
            b = 2.0**(logn/e)
            r = int(b + 0.5)
            if abs(r - b) > 0.01:
                continue
            exact = r**e == n
        else:
            r, exact = integer_nthroot(n, e)
        if exact:
            return int(r), e
    return False
```

The result seems to be that the proposed version is slightly faster.

```python
%%timeit -r 20
for n in range(1, 10_000):
    perfect_power1(n)
```

```
176 ms ± 2.77 ms per loop (mean ± std. dev. of 20 runs, 10 loops each)
```

```python
%%timeit -r 20
for n in range(1, 10_000):
    perfect_power2(n)
```

```
170 ms ± 2.59 ms per loop (mean ± std. dev. of 20 runs, 10 loops each)
```

I checked `_integer_nthroot_python` and it seems to calculate `y**(1./n)` first and then `2.0**(logn/e)` if not possible. So I don't think `_integer_nthroot_python` can be used as an idea to speed up the process.

https://github.com/sympy/sympy/blob/fe50950a699dc329bb6f6c9792261714e0693445/sympy/core/power.py#L129-L132

However, I think we could change `math.log(y, 2)` to `math.log2(y)`.

**Comment by hanspi42** [comment]
Hmm, I wonder why it is only a bit faster. I tested your code (I like it, by the way), and it occurred to me that `integer_nthroot` cannot possibly trigger for any $n<2^{80}$.

So you compare a function where `integer_nthroot` always executes for every candidate to one where it never does.

By the way, I also checked the results, up to $n=10^{7}$ it found all perfect powers.

**Comment by hanspi42** [comment]
I may have a faster one:

```python
def perfect_power3(n):
    """ Proposed Version """
    exact = False
    logn = math.log2(n)
    max_possible = int(logn) + 2
    candidates = sieve.primerange(2, max_possible)
    if logn < 80:
        for e in candidates:
            b = 2.0**(logn/e)
            r = int(b + 0.5)
            if abs(r - b) > 0.01:
                continue
            exact = r**e == n
    else:
        for e in candidates:
            r, exact = integer_nthroot(n, e)
    if exact:
        return int(r), e
    return False
```

Result:

```python
%%timeit -r 20
for n in range(1, 10000):
    perfect_power3(n)
    
93.5 ms ± 3.5 ms per loop (mean ± std. dev. of 20 runs, 10 loops each)

%%timeit -r 20
for n in range(1, 10000):
    perfect_power2(n)
    
99.7 ms ± 4.41 ms per loop (mean ± std. dev. of 20 runs, 10 loops each)

%%timeit -r 20
for n in range(1, 10000):
    perfect_power1(n)
    
114 ms ± 10.3 ms per loop (mean ± std. dev. of 20 runs, 10 loops each)
```

**Comment by haru-44** [comment]
Does `perfect_power3` work as expected? I think I have to break out of the `candidates` loop when `exact == True`.

```python
def perfect_power3_fix(n):
    exact = False
    logn = math.log2(n)
    max_possible = int(logn) + 2
    candidates = sieve.primerange(2, max_possible)
    if logn < 80:
        for e in candidates:
            b = 2.0**(logn/e)
            r = int(b + 0.5)
            if abs(r - b) > 0.01:
                continue
            if r**e == n:
                return r, e
    else:
        for e in candidates:
            r, exact = integer_nthroot(n, e)
            if exact:
                return int(r), e
    return False
```

Since `e` is always greater than or equal to 2, if `logn < 80`, then `logn/e < 40` is satisfied. So `perfect_power2` and `perfect_power3_fix` are equivalent.

As you have tried, it is fast when `logn < 80`. On the other hand, it can be `logn >= 80` but `logn/e < 40`, in which case it is not efficient.

```python
%%timeit -r 20
for n in range(2**100, 2**100 + 10_000):
    perfect_power2(n)

423 ms ± 14.1 ms per loop (mean ± std. dev. of 20 runs, 1 loop each)

%%timeit -r 20
for n in range(2**100, 2**100 + 10_000):
    perfect_power3_fix(n)

1.02 s ± 24.2 ms per loop (mean ± std. dev. of 20 runs, 1 loop each)
```

To make it work both ways, the following proposal is possible, but it is a trade-off for simplicity.

```python
def perfect_power4(n):
    exact = False
    logn = math.log2(n)
    max_possible = int(logn) + 2
    candidates = sieve.primerange(2, max_possible)
    if logn < 80:
        for e in candidates:
            b = 2.0**(logn/e)
            r = int(b + 0.5)
            if abs(r - b) > 0.01:
                continue
            if r**e == n:
                return r, e
    else:
        for e in candidates:
            if logn/e < 40:
                b = 2.0**(logn/e)
                r = int(b + 0.5)
                if abs(r - b) > 0.01:
                    continue
                exact = r**e == n
            else:
                r, exact = integer_nthroot(n, e)
            if exact:
                return int(r), e
    return False
```

**Comment by smichr** [comment]
On page 387 of http://cr.yp.to/lineartime/powers2-20060914-ams.pdf we find:
```
For most values of n, computing a floating point
number within 2**-32 of sqrt(n) reveals immediately that n is not a square, because
the floating-point number is not within 2**-32 of an integer.
Similarly, for almost all values of n, computing reasonably precise floating point
approximations to root(n, 2), root(n,3), . . . reveals immediately that k = 1. Here
one can define “reasonably precise” as, e.g., “within 2**-32/b.” 
```
So I wonder if the infeasibility check should use a more restrictive value than 0.01 to know whether the b is worth testing, e.g. `abs(r - b)*(r<<32) > 1` or something like that -- I'm not sure if `int(b)` or `r` should be the value shifted.
