### ISSUE TITLE
TorqueActuator.at_pin_joint has counter intuitive directions

### ISSUE THREAD

**Issue by TJStienstra** [sympy/sympy#25319]
The current implementation of the experimental `at_pin_joint` class method seems counter intuitive to me, missed it when approving it earlier. As the names of a torque actuator imply, we have a target and a reaction body/frame. The target is to which the torque is applied positively and an opposite torque is applied on the reaction frame. In case of a pin joint, we have a parent and a child, where the child is orient with respect to the parent.

Now let's go through an example on what we would expect. Suppose we add a torque actuator to a pin joint. The most sensible is to think that the parent applies a torque to the child. This means that the child is the target. Assuming that this torque of our actuator is positive, then we should get a positive deflection (generalized coordinate of our pin joint gets higher).

If we now actually look at the implementation side of things, we will see that it is exactly opposite. The target is currently the parent and the child is the reaction body. This also mean that a positive torque results in a negative acceleration.

As this feature is still experimental I suppose to swap the parent and child argument in the `TorqueActuator.at_pin_joint` definition, while also adding some documentation on what the definition is.

**Comment by TJStienstra** [comment]
@brocksam FYI

**Comment by kaustubh-765** [comment]
![image](https://github.com/sympy/sympy/assets/90597818/1e5e0f1c-b11d-4d77-a1a4-d675adcfcb11)
![image](https://github.com/sympy/sympy/assets/90597818/b939c1ca-291b-46b8-9239-740f8a6c1ee5)

I guess the point here mentioned is that we have to swap the target frame and reference frame and provide target frame with the None option too? 

For making the parent to reference and child as the target. 

I am confused for the part, it's just the comments that need amendments or in the actual code?
Would love your help here, and also it's my first time contributing so would request for a little guidance. 

Thank you

**Comment by TJStienstra** [comment]
Good to see, that you'd like to contribute.

> I guess the point here mentioned is that we have to swap the target frame and reference frame and provide target frame with the None option too?

They have to be swapped, but not in the `__init__`. They should be swapped in the class method [`at_pin_joint`](https://github.com/sympy/sympy/blob/76de4896380d27e3528b7aaba0dbffc89315b463/sympy/physics/mechanics/_actuator.py#L663), [here](https://github.com/sympy/sympy/blob/76de4896380d27e3528b7aaba0dbffc89315b463/sympy/physics/mechanics/_actuator.py#L729C1-L734C10):
```py
        return cls(
            torque,
            pin_joint.joint_axis,
            pin_joint.parent_interframe,
            pin_joint.child_interframe,
        )
```
Solving this issue involves three steps:
- [ ] Swap `pin_joint.parent_interframe` and `pin_joint.child_interframe` in the call
- [ ] Fix the broken tests. Note that tests should normally not break, but as this is an experimental feature, we can still make such changes.
- [ ] Update the documentation to clarify that a positive torque will cause an increase of the joint coordinate of the pin joint.

Hope this clarifies it a bit. If there are any other questions let me know?

**Comment by kaustubh-765** [comment]
![image](https://github.com/sympy/sympy/assets/90597818/5377e4bc-0acc-4e42-b722-21af7597ac4a)
I have swapped the variables

![image](https://github.com/sympy/sympy/assets/90597818/b7acfdc6-b3e9-4679-9ae5-f54216271768)
Updating the variables in Documentation, where now the target frame is child and reference frame is parent.

![image](https://github.com/sympy/sympy/assets/90597818/35b573e1-c670-455d-bbc7-cb5d52080276)
Have updated the test case to handle the test case of target frame and reference frame. 

As after the swap the target frame will be the child's frame and the reference frame will be the parent's frame. 

Would love your review, and if I need to correct anything.

Thank you

**Comment by kaustubh-765** [comment]
Sure
