### ISSUE TITLE
Derivation error

### ISSUE THREAD

**Issue by Enming-Zhou** [sympy/sympy#25320]
the diff(?, x) syntax will output an error result (e.g. sin(x+1))
The output is  cos(x+1). The correct output should be x*cos(x+1).

Is it because complex ‘x’ functions are not supported?

**Comment by oscarbenjamin** [comment]
I don't understand the question. Can you show example code?

**Comment by Enming-Zhou** [comment]
> I don't understand the question. Can you show example code?

![image](https://github.com/sympy/sympy/assets/33157807/a8bbf228-948b-4354-97cb-7f0fda1fc285)

**Comment by Enming-Zhou** [comment]
> I don't understand the question. Can you show example code?

sorry my bad. I didn't realize the coefficient is 1

**Comment by oscarbenjamin** [comment]
The output seems correct to me.
