### ISSUE TITLE
Create a Pieuseux series from a string

### ISSUE THREAD

**Issue by RagonEbker** [sympy/sympy#25339]
In the documentation about Series Manipulation a method is given to extract an expression from a power series:
`series.as_expr()`
but there is no method given to convert an expression into a power series.

My specific case:
```
R, x = ring('x', RR)
p = 1+x
s = "1+x"
a = parsing.parse_expr(s)
```

How can I convert `a` into the same object as `p`?

**Comment by smichr** [comment]
You have to tell the parser what you want to use for 'x': `parse_expr(s,local_dict={'x':x}) == p -> True`

**Comment by RagonEbker** [comment]
Thank you for your help!
