### ISSUE TITLE
Differentiating one function with respect to another function implementation!

### ISSUE THREAD

**Issue by MBSA-INFINITY** [sympy/sympy#25355]
- When we call `diff(exp(x),x)` function, we successfully get `exp(x)` as the result, but when we try to call `diff(exp(x),2*x)` and `diff(exp(x),exp(x))`, it throws ` ValueError(filldedent(''' ValueError: Can't calculate derivative wrt 2*x.` and ` ValueError(filldedent(''' ValueError: Can't calculate derivative wrt exp(x).` respectively.
- In calculus `diff(exp(x),2*x)` = `diff(exp(x),x) /diff(2*x,x)` or In general  `diff(f1(x),f2(x))` = `diff(f1(x),x) /diff(f2(x),x)`.
- **Problem Statement** - Modification of `diff()` function, in accordance with the general calculus logic stated above
- *I would be more than happy to take up on this issue and contribute to the sympy community!*
![Screenshot 2023-07-11 200652](https://github.com/sympy/sympy/assets/85332648/afe89d25-bb17-4a98-a7c9-0dddf5de8ad0)

**Comment by smichr** [comment]
Something like this?
```python
def diff(f, x):
    if not x._diff_wrt:
        g = x
        x = f.free_symbols and g.free_symbols
        assert len(x) == 1
        x = x.pop()
        return f.diff(x)/g.diff(x)
    return f.diff(x)
```

**Comment by MBSA-INFINITY** [comment]
Yes it should be something like this! But I think `_diff_wrt` param has to be checked with all the `*symbols` in the actual `diff` function in the codebase right?

**Comment by oscarbenjamin** [comment]
I'm not sure we should add this because I don't think that it is well defined in general.

What should `f(x, y).diff(g(x, y))` give? What about `(a*x).diff(x + y)` how would we know which symbols should be considered "constants" and which are supposed to be the "variables".

It is already very easy to use `f.diff(x) / g.diff(x)` is that is what is wanted.

**Comment by MBSA-INFINITY** [comment]
> I'm not sure we should add this because I don't think that it is well defined in general.
> 
> What should `f(x, y).diff(g(x, y))` give? What about `(a*x).diff(x + y)` how would we know which symbols should be considered "constants" and which are supposed to be the "variables".
> 
> It is already very easy to use `f.diff(x) / g.diff(x)` is that is what is wanted.

Yup, when you come to think of it, what you are saying is right and it make sense, but shouldn't we automatically do it inside the `diff` function itself!

**Comment by oscarbenjamin** [comment]
How can we do it automatically if we don't know which symbol to use?

**Comment by MBSA-INFINITY** [comment]
> How can we do it automatically if we don't know which symbol to use?

Frankly speaking, it has to be thought! 😅 But do you agree that, it should be automatically be done inside the function itself ?

**Comment by oscarbenjamin** [comment]
> But do you agree that, it should be automatically be done inside the function itself ?

No, I don't.

There is no way to know which symbol should be used so the operation is not well defined. It might seem straight-forward in simple cases but if it is not well defined in general then it will just lead to bugs and confusion.

**Comment by smichr** [comment]
> There is no way to know which symbol should be used

That is why there is an assertion of 1 free symbol is made in the function I proposed. In an actual version for SymPy the appropriate error would be raised.

**Comment by smichr** [comment]
But I am more in favor of having something that works well (the current diff) and allows others two write their own functions to do something extra so the burden is not on SymPy to maintain all the varieties of use cases. SymPy has the symbolic batteries; you use them to power your application(s).

**Comment by oscarbenjamin** [comment]
> That is why there is an assertion of 1 free symbol is made in the function I proposed.

You have to view this from a setting where more possible inputs could be given: would it be consistent with other cases?
```python
In [18]: f, g = symbols('f, g', cls=Function)

In [19]: x, y = symbols('x, y')

In [20]: f(x, y).diff(g(x, y))
Out[20]: 0

In [21]: f(x).diff(g(x))
Out[21]: 0

In [22]: sin(x).diff(cos(x))
ValueError
```
If we change `Out[22]` or `Out[21]` then what would happen to `Out[20]`? Would these all be consistent in a meaningful way?

Currently these are relatively well defined but I think that the suggestion here would make the operation strange and would almost certainly lead to weird edge cases that do not do what anyone expected. It would make it confusing to even know whether the differentiation variable should be treated as the variable or some function of the variable. We don't want to have that kind of ambiguity on such a basic point in an important function like `diff`.

**Comment by MBSA-INFINITY** [comment]
> > That is why there is an assertion of 1 free symbol is made in the function I proposed.
> 
> You have to view this from a setting where more possible inputs could be given: would it be consistent with other cases?
> 
> ```python
> In [18]: f, g = symbols('f, g', cls=Function)
> 
> In [19]: x, y = symbols('x, y')
> 
> In [20]: f(x, y).diff(g(x, y))
> Out[20]: 0
> 
> In [21]: f(x).diff(g(x))
> Out[21]: 0
> 
> In [22]: sin(x).diff(cos(x))
> ValueError
> ```
> 
> If we change `Out[22]` or `Out[21]` then what would happen to `Out[20]`? Would these all be consistent in a meaningful way?
> 
> Currently these are relatively well defined but I think that the suggestion here would make the operation strange and would almost certainly lead to weird edge cases that do not do what anyone expected. It would make it confusing to even know whether the differentiation variable should be treated as the variable or some function of the variable. We don't want to have that kind of ambiguity on such a basic point in an important function like `diff`.

Yup, that make sense! When it comes to resolving edge cases, it might be become very confusing! Thank you so much for you inputs @smichr  and @oscarbenjamin .
