### ISSUE TITLE
Eq function makes mistakes even in simple equality judgments

### ISSUE THREAD

**Issue by jropen** [sympy/sympy#25359]
'sympy.Eq(sympy.Mul(200, 1.1), sympy.Float(220.))' return False
'sympy.Eq(sympy.Mul(200, 1.1), sympy.Mul(20, 11))' return False
'sympy.Eq(sympy.Mul(200, 1.1), sympy.Mul(2000, 0.11))' return False
however，if change the number, it can get correct result:
'sympy.Eq(sympy.Mul(200, 1.2), sympy.Float(240.))' return True
'sympy.Eq(sympy.Mul(200, 1.1), sympy.Mul(200, 1.1))' return True

Can someone tell me why this happens? Thanks

**Comment by oscarbenjamin** [comment]
This is because you use floats so the numbers are not necessarily exactly equal depending on rounding error. You should usually avoid testing for equality of floats.

Use rational numbers instead:
```
In [87]: Eq(200*Rational('1.1'), 220)
Out[87]: True
```
