### ISSUE TITLE
[GSoC] Add features to Lark LaTeX Parser

### ISSUE THREAD

**Issue by wermos** [sympy/sympy#25364]
# Motivation

This issue is to keep track of the features that the current Lark LaTeX parser lacks.

Some features are things we want, but are difficult to implement, so those have been relegated for later. The current priority is to have a Lark LaTeX parser in SymPy, so that we can have some feedback from users and improve on it.

Some of the features that the ANTLR parser currently supports, we might _not_ want to support, so this issue is also for discussing those.

# Expressions We Plan to Support

## ~Limits~

~Limit expressions are not handled in the parser as of now. The reason for that is because handling limit expressions requires us to handle things like `3^{-}` and `3^{+}`, which are well-formed expressions in this context, but ill-formed otherwise.~

<details><summary>Failing Test Cases</summary>
<p>

- ~`expression = \lim_{x \to 3} a`~
- ~`expression = \lim_{x \rightarrow 3} a`~
- ~`expression = \lim_{x \Rightarrow 3} a`~
- ~`expression = \lim_{x \longrightarrow 3} a`~
- ~`expression = \lim_{x \Longrightarrow 3} a`~
- ~`expression = \lim_{x \to 3^{+}} a`~
- ~`expression = \lim_{x \to 3^{-}} a`~
- ~`expression = \lim_{x \to 3^+} a`~
- ~`expression = \lim_{x \to 3^-} a`~

</p>
</details>

### ~Ideas~

~To handle limit expressions, we can create a separate node called `limit_superscript` which allows for things like `<expression>^PLUS` and `<expression>^MINUS`.~

UPDATE: Support for limit expressions has been added.

## Derivatives

Derivative expressions are also not handled at all in the parser as of now. The reason for that is because we have to handle the case where there's `d<something>` and `d<same thing>` in the numerator and denominator case separately from how we would handle a fraction normally.

However, this is an important feature to support so we plan to support it.
<details><summary>Failing Test Cases</summary>
<p>

- `expression = \frac{d}{dx} [ \tan x ]`
- `expression = \frac{d f(x)}{dx}`
- `expression = \frac{d\theta(x)}{dx}`

</p>
</details>

### Ideas <a href="#ideas" id="ideas"/>

We can probably do the checking for whether we have a possible derivative expression in the transformer. The advantage is that the grammar doesn't need to be complicated further.

## Integrals 

The current work in the parser correctly handles 17/23 of the integral-related test cases in [`test_latex.py`](https://github.com/sympy/sympy/blob/a9320ec9328d722417b5bcd3b5cd885ae2960eb1/sympy/parsing/tests/test_latex.py).

Here is the full set of expressions on which the parser is currently failing:
<details><summary>Failing Test Cases</summary>
<p>

1. `expression = \int x d\theta`
1. `expression = \int_{f(a)}^{f(b)} f(z) dz`
1. `expression = \int (x+a)`
1. `expression = \int \frac{dz}{z}`
1. `expression = \int \frac{3 dz}{z}`
1. `expression = \int \frac{3 \cdot d\theta}{\theta}`

</p>
</details>

### Expressions of Interest

Out of the failing test cases, there are a couple of expressions of interest:

*  `expression = \int (x+a)`

In the current ANTLR-based parser, this is what happens:
```python
>>> from sympy.parsing.latex import parse_latex
>>> parse_latex(r"\int (x + a)")
Integral(a + x, x)
```
That is, if the expression does not have the trailing `d` operator, then it is assumed to be an integral with respect to `x`. This is, as @Upabjojr mentioned in a team meeting, a strange assumption. I concur, so I think we should remove that test and remove this behavior.

After some sleuthing, I found that this test was added in #13706, meaning it was ported from the `latex2sympy` code. The tests were simply ported in the `latex2sympy` repository, where this specific test was added in [6226801e](https://github.com/augustt198/latex2sympy/commit/6226801e5ab19d8a5cbc931984c5d94cf0ce10a5) along with all the other tests.

The other expression of interest is
* `expression = \int \frac{dz}{z}`

This is a valid expression, but the difficulty comes in handling the fact that the `d` operator is part of the fraction.

Since the `d` is part of the fraction, whereas semantically it is part of the integral operator, we cannot use the trick mentioned in the [Derivatives section](https://github.com/sympy/sympy/issues/25364#ideas), because the transformer does not have any knowledge about the surrounding nodes in the tree. This means that while we are transforming the fraction node, we do not know whether the fraction was inside an integral expression or not.

## ~Expressions Involving Greek Symbols~

~The parser currently does not recognize Greek symbols. This is a very easy feature to add and will done soon.~

UPDATE: This was done in commit 0837b37f8b6203d65c2d6d6242d0015ead80d364 on my fork.

## Bra and Ket Notation

The ANTLR parser also has support for Bra and Ket notation.

The two tests for this can be found [here](https://github.com/sympy/sympy/blob/a9320ec9328d722417b5bcd3b5cd885ae2960eb1/sympy/parsing/tests/test_latex.py#L128-L129):
* `expression = \langle x |`
* `expression = | x \rangle`

However, since I am not a Physics student, and don't have much knowledge about Physics, I am not sure how to add it into the parser. The thing I am not sure about is whether the thing inside the Bra or Ket can be a complicated expression. I _did_ have to take an introductory QM class (for college), so I have never seen something like `| \cos x \rangle`.

It is still something I need to know for sure, because the grammar would be written accordingly. If we can only have things like `| x \rangle` and `\langle p |`, then the grammar definition would be different from what I would write if `| \cos x \rangle` or `\langle p^2 |` is allowed.

# Questionable Expressions

There are a few expressions in the test, that I have briefly discussed before. I will mention them here, so that we can get the community's views on whether support for these expressions should be retained or not.

* `expression = [x]`
* `expression = [a + b]`

In both cases, the ANTLR parser simply acts like the square brackets weren't even there:
```python
>>> from sympy.parsing.latex import parse_latex
>>> parse_latex("[a + b]")
a + b
>>> parse_latex("[x]")
x
```
This is strange behavior, especially because in some contexts, [square brackets are used for the floor function](https://en.wikipedia.org/wiki/Floor_and_ceiling_functions#Notation).

Apart from this, the following expressions are also present as test cases:

* `expression = \left[x + y\right] z`
* `expression = \left\{x + y\right\} z`

In both cases, the square brackets and the curly braces are parsed the way parentheses would be. That is, the expressions are converted into `(x + y) * z`.

While I was taught in school that `[]` and `{}` are sometimes interchangeably used with parentheses in deeply nested expressions, I have never seen this in real life. @Upabjojr mentioned something similar during our team meeting when I brought this up.

Moreover, LaTeX's support for resizeable parentheses (using `\left` and `\right`, or manually resizing using `\big`, `\bigg`, et. al.) reduce the need for using `[]` and `{}` as parentheses.

Finally, there are quite a few tests where `'` is used in function or variable names:

* `expression = a'b+ab'`
* `expression = y''_1`
* `expression = y_1''`
* `expression = f'_1(x)`
* `expression = f_{1}''(x+y)`

I'm not sure how realistic this is. `a'` is reasonably parsed, I think, because often we suffix already-used variable names with apostrophes to make new variables. However, for the functions, I don't think this is correct. In Physics, the apostrophe is often used to mean the derivative of a function.

**Edit:** The motivation for parsing function names like `f'(x)` as `Function("f'")(x)` can be found in #23515.

**Comment by idanpa** [comment]
FYI - few things I needed and are currently missing on the antlr parser:
* `\intop` should be an alias to `\int`
* `\nicefrac` should be an alias to `\frac`
* support for matrices/arrays `\begin{matrix}`, `\begin{smallmatrix}`, `\begin{array}`

**Comment by wermos** [comment]
Thanks for the feature suggestions.

> `\intop` should be an alias to `\int`

This is an easy feature to add and I've added it to the Lark LaTeX parser.

> `\nicefrac` should be an alias to `\frac`

Same thing here. I've added this too.

> support for matrices/arrays `\begin{matrix}`, `\begin{smallmatrix}`, `\begin{array}`

This is a complicated feature to add. I've made a note of the feature request and will work on it after the initial PR (i.e., #25324) is merged.

**Comment by wermos** [comment]
@idanpa, out of curiosity, what other matrix-related features do you need, other than support for matrices?

I imagine we'd also want to add support for things like adding and subtracting matrices, as well as things like `number matrix` and `variable matrix` implicit scalar multiplication.

We'd probably also add matrix matrix multiplication support.

Would we want to support expressions like `matrix / number` or `matrix / variable`? 🤔

**Comment by idanpa** [comment]
Hi @wermos thank you for your interest.

My general flow is to copy stuff I have in my latex files and play with it in sympy.
(and after playing with it I may use `sympy.printing.latex.latex` to print it back to latex)

Yes, I would need this to support matrices with symbolic expressions within the entries (not just numbers).
Matrix operations are needed too, but even having the basic ability - `A=parse_latex(r"\begin{matrix}...")` would help and would allow user to do the operations on the sympy object itself.

Matrix exponentiation would be nice to have too, but I think it is less common.

**Comment by wermos** [comment]
I thought I'd mention that support for matrix expressions is already in the GitHub issue tracker in a separate issue: #14007

**Comment by wermos** [comment]
I'm going to close this issue and make a new issue with the features that are yet to be added.
