### ISSUE TITLE
Resultant of Polynomials  Returns Wrong Output

### ISSUE THREAD

**Issue by dianetc** [sympy/sympy#25406]
I'm working on testing properties of the resultant in the polys library.  Specifically, the following:

Given two polynomial $`f,g`$ of degree $`d,e`$ respectively, we have:

$`g.resultant(f) = (-1)^{de}f.resultant(g)`$

This property fails in testing because it returns  $`g.resultant(f) = f.resultant(g) = 1`$,  for $`f = x^3, g = x+1`$. This is incorrect because it should be  $`f.resultant(g) = -1`$.  

```
from sympy.abc import x
from sympy.polys.polytools import Poly

f = Poly([1, 0, 0, 0], x, domain='ZZ')
g = Poly([1,1], x, domain='ZZ')

d = f.degree()
e = g.degree()

assert g.resultant(f) == ((-1)**(d*e))*(f.resultant(g))
```
**Am I misunderstanding something?**

**Comment by dianetc** [comment]
@skirpichev 
 $`res(f,g) = -1, res(g,f) = 1`$, so shouldn't the check be `assert resultant(f, g) == -resultant(g, f) == -1`?

**Comment by oscarbenjamin** [comment]
Usually the important property of the resultant is just whether it is zero or not and the sign does not really matter in context. Generally if I compute the resultant of two polynomials I consider it a symmetric function of the two and I don't care whether I compute `resultant(f, g, x)` or `resultant(g, f, x)`.

The resultant is used to define/compute the discriminant though and the sign of the discriminant does matter:
https://en.wikipedia.org/wiki/Discriminant#Definition

Maybe it is still possible to get the sign of the discriminant correct under different definitions for the sign of the resultant.

There are some notes about the definitions used in SymPy and the `resultant` function in particular here:
https://github.com/sympy/sympy/blob/12d7761b5033628cc12dc2f3b3df9546c2378086/sympy/polys/subresultants_qq_zz.py#L21-L88

**Comment by oscarbenjamin** [comment]
The inner function that computes this has this note:
https://github.com/sympy/sympy/blob/12d7761b5033628cc12dc2f3b3df9546c2378086/sympy/polys/euclidtools.py#L318
It then swaps the polynomials at the start:
https://github.com/sympy/sympy/blob/12d7761b5033628cc12dc2f3b3df9546c2378086/sympy/polys/euclidtools.py#L336-L341

Given two polynomials of equal degree then the resultant function will swap signs:
```python
In [4]: resultant(x+1, x+2, x)
Out[4]: 1

In [5]: resultant(x+2, x+1, x)
Out[5]: -1
```
However when their degrees are unequal they will be placed n a canonical order and so the sign does not depend on the order of the inputs.

The algorithm will be more efficient doing this swap. The question is whether a minus sign should be introduced to account for the swap though.

The discriminant function includes a sign variable `s` to relate the resultant to the discriminant:
https://github.com/sympy/sympy/blob/12d7761b5033628cc12dc2f3b3df9546c2378086/sympy/polys/euclidtools.py#L822-L827

In the case of the discriminant we will always have `deg(f) > deg(g)` so the swap would never occur though.

Note that there are many different resultant-related functions in the `euclidtools` module and many do this swap. Any change of behaviour here would need to be considered carefully to see whether all of the different functions are currently consistent and whether the change preserves that.

In general I don't expect that the sign of the resultant is likely to be a particularly important property although we can see that at least in the case of discriminant some things do depend on the sign.

I just checked sagemath and does give different signs for the example:
```python
>>> R.<x> = PolynomialRing(QQ, 'x')
>>> (x^3).resultant(x+1)
1
>>> (x+1).resultant(x^3)
-1
```
If nothing else consistency with other systems is also good so maybe this should be changed.

**Comment by oscarbenjamin** [comment]
@dianetc I presume that this comes from hypothesis testing. This is a case where there are many different functions that probably should all return the same results. Maybe it would be useful to assert consistency between those different implementations as part of the hypothesis testing scheme.

For example in the case of resultant we have:

1. The top-level `resultant` function.
2. The `Poly.resultant` method.
3. The `DMP.resultant` method.
4. The `PolyElement.resultant` method.
5. The `dup_resultant` function.
6. The `dmp_resultant` function.
7. `dmp_zz_modular_resultant`.
8. `dmp_zz_collins_resultant`.
9. `dmp_qq_collins_resultant`.

There may even be more!

**Comment by oscarbenjamin** [comment]
Here is code that tests all resultant methods:
```python
from sympy import *

from sympy.polys.euclidtools import (
    dup_resultant,
    dmp_resultant,
    dmp_zz_modular_resultant,
    dmp_zz_collins_resultant,
    dmp_qq_collins_resultant,
)

def resultant_Expr(p1, p2, x, K):
    return resultant(p1, p2, x)

def resultant_Poly(p1, p2, x, K):
    p1 = Poly(p1, x)
    p2 = Poly(p2, x)
    return p1.resultant(p2).as_expr()

def resultant_DMP(p1, p2, x, K):
    p1 = Poly(p1, x).rep
    p2 = Poly(p2, x).rep
    return Poly([p1.resultant(p2)], x).as_expr()

def resultant_PolyElement(p1, p2, x, K):
    R = K[x]
    return R(R(p1).resultant(R(p2))).as_expr()

def resultant_dup_resultant(p1, p2, x, K):
    p1 = Poly(p1, x).rep.rep
    p2 = Poly(p2, x).rep.rep
    return Poly(dup_resultant(p1, p2, K), x).as_expr()

def resultant_dmp_resultant(p1, p2, x, K):
    p1 = Poly(p1, x).rep.rep
    p2 = Poly(p2, x).rep.rep
    return Poly(dmp_resultant(p1, p2, 0, K), x).as_expr()

def resultant_dmp_zz_modular_resultant(p1, p2, x, K):
    p1 = Poly(p1, x).rep.rep
    p2 = Poly(p2, x).rep.rep
    p = 7
    return Poly(dmp_zz_modular_resultant(p1, p2, p, 0, K), x).as_expr()

def resultant_dmp_zz_collins_resultant(p1, p2, x, K):
    y = symbols('y')
    p1 = Poly(p1, x, y).rep.rep
    p2 = Poly(p2, x, y).rep.rep
    return Poly(dmp_zz_collins_resultant(p1, p2, 1, K), x).as_expr()

def resultant_dmp_qq_collins_resultant(p1, p2, x, K):
    y = symbols('y')
    p1 = Poly(p1, x, y).rep.rep
    p2 = Poly(p2, x, y).rep.rep
    return Poly(dmp_qq_collins_resultant(p1, p2, 1, K), x).as_expr()


methods = [
    resultant_Expr,
    resultant_Poly,
    resultant_DMP,
    resultant_PolyElement,
    resultant_dup_resultant,
    resultant_dmp_resultant,
    resultant_dmp_zz_modular_resultant,
    resultant_dmp_zz_collins_resultant,
    resultant_dmp_qq_collins_resultant,
]

x = symbols('x')
K = ZZ
p1 = x**3
p2 = x + 1

for method in methods:
    print("%s:" % method.__name__, method(p1, p2, x, K))
    print("%s:" % method.__name__, method(p2, p1, x, K))
    print()
```
Output:
```python
resultant_Expr: 1
resultant_Expr: 1

resultant_Poly: 1
resultant_Poly: 1

resultant_DMP: 1
resultant_DMP: 1

resultant_PolyElement: 1
resultant_PolyElement: 1

resultant_dup_resultant: 1
resultant_dup_resultant: 1

resultant_dmp_resultant: 1
resultant_dmp_resultant: 1

resultant_dmp_zz_modular_resultant: 1
resultant_dmp_zz_modular_resultant: 1

resultant_dmp_zz_collins_resultant: 1
resultant_dmp_zz_collins_resultant: 1

resultant_dmp_qq_collins_resultant: 1
resultant_dmp_qq_collins_resultant: 1
```
They are at least all consistent with each other but I think that is because in the base case they all boil down to the same routines that do the swap without accounting for sign.

**Comment by asmeurer** [comment]
Testing that differing implementations of the same function always agree is indeed a good use-case for hypothesis testing. In that case, we don't even have to have any kind of check that the output is "correct", just that all the implementations agree. In fact, I would expect this sort of thing to be rule rather than the exception for hypothesis testing since there are a lot of things where it is hard to directly test if the output is correct, but you can still do a consistency check against multiple implementations or multiple different ways of computing the same thing.

**Comment by asmeurer** [comment]
> Here is code that tests all resultant methods:

This is good, but for hypothesis, we'd actually want to do things the other way around, that is, generate input at the lowest level and construct the objects from that, because it is simplest to generate a list of integers with hypothesis. So something like

```py
from sympy import symbols

from sympy.polys.domains import ZZ
from sympy.polys.polytools import Poly, resultant
from sympy.polys.polyclasses import DMP
from sympy.polys.euclidtools import (
    dup_resultant,
    dmp_resultant,
    dmp_zz_modular_resultant,
    dmp_zz_collins_resultant,
    dmp_qq_collins_resultant,
)

x, y = symbols('x y')
K = ZZ
# Each of theses would be generated consectuvely by different hypothesis
# strategies (@composite and shared() are useful here)
p1_dup = [K(1), K(0), K(0), K(0)]
p2_dup = [K(1), K(1)]

p1_dmp = [[K(1)], [], [], []]
p2_dmp = [[K(1)], [K(1)]]

p1_dup_DMP = DMP(p1_dup, K)
p2_dup_DMP = DMP(p2_dup, K)

p1_dmp_DMP = DMP(p1_dmp, K)
p2_dmp_DMP = DMP(p2_dmp, K)

# Not sure how to generate PolyElement from a list

p1_dup_Poly = Poly(p1_dup, x, domain=K)
p2_dup_Poly = Poly(p2_dup, x, domain=K)

# For whatever reason, this raises an error sympy.polys.polyerrors.MultivariatePolynomialError: 'list' representation not supported
# p1_dmp_Poly = Poly(p1_dmp, x, y, domain=K)
# p2_dmp_Poly = Poly(p2_dmp, x, y, domain=K)

p1_expr = p1_dup_Poly.as_expr()
p2_expr = p2_dup_Poly.as_expr()

def resultant_dmp_zz_modular_resultant(p1, p2, x, K):
    # p would ideally be generated by hypothesis
    p = 7
    return Poly(dmp_zz_modular_resultant(p1, p2, p, 0, K), x).as_expr()

def resultant_dmp_zz_collins_resultant(p1, p2, x, K):
    return Poly(dmp_zz_collins_resultant(p1, p2, 1, K), x).as_expr()

def resultant_dmp_qq_collins_resultant(p1, p2, x, K):
    return Poly(dmp_qq_collins_resultant(p1, p2, 1, K), x).as_expr()

def resultant_dup_resultant(p1, p2, x, K):
    return Poly(dup_resultant(p1, p2, K), x).as_expr()

def resultant_dmp_resultant(p1, p2, x, K):
    return Poly(dmp_resultant(p1, p2, 0, K), x).as_expr()

def resultant_DMP(p1, p2, x, K):
    return Poly([p1.resultant(p2)], x).as_expr()

def resultant_PolyElement(p1, p2, x, K):
    return p1.resultant(p2).as_expr()

def resultant_Poly(p1, p2, x, K):
    return p1.resultant(p2).as_expr()

def resultant_Expr(p1, p2, x, K):
    return resultant(p1, p2, x)

methods = [
    resultant_dmp_zz_modular_resultant,
    resultant_dmp_zz_collins_resultant,
    resultant_dmp_qq_collins_resultant,
    resultant_dup_resultant,
    resultant_dmp_resultant,
    resultant_DMP,
    resultant_PolyElement,
    resultant_Poly,
    resultant_Expr,
]

print("resultant_dmp_zz_modular_resultant p1, p2:",
      resultant_dmp_zz_modular_resultant(p1_dup, p2_dup, x, K))
print("resultant_dmp_zz_modular_resultant p2, p1:",
      resultant_dmp_zz_modular_resultant(p2_dup, p1_dup, x, K))

print("resultant_dmp_zz_collins_resultant p1, p2:",
      resultant_dmp_zz_collins_resultant(p1_dmp, p2_dmp, x, K))
print("resultant_dmp_zz_collins_resultant p2, p1:",
      resultant_dmp_zz_collins_resultant(p2_dmp, p1_dmp, x, K))

print("resultant_dmp_qq_collins_resultant p1, p2:",
      resultant_dmp_qq_collins_resultant(p1_dmp, p2_dmp, x, K))
print("resultant_dmp_qq_collins_resultant p2, p1:",
      resultant_dmp_qq_collins_resultant(p2_dmp, p1_dmp, x, K))

print("resultant_dup_resultant p1, p2:",
      resultant_dup_resultant(p1_dup, p2_dup, x, K))
print("resultant_dup_resultant p2, p1:",
      resultant_dup_resultant(p2_dup, p1_dup, x, K))

print("resultant_dmp_resultant p1, p2:",
      resultant_dmp_resultant(p1_dup, p2_dup, x, K))
print("resultant_dmp_resultant p2, p1:",
      resultant_dmp_resultant(p2_dup, p1_dup, x, K))

print("resultant_DMP p1, p2:",
      resultant_DMP(p1_dup_DMP, p2_dup_DMP, x, K))
print("resultant_DMP p2, p1:",
      resultant_DMP(p2_dup_DMP, p1_dup_DMP, x, K))

# print("resultant_PolyElement p1, p2:",
#         resultant_PolyElement(p1_dup_PolyElement, p2_dup_PolyElement, x, K))
# print("resultant_PolyElement p2, p1:",
#         resultant_PolyElement(p2_dup_PolyElement, p1_dup_PolyElement, x, K))

print("resultant_Poly p1, p2:",
      resultant_Poly(p1_dup_Poly, p2_dup_Poly, x, K))
print("resultant_Poly p2, p1:",
      resultant_Poly(p2_dup_Poly, p1_dup_Poly, x, K))

print("resultant_Expr p1, p2:",
      resultant_Expr(p1_expr, p2_expr, x, K))
print("resultant_Expr p2, p1:",
      resultant_Expr(p2_expr, p1_expr, x, K))
```

(I'm not sure how to generate PolyElement from a list of numbers). 

The base hypothesis strategy would generate lists of numbers, just like https://github.com/sympy/sympy/pull/25428, and higher types would be generated from those with subsequent strategies using [`composite`](https://hypothesis.readthedocs.io/en/latest/data.html#composite-strategies) ([`shared`](https://hypothesis.readthedocs.io/en/latest/data.html#hypothesis.strategies.shared) is also useful here).

Actually, generating multivariate polynomials is a little harder (but doable), although in this case I think we are just generating the multivariate equivalent of a univariate polynomial, and I think there's a helper function somewhere that can just do this. For starters, though, I would only worry about univariate polynomials as that simplifies things a lot.
