### ISSUE TITLE
`linear_eq_to_matrix` should reject unordered symbols

### ISSUE THREAD

**Issue by smichr** [sympy/sympy#25423]
Although dictionaries are ordered in newer Python versions, sets are unordered and should be rejected as input to `linear_eq_to_matrix` which returns the linear coefficients for one or more expressions *in the order that symbols are given*. Although the routine which this function uses will order the symbols, this order is not reported back to the user. It might be better to simply raise an error in this case.
```python
>>> linear_eq_to_matrix(2*x + y, {x, y})  # order is `list(ordered({x,y})) -> [x, y]
(Matrix([[2, 1]]), Matrix([[0]]))
```

**Comment by haileyHaii** [comment]
Can I work on this?
