### ISSUE TITLE
Solve gives incorrect result with trigonometric functions

### ISSUE THREAD

**Issue by ThibaultLejemble** [sympy/sympy#25489]
I am solving polynomial equations that involve `cos` and `sin` functions, but these trigonometric functions are actually constant since I solve for `x`, `y` and `z` and I only use `cos(theta)` and `sin(theta)`, where `theta` is another symbol not used as variable when calling `solve()`.

I get the error using this piece of code 
```python
from sympy import *

x = Symbol('x')
y = Symbol('y')
z = Symbol('z')

theta = Symbol('theta')

a = Symbol('a')
b = Symbol('b')
c = Symbol('c')

eq = [
    x**2 - 1, 
    a**2*x**4*cos(theta)**4/4 +
        b**2*x**4*sin(theta)**4/4 +
        a*b*x**4*sin(theta)**2*cos(theta)**2/2 +
        2*x*z + y**2,
    2*x*y]

print(eq)

solutions = solve(eq, [x,y,z])

print(solutions)

# verify 
for sol in solutions:
    test0 = expand(eq[0].subs([(x,sol[0]), (y,sol[1]), (z,sol[2])]))
    test1 = expand(eq[1].subs([(x,sol[0]), (y,sol[1]), (z,sol[2])]))
    test2 = expand(eq[2].subs([(x,sol[0]), (y,sol[1]), (z,sol[2])]))
    print('____________')
    print(test0) # =0 (OK)
    print(test1) # != 0 (ERROR)
    print(test2) # =0 (OK)
```
that prints 
```
[x**2 - 1, a**2*x**4*cos(theta)**4/4 + a*b*x**4*sin(theta)**2*cos(theta)**2/2 + b**2*x**4*sin(theta)**4/4 + 2*x*z + y**2, 2*x*y]
[(-1, 0, (-a*sin(theta)**2 + a + b*sin(theta)**2)**2/8), (1, 0, -(-a*sin(theta)**2 + a + b*sin(theta)**2)**2/8)]
____________
0
-a**2*sin(theta)**4/4 + a**2*sin(theta)**2/2 + a**2*cos(theta)**4/4 - a**2/4 + a*b*sin(theta)**4/2 + a*b*sin(theta)**2*cos(theta)**2/2 - a*b*sin(theta)**2/2
0
____________
0
-a**2*sin(theta)**4/4 + a**2*sin(theta)**2/2 + a**2*cos(theta)**4/4 - a**2/4 + a*b*sin(theta)**4/2 + a*b*sin(theta)**2*cos(theta)**2/2 - a*b*sin(theta)**2/2
0
```

If I replace `cos(theta)` and `sin(theta)` by new symbols the solutions become valid
```python
from sympy import *

x = Symbol('x')
y = Symbol('y')
z = Symbol('z')

theta = Symbol('theta')

a = Symbol('a')
b = Symbol('b')
c = Symbol('c')

# eq = [
#     x**2 - 1, 
#     a**2*x**4*cos(theta)**4/4 +
#         b**2*x**4*sin(theta)**4/4 +
#         a*b*x**4*sin(theta)**2*cos(theta)**2/2 +
#         2*x*z + y**2,
#     2*x*y]
cosTheta = Symbol('cosTheta')
sinTheta = Symbol('sinTheta')
eq = [
    x**2 - 1, 
    a**2*x**4*cosTheta**4/4 +
        b**2*x**4*sinTheta**4/4 +
        a*b*x**4*sinTheta**2*cosTheta**2/2 +
        2*x*z + y**2,
    2*x*y]

print(eq)

solutions = solve(eq, [x,y,z])

print(solutions)

# verify
for sol in solutions:
    test0 = expand(eq[0].subs([(x,sol[0]), (y,sol[1]), (z,sol[2])]))
    test1 = expand(eq[1].subs([(x,sol[0]), (y,sol[1]), (z,sol[2])]))
    test2 = expand(eq[2].subs([(x,sol[0]), (y,sol[1]), (z,sol[2])]))
    print('____________')
    print(test0) # =0 ok
    print(test1) # =0 ok
    print(test2) # =0 ok
```
which prints
```
[x**2 - 1, a**2*cosTheta**4*x**4/4 + a*b*cosTheta**2*sinTheta**2*x**4/2 + b**2*sinTheta**4*x**4/4 + 2*x*z + y**2, 2*x*y]
[(-1, 0, (a*cosTheta**2 + b*sinTheta**2)**2/8), (1, 0, -(a*cosTheta**2 + b*sinTheta**2)**2/8)]
____________
0
0
0
____________
0
0
0
```

Is there an issue when calling `solve()` with `cos()` and `sin()`, or am I doing something wrong?

I am using `sympy` `1.9`, maybe I should upgrade it.

**Comment by geetHonve** [comment]
Hi, when I expand the result in the first case, I need to use the property of {sin(theta)**2 + cos(theta)**2 = 1}, it also reduces to 0 as it should be. But i tested both given sin, cos versions with this property and none of them explicitly gave "1" while it being a crucial property to solve this problem. I think somebody more well versed with this side of code can suggest the right path.

**Comment by geetHonve** [comment]
For the first case, you can add simplify(test1), that gives a 0 as required. 
This I figured was because the crucial property of sin(x)**2 + cos(x)**2 = 1, is implemented only by invoking simplify and it is an important property in the solving of the expression got at the end.

`from sympy import *

x = symbols('x')
y = symbols('y')
z = symbols('z')

theta = symbols('theta')

a = symbols('a')
b = symbols('b')
c = symbols('c')


expr = sin(theta)**2 + cos(theta)**2
expr2 = expr.subs(expr, 1)

eq = [
    x**2 - 1, 
    a**2*x**4*cos(theta)**4/4 +
        b**2*x**4*sin(theta)**4/4 +
        a*b*x**4*sin(theta)**2*cos(theta)**2/2 +
        2*x*z + y**2,
    2*x*y]

print(eq)

solutions = solve(eq, [x,y,z])

print(solutions)

# verify 
for sol in solutions:
    test0 = expand(eq[0].subs([(x,sol[0]), (y,sol[1]), (z,sol[2])]))
    test1 = expand(eq[1].subs([(x,sol[0]), (y,sol[1]), (z,sol[2])]))
    test2 = expand(eq[2].subs([(x,sol[0]), (y,sol[1]), (z,sol[2])]))
    print('____________')
    print(test0) # =0 (OK)
    print(simplify(test1)) # != 0 (ERROR)
    print(test2) # =0 (OK)`
    
    
gives 
`[x**2 - 1, a**2*x**4*cos(theta)**4/4 + a*b*x**4*sin(theta)**2*cos(theta)**2/2 + b**2*x**4*sin(theta)**4/4 + 2*x*z + y**2, 2*x*y]
[(-1, 0, (-a*sin(theta)**2 + a + b*sin(theta)**2)**2/8), (1, 0, -(-a*sin(theta)**2 + a + b*sin(theta)**2)**2/8)]
____________
0
0
0
____________
0
0
0`

**Comment by smichr** [comment]
`solve` does not (easily) know whether to keep the trig functions or mask them off as variables. As was noted, retention of them gives a solution which, when simplified, is actually zero. So the answer is correct, though not as simple as might be desired.
