### ISSUE TITLE
n_order possible optimization

### ISSUE THREAD

**Issue by jxu** [sympy/sympy#25488]
https://github.com/sympy/sympy/blob/d2be7bacd2604e98a642f74028e8f0d7d6084f78/sympy/ntheory/residue_ntheory.py#L62-L67

The code here repeatedly calculates `pow(a, order // p, n)`. But Looking at the algorithm in Bach & Shallit cited at https://rosettacode.org/wiki/Multiplicative_order, instead we factor n into prime powers and combine the multiplicative orders for a mod prime power via CRT. Also ord_p^k(a) = ord_p^(k-1)(a) or p times that, but I think the procedure works with p^k. Start with factorization phi(p) = p-1 = q1^e1 ... qk^ek, then set yi = (p-1)/qi^ei, xi = a^yi mod p, then repeatedly raise xi by qi until 1 is obtained (all mod p). This should be more efficient because qi is usually much smaller than order // p.

**Comment by haru-44** [comment]
I think it is a good idea. Intuitively it works, but I need to actually make it and see if it is faster.

I am not likely to start on it anytime soon.

**Comment by jxu** [comment]
For a Project Euler problem to calculate order of 10 mod n from 1 to 10^8, I observed a small speedup (30s to 25s). I was already using the LCM of prime powers for the factorization of n: For a,b coprime, order 10 mod ab = lcm(order 10 mod a, order 10 mod b)

Here's the code for order of 10 mod p. I think it'll work for arbitrary mod n as long as the factorization of phi(n) is computed and a is coprime to n.

```python
            tot = p-1  # order of Z/(p)
            factors = factors_from_linear_sieve(lp, tot)
            order = 1  # order of 10
            for qi, ei in factors.items():
                fi = 0
                yi = tot // (qi ** ei)
                xi = pow(10, yi, p)
                while xi != 1:
                    xi = pow(xi, qi, p)
                    fi += 1

                order *= qi ** fi 
```

**Comment by jxu** [comment]
See #25487 to avoid redundant computations.

**Comment by haru-44** [comment]
I think it should be closed.
