### ISSUE TITLE
Privileging expr.__class__ over expr.func for reconstruction

### ISSUE THREAD

**Issue by FabioLuporini** [sympy/sympy#25496]
Hi, simple question:

Why are there places in which `expr.__class__` is used, instead of `expr.func`, to reconstruct objects?

https://github.com/sympy/sympy/blob/master/sympy/polys/rationaltools.py#L77-L81

This hits subclasses (and in my specific case, a subclass overriding .func for custom reconstruction)

Thank you for the fantastic work with SymPy!

**Comment by oscarbenjamin** [comment]
No idea. The code goes back a long time (pre-github):
https://github.com/sympy/sympy/commit/dc327fedfa9b4edc774dcf7f38425e14eada5258
https://code.google.com/archive/p/sympy/issues/1069

Maybe func wasn't used then?

Sometimes things like this are the result of trying to handle non-Basic objects but in this example there is an explicit `isinstance(Basic)` check so it can't be that.

I would have expected that it should use `func`. Feel free to submit a pull request and we can see if anything noticeably breaks in the test suite.

**Comment by FabioLuporini** [comment]
OK thanks ! will do and reference here once ready

**Comment by sylee957** [comment]
There can be other instances like type(expr) constructor.

**Comment by asmeurer** [comment]
I think func was always there but historically it wasn't necessarily used consistently over the type (see e.g. 41b8eb5985583ace2b9e629aea0082d2c5d7af20)

**Comment by FabioLuporini** [comment]
Tentative patch: https://github.com/sympy/sympy/pull/25529

@mloubout
