### ISSUE TITLE
RecursionError in inverse_laplace_transform

### ISSUE THREAD

**Issue by proy87** [sympy/sympy#25520]
`inverse_laplace_transform(1/(s**4 - 4*s**3 + 5*s**2 - 2*s + 1), s, t)` raises `RecursionError`

**Comment by hanspi42** [comment]
Thanks for telling us!

This runs without problems in the most recent development version, so I looked for the fix using `git bisect`. 

Turns out that I have solved this by chance in #24778 when I re-wrote `laplace_deep_collect`. :)
