### ISSUE TITLE
AttributeError: module 'sympy' has no attribute 'physics'

### ISSUE THREAD

**Issue by wermos** [sympy/sympy#25551]
While working on the LaTeX parser, I ran into this issue:
```python
>>> import sympy
>>> b = sympy.physics.quantum.state.Bra(sympy.Symbol('x'))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'sympy' has no attribute 'physics'
```
Not sure why it can't find the physics module.

Something like
```python
>>> import sympy.physics.quantum
>>> Bra('x')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'Bra' is not defined
>>> import sympy.physics.quantum as q
>>> q.Bra('x')
<x|
```
still works, surprisingly.

It might not be a bug but I can't figure out this weird behavior.

**Comment by Upabjojr** [comment]
That's how Python imports work. It does **not** look like a bug.

**Comment by Upabjojr** [comment]
Importing the main module does not import the submodules.

**Comment by wermos** [comment]
> Importing the main module does not import the submodules.

I'm not sure what you mean by this. For example, this works:
```python
>>> import sympy
>>> x = sympy.core.numbers.Integer(5)
```

**Comment by oscarbenjamin** [comment]
This is just the way that imports work. Try creating a package and testing it yourself.

**Comment by wermos** [comment]
Alright, since it looks like the issue is my understanding of Python import and not an issue in SymPy, I'm closing the issue.
