### ISSUE TITLE
`GramSchmidt` can't work with symbolic matrices

### ISSUE THREAD

**Issue by CharlesJQuarra** [sympy/sympy#25559]
I provided a very simple 2x2 matrix to sympy:

```
import sympy as sp

sq = sp.Matrix([[sp.sqrt(3), sp.sqrt(2)], [- sp.sqrt(2), sp.sqrt(3)]])
```

I tried to find an orthogonal basis spanned with the row vectors of this matrix *hint: they are already orthogonal* but `GramSchmidt` reports a weird error about square roots or powers not having a matrix method interface:

```
>>> sp.GramSchmidt(sq)
..... anaconda3/lib/python3.8/site-packages/sympy/matrices/subspaces.py", line 176, in _orthogonalize
    while len(vecs) > 0 and vecs[0].is_zero_matrix:
AttributeError: 'Pow' object has no attribute 'is_zero_matrix'
```

I wanted to find the target and null space of irrational matrices, but I cannot proceed further because of this error

```
>>>sp.__version__
'1.6.2'
```

**Comment by sylee957** [comment]
Unfortunately, it isn't a correct way to use GramSchmidt
In the documentation, you should pass a 'list' of matrix, than a matrix.
```
sq = [
    sp.Matrix([sp.sqrt(3), sp.sqrt(2)]), 
    sp.Matrix([-sp.sqrt(2), sp.sqrt(3)])
]
sp.GramSchmidt(sq)
```

I agree that the error is misleading, but I don't think that it is easy to give users correct errors

**Comment by CharlesJQuarra** [comment]
> Unfortunately, it isn't a correct way to use GramSchmidt In the documentation, you should pass a 'list' of matrix, than a matrix.
> 
> ```
> sq = [
>     sp.Matrix([sp.sqrt(3), sp.sqrt(2)]), 
>     sp.Matrix([-sp.sqrt(2), sp.sqrt(3)])
> ]
> sp.GramSchmidt(sq)
> ```
> 
> I agree that the error is misleading, but I don't think that it is easy to give users correct errors. The reason is that vecs[0] points out to Matrix[0, 0] if you pass a single Matrix than a list, and since it is just a single square root, it gives an error

Thanks! I can work with this, albeit it is counterintuitive that the row vectors will be on their own Matrix object. I will close this now

**Comment by oscarbenjamin** [comment]
It probably does make sense to be able to do Gram Schmidt with matrices (on rows or perhaps columns).
