### ISSUE TITLE
Simplify of `re(x) + I*im(x)`

### ISSUE THREAD

**Issue by MGinsberg** [sympy/sympy#25564]
I'm showing a problem with sympy not realizing that  re(a)+ I*im(a) = a

The code snippet where I ran into it is as follows:

a, b, g, k, s, t, x, y = symbols('a b g k s t x y')
expr=(k*g/(s-a))
print(simplify(inverse_laplace_transform(expr,s,t)))

Which prints "g*k*exp(t*(re(a) + I*im(a)))*Heaviside(t)"

So either there is a previous fix that I should be made aware of, or there is a missing identity in the "simplify" routine.

Anyone care to comment?

**Comment by sylee957** [comment]
`out = inverse_laplace_transform(expr,s,t))` and
`simplify(out.rewrite(re))` or `simplify(out.rewrite(im))` gives the result though.

**Comment by MGinsberg** [comment]
Thanks for the work around.  Much appreciated.

**Comment by MGinsberg** [comment]
Another solution is to declare 'a' to be real.

**Comment by hanspi42** [comment]
I looked deeper into this; this behaviour disappeared with #24765, which is in Sympy 1.12. Can I close the issue?

**Comment by oscarbenjamin** [comment]
I guess there is a separate question about whether `simplify` should be able to handle something like this:
```python
In [2]: simplify(re(a)+I*im(a))
Out[2]: re(a) + ⅈ⋅im(a)
```
There is another issue somewhere for that though I think.

The issue here with `inverse_laplace_transform` is fixed.

**Comment by hanspi42** [comment]
> There is another issue somewhere for that though I think.

Yes, it is #18271

**Comment by MGinsberg** [comment]
Sorry not to reply earlier.  I'm kinda sheepish, but I can't find the right incantation to make anaconda update to sympy 1.12.  I've tried the obvious stuff, and I keep getting updated to sympy 1.11.  Any gentle guidance?

**Comment by oscarbenjamin** [comment]
There are problems with mixing Anaconda and pip but you could just `pip install sympy`.

**Comment by MGinsberg** [comment]
When attempted via "pip install sympy" I get the following...
Requirement already satisfied: sympy in c:\users\admin\anaconda3\lib\site-packages (1.11.1)
Requirement already satisfied: mpmath>=0.19 in c:\users\admin\anaconda3\lib\site-packages (from sympy) (1.3.0)

**Comment by oscarbenjamin** [comment]
You can use `pip install -U sympy` to update but I recommend instead first uninstalling sympy like `conda uninstall sympy` and then installing with pip like `pip install sympy`.

I am not much of a conda user myself but I think that there are ways that mixing conda and pip can be problematic so I would not recommend following this approach in general but it can be okay for a quick test.

**Comment by sylee957** [comment]
You can always experiment with dev version of SymPy with github codespaces.

**Comment by hanspi42** [comment]
> When attempted via "pip install sympy" I get the following... Requirement already satisfied: sympy in c:\users\admin\anaconda3\lib\site-packages (1.11.1) Requirement already satisfied: mpmath>=0.19 in c:\users\admin\anaconda3\lib\site-packages (from sympy) (1.3.0)

With Anaconda, you can always get new versions faster if you use conda-forge.

For example, you can do:

`conda install sympy=1.12 --channel conda-forge`

If you want to know more about conda-forge: https://conda-forge.org/docs/user/introduction.html
