### ISSUE TITLE
asv 0.6.0 breaks our CI

### ISSUE THREAD

**Issue by moorepants** [sympy/sympy#25561]
A new ASV came out yesterday and is failing with:

```
Run asv run --config asv.conf.actions.json
Couldn't load asv.plugins.mamba because
No module named 'mamba'
Couldn't load asv.plugins.virtualenv because
No module named 'packaging'
· Unknown environment type 'virtualenv'
· No environments selected
Error: Process completed with exit code 1.
```

We will pin asv for a temporary solution.

**Comment by moorepants** [comment]
This is the only thing referencing mamba in the changelog:

```
- ``mamba`` and ``conda`` use ``environment.yml`` if it exists
```

**Comment by moorepants** [comment]
The error raised had some changes around it:

https://github.com/airspeed-velocity/asv/compare/v0.5.1...v0.6.0#diff-d02369f9dea9fca9ff62b435167e39cd05aedfd6be0b15e8e1e572e714f2099bR28

**Comment by moorepants** [comment]
There is a new mamba plugin and I guess it is trying to load it:

https://github.com/airspeed-velocity/asv/compare/v0.5.1...v0.6.0#diff-efea474305a4261d32ed638154542535d25b25d4c848e25776a581a96613adc7R1

**Comment by tqa236** [comment]
Hello, I think that this issue is resolved now as `asv` is unpinned in https://github.com/sympy/sympy/pull/25625

**Comment by oscarbenjamin** [comment]
Thanks
