### ISSUE TITLE
Taylor Expansion

### ISSUE THREAD

**Issue by jaindevesh144** [sympy/sympy#25573]
There should be a function to expand an expression in taylor polynomial

**Comment by oscarbenjamin** [comment]
Presumably like this:
```python
In [11]: exp(x).series(n=3)
Out[11]:
         2
        x     ⎛ 3⎞
1 + x + ── + O⎝x ⎠
        2

In [12]: exp(x).series(n=3).removeO()
Out[12]:
 2
x
── + x + 1
2
```
I'm closing for now. This can be reopened if the above is not suitable and if more explanation is given about what is actually wanted.
