### ISSUE TITLE
positive -> extended_positive?

### ISSUE THREAD

**Issue by smichr** [sympy/sympy#25580]
```
>>> var('n',positive=1)
n
>>> n.is_positive
True
>>> n.is_extended_positive
True                                          <--- should be False?
>>> n.is_extended_real
True                                          <--- should be False?
>>> n.is_finite
True
>>> n.is_infinite
False

>>> var('n',extended_positive=True)
n
>>> n.is_positive
>>> n.is_extended_positive
True
>>> n.is_extended_real
True
>>> n.is_finite  # -> None
>>> n.is_infinite  # -> None
```
It seems like this behavior is reversed to me. If I know it is positive, I don't know if it is infinite so I don't know why the extended tests are giving True.

**Comment by bobby-palmer** [comment]
According to the documentation, extended positive means that it could either be positive OR infinity (hence extended).
The predicate for being positive infinity is called `Q.positive_infinite({EXPR})` However I don't see that there is a way to call this like `n.is_positive_infinite`. maybe this functionality should be added

**Comment by asmeurer** [comment]
This looks correct to me. Extended positive is a superset of positive, so knowing positive means you know it is extended positive, but not the other way around. Positive implies finite because positive implies real. Note that x > 0 more accurately means extended positive than positive because it could include infinity.

**Comment by oscarbenjamin** [comment]
> The predicate for being positive infinity is called `Q.positive_infinite({EXPR})`

This predicate is outdated. It should be called `Q.extended_positive`.

**Comment by oscarbenjamin** [comment]
Everything here is working as it should.
