### ISSUE TITLE
Incorrect limit for atan

### ISSUE THREAD

**Issue by proy87** [sympy/sympy#25582]
`limit(atan(exp(x)),x,oo,'-')` doesn't return `pi/2`.

**Comment by anutosh491** [comment]
Well I do think sympy is capable of doing this but the approach being followed is not exactly correct . I would expect this to be solved through `gruntz` but it is being solve through the `leading term` approach.
```
>>> x = Symbol("x")
>>> gruntz(atan(exp(x)), x, oo)
pi/2
>>> gruntz(atan(exp(x)), x, -oo)
0
>>> gruntz(asin(exp(x)), x, oo)
-oo*I
>>> gruntz(asin(exp(x)), x, -oo)
0
```
This is correct for almost all hyperbolic and inverse-hyperbolic functions.
If we look at the code https://github.com/sympy/sympy/blob/f3f81124d8795f095ef53ea786042da7371c74a1/sympy/functions/elementary/trigonometric.py#L2677-L2679
Here `x0` would become `nan` and there is no check for handling `nan`. 
I think the correct approach here is to return a `PoleError` when we encounter `nan`.

**Comment by borgesaugusto** [comment]
Hello, I have made PR  ( #25763 ) implementing [anutosh491](https://github.com/anutosh491)'s idea.
