### ISSUE TITLE
n=6000002; `int(n*(log(n) + log(log(n))))` takes more than 200 s to compute on sympy.live.org

### ISSUE THREAD

**Issue by platypus999** [sympy/sympy#25698]
Version: sympy 1.12

The `sympy.prime` takes an unnaturally long time to return its value on certain arguments, for example, $6000002$. Note that feeding surrounding values such as $6000001$ and $6000003$ to the function does not yield such a hang.

```
sympy.prime(6000001) # Instant
sympy.prime(6000002) # Takes well over a minute
sympy.prime(6000003) # Instant
```

This is likely due to the code of calculating the upper bound for binary searching the value of $\mathrm{li}^{-1}$.
https://github.com/sympy/sympy/blob/f59cbf85581d2b9cd23d8f864607f4520df2366f/sympy/ntheory/generate.py#L441
Here, the equation `n * (log(n) + log(log(n)))` is calculated, and then casted to an `int`. When $n$ is $6000002$, the value of `n * (log(n) + log(log(n)))` is close to an integer (`110130079.99980894` when casted to a float). 
When provided with an $n$ such that the value of $n (\log n + \log \log n)$ is close to an integer, the `sympy.prime` function becomes extremely slow compared to other values close to $n$.

**Comment by smichr** [comment]
The easy solution is to evaluate the expression before taking int:  `b = int((n*(log(n) + log(log(n)))).n())`. I don't think being off a little is significant in this case so perhaps ceil could be used instead of int.

**Comment by platypus999** [comment]
Thank you for the comment! I will fix the line calculating `b` with your method and make a pull request.

**Comment by platypus999** [comment]
https://github.com/sympy/sympy/pull/25699

**Comment by smichr** [comment]
I left a comment on the PR. I am not sure why that expression is taking so long to compute. The value is 110130079.999809 so it's not that large nor even that close to an integer -- 13th digit indicates the need to round down.

**Comment by platypus999** [comment]
Thank you! I replied to some of your concerns in PR.

As for why the computation time is so long when the value is not that close to an integer, I couldn't find a convincing answer, but I found that the resulting value does not need to be extremely close to an integer, just the number rounded to the 2nd decimal place is important.

The method of casting equations to `int` seems to greatly differ depending on whether the value is an integer ±0.005. When such an expression enters `Eval.__int__` below, `i == r` (where `r` is the value rounded to the 2nd decimal place and `i` is `int(r)`), and the second `(self - i).equals(0)` will be evaluated.
https://github.com/sympy/sympy/blob/f59cbf85581d2b9cd23d8f864607f4520df2366f/sympy/core/expr.py#L330
Calling `equals` here leads to a lengthy and time-consuming sequence of function calls, which I suppose many thousand digits are calculated precisely. (Why so many digits are calculated is a mystery though)

**Comment by asmeurer** [comment]
What is the purpose of that block? Shouldn't round(2) be correct, and fixed if it is not?

**Comment by smichr** [comment]
The logic should be simplified to something like this:
```python
r = eq.round(2)
if int_valued(r):
    # it might have rounded to an int and be 1 too high
    return int(r - 1) if r > eq else int(r)
return int(r)
```

**Comment by smichr** [comment]
@platypus999 , no matter how simple of a change I think something is, there is always something that shows what I missed. Perhaps you could try make the change at the top

```python
from .numbers import int_valued
...
```
and then instead of calculating `i = int(r)` just do
```python
if int_valued(r):
    # it might have rounded to an int and be 1 too high
    return int(r - 1) if r > self else int(r)
return int(r)
```
BUT the problem is that the comparisons might not evaluate. So
```python
i = int(r)
if int_valued(r):
    if self > i is S.true:
        return i
    if self < i is S.true:
        return i - 1
    if self > i is S.false and self < i is S.False:
        return i
    if self.equals(i):
        return i
    assert None  # what should be done now?
return i
```

**Comment by atharvParlikar** [comment]
Is the issue resolved because the specific slow example is working quite fast on my machine, or am I missing something?
```python
import sympy as sp
import time

start = time.time()

print("6000002th prime number:", sp.prime(6000002));

print("Time taken:", time.time() - start, "seconds")
```
output:
```
❯ python3 _.py
6000002th prime number: 104395337
Time taken: 0.2081165313720703 seconds
```

**Comment by smichr** [comment]
> Is the issue resolved because the specific slow example is working quite fast on my machine, or am I missing something?

I was confused by the same thing. It is fast in current dev because the if-block fails when testing `r == i` (Float is no longer equal to int). So that block (which contains the slow `equals` tests) is bypassed. The PR re-activates the block but now uses other tests that often can succeed (as in this case) without using `equals`. So doing the right thing, now, doesn't take much longer than doing the wrong thing.

**Comment by smichr** [comment]
continued in #25704
