### ISSUE TITLE
Powermod bug?

### ISSUE THREAD

**Issue by fedematico** [sympy/sympy#25707]
I believe I've encountered a bug with the `powermod` function in SymPy.

I expected the `powermod` function to produce a result of 5 when calculating `powermod(2, 17, 9)

The `powermod` function is currently producing a result of 8 for `powermod(2, 17, 9)`.

1. Import SymPy **version 1.8 (Sep 2021 is an old one?)**
2. Use the `powermod` function with the inputs `powermod(2, 17, 9)`.

1. Import SymPy.
2. Use the `powermod` function with the inputs `powermod(2, 17, 9)`.

I have verified that `mod(2^17, 9)` correctly results in 5, but `powermod(2, 17, 9)` is producing 8. I believe this may be a bug in the `powermod` function?

I attempted to cross-check the result with manual calculations and confirmed that the result is inconsistent with expectations.

**Comment by oscarbenjamin** [comment]
I don't see any `powermod` function in current SymPy. Also yes, 1.8 is an old version. The current release is 1.12.

**Comment by smichr** [comment]
```python
>>> pow(2, 17, 9)
5
```

**Comment by fedematico** [comment]
Thank you smichr, I'm new with simpy, and I'll use pow then. Thank you for your answer.
