### ISSUE TITLE
GCD missing polynomial factor

### ISSUE THREAD

**Issue by oscarbenjamin** [sympy/sympy#25723]
This comes from a hypothesis failure in CI:
```python
In [16]: gcd(-32425*(x - 35541), -32425*(x - 35541)*(2*x + 1))
Out[16]: 32425

In [17]: gcd((x - 35541), (x - 35541)*(2*x + 1))
Out[17]: 1
```
Clearly the GCD is not 1.

**Comment by smichr** [comment]
It starts failing after `i=4850`
```python
>>> i=4850;gcd(x-i,(x-i)*(2*x+1))
x - 4850
>>> i=4851;gcd(x-i,(x-i)*(2*x+1))
1
```

**Comment by oscarbenjamin** [comment]
With gh-25722 and ground types = flint this problem is not seen:
```console
$ SYMPY_GROUND_TYPES=flint isympy
...
In [1]: gcd((x - 35541), (x - 35541)*(2*x + 1))
Out[1]: x - 35541
```
The bug must be somewhere in the DMP.gcd code.

**Comment by oscarbenjamin** [comment]
It goes wrong inside heugcd somewhere:
https://github.com/sympy/sympy/blob/f63c3f688544e4e7b4924365521308e80e545110/sympy/polys/euclidtools.py#L1224
The sparse implementation gets it right:
```python
In [3]: R = ZZ[x]

In [4]: p1 = R((x - 35541))

In [5]: p2 = R((x - 35541)*(2*x + 1))

In [6]: p1
Out[6]: x - 35541

In [7]: p2
Out[7]: 2*x**2 - 71081*x - 35541

In [8]: p1.gcd(p2)
Out[8]: x - 35541
```
There must be some difference between the dense and sparse implementations:
https://github.com/sympy/sympy/blob/f63c3f688544e4e7b4924365521308e80e545110/sympy/polys/euclidtools.py#L1147-L1250
https://github.com/sympy/sympy/blob/f63c3f688544e4e7b4924365521308e80e545110/sympy/polys/heuristicgcd.py#L55-L118

**Comment by oscarbenjamin** [comment]
Looks like gh-18566 which fixed this in the sparse implementation should also be applied in the dense implementation

**Comment by oscarbenjamin** [comment]
This is the change needed:
```diff
diff --git a/sympy/polys/euclidtools.py b/sympy/polys/euclidtools.py
index 16cff2a03d..9df09416d3 100644
--- a/sympy/polys/euclidtools.py
+++ b/sympy/polys/euclidtools.py
@@ -1199,7 +1199,7 @@ def dup_zz_heu_gcd(f, g, K):
 
     x = max(min(B, 99*K.sqrt(B)),
             2*min(f_norm // abs(dup_LC(f, K)),
-                  g_norm // abs(dup_LC(g, K))) + 2)
+                  g_norm // abs(dup_LC(g, K))) + 4)
 
     for i in range(0, HEU_GCD_MAX):
         ff = dup_eval(f, x, K)
```

**Comment by smichr** [comment]
Let's not leave a wrong answer to wait for someone to pick it up. I'll post a PR now.

**Comment by smichr** [comment]
Similar structure in dup_zz_heu_gcd and made change there but don't have a failing test for it.
