### ISSUE TITLE
Incorrect domain of `pi`

### ISSUE THREAD

**Issue by vitrun** [sympy/sympy#25736]
sympy v1.12:

```python
In [69]: construct_domain(pi)
Out[69]: (ZZ[pi], pi)
```

The domain of `pi` should be `RR`.

**Comment by oscarbenjamin** [comment]
We would not want to use an inexact domain like `RR` for something exact like `pi` and the integers. Since `pi` is transcendental the polynomial ring `ZZ[pi]` is a valid domain for representing expressions involving `pi`:
```python
In [1]: D = ZZ[pi]

In [2]: e1 = D(1 + pi)

In [3]: e1
Out[3]: pi + 1

In [4]: e1**2
Out[4]: pi**2 + 2*pi + 1
```
