### ISSUE TITLE
Adding NumPy, SciPy and matplotlib to environments for doctest jobs in CI

### ISSUE THREAD

**Issue by brocksam** [sympy/sympy#25741]
PR https://github.com/sympy/sympy/pull/25525 sets to add a tutorial for the new biomechanics package in `sympy.physics`. This tutorial contains lots of code snippets going over the usage of the biomechanics package. For these to be doctested in full, additional dependencies of NumPy, SciPy, and matplotlib are required. These aren't currently installed in the environments of the CI jobs that run the doctests.

In PR https://github.com/sympy/sympy/pull/25525 we simply install these three additional packages into the environment in the doctests-related CI jobs. I'm opening this issue to draw attention to this specifically to see if anyone objects to this approach.

This feels like the simplest approach. We are not aware of any way of conditionally running doctests that have additional dependencies. Even if there was it would likely significantly complicate the documentation files and CI workflows. If there is a good reason to not have NumPy, SciPy, and matplotlib installed in CI then the alternative would be to skip the corresponding code snippets in these doctests, but that would mean that large chunks of the biomechanics tutorial's code aren't being tested.

**Comment by brocksam** [comment]
One immediate downside of that simply trying to install SciPy with PyPy in CI fails due to missing OpenBLAS.

**Comment by oscarbenjamin** [comment]
> One immediate downside of that simply trying to install SciPy with PyPy in CI fails due to missing OpenBLAS.

Is it not just a case of installing libopenblas-dev?
https://github.com/sympy/sympy/blob/191a72d67a4c082d2c526bc390c1d00b73ffcdd3/.github/workflows/runtests.yml#L200

**Comment by oscarbenjamin** [comment]
> We are not aware of any way of conditionally running doctests that have additional dependencies.

https://github.com/sympy/sympy/blob/191a72d67a4c082d2c526bc390c1d00b73ffcdd3/sympy/utilities/decorator.py#L126-L175

**Comment by oscarbenjamin** [comment]
We also need to test that SymPy works without having NumPy etc installed. Inevitably if no CI jobs test that case then someone will add code that depends on NumPy which would then become a hard dependency rather than an optional dependency.

What should be done to test this is to add this to the optional dependency jobs:
https://github.com/sympy/sympy/blob/191a72d67a4c082d2c526bc390c1d00b73ffcdd3/bin/test_optional_dependencies.py#L86-L128

**Comment by brocksam** [comment]
Thanks for pointing me to `doctest_depends_on`. The complication is that the code that we're testing is within code blocks in a `.rst` file so we can't directly apply the decorator to a specific function or class.

Would your recommended solution be to blacklist the whole of the tutorial in question from the general doctests run with just SymPy and mpmath? And then add it specifically to the `doctest_list` in `sympy/bin/test_optional_dependencies.py`?

**Comment by oscarbenjamin** [comment]
> Would your recommended solution be to blacklist the whole of the tutorial in question from the general doctests run with just SymPy and mpmath? And then add it specifically to the `doctest_list` in `sympy/bin/test_optional_dependencies.py`

That is one possibility. Ideally the general mechanism for conditionally running doctests needs to be improved so we need an analogue of `doctest_depends_on` that can work for rst files. Also `doctest_depends_on` already does not work with `pytest-doctestplus` (if I remember correctly) and really we should be trying to switch to using that.

**Comment by moorepants** [comment]
One option is to make a new job that only doctests .rst files that need the optional dependencies and leave the current doctest as it is (blacklisting the .rst files we have running in the new job). Sorry if this was already said.

**Comment by oscarbenjamin** [comment]
> One option is to make a new job that only doctests .rst files that need the optional dependencies and leave the current doctest as it is

We already have a job that does this (the optional dependency jobs). We just not to have that job also test the .rst files.

**Comment by brocksam** [comment]
Closing as we are now using the optimal dependency job and putting tutorials in the `doctest_list` for this.
