### ISSUE TITLE
The unimodular matrices in the smith normal form

### ISSUE THREAD

**Issue by ZhouGD2000** [sympy/sympy#25759]
The Sympy package supports the calculation of the Smith normal form of a matrix. However, the unimodular matrices S,T such that A = S * J * T where A is the original matrix and J is the Smith normal form are not given. I hope there will be a function providing S,T too. Thanks a lot.

**Comment by samithkavishke** [comment]
Can i work on this?

**Comment by oscarbenjamin** [comment]
Anyone is welcome to work on this. You can find the existing code for Smith normal form here and there is also a note about potentially better algorithms that could be implemented:
https://github.com/sympy/sympy/blob/0cff299b7c0568360cb9e53320bbc2d333a8001b/sympy/polys/matrices/normalforms.py#L11-L17
Ideally we should ensure that anything here is compatible with python-flint which should also be used when possible but a pure Python implementation will be needed for when python-flint is not installed:
```python
In [1]: from sympy.polys.matrices.normalforms import smith_normal_form

In [2]: M = randMatrix(5)

In [3]: M
Out[3]: 
⎡18  54  98  45  24⎤
⎢                  ⎥
⎢97  68  35  93  74⎥
⎢                  ⎥
⎢74  28  69  62  72⎥
⎢                  ⎥
⎢52  94  75  84  55⎥
⎢                  ⎥
⎣75  63  63  58  99⎦

In [4]: dM = M.to_DM()

In [5]: smith_normal_form(dM).to_Matrix()
Out[5]: 
⎡1  0  0  0      0     ⎤
⎢                      ⎥
⎢0  1  0  0      0     ⎥
⎢                      ⎥
⎢0  0  1  0      0     ⎥
⎢                      ⎥
⎢0  0  0  1      0     ⎥
⎢                      ⎥
⎣0  0  0  0  -154076689⎦

In [6]: import flint

In [7]: fM = flint.fmpz_mat([[int(i) for i in row] for row in M.tolist()])

In [8]: fM
Out[8]: 
[18, 54, 98, 45, 24]
[97, 68, 35, 93, 74]
[74, 28, 69, 62, 72]
[52, 94, 75, 84, 55]
[75, 63, 63, 58, 99]

In [9]: fM.snf()
Out[9]: 
[1, 0, 0, 0,         0]
[0, 1, 0, 0,         0]
[0, 0, 1, 0,         0]
[0, 0, 0, 1,         0]
[0, 0, 0, 0, 154076689]
```

**Comment by oscarbenjamin** [comment]
> I have already resolved this issue.
> 
> #25799

The code in that PR is a good start but more work is needed before this issue can be solved.

For anyone looking at this and wanting to make a start note that a calculation like this should be done using DomainMatrix and the domain system rather than by using the Matrix type:
https://docs.sympy.org/latest/modules/polys/domainmatrix.html
https://docs.sympy.org/latest/modules/polys/domainsintro.html

A good way to start with this would be to study the code for the existing implementation which already uses DomainMatrix.

**Comment by oscarbenjamin** [comment]
> Can I work on this issue and go on resolve it?

Yes, anyone can work on this.

**Comment by oscarbenjamin** [comment]
This has been added now in gh-17451:
```python
In [6]: from sympy.matrices.normalforms import smith_normal_decomp

In [7]: M = Matrix([[1, 2], [3, 4]])

In [8]: smith_normal_decomp(M)
Out[8]: 
⎛⎡1  0⎤  ⎡1  0 ⎤  ⎡1  -2⎤⎞
⎜⎢    ⎥, ⎢     ⎥, ⎢     ⎥⎟
⎝⎣0  2⎦  ⎣3  -1⎦  ⎣0  1 ⎦⎠
```
