### ISSUE TITLE
solution loss when passing equation as list

### ISSUE THREAD

**Issue by BlankShrimp** [sympy/sympy#25781]
Test case:
```python
x= sympy.symbols("x", real=True)
a = sympy.Eq(sympy.sqrt(x / 2), x)
```

Test result:
```python
sympy.solve(a, x, dict=True)     # [{x: 0}, {x: 1/2}], no problem
sympy.solve(a, [x], dict=True)   # [{x: 0}, {x: 1/2}], no problem
sympy.solve([a], x, dict=True)   # [{x: 1/2}], lose x=0
```

When putting single equation in a list, the solve() may lost solutions in certain circumstance. I'm not sure if this is a designed behavior or flaw, my guess is substituting intermediate solutions to other equations (when there is None in [a]).

**Comment by oscarbenjamin** [comment]
This is a bug. Passing the equation is a list results in a different code path (that inconsistency should be removed). That different code path apparently has a bug that loses the solution somehow.

**Comment by smichr** [comment]
This is failing because of how the equation is processed with `_invert`. When it gets `a1*b**e1 = a2*b**e2` it rewrites as `b**(e1-e2) = a2/a1` In the case of `sqrt(f(x)) = f(x)` this becomes `1/sqrt(f(x)) = 1` and the solution for `f(x) = 0` is lost.
```
solve([sqrt(x-2)-(x-2)**2])
[{x: 3}]  # 2 is missing
```
