### ISSUE TITLE
Minor issues in the new biomechanics docs

### ISSUE THREAD

**Issue by moorepants** [sympy/sympy#25785]
Math not rendering here:
![image](https://github.com/sympy/sympy/assets/276007/dac231e7-8ccf-4aeb-b436-1e609661fce0)
![image](https://github.com/sympy/sympy/assets/276007/17a88784-02bc-45b3-a5e9-bc991f6aeca8)

Number of places we could use sphinx rerferencing to create hyperlinks, e.g.:
![image](https://github.com/sympy/sympy/assets/276007/e9a95beb-85e2-4360-8dff-80049b44cb18)

**Comment by bsach64** [comment]
Hey, Can I work on this?

**Comment by moorepants** [comment]
Anyone can work on it.
