### ISSUE TITLE
Limit at infinity of arctan(expression that goes to infinity) erroneously gives NaN or it doesn't compute.

### ISSUE THREAD

**Issue by mashburnj** [sympy/sympy#25833]
I wrote an exercise for students requiring them to compute the limit of `sp.atan(sp.log(2**x) / sp.log(2*x))` as x approaches infinity, which should have been pi/2. However, on SymPy 1.12, some students get NaN, while others get `Limit(expression, x, oo)`. I downgraded to 1.7.1, and it computed properly with that.

Taking the limit of `sp.atan(x**2)` works, but even something as "complicated" as `sp.atan(x**2 - 1)` will give me the same erroneous result.

**Comment by oscarbenjamin** [comment]
With current master I get:
```python
In [2]: limit(atan(log(2**x)/log(2*x)), x, oo)
Out[2]: 
π
─
2
```

**Comment by oscarbenjamin** [comment]
Looks like this was fixed in 86fd144cfeca1937b19d05370bdef95446767c40 from gh-25763.

**Comment by oscarbenjamin** [comment]
It would be good to add a test for this case.

**Comment by oscarbenjamin** [comment]
Thanks for reporting!
