### ISSUE TITLE
Logs not simplified

### ISSUE THREAD

**Issue by vitrun** [sympy/sympy#25860]
```python
In [21]: expr = log(5, 10)**2 + log(5, 10)*log(2, 10) + log(2, 10)

In [22]: simplify(expr)
Out[22]: (log(2) + log(5))/log(10)
```
The result is expected to be 1. 
Sympy version used: v1.12

**Comment by oscarbenjamin** [comment]
I thought that `expand_log` might do this but it does not seem to. I am not sure that `expand_log` should do this but at least there should be some `simplify` function that can do this.

**Comment by shreyash3087** [comment]
You need to simplify the expression twice in order to achieve the desired result

from sympy import *

expr=log(5, 10)**2 + log(5, 10)*log(2, 10) + log(2, 10)
print(simplify(simplify(expr)))

**Comment by oscarbenjamin** [comment]
> You need to simplify the expression twice

In general `simplify` should ideally be idempotent so that should not be necessary. It does show that somewhere `simplify` has the capability to do this though...

**Comment by smichr** [comment]
```
>>> expand(expr,log=True,factor=True).factor()
1
```
Does `expand_log(expr)` in master work?

**Comment by smichr** [comment]
The `factor` flag has to be used or else the expansion of an integer argument of log will not happen.

**Comment by oscarbenjamin** [comment]
Is it not reasonable to expect that `simplify` might handle this?

**Comment by vitrun** [comment]
Hi @smichr,  what do you suggest, check if `log` is present and use `expand_log(expr,factor=1).simplify()` if necessary ?  Is it possible that `simplify` handle this internally?
