### ISSUE TITLE
Using sympy to solve ODE but getting the wrong answer

### ISSUE THREAD

**Issue by drboo** [sympy/sympy#25879]
I tried using sympy to solve a separable ODE see below:

xdy/dx = x^3 / y

============ CODE START==================

import sympy as sp

x = sp.symbols('x')
y =  sp.symbols('y', cls=sp.Function)
rhs = x*sp.diff(y(x))
lhs = x**3 / y(x)
eq = sp.Eq(rhs,  lhs)
sol = sp.dsolve(eq, ics={y(x).subs(x, 2):4}, hint='separable')
sp.pprint(sol)

============ CODE END==================

Unfortunately this gives me the wrong answer, what am I doing wrong,  solving this by hand the correct answer is:

y(x) = sqrt(2(x^3 + 16)/3)

which I've also validated using Wolfram's Mathematica see attached file 
![mathematica](https://github.com/sympy/sympy/assets/4081614/3b48a6d2-0aaa-4e29-ad4a-189f12dc0cdf)

Any assistance would be greatly appreciated.

thanks in advance.

Thanks

**Comment by oscarbenjamin** [comment]
You don't show the answer that you get but this is the answer that I get from running your code:
```python
In [7]: sol
Out[7]: 
          ___________
         ╱    3      
       ╲╱  6⋅x  + 96 
y(x) = ──────────────
             3 
```
That answer is correct because it satisfies the initial condition:
```python
In [9]: sol.subs(x, 2)
Out[9]: y(2) = 4
```
It also satisfies the differential equation:
```python
In [10]: eq
Out[10]: 
               3 
  d           x  
x⋅──(y(x)) = ────
  dx         y(x)

In [11]: eq.subs(sol.lhs, sol.rhs)
Out[11]: 
    ⎛   ___________⎞                 
    ⎜  ╱    3      ⎟           3     
  d ⎜╲╱  6⋅x  + 96 ⎟        3⋅x      
x⋅──⎜──────────────⎟ = ──────────────
  dx⎝      3       ⎠      ___________
                         ╱    3      
                       ╲╱  6⋅x  + 96 

In [12]: eq.subs(sol.lhs, sol.rhs).doit()
Out[12]: True
```
The answer given here is also equivalent to the answer that you expected:
```python
In [13]: expected = sqrt(2*(x**3 + 16)/3)

In [14]: expected
Out[14]: 
     ___________
    ╱    3      
   ╱  2⋅x    32 
  ╱   ──── + ── 
╲╱     3     3  

In [15]: sol.rhs
Out[15]: 
   ___________
  ╱    3      
╲╱  6⋅x  + 96 
──────────────
      3       

In [16]: simplify(sol.rhs - expected)
Out[16]: 0
```
Both forms can be transformed to a canonical form by factoring from under the radical:
```python
In [18]: sol.rhs.factor(deep=True)
Out[18]: 
      _________
     ╱  3      
√6⋅╲╱  x  + 16 
───────────────
       3       

In [19]: expected.factor(deep=True)
Out[19]: 
      _________
     ╱  3      
√6⋅╲╱  x  + 16 
───────────────
       3
```

**Comment by drboo** [comment]
Thanks @oscarbenjamin, I made a newbie error (very embarrassing!) by not checking the result provided by my implementation and automatically assuming that this was incorrect because of the result I obtained via Mathematica and my worked-out solution.

**Comment by oscarbenjamin** [comment]
It's easily done. Thanks for reporting!
