### ISSUE TITLE
Wrong result for a limit

### ISSUE THREAD

**Issue by ytxytx** [sympy/sympy#25885]
I tried out a calculus exercise on SymPy and surprisingly it just failed to give the right answer, rather than timed out or throw an exception.
The problem is a bit confusing for human, though. But there must be something wrong that caused this fault.

```
In [2]: x = symbols('x', real = True)
In [3]: expr = (1+1/x)**(x**2)/exp(x)
In [4]: limit(expr, x, oo)
Out[4]: 1
```

The correct answer is `exp(-1/2)`.

**Comment by smichr** [comment]
This looks like a duplicate of #24210 which was just fixed in master -- please check the result with the current master.
