### ISSUE TITLE
CeorcionError in integrate()

### ISSUE THREAD

**Issue by Arawir** [sympy/sympy#25886]
Hey,
recently I've found an odd problem with integrating exp() function. The problem appears in the newest version 1.12. Below is the code:

##################################################3
from sympy import Symbol, exp, integrate

x = Symbol('x', real=True)
y = Symbol('y', real=True)

f = (1-x)*exp(0.93709866*1j*x)
print('f(x)=',1)

F = integrate(f, (x,y,1.0))
print('F(x)=',F)
##################################################

And the output:

---------------------------------------------------------------------------
CoercionFailed                            Traceback (most recent call last)
<ipython-input-1-0aecf0fcfd0b> in <module>
      7 print('f(x)=',1)
      8 
----> 9 F = integrate(f, (x,y,1.0))
     10 print('F(x)=',F)

~/.local/lib/python3.8/site-packages/sympy/integrals/integrals.py in integrate(meijerg, conds, risch, heurisch, manual, *args, **kwargs)
   1565 
   1566     if isinstance(integral, Integral):
-> 1567         return integral.doit(**doit_flags)
   1568     else:
   1569         new_args = [a.doit(**doit_flags) if isinstance(a, Integral) else a

~/.local/lib/python3.8/site-packages/sympy/integrals/integrals.py in doit(self, **hints)
    610                     antideriv = None
    611                 else:
--> 612                     antideriv = self._eval_integral(
    613                         function, xab[0], **eval_kwargs)
    614                     if antideriv is None and meijerg is True:

~/.local/lib/python3.8/site-packages/sympy/integrals/integrals.py in _eval_integral(self, f, x, meijerg, risch, manual, heurisch, conds, final)
    953         if risch is not False:
    954             try:
--> 955                 result, i = risch_integrate(f, x, separate_integral=True,
    956                     conds=conds)
    957             except NotImplementedError:

~/.local/lib/python3.8/site-packages/sympy/integrals/risch.py in risch_integrate(f, x, extension, handle_first, separate_integral, rewrite_complex, conds)
   1827         fa, fd = fa.cancel(fd, include=True)
   1828         if case == 'exp':
-> 1829             ans, i, b = integrate_hyperexponential(fa, fd, DE, conds=conds)
   1830         elif case == 'primitive':
   1831             ans, i, b = integrate_primitive(fa, fd, DE)

~/.local/lib/python3.8/site-packages/sympy/integrals/risch.py in integrate_hyperexponential(a, d, DE, z, conds)
   1560     pp = as_poly_1t(p, DE.t, z)
   1561 
-> 1562     qa, qd, b = integrate_hyperexponential_polynomial(pp, DE, z)
   1563 
   1564     i = pp.nth(0, 0)

~/.local/lib/python3.8/site-packages/sympy/integrals/risch.py in integrate_hyperexponential_polynomial(p, DE, z)
   1512             iDta, iDtd = frac_in(iDt, DE.t, field=True)
   1513             try:
-> 1514                 va, vd = rischDE(iDta, iDtd, Poly(aa, DE.t), Poly(ad, DE.t), DE)
   1515                 va, vd = frac_in((va, vd), t1, cancel=True)
   1516             except NonElementaryIntegralException:

~/.local/lib/python3.8/site-packages/sympy/integrals/rde.py in rischDE(fa, fd, ga, gd, DE)
    796         y = C
    797     else:
--> 798         y = solve_poly_rde(B, C, m, DE)
    799 
    800     return (alpha*y + beta, hn*hs)

~/.local/lib/python3.8/site-packages/sympy/integrals/rde.py in solve_poly_rde(b, cQ, n, DE, parametric)
    683             from .prde import prde_no_cancel_b_large
    684             return prde_no_cancel_b_large(b, cQ, n, DE)
--> 685         return no_cancel_b_large(b, cQ, n, DE)
    686 
    687     elif (b.is_zero or b.degree(DE.t) < DE.d.degree(DE.t) - 1) and \

~/.local/lib/python3.8/site-packages/sympy/integrals/rde.py in no_cancel_b_large(b, c, n, DE)
    455         p = Poly(c.as_poly(DE.t).LC()/b.as_poly(DE.t).LC()*DE.t**m, DE.t,
    456             expand=False)
--> 457         q = q + p
    458         n = m - 1
    459         c = c - derivation(p, DE) - b*p

~/.local/lib/python3.8/site-packages/sympy/polys/polytools.py in wrapper(f, g)
     70         g = _sympify(g)
     71         if isinstance(g, Poly):
---> 72             return func(f, g)
     73         elif isinstance(g, Expr):
     74             try:

~/.local/lib/python3.8/site-packages/sympy/polys/polytools.py in __add__(f, g)
   4258     @_polifyit
   4259     def __add__(f, g):
-> 4260         return f.add(g)
   4261 
   4262     @_polifyit

~/.local/lib/python3.8/site-packages/sympy/polys/polytools.py in add(f, g)
   1445             return f.add_ground(g)
   1446 
-> 1447         _, per, F, G = f._unify(g)
   1448 
   1449         if hasattr(f.rep, 'add'):

~/.local/lib/python3.8/site-packages/sympy/polys/polytools.py in _unify(f, g)
    492                 F = DMP(dict(list(zip(f_monoms, f_coeffs))), dom, lev)
    493             else:
--> 494                 F = f.rep.convert(dom)
    495 
    496             if g.gens != gens:

~/.local/lib/python3.8/site-packages/sympy/polys/polyclasses.py in convert(f, dom)
    300             return f
    301         else:
--> 302             return DMP(dmp_convert(f.rep, f.lev, f.dom, dom), dom, f.lev)
    303 
    304     def slice(f, m, n, j=0):

~/.local/lib/python3.8/site-packages/sympy/polys/densebasic.py in dmp_convert(f, u, K0, K1)
    559     """
    560     if not u:
--> 561         return dup_convert(f, K0, K1)
    562     if K0 is not None and K0 == K1:
    563         return f

~/.local/lib/python3.8/site-packages/sympy/polys/densebasic.py in dup_convert(f, K0, K1)
    536         return f
    537     else:
--> 538         return dup_strip([ K1.convert(c, K0) for c in f ])
    539 
    540 

~/.local/lib/python3.8/site-packages/sympy/polys/densebasic.py in <listcomp>(.0)
    536         return f
    537     else:
--> 538         return dup_strip([ K1.convert(c, K0) for c in f ])
    539 
    540 

~/.local/lib/python3.8/site-packages/sympy/polys/domains/domain.py in convert(self, element, base)
    407             if _not_a_coeff(element):
    408                 raise CoercionFailed('%s is not in any domain' % element)
--> 409             return self.convert_from(element, base)
    410 
    411         if self.of_type(element):

~/.local/lib/python3.8/site-packages/sympy/polys/domains/domain.py in convert_from(self, element, base)
    399                 return result
    400 
--> 401         raise CoercionFailed("Cannot convert %s of type %s from %s to %s" % (element, type(element), base, self))
    402 
    403     def convert(self, element, base=None):

CoercionFailed: Cannot convert (0.0 + 1.06712349796765j) of type <class 'sympy.polys.domains.mpelements.ComplexElement'> from CC to EX

**Comment by oscarbenjamin** [comment]
Thanks for reporting. I have opened gh-25889 to fix this.
