### ISSUE TITLE
matrices

### ISSUE THREAD

**Issue by ghost** [sympy/sympy#25894]

**Comment by oscarbenjamin** [comment]
Please format code using markdown backticks rather than sending screenshots.

Can you explain what it is that seems incorrect and what you expected to see?

The result shown for `M*N` is correct for matrix multiplication:
https://en.wikipedia.org/wiki/Matrix_multiplication

**Comment by smichr** [comment]
M-N is subtraction, not multiplication. Try M*-N. Also M*N is not element-wise multiplication. But if you want that, it is there:
```python
>>> a
Matrix([
[-1, -1],
[-2,  3]])
>>> b
Matrix([
[-3, -2],
[ 3,  3]])
>>> a.multiply_elementwise(b)
Matrix([
[ 3, 2],
[-6, 9]])
```
This can be closed.
