### ISSUE TITLE
Weird evaluation of `tan(x)**(-1.0)**2`

### ISSUE THREAD

**Issue by oscargus** [sympy/sympy#25908]
I am not sure it is caused by this. Entering `tan(x)**(-1.0)**2` gives `tan(x)**(1.0)`

_Originally posted by @oscargus in https://github.com/sympy/sympy/issues/22993#issuecomment-1814381621_

**Comment by oscarbenjamin** [comment]
This is correct and is just how Python evaluation works:
```python
In [1]: 2**3**4
Out[1]: 2417851639229258349412352

In [2]: (2**3)**4
Out[2]: 4096

In [3]: 2**(3**4)
Out[3]: 2417851639229258349412352
```

**Comment by oscargus** [comment]
Yes, I see that. However, it causes problems as mentioned in #22993. But I think that it can be solved by returning unevaluated results from the rewrites (although this is probably an issue in quite a lot of locations where the rewrite returns a reciprocal or another power so one may consider if it can be changed elsewhere).
