### ISSUE TITLE
False equality test for vectors

### ISSUE THREAD

**Issue by ytxytx** [sympy/sympy#25915]
This expression `(sqrt(6)+sqrt(2))/sqrt(sqrt(3)+2)` exactly equals `2`. While `simplify()` doesn't simplify it due to implementation reasons, `radsimp()` works to prove it right. But when multiplied with a vector, equatily test results false.

using sympy ver 1.11.1

```
In [3]: from sympy.vector import CoordSys3D
In [4]: from sympy.vector import Vector
In [5]: Q = CoordSys3D('Q')
In [6]: A = (sqrt(2) + sqrt(6))/(sqrt(sqrt(3) + 2))
In [7]: A.simplify()
Out[7]:
 √2 + √6
──────────
  ________
╲╱ √3 + 2
In [8]: A.radsimp()
Out[8]: 2
In [9]: A.equals(2)
Out[9]: True
In [10]: (A*Q.i).equals(2*Q.i)
Out[10]: False
```

**Comment by ytxytx** [comment]
I just looked over the documentation and found out that equals() is a basically a numerical method, and the more recommended way to determine whether two expressions are equal is to simplify() on the difference. I examined the code for equals() and found that it did not seem to support special handling of mathematical objects such as vectors. Is this a defect that needs to be improved? I would love to make some contributions to sympy, but have no experience involved in projects.

**Comment by oscarbenjamin** [comment]
When you call `.equals` it will try to use simplify. I don't know why that fails when there are vectors involved.

**Comment by ytxytx** [comment]
sympy/core/expr.py .equals
```python
   730          diff = factor_terms(simplify(self - other), radical=True)
   731
   732          if not diff:
   733              return True
```
It uses `not diff` to check zero, but `VectorZero` can't be checked this way actually.
`equals()` seems not adapted for vectors right now. I'm not sure if modification should be made on this `equals()` method or there should be method specified for vectors elsewhere.
Another thing is that the `is_number` assumption for vectors is `True`, is this intended?

**Comment by oscarbenjamin** [comment]
Okay, well that explains the bug. It is not clear actually what should be the best test for something being "zero" in this context. There is `is_zero` but that is only for the number zero and not vectors. There is also e.g. `is_zero_matrix` for matrices. We wouldn't want to check here for `is_zero or is_zero_matrix or is_...`.

It might make sense to define a Vector.equals method that would extract the scalar components and call `.equals` with them. That could also be used to convert between different coordinate systems as part of the `.equals` check.

More generally it would be useful if there was a generic way to turn an object into a list of scalar equations for things like this. The e.g. `solve` could work with vectors. Then the code in the general `.equals` method could convert a matrix or vector etc into scalar equations.

> Another thing is that the `is_number` assumption for vectors is `True`, is this intended?

It should be False. The definition of `is_number` is that something can be evaluated to a complex number with `.evalf` but that is not true for vectors.

**Comment by MohitKumar020291** [comment]
Hello, here is a [PR](https://github.com/sympy/sympy/pull/25932#issuecomment-1827506011) I opened.
