### ISSUE TITLE
`cycle_length` documentation / behaviour mismatch

### ISSUE THREAD

**Issue by coreycerovsek** [sympy/sympy#25922]
Documentation reads

> The sequence is started with value `x0`

but the examples (including in the docstring for `pollard_rho`), implementation, and tests all use the sequence

$f(x_0), f(f(x_0)), \dots$

I think either the documentation should read "The sequence is started with value `f(x0)`", or the examples, implementation, and tests should be tweaked to match the behaviour of Brent's method as described in the cited Wikipedia article. Personally I'm inclined to the latter, as the hack to adjust `mu` at the end of `cycle_length` is a bit unlovely, and I was expecting consistency with the article, but that would change the way the method has behaved since a decade. Also, I'd be happy to create a PR, but I'm new to contributing, so thought I'd ask which fix is preferred!

**Comment by haru-44** [comment]
I think we can change the behavior.

**Comment by coreycerovsek** [comment]
Great! I've created pull request #25923.
