### ISSUE TITLE
Inaccurate singular value decomposition

### ISSUE THREAD

**Issue by suriyachaudary** [sympy/sympy#25925]
SymPy [singular_value_decomposition()](https://docs.sympy.org/latest/modules/matrices/matrices.html#sympy.matrices.matrices.MatrixBase.singular_value_decomposition) seems inaccurate compared to SciPy [linalg.svd()](https://docs.scipy.org/doc/scipy/reference/generated/scipy.linalg.svd.html#scipy-linalg-svd).

```python
import numpy as np
import scipy
import sympy
print('SciPy')
A = np.random.random((100,100))
U, S, Vh = scipy.linalg.svd(A)
for k in range(Vh.shape[0]):
    A_ = U[:, :k]@np.diag(S)[:k, :k]@Vh[:k, :]
    print(k, scipy.linalg.norm(A-A_, 'fro'))

print('SymPy')
A_sympy = sympy.Matrix(A)
print("(A-A_sympy).norm('fro') = ", (A-A_sympy).norm('fro'))
U_sympy, S_sympy, V_sympy = A_sympy.singular_value_decomposition()
for k in range(V_sympy.shape[1]):
    A_sympy_svd = U_sympy[:, :k]@S_sympy[:k, :k]@V_sympy.H[:k, :]
    print(k, (A_sympy_svd-A_sympy).norm('fro'))
```

Outputs

SciPy
0 58.00721433853012
1 28.712051855450245
2 28.156995234391182
3 27.64712332505014
4 27.151409422344546
5 26.660613933044075
6 26.17137920398219
7 25.683510156500628
8 25.187147206792957
9 24.703221140684185
10 24.231468410934237
11 23.768066166062944
12 23.323228284857972
13 22.882664345688454
14 22.446108966806765
15 22.003713313676787
16 21.578339511953285
17 21.14783866778032
18 20.710208133438833
19 20.28295224837908
20 19.86793893437183
21 19.458872866406693
22 19.063627496905188
23 18.667791984133792
24 18.27120910955213
25 17.88642355556194
26 17.50046962653396
27 17.11764362998228
28 16.7398337867373
29 16.356539655233288
30 15.983569772403083
31 15.615879914216471
32 15.25844739249264
33 14.901665295023713
34 14.549307043654538
35 14.190561534872234
36 13.844400939813607
37 13.502660745638737
38 13.166496687016174
39 12.828145173278944
40 12.497500263234892
41 12.170936927189084
42 11.848842243945873
43 11.532319706423632
44 11.214945523911343
45 10.897622364542682
46 10.585499030320205
47 10.286520539274099
48 9.983643500148949
49 9.687083293607797
50 9.388096864533518
51 9.093950027018124
52 8.802038927811713
53 8.511741058135447
54 8.218394923173483
55 7.93989315341009
56 7.665980862350097
57 7.403867074025123
58 7.1441601326310025
59 6.877131045612154
60 6.635377299777032
61 6.392273259704447
62 6.163240716105294
63 5.931110945313491
64 5.696916156081331
65 5.461899260009739
66 5.229609532403313
67 4.997052416279001
68 4.757359591144843
69 4.529914637042529
70 4.305458775233967
71 4.0932005776464075
72 3.873517683430584
73 3.6447482711469092
74 3.430066924075327
75 3.240042083337338
76 3.0514850755052763
77 2.8619330233205202
78 2.6802605237221475
79 2.515122676442693
80 2.3423888300327507
81 2.1799704797279684
82 2.008712222261469
83 1.8544316659682816
84 1.6986307383958406
85 1.5456682255507292
86 1.390657595267397
87 1.2487489243808023
88 1.1025616864172403
89 0.9588195216748879
90 0.8089459998361415
91 0.6640397806911598
92 0.5457719018055007
93 0.4378811109931007
94 0.3236875122642835
95 0.2115092886084592
96 0.15221373366561325
97 0.09464749777708063
98 0.0483484489786657
99 0.00985072408046962
SymPy
(A-A_sympy).norm('fro') =  0
0 58.0072143385301
1 28.7120518554503
2 28.1569952343911
3 27.6471233250501
4 27.1514094223446
5 26.6606139330441
6 26.1713792039822
7 25.6835101565006
8 25.1871472067930
9 24.7032211406842
10 24.2314684109343
11 23.7680661660629
12 23.3232282848580
13 22.8826643456884
14 22.4488734549900
15 22.0037133136768
16 21.5783395119533
17 21.1478386677803
18 20.7102081334389
19 20.2829522483791
20 19.8679389343718
21 19.4588728664067
22 19.0636274969051
23 18.6677919841338
24 18.2712091095522
25 17.8864235555620
26 17.5004696265340
27 17.1176436299823
28 16.7398337867373
29 16.3565396552333
30 15.9835697724031
31 15.6158799142165
32 15.2584473924927
33 14.9016652950237
34 14.5493070436545
35 14.1905615348722
36 14.1905581158118
37 14.1904791709962
38 14.1902458937877
39 14.1897451581866
40 14.1889851820286
41 14.1868693893120
42 14.1838040316281
43 14.1800624013505
44 14.1750163260807
45 14.1674854171213
46 14.1581320024871
47 14.1476639203312
48 14.1355107017346
49 14.1222557733430
50 14.1061315182979
51 14.0885304517388
52 14.0688705968621
53 14.0476728280215
54 14.0215048316704
55 13.9959012301435
56 13.9652173934553
57 13.9351440681455
58 13.8989703231939
59 13.8585885107021
60 13.8157216233246
61 13.7697740566561
62 13.7145122667548
63 13.6516628082862
64 13.5874112952450
65 13.5216515784780
66 13.4481192014387
67 13.3693517567434
68 13.2816227857877
69 13.1917861115768
70 13.0973162574819
71 12.9968143398902
72 12.8916236227008
73 12.7822729023573
74 12.6692888217241
75 12.5436758872589
76 12.4127799165405
77 12.2610363621646
78 12.1059815391055
79 11.9417240837778
80 11.7613831409161
81 11.5684926227124
82 11.3543956613395
83 11.1308646289623
84 10.8936729150958
85 10.6412252084585
86 10.3697856264100
87 10.0845872070665
88 9.77545558376117
89 9.45088604068873
90 9.08921687907240
91 8.69465546014886
92 8.26907726798030
93 7.80877545797541
94 7.16047308914680
95 6.59816123603363
96 5.84723366440903
97 5.11217511263621
98 4.21432540569586
99 2.96569155889282

**Comment by sylee957** [comment]
`mpmath` has its own singular value decomposition to dispatch for pure float matrix
https://mpmath.org/doc/current/matrices.html#the-singular-value-decomposition
if numeric error is an issue

**Comment by suriyachaudary** [comment]
@sylee957 `mpmath` [svd_r()](https://mpmath.org/doc/current/matrices.html#the-singular-value-decomposition) seem as accurate compared to Numpy [linalg.svd()](https://numpy.org/doc/stable/reference/generated/numpy.linalg.svd.html#numpy-linalg-svd).

```python

import numpy as np
import scipy
import sympy
import mpmath
print('Numpy')
A = np.random.random((100,100))
U, S, Vh = scipy.linalg.svd(A)
for k in range(Vh.shape[0]):
    A_ = U[:, :k]@np.diag(S)[:k, :k]@Vh[:k, :]
    print(k, scipy.linalg.norm(A-A_, 'fro'))

print('Sympy')
A_sympy = sympy.Matrix(A)
print("(A-A_sympy).norm('fro') = ", (A-A_sympy).norm('fro'))
U_sympy, S_sympy, V_sympy = A_sympy.singular_value_decomposition()
for k in range(V_sympy.shape[1]):
    A_sympy_svd = U_sympy[:, :k]@S_sympy[:k, :k]@V_sympy.H[:k, :]
    print(k, (A_sympy_svd-A_sympy).norm('fro'))

print('mpmath')
A_mp = mpmath.matrix(A.tolist())
U_mp, S_mp, V_mp = mpmath.svd_r(A_mp)
for k in range(V_mp.cols):
    A_mp_svd = U_mp[:, :k]@mpmath.diag(S_mp)[:k, :k]@V_mp.H.transpose()[:k, :]
    print(k, mpmath.mnorm(A_mp-A_mp_svd, 'f'))
```

Outputs

Numpy
0 57.548895934813004
1 28.65072119325715
2 28.0941262527906
3 27.561591148577467
4 27.042244046758363
5 26.528486405492124
6 26.015566320846936
7 25.533363344223677
8 25.045952342623185
9 24.584057497690903
10 24.1192792973871
11 23.671446171120927
12 23.226480548024327
13 22.782694439391168
14 22.337822913688555
15 21.896549176483823
16 21.46984431130971
17 21.039767226721416
18 20.609536350968828
19 20.185783133252674
20 19.774768543734826
21 19.36658844363796
22 18.9637696833307
23 18.556581581660925
24 18.15090440159481
25 17.757194422755894
26 17.35849796181747
27 16.974314844094415
28 16.588043036826186
29 16.214039609687493
30 15.84398667240996
31 15.47647556674993
32 15.108632674259493
33 14.745627577577174
34 14.38860032373299
35 14.03724545724466
36 13.710375709343671
37 13.386195896771262
38 13.059345847410722
39 12.72895413672989
40 12.410699437245073
41 12.090920990747026
42 11.771760051523627
43 11.451485306562084
44 11.130767097628846
45 10.810001499348555
46 10.491749684165653
47 10.189774937637546
48 9.888326668346613
49 9.595291484912234
50 9.306153051144372
51 9.009035229101487
52 8.725362244484549
53 8.445740365278759
54 8.17225487252759
55 7.898356089240868
56 7.626174545233015
57 7.357908858989325
58 7.0886148006753436
59 6.834750229171064
60 6.588877816928939
61 6.348088488681122
62 6.102551424206429
63 5.860068932189406
64 5.619112857435561
65 5.378600032120473
66 5.135418326173467
67 4.89332477484851
68 4.658615603726126
69 4.43391190020514
70 4.213684823579629
71 4.002550800700149
72 3.784691301075305
73 3.5643083844553978
74 3.3399847113123795
75 3.143642058654498
76 2.957435027265369
77 2.7640930760553433
78 2.5792368458849575
79 2.3959435238052706
80 2.2031501638836577
81 2.0077751309318597
82 1.8461915497884815
83 1.6925611926770183
84 1.5395470667188196
85 1.3896033815697615
86 1.2356483602888593
87 1.0770865962734704
88 0.9227533737428973
89 0.7763529521015717
90 0.6385559296153138
91 0.5393861635052567
92 0.4468914868852022
93 0.35530426619760935
94 0.2549645533296689
95 0.1818292025453047
96 0.10577350548383319
97 0.07780371059350022
98 0.04749966320654093
99 0.027961931704810067
Sympy
(A-A_sympy).norm('fro') =  0
0 57.5488959348131
1 28.6507211932572
2 28.0941262527906
3 27.5615911485775
4 27.0422440467584
5 26.5284864054921
6 26.0155663208470
7 25.5373603975664
8 25.0459523426231
9 24.5840574976909
10 24.1192792973871
11 23.6714461711209
12 23.2264805480243
13 22.7826944393911
14 22.3378229136885
15 21.8965491764838
16 21.4698443113097
17 21.0397672267214
18 20.6095363509689
19 20.1857831332527
20 19.7747685437349
21 19.3665884436380
22 18.9637696833307
23 18.5565815816609
24 18.1509044015948
25 17.7571944227559
26 17.3584979618175
27 16.9743148440944
28 16.5880430368262
29 16.2140396096875
30 15.8439866724099
31 15.4764755667500
32 15.1086326742595
33 14.7456275775772
34 14.3886003237330
35 14.0372454572447
36 14.0372176073933
37 14.0371650916035
38 14.0370298357435
39 14.0368469391268
40 14.0360677601684
41 14.0349297505716
42 14.0327480881457
43 14.0301300074478
44 14.0268785762747
45 14.0227139438730
46 14.0157602762283
47 14.0068835305425
48 13.9958616916238
49 13.9827548486216
50 13.9682949019867
51 13.9525644544755
52 13.9348303411265
53 13.9153094391905
54 13.8929154265959
55 13.8632748433519
56 13.8312586071431
57 13.7982534155511
58 13.7624143773481
59 13.7221659400563
60 13.6807081188802
61 13.6341029098043
62 13.5771854877010
63 13.5174099509669
64 13.4530905334879
65 13.3898887312207
66 13.3185842073456
67 13.2416600425949
68 13.1567333588087
69 13.0641394145247
70 12.9659138405825
71 12.8635077145519
72 12.7555420165873
73 12.6413261227552
74 12.5198255805267
75 12.3947952439932
76 12.2609318296687
77 12.1159316701020
78 11.9543062220165
79 11.7849786521901
80 11.6043195024304
81 11.4130850485478
82 11.2122134170393
83 10.9960135380718
84 10.7648290403398
85 10.5079213072157
86 10.2457133156509
87 9.96319505615546
88 9.65467486491544
89 9.32563395119849
90 8.82596117463538
91 8.31344869182131
92 7.77622675383722
93 7.20759751788229
94 6.72087352946439
95 6.17513540202287
96 5.54025976368220
97 4.84272017613299
98 3.97943501146655
99 2.82857082169384
mpmath
0 57.548895934813
1 28.6507211932572
2 28.0941262527906
3 27.5615911485775
4 27.0422440467584
5 26.5284864054921
6 26.0155663208469
7 25.5333633442237
8 25.0459523426232
9 24.5840574976909
10 24.1192792973871
11 23.6714461711209
12 23.2264805480243
13 22.7826944393912
14 22.3378229136886
15 21.8965491764838
16 21.4698443113097
17 21.0397672267214
18 20.6095363509688
19 20.1857831332527
20 19.7747685437348
21 19.366588443638
22 18.9637696833307
23 18.5565815816609
24 18.1509044015948
25 17.7571944227559
26 17.3584979618175
27 16.9743148440944
28 16.5880430368262
29 16.2140396096875
30 15.84398667241
31 15.4764755667499
32 15.1086326742595
33 14.7456275775772
34 14.388600323733
35 14.0372454572447
36 13.7103757093437
37 13.3861958967713
38 13.0593458474107
39 12.7289541367299
40 12.4106994372451
41 12.090920990747
42 11.7717600515236
43 11.4514853065621
44 11.1307670976288
45 10.8100014993486
46 10.4917496841657
47 10.1897749376375
48 9.88832666834661
49 9.59529148491223
50 9.30615305114437
51 9.00903522910149
52 8.72536224448455
53 8.44574036527876
54 8.17225487252759
55 7.89835608924087
56 7.62617454523301
57 7.35790885898932
58 7.08861480067534
59 6.83475022917106
60 6.58887781692894
61 6.34808848868112
62 6.10255142420643
63 5.86006893218941
64 5.61911285743556
65 5.37860003212047
66 5.13541832617347
67 4.89332477484851
68 4.65861560372613
69 4.43391190020514
70 4.21368482357963
71 4.00255080070015
72 3.7846913010753
73 3.5643083844554
74 3.33998471131238
75 3.1436420586545
76 2.95743502726537
77 2.76409307605534
78 2.57923684588496
79 2.39594352380527
80 2.20315016388366
81 2.00777513093186
82 1.84619154978848
83 1.69256119267702
84 1.53954706671882
85 1.38960338156976
86 1.23564836028886
87 1.07708659627347
88 0.922753373742897
89 0.776352952101572
90 0.638555929615313
91 0.539386163505256
92 0.446891486885202
93 0.355304266197609
94 0.254964553329669
95 0.181829202545305
96 0.105773505483833
97 0.0778037105935
98 0.0474996632065407
99 0.0279619317048095

**Comment by oscarbenjamin** [comment]
For a matrix of floats SymPy should use the mpmath routine.

Otherwise I am not sure what all of these numbers are really supposed to be showing. Is this not the expected result:
```python
In [13]: A = np.random.random((10,10))

In [14]: A_sympy = sympy.Matrix(A)

In [15]: %time U, S, Vh = A_sympy.singular_value_decomposition()
CPU times: user 646 ms, sys: 32 µs, total: 646 ms
Wall time: 645 ms

In [16]: (U*S*Vh.H - A_sympy).norm()
Out[16]: 1.49326947557154e-15
```

**Comment by suriyachaudary** [comment]
@oscarbenjamin 

$$A_{m\times n} = U_{m\times n}S_{n\times n}V_{n\times n}^T$$

These numbers are $\forall k \in \left[1, n\right]$  

$$\lVert A - \sum_{i=1}^{i=k} U_i S_i V_i^T \rVert_F$$

**Comment by suriyachaudary** [comment]
Changed ```for k in range(0, Vh.shape[0])```
 to ```for k in range(1, Vh.shape[0] + 1)```

```python
import numpy as np
import scipy
import sympy
import mpmath

np.random.seed(1)
A = np.random.random((100,100))

print('SciPy')
U, S, Vh = scipy.linalg.svd(A)
for k in range(1, Vh.shape[0]+1):
    A_ = U[:, :k]@np.diag(S)[:k, :k]@Vh[:k, :]
    print(k, scipy.linalg.norm(A-A_, 'fro'))

print('SymPy')
A_sympy = sympy.Matrix(A)
print("(A-A_sympy).norm('fro') = ", (A-A_sympy).norm('fro'))
U_sympy, S_sympy, V_sympy = A_sympy.singular_value_decomposition()
for k in range(1, V_sympy.shape[1]+1):
    A_sympy_svd = U_sympy[:, :k]@S_sympy[:k, :k]@V_sympy.H[:k, :]
    print(k, (A_sympy_svd-A_sympy).norm('fro'))

print('mpmath')
A_mp = mpmath.matrix(A.tolist())
U_mp, S_mp, V_mp = mpmath.svd_r(A_mp)
for k in range(1, V_mp.cols+1):
    A_mp_svd = U_mp[:, :k]@mpmath.diag(S_mp)[:k, :k]@V_mp.H.transpose()[:k, :]
    print(k, mpmath.mnorm(A_mp-A_mp_svd, 'f'))
```

Outputs

SciPy
1 28.430666059234916
2 27.893998943483663
3 27.38151409191446
4 26.86391433755221
5 26.36265080609842
6 25.864620498442957
7 25.372583843285312
8 24.88753690128461
9 24.398846894333747
10 23.932009345805902
11 23.47929022618035
12 23.023926558956543
13 22.57952490569608
14 22.13637186224638
15 21.710162240100743
16 21.279871814399787
17 20.849606052218796
18 20.428073267645193
19 20.021961226062167
20 19.612799586685473
21 19.205104719627386
22 18.80297364449492
23 18.400746367116206
24 18.005231773991827
25 17.61670281529501
26 17.234236519218832
27 16.85281602199009
28 16.468376321345843
29 16.09493091484479
30 15.739677868046096
31 15.38218527630944
32 15.028264628275776
33 14.67307160015606
34 14.317336188571765
35 13.970313650402721
36 13.623888867938566
37 13.29571322372928
38 12.963198885182425
39 12.629474087540759
40 12.308738823192089
41 11.979706244066556
42 11.668035994024248
43 11.362240608251266
44 11.068592966448856
45 10.777877708928562
46 10.482579538275552
47 10.188376145305051
48 9.897769052411434
49 9.610079548045006
50 9.316658449345333
51 9.017860243272743
52 8.73458727753384
53 8.455890756433766
54 8.177361861582645
55 7.9065665677971175
56 7.644110915006991
57 7.389934282138123
58 7.136878799774938
59 6.880735923534271
60 6.628229873254711
61 6.375330751019284
62 6.127088004184262
63 5.876649841008913
64 5.638753599489787
65 5.399957257665227
66 5.166733737306744
67 4.929680487113898
68 4.704981292533935
69 4.483700757678324
70 4.268217247382129
71 4.050045329968172
72 3.8410443985705043
73 3.6334545129311806
74 3.4172721102817407
75 3.2177223301594307
76 3.0247322929438973
77 2.8243915872816974
78 2.6281383886261276
79 2.452629247169676
80 2.270076523204074
81 2.105200260187865
82 1.941764905071204
83 1.7746200349936838
84 1.6120038347602939
85 1.4637215482406243
86 1.318105389240639
87 1.1728095911871539
88 1.0331413158964413
89 0.8913079220752657
90 0.7505335327854612
91 0.6305595078555789
92 0.5031832899445
93 0.3783677522227951
94 0.30043851796317195
95 0.21188246385713372
96 0.1393518752976365
97 0.09775044023901437
98 0.06447448151272754
99 0.03627850992296259
100 7.665734300978016e-14
SymPy
(A-A_sympy).norm('fro') =  0
1 28.4306660592349
2 27.8939989434837
3 27.3815140919145
4 26.8639143375522
5 26.3626508060984
6 25.8646204984430
7 25.3725838432853
8 24.8875369012846
9 24.3988468943338
10 23.9320093458059
11 23.4792902261803
12 23.0239265589566
13 22.5795249056961
14 22.1363718622464
15 21.7101622401007
16 21.2798718143998
17 20.8496060522188
18 20.4280732676452
19 20.0219612260622
20 19.6127995866855
21 19.2051047196274
22 18.8029736444949
23 18.4007463671162
24 18.0052317739919
25 17.6167028152950
26 17.2342365192189
27 16.8528160219901
28 16.4683763213459
29 16.0949309148448
30 15.7396778680461
31 15.3821852763095
32 15.0282646282758
33 14.6730716001561
34 14.3173361885718
35 14.3172902256783
36 14.3171910156224
37 14.3170024931206
38 14.3166580105637
39 14.3157682769070
40 14.3139205847053
41 14.3123357066785
42 14.3084912591547
43 14.3034439993884
44 14.2976506794911
45 14.2895656240710
46 14.2800117142100
47 14.2692197824340
48 14.2565323174831
49 14.2423184477038
50 14.2262981542390
51 14.2069292694792
52 14.1850507433009
53 14.1617176712817
54 14.1362253842879
55 14.1056983277155
56 14.0740542896074
57 14.0359868800978
58 13.9941812941168
59 13.9510708744017
60 13.9035379260416
61 13.8486145097279
62 13.7924795981287
63 13.7325616096120
64 13.6663249290267
65 13.5971520198967
66 13.5221768430047
67 13.4418884771283
68 13.3525644737018
69 13.2599614310138
70 13.1601889568816
71 13.0556923287414
72 12.9400505457115
73 12.8195660360129
74 12.6906534222585
75 12.5555401591159
76 12.4117314075801
77 12.2627479319387
78 12.1059358934226
79 11.9361769694312
80 11.7523133263762
81 11.5535287705464
82 11.3442981549204
83 11.1204456821383
84 10.8713380443637
85 10.6100795274922
86 10.3450608176904
87 10.0589814125669
88 9.75200706318004
89 9.42462029091714
90 9.08142969359262
91 8.71123434978031
92 8.29717129983113
93 7.84045622667836
94 7.18723185910272
95 6.48821903081372
96 5.83997401264631
97 5.10947474385351
98 4.15600461979847
99 2.92248346598083
100 4.29453404380655e-14
mpmath
1 28.4306660592349
2 27.8939989434837
3 27.3815140919145
4 26.8639143375522
5 26.3626508060984
6 25.864620498443
7 25.3725838432853
8 24.8875369012846
9 24.3988468943337
10 23.9320093458059
11 23.4792902261803
12 23.0239265589565
13 22.5795249056961
14 22.1363718622464
15 21.7101622401007
16 21.2798718143998
17 20.8496060522188
18 20.4280732676452
19 20.0219612260622
20 19.6127995866855
21 19.2051047196274
22 18.8029736444949
23 18.4007463671162
24 18.0052317739918
25 17.616702815295
26 17.2342365192188
27 16.8528160219901
28 16.4683763213458
29 16.0949309148448
30 15.7396778680461
31 15.3821852763094
32 15.0282646282758
33 14.6730716001561
34 14.3173361885718
35 13.9703136504027
36 13.6238888679386
37 13.2957132237293
38 12.9631988851824
39 12.6294740875408
40 12.3087388231921
41 11.9797062440666
42 11.6680359940242
43 11.3622406082513
44 11.0685929664489
45 10.7778777089286
46 10.4825795382755
47 10.1883761453051
48 9.89776905241143
49 9.61007954804501
50 9.31665844934533
51 9.01786024327274
52 8.73458727753384
53 8.45589075643377
54 8.17736186158264
55 7.90656656779712
56 7.64411091500699
57 7.38993428213812
58 7.13687879977494
59 6.88073592353427
60 6.62822987325471
61 6.37533075101928
62 6.12708800418426
63 5.87664984100891
64 5.63875359948979
65 5.39995725766523
66 5.16673373730674
67 4.9296804871139
68 4.70498129253394
69 4.48370075767833
70 4.26821724738213
71 4.05004532996817
72 3.8410443985705
73 3.63345451293118
74 3.41727211028174
75 3.21772233015943
76 3.0247322929439
77 2.8243915872817
78 2.62813838862613
79 2.45262924716968
80 2.27007652320407
81 2.10520026018787
82 1.9417649050712
83 1.77462003499368
84 1.61200383476029
85 1.46372154824062
86 1.31810538924064
87 1.17280959118715
88 1.03314131589644
89 0.891307922075266
90 0.750533532785462
91 0.630559507855579
92 0.5031832899445
93 0.378367752222795
94 0.300438517963172
95 0.211882463857134
96 0.139351875297636
97 0.0977504402390144
98 0.0644744815127276
99 0.036278509922963
100 1.1037478760242e-13

**Comment by sylee957** [comment]
What is your theory for the expected error bound to fall in?
Have you tried
https://stats.stackexchange.com/questions/211686/why-does-the-reconstruction-error-of-truncated-svd-equal-the-sum-of-squared-sing

**Comment by Krushna1979** [comment]
i solve your problem.

**Comment by oscarbenjamin** [comment]
The outputs for SymPy and SciPy look similar in https://github.com/sympy/sympy/issues/25925#issuecomment-1830466635. I don't know if that is supposed to mean that there is not an issue here.

In any case without more explanation it is not useful to keep this issue open because the description of the problem is unclear.
