### ISSUE TITLE
Relational.canonical is not particularly canonical

### ISSUE THREAD

**Issue by lezcano** [sympy/sympy#25924]
```python
>>> from sympy.abc import x,y,z
>>> (x <= -y + z).canonical
x <= -y + z
>>> ((x + y) <= z).canonical
z >= x + y
```

**Comment by oscarbenjamin** [comment]
You can subtract the sides if you want but otherwise I think it is reasonable that canonical does not move terms from one side to the other.

**Comment by smichr** [comment]
From the docstring:
```
Return a canonical form of the relational by putting a
number on the rhs, canonically removing a sign or else
ordering the args canonically. No other simplification is
attempted.
```
Perhaps more canonical would be an expression in which the lowest ordered symbol with a numerical coefficient is put on the let would be more what you are looking for:
```
>>> def more_canonical(r):
...     args = [a.as_coeff_Mul()[::-1] for a in Add.make_args(r.lhs - r.rhs)]
...     for a in ordered(args):
...         if a[1].is_number and a[1].is_zero is False:
...             r = r.func(a[0], (sum([prod(i) for i in args]) - prod(a))/a[1])
...             break
...     return r.canonical
...
>>> more_canonical(x <= -y + z)
x <= y - z
>>> more_canonical((x + y) <= z)
x <= y - z
```

**Comment by lezcano** [comment]
Yeah, I ended up implementing my `more_canonical` at https://github.com/pytorch/pytorch/pull/114509. Closing as expected

**Comment by oscarbenjamin** [comment]
I think that it could be reasonable to add something like this to SymPy but we just need to define clearly what the goal is and it should be a different method from the existing canonical method that behaves as intended.
