### ISSUE TITLE
Extra space added to equations obtained with diff

### ISSUE THREAD

**Issue by damianoazzolini** [sympy/sympy#25937]
The result of the diff function has some extra white spaces between the characters (sympy version 1.12).
Example to reproduce the issue:
```
import sympy

symbolic_variables = ["f(1,2)","f(1,3)"]
s = "(-0.9*f(1,2)*f(1,3) + 0.9*f(1,2) + 0.9*f(1,3)) - 0.7"

for symbolic_var in symbolic_variables:
    d = diff(s,symbolic_var)
    print(f"diff {s}:")
    print(str(d))
```
output
```
diff (-0.9*f(1,2)*f(1,3) + 0.9*f(1,2) + 0.9*f(1,3)) - 0.7:
0.9 - 0.9*f(1, 3)
# ------------^------
diff (-0.9*f(1,2)*f(1,3) + 0.9*f(1,2) + 0.9*f(1,3)) - 0.7:
0.9 - 0.9*f(1, 2)
# ------------^------
```
Note the extra spaces in f(1,3) and f(1,2). This may be a possible issue, expecially if the result of the differentiation is used in other functions.
For example, as in my case, the result of diff is treated as a string. In this string i find-replace f(1,2) and f(1,3) with numerical values and then evaluate the resulting string with python eval. However, the find-replace operation ''fails'' meaning that f(1,2) cannot be found since in the equation obtained with diff f(1,2) is replaced by f(1, 2) (with spaces).

**Comment by oscarbenjamin** [comment]
There could perhaps be a printer option for controlling spaces.

I don't think that your approach of converting the expression to a string and using string find-replace is a good reason for wanting this though. Instead you should just work with expressions:
```python
In [37]: s = "(-0.9*f(1,2)*f(1,3) + 0.9*f(1,2) + 0.9*f(1,3)) - 0.7"

In [38]: e = parse_expr(s)

In [39]: e
Out[39]: -0.9⋅f(1, 2)⋅f(1, 3) + 0.9⋅f(1, 2) + 0.9⋅f(1, 3) - 0.7

In [40]: f = Function('f')

In [41]: e.xreplace({f(1,2):3, f(1,3):4})
Out[41]: -5.20000000000000
```
Convert to strings only at the end of the operation when you are done doing symbolic manipulation.

**Comment by smichr** [comment]
This is not an error. When you sympify with autofunction you create functions from things that look like functions. If you want to treat those entities as symbols you can. I am essentially letting `e = S('f(1,2)')` in the following to demonstrate the concept:

![image](https://github.com/sympy/sympy/assets/90703/9d87d312-de16-47ba-a80b-09fc653c9d57)

@oscarbenjamin comments still apply, however. There is (probably) no need to be working with the strings for intermediate steps.

**Comment by asmeurer** [comment]
See also https://docs.sympy.org/dev/explanation/best-practices.html#avoid-string-inputs and https://docs.sympy.org/dev/explanation/best-practices.html#avoid-manipulating-expressions-as-strings
