### ISSUE TITLE
How to write Custom Functions

### ISSUE THREAD

**Issue by haru-44** [sympy/sympy#25964]
I am studying Functions, but I'm surprised to find no example functions that adhere to the [documentation](https://docs.sympy.org/latest/guides/custom-functions.html).

For example, `mobius` requires `is_integer==True`, so the following code would result in an error.

```python
from sympy import Symbol
from sympy.ntheory.residue_ntheory import mobius

n = Symbol('n')
mobius(n)
```

If the intention of the document is to be understood, should it be written as follows?

```python
class mobius(Function):
    @classmethod
    def eval(cls, n):
        if n.is_integer is False:
            raise TypeError("n should be an integer")
        if n.is_positive is False:
            raise ValueError("n should be a positive integer")
        if n.is_prime is True:
            return S.NegativeOne
        if n is S.One:
            return S.One
        if n.is_Integer is True:
            factors = factorint(n)
            if any(e > 1 for e in factors.values()):
                return S.Zero
            return S.NegativeOne if len(factors) % 2 else S.One
```

Also, since the function is only {-1,0,1}, it seems acceptable to write the following assumption

```python
class mobius(Function):
    is_integer = True
    is_prime = False
```

On the other hand, the `partition` writes

https://github.com/sympy/sympy/blob/4adf8d2417fbb5af0841aa6348bf8344901e8152/sympy/functions/combinatorial/numbers.py#L1661-L1664

This would make `n = Symbol('n'); partition(n).is_integer` seem to be `None`, which is undesirable, wouldn't it?

Next, the mobius function $\mu(n)$ uses `sympy.ntheory.factor_.primeomega` $\Omega(n)$, `sympy.ntheory.factor_.primenu` $\omega(n)$, `sympy. functions.special.tensor_functions.KroneckerDelta` $\delta_{ij}$, Liouville function $\lambda(n)$ using $\mu(n) = \delta_{\omega(n)\Omega(n)}\lambda(n)$ [[ref](https://en.wikipedia.org/wiki/M%C3%B6bius_function)]. In this case, `_eval_rewrite` could be written as follows.

```python
class mobius(Function):
    def _eval_rewrite(self, rule, args, **hints):
        if rule == KroneckerDelta:
            return KroneckerDelta(primenu(*args), primeomega(*args)) * liouville_function(*args)
```

In summary, I think it is better to write `mobius` as follows, is my understanding wrong?

```python
class mobius(Function):
    is_integer = True
    is_prime = False
    
    @classmethod
    def eval(cls, n):
        if n.is_integer is False:
            raise TypeError("n should be an integer")
        if n.is_positive is False:
            raise ValueError("n should be a positive integer")
        if n.is_prime is True:
            return S.NegativeOne
        if n is S.One:
            return S.One
        if n.is_Integer is True:
            factors = factorint(n)
            if any(e > 1 for e in factors.values()):
                return S.Zero
            return S.NegativeOne if len(factors) % 2 else S.One
        
    def _eval_rewrite(self, rule, args, **hints):
        if rule == KroneckerDelta:
            return KroneckerDelta(primenu(*args), primeomega(*args)) * liouville_function(*args)
        
    def _latex(self, printer):
        return r'\mu\left( %s \right)' % printer._print(self.args[0])
```

**Comment by haru-44** [comment]
The `divisor_sigma` evaluates to

https://github.com/sympy/sympy/blob/f5f6c98bf9ee71c9f3c5569f54d15c4d299049d7/sympy/ntheory/factor_.py#L2170-L2175

For example

```python
>>> from sympy import Symbol
>>> from sympy.ntheory.factor_ import divisor_sigma

>>> n = Symbol('n', prime=True)
>>> m = Symbol('m', prime=True)
>>> divisor_sigma(n*m)
(m**2 - 1)*(n**2 - 1)/((m - 1)*(n - 1))
```

This is the correct expression if n and m are different, but not if n and m are equal.

```python
>>> divisor_sigma(n*m).subs({n: 3, m: 5}) == divisor_sigma(15)
True
>>> divisor_sigma(n*m).subs({n: 5, m: 5}) == divisor_sigma(25)
False
```

**Comment by haru-44** [comment]
> That seems reasonable to me.

Thanks.

> Have you tried looking in `sympy.functions` rather than `sympy.ntheory`? Most Function classes are in there.

I looked in `sympy.functions.combinatorial.numbers` and saw methods named `_eval_rewrite_as_*`. Is this an old way of writing? If so, I would appreciate a note in the documentation.
I also found out that the reason I am able to convert to latex even though I don't see any function writing `_latex` is because of the `sympy.printing.latex`. Should I add functions here when I add functions in the future?
Also, I don't understand how `sympy.functions.special.error_functions.li` can compare, for example, `li(4) < 3`.

Sorry for the rambling question.

> The ntheory symbolic functions have been added more as an afterthought since previously ntheory was functions for concrete integers rather than symbolic expressions.

There are symbolic functions cluttering up `ntheory` and `functions` and I think they should be organized.

**Comment by oscarbenjamin** [comment]
> Is this an old way of writing?

At some point it was decided that looking up the method names as strings was not good so a newer way was added but many functions have not been changed.

> I am able to convert to latex even though I don't see any function writing `_latex` is because of the `sympy.printing.latex`. Should I add functions here when I add functions in the future?

Usually the printing code goes in the `sympy.printing` although I am not sure that I like the overall structure.

> I don't understand how `sympy.functions.special.error_functions.li` can compare, for example, `li(4) < 3`.

This is most likely using numerical evaluation:
```
In [11]: li(4).evalf()
Out[11]: 2.96758509503905
```
If you are not sure about something like this then you can follow through in a debugger.

**Comment by haru-44** [comment]
Thanks for the answer.

> Usually the printing code goes in the `sympy.printing` although I am not sure that I like the overall structure.

If so, I interpret `_latex` as being provided for sympy users to create their own custom functions. But `printing` is hard to read...

I would like to learn more about Function, as I don't think I understand it well enough yet.

**Comment by oscarbenjamin** [comment]
@haru-44 should this issue be kept open? Or perhaps should it be a discussion rather than an issue?

**Comment by haru-44** [comment]
I will close this issue. I will create a separate issue on the relationship between `ntheory` and `functions`. I think it will be confusing unless we have some criteria for whether a function should be in `ntheory` or `functions`. I think only purely numerical functions should be placed in `ntheory`.
