### ISSUE TITLE
solve(..., [x, y, z]) returns two variables only for under-determined system

### ISSUE THREAD

**Issue by tanvirhasanrayhan** [sympy/sympy#25985]
from sympy import symbols, Eq, solve

# Define the variables
x, y, z = symbols('x y z')

# Define the equations
equation1 = Eq(x + y - z, 170)
equation2 = Eq(y + z - x, 130)

# Solve the system of equations
solution = solve((equation1, equation2), (x, y, z))

# Print the solution
print("Solution for z:", solution[z])

**Comment by gschintgen** [comment]
Your system is underdetermined. `solve` has chosen to use `z` as free variable / parameter for the solution. What you're seeing seems to be solve's output format for this situation. Depending on your use case it may be advisable to use `set=True`:
```
In [19]: solve((equation1, equation2), (x, y, z), set=True)
Out[19]: ([x, y, z], {(z + 20, 150, z)})
```

**Comment by oscarbenjamin** [comment]
The question is whether a key like `z: z` should be included in the solution dict. You can do e.g. `solution.get(z, z)` but perhaps the key should already be in there.

Not including the keys is useful when solving a large underdetermined system:
```python
In [9]: syms = symbols('x:1000')

In [10]: eq = Eq(syms[50], syms[500])

In [11]: solve(eq, syms, dict=True)
Out[11]: [{x₅₀: x₅₀₀}]
```

**Comment by oscarbenjamin** [comment]
If there is no suggestion for what to do then I don't think it is useful to keep this issue open. If someone wants to propose a helper function or a keyword argument to solve or something then feel free to do so.
