### ISSUE TITLE
How to convince factor to factorize -- `factor(a**2 − 2*a + b**2 + 1)` does not return `(a - 1)**2 + b**2`

### ISSUE THREAD

**Issue by maelh** [sympy/sympy#25995]
How do you convince `factor` to factorize?
`factor(a**2 − 2*a + b**2 + 1)` does not return `(a - 1)**2 + b**2`

In more detail below:

Expand works as expected:
```
>>> expr = expand((a-1)**2 + b**2)
>>> expr
a**2 − 2*a + b**2 + 1
```

But factor does not work in the opposite direction:
```
>>> factor(expr)
a**2 − 2*a + b**2 + 1
```

Expected output would be:
```
(a - 1)**2 + b**2
```

However this works:
```
>>> factor(a**2 - 2*a + 1)
(a - 1)**2
```

Is there a hint you can give to SymPy to ignore `b**2` so it does factorize as expected? I tried specifying `a` as additional parameter to `factor`, but it made no difference.

**Comment by oscarbenjamin** [comment]
How would you make this well defined in general with or without a hint?

What if there are many possible factorisations e.g.:
```python
In [60]: expand((x + y)**2 + (x - y)**2)
Out[60]: 
   2      2
2⋅x  + 2⋅y 

In [61]: factor(_)
Out[61]: 
  ⎛ 2    2⎞
2⋅⎝x  + y ⎠
```
How would you define the set of all possible "factorisations" and decide which one was best?

**Comment by maelh** [comment]
I thought of simply specifying which variables I want to have factorized and which not. In this case only a, and ignoring b. All sub-expressions that have variables that were not explicitly mentioned in the additional argument would be ignored while factorizing.

Something like that:
`factor(expr, a)`

The current hack I use is to write:
`factor(expr-b**2)+b**2`

Which works but isn't really elegant.

**Comment by oscarbenjamin** [comment]
Maybe something more like a function for completing the square would be most suitable.

**Comment by maelh** [comment]
> Maybe something more like a function for completing the square would be most suitable.

Can you elaborate on what that could look like?

**Comment by oscarbenjamin** [comment]
Something like 
```
>>> expr
a**2 − 2*a + b**2 + 1
>>> complete_the_square(expr, a)
(a - 1)**2 + b**2
```
It could be more general than just squares but you have to say which variable you want to use for contracting to a power.

**Comment by oscarbenjamin** [comment]
https://en.wikipedia.org/wiki/Completing_the_square

**Comment by gschintgen** [comment]
Maybe this is sufficient for your needs:
```PythonIn [1]: var('a b')
Out[1]: (a, b)

In [2]: expr = expand((a-1)**2 + b**2); expr
Out[2]: 
 2          2    
a  - 2⋅a + b  + 1

In [3]: Add(*factor(expr.as_independent(b, as_Add=True)))
Out[3]: 
 2          2
b  + (a - 1) 
```
You might want to check out [`as_independent()`](https://docs.sympy.org/latest/modules/core.html#sympy.core.expr.Expr.as_independent).

**Comment by oscarbenjamin** [comment]
See also gh-19386. Probably this should be closed as a duplicate.
