### ISSUE TITLE
`Interval.contains()` is not equal to its own `repr()`

### ISSUE THREAD

**Issue by gschintgen** [sympy/sympy#26002]
The following is problematic for creating tests containing `ConditionSet`s with this type of condition:
```Python
In [13]: i = Interval(-1, 1).contains(sin(y)); i
Out[13]: -1 ≤ sin(y) ∧ sin(y) ≤ 1

In [14]: repr(_)
Out[14]: '(-1 <= sin(y)) & (sin(y) <= 1)'

In [15]: r = (-1 <= sin(y)) & (sin(y) <= 1); r
Out[15]: sin(y) ≥ -1 ∧ sin(y) ≤ 1

In [16]: assert i == r
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
Cell In[16], line 1
----> 1 assert i == r

AssertionError: 

```
I can work around it by wrapping my tested expression in a `simplify_logic` in order to canonicalize `Interval`'s output, but it seems to me that this should not be necessary. I.e. it should be possible to just copy the `repr()` to create the test.

**Comment by oscarbenjamin** [comment]
It is not possible to distinguish `1 < x` and `x > 1` because of the way that `__gt__` is called by `<` since `1` is not a SymPy object:
```python
In [4]: x > 1
Out[4]: x > 1

In [5]: 1 < x
Out[5]: x > 1

In [6]: x > S(1)
Out[6]: x > 1

In [7]: S(1) < x
Out[7]: 1 < x
```

**Comment by gschintgen** [comment]
Ah, I see. So instead of using `simplify_logic` it should be sufficient to use `S(1)` instead of `1`?
I think I'll close this then since it's not really a Sympy issue, but rather like `1/2` being evaluated to 0.5 by Python before it even reaches Sympy.
Thanks!
