### ISSUE TITLE
Incorrect Simplification in SymPy of Powers to Logarithms

### ISSUE THREAD

**Issue by georgepittock** [sympy/sympy#26006]
### Problem Description:

There is a further simplification that should be done when simplifying expressions in cases involving logarithmic powers. When attempting to simplify expressions like $(b^x)^\frac{\log(a)} {\log(b)}$, the expected result should be $a^x$.

### Code Snippet:
```
>>> from sympy import symbols, log, simplify, pprint
>>> a, b, x = symbols("a b x")
>>> expr = (b**x)**(log(a,b))
>>> pprint(simplify(expr), use_unicode=False)
    log(a)
    ------
    log(b)
/ x\
\b /
```

**Comment by oscarbenjamin** [comment]
You need to set some assumptions on the symbols:
```python
In [53]: a, b = symbols('a, b', positive=True)

In [54]: x = symbols('x', real=True)

In [55]: e = (b**x)**(log(a,b))

In [56]: e
Out[56]: 
 x⋅log(a)
ℯ        

In [57]: simplify(e)
Out[57]: 
 x
a 
```
(This is still not valid for `b=1`.)

Otherwise you can have:
```python
In [58]: N(expr.subs({a:2, x:2, b:-2}))
Out[58]: 1.02142647003754 - 0.306662540131076⋅ⅈ
```

**Comment by georgepittock** [comment]
I see - thank you, thanks for clarifying.
