### ISSUE TITLE
i think mod(a,b) are considering only integers solutions

### ISSUE THREAD

**Issue by joaorrmattos** [sympy/sympy#26016]
Hello guys, i have a simplification of my code which is:

```
import sympy as sp
import itertools

Zp = range(3)
Zq = range(3) 
sextetos = itertools.product(Zp, Zp, Zp, Zq, Zq, Zq)


x, y, z, w = sp.symbols('x y z w', real=True)
system = []
#it will test the generic form: B(a,b) = x*a1*b1+y*a1*b2+z*a2*b1+w*a2*b2, for all pairs a= (a1,a2), b=(b1,b2) e c=(c1,c2)
#both mapping axioms, and return the set of conditions that x, y, z e w must satisfy.

for a1, b1, c1, a2, b2, c2 in sextetos:
 d1 = (b1 + c1) % p
 d2 = (b2 + c2) % q   
 if (a1, b1, c1, a2, b2, c2) != (0, b1, c1, 0, b2, c2):
    print(a1,b1,c1,a2,b2,c2)
    eq1 = ((x * (a1 * b1+b1 * a1)+y * (a1 * b2+b1 * a2)+z * (a2*b1+b2 * a1)+w * (a2 * b2+a2 * b2))) % 2
    system.append(eq1)
    eq2 = (x * (a1 * ((b1+c1)%p))+y * (a1 * ((b2+c2)%q))+z * (a2 * ((b1+c1)%p))+w * (a2*((b2+c2)%q)) - (x * a1 * (b1+c1)+y * a1 * (b2+c2)+z * a2*(b1+c1)+w * a2 * (b2+c2))) % 2
    eq2 = (x * a1 * (sp.Mod(b1+c1,p)-(b1+c1))+y * a1 * (sp.Mod(b2+c2,q)-(b2+c2))+z * a2 * (sp.Mod(b1+c1,p)-(b1+c1))+w * a2 * (sp.Mod(b2+c2,q)-(b2+c2))) % 2
    print(eq1)
    print(eq2)
    input()
vars = [x, y, z, w]
print(sp.nonlinsolve(system, vars)) 
```

I was feeling something was a litte bit wrong with this code, because the conditionset it returns has some rules that i know that doesnt exist, like for the sexteto (a1,b1,c1,a2,b2,c2) = (0,0,0,1,1,2), eq2 should be w * 1 * (-3) % 2. Or, with sp tools: Eq(3*Mod(w,2),0), considering the possibility of w = 2/3 (example). However, the code returns me just Eq(Mod(w,2),0), and i just cant understand why...

Important that: the error is before the nonlinsolve function. If u just put a print(eq2) with the equations.append(eq2), it will return (Eq(Mod(w,2),0). 

If someone have an ideia of what is happening, please give me a hand. 

Merry Christmas, gifhubbers :D

**Comment by asmeurer** [comment]
You haven't defined what p and q are.

**Comment by joaorrmattos** [comment]
oops, sorry, it was an input, and Zp, Zq was two ranges based on p and q. I decided to send with p and q = 3 to make it more specific, but i forgot to switch all the p and q with the number 3. Sorry.

**Comment by Spinachboul** [comment]
@joaorrmattos 
I think the following code is a simplified version which removes unnecessary calculations and aligns with the length of respective changes, please have a look at it!

```
import sympy as sp
import itertools

p = 3  # Define the value of p
q = 3  # Define the value of q
Zp = range(p)
Zq = range(q)
sextetos = itertools.product(Zp, Zp, Zp, Zq, Zq, Zq)

x, y, z, w = sp.symbols('x y z w', real=True)
system = []

for a1, b1, c1, a2, b2, c2 in sextetos:
    if (a1, b1, c1, a2, b2, c2) != (0, 0, 0, 1, 1, 2):
        eq1 = ((x * (a1 * b1 + b1 * a1) + y * (a1 * b2 + b1 * a2) + z * (a2 * b1 + b2 * a1) + w * (a2 * b2 + a2 * b2))) % 2
        system.append(eq1)

        mod_val_p = sp.Mod(b1 + c1, p)
        mod_val_q = sp.Mod(b2 + c2, q)
        eq2 = (x * a1 * mod_val_p + y * a1 * mod_val_q + z * a2 * mod_val_p + w * a2 * mod_val_q - (x * a1 * (b1 + c1) + y * a1 * (b2 + c2) + z * a2 * (b1 + c1) + w * a2 * (b2 + c2))) % 2
        system.append(eq2)

vars = [x, y, z, w]
solutions = sp.nonlinsolve(system, vars)
print(solutions)
```

**Comment by joaorrmattos** [comment]
hmmm unfortunately it doesnt work. 

1: i put (a1, b1, c1, a2, b2, c2) != (0,b1,c1,0,b2,c2) because if a1 and a2 equals 0, both eq1 and eq2 goes to 0.

2: its important to analyse  (a1, b1, c1, a2, b2, c2) = (0, 0, 0, 1, 1, 2), because it shows us the problem very quick.

Ur idea was really good, but it keeps turning the equation Eq(Mod(3*w, 2,), 0) to Eq(Mod(w, 2), 0), considering the only the possibility of w to be integer. 

:/

**Comment by oscarbenjamin** [comment]
If I understand correctly then the question is why this happens:
```
In [1]: Mod(3*x, 2)
Out[1]: x mod 2

In [2]: (3*x) % 2
Out[2]: x mod 2
```
This simplification assumes that `x` is an integer which is not necessarily the case if no assumptions are set on `x`:
```
In [3]: (3*(S(2)/3)) % 2
Out[3]: 0
```

**Comment by joaorrmattos** [comment]
yes, thats correct. I have an alternative that is: keep my equations without mod app, then only %2 when i already switched the variables with the values i want to verify. The bad thing is: it takes more time than it would with Mod(a,b)... Thats why i asked for a solution... If there is nothing to do with it, ie, the simplification will assume that x is intenger everytime when it is a variable, i accept it ahahaha. Thanks for the explanation! Happy new year!

**Comment by oscarbenjamin** [comment]
This is my suggested fix:
```diff
diff --git a/sympy/core/mod.py b/sympy/core/mod.py
index 873e815cb2..3f0e07a561 100644
--- a/sympy/core/mod.py
+++ b/sympy/core/mod.py
@@ -164,8 +164,10 @@ def number_eval(p, q):
                 return prod_non_mod*cls(net, q)
 
             if q.is_Integer and q is not S.One:
-                non_mod_l = [i % q if i.is_Integer and (i % q is not S.Zero) else i for
-                             i in non_mod_l]
+                if all(t.is_integer for t in p.args):
+                    non_mod_l = [i % q if i.is_Integer else i for i in p.args]
+                    if any(iq is S.Zero for iq in non_mod_l):
+                        return S.Zero
 
             p = Mul(*(non_mod_l + mod_l))
```
Then
```python
In [1]: x = symbols('x')

In [2]: Mod(3*x, 2)
Out[2]: 3⋅x mod 2

In [3]: x = symbols('x', integer=True)

In [4]: Mod(3*x, 2)
Out[4]: x mod 2
```

**Comment by oscarbenjamin** [comment]
@joaorrmattos are you actually interested in non-integer solutions to these equations?

There is a PR (gh-26031) that will change the behaviour of `Mod(3*x, 2)` as I described above. Still though `nonlinsolve` will not be able to solve these equations because it does not know how to handle `Mod`.

There is an issue gh-25883 which discusses adding methods to solve equations such as this but with the intention of finding integer solutions.

For the example system shown as far as I can tell the solutions require all symbols to take integer values. In fact the set of solutions is just that all symbols need to be even (if I have worked this out correctly):
```python
In [42]: s = FiniteSet(*system)

In [43]: print(s)
{0, 2*(Mod(-3*w, 1)), Mod(-3*w, 2), 2*(Mod(w, 1)), 2*(Mod(2*w, 1)), 2*(Mod(4*w, 1)), 2*(Mod(-3*x, 1)), Mod(-3*x, 2), 2*(Mod(x, 1)), 2*(Mod(2*x, 1)), 2*(Mod(4*x, 1)), 2*(Mod(-3*y, 1)), Mod(-3*y, 2), 2*(Mod(-3*z, 1)), Mod(-3*z, 2), Mod(-6*w - 3*y, 2), Mod(-3*w - 6*y, 2), 2*(Mod(-3*w - 3*y, 1)), Mod(-3*w - 3*y, 2), 2*(Mod(-3*w - 3*z, 1)), Mod(-3*w - 3*z, 2), Mod(-6*x - 3*z, 2), 2*(Mod(-3*x - 3*y, 1)), Mod(-3*x - 3*y, 2), Mod(-3*x - 6*z, 2), 2*(Mod(-3*x - 3*z, 1)), Mod(-3*x - 3*z, 2), 2*(Mod(y + z, 1)), Mod(y + z, 2), 2*(Mod(2*y + 2*z, 1)), 2*(Mod(w + y + z, 1)), 2*(Mod(2*w + y + z, 1)), Mod(2*w + y + z, 2), 2*(Mod(2*w + 2*y + 2*z, 1)), 2*(Mod(4*w + y + z, 1)), Mod(4*w + y + z, 2), 2*(Mod(4*w + 2*y + 2*z, 1)), 2*(Mod(x + y + z, 1)), 2*(Mod(2*x + y + z, 1)), Mod(2*x + y + z, 2), 2*(Mod(2*x + 2*y + 2*z, 1)), 2*(Mod(4*x + y + z, 1)), Mod(4*x + y + z, 2), 2*(Mod(4*x + 2*y + 2*z, 1)), Mod(-6*w - 3*x - 3*y - 6*z, 2), Mod(-3*w - 6*x - 6*y - 3*z, 2), 2*(Mod(-3*w - 3*x - 3*y - 3*z, 1)), Mod(-3*w - 3*x - 3*y - 3*z, 2), 2*(Mod(w + x + y + z, 1)), 2*(Mod(w + 4*x + 2*y + 2*z, 1)), 2*(Mod(2*w + 2*x + 2*y + 2*z, 1)), 2*(Mod(2*w + 4*x + 3*y + 3*z, 1)), Mod(2*w + 4*x + 3*y + 3*z, 2), 2*(Mod(4*w + x + 2*y + 2*z, 1)), 2*(Mod(4*w + 2*x + 3*y + 3*z, 1)), Mod(4*w + 2*x + 3*y + 3*z, 2), 2*(Mod(4*w + 4*x + 4*y + 4*z, 1)), Mod(4*w + 4*x + 5*y + 5*z, 2)}

In [44]: n, m, i, j = symbols('n, m, i, j', even=True)

In [45]: s.subs({w:n,x:m,y:i,z:j})
Out[45]: {0}
```
