### ISSUE TITLE
Simple terms containing non integer powers don't simplify despite conveying enough information on their sign

### ISSUE THREAD

**Issue by arnabnandikgp** [sympy/sympy#26021]
I was working on  a issue and realised that in sympy terms like `a+b-sqrt(a**2+b**2+2*a*b)` dont simplify though declarations about their signs have already been made clear, as in the following examples
```
>>> a,b=symbols('a b',positive=True)
>>> term=a+b-sqrt(a**2+b**2+2*a*b)
>>> init_printing()
>>> term
           _________________
          ╱  2            2 
a + b - ╲╱  a  + 2⋅a⋅b + b  
>>> term.equals(0)
False
```
even after trying methods like simplify() and factor things do not work
```
>>> term.simplify()
           _________________
          ╱  2            2 
a + b - ╲╱  a  + 2⋅a⋅b + b  
>>> term.factor()
           _________________
          ╱  2            2 
a + b - ╲╱  a  + 2⋅a⋅b + b  
```
though if we try the same with a single variable , it works as expected:
```
>>> term1=a-sqrt(a**2)
>>> term1
0
```
I tried similar examples with cube roots  with additional conditions of the variable being real too but the same behaviour is seen:
```
>>> a,b=symbols('a b',positive=True,real=True)
>>> term2=a+b-(a**3+b**3+3*a**2*b+3*a*b**2)**(S(1)/3)
>>> term2
           ___________________________
        3 ╱  3      2          2    3 
a + b - ╲╱  a  + 3⋅a ⋅b + 3⋅a⋅b  + b  
>>> term2.simplify()
           ___________________________
        3 ╱  3      2          2    3 
a + b - ╲╱  a  + 3⋅a ⋅b + 3⋅a⋅b  + b  
>>> term2.equals(S.Zero)
>>> 

```

**Comment by oscarbenjamin** [comment]
You can use factor with `deep=True` to factor the expression under the radical:
```python
In [1]: >>> a,b=symbols('a b',positive=True)
   ...: >>> term=a+b-sqrt(a**2+b**2+2*a*b)

In [2]: term
Out[2]: 
           _________________
          ╱  2            2 
a + b - ╲╱  a  + 2⋅a⋅b + b  

In [3]: term.factor(deep=True)
Out[3]: 0
```

**Comment by MostlyKIGuess** [comment]
- This is  specified in the docs here https://docs.sympy.org/latest/modules/simplify/simplify.html
- Here's the source:
https://github.com/sympy/sympy/blob/d2be7bacd2604e98a642f74028e8f0d7d6084f78/sympy/simplify/powsimp.py#L18-L490
