### ISSUE TITLE
[unintuitive] sympy.solve(...,x,y,z) returns less results when specifiyng the required variables

### ISSUE THREAD

**Issue by alexanderthiem** [sympy/sympy#26025]
Given a system of equations *eq and a subset of variables used in those equations (x,y,z in my example), sympy.solve(*eq) does give solutions (in my case the single one solution present), while sympy.solve(*eq, x,y,z) returns an empty list of solutions, implying no solution is present.

This problem occured to me while solving the following application in 3d vector geometry, i,j and k can be considered constant non co-planar points with directions in 3dimensionial space. I also experienced cases, where solving for specific variables resulted in solutions dependent from a free variable, while searching for others resulted in only one solution

```
    x1, y1, z1, x1d, y1d, z1d = i  # time t1
    x2, y2, z2, x2d, y2d, z2d = j  # time t2
    x3, y3, z3, x3d, y3d, z3d = k  # time t3

    t1 = sp.Symbol('t1')
    t2 = sp.Symbol('t2')
    t3 = sp.Symbol('t3')

    #coordinates after time
    x1, y1, z1 = x1+x1d*t1, y1+y1d*t1, z1+z1d*t1
    x2, y2, z2 = x2+x2d*t2, y2+y2d*t2, z2+z2d*t2
    x3, y3, z3 = x3+x3d*t3, y3+y3d*t3, z3+z3d*t3

    x, y, z, xd, yd, zd = ["x", "y", "z", "xd", "yd", "zd"] * map(sp.Symbol)
    
    res = sp.solve([x1 - (x+xd*t1), y1 - (y+yd*t1), z1 - (z+zd*t1), x2 - (x+xd*t2), y2 - (y +
                    yd*t2), z2 - (z+zd*t2), x3 - (x+xd*t3), y3 - (y+yd*t3), z3 - (z+zd*t3)])```

**Comment by oscarbenjamin** [comment]
The code as shown does not run:
```
NameError: name 'i' is not defined
```
Please include complete code.

In any case the problem is most likely that you are trying to solve 9 equations for 9 unknowns but you are only providing 3 unknowns to `solve`.

**Comment by alexanderthiem** [comment]
You are right, i am only providing 3 unknowns to solve, while the 9 equations contain more unknowns than that.
That's because I don't care for the solution of those, whether there are multiple or just one or whatever... When s is the set of all solutions of the equations, I expected it to return something like the projection of all solutions:
`set( map( lambda res: res[x],res[y],res[z] , s ) )` thus if the other variables remain free, the result is dependent on them, if they don't only a single solution is spit out....

I realised now, the solve method assumes all symbols not provided as unknowns to remain free by the equations

For completeness, the whole code would be:
```
import sympy as sp

i,j,k = [346929738756520, 180308062329517, 348158644025623, 6, -5, -22], [254810664927620, 353739895010289, 244141919277765, -144, 403, -76], [295870756794909, 404627177923603, 198720163538165, -23, -185, 145]
x1, y1, z1, x1d, y1d, z1d = i  # time t1
x2, y2, z2, x2d, y2d, z2d = j  # time t2
x3, y3, z3, x3d, y3d, z3d = k  # time t3

t1 = sp.Symbol('t1')
t2 = sp.Symbol('t2')
t3 = sp.Symbol('t3')

#coordinates after time
x1, y1, z1 = x1+x1d*t1, y1+y1d*t1, z1+z1d*t1
x2, y2, z2 = x2+x2d*t2, y2+y2d*t2, z2+z2d*t2
x3, y3, z3 = x3+x3d*t3, y3+y3d*t3, z3+z3d*t3

x, y, z, xd, yd, zd = map(sp.Symbol, "x y z xd yd zd".split(" "))

res = sp.solve([x1 - (x+xd*t1), y1 - (y+yd*t1), z1 - (z+zd*t1), x2 - (x+xd*t2), y2 - (y +
                yd*t2), z2 - (z+zd*t2), x3 - (x+xd*t3), y3 - (y+yd*t3), z3 - (z+zd*t3)],x,y,z)
print(res)
```

**Comment by oscarbenjamin** [comment]
This is expected behaviour. Think of the equations as `F(X,P)=0` where `X` is the vector of unknowns and `P` are the symbolic parameters. The definition of the set that solve attempts to find is
```
{X: F(X,P)=0 for almost all P}
```
Depending on the choice of unknowns `X` this set might be empty so it is not just a question of projecting the set of solutions for the variables of interest.

Mathematica's `Solve` function has a third parameter representing unknowns whose values are not desired and that should be eliminated from the solution expressions. With that you could do
```python
solve(eqs, [x,y,z], [t1,t2,t3,xd,yd,zd])
```
but it is still necessary to list the 9 unknowns because the choice of unknowns determines whether or not solutions exist generically at all.

A simpler demonstration is something like this:
```python
In [12]: solve([x, x+y], [x, y])
Out[12]: {x: 0, y: 0}

In [11]: solve([x, x+y], [x])
Out[11]: []
```
Your expectation is for the second case to return `{x: 0}` but if you consider concrete values for the parameter `y` then for almost all choices there are no solutions for `x`:
```python
In [13]: solve([x, x+1], [x])
Out[13]: []

In [14]: solve([x, x+2], [x])
Out[14]: []
```
