### ISSUE TITLE
Limit involving modified bessel function not working as expected

### ISSUE THREAD

**Issue by anutosh491** [sympy/sympy#26040]
This works 
```
>>> limit(besselk(0, x + 1)/besselk(0, x), x, oo)
exp(-1)
```
This doesn't
```
>>> limit(besseli(0, x + 1)/besseli(0, x), x, oo)
Limit(besseli(0, x + 1)/besseli(0, x), x, oo, dir='-')     # expected exp(1)
```
For reference [from wolfram](https://www.wolframalpha.com/input?i=limit+calculator&assumption=%7B%22F%22%2C+%22Limit%22%2C+%22limit%22%7D+-%3E%22oo%22&assumption=%7B%22F%22%2C+%22Limit%22%2C+%22limitfunction%22%7D+-%3E%22besseli%280%2C+x+%2B+1%29%2Fbesseli%280%2C+x%29%22&assumption=%22FSelect%22+-%3E+%7B%7B%22Limit%22%7D%2C+%22dflt%22%7D)

**Comment by Abhishekjsr283204** [comment]
please assign it to me I
 want to work on this issue!

**Comment by sriramsowmithri9807** [comment]
![Screenshot 2024-01-05 100552](https://github.com/sympy/sympy/assets/95630559/2c292a8d-74f9-4b50-9391-57a1d1e5355e)
```
from sympy import symbols, oo, limit, besseli, exp

x = symbols('x')
expr = besseli(0, x + 1) / besseli(0, x)
result = limit(expr, x, oo)

print(result)

```

Try like this!!!

**Comment by sriramsowmithri9807** [comment]
> ![Screenshot 2024-01-05 100552](https://private-user-images.githubusercontent.com/95630559/294395738-2c292a8d-74f9-4b50-9391-57a1d1e5355e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ0Mjk3MjksIm5iZiI6MTcwNDQyOTQyOSwicGF0aCI6Ii85NTYzMDU1OS8yOTQzOTU3MzgtMmMyOTJhOGQtNzRmOS00YjUwLTkzOTEtNTdhMWQxZTUzNTVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA1VDA0MzcwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJkMWE0NTA2Mzc0NDk4ZWNiMWZiZDIxOGU4ZWYzMzc5M2FlOGRhNWEwNzliZDhjZjc5NjUwNzM2OGU3YjM1NGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.eZiLQRsJvSfBlzzi1ZV-w0_4RCyj2MA1bFDN2jXg50A)
> 
> ```
> from sympy import symbols, oo, limit, besseli, exp
> 
> x = symbols('x')
> expr = besseli(0, x + 1) / besseli(0, x)
> result = limit(expr, x, oo)
> 
> print(result)
> ```
> 
> Try like this!!!

@anutosh491

**Comment by anutosh491** [comment]
Wait are you using the latest master. Firstly 1 is the wrong result and secondly I think it would return self. What version are you using ?

**Comment by anutosh491** [comment]
@Abhishekjsr283204 
We don't assign issues here at SymPy, though you are welcome to work on it.

**Comment by sriramsowmithri9807** [comment]
@anutosh491 Bro i am using the latest version sympy (1.12v) is that the result was not correct

**Comment by anutosh491** [comment]
If that's the case, you can go ahead and try fixing it.

**Comment by sriramsowmithri9807** [comment]
ok!

**Comment by arnabnandikgp** [comment]
The issue here is that in the following lines:
https://github.com/sympy/sympy/blob/3f7066f0d4f7efde2126715c9f5e1768be832371/sympy/series/limits.py#L341-L342
For the expression `besseli(0, x + 1)/besseli(0, x)` whose leading term contains exp(1) is not able to clear this conditional in contrast to the case for `(besselk(0, x + 1)/besselk(0, x)` where it had exp(-1) in its leading term. The reason for this is sympy after calculating leading term internally converts exp(1) to as E and hence the error.
