### ISSUE TITLE
Fourier Transform not giving Dirac Function

### ISSUE THREAD

**Issue by MostlyKIGuess** [sympy/sympy#26053]
- I am not really sure how this works but for  $e^{2\pi i f_{0}t}$ it should return Dirac Delta function when Fourier Transformed, but it is giving this for me :
when my code is:
```python
from sympy import * 
from sympy.plotting import plot
from sympy.abc import x, k,t,f,i,j

func2 = exp(2*pi*i*f*t)
inverse = fourier_transform(func2, f, t)
print(inverse)
simplified_inverse = simplify(inverse)
print(simplified_inverse)
```
- Output
```sh
 python3 fourier.py 
FourierTransform(exp(2*pi*f*i*t), f, t)
FourierTransform(exp(2*pi*f*i*t), f, t)
```

- Now can anyone make me understand why is it not giving Dirac Delta? or I am not able to use it properly

**Comment by jksuom** [comment]
See e.g.. https://github.com/sympy/sympy/issues/18855#issuecomment-599059023

**Comment by abhayku2002** [comment]
In the Inverse Fourier Transform, `omega` and `t` represent the frequency and time variables
``` python
from sympy import * 
from sympy.plotting import plot
from sympy.abc import x, k,t,omega,i,j

delta = DiracDelta(omega - 1)
inverse_fourier_transform(delta, omega, t)
```
Output: 
$` \displaystyle e^{2 i \pi t} `$

and for Fourier transform, 
```python
fourier_transform(exp(2*pi*I*t), t, omega)
 ```
 Output: 
  $` \displaystyle \mathcal{F}_{t}\left[e^{2 i \pi t}\right]\left(\omega\right) `$

**Comment by MostlyKIGuess** [comment]
Got it, thank you everyone
