### ISSUE TITLE
solving nonlinear differential equation 

### ISSUE THREAD

**Issue by hariharan382** [sympy/sympy#26067]
Hi I am trying to solve a nonlinear differential equation, but getting an below error , I have no idea how to proceed further, what are the other ways to solve it, I tried solving using scipy , which also gives error , How do I solve this 

NotImplementedError: The given ODE 0.25*q(t) + 10.0*sin(q(t)) + Derivative(q(t), t) + Derivative(q(t), (t, 2)) - 10.3926990816987 cannot be solved by the factorable group method

`import numpy as np
from sympy import symbols
import sympy as sym
from sympy.abc import x
from sympy import Function, dsolve, Eq, pprint, diff,sin, cos,pi
from pprint import pprint
from scipy.integrate import odeint
import matplotlib.pyplot as plt

#init variables  
J = 1
m=1
g =10
kp =1/4
kd = 1
q0 = pi/8
qdot0 = 0
qd = pi/2
l=1

t =  symbols("t")
q = sym.Function("q", real=True)(t)
dqdt = q.diff(t)
dq2dt2 = q.diff(t,2)
diff_eqn = sym.Eq(J*dq2dt2+m*g*l*sin(q)-kp*(qd-q) + kd*(dqdt) - m*g*l*sin(qd),0)
ics= {q.subs(t,0):q0, q.diff(t).subs(t,0):qdot0}
result = sym.dsolve(diff_eqn,ics = ics)

pprint(result)
`

config: 
* python 3.10
* Windows
* sympy  1.12

**Comment by oscarbenjamin** [comment]
GitHub issues are not the place to ask for help with using SymPy. Use stackoverflow or the mailing list instead.
