### ISSUE TITLE
sympify function breaking on numpy datatypes in numpy 2.0.0.dev0

### ISSUE THREAD

**Issue by mironleon** [sympy/sympy#26094]
I could not find if there was already some issue tracking the upcoming release of numpy 2.0, but I was future proofing a project by testing it against the numpy 2 dev release and ran into an issue with `sympify`.

Apologies if you are already working on this

```python
import numpy as np
from sympy.core import sympify

sympify(np.float64(2.34))
```
Will work with numpy 1.x, but it breaks (with the `2.0.0.dev0` numpy) with:

```
Traceback (most recent call last):
  File "/home/miron/src/finesse3/test.py", line 4, in <module>
    sympify(np.float64(2.34))
  File "/home/miron/.pyenv/versions/3.11.6/envs/finesse3/lib/python3.11/site-packages/sympy/core/sympify.py", line 383, in sympify
    return conv(a)
           ^^^^^^^
  File "/home/miron/.pyenv/versions/3.11.6/envs/finesse3/lib/python3.11/site-packages/sympy/core/numbers.py", line 1070, in __new__
    num = _convert_numpy_types(num)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/miron/.pyenv/versions/3.11.6/envs/finesse3/lib/python3.11/site-packages/sympy/core/sympify.py", line 95, in _convert_numpy_types
    return Float(a, precision=prec)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/miron/.pyenv/versions/3.11.6/envs/finesse3/lib/python3.11/site-packages/sympy/core/numbers.py", line 1126, in __new__
    _mpf_ = mlib.from_str(num, precision, rnd)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/miron/.pyenv/versions/3.11.6/envs/finesse3/lib/python3.11/site-packages/mpmath/libmp/libmpf.py", line 1331, in from_str
    man, exp = str_to_man_exp(x, base=10)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/miron/.pyenv/versions/3.11.6/envs/finesse3/lib/python3.11/site-packages/mpmath/libmp/libmpf.py", line 1294, in str_to_man_exp
    float(x)
ValueError: could not convert string to float: 'np.float64(2.34)'
```

The issue lies in that numpy seems to have changed their `__repr__` implementation:

numpy 1.x `repr(np.float64(2.34))` returns `'2.34'`, but numpy 2 returns `'np.float64(2.34)'`

This breaks the internal function `_convert_numpy_types` https://github.com/sympy/sympy/blob/36bcecfeb5b359238a6047c7888555e196d43c89/sympy/core/sympify.py#L76

specifically here:

```python
a = str(list(np.reshape(np.asarray(a), (1, np.size(a)))[0]))[1:-1]
```

because in the end this is calling `str` on a list, which outputs `'[repr(i) for i in list]'`, which in numpy 2 would result in:

`'[np.float64]'` and cutting of the brackets (done with the `[1:-1]` at the end) leaves you with `'np.float64'`, which is eventually gets passed to `float` and fails.

Possible fix would be something like:

```python
# index the resulting list so you are calling `str` directly on the numpy float
a = str(list(np.reshape(np.asarray(a), (1, np.size(a)))[0])[0])[1:-1]
```
Or something similiar.

**Comment by oscarbenjamin** [comment]
I guess we should add a CI job for this.

> numpy 1.x `repr(np.float64(2.34))` returns `'2.34'`, but numpy 2 returns `'np.float64'`

I can't immediately test this. Do you mean that that literally this happens:
```python
>>> repr(np.float64(2.34))
'np.float64'
```
That seems like an odd change...

Any idea what is the motivation for that?

**Comment by mironleon** [comment]
![image](https://github.com/sympy/sympy/assets/119943561/2073a292-6f43-4007-abb9-9e4f36d47fbf)

Maybe I'm being a bit to early, I could not directly find something in the release notes https://numpy.org/devdocs/release/2.0.0-notes.html

The dev versions can be downloaded from here https://anaconda.org/scientific-python-nightly-wheels/repo?type=pypi&label=main

**Comment by oscarbenjamin** [comment]
Looks like it is this:
https://numpy.org/neps/nep-0051-scalar-representation.html

**Comment by mironleon** [comment]
Good find, seems like the change is here to stay then.

Let me know if you want me to open a PR (although I can imagine this might have a bigger impact on sympy)

As far as I am aware there is a release candidate for numpy2 at the end of the month and the actual release will be a few months later still

**Comment by oscarbenjamin** [comment]
It is difficult to run all tests for numpy if we can't also test with scipy, matplotlib etc.

It doesn't seem to be possible from the nightly builds:
```
$ pip install -i https://pypi.anaconda.org/scientific-python-nightly-wheels/simple numpy scipy --force-reinstall
Looking in indexes: https://pypi.anaconda.org/scientific-python-nightly-wheels/simple
Collecting numpy
  Downloading https://pypi.anaconda.org/scientific-python-nightly-wheels/simple/numpy/2.0.0.dev0/numpy-2.0.0.dev0-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (18.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.6/18.6 MB 19.2 MB/s eta 0:00:00
Collecting scipy
  Downloading https://pypi.anaconda.org/scientific-python-nightly-wheels/simple/scipy/1.13.0.dev0/scipy-1.13.0.dev0-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (38.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 38.2/38.2 MB 14.4 MB/s eta 0:00:00
INFO: pip is looking at multiple versions of <Python from Requires-Python> to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of numpy to determine which version is compatible with other requirements. This could take a while.
ERROR: Cannot install numpy and scipy==1.13.0.dev0 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested numpy
    scipy 1.13.0.dev0 depends on numpy>=1.22.4

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
```
I guess that the same would happen if trying to build from git directly.

**Comment by oscarbenjamin** [comment]
The core tests only show a few numpy failures (all because of repr) but I expect that there would be more problems if we could run the full optional dependency test suite.

**Comment by mironleon** [comment]
I can install the dev versions of scipy and numpy next to each other (on python 3.11).

But possibly for sympy it is easier to wait for the release candidates to come out

**Comment by oscarbenjamin** [comment]
Thinking purely about the repr issue I think that it is probably a bad idea to convert the float to a string anyway. The reason that it is done is to avoid calling `float` which would potentially lose precision for non-64-bit floats but at least for 64-bit floats which is the most common case we should just call float.

I am not sure that NumPy provides a good way to handle things like longdouble, doubledouble etc without losing precision during conversion. That is most likely why repr is being used here.

**Comment by bjodah** [comment]
If we  call `.as_integer_ratio()` on the numpy float we will keep the full precision. This also works for `numpy.float128` (I've used that with `flint` to generate reference values for test cases various C++ solvers using `long double`).

**Comment by bjodah** [comment]
any way, to avoid rounding issues, `.hex()` is already much better than `__str__`.

**Comment by bjodah** [comment]
Oh yes, `numpy.float128` is a terrible name. On x86-64 we only get 80-bit extended precision (as you have figured out).

**Comment by bjodah** [comment]
The missing `.hex` method has an open issue over at numpy, xref: https://github.com/numpy/numpy/issues/13375

**Comment by asmeurer** [comment]
The most ideal would be if numpy had a way to extract the mpf tuple from a numpy float directly.

**Comment by oscarbenjamin** [comment]
Closing after gh-26112
