### ISSUE TITLE
Multiple Levi-Civita with common index not simplified.

### ISSUE THREAD

**Issue by handec** [sympy/sympy#26109]
Hi, I have an expression being generated for multiple different variables, which has two Levi-Civita symbols as below
`from sympy import LeviCivita;
x = LeviCivita(a,b,c)*LeviCivita(d,e,c)`

This actually needs to return the following contracted expression consisting of Kronecker Deltas.
`KroneckerDelta(a,d)*KroneckerDelta(b,e) - KroneckerDelta(a,e)*KroneckerDelta(b,d)`

However, it cannot be contracted using the simplification or evaluation methods I have tried. Is there a way to incorporate this into the sympy methods?

**Comment by oscarbenjamin** [comment]
Methods for rewriting LeviCivita could be added. I'm not sure which rewrites make sense but most likely `.rewrite(Piecewise)` is the most generally useful method.

In your case I think that the identity does not hold without a summation though so it would not be a valid transformation unless using some function that is expected to interpret the expression using Einstein summation for `c`.

**Comment by vicbguti-espol** [comment]
Something you might do meanwhile, would be use this.

```python
from sympy import symbols, Eq, Piecewise, KroneckerDelta, LeviCivita, simplify

# Define symbols
a, b, c, d, e = symbols('a b c d e')

# Original expression
expr = LeviCivita(a, b, c) * LeviCivita(d, e, c)

# Define the piecewise expression
p = Piecewise(
    ((KroneckerDelta(a, d) * KroneckerDelta(b, e) - KroneckerDelta(a, e) * KroneckerDelta(b, d)), True),
)

# Rewrite the expression
rewritten_expr = Eq(expr, p)

# Simplify the expression
simplified_expr = simplify(rewritten_expr)

simplified_expr
```
![image](https://github.com/sympy/sympy/assets/133924738/0ebdf1aa-9324-49ff-a6a7-c63ad55ee4a1)

**Comment by handec** [comment]
Hi @vicbguti-espol I tried this and it worked. But I have around 100 of different indexed versions of these in my calculations. So I am trying to place this into a function where the argument is the `expr`. 

I tried the `get_indices` and `get_free_indices` with `split` as in the documentation of TensMul in [here](https://docs.sympy.org/latest/modules/tensor/tensor.html#sympy.tensor.tensor.TensMul). But those did not work as I intended them to be.

I also tried `replace` and `rewrite` methods to try to simplify and rewrite some parts of my calculations but I had no concrete result at the end. Do you have any recommendation on how to obtain the indices of the `LeviCivita`s from the expression?

**Comment by handec** [comment]
> Hi @vicbguti-espol I tried this and it worked. But I have around 100 of different indexed versions of these in my calculations. So I am trying to place this into a function where the argument is the `expr`.
> 
> I tried the `get_indices` and `get_free_indices` with `split` as in the documentation of TensMul in [here](https://docs.sympy.org/latest/modules/tensor/tensor.html#sympy.tensor.tensor.TensMul). But those did not work as I intended them to be.
> 
> I also tried `replace` and `rewrite` methods to try to simplify and rewrite some parts of my calculations but I had no concrete result at the end. Do you have any recommendation on how to obtain the indices of the `LeviCivita`s from the expression?

I came back with a solution that does the job but is a temporary fix for this. Here is my solution.

```python
################################################################################################################
## ---------------------------- Einstein summation convention for Levi-Civita ----------------------------------
from sympy import symbols, Eq, Piecewise, KroneckerDelta, LeviCivita, simplify
from sympy.tensor.tensor import TensorIndexType, tensor_indices, tensor_heads
import regex as re

def EinsteinSum_LeviCivita(expr):                  # c is the common index to be summed over
    res = re.findall(r'\(.*?\)', str(expr))
    indices_list = [i.strip('()') for i in res]
    a,b,c = symbols(indices_list[0])
    d,e,c = symbols(indices_list[1])
    expr_to_check = LeviCivita(a, b, c) * LeviCivita(d, e, c)
    p = Piecewise(((KroneckerDelta(a, d) * KroneckerDelta(b, e) - KroneckerDelta(a, e) * KroneckerDelta(b, d)), True),)
    rewritten_expr = Eq(expr_to_check, p)
    simplified_expr = simplify(rewritten_expr)
    return simplified_expr

# Define symbols
a, b, c, d, e, f= symbols('a b c d e f')

# Original expression
expr = LeviCivita(a, b, c) * LeviCivita(f, e, c)

simplified_expr = EinsteinSum_LeviCivita(expr)
simplified_expr
```
