### ISSUE TITLE
Lambdify crashes on empty tuple

### ISSUE THREAD

**Issue by tjstienstra** [sympy/sympy#26119]
Sometimes I have a large set of expressions grouped in various tuples to be used in combination with CSE. However, I noticed that `lambidfy` actually crashes due to a simple `SyntaxError` if one of those tuples is empty. Here is a simple example:
```python
import sympy as sm
from sympy.printing.numpy import NumPyPrinter

a = sm.symbols("a")
sm.lambdify((a,), ((), (a,)), printer=NumPyPrinter)
```
This gives the following error in `lambdify`:
```
.../sympy/utilities/lambdify.py:903) in lambdify
    c = compile(funcstr, filename, 'exec')

  File <lambdifygenerated-2>:2
    return ((,), (a,),)
             ^
SyntaxError: invalid syntax
```

**Comment by TJStienstra** [comment]
I think that [this line](https://github.com/sympy/sympy/blob/b60badaf57441334c145590f6da28fb059ebc61f/sympy/utilities/lambdify.py#L965) in `sympy.utilities.lambdify._recursive_to_string` is causing the trouble.

**Comment by mohakmalviya** [comment]
hello sir i have raised a PR for this issue! please review it. Thankyou

**Comment by mohakmalviya** [comment]
hello sir i have raised a PR for this issue please review it! thanks

**Comment by sylee957** [comment]
> [Around this line](https://github.com/sympy/sympy/blob/b60badaf57441334c145590f6da28fb059ebc61f/sympy/utilities/lambdify.py#L965) in `sympy.utilities.lambdify._recursive_to_string` is the trouble. Changing it to something like the following already fixes it:
> 
> ```python
>         elif isinstance(arg, tuple):
>             left, right = "(", ",)"
>             if not arg:
>                 return "()"
> ```

After seeing the attempted PR implementation, I question by symmetry that why not as well:

>         if isinstance(arg, list):
>             left, right = "[", ",]"
>             if not arg:
>                 return "[]"

Is empty list not an issue, or does it `_recursive_to_string` logically reach the case where list is empty as well?

**Comment by TJStienstra** [comment]
> Is empty list not an issue, or does it _recursive_to_string logically reach the case where list is empty as well?

No that is not an issue. The problem is that we choose to always end a tuple with a `,` to cover the case that a tuple has a length of 1, e.g. `(a,)`. This is not a problem with lists as `[a]` is perfectly valid.

**Comment by sylee957** [comment]
Okay, I notice the difference that right of tuple is fused with comma like ‚)
