### ISSUE TITLE
Error in creating virtual environment

### ISSUE THREAD

**Issue by mohakmalviya** [sympy/sympy#26118]
while creating virtual environment using this command - 
![Screenshot from 2024-01-25 01-56-11](https://github.com/sympy/sympy/assets/38376114/e43166fb-3b0b-43ce-8fa7-524bc60c3565)

It is throwing me this error - 

![image](https://github.com/sympy/sympy/assets/38376114/d7424ced-50f3-4f7a-a91c-f7297f1f563d)

this should be resolved by running several commands which are not given in the sympy documentation

**Comment by oscarbenjamin** [comment]
Those instructions are likely incorrect. You can just venv/virtualenv. There is no need to use conda.

**Comment by mohakmalviya** [comment]
> Those instructions are likely incorrect. You can just venv/virtualenv. There is no need to use conda.

i have gone through the documentation of Sympy 1.12 (latest version) and found that it is outdated and needs to be changed!

**Comment by moorepants** [comment]
It may be that the flake8-comprehensions package is only available from the conda forge channel and the instructions assume that is setup.

**Comment by moorepants** [comment]
Yes, that is the case: https://anaconda.org/search?q=flake8-comprehensions

**Comment by hanspi42** [comment]
conda-forge is not normally used, so the correct command (for the manual) would be:

```conda create -n sympy-dev python=3 mpmath flake8 conda-forge::flake8-comprehensions```

**Comment by sylee957** [comment]
I'd suggest to remove flake8 stuff there

- It's not SymPy's hard dependency

- Neither is it optional dependency

- We don't exhaustively list other optional dev dependencies like pytest, or mypy.

- It may not be useful.

- It can be installed in many other paths now, for instance, vscode marketspace has flake8 plugin. (And I have opinion that that is easier to use that instead)

**Comment by moorepants** [comment]
But isn't the page shown by the OP for the development environment setup?

**Comment by sylee957** [comment]
It is on the latest version, but anyway seems like changed in the current version.
So we can close this issue if author is answered

https://docs.sympy.org/latest/contributing/dev-setup.html

**Comment by moorepants** [comment]
Dev docs:

![image](https://github.com/sympy/sympy/assets/276007/7f3b7eff-061f-4e80-8fdc-5d461108d677)
