### ISSUE TITLE
Integral isn't distributed in summation

### ISSUE THREAD

**Issue by RemDelaporteMathurin** [sympy/sympy#26116]
Hi all,

I'm trying to perform this integration

$$
\int\limits_{0}^{t_{f}} 2 D L P_{0} S \sum_{n=1}^{\infty} \frac{\alpha{\left(n \right)} e^{- D t \alpha^{2}{\left(n \right)}}}{\left(L + l \left(L^{2} + \alpha^{2}{\left(n \right)}\right)\right) \sin{\left(l \alpha{\left(n \right)} \right)}} \, dt
$$

```python
import sympy as sp


x = sp.Symbol("x", real=True, positive=True)
t = sp.Symbol("t", real=True, positive=True)
D = sp.Symbol("D", real=True, positive=True, nonzero=True)
S = sp.Symbol("S", real=True, positive=True)
P_0 = sp.Symbol("P_0", real=True, positive=True)
l = sp.Symbol("l", real=True, positive=True)
L = sp.Symbol("L", real=True, positive=True)
n = sp.Symbol("n", integer=True, positive=True)
alpha = sp.Function("alpha", positive=True, nonzero=True)(n)

numerator = sp.exp(-(alpha**2) * D * t) * sp.sin(alpha * x)
denum = (l * (alpha**2 + L**2) + L) * sp.sin(alpha * l)
c = 2 * S * P_0 * L * sp.Sum(numerator / denum, (n, 1, sp.oo))

flux = D * sp.diff(c, x)
flux_at_x0 = flux.subs(x, 0)

t_f = sp.Symbol("t_f")
cumulative_flux = sp.integrate(flux_at_x0, (t, 0, t_f)).simplify()
print(cumulative_flux)
```

I obtain:

$$
2 D L P_{0} S \int\limits_{0}^{t_{f}} \sum_{n=1}^{\infty} \frac{\alpha{\left(n \right)} e^{- D t \alpha^{2}{\left(n \right)}}}{\left(L^{2} l + L + l \alpha^{2}{\left(n \right)}\right) \sin{\left(l \alpha{\left(n \right)} \right)}}\, dt
$$

where I expected this since no variables at $t$ dependent:

$$
2 D L P_{0} S  \sum_{n=1}^{\infty} \frac{\alpha{\left(n \right)} \int\limits_{0}^{t_{f}}e^{- D t \alpha^{2}{\left(n \right)}}\, dt}{\left(L^{2} l + L + l \alpha^{2}{\left(n \right)}\right) \sin{\left(l \alpha{\left(n \right)} \right)}}
$$

I tried making a minimal working example:

```python
import sympy as sp


t = sp.Symbol("t", real=True, positive=True)
n = sp.Symbol("n", integer=True, positive=True)
t_f = sp.Symbol("t_f")


Ft = sp.Function("Ft")(t)
Fn = sp.Function("Fn")(n)

expr = sp.Sum(Ft * Fn, (n, 1, sp.oo))
print(sp.integrate(expr, (t, 0, t_f)))
```

I obtain:
```
Integral(Sum(Fn(n)*Ft(t), (n, 1, oo)), (t, 0, t_f))
```

and expected:

```
Sum(Fn(n)*Integral(Ft(t), (t, 0, t_f)), (n, 1, oo))
```

Am I doing something silly here?

Thanks in advance!

**Comment by RemDelaporteMathurin** [comment]
Note: the derivative seems to be distributed correctly:

```python
import sympy as sp


t = sp.Symbol("t", real=True, positive=True)
n = sp.Symbol("n", integer=True, positive=True)
t_f = sp.Symbol("t_f", real=True, positive=True)


Ft = sp.Function("Ft")(t)
Fn = sp.Function("Fn")(n)

expr = sp.Sum(Ft * Fn, (n, 1, sp.oo))
print(sp.integrate(expr, (t, 0, t_f)))
print(sp.diff(expr, t))
```

```
Integral(Sum(Fn(n)*Ft(t), (n, 1, oo)), (t, 0, t_f))
Sum(Fn(n)*Derivative(Ft(t), t), (n, 1, oo))
```

Related to https://github.com/sympy/sympy/issues/7827 maybe?

**Comment by oscarbenjamin** [comment]
I don't see why an integral of a sum should turn into a sum of an integral.

Or is the point that the integral should evaluate?

**Comment by RemDelaporteMathurin** [comment]
> I don't see why an integral of a sum should turn into a sum of an integral.

In this specific case you do have:

$$
\int_0^{t_f} \sum_n Fn(n) \ Ft(t) \ dt =  \sum_n \left( Fn(n) \int_0^{t_f}  Ft dt \right)
$$

since $Fn(n)$ isn't dependent on $t$

Here is another [example of distributing an integral in a sum](https://stackoverflow.com/questions/61119648/sympy-integral-of-summation)

**Comment by RemDelaporteMathurin** [comment]
@oscarbenjamin I realised that the difference between the sum in the Stackoverflow reply and mine is that mine is an infinite sum. If I replace `sp.oo` by a symbol $N$ then i obtain the expected behaviour:

```python
import sympy as sp


t = sp.Symbol("t", real=True, positive=True)
n = sp.Symbol("n", integer=True, positive=True)
t_f = sp.Symbol("t_f", real=True, positive=True)

N = sp.Symbol("N", integer=True, positive=True)

Ft = sp.Function("Ft")(t)
Fn = sp.Function("Fn")(n)

expr = sp.Sum(Ft * Fn, (n, 1, N))  # <-- infinity replaced by N
print(sp.integrate(expr, (t, 0, t_f)))
```


```
Sum(Fn(n)*Integral(Ft(t), (t, 0, t_f)), (n, 1, N))
```

Is there a bug with distributing in infinite sums?

**Comment by oscarbenjamin** [comment]
> Here is another [example of distributing an integral in a sum](https://stackoverflow.com/questions/61119648/sympy-integral-of-summation)

In that example the integral evaluates.

> In this specific case you do have:
> 
> ∫0tf∑nFn(n) Ft(t) dt=∑n(Fn(n)∫0tfFtdt)
> 
> since Fn(n) isn't dependent on t

I showed how to get that with factor_terms. I don't see why `integrate` should do that by default though. You asked for an integral of a sum and you got an integral of a sum.

> Is there a bug with distributing in infinite sums?

I don't consider it a bug since both expressions are correct. More care needs to be taken with infinite sums though because it is not always valid to exchange the order of infinite summations/integrals.

**Comment by RemDelaporteMathurin** [comment]
> I showed how to get that with factor_terms

I'm not sure I'm following what you mean here

> In that example the integral evaluates.

Yes I would like this integral to evaluate too. 

Do we agree on:

$$
\int\limits_{0}^{t_{f}} 2 D L P_{0} S \sum_{n=1}^{N} \frac{\alpha{\left(n \right)} e^{- D t \alpha^{2}{\left(n \right)}}}{\left(L + l \left(L^{2} + \alpha^{2}{\left(n \right)}\right)\right) \sin{\left(l \alpha{\left(n \right)} \right)}} \, dt =
2 D L P_{0} S  \sum_{n=1}^{N} \frac{\alpha{\left(n \right)} \int\limits_{0}^{t_{f}}e^{- D t \alpha^{2}{\left(n \right)}}\, dt}{\left(L^{2} l + L + l \alpha^{2}{\left(n \right)}\right) \sin{\left(l \alpha{\left(n \right)} \right)}}
$$

no other terms are depending on $t$ so I naively assumed that the above statement is correct but I may be wrong?


When running 
```python
import sympy as sp


x = sp.Symbol("x", real=True, positive=True)
t = sp.Symbol("t", real=True, positive=True)
D = sp.Symbol("D", real=True, positive=True, nonzero=True)
S = sp.Symbol("S", real=True, positive=True)
P_0 = sp.Symbol("P_0", real=True, positive=True)
l = sp.Symbol("l", real=True, positive=True)
L = sp.Symbol("L", real=True, positive=True)
n = sp.Symbol("n", integer=True, positive=True)
N = sp.Symbol("N", integer=True, positive=True, nonzero=True)
alpha = sp.Function("alpha", positive=True, nonzero=True)(n)

numerator = sp.exp(-(alpha**2) * D * t) * sp.sin(alpha * x)
denum = (l * (alpha**2 + L**2) + L) * sp.sin(alpha * l)
c = 2 * S * P_0 * L * sp.Sum(numerator / denum, (n, 1, N))

flux = D * sp.diff(c, x)
flux_at_x0 = flux.subs(x, 0)

cumulative_flux = sp.integrate(flux_at_x0, (t, 0, t)).simplify()
print(cumulative_flux)
```

I now obtain a Piecewise expression:

```
2*D*L*P_0*S*Sum(Piecewise((1/(D*L**2*l*alpha(n)*sin(l*alpha(n)) + D*L*alpha(n)*sin(l*alpha(n)) + D*l*alpha(n)**3*sin(l*alpha(n))) - exp(-D*t*alpha(n)**2)/(D*L**2*l*alpha(n)*sin(l*alpha(n)) + D*L*alpha(n)*sin(l*alpha(n)) + D*l*alpha(n)**3*sin(l*alpha(n))), Ne(D*L**2*l*alpha(n)*sin(l*alpha(n)) + D*L*alpha(n)*sin(l*alpha(n)) + D*l*alpha(n)**3*sin(l*alpha(n)), 0)), (t*alpha(n)/(L**2*l*sin(l*alpha(n)) + L*sin(l*alpha(n)) + l*alpha(n)**2*sin(l*alpha(n))), True)), (n, 1, N))
```

where I would expect:

```
2*L*P_0*S*Sum((1 - exp(-D*t*alpha(n)**2))/((L + l*(L**2 + alpha(n)**2))*alpha(n)*sin(l*alpha(n))), (n, 1, N))
```


I'm sorry if I'm not clear enough, happy to provide more info if need be

**Comment by oscarbenjamin** [comment]
> > I showed how to get that with factor_terms
> 
> I'm not sure I'm following what you mean here
> 
> >

Sorry I thought I showed it but I didn't:
```
In [21]: i = Integral(expr, (t, 0, t_f))

In [22]: i
Out[22]: 
t_f                     
 ⌠                      
 ⎮    ∞                 
 ⎮   ___                
 ⎮   ╲                  
 ⎮    ╲                 
 ⎮    ╱   Fn(n)⋅Ft(t) dt
 ⎮   ╱                  
 ⎮   ‾‾‾                
 ⎮  n = 1               
 ⌡                      
 0                      

In [23]: factor_terms(i)
Out[23]: 
               ∞        
              ___       
t_f           ╲         
 ⌠             ╲        
 ⎮  Ft(t) dt⋅  ╱   Fn(n)
 ⌡            ╱         
 0            ‾‾‾       
             n = 1
```
The OP says that you expect an integral of a sum to be turned into a sum of an integral but I don't see why it is better to have one or the other. It is good though to have a function like `factor_terms` that can manipulate the different forms.

If your point is that the integral should evaluate then that is a very different point that should be stated explicitly.

(It is important to be clear in these communications: reading through all of the thousands of open issues is a lot of work and many people reading will misunderstand the point that you are making.)

**Comment by RemDelaporteMathurin** [comment]
Understood! Apologies, I'm not a regular sympy user and therefore not super familiar with the different terms.

Basically what I would like is to automate (for a paper) the derivation of some analytical solutions of a PDE.

My end goal is to obtain (in a programmatic way) the expression of $R$ below:

<img width="340" alt="image" src="https://github.com/sympy/sympy/assets/40028739/7a5bd41c-0349-4e83-9629-341adbd0a9c6">

I managed to obtain:

$$
2 L P_{0} S \sum_{n=1}^{N} \begin{cases} \frac{1}{D L^{2} l \alpha{\left(n \right)} \sin{\left(l \alpha{\left(n \right)} \right)} + D L \alpha{\left(n \right)} \sin{\left(l \alpha{\left(n \right)} \right)} + D l \alpha^{3}{\left(n \right)} \sin{\left(l \alpha{\left(n \right)} \right)}} - \frac{e^{- D t \alpha^{2}{\left(n \right)}}}{D L^{2} l \alpha{\left(n \right)} \sin{\left(l \alpha{\left(n \right)} \right)} + D L \alpha{\left(n \right)} \sin{\left(l \alpha{\left(n \right)} \right)} + D l \alpha^{3}{\left(n \right)} \sin{\left(l \alpha{\left(n \right)} \right)}} & \text{for}\: D L^{2} l \alpha{\left(n \right)} \sin{\left(l \alpha{\left(n \right)} \right)} + D L \alpha{\left(n \right)} \sin{\left(l \alpha{\left(n \right)} \right)} + D l \alpha^{3}{\left(n \right)} \sin{\left(l \alpha{\left(n \right)} \right)} \neq 0 \\\frac{t \alpha{\left(n \right)}}{L^{2} l \sin{\left(l \alpha{\left(n \right)} \right)} + L \sin{\left(l \alpha{\left(n \right)} \right)} + l \alpha^{2}{\left(n \right)} \sin{\left(l \alpha{\left(n \right)} \right)}} & \text{otherwise} \end{cases}
$$

Which is far from ideal but closer to what I had initially.

For anyone reading, the solution to the initial "integral/summation distribution" problem was to not work with infinite sums but rather a large $N$ number.

I guess all I need to work out now is how to tell sympy that the first condition is always true.

```python
import sympy as sp


x = sp.Symbol("x", real=True, positive=True)
t = sp.Symbol("t", real=True, positive=True)
D = sp.Symbol("D", real=True, positive=True, nonzero=True)
S = sp.Symbol("S", real=True, positive=True, nonzero=True)
P_0 = sp.Symbol("P_0", real=True, positive=True, nonzero=True)
l = sp.Symbol("l", real=True, positive=True, nonzero=True)
L = sp.Symbol("L", real=True, positive=True, nonzero=True)
n = sp.Symbol("n", integer=True, nonzero=True)
N = sp.Symbol("N", integer=True, nonzero=True)
alpha = sp.Function("alpha", real=True, positive=True, nonzero=True)(n)

numerator = sp.exp(-(alpha**2) * D * t) * alpha
denum = (l * (alpha**2 + L**2) + L) * sp.sin(alpha * l)
expr = sp.Sum(numerator / denum, (n, 1, N)) * 2 * S * P_0 * L

cumulative_flux = sp.integrate(expr, (t, 0, t), conds="separate").simplify()
print(cumulative_flux)
print(sp.printing.latex(cumulative_flux))
```

**Comment by oscarbenjamin** [comment]
Ideally the integral would not come out with a Piecewise like that. I don't think the condition is necessary for the integral expression to be correct.

**Comment by RemDelaporteMathurin** [comment]
> Ideally the integral would not come out with a Piecewise like that.

I agree, I must admit I jsut don't know how to solve this. All these symbols are set with nonzero True and positive=True...

**Comment by oscarbenjamin** [comment]
The assumptions don't imply that the condition is False because the sin factor can still be zero. 

I don't see why the integral needs to be specified with that condition at all though.

Likely it comes from meijerg so you could pass `meijerg=False` to `integrate` maybe.
