### ISSUE TITLE
Add integral rewriting for Si/Ci/FresnelS/FresnelC/Ei

### ISSUE THREAD

**Issue by cbm755** [sympy/sympy#26144]
See #26134 for details.  Do this for 

- [x] expint: see https://github.com/sympy/sympy/pull/26135
- [ ] Ci
- [ ] Si
- [ ] FresnelS
- [ ] FresnelC
- [ ] Ei

### How to get started

- take a look at  https://github.com/sympy/sympy/pull/26135
- do something similar

**Comment by sylee957** [comment]
I think that the tasks are done. 
I didn't have chance to check the mathematical things very meticulously 
(often such as conditional rewritings)
However, I do think that it is enough for easy to fix issue.
Whoever may recongize some mathematical error, can come up with another issue

**Comment by cbm755** [comment]
xref #26306
