### ISSUE TITLE
Issue with sympy.physics.quantum.cg.CG returning incorrect values

### ISSUE THREAD

**Issue by dev-aditya** [sympy/sympy#26166]
I have encountered an issue where the `sympy.physics.quantum.cg.CG` function and the `py3nj.clebsch_gordan` function return different results for the same inputs. 
Here is a minimal reproducible example:
```python3
import sympy.physics.quantum.cg as spy
import py3nj

def CGsmpy(j1, m1, j2, m2, j3, m3):
    return float(spy.CG(j1, m1, j2, m2, j3, m3).doit())

def CGpy3nj(j1, m1, j2, m2, j3, m3):
    j1_, m1_, j2_, m2_, j3_, m3_ = int(2*j1), int(2*m1), int(2*j2), int(2*m2), int(2*j3), int(2*m3)
    try:
        return py3nj.clebsch_gordan(j1_, j2_, j3_, m1_, m2_, m3_)
    except ValueError:
        return 0.0

sR = 0.5
print("Calculating Clebsch-Gordan coefficients... \n")
for l in range(14):
    for j in range(14):
        for mi in range(-1, 2):
            for mip in range(-1, 2):
                for mR in range(1, 3, 2):
                    for mRp in range(-1, 3, 2):
                        j1, m1, j2, m2, j3, m3 = l, mi, sR, mR*0.5, j * 0.5, mi + mR*0.5
                        cg_sympy = CGsmpy(j1, m1, j2, m2, j3, m3)
                        cg_py3nj = CGpy3nj(j1, m1, j2, m2, j3, m3)
                        if abs(cg_sympy - cg_py3nj) > 1e-10:
                            print("j1, m1, j2, m2, j3, m3: ", l, mi, sR, mR*0.5, j * 0.5, mi + mR*0.5)
                            print("sympy: ", cg_sympy)
                            print("py3nj: ", cg_py3nj)
                            print("--------------------")
```

For some inputs, such as j1, m1, j2, m2, j3, m3: 4 -1 0.5 0.5 4.0 -0.5, the sympy function returns 0.474341649025257 while the py3nj function returns -0.0. I checked with other libraries too (and Mathematica) and it seems like `sympy` returns wrong values. 

The `python` and `sympy` versions are:
```python3
Python version
3.10.13 (main, Sep 11 2023, 13:44:35) [GCC 11.2.0]
Version info.
sys.version_info(major=3, minor=10, micro=13, releaselevel='final', serial=0)
Sympy version
1.12
```

Could you please look into this?

**Comment by xzdlj** [comment]
I tried the input you provided in **Mathematica** `ClebschGordan[{4, -1}, {0.5, 0.5}, {4, -0.5}]` and received the expected error: 
**"ClebschGordan: ThreeJSymbol[{4,-1},{0.5,0.5},{4,0.5}] is not triangular."** 
This error indicates that the input does not follow the selection rules of the Wigner 3j-Symbol. In other words, it does not satisfy the rules for angular momentum coupling.

Please check [Wigner3j-Symbol](https://mathworld.wolfram.com/Wigner3j-Symbol.html).

I don't think Sympy should be blamed for giving incorrect answers in response to inputs that do not follow the rules.
However, throwing an  exception in such cases might be helpful.

**Comment by dev-aditya** [comment]
@xzdlj  I completely agree! In many software packages, when the selection rules for Wigner 3j-symbols aren't satisfied, they either return zero or raise an error. Opting for either approach can depend on the specific requirements of the calculation. 
The developers must look into this issue.

**Comment by shishir-11** [comment]
@dev-aditya Can you please explain or give more examples on what values were causing you issues . Although I think the issue arises cause 

Inside the celbsch gordon method called with CG class `.doit()` method
```python
    res = (-1) ** sympify(j_1 - j_2 + m_3) * sqrt(2 * j_3 + 1) * \
        wigner_3j(j_1, j_2, j_3, m_1, m_2, -m_3)
``` 

Inside the wigner_3j() function
```python
    m_3 = -m_3

``` 

Meaning m1+m2 = M would be satisfied , the only remaining condition i.e. integer perimeter is not implemented which should probably also fail with your example but is not implemented since it is implied by the other three .
