### ISSUE TITLE
Create a PID controller object

### ISSUE THREAD

**Issue by moorepants** [sympy/sympy#26163]
There are probably many different specialized transfer functions that are often used. For example, a PID controller is a common transfer function. We could have an object that the user passes the gains and the transfer function is created.

```python
import sympy as sm
import sympy.physics.control as cn

KD, KP, KI = sm.symbols('K_D, K_P, K_I', real=True)
s = sm.symbols('s')

Pcont = cn.TransferFunction(KP, 1, s)
Icont = cn.TransferFunction(KI, s, s)
Dcont = cn.TransferFunction(KD*s, 1, s)

PIDcont = cn.Parallel(Pcont, Icont, Dcont)
```

```
In [3]: PIDcont
Out[3]: Parallel(TransferFunction(K_P, 1, s), TransferFunction(K_I, s, s), TransferFunction(K_D*s, 1, s))

In [4]: PIDcont.doit()
Out[4]: TransferFunction(K_I + s*(K_D*s + K_P), s, s)
```

**Comment by shishir-11** [comment]
I've worked PID controllers before so i want to work on this issue . Can you please describe a bit more on what you expect , I don't fully understand the task at hand , Thanks.

**Comment by mohakmalviya** [comment]
> There are probably many different specialized transfer functions that are often used. For example, a PID controller is a common transfer function. We could have an object that the user passes the gains and the transfer function is created.
> 
> ```python
> import sympy as sm
> import sympy.physics.control as cn
> 
> KD, KP, KI = sm.symbols('K_D, K_P, K_I', real=True)
> s = sm.symbols('s')
> 
> Pcont = cn.TransferFunction(KP, 1, s)
> Icont = cn.TransferFunction(KI, s, s)
> Dcont = cn.TransferFunction(KD*s, 1, s)
> 
> PIDcont = cn.Parallel(Pcont, Icont, Dcont)
> ```
> 
> ```
> In [3]: PIDcont
> Out[3]: Parallel(TransferFunction(K_P, 1, s), TransferFunction(K_I, s, s), TransferFunction(K_D*s, 1, s))
> 
> In [4]: PIDcont.doit()
> Out[4]: TransferFunction(K_I + s*(K_D*s + K_P), s, s)
> ```

hello sir i have tried to solve your issue can you please check my PR and guide me if i am on the right path? or do i need to change something else

**Comment by abhiphile** [comment]
Sir, I've one doubt regarding this issue: which of of the following will be a better design?
Design 1 :
```
>>> pid = PIDController(1,0,0,0,s)
>>> pid
PIDController(1,0,0,0,s)
>>> pid.doit()
TransferFunction(s,1,s)
>>> isinstance(pid, TransferFunction)
True
```

Design 2
```
>>> pid = PIDController(1,0,0,0,s)
>>> pid
PIDController(1,0,0,0,s)
>>> pid.doit()
TransferFunction(s,1,s)
>>> isinstance(pid, TransferFunction)
True
```

**Comment by abhiphile** [comment]
Or,  I can think of another implementation also,  rather than making a different class for `PIDController`, we can do it inside `TransferFunction,` eg :
Design 3 :

```
>>> tf = TranferFunction.PIDController(1,0,0,0,s)
TransferFunction(s,1,s)
```

I've used the fourth argument here, which is the Derivative filter time constant, I've taken the reference for this Derivative filter time constant from https://in.mathworks.com/help/control/ug/proportional-integral-derivative-pid-controllers.html

Should I use this `TF` or not?

**Comment by abhiphile** [comment]
@fake-geek can you help me with choosing the best Design style ?
I think the third design will be better approach because by using this one can add more numbers of Controllers of type `TransferFunction`

**Comment by abhiphile** [comment]
@faze-geek can you help me with choosing the best Design style ?
I think the third design will be better approach because by using this one can add more numbers of Controllers of type `TransferFunction`

**Comment by moorepants** [comment]
> Or, I can think of another implementation also, rather than making a different class for PIDController, we can do it inside TransferFunction, eg :

I'm not a fan of this. It is an unusual interface. Having a class for specific types of transfer functions is good design choice, IMHO.

**Comment by abhiphile** [comment]
> > Or, I can think of another implementation also, rather than making a different class for PIDController, we can do it inside TransferFunction, eg :
> 
> I'm not a fan of this. It is an unusual interface. Having a class for specific types of transfer functions is good design choice, IMHO.

And sir , what about the design 1 and design 2 what should I prefer ?
