### ISSUE TITLE
CoercionFailed when integrating exponential functions. But only for some values - why?

### ISSUE THREAD

**Issue by cayobro** [sympy/sympy#26176]
I am using sympy to solve and evaluate integrals. For some values, I get the error about coercion failed:

_raise CoercionFailed("Cannot convert %s of type %s from %s to %s" % (element, type(element), base, self))
sympy.polys.polyerrors.CoercionFailed: Cannot convert (8.48717*_Dummy_6413 + 2.999)/(8.0089*_Dummy_6413 + 2.83) of type <class 'sympy.polys.fields.FracElement'> from RR(_Dummy_6413) to RR[_Dummy_6413]_

Even debugging and going through other issues here in github couldn't help me to find a solution. The integral is bounded, and only using slightly different values works.
This is a minimal example:

`import sympy as sym
maximum_age = 1
a = sym.symbols('a')

# Example 1: these values work
[constant_1, constant_2] = [2.83, 2.99]

# Example 2: these values work
[constant_1, constant_2] = [1, 2.999]

# Example 3: these values don't work
[constant_1, constant_2] = [2.83, 2.999]

# This is the mathematical operation to do
factor_1 = 1 / (constant_1 * a + 1)
factor_2 = constant_2 * sym.exp(-a)
integral_term = sym.integrate(factor_1 * factor_2, (a, 0, maximum_age))`

**Comment by oscarbenjamin** [comment]
The problem is:
```python
In [11]: integrate(2.999*exp(-x)/(2.83*x + 1), (x, 0, 1))
---------------------------------------------------------------------------
CoercionFailed
```
More directly the problem is:
```python
In [18]: Poly([F(8.48717/(8.0089*x + 2.83)), F(0.0)], y, domain=F).clear_denoms()
Out[18]: (1.0⋅x + 0.353356890459364, Poly((8.48717*x + 2.999)/(8.0089*x + 2.83)*y, y, domain='RR(x)'))

In [19]: Poly([F(8.48717/(8.0089*x + 2.83)), F(0.0)], y, domain=F).clear_denoms(convert=True)
---------------------------------------------------------------------------
CoercionFailed
```
This is what happens if QQ is used instead of RR:
```python
In [20]: F2 = QQ.frac_field(x)

In [21]: Poly([F2(8.48717/(8.0089*x + 2.83)), F2(0.0)], y, domain=F2).clear_denoms()
Out[21]: 
⎛    5570104133810989                                                                               ↪
⎜x + ─────────────────, Poly(3900929712011235641763145417/3681104063018271642939543012*y, y, domain ↪
⎝    15763394698685100                                                                              ↪

↪          ⎞
↪ ='QQ(x)')⎟
↪          ⎠

In [22]: Poly([F2(8.48717/(8.0089*x + 2.83)), F2(0.0)], y, domain=F2).clear_denoms(convert=True)
Out[22]: 
⎛    5570104133810989                                                                               ↪
⎜x + ─────────────────, Poly(3900929712011235641763145417/3681104063018271642939543012*y, y, domain ↪
⎝    15763394698685100                                                                              ↪

↪          ⎞
↪ ='QQ[x]')⎟
↪          ⎠
```
So the problem seems to be in `clear_denoms`. When the domain is `RR(x)` is does not extract the polynomial denominator properly.

The problem seems to be this code:
https://github.com/sympy/sympy/blob/0fef9fb5da57ab3ae58a7cbd4f63981f243e2747/sympy/polys/densetools.py#L1199-L1208
It assumes that multiplying by the lcm of the denominator will give a rational function without polynomia denominator but for an inexact domain like `RR` it is possible that the denominators do not cancel completely due to rounding error. Actually the error looks much bigger than a typical rounding error:
```
1201 	        common = K1.lcm(common, K0.denom(c))
1202 	
1203 	    if not K1.is_one(common):
1204 	        f = dup_mul_ground(f, common, K0)
1205 	
1206 ->	    if not convert:
1207 	        return common, f
1208 	    else:
1209 	        return common, dup_convert(f, K0, K1)
1210 	
1211 	
(Pdb) p f
[(8.48717*x + 2.999)/(8.0089*x + 2.83), 0.0]
(Pdb) p common
x + 0.353356890459364
```
It would be worth trying to understand how the error is so large but in any case `dup_clear_denoms` should be written differently to handle inexact domains. Rather than just multiplying by the LCM of the denominators and hoping that it cancels it should separate the numerator explicitly and multiply each numerator by the lcm divided by the denominator.

Actually that is possibly a more efficient approach for exact fields including `QQ` and `QQ(x)` etc as well.

This seems to be the fix:
```diff
diff --git a/sympy/polys/densetools.py b/sympy/polys/densetools.py
index b56a4a773b..ecd1c98c3b 100644
--- a/sympy/polys/densetools.py
+++ b/sympy/polys/densetools.py
@@ -1199,13 +1199,20 @@ def dup_clear_denoms(f, K0, K1=None, convert=False):
     for c in f:
         common = K1.lcm(common, K0.denom(c))
 
-    if not K1.is_one(common):
-        f = dup_mul_ground(f, common, K0)
+    if K1.is_one(common):
+        if not convert:
+            return common, f
+        else:
+            return common, dup_convert(f, K0, K1)
+
+    # Use quo rather than exquo to handle inexact domains by discarding the
+    # remainder.
+    f = [K0.numer(c)*K1.quo(common, K0.denom(c)) for c in f]
 
     if not convert:
-        return common, f
+        return common, dup_convert(f, K1, K0)
     else:
-        return common, dup_convert(f, K0, K1)
+        return common, f
 
 
 def _rec_clear_denoms(g, v, K0, K1):
```

**Comment by oscarbenjamin** [comment]
> It would be worth trying to understand how the error is so large

Actually the error is not as big as I thought:
```python
In [5]: monic((8.48717*x + 2.999))
Out[5]: 1.0⋅x + 0.353356890459364

In [6]: monic(8.0089*x + 2.83)
Out[6]: 1.0⋅x + 0.353356890459364

In [7]: cancel((8.48717*x + 2.999)/(8.0089*x + 2.83))
Out[7]: 
8.48717⋅x + 2.999
─────────────────
 8.0089⋅x + 2.83 
```

**Comment by oscarbenjamin** [comment]
In any case the issue can be closed with the diff above and a test for `clear_denoms`.

**Comment by shishir-11** [comment]
@oscarbenjamin Can you please tell me the reason for interchanging the return statments in the `dup_clear_denoms` ?
