### ISSUE TITLE
MatrixSymbol with subscript do not produce valid latex with latex()

### ISSUE THREAD

**Issue by kompre** [sympy/sympy#26198]
Hello,

`MatrixSymbol` defined with a subscript will not get correctly "escaped" when converted to a latex string with the `latex()` method: it will produce a double subscript which is not correct latex syntax and would raise an error when rendering the latex object. 

An `IndexedBase` with subscript instead get correctly enclosed in `{}` when the `latex()` method is called.

- let's define two symbol with subscript and print them to a notebook:

```py
from sympy import *
from sympy.tensor.array.expressions import ArraySymbol
init_printing()

Y_a = symbols('Y_a', cls=IndexedBase)
Z_a = MatrixSymbol('Z_a', *(3,1))

print(latex(Y_a))
Y_a
```
![image](https://github.com/sympy/sympy/assets/11796345/9ff62735-7983-49bc-bcb1-050b7a0bc49c)

```py
print(latex(Z_a))
Z_a
```
![image](https://github.com/sympy/sympy/assets/11796345/927cd913-692b-410b-9997-d6cca4ad55c0)

- with a subscript, the IndexBase get `{}` and works fine:

```py
print(latex(Y_a[1]))
Y_a[1]
```
![image](https://github.com/sympy/sympy/assets/11796345/976eda85-265e-4c79-83d7-faa8ea59390d)

-  with a subscript, the MatrixSymbiol do NOT get `{}` and cannot render:

```py
print(latex(Z_a[1]))
Z_a[1]
```

![image](https://github.com/sympy/sympy/assets/11796345/3067c21e-d3df-4b92-b7f0-1f486e5961a8)

`MatrixSymbol` should get "escaped" like IndexedBase with curly braces.

**Comment by sylee957** [comment]
I didn’t know about the usage of matrix symbols with subscripts, however, if indexedbase does already, let do it

**Comment by kompre** [comment]
> I didn’t know about the usage of matrix symbols with subscripts, however, if indexedbase does already, let do it

Eh, mathematician probably will find that abhorrent, but I'm just a simple engineer making use of the available to me. I even use units in my calculations! 😂

I find matrix object convenient list-like container that looks good when rendered in a notebook, and have useful functions (e. g. Hadamard product). Indeed most of the time I just use one dimensional matrix (I'm kinda bothered by the fact that even a 1 dimensional matrix still need 2 indices to access a single element, but oh well).

IndexedBase will probably be more adapt to my use case, but since they are commutative, multiplication usually get messed up when I subs the actual matrix to the symbol.

By the way, ArraySymbol works like IndexedBase, but you can't use matrix's function on them like transpose or Hadamard product.

**Comment by sylee957** [comment]
I think that the problem is SymPy sticks to subscript for matrix and array indexes. There can be alternative notations more appropriate for subscripted symbol, for example, $X_a[i, j]$, however, I don't think that SymPy provides very general options to customize printing to everything, because we don't know the expectation from SymPy users. 
However, you can always subclass printers to do that if you need to.
