### ISSUE TITLE
Methods that do not exist in `SATSolver`

### ISSUE THREAD

**Issue by haru-44** [sympy/sympy#26226]
Do `self.simple_compute_conflict` and `self.simple_clean_clauses` exist?
I think `self._simple_compute_conflict` and `self._simple_clean_clauses` are correct?

https://github.com/sympy/sympy/blob/680fb21363e1ea685d6fc868d15069d80ac0c97f/sympy/logic/algorithms/dpll2.py#L122-L124

**Comment by shishir-11** [comment]
I read a bit more through the code and there is a block of comment
```python
            # Note: Uncomment this if/when clause learning is enabled
            #self.update_functions.append(self._vsids_decay)
``` 
I believe there are no tests added and this functionality was never updated .
