### ISSUE TITLE
Incorrect result while expanding `Ci(x)` around -infinty.

### ISSUE THREAD

**Issue by abhiphile** [sympy/sympy#26257]
I got this result while expanding `Ci(x)` for -inf
```
>> Ci(x).series(x,-oo)
I*pi - (-6/x**3 + 1/x + O(-1/x**7, (x, -oo)))*cos(x)/x + (24/x**4 - 2/x**2 + 1 + O(-1/x**7, (x, -oo)))*sin(x)/x
```
while on wolfram it has an extra O(-1/x**7) term with it.
![image](https://github.com/sympy/sympy/assets/140839576/7b446bb1-f78a-4b2f-a9c2-6da1fa1a3596)

**Comment by haru-44** [comment]
The reason why the 7th order term appears is because it is handled as such in `TrigonometricIntegral`, but I don't know what the intent is.

https://github.com/sympy/sympy/blob/432f2e789b64e01cafd173051223ae8abd90ae1f/sympy/functions/special/error_functions.py#L1797-L1799

**Comment by abhiphile** [comment]
https://github.com/sympy/sympy/pull/26233 This PR introduced the series expansion of `Ci(x)` around `-oo`.

**Comment by anutosh491** [comment]
> while on wolfram it has an extra O(-1/x**7) term with it.

I don't think that matters much. Finally we would like to pay attention to the **expanded** form. For eg 
```
>>> sin(1/x).series(x, oo)
1/(120*x**5) - 1/(6*x**3) + 1/x + O(x**(-6), (x, oo))
>>>
>>> Ci(x).series(x, -oo)
I*pi - (-6/x**3 + 1/x + O(-1/x**7, (x, -oo)))*cos(x)/x + (24/x**4 - 2/x**2 + 1 + O(-1/x**7, (x, -oo)))*sin(x)/x
>>> _.expand()
24*sin(x)/x**5 + 6*cos(x)/x**4 - 2*sin(x)/x**3 - cos(x)/x**2 + sin(x)/x + I*pi + O(x**(-8), (x, -oo))
```
Here what's wrong is the `O(x**(-8), (x, -oo))` term. We should have a `O(x**(-6), (x, -oo))` here and that would do it.
