### ISSUE TITLE
Incorrect Limit Calculation for $\lim_{x\rightarrow +\infty} \frac{\left( 1+\frac{1}{x} \right) ^{x^2}}{e^x}$

### ISSUE THREAD

**Issue by jamiu99** [sympy/sympy#26254]
# Incorrect Limit Calculation in SymPy

## Description

When computing the limit of the function ( $\left(1 + \frac{1}{x}\right)^{x^2}$ ) divided by ( $e^x$ ) as ( $x$ ) approaches infinity, SymPy returns 1, which contradicts the expected result of ( $e^{-\frac{1}{2}}$ ).

## Steps to Reproduce

The following code was used to calculate the limit:

```python
import sympy as sp
x = sp.symbols('x')
function = (1 + 1/x)**(x**2)
limit_exp = sp.limit(function / sp.exp(x), x, sp.oo)
print(limit_exp)
```

The expected result is $e^{-\frac{1}{2}}$, which is confirmed by standard limit calculation techniques as shown below:

$$
\lim_{x\rightarrow +\infty} \frac{\left( 1+\frac{1}{x} \right) ^{x^2}}{e^x}=\lim_{x\rightarrow +\infty} \frac{e^{x^2\ln \left( 1+\frac{1}{x} \right)}}{e^x}
= e^{\lim_{x\rightarrow +\infty} x^2\ln \left( 1+\frac{1}{x} \right) -x}\mathop {=}^{x=\frac{1}{t}}e^{\lim_{t\rightarrow 0^+} \frac{\ln \left( 1+t \right) -t}{t^2}}= e^{-\frac{1}{2}}
$$

## Expected Behavior

The limit should evaluate to $e^{-\frac{1}{2}}$ .

## Actual Behavior

SymPy evaluates the limit to 1.

## Possible Solution

This might be an issue with the limit evaluation algorithm that fails to handle this specific case correctly.

## Additional context

The correct result was confirmed using MATLAB, which suggests that there might be a bug in SymPy's algorithm for limit evaluation.

- SymPy version: 1.12
- Python version: 3.10.13

I would appreciate it if this issue could be looked into and addressed accordingly. Thank you for your assistance and for the continuous development of SymPy.

**Comment by oscarbenjamin** [comment]
This is already fixed on master since 5432ba1ee1d04fc3c967c45bc517cd347fe7c2bb from gh-25893 which also includes a test for this exact case.

Thanks for reporting.
