### ISSUE TITLE
Unable to find the point(s) in the sine path that is/are nearest to a fixed point

### ISSUE THREAD

**Issue by Zhang-Junzhi** [sympy/sympy#26253]
Say, there is a fixed point (15, 3).
I want to find the point(s) in the sine path that is/are nearest to (15, 3).
Here is the incomplete code, showing only the very first step to reach the answer.

```
import sympy as sp
x = sp.Symbol("x")
f = (15 - x) ** 2 + (3 - sp.sin(x)) ** 2
df = sp.diff(f, x)
s = sympy.solve(df, x) #got NotImplementedError
...
```

It got a NotImplementedError:

> No algorithms are implemented to solve equation 2*x - 2*(1 - tan(x/2)**2)*(3 - 2*tan(x/2)/(tan(x/2)**2 + 1))/(tan(x/2)**2 + 1) - 30

It's undoutedly differentiable, though I don't know how to do it either.

What do you think about it? How to implement the solve?

**Comment by smichr** [comment]
`nsolve(df,15) -> 14.4235...`

**Comment by Zhang-Junzhi** [comment]
> `nsolve(df,15) -> 14.4235...`

Good point. I wasn't aware of nsolve. Thanks.
