### ISSUE TITLE
convert_to duplicates units when mixing floating point and rationals

### ISSUE THREAD

**Issue by LQ1234** [sympy/sympy#26263]
```python
from sympy.physics.units import *
from sympy import *

convert_to(sqrt(meter ** 2 + meter ** 2.0), [meter])
# gives sqrt(m ** 2 + m ** 2.0) * m instead of m
```

**Comment by LQ1234** [comment]
Looks like get_total_scale_factor in convert_to assumes that a unit cannot be factored out of an `Add` while UnitSystem.get_dimensional_expr assumes that the unit of the first argument can be factored out of the whole expression:

```python
    def get_total_scale_factor(expr):
        # print("getting scale factor", expr)
        if isinstance(expr, Mul):
            return reduce(lambda x, y: x * y,
                [get_total_scale_factor(i) for i in expr.args])
        elif isinstance(expr, Pow):
            return get_total_scale_factor(expr.base) ** expr.exp
        elif isinstance(expr, Quantity):
            return unit_system.get_quantity_scale_factor(expr)
        return expr
```
```python
    def get_dimensional_expr(self, expr):
        from sympy.physics.units import Quantity
        if isinstance(expr, Mul):
            return Mul(*[self.get_dimensional_expr(i) for i in expr.args])
        elif isinstance(expr, Pow):
            return self.get_dimensional_expr(expr.base) ** expr.exp
        elif isinstance(expr, Add):
            return self.get_dimensional_expr(expr.args[0])
        ...
```
Easiest way to fix this is to probably make get_dimensional_expr return 1 for all Adds.

**Comment by smichr** [comment]
Perhaps an error should be raised when using a non-rational exponent with a unit as base? (But maybe [not](https://physics.stackexchange.com/questions/13245/dimensional-analysis-restricted-to-rational-exponents).)

Should `m**2 + m**2.0` combine as `m**2.0` (where `m` is for 'meters')?

**Comment by LQ1234** [comment]
I think that either interpretation is fine, since technically speaking separating the two preserves precision but combining the two might be convenient. `convert_to` including both is definitely wrong though.

**Comment by LQ1234** [comment]
The underlying problem is not that convert_to should treat rational / floating point exponents differently, but rather that the implementation of convert_to treats Adds inconsistently causing the factor to be duplicated.

**Comment by Henrique-S123** [comment]
Hi, I would like to work on this issue. Can you clarify what should be the correct output of the following line?
```
convert_to(sqrt(meter ** 2 + meter ** 2.0), [meter])
```
