### ISSUE TITLE
The integral of asinh(x) from -1 to 1 yields an incorrect result.

### ISSUE THREAD

**Issue by ninthseason** [sympy/sympy#26286]
The integral of asinh(x) from -1 to 1 should be zero because asinh(x) is an odd function. However, the result calculated by sympy is not zero.
![image](https://github.com/sympy/sympy/assets/29861280/d0563ee5-94ec-49db-b193-0e4ace7e5d22)
However, the results obtained using other integration limits are correct.
![image](https://github.com/sympy/sympy/assets/29861280/861a3a95-6810-462d-8085-65e4134332d7)
![image](https://github.com/sympy/sympy/assets/29861280/3703d4f0-70cf-4b5f-990a-16ffa63a241f)

**Comment by fetchinson** [comment]
The first result you got is also zero.

**Comment by ninthseason** [comment]
You're right, I made a simple calculation error. Thank you.
