### ISSUE TITLE
`as_coeff_exponent`  method does not work as intended

### ISSUE THREAD

**Issue by arnabnandikgp** [sympy/sympy#26305]
we have 
```
In [15]: #expected
In [16]: ((x)**(-S(1)/3)).as_coeff_exponent(x)
Out[16]: (1, -1/3)
In [17]: ((x)**(-S(1)/2)).as_coeff_exponent(x)
Out[17]: (1, -1/2)
```
but 
```
In [14]: ((1/x)**(S(1)/3)).as_coeff_exponent(x)
Out[14]: 
⎛    ___   ⎞
⎜   ╱ 1    ⎟
⎜3 ╱  ─ , 0⎟
⎝╲╱   x    ⎠
In [19]: (sqrt(1/x)).as_coeff_exponent(x)
Out[19]: 
⎛    ___   ⎞
⎜   ╱ 1    ⎟
⎜  ╱  ─ , 0⎟
⎝╲╱   x    ⎠
```

**Comment by smichr** [comment]
`var('x',positive=True);((1/x)**(S(1)/3)).as_coeff_exponent(x)` gives `(1, -1/3)`. Is the transofrmation valid if `x` is negative? zero?

**Comment by arnabnandikgp** [comment]
>var('x',positive=True);((1/x)**(S(1)/3)).as_coeff_exponent(x) gives (1, -1/3). Is the transofrmation valid if x is negative? zero?

ya that may be an area to ponder upon but according to the comment in the code 
https://github.com/sympy/sympy/blob/8117d24ac05a6b5a8419096caaaba0fa171cf422/sympy/core/expr.py#L3499-L3502
which says that x can be any symbolic expression, so maybe we should expect `(1, -1/3)` in every conditon.

**Comment by smichr** [comment]
`root(1/y,n) != 1/root(y,n)` when `y` is negative.
```python
>>> q
((1/y)**(1/3), y**(-1/3))
>>> [i.subs(y,-2).n(3) for i in q]
[0.397 + 0.687*I, 0.397 - 0.687*I]
```

**Comment by smichr** [comment]
> So does the current implementation then require change for the case when x is positive as you we (you too pointed out) can see that this issue holds when the x is positive.

I tried to point out that the issue does *not* hold when x is known to be positive:
```python
>>> y=var('y'); x=var('x',positive=True)
>>> (1/x)**y
x**(-y)
>>> _.as_coeff_exponent(x)
(1, -y)
```
