### ISSUE TITLE
failed to simplify sqrt on large number

### ISSUE THREAD

**Issue by auntyellow** [sympy/sympy#26317]
This is with sympy 1.12 (Python 3.8.10)
```
>>> sqrt(2663901769)
51613
>>> sqrt(1001885125670250202210728125403128548905806811601)
sqrt(1001885125670250202210728125403128548905806811601)
```
expected `51613*sqrt(376096873138962280636080063132060838729)` because there is a square factor `51613`:
```
>>> factorint(1001885125670250202210728125403128548905806811601)
{7: 1, 431: 1, 2459: 1, 6599: 1, 51613: 2, 86113: 1, 431036329: 1, 206968932994541: 1}
```
This causes incorrect comparison of two sqrt numbers:
```
>>> 51613*sqrt(376096873138962280636080063132060838729) == sqrt(1001885125670250202210728125403128548905806811601)
False
```
expected `True` because:
```
>>> 51613**2*376096873138962280636080063132060838729 == 1001885125670250202210728125403128548905806811601
True
```
I guess SymPy first simplify on both sides then do comparison, instead of square both sides: a = b iif sgn(a) = sgn(b) and a^2 = b^2.

**Comment by oscarbenjamin** [comment]
In SymPy `==` is for structural equality and is not expected to resolve all mathematical equivalences:
```python
In [1]: eq = Eq(51613*sqrt(376096873138962280636080063132060838729), sqrt(1001885125670250202210728125403128548905806811601))

In [2]: eq
Out[2]: 51613⋅√376096873138962280636080063132060838729 = √1001885125670250202210728125403128548905806811601

In [3]: eq.simplify()
Out[3]: True
```
There are other ways to do this, depending on what your requirements are but it is not expected that `==` would resolve this.

**Comment by auntyellow** [comment]
> `In [1]: eq = Eq(51613*sqrt(376096873138962280636080063132060838729), sqrt(1001885125670250202210728125403128548905806811601))`

@oscarbenjamin thanks for help. however, why `simplify` doesn't work on RHS?
```
>>> a = sqrt(1001885125670250202210728125403128548905806811601)
>>> a
sqrt(1001885125670250202210728125403128548905806811601)
>>> type(a)
<class 'sympy.core.power.Pow'>
>>> a.simplify()
sqrt(1001885125670250202210728125403128548905806811601)
```

**Comment by smichr** [comment]
Factoring a large number can be very expensive, so there is probably a limit made for auto-factoring arguments of `sqrt`. You can force a factoring with 
```python
>>> a.replace(lambda x:x.is_Integer, lambda x:factorint(x, visual=True))
51613*sqrt(376096873138962280636080063132060838729)
```

**Comment by auntyellow** [comment]
I see. I also found https://en.wikipedia.org/wiki/Square-free_integer#Square-free_factorization mentioned that

> The use of the square-free factorization of integers is limited by the fact that its computation is as difficult as the computation of the prime factorization.

So sometimes I should use `Eq(lhs, rhs).simplify()` instead.
