### ISSUE TITLE
wigner modifications

### ISSUE THREAD

**Issue by smichr** [sympy/sympy#26323]
Rather than convert to SymPy types, let `wigner_3j` (and perhaps `_eval_wignerd`) deal with raw Python types:
```python
    def _int_or_halfint(i):
        if isinstance(i, Rational):
            if i.q==2:
                return i.p/i.q
            if i.q==1:
                return i.p
        elif isinstance(i,Float):
            i=float(i)
        elif type(i) is int:
            return i
        if type(i) is float:
            if i.is_integer()
                return int(i)
            if (2*i).is_integer():
                return i
        raise ValueError("expecting integer or half-integer, got %s" % i)

>>> [_int_or_halfint(i) for i in (1/2, 2/2, 1, S(1), S.Half, Float(1), Float(1.5))]
[0.5, 1, 1, 1, 0.5, 1, 1.5]
>>> set([type(i) for i in _])
{float, int}
```
This could be used like this in `wigner_3j`:
```python
j_1, j_2, j_3, m_1, m_2, m_3 = [_int_or_halfint(i) for i in [j_1, j_2, j_3, m_1, m_2, m_3]]
```

**Comment by shishir-11** [comment]
Also it might be unrelated to this issue but in the same file, 

In the wigner_3j functions
`m_3 = -m_3`

In the clebsch_gordon method 
` res = (-1) ** sympify(j_1 - j_2 + m_3) * sqrt(2 * j_3 + 1) *  wigner_3j(j_1, j_2, j_3, m_1, m_2,-m_3)`

Is it correct m should a new issue be opened for it .

**Comment by smichr** [comment]
> In the wigner_3j functions

I noticed that, too, and having spent more time looking at how `wigner_3j` works, believe that it is not necessary in `wigner_3j`. Look at how it is used after it is defined:

![image](https://github.com/sympy/sympy/assets/90703/6185c293-389e-483e-8cd8-f7d51aaf2e8d)

It is used in `abs` and then both positive and negative forms are used when selecting factorials (which are already pre-computed). So it has no purpose in either case. It should be remove from `wigner_3j`.
