### ISSUE TITLE
Parse units in LaTeX expression

### ISSUE THREAD

**Issue by mxrcooo** [sympy/sympy#26332]
Is there a way to use `parse_latex` for a LaTeX expression that includes units? 

Let's say I have the diameter of a sphere in meters: `d=4\mathrm{~m}`. `parse_latex` fails with parsing this string because it doesn't understand mathrm. Is there any way to detect units having this mathrm format and convert it to a sympy expression?

**Comment by samithkavishke** [comment]
at the moment sympy latex parser does not support `mathrm`

**Comment by mxrcooo** [comment]
Found a workaround for now if anyone is interested:

You can replace all mathrm occurrences with a placeholder variable that has a subscript with the content of mathrm (note that characters like ~ also have to be replaced). So in my case `\mathrm{~m} -> A_{-m}`. Parsing this will work and also keeps the (in my case unit) in place in case you want to recover the mathrm command later on.
