### ISSUE TITLE
physics.vector documentation error (typo on dcm example)

### ISSUE THREAD

**Issue by jskoun** [sympy/sympy#26345]
In [physics.vector](https://docs.sympy.org/latest/modules/physics/vector/vectors.html#vector-calculus-in-physics-vector) documentation, error in the DCM matrix explanation:

_From the above documentation page:_
This code: `N.dcm(A)` gives the dcm ${}^A\mathbf{C}^N$ <-- should be ${}^N\mathbf{C}^A$

_From_ `sympy/physics/vector/frame.py` _line 505_:
If ``B.dcm(A)`` is called, it means the "direction cosine matrix of B rotated relative to A". This is the matrix ${}^B\mathbf{C}^A$ shown in the following relationship: [...]

_please excuse the poor form of this issue, and do delete if it is placed in the wrong section. I am not familiar with issue reporting_

**Comment by smichr** [comment]
Please confirm that the "should be" that I added in the OP is correct.

**Comment by jskoun** [comment]
> Please confirm that the "should be" that I added in the OP is correct.

Yes that was what I would expect.  Also found in this [book ](https://moorepants.github.io/learn-multibody-dynamics/learnmultibodydynamics.pdf) at page 61.

**Comment by smichr** [comment]
# The full context is:

If we want to do vector multiplication, first we have to define and orientation. The orient method of ReferenceFrame provides that functionality.
```
>>> A.orient(N, 'Axis', [x, N.y])
```
If we desire, we can view the DCM between these two frames at any time. This can be calculated with the dcm method. This code: N.dcm(A) gives the dcm ${}^A\mathbf{C}^N$.

This orients the A frame relative to the N frame by a simple rotation around the Y axis, by an amount x.

# suggested rewrite

If we want to do vector multiplication, first we have to define and orientation. The orient method of ReferenceFrame provides that functionality.
```
>>> A.orient(N, 'Axis', [x, N.y])
```
This orients the A frame relative to the N frame by a simple rotation around the Y axis, by an amount x.  We can view the DCM between these two frames at any time with the dcm method: A.dcm(N) gives the dcm ${}^A\mathbf{C}^N$.

**Comment by moorepants** [comment]
Yes, `N.dcm(A)`  is the ${}^N\mathbf{C}^A$ in this relationship:

$$
\begin{split}\begin{bmatrix}
  \hat{n}_x \\
  \hat{n}_y \\
  \hat{n}_z
\end{bmatrix}
=
{}^N\mathbf{C}^A
\begin{bmatrix}
  \hat{a}_x \\
  \hat{a}_y \\
  \hat{a}_z
\end{bmatrix}\end{split}
$$

**Comment by moorepants** [comment]
the suggested rewrite is good
