### ISSUE TITLE
`expand_power_exp()` Has No Effect In Cases For Which It Should

### ISSUE THREAD

**Issue by ricopicone** [sympy/sympy#26370]
This is the example from the simplification tutorial:

```python
x = sp.symbols("x", positive=True)
a, b = sp.symbols("a, b", real=True)
sp.expand_power_exp(x**(a + b))
```

This returns $x^a x^b$, as expected. However, as the tutorial points out, the identity $x^{a+b} = x^a x^b$ holds for $x, a, b \in \mathbb{C}$. So why doesn't the following work?

```python
x, a, b = sp.symbols("x, a, b", complex=True)
sp.expand_power_exp(x**(a + b))
```

This returns $x^{a + b}$; that is, it doesn't expand as it should. I don't think this has to do with an automatic simplification, but perhaps I'm wrong.

**Comment by smichr** [comment]
The docstring of `expand_power_exp` also indicates
```
    >>> expand_power_exp(x**(y + 2))
    x**(y + 2)

    If ``x = 0`` the value of the expression depends on the
    value of ``y``; if the expression were expanded the result
    would be 0. So expansion is only done if ``x != 0``:

    >>> expand_power_exp(Symbol('x', zero=False)**(y + 2))
    x**2*x**y
```
Since we don't know if the base is zero or not we don't do the expansion. But if we know `x` is not zero then it is ok:
```python
>>> a, b = symbols("a, b", complex=True)
>>> x = var('x', zero=False)
>>> expand_power_exp(x**(a+b))
x**a*x**b
```

**Comment by ricopicone** [comment]
Ah, excellent. Thank you @smichr!
