### ISSUE TITLE
Questions about Copilot + Open Source Software Hierarchy

### ISSUE THREAD

**Issue by liaochris** [sympy/sympy#26397]
Hi! My name is Chris and I'm writing a thesis on Open Source Software. I'm trying to collect/validate my data and I have two questions for the maintainers of this project.
1) Did you receive free github copilot access on June 2022?
2) My thesis is especially focused on understanding hierarchical structures. Would it be possible to share a list of individuals in this project with triage/write/maintain/admin access in this project? I understand this may be confidential information, so please feel free to share it with [chrisliao@uchicago.edu ](chrisliao@uchicago.edu)

Happy to chat further if you have questions, and thank you for your time!

**Comment by 1e9abhi1e10** [comment]
Hey Chris, it would be more beneficial if you posted this question on the sympy mailing list.

**Comment by oscarbenjamin** [comment]
> it would be more beneficial if you posted this question on the sympy mailing list.

Agreed. We have a lot of open issues and there is no need to keep this open.
