### ISSUE TITLE
Mod(-x, 2) evaluates to Mod(x,2)

### ISSUE THREAD

**Issue by toewen** [sympy/sympy#26410]
The problem occurs with python 3.11.6 and sympy 1.12.

```
import sympy as sp
x = sp.Symbol("x")

sp.Mod(-x, 2)
```
results in `Mod(x, 2)`, which would be correct if x is an integer but not otherwise.

Interestingly, `sp.Mod(-x, 2.0)` does not show this behavior.

**Comment by oscarbenjamin** [comment]
I believe this is already fixed in master.

**Comment by toewen** [comment]
That was a quick response :)

I will check again with master

**Comment by toewen** [comment]
Works as expected now, thanks!

**Comment by oscarbenjamin** [comment]
I think this was fixed by gh-26031
