### ISSUE TITLE
Extra `\cdot` in LaTeX output for `Mul` between a numeric power and a polynomial with numeric coefficient since SymPy 1.10

### ISSUE THREAD

**Issue by utensil** [sympy/sympy#26430]
For an `Mul` between a numeric power and a polynomial with numeric coefficient

`Mul(Pow(Symbol('x', real=True), Integer(2)), Add(Mul(Integer(2), Symbol('x', real=True)), Integer(1)))`

In SymPy 1.9, it gives

$$
\displaystyle x^{2} \left(2 x + 1\right)
$$

Since SymPy 1.10, it gives:

$$
\displaystyle x^{2} \cdot \left(2 x + 1\right)
$$

(LaTeX directly copied from MathJax output)

See https://nbviewer.org/github/pygae/galgebra/blob/fix-494/test/issues/494.ipynb for code of the minimal reproduction, see https://github.com/pygae/galgebra/issues/494 for the original issue.

Probable cause:

#21101 matches LaTeX for a pattern of between numbers and add a `\cdot`, but it seems to be also matching an `Mul` between a numeric power and a polynomial with numeric coefficient .

**Comment by utensil** [comment]
@iam-abbas @namannimmo10 Can you help assessing if #21101 is the cause and the possible fix?

This is not an issue for e.g. real numbers, but `\cdot` means scalar product rather than geometric product between vectors in geometric algebra, so the produced LaTeX formula would be a bug for GAlgebra.

**Comment by ccatrett** [comment]
It seems that #21101 is a possible issue. It looks like `_between_two_numbers_p` is comparing the exponent of the monomial with the coefficient of the polynomial and inserting a \cdot when it shouldn't be.

**Comment by utensil** [comment]
I'll close this when I updated the changed log to say that this is fixed in upstream.
