### ISSUE TITLE
Counter intuitive result when adding Relational and numbers

### ISSUE THREAD

**Issue by Juanlu001** [sympy/sympy#2646]
I was playing with Relational objects and found this:

```
In [1]: Eq(x, 1)
Out[1]: x = 1

In [2]: _ - 1
Out[2]: -1 + x = 1
```

I expected the `-1` to affect both the left hand and the right hand side. Anyway this result makes no sense, so if not giving `Eq(x, 1) - 1 == Eq(x - 1, 0)`, perhaps the operation should not be allowed at all.

**Comment by jcrist** [comment]
Closing, as printer has been fixed, and `Eq` represent equality, not equations. Current master (0.7.7 dev):

```
>>> Eq(x, 1)
Eq(x, 1)
>>> pprint(_)
x = 1
>>> Eq(x, 1) + 1
Eq(x, 1) + 1
>>> pprint(_)
1 + (x = 1)
```

**Comment by Juanlu001** [comment]
Great! Can you point to the specific PR @jcrist?

**Comment by jcrist** [comment]
Fixed by #8566

**Comment by asmeurer** [comment]
Did we decide that we do want to allow such expressions? What is the meaning of `1 + Eq(x, y)`?

**Comment by jcrist** [comment]
From reading the above, (and the other duplicate issues), it looks like all that was decided was that the printer should be changed. Since symbols have no types, one could reasonably (or maybe unreasonably) say that `a + Eq(x, y)` is valid, if `a` represents a boolean value.

**Comment by toolforger** [comment]
I'm confused as well.
I'm seeing two approaches mentioned:
1) `1 + Eq(whatever)` means that all free variables `v` in `whatever` are replaced by `v + 1`. Which gets less useful with each variable added; one could fix that with making the API require a dict. However, it would be easier to simply use `Eq(...).subs(...)`.
2) `1 + Eq(a, b)` means `Eq(a + 1, b + 1)`. I'm wondering what that's good for; sure you can transform equations with that, but then `1 + Eq(a - 1, b - 1)` won't give you `Eq(a, b)`, it will give you `Eq(1 + a - 1, 1 + b - 1)`, and you still need to simplify to get `Eq(a, b)` - which one could also arrive at by simply simplifying the expression.

So all in all I'm confused about what the purpose of adding anything to `Eq` should be.
Maybe we should take this discussion to the mailing list.

**Comment by asmeurer** [comment]
There's also

3) Eq(a, b) is True if a == b and False if a != b, and we define addition on booleans (which we don't by the way).

**Comment by jcrist** [comment]
Well, either way, the issue above seemed to decide that the reasonable path forward was to fix the printers to surround relationals in parens inside `Add`s, and the printer was fixed. If we want to continue discussion about including relationals inside general expression trees, I suggest we open a new issue.

**Comment by toolforger** [comment]
The question is whether fixing the printer is the right thing to do in 
the first place; possibly the best way forward would be to revert this 
and instead throw an exception. (And apologize to the person whose 
effort in fixing the printer was wasted.)
