### ISSUE TITLE
Plotting with Sympy's inbuilt TextBackend doesn't seem to be working

### ISSUE THREAD

**Issue by SamLubelsky** [sympy/sympy#26481]
```from sympy import symbols
from sympy.plotting import plot
x = symbols('x')
plot(x, (x, 0, 5))

Traceback (most recent call last):
  File "c:\Users\sammy\gsoc\sympy\test.py", line 4, in <module>
    plot(x, (x, 0, 5))
  File "c:\Users\sammy\gsoc\sympy\sympy\plotting\plot.py", line 408, in plot
    plots.show()
  File "c:\Users\sammy\gsoc\sympy\sympy\plotting\backends\textbackend\text.py", line 21, in show
    textplot(ser.expr, ser.start, ser.end)
  File "c:\Users\sammy\gsoc\sympy\sympy\plotting\textplot.py", line 161, in textplot
    for line in textplot_str(expr, a, b, W, H):
  File "c:\Users\sammy\gsoc\sympy\sympy\plotting\textplot.py", line 53, in textplot_str
    a = float(a)
        ^^^^^^^^
TypeError: float() argument must be a string or a real number, not 'complex'
```

Note: I think you will only be able to reproduce this if you don't have matplotlib installed, or else it will just use matplotlib.

**Comment by moorepants** [comment]
You can force the backend to be text with `plot(..., backend='text')`.

**Comment by oscarbenjamin** [comment]
@SamLubelsky did you come across this as a result of running the tests/doctests in some way?

I recently came across this as well with `pytest --doctest-only sympy/plotting` when matplotlib was not installed. I have fixed that in https://github.com/sympy/sympy/pull/26451 to at least skip the test when matplotlib is not installed but if this gets fixed then the test should not be skipped.

**Comment by SamLubelsky** [comment]
I came across it while I was trying to fix some of the issues shown [here](https://github.com/sympy/sympy/issues/19996) that should be fixed due to changing from exprimental_lambdify to lambdify when I didn't have matplotlib installed in my environment.

@moorepants This doesn't work because the problem seems to be with the text backend, so forcing it to use the text backend doesn't change anything.  Using backend='matplotlib' on the other hand does work as long as matplotlib is installed, cause the matplotlib plotting seems to be working.

If this issue can't be fixed(I have no idea how it would be), I feel like users who don't have matplotlib installed should be given some better error telling them something like:

`Since matplotlib is not installed, Sympy's graphing backend will be used.  Installing matplotlib is recommended.`

When I was trying to debug why it wasn't graphing properly it took me a while to figure out it was because matplotlib wasn't installed because Sympy currently gives no indication of that.

**Comment by moorepants** [comment]
> This doesn't work because the problem seems to be with the text backend, so forcing it to use the text backend doesn't change anything. 

I wasn't trying to imply that it fixed anything. I just mentioned it so you can reproduce the error without uninstalling matplotlib.

**Comment by SamLubelsky** [comment]
oh sorry yeah I see

**Comment by SamLubelsky** [comment]
I just put in a PR which seems to fix this, though I noticed while adding a regression test that the issue I was having doesn't seem to set off with backend='text' doesn't seem to set off the regression tests.  I think something strange is going on, but I don't know enough about pytest to really say.
