### ISSUE TITLE
isprime should error on floats

### ISSUE THREAD

**Issue by BorneNeedsHelp** [sympy/sympy#26489]
I was making a calculator and ran into an issue. 2 in not prime?? What!? I looked up tutorials, but still. 2 = false or not prime please help!

**Comment by asmeurer** [comment]
What SymPy code are you using that gives you this? SymPy does not have a function called `IsPrime`. It does have a function called `isprime`, but it does treat 2 as prime:

```
>>> isprime(2)
True
```

**Comment by BorneNeedsHelp** [comment]
Oh! I ment isprime but yes, I tried it, I says, False or not prime. Sorry!

**Comment by asmeurer** [comment]
I was about to suggest just that. It might be better if isprime just errored if the input is a float. Returning False for an integral float is confusing.

**Comment by asmeurer** [comment]
This would be trivial to change, by the way. Just delete these lines https://github.com/sympy/sympy/blob/e89ee9373fbbb90e92e18e6181606254653bbc34/sympy/ntheory/primetest.py#L672-L673. 

Looks like this comes from https://github.com/sympy/sympy/pull/9670. It's good for the assumptions to return False here, but the isprime() function would be better raising an exception.

**Comment by Abhishekjsr283204** [comment]
@haru-44 sir we need to delete those lines suggested by @asmeurer and can i make a PR  should we need to add the test cases.?

**Comment by asmeurer** [comment]
You'll also need to update the code in Q.isprime to catch the exception and continue to give False for floats.

**Comment by shishir-11** [comment]
Would it be better if instead of an error we internally converted them to integers(if the value was integral) or is there any particular reason to be raising an error on those values as well?

**Comment by asmeurer** [comment]
You can see the discussion on the old PR I linked to on why integral floats aren't considered prime.

**Comment by shishir-11** [comment]
I tried the method given in the documentation since i wanted to take a look at the working

```powershell
SYMPY_DEBUG=True bin/isympy
``` 

but in the sympy interactive terminal I still just get the output 

```powershell
In [1]: ask(Q.prime(2))
Out[1]: True
``` 
Can someone please inform me about what I am doing wrong.

**Comment by asmeurer** [comment]
There's just not any debug output configured for ask. You'll need to just dig into the source code to see where `isprime` is being used.
