### ISSUE TITLE
Roots of non-real elements should be non-real themselves, but their domain is unknown

### ISSUE THREAD

**Issue by lorenzwinkler1** [sympy/sympy#26545]
### Description
This is not a bug, rather an idea for an improvement

At the moment, taking the squareroot of a non-real expression (`is_extended_real==False`) does result in the value of `is_extended_real` being `None`.

```{python}
>>> x = Symbol('x', real=True)
>>> print((I+x).is_extended_real)
False
>>> print(sqrt(I+x).is_extended_real)
None
```
To the best of my knowledge, it would be correct to assume, that the root of a non-real number is not real itself, since this follows directly from the reals being closed under multiplication, i.e. $\sqrt{a}\in \mathbb{R} \Rightarrow \sqrt{a}\cdot \sqrt{a}\in\mathbb{R}$, which contradicts with the assumption.

### Motivation
When solving multivariate quartic polynomials, the solution sometimes contains the above mentioned subexpression.
For example the polynomial $a^4 - 2a^3b - 2a^3c + a^2b^2 + 4a^2bc + a^2c^2 - 2ab^2c - 2abc^2 + b^2c^2 + 1$ has no real solution. When we solve for a, we get, among others, the following solution: $\frac{b}{2} + \frac{c}{2} - \frac{\sqrt{b^2 - 2bc + c^2 - 4I}}{2}$.

```{python}
>>> a = Symbol('a', real=True)
>>> b = Symbol('b', real=True)
>>> c = Symbol('c', real=True)
>>> expr = solve(a**4 - 2*a**3*b - 2*a**3*c + a**2*b**2 + 4*a**2*b*c + a**2*c**2 - 2*a*b**2*c - 2*a*b*c**2 + b**2*c**2 + 1, a)[0]
>>> print(expr.is_extended_real)
None
```

### Possible modification
The function `_eval_is_extended_real` of the `Pow` class could be amplified, to return False, when the base is not real and the exponent is a rational with a nominator of 1.

**Comment by oscarbenjamin** [comment]
> The function `_eval_is_extended_real` of the `Pow` class could be amplified, to return False, when the base is not real and the exponent is a rational with a nominator of 1.

Sounds reasonable.
