### ISSUE TITLE
Why is the Quaternion logarithmic map given a private-looking name?

### ISSUE THREAD

**Issue by jpreiss** [sympy/sympy#26552]
Why is `Quaternion._ln` not given a name like `Quaternion.log` and documented as part of the public interface?

This was asked a while back, but it was tangential to the main topic and thus ignored:

> BTW, Is it any reason to avoid conventional `log` name for method. There is only `_ln`. Leading underscore in the method name may confuse since it looks like a private method. Maybe, adding `log = _ln` to the class definition makes sense.

_Originally posted by @vr050714 in https://github.com/sympy/sympy/issues/21576#issuecomment-855421034_

It seems odd to me, especially since `Quaternion.exp` is public. There are many use cases of quaternions where we wish to go between the Lie group and Lie algebra in both directions.

**Comment by oscarbenjamin** [comment]
I think it could be made a public method. I'm not sure if more tidying up or something is needed.

**Comment by jpreiss** [comment]
I can make a PR if desired!

**Comment by oscarbenjamin** [comment]
Yes, go ahead.
