### ISSUE TITLE
RecursionError in simplify of non-commutative expressions with non-integer coefficient

### ISSUE THREAD

**Issue by rrodenbusch** [sympy/sympy#26556]
Simplifying expressions with non-commutative symbols and floating point coeefficients generates a recursion error.

```python
from sympy import Symbol, cos, pi
X = Symbol('X', commutative = False)

try:
    display( (2 * cos(pi/3) * X).simplify() )
except RecursionError as e:
    print(f'RecursionError 2*cos(pi/3): {e}')

try:
    display( (2.0 * cos(pi/3) * X).simplify() )
except RecursionError as e:
    print(f'RecursionError 2.0*cos(pi/3): {e}')

try:
    display( (2.0 * cos(pi/6) * X).simplify() )
except RecursionError as e:
    print(f'RecursionError 2.0*cos(pi/6): {e}')
```
outputs:

X
RecursionError 2.0*cos(pi/3): maximum recursion depth exceeded in comparison
RecursionError 2.0*cos(pi/6): maximum recursion depth exceeded in comparison

**Comment by oscarbenjamin** [comment]
The check here fails if `com_coeff = 1.0`:
https://github.com/sympy/sympy/blob/7c4f580838612edea6dcd6ae7d5b8a75af2d8f10/sympy/simplify/simplify.py#L1761-L1762
