### ISSUE TITLE
sympy factor function produces wrong result

### ISSUE THREAD

**Issue by janfratric** [sympy/sympy#26578]
This is the code:
```python
import sympy
from sympy import symbols
var ('x y')
eq = ((2*x + 1)/y) - ((3*x + 2)/2*y)
sympy.factor(eq)
```
and this is the result it produces:
![image](https://github.com/sympy/sympy/assets/9251101/957be483-9763-43b4-bdc9-387bdbef9578)

I have seen that some of other reportes issues with more complex factors were closed, but this is fundamentally wrong.

**Comment by oscarbenjamin** [comment]
It seems correct to me.

Can you explain why you think it is wrong?

**Comment by smichr** [comment]
Did you mean this?
```python
>>> eq = (2*x + 1)/y - (3*x + 2)/(2*y)  # notice parentheses around 2*y
>>> factor(eq)
x/(2*y)
```

**Comment by janfratric** [comment]
Hello, thank you for replies. 
@oscarbenjamin - as @smichr pointed out, I left out parentheses arount the 2*y, therefore I was not getting the expected result.
Sorry for opening a wrong ticket. 
My appologies.

Thanks again
