### ISSUE TITLE
Accessing Matrix row/col ranges produces incorrect results

### ISSUE THREAD

**Issue by crgfn** [sympy/sympy#26588]
**Initialization**

from sympy import Matrix, shape
M = Matrix([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(M)
Matrix([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

pprint(shape(M))
(3, 3)

**Accessing ranges produces incorrect results**

print(M[0:1,0:1])
Matrix([[1]])

print(M[0:2,0:2])
Matrix([[1, 2], [4, 5]])

print(M[0:3,0:3])
Matrix([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(M[0:9,0:9])
Matrix([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

**Comment by wermos** [comment]
Can you elaborate on which one of these you think is the incorrect result? Also, it would be nice if you use the code font for the code snippets. You can use single backticks (`) for single lines, and triple backticks (```) for multiline snippets.

As far as `print(M[0:1,0:1])` and `print(M[0:2,0:2])` and `print(M[0:3,0:3])` is concerned, this is expected and documented behavior. See [this section](https://docs.sympy.org/dev/modules/matrices/matrices.html#basic-manipulation) for a reference.

**Comment by wermos** [comment]
I did a little investigating, and the behavior is arising from this part of the code:
https://github.com/sympy/sympy/blob/b412fa4b4a55e777c6766351bb7c48b46edd3004/sympy/matrices/repmatrix.py#L966-L978

Here, if `i` and `j` are `slice` instances, their max values are being clamped to the size of the matrix.

I'm not sure if this is the intended/desired behavior or not. If it is, then it should definitely be documented somewhere.

**Comment by oscarbenjamin** [comment]
This is just how slicing in Python works:
```python
In [58]: l = [1,2,3,4]

In [59]: l[:10]
Out[59]: [1, 2, 3, 4]
```

**Comment by sylee957** [comment]
I don't think that we should change this.
