### ISSUE TITLE
Version information that is not clear

### ISSUE THREAD

**Issue by haru-44** [sympy/sympy#26616]
Perhaps we can delete it.

https://github.com/sympy/sympy/blob/2eb826cdab1a4af50341fdbb470c6df518ecf1b8/sympy/multipledispatch/__init__.py#L5

**Comment by oscarbenjamin** [comment]
See also gh-23830.

**Comment by haru-44** [comment]
I understand. In that case, there is no point in pointing out trivial matters.
Thank you.
