### ISSUE TITLE
Why does Sympy seem to treat symbols defined the same way in different manners?

### ISSUE THREAD

**Issue by xjay73** [sympy/sympy#26617]
For this code:

```
from sympy import symbols, factor

a, b, n, s = symbols('a b n s')
expr1 = a**2 - b**2
expr2 = n**2 - s**2
print(factor(expr1))
print(factor(expr2))
```

The output:
```
(a - b)*(a + b)
-(-n + s)*(n + s)
```

Why does the factor method not factor identically constructed expressions to give the same style of output?

**Comment by oscarbenjamin** [comment]
It is because a symbol ordering is needed. You can control the symbol ordering:
```python
In [2]: factor(expr1, [a, b])
Out[2]: (a - b)⋅(a + b)

In [3]: factor(expr2, [n, s])
Out[3]: (n - s)⋅(n + s)

In [4]: factor(expr1, [b, a])
Out[4]: -(-a + b)⋅(a + b)

In [5]: factor(expr2, [s, n])
Out[5]: -(-n + s)⋅(n + s)
```
The signs of the factors are normalised by the leading coefficient which means the coefficient of first symbol in the symbol ordering in this case.

**Comment by xjay73** [comment]
Thank you, @oscarbenjamin. This raises two more questions then:

1. If an ordering is needed, then why in the second example of my original post doesn't it factor it as (s-n)*(s+n), since it's wanting 's' to come before 'n'.
2. What is the default ordering, then, if it isn't alphabetical?

**Comment by oscarbenjamin** [comment]
The factor function just needs a symbol ordering and if you don't provide one it chooses arbitrarily with a heuristic:
```
In [11]: from string import ascii_letters

In [12]: print(Poly(sum(symbols(list(ascii_letters)))).gens)
(x, y, z, p, q, r, s, t, u, v, w, a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, X, Y, Z)
```

**Comment by xjay73** [comment]
Wow... arbitrariness is always fun.

One more question, then... can the ordering be set at the symbol level, then, so that any method I need to use in my code that depends on this ordering uses the one I want throughout rather than having to specify it each time I call such a method?

**Comment by oscarbenjamin** [comment]
There is no non-arbitrary way to choose a symbol ordering.

There is no way to set the ordering at the symbol level except by choosing different names for your symbols.

**Comment by xjay73** [comment]
Thanks again for your answers. Just one more question that I asked earlier that got lost... Using part of your examples from earlier:

```
In [3]: factor(expr2, [n, s])
Out[3]: (n - s)⋅(n + s)

In [5]: factor(expr2, [s, n])
Out[5]: -(-n + s)⋅(n + s)
```

In both of these, regardless of the ordering supplied to `factor`, when the result is printed, `n` comes first within the factors. If I'm taking the time to impose an ordering on the `factor`, having the output like this is frustrating. 

How can I get the output here to look like `(s-n)*(s+n)` without needing to do a bunch of manual manipulation of the expression? More generally, how do I get the printed representation to match the ordering given to `factor`? (This is what I was getting to by asking if there is a way to set the ordering in some universal way so does what I want instead of something arbitrarily decided by sympy.)

**Comment by oscarbenjamin** [comment]
> How can I get the output here to look like `(s-n)*(s+n)`

The output cannot look like that because the sign is incorrect but if you mean `-(s-n)*(s+n)` then you are asking to change the printer ordering which is set differently:
```
In [9]: print(sum(symbols(list(ascii_letters))))
A + B + C + D + E + F + G + H + I + J + K + L + M + N + O + P + Q + R + S + T + U + V + W + X + Y + Z + a + b + c + d + e + f + g + h + i + j + k + l + m + n + o + p + q + r + s + t + u + v + w + x + y + z
```
There are order settings for `init_printing` but I don't know if they allow controlling the symbol ordering.
