### ISSUE TITLE
sympy.Float and sympy.Integer compare equal but have different hashes

### ISSUE THREAD

**Issue by larchen** [sympy/sympy#26624]
I noticed some unexpected behavior when using sympy floats/integers in sets/dictionaries and found that

```python
import sympy

sympy.Float(1) == sympy.Integer(1)  # evaluates to True
hash(sympy.Float(1)) == hash(sympy.Integer(1)) # evaluates to False
```

If I understand correctly, hashable objects that compare equal should also have the same hash value. https://docs.python.org/3/glossary.html#term-hashable

This is on Python 3.12 and Sympy 1.12

**Comment by oscarbenjamin** [comment]
This is already changed in master:
```python
In [2]: Float(1) == Integer(1)
Out[2]: False
```
