### ISSUE TITLE
Question: Can `parse_expr` parse Symbols with subtraction char in it? 

### ISSUE THREAD

**Issue by roykoand** [sympy/sympy#26686]
I want to parse Sympy string expression but in my use case I need to work with Symbols that contain subtraction character. 
```
_locals = {"A-C": "A-C"}
example = "A-C | 1"
simplify(example, locals=_locals)
```
Therefore it can't be parsed the way I want:
```
TypeError: unsupported operand type(s) for |: 'Add' and 'Integer'
```
Is it possible to either change the precedence of operations (and give the priority for parsing of Symbols first) OR somehow escape "keyword" characters in Symbol?

Thanks in advance!

**Comment by smichr** [comment]
The recognized transforms don't appear to handle this case:
```
    >>> from sympy.parsing.sympy_parser import transformations

    >>> print(transformations)
    0: lambda_notation
    1: auto_symbol
    2: repeated_decimals
    3: auto_number
    4: factorial_notation
    5: implicit_multiplication_application
    6: convert_xor
    7: implicit_application
    8: implicit_multiplication
    9: convert_equals_signs
    10: function_exponentiation
    11: rationalize
```
You could replace `|` with `__` in the string and then post-process the expression by replacing any symbol with `__` in the name with `|`:
```python
>>> parse_expr('a|b'.replace('|','__')).replace(lambda x: x.is_Symbol and '__' in x.name, lambda x: Symbol(x.name.replace('__','|')))
a|b
```

**Comment by smichr** [comment]
Or modify `parse_expr` to handle the `|` character as literal instead of logically.

**Comment by roykoand** [comment]
Thank you @smichr! I was thinking about the same workaround with `replace` but had a hope for some prettier solution.
Appreciate your help

**Comment by asmeurer** [comment]
The more "correct" solution would be to write a custom transformer that translates the tokens.
