### ISSUE TITLE
Sparse Matrix Multiplication Performance

### ISSUE THREAD

**Issue by ricdigi** [sympy/sympy#26741]
## Issue Description

When multiplying two large matrices in SymPy, the multiplication of sparse matrices appears to be less efficient than expected. Specifically, the multiplication of sparse matrices does not seem to take full advantage of the sparsity, leading to performance that is slower than the dense matrix multiplication and significantly slower than a custom sparse matrix multiplication implementation. **Can somebody help me understand if I am doing something wrong?**

## Code to Reproduce

```python
import sympy as sm
import random
import time

# Matrix size
n = 5000

# Create random non-zero indices with higher sparsity
non_zero_count = n * 2  # For example, 2 non-zero elements per row
rows = [random.randint(0, n-1) for _ in range(non_zero_count)]
cols = [random.randint(0, n-1) for _ in range(non_zero_count)]
values = [random.randint(1, n) for _ in range(non_zero_count)]

# Create sparse matrix
sparse_entries = {(rows[i], cols[i]): values[i] for i in range(non_zero_count)}
sparse_matrix = sm.SparseMatrix(n, n, sparse_entries)

# Create dense matrix with the same non-zero entries
dense_matrix = sm.Matrix(n, n, lambda i, j: sparse_entries.get((i, j), 0))

# Number of iterations to average
iterations = 10

# Average time for sparse matrix multiplication
sparse_times = []
for _ in range(iterations):
    start_sparse = time.time()
    sparse_result = sparse_matrix * sparse_matrix
    end_sparse = time.time()
    sparse_times.append(end_sparse - start_sparse)

avg_sparse_time = sum(sparse_times) / iterations
print(f"Average sparse matrix multiplication took {avg_sparse_time:.4f} seconds.")

# Average time for dense matrix multiplication
dense_times = []
for _ in range(iterations):
    start_dense = time.time()
    dense_result = dense_matrix * dense_matrix
    end_dense = time.time()
    dense_times.append(end_dense - start_dense)

avg_dense_time = sum(dense_times) / iterations
print(f"Average dense matrix multiplication took {avg_dense_time:.4f} seconds.")

def example_sparse_matrix_multiply(A, B):
    # Initialize result dictionary
    result = {}

    # Iterate through each non-zero element in A
    for (i, k), a_val in A.items():
        # If k is a row in B
        if k in B:
            for (k2, j), b_val in B.items():
                if k == k2:
                    # If the result cell already has a value, add to it
                    if (i, j) in result:
                        result[(i, j)] += a_val * b_val
                    else:
                        result[(i, j)] = a_val * b_val

    return result

A_dok = sparse_matrix.todok()
B_dok = sparse_matrix.todok()

# Average time for custom matrix multiplication
custom_times = []
for _ in range(iterations):
    start_cust = time.time()
    custom_result = example_sparse_matrix_multiply(A_dok, B_dok)
    end_cust = time.time()
    custom_times.append(end_cust - start_cust)

avg_custom_time = sum(custom_times) / iterations
print(f"Average example matrix multiplication took {avg_custom_time:.4f} seconds.")

```
### Results

```
Average sparse matrix multiplication took 0.0205 seconds.
Average dense matrix multiplication took 0.0129 seconds.
Average example matrix multiplication took 0.0007 seconds.
```

**Comment by oscarbenjamin** [comment]
> Average sparse matrix multiplication took 0.0205 seconds.
> Average dense matrix multiplication took 0.0129 seconds.
> Average example matrix multiplication took 0.0007 seconds.

Maybe check the output from the last one before you compare timings :)

SparseMatrix and Matrix have the same internal representation which is always a sparse DomainMatrix so they both call the same internal routine:
```python
In [6]: Matrix([[1, 0], [2, 3]])._rep
Out[6]: DomainMatrix({0: {0: 1}, 1: {0: 2, 1: 3}}, (2, 2), ZZ)
```
The routine that computes this product is here:
https://github.com/sympy/sympy/blob/206ec997872e05034e10494f6954daf17cf4fe6f/sympy/polys/matrices/sdm.py#L1453-L1494
Improvements to that code are welcome but please benchmark lots of different cases and bear in mind that the same routine is used both in the sparse and dense cases by default.

For comparison this is the time for Flint's dense representation:
```python
In [23]: M = Matrix.from_dok(n, n, sparse_entries)

In [24]: dM = M.to_DM().to_dense()

In [25]: %time r = dM*dM
CPU times: user 58.5 s, sys: 276 ms, total: 58.8 s
Wall time: 58.5 s
```
Unfortunately Flint does not have sparse matrices yet.

**Comment by ricdigi** [comment]
> > Average sparse matrix multiplication took 0.0205 seconds.
> > Average dense matrix multiplication took 0.0129 seconds.
> > Average example matrix multiplication took 0.0007 seconds.
> 
> Maybe check the output from the last one before you compare timings :)
> 
> SparseMatrix and Matrix have the same internal representation which is always a sparse DomainMatrix so they both call the same internal routine:
> 
> ```python
> In [6]: Matrix([[1, 0], [2, 3]])._rep
> Out[6]: DomainMatrix({0: {0: 1}, 1: {0: 2, 1: 3}}, (2, 2), ZZ)
> ```
> 
> The routine that computes this product is here:
> 
> https://github.com/sympy/sympy/blob/206ec997872e05034e10494f6954daf17cf4fe6f/sympy/polys/matrices/sdm.py#L1453-L1494
> 
> 
> Improvements to that code are welcome but please benchmark lots of different cases and bear in mind that the same routine is used both in the sparse and dense cases by default.
> For comparison this is the time for Flint's dense representation:
> 
> ```python
> In [23]: M = Matrix.from_dok(n, n, sparse_entries)
> 
> In [24]: dM = M.to_DM().to_dense()
> 
> In [25]: %time r = dM*dM
> CPU times: user 58.5 s, sys: 276 ms, total: 58.8 s
> Wall time: 58.5 s
> ```
> 
> Unfortunately Flint does not have sparse matrices yet.

was trying to find a way to delete the issue because I noticed the output wasn't correct, sorry

**Comment by oscarbenjamin** [comment]
There is no way to delete an issue but you can close it.

**Comment by ricdigi** [comment]
> There is no way to delete an issue but you can close it.

ok I will close this one, thanks anyway for the explanation
