### ISSUE TITLE
function_range is not robust with trigonometric functions

### ISSUE THREAD

**Issue by raks0009** [sympy/sympy#26742]
assumption: x = Symbol('x', real=True)

Test-case 1:
function_range(sin(22*x), x, S.Reals) => Interval(-1,1) which is correct

Test-case 2:
function_range(sin(22.22*x), x, S.Reals) => raises NotImplementedError: Unable to find critical points for sin(22.22*x)

Test-case 3:
function_range(sin(x + 2), x, S.Reals) =>Interval(-sin(I*(log(sqrt(cos(2)**2 + sin(2)**2)) + I*(atan(cos(2)/sin(2)) + pi)) - 2), -sin(I*(log(sqrt(cos(2)**2 + sin(2)**2)) + I*(atan(cos(2)/sin(2)) + 2*pi)) - 2)) I am not sure this makes much sense either.

**Comment by oscarbenjamin** [comment]
This is what I get with master:
```python
In [3]: from sympy.calculus.util import function_range

In [4]: x = symbols('x', real=True)

In [5]: function_range(sin(22*x), x, S.Reals)
Out[5]: [-1, 1]

In [6]: function_range(sin(22.22*x), x, S.Reals)
Out[6]: [-1, sin(0.5⋅π)]

In [7]: function_range(sin(x + 2), x, S.Reals)
Out[7]: [-1, 1]
```
What version of SymPy are you using?

**Comment by raks0009** [comment]
I see.
I forgot to mention that I am using version 1.12.1. 
I will test with the pre-release and update here.
Thanks for your reply @oscarbenjamin

**Comment by raks0009** [comment]
I tested with the pre-release version 1.13.0rc3, and it works!
Hence, I am closing this issue.
