### ISSUE TITLE
`inverse_laplace_transform(F,s,t)` return wrong result when `F` is `s**n` where `n` is a positive integer

### ISSUE THREAD

**Issue by mammalwong** [sympy/sympy#26775]
sympy version: 1.12.1, the issue is found when using google colab.
To reproduce the issue:
```
import sympy as sy
s,t = sy.symbols('s,t')
[sy.inverse_laplace_transform(F,s,t) for F in (1,s,s**2,s**3)]
```
it returns wrong result:
```
[δ(t), δ(t), δ(t), δ(t)]
```
expected result:
```
[δ(t), δ'(t), δ''(t), δ'''(t)]
```
for $s^n$ where $n$ is a positive integer, `inverse_laplace_transform` should return the n-th derivative of the Dirac Delta function `DiracDelta(t,n)` $\delta^{(n)}(t)$, which Wolfram Alpha does.

**Comment by oscarbenjamin** [comment]
CC @hanspi42

**Comment by hanspi42** [comment]
Thanks, this is indeed incorrect. I did not find it because the inverse Laplace transform of s**n for n>1 has no use in my field.
