### ISSUE TITLE
Boolean indexing for SymPy Matrices

### ISSUE THREAD

**Issue by certik** [sympy/sympy#2677]
This should work for `a` as a SymPy Matrix:

```
a[[True, False, True]]
```

**Comment by oscarbenjamin** [comment]
I don't see anything clear to fix here. Boolean indexing works for a Matrix and I assume that is the reason for the issue.

**Comment by czgdp1807** [comment]
@certik I am closing this for now as Boolean indexing works fine for Matrices in SymPy. Let me know if it needs to be re-opened again. Thanks.
