### ISSUE TITLE
diophantine and diop_solve ignore assumptions

### ISSUE THREAD

**Issue by IlGufo** [sympy/sympy#26783]
Using `solvers.diophantine` `diophantine` and `diop_solve` functions with integer and positive assumed symbols, also `{(0, 0)}` and negative solutions are returned.
For example:
```python
from sympy import Symbol
from sympy.solvers.diophantine import diophantine, diop_solve

x = Symbol("x", integer=True, positive=True)
y = Symbol("y", integer=True, positive=True)
eq = 10*x**2 + 5*x*y - 3*y
print(diophantine(eq))
print(diop_solve(eq))
```
prints
```
{(0, 0)}
{(1, -5), (-3, 5), (0, 0)}
```
while it should print at least an empty solution set.

**Comment by zylipku** [comment]
It seems currently `diop_quadratic()` will always return a trivial solution if applied when no other solutions are found.
https://github.com/sympy/sympy/blob/3a812204052176854bdfc1ea9d12097c3f9307ca/sympy/solvers/diophantine/diophantine.py#L1479-L1485
Maybe we should rearrange the logic?

**Comment by IlGufo** [comment]
I'm not inside `sympy` logic, but if a symbol is subjected to certain assumptions, intuitively I expect that functions I call on that symbols are going to adhere to such assumptions. So yes, probably editing `diophantine()` to make it returns an empty set if the trivial solution is not compatible with assumptions will be a better choice. Regarding `diop_solve()`, as it is an internal use function only, maybe adding in the documentation the warning that it does not respect assumptions (except the obvious `integer=True`) is the way.
