### ISSUE TITLE
Sympy 1.13.0 breaks nonlinsolve if noninteger constants used in function

### ISSUE THREAD

**Issue by bc118** [sympy/sympy#26820]
Sympy 1.13.0 breaks nonlinsolve if noninteger constants are used in function.   Specifically, EXAMPLE 1 below was working in Sympy 1.12.1 (1.12.1-pypyh2585a3b_103).  I noticed this as it broke my unit tests.

Is it possible to get Sympy to round the non-integer value (i.e., like 0.5 and 1.0 below in the examples) and outputs the correct equation ratio ("eqn_ratio") in all the examples below?  Am I missing the correct way to do this?  

Note: I did try "symengine.sympify" and "sympy.sympify" and neither seem to work.  

Thank you for you input and help in advance.

```
# EXAMPLE 1 
eqn_ratio, k0, k1, k2, k3, k4, phi = sympy.symbols(
    "eqn_ratio k0 k1 k2 k3 k4 phi"
)
values = sympy.nonlinsolve(
    [
        eqn_ratio
        - symengine.sympify(f"2*(0.5*k0 + 0.5*k1*(cos(phi) + 1) - 0.5*k2*(cos(2*phi) - 1) + 0.5*k3*(cos(3*phi) + 1) - 0.5*k4*(cos(4*phi) - 1))")
        / symengine.sympify(   "(0.5*k0 + 0.5*k1*(cos(phi) + 1) - 0.5*k2*(cos(2*phi) - 1) + 0.5*k3*(cos(3*phi) + 1) - 0.5*k4*(cos(4*phi) - 1))"),
    ],
    [eqn_ratio],
)
print(f"")
print(f"0.5 *2 values  = { values }")
print(f"0.5 eqn_ratio  = { eqn_ratio }")
print(f"")

# EXAMPLE 2
eqn_ratio, k0, k1, k2, k3, k4, phi = sympy.symbols(
    "eqn_ratio k0 k1 k2 k3 k4 phi"
)
values = sympy.nonlinsolve(
    [
        eqn_ratio
        - symengine.sympify(  "(1.0*k0 + 1.0*k1*(cos(phi) + 1) - 1.0*k2*(cos(2*phi) - 1) + 1.0*k3*(cos(3*phi) + 1) - 1.0*k4*(cos(4*phi) - 1))")
        / symengine.sympify("2.0*(0.5*k0 + 0.5*k1*(cos(phi) + 1) - 0.5*k2*(cos(2*phi) - 1) + 0.5*k3*(cos(3*phi) + 1) - 0.5*k4*(cos(4*phi) - 1))"),
    ],
    [eqn_ratio],
)

print(f"0.5 with sympy and symengine -- values  = { values }")
print(f"0.5 with sympy and symengine -- eqn_ratio  = { eqn_ratio }")
print(f"")


# EXAMPLE 3
eqn_ratio, k0, k1, k2, k3, k4, phi = sympy.symbols(
    "eqn_ratio k0 k1 k2 k3 k4 phi"
)
values = sympy.nonlinsolve(
    [
        eqn_ratio
        - sympy.sympify(  "(1.0*k0 + 1.0*k1*(cos(phi) + 1) - 1.0*k2*(cos(2*phi) - 1) + 1.0*k3*(cos(3*phi) + 1) - 1.0*k4*(cos(4*phi) - 1))")
        / sympy.sympify("2*(0.5*k0 + 0.5*k1*(cos(phi) + 1) - 0.5*k2*(cos(2*phi) - 1) + 0.5*k3*(cos(3*phi) + 1) - 0.5*k4*(cos(4*phi) - 1))"),
    ],
    [eqn_ratio],
)

print(f"0.5 with sympy only -- values  = { values }")
print(f"0.5 with sympy only -- eqn_ratio  = { eqn_ratio }")
print(f"")


# EXAMPLE 4
eqn_ratio, k0, k1, k2, k3, k4, phi = sympy.symbols(
    "eqn_ratio k0 k1 k2 k3 k4 phi"
)
values = sympy.nonlinsolve(
    [
        eqn_ratio
        - 1.0*symengine.sympify("(1.0*k0 + 1.0*k1*(cos(phi) + 1) - 1.0*k2*(cos(2*phi) - 1) + 1.0*k3*(cos(3*phi) + 1) - 1.0*k4*(cos(4*phi) - 1))")
        / symengine.sympify("(1/2*k0 + 1/2*k1*(cos(phi) + 1) - 1/2*k2*(cos(2*phi) - 1) + 1/2*k3*(cos(3*phi) + 1) - 1/2*k4*(cos(4*phi) - 1))"),
    ],
    [eqn_ratio],
)

print(f"1/2 values  = { values }")
print(f"1/2 eqn_ratio  = { eqn_ratio }")
print(f"")

# EXAMPLE 5
eqn_ratio, k0, k1, k2, k3, k4, phi = sympy.symbols(
    "eqn_ratio k0 k1 k2 k3 k4 phi"
)
values = sympy.nonlinsolve(
    [
        eqn_ratio
        - symengine.sympify("(1.0*k0 + 1.0*k1*(cos(phi) + 1) - 1.0*k2*(cos(2*phi) - 1) + 1.0*k3*(cos(3*phi) + 1) - 1.0*k4*(cos(4*phi) - 1))")
        / symengine.sympify("(1.0*k0 + 1.0*k1*(cos(phi) + 1) - 1.0*k2*(cos(2*phi) - 1) + 1.0*k3*(cos(3*phi) + 1) - 1.0*k4*(cos(4*phi) - 1))"),
    ],
    [eqn_ratio],
)

print(f"1.0 values  = { values }")
print(f"1.0 eqn_ratio  = { eqn_ratio }")
print(f"")
```

**Comment by oscarbenjamin** [comment]
It isn't clear what exactly has changed from your description.

This is the sympy 1.13.0 output for example 1:
```python
In [7]: values
Out[7]:
⎧⎛1.0⋅k₀ + 1.0⋅k₁⋅(cos(φ) + 1) - 1.0⋅k₂⋅(cos(2⋅φ) - 1) + 1.0⋅k₃⋅(cos(3⋅φ) + 1) - 1.0⋅k₄⋅(cos(4⋅φ) - 1) ⎞⎫
⎨⎜────────────────────────────────────────────────────────────────────────────────────────────────────,⎟⎬
⎩⎝0.5⋅k₀ + 0.5⋅k₁⋅(cos(φ) + 1) - 0.5⋅k₂⋅(cos(2⋅φ) - 1) + 0.5⋅k₃⋅(cos(3⋅φ) + 1) - 0.5⋅k₄⋅(cos(4⋅φ) - 1) ⎠⎭
```
This is the output with sympy 1.12.1:
```python
In [5]: values
Out[5]:
⎧⎛          k₀ + k₁⋅(cos(φ) + 1) - k₂⋅(cos(2⋅φ) - 1) + k₃⋅(cos(3⋅φ) + 1) - k₄⋅(cos(4⋅φ) - 1)           ⎞⎫
⎨⎜────────────────────────────────────────────────────────────────────────────────────────────────────,⎟⎬
⎩⎝0.5⋅k₀ + 0.5⋅k₁⋅(cos(φ) + 1) - 0.5⋅k₂⋅(cos(2⋅φ) - 1) + 0.5⋅k₃⋅(cos(3⋅φ) + 1) - 0.5⋅k₄⋅(cos(4⋅φ) - 1) ⎠⎭
```
The difference is just some `1.0` in the numerator.

You can use `nsimplify` to turn all floats into rationals if that is what you want:
```python
In [7]: nsimplify(values)
Out[7]:
⎧⎛k₀ + k₁⋅(cos(φ) + 1) - k₂⋅(cos(2⋅φ) - 1) + k₃⋅(cos(3⋅φ) + 1) - k₄⋅(cos(4⋅φ) - 1) ⎞⎫
⎪⎜────────────────────────────────────────────────────────────────────────────────,⎟⎪
⎨⎜k₀   k₁⋅(cos(φ) + 1)   k₂⋅(cos(2⋅φ) - 1)   k₃⋅(cos(3⋅φ) + 1)   k₄⋅(cos(4⋅φ) - 1) ⎟⎬
⎪⎜── + ─────────────── - ───────────────── + ───────────────── - ───────────────── ⎟⎪
⎩⎝2           2                  2                   2                   2         ⎠⎭
```
It would be better actually to do that before calling `nonlinsolve`.

**Comment by oscarbenjamin** [comment]
> Sympy 1.13.0 breaks nonlinsolve if noninteger constants are used in function.

I don't believe this is true or at least you have not demonstrated that anything is broken. Please explain more clearly if you think something is broken or otherwise I think we can close this.

**Comment by bc118** [comment]
@oscarbenjamin   Sorry that I was not clearer initially.  

The Example #1 worked in sympy 1.12.1 , but  it fails in the new 1.13.0 version.   My finding was having any non-integer numbers is what seems to make it not work, and you suggest the same above.  I provided some other examples that I tested (Examples 2 to 5) for reference and your testing if applicable. 

I 100% agree that ideally users would enter it as 1/2 not 0.5; however, some of the equations people standardized on contained the 0.5, and not always 1/2.  This is the reason I have it in my software, otherwise, I would have called it 1/2.  

If sympy can make Example 1 work again in the next revision that would be great, otherwise, I will have to remove scaling features and force them to only input the exact equation.  

Are you saying just straight up replace the 0.5 with 1/2 automatically?  If so, I am not sure how I selectively do that, as simplify does not seem to want to push the 1/2 value outside the ()s, as this would also resolve the issue.  Any other thoughts here?

Please let me know your thoughts or if you have any other questions or concerns.

Thanks,

Brad

**Comment by oscarbenjamin** [comment]
Okay great. Thanks for reporting this. I'm going to close this for now but we can reopen if a problem is discovered.

**Comment by bc118** [comment]
Sent from my iPhoneOn Jul 17, 2024, at 4:47 AM, Oscar Benjamin ***@***.***> wrote:﻿
Okay great. Thanks for reporting this. I'm going to close this for now but we can reopen if a problem is discovered.
