### ISSUE TITLE
[Potential Bug] parse_expr fails to parse complete expression

### ISSUE THREAD

**Issue by LakshyAAAgrawal** [sympy/sympy#26834]
Hi, I am new to sympy, and trying to use sympy for programatic algebraic simplification. I find that it is very useful, and works in most cases, however I found the following case where it deviates from my expected behaviour:

```python3
from sympy import parse_expr
parse_expr("0 <= x <= 100", evaluate=False)
# Output: 0 <= x
```

I believe that trying to parse such an expression should either parse the full expression, or fail with an exception if unable to parse completely. Could anybody with more experience please point out if this is expected, and if yes, is there any way to achieve my desired behaviour?

**Comment by sylee957** [comment]
The parser can be strict with the fix
```diff
diff --git a/sympy/parsing/sympy_parser.py b/sympy/parsing/sympy_parser.py
index 17919fe01a..3779107edf 100644
--- a/sympy/parsing/sympy_parser.py
+++ b/sympy/parsing/sympy_parser.py
@@ -1128,7 +1128,7 @@ class EvaluateFalseTransformer(ast.NodeTransformer):
         ast.Eq: 'Eq'
     }
     def visit_Compare(self, node):
-        if node.ops[0].__class__ in self.relational_operators:
+        if len(node.ops) == 1 and node.ops[0].__class__ in self.relational_operators:
             sympy_class = self.relational_operators[node.ops[0].__class__]
             right = self.visit(node.comparators[0])
             left = self.visit(node.left)
```
However, I'd like to see more proper fix to handle multiple inequality
