### ISSUE TITLE
very simple example of series bug

### ISSUE THREAD

**Issue by elexunix** [sympy/sympy#26856]
```
>>> series(2**n, n, oo, -1)
O(n, (n, oo))
```

Isn't it wrong? Of course 2^n is not O(n) as n->inf...

**Comment by cyan-ice** [comment]
You are not supposed to put -1 as the number of terms I guess...

**Comment by elexunix** [comment]
Ah, sorry.. I thought giving k here is saying that I need the expression up to O(n^k) error
Btw, is there a way to tell it that I need k leading terms instead of giving the absolute error? I often want to estimate something for theoretical computer science, where I need an expansion of a fast-growing function like binomial(n, n/3), but I often need only 1-2 leading terms of it, not up to O(1)
