### ISSUE TITLE
Can't simplify expression with radicals

### ISSUE THREAD

**Issue by rehenoakoton** [sympy/sympy#26857]
This simple numerical expression given below could be simplified to 4.
```python
In [75]: x
Out[75]: 
3 ___ ⎛  3 ____________   3 ___________⎞
╲╱ 2 ⋅⎝- ╲╱ -22 + 9⋅√6  + ╲╱ 22 + 9⋅√6 ⎠

In [76]: simplify(x)
Out[76]: 
3 ___ ⎛  3 ____________   3 ___________⎞
╲╱ 2 ⋅⎝- ╲╱ -22 + 9⋅√6  + ╲╱ 22 + 9⋅√6 ⎠

In [77]: x.evalf()
Out[77]: 4.00000000000000
```

**Comment by smichr** [comment]
There are more specific things that can be tried:
```python
eq=root(2,3)*(root(22+9*sqrt(6),3)-root(-22+9*sqrt(6),3))
>>> nsimplify(eq)
4
>>> eq.equals(_)
True
>>> minpoly(eq)
x - 4
```
Perhaps, for numerical expressions, testing that the numerical simplification is equal to the expression could be done. But I'm not sure if that is a "simplification" as much as it is an alternate representation. I'm not sure one can always get from one form to another with standard simplifications/rewriting.

**Comment by Davide-sd** [comment]
If you are only dealing with numbers, you can try `nsimplify`. For example:

```py
eq = sqrt(3 + 2 * sqrt(2)) - sqrt(2)
eq.nsimplify()
# 1
```

Or, you can try `sqrtdenest`:

```py
sqrtdenest(eq)
# (-1 + sqrt(2))*(1 + sqrt(2))
```

**Comment by oscarbenjamin** [comment]
Try e.g.:
```python
In [11]: eq = root(2,3)*(root(22+9*sqrt(6),3)-root(-22+9*sqrt(6),3))

In [12]: eq
Out[12]:
3 ___ ⎛  3 ____________   3 ___________⎞
╲╱ 2 ⋅⎝- ╲╱ -22 + 9⋅√6  + ╲╱ 22 + 9⋅√6 ⎠

In [13]: eq.as_poly(z, extension=True).as_expr()
Out[13]: 4
```
That should be able to reduce any algebraic number expression to rational if it is a rational number.

It can be slow for some expressions which is why it is not done by default in `simplify`.
