### ISSUE TITLE
[DOC] conf.py  contains obsolete reference to sphinx.ext.pngmath

### ISSUE THREAD

**Issue by jfbu** [sympy/sympy#26886]
The conf.py contains
```
pngmath_divpng_args = ['-gamma 1.5', '-D 110']
# Note, this is ignored by the mathjax extension
# Any \newcommand should be defined in the file
pngmath_latex_preamble = '\\usepackage{amsmath}\n' \
    '\\usepackage{bm}\n' \
    '\\usepackage{amsfonts}\n' \
    '\\usepackage{amssymb}\n' \
    '\\setlength{\\parindent}{0pt}\n'

```

but `sphinx.ext.pngmath` was removed from Sphinx at 1.8 (released Sep 13, 2018).  Besides there was a typo and it should have been `pngmath_dvipng_args` not `pngmath_divpng_args`.

The correct way now is to use [`sphinx.ext.imgmath`](https://www.sphinx-doc.org/en/master/usage/extensions/math.html#module-sphinx.ext.imgmath) with `html_math_renderer='imgmath'` if desired. But the default is MathJax and needs no extra configuration.

So all of the above could (should?) be removed.

**Comment by asmeurer** [comment]
Yes, we should only be using mathjax.
