### ISSUE TITLE
[DOC] Be it for HTML or LaTeX (at least, currently) `\mathbf{\omega}` (and all lowercase Greek) mark-up does not work

### ISSUE THREAD

**Issue by jfbu** [sympy/sympy#26907]
Here is a screenshot of current HTML docs:

![Capture d’écran 2024-08-03 à 19 31 34](https://github.com/user-attachments/assets/2c019159-4cb2-42ae-ba23-06ca61533dac)

We see that alpha and omega are not bold. Well a doubt can arise but I assure you they are not bold.

Further examination of the MathJax reveals that the mark-up is with U+1D714 MATHEMATICAL ITALIC SMALL OMEGA (and no bold-variant seems added, and if one uses the pop-up to export to MathML there is no bold for that character):

![Capture d’écran 2024-08-03 à 19 36 48](https://github.com/user-attachments/assets/e567a99f-c253-41a0-8a2d-016b894d7afe)

The source mark-up is

```
.. math::
  ^{\mathbf{N}}\mathbf{v}^P &= ^\mathbf{B}\mathbf{v}^P +
  ^\mathbf{N}\mathbf{v}^S + ^\mathbf{N}\mathbf{\omega}^\mathbf{B} \times
  \mathbf{r}^{SP}\\

  ^{\mathbf{N}}\mathbf{a}^P &= ^\mathbf{B}\mathbf{a}^S +
  ^\mathbf{N}\mathbf{a}^O + ^\mathbf{N}\mathbf{\alpha}^\mathbf{B}
  \times \mathbf{r}^{SP} + ^\mathbf{N}\mathbf{\omega}^\mathbf{B} \times
  (^\mathbf{N}\mathbf{\omega}^\mathbf{B} \times \mathbf{r}^{SP}) +
  2 ^\mathbf{N}\mathbf{\omega}^\mathbf{B} \times ^\mathbf{B} \mathbf{v}^P \\
```

i.e. using `\mathbf{\omega}` and `\mathbf{\alpha}`.

Math mode in LaTeX has always been very poorly documented (imho), and there is wide-spread misguided belief that `\mathbf` can work with Greek.  This is explained in part because it does work with **uppercase** Greek, but only in the default TeX math font configuration.  Now it seems that MathJax, like default LaTeX, does not understand `\mathbf{\omega}`.  But MathJax, like default LaTeX does understand `\mathbf{\Gamma}`.  Here is a screenshot of an HTML rendering (which uses MathJax) of ``.. math:: \mathbf{\alpha\Gamma}` in a minimal Sphinx document:

![Capture d’écran 2024-08-03 à 19 48 32](https://github.com/user-attachments/assets/e4347500-55d6-4dda-ba28-be5224e34134)

The Gamma is bold, the alpha is not bold.

In fact for the last 30 years or so, 99% of people seem to have understood that `\mathbf` will bolden its argument, but this is not the case. `\mathbf` in LaTeX (MathJax is not LateX Math at all but seems to follow it very closely) means to use a certain font.  Furthermore only very few TeX math commands will react to `\mathbf`.  In particular lowercase Greek letters ignore it completely.  Here is a screenshot of 1.13.1 PDF docs:

![Capture d’écran 2024-08-03 à 19 27 16](https://github.com/user-attachments/assets/bf98f8f7-16ef-4f19-8afa-b66483ab71ed)

We see that in PDF as in HTML-MathJax the lowercase Greek is not boldened.  No warnings are emitted during PDF build, because core TeX sees no error: `\mathbf{...}` is a command where one can put many things inside, some will react (Latin letters and **uppercase** Greek) others will not (in particular all non-letter symbols).

When a document is produced with xelatex or lualatex, chances are it uses `fontspec` which by default will change the target font of `\mathbf` from an "Old TeX font" of original Knuth TeX with only 128 glyphs to the document body text font in bold.  As anyhow `\omega` does not react, again no error arises.  When one adds usage of `unicode-math` then the `\omega` is rendered as a Unicode letter so here U+1D714, and it is configured by `unicode-math` to be of "type `\mathalpha`" which means that now it *will react* to `\mathbf`.  But then maybe the glyph is not available in the Bold variant of the body text font, and so a Missing character warning is emitted which one sees in LaTeX log.  This is not yet an error, so one has to pay attention, but with recent Latexmk used by Sphinx, this is summarized at end of run.  This is how I ended up finding the above occurrences in the SymPy documentation.

Options:
- `\bm` in LaTeX if one uses eponymous package (but appears to be incompatible with `unicode-math`)  and not supported by MathJax (maybe I am not well informed and some additional setting enacts it; I tested adding it to SymPy docs and MathJax displays a red string `\bm`),
- `\symbf` if one uses `unicode-math`, but <strike>I encountered at least one case during prior investigation, now lost, where a `\mathbf` with a more complex argument using super- or subscript caused a breakage if transformed into `\symbf`,</strike> (edit) unicode-math option `mathbf=sym` then causes build crash when `\mathbf{\hat{p_3}}` is encountered  (such mark-up is frequent in kinematics.rst),
- `\boldsymbol` works both in LaTeX (+amsmath, which Sphinx uses automatically) and MathJax (at least this is what I see on a small project compiled with current Sphinx and thus using MathJax3, there is no need for additional configuration it seems).  And the good thing is that despite its name `\boldsymbol` accepts a multi-character expression; it will bolden everything inside its argument, **if** the math font set-up for as "bold math version" as the bold glyphs; in MathJax it seems to work well.

It seems the fix here is to use `\boldsymbol` in kinematics.rst.

Here is in HTML+MathJax with `\boldsymbol` used in place of `\mathbf` for `\alpha` and `\omega`:

![Capture d’écran 2024-08-03 à 20 52 19](https://github.com/user-attachments/assets/adfb78a3-77a7-44f6-89bf-9ef18b3cf51f)

Now we see how bold alpha and omega look like.  We also see many instances of faulty mark-up  such as ``\times ^\mathbf{B} \mathbf{v}^P`` which causes the bold B to be a superscripting the `\times` multiplication symbol.  This should be (at minimal) ``\times {}^\mathbf{B} \mathbf{v}^P`` which renders as:
![Capture d’écran 2024-08-03 à 20 59 42](https://github.com/user-attachments/assets/75debab0-30c3-4e3e-95fd-697c1eb950ad)

Replacing globally `s/mathbf/boldsymbol/` is preferably to be avoided from LaTeX point of view because `\boldsymbol` is a bit costly (it tells TeX to prepare all four versions for display size, normal size, script size and script script size at each usage).

Some testing has to be done to see how usage of `\boldsymbol` will interact with `unicode-math` for PDF output: there are good arguments to use `unicode-math` as it will allow to set-up the TeXGyre DejaVu Math font which fits much better with the DejaVu Serif body fonts.

**Comment by moorepants** [comment]
These can be changed to `\boldsymbol`. I believe that is what I use when I write LaTeX documents that need this kind of notation. The missing `{}` for the superscripts is an error, not everyone is aware of that detail.

**Comment by jfbu** [comment]
I hope my "faulty mark-up" vocabulary will not be cause for bruised feelings :smiley:.  In my country teachers are definitely not allowed at all to say things like that... I am just expressing myself as a TeXnician..

**Comment by jfbu** [comment]
@moorepants In file g-functions.rst after a comment "many of the latex expressions below were generated semi-automatically" I find usage of ``\operatorname{\lambda_{s0}}``.  Is that mark-up aim to get an "upright" `\lambda`? 

With `unicode-math` this would trigger a `Missing character: There is no 𝜆 (U+1D706) in font DejaVu Serif`.

The `\lambda` is not at all modified in fact, but the `s` in the subscript is upright which is probably the intent.  Would `\lambda_{\mathrm{s}0}` be ok? It produces exact same output.

On the other hand I wonder if this upright `s` is really desired.  On line above we find `\lambda_{s0}`.

```rest
.. math:: \lambda_{s0}(c_1, c_2) = c_1 (q - p)|\omega|^{1/(q - p)} \sin{\psi}
                    + c_2 (v - u)|\sigma|^{1/(v - u)} \sin{\theta}
.. math:: \lambda_s =
  \begin{cases} \operatorname{\lambda_{s0}}\left(-1,-1\right) \operatorname{\lambda_{s0}}\le
```

See [Conditions of convergence for integral (2)](https://docs.sympy.org/latest/modules/integrals/g-functions.html#conditions-of-convergence-for-integral-2) the `\lambda_s` entry.

**Comment by jfbu** [comment]
In file hyperexpand.rst we find `\mathbf{\imath}`. Is the intent to obtain a bold symbol or an upright dotless i?  The `\mathbf` has no effect in MathJax, `\boldsymbol` does.  See screenshot whose source is ``\mathbf{\imath}\imath\boldsymbol{\imath}``: 
![Capture d’écran 2024-08-03 à 23 27 21](https://github.com/user-attachments/assets/650b6ef5-fbe8-44bf-b6fd-6d7d00ad7413)

See https://docs.sympy.org/latest/modules/simplify/hyperexpand.html#an-example, the formula for B_0 after the sentence The first basis element B_0 (etc...).  I find it strange that this formula should contain a bold Gauss-Argand "i" (with no dot ok, but bold why?)
