### ISSUE TITLE
minpoly returns a not irreducible polynomial

### ISSUE THREAD

**Issue by oscarbenjamin** [sympy/sympy#26903]
CC @smichr 

In this example minpoly returns `x**2` when it should return `x`:
```python
In [1]: p1 = nextprime(10**20)

In [2]: p2 = nextprime(p1)

In [3]: minpoly(sqrt(p1**2*p2) - p1*sqrt(p2))
Out[3]: 
 2
x 
```
I don't fully understand the `_separate_sq` function:
https://github.com/sympy/sympy/blob/199aafdfb2c18fd18be47503a6aa93a1eb992187/sympy/polys/numberfields/minpoly.py#L577-L579

Apart from a degenerate case like this is there a reason to assume that it will generate an irreducible polynomial?

Otherwise I guess we need to use the usual `choose_factor` method for this case as well.

**Comment by smichr** [comment]
I don't know a lot about this routine, but the first failing example for two consecutive primes has `p1 = nextprime(2**15)` which makes it look suspiciously dependent on something that happens only for small ints.
```python
>>> p1=2
>>> for p2 in primerange(3,100000):
...  if minpoly(sqrt(p1**2*p2) - p1*sqrt(p2)).is_Pow:
...    print(p1,p2)
...    stop
...  p1=p2
...
32771 32779
>>> p1 == nextprime(2**15)
True
```

**Comment by smichr** [comment]
```diff
diff --git a/sympy/polys/numberfields/minpoly.py b/sympy/polys/numberfields/minpoly.py
index a3543339bf..3045c79c52 100644
--- a/sympy/polys/numberfields/minpoly.py
+++ b/sympy/polys/numberfields/minpoly.py
@@ -576,7 +576,12 @@ def _minpoly_compose(ex, x, dom):
         while 1:
             ex1 = _separate_sq(ex)
             if ex1 is ex:
-                return ex
+                if ex.is_Add:
+                    return ex
+                ex = ex.as_independent(x, as_Add=False)[1]
+                if ex.is_Pow and ex.exp.is_Integer:
+                    return ex.base
+                assert None, "unhandled case"
             else:
                 ex = ex1
```

**Comment by oscarbenjamin** [comment]
> the first failing example for two consecutive primes has `p1 = nextprime(2**15)` which makes it look suspiciously dependent on something that happens only for small ints.

That is the limit on prime factorisation in `Pow.__new__` I think:
```python
In [3]: p1 = nextprime(100)

In [4]: p2 = nextprime(p1)

In [5]: sqrt(p1**2*p2) - p1*sqrt(p2)
Out[5]: 0
```
I was deliberately testing primes large enough that Expr would not automatically simplify the expression to zero (by extracting `p1` from the first `sqrt`).

**Comment by oscarbenjamin** [comment]
I'm not sure about this:

> ```diff
> +                if ex.is_Add:
> +                    return ex
> ```

The fact that this case returns a non-irreducible polynomial makes me wonder if there could be others where the polynomial is not just a simple power but is still not irreducible. It is unclear to me how the routine guarantees irreducibility without factorising the polynomial.

**Comment by smichr** [comment]
We can fix the problem while pondering the nature of the routine.... The suggested change will, at least, not hurt the behavior.

**Comment by oscarbenjamin** [comment]
If our expectation is that the worst case is we get a polynomial like `x**2` then how bad is it to just call `factor` (`factor(x**2)` is not a slow operation) and if there is more than one factor go through `choose_factor`?

Another possibility could be to check for what we expect and otherwise `assert False`.

**Comment by smichr** [comment]
What about
```python
    if dom.is_QQ and _is_sum_surds(ex):
        # eliminate the square roots
        ex -= x
        while 1:
            ex1 = _separate_sq(ex)
            if ex1 is ex:
                if ex.is_Add:
                    return ex
                if ex == -x**2:  # original number simplified to 0, e.g. sqrt(4*3)-2*sqrt(3)
                    return x
                assert None, 'unexpected result'
            else:
                ex = ex1
```

**Comment by oscarbenjamin** [comment]
I don't see how in general we can assume that the output of `_separate_sq` does not need to be sent to factor. In this case it generates a reducible polynomial but there could be others.
