### ISSUE TITLE
Biomechanics docs redirects not present

### ISSUE THREAD

**Issue by moorepants** [sympy/sympy#26917]
I was checking this post: https://mechmotum.github.io/blog/czi-sympy-wrapup.html and clicked these two hyperlinks:

https://docs.sympy.org/dev/tutorials/biomechanics/biomechanics.html

https://docs.sympy.org/dev/tutorials/biomechanics/biomechanical-model-example.html

and got "Page Not Found".

I thought we setup the redirects either in https://github.com/sympy/sympy/pull/26627 or https://github.com/sympy/sympy/pull/26727

cc/ @eh111eh

**Comment by eh111eh** [comment]
In [PR #26627](https://github.com/sympy/sympy/pull/26627), the file 'doc/src/tutorials/biomechanics/biomechanical-model-example.rst' was moved to 'doc/src/tutorials/physics/biomechanics/biomechanical-model-example.rst' and 'doc/src/tutorials/biomechanics/biomechanics.rst' was moved to 'doc/src/tutorials/physics/biomechanics/biomechanics.rst'.

After that, in [PR #26727](https://github.com/sympy/sympy/pull/26727), 'doc/src/tutorials/physics/biomechanics/biomechanics.rst' was further moved to 'doc/src/explanation/modules/physics/biomechanics/biomechanics.rst'.

We set up the redirects correctly in PR #26727, but not in PR #26627, which I think is the reason why the links don't work as expected. So, I think it would be best to open a new PR for the redirect:
```python
redirects = {
    "tutorials/biomechanics/biomechanical-model-example": "../tutorials/physics/biomechanics/biomechanical-model-example.html",
    "tutorials/biomechanics/biomechanics.rst": "../explanation/modules/physics/biomechanics/biomechanics.html",
}
```

**Comment by eh111eh** [comment]
I double checked [PR #26627](https://github.com/sympy/sympy/pull/26627), and there are no files to set the redirect other than 'doc/src/tutorials/biomechanics/biomechanical-model-example.rst' and 'doc/src/tutorials/biomechanics/biomechanics.rst'.

**Comment by moorepants** [comment]
https://docs.sympy.org/dev/tutorials/biomechanics/biomechanical-model-example.html

should point to:

https://docs.sympy.org/dev/tutorials/physics/biomechanics/biomechanical-model-example.html

and you have:

```
    "tutorials/biomechanics/biomechanical-model-example": "../tutorials/physics/biomechanics/biomechanical-model-example.html",
``

would it be because the `.html` is missing on the first part of the redirect?

**Comment by eh111eh** [comment]
> would it be because the `.html` is missing on the first part of the redirect?

Yes, the first redirect in [PR #26627](https://github.com/sympy/sympy/pull/26627) should have had
```python
redirects = {
    "tutorials/biomechanics/biomechanical-model-example": "../tutorials/physics/biomechanics/biomechanical-model-example",
    "tutorials/physics/biomechanics/biomechanics": "../tutorials/physics/biomechanics/biomechanics.html",
}
```
And then the second redirect in [PR #26727](https://github.com/sympy/sympy/pull/26727) should have had
```python
redirects = {
    "tutorials/physics/biomechanics/biomechanical-model-example": "../tutorials/physics/biomechanics/biomechanical-model-example.html",
    "tutorials/physics/biomechanics/biomechanics": "../explanation/modules/physics/biomechanics/biomechanics.html",
}
```

But I missed these redirects (sorry, my bad), so I think
```python
redirects = {
    "tutorials/biomechanics/biomechanical-model-example": "../tutorials/physics/biomechanics/biomechanical-model-example.html",
    "tutorials/biomechanics/biomechanics.rst": "../explanation/modules/physics/biomechanics/biomechanics.html",
}
```
can properly set up the redirects.

**Comment by moorepants** [comment]
In our meeting today we discussed that maybe these redirects are needed. SymPy 1.12.* docs did not have these pages and now the SymPy 1.13 does. The old locations were only present in the SymPy 1.13 development docs, which have no guarantee of URL stability. So I think that I just have to update my blog post to point to the SymPy 1.13 docs.

**Comment by eh111eh** [comment]
The URLs 
```
'doc/src/tutorials/biomechanics/biomechanical-model-example.rst', 
'doc/src/tutorials/biomechanics/biomechanics.rst'
```
no longer exist because these files were moved via [PR 326627](https://github.com/sympy/sympy/pull/26627), which was applied to SymPy 1.13.

The new URLs for these files are now
```
'doc/src/tutorials/physics/biomechanics/biomechanical-model-example.rst',
'doc/src/tutorials/physics/biomechanics/biomechanics.rst'
```
as found in the SymPy 1.13.2 documentation site.

Since [PR #26727](https://github.com/sympy/sympy/pull/26727) further moved
'doc/src/tutorials/physics/biomechanics/biomechanics.rst' to 'doc/src/explanation/modules/physics/biomechanics/biomechanics.rst', I think the redirect is only needed for this change, and it's correctly set in `conf.py` as
```python
redirects = {
    "tutorials/physics/biomechanics/biomechanics": "../explanation/modules/physics/biomechanics/biomechanics.html",
}
```

How are your site updates going? If there are no issues with the URL updates in your blog post, I think we can close this issue.

**Comment by moorepants** [comment]
I updated the site. This can be closed.
