### ISSUE TITLE
The following Integral doesn't evaluate anymore

### ISSUE THREAD

**Issue by Davide-sd** [sympy/sympy#26922]
```py
from sympy import *
init_printing()

a, b, x = symbols("a, b, x", real=True, positive=True)
C = symbols("C", real=True)
i = Integral(-C*x*exp(-a*x**2 - sqrt(b)*x), x) + Integral(C*x*exp(-a*x**2 + sqrt(b)*x), x)
i.doit()
```

Output with sympy 1.12.1 (and older):

![image](https://github.com/user-attachments/assets/e73668f8-c125-490d-967e-b0918c28ddbf)

Output with sympy 1.13.1:

![image](https://github.com/user-attachments/assets/7bf1b4e1-53a2-4b9b-92d1-a4841c627e5c)

**Comment by oscarbenjamin** [comment]
Bisected to 83ca9d981f5c610d3e087b045691410f2c4250a7 from gh-26358

CC @smichr

**Comment by smichr** [comment]
This was a very helpful test case, @Davide-sd. I appreciate you taking time to file the report! #26935 fixes this if you care to take a look.
