### ISSUE TITLE
Create an SVG figure for the MDoF Pendulum example

### ISSUE THREAD

**Issue by moorepants** [sympy/sympy#26923]
This example:

https://docs.sympy.org/dev/tutorials/physics/mechanics/multi_degree_freedom_holonomic_system.html

has a PNG as the figure:

![image](https://github.com/user-attachments/assets/d1269358-b983-4ecd-9635-d1eba366fc07)

I drew it on a Microsoft surface for a lecture a long time back and the surface gave wavy lines. This figure needs to be replaced with an SVG (pngs shouldn't be committed to the repo, this one was) and the figure should look better.

**Comment by moorepants** [comment]
This is taken from a PyDy example: https://pydy.readthedocs.io/en/stable/examples/multidof-holonomic.html

**Comment by Bitla-venkat** [comment]
should the svg look same as the image?

**Comment by Sambodhi-Roy** [comment]
This is my first open source contribution, please guide me through it and let me know if I need to make any further changes. I changed the png and replaced it with the svg file.

**Comment by tjstienstra** [comment]
To tackle this issue it is best to redraw the SVG. My personal workflow would be something as follows.
- Redraw the SVG from scratch in Inkscape (or PowerPoint).
- Format the SVG (optional):
  - Open the SVG in Inkscape
  - `ctrl` + `shift` + `R` crops the canvas
  - File -> Clean Up Document
  - File -> Save as -> Select `Plain SVG` or `Optimized SVG` (`Plain SVG` is easier to edit in the future)
- Open SVG in Notepad++
- Optionally, do some additional cleaning
- Adjust some of the black colors `#000000` to `CurrentColor` such that it switches color based on the theme
- Specify `class="align-center"` and the `width` at the start of the SVG. E.g.:
  ```
  <svg
     class="align-center"
     width="700"
     ...
  ```
- Adjust the rst file to show the SVG using:
  ```
  .. raw:: html
     :file: path_to_svg.svg
  ```
- Remove the old PNG file

The [four-bar linkage tutorial](https://docs.sympy.org/dev/tutorials/physics/mechanics/four_bar_linkage_example.html) is a nice example.

**Comment by naivedyammishra** [comment]
Is this issue still active to work upon?

**Comment by tjstienstra** [comment]
> Is this issue still active to work upon?

Yes

**Comment by ZiYao54** [comment]
Hi ,I would like to work upon this issue. This is my first open source contribution, please guide me through it and let me know if I need to make any further changes.

**Comment by tjstienstra** [comment]
> Hi ,I would like to work upon this issue. This is my first open source contribution, please guide me through it and let me know if I need to make any further changes.

[This comment](https://github.com/sympy/sympy/issues/26923#issuecomment-2401931666) explains what would be my own approach to fix this issue.
You can refer to the [new contributors guide](https://docs.sympy.org/dev/contributing/new-contributors-guide/index.html) for information on setting up your environment and such.
Additionally, you'll have to add yourself to the `.mailmap` when opening the PR. An detailed explanation can be found in the [.mailmap](https://github.com/sympy/sympy/blob/master/.mailmap) itself.

**Comment by ZiYao54** [comment]
![Image](https://github.com/user-attachments/assets/7b8149c1-f036-42b3-8296-22952a2a0e80)
"Hi, before I continue, could you confirm if this picture matches what you're looking for? If it does, I'll proceed to complete the drawing first."

**Comment by tjstienstra** [comment]
> ![Image](https://github.com/user-attachments/assets/7b8149c1-f036-42b3-8296-22952a2a0e80) "Hi, before I continue, could you confirm if this picture matches what you're looking for? If it does, I'll proceed to complete the drawing first."

Yes, this is indeed what we are looking for. Small review point: it might be nicer and easier to use a spline to draw that green body, as it gives less points (thought the same was done [here](https://docs.sympy.org/dev/explanation/modules/physics/mechanics/joints.html) only then in 3D).

Looking forward to seeing the final result.

**Comment by ZiYao54** [comment]
> > ![Image](https://github.com/user-attachments/assets/7b8149c1-f036-42b3-8296-22952a2a0e80) "Hi, before I continue, could you confirm if this picture matches what you're looking for? If it does, I'll proceed to complete the drawing first."
> 
> Yes, this is indeed what we are looking for. Small review point: it might be nicer and easier to use a spline to draw that green body, as it gives less points (thought the same was done [here](https://docs.sympy.org/dev/explanation/modules/physics/mechanics/joints.html) only then in 3D).
> 
> Looking forward to seeing the final result.

Thank you for the suggestion! I’ve completed the figure. Could you please confirm it before I proceed to the next step?
![Image](https://github.com/user-attachments/assets/f781c185-f1e9-4688-bf4d-f8d688ba940d)

**Comment by moorepants** [comment]
The one dimension should be $\frac{2l}{3}$, two thirds of the length.

**Comment by moorepants** [comment]
Other than the one dimension the figure looks very nice and I think it is correct. Thank you. I recommend make a pull request with the SVG to replace the PNG.

**Comment by ZiYao54** [comment]
> Other than the one dimension the figure looks very nice and I think it is correct. Thank you. I recommend make a pull request with the SVG to replace the PNG.

Thanks for the correction. 
I've created pull request #27166, but it's not eligible for automatic merging. Could I get some assistance resolving this?
