### ISSUE TITLE
Bug: Segment with point order reversed become unequal

### ISSUE THREAD

**Issue by evan0greenup** [sympy/sympy#26974]
In geometry, a segment is a set of points which are co-linear and within a range.

There is no concept of direction in segment.

However for the following code:

```python3
>>> pa = sympy.Point(1,2)
>>> pb = sympy.Point(3,4)
>>> sympy.Segment(pa, pb) == sympy.Segment(pb,pa)
False
```

It seems that segment with point order reversed become unequal. This should be unexpected and make a lot inconvenience on geometry calculation.

**Comment by smichr** [comment]
The args are not canonically ordered, perhaps by design -- auto-ordering of args can sometimes be a pain. There is a method that can be used to test for canonical/mathematical equality, however:
```
>>> Segment(pa,pb).equals(Segment(pb,pa))
True
```
