### ISSUE TITLE
Sympy coeff method gives wrong result

### ISSUE THREAD

**Issue by nightHawk406** [sympy/sympy#26977]
Hello,

I have having an issue with coeff method.
``` import sympy as smp

 X1 = smp.symbols("X1")
 x1 , x2 = smp.symbols("x_1 , x_2")
 a0 , a1 = smp.symbols("a0 , a1", real=True)
 disp = a0 + a1*X1
 Eq1 = disp.subs({X1 : 0})
 Eq2 = disp.subs({X1 : 1/4})
 sol = smp.solve([Eq1 - x1 , Eq2 - x2], [a0, a1])
 disp = disp.subs({a0 : sol[a0], a1 : sol[a1]})
 disp.coeff(x1,1 ) 
```

The output is
`1`
Instead of 
`1 - 4X1` 

Not sure if there is another method for this type of problems
Cheers

**Comment by smichr** [comment]
`coeff` deals with an expression literally. There is only one term having a factor of `x1` in `disp` and its coefficient is 1. To see what you want, expand the expression first:
```python
>> disp.expand().coeff(x1,1)
1 - 4.0*X1
```
