### ISSUE TITLE
TransferFunction.from_zpk and TransferFunction.from_coeff_lists example code gives error

### ISSUE THREAD

**Issue by ProComputerGaming** [sympy/sympy#26975]
Following the example code in the lti.py file I get these results:
(controls) C:\Users\mbeck>python
Python 3.10.14 | packaged by Anaconda, Inc. | (main, May  6 2024, 19:44:50) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from sympy.abc import s, p, k
>>> from sympy.physics.control.lti import TransferFunction
>>> zeros=[1,2,3]
>>> poles = [6,5,4]
>>> gain = 7
>>> tf = TransferFunction.from_zpk(zeros, poles, gain, s)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: type object 'TransferFunction' has no attribute 'from_zpk'

I'm not certain its a bug in SymPy, but I tried everything I could think of, I ended up just copying and pasting the functions directly into my project, and passing "TransferFunction" as 'cls' at the advice of a friend. Then it worked.

**Comment by ProComputerGaming** [comment]
Want to note the same issue and solution happens with "from_coeff_lists," I haven't tried with other similar functions

**Comment by Davide-sd** [comment]
What version of sympy are you using? Execute this and report your finding:

```py
import sympy;print(sympy.__version__)
```

**Comment by ProComputerGaming** [comment]
I got SymPy 1.12. 

I see the latest is 1.13.2, 1.12 is what was available through Anaconda once I downgraded the python in the environment to 3.10, the latest SymPy supports from the documentation. I just added Conda-forge and that sees 1.13.2. 

Could this version discrepancy be the cause of the error?

**Comment by Davide-sd** [comment]
Yes, I believe `from_zpk` was added with Sympy 1.13.0.
