### ISSUE TITLE
bode_plot function - setting phase_unwrap in parameter list gives matplotlib error

### ISSUE THREAD

**Issue by ProComputerGaming** [sympy/sympy#26976]
Traceback (most recent call last):

  File ~\anaconda3\envs\controls\lib\site-packages\spyder_kernels\py3compat.py:356 in compat_exec
    exec(code, globals, locals)

  File c:\users\mbeck\onedrive\projects\design tools\flyback supply\temp.py:65
    bode_plot(comp_tf, initial_exp=-5, final_exp=6, grid=True, show_axes=False, show=True, freq_unit='Hz', phase_unit='deg', phase_unwrap=True)

  File ~\anaconda3\envs\controls\lib\site-packages\sympy\physics\control\control_plots.py:948 in bode_plot
    mag = bode_magnitude_plot(system, initial_exp=initial_exp, final_exp=final_exp,

  File ~\anaconda3\envs\controls\lib\site-packages\sympy\physics\control\control_plots.py:761 in bode_magnitude_plot
    plt.plot(x, y, color=color, **kwargs)

  File ~\anaconda3\envs\controls\lib\site-packages\matplotlib\pyplot.py:3590 in plot
    return gca().plot(

  File ~\anaconda3\envs\controls\lib\site-packages\matplotlib\axes\_axes.py:1724 in plot
    lines = [*self._get_lines(self, *args, data=data, **kwargs)]

  File ~\anaconda3\envs\controls\lib\site-packages\matplotlib\axes\_base.py:303 in __call__
    yield from self._plot_args(

  File ~\anaconda3\envs\controls\lib\site-packages\matplotlib\axes\_base.py:539 in _plot_args
    return [l[0] for l in result]

  File ~\anaconda3\envs\controls\lib\site-packages\matplotlib\axes\_base.py:539 in <listcomp>
    return [l[0] for l in result]

  File ~\anaconda3\envs\controls\lib\site-packages\matplotlib\axes\_base.py:532 in <genexpr>
    result = (make_artist(axes, x[:, j % ncx], y[:, j % ncy], kw,

  File ~\anaconda3\envs\controls\lib\site-packages\matplotlib\axes\_base.py:346 in _makeline
    seg = mlines.Line2D(x, y, **kw)

  File ~\anaconda3\envs\controls\lib\site-packages\matplotlib\lines.py:407 in __init__
    self._internal_update(kwargs)

  File ~\anaconda3\envs\controls\lib\site-packages\matplotlib\artist.py:1219 in _internal_update
    return self._update_props(

  File ~\anaconda3\envs\controls\lib\site-packages\matplotlib\artist.py:1193 in _update_props
    raise AttributeError(

AttributeError: Line2D.set() got an unexpected keyword argument 'phase_unwrap'
---------------------------------------------------------------

Removing phase_unwrap from the parameter list and not setting it at all doesn't throw any errors.

**Comment by Davide-sd** [comment]
What version of sympy are you using? Execute this and report your finding:

```py
import sympy;print(sympy.__version__)
```

**Comment by ProComputerGaming** [comment]
I got SymPy 1.12.

I see the latest is 1.13.2, 1.12 is what was available through Anaconda once I downgraded the python in the environment to 3.10, the latest SymPy supports from the documentation. I just added Conda-forge and that will let me get SymPy 1.13.2.

Could this version discrepancy be the cause of the error?

**Comment by Davide-sd** [comment]
Yes, `phase_unwrap` was added with Sympy 1.13.0.

**Comment by sylee957** [comment]
You should set minimal SymPy version in your package to `1.13` 
or try to suggest the fix the respository of `design tools/flyback supply` if it is other public project.
