### ISSUE TITLE
Custom `PrettyPrinter` not receiving settings from `init_printing`

### ISSUE THREAD

**Issue by Davide-sd** [sympy/sympy#26979]
Working on this [SO question](https://stackoverflow.com/questions/78883266/how-to-print-fuctions-save-the-arguments-using-sympy-pprint) I discovered a bug with the way `init_printing` sends optional settings to custom printers.

The following custom printer displays applied undefined functions without their arguments. Also, I set up a custom option: when `applied_func_with_no_args=False`, the printer should display applied undefined functions with arguments (the usual behavior):

```py
from sympy.printing.pretty.pretty import PrettyPrinter
from sympy.printing.pretty.pretty_symbology import pretty_use_unicode
from sympy.core.function import AppliedUndef
from sympy.printing.conventions import requires_partial
from sympy.printing.pretty.stringpict import stringPict, prettyForm

class MyPrettyPrinter(PrettyPrinter):
    """Pretty printer customized to visualize applied undefined functions
    without arguments.
    """
    def __init__(self, settings=None):
        self._default_settings.update({
            "applied_func_with_no_args": True
        })
        super().__init__(settings)

    def _print_Function(self, expr, sort=False, func_name=None, left='(', right=')'):
        if isinstance(expr, AppliedUndef) and self._settings["applied_func_with_no_args"]:
            prettyFunc = self._print(Symbol(expr.func.__name__))
            prettyArgs = prettyForm("")
            pform = prettyForm(
                binding=prettyForm.FUNC, *stringPict.next(prettyFunc))
            # store pform parts so it can be reassembled e.g. when powered
            pform.prettyFunc = prettyFunc
            pform.prettyArgs = prettyArgs
            return pform
        
        return super()._print_Function(expr, sort=sort, func_name=func_name, left=left, right=right)

def my_pretty_printer(expr, **settings):
    pp = MyPrettyPrinter(settings)
    
    # XXX: this is an ugly hack, but at least it works
    use_unicode = pp._settings['use_unicode']
    uflag = pretty_use_unicode(use_unicode)
    
    try:
        return pp.doprint(expr)
    finally:
        pretty_use_unicode(uflag)
```

The printer works as expected if no additional options are provided to `init_printing`:

```py
from sympy import *
init_printing(use_latex=False, use_pretty=True, pretty_printer=my_pretty_printer)

var("x:z")
f = Function("f")(x, y, z)
f**2
#  2
# f 
```

However, if I provide my custom option, it will not be passed down to the printer:

```py
init_printing(use_latex=False, use_pretty=True, pretty_printer=my_pretty_printer, applied_func_with_no_args=False)

f**2
#  2
# f 
```

The output should have been:

```text
 2         
f (x, y, z)
```

The problem appears to be this line of code:

https://github.com/sympy/sympy/blob/c12282dd33113ef1e6ca338fe1986beeb7116ae0/sympy/interactive/printing.py#L82

In this case, `stringify_func` is `my_pretty_printer`, which is not receiving the user provided settings.

**Comment by phoeenniixx** [comment]
So I tried your code. The problem I encountered is that if you change the `applied_func_with_no_args` value in `init_printing`, the value is not changed in `self._default_settings` of your `MyPrettyPrinter` class. That means if you kept  `applied_func_with_no_args` `False` in `init_printing`, The value in `MyPrettyPrinter` class somehow stays `True`


```python
class MyPrettyPrinter(PrettyPrinter):
    """Pretty printer customized to visualize applied undefined functions
    without arguments.
    """
    def __init__(self, settings=None):
        self._default_settings.update({
            "applied_func_with_no_args": False
        })
        super().__init__(settings)

    def _print_Function(self, expr, sort=False, func_name=None, left='(', right=')'):
        if isinstance(expr, AppliedUndef) and self._settings["applied_func_with_no_args"]:
            prettyFunc = self._print(Symbol(expr.func.__name__))
            prettyArgs = prettyForm("")
            pform = prettyForm(
                binding=prettyForm.FUNC, *stringPict.next(prettyFunc))
            # store pform parts so it can be reassembled e.g. when powered
            pform.prettyFunc = prettyFunc
            pform.prettyArgs = prettyArgs
            return pform
``` 

when I changed the value of `applied_func_with_no_args` to `False` in `MyPrettyPrinter` class, No matter what we keep in `init_printing` it prints only this. Even the function without additional options give the following result.

```python
 2         
f (x, y, z)
```

**Comment by asmeurer** [comment]
This fix for this is going to need to be reverted. See https://github.com/sympy/sympy/issues/27992 and https://github.com/sympy/sympy/pull/27994
