### ISSUE TITLE
Possible bug with sympy.solve

### ISSUE THREAD

**Issue by YikesItsSykes** [sympy/sympy#27001]
For some systems of equations, sympy.solve can succeed when solving with respect to a subset of variables but raises an error when asked to solve with respect to a large set containing that variable set (containing that subset). This seems like a bug, as it should at least be able to find the same solutions it could find with the smaller variable set.

Here is a minimal example.
The following code can be executed without an error:
```
from sympy import symbols, solve
a1,a2,a3=symbols(['a1','a2','a3'])
eqnSystem=[a1, a1**2]
solve(eqnSystem,[a1,a2],dict=True)
```

But  an error will be raised if the following line is then executed:
```
solve(eqnSystem,[a1,a2,a3],dict=True)
```
The error raise is *no valid subset found*.

If solve can solve the system with respect to `[a1,a2]`, shouldn't it also be able to find some solution with respect to `[a1,a2,a3]`?

**Comment by oscarbenjamin** [comment]
This comes from SO:
https://stackoverflow.com/questions/78913691/why-might-sympy-solve-succeed-with-respect-to-fewer-variables-but-fail-w-r-t-mo

This is the error:
```python
In [2]: solve([x, x**2], [x, y, z])
---------------------------------------------------------------------------
NotImplementedError                       Traceback (most recent call last)
Cell In[2], line 1
----> 1 solve([x, x**2], [x, y, z])

File ~/current/active/sympy/sympy/solvers/solvers.py:1172, in solve(f, *symbols, **flags)
   1170         solution = _solve(f[0], *symbols, **flags)
   1171 else:
-> 1172     linear, solution = _solve_system(f, symbols, **flags)
   1173 assert type(solution) is list
   1174 assert not solution or type(solution[0]) is dict, solution

File ~/current/active/sympy/sympy/solvers/solvers.py:1896, in _solve_system(exprs, symbols, **flags)
   1894         solved_syms = list(got_s)
   1895     else:
-> 1896         raise NotImplementedError('no valid subset found')
   1897 else:
   1898     try:

NotImplementedError: no valid subset found
```
The problem comes from the overly complicated looking code here:
https://github.com/sympy/sympy/blob/9ae79a9b5802d2697e0644895e91734c33be5a1b/sympy/solvers/solvers.py#L1869-L1896
I don't know what that is doing but it should be rewritten some other way.

Calling `solve_poly_system` in a loop of combinatoric size should not happen...

**Comment by smichr** [comment]
The following still fails: subsets should additionally not exceed the length of equations.
```
from sympy import symbols, solve
s=a1,a2,a3,a4,a5=symbols(['a1','a2','a3','a4','a5'])
eqnSystem3=[8*a1**4*a2 + 4*a1**2*a2**3 - 8*a1**2*a2*a4 + a2**5/2 - 2*a2**3*a4 + 8*a2*a3**2 + 2*a2*a4**2 + 8*a2*a5, 12*a1**4 + 6*a1**2*a2**2 - 8*a1**2*a4 + 3*a2**4/4 - 2*a2**2*a4 + 4*a3**2 + a4**2 + 4*a5, 16*a1**3 + 4*a1*a2**2 - 8*a1*a4, -8*a1**2*a2 - 2*a2**3 + 4*a2*a4]
solve(eqnSystem3,s,dict=True)
```
