### ISSUE TITLE
(Please delete this issue)

### ISSUE THREAD

**Issue by bshoshany** [sympy/sympy#27016]
EDIT: Never mind, I figured it out. Please delete this issue.

**Comment by sylee957** [comment]
Unfortunately, there is no way to delete the issue in Github. Even the edits edits are visible

I don't know if you have exposed some privacy information here, to request some deletion here

**Comment by bshoshany** [comment]
Accounts with admin/owner permissions on this repository can delete issues, as described [here](https://docs.github.com/en/issues/tracking-your-work-with-issues/deleting-an-issue) (I can do that in my own repositories). Initially I thought there was an issue with `tensorcontraction()`, but then I realized I just misunderstood how it's supposed to work.

**Comment by oscarbenjamin** [comment]
We don't normally bother to delete issues once closed.
