### ISSUE TITLE
`prime(n)` is very slow

### ISSUE THREAD

**Issue by oscarbenjamin** [sympy/sympy#27034]
```python
In [4]: %time [[prime(n) for i in range(n)] for n in range(1, 10)]
CPU times: user 180 ms, sys: 7.68 ms, total: 187 ms
Wall time: 185 ms
Out[4]: 
[[2], [3, 3], [5, 5, 5], [7, 7, 7, 7], [11, 11, 11, 11, 11], [13, 13, 13, 13, 13, 13], [17, 17, 17, ↪

↪  17, 17, 17, 17], [19, 19, 19, 19, 19, 19, 19, 19], [23, 23, 23, 23, 23, 23, 23, 23, 23]]
```
It should not take anywhere near as long as this to compute `prime(n)` for such small values of `n`.

The profiler shows:
```python
In [5]: %prun -s cumulative [[prime(n) for i in range(n)] for n in range(1, 10)]

         207187 function calls (200958 primitive calls) in 0.303 seconds

   Ordered by: cumulative time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
       45    0.001    0.000    0.369    0.008 generate.py:372(prime)
      2/1    0.001    0.000    0.303    0.303 {built-in method builtins.exec}
        1    0.000    0.000    0.302    0.302 <string>:1(<module>)
  482/257    0.001    0.000    0.260    0.001 decorators.py:224(_func)
  802/354    0.010    0.000    0.239    0.001 evalf.py:1559(evalf)
      129    0.001    0.000    0.188    0.001 expr.py:357(__gt__)
      129    0.001    0.000    0.182    0.001 relational.py:834(__new__)
      129    0.000    0.000    0.180    0.001 relational.py:862(_eval_relation)
      129    0.000    0.000    0.179    0.001 relational.py:1171(_eval_fuzzy_relation)
      129    0.000    0.000    0.179    0.001 relational.py:1273(is_gt)
      129    0.000    0.000    0.178    0.001 relational.py:1281(is_le)
      129    0.001    0.000    0.178    0.001 relational.py:1289(is_ge)
      129    0.001    0.000    0.169    0.001 relational.py:1220(_n2)
 3290/698    0.018    0.000    0.167    0.000 evalf.py:1449(evalf)
       24    0.000    0.000    0.152    0.006 expr.py:305(__int__)
   128/24    0.004    0.000    0.150    0.006 expr.py:3804(round)
      225    0.004    0.000    0.135    0.001 evalf.py:586(evalf_add)
      352    0.010    0.000    0.110    0.000 evalf.py:635(evalf_mul)
      363    0.002    0.000    0.066    0.000 basic.py:796(is_comparable)
      329    0.005    0.000    0.057    0.000 function.py:528(_eval_evalf)
      329    0.003    0.000    0.037    0.000 ctx_mp_python.py:1017(f_wrapped)
      208    0.002    0.000    0.035    0.000 expr.py:4022(_mag)
     4367    0.009    0.000    0.035    0.000 cache.py:69(wrapper)
      716    0.004    0.000    0.032    0.000 expr.py:1896(as_real_imag)
      329    0.001    0.000    0.027    0.000 expintegrals.py:275(li)
     2327    0.010    0.000    0.024    0.000 sympify.py:98(sympify)
      658    0.002    0.000    0.024    0.000 ctx_mp_python.py:989(f)
     3033    0.008    0.000    0.021    0.000 numbers.py:914(_new)
     1910    0.002    0.000    0.021    0.000 sympify.py:488(_sympify)
  720/480    0.004    0.000    0.020    0.000 evalf.py:957(evalf_log)
     2123    0.003    0.000    0.020    0.000 numbers.py:1110(__eq__)
     1378    0.007    0.000    0.019    0.000 libelefun.py:668(mpf_log)
      577    0.003    0.000    0.019    0.000 numbers.py:1128(_Frel)
  650/521    0.001    0.000    0.017    0.000 decorators.py:58(__sympifyit_wrapper)
     2925    0.009    0.000    0.016    0.000 basic.py:469(__eq__)
      824    0.005    0.000    0.015    0.000 numbers.py:769(__new__)
      329    0.003    0.000    0.015    0.000 libhyper.py:484(mpf_ei)
     5031    0.011    0.000    0.014    0.000 numbers.py:148(mpf_norm)
     1509    0.003    0.000    0.014    0.000 numbers.py:1122(__hash__)
     1693    0.002    0.000    0.011    0.000 numbers.py:405(__float__)
      464    0.004    0.000    0.010    0.000 evalf.py:500(add_terms)
      313    0.000    0.000    0.010    0.000 numbers.py:1165(__ge__)
    22661    0.009    0.000    0.009    0.000 {built-in method builtins.isinstance}
    17625    0.009    0.000    0.009    0.000 {method 'get' of 'dict' objects}
     1316    0.002    0.000    0.009    0.000 ctx_mp_python.py:612(_set_prec)
     1218    0.008    0.000    0.008    0.000 libelefun.py:634(log_taylor_cached)
      160    0.000    0.000    0.007    0.000 numbers.py:1157(__gt__)
      353    0.001    0.000    0.007    0.000 decorators.py:99(binary_op_wrapper)
     2022    0.002    0.000    0.007    0.000 numbers.py:958(_as_mpf_val)
```
There is just a lot of stuff there that doesn't seem like it should be happening. The main thing seems to be that there is a symbolic comparison of expressions which seems unnecessary.

Probably symbolic comparison of expressions can be speeded up a lot but really they should not be used here:
https://github.com/sympy/sympy/blob/b3701d548874a1386aa9053b6be386e22fba76de/sympy/ntheory/generate.py#L427-L439
I don't know whether using the `li` function to compute a bound is reasonable for large arguments but at least for small arguments a sieve based approach should be used. Currently the sieve is checked but no attempt is made to extend the sieve:
https://github.com/sympy/sympy/blob/b3701d548874a1386aa9053b6be386e22fba76de/sympy/ntheory/generate.py#L424-L425

**Comment by haru-44** [comment]
I agree with setting a threshold and using the sieve for cases where `n` is below that threshold. However, I think we can only determine the specific value through experimentation.

Expanding the `sieve` to an appropriate length is important not just for `prime` but for many `ntheory` functions. Therefore, I think it might be useful to create documentation encouraging users to expand it to an appropriate length.

**Comment by haru-44** [comment]
The part where prime numbers are counted at the end can be shared with `nextprime`, so I created a pull request. However, there isn't much of a speed improvement.

Other points that I believe could be improved:

The expression `b = int(n*(log(n) + log(log(n))))` uses, for example, this [article](https://projecteuclid.org/journals/illinois-journal-of-mathematics/volume-6/issue-1/Approximate-formulas-for-some-functions-of-prime-numbers/10.1215/ijm/1255631807.full) (3.13). On [Wikipedia](https://en.wikipedia.org/wiki/Prime-counting_function), the following inequalities are presented:
$p_n \le n \left( \log n + \log \log n - 1 + \frac{\log \log n - 2}{\log n} \right)$
and
$p_n \ge n \left( \log n + \log \log n - 1 + \frac{\log \log n - 2.1}{\log n} \right).$
By setting these as `b` and `a`, the number of binary search iterations could be reduced.

If there were a more cost-effective way to evaluate `li(mid) > n`, it would be great, but I don’t have any ideas at the moment.

If we use `mid/log(mid)` instead of `li(mid)`, then I believe the cost will become too high when counting the primes at the end.

**Comment by haru-44** [comment]
By using the Newton's method instead of binary search, the number of `li` calls can be reduced.

```python
n = 123456789
mlog = math.log(n)
loglog = math.log(mlog)
x = n*(mlog + loglog - 1 + (loglog - 2) / mlog)
while True:
    diff = int((approx_li(x) - n) * math.log(x))
    if not diff:
        break
    x -= diff
```
