### ISSUE TITLE
Prefer log2(x) over log(x)/log(2)

### ISSUE THREAD

**Issue by nerai** [sympy/sympy#27049]
Please pardon my ignorance about SymPy. I'm only a new and indirect user via the PySR library.

In PySR, expressions using log2 are translated to SymPy via `sympy.log(x, 2)`. This is apparently forcibly translated to log(x)/log(2), and shows up in the final result in this form. However, the desired expression just is log2 directly.

To circumvent this, one can instead translate log2 to `sympy.codegen.cfunctions.log2(x)`. This correctly shows up as log2 in the resulting expressions. [Corresponding patch for PySR](https://github.com/MilesCranmer/PySR/pull/712/files)

However, `cfunctions.log2` seems to be an internal, undocumented function. Are we using the right approach? Is there a better documented way to get to the same result?

**Comment by bjodah** [comment]
The documentation for log2 is somewhat terse, but it's at least present in the documentation:
https://docs.sympy.org/latest/modules/codegen.html#sympy.codegen.cfunctions.log2

**Comment by oscarbenjamin** [comment]
Using the codegen function is the right approach I think.

I'll close this but we can reopen if there is something specific to change.

**Comment by asmeurer** [comment]
https://github.com/sympy/sympy/issues/6888# is also relevant here
