### ISSUE TITLE
Regression: `Matrix([[],[]])` raises ZeroDivisionError

### ISSUE THREAD

**Issue by sweeneyde** [sympy/sympy#27064]
The following worked in Sympy 1.12 but fails in Sympy 1.13:

```python
>>> from sympy import Matrix
>>> Matrix([[],[]])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Owner\Repos\sympy\sympy\matrices\repmatrix.py", line 558, in __new__
    return cls._new(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Owner\Repos\sympy\sympy\matrices\repmatrix.py", line 569, in _new
    rows, cols, flat_list = cls._handle_creation_inputs(*args, **kwargs)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Owner\Repos\sympy\sympy\matrices\matrixbase.py", line 3957, in _handle_creation_inputs
    T = reshape(flatT, [c])
        ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Owner\Repos\sympy\sympy\utilities\iterables.py", line 170, in reshape
    n, rem = divmod(len(seq), m)
             ^^^^^^^^^^^^^^^^^^^
ZeroDivisionError: integer division or modulo by zero
```

Bisected this to badb9b1610c3deaed1b87a5c6a34c8cc79677177 from PR https://github.com/sympy/sympy/pull/26605 and issue https://github.com/sympy/sympy/issues/26596

**Comment by oscarbenjamin** [comment]
In SymPy 1.12.1 we have:
```python
In [2]: Matrix([[],[]]).shape
Out[2]: (0, 0)
```
This is incorrect as it should be of shape `(2,0)`.

In SymPy 1.13 it raises as shown.

**Comment by oscarbenjamin** [comment]
Fix is in gh-27065

**Comment by sylee957** [comment]
I'm okay with the change. 
However, I'm unsure that users should use the construction `Matrix([[], ..., []])` other than `Matrix(n, 0, [])` or `Matrix(0, n, [])` which already works well.

You may face obvious limitation that it isn't possible to construct matrix with `n` columns in this construction,
because Python don't allow to create list like `[,,,]`
