### ISSUE TITLE
From Allyn Washington's 'Basic Tech Math' chap 31 example 5

### ISSUE THREAD

**Issue by Moses-1600** [sympy/sympy#27106]
From Allyn Washington's 'Basic Tech Math' chap 31 example 5
"Show that y=3x+x**2 is a solution of the differential equation xy'-y=x**2
Taking one derivative and substituting in the differential equation, we have
y=3x+x**2
y'=3+2x
x(3+2x)-(3x+x**2)=x**2
xy'-y=x**2 particular solution -- no arbitrary constants" 

The following is my code, 1st I use solve with the literal equations given then I use dsolve and zero out the differential equation -x**2
which I found is necessary

from sympy.abc import y
ode=x*(3+2*x)-x**2-y
ode=3*x+x**2-y
#eq=x**2-4
result=sp.solve(ode,y)
print(result)
Output was:[x*(x+3)]

from sympy import Function, dsolve, Derivative, symbols, checkodesol # must be 1st?
import sympy as sp
from sympy.abc import x
#y = 3*x+x**2
f=Function('f')
# Solve the ODE

#result=dsolve(sp.diff(y(x),x)*x-y(x),y(x)) # This line works the same
result=dsolve(Derivative(f(x),x)*x-f(x)-x**2,f(x))
print(result)
Output was: Eq(f(x),x*(C1+x))

However, does anybody no how to alleviate the arbitrary constant C1, should be

_Originally posted by @Moses-1600 in https://github.com/sympy/sympy/discussions/27101_

**Comment by oscarbenjamin** [comment]
There is already a discussion for this: gh-27101.

GitHub issues are not for getting help with using SymPy so I will close this.

You will likely get better response by asking on the mailing list than in GitHub Discussions.
