### ISSUE TITLE
Adding a function to cache prime factors

### ISSUE THREAD

**Issue by haru-44** [sympy/sympy#27124]
The prime factorization performed by `factorint` does not cache results. This leads to performance degradation when factorizing the same natural numbers multiple times. However, the amount of data to be cached depends on the use case. To address this, how about implementing an LRU cache class using `OrderedDict`, allowing the user to define the cache size?

Additionally, I thought it would be useful to query prime factors from `factordb` using `requests`, but since this would require the `requests` library, further consideration is needed.

```python
from bisect import bisect
from collections import OrderedDict
from typing import Iterable
from warnings import warn
from sympy.external import import_module
from sympy.external.gmpy import remove
from sympy.ntheory import sieve, isprime

class FactorCache:
    def __init__(self, use_factordb:bool=False, maxsize:int|None=None):
        self._cache: OrderedDict[int, int] = OrderedDict()
        self.use_factordb = use_factordb
        self.maxsize = maxsize

    FACTORDB_URL = "http://factordb.com/api"

    @property
    def use_factordb(self) -> bool:
        return self._requests is not None

    @use_factordb.setter
    def use_factordb(self, value: bool) -> None:
        if value:
            self._requests = import_module("requests", warn_not_installed=True)
        else:
            self._requests = None

    @property
    def maxsize(self) -> int | None:
        return self._maxsize

    @maxsize.setter
    def maxsize(self, value: int | None) -> None:
        if value is not None and value <= 0:
            raise ValueError("value must be None or a positive integer")
        self._maxsize = value
        if value is not None:
            while len(self._cache) > value:
                self._cache.popitem(False)

    def clear(self) -> None:
        self._cache = OrderedDict()

    def add_factors(self, n:int, factors:Iterable[int]) -> None:
        if n < 2:
            return

        def _add_new_item(k:int, v:int) -> None:
            self._cache[k] = v
            if self.maxsize is not None and len(self._cache) > self.maxsize:
                self._cache.popitem(False)

        for factor in sorted(set(factors), reverse=True):
            if n == factor:
                if isprime(factor):
                    _add_new_item(n, 1)
                    return
                continue
            if factor <= 1 or n % factor or not isprime(factor):
                continue
            if n in self._cache:
                self._cache[n] = max(self._cache[n], factor)
            else:
                _add_new_item(n, factor)
            n, _ = remove(n, factor)
            n = int(n)
        return

    def get(self, n: int) -> tuple[dict[int, int], int]:
        factors: dict[int, int] = {}
        while n > 1:
            if sieve._list[bisect(sieve._list, n) - 1] == n:
                # If it exists in sieve
                factors[n] = 1
                n = 1
                break
            if n in self._cache:
                # If it exists in cache
                self._cache.move_to_end(n)
                p = self._cache[n]
                if p == 1:
                    # prime
                    factors[n] = 1
                    n = 1
                    break
                n, e = remove(n, p)
                factors[p] = e
                continue
            if self.use_factordb:
                res = self._requests.get(FactorCache.FACTORDB_URL, params={"query": str(n)})
                if res.status_code != self._requests.codes.ok:
                    warn("Not used because it does not connect to factordb")
                    self.use_factordb = False
                    break
                j = res.json()
                if j.get("status") == "FF":
                    for p, e in j.get("factors"):
                        factors[int(p)] = int(e)
                    self.add_factors(n, factors.keys())
                    n = 1
                    break
                else:
                    break
            break
        return factors, n

factor_cache = FactorCache(maxsize=1024)
```

**Comment by tasfia8** [comment]
Hello! Would you consider this a good first issue? What would be the label for difficulty?

**Comment by asmeurer** [comment]
A cache should either use the global SymPy cache or at least the same mechanisms as it (I think there might be other functions that use their own cache, but share some code with the core cache). 

For factordb, that sounds fine. It can just be an optional keyword argument to the `factorint` function, which is disabled by default, and requests would just be an optional dependency for that feature. If you want a global way to enable it, maybe you could use an environment variable or a module variable. I'm not sure if most people would want library functions to try to access the internet, though.

**Comment by asmeurer** [comment]
I couldn't find any ToS for factordb other than https://factordb.com/res.php, but if they do have one we should make sure we are within that.

**Comment by haru-44** [comment]
> Hello! Would you consider this a good first issue? What would be the label for difficulty?

I don't think this would be a good first issue.

> A cache should either use the global SymPy cache or at least the same mechanisms as it (I think there might be other functions that use their own cache, but share some code with the core cache).

Global caches can only handle immutable values. Following this notation, `cacheit` cannot be used for functions like `factorint(n: int) -> dict[int, int]`. (although, for example, `sympy.functions.elementary.trigonometric._table2` does not adhere to this rule).

https://github.com/sympy/sympy/blob/dc69be1c42b3dfdbf03478d14b9ad2ca5a7dbc9e/sympy/core/cache.py#L45-L48

We could consider creating a function like `get_factor(n: int) -> int`, which returns a prime factor of `n`. However, when attempting to register prime factors without using a function, it becomes unclear how to proceed.

I understand that we want to manage the cache across the entire `sympy` library, but it seems that using just a decorator may not be sufficient to handle the diverse requirements. Similar examples include `sympy.ntheory.generate.sieve` and `sympy.integrals.heurisch.DiffCache`.

> I'm not sure if most people would want library functions to try to access the internet, though.

As you mentioned, it requires internet access. I believe this is unprecedented in SymPy, so I am being cautious about implementing this feature.

**Comment by tasfia8** [comment]
Okay sounds good, thanks for letting me know.

**Comment by sylee957** [comment]
> Global caches can only handle immutable values. 

I don't think that you need to use dict.
You can use a tuple like `(2, m), (3, n), ...` to represent a prime factorization `2**m*3**n*...`
That may work. 
I'm even unsure that the requirement that values should be immutable is strict requirement, or some requirement from some coding styles, or it can be. 
For example, you can still use `dict` but it can work fine as long as you don't change anything.
This can even be enforced with type checkers by promoting the return type to `Mapping` instead of `dict`.

**Comment by haru-44** [comment]
Since the `cache.py` is under `core`, caution may be necessary when using it in `ntheory` (see [#25059](https://github.com/sympy/sympy/pull/25059#issuecomment-1512140372)).
At the moment, I cannot think of a compromise that would satisfy all requirements.

**Comment by sylee957** [comment]
At least I'd like to exclude discussion about using `factordb`.
I'm not very clear about how that helps performance, considering non-obvious factors like network latency.
It complicates the implementation, and introduces security vulnerability, or denial of sevice issues that I'm concerned of.

At least after excluding that, you may suggest something that is more easy to verify.

**Comment by haru-44** [comment]
> At least after excluding that, you may suggest something that is more easy to verify.

As you mentioned, factordb is indeed difficult to handle, so it would be fine to disregard it. Even when focusing solely on the caching of prime factors, I don’t have any ideas.

**Comment by asmeurer** [comment]
I think a much more reasonable thing to do would be to add a simple, user-facing way to add known prime factorizations to the cache. For any user-facing API, IMO we should check the inputs for correctness, since that should be cheap. In the docstring for this, we can then show a simple example of how you might use this with factordb. This should just be a few lines of code. That way it's not really an API in SymPy, but rather just a docs example for any interested users. 

As you noted, users could also extend the cache from other sources. 

The API itself could just be a simple [MutableMapping](https://docs.python.org/es/3/library/collections.abc.html#collections.abc.MutableMapping) (so that to the user it just looks like a dictionary), with the additional checks that I noted, and maybe LRU eviction (thought that would only really be needed if it is also hooked into all factorint inputs).

**Comment by haru-44** [comment]
Is this the kind of code you are envisioning?

```python
from collections.abc import MutableMapping
from sympy.external.gmpy import remove

class FactorCache(MutableMapping):
    def __init__(self):
        self._cache = {}
        
    def get(self, n: int, default=None):
        if n in self._cache:
            return self._cache[n]
        
        if res := get_external(n):
            m = n
            for p in sorted(res, reverse=True):
                self[m] = p
                m, _ = remove(m, p)
            return self._cache[n]
        return default
        
    def __getitem__(self, n: int) -> int:
        factor = self.get(n)
        if factor is None:
            raise KeyError()
        return factor
        
    def __setitem__(self, n: int):
        # Check input and register it in _cache
        pass
    
    def get_external(self, n: int) -> list[int] | None:
        return None

factor_cache = FactorCache()
```

And if the user wants to use factordb, they can write it like this:

```python
import requests
from sympy import factor_cache

def get_external(self, n: int) -> list[int] | None:
    res = requests.get("http://factordb.com/api", params={"query": str(n)})
    if res.status_code != requests.codes.ok:
        return None
    j = res.json()
    if j.get("status") == "FF":
        return list(int(p) for p, _ in j.get("factors"))
    
factor_cache.get_external = get_external
```

In this case, I think it does not match with SymPy’s caching mechanism.

**Comment by asmeurer** [comment]
I wasn't even thinking about having a hook, although I don't see an issue with it. I was actually thinking more along the lines of something where you can manually insert items into the cache

```
factor_cache[1606938044258990275541962093111894167460966469892788384261671] = {1267650600228229401496703205653: 1, 1267650600228229401496703205707: 1}
```

And internally it checks that `1267650600228229401496703205653` and `1267650600228229401496703205707` are indeed prime and multiply to `1606938044258990275541962093111894167460966469892788384261671`. 

And then the user could manually inject numbers into the factor cache from factordb or whatever other source, like

```py
for n in <numbers you care about>:
    res = requests.get("http://factordb.com/api", params={"query": str(n)})
    if res.status_code != requests.codes.ok:
        return None
    j = res.json()
    if j.get("status") == "FF":
        factor_cache[n] = list(int(p) for p, _ in j.get("factors"))
```

(and a minor note: the factor cache should also be able to handle a list of factors without multiplicities, since that's what factordb returns)

**Comment by haru-44** [comment]
> I was actually thinking more along the lines of something where you can manually insert items into the cache

The user can register prime factors in this way as well. However, they may not always know in advance what prime factorization will be needed. For example, `sympy.ntheory.residue_ntheory.n_order` internally uses `factorint`, but predicting the required prime factorization in this case would require a deep understanding of the algorithm.

> Actually, I just had a better idea: instead of caching factorizations, how about we just cache known large primes. These would then be added to the set of primes that are checked for trial divisions in factorint.

That idea works well when caching is useful, but it’s not a good method in general. In cases where random numbers are input to `factorint`, we would end up performing checks that are unlikely to hit. In this scenario, storing the prime factors of `n` only requires a logarithmic-order comparison check for the cache, whereas storing primes requires linear-order trial factoring.

**Comment by haru-44** [comment]
> probably best to leave the cache up to the programmer. if they know that they will be using the same function multiple times, then they can figure out how to build a simple look up table/dict for each number that has the factors cached.

If you're only caching `factorint`, I think your suggested method is fine. However, there are also functions that use `factorint` internally. For example, `n_order(a, n)` internally calls `factorint(n)`. When using it in the following way, caching `n_order` does not speed up the process.

```python
n = ...
for a in range(2, 100):
    if math.gcd(a, n) == 1:
        print(n_order(a, n))
```

There are many other functions that use `factorint`, such as `sqrt_mod`. I think it would be better to handle them all at once by caching within `factorint`.

**Comment by asmeurer** [comment]
> That idea works well when caching is useful, but it’s not a good method in general. In cases where random numbers are input to factorint, we would end up performing checks that are unlikely to hit. In this scenario, storing the prime factors of n only requires a logarithmic-order comparison check for the cache, whereas storing primes requires linear-order trial factoring.

I don't think this will be a problem, so long as you use a bounded cache with LRU eviction. The cache would need to be designed so that an cache "hit" happens whenever a prime factor is actually present in some input to `factorint`. Random primes that are never seen again would be evicted and primes that are seen often would stay in the cache.

There are also other eviction strategies that might be more appropriate. https://en.wikipedia.org/wiki/Cache_replacement_policies For instance, maybe LFU (least frequently used) would make more sense than LRU. Or maybe something else. There's a ton of literature here. The main thing is to test this against some real world usage (speaking of which, do we know of actual real uses where this is a problem at all? Most code does not involve very large numbers).

**Comment by asmeurer** [comment]
Also, to be clear, this really only makes sense for relatively large primes, where finding them by other means would be too slow. We'd have to benchmarking to find a good lower bound, as well as a good cache size n that balances the cost of running trial divisions (also keep in mind that you only have to check the cached primes that are actually smaller than the input composite).

**Comment by haru-44** [comment]
> the programmers who need to use these caches can simply modify factorint with their own cache logic. I think it is called monkey patching.

For example, do you know if `factorint` is used when running `diophantine(x**2 - y)`? Not all users fully understand the internal implementation of SymPy. It would be unkind to leave it to the users to decide when to add caching functionality to `factorint`.
Furthermore, it is important to note that whether or not something is feasible for the user has no bearing on whether SymPy should offer it as a feature.

> > That idea works well when caching is useful, but it’s not a good method in general. In cases where random numbers are input to factorint, we would end up performing checks that are unlikely to hit. In this scenario, storing the prime factors of n only requires a logarithmic-order comparison check for the cache, whereas storing primes requires linear-order trial factoring.
> 
> I don't think this will be a problem, so long as you use a bounded cache with LRU eviction. The cache would need to be designed so that an cache "hit" happens whenever a prime factor is actually present in some input to `factorint`. Random primes that are never seen again would be evicted and primes that are seen often would stay in the cache.

I was pointing out that the cost when a cache miss occurs is linear in relation to the size of the cache. I don’t think changing the caching strategy will solve this problem.

> We'd have to benchmarking to find a good lower bound, as well as a good cache size n that balances the cost of running trial divisions.

Are you suggesting fixing the cache size? If so, I suppose it would be possible to consider the issue a constant cost. I don’t understand the advantage of such an implementation.

**Comment by asmeurer** [comment]
Yes, I was considering a bounded cache size. An unbounded cache would lead to unbounded memory usage, although I suppose the memory usage of some integers might not be that great. The main point would be to protect against someone doing something like

```py
while True:
    p = nextprime(p)
    factorint(p)
```

and filling up the cache. 

> I was pointing out that the cost when a cache miss occurs is linear in relation to the size of the cache. I don’t think changing the caching strategy will solve this problem.

I'm assuming trial division is cheaper than running full factorization. And for large enough numbers (which is what I'm assuming we're referring to here, since smaller numbers already go through trial division by default and will be fast to factor), actual factorization might be infeasible. But if this isn't the case, some more sophisticated strategy could be used. For the cache size to grow large that would imply that factorint has seen a large number of large prime factors. Again, a real workflow would be useful here, but I'm not seeing this becoming an issue.

**Comment by haru-44** [comment]
I am not consistently saying that the method you propose is unfeasible. I am simply pointing out that it does not appear to offer an advantage over the method of caching natural numbers and their prime factors. I would like you to present the benefits compared to the case where natural numbers and their prime factors are cached, rather than the current situation without caching. At present, the disadvantages I have already pointed out stand out more prominently.

**Comment by haru-44** [comment]
I thought it would be better to discuss after seeing the actual content, so I created the PR. Please consider this as an alpha version.

**Comment by oscarbenjamin** [comment]
If we are going to cache factorint then it would probably make sense to cache primes and possibly other operations in the same cache. Once factorint returns it also returns prime factors that could be cached for future calls to e.g. `isprime` as well as future calls to `factorint`.

It also might make sense to use `python-flint` for factorisation of integers when available:
```python
In [20]: r = random.randint(0, 10**100)

In [21]: %time factorint(r)
CPU times: user 1.31 s, sys: 7.68 ms, total: 1.32 s
Wall time: 1.32 s
Out[21]: 
{5: 1,
 293: 1,
 15739: 1,
 7055303: 1,
 7483449187: 1,
 3358277065269664199556260986278615803341739810760127139133198186387361389343: 1}

In [22]: %time ZZ(r).factor()
CPU times: user 166 ms, sys: 3.49 ms, total: 170 ms
Wall time: 169 ms
Out[22]: 
[(5, 1),
 (293, 1),
 (15739, 1),
 (7055303, 1),
 (7483449187, 1),
 (3358277065269664199556260986278615803341739810760127139133198186387361389343,
  1)]

In [23]: r
Out[23]: 4088356583282512248842760186692105999508619596982644555687858377475716950362738977029701052472435105
```

**Comment by haru-44** [comment]
> If we are going to cache factorint then it would probably make sense to cache primes and possibly other operations in the same cache. Once factorint returns it also returns prime factors that could be cached for future calls to e.g. `isprime` as well as future calls to `factorint`.

I agree with sharing the cache, but I can’t think of any functions other than `isprime` that could benefit from it.

> It also might make sense to use `python-flint` for factorisation of integers when available:

If we could completely rewrite `factorint`, the problem would become somewhat simpler, but it seems challenging to integrate `factorint` and `flint`'s `factor`. For instance, `factorint` has options like `limit` and `use_trial` that can’t be replicated in `factor`. Also, if we were to move it to `sympy.external`, we would need to move not only `factorint` but also many related functions like `pollard_rho` and `_ecm_one_factor`, which would require quite a substantial amount of work.
Even if I want to make it happen, I have no idea where to start.
