### ISSUE TITLE
Matrix equality fails when element has factor 1.0

### ISSUE THREAD

**Issue by Hyalunar** [sympy/sympy#27198]
The matrix comparison fails, when there is a one matrix element with the factor `1.0`, which should compare equal.

Setup:
- Python 3.12.6
- ipython 8.23.0
- sympy 1.13.3

Expected Behaviour:
- The matrices should compare equal
  
Observed Behaviour:
- The matrices do not compare equal

The matrix `A` raised to the power of 4 is the identity matrix of power 2, therefore `A == A**n` if `n%4 == 1`.
The difference between the matrices is exactly zero, they are not computed to be equal, I suspect this to be because of some floating-point shenanigangs with the factor `1.0`, 
```python
In [26]: A
Out[26]:
Matrix([
[1,     k],
[0, 1.0*I]])

In [27]: A**4
Out[27]:
Matrix([
[1,   0],
[0, 1.0]])

In [28]: A**5 == A
Out[28]: False

In [29]: A**5 == A**9
Out[29]: True

In [30]: A**5 - A
Out[30]:
Matrix([
[0, 0],
[0, 0]])

In [31]: A**5
Out[31]:
Matrix([
[1, 1.0*k],
[0, 1.0*I]])

In [32]: A
Out[32]:
Matrix([
[1,     k],
[0, 1.0*I]])


In [33]: A**9
Out[31]:
Matrix([
[1, 1.0*k],
[0, 1.0*I]])
```

the elements at `(0, 1)` in the matrices `A` and `A**5` are also not equal as seen here:
```python
In [1]: from sympy.abc import k

In [2]: import sympy

In [3]: A = sympy.Matrix([[1, k],[0, complex(0, 1)]])

In [4]: A[(0, 1)]
Out[4]: k

In [5]: (A**5)[(0, 1)]
Out[5]: 1.0*k

In [6]: type(_)
Out[6]: sympy.core.mul.Mul

In [7]: type(A[(0, 1)])
Out[7]: sympy.core.symbol.Symbol

In [8]: (A**5)[(0, 1)] == A[(0, 1)]
Out[8]: False
```

**Comment by oscarbenjamin** [comment]
This is expected:
```python
In [1]: x == 1.0*x
Out[1]: False
```
