### ISSUE TITLE
perfect_power(-64) fails to find (-4)**3

### ISSUE THREAD

**Issue by oscarbenjamin** [sympy/sympy#27238]
From SO: 
https://stackoverflow.com/questions/79172182/why-does-sympy-perfect-power-64-return-false

This is inconsistent:
```python
In [21]: perfect_power(-8)
Out[21]: (-2, 3)

In [22]: (-2)**3
Out[22]: -8

In [23]: perfect_power(-64)
Out[23]: False

In [24]: (-4)**3
Out[24]: -64
```
If it is supposed to work for negative numbers with odd exponent then the `-64` case is a bug.

The logic here is incorrect:
https://github.com/sympy/sympy/blob/91ab0d56601537db30574666941424d4c24f3083/sympy/ntheory/factor_.py#L521-L528
It checks if the exponent is even so in the case of `-64` we get:
```python
In [28]: perfect_power(64)
Out[28]: (2, 6)
```
This means that `64 = 2**6` but then that is `(2**2)**3` which has odd exponent. The proper check should be if the exponent is a power of `2`. If there is any odd factor then a negative perfect power can be found.

In general I think that it is a mistake to allow `perfect_power` to be defined for negative arguments but I guess it is too late for that.

**Comment by oscarbenjamin** [comment]
Another `perfect_power` bug:
```python
In [4]: perfect_power(S(2**9)/3**9)
Out[4]: (2/3, 9)

In [5]: perfect_power(S(2**9)/3**12)
Out[5]: (2, 9)
```
It would have been better if `perfect_power` had been left alone as a function for natural numbers rather than adding these other cases in gh-22672.

**Comment by aasim-maverick** [comment]
> Another `perfect_power` bug:
> 
> In [4]: perfect_power(S(2**9)/3**9)
> Out[4]: (2/3, 9)
> 
> In [5]: perfect_power(S(2**9)/3**12)
> Out[5]: (2, 9)

Is this expected behavior ? :

```python
>>> perfect_power(S(2**9)/3**12)
(8/81, 3)
```
