### ISSUE TITLE
mpf_normalize with non-mpz TypeError

### ISSUE THREAD

**Issue by sn6uv** [sympy/sympy#2724]
I've been getting the following traceback:

    File "/usr/lib/python2.7/site-packages/Mathics-0.6.0rc1-py2.7.egg/mathics/builtin/arithmetic.py", line 551, in apply
    sym_real = sym_real.n(dps(prec))
 
    File "/usr/lib/python2.7/site-packages/sympy-0.7.2-py2.7.egg/sympy/core/evalf.py", line 1215, in evalf
    re = C.Float._new(re, p)
 
    File "/usr/lib/python2.7/site-packages/sympy-0.7.2-py2.7.egg/sympy/core/numbers.py", line 621, in _new
    ok = mpf_normalize(sign, man, expt, bc, _prec, rnd)
 
    TypeError: argument is not an mpz

and I'm not sure why. `sym_real` is a sympy Float (I'm not quite sure how it's created).

The issue is that `sym_real._mpf_` is `(0, 5648393035369864705L, -63L, 63L)`, whereas normally the second element would be an `mpz` instance.

I see two possible solutions:
  - fix whatever's causing Floats to be created with `long` not `mpz` values
  - convert the `long` to a `mpz`  upon calling e.g. `sympy_Float.n(18)' etc.

**Comment by jcrist** [comment]
With no code available to reproduce, we can't easily diagnose the issue. @sn6uv , can you provide code to reproduce the issue? Otherwise, I'll close this.

**Comment by sn6uv** [comment]
I have since lost the code that caused this. I'll reopen if I find it again.
