### ISSUE TITLE
DOC: GenericDataSeries is missing

### ISSUE THREAD

**Issue by mgeier** [sympy/sympy#27240]
It has a docstring there:

https://github.com/sympy/sympy/blob/91ab0d56601537db30574666941424d4c24f3083/sympy/plotting/series.py#L2122

But I can't find the documentation at https://docs.sympy.org/dev/ (I would probably expect to find it in this page: https://docs.sympy.org/dev/modules/plotting.html).

The reason why I'm asking is because I'm interested in the behavior of the example plots.

I think `p._backend.ax[0]` should be changed to `p._backend.ax` and I'm wondering whether the plot is shown twice ...

**Comment by oscarbenjamin** [comment]
I guess it should be listed here somewhere:
https://github.com/sympy/sympy/blob/91ab0d56601537db30574666941424d4c24f3083/doc/src/modules/plotting.rst?plain=1#L55-L86
