### ISSUE TITLE
Command given in test runs all the test

### ISSUE THREAD

**Issue by curiousHG** [sympy/sympy#27265]
Documentation says to run a specific for a module use:
`./bin/test sympy/printing/pretty/tests/test_pretty.py::test_upretty_sub_super`

but this runs all the tests instead of the specific function

![Image](https://github.com/user-attachments/assets/00b87a15-59a0-4f21-9b6a-e9349f28761c)

**Comment by oscarbenjamin** [comment]
It should be:
```
pytest sympy/printing/pretty/tests/test_pretty.py::test_upretty_sub_super
```

**Comment by curiousHG** [comment]
I agree @oscarbenjamin, but the documentation mentions both and the first one should be removed if it is incorrect.
https://docs.sympy.org/dev/contributing/new-contributors-guide/writing-tests.html#running-tests

**Comment by oscarbenjamin** [comment]
The example could be changed to:
```
./bin/test sympy/printing/pretty/tests/test_pretty.py -k test_upretty_sub_super
```
