### ISSUE TITLE
Adding ways to send stop and continue signals for evaluation functions that can take much time.

### ISSUE THREAD

**Issue by mmatera** [sympy/sympy#27277]
In Mathics (https://github.com/Mathics3/mathics-core), we use Sympy to evaluate expressions.  In some cases, we want to limit the time used for the computation. For that, we put the evaluation in a thread, and if the evaluation takes more than a certain walltime, we abandon the thread and raise a Timeout Exception (see the original code here: https://github.com/Mathics3/mathics-core/blob/master/mathics/eval/sympy.py) 

The problem is that the evaluation continues, and continues consuming resources.  Suppose for example the expression is
```
sympy.integrate(sympy.sin(x)**100000, (x, 0, 1))
```
This reaches any reasonable walltime, and continues computing, until reaches a MaxRecursionError, or a core dump if the maxrecursion is set to a too large number.

It would be useful then to have a way to tell Sympy to stop the evaluation, and then resume it. Below is a simplified example of our code in Mathics ( https://github.com/Mathics3/mathics-core/blob/master/mathics/eval/sympy.py), and where the signals should be sent (`sympy.halt()` and `sympy.resume()`). 

```

from queue import Queue
from threading import Thread

import sympy
from sympy.abc import x


def eval_with_timeout(func, args, walltime=None):
    """

    Parameters
    ----------
    func : Callable
        long evaluation function, like `simplify` or `integrate`.
    args : Tuple
        the arguments of the function.
    walltime : int, optional
        DESCRIPTION. The default is None.

    Raises
    ------
    TimeoutError
        The evaluation was cancel because took too
        long time.

    Returns
    -------
        sympy expression.

    """
    if walltime is None:
        return func(*args)

    def _target(queue):
        args = queue.get()
        try:
            func_result = func(*args)
            queue.put((True, func_result))
        except BaseException as exc:
            queue.put((False, exc))

    queue = Queue(maxsize=1)
    queue.put(args)
    thread = Thread(target=_target, args=(queue,))
    thread.start()
    thread.join(walltime)
    if thread.is_alive():
        # Send the `halt` signal
        ##################
        # sympy.halt()
        ##################
        # Give the chance to allow `func`
        # to acknowledge the `halt` signal
        while thread.is_alive()
            thread.join(0.001)

        # Restore the "working" state
        ##################
        # sympy.resume()
        ###############
        raise TimeoutError

    # pick the result and return
    success, result = queue.get()
    if success:
        return result
    raise result


print("calling with a timeout of 10")
print("  result of type:", type(eval_with_timeout(sympy.integrate,
      (sympy.sin(x)**1000, (x, 0, 1)), walltime=10)))
print("calling with a timeout of 1")
print("  result of type:", type(eval_with_timeout(sympy.integrate,
      (sympy.sin(x)**1000, (x, 0, 1),), walltime=1)))
```

A simple way to implement these signals would be to implement methods that set a global variable `SYMPY_EVALUATION_HALTED`
and use `halt()` and `resume()` to change its state. Then, functions like `integrate` or `simplify` could check the state of this variable to see if the evaluation must be interrupted.

**Comment by bjodah** [comment]
And for stopping and resuming (and checkpointing) long running coputations: I think a separrate process is the way to go, and then you can use generic tools such as:
https://manpages.debian.org/unstable/criu/criu.8.en.html

**Comment by mmatera** [comment]
> When this discussion has come up before, the conclusion was that the user should use a 3rd party solution, e.g.: https://github.com/glenfant/stopit
> 
> See also:
> 
>     * [allow set of timeout when solving expressions #9691](https://github.com/sympy/sympy/issues/9691)
> 
>     * [`simplify` hangs for complex, trigonometric, surd expression  #26453](https://github.com/sympy/sympy/issues/26453)
> 
>     * [Add timeout facilities #24932](https://github.com/sympy/sympy/pull/24932)
> 
> 
> It would be interesting to hear if `stopit` works for you, and if it does: would it be helpful to mention it in the documentation somewhere?

Good! This looks useful! I will probe it in Mathics, and then I can tell you about the results.

**Comment by mmatera** [comment]
> > When this discussion has come up before, the conclusion was that the user should use a 3rd party solution, e.g.: https://github.com/glenfant/stopit
> > See also:
> > ```
> > * [allow set of timeout when solving expressions #9691](https://github.com/sympy/sympy/issues/9691)
> > 
> > * [`simplify` hangs for complex, trigonometric, surd expression  #26453](https://github.com/sympy/sympy/issues/26453)
> > 
> > * [Add timeout facilities #24932](https://github.com/sympy/sympy/pull/24932)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > It would be interesting to hear if `stopit` works for you, and if it does: would it be helpful to mention it in the documentation somewhere?
> 
> Good! This looks useful! I will probe it in Mathics, and then I can tell you about the results.

Indeed, `stopit` works very well. Also, as it encapsulates all the thread logic, there is no need to make any changes here.
