### ISSUE TITLE
Please help me with this issue

### ISSUE THREAD

**Issue by techwithsatish** [sympy/sympy#27295]
I have already submitted my .mailmap PR [here](https://github.com/sympy/sympy/pull/27292)

and unable to submit two PR of mine due to this issue and here is

- [My first PR](https://github.com/sympy/sympy/pull/27270) 
  - The [issue](https://github.com/sympy/sympy/actions/runs/11897876016?pr=27270)

- [My second PR](https://github.com/sympy/sympy/pull/27294) 
  - The [Issue ](https://github.com/sympy/sympy/actions/runs/11951743270?pr=27294)

- Please help me with this issue as soon as possible and waiting for your reply.

**Comment by oscarbenjamin** [comment]
You don't need to open an issue to discuss this, you can just comment on the pull request. Also it is not necessary to open a new pull request because you can just push changes to the existing pull request to fix the problem.
