### ISSUE TITLE
Unable to simplify expression with Mod

### ISSUE THREAD

**Issue by mstechly** [sympy/sympy#27304]
I have encountered the following expression: `expr = sympify("Mod(-a + b, c) + Mod(a - b, c)")`.
It always evaluates just to `c`, but using `simplify` doesn't simplify it this way.

After some tinkering I found out that if some of the numbers are complex, then it actually doesn't evaluate to `c`:

```
expr = sympify("Mod(-a + b, c) + Mod(a - b, c)")
expr.subs({"a": 10, "b": 2j, "c": 100})
```

`> Mod(10.0 - 2.0*I, 100) + Mod(90.0 + 2.0*I, 100)`

However, even when I recreated this expression to make sure all the variables are integers or real, it still doesn't simplify it properly.
```
a = symbols('a', real=True)
b = symbols('b', real=True)
c = symbols('c', real=True)
expr = Mod(a-b,c) +Mod(b-a, c)
simplify(expr)
```

`>Mod(-a + b, c) + Mod(a - b, c)` 

I'm curious whether there is any way to simplify such expression?

**Comment by haru-44** [comment]
`Mod(-a + b, c) + Mod(a - b, c)` becomes `3` when substituting `a=1, b=2, c=3`, but it becomes `0` when `a=1, b=1, c=3`. In general, I don't think this expression can be simplified.

**Comment by oscarbenjamin** [comment]
This simplifies automatically:
```python
In [3]: Mod(Mod(-a + b, c) + Mod(a - b, c), c)
Out[3]: 0
```

**Comment by mstechly** [comment]
Well, indeed, I missed this (quite obvious) case @haru-44 ...
Thanks @haru-44 and @oscarbenjamin !
I think we could close it?

**Comment by oscarbenjamin** [comment]
Yes, let's close this.
