### ISSUE TITLE
setup missing in CI

### ISSUE THREAD

**Issue by smichr** [sympy/sympy#27316]
Tests are failing because setup is missing. See [here](https://github.com/sympy/sympy/pull/27314#issuecomment-2499037402), for example, where the error reported is

```
Run bin/test_setup.py
Traceback (most recent call last):
  File "/home/runner/work/sympy/sympy/bin/test_setup.py", line 22, in <module>
    import setup
  File "/home/runner/work/sympy/sympy/setup.py", line 33, in <module>
    from setuptools import setup, Command
ModuleNotFoundError: No module named 'setuptools'
Error: Process completed with exit code 1.
```

**Comment by oscarbenjamin** [comment]
It isn't useful to open an issue like this with an inaccurate title, no description, no link  to anything else etc. You might as well just an open an issue saying "there is a problem".

What value do you think that this issue provides over just commenting somewhere else?

**Comment by smichr** [comment]
> What value do you think that this issue provides over just commenting somewhere else?

It lets anyone else running a test know that the issue has been reported and anyone that knows how to fix it will see that all (current) PRs are failing (which seems to happen often enough). 

Feel free to edit the title. I was just basing it off of what you told me in the PR where you commented about this.
