### ISSUE TITLE
Feature Add -> Made light and dark theme toggle button

### ISSUE THREAD

**Issue by SDprogramer** [sympy/sympy#27338]
After carefully analyzing the homepage of the SymPy website I have made a light and dark theme toggle button along the base.html file in templates and dark.css and light.css file in sidebar folder inside static.

photos and screenshots are attached to it
![Image](https://github.com/user-attachments/assets/ca5495c0-d6c3-47e5-a5b3-49124685cc8a)
![Image](https://github.com/user-attachments/assets/36d5851a-8dda-4ebd-9088-9238db924942)
![Image](https://github.com/user-attachments/assets/66a238d8-b3d4-4082-ad8d-cf874492b07b)

Now can you please tell me how to check if this is working or not in the development server

**Comment by oscarbenjamin** [comment]
It would be good to add this to the website but this isn't the right repo for the website.

**Comment by SDprogramer** [comment]
Ohh okay then I will add the code to the website repo

**Comment by SDprogramer** [comment]
https://github.com/sympy/sympy.github.com 
Is this the SymPy website repo ??

**Comment by oscarbenjamin** [comment]
Yes, I think so. There are instructions there for how to generate and test the website.

I'll close this issue since it isn't an issue in the sympy codebase itself.
