### ISSUE TITLE
solve on simple equation gives NotImplementedError (multiple generators)

### ISSUE THREAD

**Issue by klmcwhirter** [sympy/sympy#27330]
This example comes from this video: [MindYourDecisions](https://youtu.be/NiHH0OuKSS4)

Here is  a link to the [Wolfram Alpha solutions](https://www.wolframalpha.com/input?i=2%5Ex+*+3%5E%28x%5E2%29+%3D+6).

Consider this sympy (version 1.14.1 with python 3.13.0) code:

```python
import sympy as sym

x = sym.symbols('x')

expr = 2**x * 3**(x**2)
print('expr = ', expr)

eq = sym.Equality(expr, 6)
print('', eq)

sols = sym.solve(eq, x)
print(sols = ', sols)
```

I expected sympy to find `x = { 1, - log(6) / log(3) }` or `x = { 1, -1 - ln(2) / ln(3) }`.

But, get `NotImplementedError: multiple generators [2**x, 3**(x**2)]` instead.

Using solveset produces a solution that is not simplified:

```math
\displaystyle sols = \left\{x\; \middle|\; x \in \mathbb{C} \wedge 2^{x} 3^{x^{2}} - 6 = 0 \right\}
```

Note that passing `x**2` as a symbol to solve produces a result:
```math
\displaystyle sols = \left[ \frac{\log{\left(6 \cdot 2^{- x} \right)}}{\log{\left(3 \right)}}\right]
```

Declaring `x` as real : `x = sym.symbols('x', real=True)` results in the same behavior for both solve (error) and solveset (not simplified in complex domain).

**Comment by klmcwhirter** [comment]
Note I was able to finally get the solutions from the video by manually applying his steps in turn.

```pythonsym_display_latex
import sympy as sym

x = sym.symbols('x', real=True)

# apply first few steps from video manually
# expr = 2**x * 3**(x**2)
# eq = sym.Eq(expr, 6)

# note that 6 is 2^1 * 3^1
# expr = (2**(x - 1) * 3**(x**2 - 1)) / (2**-1 * 3**-1)
# expr = 2**(x - 1) * 3**(x**2 - 1)
# eq = sym.Eq(expr, 1)

# expr = sym.log(2**(x - 1) * 3**(x**2 - 1))
# expr = sym.log(2**(x - 1)) + sym.log(3**(x**2 - 1))
# expr = (x - 1) * sym.log(2) + (x**2 - 1) * sym.log(3)  # get sols here, but 2nd sol needs reduction
# expr = (x - 1) * sym.log(2) + (x - 1) * (x + 1) * sym.log(3)  # no help with reduction from this step

expr = (x - 1) * (sym.log(2) + (x + 1) * sym.log(3))
print('expr = ', expr)

eq = sym.Eq(expr, sym.log(1))  # note: ln1 = 0
print('eq = ', eq)

sols = sym.solveset(eq, x)
print('sols = ', sols)```

**Comment by klmcwhirter** [comment]
I then tried to replicate the Wolfram Alpha result - and did so successfully; but only with solve. solveset gives different result that needs simplification.

```python
x = sym.symbols('x', real=True)

# try to replicate Wolfram Alpha result - https://www.wolframalpha.com/input?i=2%5Ex+*+3%5E%28x%5E2%29+%3D+6

# expr = 2**x * 3**(x**2)
# eq = sym.Eq(expr, 6)

# expr = sym.log(2**x * 3**(x**2))
# expr = sym.log(2**x) + sym.log(3**(x**2))
# expr = x * sym.log(2) + (x**2) * sym.log(3)  # get sols here, needs reduction
# eq = sym.Eq(expr, sym.log(6))

# expr = (x * sym.log(2) + (x**2) * sym.log(3)) / sym.log(6)

# note that ln(6) is ln(2) + ln(3)
expr = (x * sym.log(2) + (x**2) * sym.log(3)) / (sym.log(2) + sym.log(3))  # <== this step did it

eq = sym.Eq(expr, 1)

from IPython.display import display, Math
sym_display_latex = lambda msg, basic: display(Math(f'{msg} {sym.latex(basic)}'))

# if not running in jupyter notebook
# sym_display_latex = print

sym_display_latex('expr = ', expr)
sym_display_latex('eq => ', eq)

# sols = sym.solveset(eq, x)  # note the difference !!!

sols = sym.solve(eq, x)  # ===============> GOT IT
sym_display_latex('sols = ', sols)
```

```math
\displaystyle sols =  \left[ 1, \  - \frac{\log{\left(6 \right)}}{\log{\left(3 \right)}}\right]
```

solveset provides this result:

```math
\displaystyle sols =  \left\{1, \frac{- \log{\left(3 \right)} - \log{\left(2 \right)}}{\log{\left(3 \right)}}\right\}
```

Note that:
```math
\displaystyle - \log{3} - \log{2} = -1 [\log{3} + \log{2}] = -\log{6}
```

This seems to be missing from solveset in this case.

If I add the following code after the call to solveset then I get the same output as solve.
```python
...
sols = sym.solveset(eq, x)  # note the difference !!!

sols = [s for s in sols]
sol1: sym.Mul = sols[1]
num, denom = sol1.as_numer_denom()
num = sym.logcombine(num)
sols[1] = num / denom
...
```

However, if I simply call `sols[1] = sym.logcombine(sols[1])` instead of just on the numerator then I get this undesirable result:

```math
\displaystyle sols =  \left[ 1, \  - \log{\left(6^{\frac{1}{\log{\left(3 \right)}}} \right)}\right]
```

I hope this helps.

**Comment by oscarbenjamin** [comment]
I guess it is just a question of recognising somewhere that this can be rewritten:
```python
In [33]: x = symbols('x')

In [34]: eq = 2**x * 3**(x**2) - 6

In [35]: eq.rewrite(exp)
Out[35]: 
 ⎛ 2⋅log(x)⎞              
 ⎝ℯ        ⎠  x⋅log(2)    
3           ⋅ℯ         - 6

In [36]: eq.rewrite(exp).rewrite(exp)
Out[36]: 
            2           
 x⋅log(2)  x ⋅log(3)    
ℯ        ⋅ℯ          - 6

In [37]: eq.rewrite(exp).rewrite(exp).powsimp()
Out[37]: 
  2                      
 x ⋅log(3) + x⋅log(2)    
ℯ                     - 6

In [38]: solve(eq.rewrite(exp).rewrite(exp).powsimp(), x)
Out[38]: 
⎡     _________________________                        _________________________⎤
⎢    ╱    2         ⎛ log(81)⎞                        ╱    2         ⎛ log(81)⎞ ⎥
⎢- ╲╱  log (2) + log⎝6       ⎠  - log(2)  -log(2) + ╲╱  log (2) + log⎝6       ⎠ ⎥
⎢───────────────────────────────────────, ──────────────────────────────────────⎥
⎣               2⋅log(3)                                 2⋅log(3)               ⎦
```
I'm not sure why that last result comes out so complicated when it should be possible to just invert the equation.

In general equations like this are unlikely to have analytic solutions unless they can be rewritten so that solving is a sequence of inverting polynomial, algebraic or single elementary functions. There are therefore two basic cases that solve needs to be able to recognise:

- a polynomial function of a single transcendental function e.g. `E**f(x) + E**(2*f(x)) - 6 -> y + y**2 - 6`.
- transcendental functions that can be combined `2**f(x)*3**g(x) - 6 -> (exp(f(x)*log(2) + g(x)*log(3)) - 6`.

If neither case arises as in `2**x + 3**x - 6` then no analytic solution is possible.

**Comment by klmcwhirter** [comment]
@oscarbenjamin Thanks for the input. I have not used the rewrite mechanism before. I'll do a deep dive into that and report back here.

BTW, I have seen those last solutions in my work above, but got to them in a very different way. It is good to see that there is at least some internal consistency. Also, I notice you using solve and not solveset. I guess I should stop worrying about solve being removed anytime soon ;)

**Comment by klmcwhirter** [comment]
@oscarbenjamin This FAQ implies it by the use of the word "yet". I thought I saw something within the last year that used stronger wording. I got the impression from that piece (cannot remember whether it was in the docs or source somewhere) that solve was already in "soft deprecation" and will eventually be replaced by solveset.

But for now, I think the addition of a firm statement at the end along the lines of your comment above would help clarify.

> `solve` will not be removed.

https://docs.sympy.org/latest/modules/solvers/solveset.html#what-is-the-plan-for-solve-and-solveset

**Comment by klmcwhirter** [comment]
@oscarbenjamin , I spent most of today working with rewrite and expand - passing an object containing all the kwargs set explicitly for what I was testing at the moment.

I think I have come to the conclusion that I just need a couple more years experience working with sympy to learn how to work around things like this. This is the first problem I have encountered that has given me so much head scratching trouble.

And that is probably due to the fact that I have at best a Calc 2 skill level. But, I am retired and am just having fun as a math nerd.

I recognize the vast expert system built into sympy. And am grateful to be able to use it - even though much of it is over my head.

Is there any value in keeping this issue open? If not, I can close it.

**Comment by oscarbenjamin** [comment]
> This FAQ implies it by the use of the word "yet"

All such wording should be removed. There are problems with solve but solveset does not even remotely serve as a replacement for its functionality so there should be no suggestion that solve will be removed. Some of the problems of solve are inherent to the fact that it provides an explicit list of substitutions and solveset only improves on that by failing to provide a list of substitutions. That is no use to someone who wants a list of substitutions!

**Comment by klmcwhirter** [comment]
OK. I can fork and provide a fork on the docs. That much I can do.

Should I include wording like what you provided above? I see you are a project Collaborator. Is there someone else in the project who acts as "Docs Owner" that I should check with?

Thank you again for the help. I'll go ahead and close this issue and open a different one after I see your response.

**Comment by oscarbenjamin** [comment]
I think if you open a PR then we can discuss/refine the exact wording. There is no need to check with anyone else: once a PR is opened then anyone can review or comment.

**Comment by klmcwhirter** [comment]
I am closing this after working with @oscarbenjamin and then doing some more homework that helped me realize I just need more experience with `sympy`.

I am satisfied with the need to do some post-processing on the output from `solve` to get the solution to look like what I want. That feels reasonable to me.

**Comment by klmcwhirter** [comment]
For future readers ...

This is what I saw in the docs that led me to believe `solve` was deprecated. It seems like that was the original plan.

> was changed in commit 30919652 2 yrs ago - not sure when the change was published

```
What will you do with the old solve?
------------------------------------

 There are still a few things ``solveset`` can't do, which the old ``solve``
 can, such as solving nonlinear multivariate & LambertW type equations.
 Hence, it's not yet a perfect replacement for old ``solve``. The ultimate
 goal is to:

 * Replace ``solve`` with ``solveset`` once solveset is at least as powerful as
   ``solve``, i.e., ``solveset`` does everything that ``solve`` can do
   currently, and

 * eventually rename ``solveset`` to ``solve``.
```

The docs were changed in commit 30919652 to read:

```
What is the plan for solve and solveset?
----------------------------------------

There are still a few things ``solveset`` can't do, which ``solve`` can, such
as solving nonlinear multivariate & LambertW type equations.  Hence, it's not
yet a perfect replacement for ``solve``. As the algorithms in ``solveset``
mature, ``solveset`` may be able to be used within ``solve`` to replace some of
its algorithms.
```

But see #27332 for clarifying changes being made as I write this.

FYI
