### ISSUE TITLE
Why doesn't expectation of Poisson random variable just return lambda?

### ISSUE THREAD

**Issue by Evidlo** [sympy/sympy#27344]
I find the behavior of some aspects of Sympy to be utterly bizarre.  For example, take these two lines:

``` python
>>> E(Poisson('xxx', np.float64(4.72544290380919e-11)))
4.72544290358589e-11*exp(472544290380919/10000000000000000000000000)
>>> E(Poisson('xxx', np.float64(4.725442903809197e-11)))
...
ValueError: Could not calculate 2 terms for 0.999999999952746*exp(4.7254429038092e-11*exp(_x))
```

Clearly some kind of floating point error is occurring here, but why?

The expectation of a Poisson random variable is λ, so why not just return the original argument?  Instead `E(...)` is returning `e^λ * (λ / e^λ)` and creating precision issues.

Does it have something to do with the generation of Nth moment, and if so why isn't it reduced to λ before evaluation?

**Comment by haru-44** [comment]
`sympy.stats.drv_types.PoissonDistribution` does not implement `expectation`, so `sympy.stats.drv.SingleDiscreteDistribution.expectation` is used instead. This method employs a general approach to calculate the expected value using the moment-generating function. Overriding `expectation` in `PoissonDistribution` should resolve the issue.

```python
def expectation(self, expr, var, evaluate=True, **kwargs):
    if evaluate:
        # E[X] = lamda
        if expr == var:
            return self.lamda
        # E[X(X-1)...(X-n+1)] = lamda**n
        from sympy.functions.combinatorial.factorials import FallingFactorial
        if isinstance(expr, FallingFactorial) and expr.args[1].is_integer and expr.args[1].is_positive and expr.args[0] == var:
            return self.lamda**expr.args[1]
    return super().expectation(expr, var, evaluate, **kwargs)
```
