### ISSUE TITLE
Plot simple region, bug in plot_implicit

### ISSUE THREAD

**Issue by proy87** [sympy/sympy#27342]
I want to try to plot a region bounded from above and below by curves. What is the best way to do it?
I'm trying to plot a inside the circle and outside the hyperbola (`x**2+y**2<=25, x**2-y**2<=16`).
I'm trying to use `plot_implicit`, but it doesn't show the full region.
`(x >= -4 ∧ x <= 4 ∧ y <= sqrt(25 - x**2) ∧ y >= -sqrt(25 - x**2)) ∨ (x >= 4 ∧ x <= sqrt(82)/2 ∧ y >= sqrt(x**2 - 16) ∧ y <= sqrt(25 - x**2)) ∨ (x <= -4 ∧ x >= -sqrt(82)/2 ∧ y >= sqrt(x**2 - 16) ∧ y <= sqrt(25 - x**2)) ∨ (x >= 4 ∧ x <= sqrt(82)/2 ∧ y <= -sqrt(x**2 - 16) ∧ y >= -sqrt(25 - x**2)) ∨ (x <= -4 ∧ x >= -sqrt(82)/2 ∧ y <= -sqrt(x**2 - 16) ∧ y >= -sqrt(25 - x**2))`

Should I split it on subintervals?

**Comment by oscarbenjamin** [comment]
Does this work?

```
plot_implicit((x**2+y**2<=25) & ~(x**2-y**2<=16))
```

**Comment by proy87** [comment]
@oscarbenjamin , it works. fine.

**Comment by oscarbenjamin** [comment]
Is there a bug here or is this issue just to ask how to do the plot?

**Comment by proy87** [comment]
@oscarbenjamin `plot_implicit((x**2+y**2<=25) & ~(x**2-y**2<=16))` works but `(x >= -4 ∧ x <= 4 ∧ y <= sqrt(25 - x**2) ∧ y >= -sqrt(25 - x**2)) ∨ (x >= 4 ∧ x <= sqrt(82)/2 ∧ y >= sqrt(x**2 - 16) ∧ y <= sqrt(25 - x**2)) ∨ (x <= -4 ∧ x >= -sqrt(82)/2 ∧ y >= sqrt(x**2 - 16) ∧ y <= sqrt(25 - x**2)) ∨ (x >= 4 ∧ x <= sqrt(82)/2 ∧ y <= -sqrt(x**2 - 16) ∧ y >= -sqrt(25 - x**2)) ∨ (x <= -4 ∧ x >= -sqrt(82)/2 ∧ y <= -sqrt(x**2 - 16) ∧ y >= -sqrt(25 - x**2))` doesn't work.

**Comment by oscarbenjamin** [comment]
Can you show runnable code for the condition?

Are you sure that the more complicated conditions are equivalent?

**Comment by proy87** [comment]
They are not equivalent.
The complicated condition doesn't show all region. It misses the values between `-4` and `4`.

**Comment by oscarbenjamin** [comment]
I'm confused here. What exactly is the bug? Can you show at least a screen shot of the plot and explain what is wrong with it?

Ideally it would be best to show runnable code that demonstrates clearly what you are doing.

**Comment by proy87** [comment]
Sorry, I mixed up the code.
