### ISSUE TITLE
Sin^2 x + Cos^ 2 Not simplified.

### ISSUE THREAD

**Issue by Harrilee** [sympy/sympy#27356]
My test

```python

from sympy import *
import sympy

x, y = symbols('x y')
expr = (sin(x)**2 + cos(x)**2) + 2 * (x + y) ** 2 + 2 * (x + y) ** 3

print(simplify(expr))
print(sympy.__version__)

```

Reuslt
```
2*(x + y)**3 + 2*(x + y)**2 + sin(x)**2 + cos(x)**2
1.14.dev
```

Expected Result
```
2*(x + y)**3 + 2*(x + y)**2 + 1
```

**Comment by bjodah** [comment]
All but the most trivial simplifications are opt-in, that is: you will need to call the relevant simplification method (or try with the swiss army-knife `sympy.simplify` which applies a bunch of simplification methods).
```python
>>> (x**2 + sin(x)**2 + cos(x)**2).trigsimp()
 2    
x  + 1
```

**Comment by Harrilee** [comment]
But when removing the last item, `simplify((sin(x)**2 + cos(x)**2) + 2 * (x + y) ** 2)` gives `2*x**2 + 4*x*y + 2*y**2 + 1`. Is that what we expect?

**Comment by bjodah** [comment]
I'm guessing you would have preferred a factorized expression? If an expression completely factorizes, it's enough to call `factor` on it:
```python
>>> factor(x**2 - y**2)
(x - y)*(x + y)
```
However, if only part of the expression can participate in the factorization, this fails:
```python
>>> factor(x**2 - y**2 + 1)
x**2 - y**2 + 1
```
So we want a "smarter" factor function, this is a rather common request, I have multiple versions of such a function written by @smichr on the mailing list and in answers on stackoverflow, I'm not up to date on whether any of those are included in sympy itself nowadays, but adapting [one of his functions](https://groups.google.com/g/sympy/c/dxcMAhk8XRM/m/W8kBrjb0IUgJ):
```python
>>> simp = simplify((sin(x)**2 + cos(x)**2) + 2 * (x + y) ** 2)
>>> simp
   2              2    
2⋅x  + 4⋅x⋅y + 2⋅y  + 1
>>> def my_factor(expr):
...     const, nonconst = expr.as_coeff_Add()
...     cand0 = factor(nonconst) + const
...     candidates = {cand0: cand0.count_ops()}
...     for fs in expr.free_symbols:
...         i, d = expr.as_independent(fs, as_Add=True)
...         cand = factor(i) + factor(d)
...         candidates[cand] = cand.count_ops()
...     print(f"{candidates=}")  # debug print, remove in production
...     return min(candidates, key=candidates.__getitem__)
... 

>>> my_factor(simp)
candidates={2*(x + y)**2 + 1: 4, 2*x**2 + 2*y*(2*x + y) + 1: 8, 2*x*(x + 2*y) + 2*y**2 + 1: 8}
         2    
2⋅(x + y)  + 1

```

**Comment by Diya910** [comment]
I want to contribute to this issue can you assign me this task?

**Comment by bjodah** [comment]
@Diya910 we don't really assign issues in the SymPy project, anyone can work on any issue they find interesting/useful.

@Harrilee, feel free to reopen this issue and add more questions if you have any.
