### ISSUE TITLE
sympy.physics.mechanics.find_dynamicsymbols() does not detect dynamic symbols that have operations in the argument.

### ISSUE THREAD

**Issue by chris-konrad** [sympy/sympy#27418]
## Issue description

An expression $x(t-t_0)$ is a dynamic symbol that depends on the time $t$ and a parameter $t_0$. However, `sympy.physics.mechanics.find_dynamicsymbols()` does not find such symbols in an expression because it only looks for symbols whose argument exactly equals the time symbol.

https://github.com/sympy/sympy/blob/b4ce69ad5d40e4e545614b6c76ca9b0be0b98f0b/sympy/physics/mechanics/functions.py#L479-L480

I am not sure if this behaviour is generally desired. But for my application (estimating a time delay in a parameter identification problem), it would be nice to detect symbols with arguments that have operations on the time symbol as dynamic symbols as well. 

## Reproduce the issue

The following code is an example of sympy not finding the expression $x(t-t_0)$.

``` Python
import sympy as sm

x, y = sm.symbols('x, y', cls=sm.Function)
t, t_0 = sm.symbols('t, t_0')

eom = y(t) - x(t - t_0) + 2 * x(t).diff(t)

print(sm.physics.mechanics.find_dynamicsymbols(eom))
```

## Potential fix

The issue can be easily resolved by checking for arguments whose set of parameters include the time variable rather then exclusively being the time variable. For example, replace L479-L480 from above with:

``` Python
    return {i for i in expression.atoms(AppliedUndef, Derivative) if
            len(i.free_symbols.intersection(t_set)) == 1} - exclude_set
```

**Comment by moorepants** [comment]
The definition of a "dynamic symbol" in mechanics is strictly defined as `Function('f')(dynamicsymbols._t)`, where `'f'` can be any string. It simply distinguishes what SymPy objects in an expression are constant with respect to time and what are functions of time.

There currently is no use of something like f(t-t0) in sympy mechanics, so I don't see that we should support that. I recommend writing a simple function like `find_dynamicsymbols()` in your own code to find what you are looking for.

Changing the function may have consequences that aren't expected in code in other libraries and scripts that use sympy mechanics, as the behavior has been to return only f(t) for about 15 years now.

**Comment by chris-konrad** [comment]
Alright, thanks for the explanation. I understand. 

Implementing workarounds on per-case basis should be fine.
