### ISSUE TITLE
Printing matrix symbols with ...

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#2748]
See http://stackoverflow.com/q/20885374/161801. It would be useful to be able to print matrix symbols with symbolic number of rows or columns like `[y1, y2, ..., yn]`.

**Comment by jcrist** [comment]
A pull request was made for this, and then rejected due to lack of need. Is this still an issue, or can it be closed? @asmeurer @smichr

**Comment by jcrist** [comment]
Closing, due to lack of need. If anyone disagrees, please reopen/open a new issue.
