### ISSUE TITLE
S.UniversalSet + Interval(0, oo) takes forever.

### ISSUE THREAD

**Issue by hargup** [sympy/sympy#2799]

**Comment by rpisarev** [comment]
I want to help, so I created pull request https://github.com/sympy/sympy/pull/10643. 
I think, in one-dimensional space Universal Set is the set of everyone of real numbers or interval (-oo, oo).

Yes, of course it breaks tests for Universal Set

assert U.union(Interval(2, 4)) == U

assert U.intersect(Interval(2, 4)) == Interval(2, 4)

But maybe, its wrong test? 
I can remove this test or we can decide about change in Universal Set.

**Comment by asmeurer** [comment]
Just because you have an interval doesn't automatically make the domain of interest just the real numbers. UniversalSet is an abstract set that contains everything, so UniversalSet.union(anything) should give UniversalSet.

**Comment by rpisarev** [comment]
Yes, I have already understood it, so my last commit return UniversalSet.
