### ISSUE TITLE
Host code for Python/Numpy to Sympy conversion

### ISSUE THREAD

**Issue by hunse** [sympy/sympy#2810]
I've been working on some code to convert Python/Numpy functions to Sympy, so that they can then be converted to C++/Fortran (or in my case OpenCL) code using Sympy's code printing facilities.

Is Python/Numpy to Sympy conversion something that the Sympy project would be interested in hosting? It seems like something that would fit nicely in the project, though from what I can tell the codegen module is still in infancy and will need expansion to handle things like if statements and loops. It would be great for me to have my code hosted as part of a developed project like Sympy, because it will get more exposure and the community can help improve it.

**Comment by jcrist** [comment]
Closing, as not a specific issue. Please reopen/create a new issue with smaller scope if you disagree.

**Comment by aadya940** [comment]
Hey folks! I built a tool that converts Python and NumPy programs to SymPy Expressions. Since this thread is directly relevant, posting it here:
[https://github.com/aadya940/scikit-verify](https://github.com/aadya940/scikit-verify)
