### ISSUE TITLE
Custom functions named gamma are dispatched to the specialized gamma function printer

### ISSUE THREAD

**Issue by moorepants** [sympy/sympy#2832]
```
In [6]: from sympy import Function, latex, symbols

In [7]: gamma = Function('gamma')

In [8]: latex(gamma)
Out[8]: '\\gamma'

In [9]: latex(gamma(symbols('x')))
Out[9]: '\\Gamma\\left(x\\right)'
```

**Comment by asmeurer** [comment]
Looks like a special case fix was implemented for gamma in the pretty printer https://github.com/sympy/sympy/blob/ad7222648393e5befb9dd06e875cd312d0542c96/sympy/printing/pretty/pretty.py#L1262 https://github.com/sympy/sympy/pull/11919, but I still think all the printers should do the behavior I described above where UndefinedFunctions don't dispatch to named printers.  And either way, the LaTeX printer was not fixed.

**Comment by asmeurer** [comment]
As pointed out in #13556, there is another bug in the pretty printer:

```
>>> pprint(Function('gamma')(x, y))
γ(x)
```

It drops the `y`. There could be similar bugs with other functions that assume they have a single argument. So we should definitely fix UndefinedFunction objects to just not dispatch to the Function subclass printers.
