### ISSUE TITLE
lambdify inserts numpy after math

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#2866]
If you call `lambdify` without setting the `modules` argument, it defaults to `['math', 'mpmath', 'sympy']`. If numpy is available, it inserts it after `['math']`. Why does it do this? It seems that numpy is the most common usage of lambdify, so it should come first.

**Comment by Shekharrajak** [comment]
* Math module should be at first , because when we install `Sympy` we install math module also , so all the functions works without any other dependencies.
* If `NumPy` would be at first ,then if user haven't installed the `NumPy` module it will throw `can't import numpy` error.If it is installed then it works fine.May be that's why [this line 
](https://github.com/sympy/sympy/blob/master/sympy/utilities/lambdify.py#L310) is there to check availability of  `NumPy` and then we add that into module.
* If we change the order now we need to solve some problems(mostly mapping) to  pass all checks.

**Comment by asmeurer** [comment]
If numpy is not installed I believe it is skipped entirely (correct me if I am wrong).

**Comment by moorepants** [comment]
I may agree that NumPy should be first. Here are some thoughts:

- User has Python, mpmath, and SymPy installed, so order of preference should be: math, mpmath, sympy.
- Python, mpmath, SymPy, and NumPy: numpy, math, mpmath, sympy.
- Python, mpmath, SymPy, NumPy, SciPy: scipy, numpy, math, mpmath, sympy (SciPy imports the top level of NumPy namespace).
- If numexpr is installed, I think we should default to scipy/numpy as they are much more ubiquitous. numexpr should probably only be used if the user wants it explicitly, as it can't be combined with the other modules.

The goal of lambdify is to provide faster execution, so the preference order for the modules should help meet that goal.

**Comment by Shekharrajak** [comment]
@asmeurer 
If `NumPy` isn't installed then it [pass](https://github.com/sympy/sympy/blob/master/sympy/utilities/lambdify.py#L314) and continue executing from [this line](https://github.com/sympy/sympy/blob/master/sympy/utilities/lambdify.py#L319) without adding `numpy` is modules list.
* Similarly for `Scipy` also it [should be added](https://github.com/sympy/sympy/pull/10319/files#diff-16366e978f6ce314c0fa904081d58c24R372) in modules.I was also confused about index for `scipy`.

* I have checked this with virtualenv and PuDB, to run my test cases during solving some issues.In one env numpy,scipy is installed and in other env only sympy is installed.

###### If we want faster execution we should add `NumPy`  at 0th index in modules list. it passes all checks also.
I am agree with @moorepants last comment.

**Comment by asmeurer** [comment]
IMHO lambdify's mixing and matching of different libraries is confusing. NumPy/SciPy, mpmath, math, and SymPy all provide four different kinds of functions that each work on different data types (numpy.array, mpf, float, and symbolic expressions, resp.). In particular, if the input is a numpy array, then only numpy/scipy functions make sense. Additionally (this is unrelated to this issue but related to Jason's comment), the fact that lambdify works at all with SymPy expressions, and has a SymPy "backend" is very confusing to users in my experience.

**Comment by moorepants** [comment]
I agree Aaron. "explicit is better than implicit" would make lambdify less confusing and I don't really see any need to have the mpmath or sympy backends.
