### ISSUE TITLE
iterable() function is a mess

### ISSUE THREAD

**Issue by skirpichev** [sympy/sympy#2886]
We must rename this function and document it, see [this pr](https://github.com/sympy/sympy/pull/2829).  What we, probably, want here - `finite_iterable` or `is_finite_iterable`, i.e. we should additionally check if len(i) < oo is True (and doesn't raise an exception).

Also, I don't sure if using `iter()` is intentional (and not something like `hasattr(i, '__iter__')`).  In the next function `is_sequence` we have 'and'ed test `hasattr(i, '__getitem__') and iterable(i)`.  But `iter()` already has test for `__getitem__`!  See this:
http://docs.python.org/2/library/functions.html#iter
http://docs.python.org/3/library/functions.html#iter

**Comment by oscarbenjamin** [comment]
What is there to solve here? Is it just renaming iterable to is_iterable?

**Comment by smichr** [comment]
One of the concerns in the issue referenced was "iterable docstring doesn't define what's a Sympy's iterable". The docstring states:

>As a rule of thumb, some SymPy functions use this to check if they should
    recursively map over an object. If an object is technically iterable in
    the Python sense but does not desire this behavior (e.g., because its
    iteration is not finite, or because iteration might induce an unwanted
    computation), it should disable it by setting the _iterable attribute to False.

So I think this can be closed.
