### ISSUE TITLE
limit((x*exp(x))/(exp(x)-1), x, -oo) gives -oo

### ISSUE THREAD

**Issue by skirpichev** [sympy/sympy#2929]
`gruntz()` - returns correct answer, 0.

@asmeurer 

> Ah, so it seems that these incorrect limit heuristics have still not
> been completely abolished from the code base.

Yes, `e.is_Mul` branch is still here.  It's a workaround for test_issue2856 (last test).

**Comment by oscarbenjamin** [comment]
Current master gives the correct answer:
```julia
In [1]: limit((x*exp(x))/(exp(x)-1), x, -oo)
Out[1]: 0
```

**Comment by smichr** [comment]
could use a test
