### ISSUE TITLE
incorrect behavior in the latex output

### ISSUE THREAD

**Issue by andreacortis** [sympy/sympy#2934]
I am trying to define the representation of a symbol as a latex fraction

If denominator and numerator of the fraction do not have subscripts, the representation is  correct

   In [1]: print sympy.latex(sympy.Symbol(r'\frac{a}{b}'))
   \frac{a}{b}

But when you add subscripts the sympy representation breaks down

   In [4]: print sympy.latex(sympy.Symbol(r'\frac{a_1}{b_1}'))
   \frac{a_{1}{b 1}}

**Comment by smichr** [comment]
Here's a kickstart for this issue that passes `bin/test latex`:

```diff
diff --git a/sympy/printing/latex.py b/sympy/printing/latex.py
index a8c905c..61634a0 100644
--- a/sympy/printing/latex.py
+++ b/sympy/printing/latex.py
@@ -1240,7 +1240,31 @@ def _print_Symbol(self, expr):
         if expr in self._settings['symbol_names']:
             return self._settings['symbol_names'][expr]

-        return self._deal_with_super_sub(expr.name)
+        # process anything in braces for super/subscripts first
+        s = expr.name
+        # get a token holder
+        tok = '~'
+        while tok in s:
+            tok += "~"
+        tok = tok + "%i" + tok
+        # recursively swap out the brace-surrounded expressions
+        i = 0
+        subs = {}
+        while True:
+            braced = set(re.findall(r'(\{ *[^{}]+\})', s))
+            if not braced:
+                break
+            for b in braced:
+                v = tok % i
+                subs[i] = (v, self._deal_with_super_sub(b))
+                s = s.replace(b, v)
+                i += 1
+        # now deal with the symbol as a "name"
+        s = self._deal_with_super_sub(s)
+        # and restore braced expressions
+        for k in subs:
+            s = s.replace(*subs[k])
+        return s
```

**Comment by smichr** [comment]
I believe it passes the issue, too:

```
>>> from sympy import *;latex(Symbol(r'\frac{a_1}{b_1}'))
'\\frac{a_{1}}{b_{1}}'
```

**Comment by asmeurer** [comment]
I think it would be better to just apply some heuristic to see if a Symbol is already LaTeX (say, `'\\' in s.name`) and not apply any transformations in that case.

**Comment by smichr** [comment]
That sounds good, @asmeurer: keep it simple. In addition multiple subscripts or superscripts should also indicate that no parsing should be done (so x_1_2 should not be parsed with Symbol's version of parser).

Summary: if you use latex in the symbol you are responsible for making it do what you want, otherwise the non-latex parsing will be done for you so x_first will become x_{first}.
