### ISSUE TITLE
Indefinite integration problems: wrong result.

### ISSUE THREAD

**Issue by isturunt** [sympy/sympy#2949]
### update
#8688 fixed the integration. The degree error was fixed some time before that:

```python
>>> integrate((5.5*x + 10)*exp(2.3*x), x, risch=False)  # fails before #8688 commit
2.39130434782609*x*exp(2.3*x) + 3.30812854442344*exp(2.3*x)
>>> Poly(-8.88178419700125e-16*x + 7.60869565217391, x, domain='RR') .degree()
0
```

So all that needs to be done is to add tests.

-------------------------- original issue description:

The problem appears when one tries to calculate indefinite integrals of type integrate(exp(a*x)*(b * x + c), x ) with some custom values of a, b and c. For example:
```python
>>> x = symbols('x')
>>> integrate((5.5*x + 10)*exp(2.3*x), x)
0
```
It returns 0 while it shouldn't. But sometimes these calculations are done properly:
```python
>>> integrate((5.6*x + 10)*exp(2.3*x), x)
(2.43478260869565*x + 3.28922495274102)*exp(2.3*x)
```
The problem can be solved using parameters and substitutions:
```python
>>> x, a, b, c = symbols('x a b c')
>>> pw = integrate(exp(a*x)*(b*x + c), x)
>>> pw
Piecewise((b*x**2/2 + c*x, a**3 == 0), ((a**2*b*x + a**2*c - a*b)*exp(a*x)/a**3, True))
>>> simplify(pw.subs([(a, 2.3), (b, 5.5), (c, 10)]))
(2.39130434782609*x + 3.30812854442344)*exp(2.3*x)
```
But I think the integrate algorithm should be touched up.

**Comment by smichr** [comment]
The degree error was fixed by

```
commit 9dea2b3a88af98412949d325c3ef6ddd985feb56
Merge: 1ca8cbc 466ec0f
Author: Aaron Meurer <asmeurer@gmail.com>
Date:   Sat Apr 19 19:38:30 2014 -0500

    Merge pull request #7360 from jcrist/issue7263

    Changed tol on Complex and Real field to None
```

which was addressing the issue of watching Floats so I will not add a test for this specific instance of the problem.

**Comment by asmeurer** [comment]
`integrate((5.5*x + 10)*exp(2.3*x), x, risch=False) ` still gives 0.

**Comment by jcrist** [comment]
Fixed in current master. Closing.

```
>>> integrate((5.5*x + 10)*exp(2.3*x), x, risch=False)
2.39130434782609*x*exp(2.3*x) + 3.30812854442344*exp(2.3*x)
```
