### ISSUE TITLE
Multiple dispatch

### ISSUE THREAD

**Issue by mrocklin** [sympy/sympy#2972]
I started yet another multiple dispatch project here http://github.com/mrocklin/multipledispatch

This generated some discussion between @ellisonbg and myself about the use of multiple dispatch in SymPy here https://github.com/mrocklin/multipledispatch/issues/2

We decided that this discussion should happen on a SymPy issue.

**Comment by oscarbenjamin** [comment]
I don't quite understand what this issue is for. Presumably things have moved on since 2012. Is this already implemented in sympy or elsewhere or no longer relevant?

**Comment by jksuom** [comment]
I think that this has been included as the [multipledispatch module](https://github.com/sympy/sympy/commit/a0323c9b57eb31b632fd02b2674856164c91293e#diff-fc39936bdec47022b32946bce0be4c93).

**Comment by smichr** [comment]
And work toward making this part of SymPy is underway in #14490 which references this issue so this initiation of discussion can be closed.
