### ISSUE TITLE
Unicode printing in IPython qtconsole is messed up

### ISSUE THREAD

**Issue by temp4746** [sympy/sympy#2974]
Unicode printing in the IPython console seems messed up, it just uses the glyph for a lowercase 'a' as a replacement character for almost all unicode chars.

Here's an example:
![bug](https://f.cloud.github.com/assets/2670892/2292317/be574a32-a056-11e3-82e8-72acccc24efc.PNG)

In input `#6` where I just printed `sympy.I` it used the latex printer and printed ok. (I use matplotlib mathtext which I think why Sympy might be trying to use the unicode printer for some things instead of latex for everything)
With the rest trying to use the unicode printer and showing those weird 'a' characters instead of something legible.

Using `sympy.init_printing(use_unicode=False)` is a temporary workaround for now, but I would much like this to work properly so that I can enjoy unicode printing in the IPython qt console.

Using:
* Windows 7 SP1 64-Bit
* Python 2.7.6 32-Bit
* Sympy 0.7.5
* Matplotlib 1.3.1 (Pyparsing 2.0.1, python-dateutil 2.2, six 1.5.2, tornado 3.2, backports.ssl-match-hostname 3.4.0.2)
* Numpy 1.8.0
* IPython 1.2.1 (Pygments 1.6, pyzmg 14.0.1)
* Tried both PyQt4 and PySide

**Comment by jcrist** [comment]
Tested in master on linux, issue isn't present. Can someone with windows verify?

**Comment by flacjacket** [comment]
On Windows 0.7.6, the lists/dicts/Matrices print just fine with latex output.

**Comment by jcrist** [comment]
Closing then.
