### ISSUE TITLE
make Add._eval_power handle Float coefficients better

### ISSUE THREAD

**Issue by jbayless** [sympy/sympy#2993]
I'm not sure if this has been reported before because I'm not exactly sure how to describe it. But I find that sympy is generating some expressions which have some constant factors rather strangely factored out in places, such as this:

```
-0.647*x -2.15e-16*sqrt(-5.669e+29*x**4 - 2.961e+30*x**3 -4.999e+30*x**2 -2.961e+30*x-5.669e+29)
```

This particular output was created by calling solve(eq, y) on an equation that was quadratic in y and quartic in x. The code below will generate the output above.

```
eq = 0.0121787141081027*x**4 + 0.0636077296587915*x**3 + 0.302270434899319*x**2 + 0.15709634216953*x + 0.465497194955889*y**2 + y*(0.60235044978107*x + 0.144496237696458) + 0.0233920806625508

expr = solve(eq,y)

expr[1]
```

The coefficients in the input equation were all fairly close to 1, so I don't understand why sympy decided to pull 2e-16 out of the square root while at the same time multiplying everything under the radical sign by 4e+32. More importantly, I can't find any simplification commands that will convince sympy to factor those coefficients back in. In addition to making the equation needlessly long and messy, it can introduce loss of precision when numerically evaluating the output.

Any suggestions?

**Comment by smichr** [comment]
`solve` casts Float as Rational while solving and restores them to Floats when done. It should do the clean up of the extractions like this that were made. A workaround in the meanwhile is:
```python
>>> def fold(eq):
...   muls = eq.atoms(Mul)
...   reps = {}
...   for i in muls:
...      c, m = i.as_coeff_Mul()
...      if c.is_Float:
...        for mi in Mul.make_args(m):
...           if mi.is_Pow and mi.exp == S.Half and mi.base.has(Float):
...             reps[i] = m/mi*sqrt(mi.base*c**2)
...   return eq.xreplace(reps)
...
>>> [fold(i) for i in expr]
[-0.646996863040334*x + sqrt(-0.026162808799002*x**4 - 0.136644710962907*x**3 -
0.230744696925304*x**2 - 0.136644710962907*x - 0.0261628087990018) - 0.155206346
313376, -0.646996863040334*x + sqrt(-0.026162808799002*x**4 - 0.136644710962907*
x**3 - 0.230744696925304*x**2 - 0.136644710962907*x - 0.0261628087990018) - 0.15
5206346313376]
```

**Comment by smichr** [comment]
`solveset` rescales polys so the maximum coefficient is 1. That would be another possibility to use for solve:
```
>>> solveset(eq,y)
{-0.646996863040334*x - 0.480358925102161*sqrt(-0.113384225716231*x**4 - 0.59219
0038530512*x**3 - 1.0*x**2 - 0.59219003853051*x - 0.11338422571623) - 0.15520634
6313376, -0.646996863040334*x + 0.480358925102161*sqrt(-0.113384225716231*x**4 -
 0.592190038530512*x**3 - 1.0*x**2 - 0.59219003853051*x - 0.11338422571623) - 0.
155206346313376}
```

**Comment by smichr** [comment]
`Mul` already extracts a Float from within the power so `sqrt(0.04*x)` -> `0.2*sqrt(x)`. Add could be smarter about Floats and then the original OP issue would be solved. Here is some new processing added to `Add._eval_power`:
```
old = Add._eval_power
def new(self, e):
    if e.is_Number:
      c, m = zip(*[i.as_coeff_Mul() for i in self.args])
      if all(i.is_Float for i in c):
        big = max([abs(i) for i in c])
        if big != 1:
          return big**e*Add(*[m[i]*c[i]/big for i in range(len(c))])**e
    return old(self, e)
Add._eval_power = new
```
old result (in master)
```
sqrt(0.23*x + 0.4)
(0.23*x + 0.4)**0.3
```
new
```
0.632455532033676*sqrt(0.575*x + 1.0)
0.759657792932374*(0.575*x + 1.0)**0.3
```
If this change is made then whatever special processing Poly does to make this happen would not be necessary (but that might be harder to extract/track down).

**Comment by zachetienne** [comment]
This issue needs to be reopened and repatched. As reported in https://github.com/sympy/sympy/issues/17735, it causes a severe breakage of SymPy (i.e., **wrong results**). The following minimal example (courtesy @isuruf), coupled to this patch in particular yields an erroneous sign flip.

```python
from sympy import *
x = symbols('x')
expr = 0.5*exp(x) + 0.1 - 0.5*exp(-x)
print(expr)
print(expr**2)
```
Reverting this patch fixes the issue.
