### ISSUE TITLE
objects with indices (tensors)

### ISSUE THREAD

**Issue by certik** [sympy/sympy#3115]
bc.. Let's get inspired by ginac. This code should make it easy to compute for
example einstein equations from the (symbolic) metric tensor. We can do it
already now, but it would be nice to type in equations in the index form as
found in the general relativity books and then just plug in a symbolic
matrix for the metric tensor, and it would figure all the rest by itself.

p. Original issue for "#3115":https://github.com/sympy/sympy/issues/3115: "http://code.google.com/p/sympy/issues/detail?id=16":http://code.google.com/p/sympy/issues/detail?id=16

p. Original author: "https://code.google.com/u/104039945248245758823/":https://code.google.com/u/104039945248245758823/

**Comment by asmeurer** [comment]
Things are always improving, but we have indexed object and mathematical tensor support now. New issues should be opened for anything that isn't yet implemented.
