### ISSUE TITLE
assumptions for "bounded" (over different domains)

### ISSUE THREAD

**Issue by certik** [sympy/sympy#3141]
bc.. I think this should return sqrt(x**2+y**2):

In [1]: abs(x+I_y)
Out[1]: abs(x+i_y)

It used to work, but you commented out the relevant tests - do you think
it's wrong? I believe it's true for all x,y real. So the abs_.eval() should
work for this.

p. Original issue for "#3141":https://github.com/sympy/sympy/issues/3141: "http://code.google.com/p/sympy/issues/detail?id=42":http://code.google.com/p/sympy/issues/detail?id=42

p. Original author: "https://code.google.com/u/104039945248245758823/":https://code.google.com/u/104039945248245758823/

**Comment by oscarbenjamin** [comment]
The OP problem is solved now:
```
In [1]: x = Symbol('x', real=True)

In [2]: y = Symbol('y', real=True)

In [4]: abs(x+I*y)
Out[4]: 
   _________
  ╱  2    2 
╲╱  x  + y  
```
Various other things are discussed in this issue but it seems that most are implemented in the current (old) assumptions system.

**Comment by oscarbenjamin** [comment]
I think this can be closed now
