### ISSUE TITLE
ironpython porting

### ISSUE THREAD

**Issue by sympy-issue-migrator** [sympy/sympy#3159]
bc.. Currently ironpython raises this exception:

> > > from sympy import *
> > > Traceback (most recent call last):
> > >   File **init**, line unknown, in Initialize
> > >   File **init**, line unknown, in Initialize
> > >   File symbol, line unknown, in Initialize
> > >   File numbers, line unknown, in Initialize
> > >   File basic, line unknown, in **call**
> > >   File basic, line unknown, in **call**
> > > AttributeError: type object 'AutomaticEvaluationType' has no attribute 'eval'

p. Original issue for "#3159":https://github.com/sympy/sympy/issues/3159: "http://code.google.com/p/sympy/issues/detail?id=60":http://code.google.com/p/sympy/issues/detail?id=60

p. Original author: "https://code.google.com/u/111543943295681634297/":https://code.google.com/u/111543943295681634297/

**Comment by asmeurer** [comment]
Iron Python seems to be Python 2 only, which we are dropping support for later this year. I don't think many people have much interest in it anymore.
