### ISSUE TITLE
Square root denesting

### ISSUE THREAD

**Issue by sympy-issue-migrator** [sympy/sympy#3192]
bc.. Just an idea: implement the "square root denesting" ideas of http://www.almaden.ibm.com/cs/people/fagin/symb85.pdf doesn't look to complicated.
I am happy to work on this after the prettyprinter works: that we can see what we are doing :-)
- Jurjen

p. Original issue for "#3192":https://github.com/sympy/sympy/issues/3192: "http://code.google.com/p/sympy/issues/detail?id=93":http://code.google.com/p/sympy/issues/detail?id=93

p. Original author: "https://code.google.com/u/105448442912468869732/":https://code.google.com/u/105448442912468869732/

**Comment by smichr** [comment]
An upgrade as described [here](https://github.com/sympy/sympy/issues/3192#issuecomment-36981425) is pending (according to the history here).

**Comment by sylee957** [comment]
I think that this issue can be closed now because I see the final algorithm of
http://researcher.watson.ibm.com/researcher/files/us-fagin/symb85.pdf is implemented in `_sqrtdenest_rec`
