### ISSUE TITLE
tests on the wiki documentation

### ISSUE THREAD

**Issue by sympy-issue-migrator** [sympy/sympy#3200]
bc.. it shouldn't be too difficult to tests the examples in the wiki the same 
way as we test the examples in the source code ...

so that it's always up to date

p. Original issue for "#3200":https://github.com/sympy/sympy/issues/3200: "http://code.google.com/p/sympy/issues/detail?id=101":http://code.google.com/p/sympy/issues/detail?id=101

p. Original author: "https://code.google.com/u/103948515893177094863/":https://code.google.com/u/103948515893177094863/

**Comment by oscarbenjamin** [comment]
I don't think this is needed any more
