### ISSUE TITLE
Plot linear maps

### ISSUE THREAD

**Issue by sympy-issue-migrator** [sympy/sympy#3281]
bc.. It would be nice, if there was some support to visualize the effect of,
say, a 2x2 matrix on points of the real plane. I've used a small program
sometimes, where one could enter the matrix, and then just draw in the
plane in blue, while watching the image drawn in red. That way, a beginner
in linear algebra could easily understand scaling, rotations etc.

I once tried to do a similar thing in 3D with vtk, where one could enter a
3x3 matrix and could place some object, for example a colored cube in a 3D
render window, to see the image of the cube. It worked quite well, but I
didn't get interaction working (and all code is lost).

I don't know if someone has ideas on this, but it would be a nice learning
tool, if you could also display eigenvectors and kernels of the linear map,
for example.

p. Original issue for "#3281":https://github.com/sympy/sympy/issues/3281: "http://code.google.com/p/sympy/issues/detail?id=182":http://code.google.com/p/sympy/issues/detail?id=182

p. Original author: "https://code.google.com/u/116277859734487035258/":https://code.google.com/u/116277859734487035258/

p. Original owner: "https://code.google.com/u/116277859734487035258/":https://code.google.com/u/116277859734487035258/

**Comment by oscarbenjamin** [comment]
This is a nice idea that could be added as an example in the notebook examples but it seems more like something that someone could do with sympy rather than something that sympy should have code for. This has been open for 13 years and it hasn't happened so I'm going to close this.
