### ISSUE TITLE
Sums and products

### ISSUE THREAD

**Issue by fredrik-johansson** [sympy/sympy#3284]
bc.. See the newly added module sums_products.py

The class Sum is entirely analogous to Integral. It can currently do basic
sums involving polynomial and geometric terms. There is also a skeleton
Product class, but it lacks functionality yet.

I'm opening this issue for general discussion and feature requests. First
of all, I guess if there are any objections to the present code
organization/nomenclature/interface, that should be dealt with immediately.

The next step, I think, should be to support sums and products of rational
functions. If the object function is written as a combination of linear
factors, i.e. f(n) = (n+r_1)_(n+r_2)_..._(n+r_i) /
((n-s_1)_(n-s_2)_..._(n-s_j)), the product of f(n) from a to b from can be
calculated easily with factorials/gamma functions, and the analogous sum
can be done with polygamma functions. I wonder, are there already functions
present in SymPy for rewriting a rational function to linearly factored
form (this would be quite convenient)?

p. Original issue for "#3284":https://github.com/sympy/sympy/issues/3284: "http://code.google.com/p/sympy/issues/detail?id=185":http://code.google.com/p/sympy/issues/detail?id=185

p. Original author: "https://code.google.com/u/111502149103757882156/":https://code.google.com/u/111502149103757882156/

p. Original owner: "https://code.google.com/u/101069955704897915480/":https://code.google.com/u/101069955704897915480/

**Comment by oscarbenjamin** [comment]
I think everything above has been implemented. I'm sure that plenty more can be done but I don't think we need this old issue.
