### ISSUE TITLE
Assumptions and their effect on substitution

### ISSUE THREAD

**Issue by thegedge** [sympy/sympy#3363]
bc.. I was just thinking about it, and was looking for some thoughts.

> > > x = Symbol('x', negative=True)
> > > x.is_negative
> > >    True
> > > x.subs(x, 5)
> > >    5

The issue is the substitution line, and the fact that a positive value is
being substituted for something that isn't positive. I think substitute
should only substitute values if their assumptions correspond exactly
(maybe not quite exactly?).

I know that if a programmer/user does exactly what I done above it would
probably be considered a silly action but automated code might do something
of that nature and a programmer might want their script to be able to pick
this up, via some exception.

p. Original issue for "#3363":https://github.com/sympy/sympy/issues/3363: "http://code.google.com/p/sympy/issues/detail?id=264":http://code.google.com/p/sympy/issues/detail?id=264

p. Original author: "https://code.google.com/u/inferno1386/":https://code.google.com/u/inferno1386/

p. Original owner: "https://code.google.com/u/inferno1386/":https://code.google.com/u/inferno1386/

**Comment by oscarbenjamin** [comment]
It's too late now to change this.
