### ISSUE TITLE
plotting on macos x freezes

### ISSUE THREAD

**Issue by certik** [sympy/sympy#3408]
bc.. I don't have a macosx, but when I was presenting at SciPy2007, I borrowed a
Mac OS X laptop and sympy was working well (with python2.5), except plotting:

Plot(x*y)

worked fine, then I did:

Plot(sin(x)*cos(y))

and the plotting window stopped responding (the "hour" cursor when moved
over it with mouse). I think it happened always when I called Plot for the
second time.

It would be nice, if someone with macosx could verify that && fix that.

p. Original issue for "#3408":https://github.com/sympy/sympy/issues/3408: "http://code.google.com/p/sympy/issues/detail?id=309":http://code.google.com/p/sympy/issues/detail?id=309

p. Original author: "https://code.google.com/u/104039945248245758823/":https://code.google.com/u/104039945248245758823/

p. Original owner: "https://code.google.com/u/115549613129666820104/":https://code.google.com/u/115549613129666820104/

**Comment by oscarbenjamin** [comment]
SymPy uses matplotlib for plotting now.
