### ISSUE TITLE
intelligent simplification

### ISSUE THREAD

**Issue by certik** [sympy/sympy#3448]
bc.. Mateusz wrote:

Now some interesting results:

In [1]: integrate(cot(x), x)
Out[1]: -1/2*log(1 + tan(x)**2) + log(tan(x))

In [2]: integrate(1/tan(x), x)
Out[2]: -1/2*log(1 + tan(x)**2) + log(tan(x))

In [3]: integrate(cos(x)/sin(x), x)
Out[3]: log(sin(x))

There are two conclusions. The resulting expression is highly dependent on
the input
form, so maybe I should add some additional preprocessing steps to make the
output
automatically more pretty and to cut down on the size of intermediate
expressions
(improving computation times). Another thing is that no matter how good the
preprocessing steps were, we need "intelligent" simplification routines to
handle
cases [1, 2] (in fact Mathematica's FullSimplify[] can't transform [1, 2]
-> [3]).

Ondrej: yes, let's do it, so that we can finally get to the ground, where
even Mathematica cannot compete with us. :))

p. Original issue for "#3448":https://github.com/sympy/sympy/issues/3448: "http://code.google.com/p/sympy/issues/detail?id=349":http://code.google.com/p/sympy/issues/detail?id=349

p. Original author: "https://code.google.com/u/104039945248245758823/":https://code.google.com/u/104039945248245758823/

**Comment by oldk1331** [comment]
In SymPy 1.0:
````
In [1]: integrate(cot(x), x)
Out[1]: 
   ⎛   2       ⎞
log⎝cos (x) - 1⎠
────────────────
       2        

In [2]: integrate(1/tan(x), x)
Out[2]: 
   ⎛   2       ⎞
log⎝cos (x) - 1⎠
────────────────
       2        

In [3]: integrate(cos(x)/sin(x), x)
Out[3]: 
   ⎛   2       ⎞
log⎝cos (x) - 1⎠
────────────────
       2        
````

This issue can be closed.

**Comment by oldk1331** [comment]
`log(cos(x)**2-1)/2` is complex, thus not a good enough answer.
Similar reason, `-1/2*log(1 + tan(x)**2) + log(tan(x))`, `log(sin(x))` is not good,
but `log(sin(x)**2)/2`, `log(tan(x)**2/(1+tan(x)**2))/2`, `log((1-cos(2*x))/2)/2` is good answer.

Reopening this.
