### ISSUE TITLE
API design

### ISSUE THREAD

**Issue by certik** [sympy/sympy#3486]
bc.. I created a wiki: http://code.google.com/p/sympy/wiki/SymPySvn that documents how things are done in the current svn trunk. Please use
this issue for discussing and arriving at the "one-- and preferably only
one --obvious way to do" things. 

Before we close this issue, we need to agree on: 
- how to work with unapplied functions? and lambdas?
- is the current way of dealing with applied functions ok?
- if you don't like the way I proposed in the wiki, let's discuss it and
  change it if we agree on something better

Let's just use one "coding style" all over sympy, both inside and outside.
If there are exceptions to this (i.e. Basic.One, vs 1), it should be
documented in the wiki.

p. Original issue for "#3486":https://github.com/sympy/sympy/issues/3486: "http://code.google.com/p/sympy/issues/detail?id=387":http://code.google.com/p/sympy/issues/detail?id=387

p. Original author: "https://code.google.com/u/104039945248245758823/":https://code.google.com/u/104039945248245758823/

**Comment by oscarbenjamin** [comment]
There is an obvious scalability problem with the `is_Class` approach:
https://github.com/sympy/sympy/blob/ecbb8368b11aa7122aaaf3688594d7dad30ac18e/sympy/core/basic.py#L80-L109

In any case I don't think this issue needs to kept open.
