### ISSUE TITLE
limits for complex variables

### ISSUE THREAD

**Issue by certik** [sympy/sympy#3496]
bc.. I am fixing limits and there are problems with assumptions.

Some things, like log(exp(x)) won't simplify for x complex and the
algorithm will completely break down. So one needs to explicitely set all
symbols to real. Which brings me to our old issue, to resolve the
assumptions in some way.

p. Original issue for "#3496":https://github.com/sympy/sympy/issues/3496: "http://code.google.com/p/sympy/issues/detail?id=397":http://code.google.com/p/sympy/issues/detail?id=397

p. Original author: "https://code.google.com/u/104039945248245758823/":https://code.google.com/u/104039945248245758823/

**Comment by oscarbenjamin** [comment]
This is fixed now:
```python
In [10]: z = Symbol('z', real=True)

In [11]: log(exp(z))
Out[11]: z

In [12]: z = Symbol('z', complex=True)

In [13]: log(exp(z))
Out[13]: 
   ⎛ z⎞
log⎝ℯ ⎠
```
