### ISSUE TITLE
caching mechanism

### ISSUE THREAD

**Issue by certik** [sympy/sympy#3528]
bc.. There are several different way how caching is done in SymPy. One can use
@cache_it, @cache_it_immutable and Order is using it's own caching system,
_cache.

I think there should be only one way how to cache things and it should be
completely transparent - i.e. one just comments out the @cache_it and
everything will still be working (albeit slower).

The Order caching should be converted to @cache_it or @cache_it_immutable
(do we need these two?), if it is possible to do it in a way, that doesn't
slow things down.

p. Original issue for "#3528":https://github.com/sympy/sympy/issues/3528: "http://code.google.com/p/sympy/issues/detail?id=429":http://code.google.com/p/sympy/issues/detail?id=429

p. Original author: "https://code.google.com/u/104039945248245758823/":https://code.google.com/u/104039945248245758823/

**Comment by oscarbenjamin** [comment]
I think that this is mostly done although some issues remain as described in #17731
