### ISSUE TITLE
Symbol.__call__ should not create a Function

### ISSUE THREAD

**Issue by certik** [sympy/sympy#3539]
bc.. sympycore now has a working implementation of how to work with unapplied
functions easily. There are related bugs in sympy now, for example:

In [1]: a = Symbol("exp")

In [2]: a(z)
Ignoring redefinition of exp: <class
'sympy.functions.elementary.exponential.exp'> defined earlier than <class
'sympy.core.function.exp'>
Out[2]: exp(z)

There should be one and only one way of creating new functions, be it
Function("something"), or Symbol("something")(x), or whatever, that's fine,
as long as it's just one way.

Let's implement that in sympy and fix all related issues.

p. Original issue for "#3539":https://github.com/sympy/sympy/issues/3539: "http://code.google.com/p/sympy/issues/detail?id=440":http://code.google.com/p/sympy/issues/detail?id=440

p. Original author: "https://code.google.com/u/104039945248245758823/":https://code.google.com/u/104039945248245758823/

**Comment by bjodah** [comment]
Possibly related: gh-9064
