### ISSUE TITLE
ironpython: AttributeError: 'dictproxy' object has no attribute 'get'

### ISSUE THREAD

**Issue by sympy-issue-migrator** [sympy/sympy#3552]
bc.. Trying to use with IRONPython and get the error below:

  File C:\Python24\Lib\site-packages\sympy__init__.py, line 4, in 
Initialize
  File , line 0, in _stub_##2
  File C:\Python24\Lib\site-packages\sympy\core__init__.py, line 26, in 
Initialize
AttributeError: 'dictproxy' object has no attribute 'get'

Any thoughts?

p. Original issue for "#3552":https://github.com/sympy/sympy/issues/3552: "http://code.google.com/p/sympy/issues/detail?id=453":http://code.google.com/p/sympy/issues/detail?id=453

p. Original author: "https://code.google.com/u/115961875564935506885/":https://code.google.com/u/115961875564935506885/

**Comment by oscarbenjamin** [comment]
I doubt this is still relevant.
