### ISSUE TITLE
pure python latex math printing? (no tex/latex dependency)

### ISSUE THREAD

**Issue by certik** [sympy/sympy#3605]
bc.. Imho matplotlib has a python reimplementation of the tex math engine. Maybe
we can reuse it/improve it. This would be probably worth a separate
project. Depending on latex clearly sucks. But imho, what is needed is just
the algorithm in python, plus fonts. All of which can be imho shipped in
the separate project and we'd just include it in sympy.

p. Original issue for "#3605":https://github.com/sympy/sympy/issues/3605: "http://code.google.com/p/sympy/issues/detail?id=506":http://code.google.com/p/sympy/issues/detail?id=506

p. Original author: "https://code.google.com/u/104039945248245758823/":https://code.google.com/u/104039945248245758823/

p. Original owner: "https://code.google.com/u/104039945248245758823/":https://code.google.com/u/104039945248245758823/

**Comment by oscarbenjamin** [comment]
Is this resolved by using Mathjax in the docs and Jupyter now?
