### ISSUE TITLE
what to be added to the wiki.sympy.org

### ISSUE THREAD

**Issue by certik** [sympy/sympy#3658]
bc.. google now for some time allows to sort the issues as we want, so if you go to: http://code.google.com/p/sympy/issues/list the first issues are the ones with a milestone set, the rest is sorted
according to a priority.
Usually, the time each of us can put into sympy is scattered - so what
I do is that I
just open the issues and try to fix some of the top ones.

So the priority should be set according to what is best for sympy. So
my proposition:
- critical - those that need to be fixed right now (maybe some failing
  tests, etc.)
- high - all usability issues reported by users, that are quite easy
  to fix, like integrate() method not working
  for some particular integral, or **nonzero** working, or bad
  cooperation with numpy etc. This is very
  important to get fixed, because if the user reported it, it means it's
  important for them, and
  most of it is quite easy for us to fix
- normal - all other bugs - either difficult to fix (if we are not
  even sure about the approach), or just enhancements, etc.
- low - the rest

Also, maybe let's write xfailing tests for reported issues _before_
fixing them?

This way we will be able to see that some issue is fixed automatically
by other change.

Yes, but only later -- time is the issue. And one can always forget...

So let's accept this practice?

p. Original issue for "#3658":https://github.com/sympy/sympy/issues/3658: "http://code.google.com/p/sympy/issues/detail?id=559":http://code.google.com/p/sympy/issues/detail?id=559

p. Original author: "https://code.google.com/u/104039945248245758823/":https://code.google.com/u/104039945248245758823/

**Comment by oscarbenjamin** [comment]
This doesn't seem relevant any more:

1. We no longer use google code so the part specific to that no longer applies
2. There are so many open issues. Marking them with priority doesn't seem to affect when anyone does to fix them.

I think this should be closed.
