### ISSUE TITLE
nouns vs verbs

### ISSUE THREAD

**Issue by certik** [sympy/sympy#3660]
bc.. Kirill suggested:

I think Maxima uses generic approach to nouns v.s. verbs -- quoting:

'diff -- diff
'integrate -- integrate
'limit -- limit
etc...

quoting prevents eveluation of symbolic tree.

Maybe we should add some generic mechanism like quoting to SymPy as well?
So the user will have ability to construct exactly symbolic tree as he wants.

p. Original issue for "#3660":https://github.com/sympy/sympy/issues/3660: "http://code.google.com/p/sympy/issues/detail?id=561":http://code.google.com/p/sympy/issues/detail?id=561

p. Original author: "https://code.google.com/u/104039945248245758823/":https://code.google.com/u/104039945248245758823/

**Comment by oscarbenjamin** [comment]
Some of the issues here are still relevant but we don't need to keep this old issue open for them.
