### ISSUE TITLE
series expansion of acosh and acoth

### ISSUE THREAD

**Issue by certik** [sympy/sympy#3663]
bc.. Those are series are calculated by SymPy now:

assert acosh(x).series(x, 6) == pi_I/2 - I_x - 3_I_x**5/40 - I*x**3/6 + O(x**6)
assert acoth(x).series(x, 6) == x + x**3/3 + x**5/5 + pi*I/2 + O(x**6)

However, Maxima (Sage) returns the same series, but with I replaced by -I.
Let's check what is correct. It probably depends on the definition of acosh
and acoth (there are probably more options). Let's get this documented, in
docstrings.

p. Original issue for "#3663":https://github.com/sympy/sympy/issues/3663: "http://code.google.com/p/sympy/issues/detail?id=564":http://code.google.com/p/sympy/issues/detail?id=564

p. Original author: "https://code.google.com/u/104039945248245758823/":https://code.google.com/u/104039945248245758823/

**Comment by pinballwiz17** [comment]
Is the issue still open ? If so can I please give it a try ? I'm a newbie so I would appreciate any pointers before starting on. Thanks

**Comment by czgdp1807** [comment]
@pinballwiz17 I think you can test the various examples on the latest `master`. If they give correct results then we can close this issue otherwise feel free to make a PR for it.

**Comment by pinballwiz17** [comment]
I have tested it for sample cases such as 0,oo,zoo,etc, but for other cases if I use evalf and N to find say acosh(-2) it only displays the real part of the answer.

**Comment by oscarbenjamin** [comment]
At least the result for sympy here should be consistent with mpmath:
```
In [85]: acoth(x).series(x, n=6).removeO().subs(x, 0.01).n()
Out[85]: 0.0100003333533333 + 1.5707963267949⋅ⅈ

In [86]: acoth(0.01)
Out[86]: 0.0100003333533348 - 1.5707963267949⋅ⅈ
```
