### ISSUE TITLE
Use numpy.array or numpy.matrix like syntax for matrix-operations

### ISSUE THREAD

**Issue by sympy-issue-migrator** [sympy/sympy#3745]
bc.. When playing around with the matrix operations in sympy I got quite
confused since the used syntax is not conistent with numpy syntax.
The follwing link gives a good overview for differences between the two: http://www.scipy.org/NumPy_for_Matlab_Users? action=show&redirect=NumPy+for+Matlab+Addicts

I would suggest to stick to the numpy.array convention since arrays are 
the more general concept and numpy.matrix operations are limited to the 
two dimensional arrays. So if one day one likes to extend the abilities of 
sympy to higher dimensional arrays it is easier to do this and at the same 
time to stay consistent to numpy.

Alo, when doing number crunching with numpy I frequently find myself using 
elementwise operations. e.g. the follwing example
A= 
[3 4
 5 7]
B= 
[x y
 z a)
then in numpy.array A_B=
[3_x 4_y
 5_z 7*a]

If the dimensions of A and B would not be the same this would raise and 
error.

equivalently in numpy.array: 
b**2=
[x**2 y**2
 z**2 a**2]

In numpy.array the function dot(A,B) would lead to the matrix 
multiplication and dot(B,B) would lead to matrix multiplication with 
itself.

Also in numpy.array:
exp(B)=
[exp(x) exp(y)
 exp(z) exp(a)]

I think the advantages of a consitent syntax are obvious for everybody who 
is using numpy and sympy at the same time. Of course I am aware of the 
fact that numpy is not the only matrix number crunching implementation and 
you might prefer to stick to a different convention.
Keep up the good work!

p. Original issue for "#3745":https://github.com/sympy/sympy/issues/3745: "http://code.google.com/p/sympy/issues/detail?id=646":http://code.google.com/p/sympy/issues/detail?id=646

p. Original author: "https://code.google.com/u/110757295363610591147/":https://code.google.com/u/110757295363610591147/

**Comment by moorepants** [comment]
I read through this and don't think any of it is relevant anymore.  SymPy matrices are strictly 2D matrices and the syntax is now well established. It matches NumPy where it can. I'm closing. Feel free to reopen if there are relevant parts to today's SymPy.
