### ISSUE TITLE
generate documentation from tests

### ISSUE THREAD

**Issue by certik** [sympy/sympy#3787]
bc.. Let's write a script, that parses all our tests and generates a nice (html
or pdf -- rather both) documentation out of it. 

It will be like "sympy in examples" type of doc. This is usually the most
useful, as I don't like reading some boring reference manuals (I can look
into the sources!), but being able to easily see by examples how to use
things, that would be cool.

p. Original issue for "#3787":https://github.com/sympy/sympy/issues/3787: "http://code.google.com/p/sympy/issues/detail?id=688":http://code.google.com/p/sympy/issues/detail?id=688

p. Original author: "https://code.google.com/u/104039945248245758823/":https://code.google.com/u/104039945248245758823/

**Comment by oscarbenjamin** [comment]
This is a nice idea but we don't need to keep this old issue open for it

**Comment by asmeurer** [comment]
I think it's a bad idea. Tests aren't supposed to be documentation and documentation isn't supposed to be tests.  If a function doesn't have sufficient examples, we should fix that by adding well thought out examples to its documentation, not referring people to its tests.
