### ISSUE TITLE
copy (not move) isympy to isympy.py

### ISSUE THREAD

**Issue by certik** [sympy/sympy#3791]
bc.. > Perfect. Is there something you would add to our installation instructions?

> I need to get to some windows machine and try the experience for myself.
> Just one thing. Copy isympy.py in Scripts directory along with plain
> isympy as windows can not executes files without an extension.

p. Original issue for "#3791":https://github.com/sympy/sympy/issues/3791: "http://code.google.com/p/sympy/issues/detail?id=692":http://code.google.com/p/sympy/issues/detail?id=692

p. Original author: "https://code.google.com/u/104039945248245758823/":https://code.google.com/u/104039945248245758823/

p. Original owner: "https://code.google.com/u/104039945248245758823/":https://code.google.com/u/104039945248245758823/

**Comment by oscarbenjamin** [comment]
This is solved by setuptools entry points which are used when installing via pip or from setup.py. Setuptools takes care of ensuring that `isympy` will work in the terminal. I think on Windows it will create an isympy.exe stub but that can be considered an implementation detail from our (and our users') perspective.

I think this can be closed.
