### ISSUE TITLE
Add tests from "Review of CAS mathematical capabilities", by Michael Wester

### ISSUE THREAD

**Issue by certik** [sympy/sympy#3793]
bc.. Go through the 1994 paper "Review of CAS mathematical capabilities", by
Michael Wester, available for example here: http://www.math.unm.edu/~wester/cas/book/Wester.pdf And write tests for each of the example in there if sympy can do it, or a
new issue if it cannot. Together with fixing the issue 3787 , this should
produce a nice documentation of how to do the ususal things in sympy.

See also: http://www.sagemath.org/doc/html/ref/module-sage.calculus.wester.html

p. Original issue for "#3793":https://github.com/sympy/sympy/issues/3793: "http://code.google.com/p/sympy/issues/detail?id=694":http://code.google.com/p/sympy/issues/detail?id=694

p. Original author: "https://code.google.com/u/104039945248245758823/":https://code.google.com/u/104039945248245758823/

p. Referenced issues: "#3787":https://github.com/sympy/sympy/issues/3787

**Comment by oscarbenjamin** [comment]
I think these are now in sympy/utilities/tests/test_wester.py:
```console
$ pytest sympy/utilities/tests/test_wester.py -m 'not slow' -n4
============================================================= test session starts =============================================================
platform darwin -- Python 2.7.10, pytest-4.1.1, py-1.7.0, pluggy-0.8.0
architecture: 64-bit
cache:        yes
ground types: python 

rootdir: /Users/enojb/current/sympy/sympy, inifile: pytest.ini
plugins: xdist-1.26.0, instafail-0.4.1, forked-0.2, doctestplus-0.3.0.dev0
gw0 [389] / gw1 [389] / gw2 [389] / gw3 [389]
ss........................x..x.xxx...x..xx..x..x.x.xx.x....x.x..xx.x.x.......x...x..xx.xx.xxx.........x..x..x.x...x..x.xxx.xx..x....x.. [ 34%]
..x.....x.x.x...x.xx..x..x..x.xx.x....x.....x...xx............x.x.x.xxxxx..x.xx.....x....x..x..........xx.xxxxxxxxxx.xxxxxx..........x. [ 69%]
x.xxxxx..x.xxxxx..x...xxx....xxx..Xxx.x....xx.x..x.x...xx.x.xxx...x..xx.x...x...x...x.x.xx..xx..x..xxx.x..xx.x..xxx.xx.                 [100%]
======================================= 236 passed, 2 skipped, 150 xfailed, 1 xpassed in 140.75 seconds =======================================
```
I guess this can be closed...
