### ISSUE TITLE
Plot() should use standard kwarg syntax -- examples in docstrings don't work

### ISSUE THREAD

**Issue by fredrik-johansson** [sympy/sympy#3801]
bc.. Plot uses a weird syntax for specifying options:

    Plot(1, 'mode=spherical; color=zfade4')

It would be more consistent and familiar to use standard Python keyword
arguments:

    Plot(1, mode='spherical', color='zfade4')

Now, the weird thing is that the Plot class documentation contradicts the
real syntax. Plot.__doc__ actually gives docstring examples using standard
keyword syntax:

    >>> Plot(1*x, [], [x], mode='cylindrical')

    >>> Plot(1, mode='spherical')

But these don't work:

>>> from sympy import *
>>> var('x')
x
>>> Plot(1*x, [], [x], mode='cylindrical')
Window initialization failed: __init__() got an unexpected keyword argument
'mode'
Exception in thread Thread-3:
Traceback (most recent call last):
  File "C:\Python25\lib\threading.py", line 460, in __bootstrap
    self.run()
  File "C:\Python25\lib\threading.py", line 440, in run
    self.__target(*self.__args, **self.__kwargs)
  File "C:\source\sympyhg\sympy\sympy\plotting\managed_window.py", line 66,
in _
_event_loop__
    super(ManagedWindow, self).close()
  File
"C:\source\sympyhg\sympy\sympy\thirdparty\pyglet\pyglet\window\win32\__in
it__.py", line 529, in close
    super(Win32Window, self).close()
  File
"C:\source\sympyhg\sympy\sympy\thirdparty\pyglet\pyglet\window\__init__.p
y", line 789, in close
    self._display._windows.remove(self)
AttributeError: 'PlotWindow' object has no attribute '_display'

[0]: x, 'mode=cartesian'

p. Original issue for "#3801":https://github.com/sympy/sympy/issues/3801: "http://code.google.com/p/sympy/issues/detail?id=702":http://code.google.com/p/sympy/issues/detail?id=702

p. Original author: "https://code.google.com/u/111502149103757882156/":https://code.google.com/u/111502149103757882156/

**Comment by siddharthist** [comment]
[This looks fixed in master](https://github.com/sympy/sympy/blob/0a15782f20505673466b940454b33b8014a25c13/sympy/plotting/plot.py#L175-L179)
