### ISSUE TITLE
Allow manipulation of raw expression trees

### ISSUE THREAD

**Issue by certik** [sympy/sympy#3846]
bc.. when writing sin(w_t), sympy produces sin(t_w):

In [1]: var("t w")
Out[1]: (t, w)

In [2]: sin(w_t)
Out[2]: sin(t_w)

Sometimes, it is desirable to preserve the original ordering, like when
producing nice latex output. 

How can we achieve that?

See also: http://groups.google.com/group/sympy/browse_thread/thread/d84e697477d385e9

p. Original issue for "#3846":https://github.com/sympy/sympy/issues/3846: "http://code.google.com/p/sympy/issues/detail?id=747":http://code.google.com/p/sympy/issues/detail?id=747

p. Original author: "https://code.google.com/u/104039945248245758823/":https://code.google.com/u/104039945248245758823/

**Comment by oscarbenjamin** [comment]
This is still an issue bt I don't think we need to keep this old issue open for it.
