### ISSUE TITLE
pprint: problems with unicode symbols

### ISSUE THREAD

**Issue by navytux** [sympy/sympy#3868]
bc.. In [1]: a = Symbol('ПРИВЕТ')

In [2]: a
Out[2]: ПРИВЕТ

In [3]: sin(a)
Out[3]: sin(ПРИВЕТ)

In [4]: a/2
## Out[4]:

UnicodeDecodeError                        Traceback (most recent call last)

...

/home/kirr/src/sympy/sympy-official/sympy/printing/pretty/stringpict.py in
stack(*args)
    135         newPicture = [line.center(newWidth) for line in newPicture]
    136         newBaseline = objects[0].height()+objects[1].baseline
--> 137         return '\n'.join(newPicture), newBaseline
    138 
    139     def below(self, *args):

UnicodeDecodeError: 'ascii' codec can't decode byte 0xd0 in position 0:
ordinal not in ra
nge(128)

p. Original issue for "#3868":https://github.com/sympy/sympy/issues/3868: "http://code.google.com/p/sympy/issues/detail?id=769":http://code.google.com/p/sympy/issues/detail?id=769

p. Original author: "https://code.google.com/u/111152560333599832822/":https://code.google.com/u/111152560333599832822/

**Comment by eric-wieser** [comment]
This can be closed now that python 2 is dropped.
