### ISSUE TITLE
Should Lambda accept Functions as variables?

### ISSUE THREAD

**Issue by navytux** [sympy/sympy#3896]
bc.. In [1]: H = Lambda(f(x), diff(f(x), x,x) + x**2 *f(x))

In [2]: H
Out[2]: 
      ⎛       2     ⎞
Lambda⎝f(x), x *f(x)⎠

Where is the f'' term?

In [3]: H(x)
Out[3]: 
 3
x

p. Original issue for "#3896":https://github.com/sympy/sympy/issues/3896: "http://code.google.com/p/sympy/issues/detail?id=797":http://code.google.com/p/sympy/issues/detail?id=797

p. Original author: "https://code.google.com/u/111152560333599832822/":https://code.google.com/u/111152560333599832822/

**Comment by oscarbenjamin** [comment]
An error is now raised if the signature for a `Lambda` is not a symbol or a tuple:
```python
In [8]: H = Lambda(f(x), diff(f(x), x,x) + x**2 *f(x))
---------------------------------------------------------------------------
BadSignatureError: Lambda signature should be only tuples and symbols, not f(x)
```
