### ISSUE TITLE
an attempt at better printing of derivatives

### ISSUE THREAD

**Issue by sympy-issue-migrator** [sympy/sympy#3926]
bc.. This is my attempt at better printing for derivatives, in latex, mathml 
and pretty. Latex is mostly unchanged, although the code looks a little 
cleaner. Mathml uses the "degree" tag, and pretty looks prettier.

I would have condensed all the terms, but i am not sure that it is 
mathematically correct that the order of the variables one differentiates 
by does not matter. This wouldn't require much to implement.

The new functions in the LatexPrinter, PrettyPrinter and MathMLPrinter are 
_print_derivative2. Some tests need to written, so this is just a 
preliminary stage thing.

*I have no idea why this patch is so large, I only added a single function 
to 3 different files

old:
         6  
        d        / 5\
-----------------\x /
dy dz dz dx dz dx

new:
        6  
       d       / 5\
---------------\x /
     2  
dy dz  dx dz dx

old:  
<apply>
    <diff/>
    <bvar>
        <ci>
            x
        </ci>
        <ci>
            z
        </ci>
        <ci>
            x
        </ci>
        <ci>
            z
        </ci>
        <ci>
            z
        </ci>
        <ci>
            y
        </ci>
    </bvar>
    <apply>
        <power/>
        <ci>
            x
        </ci>
        <cn>
            5
        </cn>
    </apply>
</apply>

new:
<apply>
    <diff/>
    <bvar>
        <ci>
            x
        </ci>
        <ci>
            z
        </ci>
        <ci>
            x
        </ci>
        <ci>
            z
        </ci>
        <degree>
            <cn>
                2
            </cn>
        </degree>
        <ci>
            y
        </ci>
    </bvar>
    <apply>
        <power/>
        <ci>
            x
        </ci>
        <cn>
            5
        </cn>
    </apply>
</apply>

p. Original issue for "#3926":https://github.com/sympy/sympy/issues/3926: "http://code.google.com/p/sympy/issues/detail?id=827":http://code.google.com/p/sympy/issues/detail?id=827

p. Original author: "https://code.google.com/u/112859157854744488476/":https://code.google.com/u/112859157854744488476/

**Comment by oscargus** [comment]
Gigantic patch (probably caused by changing line endings): http://storage.googleapis.com/google-code-attachments/sympy/issue-827/comment-0/better_deriv_printing.patch

**Comment by certik** [comment]
@oscargus would you mind please sending the patch as a github pull request?

**Comment by oscargus** [comment]
I can give it a try.

**Comment by oscargus** [comment]
See #15975
