### ISSUE TITLE
new lambdify fails to raise an exception

### ISSUE THREAD

**Issue by vks** [sympy/sympy#3953]
bc.. I was reviving my efforts to compile functions to machine code and got this
(you will probably need the latest revision):

Traceback (most recent call last):
  File "/home/one/src/sympy/compilef.py", line 331, in <module>
    benchmark(f)
  File "/home/one/src/sympy/compilef.py", line 302, in benchmark
    pf = lambdify(var, f)
  File
"/usr/local/lib/python2.5/site-packages/sympy/utilities/lambdify.py", line
169, in lambdify
    buf = _get_namespace(m)
  File
"/usr/local/lib/python2.5/site-packages/sympy/utilities/lambdify.py", line
184, in _get_namespace
    _import(m)
  File
"/usr/local/lib/python2.5/site-packages/sympy/utilities/lambdify.py", line
86, in _import
    raise ImportError, "Can't import %s with command %s"%(modulename,
NameError: name 'modulename' is not defined

It seems to fail at raising an exception because uses a non-existent name.
I think that it tries to analyze the namespace and fails due to being used
from a function, but I'm not sure. I did not yet look into lambdify's
implementation and I still need to figure out what exactly causes the bug.

At least the NameError should be fixed.

p. Original issue for "#3953":https://github.com/sympy/sympy/issues/3953: "http://code.google.com/p/sympy/issues/detail?id=854":http://code.google.com/p/sympy/issues/detail?id=854

p. Original author: "https://code.google.com/u/Vinzent.Steinberg@gmail.com/":https://code.google.com/u/Vinzent.Steinberg@gmail.com/

**Comment by oscarbenjamin** [comment]
I guess this isn't an issue but I don't see how to test it from the information above...

**Comment by vks** [comment]
I think it is safe to close this issue.
