### ISSUE TITLE
lite.sympy.org: easy to overload?

### ISSUE THREAD

**Issue by navytux** [sympy/sympy#3954]
bc.. Try to enter this at lite.sympy.org:

> > > from sympy import *
> > > x=Symbol('x')
> > > integrate(sin(x)_exp(-x_*2), x)

The output will be:

<html><head>
<meta http-equiv="content-type" content="text/html;charset=utf-8">
<title>502 Server Error</title>

<style></style>

<script>
</script>

</head>
<body text=#000000 bgcolor=#ffffff>

<table border=0 cellpadding=2 cellspacing=0 width=100%><tr><td rowspan=3
width=1% nowrap>
<b><font face=times color=#0039b6 size=10>G</font><font face=times
color=#c41200 size=10>o</font><font face=times color=#f3c518
size=10>o</font><font face=times color=#0039b6 size=10>g</font><font
face=times color=#30a72f size=10>l</font><font face=times color=#c41200
size=10>e</font>&nbsp;&nbsp;</b>
<td>&nbsp;</td></tr>
<tr><td bgcolor=#3366cc><font face=arial,sans-serif
color=#ffffff><b>Error</b></td></tr>
<tr><td>&nbsp;</td></tr></table>

<blockquote>
<H1>Server Error</H1>
The server encountered a temporary error and could not complete your
request.<p>Please try again in 30 seconds.

<p>
</blockquote>

<table width=100% cellpadding=0 cellspacing=0><tr><td bgcolor=#3366cc><img
alt="" width=1 height=4></td></tr></table>

</body></htm

p. Original issue for "#3954":https://github.com/sympy/sympy/issues/3954: "http://code.google.com/p/sympy/issues/detail?id=855":http://code.google.com/p/sympy/issues/detail?id=855

p. Original author: "https://code.google.com/u/111152560333599832822/":https://code.google.com/u/111152560333599832822/

**Comment by oldk1331** [comment]
Maybe we should close this issue and open a new one:

### integrate(sin(x)*exp(-x**2), x) times out

The answer given by FriCAS is:
````
                     ┌───┐                    ┌───┐
           ┌───┐    \│- 1  + 2x     ┌───┐    \│- 1  - 2x   ┌───┐
         (\│- 1 erf(───────────) + \│- 1 erf(───────────))\│%pi
                         2                        2
         ───────────────────────────────────────────────────────
                                      1
                                      ─
                                      4
                                   4%e
````
Or in sympy's notation: `((sqrt(-1)*erf((sqrt(-1)+2*x)/2)+sqrt(-1)*erf((sqrt(-1)-2*x)/2))*sqrt(pi))/(4*exp(S(1)/4))`

The answer is correct, and maybe it can be simplified further.

**Comment by oscarbenjamin** [comment]
Is lite.sympy.org a prior version of SymPy Live?

The integral is computer quickly enough:
```
In [1]: %time integrate(sin(x)*exp(-x*2), x)
CPU times: user 790 ms, sys: 18.9 ms, total: 809 ms
Wall time: 804 ms
Out[1]: 
     -2⋅x           -2⋅x       
  2⋅ℯ    ⋅sin(x)   ℯ    ⋅cos(x)
- ────────────── - ────────────
        5               5    
```

**Comment by oscarbenjamin** [comment]
This works fine on SymPy Live:
```
>>> integrate(sin(x)*exp(-x*2), x)
     -2*x           -2*x       
  2*e    *sin(x)   e    *cos(x)
- -------------- - ------------
        5               5  
```
Maybe this can be closed.

**Comment by oldk1331** [comment]
Hi @oscarbenjamin , if you see the original comment on googlecode, it uses `integrate(sin(x)*exp(-x**2), x)` instead of `integrate(sin(x)*exp(-x*2), x)`.

Currently sympy can not solve former:

````
>>> integrate(sin(x)*exp(-x**2), x)
⌠               
⎮    2          
⎮  -x           
⎮ ℯ   ⋅sin(x) dx
⌡               
````

**Comment by oscarbenjamin** [comment]
I opened https://github.com/sympy/sympy/issues/21362
