### ISSUE TITLE
remove dependency on pexpect and add support for Mathtex

### ISSUE THREAD

**Issue by vks** [sympy/sympy#3971]
## bc.. In [39]: preview(x**x)

ImportError                               Traceback (most recent call last)

/home/one/<ipython console> in <module>()

/usr/local/lib/python2.5/site-packages/sympy-0.5.15-py2.5.egg/sympy/printing/preview.pyc
in preview(expr, output, viewer, euler)
     53     # we don't want to depend on anything not in the
     54     # standard library with SymPy by default
---> 55     import pexpect
     56
     57     special = [ 'pyglet' ]

ImportError: No module named pexpect

p. Original issue for "#3971":https://github.com/sympy/sympy/issues/3971: "http://code.google.com/p/sympy/issues/detail?id=872":http://code.google.com/p/sympy/issues/detail?id=872

p. Original author: "https://code.google.com/u/Vinzent.Steinberg@gmail.com/":https://code.google.com/u/Vinzent.Steinberg@gmail.com/

**Comment by oscarbenjamin** [comment]
This issue seems to have been fixed at the time. I think preview still doesn't work well (at least on OSX). We should probably just get rid of preview since we have `latex` and also Jupyter notebooks.
