### ISSUE TITLE
simplify for general functions and derivatives could be improved

### ISSUE THREAD

**Issue by vks** [sympy/sympy#3985]
bc.. >>> from sympy import *

> > > var('x')
> > > x
> > > f=Function('f')
> > > f(x)_f(x).diff(x,2)/f(x).diff(x)__2
> > > f(x)_D(f(x), x, x)_D(f(x), x)__(-2)
> > > z=f(x)_f(x).diff(x,2)/f(x).diff(x)**2
> > > z
> > > f(x)_D(f(x), x, x)_D(f(x), x)**(-2)
> > > z.diff(x)
> > > D(f(x), x)_D(f(x), x, x)_D(f(x), x)**(-2) + f(x)_D(f(x), x, x, x)_D(f(x),
> > > x)**(-
> > > 2) - 2_f(x)_D(f(x), x, x)_D(f(x), x)__(-2)_D(f(x), x, x)/D(f(x), x)
> > > simplify(_)
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "sympy\simplify\simplify.py", line 970, in simplify
> > >     expr = powsimp(radsimp(expr))
> > >   File "sympy\simplify\simplify.py", line 808, in radsimp
> > >     n = collect( (n_(a-b_sqrt(c))).expand(), syms )
> > >   File "sympy\simplify\simplify.py", line 599, in collect
> > >     terms = [ parse_term(i) for i in make_list(product, Mul) ]
> > >   File "sympy\simplify\simplify.py", line 522, in parse_term
> > >     sexpr, deriv = parse_derivative(expr)
> > >   File "sympy\simplify\simplify.py", line 485, in parse_derivative
> > >     expr, sym, order = deriv.f, deriv.x, 1
> > >   File "sympy\core\basic.py", line 219, in __getattr__
> > >     raise AttributeError(name)
> > > AttributeError: f

p. Original issue for "#3985":https://github.com/sympy/sympy/issues/3985: "http://code.google.com/p/sympy/issues/detail?id=886":http://code.google.com/p/sympy/issues/detail?id=886

p. Original author: "https://code.google.com/u/Vinzent.Steinberg@gmail.com/":https://code.google.com/u/Vinzent.Steinberg@gmail.com/

**Comment by oscarbenjamin** [comment]
Seems to work okay now:
```python
from sympy import *
x = Symbol('x')

integrate(cos(x)*sin(x)*sin(2*x))

D = diff

var('x')
x
f=Function('f')
f(x)*f(x).diff(x,2)/f(x).diff(x)**2
f(x)*D(f(x), x, x)*D(f(x), x)**(-2)
z=f(x)*f(x).diff(x,2)/f(x).diff(x)**2
f(x)*D(f(x), x, x)*D(f(x), x)**(-2)
t = D(f(x), x)*D(f(x), x, x)*D(f(x), x)**(-2) + f(x)*D(f(x), x, x, x)*D(f(x), x)**(- 2) - 2*f(x)*D(f(x), x, x)*D(f(x), x)**(-2)*D(f(x), x, x)/D(f(x), x)
```

```python
In [7]: t
Out[7]: 
                                   2            
       3                ⎛  2      ⎞      2      
      d                 ⎜ d       ⎟     d       
f(x)⋅───(f(x))   2⋅f(x)⋅⎜───(f(x))⎟    ───(f(x))
       3                ⎜  2      ⎟      2      
     dx                 ⎝dx       ⎠    dx       
────────────── - ─────────────────── + ─────────
           2                   3        d       
 ⎛d       ⎞          ⎛d       ⎞         ──(f(x))
 ⎜──(f(x))⎟          ⎜──(f(x))⎟         dx      
 ⎝dx      ⎠          ⎝dx      ⎠                 

In [8]: simplify(t)
Out[8]: 
                                            2                        
                3                ⎛  2      ⎞              2   2      
     d         d                 ⎜ d       ⎟    ⎛d       ⎞   d       
f(x)⋅──(f(x))⋅───(f(x)) - 2⋅f(x)⋅⎜───(f(x))⎟  + ⎜──(f(x))⎟ ⋅───(f(x))
     dx         3                ⎜  2      ⎟    ⎝dx      ⎠    2      
              dx                 ⎝dx       ⎠                dx       
─────────────────────────────────────────────────────────────────────
                                       3                             
                             ⎛d       ⎞                              
                             ⎜──(f(x))⎟                              
                             ⎝dx      ⎠ 
```
