### ISSUE TITLE
Lambdify with Matrix and python math

### ISSUE THREAD

**Issue by goriccardo** [sympy/sympy#4033]
bc.. Hello,
I think we should fix this:

In [1]: M = Matrix([[1,2,3],[x,y**2,z**3],[4,5,6]])

In [2]: lmat = lambdify((x,y,z),M,'math')
## In [3]: lmat(1,2,3)

NameError: global name 'Matrix' is not defined

lamat should return a list as this:

Out [3]: [[1,2,3],[1,4,27],[4,5,6]]

p. Original issue for "#4033":https://github.com/sympy/sympy/issues/4033: "http://code.google.com/p/sympy/issues/detail?id=934":http://code.google.com/p/sympy/issues/detail?id=934

p. Original author: "https://code.google.com/u/goriccardo@gmail.com/":https://code.google.com/u/goriccardo@gmail.com/

**Comment by oscarbenjamin** [comment]
Since this has "needs decision" I'll make the decision and close this issue. It isn't possible to lambdify a matrix with `math` as the module because the math module does not support matrices. Any arguments about performance are likely not relevant after this much time.
