### ISSUE TITLE
put all _sage_ methods to one place

### ISSUE THREAD

**Issue by certik** [sympy/sympy#4049]
bc.. A patch was committed that greatly expands what can be converted from sympy
to Sage: http://hg.sympy.org/sympy/rev/414880e1c8be Kirr review:

Looks ok, although I'd put it in one place (Basic._sage_) and build a
map of correspondence between SymPy classes and Sage classes.

Btw, this map could be handy for implementing _sympy_ method in Sage to
map back Sage objects to SymPy, so

This way we'll control both conversions mostly in one place.

Let's do it.

See this thread for the background: http://groups.google.com/group/sympy-patches/browse_thread/thread/d3bf166d967451ff/

p. Original issue for "#4049":https://github.com/sympy/sympy/issues/4049: "http://code.google.com/p/sympy/issues/detail?id=950":http://code.google.com/p/sympy/issues/detail?id=950

p. Original author: "https://code.google.com/u/104039945248245758823/":https://code.google.com/u/104039945248245758823/

**Comment by oscarbenjamin** [comment]
If there is still an issue here then it should be discussed in a new issue. It's not clear to me from the above whether any of this is still relevant. I'm going to close this.
