### ISSUE TITLE
preview() should work out of the box

### ISSUE THREAD

**Issue by vks** [sympy/sympy#4069]
bc.. By now, it uses ps by default. But this fails usually, because it does not
find a viewer. And after all, ps is uncommon Windows.

I suggest to use png + pyglet by default to work out of the box. Trying to
do it this way I get:

In [29]: e=x**y/z
## In [30]: preview(e, output='png')

SystemError                               Traceback (most recent call last)

/tmp/<ipython console> in <module>()

/usr/local/lib/python2.5/site-packages/sympy/printing/preview.py in
preview(expr, output, viewer, euler)
    136         try:
    137             if execute(command[output] % (tmp, tmp)) != 0:
--> 138                 raise SystemError("Failed to generate '%s' output."
% output)
    139             else:
    140                 os.remove(tmp + ".dvi")

SystemError: Failed to generate 'png' output.

The reason might be that dvi generation fails too. preview(e, output='dvi')
closes my viewers (kdvi, okular) immediately.

This all could be due to a broken LaTeX on my system, I'll need to verify.

Anyway, I think preview should not use an external viewer by default if
pyglet is available.

p. Original issue for "#4069":https://github.com/sympy/sympy/issues/4069: "http://code.google.com/p/sympy/issues/detail?id=970":http://code.google.com/p/sympy/issues/detail?id=970

p. Original author: "https://code.google.com/u/Vinzent.Steinberg@gmail.com/":https://code.google.com/u/Vinzent.Steinberg@gmail.com/

**Comment by oscarbenjamin** [comment]
Preview was changed to use pyglet. I think we should probably ditch that and use matplotlib though. In any case I don't think that this issue needs to be kept open.
