### ISSUE TITLE
expansion speedup:

### ISSUE THREAD

**Issue by certik** [sympy/sympy#4072]
bc.. diff --git a/sympy/core/power.py b/sympy/core/power.py
--- a/sympy/core/power.py
+++ b/sympy/core/power.py
@@ -341,12 +341,14 @@ class Pow(Basic, ArithMeths, RelMeths):

```
             # An elegant way would be to use Poly, but unfortunately it is
             # slower than the direct method below, so it is commented out:
```
-                #b = {}
-                #for k in expansion_dict:
-                #    b[k] = Integer(expansion_dict[k])
-                #return Poly(b, *p).as_basic()
-                b = {}
-                for k in expansion_dict:
-                    b[k] = Integer(expansion_dict[k])
-                from sympy import Poly
- ```
             return Poly(b, *p).as_basic()
  
           # use a direct method which is faster:
  ```
- ```
             #return expansion_dict
           l = []
           for powers, k in expansion_dict.iteritems():
               # assemble a term, e.g. 3*x**2*y
  ```
  
  diff --git a/sympy/polys/polynomial.py b/sympy/polys/polynomial.py
  --- a/sympy/polys/polynomial.py
  +++ b/sympy/polys/polynomial.py
  @@ -659,6 +659,18 @@ class Poly(Basic, RelMeths, ArithMeths):
          3 + x**2
  
  ```
   """
  ```
-        p = self.symbols
-        l = []
-        for k, powers in self.iter_terms():
-            # assemble a term, e.g. 3_x__2_y
-            term = [k]
-            for i,e in enumerate(powers):
-                term.append(Pow(p[i], powers[i]))
-            l.append(Mul(_term, *_{"evaluate": False}))
-        # sum up all terms
-        result = Add(_l, *_{"evaluate": False})
-        return result
  +
       return Add(*[ coeff.as_basic() \* monomial_as_basic(monom,
           *self.symbols) for coeff, monom in self.iter_terms() ])

Before:

py$ python t.py 
0.984194040298

now:

$ python t.py 
0.258791923523

p. Original issue for "#4072":https://github.com/sympy/sympy/issues/4072: "http://code.google.com/p/sympy/issues/detail?id=973":http://code.google.com/p/sympy/issues/detail?id=973

p. Original author: "https://code.google.com/u/104039945248245758823/":https://code.google.com/u/104039945248245758823/

**Comment by oscarbenjamin** [comment]
There are still some relevant ideas here but we don't need to keep this open.
