### ISSUE TITLE
extract (-1) from all expressions canonically

### ISSUE THREAD

**Issue by certik** [sympy/sympy#4077]
bc.. For all functions with reflection symmetry, I suggest sorting the terms
sans their
coefficients in an arbitrary but consistent order (we already have
functions for
this, right?), and extracting the sign of the first term. This is also what
Mathematica does:

In[1]:= Sin[x - y]
Out[1]= Sin[x-y]

In[2]:= Sin[y - x]
Out[2]= -Sin[x-y]

In[10]:= Sin[b+c+d+e+f-a]
Out[10]= -Sin[a-b-c-d-e-f]

p. Original issue for "#4077":https://github.com/sympy/sympy/issues/4077: "http://code.google.com/p/sympy/issues/detail?id=978":http://code.google.com/p/sympy/issues/detail?id=978

p. Original author: "https://code.google.com/u/104039945248245758823/":https://code.google.com/u/104039945248245758823/

**Comment by oscarbenjamin** [comment]
@smichr do we still need this issue?

**Comment by smichr** [comment]
> do we still need this issue?

not for trig functions, but for `cancel`..I can't believe we don't have this in place.

**Comment by smichr** [comment]
Canonicalization of expressions can be too intrusive on the desired expression that a user wants to input so this idea hasn't gained traction. The function is in place, however, for users to do so on their own (and trig functions do some sign wrangling automatically).

`signsimp` is now part of `cancel`.

I don't think there is more to do on this issue.
