### ISSUE TITLE
add examples about oscillatory quadrature into our docs

### ISSUE THREAD

**Issue by certik** [sympy/sympy#4084]
bc.. see the issue 4080 for examples of usage.

p. Original issue for "#4084":https://github.com/sympy/sympy/issues/4084: "http://code.google.com/p/sympy/issues/detail?id=985":http://code.google.com/p/sympy/issues/detail?id=985

p. Original author: "https://code.google.com/u/104039945248245758823/":https://code.google.com/u/104039945248245758823/

p. Referenced issues: "#4080":https://github.com/sympy/sympy/issues/4080

**Comment by aaryandewan** [comment]
I want to work on this issue. I have read about [oscillatory quadratures](https://docs.sympy.org/latest/modules/evalf.html#sums-and-integrals) but I have never worked on one. 

So can you please guide me, as in what exactly do you expect? Where do I need to add some examples? Can you please give me a sample example?
