### ISSUE TITLE
Numerical differentiation

### ISSUE THREAD

**Issue by fredrik-johansson** [sympy/sympy#4093]
bc.. The patch implements basic numerical differentiation of order 1 and 2 via
central finite differences.

Unfortunately, it only works via evalf(subs={}) since the Derivative class
provides no way to represent a derivative at a specific point.

An option for left- or right-sided derivatives should be implemented.

It should be improved to support differentiation of arbitrary order, by
generating order finite difference formulas of higher order. It should also
be possible to differentiate via the Cauchy integral formula.

p. Original issue for "#4093":https://github.com/sympy/sympy/issues/4093: "http://code.google.com/p/sympy/issues/detail?id=994":http://code.google.com/p/sympy/issues/detail?id=994

p. Original author: "https://code.google.com/u/111502149103757882156/":https://code.google.com/u/111502149103757882156/

p. Original owner: "https://code.google.com/u/111502149103757882156/":https://code.google.com/u/111502149103757882156/

**Comment by oscarbenjamin** [comment]
I'm not sure what happened with this although there is now a `doit_numerically` method. I don't think this old issue needs to be kept open though.
