### ISSUE TITLE
Symbol('') does not raise an Exception

### ISSUE THREAD

**Issue by sympy-issue-migrator** [sympy/sympy#4101]
bc.. I think this is a bug rather than intended.

The most simple approach to fix it imho is 

assert name != ""

right after checking if name is a str instance.

A patch comes soon.

p. Original issue for "#4101":https://github.com/sympy/sympy/issues/4101: "http://code.google.com/p/sympy/issues/detail?id=1002":http://code.google.com/p/sympy/issues/detail?id=1002

p. Original author: "https://code.google.com/u/115578486913798231657/":https://code.google.com/u/115578486913798231657/

**Comment by outkaj** [comment]
I can confirm that a=Symbol(' ') and a=Symbol(" ") still do not raise exceptions. Do you still want to raise a   ValueError for whitespace? If so, I can try to patch this.

**Comment by moorepants** [comment]
It seems like the consensus from above was that a=Symbol(' ') and a=Symbol(" ") should raise an error. So yes, please submit a PR.

**Comment by certik** [comment]
I agree with @moorepants.

**Comment by asmeurer** [comment]
Why not? We already allow other strange symbol names. And it can be useful sometimes if you want to trick the pretty printer.

**Comment by moorepants** [comment]
Because this is what you said earlier in the thread:

> Whitespace Symbols are another issue (including the empty string).   I don't have a problem with those not being allowed. On the other hand, they probably wouldn't cause any problems, other than strange printing.

I don't care either way. I just read the old thread and tried to judge what the conclusion was.

**Comment by toolforger** [comment]
I do not think ```' '``` or ```'3'``` should be allowed as symbols. Normal print and pretty print will give outputs that are indistinguishable from outputs with an entirely different semantics.
Tricking pretty printing is even worse. It gets the job done, but it's adding an arcane feature to the mental landscape that people need to understand if they read other people's SymPy code.

Then there are some social effects: Longer learning curve, elite groups forming around "we understood that feature and you did not", a new expectation that one needs to understand arcane stuff to be really competent with SymPy.
I do not think that these effects are huge, but each arcane feature adds to them, so I tend to dislike arcanity.

**Comment by asmeurer** [comment]
My opinion now is that any string should be allowed for Symbol (i.e., as it is now). There's no technical reason to disallow it, so we shouldn't. Our style guides should discourage arcane names, just as they discourage using different variable names from the Symbols they point to.

**Comment by moorepants** [comment]
After thinking about it I agree with Aaron. There is really no reason to ban certain characters. We should probably just close this issue.

**Comment by debugger22** [comment]
+1 for closing the issue.

**Comment by certik** [comment]
I agree. Is there anything else to be done, or can we close it?

**Comment by outkaj** [comment]
Makes sense - I won't submit a PR then. It looks like this issue can be closed.
