### ISSUE TITLE
use pylab for latex printing (optionally)

### ISSUE THREAD

**Issue by certik** [sympy/sympy#4103]
bc.. However, I think there is a better way to output the formulae: just
use pylab latex facility.
Using a simple script:

from pylab import *

def print_matplotlib(s):
       text(0,0,s)
       axis('off')
       show()
       return

It is possible to print any latex expression generated by sympy as:
print_matplotlib(latex(any_expression))

p. Original issue for "#4103":https://github.com/sympy/sympy/issues/4103: "http://code.google.com/p/sympy/issues/detail?id=1004":http://code.google.com/p/sympy/issues/detail?id=1004

p. Original author: "https://code.google.com/u/104039945248245758823/":https://code.google.com/u/104039945248245758823/

**Comment by oscarbenjamin** [comment]
This is not needed. SymPy has improved printing capabilities since this issue was opened.
