### ISSUE TITLE
limit((1+x/(n+sin(n)))**n,n,oo) doesn't work

### ISSUE THREAD

**Issue by sk-** [sympy/sympy#4114]
bc.. If we play with the form limit((1+x/n)**n,n,oo), there are lots of problems

In [1]: limit((1+x/n)**n,n,oo)
Out[1]: exp(x)    Correct

In [2]: limit((1+x/(2_n))__n,n,oo)
Out[2]: NotImplementedError: Don't know how to calculate the mrv of 'O(_x__3)'
The limit algorithm needs to calculate the series of
series: 2__(-1/_w)_(2 + x__w)_*(1/_w)
expansion variable (expanding around 0+): _w
But the series expansion failed. Check that this series is meaningful and make
it work, then run this again. If the series cannot be mathematically
calculated, the bug is in the limit algorithm.

In this case the limit is exp(x/2)

The funny thing is that if we compute
In [3]: limit((1+x/(n/(1/2))*_n,n,oo)
Out[3]: exp(0.5_x)

The same happens with
In [4]: limit((1+x/2/(n))**n,n,oo)
Out[4]: Error:should be exp(0.5_x)
In [5]: limit((1+x_0.5/(n))**n,n,oo)
Out[5]: exp(0.5*x)

In [6]: limit((1+x/(2_n+1))__n,n,oo)
Out[6]: nan   Wrong:should be exp(0.5_x)

In [7]: limit((1+x/(n/(1/2)+1))*_n,n,oo)
Out[7]: Error: should be exp(0.5_x)

Also
In [8]: limit((1+x/(n+sin(n)))**n,n,oo)
Out[8]: Error  :should be exp(x)

p. Original issue for "#4114":https://github.com/sympy/sympy/issues/4114: "http://code.google.com/p/sympy/issues/detail?id=1015":http://code.google.com/p/sympy/issues/detail?id=1015

p. Original author: "https://code.google.com/u/113978530372034429162/":https://code.google.com/u/113978530372034429162/

**Comment by sachin-4099** [comment]
Current status on master:
```
In [2]: limit((1+x/n)**n,n,oo)
Out[2]:
 x
e

In [3]: limit((1+x/(2*n))**n,n,oo)
Out[3]:
 x
 -
 2
e

In [4]: limit((1+x/(n/(1/2)))**n,n,oo)
Out[4]:
 0.5*x
e

In [5]: limit((1+x/2/(n))**n,n,oo)
Out[5]:
 x
 -
 2
e


In [6]: limit((1+x*0.5/(n))**n,n,oo)
Out[6]:
 0.5*x
e

In [7]: limit((1+x/(2*n+1))**n,n,oo)
Out[7]:
 x
 -
 2
e

In [8]: limit((1+x/(n/(1/2)+1))**n,n,oo)
Out[8]:
 0.5*x
e

In [9]: limit((1+x/(n+sin(n)))**n,n,oo)
Out[9]:
                     n
     /    x         \
 lim |---------- + 1|
n->oo\n + sin(n)    /
```

Only the last case needs improvement, where the intended result is `exp(x)`, but is currently returned unevaluated.
