### ISSUE TITLE
bounds can only be set for first series on a plot

### ISSUE THREAD

**Issue by lleeoo** [sympy/sympy#4142]
bc.. the first function below will have the correct bounds (-10,10), but the
others will take the default (-5,5) and there does not seem to be
documentation on how to change that. Example:

x = Symbol('x')
f = x*_2/10 + 10_cos(x)
df = f.diff(x)
p = Plot(f,[-10,10])
p[1] = df

expected: both f and df should be plot over the same domain. Furthermore,
there is no documented way to change the bounds of df.

also, the plot is off-scale, way zoomed in.

Platform: XP, Python official 2.5.

p. Original issue for "#4142":https://github.com/sympy/sympy/issues/4142: "http://code.google.com/p/sympy/issues/detail?id=1043":http://code.google.com/p/sympy/issues/detail?id=1043

p. Original author: "https://code.google.com/u/101392536990756193889/":https://code.google.com/u/101392536990756193889/

**Comment by oscarbenjamin** [comment]
The code shown no longer works. It isn't clear to me that this is an issue any more so closing.
