### ISSUE TITLE
make sympify intelligent about 1/2 and 0.5

### ISSUE THREAD

**Issue by certik** [sympy/sympy#4152]
bc.. > It is sometimes slow if the nsimplify() cannot make it, so it probably

> should not be default, but it should be optional.
> 
> I know many people (including myself) have burned themselves by
> writing 1/2_x_*2, so this might help.

If one is just interested in matching fractions, continued fractions
can be used. This is extremely fast. See http://en.wikipedia.org/wiki/Continued_fraction#Best_rational_approximations Still, I think this is too much magic to use by default in sympify().
And most users won't have imported division from **future** anyway, so
it won't help when 1/2 == 0.

Ondrej:

This should be optional. Then we'll improve.

p. Original issue for "#4152":https://github.com/sympy/sympy/issues/4152: "http://code.google.com/p/sympy/issues/detail?id=1053":http://code.google.com/p/sympy/issues/detail?id=1053

p. Original author: "https://code.google.com/u/104039945248245758823/":https://code.google.com/u/104039945248245758823/

**Comment by smichr** [comment]
The `rational` flag for `sympify` works for string input, so if one wants to convert all floats to ints in an expression, the expression should be passed as a string:
```python
>>> S((x+.5),rational=True)  # doesn't work because x + .5 is already sympified
x + 0.5
>>> S(str(x+.5),rational=True)
x + 1/2

>>> S([.5], rational=True)
[0.500000000000000]
>>> S(str([.5]), rational=True)
[1/2]
```
