### ISSUE TITLE
series expansion of floor, ceiling, abs...

### ISSUE THREAD

**Issue by sympy-issue-migrator** [sympy/sympy#4156]
bc.. The series expansion of floor and ceiling gives wrong
results depending on the variables used:

In [14]: x = Symbol('x',negative=True)

In [15]: (floor(x+1.5)).series(x,n=10)
Out[15]: 0

In [16]: x = Symbol('x',positive=True)

In [17]: (floor(x+1.5)).series(x,n=10)
Out[17]: 1

This is because following code in sympy/functions/elementary/integers.py
decides on base of is_positive assumption of its argument which
is not relevant in this case.

```
def _eval_nseries(self, x, x0, n):
    positive = self.args[0].is_positive
    r = self.subs(x, x0)
    if positive:
        return r
    else:
        return r-1
```

I thik it is there to make work things like this

> > > x = Symbol('x', positive=True)
> > > floor(x).series(x)
> > > 0
> > > x = Symbol('x', negative=True)
> > > floor(x).series(x)
> > > -1

but this is undocumented and not very good imho. Cleaner solution
would be to define that series is always from 0+, so we can do:

> > > floor(x).series(x)
> > > 0
> > > floor(-x).series(x)
> > > -1

or adding a dir keyword like in limits...?

p. Original issue for "#4156":https://github.com/sympy/sympy/issues/4156: "http://code.google.com/p/sympy/issues/detail?id=1057":http://code.google.com/p/sympy/issues/detail?id=1057

p. Original author: "https://code.google.com/u/108972745133116904410/":https://code.google.com/u/108972745133116904410/

**Comment by 0sidharth** [comment]
This could be closed, the series expansions have been rewritten in a better way since, and all the examples mentioned in this thread work as expected.

**Comment by oscarbenjamin** [comment]
Am I misunderstanding something basic here? Why does `series(floor(x))` give zero?
```python
In [72]: x = Symbol('x', positive=True)

In [73]: floor(x).series(x)
Out[73]: 0

In [74]: floor(4).series(x)
Out[74]: 4

In [76]: floor(x+1.5).series(x)
Out[76]: 1
```
Shouldn't `series(floor(x))` just be `floor(x)`?

**Comment by 0sidharth** [comment]
The series function definition `series(expr, x=None, x0=0, n=6, dir='+')` is by default around 0, and by default as `x->0+` (due to the dir parameter). The value of `floor(x)` as `x->0+` is exactly 0, unlike something like `sin(x)`, which is non-zero at any value apart from `x=0` (in a neighbourhood around 0). Similarly, for the other examples, the value of `floor` is actually constant (a horizontal line even as seen by the graph of it), so the series expansion reflects that by returning a constant.

**Comment by oscarbenjamin** [comment]
Okay I'm not sure why I got confused about that.

I can see that there also tests for this:
```python
$ git grep series | grep floor
sympy/functions/elementary/tests/test_integers.py:    assert floor(x).nseries(x, y, 100) == floor(y)
sympy/functions/elementary/tests/test_integers.py:    assert floor(x).nseries(x, pi, 100) == 3
sympy/functions/elementary/tests/test_integers.py:    assert floor(x).nseries(x, 0, 100) == 0
sympy/functions/elementary/tests/test_integers.py:    assert floor(-x).nseries(x, 0, 100) == -1
sympy/series/tests/test_nseries.py:    assert floor(x).series(x) == 0
sympy/series/tests/test_nseries.py:    assert floor(-x).series(x) == -1
sympy/series/tests/test_nseries.py:    assert floor(sin(x)).series(x) == 0
sympy/series/tests/test_nseries.py:    assert floor(sin(-x)).series(x) == -1
sympy/series/tests/test_nseries.py:    assert floor(x**3).series(x) == 0
sympy/series/tests/test_nseries.py:    assert floor(-x**3).series(x) == -1
sympy/series/tests/test_nseries.py:    assert floor(cos(x)).series(x) == 0
sympy/series/tests/test_nseries.py:    assert floor(cos(-x)).series(x) == 0
sympy/series/tests/test_nseries.py:    assert floor(5 + sin(x)).series(x) == 5
sympy/series/tests/test_nseries.py:    assert floor(5 + sin(-x)).series(x) == 4
sympy/series/tests/test_nseries.py:    assert floor(x).series(x, 2) == 2
sympy/series/tests/test_nseries.py:    assert floor(-x).series(x, 2) == -3
sympy/series/tests/test_nseries.py:    assert floor(x + 1.5).series(x) == 1
sympy/series/tests/test_nseries.py:    assert floor(x + 2).series(x, 0, dir='+') == 2
sympy/series/tests/test_nseries.py:    assert floor(x + 2).series(x, 0, dir='-') == 1
sympy/series/tests/test_nseries.py:    assert floor(x + 2.2).series(x, 0, dir='-') == 2
sympy/stats/drv.py:                   series, factorial, And, floor)
```
I guess this can be closed now then.
