### ISSUE TITLE
Classifying formulas

### ISSUE THREAD

**Issue by fredrik-johansson** [sympy/sympy#4157]
bc.. I've written some code for determining the "class" of a formula. The
function classify(expr, x) walks the expression top-down and at each level
classifies it as a function of x. It distinguishes between various classes
of functions, including:
- linear expressions
- polynomials (degree > 1)
- rational functions
- algebraic roots
- exponentials
- logarithms
- trigonometric functions
- etc

It then recursively classifies all subexpressions and returns the path with
the "greatest" complexity. The following test outputs should hopefully make
it more clear:

pi []
1 + 3_x [LINEAR]
3_x + x**2 [POLYNOMIAL](1 + pi)_(5 + 4_x) [LINEAR](1 + pi)_(5 + E_(pi + 8_x)) [LINEAR](1 + 2*x)_(5 + 4_x) [POLYNOMIAL]
1/x [RATIONAL]
1/(1 + 2_x) [RATIONAL]
1/(2*x + x**2) [RATIONAL](1 + x)/(1 - x) [RATIONAL](4 + x)/(2_x + x__2) [RATIONAL](4 + x)/(2_x + x**2) + x**2 [RATIONAL]
x**2_(4 + x)/(2_x + x**2) [RATIONAL](1 + 3*x)**(1/2) [ROOT, LINEAR]
x**(3/2) [ROOT, LINEAR]
x**pi [EXP, LINEAR, LOG]
2_x + exp(1 + 2_x) + exp(4 + 3_x) [LINEAR, EXP, LINEAR]
2_x + (exp(3_x) + exp(1 + x))/(1 + 5_x) [RATIONAL, EXP, LINEAR]
2_x + sin(1 + 2_x)**2 + cos(4 + x)**4 [POLYNOMIAL, TRIGONOMETRIC, LINEAR]
2_x + (sin(1 + 2_x)**2 + cos(4 + x)**4)/(1 + 5*x) [RATIONAL, TRIGONOMETRIC,
LINEAR]
2**x [EXP, LINEAR]
x**x [EXP, LOG, LINEAR](1 + 2*x)**x [EXP, LOG, LINEAR](1 + acosh%28x%29)**x [EXP, LOG, LINEAR, INVHYPERBOLIC, LINEAR]
exp(exp(x)) [EXP, EXP, LINEAR]
exp(exp(1/x)) [EXP, EXP, RATIONAL]
exp(exp(x)) + exp(exp(1/x)) [LINEAR, EXP, EXP, RATIONAL]
exp(gamma(x)**2) [EXP, POLYNOMIAL, NONELEMENTARY, LINEAR]

(The trailing LINEAR for f(a_x+b) could perhaps be dropped when a_x+b is
actually precisely x.)

The classification gives an ordering roughly similar to (though more coarse
than) that used in integral tables like Gradshteyn and Ryzhik. I think this
could be used by various symbolic algorithms to decide which heuristic
algorithms to try. For example, integrate could choose heuristics among
these (and other) cases:

[POLYNOMIAL] -- use a polynomial integrator
[RATIONAL] -- use a rational integrator
[LINEAR ROOT, LINEAR] -- try looking up a direct formula in a table
[LINEAR, NONELEMENTARY, LINEAR] -- try looking up a formula in a table
[POLYNOMIAL, TRIGONOMETRIC, LINEAR] -- try the integrator for trigonometric
polynomials

There is a clear advantage to the fact that only a single pass through the
expression is required, instead of requiring every heuristic to "smell" the
expression. So it becomes cheaper to have lots of special-purpose heuristics.

The output can also be used to determine whether a function is elementary,
transcendental, etc.

What do you think? Where should the code go, does it need improvements,
should the SYMBOLS perhaps be something else (e.g. strings)? Maybe return
an object with **eq**, **le** methods etc so that computed classifications
can be compared more easily in terms of the complexity() measure?

p. Original issue for "#4157":https://github.com/sympy/sympy/issues/4157: "http://code.google.com/p/sympy/issues/detail?id=1058":http://code.google.com/p/sympy/issues/detail?id=1058

p. Original author: "https://code.google.com/u/111502149103757882156/":https://code.google.com/u/111502149103757882156/

**Comment by Shekharrajak** [comment]
Is this fixed ?

**Comment by oscarbenjamin** [comment]
This looks like a nice idea and is probably still needed but I expect too much time has passed to apply this code.
