### ISSUE TITLE
Implement arbitrary discrete probability distributions

### ISSUE THREAD

**Issue by sympy-issue-migrator** [sympy/sympy#4166]
bc.. Discrete distributions should be supported as well.

p. Original issue for "#4166":https://github.com/sympy/sympy/issues/4166: "http://code.google.com/p/sympy/issues/detail?id=1067":http://code.google.com/p/sympy/issues/detail?id=1067

p. Original author: "https://code.google.com/u/108972745133116904410/":https://code.google.com/u/108972745133116904410/

**Comment by Smit-create** [comment]
@asmeurer  Currently stats module support Discrete Distributions. There different discrete distributions supported and can be found in` sympy/stats/drv_types.py`.

**Comment by Smit-create** [comment]
We have the following discrete distribution in `stats`
https://github.com/sympy/sympy/blob/969cf54cf19e830306a84c00864b03f7b66bf8e0/sympy/stats/drv_types.py#L31-L40

Also, we can create custom discrete distributions,
https://github.com/sympy/sympy/blob/969cf54cf19e830306a84c00864b03f7b66bf8e0/sympy/stats/__init__.py#L63-L82

Can this be closed @asmeurer @czgdp1807 @Upabjojr?
