### ISSUE TITLE
implement StieltjesGamma

### ISSUE THREAD

**Issue by certik** [sympy/sympy#4186]
bc.. http://reference.wolfram.com/mathematica/ref/StieltjesGamma.html

p. Original issue for "#4186":https://github.com/sympy/sympy/issues/4186: "http://code.google.com/p/sympy/issues/detail?id=1087":http://code.google.com/p/sympy/issues/detail?id=1087

p. Original author: "https://code.google.com/u/104039945248245758823/":https://code.google.com/u/104039945248245758823/

**Comment by leosartaj** [comment]
I want to work on this issue. Please suggest regarding its implementation.

**Comment by asmeurer** [comment]
See https://github.com/sympy/sympy/wiki/About-implementing-special-functions
