### ISSUE TITLE
integrate(log(x)*exp(x), (x, 0, oo)) should return -EulerGamma

### ISSUE THREAD

**Issue by certik** [sympy/sympy#4187]
bc.. In [5]: integrate(log(x)*exp(x), (x, 0, oo))
    Out[5]:
    ∞
    ⌠
    ⎮  x
    ⎮ ℯ ⋅log(x) dx
    ⌡
    0

p. Original issue for "#4187":https://github.com/sympy/sympy/issues/4187: "http://code.google.com/p/sympy/issues/detail?id=1088":http://code.google.com/p/sympy/issues/detail?id=1088

p. Original author: "https://code.google.com/u/104039945248245758823/":https://code.google.com/u/104039945248245758823/

**Comment by oldk1331** [comment]
In sympy 1.0:
````
In [12]: integrate(log(x)*exp(-x), (x, 0, oo))
Out[12]: -EulerGamma
````

This issue can be closed.

**Comment by asmeurer** [comment]
Found a related bug. The indefinite integral `integrate(log(x)*exp(-x), x)` gives a recursion error from manualintegrate.

**Comment by oscarbenjamin** [comment]
All seems fixed now:
```
In [49]: integrate(log(x)*exp(-x), (x, 0, oo))
Out[49]: -γ

In [50]: integrate(log(x)*exp(-x), x)
Out[50]: 
          -x       
Ei(-x) - ℯ  ⋅log(x)
```
This can be closed with a test for each of the above if there isn't one already.
