### ISSUE TITLE
implement ListPlot[Table[DivisorSigma[1, n]/(n Log[Log[n]]), {n, 1000}]]

### ISSUE THREAD

**Issue by certik** [sympy/sympy#4192]
bc.. See here how it should look like: http://reference.wolfram.com/mathematica/ref/EulerGamma.html

p. Original issue for "#4192":https://github.com/sympy/sympy/issues/4192: "http://code.google.com/p/sympy/issues/detail?id=1093":http://code.google.com/p/sympy/issues/detail?id=1093

p. Original author: "https://code.google.com/u/104039945248245758823/":https://code.google.com/u/104039945248245758823/

**Comment by oscarbenjamin** [comment]
I can't tell what this issue is referring to...
