### ISSUE TITLE
collect sometimes doesn't collect inside brackets

### ISSUE THREAD

**Issue by goriccardo** [sympy/sympy#4198]
bc.. In [1]: f = x_(y_z+y)

In [2]: f1 = f+1

In [3]: f
Out[3]: x⋅(y + y⋅z)

In [4]: f1
Out[4]: 1 + x⋅(y + y⋅z)

In [5]: collect(f,y)
Out[5]: x⋅y⋅(1 + z)

In [6]: collect(f1,y)
Out[6]: 1 + x⋅(y + y⋅z)

I think collect(f1,y) should return 1 + x⋅y⋅(1 + z)

p. Original issue for "#4198":https://github.com/sympy/sympy/issues/4198: "http://code.google.com/p/sympy/issues/detail?id=1099":http://code.google.com/p/sympy/issues/detail?id=1099

p. Original author: "https://code.google.com/u/goriccardo@gmail.com/":https://code.google.com/u/goriccardo@gmail.com/

**Comment by oscarbenjamin** [comment]
It seems that this works now:
```julia
In [41]: f = x*(y*z + y)

In [42]: f
Out[42]: x⋅(y⋅z + y)

In [43]: f1 = f + 1

In [44]: f1
Out[44]: x⋅(y⋅z + y) + 1

In [45]: collect(f, y)
Out[45]: x⋅y⋅(z + 1)

In [46]: collect(f1, y)
Out[46]: x⋅y⋅(z + 1) + 1
```
