### ISSUE TITLE
add infix notation to sympy

### ISSUE THREAD

**Issue by certik** [sympy/sympy#4209]
bc.. The code is here: http://groups.google.com/group/sympy/browse_thread/thread/49f680fdcf79228d someone just needs to polish it, write tests and prepare a patch for inclusion.

p. Original issue for "#4209":https://github.com/sympy/sympy/issues/4209: "http://code.google.com/p/sympy/issues/detail?id=1110":http://code.google.com/p/sympy/issues/detail?id=1110

p. Original author: "https://code.google.com/u/104039945248245758823/":https://code.google.com/u/104039945248245758823/

**Comment by oscarbenjamin** [comment]
I'm not sure what this is but I don't think it's needed.
