### ISSUE TITLE
integrate outputs wrong result when the function is singular

### ISSUE THREAD

**Issue by sympy-issue-migrator** [sympy/sympy#4215]
bc.. For example: 

In [1]: integrate(1/(x**2), (x, 0, 1))
Out[1]: ∞

In [2]: integrate(1/(x**2), (x, -1, 1))
Out[2]: -2

but last line should also be Infinity because of the symmetry of the function.

p. Original issue for "#4215":https://github.com/sympy/sympy/issues/4215: "http://code.google.com/p/sympy/issues/detail?id=1116":http://code.google.com/p/sympy/issues/detail?id=1116

p. Original author: "https://code.google.com/u/103948515893177094863/":https://code.google.com/u/103948515893177094863/

**Comment by asmeurer** [comment]
SymPy now has a `singularities` function (it currently only works on rational functions, but with improvements to solveset, it should be able to get smarter). It would be nice to integrate this into `integrate`. Basically, split the integral interval into smaller intervals based on singularities of the integrand, and `_eval_interval` each one. Things get hairy if you start having symbolic parameters (like `integrate(1/x**2, (x, a, b))`, but I think we can find a good solution. 

CC @hargup @aktech @Shekharrajak @kshitij10496

**Comment by jksuom** [comment]
It may be necessary to look at the singularities of the antiderivative as well. Consider, for example, `integrate(1/(cos(x) + 2), x)`.

**Comment by Shekharrajak** [comment]
If we look proper definition of Singular function : 

A real-valued function f on the interval  `[a, b]` is said to be singular if it has the following properties:

* `f` is continuous on `[a, b]`.
* there exists a set `N` of measure `0` such that for all `x` outside of `N` the derivative `f ′(x)` exists and is zero, that is, the derivative of `f` vanishes almost everywhere.
* `f` is nondecreasing on `[a, b]`.
* `f(a) < f(b)` .

So for non rational we can check at least last 2 conditions, and  split the integral into continuous intervals. This should work isn't it ?  
Related to this https://github.com/sympy/sympy/pull/2723

**Comment by sn6uv** [comment]
@Shekharrajak, I think that definition is not quite what we want here. We are interested in functions that have a singularity  (or blowup) in the sense of https://en.wikipedia.org/wiki/Singularity_%28mathematics%29?wprov=sfla1

**Comment by Shekharrajak** [comment]
@sn6uv , actually I was talking about non rational functions. Here in this case we can get the point where it is not continuous using 
```
from sympy.calculus.singularities import singularities
x = Symbol('x', real=True)
In [ ]: singularities(1/x**2, x)
Out[]: {0}
 
```
Then we can split the integral from `-1 ` to `0` and `0` to `-1`  then we can get finite number or infinity as solution.

**Comment by sn6uv** [comment]
But $x \mapsto 1/x^2$ is not nondecreasing on [a,b] for a<0<b nor is its derivative zero anywhere. The definition for singular you gave is for another class of function e.g.  the devil's staircase.

**Comment by Shekharrajak** [comment]
Okay understood, deleting that definition. Thanks @sn6uv

**Comment by smichr** [comment]
Is this a duplicate of #12133 ? The OP test works in master after commit 8b81380  (#12142 from ArifAhmed1995/issue#12133).

**Comment by jksuom** [comment]
I think this particular issue concerned with singularities of the integrand could be closed. There are other, unsolved issues with definite integrals where the indefinite integral is multivalued and may have removable singularities, but that is a different topic.

**Comment by sachin-4099** [comment]
On current master:
```
In [2]: integrate(1/(x**2), (x, -1, 1))
Out[2]: oo
```
Closing in favour #12142.
