### ISSUE TITLE
Setup buildbot (again)

### ISSUE THREAD

**Issue by certik** [sympy/sympy#4216]
bc.. The ultimate solution is to provide test access to all developers on our
buildbots (the buildbots allow to test only a patch that you send to them)
& setup parallel testing & provide several levels of testing (core, basic,
thorough). 

Any volunteers to setup buildbots? I'll provide you with necessary access.

I can do that after I finish my finals. http://buildbot.sympy.org/waterfall

p. Original issue for "#4216":https://github.com/sympy/sympy/issues/4216: "http://code.google.com/p/sympy/issues/detail?id=1117":http://code.google.com/p/sympy/issues/detail?id=1117

p. Original author: "https://code.google.com/u/104039945248245758823/":https://code.google.com/u/104039945248245758823/

**Comment by oscarbenjamin** [comment]
We now use Github Actions. This thread has been outdated for some time
