### ISSUE TITLE
Memory leak in trig functions

### ISSUE THREAD

**Issue by aplund** [sympy/sympy#4217]
bc.. I came across this trying to figure out why my script was using so much
memory.  I narrowed it down to the trig functions.  The script below
demonstrates this.

If you comment out the num += 0.001 then the leak goes away.  Also, it
doesn't seem to matter if you use cos or sin or tan or whatever. 

I have tried to narrow down where the leak is occurring, but am unable.

Script follows and sample output after that.
## 

import gc
import sympy

print len(gc.get_objects())

num = 0.1
for x in range(20):
    gc.collect()
    print "A", len(gc.get_objects())

```
sympy.cos(num)

gc.collect()
print "B", len(gc.get_objects())
num += 0.001
```

gc.collect()
print len(gc.get_objects())
## 

l$ python tests.py 
20698
A 20700
B 20708
A 20708
B 20716
A 20716
B 20724
A 20724
B 20732
A 20732
B 20740
A 20740
B 20748
A 20748
B 20756
A 20756
B 20764
...

p. Original issue for "#4217":https://github.com/sympy/sympy/issues/4217: "http://code.google.com/p/sympy/issues/detail?id=1118":http://code.google.com/p/sympy/issues/detail?id=1118

p. Original author: "https://code.google.com/u/111408767815219685794/":https://code.google.com/u/111408767815219685794/

**Comment by isuruf** [comment]
Close as invalid?

**Comment by asmeurer** [comment]
Cache is LRU now and should no longer grow boundlessly.
