### ISSUE TITLE
add a test for complex integral from wikipedia

### ISSUE THREAD

**Issue by certik** [sympy/sympy#4231]
bc.. In [4]: d = (1+2_x+sqrt(x+log(x))_(1+3_x) +
x__2)/(x_(x+sqrt(x+log(x)))*sqrt(x+log(x)))

In [5]: d
Out[5]:
            ⎽⎽⎽⎽⎽⎽⎽⎽⎽⎽⎽⎽              2
1 + 2⋅x + ╲╱ x + log(x) ⋅(1 + 3⋅x) + x
───────────────────────────────────────
   ⎛      ⎽⎽⎽⎽⎽⎽⎽⎽⎽⎽⎽⎽⎞   ⎽⎽⎽⎽⎽⎽⎽⎽⎽⎽⎽⎽
 x⋅⎝x + ╲╱ x + log(x) ⎠⋅╲╱ x + log(x)

In [6]: integrate(d, x)
Out[6]:
     ⎛      ⎽⎽⎽⎽⎽⎽⎽⎽⎽⎽⎽⎽⎞       ⎽⎽⎽⎽⎽⎽⎽⎽⎽⎽⎽⎽
2⋅log⎝x + ╲╱ x + log(x) ⎠ + 2⋅╲╱ x + log(x)

more info here: http://groups.google.com/group/sympy/browse_thread/thread/9a61d681e6f967e8

p. Original issue for "#4231":https://github.com/sympy/sympy/issues/4231: "http://code.google.com/p/sympy/issues/detail?id=1132":http://code.google.com/p/sympy/issues/detail?id=1132

p. Original author: "https://code.google.com/u/104039945248245758823/":https://code.google.com/u/104039945248245758823/

**Comment by oldk1331** [comment]
This integral computes much faster now (year 2016 and sympy 1.0):
````
In [14]: time(integrate(d,x))
CPU times: user 12.4 s, sys: 84.5 ms, total: 12.5 s
Wall time: 12.5 s
Out[14]: 
    ____________        ⎛      ____________⎞
2⋅╲╱ x + log(x)  + 2⋅log⎝x + ╲╱ x + log(x) ⎠
````

That's on my slow laptop, should only take few second on a good computer.

However, I don't think this should get into test suite, because this integrand is a mixed algebraic transcendental function, sympy can compute it not by Risch algorithm, but by heuristic algorithm (Bornstein's poor man integrator) , aka "luck". A simple transform makes sympy can't solve it:
````
In [15]: time(integrate(expand(d),x))
CPU times: user 24 s, sys: 82.5 ms, total: 24 s
Wall time: 24.1 s
Out[15]: 
⌠                                                      
⎮  2         ____________           ____________       
⎮ x  + 3⋅x⋅╲╱ x + log(x)  + 2⋅x + ╲╱ x + log(x)  + 1   
⎮ ────────────────────────────────────────────────── dx
⎮           ⎛    ____________             ⎞            
⎮         x⋅⎝x⋅╲╱ x + log(x)  + x + log(x)⎠            
⌡
````

So, I think this issue should be closed.

**Comment by asmeurer** [comment]
Well lots of the algorithms in SymPy (and computer algebra in general) are heuristic in nature, so if they compute anything, it's by "luck". 

I'm actually curious what change made this so much faster.

**Comment by asmeurer** [comment]
It seems to always run relatively fast for me (the slowest I found was SymPy 0.7.0, where it takes 15 seconds). So maybe my computer was just really slow back then.

**Comment by oscarbenjamin** [comment]
It now computes in 3 seconds for me:
```julia
In [38]: d = (1+2*x+sqrt(x+log(x))*(1+3*x) + x**2)/(x*(x+sqrt(x+log(x)))*sqrt(x+log(x)))

In [39]: d
Out[39]: 
 2           ____________              
x  + 2⋅x + ╲╱ x + log(x) ⋅(3⋅x + 1) + 1
───────────────────────────────────────
   ⎛      ____________⎞   ____________ 
 x⋅⎝x + ╲╱ x + log(x) ⎠⋅╲╱ x + log(x)  

In [40]: %time integrate(d, x)
CPU times: user 2.8 s, sys: 20.7 ms, total: 2.82 s
Wall time: 2.83 s
Out[40]: 
    ____________        ⎛      ____________⎞
2⋅╲╱ x + log(x)  + 2⋅log⎝x + ╲╱ x + log(x) ⎠
```
We should add this test and close this issue.
