### ISSUE TITLE
make sympy run on top of CLPython

### ISSUE THREAD

**Issue by certik** [sympy/sympy#4235]
bc.. Let's discuss here all things that need to be fixed in order for sympy to
run on top of clpython.

So far there is the issue 4233 , but there are probably more.

p. Original issue for "#4235":https://github.com/sympy/sympy/issues/4235: "http://code.google.com/p/sympy/issues/detail?id=1136":http://code.google.com/p/sympy/issues/detail?id=1136

p. Original author: "https://code.google.com/u/104039945248245758823/":https://code.google.com/u/104039945248245758823/

p. Referenced issues: "#4233":https://github.com/sympy/sympy/issues/4233

**Comment by oscarbenjamin** [comment]
I guess this isn't relevant any more. If there is a new plan to do this then we can open a new issue
