### ISSUE TITLE
integrate(d) should raise TypeError

### ISSUE THREAD

**Issue by vks** [sympy/sympy#4236]
bc.. integrate(d) <=> integrate(d, x) but diff(d) raises TypeError

p. Original issue for "#4236":https://github.com/sympy/sympy/issues/4236: "http://code.google.com/p/sympy/issues/detail?id=1137":http://code.google.com/p/sympy/issues/detail?id=1137

p. Original author: "https://code.google.com/u/Vinzent.Steinberg@gmail.com/":https://code.google.com/u/Vinzent.Steinberg@gmail.com/

**Comment by oscarbenjamin** [comment]
Now both detect the symbol:
```julia
In [26]: integrate(d)
Out[26]: 
 2
d 
──
2 

In [27]: diff(d)
Out[27]: 1
```

**Comment by oscarbenjamin** [comment]
I think this can be closed
