### ISSUE TITLE
New options pricing example

### ISSUE THREAD

**Issue by ellisonbg** [sympy/sympy#4274]
bc.. This is a simple example that uses sympy to derive some basic formulas used
in binomial tree options pricing algorithms.

p. Original issue for "#4274":https://github.com/sympy/sympy/issues/4274: "http://code.google.com/p/sympy/issues/detail?id=1175":http://code.google.com/p/sympy/issues/detail?id=1175

p. Original author: "https://code.google.com/u/110706953761515533762/":https://code.google.com/u/110706953761515533762/

**Comment by smichr** [comment]
The link [referenced](http://storage.googleapis.com/google-code-attachments/sympy/issue-1175/comment-0/option_replication.py) does not exist. This can probably be closed.
