### ISSUE TITLE
Nicer LaTeX error messages

### ISSUE THREAD

**Issue by sympy-issue-migrator** [sympy/sympy#4306]
bc.. When a LaTeX environment is not setup appropriately, sympy will error out
with an unhelpful "Failed to generate DVI output." It would be nice if
sympy also told the user where the LaTeX log file's location, so they could
inspect and figure out what went wrong (in my case, not having the eulervm
fonts installed).

p. Original issue for "#4306":https://github.com/sympy/sympy/issues/4306: "http://code.google.com/p/sympy/issues/detail?id=1207":http://code.google.com/p/sympy/issues/detail?id=1207

p. Original author: "https://code.google.com/u/103248578920164941169/":https://code.google.com/u/103248578920164941169/

**Comment by eagleoflqj** [comment]
It's very old and this error message is not found in current code base. Closing.
