### ISSUE TITLE
integrate cannot integrate more complex Piecewise functions

### ISSUE THREAD

**Issue by certik** [sympy/sympy#4313]
bc.. In [1]: var("h")
Out[1]: h

In [2]: u = Piecewise( (0, x<=0), (1, x>=h), (x/h, True))

In [3]: e = (u-u.subs(x, y))**2/(x-y)**2

In [4]: e
Out[4]: 
                                 2
⎛- ⎧0  for y ≤ 0 + ⎧0  for x ≤ 0⎞ 
⎜  ⎪               ⎪            ⎟ 
⎜  ⎪1  for h ≤ y   ⎪1  for h ≤ x⎟ 
⎜  ⎨               ⎨            ⎟ 
⎜  ⎪y              ⎪x           ⎟ 
⎜  ⎪─  otherwise   ⎪─  otherwise⎟ 
⎝  ⎩h              ⎩h           ⎠ 
──────────────────────────────────
                    2  
             (x - y)              

In [5]: integrate(e,  x)
Out[5]: 
⌠  
⎮                                  2  
⎮ ⎛- ⎧0  for y ≤ 0 + ⎧0  for x ≤ 0⎞  
⎮ ⎜  ⎪               ⎪            ⎟  
⎮ ⎜  ⎪1  for h ≤ y   ⎪1  for h ≤ x⎟  
⎮ ⎜  ⎨               ⎨            ⎟  
⎮ ⎜  ⎪y              ⎪x           ⎟  
⎮ ⎜  ⎪─  otherwise   ⎪─  otherwise⎟  
⎮ ⎝  ⎩h              ⎩h           ⎠  
⎮ ────────────────────────────────── dx
⎮                     2  
⎮              (x - y)  
⌡                                      

In [6]: integrate(e.expand(),  x)
Out[6]: 
⌠  
⎮ ⎛                                               2                2⎞  
⎮ ⎜  2⋅⎧0  for x ≤ 0⋅⎧0  for y ≤ 0   ⎧0  for x ≤ 0    ⎧0  for y ≤ 0 ⎟  
⎮ ⎜    ⎪             ⎪               ⎪                ⎪             ⎟  
⎮ ⎜    ⎪1  for h ≤ x ⎪1  for h ≤ y   ⎪1  for h ≤ x    ⎪1  for h ≤ y ⎟  
⎮ ⎜    ⎨             ⎨               ⎨                ⎨             ⎟  
⎮ ⎜    ⎪x            ⎪y              ⎪x               ⎪y            ⎟  
⎮ ⎜    ⎪─  otherwise ⎪─  otherwise   ⎪─  otherwise    ⎪─  otherwise ⎟  
⎮ ⎜    ⎩h            ⎩h              ⎩h               ⎩h            ⎟  
⎮ ⎜- ───────────────────────────── + ────────────── + ──────────────⎟ dx
⎮ ⎜                    2                       2                2   ⎟  
⎮ ⎝             (x - y)                 (x - y)          (x - y)    ⎠  
⌡                                                                       

In [7]:

p. Original issue for "#4313":https://github.com/sympy/sympy/issues/4313: "http://code.google.com/p/sympy/issues/detail?id=1214":http://code.google.com/p/sympy/issues/detail?id=1214

p. Original author: "https://code.google.com/u/104039945248245758823/":https://code.google.com/u/104039945248245758823/

**Comment by smichr** [comment]
In #12587 the equivalent method, `piecewise_integrate`, gives:

```
>>> factor_terms(piecewise_fold(e).piecewise_integrate(x))
Piecewise(
    (0, (x <= 0) & (y <= 0)),
    (-1/(x - y), (h <= x) & (y <= 0)),
    ((x - y**2/(x - y) + 2*y*log(x - y))/h**2, y <= 0),
    (-1/(x - y), (h <= y) & (x <= 0)),
    (0, (h <= x) & (h <= y)),
    ((x + 2*(-h + y)*log(x - y) - (h**2 - 2*h*y + y**2)/(x - y))/h**2, h <= y)
    (-y**2/(h**2*(x - y)), x <= 0),
    (-(h**2 - 2*h*y + y**2)/(h**2*(x - y)), h <= x),
    (x/h**2, True))
```

(The normal `integrate` in #12587 gives the *continuous* integrated result as a function of x...but that may change depending on feedback.)
