### ISSUE TITLE
Integration failure

### ISSUE THREAD

**Issue by sympy-issue-migrator** [sympy/sympy#4326]
bc.. Well, I was trying to calculate the volume of a cylindrical wedge ( http://mathworld.wolfram.com/CylindricalWedge.html )

In [1]: R, b, h = symbols('Rbh', Real=True)

In [2]: x = symbols('x')

In [3]: 2*integrate(((h*(x-R+b))/b)*sqrt(R**2-x**2), (x, R-b, R))
Out[3]: 
    R                                
    ⌠                                
    ⎮        ⎽⎽⎽⎽⎽⎽⎽⎽⎽               
    ⎮       ╱  2    2                
    ⎮   h⋅╲╱  R  - x  ⋅(b + x - R)   
2⋅  ⎮   ────────────────────────── dx
    ⎮               b                
    ⌡                                
  R - b

p. Original issue for "#4326":https://github.com/sympy/sympy/issues/4326: "http://code.google.com/p/sympy/issues/detail?id=1227":http://code.google.com/p/sympy/issues/detail?id=1227

p. Original author: "https://code.google.com/u/111211129517653688844/":https://code.google.com/u/111211129517653688844/

**Comment by smichr** [comment]
This now gives

```python
>>> R, b, h = var('Rbh',real=True)
>>> i=2*integrate(((h*(x-R+b))/b)*sqrt(R**2-x**2), (x, R-b, R))
>>> i.has(S.NaN)
False
>>> i
2*h*(-pi*R**3/4 + pi*R**2*b/4)/b - 2*h*(-R*Piecewise((-I*R**2*acosh((R
- b)/R)/2 - I*R*(R - b)/(2*sqrt(-1 + (R - b)**2/R**2)) + I*(R -
b)**3/(2*R*sqrt(-1 + (R - b)**2/R**2)), Abs((R - b)**2/R**2) > 1),
(R**2*asin((R - b)/R)/2 + R*sqrt(1 - (R - b)**2/R**2)*(R - b)/2,
True)) + b*Piecewise((-I*R**2*acosh((R - b)/R)/2 - I*R*(R -
b)/(2*sqrt(-1 + (R - b)**2/R**2)) + I*(R - b)**3/(2*R*sqrt(-1 + (R -
b)**2/R**2)), Abs((R - b)**2/R**2) > 1), (R**2*asin((R - b)/R)/2 +
R*sqrt(1 - (R - b)**2/R**2)*(R - b)/2, True)) - (R**2 - (R -
b)**2)**(3/2)/3)/b
```

So perhaps this can be closed with a test (if necessary).

**Comment by asmeurer** [comment]
Yeah the contains nan vs. is nan stuff has been fixed in `_eval_interval` for some time. We can check, but I doubt a test is needed.

**Comment by smichr** [comment]
The integration starts to work with 

```
commit 9f5dbf4630121ccc6f4d8a848620d0b10760b660
Merge: 33b86c4 1ddbb4e
Author: Aaron Meurer <asmeurer@gmail.com>
Date:   Fri Dec 23 04:47:04 2011 -0800

    Merge pull request #504 from ness01/gsoc-2

    Gsoc 2

```

By that point there is no NaN in the result. Since this is such a large commit, improving integration, and there are probably lots of integrals that wouldn't have worked before that do work now I am going to pass on documenting that this particular integral now works, too.

**Comment by certik** [comment]
Thanks @smichr.

**Comment by asmeurer** [comment]
8eab3aa1 is the relevant change here.

**Comment by asmeurer** [comment]
And indeed if I run the integral in 8eab3aa1~ I get a result with nan (and in 8eab3aa1 it gives an unevaluated Integral).
