### ISSUE TITLE
Real don't manage unicode argument

### ISSUE THREAD

**Issue by wxgeo** [sympy/sympy#4337]
bc.. Using sympy 0.6.3, Real has a strange behaviour if you use unicode as argument:

> > > pi="3.14159265358979323846264338327950288419716939937510582097494"
> > > sympy.Real(pi,60)
> > > 3.14159265358979323846264338327950288419716939937510582097494

That's ok.

And then, the same with unicode :

> > > pi=u"3.14159265358979323846264338327950288419716939937510582097494"
> > > sympy.Real(pi,60)
> > > 3.14159265358979311599796346854418516159057617187500000000000

This may be patch this way :
in sympy/core/numbers.py
replace
       if isinstance(num, (str, decimal.Decimal)):
            _mpf_ = mlib.from_str(str(num), prec, rnd)
by
       if isinstance(num, (str, unicode, decimal.Decimal)):
            _mpf_ = mlib.from_str(str(num), prec, rnd)

Thanks a lot !

p. Original issue for "#4337":https://github.com/sympy/sympy/issues/4337: "http://code.google.com/p/sympy/issues/detail?id=1238":http://code.google.com/p/sympy/issues/detail?id=1238

p. Original author: "https://code.google.com/u/117997262464115802198/":https://code.google.com/u/117997262464115802198/

**Comment by oscarbenjamin** [comment]
This was recently fixed (not sure of the issue number). On Python 2.7:
```julia
In [1]: pi=u"3.14159265358979323846264338327950288419716939937510582097494"

In [2]: Float(pi, 60)
Out[2]: 3.14159265358979323846264338327950288419716939937510582097494
```

**Comment by smichr** [comment]
#16096, perhaps?
