### ISSUE TITLE
export mathml by default

### ISSUE THREAD

**Issue by certik** [sympy/sympy#4372]
bc.. Currently one has to do:

In [2]: from sympy.printing.mathml import print_mathml

In [3]: print_mathml(x+sin(x))
<apply>
    <plus/>
    <apply>
        <sin/>
        <ci>
            x
        </ci>
    </apply>
    <ci>
        x
    </ci>
</apply>

Why not to export mathml and print_mathml by default?

p. Original issue for "#4372":https://github.com/sympy/sympy/issues/4372: "http://code.google.com/p/sympy/issues/detail?id=1273":http://code.google.com/p/sympy/issues/detail?id=1273

p. Original author: "https://code.google.com/u/104039945248245758823/":https://code.google.com/u/104039945248245758823/

**Comment by oscargus** [comment]
This seems to have be solved in current master so I am closing for now.
