### ISSUE TITLE
more tests for the solvers module

### ISSUE THREAD

**Issue by sympy-issue-migrator** [sympy/sympy#4383]
bc.. We need more tests for the solvers module.(sympy.solvers.tests.test_solvers)

It is a very important feature and most parts have very few tests.

p. Original issue for "#4383":https://github.com/sympy/sympy/issues/4383: "http://code.google.com/p/sympy/issues/detail?id=1284":http://code.google.com/p/sympy/issues/detail?id=1284

p. Original author: "https://code.google.com/u/103948515893177094863/":https://code.google.com/u/103948515893177094863/

**Comment by abaokar-07** [comment]
@asmeurer What more tests do we need to add? I mean what sorts of equation should be added to the test_solvers.py?

**Comment by moorepants** [comment]
Anything that isn't there already is a good place to start.

**Comment by abaokar-07** [comment]
@moorepants But there are a lot of equations that aren't added, so what should we add anyway? Or which category equations are required to be added?

**Comment by abaokar-07** [comment]
In the test_solvers.py file, line number 121 : 
assert solve(a + b*x - 2, [a, b]) == {a: 2, b: 0}
Can't there be another set of solutions in terms of 'x'?

**Comment by oscarbenjamin** [comment]
I agree that more tests are need for the solvers module but this is a very old issue and doesn't contain any useful information to help anyone solve the problem.

A new issue could be opened that details what currently should be done i.e. which parts of solvers need improved test coverage.
