### ISSUE TITLE
Interval arithmetic support

### ISSUE THREAD

**Issue by jbaayen** [sympy/sympy#4417]
bc.. It would be great if sympy would support mpmath's interval arithmetic
class, mpi, so that one could do something like:

f=x**2
f.subs(x,mpi(0,1))

p. Original issue for "#4417":https://github.com/sympy/sympy/issues/4417: "http://code.google.com/p/sympy/issues/detail?id=1318":http://code.google.com/p/sympy/issues/detail?id=1318

p. Original author: "https://code.google.com/u/104490253617518974981/":https://code.google.com/u/104490253617518974981/

**Comment by davidlowryduda** [comment]
Good interval arithmetic was added in #2682. I think that this issue should now be closed.

**Comment by certik** [comment]
@davidlowryduda thanks!
