### ISSUE TITLE
make lambdify to use scipy for integration optionally

### ISSUE THREAD

**Issue by certik** [sympy/sympy#4471]
bc.. make lambdify to use scipy.integrate.quad for all Integrals. This should
make it as fast as doing by hand:

quad(lambda x: exp(-x**2), 0, oo)

p. Original issue for "#4471":https://github.com/sympy/sympy/issues/4471: "http://code.google.com/p/sympy/issues/detail?id=1372":http://code.google.com/p/sympy/issues/detail?id=1372

p. Original author: "https://code.google.com/u/104039945248245758823/":https://code.google.com/u/104039945248245758823/

**Comment by asmeurer** [comment]
To solve this, you need to recursively lambdify the integrand. This can be done naively as described at https://stackoverflow.com/questions/51173981/lambdify-a-parametric-integral, but that involves relambdifying the integrand every time it is called. Better would be to lambdify it once, save it as a dummy function, and add that function to the outer lambdify namespace. I think this would not be difficult with the current lambdify printer architecture, though I'm not sure we may need to refactor things to make sure all the relevant arguments are passed through to the recursive lambdify call.
