### ISSUE TITLE
integrate takes forever

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#4540]
```
I ran the below for several hours, and when after that it had still not returned anything, I gave up.  It 
should return an Integral class (at least that is what Maple does).  

integrate((sin(1/x) - x*exp(x))/((-sin(1/x) + x*exp(x))*x + x*sin(1/x)), x)
```

Original issue for #4540: http://code.google.com/p/sympy/issues/detail?id=1441
Original author: https://code.google.com/u/asmeurer@gmail.com/
Original owner: https://code.google.com/u/asmeurer@gmail.com/

**Comment by oldk1331** [comment]
Seems this integral still takes forever (at least a few minutes) in sympy 1.0.

FYI, FriCAS can prove this integral has no elementary result.

**Comment by asmeurer** [comment]
SymPy will assumedly be able to as well, whenever trig functions are implemented in the Risch algorithm. Getting the answer in terms of Ci, at least from Risch, is more complicated.

**Comment by smichr** [comment]
I affirm again, that this does not take a long time -- about 30 s on a slow machine -- so I am closing this issue:
```
>>> integrate((sin(1/x) - x*exp(x))/((-sin(1/x) + x*exp(x))*x + x*sin(1/x)), x)
-Integral(1/x, x) - Integral(-exp(-x)*sin(1/x)/x**2, x)
```
