### ISSUE TITLE
docs: adding instructions how to get stuff working on windows

### ISSUE THREAD

**Issue by certik** [sympy/sympy#4563]
```
See this thread for more info: http://groups.google.com/group/sympy/browse_thread/thread/de26d886c983fbec
```

Original issue for #4563: http://code.google.com/p/sympy/issues/detail?id=1464
Original author: https://code.google.com/u/104039945248245758823/

**Comment by souravsingh** [comment]
Is the issue still open?

**Comment by asmeurer** [comment]
The user installation docs should work fine on Windows. I'm not sure if the developer docs  https://github.com/sympy/sympy/wiki/Development-workflow are sufficient.

**Comment by htrivedi04** [comment]
@asmeurer I have just checked the developer docs and followed them to setup my developer environment in Windows, and can confirm that they are sufficient. You can close this issue! In case you need any other modifications to the docs, I'll be happy to collaborate.

**Comment by asmeurer** [comment]
Indeed I haven't heard any complaints from Windows users.
