### ISSUE TITLE
Symbol('f')(x) != Function('f')(x)

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#4711]
```
>>> S("f(x)") == Function('f')(Symbol('x'))
False

sympify should make "f(x)" the same as Function('f')(Symbol('x'))
```

Original issue for #4711: http://code.google.com/p/sympy/issues/detail?id=1612
Original author: https://code.google.com/u/asmeurer@gmail.com/
Referenced issues: #5154
Original owner: https://code.google.com/u/asmeurer@gmail.com/

**Comment by isuruf** [comment]
Close as invalid?

**Comment by asmeurer** [comment]
I guess close in favor of https://github.com/sympy/sympy/issues/3539.
