### ISSUE TITLE
integral of heaviside

### ISSUE THREAD

**Issue by sympy-issue-migrator** [sympy/sympy#4795]
```
sympy seems to be unable to compute the integral of a Heaviside function

f=Heaviside(x)
g=integrate(f,(x,0,1))
float(g)
#ValueError: Symbolic value, can't compute
```
Original issue for #4795: http://code.google.com/p/sympy/issues/detail?id=1696
Original author: https://code.google.com/u/106717656539804830979/

**Comment by ashutoshsaboo** [comment]
@asmeurer @sympy-issue-migrator Is this issue fixed? I would like to work on this. Can I work on this?

**Comment by asmeurer** [comment]
Looks like it:

```
In [11]: integrate(Heaviside(x), (x, 0, 1))
Out[11]: 1

In [12]: float(Integral(Heaviside(x), (x, 0, 1)))
Out[12]: 1.0
```

**Comment by Chuyen-Toung** [comment]
but it seems to be strange when computing the integral of a function with Heaviside and variable

sympy:

`import sympy as m

a, x = m.symbols('a,x')

f = a+m.Heaviside(x-0.5)

print(m.integrate(f, (x, -1.0, 1.0)))`

get:
`2.0*a + 0.5*meijerg(((2, 1), ()), ((), (1, 0)), -1.0) - 0.5*meijerg(((2, 1), ()), ((), (1, 0)), 1.0) + 0.5*meijerg(((2, 1), ()), ((), (1, 0)), 2.0) - 0.5*meijerg(((2, 1), ()), ((), (1, 0)), -2.0)`


matlab:

`syms a x

f = a + heaviside(x-0.5)

int(f,x,-1.0,1.0)`

get:

`ans =
2*a + 1/2`
