### ISSUE TITLE
XFAIL decorator does not work with py.test

### ISSUE THREAD

**Issue by vks** [sympy/sympy#4825]
```
$ py.test -k sqrt
[...]
    def wrapper():
        try:
            func()
        except Exception:
>           raise XFail()
E           XFail

sympy/utilities/pytest.py:42: XFail
[...]
```

Original issue for #4825: http://code.google.com/p/sympy/issues/detail?id=1726
Original author: https://code.google.com/u/Vinzent.Steinberg@gmail.com/

**Comment by oscarbenjamin** [comment]
It is now possible to use pytest with SymPy. The XFAIL decorator works as well.
