### ISSUE TITLE
Rename .func attribute

### ISSUE THREAD

**Issue by rlamy** [sympy/sympy#4834]
```
I.e. use expr.func == some_class instead of isinstance(expr, some_class), and
expr.func instead of type(expr) wherever possible.

The Python class of a sympy object is an implementation detail whereas
the head of an expression (i.e. whether it's an addition, a multiplication,
etc.) is a very important piece of data for symbolic manipulation. The
latter is defined by the attribute 'func'. Using it systematically allows
to abstract the notion of head from the implementation, allowing design
changes and paving the way for possible optimisations and refactorings.

The patch is probably incomplete: it only includes things that caused
problems while I worked on issue 4787 . There are probably more places where
the transform can be applied.
```

Original issue for #4834: http://code.google.com/p/sympy/issues/detail?id=1735
Original author: https://code.google.com/u/101272611947379421629/
Original owner: https://code.google.com/u/101272611947379421629/

**Comment by oscarbenjamin** [comment]
I see two issues mentioned above:

1. Rename .func or .args. That seems unnecessary

2. Change it so that e.g. `sin` can be a proper SymPy object (i.e. Basic instance?) rather than the Python type of an object like `sin(1)`. Is that a desired change?

**Comment by asmeurer** [comment]
It's probably too late at this point to rename func or args (and the names seem fine to me).

As for making functions objects, that is issue https://github.com/sympy/sympy/issues/4787.

**Comment by oscarbenjamin** [comment]
Okay so this can be closed then
