### ISSUE TITLE
how to implement functions for sympy

### ISSUE THREAD

**Issue by vks** [sympy/sympy#4841]
```
From doc/src/guide.txt:

[...]
if isinstance(arg, Basic.NaN):
    return S.NaN
if isinstance(arg, Basic.Zero):
    return S.Zero
[...]

I have several questions:

Why using isinstance()?
Why mixing S.Zero and Basic.Zero?
Why not using

if arg is S.NaN: ...

?
```

Original issue for #4841: http://code.google.com/p/sympy/issues/detail?id=1742
Original author: https://code.google.com/u/Vinzent.Steinberg@gmail.com/
Original owner: https://code.google.com/u/Vinzent.Steinberg@gmail.com/

**Comment by oscarbenjamin** [comment]
That part of the guide should be updated to use S.NaN rather than Basic.NaN. I get:
```
AttributeError: type object 'Basic' has no attribute 'NaN'
```
