### ISSUE TITLE
sympify(u"α") does not work

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#4862]
```
In [37]: S("α")
--------------------------------------------------------------------------
-
SympifyError                              Traceback (most recent call last)

/Users/aaronmeurer/Documents/Python/sympy/sympy/<ipython console> in <module>()

/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/core/sympify.pyc in sympify(a, 
locals, convert_xor)
    114             a = a.replace('^','**')
    115         import ast_parser
--> 116         return ast_parser.parse_expr(a, locals)
    117     raise SympifyError("%r is NOT a valid SymPy expression" % a)
    118 

/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/core/ast_parser.pyc in 
parse_expr(s, local_dict)
     89             a = parse(s.strip(), mode="eval")
     90         except SyntaxError:
---> 91             raise SympifyError("Cannot parse.")
     92         a = Transform(local_dict, global_dict).visit(a)
     93         e = compile(a, "<string>", "eval")

SympifyError: SympifyError: Cannot parse.

sympify() should be able to parse greek letters, as they are pretty printed for symbols of that 
name:

In [44]: alpha = Symbol('alpha')

In [45]: alpha
Out[45]: α
```

Original issue for #4862: http://code.google.com/p/sympy/issues/detail?id=1763
Original author: https://code.google.com/u/asmeurer@gmail.com/
Original owner: https://code.google.com/u/asmeurer@gmail.com/

**Comment by SaiHarsh** [comment]
If it's still open I would like to work on this.

**Comment by asmeurer** [comment]
Looks like it still doesn't work.

**Comment by asmeurer** [comment]
But there may already be a fix at https://github.com/sympy/sympy/pull/8334

**Comment by SaiHarsh** [comment]
@asmeurer  I feel this is not fixed  till now, please have a look below, I would like to solve this can you guide me

```
In [1]: from sympy import *

In [2]: sympify(u"α")
---------------------------------------------------------------------------
SympifyError                              Traceback (most recent call last)
<ipython-input-2-cf317bba09e1> in <module>()
----> 1 sympify(u"α")

/home/saiharsh/sympy/sympy/core/sympify.pyc in sympify(a, locals, convert_xor, strict, rational, evaluate)
    329         expr = parse_expr(a, local_dict=locals, transformations=transformations, evaluate=evaluate)
    330     except (TokenError, SyntaxError) as exc:
--> 331         raise SympifyError('could not parse %r' % a, exc)
    332 
    333     return expr

SympifyError: Sympify of expression 'could not parse u'\u03b1'' failed, because of exception being raised:
SyntaxError: invalid syntax (<string>, line 1)
```

**Comment by asmeurer** [comment]
We just need to update our copy of the Python tokenizer (in sympy_tokenize.py) to be compatible with Python 3. 

I forget the reason why we have a copy of it instead of just using the version from the standard library? Can someone figure out the difference between our tokenizer and the Python 2 tokenizer?

**Comment by asmeurer** [comment]
It looks like our tokenizer is there to support two extensions:

- factorial (`x!`)
- repeated decimals (`1.[2]`)

I would reconsider for both of these if they could just be done with a preparser, so we can just use the standard tokenizer. That would also allow disabling these things, which currently isn't possible. We'd have to do some manual tokenization to make sure we don't preparse the inside of a string, though.

If we don't go this route, we need to update the tokenizer to be based on Python 3's grammar. This should be a simple matter of copying the Python 3 tokenize module and re-applying our modifications to it.

**Comment by asmeurer** [comment]
Actually to properly handle ! we have to do a proper tokenization. Consider more complicated expressions like `(1 + 2)!`. 

Perhaps it is possible to just tokenize the expression with `!` and postprocess. It seems to produce an ERRORTOKEN and not stop the tokenization.

```py
>>> import tokenize
>>> import io
>>> for i in tokenize.tokenize(io.BytesIO(b'(1 + 2)! + 1').readline):
...     print(i)
TokenInfo(type=59 (BACKQUOTE), string='utf-8', start=(0, 0), end=(0, 0), line='')
TokenInfo(type=53 (OP), string='(', start=(1, 0), end=(1, 1), line='(1 + 2)! + 1')
TokenInfo(type=2 (NUMBER), string='1', start=(1, 1), end=(1, 2), line='(1 + 2)! + 1')
TokenInfo(type=53 (OP), string='+', start=(1, 3), end=(1, 4), line='(1 + 2)! + 1')
TokenInfo(type=2 (NUMBER), string='2', start=(1, 5), end=(1, 6), line='(1 + 2)! + 1')
TokenInfo(type=53 (OP), string=')', start=(1, 6), end=(1, 7), line='(1 + 2)! + 1')
TokenInfo(type=56 (ERRORTOKEN), string='!', start=(1, 7), end=(1, 8), line='(1 + 2)! + 1')
TokenInfo(type=53 (OP), string='+', start=(1, 9), end=(1, 10), line='(1 + 2)! + 1')
TokenInfo(type=2 (NUMBER), string='1', start=(1, 11), end=(1, 12), line='(1 + 2)! + 1')
TokenInfo(type=0 (ENDMARKER), string='', start=(2, 0), end=(2, 0), line='')
```

For `0.[1]`, it's actually valid Python (it's an indexing of a float literal). So this can be post processed as well, probably at the AST level. We only allow this syntax for numeric values, no symbolic, so this isn't an issue.

**Comment by asmeurer** [comment]
Our transformations are currently done only with the tokenization, not the ast (though that [could change](https://github.com/sympy/sympy/issues/10805)). Regardless, handling `0.[1]` is trivial to do with the standard tokenization.

**Comment by asmeurer** [comment]
By the way you have to use `tokenize.generate_tokens`, not `tokenize.tokenize`, because in Python 2 `tokenize.tokenize` just prints the tokens instead of returning them.

**Comment by asmeurer** [comment]
Fix started at https://github.com/sympy/sympy/pull/14085.
