### ISSUE TITLE
ode can survive (so far) with less expansion

### ISSUE THREAD

**Issue by smichr** [sympy/sympy#4930]
```
If the expand()s in ode are changed to expand(mul=True) all the tests still
pass, so perhaps it can get by with less.

commit 1831 in smichr's 1766 branch at github
```

Original issue for #4930: http://code.google.com/p/sympy/issues/detail?id=1831
Original author: https://code.google.com/u/117933771799683895267/
Original owner: https://code.google.com/u/117933771799683895267/

**Comment by oscarbenjamin** [comment]
It's not easy to know what this issue originally referred to but I don't think it is needed any more
