### ISSUE TITLE
Implement sinc function

### ISSUE THREAD

**Issue by fredrik-johansson** [sympy/sympy#5051]
```
SymPy should implement a sinc function with correct evaluation at x = -oo,
0 and oo.

See: http://groups.google.com/group/sympy/browse_thread/thread/9243051af53c786?hl=en
```
Original issue for #5051: http://code.google.com/p/sympy/issues/detail?id=1952
Original author: https://code.google.com/u/111502149103757882156/

**Comment by lxkain** [comment]
1/(2*pi)*integrate(exp(1j*w*n), (w, -wc, wc))

does not correctly evaluate either

**Comment by asmeurer** [comment]
@lxkain can you open a new issue for this?

**Comment by lxkain** [comment]
I already did - thank you for the good work!

**Comment by asmeurer** [comment]
https://github.com/sympy/sympy/issues/10434
