### ISSUE TITLE
Bug in dsolve() undetermined coefficients solver

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#5096]
```
>>> dsolve(f(x).diff(x, x) + f(x) - x*sin(x - 2), f(x), hint='nth_linear_constant_coeff_undetermined_coefficients')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "sympy/solvers/ode.py", line 457, in dsolve
    match=hints[hint]), func, hints['order'], hint)
  File "sympy/solvers/ode.py", line 2370, in ode_nth_linear_constant_coeff_undetermined_coefficients
    return _solve_undetermined_coefficients(eq, func, order, match)
  File "sympy/solvers/ode.py", line 2460, in _solve_undetermined_coefficients
    " method of undetermined coefficients (unable to solve for coefficients).")
NotImplementedError: Could not solve -x*sin(-2 + x) + D(f(x), x, x) + f(x) using the  method of undetermined coefficients (unable to solve for coefficients).
```
As I was explaining to Chris on IRC, any time you explicitly pass a hint to dsolve() and it gives NotImplementedError, it means that there was a problem in the particular solver, so it is a bug (which is another reason why issue 5095 needs to be fixed).  

I haven't looked into it yet, but if I had to guess, I would say it's because of the fishy behavior of sin(2 - x) vs. sin(x - 2).

```
Original issue for #5096: http://code.google.com/p/sympy/issues/detail?id=1997
Original author: https://code.google.com/u/asmeurer@gmail.com/
Referenced issues: #5095
Original owner: https://code.google.com/u/asmeurer@gmail.com/
```

**Comment by oscarbenjamin** [comment]
This is still the case in master. This ODE is solved by variation of parameters but not by undetermined coefficients:
```julia
In [20]: eq = f(x).diff(x, x) + f(x) - x*sin(x - 2)                                                                                                           

In [21]: classify_ode(eq)                                                                                                                                     
Out[21]: 
('nth_linear_constant_coeff_undetermined_coefficients',
 'nth_linear_constant_coeff_variation_of_parameters',
 'nth_linear_constant_coeff_variation_of_parameters_Integral')

In [22]: dsolve(eq)                                                                                                                                           
---------------------------------------------------------------------------
NotImplementedError                       Traceback (most recent call last)
...
NotImplementedError: Could not solve `-x*sin(x - 2) + f(x) + Derivative(f(x), (x, 2))` using the method of undetermined coefficients (unable to solve for coefficients).

In [24]: dsolve(eq, hint='nth_linear_constant_coeff_variation_of_parameters')                                                                                 
Out[24]: 
                                                     2                                        ⎛   2                                       ⎞    2   
                   x⋅(-x⋅cos(x - 2) + sin(x - 2))⋅sin (x)   ⎛     sin(x - 2)⋅cos(x)⎞          ⎝- x ⋅cos(x - 2) + x⋅sin(x - 2) + cos(x - 2)⎠⋅cos (x)
f(x) = C₂⋅cos(x) + ────────────────────────────────────── + ⎜C₁ + ─────────────────⎟⋅sin(x) + ─────────────────────────────────────────────────────
                                     4                      ⎝             4        ⎠                                    4                          

In [25]: checkodesol(eq, _)                                                                                                                                   
Out[25]: (True, 0)
```

**Comment by Mohitbalwani26** [comment]
@oscarbenjamin can i work on this issue?

**Comment by oscarbenjamin** [comment]
Yes

**Comment by Mohitbalwani26** [comment]
@oscarbenjamin In parameters of dsolve the `hint = default` if carried out in this example but as `default = classify_ode(eq)[0]` from classification. so shouldn't it be better that we check for all the hints returned by `classify_ode`?

**Comment by oscarbenjamin** [comment]
We want to make sure all hints work on as many equations as possible. If a hint matches the equation then it should be able to give a solution for it. The issue here is about improving the undetermined coefficients code so that it works in this case.

**Comment by Mohitbalwani26** [comment]
I guess i have found the bug the method `_solve_undetermined_coefficients` considers `sin(x-2) and sin(x)` as separate terms for checking the condition of trial set instead in this example the trial set should be multiplied by `x` but the code isn't doing the same.am i correct?

**Comment by oscarbenjamin** [comment]
Yes I think so. Since the complementary function is not linearly independent from trial set we need to multiply by `x`...

**Comment by oscarbenjamin** [comment]
The same problem occurs any time the non-homogeneous part is a shift of the complementary function:
```julia
In [3]: dsolve(f(x).diff(x, 2) - f(x) - exp(x - 1))                                                                                            
---------------------------------------------------------------------------
NotImplementedError
```

This seems to work for the cases I tested:
```julia
diff --git a/sympy/solvers/ode.py b/sympy/solvers/ode.py
index 8a92d329c3..5a5c0d5fce 100644
--- a/sympy/solvers/ode.py
+++ b/sympy/solvers/ode.py
@@ -5761,7 +5761,12 @@ def _solve_undetermined_coefficients(eq, func, order, match):
         coefflist.append(c)
         trialfunc += c*i
 
-    eqs = sub_func_doit(eq, f(x), trialfunc)
+    while True:
+        eqs = sub_func_doit(eq, f(x), trialfunc)
+        if set(coefflist) < eqs.free_symbols:
+            break
+        else:
+            trialfunc *= x
 
     coeffsdict = dict(list(zip(trialset, [0]*(len(trialset) + 1))))
```
Putting a potentially infinite loop there makes me nervous though...

**Comment by Mohitbalwani26** [comment]
```
I also thought about this so i am trying to find some alternative by using 
```
match
```
Or something through which i can replace 
```
x + constant_term 
```
With 
```
x
```
But it would be kind of hard coded.So i guess whil loop is better choice in that case.

**Comment by oscarbenjamin** [comment]
I guess the real test is if any of the trial functions satisfies the homogeneous part of the equation.

**Comment by Mohitbalwani26** [comment]
> I guess the real test is if any of the trial functions satisfies the homogeneous part of the equation.
can you give an example for better understanding ?

**Comment by oscarbenjamin** [comment]
I'm not sure what I meant by that actually.

Here:
https://github.com/sympy/sympy/blob/dede4098030c77de8c1f5e360f2e552169809411/sympy/solvers/ode.py#L5742-L5752
It is not enough to check if the function is in the trialset.

**Comment by Mohitbalwani26** [comment]
I guess we can check everytime wronskian that while it is 0 then we multiply by x

**Comment by Mohitbalwani26** [comment]
> The same problem occurs any time the non-homogeneous part is a shift of the complementary function:
> 
> ```julia
> In [3]: dsolve(f(x).diff(x, 2) - f(x) - exp(x - 1))                                                                                            
> ---------------------------------------------------------------------------
> NotImplementedError
> ```
> 
> This seems to work for the cases I tested:
> 
> ```julia
> diff --git a/sympy/solvers/ode.py b/sympy/solvers/ode.py
> index 8a92d329c3..5a5c0d5fce 100644
> --- a/sympy/solvers/ode.py
> +++ b/sympy/solvers/ode.py
> @@ -5761,7 +5761,12 @@ def _solve_undetermined_coefficients(eq, func, order, match):
>          coefflist.append(c)
>          trialfunc += c*i
>  
> -    eqs = sub_func_doit(eq, f(x), trialfunc)
> +    while True:
> +        eqs = sub_func_doit(eq, f(x), trialfunc)
> +        if set(coefflist) < eqs.free_symbols:
> +            break
> +        else:
> +            trialfunc *= x
>  
>      coeffsdict = dict(list(zip(trialset, [0]*(len(trialset) + 1))))
> ```
> 
> Putting a potentially infinite loop there makes me nervous though...

I tested this locally it throws exception.

**Comment by oscarbenjamin** [comment]
> I guess we can check everytime wronskian that while it is 0 then we multiply by x

The problem is the wronskian is not zero:
```julia
In [5]: dsolve(f(x).diff(x, 2) + f(x))                                                                                                         
Out[5]: f(x) = C₁⋅sin(x) + C₂⋅cos(x)

In [6]: wronskian([sin(x), cos(x), x*sin(x-2)], x)                                                                                             
Out[6]: 
       2                                 2                                        2                                        2   
- x⋅sin (x)⋅sin(x - 2) - x⋅sin(x - 2)⋅cos (x) - (-x⋅sin(x - 2) + 2⋅cos(x - 2))⋅sin (x) - (-x⋅sin(x - 2) + 2⋅cos(x - 2))⋅cos (x)

In [7]: simplify(_)                                                                                                                            
Out[7]: -2⋅cos(x - 2)
```

The issue here arises because the derivatives of the trial function has terms that are not linearly independent with the elementary solutions in the complementary function. There is a useful discussion of that here (which includes almost exactly the example in this issue):
https://www.cliffsnotes.com/study-guides/differential-equations/second-order-equations/the-method-of-undetermined-coefficients

**Comment by oscarbenjamin** [comment]
> There is a useful discussion of that here (which includes almost exactly the example in this issue):
> https://www.cliffsnotes.com/study-guides/differential-equations/second-order-equations/the-method-of-undetermined-coefficients

I think it would be good to change the undetermined coefficients code to follow the approach there: explicitly construct the "family" of the trial functions and check whether any element of the family solves the ODE. The family is constructed by ignoring coefficients and taking unions in the case of `Add` and the Cartesian product in the case of `Mul`.

**Comment by Mohitbalwani26** [comment]
> > There is a useful discussion of that here (which includes almost exactly the example in this issue):
> > https://www.cliffsnotes.com/study-guides/differential-equations/second-order-equations/the-method-of-undetermined-coefficients
> 
> I think it would be good to change the undetermined coefficients code to follow the approach there: explicitly construct the "family" of the trial functions and check whether any element of the family solves the ODE. The family is constructed by ignoring coefficients and taking unions in the case of `Add` and the Cartesian product in the case of `Mul`.

currently the family is constructed by correct method taking in account for `Mul` and `Add` but this method does not check for linear dependency on complimentary solution so i think we should change the code block which just `checks the function in trialset`

**Comment by Mohitbalwani26** [comment]
> The problem is the wronskian is not zero:
> 
> ```julia
> In [5]: dsolve(f(x).diff(x, 2) + f(x))                                                                                                         
> Out[5]: f(x) = C₁⋅sin(x) + C₂⋅cos(x)
> 
> In [6]: wronskian([sin(x), cos(x), x*sin(x-2)], x)                                                                                             
> Out[6]: 
>        2                                 2                                        2                                        2   
> - x⋅sin (x)⋅sin(x - 2) - x⋅sin(x - 2)⋅cos (x) - (-x⋅sin(x - 2) + 2⋅cos(x - 2))⋅sin (x) - (-x⋅sin(x - 2) + 2⋅cos(x - 2))⋅cos (x)
> 
> In [7]: simplify(_)                                                                                                                            
> Out[7]: -2⋅cos(x - 2)
> ```
> 

> ```julia
> In [1]: wronskian([sin(x),cos(x),x*sin(x-2),x*cos(x-2),sin(x-2),cos(x-2)],x)
> out [1]: 0
> ```
sin(x-2) is linearly dependent on sin(x) and you were applying wronskian for sin(x) and x*sin(x-2)
