### ISSUE TITLE
has() doesn't like sqrt

### ISSUE THREAD

**Issue by smichr** [sympy/sympy#5101]
While it's possible to see if an expr has cos, a similar request for sqrt fails:
```
>>> cos(x).has(cos)
True
>>> sqrt(x).has(sqrt)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "sympy\core\basic.py", line 916, in has
    p = sympify(patterns[0])
  File "sympy\core\sympify.py", line 125, in sympify
    return ast_parser.parse_expr(a, locals)
  File "sympy\core\ast_parser.py", line 90, in parse_expr
    raise SympifyError("Cannot parse.")
sympy.core.sympify.SympifyError: SympifyError: 'Cannot parse.'
```

Original issue for #5101: http://code.google.com/p/sympy/issues/detail?id=2002
Original author: https://code.google.com/u/117933771799683895267/
Original owner: https://code.google.com/u/117933771799683895267/

**Comment by oscarbenjamin** [comment]
This can be closed if the current behaviour is documented

**Comment by sylee957** [comment]
I see there is an another duplicate `Sqrt` in codegen module that does not expand, so if you use that, maybe it can be possible to `.has(Sqrt)`
But I wonder if such naming warkaround are needed in the codegen if the original `sqrt` was a class than function.

**Comment by smichr** [comment]
> if the original `sqrt` was a class than function.

If this is done then all code that looks for Pow would have to be modified to also recognize sqrt.
