### ISSUE TITLE
bullet proofing doit

### ISSUE THREAD

**Issue by smichr** [sympy/sympy#5161]
Today, RootOf in master has non-Basic args and if this gets fed to doit, it fails because those arguments don't have a doit method. There are two ways around this:

1) only process Basic args and leave the others unchanged (but then you have to watch for tuples that have Basic items in them -- but anything like Integral that has those should be changed to use the Tuple container instead)
2) fix RootOf

RootOf has already been fixed in polys11, but in the meantime (and in case other such objects are encountered) doit can be bullet-proofed by implementing 1. 

commit 2062 at github/smichr/t2 implements such a change but doesn't try to traverse tuples.

Original issue for #5161: http://code.google.com/p/sympy/issues/detail?id=2062
Original author: https://code.google.com/u/117933771799683895267/
Original owner: https://code.google.com/u/117933771799683895267/

**Comment by oscarbenjamin** [comment]
Does RootOf still have non-basic args?

```julia
In [11]: RootOf(x**5 - x +1, 1).args                                                                                                           
Out[11]: 
⎛ 5           ⎞
⎝x  - x + 1, 1⎠

In [12]: [isinstance(y, Basic) for y in _]                                                                                                     
Out[12]: [True, True]
```
