### ISSUE TITLE
has() might need wild flag

### ISSUE THREAD

**Issue by smichr** [sympy/sympy#5190]
I got an unexpected result from has():
```
h[1] >>> w=Wild('w')
h[1] >>> S(1).has(w)
True
```
I know this is because it allows for matching. Perhaps has should have a flag to disallow pattern matching. Possibilities include:

wild=False
literal=True
exact=True

Original issue for #5190: http://code.google.com/p/sympy/issues/detail?id=2091
Original author: https://code.google.com/u/117933771799683895267/
Original owner: https://code.google.com/u/117933771799683895267/

**Comment by smichr** [comment]
This now gives
```python
>>> [i.has(Wild('x')) for i in [S(1),x,Wild('x')]]
[False, False, True]
```
A test can close this issue.

**Comment by asmeurer** [comment]
I agree that `has` should work structurally only and other methods should be used for more advanced things like pattern matching.
