### ISSUE TITLE
GA SymPy module not work embeded

### ISSUE THREAD

**Issue by huahaiy** [sympy/sympy#5208]
I am learning Geometric Algebra and would like to use the SymPy GA module. Using the module in a python REPL is fine, but I have trouble getting it work within another environment. 

I have tried but failed to use GA module in Sage and in Pydev. In both cases, the following simple code generate the same error below. 

Code: 

from sympy.galgebra.GA import *
MV.setup('a b c')

Error:

AttributeError: 'str' object has no attribute 'a'

The same code works fine in a python REPL. Apparently I am not the only one having the problem, see this comment thread: http://gaupdate.wordpress.com/2010/10/27/g-utama-geometric-algebra-sympy-module-ga-for-phython/#comments

Original issue for #5208: http://code.google.com/p/sympy/issues/detail?id=2109
Original author: https://code.google.com/u/100301615825382667198/

**Comment by sylee957** [comment]
I'm closing this because `GA` isn't part of SymPy for now
