### ISSUE TITLE
List of dependencies

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#5259]
We should include in the README, and probably in the docs somewhere too, a list of all the "dependencies" of SymPy.  Now, obviously, SymPy's only dependency is Python, but there are several optional dependencies like IPython and gmpy that are not required but extent the capabilities of SymPy if they are installed. 

I am putting this here instead of just doing it and making a pull request because I don't know exactly how things work with things like numpy and scipy, and I also don't know if I am forgetting anything.  So far, I have this:

"""
Dependencies
------------

One of the fundamental design decisions behind SymPy is that it should not have any external dependencies besides Python to install.  Therefore, the only real "dependency" of SymPy is an installation of Python 2.4, 2.5, 2.6, or 2.7 (note that Python 2.4 support is deprecated and will no longer work in the next release).

However, there are several packages that are not required to use SymPy, but that will enhance SymPy if they are installed.  These packages are:

- IPython ( http://ipython.scipy.org/moin/ ).  IPython is a third party Python interactive shell that has many more features over the built-in Python interactive shell, such as tab-completetion and [what other important features should I mention here?].  If IPython is installed, isympy will automatically use it.  Otherwise, it will fall back to the regular Python interactive shell.  You can override this behavior by setting the -c option to isympy, like `isympy -c python`.

- gmpy ( http://code.google.com/p/gmpy/ ). gmpy is a Python wrapper around the GNU Multiple Precision Arithmetic Library (GMP). If gmpy is installed, it may make certain operations in SymPy faster, because it will use gmpy as the ground type instead of the built-in Python ground types.  If gmpy is not installed, it will fall back to the default Python ground types.  You can override this behavior by setting the SYMPY_GROUND_TYPES environment variable, such as `SYMPY_GROUND_TYPES=python isympy`. [Note: this should be an option to isympy!]

- Cython. [What exactly is the situation with Cython?]

- Numpy. [Ditto]

- Scipy. [Ditto]

- [Code generation dependencies?]

- [Other dependencies?]

Note that mpmath and pyglet, our floating point and plotting libraries respectively, are included with SymPy, so it is unnecessary to install them.  Indeed, SymPy will always use the version of mpmath or pyglet that comes with SymPy, even if a newer version is installed in the system.  This is done for compatibility reasons.

"""

OK, the text in [] are comments.  I need help from others writing the rest of this.  Note that I do not want to include any development dependencies here (like Sphinx), because the user does not care about that (maybe we could have that list somewhere else in our development docs).   

But basically for the others, explain what happens when they are installed and what happens when they are not (and how to override, if relevant).  

I just realized that the best way to do this would be through the wiki.  So if anyone has anything to add to this, please do it at https://github.com/sympy/sympy/wiki/Dependencies .  And then when we have it finished we can add it to the README and regular docs.
```

Original issue for #5259: http://code.google.com/p/sympy/issues/detail?id=2160
Original author: https://code.google.com/u/asmeurer@gmail.com/
Referenced issues: #4887
Original owner: https://code.google.com/u/asmeurer@gmail.com/
```

**Comment by wermos** [comment]
Is this issue still open? It appears that the `Valid` tag was removed 26 days ago (at the time of writing) and a `requirements.txt` file was added 6 years ago.

**Comment by ThePauliPrinciple** [comment]
I think @smichr has been removing all `Valid` tags since they don't hold any meaning (not sure on the specifics, but I think this got mentioned at some point). It does seem this can be closed though.

**Comment by oscarbenjamin** [comment]
I think that this is still a valid issue (although we don't need to use the valid tag). Installing gmpy2 makes a lot of core functionality in SymPy a lot faster but I don't see that mentioned in the README or here:
https://docs.sympy.org/dev/tutorial/preliminaries.html#installation
https://docs.sympy.org/dev/guides/getting_started/install.html

**Comment by moorepants** [comment]
I agree. The original idea is still needed in the documentation. The `requirements.txt` file isn't sufficient especially since it doesn't lay out all of the optional dependencies and what they are for.

**Comment by asmeurer** [comment]
I wonder what would be a better way to organize this, by function or by dependency? My initial thought was to just have a page listing every optional dependency and what it enables, but I wonder if it's better to invert that.

**Comment by oscarbenjamin** [comment]
I think it would be good to have one place that briefly lists the possible dependencies. That's useful for contributors if nothing else. Otherwise though the relevant dependencies should be mentioned with the functions that they work with e.g. lambdify, codegen etc.

With gmpy2 it's a bit different because it doesn't enable any functionality. It just makes some core things a lot faster. As far as I'm concerned you always want to install gmpy2 with SymPy. The only reason it's not a hard dependency is because it has a different license. That's why I think this should be explained in the installation instructions.

**Comment by asmeurer** [comment]
I've started this over at https://github.com/sympy/sympy/pull/22693. I haven't written everything yet, but have a skeleton of every optional dependency I could find. Let me know if I've missed any. Comments on the general organization of the page are also welcome.
