### ISSUE TITLE
gotcha addons

### ISSUE THREAD

**Issue by smichr** [sympy/sympy#5297]
```
Just so this doesn't get forgotten...

x**(a+b).expand() -- gotcha: you are expanding a+b not (x**(a+b))

powsimp(x**A*x**B) != x**(A+B) when A and B are non-commutative
```

Original issue for #5297: http://code.google.com/p/sympy/issues/detail?id=2198
Original author: https://code.google.com/u/117933771799683895267/
Original owner: https://code.google.com/u/117933771799683895267/

**Comment by VBhat97** [comment]
Hello @smichr @asmeurer ! I would like to work on this issue if its still not added. 

I did some reading and from the example : x**(a + b).subs(x, y) will return x**(a + b), not y**(a + b).
I think I am aware what needs to be added in the gotcha.

Could you please point me to the files which I need to work on for making these changes?

Thank you so much!

**Comment by shilpiprd** [comment]
i did some research when commutative= False argument is  passed 
do you still need some changes to be made to the gotcha folder to show some examples on non commutative

**Comment by shilpiprd** [comment]
I have submitted my first PR.
Please review.
gh pr checkout 22501

**Comment by asmeurer** [comment]
There is perhaps some confusion in the original issue here. `x**(a + b)` does not equal `x**a*x**b` in general when `a` and `b` do not commute (to see this, consider the power series definitions of the exponential). So the reason it does not expand isn't that "you are expanding a+b not (x**(a+b))" but rather that the expansion is not true in general, so SymPy does not perform it.

Here's a proof that `exp(a + b) = exp(a)*exp(b)` does hold when `a` and `b` commute https://www.physicsforums.com/threads/proof-of-commutative-property-in-exponential-matrices-using-power-series.578887/ (note that `x**a = exp(log(x)*a)` so the proof for general base is similar). To see that it doesn't hold for general `a` and `b`, you can just note that the proof doesn't work.  Or consider two non-commuting matrices. 

```py
>>> A = Matrix([[0, 1], [1, 0]])
>>> B = Matrix([[1, 1], [0, 1]])
>>> exp(A + B)
Matrix([
[                 exp(1 - sqrt(2))/2 + exp(1 + sqrt(2))/2, -sqrt(2)*exp(1 - sqrt(2))/2 + sqrt(2)*exp(1 + sqrt(2))/2],
[-sqrt(2)*exp(1 - sqrt(2))/4 + sqrt(2)*exp(1 + sqrt(2))/4,                  exp(1 - sqrt(2))/2 + exp(1 + sqrt(2))/2]])
>>> exp(A)*exp(B)
Matrix([
[ E*(exp(-1)/2 + E/2), E*(-exp(-1)/2 + E/2) + E*(exp(-1)/2 + E/2)],
[E*(-exp(-1)/2 + E/2), E*(-exp(-1)/2 + E/2) + E*(exp(-1)/2 + E/2)]])
>>> A*B
Matrix([
[0, 1],
[1, 1]])
>>> B*A
Matrix([
[1, 1],
[1, 0]])
```
