### ISSUE TITLE
nsimplify should use any symbols that already appear in expr

### ISSUE THREAD

**Issue by smichr** [sympy/sympy#5358]
nsimplify will only use certain symbols in the returned expression if it is told to. It seems to me that if there are NumberSymbols like pi already in the expression, those at least should be used:

```
    h[17] >>> nsimplify(pi/7.)
    0.142857142857143*pi
```

If nsimplify looked to see that there was already a pi then the user wouldn't have to explicitly say so:

```
    h[17] >>> nsimplify(_, [pi])
    pi/7
```

Should nsimplify check for such symbols if none are given?

Original issue for #5358: http://code.google.com/p/sympy/issues/detail?id=2259
Original author: https://code.google.com/u/117933771799683895267/
Original owner: https://code.google.com/u/117933771799683895267/

**Comment by smichr** [comment]
This now gives pi/7:
```python
>>> nsimplify(pi/7.)
pi/7
```
This can be closed with a test if there is not already one created by the change that fixed this.

**Comment by Perseus-Jackson477** [comment]
Is this just a testing issue?

**Comment by smichr** [comment]
yes - if there was no test for this sort of thing added, then one should be added. Otherwise, if there was a test added, then this can just be closed.

**Comment by zain93393** [comment]
I would like to work on this issue. Can you please guide me a bit as I am new to this open source contributions.

**Comment by smichr** [comment]
In the `test_simplify.py` where nsimplify is being tested, add a line that says `assert nsimplify(pi/7.0) == pi/7`. But we already have `assert nsimplify(pi/1e2) == pi/100` so I think this can just be closed.
