### ISSUE TITLE
LaTeX input

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#5418]
```
So my friend pointed out to me that WolphramAlpha lets you enter any LaTeX formula, and it will parse it and evaluate it.  I think we should have a parser that lets us do the same thing. In his case, he takes notes in LaTeX and does all of his homework in it, and he was able to just paste an expression from his homework into WolphramAlpha and it did if for him.
```

Original issue for #5418: http://code.google.com/p/sympy/issues/detail?id=2319
Original author: https://code.google.com/u/asmeurer@gmail.com/

**Comment by zelnoth** [comment]
Would also be interested in this. Have been working on a project for a while where we use mathquil (latex) and use sympy on the input (a bit like symbolab.com). I Wrote my own heuristic translator that  seems to work pretty well, but it would be fantastic if this was supported in sympy.

**Comment by caos21** [comment]
Hi. I am also interested. Any progress on this?

**Comment by zelnoth** [comment]
Out of curiosity, what exactly is needed of a latex->sympy translator for it to be implemented in sympy?

**Comment by moorepants** [comment]
You need to write a parser (or find one that parses into something we already have a parser for). See

https://github.com/sympy/sympy/tree/master/sympy/parsing

for examples of some of the parsers that are implemented in SymPy already.

**Comment by toolforger** [comment]
Parsing LaTeX is hard: The official grammar is that of TeX, and TeX macros change the TeX syntax, and none of the typical parsing approaches can handle that scenario.
Approach 1: Port the TeX parsing engine to Python. The TeX code is rock-stable and well-documented, so this is entirely doable, but it is going to be a whole lot of work. This would be a project in its own right.
Approach 2: Use the TeX (the binary) and somehow make it return the parse. I'm not sure that this is even doable, I suspect TeX isn't built for that. (It's entirely possible that rendering details get fed back into the parser. Knuth's programming style is from the 50ies, and defining separated software layers wasn't the big thing then that it is today.)
Approach 3: Collect a large body of LaTeX documents, define a grammar for a LaTeX subset, write a parser for that and tweak the grammar until it parses a sufficiently large subset of the documents.
Approach 4: Find an existing LaTeX parser and integrate that. Google turns up several of them (though at least at one point in time, all of them were dead).

**Comment by zelnoth** [comment]
You would only really need to parse the math subset of latex though so porting the whole parsing engine would be a bit overkill.

**Comment by toolforger** [comment]
I'd probably go for the subset option myself. That list was just for completeness :-)

You'll need to specify what subset exactly you're going to parse.
This is important for users, because then they'll know what will work and what won't.
It is also important for testers, because if something doesn't work they will need to know whether that's intentional (so they can ignore the problem) or not (so either the bug can get fixed, or the user docs can be made more precise about what does not work).

**Comment by Upabjojr** [comment]
What about parsing MathML? It is easier to parse MathML, and there are many LaTeX to MathML converters.

**Comment by toolforger** [comment]
You'll have to integrate the converter into SymPy, picking up the trouble SymPy is having with external dependencies.
Also, you'll pick up all idiosyncrasies of the converter.

This might still be the best (or least bad) option.

**Comment by zelnoth** [comment]
True. Anyone have a good list of a minimum subset of latex that needs to be supported?

**Comment by vermiculus** [comment]
Unfortunately, given the nature of TeX, there is no 'minimum subset'. Consider:

How would you parse the following expression?
```tex
\sum_{i \to 5} i^{-2} \sum_{b \to 10} b + 3
```

**Comment by zelnoth** [comment]
Saying that we could parse another language doesn't exactly solve the problem vermiculuis. Also there are minimum subsets though, depending on perspective. For instance a subset could just be supporting translation for all the latex used in mathquill. (Like symbolab does) Btw. How would that summation look in sympy vermiculus?

**Comment by asmeurer** [comment]
@vermiculus I don't even know how to interpret that expression myself. What does `i \to 5` mean?

**Comment by certik** [comment]
@asmeurer it means `i -> 5`.

**Comment by jksuom** [comment]
But in connection with a sum...?

**Comment by vermiculus** [comment]
Ah, sorry. We assumed a starting point of zero when I was going through all that stuff :) So,

```tex
\sum_{i = 1 \to 5} i^{-2} \sum_{b = 1 \to 10} b + 3
```

There's no way to unambiguously convert this expression without more information, but it's certainly valid notation where the meaning could be very obviously implied by the context. TeX isn't a maths *representation* language, it's a maths *typesetting* language.

**Comment by jksuom** [comment]
This expression is usually written
```
\sum_{i = 1}^5 i^{-2} \sum_{b = 1}^{10} b + 3
```

**Comment by vermiculus** [comment]
Excuse my memory, but my point stands...

**Comment by asmeurer** [comment]
Sure, there will have to be some places where some ambiguities are resolved in one way or another. As has been pointed out dozens of times, this would be very heuristical. I think in this case, it should assume that if an operator has no parenthese, only the closest "term" (for some definition of "term") binds to it. This would match how the SymPy printers work:

```
In [1]: latex(Sum(x**2, (x, 0, 10)))
Out[1]: '\\sum_{x=0}^{10} x^{2}'

In [2]: latex(Sum(x**2*y,  (x, 0, 10)))
Out[2]: '\\sum_{x=0}^{10} x^{2} y'

In [3]: latex(Sum(x**2*y + 1,  (x, 0, 10)))
Out[3]: '\\sum_{x=0}^{10} \\left(x^{2} y + 1\\right)'
```

Aside from the exponent vs. fraction, this is how SymPy prints this

```
In [14]: latex(Sum(1/i**2*Sum(b, (b, 1, 10)),  (i, 1, 5)) + 1)
Out[14]: '1 + \\sum_{i=1}^{5} \\frac{\\sum_{b=1}^{10} b}{i^{2}}'
```

And I also think we shouldn't worry about obscure ways of writing things like using `\to` in summation indices.

**Comment by shuokay** [comment]
Hi, @dennisss , I am using your latex_addons branch, most expr can be parsed correctly, however, when  there are more than 2 minus symbol, the parsed result is wrong.
```
>>> from sympy.parsing.latex import parse_latex
>>> parse_latex("2-1-1")
2
```
I think it is parsing "2-(1-1)". priority not set correctly.

**Comment by Harrison-G** [comment]
:+1: Would love to see this soon, especially seeing as [it's been planned on the wiki since March of 2012](https://github.com/sympy/sympy/wiki/Parsing).

**Comment by nicodjimenez** [comment]
augustt198 has released a parser for Latex that uses Antlr: https://github.com/augustt198/latex2sympy

**Comment by pylang** [comment]
A link to a project that claims to parse latex

https://github.com/augustt198/latex2sympy

**Comment by asmeurer** [comment]
latex2sympy has been included in sympy as sympy.parsing.latex.parse_latex() for some time now. It is still a work in progress that needs improvement, but it does work.
