### ISSUE TITLE
Printing of rational functions with floats could be better

### ISSUE THREAD

**Issue by mattpap** [sympy/sympy#5521]
```
Example:

In [1]: (3.0*x + 1.0)/(1.0*x)
Out[1]: 
1.0⋅(3.0⋅x + 1.0)
─────────────────
        x   

The first 1.0 should be in the denominator.
```

Original issue for #5521: http://code.google.com/p/sympy/issues/detail?id=2422
Original author: https://code.google.com/u/101069955704897915480/

**Comment by asmeurer** [comment]
The expression `(3.0*x + 1.0)/(1.0*x)` is represented as `Mul(1.0, 1/x, 3.0*x + 1.0)`. The 1 in the denominator is automatically extracted as the numeric coefficient of the Mul. The first argument of Mul being a numeric coefficient is something that is expected by a lot of code, so making it work differently would be a lot of work and probably not worth it. This means for floats in particular, there is no way to distinguish between "1/a" and the evaluated reciprocal of a. For rationals, the printer just puts the denominator in the denominator.
