### ISSUE TITLE
use_unicode=False does not work in pretty of physics.quantum

### ISSUE THREAD

**Issue by Krastanov** [sympy/sympy#5609]
```
Because the printing methods are overridden use_unicode is not taken into account.

In master:
In [1]: from sympy.physics.quantum.spin import JzKet

In [2]: pretty(JzKet(1,1),use_unicode=False)
Out[2]: ❘1,1⟩
```
Original issue for #5609: http://code.google.com/p/sympy/issues/detail?id=2510
Original author: https://code.google.com/u/100157245271348669141/

**Comment by flacjacket** [comment]
This is fixed and tested:

https://github.com/sympy/sympy/blob/master/sympy/physics/quantum/tests/test_printing.py
