### ISSUE TITLE
Compatibility with py.test

### ISSUE THREAD

**Issue by rlamy** [sympy/sympy#5641]
Currently, py.test 2.0.3 (the latest version) fails in master because of incompatible code in sympy/conftest.py - cf. http://paste.pocoo.org/show/428508/ .

It wouldn't be hard to fix it (and issue #4825 as well), which would be quite useful since py.test has much more functionalities than our homegrown and obsolete fork of it (notably JUnitXml for Jenkins integration). However, there are a few problems:
* sympy/mpmath/conftest.py is also incompatible with recent versions, but there are several possible workarounds allowing it to be ignored
* this would break compatibility with py.test 0.9.*, and therefore make it impossible (instead of merely seriously inconvenient) to run py.bench.

Original issue for #5641: http://code.google.com/p/sympy/issues/detail?id=2542
Original author: https://code.google.com/u/101272611947379421629/
Referenced issues: #4840, #4825
Original owner: https://code.google.com/u/101272611947379421629/

**Comment by skirpichev** [comment]
FYI, @pbrady, I think that the underlying reason for doctest's failure [mentioned here](http://stackoverflow.com/questions/26239640/py-test-doctests-not-respecting-execution-context) is using sys.displayhook by doctest, e.g. see [this](https://hg.python.org/cpython/rev/9704b9d810e5/).

I don't think you could workaround this with py.test without changing broken doctests.

**Comment by pbrady** [comment]
@skirpichev thanks for digging that up.  My take away from that chunk of code is that only way to effect the printed display of the doctests (as we do) is to have a custom doctest runner (as we do).  Does that sound about right to you?

**Comment by skirpichev** [comment]
> Does that sound about right to you?

Yes, I don't think this is solvable with py.test without monkeypatching of the doctest runner.

On another hand, I don't think that own testing framework is a viable idea for such project as sympy.  It's better to adopt tests for py.test in some way.

**Comment by pbrady** [comment]
I agree that it would be quite a bit easier from a maintenance perspective to ditch our custom test runner.  Would we still be able to test things like the unicode printer though?

**Comment by skirpichev** [comment]
Sure.  All you need - include `init_printing` calls.  `displayhook` shouldn't be the problem in such case.

(I assume that there is no other traps from unicode in the doctest, especially in 2.6.  But I'm not sure.)

**Comment by asmeurer** [comment]
A big difference between our doctest runner and the one in the standard library is that ours requires all imports to be in the doctest. The one in the standard library takes the namespace of the module that the function is in, which doesn't make much sense. I don't know how py.test handles this.

**Comment by skirpichev** [comment]
> The one in the standard library takes the namespace of the module that the function is in, which doesn't make much sense.

I suspect you can workaround this with `globs` kwarg of the `doctest`, isn't?

**Comment by skirpichev** [comment]
In fact, the [quoted above](http://stackoverflow.com/questions/26239640/py-test-doctests-not-respecting-execution-context) @pbrady's solution could be the answer for imports problem.  Not literally, but I think you got the idea.

**Comment by oscarbenjamin** [comment]
Pytest now works fine on current master. Doctests can be run if pytest-doctestplus is installed with:
```
$ pytest --doctestplus --doctest-rst
```

**Comment by oscarbenjamin** [comment]
This was fixed in #15768, #15720, #15587, #15515, #15506, #15500

#15503 cleaned up the warnings tests. This is still a problem that crops up if someone writes a test like `raises(DeprecationWarning, func)` so occasionally fixes for that need to be added.

**Comment by asmeurer** [comment]
Can we make `raises` fail if the first argument is SymPyDeprecationWarning?

**Comment by oscarbenjamin** [comment]
We could make raises fail. Alternatively removing this line would do it:
https://github.com/sympy/sympy/blob/b176f6a1d9890b42dc361857c887992315e3d5ad/sympy/utilities/runtests.py#L539

**Comment by asmeurer** [comment]
Doesn't that line make it so we don't use any deprecated behavior? I don't think we should remove that.

**Comment by oscarbenjamin** [comment]
It would be better to catch the warnings in the test runner and report a test failure I think

**Comment by asmeurer** [comment]
Doesn't that line effectively do that? Exceptions are reported as failures.

**Comment by oscarbenjamin** [comment]
Exceptions are reported as failures but they aren't caught by the normal pytest machinery for testing warnings. Also we should be testing that the warning is actually emitted as a warning rather than raised:
```
In [10]: raise DeprecationWarning()                                                                                                            
---------------------------------------------------------------------------
DeprecationWarning                        Traceback (most recent call last)
<ipython-input-10-29c37265c864> in <module>
----> 1 raise DeprecationWarning()

DeprecationWarning: 
```

**Comment by asmeurer** [comment]
I'm still a bit confused. Is the line you posted called when pytest is run, or only with the SymPy test runner?

Also I'm distinguishing SymPyDeprecationWarning, which I agree should be tested as such, and DeprecationWarning, which represents other deprecation warnings and shouldn't ever be omitted from SymPy code. Does `filterwarnings(DeprecationWarning)` also apply to SymPyDeprecationWarning? Maybe your issue is with the line above that line, but then we may need to add another filterwarning to cancel the DeprecationWarning effect for SymPyDeprecationWarning (assuming filterwarnings does apply to subclasses).

**Comment by oscarbenjamin** [comment]
The line I linked to is only run when *not* using pytest. Under pytest you can achieve the same with the `-Werror' command line option.

> Does filterwarnings(DeprecationWarning) also apply to SymPyDeprecationWarning? 

Yes because it's a subclass.

If this comes up again (because someone adds a raises test again) I'll fix it properly.

**Comment by oscarbenjamin** [comment]
Running full not-slow tests with pytest I just got:
```
  /Users/enojb/current/sympy/sympy/sympy/core/relational.py:396: SymPyDeprecationWarning: 
  
  Eq(expr) with rhs default to 0 has been deprecated since SymPy 1.5.
  Use Eq(expr, 0) instead. See
  https://github.com/sympy/sympy/issues/16587 for more info.
  
    deprecated_since_version="1.5"

-- Docs: https://docs.pytest.org/en/latest/warnings.html
```
This means that one of the tests is raising a warning. It doesn't show up on Travis I think because it happens in an XFAIL test and the test runner catches the warning as an error treating it as a failure of the tests. That means that the intended failure isn't being tested. So turning warnings into errors has the effect that XFAIL tests don't work properly.

**Comment by asmeurer** [comment]
Maybe we should make `@XFAIL` take an argument that is an expected failing exception (it can default to AssertionError).

XFAIL tests are a bit tricky in general. It's not uncommon for an XFAIL to be written incorrectly and always fail, even when it should start working. It would be good if we could come up with a better way to structure them. The best I can think of is to do regular audits of them.
