### ISSUE TITLE
Ternary pow()

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#5715]
```
According to http://docs.python.org/release/2.5.2/ref/numeric-types.html , __pow__ should define a third, optional argument to work with ternary pow().  We should do that for at least Integer, though it would be cool to do it for arbitrary expressions (this will require Mod from issue 5589 , and also some care to make sure that it still evaluates efficiently when values are substituted in).  Right now, we get:

In [1]: pow(S(2), S(3), S(5))
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)

/Users/aaronmeurer/Documents/python/sympy/sympy/<ipython console> in <module>()

TypeError: __sympifyit_wrapper() takes exactly 2 arguments (3 given)
```

Original issue for #5715: http://code.google.com/p/sympy/issues/detail?id=2616
Original author: https://code.google.com/u/asmeurer@gmail.com/
Referenced issues: #5589
Original owner: https://code.google.com/u/asmeurer@gmail.com/

**Comment by rd13123013** [comment]
This is an old issue and I'm interested in working on it. I'd like to know if there is a reason why it hasn't been fixed yet, any organizational issues that I should be aware of? /cc @asmeurer

**Comment by asmeurer** [comment]
I don't think so. I think it should be easy to implement. Call `pow()` if the arguments are numbers, and create the symbolic power mod n otherwise.

**Comment by leosartaj** [comment]
@rd13123013 @asmeurer This can be fixed by simply allowing 3 arguments for ``__pow__`` in ``Expr`` class. However, it looks as if ``_sympifyit``, allows only one argument. ``_sympifyit`` should be more flexible towards multiple args, I guess. Same is the case with ``call_highest_priority``.
