### ISSUE TITLE
Noncommutative functions do not work

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#5856]
```
In [60]: x = Function('x', commutative=False)

In [61]: y = Function('y', commutative=False)

In [62]: x(t)*y(t)
Out[62]: x(t)⋅y(t)

In [63]: y(t)*x(t)
Out[63]: x(t)⋅y(t)

They should work non-commutatively.
```

Original issue for #5856: http://code.google.com/p/sympy/issues/detail?id=2757
Original author: https://code.google.com/u/asmeurer@gmail.com/
Original owner: https://code.google.com/u/asmeurer@gmail.com/

**Comment by mshvartsman** [comment]
How easy would this be to fix, for someone who's not familiar with the internals of sympy? I have a super kludgy hackaround for my specific setting (creating f(x) as a separate variable), but if fixing it so I can do it properly isn't too hard I can give it a shot.

**Comment by asmeurer** [comment]
This now works in master:

```
>>> x = Function('x', commutative=False)
>>> y = Function('y', commutative=False)
>>> x(t)*y(t)
x(t)*y(t)
>>> y(t)*x(t)
y(t)*x(t)
```

**Comment by homocomputeris** [comment]
@asmeurer I don't know it I shall open a new issue, but I see this in 1.1.1:
```
from sympy import *
var('z')
g = Function('g', commutative=False)
g(z).is_commutative
  True
h = Function('h', commutative=False)
h(z).is_commutative
  True
h(z)*g(z)-h(z)*g(z)
  0
```
Maybe, related to #12979 #12954.
Or maybe I'm missing something in the syntax?

**Comment by asmeurer** [comment]
@homocomputeris are you running this in master? This isn't included in a release yet (I'm working on 1.2 now). 

Also you probably meant `h(z)*g(z) - g(z)*h(z)`. This works correctly in master:

```py
>>> g = Function('g', commutative=False)
>>> h = Function('h', commutative=False)
>>> h(z)*g(z)-g(z)*h(z)
-g(z)*h(z) + h(z)*g(z)
```

**Comment by homocomputeris** [comment]
@asmeurer Sorry.
The issue seemed so old that I thought it had been already included in 1.1.1. In Git version it works as expected.

**Comment by homocomputeris** [comment]
In master branch I've noticed that
```python
var('x')
a = Function('a', commutative=False)
b = Function('b', commutative=True)
a(x)*b(x) - b(x)*a(x)
```
gives 0.
I don't know if by definition commutative by non-commutative should give commutative. This way, though, one can't represent, say, non-commuting operator acting on a commuting operator.

**Comment by asmeurer** [comment]
Yes, that is expected behavior. SymPy only knows about commutative expressions and noncommutative expressions. In a Mul, all commutative terms are pulled out to the end and re-ordered, and the noncommutative terms are kept in order. In other words, commutative=True means "commutes with everything", including commutative=False.
