### ISSUE TITLE
Research ways to extract statistics from the issue tracker

### ISSUE THREAD

**Issue by vperic** [sympy/sympy#5897]
The issue tracker can provide some valuable statistics about the health of the project - it might be interesting to graph the number of open issues, number of issues per category, the average "age" of the (closed/open) issues, who closes the most issues, the number of issue reports by users (as opposed to developers of SymPy) etc. This likely involves interfacing somehow with the Google API.

Original issue for #5897: http://code.google.com/p/sympy/issues/detail?id=2798
Original author: https://code.google.com/u/108713607268198052411/

**Comment by oscarbenjamin** [comment]
This issue seems to be about the web API for google code. Since SymPy now uses Github is this still needed?

**Comment by asmeurer** [comment]
It's also another generic CodeIn task which isn't something we really need.
