### ISSUE TITLE
coverage testing should be part of the bot test

### ISSUE THREAD

**Issue by smichr** [sympy/sympy#5898]
Two things on my wish list for testing;

1) a coverage fingerprint of master would be compared to a given branch's coverage profile to make sure that no line has become uncovered.

2) a report of lines added that are not covered would be reported with the test-bot report.

Someone who likes parsing html (beautiful soup (*) might help with this) might enjoy this as a project. Google CodeIn?

(*) www.crummy.com/software/BeautifulSoup/

Original issue for #5898: http://code.google.com/p/sympy/issues/detail?id=2799
Original author: https://code.google.com/u/117933771799683895267/
Original owner: https://code.google.com/u/117933771799683895267/

**Comment by oscarbenjamin** [comment]
We now have a coverage testing bot (although there are other issues with that). Can this be closed?
