### ISSUE TITLE
integrate(1/(x**2 + a**2)**2, x) is wrong if a is real

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#5907]
```
In [4]: a = Symbol('a', positive=True)

In [5]: integrate(1/(x**2 + a**2)**2, x)
Out[5]: 
                     ⎛x⎞
                 atan⎜─⎟
      x              ⎝a⎠
────────────── + ───────
   4      2  2        3 
2⋅a  + 2⋅a ⋅x      2⋅a  

In [6]: a = Symbol('a', real=True)

In [7]: integrate(1/(x**2 + a**2)**2, x)
Out[7]: 
      x       
──────────────
   4      2  2
2⋅a  + 2⋅a ⋅x 

It's easy to check that the first result is correct and the second is not.
```

Original issue for #5907: http://code.google.com/p/sympy/issues/detail?id=2808
Original author: https://code.google.com/u/asmeurer@gmail.com/

**Comment by Roland-Sands** [comment]
I think this has been fixed

`>>> var('x a b c d')`
`>>> integrate(1/(x**2 + a**2)**2, x)`
`x/(2*a**4 + 2*a**2*x**2) + (-I*log(-I*a + x)/4 + I*log(I*a + x)/4)/a**3`
`>>> y = integrate(1/(x**2 + a**2)**2, x)`
`>>> z = diff(y,x)`
`>>> simplify(z)`
`1/(a**4 + 2*a**2*x**2 + x**4)`
