### ISSUE TITLE
logcombine(log(3) - log(2)) does nothing

### ISSUE THREAD

**Issue by rlamy** [sympy/sympy#5950]
```
logcombine(log(3) - log(2)) should return log(3/2) but it doesn't. This used to work in 0.6.7.
```

Original issue for #5950: http://code.google.com/p/sympy/issues/detail?id=2851
Original author: https://code.google.com/u/101272611947379421629/

**Comment by abaokar-07** [comment]
I want to work on this issue

**Comment by abaokar-07** [comment]
@asmeurer @normalhuman please review this

**Comment by abaokar-07** [comment]
@normalhuman @asmeurer please review the changes made

**Comment by jksuom** [comment]
`logcombine` probably works correctly but its output is determined by the `eval` method of `log`:
```
 >>> log(Rational(3, 2))
-log(2) + log(3)
```

**Comment by smichr** [comment]
If the rationals are not separated, it still may be a good idea to remove perfect powers of the base from the numerator or denominator so `log(2/27, 3) -> log(2/3**3, 3) ->log(2)/log(3) - 3`. `sympy.core.power.integer_log` can help with that process.

**Comment by abaokar-07** [comment]
Ok @smichr I'll look into it, thanks

**Comment by abaokar-07** [comment]
@smichr but if there are no perfect powers, for example Rational(3,2), then what to do?
Can you elaborate what you want to say?
Also, I was debugging the file simplify.py with the input as  logcombine(log(Rational(3,2) , evaluate = False) - log(2)). I found that after returning rv as log(3/2)(as per the code of simplify.py), it didn't proceed further and it automatically returned None and got out of the debugger. The finally returned value remained -log(2) + log(3/2)

**Comment by asmeurer** [comment]
`logcombine` could apply evaluate=False to force the combination. 

Although I personally think automatically splitting rationals is too much (see also https://github.com/sympy/sympy/wiki/Automatic-Simplification).

**Comment by abaokar-07** [comment]
@asmeurer so what do you suggest should be done further?

**Comment by asmeurer** [comment]
I still think we should consider removing the automatic simplification entirely. I opened a new issue for that https://github.com/sympy/sympy/issues/14095.
