### ISSUE TITLE
Standard sets (ZZ, QQ, RR, etc.) for the sets module

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#5952]
We need to add the standard sets in the sets module, such as ZZ, RR, QQ, etc.  

Since this syntax is already used for the polys domains, we need to decide what to do about that.  I'm thinking that we should just make ZZ, QQ, etc. the sets, and allow the syntactic sugar to send those to Poly.  There would also be some function, to_domain() or something, that would convert a standard set into a polys domain (in case you needed it for more than just passing it to Poly).

Original issue for #5952: http://code.google.com/p/sympy/issues/detail?id=2853
Original author: https://code.google.com/u/asmeurer@gmail.com/

**Comment by oscarbenjamin** [comment]
Looks like the sets module already has Reals, Naturals, Naturals0, Integers and Complexes but not Rationals. Are there any other needed but missing sets?

**Comment by oscarbenjamin** [comment]
Closing as Rationals was added to Sets in #10757
