### ISSUE TITLE
Improve code coverage

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#5958]
This is a stand-in issue to increase code coverage.  While you should always be careful about writing tests for no reason other than to increase coverage, it's also good to have good coverage (I personally have found a lot of bugs this way).  I think somewhere around 90% is pretty good, and 80% is healthy.

Note that coverage is tested using the `bin/coverage_report.py` script.  This requires the coverage module (it will tell you if you try to run it and don't have it).  This will run the test suite and create a coverage report from it (it's pretty self-explanatory).  

Note that there are some subtlties with coverage testing.  It's based on lines, so for example, something like

if a or b:

will be considered covered, even if only the a condition is ever hit (it will short-circuit and not hit b).  Also, something like
```
if a: do_something # one line
```
will be considered covered even if a is never true.  The solution to this last one is to never have one-line statements like this, but to instead always write:
```
if a:
    do_something
```
which is cleaner anyway.  See also issue #4906 , issue #5807 , and issue #5898 for some more subtitles.

Note that this is not the same as the doctest coverage from issue 3393 .

I set the difficulty as Medium, because when you increase coverage, you invariably find bugs, which you then have to fix (that's the whole point of doing this anyway).

Original issue for #5958: http://code.google.com/p/sympy/issues/detail?id=2859
Original author: https://code.google.com/u/asmeurer@gmail.com/
Referenced issues: #3393, #4906, #5898, #5807

**Comment by oscarbenjamin** [comment]
I think maybe this issue should be closed and a new coverage issue opened with up to date information on the coverage for each package and referenced easy to fix issues (rather than GCI tasks).

**Comment by asmeurer** [comment]
Agreed.
