### ISSUE TITLE
PackageMaker project file for building OS X pkg installers

### ISSUE THREAD

**Issue by smichr** [sympy/sympy#5996]
This project was started and still has a few issues. It is located at https://github.com/sympy/sympy/pull/748

Original issue for #5996: http://code.google.com/p/sympy/issues/detail?id=2897
Original author: https://code.google.com/u/117933771799683895267/

**Comment by oscarbenjamin** [comment]
Do we still want OSX pkg installers?

These days wheel/pip/conda etc seem to have replaced most platform-specific installer files for Python projects.

**Comment by asmeurer** [comment]
No we do not.
