### ISSUE TITLE
Pretty printing for lerchphi, polylog

### ISSUE THREAD

**Issue by ness01** [sympy/sympy#6013]
The gsoc-3 branch adds various new special functions, some of which might profit from pretty printing. In particular: lerchphi, polylog.

I did not add pretty printing for lerchphi, since printing it as a capital phi seemed like a potential source of confusion to me (e.g. the distribution function of the standard normal random variable is also often written as capital phi).

I did not add printing for polylog since this typically written with one of the variables as subscript (i.e. there is some non-trivial work to do for printing).

None of this should be difficult, once it has been decided what to print how.

 - [x] Add printing for lerchphi
 - [ ] Add printing for polylog

Original issue for #6013: http://code.google.com/p/sympy/issues/detail?id=2914
Original author: https://code.google.com/u/104531927090589914088/

**Comment by ArielKarp** [comment]
Hi, I'm new to open source, may I try to fix this issue?

**Comment by asmeurer** [comment]
Yes, go for it. The lerchphi one should be easy. Just look at how printing of something like `gamma` is implemented.

**Comment by sibasish14** [comment]
Hi I'm new to open source. May I try to solve this?
Where do I find the functions lerchphi and polylog?

**Comment by bhavya17037** [comment]
@asmeurer what greek symbol would lerchphi use?

**Comment by shubhamabhang77** [comment]
Is This solved or not? If not I would like to work on it. Tell me something more about it. I haven't got it that how the printing should look like.

**Comment by asmeurer** [comment]
Looks like lerchphi was fixed by https://github.com/sympy/sympy/pull/15971.

polylog requires a subscript, which is cumbersome for the Unicode pretty printer unless it uses only those characters that have subscript form. So I'm not sure if we should do it. There are other functions that print with subscripts, though. It looks like `latex(polylog)` already does the right thing.

**Comment by shubhamabhang77** [comment]
So basically this issue is closed, right?

**Comment by oscarbenjamin** [comment]
I think printing still needs to be added for polylog:
```
In [35]: pprint(polylog(1 ,2))                                                                                                                                
polylog(1, 2)
```

**Comment by nishant-sg** [comment]
I would like to contribute to this issue, please guide me on what needs to be done.

**Comment by smichr** [comment]
> please guide me on what needs to be done.

see [here](https://github.com/sympy/sympy/issues/6013#issuecomment-343329891)
