### ISSUE TITLE
Canonical form/Simplification for equalities/disequalities/inequalities

### ISSUE THREAD

**Issue by liuq** [sympy/sympy#6141]
I am attempting to use sympy for as the basis for a numerical interval-based constraint programming solver, where I will face constraint expressions like 3_x + 2_y - x*y == 30 + 2 \* x. I think it would be reasonable to have it in a canonical form (eventually after simplification), e.g., with all the variable terms on the left-hand side and the constant on the rhs or something like all the simplified terms on lhs and the equality to zero.

Obviously I added some method to handle those situations in my code, but I think that, apart of my case, a simplification of relations would also be of a general utility.

Original issue for #6141: http://code.google.com/p/sympy/issues/detail?id=3042
Original author: https://code.google.com/u/112048958330635014643/

**Comment by smichr** [comment]
Relationals now have the `.canonical` property that will help to standardize them:
```python
>>> (S(1)>x)
1 > x
>>> (S(1)>x).canonical
x < 1
```
