### ISSUE TITLE
Interval and FiniteSet printing

### ISSUE THREAD

**Issue by mrocklin** [sympy/sympy#6265]
Currently 
str(Interval(0,1)) produces "[0, 1]" 
and 
str(FiniteSet(1,2,3)) produces "{1, 2, 3}"

This violates the str(object) is valid code to create object principle. 

If we change this then code for Interval looks quite ugly. We will end up printing things like "Interval(0, 1, True, False)" to the screen.

Original issue for #6265: http://code.google.com/p/sympy/issues/detail?id=3166
Original author: https://code.google.com/u/109882876523836932473/

**Comment by oscarbenjamin** [comment]
Is this issue still worth fixing? The printing of both FiniteSet and Interval has been unchanged for some time now. It would seem gratuitous to fix at at this point...

**Comment by smichr** [comment]
```python
>>> S(str(Interval(0,1)) )
Interval(0, 1)
>>> type(S(str(FiniteSet(0,1)) ))
<class 'set'>
```

Perhaps `set`, like `dict`, is just not handled yet by `sympify`.

**Comment by oscarbenjamin** [comment]
Sympify will convert a `set` to a `FiniteSet` but doesn't recognise a set literal and passes that on to eval.

**Comment by oscarbenjamin** [comment]
For the original issue this has already been changed for Interval but not FiniteSet:
```julia
In [1]: str(Interval(0, 1))                                                                                                                                   
Out[1]: 'Interval(0, 1)'

In [2]: str(FiniteSet(1))                                                                                                                                     
Out[2]: '{1}'
```
Changing this for FiniteSet does not seem problematic. PR underway...

**Comment by oscarbenjamin** [comment]
I've opened #17845
