### ISSUE TITLE
Generating Functions for sympy.stats

### ISSUE THREAD

**Issue by mrocklin** [sympy/sympy#6323]
```
Is there any benefit to reasoning about generating functions (moment, cumulant, etc...) for random variables? Are there problems that we could solve more easily with this extra formalism? http://en.wikipedia.org/wiki/Cumulant_generating_function http://en.wikipedia.org/wiki/Moment_generating_function
```

Original issue for #6323: http://code.google.com/p/sympy/issues/detail?id=3224
Original author: https://code.google.com/u/109882876523836932473/

**Comment by Smit-create** [comment]
Currently `sympy.stats` support, `moment`, `cmoment`, `smoment`, `factorial_moment`, `characteristic_function`, and `moment_generating_function`
https://github.com/sympy/sympy/blob/3b4c1a6ad7ef692e2e1b1fc5a306c33951da64e7/sympy/stats/rv_interface.py#L19-L22

https://github.com/sympy/sympy/blob/3b4c1a6ad7ef692e2e1b1fc5a306c33951da64e7/sympy/stats/rv_interface.py#L197-L201

https://github.com/sympy/sympy/blob/3b4c1a6ad7ef692e2e1b1fc5a306c33951da64e7/sympy/stats/rv_interface.py#L218-L222

https://github.com/sympy/sympy/blob/3b4c1a6ad7ef692e2e1b1fc5a306c33951da64e7/sympy/stats/rv_interface.py#L314-L319

https://github.com/sympy/sympy/blob/3b4c1a6ad7ef692e2e1b1fc5a306c33951da64e7/sympy/stats/rv.py#L969-L973

https://github.com/sympy/sympy/blob/3b4c1a6ad7ef692e2e1b1fc5a306c33951da64e7/sympy/stats/rv.py#L1002-L1006

IMHO, this can be safely closed. Should we close this @Upabjojr @czgdp1807 ?

**Comment by Upabjojr** [comment]
> Currently `sympy.stats` support, `moment`, `cmoment`, `smoment`, `factorial_moment`, `characteristic_function`, and `moment_generating_function`

Do we have the symbolic class for all of them? It's important to have a class to express unevaluated functions, so we can leave the unevaluated `Moment(X, 1)` in case functions like `moment(X, 1)` are unable to evaluate.

**Comment by Smit-create** [comment]
For unevaluated results, we can use `evaluate=False`:
```py
In [1]: from sympy.stats import *

In [2]: X = Normal('X', 1, 3)

In [3]: moment(X, 4, evaluate=False)
Out[3]:
∞
⌠
⎮                 2

⎮         -(X - 1)
⎮         ──────────
⎮      4      18
⎮  √2⋅X ⋅ℯ
⎮  ───────────────── dX
⎮         6⋅√π
⌡
-∞

In [4]: moment(X, 4)
Out[4]: 298

In [5]: cmoment(X, 3, evaluate=False)
Out[5]:
∞
⌠
⎮                                 3
⎮     ⎛    ∞                     ⎞
⎮     ⎜    ⌠                     ⎟
⎮     ⎜    ⎮                2    ⎟
⎮     ⎜    ⎮        -(X - 1)     ⎟           2
⎮     ⎜    ⎮        ──────────   ⎟   -(X - 1)
⎮     ⎜    ⎮            18       ⎟   ──────────
⎮     ⎜    ⎮  √2⋅X⋅ℯ             ⎟       18
⎮  √2⋅⎜X - ⎮  ──────────────── dX⎟ ⋅ℯ

⎮     ⎜    ⎮        6⋅√π         ⎟
⎮     ⎜    ⌡                     ⎟
⎮     ⎝    -∞                    ⎠
⎮  ──────────────────────────────────────────── dX
⎮                      6⋅√π
⌡
-∞

In [6]: cmoment(X, 3)
Out[6]: 0

In [7]: factorial_moment(X, 2)
Out[7]: 9

In [8]: factorial_moment(X, 2, evaluate=False)
Out[8]:

∞
⌠
⎮                        2
⎮                -(X - 1)
⎮                ──────────
⎮                    18
⎮  √2⋅X⋅(X - 1)⋅ℯ
⎮  ──────────────────────── dX
⎮            6⋅√π
⌡
-∞


```

**Comment by oscarbenjamin** [comment]
Is there a `Moment` class rather than `Integral`?

**Comment by Upabjojr** [comment]
> For unevaluated results, we can use `evaluate=False`

That is returning the unevaluated integral, that is not the unevaluated `Moment`. We have already classes `Probability`, `Expectation`, `Variance`, `Covariance` for unevaluated expressions... but not for the other ones.

**Comment by Smit-create** [comment]
Sure I get it, It Will be nice additions.
