### ISSUE TITLE
Wrong resule in classify_ode when using a Symbol instead of a Function

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#6335]
```
This is related to issue 3539 and issue 4711 .

In [42]: y = Function('y')

In [43]: classify_ode(y(x).diff(x, x) + 3*y(x).diff(x) + 2*y(x) - exp(-x)*0, y(x))
Out[43]: (nth_linear_constant_coeff_homogeneous,)

In [44]: y = Symbol('y')

In [45]: classify_ode(y(x).diff(x, x) + 3*y(x).diff(x) + 2*y(x) - exp(-x)*0, y(x))
Out[45]: (nth_linear_constant_coeff_variation_of_parameters, nth_linear_constant_coeff_variation_of_parameters_Integral)

The first result is correct.  It's the same if you remove the "*0".
```

Original issue for #6335: http://code.google.com/p/sympy/issues/detail?id=3236
Original author: https://code.google.com/u/asmeurer@gmail.com/
Referenced issues: #3539, #4711

**Comment by cbm755** [comment]
I cannot reproduce with 1.2.  I could add a test as-is, but I'd like to remove magic `y(x)` making Function from Symbols (in #9064) and then the test wouldn't be valid anymore.

Ok to close this?

**Comment by asmeurer** [comment]
I think there used to be a lot more bugs with symbols that automatically converted to functions. I'm OK to close.
