### ISSUE TITLE
combsimp and binomial coefficients

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#6341]
```
In [161]: summation( binomial(n,k)**2, (k,0,oo))
Out[161]: 
Γ(2⋅n + 1)
──────────
        2 
Γ(n + 1)  

In [162]: combsimp(summation( binomial(n,k)**2, (k,0,oo)))
Out[162]: 
 2⋅n + 1           
2       ⋅Γ(n + 1/2)
───────────────────
      ___          
  2⋅╲╱ π ⋅Γ(n + 1) 

First off, I have n defined as an integer, so IMHO gamma should reduce to factorial in that case.

Second, this is just binomial(2*n, n).

Third, why doesn't this work:

In [165]: summation( binomial(n,k)**2, (k,0,oo)).rewrite(factorial)
Out[165]: 
Γ(2⋅n + 1)
──────────
        2 
Γ(n + 1)
```

Original issue for #6341: http://code.google.com/p/sympy/issues/detail?id=3242
Original author: https://code.google.com/u/asmeurer@gmail.com/

**Comment by mohit3011** [comment]
I would like to resolve this issue if it's still open

**Comment by mohit3011** [comment]
Just guide me how to start because I'm new here.

**Comment by jksuom** [comment]
You should start by studying the code in combsimp.py. The issue #9785 contains some suggestions on how to continue.

**Comment by mohit3011** [comment]
As you have mentioned in #9785 , combsimp.py contains both combinatorics and gamma functions and this is creating a problem in understanding combsimp.py

**Comment by jksuom** [comment]
There could probably be a separate function `gammasimp`. It could be added to the end of the file, and suitable parts of `combsimp` could be copied into it (leaving `combsimp` as it is for the time being). Those tests in `test_combsimp.py` that are concerned with `gamma` could be used to verify that the new `gammasimp` does what is expected. The aim is to make combsimp.py more understandable.

**Comment by mohit3011** [comment]
I have edited combsimp.py as well as the test_combsimp.py but I am getting some trouble in testing.
I have followed the following steps in the python shell
`import sympy`
`sympy.test("sympy/simplify/tests/test_combsimp.py")`

But I'm getting error

sympy/simplify/tests/test_combsimp.py[0] Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "sympy/utilities/runtests.py", line 526, in _test
    slow=slow, enhance_asserts=enhance_asserts))
  File "sympy/utilities/runtests.py", line 1002, in test
    self.test_file(f, sort, timeout, slow, enhance_asserts)
  File "sympy/utilities/runtests.py", line 1075, in test_file
    reporter.test_exception(sys.exc_info())
  File "sympy/utilities/runtests.py", line 2206, in test_exception
    self._exceptions.append((self._active_file, self._active_f, exc_info))
AttributeError: 'PyTestReporter' object has no attribute '_active_file'
False

**Comment by mohit3011** [comment]
[Fixes#6341.zip](https://github.com/sympy/sympy/files/704136/Fixes.6341.zip)
In this zip file I have edited combsimp.py and test_combsimp.py

**Comment by jksuom** [comment]
> AttributeError: 'PyTestReporter' object has no attribute '_active_file'

This is what happens when Python cannot import a file because of syntax errors. You can probably find the error by running `python`  and then attempting `from sympy.simplify.combsimp import *` (or `from sympy.simplify.tests.test_combsimp import *`).

**Comment by asmeurer** [comment]
@mohit3011 please submit your changes as a pull request, not a zip file. There is a guide [here](https://github.com/sympy/sympy/wiki/Development-workflow). Feel free to ask here or on [gitter](https://gitter.im/sympy/sympy) if you have any questions.

**Comment by mohit3011** [comment]
I am trying to test the new gammasimp function in combsimp.py . I have written the tests for it but somehow they are not getting tested as I am getting no error while testing locally. But, when I pushed the code for merging Travis found some error. Please help

**Comment by mohit3011** [comment]
`import sympy
sympy.test("sympy/simplify/tests/test_combsimp.py")`

I am testing in this manner . Is this correct ?

**Comment by mohit3011** [comment]
![screen shot 2017-01-25 at 4 52 56 pm](https://cloud.githubusercontent.com/assets/19210197/22288856/c8214532-e31e-11e6-8fca-0786a297f70b.png)

**Comment by jksuom** [comment]
That is one way of testing. bin/test can also be used to run individual test files by giving (a part of) the name as a parameter: `bin/test combsimp`.
