### ISSUE TITLE
substitute warnings for print statements

### ISSUE THREAD

**Issue by Krastanov** [sympy/sympy#6388]
There are some places in the code where print statements are used instead of warnings (eg in solve). This should probably be corrected.

Original issue for #6388: http://code.google.com/p/sympy/issues/detail?id=3289
Original author: https://code.google.com/u/100157245271348669141/

**Comment by ajjayymahato** [comment]
I am taking up this issue.

**Comment by Naba7** [comment]
I am working on this

**Comment by Naba7** [comment]
What is to be done? Shall I remove the warnings?

**Comment by oscarbenjamin** [comment]
I think this should have been closed when #1771 was merged.
