### ISSUE TITLE
Complex Sets

### ISSUE THREAD

**Issue by mrocklin** [sympy/sympy#6405]
```
We need a set to represent the complex numbers and regions in the complex plane. We need the equivalent of Interval for C.
```
Original issue for #6405: http://code.google.com/p/sympy/issues/detail?id=3306
Original author: https://code.google.com/u/109882876523836932473/

**Comment by darkcoderrises** [comment]
Hi, i would like to work on this.Can someone guide me ?

**Comment by skirpichev** [comment]
@hargup are you ready to mentor? ;)

**Comment by hargup** [comment]
> @hargup are you ready to mentor? ;)

yes :),

> Hi, i would like to work on this.Can someone guide me ?

cool, go through the implementation of `Real` class in `sympy.sets.fancysets`. Read [this](https://github.com/sympy/sympy/issues/6405#issuecomment-52150880) and following comments . This should give you a clear idea of what needs to be done. If not ask questions, even if you think your question is very silly. Then make changes and send a pull request. Also go through the [Developement workflow](https://github.com/sympy/sympy/wiki/Development-workflow) if you haven't done that already.

**Comment by darkcoderrises** [comment]
what should be the output of 
ImageSet(lambda(x,x),S.complex)

**Comment by hargup** [comment]
> what should be the output of 
ImageSet(lambda(x,x),S.complex)

It should be `S.Complex`

> Actually i am not getting how do i send back two sets for the x coordinate and the y coordinate

What is your use case? If by "send back" you mean returning two sets then you can return a tuple. `(set1, set2)`

**Comment by darkcoderrises** [comment]
I thought that and tried also, then the output of ImageSet(lambda(x,x),S.complex) comes out , 
 {x | x ∊ ((-∞, ∞), (-∞, ∞))}
Do i have to just create a class or update it in other places also?

**Comment by hargup** [comment]
> Then the output of ImageSet(lambda(x,x),S.complex) comes out , 
{x | x ∊ ((-∞, ∞), (-∞, ∞))}

Save the output to some variable, say `var` and do `type(var)`. If the output is something like `sympy.sets.fancysets.Complex` then you are doing it right. You see `{x | x ∊ ((-∞, ∞), (-∞, ∞))}` as output because you might not have written a printer for `Complex` class and it is using the printer of `ImageSet`. Write printing functions for `Complex` in `sympy.printing`. Also send a PR with your work. Add a `[WIP]` (Work in Progress) tag in the PR title if you think work isn't yet completed.

**Comment by darkcoderrises** [comment]
how to save the output?

**Comment by hargup** [comment]
> how to save the output?

assign it to some variable `var = ImageSet(Lambda(x, x), S.Complex)`, or if you are using the IPython console then `_` stores the output of the last run command.

**Comment by darkcoderrises** [comment]
if i do var =  ImageSet(Lambda(x, x), S.Reals) then type(var) it comes imageset not reals

**Comment by hargup** [comment]
> if i do var = ImageSet(Lambda(x, x), S.Reals) then type(var) it comes imageset not reals

oops, I'm sorry I should have mentioned earlier. You should use `imageset` instead of `ImageSet`. `ImageSet` always returns an unevaluated instance. See https://github.com/sympy/sympy/issues/7655

**Comment by darkcoderrises** [comment]
but imageset do not support tuple or list

**Comment by hargup** [comment]
> but imageset do not support tuple or list

Where do you need a tuple or list? Can you give me an example of code you are trying to run.

**Comment by darkcoderrises** [comment]
class Complex(with_metaclass(Singleton, Interval)):

	def __new__(cls):
		return [Interval.__new__(cls, -S.Infinity, S.Infinity),Interval.__new__(cls, -S.Infinity, S.Infinity)]

type(imageset(Labmda(x,x),S.Complex))

**Comment by hargup** [comment]
An ImageSet can have products of an interval as input set. See https://github.com/sympy/sympy/issues/6405#issuecomment-52150880

**Comment by darkcoderrises** [comment]
wait, what do i have to do?

**Comment by hargup** [comment]
> wait, what do i have to do?

I think I made my self sufficiently clear in the comments above. Try reading them again and post your interpretation here. If you still don't get it then it is likely that I'm suffering from [the curse of knowledge](https://hbr.org/2006/12/the-curse-of-knowledge). I'll then try some other method of explaining it to you.

**Comment by darkcoderrises** [comment]
My interpretation was that I have to create a similar class definition of S.Complex as S.Reals. Then i was checking it using ImageSet. But then by "An ImageSet can have products of an interval as input set. See #6405 (comment)" i thought that i can also create a class definition using imageset not like S.Reals which uses Interval

**Comment by hargup** [comment]
@darkcoderrises You can do something like:
``` python
class Complex(with_metaclass(Singleton, Interval)):

    def __new__(cls):
        x = Symbol('x')
        y = Symbol('y')
        return ImageSet(Lambda((x, y), x + I*y), S.Reals*S.Reals)
```

**Comment by asmeurer** [comment]
@hargup if you do that, then `Complex` becomes nothing more than a shortcut to create an ImageSet. You would never have an instance of `Complex`. I would look for some way use an ImageSet internally for calculations, but have a wrapper that can print nicely (like ℂ).

**Comment by darkcoderrises** [comment]
I gave the pull request for the class Complex declaration.
please check
https://github.com/sympy/sympy/pull/8870

**Comment by darkcoderrises** [comment]
Sorry i gave that request with running the test. But apparently the test is giving DO NOT COMMIT for this also only
 
+class Complex(with_metaclass(Singleton, Interval)):
+
+    def __new__(cls):
+        from sympy.core import Symbol
+        from sympy.core.numbers import ImaginaryUnit
+        I = ImaginaryUnit()
+        x = Symbol('x')
+        y = Symbol('y')
+        return ImageSet(Lambda((x,y), x + I*y), S.Reals*S.Reals)
+

**Comment by luviiit** [comment]
what would be the problem in defining the Complex set definition the following way?:
```
class Complex(with_metaclass(Singleton, ImageSet)):

    def __new__(cls):
        x, y = symbols('x y')
        I = ImaginaryUnit()
        return ImageSet.__new__(cls, Lambda((x, y), x + I*y), S.Reals*S.Reals)

```

**Comment by darkcoderrises** [comment]
I think that we will also have to include symbol and imaginary unit, wont we?

**Comment by luviiit** [comment]
@darkcoderrises, i did a global import of both

**Comment by darkcoderrises** [comment]
@luviiit Sorry i am new here,is it in with_metaclass(Singleton,ImageSet)

**Comment by luviiit** [comment]
@darkcoderrises, global import means when you import at the top of the file and so it is accessible everywhere in the file

**Comment by darkcoderrises** [comment]
oh sorry then, it was not shown in the code snippet so i was confused

**Comment by luviiit** [comment]
@hargup, @asmeurer:
please take a look at https://github.com/sympy/sympy/issues/6405#issuecomment-71100499.

**Comment by darkcoderrises** [comment]
I gave the pull request for the class Complex declaration.
please check
https://github.com/sympy/sympy/pull/8893

**Comment by aktech** [comment]
Added here #9463 , closing this.
