### ISSUE TITLE
use unicode names instead of hex encoding

### ISSUE THREAD

**Issue by Krastanov** [sympy/sympy#6430]
```
The code will be much more readable if we use unicode names in literal. It is all done on compile time:

>>> u"\N{NUMERO SIGN}"
u'\u2116'
```
Original issue for #6430: http://code.google.com/p/sympy/issues/detail?id=3331
Original author: https://code.google.com/u/100157245271348669141/

**Comment by skirpichev** [comment]
@asmeurer, this should be closed?

**Comment by asmeurer** [comment]
Yes, it looks like https://github.com/sympy/sympy/pull/8547 fixed this.
