### ISSUE TITLE
WignerD with angles all 0 should return delta function

### ISSUE THREAD

**Issue by flacjacket** [sympy/sympy#6521]
When all the angles passed to the Wigner-D function are zero, it would be nice if it returned a KroneckerDelta, rather than a Wigner small-d function. Currently it gives:

```
In [1]: from sympy.physics.quantum.spin import WignerD

In [2]: j, m, mp = symbols('j m mp')

In [3]: WignerD(j, m, mp, 0, 0, 0)
Out[3]: 
  j     
d    (0)
 m,mp   
```

It's easy to do a `if args[3:] == (0, 0, 0):` in the `__new__` function and return a KroneckerDelta:

```
In [4]: WignerD(j, m, mp, 0, 0, 0)
Out[4]: 
δ
 m,mp
```

But just doing this will mess up some other stuff with the rewrite machinery:

```
In [5]: from sympy.physics.quantum.spin import JzKet

In [6]: JzKet(j, m).rewrite('Jz')
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-19-6ad2c34dbd31> in <module>()
----> 1 JzKet(j, m).rewrite('Jz')

/home/sean/sympy/sympy/core/basic.pyc in rewrite(self, *args, **hints)
   1386 
   1387             if not pattern:
-> 1388                 return self._eval_rewrite(None, rule, **hints)
   1389             else:
   1390                 if iterable(pattern[0]):

/home/sean/sympy/sympy/physics/quantum/qexpr.pyc in _eval_rewrite(self, pattern, rule, **hints)
    330         if pattern is None or isinstance(self, pattern):
    331             if hasattr(self, rule):
--> 332                 rewritten = getattr(self, rule)(*args, **hints)
    333 
    334                 if rewritten is not None:

/home/sean/sympy/sympy/physics/quantum/spin.py in _eval_rewrite_as_Jz(self, *args, **options)
    903         if isinstance(self, Bra):
    904             return self._rewrite_basis(Jz, JzBra, **options)
--> 905         return self._rewrite_basis(Jz, JzKet, **options)
    906 
    907     def _rewrite_basis(self, basis, evect, **options):

/home/sean/sympy/sympy/physics/quantum/spin.py in _rewrite_basis(self, basis, evect, **options)
    943             else:
    944                 state = evect(j, mi, *args)
--> 945                 lt = Rotation.D(j, mi, self.m, *angles)
    946                 return Sum(lt * state, (mi,-j,j))
    947 

TypeError: D() takes exactly 7 arguments (4 given)
```

This really comes down to addressing the 'TODO: better way to get angles of rotation' in _rewrite_basis and 'TODO: Use KroneckerDelta if all Euler angles == 0' in _represent_base.

A good test for this is:

```
qapply(Jz * JzKet(1, m)) == -hbar * KroneckerDelta(-1, m) * JzKet(1, -1) + hbar * KroneckerDelta(1, m) * JzKet(1, 1)
```

while not causing any of the rewrite/represent tests to fail.

**Comment by VBhat97** [comment]
Hello ! Is this issue still not fixed? I would like to work on fixing this issue. Thanks!

**Comment by oscarbenjamin** [comment]
We still have
```
>>> WignerD(j, m, mp, 0, 0, 0)
  j     
d    (0)
 m,mp 
```
so I guess it's not fixed.

**Comment by VBhat97** [comment]
Hey @oscarbenjamin !

Thanks for the information.

As mention by @anuraghota above, I am planning to add a case in _eval_wignerd in spin.py, that if alpha, beta, gamma are 0, return KroneckerDelta().

However, I have 2 questions :

1. What should be the 2 arguments that needs to be passed in KroneckerDelta function while returning.
2. Is there any test case I have to write for the same? or just run the ones already written for checking whether it passes or not.

Thanks!

**Comment by oscarbenjamin** [comment]
According to the OP the arguments would be `m` and `mp`. Yes new test cases will be needed if there aren't already tests for this case.

**Comment by VBhat97** [comment]
Hey @oscarbenjamin !

So, I added the return KroneckerDelta part in _eval_wignard and ran the preivous test cases and they all pass.

For adding new test cases, I dont see any specific test cases for the WignerD function in test_spin.py. Should I add a set of test cases for WignerD in a new function? If not, I am kind of confused about where to add them.

Also, can I borrow some of the test cases of KroneckerDelta from test_tensor_functions.py? 

Thanks for the help!

**Comment by VBhat97** [comment]
Hey @oscarbenjamin!

I added the required conditional part and also wrote modified tests from the test_KroneckerDelta function.
Would you be able to take a look and merge if possible? or suggest what additional things I have to do.?

Thanks!
