### ISSUE TITLE
polylog.evalf doesn't work

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#6603]
```
In [8]: integrate(ln(1 - y)/y, (y, 0, 1)).evalf()
Out[8]: 
        ⎛    2⋅ⅈ⋅π⎞
-polylog⎝2, ℯ     ⎠

According to http://www.wolframalpha.com/input/?i=integrate%28-log%281+-+y%29%2Fy%2C+%28y%2C+0%2C+1%29%29 it should be 1.64493.
```

Original issue for #6603: http://code.google.com/p/sympy/issues/detail?id=3504
Original author: https://code.google.com/u/asmeurer@gmail.com/

**Comment by normalhuman** [comment]
This was corrected by #13965, which also added a [test](https://github.com/sympy/sympy/blob/master/sympy/integrals/tests/test_integrals.py#L290) with exactly this integral (which now returns `-pi**2/6`).
