### ISSUE TITLE
gruntz( exp(2*Ei(-z))/z**2, z, 0)

### ISSUE THREAD

**Issue by raoulb** [sympy/sympy#6682]
```
The following limit containing the expüonential integral fails:

gruntz( exp(2*Ei(-z))/z**2, z, 0)

The correct result is exp(2*EulerGamma).
```

Original issue for #6682: http://code.google.com/p/sympy/issues/detail?id=3583
Original author: https://code.google.com/u/107490137238222069432/
Original owner: https://code.google.com/u/113518207426301808764/

**Comment by anutosh491** [comment]
The issue here isn't fully solved , `gruntz` is working here but limit isn't due to leading term methods of `Ei` and `Chi` function ! 
```
>>> limit( exp(2*Ei(-z))/z**2, z, 0)
oo
>>> gruntz( exp(2*Ei(-z))/z**2, z, 0)
exp(2*EulerGamma)
```
