### ISSUE TITLE
Series of li(z)

### ISSUE THREAD

**Issue by raoulb** [sympy/sympy#6683]
```
Series expansion for li(z) failes:

>>> series(li(z), z)
nan
```

Original issue for #6683: http://code.google.com/p/sympy/issues/detail?id=3584
Original author: https://code.google.com/u/107490137238222069432/

**Comment by leosartaj** [comment]
I am trying to solve this. One way is to write ```li(x)``` as ```Ei(ln(x))``` and then compute the series. But currently sympy is unable to evaluate expansion of ```Ei(ln(x))```.  Am stuck here. Is there another way?

**Comment by asmeurer** [comment]
I would dig into the code to see why it returns nan. It might be caused by a bug.

**Comment by asmeurer** [comment]
Perhaps this is not even well-defined http://www.wolframalpha.com/input/?i=series+of+li%28z%29+at+z+%3D+0

**Comment by leosartaj** [comment]
I referred to http://en.wikipedia.org/wiki/Logarithmic_integral_function, it has definition of series expansion of ```li(x)```. Also it is defined about points other than 0, http://www.wolframalpha.com/input/?i=series+of+li%28z%29

**Comment by 0sidharth** [comment]
This now returns - 
```py
In [8]: series(li(z), z)
Out[8]: 
   5         4         3         2                              
log (z)   log (z)   log (z)   log (z)                           
─────── + ─────── + ─────── + ─────── + log(z) + log(log(z)) + γ
  600        96        18        4                              

```
