### ISSUE TITLE
PyPy tests use too much memory

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#6767]
```
I don't know if this is really a PyPy bug, but the PyPy tests use way too much memory.  Just right now, I am running PyPy tests in sympy-bot, and they are only to the quantum tests, and it already is using 2.86 GB of virtual memory.  On my cheap linux laptop that has very little memory, it doesn't even make it to the core tests before it runs out of memory and dies (see http://reviews.sympy.org/report/agZzeW1weTNyDAsSBFRhc2sYp9hqDA ).
```

Original issue for #6767: http://code.google.com/p/sympy/issues/detail?id=3668
Original author: https://code.google.com/u/asmeurer@gmail.com/

**Comment by davidlowryduda** [comment]
PyPy's behavior is much better now than it was 6 years ago, and I don't think this is an issue any more. I suggest that it be closed.

**Comment by asmeurer** [comment]
I don't know how much memory it uses but it doesn't crash Travis, so that's good enough for me. We've also fixed several memory issues in SymPy itself since this issue was opened (like removing the unbounded cache).
