### ISSUE TITLE
probability() should handle union and intersection of conditions as well as point conditions

### ISSUE THREAD

**Issue by aaaagrawal** [sympy/sympy#6810]
```
Currently,

>>> from sympy.stats import Die, P, Normal
>>> X = Die('X', 6)
>>> Y = Normal('Y', 0, 1)
>>> P(X = 2)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: probability() takes at least 1 argument (0 given)
>>> P(Y = 0)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: probability() takes at least 1 argument (0 given)
>>> P(X > 2 or X < 3)
2/3
>>> P(X > 3 and X > 2)
2/3


Desired :

>>> from sympy.stats import Die, P, Normal
>>> X = Die('X', 6)
>>> Y = Normal('Y', 0, 1)
>>> P(X = 2)
1/6
>>> P(Y = 0)
0
>>> P(X > 2 or X < 3)
1
>>> P(X > 3 and X > 2)
1/2
```

Original issue for #6810: http://code.google.com/p/sympy/issues/detail?id=3711
Original author: https://code.google.com/u/110118527174861881051/

**Comment by eronlloyd** [comment]
I'm beginning to experiment with sympy.stats, and wonder if this and #6815 are what prevents the proper calculation of probability calls such as P(0.5 < X < 0.75) in SymPy? Conditional calls such as

`P(X > 0.5, X < 0.75)`

yield a different result and are not the expected way an area is calculated given P(a < X < b), where a and b are ordinates on a normal distribution.

I was going to file a new issue, but did some digging and found this. Any updates? I believe sympy.stats is shaping up to be a great learning tool, but more functionality to work with areas under a normal curve would be a big help.

**Comment by Smit-create** [comment]
Currently on master:
```
>>> from sympy import Eq, Or, And
>>> from sympy.stats import *
>>> X = Die('X', 6)
>>> Y = Normal('Y', 0, 1)
>>> P(Eq(X, 2))
1/6
>>> P(Eq(Y, 0))
0
>>> P(Or(X > 2, X < 3))
1
>>> P(And(X > 3, X > 2))
1/2

```
This works correctly as expected. 
Can this be closed with a test case? @oscarbenjamin @czgdp1807
