### ISSUE TITLE
add tests for sho1d.py

### ISSUE THREAD

**Issue by Krastanov** [sympy/sympy#6847]
```
This pull request fixed some typos that should have never happened. Given that the number of PRs is very big at the moment, I am merging it, because asking for tests may delay it indefinitely. https://github.com/sympy/sympy/pull/2004
```

Original issue for #6847: http://code.google.com/p/sympy/issues/detail?id=3748
Original author: https://code.google.com/u/100157245271348669141/

**Comment by guenp** [comment]
Closing this in favor of a larger effort to assess tech debt on this library by me and @hodgestar.
