### ISSUE TITLE
combsimp(RisingFactorial(-10,n)) produces wrong result

### ISSUE THREAD

**Issue by katjasophie** [sympy/sympy#6878]
```
In [3]: combsimp(RisingFactorial(-10,n))
Out[3]: 0

This is not correct for n < 11.
```

Original issue for #6878: http://code.google.com/p/sympy/issues/detail?id=3779
Original author: https://code.google.com/u/117981593070261792282/

**Comment by vdwees** [comment]
I tried this:
`>>> combsimp(RisingFactorial(-10, 5))`
`-30240`

This is as expected.

Presumably, this is what the OP did:
`>>> from sympy.abc import n`
`>>> combsimp(RisingFactorial(-10, n))`
`0`

This is not as expected.

Should it instead behave as follows?
`>>> from sympy.abc import n`
`>>> combsimp(RisingFactorial(-10, n))`
`RisingFactorial(-10, n)`

**Comment by smichr** [comment]
`combsimp` starts with a `rewrite(gamma)` which, for `RisingFactorial(x, k)` is `gamma(x + k)/gamma(x)`. With `x = -10` this ends up being `gamma(-10 + k)/zoo -> 0`.

**Comment by namannimmo10** [comment]
Yes, +1 to that. 
https://github.com/sympy/sympy/blob/3c34a09e98aaeffe18ac5352e49e9f258384a375/sympy/simplify/combsimp.py#L49
This line indeed returns 0.

**Comment by smichr** [comment]
The `rf` rewrite has to give a `Piecewise` result that considers the sign of `k` and the sign of `x`.
