### ISSUE TITLE
plot does not use the given range

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#6893]
With plot(sqrt(100 - x**2) + 20 - x, (x, -20, 20)), the plot is shown from -10 to 10.  See attached file.

Original issue for #6893: http://code.google.com/p/sympy/issues/detail?id=3794
Original author: https://code.google.com/u/asmeurer@gmail.com/

**Comment by tjstienstra** [comment]
Closing because this issue seems to be fixed. The `xlim` is automatically updated to where the specified range gives real values.
```
from sympy import plot, sqrt
from sympy.abc import x
plot(sqrt(225 - x**2) + 20 - x, (x, -20, 20))
```
Updates the `xlim` to `(-15, 15)`. Note that it is not updated to `(-20, 20)` because `[-20, -15)` and `(15, 20]` is complex.
