### ISSUE TITLE
IdentityFunction doesn't rebuild from args

### ISSUE THREAD

**Issue by smichr** [sympy/sympy#6899]
```
>>> Lambda(x, x)
Lambda(_x, _x)
>>> _.func(*_.args)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: __new__() takes exactly 1 argument (3 given)
>>> Lambda(x, x).func
<class 'sympy.functions.elementary.miscellaneous.IdentityFunction'>
```

Original issue for #6899: http://code.google.com/p/sympy/issues/detail?id=3800
Original author: https://code.google.com/u/117933771799683895267/

**Comment by smichr** [comment]
This works now. A test for this can be added (or found to have been added) and the issue closed.

**Comment by praneethratna** [comment]
Hi , i would like to work on this issue , so the test should assert if  _.func(*_.args) is equal to Lambda(x,x).fun is that it ?

**Comment by praneethratna** [comment]
@smichr I'm unable to build Identity function from args as it is saying an positional argument 'name' is missing , so how to fix that?

**Comment by smichr** [comment]
```python
>>> eq=Lambda(x, x)
>>> assert eq.func(*eq.args)==eq
```
