### ISSUE TITLE
solve(boolean) should raise an exception

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#6924]
```
solve(False) currently gives False. I think it should raise an exception instead. The reason is that new users might type something like solve(x - 1 == 0) and get False, and then incorrectly think that solve cannot solve the equation. 

Plus, solve(False) doesn't even make sense anyway.
```

Original issue for #6924: http://code.google.com/p/sympy/issues/detail?id=3825
Original author: https://code.google.com/u/asmeurer@gmail.com/

**Comment by abaokar-07** [comment]
@asmeurer @jksuom This problem is still present, shall I open a pull request for this?

**Comment by asmeurer** [comment]
solve(boolean) ought to work at least for systems or solve(False). Think of it in terms of `solve(Eq(0, 0))` or `solve(Eq(0, 1))`.  `solve(True)` can't give a useful solution, though solveset(True) could give UniversalSet.

See https://github.com/sympy/sympy/issues/14632, which I'm closing this in favor of.
