### ISSUE TITLE
Extra output from GA.reciprocal_frame

### ISSUE THREAD

**Issue by moble** [sympy/sympy#6987]
I'm not really sure that this really rises to the level of a bug, but it's unexpected behavior, and is distracting and confusing.

The GA.reciprocal_frame has two print statements that appear to be debug statements that got left in.  The function returns a list of vectors, but also results in this unexpected printing, which is not useful.  The following two lines print out the square of the pseudovector and its simplification.
```
    print Esq
    print sympy.simplify(Esq)
```

Original issue for #6987: http://code.google.com/p/sympy/issues/detail?id=3888
Original author: https://code.google.com/u/105258038539638189385/

**Comment by smichr** [comment]
galgebra is at [its own location](https://github.com/brombo/galgebra) now.
