### ISSUE TITLE
Use IPython display system automatically

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#7003]
```
Is there a good reason to not just use the IPython display system to make SymPy objects always print with mathjax in the notebook? pandas defaults to a custom display in IPython. We could make init_printing() overwrite the default.
```

Original issue for #7003: http://code.google.com/p/sympy/issues/detail?id=3904
Original author: https://code.google.com/u/asmeurer@gmail.com/

**Comment by moorepants** [comment]
@certik and I just talked about this issue today and agreed again that SymPy objects should print as rendered LaTeX by default in the notebook and probably the qt console. `init_printing` should only be needed for printing needs other than the rendered LaTeX.

**Comment by certik** [comment]
Agreed.

**Comment by asmeurer** [comment]
Should be an easy change. Let's do it.

**Comment by moorepants** [comment]
Ok, I'm happy to look into after my talk or during the sprint.

**Comment by asmeurer** [comment]
The qtconsole is more problematic. To enable printing in the qtconsole, you have to enable PNG output. But you don't want to do this in the notebook, because of the way the notebook works, every SymPy equation will save a PNG, leading to a huge ipynb file size. So one thing `init_printing()` does is it dynamically enables PNG only when it detects the qtconsole. The good news is that not many people use the qtconsole, compared to the notebook. 

For the notebook, yes, let's just define the appropriate method on Basic for Jupyter to print LaTeX. `init_printing()` will still be needed to render builtin types like lists, tuples, and dictionaries. This means functions like `solve` that return lists will not pretty print, unless you call `init_printing()`. We could make this work if we effectively call init_printing() at SymPy import time. But there could be some side effects to doing that, since it does instance checks on lists to see if they should be pretty printed. It also considers built in numeric types as something that should be pretty printed, which we probably don't want to enable automatically. 

There's also the question of the terminal IPython. Should it automatically use the pretty printing, without using init_printing/init_session/isympy?
