### ISSUE TITLE
preview viewer='file' without a specified filename is deprecated

### ISSUE THREAD

**Issue by thisch** [sympy/sympy#7018]
The viewer='file' option to the preview function without a file name will be deprecated starting with sympy 0.7.3. You need to specify a filename with filename='name' in addition to viewer='file. In SymPy 0.7.2 preview()  returned a file handle when viewer='file' was specified. This is not good practice and therefore this feature was deprecated in the course of the large cleanup in PR 1779.

Original issue for #7018: http://code.google.com/p/sympy/issues/detail?id=3919
Original author: https://code.google.com/u/t.hisch@gmail.com/

**Comment by oscarbenjamin** [comment]
Closed by #18392

**Comment by MuellerSeb** [comment]
@oscarbenjamin : but the whole `viewer=="file"` option was removed, that is disappointing!
