### ISSUE TITLE
primepi is slow and takes too much memory

### ISSUE THREAD

**Issue by danaj** [sympy/sympy#7021]
primepi (prime_count) is fine for small values, but middling size numbers like 10 million are quite slow, and larger values like 10e9 are only possible on machines with more than 32GB.

Note that the current system generates all the primes up to the limit, then counts them, so using timeit is problematic as it ignores the large cost to run it the first time and only reports the fast lookups.

There are some relatively straightforward changes that should be able to speed this up 10-30x, and help a little with the memory use.

Once done with that, there are a some other possibilities if we want more speed.  (1) segmented sieve, (2) tables to speed up counts, (3) Lehmer's method or LMO, which will be much faster for very large values.

Lastly, fast primecount + (Li or Riemann R) can be used to speedup prime() (SymPy's nth_prime function).  We ought to be shooting for  on the order of 1 second and under 100MB to compute the 100 millionth prime.

Original issue for #7021: http://code.google.com/p/sympy/issues/detail?id=3922
Original author: https://code.google.com/u/108653038694775415778/

**Comment by jksuom** [comment]
This can be closed as #10848 gives a good implementation of ``primepi`.
