### ISSUE TITLE
Disable diff_wrt on non-undefined Functions

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#7027]
```
We currently have 

In [6]: diff(cos(x), sin(x))
Out[6]: 0

But this confuses people, especially things like

In [7]: diff(x, re(x))
Out[7]: 0

In [8]: diff(x, conjugate(x))
Out[8]: 0

We should disable diff_wrt except on undefined functions, like Function('f'), and their derivatives.
```

Original issue for #7027: http://code.google.com/p/sympy/issues/detail?id=3928
Original author: https://code.google.com/u/asmeurer@gmail.com/

**Comment by kaichogami** [comment]
@asmeurer I would like to work on this if no one else is working on it already.

**Comment by asmeurer** [comment]
I don't think anyone is working on it. I don't see any pull requests.

**Comment by kaichogami** [comment]
@asmeurer if I am correct, we have to set `_diff_wrt` of various defined functions in sympy such as functions in `sympy.functions.elementary.trigonometric` to `False` so that it raises an error, instead of giving a `0`?

**Comment by asmeurer** [comment]
Yes, although the correct place to fix it is in the superclass in sympy.core.function.

**Comment by Abdullahjavednesar** [comment]
I'd like to take this up.
@asmeurer can you tell me what exactly you mean?

**Comment by smichr** [comment]
When this is fixed, `Derivative._diff_wrt` should be changed to return `self.expr._diff_wrt`.
