### ISSUE TITLE
Rational issue on simple expressions

### ISSUE THREAD

**Issue by sympy-issue-migrator** [sympy/sympy#7077]
```
On http://live.sympy.org/ I found this bug :

typing Rational(201,10**2) it shows 

201/100

but typing  Rational((2.01*10**2),10**2)
it shows  

7072058789855231/3518437208883200
```

Original issue for #7077: http://code.google.com/p/sympy/issues/detail?id=3978
Original author: https://code.google.com/u/107837697286144707451/

**Comment by oscarbenjamin** [comment]
There isn't anything to fix here so I'll close this issue now.
