### ISSUE TITLE
Expectation object

### ISSUE THREAD

**Issue by mrocklin** [sympy/sympy#7094]
We should have an expectation object for sympy.stats.  This should be the unevaluated version of the expectation/E function.  

Several tests may be shortened with this in hand, it may also enable the simpler expression of simplifications.

Original issue for #7094: http://code.google.com/p/sympy/issues/detail?id=3995
Original author: https://code.google.com/u/109882876523836932473/

**Comment by Smit-create** [comment]
Hi @mrocklin,
Currently we have symbolic Expectation class in sympy.stats.symbolic_probability:
https://github.com/sympy/sympy/blob/0e5c17184b411a10b475b32c84ac161e93abfa05/sympy/stats/symbolic_probability.py#L70-L138

Should this be closed @mrocklin @Upabjojr @czgdp1807 ?

**Comment by Upabjojr** [comment]
I suppose @mrocklin is quite busy with [dask](https://github.com/dask/dask) now.
