### ISSUE TITLE
Incorrect expression resulting from integral evaluation

### ISSUE THREAD

**Issue by sympy-issue-migrator** [sympy/sympy#7098]
Using sympy version 0.7.3, the following definite integral evaluation produces -pi, but the result should be +pi.
```
from sympy import *
>>> x = Symbol('x')
>>> integrate(1/sqrt(x) * 1/sqrt(1-x), (x,0,1))
-pi
```

This integral should produce the same result as B(1/2, 1/2) = pi (where B is the beta function). Also, for comparison, passing the expression "int 1/sqrt(x) * 1/sqrt(1-x) dx, x=0..1" to wolfram alpha produces pi.

Maybe the integration limits are getting switched somewhere internally?

Original issue for #7098: http://code.google.com/p/sympy/issues/detail?id=3999
Original author: https://code.google.com/u/108737546178018247953/

**Comment by smichr** [comment]
Now this is unevaluated:

```
>>> integrate(1/sqrt(x) * 1/sqrt(1-x), (x,0,1))
Integral(1/(sqrt(x)*sqrt(-x + 1)), (x, 0, 1))
```

**Comment by oscarbenjamin** [comment]
This consistently gives the correct result now:
```julia
In [6]: integrate(1/sqrt(x) * 1/sqrt(1-x), (x,0,1))                                                                                            
Out[6]: π
```
I think maybe this can be closed.
