### ISSUE TITLE
Geometric Algebra - gradient of an exponential

### ISSUE THREAD

**Issue by jdekozak** [sympy/sympy#7099]
Hi team,

With git version of sympy (to be the 0.7.4 release), I don't understand the following results for the attached script :
```
my exponential = exp(-E*gamma_w*t)
-E*gamma_w*exp( -E*gamma_w*t )*gamma_t = E*exp(-E*gamma_w*t)*gamma_t^gamma_w

grad*(my exponential) = -E*gamma_w*exp(-E*gamma_w*t)*gamma_t
grad*(my exponential)+E*gamma_w*(my exponential)*gamma_t = -E*gamma_w*exp(-E*gamma_w*t)*gamma_t - E*exp(-E*gamma_w*t)*gamma_t^gamma_w
```
Is it a correct value for the gradient ?

Original issue for #7099: http://code.google.com/p/sympy/issues/detail?id=4000
Original author: https://code.google.com/u/111956095810919425372/

**Comment by smichr** [comment]
see galgebra at [this location](https://github.com/brombo/galgebra)
