### ISSUE TITLE
Allow to choose a custom printer in init_printing

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#7112]
I thought I already opened this issue, but I didn't find it. `init_printing()` and `init_session()` should allow to pass in a custom printer. This should work for both string printers and latex printers. Issue ~~3612~~ #6711 is somewhat related as well.

**Comment by oscarbenjamin** [comment]
It looks like `init_printing` and `init_session` both now have the option to pass in custom printers e.g.:
[https://github.com/sympy/sympy/blob/88f7236a418a04e6c49e3443167f8759dfb0b06c/sympy/interactive/printing.py#L337-L343](https://github.com/sympy/sympy/blob/88f7236a418a04e6c49e3443167f8759dfb0b06c/sympy/interactive/printing.py#L337-L343)

[https://github.com/sympy/sympy/blob/88f7236a418a04e6c49e3443167f8759dfb0b06c/sympy/interactive/session.py#L346-L353](https://github.com/sympy/sympy/blob/88f7236a418a04e6c49e3443167f8759dfb0b06c/sympy/interactive/session.py#L346-L353)

So I guess this is fixed and can be closed.
