### ISSUE TITLE
Nondeterminism in integral of tanh(x)

### ISSUE THREAD

**Issue by versusvoid** [sympy/sympy#7119]
```
http://www.sympygamma.com/input/?i=integrate%28tanh%28x%29%2C+x%29 Should be log(cosh(x)): http://www.wolframalpha.com/input/?i=int%5Btanh%28x%29%5D
```

Original issue for #7119: http://code.google.com/p/sympy/issues/detail?id=4020
Original author: https://code.google.com/u/101768856126303922845/

**Comment by oscarbenjamin** [comment]
I tried this code:
```python
from sympy import *
x = Symbol('x')
print(tanh(x).integrate(x))
```

And I consistently get the right answer on master:
```console
$ python t.py 
x - log(tanh(x) + 1)
```

**Comment by asmeurer** [comment]
Both answers were correct. Most nondeterminism in the codebase was rooted out a long time ago thanks to hash randomization.
