### ISSUE TITLE
logcombine not working on some inputs

### ISSUE THREAD

**Issue by nebffa** [sympy/sympy#7123]
```
If I do:

logcombine(log(5) + log(3))
>>> log(15)

yet logcombine(log(5) - log(3))
>>> -log(3) + log(5)

Where it should be log(5/3)
```

Original issue for #7123: http://code.google.com/p/sympy/issues/detail?id=4024
Original author: https://code.google.com/u/109155823183661363200/

**Comment by abaokar-07** [comment]
@asmeurer @jksuom This issue should be closed now, it's fixed in the current master

**Comment by jksuom** [comment]
Fixed by https://github.com/sympy/sympy/pull/14134.
