### ISSUE TITLE
Remove the ClassRegistry

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#7124]
The ClassRegistry was introduced to make it easier to get around circular imports, but it's a bad idea, because it forces all subclasses of Basic to have a unique name. We should get rid of it, and use other methods to get around circular imports (like moving imports inside functions).

Original issue for #7124: http://code.google.com/p/sympy/issues/detail?id=4025
Original author: https://code.google.com/u/asmeurer@gmail.com/

**Comment by toolforger** [comment]
In case somebody isn't informed yet: I've been working on this, and am currently making substantial progress.

**Comment by toolforger** [comment]
Fixed via #9348 .

**Comment by asmeurer** [comment]
This is the issue in the code, so it should stay open until the object is completely removed.

**Comment by asmeurer** [comment]
When this is removed we can add it to abc.py.

**Comment by jcrist** [comment]
Isn't #9371 the deprecation removal issue for this?

**Comment by asmeurer** [comment]
I suppose it is. The issue in the code is wrong then.

**Comment by asmeurer** [comment]
https://github.com/sympy/sympy/pull/10441
