### ISSUE TITLE
Permutation * PermutationGroup should give the coset

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#7127]
```
In [5]: a
Out[5]: Permutation(1, 2)

In [6]: b
Out[6]: Permutation(0, 1)

In [7]: G
Out[7]:
    PermutationGroup([
      Permutation(1, 2),
    Permutation(2)(0, 1)])

In [8]: a*G
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-8-b860fc9136f1> in <module>()
----> 1 a*G

/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/combinatorics/permutations.py in __mul__(self, other)
   1241         a = self.array_form
   1242         # __rmul__ makes sure the other is a Permutation
-> 1243         b = other.array_form
   1244         if not b:
   1245             perm = a

AttributeError: 'PermutationGroup' object has no attribute 'array_form'

See https://twitter.com/cwlcks/status/380359799675695104 .
```

Original issue for #7127: http://code.google.com/p/sympy/issues/detail?id=4028
Original author: https://code.google.com/u/asmeurer@gmail.com/

**Comment by kaushik94** [comment]
#8734

**Comment by sylee957** [comment]
I'd have some options like either
1. Returning a `FiniteSet` when the coset is not a subgroup, and returning a `PermutationGroup` when the coset is a subgroup.
2. Return `FiniteSet` regardless of coset is a subgroup or not.
3. Only compute the coset as `PermutationGroup` and raise error when it cannot be.
4. Create a new set symbol `Coset` that can represent the coset without computing.

and also
- Make left multiplication and right multiplication return left cosets and right cosets individually.

At least for GAP references, I see that they provide `LeftCoset` and `RightCoset` symbols, so it ca be fine beginning with those symbolic representaitons, and I'd begin with subclassing `Basic` if it is not certain whether it should belong to Set or PermutationGroup.

**Comment by sylee957** [comment]
```python3
from sympy.core.basic import Basic
from sympy.core.sympify import _sympify
from sympy.combinatorics.permutations import Permutation
from sympy.combinatorics.perm_groups import PermutationGroup
from sympy.combinatorics.named_groups import SymmetricGroup


class LeftCoset(Basic):
    """A left coset of a permutation group with respect to an element.

    Parameters
    ==========

    g : Permutation

    H : PermutationGroup

    G : PermutationGroup, optional
        The group which contains *H* as its subgroup and *g* as its
        element.

        If not specified, it would automatically become a symmetric
        group ``SymmetricGroup(g.size)`` and
        ``SymmetricGroup(H.degree)`` if ``g.size`` and ``H.degree``
        are matching.
    """
    def __new__(cls, g: Permutation, H: PermutationGroup, G=None):
        g = _sympify(g)
        if not isinstance(g, Permutation):
            raise NotImplementedError

        H = _sympify(H)
        if not isinstance(H, PermutationGroup):
            raise NotImplementedError

        if G is not None:
            G = _sympify(G)
            if not isinstance(G, PermutationGroup):
                raise NotImplementedError
            if not H.is_subgroup(G):
                raise ValueError("{} must be a subgroup of {}.".format(H, G))
            if g not in G:
                raise ValueError("{} must be an element of {}.".format(g, G))
        else:
            g_size = g.size
            h_degree = H.degree
            if g_size != h_degree:
                raise ValueError(
                    "The size of the permutation {} and the degree of "
                    "the permutation group {} should be matching "
                    .format(g, H))
            G = SymmetricGroup(g.size)
        return Basic.__new__(cls, g, H, G)

    def __contains__(self, other):
        pass

    @classmethod
    def _new(cls, g: Permutation, H: PermutationGroup, G: PermutationGroup):
        """A constructor which bypasses the checks for internal use.
        Use this only if every parameters are already sympified and
        sanitized."""
        return Basic.__new__(cls, g, H, G)

    def _eval_rewrite_as_PermutationGroup(self, *args, **kwargs):
        pass

    def _eval_rewrite_as_FiniteSet(self, *args, **kwargs):
        pass
```

I'd have this framework to begin with.

**Comment by asmeurer** [comment]
I think having a coset object is the best way to go.

**Comment by mohitacecode** [comment]
Basically we have to create two class 'Left Coset` (which will used in computing the left coset) and 'Right coset`(which will used in computing the right coset ) which will be used when `Permutation * PermutationGroup` and `PermutationGroup * Permutation`.
Am I understanding it right? @asmeurer @sylee957

**Comment by sylee957** [comment]
Yes, I think that it’s good to begin with defining each objects symmetrically.

**Comment by mohitacecode** [comment]
what `_eval_rewrite_as_PermutationGroup` and `_eval_rewrite_as_FiniteSet` will be doing here?

**Comment by mohitacecode** [comment]
ping @sylee957

**Comment by mohitacecode** [comment]
I want to ask few things:
1.)will these class suffice for this issue?(since a*G and G*a just means left or right coset.
2.) what about these options will they be needed after the class is made.?

>1. Returning a `FiniteSet` when the coset is not a subgroup, and returning a `PermutationGroup` when the coset is a subgroup.
> 2. Return `FiniteSet` regardless of coset is a subgroup or not.
> 3. Only compute the coset as `PermutationGroup` and raise error when it cannot be.
> 4. Create a new set symbol `Coset` that can represent the coset without computing.

**Comment by sylee957** [comment]
Once the class is done to be representing some lazy evaluation of coset, then the stuff that I've enumerated should be implemented as computational methods inside the classes in any way.

The obvious computational things that would jump in are:

1. Writing `aG -> FiniteSet` to list all the elements
2. Finding isomorphic permutation group of the coset when it's possible
3. Finding a new representation for the coset `aG -> a'G`

So that's why I've listed them before

**Comment by mohitacecode** [comment]
Thanks @sylee957  I got it.
Just a quick question I saw that gap does not provide leftcoset as a seprate datatype they say that left coset gU consists of exactly the inverses of the elements of the right coset.
Should we consider that as a option too?

**Comment by sylee957** [comment]
I think that it can also make sense to have a single coset representative that can accept both arguments.

- `Coset(g, H)`
- `Coset(H, g)`

And making `Coset(H, g) => Coset(g**-1, H)` automatically canonicalized.

I may also think of dropping the third argument `G` if creating symmetric group every time can be time consuming. I think that coset needs some universe to be well-defined. But I'd expect special groups like `SymmetricGroup`, `AbelianGroup` to have a separate class for lazy construction.

**Comment by mohitacecode** [comment]
Ping @sylee957 

I was also thinking to have a single coset representative that can accept both arguments I think that we can make a API which will accept a `dir` as an input. 
for instance :

- Coset(g,H, dir = `left') - Calculate left coset.
- Coset(g,H, dir = `right`) - Calculate right coset.

As you said canonicalization can be disable in sympy at a lot of places so `dir` will help us here and accordingly we will flip the argument inside.

**Comment by mohitacecode** [comment]
I like the idea of representing `Rightcoset` and `LeftCoset` differently. I am not sure whether we can do this or not but here's my thought.

Can't we just return a Rightcoset and Leftcoset according to the `dir` mentioned by having RightCoset and LeftCoset have as a subclass of Coset.

**Comment by mohitacecode** [comment]
Thanks :) Okay got it.
I suppose it should be implemented in `perm_groups.py` .

> I think that 'left', 'right', 'center' can be made into some global symbols.

Just a small query can' we use them as string I saw that `Limit` use `+` and `-` as string.

**Comment by sylee957** [comment]
In Limit, '+' and '-' are internally converted to symbols that looks like plus and minus, and stored with them.
You can use the same symbols '+', '-', '+-' as Limit and comprehending '+' as 'right' and it can be better for reuse, though it can look awkward if you don't redefine the printers.

**Comment by mohitacecode** [comment]
Ping @sylee957 
just a quick questions before I soon a open a pr.

- While Implementing I took a close look at `GAP` and `Maple` I saw that they just return a list instead of group in every case whether coset is a subgroup or not.g

- for instance:
    GAP has a method AsList for printing the coset.
    
Should we follow that?

- why are we `sympifying(_sympify)` the `g`, `H` and `G` can you give any example please. 

- I am also thinking to remove the creation of group(G) if it's not provided I don't see any use.

**Comment by sylee957** [comment]
> why are we sympifying(_sympify) the g, H and G can you give any example please.

In sympy, it is possible to pass objects types to any kind of objects, and it is expected to raise proper errors when users pass nonsensical types. (Or it would just not be an user-friendly API)
So calling sympify should make it easier to deal with such situation.

> While Implementing I took a close look at GAP and Maple I saw that they just return a list instead of group in every case whether coset is a subgroup or not.g

This is the reason why I have made Coset as an intermediate object that does not inherit Group or Set. 
I'd keep the basic structure of Coset as I've defined, not inheriting crude types like `list`, because it can also serve better for educational purpose, that people can have visual of coset as LaTeX in their notebook.

> I am also thinking to remove the creation of group(G) if it's not provided I don't see any use. 

Coset is formally defined to have G as its universe. You can remove the definition because finite groups have symmetric groups of respective degrees as its universe. But I would expect you to explain what kind of feature will be lost if `G` is always expected to be symmetric group of the degree.

**Comment by mohitacecode** [comment]
Ping @sylee957  I have written this should I continue it?

```
class Cosets(Basic):

    """A coset of a permutation group with respect to an element.

    Parameters
    ==========

    g : Permutation

    H : PermutationGroup

    dir : "+" or "-", If not specified by default it will be "+"
        Here dir specified the type of coset "+" represent the
        right coset and "-" represent the left coset.

    G : PermutationGroup, optional
        The group which contains *H* as its subgroup and *g* as its
        element.

        If not specified, it would automatically become a symmetric
        group ``SymmetricGroup(g.size)`` and
        ``SymmetricGroup(H.degree)`` if ``g.size`` and ``H.degree``
        are matching.
    """
    def __new__(cls, g, H, G=None, dir = "+"):
        from sympy.combinatorics.named_groups import SymmetricGroup
        g = sympify(g)
        if not isinstance(g, Permutation):
            raise NotImplementedError

        H = sympify(H)
        if not isinstance(H, PermutationGroup):
            raise NotImplementedError

        if G is not None:
            G = sympify(G)
            if not isinstance(G, PermutationGroup):
                raise NotImplementedError
            if not H.is_subgroup(G):
                raise ValueError("{} must be a subgroup of {}.".format(H, G))
            if g not in G:
                raise ValueError("{} must be an element of {}.".format(g, G))
        else:
            g_size = g.size
            h_degree = H.degree
            if g_size != h_degree:
                raise ValueError(
                    "The size of the permutation {} and the degree of "
                    "the permutation group {} should be matching "
                    .format(g, H))
            G = SymmetricGroup(g.size)

        if dir == "+":
            return RightCoset(H, g, G)
        else:
            return LeftCoset(g, H, G)

class RightCoset(Basic):
    def __new__(cls, H, g, G = None):
        return Basic.__new__(cls, g, H, G)

    def __init__(self, H, g, G = None):
        self.list_repr = self._aslist(H, g)

    def __contains__(self, i):
        """
        Check if an element is present in a Coset or not.
        """
        if not isinstance(i,Permutation):
            raise TypeError("Element should be of type {} but it is {}".format("Permutation",type(i)))
        return i in self.list_repr

    def _aslist(self, H, g):
        cst = []
        for h in H.elements:
            cst.append(h*g)
        return cst

class LeftCoset(Basic):
    def __new__(cls, g, H, G = None):
        return Basic.__new__(cls, g, H, G)

    def __init__(self, g, H, G = None):
        self.list_repr = self._aslist(g, H)

    def __contains__(self, i):
        """
        Check if an element is present in a Coset or not.
        """
        if not isinstance(i,Permutation):
            raise TypeError("Element should be of type {} but it is {}".format("Permutation",type(i)))
        return i in self.list_repr

    def _aslist(self, g, H):
        cst = []
        for h in H.elements:
            cst.append(g*h)
        return cst
```

**Comment by sylee957** [comment]
Actually, I'd expect something like

```python3
class Coset(Basic):
    def __new__(cls, g, H, G=None, dir = "+"):
        from sympy.combinatorics.named_groups import SymmetricGroup
        g = sympify(g)
        if not isinstance(g, Permutation):
            raise NotImplementedError

        H = sympify(H)
        if not isinstance(H, PermutationGroup):
            raise NotImplementedError

        if G is not None:
            G = sympify(G)
            if not isinstance(G, PermutationGroup):
                raise NotImplementedError
            if not H.is_subgroup(G):
                raise ValueError("{} must be a subgroup of {}.".format(H, G))
            if g not in G:
                raise ValueError("{} must be an element of {}.".format(g, G))
        else:
            g_size = g.size
            h_degree = H.degree
            if g_size != h_degree:
                raise ValueError(
                    "The size of the permutation {} and the degree of "
                    "the permutation group {} should be matching "
                    .format(g, H))
            G = SymmetricGroup(g.size)

        dir = Symbol(dir)
        return Basic.__new__(cls, g, H, G, dir)

    @property 
    def is_left_coset(self):
        pass

    @property
    def is_right_coset(self):
        pass

    def aslist(self):
        pass
```
In your construction, `Cosets` can be meaningless if it just dispatches to different objects, so I think that it should rather be defined as a tuple of 4 containing the direction parameter, and figure out the direction by calling the property like `is_left_coset`
And you should also not use `__init__`, but define everything with `__new__` and make them follow the immutable design.

**Comment by mohitacecode** [comment]
Sure will change it.

**Comment by sylee957** [comment]
One of my other idea is making a new sympy object for SymmetricPermutationGroup which is a lazy form for SymmetricGroup, so that the permutations doesn’t have to be generated every time when G is built

**Comment by mohitacecode** [comment]
Do you mean we will avoid the computation and instead represent it like:
```
SymmetricPermutationGroup(g.size)
for instance: 
SymmetricPermutationGroup(5)
```

**Comment by sylee957** [comment]
Yes, and SymmetricPermutationGroup can contain some other methods that can take advantage of formulas that it already have.

**Comment by mohitacecode** [comment]
Sure got it.

**Comment by sylee957** [comment]
Actually #19077 does not close this issue completely. Some other work remains to define the multiplication between permutation and group

**Comment by mohitacecode** [comment]
will it suffice to modify `__mul__` of `Permutation` class for `a*G` and  `__mul__` of `PermutationGroup` class for `G*a`.

**Comment by sylee957** [comment]
I think that you can both modify `__mul__` and `__rmul__`

**Comment by mohitacecode** [comment]
I see that `PermutationGroup` class does not have `__rmul__`  defined and I am not sure about that but I have opened a pr by modifying `__mul__` only and it seems to work fine have a look if it looks ok to you.
