### ISSUE TITLE
Poly.real_roots may return non-real roots

### ISSUE THREAD

**Issue by sympy-issue-migrator** [sympy/sympy#7189]
```
Using Python 2.7.5 and sympy 0.7.3:

>>> from sympy import Poly, Symbol
>>> p = Symbol('p', nonnegative=True)
>>> n = 14
>>> alpha = 0.01
>>> Poly(p**n - alpha).real_roots()
[10**(6/7)*cos(pi/7)/10 + 10**(6/7)*I*sin(pi/7)/10, 10**(6/7)/10]

A complex root appears also for n in (18, 22, 26, 30).
```
Original issue for #7189: http://code.google.com/p/sympy/issues/detail?id=4090
Original author: https://code.google.com/u/100445484986973510686/

**Comment by smichr** [comment]
This appears to be fixed:

```
>>> p = Symbol('p', nonnegative=True)
>>> n = 14
>>> alpha = 0.01
>>> Poly(p**n - alpha).real_roots()
[-10**(6/7)*cos(pi/7)**2/10 - 10**(6/7)*sin(pi/7)**2/10, 10**(6/7)/10]
>>> [i.n()  for i in _]
[-0.719685673001152, 0.719685673001152]
```

I suspect it was fixed when the change to root isolation was made. I guess a test could be added to close this fully.

**Comment by asmeurer** [comment]
Or check if the PR that fixed it already added a similar test.

**Comment by smichr** [comment]
I remember work that I and @jksuom did on this. There were some issues with root isolation that were fixed and those were tested well. I'm just going to close this.
