### ISSUE TITLE
"Geometric Algebra" Documentation missing

### ISSUE THREAD

**Issue by sympy-issue-migrator** [sympy/sympy#7226]
The page http://docs.sympy.org/latest/modules/galgebra/ga.html returns "Page Not Found" which results in many broken links on the page http://docs.sympy.org/latest/modules/galgebra/index.html

Original issue for #7226: http://code.google.com/p/sympy/issues/detail?id=4127
Original author: https://code.google.com/u/106855735314640812954/

**Comment by QuLogic** [comment]
Are you sure about that? http://docs.sympy.org/latest/modules/galgebra/index.html points to http://docs.sympy.org/latest/modules/galgebra/ga.html which 404s, while GA.html would work fine.

**Comment by asmeurer** [comment]
Maybe only the dev docs were fixed.
