### ISSUE TITLE
Add scipy to lambdify

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#7229]
```
SciPy has versions of several functions that are in SymPy that aren't in NumPy, such as special functions ( http://docs.scipy.org/doc/scipy/reference/special.html ).  We need to add a scipy translation dictionary to lambdify.py, and include "scipy" automatically just as we do numpy.
```

Original issue for #7229: http://code.google.com/p/sympy/issues/detail?id=4130
Original author: https://code.google.com/u/asmeurer@gmail.com/

**Comment by Shekharrajak** [comment]
[NUMPY_TRANSLATIONS](https://github.com/Sympy/sympy/blob/master/sympy/utilities/lambdify.py#L67)  is it means, like we use  "atanh" in sympy but in numpy we use  "arctanh"for the same work.so mapping them?

**Comment by moorepants** [comment]
Yes. For SciPy there are some special functions that map to SymPy objects.

**Comment by Shekharrajak** [comment]
[Abs](https://github.com/Sympy/sympy/blob/master/sympy/utilities/lambdify.py#L68) in sympy ,then we have [fabs](http://docs.scipy.org/doc/numpy-1.10.1/reference/generated/numpy.fabs.html) , [absolute](http://docs.scipy.org/doc/numpy-1.10.0/reference/generated/numpy.absolute.html) and [abs](http://nullege.com/codes/search/numpy.abs) in numpy .so why only map Abs to  [abs](http://nullege.com/codes/search/numpy.abs) .?

Then we need to add Scipy in [line](https://github.com/Sympy/sympy/blob/master/sympy/utilities/lambdify.py#L18) other 2-3 lines where we can see numpy .
Are these changes enough to add Scipy like : lambdify((x,y), tan(x*y), "scipy") ?
If all is good, we can add examples and edit docs also. @moorepants

**Comment by moorepants** [comment]
> Abs in sympy ,then we have fabs , absolute and abs in numpy .so why only map Abs to abs .?

What else do you suggest?

> Then we need to add Scipy in line other 2-3 lines where we can see numpy . Are these changes enough to add Scipy like : lambdify((x,y), tan(x*y), "scipy") ? If all is good, we can add examples and edit docs also. @moorepants

I think you need to decide on what scipy functions map to sympy functions. There are some other pull requests that attempted this but they never got the testing set up correctly. You should start with those PRs.

**Comment by Shekharrajak** [comment]
We need some proper addition of Scipy inside the code . I am trying to modify correctly .I'll catch you in gitter chat.Thanks.

**Comment by moorepants** [comment]
Here are some issues and PRs that are relevant:

- https://github.com/sympy/sympy/pull/2883
- https://github.com/sympy/sympy/pull/7977
- https://github.com/sympy/sympy/issues/4471
- https://github.com/sympy/sympy/issues/5932
- https://github.com/sympy/sympy/issues/4470

**Comment by Shekharrajak** [comment]
I am able to `import scipy` using the shell `bin/isympy` (and using `isympy` , `ipython` also) .Is it because I have installed scipy in my system ? Because we can't import it from sympy live.

```
>>> import scipy
>>> import numpy
>>> a = numpy.arange(10)
>>> a
[0 1 2 3 4 5 6 7 8 9]
>>> expr=sin(x)
>>> f= lambdify(x,expr,"scipy")
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/root/sympy/sympy/utilities/lambdify.py", line 334, in lambdify
    buf = _get_namespace(m)
  File "/root/sympy/sympy/utilities/lambdify.py", line 406, in _get_namespace
    _import(m)
  File "/root/sympy/sympy/utilities/lambdify.py", line 124, in _import
    "'%s' module can't be used for lambdification" % module)
NameError: 'scipy' module can't be used for lambdification
>>> f= lambdify(x,expr,scipy)
>>> f(a)
[ 0.          0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427
            -0.2794155   0.6569866   0.98935825  0.41211849]            
>>> 

```
@moorepants

**Comment by moorepants** [comment]
SciPy isn't available on the Google App Engine so you won't see it on SymPy live.

lambdify doesn't accept `scipy` as a module yet. That's what is desired.

**Comment by Shekharrajak** [comment]
Okay got it. Thanks

**Comment by ramvenkat98** [comment]
@asmeurer @moorepants 

Hi,

I would like to work on this issue if it is still open. It seems from the comment threads that pull request 10319 fixed most issues, except for:

1. Not repeating the Numpy dictionary when creating the Scipy dictionary but just updating a copy
2. Adding scipy.special functions to the existing functions (would this be similar to what has already been done in 2883?)

Are these the main things to fix or are there others? Also, is there a way to work off this pull request and add on to it directly or would it be better to start another, since this is somewhat old and the branch has some conflicts?

Thank You!

**Comment by bjodah** [comment]
It should be as simple as adding the functions missing to:
https://github.com/sympy/sympy/blob/952382d9dcd7eb949480f6662e3222176debcdbc/sympy/printing/pycode.py#L513

and making sure passing `'scipy'` to `lambdify` makes it use `SciPyPrinter` from `.printing.pycode`.
