### ISSUE TITLE
precision of mpmath in Sympy

### ISSUE THREAD

**Issue by sympy-issue-migrator** [sympy/sympy#7230]
Computing pi in sympy using mpmath is not performed with the correct precision. For instance if mp.dps=100000 only the first 30000 digits are correct. It looks there is a mixed up between binary and decimal precision.
On the IPAD version of Python where mpmath is implemented, the computation is correct. mpmath could not be downloaded on my computer to check because Norton block the downloading and tells mpmath is a big risk?

Original issue for #7230: http://code.google.com/p/sympy/issues/detail?id=4131
Original author: https://code.google.com/u/102177633984609126004/

**Comment by smichr** [comment]
current master: `print(str(pi.n( 255945+7))[-10:]) # 4171111118` shows the string of 6 1s as described by

[A035117](http://oeis.org/A035117) at that position.
