### ISSUE TITLE
Change Python 3 compatibility to use Python 3 idioms

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#7258]
Currently the compatibility file tries to use Python 2 idioms in Python 3. We should be doing things the other way around, encouraging people to use Python 3 idioms. So for instance, we should be defining range in Python 2, not xrange in Python 3. 

I thought we had an issue for this already, but I can't find it. 
- [x] xrange has been removed. If xrange-compatibility is needed, range (which maps to xrange under PY2) should be imported from sympy.core.compatibility.  That range function cannot be sliced as range(10)[::2], however, and a workaround is used in code where that occurs (in 4 places currently which have been marked with an inline note).

**Comment by jayesh92** [comment]
Hi,
I've resolved this bug in my forked repo. The commit can be viewed at https://github.com/jayesh92/sympy/commit/eed80ddec8dd0c4803e9883b153ab5efc43df9de
Any comments ?

**Comment by moorepants** [comment]
@jayesh92 Please submit a pull request with your code changes.

**Comment by asmeurer** [comment]
@jayesh92 that's the right idea, although you'll need to fix code throughout SymPy to be compatible.

**Comment by rahilhastu** [comment]
Is there some more Python2 to Python3 conversion pending?
xrange has been resolved, are there any other idioms pending? I'm new to contributing and would love to work on this.

**Comment by oscarbenjamin** [comment]
I guess this isn't relevant any more. Soon Python 2 will be dropped and much of this can be excised from the codebase.

**Comment by asmeurer** [comment]
This could still be fixed in the interim. It will need to be done anyway once we drop Python 2. 

Although just glancing at the file I'm not sure what remains to be fixed here. My biggest gripe was with xrange. There is `unicode=str` which is used only in a handful of places, and `long=int`, which should probably stay for now (it's usually a bad idea to create small longs in Python 2). 

I didn't check everything. More than likely none of this will end up being changed until we do the big Python 2 support drop later this year.

**Comment by smichr** [comment]
We've got enough activity to not worry about modifying this file which will soon go away. :-)
