### ISSUE TITLE
LambertW has no series expansion at x=0 (nan)

### ISSUE THREAD

**Issue by mforbes** [sympy/sympy#7259]
With sympy version 0.7.5:

```
>>> series(LambertW(x),x)
nan
```

This is probably due to the chosen representation of the derivative

```
>>> LambertW(x).diff(x)
LambertW(x)/(x*(LambertW(x) + 1))
```

which requires a 0/0 limiting form with numerator `LambertW(x)`, which requires the derivative at 0 which has a limiting form of 0/0 and so on...

One mathematical solution is to replace `x = LambertW(x)*exp(LambertW(x))` in the derivative `1/(LambertW(x) + 1)/exp(LambertW(x))` which may be safely evaluated at `x=0` where `W(0) = 0`.  Not sure if this type of thing is easy to do in the code though.

**Comment by cbm755** [comment]
After #10531 is done, we may be able to cherry-pick here.
