### ISSUE TITLE
Cannot integrate exp(x)*sqrt(1+exp(2*x))

### ISSUE THREAD

**Issue by jondo** [sympy/sympy#7264]
Seen with version 0.7.2.
Maxima can do that, but it has GPL license.

**Comment by jondo** [comment]
According to that diofant issue, the Rubi integrator (https://github.com/sympy/sympy/issues/12233) can integrate this.

**Comment by rwst** [comment]
FWIW, Rubi's solution (via Mma): `1/2 E^x Sqrt[1 + E^(2 x)] + ArcSinh[E^x]/2`.
