### ISSUE TITLE
Should we be using the numbers ABCs?

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#7292]
See http://docs.python.org/2/library/numbers.html.

**Comment by pelegm** [comment]
+1. NumPy also support this: https://github.com/numpy/numpy/pull/4547

**Comment by toolforger** [comment]
Slight annoyance: There's a `numbers.Integral` class, so we have confusability with `sympy.integrals.integrals.Integral`.
This could cause devious problems if the two classes share method names, it's easy to mistake which of them was imported. IOW we probably should never `import numbers.Integral` or `from numbers import Integral`, just `import numbers`.

**Comment by oscarbenjamin** [comment]
I can't remember where it is but I'm sure there's another issue about the same thing.

**Comment by asmeurer** [comment]
https://github.com/sympy/sympy/issues/12134
