### ISSUE TITLE
Integration with Piecewise function returns incorrect answer.

### ISSUE THREAD

**Issue by woodscn** [sympy/sympy#7334]
The result is correct if S = x
Mathematica code:                                                             

> ranges={{t,.8,1},{x,-1,1}};  
> S=x/t;  
> eq=x^2+Piecewise[{{0,S<0}},1];  
> Integrate[eq,ranges[[1]],ranges[[2]]]                                       

yields: 0.333333                                                           

import sympy
x = sympy.Symbol('x')
t = sympy.Symbol('t')
ranges = ((t,.8,1),(x,-1,1))
S = x/t
base_integrand = x**2
integrand = sympy.Piecewise((base_integrand,S<0),(1+base_integrand,True))
exact_integral = sympy.N(
    sympy.integrate(
    sympy.integrate(integrand,ranges[0])
    ,ranges[1])
    )
print exact_integral
test = abs(exact_integral-0.333333) < 1e-5
if not test:
print "Test failed!"

**Comment by oscarbenjamin** [comment]
This integral doesn't evaluate:
```julia
In [57]: x, t = symbols('x t')

In [58]: p = Piecewise((x**2, x/t < 0), (x**2+1, True))

In [59]: p
Out[59]: 
⎧   2        x    
⎪  x     for ─ < 0
⎪            t    
⎨                 
⎪ 2               
⎪x  + 1  otherwise
⎩                 

In [60]: p.integrate((t, .8, 1))
Out[60]: 
 1                       
 ⌠                       
 ⎮  ⎧   2        x       
 ⎮  ⎪  x     for ─ < 0   
 ⎮  ⎪            t       
 ⎮  ⎨                  dt
 ⎮  ⎪ 2                  
 ⎮  ⎪x  + 1  otherwise   
 ⎮  ⎩                    
 ⌡                       
0.8                      

In [61]: p.integrate((t, .8, 1)).integrate((x, -1, 1))
Out[61]: 
1                             
⌠                             
⎮  ⎧        2         x       
⎮  ⎪   0.2⋅x      for ─ < 0   
⎮  ⎪                  t       
⎮  ⎨                        dx
⎮  ⎪     2                    
⎮  ⎪0.2⋅x  + 0.2  otherwise   
⎮  ⎩                          
⌡                             
-1  
```
Changing the order of integration doesn't help.

It also can't be computed with .evalf.

**Comment by smichr** [comment]
When t is made positive (as warranted by the integration range) the answer is obtained:
```python
>>> x = symbols('x')
>>> t=symbols('t',positive=True)
>>> p = x**2 + Piecewise((0, x/t < 0), (1, True))
>>> p.integrate((t, .8, 1)).integrate((x, -1, 1))
0.333333333333333
```

**Comment by asmeurer** [comment]
Where do the assumptions come into play? `integrate` should be smarter about setting the assumptions on the integration variable for definite integrals.

**Comment by smichr** [comment]
This suggests that when definite integration is being done that it would be a good idea to update the symbols used with appropriate assumptions:

```python
for lim in limits:
  if len(lim) != 3: continue
  v, a, b = lim
  assumptions = {}
  r = sorted([a, b])
  if all(i.is_real for i in r):
    assumptions.update(real=True)
  if r[0] > 0:
    assumptions.update(positive=True)
  elif r[0] == 0:
    assumptions.update(nonnegative=True)
  elif r[1] == 0:
    assumptions.update(nonpositive=True)
  elif r[1] < 0:
    assumptions.update(negative=True)
  elif not any(i.is_infinite for i in r):
    assumptions.update(finite=True)
  if not all(getattr(v, 'is_%s' % k, None) == a for k, a in assumptions.items()) # update limit with assumptions
```

**Comment by smichr** [comment]
> Where do the assumptions come into play

`x/t < 0` can't be simplified to `x < 0` unless the sign of t is known; perhaps this is encountered while integrating Piecewise.

**Comment by asmeurer** [comment]
The limits themselves could be symbolic, so we have to be careful about that. We also shouldn't assume that the lower limit is less than the upper limit.

**Comment by smichr** [comment]
> lower limit is less than the upper limit.

yes, that's why sorted is used. Catching an exception for non-sortable input would be a good idea there, too.

**Comment by smichr** [comment]
#4215 is a related issue involving symbol assumptions since splitting the integration could result in different assumptions for each part

**Comment by asmeurer** [comment]
I didn't notice the sorted call. I guess that will fail if a and b are symbolic with no base assumptions. Probably simpler would be to just check if both are positive or both are negative. 

The edge cases for 0 and infinity shouldn't matter. A single point doesn't affect the answer of an integral. In general, the value of the indefinite at the end points may only exist in the limit. So I think we only need to worry about `real`, `positive`, and `negative`.
