### ISSUE TITLE
Use scipy.stats when sampling from sympy.stats distributions

### ISSUE THREAD

**Issue by mrocklin** [sympy/sympy#7358]
The `sample` operation samples a random expression. 

```
>>> X = Normal('X', 0, 1)
>>> sample(100 + X)
100.325245
```

This depends on `*Distribution.sample` methods for each type of distribution (like `NormalDistribution`.)  These methods often call out to a sampling method in the `random` stdlib module.  When these methods do not exist we attempt to create one analytically by computing the CDF of the distribution.

In some cases the distribution is not found in `random` and the computation of the CDF is difficult.  When these two happen together it breaks our ability to sample.

One way to resolve this issue is to depend on the `scipy.stats` module instead of `random`, which is generally far more comprehensive.  This dependence would need to be shielded in case `scipy` wasn't present on the user's machine.

If someone wanted to fix this they should look at `sympy/stats/crv_types.py`, take a look at `GammaDistribution.sample` (works) and then try to implement the same thing for `GammaInverseDistribution.sample` (does not yet exist) using `scipy.stats.invgamma`.  Once that works there are several more!

**Comment by souravsingh** [comment]
I would like to work on this.How should I start?

**Comment by tokencolour** [comment]
I would like to work on this.

**Comment by tokencolour** [comment]
To make a guarded import, in addition to a try except block that raises an `ImportError` only when situations described by @mrocklin arise (i.e when random stdlib has no method and when CDF is difficult to evaluate), I wanted to use the `_import(module)` approach as used in `utilities/lamdify.py`. Should I? This might help us to support more modules. However, this foresight might be unnecessary. What do you think? @mrocklin @asmeurer

**Comment by tokencolour** [comment]
Or rather should I just use `import_module` from `sympy.external` ?

**Comment by tokencolour** [comment]
Could you please help me with this @leosartaj @gxyd ?

**Comment by leosartaj** [comment]
``import_module`` should do the job I guess. It looks general enough. Though you have to be careful if ``scipy.stats`` is not installed, it should gracefully fall back to ``random``. Try submitting a PR, it will be easier to discuss.

**Comment by tokencolour** [comment]
`random` doesn't support sampling Inverse-Gamma Probability Distribution, probably.

**Comment by leosartaj** [comment]
> random doesn't support sampling Inverse-Gamma Probability Distribution, probably.

True. If ``scipy.stats`` is absent and user tries to sample from distributions like Inverse-Gamma Probability Distribution, user should be informed with a message.

**Comment by Lakshya1605** [comment]
Is this still open? I'll take it if so.

**Comment by asmeurer** [comment]
I believe so. I don't see `scipy` used anywhere in the stats module.

**Comment by tokencolour** [comment]
@Lakshya1605 I wasn't able to solve this. It will be great if you take a look at the issue!

**Comment by Lakshya1605** [comment]
I was thinking if we could use this  scipy.stats.invgamma.rvs(self.k,0,selk,theta) to  solve this issue.Can please some help me by stating whether this is the correct approach.

**Comment by Lakshya1605** [comment]
inv_gamma=invgamma.rvs(self.a,0,self.b)
       return inv_gamma
is giving this error:TypeError: ufunc 'gammaincinv' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''
Whereas 
  inv_gamma=invgamma.rvs(1,0,1)
       return inv_gamma
is working fine can someone please help me

**Comment by Lakshya1605** [comment]
I have fixed the bug and sent a pull request .Thank

**Comment by asmeurer** [comment]
Please add a link to the PR here so that we don't have to go find it.

**Comment by Lakshya1605** [comment]
https://github.com/sympy/sympy/pull/11673

**Comment by Lakshya1605** [comment]
Pull request  #11699 sent ,Please verify @asmeurer  and @tokencolour .Thank you.

**Comment by Smit-create** [comment]
Closed via #19342
