### ISSUE TITLE
Problem integrating Piecewise function when mp.dps is set to 30

### ISSUE THREAD

**Issue by michaelwu0505** [sympy/sympy#7370]
When mp.dps is set to 30 (default is 15), the following code snippet will throw exception:

> from sympy.abc import x
> from sympy.mpmath import mpf, mp
> mp.dps = 30
> 
> f = Piecewise((1, x <= mpf(2400)))
> v = integrate(f, (x, 0, mpf("252.4")))

The exception thrown is:

> ValueError: Called interval evaluation over piecewise function on undefined intervals (252.400000000000000000000000000, 252.400000000000000000000000000)

I have verified that the problem exists with Sympy version 0.7.4.1 and 0.7.5.

**Comment by oscarbenjamin** [comment]
Seems to work fine now:
```julia
In [40]: f = Piecewise((1, x <= 2400)) 
    ...:                                                                                                                                       

In [41]: v = integrate(f, (x, 0, Float("252.4", 30)))                                                                                          

In [42]: v                                                                                                                                     
Out[42]: 252.400000000000000000000000000
```
