### ISSUE TITLE
Problem integrating Piecewise function

### ISSUE THREAD

**Issue by michaelwu0505** [sympy/sympy#7372]
The following code snippet does not produce correct result:
>from sympy import Piecewise, integrate, symbols, cos
>from sympy.abc import x
>
>f = Piecewise( (x+2, x<=10), (12, True))
>intFx = integrate(f, x)
>cosIntFx = cos(intFx)
>res = integrate(cosIntFx, (x, 0, 15))
>
>print res.evalf()

The result was:
>-Integral(cos(x**2/2 + 2*x), (x, 0)) + Integral(cos(x**2/2 + 2*x), (x, 10)) - 0.115146984995512

However, I was expecting the result to be a real number.

If changing
>f = Piecewise( (x+2, x<=10), (12, True))

to
>f = Piecewise( (x*2, x<=10), (12, True))

then the result would be a real number (res=0.485978199817932).

This problem is verified with Sympy version 7.5

**Comment by jcrist** [comment]
Fixed in master:

```
>>> from sympy import Piecewise, integrate, symbols, cos
>>> x = symbols('x')

>>> f = Piecewise( (x+2, x<=10), (12, True))
>>> intFx = integrate(f, x)
>>> cosIntFx = cos(intFx)
>>> res = integrate(cosIntFx, (x, 0, 15))
>>> res.evalf()
0.0345116413320612
```

Closing.
