### ISSUE TITLE
TypeError when using both multiprocessing and gmpy

### ISSUE THREAD

**Issue by cgkanchi** [sympy/sympy#7457]
When using Sympy with both gmpy (tested on 2.0.3 and 1.5) and multiprocessing, certain operations raise a TypeError: 'argument is not an mpz'. The code works fine within a single process with gmpy or with multiple processes without gmpy but not both.

Please see code below. 

``` python
import sympy
import multiprocessing
import numpy

def thread_function(func, data, extra_kwargs=None, num_procs=None):
    if extra_kwargs:
        func = functools.partial(func, **extra_kwargs)

    if not num_procs:
        num_procs = multiprocessing.cpu_count()
    pool = multiprocessing.Pool(processes=num_procs)
    results = pool.map_async(func, data.T)
    pool.close()

    pool.join()
    return results.get()

def test_fn(data):
    x = data[0]
    y = data[1]
    circle = sympy.Circle((0,0), 10)
    line = sympy.Line(sympy.Point(0,0), sympy.Point(x,y))
    return line.intersection(circle)[0].evalf()

if __name__ == '__main__':
    data = numpy.vstack((numpy.arange(1, 100), numpy.arange(1, 100)))

    print thread_function(test_fn, data) #raises error
#    print [test_fn(data[(0,1):,i]) for i in xrange(data.shape[1])] #works fine
```

This raises a TypeError as below:

```
Exception in thread Thread-3:
Traceback (most recent call last):
  File "C:\python27\lib\threading.py", line 810, in __bootstrap_inner
    self.run()
  File "C:\python27\lib\threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "C:\python27\lib\multiprocessing\pool.py", line 376, in _handle_results
    task = get()
  File "C:\python27\lib\site-packages\sympy\geometry\point.py", line 91, in __new__
    for f in coords.atoms(Float)]))
  File "C:\python27\lib\site-packages\sympy\simplify\simplify.py", line 3839, in nsimplify
    return _real_to_rational(expr, tolerance)
  File "C:\python27\lib\site-packages\sympy\simplify\simplify.py", line 3781, in _real_to_rational
    r = nsimplify(float, rational=False)
  File "C:\python27\lib\site-packages\sympy\simplify\simplify.py", line 3861, in nsimplify
    exprval = expr.evalf(prec, chop=True)
  File "C:\python27\lib\site-packages\sympy\core\evalf.py", line 1300, in evalf
    re = C.Float._new(re, p)
  File "C:\python27\lib\site-packages\sympy\core\numbers.py", line 673, in _new
    obj._mpf_ = mpf_norm(_mpf_, _prec)
  File "C:\python27\lib\site-packages\sympy\core\numbers.py", line 56, in mpf_norm
    rv = mpf_normalize(sign, man, expt, bc, prec, rnd)
TypeError: ('argument is not an mpz', <class 'sympy.geometry.point.Point'>, (-4.47213595499958, -8.94427190999916))
```

This looks to me as if Sympy.geometry.Point is not correctly being cast into an mpz. Why this should only happen in a multiprocessing environment however, is puzzling.

**EDIT**: I'm using Sympy 0.7.5 (release), Python 2.7.6 (32-bit) and gmpy 2.0.3 (32-bit) (from binaries) on Windows 8.1 64-bit. 

**EDIT2**: This also occurs on the current Master (2-May-2014)

**EDIT3**: There was a small bug in the example code with the order of iteration of the data. This is now fixed.

**Comment by isuruf** [comment]
This was fixed unintentionally in #11862, but #7457 might be a good idea.

**Comment by asmeurer** [comment]
@isuruf did you mean to link to a comment on this issue?

The fix in https://github.com/sympy/sympy/pull/11862 was intentional (see https://github.com/sympy/sympy/pull/11862/commits/8a7e07992035f05780ebc33b4ffbf72d32a83069). I didn't add a test for pickling, but I did add a test that Float works with a tuple input of non-mpz.

**Comment by asmeurer** [comment]
That is to say, I wasn't intentionally fixing pickling, but I did come across the source of this issue when working on Float and fix it directly (that PR didn't just mask the error or anything like that).
