### ISSUE TITLE
Questions about mixing formula-HANG

### ISSUE THREAD

**Issue by bxlkm** [sympy/sympy#7463]
Hello everyone!
Please help me!

Sympy 0.7.5 rc1(release), Python 2.7.6 (32-bit) ,numpy-1.8.1 rc1(release)
code:

```python
import sympy as sym
import numpy as np
i = sym.Symbol("i")
sym.summation(sym.factorial(i).evalf(), (i, 1, 3)).evalf()
```

This is right! 

The following combinations.
```python
import sympy as sym
import numpy as np
i = sym.Symbol("i")
sym.summation(sym.factorial(i).evalf(), (i, 1.5, 3.5)).evalf()
```
This is Hang!

Parameter is float type!
`i =  1.5 to 3.5`

How to solve this problem?

**Comment by hargup** [comment]
Other than the floating point issues, summation also misbehaves on for non-integer rangers for very simple functions.

```python
summation(1, (i, 1, Rational(5, 2)))
Out[9]: 5/2
```

The documentation says:
> ``Sum`` represents a finite or infinite series, with the first argument
being the general form of terms in the series, and the second argument
being ``(dummy_variable, start, end)``, with ``dummy_variable`` taking
all integer values from ``start`` through ``end``.

Hence, the output should be 2.

**Comment by hargup** [comment]
Closing the issue in favor of simpler https://github.com/sympy/sympy/issues/9358
