### ISSUE TITLE
What is the recommended way to add a horizontal or vertical line to a plot?

### ISSUE THREAD

**Issue by smichr** [sympy/sympy#7471]
I can't use plot to plot y=3

```
>>> plot(3)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "sympy\plotting\plot.py", line 1260, in plot
    series = [LineOver1DRangeSeries(*arg, **kwargs) for arg in plot_expr]
TypeError: __init__() takes exactly 3 arguments (2 given)
>>>
```

nor `x-3` (obviously, because it makes this `y=x-3`. If I use `plot_implicit` the boldness of the lines does not match (the implicit line is much lighter and it looks the same even if the ranges are both the same).

```
>>> p=plot(x)
>>> p.extend(iplot(x-3))
>>> p.show()
```

![figure_1](https://cloud.githubusercontent.com/assets/90703/2892879/418d0ffc-d542-11e3-9ffb-fdd77ce2b6dc.png)

**Comment by sahilshekhawat** [comment]
Seems like a bug to me as I am only able to plot if y is of the form 2**x. So, I am gettting the ``plot(2)``  , ``plot(4)`` etc. but not of others.

**Comment by davidlowryduda** [comment]
I don't think this is possible (surprisingly enough). This is easy enough to do in matplotlib, but there doesn't seem to be an obvious way to communicate to matplotlib through the plotting interface. Am I wrong?

**Comment by moorepants** [comment]
It should somehow translate to the axhline and axvline functions in matplotlib.

**Comment by normalhuman** [comment]
`plot_parametric(x, 3)` works. Tested in the 
```
from sympy.plotting import plot_parametric
p = plot(x)
p.extend(plot_parametric(x, 3))
p.show()
```
![plot](https://i.stack.imgur.com/aumLe.png)

I think that for _vertical_ lines this is all there is to be done; they are not graphs of functions, so cannot be plotted with `plot`. 

For horizontal, of course, this is a bug.

**Comment by westurner** [comment]
What is the recommended way to add a horizontal line to a plot?

(Use case: Labeling quantiles on a plot of a Normal density function)

**Comment by asmeurer** [comment]
The easiest way to add custom stuff to a plot is to access the matplotlib objects with `p._backend.ax` and `p._backend.fig` and add it using the matplotlib APIs.

**Comment by westurner** [comment]
Thanks. I'll check the docs for that advice

**Comment by westurner** [comment]
Is there a backend-independent way to draw a horizontal line?

**Comment by westurner** [comment]
These may be the relevant docs:

https://github.com/sympy/sympy/blob/a44cc429c0c38e9abf6e60d421a94bb2f1de26c9/sympy/plotting/plot.py#L8-L18

**Comment by asmeurer** [comment]
Well matplotlib is the only "real" backend that we have. Personally I think our plotting API should just focus on matplotlib, and more specifically, do a better job of exposing the matplotlib objects to the user so they can use the matplotlib API to do custom stuff. 

With that being said, I believe the method described at https://github.com/sympy/sympy/issues/7471#issuecomment-360932007 should work too.

**Comment by westurner** [comment]
When I modify the matplotlib plot with the matplotlib backend by adding vertical lines, how do I then show that modified figure?

```python3
# %%
from sympy import plot, Symbol
from sympy.stats import Normal, density
mean = 100
stddev = 15
quantile_ranges = [(n, mean - stddev*n, mean + stddev*n) for n in [0, 1, 2, 3, 4, 5]]

ndist = Normal('iqdist', mean, stddev)
x = Symbol('x')
densityfunc = density(ndist)
y = densityfunc(x)
distplot = plot(y, (x, 0, 200), title=f'Distribution ($\sigma$ = {stddev})')

# %%
# import pdb; pdb.set_trace()
plt = distplot._backend.fig.gca()
for n, start, end in quantile_ranges:
    ymax = float(densityfunc(start))
    plt.vlines(start, 0, ymax, label=f'-{n} $\sigma$ = {start}')
    plt.vlines(end, 0, ymax, label=f'{n} $\sigma$ = {end}')

display(distplot._backend.fig)  # Shows vlines and PDF but cropped with no labels?
distplot.show()    # Doesn't show vlines
display(distplot)  # <sympy.plotting.plot.Plot at 0x7fa1fb3d65e0>
display(plt)       # <AxesSubplot:title={'center':'Distribution ($\\sigma$ = 15)'}, xlabel='x', ylabel='f(x)'>
# plt.show()       # AttributeError: 'AxesSubplot' object has no attribute 'show'
```

**Comment by westurner** [comment]
FWIW, these each display three plots in JupyterLab; both with *horizontal* lines:

1) y=x
2) blank with axes
3) y=x && y=3)

```python
# %%
# Horizontal line from x_-inf to x_+inf where y=3:
from sympy.plotting import plot_parametric
x = Symbol('x')
p = plot(x)
p.extend(plot_parametric(x, 3))
p.show()

# %%
# Also a horizontal line from x_-inf to x_+inf where y=3:
y = Symbol('y')
p.extend(plot_parametric(y, 3))
p.show()
```

**Comment by oscarbenjamin** [comment]
We should expose the `ax` and `fig` objects in a public API (not using underscores).

**Comment by westurner** [comment]
Is this https://github.com/sympy/sympy/issues/14048#issuecomment-674427544 the recommended way to access the backend API? ::

```python
p.backend = p.backend(p)
```

Is that an alternative to using the 'private' _fig/_ax API?
