### ISSUE TITLE
Implement sets to Boolean and Boolean to set transformations for multidimensional/multivariate sets and Boolean.

### ISSUE THREAD

**Issue by hargup** [sympy/sympy#7482]
Sample input and output.

```
In[]: (x**2 + y**2 < 1).as_set(r, theta)
Out[]: {(r⋅cos(θ), r⋅sin(θ)) | r, θ ∊ [0, 1] × [0, 2⋅π]}

In[]: Interval(0, 1)*Interval(0, 3).as_relational(x, y)
Out[]: x ≥ 0 ∧ y ≥ 0 ∧ x ≤ 1 ∧ y ≤ 3
```

**Comment by oscarbenjamin** [comment]
The suggested API for these examples is not generally well defined. How should sympy know the relationship between x,y and r,theta? How many sets can be expressed as relations?

**Comment by oscarbenjamin** [comment]
I'm going to close this issue because the suggestion is ill-posed.
