### ISSUE TITLE
Printer for Product Set with Unions is ambiguous. 

### ISSUE THREAD

**Issue by hargup** [sympy/sympy#7486]
In the printer of sets like this
```
In [46]: (Interval(-oo, 0, True, True) + Interval(1, oo, True, True)) * (FiniteSet(1) + Interval(2, 3, True, True)
)
Out[46]: (-oo, 0) U (1, oo) x {1} U (2, 3)
```
It is hard to guess the parenthesization of the operators. The printers should solve this maybe by introducing new parenthesis at right places.

**Comment by hargup** [comment]
@kaushik94 yes I'm expecting the output as `((-oo, 0) U (1, oo)) x ({1} U (2, 3))`, except the parenthesis part the current printer is clear enough hence I don't think we should print the word `Set` in it.

This should be an easy to fix issue.

**Comment by kaushik94** [comment]
@hargup okay. Its been a long time, I'll take a look and try to fix it today.

**Comment by aktech** [comment]
@kaushik94 
You can help in reviewing this #9527

**Comment by gxyd** [comment]
This "does not" seem to have been fixed. The problem is there with other `printing` in `sets`
```
>>> Union(Complement(Interval(1, 2, False, True), FiniteSet(x)), Interval(2, 3, True, True))
(2, 3) U [1, 2) \ {x}                 # this should be like ->     ((2, 3) U ([1, 2)  \ {x}))
```
Since in general `A U (B - C) !=  (A U B) - C`

**Comment by gxyd** [comment]
@jksuom can you confirm if this has been fixed or not ?

**Comment by jksuom** [comment]
This is what I get in the first case: ``((-∞, 0) ∪ (1, ∞)) × ({1} ∪ (2, 3))``. So it seems to have been fixed. 
But the other case with the complement definitely should have parentheses.

**Comment by hargup** [comment]
@gxyd can you open up another issue for complement printing.

**Comment by gxyd** [comment]
Opened #9877
