### ISSUE TITLE
4 tests failing in Python 3.4 (and 2 unexpectedly passing)

### ISSUE THREAD

**Issue by andrewclegg** [sympy/sympy#7510]
Not sure if you officially support Python 3.4 yet, but in case this is useful -- I am trying to get SymPy working in this environment for the [Snake Charmer](https://github.com/andrewclegg/snake-charmer/) project.

However, 4 tests are failing, and 2 are passing unexpectedly -- see this transcript:

https://gist.github.com/andrewclegg/1413dec10856535d6157

This on an Ubuntu 12.04 VM, see ["what is included"](https://github.com/andrewclegg/snake-charmer/blob/master/README.md) for a list of the Python packages installed.

**Comment by hargup** [comment]
@andrewclegg are you still facing the issue?

**Comment by oscarbenjamin** [comment]
I think this can be closed now
