### ISSUE TITLE
Incorrect limit result

### ISSUE THREAD

**Issue by justanotheranonymoususer** [sympy/sympy#7535]
Here's one I've stumbled upon:

http://www.sympygamma.com/input/?i=limit+%28tan%28x%29%2Fsin%28tan%28x%29%29+%2Cx%2Cpi%2F2%29

It says that the limit is ∞, but it's incorrect. It reaches -∞ too: sin goes crazy because tan goes to +∞/-∞.

I hope that this is the correct place to report this.

Thank you and best regards.

**Comment by gschintgen** [comment]
With current master:
```
In [1]: limit(tan(x)/sin(tan(x)), x, pi/2)
Out[1]:
     ⎛   tan(x)  ⎞
 lim ⎜───────────⎟
   π ⎝sin(tan(x))⎠
x─→─⁺
   2

In [2]: limit(tan(x)/sin(tan(x)), x, pi/2, dir='-')
Out[2]:
     ⎛   tan(x)  ⎞
 lim ⎜───────────⎟
   π ⎝sin(tan(x))⎠
x─→─⁻
   2

In [3]: limit(tan(x)/sin(tan(x)), x, pi/2, dir='+-')
Out[3]:
    ⎛   tan(x)  ⎞
lim ⎜───────────⎟
   π⎝sin(tan(x))⎠
x─→─
   2
```
And also:
```
In [4]: limit(sin(tan(x)), x, pi/2)
Out[4]: <-1, 1>

In [5]: -oo*(1/sin(-oo))
Out[5]: <-∞, ∞>

In [6]: oo*(1/sin(oo))
Out[6]: <-∞, ∞>

In [7]: oo*(1/sin(-oo))
Out[7]: <-∞, ∞>

In [8]: -oo*(1/sin(oo))
Out[8]: <-∞, ∞>
```
Seems alright to me. I think all the issues here are fixed and all that's left is to add a test for the original limit.

**Comment by evatiwari** [comment]
Hi, I would like to help close this issue. Since I am a beginner, I would appreciate some help regarding adding a test, since I have seen this phrase come up repeatedly in other issues as well.

**Comment by oscarbenjamin** [comment]
You can see examples of other tests for limit here:
https://github.com/sympy/sympy/blob/153864a6ed7432256022a13c78499e558d04fa31/sympy/series/tests/test_limits.py#L888

We should add a test function that tests each of the examples shown by @gschintgen above.

**Comment by evatiwari** [comment]
I have written tests for the first few cases, but I wanted to know how to assert that an expression oscillates between -1 and 1, since actually writing <-1,1> gives syntax error. I have written 
```
assert oo*(1/sin(oo)) >= -oo and oo*(1/sin(oo)) <= oo
```
but I'm not sure if it is the same thing as stated above.
Also on what basis do I number the function that I have written?

**Comment by sidhu1012** [comment]
> On what basis do I number the function that I have written?

Issue number , as in this case it is 7535
