### ISSUE TITLE
"incompatibility" between builtin sets and FiniteSet interfaces

### ISSUE THREAD

**Issue by amitsaha** [sympy/sympy#7537]
Some of the standard set operation methods are named differently between the two. For example:

```
- intersect() in FiniteSet and intersection() in builtin set
- is_subset() in FiniteSet and issubset() in builtin set
...
```

Is there any plan or thoughts on how to make it possible for 3rd party libraries which allow sets as inputs to work with sets created using `FiniteSet`?  (but currently do not work because of these incompatibilities ?)

We could start having these "compatible" methods in SymPy calling the actual SymPy methods, but i am not sure if that is the cleanest solution.

TODO:
- [x] issubset/issuperset, see #7553
- [x] isdisjoint, see #7565 
- [ ] symmetric_difference

**Comment by kaichogami** [comment]
@amitsaha @skirpichev @hargup I think this issue could be closed now.

**Comment by oscarbenjamin** [comment]
It looks like the relevant methods are implemented so I'll close this.
