### ISSUE TITLE
Missprint in the documentation?

### ISSUE THREAD

**Issue by sachilles** [sympy/sympy#7551]
Dear all,

today I used the faunction gaunt from the module sympy/physics/wigner.py. I was a bit surprised about the documtentation since it is stated that

```
Y(j_1,j_2,j_3,m_1,m_2,m_3)
        =\int Y_{l_1,m_1}(\Omega)
         Y_{l_2,m_2}(\Omega) Y_{l_3,m_3}(\Omega) d\Omega
        =\sqrt{(2l_1+1)(2l_2+1)(2l_3+1)/(4\pi)}
         \; Y(j_1,j_2,j_3,0,0,0) \; Y(j_1,j_2,j_3,m_1,m_2,m_3)
```
but there is no definition of j_1, j_2, and j_3. I guess this is simpy a mistake and all the j's should read as l's, isn't it?

In addition, the nomenclature is a bit confusing. On the left hand side it is stated that Y belongs to the gaunt coefficient. But what is about the right hand side? Shouldn't the Y's used here name the Wigner 3jm symbols?

Thanks in advance and best regards.

**Comment by hargup** [comment]
FYI the documentation issue was fixed with https://github.com/sympy/sympy/pull/9752  not sure about the code issues mentioned in https://github.com/sympy/sympy/issues/7551#issuecomment-45104115.

**Comment by hargup** [comment]
Okay the code issue is reported at https://github.com/sympy/sympy/issues/7586 so this can be closed now.
