### ISSUE TITLE
algebra with stored symbols and limits

### ISSUE THREAD

**Issue by AParraRodriguez** [sympy/sympy#7558]
Hi everyone, I am quite new with sympy and I am having trouble dealing with symbols in Matrices. I might be doing something wrong and I don't understand why.

Basically my program runs as follows:
1. Store a list of symbols in a list: 

Lsymbols = symbols('L0:%d,positive=True'%numberOfSymbols)
and an explicit one: 
MLX = symbols('MLX',positive=True)
1. Make some matrices with those symbols and perform some multiplications, square roots and divisions of those elements.

for example: 
A[1,1] = sqrt(Lsymbols[0]/Lsymbols[1])  
B[1,1] = sqrt(Lsymbols[0]_Lsymbols[1] - MLX_*2)
1. From the final matrix I take the limit of each position's expression

limit(FinalMatrix[1,1],MLX,0) = oo*sign(...)         Wrong

The problem is that when I take the limit of the elements of the last matrix they are not well calculated. If I take the same explicit expression with symbols created one by one like:

L0 ,L1= Symbol("L0,L1",positive =True)
....

and calculate the limit then I have the correct result.

limit(sameExpressionAsC[1,1],MLX,0)  = 1/(L0 + L1)             Correct

Expressions like for example: 
L0_(2_L1 - 2_sqrt(L1/L0)_sqrt(L0_L1 - MLX__2))/(MLX__2_(L0 + L1))

I think the problem is that sympy is not able to simplify enough those expressions but I cannot understand why when the symbols are stored and then used is different.

I want to share the code but I don't know if there is any policy of not writing here too many lines of code

**Comment by oscarbenjamin** [comment]
I think this can be closed.
