### ISSUE TITLE
slowness of `replace` method

### ISSUE THREAD

**Issue by berceanu** [sympy/sympy#7560]
In this IPython notebook 
http://nbviewer.ipython.org/github/berceanu/notebooks/blob/master/min_example.ipynb
I use Sympy to solve a problem similar to 
http://mathematica.stackexchange.com/questions/24794/symbolic-manipulation-of-functional-form
by implementing the second answer, with the series expansion.
However, it seems that due to using `replace` this take on the order of 200 times longer than the Mathematica version. Am I doing something wrong?

**Comment by oscarbenjamin** [comment]
Should thus be closed?

The link to the Jupyter notebook no longer works so I can't see what the original problem was.

**Comment by smichr** [comment]
> I can't see what the original problem was.

From the Mathematica page: `... [select] terms that are up to linear (i.e. zero and first order) in the functions f and g:` for an expression like 
```
3*f(t)*conjugate(g(x)) + f(x)*f(y)*g(w) + f(x)*g(w) + f(x) + g(w) + g(z)*conjugate(f(y)) + conjugate(b)*conjugate(c) + conjugate(g(z)) + 1
```
The approach that I gave doesn't use series to do this, it just works with the expanded expression.

I don't know if there is a function that should be written for this or not for polynomial expressions, to truncate past some given order in given symbols. Perhaps these special approaches are best collected at a stackexchange like location...or here in the issues archive.
