### ISSUE TITLE
Gaunt coefficients

### ISSUE THREAD

**Issue by sachilles** [sympy/sympy#7586]
Dear all,

I'm wondering about the Gaunt coefficients calculated by the Python function ```gaunt``` from the submodule ```sympy.physics.wigner```. Besides some issues related to the documentation (see https://github.com/sympy/sympy/issues/7551) I found Gaunt coefficients that should be zero.

I did check all the coefficients for given ```l1, l2``` up to ```lmax```, and ```l3``` up to ```2*lmax```. Besides the selection rule with respect to the sum of ```m1```,  ```m2```, and ```m3``` there should be an additional selection rule with respect to ```l1 + l2 + l3```. If ```l1 + l2 + l3``` is an even number, everything is fine. But if ```l1 + l2 + l3``` belongs to an odd number, the corresponding coefficient should be zero.

Unfortunately,  I found that the function ```gaunt``` does violate the selection rule with respect to the sum of the ```l``` quantum numbers. Below there is a small python script the checks the gaunts.

```python
#!/usr/bin/env python
# -*- coding: utf-8 -*-

import numpy as np

#
# GAUNT(l1, l2, l3, m1, m2, m3)
# = int do Y_{l1, m1} Y_{l2, m2} Y_{l3, m3}
#
#
from sympy.physics.wigner import gaunt
def cgval(l1, m1, l2, m2, l3, m3):
    return gaunt(l1, l2, l3, m1, m2, m3, prec=12)

if __name__=='__main__':

    lmax = 3
    lmmax = (lmax + 1)**2

    lpot = 8 * lmax
    lmpot = (lpot+1)**2

    fmt_out = '%3d | %3d %3d %3d |  %3d %3d     %3d %3d     %3d %3d | %+18.16f | %3d    %3d'

    print('lmax = %3d <=> lmmax = %3d' % (lmax, lmmax))
    print('lpot = %3d <=> lmpot = %3d' % (lpot, lmpot))
    print('\n')

    i = 0
    for l1 in range(0, lmax + 1):
        for l2 in range(0, lmax + 1):
            for l3 in range(0, lpot + 1):

                for m1 in range(-l1, l1 + 1):
                    for m2 in range(-l2, +l2+1):
                        for m3 in range(-l3, l3+1):

                            lm1 = l1*(l1 + 1) + m1 + 1
                            lm2 = l2*(l2 + 1) + m2 + 1
                            lm3 = l3*(l3 + 1) + m3 + 1

                            mok = 0
                            if m1 + m2 + m3 == 0: mok = 1

                            lok = 1
                            if (l1 + l2 +l3 )%2: lok = 0

                            cg = cgval(l1, m1, l2, m2, l3, m3)
                            if np.abs(cg) > 1.e-10:
                                i = i + 1
                                print(fmt_out %(i, lm1, lm2, lm3, l1, m1, l2, m2, l3, m3, cg, mok, lok))
```

In particular, the last two given columns are of interest since they state if the ```m``` and the ```l``` selection rule are fulfilled (in this case ```1``` will be reported) or not (```0``` will be reported.

### Supplementary material
How do I come to this conclusion? First of all, according to [1], the Gaunt coefficient is defined by

```latex
G(l1, l2, l3, m1, m2, m3) = \int do Y_{l1}^{m^1}(o) Y_{l2}^{m^2}(o) Y_{l3}^{m^3}(o) = \sqrt{\frac{(2*l1+1)(2*l2+1)(2*l3+1)}{4\pi}} Wigner3jm(l1, l2, l3, 0, 0, 0) * Wigner3jm(l1, l2, l3, m1, m2, m3)
```

at the integral over

```latex
\int do Y_{l1}^{m1}(o) Y_{l2}^{m2}(o)^* Y_{l3}^{m3}(o) = \sqrt{\frac{(2*l1+1)(2*l3+1)}{4\pi (2*l2+1)}} Clebsch(l1, l3, l2, 0, 0, 0) * Clebsch(l1, l3, l2, m1, m3, m2)
```

where Clebsch defines the Clebsch-Gordan coefficients, is related to the Gaunt coefficients because of the Condon-Shortley phase convention. In fact, both expressions are related via

```latex
\int do Y_{l1}^{m1}(o) Y_{l2}^{m2}(o) Y_{l3}^{m3}(o) = (-1)^{m2} \int do Y_{l1}^{m^1}(o) Y_{l2}^{-m2}(o)^* Y_{l3}^{m^3}(o)
```

Anyhow, the Clebsch-Gordan coefficient ```Clebsch(l1, l3, l2, 0, 0, 0)``` has to be zero if ```l1+l2+l3``` belongs to an odd number (see Ref.[1], p. 251, Eq.(32)).

Do you have any idea? Thanks in advance.

### References

[1] D. A. Varshalovic, A. N. Moskalev, and V. K. Khersonskii, "Quantum Theory of Angular Momentum",  World Scientific Publishing Co. Pte. Ltd, 2008.

**Comment by Rufflewind** [comment]
This part looks suspicious: https://github.com/sympy/sympy/blob/e7f4f1e67cadf83c057d01c7508057d789bb2e9a/sympy/physics/wigner.py#L645-L658

```py
    bigL = (l_1 + l_2 + l_3) // 2
    …
    if (2 * bigL) % 2 != 0:
        return 0
```

`bigL` is an integer since we just used `//`, so `2 * bigL` is always even!
