### ISSUE TITLE
diophantine(x**2-y**2-x*y-1)

### ISSUE THREAD

**Issue by rwst** [sympy/sympy#7671]
```
from sympy.solvers.diophantine import *
diop_solve(x**2 - y**2 - x*y - 1)
{(-38*sqrt(5)*(-4*sqrt(5) + 9)**(2*t)/5 + 17*(-4*sqrt(5) + 9)**(2*t) + 38*sqrt(5)*(4*sqrt(5) + 9)**(2*t)/5 + 17*(4*sqrt(5) + 9)**(2*t),
  -47*sqrt(5)*(-4*sqrt(5) + 9)**(2*t)/10 + 21*(-4*sqrt(5) + 9)**(2*t)/2 + 21*(4*sqrt(5) + 9)**(2*t)/2 + 47*sqrt(5)*(4*sqrt(5) + 9)**(2*t)/10),
 (-199*sqrt(5)*(-4*sqrt(5) + 9)**(2*t)/10 + 89*(-4*sqrt(5) + 9)**(2*t)/2 + 199*sqrt(5)*(4*sqrt(5) + 9)**(2*t)/10 + 89*(4*sqrt(5) + 9)**(2*t)/2,
  -123*sqrt(5)*(-4*sqrt(5) + 9)**(2*t)/10 + 55*(-4*sqrt(5) + 9)**(2*t)/2 + 55*(4*sqrt(5) + 9)**(2*t)/2 + 123*sqrt(5)*(4*sqrt(5) + 9)**(2*t)/10),
 (-521*sqrt(5)*(-4*sqrt(5) + 9)**(2*t)/10 + 233*(-4*sqrt(5) + 9)**(2*t)/2 + 521*sqrt(5)*(4*sqrt(5) + 9)**(2*t)/10 + 233*(4*sqrt(5) + 9)**(2*t)/2,
  -161*sqrt(5)*(-4*sqrt(5) + 9)**(2*t)/5 + 72*(-4*sqrt(5) + 9)**(2*t) + 72*(4*sqrt(5) + 9)**(2*t) + 161*sqrt(5)*(4*sqrt(5) + 9)**(2*t)/5)}
```

This is only a subset of all solutions which can be completely expressed as (fibonacci(2_t+1),fibonacci(2_t)). For example the solutions (5,3) and (13,8) are not covered.

**Comment by PaulElschot** [comment]
I may have hit a similar problem. When running this code:

```python
from sympy import symbols, simplify
from sympy.solvers.diophantine import diophantine
x,y,t=symbols("x y t", integer=True)

s = diophantine(-2*x**2 + 2*x + y**2 + 2*y, t)
s0 = s.pop()
for tt in range(-3,2):
    print tt, simplify(s0[0].subs(t,tt)), simplify(s0[1].subs(t,tt))
```

The output (`t x y`) is:
-3 697 984
-2 21 28
-1 1 0
0 -3 4
1 -119 168

However, for `t=0` and `t=1`, I would expect (`x y`) values in this way:

4 4
120  168

For these non negative`t` the solutions contain `-x+1`  instead of` x`, which is ok from inspection of the first two terms `-2*x**2 + 2*x == -2*x*(x - 1)`.

In this case both solutions `x` and `-x+1` are normally possible, so the question is: how do I detect this case?

In case there is a better place to discuss this, please let me know.

**Comment by jksuom** [comment]
These are the values I get using the development version:
```
In [6]: s0 = s.pop()

In [7]: s1 = s.pop()

In [8]: for tt in range(-3,2):
   ...:     print tt, simplify(s0[0].subs(t,tt)), simplify(s0[1].subs(t,tt))
   ...:     
-3 21 28
-2 4 4
-1 1 0
0 0 0
1 -3 4

In [9]: for tt in range(-3,2):
   ....:    print tt, simplify(s1[0].subs(t,tt)), simplify(s1[1].subs(t,tt))
   ...:     
-3 -20 -30
-2 -3 -6
-1 0 -2
0 1 -2
1 4 -6
```

**Comment by PaulElschot** [comment]
The development version provides two solutions, and that is a nice improvement.
The actual solution has more structure, for each t it has a pair of values for x and a pair of values for y.

I only need solutions with `1 <= x <= y` , and the first solution in dev appears to provide these.
I'll give the dev version a try.

**Comment by PaulElschot** [comment]
Thanks, the dev version here provides the improved answer.

**Comment by smichr** [comment]
The OP now gives
```python
s=FiniteSet(diophantine(x**2-y**2-x*y-1,t))
for i in range(-2,0):
  for si in s:
    for k in si:
      print(simplify(Tuple(*k).subs(t,i)))
    print()

(89, 55)
(-89, -55)
(13, 8)  <-- ok
(34, 21)
(-34, -21)
(-13, -8)

(5, 3) <-- ok
(-5, -3)
(1, 0)
(2, 1)
(-2, -1)
(-1, 0)
```
