### ISSUE TITLE
inconsistent output of diop_solve()

### ISSUE THREAD

**Issue by rwst** [sympy/sympy#7710]
Can the user expect a single solution contained in a Set or naked?

```
In [12]: diop_solve(x**2-y)
Out[12]: {(t, t**2)}

In [13]: diop_solve(x**2+y**2-z**2)
Out[13]: (2*p*q, p**2 - q**2, p**2 + q**2)
```

**Comment by Abhi58** [comment]
Hello,

I want to work on this issue. So do we need to write that `diophantine` is recommened over `diop_solve` in the docstring of diop_solve https://docs.sympy.org/latest/modules/solvers/diophantine.html#sympy.solvers.diophantine.diop_solve ?

**Comment by Abhi58** [comment]
I opened a PR please have a look.
