### ISSUE TITLE
deprecate diop_ternary_quadratic

### ISSUE THREAD

**Issue by rwst** [sympy/sympy#7711]
The capabilities of stock `diophantine()` are certainly much better, and the listing of `diop_ternary_quadratic` in the docs is quite confusing.

```
In [11]: diop_ternary_quadratic(x**2 + 3*y**2 - z**2)
Out[11]: (1, 0, 1)

In [12]: diophantine(x**2 + 3*y**2 - z**2)
Out[12]: set([(3*p**2 - q**2, 2*p*q, 3*p**2 + q**2)])
```

**Comment by oscarbenjamin** [comment]
This issue is that an internal function is not as useful as the public function that users should use. Unless I misunderstand there is nothing to fix here (except perhaps the documentation).

**Comment by smichr** [comment]
nice docstring provided:
https://github.com/sympy/sympy/blob/b176f6a1d9890b42dc361857c887992315e3d5ad/sympy/solvers/diophantine.py#L1916-L1948
