### ISSUE TITLE
roots should find the roots of x**4*I + x**2 + I

### ISSUE THREAD

**Issue by hargup** [sympy/sympy#7724]
```
In [34]: roots(x**4*I + x**2 + I, x)
Out[34]: {}
```

surprisingly if we replace `I` with variable coefficients we get an answer.

```
In [35]: roots(x**4*a + x**2 + b, x)
Out[35]: 
{sqrt(2)*sqrt(-sqrt(-4*a*b + 1)/a - 1/a)/2: 1,
 sqrt(2)*sqrt(sqrt(-4*a*b + 1)/a - 1/a)/2: 1,
 -sqrt(2)*sqrt(sqrt(-4*a*b + 1)/a - 1/a)/2: 1,
 -sqrt(2)*sqrt(-sqrt(-4*a*b + 1)/a - 1/a)/2: 1}
```

**Comment by pelegm** [comment]
I think it stands for **arbitrary EXpressions**.

**Comment by asmeurer** [comment]
The domain parameter only specifies the domain of the coefficients of the polynomial, not the roots. Roots of a polynomial in the domain ZZ might be non-integers.

**Comment by smichr** [comment]
There is another example of a 7th order unfactorable polynomial that gives no roots instead of RootOf instances at [this SO issue](http://stackoverflow.com/questions/29657654/eigenvector-does-not-work-in-sympy/29663526#29663526)

**Comment by smichr** [comment]
See also #12345 and #12421

**Comment by smichr** [comment]
> example for domains and filters

The filters use the assumption system to filter the results, basically `return [i for i in full_solution if i.is_foo]`. So this is limited by the assumption system's ability to deduce these properties. For complicated expressions it might have problems and get a None.

**Comment by oscarbenjamin** [comment]
The original example from this issue now works fine:
```julia
In [9]: roots(x**4*I + x**2 + I, x)                                                                                                            
Out[9]: 
⎧     __________         __________          ____________         ____________   ⎫
⎪    ╱ ⅈ   √5⋅ⅈ         ╱ ⅈ   √5⋅ⅈ          ╱   √5⋅ⅈ   ⅈ         ╱   √5⋅ⅈ   ⅈ    ⎪
⎨-  ╱  ─ + ──── : 1,   ╱  ─ + ──── : 1, -  ╱  - ──── + ─ : 1,   ╱  - ──── + ─ : 1⎬
⎪ ╲╱   2    2        ╲╱   2    2         ╲╱      2     2      ╲╱      2     2    ⎪
⎩                                                                                ⎭
```

I think this can probably be closed now.

**Comment by smichr** [comment]
A check to see if a test covers this case should be made.

**Comment by Anjali167-sopho** [comment]
If no one is working on this issue and the issue is still open. Can I start working on it?
Also, it would be great, if anyone could guide me as to where to start from

**Comment by jotharman** [comment]
> A check to see if a test covers this case should be made.

The function roots is not working for polynomials with degree more than 4.
 ```
In[7] : roots(x**5*I + x**1 + I, x)
Out[7] : {}
In[8] : roots(x**5*5 + x**1 + 5, x)
Out[8] : {}
```

**Comment by oscarbenjamin** [comment]
It is not always possible to express the roots of polynomials of degree more than 4:
https://en.wikipedia.org/wiki/Abel%E2%80%93Ruffini_theorem

**Comment by oscarbenjamin** [comment]
@Anjali167-sopho to fix this issue you can add a test for this polynomial in `sympy/polys/tests/test_polyroots.py`

**Comment by Jonty16117** [comment]
> roots(x**4*I + x**2 + I, x)

In my computer, it gives:
`>>> roots(x**4*I + x**2 + I, x)
{-sqrt(I/2 + sqrt(5)*I/2): 1, -sqrt(-sqrt(5)*I/2 + I/2): 1, sqrt(-sqrt(5)*I/2 + I/2): 1, sqrt(I/2 + sqrt(5)*I/2): 1}`
