### ISSUE TITLE
mpmath.plot(f) when f is Piecewise fails

### ISSUE THREAD

**Issue by hammer** [sympy/sympy#7726]
Hey,

I'm trying to plot a piecewise function and not having any luck. Here's some sample code:

```python
from sympy import Piecewise, mpmath
from sympy.abc import x
f = Piecewise((1, x > 0), (0, True))
mpmath.plot(f)
```

When I run this code, I get: `'Piecewise' object is not callable`.

NB that I've been able to plot things like `sin` and `cos` just fine.

I'm new to SymPy so my apologies if I'm missing something obvious.

Thanks,
Jeff

**Comment by hargup** [comment]
@hammer Please report the issue to [mpmath](https://github.com/fredrik-johansson/mpmath), btw sympy's plotting got fixed with https://github.com/sympy/sympy/pull/8577
