### ISSUE TITLE
Recommended installation path should be with pip

### ISSUE THREAD

**Issue by thedrow** [sympy/sympy#7763]
The README file specifies that sympy should be installed using `setup.py`.
Is there something that prevents sympy to be installed using pip?

**Comment by oscarbenjamin** [comment]
I would say that if someone is looking at the README then they have downloaded the source and should use the setup,py. However actually the README is shown on the front page on github. So absolutely pip should be listed as the default way to install.

**Comment by asmeurer** [comment]
It probably just needs better wording that the README is talking about installation *if you have downloaded the source*, and point to the installation page in the docs if you haven't and just want to install the latest released version.

**Comment by mijo2** [comment]
@asmeurer We can add something like below in the README file below or above the source installation steps:

To install sympy using PyPI you can run the following command:
``` pip install sympy ```

I think that should suffice for a user who wants the latest released version instead of installing from source.

**Comment by mijo2** [comment]
Updated string for README - 

- **Install SymPy from the GitHub source:**

To install SymPy from GitHub source, first clone SymPy using ```git```:

```sh
git clone https://github.com/sympy/sympy.git
```

Then, inside the ```sympy``` repTo install SymPy from GitHub source, first clone SymPy using ```git```:

```sh
git clone https://github.com/sympy/sympy.git
```

Then, inside the ```sympy``` repository that you just cloned, simply run:

```sh
python setup.py install
```ository that you just cloned, simply run:

```sh
python setup.py install
```

- **Install SymPy using PyPI:**

To install SymPy using PyPI you can run the following command:

```sh
pip install sympy
```
