### ISSUE TITLE
solve: can't distinguish between no solutions and arbitrary solution

### ISSUE THREAD

**Issue by cbm755** [sympy/sympy#7780]
Probably a dup, but I didn't find it.

Both of these make the same output:
````
In [147]: solve(0, x)     # 0 == 0, any x is a solution
Out[147]: []

In [148]: solve(1, x)    # 1 == 0, there are no solutions
Out[148]: []
````
This will matter with `evaluate` in merge #7778 because:
````
In [170]: solve(Eq(x, x, evaluate=False), x)     # x == x, any x is solution
Out[170]: []

In [171]: solve(Eq(x, x, evaluate=True), x)      # Eq(x,x) reduces to True
Out[171]: True
````
and:
````
In [172]: solve(Eq(x, x-1, evaluate=True), x)    #
Out[172]: False

In [173]: solve(Eq(x, x-1, evaluate=False), x)   # x == x-1, no finite solutions
Out[173]: []
````
From looking at the solver.py code, I think this last example will first do `lhs - rhs` which gives `1` and should be trying to solve 1 == 0, i.e., no solutions.  Hence I  think my opening example is important.

Presumably the issue is what happens when a symbol isn't in the expression.  For example, solve x**2 = 9 for x and y.  There is no way to tell from this output that y is arbitrary:
````
In [175]: solve(Eq(x*x,9), [x,y], set=True)
Out[175]: ([x], set([(-3,), (3,)]))

In [176]: solve(Eq(x*x,9), [x,y], dict=True)
Out[176]: [{x: -3}, {x: 3}]

In [177]: solve(Eq(x*x,9), [x,y])
Out[177]: [{x: -3}, {x: 3}]
````

**Comment by hargup** [comment]
We will be replacing `solve` by `solveset` in the next release, see #10006 . Hence we are closing issues for `solve` and opening corresponding `solveset` issues if needed.
