### ISSUE TITLE
`Interval(..) in Interval(..)` should return false

### ISSUE THREAD

**Issue by hargup** [sympy/sympy#7805]
Currently `Interval(0, 1) in Interval(0, 1)` raises `TypeError` rather the `False` should be returned because any Interval in not a member of any other interval. In general any Interval doesn't have any set as its member.

Adding a special case for Set in `Interval._contains` should do, so this is a Easy to fix task.

**Comment by gxyd** [comment]
@skirpichev 
> If other may be real - the contains method should return an unevaluated Contains object

I ratger think it should return `false` for every instance of `Set`. Please can you tell why you though so ?

**Comment by kshitij10496** [comment]
The `TypeError` is introduced via this [line](https://github.com/sympy/sympy/blob/master/sympy/sets/sets.py#L975).

- Shouldn't adding an `isinstance` condition at the beginning fix this ?
- Wouldn't it add to code completeness, if we can call `is_subset` when `Interval() in Interval()` is called ?

**Comment by rpisarev** [comment]
In current master I had have:

In [1]: from sympy import *

In [2]: Interval(0, 1) in Interval(0, 1)
Out[2]: False

Should we close this ticket? @hargup

**Comment by hargup** [comment]
> Should we close this ticket? @hargup

Thanks I it works now, I would appreciate it if you can `git bisect` and let us know the commit which introduced the fix.

**Comment by rpisarev** [comment]
Sorry, but I don't know how to use git bisect.

**Comment by hargup** [comment]
> I am ashamed.

Not knowing `git bisect` is absolutely nothing to be ashamed of, you can have a look at the [official document](https://git-scm.com/docs/git-bisect) to learn how to use it, basically you do a binary search on the history to see after which commit the behavior got the fixed.

**Comment by rpisarev** [comment]
@hargup I have read the article and done procedure. So I have had:

24672c20cc40662775ecba261ce2c150357860cf is the first bad commit
commit 24672c20cc40662775ecba261ce2c150357860cf
Author: Kshitij Saraogi <KshitijSaraogi@gmail.com>
Date:   Thu Dec 31 22:05:13 2015 +0530

    fixes #10326 Interval does not contain extended reals

:040000 040000 078ec8844260ec3d7ec61801b584d8c42a03226d 0d904e4fcf85e1bde373ef9ec89e2b3164f737f3 M	sympy

But, I have never used git bisct before. I could be wrong.

**Comment by kshitij10496** [comment]
@rpisarev I hope you mean that this commit fixed this issue.

**Comment by rpisarev** [comment]
Yes, of course!

**Comment by pelegm** [comment]
Should we add a test for this?

**Comment by hargup** [comment]
> Should we add a test for this?

Yes, #10740
