### ISSUE TITLE
Incorrect behavior with subs and second derivatives

### ISSUE THREAD

**Issue by jsoishi** [sympy/sympy#7806]
In Sympy 0.7.4.1 on my machine with Python 3.3.2, and on the sympy live shell on sympy.org (which is currently SymPy 0.7.4.1 (Python 2.7.5)), the following code 

``` python
from sympy import *
x,z,t = symbols('x, z, t')
psi = Function('psi')(x,z)
j1 = Derivative(psi,x) - Derivative(psi,z)
j1.subs(Derivative(psi,x), t)
```

gives the expected behavior, t - d psi/dx. 

However, if I do the same thing with a second derivative with respect to z, 

```
j2 = Derivative(psi,x) - Derivative(psi,z,2)
j2.subs(Derivative(psi,x), t)
```

it returns t - d^2 t/dz^2. I expect it to return t - d^2 psi/dz^2. This happens even if I make `t` a `Function` instead of a `symbol`.

**Comment by nschaeff** [comment]
I just ran into a reelated problem, with sympy 0.7.6. When running this code:

    from sympy import *
    init_printing()

    x=Symbol('x')
    y=Symbol('y')
    z=Symbol('z')
    f=Function('f')

    expr = diff(f(x,y),x,x,y)
    pprint(expr)

    e2 = expr.subs(diff(f(x,y),y,2), z)
    pprint(e2)

The call to subs() method incorrectly substitutes a df/dy with z, while we asked to substitute d2f/dy2 instead !

**Comment by chengdi123000** [comment]
Here is part of my code to solve Blasius Equation in [0,+oo) with change of variables to [-1,1]. I am using **replace** rather than **subs** or **xreplace**. I think this may be helpful.
```python

from sympy import *
U,V,x,y = symbols('U,V,x,y')
L = symbols('L')
init_printing()
get_ipython().magic(u'matplotlib inline')

# Blasius equation
beq = 2*Derivative(U(y),y,3)+Derivative(U(y),y,2)*U(y)
Eq(beq,0)

# ## substitution of variables

# from y to x

#new variable: x
#old variable: y
y2x = 2*y/(L+y)-1

# from x to y
x2y = solve(y2x-x,y)[0]

# Dictionary for change of variable

sd = zip([diff(U(y),y,i) for i in range(4)],[diff(y+V(y2x),y,i).subs({y:x2y}).simplify().doit() for i in range(4)])
sd


# Change of variables from high order derivative to low order ones.
# 
# *sympy* function **replace** is used rather than **subs** which will give incorrect result.
for sdi in sd[::-1]:
    beq = beq.replace(*sdi)
beq=beq.simplify()

# ## some hacks to generate code for chebfun.chebop in matlab
DIFF=symbols('diff')
sd2 = zip([Derivative(V(x),x,i)for i in range(4)],[DIFF(V,i) for i in range(4)])

beq2  = beq.args[-1]
for sdi in sd2[::-1]:
    beq2 = beq2.replace(*sdi)
beq2

print octave_code(beq2.subs({L:1}))

```

**Comment by asmeurer** [comment]
This issue has been fixed, I believe by https://github.com/sympy/sympy/pull/10014.

@chengdi123000 subs works for me with your expression, although you need to reverse the order of `sd` before passing it to subs, like `beq.subs(reversed(sd))`, to make sure the higher derivatives get replaced before the lower ones.
