### ISSUE TITLE
Integration of summations:

### ISSUE THREAD

**Issue by nicoguaro** [sympy/sympy#7827]
I want to compute an integral like (`n` and `N` are integers)
`integrate(summation(sin(n*x), (n,1,N)), x)`
but SymPy returns the same, i.e., it cannot interchange the summation and the integral.

For derivatives it works, though
`diff(summation(sin(n*x), (n,1,N)), x)`
returns
`Sum(n*cos(n*x), (n,1,N))` .

This feature can be useful, e.g.,  when solving differential equations with harmonic forcing.

**Comment by Shekharrajak** [comment]
What should be the answer for :
 integrate(summation(sin(n*x), (n,1,N)), x)
Should it be :
 Sum(Piecewise((0, n == 0), (-cos(n*x)/n, True)), (n, 1, N)) ?

Is there any better answer ?(without  Piecewise)
Please try to reply me @asmeurer @nicoguaro

**Comment by nicoguaro** [comment]
@Shekharrajak, yes it is. Since the limits of the summation are 1 and N you already know that n!=0.

**Comment by asmeurer** [comment]
I don't know if there's a simple way to simplify a Piecewise given some known conditions on the variables.

**Comment by nicoguaro** [comment]
I also tried with a Taylor series, and the same problem appears


    x = symbols('x')
    n = symbols('n', integer=True)
    c = symbols('c', function=True)
    integrate(Sum(c(n)*x**n, (n, 0, oo)), x)

**Comment by Shekharrajak** [comment]
Thanks @nicoguaro  @asmeurer

**Comment by Lakshya1605** [comment]
Is this still open .If yes i would like to work on this issue.Thank you

**Comment by Shekharrajak** [comment]
@Lakshya1605 , go ahead. You can also use the PR #10444

**Comment by Lakshya1605** [comment]
Please verify @asmeurer  @nicoguaro  @Shekharrajak

**Comment by gxyd** [comment]
To whoever tries to fix this issue, PR #8771 looked like a good attempt at that. Instead of starting from scratch, one can pick up the commits from that PR and eventually complete that may be.

**Comment by Ankit-Sonthalia** [comment]
Is this issue still open? If so, I would like to give it a shot.

**Comment by czgdp1807** [comment]
@ghost Yes, the issue is still unresolved. You can check the already existing PR and may be cherry pick some commits from it or just check it out in a new branch and make your changes on top of the previous ones. Check https://blog.scottlowe.org/2015/09/04/checking-out-github-pull-requests-locally/

**Comment by mijo2** [comment]
Hi @czgdp1807 since no one is currently working on this issue, I started working on it. I tried the fixes introduced in #8771 and #8929 but there were couple of problems that I ran into and since the codebase has changed while this issue was active, I would like to point them below - 

1. Last year, a new line was introduced in ```summations.py``` namely - 
        ```from sympy.calculus.singularities import is_decreasing```
    So, when I imported ```Sum``` from ```summations.py``` in ```integrals.py```, a circular import dependency was found, so to fix that I did something like below - 
        ```import sympy.concrete.summations as csm
           ...
           Sum = csm.Sum
         ```
   After that, the imports were working properly.

2. I don't know what changes were made in these past years but I noticed one thing - 
       Years ago when #8929 was implemented, a line like below - 
        ```integrate(summation(sin(n*x), (n,1,N)), x)```
        Gave output like below -
          ```Sum(Piecewise((0, Eq(n, 0)), (-cos(n*x)/n, True)), (n, 1, N))```
        
        But when I made the changes today, I got output - 
           ```Sum(Piecewise((-cos(n*x)/n, Ne(n, 0)), (0, True)), (n, 1, N))```

        Now, both the outputs are essentially the same, so should I update the test cases for what output I am getting today or should I construct an OR expression and try to see if the output is one of the above?
