### ISSUE TITLE
Deprecation of lambdify converting `Matrix` -> `numpy.matrix`

### ISSUE THREAD

**Issue by jcrist** [sympy/sympy#7853]
This issue is for documenting the deprecation cycle for the default behavior of lambdify to convert `Matrix` to `numpy.matrix`. Per the numpy devs, `array` is always preferable to `matrix`, and many scipy functions only work with `array`. To avoid breaking code after the release, the following deprecation cycle will be observed:

1. Prior to release of 0.7.6 (versions up to and including 0.7.5) lambdify converted `Matrix` to `numpy.matrix` by default.

2. In 0.7.6, expressions that contain Matrices throw a SymPyDeprecationWarning warning the user of the upcoming change. The user is advised to set `modules=[{'ImmutableMatrix': numpy.array}, 'numpy']`, which will avoid the deprecation warning and result in `Matrix->array`. If they will be using `lambdify` often, a recommendation to apply `functools.partial` to set the kwarg permanently is also given.

3. For the release of 0.7.7, `Matrix` -> `array` will be the new behavior.

The modules kwarg is set to `[{'ImmutableMatrix': numpy.array}, 'numpy']` for some uses of `lambdify` internally. For the release of 0.7.7 the use of modules in this case should be reverted.

For more rational on why this change was made, see #7284, and the implementing PR #8034.

**Comment by richardotis** [comment]
#9657 resolves this issue.

**Comment by asmeurer** [comment]
Closing this issue, since the deprecated feature was removed.
