### ISSUE TITLE
Nth root mod giving wrong solutions

### ISSUE THREAD

**Issue by isuruf** [sympy/sympy#7858]
`nthroot_mod(9, 12, 36)` gives that there are no solutions, but 9 is a solution to `x ^ 12 = 9 mod 36`

**Comment by zb3** [comment]
Well, the problem is still there...
```
>>> is_nthpow_residue(676,3,5364)
False
>>> pow(574,3,5364)
676
```

The point is - it shouldn't return anything if the assumptions are not met.

**Comment by rd13123013** [comment]
The current code for  ``is_nthpow_residue`` uses Euler’s Criterion but this criteria assumes that ``n`` needs to have atleast one primitive root,  so we cannot use it for the numbers which do not have a primitive root. 36 and 5364 both do not have any primitive root hence function fails on this. We need to work further on behavior of function when ``n`` does not have any primitive root.  I am willing to work on this issue further.

**Comment by rd13123013** [comment]
We can use Chinese remainder theorem to enable function to work with m which don't have a primitive root . i seek little advice from senior member on this.

**Comment by jksuom** [comment]
@rd13123013 It seems to me that you are on the right track. It should be enough to consider separately the prime power factors of ``m``. Only powers of 2 need special attention. Please, go ahead.

**Comment by rd13123013** [comment]
@jksuom

My idea was to check

    for all (p^k divides m ) if   s_nthpow_residue( a , n , p^k)  holds then it holds for m else not 

    is_nthpow_residue( 676 , 3 , 5364 )

    But in case of 5364 = 2^2 * 3^2 * 149 it do not hold for 2^2 , but it should have

    I think power of two needs to be treated differently when power >= 3 , can u elaborate how we do that too ( i m not getting the part where they say 5 is nearly primitive root for opwer >= 3 ) ?

Am i missing something obvious or doing it wrong ?

**Comment by isuruf** [comment]
Yes, you also have to special case `p | a`.
There's an implementation in SymEngine which calculates the nthroot_mod of `a` for any integer `a`, `n`. 
Used several literature which is mentioned there. You can read the literature or go through the code. https://github.com/symengine/symengine/blob/master/symengine/ntheory.cpp#L1166
