### ISSUE TITLE
Sum (and similar) should have a way to factor out constant terms

### ISSUE THREAD

**Issue by smichr** [sympy/sympy#7902]
https://groups.google.com/forum/#!topic/sympy/MtxkXJ6h3-M gives an example where not having an _eval_solve method for Sum makes solve (or user) do things that such a method should probably do (i.e. isolate a factor from a sum that is independent of the summation variable(s)). Wish list:
- it would be nice to have a way to get constant term outside of a summation so Sum(a_x, (x, 1, 2)) could be rewritten as a_Sum(x, (x, 1, 2)) -- would this be a use case for `expand_basic`?
- solve should have a way to solve such expressions; it seems like having an `_eval_solve` system might be the best way to do this since Sum should know how to solve for a symbol that it contains.
- expand_basic could perhaps change Sums into a form where the factors independent of the summation are placed outside the Sum as `constant*Sum(i, (i, 1, 10))`.

**Comment by pablocobelli** [comment]
I second this. It is indeed a very necessary feature for sympy and smichr has already found a solution.

**Comment by zanzibar7** [comment]
Currently, this is partially implemented, but easy to break
```
>>> from sympy import *
>>> from sympy.abc import x,a
>>> (Sum(3*x,(x,1,10))).factor()
3*Sum(x, (x, 1, 10))
>>> (5*Sum(3*x,(x,1,10))).factor()
5*Sum(3*x, (x, 1, 10))
```

**Comment by zanzibar7** [comment]
I'd appreciate any suggestions on how to improve this pull request.  It works, but I'm concerned it isn't adequately recursive.

**Comment by smichr** [comment]
We should put comments regarding the PR on the PR, not the issue. I will add one there.

**Comment by smichr** [comment]
The recent PR by @zanzibar7 now allows Sums to be factored.

**Comment by smichr** [comment]
closed via #11481

**Comment by sschuldenzucker** [comment]
Is there some way to do this explicitly (rather than in the context of `simplify()`)?

I get what I perceive as an inconsistency:
```
>>> from sympy import *; from sympy.abc import x, y
>>> expr = Sum(x * y, (x, 1, 3))
>>> simplify(expr)
y*Sum(x, (x, 1, 3))
>>> collect(expr, y)
Sum(x*y, (x, 1, 3))
```

Use case: When we want to collect one particular variable (out of many).

**Comment by oscarbenjamin** [comment]
I'm not sure I understand what it is that you want but does this do it?
```python
In [191]: expr = Sum(x * y, (x, 1, 3))

In [192]: expr
Out[192]: 
  3      
 ___     
 ╲       
  ╲      
  ╱   x⋅y
 ╱       
 ‾‾‾     
x = 1    

In [193]: factor_terms(expr)
Out[193]: 
    3    
   ___   
   ╲     
    ╲    
y⋅  ╱   x
   ╱     
   ‾‾‾   
  x = 1 
```

**Comment by sschuldenzucker** [comment]
Interesting! Yes, this is what I wanted! Thanks! (this collects *all* the independent factors from the sum, instead of only the ones specified, but that's also good for me)

There still seems to be an inconsistency, though, in how `collect()` treats `Sum` vs `Plus`:

```
>>> from sympy.abc import x, y, i
>>> collect(Sum(x**i * y, (i, 1, 3)), y)
Sum(x**i*y, (i, 1, 3))
>>> collect(x**1 * y + x**2 * y + x**3 * y, y)
y*(x**3 + x**2 + x)
```

Note that the two expressions are equivalent, but `collect()` only successfully collects `y` in the variant without `Sum()`.

Doing `factor_terms()` before `collect()` yields the correct result, but I feel it shouldn't be needed:
```
>>> collect(factor_terms(Sum(x**i * y, (i, 1, 3))), y)
y*Sum(x**i, (i, 1, 3))
```

**Comment by oscarbenjamin** [comment]
It looks like `collect` causes the `Sum` to evaluate which I don't think should happen. Could you open a new issue about that?

**Comment by sschuldenzucker** [comment]
Uhm, tbf I don't quite get what you mean by that. In the offending 
example, `collect(Sum(x**i * y, (i, 1, 3)), y)`, the Sum is returned 
unmodified.

I'm not familiar with the internals of sympy though; I'm afraid I don't 
have enough details on this to open a useful issue.
