### ISSUE TITLE
solve(Eq(sin(2*x)*cos(x)+cos(2*x)*sin(x), 1))

### ISSUE THREAD

**Issue by satels** [sympy/sympy#7914]
Dnot found solution for

sin(2_x)_cos(x)+cos(2_x)_sin(x) == 1

The solution must be:

http://www.wolframalpha.com/input/?i=sin%282*x%29*cos%28x%29%2Bcos%282*x%29*sin%28x%29%3D1

**Comment by hargup** [comment]
Nope, this does work with solveset. @aktech you should take a note of it.

**Comment by Shekharrajak** [comment]
Answer should be this : 
`ImageSet(Lambda(_n, 2*_n*pi - pi/2), Integers()) U ImageSet(Lambda(_n, 2*_n*pi + pi/6), Integers()) U ImageSet(Lambda(_n, 2*_n*pi + 5*pi/6), Integers())
`
Isn't it ?

**Comment by oscargus** [comment]
`solveset(sin(2*x)*cos(x)+cos(2*x)*sin(x)- 1, x)` now gives 
![image](https://user-images.githubusercontent.com/8114497/53112579-d5f00700-353f-11e9-8496-d0491e6274e8.png)

which seems to correspond with Wolfram Alpha. (At least it gives that using the #16033 PR...)

**Comment by oscarbenjamin** [comment]
Also solve now finds these solutions without rewriting
```julia
In [1]: solve(Eq(sin(2*x)*cos(x)+cos(2*x)*sin(x), 1))                                                                                          
Out[1]: 
⎡-π                                                      ⎤
⎢───, ⅈ⋅(log(2) - log(-√3 + ⅈ)), ⅈ⋅(log(2) - log(√3 + ⅈ))⎥
⎣ 2                                                      ⎦
```

I think this can be closed.
