### ISSUE TITLE
review Piecewise_eval_template_is_attr

### ISSUE THREAD

**Issue by smichr** [sympy/sympy#7932]
The logic is:

return True if all True
return False if all False
return `when_multiple` if True and False present
None if a None is encountered and none of the above were met

For example  for Piecewise.is_bounded and is_zero:
if the args were T, F, None the is_bounded value would be F
if the args were T, None, F the is_bounded value would be None

For Piecewise.is_nonzero
if the args were T, F, None the is_bounded value would be T
if the args were T, None, F the is_bounded value would be None

This can't be right. Is the logic of its template routine supposed to be the same as AssocOp?

**Comment by oscarbenjamin** [comment]
@smichr is this still relevant?

**Comment by smichr** [comment]
> @smichr is this still relevant?

I don't think so: there is no `when_multiple` anymore:
```python
def _eval_template_is_attr(self, is_attr):
        b = None
        for expr, _ in self.args:
            a = getattr(expr, is_attr)
            if a is None:
                return
            if b is None:
                b = a
            elif b is not a:
                return
        return b
```
