### ISSUE TITLE
MeijerG integration: `_check_antecedents` internals produce NaN's

### ISSUE THREAD

**Issue by cbm755** [sympy/sympy#7942]
Working on pr #7834, I found some tests caused `0/0` NaN's to appear in `_check_antecedents` of meijerint.py.  These are involved internally in comparisons like `lambda_c > 0` (where `lambda_c` was sometimes NaN).

Currently such comparisons are false but in pr #7834 they will raise TypeError.

Its easy enough to ensure this is still the case but perhaps those NaN's are indicative of some other issue beyond my understanding of MeijerG.  I left lots of comments in my workaround.  See commit 258b110449e0bbc696552c1ece10379211849695.

**Comment by oscarbenjamin** [comment]
@cbm755 is this still relevant?

**Comment by smichr** [comment]
> Currently such comparisons are false but in pr #7834 they will raise TypeError.

In master TypeError is raised when nan is used in a relational. So until such an example that raises this error is found, this issue closed.
