### ISSUE TITLE
Some comments on sympy.physics.optics.waves

### ISSUE THREAD

**Issue by GeorgeSalt** [sympy/sympy#7944]
1.  Documentation indicates (and trial verifies) that when two TWave objects (A1, f phi1) and (A2,f,phi2) are added (superimposed) the resulting TWave object has phase ph1+phi2.  This is incorrect.
   The correct form is:
   w1+w2=A3_sin(wt+phi3) 
   where: tan(phi3)=(A1_sin(phi1)+A2_sin(phi2))/(A1_cos(phi1)+A2*cos(phi2))
   A thorough derivation of this formula can be found in the book "Light" by R.W. Ditchburn, pages 43-45 (Dover edition).
2.  Operations such as w1+w2+w3 produce a wave object with the correct amplitude.  I assume this is done by repeatedly applying the addition method?  Please note that there is an explicit formula for this case and it may be more computationally efficient.  Again, see Ditchburn.
3.  The TWave object lacks spatial frequency or wave number (usually denoted as kappa).
   The correct form is w=A_sin(w_t - kappa_f(x,y,z) + phi).  For a plane wave, f(x,y,z)=alpha_x+beta_y+gamma_z where alpha**2+beta**2+gamma**2==1.  One can also define f for spherical waves or other wave surfaces.

Once I'm up to speed on the github infrastructure I'd like to contribute to this module.  Do you have any preference for the way I submit code for review and comment?

**Comment by oscarbenjamin** [comment]
Looks like this should have been closed when #7944 was merged...
