### ISSUE TITLE
Simplifying logic and equality constraints

### ISSUE THREAD

**Issue by aldanor** [sympy/sympy#7950]
``` python
>>> x = sympy.Symbol('x')
>>> sympy.simplify_logic(sympy.And(sympy.Eq(x, 1), sympy.Eq(x, 2)))
And(x == 1, x == 2)
```

Wouldn't one expect it to be just `False` since `x` cannot be simultaneously equal to two different values? If not, is there any way to simplify it to `False`, at least in the case when `x` is an integer?

Could be somewhat related: https://code.google.com/p/sympy/issues/detail?id=4009

**Comment by czgdp1807** [comment]
The issue still persists on `master`.

**Comment by oscargus** [comment]
Seems to have been solved at some stage as it simplifies to False on the current master. #21854 adds a test for it and closes this when merged.
