### ISSUE TITLE
Relational: `_eval_sides` makes inequality decisions based on `.evalf`

### ISSUE THREAD

**Issue by cbm755** [sympy/sympy#7957]
Seems to me there is a potential for erroneously concluding an inequality is true or false when its only so to the precision of the `evalf` code.  Although I don't have such a counterexample, and maybe evalf is robust to (all?) such things.

If I remove this bit of the code, I get a failures (maybe even just one?) in `test_matrix_norm` of `matrix/tests/test_matrices.py'.  Update: cannot reproduce right now.

TODO: get the actual failing test, my recollection was it looked more like a failure to simplify rather than something that really needed numerical evaluation.

**Comment by jcrist** [comment]
@cbm755 : can this be closed?

**Comment by cbm755** [comment]
Looks like, thanks.
