### ISSUE TITLE
Solve system of inequalities 2*x**2 + 5*x + 20 <= 0, x >= 1.5 error exception

### ISSUE THREAD

**Issue by satels** [sympy/sympy#7982]
inequals = [2_x__2 + 5_x + 20 <= 0, x >= 1.5]

vars = [x]

solve(inequals, vars)

Traceback (most recent call last): File "<string>", line 1, in <module> File "/base/data/home/apps/s~sympy-live-hrd/43.373169527249054993/sympy/sympy/solvers/solvers.py", line 688, in solve symbols=symbols) File "/base/data/home/apps/s~sympy-live-hrd/43.373169527249054993/sympy/sympy/solvers/inequalities.py", line 436, in reduce_inequalities

poly_reduced.append(reduce_rational_inequalities([exprs], gen, assume)) File "/base/data/home/apps/s~sympy-live-hrd/43.373169527249054993/sympy/sympy/solvers/inequalities.py", line 214, in reduce_rational_inequalities solution = solution.evalf() AttributeError: 'EmptySet' object has no attribute 'evalf'

// edited by @skirpichev:

``` python
In [2]: solve([2*x**2 + 5*x + 20 <= 0, x >= 1.5], x)
AttributeError                            Traceback (most recent call last)
<ipython-input-2-5dcf60f7d443> in <module>()
----> 1 solve([2*x**2 + 5*x + 20 <= 0, x >= 1.5], x)
... inequalities.py in reduce_rational_inequalities(exprs, gen, relational)
    262 
    263     if not exact:
--> 264         solution = solution.evalf()
    265 
    266     if relational:

AttributeError: 'EmptySet' object has no attribute 'evalf'
```

**Comment by aktech** [comment]
@skirpichev  @satels 

It returns False because the expression `2*x**2 + 5*x + 20` is positive for any value of `x`.
Reason: for the given quadratic, coefficient of `x**2` is positive and Discriminant is negative, this is a  sufficient condition for a quadratic expression to be positive.
```python
In [3] solve(2*x**2 + 5*x + 20 <= 0,x)
Out[3] False
In [4] solve(2*x**2 + 5*x + 20 >= 0,x)
Out[4] And(-oo < x, x < oo)
```

> Other
solve([x3 - 8.88*x2 - 56.08*x/5 - 106 >= 0, x - 1 <= 0], [x])

```python
In [3]: solve(x**3 - 8.88*x**2 - 56.08*x/5 - 106 >= 0,x)
Out[3]: And(10.8216004247828 <= x, x < +inf)
```

**Comment by skirpichev** [comment]
@aktech, please try to understand the issue first.

**Comment by aktech** [comment]
@skirpichev 
> @aktech, please try to understand the issue first.

.

> In [15]: solve([2*x**2 + 5*x + 20 <= 0, x >= S(3)/2], x)
Out[15]: False

I have gone through this in a debugger, I don't see an exception.
I had understood the issue, I have not given the example for system of equation (in comment above) in the issue, as for a system of equation to have a solution every equation must have a solution.
Then how can we expect the solution for this system: `2*x**2 + 5*x + 20 <= 0`, `x >= S(3)/2` when this equation`2*x**2 + 5*x + 20 <= 0` has no real solution?

**Comment by skirpichev** [comment]
> I have gone through this in a debugger, I don't see an exception.

Last attempt.  Please read the issue first.

**Comment by aktech** [comment]
Sorry, I mistakenly wrote "inequality" as "equation". I have updated my comment.
