### ISSUE TITLE
Indexed should work with subs on a container

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#7985]
See http://stackoverflow.com/questions/25669581/lambdas-operating-on-containers-in-sympy/25693303#25693303. Ideally one could just do 

```py
d = IndexedBase('d')
l = Lambda(d, d[1] + d[2])
l(Dict({1: x, 2: y}))
```

A hand-grown solution like I have in my answer there requires a lot of tricks which have already been figured out with Indexed (and I probably missed some as well).

**Comment by ashish-belokar** [comment]
Hello,
Is this issue fixed ?

**Comment by moorepants** [comment]
No, it does not seem the issue is fixed. There is work in this PR to address it: https://github.com/sympy/sympy/pull/8065

**Comment by zanzibar7** [comment]
I'm working on an issue with subs, and have encountered the following code in test_indexed.py which I do not understand.

```
def test_IndexedBase_subs():
    i, j, k = symbols('i j k', integer=True)
    a, b, c = symbols('a b c')
    A = IndexedBase(a)
    B = IndexedBase(b)
    C = IndexedBase(c)
    assert A[i] == B[i].subs(b, a)
    assert isinstance(C[1].subs(C, {1: 2}), type(A[1]))
```
The test passes, but `C[1].subs(C, {1: 2})` seems to evaluate to `{1: 2}[1]`.  What's that supposed to mean?  My best interpretation is that we really want `C[2]` out of this evaluation, but that's not what we're getting.

**Comment by asmeurer** [comment]
You can look at the discussion on the PR. The idea is that subs should not necessarily evaluate expressions automatically (doit() on that should give the final answer 2).
