### ISSUE TITLE
define public names for NumberSymbols

### ISSUE THREAD

**Issue by smichr** [sympy/sympy#8062]
While some symbols are defined, 

```
>>> E
E
```

others are not

```
>>> Catalan
<class 'sympy.core.numbers.Catalan'>
>>> EulerGamma
<class 'sympy.core.numbers.EulerGamma'>
>>> GoldenRatio
<class 'sympy.core.numbers.GoldenRatio'>
```

Would it be a good idea to define these like `catalan = Catalan, eulergamma = EulerGamma and goldenratio = GoldenRatio` like other constants? (Of course, they can already be accessed through S like S.Catalan, but S.Pi can also be accessed as pi, which is nice.)

**Comment by aka001** [comment]
Why the PR is not merged? :/

**Comment by skirpichev** [comment]
> Why the PR is not merged?

Please read this thread first.

**Comment by aka001** [comment]
@skirpichev Okay, just read it. The PR didn't pass travis CI, sorry I didn't see that.

**Comment by skirpichev** [comment]
> Okay, just read it.

No, here is the [answer](https://github.com/sympy/sympy/issues/8062#issuecomment-56259532).

**Comment by aka001** [comment]
> No, here is the answer.
Okay. :thumbsup:

**Comment by asmeurer** [comment]
Shouldn't this be closed?

**Comment by skirpichev** [comment]
If you are sure this idea is bad.

**Comment by arjunc77** [comment]
@debugger22 this issue seems to be fixed on master. I see the travis build passing.

**Comment by Smit-create** [comment]
I get the following results on the current master:
```
>>> from sympy import *
>>> E
E
>>> Catalan
Catalan
>>> EulerGamma
EulerGamma
>>> GoldenRatio
GoldenRatio
>>> EulerGamma is S.EulerGamma
True
>>> GoldenRatio is S.GoldenRatio
True
>>> Catalan is S.Catalan
True
```
@oscarbenjamin  The issue seems to be fixed and I think it can be closed.
