### ISSUE TITLE
Throwing PolynomialDivisionFailed.

### ISSUE THREAD

**Issue by jiegec** [sympy/sympy#8067]
I'm calculating ode:
diffeq = Eq(f(t).diff(t),10-5/18*f(t)*f(t))
dsolve(diffeq)

It throws a PolynomialDivisionFailed.

Well, actually this is a first-order nonlinear ordinary differential equation, and it is not supported.

Hope sympy to be a better library and support this kind of ode!

**Comment by leosartaj** [comment]
Why was this closed @jiegec?

**Comment by jiegec** [comment]
@leosartaj Already fixed in the newest version.

**Comment by leosartaj** [comment]
Ok.
