### ISSUE TITLE
The probability function does not handle expressions like `b>=b`

### ISSUE THREAD

**Issue by pelegm** [sympy/sympy#8129]
I am not sure whether this is a bug or a feature request, but the documentation hints that this is a bug.

According to the docstring of `sympy.stats.rv.probability`, that function returns the _probability that a condition is true_, where the `Parameters` section clarifies that a "condition" is a _Relational containing RandomSymbols_ (note that the docstring calls that parameter `expr`, which is inconsistent with the function's signature).

However, if `a` and `b` are both `RandomSymbol`s, `a>b` and `a>a+b` are both relationals containing a random symbol, but `b>b` or `b>=b` or `b>=b+1` are not (these are simply booleans), so `P(b>=b)` fails. Traceback:

``` pytb
Traceback (most recent call last):
  File "<ipython-input-73-71784435f0fc>", line 1, in <module>
    P(b>=b)
  File "sympy/stats/rv.py", line 621, in probability
    result = pspace(condition).probability(condition, **kwargs)
AttributeError: 'NoneType' object has no attribute 'probability'
```

This can be solved in one of two ways which make sense, in my opinion:
1. `b>=(b+1)` may be a relational instead of boolean, which is consistent with `b>=b+a`, so that `P(...)` will know how to handle it
2. `P(...)` may return 1 for True boolean and 0 for False boolean

**Comment by pelegm** [comment]
Something is now different. Suddenly relationals containing RandomSymbols do not autosimplify. `b>b` is not `False` and `b>=b` is not `True`. Is that a new bug, or a solution for this issue? @shivamvats, are you behind this?

**Comment by shivamvats** [comment]
I am not. But that solves the issue, I guess.

**Comment by pelegm** [comment]
OK, so I'll add tests and only then close it.

**Comment by shivamvats** [comment]
That' d be great.

**Comment by SJCaldwell** [comment]
Is this still open? I'll take it if so.

**Comment by asmeurer** [comment]
You'll have to check, but I suspect that https://github.com/sympy/sympy/pull/10053/files fixed this.

**Comment by pelegm** [comment]
The probability function indeed returns 1 for True and 0 for False, and this is an implementation of option 1 described above. You may check if the PR linked by @asmeurer includes a relevant test, and if not, add one, and then close this issue.

**Comment by pelegm** [comment]
It also works perfectly (it seems) for `RandomSymbol` relationals.

**Comment by sarthak268** [comment]
please assign me this

**Comment by shivamvats** [comment]
@sarthak268 Looks like it has been solved. Can you add a relevant test for it?

**Comment by madan96** [comment]
@shivamvats Can you please take a look at the test cases I have added?
