### ISSUE TITLE
Plotting does not work with piecewise functions

### ISSUE THREAD

**Issue by ClemensFMN** [sympy/sympy#8140]
The following code yields an error (both 0.7.5 and git)

    from sympy import *
    from sympy.plotting import *
    from sympy.stats import *

    x = symbols('x')
    fx = Piecewise( (1, x<1), (0, True))
    plot(fx)

Error message is below. The issue came up in this discussion: https://groups.google.com/forum/?hl=de#!topic/sympy/rlNZIQLY5qk and seems to exist both in python 2.7 & python 3.

Error message

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/usr/lib/python2.7/dist-packages/IPython/utils/py3compat.pyc in execfile(fname, *where)
    202             else:
    203                 filename = fname
--> 204             __builtin__.execfile(filename, *where)

/home/cnovak/Desktop/piecewise_simple.py in <module>()
     15 
     16 
---> 17 plot(fx)

/home/cnovak/sympy/sympy/plotting/plot.pyc in plot(*args, **kwargs)
   1278     plots = Plot(*series, **kwargs)
   1279     if show:
-> 1280         plots.show()
   1281     return plots
   1282 

/home/cnovak/sympy/sympy/plotting/plot.pyc in show(self)
    183             self._backend.close()
    184         self._backend = self.backend(self)
--> 185         self._backend.show()
    186 
    187     def save(self, path):

/home/cnovak/sympy/sympy/plotting/plot.pyc in show(self)
   1016 
   1017     def show(self):
-> 1018         self.process_series()
   1019         #TODO after fixing https://github.com/ipython/ipython/issues/1255
   1020         # you can uncomment the next line and remove the pyplot.show() call

/home/cnovak/sympy/sympy/plotting/plot.pyc in process_series(self)
    895             # Create the collections
    896             if s.is_2Dline:
--> 897                 collection = self.LineCollection(s.get_segments())
    898                 self.ax.add_collection(collection)
    899             elif s.is_contour:

/home/cnovak/sympy/sympy/plotting/plot.pyc in get_segments(self)
    503             f_start = f(self.start)
    504             f_end = f(self.end)
--> 505             sample([self.start, f_start], [self.end, f_end], 0)
    506             return list_segments
    507 

/home/cnovak/sympy/sympy/plotting/plot.pyc in sample(p, q, depth)
    477                 #depth of 6. We are not using linspace to avoid aliasing.
    478                 elif depth < 6:
--> 479                     sample(p, new_point, depth + 1)
    480                     sample(new_point, q, depth + 1)
    481 

/home/cnovak/sympy/sympy/plotting/plot.pyc in sample(p, q, depth)
    477                 #depth of 6. We are not using linspace to avoid aliasing.
    478                 elif depth < 6:
--> 479                     sample(p, new_point, depth + 1)
    480                     sample(new_point, q, depth + 1)
    481 

/home/cnovak/sympy/sympy/plotting/plot.pyc in sample(p, q, depth)
    477                 #depth of 6. We are not using linspace to avoid aliasing.
    478                 elif depth < 6:
--> 479                     sample(p, new_point, depth + 1)
    480                     sample(new_point, q, depth + 1)
    481 

/home/cnovak/sympy/sympy/plotting/plot.pyc in sample(p, q, depth)
    477                 #depth of 6. We are not using linspace to avoid aliasing.
    478                 elif depth < 6:
--> 479                     sample(p, new_point, depth + 1)
    480                     sample(new_point, q, depth + 1)
    481 

/home/cnovak/sympy/sympy/plotting/plot.pyc in sample(p, q, depth)
    477                 #depth of 6. We are not using linspace to avoid aliasing.
    478                 elif depth < 6:
--> 479                     sample(p, new_point, depth + 1)
    480                     sample(new_point, q, depth + 1)
    481 

/home/cnovak/sympy/sympy/plotting/plot.pyc in sample(p, q, depth)
    477                 #depth of 6. We are not using linspace to avoid aliasing.
    478                 elif depth < 6:
--> 479                     sample(p, new_point, depth + 1)
    480                     sample(new_point, q, depth + 1)
    481 

/home/cnovak/sympy/sympy/plotting/plot.pyc in sample(p, q, depth)
    495                 #value) or the three points are not almost collinear.
    496                 elif (p[1] is None or q[1] is None or new_point[1] is None
--> 497                         or not flat(p, new_point, q)):
    498                     sample(p, new_point, depth + 1)
    499                     sample(new_point, q, depth + 1)

/home/cnovak/sympy/sympy/plotting/plot.pyc in flat(x, y, z, eps)
   1090     vector_b = z - y
   1091     dot_product = np.dot(vector_a, vector_b)
-> 1092     vector_a_norm = np.linalg.norm(vector_a)
   1093     vector_b_norm = np.linalg.norm(vector_b)
   1094     cos_theta = dot_product / (vector_a_norm * vector_b_norm)

/usr/lib/python2.7/dist-packages/numpy/linalg/linalg.pyc in norm(x, ord, axis)
   2054     # Check the default case first and handle it immediately.
   2055     if ord is None and axis is None:
-> 2056         return sqrt(add.reduce((x.conj() * x).real, axis=None))
   2057 
   2058     # Normalize the `axis` argument to a tuple.

AttributeError: sqrt

**Comment by hargup** [comment]
fixed with https://github.com/sympy/sympy/pull/8577
