### ISSUE TITLE
multiplicity(2, 0) of ntheory gives answer 0

### ISSUE THREAD

**Issue by vaibhav4595** [sympy/sympy#8159]

**Comment by gxyd** [comment]
@vaibhav4595 according to the definition on wikipedia "In mathematics, the multiplicity of a member of a multiset is the number of times it appears in the multiset."  http://en.wikipedia.org/wiki/Multiplicity_(mathematics) . So in this case the multiset will be the set of primefactors of  0 , now primefactos(0) returns [] l. So i think it should rather return an Error. I am not sure regarding which error it should return.
