### ISSUE TITLE
zero=True assumption is ignored?

### ISSUE THREAD

**Issue by pelegm** [sympy/sympy#8167]
For `a = Symbol('a', zero=True)`, the following happen:
1. `a == 0` returns `False`
2. `a.evalf()` returns `a` (why not 0?)
3. while `limit((E**0)**x, x, oo)` returns 1, `limit((E**a)**x, x, oo)` raises `PoleError: Don't know how to calculate the limit(exp(a/x), x, 0, dir=+), sorry.`

Adding `real=True` to `a`'s construction does not help.

(1.) and (2.) and (3.) occur also when `a = Symbol('a', real=True, positive=False, negative=False)`.

I am not sure if (1.) is a bug, as I am not entirely sure what the `==` should really mean here. But if `a >= 0` returns `True` and `a > 0` returns `False`, then clearly `a` could be evaluated to `0` only, and the limit should work.

**Comment by pelegm** [comment]
The bug is now different:
```python
>>> x = Symbol('x', real=True)
>>> a = Symbol('a', zero=True)
>>> limit((E**a)**x, x, oo)
exp(oo*a)
```
but the result should be `1`. I guess it is so since `(E**a)**x` autosimplifies to `exp(a*x)`, ignoring the fact that `a` is `zero`.

**Comment by leosartaj** [comment]
I would like to work on this bug. A simple check can be added in the 'doit' function of the Limit class, to substitute all the symbols that are equal to zero and then simply compute the limit or there can be a better approach?

**Comment by Shekharrajak** [comment]
`Sympy ` treat zero assumption means   ` nonnegative & nonpositive & real`.But  `Sympy` doesn't  know  that is `0`.It is not defined anywhere in `Sympy`.
In this line ` x = Symbol('x' ,zero=True)`  , x is treated as symbol only during execution and didn't take its value.

**Comment by czgdp1807** [comment]
The unfixed parts of the issues are,
```python
>>> solve(Eq(x, x), x)
[]
>>> solve(Eq(a, 0), x)
[]
```

**Comment by oscarbenjamin** [comment]
> The unfixed parts of the issues are,
> 
> ```python
> >>> solve(Eq(x, x), x)
> []
> >>> solve(Eq(a, 0), x)
> []
> ```

Those both look fine to me.

**Comment by czgdp1807** [comment]
Attaching a `Could Close` label to it. If others agree with the results in https://github.com/sympy/sympy/issues/8167#issuecomment-565327214 then this issue can be closed.

**Comment by czgdp1807** [comment]
Closing in reference to https://github.com/sympy/sympy/issues/8167#issuecomment-578478589
Thanks for contributions. If there is a need please feel free to re-open this issue or just let us know if you are unable to do so.
