### ISSUE TITLE
Solving x**2-1 = (x-1)*(x+1) yields no results

### ISSUE THREAD

**Issue by pelegm** [sympy/sympy#8168]
For some reason,

``` python
solve(Eq(x**2-1, (x-1)*(x+1)))
```

returns an empty list. And so does

``` python
solve(Eq(x**2-1, (x-1)*(x+1)), x)
```

I'm not sure about the reason or the main ideology here, but WolframAlpha seems to agree that `solve x**2-1 = (x-1)*(x+1)` should be something like `all values of x are solutions`.

**Comment by oscarbenjamin** [comment]
The solve API doesn't have any way to return infinite solutions. It could maybe do so with arbitrary constants (like dsolve).

**Comment by oscarbenjamin** [comment]
As it stands an empty set is solve's way of saying that there are infinitely many solutions so what you see here is correct behaviour.

**Comment by asmeurer** [comment]
This is why we have solveset. I don't think solve will ever support infinite solution sets, except in the cases where they are parameterized by symbols already in the equation set.
