### ISSUE TITLE
Implement symmetric difference for finite sets

### ISSUE THREAD

**Issue by pelegm** [sympy/sympy#8179]
In python,
```python
set([1,2,3]) ^ set([2,3,4])  ## returns {1, 4}
```

Why not in sympy as well?
```python
FiniteSet(1,2,3) ^ FiniteSet(2,3,4)  ## should return FiniteSet(1,4)
```

For that, all we need is to write `__xor__`.

I'd recommend writing a `.symmetric_difference` method, and then call it from `.__xor__`.

**Comment by hargup** [comment]
This should be easy to fix.

**Comment by kaichogami** [comment]
I am new to SymPy and I would like to work on this starter bug to start contributing as well as to get to know about the codebase.

**Comment by hargup** [comment]
> I am new to SymPy and I would like to work on this starter bug to start contributing as well as to get to know about the codebase.

Great, go ahead, make changes, send a pull request and ask questions when in doubt.
