### ISSUE TITLE
KeyError with dsolve and a system of ODEs

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#8193]
```
In [1]: V, I = symbols("V I", cls=Function)

In [2]: RC, t, C, Vs, L, R1, V0, I0 = symbols("RC t C Vs L R1 V0 I0")

In [3]: system = [Eq(V(t).diff(t), -1/RC*V(t) + I(t)/C), Eq(I(t).diff(t), -R1/L*I(t) - 1/L*V(t) + Vs/L)]

In [4]: ics = {V(0): V0, I(0): I0}

In [5]: dsolve(system, [V(t), I(t)], ics=ics)
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-5-2ec11ceb3916> in <module>()
----> 1 dsolve(system, [V(t), I(t)], ics=ics)

/Users/aaronmeurer/Documents/python/sympy/sympy-scratch/sympy/solvers/ode.py in dsolve(eq, func, hint, simplify, ics, xi, eta, x0, n, **kwargs)
    577     """
    578     if iterable(eq):
--> 579         match = classify_sysode(eq, func)
    580         eq = match['eq']
    581         order = match['order']

/Users/aaronmeurer/Documents/python/sympy/sympy-scratch/sympy/solvers/ode.py in classify_sysode(eq, funcs, **kwargs)
   1364     func_dict = dict()
   1365     for func in funcs:
-> 1366         if not order[func]:
   1367             max_order = 0
   1368             for i, eqs_ in enumerate(eq):

KeyError: V(t)
```

CC @KDMOE.

**Comment by FiachAntaw** [comment]
I ran into this issue myself today, but I suspect it's due to a bug in the setup for classify_sysode when ```funcs != None```, rather than in dsolve itself. For example, the following crashes when I would expect it to produce identical output:

```python
from sympy import Function, Eq, symbols, diff
from sympy.solvers.ode import classify_sysode
from sympy.abc import t
f, x, y = symbols('f, x, y', function=True)
k, l, m, n = symbols('k, l, m, n', Integer=True)
x1 = diff(x(t), t) ; y1 = diff(y(t), t)
x2 = diff(x(t), t, t) ; y2 = diff(y(t), t, t)
eq = (Eq(diff(x(t),t), 5*t*x(t) + t**2*y(t)), Eq(diff(y(t),t), -t**2*x(t) + 5*t*y(t)))
a = classify_sysode(eq)
b = classify_sysode(eq, funcs=c['func'])
assert a == b
```

I suspect that the ```not order[func]``` condition at ode.py:L1373 will always raise KeyError when the funcs is argument is given. ```order``` gets initialized to an empty dictionary, and if ```funcs``` is not None the keys aren't filled out causing a KeyError to be thrown when the ```order[func]``` access is made.

Should it be ```not order.get(func, False)``` instead, to compute the ODE order in both cases? Or equivalently, should the ```order[func_] = 0``` line be removed from the ```funcs == None``` code path and the order condition removed entirely, like so?

```diff
diff --git a/sympy/solvers/ode.py b/sympy/solvers/ode.py
index d717595..7874275 100644
--- a/sympy/solvers/ode.py
+++ b/sympy/solvers/ode.py
@@ -1358,30 +1358,28 @@ def _sympify(eq):
     # find all the functions if not given
     order = dict()
     if funcs==[None]:
         funcs = []
         for eqs in eq:
             derivs = eqs.atoms(Derivative)
             func = set().union(*[d.atoms(AppliedUndef) for d in derivs])
             for func_ in  func:
-                order[func_] = 0
                 funcs.append(func_)
     funcs = list(set(funcs))
     if len(funcs) < len(eq):
         raise ValueError("Number of functions given is less than number of equations %s" % funcs)
     func_dict = dict()
     for func in funcs:
-        if not order[func]:
-            max_order = 0
-            for i, eqs_ in enumerate(eq):
-                order_ = ode_order(eqs_,func)
-                if max_order < order_:
-                    max_order = order_
-                    eq_no = i
+        max_order = 0
+        for i, eqs_ in enumerate(eq):
+            order_ = ode_order(eqs_,func)
+            if max_order < order_:
+                max_order = order_
+                eq_no = i
         if eq_no in func_dict:
             list_func = []
             list_func.append(func_dict[eq_no])
             list_func.append(func)
             func_dict[eq_no] = list_func
         else:
             func_dict[eq_no] = func
         order[func] = max_order
```

**Comment by asmeurer** [comment]
@FiachAntaw feel free to submit a PR.

**Comment by sadbuttrue1** [comment]
@FiachAntaw submit your fix please…

**Comment by FiachAntaw** [comment]
@sadbuttrue1 See PR #11209, sorry for the extraordinarily long delay (I completely forgot about this).

**Comment by raphaeltimbo** [comment]
Is this solved? I tried the code sent by asmeurer and I am still getting the KeyError.
I see that this have been recently merged, so I tried to copy the ode.py file and then I tried to reinstall sympy. I saw the code inside the PR and I believe I have the updated code...
I have also tried the following:
`X = f(x).diff(x, x)`
`Y = f(y).diff(y, y)`
`system = [X, Y]`
`dsolve(system, [f(x), f(y)])`

Expected to see:
f(x) = C₁ + C₂⋅x
f(y) = C₁ + C₂⋅y

but got:

```
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-35-d64d39b5dc9e> in <module>()
----> 1 dsolve(system, [f(x), f(y)])

c:\users\up49\appdata\local\continuum\anaconda3\lib\site-packages\sympy\solvers\ode.py in dsolve(eq, func, hint, simplify, ics, xi, eta, x0, n, **kwargs)
    582     """
    583     if iterable(eq):
--> 584         match = classify_sysode(eq, func)
    585         eq = match['eq']
    586         order = match['order']

c:\users\up49\appdata\local\continuum\anaconda3\lib\site-packages\sympy\solvers\ode.py in classify_sysode(eq, funcs, **kwargs)
   1375     func_dict = dict()
   1376     for func in funcs:
-> 1377         if not order[func]:
   1378             max_order = 0
   1379             for i, eqs_ in enumerate(eq):

KeyError: f(x)
```

**Comment by FiachAntaw** [comment]
Running:

```python
from sympy import symbols
from sympy.solvers.ode import dsolve
f, x, y = symbols('f, x, y', function=True)
X = f(x).diff(x, x)
Y = f(y).diff(y, y)
system = [X, Y]
dsolve(system, [f(x), f(y)])
```

on the current git head gives me a NotImplementedError, not a KeyError (since classify_sysode can't classify the type of the ODE). Are you installing from pip or the git repository? There hasn't been a release since the new code was merged, so the version available via pip won't have the bug fix integrated.

**Comment by raphaeltimbo** [comment]
@FiachAntaw 
> Are you installing from pip or the git repository?
The first time I have got the files from the git repository, but I think I did not notice that it was a different error!
I have replaced again with the files from the repository and now I get the NotImplementedError.
Is this an issue? Or the results that I expected to get do not make sense in sympy?

Thank you for your explanation!

**Comment by FiachAntaw** [comment]
>Is this an issue? Or the results that I expected to get do not make sense in sympy?

I would say it's an issue (there's no explanation as to *why* the calculation fails, which is concerning) but at the same time your formulation of the ODE has a couple of problems:

- You're giving dsolve expressions, which are implicitly equated to zero as per the documentation.
- You're giving dsolve two separate differential equations in two different functions (`f(x)` and `f(y)` are considered separate functions, if I understand correctly); dsolve assumes its parameters are part of a coupled system and fails to handle this case (though it's concerning that dsolve fails to return an appropriate error)

To get the answer you're looking for, you need to call dsolve with something like the following:
```python
from sympy import symbols, Eq
from sympy.solvers.ode import dsolve
f, x, y, A = symbols('f, x, y, A', function=True)
X = Eq(f(x).diff(x), A)
Y = Eq(f(y).diff(y), A)
dsolve(X) # returns 'Eq(f(x), A*x + C1)'
dsolve(Y) # returns 'Eq(f(y), A*y + C1)'
```

**Comment by raphaeltimbo** [comment]
Got your point.
The problem is that, in the code I'm writing, a system of ODEs is generated and it can be coupled or uncoupled depending on some parameters. 
I thought that dsolve would be able to handle the case where the equations are decoupled.
