### ISSUE TITLE
Why is oo real?

### ISSUE THREAD

**Issue by pelegm** [sympy/sympy#8203]
In other words, what does it mean "to be real"? Is it not "being in R, the set of reals"? Well, infinity is not in that set.

And if this is a design decision, is it mentioned in the docs somewhere?

**Comment by pelegm** [comment]
Perhaps it worth mentioning this:
```python
>>> x = Symbol('x', real=True)  # may be oo
>>> S.Reals.contains(x)
True
```

**Comment by skirpichev** [comment]
It's a bug.

**Comment by smichr** [comment]
`oo` is an `extended_real`, now:
```python
>>> oo.is_real
False
>>> Reals.contains(x)
(-oo < x) & (x < oo)
```
