### ISSUE TITLE
is_increasing, is_monotone, etc.

### ISSUE THREAD

**Issue by pelegm** [sympy/sympy#8205]
Do you think it is a good idea to try and implement a general `is_monotone` method for functions? In cases the function is differentiable everywhere, it should be easy enough to implement (`solve(f.diff()>=0` and see if that includes all the reals). In other cases, we may need to work harder or raise `NotImplementedError`.

Other similar methods:

* `is_increasing`
* `is_strictly_increasing`
* `is_decreasing`
* `is_strictly_decreasing`

Of course, all of this is relevant only for functions from a subset of R to R.

**Comment by aktech** [comment]
Implemented here #9820
