### ISSUE TITLE
Integrate tan(x)

### ISSUE THREAD

**Issue by dariober** [sympy/sympy#8218]
Hello- Is this result expected?
sympy 0.7.5:

```
x= symbol('x')
fx= tan(x)
F= integrate(fx)
print F  # >>>  -log(sin(x)**2 - 1)/2
```
From WolframAlpha (http://www.wolframalpha.com/input/?i=tan%28x%29) the indefinite integral of `tan(x)` is -log(cos(x)) which is what I expected.

Thanks! Dario

**Comment by leosartaj** [comment]
Duplicate to #9494
