### ISSUE TITLE
sympy and numpy return different value for the rank of a complex matrix

### ISSUE THREAD

**Issue by epifanio** [sympy/sympy#8233]
numpy and sympy return a different value of the rank for a complex matrix.
code here :  http://nbviewer.ipython.org/gist/epifanio/7bcd548a82dde9a97584 here 
A is the original matrix in sympy (C in numpy) 
and B is the A-eigenval*Identity matrix in sympy  (  D in numpy)

i'm using both sympy and numpy form git master.
sympy gives rank = 2 for B , while numpy gives 1 (matrix D ) 

It is possible i'm using sympy in a wrong way .. ahy thoughts ?

**Comment by moorepants** [comment]
This is fixed in master.
