### ISSUE TITLE
plot((-7*x)**12-((-7*x)**3)**4) TypeError: __init__() takes exactly 3 arguments (2 given)

### ISSUE THREAD

**Issue by satels** [sympy/sympy#8234]
<pre>
In [8]: plot((-7*x)**12-((-7*x)**3)**4)
TypeError                                 Traceback (most recent call last)
----> 1 plot((-7*x)**12-((-7*x)**3)**4)

sympy/plotting/plot.pyc in plot(*args, **kwargs)
   1274     series = []
   1275     plot_expr = check_arguments(args, 1, 1)
-> 1276     series = [LineOver1DRangeSeries(*arg, **kwargs) for arg in plot_expr]
   1277
   1278     plots = Plot(*series, **kwargs)

TypeError: __init__() takes exactly 3 arguments (2 given)
</pre>

**Comment by oscargus** [comment]
Works in master so must have been fixed over the years:
![image](https://user-images.githubusercontent.com/8114497/63355993-5795e580-c367-11e9-9a5b-e79223635833.png)

(It may be that the result is simplified to zero at some stage...)

**Comment by oscargus** [comment]
Btw, it is exactly the same plot as for `plot(0)`.
