### ISSUE TITLE
Interval(-oo, oo) + FiniteSet(oo) takes forever

### ISSUE THREAD

**Issue by hargup** [sympy/sympy#8257]
It should rather remain unevaluated.

**Comment by gxyd** [comment]
I think this should rather be returned `Interval(-oo, oo)` instead of returning `un-evaluated`.
This issue is a subset of issue #9706 .
@hargup  why do you think this be returned un-evaluated ?

**Comment by kshitij10496** [comment]
@hargup Are you expecting an output like this : `(-∞, ∞) ∪ {∞}`

Moreover, can you explain why it should remain unevaluated ?

**Comment by asmeurer** [comment]
Interval apparently can't contain `oo` (it always remains open), so `Interval(-oo, oo)` is incorrect. `(-∞, ∞) ∪ {∞}` is unevaluated (there's no way to evaluate it, unless we add support for intervals over the extended reals).

**Comment by kshitij10496** [comment]
@asmeurer 

> Interval apparently can't contain oo
```
In [ ]: Interval(-oo, oo).contains(oo)
Out[ ]: True
```
I had the doubt as to why we want the union to remain unevaluated after I tried this. 
Should, this behaviour be changed then ?

**Comment by rpisarev** [comment]
Can you confirm #10712, @hargup ?

**Comment by rpisarev** [comment]
Guys, let's see #10712 :)
