### ISSUE TITLE
nan.is_number is True

### ISSUE THREAD

**Issue by pelegm** [sympy/sympy#8403]
Is that a bug?

``` python
In [2]: nan.is_number
Out[2]: True
```

How else should I know I got `nan` as a result?

**Comment by debugger22** [comment]
I'm going through `Needs Decision` issues. What's stopping this? @asmeurer

**Comment by skirpichev** [comment]
> I'm going through Needs Decision issues.  What's stopping this?

Because no reasons for change are made.  I hope, this explains that label.

**Comment by debugger22** [comment]
It sounded counter-intuitive. After reading wikipedia, it all makes sense. Thanks!

**Comment by skirpichev** [comment]
> It sounded counter-intuitive.

Are you about "nan = not a number" and "is_number = True"?  You should first look on the is_number docstring, not in the wikipedia.

**Comment by skirpichev** [comment]
unsubscribed.

please mention we if you want more comments

**Comment by debugger22** [comment]
I was talking about not a number being a number. I know that is_number checks for free symbols. Anyway, it's better this way rather than going for semantics.

**Comment by smichr** [comment]
nan is a result of doing something illegal with numbers; it can be added to other numbers but it trumps others and the result becomes nan. It is a non-comparable number so 

```
>>> S.NaN.is_comparable
False
```

Seeing nothing to change, I am closing this issue.
