### ISSUE TITLE
integrate(abs(x), (x, 0, 1)) does not simplify

### ISSUE THREAD

**Issue by pelegm** [sympy/sympy#8430]
See this:

``` python
In [2]: x = Symbol('x', real=True)

In [3]: integrate(abs(x), (x, 0, 1))
Out[3]: Integral(Abs(x), (x, 0, 1))
```

`.doit()` doesn't help there. I'd expect `1/2`.

**Comment by asmeurer** [comment]
See also https://github.com/sympy/sympy/issues/2868 for the indefinite integral

```
In [4]: integrate(abs(x), x)
Out[4]:
⌠
⎮ │x│ dx
⌡
```

**Comment by jdmarble** [comment]
The Heaviside work around doesn't seem to work in version 1.0:

```Python
>>> from sympy import *
>>> x = Symbol('x')
>>> Integral(abs(x), (x, 0, 1)).rewrite(Abs,Heaviside).doit() 
Integral(Abs(x), (x, 0, 1))
```

**Comment by jdmarble** [comment]
Disregard. I forgot the `real=True`. Sorry!

```python
>>> x = Symbol('x', real=True)
>>> Integral(abs(x), (x, 0, 1)).rewrite(Abs,Heaviside).doit()
1/2
```

**Comment by pelegm** [comment]
Anyway, this ticket seems to still be relevant. It is not obvious that one should rewrite using heaviside in order to calculate the integral.

**Comment by asmeurer** [comment]
It should just work out of the box. The assumptions should be unnecessary because it could infer that from the integration limits.
