### ISSUE TITLE
float('inf') is getting in the way

### ISSUE THREAD

**Issue by pelegm** [sympy/sympy#8439]
Sometimes I find myself handling with mixed expressions like `n + float('inf')`, which are then printed like `n + +inf`. It does not help if I `n + sympify(float('inf'))`. Why won't `sympify(float('inf'))` return `oo`?

**Comment by smichr** [comment]
Looks like `float('inf')` is cast to `oo` in a SymPy expression:
```python
>>> float('inf')
inf
>>> 1 + float('inf')
inf
>>> x + float('inf')
x + oo
>>> S.One + float('inf')
oo
>>> n = Symbol('n', integer=True, nonnegative=True)
>>> (n + sympify(float('inf'))).is_infinite
True
```
Adding a test like `x + float('inf') == x + oo` and `S(float('inf')) == oo` could close this issue.

**Comment by himanshi-2602** [comment]
@smichr 
I would like to work on this issue .
I am a beginner but I really want to explore open source field.

**Comment by faze-geek** [comment]
> I am a beginner but I really want to explore open source field.

Hello @himanshi-2602 
This link would be a good place to get started with contributing https://github.com/sympy/sympy/wiki/Introduction-to-contributing

**Comment by daspartho** [comment]
Is this available? I'd like to work on this.

**Comment by ajjayymahato** [comment]
Hi there! I would like to work on this issue. Can you please assign this issue to me if its still open!

**Comment by carverde** [comment]
Hello! I would like to work on this, is it still available?

**Comment by siya100** [comment]
hello,i am beginner with basic idea of python and i would like to work on it

**Comment by Jay-Patankar** [comment]
@pelegm 
I am a beginner in opensource and would like to take up this issue if its not closed? Can you assign me this issue?
