### ISSUE TITLE
Ipython Notebook Examples Are Not Working. 

### ISSUE THREAD

**Issue by dpallone** [sympy/sympy#8443]
When I try to run the plotting examples from the command line with 

`ipython plot_advanced.ipynb`

but I get an error that says
`/sympy/examples/beginner/plot_advanced.ipynb in <module>()`
`     15     {`
`     16      "cell_type": "code",`
`---> 17      "collapsed": true,`
`     18      "input": [`
`     19       "from sympy.plotting import plot"`
``
`NameError: name 'true' is not defined``

**Comment by Pretovelho** [comment]
On python true or false must be capitalize: 'True' or 'False'.
