### ISSUE TITLE
Trivial bounds on binomial coefficients

### ISSUE THREAD

**Issue by pelegm** [sympy/sympy#8462]
This is a suggestion; I am ready to implement it, but I'll need a hint about how possible/easy it might be, and where to start.

In #5415 it is reported that limits of expressions involving function of several arguments, such as `binomial(n, k)`, fail. Perhaps trivial bounds on binomial coefficients may help to solve this issue for the case where all such functions are binomial coefficients.

The trivial bounds are

``` latex
\left(\frac{n}{k}\right)^k \le {n\choose k} \le \left(\frac{en}{k}\right)^k
```

Here's an illustration:

``` python
limit(binomial(n, n/2), n, oo)
```

fail with `MRV set computation for functions in several variables not implemented.`. But using the lower bound, we know that `binomial(n, n/2)` is at least `2**(n/2)`, and SymPy knows that the limit of this is infinity.

Similarly,

``` python
limit(binomial(n, n/2) * 3 ** (-n), n, oo)
```

fails, but the trivial upper bound yields that `binomial(n, n/2)` is at most `(2*E)**(n/2)`, and since the expression is positive, the limit is 0 (as `limit((2*E)**(n/2) * 3**(-n), n, oo)` shows).

**Comment by anutosh491** [comment]
Both these issues work and the fix for these are proper and not accidental ( https://github.com/sympy/sympy/commit/22700c9d2dab8172412c92e028afa01a534c839f).
```
>>> n = Symbol('n')
>>> limit(binomial(n, n/2), n, oo)
oo
>>> limit(binomial(n, n/2) * 3 ** (-n), n, oo)
0
```
So yeah this could be closed after adding a test . Marking as easy to fix
