### ISSUE TITLE
b splines of degree > 1?

### ISSUE THREAD

**Issue by raddy** [sympy/sympy#8474]
Looking at the spline_basis function:

```
knots = [0,0,0,2.5,5,7.5,10,10,10] 
sy.bspline_basis_set(2,knots,x)
```

This seems to break while the following is fine:

```
knots = [0,0,2.5,5,7.5,10,10]
sy.bspline_basis_set(1,knots,x)
```

I can tweak in extra knots, i.e. placing them at (0.1,0.2, 10.1,10.2 in the example) but this is still not really giving the desired basis matrix. 

Or am I just missing something very obvious?

I always generated knots for bspline basis matrix by taking the list of knots and:

```
 nknots = np.concatenate((np.repeat(knots[0],(degree+1)),np.array(knots[1:-1]),np.repeat(knots[-1],(degree+1))))
```

**Comment by Saintis** [comment]
Also having problems with this. Is there no way of generating B-splines with repeated knots and order > 1?
