### ISSUE TITLE
_eval_is_prime for the Mul class

### ISSUE THREAD

**Issue by pelegm** [sympy/sympy#8488]
Can we implement a `_eval_is_prime` for the `Mul` class? For example, if `k` is an integer symbol, it would be nice if `(9 * k).is_prime` will return `False`.

**Comment by AadityaNair** [comment]
I am working on this issue. Should the tests be added in `test_assumptions.py` ?

**Comment by asmeurer** [comment]
Careful! That's not true if k is 1.

**Comment by asmeurer** [comment]
See also https://github.com/sympy/sympy/issues/7286 (the same mistake was made in the new assumptions).

**Comment by asmeurer** [comment]
Ah, I see you chose 9. So that is fine. But be careful that integer*integer is not necessarily composite. And it doesn't help that our definition of prime also requires the number to be positive.

**Comment by AadityaNair** [comment]
True. I tried this and it failed.
```python
>>> a=Symbol('a', positive=True, integer=True)
>>> a=1
>>> (7*a).is_prime
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-11-fd35576c5f59> in <module>()
----> 1 (7*b).is_prime

AttributeError: 'int' object has no attribute 'is_prime'
```

but this works
```python
>>> (sympify(7)*a).is_prime
True
```
Shall I `sympify` all arguments that are not instances of SymPy classes?

**Comment by AadityaNair** [comment]
@asmeurer  
Well, the problem with the above approach is that once I assign `a=1`, `7*a` automatically returns a `int` type object and hence cannot be checked for primality. Should I just ignore the case like the other assumptions.
