### ISSUE TITLE
Dividing factorial(n) by n

### ISSUE THREAD

**Issue by pelegm** [sympy/sympy#8531]
If
```python
n = Symbol('n', integer=True, positive=True)
```
then this should return 0:
```python
>>> factorial(n) % n
```
and this should return factorial(n-1):
```python
>>> factorial(n) / n
```

Similarly, if
```python
n = Symbol('n', integer=True, nonnegative=True)
```
then this should return factorial(n+1):
```python
>>> factorial(n) * (n + 1)
```

**Comment by certik** [comment]
Yeah, I don't think this should be automatic. But there should be functions that do this.

**Comment by asmeurer** [comment]
It should be combsimp. See https://github.com/sympy/sympy/issues/9699.
