### ISSUE TITLE
Expression match doesn't work properly

### ISSUE THREAD

**Issue by proy87** [sympy/sympy#8558]
I want to match expressions of the form 1/sin^2(ax+b)
import sympy
from sympy.abc import x
a = sympy.Wild('a', exclude=[x])
b = sympy.Wild('b', exclude=[x])

(1/sympy.sin(x+2)**2).match(1/sympy.sin(a*x+b)**2) matches
(1/sympy.sin(2x)**2).match(1/sympy.sin(a*x+b)**2) matches
(1/sympy.sin(3x+2)**2).match(1/sympy.sin(a*x+b)**2) matches
(1/sympy.sin(x)**2).match(1/sympy.sin(a*x+b)**2) doesn't match
Why 1/sympy.sin(x)**2 doesn't match?

**Comment by jcrist** [comment]
Currently matches in master, as pointed out above. Closing.
