### ISSUE TITLE
nsolve loses accuracy when solving `x*x == pi`

### ISSUE THREAD

**Issue by cbm755** [sympy/sympy#8564]
It looks like sometimes nsolve is limited to double precision:

```
sympy.mpmath.mp.dps = 128
e1 = Eq(x*x, pi)
q = nsolve(e1, x, 3.0)

sin(q*q)   # i.e., sin(pi)
Out[30]: 0.00000000000000323108914886517363090877526387617491958104246375523750266199776312416052999856025822151250757371201176461629253175135549

q - N(sqrt(pi), 128)
Out[45]: mpf('-0.00000000000000091147342065195854887259993738062373324012048212675893913882065856629599443261056363296123272878981225608269284506517613253555513073')
```

But it often works properly, even on "harder" problems:

```
e2 = Eq(tan(x/4), 1)
q = nsolve(e2, x, 3.0)
sin(q)
Out[35]: -3.3218e-130
```

Other things that do work include `x*x == pi*pi` and `x*x == 2`.

**Comment by cbm755** [comment]
I lied `x*x == pi*pi` does not work.

I have tracked this down to a call to `f = f.evalf()` on line 2520 of solvers.py.  In my example, f will be `x**2 - pi` and evalf of this gives `x**2 - 3.14159265358979`.  And of course it doesn't matter how much precision one uses to solve that, it'll be limited to the 16 digits.

Perhaps I'm not supposed to be using `mpmath.mp.dps` to control nsolve, but the example docstring sure looks like it!

**Comment by cbm755** [comment]
So I can "fix" this by replacing the call `f = f.evalf()` with:
````
       import mpmath
        f = f.evalf(mpmath.mp.dps)
````
I'll submit a merge request later.

Another option would be to make `.evalf()` respect `mpmath.mp.dps` but I should problem read more about how Floats are supposed to behave in SymPy first!

**Comment by cbm755** [comment]
Hmmm, this is a rabbit hole for sure.  Filed #8818 for lambdify problems.

**Comment by smichr** [comment]
See #5536, too, which looks like a loss of precision case, too.

**Comment by asmeurer** [comment]
One can also fix the problem by removing the evalf line. I don't understand why it's there. The expression is lambdified, which should take care of converting things to mpmath (albeit with the issues you noted, which I haven't checked if they are still relevant). 

Do you have a test case where lambdify breaks things? I removed the `f = f.evalf()` call and this works

```
In [1]: import mpmath

In [2]: mpmath.mp.dps = 128

In [3]: e1 = Eq(x*x, pi)

In [4]: q = nsolve(e1, x, 3.0)

In [6]: q
Out[6]: mpf('1.7724538509055160272981674833411451827975494561223871282138077898529112845910321813749506567385446654162268236242825706662361528657')

In [7]: sin(q*q)
Out[7]: -3.3218e-130
```
