### ISSUE TITLE
Where is the IdentityOperator

### ISSUE THREAD

**Issue by cowlicks** [sympy/sympy#8575]
It is defined [here](http://docs.sympy.org/dev/_modules/sympy/physics/quantum/operator.html#IdentityOperator) but running the example in the sympy live shell gives:

```python
>>> from sympy.physics.quantum import IdentityOperator
Traceback (most recent call last): File "<string>", line 1, in <module>
```

Importing `UnitaryOperator` works, it is defined and imported in the same way. Whats going on?

**Comment by xuhdev** [comment]
Can you close this? It should have been fixed now.

**Comment by moorepants** [comment]
Fixed in master. SymPy live will get updated when it gets updated.
