### ISSUE TITLE
RootOf might ignore generator

### ISSUE THREAD

**Issue by smichr** [sympy/sympy#8617]
This is related to #8551 but a little different. I'm not sure of all the ramifications but just want to document this.

Note how feeding RootOf an expression in terms of a new generator might ignore that generator if the form of the polynomial is the same

```
>>> RootOf(x**3+x-1,0)
RootOf(x**3 + x - 1, 0)
>>> RootOf((x**3+x-1).subs(x,tan(x)),0)
RootOf(x**3 + x - 1, 0)
>>> _.poly.gen
x  <----------------/!\ When you solve for RootOf values you will be getting tan(x) values
```

```
>>> RootOf(tan(x)**3 + 2*tan(x) - 1, 0)  # a new form
RootOf(tan(x)**3 + 2*tan(x) - 1, 0)
>>> RootOf((x**3+2*x-1),0)  # same form but new generator (x instead of tan(x)
RootOf(tan(x)**3 + 2*tan(x) - 1, 0)  <--------/!\ generator is tan(x) instead of x
>>> _.poly.gen
tan(x)
```

**Comment by smichr** [comment]
`solve` may have worked a way around this but the issue still remains.
```python
>>> RootOf(x**3+x-1, 0).poly.gen
x
>>> RootOf(sin(x)**3+sin(x)-1, 0)
CRootOf(x**3 + x - 1, 0)
```
RootOf represents a number, so it's proper to hash the above as the same. But from a user perspective one has to realize that it doesn't represent a solution for `x` unless `x` is a symbol.
```
>>> RootOf(sin(x)-1,0)  # sin(x) == 1 so x = (2*i+1)*pi/2
1
```
Perhaps the safest solution is to disallow anything but a symbol to be the generator.

**Comment by jksuom** [comment]
>  the safest solution is to disallow anything but a symbol to be the generator.

+1
