### ISSUE TITLE
Mod ignores the `is_even` assumption

### ISSUE THREAD

**Issue by pelegm** [sympy/sympy#8630]
For example,

``` python
>>> n = Symbol('n', integer=True, positive=True, even=True)
n%2
```

should have probably returned 0.

**Comment by ylemkimon** [comment]
Latest development version gives correct answer(0).

**Comment by pelegm** [comment]
Thanks for verifying this. Do you think we should add a test before closing this issue?

**Comment by ylemkimon** [comment]
@pelegm I think we have it somewhere. But if not, please add it. Thank you!

**Comment by pelegm** [comment]
Couldn't find, so added...

**Comment by ylemkimon** [comment]
I'm sorry, but it seems there is one:

https://github.com/sympy/sympy/blob/50d8a102f0735da8e165a0369bbb994c7d0592a6/sympy/core/tests/test_arit.py#L1649-L1653

**Comment by pelegm** [comment]
OOPS :)
Removing the PR.
