### ISSUE TITLE
limit(x**n, x, -oo) is sometimes wrong

### ISSUE THREAD

**Issue by pelegm** [sympy/sympy#8634]
For example,

``` python
>>> n = Symbol('n', integer=True, positive=True)  # could be 3
>>> limit(x**n, x, -oo)
oo
```

while

``` python
>>> limit(x**3, x, -oo)
-oo
```

It looks like it assumes `n` is even, because stating `odd=True` for `n` seems to solve this issue.

**Comment by Amitjha1412** [comment]
Hi ,
I am new to Sympy community. I wanted to get started with this bug. Can you please explain more about this bug ?

Thanks.
Amit

**Comment by pelegm** [comment]
Can you ask a more specific question?

**Comment by Amitjha1412** [comment]
Where should i start looking into?

**Comment by pelegm** [comment]
> Where should i start looking into?

I have no idea. I just reported the bug, I don't have a clue about where to start looking for a solution.

**Comment by sandeepveethu** [comment]
> It looks like it assumes n is even, because stating odd=True for n seems to solve this issue.
``` python
>>>n=symbols('n',integer=True,positive=True,odd=True)
>>>x=symbols('x')
>>>limit(x**n,x,-oo)
oo
```
@pelegm odd=True doesn't solve this issue
@jksuom can you help me in fixing this , i think [limitinf](https://github.com/sympy/sympy/blob/master/sympy/series/gruntz.py#L408) function is causing this issue but i am not able to figure out where?

**Comment by jksuom** [comment]
I'm afraid this is not going to be easy to fix. It seems that ``limit`` invokes ``gruntz`` even if that would not be necessary in this case. That will routinely replace the variable ``x`` with an expression of type ``-exp(y)`` (as ``x`` is expected to be negative). Then ``x**n`` will take the form ``exp(y*n + I*pi*n)``, which is correct. But afterwards, in passing to the limit ``y -> oo``, the ``I*pi*n`` term is lost and the result will be ``exp(oo) = oo``.

It seems to me that the limit should be computed without passing over to ``gruntz``, but that would imply a major rearrangement of ``limit``.

**Comment by sandeepveethu** [comment]
@jksuom thanks a lot for the insight.

**Comment by anutosh491** [comment]
Currently this functions opposite to what the issue was reported for 
```
>>> n = Symbol('n', integer=True, positive=True)
>>> limit(x**n, x, -oo)
-oo
```
