### ISSUE TITLE
Max should be positive if any of its args is positive

### ISSUE THREAD

**Issue by pelegm** [sympy/sympy#8643]
At the moment,
```python
>>> x = Symbol('x', real=True, positive=True)
>>> y = Symbol('y', real=True)
>>> Max(x, y).is_positive
```
returns `None`, while it should return `True`. Do you think that implementing `_eval_is_positive` is enough here? Or `_eval_is_nonnegative` as well? Or just the latter? Will it conclude `is_nonpositive` and `is_negative` automatically?

**Comment by leosartaj** [comment]
``Min`` is also not able to tell.

```
>>> x = Symbol('x', real=True, negative=True)
>>> y = Symbol('y', real=True)
>>> Min(x, y).is_positive
```

returns ``None`` but should be ``False``.
