### ISSUE TITLE
Ordinal arithmetic

### ISSUE THREAD

**Issue by pelegm** [sympy/sympy#8668]
It would be nice if SymPy would have provided ordinal arithmetic.

That would require either definining a new object called `OrdinalNumber`, that will either inherit from `Symbol` or from `Basic` (option 1), or new assumption(s) that will allow the current symbols to be ordinals.

How can it work with assumptions? Roughly as follows:

``` python
    ...
    'natural            ==  integer & nonnegative & finite',
    'natural            ->  ordinal',
    'limit_ordinal      == ordinal & !successor_ordinal',
    'successor_ordinal  == ordinal & !limit_ordinal',
    ...
```

and arithmetic should be defined: addition, multiplication and exponentiation (all are not commutative in general), and some other useful methods, such as:
- relationals supporting ordinals
- cantor normal form
- prime ordinals (perhaps also with the `prime` assumption)
- limits of sequences of ordinals
- cardinals (related to #2995)
- some "known" ordinals such as omega, omega_1, ..., epsilon numbers, etc.

[Here](http://web.mit.edu/dmytro/www/other/OrdinalArithmetic.py) you can find a python implementation of non-symbolic ordinal arithmetic. I can be up to the task of defining a symbolic variation, but I don't think I can implement it in SymPy.

**Comment by drocta** [comment]
I wrote a python class for ordinal numbers less than epsilon_0 which has natural addition and natural multiplication, and I happened upon this issue. Might this code be useful as something to use as a base for a solution to this issue?

It uses natural (Hessenberg) operations, so `__mul__` is commutative for it (as is `__add__` ), so I don't know if it would serve the same purposes as well, but it also wouldn't have the problems mentioned above with `n*2 != 2*n` .

I hope I'm not going against any norms by responding to an old issue or anything like that. Just thought it might be possible that what I wrote could be helpful, and wanted to share it if it could be. It is fairly short, so it should be relatively easy to extend I think.

I haven't put it in any repository of mine yet, but I will do so shortly.

**Comment by smichr** [comment]
> Now I feel silly. Whoops

Activity on an issue raises it to the top of the "recently updated" listing, so all is not lost. If nobody responds to an old issue it gets stale. Now...whether anything will happen or not is another issue ;-)

**Comment by ashishkg0022** [comment]
@jksuom can this be implemented? I want to take this up. Can you please tell me more about it.

**Comment by jksuom** [comment]
It is hard to find easily accessible references where ordinal arithmetic is discussed in detail. The [wikipedia article](https://en.wikipedia.org/wiki/Ordinal_arithmetic) is probably the best starting point. It shows that there are (at least) two kinds of *ordinal arithmetic*, the 'classical' operations (defined by Cantor, I think) and 'natural' operations. The former are easier to understand but neither addition nor multiplication is commutative. The natural operations are commutative, but harder to construct.

It seems that Taranowsky ([referred to](http://web.mit.edu/dmytro/www/other/OrdinalArithmetic.py) in OP above) is using the natural operations. He has developed a new [notational system](http://web.mit.edu/dmytro/www/other/OrdinalNotation.htm) for the implementation. It looks rather complicated to me.

If I were to implement ordinal arithmetic, I would probably choose the classical operations. Ordinals could be constructed recursively and represented in Cantor's normal form. Ordinal could possibly be a subclass of Basic but not one of Expr as the addition is non-commutative. I see no need for using the Symbol class. Named ordinals can be defined as special (singleton) subclasses. The order relations should not be hard to implement, and it should also be possible to define `is_limit_ordinal` as a property. I'm not sure if assumptions are necessary, but they could be added later if desired.

**Comment by pelegm** [comment]
@jksuom - I tend to agree with what you wrote.

**Comment by ashishkg0022** [comment]
thanks @jksuom  @pelegm  , I will try to implement it and soon open a PR.
