### ISSUE TITLE
reduce -> functools.reduce / for loops

### ISSUE THREAD

**Issue by pelegm** [sympy/sympy#8671]
From "what's new in python 3" webpage:

> Removed reduce(). Use functools.reduce() if you really need it; however, 99 percent of the time an explicit for loop is more readable.

There are many (hundreds) of appearances of `reduce` in sympy's code. Only in a couple of places I saw `functools.reduce` or `from functools import reduce`.

What do you think? This is a project I am willing to take, if you think it might do good.

This issue is a specific 2to3 idiom, and the motivation can be found in #6698.

**Comment by jayesh92** [comment]
Isn't this issue already handled, in `compatibility` we have imported reduce from `functools` for PY3 and `reduce` elsewhere. 
Line 89, 123

**Comment by AadityaNair** [comment]
Hey, I want to fix this issue.
Will replacing `functools` with `sympy.core.compatiblity` in the above files fix this issue ?

**Comment by jcrist** [comment]
Yes. Except in the last one, where an import needs to be added. If you're new to sympy, please read this: https://github.com/sympy/sympy/wiki/Development-workflow.

**Comment by AadityaNair** [comment]
Generated pull request #8913. Please comment if modifications are needed.

**Comment by pelegm** [comment]
So... should that be closed now?

**Comment by AadityaNair** [comment]
Yes. I think so.
