### ISSUE TITLE
Implementing Fraction Part function

### ISSUE THREAD

**Issue by pelegm** [sympy/sympy#8674]
I wish to implement fractional part function, just like [this one](http://mathworld.wolfram.com/FractionalPart.html). I think of doing this in `sympy/functions/elementary/integers.py`.

Do you have any objection? If not, I'll do it - it should be easy enough.

**Comment by leosartaj** [comment]
Can I pick this up? If nobody is doing it.

**Comment by pelegm** [comment]
@leosartaj, sorry for the late reply, thanks for taking this.

**Comment by leosartaj** [comment]
:smile:
