### ISSUE TITLE
Max forgets the `is_prime` assumption

### ISSUE THREAD

**Issue by pelegm** [sympy/sympy#8676]
For example,

``` python
>>> p = Symbol('n', integer=True, prime=True)
>>> q = Symbol('k', integer=True, prime=True)
>>> Max(n, k).is_prime
```

returns `None`, but should return `True`.

This is related to issue #8640 and pull request #8652 (which I have authored) - but I am not sure whether `_eval_is_prime` is the way to do it here.

**Comment by pelegm** [comment]
Added that functionality to #8652.

**Comment by mvnnn** [comment]
i want to work on this issue.this issue is open?

**Comment by pelegm** [comment]
This is probably fixed in #10338, but it's a good thing to check!

**Comment by AnishShah** [comment]
This works on the master

**Comment by pelegm** [comment]
@mvnnn, perhpas you could check if there's a test for it. If there is such, we can close this, otherwise you could write one and add a PR.

**Comment by mvnnn** [comment]
@pelegm thanks.

**Comment by mvnnn** [comment]
@pelegm Given example is wrong.you takes ```n``` and ```k``` instead of ```p``` and ```q```
```
>>> p = Symbol('n', integer=True, prime=True)
>>> q = Symbol('k', integer=True, prime=True)
>>> Max(p, q).is_prime
True
```
that's working correctly in terminal but that's not working on ```SymPy Live Shell``` it's return ```None```.

**Comment by AnishShah** [comment]
Yeah, I think it is a typo.

**Comment by sum2it** [comment]
I think we can close this issue since it clearly is a typo by OP. They should've written Max(p, q).is_prime ad it would've worked the way it is meant to. 

Please close this issue.

**Comment by pelegm** [comment]
This was a typo, but the issue originally was a real issue, which now seems to be solved.
