### ISSUE TITLE
rsolve fails to find solutions to some higer order recurrence relations

### ISSUE THREAD

**Issue by klemvor** [sympy/sympy#8697]
I was trying to solve the difference equation:

``` python
>>> eq = a(n+3) - a(n+2) - a(n+1) + a(n)
```

with `rsolve` and I have the following output:

``` python
>>> rsolve(eq,a(n))
>>> (-1)**n*C0 + C1*(C0 + C1*n)/C0
```

Hower I know that the correct solution is:

``` python
(-1)**n*C0+C1+C2*n
```

therefore I think that there is a bug in rsolve, which I think is located in the handling of degenerate solutions. Indeed if we take another equation with characteristic equation with roots of multiplicity greater than one like (for the method of solution of such equation one can simply refer to [Wikipedia](http://en.wikipedia.org/wiki/Recurrence_relation#Solving)):

``` python
>>> eq2 = a(n+3)+3*a(n+2)+3*a(n+1)+a(n)
```

again we get:

``` python
>>> rsolve(eq3,a(n))
>>> C0*((-1)**n + (-1)**n*C1*n/C0 + (-1)**n*C2*n**2/C0)
```

instead of the correct solution:

``` python
>>> C0*(-1)**n + (-1)**n*C1*n + (-1)**n*C2*n**2
```

So I think that `rsolve` code must be examined in search of this little bug. I incidentally note that in the case of recurrence relations of the second order this seems not to occur.

**Comment by pedritomelenas** [comment]
We experimented a similar issue while using `rsolve` to solve the recurrence equation $a(n)=2a(n-1)+n$ with $a(0)=1$

By evaluating
```
from sympy import *
n=Symbol("n", integer = True)
a=Function('a')
rsolve(a(n)-2*a(n-1)-n,a(n),[1])
```
we obtain
```
2**n/2 + n/2 + 1/2
```
However if we check the solution,
```
f = lambda n : (2**n + n + 1)/2
simplify(f(n)-2*f(n-1)-n)
```
the returned value is
```
-3*n/2 + 1/2
```
So our first attempt to see what happens was to homogenize in two steps the original equation. As $a(n)-2a(n-1)-n=0$, the following equality is also satisfied by $a(n)$
```
 a(n)-2*a(n-1)-n-(a(n-1)-2*a(n-2)-(n-1))
 ```
 which is just
 ```
 a(n) + 2*a(n - 2) - 3*a(n - 1) - 1
 ```
 Applying `rsolve` to this last relation, we obtain the desired solution (notice that $a(1)=3$)
 ```
 rsolve(a(n) + 2*a(n - 2) - 3*a(n - 1) - 1,a(n),[1,3])
 ```
 with output
 ```
 3*2**n - n - 2
 ```
And this is the correct solution; the following yields 0
```
ff = lambda n: 3*2**n - n - 2
simplify(ff(n)-2*ff(n-1)-n)
```
Trying to understand the problem, we keep "homogenizing" the equation $a(n)-3a(n-1)+2a(n-2)-1$ that we obtained above (we want to remove the independent term):
```
a(n) + 2*a(n - 2) - 3*a(n - 1) - 1 - (a(n-1) + 2*a(n - 3) - 3*a(n - 2) - 1)
```
yields
```
a(n) - 2*a(n - 3) + 5*a(n - 2) - 4*a(n - 1)
```
Again `rsolve` fails to produce a solution. The output of
```
rsolve(a(n) - 2*a(n - 3) + 5*a(n - 2) - 4*a(n - 1),a(n),[1,3,8])
```
is `None` ($a(2)=8$).

So we solved it "by hand". The characteristic polynomial associated to this recurrence equation is
```
x=Symbol("x")
factor(x**3-4*x**2+5*x-2)
```
that is,
```
(x - 2)*(x - 1)**2
```
Consequently the general solution is of the form $u2^n+v+n w$, and we need to find the values for the parameters $u,v,w$
```
u,v,w = symbols("u,v,w")
s = lambda n:u*2**n+v+n*w
solve([s(0)-1,s(1)-3,s(2)-8],[u,v,w])
```
gives
```
{w: -1, v: -2, u: 3}
```
and the solution is $a(n)=3\times 2^n-2-n$, as expected.

Thank you,
Pedro
