### ISSUE TITLE
Wrong solution for a simple inequality

### ISSUE THREAD

**Issue by pelegm** [sympy/sympy#8708]
I have tried to solve the following rather simple inequality:
```python
>>> x = symbols('x', real=True, positive=True)
>>> solve(1-x-exp(-2*x)>0)
False
```
and the result (`False`) was quite surprising, and indeed wrong, as, for example,
```python
>>> (1-x-exp(-2*x)).subs(x, S(1)/2).evalf()
0.132120558828558
```
which looks positive...

**Comment by skirpichev** [comment]
Actually, both)  Sympy miss some reall solutions of the Lambert's transcendental equation and (if that's fixed) it can't compare some such roots numerically (zero-decision problem).

**Comment by asmeurer** [comment]
Lambert equations have infinitely many complex solutions. Ideally solve would always return them all.

**Comment by skirpichev** [comment]
> Ideally solve would always return them all. 

I don't think it's possible.  solveset - a good candidate for.
