### ISSUE TITLE
solve(x - sqrt(x**2)) returns no solution

### ISSUE THREAD

**Issue by aktech** [sympy/sympy#8716]
Solve is not able to determine the solution for this Equation:
```python
In [12]: solve(x - sqrt(x**2))
Out[12]: []

```
It returns no solution.
Though the range of solution should be all nonnegative real numbers.

**Comment by jondo** [comment]
... and of course `solveset(x - sqrt(x**2))` works :-)

**Comment by hargup** [comment]
As dicussed above `solve` can't represent "all solution" and since `solveset` works on this correctly, this is won't fix.
