### ISSUE TITLE
factorial(x) is not known to be real when x is a noninteger

### ISSUE THREAD

**Issue by pelegm** [sympy/sympy#8722]
I guess this is very much related to #8658.

When `x` is a noninteger real, `factorial(x)` is simply `gamma(x+1)`, which is gamma of a number which is not a nonpositive integer, hence it must be real. Thus, `factorial(x).is_real` should return `True` (but now it returns `None`).

**Comment by aktech** [comment]
Thanks for reporting. 
PR #8723
