### ISSUE TITLE
Add docs for solveset

### ISSUE THREAD

**Issue by hargup** [sympy/sympy#8725]
See #7523

**Comment by skirpichev** [comment]
Are you sure about "Easy to Fix" label?

**Comment by deepanshu1995** [comment]
I would like to work on this issue

**Comment by hargup** [comment]
@deepanshu1995 great go ahead. See how other docs are added. Make the changes and send a pull request.
@skirpichev I'm not very sure of "Easy to Fix", but I don't think it will be hard.

**Comment by skirpichev** [comment]
@smichr, it could be a good idea next time build a docs first.

unsubscribed
