### ISSUE TITLE
`nan` is a rational function

### ISSUE THREAD

**Issue by pelegm** [sympy/sympy#8729]
In `is_rational_function()`, there's a line which states that if the intersection of the expression's free symbols is an empty set, then the expression is a *constant rational function*. Thus, `nan.is_rational_function()` is `True`, and this behaviour causes bugs like #8414.

I guess that a simple check of `if self is nan` or so just before `return True` should fix that bug. However, there may be some implications that I miss, so I leave it as an issue rather than as a pull request.

**Comment by tanmaysahay94** [comment]
@pelegm: Can I work on this?

**Comment by skirpichev** [comment]
Sure, if you *know* that it's an issue and you *know* how to fix that.

**Comment by jksuom** [comment]
An expression representing a rational function should not only be different from ``nan`` but should not involve ``nan`` at all. The same goes for the infinities.

**Comment by pelegm** [comment]
I'm also +1, even if this is not complete.
