### ISSUE TITLE
Limit of subfactorial

### ISSUE THREAD

**Issue by pelegm** [sympy/sympy#8730]
Despite the fact that `subfactorial` is defined over nonnegative integers only, it still has a limit at `oo`, which is `oo`. So I'd expect `limit(subfactorial(n), n, oo)` to work (and return `oo`), but that insted raises a `ValueError`. I am not sure how to solve that.

**Comment by pelegm** [comment]
It fails in `heuristics`. The weird thing is that it tries to do heuristics on `subfactorial(1/n)`, which is generally not defined. I guess that what causes that issue is the following line:
```python
        rv = limit(e.subs(z, 1/z), z, S.Zero, "+" if z0 is S.Infinity else "-")
```

Can we condition running that line only on certain cases, or catch `ValueError` exceptions raised by it?

@skirpichev, you seems involved in this area of the code - any ideas?

**Comment by skirpichev** [comment]
No, I don't know how to tune heuristic in a meaningful way.

BTW, I think that the Gruntz algorithm assume that the function in question is continuous (see section about tractable functions).

But we can generalize subfactorial to any real number and also in the complex plane.  See [this](http://mathworld.wolfram.com/Subfactorial.html).

**Comment by skirpichev** [comment]
See #8753

**Comment by pelegm** [comment]
You may solve the problem of `subfactorial` like that, perhaps, but I don't think you can generalize any function which is defined on the integers to the reals / complexes. For example, I don't know how you can extend Euler's totient function to the reals. You may still want to ask about its limit (which does not exist in this case).

**Comment by skirpichev** [comment]
> I don't think you can generalize any function which is defined on the integers to the reals / complexes.

For sure, I can :)  In may ways, actually.

But yes, we have another issue.  Clearly, we don't have notion of the domain of the function.  I think, we have similar discussions in the bugtracker.
