### ISSUE TITLE
Convolution of pulse - Problem with Integrals of Piecewise

### ISSUE THREAD

**Issue by mwiebe** [sympy/sympy#8742]
I tried a bunch of things, and everything fails, gives an unevaluated answer, or gives an answer that looks wrong. I've created a gist notebook you can see here:

http://nbviewer.ipython.org/gist/mwiebe/48bed4e5d52335c47e25

I also sent a message to the sympy mailing list, but I guess it ended up in moderation purgatory? The message moderation is resolved, thanks!

**Comment by asmeurer** [comment]
It looks like you discovered three distinct bugs. I put a simple fix in for the second one (`sign.doit` needs `**hints`), and I found a fourth, which is that it can't be printed because it tries to evalf an integral to in the printer, which hangs.

**Comment by oscarbenjamin** [comment]
I currently get this:
```

In [25]: import sympy 
    ...: from sympy import symbols, Piecewise, integrate, oo 
    ...: sympy.init_printing() 
    ...: x, y, t = symbols("x y t", real=True)                                                                                                 

In [26]: B = Piecewise((1, sympy.Abs(x) < 0.5), (0, True)) 
    ...: sympy.plot(B, (x, -1.5, 1.5)) 
    ...: B2 = integrate(B.subs(x, t) * B.subs(x, t - x), (t, -oo, oo)) 
    ...: B2                                                                                                                                    
Out[26]: 
∞                                      
⌠                                      
⎮  ⎧1  for │t│ < 0.5 ∧ │t - x│ < 0.5   
⎮  ⎨                                 dt
⎮  ⎩0            otherwise             
⌡                                      
-∞                                     

```

**Comment by smichr** [comment]
Looks like this is correct and the code that fixed piecewise folding was heavily tested:
c.f. [these notes regarding this convolution](http://mikewilkes-irsc.weebly.com/uploads/2/3/1/7/23176182/rectangular_pulse_convolution-update.pdf)
```python
>>> >>> from sympy import *
>>> from sympy.abc import x, t
>>> B = Piecewise((1, Abs(x) < 0.5), (0, True)) 
>>> p=B.subs(x, t) * B.subs(x, t - x)
>>> [integrate(p.subs(x,i),(t,-oo,oo)) for i in (0,.5,1)]
[1.00000000000000, 0.500000000000000, 0]
```
