### ISSUE TITLE
sympy.physics.wigner: wigner_6j not working as expected

### ISSUE THREAD

**Issue by woutergins** [sympy/sympy#8748]
Using the following MWE, the 6J-symbol cannot be calculated.
```
    from sympy.physics.wigner import wigner_6j
    Jgr = 2.0
    Fg = 0.5
    I = 1.5
    Fe = 1.5
    Jex = 3.0
    print wigner_6j(Jgr, Fg, I, Fe, Jex, 1.0, prec=15)
```
File "C:\Users\MyStuff\Anaconda\lib\site-packages\sympy\physics\wigner.py", line 491, in wigner_6j
    racah(j_1, j_2, j_5, j_4, j_3, j_6, prec)
  File "C:\Users\MyStuff\Anaconda\lib\site-packages\sympy\physics\wigner.py", line 375, in racah
    _big_delta_coeff(aa, cc, ff, prec) \* \
  File "C:\Users\MyStuff\Anaconda\lib\site-packages\sympy\physics\wigner.py", line 313, in _big_delta_coeff
    _calc_factlist(maxfact)
  File "C:\Users\MyStuff\Anaconda\lib\site-packages\sympy\physics\wigner.py", line 68, in _calc_factlist
    for ii in range(len(_Factlist), nn + 1):
TypeError: range() integer end argument expected, got float.

Doing the same in an IPython console, I get the correct value. I can also solve the problem by calculating some wigner_3j symbols before the 6j in the script.

**Comment by Rufflewind** [comment]
This has already been fixed by https://github.com/sympy/sympy/commit/cf159392a68242c1cffa3ce3e9df954fdfec4d96 in 2014-05-04.  Your Anaconda sympy distribution is likely out of date.

**Comment by oscarbenjamin** [comment]
I get:
```
In [22]:     from sympy.physics.wigner import wigner_6j 
    ...:     Jgr = 2.0 
    ...:     Fg = 0.5 
    ...:     I = 1.5 
    ...:     Fe = 1.5 
    ...:     Jex = 3.0 
    ...:     print(wigner_6j(Jgr, Fg, I, Fe, Jex, 1.0, prec=15))                                                                               
0.223606797749979
```
so as mentioned before it looks like this might be fixed (I don't know how to check that the number is correct though!).
