### ISSUE TITLE
limit(Abs(x)/(x), x, 0) evaluates to 1, without knowing x is zero or not.

### ISSUE THREAD

**Issue by aktech** [sympy/sympy#8751]
```python
x  = symbols('x')
In [2]: limit(Abs(x)/(x), x, 0)
Out[2]: 1
```
This can't be evaluated to 1, until and unless it knows that x is not equal to zero.

**Comment by pelegm** [comment]
I disagree. The default limit direction is `+`, and to the right of `0`, `x` is always positive. The limit result is true. At least, assuming `x` is real (and I believe `limit` assumes that).

**Comment by aktech** [comment]
I think for the limit to exist: the Left hand limit and Right hand limit should be equal to the value of the function at that point, and value of the function is not defined at that point.

**Comment by pelegm** [comment]
Check the discussion at #8165. The current decision (which is not according to my opinion) is that the default direction of the limit is `+`, and two-sided limit is not supported. If you want a two sided limit, you should manually try both sides and compare.

**Comment by aktech** [comment]
Oh! I see.
Thanks

**Comment by hargup** [comment]
> I think for the limit to exist: the Left hand limit and Right hand limit should be equal to the value of the function at that point, and value of the function is not defined at that point.

The second condition "limit should be equal to value of the function` is not necessary. See http://mathworld.wolfram.com/Limit.html

**Comment by aktech** [comment]
@hargup 
Yes! Thanks

**Comment by skirpichev** [comment]
On another hand, there is a bug:
```python
In [1]: Z = Symbol('Z', zero=True)

In [2]: Abs(x)/(x)
Out[2]: 
│x│
───
 x 

In [3]: Abs(Z)/(Z)
Out[3]: 0
```

**Comment by pelegm** [comment]
@skirpichev, I'd open a new issue for that.
