### ISSUE TITLE
cubics should always yield a solution

### ISSUE THREAD

**Issue by smichr** [sympy/sympy#8755]
A solution is not obtained for the following, but there should be the generic 3 solutions for a cubic:

```
>>> from sympy import *;var('x y')
(x, y)
>>> solve(sqrt(y)*x + x**3 - 1, x)
[]
```

**Comment by nishithshah2211** [comment]
`roots` works fine and returns 3 solutions. I think the problem is with the recursive `_solve` call by the `unrad` part, which returns `[]` and the next line checks if `result` is still `False`.
