### ISSUE TITLE
Rewrite factorial as a product

### ISSUE THREAD

**Issue by pelegm** [sympy/sympy#8757]
It would be nice that if, say,
```python
>>> k = Symbol('k', integer=True, nonnegative=True)
```
then the following would hold
```python
>>> factorial(k).rewrite(product)
Product(i, (i, 1, k))
```
(for a dummy positive integer `i`)

**Comment by Amitjha1412** [comment]
Hi ,
I am new to Sympy community. I wanted to get started with this bug. Can you please explain more about this bug ?

Thanks.
Amit

**Comment by pelegm** [comment]
@Amitjha1412, @aktech is already working on this issue.

**Comment by skirpichev** [comment]
> I am new to Sympy community. I wanted to get started with this bug.

Please start [here](https://github.com/sympy/sympy/wiki/introduction-to-contributing) and [here](https://help.github.com/).  Please be familiar with github's interface.
