### ISSUE TITLE
Assuming a function is bounded

### ISSUE THREAD

**Issue by pelegm** [sympy/sympy#8759]
There have been a couple of discussions here about "assumptions on functions". A few examples:

* is_even, is_odd in #2671
* is_increasing, is_monotone, etc. in #8205 

I was thinking that with the same spirit, we can implement something like `is_bounded` (which is not the old deprecated `is_bounded` discussed in #8071, but rather something like `is_bounded_function`).

This can be very useful in some cases. For example, if I know that `f` is a bounded function (of reals), but know nothing else about it, I can still calculate the limit
```python
>>> limit(f(x**2)/x, x, oo)
```
(which should be 0).

**Comment by skirpichev** [comment]
> I can still calculate the limit

In fact, no, e.g. `f(x) = x**2*sin(sqrt(1/x))` for `x >= 0`.

But your claim still holds: this can be useful.

**Comment by skirpichev** [comment]
Indeed)

**Comment by pelegm** [comment]
I guess we should think of this in the context of #8760, so perhaps I can/should close this one?

**Comment by skirpichev** [comment]
maybe
