### ISSUE TITLE
Missing parentheses in pprint output

### ISSUE THREAD

**Issue by Zeleznyj** [sympy/sympy#8774]
Parenthesis are sometimes missing in pprint output, when using MatrixSymbol. Here is an example that produces this issue. 

```
>>> import sympy
>>> x=sympy.MatrixSymbol('x',1,2)
>>> a = x[0,0] + -1 * (x[0,0]-x[0,1])
>>> print a
-(x[0, 0] - x[0, 1]) + x[0, 0]
>>> sympy.pprint(a)
-x₀₀ - x₀₁ + x₀₀
```

Happens with sympy 0.7.6.

**Comment by behrmann** [comment]
I have just reproduced this bug too and I assume that is a problem with the MatrixSymbol class, as all printers are affected (LaTeX too, MathML does not work and throws `TypeError: 'MatrixElement' object is not iterable`)

**Comment by oscargus** [comment]
At the moment it prints `x_01` as it seems like it is evaluating the expression. I am closing the issue and if anyone finds a similar current issue, feel free to reopen it.
