### ISSUE TITLE
And(x > 2,x < oo).as_set() returns EmptySet()

### ISSUE THREAD

**Issue by aktech** [sympy/sympy#8777]
`And(x > 2,x < oo).as_set()` returns `EmptySet()`
```python
In [1]: from sympy import *
In [2]: x = symbols('x')
In [3]: And(x>2,x<oo).as_set()
Out[3]: EmptySet()
```
It should return `(2, oo)`

**Comment by smichr** [comment]
The culprit is 

```
>>> (x<oo).as_set()
EmptySet()
```

But if assumptions allow, the solution is obtained:

```
>>> x = var('x',finite=True); And(x > 2,x < oo).as_set()
EmptySet()
>>> x = var('x',real=1,finite=True); And(x > 2,x < oo).as_set()
(2, oo)
```

**Comment by aktech** [comment]
@smichr 
and the reason behind that culprit:
line 435 inequalities.py
```python
if valid((start + end)/2 if start != S.NegativeInfinity else end - 1):
            sol_sets.append(Interval(start, end, True, True))
```
The algorithm is not able to handle the situation when `start` and `end` both are infinity (positive and/or negative) as 
(start + end)/2 returns nan.
