### ISSUE TITLE
substitution of symbols with 'real' assumption does not work

### ISSUE THREAD

**Issue by thisch** [sympy/sympy#8782]
```
from sympy import *
x, y, z, r = symbols(r'x y z r')
b = -1/r
rxyz = sqrt(x**2 + y**2 + z**2)
print(b.subs(dict(r=rxyz))) 
```
outputs ``-1/sqrt(x**2 + y**2 + z**2)``

whereas in the following example ``r`` in ``b`` does not get substituted if ``x``,``y``,``z`` and ``r`` are real valued:
```
from sympy import *
x, y, z, r = symbols(r'x y z r', real=True)
b = -1/r
rxyz = sqrt(x**2 + y**2 + z**2)
print(b.subs(dict(r=rxyz))) 
```
outputs: ``-1/r``

**Comment by asmeurer** [comment]
That's because `dict(r=rxyz)` is shorthand for `{'r': rxyz}`, and the string `'r'`gets translated to `Symbol('r')` (with no assumptions). Using this syntax is not recommended, for exactly this reason. Use `{r: rxyz}` instead.

**Comment by thisch** [comment]
Thx for the info.
