### ISSUE TITLE
create Root object

### ISSUE THREAD

**Issue by smichr** [sympy/sympy#8789]
Although some of this is discussed in [here](https://groups.google.com/forum/#!searchin/sympy/Fateman/sympy/40d-NGT_gF4/SJCETmfTfbkJ) I did not want this issue to get buried in the discussion.  When solving a radical expression like the following, SymPy's use of the principle root make solve miss a solution:

```
>>> eq
-x + (x**3 - 3*x**2)**(1/3) + 4/3
>>> solve(_, check=0)
[-8*sqrt(6)/9 + 8/3, 8*sqrt(6)/9 + 8/3]  <--------- both are solutions (as can be seen graphically)
>>> [eq.subs(x,i).n() for i in _]
[1.2659863237109 + 0.730917544784875*I, 0.e-124]  <-- the first one does not appear to be a soln

Here's a case where the root is rational:

>>> eq=eq-S(1)/3; eq
-x + (x**3 - 3*x**2)**(1/3) + 4/3
>>> solve(eq)
[]
>>> solve(eq, check=False)
[1/3]
>>> eq.subs(x,S(1)/3)
2/3 + 2*(-1)**(1/3)/3
```

The 1/3 does not appear to be a solution because the principle value of the root is being used rather than the real value:

```
>>> root(-1,3).n()
0.5 + 0.866025403784439*I
>>> real_root(-1, 3)
-1
```

Note that nsolve cannot find the root either because of this issue:

```
>>> nsolve(eq,.33)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "sympy\solvers\solvers.py", line 2532, in nsolve
    return findroot(f, x0, **kwargs)
  File "c:\Python26\lib\site-packages\mpmath\calculus\optimization.py", line 975
, in findroot
    % (norm(f(*xl))**2, tol))
ValueError: Could not find root within given tolerance. (2.60832 > 2.1684e-19)
Try another starting point or tweak arguments.
>>> nsolve(eq,.33+.01j)  # try an initial guess that is off the real axis
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "sympy\solvers\solvers.py", line 2532, in nsolve
    return findroot(f, x0, **kwargs)
  File "c:\Python26\lib\site-packages\mpmath\calculus\optimization.py", line 975
, in findroot
    % (norm(f(*xl))**2, tol))
ValueError: Could not find root within given tolerance. (2.60832 > 2.1684e-19)
Try another starting point or tweak arguments.
```

How should a formula be written that will allow one to verify that 1/3 is a solution?

**Comment by smichr** [comment]
One way to do it for roots would be to return something like:

```python
>>> def Root(a, b, i=None):
...     return a**(S.One/b)*exp(2*I*Mod(i if i is not None else Dummy('i'), b)*pi/b)
...
>>> Root(a,b)
a**(1/b)*exp(2*I*pi*Mod(_i, b)/b)
>>> Root(a,b,0)
a**(1/b)
>>> [Root(-2,3,i).n(2, chop=True) for i in range(3)]
[0.63 + 1.1*I, -1.3, 0.63 - 1.1*I]
```

**Comment by asmeurer** [comment]
We already have RootOf, which can probably be made to handle this.

**Comment by smichr** [comment]
Do you mean for something like root(-2, 3, 1) we get back RootOf(x**3 + 2, 0) (both referring to the real root)?

**Comment by asmeurer** [comment]
I don't remember how RootOf counts roots if 0 is the real one or not.

**Comment by asmeurer** [comment]
The point is with RootOf is that even if the root is not principal you have enough information to recover the remaining roots.

**Comment by skirpichev** [comment]
> SymPy's use of the principle root make solve miss a solution

@smichr, I don't think that your examples are relevant here.

Take ``eq = x + (x**3 - 3*x**2)**(1/3) + 1`` (btw, there is a typo in bug description), your last equation, which now in ``solve()`` docstring.  ``1/3`` is not a solution for this equation, but for ``x + RootOf(y**3 - (x**3 - 3*x**2), y, 0) + 1`` (see diofant's PR diofant/diofant#493, that use this test).

Mathematica 7 (which like SymPy uses principal root of ``Expr[Log[x] y]`` as a definition for ``x^y``) also produces empty set as answer.
