### ISSUE TITLE
fibonacci(n).limit(n, oo) should be oo rather than fibonacci(oo)

### ISSUE THREAD

**Issue by pelegm** [sympy/sympy#8800]
This is consistent with `factorial(n).limit(n, oo)`, `subfactorial(n).limit(n, oo)`, etc.

**Comment by murgrehk** [comment]
lucas(n).limit(n, oo) should be oo rather than lucas(oo) as well. Because these two sequences are similar, I feel that these issues can be fixed in similar ways.
