### ISSUE TITLE
factorial(0).is_composite returns True, the answer however should be False

### ISSUE THREAD

**Issue by aka001** [sympy/sympy#8807]
>>> factorial(0).is_composite
True

**Comment by pelegm** [comment]
The real bug is that 1 is considered composite. This appears in `core/assumptions.py`, in the following line:
```python
    'composite      ==  integer & positive & !prime',
```
there's a relevant discussion in #8081, but this is absolutely a bug.

**Comment by pelegm** [comment]
Oh, and it shouldn't be `None` but rather `False`. 1 is not composite.

**Comment by aka001** [comment]
@pelegm true that. Edited.

**Comment by skirpichev** [comment]
Perhaps, we can replace `==` with `->` (implies)
