### ISSUE TITLE
asymmetry in roots result for quadratic expression

### ISSUE THREAD

**Issue by smichr** [sympy/sympy#8813]
```python
>>> roots(Poly((z - 1)**2 - y**2, y))
{sqrt((z - 1)**2): 1, -sqrt((z - 1)**2): 1}
>>> roots(Poly(z**2 - y**2, y))
{-z: 1, z: 1}  # <--- in this case roots realizes sqrt(z**2) is +/-z but not in the former case
```

It would be preferably to have the former result be +/-(z - 1), too.

**Comment by jugnu** [comment]
But : 
>>> roots(Poly(x**2 - y**2),y)
{x: 1, -x: 1}     +/- format..    // There is only a difference of symbol yet we are getting a +/- format
>>> roots(Poly(x**2 - y**2),x)
{-y: 1, y: 1}
How change in symbols are giving differnt answer to same equation ???

**Comment by smichr** [comment]
The order that items are printed in a dictionary can vary. In both cases the keys are +/-s where s is the symbol you solve for so all's well there.

**Comment by asmeurer** [comment]
I seem to remember opening an issue for this before. The quadratic equation can always denest `sqrt(x**2) = x` because it automatically includes both +/- (and `sqrt(x**2)` always equals `+/- x`).

**Comment by darkcoderrises** [comment]
hi, can anyone mentor me in fixing this bug?

**Comment by smichr** [comment]
I thought the root of the problem is somewhere in preprocess_roots of polyroots, but making the change there would require more insight than I currently have for the low-level workings of polys. I would be more inclined to make the change in roots_quadratic as

```
diff --git a/sympy/polys/polyroots.py b/sympy/polys/polyroots.py
index 2880232..a0c9834 100644
--- a/sympy/polys/polyroots.py
+++ b/sympy/polys/polyroots.py
@@ -7,7 +7,8 @@
 from sympy.core.symbol import Dummy, Symbol, symbols
 from sympy.core import S, I, pi
 from sympy.core.compatibility import ordered
-from sympy.core.mul import expand_2arg
+from sympy.core.mul import expand_2arg, Mul
+from sympy.core.power import Pow
 from sympy.core.relational import Eq
 from sympy.core.sympify import sympify
 from sympy.core.numbers import Rational, igcd
@@ -53,6 +54,20 @@ def roots_quadratic(f):
     a, b, c = f.all_coeffs()
     dom = f.get_domain()

+    def _sqrt(d):
+        co = []
+        other = []
+        for di in Mul.make_args(d):
+            if di.is_Pow and di.exp.is_Integer and di.exp % 2 == 0:
+                co.append(Pow(di.base, di.exp//2))
+            else:
+                other.append(di)
+        if co:
+            d = Mul(*other)
+            co = Mul(*co)
+            return co*sqrt(d)
+        return sqrt(d)
+
     def _simplify(expr):
         if dom.is_Composite:
             return factor(expr)
@@ -71,7 +86,7 @@ def _simplify(expr):
         if not dom.is_Numerical:
             r = _simplify(r)

-        R = sqrt(r)
+        R = _sqrt(r)
         r0 = -R
         r1 = R
     else:
@@ -83,7 +98,7 @@ def _simplify(expr):
             d = _simplify(d)
             B = _simplify(B)

-        D = sqrt(d)/A
+        D = _sqrt(d)/A
         r0 = B - D
         r1 = B + D
         if a.is_negative:
```

and then use the test of this issue to hit one of those lines and then see if there is another test that can hit the other line where `_sqrt` is used (and if that's impossible then just use regular sqrt there.

So two steps: modify the code and add tests that cover the new lines added in the appropriate place. I suspect the tests should go in something like `test_roots_quadratic` in `test_poly_roots`.

**Comment by darkcoderrises** [comment]
I belive while adding tests i have to do something like:-
assert  roots_quadratic(Poly((z - 1)**2 - y**2, y)) == [1-z,z-1]
but print roots_quadratic gives me [-sqrt((z - 1)**2), sqrt((z - 1)**2)]

please tell me where am i wrong

**Comment by smichr** [comment]
> please tell me where am i wrong

Probably nothing. I only tested that roots_quadratic gave the right result. But these sort of expressions you are considering are binomials so the changes are probably best made there. And you won't need a loop since you can check to see what the degree of the binomial is and then filter out any powers that have a matching exponent.

Perhaps the change is best made in `roots_binomial`. I'm guessing that roots_quadratic should be left alone since that's a private method and one should be calling roots (not `roots_quadratic`) when trying to get the roots of an expression.

**Comment by darkcoderrises** [comment]
When you said:
Perhaps the change is best made in roots_binomial. I'm guessing that roots_quadratic should be left alone since that's a private method and one should be calling roots (not roots_quadratic) when trying to get the roots of an expression.

did you mean about the changes for tests or the code?.
1-if tests then probably i dint explain properly what i was saying. 
when we do  roots(Poly((z)3 - y3, y)) result comes z,(1+i)*z , (1-i)z but when we do 
roots(Poly((z - 1)3 - y3, y)); result that come is expanded and shows cube root of (z^3-3z^2+3z-1)
so i was suggesting change in the code you proposed.

2-if you were talking about the code only, then i am afraid that i could not understand what you said.(i cant find any roots_binomial in places other then test documents)

**Comment by smichr** [comment]
> did you mean about the changes for tests or the code?.

yes. At line 357 of polyroots.py `alpha` is calculated. Those factors that have exponents, e, with `e % n == 0` should be factored out. If base is `2*x**4` and `n=2` then `base = x**2*root(2, 2)`.

**Comment by smichr** [comment]
> At line 357 of polyroots.py alpha is calculated

It's too late to check there since the expression has already been expanded at that point. I'm not sure that using factor there is a good idea, either. If not, then the expression needs to be caught before it is expanded, e.g. `x**3 - 2*(y-1)**3` becomes `x**3 - 2*y**3 + 6*y**2 - 6*y + 2` by the time it gets to `roots_binomial`.

**Comment by smichr** [comment]
Perhaps the following?

```diff
diff --git a/sympy/polys/polyroots.py b/sympy/polys/polyroots.py
index 2880232..36aacdd 100644
--- a/sympy/polys/polyroots.py
+++ b/sympy/polys/polyroots.py
@@ -7,7 +7,7 @@
 from sympy.core.symbol import Dummy, Symbol, symbols
 from sympy.core import S, I, pi
 from sympy.core.compatibility import ordered
-from sympy.core.mul import expand_2arg
+from sympy.core.mul import expand_2arg, Mul
 from sympy.core.relational import Eq
 from sympy.core.sympify import sympify
 from sympy.core.numbers import Rational, igcd
@@ -856,7 +856,28 @@ def roots(f, *gens, **flags):
         f = Poly(poly, x, field=True)
     else:
         try:
+            expr = f
             f = Poly(f, *gens, **flags)
+            if not isinstance(expr, Poly) and f.length() == 2 and f.degree() != 1:
+                # see if there are powers in the constant that match the degree
+                con = expr.as_independent(*gens)[0]
+                n = f.degree()
+                npow_bases = []
+                others = []
+                for p in Mul.make_args(con):
+                    if p.is_Pow and not p.exp % n:
+                        npow_bases.append(p.base**(p.exp/n))
+                    else:
+                        others.append(p)
+                if npow_bases:
+                    b = Mul(*npow_bases)
+                    B = Dummy()
+                    d = roots(Poly(expr - con + B**n*Mul(*others), *gens, **flags), *gens, **flags)
+                    rv = {}
+                    for k, v in d.items():
+                        rv[k.subs(B, b)] = v
+                    return rv
+
         except GeneratorsNeeded:
             if multiple:
                 return []

```

**Comment by smichr** [comment]
ping @darkcoderrises -- are you interested in making the changes and creating a PR?

**Comment by darkcoderrises** [comment]
@smichr sir i have created the changes but i was just understanding them.Sorry for the delay

**Comment by darkcoderrises** [comment]
please check https://github.com/sympy/sympy/pull/8911

**Comment by darkcoderrises** [comment]
I am not able to fix the last remaining test.Please can u suggest me something?

**Comment by smichr** [comment]
This is fixed for quadratic and binomial expressions.
