### ISSUE TITLE
make it easier to compare numbers

### ISSUE THREAD

**Issue by smichr** [sympy/sympy#8815]
```
>>> a=(-sqrt(2)).n(2); a
-1.4
>>> b=S('-1.4').n(2); b
-1.4
>>> a==b
False
```

It should be easier to compare numbers. Perhaps something like the following should be incorporated into equality testing for numbers?

```
>>> from sympy.core.numbers import mpf_norm as F
>>> F(a._mpf_,2) == F(b._mpf_,2)
True
```

Although string comparisons are often used successfully, a string comparison failed when using GMPY. The run is [here](https://travis-ci.org/sympy/sympy/builds/46880654) and the particular error is shown [here](https://travis-ci.org/sympy/sympy/jobs/46880686). The test was

```python
eq = (531441*x**11 + 3857868*x**10 + 13730229*x**9 + 32597882*x**8 +
    55077472*x**7 + 60452000*x**6 + 32172064*x**5 - 4383808*x**4 -
    11942912*x**3 - 1506304*x**2 + 1453312*x + 512)
assert str(RootOf(eq, 1).n(2)) == '-1.4 - 0.77*I'
```

#### I am not sure if that error is intermittent or if there was some invisible character that made the test fail. The last run [here](https://travis-ci.org/smichr/sympy/builds/47702371) did not fail.

**Comment by mihir-w** [comment]
Hi, I am new to open source in general and am trying to solve this bug.
While comparing the Floats, mpf_eq function is used where a._mpf_ and b._mpf_ are passed as arguments.    
As mentioned above, if normalized tuples are instead sent as arguments ( With precision being the greater precision of the two numbers ) to mpf_eq, comparison works fine.
Does this approach seem correct ?

**Comment by smichr** [comment]
I don't think so. I think the simpler problem has to be solved first: how to get the above comparison to succeed. The following are a few things that I tried quickly to show some different aspects of the problem.

```
We know that a has a `_prec` of 10. What do we need to compare to it to see that it is the same? Checking...

```
>>> F(Float((-sqrt(2)).n(2),2)._mpf_,10)==F(Float('-1.4',2)._mpf_,10)
False
>>> F(Float((-sqrt(2)).n(2),2)._mpf_,10)==F(Float('-1.41',2)._mpf_,10)
False
>>> F(Float((-sqrt(2)).n(2),2)._mpf_,10)==F(Float('-1.414',2)._mpf_,10)
True
```

We can't fool around like that when we want to write an expression that will compare with a Float evaluated to a given decimal place. Let's see how much lower we can change precision before the number *itself* fails to compare equally:

```
>>> F((-sqrt(2)).n(2)._mpf_,10)==F((-sqrt(2)).n(2)._mpf_,9)
True
>>> F((-sqrt(2)).n(2)._mpf_,10)==F((-sqrt(2)).n(2)._mpf_,8)
True
>>> F((-sqrt(2)).n(2)._mpf_,10)==F((-sqrt(2)).n(2)._mpf_,7)
False
```

So perhaps we have to reduce the `_prec` until it actually rounds the number:

```
>>> F(Float((-sqrt(2)).n(2),2)._mpf_,9)==F(Float('-1.4',2)._mpf_,9)
False
>>> F(Float((-sqrt(2)).n(2),2)._mpf_,8)==F(Float('-1.4',2)._mpf_,8)
False
>>> F(Float((-sqrt(2)).n(2),2)._mpf_,7)==F(Float('-1.4',2)._mpf_,7)
True
```

That doesn't seem like a good idea, however. How do we find how much lower we need to go to get a failure in comparison?

```
>>> for i in range(3,10):
...   a = sqrt(2).n(i)
...   p = a._prec
...   while 1:
...     if F(a._mpf_, a._prec)!=F(a._mpf_,p):break
...     p -= 1
...   print i, a._prec - p
...
3 1
4 2
5 1
6 2
7 2
8 1
9 4
```

(But that won't work if we have an exact decimal in binary, e.g. 1/2 instead of sqrt(2) --but it's easy to detect that case. Maybe that is the way to go.)

Perhaps we should just compare strings:

```
>>> str(sqrt(2).n(2))==str(S('1.4').n(2))
True
```

But that bit me in tests here (so I just worked around the issue):

```
File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/sympy-0.7.6_git-py2.7.egg/sympy/polys/tests/test_rootoftools.py", line 227, in test_RootOf_evalf
    assert str(RootOf(eq, 1).n(2)) == '-1.4 - 0.77*I'
AssertionError
```

Note:  A mistake that I made which you must watch out for, however, is to differentiate between binary precision and decimal precision (usually abbreviated dps in the code base). In the F-call in the OP I used dps when I should have been using binary precision.

**Comment by mihir-w** [comment]
Pardon me if this seems stupid, but here is what I am thinking.

Consider the following example:
```
>>> a = sqrt(5).n(3)
>>> b = Float(2.24,3)
>>> dps_to_prec(3)
13
>>> F(a._mpf_,13)
(0, 4579L, -11, 13)
>>> F(a._mpf_,12)
(0, 1145L, -9, 11)
>>> F(a._mpf_,10)
(0, 143L, -6, 8)
>>>
>>> F(b._mpf_,13)
(0, 1147L, -9, 11)
>>> F(b._mpf_,10)
(0, 287L, -7, 9)
>>> F(b._mpf_,8)
(0, 143L, -6, 8)
```

So here the two tuples finally became equal when the numbers have failed *twice*.  So we would also need to check *how many times* the number have failed before the required precision can be known and used in `mpf_norm` .

Instead what if we keep the numbers at default precision. Whenever a user requests a rounding off, round off the float and add zeroes at the end ( Don't print the zeros on output). So whenever any two Floats are compared, `_mpf_` function would be sufficient to compare and there would be no need for `mpf_norm`.
I know we are not doing exactly what the user asked, but this way changes to code will be less and easier to understand. Will change and run the tests but does the method seem correct ?

Regarding string comparison, can you please briefly explain the error in the tests. I tried but couldn't understand it.

Also thanks for the note, was committing the same mistake while using precision.

**Comment by smichr** [comment]
I don't like the idea of comparing the numbers at lower precision since there is no guarantee that the original numbers are actually the same, then. I think that recomputing the Floats from strings with precision defaulting to the string length is the most robust way to go:

```
>>> a=sqrt(2).n(3)
>>> b=Float('1.41','')
>>> Float(str(a),'') == Float(str(b),'')
True
```

That last step would happen in a comparison routine for floats so in practice one would just assert `a == Float('1.41','')` and get True instead of the current False value.

As to the error in the tests, I document that in the opening paragraph above so others can find it easily.

**Comment by mihir-w** [comment]
Just a fundamental doubt, I guess;
`test_numbers.py` has the following function:
```
def test_Float_eq():
    assert Float(.12, 3) != Float(.12, 4)
    assert Float(.12, 3) == .12
    assert 0.12 == Float(.12, 3)
    assert Float('.12', 22) != .12
```

Why are 1st and 4th tests not supposed to be equal ? They have different precision, but their values are same.

**Comment by smichr** [comment]
For the first case, it seems like they shouldn't be the same if they have different precisions. For the last case, I'm not sure. If we do Float(.12,3)-.12 (2nd case) we get -4.88281249999556e-6 while the same difference for the last case gives 0 (and actually does so with n=14 instead of n=22).

**Comment by smichr** [comment]
(I'm just assigning myself to watch this issue, not to fix it.)
