### ISSUE TITLE
lambdify precision loss with module=mpmath from high-precision Floats

### ISSUE THREAD

**Issue by cbm755** [sympy/sympy#8818]
Floats with more than 16 digits are converted to double precision somewhere.

Consider:

```
In [52]: x = symbols('x')

In [53]: g = sqrt(2) - x

In [54]: h = g.evalf(64)

In [55]: g
Out[55]: -x + sqrt(2)

In [56]: h
Out[56]: -x + 1.414213562373095048801688724209698078569671875376948073176679738
```

Note `h` has a 64-digit accurate Float in it (and the value is correct).

But lambdifying `g` and `h` is not same:

```
In [57]: f1 = lambdify(x, g, modules='mpmath')

In [58]: f2 = lambdify(x, h, modules='mpmath')

In [59]: f1(N(sqrt(2),64))
Out[59]: 1.899113549151959749494648453912391430844193166723988993255955998e-65

In [60]: f2(N(sqrt(2),64))
Out[60]: 0.00000000000000009667293313452913037187168859825586442682332026201917202971226475
```

The help string for `f2` shows no loss: 

```
In [64]: f2?
Type:        function
String form: <function <lambda> at 0x7f6a43bd92a8>
File:        Dynamically generated function. No source code available.
Definition:  f2(_Dummy_22)
Docstring:
Created with lambdify. Signature:

func(x)

Expression:

-x + 1.414213562373095048801688724209698078569671875376948073176679738
```

I haven't figured out how to look at the actual code yet, but somewhere something is being converted to double-precision (which might be fine for module=numpy but should not happen here).

**Comment by cbm755** [comment]
Tracked down a bit: lambdify.py line 376 calls python's builtin `eval` from a string representation of the function.  This will convert the 64 digit float into a double precision.

Perhaps this is a design decision of `lambdify`: currently it cannot support more than double precision.  But then what is "module=mpmath" supposed to do here?

**Comment by moorepants** [comment]
If you check the history of lambdify, someone refactored it long back and added the "modules" support. I personally never understood why the sympy or mpmath modules are necessary at all, because evalf and subs already give that functionality. I'd be fine with removing them because I've never heard of a use case.

**Comment by asmeurer** [comment]
modules='mpmath' is used in nsolve (the function is lambdified and passed to `mpmath.findroot`). This bug prevents you from using higher precision in nsolve, even if you set `mpmath.mp.dps` manually. 

CC @scopatz, this is the source of the problem we were having.

**Comment by scopatz** [comment]
I see, @asmeurer. So is the solution to remove that line? Or to have a kwarg to turn it off?

**Comment by asmeurer** [comment]
Fix is at https://github.com/sympy/sympy/pull/11862.

**Comment by csubich** [comment]
This issue appears to have resurfaced, and it is not confined to modules='mpmath'.  I can reproduce it with modules='spympy':

<code>import mpmath as mp
import sympy as sp
mp.mpf.dps = 50

x = sp.symbols('x')

f = sp.sqrt(2)-x
g = f.evalf(n=16)
h = f.evalf(n=32)

print('Sympy version ' + sp.__version__)
print('Functions')
print(f)
print(g)
print(h)

# Substitute:

print('Substitute')
print(sp.N(f.subs({x:sp.sqrt(2)}),48))
# Expected: 0
print(sp.N(g.subs({x:sp.sqrt(2)}),48))
# Expected: O(10^-16)
print(sp.N(h.subs({x:sp.sqrt(2)}),48))
# Expected: O(10^-32)

l1 = sp.lambdify(x,f,modules='sympy')
l2 = sp.lambdify(x,g,modules='sympy')
l3 = sp.lambdify(x,h,modules='sympy')

# Lambdify
print('Lambdify')
print(sp.N(l1(sp.sqrt(2)),48))
# Expected: 0
print(sp.N(l2(sp.sqrt(2)),48))
# Expected: O(10^-16)
print(sp.N(l3(sp.sqrt(2)),48))
# Expected: O(10^-32)
</code>

Prints:

<code>
Sympy version 1.3
Functions
-x + sqrt(2)
-x + 1.414213562373095
-x + 1.4142135623730950488016887242097
Substitute
0
1.34062062876423898400993134914443409893233202620e-17
4.83556557829952435259872215411537137823424415914e-34
Lambdify
0
-1.25371671790502177712854645019908198073176679738e-16
9.66729331345291303718716885982558644268233202620e-17
</code>
