### ISSUE TITLE
N(<decimal string>) limited to double precision

### ISSUE THREAD

**Issue by cbm755** [sympy/sympy#8821]
Is input like `N('1.23')` supposed to work?  It is limited to double precision.

````
In [18]: s = str(pi.evalf(1024))  # very accurate pi string

In [19]: a = Float(s, 128)

In [20]: sin(a)   # looks good
Out[20]: -3.3218e-130

In [21]: 

In [21]: b = N(s, 128)

In [22]: sin(b)  # not good
Out[22]: 0.00000000000000012246467991473531772260659322749979970830539012997919494882577162608696099732581037750932552756901365545642854007441419
````

Let's look at the `N` code:
````
return sympify(x).evalf(n, **options
````
So this happens because `N` runs `sympify(str)` which has no knowledge of `n`.

It should be easy enough to special-case strings that contain a decimal point (and only digits).  We could call Float directly in those cases.

Even so, some cases that would still lose precision: `N('1.0*x')`, `N('1.0/3.0',128)` but meh, diminishing returns at some point!

**Comment by cbm755** [comment]
I looked a bit deeper to see what `sympify(string)` does.  It seems to coerce to `float` (lowercase Python float, double precision).  Is it desirable to change that?

i.e., do we want this
````
p = sympify('3.141592653589793238462643383279502884197169399375105820974944592307816406286')
````
to be the same as:
````
q = Float('3.141592653589793238462643383279502884197169399375105820974944592307816406286', '')
````

**Comment by smichr** [comment]
> to be the same as:

I would vote 'yes' under the assumption that you should get what you are asking for, especially in a *symbolic* system like SymPy -- if one typed those symbols, it is fair to expect that they wanted all of them to be represented in the returned number.

**Comment by cbm755** [comment]
Yes my feelings too.  I'll try to take a look at this.

For the record, may need to be a bit careful:
````
In [103]: a = Float('1.234','')

In [104]: a
Out[104]: 1.234

In [105]: srepr(a)
Out[105]: "Float('1.233994', prec=4)"

In [106]: b = sympify('1.234')

In [107]: srepr(b)
Out[107]: "Float('1.234', prec=15)"
````
Where note the new approach would give a different `prec=`.

Also: I was wrong when I said it coerces to `float`.

**Comment by petarmaric** [comment]
I think the same underlying issue is causing #2439

**Comment by cbm755** [comment]
@petarmaric:  can you check if my proposed merge request #8826 helps?  I would, but cannot easily install:
````
 pip install --user beam_integrals
Downloading/unpacking beam-integrals
  Could not find any downloads that satisfy the requirement beam-integrals
Cleaning up...
No distributions at all found for beam-integrals
````

**Comment by petarmaric** [comment]
Sorry for the trouble but I still feel `beam_integrals`, altough quite stable, needs a bit more work before "blessing" an official release. If you wish you can grab the current dev version from https://bitbucket.org/petar/beam_integrals

Also, I'm sorry to say your proposed merge request #8826 has no effect on my problems, see https://github.com/sympy/sympy/issues/2439#issuecomment-70339616 for more details.
