### ISSUE TITLE
python 3.4 and lambdify - SyntaxError: more than 255 arguments

### ISSUE THREAD

**Issue by maito78** [sympy/sympy#8824]
Hi, I am working on a code where I used lambdify for more than 256 elemets.
I'm using IPython Notebook, and with python 2.7 I have no problems, but with Python 3.4 I obtain this error: *SyntaxError: more than 255 arguments*
Here an example:

```python
def makeMatrix(mySymbol,n,m):
    '''makes a lambdafiable matrix'''

    myMatrix = sp.zeros(n,m)

    for i in range(n):
        for j in range(m):
            myStr = mySymbol+"_"+str(i)+"_"+str(j)

            myMatrix[i,j] = sp.sympify(myStr)

    return myMatrix


varP = makeMatrix('p', 100, 3)
y = varP[1,1] + varP[1,2]
```

```python
g = sp.lambdify(varP,y)

 File "<string>", line 1
SyntaxError: more than 255 arguments
```

When the code runs in Blender the error is:
```python
>>> sp.lambdify(cn[0], cn[1])
Traceback (most recent call last):
  File "<blender_console>", line 1, in <module>
  File "C:\Users\m2P0\blender\2.72\python\lib\sympy\utilities\lambdify.py", line 312, in lambdify
    return eval(lstr, namespace)
  File "<string>", line 1
SyntaxError: more than 255 arguments
```

**Comment by moorepants** [comment]
You don't need a custom function to create varP. `Matrix` has this built it:

```python
varP = sp.Matrix(100, 3, lambda i, j: sp.Symbol('p_{}_{}'.format(i, j)))
```
Can you use a `DeferredVector` of length 100 * 3 for this instead? Ideally, `MatrixSymbol` would work with `lambdify`, but this is an open bug: https://github.com/sympy/sympy/issues/8512.

The failure must be coming from the generated lambda function having a length limit on the number of characters in its arguments or something.

**Comment by maito78** [comment]
Thanks for the advice.
`DeferredVector` works well. It is also possible `lambdify` more than one DeferredVector at time.

```python
x1 = DeferredVector( 'x1' )
x2 = DeferredVector( 'x2' )
x3 = DeferredVector( 'x3' )

gL = lambdify([x1, x2, x3], some_equations)
```

**Comment by jcrist** [comment]
This is a limitation of Python, closing.
