### ISSUE TITLE
NameError: global name 'z1e400' is not defined

### ISSUE THREAD

**Issue by escher9** [sympy/sympy#8831]
![bandicam 2015-01-16 17-46-52-905](https://cloud.githubusercontent.com/assets/5399495/5773609/b0349cd0-9da7-11e4-8e1e-00006b641063.jpg)

**Comment by pelegm** [comment]
Please avoid reporting issues like that. There are several problems with it:

1. it's not searchable
2. it's hard do read
3. it's impossible to understand what you've tried to do

**Comment by aktech** [comment]
This should be closed.

**Comment by asmeurer** [comment]
We would need to see what the `tangent_eq` is to reproduce this, unless someone wants to dig through the code and guess how it happened.

**Comment by oscarbenjamin** [comment]
This issue has insufficient information and should probably be closed.

**Comment by asmeurer** [comment]
@escher9 if you can still reproduce this, please paste the full expression that you are plotting here (just pating `str(tangent_eq)` should be fine) and reopen the issue.
