### ISSUE TITLE
powsimp drops factor

### ISSUE THREAD

**Issue by smichr** [sympy/sympy#8836]
```python
>>> a,b=exp(I*pi/3),root(-1,3)
>>> powsimp(a)
exp(I*pi/3)
>>> powsimp(b)
(-1)**(1/3)
>>> a*b
(-1)**(1/3)*exp(I*pi/3)
>>> powsimp(_)
(-1)**(1/3)
>>> _.n(2)
0.5 + 0.87*I
>>> (a*b).n(2)
-0.5 + 0.87*I
```

The problem is with bkey which, for exp(I*pi/3), returns 

```python
>>> bkey(exp(I*pi/3))
((-1, 3), 1)
```

**Comment by mihir-w** [comment]
`bkey` is returning the same tuple for both `exp(I*pi.3)` and `root(-1,3)` which is causing problem. ( Factor gets dropped). If instead a check is made, whether the tuple returned is already present or not and then accordingly changing `c_powers` and `common_b`, I am getting correct answers.
Does this approach seem correct ?
Thanks
