### ISSUE TITLE
latest documentation links are dead

### ISSUE THREAD

**Issue by phdoerfler** [sympy/sympy#8845]
All the links in latest are dead but work just fine in dev.

Dead:
http://docs.sympy.org/latest/modules/galgebra/index.html

Not dead:
http://docs.sympy.org/dev/modules/galgebra/

**Comment by debugger22** [comment]
Something converted `ga.html` to `GA.html` in `latest` docs. @asmeurer

**Comment by aktech** [comment]
> Dead:
http://docs.sympy.org/latest/modules/galgebra/index.html

It's working.
