### ISSUE TITLE
python setup.py clean is not cross platform

### ISSUE THREAD

**Issue by moorepants** [sympy/sympy#8857]
`find` and `rm` are not generally available on Windows. This should switch to using Python builtin functions to do the same thing.

**Comment by darshanime** [comment]
Is this fine ?

```python


def run(self):
        import platform
        import os
	if platform.system()=='Windows':
		os.system("del /S /P *.pyc")
		os.system("del python-build-stamp-2.4")
		os.system("del MANIFEST")
		os.system("deltree /Y build")
		os.system("deltree /Y dist")
		os.system("deltree /Y doc/_build")
		os.system("del sample.tex")
	
	else
        	os.system("find . -name '*.pyc' | xargs rm -f")
        	os.system("rm -f python-build-stamp-2.4")
        	os.system("rm -f MANIFEST")
        	os.system("rm -rf build")
        	os.system("rm -rf dist")
        	os.system("rm -rf doc/_build")
        	os.system("rm -f sample.tex")
```


I am not able to get the indentation right here. Will correct it in the actual file once you approve this.

**Comment by moorepants** [comment]
That solution will likely work. I was thinking more of using `os.remove` and other python commands. The advantage to using the os module, is that all the if statements are taken care for you under the hood and you only have to write one version for all os's. But this is a solution and if you submit it as a PR it can be reviewed. Please show that it does what it is supposed to do on Windows, as we don't have automatic testing Windows.

**Comment by asmeurer** [comment]
It would be better to use shutil.rmtree than os.system.

**Comment by amitsaha** [comment]
+1 to avoiding ``os.system``.

**Comment by darshanime** [comment]
Thank you for the suggestions. 

How about this ?

```python

import os
import shutil

for root, dirs, files in os.walk("."):
	for file in files:
   		if file.endswith('.pyc') and os.path.isfile:
			os.remove(os.path.join(root, file)) 
			

if os.path.isfile("python-build-stamp-2.4"): os.remove("python-build-stamp-2.4")
if os.path.isfile("MANIFEST"): os.remove("MANIFEST")
if os.path.isdir("build"): shutil.rmtree("build")
if os.path.isdir("dist"): shutil.rmtree("dist")
if os.path.isdir("doc/_build"): shutil.rmtree("doc/_build")
if os.path.isfile("sample.tex"): os.remove("sample.tex")
```

**Comment by moorepants** [comment]
Please submit this as a pull request. It is much easier to comment on the code there. Thanks.
