### ISSUE TITLE
Incorrect simplification of log function with base 10

### ISSUE THREAD

**Issue by alec-kalinin** [sympy/sympy#8866]
Consider the following code:

import sympy as sp
x = sp.Symbol('x')
f = sp.log(x, 10, evaluate=False)
print (f.subs(x, 10))
g = sp.simplify(f)
print (g.subs(x, 10))

The result should be the same and equals to 1. But the answer is:
1
log(10)

**Comment by aktech** [comment]
Culprit is this:
```python
In [3]: simplify(log(x, 10, evaluate=False))
Out[3]: log(x)

In [4]: simplify(log(x, 10))
Out[4]: log(x)/log(10)
```

**Comment by pelegm** [comment]
Simply:
```python
>>> simplify(log(x, 10, evaluate=False))  ## should be log(x, 10)
log(x)
```

**Comment by aktech** [comment]
Yes, `evaluate=False` is meaningless.
