### ISSUE TITLE
Subfactorial of nonintegers

### ISSUE THREAD

**Issue by pelegm** [sympy/sympy#8876]
After looking at #8875, I have realized that `subfactorial`'s docstring suggests
```python
"""
...
This function is generalized to noninteger arguments [2]_ as

.. math:: !x = \Gamma(x + 1, -1)/e
...
"""
```
But the actual code does not evaluate any nonintegers:
```python
    @classmethod
    def eval(cls, arg):
        if arg.is_Number:
            if arg.is_Integer and arg.is_nonnegative:
                return cls._eval(arg)
            elif arg is S.Infinity:
                return arg
```

Thus we have two options: implement it, or update the docstring.

**Comment by luviiit** [comment]
@pelegm, to calculate the subfactorial of nonintegers, we will need to evaluate the value of incomplete gamma function for noninteger. Should I calculate the value of this function using ```gammainc``` function of ```mpmath```?
