### ISSUE TITLE
Unable to build documentation 

### ISSUE THREAD

**Issue by viv1** [sympy/sympy#8879]
While building documentation(from doc/ directory), following error is shown in log file:

# Sphinx version: 1.2.3
# Python version: 3.4.0
# Docutils version: 0.12 release
# Jinja2 version: 2.7.3
# Loaded extensions:
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/sphinx/cmdline.py", line 253, in main
    warningiserror, tags, verbosity, parallel)
  File "/usr/local/lib/python3.4/dist-packages/sphinx/application.py", line 119, in __init__
    self.setup_extension(extension)
  File "/usr/local/lib/python3.4/dist-packages/sphinx/application.py", line 333, in setup_extension
    mod = __import__(extension, None, None, ['setup'])
  File "ext/numpydoc.py", line 41
    title_re = re.compile(ur'^\s*[#*=]{4,}\n[a-z0-9 -]+\n[#*=]{4,}\s*',
                                                                     ^
SyntaxError: invalid syntax

**Comment by viv1** [comment]
Python doc building code is only python2 compatible, and not python3

Python3 has implicit provision for unicode strings.So, 'ur' does not make sense. Replacing all occurrences of "ur" with "r" (in 'doc/ext/numpydoc.py') solves this issue, BUT is now showing another error----------

Extension error:
Could not import extension numpydoc (exception: No module named 'StringIO')
make: *** [html] Error 1

**Comment by moorepants** [comment]
Yes, please use Python 2.6+ to build the docs.

**Comment by viv1** [comment]
But, if sympy supports python3, shouldn't we be able to build docs in python3 itself?
@moorepants

**Comment by moorepants** [comment]
Building the documentation is currently considered a "developer task" so no resources have been spent to make ti Python 3 compatible. You are welcome to remedy that. We'd surely like it to work on both versions of Python.

**Comment by viv1** [comment]
If you could direct me on how to go about it, I would like to try solving the issue.I have basic knowledge and experience with Python, C and a few more languages, and I can certainly learn other concepts, if required.
@moorepants

**Comment by moorepants** [comment]
You've already started the process. You simply try to run the doc build with Python 3 and see what errors you get. Then try to find out what is causing the error. Then change the code to something that works. That error you have is coming from numpydoc, maybe numpydoc isn't python 3 compatible.
