### ISSUE TITLE
MKS unitsystem does not have Hz and other units

### ISSUE THREAD

**Issue by ArkBrj** [sympy/sympy#8880]
I think the problem is in this fragment of code in mks.py:

units = [m, g, s, J, N, W, Pa, Hz]
all_units = []
for u in units:
    all_units.extend(prefix_unit(u, PREFIXES))
all_units.extend([v, a, p, G, c])

We add all derivative units like mHz, kHz and so on to all_units but we never add the originals.

**Comment by paramsingh** [comment]
Fixed this in #8989.
