### ISSUE TITLE
Subtracting waves in optics module

### ISSUE THREAD

**Issue by darshanime** [sympy/sympy#8887]
The Optics module enables working with waves.

However, subtracting the waves which follows intuitively results in the result being an instance of the `sympy.core.add.Add` class. This stops the user from accessing properties of the resultant wave like amplitude, phase etc. 

This can be fixed by simply returning the result of the  `__add__(self, other)` method with the amplitude of `other` multiplied by `-1`.

Is it a good idea to make this change ?

``` python
In [1]: from sympy.physics.optics import *
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-1-1d52e0c05aa5> in <module>
----> 1 from sympy.physics.optics import *

AttributeError: module 'sympy.physics.optics' has no attribute 'polarizing_beam_splitte'

In [2]: from sympy.physics.optics import TWave

In [3]: A,f,phi = symbols('A,f,phi')

In [4]: w1 = TWave(A, f)

In [5]: w2 = TWave(A, f, phi)

In [6]: w1+w2
Out[6]: TWave(sqrt(2*A**2*cos(phi) + 2*A**2), f, atan2(A*cos(phi) + A, A*sin(phi)))

In [7]: _.amplitude
Out[7]: 
   ____________________
  ╱    2             2 
╲╱  2⋅A ⋅cos(φ) + 2⋅A  

In [8]: w1 - w2
Out[8]: TWave(A, f) - TWave(A, f, phi)

In [9]: type(_)
Out[9]: sympy.core.add.Add

In [10]: (w1 - w2).amplitude
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-10-cea1328571ac> in <module>
----> 1 (w1 - w2).amplitude

AttributeError: 'Add' object has no attribute 'amplitude'
```

**Comment by kevinventullo** [comment]
Maybe it would be better to add the ability to multiply by scalars. Note that `-1*w1` is a Mul, not a TWave.

**Comment by darshanime** [comment]
Working on it !

**Comment by kevinventullo** [comment]
Hey I was thinking of adding __neg__, __sub__, and __mul__ in as well. Do you mind if I work on this?

**Comment by darshanime** [comment]
I implemented **mul** already. 
There is much to do here. We could surely work on this together !

**Comment by darshanime** [comment]
Ping if you want to discuss more.

**Comment by czgdp1807** [comment]
This is an important issue and should be fixed. Interested contributor may refer, https://github.com/sympy/sympy/pull/8908
