### ISSUE TITLE
Code generation documentation needs a major update

### ISSUE THREAD

**Issue by moorepants** [sympy/sympy#8889]
We now have C, Fortran, and Octave/Matlab code generators plus recent support was added for generating code for Matrix and MatrixSymbol objects. The current documentation on code generation is pretty sparse.

There is also support for Theano that isn't well documented in the prose documentation.

This is the main thing we have now: http://docs.sympy.org/latest/modules/numeric-computation.html (besides api docs, which are pretty good).

It would be great to have some thorough documentation showing how to use the code printing, code generators, and autowrapping features. These would probably get more use if we had nice docs.

This could be a nice task for a new contributor.

**Comment by smichr** [comment]
Perhaps it could include some discussion about using cse to optimize an expression calculation, too?

**Comment by moorepants** [comment]
Yes, more docs on cse would be nice too. This may be all there is: http://docs.sympy.org/0.7.0/modules/rewriting.html.

**Comment by jayesh92** [comment]
I was looking to fix up this issue. I'm not getting as to what else should be written for documenting the `utilities/codegen.py` . I also looked at the documentation at http://docs.sympy.org/latest/modules/utilities/codegen.html  and as far as I know the Sphinx documentation is also generated from the docstrings.
If you could help me get started with a few more use-cases, it would be a great help !

**Comment by moorepants** [comment]
The page you link to is mostly API documentation. The first bit is ok but needs to be expanded. We'd really like a nice tutorial/prose style page that shows how you can use the code gen. I'd start by reading the docstrings in the codegen module and checking out the examples directory to see if there are any examples.

The matrices docs give a good example by what I mean by "prose" documentation.

Some of the topics that need to be covered:

- printing all types of of code and using the various printer options for fortran, C, js, etc
- codegen examples for fortran, C, and octave/matlab (show how different optional args affect output)
- examples for autowrap and ufuncify using the different backends and options

**Comment by moorepants** [comment]
Maybe adding a new tutorial to: https://github.com/sympy/sympy/tree/master/doc/src/tutorial would be good.

**Comment by moorepants** [comment]
Or just expand this: https://github.com/sympy/sympy/blob/master/doc/src/modules/utilities/codegen.rst

**Comment by moorepants** [comment]
This, http://docs.sympy.org/latest/modules/numeric-computation.html, is also missing any mention of autowrap.

**Comment by moorepants** [comment]
Here is autowrap: http://docs.sympy.org/latest/modules/utilities/autowrap.html

So it seems there is mention of most things spread out in different places. It would be nice to consolidate the prose together into one document. The API (i.e. auto-generated from the docstrings) could remain with the module.

**Comment by tokencolour** [comment]
I would like to work on this.

**Comment by moorepants** [comment]
@tokencolour Sounds good. Let us know if you have any questions. Hopefully the conversation above is helpful.

**Comment by tokencolour** [comment]
Other than the examples embedded in the docstrings  of codegen.py, I found the following:

1. https://github.com/asmeurer/scipy-2014-tutorial/blob/master/tutorial_exercises/examples-code-generation.ipynb
2. https://github.com/sympy/sympy/blob/master/examples/advanced/autowrap_ufuncify.py
3. https://github.com/sympy/sympy/blob/master/examples/advanced/autowrap_integrators.py

I couldn't find more examples. Moreover, this does not include examples explicitly using the classes and methods of codegen.py. Sure, autowrap modules use it, however, in the first place, the documentation [here](http://docs.sympy.org/latest/modules/utilities/codegen.html) needs to be expanded.
 Should I be including examples that have an explicit call to make_routine(), or create objects of CCodeGen or OctaveCodeGen class? I ask this because some good examples are already included in the docstring after http://docs.sympy.org/latest/modules/utilities/codegen.html#sympy.utilities.codegen.codegen.
 Should this be shifted to the beginning (just as the examples in the documentation of the matrices module are placed in the beginning and the rest includes description of the various classes and methods from the docstrings.)?
I also wanted to ask if I need to come up with an example using codegen and cse together or with more examples on cse.

**Comment by tokencolour** [comment]
Also,
When I try to execute the file https://github.com/sympy/sympy/blob/master/examples/advanced/autowrap_ufuncify.py, I get the following error:
File "autowrap_ufuncify.py", line 31, in <module>
from sympy import symbols, legendre, Plot, pprint
ImportError: cannot import name Plot
I have matplotlib installed and can't seem to figure out what the matter is.

**Comment by moorepants** [comment]
This page: http://docs.sympy.org/latest/modules/utilities/codegen.html, in particular could use some help. Everything on the page is autogenerated from the doc strings, but it doesn't really provide a use with a good starting point. I think a page that explains in prose what the code generation is all about, what all the options are, and how to use them would be nice. Maybe this belongs in the SymPy tutorial. Or it can be simply a page in the docs. It should talk about lambdify, all the CodeGen classes, codegen, autowrap, ufuncify, the code printers. Check out this page: https://github.com/sympy/sympy/wiki/Code-Generation-Notes. It has a nice summary of all these things that should be in the docs.

**Comment by asmeurer** [comment]
Not everything on that notes wiki page should go in the docs (in particular, the stuff on things outside of SymPy does not need to go in the docs).

**Comment by moorepants** [comment]
Agreed. I was just hoping we could take the nice overview you wrote for all the code gen related stuff in SymPy as an opener to a nice doc page on the topic. It can be followed by examples of how to use all of them, maybe in tutorial style or something.

**Comment by tokencolour** [comment]
I have prepared a .rst file that includes Codegen,  codeprinters, ufuncify and lambdify in a similar fashion as described by the wiki note by @asmeurer . @moorepants , thank you for providing me the link. It is a nice summary indeed!
There's a problem I face while trying autowrap, though (and therefore I am not still able to include it in the file). I tried the first example given here: http://docs.sympy.org/latest/modules/utilities/autowrap.html.
```
>>> from sympy.utilities.autowrap import autowrap
>>> from sympy import symbols, IndexedBase, Idx, Eq
>>> A, x, y=map(IndexedBase, ['A', 'x', 'y'])
>>> m, n=symbols('m n', integer=True)
>>> i=Idx('i',m)
>>> j=Idx('j',n)
>>> instruction=Eq(y[i], A[i,j]*x[j])
>>> matvec=autowrap(instruction)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "sympy/core/cache.py", line 93, in wrapper
    retval = cfunc(*args, **kwargs)
  File "sympy/core/compatibility.py", line 880, in wrapper
    result = user_function(*args, **kwds)
  File "sympy/utilities/autowrap.py", line 525, in autowrap
    return code_wrapper.wrap_code(routine, helpers=helps)
  File "sympy/utilities/autowrap.py", line 144, in wrap_code
    self._process_files(routine)
  File "sympy/utilities/autowrap.py", line 167, in _process_files
    " ".join(command), e.output.decode()))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 4260: ordinal not in range(128)
```
Probably, it is trying to decode a unicode string with the ascii codec and is failing, or there might be a problem with how I am implementing the example. Please help me find out what's wrong.

**Comment by asmeurer** [comment]
It looks like a bug. I'm not able to reproduce it, though. Are you using Python 2 or Python 3?

**Comment by tokencolour** [comment]
Python 2.7.6

**Comment by asmeurer** [comment]
I think your error is masking the real error, since that line is an exception handling block. What happens if you run the code in Python 3. Python 3 will show you both errors (and it also handles decoding of strings better).

**Comment by tokencolour** [comment]
When I executed the above example on Python 3, I got
`ld: cannot find crti.o: No such file or directory`
I googled it and found that this might mean a wrong kind of installation of the fortran compiler. I reinstalled it and the code ran fine on both Python 3 and 2. Thank you!

**Comment by tokencolour** [comment]
I am ready with the rst file. Where should I include it? Should the codegen doc be extended or should it be a seperate doc or should it reside in the tutorials? 
Also,
I wanted to include an example using helper function in `autowrap`. I can't figure out how.
I tried this.
```
>>> from sympy.utilities.autowrap import autowrap 
>>> from sympy import Eq, symbols >>> x, y, z=symbols("x, y, z") 
>>> expr=(x-y+z)**(13)
>>> binary_func=autowrap(expr, language='C', backend='Cython', 
... helpers=('helper',x-y+z, (x,z,y))
 ... ) 
Traceback (most recent call last): 
File "<stdin>", line 2, in <module> 
File "/home/thd/sympy/sympy/core/cache.py", line 93, in wrapper
retval = cfunc(*args, **kwargs) 
File "/usr/lib/python3.4/functools.py", line 472, in wrapper 
result = user_function(*args, **kwds) 
File "/home/thd/sympy/sympy/utilities/autowrap.py", line 522, in autowrap 
for name, expr, args in helpers: 
ValueError: too many values to unpack (expected 3)
```
The args in helpers are used to call make_routine(), so the argument sequence should be tuple or a list, shouldn't it be?
Please help me with this.

**Comment by moorepants** [comment]
> I am ready with the rst file. Where should I include it? Should the codegen doc be extended or should it be a seperate doc or should it reside in the tutorials? 

Just include it wherever you think it belongs and submit a pull request. If we think the content belongs in a different spot we can move it during the review.

**Comment by moorepants** [comment]
As far as the "helpers" arg goes, I don't see any unit tests that exercise that kwarg, so it very well may be broken. Have you found an example of it's use anywhere?

**Comment by tokencolour** [comment]
No, I haven't found an example for helpers kwarg.

**Comment by tokencolour** [comment]
Should I not include it?

**Comment by moorepants** [comment]
Please open an issue about the helpers kwarg being broken and that there are no unit tests for that. We should probably remove the helpers kwarg if that is the case, or fix it.

No need to include the helpers example until that issue is remedied.
