### ISSUE TITLE
subs needs a better error message when trying to sub in Vectors

### ISSUE THREAD

**Issue by moorepants** [sympy/sympy#8892]
See issue  #8886. User tried to substitute a `sympy.physics.vector.Vector` for a scalar symbol in an expression. The error message isn't that informative. It should tell you that it isn't allowed.

**Comment by darshanime** [comment]
Is it fine to use `try` `except` ?
Something like :

```python
try:
    def eval_expr(...)
    ....

except AttributeError as e:
    e.message=e.message+"Substituting a Vector for a scalar is not allowed"
    print e.message
    raise
```

**Comment by moorepants** [comment]
Please post a pull request with any code that you'd like to suggest. We can discuss it there.

**Comment by Soumya-13106** [comment]
This issue has been addressed, I believe. Please close it.

**Comment by moorepants** [comment]
Seems like two PRs are open to address this:
- https://github.com/sympy/sympy/pull/8899 
- https://github.com/sympy/sympy/pull/8900

Where has this been addressed otherwise?
