### ISSUE TITLE
solve((1e-32)*x) gives an error

### ISSUE THREAD

**Issue by mw8** [sympy/sympy#8894]
The same is true for any power of 10 less than -32, as reported by sympy gamma.

**Comment by abhirathb** [comment]
can you please tell how to exactly reproduce the error?

**Comment by pelegm** [comment]
It works here:
```python
>>> x = Symbol('x', real=True)
>>> solve((1e-32)*x)
[0.0]
```

**Comment by abhirathb** [comment]
exactly!

**Comment by mw8** [comment]
My mistake. I assumed sympy gamma had the latest installation of sympy. Turns out it's using a version from April of last year:

http://gamma.sympy.org/input/?i=solve%281e-32*x%29

**Comment by mw8** [comment]
It is strange though that sympy.org is not running the latest version of its own software.

**Comment by moorepants** [comment]
It actually isn't that strange. It takes time to maintain downstream (of sympy) applications and each time we make a new releases it could possibly break things in gamma. So gamma is pinned to a version that works and when the developers have time they upgrade.

You are welcome to download the source from: https://github.com/sympy/sympy_gamma/ and update the sympy submodule to a newer release and see if gamma runs. If it does you can submit a pull request to gamma to get things updated.
