### ISSUE TITLE
Plot ellipse in sympy 0.7.6

### ISSUE THREAD

**Issue by rfeynman** [sympy/sympy#8915]
I tried to plot ellipse in sympy:
Here is what I did:

from sympy.plotting.pygletplot import PygletPlot as Plot

el1=Ellipse(Point(0,0),3,2)
p=Plot(el1)
p[0]=el1
    
But I got error

Traceback (most recent call last):
  File "C:\Users\Erdong\workspace\Gungeo\src\gungeo.py", line 92, in <module>
    p=Plot(el1)
  File "C:\Python27\lib\site-packages\sympy\plotting\pygletplot\__init__.py", line 139, in PygletPlot
    import plot
  File "C:\Python27\lib\site-packages\sympy\plotting\pygletplot\plot.py", line 16, in <module>
    from plot_axes import PlotAxes
  File "C:\Python27\lib\site-packages\sympy\plotting\pygletplot\plot_axes.py", line 7, in <module>
    from util import strided_range, billboard_matrix
  File "C:\Python27\lib\site-packages\sympy\plotting\pygletplot\util.py", line 8, in <module>
    def get_model_matrix(array_type=c_float, glGetMethod=glGetFloatv):
NameError: name 'c_float' is not defined

**Comment by smichr** [comment]
in pygletplot/util.py and plot_rotation.py this import is missing, I believe: `from ctypes import c_float`

**Comment by AadityaNair** [comment]
I had the same problem. I think in the latest version of pyglet (**1.2alpha1**) `c_float` is defined in `pyglet.gl.gl` not in `pyglet.gl`.
This causes all the plotting related tests to fail.

**Comment by rfeynman** [comment]
@smichr  The problem still same
{
Traceback (most recent call last):
  File "C:\Users\Erdong\workspace\Gungeo\src\gungeo.py", line 110, in <module>
    p=Plot(el1)
  File "C:\Python27\lib\site-packages\sympy\plotting\pygletplot\__init__.py", line 139, in PygletPlot
    import plot
  File "C:\Python27\lib\site-packages\sympy\plotting\pygletplot\plot.py", line 16, in <module>
    from plot_axes import PlotAxes
  File "C:\Python27\lib\site-packages\sympy\plotting\pygletplot\plot_axes.py", line 7, in <module>
    from util import strided_range, billboard_matrix
  File "C:\Python27\lib\site-packages\sympy\plotting\pygletplot\util.py", line 8, in <module>
    def get_model_matrix(array_type=c_float, glGetMethod=glGetFloatv):
NameError: name 'c_float' is not defined
}

**Comment by rfeynman** [comment]
@AadityaNair 
What is your solution?

**Comment by AadityaNair** [comment]
I tried a `try - except` block like this:
```python
try:
    from pyglet.gl.gl import c_float
except ImportError:
    pass
```
Seems to clear all the tests.

**Comment by AadityaNair** [comment]
I have generated a PR #8921.
What do you think @smichr ?

**Comment by AadityaNair** [comment]
Also we probably need to update Travis Tests catch such problems.

**Comment by rfeynman** [comment]
Any update right now?

**Comment by AadityaNair** [comment]
Well my PR is incorrect. The last time I just checked for `c_float`. Probably why I missed it.
Even when I apply the changes I suggested it gives the following errors:
```python
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-3-532d9203afe4> in <module>()
----> 1 p=Plot(el1)

/home/Prometheus/projects/sympy/sympy/plotting/pygletplot/__init__.py in PygletPlot(*args, **kwargs)
    138 
    139         from .plot import PygletPlot
--> 140         return PygletPlot(*args, **kwargs)
    141 
    142 except Exception as e:

/home/Prometheus/projects/sympy/sympy/plotting/pygletplot/plot.py in __init__(self, *fargs, **win_args)
    240         self._pobjects.append(self.axes)
    241 
--> 242         self[0] = fargs
    243         if win_args.get('visible', True):
    244             self.show()

/home/Prometheus/projects/sympy/sympy/plotting/pygletplot/plot.py in __setitem__(self, i, args)
    317                 return  # no arguments given
    318             kwargs = dict(bounds_callback=self.adjust_all_bounds)
--> 319             f = PlotMode(*args, **kwargs)
    320 
    321         if f:

/home/Prometheus/projects/sympy/sympy/plotting/pygletplot/plot_mode.py in __new__(cls, *args, **kwargs)
     71 
     72         # Interpret the arguments
---> 73         d_vars, intervals = PlotMode._interpret_args(newargs)
     74         i_vars = PlotMode._find_i_vars(d_vars, intervals)
     75         i, d = max([len(i_vars), len(intervals)]), len(d_vars)

/home/Prometheus/projects/sympy/sympy/plotting/pygletplot/plot_mode.py in _interpret_args(args)
    351         functions, intervals = [], []
    352         if isinstance(args[0], GeometryEntity):
--> 353             for coords in list(args[0].arbitrary_point()):
    354                 functions.append(coords)
    355             intervals.append(PlotInterval.try_parse(args[0].plot_interval()))

TypeError: 'Point' object is not iterable

``` 
Maybe @smichr can throw some light on it.

**Comment by AadityaNair** [comment]
I think I get the error. `args[0]` is the same as `el1`. `el1.arbitrary_piont()` just returns `Point(3*cos(t), 2*sin(t))`. which is just the parametric coordinates for the ellipse itself. No _'arbitrary point'_ is returned.
