### ISSUE TITLE
Integration of Piecewise functions : wrong result

### ISSUE THREAD

**Issue by nbedou** [sympy/sympy#8919]
Sympy yields a wrong result for the integral of the product of two Piecewise functions. The expected result is 1/3 c₁⋅c₃ + 2/3 c₁⋅c₄ + c₂⋅c₄.

```
In [1]: from sympy import *

In [2]: init_printing()

In [3]: var('x c_1 c_2 c_3 c_4')
Out[3]: (x, c₁, c₂, c₃, c₄)

In [4]: f1 = Piecewise( (c_1, x<1), (c_2, True))

In [5]: f2 = Piecewise( (c_3, x<S(1)/3), (c_4, True))

In [6]: f1,f2
Out[6]: 
⎛⎧c₁  for x < 1  ⎧c₃  for x < 1/3⎞
⎜⎨             , ⎨               ⎟
⎝⎩c₂  otherwise  ⎩c₄   otherwise ⎠

In [7]: integrate(f1*f2, (x, 0, 2))
Out[7]: c₁⋅c₄ + c₂⋅c₄
```

Version : sympy 0.7.6, Python 3.4.0

**Comment by TheLartians** [comment]
Some other functions that fail:

    from sympy import *

    a,b,c,x,z = symbols("a,b,c,x,z",real = True)
    y = Symbol("y",real=True,positive=True)
    I = Integral(Piecewise((0,(x>=y)|(x<0)|(b>c)),(a,True)),(x,0,z))
    Eq(I,I.doit())

    >>> Integral(Piecewise((1,(x<1)|(z<x)), (0,True)) ,(x,0,2)).doit()
    -Max(0, Min(2, Max(0, z))) + 3

    >>> Integral(Piecewise((1,(x<1)|(x>z)), (0,True)) ,(x,0,2)).doit()
    -Max(0, Min(2, Max(1, z))) + 3

**Comment by TheLartians** [comment]
Some other examples that give incorrect results:
    
    In [1]: from sympy import *
    In [2]: init_printing()
    In [3]: a,b,c,x,z = symbols("a,b,c,x,z",real = True); y = Symbol("y",real=True,positive=True)
    In [4]: I = Integral(Piecewise((0,(x>=y)|(x<0)|(b>c)),(a,True)),(x,0,z))
    In [5]: Integral(Piecewise((0,(x>=y)|(x<0)|(b>c)),(a,True)),(x,0,z)).doit()
    Out[5]: 
    ⎧       0         for z ≥ -∞ ∧ z ≤ 0
    ⎪                                   
    ⎪⎧ 0   for b > c                    
    ⎪⎨                for z ≥ y ∧ z ≤ ∞ 
    ⎨⎩a⋅y  otherwise                    
    ⎪                                   
    ⎪       0         for z ≥ 0 ∧ z ≤ y 
    ⎪                                   
    ⎩      a⋅z            otherwise     
    In [6]: Integral(Piecewise((1,(x<1)|(z<x)), (0,True)) ,(x,0,2)).doit()
    Out[6]: -Max(0, Min(2, Max(0, z))) + 3

(see http://stackoverflow.com/questions/30155166/integral-of-piecewise-function-gives-incorrect-result/30179185?noredirect=1#comment48585402_30179185 for details)

In fact, most Piecewise functions I tried so far either don't evaluate, result in an error or give a wrong result. Maybe integrating PieceWise should raise NotImplementedError until fixed?

**Comment by cbm755** [comment]
Even simple explicit Piecewise are wrong:
````
In [72]: f1 = Piecewise( (0, x<1), (2, True))
In [73]: f2 = Piecewise( (3, x<2), (0, True))
In [74]: g = f1*f2

In [75]: g
Out[75]: 
⎛⎧0  for x < 1⎞ ⎛⎧3  for x < 2⎞
⎜⎨            ⎟⋅⎜⎨            ⎟
⎝⎩2  otherwise⎠ ⎝⎩0  otherwise⎠

In [76]: g.subs(x, 0)   # yes
Out[76]: 0

In [77]: g.subs(x, 3)   # yes
Out[77]: 0

In [78]: g.subs(x, S(3)/2)   # yes
Out[78]: 6

In [79]: integrate(f1*f2, (x,0,3))   # no!
Out[79]: -6
````
The solution should be 6.  Staying within a constant region works:
````
In [94]: integrate(g, (x,1,S(199)/100))
Out[94]: 
297
───
 50
````
(and limits to the correct value in this case).

Plotting `g` also seems to fail.

**Comment by snotskie** [comment]
Also getting bad results when attempting to convolute p.d.f.s, akin to the continuous example given [here](http://www.dartmouth.edu/~chance/teaching_aids/books_articles/probability_book/Chapter7.pdf)
