### ISSUE TITLE
str(Eq()) should not use ==

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#8920]
See for instance https://github.com/sympy/sympy/pull/8771/files#r23880014. I imagine this is a pretty common mistake, especially with Piecewise. str(Eq) should maybe print with a single =, so that at least it will give a syntax error. Or maybe `str(Eq(x, y))` should just give `'Eq(x, y)'`.

**Comment by smichr** [comment]
> should just give 'Eq(x, y)'

In spirit of being able to copy str and sympify it, yes. Also I ran into this with `x != y` , too. It would be nice to get that wrapped with `Ne(x, y)`.

**Comment by luviiit** [comment]
Hi, I am working on this issue. Please have a look at https://github.com/luviiit/sympy/commit/bc038ab4d961816f79d2f7d588213ec5d0c19ddd

**Comment by asmeurer** [comment]
@luviiit go ahead and start a pull request with that. The change looks OK, but the tests will also need to be fixed.

**Comment by luviiit** [comment]
Opened PR -> https://github.com/sympy/sympy/pull/8931
