### ISSUE TITLE
wrong result for integrate(s*cos(1.0*s), s)

### ISSUE THREAD

**Issue by spescha** [sympy/sympy#8932]
the code:
```python
In [4]: integrate(s*cos(s), s)
Out[4]: s*sin(s) + cos(s)
```
delivers the correct result. for floating point numbers in the argument of the cosine, the integration delivers wrong results:
```python
In [6]: integrate(s*cos(1.0*s), s)
Out[6]: 0
```

**Comment by kaushik94** [comment]
Works fine for me
```
>>> integrate(s*cos(1.0*s), s)
1.0*s*sin(1.0*s) + 1.0*cos(1.0*s)
```
which version of sympy are you using ?

**Comment by smichr** [comment]
This was just fixed today.

**Comment by smichr** [comment]
Thanks for reporting it, however.

**Comment by spescha** [comment]
I'm really impressed about that quick reply.
Before, I used sympy version 0.7.6.
I installed the newest version from GitHub (0.7.6-git) and now it works fine.

Thanks a lot
