### ISSUE TITLE
x.is_Integer returns False

### ISSUE THREAD

**Issue by aka001** [sympy/sympy#8938]
>x=symbols('x')
>x.is_Integer
False

It should be None.

However, x.is_integer returns the expected output.
I am not aware of the output expected from is_Integer. Please correct me if I am wrong.

**Comment by aktech** [comment]
* `is_Integer` is used for checking if it is an instance of Integer Class.

(i.e. Capital attributes are used for checking instances (objects) of the exact Capital class.)
* `is_integer` is used to check the property. 

(i.e. if that's an integer or not.)

**Comment by aka001** [comment]
@aktech Thank you for clarifying it.
