### ISSUE TITLE
diophantine misses trivial solution

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#8943]
```py
In [6]: diophantine((3*(x**2 + y**2 + z**2) - 14*(x*y + y*z + z*x)))
Out[6]: set([])
```

See http://math.stackexchange.com/questions/1133888/hard-number-theory-problem. The only solution is `(0, 0, 0)`. Nothing in the docstring indicates that it should skip trivial solutions.

**Comment by mihir-w** [comment]
I am thinking of simply adding a check which adds trivial solution if solution set is null and if the equation lacks constants.
Is this approach okay ? Or should I try to ensure that trivial solution is returned by every type of diophantine equation

**Comment by kevinventullo** [comment]
My guess is that because it's homogeneous, the trivial solution is left out.

Finding integer solutions to homogeneous equations is often phrased as finding rational points on a hypersurface in projective space. In this context, you don't include the point *0*.

**Comment by asmeurer** [comment]
I would first investigate the algorithms and the code, to see why exactly this is not included. If @kevinventullo is right then we should just add a special case where we include 0 if it's needed.
