### ISSUE TITLE
integrate(sin(x)**2/x, (x, 0, 1)) returns nan

### ISSUE THREAD

**Issue by certik** [sympy/sympy#8944]
But the integral is finite:
```
In [4]: integrate(sin(x)**2/x, (x, 0, 1))
Out[4]: nan

In [5]: Integral(sin(x)**2/x, (x, 0, 1)).n()
Out[5]: 0.423691008343307
```
and not only that, it is actually equal to:
```
In [9]: -Ci(2)/2+log(2)/2+EulerGamma/2
Out[9]: 
  Ci(2)   EulerGamma   log(2)
- ───── + ────────── + ──────
    2         2          2   

In [10]: _.n()
Out[10]: 0.423691008343307
```

**Comment by asmeurer** [comment]
It looks like a bug in the meijerg algorithm:

```
In [2]: integrate(sin(x)**2/x, (x, 0, 1), meijerg=False)
Out[2]:
1
⌠
⎮    2
⎮ sin (x)
⎮ ─────── dx
⎮    x
⌡
0

In [3]: integrate(sin(x)**2/x, (x, 0, 1), meijerg=True)
Out[3]: nan
```

It looks like it can compute the definite integral just fine though (I'm not sure why it doesn't do this with `meijerg=False`)

```
In [4]: integrate(sin(x)**2/x, x)
Out[4]:
log(x)   Ci(2⋅x)
────── - ───────
  2         2

In [5]: limit(integrate(sin(x)**2/x, x), x, 0)
Out[5]:
  log(2)   EulerGamma
- ────── - ──────────
    2          2

In [6]: limit(integrate(sin(x)**2/x, x), x, 1)
Out[6]:
-Ci(2)
───────
   2
```

**Comment by asmeurer** [comment]
Oh I guess it's because the meijerg algorithm is what computes the indefinite integral.

**Comment by darkcoderrises** [comment]
https://github.com/sympy/sympy/issues/8945
Like in this, i suggested a way to find these integrals.
in this case the output comes out to be 
  cos(2*x)    1 
- -------- + ---
    2*x      2*x
and when i integrate this this gives nan at (0,1). 
I think that is because at 0 is might that that 1/2*x is inifinite. So, this should be rectified irrespective of this issue.

**Comment by certik** [comment]
As of 8d7b522e58aae883b4592e4fae3babf82d1e4db2, this is now fixed. But it's terribly slow. Fortunately, there now exists a much quicker (and robust?) way using holonomic functions:
```
In [1]: from sympy.holonomic import from_sympy

In [2]: time integrate(sin(x)**2/x, (x, 0, 1))
CPU times: user 8.92 s, sys: 76 ms, total: 9 s
Wall time: 8.97 s
Out[2]: 
  Ci(2)   γ   log(2)
- ───── + ─ + ──────
    2     2     2   

In [3]: time from_sympy(sin(x)**2/x).integrate((x, 0, x)).to_sympy().subs(x, 1)
CPU times: user 1.15 s, sys: 48 ms, total: 1.2 s
Wall time: 1.13 s
Out[3]: 
  Ci(2)   γ   log(2)
- ───── + ─ + ──────
    2     2     2   
```
Note that most time is spent converting to and from holonomic functions. The actual integration is immediate.
```
In [1]: from sympy.holonomic import from_sympy

In [2]: time a = from_sympy(sin(x)**2/x)
CPU times: user 896 ms, sys: 56 ms, total: 952 ms
Wall time: 911 ms

In [3]: time b = a.integrate((x, 0, x))
CPU times: user 4 ms, sys: 0 ns, total: 4 ms
Wall time: 1.3 ms

In [4]: time c = b.to_sympy()
CPU times: user 592 ms, sys: 32 ms, total: 624 ms
Wall time: 595 ms

In [5]: time c.subs(x, 1)
CPU times: user 4 ms, sys: 0 ns, total: 4 ms
Wall time: 4.93 ms
Out[5]: 
  Ci(2)   γ   log(2)
- ───── + ─ + ──────
    2     2     2   
```

**Comment by certik** [comment]
Thanks to @shubhamtibra for implementing the holonomic functions module, which made this possible. Great job, it's already very useful and better in the above case than what we have in sympy's integrate.

**Comment by asmeurer** [comment]
I don't like how you have to substitute endpoints to get a definite integral. Based on that, I would say that miejerint_definite should still remain the default for definite integrals (plus it can give convergence conditions). But for indefinite integrals, that doesn't matter, so if this is good in general, it may be worth adding it before meijerint_indefinite (but after risch, I'd say, since risch is very fast, and fails fast for expressions it can't handle).

**Comment by asmeurer** [comment]
This is interesting. I wonder what is going on

```
In [2]: time integrate(sin(x)**2/x, (x, 0, 1), meijerg=True)
CPU times: user 1.69 s, sys: 12.1 ms, total: 1.7 s
Wall time: 1.72 s
Out[2]:
  Ci(2)   γ   log(2)
- ───── + ─ + ──────
    2     2     2

In [3]: time integrate(sin(x)**2/x, (x, 0, 1))
CPU times: user 8.53 s, sys: 14.6 ms, total: 8.54 s
Wall time: 8.55 s
Out[3]:
  Ci(2)   γ   log(2)
- ───── + ─ + ──────
    2     2     2
```

**Comment by certik** [comment]
Regarding the endpoints, there is a technical bug (#11316) and then a fundamental issue (#11319).
