### ISSUE TITLE
integrate(sin(x)**3/x, (x, 0, 1)) can't do it

### ISSUE THREAD

**Issue by certik** [sympy/sympy#8945]
But the answer is given below in [15]:

```
In [13]: integrate(sin(x)**3/x, (x, 0, 1))
Out[13]: 
1           
⌠           
⎮    3      
⎮ sin (x)   
⎮ ─────── dx
⎮    x      
⌡           
0           

In [14]: Integral(sin(x)**3/x, (x, 0, 1)).n()
Out[14]: 0.247399170775520

In [15]: Si(1)*3/4-Si(3)/4
Out[15]: 
  Si(3)   3⋅Si(1)
- ───── + ───────
    4        4   

In [16]: _.n()
Out[16]: 0.247399170775520
```

Once this is fixed, try higher powers of `sin(x)^n/x` for integer `n`.

**Comment by asmeurer** [comment]
This is the definite integral: http://www.wolframalpha.com/input/?i=integrate(sin(x)**3%2Fx%2C+x)&dataset=. I would expect the meijerg algorithm to be able to do this.

**Comment by asmeurer** [comment]
@raoulb

**Comment by darkcoderrises** [comment]
Can i work on this?

**Comment by certik** [comment]
Of course!

**Comment by darkcoderrises** [comment]
Is was thinking that we can implement something like, for all undefined defined integrals  we have we manually calculate the area i.e.
for (x = lowerlimit; x<upperlimit;x=x+0.00001//some low value)
{
    area = area + f(x)*0.00001;
}
(If such thing is not implemented yet.)

**Comment by certik** [comment]
Yes, that's implemented by `.n()` (in a much more robust way), see the cell [14] in the issue description for an example of usage.

**Comment by darkcoderrises** [comment]
Oh okay,thanks

**Comment by darkcoderrises** [comment]
In [43]: f = sin(x)**3/x

In [44]: g =mellin_transform(f, x, s)

In [45]: l=inverse_mellin_transform(g[0], s, x, (0, 1))

In [46]: integrate(l,(x,0,1))
Out[46]: 
  Si(3)   3*Si(1)
- ----- + -------
    4        4   

In [47]: _.n()
Out[47]: 0.247399170775520

**Comment by darkcoderrises** [comment]
for the functions which do not have a mellin transform (like e^(x**2)), we can see that
type(g) = sympy.integrals.transforms.MellinTransform
else
type(g) = tuple

**Comment by certik** [comment]
Nice. Essentially you are rewriting the `sin^3(x)` to an equivalent expression.

**Comment by darkcoderrises** [comment]
can someone help me in finding where to implement it.

**Comment by certik** [comment]
I think the integration subroutine needs to be fixed to handle this integral. I don't think it should call the Mellin transform.

**Comment by darkcoderrises** [comment]
Okay, Where should i start looking then?

**Comment by asmeurer** [comment]
You're welcome to try extending the meijerg algorithm, but a simpler way to fix this would be to add it to manualintegrate.
