### ISSUE TITLE
Test failures in PyPy on Travis

### ISSUE THREAD

**Issue by certik** [sympy/sympy#8949]
The PR #8386 triggered unrelated failures on Travis:

https://travis-ci.org/sympy/sympy/jobs/49611610
https://travis-ci.org/sympy/sympy/jobs/49611613

Looking at one of the failures:
```
File "/home/travis/virtualenv/pypy-2.5.0/site-packages/sympy-0.7.6_git-py2.7.egg/sympy/ntheory/residue_ntheory.py", line 786, in sympy.ntheory.residue_ntheory.legendre_symbol
Failed example:
    list(set([i**2 % 7 for i in range(7)]))
Expected:
    [0, 1, 2, 4]
Got:
    [0, 1, 4, 2]
```
This looks like a bug in sympy, i.e. the order of `list(set([...]))` is undefined (http://stackoverflow.com/questions/9792664/python-set-changes-element-order).

**Comment by smichr** [comment]
At the end of [this thread](http://bugs.python.org/issue3332) Tim Peters wrote:
```
It's "a feature" that doctest demands exact textual equality, and that the only way to override this is with one of the `#doctest:` flags.  "What you see is what you get - exactly" is one of doctest's fundamental design goals.

If you would like to open a different report, suggesting (e.g.) a new "#doctest: object_equality" flag, go ahead.  But I don't expect that would get a warm reception:  there are many ways to write doctests with sets and dicts that already work fine.  That you may have to add additional functions to make them pass in all cases isn't a bug:  it's being explicit about that the raw unprocessed output is _not_ reliable.

If you don't want that level of pickiness, fine, use something else :-)
```

Although I tried to work around some tests by adding decoration to the doctest to make it work (e.g. a sorted_str_dict to convert a dict to an ordered string) but this is frowned on because they obfuscate what you are trying to show. In such cases I would recommend using the "# doctest: +SKIP" directive -- the tests themselves should test the functionality.

**Comment by certik** [comment]
Interesting. It is consistent to just require exact string output, also it'd be hard for doctests to try all permutations until one agrees with the specified output. That being said, the comment right above Tim Peters is right --- this "feature" greatly diminishes the usefulness of doctests, because you can't show how functions that return dicts/sets should be used and what they return, because the exact string representation happens to be undefined. So it's a real problem.

**Comment by asmeurer** [comment]
You can't rely on `list(set)` giving a consistent output. Just replace `list` with `sorted` in the doctest.

**Comment by smichr** [comment]
> you can't show how functions that return dicts/sets should be used and what they return

Rather, you can show how the output should be used, you just can't use the **doctest** to test *non-trivial* return values (i.e. set/dict with more than one element). You can skip a doctest, however, with output shown and (as always) you can test the output in the test suite.

We can work around the current failures of the above variety. I have no idea why the following have failures, however:

https://travis-ci.org/smichr/sympy/jobs/49777907
https://travis-ci.org/smichr/sympy/jobs/49777910
