### ISSUE TITLE
SymPy has invalid version numbers for PEP 440

### ISSUE THREAD

**Issue by moorepants** [sympy/sympy#8953]
In particular the version number for the dev versions, e.g. `0.7.6-git` is invalid. The latest version of setuptools is now treating `0.7.6-git` to be older than `0.7.6`. This is bad. For example it is breaking upstream tests in PyDy for SymPy master: https://github.com/pydy/pydy/pull/113.

**Comment by moorepants** [comment]
It seems like Travis has just upgraded from pip 1.5 series to pip 6 series. See all of the backwards incompatibilities in the release notes: https://pip.pypa.io/en/latest/news.html.

**Comment by moorepants** [comment]
If we want to be compliant with PEP 440 with our development version numbers then we need things to go like this:

- 0.7.6
- 0.7.7.dev1
- 0.7.7
- 0.8.0.dev1
- 0.8.0

whereas our current scheme is:

- 0.7.6
- 0.7.6-git
- 0.7.7
- 0.7.7-git
- 0.8.0

See this link: https://www.python.org/dev/peps/pep-0440/#id46

This is sort of annoying since you have to predict what the next version number is as soon as you make the previous final release. I think I like our way better, but this is now going to break with all setuptools/pip tools.

**Comment by moorepants** [comment]
The Travis people suggest:

`pip install pip<6 setuptools<8` to avoid PEP 440 issues.

https://github.com/travis-ci/travis-ci/issues/3060#issuecomment-73227013

**Comment by certik** [comment]
Unfortunately, I think we need to be PEP 440 compliant, as we need to be able to use pip.

So #8955 is the way to go.

**Comment by toolforger** [comment]
We can still do

* 0.7.7
* 0.7.8-git
* 0.8.0 (whoops, didn't want to go to 0.7.8 after all)

It might make people wonder, but most won't ever look at old -git versions anyway so I doubt it's going to hurt.

**Comment by AadityaNair** [comment]
I am curious. Where do you change these kind of stuff. I checked the tags in the repository but they go as `0.7.5` and `0.7.5-rc1`, etc.

**Comment by moorepants** [comment]
This has to do with the version we set in the setup.py file which gets used on PyPi and for conda, etc.

**Comment by moorepants** [comment]
I have a PR here: https://github.com/sympy/sympy/pull/8955 to address this. You can see what I've changed.
