### ISSUE TITLE
O(n) + n**2 evaluates incorrectly.

### ISSUE THREAD

**Issue by mihir-w** [sympy/sympy#8978]
Using the big-O notation,
```
>>> O(n) + n**2
O(n)
>>> O(n**2) + n
O(n**2) + n
```

I think the first answer should be `O(n) + n**2`.

**Comment by sahilshekhawat** [comment]
I just checked with the latest master and this seems to be working fine.
```
>>> O(n) + n**2
n**2 + O(n)
>>> O(n**2) + n
n + O(n**2)
```

**Comment by pelegm** [comment]
I think that by default `O` is about 0. If you wish it to be around `oo`, you should do it explicitly:
```python
>>> O(n, (n, oo)) + n**2
n**2 + O(n, (n, oo))
>>> O(n**2, (n, oo)) + n
O(n**2, (n, oo))
```

**Comment by sahilshekhawat** [comment]
@pelegm I am getting inconsistence results while calculating this. I tried checking out various commit and even removing cache. Sometimes this works and sometimes it doesn't. I guess there is a bug in assumptions.

**Comment by pelegm** [comment]
@sahilshekhawat I have no idea what you're talking about. Perhaps you'd better post some inputs and outputs.

**Comment by asmeurer** [comment]
@sahilshekhawat please open a new issue with a log of what you are seeing. 

@mihir-w as noted, O() is the order at 0 by default, not infinity like you are used to from computer science. This is because it's used for series expansions.

**Comment by mihir-w** [comment]
Thanks for clearing it up.
