### ISSUE TITLE
[enhancement] (p + 2)**3 > 1 should be True when p is positive

### ISSUE THREAD

**Issue by smichr** [sympy/sympy#8992]
Similar to issues #8632, #8633, #8638 and #8675, when values of variables in a polynomial put one in a domain where the polynomial is monotonic, then inequalities like the one of this issue should be known. For (x+2)**3 there is an inflection at x = -2 and the function is monotonically rising to the right (and falling to the left) so it should be safe to say that it is greater than 1 if x is positive.

Some work is in progress in my `geno` branch if anyone is interested in using that as a starting point.

**Comment by pelegm** [comment]
Are you trying to accomplish it using old or new assumptions?

**Comment by smichr** [comment]
Old. Feel free to take a look.
