### ISSUE TITLE
'sys' NameError when mpmath dependency not met

### ISSUE THREAD

**Issue by lokeshh** [sympy/sympy#9006]
Environment with mpmath not installed returns the following upon running setup.py:

> Please install the mpmath package with a version >= 0.19

> Traceback (most recent call last):
  File "C:\Users\Amit\Desktop\sympy-master\setup.py", line 47, in <module>
    sys.exit(-1)
NameError: name 'sys' is not defined

**Comment by lokeshh** [comment]
It's certainly because the 

> import sys

is written at the wrong place.

I am fixing it.

**Comment by lokeshh** [comment]
Here's my fix: https://github.com/sympy/sympy/pull/9007

**Comment by smichr** [comment]
#9007 was merged
