### ISSUE TITLE
rootof: RootOf.evalf() infinite loop

### ISSUE THREAD

**Issue by cswiercz** [sympy/sympy#9019]
The following code hangs indefinitely:

```
In [1]: r = RootOf(x**2 + 1, 0, radicals=False)
In [2]: r.evalf()   # hangs indefinitely
```

Upon inspection, the issue occurs in `RootOf._eval_evalf()` inside an infinite (a `while True:`) loop. On [Line 598](https://github.com/sympy/sympy/blob/fa42fb33200ccb7d135cbccf29c6e77fb0cf8800/sympy/polys/rootoftools.py#L598) of `rootoftools.py` there is a check to see if the numerical approximation lies inside a continuously refining interval. Here's a snippet.
```python
if self.is_real:
    if (a < root < b):
        break
    elif (ax < root.real < bx and ay < root.imag < by):
        break
```
Below is the output of a pdb session after several iterations of the `while True:` loop at the point of the `elif` above.
```
(Pdb) p ax
mpf('0.0')
(Pdb) p bx
mpf('0.5')
(Pdb) p ay
mpf('-1.0')
(Pdb) p by
mpf('-0.75')
(Pdb) p root
mpc(real='0.0', imag='-1.0')
```
So the real an imaginary parts happen to lie exactly on the boundary of the real and imaginary intervals, respectively, but the check is for inclusion in the interior. I don't understand the reasoning behind this algorithm enough to offer a pull request simply changing the "`<`" to a "`<=`".

**Comment by smichr** [comment]
ping @jksuom

**Comment by jksuom** [comment]
The evaluation begins with `dup_isolate_complex_roots_sqf()` which returns a *closed* complex rectangle containing one root. There is nothing to prevent the root from lying on the boundary or even at a corner. So I cannot see any possibility of avoiding the equality in the comparisons.

**Comment by smichr** [comment]
Thanks, @jksuom. @cswiercz would you like to send a PR making the change?

**Comment by cswiercz** [comment]
@smichr Sure. Again, I wasn't sure if inclusion in the interior was a necessary condition for the algorithm to work but thanks to @jksuom it should be a quick change.
