### ISSUE TITLE
Trigsimp hangs

### ISSUE THREAD

**Issue by proy87** [sympy/sympy#9032]
Trigsimp hangs on `-32*sin(64*x)/sqrt(cos(64*x))`

**Comment by smichr** [comment]
It doesn't hang but the time taken to simplify `sin(n*x)/sqrt(cos(n*x))` increases approximately eponentially with n:

```
n
|  time to simplify (sec)
|   |
2 0.14
4 0.29
8 0.81
16 2.56
32 9.82
64 88.67
```

**Comment by simamura87** [comment]
Got it!
