### ISSUE TITLE
Matrices: Trace ineffective when used with MatAdd

### ISSUE THREAD

**Issue by lokeshh** [sympy/sympy#9035]
`trace(MatAdd(M1, M2, M3...))`, lacks expression evaluation inside to give smart results.

To meantion one such example, let `X` and `Y` be defined as follows:
```python
>>> X = Matrix([[1, 2], [3, 4]])
>>> pprint(X)
⎡1  2⎤
⎢    ⎥
⎣3  4⎦

>>> Y = MatrixSymbol('Y', 2, 2)
```
Now, it is expected for 
```python 
trace(MatAdd(X, Y, -Y))
``` 
to return 

```python
5
``` 

but it gives

```python
5 + Trace(Y) - Trace(Y)
``` 

(Its being dealt with at #9031.)

**Comment by cbm755** [comment]
Did you file this before #9009 went in?  I think its ok now.  (Sorry as you probably filed this b/c I asked you to!)

I'll leave open in case I'm wrong.

**Comment by cbm755** [comment]
I think this is fixed already in master.
