### ISSUE TITLE
Stirling's approximation does not work for integers

### ISSUE THREAD

**Issue by pelegm** [sympy/sympy#9041]
The following is a wrong result:

``` python
>>> n = Symbol('n', integer=True, positive=True)
>>> limit(factorial(n) / ((n/E)**n * sqrt(2*pi*n)), n, oo)
0
```

(should be 1).

If `n` is not assumed to be an integer, the returned limit is indeed 1.

**Comment by leosartaj** [comment]
The following gives the correct result
```
>>> n = Symbol('n', integer=True)
>>> limit(factorial(n) / ((n/E)**n * sqrt(2*pi*n)), n, oo)
1
```
while
```
>>> n = Symbol('n', integer=True, positive=True)
>>> limit(factorial(n) / ((n/E)**n * sqrt(2*pi*n)), n, oo)
0
```
gives the wrong result.

**Comment by sachin-4099** [comment]
Closing in favour of: https://github.com/sympy/sympy/pull/19292
Adding the testcase in: https://github.com/sympy/sympy/pull/19432
