### ISSUE TITLE
pretty printing: `Trace` could be improved (and LaTeX)

### ISSUE THREAD

**Issue by cbm755** [sympy/sympy#9044]
````
In [69]: X = ImmutableMatrix([[1, 2], [3, 4]])

In [70]: pprint(X)
⎡1  2⎤
⎢    ⎥
⎣3  4⎦

In [71]: w = Trace(X) + Trace(2*X)

In [72]: pprint(w)
Trace(Matrix([ + Trace(Matrix([
   [1, 2],          [2, 4],    
  [3, 4]]))        [6, 8]]))   
````

I suppose `pprint(Trace(X))` should be:
````
  ⎛⎡1  2⎤⎞ 
tr⎜⎢    ⎥⎟ 
  ⎝⎣3  4⎦⎠ 
````

**Comment by Sumith1896** [comment]
@cbm755 I am on it. Thanks for reporting.
@asmeurer Shouldn't the value of below `Out[3]:` be 5?
```
In[1]: X = ImmutableMatrix([[1, 2], [3, 4]])
In[2]: w = Trace[X]
In[3]: simplify(w)
Out[3]: 
Trace(Matrix([
   [1, 2],    
  [3, 4]])) 
```

**Comment by cbm755** [comment]
> below Out[3]: be 5?

No, `w.doit()` would be 5.  So would lowercase `trace(w)`.

**Comment by swachhandl** [comment]
@cbm755  I am new to SymPy and I would like to work on this as my first issue. Could you please help me get started? Thanks.

**Comment by cbm755** [comment]
@swachhandl start [here](https://github.com/sympy/sympy/wiki/Development-workflow)

Then run the commands I gave above and try to figure out what code is executed.

**Comment by swachhandl** [comment]
@cbm755 I have defined a function _print_Trace in sympy.printing.pretty.pretty.PrettyPrinter so that this function is used to print the Trace rather than the emptyPrinter.

```
def _print_Trace(self, e):
        mat = e._args[0]
        D = self._print_MatrixBase(mat)
        D = prettyForm(*D.parens('(', ')'))
        D = prettyForm(*D.left('\n'*(D.height()//2) + 'tr'))
        return D
```

I have managed to pretty print the trace:
```
  ⎛⎡1  2⎤⎞
tr⎜⎢    ⎥⎟
  ⎝⎣3  4⎦⎠
```

But the '+' is off position:
```
  ⎛⎡1  2⎤⎞ +   ⎛⎡2  4⎤⎞
tr⎜⎢    ⎥⎟   tr⎜⎢    ⎥⎟
  ⎝⎣3  4⎦⎠     ⎝⎣6  8⎦⎠
```
I guess I need to make changes in the functions PrettyPrinter._print_Add and PrettyPrinter._print_Mul so that the operators show up correctly, am I right? Thanks.

**Comment by Sumith1896** [comment]
Create a PR, we can review and discuss it there.

**Comment by tokencolour** [comment]
Why is the issue still open? I would like to work on it if required.

**Comment by cbm755** [comment]
@tokencolour its still open because it is not fixed.  #9049 has a partial solution

**Comment by tokencolour** [comment]
@cbm755 , Please take a look at this. Do suggest any improvements. Thank you.
