### ISSUE TITLE
`trace(2*A) != 2*Trace(A)` because LHS still has an MatMul

### ISSUE THREAD

**Issue by cbm755** [sympy/sympy#9052]
````
n = Symbol('n', integer=True)
A = MatrixSymbol('A', n, n)
trace(2*A) == 2*Trace(A)    # False
srepr(trace(2*A))   # note 2*Trace(MatMul(A))
````

**Comment by kevinventullo** [comment]
I guess the problem is that `2*A` is represented as a MatMul, and in general you can't simplify the trace of a product of two matrices.

Should we have trace check if its argument is a MatMul, and if the first argument of MatMul is a number, take that number times the trace of the rest?

**Comment by cbm755** [comment]
Currently for , it does correctly pull the 2 out, it just leaves the MatMul behind :)    #9031 has an XFAIL test for this.  I think `_eval_trace` of `matmul.py` needs `.doit()`

(and yes, `trace(MatMul(A, 2, B))` should go to `2*Trace(MatMul(A, B))` of course.  #9031 has improves the test of that.)
