### ISSUE TITLE
Getting arbitrary points of an ellipse

### ISSUE THREAD

**Issue by AadityaNair** [sympy/sympy#9065]
I tried the following code:
```python
>>> el1=Ellipse(Point(0,0),3,2)
>>> el1.arbitrary_point()
Point(3*cos(t), 2*sin(t))
```

Shouldn't `arbitrary_point()` return an *arbitrary point* and not the parametric coordinates 
of the ellipse ?

I am also unable to substitute it for anything:
```python
>>> pt=el1.arbitrary_point()
>>> pt.subs(t, 0)
Point(3*cos(t), 2*sin(t))
```

Is it a bug or am I missing something ?

**Comment by debugger22** [comment]
In the documentation it says:

```
A parameterized point on the ellipse.
```

If you are going by the literal meaning of `arbitrary`, there's also a method called `random_point`. I think together they make sense.

@akshayah3 ping.

**Comment by smichr** [comment]
The docstring examples for Triangle are better in that they give an example of how to do the substitution. Basically, if you pass no variable you get a *real* symbol named `t` and since assumptions go with the symbol definition, if you use a vanilla symbol (no assumptions) the subs fails because *that* `t` is not found.

```python
>>> Ellipse((0,0),1,2).arbitrary_point(x)
Point(cos(x), 2*sin(x))
>>> _.subs(x,pi)
Point(-1, 0)
>>> Ellipse((0,0),1,2).arbitrary_point()
Point(cos(t), 2*sin(t))
>>> _.subs(var('t',real=True),pi)
Point(-1, 0)
```

In retrospect, a better name for `arbitrary_point` might have been `parametric_point`.

**Comment by smichr** [comment]
I think this can be closed but maybe you want to make some suggestion about how the routine might work better or mre intuitively. Note, however, that using a non-real symbol might lead to issues in how well calculations involving the Point would work.

**Comment by smichr** [comment]
:e-mail: Also, so the issues list doesn't get clogged with discussions that don't have a well defined issue, perhaps it might be better to raise such questions on the [mailing list](https://groups.google.com/forum/#!forum/sympy) and once a clear issue emerges, then open it here.

**Comment by smichr** [comment]
Seeing no further discussion, I am closing this.
