### ISSUE TITLE
sympy.limit yields incorrect result

### ISSUE THREAD

**Issue by cstoudt** [sympy/sympy#9075]
Python 2.7.9; SymPy 0.7.6

Consider the function `g=(6**(n+1)+n+1)/(6**n+n)` where x is real and n is an integer

It is easy to show that the limit of g as n->oo is 6

Yet, look at the output of the following code:

```
from sympy import symbols, limit, oo, Pow
n=symbols('n',integer=True)
x=symbols('x',real=True)
g=(Pow(6,n+1)+n+1)/(Pow(6,n)+n)
limit(g,n,oo)
```
out[4]: 1

**Comment by smichr** [comment]
Interestingly, if you make n positive

```
>>> n=symbols('n',integer=True,positive=True)
>>> limit(g,n,oo)
(6**(n + 1) + n + 1)/(6**n + n)
```

**Comment by raoulb** [comment]
> Consider the function `g=(6**(n+1)+n+1)/(6**n+n)` where x is real and
> n is an integer

Some heuristics seem to fail here.
Use the superior Gruntz algorithm:

```
In [9]: g
Out[9]: (6**(n + 1) + n + 1)/(6**n + n)

In [10]: gruntz(g, n, oo)
Out[10]: 6
```

**Comment by cstoudt** [comment]
According to the documentation, limit uses some heuristics to solve the "easy" cases for speed, and uses the Gruntz algorithm for all other cases.  So something is failing in the heuristics.

Interestingly, gruntz also fails for the case that smichr pointed out:

```
>>> from sympy.series import gruntz
>>> n=symbols('n',integer=True,positive=True)
>>> gruntz(g, n, oo)
(6**(n + 1) + n + 1)/(6**n + n)
```

**Comment by zanzibar7** [comment]
Bug traces back to atleast 0.7.2.   Also in a reduced version...
```
In [3]: limit( (6**(n+1)+1)/(6**n+1), n, oo)
Out[3]: 1
```
Looks like the heuristic is equating `n+1` and `n` when n is large.

**Comment by leosartaj** [comment]
On some debugging,
This is due to incorrect result by [inve.as_leading_term()](https://github.com/sympy/sympy/blob/master/sympy/series/limits.py#L149). It returns `1` rather than `6`.
This is because in general
```
>>> (6**(n+1))._eval_leading_term(n)
1 # incorrect
>>>(6*6**n)._eval_leading_term(n)
6 # correct
```
This ultimately boils down  to `_eval_leading_term` method in `Pow`.
I am working on this and will send a pull request shortly.
