### ISSUE TITLE
Replacing some lists with generators.

### ISSUE THREAD

**Issue by mihir-w** [sympy/sympy#9079]
There are various places in the codebase where a list is used only to have it's arguements split and passed to a different function.
Ex:

```
And(*[ Not(a) for a in self.args] )
```

A generator would be better suited here.

```
Add(*( Not(a) for a in self.args ) )
```

Doing a grep, lists hundreds of such cases.

Also in various places, a generator is converted to a list which is then converted to a tuple.
Ex:

```
 tuple([self._print(s) for s in (l[1], l[0], l[2])])
```

Tuples can directly handle generators.

```
 tuple(self._print(s) for s in (l[1], l[0], l[2]))
```

A grep roughly shows 50 such instances.

**Comment by oscarbenjamin** [comment]
Are there any cases where this leads to a significant performance penalty? I think most things in SymPy are so slow that this kind of difference should be negligible unless it really hits the inner-most loop of something.
