### ISSUE TITLE
solve: Returns wrong solution

### ISSUE THREAD

**Issue by Sumith1896** [sympy/sympy#9083]
```
In [9]: solve(Eq(sin(x),2),x)
Out[9]: [π - asin(2), asin(2)]
```
but as 2 is not in range of sin(x), `solve` should've returned null set.
`solveset` is capable of handling this and returns `null`

**Comment by smichr** [comment]
You were probably using `solveset_real` to get the null set answer because solveset itself returns a NotImplementedError. The solutions returned that you noted above are valid as may be confirmed by backsubstitution:

```python
>>> var('x')
x
>>> solve(cos(x)-2)
[2*pi - acos(2), acos(2)]
>>> [cos(x).subs(x,i).n() for i in _]
[2.00000000000000, 2.00000000000000]
```

To only consider real solutions, set the attribute on `x`:

```python
>>> var('x', real=True)
x
>>> solve(cos(x)-2)
[]
```

**Comment by Sumith1896** [comment]
Sorry, I hadn't considered the fact of `asin(2)` not lying in real domain. And yes I had used `solveset_real`
