### ISSUE TITLE
ln(n) is not known to be nonnegative for positive integer n

### ISSUE THREAD

**Issue by pelegm** [sympy/sympy#9116]
If `n` is a positive integer, it is as least 1, hence `ln(n)` is at least 0, hence I'd expect
```python
>>> ln(n).is_nonnegative
```
to return `True` (but it returns `None`).

**Comment by pelegm** [comment]
It may worth noting that for a prime `p`, `ln(p).is_positive` is indeed `True`.

**Comment by Sumith1896** [comment]
```
In [4]: n = 3

In [5]: ln(n).is_nonnegative
Out[5]: True

In [6]: n = 4

In [7]: ln(n).is_nonnegative
Out[7]: True
```
That doesn't seem to be the case.

**Comment by Sumith1896** [comment]
Could you show a more detailed version of how to reproduce this bug?

**Comment by pelegm** [comment]
In your examples `n` is not a symbol, but rather a number.

**Comment by Newman101** [comment]
Related: #9157. Basically, this happens, when one defines n to be a symbol and then tries to use number methods to n. 

I reproduced the bug by simply... 

In [15]: n = Symbol('n', integer = True, positive = True)
In [16]: n.is_Symbol
Out[16]: True

Now, if you try ln(n):

In [18]: type(ln(n))
Out[18]: sympy.functions.elementary.exponential.log

**Comment by pelegm** [comment]
@Newman101, I have no idea what you're talking about. What you describe is not a bug.
