### ISSUE TITLE
roots of third order equation have imaginary terms

### ISSUE THREAD

**Issue by TRiedling** [sympy/sympy#9120]
When i try to solve the following equation with sympy 0.76, the answer is not accurate
``` 
x=symbols('x')
q=Eq(x**3+4.5*x**2-12*x-15)
solve(q,x)
```
I get:
[−6.06985210467499+1.0⋅10−20i,−0.972156417567709+3.0⋅10−20i,2.5420085222427+1.0⋅10−20i]

The solutions shouldn't have an imaginary part.

Am I doing something wrong?

Thanks for your great work!

### update
___
There is no error here, but perhaps a note could be added to the tutorial/gotchas regarding imaginary parts in solutions.

**Comment by smichr** [comment]
See the comment I left at this [similar stackoverflow question](http://stackoverflow.com/questions/24740517/python-sympy-trigonometric-solution-of-cubic-equation#comment44014595_24743048). By using a Float (the 4.5) you force the solution to be evaluated. If you had used `9*x**2/2` instead you would have obtained 

```
>>> solve(x**3+9*x**2/2-12*x-15)
[-3/2 - 75/(4*(-1/2 - sqrt(3)*I/2)*(1053/8 + 27*sqrt(3526)*I/4)**(1/3
- sqrt(3)*I/2)*(1053/8 + 27*sqrt(3526)*I/4)**(1/3)/3, -3/2 - (-1/2 +
)*(1053/8 + 27*sqrt(3526)*I/4)**(1/3)/3 - 75/(4*(-1/2 + sqrt(3)*I/2)*
7*sqrt(3526)*I/4)**(1/3)), -3/2 - (1053/8 + 27*sqrt(3526)*I/4)**(1/3)
(1053/8 + 27*sqrt(3526)*I/4)**(1/3))]
>>> print filldedent(_)

[-3/2 - 75/(4*(-1/2 - sqrt(3)*I/2)*(1053/8 +
27*sqrt(3526)*I/4)**(1/3)) - (-1/2 - sqrt(3)*I/2)*(1053/8 +
27*sqrt(3526)*I/4)**(1/3)/3, -3/2 - (-1/2 + sqrt(3)*I/2)*(1053/8 +
27*sqrt(3526)*I/4)**(1/3)/3 - 75/(4*(-1/2 + sqrt(3)*I/2)*(1053/8 +
27*sqrt(3526)*I/4)**(1/3)), -3/2 - (1053/8 +
27*sqrt(3526)*I/4)**(1/3)/3 - 75/(4*(1053/8 +
27*sqrt(3526)*I/4)**(1/3))]
```

In either case (yours or above), if you re-evaluate with chop=True you should see the real solutions:

```
>>> [i.n(chop=True) for i in _]
[-0.972156417567709, 2.54200852224270, -6.06985210467499]
```

**Comment by smichr** [comment]
You can also see the roots without the imaginary parts if you are willing to see them written in terms of trig functions instead:


```
>>> for i in roots(x**3+9*x**2/2-12*x-15,trig=True): print i
...
-3/2 - 5*sin(-acos(-39/125)/3 + pi/6)
-3/2 + 5*cos(acos(-39/125)/3)
-5*cos(-acos(-39/125)/3 + pi/3) - 3/2
```

**Comment by smichr** [comment]
If you want numerical values, you could also use `nroots` directly:

```
>>> nroots(x**3+9*x**2/2-12*x-15)
[-6.06985210467499, -0.972156417567709, 2.54200852224270]
```

**Comment by TRiedling** [comment]
Thanks a lot for your suggestions!
I think for me nroots is the best solution, because I use sympy in ipython as a calculator.
