### ISSUE TITLE
IntQubit doesn't work if the number of qubits to use is 1

### ISSUE THREAD

**Issue by Temigo** [sympy/sympy#9136]
Using Python 3.4 and SymPy 0.7.6, I came through this strange output : 

```
>>> from sympy.physics.quantum.qubit import Qubit, IntQubit
>>> IntQubit(0,1)
|1>
>>> IntQubit(1,1)
|3>
>>> Qubit(IntQubit(0,1))
|01>
>>> Qubit(IntQubit(1,1))
|11>
```

Shouldn't it return the same as `IntQubit(0)` and `IntQubit(1)` (that is, `|0>` and `|1>`) ? Or am I missing something ?

**Comment by triviality** [comment]
I believe this really a bug. I think it happened because ```IntQubit```  inherit ```Qubit```, and ```Qubit``` accept two representation for qubit. For example, consider ``` v = |10101>``` , you can use ```Qubit("10101")```, or ```Qubit(1,0,1,0,1)```.

I like this library, but it looks like a forest for me when I was trying to debug the code through winpdb.

**Comment by moorepants** [comment]
Note that we currently do not have an active maintainer of the quantum physics modules but if you need help navigating the code, just ask here or on the sympy mailing list.

**Comment by triviality** [comment]
@moorepants 
I would be glad to help in Quantum modules, particularly those related to quantum computations.   However, I need some time to read  documentation. 
Thank you for informing me.
