### ISSUE TITLE
atan(n-1) is not known to be nonnegative for a positive integer n

### ISSUE THREAD

**Issue by pelegm** [sympy/sympy#9157]
Check this:
```python
>>> n = Symbol('n', integer=True, positive=True)
>>> atan(n-1).is_nonnegative
```
(should be `True`).

**Comment by Newman101** [comment]
Hi.

I checked the type of n:

In [9]: n = Symbol('n', integer = True, positive = True)
In [10]: type(n)
Out[10]: sympy.core.symbol.Symbol

Type of atan... 

In [11]: type(atan(n-1))
Out[11]: sympy.functions.elementary.trigonometric.atan

This is a class. 

What happens when you try to test non-negativity of a class?

As far as I know, this is related to #9116.

**Comment by debugger22** [comment]
> What happens when you try to test non-negativity of a class?

The class has method associated with the particular assumption which evaluates it and returns the result.

**Comment by Newman101** [comment]
In [24]: atan(n).is_nonnegative
Out[24]: True

**Comment by Newman101** [comment]
In [25]: atan(n-1).is_nonnegative

Returns none.

**Comment by debugger22** [comment]
> In [25]: atan(n-1).is_nonnegative
Returns none.

This is because it couldn't compute it to either `True` or `False`.

**Comment by Newman101** [comment]
In [28]: type(n-1)
Out[28]: sympy.core.add.Add

**Comment by Newman101** [comment]
But...

In [30]: (n-1).is_nonnegative
Out[30]: True

**Comment by debugger22** [comment]
You've this: `n = Symbol('n', integer = True, positive = True)`

Now, since `n` is +ve and an integer so the minimum value it can attain is `1`. Therefore, `n - 1` will always be non-negative. What is wrong here?

I'm unable to understand what you are trying to tell here.

**Comment by debugger22** [comment]
> In [28]: type(n-1)
Out[28]: sympy.core.add.Add

The `Add` class also has methods for assumptions.

**Comment by Newman101** [comment]
Yes, you are right about this one.

**Comment by Newman101** [comment]
Thanks for clarification, I'm in process of getting familiar to package. :)
