### ISSUE TITLE
"0/0 = 0" from `0 / Symbol('z', zero=True)`

### ISSUE THREAD

**Issue by cbm755** [sympy/sympy#9165]
@skirpichev noted this in https://github.com/sympy/sympy/issues/8751#issuecomment-68861692 in a now-closed bug and I didn't see it filed elsewhere.

````
S(0)/0   # nan, correct
````

But now:
````
z = Symbol('z', zero=True)
0/z  # 0, wrong, should be nan
(1/z).is_finite   # False, correct    (UPDATED, thanks @debugger22)
0*(1/z)   # 0, wrong, should be nan
````

Similarly:
````
f = Symbol('f', finite=False)
0*f   # 0, this is wrong, should be nan
````

Something should be checking `is_finite`?  I started taking a look inside `mul.py` but scary...!

**Comment by debugger22** [comment]
> z = Symbol('z', zero=True)
0/z  # 0, wrong, should be nan
(1/z).is_finite   # True, correct
0*(1/z)   # 0, wrong, should be nan

`(1/z).is_finite` gives `False`.

**Comment by debugger22** [comment]
```diff
diff --git a/sympy/core/mul.py b/sympy/core/mul.py
index 9d14d31..31fbc99 100644
--- a/sympy/core/mul.py
+++ b/sympy/core/mul.py
@@ -195,6 +195,8 @@ def flatten(cls, seq):
                                 bargs.insert(0, ar)
                             bargs = [Add._from_args(bargs)]
                             rv = bargs, [], None
+            if (not a.is_finite and b.is_zero) or (not b.is_finite and a.is_zero):
+                rv = [S.NaN], [], None
             if rv:
                 return rv
```

This patch fixed the problem here but caused awful lot of test failures.

**Comment by skirpichev** [comment]
> but caused awful lot of test failures

Because it's a wrong fix.  not a.is_finite != "a is infinite".  Non None is True.

Unsubscribed.

**Comment by debugger22** [comment]
> not a.is_finite != "a is infinite". Non None is True.

Oh! I see. I always miss None. :(

**Comment by asmeurer** [comment]
To me, this issue is a great example of why the assumptions should be separate from the core. Doing all this checking just to see if `0*x` should give `0` is not something that should be happening in the core.

**Comment by debugger22** [comment]
@asmeurer Agree! What would be a good place to start removing assumptions from the core so that I don't break too many things in the beginning? I want to start with some lame implementation and see how it works.

**Comment by asmeurer** [comment]
https://github.com/sympy/sympy/pull/2508 is (IMHO) a good place to start.

**Comment by debugger22** [comment]
> not a.is_finite != "a is infinite"

I'm sending a fix on the basis of this: Anything which is not commutative should be neither finite nor infinite.
