### ISSUE TITLE
Reorganize the SymPy GSoC Ideas wiki page

### ISSUE THREAD

**Issue by moorepants** [sympy/sympy#9167]
Some suggestions:

- Break this page up into sub pages. The document is just too long.
- Introduce an "idea template" that all ideas should follow with things like: intro, possible mentors, complexity, details, etc.
- Remove dated ideas.

**Comment by Chitrank-Dixit** [comment]
Hello moorepants, I want to resolve this issue I want to ask Do I need to make the subpages of the project Ideas. From the above post I have understood that we need to make a subpage of the project Idea. So I will let the Project name and its abstract displayed at the current page but make a new page with more details when a person just click the view details link.

I am not able to understand the dated idea, could you please explain this ?

**Comment by moorepants** [comment]
I'd start by making a template for an "idea". It could have headings like these:

- title
- potential mentors
- description
- rationale
- approach
- involved software
- degree of difficulty
- prerequisite knowledge

Once you create the "idea template", then you'd want to take each idea and fit it into the template.

That alone may help clean up and organize the document. Once you do that, then you can think about whether it would be better to break up the ideas page into several broad collections of ideas.

**Comment by Chitrank-Dixit** [comment]
Alright Sorry for late reply I was suffering from fever. For the sake of proper readability I am justifying the current document and also as per the following headings.

* title
* potential mentors
* status
* idea
* prerequisite
* difficulty

**Comment by Chitrank-Dixit** [comment]
Please have a look at the updated documentation. I was unable to figure out some of the potential mentors , status, prerequisite knowledge , difficulty and involved software in some ideas so I left them blank.

**Comment by moorepants** [comment]
It looks great. Can you make an "idea template" near the top of that page that has these headings and brief description of what people should put in them.

Thanks for cleaning this up!

**Comment by Chitrank-Dixit** [comment]
I have fixed the page with Proper Idea Template heading under the Submitting your Idea please, have a look at this page.

https://github.com/sympy/sympy/wiki/GSoC-2015-Ideas

**Comment by moorepants** [comment]
Awesome. Thanks. I'm closing this issue now.
