### ISSUE TITLE
Sphinx docs for sympy.liealgebras

### ISSUE THREAD

**Issue by aktech** [sympy/sympy#9171]
As of now, docs for Lie Algebra Module is not there.

**Comment by aktech** [comment]
@debugger22
Maybe an Easy To Fix label also (?)

**Comment by Jawadh-Salih** [comment]
What is this issue about ?

**Comment by aktech** [comment]
> What is this issue about ?

The documentation for sympy.liealgebras is not present in docs folder. See [this](https://github.com/sympy/sympy/tree/master/doc/src/modules) to get an idea of how docs are build for other modules.

**Comment by Jawadh-Salih** [comment]
ok.. Thank you.

**Comment by Jawadh-Salih** [comment]
is index.rst the doc file ?

**Comment by aktech** [comment]
> is index.rst the doc file ?
It basically contains the list of modules for which docs have been built.

**Comment by Jawadh-Salih** [comment]
Sorry. Still I couldn't get clearly. Do I need to create a doc for sympy.liealgebra? and please clear me with .rst file. What is the purpose of that file?

**Comment by aktech** [comment]
> Sorry. Still I couldn't get clearly. Do I need to create a doc for sympy.liealgebra? and please clear me with .rst file. What is the purpose of that file?

[.rst](http://en.wikipedia.org/wiki/ReStructuredText) is the doc file.
Yes, doc for sympy.liealgebra needs to be created. See other .rst files in the modules folder to get an idea of how docs are created.

**Comment by Jawadh-Salih** [comment]
I like to know about this doc.  how this work in codes?

**Comment by aktech** [comment]
> I like to know about this doc. how this work in codes?

Please see other docs in that folder, you need to have [Sphinx](http://sphinx-doc.org/)  documentation Generator and also read [this](https://github.com/sympy/sympy/blob/master/doc/README.rst).

**Comment by debugger22** [comment]
> I like to know about this doc. how this work in codes?

This is just a standard text format. Read more about it [here](https://en.wikipedia.org/wiki/ReStructuredText).

> It seems like I need to write a big.

You just have to connect the module with sphinx. The code is already documented.

**Comment by Jawadh-Salih** [comment]
So I need to just make a link using sphinx ? Am I correct?

**Comment by debugger22** [comment]
If that works then yes. :)

**Comment by Jawadh-Salih** [comment]
Ok thank you very much. Pleas tel me that do we need to fix a bug before 27th of this month?

**Comment by aktech** [comment]
Here is a Quote from [GSoC 2015 Application Template](https://github.com/sympy/sympy/wiki/GSoC-2015-Application-Template#patch-requirement).

> Note that because we may be slow to review the pull requests, you do not have to have your request merged by the application deadline (though you should try to do it if you can!). But you do need to at least have one submitted by then. We will give priority to reviewing requests that are needed to satisfy patch requirements. It is up to you to respond to our feedback in a timely enough manner so that your patch gets merged before the acceptance deadline.

**Comment by Jawadh-Salih** [comment]
I am going t try this using windows. Is there any issue if I use windows instead ubuntu . I mean I am going document the class liealgebra using windows.

**Comment by moorepants** [comment]
You can use any operating system you like. Sphinx and SymPy work on Windows. But there are a couple of details our documentation build chain that may be unix specific. For example, the svg conversion tool may be harder to setup on Windows. You should try and let us know if there are any issues on Windows.

**Comment by Chitrank-Dixit** [comment]
Hello @aktech and @moorepants I want to fix this issue, So to generate the html from the doc I am simply using 

$ make html

but I am getting the following error while the execution of the third process
preparing documents... 
Theme error:
unsupported theme option 'visitedlinkcolor' given
make: *** [html] Error 1

I am working on Sympy using the virtualenv wrapper and installed sphinx in virtualenv as well. Please let me know the problem.

**Comment by moorepants** [comment]
Maybe it is a Sphinx version issue?

**Comment by Chitrank-Dixit** [comment]
@moorepants I used 

$ sudo make html 

and this worked for me and I generated the local copy of the sympy documentation, I have also made a folder into the doc/source/liealgebras and writing the documentation for liealgebras , But I may need some source to look at that and then write the documentation as I have not used this module from sympy before. So please give me some source to write about this module.

**Comment by toolforger** [comment]
Ah, so it's probably an install path issue.

Using ```sudo``` for installing test versions of anything is very risky. The software in your system might get damaged, up to and including nastiness like becoming unbootable.
I wouldn't worry too much since SymPy's ```make html``` is most likely run whenever SymPy is installed normally, so that command should be well-tested and not do any damage; however, I wouldn't want to rely on that for future installs in your position.

So, better correct the ```make html``` command, probably by the install path (that's traditionally an option with ```prefix``` in its name; traditionally, ```make help``` will give you a list of options).

**Comment by Chitrank-Dixit** [comment]
thanks for the tip @toolforger , I have generated the document Lie Algebra but I am only able to generate the index.rst file for that, I do not have other information about the module so I am not able to add the contents of Lie Algebra. So this looks something like this, please let me know what content to be added in the documentation.

![selection_070](https://cloud.githubusercontent.com/assets/1781313/6884202/070a5ecc-d602-11e4-89af-5feac4c5fd67.png)

**Comment by aktech** [comment]
The code is documented already, you just need to use the auto document feature to get the documentation from the code.

For Example:

```rst
Liealgebra
==========

This module contains Liealgebra ...

.. automodule:: sympy.liealgebras

RootSystem
^^^^^^^^^^^^
.. autoclass:: RootSystem
   :members:


Type A
^^^^^^^
.. autoclass:: TypeA
   :members:

Type B
^^^^^^^
.. autoclass:: TypeB
   :members:

Type C
^^^^^^^
.. autoclass:: TypeC
   :members:

Type D
^^^^^^^
.. autoclass:: TypeD
   :members:

Type E
^^^^^^^
.. autoclass:: TypeE
   :members:

Type F
^^^^^^^
.. autoclass:: TypeF
   :members:

Type G
^^^^^^^
.. autoclass:: TypeG
   :members:

.
.
.
.. autofunction:: sympy.liealgebras.cartan_matrix.CartanMatrix


```
Create a folder in `sympy/doc/src/modules` named `liealgebras` , and create the `.rst` File there.

**Comment by Chitrank-Dixit** [comment]
thanks for the instructions @aktech , I have submitted one pull request resolving this issue please have a look 

https://github.com/sympy/sympy/pull/9215

**Comment by tokencolour** [comment]
Hello everybody,
As it has been a while anybody commented here, I took the freedom to look into this issue. I have an .rst file ready which is on the lines of what @aktech suggested here. I am new to Sympy and open source community as a whole. I have run tests and as soon as they are over I'll submit a PR. Kindly review it.

**Comment by moorepants** [comment]
@tokencolour We'd be happy to review your pull request with the new rst file. Have you submitted one?

**Comment by tokencolour** [comment]
I'll submit it as soon as I am over with #8889 .
