### ISSUE TITLE
Allow differentiation of expressions involving sympy.tensor.Indexed

### ISSUE THREAD

**Issue by joshburkart** [sympy/sympy#9185]
I'd like to be able to do things like the following: 

``` python
import sympy as sy
import sympy.tensor as syt

i, j = sy.symbols('i j', cls=syt.Idx)
h = syt.IndexedBase('h')

sy.diff(h[j] * h[j] / sy.sympify(2), h[i])
```

and receive `h[i]` as output; instead I get an error (below). Is there some other module I should be using? Or should I try implementing this? Would imagine just putting in some sort of custom rule that e.g. `Derivative(h[j], h[i]) -> KroneckerDelta[j, i]`, and then simplification rules for `KroneckerDelta`...

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-1-71447fa6ae6c> in <module>()
      5 h = syt.IndexedBase('h')
      6 
----> 7 sy.diff(h[j]*h[j]/sy.sympify(2), h[i])

/opt/anaconda3/lib/python3.4/site-packages/sympy/core/function.py in diff(f, *symbols, **kwargs)
   1639     """
   1640     kwargs.setdefault('evaluate', True)
-> 1641     return Derivative(f, *symbols, **kwargs)
   1642 
   1643 

/opt/anaconda3/lib/python3.4/site-packages/sympy/core/function.py in __new__(cls, expr, *variables, **assumptions)
   1027                 from sympy.utilities.misc import filldedent
   1028                 raise ValueError(filldedent('''
-> 1029                 Can\'t differentiate wrt the variable: %s, %s''' % (v, count)))
   1030 
   1031             if all_zero and not count == 0:

ValueError: 
Can't differentiate wrt the variable: h[i], 1
```

**Comment by smichr** [comment]
I believe this has been fixed or is fixed in #15049

**Comment by smichr** [comment]
Yes, this gives `KroneckerDelta(i, j)*h[j]` on sympy.live.org so it's been fixed for a while.

**Comment by smichr** [comment]
It is also tested:    

https://github.com/sympy/sympy/blob/5997e30a33f92e6b4b4d351e835feb7379a0e31d/sympy/tensor/tests/test_indexed.py#L285-L293

**Comment by asmeurer** [comment]
The OP code works in master. https://github.com/sympy/sympy/issues/11568 tracks the remaining issues with derivatives wrt indexed expressions. Let's move the discussion on this over there.
