### ISSUE TITLE
Lambdify deprecation doesn't actually throw warning

### ISSUE THREAD

**Issue by jcrist** [sympy/sympy#9191]
So, in the process of rewriting how the deprecation for lambdify `Matrix` -> `matrix` works for the 3rd time (see #8034), it somehow slipped through that the warning doesn't actually ever get thrown. This is a simple fix, but the bigger issue is how to deal with the deprecation now that we've had a release go by.

I think the only option we have is to bump the deprecation timeline back another release, which is unfortunate. But as users haven't been notified, there's not much else to do.

**Comment by jcrist** [comment]
ping @moorepants : thoughts on the best fix? If no one has a better suggestion, I'll bump the deprecation date back one release, and fix the warning to be actually thrown.

**Comment by moorepants** [comment]
We can bump it back a release. That's fine. It's worth having people see this warning. I think lambdify is used a lot in the wild and it's probably worth letting this deprecate properly.

**Comment by moorepants** [comment]
But maybe since we haven't had any complaints so far it isn't worth worrying about. I'd say put this on the 0.7.7 milestone and if we haven't received any complaints by the time we are ready to release, then don't worry about it.

**Comment by asmeurer** [comment]
0.7.7 will be 1.0. What ever happend with this? What needs to be done for the 1.0 release?

**Comment by asmeurer** [comment]
I don't know if we received any complaints, although I don't know why we would, since the behavior is only different in master. 

@jcrist @moorepants I remember discussing this at SciPy, but I don't remember what conclusion we came to.

**Comment by asmeurer** [comment]
I guess according to https://github.com/sympy/sympy/pull/9657, we decided to just change it. Meaning this issue can be closed, unless anyone objects.

**Comment by moorepants** [comment]
There have been no complaints if this was in 0.7.6, so we can ignore the proper deprecation.

**Comment by asmeurer** [comment]
Again, not sure what complaints you were expecting. 0.7.6 was identical to 0.7.5 except that the release notes mentioned a deprecation. The behavior didn't change until 0.7.7-dev.

**Comment by moorepants** [comment]
Oh yeah. I think we got the deprecation warning wrong, so no one has been warned that we are changing this for the next release. Maybe we do need to fix it so that users get some kind of warning.
