### ISSUE TITLE
O(y + 1) = O(1)

### ISSUE THREAD

**Issue by j2kun** [sympy/sympy#9192]
I'm getting a very silly output from some simple big-O expressions involving O(1). I'm using Sympy 0.7.5, but I don't see anything in the release notes for 0.7.6 that addresses this issue.

```
    >>> y = Symbol('y')
    >>> O(y + 1)
    O(1)
    >>> x = O(1)
    >>> x * x
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.3/site-packages/sympy/core/decorators.py", line 77, in __sympifyit_wrapper
    return func(a, b)
  File "/usr/local/lib/python3.3/site-packages/sympy/core/decorators.py", line 118, in binary_op_wrapper
    return func(self, other)
  File "/usr/local/lib/python3.3/site-packages/sympy/core/expr.py", line 125, in __mul__
    return Mul(self, other)
  File "/usr/local/lib/python3.3/site-packages/sympy/core/cache.py", line 93, in wrapper
    r = func(*args, **kw_args)
  File "/usr/local/lib/python3.3/site-packages/sympy/core/operations.py", line 40, in __new__
    c_part, nc_part, order_symbols = cls.flatten(args)
  File "/usr/local/lib/python3.3/site-packages/sympy/core/mul.py", line 237, in flatten
    o, order_symbols = o.as_expr_variables(order_symbols)
  File "/usr/local/lib/python3.3/site-packages/sympy/series/order.py", line 284, in as_expr_variables
    if order_symbols[0][1] != self.point[0]:
IndexError: tuple index out of range
```
```
    >>> O(1) ** O(1) # should be O(1)
    O(1)**O(1) 
```
However, this one works, which is strange.
```
    >>> O(1) + y**y
    y**y + O(1)
```

**Comment by debugger22** [comment]
This was supposed to raise `NotImplementedError` but because of a bad check it fails just above it.

**Comment by debugger22** [comment]
No, my bad. This should give a genuine output.

**Comment by hacman** [comment]
It was not addressed here that `O(1+y)` is expected to be `O(1)` since the limit is taken as y -> 0 by default. The sympy documentation could be more clear on this point. It does mention that the default limit is taken as the variable approaches 0, but it is the last line of the class doc string (for the Order class). Also, although there are examples, the documentation does not explain that you can substitute your own limit such as `O(1+y, (y, oo))`, which gives the `O(y)` that the original creator of this issue probably expected.

**Comment by jcrist** [comment]
@hacman: if the docs on `O` are confusing, please open a new issue expressing your concerns.

**Comment by j2kun** [comment]
@hacman @jcrist I may be of a different mindset, but a big-O shouldn't ever evaluate to anything. Having a big-O "evaluate" to something is not helpful from a mathematical perspective. Nobody ever used a big-O to kill terms, but rather to bound some complicated expression asymptotically *while still expressing* the existence of that term to the reader. Big-O is not synonymous with taking a limit.

But even if you want big-O's to evaluate to something, the current behavior has consistency issues. If it makes sense for O(y+1) = O(1) (because by default y -> 0), then O(1+y, (y, oo)) should evaluate to oo. At the least, it would be helpful for me as a user if any implicit "limiting value" was expressed symbolically and not used to silently kill a term.

**Comment by toolforger** [comment]
I'm having similar concerns as @j2kun, though I'm coming from a slightly different schoolbook definition.
By that definition, `O` is not merely a notational shorthand for an assumption; instead, `O(whatever)` is the class of functions that behave asymptotically the same as `whatever`.
By that definition, the shortest form to express an `O` expression is again an `O` expression, possibly simplified (i.e. `O(x+1)` could become `O(x)`).

What's unintuitive about `O` as it stands is that by default, it assumes that all symbols are constants.
Which makes `O(x + x**2)` equivalent to `O(x)`, though readers would expect it to be `O(x**2)`.
I think `O` as implemented ignores the common convention that if a formula contains just one free variable, it is supposed to be the limit.
I'm not sure that implementing that convention is a good idea; it could lead to unexpected behaviour.
I'd rather expect that to the standard assumptions, e.g. ```x```, ```y```, ```z```, ```a```, ```b```, ```c```, ... could be assumed to be free variables, while ```C``` would be assumed to be a constant. Though that would run counter to the conventions in the vector and physics modules, which routinely use ```A```, ```B```, ```C```, ... for matrixes.

I guess the easiest thing to do would be to add a caveat to the docs, in that you *must* supply the free variable to `O`.
