### ISSUE TITLE
Are there any python libraries that convert Math Ml to Sympy understandable format.

### ISSUE THREAD

**Issue by mandavavinay** [sympy/sympy#9200]
Are there any python libraries that convert Math Ml to Sympy understandable format. I want to pass Math Ml to sympy from my application. So, is there a way to do this.

**Comment by moorepants** [comment]
@mandavavinay This is best asked on the SymPy mailing list or on Stackoverflow. The issues are for bugs and feature requests, etc.

**Comment by mandavavinay** [comment]
Thanks Moore.

On Wed, Mar 25, 2015 at 9:18 PM, Jason K. Moore <notifications@github.com>
wrote:

> @mandavavinay <https://github.com/mandavavinay> This is best asked on the
> SymPy mailing list or on Stackoverflow. The issues are for bugs and feature
> requests, etc.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sympy/sympy/issues/9200#issuecomment-86091045>.
>



-- 
Vinay Mandava
91-9885127836
