### ISSUE TITLE
are_collinear(*points) : strange code  

### ISSUE THREAD

**Issue by fbenmena** [sympy/sympy#9214]
According to the present code of `are_collinear` method (included in the `Point3D` class), I
think there is a bug (the fixing is easy).  The bug arises when the method is called with 3 points.
Here is a minimal sample

```
>>> pt1 = Point3D(0, 0, -1)
>>> pt2 = Point3D(1, -1, -1)
>>> pt3 = Point3D(1, 1, -1)
>>> Point3D.are_collinear(pt1, pt2, pt3) ## True
The reason is that
>>> a = pt1.direction_cosine(pt2) ## [sqrt(2)/2, -sqrt(2)/2, 0]
>>> b = pt1.direction_cosine(pt3) ## [sqrt(2)/2, sqrt(2)/2, 0]
```

the code assumes the return is True if all components of `a` and `b` have same absolute value.  The right test isn't that `a` and `b` are either equal or opposite ?

Am'I wrong ?

**Comment by jksuom** [comment]
I think you are right.
