### ISSUE TITLE
asec(0).is_real throws ZeroDivisionError

### ISSUE THREAD

**Issue by proy87** [sympy/sympy#9220]
Everything written in the header.

**Comment by toolforger** [comment]
```asec(x)``` is not defined for ```-1 < x < 1``` (see https://en.wikipedia.org/wiki/File:Arcsecant_Arccosecant.svg).
It is possible that ```is_real``` tries to evaluate ```asec(0)```, which fails.

**Comment by simamura87** [comment]
Exactly.
I think, that is_real should return False in this case, not throw error.

**Comment by aktech** [comment]
I think it uses `mpmath` for evaluating this, and `mpmath` doesn't performs a check on the arguments passed.

```python
In [1]: from mpmath import *
In [2]: asec(0)
---------------------------------------------------------------------------
ZeroDivisionError                         Traceback (most recent call last)
<ipython-input-2-09ba3eda89a4> in <module>()
----> 1 asec(0)
..
..
..
```

Also, there are no assumption helper functions written in `trigonometric.py` to do this correctly.

**Comment by jksuom** [comment]
``asec(x)`` is defined for all ``x != 0``. I believe SymPy should return ``nan`` for ``asec(0)``.

**Comment by aktech** [comment]
> `asec(x)` is defined for all `x != 0`. I believe SymPy should return `nan` for `asec(0)`.

The domain of arcsec x is: All values of x, except -1 < x < 1 .
See link given by **toolforger**.

**Comment by jksuom** [comment]
The link is only concerned with real values. Values between -1 and 1 are imaginary.

**Comment by aktech** [comment]
Oh I see, It is defined but the range is not in real. 
Thanks!

**Comment by jksuom** [comment]
[Here](http://functions.wolfram.com/ElementaryFunctions/ArcSec/02/) is one explicit formula. There are other versions too.

**Comment by aktech** [comment]
So, it seems `asec(x).is_real` should return `nan` for `x = 0` and for all `x` between -1 to 1 (except 0) it should return False, as it appears imaginary from the formula.

**Comment by jksuom** [comment]
``nan.is_real`` is currently ``None``. So that could be the result of ``asec(0).is_real``.

**Comment by aktech** [comment]
Indeed.

**Comment by toolforger** [comment]
Am 30.03.2015 um 17:38 schrieb AMiT Kumar:
> So, it seems `asec(x).is_real` should return `nan` for `x = 0`

Shouldn't that be `None`?

**Comment by aktech** [comment]
> Shouldn't that be `None`?

Yes, Indeed. `nan` would not make sense. All `is_property` should only return True, False or None.
