### ISSUE TITLE
Pow gives wrong output for is_infinite

### ISSUE THREAD

**Issue by debugger22** [sympy/sympy#9227]
```
In [3]: z = Symbol('z', zero=True)

In [4]: (1/z).is_commutative
Out[4]: True  # Correct

In [5]: (1/z).is_finite
Out[5]: False  # Correct

In [6]: (1/z).is_infinite  # Should be True
```

**Comment by skirpichev** [comment]
> (1/z).is_infinite  # Should be True

Sure, it shouldn't.  According to old assumptions: "infinite -> !finite", but not vice versa.  That make sense, as 1/z is not an infinite quantity (in sense of e.g. `math.isinfinite()`).

It would be wise if you first take into account the current documentation and definitions in the codebase.  At least, when you attach "Easy to Fix" labels.  But, perhaps, I have too high requirements for sympy developers.

**Comment by debugger22** [comment]
Sorry. Closing for https://github.com/sympy/sympy/pull/9179#discussion_r27041593

**Comment by asmeurer** [comment]
1/z would be zoo. I don't remember if we decided if zoo should be infinite in the assumptions system. I suppose there advantages to making it so only positive and negative infinity are "infinite" (e.g., then "extended real" would mean exactly "real U infinite").

**Comment by skirpichev** [comment]
Hmm, "object absolute value is bounded (is value is arbitrarily large)" - the definition for finite (infinite) in assumptions.py.  So, if it's a real failing test for #9179, maybe it make sense in this issue.

Probably, you want a new is_infinite handler for Mul.  I doubt it's an easy to fix issue, however.
