### ISSUE TITLE
dsolve: needs Poly and Dummy fixes

### ISSUE THREAD

**Issue by cbm755** [sympy/sympy#9238]
I've been looking at dsolve in #9235.

@ga7g08 there is lots of code in ode.py that needs the same sort of fixes that you did in #9025...  Interested?  See the `_linear_2eq_order<>_type<>` files.

Here's a nice construct I've learned for this:

```
-        x0, y0 = symbols('x0, y0')
+        x0, y0 = symbols('x0, y0', cls=Dummy) 
```

**Comment by ga7g08** [comment]
I would be happy to help. Before I go ahead and start making PRs can I check exactly what you would like to see? My assumption is

* All cases of `symbols` to use the `Dummy` variable as you mentiond
* All `RootsOf` to be passed the `Dummy` as we did in #9025 

Do the tests also need to be modified to reflect this?

**Comment by cbm755** [comment]
> All cases of symbols to use the Dummy variable

That's a pretty broad statement... at least we have to think about each case.

I'm not sure about tests for the symbol->dummy change: we didn't have one in #9025 right?  I'm not really sure how to test this!

Re: RootsOf: maybe in some cases there are better ways?  I also saw something (IIRC on maillist) where RootsOf rather rudely converted Floats to Rationals without asking[**], so maybe its worth considering what options there are here.  See also @skirpichev's comments in #9025.

Re: tests for the RootsOf change: ideally we could test each solver with a problem involving a parameter.  Not sure how much work that might be in practice.

Currently, I'm trying to replace most of the linear sysode solvers (which are full of bugs) with a single function.  So maybe it makes sense to start with the nonlinear ones?

[**] the reason for this, I think, to wanting to avoid the usage of numerical rootfinding.  I offer no opinion on whether that is a good idea or not.

**Comment by ga7g08** [comment]
Hello Colin,

I've had a look into the nonlinear solvers and as far as I can tell they don't seem to have any issue with arbitary parameters. If I am completely honest I think I am a bit out of my depth as it is taking me a long time to work out exactly how the code is working. I really would like to help though, so feel free to ping me if there is something I can handle, but I really don't know what you're asking for here. 

Cheers, 

Greg

**Comment by cbm755** [comment]
> I've had a look into the nonlinear solvers and as far as I can tell
> they don't seem to have any issue with arbitary parameters. If I am
> completely honest I think I am a bit out of my depth

Hah!  Me too :)   We could just change them to use Dummy instead of 
Symbol, just by reading the code.  If you have any tests with arbitrary 
parameters that you've been playing with then we add those as tests.

Otherwise, shame to waste the time you've put into wading through this...

(Its ok to make changes to the linear ones too: I didn't mean to 
discourage you from that code.)

**Comment by virajvekaria** [comment]
Hey is this issue still open? Can I do something to help?

**Comment by oscarbenjamin** [comment]
The ode code has been largely rewritten so I don't think this issue is relevant any more.

**Comment by virajvekaria** [comment]
@oscarbenjamin I needed some help with issue #26139, please can you look into it.
