### ISSUE TITLE
dsolve: sysode stuff not careful defining new constants

### ISSUE THREAD

**Issue by cbm755** [sympy/sympy#9239]
Lots of code like `C1, C2, C3, C4 = symbols('C1:5')` but is it supposed to be using this instead?

```
def get_numbered_constants(eq, num=1, start=1, prefix='C'):
    """
    Returns a list of constants that do not occur
    in eq already.
    """
```

I might address this in #9235, but feel free to take it.

**Comment by meghana1995** [comment]
Can I take this issue up? ( I'm a beginner though so might take me a few of days or so.)

**Comment by debugger22** [comment]
Sure! You can start by taking a look at the output of this. `git grep "get_numbered_constants("`

**Comment by cbm755** [comment]
Yes, sure.  Some more comments:

1.  Might be nice to start with a test that included `C1` as an input and thus failed.
2.  I think this mostly effects systems (the scalar ODE code looks better so maybe follow what they do).
3.  You can send a pull request while you're still working, just mark it with "WIP" until its ready for review.

**Comment by meghana1995** [comment]
Thank you for the suggestions, I will proceed in that manner.

**Comment by sss97** [comment]
I would like to work on this issue! Can someone guide me on how should I get started?

**Comment by oscarbenjamin** [comment]
It looks like this is fixed now and `get_numbered_constants` is used everywhere.
