### ISSUE TITLE
Bug in galgebra

### ISSUE THREAD

**Issue by moble** [sympy/sympy#9245]
I know that `galgebra` [has parted ways with sympy](https://github.com/sympy/sympy/issues/8365), and will be separated in the next release, but I think this should be reported as a bug either way.

[In the forum](https://groups.google.com/d/msg/sympy/kSeAqzXtTv8/8bYqmsydS5sJ), chaowen guo pointed out a bug in obtaining the inverse of the pseudoscalar.  The code to reproduce this bug is:

``` python
from __future__ import print_function
import sympy.galgebra
sympy.galgebra.Format(ipy=True)
base=sympy.galgebra.MV.setup('e*1|2')
print(str(sympy.galgebra.MV.I.inv()))
print(str(sympy.galgebra.MV.Iinv))
```

The first print statement gives an incorrect result, seemingly assuming that `e1` and `e2` are orthonormal.  The second gives the expected result, which makes no assumptions about the metric.

I've traced this back to a problem in `__div__` in `ga.py`.  Apparently, the `MV` itself and `MV.obj` are storing different results.  In particular, if you print out the `.obj` fields instead of the `MV`s themselves, the result is closer to correct (though the printing is wonky).  Alternatively, if you drop the `sympy.galgebra.Format(ipy=True)` statement, the output is also correct.  I guess this could be considered a bug in the formatting, but ultimately, the `MV` object contains/returns incorrect data.

**Comment by moble** [comment]
I probably should have pinged @brombo about this.  Alan, is this still a problem in your new [galgebra](https://github.com/brombo/galgebra)?

**Comment by brombo** [comment]
On 04/06/2015 04:44 PM, Mike Boyle wrote:
>
> I probably should have pinged @brombo <https://github.com/brombo> 
> about this. Alan, is this still a problem in your new galgebra 
> <https://github.com/brombo/galgebra>?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/sympy/sympy/issues/9245#issuecomment-90233944>.
>
Using galgebra at github.com/brombo/galgebra

and

from ga import Ga
base = Ga('e*1|2')
I = base.I()
Iinv = I.inv()
print 'I =',I
print '1/I =',Iinv
print 'I*(1/I) =',I*Iinv

I get

I = e_1^e_2/sqrt(Abs((e_1.e_1)*(e_2.e_2) - (e_1.e_2)**2))
1/I = -sqrt(Abs((e_1.e_1)*(e_2.e_2) - 
(e_1.e_2)**2))*e_1^e_2/((e_1.e_1)*(e_2.e_2) - (e_1.e_2)**2)
I*(1/I) = 1

Somethings have changed quite a bit.  Look at the documentation at 
github.com/brombo/galgebra

**Comment by moble** [comment]
Seems to work in the new external version.
