### ISSUE TITLE
Limit with a positive parameter fails

### ISSUE THREAD

**Issue by pelegm** [sympy/sympy#9252]
I let `n` be my integer variable, which will tend to `oo`, and `c` is a positive (real) parameter:

``` python
>>> n = Symbol('n', integer=True)
>>> c = Symbol('c', positive=True)
```

Then I calculate the following parametric limit:

``` python
>>> limit((ln(n))**(n/ln(n)) / c**n, n, oo)
oo
```

But that result is not generally true, as

``` python
>>> limit((ln(n))**(n/ln(n)) / 2**n, n, oo)
0
```

**Comment by 0sidharth** [comment]
This issue had been fixed on the current master I believe. 

```
>>> limit((ln(n))**(n/ln(n)) / c**n, n, oo)
NotImplementedError: Result depends on the sign of -sign(log(c))

>>> limit((ln(n))**(n/ln(n)) / 2**n, n, oo)
0

>>> limit((ln(n))**(n/ln(n)) / 0.5**n, n, oo)
oo
```
If anyone can confirm this result and that it is correct, only regression tests need to be added.
