### ISSUE TITLE
integrate(1/x**2,(x,-1,oo)) returns -1

### ISSUE THREAD

**Issue by ivanslapnicar** [sympy/sympy#9270]

**Comment by toolforger** [comment]
Seems it's ignoring the pole at `x==0`.
There's also something funny going on with the sign, integrating from `1` to `0` gives me `-oo` instead of the expected `oo`.

**Comment by hacman** [comment]
I think this is a dupe of #4215. Also, I think the result of integrating from 1 to 0 is correct. When you reverse the limits of integration, you negate the sign of the integral.

**Comment by debugger22** [comment]
> I think this is a dupe of #4215.

+1 for closing. https://github.com/sympy/sympy/issues/4215#issuecomment-36989914
