### ISSUE TITLE
Wrong Jordan form: complex eigenvalues w/ geo. mult. > alg. mult.

### ISSUE THREAD

**Issue by cbm755** [sympy/sympy#9274]
Consider the following matrix:

````
In [172]: L = Matrix([[2, 4], [-4, 2]])

In [173]: Z = zeros(2,2);  I = Identity(2)

In [174]: A = Matrix(BlockMatrix([[L, I], [Z, L]]))

In [175]: pprint(A)
⎡2   4  1   0⎤
⎢            ⎥
⎢-4  2  0   1⎥
⎢            ⎥
⎢0   0  2   4⎥
⎢            ⎥
⎣0   0  -4  2⎦
````

Compute its Jordan form:

````
In [177]: pprint(A.jordan_form())
⎛⎡0  ⅈ  ⅈ  0⎤, ⎡2 - 4⋅ⅈ     1        0        0        0        0        0        0        0        0   ⎤⎞
⎜⎢          ⎥  ⎢                                                                                        ⎥⎟
⎜⎢0  1  1  0⎥  ⎢   0     2 - 4⋅ⅈ     0        0        0        0        0        0        0        0   ⎥⎟
⎜⎢          ⎥  ⎢                                                                                        ⎥⎟
⎜⎢0  0  0  ⅈ⎥  ⎢   0        0     2 - 4⋅ⅈ     1        0        0        0        0        0        0   ⎥⎟
⎜⎢          ⎥  ⎢                                                                                        ⎥⎟
⎜⎣0  0  0  1⎦  ⎢   0        0        0     2 - 4⋅ⅈ     0        0        0        0        0        0   ⎥⎟
⎜              ⎢                                                                                        ⎥⎟
⎜              ⎢   0        0        0        0     2 - 4⋅ⅈ     0        0        0        0        0   ⎥⎟
⎜              ⎢                                                                                        ⎥⎟
⎜              ⎢   0        0        0        0        0     2 + 4⋅ⅈ     1        0        0        0   ⎥⎟
⎜              ⎢                                                                                        ⎥⎟
⎜              ⎢   0        0        0        0        0        0     2 + 4⋅ⅈ     0        0        0   ⎥⎟
⎜              ⎢                                                                                        ⎥⎟
⎜              ⎢   0        0        0        0        0        0        0     2 + 4⋅ⅈ     1        0   ⎥⎟
⎜              ⎢                                                                                        ⎥⎟
⎜              ⎢   0        0        0        0        0        0        0        0     2 + 4⋅ⅈ     0   ⎥⎟
⎜              ⎢                                                                                        ⎥⎟
⎝              ⎣   0        0        0        0        0        0        0        0        0     2 + 4⋅ⅈ⎦⎠
````

This is wrong.  The J matrix is too big.  And there is a zero (generalized) eigenvector.

So far, I've traced it back to here:
````
In [178]: pprint(A._jordan_block_structure())
⎧2 - 4⋅ⅈ: ⎧1: ⎡⎡⎡ⅈ⎤⎤⎤, 2: ⎡⎡⎡0⎤, ⎡ⅈ⎤⎤, ⎡⎡ⅈ⎤, ⎡0⎤⎤⎤⎫, 2 + 4⋅ⅈ: ⎧1: ⎡⎡⎡-ⅈ⎤⎤⎤, 2: ⎡⎡⎡0⎤, ⎡-ⅈ⎤⎤, ⎡⎡-ⅈ⎤, ⎡0 ⎤⎤⎤⎫⎫
⎪         ⎪   ⎢⎢⎢ ⎥⎥⎥     ⎢⎢⎢ ⎥  ⎢ ⎥⎥  ⎢⎢ ⎥  ⎢ ⎥⎥⎥⎪           ⎪   ⎢⎢⎢  ⎥⎥⎥     ⎢⎢⎢ ⎥  ⎢  ⎥⎥  ⎢⎢  ⎥  ⎢  ⎥⎥⎥⎪⎪
⎪         ⎪   ⎢⎢⎢1⎥⎥⎥     ⎢⎢⎢0⎥  ⎢1⎥⎥  ⎢⎢1⎥  ⎢0⎥⎥⎥⎪           ⎪   ⎢⎢⎢1 ⎥⎥⎥     ⎢⎢⎢0⎥  ⎢1 ⎥⎥  ⎢⎢1 ⎥  ⎢0 ⎥⎥⎥⎪⎪
⎨         ⎨   ⎢⎢⎢ ⎥⎥⎥     ⎢⎢⎢ ⎥  ⎢ ⎥⎥  ⎢⎢ ⎥  ⎢ ⎥⎥⎥⎬           ⎨   ⎢⎢⎢  ⎥⎥⎥     ⎢⎢⎢ ⎥  ⎢  ⎥⎥  ⎢⎢  ⎥  ⎢  ⎥⎥⎥⎬⎬
⎪         ⎪   ⎢⎢⎢0⎥⎥⎥     ⎢⎢⎢0⎥  ⎢0⎥⎥  ⎢⎢0⎥  ⎢ⅈ⎥⎥⎥⎪           ⎪   ⎢⎢⎢0 ⎥⎥⎥     ⎢⎢⎢0⎥  ⎢0 ⎥⎥  ⎢⎢0 ⎥  ⎢-ⅈ⎥⎥⎥⎪⎪
⎪         ⎪   ⎢⎢⎢ ⎥⎥⎥     ⎢⎢⎢ ⎥  ⎢ ⎥⎥  ⎢⎢ ⎥  ⎢ ⎥⎥⎥⎪           ⎪   ⎢⎢⎢  ⎥⎥⎥     ⎢⎢⎢ ⎥  ⎢  ⎥⎥  ⎢⎢  ⎥  ⎢  ⎥⎥⎥⎪⎪
⎩         ⎩   ⎣⎣⎣0⎦⎦⎦     ⎣⎣⎣0⎦  ⎣0⎦⎦  ⎣⎣0⎦  ⎣1⎦⎦⎦⎭           ⎩   ⎣⎣⎣0 ⎦⎦⎦     ⎣⎣⎣0⎦  ⎣0 ⎦⎦  ⎣⎣0 ⎦  ⎣1 ⎦⎦⎦⎭⎭
````

**Comment by jksuom** [comment]
It seems that the bug is in the implementation of what these lines explain:
```
# We want the vectors in `Kernel((self-lI)^s)` (**),
# but without those in `Kernel(self-lI)^s-1` so we will add  these as additional equations
# to the sytem formed by `S`
```
The idea of adding new equations is to restrict the null space of ``(self-lI)^s`` to those vectors that are orthogonal to `` Kernel(self-lI)^s-1``. This works well in the real case, but vectors in the complex domain can be 'orthogonal' to themselves unless hermitian metric is applied. So, instead of
adding the vectors of `` Kernel(self-lI)^s-1`` as such, their complex conjugates should be used here:
```
for k in range(0, a[s-1]):
    S = S.col_join((exclude_vectors[k]).transpose())
```

**Comment by cbm755** [comment]
I changed to `S = S.col_join((exclude_vectors[k]).H)` and that does look better, although not quite right yet:

In [13]: pprint(A.jordan_cells())
⎛⎡ⅈ  0  ⅈ  -ⅈ⎤, ⎡⎡2 - 4⋅ⅈ     1   ⎤, [2 - 4⋅ⅈ], ⎡2 + 4⋅ⅈ     1   ⎤, [2 + 4⋅ⅈ]⎤⎞
⎜⎢           ⎥  ⎢⎢                ⎥             ⎢                ⎥           ⎥⎟
⎜⎢1  0  1  1 ⎥  ⎣⎣   0     2 - 4⋅ⅈ⎦             ⎣   0     2 + 4⋅ⅈ⎦           ⎦⎟
⎜⎢           ⎥                                                                ⎟
⎜⎢0  ⅈ  0  0 ⎥                                                                ⎟
⎜⎢           ⎥                                                                ⎟
⎝⎣0  1  0  0 ⎦                                                                ⎠

In [14]: pprint(A.jordan_form())
⎛⎡ⅈ  0  ⅈ  -ⅈ⎤, ⎡2 - 4⋅ⅈ     1        0        0        0        0   ⎤⎞
⎜⎢           ⎥  ⎢                                                    ⎥⎟
⎜⎢1  0  1  1 ⎥  ⎢   0     2 - 4⋅ⅈ     0        0        0        0   ⎥⎟
⎜⎢           ⎥  ⎢                                                    ⎥⎟
⎜⎢0  ⅈ  0  0 ⎥  ⎢   0        0     2 - 4⋅ⅈ     0        0        0   ⎥⎟
⎜⎢           ⎥  ⎢                                                    ⎥⎟
⎜⎣0  1  0  0 ⎦  ⎢   0        0        0     2 + 4⋅ⅈ     1        0   ⎥⎟
⎜               ⎢                                                    ⎥⎟
⎜               ⎢   0        0        0        0     2 + 4⋅ⅈ     0   ⎥⎟
⎜               ⎢                                                    ⎥⎟
⎝               ⎣   0        0        0        0        0     2 + 4⋅ⅈ⎦⎠

It is still giving erroneous multiplicity-1 blocks for each eigenvalue.

**Comment by jksuom** [comment]
Those vectors are added in two places, [here](https://github.com/sympy/sympy/blob/master/sympy/matrices/matrices.py#L3624) and [here](https://github.com/sympy/sympy/blob/master/sympy/matrices/matrices.py#L3652). After changing transpose() to adjoint() in both lines I seem to get quite reasonable looking results.
```
In [5]: pprint(A.jordan_cells())
⎛⎡ⅈ  0  -ⅈ  0 ⎤, ⎡⎡2 - 4⋅ⅈ     1   ⎤, ⎡2 + 4⋅ⅈ     1   ⎤⎤⎞
⎜⎢            ⎥  ⎢⎢                ⎥  ⎢                ⎥⎥⎟
⎜⎢1  0  1   0 ⎥  ⎣⎣   0     2 - 4⋅ⅈ⎦  ⎣   0     2 + 4⋅ⅈ⎦⎦⎟
⎜⎢            ⎥                                          ⎟
⎜⎢0  ⅈ  0   -ⅈ⎥                                          ⎟
⎜⎢            ⎥                                          ⎟
⎝⎣0  1  0   1 ⎦                                          ⎠

In [6]: pprint(A.jordan_form())
⎛⎡ⅈ  0  -ⅈ  0 ⎤, ⎡2 - 4⋅ⅈ     1        0        0   ⎤⎞
⎜⎢            ⎥  ⎢                                  ⎥⎟
⎜⎢1  0  1   0 ⎥  ⎢   0     2 - 4⋅ⅈ     0        0   ⎥⎟
⎜⎢            ⎥  ⎢                                  ⎥⎟
⎜⎢0  ⅈ  0   -ⅈ⎥  ⎢   0        0     2 + 4⋅ⅈ     1   ⎥⎟
⎜⎢            ⎥  ⎢                                  ⎥⎟
⎝⎣0  1  0   1 ⎦  ⎣   0        0        0     2 + 4⋅ⅈ⎦⎠
```

**Comment by cbm755** [comment]
Thanks!  are you going to do a PR or shall I?

**Comment by jksuom** [comment]
It would suit me fine if you could do that. The comments would require some editing, at least to fix the typos. It seems that [this paragraph]( https://github.com/sympy/sympy/blob/master/sympy/matrices/matrices.py#L3646) could be removed altogether as the vectors added in the complex case are conjugates.
