### ISSUE TITLE
plot fails after new install

### ISSUE THREAD

**Issue by mulllhausen** [sympy/sympy#9277]
i installed sympy using `apt-get` and i get the following error when i try plot:

    $ uname -a
    Linux 3.2.0-4-686-pae #1 SMP Debian 3.2.65-1+deb7u2 i686 GNU/Linux
    $ ipython
    Python 2.7.3 (default, Mar 14 2014, 11:57:14) 
    Type "copyright", "credits" or "license" for more information.
    IPython 3.1.0 -- An enhanced Interactive Python.
    ?         -> Introduction and overview of IPython's features.
    %quickref -> Quick reference.
    help      -> Python's own help system.
    object?   -> Details about 'object', use 'object??' for extra details.
    In [1]: from sympy.plotting import plot
    In [2]: from sympy import symbols
    In [3]: x = symbols('x')
    In [4]: p1 = plot(x*x)
    ---------------------------------------------------------------------------
    TypeError                                 Traceback (most recent call last)
    <ipython-input-4-d1b042a6dc23> in <module>()
    ----> 1 p1 = plot(x*x)
    TypeError: 'module' object is not callable
    In [5]: import sympy
    In [6]: sympy.__version__
    Out[6]: '0.7.1.rc1'

**Comment by debugger22** [comment]
Can you try by opening IPython from other locations?

**Comment by mulllhausen** [comment]
i have tried from my home dir and from a project's subdir in there but the result is the same. is there anywhere else i should try?

**Comment by mulllhausen** [comment]
also note that the result is the same with the regular python shell (its not just an ipython thing).

**Comment by moorepants** [comment]
In SymPy 0.7.1.rc1, plot is a module, not a function. Just do `from sympy import Plot` to get the class or `from sympy.plotting.plot import Plot`.

**Comment by debugger22** [comment]
This seems to be a very old version of sympy. The API has changed.

**Comment by moorepants** [comment]
This version is from July 2011. It is certainly usable but you need to look at the docs for that version, as there have been API changes since then.

**Comment by moorepants** [comment]
Here are the correct docs: http://docs.sympy.org/0.7.1/modules/plotting.html

**Comment by mulllhausen** [comment]
ah right. maybe i'll just upgrade to the latest version.
