### ISSUE TITLE
slow Python REPL after plotting

### ISSUE THREAD

**Issue by rlabbe** [sympy/sympy#9280]
If I start Python or IPython from the command prompt and enter the following code I get a plot in Matplotlib as expected. After I close the plot the REPL is very sluggish - it cannot keep up with my typing. I can get 2-3 characters ahead of the display. I am running Python 3.4.3  and sympy 0.7.6 using the Anaconda distribution on Windows 8 and 7 (tested on two different systems). 

When I quit the session the message " QObject::killTimers: timers cannot be stopped from another thread" is printed by Python prior to returning to the shell. This message does not appear if I do not run a sympy plot.

    from sympy import symbols
    from sympy.plotting import plot
    x =symbols('x')
    plot(x+3)

**Comment by toolforger** [comment]
Am 11.04.2015 um 06:04 schrieb Roger Labbe:
> If I start Python or IPython from the command prompt and enter the
> following code I get a plot in Matplotlib as expected. After I close
> the plot the REPL is very sluggish [...]
>
> When I quit the session the message " QObject::killTimers: timers
> cannot be stopped from another thread" is printed by Python prior to
> returning to the shell. This message does not appear if I do not run
> a sympy plot.

That's a QT message.
SymPy does not call into QT directly, but maybe matplotlib does. Or one 
of the modules that matplotlib calls does, I don't know too much about 
matplotlib but I guess it needs access to windows to paint to.

To reproduce that behaviour, we'd like to know which version of 
matplotlib you use (and probably also which version of Qt is available 
to matplotlib if Qt was installed independently of matplotlib).

Do you have access to a non-Windows system on which you can test?
Knowing this will help further pinpoint the source of error.

Regards,
Jo

**Comment by rlabbe** [comment]
This is embarrassing, I should have investigated more. This is not just happening with SymPy, but with any matplotlib plot. I note that if I start the repl with 'ipython --gui=qt' everything runs great. I've changed my profile to set 

    c.InteractiveShellApp.gui = 'qt'

 I apologize for wasting people's time; I should have been able to figure this out myself, or at least not have blamed it on SymPy!

**Comment by toolforger** [comment]
Don't worry, we all misattribute things because we don't know better.
Now you know better, that's a positive result in the end :-)

And no, I didn't spend *that* much time.
Actually I just did what you did: Investigate until I hit an area that I didn't know enough about, then played that ball back into your field to investigate, which you did.
That's how we find out things despite every participant now knowing everything - all is well :-)
