### ISSUE TITLE
Truth values of comparisons

### ISSUE THREAD

**Issue by jksuom** [sympy/sympy#9286]
The truth values of some comparisons behave unexpectedly:
```
>>> s = Symbol('s', positive=True)
>>> s > 0
True
>>> s > 0 is True
False
```
An explanation could be that the truth value of  ``s > 0`` is  apparently ``BooleanTrue``.
I wonder if this is the intended behaviour.

**Comment by asmeurer** [comment]
It is. See https://github.com/sympy/sympy/blob/01400b0616f257ca7cfbba7b26a7b6305d1acb8d/sympy/logic/boolalg.py#L83 (we should move that into real documentation). Also look up the PR that made this change.

**Comment by toolforger** [comment]
Am 13.04.2015 um 20:16 schrieb Aaron Meurer:
> It is. See https://github.com/sympy/sympy/blob/01400b0616f257ca7cfbba7b26a7b6305d1acb8d/sympy/logic/boolalg.py#L83 (we should move that into real documentation).

I can do that. Just tell me which document to place that in.

**Comment by jksuom** [comment]
Thanks. That confirms my suspicion that [this test](https://github.com/sympy/sympy/blob/master/sympy/functions/special/tensor_functions.py#L158) would be useless.

**Comment by smichr** [comment]
> this test would be useless.

The test that `i > j is True` *could* be true if `i` and `j` are ints:

```
>>> (1>0) is True
True
>>> (S(1)>0) is True
False
>>> (1>S(0)) is True
False
```

Since this routine does not sympify input that means that the result will be different if one passed Integers instead of integers. The same fragility is present at

```
  sympy\geometry\polygon.py (2 hits)
	Line 854:             if (e1_angle < e2_angle) is True:
	Line 868:             elif (e1_angle > e2_angle) is True:
  sympy\integrals\rde.py (1 hits)
	Line 390:         if (n < 0) is True:
```

**Comment by jksuom** [comment]
>The test that i > j is True could be true if i and j are ints:

I saw that too, but it seemed that the arguments would already be sympified at an [earlier stage](https://github.com/sympy/sympy/blob/master/sympy/core/function.py#L190).
