### ISSUE TITLE
Update cache's printing style in FAQ

### ISSUE THREAD

**Issue by debugger22** [sympy/sympy#9300]
Perhaps, we should update this section with printing style of new cache.
https://github.com/sympy/sympy/wiki/Faq#how-do-i-clear-the-cache

**Comment by sagaragarwal94** [comment]
I am working on this issue :)

**Comment by sagaragarwal94** [comment]
Fixed it https://github.com/sympy/sympy/wiki/Faq#how-do-i-clear-the-cache .

**Comment by debugger22** [comment]
Thanks!
