### ISSUE TITLE
Inverse Laplace Transform raises TypeError

### ISSUE THREAD

**Issue by proy87** [sympy/sympy#9347]
Input: `ilaplace(1/(s**2+1)**2)`
Output: Invalid comparison of complex 2 - 2*I

Correct answer: 1/2*(sin(t)-t*cos(t))

**Comment by jksuom** [comment]
This is what I get with SymPy 0.7.6-git:
```
In [14]: inverse_laplace_transform(1/(s**2 + 1)**2, s, t)
Out[14]: 
(-t⋅cos(t) + sin(t))⋅Heaviside(t)
─────────────────────────────────
                2
```

**Comment by proy87** [comment]
Sorry, t should be positive.
t = symbols('t', positive=True)
s = symbols('s', positive=True)
inverse_laplace_transform(1/(s**2 + 1)**2, s, t)

**Comment by jksuom** [comment]
```
In [19]: t = Symbol('t', positive=True)

In [20]: inverse_laplace_transform(1/(s**2 + 1)**2, s, t)
Out[20]: 
  t⋅cos(t)   sin(t)
- ──────── + ──────
     2         2 
```

**Comment by proy87** [comment]
Weird. I have sympy 0.7.6 and got error.

**Comment by jksuom** [comment]
0.7.6 release version?

**Comment by proy87** [comment]
Don't know the difference. I instlled sympy 0.7.6 a couple of months ago.

**Comment by jksuom** [comment]
There has been a great number of improvements in the few months after the official release. Mine is the development version from the github repository. It would seem that the bug was fixed already.

**Comment by proy87** [comment]
Then, it seems that issue should be closed. How can I upgrade to the newest version?

**Comment by jksuom** [comment]
If you have git installed, then you can clone the repository. Else there seems to be available a zip-package, but I am not sure if it would be the latest version. You can find the repository via the 'Code' button in the upper right hand corner.

**Comment by proy87** [comment]
Thank you very much for your help.

**Comment by jksuom** [comment]
You are welcome.
