### ISSUE TITLE
Integration problem (the integral result should be 2)

### ISSUE THREAD

**Issue by beevageeva** [sympy/sympy#9355]
from sympy import oo,Symbol, integrate
x = Symbol('x')
print(integrate((x\*\*2+1)**(-3/2),(x, -oo,oo)))

**Comment by jksuom** [comment]
It appears that the exponent is mangled by the python interpreter. You could write e.g. ``-S(3)/2``.
```
In [21]: integrate((x**2 + 1)**(-S(3)/2), (x, -oo, oo))
Out[21]: 2
```

**Comment by jksuom** [comment]
See (http://docs.sympy.org/latest/gotchas.html#python-numbers-vs-sympy-numbers)
