### ISSUE TITLE
Deprecation of C in sympy.deprecated.class_registry

### ISSUE THREAD

**Issue by toolforger** [sympy/sympy#9371]
Removal is currently scheduled for the release after 0.7.8.
Removal involves touching multiple files; see the comments in `sympy/deprecated/class_registry.py` for details.

**Comment by jcrist** [comment]
For more information see #7124 and the implementing PR #9348.

**Comment by huangzhaor** [comment]
I made a mistake in the integral operation.
p = float(integrate(f(x),(x,lb,ub)))

F:\ANACONDA\lib\site-packages\sympy\deprecated\class_registry.py:38: SymPyDeprecationWarning: 
C, including its class ClassRegistry, has been deprecated since SymPy
1.0. It will be last supported in SymPy version 1.0. Use direct
imports from the defining module instead. See
https://github.com/sympy/sympy/issues/9371 for more info.
  deprecated_since_version='1.0').warn(stacklevel=2)

After reading this page, I still didn't get an alternative. I just know that the ClassRegistry has been removed. I want to know what changes need to be made to the code now.

**Comment by toolforger** [comment]
The problem is that some code is importing class_registry.py.
Can you produce a stack trace that shows what led to that import?

**Comment by oscarbenjamin** [comment]
Perhaps if you run the code like `python -Werror myscript.py` then you can see a stack trace.

**Comment by HongruiDuan** [comment]
After reading this page, i still don't know how to solve this bug? Could someone  provide some suggesstions?

**Comment by oscarbenjamin** [comment]
We can just remove the class registry now as it has been deprecated for a long time.

**Comment by toolforger** [comment]
This could have been done with the next release after 0.7.8, but I wasn't around to do it at that time.
Feel free to follow through with the scheduled update; `sympy/deprecated/class_registry.py` should have all the details (and if it doesn't anymore, take a look at the status as of 0.7.8).

**Comment by toolforger** [comment]
You can ignore the comments by huangzor, they're from the client side and shouldn't affect what should be done in SymPy.

**Comment by Honigmelone** [comment]
I saw a similar error to @huangzhaor with only running `sympy.init_session()`.
I have opened a new issue for it. Since it only occurs in an IPython console, `-Werror` did not work for me.

**Comment by oscarbenjamin** [comment]
They are the same issue really. We can just delete `sympy/deprecated/class_registry.py` and I think that will fix it.

**Comment by oscarbenjamin** [comment]
I'm marking this as easy to fix.

**Comment by 0sidharth** [comment]
Should the directory `sympy/deprecated` be removed completely, as the only thing it contains is the deprecated `class_registry`, or only those parts of the files which mention `class_registry`?

**Comment by oscarbenjamin** [comment]
The whole directory should be removed

**Comment by NooooBuG** [comment]
> After reading this page, i still don't know how to solve this bug? Could someone provide some suggesstions?

please check your python version.  SymPy officially supports Python 3.5, 3.6, 3.7, and PyPy.
https://docs.sympy.org/latest/install.html#id1:~:text=The%20SymPy%20CAS%20can%20be%20installed,Python%203.5%2C%203.6%2C%203.7%2C%20and%20PyPy.

**Comment by NooooBuG** [comment]
> After reading this page, i still don't know how to solve this bug? Could someone provide some suggesstions?

please check your python version. SymPy officially supports Python 3.5, 3.6, 3.7, and PyPy.
When I change my python version from 3.8 to 3.7,it works!
https://docs.sympy.org/latest/install.html#id1:~:text=The%20SymPy%20CAS%20can%20be%20installed,Python%203.5%2C%203.6%2C%203.7%2C%20and%20PyPy.

**Comment by oscarbenjamin** [comment]
That doc needs to be updated. The latest release of sympy supports Python 3.6 through to 3.9.

**Comment by oscarbenjamin** [comment]
https://github.com/sympy/sympy/wiki/Release-Notes-for-1.7.1

**Comment by Ahek** [comment]
> Should the directory sympy/deprecated be removed completely, as the only thing it contains is the deprecated class_registry, or only those parts of the files which mention class_registry?

> The whole directory should be removed

I had the same problem. So I removed the whole directory and updated SymPy. However right now I get the following error in Spyder when using sympy:

`ModuleNotFoundError: No module named 'sympy.deprecated.class_registry'`

Should I delete and reinstall SymPy? Or is there another solution?

**Comment by oscarbenjamin** [comment]
This issue has been fixed on master so you could install sympy from github master. Otherwise a new release will be out soon with the fix. You can see the changes that were needed here:
https://github.com/sympy/sympy/pull/20896/files
