### ISSUE TITLE
Max/Min with nan arg should be nan

### ISSUE THREAD

**Issue by abloomston** [sympy/sympy#9385]
Currently, the following:

   Max(S.NaN, 4)
   Max(S.NaN, x)
   Min(S.NaN, 4)
   Min(S.NaN, x)

All raise a `TypeError` for `Invalid NaN comparison`. I believe Max/Min called with any argument being S.NaN should evaluate to S.NaN, including +/- oo args.

**Comment by cbm755** [comment]
I tend to agree with you.  But I think the consensus/decision was SymPy nan is not like floating point nan.  max/min imply ordering of the arguments and nan cannot be ordered: hence the exception.

So I thnik it is the desired behavior, even if unintuitive for anyone used to numerical computing.

**Comment by abloomston** [comment]
Hey @cbm755 - just to be clear, you're saying you agree with nan taking precedence over +/- oo for the evaluation of Max/Min, right (i.e. how I implemented it in the fix)? I just want to make sure I understand whether you want me to change the way it is currently implemented.

**Comment by toolforger** [comment]
> But I think the consensus/decision was SymPy nan is not like floating point nan.

Sort of.
It's almost the same, in that it's a stand-in value for computations 
where any numberic result would be wrong, and we don't want to throw an 
exception. Like IEEE, it forces us into ugly warts like declaring that 
`nan != nan`.
It's different in that for cases like `sqrt(-1)`, IEEE cannot compute a 
result but we can because we have complex numbers.

**Comment by cbm755** [comment]
@abloomston I'm saying this is not a bug :(

(I think *I personally* would like `min(nan, 10)` to return nan but I think the decision of the community is that raising an exception is the desired behaviour.)

Let me see if I can find a reference for our discussions on this...

**Comment by cbm755** [comment]
I guess see #7834 and references therein.   Also, discussions in #7773 and #7776.  As you can see, its some what contentious.

1.  The guiding principle I've been following is: "False should not be a stand-in for does-not-make-sense".

2. In particular, #7834 added this to the docstring for `S.NaN`:
````
NaN is not comparable so inequalities raise a TypeError.  This is in
constrast with floating point nan where all inequalities are false.
````

Sorry I wasn't clear earlier.  Happy to revisit if you think I've missed the point of your bug and patch.

**Comment by abloomston** [comment]
@cbm755, thanks for taking the time to dig up the relevant references. I'll close my pull request and keep this in mind when I use sympy in my code.

**Comment by cbm755** [comment]
> keep this in mind when I use sympy in my code.

+1 to that!  As a numerical analyst, its very counterintuitive (even though I understand the reasoning).

Hope you don't feel your time was wasted: the help if much appreciated.
