### ISSUE TITLE
simplify(expand((x - 1j) ** 3)) with un-simple output

### ISSUE THREAD

**Issue by elvis-sik** [sympy/sympy#9390]
I have executed the line in the title after a init_session()
The output I am getting is the following (I haven't pasted the line with the exponents):     
x  - -3.0⋅(-1)⋅ⅈ⋅x  - -3.0⋅(-1)⋅x + 1.0⋅ⅈ
I don't know if this is expected behavior, but it seems to me "- - 3.0 * (-1)" should be "-3.0"
Thanks.

**Comment by toolforger** [comment]
I'm getting this:

```
$ bin/isympy 
Python console for SymPy 0.7.6-git (Python 2.6.9-64-bit) (ground types: python)

These commands were executed:
>>> from __future__ import division
>>> from sympy import *
>>> x, y, z, t = symbols('x y z t')
>>> k, m, n = symbols('k m n', integer=True)
>>> f, g, h = symbols('f g h', cls=Function)
>>> init_printing()

Documentation can be found at http://docs.sympy.org/dev

>>> simplify(expand((x - 1j) ** 3))
 3          2                
x  - 3.0⋅ⅈ⋅x  - 3.0⋅x + 1.0⋅ⅈ
>>> 
```

I.e. I'm getting no double minus, but it's generally not eliminating double minus signs.
That's on current master.

Can you post a transcript of a full session, so that we can see whether we can reproduce this behaviour?

**Comment by elvis-sik** [comment]
Hm, maybe it's the version, I am using latest stable (0.7.6), with Python 3.4.3.

>In [1]: from sympy import init_session
>In [2]: init_session()
>IPython console for SymPy 0.7.6 (Python 3.4.3-64-bit) (ground types: python)
>These commands were executed:
>[...]
>In [3]: simplify(expand((x-1j)**3))
>Out[3]: 
> 3                2                      
>x  - -3.0⋅(-1)⋅ⅈ⋅x  - -3.0⋅(-1)⋅x + 1.0⋅ⅈ

**Comment by cbm755** [comment]
I can confirm on 0.7.6.  But I agree the pretty printer does seem fixed in git master...

If you'd like to learn how to use `git bisect`, we could figure out what change fixed it?  And possibly add a test.

Otherwise, close I suppose.

**Comment by elvis-sik** [comment]
Glad it was fixed.

**Comment by dengsauve** [comment]
@elvis-sik routed here from codetriage. Glad to help in any way, but could you close this issue if it has been resolved? Thanks.
