### ISSUE TITLE
sympygamma.com directs to code.google.com to report an issue

### ISSUE THREAD

**Issue by 10110111** [sympy/sympy#9408]
When I come across a problem with sympygamma.com, it says
Oops!
Looks like we've had a problem...Please report the issue to us so we can fix it!

And "report the issue" links to https://code.google.com/p/sympy/issues/list . Then when I try to create an issue, the text boxes are filled with information that issue tracker has moved to github, and one has to manually navigate here.

**Comment by debugger22** [comment]
Thanks for reporting! Fixed it [here](https://github.com/sympy/sympy_gamma/pull/62).
