### ISSUE TITLE
Q.infinity is now deprecated

### ISSUE THREAD

**Issue by debugger22** [sympy/sympy#9426]
`Q.infinity` has been deprecated. Use `Q.infinite` instead.

This is the `Deprecation Removal` issue for the same.

See https://github.com/sympy/sympy/pull/9228

**Comment by mvnnn** [comment]
this issue is open ? i want to work on this.

**Comment by asmeurer** [comment]
@mvnnn "Deprecation Removal" issues do not have anything do to. They are just here to inform people who use the deprecated behavior (if you run `Q.infinity` you will get a message leading you here). See https://github.com/sympy/sympy/wiki/Deprecating-policy.
