### ISSUE TITLE
sets.Complement fails on certain Unions

### ISSUE THREAD

**Issue by siefkenj** [sympy/sympy#9447]
`sympy.sets.Complement` fails on certain unions.  That is, it seems to get stuck in a loop.

To recreate

    from sympy import S
    from sympy.sets import *
    
    a = Interval(0,1) + Interval(2,3)
    # this works
    Complement( S.Reals, a )
    # this gets stuck in a loop
    Complement( S.UniversalSet, a)

The expected behaviour is for it to output `UniversalSet() \ ([0,1] U [2,3])`

**Comment by kshitij10496** [comment]
I would like to work on this.
Any suggestions @gxyd @aktech

**Comment by kshitij10496** [comment]
```
[ ]: Complement(S.UniversalSet, a, evaluate=False)
[ ]: UniversalSet() \ ([0, 1] ∪ [2, 3])
```
By setting the `evaluate` keyword to `False`, we get the expected output.

**Comment by kshitij10496** [comment]
Moreover, this complement is failing with Natural Set too.

```python
In [ ]: Complement(S.Naturals, a, evaluate=False) # hangs
```
