### ISSUE TITLE
solve() does not give all solutions to a polynomial equation.

### ISSUE THREAD

**Issue by KiWSong** [sympy/sympy#9465]
`x = var('x')`
`g = x**4 + 2*x**3+3*x**2+x+2.`
`solve(g)`

gives only two complex solutions, but I know (using the argument principle and Maple) that there are two more complex solutions.
EDIT: I'm on mac 10.6.8. Python 2.7.6.

**Comment by gxyd** [comment]
If could please paste the output.
I get this on my machine
```
>>> g = x**4 + 2*x**3+3*x**2+x+2
>>> a = solve(g)
>>> len(a)
4
>>> [ i.evalf() for i in a ]
[−1.10972344598875+1.23765287406497i,0.109723445988746+0.843647274929224i,−1.10972344598875−1.23765287406497i,0.109723445988746−0.843647274929224i]
```
So one in each of the four quadrants.

**Comment by KiWSong** [comment]
>In [9]: `x = var('x')`
>In [10]: `g = x**4 + 2*x**3+3*x**2+x+2`
>In [11]: `a=solve(g)`
>In [12]: `len(a)`
>Out[12]: `2`
>In [13]: `[i.evalf() for i in a]`
>Out[13]: 
>`[0.109723445988746 + 0.843647274929224*I,
> 0.109723445988746 - 0.843647274929224*I]`

**Comment by AndrewUshakov** [comment]
I would like to confirm error with 64-bit Windows version of Python 3.4.3

**Comment by baskerville** [comment]
Works fine with the Git version.

**Comment by KiWSong** [comment]
How do you get the "git" version?

**Comment by KiWSong** [comment]
I followed the instructions here

https://github.com/sympy/sympy

but I am not getting the "git" at the end of the version....

**Comment by moorepants** [comment]
The "git" version is the development version. You can install this in multiple ways. One way is to simply download the zip file from https://github.com/sympy/sympy, unzip the file, and from within the sympy directory type `python setup.py install`. Note that the development version does not guarantee a stable API.

**Comment by Shekharrajak** [comment]
This should be closed , right ?.

**Comment by hargup** [comment]
> This should be closed , right ?

Yes.
