### ISSUE TITLE
log(100, 10, evaluate=False).evalf() != 2

### ISSUE THREAD

**Issue by mcho421** [sympy/sympy#9469]
```
>>> log(100, 10, evaluate=False).evalf()
4.60517018598809
```

This should be 2. It works if you don't add evaluate=False, so it might be related to that.

I'm using SymPy 3766b9ca505bb3645e81912b3cc883df73c7a32b

**Comment by jksuom** [comment]
``evalf_log`` appears to ignore the base of a logarithm. It only looks at the [first argument] (https://github.com/sympy/sympy/blob/master/sympy/core/evalf.py#L770).

**Comment by wanglongqi** [comment]
So the correct way to fix this one should be evaluate the log first, then apply the `evalf` function? or using property of logarithmic function to calculate it in the function? I think both of them are easy to fix.
