### ISSUE TITLE
Fix dependency timeouts in Travis by caching

### ISSUE THREAD

**Issue by toolforger** [sympy/sympy#9470]
We're seeing various test failures due to timeouts when downloading dependencies, mostly for mpmath from mpmath.org.
Should we try and enable pip caching? This will persist ~/.cache/pip, with the intention that the next test will download that directory from Amazon S3 instead of a multitude of project websites that may or may not be up.
http://docs.travis-ci.com/user/caching/ describes some caveats, I don't know much they're an issue for us.

**Comment by moorepants** [comment]
Yes, please enable this if you can. I think it will be helpful.

Another alternative is to figure out how to switch to conda for testing (which I think is the long term plan).

**Comment by toolforger** [comment]
I haven't seen a consensus on what the long-term plan for testing is.
There is some drive towards returning to a standard testing framework, but there were also counterarguments (not all of them with a satisfactory answer right now - ironically, the relatively unstable dependency downloads in the Python ecosystem are a strong argument *against* adding external dependencies).

**Comment by toolforger** [comment]
Anyway... anybody got a good idea how to test that a failing download is properly cached?
It need not be an automated test, but I'd want to see at least once that it works as advertised.

**Comment by oscarbenjamin** [comment]
Similar issues sometimes occur now in Travis but I think this issue refers to something that doesn't apply any more. Closing.
