### ISSUE TITLE
Wrong limit with log and constant in exponent

### ISSUE THREAD

**Issue by pcworld** [sympy/sympy#9471]
`limit((((27**(log(n,3))))/n**3),n,oo)` returns 1, as do [Wolfram Alpha](http://www.wolframalpha.com/input/?i=lim+n-%3Einfty+%28%28%2827%5E%28log_3%28n%29%29%29%29%2Fn%5E3%29) and Maple.
However when increasing the first exponent by 1:
`limit((((27**(log(n,3)+1)))/n**3),n,oo)` SymPy returns infinity. Both [Wolfram Alpha](http://www.wolframalpha.com/input/?i=lim+n-%3Einfty+%28%28%2827%5E%28log_3%28n%29%2B1%29%29%29%2Fn%5E3%29) and Maple return 27.

**Comment by mickyaero** [comment]
I would like to work on this bug

**Comment by oscarbenjamin** [comment]
SymPy now returns 27 as well:
```
In [7]: limit((((27**(log(n,3))))/n**3),n,oo)                                                                                                  
Out[7]: 1

In [8]: limit((((27**(log(n,3)+1)))/n**3),n,oo)                                                                                                
Out[8]: 27
```

**Comment by smichr** [comment]
a test can be added

**Comment by Anjali167-sopho** [comment]
If no one is working on this issue and the issue is still open. Can I start working on it?
Also, it would be great, if anyone could guide me as to where to start from

**Comment by oscarbenjamin** [comment]
This just needs a test to be added. Do you know how to run the tests?

For this issue the test should go somewhere in `sympy/series/tests`.
