### ISSUE TITLE
Q.hermitian/Q.antihermitian do not work with matrices

### ISSUE THREAD

**Issue by debugger22** [sympy/sympy#9478]
```
In [2]: A = Matrix([[I, 1 + I, 2*I], [-1 + I, 5*I, 3], [2*I, -3, 0]])

In [3]: B = Matrix([[1, -I], [I, 1]])

In [4]: ask(Q.hermitian(B))  # Should be True

In [4]: ask(Q.antihermitian(A))  # Should be True

In [7]: A.is_hermitian
Out[7]: False

In [8]: B.is_hermitian
Out[8]: True
```

**Comment by debugger22** [comment]
Well, `Matrix.is_hermitian` is a property and has nothing to do with the old assumptions.

**Comment by AnishShah** [comment]
Hi, I'm working on this..

**Comment by debugger22** [comment]
There were some discussions on removing hermitian/antihermitian from assumptions. You should first read them before proceeding.

**Comment by AnishShah** [comment]
@debugger22 Thank you for telling. I search on Google Group, but could not find any discussion. Do you have any link?

**Comment by asmeurer** [comment]
I don't recall those discussions, but they were probably on a GitHub issue or pull request.

**Comment by AnishShah** [comment]
@asmeurer I searched issues & PRs with "hermitian" but could find only 3 -> #1158 #1606 #6250
There's not much about removing hermitian/anti-hermitian from assumptions.
Should I work on this issue?

**Comment by asmeurer** [comment]
I'd say yes. I can't think of why we would want to remove them.

**Comment by AnishShah** [comment]
Okay, Thanks. I will send a PR..

**Comment by debugger22** [comment]
This is what I was talking about. 

https://gitter.im/sympy/sympy?at=55917d37666fd9af67369fcc

**Comment by asmeurer** [comment]
Ah, I remember now. So the issue is that hermitian includes real numbers, instead of just applying to matrices and operators. I think this issue is still valid, though, even if we decide to change that later.

**Comment by debugger22** [comment]
+1

**Comment by AnishShah** [comment]
Should I do it for matrices?

**Comment by asmeurer** [comment]
Yeah

**Comment by AnishShah** [comment]
Hi @asmeurer @debugger22, after reading the source code, I got familiar with all the workflow of the new assumptions. 

Currently, `AskHermitianHandler/AskAntiHermitianHandler` are under `sets.py`, since we are adding Matrices to it, should it still under `sets.py`?

**Comment by AnishShah** [comment]
Or should I add a new handler specifically for matrices?
