### ISSUE TITLE
Matrix.rank() incorrect results

### ISSUE THREAD

**Issue by siefkenj** [sympy/sympy#9480]
There is an error in the Matrix.rank() function.  It also appears to be in Matrix.rref().

    m = Matrix([[-5 + 5*sqrt(2), -5], [-5*sqrt(2)/2 + 5, -5*sqrt(2)/2]])
    print("shape:", m.shape)
    print("det:", m.det())
    print("rank:", m.rank())

outputs

    shape: (2, 2)
    det: 0
    rank: 2

but should output

    shape: (2, 2)
    det: 0
    rank: 1

Doing `m.rank(simplify=True)` gives the correct result, but if `simplify=True` is needed, `m.rank()` should at least throw some kind of warning to indicate that it might have computed the result incorrectly...

**Comment by toolforger** [comment]
Was that limited to just PyPy, or does this happen with standard CPython as well?

**Comment by siefkenj** [comment]
This happens in pypy and all versions of cpython, AFAIK.  I've tested on pypy 2.5, python 3.4, and python 2.7.5.

**Comment by toolforger** [comment]
Good to know, thanks.
I can't fix it because I didn't write it and because I know far too little about matrices; can you look in `git annotate` who was last working on this? We can then ping that person (or persons), that should speed up the fixing process.

**Comment by siefkenj** [comment]
I'm sorry, I'm not that experienced with `git`. What exactly do you mean?

**Comment by siefkenj** [comment]
Looking at the `Matrix.rref` code, I see

    if iszerofunc(r[pivot, i]):

and if this fails, the code acts like it isn't zero.  However, `x.is_zero` returns `True/False/None`; `None` is returned when it cannot decide if the object is non-zero, and this is treated by the code as the object being non-zero even though its zero value cannot be determined...Doing this right might have some consequences though...For instance, the example that is included in the documentation `Matrix([[1, 2], [x, 1 - 1/x]]).rref()` should only be the identity matrix provided some assumptions on `x` (e.g., it is real and non-zero).

**Comment by toolforger** [comment]
> I'm sorry, I'm not that experienced with `git`. What exactly do you mean?

If you have a local clone of the repository, you can do `git annotate 
name/of/file.py` and you'll see what lines of the file were last changed 
by whom, in what commit.
Or you can go to e.g. 
https://github.com/sympy/sympy/blob/master/sympy/matrices/matrices.py 
and click on the "Blame" button on the right side above the file's text. 
That's particularly nifty because you can click on the commits directly 
and see the commit's comment and discussion.

**Comment by siefkenj** [comment]
Looks like @smichr was most recently involved.

**Comment by hargup** [comment]
@siefkenj Thanks for digging this up, adding a warning should be easy and you are welcome to make a PR.

> Looking at the `Matrix.rref` code, I see
> 
>     if iszerofunc(r[pivot, i]):
> 
> and if this fails, the code acts like it isn't zero.  However, `x.is_zero`
> returns `True/False/None`; `None` is returned when it cannot decide if the
> object is non-zero, and this is treated by the code as the object being non-zero
> even though its zero value cannot be determined...Doing this right might have
> some consequences though...For instance, the example that is included in the
> documentation `Matrix([[1, 2], [x, 1 - 1/x]]).rref()` should only be the
> identity matrix provided some assumptions on `x` (e.g., it is real and
> non-zero).

If the value of `is_zero` is `None` then we should raise an error, maybe a `NotImplementedError` saying `cannot determine zero value for %s`, then prompting the user to try again with `simplify=True` option. This too should be easy to fix.

**Comment by siefkenj** [comment]
Doing this will presumably break several of the examples and unit tests.  Should they be changed accordingly?

**Comment by toolforger** [comment]
> Doing this will presumably break several of the examples and unit tests.  Should they be changed accordingly?

We should probably look which of these tests describe functionality that 
we ultimately want to have, and mark them as `@XFAIL`.
Of course we should fix tests that assume results that we do not want to 
have, too.

**Comment by jgrochow** [comment]
Just as a note, this issue also comes up with matrices with polynomial entries, and I haven't found an example where simplify=True doesn't fix the problem...

**Comment by asmeurer** [comment]
> If the value of is_zero is None then we should raise an error, maybe a NotImplementedError saying cannot determine zero value for %s, then prompting the user to try again with simplify=True option. This too should be easy to fix.

The problem is that it shouldn't raise an error if `simplify=True` is already given, and there's no way for `iszerofunc` to know what the value of that option is.

**Comment by tyagi221295** [comment]
@asmeurer when the rank function is being called cant be check if the  is_zero value if it turns out to be none then we could simply assign simplify=True instead of false that is default value

**Comment by tyagi-prashant** [comment]
if a waring is add for simplify = True when rank function is called without it, the warning will also shown when the matrix is already simplify. I think it is not right to add a waring.

**Comment by ashutoshsaboo** [comment]
I want to work on this issue, and try resolving this! Is this solved? Can I try solving this?

**Comment by rpisarev** [comment]
PQ #10650 was updated to currenr master

**Comment by BrickMoon** [comment]
As has been said already, this is definitely related to the is_zero function returning None. Calling is_zero on this expression in particular returns None when it should return True:

expr = -5*sqrt(2)/2 + 5*(-5*sqrt(2)/2 + 5)/(-5 + 5*sqrt(2))

Is this correct behavior for sympy.core.add.Add? Is there a good reason why is_zero can't be determined for this expression? Seems weird to me that something this fundamental wouldn't be working correctly.

**Comment by siefkenj** [comment]
I think `.is_zero` is supposed to have low computational overhead.  It returns `None` if it cannot decide without doing computations.  I suspect the root of the problem is someone not thinking of this somewhere in the code.  One should never write `if not x.is_zero:` for example, because that is different than `if x.is_zero == False:`

**Comment by siefkenj** [comment]
Resolved by PR #11554
