### ISSUE TITLE
oo**zoo

### ISSUE THREAD

**Issue by proy87** [sympy/sympy#9491]
oo**zoo give recursion error.

**Comment by debugger22** [comment]
I do not get this error in the current master.

```
In [1]: from sympy import *

In [2]: oo*zoo
Out[2]: zoo
```

**Comment by jksuom** [comment]
``Infinity._eval_power`` should probably test for exponent ``zoo`` and perhaps return ``nan``.

**Comment by debugger22** [comment]
Damnit. I didn't see `**`.  :(
