### ISSUE TITLE
Solveset returns solution where denom is Zero.

### ISSUE THREAD

**Issue by aktech** [sympy/sympy#9522]
`solveset` returns a solution where denominator is zero for the original given equation. 

```python
In [9]: expr = Eq(1/(x**2 - 4) + x, 1/(x**2 - 4) + 2)

In [10]: expr
Out[10]: 
      1            1   
x + ────── = 2 + ──────
     2            2    
    x  - 4       x  - 4

In [11]: solveset(expr, x)
Out[11]: {2}

```

Or perhaps a more general case:
```python
In [5]: solveset(Eq(1/x + x, 1/x), x)
Out[5]: {0}
```

**Comment by Sumith1896** [comment]
Verifying all the resulting solutions doesn't seem to be an option, does it?

**Comment by Sumith1896** [comment]
Reducing the domain from `R` (real numbers) to that of the equation can be done, thoughts?

**Comment by aktech** [comment]
> Verifying all the resulting solutions doesn't seem to be an option, does it?

Yes, it is a long term solution, but eventually, `solveset` doesn't have a `checksol` implemented as of yet.

> Reducing the domain from R (real numbers) to that of the equation can be done, thoughts?

Finding the domain of a function is itself a hard problem, though `singularities` module is a good candidate for such improvements, but it's in the initial phase of development, as it can't handle a lot of expressions.

**Comment by aktech** [comment]
The following diff is a workaround, which fixes this:

```diff
--- a/sympy/solvers/solveset.py
+++ b/sympy/solvers/solveset.py
@@ -855,7 +855,8 @@ def solveset(f, symbol=None):
     f = sympify(f)
 
     if isinstance(f, Eq):
-        f = f.lhs - f.rhs
+        from sympy.core import Add
+        f = Add(f.lhs, - f.rhs, evaluate=False)
 
     if f.is_Relational:
         if real is False:
```

Maybe I should open a PR, to discuss this solution.
