### ISSUE TITLE
solveset(sinh(x)) doesn't returns all solutions

### ISSUE THREAD

**Issue by aktech** [sympy/sympy#9531]
``` python
In [2]: solveset(sinh(x))
Out[2]: {0}
```

**Comment by hargup** [comment]
`{0}` is the only solution if you solving the equation in the real domain. What are the other solutions in the complex domain? btw rewriting `sinh(x)` in terms of `exp` and then solving gives the following result:

```python
In [6]: solveset(exp(x)/2 - exp(-x)/2, x)
Out[6]: ImageSet(Lambda(_n, nan), Integers()) U ImageSet(Lambda(_n, _n*I*pi), Integers())
```

**Comment by aktech** [comment]
Basically I meant the following:
```
In [8]: x = Symbol('x', real=False)

In [9]: solveset(sinh(x))
Out[9]: {0}
```

In complex domain it should be `{n⋅ⅈ⋅π | n ∊ ℤ}`   Which is Equivalent to:
`ImageSet(Lambda(_n, _n*I*pi), Integers())`
