### ISSUE TITLE
diophantine() doesn't let you specify the variable order

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#9538]
`diophantine` gives a tuple of solutions, but it doesn't let you specify the variable order (it orders them alphabetically, I think). It should either require you to specify an order or return a dictionary. 

@thilinarmtb

**Comment by Gadal** [comment]
Straightforward enough to fix.  Changing it won't be compatible with code that uses older versions of sympy though.  Does anyone generally bother with backward compatibility?

**Comment by asmeurer** [comment]
We do try to maintain backwards compatibility, and do deprecations when things need to break. I think it's possible to do a deprecation here.

**Comment by asmeurer** [comment]
See https://github.com/sympy/sympy/blob/master/sympy/utilities/exceptions.py

**Comment by Gadal** [comment]
Ah, good to know.

**Comment by smichr** [comment]
What's the best way to 

> or return a dictionary

Would you return a set of dictionaries (actually Dict instances b/c dict cannot be contained in a set) in the cases where a set is returned?

To maintain backward compatibility, could we do the following?
* no symbols arg = ordered free symbols (default? or should a backward compatibility kw be required to get this, like ordered=True?)
* symbols -> symbols in the order given *and only for the symbols given?* btw is list(set(foo)) invariant on a given system
* dict=True -> instance of dict or set of Dicts
