### ISSUE TITLE
diophantine(6*k + 9*n + 20*m - x) gives TypeError: unsupported operand type(s) for *: 'NoneType' and 'Symbol'

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#9539]
```
In [15]: diophantine(6*k + 9*n + 20*m - x)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-15-234fff11d03b> in <module>()
----> 1 diophantine(6*k + 9*n + 20*m - x)

/Users/aaronmeurer/Documents/python/sympy/sympy/sympy/solvers/diophantine.py in diophantine(eq, param)
     85
     86         var_t, jnk, eq_type = classify_diop(base)
---> 87         solution = diop_solve(base, param)
     88
     89         if eq_type in ["linear", "homogeneous_ternary_quadratic", "general_pythagorean"]:

/Users/aaronmeurer/Documents/python/sympy/sympy/sympy/solvers/diophantine.py in diop_solve(eq, param)
    173
    174     if eq_type == "linear":
--> 175         return _diop_linear(var, coeff, param)
    176
    177     elif eq_type == "binary_quadratic":

/Users/aaronmeurer/Documents/python/sympy/sympy/sympy/solvers/diophantine.py in _diop_linear(var, coeff, param)
    402         for v in var[2:]:
    403             sol_x, sol_y  = base_solution_linear(-coeff[v], a, b)
--> 404             X.append(sol_x*v)
    405             Y.append(sol_y*v)
```

If I reorder the variables it works.

```

In [14]: diophantine(6*n + 9*m + 20*k - x)
Out[14]: set([(24⋅n - 9⋅t - 4⋅x, -54⋅n + 20⋅t + 9⋅x, n, x)])

```

All variables are set as `integer=True`.

**Comment by asmeurer** [comment]
@thilinarmtb

**Comment by Gadal** [comment]
Fixed the issue.  If the coefficients of the first (lexicographically) two parameters had a gcd that didn't divide the coefficients of any of the other parameters, you'd get an incorrect answer (which was hidden by an error caused by multiplying a None).

New method returns different correct solutions from the original.  Not sure if that's a problem (?).

**Comment by asmeurer** [comment]
Is there a pull request?

**Comment by Gadal** [comment]
https://github.com/sympy/sympy/pull/9681/files

**Comment by jksuom** [comment]
> New method returns different correct solutions from the original. Not sure if that's a problem (?).

There are many possible forms of solutions. 
All complete solutions are related by different choices of parameters. Then there are also incomplete solutions.
For example, the current code gives
```
>>> diophantine(3*x + 5*y + 7*z)
set([(5*t - 14*z, -3*t + 7*z, z)])
```
which is one form of a complete solution.
The result of the code in 9861 is
```
>>> diophantine(3*x + 5*y + 7*z)
set([(0, 7*t, -5*t)])
```
which gives only a part of the solutions.

**Comment by Gadal** [comment]
Each variable is paramaterised now.

>>> diop_solve(3*x + 5*y + 7*z)
(t, -9*t, 6*t)

**Comment by jksuom** [comment]
Two parameters are needed for a complete solution of an equation with three variables.

**Comment by Gadal** [comment]
Only if the three variables are mutually linearly independent.

In any case, the original function introduced at most one.  Do we want to generate all possible parameters?

**Comment by jksuom** [comment]
I believe that a complete solution is expected. In many cases some of the variables can also act as parameters. That is what happens with the current code.

**Comment by Gadal** [comment]
Yeah, fair enough.  I expect the fix for multiple parameters is relatively straightforward.  I'll add it in the morning.

//TODO: sleep

**Comment by Gadal** [comment]
@asmeurer 
The Travis Cl build seems to be failing on tests in the test suite (tests_diophantine.py) that I thought I'd replaced.  Any idea why that's happening?

https://github.com/sympy/sympy/pull/9681

**Comment by Gadal** [comment]
@asmeurer #9681 is passing now.

**Comment by smichr** [comment]
With modifications of #10997, this now gives:

```python
>>> diophantine(6*k + 9*n + 20*m - x)
set([(t_0, t_1, t_1 + t_2, 6*t_0 + 29*t_1 + 9*t_2)])
```

**Comment by smichr** [comment]
Actually, that is already obtained in master w/o the PR's modifications.
