### ISSUE TITLE
ImageSet.is_subset(S.Reals) returns False

### ISSUE THREAD

**Issue by aktech** [sympy/sympy#9543]
``` python
In [54]: x = Symbol('x', real=True)

In [55]: N = S.Naturals

In [56]: squares = ImageSet(Lambda(x, x**2), N) # {x**2 for x in N}

In [58]: squares.is_subset(S.Reals)
Out[58]: False
```

**Comment by shivamT95** [comment]
After some experimenting i observed that the issue is arising because the following is false
In [31]: st = ImageSet(Lambda(x,x),S.Naturals)

In [32]: st == S.Naturals
Out[32]: False

**Comment by aktech** [comment]
Why do you think the following should be `True`?

```
In [32]: st == S.Naturals
Out[32]: False
```

**Comment by shivamT95** [comment]
set of all Natural Numbers is {x for x in N} . I tried 
In [33]: S.Reals.intersect(squares)
Out[33]: 
⎧ 2                            ⎫
⎨x  | x ∊ {1, 2, …, ∞}⎬
⎩                               ⎭

In [34]: squares
Out[34]: 
⎧ 2            ⎫   
⎨x  | x ∊ ℕ⎬
⎩               ⎭

In [30]: squares == S.Reals.intersect(squares)
Out[30]: False

**Comment by aktech** [comment]
> set of all Natural Numbers is mathematically {x for x in N}

Yeah, it is. But `st` & `S.Naturals` are instances of different classes.
Though you are right, we need to establish their equivalence in some way.

**Comment by shivamT95** [comment]
yeah is_subset compares the interesection of S.Reals with squares returns a set whose range is an ImageSet {x for x in N} . But squares have S.Naturals as their range hence we are getting the output as False . So we need to establish their equivalence in some way. 
I am thinking maybe writing a separate function for equality when S.Naturals ,S.Reals and S.Integers is involved

**Comment by aktech** [comment]
> I am thinking maybe writing a separate function for equality when S.Naturals ,S.Reals and S.Integers is involved

That may work, but I am not sure how far it would go.

**Comment by gxyd** [comment]
In that case we have a lot of possibilities to handle, I do not think that would work. 
Consider
```
>>> imageset(Lambda(x, Abs(x-S(1)/2)), S.Naturals) == imageset(Lambda(x, Abs(x-S(1)/2)), S.Integers)
False.             # though they are same, but not easy to check
```
I thing possibilities are numerous.
Now but we can do one thing that check the domain first then if the domains are same only then check for equality in functions provided, I guess.

**Comment by kshitij10496** [comment]
@gxyd Can you elaborate on your idea of checking domains beforehand ?
What exactly do you mean by checking `S.Naturals` and `S.Integers` ?

**Comment by oscarbenjamin** [comment]
This example at least is fixed:
```
In [14]: st = ImageSet(Lambda(x,x),S.Naturals)                                                           

In [15]: st == S.Naturals                                                                                
Out[15]: True
```
