### ISSUE TITLE
Splitting simplify

### ISSUE THREAD

**Issue by jksuom** [sympy/sympy#9547]
``sympy/simplify/simplify.py`` has grown uncomfortably large. It is a collection of different types of simplification methods that are mostly independent of each other. It should be split into smaller files.

**Comment by toolforger** [comment]
Defining partitions and determining what goes to which partition requires judgement; this requires library design experience and/or feedback from the community. This is a chance to get one's feet wet with that kind of work though.
Carrying out an agreed-on partitioning is going to be the easy part.

**Comment by gxyd** [comment]
@jksuom also please close the issue. Thanks.
