### ISSUE TITLE
series expansion: (x**2 + x + 1)/(x**3 + x**2) about oo gives wrong result

### ISSUE THREAD

**Issue by leosartaj** [sympy/sympy#9549]
```
>>> e = (x**2 + x + 1) / (x**3 + x**2)
>>> series(e, x, oo)
x**(-5) + x**(-3) + 1/x + O(x**(-6), (x, oo)) # wrong result
```

Here's the result by [WolframAlpha](http://www.wolframalpha.com/input/?i=Series%5B%28x%5E2+%2B+x+%2B+1%29%2F%28x%5E3+%2B+x%5E2%29%2C+%7Bx%2C+Infinity%2C+5%7D)

```
x**(-5) - x**(-4) + x**(-3) + 1/x + O(x**(-6), (x, oo))
```

On Some further digging, result also appears to be inconsistent.

```
>>> series(e, x, oo, n=8)
-x**(-6) - x**(-4) + x**3 + 1/x + O(x**(-8), (x, oo))
```

Result by [WolframAlpha](http://www.wolframalpha.com/input/?i=Series%5B%28x%5E2+%2B+x+%2B+1%29%2F%28x%5E3+%2B+x%5E2%29%2C+%7Bx%2C+Infinity%2C+7%7D)

**Comment by leosartaj** [comment]
However, for

```
>>> apart((x**2 + x + 1) / (x**3 + x**2))
1/(x + 1) + 1/x**2
```
The result is correct

**Comment by vovapolu** [comment]
@leosartaj I found this while debugging your issue, but my fix doesn't solve the problem :(

**Comment by wrat** [comment]
issue solved?? I would like to work on this .

**Comment by grassknoted** [comment]
Is the Issue still open to work on?

**Comment by Him98** [comment]
@leosartaj  I was following this issue. Firstly, I wanted to ask if I can work upon it?
Secondly, while going through the code of sympy/core/sympy/expr.py I inferred that the for loop in line 2679 is creating the whole issue. Is that correct?

**Comment by Yathartha22** [comment]
@Him98 if you have found a fix just create a PR, there are lots of active people here who will help review your PR.

**Comment by grassknoted** [comment]
I will take this up.

**Comment by Him98** [comment]
It would be really helpful if someone can explain the present implementation of series function.
