### ISSUE TITLE
Eigen Value computation and Implementation of Cramers way to solve equations

### ISSUE THREAD

**Issue by dineshiith** [sympy/sympy#9550]
Why don't we have Computaion of eigen vectors and Cramers way of solving Equations

**Comment by aktech** [comment]
We do have Eigenvalue & Eigenvector computations, implemented in `matrices.py` , See [1] & [2].

The reason why we don't (may?) have Cramers way to solve equations, (probably you mean system of linear equations), is:

* Cramer's rule is computationally very inefficient for systems of more than two or three equations;
* Its asymptotic complexity is O(n·n!) compared to elimination methods that have polynomial time complexity.

We do have lot of better (computationally) techniques to solve such systems, implemented in `matrices.py`. If you are interested, you can help in improving them.

[1] https://github.com/sympy/sympy/blob/master/sympy/matrices/matrices.py#L2988
[2] https://github.com/sympy/sympy/blob/master/sympy/matrices/matrices.py#L3007
