### ISSUE TITLE
Ylm

### ISSUE THREAD

**Issue by mrnv** [sympy/sympy#9551]
Hi. I can't import Ylm: 
[code]In [206]: from sympy import Ylm[/code]
I get this message:
[code]ImportError                               Traceback (most recent call last)
<ipython-input-206-ca6d4f75f151> in <module>()
----> 1 from sympy import Ylm
ImportError: cannot import name Ylm[/code]

**Comment by aktech** [comment]
Can you please elaborate what functionality are you trying to import?

**Comment by mrnv** [comment]
Thank you for answer. Functionality is a Spherical. I'm a new in sympy, and did all of read in tutorial with every examples, and get mistakes only in one place:
>>> from sympy import Ylm
>>> from sympy.abc import theta, phi
>>> Ylm(1, 0, theta, phi)
  ___

**Comment by debugger22** [comment]
Could you please post the link to the tutorial having this example?

**Comment by mrnv** [comment]
It's russian tutorial, but if Ctrl+F you will find Ylm:
http://docs.sympy.org/dev-py3k/tutorial/tutorial.ru.html

**Comment by debugger22** [comment]
I found it [here](http://docs.sympy.org/0.7.2/tutorial.html). I think, it was renamed to `Ynm` in 0.7.3 release. You can see the implementation here https://github.com/sympy/sympy/blob/master/sympy/functions/special/spherical_harmonics.py

**Comment by debugger22** [comment]
@mrnv If this resolves your doubt, feel free to close this issue.

**Comment by mrnv** [comment]
Thank you, very much! And one more question, I use ipython and sage, instead isympy, but the functionality of the first was not enough. As I understand from sympy can use the missing functions in ipython simply inserting the required modules? Like this:
from sympy import <module_name>
