### ISSUE TITLE
parse_expr() crashes when used on matrix.

### ISSUE THREAD

**Issue by zelnoth** [sympy/sympy#9555]
If you use parse_expr on a matrix with matrix operations it crashes. 
example: Matrix([[1, -1], [3, 4], [0, 2]])+Matrix([[1, -1], [3, 4]
the error message: ImmutableMatrix has no attribute as_coef_Mul.

**Comment by smichr** [comment]
Please post the actual command that you used. It looks like part of what you meant to say is missing since there is a missing closing parenthesis on the 2nd Matrix.

**Comment by oscarbenjamin** [comment]
Completing that expression with brackets I get:
```julia
In [8]: parse_expr('Matrix([[1, -1], [3, 4], [0, 2]])+Matrix([[1, -1], [3, 4]])')                        
---------------------------------------------------------------------------
ShapeError                                Traceback (most recent call last)
...
ShapeError: Matrix size mismatch: (3, 2) + (2, 2)
```
which seems reasonable.

If I make the two matrices the same size then it works fine:
```julia
In [9]: parse_expr('Matrix([[1, -1], [3, 4], [0, 2]])+Matrix([[1, -1], [3, 4], [5, 6]])')                
Out[9]: 
⎡2  -2⎤
⎢     ⎥
⎢6  8 ⎥
⎢     ⎥
⎣5  8 ⎦
```

As far as the information provided this seems to be fixed now on master so I'll close.
