### ISSUE TITLE
solveset should solve the rational inequality abs((x-1)/(x-5)) <= 1/3

### ISSUE THREAD

**Issue by jondo** [sympy/sympy#9565]
```python
In [1]: x = symbols('x', real=True)
In [2]: from sympy.solvers.solveset import solveset
In [3]: solveset(abs((x-1)/(x-5)) <= 1/3)
```
gives
```
NotImplementedError: 
No algorithms are implemented to solve equation Piecewise(((x - 1)/(x - 5), x - 1 >= 0), ((-x + 1)/(x - 5), True)) - 1/3
```

Workaround, resolving the `abs`:
```python
In [4]: Intersection(solveset((x-1)/(x-5) <= 1/3), solveset(-(x-1)/(x-5) <= 1/3))
Out[4]: [-1.0, 2.0]
```

(Btw., this inequality also causes [trouble](https://groups.google.com/d/msg/sage-devel/QLEFLgkuXRg/RyYA7jpiuAAJ) in Sage.)

**Comment by jondo** [comment]
@aktech - is this planned to be implemented?

**Comment by aktech** [comment]
> @aktech - is this planned to be implemented?

It would certainly, someday. If you are interested, feel free to work on this.

**Comment by jondo** [comment]
Thanks!
For the record, setting `x` to real is not enough. I need to set the domain in the call:
```python
In [3]: solveset(abs((x-1)/(x-5)) <= 1/3, domain=S.Reals)
Out[3]: [-1.0, 2.0]
```

**Comment by jondo** [comment]
I have just tested this again in `isympy` on the current Git master.
For some reason it now does not work any more:

```python
>>> x = symbols('x', real=True)
>>> from sympy.solvers.solveset import solveset
>>> solveset(abs((x-1)/(x-5)) <= 1/3, domain=S.Reals)
⎧            │x - 1│                    ⎫
⎨x | x ∊ ℝ ∧ ─────── ≤ 0.333333333333333⎬
⎩            │x - 5│                    ⎭
```

Can someone please reproduce what I see? Pinging @smichr @kshitij10496 @hargup.
What happened?

**Comment by jondo** [comment]
For the record, @skirpichev showed me how to solve this without solveset:
```python
In [1]: x = symbols('x', real=True)
In [2]: reduce_inequalities(abs((x - 1)/(x - 5)) <= Rational(1, 3), x)
Out[2]: -1 ≤ x ∧ x ≤ 2
```
