### ISSUE TITLE
solve_univariate_inequality gives wrong solution to the rational inequality abs(1/(x-1)) > 1

### ISSUE THREAD

**Issue by jondo** [sympy/sympy#9567]
In current SymPy (commit c2ffd9), I see
```python
In [1]: x = symbols('x', real=True)
In [2]: from sympy.solvers.solveset import solveset
In [3]: solveset(abs(1/(x-1)) > 1)
Out[3]: (1, 2)
```
while the result should be ```(0, 1) ∪ (1, 2)```.

The following similar case works:
```python
In [4]: solveset(abs(1/x) > 1)
Out[4]: (-1, 0) ∪ (0, 1)
```
@aktech - can you please take a look?

**Comment by aktech** [comment]
Thanks for reporting. :)

I will take a look soon.

**Comment by aktech** [comment]
The problem is with `solve_univariate_inequality` in `sympy/solvers/inequalities.py`

```python
In [5]: solve_univariate_inequality(abs(1/(x-1)) > 1, x).as_set()
Out[5]: (1, 2)
```

**Comment by jondo** [comment]
Note to myself: This behavior exists since commit 613f2b6538722b5efceef0fa3c505db99504dc60. Before, it was a `NotImplementedError`.

**Comment by jondo** [comment]
@aktech Do you have any plans to continue [your GSoC work](http://iamit.in/blog/Google-Summer-Of-Code-with-SymPy/)?

**Comment by aktech** [comment]
> @aktech Do you have any plans to continue your GSoC work?

Currently, I don't have time to work on it full time, probably I may have some time in future to contribute more, but will be available to guide anyone interested in improving solvers, though expect slow replies from me these days, due to extremely busy schedule.

**Comment by smichr** [comment]
I note the problem with even solve:

```python
>>> from sympy import *;var('x',real=1)
x
>>>
>>> solve(-1+1/(1-x))
[]
>>>
>>> eq=-1+1/(1-x)
>>> eq.subs(x,0)
0
>>>
>>> solve(eq)  <--- 0 should be the solution
[]
```

**Comment by smichr** [comment]
The problem is that at line 1964 of solvers a `(0,0)` is returned; the logic of when there is no solution is wrong at that point. Line 1275 also needs to check that `d` is independent of `n`.

**Comment by smichr** [comment]
Fixing the underlying issue fixes the reported issue:

```python
>>> solveset(abs(1/(x-1)) > 1,domain=S.Reals)
(0, 1) U (1, 2)
```
