### ISSUE TITLE
Non-Assumption variable solving in `test_solveset.py`

### ISSUE THREAD

**Issue by gxyd** [sympy/sympy#9571]
I think  on [line] (https://github.com/sympy/sympy/blob/master/sympy/solvers/tests/test_solveset.py#L60)
```
>>> y = Symbol('y', real=True)
>>> x = Symbol('x', real=True)
>>> invert_real(Abs(x), y, x)
(x, FiniteSet(-y, y))       # this should not work unless we have some assumptions on `y` being a positive number, i guess.
```

**Comment by gxyd** [comment]
@hargup before i go for its PR.  Please answer the question on the [google groups] (https://groups.google.com/forum/#!topic/sympy/OLBjEvbgMn4)

**Comment by toolforger** [comment]
That's two unrelated issues.
Please open two small issues instead of one where each comment would need to state which of the two it's addressing.

**Comment by gxyd** [comment]
Opened now #9573 , lazy work.

**Comment by gxyd** [comment]
Can this be closed now ? It seems to have been fixed.

**Comment by hargup** [comment]
fixed with https://github.com/sympy/sympy/pull/9628
