### ISSUE TITLE
inconsistent diff on polynomials

### ISSUE THREAD

**Issue by pbrady** [sympy/sympy#9585]
From this stackoverflow question: http://stackoverflow.com/questions/31120436/why-does-sympy-diff-not-differentiate-sympy-polynomials-as-expected

``` python
In [1]: from sympy import *

In [2]: from sympy.abc import x

In [3]: p = Poly(x+1, x, domain='QQ')

In [4]: p.diff(x)
Out[4]: Poly(1, x, domain='QQ')

In [5]: diff(p, x)
Out[5]: Derivative(Poly(x + 1, x, domain='QQ'), x)

In [6]: diff(p, x).doit()
Out[6]: Derivative(Poly(x + 1, x, domain='ZZ'), x)
```

Seems like the toplevel `diff` is following a different code path compared to the `diff` method on Poly.

**Comment by leosartaj** [comment]
On inspection ``Poly`` class overrides the ``diff`` method. Top-level ``diff`` checks for a ``_eval_diff``, which is not implemented. Hence the inconsistent results.
