### ISSUE TITLE
utilities.autowrap.ufuncify fails with symbol lists of length >= 32

### ISSUE THREAD

**Issue by mikeroberts3000** [sympy/sympy#9593]
Hi friends, please allow me to introduce myself. My name is Mike Roberts. I am a computer science PhD student at Stanford. I've been using sympy recently to help me solve some fun optimization problems.

I have encountered some unexpected behavior in the `sympy.utilities.autowrap` module. I believe I am running into an undocumented hard-coded limit on the number of symbols I can pass into `sympy.utilities.autowrap.ufuncify(...)`. Here is the code snippet that demonstrates the unexpected behavior I'm seeing.

```
from pylab import *
import sympy
import sympy.utilities.autowrap

zero_expr = sympy.sympify("0")

num_syms           = 31
syms               = [ sympy.Symbol("x_%02d"%i) for i in range(num_syms) ]
vals               = zeros(len(syms))
zero_expr_ufuncify = sympy.utilities.autowrap.ufuncify(args=syms,expr=zero_expr,backend="numpy",verbose=True)

# works
print zero_expr_ufuncify(*vals)
print

num_syms           = 31
syms               = [ sympy.Symbol("x_%099d"%i) for i in range(num_syms) ]
vals               = zeros(len(syms))
zero_expr_ufuncify = sympy.utilities.autowrap.ufuncify(args=syms,expr=zero_expr,backend="numpy",verbose=True)

# also works
print zero_expr_ufuncify(*vals)
print

num_syms           = 32
syms               = [ sympy.Symbol("x_%02d"%i) for i in range(num_syms) ]
vals               = zeros(len(syms))
zero_expr_ufuncify = sympy.utilities.autowrap.ufuncify(args=syms,expr=zero_expr,backend="numpy",verbose=True)

# doesn't work
print "about to evaluate ufunc with 32 args..."
print zero_expr_ufuncify(*vals)
print
```

The first two calls to `zero_expr_ufuncify(*vals)` behave as expected, returning 0.0. But the last call to `zero_expr_ufuncify(*vals)` causes a segmentation fault. The exact error I'm getting is as follows.

```
Segmentation fault: 11
```

The only difference between these calls is that `sympy.utilities.autowrap.ufuncify(...)` was called with symbol lists of different lengths. For both behaves-as-expected calls, the corresponding symbol list is of length 31. For the does-not-behave-as-expected call, the corresponding symbol list is of length 32.

Note that the second call has a corresponding symbol list of length 31, but the symbols have very long names. Since this call behaves as expected, I believe this is not a problem of the generated C code having too many ASCII characters on a single line.

Note that I also found a post describing a similar issue on the Google Group. However, the code example from the Google Group is targeting a Fortran backend. Therefore, I believe the issue on the Google Group is different to the one I'm reporting here.

https://groups.google.com/forum/#!searchin/sympy/ufuncify/sympy/kgzcR8Qu7s4/RAGTw7A0I3oJ

I'm running sympy 0.7.6-1, which I installed via the Canopy Package Manager on OSX Yosemite 10.10.3, 64 bit.

**Comment by moorepants** [comment]
I think this is just a limit in C90, for example, see:

http://bytes.com/topic/c/answers/220647-maximum-number-arguments-function-call

You can get 127 with C99, which is enabled with the compiler flag `-std=c99'. I have this PR:

https://github.com/sympy/sympy/pull/9001

that allows you to add extra compile flags, but I needs to be finished.

You may be able to set an environment variable too.

**Comment by asmeurer** [comment]
Should the code generator try to work around this somehow (e.g., by passing in an array of values)?

**Comment by moorepants** [comment]
I suspect we could make the code generators "work" around this but it also seems reasonable that if you want to generate C backed code that you abide by C's rules. Maybe you could lump any args greater than 30 all together into a 2D array in the generated code, but I doubt that would play nicely with NumPy's ufunc machinery. We also don't have good support for multi-dimensional arrays in C yet.

**Comment by mroberts3000** [comment]
Here are my thoughts on this topic.

@moorepants If this is indeed a C compiler limitation, it is surprising that gcc didn't issue an error, or at least a warning, when it encountered a function with too many arguments. Note that I have verbose=True in the code example above, so I can confirm that gcc did not issue any such error or warning.

@moorepants I'm fine with my generated code abiding by the rules of C. But if I was actually writing the C code myself, and I needed to pass in more than 32 arguments, I would wrap those arguments into some kind of struct. There is no interface to do anything like that in sympy, so I am left with this severe limitation. My intuition is that it should always be possible to generate code that lumps all arguments into a struct, passes in the struct, and then retrieves the arguments from the struct inside the function into local variables before doing anything else. These local variables would have the exact same scope as the function's arguments. My intuition is that this approach could be implemented in a way that doesn't interfere with the rest of NumPy's ufunc machinery. Although maybe I'm missing something.

@asmeurer My feeling is, yes, the code generator ought to work around this somehow. Defining a struct whose members match the argument list for some to-be-autogenerated function, filling in the struct, passing the in the struct instead of the long argument list, and then retrieving the arguments out of the struct into local variables seems like a reasonable approach to me.

In the meantime, I'll try working around this issue, either by hacking in a compiler flag or setting an environment variable. I consider this approach to be suboptimal though. Although 127 arguments would be enough for me, I think it would be better if sympy natively supported an arbitrary number of arguments.

**Comment by moorepants** [comment]
@mroberts3000 I'm certainly not opposed to the code generators being smart enough in this case, for example creating a struct to house all the args as you suggest. It may need to be an optional thing, maybe only used in the auto wrappers as there are other use cases for the generated C code besides immediate wrapping. We can add this to the feature request list and we are always open to pull requests. Maybe you'd like to investigate implementing this?

**Comment by moorepants** [comment]
Btw, I get a ValueError instead of a segmentation fault:

```
In [17]: num_syms           = 32

In [18]: syms               = [ sympy.Symbol("x_%02d"%i) for i in range(num_syms) ]

In [19]: vals               = np.zeros(len(syms))

In [20]: zero_expr_ufuncify = sympy.utilities.autowrap.ufuncify(args=syms,expr=zero_expr,backend="numpy",verbose=True)
running build_ext
running build_src
build_src
building extension "wrapper_module_1" sources
build_src: building npy-pkg config files
customize UnixCCompiler
customize UnixCCompiler using build_ext
building 'wrapper_module_1' extension
compiling C sources
C compiler: gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC

creating build
creating build/temp.linux-x86_64-2.7
compile options: '-I/home/moorepants/anaconda/lib/python2.7/site-packages/numpy/core/include -I/home/moorepants/anaconda/include/python2.7 -c'
gcc: wrapped_code_1.c
gcc: wrapper_module_1.c
In file included from /home/moorepants/anaconda/lib/python2.7/site-packages/numpy/core/include/numpy/ndarraytypes.h:1804:0,
                 from wrapper_module_1.c:3:
/home/moorepants/anaconda/lib/python2.7/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
 #warning "Using deprecated NumPy API, disable it by " \
  ^
gcc -pthread -shared -L/home/moorepants/anaconda/lib -Wl,-rpath=/home/moorepants/anaconda/lib,--no-as-needed build/temp.linux-x86_64-2.7/wrapper_module_1.o build/temp.linux-x86_64-2.7/wrapped_code_1.o -L/home/moorepants/anaconda/lib -lpython2.7 -o wrapper_module_1.so


In [21]: zero_expr_ufuncify(*vals)
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-21-c03907e99a86> in <module>()
----> 1 zero_expr_ufuncify(*vals)

ValueError: Cannot construct an iterator with more than 32 operands (33 were requested)
```

**Comment by moorepants** [comment]
Looks like this is a NumPy issue: https://github.com/numpy/numpy/issues/5672

The code I show above is with NumPy 1.9.2.

**Comment by jcrist** [comment]
This is a limitation of the numpy ufunc api. Do you need ufunc behavior? If not, you can pass in arrays of values using ``MatrixSymbol``s.

**Comment by mroberts3000** [comment]
@moorepants I'd be in favor of that functionality being optional, as you suggest. That way, you'd only have to pay for it (slightly larger code size, slightly longer compile times, maybe slightly slower at runtime if the compiler couldn't optimize out all this intermediate struct stuff) if you figure out on your system that you need it. If I can't work around this issue by hacking in an additional command-line argument or environment variable, I'll implement the nicer struct passing solution.

**Comment by moorepants** [comment]
Here is a request in NumPy to increase the max # of args: https://github.com/numpy/numpy/issues/4398

**Comment by mroberts3000** [comment]
@moorepants Interesting that you get a ValueError instead of a segmentation fault.

**Comment by moorepants** [comment]
What version of NumPy are you using?

**Comment by mroberts3000** [comment]
@moorepants I'm using NumPy version 1.9.2-1. So do you think this isn't a compiler issue?

**Comment by moorepants** [comment]
Not sure, oddly this guy gets a seg fault with 1.9.2 but a ValueError with 1.8.2: https://github.com/numpy/numpy/issues/5672

**Comment by mroberts3000** [comment]
@moorepants That is odd. If this is a numpy thing, it's probably not possible to fix from within sympy. In that case, I would be in favor of sympy warning me not to pass in more than 31 arguments.

**Comment by mroberts3000** [comment]
@moorepants I did a bit more digging. I just successfully compiled and ran a C program that contained a function with 64 arguments. I was able to successfully call and return from the function with the long argument list, and I was able to make use of all the arguments from within that function. I compiled this program with the simplest possible command line invocation, `gcc main.c`. This confirms that the default gcc on my system supports functions with more than 32 arguments. In turn, this suggests that the issue I came across here is not a gcc issue, and seems to be related to the numpy issue you found.

**Comment by moorepants** [comment]
Yes, it seems to be related to NumPy's ufunc mechanics.

We could add a warning (or error) to the user if they pass in 32+ args to ufuncify with the 'numpy' backend. That's the simplest "fix" for now.

**Comment by mroberts3000** [comment]
@moorepants I agree with that approach as a simple "fix" until the underlying numpy issue is resolved. If such a warning was to be added to sympy, it would be ideal if sympy could check against the internal numpy constant. That way, if numpy changes that constant in future, sympy's behavior won't be overly restrictive. I'm not sure if that constant is considered part of numpy's "public" interface though. Anyway, thanks for all your help! :smile:
