### ISSUE TITLE
`solveset_complex(sinh(x), x)` returns `FiniteSet(0)`

### ISSUE THREAD

**Issue by gxyd** [sympy/sympy#9606]
```
>>> x = Symbol('x')
>>> solveset_complex(sinh(x), x)
FiniteSet(0)
```

It should return `ImageSet(Lambda(_n, _n*I*pi), Integers())`

**Comment by hargup** [comment]
> It should return `ImageSet(Lambda(_n, _n*I*pi), Integers())`

agreed, it should be easy to fix, you need to rewrite Hyperbolics as exp.

**Comment by oscarbenjamin** [comment]
I now get a new wrong result:
```
In [72]: x = Symbol('x')                                                                                                                       

In [73]: from sympy.solvers.solveset import solveset_complex                                                                                   

In [74]: solveset_complex(sinh(x), x)                                                                                                          
Out[74]: 
⎧            ⎛ 2⋅x    ⎞  -x    ⎫
⎪            ⎝ℯ    - 1⎠⋅ℯ      ⎪
⎨x | x ∊ ℝ ∧ ────────────── = 0⎬
⎪                  2           ⎪
⎩                              ⎭
```

**Comment by gschintgen** [comment]
If/when this gets fixed, it may be best to add a direct test case for ` _solve_trig1(sinh(x), x, S.Complexes)`.

(I'll try to improve and incorporate `_invert_complex` in `_solve_trig`. That could hide this issue, without fixing it. #17334)

As far as I can tell, the only thing mathematically wrong with the current answer is the "x in R" part, that `_solve_trig1` returns independently of the passed domain, S.Reals or S.Complexes. Possibly that part is not too difficult to fix.

```
In [12]: _solve_trig1(sinh(x), x, S.Complexes)
Out[12]:
⎧            ⎛ 2⋅x    ⎞  -x    ⎫
⎪            ⎝ℯ    - 1⎠⋅ℯ      ⎪
⎨x | x ∊ ℝ ∧ ────────────── = 0⎬
⎪                  2           ⎪
⎩                              ⎭

In [13]: _solve_trig1(sinh(x), x, S.Reals)
Out[13]:
⎧            ⎛ 2⋅x    ⎞  -x    ⎫
⎪            ⎝ℯ    - 1⎠⋅ℯ      ⎪
⎨x | x ∊ ℝ ∧ ────────────── = 0⎬
⎪                  2           ⎪
⎩                              ⎭
```

**Comment by gschintgen** [comment]
I've had a quick look at the code:  
- `_solveset` calls `_solve_trig` for both trig and hyperbolic equations.
- `_solve_trig1` then rewrites as exponentials
- **but** supposes that the rewritten equations contains only `exp(I*x)`, which is obviously wrong for hyperbolic equations
- it then returns a ConditionSet with a **hardcoded** S.Reals.

https://github.com/sympy/sympy/blob/a387ec651951f72b77ca45b3a43c0a45bc142dfe/sympy/solvers/solveset.py#L547-L554

I'll submit a fix.

**Comment by gschintgen** [comment]
I revived PR #14053, any review is most welcome.
