### ISSUE TITLE
Inverse Laplace Transform bug

### ISSUE THREAD

**Issue by proy87** [sympy/sympy#9619]
`3*s/(s**2 + 9)**2` raises `TypeError`. In fact, answer should be `1/2tsin(3t)`

**Comment by jksuom** [comment]
It seems to work now in master.

**Comment by proy87** [comment]
When this will available? I mean when will ne version be released?

**Comment by jksuom** [comment]
It is available from github. For example, as explained [here](https://github.com/sympy/sympy/wiki/Development-workflow#id32). The link on the right above (that looks like <>) offers other possibilities such as a [zip-file](https://github.com/sympy/sympy/archive/master.zip).

**Comment by proy87** [comment]
Thank you.

**Comment by jksuom** [comment]
NP. Perhaps this could be closed?

**Comment by proy87** [comment]
Sure.
