### ISSUE TITLE
Repeated example in the docstring of hermite

### ISSUE THREAD

**Issue by leosartaj** [sympy/sympy#9634]
The examples on [L-953](https://github.com/sympy/sympy/blob/master/sympy/functions/special/polynomials.py#L953) and [L-955](https://github.com/sympy/sympy/blob/master/sympy/functions/special/polynomials.py#L955) are the same. One example should be removed or add a new one instead.

**Comment by leosartaj** [comment]
This should be easy to fix.

**Comment by rjlasota** [comment]
Removed the redundancy, but have not added new examples.

**Comment by aktech** [comment]
Closed via #9645
