### ISSUE TITLE
Floats shouldn't be even, odd or prime in new assumptions

### ISSUE THREAD

**Issue by debugger22** [sympy/sympy#9636]
```
In [1]: from sympy import *

In [2]: a = S(1.0)

In [3]: a.is_odd
Out[3]: False

In [4]: ask(Q.odd(a))
Out[4]: True
```

Same goes for even and prime. Composite works fine.

**Comment by toolforger** [comment]
Note that 1 is generally considered non-prime. `Q.prime` does the right thing here:

```
>>> a = S(1.0)
>>> ask(Q.prime(a))
False
>>> b = S(3.0)
>>> ask(Q.prime(b))
True
```

**Comment by debugger22** [comment]
Yeah. For prime, you can consider something else. I'm talking about the floats. :)

**Comment by asmeurer** [comment]
The real question is whether 1.0 should be considered integer I suppose.
