### ISSUE TITLE
test_kane3 fails in master

### ISSUE THREAD

**Issue by moorepants** [sympy/sympy#9641]
I've been doing some investigation on `sympy/physics/mechanics/tests/test_kane3.py`. This test implements the bicycle test for mechanics that is a comprehensive test that exercises all of the details of the KanesMethod and Linearizer classes.

The test was introduced in PR #2182 (commit 919853f) and it worked then as a slow test which takes about 3-4 minutes on my machine.

The test was then removed from the slow tests on Travis mistakenly. I believe the code was broken by a commit to master and it was misdiagnosed as a too slow test on Travis, but it actually fails. So I'm not completely sure where the break is, but a git bisect based on timings of the completion of the function found in commit 6800beb.

The current failure in master is such that it takes a long time to complete >1 hour on my machine then when the numerics are subbed the comparisons fail because of NaNs in the expressions.

**Comment by moorepants** [comment]
FYI @jcrist

**Comment by moorepants** [comment]
I've just confirmed that 6800beb is the culprit for slowing down and breaking the old version of the linearizer. I'll check on the new linearizer code now.

**Comment by moorepants** [comment]
I reverted this commit on the master branch and ran the code as in master (i.e. with the old linearizer). It completes in ~4 mins but then NaNs are present. So there is a commit between this one and master that breaks the linearization in another way. Commit 6800beb is the cause of the slowdown. Now I can try to git bisect to find the commit that breaks the linearization.

**Comment by moorepants** [comment]
@certik @asmeurer Check this out. I'm not clear why this change to subs slows down our code so much.

**Comment by toolforger** [comment]
Is the `!=` doing a Python default comparison?
If yes, the new code iterates over all subexpression, applying a factor of `O(n)` to whatever is calling this, or `O(n²)` if `subs` recurses into the subexpressions again (`n` = number of nodes in the expression).

**Comment by certik** [comment]
@moorepants thanks for figuring it out. I don't know why it does it, but it needs to be fixed.

**Comment by jksuom** [comment]
This is what I get now after turning of the warning.
```
___________ sympy/physics/mechanics/tests/test_kane3.py:test_bicycle ___________
  File "sympy/utilities/pytest.py", line 147, in func_wrapper
    func()
  File "/home/jks/sympy/sympy/physics/mechanics/tests/test_kane3.py", line 260, in test_bicycle
    forcing_lin = KM.linearize()[0]
  File "sympy/physics/mechanics/kane.py", line 505, in linearize
    return self._old_linearize()
  File "sympy/physics/mechanics/kane.py", line 533, in _old_linearize
    subdict = dict(list(zip(uaux + uauxdot, [0] * (len(uaux) + len(uauxdot)))))
  File "sympy/core/decorators.py", line 118, in binary_op_wrapper
    return func(self, other)
  File "sympy/matrices/dense.py", line 532, in __add__
    return super(DenseMatrix, self).__add__(_force_mutable(other))
  File "sympy/matrices/matrices.py", line 570, in __add__
    raise TypeError('cannot add matrix and %s' % type(other))
TypeError: cannot add matrix and <type 'list'>
```
It seems that ``uaux`` gets a value of wrong type, possibly on [this line](https://github.com/sympy/sympy/blob/master/sympy/physics/mechanics/kane.py#L165).

**Comment by moorepants** [comment]
@jksuom So you turned off the deprecation warning? I very recently fixed the bug you mentioned, maybe you need to pull down master?

**Comment by jksuom** [comment]
Ok. This is the last commit I have: Tue Jul 7 11:58:30 2015 -0500

**Comment by moorepants** [comment]
This commit 14bcd32457 should have fixed your issue @jksuom, this is from July 9.

**Comment by jksuom** [comment]
Thanks, I did the pull. So far it seems that the subs's take an incredibly long time. It appears that @toolforger is right here.

**Comment by jksuom** [comment]
I have been profiling the old version. (It takes a tolerable time.) Most of the time is taken by ``linearize``, and there mostly (ca. 2/3 of the total time) in the computation of the jacobians of ``f2``. It is a vector with 6 components and ``count_ops`` gives the following numbers:
```
In [24]: count_ops(f2[0])
Out[24]: 201607

In [25]: count_ops(f2[1])
Out[25]: 162521

In [26]: count_ops(f2[2])
Out[26]: 186933

In [27]: count_ops(f2[3])
Out[27]: 4384

In [28]: count_ops(f2[4])
Out[28]: 4765

In [29]: count_ops(self[5])
Out[29]: 4028
```
Also substitutions and finding atoms in the first three expressions are very slow.

**Comment by moorepants** [comment]
@jksuom We think #8506 has to do with the extreme slowness. The substitutions are taking the most time now in master. And the old version is more bottlenecked by the linearize (jacobian/diff) methods. Thanks for the operation counts.

**Comment by moorepants** [comment]
It seems that `as_real_imag` is too slow and is called a lot in both subs and diff.

**Comment by certik** [comment]
@jksuom I've been working on speeding up the Jacobian, I just implemented it in SymEngine (https://github.com/sympy/symengine/pull/524), I just need to implement a few more things so that I can handle PyDy problems using SymEngine.

**Comment by jksuom** [comment]
Some of the structures in ``test_bicycle`` are so huge that even a small improvement may have a remarkable effect. Among the components of the result of ``linearize``, called ``forcing_lin``, there are half a dozen having between 1.3 and 1.5 million operations. Merely ``count_ops`` takes tens of seconds. It is no wonder that the substitutions seem to last 'forever'.

**Comment by moorepants** [comment]
> that even a small improvement may have a remarkable effect

Absolutely, this is a good stress test for some of our algorithms.

> It is no wonder that the substitutions seem to last 'forever'.

The code before the offending commit ran in ~4 mins and now it takes > 1 hr. The 4 mins was tolerable, but we can likely get it faster than that, even in pure SymPy.

**Comment by oliverlee** [comment]
This test now takes me < 2 minutes.

**Comment by moorepants** [comment]
Does it pass? It was failing for me due to some other reason than just being slow.

**Comment by oliverlee** [comment]
No still NaNs in the matrices.

**Comment by moorepants** [comment]
Ok, this bug may be tougher to track down. It was likely introduced in @jcrist's makeover of the linearization code.

**Comment by oliverlee** [comment]
```msubs``` returns NaNs after dividing by zero in the expression tree.

**Comment by moorepants** [comment]
@jcrist FYI

**Comment by moorepants** [comment]
But I think the issue is that the new linearization routines setup these possible divide by zeros, whereas the old routine didn't. There is a `smart` flag in msubs that tries to avoid evaluating any `1/0` explicitly and treat it as a limit instead.

**Comment by oliverlee** [comment]
The test didn't finish after 8000 seconds with ```smart=True```

**Comment by moorepants** [comment]
We should determine if the test passes if we use subs instead of msubs. If it does, then subs must have something in it that can handle these `1/0` terms and treat them more like a limit. Not sure.

**Comment by oliverlee** [comment]
Test doesn't finish after 42000 seconds if subs is used instead of msubs.

**Comment by asmeurer** [comment]
Still fails in the 1.1.1 branch:

```
______________________________________________________________________________________________________________________________________________________________
__________________________________________________ sympy/physics/mechanics/tests/test_kane3.py:test_bicycle __________________________________________________
  File "/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/utilities/pytest.py", line 147, in func_wrapper
    func()
  File "/users/aaronmeurer/documents/python/sympy/sympy/sympy/physics/mechanics/tests/test_kane3.py", line 282, in test_bicycle
    Amat = MM_full_s.inv() * forcing_lin_s
  File "/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/matrices/matrices.py", line 2781, in inv
    """
  File "/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/matrices/dense.py", line 260, in _eval_inverse
    rv = M.inverse_GE(iszerofunc=iszerofunc)
  File "/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/matrices/matrices.py", line 2696, in inverse_GE
    raise NonSquareMatrixError("A Matrix must be square to invert.")
ValueError: Matrix det == 0; not invertible.
```

It took 5437 seconds to run.

**Comment by moorepants** [comment]
This is now fixed. Some notes:

- When the new linearizer class was introduced it relied on LUsolve instead of the prior solve methods. It broke kane3 because divide-by-zeros occurred.
- Every problem will likely require a different linear solver to avoid divide-by-zero and some problems can't avoid without a super slow full proof symbolic method that produces excessively long equations. I think also that some problems can't even avoid divide-by-zero because we purposely set some of the variables to zero. So care has to be taken to try to find a choice of generalized coordinates and a form of the various constraint equations + a suitable solver to get stable floating point results.

**Comment by certik** [comment]
@moorepants great job, thanks for fixing it!

**Comment by oscarbenjamin** [comment]
> * I think also that some problems can't even avoid divide-by-zero because we purposely set some of the variables to zero.

I think this can be avoided. You just need a separate symbolic solve for the cases where you set some variables to zero (i.e. set to zero before solving). I showed somewhere a solver that could get generic solutions reasonably fast but it would just need to be applied separately for each degenerate case. I also showed a solver that would find all possible generic and degenerate cases. It would be worth looking into those methods.

**Comment by moorepants** [comment]
Yes, I agree we'd have to identify and solve every degenerate case separately.

> I showed somewhere a solver that could get generic solutions reasonably fast but it would just need to be applied separately for each degenerate case. I also showed a solver that would find all possible generic and degenerate cases. It would be worth looking into those methods.

I think I know which solution you are referring to (the one where you sub in random values?), if that is it, it misses all degenerate cases. I don't recall seeing a solution that identifies the degenerate cases.

**Comment by oscarbenjamin** [comment]
> I don't recall seeing a solution that identifies the degenerate cases.

See https://github.com/sympy/sympy/issues/24679#issuecomment-1479654290 and gh-16861.

**Comment by moorepants** [comment]
https://github.com/sympy/sympy/issues/16861 does look like what we need, in general. We\ll have to investigate more. Thanks!
