### ISSUE TITLE
Cancel Travis builds if a newer commit on the same branch appears

### ISSUE THREAD

**Issue by toolforger** [sympy/sympy#9658]
A "stale" Travis run is a run scheduled for a commit that was superseded by a later commit on the same branch.
We want to have such stale runs cancelled, because
1) stale runs needlessly tie up Travis resources, i.e. we're not playing nice with Travis.
2) Travis schedules a limited number of runs per repository. This means that the stale runs delay execution of the final, actually interesting run.

Bonus points if a stale run can be reactivated, because sometimes such runs are still interesting.
One way to make that happen would be to let restarted runs execute even if they are stale.

**Comment by isuruf** [comment]
See https://github.com/grosser/travis_dedup

**Comment by asmeurer** [comment]
Travis finally has this feature built in https://blog.travis-ci.com/2017-03-22-introducing-auto-cancellation. I've enabled it for pull request builds. It seems reasonable to leave it off for master builds, and there aren't many of them anyway (only one per merged PR).

**Comment by toolforger** [comment]
Am 23.03.2017 um 20:54 schrieb Aaron Meurer:
> Travis finally has this feature built in
> https://blog.travis-ci.com/2017-03-22-introducing-auto-cancellation.
> I've enabled it for pull request builds.

Nice to see that this has finally become possible :-)
