### ISSUE TITLE
Improve Coverage of Geometry Module

### ISSUE THREAD

**Issue by aktech** [sympy/sympy#9660]
Ideally It should be around 98%, though anything above 95% would be good.

Current coverage:

![geometrt](https://cloud.githubusercontent.com/assets/5647941/8637465/bec87080-28af-11e5-95a0-873813bb2ea1.png)

**Comment by toolforger** [comment]
If you work on this, do not chase percentages; look at the module, devise things you'd like to see tested, see if a test for that already exists, and if it does not, write the test.

References:
http://www.artima.com/forums/flat.jsp?forum=106&thread=204677
http://www.exampler.com/testing-com/writings/coverage.pdf (pp. 4 ff. in particular)

**Comment by gxyd** [comment]
@aktech  As an example: currently only `23 %` is shown in coverage_report.py for `plane.py` but a good percentage of the code is covered in the `doctest` itself. Do you still think that for `that case(plane.py)` it still remains an issue to add `the test` for the `plane.py` file ? I am `not` saying the issue you have filed is invalid. I am just asking that does those `tests` still needs to be added if they have been covered in `doctest` ?

**Comment by moorepants** [comment]
@gxyd I think the pattern we follow in SymPy is to test all functionality in the unit tests. The doc tests are examples of usage and just happen to be able to be tested as a bonus to our test suite. So, in general, we should focus on writing useful unit tests that have strong coverage in the `test_*.py` files.

**Comment by aktech** [comment]
@gxyd 

The following addresses your concerns, quite good.
Quoting from the Development Workflow [Code modification](https://github.com/sympy/sympy/wiki/Development-workflow#code-modification) section.

>
Keep in mind, doctests are not tests. Think of them as examples that happen to be tested. Some key differences:

> * write doctests to be informative; write regular tests to check for regressions and corner cases.
* doctests can be changed at any time; regular tests should not be changed.

>In particular, we should be able to change or delete any doctest at any time if it makes the docstring better to understand.

**Comment by gxyd** [comment]
Thanks @moorepants @aktech. If no one is working on the issue can i take it up ?

**Comment by aktech** [comment]
>  If no one is working on the issue can i take it up ?

Sure, go ahead!

**Comment by gxyd** [comment]
@aktech here the `23%` coverage report for the `plane.py` comes after the running the `tests` without the `--slow` option. But `almost`(may be not all) all the requisite `tests` are present in `plane.py` in the function `test_plane` decorated with `@slow`. Am i doing some thing wrong here ?

**Comment by aktech** [comment]
@gxyd 

Good catch! You are right. The `coverage_report.py` doesn't runs the slow tests by default, so the current coverage is due to not running of the `@slow` decorated tests.

Here is the actual report (running all the `@slow` tests):

![geometry](https://cloud.githubusercontent.com/assets/5647941/8935745/eff8d7e4-356b-11e5-82a7-d7a1ad2c1ab2.png)

**Comment by aktech** [comment]
I think this issue is resolved, we already have enough coverage to close this issue.

**Comment by gxyd** [comment]
@aktech  Can you please tell me which command did you used in terminal for running `@slow` tests
I did this
```
$ ./bin/coverage_report.py sympy/geometry --slow
The generated coverage report is in covhtml directory.
Open sympy/covhtml/index.html in your web browser to view the report
gxyd@swap:~/Public/sympy$ ./bin/coverage_report.py sympy/geometry --slow
Usage: coverage_report.py [options]

coverage_report.py: error: no such option: --slow
```
This returns an error.

**Comment by aktech** [comment]
I did it manually, removing all the `@slow` decorators.
