### ISSUE TITLE
Zero matrix notebook display

### ISSUE THREAD

**Issue by akhmerov** [sympy/sympy#9661]
A `ZeroMatrix` object has MathJax-incompatible LaTeX representation:

    >>> sympy.printing.latex(ZeroMatrix(n, n))
    '\\bold{0}'

Which results in the following in IPython notebook:

![zeromatrix](https://cloud.githubusercontent.com/assets/2069677/8637642/08f8a292-289c-11e5-9842-2ebac54882fa.png)

A fix should probably replace `bold` with `mathbb`.

**Comment by jksuom** [comment]
I think you are right. ``\bold`` does not seem to be a standard latex (or tex) command, neither is it in the [mathjax documentation](http://www.onemathematicalcat.org/MathJaxDocumentation/TeXSyntax.htm). In the old AMS-TeX package there is ``\boldsymbol``, which applies to almost all symbols. ``\mathbf`` was introduced in AMS-LaTeX  primarily for letters and numbers. In this case, probably either one of ``\boldsymbol`` and ``\mathbf`` could be used.

**Comment by akhmerov** [comment]
I've chosen `\mathbb` in line with the way identity matrix is printed (see PR)

**Comment by gxyd** [comment]
Though this was already reported on issue #9420

**Comment by akhmerov** [comment]
Thanks, I updated the PR description.
