### ISSUE TITLE
Summing symbolic element

### ISSUE THREAD

**Issue by ArrinasW** [sympy/sympy#9664]
Greetings, everyone.
     I am trying to use sympy calculate a perturbation problem, which looks like:
    
![per](https://cloud.githubusercontent.com/assets/13285424/8638804/01e256e4-28f9-11e5-8ab8-92f424a56b92.png)

     In sympy, I think it's safe to use code like:(all elements are Matrices.)

     i=Symbol("i",integer=True)
     summation( (u.H*Hamil*p.col(i))*(p.col(i).H*Hamil*u) , (i,0,5))   
      
     However, it gives the error:
     IndexError: Invalid index a[i]
     
     It seems that SymPy doesn't support such operaion.
     Does anyone knows solution to this?
     Any advises would be appreciated.
     Thanks.

**Comment by leosartaj** [comment]
Could you give an example for all the matrices you have used and the expected result? @ArrinasW

**Comment by ArrinasW** [comment]
Yes,sure.
@leosartaj, thanks for reply.
u=Matrix([1,0,0,1,0,1j,0,0,0,0])/sqrt(3)
Hamil is a symbolic 10*6 matrix,
![Uploading 选区_002.png…]()

p matrix is an identity matrix, which makes p.col(i) look like Matrix([1,0,0,0,0,0]).
Manually, I have done the sum, which gives the right result.

At first, I thought it is p.col(i) could not be used with i as an index.
So, a list P_orb is used to store p.col(i), and the code becomes:
   summation( (u.H * Hamil * P_orb[i]) * (P_orb[i].H * Hamil * u) , (i,0,5))  
Run it would give an error:
   TypeError: list indices must be integers, not Symbol
It seems that SymPy have such "symbol-index" problem, I am hoping there might be a solution.
Thank you very much!

**Comment by leosartaj** [comment]
This is a problem with indexing.

For eg.

```
>>> l = [1, 2, 3]
>>> l[m]
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-424-eb08d94c8253> in <module>()
----> 1 l[m]

TypeError: list indices must be integers, not Symbol
```

Therefore the error is caused before summation can be done. You need to somehow modify your code. Something like ``P.col(i)`` or ``P_orb[i]`` will not work simply because symbolic indexing is not allowed.

**Comment by leosartaj** [comment]
Maybe you can use a for loop rather than calling ``summation``.

**Comment by ArrinasW** [comment]
OK, I think it is the best solution for now.
Thank you very much!
