### ISSUE TITLE
Solving trigonometric nonlinear equations using Python

### ISSUE THREAD

**Issue by Nedaaaa** [sympy/sympy#9672]
I am trying to solve the following equation in Python. I used Sympy library but I got the error that No algorithms are implemented to solve equation!
2 * cos(x) = x
Can anyone please tell me how can I solve this equation?

**Comment by moorepants** [comment]
@Nedaaaa Would you mind typing the exact code you use here along with the error traceback?

**Comment by jksuom** [comment]
```
In [9]: nsolve(2*cos(x) - x, 0)
Out[9]: mpf('1.0298665293222588')
```

**Comment by Nedaaaa** [comment]
@moorepants first I tried this:
x  =  symbols('x')
solve(2 * cos(x) - x, x)
I also tried this:
solve( Eq(2 * cos(x) / x, 1), x)
but for both of them I got the same error!

**Comment by aktech** [comment]
Solving `2*cos(x) = x` symbolically is a very hard problem, I don't think any Computer Algebra System can solve this symbolically.

SymPy also can't provide an symbolic solution to this.
Nevertheless you can solve this numerically, using `nsolve`:

```python
In [3]: nsolve(2*cos(x) - x, x, 1)
Out[3]: mpf('1.0298665293222588')
```

This is a correct result, you can Verify from [WolframAlpha](http://www.wolframalpha.com/input/?i=solve+2+*+cos%28x%29+%3D+x) as well.

**Comment by Nedaaaa** [comment]
@jksuom @aktech Thank you so much, Super helpful suggestion!
