### ISSUE TITLE
Q.infinitesimal is now deprecated

### ISSUE THREAD

**Issue by debugger22** [sympy/sympy#9675]
`Q.infinitesimal` has been deprecated. Use `Q.zero` instead.

This is the `Deprecation Removal` issue for the same.

See https://github.com/sympy/sympy/pull/9676

**Comment by aktech** [comment]
> Q.infinitesimal has been deprecated. Use Q.infinitesimal instead.

I think you mean this:
`Q.infinitesimal` has been deprecated. Use `Q.zero` instead.

**Comment by debugger22** [comment]
Yes. Thanks!
