### ISSUE TITLE
Trig Functions with Symbols

### ISSUE THREAD

**Issue by ktbug** [sympy/sympy#9680]
Please excuse my ignorance. This is my first time with Sympy.

I am trying to solve 6 equations with 4 unknowns. 

The equations have trig functions of symbols.

For instance one equation I am working on:

distance=[] # a list of calculated values
beta=Symbol('beta')
equation_one=Eq(distance,d*mpmath.cos(beta))

Error: cannot convert mpf from 'beta'

Can someone please explain this to me? Suggestions on how to fix it?

**Comment by debugger22** [comment]
Hi,

​
> equation_one=Eq(distance,d*mpmath.cos(beta))

 ​
Why is there a list in the equation?

Sudhanshu Mishra

**Comment by ktbug** [comment]
Sorry, I meant array. I have a calculated numpy array of values. 

I want to go through and calculate for each value in the array the potential beta and d values from the equations

**Comment by asmeurer** [comment]
You can't just freely mix SymPy, NumPy, and mpmath functions. In particular, you can't pass SymPy symbols to mpmath functions (they only take numeric arguments). If you are interested in using numpy to evaluate a SymPy expression you should create the expression with SymPy functions and then use `lambdify` to convert that to something that you can evaluate with numpy.

**Comment by ktbug** [comment]
How would I define a trig function then? To get the the point that I can use lambdify?

**Comment by asmeurer** [comment]
Use `sympy.cos`.

**Comment by asmeurer** [comment]
I'm going to close this because I don't think there are any SymPy bugs here, but feel free to continue the discussion if you still have questions.
