### ISSUE TITLE
Investigate whether msubs() is any different than xreplace.

### ISSUE THREAD

**Issue by moorepants** [sympy/sympy#9703]
We created sympy/physics/mechanics/functions:msubs because subs is slow, but we may not have realized that xreplace would solve what we need. We should make sure that msubs is not redundant wrt to xreplace.

**Comment by oliverlee** [comment]
```xreplace``` performs bottom up replacement in the expression tree. This would not ignore ```Derivative``` expressions as is done in ```msubs```.

However, it may be useful to have a general substitution function that can ignore certain types of subexpressions.

**Comment by moorepants** [comment]
Got it. It's never been very clear to me the difference in subs and xreplace. Understand now. We can close this.
