### ISSUE TITLE
`Interval(-oo, 0).closure` hangs

### ISSUE THREAD

**Issue by gxyd** [sympy/sympy#9706]
```
>>> Interval(-oo, 0).closure`
# hangs (takes forever)
# Interval(-oo, 0) should be returned
```

**Comment by moorepants** [comment]
Can you quantify forever? Does is actually finish?

**Comment by gxyd** [comment]
No, it does not finish till 10 minutes.
I ran for 10 minutes on my `Linux` machine. It resulted in no output(error) on the `IPython Notebook` as `Traceback`. But just hanged.

**Comment by aktech** [comment]
The problem resides in the reduce method of Union class:
```python
Union(Interval(-oo, 0), FiniteSet(-oo))
```

[This](https://github.com/sympy/sympy/blob/master/sympy/sets/sets.py#L1195) iterates infinitely: `
  new_args = (args - set((s, t))).union(new_set)
`

**Comment by jksuom** [comment]
``Interval`` does currently not allow the construction of the closure. It will [silently remove](https://github.com/sympy/sympy/blob/master/sympy/sets/sets.py#L763) the added endpoint.

**Comment by kshitij10496** [comment]
Do we want the `closure` to remain unevaluated (like @hargup suggested in #8257 ) or
do we want it to return a value ?

**Comment by asmeurer** [comment]
closure doesn't have a docstring, but given that Interval always represents a subset of the reals (it is impossible to create an interval containing `oo`), I think closure should mean "closure over R" (keep in mind that "closure" is a meaningless concept without a larger topological space, much like "complement" is meaningless without a set universe). In that case, the closure of `(-oo, 0)` is `(-oo, 0]`.

**Comment by asmeurer** [comment]
We could also change Interval to be over extended reals, but that would be an API break (currently `Interval(-oo, oo)` doesn't contain the endpoints, even though `Interval(a, b)` otherwise does contain the endpoints). IMHO we should keep it as finite real as it currently is (but make sure this is documented well).

**Comment by jksuom** [comment]
I wonder if there is any well-grounded reason for defining intervals as subsets of reals instead of extended reals. (That would be natural as both concepts, intervals and extended reals, are derived from the same order.) I suspect that issues like this one and #8257 are symptoms of an inconsistent choice.

**Comment by kshitij10496** [comment]
Like its stated in the documentation of `Interval` that `Only real end points are supported`.

```
In [ ]: foo = Interval(-oo, oo)

In [ ]: foo.contains(-oo)
Out[ ]: True

In [ ]: foo.contains(oo)
Out[ ]: True

```
However, the `contains` method includes both `∞` and `-∞`.
Doesn't this contradict the stated behaviour of Interval being a subset of reals ?

**Comment by asmeurer** [comment]
That definitely looks a bug. `foo` prints as `(-oo, oo)` and foo.args` is `(-oo, oo, True, True)` (True means open). Can you open a new issue (or pull request) for it?

**Comment by asmeurer** [comment]
I guess the issue is

```
        if self.start is S.NegativeInfinity and self.end is S.Infinity:
            if not other.is_real is None:
                return other.is_real
```

in `Interval._contains`. But the problem is that oo.is_real is True, which is a known issue with the old assumptions (I guess https://github.com/sympy/sympy/issues/8203 is the issue for it).

**Comment by rpisarev** [comment]
@gxyd Please see my fix
