### ISSUE TITLE
wrong statement in docstring at sympy.calculus.finite_diff

### ISSUE THREAD

**Issue by derDavidT** [sympy/sympy#9709]
`using sympy 0.7.6`
The code itself is fine. This concerns its docstring only.
The docstring of `sympy.calculus.finite_diff_weights` mentiones, that the gridpoints `x_list` have to be given as "strictly monotonically increasing sequence". In fact, the cited resource [1] does not say so. Instead it mentions that "the order in which the [gridpoints] are given is significant" and later on gives examples with a list of gridpoints "from the inside out", e.g. `[0, -1, 1, -2, 2]` or `[-1/2, 1/2, -3/2, 3/2]`.
This approach is especially beneficial, if using finite difference weights for a subset of `x_list`.
Strictly speaking, this issuse concerns `sympy.calculus.apply_finite_diff` and `sympy.calculus.as_finite_diff` as well.

**Comment by bjodah** [comment]
Interesting, that was an oversight by me. Would you mind opening a pull request updating the docstring and maybe include an example of these unordered x_list and maybe write a sentence or two about their usefulness?

**Comment by derDavidT** [comment]
Hi,

I will do so. But since I'm new to github please habe some patience.

Am 21.07.2015 20:34 schrieb =?ISO-8859-1?Q?Bj=F6rn_Dahlgren?= <notifications@github.com>:

Interesting, that was an oversight by me. Would you mind opening a pull request updating the docstring and maybe include an example of these unordered x_list and maybe write a sentence or two about their usefulness?

**Comment by bjodah** [comment]
Feel free to ask any questions if you run into trouble making the pull request.
(for this kind of changes you may even do your editing directly in your web browser by hitting the "pen" icon on the upper right here: https://github.com/sympy/sympy/blob/master/sympy/calculus/finite_diff.py)

**Comment by derDavidT** [comment]
I just created a new pull request #9715.

**Comment by bjodah** [comment]
Fixed in #9715
