### ISSUE TITLE
symbolic integration of a matrix results in a vector?

### ISSUE THREAD

**Issue by laflij** [sympy/sympy#9712]
I am using sympy in a python3 ipython notebook.  I have defined a 4x4 matrix who's entries are functions of 'x' and then integrate the matrix, the integration then returns a vector. 

![sympy integrate matrix to vector](https://cloud.githubusercontent.com/assets/4930270/8804517/acdcc17c-2f9a-11e5-81ab-dc4ce4fd36cc.png)

**Comment by bjodah** [comment]
I am unable to reproduce this.
What version of SymPy are you using?
Could you provide a small script which sets up a (minimal) matrix, integrates and makes a (failing) `assert`?

**Comment by laflij** [comment]
Sympy 0.7.6

Here is a script that reproduces the problem.  In coming up with the minimal script I noticed that if you take out the sym.expand() the problem goes away.  



    import sympy as sym
    
    from sympy.interactive import printing
    printing.init_printing(use_latex='mathjax')


    x, l = sym.symbols('x l')
    h = sym.symarray('h', 2)
    
    h[0] = sym.Rational(1,2)*(1 - x)
    h[1] = sym.Rational(1,2)*(1 + x)
    H = sym.expand(sym.Matrix([h[0]*sym.eye(2), h[1]*sym.eye(2)])).T

    D = H.T*H
    D
    sym.integrate(D,(x,0,l))

**Comment by bjodah** [comment]
The bug is related to expand() making H an instance of ImmutableMatrix.
sym.integrate(D.as_mutable(), (x,0,l)) works.
