### ISSUE TITLE
Add domain argument to solveset

### ISSUE THREAD

**Issue by hargup** [sympy/sympy#9727]
The current solveset code has two main solvers `solveset_real` and `solveset_complex` for real complex domains respectively. `solveset` is a thin wrapper on top of them which calls these domain specific solvers on the basis of the assumptions on the input variables. A better way to do this would be to have a explicit `domain` argument in `solveset`.

**Comment by hargup** [comment]
@shivamvats wants to help with this, @aktech you can concentrate on other issues.

**Comment by aktech** [comment]
> @shivamvats wants to help with this

Thanks @shivamvats !

**Comment by hargup** [comment]
@shivamvats any news?

**Comment by shivamvats** [comment]
@hargup I am on it. Will update in some time.

**Comment by shivamvats** [comment]
Do set operations auto-simplify? 
Shouldn't any set `A` `Intersection` `S.Complexes simplify to `A` ?

**Comment by gxyd** [comment]
Atleast this should not satisfy it.
```
>>> (S.UniversalSet).intersection(S.Complexes)
S.Complexes
```

**Comment by shivamvats** [comment]
Ah! I didn't know about `S.UniversalSet`.
I had this in mind:
```
In [28]: solveset(exp(x) - 1, x).intersection(S.Complexes)
Out[28]: Intersection(ImageSet(Lambda(_n, 2*_n*I*pi), Integers()), Complexes(Lambda((x, y), x + I*y), (-oo, oo) x (-oo, oo)))
```

**Comment by gxyd** [comment]
> I had this in mind:
In [28]: solveset(exp(x) - 1, x).intersection(S.Complexes)
Out[28]: Intersection(ImageSet(Lambda(_n, 2*_n*I*pi), Integers()), Complexes(Lambda((x, y), x + I*y), (-oo, oo) x (-oo, oo)))

I had the same thought what you may be thinking.
I think this is an issue which is a subset of the issue #9543 , i am not sure though.

**Comment by shivamvats** [comment]
Yes. The plan is to take intersection of `domain` with whatever result `solveset_*` gives. But that complicates the answer in many cases.

**Comment by hargup** [comment]
@shivamvats you can simply call `solveset_real` and `solveset_complex` when the domain is given as `S.Reals` and `S.Complex` without taking an intersection with the domain. `solveset_real` and `solveset_complex` that the result is in required domain. For other cases you need not worry about a complicated `Intersection` object now.
