### ISSUE TITLE
Add an optional dependency of pycosat

### ISSUE THREAD

**Issue by debugger22** [sympy/sympy#9728]
We should use [this](https://github.com/ContinuumIO/pycosat) Python binding to picosat solver.

Thoughts?

**Comment by bjodah** [comment]
If you think it will speed up the assumptions (cf. #9714) it would be great. If it's added in the same way as `fastcache` is optional the only downside would be a larger test-suite, right? (but maybe not the complete testsuite needs to be rerun with and without pycosat?)

**Comment by debugger22** [comment]
> the only downside would be a larger test-suite, right?

I think only the logic(or assumptions) tests would suffice to test the integrity.
