### ISSUE TITLE
num/denom is not equal to (-num)/(-denom)

### ISSUE THREAD

**Issue by aktech** [sympy/sympy#9737]
Following is an example:
```
In [25]: n = x + y

In [26]: d = x - y

In [27]: n/d == -n/-d
Out[27]: False
```

**Comment by jonesnp** [comment]
Similarly, 

`>>> (n/d).compare(-n/-d)`
` -1`
`>>>`

**Comment by asmeurer** [comment]
This is correct. Remember that == is structural comparison, not mathematical. http://docs.sympy.org/latest/tutorial/gotchas.html#equals-signs
