### ISSUE TITLE
`singularities((x**2 - 1)/(x**3 - 1), x)` returns `()`

### ISSUE THREAD

**Issue by gxyd** [sympy/sympy#9739]
It should return `(1,)` since `1` is a singularity point of `(x**2 - 1)/(x**3 - 1)`

**Comment by jksuom** [comment]
According to the docstring of ``singularities``.
> Finds singularities for a function.
    Currently supported functions are:
    - univariate real rational functions

The point is: what is a rational function?

I think that ``(x**2 - 1)/(x**3 - 1)`` and ``(x + 1)/(x**2 + x + 1)`` are SymPy expressions that denote the same rational function. That rational function has no real singularities. (Apparently complex singularities are not considered, though not explicitly excluded.)

A rational function is more abstract than an expression. It can be thought of an an equivalence class of rational expressions.

**Comment by gxyd** [comment]
@jksuom So your argument looks valid. Then should  this be closed ?

**Comment by jksuom** [comment]
I think so.
