### ISSUE TITLE
 solveset(Piecewise(((x - 2)**2, x >= 0), (0, True)), x) returns EmptySet()

### ISSUE THREAD

**Issue by aktech** [sympy/sympy#9742]
```python
In [14]: f = Piecewise(((x - 2)**2, x >= 0), (0, True))

In [15]: f
Out[15]: 
⎧       2           
⎪(x - 2)   for x ≥ 0
⎨                   
⎪   0      otherwise
⎩                   

In [16]: solveset(f, x)
Out[16]: ∅

```

**Comment by aktech** [comment]
It works now:

```python
In [8]: f = Piecewise(((x - 2)**2, x >= 0), (0, True))

In [9]: solveset(f, x, S.Reals)
Out[9]: (-∞, 0) ∪ {2}
```

**Comment by gxyd** [comment]
Isn't it still required to add the `corresponding test`, and figure out which PR fixed this ?

**Comment by aktech** [comment]
Oh, I see #9743 was not merged, hence the [XFAILing](https://github.com/sympy/sympy/pull/9743/files#diff-fe18b6ce3631e6ad441c4d6cfc5eb58dR328) Test is not already present. Feel free to open an issue/PR for adding the test. Btw, I don't remember where it was fixed.
