### ISSUE TITLE
coverage_report.py should be able to run slow tests also

### ISSUE THREAD

**Issue by aktech** [sympy/sympy#9746]
Currently Coverage report doesn't runs slow tests, so the coverage report generated is not accurate.
It should run slow tests by a flag.

```
bin/coverage_report.py 
```

**EDIT**
It  should accept a --slow flag just like bin/test.

**Comment by aktech** [comment]
See https://github.com/sympy/sympy/issues/9660#issuecomment-125655647

**Comment by moorepants** [comment]
I don't think it should run the slow tests by default but it should accept a `--slow` flag just like `bin/test`.

**Comment by aktech** [comment]
> I don't think it should run the slow tests by default but it should accept a --slow flag just like bin/test.

Yes, I agree. I was about to change the description.
