### ISSUE TITLE
Integral done wrong by sympy

### ISSUE THREAD

**Issue by hhassey** [sympy/sympy#9753]
It seems to me that this integral is not solved correctly in Sympy, I checked the correct result in Sage and Mathematica, Am I wrong in something:

integrate(1/(d*k-k*x))  Note: d is not a diferential, was a distance on my original formula. and the integral is made with respect to x. also K is just a constant.

Here you can take the Ipython notebook to take a closer look:

https://drive.google.com/file/d/0B3df_KfoaW8qQk95RE0xRVRjZVk/view?usp=sharing

I love sympy but I am really worried about all my other results on stuff calculated with it,
Can you please keep me posted on this?

Regards

Humberto

**Comment by asmeurer** [comment]
The two integrals differ by a constant (granted, it's a complex constant, but it's still a constant). If you differentiate the result given by SymPy you get the original function back:

```
In [9]:

simplify(f - a.doit().diff(x))
Out[9]:
0
```

**Comment by asmeurer** [comment]
To clarify, SymPy's integrate uses the complex logarithm. The usual real integral of 1/x is log(|x|), but SymPy returns just log(x), which is correct in the complex domain. Depending on what you do with the resulting integral, you may need to make a modification, or you may not (often the complex terms cancel out, e.g., when taking a definite integral over a real domain).

**Comment by hhassey** [comment]
OK Thanks so much for your response, I hardcoded the result so I will go
back and re calculate with sympy's result and report back, I am calculating
the definite integral on the real domain.
