### ISSUE TITLE
unxfail few solveset tests

### ISSUE THREAD

**Issue by hargup** [sympy/sympy#9771]
https://github.com/sympy/sympy/pull/9628 made [this](https://github.com/sympy/sympy/blob/master/sympy/solvers/tests/test_solveset.py#L540-L547) and [this](https://github.com/sympy/sympy/blob/master/sympy/solvers/tests/test_solveset.py#L565-L572) xfailed test pass. We need to unxfail them.

**Comment by hargup** [comment]
This should be an "Easy to Fix" issue. @kumarkrishna this would be a good issue for you to take up.

**Comment by arun11meena** [comment]
Hi, I am new to github and sympy. Can I pick this up? @hargup

**Comment by gxyd** [comment]
@arun11meena I think you can go ahead with this.

**Comment by gxyd** [comment]
You can follow the [this](https://github.com/sympy/sympy/wiki/Development-workflow)
