### ISSUE TITLE
LUdecomposition_Simple does not compute the LU decomposition of a non-square or non-invertible matrix

### ISSUE THREAD

**Issue by twhunt** [sympy/sympy#9796]
The current implementation of LUdecomposition_SImple does not compute the LU decomposition of a matrix A if A is non-invertible or non-square. However, for any m x n matrix matrix A, there exists an m x m  permutation matrix P, m x m lower triangular matrix L with unit diagonal, and m x n upper triangular matrix U  such that P_A = L_U [1]. Less formally stated, for any A, there exists a permutation of the rows of A such that the permuted A is the product of a square invertible lower triangular matrix, and an upper triangular matrix. Extending the implementation of LUDecomposition_Simple to handle the general non-square and non-invertible case for computing solutions to systems of equations that have infinitely many solutions.

[1] Linear Algebra and its Applications, 3rd edition, Gilbert Strang, p. 73

**Comment by siefkenj** [comment]
This was fixed with your patch in #12218.  I think we can close the issue.

**Comment by jksuom** [comment]
Closed on account of #12218.
