### ISSUE TITLE
Change get/set methods in vector and mechanics modules to @property

### ISSUE THREAD

**Issue by moorepants** [sympy/sympy#9800]
In `sympy/physics/vector` and `sympy/physics/mechanics` most of the classes have lots of getter/setter methods. It would be nice to change the API to be more pythonic by making use of the `@property` decorator. It would be great to do this before a SymPy 1.0 release.

@sympy/mechanics

**Comment by oliverlee** [comment]
A number of the set/get involve a frame and a vector. Do you propose using a `(frame, vector)` tuple for the get/set methods in `sympy/physics/vector`?

**Comment by moorepants** [comment]
Great point, I haven't thought it out that far. Maybe this proposal is premature...

What brought this up was more like `get_masscenter` on RigidBody, which should just be an attribute. There are a number of things that could be fixed.

**Comment by moorepants** [comment]
I'll try to make a list of the getter/setters soon so we can see which ones may be able to be changed.

**Comment by oliverlee** [comment]
WIP: https://github.com/oliverlee/sympy/tree/fix-9800

**Comment by moorepants** [comment]
How do you think we should deprecate it? It may be best to leave the get/set methods in place and have them spit a dep warning saying that they will be removed with SymPy 1.0. What do you think?

**Comment by oliverlee** [comment]
https://github.com/oliverlee/sympy/commit/4f720dce95141c96f7280ef5823ce0047849ab48

**Comment by oliverlee** [comment]
There's an option in the `SymPyDeprecationWarning` class for last supported version, which is a bit different than the first version it's no longer supported, so I just left it out.

**Comment by moorepants** [comment]
@sahilshekhawat FYI, do you want to incorporate Oliver's changes for your new Body code. If he opens a PR we can merge it before your Body PR. Once he opens a PR, you should review it.
