### ISSUE TITLE
resolve_atan2 fails on master branch (infinite loop with certain input)

### ISSUE THREAD

**Issue by Erotemic** [sympy/sympy#9802]
I'm running into what looks like an infinite loop using the following minimial test example: 

            import sympy
            from sympy.assumptions.refine import refine_atan2
            symkw = dict(real=True, finite=True)
            a = sympy.symbols('a', positive=True, **symkw)
            theta  = sympy.symbols('theta', **symkw)

            iv11, iv12  = sympy.symbols('iv11, iv12', **symkw)
            arb_assign = {
                 iv12: -sympy.sin(theta)/a,
                 iv11: sympy.cos(theta)/a,
            }

            ori_subs_nomod = sympy.atan2(-sympy.sin(theta)/a, sympy.cos(theta)/a)

            # Causes an infinite loop
            atan2_case1 = refine_atan2(ori_subs_nomod,
                sympy.Q.real(arb_assign[iv12]) & sympy.Q.positive(arb_assign[iv11])
            )

I based my code on the example in http://omg.readthedocs.org/en/latest/modules/assumptions/refine.html#sympy.assumptions.refine.refine_atan2

The following code seems to work. 

        >>> from sympy import Symbol, Q, refine, atan2
        >>> from sympy.assumptions.refine import refine_atan2
        >>> from sympy.abc import x, y
        >>> print(refine_atan2(atan2(y,x), Q.real(y) & Q.positive(x)))
        >>> print(refine_atan2(atan2(y,x), Q.negative(y) & Q.negative(x)))
        >>> print(refine_atan2(atan2(y,x), Q.positive(y) & Q.negative(x)))

The sympy version info is:
sympy.__version__ = '0.7.7.dev'
commit hash: e91e0d845ac27633f4b708514ee1ca77cfde40d6

Here is my machine info if it is relevant: 
platform.machine() = 'AMD64'
platform.python_build() = ('default', 'Jun 30 2014 16:03:49')
platform.python_compiler() = 'MSC v.1500 32 bit (Intel)'
platform.python_implementation() = 'CPython'
platform.python_revision() = ''
platform.python_version() = '2.7.8'
platform.python_version_tuple() = ('2', '7', '8')
platform.release() = '7'
platform.system() = 'Windows'

**Comment by moorepants** [comment]
@Erotemic Note that the omg docs are not the official SymPy docs. omg is a fork of SymPy which may be different. See docs.sympy.org for the official documentation.

**Comment by debugger22** [comment]
@Erotemic This code gives me an output

```
debugger22@jarvis:~/workspace/sympy$ [master] time python test.py
-atan(sin(theta)/cos(theta))

real	0m8.512s
user	0m8.474s
sys	0m0.043s
```

**Comment by debugger22** [comment]
We are changing the way how refine works but none of the code has been merged yet which can affect this.

**Comment by debugger22** [comment]
Could you please try with the latest master? If it works, feel free to close this issue.

**Comment by Erotemic** [comment]
Testing this on my linux machine seems to work now. It takes 6 seconds, but that is significantly less than forever.

**Comment by debugger22** [comment]
Could anyone please try this on a windows machine?

**Comment by Erotemic** [comment]
I did. Seems to be fine.
