### ISSUE TITLE
Evalf gives wrong result for 0**I

### ISSUE THREAD

**Issue by debugger22** [sympy/sympy#9807]
```
In [1]: from sympy import *

In [2]: x = Symbol('x')

In [3]: (x**I).evalf(subs={x:0})
Out[3]: 0  # should be nan

```

UnXFAIL `test_autosimp_fails` in test_query.py after fixing this.

**Comment by rpisarev** [comment]
On current master we have that

In [3]: 0**I
Out[3]: nan

Probably, we can close this issue.

**Comment by oscargus** [comment]
This seems to work now since the `test_autosimp_fails` no longer fails.
