### ISSUE TITLE
Complements with symbols should remain unevaluated

### ISSUE THREAD

**Issue by hargup** [sympy/sympy#9808]
Complements with symbols should remain unevaluated for the same reason Intersections with symbols should remain unevaluated i.e., we don't know what the complement is unless we the value of the symbol. Our current behaviour is:
```python
In [14]: Complement(FiniteSet(y), FiniteSet(1))
Out[14]: {y} # should be {y}\{1}
```

**Comment by hargup** [comment]
@gxyd probably you can take this up.

**Comment by gxyd** [comment]
@hargup What you expect the output of this : 
```
>>> FiniteSet(1) - FiniteSet(x, y, z)  # what output you expect ?
{1} \ {x, y, z}    # some may expect this
{1} \ {x}           # the next three are same in behavior
{1} \ {y}
{1} \ {z}
```
?
I am not sure how hard it is going to be to implement this.

**Comment by jksuom** [comment]
I would prefer the first variant, i.e., the essentially unevaluated expression. It seems more readable than some other alternatives such as ConditionSet.

**Comment by hargup** [comment]
The first variant is the correct and expected variant, btw I don't see how the second variant is correct and same as the first variant?

**Comment by gxyd** [comment]
Thanks @jksuom 
@hargup 
> btw I don't see how the second variant is correct and same as the first variant?

Yes, you are right. I got a little confused. Thanks.
