### ISSUE TITLE
ODE solver cannot solve Bessel equation

### ISSUE THREAD

**Issue by yanncalec** [sympy/sympy#9819]
I tried to solve the Bessel equation with Sympy (version 0.7.6), but got a weird result (the Bessel function is expected):

```
>>> x = symbols('x')
>>> f = Function('f')
>>> eq=Derivative(f(x),x,2)*x*x+x*Derivative(f(x),x,1)+(x*x)*f(x)
>>> dsolve(eq)
f(x) == C1*(x**4/64 - x**2/4 + 1) + O(x**6)
```

**Comment by zanzibar7** [comment]
Yes, we need somebody to implement a routine in ode.py that will recognize and solve the 
classical 2nd-order variable-coefficient linear ordinary differential equations like the Bessel equation and the Airy equation.  The solution sympy is currently giving is the series for Bessel's J function of order 0:

```
In [51]: besselj(0,x).series(x,0,6)
Out[51]: 
     2    4        
    x    x     ⎛ 6⎞
1 - ── + ── + O⎝x ⎠
    4    64       
```
The full solution should be `C1*bessely(0,x)+C2*besselj(0,x)`.

**Comment by nagarakshay** [comment]
I would like to work on this.

**Comment by zanzibar7** [comment]
@nagarakshay  I [started to work](https://github.com/zanzibar7/sympy.git) on this several months ago and got a little way, but not to Bessel functions.  Airy equations seemed like an easier place to start, and then Bessel equations could be added on.  Ultimately, hypergeometric equations could also be addressed.  Please feel free to look at my changes, and feel free to incorporate them.

**Comment by nagarakshay** [comment]
@zanzibar7 Thank you. I will surely have a look. I will incorporate them in my PR.

**Comment by nagarakshay** [comment]
@zanzibar7 What further changes may be done?

**Comment by nagarakshay** [comment]
However the issue is not addressed because it really won't work for n=0 and I don't think it should because both solution are linearly dependant when n=0. Correct me if I am wrong.
Jn(x)=J-n(x)

**Comment by nagarakshay** [comment]
See PR#10870
