### ISSUE TITLE
Simple equation solving over finite fields incorrectly produces empty solution sets

### ISSUE THREAD

**Issue by j2kun** [sympy/sympy#9821]
To reproduce, run

```
>>> solve(Eq(poly(x + y,domain=FF(7)),0),x,y)
```

Expected behavior: produce any solution to the equation that is reduced mod 7, e.g. `[{x:0, y:0}]`

Actual behavior: output is `[]`

If this is the actual behavior, I would like to know how to solve equations over finite fields properly in Sympy. I have tried to find this in the documentation but it does not seem to exist. Apologies if I am mistaken.

**Comment by j2kun** [comment]
This appears to always produce empty solution sets no matter the equation, so long as any argument is over a finite field domain.

**Comment by hargup** [comment]
@j2kun you are right SymPy doesn't support equation solving over finite fields. The `solve` function has couple of other issues too and we are rewriting it in a new module called `solveset`. The documentation for that is being carried out in https://github.com/sympy/sympy/pull/9500, let us know what do you think about it. I also invite you to add equation solving over finite fields in the `solveset` module.

**Comment by jksuom** [comment]
This seems to work, however:
```
>>> solve(poly(x + y, domain=FF(7)), x, y)
[{x: -y}]
```

**Comment by j2kun** [comment]
Can anyone comment on whether @jksuom 's solution generalizes correctly?

**Comment by hargup** [comment]
> Can anyone comment on whether @jksuom 's solution generalizes correctly?

No it doesn't, it worked only because the solution concided with the solution in the Real domain, here are two quick examples to show that:

```python
In [34]: f = Poly(x*3 + y + 5, domain=FF(7))

In [35]: solve(f,x,y)
Out[35]: [{x: -y/3 + 2/3}]

In [27]: f = Poly(x*y + y*y + x*x + 4, domain=FF(7))

In [28]: solve(f,x,y)
Out[28]: [{x: -y/2 - sqrt(-3*y**2 + 12)/2}, {x: -y/2 + sqrt(-3*y**2 + 12)/2}]
```

**Comment by sorgloomer** [comment]
Hi! Seems like solveset is implemented now, but it still does not support linear equations over finite fields, is that the case?

**Comment by island99** [comment]
@sorgloomer I have the same problem as you. Have you found a feasible method, for linear equations over finite fields.

**Comment by hamadakafu** [comment]
I'm now using this
```python
import sympy as sp

def r_to_f(rational, f):
    return f(rational.p) / f(rational.q)


def main():
    f = sp.FF(811)
    a = sp.Symbol("a")
    b = sp.Symbol("b")
    c = sp.Symbol("c")
    f = sp.FF(811)

    eq1 = sp.Poly(a + b + c - 1, a, b, c, domain=f)
    eq2 = sp.Poly(2 * a + b + 3 * c - 10, a, b, c, domain=f)
    eq3 = sp.Poly(5 * a + 3 * b + 3 * c, a, b, c, domain=f)
    ans = sp.solve([eq1, eq2, eq3])
    print(eq1(r_to_f(ans[a], f), r_to_f(ans[b], f), r_to_f(ans[c], f)))
    print(eq2(r_to_f(ans[a], f), r_to_f(ans[b], f), r_to_f(ans[c], f)))
    print(eq3(r_to_f(ans[a], f), r_to_f(ans[b], f), r_to_f(ans[c], f)))
```
```shell
# output
0
0
0
```

**Comment by oscarbenjamin** [comment]
It should be possible to do this using `solve_lin_sys` but it doesn't seem to work:
```julia
In [7]: from sympy.polys.solvers import solve_lin_sys                                                                                          

In [8]: x, y = symbols('x, y')                                                                                                                 

In [9]: R = FF(7)[x, y]                                                                                                                        

In [10]: rx, ry = map(R.convert, [x, y])                                                                                                       

In [11]: solve_lin_sys([rx + ry], R)                                                                                                           
Out[11]: {x: 6 mod 7*y}
```
