### ISSUE TITLE
Matrix power of identity matrix fails

### ISSUE THREAD

**Issue by Bonnevie** [sympy/sympy#9823]
This seems very wrong to me: taking the identity matrix to the power of 2 yields the matrix of all zeros.

``` ipython
In [1]: import sympy as s

In [2]: M = s.Identity(3)

In [3]: A = (M**2)

In [4]: A.as_explicit()
Out[4]: 
Matrix([
[0, 0, 0],
[0, 0, 0],
[0, 0, 0]])
```

calculating I*I explicitly yields the correct result.

**Comment by oliverlee** [comment]
Looks like ```__pow__``` isn't defined for the ```Identity`` class.

**Comment by jksuom** [comment]
``__pow__`` is defined for the ``Identity`` class, but it returns a ``MatPow`` object that is not explicitly evaluated. Matrix multiplication works fine.
```
>>> M = Identity(3)
>>> A = M*M
>>> A.as_explicit()
Matrix([
[1, 0, 0],
[0, 1, 0],
[0, 0, 1]])
```

**Comment by oliverlee** [comment]
Are you looking at the right branch? It isn't defined for me.

**Comment by oliverlee** [comment]
This also happens for ```ZeroMatrix``` with ```MatPow``` as it only handles instances of ```MatrixBase```.
```python
In [1]: from sympy import MatPow, ZeroMatrix

In [2]: M = ZeroMatrix(3, 3)

In [3]: M**3 == M
Out[3]: True

In [4]: MatPow(M, 3) == M
Out[4]: False
```

**Comment by kevalds51** [comment]
according to me it would be better to have separate conditions for ZeroMatrix and Identity matrix, this can be very easily evaluated using the predefined boolean variables such as isIdentity and is_ZeroMatrix. This would also reduce a lot of computation in case of large matrices.

**Comment by oscarbenjamin** [comment]
This works fine on master:
```julia
In [58]: In [1]: import sympy as s 
    ...:  
    ...: In [2]: M = s.Identity(3) 
    ...:  
    ...: In [3]: A = (M**2) 
    ...:  
    ...: In [4]: A.as_explicit()                                                                                                               
Out[58]: 
⎡1  0  0⎤
⎢       ⎥
⎢0  1  0⎥
⎢       ⎥
⎣0  0  1⎦
```
