### ISSUE TITLE
solveset fails on sin(x)**2 - 2*sin(x) + 1

### ISSUE THREAD

**Issue by kumarkrishna** [sympy/sympy#9824]
`solveset` raises `NotImplementedError` on the above equation.

However, a similar variation is solved :
`>>> solveset(cos(x)**2 - 2*cos(x) + 1, x, domain=S.Reals)`
`ImageSet(Lambda(_n, 2*_n*pi), Integers())`

**Comment by ishanaj** [comment]
`solveset` currently produces the correct output for:
```
>>>solveset(sin(x)**2 - 2*sin(x) + 1, x, domain=S.Reals)
ImageSet(Lambda(_n, 2*_n*pi + pi/2), S.Integers)
```
@aktech @kumarkrishna Is there anything else to be done? I would like to work on it.

**Comment by namannimmo10** [comment]
I think this just needs a test. And we can close this issue afterwards. @asmeurer, "easy to fix" label can be added.

**Comment by oscarbenjamin** [comment]
I've added the easy to fix label. Tests are needed for these two results:
```
In [24]: solveset(cos(x)**2 - 2*cos(x) + 1, x)                                                                                                 
Out[24]: {2⋅n⋅π | n ∊ ℤ}

In [25]: solveset((sin(x)**2 - 2*sin(x) + 1))                                                                                                  
Out[25]: 
⎧        π        ⎫
⎨2⋅n⋅π + ─ | n ∊ ℤ⎬
⎩        2        ⎭
```
