### ISSUE TITLE
solveset fails on solveset(Eq(tan(x), y), x, domain=S.Reals)

### ISSUE THREAD

**Issue by kumarkrishna** [sympy/sympy#9825]
`>>> solveset(Eq(tan(x), y), x, domain=S.Reals)`
`EmptySet()`

However, `solveset(Eq(tan(x), y), x)` raises `NotImplementedError` since inversion is not handled.

**Comment by ishanaj** [comment]
@smichr  @Shekharrajak @aktech Currently `solveset(Eq(tan(x), y), x, domain=S.Reals)` goes to `_solve_trig()` and returns a `ConditionSet`. But, this can be solved by simply calling `invert_real()` (somewhere [here](https://github.com/sympy/sympy/blob/master/sympy/solvers/solveset.py#L720)) and the correct answer is obtained i.e.
`(x, ImageSet(Lambda(_n, _n*pi + Mod(atan(y), pi)), S.Integers))`.
Can this be a good fix?
