### ISSUE TITLE
Solve ode with initial conditions

### ISSUE THREAD

**Issue by MichielStock** [sympy/sympy#9826]
I want to solve an ode with initial conditions. For example

> N, t, r, K, N0 = sp.symbols('N, t, r, K, N_0')
> logistic = sp.Eq(N(t).diff(t), r \* N(t) \* (1 - N(t)/K))
> sp.dsolve(sp.powsimp(logistic), N(t))

Returns $N{\left (t \right )} = \frac{K e^{C_{1} K + r t}}{e^{C_{1} K + r t} - 1}$. How can I find $C_1$ so that N(0) = N0?

I know there are [issues](https://www.google.be/url?sa=t&rct=j&q=&esrc=s&source=web&cd=4&cad=rja&uact=8&ved=0CC4QFjADahUKEwjo9KCVkqbHAhVFLNsKHWcRDpg&url=http%3A%2F%2Fcode.google.com%2Fp%2Fsympy%2Fissues%2Fdetail%3Fid%3D1621&ei=i5jMVaiDJcXY7AbnorjACQ&usg=AFQjCNEi_yMqOi-ZAXZbTFSdIBudM4auWg&sig2=DBGkhG1gU6H8BMUA5AxRbA) with entering the initial conditions directly, but I don't see how to know the solve() function as I cannot access C1, the constant term. Is there a hack to this?

**Comment by zanzibar7** [comment]
This can be worked around but creating some symbol sets and looking for the new symbols that
didn't appear in your original equation.

```python
N, t, K = symbols('N, t, K')
logistic = Eq(N(t).diff(t), N(t) * (1 - N(t)))
sol = dsolve(powsimp(logistic), N(t))
C_1 = sol.atoms(Symbol).difference(logistic.atoms(Symbol)).pop()
Eq(C_1,solve(sol,C_1).pop().subs(t,0))```

**Comment by MichielStock** [comment]
Thanks for the hack. Seems to work now.

**Comment by oscarbenjamin** [comment]
This doesn't seem to be an issue any more. The current `dsolve` can solve this ODE with ICs just fine:
```julia
In [32]: t, r, K, N0 = symbols('t, r, K, N_0')
    ...: N = Function('N')
    ...: logistic = Eq(N(t).diff(t), r * N(t) * (1 - N(t)/K))
    ...: dsolve(powsimp(logistic), N(t), ics={N(0):N0})
    ...: 
    ...: 
    ...: 
Out[32]: 
                    r⋅t        
             -K⋅N₀⋅ℯ           
N(t) = ────────────────────────
                ⎛      r⋅t    ⎞
                ⎜  N₀⋅ℯ       ⎟
       (K - N₀)⋅⎜- ─────── - 1⎟
                ⎝   K - N₀    ⎠
```

**Comment by oscarbenjamin** [comment]
Closing as fixed.
