### ISSUE TITLE
Defining printing for `S.Naturals0`

### ISSUE THREAD

**Issue by gxyd** [sympy/sympy#9848]
```
>>> init_printing(use_unicode=True)
>>> S.Naturals
ℕ
>>> S.Naturals0
ℕ
```

There should should be some difference in their printing may be putting a `N0`(0 in subscript) for `S.Naturals0`.

**Comment by aktech** [comment]
It's not the case, printing is not defined for `Naturals0`.

```python
In [8]: S.Naturals0
Out[8]: Naturals0()

In [9]: S.Naturals
Out[9]: ℕ
```
Possible issue can be: Define printing for `Naturals0`.

**Comment by gxyd** [comment]
@aktech I have updated the title of the issue.
