### ISSUE TITLE
solveset(Abs(sin(x)) + 1, x, S.Reals) returns `Non-Empty`

### ISSUE THREAD

**Issue by gxyd** [sympy/sympy#9849]
```
>>> solveset(Abs(sin(x)) + 1, x, S.Reals)
{x | x ∈ ℝ ∧ False }        # this should return S.EmptySet
```
While the `Eq` version works correctly
```
>>> solveset(Eq(Abs(sin(x)), -1), x, S.Reals)
∅
```
The reason for this i think is(i am guessing):
```
>>> imageset(Lambda(n, S.false), S.Naturals)
{False | n ∈ ℕ }
```

**Comment by gxyd** [comment]
@aktech do you agree with the reason ?

**Comment by aktech** [comment]
The reason for this is `ConditionSet` doesn't simplify `ConditionSet(Lambda(x, False), (-oo, oo))`, even though it's implicitly an `EmptySet()`. I think `ConditionSet` can be made to return `EmptySet` when the second argument to `Lambda` is `False` .
