### ISSUE TITLE
Second derivatives of coordinates cause an error in Kane's method linearization

### ISSUE THREAD

**Issue by thessem** [sympy/sympy#9852]
I'm attempting to linearize the output of Kane's method with `linearizer = KM.to_linearizer()` and I am getting the following error

> ValueError                                Traceback (most recent call last)
> <ipython-input-28-dbbef311e200> in <module>()
> ----> 1 linearizer = KM.to_linearizer()
> 
> C:\Development\Python27\lib\site-packages\sympy\physics\mechanics\kane.pyc in to_linearizer(self)
>     440         #        self._k_ku, self._f_k, self._k_dnh, self._f_dnh, self._k_d]):
>     441         #    raise ValueError('Cannot have dynamicsymbols outside dynamic \
> --> 442         #                     forcing vector.')
>     443 
>     444         # Find all other dynamic symbols, forming the forcing vector r.
> 
> ValueError: Cannot have dynamicsymbols outside dynamic                              forcing vector.

When checking for dynamic symbols it populates an excluded symbol list with `sym_list = set(Matrix([q, self._qdot, u, self._udot, uaux, uauxdot]))` but I have second derivatives of my coordinates in the equations, causing this check to fail (whereas first derivatives are excluded).

Is this expected behaviour? Will skipping this check cause the result to be incorrect?

**Comment by moorepants** [comment]
Kane's method requires that you substitute the definitions of the generalized speeds into all of the velocity expressions before forming the equations of motion. If you do that, then you should not have any second derivatives in the equations of motion, they should be in first order form with only first derivatives present.

Why do you have second derivatives in your equations of motion?

**Comment by thessem** [comment]
I had to add a a term to my u_ind, since I couldn't generate a list of velocity constraints without a coordinate 1st derivative. This was the obvious thing to do in retrospect, and so the failure to run the linearisation is a good sanity check.

I'm closing the issue, thanks.
