### ISSUE TITLE
bad subset evaluation

### ISSUE THREAD

**Issue by worldmaker18349276** [sympy/sympy#9855]
> > > x, y, z = symbols('x, y, z', real=True)
> > > s1 = Interval(1,x) & Interval(y,2)
> > > s2 = Interval(1,2)
> > > s1.is_subset(s2)
> > > False
> > > simplify(s1.contains(z) >> s2.contains(z))
> > > True

**Comment by smichr** [comment]
Looks like this might be fixed:
```python
>>> s1.is_subset(s2) is None
True
```

**Comment by oscarbenjamin** [comment]
The `is_subset` result was changed from False to None in 31c2dfa2ed466bbd644ade6ad14bbfb7ecbb33a0 from #17526.

On the other hand the correct answer is True so None is suboptimal here. I'm not sure if there is a simple way to improve `is_subset` or if there should be some other way of asking more complicated `is_subset` queries like this.

**Comment by 1e9abhi1e10** [comment]
Hello everyone , I wish to fix this issue  could you please assign this  issue to me ?

**Comment by oscarbenjamin** [comment]
Issues are not assigned. Feel free to work on this though.

I think that @smichr's intention was that this could be fixed if a test is added for this case somewhere.

**Comment by Lucas-longxutang** [comment]
Hi, may I be assigned to this issue? I would like to do my best to address it.

**Comment by Gpanaritis** [comment]
Hello, I am currently working on a handler for (intersection, interval). Should I continue or is None result acceptable?

**Comment by oscarbenjamin** [comment]
There could be a handler for Intersection and Interval. All of these handlers should be fairly cheap though so it should be simple and should not use any potentially slow functions/operations.
