### ISSUE TITLE
Change interface for ConditionSet

### ISSUE THREAD

**Issue by hargup** [sympy/sympy#9860]
In a recent [PR](https://github.com/sympy/sympy/pull/9696) we added a ConditionSet class to represent sets of form `{x | condition(x) is True for x in S}`. The current interface to create a condition set is `ConditionSet(imageset(var, condition), input_set)`. Since the first argument is always an `imageset` the interface can be simplified to `ConditionSet(var, condition, input_set)`.

**Comment by gxyd** [comment]
In this what is the expected value of
```
>>> ConditionSet(x, Eq(sin(x), 0), S.Reals).condition
-> Eq(sin(x), 0)   # this is what i think should be returned
-> (x |-> sin(x) = 0)    # this is currently returned
```
?
I am asking since, if i use `Eq(sin(x), 0)` as answer of above question, then i have to make changes to the `printing` of `Condition` (a little more things to do then)

**Comment by hargup** [comment]
> In this what is the expected value of
```
>>> ConditionSet(x, Eq(sin(x), 0), S.Reals).condition
-> Eq(sin(x), 0)   # this is what i think should be returned
-> (x |-> sin(x) = 0)    # this is currently returned
```
?
I am asking since, if i use `Eq(sin(x), 0)` as answer of above question, then i have to make changes to the `printing` of `Condition` (a little more things to do then)

Yes, `.condition` shoulld` return the condition not the underlying imageset.
