### ISSUE TITLE
Symbol names with sub/superscripts interact badly with parentheses

### ISSUE THREAD

**Issue by QuLogic** [sympy/sympy#9861]
[Here](http://live.sympy.org/?evaluate=Symbol%28%27x_a%27%29%0A%23--%0ASymbol%28%27x^a%27%29%0A%23--%0ASymbol%28%27x^ab%27%29%0A%23--%0ASymbol%28%27x^{a}b%27%29%0A%23--%0ASymbol%28%27{x^a}b%27%29%0A%23--%0ASymbol%28%27x_1^a%27%29%0A%23--%0ASymbol%28%27%28x_1%29^a%27%29%0A%23--%0ASymbol%28%27%28{x_1}%29^a%27%29%0A%23--%0ASymbol%28%27{%28{x_1}%29}^a%27%29%0A%23--%0A) is a SymPy Live example of sub/superscripts with parentheses.

Some version stuff:

``` python
In [2]: sympy.__version__
Out[2]: '0.7.6'
```

These look reasonable:

``` python
In [5]: latex(Symbol('x_a'))
Out[5]: 'x_{a}'

In [6]: latex(Symbol('x^a'))
Out[6]: 'x^{a}'
```

A bit strange coming from LaTeX, but fine:

``` python
In [7]: latex(Symbol('x^ab'))
Out[7]: 'x^{ab}'
In [8]: latex(Symbol('x^{a}b'))
Out[8]: 'x^{{a}b}'
```

and at least there's a workaround:

``` python
In [9]: latex(Symbol('{x^a}b'))
Out[9]: '{x^{a}b}'
```

and again odd, but self-consistent:

``` python
In [11]: latex(Symbol('(x_1)^a'))
Out[11]: '(x^{a}_{1)}'
```

But now what's going on?

``` python
In [12]: latex(Symbol('({x_1})^a'))
Out[12]: '({x^{a}_{1})}'

In [13]: latex(Symbol('{({x_1})}^a'))
Out[13]: '{({x^{a}_{1})}}'
```

How am I supposed to get the superscript on the parenthesis when it keeps moving somewhere else?

**Comment by moorepants** [comment]
Can you post what your desired output is? (and what you would expect the input to be)

Note, that our LaTeX printer tries to do a what the user might have intended. It doesn't convert full LaTeX symbol names directly to LaTeX.

**Comment by QuLogic** [comment]
As noted, I am aware that the parser tries to use the full name following a super/subscript (like in 7/8), but I also see there's a workaround using braces in 9.

But in 12/13, no amount of braces allow me to put the superscript on the closing parenthesis. It _always_ moves to the `x`. In LaTeX terms, I'd expect the output to be `(x_1)^a`, and if the extra braces are required, then it would be `{({x_{1}})}^{a}`.

Another way to look at it is the following:
```python
In [15]: latex(Symbol('(x)^a'))  # x has nothing.
Out[15]: '(x)^{a}'    # Superscript is on closing parenthesis.

In [16]: latex(Symbol('({x_1})^a'))   # x has a subscript
Out[16]: '({x^{a}_{1})}'    # Superscript 'a' moves to x!

In [17]: latex(Symbol('({x^1})^a'))  # x has a superscript.
Out[17]: '({x^{1}) a}'    # 'a' is no longer a superscript at all!
```

**Comment by moorepants** [comment]
You could try the `symbol_names` kwarg for the `latex()` function to enforce names of symbols. I think the trouble is that you are mixing exponents with superscripts and sympy doesn't have an easy way to tell what you are trying to do.

Note that you can see all of the desired behavior of our latex printer here:

https://github.com/sympy/sympy/blob/master/sympy/printing/tests/test_latex.py

In particular, the lines here:

https://github.com/sympy/sympy/blob/master/sympy/printing/tests/test_latex.py#L817

show some super/sub script behavior we've defined.

If you think the desired behavior is a poor choice you can suggest what you think the desired output should be for a given input.

It is a bit odd to think of a symbol containing parentheses, as you suggest: `(x_1)^a`. That seems more like an exponential operation on the symbol `x_1`. So I think the behavior from input `(x_1)^a` to output `x_1^a` is correct if you think of this as a symbol and not an operation.

**Comment by QuLogic** [comment]
I don't understand; I am passing this text to `Symbol`, therefore it is _the_ name. Why should there be any confusion about whether I meant the exponential operation?

**Comment by moorepants** [comment]
In SymPy, we have objects that represent mathematical symbols and mathematical expressions (among other things). The printers then try to give an appropriate representation of these objects. I could name a symbol something like:

`symbol = Symbol('(a**2+b**2)**(-1/2)')`

but that is not a common way to represent symbols. But it is a common way to represent expressions made up of symbols. It seems like my example is very similar to saying `symbol = Symbol('(x_1)^a')`. You are giving symbol a name that looks like an expression. The correct way to do this would be:

```python
a, x_1 = symbols('a, x_1')
latex((x_1)**a)
```

But if you actually want a symbol that has both a subscript and superscript you can use:

```python
latex(Symbol('x_1^a'))
```

But say that you have a special mathematical notation where you allow parentheses in symbol names, then you could do:

```python
x = Symbol('x')
latex(x, symbol_names={x: '(x_1)^a'})
```

**Comment by moorepants** [comment]
> Why should there be any confusion about whether I meant the exponential operation?

The confusion is because SymPy symbols expect the user to pass in "reasonable" names. Then the printers try to do reasonable things with that set of reasonable names. SymPy symbols don't really support very unusual names, e.g. those that look like expressions.

**Comment by QuLogic** [comment]
> The confusion is because SymPy symbols expect the user to pass in "reasonable" names.

If this is true, then there should be some documentation explaining what "reasonable" means. When I asked on gitter, @asmeurer told me there were _no_ restrictions on names.

**Comment by moorepants** [comment]
Aaron is right, there are no restrictions on names for Symbols (i.e. anything that can be held in a Python string). I should have said "The confusion is because SymPy printers expect the user to pass in "reasonable" names". Each printer can only "correctly" print some finite set of symbol names. If you want a printer to print special styles of symbol names then you have to create that printer. Our LaTeX printer currently deals with some subset of strings and it is defined by the tests I linked to above.

If you think that the LaTeX printer should behave in a way different than what it does, you can propose a change and we will all can evaluate it (PRs welcome). Maybe our LaTeX printer should be able to handle parentheses in a Symbol name in a different way. But, you haven't convinced me yet that it should. If you can define a set of inputs and outputs to the LaTeX printer that you think are desirable we can see if it is possible and desirable to make the necessary changes.

> then there should be some documentation explaining what "reasonable" means

The documentation may be weak here. We are always happy to accept pull requests with improvements to our documentation. Someone could start by reading the source code for the LaTeX printer and its unit tests and then write up some explanations of the current logic. There isn't currently a nice page about the LaTeX printer in the docs.

**Comment by oscargus** [comment]
This seems to have been fixed since this was filed:

```
In [25]: latex(Symbol('(x)^a'))
Out[25]: '(x)^{a}'

In [26]: latex(Symbol('({x_1})^a'))
Out[26]: '({x_1})^a'

In [27]: latex(Symbol('({x^1})^a'))
Out[27]: '({x^1})^a'
```

Feel free to reopen it if this is still a problem.
