### ISSUE TITLE
Use Dummy symbols in ComplexPlane

### ISSUE THREAD

**Issue by aktech** [sympy/sympy#9865]
We implemented `ComplexPlane` here #9463,  Currently we defined symbols internally as:
```
x, y, r, theta = symbols('x, y, r, theta')
```
The above symbols should be changed to Dummy symbols.

**Comment by gxyd** [comment]
@aktech  I agree that it is better to use `Dummy symbols` compared to `symbols` in internal calls. Is there is any specific reason(in this case) why this is necessary to be changed?

**Comment by aktech** [comment]
I think it's a bad practice in General. People may confuse these symbols with the defined symbols, in their code.
