### ISSUE TITLE
Rename ComplexPlane to ComplexRegion

### ISSUE THREAD

**Issue by aktech** [sympy/sympy#9869]
See https://github.com/sympy/sympy/pull/9500#discussion_r37886701

The complex plane is the whole complex plane, whereas an instance of `ComplexPlane` is generally not.

**Comment by asmeurer** [comment]
Should be done before the release so we don't have to deprecate things.

**Comment by aktech** [comment]
> Should be done before the release so we don't have to deprecate things.

Yeah, will do it, if no one does.

**Comment by gxyd** [comment]
@aktech  I am on it. I thought you were not around. So i started.

**Comment by aktech** [comment]
@gxyd 
Cool! Go ahead. :+1:

**Comment by preetskhalsa97** [comment]
I would like to fix this bug. Can someone please get me started?
Thanks.

**Comment by leosartaj** [comment]
@preetskhalsa97 this was fixed #9873. I suggest you to first look at https://github.com/sympy/sympy/wiki/Development-workflow. Then you should pick up an [easy to fix](https://github.com/sympy/sympy/labels/Easy%20to%20Fix) issue to get started.
