### ISSUE TITLE
init_printing(use_latex='mathjax') not working in ipython notebook 4

### ISSUE THREAD

**Issue by titas99** [sympy/sympy#9888]
Hi,

Previously I used ipython notebook 3, where init_printing(use_latex='mathjax') worked perfectly for sympy. But recently I upgraded my system, and now in ipython notebook 4 it is not working anymore. I posted this issue in ipython threads, but they suggested me to report here, as sympy might not recognize new ipython notebook 4. 

Any help!!!!!! I am using sympy 0.7.6!!!!

**Comment by moorepants** [comment]
We are working on a bug fix release for this, see: https://github.com/sympy/sympy/pull/9883

**Comment by titas99** [comment]
Thank you....
