### ISSUE TITLE
Subs RuntimeError: maximum recursion depth exceeded while calling a Python object

### ISSUE THREAD

**Issue by proy87** [sympy/sympy#9895]
>>> a=oo**(-1/t)
>>> a.subs(t,0)

**Comment by gxyd** [comment]
I guess this has been fixed in master. This is what i get in master.
```
>>> a = oo**(-1/t)
>>> a.subs(t,0)
nan
```

**Comment by gxyd** [comment]
I checked using `git bisect`, indicating that this was fixed in #9493 .
