### ISSUE TITLE
Nice to have latex printing back (0.7.6.1) but Matrix([]) returns error

### ISSUE THREAD

**Issue by juanklopper** [sympy/sympy#9896]
Everything (latex printing as output) seems to be back to normal as far as 0.7.6.1 and Jupyter is concerned (somehow just SLOW), except Matrix() which returns an error: RuntimeError: latex program is not installed.

**Comment by thisch** [comment]
Can you provide a minimal example?

**Comment by juanklopper** [comment]
Please close.  Seems to work now!  Thanks.
![sympy](https://cloud.githubusercontent.com/assets/8681335/10043526/11419b52-61f4-11e5-83dd-5be20a9aedfb.png)
