### ISSUE TITLE
Python 3.5 support

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#9927]
We need to run the tests in Python 3.5 in Travis, and fix any bugs that there might be.

**Comment by yashmehrotra** [comment]
@asmeurer I ran a changed `.travis.yml` file and replaced `python 3.4` with `python 3.5`. The failed test summary:
 
1. `sympy/doc/src/gotchas.rst` throws a `RecursionError` instead of `RuntimeError` with the same error message.
2.  https://github.com/sympy/sympy/blob/master/sympy/core/tests/test_sympify.py#L242 throws a `TypeError` which I will look into in detail.
3. There are many failures with `Python 3.5` with the environment variables `TEST_DOCTESTS="true"` and `FASTCACHE="false"`

I would be adding the fixed test cases in PR #9944

**Comment by asmeurer** [comment]
Great, we need to fix those errors. I think at least the caching one was discovered to be related to a bug in Python 3.5, but it could also end up being a bug in SymPy as well.

We also should figure out if we can reduce the number of entries in the Travis matrix, as adding another five for Python 3.5 would slow the time for Travis tests to finish down even more.

**Comment by VinaySingh035** [comment]
do we really need to check the working of all the functions in all the versions of Python??

**Comment by asmeurer** [comment]
All the supported versions, yes. It's not uncommon for an issue to come up in only one version of Python, and for new issues to come up with new Python versions (for instance, because we used some undocumented API in the standard library that was changed).

**Comment by VinaySingh035** [comment]
as i'm using python 2.7.6.

while using some of the functions it doesn't shows the result in the usual format.
so, do we need to consider that too for improvement.

**Comment by asmeurer** [comment]
If it's causing a test to fail, then yes, the test should be fixed so that it passes.

**Comment by SpeedyiiiTH** [comment]
its not about its failing a test or something like that.
I was going thorough the tutorial, and found that there its mentioned that if I give
Eq(x**2,0)
it should give x**2==0

but in my system its showing 
Eq(x**2,0)

and gives same result for all the Eq usage.
Is this need to be improved or its all right??

**Comment by asmeurer** [comment]
That's a difference between the development version and the last release (the tutorial is based on the last release).

**Comment by SpeedyiiiTH** [comment]
ok then

by the way as per this issue is concerned.
what do we really need to do here, please tell me more about it as i'm a newbie.

thanks.

**Comment by asmeurer** [comment]
The issue here is to:

- Run the tests in Python 3.5 and fix any failures.
- Add Python 3.5 to .travis.yml so that Travis CI runs them

**Comment by SpeedyiiiTH** [comment]
ok let me first get my environment suitable for the purpose,
then I'll like to try it out.

**Comment by opoplawski** [comment]
sympy builds in Fedora are failing now with the switch to python 3.5.  Build log is here: https://kojipkgs.fedoraproject.org//work/tasks/8924/11858924/build.log

**Comment by asmeurer** [comment]
There is work to fix all these issues at https://github.com/sympy/sympy/pull/10084.
