### ISSUE TITLE
boolalg.py:is_cnf fails when it should pass

### ISSUE THREAD

**Issue by jdcasi** [sympy/sympy#9949]
- If i create a simple conjunction of two literals, which by definition is in conjunctive normal form, the boolalg.py:is_cnf function incorrectly returns false.
- Additionally, if I create I an expression in disjunctive normal form, and then call boolalg.py:to_cnf on it. It is correctly put in conjunctive normal form, but boolalg.py:is_cnf still returns false.

Below is sample code that demonstrates both of these issues. 

``` Python
from sympy import S
from sympy.logic import boolalg
from sympy import srepr

literal1 = S("X>2")
literal2 = S("X<4")
literal3 = S("Y>-5")

# Conjunction by itself, which should be in CNF form
conjunction_clause = boolalg.And(literal1, literal2)

# Disjunction of a conjunction and literal, should be in DNF
dnf_exp = boolalg.Or(literal3, conjunction_clause)

print(srepr(conjunction_clause))
print(srepr(dnf_exp))

# Expression already in CNF, but is_cnf fails
simple_is_cnf_test = boolalg.is_cnf(conjunction_clause)
print("simple_is_cnf_test", simple_is_cnf_test)

# Expression in DNF
# Expression correctly put in CNF
print("DNF Expression, turned to CNF: \n\t", boolalg.to_cnf(dnf_exp))
dnf_to_cnf_test = boolalg.is_cnf(boolalg.to_cnf(dnf_exp))

assert((simple_is_cnf_test or dnf_to_cnf_test),
                "2 expression in CNF, but is_cnf returns false.")
```

**Comment by Newman101** [comment]
Hi. I attempted to replicate this and got the following: 

<input>:1: SyntaxWarning: assertion is always true, perhaps remove parentheses?
<input>:1: SyntaxWarning: assertion is always true, perhaps remove parentheses?
<input>:1: SyntaxWarning: assertion is always true, perhaps remove parentheses?
<input>:1: SyntaxWarning: assertion is always true, perhaps remove parentheses?
<input>:1: SyntaxWarning: assertion is always true, perhaps remove parentheses?
<input>:1: SyntaxWarning: assertion is always true, perhaps remove parentheses?
<ipython-input-20-6914e05aab57>:1: SyntaxWarning: assertion is always true, perhaps remove parentheses?
  assert((simple_is_cnf_test or dnf_to_cnf_test),

Is this still an issue?

**Comment by jdcasi** [comment]
Sorry that was a mistake I made, when converting from a unittest framework to a simple assert.  If you change the assertion line of code to the following line, I believe the assertion will fail.
```Python
assert(simple_is_cnf_test or dnf_to_cnf_test)
```

**Comment by Newman101** [comment]
Ok, thanks for verification. I'll have a look soon.

**Comment by jdcasi** [comment]
I just upgraded to sympy-0.7.6.1, the assertion is still hit for me.

-Thank you.

**Comment by smichr** [comment]
If relational literals are replaced with symbols this works:
```python
>>> dnf_exp
(Y > -5) | ((X > 2) & (X < 4))
>>> cnf_exp = to_cnf(dnf_exp)
>>> is_cnf(cnf_exp)
False

>>> cnf_exp.atoms(Relational)
{X > 2, Y > -5, X < 4}
>>> is_cnf(cnf_exp.subs(dict(zip(_, numbered_symbols('l', cls=Dummy)))))
True
```

Perhaps the following diff is sufficient to solve this:
```diff
diff --git a/sympy/logic/boolalg.py b/sympy/logic/boolalg.py
index dd734ce..dd1f61c 100644
--- a/sympy/logic/boolalg.py
+++ b/sympy/logic/boolalg.py
@@ -1916,6 +1916,8 @@ def is_a_literal(lit):
             return True
         elif lit.is_Atom:
             return True
+        elif lit.is_Relational and all(map(is_a_literal, lit.args)):
+            return True
         return False

     vals = function1.make_args(expr) if isinstance(expr, function1) else [expr]
```
