### ISSUE TITLE
Create requirements.txt file

### ISSUE THREAD

**Issue by aktech** [sympy/sympy#9955]
Here are some:
# Required
- python 2.6-2.7, 3.2-3.5
- mpmath
# Recommended
- fastcache
- ipython, ipython notebook, ipython qtconsole
# Plotting
- matplotlib
# Code generation
- cython
- theano
- numpy
# Docs
- graphviz
- inkscape
- texlive
- texlive-xetex
- texlive-fonts-recommended
- texlive-latex-extra
- lmodern
- librsvg2-bin
- imagemagick
- docbook2x

**Comment by aktech** [comment]
ping @ethcelon

**Comment by moorepants** [comment]
Why is this needed? A requirements.txt file is typically used to set a specific environment, i.e. exact dependency version numbers. SymPy is a library that should work with a range of dependency versions.

It may be more useful to have sympy conda builds and distutils options that pull in and check for all of the optional deps.

**Comment by aktech** [comment]
@moorepants 

The idea was to write down all that's required in a single file.
Like `mpmath` is a dependency. There are few dependencies for building doc such as:
`sudo apt-get install --no-install-recommends graphviz inkscape texlive texlive-xetex texlive-fonts-recommended texlive-latex-extra lmodern librsvg2-bin imagemagick docbook2x;`

**Comment by moorepants** [comment]
Note that a `requirements.txt` file is specific to pip which is Python centric.

But we should have some list of all the dependencies. There are few layers too: python deps, conda installable deps (cross platform) and deps that have different install instructions for different OSs. I'll start a list that people can collaboratively edit in the first comment on this issue.

**Comment by aktech** [comment]
> I'll start a list that people can collaboratively edit in the first comment on this issue.

Good Idea! :+1:

**Comment by asmeurer** [comment]
There is https://github.com/sympy/sympy/wiki/Dependencies, but it's out of date. We could just update that, and reference it (or move it to the docs if it seems useful).

**Comment by souravsingh** [comment]
I can work on the issue

**Comment by moorepants** [comment]
@souravsingh Thanks, if you can update the dependencies page on the wiki that would be great, but there should probably be something in the documentation that details this too, that we keep up to date with the changing code.

There seems to be a lot of request for better dep management with conda that would be useful here: see https://github.com/conda/conda/issues/1696

For the setup.py file we could also introduce the optional packages so you could do things like:

`pip install sympy[codegen]`

**Comment by moorepants** [comment]
This is a relevant issue that should be read:

https://github.com/sympy/sympy/issues/5259

**Comment by moorepants** [comment]
Also relevant to read: https://github.com/sympy/sympy/issues/7339

**Comment by souravsingh** [comment]
Thanks a lot @moorepants

**Comment by moorepants** [comment]
A conda metapackage that has all these deps would be useful too.

**Comment by mohitiitb** [comment]
Is this issue still open??

**Comment by moorepants** [comment]
I'm closing this. I think the wiki page is sufficient. We don't need a requirements.txt.
