### ISSUE TITLE
Union(Interval(-oo, oo), FiniteSet(1)) not evaluated

### ISSUE THREAD

**Issue by gxyd** [sympy/sympy#9956]
```
>>> Union(Interval(-oo, oo), FiniteSet(1))
(-∞, ∞) ∪ {1}       # this should return (-∞, ∞) i guess
```

Can some one please verify the validity of issue?

**Comment by jksuom** [comment]
I think it is valid. It seems to be caused by the confusion of booleans in ``FiniteSet._union`` on [this line](https://github.com/sympy/sympy/blob/master/sympy/sets/sets.py#L1806). (``Interval(-oo, oo).contains(1)`` is ``True`` but not ``true``.)

**Comment by gxyd** [comment]
In these situations why not use `==` instead of `is`? (I know the difference between `is` and `==`). But would that be any of problem.

**Comment by gxyd** [comment]
> I think it is valid. It seems to be caused by the confusion of booleans in FiniteSet._union on this line. 

I also confirmed using `git-bisect`, the same conclusion.

**Comment by jksuom** [comment]
Perhaps ``other.contains(x)`` would suffice.

**Comment by jksuom** [comment]
This is from PEP 8:


Don't compare boolean values to True or False using == .

Yes:   if greeting:
No:    if greeting == True:
Worse: if greeting is True:

**Comment by gxyd** [comment]
```
>>> if any(Interval(1, 2).contains(x) == True for x in [y, z]):
           print('yes')

None                    # expected behavior
```

while 
```
>>> if any(Interval(1, 2).contains(x) for x in [y, z]):
           print('yes')

'yes'
```
I know why this is happening, i had the same situation in one of previous PR's. Do you think we should go with `==`?.

**Comment by jksuom** [comment]
The docstring of ``contains`` says:
``Returns True if 'other' is contained in 'self' as an element.``
This looks to me as if saying that we can expect a boolean value or possibly None.

However, some internal ``_contains`` functions return boolean functions or true or false (singletons, I think). I have no clear idea about what should be done.

**Comment by gxyd** [comment]
.contains is supposed to return 3-valued logic `True`, `False` or `None`. This is different from `in` operator, which uses two valued-logic `True`, `False` and `TypeError` for unknown. 
> This looks to me as if saying that we can expect a boolean value or possibly None.

So i this is true what you said.

I am quoting @asmeurer here what he said in the `is_convergent` PR comment for `is_convergent()`.
> S.true should only be used in places where a general symbolic boolean could be returned. Also, since this uses three-valued logic (with None), it should use bool, since S.true only represents two-valued logic.

**Comment by leosartaj** [comment]
In the example given by @gxyd ``contains`` returns an unevaluated ``And`` because bound on ``x`` is not known. ``any`` returns ``True`` in this case. I think we should go with ``==`` here so that there is confusion.
