### ISSUE TITLE
Raise an error if matplotlib and latex are not installed when trying to render a png

### ISSUE THREAD

**Issue by moorepants** [sympy/sympy#9962]
If you enable printing in qtconsole or ipython notebook and you have neither matplotlib or latex (or mathjax) installed you'll get empty pngs, e.g.:

![ipython_011](https://cloud.githubusercontent.com/assets/276007/10271647/c86c1122-6ac8-11e5-9133-17f6803ffcff.png)

`from IPython.lib.latextools import latex_to_png` doesn't seem to raise and error if neither are available.

**Comment by moorepants** [comment]
Maybe this should be: print using string or pretty printing if they are not installed.

**Comment by jksuom** [comment]
notebook: Newer versions of notebook load MathJax from the net. It does not matter if neither matplotlib nor latex is available. It will suffice to provide IPython with a latex representation of the output.

qtconsole: If matplotlib and latex are not installed, png-data won't be available. If a latex string is provided, qtconsole will then try to use matplotlib. It will not fall back to pretty printing after getting None. (I think this is a bug.)

So it seems that, if matplotlib and latex are not installed, we should provide notebook with a latex string but let qtconsole only have the (pretty) string. However, there is a problem. Quoting from [this thread](http://stackoverflow.com/questions/15411967/how-can-i-check-if-code-is-executed-in-the-ipython-notebook):
> We do our best in IPython prevent the kernel from knowing to which kind of frontend is connected, and actually you can even have a kernel connected to differents frontend at the same time.

This leaves the question: which (common) default should be chosen for notebook and qtconsole when both matplotlib and latex are missing, ``use_latex='mathjax'`` or ``use_latex=False``?

**Comment by moorepants** [comment]
> notebook: Newer versions of notebook load MathJax from the net. It does not matter if neither matplotlib nor latex is available. It will suffice to provide IPython with a latex representation of the output.

I don't necessarily agree with this. I'd like it to "work" without an internet connection too.

> qtconsole: If matplotlib and latex are not installed, png-data won't be available. If a latex string is provided, qtconsole will then try to use matplotlib. It will not fall back to pretty printing after getting None. (I think this is a bug.)

Agreed.

> This leaves the question: which (common) default should be chosen for notebook and qtconsole when both matplotlib and latex are missing, use_latex='mathjax' or use_latex=False?

Maybe pretty print? But is it possible everything isn't installed for that to work too? Maybe it should just be the simple string rep.

**Comment by jksuom** [comment]
> I'd like it to "work" without an internet connection too.

I was just referring to how the designers of notebook seem to have planned it. An alternative is a local installation of MathJax. But that is big, of course...

As to the default, I think text/plain should perhaps be taken even if MathJax could give nicer output in notebook. Anyway, a notebook user will always have the option of running ``init_printing(use_latex='mathjax')``.

**Comment by jksuom** [comment]
A possible plan for IPython notebook and qtconsole printing defaults (when ``use_latex=None``).

- If both latex and dvipng are available, set ``use_latex=True`` to enable png-formatting in SymPy.

- Else if matplotlib is available, set ``use_latex='matplotlib'`` to enable png-formatting in IPython.

- Else set ``use_latex=False`` to fall back to text/plain-formatting in SymPy. (Always configured, ``pretty`` by default. Custom ``pretty_printer`` can be set.)

These defaults may always be overridden by setting ``use_latex``. For example, notebook users can choose ``mathjax``.

**Comment by asmeurer** [comment]
The upstream bug in the qtconsole has been fixed. See also the related https://github.com/jupyter/qtconsole/pull/95.
