### ISSUE TITLE
Pretty Printing (Latex/Mathjax) doesn't work

### ISSUE THREAD

**Issue by Stefan-Code** [sympy/sympy#9964]
Hi,
I'm using 
```
 ./pip freeze | egrep "jupyter|notebook|sympy|ipython"
ipython==4.0.0
ipython-genutils==0.1.0
jupyter==1.0.0
jupyter-client==4.0.0
jupyter-console==4.0.2
jupyter-core==4.0.6
notebook==4.0.5
sympy==0.7.6 / 0.7.6.1 (see below)
```
from a anaconda install (Python 3) on `Linux user 3.13.0-37-generic #64-Ubuntu SMP Mon Sep 22 21:28:38 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux`
When running this in an ipython notebook:
```
from sympy import *

init_printing(use_latex=True)
# init_printing(use_latex="mathjax") # not working either

x = Symbol('x')

x**2
# prints x**2 in text form, nothing pretty about it

pprint(x**2)

# pprint 0.7.6: nothing at all 0.7.6.1: prints with unicode
```
Pretty printing doesn't seem to work at all. Also I don't get any warning/error messages whatsoever. 
Mathjax is installed locally using:

```from IPython.external.mathjax import install_mathjax
install_mathjax()```
Any idea how to get it to work?

EDIT: Originally tried it with sympy 0.7.6. After upgrading to 0.7.6.1 using pprint shows unicode output but not Latex/Mathjax

**Comment by account-login** [comment]
I encountered the same problem. Clearing the cookie fixed the problem. (https://groups.google.com/forum/#!topic/jupyter/XsiE82A8r9I)

**Comment by Stefan-Code** [comment]
Thank you for your answer. I just tried it again today and it seems to work now!
