### ISSUE TITLE
Smoothstep function

### ISSUE THREAD

**Issue by Nedaaaa** [sympy/sympy#9966]
I am solving a problem and I need to ramp up an external force to its maximum amount during an interval and then it is constant but both the maximum force and the time interval are really small ( 4.91e-9 and 2e-7 respectively). I need a smooth transition at the end of the interval when the force is getting constant. 
I used some transition function using tanh() and polynomial functions but actually they did not work right in my case because my numbers are too small.

Can anyone tell me how can I do this? Thanks

**Comment by jksuom** [comment]
Perhaps you could use symbols for the maximum force and the time interval and substitute the values only after solving the problem symbolically.

**Comment by Nedaaaa** [comment]
@jksuom I can not solve it symbolically because I have a numerical algorithm and I need to use the force in each step!

**Comment by jksuom** [comment]
Maybe SymPy is not the best library for such a problem. Did you consider others such as NumPy?

Another possibility might be scaling the problem differently. (Essentially using other units of force and time.)

**Comment by zanzibar7** [comment]
```tanh((x-shift)/scale)``` should work well as long as you choose shift and scale to match your situation.  Alternatively, you can use  ```Piecewise``` to construct whatever you want.  But this does sound more like a numerical methods issue, and not an issue with sympy.

**Comment by Nedaaaa** [comment]
@jksuom Actually I do not know exactly which library is appropriate in this case!

**Comment by Nedaaaa** [comment]
@zanzibar7 I exactly use this function(tanh) but because all the numbers are small it did not work and it always return zero!

**Comment by oscarbenjamin** [comment]
@Nedaaaa did you solve your problem? I'm looking at this open issue and it doesn't seem that there is anything about SymPy to be fixed...

**Comment by Nedaaaa** [comment]
Yes, it’s solved. You can close it.

Thank you,
Neda

**Comment by oscarbenjamin** [comment]
Thanks for getting back!
