### ISSUE TITLE
Probability of normal random variable below upper bound yields a TypeError for some values

### ISSUE THREAD

**Issue by joyofdata** [sympy/sympy#9972]
```
from sympy import *
from sympy.stats import *
X = Normal("X",0,1)

P(X<1.3)
# erf(0.65*sqrt(2))/2 + erf(+inf*sqrt(2))/2

P(X<1.4)
# TypeError: cannot determine truth value of -oo < -inf

P(X<1.5)
# TypeError: cannot determine truth value of -oo < -inf

P(X<1.6)
# TypeError: cannot determine truth value of -oo < -inf

P(X<1.7)
# erf(0.85*sqrt(2))/2 + erf(+inf*sqrt(2))/2
```

- Python 3.4.3
- SymPy 0.7.6.1

**Comment by gxyd** [comment]
```
>>> x = Symbol('x')
>>> X = Exponential('X', 3)
>>> stats.P(X < x)
⎧    0      for x ≤ 0
⎪                    
⎨     -3⋅x           
⎪1 - ℯ      for x > 0
⎩                                  # is this the expected answer?
```

Is this the expected answer? Or just a non-piecewise function `1 - exp(-3*x)`?

**Comment by joyofdata** [comment]
I don't understand your question. A valid expression `P(X<1.4)` leads to an error. As far as I can tell this is no good and it seems to be rather erratic given that for some upper bounds the expression works and for some it doesn't.

I guess the propper answer for `P(X<1.4)` **in line** with what SymPy returns for `P(X<1.3)` and `P(X<1.7)` is `erf(0.7*sqrt(2))/2 + erf(+inf*sqrt(2))/2` - right?

**Comment by gxyd** [comment]
First of all sorry i commented on the wrong issue. Please comment on issue #9770

**Comment by Upabjojr** [comment]
This has been solved:

https://github.com/sympy/sympy/pull/9199

@joyofdata please use latest master branch before reporting issues, not latest version.

**Comment by Upabjojr** [comment]
Close this issue, please.

**Comment by joyofdata** [comment]
Makes sense (y)
