### ISSUE TITLE
Error for the calculation of the radius of curvate of BeamParameter in physics.optics.

### ISSUE THREAD

**Issue by MarkSuperman** [sympy/sympy#9974]
According to the source code the calculation of the radius of curvate for BeamParameter is:
    
@property
    def radius(self):
        return self.z*(1 + (self.z/self.z_r)**2)

As it can be seen here (https://en.wikipedia.org/wiki/Gaussian_beam#Radius_of_curvature), the correct calculation is:

return self.z*(1 + (self.z_r/self.z)**2)

**Comment by jksuom** [comment]
Yes, you are right. It has been taken care of in #9875.

**Comment by leosartaj** [comment]
Looks like this is resolved. Closing.
