### ISSUE TITLE
simplification of Unions of ComplexRegions

### ISSUE THREAD

**Issue by gxyd** [sympy/sympy#9980]
```
>>> c1 = ComplexRegion(Interval(1, 2)*Interval(2, 3))
>>> c2 = ComplexRegion(Interval(1, 5)*Interval(1, 3))
>>> simplify(Union(c1, c2))
---------------------------------------------------------------------------
UnboundLocalError                         Traceback (most recent call last)
<ipython-input-20-c14828895520> in <module>()
----> 1 simplify(Union(c1, c2))

/home/gxyd/Public/sympy/sympy/simplify/simplify.py in simplify(expr, ratio, measure, fu)
    516     if not isinstance(expr, (Add, Mul, Pow, ExpBase)):
    517         return expr.func(*[simplify(x, ratio=ratio, measure=measure, fu=fu)
--> 518                          for x in expr.args])
    519 
    520     # TODO: Apply different strategies, considering expression pattern:

/home/gxyd/Public/sympy/sympy/sets/fancysets.py in __new__(cls, sets, polar)
    673                                    r*(cos(theta) + I*sin(theta))),
    674                                    sets)
--> 675         return obj
    676 
    677     @property

UnboundLocalError: local variable 'obj' referenced before assignment
```

**Comment by jksuom** [comment]
``simplify`` operates on an expression by replacing its arguments with simplified versions (on line 517).
This works well on expressions having the invariance property ``expr == expr.func(*expr.args)`` ([Key Invariant](http://docs.sympy.org/latest/tutorial/manipulation.html#args)).

In this case we have
```
>>> R = Union(c1, c2)
>>> R.func
<class 'sympy.sets.fancysets.ComplexRegion'>
>>> R.args
(Lambda((_x, _y), _x + _y*I), [1, 2] x [2, 3] U [1, 5] x [1, 3]
>>> R.func(*R.args)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "sympy/sets/fancysets.py", line 675, in __new__
    return obj
UnboundLocalError: local variable 'obj' referenced before assignment
```
``ComplexRegion`` expect sets as its arguments. It is confused by the lambda expression. Hence it does not construct the object ``obj``.

Perhaps it would be possible to omit the lambda expression from the arguments of ``ComplexRegion``. Anyway, it is always the same, and can be constructed whenever needed. Only the latter part of the arguments is significant.

**Comment by aktech** [comment]
We could probably simplify the output API as:

```
In [4]: ComplexRegion(Interval(1, 2)*Interval(2, 3))
Out[4]: ComplexRegion(_x + _y*I, [1, 2] x [2, 3])
```
rather than this:

```
In [4]: ComplexRegion(Interval(1, 2)*Interval(2, 3))
Out[4]: ComplexRegion(Lambda((_x, _y), _x + _y*I), [1, 2] x [2, 3])
```

**Comment by jksuom** [comment]
It seems to lead to the same error.
```
>>> x = Dummy('x')
>>> y = Dummy('y')
>>> ComplexRegion(x + I*y, R.args[1])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "sympy/sets/fancysets.py", line 675, in __new__
    return obj
UnboundLocalError: local variable 'obj' referenced before assignment
```

**Comment by aktech** [comment]
Btw, [that](https://github.com/sympy/sympy/issues/9980#issuecomment-147755181) was a general comment. I think simplify probably won't work on `ComplexRegion`, that way.

**Comment by jksuom** [comment]
I think the issue is that ``ComplexRegion`` does not satisfy the Key Invariant. It should have the argument that is needed for its reconstruction (``sets``). The lambda expression is not necessary as it is known in advance.
```
>>> ComplexRegion(R.args[1]) == R
True
```
There should be no compelling reason why ``simplify`` could not work on ``ComplexRegion``.

**Comment by aktech** [comment]
> ComplexRegion does not satisfy the Key Invariant.

Yeah.

> The lambda expression is not necessary as it is known in advance.

I used the lambda expression while writing `ComplexRegion` just for representational purpose. I agree with you that it is redundant and we can probably discard it. We can simply represent `x + iy` and `r(cos(θ) + isin(θ))` in printing.

The following output API, should work(?) probably:

```
In [4]: ComplexRegion(Interval(1, 2)*Interval(2, 3))
Out[4]: ComplexRegion([1, 2] x [2, 3])

In [4]: ComplexRegion(Interval(0, 1)*Interval(0, 2*pi), polar=True)
Out[4]: ComplexRegion([0, 1] x [0, 2*pi], polar)
```

(If `init_printing` is called, the current printing output would be used)

**Comment by hargup** [comment]
I agree with @aktech and we should drop the lambda expression while printing a `ComplexRegion`.

**Comment by Newman101** [comment]
I agree with @aktech too, it probably should be dropped.

**Comment by Newman101** [comment]
Question follows: Class ImageSet has a __new__ method which is being called: 

```Python

    from sympy import cos, sin
            obj = ImageSet.__new__(cls, Lambda((r, theta),
                                   r*(cos(theta) + I*sin(theta))),
                                   sets)
```

And...

```Python

    def __new__(cls, lamda, base_set):
        return Basic.__new__(cls, lamda, base_set)

```

Where:

```Python
    lamda = property(lambda self: self.args[0])
```

Basically, should Lambda expression be removed from entire ImageSet class?

**Comment by asmeurer** [comment]
@aktech @hargup what should be done here? 

It's possible to have a class that can be constructed in multiple ways, as long as one of those ways corresponds to the .args (and as long as it is unambiguous). 

ComplexRegion does seem odd to me, though. Why is it needed instead of just ImageSet on S.Complexes?  If the whole point is just to represent rectangular or polar regions, and nothing else, it would be better to have two classes (but again, why not just use ImageSet, and maybe a convenience function for polar regions?).

**Comment by aktech** [comment]
> ComplexRegion does seem odd to me, though. Why is it needed instead of just ImageSet on S.Complexes?

I don't think currently ImageSet is able to perform all the set operations on Complex Sets.

Please note that it's not just about representing rectangular or polar regions, we should be able to perform all the set operations in argand plane, & `ComplexRegion` is a good candidate for that.
To be concise: `ComplexRegion` is analogous to `Interval` *and* `S.Complexes` is analogous to `S.Reals` in complex & real domains respectively.

**Comment by asmeurer** [comment]
What other kinds of regions would you have (other than those that can be constructed from Union and Intersection of rectangular and polar regions)? 

I'm unclear what you think should be done here.
