### ISSUE TITLE
Integral(f(x), f(x)) doesn't work

### ISSUE THREAD

**Issue by mcho421** [sympy/sympy#9984]
Calling Integral() or integrate() with a function instead of an integration variable doesn't work:

```
from sympy import *
init_session()
Integral(f(x), f(x))
```

This raises `ValueError: Invalid limits given: (f(x),)`

I was expecting this to work since `Derivative(f(x), f(x))` works.

**Comment by Newman101** [comment]
Error replicated. Stack trace here, might be useful. 

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-3-ab1e69fdc24c> in <module>()
----> 1 Integral(f(x), f(x))

/home/jremes/Projects/Python/sympy/sympy/integrals/integrals.py in __new__(cls, function, *symbols, **assumptions)
     72             return function._eval_Integral(*symbols, **assumptions)
     73 
---> 74         obj = AddWithLimits.__new__(cls, function, *symbols, **assumptions)
     75         return obj
     76 

/home/jremes/Projects/Python/sympy/sympy/concrete/expr_with_limits.py in __new__(cls, function, *symbols, **assumptions)
    366 
    367         if symbols:
--> 368             limits, orientation = _process_limits(*symbols)
    369         else:
    370             # symbol not provided -- we can still try to compute a general form

/home/jremes/Projects/Python/sympy/sympy/concrete/expr_with_limits.py in _process_limits(*symbols)
     67                     continue
     68 
---> 69         raise ValueError('Invalid limits given: %s' % str(symbols))
     70 
     71     return limits, orientation

ValueError: Invalid limits given: (f(x),)

**Comment by zanzibar7** [comment]
What are these supposed to mean?  I don't think they are well-defined.  When I've seen these kinds of things, they have been in functional calculus, which is infinite dimensional and involves lots of linear operators.

**Comment by oscarbenjamin** [comment]
This seems to work fine now:
```julia
In [25]: Integral(f(x), f(x))                                                                                                                  
Out[25]: 
⌠             
⎮ f(x) d(f(x))
⌡             

In [26]: Integral(f(x), f(x)).doit()                                                                                                           
Out[26]: 
 2   
f (x)
─────
  2  
```
