### ISSUE TITLE
wrong diff

### ISSUE THREAD

**Issue by wenaaa** [sympy/sympy#9994]
I use Python 2.7.9
trying simple diff

input: 'diff((-1/5)*cos(t)**5)'

output: '5*sin(t)*cos(t)**4'

which is obviously wrong
on [sympy live](http://live.sympy.org/) it works OK

**Comment by leosartaj** [comment]
This works correctly in the current master.

```
>>> diff((-1/5)*cos(t)**5, t)
1.0*sin(t)*cos(t)**4
```
